Zapdos: crane/src/actions/AddReactions.C File Reference
AddReactions.C File Reference
Functions
registerMooseAction ("CraneApp", AddReactions, "add_aux_variable")
registerMooseAction ("CraneApp", AddReactions, "add_aux_kernel")
registerMooseAction ("CraneApp", AddReactions, "add_material")
registerMooseAction ("CraneApp", AddReactions, "add_kernel")
registerMooseAction ("CraneApp", AddReactions, "add_function")
static std::string & ltrim (std::string &s)
static std::string & rtrim (std::string &s)
static std::string trim (std::string &s)
Function Documentation
ltrim()
static std::string & ltrim (std::string & s) inline static
Definition at line 61 of file AddReactions.C.
{
  s.erase(s.begin(), find_if_not(s.begin(), s.end(), [](int c) { return isspace(c); }));
  return s;
}
Referenced by trim().
registerMooseAction() [1/5]
registerMooseAction ("CraneApp" , AddReactions , "add_aux_kernel")
registerMooseAction() [2/5]
registerMooseAction ("CraneApp" , AddReactions , "add_aux_variable")
registerMooseAction() [3/5]
registerMooseAction ("CraneApp" , AddReactions , "add_function")
registerMooseAction() [4/5]
registerMooseAction ("CraneApp" , AddReactions , "add_kernel")
registerMooseAction() [5/5]
registerMooseAction ("CraneApp" , AddReactions , "add_material")
rtrim()
static std::string & rtrim (std::string & s) inline static
Definition at line 68 of file AddReactions.C.
{
  s.erase(find_if_not(s.rbegin(), s.rend(), [](int c) { return isspace(c); }).base(), s.end());
  return s;
}
Referenced by trim().
trim()
static std::string trim (std::string & s) inline static
Definition at line 75 of file AddReactions.C.
{
  return ltrim(rtrim(s));
}
Referenced by ChemicalReactions::ChemicalReactions(), and ChemicalReactionsBase::ChemicalReactionsBase().