Zapdos: moose/framework/src/base/Assembly.C File Reference
Assembly.C File Reference
Functions
template<typename P , typename C >
void coordTransformFactor (const SubProblem &s, const SubdomainID sub_id, const P &point, C &factor, const SubdomainID neighbor_sub_id)
Computes a conversion multiplier for use when computing integraals for the current coordinate system type.
template<typename P , typename C >
void coordTransformFactor (const MooseMesh &mesh, const SubdomainID sub_id, const P &point, C &factor, const SubdomainID libmesh_dbg_var(neighbor_sub_id))
template void coordTransformFactor< Point, Real > (const SubProblem &s, SubdomainID sub_id, const Point &point, Real &factor, SubdomainID neighbor_sub_id)
template void coordTransformFactor< ADPoint, ADReal > (const SubProblem &s, SubdomainID sub_id, const ADPoint &point, ADReal &factor, SubdomainID neighbor_sub_id)
template void coordTransformFactor< Point, Real > (const MooseMesh &mesh, SubdomainID sub_id, const Point &point, Real &factor, SubdomainID neighbor_sub_id)
template void coordTransformFactor< ADPoint, ADReal > (const MooseMesh &mesh, SubdomainID sub_id, const ADPoint &point, ADReal &factor, SubdomainID neighbor_sub_id)
Function Documentation
coordTransformFactor() [1/2]
template<typename P , typename C > void coordTransformFactor (const MooseMesh & mesh, const SubdomainID sub_id, const P & point, C & factor, const SubdomainID libmesh_dbg_varneighbor_sub_id)
Definition at line 50 of file Assembly.C.
{
  mooseAssert(neighbor_sub_id != libMesh::Elem::invalid_subdomain_id
                  ? mesh.getCoordSystem(sub_id) == mesh.getCoordSystem(neighbor_sub_id)
                  : true,
              "Coordinate systems must be the same between element and neighbor");
  const auto coord_type = mesh.getCoordSystem(sub_id);
  if (coord_type == Moose::COORD_RZ)
  {
    if (mesh.usingGeneralAxisymmetricCoordAxes())
    {
      const auto & axis = mesh.getGeneralAxisymmetricCoordAxis(sub_id);
      MooseMeshUtils::coordTransformFactorRZGeneral(point, axis, factor);
    }
    else
      MooseMeshUtils::coordTransformFactor(
          point, factor, coord_type, mesh.getAxisymmetricRadialCoord());
  }
  else
    MooseMeshUtils::coordTransformFactor(point, factor, coord_type, libMesh::invalid_uint);
}
coordTransformFactor() [2/2]
template<typename P , typename C > void coordTransformFactor (const SubProblem & s, SubdomainID sub_id, const P & point, C & factor, SubdomainID neighbor_sub_id = libMesh::Elem::invalid_subdomain_id)
Computes a conversion multiplier for use when computing integraals for the current coordinate system type.
This allows us to handle cases where we use RZ, spherical, or other non-cartesian coordinate systems. The factor returned by this function should generally be multiplied against all integration terms. Note that the computed factor is particular to a specific point on the mesh. The result is stored in the factor argument. point is the point at which to compute the factor. point and factor can be either Point and Real or ADPoint and ADReal.
Definition at line 39 of file Assembly.C.
{
  coordTransformFactor(s.mesh(), sub_id, point, factor, neighbor_sub_id);
}
Referenced by MooseMesh::computeFiniteVolumeCoords(), coordTransformFactor(), Assembly::elementVolume(), and Assembly::setCoordinateTransformation().
coordTransformFactor< ADPoint, ADReal >() [1/2]
template void coordTransformFactor< ADPoint, ADReal > (const MooseMesh & mesh, SubdomainID sub_id, const ADPoint & point, ADReal & factor, SubdomainID neighbor_sub_id)
coordTransformFactor< ADPoint, ADReal >() [2/2]
template void coordTransformFactor< ADPoint, ADReal > (const SubProblem & s, SubdomainID sub_id, const ADPoint & point, ADReal & factor, SubdomainID neighbor_sub_id)
coordTransformFactor< Point, Real >() [1/2]
template void coordTransformFactor< Point, Real > (const MooseMesh & mesh, SubdomainID sub_id, const Point & point, Real & factor, SubdomainID neighbor_sub_id)
coordTransformFactor< Point, Real >() [2/2]
template void coordTransformFactor< Point, Real > (const SubProblem & s, SubdomainID sub_id, const Point & point, Real & factor, SubdomainID neighbor_sub_id)