Zapdos: moose/framework/include/base/Assembly.h File Reference
Assembly.h File Reference
Classes
class Assembly
Keeps track of stuff related to assembling.
class Assembly::GlobalDataKey
Key structure for APIs manipulating global vectors/matrices.
class Assembly::LocalDataKey
Key structure for APIs adding/caching local element residuals/Jacobians.
struct Assembly::QRules
Data structure for tracking/grouping a set of quadrature rules for a particular dimensionality of mesh element.
class Assembly::FEShapeData
class Assembly::VectorFEShapeData
Namespaces
namespace libMesh
The following methods are specializations for using the libMesh::Parallel::packed_range_* routines for std::strings.
Typedefs
typedef VectorValue< Real > libMesh::RealVectorValue
typedef FEGenericBase< Real > libMesh::FEBase
typedef FEGenericBase< VectorValue< Real > > libMesh::FEVectorBase
typedef MooseVariableFE< Real > MooseVariable
typedef MooseVariableFE< RealVectorValue > VectorMooseVariable
typedef MooseVariableFE< RealEigenVector > ArrayMooseVariable
Functions
template<typename P , typename C >
void coordTransformFactor (const SubProblem &s, SubdomainID sub_id, const P &point, C &factor, SubdomainID neighbor_sub_id=libMesh::Elem::invalid_subdomain_id)
Computes a conversion multiplier for use when computing integraals for the current coordinate system type.
template<typename P , typename C >
void coordTransformFactor (const MooseMesh &mesh, SubdomainID sub_id, const P &point, C &factor, SubdomainID neighbor_sub_id=libMesh::Elem::invalid_subdomain_id)
Typedef Documentation
ArrayMooseVariable
typedef MooseVariableFE<RealEigenVector> ArrayMooseVariable
Definition at line 62 of file Assembly.h.
MooseVariable
typedef MooseVariableFE<Real> MooseVariable
Definition at line 60 of file Assembly.h.
VectorMooseVariable
typedef MooseVariableFE<RealVectorValue> VectorMooseVariable
Definition at line 61 of file Assembly.h.
Function Documentation
coordTransformFactor() [1/2]
template<typename P , typename C > void coordTransformFactor (const MooseMesh & mesh, SubdomainID sub_id, const P & point, C & factor, SubdomainID neighbor_sub_id = libMesh::Elem::invalid_subdomain_id)
coordTransformFactor() [2/2]
template<typename P , typename C > void coordTransformFactor (const SubProblem & s, SubdomainID sub_id, const P & point, C & factor, SubdomainID neighbor_sub_id = libMesh::Elem::invalid_subdomain_id)
Computes a conversion multiplier for use when computing integraals for the current coordinate system type.
This allows us to handle cases where we use RZ, spherical, or other non-cartesian coordinate systems. The factor returned by this function should generally be multiplied against all integration terms. Note that the computed factor is particular to a specific point on the mesh. The result is stored in the factor argument. point is the point at which to compute the factor. point and factor can be either Point and Real or ADPoint and ADReal.
Definition at line 39 of file Assembly.C.
{
  coordTransformFactor(s.mesh(), sub_id, point, factor, neighbor_sub_id);
}
Referenced by MooseMesh::computeFiniteVolumeCoords(), coordTransformFactor(), Assembly::elementVolume(), and Assembly::setCoordinateTransformation().