Zapdos: moose/framework/src/loops/BoundaryElemIntegrityCheckThread.C File Reference
BoundaryElemIntegrityCheckThread.C File Reference
Functions
void boundaryIntegrityCheckError (const MooseObject &object, const std::set< MooseVariableFieldBase * > &variables, const BoundaryName &boundary_name)
Compose boundary restricted error message for the provided object, variables, and boundary_name if the variables container is non-empty.
Function Documentation
boundaryIntegrityCheckError()
void boundaryIntegrityCheckError (const MooseObject & object, const std::set< MooseVariableFieldBase * > & variables, const BoundaryName & boundary_name)
Compose boundary restricted error message for the provided object, variables, and boundary_name if the variables container is non-empty.
Definition at line 135 of file BoundaryElemIntegrityCheckThread.C.
{
  if (variables.empty())
    return;
  std::vector<std::string> names;
  names.reserve(variables.size());
  for (const auto * const var : variables)
    names.push_back(var->name());
  mooseError("'",
             object.name(),
             "' of type '",
             object.type(),
             "' depends on variable(s) '",
             MooseUtils::join(names, ","),
             "'. However, that variable does not appear to be defined on (all of) boundary '",
             boundary_name,
             "'.");
}
Referenced by DumpObjectsProblem::addAuxVariable(), BoundaryNodeIntegrityCheckThread::onNode(), and BoundaryElemIntegrityCheckThread::operator()().