Zapdos: MooseServer Class Reference
MooseServer Class Reference
#include <MooseServer.h>
Public Member Functions
MooseServer (MooseApp &moose_app)
virtual ~MooseServer ()=default
std::shared_ptr< wasp::lsp::Connection > getConnection ()
Get read / write connection - specific to this server implemention.
Private Types
using SortedLocationNodes = std::set< wasp::HITNodeView, std::function< bool(const wasp::HITNodeView &, const wasp::HITNodeView &)> >
SortedLocationNodes - type alias for set of nodes sorted by location.
Private Member Functions
bool parseDocumentForDiagnostics (wasp::DataArray &diagnosticsList)
Parse document for diagnostics - specific to this server implemention.
bool updateDocumentTextChanges (const std::string &replacement_text, int start_line, int start_character, int end_line, int end_character, int range_length)
Update document text changes - specific to this server implemention.
bool gatherDocumentCompletionItems (wasp::DataArray &completionItems, bool &is_incomplete, int line, int character)
Gather document completion items - specific to this server implemention.
void getExistingInput (wasp::HITNodeView parent_node, std::set< std::string > &existing_params, std::set< std::string > &existing_subblocks)
Get names of parameters and subblocks specified in given input node.
void getAllValidParameters (InputParameters &valid_params, const std::string &object_path, const std::string &object_type, std::set< std::string > &obj_act_tasks)
Get all global parameters, action parameters, and object parameters.
void getActionParameters (InputParameters &valid_params, const std::string &object_path, std::set< std::string > &obj_act_tasks)
Get all action parameters using requested object path to collection.
void getObjectParameters (InputParameters &valid_params, std::string object_type, const std::set< std::string > &obj_act_tasks)
Get all object parameters using requested object path to collection.
bool addParametersToList (wasp::DataArray &completionItems, const InputParameters &valid_params, const std::set< std::string > &existing_params, int request_line, int request_char)
Add parameters that were previously gathered to list for completion.
bool addSubblocksToList (wasp::DataArray &completionItems, const std::string &object_path, int request_line, int request_char)
Add subblocks to completion list for request path, line, and column.
bool addValuesToList (wasp::DataArray &completionItems, const InputParameters &valid_params, const std::set< std::string > &existing_subblocks, const std::string &param_name, const std::set< std::string > &obj_act_tasks, int replace_line_start, int replace_char_start, int replace_line_end, int replace_char_end)
Add parameter values to completion list for request line and column.
template<typename MooseEnumType >
void getEnumsAndDocs (MooseEnumType &moose_enum_param, std::map< std::string, std::string > &options_and_descs)
Fill map of all options and descriptions if parameter is moose enum.
bool gatherDocumentDefinitionLocations (wasp::DataArray &definitionLocations, int line, int character)
Gather definition locations - specific to this server implemention.
void getInputLookupDefinitionNodes (SortedLocationNodes &location_nodes, const std::string &clean_type, const std::string &val_string)
Get set of nodes from associated path lookups matching value string.
bool addLocationNodesToList (wasp::DataArray &definitionLocations, const SortedLocationNodes &location_nodes)
Add locations of lookups or parameter declarator to definition list.
bool gatherDocumentReferencesLocations (wasp::DataArray &referencesLocations, int line, int character, bool include_declaration)
Gather references locations - specific to this server implemention.
bool gatherDocumentFormattingTextEdits (wasp::DataArray &formattingTextEdits, int tab_size, bool insert_spaces)
Gather formatting text edits - specific to this server implemention.
bool gatherDocumentSymbols (wasp::DataArray &documentSymbols)
Gather document symbols - specific to this server implemention.
bool traverseParseTreeAndFillSymbols (wasp::HITNodeView view_parent, wasp::DataObject &data_parent)
Recursively fill document symbols from the given node.
int getCompletionItemKind (const InputParameters &valid_params, const std::string &param_name, const std::string &clean_type, bool is_param)
Get completion item kind value that client may use for icon in list.
int getDocumentSymbolKind (wasp::HITNodeView symbol_node)
Get document symbol kind value that client may use for outline icon.
bool connectionRead (wasp::DataObject &object)
Read from connection into object - specific to this server's connection.
bool connectionWrite (wasp::DataObject &object)
Write object json to connection - specific to this server's connection.
Private Attributes
MooseApp & _moose_app
_moose_app - reference to parent application that owns this server
std::shared_ptr< MooseApp > _check_app
_check_app - application created to check input and access parser
std::shared_ptr< wasp::lsp::IOStreamConnection > _connection
_connection - shared pointer to this server's read / write iostream
std::map< std::string, std::set< std::string > > _syntax_to_subblocks
_syntax_to_subblocks - map of syntax paths to valid subblocks
std::map< std::string, std::set< std::string > > _type_to_input_paths
_type_to_input_paths - map of parameter types to lookup paths
Detailed Description
Definition at line 28 of file MooseServer.h.
Member Typedef Documentation
SortedLocationNodes
using MooseServer::SortedLocationNodes = std::set<wasp::HITNodeView, std::function<bool(const wasp::HITNodeView &, const wasp::HITNodeView &)> > private
SortedLocationNodes - type alias for set of nodes sorted by location.
Definition at line 45 of file MooseServer.h.
Constructor & Destructor Documentation
MooseServer()
MooseServer::MooseServer (MooseApp & moose_app)
Definition at line 32 of file MooseServer.C.
  : _moose_app(moose_app), _connection(std::make_shared<wasp::lsp::IOStreamConnection>(this))
{
  // set server capabilities to receive full input text when changed
  server_capabilities[wasp::lsp::m_text_doc_sync] = wasp::DataObject();
  server_capabilities[wasp::lsp::m_text_doc_sync][wasp::lsp::m_open_close] = true;
  server_capabilities[wasp::lsp::m_text_doc_sync][wasp::lsp::m_change] = wasp::lsp::m_change_full;
  // notify completion, symbol, formatting, definition capabilities support
  server_capabilities[wasp::lsp::m_completion_provider] = wasp::DataObject();
  server_capabilities[wasp::lsp::m_completion_provider][wasp::lsp::m_resolve_provider] = false;
  server_capabilities[wasp::lsp::m_doc_symbol_provider] = true;
  server_capabilities[wasp::lsp::m_doc_format_provider] = true;
  server_capabilities[wasp::lsp::m_definition_provider] = true;
  server_capabilities[wasp::lsp::m_references_provider] = false;
  server_capabilities[wasp::lsp::m_hover_provider] = false;
}
~MooseServer()
virtual MooseServer::~MooseServer () virtual default
Member Function Documentation
addLocationNodesToList()
bool MooseServer::addLocationNodesToList (wasp::DataArray & definitionLocations, const SortedLocationNodes & location_nodes) private
Add locations of lookups or parameter declarator to definition list.
Parameters
definitionLocations - data array of locations objects to fill
location_nodes - set of nodes that have locations to be added
Returns
- true if filling of location objects completed successfully
Definition at line 895 of file MooseServer.C.
{
  bool pass = true;
  // walk over set of nodes with locations to add and build definition list
  for (const auto & location_nodes_iter : location_nodes)
  {
    // add file scheme prefix to front of file path to build definition uri
    auto location_uri = wasp::lsp::m_uri_prefix + location_nodes_iter.node_pool()->stream_name();
    // add file uri and zero based line and column range to definition list
    definitionLocations.push_back(wasp::DataObject());
    wasp::DataObject * location = definitionLocations.back().to_object();
    pass &= wasp::lsp::buildLocationObject(*location,
                                           errors,
                                           location_uri,
                                           location_nodes_iter.line() - 1,
                                           location_nodes_iter.column() - 1,
                                           location_nodes_iter.last_line() - 1,
                                           location_nodes_iter.last_column());
  }
  return pass;
}
Referenced by gatherDocumentDefinitionLocations().
addParametersToList()
bool MooseServer::addParametersToList (wasp::DataArray & completionItems, const InputParameters & valid_params, const std::set< std::string > & existing_params, int request_line, int request_char) private
Add parameters that were previously gathered to list for completion.
Parameters
completionItems - list of completion objects to be filled out
valid_params - all valid parameters to add to completion list
existing_params - set of parameters already existing in input
request_line - line in input where autocomplete was requested
request_char - char in input where autocomplete was requested
Returns
- true if filling of completion items completed successfully
Definition at line 385 of file MooseServer.C.
{
  bool pass = true;
  // walk over collection of all valid parameters and build completion list
  for (const auto & valid_params_iter : valid_params)
  {
    const std::string & param_name = valid_params_iter.first;
    bool deprecated = valid_params.isParamDeprecated(param_name);
    bool is_private = valid_params.isPrivate(param_name);
    // filter out parameters that are deprecated, private, or already exist
    if (deprecated || is_private || existing_params.count(param_name))
      continue;
    // process parameter description and type to use in input default value
    std::string dirty_type = valid_params.type(param_name);
    std::string clean_type = MooseUtils::prettyCppType(dirty_type);
    std::string basic_type = JsonSyntaxTree::basicCppType(clean_type);
    std::string doc_string = valid_params.getDocString(param_name);
    MooseUtils::escape(doc_string);
    // use basic type to decide if parameter is array and quotes are needed
    std::string array_quote = basic_type.compare(0, 6, "Array:") == 0 ? "'" : "";
    // remove any array prefixes from basic type string and leave base type
    pcrecpp::RE("(Array:)*(.*)").GlobalReplace("\\2", &basic_type);
    // prepare clean cpp type string to be used for key to find input paths
    pcrecpp::RE(".+<([A-Za-z0-9_' ':]*)>.*").GlobalReplace("\\1", &clean_type);
    // decide completion item kind that client may use to display list icon
    int complete_kind = getCompletionItemKind(valid_params, param_name, clean_type, true);
    // default value for completion to be built using parameter information
    std::string default_value;
    // first if parameter default is set then use it to build default value
    if (valid_params.isParamValid(param_name))
    {
      default_value = JsonSyntaxTree::buildOutputString(valid_params_iter);
      default_value = MooseUtils::trim(default_value);
    }
    // otherwise if parameter has coupled default then use as default value
    else if (valid_params.hasDefaultCoupledValue(param_name))
    {
      std::ostringstream oss;
      oss << valid_params.defaultCoupledValue(param_name);
      default_value = oss.str();
    }
    // otherwise if parameter is enum then use first item for default value
    if (default_value.empty())
    {
      std::map<std::string, std::string> options_and_descs;
      if (valid_params.have_parameter<MooseEnum>(param_name))
        getEnumsAndDocs(valid_params.get<MooseEnum>(param_name), options_and_descs);
      else if (valid_params.have_parameter<MultiMooseEnum>(param_name))
        getEnumsAndDocs(valid_params.get<MultiMooseEnum>(param_name), options_and_descs);
      else if (valid_params.have_parameter<ExecFlagEnum>(param_name))
        getEnumsAndDocs(valid_params.get<ExecFlagEnum>(param_name), options_and_descs);
      else if (valid_params.have_parameter<std::vector<MooseEnum>>(param_name))
        getEnumsAndDocs(valid_params.get<std::vector<MooseEnum>>(param_name)[0], options_and_descs);
      if (!options_and_descs.empty())
        default_value = options_and_descs.begin()->first;
    }
    // otherwise use parameter basic type to pick appropriate default value
    if (default_value.empty())
    {
      if (basic_type == "Boolean")
        default_value = "true";
      else if (basic_type == "Integer")
        default_value = "0";
      else if (basic_type == "Real")
        default_value = "0.0";
      else
        default_value = "value";
    }
    // switch 1 to true or 0 to false if boolean parameter as default value
    if (basic_type == "Boolean" && default_value == "1")
      default_value = "true";
    else if (basic_type == "Boolean" && default_value == "0")
      default_value = "false";
    // finally build full insertion from parameter name, quote, and default
    std::string embed_text = param_name + " = " + array_quote + default_value + array_quote;
    // add parameter label, insert text, and description to completion list
    completionItems.push_back(wasp::DataObject());
    wasp::DataObject * item = completionItems.back().to_object();
    pass &= wasp::lsp::buildCompletionObject(*item,
                                             errors,
                                             param_name,
                                             request_line,
                                             request_char,
                                             request_line,
                                             request_char,
                                             embed_text,
                                             complete_kind,
                                             "",
                                             doc_string,
                                             false,
                                             false);
  }
  return pass;
}
Referenced by gatherDocumentCompletionItems().
addSubblocksToList()
bool MooseServer::addSubblocksToList (wasp::DataArray & completionItems, const std::string & object_path, int request_line, int request_char) private
Add subblocks to completion list for request path, line, and column.
Parameters
completionItems - list of completion objects to be filled out
object_path - full node path where autocomplete was requested
request_line - line in input where autocomplete was requested
request_char - char in input where autocomplete was requested
Returns
- true if filling of completion items completed successfully
Definition at line 503 of file MooseServer.C.
{
  Syntax & syntax = _check_app->syntax();
  // set used to prevent reprocessing syntax paths for more than one action
  std::set<std::string> syntax_paths_processed;
  // build map of all syntax paths to names for subblocks and save to reuse
  if (_syntax_to_subblocks.empty())
  {
    for (const auto & syntax_path_iter : syntax.getAssociatedActions())
    {
      std::string syntax_path = "/" + syntax_path_iter.first;
      // skip current syntax path if already processed for different action
      if (!syntax_paths_processed.insert(syntax_path).second)
        continue;
      // walk backward through syntax path adding subblock names to parents
      for (std::size_t last_sep; (last_sep = syntax_path.find_last_of("/")) != std::string::npos;)
      {
        std::string subblock_name = syntax_path.substr(last_sep + 1);
        syntax_path = syntax_path.substr(0, last_sep);
        _syntax_to_subblocks[syntax_path].insert(subblock_name);
      }
    }
  }
  // get registered syntax from object path using map of paths to subblocks
  std::string registered_syntax = syntax.isAssociated(object_path, nullptr, _syntax_to_subblocks);
  bool pass = true;
  // walk over subblock names if found or at root and build completion list
  if (!registered_syntax.empty() || object_path == "/")
  {
    for (const auto & subblock_name : _syntax_to_subblocks[registered_syntax])
    {
      std::string doc_string;
      std::string embed_text;
      int complete_kind;
      // customize description and insert text for star and named subblocks
      if (subblock_name == "*")
      {
        doc_string = "custom user named block";
        embed_text = "[block_name]\n  \n[]";
        complete_kind = wasp::lsp::m_comp_kind_variable;
      }
      else
      {
        doc_string = "application named block";
        embed_text = "[" + subblock_name + "]\n  \n[]";
        complete_kind = wasp::lsp::m_comp_kind_struct;
      }
      // add subblock name, insert text, and description to completion list
      completionItems.push_back(wasp::DataObject());
      wasp::DataObject * item = completionItems.back().to_object();
      pass &= wasp::lsp::buildCompletionObject(*item,
                                               errors,
                                               subblock_name,
                                               request_line,
                                               request_char,
                                               request_line,
                                               request_char,
                                               embed_text,
                                               complete_kind,
                                               "",
                                               doc_string,
                                               false,
                                               false);
    }
  }
  return pass;
}
Referenced by gatherDocumentCompletionItems().
addValuesToList()
bool MooseServer::addValuesToList (wasp::DataArray & completionItems, const InputParameters & valid_params, const std::set< std::string > & existing_subblocks, const std::string & param_name, const std::set< std::string > & obj_act_tasks, int replace_line_start, int replace_char_start, int replace_line_end, int replace_char_end) private
Add parameter values to completion list for request line and column.
Parameters
completionItems - list of completion objects to be filled out
valid_params - all valid parameters used for value completion
existing_subblocks - active and inactive subblock name values
param_name - name of input parameter for value autocompletion
obj_act_tasks - tasks to verify object type with valid syntax
replace_line_start - start line of autocomplete replace range
replace_char_start - start char of autocomplete replace range
replace_line_end - end line of autocomplete replacement range
replace_char_end - end char of autocomplete replacement range
Returns
- true if filling of completion items completed successfully
Definition at line 585 of file MooseServer.C.
{
  Syntax & syntax = _check_app->syntax();
  Factory & factory = _check_app->getFactory();
  // get clean type for path associations and basic type for boolean values
  std::string dirty_type = valid_params.type(param_name);
  std::string clean_type = MooseUtils::prettyCppType(dirty_type);
  std::string basic_type = JsonSyntaxTree::basicCppType(clean_type);
  // remove any array prefixes from basic type string and replace with base
  pcrecpp::RE("(Array:)*(.*)").GlobalReplace("\\2", &basic_type);
  // prepare clean cpp type string to be used for a key to find input paths
  pcrecpp::RE(".+<([A-Za-z0-9_' ':]*)>.*").GlobalReplace("\\1", &clean_type);
  // decide completion item kind that client may use to display a list icon
  int complete_kind = getCompletionItemKind(valid_params, param_name, clean_type, false);
  // map used to gather options and descriptions for value completion items
  std::map<std::string, std::string> options_and_descs;
  // first if parameter name is active or inactive then use input subblocks
  if (param_name == "active" || param_name == "inactive")
    for (const auto & subblock_name : existing_subblocks)
      options_and_descs[subblock_name] = "subblock name";
  // otherwise if parameter type is boolean then use true and false strings
  else if (basic_type == "Boolean")
  {
    options_and_descs["true"];
    options_and_descs["false"];
  }
  // otherwise if parameter type is one of the enums then use valid options
  else if (valid_params.have_parameter<MooseEnum>(param_name))
    getEnumsAndDocs(valid_params.get<MooseEnum>(param_name), options_and_descs);
  else if (valid_params.have_parameter<MultiMooseEnum>(param_name))
    getEnumsAndDocs(valid_params.get<MultiMooseEnum>(param_name), options_and_descs);
  else if (valid_params.have_parameter<ExecFlagEnum>(param_name))
    getEnumsAndDocs(valid_params.get<ExecFlagEnum>(param_name), options_and_descs);
  else if (valid_params.have_parameter<std::vector<MooseEnum>>(param_name))
    getEnumsAndDocs(valid_params.get<std::vector<MooseEnum>>(param_name)[0], options_and_descs);
  // otherwise if parameter name is type then use all verified object names
  else if (param_name == "type")
  {
    // walk over entire set of objects that have been registered in factory
    for (const auto & objects_iter : factory.registeredObjects())
    {
      const std::string & object_name = objects_iter.first;
      const InputParameters & object_params = objects_iter.second->buildParameters();
      // check if object has registered base parameter that can be verified
      if (!object_params.have_parameter<std::string>("_moose_base"))
        continue;
      const std::string & moose_base = object_params.get<std::string>("_moose_base");
      // walk over gathered MooseObjectAction tasks and add if base matches
      for (const auto & obj_act_task : obj_act_tasks)
      {
        if (!syntax.verifyMooseObjectTask(moose_base, obj_act_task))
          continue;
        std::string type_description = object_params.getClassDescription();
        MooseUtils::escape(type_description);
        options_and_descs[object_name] = type_description;
        break;
      }
    }
  }
  // otherwise if parameter type has any associated syntax then use lookups
  else
  {
    // build map of parameter types to input lookup paths and save to reuse
    if (_type_to_input_paths.empty())
    {
      for (const auto & associated_types_iter : syntax.getAssociatedTypes())
      {
        const std::string & type = associated_types_iter.second;
        const std::string & path = associated_types_iter.first;
        _type_to_input_paths[type].insert(path);
      }
    }
    // check for input lookup paths that are associated with parameter type
    const auto & input_path_iter = _type_to_input_paths.find(clean_type);
    if (input_path_iter != _type_to_input_paths.end())
    {
      wasp::HITNodeView view_root = _check_app->parser()._root->getNodeView();
      // walk over all syntax paths that are associated with parameter type
      for (const auto & input_path : input_path_iter->second)
      {
        // use wasp siren to gather all input values at current lookup path
        wasp::SIRENInterpreter<> selector;
        if (!selector.parseString(input_path))
          continue;
        wasp::SIRENResultSet<wasp::HITNodeView> results;
        std::size_t count = selector.evaluate(view_root, results);
        // walk over results and add each input value found at current path
        for (std::size_t i = 0; i < count; i++)
          if (results.adapted(i).type() == wasp::OBJECT)
            options_and_descs[results.adapted(i).name()] = "from /" + input_path;
      }
    }
  }
  bool pass = true;
  // walk over pairs of options with descriptions and build completion list
  for (const auto & option_and_desc : options_and_descs)
  {
    const std::string & option = option_and_desc.first;
    const std::string & dscrpt = option_and_desc.second;
    // add option name, insertion range, and description to completion list
    completionItems.push_back(wasp::DataObject());
    wasp::DataObject * item = completionItems.back().to_object();
    pass &= wasp::lsp::buildCompletionObject(*item,
                                             errors,
                                             option,
                                             replace_line_start,
                                             replace_char_start,
                                             replace_line_end,
                                             replace_char_end,
                                             option,
                                             complete_kind,
                                             "",
                                             dscrpt,
                                             false,
                                             false);
  }
  return pass;
}
Referenced by gatherDocumentCompletionItems().
connectionRead()
bool MooseServer::connectionRead (wasp::DataObject & object) inline private
Read from connection into object - specific to this server's connection.
Parameters
object - reference to object to be read into
Returns
- true if the read from the connection completed successfully
Definition at line 282 of file MooseServer.h.
{ return _connection->read(object, errors); }
connectionWrite()
bool MooseServer::connectionWrite (wasp::DataObject & object) inline private
Write object json to connection - specific to this server's connection.
Parameters
object - reference to object with contents to write to connection
Returns
- true if the write to the connection completed successfully
Definition at line 289 of file MooseServer.h.
{ return _connection->write(object, errors); }
gatherDocumentCompletionItems()
bool MooseServer::gatherDocumentCompletionItems (wasp::DataArray & completionItems, bool & is_incomplete, int line, int character) private
Gather document completion items - specific to this server implemention.
Parameters
completionItems - data array of completion item objects to fill
is_incomplete - flag indicating if the completions are complete
line - line to be used for completions gathering logic
character - column to be used for completions gathering logic
Returns
- true if the gathering of items completed successfully
Definition at line 174 of file MooseServer.C.
{
  // add only root level blocks to completion list when parser root is null
  if (!_check_app || !_check_app->parser()._root ||
      _check_app->parser()._root->getNodeView().is_null())
    return addSubblocksToList(completionItems, "/", line, character);
  // find hit node for zero based request line and column number from input
  wasp::HITNodeView view_root = _check_app->parser()._root->getNodeView();
  wasp::HITNodeView request_context =
      wasp::findNodeUnderLineColumn(view_root, line + 1, character + 1);
  // get object context and value of type parameter for request if provided
  wasp::HITNodeView object_context = request_context;
  while (object_context.type() != wasp::OBJECT && object_context.has_parent())
    object_context = object_context.parent();
  const std::string & object_path = object_context.path();
  wasp::HITNodeView type_node = object_context.first_child_by_name("type");
  const std::string & object_type = type_node.is_null() ? "" : type_node.last_as_string();
  // get set of all parameter and subblock names already specified in input
  std::set<std::string> existing_params, existing_subblocks;
  getExistingInput(object_context, existing_params, existing_subblocks);
  // set used to gather all parameters valid from object context of request
  InputParameters valid_params = emptyInputParameters();
  // set used to gather MooseObjectAction tasks to verify object parameters
  std::set<std::string> obj_act_tasks;
  // get set of global parameters, action parameters, and object parameters
  getAllValidParameters(valid_params, object_path, object_type, obj_act_tasks);
  bool pass = true;
  // use context of request to pick types of items added to completion list
  if (request_context.type() == wasp::OBJECT || request_context.type() == wasp::DOCUMENT_ROOT)
  {
    // add gathered parameters to completion list at request input location
    pass &= addParametersToList(completionItems, valid_params, existing_params, line, character);
    // add all valid subblock objects to completion list for request object
    pass &= addSubblocksToList(completionItems, object_path, line, character);
  }
  else if (request_context.type() == wasp::VALUE)
  {
    // get name of parameter in input and zero based line and column ranges
    std::string param_name = request_context.has_parent() ? request_context.parent().name() : "";
    int replace_line_start = request_context.line() - 1;
    int replace_char_start = request_context.column() - 1;
    int replace_line_end = request_context.last_line() - 1;
    int replace_char_end = request_context.last_column();
    // add options to completion list for request value if parameter exists
    for (const auto & valid_params_iter : valid_params)
    {
      const std::string & valid_param_name = valid_params_iter.first;
      if (param_name == valid_param_name)
      {
        pass &= addValuesToList(completionItems,
                                valid_params,
                                existing_subblocks,
                                param_name,
                                obj_act_tasks,
                                replace_line_start,
                                replace_char_start,
                                replace_line_end,
                                replace_char_end);
        break;
      }
    }
  }
  is_incomplete = !pass;
  return pass;
}
gatherDocumentDefinitionLocations()
bool MooseServer::gatherDocumentDefinitionLocations (wasp::DataArray & definitionLocations, int line, int character) private
Gather definition locations - specific to this server implemention.
Parameters
definitionLocations - data array of locations objects to fill
line - line to be used for locations gathering logic
character - column to be used for locations gathering logic
Returns
- true if the gathering of locations completed successfully
Definition at line 746 of file MooseServer.C.
{
  Factory & factory = _check_app->getFactory();
  // return without any definition locations added when parser root is null
  if (!_check_app || !_check_app->parser()._root ||
      _check_app->parser()._root->getNodeView().is_null())
    return true;
  // find hit node for zero based request line and column number from input
  wasp::HITNodeView view_root = _check_app->parser()._root->getNodeView();
  wasp::HITNodeView request_context =
      wasp::findNodeUnderLineColumn(view_root, line + 1, character + 1);
  // return without any definition locations added when node not value type
  if (request_context.type() != wasp::VALUE)
    return true;
  // get name of parameter node parent of value and value string from input
  std::string param_name = request_context.has_parent() ? request_context.parent().name() : "";
  std::string val_string = request_context.last_as_string();
  // add source code location if type parameter with registered object name
  if (param_name == "type" && factory.isRegistered(val_string))
  {
    // get file path and line number of source code registering object type
    FileLineInfo file_line_info = factory.getLineInfo(val_string);
    // return without any definition locations added if file cannot be read
    if (!file_line_info.isValid() ||
        !MooseUtils::checkFileReadable(file_line_info.file(), false, false, false))
      return true;
    // add file scheme prefix to front of file path to build definition uri
    auto location_uri = wasp::lsp::m_uri_prefix + file_line_info.file();
    // add file uri and zero based line and column range to definition list
    definitionLocations.push_back(wasp::DataObject());
    wasp::DataObject * location = definitionLocations.back().to_object();
    return wasp::lsp::buildLocationObject(*location,
                                          errors,
                                          location_uri,
                                          file_line_info.line() - 1,
                                          0,
                                          file_line_info.line() - 1,
                                          1000);
  }
  // get object context and value of type parameter for request if provided
  wasp::HITNodeView object_context = request_context;
  while (object_context.type() != wasp::OBJECT && object_context.has_parent())
    object_context = object_context.parent();
  const std::string & object_path = object_context.path();
  wasp::HITNodeView type_node = object_context.first_child_by_name("type");
  const std::string & object_type = type_node.is_null() ? "" : type_node.last_as_string();
  // set used to gather all parameters valid from object context of request
  InputParameters valid_params = emptyInputParameters();
  // set used to gather MooseObjectAction tasks to verify object parameters
  std::set<std::string> obj_act_tasks;
  // get set of global parameters, action parameters, and object parameters
  getAllValidParameters(valid_params, object_path, object_type, obj_act_tasks);
  // set used to gather nodes from input lookups custom sorted by locations
  SortedLocationNodes location_nodes(
      [](const wasp::HITNodeView & l, const wasp::HITNodeView & r)
      {
        const std::string & l_file = l.node_pool()->stream_name();
        const std::string & r_file = r.node_pool()->stream_name();
        return (l_file < r_file || (l_file == r_file && l.line() < r.line()) ||
                (l_file == r_file && l.line() == r.line() && l.column() < r.column()));
      });
  // gather all lookup path nodes matching value if parameter name is valid
  for (const auto & valid_params_iter : valid_params)
  {
    if (valid_params_iter.first == param_name)
    {
      // get cpp type and prepare string for use as key finding input paths
      std::string dirty_type = valid_params.type(param_name);
      std::string clean_type = MooseUtils::prettyCppType(dirty_type);
      pcrecpp::RE(".+<([A-Za-z0-9_' ':]*)>.*").GlobalReplace("\\1", &clean_type);
      // get set of nodes from associated path lookups matching input value
      getInputLookupDefinitionNodes(location_nodes, clean_type, val_string);
      break;
    }
  }
  // add parameter declarator to set if none were gathered by input lookups
  if (location_nodes.empty() && request_context.has_parent() &&
      request_context.parent().child_count_by_name("decl"))
    location_nodes.insert(request_context.parent().first_child_by_name("decl"));
  // add locations to definition list using lookups or parameter declarator
  return addLocationNodesToList(definitionLocations, location_nodes);
}
gatherDocumentFormattingTextEdits()
bool MooseServer::gatherDocumentFormattingTextEdits (wasp::DataArray & formattingTextEdits, int tab_size, bool insert_spaces) private
Gather formatting text edits - specific to this server implemention.
Parameters
formattingTextEdits - data array of text edit objects to fill
tab_size - value of the size of a tab in spaces for formatting
insert_spaces - flag indicating whether to use spaces for tabs
Returns
- true if the gathering of text edits completed successfully
Definition at line 935 of file MooseServer.C.
{
  // return without adding any formatting text edits if parser root is null
  if (!_check_app || !_check_app->parser()._root ||
      _check_app->parser()._root->getNodeView().is_null())
    return true;
  // get input root node line and column range to represent entire document
  wasp::HITNodeView view_root = _check_app->parser()._root->getNodeView();
  int document_start_line = view_root.line() - 1;
  int document_start_char = view_root.column() - 1;
  int document_last_line = view_root.last_line() - 1;
  int document_last_char = view_root.last_column();
  // lambda that traverses hit tree clearing legacy markers and blank lines
  std::function<void(hit::Section *)> format_document = [&](hit::Section * section)
  {
    section->clearLegacyMarkers();
    for (auto child : section->children())
      if (child->type() == hit::NodeType::Blank)
        delete child;
      else if (child->type() == hit::NodeType::Section)
        format_document(static_cast<hit::Section *>(child));
  };
  // clear legacy markers and blank lines, use tab size to render, and trim
  format_document(static_cast<hit::Section *>(_check_app->parser()._root.get()));
  std::string document_format = _check_app->parser()._root->render(0, std::string(tab_size, ' '));
  document_format = MooseUtils::trim(document_format);
  // add formatted text with whole line and column range to formatting list
  formattingTextEdits.push_back(wasp::DataObject());
  wasp::DataObject * item = formattingTextEdits.back().to_object();
  bool pass = wasp::lsp::buildTextEditObject(*item,
                                             errors,
                                             document_start_line,
                                             document_start_char,
                                             document_last_line,
                                             document_last_char,
                                             document_format);
  return pass;
}
gatherDocumentReferencesLocations()
bool MooseServer::gatherDocumentReferencesLocations (wasp::DataArray & referencesLocations, int line, int character, bool include_declaration) private
Gather references locations - specific to this server implemention.
Parameters
referencesLocations - data array of locations objects to fill
line - line to be used for locations gathering logic
character - column to be used for locations gathering logic
include_declaration - flag indicating declaration inclusion
Returns
- true if the gathering of locations completed successfully
Definition at line 922 of file MooseServer.C.
{
  bool pass = true;
  // TODO - hook up this capability by adding server specific logic here
  return pass;
}
gatherDocumentSymbols()
bool MooseServer::gatherDocumentSymbols (wasp::DataArray & documentSymbols) private
Gather document symbols - specific to this server implemention.
Parameters
documentSymbols - data array of symbols data objects to fill
Returns
- true if the gathering of symbols completed successfully
Definition at line 981 of file MooseServer.C.
{
  // return prior to starting document symbol tree when parser root is null
  if (!_check_app || !_check_app->parser()._root ||
      _check_app->parser()._root->getNodeView().is_null())
    return true;
  wasp::HITNodeView view_root = _check_app->parser()._root->getNodeView();
  bool pass = true;
  // walk over all children of root node context and build document symbols
  for (const auto i : make_range(view_root.child_count()))
  {
    // walk must be index based to catch file include and skip its children
    wasp::HITNodeView view_child = view_root.child_at(i);
    // set up name, zero based line and column range, kind, and detail info
    std::string name = view_child.name();
    int line = view_child.line() - 1;
    int column = view_child.column() - 1;
    int last_line = view_child.last_line() - 1;
    int last_column = view_child.last_column();
    int symbol_kind = getDocumentSymbolKind(view_child);
    std::string detail = !view_child.first_child_by_name("type").is_null()
                             ? view_child.first_child_by_name("type").last_as_string()
                             : "";
    // build document symbol object from node child info and push to array
    documentSymbols.push_back(wasp::DataObject());
    wasp::DataObject * data_child = documentSymbols.back().to_object();
    pass &= wasp::lsp::buildDocumentSymbolObject(*data_child,
                                                 errors,
                                                 name,
                                                 detail,
                                                 symbol_kind,
                                                 false,
                                                 line,
                                                 column,
                                                 last_line,
                                                 last_column,
                                                 line,
                                                 column,
                                                 last_line,
                                                 last_column);
    // call method to recursively fill document symbols for each node child
    pass &= traverseParseTreeAndFillSymbols(view_child, *data_child);
  }
  return pass;
}
getActionParameters()
void MooseServer::getActionParameters (InputParameters & valid_params, const std::string & object_path, std::set< std::string > & obj_act_tasks) private
Get all action parameters using requested object path to collection.
Parameters
valid_params - collection for filling action input parameters
object_path - full node path where autocomplete was requested
obj_act_tasks - set for adding in all MooseObjectAction tasks
Definition at line 287 of file MooseServer.C.
{
  Syntax & syntax = _check_app->syntax();
  ActionFactory & action_factory = _check_app->getActionFactory();
  // get registered syntax path identifier using actual object context path
  bool is_parent;
  std::string registered_syntax = syntax.isAssociated(object_path, &is_parent);
  // use is_parent to skip action parameters when not explicitly registered
  if (!is_parent)
  {
    // get action objects associated with registered syntax path identifier
    auto action_range = syntax.getActions(registered_syntax);
    // traverse action objects for syntax to gather valid action parameters
    for (auto action_iter = action_range.first; action_iter != action_range.second; action_iter++)
    {
      const std::string & action_name = action_iter->second._action;
      // use action name to get set of valid parameters from action factory
      InputParameters action_params = action_factory.getValidParams(action_name);
      // gather all MooseObjectAction tasks for verifying object parameters
      if (action_params.have_parameter<bool>("isObjectAction"))
      {
        if (action_params.get<bool>("isObjectAction"))
        {
          std::set<std::string> tasks_by_actions = action_factory.getTasksByAction(action_name);
          obj_act_tasks.insert(tasks_by_actions.begin(), tasks_by_actions.end());
        }
        // filter parameter from completion list as it is not used in input
        action_params.remove("isObjectAction");
      }
      // add parameters from action to full valid collection being gathered
      valid_params += action_params;
    }
  }
}
Referenced by getAllValidParameters().
getAllValidParameters()
void MooseServer::getAllValidParameters (InputParameters & valid_params, const std::string & object_path, const std::string & object_type, std::set< std::string > & obj_act_tasks) private
Get all global parameters, action parameters, and object parameters.
Parameters
valid_params - collection to fill with valid input parameters
object_path - full node path where autocomplete was requested
object_type - type of object where autocomplete was requested
obj_act_tasks - set for adding in all MooseObjectAction tasks
Definition at line 275 of file MooseServer.C.
{
  // gather global parameters then action parameters then object parameters
  valid_params = Parser::validParams();
  getActionParameters(valid_params, object_path, obj_act_tasks);
  getObjectParameters(valid_params, object_type, obj_act_tasks);
}
Referenced by gatherDocumentCompletionItems(), and gatherDocumentDefinitionLocations().
getCompletionItemKind()
int MooseServer::getCompletionItemKind (const InputParameters & valid_params, const std::string & param_name, const std::string & clean_type, bool is_param) private
Get completion item kind value that client may use for icon in list.
Parameters
valid_params - valid parameters used for completion item kind
param_name - name of input parameter for completion item kind
clean_type - type to decide if reference completion item kind
is_param - boolean denoting if kind is for parameter or value
Returns
- enumerated kind value that client may use for icon in list
Definition at line 1086 of file MooseServer.C.
{
  // set up completion item kind value that client may use for icon in list
  auto associated_types = _check_app->syntax().getAssociatedTypes();
  if (is_param && valid_params.isParamRequired(param_name))
    return wasp::lsp::m_comp_kind_event;
  else if (param_name == "active" || param_name == "inactive")
    return wasp::lsp::m_comp_kind_class;
  else if (clean_type == "bool")
    return wasp::lsp::m_comp_kind_interface;
  else if (valid_params.have_parameter<MooseEnum>(param_name) ||
           valid_params.have_parameter<MultiMooseEnum>(param_name) ||
           valid_params.have_parameter<ExecFlagEnum>(param_name) ||
           valid_params.have_parameter<std::vector<MooseEnum>>(param_name))
    return is_param ? wasp::lsp::m_comp_kind_enum : wasp::lsp::m_comp_kind_enum_member;
  else if (param_name == "type")
    return wasp::lsp::m_comp_kind_type_param;
  else if (std::find_if(associated_types.begin(),
                        associated_types.end(),
                        [&](const auto & entry)
                        { return entry.second == clean_type; }) != associated_types.end())
    return wasp::lsp::m_comp_kind_reference;
  else
    return is_param ? wasp::lsp::m_comp_kind_keyword : wasp::lsp::m_comp_kind_value;
}
Referenced by addParametersToList(), and addValuesToList().
getConnection()
std::shared_ptr< wasp::lsp::Connection > MooseServer::getConnection () inline
Get read / write connection - specific to this server implemention.
Returns
- shared pointer to the server's read / write connection
Definition at line 39 of file MooseServer.h.
{ return _connection; }
getDocumentSymbolKind()
int MooseServer::getDocumentSymbolKind (wasp::HITNodeView symbol_node) private
Get document symbol kind value that client may use for outline icon.
Parameters
symbol_node - node that will be added to symbol tree for kind
Returns
- enumerated kind value that client may use for outline icon
Definition at line 1116 of file MooseServer.C.
{
  // lambdas that check if parameter is a boolean or number for symbol kind
  auto is_boolean = [](wasp::HITNodeView symbol_node)
  {
    bool convert;
    std::istringstream iss(MooseUtils::toLower(symbol_node.last_as_string()));
    return (iss >> std::boolalpha >> convert && !iss.fail());
  };
  auto is_number = [](wasp::HITNodeView symbol_node)
  {
    double convert;
    std::istringstream iss(symbol_node.last_as_string());
    return (iss >> convert && iss.eof());
  };
  // set up document symbol kind value that client may use for outline icon
  if (symbol_node.type() == wasp::OBJECT)
    return wasp::lsp::m_symbol_kind_struct;
  else if (symbol_node.type() == wasp::FILE)
    return wasp::lsp::m_symbol_kind_file;
  else if (symbol_node.type() == wasp::ARRAY)
    return wasp::lsp::m_symbol_kind_array;
  else if (symbol_node.type() == wasp::KEYED_VALUE && symbol_node.name() == std::string("type"))
    return wasp::lsp::m_symbol_kind_type_param;
  else if (symbol_node.type() == wasp::KEYED_VALUE && is_boolean(symbol_node))
    return wasp::lsp::m_symbol_kind_boolean;
  else if (symbol_node.type() == wasp::KEYED_VALUE && is_number(symbol_node))
    return wasp::lsp::m_symbol_kind_number;
  else if (symbol_node.type() == wasp::KEYED_VALUE)
    return wasp::lsp::m_symbol_kind_key;
  else if (symbol_node.type() == wasp::VALUE)
    return wasp::lsp::m_symbol_kind_string;
  else
    return wasp::lsp::m_symbol_kind_property;
}
Referenced by gatherDocumentSymbols(), and traverseParseTreeAndFillSymbols().
getEnumsAndDocs()
template<typename MooseEnumType > void MooseServer::getEnumsAndDocs (MooseEnumType & moose_enum_param, std::map< std::string, std::string > & options_and_descs) private
Fill map of all options and descriptions if parameter is moose enum.
Parameters
moose_enum_param - parameter to get documentation and options
options_and_descs - map to fill with options and descriptions
Definition at line 734 of file MooseServer.C.
{
  // get map that contains any documentation strings provided for each item
  const auto & enum_docs = moose_enum_param.getItemDocumentation();
  // walk over enums filling map with options and any provided descriptions
  for (const auto & item : moose_enum_param.items())
    options_and_descs[item.name()] = enum_docs.count(item) ? enum_docs.at(item) : "";
}
Referenced by addParametersToList(), and addValuesToList().
getExistingInput()
void MooseServer::getExistingInput (wasp::HITNodeView parent_node, std::set< std::string > & existing_params, std::set< std::string > & existing_subblocks) private
Get names of parameters and subblocks specified in given input node.
Parameters
parent_node - object node context under which to gather input
existing_params - set to fill with parameter names from input
existing_subblocks - set to fill with subblock names in input
Definition at line 257 of file MooseServer.C.
{
  // gather names of all parameters and subblocks provided in input context
  for (auto itr = parent_node.begin(); itr != parent_node.end(); itr.next())
  {
    auto child_node = itr.get();
    // add key value or array type as parameter and object type as subblock
    if (child_node.type() == wasp::KEYED_VALUE || child_node.type() == wasp::ARRAY)
      existing_params.insert(child_node.name());
    else if (child_node.type() == wasp::OBJECT)
      existing_subblocks.insert(child_node.name());
  }
}
Referenced by gatherDocumentCompletionItems().
getInputLookupDefinitionNodes()
void MooseServer::getInputLookupDefinitionNodes (SortedLocationNodes & location_nodes, const std::string & clean_type, const std::string & val_string) private
Get set of nodes from associated path lookups matching value string.
Parameters
location_nodes - set to fill with lookup nodes matching value
clean_type - cpp type string used for key finding input paths
val_string - specified value used for gathering input lookups
Definition at line 849 of file MooseServer.C.
{
  Syntax & syntax = _check_app->syntax();
  // build map from parameter types to input lookup paths and save to reuse
  if (_type_to_input_paths.empty())
  {
    for (const auto & associated_types_iter : syntax.getAssociatedTypes())
    {
      const std::string & type = associated_types_iter.second;
      const std::string & path = associated_types_iter.first;
      _type_to_input_paths[type].insert(path);
    }
  }
  // find set of input lookup paths that are associated with parameter type
  const auto & input_path_iter = _type_to_input_paths.find(clean_type);
  // return without any definition locations added when no paths associated
  if (input_path_iter == _type_to_input_paths.end())
    return;
  // get root node from input to use in input lookups with associated paths
  wasp::HITNodeView view_root = _check_app->parser()._root->getNodeView();
  // walk over all syntax paths that are associated with parameter type
  for (const auto & input_path : input_path_iter->second)
  {
    // use wasp siren to gather all nodes from current lookup path in input
    wasp::SIRENInterpreter<> selector;
    if (!selector.parseString(input_path))
      continue;
    wasp::SIRENResultSet<wasp::HITNodeView> results;
    std::size_t count = selector.evaluate(view_root, results);
    // walk over results and add nodes that have name matching value to set
    for (std::size_t i = 0; i < count; i++)
      if (results.adapted(i).type() == wasp::OBJECT && results.adapted(i).name() == val_string &&
          results.adapted(i).child_count_by_name("decl"))
        location_nodes.insert(results.adapted(i).first_child_by_name("decl"));
  }
}
Referenced by gatherDocumentDefinitionLocations().
getObjectParameters()
void MooseServer::getObjectParameters (InputParameters & valid_params, std::string object_type, const std::set< std::string > & obj_act_tasks) private
Get all object parameters using requested object path to collection.
Parameters
valid_params - collection for filling object input parameters
object_type - type of object where autocomplete was requested
obj_act_tasks - tasks to verify object type with valid syntax
Definition at line 332 of file MooseServer.C.
{
  Syntax & syntax = _check_app->syntax();
  Factory & factory = _check_app->getFactory();
  // use type parameter default if it exists and is not provided from input
  if (object_type.empty() && valid_params.have_parameter<std::string>("type") &&
      !valid_params.get<std::string>("type").empty())
  {
    object_type = valid_params.get<std::string>("type");
    // make type parameter not required in input since it has default value
    valid_params.makeParamNotRequired("type");
  }
  // check if object type has been registered to prevent unregistered error
  if (factory.isRegistered(object_type))
  {
    // use object type to get set of valid parameters registered in factory
    InputParameters object_params = factory.getValidParams(object_type);
    // check if object has base associated with any MooseObjectAction tasks
    if (object_params.have_parameter<std::string>("_moose_base"))
    {
      const std::string & moose_base = object_params.get<std::string>("_moose_base");
      for (const auto & obj_act_task : obj_act_tasks)
      {
        if (syntax.verifyMooseObjectTask(moose_base, obj_act_task))
        {
          // add parameters from object to valid collection if base matches
          valid_params += object_params;
          break;
        }
      }
    }
  }
  // make parameters from list of those set by action not required in input
  if (valid_params.have_parameter<std::vector<std::string>>("_object_params_set_by_action"))
  {
    auto names = valid_params.get<std::vector<std::string>>("_object_params_set_by_action");
    for (const auto & name : names)
      valid_params.makeParamNotRequired(name);
    // filter parameter from completion list since it is not used for input
    valid_params.remove("_object_params_set_by_action");
  }
}
Referenced by getAllValidParameters().
parseDocumentForDiagnostics()
bool MooseServer::parseDocumentForDiagnostics (wasp::DataArray & diagnosticsList) private
Parse document for diagnostics - specific to this server implemention.
Parameters
diagnosticsList - data array of diagnostics data objects to fill
Returns
- true if completed successfully - does not indicate parse fail
Definition at line 51 of file MooseServer.C.
{
  // strip prefix from document uri if it exists to get parse file path
  std::string parse_file_path = document_path;
  pcrecpp::RE("(.*://)(.*)").Replace("\\2", &parse_file_path);
  // copy parent application parameters and modify to set up input check
  InputParameters app_params = _moose_app.parameters();
  app_params.set<std::vector<std::string>>("input_file") = {parse_file_path};
  app_params.set<std::string>("_input_text") = document_text;
  app_params.set<bool>("check_input") = true;
  app_params.set<bool>("error_unused") = true;
  app_params.set<bool>("error") = true;
  app_params.set<bool>("error_deprecated") = true;
  app_params.set<std::string>("color") = "off";
  app_params.set<bool>("disable_perf_graph_live") = true;
  app_params.remove("language_server");
  // turn output off so input check application does not affect messages
  std::streambuf * cached_output_buffer = Moose::out.rdbuf(nullptr);
  // create new application with parameters modified for input check run
  _check_app = AppFactory::instance().createShared(
      _moose_app.type(), _moose_app.name(), app_params, _moose_app.getCommunicator()->get());
  // disable logs and enable error exceptions with initial values cached
  bool cached_logging_enabled = Moose::perf_log.logging_enabled();
  Moose::perf_log.disable_logging();
  bool cached_throw_on_error = Moose::_throw_on_error;
  Moose::_throw_on_error = true;
  bool pass = true;
  // run input check application converting caught errors to diagnostics
  try
  {
    _check_app->run();
  }
  catch (std::exception & err)
  {
    int line_number = 1;
    int column_number = 1;
    std::istringstream caught_msg(err.what());
    // walk over caught message line by line adding each as a diagnostic
    for (std::string error_line; std::getline(caught_msg, error_line);)
    {
      // skip over lines that are blank or consist totally of whitespace
      if (error_line.find_first_not_of(" \t") == std::string::npos)
        continue;
      // check if this error line already has the input file path prefix
      if (error_line.rfind(parse_file_path + ":", 0) == 0)
      {
        // strip input file path and colon prefix off of this error line
        error_line.erase(0, parse_file_path.size() + 1);
        int match_line_number;
        int match_column_number;
        std::string match_error_line;
        // get line and column number from this error line if both exist
        if (pcrecpp::RE("^(\\d+)\\.(\\d+)\\-?\\d*:\\s*(.*)$")
                .FullMatch(error_line, &match_line_number, &match_column_number, &match_error_line))
        {
          line_number = match_line_number;
          column_number = match_column_number;
          error_line = match_error_line;
        }
        // otherwise get line number off of this error line if it exists
        else if (pcrecpp::RE("^(\\d+):\\s*(.*)$")
                     .FullMatch(error_line, &match_line_number, &match_error_line))
        {
          line_number = match_line_number;
          column_number = 1;
          error_line = match_error_line;
        }
      }
      // build zero based line and column diagnostic and add to the list
      diagnosticsList.push_back(wasp::DataObject());
      wasp::DataObject * diagnostic = diagnosticsList.back().to_object();
      pass &= wasp::lsp::buildDiagnosticObject(*diagnostic,
                                               errors,
                                               line_number - 1,
                                               column_number - 1,
                                               line_number - 1,
                                               column_number - 1,
                                               1,
                                               "moose_srv",
                                               "check_inp",
                                               error_line);
    }
  }
  // reset behaviors of performance logging and error exception throwing
  if (cached_logging_enabled)
    Moose::perf_log.enable_logging();
  Moose::_throw_on_error = cached_throw_on_error;
  // turn output back on since it was turned off and input check is done
  Moose::out.rdbuf(cached_output_buffer);
  return pass;
}
traverseParseTreeAndFillSymbols()
bool MooseServer::traverseParseTreeAndFillSymbols (wasp::HITNodeView view_parent, wasp::DataObject & data_parent) private
Recursively fill document symbols from the given node.
Parameters
view_parent - nodeview used in recursive tree traversal
data_parent - data object with array of symbol children
Returns
- true if no problems with this level of the resursion
Definition at line 1035 of file MooseServer.C.
{
  // return without adding any children if parent node is file include type
  if (wasp::is_nested_file(view_parent))
    return true;
  bool pass = true;
  // walk over all children of this node context and build document symbols
  for (const auto i : make_range(view_parent.child_count()))
  {
    // walk must be index based to catch file include and skip its children
    wasp::HITNodeView view_child = view_parent.child_at(i);
    // set up name, zero based line and column range, kind, and detail info
    std::string name = view_child.name();
    int line = view_child.line() - 1;
    int column = view_child.column() - 1;
    int last_line = view_child.last_line() - 1;
    int last_column = view_child.last_column();
    int symbol_kind = getDocumentSymbolKind(view_child);
    std::string detail = !view_child.first_child_by_name("type").is_null()
                             ? view_child.first_child_by_name("type").last_as_string()
                             : "";
    // build document symbol object from node child info and push to array
    wasp::DataObject & data_child = wasp::lsp::addDocumentSymbolChild(data_parent);
    pass &= wasp::lsp::buildDocumentSymbolObject(data_child,
                                                 errors,
                                                 name,
                                                 detail,
                                                 symbol_kind,
                                                 false,
                                                 line,
                                                 column,
                                                 last_line,
                                                 last_column,
                                                 line,
                                                 column,
                                                 last_line,
                                                 last_column);
    // call method to recursively fill document symbols for each node child
    pass &= traverseParseTreeAndFillSymbols(view_child, data_child);
  }
  return pass;
}
Referenced by gatherDocumentSymbols(), and traverseParseTreeAndFillSymbols().
updateDocumentTextChanges()
bool MooseServer::updateDocumentTextChanges (const std::string & replacement_text, int start_line, int start_character, int end_line, int end_character, int range_length) private
Update document text changes - specific to this server implemention.
Parameters
replacement_text - text to be replaced over the provided range
start_line - starting replace line number (zero-based)
start_character - starting replace column number (zero-based)
end_line - ending replace line number (zero-based)
end_character - ending replace column number (zero-based)
range_length - length of replace range - server specific
Returns
- true if the document text was updated successfully
Definition at line 160 of file MooseServer.C.
{
  // replacement text swaps full document as indicated in server capabilities
  document_text = replacement_text;
  return true;
}
Member Data Documentation
_check_app
std::shared_ptr<MooseApp> MooseServer::_check_app private
_check_app - application created to check input and access parser
Definition at line 299 of file MooseServer.h.
Referenced by addSubblocksToList(), addValuesToList(), gatherDocumentCompletionItems(), gatherDocumentDefinitionLocations(), gatherDocumentFormattingTextEdits(), gatherDocumentSymbols(), getActionParameters(), getCompletionItemKind(), getInputLookupDefinitionNodes(), getObjectParameters(), and parseDocumentForDiagnostics().
_connection
std::shared_ptr<wasp::lsp::IOStreamConnection> MooseServer::_connection private
_connection - shared pointer to this server's read / write iostream
Definition at line 304 of file MooseServer.h.
Referenced by connectionRead(), connectionWrite(), and getConnection().
_moose_app
MooseApp& MooseServer::_moose_app private
_moose_app - reference to parent application that owns this server
Definition at line 294 of file MooseServer.h.
Referenced by parseDocumentForDiagnostics().
_syntax_to_subblocks
std::map<std::string, std::set<std::string> > MooseServer::_syntax_to_subblocks private
_syntax_to_subblocks - map of syntax paths to valid subblocks
Definition at line 309 of file MooseServer.h.
Referenced by addSubblocksToList().
_type_to_input_paths
std::map<std::string, std::set<std::string> > MooseServer::_type_to_input_paths private
_type_to_input_paths - map of parameter types to lookup paths
Definition at line 314 of file MooseServer.h.
Referenced by addValuesToList(), and getInputLookupDefinitionNodes().
The documentation for this class was generated from the following files:
moose/framework/include/base/MooseServer.h
moose/framework/src/base/MooseServer.C