Zapdos: BoundaryRestrictableRequired Class Reference
BoundaryRestrictableRequired Class Reference
A class for requiring an object to be boundary restricted.
#include <BoundaryRestrictableRequired.h>
Public Types
enum TEST_TYPE { ALL , ANY }
A flag changing the behavior of hasBoundary.
Public Member Functions
BoundaryRestrictableRequired (const MooseObject *moose_object, bool nodal)
virtual const std::set< BoundaryID > & boundaryIDs () const
Return the boundary IDs for this object.
const std::vector< BoundaryName > & boundaryNames () const
Return the boundary names for this object.
unsigned int numBoundaryIDs () const
Return the number of boundaries for this object.
bool hasBoundary (const BoundaryName &name) const
Test if the supplied boundary name is valid for this object.
bool hasBoundary (const std::vector< BoundaryName > &names) const
Test if the supplied vector of boundary names are valid for this object.
bool hasBoundary (const BoundaryID &id) const
Test if the supplied boundary ids are valid for this object.
bool hasBoundary (const std::vector< BoundaryID > &ids, TEST_TYPE type=ALL) const
Test if the supplied vector boundary ids are valid for this object.
bool hasBoundary (const std::set< BoundaryID > &ids, TEST_TYPE type=ALL) const
Test if the supplied set of boundary ids are valid for this object.
bool isBoundarySubset (const std::set< BoundaryID > &ids) const
Test if the class boundary ids are a subset of the supplied objects.
bool isBoundarySubset (const std::vector< BoundaryID > &ids) const
template<typename T , bool is_ad = false>
bool hasBoundaryMaterialProperty (const std::string &prop_name) const
Check if a material property is valid for all boundaries of this object.
virtual bool boundaryRestricted () const
Returns true if this object has been restricted to a boundary.
const std::set< BoundaryID > & meshBoundaryIDs () const
Returns the set of all boundary ids for the entire mesh.
virtual bool checkVariableBoundaryIntegrity () const
Whether integrity/coverage checking should be conducted for moose variables used in this object.
Static Public Member Functions
static InputParameters validParams ()
static bool restricted (const std::set< BoundaryID > &ids)
Helper for determining if the object is boundary restricted.
Protected Member Functions
bool hasBoundaryMaterialPropertyHelper (const std::string &prop_name) const
A helper method to avoid circular #include problems.
Private Member Functions
void initializeBoundaryRestrictable ()
An initialization routine needed for dual constructors.
Private Attributes
FEProblemBase * _bnd_feproblem
Pointer to FEProblemBase.
MooseMesh * _bnd_mesh
Point to mesh.
std::set< BoundaryID > _bnd_ids
Set of the boundary ids.
std::vector< BoundaryID > _vec_ids
Vector of the boundary ids.
std::vector< BoundaryName > _boundary_names
Vector the the boundary names.
const bool _bnd_dual_restrictable
Flag for allowing dual restriction with BlockRestrictable.
const std::set< SubdomainID > _empty_block_ids
An empty set for referencing when block_ids is not included.
const std::set< SubdomainID > & _block_ids
Reference to the block_ids, defaults to an empty set if not provided.
THREAD_ID _bnd_tid
Thread id for this object.
const MaterialData & _bnd_material_data
Pointer to MaterialData for boundary (.
bool _bnd_nodal
Whether or not this object is restricted to nodesets.
const MooseObject & _moose_object
The moose object that this is an interface for.
Detailed Description
A class for requiring an object to be boundary restricted.
This class acts as a wrapper for BoundaryRestrictable, it allows an additional validParams that adds the 'boundary' parameter as required.
Definition at line 21 of file BoundaryRestrictableRequired.h.
Member Enumeration Documentation
TEST_TYPE
enum BoundaryRestrictable::TEST_TYPE inherited
A flag changing the behavior of hasBoundary.
Enumerator
ALL
ANY
Definition at line 29 of file BoundaryRestrictable.h.
  {
    ALL,
    ANY
  };
Constructor & Destructor Documentation
BoundaryRestrictableRequired()
BoundaryRestrictableRequired::BoundaryRestrictableRequired (const MooseObject * moose_object, bool nodal)
Definition at line 33 of file BoundaryRestrictableRequired.C.
  : BoundaryRestrictable(moose_object, nodal)
{
}
Member Function Documentation
boundaryIDs()
const std::set< BoundaryID > & BoundaryRestrictable::boundaryIDs () const virtual inherited
Return the boundary IDs for this object.
Returns
A set of all boundary ids for which the object is restricted
Definition at line 180 of file BoundaryRestrictable.C.
{
  return _bnd_ids;
}
Referenced by MaterialBase::getGenericZeroMaterialPropertyByName(), BoundaryRestrictable::hasBoundaryMaterialPropertyHelper(), SidesetInfoVectorPostprocessor::initialize(), InterfaceQpUserObjectBase::initialSetup(), and MaterialBase::registerPropName().
boundaryNames()
const std::vector< BoundaryName > & BoundaryRestrictable::boundaryNames () const inherited
Return the boundary names for this object.
Returns
A set of all boundary names for which the object is restricted
Definition at line 186 of file BoundaryRestrictable.C.
{
  return _boundary_names;
}
Referenced by MaterialOutputAction::getParams(), NearestNodeDistanceAux::NearestNodeDistanceAux(), and NearestNodeValueAux::NearestNodeValueAux().
boundaryRestricted()
bool BoundaryRestrictable::boundaryRestricted () const virtual inherited
Returns true if this object has been restricted to a boundary.
See also
MooseObject
Definition at line 198 of file BoundaryRestrictable.C.
{
  return BoundaryRestrictable::restricted(_bnd_ids);
}
Referenced by ADSurfaceCharge::computeQpProperties(), MaterialOutputAction::getParams(), and DerivativeMaterialInterface< T >::haveMaterialProperty().
checkVariableBoundaryIntegrity()
virtual bool BoundaryRestrictable::checkVariableBoundaryIntegrity () const inline virtual inherited
Whether integrity/coverage checking should be conducted for moose variables used in this object.
This should return true if variables are only evaluated locally, e.g. on the current node or element. This should return false if evaluation of this object entails non-local variable evaluations
Definition at line 179 of file BoundaryRestrictable.h.
{ return true; }
hasBoundary() [1/5]
bool BoundaryRestrictable::hasBoundary (const BoundaryID & id) const inherited
Test if the supplied boundary ids are valid for this object.
Parameters
id A BoundaryID to check
Returns
True if the given id is valid for this object
Definition at line 224 of file BoundaryRestrictable.C.
{
  if (_bnd_ids.empty() || _bnd_ids.find(Moose::ANY_BOUNDARY_ID) != _bnd_ids.end())
    return true;
  else
    return _bnd_ids.find(id) != _bnd_ids.end();
}
hasBoundary() [2/5]
bool BoundaryRestrictable::hasBoundary (const BoundaryName & name) const inherited
Test if the supplied boundary name is valid for this object.
Parameters
name A BoundaryName to check
Returns
True if the given id is valid for this object
Definition at line 210 of file BoundaryRestrictable.C.
{
  // Create a vector and utilize the getBoundaryIDs function, which
  // handles the ANY_BOUNDARY_ID (getBoundaryID does not)
  return hasBoundary(_bnd_mesh->getBoundaryIDs({name}));
}
Referenced by BoundaryRestrictable::hasBoundary(), and BoundaryRestrictable::hasBoundaryMaterialPropertyHelper().
hasBoundary() [3/5]
bool BoundaryRestrictable::hasBoundary (const std::set< BoundaryID > & ids, TEST_TYPE type = ALL) const inherited
Test if the supplied set of boundary ids are valid for this object.
Parameters
ids A std::set of BoundaryIDs to check
type A flag for the type of matching to perform: ALL requires that all supplied ids must match those of the object; ANY requires that any one of the supplied ids must match those of the object
Returns
True if the all of the given ids are found within the ids for this object
See also
isSubset
Definition at line 240 of file BoundaryRestrictable.C.
{
  // An empty input is assumed to be ANY_BOUNDARY_ID
  if (ids.empty() || ids.find(Moose::ANY_BOUNDARY_ID) != ids.end())
    return true;
  // All supplied IDs must match those of the object
  else if (type == ALL)
  {
    if (_bnd_ids.find(Moose::ANY_BOUNDARY_ID) != _bnd_ids.end())
      return true;
    else
      return std::includes(_bnd_ids.begin(), _bnd_ids.end(), ids.begin(), ids.end());
  }
  // Any of the supplied IDs must match those of the object
  else
  {
    // Loop through the supplied ids
    for (const auto & id : ids)
    {
      // Test the current supplied id
      bool test = hasBoundary(id);
      // If the id exists in the stored ids, then return true, otherwise
      if (test)
        return true;
    }
    return false;
  }
}
hasBoundary() [4/5]
bool BoundaryRestrictable::hasBoundary (const std::vector< BoundaryID > & ids, TEST_TYPE type = ALL) const inherited
Test if the supplied vector boundary ids are valid for this object.
Parameters
ids A vector of BoundaryIDs ids to check
type A flag for the type of matching to perform: ALL requires that all supplied ids must match those of the object; ANY requires that any one of the supplied ids must match those of the object
Returns
True if the all of the given ids are found within the ids for this object
Definition at line 233 of file BoundaryRestrictable.C.
{
  std::set<BoundaryID> ids_set(ids.begin(), ids.end());
  return hasBoundary(ids_set, type);
}
hasBoundary() [5/5]
bool BoundaryRestrictable::hasBoundary (const std::vector< BoundaryName > & names) const inherited
Test if the supplied vector of boundary names are valid for this object.
Parameters
names A vector of BoundaryNames to check
Returns
True if the given ids are valid for this object
Definition at line 218 of file BoundaryRestrictable.C.
{
  return hasBoundary(_bnd_mesh->getBoundaryIDs(names));
}
hasBoundaryMaterialProperty()
template<typename T , bool is_ad> bool BoundaryRestrictable::hasBoundaryMaterialProperty (const std::string & prop_name) const inherited
Check if a material property is valid for all boundaries of this object.
This method returns true if the supplied property name has been declared in a Material object on the boundary ids for this object.
Template Parameters
T The type of material property
Parameters
prop_name the name of the property to query
Returns
true if the property exists for all boundary ids of the object, otherwise false
Definition at line 233 of file BoundaryRestrictable.h.
{
  // If you get here the supplied property is defined on all boundaries, but is still subject
  // existence in the MateialData class
  return hasBoundaryMaterialPropertyHelper(prop_name) &&
         _bnd_material_data.haveGenericProperty<T, is_ad>(prop_name);
}
hasBoundaryMaterialPropertyHelper()
bool BoundaryRestrictable::hasBoundaryMaterialPropertyHelper (const std::string & prop_name) const protected inherited
A helper method to avoid circular #include problems.
See also
hasBoundaryMaterialProperty
Definition at line 301 of file BoundaryRestrictable.C.
{
  // Reference to MaterialWarehouse for testing and retrieving boundary ids
  const MaterialWarehouse & warehouse = _bnd_feproblem->getMaterialWarehouse();
  // Complete set of BoundaryIDs that this object is defined
  const std::set<BoundaryID> & ids =
      hasBoundary(Moose::ANY_BOUNDARY_ID) ? meshBoundaryIDs() : boundaryIDs();
  // Loop over each BoundaryID for this object
  for (const auto & id : ids)
  {
    // Storage of material properties that have been DECLARED on this BoundaryID
    std::set<std::string> declared_props;
    // If boundary materials exist, populated the set of properties that were declared
    if (warehouse.hasActiveBoundaryObjects(id))
    {
      const std::vector<std::shared_ptr<MaterialBase>> & mats =
          warehouse.getActiveBoundaryObjects(id);
      for (const auto & mat : mats)
      {
        const std::set<std::string> & mat_props = mat->getSuppliedItems();
        declared_props.insert(mat_props.begin(), mat_props.end());
      }
    }
    // If the supplied property is not in the list of properties on the current id, return false
    if (declared_props.find(prop_name) == declared_props.end())
      return false;
  }
  // If you get here the supplied property is defined on all boundaries
  return true;
}
Referenced by BoundaryRestrictable::hasBoundaryMaterialProperty().
initializeBoundaryRestrictable()
void BoundaryRestrictable::initializeBoundaryRestrictable () private inherited
An initialization routine needed for dual constructors.
Definition at line 72 of file BoundaryRestrictable.C.
{
  // The name and id of the object
  const std::string & name = _moose_object.getParam<std::string>("_object_name");
  // If the mesh pointer is not defined, but FEProblemBase is, get it from there
  if (_bnd_feproblem != NULL && _bnd_mesh == NULL)
    _bnd_mesh = &_bnd_feproblem->mesh();
  // Check that the mesh pointer was defined, it is required for this class to operate
  if (_bnd_mesh == NULL)
    mooseError("The input parameters must contain a pointer to FEProblemBase via '_fe_problem' or "
               "a pointer to the MooseMesh via '_mesh'");
  // If the user supplies boundary IDs
  if (_moose_object.isParamValid("boundary"))
  {
    // Extract the blocks from the input
    _boundary_names = _moose_object.getParam<std::vector<BoundaryName>>("boundary");
    // Get the IDs from the supplied names
    _vec_ids = _bnd_mesh->getBoundaryIDs(_boundary_names, true);
    // Store the IDs, handling ANY_BOUNDARY_ID if supplied
    if (std::find(_boundary_names.begin(), _boundary_names.end(), "ANY_BOUNDARY_ID") !=
        _boundary_names.end())
      _bnd_ids.insert(Moose::ANY_BOUNDARY_ID);
    else
      _bnd_ids.insert(_vec_ids.begin(), _vec_ids.end());
  }
  // Produce error if the object is not allowed to be both block and boundary restricted
  if (!_bnd_dual_restrictable && !_bnd_ids.empty() && !_block_ids.empty())
    if (!_block_ids.empty() && _block_ids.find(Moose::ANY_BLOCK_ID) == _block_ids.end())
      _moose_object.paramError("boundary",
                               "Attempted to restrict the object '",
                               name,
                               "' to a boundary, but the object is already restricted by block(s)");
  // Store ANY_BOUNDARY_ID if empty
  if (_bnd_ids.empty())
  {
    _bnd_ids.insert(Moose::ANY_BOUNDARY_ID);
    _boundary_names = {"ANY_BOUNDARY_ID"};
  }
  // If this object is block restricted, check that defined blocks exist on the mesh
  if (_bnd_ids.find(Moose::ANY_BOUNDARY_ID) == _bnd_ids.end())
  {
    const std::set<BoundaryID> * valid_ids;
    const char * message_ptr = nullptr;
    if (_bnd_nodal)
    {
      valid_ids = &_bnd_mesh->meshNodesetIds();
      message_ptr = "node sets";
    }
    else
    {
      valid_ids = &_bnd_mesh->meshSidesetIds();
      message_ptr = "side sets";
    }
    std::vector<BoundaryID> diff;
    std::set_difference(_bnd_ids.begin(),
                        _bnd_ids.end(),
                        valid_ids->begin(),
                        valid_ids->end(),
                        std::back_inserter(diff));
    if (!diff.empty())
    {
      std::ostringstream msg;
      auto sep = " ";
      msg << "the following " << message_ptr << " (ids) do not exist on the mesh:";
      for (const auto & id : diff)
      {
        if (_boundary_names.size() > 0)
        {
          auto & name = _boundary_names.at(std::find(_vec_ids.begin(), _vec_ids.end(), id) -
                                           _vec_ids.begin());
          if (std::to_string(id) != name)
            msg << sep << name << " (" << id << ")";
          else
            msg << sep << id;
        }
        else
          msg << sep << id;
        sep = ", ";
      }
      if (!_bnd_nodal)
        // Diagnostic message
        msg << "\n\nMOOSE distinguishes between \"node sets\" and \"side sets\" depending on "
               "whether \nyou are using \"Nodal\" or \"Integrated\" BCs respectively. Node sets "
               "corresponding \nto your side sets are constructed for you by default.\n\n"
               "Try setting \"Mesh/construct_side_list_from_node_list=true\" if you see this "
               "error.\n"
               "Note: If you are running with adaptivity you should prefer using side sets.";
      _moose_object.paramError("boundary", msg.str());
    }
  }
}
Referenced by BoundaryRestrictable::BoundaryRestrictable().
isBoundarySubset() [1/2]
bool BoundaryRestrictable::isBoundarySubset (const std::set< BoundaryID > & ids) const inherited
Test if the class boundary ids are a subset of the supplied objects.
Parameters
ids A std::set of boundaries to check
Returns
True if all of the boundary ids for this class are found within the given ids (opposite of hasBoundary)
See also
hasBoundary
Definition at line 272 of file BoundaryRestrictable.C.
{
  // An empty input is assumed to be ANY_BOUNDARY_ID
  if (ids.empty() || ids.find(Moose::ANY_BOUNDARY_ID) != ids.end())
    return true;
  if (_bnd_ids.find(Moose::ANY_BOUNDARY_ID) != _bnd_ids.end())
    return std::includes(ids.begin(),
                         ids.end(),
                         _bnd_mesh->meshBoundaryIds().begin(),
                         _bnd_mesh->meshBoundaryIds().end());
  else
    return std::includes(ids.begin(), ids.end(), _bnd_ids.begin(), _bnd_ids.end());
}
Referenced by BoundaryRestrictable::isBoundarySubset().
isBoundarySubset() [2/2]
bool BoundaryRestrictable::isBoundarySubset (const std::vector< BoundaryID > & ids) const inherited
Definition at line 288 of file BoundaryRestrictable.C.
{
  std::set<BoundaryID> ids_set(ids.begin(), ids.end());
  return isBoundarySubset(ids_set);
}
meshBoundaryIDs()
const std::set< BoundaryID > & BoundaryRestrictable::meshBoundaryIDs () const inherited
Returns the set of all boundary ids for the entire mesh.
Returns
A const reference the the boundary ids for the entire mesh
Definition at line 295 of file BoundaryRestrictable.C.
{
  return _bnd_mesh->getBoundaryIDs();
}
Referenced by BoundaryRestrictable::hasBoundaryMaterialPropertyHelper().
numBoundaryIDs()
unsigned int BoundaryRestrictable::numBoundaryIDs () const inherited
Return the number of boundaries for this object.
Returns
The number of boundary ids
Definition at line 192 of file BoundaryRestrictable.C.
{
  return (unsigned int)_bnd_ids.size();
}
Referenced by SidesetInfoVectorPostprocessor::initialize().
restricted()
bool BoundaryRestrictable::restricted (const std::set< BoundaryID > & ids) static inherited
Helper for determining if the object is boundary restricted.
This is needed for the MaterialPropertyInterface.
Definition at line 204 of file BoundaryRestrictable.C.
{
  return ids.find(Moose::ANY_BOUNDARY_ID) == ids.end();
}
Referenced by BoundaryRestrictable::boundaryRestricted(), and moose::internal::boundaryRestricted().
validParams()
InputParameters BoundaryRestrictableRequired::validParams () static
Definition at line 15 of file BoundaryRestrictableRequired.C.
{
  // Create instance of InputParameters
  InputParameters params = emptyInputParameters();
  // Create user-facing 'boundary' input for restricting inheriting object to boundaries
  params.addRequiredParam<std::vector<BoundaryName>>(
      "boundary", "The list of boundary IDs from the mesh where this object applies");
  // A parameter for disabling error message for objects restrictable by boundary and block,
  // if the parameter is valid it was already set so don't do anything
  if (!params.isParamValid("_dual_restrictable"))
    params.addPrivateParam<bool>("_dual_restrictable", false);
  return params;
}
Referenced by BoundaryCondition::validParams(), FVBoundaryCondition::validParams(), FVInterfaceKernel::validParams(), InterfaceUserObjectBase::validParams(), and SideUserObject::validParams().
Member Data Documentation
_block_ids
const std::set<SubdomainID>& BoundaryRestrictable::_block_ids private inherited
Reference to the block_ids, defaults to an empty set if not provided.
Definition at line 204 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::initializeBoundaryRestrictable().
_bnd_dual_restrictable
const bool BoundaryRestrictable::_bnd_dual_restrictable private inherited
Flag for allowing dual restriction with BlockRestrictable.
Definition at line 198 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::initializeBoundaryRestrictable().
_bnd_feproblem
FEProblemBase* BoundaryRestrictable::_bnd_feproblem private inherited
Pointer to FEProblemBase.
Definition at line 183 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::hasBoundaryMaterialPropertyHelper(), and BoundaryRestrictable::initializeBoundaryRestrictable().
_bnd_ids
std::set<BoundaryID> BoundaryRestrictable::_bnd_ids private inherited
Set of the boundary ids.
Definition at line 189 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::boundaryIDs(), BoundaryRestrictable::boundaryRestricted(), BoundaryRestrictable::hasBoundary(), BoundaryRestrictable::initializeBoundaryRestrictable(), BoundaryRestrictable::isBoundarySubset(), and BoundaryRestrictable::numBoundaryIDs().
_bnd_material_data
const MaterialData& BoundaryRestrictable::_bnd_material_data private inherited
Pointer to MaterialData for boundary (.
See also
hasBoundaryMaterialProperty)
Definition at line 210 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::hasBoundaryMaterialProperty().
_bnd_mesh
MooseMesh* BoundaryRestrictable::_bnd_mesh private inherited
Point to mesh.
Definition at line 186 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::hasBoundary(), BoundaryRestrictable::initializeBoundaryRestrictable(), BoundaryRestrictable::isBoundarySubset(), and BoundaryRestrictable::meshBoundaryIDs().
_bnd_nodal
bool BoundaryRestrictable::_bnd_nodal private inherited
Whether or not this object is restricted to nodesets.
Definition at line 213 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::initializeBoundaryRestrictable().
_bnd_tid
THREAD_ID BoundaryRestrictable::_bnd_tid private inherited
Thread id for this object.
Definition at line 207 of file BoundaryRestrictable.h.
_boundary_names
std::vector<BoundaryName> BoundaryRestrictable::_boundary_names private inherited
Vector the the boundary names.
Definition at line 195 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::boundaryNames(), and BoundaryRestrictable::initializeBoundaryRestrictable().
_empty_block_ids
const std::set<SubdomainID> BoundaryRestrictable::_empty_block_ids private inherited
An empty set for referencing when block_ids is not included.
Definition at line 201 of file BoundaryRestrictable.h.
_moose_object
const MooseObject& BoundaryRestrictable::_moose_object private inherited
The moose object that this is an interface for.
Definition at line 216 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::initializeBoundaryRestrictable().
_vec_ids
std::vector<BoundaryID> BoundaryRestrictable::_vec_ids private inherited
Vector of the boundary ids.
Definition at line 192 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::initializeBoundaryRestrictable().
The documentation for this class was generated from the following files:
moose/framework/include/interfaces/BoundaryRestrictableRequired.h
moose/framework/src/interfaces/BoundaryRestrictableRequired.C