Zapdos: ArbitraryQuadrature Class Reference
ArbitraryQuadrature Class Reference
Implements a fake quadrature rule where you can specify the locations (in the reference domain) of the quadrature points.
#include <ArbitraryQuadrature.h>
Public Member Functions
ArbitraryQuadrature (const unsigned int _dim, const Order _order=INVALID_ORDER)
ArbitraryQuadrature (const ArbitraryQuadrature &)=default
Copy/move ctor, copy/move assignment operator, and destructor are all explicitly defaulted for this simple class.
ArbitraryQuadrature (ArbitraryQuadrature &&)=default
ArbitraryQuadrature & operator= (const ArbitraryQuadrature &)=default
ArbitraryQuadrature & operator= (ArbitraryQuadrature &&)=default
virtual ~ArbitraryQuadrature ()=default
QuadratureType type () const override
void setPoints (const std::vector< Point > &points)
Set the quadrature points.
void setWeights (const std::vector< Real > &weights)
Set the quadrature weights.
virtual bool shapes_need_reinit () override
virtual std::unique_ptr< QBase > clone () const override
Private Member Functions
void init_1D (const ElemType _type=INVALID_ELEM, unsigned int p_level=0) override
These functions must be defined to fulfill the interface expected by the quadrature initialization routines.
void init_2D (const ElemType _type=INVALID_ELEM, unsigned int p_level=0) override
void init_3D (const ElemType _type=INVALID_ELEM, unsigned int p_level=0) override
Detailed Description
Implements a fake quadrature rule where you can specify the locations (in the reference domain) of the quadrature points.
Definition at line 21 of file ArbitraryQuadrature.h.
Constructor & Destructor Documentation
ArbitraryQuadrature() [1/3]
ArbitraryQuadrature::ArbitraryQuadrature (const unsigned int _dim, const Order _order = INVALID_ORDER)
Definition at line 15 of file ArbitraryQuadrature.C.
: QBase(d, o) {}
ArbitraryQuadrature() [2/3]
ArbitraryQuadrature::ArbitraryQuadrature (const ArbitraryQuadrature &) default
Copy/move ctor, copy/move assignment operator, and destructor are all explicitly defaulted for this simple class.
ArbitraryQuadrature() [3/3]
ArbitraryQuadrature::ArbitraryQuadrature (ArbitraryQuadrature &&) default
~ArbitraryQuadrature()
virtual ArbitraryQuadrature::~ArbitraryQuadrature () virtual default
Member Function Documentation
clone()
std::unique_ptr< QBase > ArbitraryQuadrature::clone () const override virtual
Definition at line 18 of file ArbitraryQuadrature.C.
{
  return std::make_unique<ArbitraryQuadrature>(*this);
}
init_1D()
void ArbitraryQuadrature::init_1D (const ElemType _type = INVALID_ELEM, unsigned int p_level = 0) override private
These functions must be defined to fulfill the interface expected by the quadrature initialization routines.
Please do not modify the function names or signatures.
Definition at line 43 of file ArbitraryQuadrature.C.
{
  this->_type = _type;
  this->_p_level = p_level;
}
init_2D()
void ArbitraryQuadrature::init_2D (const ElemType _type = INVALID_ELEM, unsigned int p_level = 0) override private
Definition at line 50 of file ArbitraryQuadrature.C.
{
  this->_type = _type;
  this->_p_level = p_level;
}
init_3D()
void ArbitraryQuadrature::init_3D (const ElemType _type = INVALID_ELEM, unsigned int p_level = 0) override private
Definition at line 57 of file ArbitraryQuadrature.C.
{
  this->_type = _type;
  this->_p_level = p_level;
}
operator=() [1/2]
ArbitraryQuadrature & ArbitraryQuadrature::operator= (ArbitraryQuadrature &&) default
operator=() [2/2]
ArbitraryQuadrature & ArbitraryQuadrature::operator= (const ArbitraryQuadrature &) default
setPoints()
void ArbitraryQuadrature::setPoints (const std::vector< Point > & points)
Set the quadrature points.
Note that this also sets the quadrature weights to unity
Definition at line 30 of file ArbitraryQuadrature.C.
{
  _points = points;
  _weights.resize(points.size(), 1.0);
}
Referenced by MooseVariableFE< OutputType >::evaluate(), Assembly::reinit(), Assembly::reinitFVFace(), Assembly::reinitLowerDElem(), Assembly::reinitNeighbor(), and Assembly::reinitNeighborFaceRef().
setWeights()
void ArbitraryQuadrature::setWeights (const std::vector< Real > & weights)
Set the quadrature weights.
Definition at line 37 of file ArbitraryQuadrature.C.
{
  _weights = weights;
}
Referenced by Assembly::reinitLowerDElem().
shapes_need_reinit()
virtual bool ArbitraryQuadrature::shapes_need_reinit () inline override virtual
Definition at line 48 of file ArbitraryQuadrature.h.
{ return true; }
type()
QuadratureType ArbitraryQuadrature::type () const override
Definition at line 24 of file ArbitraryQuadrature.C.
{
  return INVALID_Q_RULE;
}
The documentation for this class was generated from the following files:
moose/framework/include/utils/ArbitraryQuadrature.h
moose/framework/src/utils/ArbitraryQuadrature.C