Zapdos: ReporterContextBase Class Reference
ReporterContextBase Class Reference abstract
This is a helper class to aid with parallel communication of compute Reporter values as well as provides a link to the stored Reporter value state object.
#include <ReporterContext.h>
Public Member Functions
ReporterContextBase (const libMesh::ParallelObject &other, const MooseObject &producer)
virtual ~ReporterContextBase ()=default
virtual const ReporterName & name () const =0
Return the ReporterName that the context is associated.
virtual std::string type () const =0
Return the type of the data stored.
virtual std::string contextType () const =0
virtual void copyValuesBack ()=0
Called by FEProblemBase::advanceState via ReporterData.
virtual void storeInfo (nlohmann::json &json) const =0
Called by JSONOutput::outputReporters to output meta data independent of calculated values.
virtual void store (nlohmann::json &json) const =0
Called by JSONOutput::outputReporters to invoke storage of values for output.
virtual void finalize ()=0
Called by FEProblemBase::joinAndFinalize via ReporterData.
void init (const ReporterMode &mode)
Initialize the producer mode.
const MooseObject & getProducer () const
Return the MooseObject that produces this Reporter.
const ReporterProducerEnum & getProducerModeEnum () const
Return the Reporter value produced mode.
virtual void transfer (ReporterData &r_data, const ReporterName &r_name, unsigned int time_index=0) const =0
Helper for enabling generic transfer of Reporter values.
virtual void transferToVector (ReporterData &r_data, const ReporterName &r_name, dof_id_type index, unsigned int time_index=0) const =0
Helper for enabling generic transfer of Reporter values to a vector.
virtual void declareClone (ReporterData &r_data, const ReporterName &r_name, const ReporterMode &mode, const MooseObject &producer) const =0
Helper for declaring new reporter values based on this context.
virtual void declareVectorClone (ReporterData &r_data, const ReporterName &r_name, const ReporterMode &mode, const MooseObject &producer) const =0
Helper for declaring new vector reporter values based on this context.
virtual void resize (dof_id_type local_size)=0
Helper for resizing vector data.
Protected Member Functions
void requiresConsumerModes (const ReporterStateBase &state, const std::set< ReporterMode > &modes) const
Helper for checking whether or not the state state has only the modes modes.
Protected Attributes
const MooseObject & _producer
The MooseObject that is producing this Reporter.
ReporterProducerEnum _producer_enum
Defines how the Reporter value can be produced and how it is being produced.
Detailed Description
This is a helper class to aid with parallel communication of compute Reporter values as well as provides a link to the stored Reporter value state object.
See also
Reporter, ReporterData, ReporterState
This file contains several reporter context types with specific polymorphism:
ReporterContextBase—>ReporterContext<T> | | | ReporterGeneralContext<T> | | | | | | | ReporterGatherContext<T> | | ReporterScatterContext<T> | ReporterBroadcastContext<T> | ReporterVectorContext<std::vector<T>>
When creating a new context, it is generally advisable to derive from ReporterGeneralContext (
See also
VectorPostprocessorContext). The reason for the split between ReporterGeneralContext and ReporterVectorContext is due to the declareVectorClone and resize functionality. If we were to declare a vector clone in ReporterContext there would be a infinite instantiation of of vector contexts, which is why this declare is defined in ReporterGeneralContext and an error is thrown in ReporterVectorContext. There is also no easy way to partially instantiate a member function (you have to due it for the entire class), which is why the resize is defined in ReporterVectorContext. That being said, we are always open for improvements, especially for simplifying the polymorphism of these contexts.
Definition at line 54 of file ReporterContext.h.
Constructor & Destructor Documentation
ReporterContextBase()
ReporterContextBase::ReporterContextBase (const libMesh::ParallelObject & other, const MooseObject & producer)
Definition at line 14 of file ReporterContext.C.
  : libMesh::ParallelObject(other), _producer(producer)
{
}
~ReporterContextBase()
virtual ReporterContextBase::~ReporterContextBase () virtual default
Member Function Documentation
contextType()
virtual std::string ReporterContextBase::contextType () const pure virtual
Returns
The derived context type for this context.
This must be overridden in every class.
Implemented in ReporterGeneralContext< T >, ReporterBroadcastContext< T >, ReporterScatterContext< T >, ReporterGatherContext< T >, ReporterVectorContext< T >, ReporterContext< T >, and ReporterContext< std::vector< T > >.
Referenced by ReporterData::getReporterInfo().
copyValuesBack()
virtual void ReporterContextBase::copyValuesBack () pure virtual
Called by FEProblemBase::advanceState via ReporterData.
Implemented in ReporterContext< T >, ReporterContext< std::vector< T > >, and VectorPostprocessorContext< T >.
Referenced by VectorPostprocessorContext< T >::copyValuesBack().
declareClone()
virtual void ReporterContextBase::declareClone (ReporterData & r_data, const ReporterName & r_name, const ReporterMode & mode, const MooseObject & producer) const pure virtual
Helper for declaring new reporter values based on this context.
Parameters
r_data The ReporterData on the app that this value is being declared
r_name The name of the Reporter value being declared
mode Reporter mode to declare with
See also
ReporterTransferInterface
Implemented in ReporterVectorContext< T >, and ReporterGeneralContext< T >.
Referenced by ReporterTransferInterface::declareClone().
declareVectorClone()
virtual void ReporterContextBase::declareVectorClone (ReporterData & r_data, const ReporterName & r_name, const ReporterMode & mode, const MooseObject & producer) const pure virtual
Helper for declaring new vector reporter values based on this context.
Parameters
r_data The ReporterData on the app that this value is being declared
r_name The name of the Reporter value being declared
mode Reporter mode to declare with
See also
ReporterTransferInterface
Implemented in ReporterVectorContext< T >, and ReporterGeneralContext< T >.
Referenced by ReporterTransferInterface::declareVectorClone().
finalize()
virtual void ReporterContextBase::finalize () pure virtual
Called by FEProblemBase::joinAndFinalize via ReporterData.
Implemented in ReporterContext< T >, ReporterContext< std::vector< T > >, ReporterBroadcastContext< T >, ReporterScatterContext< T >, ReporterGatherContext< T >, and VectorPostprocessorContext< T >.
Referenced by VectorPostprocessorContext< T >::finalize().
getProducer()
const MooseObject & ReporterContextBase::getProducer () const inline
Return the MooseObject that produces this Reporter.
Definition at line 112 of file ReporterContext.h.
{ return _producer; }
Referenced by ReporterData::getReporterInfo().
getProducerModeEnum()
const ReporterProducerEnum & ReporterContextBase::getProducerModeEnum () const
Return the Reporter value produced mode.
Definition at line 28 of file ReporterContext.C.
{
  return _producer_enum;
}
Referenced by ReporterData::getReporterMode().
init()
void ReporterContextBase::init (const ReporterMode & mode)
Initialize the producer mode.
This done after construction to allow the constructor to define the available values in the ReporterProducerEnum.
See also
ReporterData::declareReporterValue
Definition at line 21 of file ReporterContext.C.
{
  if (mode != REPORTER_MODE_UNSET)
    _producer_enum.assign(mode);
}
name()
virtual const ReporterName & ReporterContextBase::name () const pure virtual
Return the ReporterName that the context is associated.
Implemented in ReporterContext< T >, and ReporterContext< std::vector< T > >.
Referenced by requiresConsumerModes().
requiresConsumerModes()
void ReporterContextBase::requiresConsumerModes (const ReporterStateBase & state, const std::set< ReporterMode > & modes) const protected
Helper for checking whether or not the state state has only the modes modes.
Definition at line 34 of file ReporterContext.C.
{
  for (const auto & mode_object_pair : state.getConsumers())
    if (!modes.count(mode_object_pair.first))
    {
      std::stringstream oss;
      std::copy(modes.begin(), modes.end(), std::ostream_iterator<ReporterMode>(oss, " "));
      mooseError("The Reporter value '",
                 name(),
                 "' is being produced in ",
                 _producer_enum,
                 " mode, but ",
                 mode_object_pair.second->typeAndName(),
                 " is requesting to consume it in ",
                 mode_object_pair.first,
                 " mode, which is not supported.\n\nThe mode must be { ",
                 oss.str(),
                 " }.\n\n",
                 ReporterData::getReporterInfo(state, this));
    }
}
resize()
virtual void ReporterContextBase::resize (dof_id_type local_size) pure virtual
Helper for resizing vector data.
Parameters
local_size Number of elements to resize vector to
Implemented in ReporterGeneralContext< T >, and ReporterVectorContext< T >.
Referenced by ReporterTransferInterface::resizeReporter().
store()
virtual void ReporterContextBase::store (nlohmann::json & json) const pure virtual
Called by JSONOutput::outputReporters to invoke storage of values for output.
This method exists and is distinct from the RestartableData::store method for JSON output via the JSONOutput object. The RestartableData::store/load methods are designed for restart and include all the data including the old values.
This method only outputs the current value within the JSONOutput object. NOTE: nlohmann qualification is needed for argument json because the std::vector overload is not in the std namespace, it's in the nlohmann namespace, and will come up in argument dependent lookup (ADL) only because of this qualification.
See also
JsonIO.h
JSONOutput.h
Implemented in ReporterContext< T >, and ReporterContext< std::vector< T > >.
storeInfo()
virtual void ReporterContextBase::storeInfo (nlohmann::json & json) const pure virtual
Called by JSONOutput::outputReporters to output meta data independent of calculated values.
Implemented in ReporterContext< T >, and ReporterContext< std::vector< T > >.
transfer()
virtual void ReporterContextBase::transfer (ReporterData & r_data, const ReporterName & r_name, unsigned int time_index = 0) const pure virtual
Helper for enabling generic transfer of Reporter values.
Parameters
r_data The ReporterData on the app that this data is being transferred to
r_name The name of the Report being transferred to
See also
MultiAppReporterTransfer
Implemented in ReporterContext< T >, and ReporterContext< std::vector< T > >.
Referenced by ReporterTransferInterface::transferReporter().
transferToVector()
virtual void ReporterContextBase::transferToVector (ReporterData & r_data, const ReporterName & r_name, dof_id_type index, unsigned int time_index = 0) const pure virtual
Helper for enabling generic transfer of Reporter values to a vector.
Parameters
r_data The ReporterData on the app that this data is being transferred to
r_name The name of the Report being transfered to
See also
ReporterTransferInterface
Implemented in ReporterContext< T >, and ReporterContext< std::vector< T > >.
Referenced by ReporterTransferInterface::transferToVectorReporter().
type()
virtual std::string ReporterContextBase::type () const pure virtual
Return the type of the data stored.
Implemented in ReporterContext< T >, and ReporterContext< std::vector< T > >.
Referenced by AccumulateReporter::declareLateValues().
Member Data Documentation
_producer
const MooseObject& ReporterContextBase::_producer protected
The MooseObject that is producing this Reporter.
Definition at line 185 of file ReporterContext.h.
Referenced by getProducer().
_producer_enum
ReporterProducerEnum ReporterContextBase::_producer_enum protected
Defines how the Reporter value can be produced and how it is being produced.
Definition at line 188 of file ReporterContext.h.
Referenced by getProducerModeEnum(), init(), ReporterBroadcastContext< T >::ReporterBroadcastContext(), ReporterContext< T >::ReporterContext(), ReporterGatherContext< T >::ReporterGatherContext(), ReporterScatterContext< T >::ReporterScatterContext(), and requiresConsumerModes().
The documentation for this class was generated from the following files:
moose/framework/include/reporters/ReporterContext.h
moose/framework/src/reporters/ReporterContext.C