Zapdos: AttribInterfaces Class Reference
AttribInterfaces Class Reference abstract
#include <Attributes.h>
Public Types
typedef Interfaces Key
Public Member Functions
void setFrom (Key k)
AttribInterfaces (TheWarehouse &w)
AttribInterfaces (TheWarehouse &w, Interfaces mask)
AttribInterfaces (TheWarehouse &w, unsigned int mask)
virtual void initFrom (const MooseObject *obj) override
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
virtual bool isMatch (const Attribute &other) const override
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
virtual bool isEqual (const Attribute &other) const override
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
hashfunc (_val)
clonefunc (AttribInterfaces)
bool operator== (const Attribute &other) const
bool operator!= (const Attribute &other) const
unsigned int id () const
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
virtual std::size_t hash () const =0
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
virtual std::unique_ptr< Attribute > clone () const =0
clone creates and returns and identical (deep) copy of this attribute - i.e.
Private Attributes
uint64_t _val = 0
int _id = -1
Detailed Description
Definition at line 456 of file Attributes.h.
Member Typedef Documentation
Key
typedef Interfaces AttribInterfaces::Key
Definition at line 459 of file Attributes.h.
Constructor & Destructor Documentation
AttribInterfaces() [1/3]
AttribInterfaces::AttribInterfaces (TheWarehouse & w) inline
Definition at line 462 of file Attributes.h.
: Attribute(w, "interfaces") {}
AttribInterfaces() [2/3]
AttribInterfaces::AttribInterfaces (TheWarehouse & w, Interfaces mask) inline
Definition at line 463 of file Attributes.h.
    : Attribute(w, "interfaces"), _val(static_cast<uint64_t>(mask))
  {
  }
AttribInterfaces() [3/3]
AttribInterfaces::AttribInterfaces (TheWarehouse & w, unsigned int mask) inline
Definition at line 467 of file Attributes.h.
: Attribute(w, "interfaces"), _val(mask) {}
Member Function Documentation
clone()
virtual std::unique_ptr< Attribute > Attribute::clone () const pure virtual inherited
clone creates and returns and identical (deep) copy of this attribute - i.e.
the result of clone should return true if passed into isMatch.
Referenced by FEProblemBase::computeUserObjectsInternal(), and TheWarehouse::update().
clonefunc()
AttribInterfaces::clonefunc (AttribInterfaces)
hash()
virtual std::size_t Attribute::hash () const pure virtual inherited
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
is initialized with). Ideally, the data should be uniformly and randomly distributed across the domain of size_t values - e.g. 1 and 2 should hash to completely unrelated values. Use of std::hash for POD is encouraged. A convenience hash_combine function is also provided to combine the results an existing hash with one or more other values.
Referenced by std::hash< Attribute >::operator()().
hashfunc()
AttribInterfaces::hashfunc (_val)
id()
unsigned int Attribute::id () const inline inherited
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
This ID is determined at construction time this
Definition at line 66 of file TheWarehouse.h.
{ return _id; }
Referenced by std::hash< Attribute >::operator()().
initFrom()
void AttribInterfaces::initFrom (const MooseObject * obj) override virtual
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
Implements Attribute.
Definition at line 474 of file Attributes.C.
{
  _val = 0;
  // clang-format off
  _val |= (unsigned int)Interfaces::UserObject                * (dynamic_cast<const UserObject *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::ElementUserObject         * (dynamic_cast<const ElementUserObject *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::SideUserObject            * (dynamic_cast<const SideUserObject *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::InternalSideUserObject    * (dynamic_cast<const InternalSideUserObject *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::InterfaceUserObject       * (dynamic_cast<const InterfaceUserObject *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::NodalUserObject           * (dynamic_cast<const NodalUserObject *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::GeneralUserObject         * (dynamic_cast<const GeneralUserObject *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::ThreadedGeneralUserObject * (dynamic_cast<const ThreadedGeneralUserObject *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::ShapeElementUserObject    * (dynamic_cast<const ShapeElementUserObject *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::ShapeSideUserObject       * (dynamic_cast<const ShapeSideUserObject *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::Postprocessor             * (dynamic_cast<const Postprocessor *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::VectorPostprocessor       * (dynamic_cast<const VectorPostprocessor *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::BlockRestrictable         * (dynamic_cast<const BlockRestrictable *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::BoundaryRestrictable      * (dynamic_cast<const BoundaryRestrictable *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::Reporter                  * (dynamic_cast<const Reporter *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::DomainUserObject          * (dynamic_cast<const DomainUserObject *>(obj) != nullptr);
  _val |= (unsigned int)Interfaces::MortarUserObject          * (dynamic_cast<const MortarUserObject *>(obj) != nullptr);
  // clang-format on
}
isEqual()
bool AttribInterfaces::isEqual (const Attribute & other) const override virtual
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
isEqual does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 506 of file Attributes.C.
{
  auto a = dynamic_cast<const AttribInterfaces *>(&other);
  return a && (a->_val == _val);
}
isMatch()
bool AttribInterfaces::isMatch (const Attribute & other) const override virtual
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
This is is for query matching - not exact equivalence. isMatch does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 499 of file Attributes.C.
{
  auto a = dynamic_cast<const AttribInterfaces *>(&other);
  return a && (a->_val & _val);
}
operator!=()
bool Attribute::operator!= (const Attribute & other) const inline inherited
Definition at line 61 of file TheWarehouse.h.
{ return !(*this == other); }
operator==()
bool Attribute::operator== (const Attribute & other) const inline inherited
Definition at line 57 of file TheWarehouse.h.
  {
    return _id == other._id && isEqual(other);
  }
setFrom()
void AttribInterfaces::setFrom (Key k) inline
Definition at line 460 of file Attributes.h.
{ _val = static_cast<uint64_t>(k); }
Member Data Documentation
_id
int Attribute::_id = -1 private inherited
Definition at line 91 of file TheWarehouse.h.
Referenced by Attribute::id(), and Attribute::operator==().
_val
uint64_t AttribInterfaces::_val = 0 private
Definition at line 475 of file Attributes.h.
Referenced by initFrom(), isEqual(), isMatch(), and setFrom().
The documentation for this class was generated from the following files:
moose/framework/include/base/Attributes.h
moose/framework/src/base/Attributes.C