Zapdos: OutputDataWarehouse Class Reference
OutputDataWarehouse Class Reference
A helper warehouse for storing OutputData objects for the various output types.
#include <AdvancedOutputUtils.h>
Public Member Functions
OutputDataWarehouse ()
Populate the OutputData structures for all output types that are 'variable' based.
bool hasShowList ()
False when the show lists for all variables is empty.
void setHasShowList (bool value)
Set the show list bool.
void reset ()
Clear existing lists for re-initialization.
OutputData & operator[] (const std::string &name)
A map accessor that errors if the key is not found.
bool contains (const std::string &name) const
A method for testing of a key exists.
std::map< std::string, OutputData >::iterator begin ()
Provide iterator and find access to the underlying map data.
std::map< std::string, OutputData >::const_iterator begin () const
std::map< std::string, OutputData >::iterator end ()
std::map< std::string, OutputData >::const_iterator end () const
std::map< std::string, OutputData >::iterator find (const std::string &name)
const std::map< std::string, OutputData >::const_iterator find (const std::string &name) const
Static Public Member Functions
static InputParameters validParams ()
Protected Attributes
std::map< std::string, OutputData > _map
Data storage.
Private Attributes
bool _has_show_list
Detailed Description
A helper warehouse for storing OutputData objects for the various output types.
To keep syntax consistent and to provide the error checking for accessing invalid map keys the OutputMapWrapper is used for accessing the OutputData classes as well.
See also
OutputOnWarehouse OutputMapWrapper OutputData
Definition at line 146 of file AdvancedOutputUtils.h.
Constructor & Destructor Documentation
OutputDataWarehouse()
OutputDataWarehouse::OutputDataWarehouse ()
Populate the OutputData structures for all output types that are 'variable' based.
Definition at line 61 of file AdvancedOutputUtils.C.
                                         : OutputMapWrapper<OutputData>(), _has_show_list(false)
{
  _map["nodal"] = OutputData();
  _map["elemental"] = OutputData();
  _map["scalars"] = OutputData();
  _map["postprocessors"] = OutputData();
  _map["vector_postprocessors"] = OutputData();
  _map["reporters"] = OutputData();
}
Member Function Documentation
begin() [1/2]
std::map< std::string, OutputData >::iterator OutputMapWrapper< OutputData >::begin () inline inherited
Provide iterator and find access to the underlying map data.
Definition at line 84 of file AdvancedOutputUtils.h.
{ return _map.begin(); }
begin() [2/2]
std::map< std::string, OutputData >::const_iterator OutputMapWrapper< OutputData >::begin () const inline inherited
Definition at line 90 of file AdvancedOutputUtils.h.
{ return _map.begin(); }
contains()
bool OutputMapWrapper< OutputData >::contains (const std::string & name) const inline inherited
A method for testing of a key exists.
Definition at line 101 of file AdvancedOutputUtils.h.
{ return find(name) != end(); }
end() [1/2]
std::map< std::string, OutputData >::iterator OutputMapWrapper< OutputData >::end () inline inherited
Definition at line 85 of file AdvancedOutputUtils.h.
{ return _map.end(); }
end() [2/2]
std::map< std::string, OutputData >::const_iterator OutputMapWrapper< OutputData >::end () const inline inherited
Definition at line 91 of file AdvancedOutputUtils.h.
{ return _map.end(); }
find() [1/2]
std::map< std::string, OutputData >::iterator OutputMapWrapper< OutputData >::find (const std::string & name) inline inherited
Definition at line 86 of file AdvancedOutputUtils.h.
  {
    return _map.find(name);
  }
find() [2/2]
const std::map< std::string, OutputData >::const_iterator OutputMapWrapper< OutputData >::find (const std::string & name) const inline inherited
Definition at line 92 of file AdvancedOutputUtils.h.
  {
    return _map.find(name);
  }
hasShowList()
bool OutputDataWarehouse::hasShowList () inline
False when the show lists for all variables is empty.
When false everything should output.
See also
AdvancedOutput::initOutputList
Definition at line 162 of file AdvancedOutputUtils.h.
{ return _has_show_list; }
Referenced by AdvancedOutput::initOutputList().
operator[]()
OutputData & OutputMapWrapper< OutputData >::operator[] (const std::string & name) inline inherited
A map accessor that errors if the key is not found.
Definition at line 71 of file AdvancedOutputUtils.h.
  {
    // Locate the map entry, error if it is not found
    typename std::map<std::string, T>::iterator iter = _map.find(name);
    if (iter == _map.end())
      mooseError("Unknown map key ", name);
    return iter->second;
  }
reset()
void OutputDataWarehouse::reset ()
Clear existing lists for re-initialization.
Definition at line 72 of file AdvancedOutputUtils.C.
{
  for (auto map_pair : _map)
    map_pair.second.reset();
}
Referenced by AdvancedOutput::init().
setHasShowList()
void OutputDataWarehouse::setHasShowList (bool value) inline
Set the show list bool.
This is set to true when the user supplies a show list.
See also
AdvancedOutput::initShowHideLists
Definition at line 170 of file AdvancedOutputUtils.h.
{ _has_show_list = value; }
Referenced by AdvancedOutput::initShowHideLists().
validParams()
static InputParameters OutputDataWarehouse::validParams () static
Member Data Documentation
_has_show_list
bool OutputDataWarehouse::_has_show_list private
Definition at line 179 of file AdvancedOutputUtils.h.
Referenced by hasShowList(), and setHasShowList().
_map
std::map<std::string, OutputData > OutputMapWrapper< OutputData >::_map protected inherited
Data storage.
Definition at line 105 of file AdvancedOutputUtils.h.
The documentation for this class was generated from the following files:
moose/framework/include/outputs/AdvancedOutputUtils.h
moose/framework/src/outputs/AdvancedOutputUtils.C