Zapdos: ODETimeDerivative Class Reference
ODETimeDerivative Class Reference
#include <ODETimeDerivative.h>
Public Types
enum class ResidualTagType { NonReference , Reference }
Enumerate whether a (residual) vector tag is to be of a non-reference or reference tag type.
Public Member Functions
ODETimeDerivative (const InputParameters &parameters)
virtual void computeResidual () override
Compute this object's contribution to the residual.
virtual void reinit () override
Reinitialization method called before each call to computeResidual()
virtual void computeJacobian () override
Compute this object's contribution to the diagonal Jacobian entries.
virtual void computeOffDiagJacobianScalar (unsigned int jvar) override
Computes jacobian block with respect to a scalar variable.
virtual const MooseVariableScalar & variable () const override
The variable that this kernel operates on.
virtual bool isActive ()
Use this to enable/disable the scalar kernel.
const VariableValue & uOld () const
Retrieves the old value of the variable that this ScalarKernelBase operates on.
virtual void computeResidualAndJacobian ()
Compute this object's contribution to the residual and Jacobian simultaneously.
virtual void computeOffDiagJacobian (unsigned int)
Computes this object's contribution to off-diagonal blocks of the system Jacobian matrix.
virtual void computeNonlocalJacobian ()
Compute this object's contribution to the diagonal Jacobian entries corresponding to nonlocal dofs of the variable.
virtual void computeNonlocalOffDiagJacobian (unsigned int)
Computes Jacobian entries corresponding to nonlocal dofs of the jvar.
const SubProblem & subProblem () const
Returns a reference to the SubProblem for which this Kernel is active.
virtual void prepareShapes (unsigned int var_num)
Prepare shape functions.
virtual bool enabled () const
Return the enabled status of the object.
MooseApp & getMooseApp () const
Get the MooseApp this class is associated with.
const std::string & type () const
Get the type of this class.
virtual const std::string & name () const
Get the name of the class.
std::string typeAndName () const
Get the class's combined type and name; useful in error handling.
MooseObjectParameterName uniqueParameterName (const std::string &parameter_name) const
The unique parameter name of a valid parameter of this object for accessing parameter controls.
const InputParameters & parameters () const
Get the parameters of the object.
MooseObjectName uniqueName () const
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
template<typename T >
const T & getParam (const std::string &name) const
Retrieve a parameter for the object.
template<typename T1 , typename T2 >
std::vector< std::pair< T1, T2 > > getParam (const std::string &param1, const std::string &param2) const
Retrieve two parameters and provide pair of parameters for the object.
template<typename T >
const T & getRenamedParam (const std::string &old_name, const std::string &new_name) const
Retrieve a renamed parameter for the object.
template<typename T >
T getCheckedPointerParam (const std::string &name, const std::string &error_string="") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
bool isParamValid (const std::string &name) const
Test if the supplied parameter is valid.
bool isParamSetByUser (const std::string &nm) const
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
template<typename... Args>
void paramError (const std::string &param, Args... args) const
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramWarning (const std::string &param, Args... args) const
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramInfo (const std::string &param, Args... args) const
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
std::string objectErrorPrefix (const std::string &error_type) const
A descriptive prefix for errors for an object.
void connectControllableParams (const std::string &parameter, const std::string &object_type, const std::string &object_name, const std::string &object_parameter) const
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
template<typename... Args>
void mooseError (Args &&... args) const
Emits an error prefixed with object name and type.
template<typename... Args>
void mooseErrorNonPrefixed (Args &&... args) const
Emits an error without the prefixing included in mooseError().
template<typename... Args>
void mooseWarning (Args &&... args) const
Emits a warning prefixed with object name and type.
template<typename... Args>
void mooseWarningNonPrefixed (Args &&... args) const
Emits a warning without the prefixing included in mooseWarning().
template<typename... Args>
void mooseDeprecated (Args &&... args) const
template<typename... Args>
void mooseInfo (Args &&... args) const
std::string errorPrefix (const std::string &error_type) const
A descriptive prefix for errors for this object:
std::string getDataFileName (const std::string &param) const
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
std::string getDataFileNameByName (const std::string &name, const std::string *param=nullptr) const
Returns the path of a data file for a given relative file path.
virtual void initialSetup ()
Gets called at the beginning of the simulation before this object is asked to do its job.
virtual void timestepSetup ()
Gets called at the beginning of the timestep before this object is asked to do its job.
virtual void jacobianSetup ()
Gets called just before the Jacobian is computed and before this object is asked to do its job.
virtual void residualSetup ()
Gets called just before the residual is computed and before this object is asked to do its job.
virtual void subdomainSetup ()
Gets called when the subdomain changes (i.e.
virtual void customSetup (const ExecFlagType &)
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
const ExecFlagEnum & getExecuteOnEnum () const
Return the execute on MultiMooseEnum for this object.
const Function & getFunction (const std::string &name) const
Get a function with a given name.
const Function & getFunctionByName (const FunctionName &name) const
Get a function with a given name.
bool hasFunction (const std::string &param_name) const
Determine if the function exists.
bool hasFunctionByName (const FunctionName &name) const
Determine if the function exists.
UserObjectName getUserObjectName (const std::string &param_name) const
template<class T >
const T & getUserObject (const std::string &param_name, bool is_dependency=true) const
Get an user object with a given parameter param_name.
template<class T >
const T & getUserObjectByName (const UserObjectName &object_name, bool is_dependency=true) const
Get an user object with the name object_name.
const UserObject & getUserObjectBase (const std::string &param_name, bool is_dependency=true) const
Get an user object with a given parameter param_name.
const UserObject & getUserObjectBaseByName (const UserObjectName &object_name, bool is_dependency=true) const
Get an user object with the name object_name.
bool isImplicit ()
bool isDefaultPostprocessorValue (const std::string &param_name, const unsigned int index=0) const
Determine whether or not the Postprocessor is a default value.
bool hasPostprocessor (const std::string &param_name, const unsigned int index=0) const
Determine if the Postprocessor data exists.
bool hasPostprocessorByName (const PostprocessorName &name) const
Determine if the Postprocessor data exists.
std::size_t coupledPostprocessors (const std::string &param_name) const
Returns number of Postprocessors coupled under parameter name.
const PostprocessorName & getPostprocessorName (const std::string &param_name, const unsigned int index=0) const
Get the name of a postprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValue (const std::string &param_name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValue (const std::string &param_name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the value of a VectorPostprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValueByName (const VectorPostprocessorName &name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValueByName (const VectorPostprocessorName &name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the value of the VectorPostprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValueOld (const std::string &param_name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValueOld (const std::string &param_name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the old value of a VectorPostprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValueOldByName (const VectorPostprocessorName &name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValueOldByName (const VectorPostprocessorName &name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the old value of a VectorPostprocessor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValue (const std::string &param_name, const std::string &vector_name) const
Return the scatter value for the post processor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValueByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Return the scatter value for the post processor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValueOld (const std::string &param_name, const std::string &vector_name) const
Return the old scatter value for the post processor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValueOldByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Return the old scatter value for the post processor.
bool hasVectorPostprocessor (const std::string &param_name, const std::string &vector_name) const
Determine if the VectorPostprocessor data exists by parameter.
bool hasVectorPostprocessor (const std::string &param_name) const
Determine if the VectorPostprocessor exists by parameter.
bool hasVectorPostprocessorByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Determine if the VectorPostprocessor data exists by name.
bool hasVectorPostprocessorByName (const VectorPostprocessorName &name) const
Determine if the VectorPostprocessor exists by name.
const VectorPostprocessorName & getVectorPostprocessorName (const std::string &param_name) const
Get the name of a VectorPostprocessor associated with a parameter.
void setRandomResetFrequency (ExecFlagType exec_flag)
This interface should be called from a derived class to enable random number generation in this object.
unsigned long getRandomLong () const
Returns the next random number (long) from the generator tied to this object (elem/node).
Real getRandomReal () const
Returns the next random number (Real) from the generator tied to this object (elem/node).
unsigned int getSeed (std::size_t id)
Get the seed for the passed in elem/node id.
unsigned int getMasterSeed () const
bool isNodal () const
ExecFlagType getResetOnTime () const
void setRandomDataPointer (RandomData *random_data)
virtual void meshChanged ()
Called on this object when the mesh changes.
void useVectorTag (const TagName &tag_name, VectorTagsKey)
void useVectorTag (TagID tag_id, VectorTagsKey)
void useMatrixTag (const TagName &tag_name, MatrixTagsKey)
void useMatrixTag (TagID tag_id, MatrixTagsKey)
bool isVectorTagged ()
bool isMatrixTagged ()
const std::set< TagID > & getVectorTags (VectorTagsKey) const
const std::set< TagID > & getMatrixTags (MatrixTagsKey) const
const std::vector< MooseVariableScalar * > & getCoupledMooseScalarVars ()
Get the list of coupled scalar variables.
const std::set< TagID > & getScalarVariableCoupleableVectorTags () const
const std::set< TagID > & getScalarVariableCoupleableMatrixTags () const
bool hasUserObject (const std::string &param_name) const
template<class T >
bool hasUserObject (const std::string &param_name) const
bool hasUserObjectByName (const UserObjectName &object_name) const
template<class T >
bool hasUserObjectByName (const UserObjectName &object_name) const
const PostprocessorValue & getPostprocessorValue (const std::string &param_name, const unsigned int index=0) const
doco-normal-methods-begin Retrieve the value of a Postprocessor or one of it's old or older values
const PostprocessorValue & getPostprocessorValueOld (const std::string &param_name, const unsigned int index=0) const
const PostprocessorValue & getPostprocessorValueOlder (const std::string &param_name, const unsigned int index=0) const
virtual const PostprocessorValue & getPostprocessorValueByName (const PostprocessorName &name) const
Retrieve the value of the Postprocessor.
const PostprocessorValue & getPostprocessorValueOldByName (const PostprocessorName &name) const
const PostprocessorValue & getPostprocessorValueOlderByName (const PostprocessorName &name) const
bool isVectorPostprocessorDistributed (const std::string &param_name) const
Return true if the VectorPostprocessor is marked with parallel_type as DISTRIBUTED.
bool isVectorPostprocessorDistributedByName (const VectorPostprocessorName &name) const
Static Public Member Functions
static InputParameters validParams ()
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Member Functions
virtual Real computeQpResidual () override
virtual Real computeQpJacobian () override
virtual Real computeQpOffDiagJacobianScalar (unsigned int jvar)
virtual Real computeQpOffDiagJacobian (unsigned int)
virtual void precalculateResidual ()
virtual void precalculateJacobian ()
virtual void precalculateOffDiagJacobian (unsigned int)
const MooseVariableFieldBase & getVariable (unsigned int jvar_num) const
Retrieve the variable object from our system associated with jvar_num.
virtual void addUserObjectDependencyHelper (const UserObject &) const
Helper for deriving classes to override to add dependencies when a UserObject is requested.
Moose::StateArg determineState () const
Create a functor state argument that corresponds to the implicit state of this object.
virtual void addPostprocessorDependencyHelper (const PostprocessorName &) const
Helper for deriving classes to override to add dependencies when a Postprocessor is requested.
virtual void addVectorPostprocessorDependencyHelper (const VectorPostprocessorName &) const
Helper for deriving classes to override to add dependencies when a VectorPostprocessor is requested.
template<typename T , typename... Args>
T & declareRestartableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
ManagedValue< T > declareManagedRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declares a piece of "managed" restartable data and initialize it.
template<typename T , typename... Args>
const T & getRestartableData (const std::string &data_name) const
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
template<typename T , typename... Args>
T & declareRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
T & declareRecoverableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "recoverable" and initialize it.
template<typename T , typename... Args>
T & declareRestartableDataWithObjectName (const std::string &data_name, const std::string &object_name, Args &&... args)
Declare a piece of data as "restartable".
template<typename T , typename... Args>
T & declareRestartableDataWithObjectNameWithContext (const std::string &data_name, const std::string &object_name, void *context, Args &&... args)
Declare a piece of data as "restartable".
std::string restartableName (const std::string &data_name) const
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
void prepareVectorTag (Assembly &assembly, unsigned int ivar)
Prepare data for computing element residual according to active tags.
void prepareVectorTag (Assembly &assembly, unsigned int ivar, ResidualTagType tag_type)
Prepare vector tags in a reference residual problem context.
void prepareVectorTagNeighbor (Assembly &assembly, unsigned int ivar)
Prepare data for computing element residual the according to active tags for DG and interface kernels.
void prepareVectorTagLower (Assembly &assembly, unsigned int ivar)
Prepare data for computing the residual according to active tags for mortar constraints.
void prepareMatrixTag (Assembly &assembly, unsigned int ivar, unsigned int jvar)
Prepare data for computing element jacobian according to the active tags.
void prepareMatrixTag (Assembly &assembly, unsigned int ivar, unsigned int jvar, DenseMatrix< Number > &k) const
void prepareMatrixTagNonlocal (Assembly &assembly, unsigned int ivar, unsigned int jvar)
Prepare data for computing nonlocal element jacobian according to the active tags.
void prepareMatrixTagNeighbor (Assembly &assembly, unsigned int ivar, unsigned int jvar, Moose::DGJacobianType type)
Prepare data for computing element jacobian according to the active tags for DG and interface kernels.
void prepareMatrixTagNeighbor (Assembly &assembly, unsigned int ivar, unsigned int jvar, Moose::DGJacobianType type, DenseMatrix< Number > &k) const
void prepareMatrixTagLower (Assembly &assembly, unsigned int ivar, unsigned int jvar, Moose::ConstraintJacobianType type)
Prepare data for computing the jacobian according to the active tags for mortar.
void accumulateTaggedLocalResidual ()
Local residual blocks will be appended by adding the current local kernel residual.
void assignTaggedLocalResidual ()
Local residual blocks will assigned as the current local kernel residual.
void accumulateTaggedLocalMatrix ()
Local Jacobian blocks will be appended by adding the current local kernel Jacobian.
void accumulateTaggedLocalMatrix (Assembly &assembly, unsigned int ivar, unsigned int jvar, const DenseMatrix< Number > &k)
void accumulateTaggedLocalMatrix (Assembly &assembly, unsigned int ivar, unsigned int jvar, Moose::DGJacobianType type, const DenseMatrix< Number > &k)
void accumulateTaggedNonlocalMatrix ()
Nonlocal Jacobian blocks will be appended by adding the current nonlocal kernel Jacobian.
void assignTaggedLocalMatrix ()
Local Jacobian blocks will assigned as the current local kernel Jacobian.
template<typename Residuals , typename Indices >
void addResiduals (Assembly &assembly, const Residuals &residuals, const Indices &dof_indices, Real scaling_factor)
Add the provided incoming residuals corresponding to the provided dof indices.
template<typename T , typename Indices >
void addResiduals (Assembly &assembly, const DenseVector< T > &residuals, const Indices &dof_indices, Real scaling_factor)
Add the provided incoming residuals corresponding to the provided dof indices.
template<typename Residuals , typename Indices >
void addResidualsAndJacobian (Assembly &assembly, const Residuals &residuals, const Indices &dof_indices, Real scaling_factor)
Add the provided incoming residuals and derivatives for the Jacobian, corresponding to the provided dof indices.
template<typename Residuals , typename Indices >
void addJacobian (Assembly &assembly, const Residuals &residuals, const Indices &dof_indices, Real scaling_factor)
Add the provided residual derivatives into the Jacobian for the provided dof indices.
void addJacobian (Assembly &assembly, DenseMatrix< Real > &local_k, const std::vector< dof_id_type > &row_indices, const std::vector< dof_id_type > &column_indices, Real scaling_factor)
Add a local Jacobian matrix.
template<typename Residuals , typename Indices >
void addResidualsWithoutConstraints (Assembly &assembly, const Residuals &residuals, const Indices &dof_indices, Real scaling_factor)
Add the provided incoming residuals corresponding to the provided dof indices.
template<typename Residuals , typename Indices >
void addResidualsAndJacobianWithoutConstraints (Assembly &assembly, const Residuals &residuals, const Indices &dof_indices, Real scaling_factor)
Add the provided incoming residuals and derivatives for the Jacobian, corresponding to the provided dof indices.
template<typename Residuals , typename Indices >
void addJacobianWithoutConstraints (Assembly &assembly, const Residuals &residuals, const Indices &dof_indices, Real scaling_factor)
Add the provided residual derivatives into the Jacobian for the provided dof indices.
void addJacobianElement (Assembly &assembly, Real value, dof_id_type row_index, dof_id_type column_index, Real scaling_factor)
Add into a single Jacobian element.
template<typename T >
void setResidual (SystemBase &sys, const T &residual, MooseVariableFE< T > &var)
Set residual using the variables' insertion API.
void setResidual (SystemBase &sys, Real residual, dof_id_type dof_index)
Set residual at a specified degree of freedom index.
template<typename SetResidualFunctor >
void setResidual (SystemBase &sys, SetResidualFunctor set_residual_functor)
Set residuals using the provided functor.
bool isCoupledScalar (const std::string &var_name, unsigned int i=0) const
Returns true if a variables has been coupled_as name.
unsigned int coupledScalarComponents (const std::string &var_name) const
Return the number of components to the coupled scalar variable.
unsigned int coupledScalar (const std::string &var_name, unsigned int comp=0) const
Returns the index for a scalar coupled variable by name.
Order coupledScalarOrder (const std::string &var_name, unsigned int comp=0) const
Returns the order for a scalar coupled variable by name.
const VariableValue & coupledScalarValue (const std::string &var_name, unsigned int comp=0) const
Returns value of a scalar coupled variable.
const ADVariableValue & adCoupledScalarValue (const std::string &var_name, unsigned int comp=0) const
Returns AD value of a scalar coupled variable.
template<bool is_ad>
const GenericVariableValue< is_ad > & coupledGenericScalarValue (const std::string &var_name, unsigned int comp=0) const
Returns value of a coupled scalar variable for use in templated automatic differentiation classes.
template<>
const GenericVariableValue< false > & coupledGenericScalarValue (const std::string &var_name, unsigned int comp) const
template<>
const GenericVariableValue< true > & coupledGenericScalarValue (const std::string &var_name, unsigned int comp) const
const VariableValue & coupledVectorTagScalarValue (const std::string &var_name, TagID tag, unsigned int comp=0) const
Returns value of a scalar coupled variable.
const VariableValue & coupledMatrixTagScalarValue (const std::string &var_name, TagID tag, unsigned int comp=0) const
Returns value of a scalar coupled variable.
const VariableValue & coupledScalarValueOld (const std::string &var_name, unsigned int comp=0) const
Returns the old (previous time step) value of a scalar coupled variable.
const VariableValue & coupledScalarValueOlder (const std::string &var_name, unsigned int comp=0) const
Returns the older (two time steps previous) value of a scalar coupled variable.
const VariableValue & coupledScalarDot (const std::string &var_name, unsigned int comp=0) const
Returns the time derivative of a scalar coupled variable.
const VariableValue & coupledScalarDotDot (const std::string &var_name, unsigned int comp=0) const
Returns the second time derivative of a scalar coupled variable.
const VariableValue & coupledScalarDotOld (const std::string &var_name, unsigned int comp=0) const
Returns the old time derivative of a scalar coupled variable.
const VariableValue & coupledScalarDotDotOld (const std::string &var_name, unsigned int comp=0) const
Returns the old second time derivative of a scalar coupled variable.
const VariableValue & coupledScalarDotDu (const std::string &var_name, unsigned int comp=0) const
Time derivative of a scalar coupled variable with respect to the coefficients.
const VariableValue & coupledScalarDotDotDu (const std::string &var_name, unsigned int comp=0) const
Second time derivative of a scalar coupled variable with respect to the coefficients.
const MooseVariableScalar * getScalarVar (const std::string &var_name, unsigned int comp) const
Extract pointer to a scalar coupled variable.
Protected Attributes
const VariableValue & _u_dot
Time derivative of u.
const VariableValue & _du_dot_du
Derivative of u_dot wrt u.
const VariableValue & _u
The current solution (old solution if explicit)
MooseVariableScalar & _var
Scalar variable.
unsigned int _i
unsigned int _j
SubProblem & _subproblem
Reference to this kernel's SubProblem.
FEProblemBase & _fe_problem
Reference to this kernel's FEProblemBase.
SystemBase & _sys
Reference to the EquationSystem object.
THREAD_ID _tid
The thread ID for this kernel.
Assembly & _assembly
Reference to this Kernel's assembly object.
MooseMesh & _mesh
Reference to this Kernel's mesh object.
const bool & _enabled
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
MooseApp & _app
The MOOSE application this is associated with.
const std::string & _type
The type of this class.
const std::string & _name
The name of this class, reference to value stored in InputParameters.
const InputParameters & _pars
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Factory & _factory
The Factory associated with the MooseApp.
ActionFactory & _action_factory
Builds Actions.
const ExecFlagEnum & _execute_enum
Execute settings for this object.
const ExecFlagType & _current_execute_flag
Reference to FEProblemBase.
const InputParameters & _ti_params
FEProblemBase & _ti_feproblem
bool _is_implicit
If the object is using implicit or explicit form.
Real & _t
Time.
int & _t_step
The number of the time step.
Real & _dt
Time step size.
Real & _dt_old
Size of the old time step.
bool _is_transient
MooseApp & _restartable_app
Reference to the application.
const std::string _restartable_system_name
The system name this object is in.
const THREAD_ID _restartable_tid
The thread ID for this object.
const bool _restartable_read_only
Flag for toggling read only status (see ReporterData)
FEProblemBase & _mci_feproblem
Reference to FEProblemBase instance.
DenseVector< Number > _local_re
Holds local residual entries as they are accumulated by this Kernel.
DenseMatrix< Number > _local_ke
Holds local Jacobian entries as they are accumulated by this Kernel.
DenseMatrix< Number > _nonlocal_ke
Holds nonlocal Jacobian entries as they are accumulated by this Kernel.
FEProblemBase & _sc_fe_problem
const THREAD_ID _sc_tid
Thread ID of the thread using this object.
const Real & _real_zero
Scalar zero.
const VariableValue & _scalar_zero
Zero value of a scalar variable.
const Point & _point_zero
Zero point.
Private Member Functions
template<typename... Args>
std::string paramErrorMsg (const std::string &param, Args... args) const
template<class T >
const T & castUserObject (const UserObject &uo_base, const std::string &param_name="") const
Internal helper that casts the UserObject uo_base to the reqested type.
const std::string & userObjectType (const UserObject &uo) const
Gets a UserObject's type; avoids including UserObject.h in the UserObjectInterface.
const std::string & userObjectName (const UserObject &uo) const
Gets a UserObject's name; avoids including UserObject.h in the UserObjectInterface.
const PostprocessorName & getPostprocessorNameInternal (const std::string &param_name, const unsigned int index, const bool allow_default_value=true) const
Internal method for getting the PostprocessorName associated with a paremeter.
bool isDefaultPostprocessorValueByName (const PostprocessorName &name) const
PostprocessorValue getDefaultPostprocessorValueByName (const PostprocessorName &name) const
void checkParam (const std::string &param_name, const unsigned int index=std::numeric_limits< unsigned int >::max()) const
Checks the parameters relating to a Postprocessor.
bool postprocessorsAdded () const
const VectorPostprocessorValue & getVectorPostprocessorByNameHelper (const VectorPostprocessorName &name, const std::string &vector_name, bool broadcast, std::size_t t_index) const
Helper function for extracting VPP data from ReporterData object.
const VectorPostprocessorContext< VectorPostprocessorValue > & getVectorPostprocessorContextByNameHelper (const VectorPostprocessorName &name, const std::string &vector_name) const
Helper for getting the VPP context that handles scatter values.
bool vectorPostprocessorsAdded () const
RestartableDataValue & registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const
Helper function for actually registering the restartable data.
void registerRestartableNameWithFilterOnApp (const std::string &name, Moose::RESTARTABLE_FILTER filter)
Helper function for actually registering the restartable data.
template<typename T , typename... Args>
RestartableData< T > & declareRestartableDataHelper (const std::string &data_name, void *context, Args &&... args) const
Helper function for declaring restartable data.
void prepareVectorTagInternal (Assembly &assembly, unsigned int ivar, const std::set< TagID > &vector_tags, const std::set< TagID > &absolute_value_vector_tags)
Prepare data for computing element residual according to the specified tags Residual blocks for different tags will be extracted from Assembly.
const VariableValue * getDefaultValue (const std::string &var_name) const
Helper method to return (and insert if necessary) the default value for an uncoupled variable.
const ADVariableValue * getADDefaultValue (const std::string &var_name) const
Helper method to return (and insert if necessary) the AD default value for an uncoupled variable.
void checkVar (const std::string &var_name) const
Check that the right kind of variable is being coupled in.
void validateExecutionerType (const std::string &name, const std::string &fn_name) const
Checks to make sure that the current Executioner has set "_is_transient" when old/older values are coupled in.
const PostprocessorValue & getPostprocessorValueInternal (const std::string &param_name, unsigned int index, std::size_t t_index) const
Internal methods for getting Postprocessor values.
const PostprocessorValue & getPostprocessorValueByNameInternal (const PostprocessorName &name, std::size_t t_index) const
void possiblyCheckHasVectorPostprocessor (const std::string &param_name, const std::string &vector_name) const
Helpers for "possibly" checking if a vpp exists.
void possiblyCheckHasVectorPostprocessorByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Private Attributes
const MooseBase *const _moose_base
The MooseBase object that inherits this class.
const MooseObject & _parent
ExecFlagEnum _empty_execute_enum
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
const InputParameters & _fni_params
Parameters of the object with this interface.
FEProblemBase & _fni_feproblem
Reference to FEProblemBase instance.
const THREAD_ID _fni_tid
Thread ID.
const MooseObject & _uoi_moose_object
Moose object using the interface.
const FEProblemBase & _uoi_feproblem
Reference to the FEProblemBase instance.
const THREAD_ID _uoi_tid
Thread ID.
const std::string _ti_name
const MooseObject & _ppi_moose_object
The MooseObject that uses this interface.
const InputParameters & _ppi_params
PostprocessorInterface Parameters.
const FEProblemBase & _ppi_feproblem
Reference the the FEProblemBase class.
std::map< PostprocessorName, std::unique_ptr< PostprocessorValue > > _default_values
Holds the default postprocessor values that are requested (key is PostprocessorName)
const bool _broadcast_by_default
Whether or not to force broadcasting by default.
const MooseObject & _vpi_moose_object
The MooseObject that uses this interface.
const FEProblemBase & _vpi_feproblem
Reference the FEProblemBase class.
const THREAD_ID _vpi_tid
Thread ID.
RandomData * _random_data
MooseRandom * _generator
FEProblemBase & _ri_problem
const std::string _ri_name
unsigned int _master_seed
bool _is_nodal
ExecFlagType _reset_on
const Node *const & _curr_node
const Elem *const & _curr_element
const RestartableDataMapName _metaname
Restartable metadata name.
std::string _restartable_name
The name of the object.
std::set< TagID > _vector_tags
The residual tag ids this Kernel will contribute to.
std::set< TagID > _abs_vector_tags
The absolute value residual tag ids.
std::set< TagID > _matrix_tags
The matrices this Kernel will contribute to.
std::set< TagID > _non_ref_vector_tags
A set to hold vector tags excluding the reference residual tag.
std::set< TagID > _non_ref_abs_vector_tags
A set to hold absolute value vector tags excluding the reference residual tag.
std::set< TagID > _ref_vector_tags
A set of either size 1 or 0.
std::set< TagID > _ref_abs_vector_tags
A set of either size 1 or 0.
const MooseObject & _moose_object
Moose objct this tag works on.
const InputParameters & _tag_params
Parameters from moose object.
std::vector< DenseVector< Number > * > _re_blocks
Residual blocks Vectors For each Tag.
std::vector< DenseVector< Number > * > _absre_blocks
Residual blocks for absolute value residual tags.
std::vector< DenseMatrix< Number > * > _ke_blocks
Kernel blocks Vectors For each Tag.
std::vector< Real > _absolute_residuals
A container to hold absolute values of residuals passed into addResiduals.
const InputParameters & _sc_parameters
const std::string & _sc_name
The name of the object this interface is part of.
const bool _sc_is_implicit
True if implicit value is required.
std::unordered_map< std::string, std::vector< MooseVariableScalar * > > _coupled_scalar_vars
Coupled vars whose values we provide.
std::unordered_map< std::string, std::unique_ptr< VariableValue > > _default_value
Will hold the default value for optional coupled scalar variables.
std::unordered_map< std::string, std::unique_ptr< ADVariableValue > > _dual_default_value
Will hold the default AD value for optional coupled scalar variables.
std::vector< MooseVariableScalar * > _coupled_moose_scalar_vars
Vector of coupled variables.
std::unordered_map< std::string, std::vector< MooseVariableFieldBase * > > _sc_coupled_vars
Field variables coupled into this object (for error checking)
std::set< TagID > _sc_coupleable_vector_tags
The scalar coupleable vector tags.
std::set< TagID > _sc_coupleable_matrix_tags
The scalar coupleable matrix tags.
Detailed Description
Definition at line 14 of file ODETimeDerivative.h.
Member Enumeration Documentation
ResidualTagType
enum class TaggingInterface::ResidualTagType strong inherited
Enumerate whether a (residual) vector tag is to be of a non-reference or reference tag type.
Enumerator
NonReference
Reference
Definition at line 75 of file TaggingInterface.h.
  {
    NonReference,
    Reference
  };
Constructor & Destructor Documentation
ODETimeDerivative()
ODETimeDerivative::ODETimeDerivative (const InputParameters & parameters)
Definition at line 23 of file ODETimeDerivative.C.
                                                                       : ODETimeKernel(parameters)
{
}
Member Function Documentation
accumulateTaggedLocalMatrix() [1/3]
void TaggingInterface::accumulateTaggedLocalMatrix () protected inherited
Local Jacobian blocks will be appended by adding the current local kernel Jacobian.
It should be called after the local element matrix has been computed.
Definition at line 375 of file TaggingInterface.C.
{
  for (auto & ke : _ke_blocks)
    *ke += _local_ke;
}
Referenced by ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ArrayIntegratedBC::computeJacobian(), IntegratedBC::computeJacobian(), NonlocalIntegratedBC::computeJacobian(), VectorIntegratedBC::computeJacobian(), NodeElemConstraint::computeJacobian(), NodeFaceConstraint::computeJacobian(), ArrayKernel::computeJacobian(), EigenKernel::computeJacobian(), Kernel::computeJacobian(), KernelGrad::computeJacobian(), KernelValue::computeJacobian(), MassLumpedTimeDerivative::computeJacobian(), NonlocalKernel::computeJacobian(), ODEKernel::computeJacobian(), TimeDerivative::computeJacobian(), VectorKernel::computeJacobian(), VectorTimeDerivative::computeJacobian(), ScalarKernel::computeJacobian(), MortarConstraint::computeJacobian(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ArrayIntegratedBC::computeOffDiagJacobian(), IntegratedBC::computeOffDiagJacobian(), NonlocalIntegratedBC::computeOffDiagJacobian(), VectorIntegratedBC::computeOffDiagJacobian(), NodeElemConstraint::computeOffDiagJacobian(), NodeFaceConstraint::computeOffDiagJacobian(), ArrayKernel::computeOffDiagJacobian(), EigenKernel::computeOffDiagJacobian(), Kernel::computeOffDiagJacobian(), KernelGrad::computeOffDiagJacobian(), KernelValue::computeOffDiagJacobian(), NonlocalKernel::computeOffDiagJacobian(), VectorKernel::computeOffDiagJacobian(), ArrayIntegratedBC::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), ArrayKernel::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), and ConservativeAdvection::fullUpwind().
accumulateTaggedLocalMatrix() [2/3]
void TaggingInterface::accumulateTaggedLocalMatrix (Assembly & assembly, unsigned int ivar, unsigned int jvar, const DenseMatrix< Number > & k) protected inherited
Definition at line 382 of file TaggingInterface.C.
{
  _ke_blocks.resize(_matrix_tags.size());
  mooseAssert(_matrix_tags.size() >= 1, "we need at least one active tag");
  auto mat_vector = _matrix_tags.begin();
  for (MooseIndex(_matrix_tags) i = 0; i < _matrix_tags.size(); i++, ++mat_vector)
    _ke_blocks[i] = &assembly.jacobianBlock(ivar, jvar, Assembly::LocalDataKey{}, *mat_vector);
  mooseAssert(_ke_blocks[0]->m() == k.m() && _ke_blocks[0]->n() == k.n(),
              "Passed-in k must match the blocks we are about to sum into");
  for (auto & ke : _ke_blocks)
    *ke += k;
}
accumulateTaggedLocalMatrix() [3/3]
void TaggingInterface::accumulateTaggedLocalMatrix (Assembly & assembly, unsigned int ivar, unsigned int jvar, Moose::DGJacobianType type, const DenseMatrix< Number > & k) protected inherited
Definition at line 406 of file TaggingInterface.C.
{
  _ke_blocks.resize(_matrix_tags.size());
  mooseAssert(_matrix_tags.size() >= 1, "we need at least one active tag");
  auto mat_vector = _matrix_tags.begin();
  for (MooseIndex(_matrix_tags) i = 0; i < _matrix_tags.size(); i++, ++mat_vector)
    _ke_blocks[i] =
        &assembly.jacobianBlockNeighbor(type, ivar, jvar, Assembly::LocalDataKey{}, *mat_vector);
  mooseAssert(_ke_blocks[0]->m() == k.m() && _ke_blocks[0]->n() == k.n(),
              "Passed-in k must match the blocks we are about to sum into");
  for (auto & ke : _ke_blocks)
    *ke += k;
}
accumulateTaggedLocalResidual()
void TaggingInterface::accumulateTaggedLocalResidual () protected inherited
Local residual blocks will be appended by adding the current local kernel residual.
It should be called after the local element vector has been computed.
Definition at line 355 of file TaggingInterface.C.
{
  for (auto & re : _re_blocks)
    *re += _local_re;
  for (auto & absre : _absre_blocks)
    for (const auto i : index_range(_local_re))
      (*absre)(i) += std::abs(_local_re(i));
}
Referenced by FVInterfaceKernel::addResidual(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDResidual(), DGLowerDKernel::computeLowerDResidual(), ArrayIntegratedBC::computeResidual(), ArrayLowerDIntegratedBC::computeResidual(), IntegratedBC::computeResidual(), LowerDIntegratedBC::computeResidual(), VectorIntegratedBC::computeResidual(), NodeElemConstraint::computeResidual(), NodeFaceConstraint::computeResidual(), FVElementalKernel::computeResidual(), ArrayKernel::computeResidual(), EigenKernel::computeResidual(), Kernel::computeResidual(), KernelGrad::computeResidual(), KernelValue::computeResidual(), ODEKernel::computeResidual(), ODETimeKernel::computeResidual(), TimeKernel::computeResidual(), VectorKernel::computeResidual(), VectorTimeKernel::computeResidual(), ADScalarKernel::computeResidual(), ScalarKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVFluxBC::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), ADMortarConstraint::computeResidual(), MortarConstraint::computeResidual(), and ConservativeAdvection::fullUpwind().
accumulateTaggedNonlocalMatrix()
void TaggingInterface::accumulateTaggedNonlocalMatrix () protected inherited
Nonlocal Jacobian blocks will be appended by adding the current nonlocal kernel Jacobian.
It should be called after the nonlocal element matrix has been computed.
Definition at line 399 of file TaggingInterface.C.
{
  for (auto & ke : _ke_blocks)
    *ke += _nonlocal_ke;
}
Referenced by NonlocalIntegratedBC::computeNonlocalJacobian(), NonlocalKernel::computeNonlocalJacobian(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), and NonlocalKernel::computeNonlocalOffDiagJacobian().
adCoupledScalarValue()
const ADVariableValue & ScalarCoupleable::adCoupledScalarValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns AD value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a ADVariableValue for the coupled variable
Definition at line 135 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getADDefaultValue(var_name);
  auto var = getScalarVar(var_name, comp);
  if (_sc_is_implicit)
    return var->adSln();
  else
    mooseError("adCoupledValue for non-implicit calculations is not currently supported. Use "
               "coupledValue instead for non-implicit");
}
Referenced by ScalarCoupleable::coupledGenericScalarValue().
addJacobian() [1/2]
template<typename Residuals , typename Indices > void TaggingInterface::addJacobian (Assembly & assembly, const Residuals & residuals, const Indices & dof_indices, Real scaling_factor) protected inherited
Add the provided residual derivatives into the Jacobian for the provided dof indices.
Definition at line 481 of file TaggingInterface.h.
{
  assembly.cacheJacobian(
      residuals, dof_indices, scaling_factor, Assembly::LocalDataKey{}, _matrix_tags);
}
Referenced by TaggingInterface::addResidualsAndJacobian(), ADScalarKernel::computeADJacobian(), ADDGKernel::computeElemNeighJacobian(), FVElementalKernel::computeJacobian(), ADNodalKernel::computeJacobian(), NodalConstraint::computeJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), FVScalarLagrangeMultiplierConstraint::computeOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), MortarScalarBase::computeScalarJacobian(), KernelScalarBase::computeScalarJacobian(), MortarScalarBase::computeScalarOffDiagJacobian(), KernelScalarBase::computeScalarOffDiagJacobian(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), and KernelScalarBase::computeScalarOffDiagJacobianScalar().
addJacobian() [2/2]
void TaggingInterface::addJacobian (Assembly & assembly, DenseMatrix< Real > & local_k, const std::vector< dof_id_type > & row_indices, const std::vector< dof_id_type > & column_indices, Real scaling_factor) inline protected inherited
Add a local Jacobian matrix.
Definition at line 524 of file TaggingInterface.h.
{
  for (const auto matrix_tag : _matrix_tags)
    assembly.cacheJacobianBlock(
        local_k, row_indices, column_indices, scaling_factor, Assembly::LocalDataKey{}, matrix_tag);
}
addJacobianElement()
void TaggingInterface::addJacobianElement (Assembly & assembly, Real value, dof_id_type row_index, dof_id_type column_index, Real scaling_factor) inline protected inherited
Add into a single Jacobian element.
Definition at line 513 of file TaggingInterface.h.
{
  assembly.cacheJacobian(
      row_index, column_index, value * scaling_factor, Assembly::LocalDataKey{}, _matrix_tags);
}
Referenced by ArrayNodalBC::computeJacobian(), NodalBC::computeJacobian(), VectorNodalBC::computeJacobian(), NodalKernel::computeJacobian(), NodalConstraint::computeJacobian(), ArrayNodalBC::computeOffDiagJacobian(), NodalBC::computeOffDiagJacobian(), VectorNodalBC::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), and MortarConstraintBase::zeroInactiveLMDofs().
addJacobianWithoutConstraints()
template<typename Residuals , typename Indices > void TaggingInterface::addJacobianWithoutConstraints (Assembly & assembly, const Residuals & residuals, const Indices & dof_indices, Real scaling_factor) protected inherited
Add the provided residual derivatives into the Jacobian for the provided dof indices.
This API should only be used if the caller knows that no libMesh-level constraints (hanging nodes or periodic boundary conditions) apply to the provided dof indices
Definition at line 503 of file TaggingInterface.h.
{
  assembly.cacheJacobianWithoutConstraints(
      residuals, dof_indices, scaling_factor, Assembly::LocalDataKey{}, _matrix_tags);
}
Referenced by TaggingInterface::addResidualsAndJacobianWithoutConstraints().
addPostprocessorDependencyHelper()
virtual void PostprocessorInterface::addPostprocessorDependencyHelper (const PostprocessorName &) const inline protected virtual inherited
Helper for deriving classes to override to add dependencies when a Postprocessor is requested.
Reimplemented in UserObject, AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, AuxKernelTempl< RealVectorValue >, and InitialConditionBase.
Definition at line 141 of file PostprocessorInterface.h.
{}
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal().
addResiduals() [1/2]
template<typename T , typename Indices > void TaggingInterface::addResiduals (Assembly & assembly, const DenseVector< T > & residuals, const Indices & dof_indices, Real scaling_factor) protected inherited
Add the provided incoming residuals corresponding to the provided dof indices.
Definition at line 437 of file TaggingInterface.h.
{
  addResiduals(assembly, residuals.get_values(), dof_indices, scaling_factor);
}
addResiduals() [2/2]
template<typename Residuals , typename Indices > void TaggingInterface::addResiduals (Assembly & assembly, const Residuals & residuals, const Indices & dof_indices, Real scaling_factor) protected inherited
Add the provided incoming residuals corresponding to the provided dof indices.
Definition at line 414 of file TaggingInterface.h.
{
  assembly.cacheResiduals(
      residuals, dof_indices, scaling_factor, Assembly::LocalDataKey{}, _vector_tags);
  if (!_abs_vector_tags.empty())
  {
    _absolute_residuals.resize(residuals.size());
    for (const auto i : index_range(residuals))
      _absolute_residuals[i] = std::abs(MetaPhysicL::raw_value(residuals[i]));
    assembly.cacheResiduals(_absolute_residuals,
                            dof_indices,
                            scaling_factor,
                            Assembly::LocalDataKey{},
                            _abs_vector_tags);
  }
}
Referenced by TaggingInterface::addResiduals(), TaggingInterface::addResidualsAndJacobian(), ADMortarScalarBase::computeResidual(), MortarScalarBase::computeResidual(), ADKernelScalarBase::computeResidual(), ADNodalKernel::computeResidual(), NodalKernel::computeResidual(), TimeNodalKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), FVScalarLagrangeMultiplierInterface::computeResidual(), NodalConstraint::computeResidual(), KernelScalarBase::computeScalarResidual(), and MortarConstraintBase::zeroInactiveLMDofs().
addResidualsAndJacobian()
template<typename Residuals , typename Indices > void TaggingInterface::addResidualsAndJacobian (Assembly & assembly, const Residuals & residuals, const Indices & dof_indices, Real scaling_factor) protected inherited
Add the provided incoming residuals and derivatives for the Jacobian, corresponding to the provided dof indices.
Definition at line 470 of file TaggingInterface.h.
{
  addResiduals(assembly, residuals, dof_indices, scaling_factor);
  addJacobian(assembly, residuals, dof_indices, scaling_factor);
}
Referenced by ADKernelScalarBase::computeJacobian(), FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVScalarLagrangeMultiplierInterface::computeJacobian(), FVElementalKernel::computeResidualAndJacobian(), ADKernelScalarBase::computeResidualAndJacobian(), and FVScalarLagrangeMultiplierConstraint::computeResidualAndJacobian().
addResidualsAndJacobianWithoutConstraints()
template<typename Residuals , typename Indices > void TaggingInterface::addResidualsAndJacobianWithoutConstraints (Assembly & assembly, const Residuals & residuals, const Indices & dof_indices, Real scaling_factor) protected inherited
Add the provided incoming residuals and derivatives for the Jacobian, corresponding to the provided dof indices.
This API should only be used if the caller knows that no libMesh-level constraints (hanging nodes or periodic boundary conditions) apply to the provided dof indices
Definition at line 492 of file TaggingInterface.h.
{
  addResidualsWithoutConstraints(assembly, residuals, dof_indices, scaling_factor);
  addJacobianWithoutConstraints(assembly, residuals, dof_indices, scaling_factor);
}
Referenced by ADMortarScalarBase::computeJacobian(), and ADMortarConstraint::computeJacobian().
addResidualsWithoutConstraints()
template<typename Residuals , typename Indices > void TaggingInterface::addResidualsWithoutConstraints (Assembly & assembly, const Residuals & residuals, const Indices & dof_indices, Real scaling_factor) protected inherited
Add the provided incoming residuals corresponding to the provided dof indices.
This API should only be used if the caller knows that no libMesh-level constraints (hanging nodes or periodic boundary conditions) apply to the provided dof indices
Definition at line 447 of file TaggingInterface.h.
{
  assembly.cacheResidualsWithoutConstraints(
      residuals, dof_indices, scaling_factor, Assembly::LocalDataKey{}, _vector_tags);
  if (!_abs_vector_tags.empty())
  {
    _absolute_residuals.resize(residuals.size());
    for (const auto i : index_range(residuals))
      _absolute_residuals[i] = std::abs(MetaPhysicL::raw_value(residuals[i]));
    assembly.cacheResidualsWithoutConstraints(_absolute_residuals,
                                              dof_indices,
                                              scaling_factor,
                                              Assembly::LocalDataKey{},
                                              _abs_vector_tags);
  }
}
Referenced by TaggingInterface::addResidualsAndJacobianWithoutConstraints().
addUserObjectDependencyHelper()
virtual void UserObjectInterface::addUserObjectDependencyHelper (const UserObject &) const inline protected virtual inherited
Helper for deriving classes to override to add dependencies when a UserObject is requested.
Reimplemented in UserObject, AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, AuxKernelTempl< RealVectorValue >, and InitialConditionBase.
Definition at line 108 of file UserObjectInterface.h.
{}
Referenced by UserObjectInterface::getUserObjectBaseByName().
addVectorPostprocessorDependencyHelper()
virtual void VectorPostprocessorInterface::addVectorPostprocessorDependencyHelper (const VectorPostprocessorName &) const inline protected virtual inherited
Helper for deriving classes to override to add dependencies when a VectorPostprocessor is requested.
Reimplemented in UserObject, AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, and AuxKernelTempl< RealVectorValue >.
Definition at line 311 of file VectorPostprocessorInterface.h.
  {
  }
Referenced by VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), and VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper().
assignTaggedLocalMatrix()
void TaggingInterface::assignTaggedLocalMatrix () protected inherited
Local Jacobian blocks will assigned as the current local kernel Jacobian.
It should be called after the local element matrix has been computed.
Definition at line 425 of file TaggingInterface.C.
{
  for (auto & ke : _ke_blocks)
    *ke = _local_ke;
}
Referenced by NodalEqualValueConstraint::computeJacobian().
assignTaggedLocalResidual()
void TaggingInterface::assignTaggedLocalResidual () protected inherited
Local residual blocks will assigned as the current local kernel residual.
It should be called after the local element vector has been computed.
Definition at line 365 of file TaggingInterface.C.
{
  for (auto & re : _re_blocks)
    *re = _local_re;
  for (auto & absre : _absre_blocks)
    for (const auto i : index_range(_local_re))
      (*absre)(i) = std::abs(_local_re(i));
}
Referenced by NodeFaceConstraint::computeResidual(), and NodalEqualValueConstraint::computeResidual().
castUserObject()
template<class T > const T & UserObjectInterface::castUserObject (const UserObject & uo_base, const std::string & param_name = "") const private inherited
Internal helper that casts the UserObject uo_base to the reqested type.
Exits with a useful error if the casting failed. If the parameter param_name is provided and is valid, a paramError() will be used instead.
Definition at line 136 of file UserObjectInterface.h.
{
  const T * uo = dynamic_cast<const T *>(&uo_base);
  if (!uo)
  {
    std::stringstream oss;
    oss << "The provided UserObject \"" << userObjectName(uo_base) << "\" of type "
        << userObjectType(uo_base)
        << " is not derived from the required type.\n\nThe UserObject must derive from "
        << MooseUtils::prettyCppType<T>() << ".";
    if (_uoi_moose_object.parameters().isParamValid(param_name))
      _uoi_moose_object.paramError(param_name, oss.str());
    else
      _uoi_moose_object.mooseError(oss.str());
  }
  return *uo;
}
checkParam()
void PostprocessorInterface::checkParam (const std::string & param_name, const unsigned int index = std::numeric_limits<unsigned int>::max()) const private inherited
Checks the parameters relating to a Postprocessor.
If index is not set, index checking is not performed.
Definition at line 139 of file PostprocessorInterface.C.
{
  const bool check_index = index != std::numeric_limits<unsigned int>::max();
  if (!_ppi_params.isParamValid(param_name))
    _ppi_moose_object.mooseError(
        "When getting a Postprocessor, failed to get a parameter with the name \"",
        param_name,
        "\".",
        "\n\nKnown parameters:\n",
        _ppi_moose_object.parameters());
  if (_ppi_params.isType<PostprocessorName>(param_name))
  {
    if (check_index && index > 0)
      _ppi_moose_object.paramError(param_name,
                                   "A Postprocessor was requested with index ",
                                   index,
                                   " but a single Postprocessor is coupled.");
  }
  else if (_ppi_params.isType<std::vector<PostprocessorName>>(param_name))
  {
    const auto & names = _ppi_params.get<std::vector<PostprocessorName>>(param_name);
    if (check_index && names.size() <= index)
      _ppi_moose_object.paramError(param_name,
                                   "A Postprocessor was requested with index ",
                                   index,
                                   " but only ",
                                   names.size(),
                                   " Postprocessors are coupled.");
  }
  else
  {
    _ppi_moose_object.mooseError(
        "Supplied parameter with name \"",
        param_name,
        "\" of type \"",
        _ppi_params.type(param_name),
        "\" is not an expected type for getting a Postprocessor.\n\n",
        "Allowed types are \"PostprocessorName\" and \"std::vector<PostprocessorName>\".");
  }
}
Referenced by PostprocessorInterface::coupledPostprocessors(), and PostprocessorInterface::getPostprocessorNameInternal().
checkVar()
void ScalarCoupleable::checkVar (const std::string & var_name) const private inherited
Check that the right kind of variable is being coupled in.
Parameters
var_name The name of the coupled variable
Definition at line 290 of file ScalarCoupleable.C.
{
  const auto var_name = _sc_parameters.checkForRename(var_name_in);
  auto it = _sc_coupled_vars.find(var_name);
  if (it != _sc_coupled_vars.end())
  {
    std::string cvars;
    for (auto jt : it->second)
      cvars += " " + jt->name();
    mooseError(_sc_name,
               ": Trying to couple a field variable where scalar variable is expected, '",
               var_name,
               " =",
               cvars,
               "'");
  }
  // NOTE: non-existent variables are handled in the constructor
}
Referenced by ScalarCoupleable::adCoupledScalarValue(), ScalarCoupleable::coupledMatrixTagScalarValue(), ScalarCoupleable::coupledScalar(), ScalarCoupleable::coupledScalarDot(), ScalarCoupleable::coupledScalarDotDot(), ScalarCoupleable::coupledScalarDotDotDu(), ScalarCoupleable::coupledScalarDotDotOld(), ScalarCoupleable::coupledScalarDotDu(), ScalarCoupleable::coupledScalarDotOld(), ScalarCoupleable::coupledScalarOrder(), ScalarCoupleable::coupledScalarValue(), ScalarCoupleable::coupledScalarValueOld(), ScalarCoupleable::coupledScalarValueOlder(), and ScalarCoupleable::coupledVectorTagScalarValue().
computeJacobian()
void ODEKernel::computeJacobian () override virtual inherited
Compute this object's contribution to the diagonal Jacobian entries.
Reimplemented from ScalarKernel.
Definition at line 43 of file ODEKernel.C.
{
  prepareMatrixTag(_assembly, _var.number(), _var.number());
  for (_i = 0; _i < _var.order(); _i++)
    for (_j = 0; _j < _var.order(); _j++)
      _local_ke(_i, _j) += computeQpJacobian();
  accumulateTaggedLocalMatrix();
  // compute off-diagonal jacobians wrt scalar variables
  const std::vector<MooseVariableScalar *> & scalar_vars = _sys.getScalarVariables(_tid);
  for (const auto & var : scalar_vars)
    computeOffDiagJacobianScalar(var->number());
}
computeNonlocalJacobian()
virtual void ResidualObject::computeNonlocalJacobian () inline virtual inherited
Compute this object's contribution to the diagonal Jacobian entries corresponding to nonlocal dofs of the variable.
Reimplemented in NonlocalIntegratedBC, and NonlocalKernel.
Definition at line 88 of file ResidualObject.h.
{}
computeNonlocalOffDiagJacobian()
virtual void ResidualObject::computeNonlocalOffDiagJacobian (unsigned int) inline virtual inherited
Computes Jacobian entries corresponding to nonlocal dofs of the jvar.
Reimplemented in NonlocalIntegratedBC, and NonlocalKernel.
Definition at line 93 of file ResidualObject.h.
{}
computeOffDiagJacobian()
virtual void ResidualObject::computeOffDiagJacobian (unsigned int) inline virtual inherited
Computes this object's contribution to off-diagonal blocks of the system Jacobian matrix.
Parameters
jvar The number of the coupled variable. We pass the number of the coupled variable instead of an actual variable object because we can query our system and obtain the variable object associated with it. E.g. we need to make sure we are getting undisplaced variables if we are working on the undisplaced mesh, and displaced variables if we are working on the displaced mesh
Reimplemented in ADIntegratedBCTempl< T >, ArrayIntegratedBC, ArrayLowerDIntegratedBC, ArrayNodalBC, IntegratedBC, LowerDIntegratedBC, NodalBC, NonlocalIntegratedBC, VectorIntegratedBC, VectorNodalBC, NodeElemConstraint, NodeFaceConstraint, ArrayDGKernel, ArrayDGLowerDKernel, DGKernelBase, DGLowerDKernel, DiracKernelTempl< T >, ADKernelScalarBase, ArrayKernel, EigenKernel, Kernel, KernelGrad, KernelValue, NonlocalKernel, VectorKernel, NodalKernel, ADScalarKernel, ADNodalBCTempl< Real, ADDirichletBCBase >, ADNodalBCTempl< T, ADDirichletBCBase >, ADNodalBCTempl< RealVectorValue, ADDirichletBCBase >, ADDGKernel, ADNodalKernel, DiracKernelBase, KernelScalarBase, FVElementalKernel, FVScalarLagrangeMultiplierConstraint, and ADKernelTempl< T >.
Definition at line 76 of file ResidualObject.h.
{}
computeOffDiagJacobianScalar()
void ODEKernel::computeOffDiagJacobianScalar (unsigned int) override virtual inherited
Computes jacobian block with respect to a scalar variable.
Parameters
jvar The number of the scalar variable
Reimplemented from ResidualObject.
Definition at line 60 of file ODEKernel.C.
{
  prepareMatrixTag(_assembly, _var.number(), jvar);
  MooseVariableScalar & var_j = _sys.getScalarVariable(_tid, jvar);
  for (_i = 0; _i < _var.order(); _i++)
    for (_j = 0; _j < var_j.order(); _j++)
    {
      if (jvar != _var.number())
        _local_ke(_i, _j) += computeQpOffDiagJacobianScalar(jvar);
    }
  accumulateTaggedLocalMatrix();
}
Referenced by ODEKernel::computeJacobian().
computeQpJacobian()
Real ODETimeDerivative::computeQpJacobian () override protected virtual
Reimplemented from ODEKernel.
Definition at line 34 of file ODETimeDerivative.C.
{
  if (_i == _j)
    return _du_dot_du[_i];
  else
    return 0;
}
computeQpOffDiagJacobian()
virtual Real ODEKernel::computeQpOffDiagJacobian (unsigned int) inline protected virtual inherited
Reimplemented in EnergyTermScalar, Product1BodyScalar, Product1BodyScalarLog, Product2BodyScalar, Product2BodyScalarLog, Product3BodyScalar, Product3BodyScalarLog, Reactant3BodyScalar, Reactant3BodyScalarLog, ParsedScalarReaction, Reactant2BodyScalar, Reactant2BodyScalarLog, and ScalarDiffusion.
Definition at line 37 of file ODEKernel.h.
{ return 0; }
Referenced by ODEKernel::computeQpOffDiagJacobianScalar().
computeQpOffDiagJacobianScalar()
virtual Real ODEKernel::computeQpOffDiagJacobianScalar (unsigned int jvar) inline protected virtual inherited
Reimplemented in ParsedODEKernel.
Definition at line 31 of file ODEKernel.h.
  {
    // Backwards compatibility
    return computeQpOffDiagJacobian(jvar);
  }
Referenced by ODEKernel::computeOffDiagJacobianScalar().
computeQpResidual()
Real ODETimeDerivative::computeQpResidual () override protected virtual
Reimplemented from ScalarKernel.
Definition at line 28 of file ODETimeDerivative.C.
{
  return _u_dot[_i];
}
computeResidual()
void ODETimeKernel::computeResidual () override virtual inherited
Compute this object's contribution to the residual.
Reimplemented from ODEKernel.
Definition at line 34 of file ODETimeKernel.C.
{
  prepareVectorTag(_assembly, _var.number());
  for (_i = 0; _i < _var.order(); _i++)
    _local_re(_i) += computeQpResidual();
  accumulateTaggedLocalResidual();
}
computeResidualAndJacobian()
void ResidualObject::computeResidualAndJacobian () virtual inherited
Compute this object's contribution to the residual and Jacobian simultaneously.
Reimplemented in ADIntegratedBCTempl< T >, ADNodalBCTempl< Real, ADDirichletBCBase >, ADNodalBCTempl< T, ADDirichletBCBase >, ADNodalBCTempl< RealVectorValue, ADDirichletBCBase >, IntegratedBC, NodalBC, ADMortarConstraint, FVElementalKernel, FVFluxKernel, InterfaceKernelTempl< T >, ADKernelTempl< T >, ADKernelGradTempl< T >, ADKernelScalarBase, Kernel, and FVScalarLagrangeMultiplierConstraint.
Definition at line 66 of file ResidualObject.C.
{
  mooseError(
      "This object has not yet implemented 'computeResidualAndJacobian'. If you would like that "
      "feature for this object, please contact a MOOSE developer.");
}
Referenced by ComputeResidualAndJacobianThread::compute().
connectControllableParams()
void MooseBaseParameterInterface::connectControllableParams (const std::string & parameter, const std::string & object_type, const std::string & object_name, const std::string & object_parameter) const inherited
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
Parameters
parameter Name of the controllable parameter of this action
object_type Type of the object added by this action.
object_name Name of the object added by this action.
object_parameter Name of the parameter of the object.
Definition at line 34 of file MooseBaseParameterInterface.C.
{
  MooseObjectParameterName primary_name(uniqueName(), parameter);
  const auto base_type = _factory.getValidParams(object_type).get<std::string>("_moose_base");
  MooseObjectParameterName secondary_name(base_type, object_name, object_parameter);
  _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
      primary_name, secondary_name);
  const auto & tags = _pars.get<std::vector<std::string>>("control_tags");
  for (const auto & tag : tags)
  {
    if (!tag.empty())
    {
      MooseObjectParameterName tagged_name(tag, _moose_base->name(), parameter);
      _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
          tagged_name, secondary_name);
    }
  }
}
coupledGenericScalarValue() [1/3]
template<> const GenericVariableValue< false > & ScalarCoupleable::coupledGenericScalarValue (const std::string & var_name, unsigned int comp) const protected inherited
Definition at line 151 of file ScalarCoupleable.C.
{
  return coupledScalarValue(var_name, comp);
}
coupledGenericScalarValue() [2/3]
template<> const GenericVariableValue< true > & ScalarCoupleable::coupledGenericScalarValue (const std::string & var_name, unsigned int comp) const protected inherited
Definition at line 159 of file ScalarCoupleable.C.
{
  return adCoupledScalarValue(var_name, comp);
}
coupledGenericScalarValue() [3/3]
template<bool is_ad> const GenericVariableValue< is_ad > & ScalarCoupleable::coupledGenericScalarValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns value of a coupled scalar variable for use in templated automatic differentiation classes.
Parameters
var_name Name of coupled scalar variable
comp Component number for vector of coupled scalar variables
Returns
Reference to a GenericVariableValue for the coupled scalar variable
coupledMatrixTagScalarValue()
const VariableValue & ScalarCoupleable::coupledMatrixTagScalarValue (const std::string & var_name, TagID tag, unsigned int comp = 0) const protected inherited
Returns value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
tag Tag ID of coupled matrix;
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
Definition at line 202 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  _sc_coupleable_matrix_tags.insert(tag);
  return getScalarVar(var_name, comp)->matrixTagSln(tag);
}
coupledPostprocessors()
std::size_t PostprocessorInterface::coupledPostprocessors (const std::string & param_name) const inherited
Returns number of Postprocessors coupled under parameter name.
Parameters
param_name The name of the Postprocessor parameter
Returns
Number of coupled post-processors, 1 if it's a single
Definition at line 129 of file PostprocessorInterface.C.
{
  checkParam(param_name);
  if (_ppi_params.isType<PostprocessorName>(param_name))
    return 1;
  return _ppi_params.get<std::vector<PostprocessorName>>(param_name).size();
}
Referenced by FunctionValuePostprocessor::FunctionValuePostprocessor().
coupledScalar()
unsigned int ScalarCoupleable::coupledScalar (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the index for a scalar coupled variable by name.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Index of coupled variable
Definition at line 93 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  return getScalarVar(var_name, comp)->number();
}
Referenced by ParsedODEKernel::ParsedODEKernel().
coupledScalarComponents()
unsigned int ScalarCoupleable::coupledScalarComponents (const std::string & var_name) const protected inherited
Return the number of components to the coupled scalar variable.
Parameters
var_name The of the coupled variable
Definition at line 343 of file ScalarCoupleable.C.
{
  const auto var_name = _sc_parameters.checkForRename(var_name_in);
  const auto it = _coupled_scalar_vars.find(var_name);
  if (it != _coupled_scalar_vars.end())
    return it->second.size();
  mooseError(_sc_name, ": Trying to get a non-existent variable '", var_name, "'");
}
coupledScalarDot()
const VariableValue & ScalarCoupleable::coupledScalarDot (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the time derivative of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a time derivative VariableValue for the coupled variable
Definition at line 243 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDot");
  return getScalarVar(var_name, comp)->uDot();
}
coupledScalarDotDot()
const VariableValue & ScalarCoupleable::coupledScalarDotDot (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the second time derivative of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a time derivative VariableValue for the coupled variable
Definition at line 251 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotDot");
  return getScalarVar(var_name, comp)->uDotDot();
}
coupledScalarDotDotDu()
const VariableValue & ScalarCoupleable::coupledScalarDotDotDu (const std::string & var_name, unsigned int comp = 0) const protected inherited
Second time derivative of a scalar coupled variable with respect to the coefficients.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the time derivative of the coupled variable with respect to the coefficients
Definition at line 282 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotDotDu");
  return getScalarVar(var_name, comp)->duDotDotDu();
}
coupledScalarDotDotOld()
const VariableValue & ScalarCoupleable::coupledScalarDotDotOld (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the old second time derivative of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a time derivative VariableValue for the coupled variable
Definition at line 267 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotDotOld");
  return getScalarVar(var_name, comp)->uDotDotOld();
}
coupledScalarDotDu()
const VariableValue & ScalarCoupleable::coupledScalarDotDu (const std::string & var_name, unsigned int comp = 0) const protected inherited
Time derivative of a scalar coupled variable with respect to the coefficients.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the time derivative of the coupled variable with respect to the coefficients
Definition at line 274 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotDu");
  return getScalarVar(var_name, comp)->duDotDu();
}
coupledScalarDotOld()
const VariableValue & ScalarCoupleable::coupledScalarDotOld (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the old time derivative of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a time derivative VariableValue for the coupled variable
Definition at line 259 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotOld");
  return getScalarVar(var_name, comp)->uDotOld();
}
coupledScalarOrder()
Order ScalarCoupleable::coupledScalarOrder (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the order for a scalar coupled variable by name.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Order of coupled variable
Definition at line 100 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return _sc_fe_problem.getMaxScalarOrder();
  return getScalarVar(var_name, comp)->order();
}
coupledScalarValue()
const VariableValue & ScalarCoupleable::coupledScalarValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
Definition at line 124 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  auto var = getScalarVar(var_name, comp);
  return _sc_is_implicit ? var->sln() : var->slnOld();
}
Referenced by BoltzmannSolverScalar::BoltzmannSolverScalar(), VariableSum::computeValue(), VariableSumLog::computeValue(), ScalarCoupleable::coupledGenericScalarValue(), ParsedAuxScalar::ParsedAuxScalar(), ParsedODEKernel::ParsedODEKernel(), and ParsedScalarRateCoefficient::ParsedScalarRateCoefficient().
coupledScalarValueOld()
const VariableValue & ScalarCoupleable::coupledScalarValueOld (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the old (previous time step) value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a old VariableValue for the coupled variable
Definition at line 216 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  validateExecutionerType(var_name, "coupledScalarValueOld");
  auto var = getScalarVar(var_name, comp);
  return _sc_is_implicit ? var->slnOld() : var->slnOlder();
}
coupledScalarValueOlder()
const VariableValue & ScalarCoupleable::coupledScalarValueOlder (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the older (two time steps previous) value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a older VariableValue for the coupled variable
Definition at line 228 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  validateExecutionerType(var_name, "coupledScalarValueOlder");
  auto var = getScalarVar(var_name, comp);
  if (_sc_is_implicit)
    return var->slnOlder();
  else
    mooseError("Older values not available for explicit schemes");
}
coupledVectorTagScalarValue()
const VariableValue & ScalarCoupleable::coupledVectorTagScalarValue (const std::string & var_name, TagID tag, unsigned int comp = 0) const protected inherited
Returns value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
tag Tag ID of coupled vector ;
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
Definition at line 181 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  if (!_sc_fe_problem.vectorTagExists(tag))
    mooseError("Attempting to couple to vector tag scalar with ID ",
               tag,
               "in ",
               _sc_name,
               ", but a vector tag with that ID does not exist");
  _sc_coupleable_vector_tags.insert(tag);
  return getScalarVar(var_name, comp)->vectorTagSln(tag);
}
customSetup()
virtual void SetupInterface::customSetup (const ExecFlagType &) inline virtual inherited
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
Reimplemented in Function.
Definition at line 61 of file SetupInterface.h.
{}
declareManagedRestartableDataWithContext()
template<typename T , typename... Args> Restartable::ManagedValue< T > Restartable::declareManagedRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declares a piece of "managed" restartable data and initialize it.
Here, "managed" restartable data means that the caller can destruct this data upon destruction of the return value of this method. Therefore, this ManagedValue<T> wrapper should survive after the final calls to dataStore() for it. That is... at the very end.
This is needed for objects whose destruction ordering is important, and enables natural c++ destruction in reverse construction order of the object that declares it.
See delcareRestartableData and declareRestartableDataWithContext for more information.
Definition at line 276 of file Restartable.h.
{
  auto & data_ptr =
      declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...);
  return Restartable::ManagedValue<T>(data_ptr);
}
declareRecoverableData()
template<typename T , typename... Args> T & Restartable::declareRecoverableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "recoverable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
Note - this data will NOT be restored on Restart!
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 351 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  registerRestartableNameWithFilterOnApp(full_name, Moose::RESTARTABLE_FILTER::RECOVERABLE);
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableData()
template<typename T , typename... Args> T & Restartable::declareRestartableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 269 of file Restartable.h.
{
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataHelper()
template<typename T , typename... Args> RestartableData< T > & Restartable::declareRestartableDataHelper (const std::string & data_name, void * context, Args &&... args) const private inherited
Helper function for declaring restartable data.
We use this function to reduce code duplication when returning const/nonconst references to the data.
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 303 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  // Here we will create the RestartableData even though we may not use this instance.
  // If it's already in use, the App will return a reference to the existing instance and we'll
  // return that one instead. We might refactor this to have the app create the RestartableData
  // at a later date.
  auto data_ptr =
      std::make_unique<RestartableData<T>>(full_name, context, std::forward<Args>(args)...);
  auto & restartable_data_ref = static_cast<RestartableData<T> &>(
      registerRestartableDataOnApp(std::move(data_ptr), _restartable_tid));
  return restartable_data_ref;
}
declareRestartableDataWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 294 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...).set();
}
declareRestartableDataWithObjectName()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectName (const std::string & data_name, const std::string & object_name, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
args Arguments to forward to the constructor of the data
Definition at line 323 of file Restartable.h.
{
  return declareRestartableDataWithObjectNameWithContext<T>(
      data_name, object_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataWithObjectNameWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectNameWithContext (const std::string & data_name, const std::string & object_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 333 of file Restartable.h.
{
  std::string old_name = _restartable_name;
  _restartable_name = object_name;
  T & value = declareRestartableDataWithContext<T>(data_name, context, std::forward<Args>(args)...);
  _restartable_name = old_name;
  return value;
}
determineState()
Moose::StateArg TransientInterface::determineState () const inline protected inherited
Create a functor state argument that corresponds to the implicit state of this object.
If we are implicit then we will return the current state. If we are not, then we will return the old state
Definition at line 80 of file TransientInterface.h.
{
  return _is_implicit ? Moose::currentState() : Moose::oldState();
}
Referenced by InternalSideIntegralVariablePostprocessor::computeFaceInfoIntegral(), SideIntegralVariablePostprocessor::computeFaceInfoIntegral(), InterfaceIntegralVariableValuePostprocessor::computeQpIntegral(), LayeredSideDiffusiveFluxAverage::computeQpIntegral(), SideIntegralFunctorUserObject::computeQpIntegral(), SideIntegralVariableUserObject::computeQpIntegral(), FVConstantScalarOutflowBC::computeQpResidual(), FVFunctorNeumannBC::computeQpResidual(), FVDiffusionInterface::computeQpResidual(), FVOneVarDiffusionInterface::computeQpResidual(), FVTwoVarContinuityConstraint::computeQpResidual(), FVAdvection::computeQpResidual(), FVAnisotropicDiffusion::computeQpResidual(), FVCoupledForce::computeQpResidual(), FVDiffusion::computeQpResidual(), FVDivergence::computeQpResidual(), FVFunctorTimeKernel::computeQpResidual(), FVMatAdvection::computeQpResidual(), FVBoundaryIntegralValueConstraint::computeQpResidual(), FVBoundedValueConstraint::computeQpResidual(), FVIntegralValueConstraint::computeQpResidual(), FVPointValueConstraint::computeQpResidual(), AdvectiveFluxAux::computeValue(), FunctorAux::computeValue(), SecondTimeDerivativeAux::computeValue(), TimeDerivativeAux::computeValue(), MeshDivisionFunctorReductionVectorPostprocessor::execute(), PositionsFunctorValueSampler::execute(), FunctorPositions::initialize(), and FunctorTimes::initialize().
enabled()
virtual bool MooseObject::enabled () const inline virtual inherited
Return the enabled status of the object.
Reimplemented in EigenKernel.
Definition at line 54 of file MooseObject.h.
{ return _enabled; }
Referenced by EigenKernel::enabled().
errorPrefix()
std::string MooseBaseErrorInterface::errorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for this object:
The following <error_type> occurred in the object "<name>", of type "<type>".
Definition at line 15 of file MooseBaseErrorInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the object \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseErrorInterface::mooseError(), and MooseBaseErrorInterface::mooseWarning().
getADDefaultValue()
const ADVariableValue * ScalarCoupleable::getADDefaultValue (const std::string & var_name) const private inherited
Helper method to return (and insert if necessary) the AD default value for an uncoupled variable.
Parameters
var_name the name of the variable for which to retrieve a default value
Returns
ADVariableValue * a pointer to the associated ADVariableValue.
Definition at line 167 of file ScalarCoupleable.C.
{
  auto default_value_it = _dual_default_value.find(var_name);
  if (default_value_it == _dual_default_value.end())
  {
    auto value = std::make_unique<ADVariableValue>(_sc_fe_problem.getMaxScalarOrder(),
                                                   _sc_parameters.defaultCoupledValue(var_name));
    default_value_it = _dual_default_value.insert(std::make_pair(var_name, std::move(value))).first;
  }
  return default_value_it->second.get();
}
Referenced by ScalarCoupleable::adCoupledScalarValue().
getCheckedPointerParam()
template<typename T > T MooseBaseParameterInterface::getCheckedPointerParam (const std::string & name, const std::string & error_string = "") const inherited
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
The template parameter must be a pointer or an error will be thrown.
Definition at line 264 of file MooseBaseParameterInterface.h.
{
  return parameters().getCheckedPointerParam<T>(name, error_string);
}
getCoupledMooseScalarVars()
const std::vector< MooseVariableScalar * > & ScalarCoupleable::getCoupledMooseScalarVars () inline inherited
Get the list of coupled scalar variables.
Returns
The list of coupled variables
Definition at line 45 of file ScalarCoupleable.h.
  {
    return _coupled_moose_scalar_vars;
  }
Referenced by AuxScalarKernel::AuxScalarKernel(), MortarScalarBase::computeJacobian(), and ScalarInitialCondition::ScalarInitialCondition().
getDataFileName()
std::string DataFileInterface< MooseObject >::getDataFileName (const std::string & param) const inherited
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
relative to the input file directory
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
relative to the input file directory
Definition at line 34 of file DataFileInterface.C.
{
  {
    const auto & absolute_path = _parent.template getParam<FileName>(param);
    if (MooseUtils::checkFileReadable(absolute_path, false, false, false))
    {
      _parent.paramInfo(param, "Data file '", absolute_path, "' found relative to the input file.");
      return absolute_path;
    }
  }
  const auto & relative_path = _parent.parameters().rawParamVal(param);
  return getDataFileNameByName(relative_path, &param);
}
getDataFileNameByName()
std::string DataFileInterface< MooseObject >::getDataFileNameByName (const std::string & name, const std::string * param = nullptr) const inherited
Returns the path of a data file for a given relative file path.
This can be used for hardcoded datafile names and will search the same locations as getDataFileName. The optional param pointer can be used to turn the mooseErrors this function emits into paramErrors
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
Definition at line 42 of file DataFileInterface.C.
{
  const auto share_dir = MooseUtils::pathjoin(Moose::getExecutablePath(), "..", "share");
  if (MooseUtils::pathIsDirectory(share_dir))
  {
    const auto dirs = MooseUtils::listDir(share_dir, false);
    for (const auto & data_dir : dirs)
    {
      const auto path = MooseUtils::pathjoin(data_dir, "data", relative_path);
      if (MooseUtils::checkFileReadable(path, false, false, false))
      {
        if (param)
          _parent.paramInfo(
              *param, "Data file '", path, "' found in an installed app distribution.");
        else
          mooseInfo("Data file '", path, "' found in an installed app distribution.");
        return path;
      }
    }
  }
  for (const auto & data_dir : Registry::getRegistry().getDataFilePaths())
  {
    const auto path = MooseUtils::pathjoin(data_dir, relative_path);
    if (MooseUtils::checkFileReadable(path, false, false, false))
    {
      if (param)
        _parent.paramInfo(*param, "Data file '", path, "' found in a source repository.");
      else
        mooseInfo("Data file '", path, "' found in a source repository.");
      return path;
    }
  }
  mooseException(param ? _parent.parameters().inputLocation(*param) : _parent.name(),
                 ": Unable to find data file '",
                 relative_path,
                 "' anywhere");
}
getDefaultPostprocessorValueByName()
PostprocessorValue PostprocessorInterface::getDefaultPostprocessorValueByName (const PostprocessorName & name) const private inherited
Returns
The default value stored in the PostprocessorName name.
Definition at line 96 of file PostprocessorInterface.C.
{
  mooseAssert(isDefaultPostprocessorValueByName(name), "Not a default value");
  Real real_value = -std::numeric_limits<Real>::max();
  std::istringstream ss(name);
  ss >> real_value;
  return real_value;
}
Referenced by PostprocessorInterface::getPostprocessorValueInternal().
getDefaultValue()
const VariableValue * ScalarCoupleable::getDefaultValue (const std::string & var_name) const private inherited
Helper method to return (and insert if necessary) the default value for an uncoupled variable.
Parameters
var_name the name of the variable for which to retrieve a default value
Returns
VariableValue * a pointer to the associated VarirableValue.
Definition at line 110 of file ScalarCoupleable.C.
{
  auto default_value_it = _default_value.find(var_name);
  if (default_value_it == _default_value.end())
  {
    auto value = std::make_unique<VariableValue>(_sc_fe_problem.getMaxScalarOrder(),
                                                 _sc_parameters.defaultCoupledValue(var_name));
    default_value_it = _default_value.insert(std::make_pair(var_name, std::move(value))).first;
  }
  return default_value_it->second.get();
}
Referenced by ScalarCoupleable::coupledMatrixTagScalarValue(), ScalarCoupleable::coupledScalarValue(), ScalarCoupleable::coupledScalarValueOld(), ScalarCoupleable::coupledScalarValueOlder(), and ScalarCoupleable::coupledVectorTagScalarValue().
getExecuteOnEnum()
const ExecFlagEnum & SetupInterface::getExecuteOnEnum () const inherited
Return the execute on MultiMooseEnum for this object.
Definition at line 65 of file SetupInterface.C.
{
  return _execute_enum;
}
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), MultiAppTransfer::checkMultiAppExecuteOn(), IntegralPreservingFunctionIC::initialSetup(), MultiAppConservativeTransfer::initialSetup(), Terminator::initialSetup(), ElementReporter::shouldStore(), GeneralReporter::shouldStore(), and NodalReporter::shouldStore().
getFunction()
const Function & FunctionInterface::getFunction (const std::string & name) const inherited
Get a function with a given name.
Parameters
name The name of the parameter key of the function to retrieve
Returns
The function with name associated with the parameter 'name'
Definition at line 30 of file FunctionInterface.C.
{
  return _fni_feproblem.getFunction(_fni_params.get<FunctionName>(name), _fni_tid);
}
Referenced by FunctionDT::FunctionDT(), and Output::Output().
getFunctionByName()
const Function & FunctionInterface::getFunctionByName (const FunctionName & name) const inherited
Get a function with a given name.
Parameters
name The name of the function to retrieve
Returns
The function with name 'name'
Definition at line 36 of file FunctionInterface.C.
{
  return _fni_feproblem.getFunction(name, _fni_tid);
}
Referenced by ArrayBodyForce::ArrayBodyForce(), ArrayFunctionIC::ArrayFunctionIC(), CompositeFunction::CompositeFunction(), FunctionArrayAux::FunctionArrayAux(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionRankTwoTensorTempl< is_ad >::GenericFunctionRankTwoTensorTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), LinearCombinationFunction::LinearCombinationFunction(), and LineFunctionSampler::LineFunctionSampler().
getMasterSeed()
unsigned int RandomInterface::getMasterSeed () const inline inherited
Definition at line 66 of file RandomInterface.h.
{ return _master_seed; }
getMatrixTags()
const std::set< TagID > & TaggingInterface::getMatrixTags (MatrixTagsKey) const inline inherited
Definition at line 95 of file TaggingInterface.h.
{ return _matrix_tags; }
getMooseApp()
MooseApp & MooseBase::getMooseApp () const inline inherited
Get the MooseApp this class is associated with.
Definition at line 35 of file MooseBase.h.
{ return _app; }
Referenced by ReporterTransferInterface::checkHasReporterValue(), Coupleable::checkWritableVar(), MooseBaseParameterInterface::connectControllableParams(), Coupleable::Coupleable(), MortarData::createMortarInterface(), EigenProblem::doFreeNonlinearPowerIterations(), Terminator::execute(), FEProblemSolve::FEProblemSolve(), SolutionInvalidInterface::flagInvalidSolutionInternal(), MaterialPropertyInterface::MaterialPropertyInterface(), MooseVariableDataFV< OutputType >::MooseVariableDataFV(), ProgressOutput::output(), MooseBaseParameterInterface::paramError(), PetscOutputInterface::petscLinearOutput(), PetscOutputInterface::petscNonlinearOutput(), PetscOutputInterface::PetscOutputInterface(), PostprocessorInterface::postprocessorsAdded(), MultiApp::preTransfer(), Reporter::Reporter(), ReporterInterface::reportersAdded(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
getParam() [1/2]
template<typename T > const T & MooseBaseParameterInterface::getParam (const std::string & name) const inherited
Retrieve a parameter for the object.
Parameters
name The name of the parameter
Returns
The value of the parameter
Definition at line 200 of file MooseBaseParameterInterface.h.
{
  return InputParameters::getParamHelper(name, _pars, static_cast<T *>(0));
}
Referenced by AddGeneralReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddPeriodicBCAction::act(), CreateDisplacedProblemAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), ConstraintWarehouse::addObject(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), ADNodalKernel::ADNodalKernel(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), PiecewiseTabularBase::buildFromJSON(), Console::Console(), FEProblemBase::createTagSolutions(), AccumulateReporter::declareLateValues(), DerivativeParsedMaterialTempl< is_ad >::DerivativeParsedMaterialTempl(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EigenKernel::EigenKernel(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), GenericConstantRankTwoTensorTempl< is_ad >::GenericConstantRankTwoTensorTempl(), MooseApp::getCheckpointDirectories(), ExecutorInterface::getExecutor(), AdvancedOutput::init(), IterationAdaptiveDT::init(), TimeSequenceStepper::init(), AttribThread::initFrom(), AttribSysNum::initFrom(), AttribResidualObject::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), Console::initialSetup(), IterationAdaptiveDT::limitDTToPostprocessorValue(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MortarConsumerInterface::MortarConsumerInterface(), NestedDivision::NestedDivision(), ConsoleUtils::outputExecutionInformation(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedMaterialTempl< is_ad >::ParsedMaterialTempl(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), ParsedODEKernel::ParsedODEKernel(), ParsedPostprocessor::ParsedPostprocessor(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), Moose::FV::setInterpolationMethod(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), TimePeriod::TimePeriod(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and VectorOfPostprocessors::VectorOfPostprocessors().
getParam() [2/2]
template<typename T1 , typename T2 > std::vector< std::pair< T1, T2 > > MooseBaseParameterInterface::getParam (const std::string & param1, const std::string & param2) const inherited
Retrieve two parameters and provide pair of parameters for the object.
Parameters
param1 The name of first parameter
param2 The name of second parameter
Returns
Vector of pairs of first and second parameters
Definition at line 257 of file MooseBaseParameterInterface.h.
{
  return _pars.get<T1, T2>(param1, param2);
}
getPostprocessorName()
const PostprocessorName & PostprocessorInterface::getPostprocessorName (const std::string & param_name, const unsigned int index = 0) const inherited
Get the name of a postprocessor.
This can only be used if the postprocessor parameter does not have a default value set (see isDefaultPostprocessorValue()), in which case the "name" is actually the default value.
Parameters
param_name The name of the Postprocessor parameter
index The index of the Postprocessor
Returns
The name of the given Postprocessor
Definition at line 185 of file PostprocessorInterface.C.
{
  return getPostprocessorNameInternal(param_name, index, /* allow_default_value = */ false);
}
Referenced by EigenKernel::EigenKernel().
getPostprocessorNameInternal()
const PostprocessorName & PostprocessorInterface::getPostprocessorNameInternal (const std::string & param_name, const unsigned int index, const bool allow_default_value = true) const private inherited
Internal method for getting the PostprocessorName associated with a paremeter.
Needed in order to allow the return of a name that is a default value.
Definition at line 192 of file PostprocessorInterface.C.
{
  checkParam(param_name, index);
  const auto & name = _ppi_params.isType<PostprocessorName>(param_name)
                          ? _ppi_params.get<PostprocessorName>(param_name)
                          : _ppi_params.get<std::vector<PostprocessorName>>(param_name)[index];
  if (!allow_default_value && isDefaultPostprocessorValueByName(name))
  {
    std::stringstream oss;
    oss << "Cannot get the name associated with PostprocessorName parameter \"" << param_name
        << "\"";
    if (index)
      oss << " at index " << index;
    oss << ",\nbecause said parameter is a default Postprocessor value.";
    _ppi_moose_object.paramError(param_name, oss.str());
  }
  return name;
}
Referenced by PostprocessorInterface::getPostprocessorName(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), and PostprocessorInterface::isDefaultPostprocessorValue().
getPostprocessorValue()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValue (const std::string & param_name, const unsigned int index = 0) const inherited
doco-normal-methods-begin Retrieve the value of a Postprocessor or one of it's old or older values
Parameters
param_name The name of the Postprocessor parameter (see below)
index The index of the Postprocessor
Returns
A reference to the desired value
The name required by this method is the name that is hard-coded into your source code. For example, if you have a Kernel that requires a Postprocessor you may have an input file with "pp = my_pp", this function requires the "pp" name as input (see .../moose_test/functions/PostprocessorFunction.C)
see getPostprocessorValueByName getPostprocessorValueOldByName getPostprocessorValueOlderByName
Definition at line 36 of file PostprocessorInterface.C.
{
  return getPostprocessorValueInternal(param_name, index, /* t_index = */ 0);
}
Referenced by EigenKernel::EigenKernel(), FunctionValuePostprocessor::FunctionValuePostprocessor(), LinearCombinationPostprocessor::LinearCombinationPostprocessor(), ParsedPostprocessor::ParsedPostprocessor(), and PicardSolve::PicardSolve().
getPostprocessorValueByName()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueByName (const PostprocessorName & name) const virtual inherited
Retrieve the value of the Postprocessor.
Parameters
name Postprocessor name (see below)
Returns
A reference to the desired value
The name required by this method is the name defined in the input file. For example, if you have a Kernel that requires a Postprocessor you may have an input file with "pp = my_pp", this method requires the "my_pp" name as input (see .../moose_test/functions/PostprocessorFunction.C)
see getPostprocessorValue getPostprocessorValueOld getPostprocessorValueOlder
Definition at line 57 of file PostprocessorInterface.C.
{
  return getPostprocessorValueByNameInternal(name, /* t_index = */ 0);
}
Referenced by EigenKernel::EigenKernel(), PIDTransientControl::execute(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), ParsedODEKernel::ParsedODEKernel(), PicardSolve::savePostprocessorValues(), SecantSolve::savePostprocessorValues(), SteffensenSolve::savePostprocessorValues(), Terminator::Terminator(), PicardSolve::transformPostprocessors(), SecantSolve::transformPostprocessors(), SteffensenSolve::transformPostprocessors(), and VectorOfPostprocessors::VectorOfPostprocessors().
getPostprocessorValueByNameInternal()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueByNameInternal (const PostprocessorName & name, std::size_t t_index) const private inherited
Definition at line 246 of file PostprocessorInterface.C.
{
  mooseAssert(t_index < 3, "Invalid time index");
  mooseAssert(!isDefaultPostprocessorValueByName(name), "Should not be default");
  // If all pps have been added, we can check for existance
  if (postprocessorsAdded() && !hasPostprocessorByName(name))
    _ppi_moose_object.mooseError("A Postprocessor with the name \"", name, "\" was not found.");
  if (t_index == 0)
    addPostprocessorDependencyHelper(name);
  return _ppi_feproblem.getReporterData().getReporterValue<PostprocessorValue>(
      PostprocessorReporterName(name), _ppi_moose_object, REPORTER_MODE_ROOT, t_index);
}
Referenced by PostprocessorInterface::getPostprocessorValueByName(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::getPostprocessorValueOldByName(), and PostprocessorInterface::getPostprocessorValueOlderByName().
getPostprocessorValueInternal()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueInternal (const std::string & param_name, unsigned int index, std::size_t t_index) const private inherited
Internal methods for getting Postprocessor values.
Definition at line 218 of file PostprocessorInterface.C.
{
  const auto & name = getPostprocessorNameInternal(param_name, index);
  // If the Postprocessor is a default value (either set by addParam or set to a constant
  // value by the user in input/an action), we covert the name to a value, store said
  // value locally, and return it so that it fits in with the rest of the interface
  // (needing a reference to a value)
  if (isDefaultPostprocessorValueByName(name))
  {
    const auto value = getDefaultPostprocessorValueByName(name);
    const auto & value_ref =
        *_default_values.emplace(name, std::make_unique<PostprocessorValue>(value))
             .first->second; // first is inserted pair, second is value in pair
    mooseAssert(value == value_ref, "Inconsistent default value");
    return value_ref;
  }
  // If not a default and all pps have been added, we check check for existance
  else if (postprocessorsAdded() && !hasPostprocessorByName(name))
    _ppi_moose_object.paramError(
        param_name, "A Postprocessor with the name \"", name, "\" was not found.");
  return getPostprocessorValueByNameInternal(name, t_index);
}
Referenced by PostprocessorInterface::getPostprocessorValue(), PostprocessorInterface::getPostprocessorValueOld(), and PostprocessorInterface::getPostprocessorValueOlder().
getPostprocessorValueOld()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOld (const std::string & param_name, const unsigned int index = 0) const inherited
Definition at line 43 of file PostprocessorInterface.C.
{
  return getPostprocessorValueInternal(param_name, index, /* t_index = */ 1);
}
getPostprocessorValueOldByName()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOldByName (const PostprocessorName & name) const inherited
Definition at line 63 of file PostprocessorInterface.C.
{
  return getPostprocessorValueByNameInternal(name, /* t_index = */ 1);
}
Referenced by EigenKernel::EigenKernel().
getPostprocessorValueOlder()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOlder (const std::string & param_name, const unsigned int index = 0) const inherited
Definition at line 50 of file PostprocessorInterface.C.
{
  return getPostprocessorValueInternal(param_name, index, /* t_index = */ 2);
}
getPostprocessorValueOlderByName()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOlderByName (const PostprocessorName & name) const inherited
Definition at line 69 of file PostprocessorInterface.C.
{
  return getPostprocessorValueByNameInternal(name, /* t_index = */ 2);
}
getRandomLong()
unsigned long RandomInterface::getRandomLong () const inherited
Returns the next random number (long) from the generator tied to this object (elem/node).
Definition at line 69 of file RandomInterface.C.
{
  mooseAssert(_generator, "Random Generator is NULL, did you call setRandomResetFrequency()?");
  dof_id_type id;
  if (_is_nodal)
    id = _curr_node->id();
  else
    id = _curr_element->id();
  return _generator->randl(id);
}
getRandomReal()
Real RandomInterface::getRandomReal () const inherited
Returns the next random number (Real) from the generator tied to this object (elem/node).
Definition at line 83 of file RandomInterface.C.
{
  mooseAssert(_generator, "Random Generator is NULL, did you call setRandomResetFrequency()?");
  dof_id_type id;
  if (_is_nodal)
    id = _curr_node->id();
  else
    id = _curr_element->id();
  return _generator->rand(id);
}
getRenamedParam()
template<typename T > const T & MooseBaseParameterInterface::getRenamedParam (const std::string & old_name, const std::string & new_name) const inherited
Retrieve a renamed parameter for the object.
This helper makes sure we check both names before erroring, and that only one parameter is passed to avoid silent errors
Parameters
old_name the old name for the parameter
new_name the new name for the parameter
Definition at line 207 of file MooseBaseParameterInterface.h.
{
  // this enables having a default on the new parameter but bypassing it with the old one
  // Most important: accept new parameter
  if (isParamSetByUser(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Second most: accept old parameter
  else if (isParamValid(old_name) && !isParamSetByUser(new_name))
    return InputParameters::getParamHelper(old_name, _pars, static_cast<T *>(0));
  // Third most: accept default for new parameter
  else if (isParamValid(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Refuse: no default, no value passed
  else if (!isParamValid(old_name) && !isParamValid(new_name))
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' is being retrieved without being set.\n"
               "Did you misspell it?");
  // Refuse: both old and new parameters set by user
  else
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' may not be provided alongside former parameter '" + old_name + "'");
}
getResetOnTime()
ExecFlagType RandomInterface::getResetOnTime () const inline inherited
Definition at line 68 of file RandomInterface.h.
{ return _reset_on; }
getRestartableData()
template<typename T , typename... Args> const T & Restartable::getRestartableData (const std::string & data_name) const protected inherited
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
Forwarded arguments are not allowed in this case because we assume that the object is restarted and we won't need different constructors to initialize it.
NOTE: This returns a const reference! Make sure you store it in a const reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
Definition at line 287 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, nullptr).get();
}
getScalarVar()
const MooseVariableScalar * ScalarCoupleable::getScalarVar (const std::string & var_name, unsigned int comp) const protected inherited
Extract pointer to a scalar coupled variable.
Parameters
var_name Name of parameter desired
comp Component number of multiple coupled variables
Returns
Pointer to the desired variable
Definition at line 311 of file ScalarCoupleable.C.
{
  const auto var_name = _sc_parameters.checkForRename(var_name_in);
  const auto it = _coupled_scalar_vars.find(var_name);
  if (it != _coupled_scalar_vars.end())
  {
    const auto & entry = it->second;
    if (comp < entry.size())
      return entry[comp];
    else
      mooseError(_sc_name, ": Trying to get a non-existent component of variable '", var_name, "'");
  }
  else
    mooseError(_sc_name, ": Trying to get a non-existent variable '", var_name, "'");
}
Referenced by ScalarCoupleable::adCoupledScalarValue(), ScalarCoupleable::coupledMatrixTagScalarValue(), ScalarCoupleable::coupledScalar(), ScalarCoupleable::coupledScalarDot(), ScalarCoupleable::coupledScalarDotDot(), ScalarCoupleable::coupledScalarDotDotDu(), ScalarCoupleable::coupledScalarDotDotOld(), ScalarCoupleable::coupledScalarDotDu(), ScalarCoupleable::coupledScalarDotOld(), ScalarCoupleable::coupledScalarOrder(), ScalarCoupleable::coupledScalarValue(), ScalarCoupleable::coupledScalarValueOld(), ScalarCoupleable::coupledScalarValueOlder(), ScalarCoupleable::coupledVectorTagScalarValue(), ParsedAuxScalar::ParsedAuxScalar(), ParsedODEKernel::ParsedODEKernel(), and ParsedScalarRateCoefficient::ParsedScalarRateCoefficient().
getScalarVariableCoupleableMatrixTags()
const std::set< TagID > & ScalarCoupleable::getScalarVariableCoupleableMatrixTags () const inline inherited
Definition at line 55 of file ScalarCoupleable.h.
  {
    return _sc_coupleable_matrix_tags;
  }
getScalarVariableCoupleableVectorTags()
const std::set< TagID > & ScalarCoupleable::getScalarVariableCoupleableVectorTags () const inline inherited
Definition at line 50 of file ScalarCoupleable.h.
  {
    return _sc_coupleable_vector_tags;
  }
getScatterVectorPostprocessorValue()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValue (const std::string & param_name, const std::string & vector_name) const inherited
Return the scatter value for the post processor.
This is only valid when you expec the vector to be of lenghth "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
param_name The name of the parameter holding the vpp name
vector_name The name of the vector
Returns
The reference to the current scatter value
Definition at line 106 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getScatterVectorPostprocessorValueByName(getVectorPostprocessorName(param_name),
                                                  vector_name);
}
getScatterVectorPostprocessorValueByName()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValueByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
Return the scatter value for the post processor.
This is only valid when you expec the vector to be of lenghth "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
name The name of the VectorPostprocessor
vector_name The name of the vector
Returns
The reference to the current scatter value
Definition at line 115 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorContextByNameHelper(name, vector_name).getScatterValue();
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValue().
getScatterVectorPostprocessorValueOld()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValueOld (const std::string & param_name, const std::string & vector_name) const inherited
Return the old scatter value for the post processor.
This is only valid when you expec the vector to be of lenghth "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
param_name The name of the parameter holding the vpp name
vector_name The name of the vector
Returns
The reference to the old scatter value
Definition at line 122 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getScatterVectorPostprocessorValueOldByName(getVectorPostprocessorName(param_name),
                                                     vector_name);
}
getScatterVectorPostprocessorValueOldByName()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValueOldByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
Return the old scatter value for the post processor.
This is only valid when you expect the vector to be of length "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
name The name of the VectorPostprocessor
vector_name The name of the vector
Returns
The reference to the old scatter value
Definition at line 131 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorContextByNameHelper(name, vector_name).getScatterValueOld();
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValueOld().
getSeed()
unsigned int RandomInterface::getSeed (std::size_t id) inherited
Get the seed for the passed in elem/node id.
Parameters
id - dof object id
Returns
current seed for this id
Definition at line 61 of file RandomInterface.C.
{
  mooseAssert(_random_data, "RandomData object is NULL!");
  return _random_data->getSeed(id);
}
getUserObject()
template<class T > const T & UserObjectInterface::getUserObject (const std::string & param_name, bool is_dependency = true) const inherited
Get an user object with a given parameter param_name.
Parameters
param_name The name of the parameter key of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with name associated with the parameter param_name
Definition at line 160 of file UserObjectInterface.h.
{
  return castUserObject<T>(getUserObjectBase(param_name, is_dependency), param_name);
}
getUserObjectBase()
const UserObject & UserObjectInterface::getUserObjectBase (const std::string & param_name, bool is_dependency = true) const inherited
Get an user object with a given parameter param_name.
Parameters
param_name The name of the parameter key of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with name associated with the parameter param_name
Definition at line 79 of file UserObjectInterface.C.
{
  const auto object_name = getUserObjectName(param_name);
  if (!hasUserObjectByName(object_name))
    _uoi_moose_object.paramError(
        param_name, "The requested UserObject with the name \"", object_name, "\" was not found.");
  return getUserObjectBaseByName(object_name, is_dependency);
}
Referenced by UserObjectInterface::getUserObject().
getUserObjectBaseByName()
const UserObject & UserObjectInterface::getUserObjectBaseByName (const UserObjectName & object_name, bool is_dependency = true) const inherited
Get an user object with the name object_name.
Parameters
object_name The name of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with the name object_name
Definition at line 91 of file UserObjectInterface.C.
{
  if (!hasUserObjectByName(object_name))
    _uoi_moose_object.mooseError(
        "The requested UserObject with the name \"", object_name, "\" was not found.");
  const auto & uo_base_tid0 = _uoi_feproblem.getUserObjectBase(object_name, /* tid = */ 0);
  if (is_dependency)
    addUserObjectDependencyHelper(uo_base_tid0);
  const THREAD_ID tid = uo_base_tid0.needThreadedCopy() ? _uoi_tid : 0;
  return _uoi_feproblem.getUserObjectBase(object_name, tid);
}
Referenced by UserObject::getDependObjects(), UserObjectInterface::getUserObjectBase(), and UserObjectInterface::getUserObjectByName().
getUserObjectByName()
template<class T > const T & UserObjectInterface::getUserObjectByName (const UserObjectName & object_name, bool is_dependency = true) const inherited
Get an user object with the name object_name.
Parameters
object_name The name of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with the name object_name
Definition at line 167 of file UserObjectInterface.h.
{
  return castUserObject<T>(getUserObjectBaseByName(object_name, is_dependency));
}
getUserObjectName()
UserObjectName UserObjectInterface::getUserObjectName (const std::string & param_name) const inherited
Returns
The name of the user object associated with the parameter param_name
Definition at line 34 of file UserObjectInterface.C.
{
  const auto & params = _uoi_moose_object.parameters();
  if (!params.isParamValid(param_name))
    _uoi_moose_object.mooseError("Failed to get a parameter with the name \"",
                                 param_name,
                                 "\" when getting a UserObjectName.",
                                 "\n\nKnown parameters:\n",
                                 _uoi_moose_object.parameters());
  // Other interfaces will use this interface (PostprocessorInterface, VectorPostprocessorInterface)
  // to grab UOs with a specialized name, so we need to check them all
  UserObjectName name;
  if (params.isType<UserObjectName>(param_name))
    name = params.get<UserObjectName>(param_name);
  else if (params.isType<PostprocessorName>(param_name))
    name = params.get<PostprocessorName>(param_name);
  else if (params.isType<VectorPostprocessorName>(param_name))
    name = params.get<VectorPostprocessorName>(param_name);
  else if (params.isType<std::string>(param_name))
    name = params.get<std::string>(param_name);
  else
    _uoi_moose_object.paramError(
        param_name,
        "Parameter of type \"",
        params.type(param_name),
        "\" is not an expected type for getting the name of a UserObject.");
  return name;
}
Referenced by UserObjectInterface::getUserObjectBase(), and UserObjectInterface::hasUserObject().
getVariable()
const MooseVariableFieldBase & ResidualObject::getVariable (unsigned int jvar_num) const inline protected inherited
Retrieve the variable object from our system associated with jvar_num.
Definition at line 119 of file ResidualObject.h.
  {
    return _sys.getVariable(_tid, jvar_num);
  }
Referenced by ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayIntegratedBC::computeOffDiagJacobian(), ArrayNodalBC::computeOffDiagJacobian(), IntegratedBC::computeOffDiagJacobian(), NonlocalIntegratedBC::computeOffDiagJacobian(), VectorIntegratedBC::computeOffDiagJacobian(), NodeFaceConstraint::computeOffDiagJacobian(), ArrayDGKernel::computeOffDiagJacobian(), ArrayDGLowerDKernel::computeOffDiagJacobian(), DGKernelBase::computeOffDiagJacobian(), DGLowerDKernel::computeOffDiagJacobian(), ArrayKernel::computeOffDiagJacobian(), EigenKernel::computeOffDiagJacobian(), Kernel::computeOffDiagJacobian(), KernelGrad::computeOffDiagJacobian(), KernelValue::computeOffDiagJacobian(), NonlocalKernel::computeOffDiagJacobian(), VectorKernel::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), ADDGKernel::computeOffDiagJacobian(), and KernelScalarBase::computeScalarOffDiagJacobian().
getVectorPostprocessorByNameHelper()
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorByNameHelper (const VectorPostprocessorName & name, const std::string & vector_name, bool broadcast, std::size_t t_index) const private inherited
Helper function for extracting VPP data from ReporterData object.
Definition at line 269 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessorByName(name, vector_name);
  addVectorPostprocessorDependencyHelper(name);
  const ReporterMode mode = broadcast ? REPORTER_MODE_REPLICATED : REPORTER_MODE_ROOT;
  return _vpi_feproblem.getReporterData().getReporterValue<VectorPostprocessorValue>(
      VectorPostprocessorReporterName(name, vector_name), _vpi_moose_object, mode, t_index);
}
Referenced by VectorPostprocessorInterface::getVectorPostprocessorValueByName(), and VectorPostprocessorInterface::getVectorPostprocessorValueOldByName().
getVectorPostprocessorContextByNameHelper()
const VectorPostprocessorContext< VectorPostprocessorValue > & VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper (const VectorPostprocessorName & name, const std::string & vector_name) const private inherited
Helper for getting the VPP context that handles scatter values.
Definition at line 284 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessorByName(name, vector_name);
  addVectorPostprocessorDependencyHelper(name);
  // The complete name of the store Reporter value
  const VectorPostprocessorReporterName r_name(name, vector_name);
  // Indicate the scatter value is desired, so the the VectorPostprocessorContext will do scatter
  _vpi_feproblem.getReporterData().getReporterValue<VectorPostprocessorValue>(
      r_name, _vpi_moose_object, REPORTER_MODE_VPP_SCATTER, 0);
  // Retrieve the VectorPostprocessorContext which contains the scattered value to be referenced
  const auto & context = _vpi_feproblem.getReporterData().getReporterContextBase(r_name);
  auto vpp_context_ptr =
      dynamic_cast<const VectorPostprocessorContext<VectorPostprocessorValue> *>(&context);
  mooseAssert(vpp_context_ptr, "Failed to get the VectorPostprocessorContext");
  return *vpp_context_ptr;
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValueByName(), and VectorPostprocessorInterface::getScatterVectorPostprocessorValueOldByName().
getVectorPostprocessorName()
const VectorPostprocessorName & VectorPostprocessorInterface::getVectorPostprocessorName (const std::string & param_name) const inherited
Get the name of a VectorPostprocessor associated with a parameter.
Parameters
param_name The name of the VectorPostprocessor parameter
Returns
The name of the given VectorPostprocessor
Definition at line 203 of file VectorPostprocessorInterface.C.
{
  const auto & params = _vpi_moose_object.parameters();
  if (!params.isParamValid(param_name))
    _vpi_moose_object.mooseError(
        "When getting a VectorPostprocessor, failed to get a parameter with the name \"",
        param_name,
        "\".",
        "\n\nKnown parameters:\n",
        _vpi_moose_object.parameters());
  if (!params.isType<VectorPostprocessorName>(param_name))
    _vpi_moose_object.mooseError(
        "Supplied parameter with name \"",
        param_name,
        "\" of type \"",
        params.type(param_name),
        "\" is not an expected type for getting a VectorPostprocessor.\n\n",
        "The allowed type is \"VectorPostprocessorName\".");
  return params.get<VectorPostprocessorName>(param_name);
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValue(), VectorPostprocessorInterface::getScatterVectorPostprocessorValueOld(), VectorPostprocessorInterface::getVectorPostprocessorValue(), VectorPostprocessorInterface::getVectorPostprocessorValueOld(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::isVectorPostprocessorDistributed(), and VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor().
getVectorPostprocessorValue() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValue (const std::string & param_name, const std::string & vector_name) const inherited
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the value of a VectorPostprocessor
Parameters
param_name The name of the VectorPostprocessor parameter (see below)
vector_name The name of the particular vector you want.
Returns
A reference to the desired value
The name required by this method is the name that is hard-coded into your source code. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this function requires the "pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValueOld getVectorPostprocessorValueByName getVectorPostprocessorValueOldByName
Definition at line 36 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueByName(getVectorPostprocessorName(param_name), vector_name);
}
getVectorPostprocessorValue() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValue (const std::string & param_name, const std::string & vector_name, bool needs_broadcast) const inherited
Retrieve the value of a VectorPostprocessor.
Parameters
param_name The name of the VectorPostprocessor parameter (see below)
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
A reference to the desired value
The name required by this method is the name that is hard-coded into your source code. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this function requires the "pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValueOld getVectorPostprocessorValueByName getVectorPostprocessorValueOldByName
Definition at line 66 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueByName(
      getVectorPostprocessorName(param_name), vector_name, needs_broadcast);
}
getVectorPostprocessorValueByName() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the value of the VectorPostprocessor
Parameters
name VectorPostprocessor name (see below)
vector_name The name of the particular vector you want.
Returns
A reference to the desired value
The name required by this method is the name defined in the input file. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this method requires the "my_pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValue getVectorPostprocessorValueOldByName getVectorPostprocessorValueByName
Definition at line 44 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(name, vector_name, _broadcast_by_default, 0);
}
Referenced by VectorPostprocessorInterface::getVectorPostprocessorValue().
getVectorPostprocessorValueByName() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueByName (const VectorPostprocessorName & name, const std::string & vector_name, bool needs_broadcast) const inherited
Retrieve the value of the VectorPostprocessor.
Parameters
name VectorPostprocessor name (see below)
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
A reference to the desired value
The name required by this method is the name defined in the input file. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this method requires the "my_pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValue getVectorPostprocessorValueOldByName getVectorPostprocessorValueByName
Definition at line 76 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(
      name, vector_name, needs_broadcast || _broadcast_by_default, 0);
}
getVectorPostprocessorValueOld() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOld (const std::string & param_name, const std::string & vector_name) const inherited
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the old value of a VectorPostprocessor
Parameters
param_name The name of the VectorPostprocessor parameter
vector_name The name of the particular vector you want.
Returns
The value of the VectorPostprocessor
see getVectorPostprocessorValue
Definition at line 51 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueOldByName(getVectorPostprocessorName(param_name), vector_name);
}
getVectorPostprocessorValueOld() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOld (const std::string & param_name, const std::string & vector_name, bool needs_broadcast) const inherited
Retrieve the old value of a VectorPostprocessor.
Parameters
param_name The name of the VectorPostprocessor parameter
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
The value of the VectorPostprocessor
see getVectorPostprocessorValue
Definition at line 86 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueOldByName(
      getVectorPostprocessorName(param_name), vector_name, needs_broadcast);
}
getVectorPostprocessorValueOldByName() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOldByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the old value of a VectorPostprocessor
Parameters
name The name of the VectorPostprocessor
vector_name The name of the particular vector you want.
Returns
The value of the VectorPostprocessor
If within the validParams for the object the addVectorPostprocessorParam was called this method will retun a reference to the default value specified in the call to the addVectorPostprocessorParam function if the postVectorPostprocessor does not exist.
see getVectorPostprocessorValueByName
Definition at line 59 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(name, vector_name, _broadcast_by_default, 1);
}
Referenced by VectorPostprocessorInterface::getVectorPostprocessorValueOld().
getVectorPostprocessorValueOldByName() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOldByName (const VectorPostprocessorName & name, const std::string & vector_name, bool needs_broadcast) const inherited
Retrieve the old value of a VectorPostprocessor.
Parameters
name The name of the VectorPostprocessor
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
The value of the VectorPostprocessor
If within the validParams for the object the addVectorPostprocessorParam was called this method will retun a reference to the default value specified in the call to the addVectorPostprocessorParam function if the postVectorPostprocessor does not exist.
see getVectorPostprocessorValueByName
Definition at line 96 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(
      name, vector_name, needs_broadcast || _broadcast_by_default, 1);
}
getVectorTags()
const std::set< TagID > & TaggingInterface::getVectorTags (VectorTagsKey) const inline inherited
Definition at line 93 of file TaggingInterface.h.
{ return _vector_tags; }
hasFunction()
bool FunctionInterface::hasFunction (const std::string & param_name) const inherited
Determine if the function exists.
Parameters
param_name The name of the function parameter
index The index of the function
Returns
True if the function exists
Definition at line 42 of file FunctionInterface.C.
{
  return hasFunctionByName(_fni_params.get<FunctionName>(param_name));
}
hasFunctionByName()
bool FunctionInterface::hasFunctionByName (const FunctionName & name) const inherited
Determine if the function exists.
Parameters
name The name of the function
Returns
True if the function exists
Definition at line 48 of file FunctionInterface.C.
{
  return _fni_feproblem.hasFunction(name, _fni_tid);
}
Referenced by FunctionInterface::hasFunction().
hasPostprocessor()
bool PostprocessorInterface::hasPostprocessor (const std::string & param_name, const unsigned int index = 0) const inherited
Determine if the Postprocessor data exists.
Parameters
param_name The name of the Postprocessor parameter
index The index of the Postprocessor
Returns
True if the Postprocessor exists
See also
hasPostprocessorByName getPostprocessorValue
Definition at line 107 of file PostprocessorInterface.C.
{
  if (!postprocessorsAdded())
    _ppi_moose_object.mooseError(
        "Cannot call hasPostprocessor() until all Postprocessors have been constructed.");
  return hasPostprocessorByName(getPostprocessorNameInternal(param_name, index));
}
hasPostprocessorByName()
bool PostprocessorInterface::hasPostprocessorByName (const PostprocessorName & name) const inherited
Determine if the Postprocessor data exists.
Parameters
name The name of the Postprocessor
Returns
True if the Postprocessor exists
See also
hasPostprocessor getPostprocessorValueByName
Definition at line 118 of file PostprocessorInterface.C.
{
  if (!postprocessorsAdded())
    _ppi_moose_object.mooseError(
        "Cannot call hasPostprocessorByName() until all Postprocessors have been constructed.");
  return _ppi_feproblem.getReporterData().hasReporterValue<PostprocessorValue>(
      PostprocessorReporterName(name));
}
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), AdvancedOutput::initShowHideLists(), Exodus::outputReporters(), and TableOutput::outputReporters().
hasUserObject() [1/2]
bool UserObjectInterface::hasUserObject (const std::string & param_name) const inherited
Returns
Whether or not a UserObject exists with the name given by the parameter param_name.
Definition at line 67 of file UserObjectInterface.C.
{
  return hasUserObjectByName(getUserObjectName(param_name));
}
hasUserObject() [2/2]
template<class T > bool UserObjectInterface::hasUserObject (const std::string & param_name) const inherited
Definition at line 175 of file UserObjectInterface.h.
{
  return hasUserObjectByName<T>(getUserObjectName(param_name));
}
hasUserObjectByName() [1/2]
bool UserObjectInterface::hasUserObjectByName (const UserObjectName & object_name) const inherited
Definition at line 73 of file UserObjectInterface.C.
{
  return _uoi_feproblem.hasUserObject(object_name);
}
Referenced by UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::hasUserObject(), and UserObjectInterface::hasUserObjectByName().
hasUserObjectByName() [2/2]
template<class T > bool UserObjectInterface::hasUserObjectByName (const UserObjectName & object_name) const inherited
Definition at line 182 of file UserObjectInterface.h.
{
  if (!hasUserObjectByName(object_name))
    return false;
  return dynamic_cast<const T *>(&_uoi_feproblem.getUserObjectBase(object_name));
}
hasVectorPostprocessor() [1/2]
bool VectorPostprocessorInterface::hasVectorPostprocessor (const std::string & param_name) const inherited
Determine if the VectorPostprocessor exists by parameter.
Parameters
name The name of the VectorPostprocessor parameter
Returns
True if the VectorPostprocessor exists
Definition at line 168 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessor() until all "
                              "VectorPostprocessors have been constructed.");
  return hasVectorPostprocessorByName(getVectorPostprocessorName(param_name));
}
hasVectorPostprocessor() [2/2]
bool VectorPostprocessorInterface::hasVectorPostprocessor (const std::string & param_name, const std::string & vector_name) const inherited
Determine if the VectorPostprocessor data exists by parameter.
Parameters
param_name The name of the VectorPostprocessor parameter
vector_name The vector name within the VectorPostprocessor
Returns
True if the VectorPostprocessor data exists
See also
hasVectorPostprocessorByName getVectorPostprocessorValue
Definition at line 138 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessor() until all VectorPostprocessors "
                              "have been constructed.");
  return hasVectorPostprocessorByName(getVectorPostprocessorName(param_name), vector_name);
}
Referenced by VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor().
hasVectorPostprocessorByName() [1/2]
bool VectorPostprocessorInterface::hasVectorPostprocessorByName (const VectorPostprocessorName & name) const inherited
Determine if the VectorPostprocessor exists by name.
Parameters
name The name of the VectorPostprocessor
Returns
True if the VectorPostprocessor exists
Definition at line 178 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessorByName() until all "
                              "VectorPostprocessors have been constructed.");
  return _vpi_feproblem.hasUserObject(name) &&
         dynamic_cast<const VectorPostprocessor *>(&_vpi_feproblem.getUserObjectBase(name));
}
hasVectorPostprocessorByName() [2/2]
bool VectorPostprocessorInterface::hasVectorPostprocessorByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
Determine if the VectorPostprocessor data exists by name.
Parameters
name The name of the VectorPostprocessor
vector_name The vector name within the VectorPostprocessor
Returns
True if the VectorPostprocessor data exists
See also
hasVectorPostprocessor getVectorPostprocessorValueByName
Definition at line 149 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessorByName() until all "
                              "VectorPostprocessors have been constructed.");
  const bool has_vpp = _vpi_feproblem.getReporterData().hasReporterValue<VectorPostprocessorValue>(
      VectorPostprocessorReporterName(name, vector_name));
  if (has_vpp)
    mooseAssert(_vpi_feproblem.hasUserObject(name) && dynamic_cast<const VectorPostprocessor *>(
                                                          &_vpi_feproblem.getUserObjectBase(name)),
                "Has reporter VectorPostprocessor Reporter value but not VectorPostprocessor UO");
  return has_vpp;
}
Referenced by VectorPostprocessorInterface::hasVectorPostprocessor(), AdvancedOutput::initShowHideLists(), CSV::output(), and VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName().
initialSetup()
void SetupInterface::initialSetup () virtual inherited
Gets called at the beginning of the simulation before this object is asked to do its job.
Reimplemented in DerivativeSumMaterialTempl< is_ad >, AdvancedOutput, MultiAppFieldTransfer, Transfer, MortarNodalAuxKernelTempl< ComputeValueType >, ProjectedStatefulMaterialAuxTempl< T, is_ad >, SolutionAux, SolutionScalarAux, TimePeriod, Axisymmetric2D3DSolutionFunction, CoarsenedPiecewiseLinear, ImageFunction, MooseParsedFunction, MooseParsedGradFunction, MooseParsedVectorFunction, PiecewiseConstantFromCSV, PiecewiseLinear, PiecewiseLinearBase, PiecewiseTabularBase, SolutionFunction, LibtorchControlValuePostprocessor, LibtorchArtificialNeuralNetParameters, DerivativeFunctionMaterialBaseTempl< is_ad >, DerivativeFunctionMaterialBaseTempl< is_ad >, FullSolveMultiApp, MultiApp, TransientMultiApp, Console, CSV, Exodus, Nemesis, OversampleOutput, NodalVariableValue, SideIntegralMaterialPropertyTempl< is_ad >, MultiAppCloneReporterTransfer, MultiAppConservativeTransfer, MultiAppDofCopyTransfer, MultiAppGeneralFieldNearestLocationTransfer, MultiAppGeneralFieldTransfer, MultiAppProjectionTransfer, MultiAppReporterTransfer, MultiAppTransfer, MultiAppVariableValueSamplePostprocessorTransfer, MultiAppVariableValueSampleTransfer, ElementSubdomainModifier, GhostingUserObject, InterfaceQpUserObjectBase, NodalPatchRecoveryMaterialProperty, ProjectedStatefulMaterialNodalPatchRecoveryTempl< T, is_ad >, RadialAverage, SolutionUserObject, Terminator, MooseVariableBase, HistogramVectorPostprocessor, and DGFunctionTemperatureAdvection.
Definition at line 40 of file SetupInterface.C.
{
}
Referenced by LibtorchControlValuePostprocessor::initialSetup(), Console::initialSetup(), CSV::initialSetup(), and Positions::meshChanged().
isActive()
virtual bool ScalarKernelBase::isActive () inline virtual inherited
Use this to enable/disable the scalar kernel.
Returns
true if the scalar kernel is active
Definition at line 40 of file ScalarKernelBase.h.
{ return true; }
isCoupledScalar()
bool ScalarCoupleable::isCoupledScalar (const std::string & var_name, unsigned int i = 0) const protected inherited
Returns true if a variables has been coupled_as name.
Parameters
var_name The of the coupled variable
i By default 0, in general the index to test in a vector of MooseVariable pointers.
Definition at line 70 of file ScalarCoupleable.C.
{
  const auto var_name = _sc_parameters.checkForRename(var_name_in);
  auto it = _coupled_scalar_vars.find(var_name);
  if (it != _coupled_scalar_vars.end())
    return (i < it->second.size());
  else
  {
    // Make sure the user originally requested this value in the InputParameter syntax
    if (!_sc_parameters.hasCoupledValue(var_name))
      mooseError(_sc_name,
                 ": The coupled scalar variable \"",
                 var_name,
                 "\" was never added to this object's "
                 "InputParameters, please double-check "
                 "your spelling");
    return false;
  }
}
Referenced by ScalarCoupleable::adCoupledScalarValue(), Product1BodyScalar::computeQpJacobian(), Product2BodyScalar::computeQpJacobian(), Product3BodyScalar::computeQpJacobian(), EnergyTermScalar::computeQpOffDiagJacobian(), Reactant3BodyScalar::computeQpOffDiagJacobian(), EnergyTermScalar::computeQpResidual(), ScalarLinearInterpolation::computeValue(), ScalarSplineInterpolation::computeValue(), SuperelasticRateCoefficientScalar::computeValue(), ScalarCoupleable::coupledMatrixTagScalarValue(), ScalarCoupleable::coupledScalarOrder(), ScalarCoupleable::coupledScalarValue(), ScalarCoupleable::coupledScalarValueOld(), ScalarCoupleable::coupledScalarValueOlder(), and ScalarCoupleable::coupledVectorTagScalarValue().
isDefaultPostprocessorValue()
bool PostprocessorInterface::isDefaultPostprocessorValue (const std::string & param_name, const unsigned int index = 0) const inherited
Determine whether or not the Postprocessor is a default value.
A default value is when the value is either the value set by addParam, or is a user-set value in input instead of a name to a postprocessor.
Parameters
param_name The name of the Postprocessor parameter
index The index of the postprocessor
Returns
True if the Postprocessor is a default value, false if the Postprocessor is the name of a Postprocessor
Definition at line 75 of file PostprocessorInterface.C.
{
  return isDefaultPostprocessorValueByName(getPostprocessorNameInternal(param_name, index));
}
Referenced by EigenKernel::EigenKernel().
isDefaultPostprocessorValueByName()
bool PostprocessorInterface::isDefaultPostprocessorValueByName (const PostprocessorName & name) const private inherited
Returns
True if the PostprocessorName name repesents a default value: the name converts to a value (set by addParam or set via input), and a Postprocessor does not exist with the same name (we do allow Postprocessors with numbered names...)
Definition at line 82 of file PostprocessorInterface.C.
{
  // We do allow actual Postprocessor objects to have names that will succeed in being
  // represented as a double... so if the name does actually exist as a PP, it's not a default
  if (_ppi_feproblem.getReporterData().hasReporterValue<PostprocessorValue>(
          PostprocessorReporterName(name)))
    return false;
  std::istringstream ss(name);
  Real real_value = -std::numeric_limits<Real>::max();
  return (ss >> real_value && ss.eof());
}
Referenced by PostprocessorInterface::getDefaultPostprocessorValueByName(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), and PostprocessorInterface::isDefaultPostprocessorValue().
isImplicit()
bool TransientInterface::isImplicit () inline inherited
Definition at line 38 of file TransientInterface.h.
{ return _is_implicit; }
Referenced by ComputeJacobianThread::compute().
isMatrixTagged()
bool TaggingInterface::isMatrixTagged () inline inherited
Definition at line 91 of file TaggingInterface.h.
{ return _matrix_tags.size() > 0; }
isNodal()
bool RandomInterface::isNodal () const inline inherited
Definition at line 67 of file RandomInterface.h.
{ return _is_nodal; }
Referenced by ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementValueSampler::ElementValueSampler(), and NodalValueSampler::NodalValueSampler().
isParamSetByUser()
bool MooseBaseParameterInterface::isParamSetByUser (const std::string & nm) const inline inherited
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
Parameters
nm The name of the parameter to test
Definition at line 108 of file MooseBaseParameterInterface.h.
{ return _pars.isParamSetByUser(nm); }
Referenced by SetAdaptivityOptionsAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), LibtorchNeuralNetControl::conditionalParameterError(), MooseBaseParameterInterface::getRenamedParam(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), PiecewiseTabularBase::PiecewiseTabularBase(), MooseMesh::prepare(), and SolutionUserObject::readXda().
isParamValid()
bool MooseBaseParameterInterface::isParamValid (const std::string & name) const inline inherited
Test if the supplied parameter is valid.
Parameters
name The name of the parameter to test
Definition at line 102 of file MooseBaseParameterInterface.h.
{ return _pars.isParamValid(name); }
Referenced by AddDriftDiffusionAction::act(), AddSpecies::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CopyNodalVarsAction::act(), CreateDisplacedProblemAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), AddGeneralReactions::AddGeneralReactions(), AddZapdosReactions::AddZapdosReactions(), AdvectiveFluxAux::AdvectiveFluxAux(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), GeneratedMesh::buildMesh(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), ChemicalReactionsBase::ChemicalReactionsBase(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), CombinerGenerator::CombinerGenerator(), CSVReader::CSVReader(), ConstantReporter::declareConstantReporterValues(), DGKernelBase::DGKernelBase(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EEDFEnergyTownsendLog::EEDFEnergyTownsendLog(), Eigenvalue::Eigenvalue(), ElectronEnergyTermRate::ElectronEnergyTermRate(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), PIDTransientControl::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FileOutput::FileOutput(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FunctionDT::FunctionDT(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getRenamedParam(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), Terminator::handleMessage(), HeavySpeciesTempl< is_ad >::HeavySpeciesTempl(), HFEMDirichletBC::HFEMDirichletBC(), EigenExecutionerBase::init(), Eigenvalue::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), MooseParsedFunction::initialSetup(), MooseParsedGradFunction::initialSetup(), MooseParsedVectorFunction::initialSetup(), PiecewiseTabularBase::initialSetup(), SolutionFunction::initialSetup(), Console::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), IterationAdaptiveDT::IterationAdaptiveDT(), LeastSquaresFit::LeastSquaresFit(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MatCoupledForce::MatCoupledForce(), MooseMesh::MooseMesh(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarConsumerInterface::MortarConsumerInterface(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalExtremeValue::NodalExtremeValue(), EigenExecutionerBase::normalizeSolution(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PetscOutput::PetscOutput(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), PicardSolve::PicardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseTabularBase::PiecewiseTabularBase(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), MooseMesh::prepare(), MultiApp::readCommandLineArguments(), SolutionUserObject::readExodusII(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), MooseMesh::setCoordSystem(), FileOutput::setFileBase(), FileOutput::setFileBaseInternal(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SideDiffusiveFluxIntegralTempl< is_ad, T >::SideDiffusiveFluxIntegralTempl(), SideExtremeValue::SideExtremeValue(), SolutionUserObject::SolutionUserObject(), Terminator::Terminator(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), MultiAppDofCopyTransfer::transfer(), TransformGenerator::TransformGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
isVectorPostprocessorDistributed()
bool VectorPostprocessorInterface::isVectorPostprocessorDistributed (const std::string & param_name) const inherited
Return true if the VectorPostprocessor is marked with parallel_type as DISTRIBUTED.
Definition at line 190 of file VectorPostprocessorInterface.C.
{
  return isVectorPostprocessorDistributedByName(getVectorPostprocessorName(param_name));
}
isVectorPostprocessorDistributedByName()
bool VectorPostprocessorInterface::isVectorPostprocessorDistributedByName (const VectorPostprocessorName & name) const inherited
Definition at line 196 of file VectorPostprocessorInterface.C.
{
  return _vpi_feproblem.getVectorPostprocessorObjectByName(name).isDistributed();
}
Referenced by VectorPostprocessorInterface::isVectorPostprocessorDistributed().
isVectorTagged()
bool TaggingInterface::isVectorTagged () inline inherited
Definition at line 89 of file TaggingInterface.h.
{ return _vector_tags.size() > 0; }
jacobianSetup()
void SetupInterface::jacobianSetup () virtual inherited
Gets called just before the Jacobian is computed and before this object is asked to do its job.
Reimplemented in EqualValueEmbeddedConstraint, Function, ADKernelTempl< T >, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 50 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::jacobianSetup(), and ComputeFVFluxJacobianThread< RangeType >::setup().
meshChanged()
virtual void MeshChangedInterface::meshChanged () inline virtual inherited
Called on this object when the mesh changes.
Reimplemented in GeometryBase, EqualValueBoundaryConstraint, DiracKernelBase, FVPointValueConstraint, MeshDivision, Console, Exodus, Nemesis, OversampleOutput, Positions, ExplicitTimeIntegrator, MultiAppVariableValueSamplePostprocessorTransfer, GhostingUserObject, NearestNodeNumberUO, RadialAverage, MooseVariableDataFV< OutputType >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 34 of file MeshChangedInterface.h.
{}
Referenced by MooseVariableFE< OutputType >::meshChanged(), and MooseVariableFV< OutputType >::meshChanged().
mooseDeprecated()
template<typename... Args> void MooseBaseErrorInterface::mooseDeprecated (Args &&... args) const inline inherited
Definition at line 78 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseDeprecatedStream(_console, false, true, std::forward<Args>(args)...);
  }
Referenced by FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::advanceMultiApps(), MultiApp::appProblem(), Executioner::augmentedPicardConvergenceCheck(), MooseMesh::buildSideList(), FEProblemBase::computeResidual(), AddVariableAction::determineType(), Eigenvalue::Eigenvalue(), MooseMesh::elem(), FunctionDT::FunctionDT(), RandomICBase::generateRandom(), MooseMesh::getBoundariesToElems(), Control::getExecuteOptions(), FEProblemBase::getNonlinearSystem(), FEProblemBase::getUserObjects(), FEProblemBase::hasPostprocessor(), MooseMesh::node(), FixedPointSolve::numPicardIts(), RelationshipManager::operator>=(), Executioner::picardSolve(), and MooseMesh::setBoundaryToNormalMap().
mooseError()
template<typename... Args> void MooseBaseErrorInterface::mooseError (Args &&... args) const inline inherited
Emits an error prefixed with object name and type.
Definition at line 38 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, errorPrefix("error"), std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
Referenced by HierarchicalGridPartitioner::_do_partition(), PetscExternalPartitioner::_do_partition(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AdaptivityAction::act(), AddFVICAction::act(), AddICAction::act(), AddMeshGeneratorAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVectorPostprocessorAction::act(), CheckFVBCAction::act(), CheckIntegrityAction::act(), CommonOutputAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DeprecatedBlockAction::act(), InitProblemAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetAdaptivityOptionsAction::act(), SetupMeshAction::act(), SetupMeshCompleteAction::act(), SetupPredictorAction::act(), SetupTimeStepperAction::act(), SplitMeshAction::act(), FEProblemBase::adaptMesh(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::addConstraint(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFVInitialCondition(), AddGeneralReactions::AddGeneralReactions(), FEProblemBase::addInitialCondition(), FEProblemBase::addLineSearch(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addOutput(), SubProblem::addPiecewiseByBlockLambdaFunctor(), DistributedRectilinearMeshGenerator::addPoint(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), FEProblemBase::addPostprocessor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseMesh::addQuadratureNode(), FEProblemBase::addReporter(), AddVariableAction::addVariable(), FEProblemBase::addVectorPostprocessor(), SubProblem::addVectorTag(), AddZapdosReactions::AddZapdosReactions(), ADEEDFRateConstantTownsend::ADEEDFRateConstantTownsend(), ADGasElectronMoments::ADGasElectronMoments(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), MooseVariableScalar::adUDot(), Output::advancedExecuteOn(), AdvectiveFluxAux::AdvectiveFluxAux(), ADZapdosEEDFRateConstant::ADZapdosEEDFRateConstant(), MooseVariableBase::allDofIndices(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayConstantIC::ArrayConstantIC(), ArrayFunctionIC::ArrayFunctionIC(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), Function::average(), Axisymmetric2D3DSolutionFunction::Axisymmetric2D3DSolutionFunction(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), BoltzmannSolverScalar::BoltzmannSolverScalar(), BoundingValueElementDamper::BoundingValueElementDamper(), BoundingValueNodalDamper::BoundingValueNodalDamper(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), MooseMesh::buildCoarseningMap(), MultiApp::buildComm(), DistributedRectilinearMeshGenerator::buildCube(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), PiecewiseTabularBase::buildFromXY(), MooseMesh::buildLowerDMesh(), GeneratedMesh::buildMesh(), MeshGeneratorMesh::buildMesh(), SpiralAnnularMesh::buildMesh(), TiledMesh::buildMesh(), ImageMesh::buildMesh3D(), ImageMeshGenerator::buildMesh3D(), MooseMesh::buildRefinementMap(), MaterialBase::buildRequiredMaterials(), MooseMesh::buildSideList(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), UserObjectInterface::castUserObject(), EigenExecutionerBase::chebyshev(), SubProblem::checkBlockMatProps(), SubProblem::checkBoundaryMatProps(), MooseMesh::checkCoordinateSystems(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkDisplacementOrders(), FEProblemBase::checkDuplicatePostprocessorVariableNames(), MooseMesh::checkDuplicateSubdomainNames(), MaterialBase::checkExecutionStage(), MeshGenerator::checkGetMesh(), ReporterTransferInterface::checkHasReporterValue(), FEProblemBase::checkICRestartError(), EigenExecutionerBase::checkIntegrity(), Eigenvalue::checkIntegrity(), Steady::checkIntegrity(), ExplicitTimeIntegrator::checkLinearConvergence(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), PostprocessorInterface::checkParam(), FEProblemBase::checkProblemIntegrity(), Sampler::checkReinitStatus(), MaterialBase::checkStatefulSanity(), FEProblemBase::checkUserObjects(), MultiAppTransfer::checkVariable(), DomainUserObject::checkVariable(), ChemicalReactionsBase::ChemicalReactionsBase(), MooseMesh::clone(), LibmeshPartitioner::clone(), CombinerGenerator::CombinerGenerator(), ElementSubdomainModifier::complementMovingBoundaryID(), ElementSubdomainModifier::complementMovingBoundaryName(), MooseVariableFieldBase::componentName(), CompositeFunction::CompositeFunction(), NodalPatchRecovery::compute(), VariableCondensationPreconditioner::computeDInverseDiag(), CompositionDT::computeDT(), MooseVariableFieldBase::computeFaceValues(), TimeStepper::computeFailedDT(), IterationAdaptiveDT::computeFailedDT(), TimeSequenceStepperBase::computeFailedDT(), MooseMesh::computeFiniteVolumeCoords(), FVFluxKernel::computeJacobian(), ArrayKernel::computeJacobian(), ArrayKernel::computeOffDiagJacobian(), FVElementalKernel::computeOffDiagJacobian(), MaterialBase::computeProperties(), ScalarKernel::computeQpJacobian(), ScalarKernel::computeQpResidual(), FVFluxKernel::computeResidual(), ArrayKernel::computeResidual(), FVFluxBC::computeResidual(), ResidualObject::computeResidualAndJacobian(), FVFluxKernel::computeResidualAndJacobian(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualL2Norm(), FEProblemBase::computeResidualTag(), FEProblemBase::computeResidualType(), TimeStepper::computeStep(), ActuallyExplicitEuler::computeTimeDerivatives(), AStableDirk4::computeTimeDerivatives(), BDF2::computeTimeDerivatives(), CrankNicolson::computeTimeDerivatives(), ExplicitEuler::computeTimeDerivatives(), ExplicitRK2::computeTimeDerivatives(), ExplicitTVDRK2::computeTimeDerivatives(), ImplicitEuler::computeTimeDerivatives(), ImplicitMidpoint::computeTimeDerivatives(), LStableDirk2::computeTimeDerivatives(), LStableDirk3::computeTimeDerivatives(), LStableDirk4::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), FEProblemBase::computeUserObjectsInternal(), BolsigValueScalar::computeValue(), PenetrationAux::computeValue(), BuildArrayVariableAux::computeValue(), TagVectorArrayVariableAux::computeValue(), ConcentricCircleMesh::ConcentricCircleMesh(), ConditionalEnableControl::ConditionalEnableControl(), TimeStepper::constrainStep(), LibtorchNeuralNetControl::controlNeuralNet(), AddVariableAction::createInitialConditionAction(), DataRead::DataRead(), ReporterTransferInterface::declareClone(), MeshGenerator::declareMeshProperty(), ReporterTransferInterface::declareVectorClone(), FunctorRelationshipManager::delete_remote_elements(), MooseMesh::deleteRemoteElements(), BicubicSplineFunction::derivative(), MooseMesh::detectPairedSidesets(), FEProblemBase::determineNonlinearSystem(), MeshDiagnosticsGenerator::diagnosticsLog(), DiffusionRateTemp::DiffusionRateTemp(), FunctorBinnedValuesDivision::divisionIndex(), FunctorRelationshipManager::dofmap_reinit(), FEProblemBase::duplicateVariableCheck(), EEDFRateConstant::EEDFRateConstant(), EEDFRateConstantTownsend::EEDFRateConstantTownsend(), Eigenvalue::Eigenvalue(), ElectricField::ElectricField(), ElectronMobility::ElectronMobility(), ElementIntegerAux::ElementIntegerAux(), ElementQualityAux::ElementQualityAux(), ElementUOAux::ElementUOAux(), DistributedRectilinearMeshGenerator::elemId(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), MooseMesh::errorIfDistributedMesh(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), BoltzmannSolverScalar::execute(), Eigenvalue::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), ElementQualityChecker::execute(), DiscreteElementUserObject::execute(), DomainUserObject::execute(), FEProblemBase::execute(), FEProblemBase::executeControls(), MultiAppVectorPostprocessorTransfer::executeFromMultiapp(), MultiAppVectorPostprocessorTransfer::executeToMultiapp(), ExplicitSSPRungeKutta::ExplicitSSPRungeKutta(), FileOutput::FileOutput(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), ElementQualityChecker::finalize(), VerifyElementUniqueID::finalize(), VerifyNodalUniqueID::finalize(), DiscreteElementUserObject::finalize(), Transfer::find_sys(), BreakMeshByBlockGeneratorBase::findFreeBoundaryId(), FunctionDT::FunctionDT(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), GapValueAux::GapValueAux(), Gas::Gas(), GasBase::GasBase(), GasElectronMoments::GasElectronMoments(), AllSideSetsByNormalsGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundingBoxNodeSetGenerator::generate(), BreakMeshByBlockGenerator::generate(), CombinerGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshCollectionGenerator::generate(), MeshDiagnosticsGenerator::generate(), MeshExtruderGenerator::generate(), MeshRepairGenerator::generate(), MoveNodeGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), SideSetsFromNormalsGenerator::generate(), SideSetsFromPointsGenerator::generate(), SmoothMeshGenerator::generate(), SpiralAnnularMeshGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), TiledMeshGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GeneratedMesh::GeneratedMesh(), GeneratedMeshGenerator::GeneratedMeshGenerator(), MeshGenerator::generateInternal(), CircularBoundaryCorrectionGenerator::generateRadialCorrectionFactor(), RandomICBase::generateRandom(), GenericConstantMaterialTempl< is_ad >::GenericConstantMaterialTempl(), GenericConstantVectorMaterialTempl< is_ad >::GenericConstantVectorMaterialTempl(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), DisplacedProblem::getActualFieldVariable(), FEProblemBase::getActualFieldVariable(), DisplacedProblem::getArrayVariable(), FEProblemBase::getArrayVariable(), MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::getBlockConnectedBlocks(), VariableOldValueBoundsAux::getBound(), MooseMesh::getBoundaryID(), MultiApp::getBoundingBox(), MooseMesh::getCoarseningMap(), MooseVariableBase::getContinuity(), Control::getControllableParameterByName(), MooseMesh::getCoordSystem(), PropertyReadFile::getData(), TransfiniteMeshGenerator::getDiscreteEdge(), FEProblemBase::getDistribution(), MooseVariableBase::getDofIndices(), VariableCondensationPreconditioner::getDofToCondense(), TransfiniteMeshGenerator::getEdge(), GhostingUserObject::getElementalValue(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), PropertyReadFile::getElementData(), MooseMesh::getElementIDIndex(), Material::getElementIDNeighbor(), Material::getElementIDNeighborByName(), MooseMesh::getElemIDMapping(), MooseMesh::getElemIDsOnBlocks(), MultiAppFieldTransfer::getEquationSystem(), MultiApp::getExecutioner(), MultiAppTransfer::getFromMultiApp(), MultiAppTransfer::getFromMultiAppInfo(), FEProblemBase::getFunction(), SubProblem::getFunctor(), MooseMesh::getGeneralAxisymmetricCoordAxis(), DistributedRectilinearMeshGenerator::getGhostNeighbors(), BatchMaterial< Tuple, Output, Input >::getIndex(), DistributedRectilinearMeshGenerator::getIndices(), SolutionUserObject::getLocalVarIndex(), Material::getMaterialByName(), FEProblemBase::getMaterialData(), SubProblem::getMatrixTagID(), AnnularMesh::getMaxInDimension(), GeneratedMesh::getMaxInDimension(), FEProblemBase::getMaxQps(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), AnnularMesh::getMinInDimension(), GeneratedMesh::getMinInDimension(), MultiAppTransfer::getMultiApp(), DistributedRectilinearMeshGenerator::getNeighbors(), MooseMesh::getNodeBlockIds(), PropertyReadFile::getNodeData(), MooseMesh::getNodeList(), FEProblemBase::getNonlinearSystem(), MooseMesh::getPairedBoundaryMapping(), ImageMesh::GetPixelInfo(), ImageMeshGenerator::GetPixelInfo(), PlaneIDMeshGenerator::getPlaneID(), FEProblemBase::getPositionsObject(), PostprocessorInterface::getPostprocessorValueByNameInternal(), MooseMesh::getRefinementMap(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), FEProblemBase::getSampler(), JSONFileReader::getScalar(), DisplacedProblem::getScalarVariable(), FEProblemBase::getScalarVariable(), DisplacedProblem::getStandardVariable(), FEProblemBase::getStandardVariable(), MooseMesh::getSubdomainBoundaryIds(), DisplacedProblem::getSystem(), FEProblemBase::getSystem(), FEProblemBase::getTimeFromStateArg(), Transient::getTimeIntegratorName(), MultiAppTransfer::getToMultiApp(), MultiAppTransfer::getToMultiAppInfo(), MooseMesh::getUniqueCoordSystem(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::getUserObjectName(), JSONFileReader::getVector(), VectorPostprocessorInterface::getVectorPostprocessorName(), SubProblem::getVectorTag(), SubProblem::getVectorTagID(), DisplacedProblem::getVectorVariable(), FEProblemBase::getVectorVariable(), GhostingAux::GhostingAux(), MultiApp::globalAppToLocal(), Function::gradient(), MooseParsedVectorFunction::gradient(), Terminator::handleMessage(), MooseVariableBase::hasDoFsOnNodes(), PostprocessorInterface::hasPostprocessor(), PostprocessorInterface::hasPostprocessorByName(), ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), AddVariableAction::init(), MooseMesh::init(), Sampler::init(), AddAuxVariableAction::init(), EigenExecutionerBase::init(), Eigenvalue::init(), Transient::init(), FEProblemBase::init(), CrankNicolson::init(), ExplicitTimeIntegrator::init(), CSVTimeSequenceStepper::init(), IterationAdaptiveDT::init(), MultiApp::init(), FEProblemBase::initialAdaptMesh(), BoltzmannSolverScalar::initialize(), PolynomialCoefficients::initialize(), CartesianGridDivision::initialize(), CylindricalGridDivision::initialize(), NestedDivision::initialize(), SphericalGridDivision::initialize(), SubProblem::initialSetup(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), Axisymmetric2D3DSolutionFunction::initialSetup(), MooseParsedFunction::initialSetup(), SolutionFunction::initialSetup(), SolutionIC::initialSetup(), FullSolveMultiApp::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), SolutionUserObject::initialSetup(), Function::integral(), InterpolatedCoefficientLinear::InterpolatedCoefficientLinear(), InterpolatedCoefficientSpline::InterpolatedCoefficientSpline(), EigenExecutionerBase::inversePowerIteration(), InversePowerMethod::InversePowerMethod(), Sampler::isAdaptiveSamplingCompleted(), MooseMesh::isBoundaryFullyExternalToSubdomains(), MooseVariableBase::isNodal(), IterationAdaptiveDT::IterationAdaptiveDT(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LineSearch::lineSearch(), ReporterPointMarker::markerSetup(), Material::Material(), MaterialOutputAction::materialOutputHelper(), MaterialRealTensorValueAux::MaterialRealTensorValueAux(), MaterialRealVectorValueAuxTempl< is_ad >::MaterialRealVectorValueAuxTempl(), Distribution::median(), FunctorRelationshipManager::mesh_reinit(), SubProblem::meshChanged(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshExtruderGenerator::MeshExtruderGenerator(), MeshRepairGenerator::MeshRepairGenerator(), SetupMeshAction::modifyParamsForUseSplit(), MeshMetaDataInterface::mooseErrorInternal(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MoveNodeGenerator::MoveNodeGenerator(), ElementSubdomainModifier::movingBoundaryID(), ElementSubdomainModifier::movingBoundaryName(), MultiApp::MultiApp(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NearestNodeDistanceAux::NearestNodeDistanceAux(), NearestNodeValueAux::NearestNodeValueAux(), FEProblemBase::needsPreviousNewtonIteration(), NewmarkBeta::NewmarkBeta(), NodalPatchRecoveryBase::nodalPatchRecovery(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), DistributedRectilinearMeshGenerator::nodeId(), DistributedRectilinearMeshGenerator::numNeighbors(), Output::onInterval(), FunctorRelationshipManager::operator()(), RelationshipManager::operator==(), MortarNodalGeometryOutput::output(), Output::Output(), DistributedRectilinearMeshGenerator::paritionSquarely(), PiecewiseBilinear::parse(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), ExplicitTimeIntegrator::performExplicitSolve(), PetscExternalPartitioner::PetscExternalPartitioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), Executioner::picardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseMulticonstant::PiecewiseMulticonstant(), PiecewiseTabularBase::PiecewiseTabularBase(), SolutionUserObject::pointValueGradientWrapper(), SolutionUserObject::pointValueWrapper(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName(), AStableDirk4::postResidual(), ExplicitRK2::postResidual(), ExplicitTVDRK2::postResidual(), ImplicitMidpoint::postResidual(), LStableDirk2::postResidual(), LStableDirk3::postResidual(), LStableDirk4::postResidual(), VariableCondensationPreconditioner::preallocateCondensedJacobian(), Predictor::Predictor(), Transient::preExecute(), MooseMesh::prepare(), MooseMesh::prepared(), FixedPointSolve::printFixedPointConvergenceReason(), RateCoefficientProvider::RateCoefficientProvider(), RateCoefficientProvider::reaction_coefficient(), RateCoefficientProvider::reaction_coefficient_derivative(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readExodusII(), SolutionUserObject::readXda(), FunctorRelationshipManager::redistribute(), Sampler::reinit(), RinglebMesh::RinglebMesh(), RinglebMeshGenerator::RinglebMeshGenerator(), PiecewiseMultiInterpolation::sample(), ScalarComponentIC::ScalarComponentIC(), ScalarLinearInterpolation::ScalarLinearInterpolation(), ScalarSplineInterpolation::ScalarSplineInterpolation(), DistributedRectilinearMeshGenerator::scaleNodalPositions(), BicubicSplineFunction::secondDerivative(), FunctorRelationshipManager::set_mesh(), MooseVariableBase::setActiveTags(), DistributedRectilinearMeshGenerator::setBoundaryNames(), MooseMesh::setCoordSystem(), FEProblemBase::setCoupling(), PiecewiseBase::setData(), FileOutput::setFileBaseInternal(), MooseMesh::setGeneralAxisymmetricCoordAxes(), FEProblemSolve::setInnerSolve(), MeshGenerator::setMeshProperty(), FEProblemBase::setNonlocalCouplingMatrix(), Sampler::setNumberOfCols(), Sampler::setNumberOfRandomSeeds(), Sampler::setNumberOfRows(), Split::setup(), TransientMultiApp::setupApp(), SetupMeshAction::setupMesh(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), TimePeriodBase::setupTimes(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SideSetsFromNormalsGenerator::SideSetsFromNormalsGenerator(), SideSetsFromPointsGenerator::SideSetsFromPointsGenerator(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), SolutionTimeAdaptiveDT::SolutionTimeAdaptiveDT(), SolutionUserObject::SolutionUserObject(), FullSolveMultiApp::solveStep(), UserObject::spatialPoints(), UserObject::spatialValue(), SpiralAnnularMesh::SpiralAnnularMesh(), SpiralAnnularMeshGenerator::SpiralAnnularMeshGenerator(), StitchedMesh::StitchedMesh(), MaterialBase::subdomainSetup(), GeneralUserObject::subdomainSetup(), NodalUserObject::subdomainSetup(), Constraint::subdomainSetup(), SuperelasticReactionRate::SuperelasticReactionRate(), FEProblemBase::swapBackMaterialsNeighbor(), Terminator::Terminator(), GeneralUserObject::threadJoin(), ThreadedGeneralUserObject::threadJoin(), DiscreteElementUserObject::threadJoin(), TimePeriodBase::TimePeriodBase(), VectorPostprocessorVisualizationAux::timestepSetup(), FEProblemBase::trustUserCouplingMatrix(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), FEProblemBase::uDotDotOldRequested(), MooseVariableScalar::uDotOld(), FEProblemBase::uDotOldRequested(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), SolutionUserObject::updateExodusBracketingTimeIndices(), FEProblemBase::updateMaxQps(), BoundingBoxIC::value(), Function::value(), Axisymmetric2D3DSolutionFunction::value(), PiecewiseConstantFromCSV::value(), ValueProvider::ValueProvider(), ValueRangeMarker::ValueRangeMarker(), ValueThresholdMarker::ValueThresholdMarker(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), MultiAppTransfer::variableIntegrityCheck(), VariableTimeIntegrationAux::VariableTimeIntegrationAux(), AddVariableAction::variableType(), Function::vectorCurl(), SubProblem::vectorTagName(), SubProblem::vectorTagType(), Function::vectorValue(), MooseParsedFunction::vectorValue(), MooseParsedGradFunction::vectorValue(), SubProblem::verifyVectorTags(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
mooseErrorNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseErrorNonPrefixed (Args &&... args) const inline inherited
Emits an error without the prefixing included in mooseError().
Definition at line 50 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
mooseInfo()
template<typename... Args> void MooseBaseErrorInterface::mooseInfo (Args &&... args) const inline inherited
Definition at line 84 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseInfoStream(_console, std::forward<Args>(args)...);
  }
Referenced by AddZapdosReactions::act(), SetupRecoverFileBaseAction::act(), AStableDirk4::AStableDirk4(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), BoltzmannSolverScalar::execute(), ExplicitRK2::ExplicitRK2(), ExplicitTVDRK2::ExplicitTVDRK2(), MultiAppTransfer::getPointInTargetAppFrame(), ImplicitMidpoint::ImplicitMidpoint(), InversePowerMethod::InversePowerMethod(), LStableDirk2::LStableDirk2(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), NonlinearEigen::NonlinearEigen(), ProjectionAux::ProjectionAux(), FEProblemBase::setRestartFile(), and SymmetryTransformGenerator::SymmetryTransformGenerator().
mooseWarning()
template<typename... Args> void MooseBaseErrorInterface::mooseWarning (Args &&... args) const inline inherited
Emits a warning prefixed with object name and type.
Definition at line 62 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(
        _console, errorPrefix("warning"), std::forward<Args>(args)...);
  }
Referenced by AddFunctionAction::act(), AddKernelAction::act(), CommonOutputAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupMeshAction::act(), DumpObjectsProblem::addAuxVariable(), DiracKernelBase::addPoint(), BoundaryMarker::BoundaryMarker(), BoundsAuxBase::BoundsAuxBase(), DistributedRectilinearMeshGenerator::buildCube(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), CartesianMeshGenerator::CartesianMeshGenerator(), CheckOutputAction::checkConsoleOutput(), MultiAppTransfer::checkMultiAppExecuteOn(), GapValueAux::computeValue(), MeshDiagnosticsGenerator::diagnosticsLog(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), Postprocessor::evaluateDotWarning(), ElementQualityChecker::finalize(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FixedPointSolve::FixedPointSolve(), ElementSubdomainIDGenerator::generate(), ParsedGenerateSideset::generate(), MultiAppTransfer::getAppInfo(), FunctorBinnedValuesDivision::getBinIndex(), FEProblemBase::getMaterial(), Terminator::handleMessage(), MaterialBase::initStatefulProperties(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::mesh(), NewmarkBeta::NewmarkBeta(), NodalPatchRecovery::NodalPatchRecovery(), Output::Output(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), Executioner::problem(), PropertyReadFile::readData(), TestSourceStepper::rejectStep(), MaterialBase::resetQpProperties(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setCoordSystem(), FEProblemBase::sizeZeroes(), TransientMultiApp::solveStep(), TimeDerivativeAux::TimeDerivativeAux(), PiecewiseConstantFromCSV::value(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
mooseWarningNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseWarningNonPrefixed (Args &&... args) const inline inherited
Emits a warning without the prefixing included in mooseWarning().
Definition at line 72 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(_console, std::forward<Args>(args)...);
  }
name()
virtual const std::string & MooseBase::name () const inline virtual inherited
Get the name of the class.
Returns
The name of the class
Reimplemented in MooseVariableBase.
Definition at line 47 of file MooseBase.h.
{ return _name; }
Referenced by HierarchicalGridPartitioner::_do_partition(), AdaptivityAction::act(), AddElementalFieldAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVariableAction::act(), CopyNodalVarsAction::act(), DeprecatedBlockAction::act(), DisplayGhostingAction::act(), MaterialOutputAction::act(), AddDriftDiffusionAction::addADKernels(), FEProblemBase::addAnyRedistributers(), Executioner::addAttributeReporter(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFunctorMaterial(), FunctorMaterial::addFunctorProperty(), FunctorMaterial::addFunctorPropertyByBlocks(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), ADDGKernel::ADDGKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), SubProblem::addPiecewiseByBlockLambdaFunctor(), FEProblemBase::addPostprocessor(), UserObject::addPostprocessorDependencyHelper(), InitialConditionBase::addPostprocessorDependencyHelper(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), UserObject::addUserObjectDependencyHelper(), AuxKernelTempl< ComputeValueType >::addUserObjectDependencyHelper(), InitialConditionBase::addUserObjectDependencyHelper(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), UserObject::addVectorPostprocessorDependencyHelper(), FVFluxKernel::adjustRMGhostLayers(), ADSurfaceCharge::ADSurfaceCharge(), Output::advancedExecuteOn(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayDGKernel::ArrayDGKernel(), ArrayParsedAux::ArrayParsedAux(), AStableDirk4::AStableDirk4(), Function::average(), MultiApp::backup(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), PiecewiseTabularBase::buildFromFile(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkICRestartError(), Damper::checkMinDamping(), Coupleable::checkWritableVar(), CompositeFunction::CompositeFunction(), MaterialBase::computeProperties(), FEProblemBase::computeUserObjectByName(), VectorPostprocessorVisualizationAux::computeValue(), MooseBaseParameterInterface::connectControllableParams(), BatchMaterial< Tuple, Output, Input >::construct(), MultiApp::createApp(), AddVariableAction::createInitialConditionAction(), MultiApp::createLocalApp(), MeshGeneratorSystem::createMeshGeneratorOrder(), MaterialBase::declareADProperty(), MeshGenerator::declareMeshesForSubByName(), MeshGenerator::declareNullMeshName(), MaterialBase::declareProperty(), DOFMapOutput::demangle(), DerivativeSumMaterialTempl< is_ad >::DerivativeSumMaterialTempl(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DomainUserObject::DomainUserObject(), DumpObjectsProblem::dumpObjectHelper(), EconomouDielectricBC::EconomouDielectricBC(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementValueSampler::ElementValueSampler(), MooseMesh::errorIfDistributedMesh(), MooseBaseErrorInterface::errorPrefix(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), PointValue::execute(), RestartableDataReporter::execute(), MultiAppNearestNodeTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), MultiApp::fillPositions(), PointSamplerBase::finalize(), FunctionDT::FunctionDT(), FVFunctionIC::functionName(), FunctionIC::functionName(), FunctorPositions::FunctorPositions(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), BoundaryDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), GeneratedMeshGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MeshGenerator::generateInternal(), InterfaceMaterial::getADMaterialProperty(), Material::getADMaterialProperty(), MultiAppTransfer::getAppInfo(), MultiApp::getBoundingBox(), Control::getControllableParameterByName(), Control::getControllableValue(), Control::getControllableValueByName(), UserObject::getDependObjects(), FEProblemBase::getDistribution(), DistributionInterface::getDistribution(), DistributionInterface::getDistributionByName(), AddZapdosReactions::getElectronImpactKernelName(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), MultiApp::getExecutioner(), FEProblemBase::getExecutor(), OutputWarehouse::getFileNumbers(), FEProblemBase::getFunction(), SubProblem::getFunctor(), AuxKernelTempl< ComputeValueType >::getGenericMaterialProperty(), NodalPatchRecovery::getGenericMaterialProperty(), InterfaceMaterial::getGenericMaterialProperty(), Material::getGenericMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialPropertyByName(), Material::getGenericOptionalMaterialProperty(), MaterialBase::getGenericZeroMaterialProperty(), BatchMaterial< Tuple, Output, Input >::getIndex(), AddZapdosReactions::getKernelName(), SolutionUserObject::getLocalVarIndex(), Marker::getMarkerValue(), Material::getMaterial(), FEProblemBase::getMaterial(), Material::getMaterialByName(), AuxKernelTempl< ComputeValueType >::getMaterialProperty(), NodalPatchRecovery::getMaterialProperty(), InterfaceMaterial::getMaterialProperty(), Material::getMaterialProperty(), SubProblem::getMaterialPropertyBlockNames(), SubProblem::getMaterialPropertyBoundaryNames(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOld(), NodalPatchRecovery::getMaterialPropertyOld(), InterfaceMaterial::getMaterialPropertyOld(), Material::getMaterialPropertyOld(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOlder(), NodalPatchRecovery::getMaterialPropertyOlder(), InterfaceMaterial::getMaterialPropertyOlder(), Material::getMaterialPropertyOlder(), MeshGenerator::getMesh(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshesByName(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MultiAppTransfer::getMultiApp(), InterfaceMaterial::getNeighborADMaterialProperty(), InterfaceMaterial::getNeighborMaterialProperty(), InterfaceMaterial::getNeighborMaterialPropertyOld(), InterfaceMaterial::getNeighborMaterialPropertyOlder(), Material::getOptionalADMaterialProperty(), Material::getOptionalMaterialProperty(), Material::getOptionalMaterialPropertyOld(), Material::getOptionalMaterialPropertyOlder(), FEProblemBase::getPositionsObject(), FEProblemBase::getPostprocessorValueByName(), AddReactions::getReactionKernelName(), ReporterData::getReporterInfo(), FEProblemBase::getSampler(), Transient::getTimeStepperName(), ProjectedStatefulMaterialStorageAction::getTypeEnum(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), Terminator::handleMessage(), FEProblemBase::hasFunction(), SubProblem::hasFunctor(), SubProblem::hasFunctorWithType(), AdvancedOutput::hasOutputHelper(), FEProblemBase::hasPostprocessor(), FEProblemBase::hasPostprocessorValueByName(), FEProblemBase::hasUserObject(), AdvancedOutput::init(), FEProblemBase::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), AttribName::initFrom(), NestedDivision::initialize(), SolutionScalarAux::initialSetup(), NodalVariableValue::initialSetup(), MultiAppProjectionTransfer::initialSetup(), SolutionUserObject::initialSetup(), AdvancedOutput::initOutputList(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MaterialBase::initStatefulProperties(), Function::integral(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), MeshGenerator::isChildMeshGenerator(), MeshGenerator::isNullMeshName(), MeshGenerator::isParentMeshGenerator(), LinearCombinationFunction::LinearCombinationFunction(), FEProblemBase::logAdd(), LymberopoulosElectronBC::LymberopoulosElectronBC(), Marker::Marker(), Material::Material(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), Distribution::median(), MemoryUsageReporter::MemoryUsageReporter(), MeshGenerator::meshPropertyPrefix(), MooseVariableInterface< T >::MooseVariableInterface(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), NeumannCircuitVoltageMoles_KV::NeumannCircuitVoltageMoles_KV(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), NodalValueSampler::NodalValueSampler(), MooseBaseParameterInterface::objectErrorPrefix(), MeshGenerator::Comparator::operator()(), DOFMapOutput::output(), ProgressOutput::output(), Output::Output(), AdvancedOutput::outputElementalVariables(), ConsoleUtils::outputExecutionInformation(), AdvancedOutput::outputInput(), AdvancedOutput::outputNodalVariables(), AdvancedOutput::outputPostprocessors(), Exodus::outputPostprocessors(), Nemesis::outputPostprocessors(), TableOutput::outputReporter(), AdvancedOutput::outputReporters(), AdvancedOutput::outputScalarVariables(), AdvancedOutput::outputSystemInformation(), AdvancedOutput::outputVectorPostprocessors(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedODEKernel::ParsedODEKernel(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PointVariableSamplerBase::PointVariableSamplerBase(), MultiApp::readCommandLineArguments(), Receiver::Receiver(), Executor::Result::record(), FEProblemBase::registerRandomInterface(), GlobalParamsAction::remove(), MaterialBase::resetQpProperties(), MultiApp::restore(), SakiyamaEnergySecondaryElectronBC::SakiyamaEnergySecondaryElectronBC(), SakiyamaSecondaryElectronBC::SakiyamaSecondaryElectronBC(), ScalarComponentIC::ScalarComponentIC(), SecondaryElectronBC::SecondaryElectronBC(), SecondaryElectronEnergyBC::SecondaryElectronEnergyBC(), MultiApp::setAppOutputFileBase(), MooseMesh::setBoundaryName(), Control::setControllableValue(), Control::setControllableValueByName(), GlobalParamsAction::setDoubleIndexParam(), OutputWarehouse::setFileNumbers(), GlobalParamsAction::setParam(), FEProblemBase::setPostprocessorValueByName(), GlobalParamsAction::setScalarParam(), MooseMesh::setSubdomainName(), GlobalParamsAction::setTripleIndexParam(), Split::setup(), TransientMultiApp::setupApp(), GlobalParamsAction::setVectorParam(), SideCurrent::SideCurrent(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SideValueSampler::SideValueSampler(), TransientMultiApp::solveStep(), UserObject::spatialValue(), StitchedMesh::StitchedMesh(), SubProblem::storeBoundaryDelayedCheckMatProp(), SubProblem::storeBoundaryMatPropName(), SubProblem::storeBoundaryZeroMatProp(), SubProblem::storeSubdomainDelayedCheckMatProp(), SubProblem::storeSubdomainMatPropName(), SubProblem::storeSubdomainZeroMatProp(), MaterialBase::subdomainSetup(), TaggingInterface::TaggingInterface(), VectorPostprocessorVisualizationAux::timestepSetup(), MultiAppDofCopyTransfer::transfer(), TransientMultiApp::TransientMultiApp(), MooseBase::typeAndName(), MooseBaseParameterInterface::uniqueParameterName(), UserObject::UserObject(), UserObjectInterface::userObjectName(), MultiAppTransfer::variableIntegrityCheck(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), AdvancedOutput::wantOutput(), Coupleable::writableCoupledValue(), and Coupleable::writableVariable().
objectErrorPrefix()
std::string MooseBaseParameterInterface::objectErrorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for an object.
Definition at line 58 of file MooseBaseParameterInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the class \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseParameterInterface::paramErrorMsg().
paramError()
template<typename... Args> void MooseBaseParameterInterface::paramError (const std::string & param, Args... args) const inherited
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseError - only printing a message using the given args.
Definition at line 233 of file MooseBaseParameterInterface.h.
{
  Moose::show_trace = false;
  std::string msg = paramErrorMsg(param, std::forward<Args>(args)...);
  callMooseErrorRaw(msg, &_moose_base->getMooseApp());
  Moose::show_trace = true;
}
Referenced by HierarchicalGridPartitioner::_do_partition(), SetupDebugAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), ADDGKernel::ADDGKernel(), ReporterPointSource::addPoints(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ADNodalKernel::ADNodalKernel(), ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), AdvectiveFluxAux::AdvectiveFluxAux(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), ArrayBodyForce::ArrayBodyForce(), ArrayDGKernel::ArrayDGKernel(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayDirichletBC::ArrayDirichletBC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), ArrayPenaltyDirichletBC::ArrayPenaltyDirichletBC(), ArrayVacuumBC::ArrayVacuumBC(), BlockDeletionGenerator::BlockDeletionGenerator(), BlockWeightedPartitioner::BlockWeightedPartitioner(), BoundsAuxBase::BoundsAuxBase(), BreakMeshByBlockGenerator::BreakMeshByBlockGenerator(), BuildArrayVariableAux::BuildArrayVariableAux(), PiecewiseTabularBase::buildFromFile(), CartesianGridDivision::CartesianGridDivision(), UserObjectInterface::castUserObject(), checkComponent(), MeshGenerator::checkGetMesh(), PostprocessorInterface::checkParam(), Coupleable::checkVar(), MultiAppTransfer::checkVariable(), CircularBoundaryCorrectionGenerator::CircularBoundaryCorrectionGenerator(), CircularBoundaryCorrectionGenerator::circularCenterCalculator(), MultiAppGeneralFieldTransfer::closestToPosition(), CombinerGenerator::CombinerGenerator(), CompositionDT::CompositionDT(), ConcentricCircleMeshGenerator::ConcentricCircleMeshGenerator(), LibtorchNeuralNetControl::conditionalParameterError(), ConstantVectorPostprocessor::ConstantVectorPostprocessor(), ContainsPointAux::ContainsPointAux(), CopyValueAux::CopyValueAux(), Coupleable::Coupleable(), CoupledForceTempl< is_ad >::CoupledForceTempl(), CoupledValueFunctionMaterialTempl< is_ad >::CoupledValueFunctionMaterialTempl(), MultiApp::createApp(), MeshGeneratorSystem::createMeshGenerator(), CylindricalGridDivision::CylindricalGridDivision(), ConstantReporter::declareConstantReporterValues(), AccumulateReporter::declareLateValues(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DGLowerDKernel::DGLowerDKernel(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementLengthAux::ElementLengthAux(), ElementLpNormAux::ElementLpNormAux(), ElementValueSampler::ElementValueSampler(), ReporterPointSource::errorCheck(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), ExtraElementIDAux::ExtraElementIDAux(), ExtraElementIntegerDivision::ExtraElementIntegerDivision(), FEProblemSolve::FEProblemSolve(), FillBetweenCurvesGenerator::FillBetweenCurvesGenerator(), FillBetweenSidesetsGenerator::FillBetweenSidesetsGenerator(), ReporterPointSource::fillPoint(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), InternalSideIndicator::finalize(), FixedPointSolve::FixedPointSolve(), ForcingFunctionAux::ForcingFunctionAux(), FunctionArrayAux::FunctionArrayAux(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorAux::FunctorAux(), FunctorBinnedValuesDivision::FunctorBinnedValuesDivision(), FunctorElementalGradientAuxTempl< is_ad >::FunctorElementalGradientAuxTempl(), FunctorPositions::FunctorPositions(), FunctorVectorElementalAuxTempl< is_ad >::FunctorVectorElementalAuxTempl(), FVFluxBC::FVFluxBC(), FVInterfaceKernel::FVInterfaceKernel(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), FVTwoVarContinuityConstraint::FVTwoVarContinuityConstraint(), AdvancedExtruderGenerator::generate(), BlockDeletionGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundaryDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), BreakMeshByBlockGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), CombinerGenerator::generate(), ExplodeMeshGenerator::generate(), ExtraNodesetGenerator::generate(), FillBetweenCurvesGenerator::generate(), FillBetweenSidesetsGenerator::generate(), GeneratedMeshGenerator::generate(), MeshCollectionGenerator::generate(), MeshExtruderGenerator::generate(), ParsedCurveGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), PropertyReadFile::getBlockData(), PropertyReadFile::getData(), Sampler::getGlobalSamples(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), Sampler::getLocalSamples(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), Sampler::getNextLocalRow(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectName(), HFEMDirichletBC::HFEMDirichletBC(), MultiApp::init(), BlockWeightedPartitioner::initialize(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), PiecewiseConstantFromCSV::initialSetup(), LibtorchControlValuePostprocessor::initialSetup(), ReferenceResidualProblem::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), HistogramVectorPostprocessor::initialSetup(), AddMetaDataGenerator::inputChecker(), IntegratedBC::IntegratedBC(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceValueUserObjectAux::InterfaceValueUserObjectAux(), InterpolatedStatefulMaterialTempl< T >::InterpolatedStatefulMaterialTempl(), InversePowerMethod::InversePowerMethod(), IterationAdaptiveDT::IterationAdaptiveDT(), MultiApp::keepSolutionDuringRestore(), Kernel::Kernel(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LinearCombinationFunction::LinearCombinationFunction(), LowerDIntegratedBC::LowerDIntegratedBC(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), MaterialADConverterTempl< T >::MaterialADConverterTempl(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), PatternedMeshGenerator::mergeSubdomainNameMaps(), MeshCollectionGenerator::MeshCollectionGenerator(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshDivisionAux::MeshDivisionAux(), MeshGenerator::MeshGenerator(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarNodalAuxKernelTempl< ComputeValueType >::MortarNodalAuxKernelTempl(), MultiApp::moveApp(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), NestedDivision::NestedDivision(), NodalBC::NodalBC(), NodalEqualValueConstraint::NodalEqualValueConstraint(), NodalKernel::NodalKernel(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), NodalValueSampler::NodalValueSampler(), Output::Output(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), PatchMeshGenerator::PatchMeshGenerator(), PatternedMeshGenerator::PatternedMeshGenerator(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), PeriodicSegmentalConstraint::PeriodicSegmentalConstraint(), PIDTransientControl::PIDTransientControl(), PlaneDeletionGenerator::PlaneDeletionGenerator(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), PolyLineMeshGenerator::PolyLineMeshGenerator(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), LibmeshPartitioner::prepareBlocksForSubdomainPartitioner(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), PropertyReadFile::PropertyReadFile(), RandomIC::RandomIC(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readXda(), ReferenceResidualProblem::ReferenceResidualProblem(), RefineBlockGenerator::RefineBlockGenerator(), RefineSidesetGenerator::RefineSidesetGenerator(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setPartitioner(), TimeSequenceStepperBase::setupSequence(), SingleRankPartitioner::SingleRankPartitioner(), SphericalGridDivision::SphericalGridDivision(), SymmetryTransformGenerator::SymmetryTransformGenerator(), Terminator::Terminator(), TimeDerivativeAux::TimeDerivativeAux(), Transfer::Transfer(), TransformGenerator::TransformGenerator(), TransientMultiApp::TransientMultiApp(), ParsedCurveGenerator::tSectionSpaceDefiner(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), UserObject::UserObject(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), VolumeAux::VolumeAux(), XYDelaunayGenerator::XYDelaunayGenerator(), and XYMeshLineCutter::XYMeshLineCutter().
paramErrorMsg()
template<typename... Args> std::string MooseBaseParameterInterface::paramErrorMsg (const std::string & param, Args... args) const inline private inherited
Definition at line 171 of file MooseBaseParameterInterface.h.
  {
    auto param_prefix = paramErrorPrefix(_pars, param);
    // With no input location information, append object info (name + type)
    const std::string object_prefix =
        _pars.inputLocation(param).empty() ? objectErrorPrefix("parameter error") : "";
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    // Wrap error message to a separate line from param_prefix if it is about to
    // blow past 100 chars.  But only wrap if the param_prefix is long enough (12
    // chars) for the wrap to buy us much extra length. We don't check object_prefix
    // here because it will go before the parameter error
    if ((param_prefix.size() > 12 && msg.size() + param_prefix.size() > 99) ||
        msg.find("\n") != std::string::npos)
    {
      if (param_prefix.size() > 0 && param_prefix[param_prefix.size() - 1] != ':')
        param_prefix += ":";
      return object_prefix + param_prefix + "\n    " + MooseUtils::replaceAll(msg, "\n", "\n    ");
    }
    return object_prefix + param_prefix + " " + msg;
  }
Referenced by MooseBaseParameterInterface::paramError(), MooseBaseParameterInterface::paramInfo(), and MooseBaseParameterInterface::paramWarning().
parameters()
const InputParameters & MooseBaseParameterInterface::parameters () const inline inherited
Get the parameters of the object.
Returns
The parameters of the object
Definition at line 53 of file MooseBaseParameterInterface.h.
{ return _pars; }
Referenced by SetupDebugAction::act(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), FEProblemBase::addPostprocessor(), FEProblemBase::addPredictor(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), AdvancedOutput::AdvancedOutput(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), Moose::assemble_matrix(), AuxScalarKernel::AuxScalarKernel(), BoundsAuxBase::BoundsAuxBase(), MooseMesh::buildTypedMesh(), UserObjectInterface::castUserObject(), PostprocessorInterface::checkParam(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), Moose::compute_bounds(), Moose::compute_jacobian(), Moose::compute_nearnullspace(), Moose::compute_nullspace(), Moose::compute_postcheck(), Moose::compute_transpose_nullspace(), LibtorchNeuralNetControl::conditionalParameterError(), Console::Console(), MultiApp::createApp(), Postprocessor::declareValue(), DumpObjectsProblem::deduceNecessaryParameters(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), DumpObjectsProblem::dumpObjectHelper(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElectronsFromIonization::ElectronsFromIonization(), Executor::Executor(), Exodus::Exodus(), FEProblem::FEProblem(), FEProblemBase::FEProblemBase(), FixedPointSolve::FixedPointSolve(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GapValueAux::GapValueAux(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), MooseBaseParameterInterface::getCheckedPointerParam(), ExecutorInterface::getExecutor(), Material::getMaterial(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), UserObjectInterface::getUserObjectName(), VectorPostprocessorInterface::getVectorPostprocessorName(), GhostingUserObject::GhostingUserObject(), HphiRadialInterface::HphiRadialInterface(), AttribSystem::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), FullSolveMultiApp::initialSetup(), FEProblemBase::initNullSpaceVectors(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), isValid(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseAppCoordTransform::MooseAppCoordTransform(), MooseVariableInterface< T >::MooseVariableInterface(), MultiApp::MultiApp(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodeFaceConstraint::NodeFaceConstraint(), PatchMeshGenerator::PatchMeshGenerator(), PenetrationAux::PenetrationAux(), PicardSolve::PicardSolve(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), ProjectedStatefulMaterialStorageAction::processProperty(), MultiAppProjectionTransfer::projectSolution(), PropertyReadFile::PropertyReadFile(), PseudoTimestep::PseudoTimestep(), RandomIC::RandomIC(), InputParameterWarehouse::removeInputParameters(), OutputWarehouse::resetFileBase(), MooseAppCoordTransform::setCoordinateSystem(), FEProblemBase::setInputParametersFEProblem(), FEProblem::setInputParametersFEProblem(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SteffensenSolve::SteffensenSolve(), DumpObjectsProblem::stringifyParameters(), TaggingInterface::TaggingInterface(), Transfer::Transfer(), Transient::Transient(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
paramInfo()
template<typename... Args> void MooseBaseParameterInterface::paramInfo (const std::string & param, Args... args) const inherited
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseInfo - only printing a message using the given args.
Definition at line 250 of file MooseBaseParameterInterface.h.
{
  mooseInfo(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by TransientMultiApp::TransientMultiApp().
paramWarning()
template<typename... Args> void MooseBaseParameterInterface::paramWarning (const std::string & param, Args... args) const inherited
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseWarning - only printing a message using the given args.
Definition at line 243 of file MooseBaseParameterInterface.h.
{
  mooseWarning(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by MultiAppNearestNodeTransfer::execute(), FEProblemSolve::FEProblemSolve(), PlaneIDMeshGenerator::generate(), UniqueExtraIDMeshGenerator::generate(), Terminator::initialSetup(), and MooseMesh::MooseMesh().
possiblyCheckHasVectorPostprocessor()
void VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor (const std::string & param_name, const std::string & vector_name) const private inherited
Helpers for "possibly" checking if a vpp exists.
This is only able to check for existance after all vpps have been added (after the task creating them has been called). If called before said task, this will do nothing, hence the "possibly". This allows us to have errors reported directly by the object requesting the vpp instead of through a system with less context.
Definition at line 228 of file VectorPostprocessorInterface.C.
{
  // Can't do checking if vpps have not been added
  if (!vectorPostprocessorsAdded())
    return;
  if (!hasVectorPostprocessor(param_name))
    _vpi_moose_object.paramError(param_name,
                                 "A VectorPostprocessor with the name \"",
                                 getVectorPostprocessorName(param_name),
                                 "\" was not found.");
  if (!hasVectorPostprocessor(param_name, vector_name))
    _vpi_moose_object.paramError(param_name,
                                 "The VectorPostprocessor \"",
                                 getVectorPostprocessorName(param_name),
                                 "\" does not have a vector named \"",
                                 vector_name,
                                 "\".");
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValue(), VectorPostprocessorInterface::getScatterVectorPostprocessorValueOld(), VectorPostprocessorInterface::getVectorPostprocessorValue(), and VectorPostprocessorInterface::getVectorPostprocessorValueOld().
possiblyCheckHasVectorPostprocessorByName()
void VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName (const VectorPostprocessorName & name, const std::string & vector_name) const private inherited
Definition at line 250 of file VectorPostprocessorInterface.C.
{
  // Can't do checking if vpps have not been added
  if (!vectorPostprocessorsAdded())
    return;
  if (!hasVectorPostprocessorByName(name))
    _vpi_moose_object.mooseError(
        "A VectorPostprocessor with the name \"", name, "\" was not found.");
  if (!hasVectorPostprocessorByName(name, vector_name))
    _vpi_moose_object.mooseError("The VectorPostprocessor \"",
                                 name,
                                 "\" does not have a vector named \"",
                                 vector_name,
                                 "\".");
}
Referenced by VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), and VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper().
postprocessorsAdded()
bool PostprocessorInterface::postprocessorsAdded () const private inherited
Returns
True if all pps have been added (the task associated with adding them is complete)
Definition at line 264 of file PostprocessorInterface.C.
{
  return _ppi_feproblem.getMooseApp().actionWarehouse().isTaskComplete("add_postprocessor");
}
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), and PostprocessorInterface::hasPostprocessorByName().
precalculateJacobian()
virtual void ResidualObject::precalculateJacobian () inline protected virtual inherited
Reimplemented in PenaltyPeriodicSegmentalConstraint.
Definition at line 113 of file ResidualObject.h.
{}
Referenced by IntegratedBC::computeJacobian(), ArrayDGLowerDKernel::computeJacobian(), DGKernelBase::computeJacobian(), DGLowerDKernel::computeJacobian(), ArrayKernel::computeJacobian(), EigenKernel::computeJacobian(), Kernel::computeJacobian(), NonlocalKernel::computeJacobian(), TimeDerivative::computeJacobian(), VectorKernel::computeJacobian(), VectorTimeDerivative::computeJacobian(), and NonlocalKernel::computeNonlocalJacobian().
precalculateOffDiagJacobian()
virtual void ResidualObject::precalculateOffDiagJacobian (unsigned int) inline protected virtual inherited
Definition at line 114 of file ResidualObject.h.
{}
Referenced by NonlocalKernel::computeNonlocalOffDiagJacobian(), IntegratedBC::computeOffDiagJacobian(), ArrayDGKernel::computeOffDiagJacobian(), ArrayDGLowerDKernel::computeOffDiagJacobian(), DGKernelBase::computeOffDiagJacobian(), DGLowerDKernel::computeOffDiagJacobian(), ArrayKernel::computeOffDiagJacobian(), EigenKernel::computeOffDiagJacobian(), Kernel::computeOffDiagJacobian(), NonlocalKernel::computeOffDiagJacobian(), and VectorKernel::computeOffDiagJacobian().
precalculateResidual()
virtual void ResidualObject::precalculateResidual () inline protected virtual inherited
Reimplemented in ADPenaltyPeriodicSegmentalConstraint, and PenaltyPeriodicSegmentalConstraint.
Definition at line 112 of file ResidualObject.h.
{}
Referenced by MortarConstraintBase::computeJacobian(), IntegratedBC::computeResidual(), MortarConstraintBase::computeResidual(), ArrayDGLowerDKernel::computeResidual(), DGKernelBase::computeResidual(), DGLowerDKernel::computeResidual(), ArrayKernel::computeResidual(), EigenKernel::computeResidual(), Kernel::computeResidual(), TimeKernel::computeResidual(), VectorKernel::computeResidual(), and VectorTimeKernel::computeResidual().
prepareMatrixTag() [1/2]
void TaggingInterface::prepareMatrixTag (Assembly & assembly, unsigned int ivar, unsigned int jvar) protected inherited
Prepare data for computing element jacobian according to the active tags.
Jacobian blocks for different tags will be extracted from Assembly. A local Jacobian will be zeroed. It should be called right before the local element matrix is computed.
Definition at line 271 of file TaggingInterface.C.
{
  _ke_blocks.resize(_matrix_tags.size());
  mooseAssert(_matrix_tags.size() >= 1, "we need at least one active tag");
  auto mat_vector = _matrix_tags.begin();
  for (MooseIndex(_matrix_tags) i = 0; i < _matrix_tags.size(); i++, ++mat_vector)
    _ke_blocks[i] = &assembly.jacobianBlock(ivar, jvar, Assembly::LocalDataKey{}, *mat_vector);
  _local_ke.resize(_ke_blocks[0]->m(), _ke_blocks[0]->n());
}
Referenced by ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ArrayIntegratedBC::computeJacobian(), IntegratedBC::computeJacobian(), NonlocalIntegratedBC::computeJacobian(), VectorIntegratedBC::computeJacobian(), ArrayKernel::computeJacobian(), EigenKernel::computeJacobian(), Kernel::computeJacobian(), KernelGrad::computeJacobian(), KernelValue::computeJacobian(), MassLumpedTimeDerivative::computeJacobian(), NonlocalKernel::computeJacobian(), ODEKernel::computeJacobian(), TimeDerivative::computeJacobian(), VectorKernel::computeJacobian(), VectorTimeDerivative::computeJacobian(), NodalEqualValueConstraint::computeJacobian(), ScalarKernel::computeJacobian(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ArrayIntegratedBC::computeOffDiagJacobian(), IntegratedBC::computeOffDiagJacobian(), NonlocalIntegratedBC::computeOffDiagJacobian(), VectorIntegratedBC::computeOffDiagJacobian(), ArrayKernel::computeOffDiagJacobian(), EigenKernel::computeOffDiagJacobian(), Kernel::computeOffDiagJacobian(), KernelGrad::computeOffDiagJacobian(), KernelValue::computeOffDiagJacobian(), NonlocalKernel::computeOffDiagJacobian(), VectorKernel::computeOffDiagJacobian(), ArrayIntegratedBC::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), ArrayKernel::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), and ConservativeAdvection::fullUpwind().
prepareMatrixTag() [2/2]
void TaggingInterface::prepareMatrixTag (Assembly & assembly, unsigned int ivar, unsigned int jvar, DenseMatrix< Number > & k) const protected inherited
Definition at line 283 of file TaggingInterface.C.
{
  mooseAssert(!_matrix_tags.empty(), "No matrix tags exist");
  const auto & ij_mat =
      assembly.jacobianBlock(ivar, jvar, Assembly::LocalDataKey{}, *_matrix_tags.begin());
  k.resize(ij_mat.m(), ij_mat.n());
}
prepareMatrixTagLower()
void TaggingInterface::prepareMatrixTagLower (Assembly & assembly, unsigned int ivar, unsigned int jvar, Moose::ConstraintJacobianType type) protected inherited
Prepare data for computing the jacobian according to the active tags for mortar.
Jacobian blocks for different tags will be extracted from Assembly. A local Jacobian will be zeroed. It should be called right before the local element matrix is computed.
Definition at line 339 of file TaggingInterface.C.
{
  _ke_blocks.resize(_matrix_tags.size());
  mooseAssert(_matrix_tags.size() >= 1, "we need at least one active tag");
  auto mat_vector = _matrix_tags.begin();
  for (MooseIndex(_matrix_tags) i = 0; i < _matrix_tags.size(); i++, ++mat_vector)
    _ke_blocks[i] =
        &assembly.jacobianBlockMortar(type, ivar, jvar, Assembly::LocalDataKey{}, *mat_vector);
  _local_ke.resize(_ke_blocks[0]->m(), _ke_blocks[0]->n());
}
Referenced by MortarConstraint::computeJacobian(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), and DGLowerDKernel::computeOffDiagLowerDJacobian().
prepareMatrixTagNeighbor() [1/2]
void TaggingInterface::prepareMatrixTagNeighbor (Assembly & assembly, unsigned int ivar, unsigned int jvar, Moose::DGJacobianType type) protected inherited
Prepare data for computing element jacobian according to the active tags for DG and interface kernels.
Jacobian blocks for different tags will be extracted from Assembly. A local Jacobian will be zeroed. It should be called right before the local element matrix is computed.
Definition at line 310 of file TaggingInterface.C.
{
  _ke_blocks.resize(_matrix_tags.size());
  mooseAssert(_matrix_tags.size() >= 1, "we need at least one active tag");
  auto mat_vector = _matrix_tags.begin();
  for (MooseIndex(_matrix_tags) i = 0; i < _matrix_tags.size(); i++, ++mat_vector)
    _ke_blocks[i] =
        &assembly.jacobianBlockNeighbor(type, ivar, jvar, Assembly::LocalDataKey{}, *mat_vector);
  _local_ke.resize(_ke_blocks[0]->m(), _ke_blocks[0]->n());
}
Referenced by ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), NodeElemConstraint::computeJacobian(), NodeFaceConstraint::computeJacobian(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), NodeElemConstraint::computeOffDiagJacobian(), and NodeFaceConstraint::computeOffDiagJacobian().
prepareMatrixTagNeighbor() [2/2]
void TaggingInterface::prepareMatrixTagNeighbor (Assembly & assembly, unsigned int ivar, unsigned int jvar, Moose::DGJacobianType type, DenseMatrix< Number > & k) const protected inherited
Definition at line 326 of file TaggingInterface.C.
{
  mooseAssert(!_matrix_tags.empty(), "No matrix tags exist");
  const auto & ij_mat = assembly.jacobianBlockNeighbor(
      type, ivar, jvar, Assembly::LocalDataKey{}, *_matrix_tags.begin());
  k.resize(ij_mat.m(), ij_mat.n());
}
prepareMatrixTagNonlocal()
void TaggingInterface::prepareMatrixTagNonlocal (Assembly & assembly, unsigned int ivar, unsigned int jvar) protected inherited
Prepare data for computing nonlocal element jacobian according to the active tags.
Jacobian blocks for different tags will be extracted from Assembly. A nonlocal Jacobian will be zeroed. It should be called right before the nonlocal element matrix is computed.
Definition at line 295 of file TaggingInterface.C.
{
  _ke_blocks.resize(_matrix_tags.size());
  mooseAssert(_matrix_tags.size() >= 1, "we need at least one active tag");
  auto mat_vector = _matrix_tags.begin();
  for (MooseIndex(_matrix_tags) i = 0; i < _matrix_tags.size(); i++, ++mat_vector)
    _ke_blocks[i] =
        &assembly.jacobianBlockNonlocal(ivar, jvar, Assembly::LocalDataKey{}, *mat_vector);
  _nonlocal_ke.resize(_ke_blocks[0]->m(), _ke_blocks[0]->n());
}
Referenced by NonlocalIntegratedBC::computeNonlocalJacobian(), NonlocalKernel::computeNonlocalJacobian(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), and NonlocalKernel::computeNonlocalOffDiagJacobian().
prepareShapes()
void ResidualObject::prepareShapes (unsigned int var_num) virtual inherited
Prepare shape functions.
Parameters
var_num The variable number whose shape functions should be prepared
Reimplemented in IntegratedBCBase, DGKernelBase, and InterfaceKernelBase.
Definition at line 60 of file ResidualObject.C.
{
  _subproblem.prepareShapes(var_num, _tid);
}
Referenced by ComputeJacobianThread::compute(), and Kernel::computeResidualAndJacobian().
prepareVectorTag() [1/2]
void TaggingInterface::prepareVectorTag (Assembly & assembly, unsigned int ivar) protected inherited
Prepare data for computing element residual according to active tags.
Residual blocks for different tags will be extracted from Assembly. A local residual will be zeroed. It should be called right before the local element vector is computed.
Definition at line 184 of file TaggingInterface.C.
{
  prepareVectorTagInternal(assembly, ivar, _vector_tags, _abs_vector_tags);
}
Referenced by FVInterfaceKernel::addResidual(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayIntegratedBC::computeResidual(), IntegratedBC::computeResidual(), VectorIntegratedBC::computeResidual(), NodeElemConstraint::computeResidual(), NodeFaceConstraint::computeResidual(), FVElementalKernel::computeResidual(), ArrayKernel::computeResidual(), EigenKernel::computeResidual(), Kernel::computeResidual(), KernelGrad::computeResidual(), KernelValue::computeResidual(), ODEKernel::computeResidual(), ODETimeKernel::computeResidual(), TimeKernel::computeResidual(), VectorKernel::computeResidual(), VectorTimeKernel::computeResidual(), ADScalarKernel::computeResidual(), NodalEqualValueConstraint::computeResidual(), ScalarKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVFluxBC::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), ADMortarConstraint::computeResidual(), MortarConstraint::computeResidual(), and ConservativeAdvection::fullUpwind().
prepareVectorTag() [2/2]
void TaggingInterface::prepareVectorTag (Assembly & assembly, unsigned int ivar, ResidualTagType tag_type) protected inherited
Prepare vector tags in a reference residual problem context.
Parameters
Assembly The assembly object that we obtain the local residual blocks from
ivar The variable which we are retrieving the local residual blocks for
ref_problem A pointer to a reference residual problem. This can be a nullptr
tag_type What type of tags to prepare
Definition at line 190 of file TaggingInterface.C.
{
  if (tag_type == ResidualTagType::NonReference)
    prepareVectorTagInternal(assembly, ivar, _non_ref_vector_tags, _non_ref_abs_vector_tags);
  else
    prepareVectorTagInternal(assembly, ivar, _ref_vector_tags, _ref_abs_vector_tags);
}
prepareVectorTagInternal()
void TaggingInterface::prepareVectorTagInternal (Assembly & assembly, unsigned int ivar, const std::set< TagID > & vector_tags, const std::set< TagID > & absolute_value_vector_tags) private inherited
Prepare data for computing element residual according to the specified tags Residual blocks for different tags will be extracted from Assembly.
A local residual will be zeroed. It should be called right before the local element vector is computed.
Definition at line 201 of file TaggingInterface.C.
{
  auto prepare = [this, ivar, &assembly](auto & re_blocks, const auto & tags)
  {
    re_blocks.clear();
    re_blocks.reserve(tags.size());
    for (const auto tag_id : tags)
    {
      const auto & tag = _subproblem.getVectorTag(tag_id);
      re_blocks.push_back(&assembly.residualBlock(ivar, Assembly::LocalDataKey{}, tag._type_id));
    }
  };
  prepare(_re_blocks, vector_tags);
  prepare(_absre_blocks, absolute_value_vector_tags);
  _local_re.resize(_re_blocks.empty()
                       ? (_absre_blocks.empty() ? std::size_t(0) : _absre_blocks[0]->size())
                       : _re_blocks[0]->size());
}
Referenced by TaggingInterface::prepareVectorTag().
prepareVectorTagLower()
void TaggingInterface::prepareVectorTagLower (Assembly & assembly, unsigned int ivar) protected inherited
Prepare data for computing the residual according to active tags for mortar constraints.
Residual blocks for different tags will be extracted from Assembly. A local residual will be zeroed. It should be called right before the local element vector is computed.
Definition at line 249 of file TaggingInterface.C.
{
  _re_blocks.resize(_vector_tags.size());
  mooseAssert(_vector_tags.size() >= 1, "we need at least one active tag");
  auto vector_tag = _vector_tags.begin();
  for (MooseIndex(_vector_tags) i = 0; i < _vector_tags.size(); i++, ++vector_tag)
  {
    const VectorTag & tag = _subproblem.getVectorTag(*vector_tag);
    _re_blocks[i] = &assembly.residualBlockLower(ivar, Assembly::LocalDataKey{}, tag._type_id);
  }
  _local_re.resize(_re_blocks[0]->size());
  _absre_blocks.resize(_abs_vector_tags.size());
  vector_tag = _abs_vector_tags.begin();
  for (MooseIndex(_abs_vector_tags) i = 0; i < _abs_vector_tags.size(); i++, ++vector_tag)
  {
    const VectorTag & tag = _subproblem.getVectorTag(*vector_tag);
    _absre_blocks[i] = &assembly.residualBlockLower(ivar, Assembly::LocalDataKey{}, tag._type_id);
  }
}
Referenced by ArrayDGLowerDKernel::computeLowerDResidual(), DGLowerDKernel::computeLowerDResidual(), ArrayLowerDIntegratedBC::computeResidual(), LowerDIntegratedBC::computeResidual(), ADMortarConstraint::computeResidual(), and MortarConstraint::computeResidual().
prepareVectorTagNeighbor()
void TaggingInterface::prepareVectorTagNeighbor (Assembly & assembly, unsigned int ivar) protected inherited
Prepare data for computing element residual the according to active tags for DG and interface kernels.
Residual blocks for different tags will be extracted from Assembly. A local residual will be zeroed. It should be called right before the local element vector is computed.
Definition at line 226 of file TaggingInterface.C.
{
  _re_blocks.resize(_vector_tags.size());
  mooseAssert(_vector_tags.size() >= 1, "we need at least one active tag");
  auto vector_tag = _vector_tags.begin();
  for (MooseIndex(_vector_tags) i = 0; i < _vector_tags.size(); i++, ++vector_tag)
  {
    const VectorTag & tag = _subproblem.getVectorTag(*vector_tag);
    _re_blocks[i] = &assembly.residualBlockNeighbor(ivar, Assembly::LocalDataKey{}, tag._type_id);
  }
  _local_re.resize(_re_blocks[0]->size());
  _absre_blocks.resize(_abs_vector_tags.size());
  vector_tag = _abs_vector_tags.begin();
  for (MooseIndex(_abs_vector_tags) i = 0; i < _abs_vector_tags.size(); i++, ++vector_tag)
  {
    const VectorTag & tag = _subproblem.getVectorTag(*vector_tag);
    _absre_blocks[i] =
        &assembly.residualBlockNeighbor(ivar, Assembly::LocalDataKey{}, tag._type_id);
  }
}
Referenced by FVInterfaceKernel::addResidual(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), NodeElemConstraint::computeResidual(), NodeFaceConstraint::computeResidual(), FVFluxBC::computeResidual(), FVFluxKernel::computeResidual(), ADMortarConstraint::computeResidual(), and MortarConstraint::computeResidual().
registerRestartableDataOnApp()
RestartableDataValue & Restartable::registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const private inherited
Helper function for actually registering the restartable data.
Definition at line 51 of file Restartable.C.
{
  return _restartable_app.registerRestartableData(
      std::move(data), tid, _restartable_read_only, _metaname);
}
Referenced by Restartable::declareRestartableDataHelper().
registerRestartableNameWithFilterOnApp()
void Restartable::registerRestartableNameWithFilterOnApp (const std::string & name, Moose::RESTARTABLE_FILTER filter) private inherited
Helper function for actually registering the restartable data.
Definition at line 59 of file Restartable.C.
{
  _restartable_app.registerRestartableNameWithFilter(name, filter);
}
Referenced by Restartable::declareRecoverableData().
reinit()
void ODEKernel::reinit () override virtual inherited
Reinitialization method called before each call to computeResidual()
Implements ScalarKernelBase.
Definition at line 27 of file ODEKernel.C.
{
}
residualSetup()
void SetupInterface::residualSetup () virtual inherited
Gets called just before the residual is computed and before this object is asked to do its job.
Reimplemented in NodeFaceConstraint, Function, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 55 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::residualSetup(), ComputeFVFluxResidualThread< RangeType >::setup(), and ComputeFVFluxRJThread< RangeType >::setup().
restartableName()
std::string Restartable::restartableName (const std::string & data_name) const protected inherited
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
This should only be used in this interface and in testing.
Definition at line 66 of file Restartable.C.
{
  return _restartable_system_name + "/" + _restartable_name + "/" + data_name;
}
Referenced by Restartable::declareRecoverableData(), and Restartable::declareRestartableDataHelper().
setRandomDataPointer()
void RandomInterface::setRandomDataPointer (RandomData * random_data) inherited
Definition at line 54 of file RandomInterface.C.
{
  _random_data = random_data;
  _generator = &_random_data->getGenerator();
}
Referenced by FEProblemBase::registerRandomInterface().
setRandomResetFrequency()
void RandomInterface::setRandomResetFrequency (ExecFlagType exec_flag) inherited
This interface should be called from a derived class to enable random number generation in this object.
Definition at line 47 of file RandomInterface.C.
{
  _reset_on = exec_flag;
  _ri_problem.registerRandomInterface(*this, _ri_name);
}
setResidual() [1/3]
template<typename T > void TaggingInterface::setResidual (SystemBase & sys, const T & residual, MooseVariableFE< T > & var) protected inherited
Set residual using the variables' insertion API.
Definition at line 537 of file TaggingInterface.h.
{
  for (const auto tag_id : _vector_tags)
    if (sys.hasVector(tag_id))
      var.insertNodalValue(sys.getVector(tag_id), residual);
}
Referenced by ArrayNodalBC::computeResidual(), NodalBC::computeResidual(), and VectorNodalBC::computeResidual().
setResidual() [2/3]
void TaggingInterface::setResidual (SystemBase & sys, Real residual, dof_id_type dof_index) inline protected inherited
Set residual at a specified degree of freedom index.
Definition at line 545 of file TaggingInterface.h.
{
  for (const auto tag_id : _vector_tags)
    if (sys.hasVector(tag_id))
      sys.getVector(tag_id).set(dof_index, residual);
}
setResidual() [3/3]
template<typename SetResidualFunctor > void TaggingInterface::setResidual (SystemBase & sys, SetResidualFunctor set_residual_functor) protected inherited
Set residuals using the provided functor.
Definition at line 554 of file TaggingInterface.h.
{
  for (const auto tag_id : _vector_tags)
    if (sys.hasVector(tag_id))
      set_residual_functor(sys.getVector(tag_id));
}
subdomainSetup()
void SetupInterface::subdomainSetup () virtual inherited
Gets called when the subdomain changes (i.e.
in a Jacobian or residual loop) and before this object is asked to do its job
Reimplemented in Material, MaterialBase, GeneralUserObject, NodalUserObject, ThreadedGeneralUserObject, and Constraint.
Definition at line 60 of file SetupInterface.C.
{
}
subProblem()
const SubProblem & ResidualObject::subProblem () const inline inherited
Returns a reference to the SubProblem for which this Kernel is active.
Definition at line 103 of file ResidualObject.h.
{ return _subproblem; }
timestepSetup()
void SetupInterface::timestepSetup () virtual inherited
Gets called at the beginning of the timestep before this object is asked to do its job.
Reimplemented in VectorPostprocessorVisualizationAux, EqualValueEmbeddedConstraint, Function, Console, JSONOutput, Positions, MemoryUsage, NumNonlinearIterations, Times, SolutionUserObject, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, MooseVariableFV< T >, and VectorMemoryUsage.
Definition at line 45 of file SetupInterface.C.
{
}
Referenced by JSONOutput::timestepSetup(), and MooseVariableField< OutputType >::timestepSetup().
type()
const std::string & MooseBase::type () const inline inherited
Get the type of this class.
Returns
the name of the type of this class
Definition at line 41 of file MooseBase.h.
{ return _type; }
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), CreateProblemDefaultAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetupDebugAction::act(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::addDistribution(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addObject(), DistributedRectilinearMeshGenerator::addPoint(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), PhysicsBasedPreconditioner::addSystem(), FEProblemBase::addTimeIntegrator(), SubProblem::addVectorTag(), DisplacedProblem::addVectorTag(), FEProblemBase::advanceMultiApps(), FEProblemBase::backupMultiApps(), BoundaryPreservedMarker::BoundaryPreservedMarker(), DistributedRectilinearMeshGenerator::buildCube(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildPRefinementAndCoarseningMaps(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), FEProblemBase::computeAuxiliaryKernels(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpJacobian(), HFEMDirichletBC::computeLowerDQpJacobian(), ArrayHFEMDiffusion::computeLowerDQpJacobian(), HFEMDiffusion::computeLowerDQpJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), FEProblemBase::computeMultiAppsDT(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), DGCoupledAdvection::computeOffDiagJacobianHelper(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ScalarKernel::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueBoundaryConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), LinearNodalConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), DGConvection::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), InterfaceDiffusion::computeQpJacobian(), InterfaceReaction::computeQpJacobian(), DGCoupledAdvection::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), DGFunctionTemperatureAdvection::computeQpJacobian(), DGTemperatureAdvection::computeQpJacobian(), InterTemperatureAdvection::computeQpJacobian(), CoupledTiedValueConstraint::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), HFEMTestJump::computeQpOffDiagJacobian(), HFEMTrialJump::computeQpOffDiagJacobian(), DGCoupledAdvection::computeQpOffDiagJacobian(), ScalarKernel::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), EqualValueBoundaryConstraint::computeQpResidual(), EqualValueEmbeddedConstraint::computeQpResidual(), LinearNodalConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), DGConvection::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), DGEFieldAdvection::computeQpResidual(), HphiRadialInterface::computeQpResidual(), InterfaceAdvection::computeQpResidual(), InterfaceLogDiffusionElectrons::computeQpResidual(), PotentialSurfaceCharge::computeQpResidual(), ADDGAdvection::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), HFEMDiffusion::computeQpResidual(), HFEMTestJump::computeQpResidual(), HFEMTrialJump::computeQpResidual(), InterfaceDiffusion::computeQpResidual(), InterfaceReaction::computeQpResidual(), DGCoupledAdvection::computeQpResidual(), DGFunctionConvection::computeQpResidual(), DGFunctionTemperatureAdvection::computeQpResidual(), DGTemperatureAdvection::computeQpResidual(), InterTemperatureAdvection::computeQpResidual(), ArrayDGDiffusion::computeQpResidual(), ArrayHFEMDiffusion::computeQpResidual(), FEProblemBase::computeUserObjectByName(), FEProblemBase::computeUserObjects(), FEProblemBase::computeUserObjectsInternal(), BatchMaterial< Tuple, Output, Input >::construct(), DisplacedProblem::createQRules(), FEProblemBase::createQRules(), MeshGenerator::declareMeshProperty(), DumpObjectsProblem::deduceNecessaryParameters(), DumpObjectsProblem::dumpObjectHelper(), FEProblemBase::duplicateVariableCheck(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), MooseBaseErrorInterface::errorPrefix(), AB2PredictorCorrector::estimateTimeError(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finishMultiAppStep(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), ElementSubdomainIDGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), PatternedMeshGenerator::generate(), MeshGenerator::generateInternal(), MultiAppTransfer::getAppInfo(), TransfiniteMeshGenerator::getEdge(), ElementGenerator::getElemType(), FEProblemBase::getMaterial(), FEProblemBase::getMaterialData(), MaterialOutputAction::getParams(), ReporterData::getReporterInfo(), Transient::getTimeIntegratorName(), FEProblemBase::getTransfers(), SubProblem::getVectorTags(), DisplacedProblem::getVectorTags(), CommonOutputAction::hasConsole(), FEProblemBase::hasMultiApps(), AdvancedOutput::hasOutput(), FEProblemBase::incrementMultiAppTStep(), AdvancedOutput::initAvailableLists(), FunctorPositions::initialize(), FunctorTimes::initialize(), MultiAppConservativeTransfer::initialSetup(), ArrayDGDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), RelationshipManager::isType(), FEProblemBase::logAdd(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), SubProblem::numVectorTags(), DisplacedProblem::numVectorTags(), MooseBaseParameterInterface::objectErrorPrefix(), AdvancedOutput::output(), Console::output(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), ProjectedStatefulMaterialStorageAction::processProperty(), SolutionInvalidInterface::registerInvalidSolutionInternal(), FEProblemBase::restoreMultiApps(), MeshRepairGenerator::separateSubdomainsByElementType(), FEProblemBase::setCoupling(), MooseBase::typeAndName(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), DisplacedProblem::updateGeomSearch(), FEProblemBase::updateGeomSearch(), UserObjectInterface::userObjectType(), and AdvancedOutput::wantOutput().
typeAndName()
std::string MooseBase::typeAndName () const inline inherited
Get the class's combined type and name; useful in error handling.
Returns
The type and name of this class in the form '<type()> "<name()>"'.
Definition at line 53 of file MooseBase.h.
  {
    return type() + std::string(" \"") + name() + std::string("\"");
  }
Referenced by ReporterContext< T >::finalize(), and ReporterData::getReporterInfo().
uniqueName()
MooseObjectName MooseBaseParameterInterface::uniqueName () const inline inherited
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
Definition at line 58 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectName(_pars.get<std::string>("_unique_name"));
  }
Referenced by MooseBaseParameterInterface::connectControllableParams(), and Action::uniqueActionName().
uniqueParameterName()
MooseObjectParameterName MooseBaseParameterInterface::uniqueParameterName (const std::string & parameter_name) const inline inherited
The unique parameter name of a valid parameter of this object for accessing parameter controls.
Definition at line 43 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectParameterName(
        _pars.get<std::string>("_moose_base"), _moose_base->name(), parameter_name);
  }
uOld()
const VariableValue & ScalarKernelBase::uOld () const inherited
Retrieves the old value of the variable that this ScalarKernelBase operates on.
Store this as a reference in the constructor.
Definition at line 44 of file ScalarKernelBase.C.
{
  if (_sys.solutionStatesInitialized())
    mooseError("The solution states have already been initialized when calling ",
               type(),
               "::uOld().\n\n",
               "Make sure to call uOld() within the object constructor.");
  return _var.slnOld();
}
useMatrixTag() [1/2]
void TaggingInterface::useMatrixTag (const TagName & tag_name, MatrixTagsKey) inherited
Definition at line 157 of file TaggingInterface.C.
{
  if (!_subproblem.matrixTagExists(tag_name))
    mooseError("Matrix tag ", tag_name, " does not exist in system");
  _matrix_tags.insert(_subproblem.getMatrixTagID(tag_name));
}
useMatrixTag() [2/2]
void TaggingInterface::useMatrixTag (TagID tag_id, MatrixTagsKey) inherited
Definition at line 175 of file TaggingInterface.C.
{
  if (!_subproblem.matrixTagExists(tag_id))
    mooseError("Matrix tag ", tag_id, " does not exist in system");
  _matrix_tags.insert(tag_id);
}
userObjectName()
const std::string & UserObjectInterface::userObjectName (const UserObject & uo) const private inherited
Gets a UserObject's name; avoids including UserObject.h in the UserObjectInterface.
Definition at line 113 of file UserObjectInterface.C.
{
  return uo.name();
}
Referenced by UserObjectInterface::castUserObject().
userObjectType()
const std::string & UserObjectInterface::userObjectType (const UserObject & uo) const private inherited
Gets a UserObject's type; avoids including UserObject.h in the UserObjectInterface.
Definition at line 107 of file UserObjectInterface.C.
{
  return uo.type();
}
Referenced by UserObjectInterface::castUserObject().
useVectorTag() [1/2]
void TaggingInterface::useVectorTag (const TagName & tag_name, VectorTagsKey) inherited
Definition at line 148 of file TaggingInterface.C.
{
  if (!_subproblem.vectorTagExists(tag_name))
    mooseError("Vector tag ", tag_name, " does not exist in system");
  _vector_tags.insert(_subproblem.getVectorTagID(tag_name));
}
useVectorTag() [2/2]
void TaggingInterface::useVectorTag (TagID tag_id, VectorTagsKey) inherited
Definition at line 166 of file TaggingInterface.C.
{
  if (!_subproblem.vectorTagExists(tag_id))
    mooseError("Vector tag ", tag_id, " does not exist in system");
  _vector_tags.insert(tag_id);
}
validateExecutionerType()
void ScalarCoupleable::validateExecutionerType (const std::string & name, const std::string & fn_name) const private inherited
Checks to make sure that the current Executioner has set "_is_transient" when old/older values are coupled in.
Parameters
name the name of the variable
fn_name The name of the function that called this method - used in the error message
Definition at line 329 of file ScalarCoupleable.C.
{
  if (!_sc_fe_problem.isTransient())
    mooseError(_sc_name,
               ": Calling '",
               fn_name,
               "' on variable \"",
               name,
               "\" when using a \"Steady\" executioner is not allowed. This value is available "
               "only in transient simulations.");
}
Referenced by ScalarCoupleable::coupledScalarDot(), ScalarCoupleable::coupledScalarDotDot(), ScalarCoupleable::coupledScalarDotDotDu(), ScalarCoupleable::coupledScalarDotDotOld(), ScalarCoupleable::coupledScalarDotDu(), ScalarCoupleable::coupledScalarDotOld(), ScalarCoupleable::coupledScalarValueOld(), and ScalarCoupleable::coupledScalarValueOlder().
validParams()
InputParameters ODETimeDerivative::validParams () static
Definition at line 15 of file ODETimeDerivative.C.
{
  InputParameters params = ODETimeKernel::validParams();
  params.addClassDescription(
      "Returns the time derivative contribution to the residual for a scalar variable.");
  return params;
}
variable()
virtual const MooseVariableScalar & ScalarKernelBase::variable () const inline override virtual inherited
The variable that this kernel operates on.
Implements ResidualObject.
Definition at line 34 of file ScalarKernelBase.h.
{ return _var; }
vectorPostprocessorsAdded()
bool VectorPostprocessorInterface::vectorPostprocessorsAdded () const private inherited
Returns
True if all vpps have been added (the task associated with adding them is complete)
Definition at line 306 of file VectorPostprocessorInterface.C.
{
  return _vpi_feproblem.getMooseApp().actionWarehouse().isTaskComplete("add_vector_postprocessor");
}
Referenced by VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), and VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName().
Member Data Documentation
_abs_vector_tags
std::set<TagID> TaggingInterface::_abs_vector_tags private inherited
The absolute value residual tag ids.
Definition at line 354 of file TaggingInterface.h.
Referenced by TaggingInterface::addResiduals(), TaggingInterface::addResidualsWithoutConstraints(), TaggingInterface::prepareVectorTag(), TaggingInterface::prepareVectorTagLower(), TaggingInterface::prepareVectorTagNeighbor(), and TaggingInterface::TaggingInterface().
_absolute_residuals
std::vector<Real> TaggingInterface::_absolute_residuals private inherited
A container to hold absolute values of residuals passed into addResiduals.
We maintain this data member to avoid constant dynamic heap allocations
Definition at line 394 of file TaggingInterface.h.
Referenced by TaggingInterface::addResiduals(), and TaggingInterface::addResidualsWithoutConstraints().
_absre_blocks
std::vector<DenseVector<Number> *> TaggingInterface::_absre_blocks private inherited
Residual blocks for absolute value residual tags.
Definition at line 387 of file TaggingInterface.h.
Referenced by TaggingInterface::accumulateTaggedLocalResidual(), TaggingInterface::assignTaggedLocalResidual(), TaggingInterface::prepareVectorTagInternal(), TaggingInterface::prepareVectorTagLower(), TaggingInterface::prepareVectorTagNeighbor(), and TaggingInterface::TaggingInterface().
_action_factory
ActionFactory& MooseBaseParameterInterface::_action_factory protected inherited
Builds Actions.
Definition at line 164 of file MooseBaseParameterInterface.h.
Referenced by CommonOutputAction::create(), AddVariableAction::createInitialConditionAction(), AddSpecies::createInitialConditions(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
_app
MooseApp& MooseBase::_app protected inherited
The MOOSE application this is associated with.
Definition at line 60 of file MooseBase.h.
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), MeshGenerator::addChildMeshGenerator(), FEProblemBase::addMaterialHelper(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addOutput(), MeshGenerator::addParentMeshGenerator(), FVFluxKernel::adjustRMGhostLayers(), FEProblemBase::allowOutput(), AStableDirk4::AStableDirk4(), FileMesh::buildMesh(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), MeshGenerator::checkGetMesh(), FEProblemBase::checkICRestartError(), FEProblemBase::checkNonlinearConvergence(), OversampleOutput::cloneMesh(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), Console::Console(), TimeStepper::constrainStep(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::createLocalApp(), FEProblemBase::customSetup(), MeshGenerator::declareMeshProperty(), MeshGenerator::declareNullMeshName(), MooseMesh::determineUseDistributedMesh(), DumpObjectsProblem::dumpObjectHelper(), DumpObjectsProblem::dumpVariableHelper(), EigenExecutionerBase::EigenExecutionerBase(), EigenKernel::EigenKernel(), PIDTransientControl::execute(), Eigenvalue::execute(), InversePowerMethod::execute(), NonlinearEigen::execute(), Steady::execute(), Transient::execute(), PseudoTimestep::execute(), IterationInfo::execute(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FileOutput::FileOutput(), ChangeOverFixedPointPostprocessor::finalize(), RadialAverage::finalize(), FixedPointSolve::FixedPointSolve(), FEProblemBase::forceOutput(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), SideSetsFromNormalsGenerator::generate(), MeshGenerator::generateInternal(), FEProblemBase::getExecutor(), MeshGenerator::getMeshByName(), NumFixedPointIterations::getValue(), NumRelationshipManagers::getValue(), GhostingUserObject::GhostingUserObject(), MooseMesh::init(), InversePowerMethod::init(), NonlinearEigen::init(), Transient::init(), FEProblemBase::init(), TimePeriod::initialSetup(), Console::initialSetup(), AdvancedOutput::initOutputList(), FEProblemBase::initPetscOutput(), EigenProblem::initPetscOutput(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MeshGenerator::MeshGenerator(), EigenExecutionerBase::normalizeSolution(), NumFailedTimeSteps::NumFailedTimeSteps(), AugmentSparsityOnInterface::operator()(), Checkpoint::output(), Exodus::output(), Nemesis::output(), PerfGraphOutput::output(), Tecplot::output(), MortarNodalGeometryOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Exodus::outputEmptyTimestep(), Console::outputInput(), Exodus::outputInput(), Exodus::outputNodalVariables(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), Console::outputSystemInformation(), JSONOutput::outputSystemInformation(), MultiApp::parentOutputPositionChanged(), PIDTransientControl::PIDTransientControl(), Transient::preExecute(), Eigenvalue::prepareSolverOptions(), FEProblemBase::projectSolution(), MultiApp::setAppOutputFileBase(), FileOutput::setFileBaseInternal(), MeshGenerator::setMeshProperty(), MeshGenerator::setMeshPropertyHelper(), FEProblemBase::setRestartFile(), TransientMultiApp::setupApp(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SolutionInvalidityReporter::SolutionInvalidityReporter(), FEProblemBase::solve(), EigenProblem::solve(), PetscOutput::solveSetup(), TransientMultiApp::solveStep(), FEProblemBase::subdomainSetup(), FEProblemBase::theWarehouse(), TimeExtremeValue::TimeExtremeValue(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), Transient::Transient(), FEProblemBase::updateMortarMesh(), Console::write(), and FEProblemBase::~FEProblemBase().
_assembly
Assembly& ResidualObject::_assembly protected inherited
Reference to this Kernel's assembly object.
Definition at line 138 of file ResidualObject.h.
Referenced by ADScalarKernel::computeADJacobian(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayIntegratedBC::computeJacobian(), IntegratedBC::computeJacobian(), NonlocalIntegratedBC::computeJacobian(), VectorIntegratedBC::computeJacobian(), ADMortarScalarBase::computeJacobian(), NodeElemConstraint::computeJacobian(), NodeFaceConstraint::computeJacobian(), FVElementalKernel::computeJacobian(), ADKernelScalarBase::computeJacobian(), ArrayKernel::computeJacobian(), EigenKernel::computeJacobian(), Kernel::computeJacobian(), KernelGrad::computeJacobian(), KernelValue::computeJacobian(), MassLumpedTimeDerivative::computeJacobian(), NonlocalKernel::computeJacobian(), ODEKernel::computeJacobian(), TimeDerivative::computeJacobian(), VectorKernel::computeJacobian(), VectorTimeDerivative::computeJacobian(), ADNodalKernel::computeJacobian(), NodalKernel::computeJacobian(), NodalEqualValueConstraint::computeJacobian(), ScalarKernel::computeJacobian(), FVFluxKernel::computeJacobian(), ADMortarConstraint::computeJacobian(), MortarConstraint::computeJacobian(), NodalConstraint::computeJacobian(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDResidual(), DGLowerDKernel::computeLowerDResidual(), NonlocalIntegratedBC::computeNonlocalJacobian(), NonlocalKernel::computeNonlocalJacobian(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), FVScalarLagrangeMultiplierConstraint::computeOffDiagJacobian(), ArrayIntegratedBC::computeOffDiagJacobian(), IntegratedBC::computeOffDiagJacobian(), NonlocalIntegratedBC::computeOffDiagJacobian(), VectorIntegratedBC::computeOffDiagJacobian(), NodeElemConstraint::computeOffDiagJacobian(), NodeFaceConstraint::computeOffDiagJacobian(), ArrayKernel::computeOffDiagJacobian(), EigenKernel::computeOffDiagJacobian(), Kernel::computeOffDiagJacobian(), KernelGrad::computeOffDiagJacobian(), KernelValue::computeOffDiagJacobian(), NonlocalKernel::computeOffDiagJacobian(), VectorKernel::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), ArrayIntegratedBC::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), ArrayKernel::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ArrayIntegratedBC::computeResidual(), ArrayLowerDIntegratedBC::computeResidual(), IntegratedBC::computeResidual(), LowerDIntegratedBC::computeResidual(), VectorIntegratedBC::computeResidual(), ADMortarScalarBase::computeResidual(), MortarScalarBase::computeResidual(), NodeElemConstraint::computeResidual(), NodeFaceConstraint::computeResidual(), FVElementalKernel::computeResidual(), ADKernelScalarBase::computeResidual(), ArrayKernel::computeResidual(), EigenKernel::computeResidual(), Kernel::computeResidual(), KernelGrad::computeResidual(), KernelValue::computeResidual(), ODEKernel::computeResidual(), ODETimeKernel::computeResidual(), TimeKernel::computeResidual(), VectorKernel::computeResidual(), VectorTimeKernel::computeResidual(), ADNodalKernel::computeResidual(), NodalKernel::computeResidual(), TimeNodalKernel::computeResidual(), ADScalarKernel::computeResidual(), NodalEqualValueConstraint::computeResidual(), ScalarKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVFluxKernel::computeResidual(), ADMortarConstraint::computeResidual(), MortarConstraint::computeResidual(), NodalConstraint::computeResidual(), FVElementalKernel::computeResidualAndJacobian(), ADKernelScalarBase::computeResidualAndJacobian(), FVScalarLagrangeMultiplierConstraint::computeResidualAndJacobian(), MortarScalarBase::computeScalarJacobian(), KernelScalarBase::computeScalarJacobian(), MortarScalarBase::computeScalarOffDiagJacobian(), KernelScalarBase::computeScalarOffDiagJacobian(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarResidual(), ConservativeAdvection::fullUpwind(), InterfaceKernelBase::getNeighborElemVolume(), DGKernelBase::getNeighborElemVolume(), MortarConstraintBase::MortarConstraintBase(), NodalScalarKernel::reinit(), and MortarConstraintBase::zeroInactiveLMDofs().
_broadcast_by_default
const bool VectorPostprocessorInterface::_broadcast_by_default private inherited
Whether or not to force broadcasting by default.
Definition at line 352 of file VectorPostprocessorInterface.h.
Referenced by VectorPostprocessorInterface::getVectorPostprocessorValueByName(), and VectorPostprocessorInterface::getVectorPostprocessorValueOldByName().
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_coupled_moose_scalar_vars
std::vector<MooseVariableScalar *> ScalarCoupleable::_coupled_moose_scalar_vars private inherited
Vector of coupled variables.
Definition at line 286 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::getCoupledMooseScalarVars(), and ScalarCoupleable::ScalarCoupleable().
_coupled_scalar_vars
std::unordered_map<std::string, std::vector<MooseVariableScalar *> > ScalarCoupleable::_coupled_scalar_vars private inherited
Coupled vars whose values we provide.
Definition at line 277 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::coupledScalarComponents(), ScalarCoupleable::getScalarVar(), ScalarCoupleable::isCoupledScalar(), and ScalarCoupleable::ScalarCoupleable().
_curr_element
const Elem* const& RandomInterface::_curr_element private inherited
Definition at line 84 of file RandomInterface.h.
Referenced by RandomInterface::getRandomLong(), and RandomInterface::getRandomReal().
_curr_node
const Node* const& RandomInterface::_curr_node private inherited
Definition at line 83 of file RandomInterface.h.
Referenced by RandomInterface::getRandomLong(), and RandomInterface::getRandomReal().
_current_execute_flag
const ExecFlagType& SetupInterface::_current_execute_flag protected inherited
Reference to FEProblemBase.
Definition at line 78 of file SetupInterface.h.
Referenced by PseudoTimestep::execute().
_default_value
std::unordered_map<std::string, std::unique_ptr<VariableValue> > ScalarCoupleable::_default_value mutable private inherited
Will hold the default value for optional coupled scalar variables.
Definition at line 280 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::getDefaultValue().
_default_values
std::map<PostprocessorName, std::unique_ptr<PostprocessorValue> > PostprocessorInterface::_default_values mutable private inherited
Holds the default postprocessor values that are requested (key is PostprocessorName)
Definition at line 154 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::getPostprocessorValueInternal().
_dt
Real& TransientInterface::_dt protected inherited
Time step size.
Definition at line 67 of file TransientInterface.h.
Referenced by ADSurfaceCharge::computeQpProperties(), InterfaceQpValueUserObject::computeRealValue(), Sigma::computeValue(), ForcingFunctionAux::computeValue(), PIDTransientControl::execute(), TimeIntegratedPostprocessor::execute(), and VariableTimeIntegrationAux::getIntegralValue().
_dt_old
Real& TransientInterface::_dt_old protected inherited
Size of the old time step.
Definition at line 70 of file TransientInterface.h.
Referenced by VariableTimeIntegrationAux::getIntegralValue().
_du_dot_du
const VariableValue& ODETimeKernel::_du_dot_du protected inherited
Derivative of u_dot wrt u.
Definition at line 32 of file ODETimeKernel.h.
Referenced by ODETimeDerivativeLog::computeQpJacobian(), ODETimeDerivativeTemperature::computeQpJacobian(), and computeQpJacobian().
_dual_default_value
std::unordered_map<std::string, std::unique_ptr<ADVariableValue> > ScalarCoupleable::_dual_default_value mutable private inherited
Will hold the default AD value for optional coupled scalar variables.
Definition at line 283 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::getADDefaultValue().
_empty_execute_enum
ExecFlagEnum SetupInterface::_empty_execute_enum private inherited
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
This is private because others should not be messing with it.
Definition at line 71 of file SetupInterface.h.
Referenced by SetupInterface::SetupInterface().
_enabled
const bool& MooseObject::_enabled protected inherited
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
Definition at line 58 of file MooseObject.h.
Referenced by MooseObject::enabled().
_execute_enum
const ExecFlagEnum& SetupInterface::_execute_enum protected inherited
Execute settings for this object.
Definition at line 75 of file SetupInterface.h.
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), SetupInterface::getExecuteOnEnum(), JSONOutput::outputReporters(), XMLOutput::outputVectorPostprocessors(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
_factory
Factory& MooseBaseParameterInterface::_factory protected inherited
The Factory associated with the MooseApp.
Definition at line 161 of file MooseBaseParameterInterface.h.
Referenced by AddGeneralReactions::act(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), ElementIDOutputAction::act(), AddSpecies::act(), AdaptivityAction::act(), AddControlAction::act(), AddNodalNormalsAction::act(), AddPeriodicBCAction::act(), AutoCheckpointAction::act(), ComposeTimeStepperAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DisplayGhostingAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), PartitionerAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SetupPreconditionerAction::act(), SetupPredictorAction::act(), SetupResidualDebugAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddGeneralReactions::addEEDFReactionKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddDriftDiffusionAction::addPosition(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), MooseBaseParameterInterface::connectControllableParams(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), MaterialOutputAction::getParams(), and ProjectedStatefulMaterialStorageAction::processProperty().
_fe_problem
FEProblemBase& ResidualObject::_fe_problem protected inherited
Reference to this kernel's FEProblemBase.
Definition at line 129 of file ResidualObject.h.
Referenced by ADKernelTempl< T >::ADKernelTempl(), ArrayKernel::ArrayKernel(), ArrayNodalBC::computeJacobian(), NodalBC::computeJacobian(), VectorNodalBC::computeJacobian(), ArrayNodalBC::computeOffDiagJacobian(), NodalBC::computeOffDiagJacobian(), VectorNodalBC::computeOffDiagJacobian(), IntegratedBC::computeResidualAndJacobian(), NodalBC::computeResidualAndJacobian(), Kernel::computeResidualAndJacobian(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), ElectronsFromIonization::ElectronsFromIonization(), and Kernel::Kernel().
_fni_feproblem
FEProblemBase& FunctionInterface::_fni_feproblem private inherited
Reference to FEProblemBase instance.
Definition at line 84 of file FunctionInterface.h.
Referenced by FunctionInterface::getFunction(), FunctionInterface::getFunctionByName(), and FunctionInterface::hasFunctionByName().
_fni_params
const InputParameters& FunctionInterface::_fni_params private inherited
Parameters of the object with this interface.
Definition at line 81 of file FunctionInterface.h.
Referenced by FunctionInterface::getFunction(), and FunctionInterface::hasFunction().
_fni_tid
const THREAD_ID FunctionInterface::_fni_tid private inherited
Thread ID.
Definition at line 87 of file FunctionInterface.h.
Referenced by FunctionInterface::getFunction(), FunctionInterface::getFunctionByName(), and FunctionInterface::hasFunctionByName().
_generator
MooseRandom* RandomInterface::_generator mutable private inherited
Definition at line 74 of file RandomInterface.h.
Referenced by RandomInterface::getRandomLong(), RandomInterface::getRandomReal(), and RandomInterface::setRandomDataPointer().
_i
unsigned int ScalarKernelBase::_i protected inherited
Definition at line 53 of file ScalarKernelBase.h.
Referenced by ADScalarKernel::computeADJacobian(), ODEKernel::computeJacobian(), ScalarKernel::computeJacobian(), ODEKernel::computeOffDiagJacobianScalar(), LogStabilizationScalar::computeQpJacobian(), ODETimeDerivativeLog::computeQpJacobian(), Product1BodyScalar::computeQpJacobian(), Product1BodyScalarLog::computeQpJacobian(), Product2BodyScalar::computeQpJacobian(), Product2BodyScalarLog::computeQpJacobian(), Product3BodyScalar::computeQpJacobian(), Product3BodyScalarLog::computeQpJacobian(), Reactant3BodyScalar::computeQpJacobian(), Reactant3BodyScalarLog::computeQpJacobian(), ODETimeDerivativeTemperature::computeQpJacobian(), Reactant1BodyScalar::computeQpJacobian(), Reactant1BodyScalarLog::computeQpJacobian(), Reactant2BodyScalar::computeQpJacobian(), Reactant2BodyScalarLog::computeQpJacobian(), CoupledODETimeDerivative::computeQpJacobian(), computeQpJacobian(), EnergyTermScalar::computeQpOffDiagJacobian(), Product1BodyScalar::computeQpOffDiagJacobian(), Product1BodyScalarLog::computeQpOffDiagJacobian(), Product2BodyScalar::computeQpOffDiagJacobian(), Product2BodyScalarLog::computeQpOffDiagJacobian(), Product3BodyScalar::computeQpOffDiagJacobian(), Product3BodyScalarLog::computeQpOffDiagJacobian(), Reactant3BodyScalar::computeQpOffDiagJacobian(), Reactant3BodyScalarLog::computeQpOffDiagJacobian(), Reactant2BodyScalar::computeQpOffDiagJacobian(), Reactant2BodyScalarLog::computeQpOffDiagJacobian(), EnergyTermScalar::computeQpResidual(), LogStabilizationScalar::computeQpResidual(), ODETimeDerivativeLog::computeQpResidual(), Product1BodyScalar::computeQpResidual(), Product1BodyScalarLog::computeQpResidual(), Product2BodyScalar::computeQpResidual(), Product2BodyScalarLog::computeQpResidual(), Product3BodyScalar::computeQpResidual(), Product3BodyScalarLog::computeQpResidual(), Reactant3BodyScalar::computeQpResidual(), Reactant3BodyScalarLog::computeQpResidual(), ODETimeDerivativeTemperature::computeQpResidual(), Reactant1BodyScalar::computeQpResidual(), Reactant1BodyScalarLog::computeQpResidual(), Reactant2BodyScalar::computeQpResidual(), Reactant2BodyScalarLog::computeQpResidual(), ScalarDiffusion::computeQpResidual(), ADScalarTimeDerivative::computeQpResidual(), CoupledODETimeDerivative::computeQpResidual(), computeQpResidual(), ODEKernel::computeResidual(), ODETimeKernel::computeResidual(), ADScalarKernel::computeResidual(), ScalarKernel::computeResidual(), and ParsedODEKernel::updateParams().
_is_implicit
bool TransientInterface::_is_implicit protected inherited
If the object is using implicit or explicit form.
This does NOT mean time scheme, but which values are going to be used in the object - either from current time or old time. Note that even explicit schemes have implicit form (it is the time derivative "kernel")
Definition at line 58 of file TransientInterface.h.
Referenced by EigenKernel::computeJacobian(), EigenKernel::computeOffDiagJacobian(), IntegratedBC::computeResidualAndJacobian(), NodalBC::computeResidualAndJacobian(), Kernel::computeResidualAndJacobian(), TransientInterface::determineState(), EigenKernel::EigenKernel(), EigenKernel::enabled(), and TransientInterface::isImplicit().
_is_nodal
bool RandomInterface::_is_nodal private inherited
Definition at line 80 of file RandomInterface.h.
Referenced by RandomInterface::getRandomLong(), RandomInterface::getRandomReal(), and RandomInterface::isNodal().
_is_transient
bool TransientInterface::_is_transient protected inherited
Definition at line 73 of file TransientInterface.h.
Referenced by InterfaceTimeKernel::InterfaceTimeKernel().
_j
unsigned int ScalarKernelBase::_j protected inherited
Definition at line 53 of file ScalarKernelBase.h.
Referenced by ODEKernel::computeJacobian(), ODEKernel::computeOffDiagJacobianScalar(), ODETimeDerivativeLog::computeQpJacobian(), ODETimeDerivativeTemperature::computeQpJacobian(), CoupledODETimeDerivative::computeQpJacobian(), and computeQpJacobian().
_ke_blocks
std::vector<DenseMatrix<Number> *> TaggingInterface::_ke_blocks private inherited
Kernel blocks Vectors For each Tag.
Definition at line 390 of file TaggingInterface.h.
Referenced by TaggingInterface::accumulateTaggedLocalMatrix(), TaggingInterface::accumulateTaggedNonlocalMatrix(), TaggingInterface::assignTaggedLocalMatrix(), TaggingInterface::prepareMatrixTag(), TaggingInterface::prepareMatrixTagLower(), TaggingInterface::prepareMatrixTagNeighbor(), TaggingInterface::prepareMatrixTagNonlocal(), and TaggingInterface::TaggingInterface().
_local_ke
DenseMatrix<Number> TaggingInterface::_local_ke protected inherited
Holds local Jacobian entries as they are accumulated by this Kernel.
Definition at line 333 of file TaggingInterface.h.
Referenced by TaggingInterface::accumulateTaggedLocalMatrix(), TaggingInterface::assignTaggedLocalMatrix(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ArrayIntegratedBC::computeJacobian(), IntegratedBC::computeJacobian(), NonlocalIntegratedBC::computeJacobian(), VectorIntegratedBC::computeJacobian(), NodeElemConstraint::computeJacobian(), NodeFaceConstraint::computeJacobian(), ArrayKernel::computeJacobian(), EigenKernel::computeJacobian(), Kernel::computeJacobian(), KernelGrad::computeJacobian(), KernelValue::computeJacobian(), MassLumpedTimeDerivative::computeJacobian(), NonlocalKernel::computeJacobian(), ODEKernel::computeJacobian(), TimeDerivative::computeJacobian(), VectorKernel::computeJacobian(), VectorTimeDerivative::computeJacobian(), NodalEqualValueConstraint::computeJacobian(), ScalarKernel::computeJacobian(), MortarConstraint::computeJacobian(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ArrayIntegratedBC::computeOffDiagJacobian(), IntegratedBC::computeOffDiagJacobian(), NonlocalIntegratedBC::computeOffDiagJacobian(), VectorIntegratedBC::computeOffDiagJacobian(), NodeElemConstraint::computeOffDiagJacobian(), NodeFaceConstraint::computeOffDiagJacobian(), ArrayKernel::computeOffDiagJacobian(), EigenKernel::computeOffDiagJacobian(), Kernel::computeOffDiagJacobian(), KernelGrad::computeOffDiagJacobian(), KernelValue::computeOffDiagJacobian(), NonlocalKernel::computeOffDiagJacobian(), VectorKernel::computeOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), ArrayIntegratedBC::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), ArrayKernel::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), MortarScalarBase::computeScalarJacobian(), KernelScalarBase::computeScalarJacobian(), MortarScalarBase::computeScalarOffDiagJacobian(), KernelScalarBase::computeScalarOffDiagJacobian(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), ConservativeAdvection::fullUpwind(), TaggingInterface::prepareMatrixTag(), TaggingInterface::prepareMatrixTagLower(), and TaggingInterface::prepareMatrixTagNeighbor().
_local_re
DenseVector<Number> TaggingInterface::_local_re protected inherited
Holds local residual entries as they are accumulated by this Kernel.
Definition at line 330 of file TaggingInterface.h.
Referenced by TaggingInterface::accumulateTaggedLocalResidual(), FVInterfaceKernel::addResidual(), TaggingInterface::assignTaggedLocalResidual(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDResidual(), DGLowerDKernel::computeLowerDResidual(), ArrayIntegratedBC::computeResidual(), ArrayLowerDIntegratedBC::computeResidual(), IntegratedBC::computeResidual(), LowerDIntegratedBC::computeResidual(), VectorIntegratedBC::computeResidual(), NodeElemConstraint::computeResidual(), NodeFaceConstraint::computeResidual(), FVElementalKernel::computeResidual(), ArrayKernel::computeResidual(), EigenKernel::computeResidual(), Kernel::computeResidual(), KernelGrad::computeResidual(), KernelValue::computeResidual(), ODEKernel::computeResidual(), ODETimeKernel::computeResidual(), TimeKernel::computeResidual(), VectorKernel::computeResidual(), VectorTimeKernel::computeResidual(), ADScalarKernel::computeResidual(), NodalEqualValueConstraint::computeResidual(), ScalarKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVFluxBC::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), ADMortarConstraint::computeResidual(), MortarConstraint::computeResidual(), ConservativeAdvection::fullUpwind(), TaggingInterface::prepareVectorTagInternal(), TaggingInterface::prepareVectorTagLower(), and TaggingInterface::prepareVectorTagNeighbor().
_master_seed
unsigned int RandomInterface::_master_seed private inherited
Definition at line 79 of file RandomInterface.h.
Referenced by RandomInterface::getMasterSeed().
_matrix_tags
std::set<TagID> TaggingInterface::_matrix_tags private inherited
The matrices this Kernel will contribute to.
Definition at line 357 of file TaggingInterface.h.
Referenced by TaggingInterface::accumulateTaggedLocalMatrix(), TaggingInterface::addJacobian(), TaggingInterface::addJacobianElement(), TaggingInterface::addJacobianWithoutConstraints(), TaggingInterface::getMatrixTags(), TaggingInterface::isMatrixTagged(), TaggingInterface::prepareMatrixTag(), TaggingInterface::prepareMatrixTagLower(), TaggingInterface::prepareMatrixTagNeighbor(), TaggingInterface::prepareMatrixTagNonlocal(), TaggingInterface::TaggingInterface(), and TaggingInterface::useMatrixTag().
_mci_feproblem
FEProblemBase& MeshChangedInterface::_mci_feproblem protected inherited
Reference to FEProblemBase instance.
Definition at line 38 of file MeshChangedInterface.h.
Referenced by MeshChangedInterface::MeshChangedInterface().
_mesh
MooseMesh& ResidualObject::_mesh protected inherited
Reference to this Kernel's mesh object.
Definition at line 141 of file ResidualObject.h.
Referenced by DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), FVFluxKernel::adjustRMGhostLayers(), LowerBoundNodalKernel::computeQpJacobian(), UpperBoundNodalKernel::computeQpJacobian(), LowerBoundNodalKernel::computeQpOffDiagJacobian(), UpperBoundNodalKernel::computeQpOffDiagJacobian(), LowerBoundNodalKernel::computeQpResidual(), UpperBoundNodalKernel::computeQpResidual(), DGKernelBase::DGKernelBase(), DGKernelBase::excludeBoundary(), NodeElemConstraint::getConnectedDofIndices(), NodeFaceConstraint::getConnectedDofIndices(), DiracKernelBase::hasPointsOnElem(), LinearNodalConstraint::LinearNodalConstraint(), LowerBoundNodalKernel::LowerBoundNodalKernel(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalScalarKernel::NodalScalarKernel(), NodeElemConstraint::NodeElemConstraint(), NonlocalIntegratedBC::NonlocalIntegratedBC(), NonlocalKernel::NonlocalKernel(), PenaltyCircuitPotential::PenaltyCircuitPotential(), EqualValueEmbeddedConstraint::prepareSecondaryToPrimaryMap(), FVPointValueConstraint::setMyElem(), EqualValueEmbeddedConstraint::shouldApply(), EqualValueBoundaryConstraint::updateConstrainedNodes(), and UpperBoundNodalKernel::UpperBoundNodalKernel().
_metaname
const RestartableDataMapName Restartable::_metaname private inherited
Restartable metadata name.
Definition at line 240 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_moose_base
const MooseBase* const MooseBaseParameterInterface::_moose_base private inherited
The MooseBase object that inherits this class.
Definition at line 168 of file MooseBaseParameterInterface.h.
Referenced by MooseBaseParameterInterface::connectControllableParams(), MooseBaseParameterInterface::objectErrorPrefix(), MooseBaseParameterInterface::paramError(), and MooseBaseParameterInterface::uniqueParameterName().
_moose_object
const MooseObject& TaggingInterface::_moose_object private inherited
Moose objct this tag works on.
Definition at line 378 of file TaggingInterface.h.
Referenced by TaggingInterface::TaggingInterface().
_name
const std::string& MooseBase::_name protected inherited
The name of this class, reference to value stored in InputParameters.
Definition at line 66 of file MooseBase.h.
Referenced by AddFieldSplitAction::act(), AddBCAction::act(), AddConstraintAction::act(), AddControlAction::act(), AddDamperAction::act(), AddDGKernelAction::act(), AddDiracKernelAction::act(), AddDistributionAction::act(), AddFunctionAction::act(), AddFunctorMaterialAction::act(), AddFVBCAction::act(), AddFVInitialConditionAction::act(), AddFVInterfaceKernelAction::act(), AddFVKernelAction::act(), AddIndicatorAction::act(), AddInitialConditionAction::act(), AddInterfaceKernelAction::act(), AddKernelAction::act(), AddMarkerAction::act(), AddMaterialAction::act(), AddMeshDivisionAction::act(), AddMeshGeneratorAction::act(), AddMultiAppAction::act(), AddNodalKernelAction::act(), AddOutputAction::act(), AddPeriodicBCAction::act(), AddPositionsAction::act(), AddPostprocessorAction::act(), AddReporterAction::act(), AddSamplerAction::act(), AddScalarKernelAction::act(), AddTimesAction::act(), AddTimeStepperAction::act(), AddTransferAction::act(), AddUserObjectAction::act(), AddVectorPostprocessorAction::act(), PartitionerAction::act(), ReadExecutorParamsAction::act(), SetupPreconditionerAction::act(), SetupTimeIntegratorAction::act(), AddDriftDiffusionAction::addADKernels(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromXY(), PiecewiseLinearBase::buildInterpolation(), CombinerGenerator::CombinerGenerator(), Executor::Executor(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), FunctionDT::FunctionDT(), FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), MooseBase::name(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), PiecewiseBase::setData(), and Split::setup().
_non_ref_abs_vector_tags
std::set<TagID> TaggingInterface::_non_ref_abs_vector_tags private inherited
A set to hold absolute value vector tags excluding the reference residual tag.
If there is no reference residual problem, this container is the same as _abs_vector_tags;
Definition at line 365 of file TaggingInterface.h.
Referenced by TaggingInterface::prepareVectorTag(), and TaggingInterface::TaggingInterface().
_non_ref_vector_tags
std::set<TagID> TaggingInterface::_non_ref_vector_tags private inherited
A set to hold vector tags excluding the reference residual tag.
If there is no reference residual problem, this container is the same as _vector_tags;
Definition at line 361 of file TaggingInterface.h.
Referenced by TaggingInterface::prepareVectorTag(), and TaggingInterface::TaggingInterface().
_nonlocal_ke
DenseMatrix<Number> TaggingInterface::_nonlocal_ke protected inherited
Holds nonlocal Jacobian entries as they are accumulated by this Kernel.
Definition at line 336 of file TaggingInterface.h.
Referenced by TaggingInterface::accumulateTaggedNonlocalMatrix(), NonlocalIntegratedBC::computeNonlocalJacobian(), NonlocalKernel::computeNonlocalJacobian(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), and TaggingInterface::prepareMatrixTagNonlocal().
_parent
const MooseObject & DataFileInterface< MooseObject >::_parent private inherited
Definition at line 46 of file DataFileInterface.h.
_pars
const InputParameters& MooseBaseParameterInterface::_pars protected inherited
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Definition at line 158 of file MooseBaseParameterInterface.h.
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), AddPeriodicBCAction::act(), AddVariableAction::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), FunctorMaterial::addFunctorPropertyByBlocks(), FVFluxKernel::adjustRMGhostLayers(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), PiecewiseTabularBase::buildFromFile(), PNGOutput::calculateRescalingValues(), BlockWeightedPartitioner::clone(), GridPartitioner::clone(), HierarchicalGridPartitioner::clone(), PetscExternalPartitioner::clone(), RandomPartitioner::clone(), SingleRankPartitioner::clone(), MooseBaseParameterInterface::connectControllableParams(), Console::Console(), AddVariableAction::createInitialConditionAction(), MaterialBase::declareADProperty(), MaterialBase::declareProperty(), FEProblemSolve::FEProblemSolve(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), FileMeshGenerator::generate(), MaterialBase::getGenericZeroMaterialProperty(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getParam(), MooseBaseParameterInterface::getRenamedParam(), AddVariableAction::init(), AdvancedOutput::initExecutionTypes(), Console::initialSetup(), MooseBaseParameterInterface::isParamSetByUser(), MooseBaseParameterInterface::isParamValid(), MultiApp::keepSolutionDuringRestore(), MooseBaseParameterInterface::paramErrorMsg(), GlobalParamsAction::parameters(), MooseBaseParameterInterface::parameters(), MooseMesh::prepare(), Eigenvalue::prepareSolverOptions(), MooseMesh::setCoordSystem(), MooseMesh::setPartitionerHelper(), SetupMeshAction::setupMesh(), Transient::setupTimeIntegrator(), MooseBaseParameterInterface::uniqueName(), and MooseBaseParameterInterface::uniqueParameterName().
_point_zero
const Point& ScalarCoupleable::_point_zero protected inherited
Zero point.
Definition at line 233 of file ScalarCoupleable.h.
Referenced by FunctionDT::computeDT(), FunctionScalarAux::computeValue(), and FunctionScalarIC::value().
_ppi_feproblem
const FEProblemBase& PostprocessorInterface::_ppi_feproblem private inherited
Reference the the FEProblemBase class.
Definition at line 151 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::hasPostprocessorByName(), PostprocessorInterface::isDefaultPostprocessorValueByName(), and PostprocessorInterface::postprocessorsAdded().
_ppi_moose_object
const MooseObject& PostprocessorInterface::_ppi_moose_object private inherited
The MooseObject that uses this interface.
Definition at line 145 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::checkParam(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), and PostprocessorInterface::hasPostprocessorByName().
_ppi_params
const InputParameters& PostprocessorInterface::_ppi_params private inherited
PostprocessorInterface Parameters.
Definition at line 148 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::checkParam(), PostprocessorInterface::coupledPostprocessors(), and PostprocessorInterface::getPostprocessorNameInternal().
_random_data
RandomData* RandomInterface::_random_data private inherited
Definition at line 73 of file RandomInterface.h.
Referenced by RandomInterface::getSeed(), and RandomInterface::setRandomDataPointer().
_re_blocks
std::vector<DenseVector<Number> *> TaggingInterface::_re_blocks private inherited
Residual blocks Vectors For each Tag.
Definition at line 384 of file TaggingInterface.h.
Referenced by TaggingInterface::accumulateTaggedLocalResidual(), TaggingInterface::assignTaggedLocalResidual(), TaggingInterface::prepareVectorTagInternal(), TaggingInterface::prepareVectorTagLower(), TaggingInterface::prepareVectorTagNeighbor(), and TaggingInterface::TaggingInterface().
_real_zero
const Real& ScalarCoupleable::_real_zero protected inherited
Scalar zero.
Definition at line 227 of file ScalarCoupleable.h.
_ref_abs_vector_tags
std::set<TagID> TaggingInterface::_ref_abs_vector_tags private inherited
A set of either size 1 or 0.
If we have a reference residual problem and _abs_vector_tags holds the reference vector tag, then this set holds the reference vector tags, otherwise it holds nothing
Definition at line 375 of file TaggingInterface.h.
Referenced by TaggingInterface::prepareVectorTag(), and TaggingInterface::TaggingInterface().
_ref_vector_tags
std::set<TagID> TaggingInterface::_ref_vector_tags private inherited
A set of either size 1 or 0.
If we have a reference residual problem and _vector_tags holds the reference vector tag, then this set holds the reference vector tags, otherwise it holds nothing
Definition at line 370 of file TaggingInterface.h.
Referenced by TaggingInterface::prepareVectorTag(), and TaggingInterface::TaggingInterface().
_reset_on
ExecFlagType RandomInterface::_reset_on private inherited
Definition at line 81 of file RandomInterface.h.
Referenced by RandomInterface::getResetOnTime(), and RandomInterface::setRandomResetFrequency().
_restartable_app
MooseApp& Restartable::_restartable_app protected inherited
Reference to the application.
Definition at line 227 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp(), and Restartable::registerRestartableNameWithFilterOnApp().
_restartable_name
std::string Restartable::_restartable_name private inherited
The name of the object.
Definition at line 243 of file Restartable.h.
Referenced by Restartable::declareRestartableDataWithObjectNameWithContext(), and Restartable::restartableName().
_restartable_read_only
const bool Restartable::_restartable_read_only protected inherited
Flag for toggling read only status (see ReporterData)
Definition at line 236 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_restartable_system_name
const std::string Restartable::_restartable_system_name protected inherited
The system name this object is in.
Definition at line 230 of file Restartable.h.
Referenced by Restartable::restartableName().
_restartable_tid
const THREAD_ID Restartable::_restartable_tid protected inherited
The thread ID for this object.
Definition at line 233 of file Restartable.h.
Referenced by Restartable::declareRestartableDataHelper().
_ri_name
const std::string RandomInterface::_ri_name private inherited
Definition at line 77 of file RandomInterface.h.
Referenced by RandomInterface::setRandomResetFrequency().
_ri_problem
FEProblemBase& RandomInterface::_ri_problem private inherited
Definition at line 76 of file RandomInterface.h.
Referenced by RandomInterface::setRandomResetFrequency().
_sc_coupleable_matrix_tags
std::set<TagID> ScalarCoupleable::_sc_coupleable_matrix_tags mutable private inherited
The scalar coupleable matrix tags.
Definition at line 294 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::coupledMatrixTagScalarValue(), and ScalarCoupleable::getScalarVariableCoupleableMatrixTags().
_sc_coupleable_vector_tags
std::set<TagID> ScalarCoupleable::_sc_coupleable_vector_tags mutable private inherited
The scalar coupleable vector tags.
Definition at line 292 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::coupledVectorTagScalarValue(), and ScalarCoupleable::getScalarVariableCoupleableVectorTags().
_sc_coupled_vars
std::unordered_map<std::string, std::vector<MooseVariableFieldBase *> > ScalarCoupleable::_sc_coupled_vars private inherited
Field variables coupled into this object (for error checking)
Definition at line 289 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::checkVar(), and ScalarCoupleable::ScalarCoupleable().
_sc_fe_problem
FEProblemBase& ScalarCoupleable::_sc_fe_problem protected inherited
Definition at line 221 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::coupledScalarOrder(), ScalarCoupleable::coupledVectorTagScalarValue(), ScalarCoupleable::getADDefaultValue(), ScalarCoupleable::getDefaultValue(), and ScalarCoupleable::validateExecutionerType().
_sc_is_implicit
const bool ScalarCoupleable::_sc_is_implicit private inherited
True if implicit value is required.
Definition at line 274 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::adCoupledScalarValue(), ScalarCoupleable::coupledScalarValue(), ScalarCoupleable::coupledScalarValueOld(), and ScalarCoupleable::coupledScalarValueOlder().
_sc_name
const std::string& ScalarCoupleable::_sc_name private inherited
The name of the object this interface is part of.
Definition at line 271 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::checkVar(), ScalarCoupleable::coupledScalarComponents(), ScalarCoupleable::coupledVectorTagScalarValue(), ScalarCoupleable::getScalarVar(), ScalarCoupleable::isCoupledScalar(), ScalarCoupleable::ScalarCoupleable(), and ScalarCoupleable::validateExecutionerType().
_sc_parameters
const InputParameters& ScalarCoupleable::_sc_parameters private inherited
Definition at line 268 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::checkVar(), ScalarCoupleable::coupledScalarComponents(), ScalarCoupleable::getADDefaultValue(), ScalarCoupleable::getDefaultValue(), ScalarCoupleable::getScalarVar(), ScalarCoupleable::isCoupledScalar(), and ScalarCoupleable::ScalarCoupleable().
_sc_tid
const THREAD_ID ScalarCoupleable::_sc_tid protected inherited
Thread ID of the thread using this object.
Definition at line 224 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::ScalarCoupleable().
_scalar_zero
const VariableValue& ScalarCoupleable::_scalar_zero protected inherited
Zero value of a scalar variable.
Definition at line 230 of file ScalarCoupleable.h.
_subproblem
SubProblem& ResidualObject::_subproblem protected inherited
Reference to this kernel's SubProblem.
Definition at line 126 of file ResidualObject.h.
Referenced by ADDGKernel::ADDGKernel(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADInterfaceKernelTempl< T >::ADInterfaceKernelTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), DGKernel::DGKernel(), FVKernel::FVKernel(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), LinearNodalConstraint::LinearNodalConstraint(), NodalBC::NodalBC(), NodalKernel::NodalKernel(), NeighborResidualObject::prepareNeighborShapes(), EqualValueEmbeddedConstraint::prepareSecondaryToPrimaryMap(), ResidualObject::prepareShapes(), IntegratedBCBase::prepareShapes(), DGKernelBase::prepareShapes(), InterfaceKernelBase::prepareShapes(), NodalScalarKernel::reinit(), ResidualObject::subProblem(), and EqualValueBoundaryConstraint::updateConstrainedNodes().
_sys
SystemBase& ResidualObject::_sys protected inherited
Reference to the EquationSystem object.
Definition at line 132 of file ResidualObject.h.
Referenced by ADDGKernel::ADDGKernel(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayKernel::ArrayKernel(), ArrayNodalBC::computeJacobian(), NodalBC::computeJacobian(), VectorNodalBC::computeJacobian(), MortarScalarBase::computeJacobian(), EigenKernel::computeJacobian(), Kernel::computeJacobian(), ODEKernel::computeJacobian(), VectorKernel::computeJacobian(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), ArrayNodalBC::computeOffDiagJacobian(), NodalBC::computeOffDiagJacobian(), VectorNodalBC::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), ArrayIntegratedBC::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), ArrayKernel::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), EqualValueEmbeddedConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayNodalBC::computeResidual(), NodalBC::computeResidual(), VectorNodalBC::computeResidual(), IntegratedBC::computeResidualAndJacobian(), NodalBC::computeResidualAndJacobian(), Kernel::computeResidualAndJacobian(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), DGKernel::DGKernel(), NodeElemConstraint::getConnectedDofIndices(), NodeFaceConstraint::getConnectedDofIndices(), ResidualObject::getVariable(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), EqualValueEmbeddedConstraint::reinitConstraint(), ScalarKernelBase::uOld(), and MortarConstraintBase::zeroInactiveLMDofs().
_t
Real& TransientInterface::_t protected inherited
Time.
Definition at line 61 of file TransientInterface.h.
Referenced by FVFunctionDirichletBC::boundaryValue(), AnalyticalDiffIndicator::computeQpIntegral(), AnalyticalIndicator::computeQpIntegral(), ElementH1SemiError::computeQpIntegral(), ElementL1Error::computeQpIntegral(), ElementL2Error::computeQpIntegral(), ElementVectorL2Error::computeQpIntegral(), ElementW1pError::computeQpIntegral(), FunctionElementIntegral::computeQpIntegral(), FunctionSideIntegral::computeQpIntegral(), FunctionElementIntegralUserObject::computeQpIntegral(), FunctionDiffusion::computeQpJacobian(), VectorFunctionReaction::computeQpJacobian(), VelocityFunctionOutflowBC::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), Gas::computeQpProperties(), GasBase::computeQpProperties(), GasElectronMoments::computeQpProperties(), FieldEmissionBC::computeQpResidual(), NeumannCircuitVoltageMoles_KV::computeQpResidual(), NeumannCircuitVoltageNew::computeQpResidual(), SchottkyEmissionBC::computeQpResidual(), TM0AntennaVertBC::computeQpResidual(), ADConservativeAdvectionBC::computeQpResidual(), ADFunctionNeumannBC::computeQpResidual(), ADFunctionPenaltyDirichletBC::computeQpResidual(), ADVectorFunctionNeumannBC::computeQpResidual(), ConvectiveFluxBC::computeQpResidual(), DGFunctionDiffusionDirichletBC::computeQpResidual(), FunctionGradientNeumannBC::computeQpResidual(), FunctionNeumannBC::computeQpResidual(), FunctionPenaltyDirichletBC::computeQpResidual(), SinDirichletBC::computeQpResidual(), SinNeumannBC::computeQpResidual(), VectorCurlPenaltyDirichletBC::computeQpResidual(), VectorDivPenaltyDirichletBC::computeQpResidual(), VectorFunctionDirichletBC::computeQpResidual(), VectorPenaltyDirichletBC::computeQpResidual(), FunctionDiracSource::computeQpResidual(), FVFunctionNeumannBC::computeQpResidual(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), FVBodyForce::computeQpResidual(), FunctionDiffusion::computeQpResidual(), VectorBodyForce::computeQpResidual(), VectorFunctionReaction::computeQpResidual(), UserForcingFunctionNodalKernel::computeQpResidual(), VelocityFunctionOutflowBC::computeQpResidual(), DGFunctionConvection::computeQpResidual(), ArrayBodyForce::computeQpResidual(), FunctionDirichletBC::computeQpValue(), DataRead::computeValue(), ScalarLinearInterpolation::computeValue(), ScalarSplineInterpolation::computeValue(), ArrayParsedAux::computeValue(), ElementH1ErrorFunctionAux::computeValue(), ElementL2ErrorFunctionAux::computeValue(), ForcingFunctionAux::computeValue(), FunctionArrayAux::computeValue(), FunctionAux::computeValue(), FunctionScalarAux::computeValue(), ParsedAux::computeValue(), ParsedVectorAux::computeValue(), SolutionAux::computeValue(), SolutionScalarAux::computeValue(), VectorFunctionAux::computeValue(), FunctionDerivativeAux::computeValue(), ConditionalFunctionEnableControl::conditionMet(), TimePeriod::conditionMet(), BoltzmannSolverScalar::execute(), BoolFunctionControl::execute(), PIDTransientControl::execute(), RealFunctionControl::execute(), NodalL2Error::execute(), TimeExtremeValue::execute(), IterationInfo::execute(), LeastSquaresFitHistory::execute(), LineFunctionSampler::execute(), UserForcingFunction::f(), ParsedPostprocessor::finalize(), FunctionValuePostprocessor::getValue(), ScalarL2Error::getValue(), BoltzmannSolverScalar::initialize(), ActivateElementsByPath::isElementActivated(), and SolutionUserObject::timestepSetup().
_t_step
int& TransientInterface::_t_step protected inherited
The number of the time step.
Definition at line 64 of file TransientInterface.h.
Referenced by PIDTransientControl::execute(), AccumulateReporter::execute(), IterationInfo::execute(), ChangeOverFixedPointPostprocessor::finalize(), and ChangeOverTimePostprocessor::finalize().
_tag_params
const InputParameters& TaggingInterface::_tag_params private inherited
Parameters from moose object.
Definition at line 381 of file TaggingInterface.h.
Referenced by TaggingInterface::TaggingInterface().
_ti_feproblem
FEProblemBase& TransientInterface::_ti_feproblem protected inherited
Definition at line 50 of file TransientInterface.h.
Referenced by Function::evaluate(), Function::evaluateDotHelper(), Function::evaluateGradientHelper(), Function::evaluateHelper(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), and SolutionFunction::SolutionFunction().
_ti_name
const std::string TransientInterface::_ti_name private inherited
Definition at line 76 of file TransientInterface.h.
_ti_params
const InputParameters& TransientInterface::_ti_params protected inherited
Definition at line 48 of file TransientInterface.h.
_tid
THREAD_ID ResidualObject::_tid protected inherited
The thread ID for this kernel.
Definition at line 135 of file ResidualObject.h.
Referenced by ADDGKernel::ADDGKernel(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ODEKernel::computeJacobian(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), ArrayIntegratedBC::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), ArrayKernel::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), IntegratedBC::computeResidualAndJacobian(), NodalBC::computeResidualAndJacobian(), Kernel::computeResidualAndJacobian(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), DGKernel::DGKernel(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), ResidualObject::getVariable(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), NodalBC::NodalBC(), NodalKernel::NodalKernel(), NeighborResidualObject::prepareNeighborShapes(), ResidualObject::prepareShapes(), IntegratedBCBase::prepareShapes(), DGKernelBase::prepareShapes(), InterfaceKernelBase::prepareShapes(), and NodalScalarKernel::reinit().
_type
const std::string& MooseBase::_type protected inherited
The type of this class.
Definition at line 63 of file MooseBase.h.
Referenced by FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), FEProblemBase::init(), FEProblemBase::solverTypeString(), and MooseBase::type().
_u
const VariableValue& ScalarKernel::_u protected inherited
The current solution (old solution if explicit)
Definition at line 28 of file ScalarKernel.h.
Referenced by LogStabilizationScalar::computeQpJacobian(), ODETimeDerivativeLog::computeQpJacobian(), Reactant3BodyScalar::computeQpJacobian(), Reactant3BodyScalarLog::computeQpJacobian(), Reactant1BodyScalarLog::computeQpJacobian(), Reactant2BodyScalar::computeQpJacobian(), Reactant2BodyScalarLog::computeQpJacobian(), Reactant3BodyScalar::computeQpOffDiagJacobian(), Reactant3BodyScalarLog::computeQpOffDiagJacobian(), Reactant2BodyScalar::computeQpOffDiagJacobian(), Reactant2BodyScalarLog::computeQpOffDiagJacobian(), LogStabilizationScalar::computeQpResidual(), ODETimeDerivativeLog::computeQpResidual(), Reactant3BodyScalar::computeQpResidual(), Reactant3BodyScalarLog::computeQpResidual(), Reactant1BodyScalar::computeQpResidual(), Reactant1BodyScalarLog::computeQpResidual(), Reactant2BodyScalar::computeQpResidual(), Reactant2BodyScalarLog::computeQpResidual(), ScalarDiffusion::computeQpResidual(), and ParsedODEKernel::updateParams().
_u_dot
const VariableValue& ODETimeKernel::_u_dot protected inherited
Time derivative of u.
Definition at line 29 of file ODETimeKernel.h.
Referenced by ODETimeDerivativeLog::computeQpJacobian(), ODETimeDerivativeLog::computeQpResidual(), ODETimeDerivativeTemperature::computeQpResidual(), and computeQpResidual().
_uoi_feproblem
const FEProblemBase& UserObjectInterface::_uoi_feproblem private inherited
Reference to the FEProblemBase instance.
Definition at line 128 of file UserObjectInterface.h.
Referenced by UserObjectInterface::getUserObjectBaseByName(), and UserObjectInterface::hasUserObjectByName().
_uoi_moose_object
const MooseObject& UserObjectInterface::_uoi_moose_object private inherited
Moose object using the interface.
Definition at line 125 of file UserObjectInterface.h.
Referenced by UserObjectInterface::castUserObject(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), and UserObjectInterface::getUserObjectName().
_uoi_tid
const THREAD_ID UserObjectInterface::_uoi_tid private inherited
Thread ID.
Definition at line 131 of file UserObjectInterface.h.
Referenced by UserObjectInterface::getUserObjectBaseByName().
_var
MooseVariableScalar& ScalarKernelBase::_var protected inherited
Scalar variable.
Definition at line 51 of file ScalarKernelBase.h.
Referenced by ADScalarKernel::computeADJacobian(), ODEKernel::computeJacobian(), NodalEqualValueConstraint::computeJacobian(), ScalarKernel::computeJacobian(), NodalScalarKernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ODEKernel::computeResidual(), ODETimeKernel::computeResidual(), ADScalarKernel::computeResidual(), NodalEqualValueConstraint::computeResidual(), ScalarKernel::computeResidual(), ParsedODEKernel::ParsedODEKernel(), ScalarKernelBase::uOld(), and ScalarKernelBase::variable().
_vector_tags
std::set<TagID> TaggingInterface::_vector_tags private inherited
The residual tag ids this Kernel will contribute to.
Definition at line 351 of file TaggingInterface.h.
Referenced by TaggingInterface::addResiduals(), TaggingInterface::addResidualsWithoutConstraints(), TaggingInterface::getVectorTags(), TaggingInterface::isVectorTagged(), TaggingInterface::prepareVectorTag(), TaggingInterface::prepareVectorTagLower(), TaggingInterface::prepareVectorTagNeighbor(), TaggingInterface::setResidual(), TaggingInterface::TaggingInterface(), and TaggingInterface::useVectorTag().
_vpi_feproblem
const FEProblemBase& VectorPostprocessorInterface::_vpi_feproblem private inherited
Reference the FEProblemBase class.
Definition at line 358 of file VectorPostprocessorInterface.h.
Referenced by VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), VectorPostprocessorInterface::isVectorPostprocessorDistributedByName(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
_vpi_moose_object
const MooseObject& VectorPostprocessorInterface::_vpi_moose_object private inherited
The MooseObject that uses this interface.
Definition at line 355 of file VectorPostprocessorInterface.h.
Referenced by VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper(), VectorPostprocessorInterface::getVectorPostprocessorName(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), and VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName().
_vpi_tid
const THREAD_ID VectorPostprocessorInterface::_vpi_tid private inherited
Thread ID.
Definition at line 361 of file VectorPostprocessorInterface.h.
The documentation for this class was generated from the following files:
moose/framework/include/scalarkernels/ODETimeDerivative.h
moose/framework/src/scalarkernels/ODETimeDerivative.C