Zapdos: VectorPostprocessorInterface Class Reference
VectorPostprocessorInterface Class Reference
#include <VectorPostprocessorInterface.h>
Public Member Functions
VectorPostprocessorInterface (const MooseObject *moose_object, bool broadcast_by_default=false)
Constructor.
virtual ~VectorPostprocessorInterface ()=default
This class has virtual methods, so it needs a virtual dtor.
const VectorPostprocessorValue & getVectorPostprocessorValue (const std::string &param_name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValueByName (const VectorPostprocessorName &name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValueOld (const std::string &param_name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValueOldByName (const VectorPostprocessorName &name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValue (const std::string &param_name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the value of a VectorPostprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValueByName (const VectorPostprocessorName &name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the value of the VectorPostprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValueOld (const std::string &param_name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the old value of a VectorPostprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValueOldByName (const VectorPostprocessorName &name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the old value of a VectorPostprocessor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValue (const std::string &param_name, const std::string &vector_name) const
Return the scatter value for the post processor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValueByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Return the scatter value for the post processor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValueOld (const std::string &param_name, const std::string &vector_name) const
Return the old scatter value for the post processor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValueOldByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Return the old scatter value for the post processor.
bool hasVectorPostprocessor (const std::string &param_name, const std::string &vector_name) const
Determine if the VectorPostprocessor data exists by parameter.
bool hasVectorPostprocessorByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Determine if the VectorPostprocessor data exists by name.
bool hasVectorPostprocessor (const std::string &param_name) const
Determine if the VectorPostprocessor exists by parameter.
bool hasVectorPostprocessorByName (const VectorPostprocessorName &name) const
Determine if the VectorPostprocessor exists by name.
const VectorPostprocessorName & getVectorPostprocessorName (const std::string &param_name) const
Get the name of a VectorPostprocessor associated with a parameter.
bool isVectorPostprocessorDistributed (const std::string &param_name) const
Return true if the VectorPostprocessor is marked with parallel_type as DISTRIBUTED.
bool isVectorPostprocessorDistributedByName (const VectorPostprocessorName &name) const
Static Public Member Functions
static InputParameters validParams ()
Protected Member Functions
virtual void addVectorPostprocessorDependencyHelper (const VectorPostprocessorName &) const
Helper for deriving classes to override to add dependencies when a VectorPostprocessor is requested.
Private Member Functions
const VectorPostprocessorValue & getVectorPostprocessorByNameHelper (const VectorPostprocessorName &name, const std::string &vector_name, bool broadcast, std::size_t t_index) const
Helper function for extracting VPP data from ReporterData object.
const VectorPostprocessorContext< VectorPostprocessorValue > & getVectorPostprocessorContextByNameHelper (const VectorPostprocessorName &name, const std::string &vector_name) const
Helper for getting the VPP context that handles scatter values.
bool vectorPostprocessorsAdded () const
void possiblyCheckHasVectorPostprocessor (const std::string &param_name, const std::string &vector_name) const
Helpers for "possibly" checking if a vpp exists.
void possiblyCheckHasVectorPostprocessorByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Private Attributes
const bool _broadcast_by_default
Whether or not to force broadcasting by default.
const MooseObject & _vpi_moose_object
The MooseObject that uses this interface.
const FEProblemBase & _vpi_feproblem
Reference the FEProblemBase class.
const THREAD_ID _vpi_tid
Thread ID.
Detailed Description
Definition at line 22 of file VectorPostprocessorInterface.h.
Constructor & Destructor Documentation
VectorPostprocessorInterface()
VectorPostprocessorInterface::VectorPostprocessorInterface (const MooseObject * moose_object, bool broadcast_by_default = false)
Constructor.
Parameters
broadcast_by_default Set to true if the system inheriting from this interface always needs the VPPs to be broadcast
Definition at line 23 of file VectorPostprocessorInterface.C.
  : _broadcast_by_default(broadcast_by_default),
    _vpi_moose_object(*moose_object),
    _vpi_feproblem(*_vpi_moose_object.parameters().getCheckedPointerParam<FEProblemBase *>(
        "_fe_problem_base")),
    _vpi_tid(_vpi_moose_object.parameters().have_parameter<THREAD_ID>("_tid")
                 ? _vpi_moose_object.parameters().get<THREAD_ID>("_tid")
                 : 0)
{
}
~VectorPostprocessorInterface()
virtual VectorPostprocessorInterface::~VectorPostprocessorInterface () virtual default
This class has virtual methods, so it needs a virtual dtor.
Member Function Documentation
addVectorPostprocessorDependencyHelper()
virtual void VectorPostprocessorInterface::addVectorPostprocessorDependencyHelper (const VectorPostprocessorName &) const inline protected virtual
Helper for deriving classes to override to add dependencies when a VectorPostprocessor is requested.
Reimplemented in UserObject, AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, and AuxKernelTempl< RealVectorValue >.
Definition at line 311 of file VectorPostprocessorInterface.h.
  {
  }
Referenced by getVectorPostprocessorByNameHelper(), and getVectorPostprocessorContextByNameHelper().
getScatterVectorPostprocessorValue()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValue (const std::string & param_name, const std::string & vector_name) const
Return the scatter value for the post processor.
This is only valid when you expec the vector to be of lenghth "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
param_name The name of the parameter holding the vpp name
vector_name The name of the vector
Returns
The reference to the current scatter value
Definition at line 106 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getScatterVectorPostprocessorValueByName(getVectorPostprocessorName(param_name),
                                                  vector_name);
}
getScatterVectorPostprocessorValueByName()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValueByName (const VectorPostprocessorName & name, const std::string & vector_name) const
Return the scatter value for the post processor.
This is only valid when you expec the vector to be of lenghth "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
name The name of the VectorPostprocessor
vector_name The name of the vector
Returns
The reference to the current scatter value
Definition at line 115 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorContextByNameHelper(name, vector_name).getScatterValue();
}
Referenced by getScatterVectorPostprocessorValue().
getScatterVectorPostprocessorValueOld()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValueOld (const std::string & param_name, const std::string & vector_name) const
Return the old scatter value for the post processor.
This is only valid when you expec the vector to be of lenghth "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
param_name The name of the parameter holding the vpp name
vector_name The name of the vector
Returns
The reference to the old scatter value
Definition at line 122 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getScatterVectorPostprocessorValueOldByName(getVectorPostprocessorName(param_name),
                                                     vector_name);
}
getScatterVectorPostprocessorValueOldByName()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValueOldByName (const VectorPostprocessorName & name, const std::string & vector_name) const
Return the old scatter value for the post processor.
This is only valid when you expect the vector to be of length "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
name The name of the VectorPostprocessor
vector_name The name of the vector
Returns
The reference to the old scatter value
Definition at line 131 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorContextByNameHelper(name, vector_name).getScatterValueOld();
}
Referenced by getScatterVectorPostprocessorValueOld().
getVectorPostprocessorByNameHelper()
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorByNameHelper (const VectorPostprocessorName & name, const std::string & vector_name, bool broadcast, std::size_t t_index) const private
Helper function for extracting VPP data from ReporterData object.
Definition at line 269 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessorByName(name, vector_name);
  addVectorPostprocessorDependencyHelper(name);
  const ReporterMode mode = broadcast ? REPORTER_MODE_REPLICATED : REPORTER_MODE_ROOT;
  return _vpi_feproblem.getReporterData().getReporterValue<VectorPostprocessorValue>(
      VectorPostprocessorReporterName(name, vector_name), _vpi_moose_object, mode, t_index);
}
Referenced by getVectorPostprocessorValueByName(), and getVectorPostprocessorValueOldByName().
getVectorPostprocessorContextByNameHelper()
const VectorPostprocessorContext< VectorPostprocessorValue > & VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper (const VectorPostprocessorName & name, const std::string & vector_name) const private
Helper for getting the VPP context that handles scatter values.
Definition at line 284 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessorByName(name, vector_name);
  addVectorPostprocessorDependencyHelper(name);
  // The complete name of the store Reporter value
  const VectorPostprocessorReporterName r_name(name, vector_name);
  // Indicate the scatter value is desired, so the the VectorPostprocessorContext will do scatter
  _vpi_feproblem.getReporterData().getReporterValue<VectorPostprocessorValue>(
      r_name, _vpi_moose_object, REPORTER_MODE_VPP_SCATTER, 0);
  // Retrieve the VectorPostprocessorContext which contains the scattered value to be referenced
  const auto & context = _vpi_feproblem.getReporterData().getReporterContextBase(r_name);
  auto vpp_context_ptr =
      dynamic_cast<const VectorPostprocessorContext<VectorPostprocessorValue> *>(&context);
  mooseAssert(vpp_context_ptr, "Failed to get the VectorPostprocessorContext");
  return *vpp_context_ptr;
}
Referenced by getScatterVectorPostprocessorValueByName(), and getScatterVectorPostprocessorValueOldByName().
getVectorPostprocessorName()
const VectorPostprocessorName & VectorPostprocessorInterface::getVectorPostprocessorName (const std::string & param_name) const
Get the name of a VectorPostprocessor associated with a parameter.
Parameters
param_name The name of the VectorPostprocessor parameter
Returns
The name of the given VectorPostprocessor
Definition at line 203 of file VectorPostprocessorInterface.C.
{
  const auto & params = _vpi_moose_object.parameters();
  if (!params.isParamValid(param_name))
    _vpi_moose_object.mooseError(
        "When getting a VectorPostprocessor, failed to get a parameter with the name \"",
        param_name,
        "\".",
        "\n\nKnown parameters:\n",
        _vpi_moose_object.parameters());
  if (!params.isType<VectorPostprocessorName>(param_name))
    _vpi_moose_object.mooseError(
        "Supplied parameter with name \"",
        param_name,
        "\" of type \"",
        params.type(param_name),
        "\" is not an expected type for getting a VectorPostprocessor.\n\n",
        "The allowed type is \"VectorPostprocessorName\".");
  return params.get<VectorPostprocessorName>(param_name);
}
Referenced by getScatterVectorPostprocessorValue(), getScatterVectorPostprocessorValueOld(), getVectorPostprocessorValue(), getVectorPostprocessorValueOld(), hasVectorPostprocessor(), isVectorPostprocessorDistributed(), and possiblyCheckHasVectorPostprocessor().
getVectorPostprocessorValue() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValue (const std::string & param_name, const std::string & vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the value of a VectorPostprocessor
Parameters
param_name The name of the VectorPostprocessor parameter (see below)
vector_name The name of the particular vector you want.
Returns
A reference to the desired value
The name required by this method is the name that is hard-coded into your source code. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this function requires the "pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValueOld getVectorPostprocessorValueByName getVectorPostprocessorValueOldByName
Definition at line 36 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueByName(getVectorPostprocessorName(param_name), vector_name);
}
getVectorPostprocessorValue() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValue (const std::string & param_name, const std::string & vector_name, bool needs_broadcast) const
Retrieve the value of a VectorPostprocessor.
Parameters
param_name The name of the VectorPostprocessor parameter (see below)
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
A reference to the desired value
The name required by this method is the name that is hard-coded into your source code. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this function requires the "pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValueOld getVectorPostprocessorValueByName getVectorPostprocessorValueOldByName
Definition at line 66 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueByName(
      getVectorPostprocessorName(param_name), vector_name, needs_broadcast);
}
getVectorPostprocessorValueByName() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueByName (const VectorPostprocessorName & name, const std::string & vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the value of the VectorPostprocessor
Parameters
name VectorPostprocessor name (see below)
vector_name The name of the particular vector you want.
Returns
A reference to the desired value
The name required by this method is the name defined in the input file. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this method requires the "my_pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValue getVectorPostprocessorValueOldByName getVectorPostprocessorValueByName
Definition at line 44 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(name, vector_name, _broadcast_by_default, 0);
}
Referenced by getVectorPostprocessorValue().
getVectorPostprocessorValueByName() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueByName (const VectorPostprocessorName & name, const std::string & vector_name, bool needs_broadcast) const
Retrieve the value of the VectorPostprocessor.
Parameters
name VectorPostprocessor name (see below)
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
A reference to the desired value
The name required by this method is the name defined in the input file. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this method requires the "my_pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValue getVectorPostprocessorValueOldByName getVectorPostprocessorValueByName
Definition at line 76 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(
      name, vector_name, needs_broadcast || _broadcast_by_default, 0);
}
getVectorPostprocessorValueOld() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOld (const std::string & param_name, const std::string & vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the old value of a VectorPostprocessor
Parameters
param_name The name of the VectorPostprocessor parameter
vector_name The name of the particular vector you want.
Returns
The value of the VectorPostprocessor
see getVectorPostprocessorValue
Definition at line 51 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueOldByName(getVectorPostprocessorName(param_name), vector_name);
}
getVectorPostprocessorValueOld() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOld (const std::string & param_name, const std::string & vector_name, bool needs_broadcast) const
Retrieve the old value of a VectorPostprocessor.
Parameters
param_name The name of the VectorPostprocessor parameter
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
The value of the VectorPostprocessor
see getVectorPostprocessorValue
Definition at line 86 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueOldByName(
      getVectorPostprocessorName(param_name), vector_name, needs_broadcast);
}
getVectorPostprocessorValueOldByName() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOldByName (const VectorPostprocessorName & name, const std::string & vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the old value of a VectorPostprocessor
Parameters
name The name of the VectorPostprocessor
vector_name The name of the particular vector you want.
Returns
The value of the VectorPostprocessor
If within the validParams for the object the addVectorPostprocessorParam was called this method will retun a reference to the default value specified in the call to the addVectorPostprocessorParam function if the postVectorPostprocessor does not exist.
see getVectorPostprocessorValueByName
Definition at line 59 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(name, vector_name, _broadcast_by_default, 1);
}
Referenced by getVectorPostprocessorValueOld().
getVectorPostprocessorValueOldByName() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOldByName (const VectorPostprocessorName & name, const std::string & vector_name, bool needs_broadcast) const
Retrieve the old value of a VectorPostprocessor.
Parameters
name The name of the VectorPostprocessor
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
The value of the VectorPostprocessor
If within the validParams for the object the addVectorPostprocessorParam was called this method will retun a reference to the default value specified in the call to the addVectorPostprocessorParam function if the postVectorPostprocessor does not exist.
see getVectorPostprocessorValueByName
Definition at line 96 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(
      name, vector_name, needs_broadcast || _broadcast_by_default, 1);
}
hasVectorPostprocessor() [1/2]
bool VectorPostprocessorInterface::hasVectorPostprocessor (const std::string & param_name) const
Determine if the VectorPostprocessor exists by parameter.
Parameters
name The name of the VectorPostprocessor parameter
Returns
True if the VectorPostprocessor exists
Definition at line 168 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessor() until all "
                              "VectorPostprocessors have been constructed.");
  return hasVectorPostprocessorByName(getVectorPostprocessorName(param_name));
}
hasVectorPostprocessor() [2/2]
bool VectorPostprocessorInterface::hasVectorPostprocessor (const std::string & param_name, const std::string & vector_name) const
Determine if the VectorPostprocessor data exists by parameter.
Parameters
param_name The name of the VectorPostprocessor parameter
vector_name The vector name within the VectorPostprocessor
Returns
True if the VectorPostprocessor data exists
See also
hasVectorPostprocessorByName getVectorPostprocessorValue
Definition at line 138 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessor() until all VectorPostprocessors "
                              "have been constructed.");
  return hasVectorPostprocessorByName(getVectorPostprocessorName(param_name), vector_name);
}
Referenced by possiblyCheckHasVectorPostprocessor().
hasVectorPostprocessorByName() [1/2]
bool VectorPostprocessorInterface::hasVectorPostprocessorByName (const VectorPostprocessorName & name) const
Determine if the VectorPostprocessor exists by name.
Parameters
name The name of the VectorPostprocessor
Returns
True if the VectorPostprocessor exists
Definition at line 178 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessorByName() until all "
                              "VectorPostprocessors have been constructed.");
  return _vpi_feproblem.hasUserObject(name) &&
         dynamic_cast<const VectorPostprocessor *>(&_vpi_feproblem.getUserObjectBase(name));
}
hasVectorPostprocessorByName() [2/2]
bool VectorPostprocessorInterface::hasVectorPostprocessorByName (const VectorPostprocessorName & name, const std::string & vector_name) const
Determine if the VectorPostprocessor data exists by name.
Parameters
name The name of the VectorPostprocessor
vector_name The vector name within the VectorPostprocessor
Returns
True if the VectorPostprocessor data exists
See also
hasVectorPostprocessor getVectorPostprocessorValueByName
Definition at line 149 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessorByName() until all "
                              "VectorPostprocessors have been constructed.");
  const bool has_vpp = _vpi_feproblem.getReporterData().hasReporterValue<VectorPostprocessorValue>(
      VectorPostprocessorReporterName(name, vector_name));
  if (has_vpp)
    mooseAssert(_vpi_feproblem.hasUserObject(name) && dynamic_cast<const VectorPostprocessor *>(
                                                          &_vpi_feproblem.getUserObjectBase(name)),
                "Has reporter VectorPostprocessor Reporter value but not VectorPostprocessor UO");
  return has_vpp;
}
Referenced by hasVectorPostprocessor(), AdvancedOutput::initShowHideLists(), CSV::output(), and possiblyCheckHasVectorPostprocessorByName().
isVectorPostprocessorDistributed()
bool VectorPostprocessorInterface::isVectorPostprocessorDistributed (const std::string & param_name) const
Return true if the VectorPostprocessor is marked with parallel_type as DISTRIBUTED.
Definition at line 190 of file VectorPostprocessorInterface.C.
{
  return isVectorPostprocessorDistributedByName(getVectorPostprocessorName(param_name));
}
isVectorPostprocessorDistributedByName()
bool VectorPostprocessorInterface::isVectorPostprocessorDistributedByName (const VectorPostprocessorName & name) const
Definition at line 196 of file VectorPostprocessorInterface.C.
{
  return _vpi_feproblem.getVectorPostprocessorObjectByName(name).isDistributed();
}
Referenced by isVectorPostprocessorDistributed().
possiblyCheckHasVectorPostprocessor()
void VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor (const std::string & param_name, const std::string & vector_name) const private
Helpers for "possibly" checking if a vpp exists.
This is only able to check for existance after all vpps have been added (after the task creating them has been called). If called before said task, this will do nothing, hence the "possibly". This allows us to have errors reported directly by the object requesting the vpp instead of through a system with less context.
Definition at line 228 of file VectorPostprocessorInterface.C.
{
  // Can't do checking if vpps have not been added
  if (!vectorPostprocessorsAdded())
    return;
  if (!hasVectorPostprocessor(param_name))
    _vpi_moose_object.paramError(param_name,
                                 "A VectorPostprocessor with the name \"",
                                 getVectorPostprocessorName(param_name),
                                 "\" was not found.");
  if (!hasVectorPostprocessor(param_name, vector_name))
    _vpi_moose_object.paramError(param_name,
                                 "The VectorPostprocessor \"",
                                 getVectorPostprocessorName(param_name),
                                 "\" does not have a vector named \"",
                                 vector_name,
                                 "\".");
}
Referenced by getScatterVectorPostprocessorValue(), getScatterVectorPostprocessorValueOld(), getVectorPostprocessorValue(), and getVectorPostprocessorValueOld().
possiblyCheckHasVectorPostprocessorByName()
void VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName (const VectorPostprocessorName & name, const std::string & vector_name) const private
Definition at line 250 of file VectorPostprocessorInterface.C.
{
  // Can't do checking if vpps have not been added
  if (!vectorPostprocessorsAdded())
    return;
  if (!hasVectorPostprocessorByName(name))
    _vpi_moose_object.mooseError(
        "A VectorPostprocessor with the name \"", name, "\" was not found.");
  if (!hasVectorPostprocessorByName(name, vector_name))
    _vpi_moose_object.mooseError("The VectorPostprocessor \"",
                                 name,
                                 "\" does not have a vector named \"",
                                 vector_name,
                                 "\".");
}
Referenced by getVectorPostprocessorByNameHelper(), and getVectorPostprocessorContextByNameHelper().
validParams()
InputParameters VectorPostprocessorInterface::validParams () static
Definition at line 18 of file VectorPostprocessorInterface.C.
{
  return emptyInputParameters();
}
Referenced by FVInterfaceKernel::validParams().
vectorPostprocessorsAdded()
bool VectorPostprocessorInterface::vectorPostprocessorsAdded () const private
Returns
True if all vpps have been added (the task associated with adding them is complete)
Definition at line 306 of file VectorPostprocessorInterface.C.
{
  return _vpi_feproblem.getMooseApp().actionWarehouse().isTaskComplete("add_vector_postprocessor");
}
Referenced by hasVectorPostprocessor(), hasVectorPostprocessorByName(), possiblyCheckHasVectorPostprocessor(), and possiblyCheckHasVectorPostprocessorByName().
Member Data Documentation
_broadcast_by_default
const bool VectorPostprocessorInterface::_broadcast_by_default private
Whether or not to force broadcasting by default.
Definition at line 352 of file VectorPostprocessorInterface.h.
Referenced by getVectorPostprocessorValueByName(), and getVectorPostprocessorValueOldByName().
_vpi_feproblem
const FEProblemBase& VectorPostprocessorInterface::_vpi_feproblem private
Reference the FEProblemBase class.
Definition at line 358 of file VectorPostprocessorInterface.h.
Referenced by getVectorPostprocessorByNameHelper(), getVectorPostprocessorContextByNameHelper(), hasVectorPostprocessor(), hasVectorPostprocessorByName(), isVectorPostprocessorDistributedByName(), and vectorPostprocessorsAdded().
_vpi_moose_object
const MooseObject& VectorPostprocessorInterface::_vpi_moose_object private
The MooseObject that uses this interface.
Definition at line 355 of file VectorPostprocessorInterface.h.
Referenced by getVectorPostprocessorByNameHelper(), getVectorPostprocessorContextByNameHelper(), getVectorPostprocessorName(), possiblyCheckHasVectorPostprocessor(), and possiblyCheckHasVectorPostprocessorByName().
_vpi_tid
const THREAD_ID VectorPostprocessorInterface::_vpi_tid private
Thread ID.
Definition at line 361 of file VectorPostprocessorInterface.h.
The documentation for this class was generated from the following files:
moose/framework/include/vectorpostprocessors/VectorPostprocessorInterface.h
moose/framework/src/vectorpostprocessors/VectorPostprocessorInterface.C