Zapdos: MooseVariableField< OutputType > Class Template Reference
MooseVariableField< OutputType > Class Template Reference abstract
Class for stuff related to variables.
#include <MooseVariableField.h>
Public Types
typedef TensorTools::IncrementRank< OutputType >::type OutputGradient
typedef TensorTools::IncrementRank< OutputGradient >::type OutputSecond
typedef TensorTools::DecrementRank< OutputType >::type OutputDivergence
typedef MooseArray< OutputType > FieldVariableValue
typedef MooseArray< OutputGradient > FieldVariableGradient
typedef MooseArray< OutputSecond > FieldVariableSecond
typedef MooseArray< OutputType > FieldVariableCurl
typedef MooseArray< OutputDivergence > FieldVariableDivergence
typedef Moose::ShapeType< OutputType >::type OutputShape
typedef TensorTools::IncrementRank< OutputShape >::type OutputShapeGradient
typedef TensorTools::IncrementRank< OutputShapeGradient >::type OutputShapeSecond
typedef TensorTools::DecrementRank< OutputShape >::type OutputShapeDivergence
typedef MooseArray< std::vector< OutputShape > > FieldVariablePhiValue
typedef MooseArray< std::vector< OutputShapeGradient > > FieldVariablePhiGradient
typedef MooseArray< std::vector< OutputShapeSecond > > FieldVariablePhiSecond
typedef MooseArray< std::vector< OutputShape > > FieldVariablePhiCurl
typedef MooseArray< std::vector< OutputShapeDivergence > > FieldVariablePhiDivergence
typedef MooseArray< std::vector< OutputShape > > FieldVariableTestValue
typedef MooseArray< std::vector< OutputShapeGradient > > FieldVariableTestGradient
typedef MooseArray< std::vector< OutputShapeSecond > > FieldVariableTestSecond
typedef MooseArray< std::vector< OutputShape > > FieldVariableTestCurl
typedef MooseArray< std::vector< OutputShapeDivergence > > FieldVariableTestDivergence
typedef Moose::DOFType< OutputType >::type OutputData
typedef MooseArray< OutputData > DoFValue
using FunctorType = FunctorBase< Moose::ADType< OutputType >::type >
using FunctorReturnType = Moose::ADType< OutputType >::type
using ValueType = Moose::ADType< OutputType >::type
using GradientType = typename MetaPhysicL::ReplaceAlgebraicType< Moose::ADType< OutputType >::type, typename TensorTools::IncrementRank< typename MetaPhysicL::ValueType< Moose::ADType< OutputType >::type >::type >::type >::type
This rigmarole makes it so that a user can create functors that return containers (std::vector, std::array).
using DotType = ValueType
Public Member Functions
MooseVariableField (const InputParameters &parameters)
virtual void setNodalValue (const OutputType &value, unsigned int idx=0)=0
virtual const ADTemplateVariableValue< OutputType > & adSln () const =0
AD solution getter.
virtual const ADTemplateVariableValue< OutputType > & adSlnNeighbor () const =0
AD neighbor solution getter.
virtual const ADTemplateVariableGradient< OutputType > & adGradSln () const =0
AD grad solution getter.
virtual const ADTemplateVariableGradient< OutputType > & adGradSlnDot () const =0
AD grad of time derivative solution getter.
virtual const ADTemplateVariableGradient< OutputType > & adGradSlnNeighbor () const =0
AD grad neighbor solution getter.
virtual const ADTemplateVariableGradient< OutputType > & adGradSlnNeighborDot () const =0
AD grad of time derivative neighbor solution getter.
virtual const ADTemplateVariableSecond< OutputType > & adSecondSln () const =0
AD second solution getter.
virtual const ADTemplateVariableSecond< OutputType > & adSecondSlnNeighbor () const =0
AD second neighbor solution getter.
virtual const ADTemplateVariableValue< OutputType > & adUDot () const =0
AD time derivative getter.
virtual const ADTemplateVariableValue< OutputType > & adUDotDot () const =0
AD second time derivative getter.
virtual const ADTemplateVariableValue< OutputType > & adUDotNeighbor () const =0
AD neighbor time derivative getter.
virtual const ADTemplateVariableValue< OutputType > & adUDotDotNeighbor () const =0
AD neighbor second time derivative getter.
virtual const MooseArray< ADReal > & adDofValues () const =0
Return the AD dof values.
virtual const MooseArray< ADReal > & adDofValuesNeighbor () const =0
Return the AD neighbor dof values.
virtual const FieldVariableValue & sln () const =0
virtual const FieldVariableValue & slnOld () const =0
virtual const FieldVariableValue & slnNeighbor () const =0
virtual const FieldVariableValue & slnOldNeighbor () const =0
virtual const FieldVariableValue & slnOlder () const =0
virtual const FieldVariableGradient & gradSln () const =0
element gradients
virtual const FieldVariableGradient & gradSlnOld () const =0
virtual const FieldVariableGradient & gradSlnNeighbor () const =0
neighbor solution gradients
virtual const FieldVariableGradient & gradSlnOldNeighbor () const =0
virtual bool computingSecond () const =0
Whether or not this variable is computing any second derivatives.
virtual bool computingCurl () const =0
Whether or not this variable is computing any curl quantities.
virtual bool computingDiv () const =0
Whether or not this variable is computing any divergence quantities.
virtual const FieldVariablePhiValue & phi () const =0
Return the variable's elemental shape functions.
virtual const FieldVariablePhiGradient & gradPhi () const =0
Return the gradients of the variable's elemental shape functions.
virtual const FieldVariablePhiSecond & secondPhi () const =0
Return the rank-2 tensor of second derivatives of the variable's elemental shape functions.
virtual const FieldVariablePhiValue & curlPhi () const =0
Curl of the shape functions.
virtual const FieldVariablePhiDivergence & divPhi () const =0
Divergence of the shape functions.
virtual const FieldVariablePhiValue & phiFace () const =0
Return the variable's shape functions on an element face.
virtual const FieldVariablePhiGradient & gradPhiFace () const =0
Return the gradients of the variable's shape functions on an element face.
virtual const FieldVariablePhiSecond & secondPhiFace () const =0
Return the rank-2 tensor of second derivatives of the variable's shape functions on an element face.
virtual const FieldVariablePhiValue & phiFaceNeighbor () const =0
Return the variable's shape functions on a neighboring element face.
virtual const FieldVariablePhiGradient & gradPhiFaceNeighbor () const =0
Return the gradients of the variable's shape functions on a neighboring element face.
virtual const FieldVariablePhiSecond & secondPhiFaceNeighbor () const =0
Return the rank-2 tensor of second derivatives of the variable's shape functions on a neighboring element face.
virtual const FieldVariablePhiValue & phiNeighbor () const =0
Return the variable's shape functions on a neighboring element.
virtual const FieldVariablePhiGradient & gradPhiNeighbor () const =0
Return the gradients of the variable's shape functions on a neighboring element.
virtual const FieldVariablePhiSecond & secondPhiNeighbor () const =0
Return the rank-2 tensor of second derivatives of the variable's shape functions on a neighboring element.
virtual const FieldVariablePhiValue & phiLower () const =0
Return the variable's shape functions on a lower-dimensional element.
virtual void setDofValues (const DenseVector< OutputData > &values)=0
Set local DOF values and evaluate the values on quadrature points.
bool usesPhiNeighbor () const
Whether or not this variable is actually using the shape function value.
bool usesGradPhiNeighbor () const
Whether or not this variable is actually using the shape function gradient.
virtual bool usesSecondPhiNeighbor () const =0
Whether or not this variable is actually using the shape function second derivatives.
virtual void clearDofIndices ()=0
Clear out the dof indices.
virtual void prepare ()=0
Prepare the elemental degrees of freedom.
virtual void prepareNeighbor ()=0
Prepare the neighbor element degrees of freedom.
virtual void prepareLowerD ()=0
Prepare a lower dimensional element's degrees of freedom.
virtual void prepareAux ()=0
virtual void reinitNode ()=0
virtual void reinitAux ()=0
virtual void reinitAuxNeighbor ()=0
virtual void reinitNodes (const std::vector< dof_id_type > &nodes)=0
virtual void reinitNodesNeighbor (const std::vector< dof_id_type > &nodes)=0
virtual Moose::VarFieldType fieldType () const =0
Filed type of this variable.
virtual bool isArray () const =0
std::string componentName (const unsigned int comp) const
Get the variable name of a component in libMesh.
virtual bool isVector () const =0
virtual bool isFV () const
virtual bool isNodalDefined () const =0
Is this variable defined at nodes.
virtual const dof_id_type & nodalDofIndex () const =0
virtual const dof_id_type & nodalDofIndexNeighbor () const =0
virtual const Elem *const & currentElem () const =0
Current element this variable is evaluated at.
const std::set< SubdomainID > & activeSubdomains () const
The subdomains the variable is active on.
bool activeOnSubdomain (SubdomainID subdomain) const
Is the variable active on the subdomain?
bool activeOnSubdomains (const std::set< SubdomainID > &subdomains) const
Is the variable active on the subdomains?
virtual void prepareIC ()=0
Prepare the initial condition.
virtual void computeFaceValues (const FaceInfo &)
Compute values at face quadrature points for the element+neighbor (both sides of the face).
virtual void computeElemValues ()=0
Compute values at interior quadrature points.
virtual void computeElemValuesFace ()=0
Compute values at facial quadrature points.
virtual void computeNeighborValuesFace ()=0
Compute values at facial quadrature points for the neighbor.
virtual void computeNeighborValues ()=0
Compute values at quadrature points for the neighbor.
virtual void computeLowerDValues ()=0
compute values at quadrature points on the lower dimensional element
virtual void computeNodalNeighborValues ()=0
Compute nodal values of this variable in the neighbor.
virtual void computeNodalValues ()=0
Compute nodal values of this variable.
virtual const std::vector< dof_id_type > & dofIndicesNeighbor () const =0
Get neighbor DOF indices for currently selected element.
virtual const std::vector< dof_id_type > & dofIndicesLower () const =0
Get dof indices for the current lower dimensional element (this is meaningful when performing mortar FEM)
virtual unsigned int numberOfDofsNeighbor ()=0
virtual void insert (NumericVector< Number > &residual)=0
virtual void add (NumericVector< Number > &residual)=0
virtual std::size_t phiSize () const =0
Return phi size.
virtual std::size_t phiFaceSize () const =0
Return phiFace size.
virtual std::size_t phiNeighborSize () const =0
Return phiNeighbor size.
virtual std::size_t phiFaceNeighborSize () const =0
Return phiFaceNeighbor size.
virtual std::size_t phiLowerSize () const =0
Return the number of shape functions on the lower dimensional element for this variable.
virtual unsigned int oldestSolutionStateRequested () const =0
The oldest solution state that is requested for this variable (0 = current, 1 = old, 2 = older, etc).
unsigned int number () const
Get variable number coming from libMesh.
const FEType & feType () const
Get the type of finite element object.
SystemBase & sys ()
Get the system this variable is part of.
const SystemBase & sys () const
Get the system this variable is part of.
const std::string & name () const override
Get the variable name.
bool useDual () const
Get dual mortar option.
const std::vector< dof_id_type > & allDofIndices () const
Get all global dofindices for the variable.
unsigned int totalVarDofs ()
Moose::VarKindType kind () const
Kind of the variable (Nonlinear, Auxiliary, ...)
void scalingFactor (Real factor)
Set the scaling factor for this variable.
void scalingFactor (const std::vector< Real > &factor)
Real scalingFactor () const
Get the scaling factor for this variable.
const std::vector< Real > & arrayScalingFactor () const
Order order () const
Get the order of this variable Note: Order enum can be implicitly converted to unsigned int.
unsigned int count () const
Get the number of components Note: For standard and vector variables, the number is one.
virtual bool isNodal () const
Is this variable nodal.
virtual bool hasDoFsOnNodes () const
Does this variable have DoFs on nodes.
virtual FEContinuity getContinuity () const
Return the continuity of this variable.
const DofMap & dofMap () const
The DofMap associated with the system this variable is in.
virtual void getDofIndices (const Elem *, std::vector< dof_id_type > &) const
virtual const std::vector< dof_id_type > & dofIndices () const
Get local DoF indices.
std::vector< dof_id_type > componentDofIndices (const std::vector< dof_id_type > &dof_indices, unsigned int component) const
Obtain DoF indices of a component with the indices of the 0th component.
virtual unsigned int numberOfDofs () const
Get the number of local DoFs.
bool eigen () const
Whether or not this variable operates on an eigen kernel.
void eigen (bool eigen)
Mark this variable as an eigen var or non-eigen var.
void initialSetup () override
Gets called at the beginning of the simulation before this object is asked to do its job.
virtual void clearAllDofIndices ()
virtual void setActiveTags (const std::set< TagID > &vtags)
Set the active vector tags.
virtual bool enabled () const
Return the enabled status of the object.
MooseApp & getMooseApp () const
Get the MooseApp this class is associated with.
const std::string & type () const
Get the type of this class.
std::string typeAndName () const
Get the class's combined type and name; useful in error handling.
MooseObjectParameterName uniqueParameterName (const std::string &parameter_name) const
The unique parameter name of a valid parameter of this object for accessing parameter controls.
const InputParameters & parameters () const
Get the parameters of the object.
MooseObjectName uniqueName () const
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
template<typename T >
const T & getParam (const std::string &name) const
Retrieve a parameter for the object.
template<typename T1 , typename T2 >
std::vector< std::pair< T1, T2 > > getParam (const std::string &param1, const std::string &param2) const
Retrieve two parameters and provide pair of parameters for the object.
template<typename T >
const T & getRenamedParam (const std::string &old_name, const std::string &new_name) const
Retrieve a renamed parameter for the object.
template<typename T >
T getCheckedPointerParam (const std::string &name, const std::string &error_string="") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
bool isParamValid (const std::string &name) const
Test if the supplied parameter is valid.
bool isParamSetByUser (const std::string &nm) const
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
template<typename... Args>
void paramError (const std::string &param, Args... args) const
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramWarning (const std::string &param, Args... args) const
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramInfo (const std::string &param, Args... args) const
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
std::string objectErrorPrefix (const std::string &error_type) const
A descriptive prefix for errors for an object.
void connectControllableParams (const std::string &parameter, const std::string &object_type, const std::string &object_name, const std::string &object_parameter) const
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
template<typename... Args>
void mooseError (Args &&... args) const
Emits an error prefixed with object name and type.
template<typename... Args>
void mooseErrorNonPrefixed (Args &&... args) const
Emits an error without the prefixing included in mooseError().
template<typename... Args>
void mooseWarning (Args &&... args) const
Emits a warning prefixed with object name and type.
template<typename... Args>
void mooseWarningNonPrefixed (Args &&... args) const
Emits a warning without the prefixing included in mooseWarning().
template<typename... Args>
void mooseDeprecated (Args &&... args) const
template<typename... Args>
void mooseInfo (Args &&... args) const
std::string errorPrefix (const std::string &error_type) const
A descriptive prefix for errors for this object:
std::string getDataFileName (const std::string &param) const
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
std::string getDataFileNameByName (const std::string &name, const std::string *param=nullptr) const
Returns the path of a data file for a given relative file path.
const std::vector< SubdomainName > & blocks () const
Return the block names for this object.
unsigned int numBlocks () const
Return the number of blocks for this object.
virtual const std::set< SubdomainID > & blockIDs () const
Return the block subdomain ids for this object Note, if this is not block restricted, this function returns all mesh subdomain ids.
unsigned int blocksMaxDimension () const
Return the largest mesh dimension of the elements in the blocks for this object.
bool hasBlocks (const SubdomainName &name) const
Test if the supplied block name is valid for this object.
bool hasBlocks (const std::vector< SubdomainName > &names) const
Test if the supplied vector of block names are valid for this object.
bool hasBlocks (const std::vector< SubdomainID > &ids) const
Test if the supplied vector block ids are valid for this object.
bool hasBlocks (const std::set< SubdomainID > &ids) const
Test if the supplied set of block ids are valid for this object.
bool isBlockSubset (const std::set< SubdomainID > &ids) const
Test if the class block ids are a subset of the supplied objects.
bool isBlockSubset (const std::vector< SubdomainID > &ids) const
Test if the class block ids are a subset of the supplied objects.
template<typename T , bool is_ad = false>
bool hasBlockMaterialProperty (const std::string &prop_name)
Check if a material property is valid for all blocks of this object.
const std::set< SubdomainID > & meshBlockIDs () const
Return all of the SubdomainIDs for the mesh.
virtual bool blockRestricted () const
Returns true if this object has been restricted to a block.
virtual void checkVariable (const MooseVariableFieldBase &variable) const
Helper for checking that the ids for this object are in agreement with the variables on the supplied variable.
void buildOutputHideVariableList (std::set< std::string > variable_names)
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
const std::set< OutputName > & getOutputs ()
Get the list of output objects that this class is restricted.
virtual void subdomainSetup ()
Gets called when the subdomain changes (i.e.
virtual void customSetup (const ExecFlagType &)
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
const ExecFlagEnum & getExecuteOnEnum () const
Return the execute on MultiMooseEnum for this object.
const MooseFunctorName & functorName () const
Return the functor name.
virtual void customSetup (const ExecFlagType &exec_type) override
void setCacheClearanceSchedule (const std::set< ExecFlagType > &clearance_schedule)
Set how often to clear the functor evaluation cache.
virtual bool isExtrapolatedBoundaryFace (const FaceInfo &, const Elem *, const StateArg &) const
Returns whether this (sided) face is an extrapolated boundary face for this functor.
bool isInternalFace (const FaceInfo &) const
Returns true if the face is an internal face.
virtual bool isConstant () const
Returns true if this functor is a constant.
virtual bool hasFaceSide (const FaceInfo &fi, const bool fi_elem_side) const override
Moose::FaceArg checkFace (const Moose::FaceArg &face) const
Examines the incoming face argument.
virtual void meshChanged ()
Called on this object when the mesh changes.
virtual void setDofValue (const OutputData &value, unsigned int index)=0
Degree of freedom value setters.
virtual const MooseArray< OutputType > & nodalValueArray () const =0
Methods for retrieving values of variables at the nodes in a MooseArray for AuxKernelBase.
virtual const MooseArray< OutputType > & nodalValueOldArray () const =0
virtual const MooseArray< OutputType > & nodalValueOlderArray () const =0
ValueType operator() (const ElemArg &elem, const StateArg &state) const
Same as their evaluate overloads with the same arguments but allows for caching implementation.
ValueType operator() (const FaceArg &face, const StateArg &state) const
ValueType operator() (const ElemQpArg &qp, const StateArg &state) const
ValueType operator() (const ElemSideQpArg &qp, const StateArg &state) const
ValueType operator() (const ElemPointArg &elem_point, const StateArg &state) const
ValueType operator() (const NodeArg &node, const StateArg &state) const
GradientType gradient (const ElemArg &elem, const StateArg &state) const
Same as their evaluateGradient overloads with the same arguments but allows for caching implementation.
GradientType gradient (const FaceArg &face, const StateArg &state) const
GradientType gradient (const ElemQpArg &qp, const StateArg &state) const
GradientType gradient (const ElemSideQpArg &qp, const StateArg &state) const
GradientType gradient (const ElemPointArg &elem_point, const StateArg &state) const
GradientType gradient (const NodeArg &node, const StateArg &state) const
DotType dot (const ElemArg &elem, const StateArg &state) const
Same as their evaluateDot overloads with the same arguments but allows for caching implementation.
DotType dot (const FaceArg &face, const StateArg &state) const
DotType dot (const ElemQpArg &qp, const StateArg &state) const
DotType dot (const ElemSideQpArg &qp, const StateArg &state) const
DotType dot (const ElemPointArg &elem_point, const StateArg &state) const
DotType dot (const NodeArg &node, const StateArg &state) const
GradientType gradDot (const ElemArg &elem, const StateArg &state) const
Same as their evaluateGradDot overloads with the same arguments but allows for caching implementation.
GradientType gradDot (const FaceArg &face, const StateArg &state) const
GradientType gradDot (const ElemQpArg &qp, const StateArg &state) const
GradientType gradDot (const ElemSideQpArg &qp, const StateArg &state) const
GradientType gradDot (const ElemPointArg &elem_point, const StateArg &state) const
GradientType gradDot (const NodeArg &node, const StateArg &state) const
Static Public Member Functions
static InputParameters validParams ()
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Member Functions
bool doDerivatives () const
virtual bool hasBlockMaterialPropertyHelper (const std::string &prop_name)
A helper method to allow the Material object to specialize the behavior of hasBlockMaterialProperty.
void initializeBlockRestrictable (const MooseObject *moose_object)
An initialization routine needed for dual constructors.
Moose::CoordinateSystemType getBlockCoordSystem ()
Check if the blocks this object operates on all have the same coordinate system, and if so return it.
Functor evaluation routines
These methods are all for evaluating functors with different kinds of spatial arguments.
Each of these methods also takes a state argument. For a description of the state argument, please see the StateArg doxygen
virtual ValueType evaluate (const ElemArg &elem, const StateArg &state) const=0
Evaluate the functor with a given element.
virtual ValueType evaluate (const FaceArg &face, const StateArg &state) const=0
virtual ValueType evaluate (const ElemQpArg &qp, const StateArg &state) const=0
virtual ValueType evaluate (const ElemSideQpArg &side_qp, const StateArg &state) const=0
virtual ValueType evaluate (const ElemPointArg &elem_point, const StateArg &state) const=0
Evaluate the functor with a given element and point.
virtual ValueType evaluate (const NodeArg &node, const StateArg &state) const=0
virtual GradientType evaluateGradient (const ElemArg &, const StateArg &) const
Evaluate the functor gradient with a given element.
virtual GradientType evaluateGradient (const FaceArg &, const StateArg &) const
virtual GradientType evaluateGradient (const ElemQpArg &, const StateArg &) const
virtual GradientType evaluateGradient (const ElemSideQpArg &, const StateArg &) const
virtual GradientType evaluateGradient (const ElemPointArg &, const StateArg &) const
Evaluate the functor gradient with a given element and point.
virtual GradientType evaluateGradient (const NodeArg &, const StateArg &) const
virtual DotType evaluateDot (const ElemArg &, const StateArg &) const
Evaluate the functor time derivative with a given element.
virtual DotType evaluateDot (const FaceArg &, const StateArg &) const
virtual DotType evaluateDot (const ElemQpArg &, const StateArg &) const
virtual DotType evaluateDot (const ElemSideQpArg &, const StateArg &) const
virtual DotType evaluateDot (const ElemPointArg &, const StateArg &) const
Evaluate the functor time derivative with a given element and point.
virtual DotType evaluateDot (const NodeArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemArg &, const StateArg &) const
Evaluate the functor gradient-dot with a given element.
virtual GradientType evaluateGradDot (const FaceArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemQpArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemSideQpArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemPointArg &, const StateArg &) const
Evaluate the functor gradient-dot with a given element and point.
virtual GradientType evaluateGradDot (const NodeArg &, const StateArg &) const
Protected Attributes
SystemBase & _sys
System this variable is part of.
FEType _fe_type
The FEType associated with this variable.
unsigned int _var_num
variable number (from libMesh)
unsigned int _index
variable number within MOOSE
bool _is_eigen
Whether or not this variable operates on eigen kernels.
Moose::VarKindType _var_kind
Variable type (see MooseTypes.h)
SubProblem & _subproblem
Problem this variable is part of.
const Variable & _variable
libMesh variable object for this variable
Assembly & _assembly
Assembly data.
const DofMap & _dof_map
DOF map.
std::vector< dof_id_type > _dof_indices
DOF indices.
MooseMesh & _mesh
mesh the variable is active in
THREAD_ID _tid
Thread ID.
const unsigned int _count
Number of variables in the array.
std::vector< Real > _scaling_factor
scaling factor for this variable
std::string _var_name
Variable name.
bool _use_dual
If dual mortar approach is used.
const bool _is_array
Whether this is an array variable.
const bool & _enabled
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
MooseApp & _app
The MOOSE application this is associated with.
const std::string & _type
The type of this class.
const std::string & _name
The name of this class, reference to value stored in InputParameters.
const InputParameters & _pars
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Factory & _factory
The Factory associated with the MooseApp.
ActionFactory & _action_factory
Builds Actions.
const MaterialData * _blk_material_data
Pointer to the MaterialData class for this object.
const ExecFlagEnum & _execute_enum
Execute settings for this object.
const ExecFlagType & _current_execute_flag
Reference to FEProblemBase.
FEProblemBase & _mci_feproblem
Reference to FEProblemBase instance.
Private Member Functions
template<typename... Args>
std::string paramErrorMsg (const std::string &param, Args... args) const
void clearCacheData ()
clear cache data
ValueType queryQpCache (unsigned int qp, const QBase &qrule, std::vector< std::pair< bool, Moose::ADType< OutputType >::type > > &qp_cache_data, const SpaceArg &space, const StateArg &state) const
check a qp cache and if invalid then evaluate
ValueType queryFVArgCache (std::map< SpaceArg, ValueType > &cache_data, const SpaceArg &space) const
check a finite volume spatial argument cache and if invalid then evaluate
Private Attributes
const MooseBase *const _moose_base
The MooseBase object that inherits this class.
const MooseObject & _parent
std::set< SubdomainID > _blk_ids
Set of block ids supplied by the user via the input file (for error checking)
std::vector< SubdomainID > _vec_ids
Vector of block ids supplied by the user via the input file (for error reporting)
std::vector< SubdomainName > _blocks
Vector the block names supplied by the user via the input file.
const bool _blk_dual_restrictable
Flag for allowing dual restriction.
FEProblemBase * _blk_feproblem
Pointer to FEProblemBase.
MooseMesh * _blk_mesh
Pointer to Mesh.
const std::set< BoundaryID > _empty_boundary_ids
An empty set for referencing when boundary_ids is not included.
const std::set< BoundaryID > & _boundary_ids
Reference to the boundary_ids, defaults to an empty set if not provided.
THREAD_ID _blk_tid
Thread id for this object.
const std::string & _blk_name
Name of the object.
unsigned int _blk_dim
Largest mesh dimension of the elements in the blocks for this object.
MooseApp & _oi_moose_app
Reference the the MooseApp; neede for access to the OutputWarehouse.
OutputWarehouse & _oi_output_warehouse
Reference to the OutputWarehouse for populating the Output object hide lists.
std::set< OutputName > _oi_outputs
The set of Output object names listed in the 'outputs' parameter.
ExecFlagEnum _empty_execute_enum
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
std::set< ExecFlagType > _clearance_schedule
How often to clear the material property cache.
dof_id_type _current_qp_map_key
Current key for qp map cache.
std::vector< std::pair< bool, ValueType > > * _current_qp_map_value
Current value for qp map cache.
std::unordered_map< dof_id_type, std::vector< std::pair< bool, ValueType > > > _qp_to_value
Cached element quadrature point functor property evaluations.
dof_id_type _current_side_qp_map_key
Current key for side-qp map cache.
std::vector< std::vector< std::pair< bool, ValueType > > > * _current_side_qp_map_value
Current value for side-qp map cache.
std::unordered_map< dof_id_type, std::vector< std::vector< std::pair< bool, ValueType > > > > _side_qp_to_value
Cached element quadrature point functor property evaluations.
std::map< ElemArg, ValueType > _elem_arg_to_value
Map from element arguments to their cached evaluations.
std::map< FaceArg, ValueType > _face_arg_to_value
Map from face arguments to their cached evaluations.
std::map< NodeArg, ValueType > _node_arg_to_value
Map from nodal arguments to their cached evaluations.
MooseFunctorName _functor_name
name of the functor
const TimeIntegrator *const _time_integrator
the time integrator used for computing time derivatives
ADReal _ad_real_dummy = 0
A dummy ADReal variable.
virtual const DoFValue & dofValues () const =0
dof values getters
virtual const DoFValue & dofValuesOld () const =0
virtual const DoFValue & dofValuesOlder () const =0
virtual const DoFValue & dofValuesPreviousNL () const =0
virtual const DoFValue & dofValuesNeighbor () const =0
virtual const DoFValue & dofValuesOldNeighbor () const =0
virtual const DoFValue & dofValuesOlderNeighbor () const =0
virtual const DoFValue & dofValuesPreviousNLNeighbor () const =0
virtual const DoFValue & dofValuesDot () const =0
virtual const DoFValue & dofValuesDotNeighbor () const =0
virtual const DoFValue & dofValuesDotOld () const =0
virtual const DoFValue & dofValuesDotOldNeighbor () const =0
virtual const DoFValue & dofValuesDotDot () const =0
virtual const DoFValue & dofValuesDotDotNeighbor () const =0
virtual const DoFValue & dofValuesDotDotOld () const =0
virtual const DoFValue & dofValuesDotDotOldNeighbor () const =0
virtual const MooseArray< Number > & dofValuesDuDotDu () const =0
virtual const MooseArray< Number > & dofValuesDuDotDuNeighbor () const =0
virtual const MooseArray< Number > & dofValuesDuDotDotDu () const =0
virtual const MooseArray< Number > & dofValuesDuDotDotDuNeighbor () const =0
virtual const FieldVariableValue & vectorTagValue (TagID tag) const =0
tag values getters
virtual const DoFValue & nodalVectorTagValue (TagID tag) const =0
virtual const DoFValue & vectorTagDofValue (TagID tag) const =0
virtual void residualSetup () override
virtual void jacobianSetup () override
virtual void timestepSetup () override
bool hasBlocks (const SubdomainID id) const override
Returns whether the functor is defined on this block.
const NumericVector< Number > & getSolution (const Moose::StateArg &state) const
Get the solution corresponding to the provided state.
Detailed Description
template<typename OutputType>
class MooseVariableField< OutputType >
Class for stuff related to variables.
Each variable can compute nodal or elemental (at QPs) values.
OutputType OutputShape OutputData
Real Real Real RealVectorValue RealVectorValue Real RealEigenVector Real RealEigenVector
Definition at line 40 of file MooseVariableField.h.
Member Typedef Documentation
DoFValue
template<typename OutputType > typedef MooseArray<OutputData> MooseVariableField< OutputType >::DoFValue
Definition at line 82 of file MooseVariableField.h.
DotType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::DotType = ValueType inherited
Definition at line 67 of file MooseFunctor.h.
FieldVariableCurl
template<typename OutputType > typedef MooseArray<OutputType> MooseVariableField< OutputType >::FieldVariableCurl
Definition at line 54 of file MooseVariableField.h.
FieldVariableDivergence
template<typename OutputType > typedef MooseArray<OutputDivergence> MooseVariableField< OutputType >::FieldVariableDivergence
Definition at line 55 of file MooseVariableField.h.
FieldVariableGradient
template<typename OutputType > typedef MooseArray<OutputGradient> MooseVariableField< OutputType >::FieldVariableGradient
Definition at line 52 of file MooseVariableField.h.
FieldVariablePhiCurl
template<typename OutputType > typedef MooseArray<std::vector<OutputShape> > MooseVariableField< OutputType >::FieldVariablePhiCurl
Definition at line 69 of file MooseVariableField.h.
FieldVariablePhiDivergence
template<typename OutputType > typedef MooseArray<std::vector<OutputShapeDivergence> > MooseVariableField< OutputType >::FieldVariablePhiDivergence
Definition at line 70 of file MooseVariableField.h.
FieldVariablePhiGradient
template<typename OutputType > typedef MooseArray<std::vector<OutputShapeGradient> > MooseVariableField< OutputType >::FieldVariablePhiGradient
Definition at line 67 of file MooseVariableField.h.
FieldVariablePhiSecond
template<typename OutputType > typedef MooseArray<std::vector<OutputShapeSecond> > MooseVariableField< OutputType >::FieldVariablePhiSecond
Definition at line 68 of file MooseVariableField.h.
FieldVariablePhiValue
template<typename OutputType > typedef MooseArray<std::vector<OutputShape> > MooseVariableField< OutputType >::FieldVariablePhiValue
Definition at line 66 of file MooseVariableField.h.
FieldVariableSecond
template<typename OutputType > typedef MooseArray<OutputSecond> MooseVariableField< OutputType >::FieldVariableSecond
Definition at line 53 of file MooseVariableField.h.
FieldVariableTestCurl
template<typename OutputType > typedef MooseArray<std::vector<OutputShape> > MooseVariableField< OutputType >::FieldVariableTestCurl
Definition at line 77 of file MooseVariableField.h.
FieldVariableTestDivergence
template<typename OutputType > typedef MooseArray<std::vector<OutputShapeDivergence> > MooseVariableField< OutputType >::FieldVariableTestDivergence
Definition at line 78 of file MooseVariableField.h.
FieldVariableTestGradient
template<typename OutputType > typedef MooseArray<std::vector<OutputShapeGradient> > MooseVariableField< OutputType >::FieldVariableTestGradient
Definition at line 75 of file MooseVariableField.h.
FieldVariableTestSecond
template<typename OutputType > typedef MooseArray<std::vector<OutputShapeSecond> > MooseVariableField< OutputType >::FieldVariableTestSecond
Definition at line 76 of file MooseVariableField.h.
FieldVariableTestValue
template<typename OutputType > typedef MooseArray<std::vector<OutputShape> > MooseVariableField< OutputType >::FieldVariableTestValue
Definition at line 74 of file MooseVariableField.h.
FieldVariableValue
template<typename OutputType > typedef MooseArray<OutputType> MooseVariableField< OutputType >::FieldVariableValue
Definition at line 51 of file MooseVariableField.h.
FunctorReturnType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::FunctorReturnType = Moose::ADType< OutputType >::type inherited
Definition at line 55 of file MooseFunctor.h.
FunctorType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::FunctorType = FunctorBase<Moose::ADType< OutputType >::type > inherited
Definition at line 54 of file MooseFunctor.h.
GradientType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::GradientType = typename MetaPhysicL::ReplaceAlgebraicType< Moose::ADType< OutputType >::type , typename TensorTools::IncrementRank<typename MetaPhysicL::ValueType<Moose::ADType< OutputType >::type >::type>::type>::type inherited
This rigmarole makes it so that a user can create functors that return containers (std::vector, std::array).
This logic will make it such that if a user requests a functor type T that is a container of algebraic types, for example Reals, then the GradientType will be a container of the gradients of those algebraic types, in this example VectorValue<Reals>. So if T is std::vector<Real>, then GradientType will be std::vector<VectorValue<Real>>. As another example: T = std::array<VectorValue<Real>, 1> -> GradientType = std::array<TensorValue<Real>, 1>
Definition at line 64 of file MooseFunctor.h.
OutputData
template<typename OutputType > typedef Moose::DOFType<OutputType>::type MooseVariableField< OutputType >::OutputData
Definition at line 81 of file MooseVariableField.h.
OutputDivergence
template<typename OutputType > typedef TensorTools::DecrementRank<OutputType>::type MooseVariableField< OutputType >::OutputDivergence
Definition at line 48 of file MooseVariableField.h.
OutputGradient
template<typename OutputType > typedef TensorTools::IncrementRank<OutputType>::type MooseVariableField< OutputType >::OutputGradient
Definition at line 46 of file MooseVariableField.h.
OutputSecond
template<typename OutputType > typedef TensorTools::IncrementRank<OutputGradient>::type MooseVariableField< OutputType >::OutputSecond
Definition at line 47 of file MooseVariableField.h.
OutputShape
template<typename OutputType > typedef Moose::ShapeType<OutputType>::type MooseVariableField< OutputType >::OutputShape
Definition at line 58 of file MooseVariableField.h.
OutputShapeDivergence
template<typename OutputType > typedef TensorTools::DecrementRank<OutputShape>::type MooseVariableField< OutputType >::OutputShapeDivergence
Definition at line 63 of file MooseVariableField.h.
OutputShapeGradient
template<typename OutputType > typedef TensorTools::IncrementRank<OutputShape>::type MooseVariableField< OutputType >::OutputShapeGradient
Definition at line 61 of file MooseVariableField.h.
OutputShapeSecond
template<typename OutputType > typedef TensorTools::IncrementRank<OutputShapeGradient>::type MooseVariableField< OutputType >::OutputShapeSecond
Definition at line 62 of file MooseVariableField.h.
ValueType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::ValueType = Moose::ADType< OutputType >::type inherited
Definition at line 56 of file MooseFunctor.h.
Constructor & Destructor Documentation
MooseVariableField()
template<typename OutputType > MooseVariableField< OutputType >::MooseVariableField (const InputParameters & parameters)
Definition at line 26 of file MooseVariableField.C.
  : MooseVariableFieldBase(parameters),
    Moose::FunctorBase<typename Moose::ADType<OutputType>::type>(name()),
    MeshChangedInterface(parameters),
    _time_integrator(_sys.getTimeIntegrator())
{
}
Member Function Documentation
activeOnSubdomain()
bool MooseVariableFieldBase::activeOnSubdomain (SubdomainID subdomain) const inherited
Is the variable active on the subdomain?
Parameters
subdomain The subdomain id in question
Returns
true if active on subdomain, false otherwise
Definition at line 45 of file MooseVariableFieldBase.C.
{
  return this->_sys.system().variable(_var_num).active_on_subdomain(subdomain);
}
Referenced by ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), ComputeFullJacobianThread::computeOnInternalFace(), ComputeDiracThread::onElement(), and FlagElementsThread::onElement().
activeOnSubdomains()
bool MooseVariableFieldBase::activeOnSubdomains (const std::set< SubdomainID > & subdomains) const inherited
Is the variable active on the subdomains?
Parameters
subdomains The subdomain ids in question
Returns
true if active on all provided subdomains, false otherwise
Definition at line 51 of file MooseVariableFieldBase.C.
{
  const auto & active_subs = activeSubdomains();
  return std::includes(
      active_subs.begin(), active_subs.end(), subdomains.begin(), subdomains.end());
}
activeSubdomains()
const std::set< SubdomainID > & MooseVariableFieldBase::activeSubdomains () const inherited
The subdomains the variable is active on.
Definition at line 39 of file MooseVariableFieldBase.C.
{
  return this->_sys.system().variable(_var_num).active_subdomains();
}
Referenced by SetupResidualDebugAction::act(), MooseVariableFieldBase::activeOnSubdomains(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), BlockRestrictable::checkVariable(), DGLowerDKernel::DGLowerDKernel(), HFEMDirichletBC::HFEMDirichletBC(), and LowerDIntegratedBC::LowerDIntegratedBC().
add()
virtual void MooseVariableFieldBase::add (NumericVector< Number > & residual) pure virtual inherited
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adDofValues()
template<typename OutputType > virtual const MooseArray< ADReal > & MooseVariableField< OutputType >::adDofValues () const pure virtual
Return the AD dof values.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adDofValuesNeighbor()
template<typename OutputType > virtual const MooseArray< ADReal > & MooseVariableField< OutputType >::adDofValuesNeighbor () const pure virtual
Return the AD neighbor dof values.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adGradSln()
template<typename OutputType > virtual const ADTemplateVariableGradient< OutputType > & MooseVariableField< OutputType >::adGradSln () const pure virtual
AD grad solution getter.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adGradSlnDot()
template<typename OutputType > virtual const ADTemplateVariableGradient< OutputType > & MooseVariableField< OutputType >::adGradSlnDot () const pure virtual
AD grad of time derivative solution getter.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adGradSlnNeighbor()
template<typename OutputType > virtual const ADTemplateVariableGradient< OutputType > & MooseVariableField< OutputType >::adGradSlnNeighbor () const pure virtual
AD grad neighbor solution getter.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adGradSlnNeighborDot()
template<typename OutputType > virtual const ADTemplateVariableGradient< OutputType > & MooseVariableField< OutputType >::adGradSlnNeighborDot () const pure virtual
AD grad of time derivative neighbor solution getter.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adSecondSln()
template<typename OutputType > virtual const ADTemplateVariableSecond< OutputType > & MooseVariableField< OutputType >::adSecondSln () const pure virtual
AD second solution getter.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adSecondSlnNeighbor()
template<typename OutputType > virtual const ADTemplateVariableSecond< OutputType > & MooseVariableField< OutputType >::adSecondSlnNeighbor () const pure virtual
AD second neighbor solution getter.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adSln()
template<typename OutputType > virtual const ADTemplateVariableValue< OutputType > & MooseVariableField< OutputType >::adSln () const pure virtual
AD solution getter.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adSlnNeighbor()
template<typename OutputType > virtual const ADTemplateVariableValue< OutputType > & MooseVariableField< OutputType >::adSlnNeighbor () const pure virtual
AD neighbor solution getter.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adUDot()
template<typename OutputType > virtual const ADTemplateVariableValue< OutputType > & MooseVariableField< OutputType >::adUDot () const pure virtual
AD time derivative getter.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adUDotDot()
template<typename OutputType > virtual const ADTemplateVariableValue< OutputType > & MooseVariableField< OutputType >::adUDotDot () const pure virtual
AD second time derivative getter.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adUDotDotNeighbor()
template<typename OutputType > virtual const ADTemplateVariableValue< OutputType > & MooseVariableField< OutputType >::adUDotDotNeighbor () const pure virtual
AD neighbor second time derivative getter.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
adUDotNeighbor()
template<typename OutputType > virtual const ADTemplateVariableValue< OutputType > & MooseVariableField< OutputType >::adUDotNeighbor () const pure virtual
AD neighbor time derivative getter.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
allDofIndices()
const std::vector< dof_id_type > & MooseVariableBase::allDofIndices () const inherited
Get all global dofindices for the variable.
Definition at line 137 of file MooseVariableBase.C.
{
  const auto it = _sys.subproblem()._var_dof_map.find(name());
  if (it != _sys.subproblem()._var_dof_map.end())
    return it->second;
  else
    mooseError("VariableAllDoFMap not prepared for ",
               name(),
               " . Check nonlocal coupling requirement for the variable.");
}
Referenced by FEProblemBase::addJacobianBlockTags(), NonlocalIntegratedBC::computeNonlocalJacobian(), NonlocalKernel::computeNonlocalJacobian(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), FEProblemBase::prepare(), Assembly::prepareNonlocal(), Assembly::prepareVariableNonlocal(), and MooseVariableBase::totalVarDofs().
arrayScalingFactor()
const std::vector< Real > & MooseVariableBase::arrayScalingFactor () const inline inherited
Definition at line 97 of file MooseVariableBase.h.
{ return _scaling_factor; }
Referenced by Assembly::addJacobianBlock(), Assembly::addJacobianBlockNonlocal(), Assembly::addJacobianNeighbor(), Assembly::cacheJacobianBlock(), and Assembly::cacheJacobianBlockNonzero().
blockIDs()
const std::set< SubdomainID > & BlockRestrictable::blockIDs () const virtual inherited
Return the block subdomain ids for this object Note, if this is not block restricted, this function returns all mesh subdomain ids.
Returns
a set of SubdomainIDs that are valid for this object
Definition at line 190 of file BlockRestrictable.C.
{
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return _blk_mesh->meshSubdomains();
  else
    return _blk_ids;
}
Referenced by FunctorMaterial::addFunctorProperty(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), NodalPatchRecoveryAuxBase::blockRestrictElements(), MooseMesh::cacheFaceInfoVariableOwnership(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), BlockRestrictable::getBlockCoordSystem(), MaterialBase::getGenericZeroMaterialPropertyByName(), BlockRestrictable::hasBlockMaterialPropertyHelper(), SubdomainsDivision::initialize(), ElementCentroidPositions::initialize(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), MaterialBase::registerPropName(), and FVPointValueConstraint::setMyElem().
blockRestricted()
bool BlockRestrictable::blockRestricted () const virtual inherited
Returns true if this object has been restricted to a block.
See also
MooseObject
Definition at line 178 of file BlockRestrictable.C.
{
  return _blk_ids.find(Moose::ANY_BLOCK_ID) == _blk_ids.end();
}
Referenced by NodalPatchRecoveryAuxBase::blockRestrictElements(), BlockRestrictable::checkVariable(), SubdomainsDivision::divisionIndex(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), SubdomainsDivision::initialize(), ElementCentroidPositions::initialize(), BlockRestrictable::initializeBlockRestrictable(), SolutionIC::initialSetup(), and FVPointValueConstraint::setMyElem().
blocks()
const std::vector< SubdomainName > & BlockRestrictable::blocks () const inherited
Return the block names for this object.
Note, if the 'blocks' input parameter was not utilized this will return an empty vector.
Returns
vector of SubdomainNames that are valid for this object
Definition at line 184 of file BlockRestrictable.C.
{
  return _blocks;
}
Referenced by MaterialOutputAction::getParams(), BlockAverageValue::initialize(), SubdomainsDivision::initialize(), and SolutionIC::initialSetup().
blocksMaxDimension()
unsigned int BlockRestrictable::blocksMaxDimension () const inherited
Return the largest mesh dimension of the elements in the blocks for this object.
Definition at line 360 of file BlockRestrictable.C.
{
  mooseAssert(_blk_dim != libMesh::invalid_uint, "Block restriction not initialized");
  return _blk_dim;
}
buildOutputHideVariableList()
void OutputInterface::buildOutputHideVariableList (std::set< std::string > variable_names) inherited
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
Parameters
variable_names A set of variables for which the 'outputs' parameter controls
By default this is called by the constructor and passes the block name as the list of variables. This needs to be called explicitly if the build_list flag is set to False in the constructor. The latter cases is needed by the Material object to work correctly with the automatic material output capability.
Definition at line 61 of file OutputInterface.C.
{
  // Set of available names
  const std::set<OutputName> & avail = _oi_output_warehouse.getOutputNames();
  // Check for 'none'; hide variables on all outputs
  if (_oi_outputs.find("none") != _oi_outputs.end())
    for (const auto & name : avail)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  // Check for empty and 'all' in 'outputs' parameter; do not perform any variable restrictions in
  // these cases
  else if (_oi_outputs.empty() || _oi_outputs.find("all") != _oi_outputs.end())
    return;
  // Limit the variable output to Output objects listed
  else
  {
    // Create a list of outputs where the variable should be hidden
    std::set<OutputName> hide;
    std::set_difference(avail.begin(),
                        avail.end(),
                        _oi_outputs.begin(),
                        _oi_outputs.end(),
                        std::inserter(hide, hide.begin()));
    // If 'outputs' is specified add the object name to the list of items to hide
    for (const auto & name : hide)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  }
}
Referenced by ReporterTransferInterface::hideVariableHelper(), and OutputInterface::OutputInterface().
checkFace()
FaceArg Moose::FunctorBase< Moose::ADType< OutputType >::type >::checkFace (const Moose::FaceArg & face) const inherited
Examines the incoming face argument.
If the face argument producer (residual object, postprocessor, etc.) did not indicate a sidedness to the face, e.g. if the face_side member of the FaceArg is nullptr, then we may "modify" the sidedness of the argument if we are only defined on one side of the face. If the face argument producer \emph has indicated a sidedness and we are not defined on that side, then we will error
Parameters
face The face argument created by the face argument producer, likely a residual object
Returns
A face with possibly changed sidedness depending on whether we aren't defined on both sides of the face
Definition at line 181 of file MooseFunctor.h.
{
  const Elem * const elem = face.face_side;
  const FaceInfo * const fi = face.fi;
  mooseAssert(fi, "face info should be non-null");
  auto ret_face = face;
  bool check_elem_def = false;
  bool check_neighbor_def = false;
  if (!elem)
  {
    if (!hasFaceSide(*fi, true))
    {
      ret_face.face_side = fi->neighborPtr();
      check_neighbor_def = true;
    }
    else if (!hasFaceSide(*fi, false))
    {
      ret_face.face_side = fi->elemPtr();
      check_elem_def = true;
    }
  }
  else if (elem == fi->elemPtr())
    check_elem_def = true;
  else
  {
    mooseAssert(elem == fi->neighborPtr(), "This has to match something");
    check_neighbor_def = true;
  }
  if (check_elem_def && !hasFaceSide(*fi, true))
  {
    std::string additional_message = "It is not defined on the neighbor side either.";
    if (hasFaceSide(*fi, false))
      additional_message = "It is however defined on the neighbor side.";
    additional_message += " Face centroid: " + Moose::stringify(fi->faceCentroid());
    mooseError(_functor_name,
               " is not defined on the element side of the face information, but a face argument "
               "producer "
               "(e.g. residual object, postprocessor, etc.) has requested evaluation there.\n",
               additional_message);
  }
  if (check_neighbor_def && !hasFaceSide(*fi, false))
  {
    std::string additional_message = "It is not defined on the element side either.";
    if (hasFaceSide(*fi, true))
      additional_message = "It is however defined on the element side.";
    additional_message += " Face centroid: " + Moose::stringify(fi->faceCentroid());
    mooseError(
        _functor_name,
        " is not defined on the neighbor side of the face information, but a face argument "
        "producer (e.g. residual object, postprocessor, etc.) has requested evaluation there.\n",
        additional_message);
  }
  return ret_face;
}
checkVariable()
void BlockRestrictable::checkVariable (const MooseVariableFieldBase & variable) const virtual inherited
Helper for checking that the ids for this object are in agreement with the variables on the supplied variable.
Parameters
variable The variable to check against.
Reimplemented in DomainUserObject.
Definition at line 333 of file BlockRestrictable.C.
{
  // a variable defined on all internal sides does not need this check because
  // it can be coupled with other variables in DG kernels
  if (variable.activeSubdomains().count(Moose::INTERNAL_SIDE_LOWERD_ID) > 0)
    return;
  if (!isBlockSubset(variable.activeSubdomains()))
  {
    std::string var_ids = Moose::stringify(variable.activeSubdomains(), ", ");
    std::string obj_ids = Moose::stringify(blockRestricted() ? _blk_ids : meshBlockIDs(), ", ");
    mooseError("The 'block' parameter of the object '",
               _blk_name,
               "' must be a subset of the 'block' parameter of the variable '",
               variable.name(),
               "':\n    Object '",
               _blk_name,
               "': ",
               obj_ids,
               "\n    Variable '",
               variable.name(),
               "': ",
               var_ids);
  }
}
Referenced by DomainUserObject::checkVariable().
clearAllDofIndices()
virtual void MooseVariableBase::clearAllDofIndices () inline virtual inherited
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 167 of file MooseVariableBase.h.
{ _dof_indices.clear(); }
clearCacheData()
void Moose::FunctorBase< Moose::ADType< OutputType >::type >::clearCacheData private inherited
clear cache data
Definition at line 391 of file MooseFunctor.h.
{
  for (auto & map_pr : _qp_to_value)
    for (auto & pr : map_pr.second)
      pr.first = false;
  for (auto & map_pr : _side_qp_to_value)
  {
    auto & side_vector = map_pr.second;
    for (auto & qp_vector : side_vector)
      for (auto & pr : qp_vector)
        pr.first = false;
  }
  _current_qp_map_key = DofObject::invalid_id;
  _current_qp_map_value = nullptr;
  _current_side_qp_map_key = DofObject::invalid_id;
  _current_side_qp_map_value = nullptr;
  _elem_arg_to_value.clear();
  _face_arg_to_value.clear();
  _node_arg_to_value.clear();
}
clearDofIndices()
virtual void MooseVariableFieldBase::clearDofIndices () pure virtual inherited
Clear out the dof indices.
We do this in case this variable is not going to be prepared at all...
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
componentDofIndices()
std::vector< dof_id_type > MooseVariableBase::componentDofIndices (const std::vector< dof_id_type > & dof_indices, unsigned int component) const inherited
Obtain DoF indices of a component with the indices of the 0th component.
Definition at line 155 of file MooseVariableBase.C.
{
  std::vector<dof_id_type> new_dof_indices(dof_indices);
  if (component != 0)
  {
    if (isNodal())
      for (auto & id : new_dof_indices)
        id += component;
    else
    {
      unsigned int n = dof_indices.size();
      for (auto & id : new_dof_indices)
        id += component * n;
    }
  }
  return new_dof_indices;
}
Referenced by Assembly::addJacobianBlock(), Assembly::cacheJacobianBlock(), and Assembly::cacheJacobianBlockNonzero().
componentName()
std::string MooseVariableFieldBase::componentName (const unsigned int comp) const inherited
Get the variable name of a component in libMesh.
Definition at line 27 of file MooseVariableFieldBase.C.
{
  if (comp >= _count)
    mooseError("Component index must be less than the number of components of variable ",
               _var_name);
  if (isArray())
    return this->_subproblem.arrayVariableComponent(_var_name, comp);
  else
    return _var_name;
}
computeElemValues()
virtual void MooseVariableFieldBase::computeElemValues () pure virtual inherited
Compute values at interior quadrature points.
Implemented in MooseVariableConstMonomial, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
computeElemValuesFace()
virtual void MooseVariableFieldBase::computeElemValuesFace () pure virtual inherited
Compute values at facial quadrature points.
Implemented in MooseVariableConstMonomial, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
computeFaceValues()
virtual void MooseVariableFieldBase::computeFaceValues (const FaceInfo &) inline virtual inherited
Compute values at face quadrature points for the element+neighbor (both sides of the face).
Reimplemented in MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 130 of file MooseVariableFieldBase.h.
{ mooseError("not implemented"); }
computeLowerDValues()
virtual void MooseVariableFieldBase::computeLowerDValues () pure virtual inherited
compute values at quadrature points on the lower dimensional element
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
computeNeighborValues()
virtual void MooseVariableFieldBase::computeNeighborValues () pure virtual inherited
Compute values at quadrature points for the neighbor.
Implemented in MooseVariableConstMonomial, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
computeNeighborValuesFace()
virtual void MooseVariableFieldBase::computeNeighborValuesFace () pure virtual inherited
Compute values at facial quadrature points for the neighbor.
Implemented in MooseVariableConstMonomial, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
computeNodalNeighborValues()
virtual void MooseVariableFieldBase::computeNodalNeighborValues () pure virtual inherited
Compute nodal values of this variable in the neighbor.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
computeNodalValues()
virtual void MooseVariableFieldBase::computeNodalValues () pure virtual inherited
Compute nodal values of this variable.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
computingCurl()
template<typename OutputType > virtual bool MooseVariableField< OutputType >::computingCurl () const pure virtual
Whether or not this variable is computing any curl quantities.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
computingDiv()
template<typename OutputType > virtual bool MooseVariableField< OutputType >::computingDiv () const pure virtual
Whether or not this variable is computing any divergence quantities.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
computingSecond()
template<typename OutputType > virtual bool MooseVariableField< OutputType >::computingSecond () const pure virtual
Whether or not this variable is computing any second derivatives.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyFaceShapes(), and Assembly::copyShapes().
connectControllableParams()
void MooseBaseParameterInterface::connectControllableParams (const std::string & parameter, const std::string & object_type, const std::string & object_name, const std::string & object_parameter) const inherited
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
Parameters
parameter Name of the controllable parameter of this action
object_type Type of the object added by this action.
object_name Name of the object added by this action.
object_parameter Name of the parameter of the object.
Definition at line 34 of file MooseBaseParameterInterface.C.
{
  MooseObjectParameterName primary_name(uniqueName(), parameter);
  const auto base_type = _factory.getValidParams(object_type).get<std::string>("_moose_base");
  MooseObjectParameterName secondary_name(base_type, object_name, object_parameter);
  _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
      primary_name, secondary_name);
  const auto & tags = _pars.get<std::vector<std::string>>("control_tags");
  for (const auto & tag : tags)
  {
    if (!tag.empty())
    {
      MooseObjectParameterName tagged_name(tag, _moose_base->name(), parameter);
      _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
          tagged_name, secondary_name);
    }
  }
}
count()
unsigned int MooseVariableBase::count () const inline inherited
Get the number of components Note: For standard and vector variables, the number is one.
Definition at line 109 of file MooseVariableBase.h.
{ return _count; }
Referenced by Assembly::addJacobianBlock(), EigenProblem::adjustEigenVector(), ArrayBodyForce::ArrayBodyForce(), ArrayConstantIC::ArrayConstantIC(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayFunctionIC::ArrayFunctionIC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), BuildArrayVariableAux::BuildArrayVariableAux(), Assembly::cacheJacobianBlock(), Assembly::cacheJacobianBlockNonzero(), TagAuxBase< T >::checkCoupledVariable(), BuildArrayVariableAux::compute(), ArrayNodalBC::computeJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), ArrayNodalBC::computeOffDiagJacobian(), ArrayIntegratedBC::computeQpJacobian(), ArrayNodalBC::computeQpJacobian(), ArrayKernel::computeQpJacobian(), EigenArrayDirichletBC::computeQpJacobian(), ArrayCoupledTimeDerivative::computeQpJacobian(), ArrayDiffusion::computeQpJacobian(), ArrayReaction::computeQpJacobian(), ArrayTimeDerivative::computeQpJacobian(), ArrayIntegratedBC::computeQpOffDiagJacobian(), ArrayKernel::computeQpOffDiagJacobian(), ArrayCoupledTimeDerivative::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), ArrayNodalBC::computeQpOffDiagJacobian(), EigenArrayDirichletBC::computeQpOffDiagJacobian(), Kernel::computeQpOffDiagJacobianArray(), ArrayIntegratedBC::computeQpOffDiagJacobianScalar(), ArrayKernel::computeQpOffDiagJacobianScalar(), ArrayCoupledTimeDerivative::computeQpResidual(), ArrayReaction::computeQpResidual(), ArrayTimeDerivative::computeQpResidual(), ArrayParsedAux::computeValue(), FunctionArrayAux::computeValue(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), FunctionArrayAux::FunctionArrayAux(), ArrayFunctionIC::gradient(), AdvancedOutput::initAvailableLists(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), ArrayDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), Assembly::prepareJacobianBlock(), Assembly::prepareLowerD(), Assembly::prepareNeighbor(), Assembly::prepareNonlocal(), Assembly::prepareVariable(), Assembly::prepareVariableNonlocal(), MultiAppDofCopyTransfer::transfer(), MultiAppDofCopyTransfer::transferDofObject(), and ArrayFunctionIC::value().
curlPhi()
template<typename OutputType > virtual const FieldVariablePhiValue & MooseVariableField< OutputType >::curlPhi () const pure virtual
Curl of the shape functions.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
currentElem()
virtual const Elem *const & MooseVariableFieldBase::currentElem () const pure virtual inherited
Current element this variable is evaluated at.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
customSetup() [1/2]
virtual void SetupInterface::customSetup (const ExecFlagType &) inline virtual inherited
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
Reimplemented in Function.
Definition at line 61 of file SetupInterface.h.
{}
customSetup() [2/2]
void Moose::FunctorBase< Moose::ADType< OutputType >::type >::customSetup (const ExecFlagType & exec_type) override virtual inherited
Implements Moose::FunctorAbstract.
Definition at line 134 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(exec_type))
    clearCacheData();
}
divPhi()
template<typename OutputType > virtual const FieldVariablePhiDivergence & MooseVariableField< OutputType >::divPhi () const pure virtual
Divergence of the shape functions.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
doDerivatives()
bool MooseVariableBase::doDerivatives () const protected inherited
Returns
whether we should insert derivatives
dofIndices()
virtual const std::vector< dof_id_type > & MooseVariableBase::dofIndices () const inline virtual inherited
Get local DoF indices.
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 142 of file MooseVariableBase.h.
{ return _dof_indices; }
Referenced by Assembly::addJacobianCoupledVarPair(), Assembly::cacheJacobianCoupledVarPair(), AuxScalarKernel::compute(), ADScalarKernel::computeADJacobian(), ADMortarScalarBase::computeJacobian(), ADKernelScalarBase::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVScalarLagrangeMultiplierInterface::computeJacobian(), ADMortarConstraint::computeJacobian(), MortarConstraint::computeJacobian(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), FVScalarLagrangeMultiplierConstraint::computeOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), ADPenaltyPeriodicSegmentalConstraint::computeQpResidual(), ADPeriodicSegmentalConstraint::computeQpResidual(), ADMortarScalarBase::computeResidual(), MortarScalarBase::computeResidual(), ADKernelScalarBase::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), FVScalarLagrangeMultiplierInterface::computeResidual(), ADKernelScalarBase::computeResidualAndJacobian(), FVScalarLagrangeMultiplierConstraint::computeResidualAndJacobian(), MortarScalarBase::computeScalarJacobian(), KernelScalarBase::computeScalarJacobian(), MortarScalarBase::computeScalarOffDiagJacobian(), KernelScalarBase::computeScalarOffDiagJacobian(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), ADPenaltyPeriodicSegmentalConstraint::computeScalarQpResidual(), KernelScalarBase::computeScalarResidual(), ScalarVariable::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), Exodus::outputScalarVariables(), Nemesis::outputScalarVariables(), TableOutput::outputScalarVariables(), Assembly::prepareJacobianBlock(), Assembly::prepareLowerD(), Assembly::prepareNeighbor(), Assembly::prepareNonlocal(), Assembly::prepareVariable(), Assembly::prepareVariableNonlocal(), FEProblemBase::projectInitialConditionOnCustomRange(), and FEProblemBase::projectSolution().
dofIndicesLower()
virtual const std::vector< dof_id_type > & MooseVariableFieldBase::dofIndicesLower () const pure virtual inherited
Get dof indices for the current lower dimensional element (this is meaningful when performing mortar FEM)
Returns
the lower dimensional element's dofs
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by MortarConstraint::computeJacobian(), MortarScalarBase::computeScalarOffDiagJacobian(), and Assembly::prepareLowerD().
dofIndicesNeighbor()
virtual const std::vector< dof_id_type > & MooseVariableFieldBase::dofIndicesNeighbor () const pure virtual inherited
Get neighbor DOF indices for currently selected element.
Returns
the neighbor degree of freedom indices
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by ADMortarConstraint::computeJacobian(), MortarConstraint::computeJacobian(), NodeFaceConstraint::computeOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), MortarScalarBase::computeScalarOffDiagJacobian(), Assembly::prepareLowerD(), and Assembly::prepareNeighbor().
dofMap()
const DofMap & MooseVariableBase::dofMap () const inline inherited
The DofMap associated with the system this variable is in.
Definition at line 131 of file MooseVariableBase.h.
{ return _dof_map; }
Referenced by AuxScalarKernel::compute(), and ScalarVariable::execute().
dofValues()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValues () const pure virtual
dof values getters
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesDot()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesDot () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesDotDot()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesDotDot () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesDotDotNeighbor()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesDotDotNeighbor () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesDotDotOld()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesDotDotOld () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesDotDotOldNeighbor()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesDotDotOldNeighbor () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesDotNeighbor()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesDotNeighbor () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesDotOld()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesDotOld () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesDotOldNeighbor()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesDotOldNeighbor () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesDuDotDotDu()
template<typename OutputType > virtual const MooseArray< Number > & MooseVariableField< OutputType >::dofValuesDuDotDotDu () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesDuDotDotDuNeighbor()
template<typename OutputType > virtual const MooseArray< Number > & MooseVariableField< OutputType >::dofValuesDuDotDotDuNeighbor () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesDuDotDu()
template<typename OutputType > virtual const MooseArray< Number > & MooseVariableField< OutputType >::dofValuesDuDotDu () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesDuDotDuNeighbor()
template<typename OutputType > virtual const MooseArray< Number > & MooseVariableField< OutputType >::dofValuesDuDotDuNeighbor () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesNeighbor()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesNeighbor () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesOld()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesOld () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesOlder()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesOlder () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesOlderNeighbor()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesOlderNeighbor () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesOldNeighbor()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesOldNeighbor () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesPreviousNL()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesPreviousNL () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dofValuesPreviousNLNeighbor()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::dofValuesPreviousNLNeighbor () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
dot() [1/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluateDot overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 110 of file MooseFunctor.h.
{
  return evaluateDot(elem, state);
}
dot() [2/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 114 of file MooseFunctor.h.
{
  return evaluateDot(elem_point, state);
}
dot() [3/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 112 of file MooseFunctor.h.
{
  return evaluateDot(elem_qp, state);
}
dot() [4/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 113 of file MooseFunctor.h.
{
  return evaluateDot(elem_side_qp, state);
}
dot() [5/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const FaceArg & face, const StateArg & state) const inherited
Definition at line 111 of file MooseFunctor.h.
{
  return evaluateDot(checkFace(face), state);
}
dot() [6/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const NodeArg & node, const StateArg & state) const inherited
Definition at line 115 of file MooseFunctor.h.
{
  return evaluateDot(node, state);
}
eigen() [1/2]
bool MooseVariableBase::eigen () const inline inherited
Whether or not this variable operates on an eigen kernel.
Definition at line 158 of file MooseVariableBase.h.
{ return _is_eigen; }
Referenced by EigenProblem::adjustEigenVector().
eigen() [2/2]
void MooseVariableBase::eigen (bool eigen) inline inherited
Mark this variable as an eigen var or non-eigen var.
Definition at line 163 of file MooseVariableBase.h.
{ _is_eigen = eigen; }
Referenced by MooseVariableBase::eigen().
enabled()
virtual bool MooseObject::enabled () const inline virtual inherited
Return the enabled status of the object.
Reimplemented in EigenKernel.
Definition at line 54 of file MooseObject.h.
{ return _enabled; }
Referenced by EigenKernel::enabled().
errorPrefix()
std::string MooseBaseErrorInterface::errorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for this object:
The following <error_type> occurred in the object "<name>", of type "<type>".
Definition at line 15 of file MooseBaseErrorInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the object \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseErrorInterface::mooseError(), and MooseBaseErrorInterface::mooseWarning().
evaluate() [1/6]
virtual ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluate (const ElemArg & elem, const StateArg & state) const protected pure virtual inherited
Evaluate the functor with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
evaluate() [2/6]
virtual ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluate (const ElemPointArg & elem_point, const StateArg & state) const protected pure virtual inherited
Evaluate the functor with a given element and point.
Some example implementations of this method could perform a two-term Taylor expansion using cell-centered value and gradient
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
evaluate() [3/6]
virtual ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluate (const ElemQpArg & qp, const StateArg & state) const protected pure virtual inherited
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor evaluated at the requested state and space
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
evaluate() [4/6]
virtual ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluate (const ElemSideQpArg & side_qp, const StateArg & state) const protected pure virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor evaluated at the requested state and space
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
evaluate() [5/6]
virtual ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluate (const FaceArg & face, const StateArg & state) const protected pure virtual inherited
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor evaluated at the requested state and space
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
evaluate() [6/6]
virtual ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluate (const NodeArg & node, const StateArg & state) const protected pure virtual inherited
Implemented in MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, MooseVariableFV< T >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, and MooseVariableFE< ComputeValueType >.
evaluateDot() [1/6]
virtual DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateDot (const ElemArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor time derivative with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 282 of file MooseFunctor.h.
  {
    mooseError("Element time derivative not implemented for functor " + functorName());
  }
evaluateDot() [2/6]
virtual DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateDot (const ElemPointArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor time derivative with a given element and point.
Definition at line 322 of file MooseFunctor.h.
  {
    mooseError("Element-point time derivative not implemented for functor " + functorName());
  }
evaluateDot() [3/6]
virtual DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateDot (const ElemQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor time derivative evaluated at the requested state and space
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, and MooseVariableFE< ComputeValueType >.
Definition at line 302 of file MooseFunctor.h.
  {
    mooseError("Element quadrature point time derivative not implemented for functor " +
               functorName());
  }
evaluateDot() [4/6]
virtual DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateDot (const ElemSideQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor time derivative evaluated at the requested state and space
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, and MooseVariableFE< ComputeValueType >.
Definition at line 313 of file MooseFunctor.h.
  {
    mooseError("Element side quadrature point time derivative not implemented for functor " +
               functorName());
  }
evaluateDot() [5/6]
virtual DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateDot (const FaceArg & , const StateArg &) const inline protected virtual inherited
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor time derivative evaluated at the requested state and space
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, and MooseVariableFE< ComputeValueType >.
Definition at line 292 of file MooseFunctor.h.
  {
    mooseError("Face time derivative not implemented for functor " + functorName());
  }
evaluateDot() [6/6]
virtual DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateDot (const NodeArg & , const StateArg &) const inline protected virtual inherited
Definition at line 327 of file MooseFunctor.h.
  {
    mooseError("Time derivative at node not implemented for functor " + functorName());
  }
evaluateGradDot() [1/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const ElemArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor gradient-dot with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, and MooseVariableFE< ComputeValueType >.
Definition at line 336 of file MooseFunctor.h.
  {
    mooseError("Element gradient-dot not implemented for functor " + functorName());
  }
evaluateGradDot() [2/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const ElemPointArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor gradient-dot with a given element and point.
Definition at line 376 of file MooseFunctor.h.
  {
    mooseError("Element-point gradient-dot not implemented for functor " + functorName());
  }
evaluateGradDot() [3/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const ElemQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient-dot evaluated at the requested state and space
Definition at line 356 of file MooseFunctor.h.
  {
    mooseError("Element quadrature point gradient-dot not implemented for functor " +
               functorName());
  }
evaluateGradDot() [4/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const ElemSideQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient-dot evaluated at the requested state and space
Definition at line 367 of file MooseFunctor.h.
  {
    mooseError("Element side quadrature point gradient-dot not implemented for functor " +
               functorName());
  }
evaluateGradDot() [5/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const FaceArg & , const StateArg &) const inline protected virtual inherited
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor gradient-dot evaluated at the requested state and space
Definition at line 346 of file MooseFunctor.h.
  {
    mooseError("Face gradient-dot not implemented for functor " + functorName());
  }
evaluateGradDot() [6/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const NodeArg & , const StateArg &) const inline protected virtual inherited
Definition at line 381 of file MooseFunctor.h.
  {
    mooseError("Gradient-dot at node not implemented for functor " + functorName());
  }
evaluateGradient() [1/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradient (const ElemArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor gradient with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 229 of file MooseFunctor.h.
  {
    mooseError("Element gradient not implemented for functor " + functorName());
  }
evaluateGradient() [2/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradient (const ElemPointArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor gradient with a given element and point.
Definition at line 268 of file MooseFunctor.h.
  {
    mooseError("Element-point gradient not implemented for functor " + functorName());
  }
evaluateGradient() [3/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradient (const ElemQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient evaluated at the requested state and space
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 249 of file MooseFunctor.h.
  {
    mooseError("Element quadrature point gradient not implemented for functor " + functorName());
  }
evaluateGradient() [4/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradient (const ElemSideQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient evaluated at the requested state and space
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, and MooseVariableFE< ComputeValueType >.
Definition at line 259 of file MooseFunctor.h.
  {
    mooseError("Element side quadrature point gradient not implemented for functor " +
               functorName());
  }
evaluateGradient() [5/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradient (const FaceArg & , const StateArg &) const inline protected virtual inherited
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor gradient evaluated at the requested state and space
Reimplemented in MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 239 of file MooseFunctor.h.
  {
    mooseError("Face gradient not implemented for functor " + functorName());
  }
evaluateGradient() [6/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradient (const NodeArg & , const StateArg &) const inline protected virtual inherited
Definition at line 273 of file MooseFunctor.h.
  {
    mooseError("Gradient at node not implemented for functor " + functorName());
  }
feType()
const FEType & MooseVariableBase::feType () const inline inherited
Get the type of finite element object.
Definition at line 54 of file MooseVariableBase.h.
{ return _fe_type; }
Referenced by SetupResidualDebugAction::act(), ADDGKernel::ADDGKernel(), Assembly::adGradPhi(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), BoundsAuxBase::BoundsAuxBase(), BuildArrayVariableAux::BuildArrayVariableAux(), TagAuxBase< T >::checkCoupledVariable(), GapValueAux::computeValue(), CopyValueAux::CopyValueAux(), DGKernel::DGKernel(), MultiAppNearestNodeTransfer::execute(), moose::internal::incompatVarMsg(), AdvancedOutput::initAvailableLists(), MultiAppProjectionTransfer::initialSetup(), AdvancedOutput::initShowHideLists(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), MeshDivisionAux::MeshDivisionAux(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodalBC::NodalBC(), NodalKernel::NodalKernel(), SolutionUserObject::pointValueWrapper(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), MultiAppDofCopyTransfer::transfer(), and VectorNodalBC::VectorNodalBC().
fieldType()
virtual Moose::VarFieldType MooseVariableFieldBase::fieldType () const pure virtual inherited
Filed type of this variable.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by ArrayDGKernel::computeOffDiagElemNeighJacobian(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), and MultiAppDofCopyTransfer::transfer().
functorName()
const MooseFunctorName & Moose::FunctorBase< Moose::ADType< OutputType >::type >::functorName () const inline inherited
Return the functor name.
Definition at line 77 of file MooseFunctor.h.
{ return _functor_name; }
getBlockCoordSystem()
Moose::CoordinateSystemType BlockRestrictable::getBlockCoordSystem () protected inherited
Check if the blocks this object operates on all have the same coordinate system, and if so return it.
Definition at line 311 of file BlockRestrictable.C.
{
  if (!_blk_mesh)
    mooseError("No mesh available in BlockRestrictable::checkCoordSystem()");
  if (!_blk_feproblem)
    mooseError("No problem available in BlockRestrictable::checkCoordSystem()");
  const auto & subdomains = blockRestricted() ? blockIDs() : meshBlockIDs();
  if (subdomains.empty())
    mooseError("No subdomains found in the problem.");
  // make sure all subdomains are using the same coordinate system
  auto coord_system = _blk_feproblem->getCoordSystem(*subdomains.begin());
  for (auto subdomain : subdomains)
    if (_blk_feproblem->getCoordSystem(subdomain) != coord_system)
      mooseError("This object requires all subdomains to have the same coordinate system.");
  return coord_system;
}
getCheckedPointerParam()
template<typename T > T MooseBaseParameterInterface::getCheckedPointerParam (const std::string & name, const std::string & error_string = "") const inherited
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
The template parameter must be a pointer or an error will be thrown.
Definition at line 264 of file MooseBaseParameterInterface.h.
{
  return parameters().getCheckedPointerParam<T>(name, error_string);
}
getContinuity()
virtual FEContinuity MooseVariableBase::getContinuity () const inline virtual inherited
Return the continuity of this variable.
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 126 of file MooseVariableBase.h.
{ mooseError("Base class cannot determine this"); };
Referenced by MultiAppGeneralFieldNearestLocationTransfer::initialSetup().
getDataFileName()
std::string DataFileInterface< MooseObject >::getDataFileName (const std::string & param) const inherited
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
relative to the input file directory
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
relative to the input file directory
Definition at line 34 of file DataFileInterface.C.
{
  {
    const auto & absolute_path = _parent.template getParam<FileName>(param);
    if (MooseUtils::checkFileReadable(absolute_path, false, false, false))
    {
      _parent.paramInfo(param, "Data file '", absolute_path, "' found relative to the input file.");
      return absolute_path;
    }
  }
  const auto & relative_path = _parent.parameters().rawParamVal(param);
  return getDataFileNameByName(relative_path, &param);
}
getDataFileNameByName()
std::string DataFileInterface< MooseObject >::getDataFileNameByName (const std::string & name, const std::string * param = nullptr) const inherited
Returns the path of a data file for a given relative file path.
This can be used for hardcoded datafile names and will search the same locations as getDataFileName. The optional param pointer can be used to turn the mooseErrors this function emits into paramErrors
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
Definition at line 42 of file DataFileInterface.C.
{
  const auto share_dir = MooseUtils::pathjoin(Moose::getExecutablePath(), "..", "share");
  if (MooseUtils::pathIsDirectory(share_dir))
  {
    const auto dirs = MooseUtils::listDir(share_dir, false);
    for (const auto & data_dir : dirs)
    {
      const auto path = MooseUtils::pathjoin(data_dir, "data", relative_path);
      if (MooseUtils::checkFileReadable(path, false, false, false))
      {
        if (param)
          _parent.paramInfo(
              *param, "Data file '", path, "' found in an installed app distribution.");
        else
          mooseInfo("Data file '", path, "' found in an installed app distribution.");
        return path;
      }
    }
  }
  for (const auto & data_dir : Registry::getRegistry().getDataFilePaths())
  {
    const auto path = MooseUtils::pathjoin(data_dir, relative_path);
    if (MooseUtils::checkFileReadable(path, false, false, false))
    {
      if (param)
        _parent.paramInfo(*param, "Data file '", path, "' found in a source repository.");
      else
        mooseInfo("Data file '", path, "' found in a source repository.");
      return path;
    }
  }
  mooseException(param ? _parent.parameters().inputLocation(*param) : _parent.name(),
                 ": Unable to find data file '",
                 relative_path,
                 "' anywhere");
}
getDofIndices()
virtual void MooseVariableBase::getDofIndices (const Elem * , std::vector< dof_id_type > &) const inline virtual inherited
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 133 of file MooseVariableBase.h.
  {
    mooseError("not implemented");
  };
Referenced by MultiAppVariableValueSamplePostprocessorTransfer::execute(), NodeElemConstraint::getConnectedDofIndices(), and NodeFaceConstraint::getConnectedDofIndices().
getExecuteOnEnum()
const ExecFlagEnum & SetupInterface::getExecuteOnEnum () const inherited
Return the execute on MultiMooseEnum for this object.
Definition at line 65 of file SetupInterface.C.
{
  return _execute_enum;
}
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), MultiAppTransfer::checkMultiAppExecuteOn(), IntegralPreservingFunctionIC::initialSetup(), MultiAppConservativeTransfer::initialSetup(), Terminator::initialSetup(), ElementReporter::shouldStore(), GeneralReporter::shouldStore(), and NodalReporter::shouldStore().
getMooseApp()
MooseApp & MooseBase::getMooseApp () const inline inherited
Get the MooseApp this class is associated with.
Definition at line 35 of file MooseBase.h.
{ return _app; }
Referenced by ReporterTransferInterface::checkHasReporterValue(), Coupleable::checkWritableVar(), MooseBaseParameterInterface::connectControllableParams(), Coupleable::Coupleable(), MortarData::createMortarInterface(), EigenProblem::doFreeNonlinearPowerIterations(), Terminator::execute(), FEProblemSolve::FEProblemSolve(), SolutionInvalidInterface::flagInvalidSolutionInternal(), MaterialPropertyInterface::MaterialPropertyInterface(), MooseVariableDataFV< OutputType >::MooseVariableDataFV(), ProgressOutput::output(), MooseBaseParameterInterface::paramError(), PetscOutputInterface::petscLinearOutput(), PetscOutputInterface::petscNonlinearOutput(), PetscOutputInterface::PetscOutputInterface(), PostprocessorInterface::postprocessorsAdded(), MultiApp::preTransfer(), Reporter::Reporter(), ReporterInterface::reportersAdded(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
getOutputs()
const std::set< OutputName > & OutputInterface::getOutputs () inherited
Get the list of output objects that this class is restricted.
Returns
A set of OutputNames
Definition at line 94 of file OutputInterface.C.
{
  return _oi_outputs;
}
getParam() [1/2]
template<typename T > const T & MooseBaseParameterInterface::getParam (const std::string & name) const inherited
Retrieve a parameter for the object.
Parameters
name The name of the parameter
Returns
The value of the parameter
Definition at line 200 of file MooseBaseParameterInterface.h.
{
  return InputParameters::getParamHelper(name, _pars, static_cast<T *>(0));
}
Referenced by AddGeneralReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddPeriodicBCAction::act(), CreateDisplacedProblemAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), ConstraintWarehouse::addObject(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), ADNodalKernel::ADNodalKernel(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), PiecewiseTabularBase::buildFromJSON(), Console::Console(), FEProblemBase::createTagSolutions(), AccumulateReporter::declareLateValues(), DerivativeParsedMaterialTempl< is_ad >::DerivativeParsedMaterialTempl(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EigenKernel::EigenKernel(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), GenericConstantRankTwoTensorTempl< is_ad >::GenericConstantRankTwoTensorTempl(), MooseApp::getCheckpointDirectories(), ExecutorInterface::getExecutor(), AdvancedOutput::init(), IterationAdaptiveDT::init(), TimeSequenceStepper::init(), AttribThread::initFrom(), AttribSysNum::initFrom(), AttribResidualObject::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), Console::initialSetup(), IterationAdaptiveDT::limitDTToPostprocessorValue(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MortarConsumerInterface::MortarConsumerInterface(), NestedDivision::NestedDivision(), ConsoleUtils::outputExecutionInformation(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedMaterialTempl< is_ad >::ParsedMaterialTempl(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), ParsedODEKernel::ParsedODEKernel(), ParsedPostprocessor::ParsedPostprocessor(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), Moose::FV::setInterpolationMethod(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), TimePeriod::TimePeriod(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and VectorOfPostprocessors::VectorOfPostprocessors().
getParam() [2/2]
template<typename T1 , typename T2 > std::vector< std::pair< T1, T2 > > MooseBaseParameterInterface::getParam (const std::string & param1, const std::string & param2) const inherited
Retrieve two parameters and provide pair of parameters for the object.
Parameters
param1 The name of first parameter
param2 The name of second parameter
Returns
Vector of pairs of first and second parameters
Definition at line 257 of file MooseBaseParameterInterface.h.
{
  return _pars.get<T1, T2>(param1, param2);
}
getRenamedParam()
template<typename T > const T & MooseBaseParameterInterface::getRenamedParam (const std::string & old_name, const std::string & new_name) const inherited
Retrieve a renamed parameter for the object.
This helper makes sure we check both names before erroring, and that only one parameter is passed to avoid silent errors
Parameters
old_name the old name for the parameter
new_name the new name for the parameter
Definition at line 207 of file MooseBaseParameterInterface.h.
{
  // this enables having a default on the new parameter but bypassing it with the old one
  // Most important: accept new parameter
  if (isParamSetByUser(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Second most: accept old parameter
  else if (isParamValid(old_name) && !isParamSetByUser(new_name))
    return InputParameters::getParamHelper(old_name, _pars, static_cast<T *>(0));
  // Third most: accept default for new parameter
  else if (isParamValid(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Refuse: no default, no value passed
  else if (!isParamValid(old_name) && !isParamValid(new_name))
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' is being retrieved without being set.\n"
               "Did you misspell it?");
  // Refuse: both old and new parameters set by user
  else
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' may not be provided alongside former parameter '" + old_name + "'");
}
getSolution()
template<typename OutputType > const NumericVector< Number > & MooseVariableField< OutputType >::getSolution (const Moose::StateArg & state) const protected
Get the solution corresponding to the provided state.
Definition at line 60 of file MooseVariableField.C.
{
  // It's not safe to use solutionState(0) because it returns the libMesh System solution member
  // which is wrong during things like finite difference Jacobian evaluation, e.g. when PETSc
  // perturbs the solution vector we feed these perturbations into the current_local_solution
  // while the libMesh solution is frozen in the non-perturbed state
  return (state.state == 0) ? *this->_sys.currentSolution()
                            : this->_sys.solutionState(state.state, state.iteration_type);
}
gradDot() [1/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluateGradDot overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 123 of file MooseFunctor.h.
{
  return evaluateGradDot(elem, state);
}
gradDot() [2/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 127 of file MooseFunctor.h.
{
  return evaluateGradDot(elem_point, state);
}
gradDot() [3/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 125 of file MooseFunctor.h.
{
  return evaluateGradDot(elem_qp, state);
}
gradDot() [4/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 126 of file MooseFunctor.h.
{
  return evaluateGradDot(elem_side_qp, state);
}
gradDot() [5/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const FaceArg & face, const StateArg & state) const inherited
Definition at line 124 of file MooseFunctor.h.
{
  return evaluateGradDot(checkFace(face), state);
}
gradDot() [6/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const NodeArg & node, const StateArg & state) const inherited
Definition at line 128 of file MooseFunctor.h.
{
  return evaluateGradDot(node, state);
}
gradient() [1/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluateGradient overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 97 of file MooseFunctor.h.
{
  return evaluateGradient(elem, state);
}
gradient() [2/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 101 of file MooseFunctor.h.
{
  return evaluateGradient(elem_point, state);
}
gradient() [3/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 99 of file MooseFunctor.h.
{
  return evaluateGradient(elem_qp, state);
}
gradient() [4/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 100 of file MooseFunctor.h.
{
  return evaluateGradient(elem_side_qp, state);
}
gradient() [5/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const FaceArg & face, const StateArg & state) const inherited
Definition at line 98 of file MooseFunctor.h.
{
  return evaluateGradient(checkFace(face), state);
}
gradient() [6/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const NodeArg & node, const StateArg & state) const inherited
Definition at line 102 of file MooseFunctor.h.
{
  return evaluateGradient(node, state);
}
gradPhi()
template<typename OutputType > virtual const FieldVariablePhiGradient & MooseVariableField< OutputType >::gradPhi () const pure virtual
Return the gradients of the variable's elemental shape functions.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyShapes().
gradPhiFace()
template<typename OutputType > virtual const FieldVariablePhiGradient & MooseVariableField< OutputType >::gradPhiFace () const pure virtual
Return the gradients of the variable's shape functions on an element face.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyFaceShapes().
gradPhiFaceNeighbor()
template<typename OutputType > virtual const FieldVariablePhiGradient & MooseVariableField< OutputType >::gradPhiFaceNeighbor () const pure virtual
Return the gradients of the variable's shape functions on a neighboring element face.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyNeighborShapes().
gradPhiNeighbor()
template<typename OutputType > virtual const FieldVariablePhiGradient & MooseVariableField< OutputType >::gradPhiNeighbor () const pure virtual
Return the gradients of the variable's shape functions on a neighboring element.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyNeighborShapes().
gradSln()
template<typename OutputType > virtual const FieldVariableGradient & MooseVariableField< OutputType >::gradSln () const pure virtual
element gradients
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
gradSlnNeighbor()
template<typename OutputType > virtual const FieldVariableGradient & MooseVariableField< OutputType >::gradSlnNeighbor () const pure virtual
neighbor solution gradients
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
gradSlnOld()
template<typename OutputType > virtual const FieldVariableGradient & MooseVariableField< OutputType >::gradSlnOld () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
gradSlnOldNeighbor()
template<typename OutputType > virtual const FieldVariableGradient & MooseVariableField< OutputType >::gradSlnOldNeighbor () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
hasBlockMaterialProperty()
template<typename T , bool is_ad> bool BlockRestrictable::hasBlockMaterialProperty (const std::string & prop_name) inherited
Check if a material property is valid for all blocks of this object.
This method returns true if the supplied property name has been declared in a Material object on the block ids for this object.
Template Parameters
T The type of material property
Parameters
prop_name the name of the property to query
Returns
true if the property exists for all block ids of the object, otherwise false
See also
Material::hasBlockMaterialProperty
Definition at line 264 of file BlockRestrictable.h.
{
  mooseAssert(_blk_material_data != NULL, "MaterialData pointer is not defined");
  return hasBlockMaterialPropertyHelper(prop_name) &&
         _blk_material_data->haveGenericProperty<T, is_ad>(prop_name);
}
hasBlockMaterialPropertyHelper()
bool BlockRestrictable::hasBlockMaterialPropertyHelper (const std::string & prop_name) protected virtual inherited
A helper method to allow the Material object to specialize the behavior of hasBlockMaterialProperty.
It also avoid circular #include problems.
See also
hasBlockMaterialProperty
Definition at line 275 of file BlockRestrictable.C.
{
  // Reference to MaterialWarehouse for testing and retrieving block ids
  const MaterialWarehouse & warehouse = _blk_feproblem->getMaterialWarehouse();
  // Complete set of ids that this object is active
  const std::set<SubdomainID> & ids = blockRestricted() ? blockIDs() : meshBlockIDs();
  // Loop over each id for this object
  for (const auto & id : ids)
  {
    // Storage of material properties that have been DECLARED on this id
    std::set<std::string> declared_props;
    // If block materials exist, populated the set of properties that were declared
    if (warehouse.hasActiveBlockObjects(id))
    {
      const std::vector<std::shared_ptr<MaterialBase>> & mats = warehouse.getActiveBlockObjects(id);
      for (const auto & mat : mats)
      {
        const std::set<std::string> & mat_props = mat->getSuppliedItems();
        declared_props.insert(mat_props.begin(), mat_props.end());
      }
    }
    // If the supplied property is not in the list of properties on the current id, return false
    if (declared_props.find(prop_name) == declared_props.end())
      return false;
  }
  // If you get here the supplied property is defined on all blocks
  return true;
}
Referenced by BlockRestrictable::hasBlockMaterialProperty().
hasBlocks() [1/5]
bool BlockRestrictable::hasBlocks (const std::set< SubdomainID > & ids) const inherited
Test if the supplied set of block ids are valid for this object.
Parameters
ids A std::set of SubdomainIDs to check
Returns
True if all of the given ids are found within the ids for this object
See also
isSubset
Definition at line 237 of file BlockRestrictable.C.
{
  if (_blk_ids.empty() || _blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return true;
  else
    return std::includes(_blk_ids.begin(), _blk_ids.end(), ids.begin(), ids.end());
}
hasBlocks() [2/5]
bool BlockRestrictable::hasBlocks (const std::vector< SubdomainID > & ids) const inherited
Test if the supplied vector block ids are valid for this object.
Parameters
ids A vector of SubdomainIDs ids to check
Returns
True if all of the given ids are found within the ids for this object
Definition at line 230 of file BlockRestrictable.C.
{
  std::set<SubdomainID> ids_set(ids.begin(), ids.end());
  return hasBlocks(ids_set);
}
hasBlocks() [3/5]
bool BlockRestrictable::hasBlocks (const std::vector< SubdomainName > & names) const inherited
Test if the supplied vector of block names are valid for this object.
Parameters
names A vector of SubdomainNames to check
Returns
True if the given ids are valid for this object
Definition at line 215 of file BlockRestrictable.C.
{
  return hasBlocks(_blk_mesh->getSubdomainIDs(names));
}
hasBlocks() [4/5]
template<typename OutputType > bool MooseVariableField< OutputType >::hasBlocks (const SubdomainID) const inline override virtual
Returns whether the functor is defined on this block.
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 370 of file MooseVariableField.h.
{ return BlockRestrictable::hasBlocks(id); }
Referenced by Coupleable::checkWritableVar(), GradientJumpIndicator::computeQpIntegral(), ProjectionAux::computeValue(), Moose::FV::determineElemOneAndTwo(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), and FVInterfaceKernel::FVInterfaceKernel().
hasBlocks() [5/5]
bool BlockRestrictable::hasBlocks (const SubdomainName & name) const inherited
Test if the supplied block name is valid for this object.
Parameters
name A SubdomainName to check
Returns
True if the given id is valid for this object
Definition at line 205 of file BlockRestrictable.C.
{
  // Create a vector and utilize the getSubdomainIDs function, which
  // handles the ANY_BLOCK_ID (getSubdomainID does not)
  std::vector<SubdomainName> names(1);
  names[0] = name;
  return hasBlocks(_blk_mesh->getSubdomainIDs(names));
}
Referenced by DiracKernelBase::addPoint(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), DomainUserObject::checkVariable(), ComputeJacobianThread::compute(), DomainUserObject::DomainUserObject(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), ExtraIDIntegralVectorPostprocessor::execute(), MeshDivisionFunctorReductionVectorPostprocessor::execute(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), MooseVariableField< OutputType >::hasBlocks(), BlockRestrictable::hasBlocks(), FVFluxKernel::hasFaceSide(), and PointwiseRenormalizeVector::PointwiseRenormalizeVector().
hasDoFsOnNodes()
virtual bool MooseVariableBase::hasDoFsOnNodes () const inline virtual inherited
Does this variable have DoFs on nodes.
Returns
true if it does, false if not.
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 121 of file MooseVariableBase.h.
{ mooseError("Base class cannot determine this"); };
hasFaceSide()
bool Moose::FunctorBase< Moose::ADType< OutputType >::type >::hasFaceSide (const FaceInfo & fi, const bool fi_elem_side) const override virtual inherited
Implements FaceArgInterface.
Definition at line 169 of file MooseFunctor.h.
{
  if (fi_elem_side)
    return hasBlocks(fi.elem().subdomain_id());
  else
    return fi.neighborPtr() && hasBlocks(fi.neighbor().subdomain_id());
}
initializeBlockRestrictable()
void BlockRestrictable::initializeBlockRestrictable (const MooseObject * moose_object) protected inherited
An initialization routine needed for dual constructors.
Definition at line 74 of file BlockRestrictable.C.
{
  // If the mesh pointer is not defined, but FEProblemBase is, get it from there
  if (_blk_feproblem != NULL && _blk_mesh == NULL)
    _blk_mesh = &_blk_feproblem->mesh();
  // Check that the mesh pointer was defined, it is required for this class to operate
  if (_blk_mesh == NULL)
    mooseError("The input parameters must contain a pointer to FEProblem via '_fe_problem' or a "
               "pointer to the MooseMesh via '_mesh'");
  // Populate the MaterialData pointer
  if (_blk_feproblem != NULL)
    _blk_material_data = &_blk_feproblem->getMaterialData(Moose::BLOCK_MATERIAL_DATA, _blk_tid);
  // The 'block' input is defined
  if (moose_object->isParamValid("block"))
  {
    // Extract the blocks from the input
    _blocks = moose_object->getParam<std::vector<SubdomainName>>("block");
    // Store the IDs in a set, handling ANY_BLOCK_ID if supplied
    if (std::find(_blocks.begin(), _blocks.end(), "ANY_BLOCK_ID") != _blocks.end())
      _blk_ids.insert(Moose::ANY_BLOCK_ID);
    else
    {
      // Get the IDs from the supplied names
      _vec_ids = _blk_mesh->getSubdomainIDs(_blocks);
      _blk_ids.insert(_vec_ids.begin(), _vec_ids.end());
    }
  }
  // When 'blocks' is not set and there is a "variable", use the blocks from the variable
  else if (moose_object->isParamValid("variable"))
  {
    std::string variable_name = moose_object->parameters().getMooseType("variable");
    if (!variable_name.empty())
      _blk_ids = _blk_feproblem
                     ->getVariable(_blk_tid,
                                   variable_name,
                                   Moose::VarKindType::VAR_ANY,
                                   Moose::VarFieldType::VAR_FIELD_ANY)
                     .activeSubdomains();
  }
  // Produce error if the object is not allowed to be both block and boundary restricted
  if (!_blk_dual_restrictable && !_boundary_ids.empty() && !_boundary_ids.empty())
    if (!_boundary_ids.empty() && _boundary_ids.find(Moose::ANY_BOUNDARY_ID) == _boundary_ids.end())
      moose_object->paramError("block",
                               "Attempted to restrict the object '",
                               _blk_name,
                               "' to a block, but the object is already restricted by boundary");
  // If no blocks were defined above, specify that it is valid on all blocks
  if (_blk_ids.empty() && !moose_object->isParamValid("boundary"))
  {
    _blk_ids.insert(Moose::ANY_BLOCK_ID);
    _blocks = {"ANY_BLOCK_ID"};
  }
  // If this object is block restricted, check that defined blocks exist on the mesh
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) == _blk_ids.end())
  {
    const std::set<SubdomainID> & valid_ids = _blk_mesh->meshSubdomains();
    std::vector<SubdomainID> diff;
    std::set_difference(_blk_ids.begin(),
                        _blk_ids.end(),
                        valid_ids.begin(),
                        valid_ids.end(),
                        std::back_inserter(diff));
    if (!diff.empty())
    {
      std::ostringstream msg;
      auto sep = " ";
      msg << "the following blocks (ids) do not exist on the mesh:";
      for (const auto & id : diff)
      {
        if (_blk_name.size() > 0)
        {
          auto & name =
              _blocks.at(std::find(_vec_ids.begin(), _vec_ids.end(), id) - _vec_ids.begin());
          if (std::to_string(id) != name)
            msg << sep << name << " (" << id << ")";
          else
            msg << sep << id;
        }
        else
          msg << sep << id;
        sep = ", ";
      }
      moose_object->paramError("block", msg.str());
    }
  }
  // Get the mesh dimension for the blocks
  if (blockRestricted())
    _blk_dim = _blk_mesh->getBlocksMaxDimension(_blocks);
  else
    _blk_dim = _blk_mesh->dimension();
}
Referenced by BlockRestrictable::BlockRestrictable().
initialSetup()
void MooseVariableBase::initialSetup () override virtual inherited
Gets called at the beginning of the simulation before this object is asked to do its job.
Reimplemented from SetupInterface.
Definition at line 187 of file MooseVariableBase.C.
{
  // Currently the scaling vector is only used through AD residual computing objects
  if (_subproblem.haveADObjects() &&
      (_subproblem.automaticScaling() || (std::find_if(_scaling_factor.begin(),
                                                       _scaling_factor.end(),
                                                       [](const Real element) {
                                                         return !MooseUtils::absoluteFuzzyEqual(
                                                             element, 1.);
                                                       }) != _scaling_factor.end())))
    _sys.addScalingVector();
}
insert()
virtual void MooseVariableFieldBase::insert (NumericVector< Number > & residual) pure virtual inherited
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by ConstraintWarehouse::subdomainsCovered().
isArray()
virtual bool MooseVariableFieldBase::isArray () const pure virtual inherited
Returns
true if this is an array variable, false otherwise.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by MooseVariableFieldBase::componentName(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), AdvancedOutput::initAvailableLists(), AdvancedOutput::initShowHideLists(), and MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer().
isBlockSubset() [1/2]
bool BlockRestrictable::isBlockSubset (const std::set< SubdomainID > & ids) const inherited
Test if the class block ids are a subset of the supplied objects.
Parameters
ids A std::set of Subdomains to check
Returns
True if all of the block ids for this class are found within the given ids (opposite of hasBlocks)
See also
hasBlocks
Definition at line 246 of file BlockRestrictable.C.
{
  // An empty input is assumed to be ANY_BLOCK_ID
  if (ids.empty() || ids.find(Moose::ANY_BLOCK_ID) != ids.end())
    return true;
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return std::includes(ids.begin(),
                         ids.end(),
                         _blk_mesh->meshSubdomains().begin(),
                         _blk_mesh->meshSubdomains().end());
  else
    return std::includes(ids.begin(), ids.end(), _blk_ids.begin(), _blk_ids.end());
}
Referenced by BlockRestrictable::checkVariable(), BlockRestrictable::isBlockSubset(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), and ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux().
isBlockSubset() [2/2]
bool BlockRestrictable::isBlockSubset (const std::vector< SubdomainID > & ids) const inherited
Test if the class block ids are a subset of the supplied objects.
Parameters
ids A std::vector of Subdomains to check
Returns
True if all of the block ids for this class are found within the given ids (opposite of hasBlocks)
See also
hasBlocks
Definition at line 262 of file BlockRestrictable.C.
{
  std::set<SubdomainID> ids_set(ids.begin(), ids.end());
  return isBlockSubset(ids_set);
}
isConstant()
virtual bool Moose::FunctorBase< Moose::ADType< OutputType >::type >::isConstant () const inline virtual inherited
Returns true if this functor is a constant.
Definition at line 167 of file MooseFunctor.h.
{ return false; }
isExtrapolatedBoundaryFace()
virtual bool Moose::FunctorBase< Moose::ADType< OutputType >::type >::isExtrapolatedBoundaryFace (const FaceInfo & , const Elem * , const StateArg &) const inline virtual inherited
Returns whether this (sided) face is an extrapolated boundary face for this functor.
Reimplemented in MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 154 of file MooseFunctor.h.
  {
    mooseError("not implemented");
  }
isFV()
virtual bool MooseVariableFieldBase::isFV () const inline virtual inherited
Reimplemented in MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 86 of file MooseVariableFieldBase.h.
{ return false; }
Referenced by ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), ComputeFullJacobianThread::computeOnInterface(), ComputeFullJacobianThread::computeOnInternalFace(), GradientJumpIndicator::computeQpIntegral(), InternalSideIndicator::finalize(), and FVInitialConditionTempl< T >::FVInitialConditionTempl().
isInternalFace()
bool Moose::FunctorBase< Moose::ADType< OutputType >::type >::isInternalFace (const FaceInfo & fi) const inherited
Returns true if the face is an internal face.
Definition at line 162 of file MooseFunctor.h.
{
  if (!fi.neighborPtr())
    return false;
  return hasBlocks(fi.elem().subdomain_id()) && hasBlocks(fi.neighborPtr()->subdomain_id());
}
isNodal()
virtual bool MooseVariableBase::isNodal () const inline virtual inherited
Is this variable nodal.
Returns
true if it nodal, otherwise false
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 115 of file MooseVariableBase.h.
{ mooseError("Base class cannot determine this"); }
Referenced by InitialConditionWarehouse::addObject(), BoundsAuxBase::BoundsAuxBase(), MooseVariableBase::componentDofIndices(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), and MeshDivisionAux::MeshDivisionAux().
isNodalDefined()
virtual bool MooseVariableFieldBase::isNodalDefined () const pure virtual inherited
Is this variable defined at nodes.
Returns
true if it the variable is defined at nodes, otherwise false
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
isParamSetByUser()
bool MooseBaseParameterInterface::isParamSetByUser (const std::string & nm) const inline inherited
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
Parameters
nm The name of the parameter to test
Definition at line 108 of file MooseBaseParameterInterface.h.
{ return _pars.isParamSetByUser(nm); }
Referenced by SetAdaptivityOptionsAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), LibtorchNeuralNetControl::conditionalParameterError(), MooseBaseParameterInterface::getRenamedParam(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), PiecewiseTabularBase::PiecewiseTabularBase(), MooseMesh::prepare(), and SolutionUserObject::readXda().
isParamValid()
bool MooseBaseParameterInterface::isParamValid (const std::string & name) const inline inherited
Test if the supplied parameter is valid.
Parameters
name The name of the parameter to test
Definition at line 102 of file MooseBaseParameterInterface.h.
{ return _pars.isParamValid(name); }
Referenced by AddDriftDiffusionAction::act(), AddSpecies::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CopyNodalVarsAction::act(), CreateDisplacedProblemAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), AddGeneralReactions::AddGeneralReactions(), AddZapdosReactions::AddZapdosReactions(), AdvectiveFluxAux::AdvectiveFluxAux(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), GeneratedMesh::buildMesh(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), ChemicalReactionsBase::ChemicalReactionsBase(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), CombinerGenerator::CombinerGenerator(), CSVReader::CSVReader(), ConstantReporter::declareConstantReporterValues(), DGKernelBase::DGKernelBase(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EEDFEnergyTownsendLog::EEDFEnergyTownsendLog(), Eigenvalue::Eigenvalue(), ElectronEnergyTermRate::ElectronEnergyTermRate(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), PIDTransientControl::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FileOutput::FileOutput(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FunctionDT::FunctionDT(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getRenamedParam(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), Terminator::handleMessage(), HeavySpeciesTempl< is_ad >::HeavySpeciesTempl(), HFEMDirichletBC::HFEMDirichletBC(), EigenExecutionerBase::init(), Eigenvalue::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), MooseParsedFunction::initialSetup(), MooseParsedGradFunction::initialSetup(), MooseParsedVectorFunction::initialSetup(), PiecewiseTabularBase::initialSetup(), SolutionFunction::initialSetup(), Console::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), IterationAdaptiveDT::IterationAdaptiveDT(), LeastSquaresFit::LeastSquaresFit(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MatCoupledForce::MatCoupledForce(), MooseMesh::MooseMesh(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarConsumerInterface::MortarConsumerInterface(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalExtremeValue::NodalExtremeValue(), EigenExecutionerBase::normalizeSolution(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PetscOutput::PetscOutput(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), PicardSolve::PicardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseTabularBase::PiecewiseTabularBase(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), MooseMesh::prepare(), MultiApp::readCommandLineArguments(), SolutionUserObject::readExodusII(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), MooseMesh::setCoordSystem(), FileOutput::setFileBase(), FileOutput::setFileBaseInternal(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SideDiffusiveFluxIntegralTempl< is_ad, T >::SideDiffusiveFluxIntegralTempl(), SideExtremeValue::SideExtremeValue(), SolutionUserObject::SolutionUserObject(), Terminator::Terminator(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), MultiAppDofCopyTransfer::transfer(), TransformGenerator::TransformGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
isVector()
virtual bool MooseVariableFieldBase::isVector () const pure virtual inherited
Returns
true if this is a vector-valued element, false otherwise.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by MortarConstraint::computeJacobian(), MortarScalarBase::computeScalarOffDiagJacobian(), and MultiAppVariableValueSamplePostprocessorTransfer::execute().
jacobianSetup()
template<typename OutputType > void MooseVariableField< OutputType >::jacobianSetup override virtual
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 44 of file MooseVariableField.C.
{
  MooseVariableFieldBase::jacobianSetup();
  FunctorBase<typename Moose::ADType<OutputType>::type>::jacobianSetup();
}
Referenced by MooseVariableFE< OutputType >::jacobianSetup().
kind()
Moose::VarKindType MooseVariableBase::kind () const inline inherited
Kind of the variable (Nonlinear, Auxiliary, ...)
Definition at line 85 of file MooseVariableBase.h.
{ return _var_kind; }
Referenced by ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), FVFluxBC::FVFluxBC(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), and PeriodicSegmentalConstraint::PeriodicSegmentalConstraint().
meshBlockIDs()
const std::set< SubdomainID > & BlockRestrictable::meshBlockIDs () const inherited
Return all of the SubdomainIDs for the mesh.
Returns
A set of all subdomians for the entire mesh
Definition at line 269 of file BlockRestrictable.C.
{
  return _blk_mesh->meshSubdomains();
}
Referenced by BlockRestrictable::checkVariable(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), and SolutionIC::initialSetup().
meshChanged()
virtual void MeshChangedInterface::meshChanged () inline virtual inherited
Called on this object when the mesh changes.
Reimplemented in GeometryBase, EqualValueBoundaryConstraint, DiracKernelBase, FVPointValueConstraint, MeshDivision, Console, Exodus, Nemesis, OversampleOutput, Positions, ExplicitTimeIntegrator, MultiAppVariableValueSamplePostprocessorTransfer, GhostingUserObject, NearestNodeNumberUO, RadialAverage, MooseVariableDataFV< OutputType >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 34 of file MeshChangedInterface.h.
{}
Referenced by MooseVariableFE< OutputType >::meshChanged(), and MooseVariableFV< OutputType >::meshChanged().
mooseDeprecated()
template<typename... Args> void MooseBaseErrorInterface::mooseDeprecated (Args &&... args) const inline inherited
Definition at line 78 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseDeprecatedStream(_console, false, true, std::forward<Args>(args)...);
  }
Referenced by FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::advanceMultiApps(), MultiApp::appProblem(), Executioner::augmentedPicardConvergenceCheck(), MooseMesh::buildSideList(), FEProblemBase::computeResidual(), AddVariableAction::determineType(), Eigenvalue::Eigenvalue(), MooseMesh::elem(), FunctionDT::FunctionDT(), RandomICBase::generateRandom(), MooseMesh::getBoundariesToElems(), Control::getExecuteOptions(), FEProblemBase::getNonlinearSystem(), FEProblemBase::getUserObjects(), FEProblemBase::hasPostprocessor(), MooseMesh::node(), FixedPointSolve::numPicardIts(), RelationshipManager::operator>=(), Executioner::picardSolve(), and MooseMesh::setBoundaryToNormalMap().
mooseError()
template<typename... Args> void MooseBaseErrorInterface::mooseError (Args &&... args) const inline inherited
Emits an error prefixed with object name and type.
Definition at line 38 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, errorPrefix("error"), std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
Referenced by HierarchicalGridPartitioner::_do_partition(), PetscExternalPartitioner::_do_partition(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AdaptivityAction::act(), AddFVICAction::act(), AddICAction::act(), AddMeshGeneratorAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVectorPostprocessorAction::act(), CheckFVBCAction::act(), CheckIntegrityAction::act(), CommonOutputAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DeprecatedBlockAction::act(), InitProblemAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetAdaptivityOptionsAction::act(), SetupMeshAction::act(), SetupMeshCompleteAction::act(), SetupPredictorAction::act(), SetupTimeStepperAction::act(), SplitMeshAction::act(), FEProblemBase::adaptMesh(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::addConstraint(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFVInitialCondition(), AddGeneralReactions::AddGeneralReactions(), FEProblemBase::addInitialCondition(), FEProblemBase::addLineSearch(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addOutput(), SubProblem::addPiecewiseByBlockLambdaFunctor(), DistributedRectilinearMeshGenerator::addPoint(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), FEProblemBase::addPostprocessor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseMesh::addQuadratureNode(), FEProblemBase::addReporter(), AddVariableAction::addVariable(), FEProblemBase::addVectorPostprocessor(), SubProblem::addVectorTag(), AddZapdosReactions::AddZapdosReactions(), ADEEDFRateConstantTownsend::ADEEDFRateConstantTownsend(), ADGasElectronMoments::ADGasElectronMoments(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), MooseVariableScalar::adUDot(), Output::advancedExecuteOn(), AdvectiveFluxAux::AdvectiveFluxAux(), ADZapdosEEDFRateConstant::ADZapdosEEDFRateConstant(), MooseVariableBase::allDofIndices(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayConstantIC::ArrayConstantIC(), ArrayFunctionIC::ArrayFunctionIC(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), Function::average(), Axisymmetric2D3DSolutionFunction::Axisymmetric2D3DSolutionFunction(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), BoltzmannSolverScalar::BoltzmannSolverScalar(), BoundingValueElementDamper::BoundingValueElementDamper(), BoundingValueNodalDamper::BoundingValueNodalDamper(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), MooseMesh::buildCoarseningMap(), MultiApp::buildComm(), DistributedRectilinearMeshGenerator::buildCube(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), PiecewiseTabularBase::buildFromXY(), MooseMesh::buildLowerDMesh(), GeneratedMesh::buildMesh(), MeshGeneratorMesh::buildMesh(), SpiralAnnularMesh::buildMesh(), TiledMesh::buildMesh(), ImageMesh::buildMesh3D(), ImageMeshGenerator::buildMesh3D(), MooseMesh::buildRefinementMap(), MaterialBase::buildRequiredMaterials(), MooseMesh::buildSideList(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), UserObjectInterface::castUserObject(), EigenExecutionerBase::chebyshev(), SubProblem::checkBlockMatProps(), SubProblem::checkBoundaryMatProps(), MooseMesh::checkCoordinateSystems(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkDisplacementOrders(), FEProblemBase::checkDuplicatePostprocessorVariableNames(), MooseMesh::checkDuplicateSubdomainNames(), MaterialBase::checkExecutionStage(), MeshGenerator::checkGetMesh(), ReporterTransferInterface::checkHasReporterValue(), FEProblemBase::checkICRestartError(), EigenExecutionerBase::checkIntegrity(), Eigenvalue::checkIntegrity(), Steady::checkIntegrity(), ExplicitTimeIntegrator::checkLinearConvergence(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), PostprocessorInterface::checkParam(), FEProblemBase::checkProblemIntegrity(), Sampler::checkReinitStatus(), MaterialBase::checkStatefulSanity(), FEProblemBase::checkUserObjects(), MultiAppTransfer::checkVariable(), DomainUserObject::checkVariable(), ChemicalReactionsBase::ChemicalReactionsBase(), MooseMesh::clone(), LibmeshPartitioner::clone(), CombinerGenerator::CombinerGenerator(), ElementSubdomainModifier::complementMovingBoundaryID(), ElementSubdomainModifier::complementMovingBoundaryName(), MooseVariableFieldBase::componentName(), CompositeFunction::CompositeFunction(), NodalPatchRecovery::compute(), VariableCondensationPreconditioner::computeDInverseDiag(), CompositionDT::computeDT(), MooseVariableFieldBase::computeFaceValues(), TimeStepper::computeFailedDT(), IterationAdaptiveDT::computeFailedDT(), TimeSequenceStepperBase::computeFailedDT(), MooseMesh::computeFiniteVolumeCoords(), FVFluxKernel::computeJacobian(), ArrayKernel::computeJacobian(), ArrayKernel::computeOffDiagJacobian(), FVElementalKernel::computeOffDiagJacobian(), MaterialBase::computeProperties(), ScalarKernel::computeQpJacobian(), ScalarKernel::computeQpResidual(), FVFluxKernel::computeResidual(), ArrayKernel::computeResidual(), FVFluxBC::computeResidual(), ResidualObject::computeResidualAndJacobian(), FVFluxKernel::computeResidualAndJacobian(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualL2Norm(), FEProblemBase::computeResidualTag(), FEProblemBase::computeResidualType(), TimeStepper::computeStep(), ActuallyExplicitEuler::computeTimeDerivatives(), AStableDirk4::computeTimeDerivatives(), BDF2::computeTimeDerivatives(), CrankNicolson::computeTimeDerivatives(), ExplicitEuler::computeTimeDerivatives(), ExplicitRK2::computeTimeDerivatives(), ExplicitTVDRK2::computeTimeDerivatives(), ImplicitEuler::computeTimeDerivatives(), ImplicitMidpoint::computeTimeDerivatives(), LStableDirk2::computeTimeDerivatives(), LStableDirk3::computeTimeDerivatives(), LStableDirk4::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), FEProblemBase::computeUserObjectsInternal(), BolsigValueScalar::computeValue(), PenetrationAux::computeValue(), BuildArrayVariableAux::computeValue(), TagVectorArrayVariableAux::computeValue(), ConcentricCircleMesh::ConcentricCircleMesh(), ConditionalEnableControl::ConditionalEnableControl(), TimeStepper::constrainStep(), LibtorchNeuralNetControl::controlNeuralNet(), AddVariableAction::createInitialConditionAction(), DataRead::DataRead(), ReporterTransferInterface::declareClone(), MeshGenerator::declareMeshProperty(), ReporterTransferInterface::declareVectorClone(), FunctorRelationshipManager::delete_remote_elements(), MooseMesh::deleteRemoteElements(), BicubicSplineFunction::derivative(), MooseMesh::detectPairedSidesets(), FEProblemBase::determineNonlinearSystem(), MeshDiagnosticsGenerator::diagnosticsLog(), DiffusionRateTemp::DiffusionRateTemp(), FunctorBinnedValuesDivision::divisionIndex(), FunctorRelationshipManager::dofmap_reinit(), FEProblemBase::duplicateVariableCheck(), EEDFRateConstant::EEDFRateConstant(), EEDFRateConstantTownsend::EEDFRateConstantTownsend(), Eigenvalue::Eigenvalue(), ElectricField::ElectricField(), ElectronMobility::ElectronMobility(), ElementIntegerAux::ElementIntegerAux(), ElementQualityAux::ElementQualityAux(), ElementUOAux::ElementUOAux(), DistributedRectilinearMeshGenerator::elemId(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), MooseMesh::errorIfDistributedMesh(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), BoltzmannSolverScalar::execute(), Eigenvalue::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), ElementQualityChecker::execute(), DiscreteElementUserObject::execute(), DomainUserObject::execute(), FEProblemBase::execute(), FEProblemBase::executeControls(), MultiAppVectorPostprocessorTransfer::executeFromMultiapp(), MultiAppVectorPostprocessorTransfer::executeToMultiapp(), ExplicitSSPRungeKutta::ExplicitSSPRungeKutta(), FileOutput::FileOutput(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), ElementQualityChecker::finalize(), VerifyElementUniqueID::finalize(), VerifyNodalUniqueID::finalize(), DiscreteElementUserObject::finalize(), Transfer::find_sys(), BreakMeshByBlockGeneratorBase::findFreeBoundaryId(), FunctionDT::FunctionDT(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), GapValueAux::GapValueAux(), Gas::Gas(), GasBase::GasBase(), GasElectronMoments::GasElectronMoments(), AllSideSetsByNormalsGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundingBoxNodeSetGenerator::generate(), BreakMeshByBlockGenerator::generate(), CombinerGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshCollectionGenerator::generate(), MeshDiagnosticsGenerator::generate(), MeshExtruderGenerator::generate(), MeshRepairGenerator::generate(), MoveNodeGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), SideSetsFromNormalsGenerator::generate(), SideSetsFromPointsGenerator::generate(), SmoothMeshGenerator::generate(), SpiralAnnularMeshGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), TiledMeshGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GeneratedMesh::GeneratedMesh(), GeneratedMeshGenerator::GeneratedMeshGenerator(), MeshGenerator::generateInternal(), CircularBoundaryCorrectionGenerator::generateRadialCorrectionFactor(), RandomICBase::generateRandom(), GenericConstantMaterialTempl< is_ad >::GenericConstantMaterialTempl(), GenericConstantVectorMaterialTempl< is_ad >::GenericConstantVectorMaterialTempl(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), DisplacedProblem::getActualFieldVariable(), FEProblemBase::getActualFieldVariable(), DisplacedProblem::getArrayVariable(), FEProblemBase::getArrayVariable(), MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::getBlockConnectedBlocks(), VariableOldValueBoundsAux::getBound(), MooseMesh::getBoundaryID(), MultiApp::getBoundingBox(), MooseMesh::getCoarseningMap(), MooseVariableBase::getContinuity(), Control::getControllableParameterByName(), MooseMesh::getCoordSystem(), PropertyReadFile::getData(), TransfiniteMeshGenerator::getDiscreteEdge(), FEProblemBase::getDistribution(), MooseVariableBase::getDofIndices(), VariableCondensationPreconditioner::getDofToCondense(), TransfiniteMeshGenerator::getEdge(), GhostingUserObject::getElementalValue(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), PropertyReadFile::getElementData(), MooseMesh::getElementIDIndex(), Material::getElementIDNeighbor(), Material::getElementIDNeighborByName(), MooseMesh::getElemIDMapping(), MooseMesh::getElemIDsOnBlocks(), MultiAppFieldTransfer::getEquationSystem(), MultiApp::getExecutioner(), MultiAppTransfer::getFromMultiApp(), MultiAppTransfer::getFromMultiAppInfo(), FEProblemBase::getFunction(), SubProblem::getFunctor(), MooseMesh::getGeneralAxisymmetricCoordAxis(), DistributedRectilinearMeshGenerator::getGhostNeighbors(), BatchMaterial< Tuple, Output, Input >::getIndex(), DistributedRectilinearMeshGenerator::getIndices(), SolutionUserObject::getLocalVarIndex(), Material::getMaterialByName(), FEProblemBase::getMaterialData(), SubProblem::getMatrixTagID(), AnnularMesh::getMaxInDimension(), GeneratedMesh::getMaxInDimension(), FEProblemBase::getMaxQps(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), AnnularMesh::getMinInDimension(), GeneratedMesh::getMinInDimension(), MultiAppTransfer::getMultiApp(), DistributedRectilinearMeshGenerator::getNeighbors(), MooseMesh::getNodeBlockIds(), PropertyReadFile::getNodeData(), MooseMesh::getNodeList(), FEProblemBase::getNonlinearSystem(), MooseMesh::getPairedBoundaryMapping(), ImageMesh::GetPixelInfo(), ImageMeshGenerator::GetPixelInfo(), PlaneIDMeshGenerator::getPlaneID(), FEProblemBase::getPositionsObject(), PostprocessorInterface::getPostprocessorValueByNameInternal(), MooseMesh::getRefinementMap(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), FEProblemBase::getSampler(), JSONFileReader::getScalar(), DisplacedProblem::getScalarVariable(), FEProblemBase::getScalarVariable(), DisplacedProblem::getStandardVariable(), FEProblemBase::getStandardVariable(), MooseMesh::getSubdomainBoundaryIds(), DisplacedProblem::getSystem(), FEProblemBase::getSystem(), FEProblemBase::getTimeFromStateArg(), Transient::getTimeIntegratorName(), MultiAppTransfer::getToMultiApp(), MultiAppTransfer::getToMultiAppInfo(), MooseMesh::getUniqueCoordSystem(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::getUserObjectName(), JSONFileReader::getVector(), VectorPostprocessorInterface::getVectorPostprocessorName(), SubProblem::getVectorTag(), SubProblem::getVectorTagID(), DisplacedProblem::getVectorVariable(), FEProblemBase::getVectorVariable(), GhostingAux::GhostingAux(), MultiApp::globalAppToLocal(), Function::gradient(), MooseParsedVectorFunction::gradient(), Terminator::handleMessage(), MooseVariableBase::hasDoFsOnNodes(), PostprocessorInterface::hasPostprocessor(), PostprocessorInterface::hasPostprocessorByName(), ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), AddVariableAction::init(), MooseMesh::init(), Sampler::init(), AddAuxVariableAction::init(), EigenExecutionerBase::init(), Eigenvalue::init(), Transient::init(), FEProblemBase::init(), CrankNicolson::init(), ExplicitTimeIntegrator::init(), CSVTimeSequenceStepper::init(), IterationAdaptiveDT::init(), MultiApp::init(), FEProblemBase::initialAdaptMesh(), BoltzmannSolverScalar::initialize(), PolynomialCoefficients::initialize(), CartesianGridDivision::initialize(), CylindricalGridDivision::initialize(), NestedDivision::initialize(), SphericalGridDivision::initialize(), SubProblem::initialSetup(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), Axisymmetric2D3DSolutionFunction::initialSetup(), MooseParsedFunction::initialSetup(), SolutionFunction::initialSetup(), SolutionIC::initialSetup(), FullSolveMultiApp::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), SolutionUserObject::initialSetup(), Function::integral(), InterpolatedCoefficientLinear::InterpolatedCoefficientLinear(), InterpolatedCoefficientSpline::InterpolatedCoefficientSpline(), EigenExecutionerBase::inversePowerIteration(), InversePowerMethod::InversePowerMethod(), Sampler::isAdaptiveSamplingCompleted(), MooseMesh::isBoundaryFullyExternalToSubdomains(), MooseVariableBase::isNodal(), IterationAdaptiveDT::IterationAdaptiveDT(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LineSearch::lineSearch(), ReporterPointMarker::markerSetup(), Material::Material(), MaterialOutputAction::materialOutputHelper(), MaterialRealTensorValueAux::MaterialRealTensorValueAux(), MaterialRealVectorValueAuxTempl< is_ad >::MaterialRealVectorValueAuxTempl(), Distribution::median(), FunctorRelationshipManager::mesh_reinit(), SubProblem::meshChanged(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshExtruderGenerator::MeshExtruderGenerator(), MeshRepairGenerator::MeshRepairGenerator(), SetupMeshAction::modifyParamsForUseSplit(), MeshMetaDataInterface::mooseErrorInternal(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MoveNodeGenerator::MoveNodeGenerator(), ElementSubdomainModifier::movingBoundaryID(), ElementSubdomainModifier::movingBoundaryName(), MultiApp::MultiApp(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NearestNodeDistanceAux::NearestNodeDistanceAux(), NearestNodeValueAux::NearestNodeValueAux(), FEProblemBase::needsPreviousNewtonIteration(), NewmarkBeta::NewmarkBeta(), NodalPatchRecoveryBase::nodalPatchRecovery(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), DistributedRectilinearMeshGenerator::nodeId(), DistributedRectilinearMeshGenerator::numNeighbors(), Output::onInterval(), FunctorRelationshipManager::operator()(), RelationshipManager::operator==(), MortarNodalGeometryOutput::output(), Output::Output(), DistributedRectilinearMeshGenerator::paritionSquarely(), PiecewiseBilinear::parse(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), ExplicitTimeIntegrator::performExplicitSolve(), PetscExternalPartitioner::PetscExternalPartitioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), Executioner::picardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseMulticonstant::PiecewiseMulticonstant(), PiecewiseTabularBase::PiecewiseTabularBase(), SolutionUserObject::pointValueGradientWrapper(), SolutionUserObject::pointValueWrapper(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName(), AStableDirk4::postResidual(), ExplicitRK2::postResidual(), ExplicitTVDRK2::postResidual(), ImplicitMidpoint::postResidual(), LStableDirk2::postResidual(), LStableDirk3::postResidual(), LStableDirk4::postResidual(), VariableCondensationPreconditioner::preallocateCondensedJacobian(), Predictor::Predictor(), Transient::preExecute(), MooseMesh::prepare(), MooseMesh::prepared(), FixedPointSolve::printFixedPointConvergenceReason(), RateCoefficientProvider::RateCoefficientProvider(), RateCoefficientProvider::reaction_coefficient(), RateCoefficientProvider::reaction_coefficient_derivative(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readExodusII(), SolutionUserObject::readXda(), FunctorRelationshipManager::redistribute(), Sampler::reinit(), RinglebMesh::RinglebMesh(), RinglebMeshGenerator::RinglebMeshGenerator(), PiecewiseMultiInterpolation::sample(), ScalarComponentIC::ScalarComponentIC(), ScalarLinearInterpolation::ScalarLinearInterpolation(), ScalarSplineInterpolation::ScalarSplineInterpolation(), DistributedRectilinearMeshGenerator::scaleNodalPositions(), BicubicSplineFunction::secondDerivative(), FunctorRelationshipManager::set_mesh(), MooseVariableBase::setActiveTags(), DistributedRectilinearMeshGenerator::setBoundaryNames(), MooseMesh::setCoordSystem(), FEProblemBase::setCoupling(), PiecewiseBase::setData(), FileOutput::setFileBaseInternal(), MooseMesh::setGeneralAxisymmetricCoordAxes(), FEProblemSolve::setInnerSolve(), MeshGenerator::setMeshProperty(), FEProblemBase::setNonlocalCouplingMatrix(), Sampler::setNumberOfCols(), Sampler::setNumberOfRandomSeeds(), Sampler::setNumberOfRows(), Split::setup(), TransientMultiApp::setupApp(), SetupMeshAction::setupMesh(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), TimePeriodBase::setupTimes(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SideSetsFromNormalsGenerator::SideSetsFromNormalsGenerator(), SideSetsFromPointsGenerator::SideSetsFromPointsGenerator(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), SolutionTimeAdaptiveDT::SolutionTimeAdaptiveDT(), SolutionUserObject::SolutionUserObject(), FullSolveMultiApp::solveStep(), UserObject::spatialPoints(), UserObject::spatialValue(), SpiralAnnularMesh::SpiralAnnularMesh(), SpiralAnnularMeshGenerator::SpiralAnnularMeshGenerator(), StitchedMesh::StitchedMesh(), MaterialBase::subdomainSetup(), GeneralUserObject::subdomainSetup(), NodalUserObject::subdomainSetup(), Constraint::subdomainSetup(), SuperelasticReactionRate::SuperelasticReactionRate(), FEProblemBase::swapBackMaterialsNeighbor(), Terminator::Terminator(), GeneralUserObject::threadJoin(), ThreadedGeneralUserObject::threadJoin(), DiscreteElementUserObject::threadJoin(), TimePeriodBase::TimePeriodBase(), VectorPostprocessorVisualizationAux::timestepSetup(), FEProblemBase::trustUserCouplingMatrix(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), FEProblemBase::uDotDotOldRequested(), MooseVariableScalar::uDotOld(), FEProblemBase::uDotOldRequested(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), SolutionUserObject::updateExodusBracketingTimeIndices(), FEProblemBase::updateMaxQps(), BoundingBoxIC::value(), Function::value(), Axisymmetric2D3DSolutionFunction::value(), PiecewiseConstantFromCSV::value(), ValueProvider::ValueProvider(), ValueRangeMarker::ValueRangeMarker(), ValueThresholdMarker::ValueThresholdMarker(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), MultiAppTransfer::variableIntegrityCheck(), VariableTimeIntegrationAux::VariableTimeIntegrationAux(), AddVariableAction::variableType(), Function::vectorCurl(), SubProblem::vectorTagName(), SubProblem::vectorTagType(), Function::vectorValue(), MooseParsedFunction::vectorValue(), MooseParsedGradFunction::vectorValue(), SubProblem::verifyVectorTags(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
mooseErrorNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseErrorNonPrefixed (Args &&... args) const inline inherited
Emits an error without the prefixing included in mooseError().
Definition at line 50 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
mooseInfo()
template<typename... Args> void MooseBaseErrorInterface::mooseInfo (Args &&... args) const inline inherited
Definition at line 84 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseInfoStream(_console, std::forward<Args>(args)...);
  }
Referenced by AddZapdosReactions::act(), SetupRecoverFileBaseAction::act(), AStableDirk4::AStableDirk4(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), BoltzmannSolverScalar::execute(), ExplicitRK2::ExplicitRK2(), ExplicitTVDRK2::ExplicitTVDRK2(), MultiAppTransfer::getPointInTargetAppFrame(), ImplicitMidpoint::ImplicitMidpoint(), InversePowerMethod::InversePowerMethod(), LStableDirk2::LStableDirk2(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), NonlinearEigen::NonlinearEigen(), ProjectionAux::ProjectionAux(), FEProblemBase::setRestartFile(), and SymmetryTransformGenerator::SymmetryTransformGenerator().
mooseWarning()
template<typename... Args> void MooseBaseErrorInterface::mooseWarning (Args &&... args) const inline inherited
Emits a warning prefixed with object name and type.
Definition at line 62 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(
        _console, errorPrefix("warning"), std::forward<Args>(args)...);
  }
Referenced by AddFunctionAction::act(), AddKernelAction::act(), CommonOutputAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupMeshAction::act(), DumpObjectsProblem::addAuxVariable(), DiracKernelBase::addPoint(), BoundaryMarker::BoundaryMarker(), BoundsAuxBase::BoundsAuxBase(), DistributedRectilinearMeshGenerator::buildCube(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), CartesianMeshGenerator::CartesianMeshGenerator(), CheckOutputAction::checkConsoleOutput(), MultiAppTransfer::checkMultiAppExecuteOn(), GapValueAux::computeValue(), MeshDiagnosticsGenerator::diagnosticsLog(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), Postprocessor::evaluateDotWarning(), ElementQualityChecker::finalize(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FixedPointSolve::FixedPointSolve(), ElementSubdomainIDGenerator::generate(), ParsedGenerateSideset::generate(), MultiAppTransfer::getAppInfo(), FunctorBinnedValuesDivision::getBinIndex(), FEProblemBase::getMaterial(), Terminator::handleMessage(), MaterialBase::initStatefulProperties(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::mesh(), NewmarkBeta::NewmarkBeta(), NodalPatchRecovery::NodalPatchRecovery(), Output::Output(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), Executioner::problem(), PropertyReadFile::readData(), TestSourceStepper::rejectStep(), MaterialBase::resetQpProperties(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setCoordSystem(), FEProblemBase::sizeZeroes(), TransientMultiApp::solveStep(), TimeDerivativeAux::TimeDerivativeAux(), PiecewiseConstantFromCSV::value(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
mooseWarningNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseWarningNonPrefixed (Args &&... args) const inline inherited
Emits a warning without the prefixing included in mooseWarning().
Definition at line 72 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(_console, std::forward<Args>(args)...);
  }
name()
const std::string & MooseVariableBase::name () const inline override virtual inherited
Get the variable name.
Reimplemented from MooseBase.
Definition at line 69 of file MooseVariableBase.h.
{ return _var_name; }
Referenced by SetupResidualDebugAction::act(), InitialConditionWarehouse::addObject(), MooseVariableBase::allDofIndices(), ArrayParsedAux::ArrayParsedAux(), BlockRestrictable::checkVariable(), DomainUserObject::checkVariable(), Coupleable::checkWritableVar(), Coupleable::coupledName(), Moose::FV::determineElemOneAndTwo(), GreaterThanLessThanPostprocessor::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppGeometricInterpolationTransfer::fillSourceInterpolationPoints(), FunctionArrayAux::FunctionArrayAux(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), GapValueAux::GapValueAux(), MultiAppGeometricInterpolationTransfer::interpolateTargetPoints(), DerivativeMaterialInterface< T >::isNotObjectVariable(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedODEKernel::ParsedODEKernel(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ConstraintWarehouse::subdomainsCovered(), MultiAppDofCopyTransfer::transfer(), MultiAppShapeEvaluationTransfer::transferVariable(), FVFluxBC::uOnGhost(), and FVFluxBC::uOnUSub().
nodalDofIndex()
virtual const dof_id_type & MooseVariableFieldBase::nodalDofIndex () const pure virtual inherited
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by NodalPatchRecovery::compute(), and NodeElemConstraint::getConnectedDofIndices().
nodalDofIndexNeighbor()
virtual const dof_id_type & MooseVariableFieldBase::nodalDofIndexNeighbor () const pure virtual inherited
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
nodalValueArray()
template<typename OutputType > virtual const MooseArray< OutputType > & MooseVariableField< OutputType >::nodalValueArray () const pure virtual
Methods for retrieving values of variables at the nodes in a MooseArray for AuxKernelBase.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
nodalValueOldArray()
template<typename OutputType > virtual const MooseArray< OutputType > & MooseVariableField< OutputType >::nodalValueOldArray () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
nodalValueOlderArray()
template<typename OutputType > virtual const MooseArray< OutputType > & MooseVariableField< OutputType >::nodalValueOlderArray () const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
nodalVectorTagValue()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::nodalVectorTagValue (TagID tag) const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
number()
unsigned int MooseVariableBase::number () const inline inherited
Get variable number coming from libMesh.
Returns
the libmesh variable number
Definition at line 49 of file MooseVariableBase.h.
{ return _var_num; }
Referenced by AdaptivityAction::act(), Assembly::addJacobianBlock(), Assembly::addJacobianCoupledVarPair(), EigenProblem::adjustEigenVector(), MooseMesh::cacheFaceInfoVariableOwnership(), Assembly::cacheJacobianBlock(), Assembly::cacheJacobianBlockNonzero(), Assembly::cacheJacobianCoupledVarPair(), ComputeJacobianThread::compute(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayIntegratedBC::computeJacobian(), IntegratedBC::computeJacobian(), NonlocalIntegratedBC::computeJacobian(), VectorIntegratedBC::computeJacobian(), NodeElemConstraint::computeJacobian(), NodeFaceConstraint::computeJacobian(), ArrayKernel::computeJacobian(), EigenKernel::computeJacobian(), Kernel::computeJacobian(), KernelGrad::computeJacobian(), KernelValue::computeJacobian(), MassLumpedTimeDerivative::computeJacobian(), NonlocalKernel::computeJacobian(), ODEKernel::computeJacobian(), TimeDerivative::computeJacobian(), VectorKernel::computeJacobian(), VectorTimeDerivative::computeJacobian(), NodalEqualValueConstraint::computeJacobian(), ScalarKernel::computeJacobian(), FVFluxBC::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), MortarConstraint::computeJacobian(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDResidual(), DGLowerDKernel::computeLowerDResidual(), NonlocalIntegratedBC::computeNonlocalJacobian(), NonlocalKernel::computeNonlocalJacobian(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ArrayIntegratedBC::computeOffDiagJacobian(), IntegratedBC::computeOffDiagJacobian(), LowerDIntegratedBC::computeOffDiagJacobian(), NodalBC::computeOffDiagJacobian(), NonlocalIntegratedBC::computeOffDiagJacobian(), VectorIntegratedBC::computeOffDiagJacobian(), VectorNodalBC::computeOffDiagJacobian(), NodeElemConstraint::computeOffDiagJacobian(), NodeFaceConstraint::computeOffDiagJacobian(), DGLowerDKernel::computeOffDiagJacobian(), ADKernelScalarBase::computeOffDiagJacobian(), ArrayKernel::computeOffDiagJacobian(), EigenKernel::computeOffDiagJacobian(), Kernel::computeOffDiagJacobian(), KernelGrad::computeOffDiagJacobian(), KernelValue::computeOffDiagJacobian(), NonlocalKernel::computeOffDiagJacobian(), VectorKernel::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), ADDGKernel::computeOffDiagJacobian(), ADNodalKernel::computeOffDiagJacobian(), ArrayIntegratedBC::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), ArrayKernel::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), NodalScalarKernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), ComputeFullJacobianThread::computeOnInterface(), ComputeFullJacobianThread::computeOnInternalFace(), EEDFReactionLog::computeQpJacobian(), EEDFReactionTownsendLog::computeQpJacobian(), OldEqualValueConstraint::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), ArrayIntegratedBC::computeQpOffDiagJacobian(), ArrayKernel::computeQpOffDiagJacobian(), ArrayCoupledTimeDerivative::computeQpOffDiagJacobian(), ArrayDiffusion::computeQpOffDiagJacobian(), ArrayReaction::computeQpOffDiagJacobian(), ArrayTimeDerivative::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), ArrayNodalBC::computeQpOffDiagJacobian(), EEDFReactionTownsendLog::computeQpOffDiagJacobian(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), ArrayIntegratedBC::computeResidual(), ArrayLowerDIntegratedBC::computeResidual(), IntegratedBC::computeResidual(), LowerDIntegratedBC::computeResidual(), VectorIntegratedBC::computeResidual(), NodeElemConstraint::computeResidual(), NodeFaceConstraint::computeResidual(), FVElementalKernel::computeResidual(), ArrayKernel::computeResidual(), EigenKernel::computeResidual(), Kernel::computeResidual(), KernelGrad::computeResidual(), KernelValue::computeResidual(), ODEKernel::computeResidual(), ODETimeKernel::computeResidual(), TimeKernel::computeResidual(), VectorKernel::computeResidual(), VectorTimeKernel::computeResidual(), ADScalarKernel::computeResidual(), NodalEqualValueConstraint::computeResidual(), ScalarKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVFluxBC::computeResidual(), FVInterfaceKernel::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), FVScalarLagrangeMultiplierInterface::computeResidual(), ADMortarConstraint::computeResidual(), MortarConstraint::computeResidual(), IntegratedBC::computeResidualAndJacobian(), NodalBC::computeResidualAndJacobian(), Kernel::computeResidualAndJacobian(), MortarScalarBase::computeScalarOffDiagJacobian(), PenaltyPeriodicSegmentalConstraint::computeScalarQpOffDiagJacobian(), PeriodicSegmentalConstraint::computeScalarQpOffDiagJacobian(), DebugResidualAux::computeValue(), ProjectionAux::computeValue(), CoupledForceNodalKernel::CoupledForceNodalKernel(), CoupledForceTempl< is_ad >::CoupledForceTempl(), ScalarCoupleable::coupledScalar(), Moose::FV::determineElemOneAndTwo(), EconomouDielectricBC::EconomouDielectricBC(), VariableResidual::execute(), NodalNormalsCorner::execute(), NodalNormalsEvaluator::execute(), NodalNormalsPreprocessor::execute(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), ConservativeAdvection::fullUpwind(), BoundsAuxBase::getDoFIndex(), FVBoundaryCondition::hasFaceSide(), LazyCoupleable::init(), NodalNormalsPreprocessor::initialize(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), ArrayKernel::initQpOffDiagJacobian(), LowerBoundNodalKernel::LowerBoundNodalKernel(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), ComputeDiracThread::onElement(), ComputeNodalKernelBCJacobiansThread::onNode(), ComputeNodalKernelJacobiansThread::onNode(), Assembly::prepareBlock(), Assembly::prepareBlockNonlocal(), Assembly::prepareJacobianBlock(), Assembly::prepareLowerD(), Assembly::prepareNeighbor(), Assembly::prepareNonlocal(), Assembly::prepareVariable(), Assembly::prepareVariableNonlocal(), MultiAppProjectionTransfer::projectSolution(), EqualValueEmbeddedConstraint::reinitConstraint(), AddPeriodicBCAction::setPeriodicVars(), FVInterfaceKernel::setupData(), NonlinearSystemBase::setupScalingData(), MultiAppDofCopyTransfer::transferDofObject(), FVFluxBC::uOnGhost(), FVFluxBC::uOnUSub(), UpdateErrorVectorsThread::UpdateErrorVectorsThread(), UpperBoundNodalKernel::UpperBoundNodalKernel(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and MortarConstraintBase::zeroInactiveLMDofs().
numberOfDofs()
virtual unsigned int MooseVariableBase::numberOfDofs () const inline virtual inherited
Get the number of local DoFs.
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 153 of file MooseVariableBase.h.
{ return _dof_indices.size(); }
Referenced by TagVectorArrayVariableAux::compute(), BuildArrayVariableAux::compute(), and ComputeDiracThread::onElement().
numberOfDofsNeighbor()
virtual unsigned int MooseVariableFieldBase::numberOfDofsNeighbor () pure virtual inherited
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
numBlocks()
unsigned int BlockRestrictable::numBlocks () const inherited
Return the number of blocks for this object.
Returns
The number of subdomains
Definition at line 199 of file BlockRestrictable.C.
{
  return (unsigned int)_blk_ids.size();
}
Referenced by ElementCentroidPositions::initialize().
objectErrorPrefix()
std::string MooseBaseParameterInterface::objectErrorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for an object.
Definition at line 58 of file MooseBaseParameterInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the class \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseParameterInterface::paramErrorMsg().
oldestSolutionStateRequested()
virtual unsigned int MooseVariableFieldBase::oldestSolutionStateRequested () const pure virtual inherited
The oldest solution state that is requested for this variable (0 = current, 1 = old, 2 = older, etc).
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
operator()() [1/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluate overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 84 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(elem, state);
  mooseAssert(state.state == 0,
              "Cached evaluations are only currently supported for the current state.");
  return queryFVArgCache(_elem_arg_to_value, elem);
}
operator()() [2/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 88 of file MooseFunctor.h.
{
  return evaluate(elem_point, state);
}
operator()() [3/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 86 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(elem_qp, state);
  const auto elem_id = elem_qp.elem->id();
  if (elem_id != _current_qp_map_key)
  {
    _current_qp_map_key = elem_id;
    _current_qp_map_value = &_qp_to_value[elem_id];
  }
  auto & qp_data = *_current_qp_map_value;
  const auto qp = elem_qp.qp;
  const auto * const qrule = elem_qp.qrule;
  mooseAssert(qrule, "qrule must be non-null");
  return queryQpCache(qp, *qrule, qp_data, elem_qp, state);
}
operator()() [4/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 87 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(elem_side_qp, state);
  const Elem * const elem = elem_side_qp.elem;
  mooseAssert(elem, "elem must be non-null");
  const auto elem_id = elem->id();
  if (elem_id != _current_side_qp_map_key)
  {
    _current_side_qp_map_key = elem_id;
    _current_side_qp_map_value = &_side_qp_to_value[elem_id];
  }
  auto & side_qp_data = *_current_side_qp_map_value;
  const auto side = elem_side_qp.side;
  const auto qp = elem_side_qp.qp;
  const auto * const qrule = elem_side_qp.qrule;
  mooseAssert(qrule, "qrule must be non-null");
  // Check and see whether we even have sized for this side
  if (side >= side_qp_data.size())
    side_qp_data.resize(elem->n_sides());
  // Ok we were sized enough for our side
  auto & qp_data = side_qp_data[side];
  return queryQpCache(qp, *qrule, qp_data, elem_side_qp, state);
}
operator()() [5/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const FaceArg & face, const StateArg & state) const inherited
Definition at line 85 of file MooseFunctor.h.
{
  const auto face = checkFace(face_in);
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(face, state);
  mooseAssert(state.state == 0,
              "Cached evaluations are only currently supported for the current state.");
  return queryFVArgCache(_face_arg_to_value, face);
}
operator()() [6/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const NodeArg & node, const StateArg & state) const inherited
Definition at line 89 of file MooseFunctor.h.
{
  return evaluate(node, state);
}
order()
Order MooseVariableBase::order () const inherited
Get the order of this variable Note: Order enum can be implicitly converted to unsigned int.
Definition at line 149 of file MooseVariableBase.C.
{
  return _fe_type.order;
}
Referenced by FEProblemBase::checkDisplacementOrders(), AuxScalarKernel::compute(), ScalarInitialCondition::compute(), ADScalarKernel::computeADJacobian(), ODEKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVScalarLagrangeMultiplierConstraint::computeOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), DGFunctionDiffusionDirichletBC::computeQpJacobian(), DGDiffusionPostprocessorDirichletBC::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), ArrayIntegratedBC::computeQpOffDiagJacobianScalar(), ArrayKernel::computeQpOffDiagJacobianScalar(), DGFunctionDiffusionDirichletBC::computeQpResidual(), DGDiffusionPostprocessorDirichletBC::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), ODEKernel::computeResidual(), ODETimeKernel::computeResidual(), ADScalarKernel::computeResidual(), ScalarKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), ProjectionAux::computeValue(), ScalarCoupleable::coupledScalarOrder(), MultiAppPostprocessorToAuxScalarTransfer::execute(), FunctionScalarAux::FunctionScalarAux(), GapValueAux::GapValueAux(), ArrayDGDiffusion::initQpResidual(), NodalPatchRecovery::NodalPatchRecovery(), FEProblemBase::projectInitialConditionOnCustomRange(), ProjectionAux::ProjectionAux(), FEProblemBase::projectSolution(), ScalarComponentIC::ScalarComponentIC(), and MooseVariableBase::validParams().
paramError()
template<typename... Args> void MooseBaseParameterInterface::paramError (const std::string & param, Args... args) const inherited
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseError - only printing a message using the given args.
Definition at line 233 of file MooseBaseParameterInterface.h.
{
  Moose::show_trace = false;
  std::string msg = paramErrorMsg(param, std::forward<Args>(args)...);
  callMooseErrorRaw(msg, &_moose_base->getMooseApp());
  Moose::show_trace = true;
}
Referenced by HierarchicalGridPartitioner::_do_partition(), SetupDebugAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), ADDGKernel::ADDGKernel(), ReporterPointSource::addPoints(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ADNodalKernel::ADNodalKernel(), ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), AdvectiveFluxAux::AdvectiveFluxAux(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), ArrayBodyForce::ArrayBodyForce(), ArrayDGKernel::ArrayDGKernel(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayDirichletBC::ArrayDirichletBC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), ArrayPenaltyDirichletBC::ArrayPenaltyDirichletBC(), ArrayVacuumBC::ArrayVacuumBC(), BlockDeletionGenerator::BlockDeletionGenerator(), BlockWeightedPartitioner::BlockWeightedPartitioner(), BoundsAuxBase::BoundsAuxBase(), BreakMeshByBlockGenerator::BreakMeshByBlockGenerator(), BuildArrayVariableAux::BuildArrayVariableAux(), PiecewiseTabularBase::buildFromFile(), CartesianGridDivision::CartesianGridDivision(), UserObjectInterface::castUserObject(), checkComponent(), MeshGenerator::checkGetMesh(), PostprocessorInterface::checkParam(), Coupleable::checkVar(), MultiAppTransfer::checkVariable(), CircularBoundaryCorrectionGenerator::CircularBoundaryCorrectionGenerator(), CircularBoundaryCorrectionGenerator::circularCenterCalculator(), MultiAppGeneralFieldTransfer::closestToPosition(), CombinerGenerator::CombinerGenerator(), CompositionDT::CompositionDT(), ConcentricCircleMeshGenerator::ConcentricCircleMeshGenerator(), LibtorchNeuralNetControl::conditionalParameterError(), ConstantVectorPostprocessor::ConstantVectorPostprocessor(), ContainsPointAux::ContainsPointAux(), CopyValueAux::CopyValueAux(), Coupleable::Coupleable(), CoupledForceTempl< is_ad >::CoupledForceTempl(), CoupledValueFunctionMaterialTempl< is_ad >::CoupledValueFunctionMaterialTempl(), MultiApp::createApp(), MeshGeneratorSystem::createMeshGenerator(), CylindricalGridDivision::CylindricalGridDivision(), ConstantReporter::declareConstantReporterValues(), AccumulateReporter::declareLateValues(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DGLowerDKernel::DGLowerDKernel(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementLengthAux::ElementLengthAux(), ElementLpNormAux::ElementLpNormAux(), ElementValueSampler::ElementValueSampler(), ReporterPointSource::errorCheck(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), ExtraElementIDAux::ExtraElementIDAux(), ExtraElementIntegerDivision::ExtraElementIntegerDivision(), FEProblemSolve::FEProblemSolve(), FillBetweenCurvesGenerator::FillBetweenCurvesGenerator(), FillBetweenSidesetsGenerator::FillBetweenSidesetsGenerator(), ReporterPointSource::fillPoint(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), InternalSideIndicator::finalize(), FixedPointSolve::FixedPointSolve(), ForcingFunctionAux::ForcingFunctionAux(), FunctionArrayAux::FunctionArrayAux(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorAux::FunctorAux(), FunctorBinnedValuesDivision::FunctorBinnedValuesDivision(), FunctorElementalGradientAuxTempl< is_ad >::FunctorElementalGradientAuxTempl(), FunctorPositions::FunctorPositions(), FunctorVectorElementalAuxTempl< is_ad >::FunctorVectorElementalAuxTempl(), FVFluxBC::FVFluxBC(), FVInterfaceKernel::FVInterfaceKernel(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), FVTwoVarContinuityConstraint::FVTwoVarContinuityConstraint(), AdvancedExtruderGenerator::generate(), BlockDeletionGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundaryDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), BreakMeshByBlockGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), CombinerGenerator::generate(), ExplodeMeshGenerator::generate(), ExtraNodesetGenerator::generate(), FillBetweenCurvesGenerator::generate(), FillBetweenSidesetsGenerator::generate(), GeneratedMeshGenerator::generate(), MeshCollectionGenerator::generate(), MeshExtruderGenerator::generate(), ParsedCurveGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), PropertyReadFile::getBlockData(), PropertyReadFile::getData(), Sampler::getGlobalSamples(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), Sampler::getLocalSamples(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), Sampler::getNextLocalRow(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectName(), HFEMDirichletBC::HFEMDirichletBC(), MultiApp::init(), BlockWeightedPartitioner::initialize(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), PiecewiseConstantFromCSV::initialSetup(), LibtorchControlValuePostprocessor::initialSetup(), ReferenceResidualProblem::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), HistogramVectorPostprocessor::initialSetup(), AddMetaDataGenerator::inputChecker(), IntegratedBC::IntegratedBC(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceValueUserObjectAux::InterfaceValueUserObjectAux(), InterpolatedStatefulMaterialTempl< T >::InterpolatedStatefulMaterialTempl(), InversePowerMethod::InversePowerMethod(), IterationAdaptiveDT::IterationAdaptiveDT(), MultiApp::keepSolutionDuringRestore(), Kernel::Kernel(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LinearCombinationFunction::LinearCombinationFunction(), LowerDIntegratedBC::LowerDIntegratedBC(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), MaterialADConverterTempl< T >::MaterialADConverterTempl(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), PatternedMeshGenerator::mergeSubdomainNameMaps(), MeshCollectionGenerator::MeshCollectionGenerator(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshDivisionAux::MeshDivisionAux(), MeshGenerator::MeshGenerator(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarNodalAuxKernelTempl< ComputeValueType >::MortarNodalAuxKernelTempl(), MultiApp::moveApp(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), NestedDivision::NestedDivision(), NodalBC::NodalBC(), NodalEqualValueConstraint::NodalEqualValueConstraint(), NodalKernel::NodalKernel(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), NodalValueSampler::NodalValueSampler(), Output::Output(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), PatchMeshGenerator::PatchMeshGenerator(), PatternedMeshGenerator::PatternedMeshGenerator(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), PeriodicSegmentalConstraint::PeriodicSegmentalConstraint(), PIDTransientControl::PIDTransientControl(), PlaneDeletionGenerator::PlaneDeletionGenerator(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), PolyLineMeshGenerator::PolyLineMeshGenerator(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), LibmeshPartitioner::prepareBlocksForSubdomainPartitioner(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), PropertyReadFile::PropertyReadFile(), RandomIC::RandomIC(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readXda(), ReferenceResidualProblem::ReferenceResidualProblem(), RefineBlockGenerator::RefineBlockGenerator(), RefineSidesetGenerator::RefineSidesetGenerator(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setPartitioner(), TimeSequenceStepperBase::setupSequence(), SingleRankPartitioner::SingleRankPartitioner(), SphericalGridDivision::SphericalGridDivision(), SymmetryTransformGenerator::SymmetryTransformGenerator(), Terminator::Terminator(), TimeDerivativeAux::TimeDerivativeAux(), Transfer::Transfer(), TransformGenerator::TransformGenerator(), TransientMultiApp::TransientMultiApp(), ParsedCurveGenerator::tSectionSpaceDefiner(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), UserObject::UserObject(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), VolumeAux::VolumeAux(), XYDelaunayGenerator::XYDelaunayGenerator(), and XYMeshLineCutter::XYMeshLineCutter().
paramErrorMsg()
template<typename... Args> std::string MooseBaseParameterInterface::paramErrorMsg (const std::string & param, Args... args) const inline private inherited
Definition at line 171 of file MooseBaseParameterInterface.h.
  {
    auto param_prefix = paramErrorPrefix(_pars, param);
    // With no input location information, append object info (name + type)
    const std::string object_prefix =
        _pars.inputLocation(param).empty() ? objectErrorPrefix("parameter error") : "";
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    // Wrap error message to a separate line from param_prefix if it is about to
    // blow past 100 chars.  But only wrap if the param_prefix is long enough (12
    // chars) for the wrap to buy us much extra length. We don't check object_prefix
    // here because it will go before the parameter error
    if ((param_prefix.size() > 12 && msg.size() + param_prefix.size() > 99) ||
        msg.find("\n") != std::string::npos)
    {
      if (param_prefix.size() > 0 && param_prefix[param_prefix.size() - 1] != ':')
        param_prefix += ":";
      return object_prefix + param_prefix + "\n    " + MooseUtils::replaceAll(msg, "\n", "\n    ");
    }
    return object_prefix + param_prefix + " " + msg;
  }
Referenced by MooseBaseParameterInterface::paramError(), MooseBaseParameterInterface::paramInfo(), and MooseBaseParameterInterface::paramWarning().
parameters()
const InputParameters & MooseBaseParameterInterface::parameters () const inline inherited
Get the parameters of the object.
Returns
The parameters of the object
Definition at line 53 of file MooseBaseParameterInterface.h.
{ return _pars; }
Referenced by SetupDebugAction::act(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), FEProblemBase::addPostprocessor(), FEProblemBase::addPredictor(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), AdvancedOutput::AdvancedOutput(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), Moose::assemble_matrix(), AuxScalarKernel::AuxScalarKernel(), BoundsAuxBase::BoundsAuxBase(), MooseMesh::buildTypedMesh(), UserObjectInterface::castUserObject(), PostprocessorInterface::checkParam(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), Moose::compute_bounds(), Moose::compute_jacobian(), Moose::compute_nearnullspace(), Moose::compute_nullspace(), Moose::compute_postcheck(), Moose::compute_transpose_nullspace(), LibtorchNeuralNetControl::conditionalParameterError(), Console::Console(), MultiApp::createApp(), Postprocessor::declareValue(), DumpObjectsProblem::deduceNecessaryParameters(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), DumpObjectsProblem::dumpObjectHelper(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElectronsFromIonization::ElectronsFromIonization(), Executor::Executor(), Exodus::Exodus(), FEProblem::FEProblem(), FEProblemBase::FEProblemBase(), FixedPointSolve::FixedPointSolve(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GapValueAux::GapValueAux(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), MooseBaseParameterInterface::getCheckedPointerParam(), ExecutorInterface::getExecutor(), Material::getMaterial(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), UserObjectInterface::getUserObjectName(), VectorPostprocessorInterface::getVectorPostprocessorName(), GhostingUserObject::GhostingUserObject(), HphiRadialInterface::HphiRadialInterface(), AttribSystem::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), FullSolveMultiApp::initialSetup(), FEProblemBase::initNullSpaceVectors(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), isValid(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseAppCoordTransform::MooseAppCoordTransform(), MooseVariableInterface< T >::MooseVariableInterface(), MultiApp::MultiApp(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodeFaceConstraint::NodeFaceConstraint(), PatchMeshGenerator::PatchMeshGenerator(), PenetrationAux::PenetrationAux(), PicardSolve::PicardSolve(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), ProjectedStatefulMaterialStorageAction::processProperty(), MultiAppProjectionTransfer::projectSolution(), PropertyReadFile::PropertyReadFile(), PseudoTimestep::PseudoTimestep(), RandomIC::RandomIC(), InputParameterWarehouse::removeInputParameters(), OutputWarehouse::resetFileBase(), MooseAppCoordTransform::setCoordinateSystem(), FEProblemBase::setInputParametersFEProblem(), FEProblem::setInputParametersFEProblem(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SteffensenSolve::SteffensenSolve(), DumpObjectsProblem::stringifyParameters(), TaggingInterface::TaggingInterface(), Transfer::Transfer(), Transient::Transient(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
paramInfo()
template<typename... Args> void MooseBaseParameterInterface::paramInfo (const std::string & param, Args... args) const inherited
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseInfo - only printing a message using the given args.
Definition at line 250 of file MooseBaseParameterInterface.h.
{
  mooseInfo(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by TransientMultiApp::TransientMultiApp().
paramWarning()
template<typename... Args> void MooseBaseParameterInterface::paramWarning (const std::string & param, Args... args) const inherited
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseWarning - only printing a message using the given args.
Definition at line 243 of file MooseBaseParameterInterface.h.
{
  mooseWarning(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by MultiAppNearestNodeTransfer::execute(), FEProblemSolve::FEProblemSolve(), PlaneIDMeshGenerator::generate(), UniqueExtraIDMeshGenerator::generate(), Terminator::initialSetup(), and MooseMesh::MooseMesh().
phi()
template<typename OutputType > virtual const FieldVariablePhiValue & MooseVariableField< OutputType >::phi () const pure virtual
Return the variable's elemental shape functions.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyShapes().
phiFace()
template<typename OutputType > virtual const FieldVariablePhiValue & MooseVariableField< OutputType >::phiFace () const pure virtual
Return the variable's shape functions on an element face.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyFaceShapes().
phiFaceNeighbor()
template<typename OutputType > virtual const FieldVariablePhiValue & MooseVariableField< OutputType >::phiFaceNeighbor () const pure virtual
Return the variable's shape functions on a neighboring element face.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyNeighborShapes().
phiFaceNeighborSize()
virtual std::size_t MooseVariableFieldBase::phiFaceNeighborSize () const pure virtual inherited
Return phiFaceNeighbor size.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
phiFaceSize()
virtual std::size_t MooseVariableFieldBase::phiFaceSize () const pure virtual inherited
Return phiFace size.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
phiLower()
template<typename OutputType > virtual const FieldVariablePhiValue & MooseVariableField< OutputType >::phiLower () const pure virtual
Return the variable's shape functions on a lower-dimensional element.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
phiLowerSize()
virtual std::size_t MooseVariableFieldBase::phiLowerSize () const pure virtual inherited
Return the number of shape functions on the lower dimensional element for this variable.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
phiNeighbor()
template<typename OutputType > virtual const FieldVariablePhiValue & MooseVariableField< OutputType >::phiNeighbor () const pure virtual
Return the variable's shape functions on a neighboring element.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyNeighborShapes().
phiNeighborSize()
virtual std::size_t MooseVariableFieldBase::phiNeighborSize () const pure virtual inherited
Return phiNeighbor size.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
phiSize()
virtual std::size_t MooseVariableFieldBase::phiSize () const pure virtual inherited
Return phi size.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
prepare()
virtual void MooseVariableFieldBase::prepare () pure virtual inherited
Prepare the elemental degrees of freedom.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
prepareAux()
virtual void MooseVariableFieldBase::prepareAux () pure virtual inherited
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
prepareIC()
virtual void MooseVariableFieldBase::prepareIC () pure virtual inherited
Prepare the initial condition.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
prepareLowerD()
virtual void MooseVariableFieldBase::prepareLowerD () pure virtual inherited
Prepare a lower dimensional element's degrees of freedom.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
prepareNeighbor()
virtual void MooseVariableFieldBase::prepareNeighbor () pure virtual inherited
Prepare the neighbor element degrees of freedom.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
queryFVArgCache()
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::queryFVArgCache (std::map< SpaceArg, ValueType > & cache_data, const SpaceArg & space) const private inherited
check a finite volume spatial argument cache and if invalid then evaluate
Definition at line 407 of file MooseFunctor.h.
{
  // We don't want to evaluate if the key already exists, so instead we value initialize
  auto [it, inserted] = cache_data.try_emplace(space, ValueType());
  auto & value = it->second;
  if (inserted)
    // value not ready to go
    // this function is only called from functions that assert we are in the current time state
    value = evaluate(space, currentState());
  return value;
}
queryQpCache()
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::queryQpCache (unsigned int qp, const QBase & qrule, std::vector< std::pair< bool, Moose::ADType< OutputType >::type > > & qp_cache_data, const SpaceArg & space, const StateArg & state) const private inherited
check a qp cache and if invalid then evaluate
Definition at line 397 of file MooseFunctor.h.
{
  // Check and see whether we even have sized for this quadrature point. If we haven't then we
  // must evaluate
  if (qp >= qp_cache_data.size())
  {
    qp_cache_data.resize(qrule.n_points(), std::make_pair(false, ValueType()));
    auto & pr = qp_cache_data[qp];
    pr.second = evaluate(space, state);
    pr.first = true;
    return pr.second;
  }
  // We've already sized for this qp, so let's see whether we have a valid cache value
  auto & pr = qp_cache_data[qp];
  if (pr.first)
    return pr.second;
  // No valid cache value so evaluate
  pr.second = evaluate(space, state);
  pr.first = true;
  return pr.second;
}
reinitAux()
virtual void MooseVariableFieldBase::reinitAux () pure virtual inherited
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
reinitAuxNeighbor()
virtual void MooseVariableFieldBase::reinitAuxNeighbor () pure virtual inherited
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
reinitNode()
virtual void MooseVariableFieldBase::reinitNode () pure virtual inherited
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
reinitNodes()
virtual void MooseVariableFieldBase::reinitNodes (const std::vector< dof_id_type > & nodes) pure virtual inherited
Implemented in MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, MooseVariableFV< T >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, and MooseVariableFE< ComputeValueType >.
reinitNodesNeighbor()
virtual void MooseVariableFieldBase::reinitNodesNeighbor (const std::vector< dof_id_type > & nodes) pure virtual inherited
Implemented in MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, MooseVariableFV< T >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, and MooseVariableFE< ComputeValueType >.
residualSetup()
template<typename OutputType > void MooseVariableField< OutputType >::residualSetup override virtual
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 36 of file MooseVariableField.C.
{
  MooseVariableFieldBase::residualSetup();
  FunctorBase<typename Moose::ADType<OutputType>::type>::residualSetup();
}
Referenced by MooseVariableFE< OutputType >::residualSetup().
scalingFactor() [1/3]
Real MooseVariableBase::scalingFactor () const inline inherited
Get the scaling factor for this variable.
Definition at line 96 of file MooseVariableBase.h.
{ return _scaling_factor[0]; }
Referenced by MooseVariableBase::MooseVariableBase().
scalingFactor() [2/3]
void MooseVariableBase::scalingFactor (const std::vector< Real > & factor) inherited
Definition at line 181 of file MooseVariableBase.C.
{
  _scaling_factor = factor;
}
scalingFactor() [3/3]
void MooseVariableBase::scalingFactor (Real factor) inherited
Set the scaling factor for this variable.
Definition at line 175 of file MooseVariableBase.C.
{
  _scaling_factor.assign(_count, factor);
}
Referenced by ADScalarKernel::computeADJacobian(), ADDGKernel::computeElemNeighJacobian(), ADMortarScalarBase::computeJacobian(), FVElementalKernel::computeJacobian(), ADKernelScalarBase::computeJacobian(), ADNodalKernel::computeJacobian(), NodalKernel::computeJacobian(), FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVScalarLagrangeMultiplierInterface::computeJacobian(), ADMortarConstraint::computeJacobian(), NodalConstraint::computeJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), FVScalarLagrangeMultiplierConstraint::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), ADMortarScalarBase::computeResidual(), MortarScalarBase::computeResidual(), ADKernelScalarBase::computeResidual(), ADNodalKernel::computeResidual(), NodalKernel::computeResidual(), TimeNodalKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), FVScalarLagrangeMultiplierInterface::computeResidual(), NodalConstraint::computeResidual(), FVElementalKernel::computeResidualAndJacobian(), ADKernelScalarBase::computeResidualAndJacobian(), FVScalarLagrangeMultiplierConstraint::computeResidualAndJacobian(), MortarScalarBase::computeScalarJacobian(), KernelScalarBase::computeScalarJacobian(), MortarScalarBase::computeScalarOffDiagJacobian(), KernelScalarBase::computeScalarOffDiagJacobian(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarResidual(), ScalarTagMatrixAux::computeValue(), ScalarTagVectorAux::computeValue(), TagMatrixAux::computeValue(), TagVectorAux::computeValue(), and ReferenceResidualProblem::initialSetup().
secondPhi()
template<typename OutputType > virtual const FieldVariablePhiSecond & MooseVariableField< OutputType >::secondPhi () const pure virtual
Return the rank-2 tensor of second derivatives of the variable's elemental shape functions.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyShapes().
secondPhiFace()
template<typename OutputType > virtual const FieldVariablePhiSecond & MooseVariableField< OutputType >::secondPhiFace () const pure virtual
Return the rank-2 tensor of second derivatives of the variable's shape functions on an element face.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyFaceShapes().
secondPhiFaceNeighbor()
template<typename OutputType > virtual const FieldVariablePhiSecond & MooseVariableField< OutputType >::secondPhiFaceNeighbor () const pure virtual
Return the rank-2 tensor of second derivatives of the variable's shape functions on a neighboring element face.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyNeighborShapes().
secondPhiNeighbor()
template<typename OutputType > virtual const FieldVariablePhiSecond & MooseVariableField< OutputType >::secondPhiNeighbor () const pure virtual
Return the rank-2 tensor of second derivatives of the variable's shape functions on a neighboring element.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyNeighborShapes().
setActiveTags()
void MooseVariableBase::setActiveTags (const std::set< TagID > & vtags) inline virtual inherited
Set the active vector tags.
Parameters
vtags Additional vector tags that this variable will need to query at dof indices for, in addition to our own required solution tags
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, MooseVariableFV< T >, and MooseVariableScalar.
Definition at line 243 of file MooseVariableBase.h.
{
  mooseError("setActiveTags must be overridden in derived classes.");
}
setCacheClearanceSchedule()
void Moose::FunctorBase< Moose::ADType< OutputType >::type >::setCacheClearanceSchedule (const std::set< ExecFlagType > & clearance_schedule) inherited
Set how often to clear the functor evaluation cache.
Definition at line 139 of file MooseFunctor.h.
{
  _clearance_schedule = clearance_schedule;
}
setDofValue()
template<typename OutputType > virtual void MooseVariableField< OutputType >::setDofValue (const OutputData & value, unsigned int index) pure virtual
Degree of freedom value setters.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by ElementLpNormAux::compute(), and VolumeAux::compute().
setDofValues()
template<typename OutputType > virtual void MooseVariableField< OutputType >::setDofValues (const DenseVector< OutputData > & values) pure virtual
Set local DOF values and evaluate the values on quadrature points.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by TagVectorArrayVariableAux::compute(), and BuildArrayVariableAux::compute().
setNodalValue()
template<typename OutputType > virtual void MooseVariableField< OutputType >::setNodalValue (const OutputType & value, unsigned int idx = 0) pure virtual
Implemented in MooseVariableFE< ComputeValueType >, MooseVariableFV< ComputeValueType >, MooseVariableFE< OutputType >, MooseVariableFV< OutputType >, MooseVariableFE< Real >, MooseVariableFV< Real >, MooseVariableFE< RealEigenVector >, MooseVariableFV< RealEigenVector >, MooseVariableFE< RealVectorValue >, MooseVariableFV< RealVectorValue >, MooseVariableFE< T >, and MooseVariableFV< T >.
Referenced by ElementH1ErrorFunctionAux::compute(), and NodalPatchRecovery::compute().
sln()
template<typename OutputType > virtual const FieldVariableValue & MooseVariableField< OutputType >::sln () const pure virtual
Returns
the current elemental solution
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by ElementalVariableValue::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), and MultiAppVariableValueSampleTransfer::execute().
slnNeighbor()
template<typename OutputType > virtual const FieldVariableValue & MooseVariableField< OutputType >::slnNeighbor () const pure virtual
Returns
the current neighbor solution
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
slnOld()
template<typename OutputType > virtual const FieldVariableValue & MooseVariableField< OutputType >::slnOld () const pure virtual
Returns
the old elemental solution, e.g. that of the previous timestep
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
slnOlder()
template<typename OutputType > virtual const FieldVariableValue & MooseVariableField< OutputType >::slnOlder () const pure virtual
Returns
the older elemental solution, e.g. that of two timesteps ago
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
slnOldNeighbor()
template<typename OutputType > virtual const FieldVariableValue & MooseVariableField< OutputType >::slnOldNeighbor () const pure virtual
Returns
the old neighbor solution, e.g. that of the previous timestep
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
subdomainSetup()
void SetupInterface::subdomainSetup () virtual inherited
Gets called when the subdomain changes (i.e.
in a Jacobian or residual loop) and before this object is asked to do its job
Reimplemented in Material, MaterialBase, GeneralUserObject, NodalUserObject, ThreadedGeneralUserObject, and Constraint.
Definition at line 60 of file SetupInterface.C.
{
}
sys() [1/2]
SystemBase & MooseVariableBase::sys () inline inherited
Get the system this variable is part of.
Definition at line 59 of file MooseVariableBase.h.
{ return _sys; }
Referenced by ADDGKernel::ADDGKernel(), FEProblemBase::addInitialCondition(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), MultiAppConservativeTransfer::adjustTransferredSolution(), MultiAppConservativeTransfer::adjustTransferredSolutionNearestPoint(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldShapeEvaluationTransfer::buildMeshFunctions(), MooseMesh::cacheFaceInfoVariableOwnership(), FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), FVFluxBC::computeResidual(), FVInterfaceKernel::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), Moose::FV::determineElemOneAndTwo(), DGKernel::DGKernel(), MultiAppGeometricInterpolationTransfer::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), MultiAppGeometricInterpolationTransfer::fillSourceInterpolationPoints(), FVBoundaryCondition::hasFaceSide(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), MultiAppGeometricInterpolationTransfer::interpolateTargetPoints(), Kernel::Kernel(), NodalBC::NodalBC(), NodalKernel::NodalKernel(), Exodus::outputScalarVariables(), Nemesis::outputScalarVariables(), TableOutput::outputScalarVariables(), FEProblemBase::projectInitialConditionOnCustomRange(), FEProblemBase::projectSolution(), MultiAppProjectionTransfer::projectSolution(), MooseVariableScalar::reinit(), FVInterfaceKernel::setupData(), MultiAppDofCopyTransfer::transfer(), MultiAppDofCopyTransfer::transferDofObject(), MultiAppShapeEvaluationTransfer::transferVariable(), FVFluxBC::uOnGhost(), and FVFluxBC::uOnUSub().
sys() [2/2]
const SystemBase & MooseVariableBase::sys () const inline inherited
Get the system this variable is part of.
Definition at line 64 of file MooseVariableBase.h.
{ return _sys; }
timestepSetup()
template<typename OutputType > void MooseVariableField< OutputType >::timestepSetup override virtual
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Reimplemented in MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 52 of file MooseVariableField.C.
{
  MooseVariableFieldBase::timestepSetup();
  FunctorBase<typename Moose::ADType<OutputType>::type>::timestepSetup();
}
Referenced by MooseVariableFV< OutputType >::timestepSetup().
totalVarDofs()
unsigned int MooseVariableBase::totalVarDofs () inline inherited
Definition at line 80 of file MooseVariableBase.h.
{ return allDofIndices().size(); }
type()
const std::string & MooseBase::type () const inline inherited
Get the type of this class.
Returns
the name of the type of this class
Definition at line 41 of file MooseBase.h.
{ return _type; }
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), CreateProblemDefaultAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetupDebugAction::act(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::addDistribution(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addObject(), DistributedRectilinearMeshGenerator::addPoint(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), PhysicsBasedPreconditioner::addSystem(), FEProblemBase::addTimeIntegrator(), SubProblem::addVectorTag(), DisplacedProblem::addVectorTag(), FEProblemBase::advanceMultiApps(), FEProblemBase::backupMultiApps(), BoundaryPreservedMarker::BoundaryPreservedMarker(), DistributedRectilinearMeshGenerator::buildCube(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildPRefinementAndCoarseningMaps(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), FEProblemBase::computeAuxiliaryKernels(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpJacobian(), HFEMDirichletBC::computeLowerDQpJacobian(), ArrayHFEMDiffusion::computeLowerDQpJacobian(), HFEMDiffusion::computeLowerDQpJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), FEProblemBase::computeMultiAppsDT(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), DGCoupledAdvection::computeOffDiagJacobianHelper(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ScalarKernel::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueBoundaryConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), LinearNodalConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), DGConvection::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), InterfaceDiffusion::computeQpJacobian(), InterfaceReaction::computeQpJacobian(), DGCoupledAdvection::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), DGFunctionTemperatureAdvection::computeQpJacobian(), DGTemperatureAdvection::computeQpJacobian(), InterTemperatureAdvection::computeQpJacobian(), CoupledTiedValueConstraint::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), HFEMTestJump::computeQpOffDiagJacobian(), HFEMTrialJump::computeQpOffDiagJacobian(), DGCoupledAdvection::computeQpOffDiagJacobian(), ScalarKernel::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), EqualValueBoundaryConstraint::computeQpResidual(), EqualValueEmbeddedConstraint::computeQpResidual(), LinearNodalConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), DGConvection::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), DGEFieldAdvection::computeQpResidual(), HphiRadialInterface::computeQpResidual(), InterfaceAdvection::computeQpResidual(), InterfaceLogDiffusionElectrons::computeQpResidual(), PotentialSurfaceCharge::computeQpResidual(), ADDGAdvection::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), HFEMDiffusion::computeQpResidual(), HFEMTestJump::computeQpResidual(), HFEMTrialJump::computeQpResidual(), InterfaceDiffusion::computeQpResidual(), InterfaceReaction::computeQpResidual(), DGCoupledAdvection::computeQpResidual(), DGFunctionConvection::computeQpResidual(), DGFunctionTemperatureAdvection::computeQpResidual(), DGTemperatureAdvection::computeQpResidual(), InterTemperatureAdvection::computeQpResidual(), ArrayDGDiffusion::computeQpResidual(), ArrayHFEMDiffusion::computeQpResidual(), FEProblemBase::computeUserObjectByName(), FEProblemBase::computeUserObjects(), FEProblemBase::computeUserObjectsInternal(), BatchMaterial< Tuple, Output, Input >::construct(), DisplacedProblem::createQRules(), FEProblemBase::createQRules(), MeshGenerator::declareMeshProperty(), DumpObjectsProblem::deduceNecessaryParameters(), DumpObjectsProblem::dumpObjectHelper(), FEProblemBase::duplicateVariableCheck(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), MooseBaseErrorInterface::errorPrefix(), AB2PredictorCorrector::estimateTimeError(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finishMultiAppStep(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), ElementSubdomainIDGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), PatternedMeshGenerator::generate(), MeshGenerator::generateInternal(), MultiAppTransfer::getAppInfo(), TransfiniteMeshGenerator::getEdge(), ElementGenerator::getElemType(), FEProblemBase::getMaterial(), FEProblemBase::getMaterialData(), MaterialOutputAction::getParams(), ReporterData::getReporterInfo(), Transient::getTimeIntegratorName(), FEProblemBase::getTransfers(), SubProblem::getVectorTags(), DisplacedProblem::getVectorTags(), CommonOutputAction::hasConsole(), FEProblemBase::hasMultiApps(), AdvancedOutput::hasOutput(), FEProblemBase::incrementMultiAppTStep(), AdvancedOutput::initAvailableLists(), FunctorPositions::initialize(), FunctorTimes::initialize(), MultiAppConservativeTransfer::initialSetup(), ArrayDGDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), RelationshipManager::isType(), FEProblemBase::logAdd(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), SubProblem::numVectorTags(), DisplacedProblem::numVectorTags(), MooseBaseParameterInterface::objectErrorPrefix(), AdvancedOutput::output(), Console::output(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), ProjectedStatefulMaterialStorageAction::processProperty(), SolutionInvalidInterface::registerInvalidSolutionInternal(), FEProblemBase::restoreMultiApps(), MeshRepairGenerator::separateSubdomainsByElementType(), FEProblemBase::setCoupling(), MooseBase::typeAndName(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), DisplacedProblem::updateGeomSearch(), FEProblemBase::updateGeomSearch(), UserObjectInterface::userObjectType(), and AdvancedOutput::wantOutput().
typeAndName()
std::string MooseBase::typeAndName () const inline inherited
Get the class's combined type and name; useful in error handling.
Returns
The type and name of this class in the form '<type()> "<name()>"'.
Definition at line 53 of file MooseBase.h.
  {
    return type() + std::string(" \"") + name() + std::string("\"");
  }
Referenced by ReporterContext< T >::finalize(), and ReporterData::getReporterInfo().
uniqueName()
MooseObjectName MooseBaseParameterInterface::uniqueName () const inline inherited
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
Definition at line 58 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectName(_pars.get<std::string>("_unique_name"));
  }
Referenced by MooseBaseParameterInterface::connectControllableParams(), and Action::uniqueActionName().
uniqueParameterName()
MooseObjectParameterName MooseBaseParameterInterface::uniqueParameterName (const std::string & parameter_name) const inline inherited
The unique parameter name of a valid parameter of this object for accessing parameter controls.
Definition at line 43 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectParameterName(
        _pars.get<std::string>("_moose_base"), _moose_base->name(), parameter_name);
  }
useDual()
bool MooseVariableBase::useDual () const inline inherited
Get dual mortar option.
Definition at line 74 of file MooseVariableBase.h.
{ return _use_dual; }
Referenced by MortarConstraintBase::MortarConstraintBase().
usesGradPhiNeighbor()
template<typename OutputType > bool MooseVariableField< OutputType >::usesGradPhiNeighbor () const inline
Whether or not this variable is actually using the shape function gradient.
Currently hardcoded to true because we always compute the value.
Definition at line 319 of file MooseVariableField.h.
{ return true; }
Referenced by Assembly::copyNeighborShapes().
usesPhiNeighbor()
template<typename OutputType > bool MooseVariableField< OutputType >::usesPhiNeighbor () const inline
Whether or not this variable is actually using the shape function value.
Currently hardcoded to true because we always compute the value.
Definition at line 312 of file MooseVariableField.h.
{ return true; }
Referenced by Assembly::copyNeighborShapes().
usesSecondPhiNeighbor()
template<typename OutputType > virtual bool MooseVariableField< OutputType >::usesSecondPhiNeighbor () const pure virtual
Whether or not this variable is actually using the shape function second derivatives.
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Referenced by Assembly::copyNeighborShapes().
validParams()
template<typename OutputType > InputParameters MooseVariableField< OutputType >::validParams static
Definition at line 20 of file MooseVariableField.C.
{
  return MooseVariableFieldBase::validParams();
}
Referenced by MooseVariableFV< OutputType >::validParams().
vectorTagDofValue()
template<typename OutputType > virtual const DoFValue & MooseVariableField< OutputType >::vectorTagDofValue (TagID tag) const pure virtual
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
vectorTagValue()
template<typename OutputType > virtual const FieldVariableValue & MooseVariableField< OutputType >::vectorTagValue (TagID tag) const pure virtual
tag values getters
Implemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Member Data Documentation
_action_factory
ActionFactory& MooseBaseParameterInterface::_action_factory protected inherited
Builds Actions.
Definition at line 164 of file MooseBaseParameterInterface.h.
Referenced by CommonOutputAction::create(), AddVariableAction::createInitialConditionAction(), AddSpecies::createInitialConditions(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
_ad_real_dummy
template<typename OutputType > ADReal MooseVariableField< OutputType >::_ad_real_dummy = 0 mutable protected
A dummy ADReal variable.
Definition at line 382 of file MooseVariableField.h.
_app
MooseApp& MooseBase::_app protected inherited
The MOOSE application this is associated with.
Definition at line 60 of file MooseBase.h.
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), MeshGenerator::addChildMeshGenerator(), FEProblemBase::addMaterialHelper(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addOutput(), MeshGenerator::addParentMeshGenerator(), FVFluxKernel::adjustRMGhostLayers(), FEProblemBase::allowOutput(), AStableDirk4::AStableDirk4(), FileMesh::buildMesh(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), MeshGenerator::checkGetMesh(), FEProblemBase::checkICRestartError(), FEProblemBase::checkNonlinearConvergence(), OversampleOutput::cloneMesh(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), Console::Console(), TimeStepper::constrainStep(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::createLocalApp(), FEProblemBase::customSetup(), MeshGenerator::declareMeshProperty(), MeshGenerator::declareNullMeshName(), MooseMesh::determineUseDistributedMesh(), DumpObjectsProblem::dumpObjectHelper(), DumpObjectsProblem::dumpVariableHelper(), EigenExecutionerBase::EigenExecutionerBase(), EigenKernel::EigenKernel(), PIDTransientControl::execute(), Eigenvalue::execute(), InversePowerMethod::execute(), NonlinearEigen::execute(), Steady::execute(), Transient::execute(), PseudoTimestep::execute(), IterationInfo::execute(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FileOutput::FileOutput(), ChangeOverFixedPointPostprocessor::finalize(), RadialAverage::finalize(), FixedPointSolve::FixedPointSolve(), FEProblemBase::forceOutput(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), SideSetsFromNormalsGenerator::generate(), MeshGenerator::generateInternal(), FEProblemBase::getExecutor(), MeshGenerator::getMeshByName(), NumFixedPointIterations::getValue(), NumRelationshipManagers::getValue(), GhostingUserObject::GhostingUserObject(), MooseMesh::init(), InversePowerMethod::init(), NonlinearEigen::init(), Transient::init(), FEProblemBase::init(), TimePeriod::initialSetup(), Console::initialSetup(), AdvancedOutput::initOutputList(), FEProblemBase::initPetscOutput(), EigenProblem::initPetscOutput(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MeshGenerator::MeshGenerator(), EigenExecutionerBase::normalizeSolution(), NumFailedTimeSteps::NumFailedTimeSteps(), AugmentSparsityOnInterface::operator()(), Checkpoint::output(), Exodus::output(), Nemesis::output(), PerfGraphOutput::output(), Tecplot::output(), MortarNodalGeometryOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Exodus::outputEmptyTimestep(), Console::outputInput(), Exodus::outputInput(), Exodus::outputNodalVariables(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), Console::outputSystemInformation(), JSONOutput::outputSystemInformation(), MultiApp::parentOutputPositionChanged(), PIDTransientControl::PIDTransientControl(), Transient::preExecute(), Eigenvalue::prepareSolverOptions(), FEProblemBase::projectSolution(), MultiApp::setAppOutputFileBase(), FileOutput::setFileBaseInternal(), MeshGenerator::setMeshProperty(), MeshGenerator::setMeshPropertyHelper(), FEProblemBase::setRestartFile(), TransientMultiApp::setupApp(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SolutionInvalidityReporter::SolutionInvalidityReporter(), FEProblemBase::solve(), EigenProblem::solve(), PetscOutput::solveSetup(), TransientMultiApp::solveStep(), FEProblemBase::subdomainSetup(), FEProblemBase::theWarehouse(), TimeExtremeValue::TimeExtremeValue(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), Transient::Transient(), FEProblemBase::updateMortarMesh(), Console::write(), and FEProblemBase::~FEProblemBase().
_assembly
Assembly& MooseVariableBase::_assembly protected inherited
Assembly data.
Definition at line 212 of file MooseVariableBase.h.
Referenced by MooseVariableFE< OutputType >::MooseVariableFE(), and MooseVariableFV< OutputType >::MooseVariableFV().
_blk_dim
unsigned int BlockRestrictable::_blk_dim private inherited
Largest mesh dimension of the elements in the blocks for this object.
Definition at line 259 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blocksMaxDimension(), and BlockRestrictable::initializeBlockRestrictable().
_blk_dual_restrictable
const bool BlockRestrictable::_blk_dual_restrictable private inherited
Flag for allowing dual restriction.
Definition at line 238 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_blk_feproblem
FEProblemBase* BlockRestrictable::_blk_feproblem private inherited
Pointer to FEProblemBase.
Definition at line 241 of file BlockRestrictable.h.
Referenced by BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), and BlockRestrictable::initializeBlockRestrictable().
_blk_ids
std::set<SubdomainID> BlockRestrictable::_blk_ids private inherited
Set of block ids supplied by the user via the input file (for error checking)
Definition at line 229 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blockIDs(), BlockRestrictable::blockRestricted(), BlockRestrictable::checkVariable(), BlockRestrictable::hasBlocks(), BlockRestrictable::initializeBlockRestrictable(), BlockRestrictable::isBlockSubset(), and BlockRestrictable::numBlocks().
_blk_material_data
const MaterialData* BlockRestrictable::_blk_material_data protected inherited
Pointer to the MaterialData class for this object.
Definition at line 207 of file BlockRestrictable.h.
Referenced by BlockRestrictable::hasBlockMaterialProperty(), and BlockRestrictable::initializeBlockRestrictable().
_blk_mesh
MooseMesh* BlockRestrictable::_blk_mesh private inherited
Pointer to Mesh.
Definition at line 244 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blockIDs(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlocks(), BlockRestrictable::initializeBlockRestrictable(), BlockRestrictable::isBlockSubset(), and BlockRestrictable::meshBlockIDs().
_blk_name
const std::string& BlockRestrictable::_blk_name private inherited
Name of the object.
Definition at line 256 of file BlockRestrictable.h.
Referenced by BlockRestrictable::checkVariable(), and BlockRestrictable::initializeBlockRestrictable().
_blk_tid
THREAD_ID BlockRestrictable::_blk_tid private inherited
Thread id for this object.
Definition at line 253 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_blocks
std::vector<SubdomainName> BlockRestrictable::_blocks private inherited
Vector the block names supplied by the user via the input file.
Definition at line 235 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blocks(), and BlockRestrictable::initializeBlockRestrictable().
_boundary_ids
const std::set<BoundaryID>& BlockRestrictable::_boundary_ids private inherited
Reference to the boundary_ids, defaults to an empty set if not provided.
Definition at line 250 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_clearance_schedule
std::set<ExecFlagType> Moose::FunctorBase< Moose::ADType< OutputType >::type >::_clearance_schedule private inherited
How often to clear the material property cache.
Definition at line 411 of file MooseFunctor.h.
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_count
const unsigned int MooseVariableBase::_count protected inherited
Number of variables in the array.
Definition at line 227 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::componentName(), MooseVariableBase::count(), MooseVariableBase::MooseVariableBase(), and MooseVariableBase::scalingFactor().
_current_execute_flag
const ExecFlagType& SetupInterface::_current_execute_flag protected inherited
Reference to FEProblemBase.
Definition at line 78 of file SetupInterface.h.
Referenced by PseudoTimestep::execute().
_current_qp_map_key
dof_id_type Moose::FunctorBase< Moose::ADType< OutputType >::type >::_current_qp_map_key mutable private inherited
Current key for qp map cache.
Definition at line 417 of file MooseFunctor.h.
_current_qp_map_value
std::vector<std::pair<bool, ValueType> >* Moose::FunctorBase< Moose::ADType< OutputType >::type >::_current_qp_map_value mutable private inherited
Current value for qp map cache.
Definition at line 420 of file MooseFunctor.h.
_current_side_qp_map_key
dof_id_type Moose::FunctorBase< Moose::ADType< OutputType >::type >::_current_side_qp_map_key mutable private inherited
Current key for side-qp map cache.
Definition at line 433 of file MooseFunctor.h.
_current_side_qp_map_value
std::vector<std::vector<std::pair<bool, ValueType> > >* Moose::FunctorBase< Moose::ADType< OutputType >::type >::_current_side_qp_map_value mutable private inherited
Current value for side-qp map cache.
Definition at line 436 of file MooseFunctor.h.
_dof_indices
std::vector<dof_id_type> MooseVariableBase::_dof_indices protected inherited
DOF indices.
Definition at line 218 of file MooseVariableBase.h.
Referenced by MooseVariableBase::clearAllDofIndices(), MooseVariableScalar::computeAD(), MooseVariableBase::dofIndices(), MooseVariableScalar::insert(), MooseVariableBase::numberOfDofs(), MooseVariableScalar::reinit(), MooseVariableScalar::setValue(), and MooseVariableScalar::setValues().
_dof_map
const DofMap& MooseVariableBase::_dof_map protected inherited
DOF map.
Definition at line 215 of file MooseVariableBase.h.
Referenced by MooseVariableBase::dofMap(), MooseVariableScalar::insert(), and MooseVariableScalar::reinit().
_elem_arg_to_value
std::map<ElemArg, ValueType> Moose::FunctorBase< Moose::ADType< OutputType >::type >::_elem_arg_to_value mutable private inherited
Map from element arguments to their cached evaluations.
Definition at line 449 of file MooseFunctor.h.
_empty_boundary_ids
const std::set<BoundaryID> BlockRestrictable::_empty_boundary_ids private inherited
An empty set for referencing when boundary_ids is not included.
Definition at line 247 of file BlockRestrictable.h.
_empty_execute_enum
ExecFlagEnum SetupInterface::_empty_execute_enum private inherited
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
This is private because others should not be messing with it.
Definition at line 71 of file SetupInterface.h.
Referenced by SetupInterface::SetupInterface().
_enabled
const bool& MooseObject::_enabled protected inherited
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
Definition at line 58 of file MooseObject.h.
Referenced by MooseObject::enabled().
_execute_enum
const ExecFlagEnum& SetupInterface::_execute_enum protected inherited
Execute settings for this object.
Definition at line 75 of file SetupInterface.h.
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), SetupInterface::getExecuteOnEnum(), JSONOutput::outputReporters(), XMLOutput::outputVectorPostprocessors(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
_face_arg_to_value
std::map<FaceArg, ValueType> Moose::FunctorBase< Moose::ADType< OutputType >::type >::_face_arg_to_value mutable private inherited
Map from face arguments to their cached evaluations.
Definition at line 452 of file MooseFunctor.h.
_factory
Factory& MooseBaseParameterInterface::_factory protected inherited
The Factory associated with the MooseApp.
Definition at line 161 of file MooseBaseParameterInterface.h.
Referenced by AddGeneralReactions::act(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), ElementIDOutputAction::act(), AddSpecies::act(), AdaptivityAction::act(), AddControlAction::act(), AddNodalNormalsAction::act(), AddPeriodicBCAction::act(), AutoCheckpointAction::act(), ComposeTimeStepperAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DisplayGhostingAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), PartitionerAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SetupPreconditionerAction::act(), SetupPredictorAction::act(), SetupResidualDebugAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddGeneralReactions::addEEDFReactionKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddDriftDiffusionAction::addPosition(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), MooseBaseParameterInterface::connectControllableParams(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), MaterialOutputAction::getParams(), and ProjectedStatefulMaterialStorageAction::processProperty().
_fe_type
FEType MooseVariableBase::_fe_type protected inherited
The FEType associated with this variable.
Definition at line 191 of file MooseVariableBase.h.
Referenced by MooseVariableBase::feType(), MooseVariableBase::MooseVariableBase(), MooseVariableConstMonomial::MooseVariableConstMonomial(), and MooseVariableBase::order().
_functor_name
MooseFunctorName Moose::FunctorBase< Moose::ADType< OutputType >::type >::_functor_name private inherited
name of the functor
Definition at line 458 of file MooseFunctor.h.
_index
unsigned int MooseVariableBase::_index protected inherited
variable number within MOOSE
Definition at line 197 of file MooseVariableBase.h.
_is_array
const bool MooseVariableBase::_is_array protected inherited
Whether this is an array variable.
Definition at line 239 of file MooseVariableBase.h.
Referenced by MooseVariableBase::isArray(), and MooseVariableBase::MooseVariableBase().
_is_eigen
bool MooseVariableBase::_is_eigen protected inherited
Whether or not this variable operates on eigen kernels.
Definition at line 200 of file MooseVariableBase.h.
Referenced by MooseVariableBase::eigen().
_mci_feproblem
FEProblemBase& MeshChangedInterface::_mci_feproblem protected inherited
Reference to FEProblemBase instance.
Definition at line 38 of file MeshChangedInterface.h.
Referenced by MeshChangedInterface::MeshChangedInterface().
_mesh
MooseMesh& MooseVariableBase::_mesh protected inherited
mesh the variable is active in
Definition at line 221 of file MooseVariableBase.h.
_moose_base
const MooseBase* const MooseBaseParameterInterface::_moose_base private inherited
The MooseBase object that inherits this class.
Definition at line 168 of file MooseBaseParameterInterface.h.
Referenced by MooseBaseParameterInterface::connectControllableParams(), MooseBaseParameterInterface::objectErrorPrefix(), MooseBaseParameterInterface::paramError(), and MooseBaseParameterInterface::uniqueParameterName().
_name
const std::string& MooseBase::_name protected inherited
The name of this class, reference to value stored in InputParameters.
Definition at line 66 of file MooseBase.h.
Referenced by AddFieldSplitAction::act(), AddBCAction::act(), AddConstraintAction::act(), AddControlAction::act(), AddDamperAction::act(), AddDGKernelAction::act(), AddDiracKernelAction::act(), AddDistributionAction::act(), AddFunctionAction::act(), AddFunctorMaterialAction::act(), AddFVBCAction::act(), AddFVInitialConditionAction::act(), AddFVInterfaceKernelAction::act(), AddFVKernelAction::act(), AddIndicatorAction::act(), AddInitialConditionAction::act(), AddInterfaceKernelAction::act(), AddKernelAction::act(), AddMarkerAction::act(), AddMaterialAction::act(), AddMeshDivisionAction::act(), AddMeshGeneratorAction::act(), AddMultiAppAction::act(), AddNodalKernelAction::act(), AddOutputAction::act(), AddPeriodicBCAction::act(), AddPositionsAction::act(), AddPostprocessorAction::act(), AddReporterAction::act(), AddSamplerAction::act(), AddScalarKernelAction::act(), AddTimesAction::act(), AddTimeStepperAction::act(), AddTransferAction::act(), AddUserObjectAction::act(), AddVectorPostprocessorAction::act(), PartitionerAction::act(), ReadExecutorParamsAction::act(), SetupPreconditionerAction::act(), SetupTimeIntegratorAction::act(), AddDriftDiffusionAction::addADKernels(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromXY(), PiecewiseLinearBase::buildInterpolation(), CombinerGenerator::CombinerGenerator(), Executor::Executor(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), FunctionDT::FunctionDT(), FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), MooseBase::name(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), PiecewiseBase::setData(), and Split::setup().
_node_arg_to_value
std::map<NodeArg, ValueType> Moose::FunctorBase< Moose::ADType< OutputType >::type >::_node_arg_to_value mutable private inherited
Map from nodal arguments to their cached evaluations.
Definition at line 455 of file MooseFunctor.h.
_oi_moose_app
MooseApp& OutputInterface::_oi_moose_app private inherited
Reference the the MooseApp; neede for access to the OutputWarehouse.
Definition at line 66 of file OutputInterface.h.
_oi_output_warehouse
OutputWarehouse& OutputInterface::_oi_output_warehouse private inherited
Reference to the OutputWarehouse for populating the Output object hide lists.
Definition at line 69 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList().
_oi_outputs
std::set<OutputName> OutputInterface::_oi_outputs private inherited
The set of Output object names listed in the 'outputs' parameter.
Definition at line 72 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList(), and OutputInterface::getOutputs().
_parent
const MooseObject & DataFileInterface< MooseObject >::_parent private inherited
Definition at line 46 of file DataFileInterface.h.
_pars
const InputParameters& MooseBaseParameterInterface::_pars protected inherited
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Definition at line 158 of file MooseBaseParameterInterface.h.
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), AddPeriodicBCAction::act(), AddVariableAction::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), FunctorMaterial::addFunctorPropertyByBlocks(), FVFluxKernel::adjustRMGhostLayers(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), PiecewiseTabularBase::buildFromFile(), PNGOutput::calculateRescalingValues(), BlockWeightedPartitioner::clone(), GridPartitioner::clone(), HierarchicalGridPartitioner::clone(), PetscExternalPartitioner::clone(), RandomPartitioner::clone(), SingleRankPartitioner::clone(), MooseBaseParameterInterface::connectControllableParams(), Console::Console(), AddVariableAction::createInitialConditionAction(), MaterialBase::declareADProperty(), MaterialBase::declareProperty(), FEProblemSolve::FEProblemSolve(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), FileMeshGenerator::generate(), MaterialBase::getGenericZeroMaterialProperty(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getParam(), MooseBaseParameterInterface::getRenamedParam(), AddVariableAction::init(), AdvancedOutput::initExecutionTypes(), Console::initialSetup(), MooseBaseParameterInterface::isParamSetByUser(), MooseBaseParameterInterface::isParamValid(), MultiApp::keepSolutionDuringRestore(), MooseBaseParameterInterface::paramErrorMsg(), GlobalParamsAction::parameters(), MooseBaseParameterInterface::parameters(), MooseMesh::prepare(), Eigenvalue::prepareSolverOptions(), MooseMesh::setCoordSystem(), MooseMesh::setPartitionerHelper(), SetupMeshAction::setupMesh(), Transient::setupTimeIntegrator(), MooseBaseParameterInterface::uniqueName(), and MooseBaseParameterInterface::uniqueParameterName().
_qp_to_value
std::unordered_map<dof_id_type, std::vector<std::pair<bool, ValueType> > > Moose::FunctorBase< Moose::ADType< OutputType >::type >::_qp_to_value mutable private inherited
Cached element quadrature point functor property evaluations.
The map key is the element id. The map values should have size corresponding to the number of quadrature points on the element. The vector elements are pairs. The first member of the pair indicates whether a cached value has been computed. The second member of the pair is the (cached) value. If the boolean is false, then the value cannot be trusted
Definition at line 427 of file MooseFunctor.h.
_scaling_factor
std::vector<Real> MooseVariableBase::_scaling_factor protected inherited
scaling factor for this variable
Definition at line 230 of file MooseVariableBase.h.
Referenced by MooseVariableBase::arrayScalingFactor(), MooseVariableBase::initialSetup(), and MooseVariableBase::scalingFactor().
_side_qp_to_value
std::unordered_map<dof_id_type, std::vector<std::vector<std::pair<bool, ValueType> > > > Moose::FunctorBase< Moose::ADType< OutputType >::type >::_side_qp_to_value mutable private inherited
Cached element quadrature point functor property evaluations.
The map key is the element id. The map values are a multi-dimensional vector (or vector of vectors) with the first index corresponding to the side and the second index corresponding to the quadrature point index. The elements returned after double indexing are pairs. The first member of the pair indicates whether a cached value has been computed. The second member of the pair is the (cached) value. If the boolean is false, then the value cannot be trusted
Definition at line 446 of file MooseFunctor.h.
_subproblem
SubProblem& MooseVariableBase::_subproblem protected inherited
Problem this variable is part of.
Definition at line 206 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::componentName(), MooseVariableScalar::computeAD(), and MooseVariableBase::initialSetup().
_sys
SystemBase& MooseVariableBase::_sys protected inherited
System this variable is part of.
Definition at line 188 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::activeOnSubdomain(), MooseVariableFieldBase::activeSubdomains(), MooseVariableScalar::adUDot(), MooseVariableBase::allDofIndices(), MooseVariableScalar::computeAD(), MooseVariableBase::initialSetup(), MooseVariableBase::MooseVariableBase(), MooseVariableFE< OutputType >::MooseVariableFE(), MooseVariableFV< OutputType >::MooseVariableFV(), MooseVariableScalar::MooseVariableScalar(), MooseVariableScalar::reinit(), MooseVariableBase::sys(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), and MooseVariableScalar::uDotOld().
_tid
THREAD_ID MooseVariableBase::_tid protected inherited
Thread ID.
Definition at line 224 of file MooseVariableBase.h.
Referenced by MooseVariableFE< OutputType >::MooseVariableFE(), MooseVariableFV< OutputType >::MooseVariableFV(), and MooseVariableScalar::reinit().
_time_integrator
template<typename OutputType > const TimeIntegrator* const MooseVariableField< OutputType >::_time_integrator protected
the time integrator used for computing time derivatives
Definition at line 379 of file MooseVariableField.h.
_type
const std::string& MooseBase::_type protected inherited
The type of this class.
Definition at line 63 of file MooseBase.h.
Referenced by FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), FEProblemBase::init(), FEProblemBase::solverTypeString(), and MooseBase::type().
_use_dual
bool MooseVariableBase::_use_dual protected inherited
If dual mortar approach is used.
Definition at line 236 of file MooseVariableBase.h.
Referenced by MooseVariableBase::useDual().
_var_kind
Moose::VarKindType MooseVariableBase::_var_kind protected inherited
Variable type (see MooseTypes.h)
Definition at line 203 of file MooseVariableBase.h.
Referenced by MooseVariableBase::kind().
_var_name
std::string MooseVariableBase::_var_name protected inherited
Variable name.
Definition at line 233 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::componentName(), MooseVariableBase::MooseVariableBase(), and MooseVariableBase::name().
_var_num
unsigned int MooseVariableBase::_var_num protected inherited
variable number (from libMesh)
Definition at line 194 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::activeOnSubdomain(), MooseVariableFieldBase::activeSubdomains(), MooseVariableBase::MooseVariableBase(), MooseVariableBase::number(), and MooseVariableScalar::reinit().
_variable
const Variable& MooseVariableBase::_variable protected inherited
libMesh variable object for this variable
Definition at line 209 of file MooseVariableBase.h.
_vec_ids
std::vector<SubdomainID> BlockRestrictable::_vec_ids private inherited
Vector of block ids supplied by the user via the input file (for error reporting)
Definition at line 232 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
The documentation for this class was generated from the following files:
moose/framework/include/interfaces/Coupleable.h
moose/framework/include/variables/MooseVariableField.h
moose/framework/src/variables/MooseVariableField.C