Zapdos: VariableCondensationPreconditioner Class Reference
VariableCondensationPreconditioner Class Reference
Interface for condensing out LMs for the dual mortar approach.
#include <VariableCondensationPreconditioner.h>
Public Member Functions
VariableCondensationPreconditioner (const InputParameters &params)
virtual ~VariableCondensationPreconditioner ()
virtual void init ()
Initialize data structures if not done so already.
virtual void setup ()
This is called every time the "operator might have changed".
virtual void apply (const NumericVector< Number > &y, NumericVector< Number > &x)
Computes the preconditioned vector "x" based on input "y".
virtual void clear ()
Release all memory and clear data structures.
virtual bool enabled () const
Return the enabled status of the object.
MooseApp & getMooseApp () const
Get the MooseApp this class is associated with.
const std::string & type () const
Get the type of this class.
virtual const std::string & name () const
Get the name of the class.
std::string typeAndName () const
Get the class's combined type and name; useful in error handling.
MooseObjectParameterName uniqueParameterName (const std::string &parameter_name) const
The unique parameter name of a valid parameter of this object for accessing parameter controls.
const InputParameters & parameters () const
Get the parameters of the object.
MooseObjectName uniqueName () const
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
template<typename T >
const T & getParam (const std::string &name) const
Retrieve a parameter for the object.
template<typename T1 , typename T2 >
std::vector< std::pair< T1, T2 > > getParam (const std::string &param1, const std::string &param2) const
Retrieve two parameters and provide pair of parameters for the object.
template<typename T >
const T & getRenamedParam (const std::string &old_name, const std::string &new_name) const
Retrieve a renamed parameter for the object.
template<typename T >
T getCheckedPointerParam (const std::string &name, const std::string &error_string="") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
bool isParamValid (const std::string &name) const
Test if the supplied parameter is valid.
bool isParamSetByUser (const std::string &nm) const
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
template<typename... Args>
void paramError (const std::string &param, Args... args) const
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramWarning (const std::string &param, Args... args) const
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramInfo (const std::string &param, Args... args) const
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
std::string objectErrorPrefix (const std::string &error_type) const
A descriptive prefix for errors for an object.
void connectControllableParams (const std::string &parameter, const std::string &object_type, const std::string &object_name, const std::string &object_parameter) const
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
template<typename... Args>
void mooseError (Args &&... args) const
Emits an error prefixed with object name and type.
template<typename... Args>
void mooseErrorNonPrefixed (Args &&... args) const
Emits an error without the prefixing included in mooseError().
template<typename... Args>
void mooseWarning (Args &&... args) const
Emits a warning prefixed with object name and type.
template<typename... Args>
void mooseWarningNonPrefixed (Args &&... args) const
Emits a warning without the prefixing included in mooseWarning().
template<typename... Args>
void mooseDeprecated (Args &&... args) const
template<typename... Args>
void mooseInfo (Args &&... args) const
std::string errorPrefix (const std::string &error_type) const
A descriptive prefix for errors for this object:
std::string getDataFileName (const std::string &param) const
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
std::string getDataFileNameByName (const std::string &name, const std::string *param=nullptr) const
Returns the path of a data file for a given relative file path.
PerfGraph & perfGraph ()
Get the PerfGraph.
Static Public Member Functions
static InputParameters validParams ()
static void copyVarValues (MeshBase &mesh, const unsigned int from_system, const unsigned int from_var, const NumericVector< Number > &from_vector, const unsigned int to_system, const unsigned int to_var, NumericVector< Number > &to_vector)
Helper function for copying values associated with variables in vectors from two different systems.
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Member Functions
void setCouplingMatrix (std::unique_ptr< CouplingMatrix > cm)
Setup the coupling matrix on the finite element problem.
template<typename T , typename... Args>
T & declareRestartableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
ManagedValue< T > declareManagedRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declares a piece of "managed" restartable data and initialize it.
template<typename T , typename... Args>
const T & getRestartableData (const std::string &data_name) const
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
template<typename T , typename... Args>
T & declareRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
T & declareRecoverableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "recoverable" and initialize it.
template<typename T , typename... Args>
T & declareRestartableDataWithObjectName (const std::string &data_name, const std::string &object_name, Args &&... args)
Declare a piece of data as "restartable".
template<typename T , typename... Args>
T & declareRestartableDataWithObjectNameWithContext (const std::string &data_name, const std::string &object_name, void *context, Args &&... args)
Declare a piece of data as "restartable".
std::string restartableName (const std::string &data_name) const
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level) const
Call to register a named section for timing.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level, const std::string &live_message, const bool print_dots=true) const
Call to register a named section for timing.
std::string timedSectionName (const std::string &section_name) const
Protected Attributes
FEProblemBase & _fe_problem
Subproblem this preconditioner is part of.
const unsigned int _nl_sys_num
The nonlinear system number whose linearization this preconditioner should be applied to.
const bool & _enabled
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
MooseApp & _app
The MOOSE application this is associated with.
const std::string & _type
The type of this class.
const std::string & _name
The name of this class, reference to value stored in InputParameters.
const InputParameters & _pars
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Factory & _factory
The Factory associated with the MooseApp.
ActionFactory & _action_factory
Builds Actions.
MooseApp & _restartable_app
Reference to the application.
const std::string _restartable_system_name
The system name this object is in.
const THREAD_ID _restartable_tid
The thread ID for this object.
const bool _restartable_read_only
Flag for toggling read only status (see ReporterData)
MooseApp & _pg_moose_app
The MooseApp that owns the PerfGraph.
const std::string _prefix
A prefix to use for all sections.
Private Member Functions
void getDofToCondense ()
Get dofs for the variable to be condensed out.
void getDofColRow ()
Get row and col dofs for the condensed system.
void findZeroDiagonals (SparseMatrix< Number > &mat, std::vector< dof_id_type > &indices)
Check if the original jacobian has zero diagonal entries and save the row indices.
void condenseSystem ()
Reconstruct the equation system.
void preallocateCondensedJacobian (PetscMatrix< Number > &condensed_mat, PetscMatrix< Number > &original_mat, const std::vector< dof_id_type > &rows, const std::vector< dof_id_type > &cols, const std::vector< dof_id_type > &grows, const std::vector< dof_id_type > &gcols, PetscMatrix< Number > &block_mat)
Preallocate memory for the condensed Jacobian matrix.
void computeCondensedJacobian (PetscMatrix< Number > &condensed_mat, PetscMatrix< Number > &original_mat, const std::vector< dof_id_type > &grows, PetscMatrix< Number > &block_mat)
The condensed Jacobian matrix is computed in this function.
void computeDInverse (Mat &mat)
Compute inverse of D using LU.
void computeDInverseDiag (Mat &mat)
Compute (approximate) inverse of D by inverting its diagonal entries.
void getCondensedXY (const NumericVector< Number > &y, NumericVector< Number > &x)
Get condensed x and y.
void computeCondensedVariables ()
Compute condensed variables (Lagrange multipliers) values using updated solution vector.
void getFullSolution (const NumericVector< Number > &y, NumericVector< Number > &x)
Assemble the full solution vector.
void mergeArrays (const PetscInt *a, const PetscInt *b, const PetscInt &na, const PetscInt &nb, std::vector< PetscInt > &c)
Find the common part of arrays a and b and save it in c.
template<typename... Args>
std::string paramErrorMsg (const std::string &param, Args... args) const
RestartableDataValue & registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const
Helper function for actually registering the restartable data.
void registerRestartableNameWithFilterOnApp (const std::string &name, Moose::RESTARTABLE_FILTER filter)
Helper function for actually registering the restartable data.
template<typename T , typename... Args>
RestartableData< T > & declareRestartableDataHelper (const std::string &data_name, void *context, Args &&... args) const
Helper function for declaring restartable data.
Private Attributes
NonlinearSystemBase & _nl
The nonlinear system this PC is associated with (convenience reference)
MooseMesh & _mesh
Mesh object for easy reference.
const DofMap & _dofmap
DofMap for easy reference.
const bool _is_lm_coupling_diagonal
Whether the coupling is diagonal.
const bool _adaptive_condensation
Whether to condense all specified variable.
const unsigned int _n_vars
Number of variables.
const std::vector< std::string > _lm_var_names
Name and ID of the variables that are to be condensed out (usually the Lagrange multiplier variable)
std::vector< unsigned int > _lm_var_ids
const std::vector< std::string > _primary_var_names
Name and ID of the corresponding coupled variable.
std::vector< unsigned int > _primary_var_ids
std::unique_ptr< PetscMatrix< Number > > _D
Submatrices that are frequently needed while computing the condensed system _D: the submatrix that couples the primary variable with the Lagrange multiplier variable _M: the columns that correspond to the Lagrange multiplier DoFs _K: the rows that correspond to the primary variable DoFs.
std::unique_ptr< PetscMatrix< Number > > _M
std::unique_ptr< PetscMatrix< Number > > _K
Mat _dinv
inverse of _D
std::unique_ptr< PetscMatrix< Number > > _J_condensed
Condensed Jacobian.
std::unique_ptr< NumericVector< Number > > _x_hat
_x_hat, _y_hat: condensed solution and RHS vectors _primary_rhs_vec: part of the RHS vector that correspond to the primary variable DoFs _lm_sol_vec: solution vector that corresponds to the LM variable
std::unique_ptr< NumericVector< Number > > _y_hat
std::unique_ptr< NumericVector< Number > > _primary_rhs_vec
std::unique_ptr< NumericVector< Number > > _lm_sol_vec
std::vector< dof_id_type > _zero_rows
The row indices that correspond to the zero diagonal entries in the original Jacobian matrix This is only used when _adaptive_condensation = true.
bool _need_condense
Whether the DoFs associated the variable are to be condensed.
PreconditionerType _pre_type
Which preconditioner to use for the solve.
std::unique_ptr< Preconditioner< Number > > _preconditioner
Holds one Preconditioner object for the condensed system to solve.
std::vector< dof_id_type > _global_lm_dofs
Vectors of DoFs: indices associated with lagrange multipliers, and its coupled primary variable global<variable_name>_dofs represents the indices that are owned by all processors _<variable_name>_dofs represents the indices that are owned only by each processor lm: the Lagrange multiplier primary: the primal variable DoFs that couples with the Lagrange multiplier Note: the global index sets may not be scalable and necessary memory optimization will be investigated later.
std::vector< dof_id_type > _lm_dofs
std::vector< dof_id_type > _global_primary_dofs
std::vector< dof_id_type > _primary_dofs
std::vector< dof_id_type > _global_rows
row and column indices for the condensed system
std::vector< dof_id_type > _rows
std::vector< dof_id_type > _global_cols
std::vector< dof_id_type > _cols
std::unordered_map< dof_id_type, dof_id_type > _global_rows_to_idx
Maps to keep track of row and col indices from the original Jacobian matrix to the condensed Jacobian matrix.
std::unordered_map< dof_id_type, dof_id_type > _rows_to_idx
std::unordered_map< dof_id_type, dof_id_type > _global_cols_to_idx
std::unordered_map< dof_id_type, dof_id_type > _cols_to_idx
std::unordered_map< dof_id_type, dof_id_type > _map_global_lm_primary
Maps to keep track of the dof orders for keeping nonzero diagonal entries of the condensed system _map_global_lm_primary: map between _global_lm_dofs and _global_primary_dofs.
std::unordered_map< dof_id_type, dof_id_type > _map_global_primary_order
PerfID _init_timer
Timers.
PerfID _apply_timer
const MooseBase *const _moose_base
The MooseBase object that inherits this class.
const MooseObject & _parent
const RestartableDataMapName _metaname
Restartable metadata name.
std::string _restartable_name
The name of the object.
Detailed Description
Interface for condensing out LMs for the dual mortar approach.
Definition at line 33 of file VariableCondensationPreconditioner.h.
Constructor & Destructor Documentation
VariableCondensationPreconditioner()
VariableCondensationPreconditioner::VariableCondensationPreconditioner (const InputParameters & params)
Definition at line 79 of file VariableCondensationPreconditioner.C.
  : MoosePreconditioner(params),
    Preconditioner<Number>(MoosePreconditioner::_communicator),
    _nl(_fe_problem.getNonlinearSystemBase(_nl_sys_num)),
    _mesh(_fe_problem.mesh()),
    _dofmap(_nl.system().get_dof_map()),
    _is_lm_coupling_diagonal(getParam<bool>("is_lm_coupling_diagonal")),
    _adaptive_condensation(getParam<bool>("adaptive_condensation")),
    _n_vars(_nl.nVariables()),
    _lm_var_names(getParam<std::vector<std::string>>("lm_variable")),
    _primary_var_names(getParam<std::vector<std::string>>("primary_variable")),
    _D(std::make_unique<PetscMatrix<Number>>(MoosePreconditioner::_communicator)),
    _M(std::make_unique<PetscMatrix<Number>>(MoosePreconditioner::_communicator)),
    _K(std::make_unique<PetscMatrix<Number>>(MoosePreconditioner::_communicator)),
    _dinv(nullptr),
    _J_condensed(std::make_unique<PetscMatrix<Number>>(MoosePreconditioner::_communicator)),
    _x_hat(NumericVector<Number>::build(MoosePreconditioner::_communicator)),
    _y_hat(NumericVector<Number>::build(MoosePreconditioner::_communicator)),
    _primary_rhs_vec(NumericVector<Number>::build(MoosePreconditioner::_communicator)),
    _lm_sol_vec(NumericVector<Number>::build(MoosePreconditioner::_communicator)),
    _need_condense(true),
    _init_timer(registerTimedSection("init", 2)),
    _apply_timer(registerTimedSection("apply", 1))
{
  if (_lm_var_names.size() != _primary_var_names.size())
    paramError("coupled_variable", "coupled_variable should have the same size as the variable.");
  if (!_mesh.getMesh().is_replicated())
    mooseError("The VariableCondensationPreconditioner cannot be used with DistributedMesh");
  // get variable ids from the variable names
  for (const auto & var_name : _lm_var_names)
  {
    if (!_nl.system().has_variable(var_name))
      paramError("variable ", var_name, " does not exist in the system");
    const unsigned int id = _nl.system().variable_number(var_name);
    _lm_var_ids.push_back(id);
  }
  // get coupled variable ids from the coupled variable names
  for (const auto & var_name : _primary_var_names)
  {
    if (!_nl.system().has_variable(var_name))
      paramError("coupled_variable ", var_name, " does not exist in the system");
    const unsigned int id = _nl.system().variable_number(var_name);
    _primary_var_ids.push_back(id);
  }
  // PC type
  const std::vector<std::string> & pc_type = getParam<std::vector<std::string>>("preconditioner");
  if (pc_type.size() > 1)
    mooseWarning("We only use one preconditioner type in VCP, the ",
                 pc_type[0],
                 " preconditioner is utilized.");
  _pre_type = Utility::string_to_enum<PreconditionerType>(pc_type[0]);
  // The following obtains and sets the coupling matrix.
  // TODO: This part can be refactored together with what are in other classes, e.g.,
  // PhysicsBasedPreconditioner
  std::unique_ptr<CouplingMatrix> cm = std::make_unique<CouplingMatrix>(_n_vars);
  const bool full = getParam<bool>("full");
  if (!full)
  {
    // put 1s on diagonal
    for (const auto i : make_range(_n_vars))
      (*cm)(i, i) = 1;
    // off-diagonal entries from the off_diag_row and off_diag_column parameters
    std::vector<std::vector<unsigned int>> off_diag(_n_vars);
    if (isParamValid("off_diag_row") && isParamValid("off_diag_column"))
      for (const auto i : index_range(getParam<std::vector<NonlinearVariableName>>("off_diag_row")))
      {
        const unsigned int row =
            _nl.getVariable(0, getParam<std::vector<NonlinearVariableName>>("off_diag_row")[i])
                .number();
        const unsigned int column =
            _nl.getVariable(0, getParam<std::vector<NonlinearVariableName>>("off_diag_column")[i])
                .number();
        (*cm)(row, column) = 1;
      }
    // off-diagonal entries from the coupled_groups parameters
    for (const auto & coupled_group :
         getParam<std::vector<NonlinearVariableName>>("coupled_groups"))
    {
      std::vector<NonlinearVariableName> vars;
      MooseUtils::tokenize<NonlinearVariableName>(coupled_group, vars, 1, ",");
      for (unsigned int j : index_range(vars))
        for (unsigned int k = j + 1; k < vars.size(); ++k)
        {
          const unsigned int row = _nl.getVariable(0, vars[j]).number();
          const unsigned int column = _nl.getVariable(0, vars[k]).number();
          (*cm)(row, column) = 1;
          (*cm)(column, row) = 1;
        }
    }
  }
  else
  {
    for (unsigned int i = 0; i < _n_vars; i++)
      for (unsigned int j = 0; j < _n_vars; j++)
        (*cm)(i, j) = 1;
  }
  setCouplingMatrix(std::move(cm));
  _nl.attachPreconditioner(this);
}
~VariableCondensationPreconditioner()
VariableCondensationPreconditioner::~VariableCondensationPreconditioner () virtual
Definition at line 191 of file VariableCondensationPreconditioner.C.
{ this->clear(); }
Member Function Documentation
apply()
void VariableCondensationPreconditioner::apply (const NumericVector< Number > & y, NumericVector< Number > & x) virtual
Computes the preconditioned vector "x" based on input "y".
Usually by solving Px=y to get the action of P^-1 y.
Definition at line 629 of file VariableCondensationPreconditioner.C.
{
  TIME_SECTION(_apply_timer);
  if (_need_condense)
  {
    getCondensedXY(y, x);
    _preconditioner->apply(*_y_hat, *_x_hat);
    computeCondensedVariables();
    getFullSolution(y, x);
  }
  else
  {
    _preconditioner->apply(y, x);
  }
}
clear()
void VariableCondensationPreconditioner::clear () virtual
Release all memory and clear data structures.
Definition at line 767 of file VariableCondensationPreconditioner.C.
{
  PetscErrorCode ierr;
  if (_dinv != nullptr)
  {
    ierr = MatDestroy(&_dinv);
    LIBMESH_CHKERR(ierr);
  }
}
Referenced by ~VariableCondensationPreconditioner().
computeCondensedJacobian()
void VariableCondensationPreconditioner::computeCondensedJacobian (PetscMatrix< Number > & condensed_mat, PetscMatrix< Number > & original_mat, const std::vector< dof_id_type > & grows, PetscMatrix< Number > & block_mat) private
The condensed Jacobian matrix is computed in this function.
Definition at line 401 of file VariableCondensationPreconditioner.C.
{
  PetscErrorCode ierr = 0;
  // obtain entries from the original matrix
  PetscInt pc_ncols = 0, block_ncols = 0;
  const PetscInt *pc_cols, *block_cols;
  const PetscScalar *pc_vals, *block_vals;
  // containers for the data
  std::vector<PetscInt> sub_cols;
  std::vector<PetscScalar> sub_vals;
  for (const auto & i : index_range(grows))
  {
    PetscInt sub_rid[] = {static_cast<PetscInt>(i)};
    PetscInt rid = grows[i];
    if (grows[i] >= original_mat.row_start() && grows[i] < original_mat.row_stop())
    {
      // get one row of data from the original matrix
      ierr = MatGetRow(original_mat.mat(), rid, &pc_ncols, &pc_cols, &pc_vals);
      LIBMESH_CHKERR(ierr);
      // get corresponding row of data from the block matrix
      ierr = MatGetRow(block_mat.mat(), i, &block_ncols, &block_cols, &block_vals);
      LIBMESH_CHKERR(ierr);
      // extract data from certain cols, subtract the value from the block mat, and save the indices
      // and entries sub_cols and sub_vals
      // First, save the submatrix col index and value as a map
      std::map<PetscInt, PetscScalar> pc_col_map;
      for (PetscInt pc_idx = 0; pc_idx < pc_ncols; pc_idx++)
      {
        // save only if the col exists in the condensed matrix
        if (_global_cols_to_idx.find(pc_cols[pc_idx]) != _global_cols_to_idx.end())
          pc_col_map.insert(std::make_pair(_global_cols_to_idx[pc_cols[pc_idx]], pc_vals[pc_idx]));
      }
      // Second, check the block cols and calculate new entries for the condensed system
      for (PetscInt block_idx = 0; block_idx < block_ncols; block_idx++)
      {
        PetscInt block_col = block_cols[block_idx];
        PetscScalar block_val = block_vals[block_idx];
        // if the block mat has nonzero at the same column, subtract value
        // otherwise, create a new key and save the negative value from the block matrix
        if (pc_col_map.find(block_col) != pc_col_map.end())
          pc_col_map[block_col] -= block_val;
        else
          pc_col_map[block_col] = -block_val;
      }
      // Third, save keys in the sub_cols and values in the sub_vals
      for (std::map<PetscInt, PetscScalar>::iterator it = pc_col_map.begin();
           it != pc_col_map.end();
           ++it)
      {
        sub_cols.push_back(it->first);
        sub_vals.push_back(it->second);
      }
      // Then, set values
      ierr = MatSetValues(condensed_mat.mat(),
                          1,
                          sub_rid,
                          sub_vals.size(),
                          sub_cols.data(),
                          sub_vals.data(),
                          INSERT_VALUES);
      LIBMESH_CHKERR(ierr);
      ierr = MatRestoreRow(original_mat.mat(), rid, &pc_ncols, &pc_cols, &pc_vals);
      LIBMESH_CHKERR(ierr);
      ierr = MatRestoreRow(block_mat.mat(), i, &block_ncols, &block_cols, &block_vals);
      LIBMESH_CHKERR(ierr);
      // clear data for this row
      sub_cols.clear();
      sub_vals.clear();
    }
  }
  condensed_mat.close();
}
Referenced by condenseSystem().
computeCondensedVariables()
void VariableCondensationPreconditioner::computeCondensedVariables () private
Compute condensed variables (Lagrange multipliers) values using updated solution vector.
Definition at line 689 of file VariableCondensationPreconditioner.C.
{
  _lm_sol_vec->clear();
  PetscMatrix<Number> Dinv(_dinv, MoosePreconditioner::_communicator);
  _lm_sol_vec->init(_D->m(), _D->local_m(), false, PARALLEL);
  std::unique_ptr<NumericVector<Number>> K_xhat(
      NumericVector<Number>::build(MoosePreconditioner::_communicator));
  K_xhat->init(_K->m(), _K->local_m(), false, PARALLEL);
  _K->vector_mult(*K_xhat, *_x_hat);
  K_xhat->close();
  (*_primary_rhs_vec) -= (*K_xhat);
  _primary_rhs_vec->close();
  Dinv.vector_mult(*_lm_sol_vec, *_primary_rhs_vec);
  _lm_sol_vec->close();
}
Referenced by apply().
computeDInverse()
void VariableCondensationPreconditioner::computeDInverse (Mat & mat) private
Compute inverse of D using LU.
This method is used when _is_lm_coupling_diagonal = false.
Definition at line 778 of file VariableCondensationPreconditioner.C.
{
  PetscErrorCode ierr;
  Mat F, I, dinv_dense;
  IS perm, iperm;
  MatFactorInfo info;
  ierr = MatCreateDense(
      PETSC_COMM_WORLD, _D->local_n(), _D->local_m(), _D->n(), _D->m(), NULL, &dinv_dense);
  LIBMESH_CHKERR(ierr);
  // Create an identity matrix as the right-hand-side
  ierr = MatCreateDense(PETSC_COMM_WORLD, _D->local_m(), _D->local_m(), _D->m(), _D->m(), NULL, &I);
  LIBMESH_CHKERR(ierr);
  for (unsigned int i = 0; i < _D->m(); ++i)
  {
    ierr = MatSetValue(I, i, i, 1.0, INSERT_VALUES);
    LIBMESH_CHKERR(ierr);
  }
  ierr = MatAssemblyBegin(I, MAT_FINAL_ASSEMBLY);
  LIBMESH_CHKERR(ierr);
  ierr = MatAssemblyEnd(I, MAT_FINAL_ASSEMBLY);
  LIBMESH_CHKERR(ierr);
  // Factorize D
  ierr = MatGetOrdering(_D->mat(), MATORDERINGND, &perm, &iperm);
  LIBMESH_CHKERR(ierr);
  ierr = MatFactorInfoInitialize(&info);
  LIBMESH_CHKERR(ierr);
  ierr = MatGetFactor(_D->mat(), MATSOLVERSUPERLU_DIST, MAT_FACTOR_LU, &F);
  LIBMESH_CHKERR(ierr);
  ierr = MatLUFactorSymbolic(F, _D->mat(), perm, iperm, &info);
  LIBMESH_CHKERR(ierr);
  ierr = MatLUFactorNumeric(F, _D->mat(), &info);
  LIBMESH_CHKERR(ierr);
  // Solve for Dinv
  ierr = MatMatSolve(F, I, dinv_dense);
  LIBMESH_CHKERR(ierr);
  ierr = MatAssemblyBegin(dinv_dense, MAT_FINAL_ASSEMBLY);
  LIBMESH_CHKERR(ierr);
  ierr = MatAssemblyEnd(dinv_dense, MAT_FINAL_ASSEMBLY);
  LIBMESH_CHKERR(ierr);
  // copy value to dinv
  ierr = MatConvert(dinv_dense, MATAIJ, MAT_INITIAL_MATRIX, &dinv);
  LIBMESH_CHKERR(ierr);
  ierr = MatDestroy(&dinv_dense);
  LIBMESH_CHKERR(ierr);
  ierr = MatDestroy(&I);
  LIBMESH_CHKERR(ierr);
  ierr = MatDestroy(&F);
  LIBMESH_CHKERR(ierr);
  ierr = ISDestroy(&perm);
  LIBMESH_CHKERR(ierr);
  ierr = ISDestroy(&iperm);
  LIBMESH_CHKERR(ierr);
}
Referenced by condenseSystem().
computeDInverseDiag()
void VariableCondensationPreconditioner::computeDInverseDiag (Mat & mat) private
Compute (approximate) inverse of D by inverting its diagonal entries.
This method is used when _is_lm_coupling_diagonal = true.
Definition at line 847 of file VariableCondensationPreconditioner.C.
{
  PetscErrorCode ierr;
  auto diag_D = NumericVector<Number>::build(MoosePreconditioner::_communicator);
  // Initialize dinv
  ierr = MatCreateAIJ(
      PETSC_COMM_WORLD, _D->local_n(), _D->local_m(), _D->n(), _D->m(), 1, NULL, 0, NULL, &dinv);
  LIBMESH_CHKERR(ierr);
  // Allocate storage
  diag_D->init(_D->m(), _D->local_m(), false, PARALLEL);
  // Fill entries
  for (const auto & i : make_range(_D->row_start(), _D->row_stop()))
  {
    auto it = _map_global_primary_order.find(_global_primary_dofs[i]);
    mooseAssert(it != _map_global_primary_order.end(), "Index does not exist in the map.");
    diag_D->set(it->second, (*_D)(i, it->second));
  }
  for (const auto & i : make_range(_D->row_start(), _D->row_stop()))
  {
    if (MooseUtils::absoluteFuzzyEqual((*diag_D)(i), 0.0))
      mooseError("Trying to compute reciprocal of 0.");
    ierr = MatSetValue(dinv,
                       i,
                       _map_global_primary_order.at(_global_primary_dofs[i]),
                       1.0 / (*diag_D)(i),
                       INSERT_VALUES);
    LIBMESH_CHKERR(ierr);
  }
  ierr = MatAssemblyBegin(dinv, MAT_FINAL_ASSEMBLY);
  LIBMESH_CHKERR(ierr);
  ierr = MatAssemblyEnd(dinv, MAT_FINAL_ASSEMBLY);
  LIBMESH_CHKERR(ierr);
}
Referenced by condenseSystem().
condenseSystem()
void VariableCondensationPreconditioner::condenseSystem () private
Reconstruct the equation system.
Definition at line 343 of file VariableCondensationPreconditioner.C.
{
  PetscErrorCode ierr = 0;
  // extract _M from the original matrix
  _matrix->create_submatrix(*_M, _rows, _lm_dofs);
  // get the row associated with the coupled primary variable
  _K->init(_global_primary_dofs.size(), _global_cols.size(), _primary_dofs.size(), _cols.size());
  // Note: enabling nonzero allocation may be expensive. Improved memeory pre-allocation will be
  // investigated in the future
  ierr = MatSetOption(_K->mat(), MAT_NEW_NONZERO_ALLOCATION_ERR, PETSC_FALSE);
  LIBMESH_CHKERR(ierr);
  // here the _global_cols may not be sorted
  _matrix->create_submatrix_nosort(*_K, _global_primary_dofs, _global_cols);
  _matrix->create_submatrix(*_D, _primary_dofs, _lm_dofs);
  // clean dinv
  if (_dinv)
  {
    ierr = MatDestroy(&_dinv);
    LIBMESH_CHKERR(ierr);
    _dinv = nullptr;
  }
  // Compute inverse of D
  if (_is_lm_coupling_diagonal)
    // when _D is strictly diagonal, we only need to compute the reciprocal number of the diagonal
    // entries
    computeDInverseDiag(_dinv);
  else
    // for general cases when _D is not necessarily strict diagonal, we compute the inverse of _D
    // using LU
    computeDInverse(_dinv);
  Mat MdinvK;
  // calculate MdinvK
  ierr = MatMatMatMult(_M->mat(), _dinv, _K->mat(), MAT_INITIAL_MATRIX, PETSC_DEFAULT, &MdinvK);
  LIBMESH_CHKERR(ierr);
  PetscMatrix<Number> MDinv_K(MdinvK, MoosePreconditioner::_communicator);
  // Preallocate memory for _J_condensed
  // memory info is obtained from _matrix and MDinv_K
  // indices are from _global_rows, _global_cols
  auto pc_original_mat = cast_ptr<PetscMatrix<Number> *>(_matrix);
  preallocateCondensedJacobian(
      *_J_condensed, *pc_original_mat, _rows, _cols, _global_rows, _global_cols, MDinv_K);
  // Extract unchanged parts from _matrix and add changed parts (MDinv_K) to _J_condensed
  computeCondensedJacobian(*_J_condensed, *pc_original_mat, _global_rows, MDinv_K);
  // Destroy MdinvK here otherwise we will have memory leak
  ierr = MatDestroy(&MdinvK);
  LIBMESH_CHKERR(ierr);
}
Referenced by setup().
connectControllableParams()
void MooseBaseParameterInterface::connectControllableParams (const std::string & parameter, const std::string & object_type, const std::string & object_name, const std::string & object_parameter) const inherited
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
Parameters
parameter Name of the controllable parameter of this action
object_type Type of the object added by this action.
object_name Name of the object added by this action.
object_parameter Name of the parameter of the object.
Definition at line 34 of file MooseBaseParameterInterface.C.
{
  MooseObjectParameterName primary_name(uniqueName(), parameter);
  const auto base_type = _factory.getValidParams(object_type).get<std::string>("_moose_base");
  MooseObjectParameterName secondary_name(base_type, object_name, object_parameter);
  _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
      primary_name, secondary_name);
  const auto & tags = _pars.get<std::vector<std::string>>("control_tags");
  for (const auto & tag : tags)
  {
    if (!tag.empty())
    {
      MooseObjectParameterName tagged_name(tag, _moose_base->name(), parameter);
      _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
          tagged_name, secondary_name);
    }
  }
}
copyVarValues()
void MoosePreconditioner::copyVarValues (MeshBase & mesh, const unsigned int from_system, const unsigned int from_var, const NumericVector< Number > & from_vector, const unsigned int to_system, const unsigned int to_var, NumericVector< Number > & to_vector) static inherited
Helper function for copying values associated with variables in vectors from two different systems.
Definition at line 95 of file MoosePreconditioner.C.
{
  for (auto & node : mesh.local_node_ptr_range())
  {
    unsigned int n_comp = node->n_comp(from_system, from_var);
    mooseAssert(node->n_comp(from_system, from_var) == node->n_comp(to_system, to_var),
                "Number of components does not match in each system");
    for (unsigned int i = 0; i < n_comp; i++)
    {
      dof_id_type from_dof = node->dof_number(from_system, from_var, i);
      dof_id_type to_dof = node->dof_number(to_system, to_var, i);
      to_vector.set(to_dof, from_vector(from_dof));
    }
  }
  for (auto & elem : as_range(mesh.local_elements_begin(), mesh.local_elements_end()))
  {
    unsigned int n_comp = elem->n_comp(from_system, from_var);
    mooseAssert(elem->n_comp(from_system, from_var) == elem->n_comp(to_system, to_var),
                "Number of components does not match in each system");
    for (unsigned int i = 0; i < n_comp; i++)
    {
      dof_id_type from_dof = elem->dof_number(from_system, from_var, i);
      dof_id_type to_dof = elem->dof_number(to_system, to_var, i);
      to_vector.set(to_dof, from_vector(from_dof));
    }
  }
}
Referenced by PhysicsBasedPreconditioner::apply().
declareManagedRestartableDataWithContext()
template<typename T , typename... Args> Restartable::ManagedValue< T > Restartable::declareManagedRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declares a piece of "managed" restartable data and initialize it.
Here, "managed" restartable data means that the caller can destruct this data upon destruction of the return value of this method. Therefore, this ManagedValue<T> wrapper should survive after the final calls to dataStore() for it. That is... at the very end.
This is needed for objects whose destruction ordering is important, and enables natural c++ destruction in reverse construction order of the object that declares it.
See delcareRestartableData and declareRestartableDataWithContext for more information.
Definition at line 276 of file Restartable.h.
{
  auto & data_ptr =
      declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...);
  return Restartable::ManagedValue<T>(data_ptr);
}
declareRecoverableData()
template<typename T , typename... Args> T & Restartable::declareRecoverableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "recoverable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
Note - this data will NOT be restored on Restart!
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 351 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  registerRestartableNameWithFilterOnApp(full_name, Moose::RESTARTABLE_FILTER::RECOVERABLE);
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableData()
template<typename T , typename... Args> T & Restartable::declareRestartableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 269 of file Restartable.h.
{
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataHelper()
template<typename T , typename... Args> RestartableData< T > & Restartable::declareRestartableDataHelper (const std::string & data_name, void * context, Args &&... args) const private inherited
Helper function for declaring restartable data.
We use this function to reduce code duplication when returning const/nonconst references to the data.
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 303 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  // Here we will create the RestartableData even though we may not use this instance.
  // If it's already in use, the App will return a reference to the existing instance and we'll
  // return that one instead. We might refactor this to have the app create the RestartableData
  // at a later date.
  auto data_ptr =
      std::make_unique<RestartableData<T>>(full_name, context, std::forward<Args>(args)...);
  auto & restartable_data_ref = static_cast<RestartableData<T> &>(
      registerRestartableDataOnApp(std::move(data_ptr), _restartable_tid));
  return restartable_data_ref;
}
declareRestartableDataWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 294 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...).set();
}
declareRestartableDataWithObjectName()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectName (const std::string & data_name, const std::string & object_name, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
args Arguments to forward to the constructor of the data
Definition at line 323 of file Restartable.h.
{
  return declareRestartableDataWithObjectNameWithContext<T>(
      data_name, object_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataWithObjectNameWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectNameWithContext (const std::string & data_name, const std::string & object_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 333 of file Restartable.h.
{
  std::string old_name = _restartable_name;
  _restartable_name = object_name;
  T & value = declareRestartableDataWithContext<T>(data_name, context, std::forward<Args>(args)...);
  _restartable_name = old_name;
  return value;
}
enabled()
virtual bool MooseObject::enabled () const inline virtual inherited
Return the enabled status of the object.
Reimplemented in EigenKernel.
Definition at line 54 of file MooseObject.h.
{ return _enabled; }
Referenced by EigenKernel::enabled().
errorPrefix()
std::string MooseBaseErrorInterface::errorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for this object:
The following <error_type> occurred in the object "<name>", of type "<type>".
Definition at line 15 of file MooseBaseErrorInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the object \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseErrorInterface::mooseError(), and MooseBaseErrorInterface::mooseWarning().
findZeroDiagonals()
void VariableCondensationPreconditioner::findZeroDiagonals (SparseMatrix< Number > & mat, std::vector< dof_id_type > & indices) private
Check if the original jacobian has zero diagonal entries and save the row indices.
Definition at line 735 of file VariableCondensationPreconditioner.C.
{
  indices.clear();
  IS zerodiags, zerodiags_all;
  PetscErrorCode ierr;
  const PetscInt * petsc_idx;
  PetscInt nrows;
  // make sure we have a PETSc matrix
  PetscMatrix<Number> * petsc_mat = cast_ptr<PetscMatrix<Number> *>(&mat);
  ierr = MatFindZeroDiagonals(petsc_mat->mat(), &zerodiags);
  LIBMESH_CHKERR(ierr);
  // synchronize all indices
  ierr = ISAllGather(zerodiags, &zerodiags_all);
  LIBMESH_CHKERR(ierr);
  ierr = ISGetIndices(zerodiags_all, &petsc_idx);
  LIBMESH_CHKERR(ierr);
  ierr = ISGetSize(zerodiags_all, &nrows);
  LIBMESH_CHKERR(ierr);
  for (PetscInt i = 0; i < nrows; ++i)
    indices.push_back(petsc_idx[i]);
  ISRestoreIndices(zerodiags_all, &petsc_idx);
  LIBMESH_CHKERR(ierr);
  ierr = ISDestroy(&zerodiags);
  LIBMESH_CHKERR(ierr);
  ierr = ISDestroy(&zerodiags_all);
  LIBMESH_CHKERR(ierr);
}
Referenced by setup().
getCheckedPointerParam()
template<typename T > T MooseBaseParameterInterface::getCheckedPointerParam (const std::string & name, const std::string & error_string = "") const inherited
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
The template parameter must be a pointer or an error will be thrown.
Definition at line 264 of file MooseBaseParameterInterface.h.
{
  return parameters().getCheckedPointerParam<T>(name, error_string);
}
getCondensedXY()
void VariableCondensationPreconditioner::getCondensedXY (const NumericVector< Number > & y, NumericVector< Number > & x) private
Get condensed x and y.
Definition at line 651 of file VariableCondensationPreconditioner.C.
{
  Mat mdinv;
  PetscErrorCode ierr = 0;
  // calculate mdinv
  ierr = MatMatMult(_M->mat(), _dinv, MAT_INITIAL_MATRIX, PETSC_DEFAULT, &mdinv);
  LIBMESH_CHKERR(ierr);
  PetscMatrix<Number> MDinv(mdinv, MoosePreconditioner::_communicator);
  _x_hat->init(_J_condensed->n(), _J_condensed->local_n(), false, PARALLEL);
  _y_hat->init(_J_condensed->m(), _J_condensed->local_m(), false, PARALLEL);
  x.create_subvector(*_x_hat, _global_cols);
  y.create_subvector(*_y_hat, _global_rows);
  _primary_rhs_vec->init(MDinv.n(), MDinv.local_n(), false, PARALLEL);
  std::unique_ptr<NumericVector<Number>> mdinv_primary_rhs(
      NumericVector<Number>::build(MoosePreconditioner::_communicator));
  mdinv_primary_rhs->init(MDinv.m(), MDinv.local_m(), false, PARALLEL);
  // get _primary_rhs_vec from the original y
  y.create_subvector(*_primary_rhs_vec, _global_primary_dofs);
  MDinv.vector_mult(*mdinv_primary_rhs, *_primary_rhs_vec);
  mdinv_primary_rhs->close();
  (*_y_hat) -= (*mdinv_primary_rhs);
  _y_hat->close();
  _x_hat->close();
  ierr = MatDestroy(&mdinv);
  LIBMESH_CHKERR(ierr);
}
Referenced by apply().
getDataFileName()
std::string DataFileInterface< MooseObject >::getDataFileName (const std::string & param) const inherited
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
relative to the input file directory
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
relative to the input file directory
Definition at line 34 of file DataFileInterface.C.
{
  {
    const auto & absolute_path = _parent.template getParam<FileName>(param);
    if (MooseUtils::checkFileReadable(absolute_path, false, false, false))
    {
      _parent.paramInfo(param, "Data file '", absolute_path, "' found relative to the input file.");
      return absolute_path;
    }
  }
  const auto & relative_path = _parent.parameters().rawParamVal(param);
  return getDataFileNameByName(relative_path, &param);
}
getDataFileNameByName()
std::string DataFileInterface< MooseObject >::getDataFileNameByName (const std::string & name, const std::string * param = nullptr) const inherited
Returns the path of a data file for a given relative file path.
This can be used for hardcoded datafile names and will search the same locations as getDataFileName. The optional param pointer can be used to turn the mooseErrors this function emits into paramErrors
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
Definition at line 42 of file DataFileInterface.C.
{
  const auto share_dir = MooseUtils::pathjoin(Moose::getExecutablePath(), "..", "share");
  if (MooseUtils::pathIsDirectory(share_dir))
  {
    const auto dirs = MooseUtils::listDir(share_dir, false);
    for (const auto & data_dir : dirs)
    {
      const auto path = MooseUtils::pathjoin(data_dir, "data", relative_path);
      if (MooseUtils::checkFileReadable(path, false, false, false))
      {
        if (param)
          _parent.paramInfo(
              *param, "Data file '", path, "' found in an installed app distribution.");
        else
          mooseInfo("Data file '", path, "' found in an installed app distribution.");
        return path;
      }
    }
  }
  for (const auto & data_dir : Registry::getRegistry().getDataFilePaths())
  {
    const auto path = MooseUtils::pathjoin(data_dir, relative_path);
    if (MooseUtils::checkFileReadable(path, false, false, false))
    {
      if (param)
        _parent.paramInfo(*param, "Data file '", path, "' found in a source repository.");
      else
        mooseInfo("Data file '", path, "' found in a source repository.");
      return path;
    }
  }
  mooseException(param ? _parent.parameters().inputLocation(*param) : _parent.name(),
                 ": Unable to find data file '",
                 relative_path,
                 "' anywhere");
}
getDofColRow()
void VariableCondensationPreconditioner::getDofColRow () private
Get row and col dofs for the condensed system.
Definition at line 274 of file VariableCondensationPreconditioner.C.
{
  // clean the containers if we want to update the dofs
  _global_rows.clear();
  _rows.clear();
  _global_cols.clear();
  _cols.clear();
  _global_rows_to_idx.clear();
  _rows_to_idx.clear();
  _global_cols_to_idx.clear();
  _cols_to_idx.clear();
  // row: all without primary variable dofs
  // col: all without lm variable dofs
  for (dof_id_type i = 0; i < _dofmap.n_dofs(); ++i)
  {
    if (std::find(_global_primary_dofs.begin(), _global_primary_dofs.end(), i) !=
        _global_primary_dofs.end())
      continue;
    _global_rows.push_back(i);
    _global_rows_to_idx.insert(std::make_pair(i, _global_rows.size() - 1));
    if (_dofmap.local_index(i))
    {
      _rows.push_back(i);
      _rows_to_idx.insert(std::make_pair(i, _global_rows_to_idx[i]));
    }
    // ensure the lm and primary correspondance, so that the condensed Jacobian has non-zero
    // diagonal if the dof corresponds to the lm variable, then find the corresponding primary
    // variable dof and add to _global_cols
    if (_map_global_lm_primary.find(i) != _map_global_lm_primary.end())
    {
      auto primary_idx = _map_global_lm_primary[i];
      _global_cols.push_back(primary_idx);
      _global_cols_to_idx.insert(std::make_pair(primary_idx, _global_cols.size() - 1));
      if (_dofmap.local_index(primary_idx))
      {
        _cols.push_back(primary_idx);
        _cols_to_idx.insert(std::make_pair(primary_idx, _global_cols_to_idx[primary_idx]));
      }
    }
    else // if the dof does not correspond to the lm nor primary varialble, just add to _global_cols
    {
      _global_cols.push_back(i);
      _global_cols_to_idx.insert(std::make_pair(i, _global_cols.size() - 1));
      if (_dofmap.local_index(i))
      {
        _cols.push_back(i);
        _cols_to_idx.insert(std::make_pair(i, _global_cols_to_idx[i]));
      }
    }
  }
}
Referenced by setup().
getDofToCondense()
void VariableCondensationPreconditioner::getDofToCondense () private
Get dofs for the variable to be condensed out.
Definition at line 194 of file VariableCondensationPreconditioner.C.
{
  // clean the containers if we want to update the dofs
  _global_lm_dofs.clear();
  _lm_dofs.clear();
  _global_primary_dofs.clear();
  _primary_dofs.clear();
  _map_global_lm_primary.clear();
  _map_global_primary_order.clear();
  // TODO: this might not work for distributed mesh and needs to be improved
  NodeRange * active_nodes = _mesh.getActiveNodeRange();
  // loop through the variable ids
  std::vector<dof_id_type> di, cp_di;
  for (const auto & vn : index_range(_lm_var_ids))
    for (const auto & node : *active_nodes)
    {
      di.clear();
      cp_di.clear();
      const auto var_id = _lm_var_ids[vn];
      // get coupled variable id
      const auto cp_var_id = _primary_var_ids[vn];
      // get var and cp_var dofs associated with this node
      _dofmap.dof_indices(node, di, var_id);
      // skip when di is empty
      if (di.empty())
        continue;
      _dofmap.dof_indices(node, cp_di, cp_var_id);
      if (cp_di.size() != di.size())
        mooseError("variable and coupled variable do not have the same number of dof on node ",
                   node->id(),
                   ".");
      for (const auto & i : index_range(di))
      {
        // when we have adaptive condensation, skip when di does not contain any indices in
        // _zero_rows
        if (std::find(_zero_rows.begin(), _zero_rows.end(), di[i]) == _zero_rows.end() &&
            _adaptive_condensation)
          break;
        _global_lm_dofs.push_back(di[i]);
        if (_dofmap.local_index(di[i]))
          _lm_dofs.push_back(di[i]);
        // save the corresponding coupled dof indices
        _global_primary_dofs.push_back(cp_di[i]);
        if (_dofmap.local_index(cp_di[i]))
          _primary_dofs.push_back(cp_di[i]);
        _map_global_lm_primary.insert(std::make_pair(di[i], cp_di[i]));
      }
    }
  // check if we endup with none dof to condense
  if (_global_lm_dofs.empty())
  {
    _need_condense = false;
    _console << std::endl
             << "The variable(s) provided do not have a saddle-point character at this step. VCP "
                "will continue without condensing the dofs."
             << std::endl
             << std::endl;
  }
  else
    _need_condense = true;
  std::sort(_global_lm_dofs.begin(), _global_lm_dofs.end());
  std::sort(_lm_dofs.begin(), _lm_dofs.end());
  std::sort(_global_primary_dofs.begin(), _global_primary_dofs.end());
  std::sort(_primary_dofs.begin(), _primary_dofs.end());
  for (const auto & i : index_range(_global_lm_dofs))
  {
    auto it = _map_global_lm_primary.find(_global_lm_dofs[i]);
    mooseAssert(it != _map_global_lm_primary.end(), "Index does not exist in the map.");
    _map_global_primary_order.insert(std::make_pair(it->second, i));
  }
}
Referenced by setup().
getFullSolution()
void VariableCondensationPreconditioner::getFullSolution (const NumericVector< Number > & y, NumericVector< Number > & x) private
Assemble the full solution vector.
Definition at line 710 of file VariableCondensationPreconditioner.C.
{
  std::vector<dof_id_type> dof_indices;
  std::vector<Number> vals;
  // save values and indices from _x_hat and _lm_sol_vec
  for (const auto & i : make_range(_x_hat->first_local_index(), _x_hat->last_local_index()))
  {
    dof_indices.push_back(_global_cols[i]);
    vals.push_back((*_x_hat)(i));
  }
  for (const auto & i :
       make_range(_lm_sol_vec->first_local_index(), _lm_sol_vec->last_local_index()))
  {
    dof_indices.push_back(_global_lm_dofs[i]);
    vals.push_back((*_lm_sol_vec)(i));
  }
  x.insert(vals.data(), dof_indices);
  x.close();
}
Referenced by apply().
getMooseApp()
MooseApp & MooseBase::getMooseApp () const inline inherited
Get the MooseApp this class is associated with.
Definition at line 35 of file MooseBase.h.
{ return _app; }
Referenced by ReporterTransferInterface::checkHasReporterValue(), Coupleable::checkWritableVar(), MooseBaseParameterInterface::connectControllableParams(), Coupleable::Coupleable(), MortarData::createMortarInterface(), EigenProblem::doFreeNonlinearPowerIterations(), Terminator::execute(), FEProblemSolve::FEProblemSolve(), SolutionInvalidInterface::flagInvalidSolutionInternal(), MaterialPropertyInterface::MaterialPropertyInterface(), MooseVariableDataFV< OutputType >::MooseVariableDataFV(), ProgressOutput::output(), MooseBaseParameterInterface::paramError(), PetscOutputInterface::petscLinearOutput(), PetscOutputInterface::petscNonlinearOutput(), PetscOutputInterface::PetscOutputInterface(), PostprocessorInterface::postprocessorsAdded(), MultiApp::preTransfer(), Reporter::Reporter(), ReporterInterface::reportersAdded(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
getParam() [1/2]
template<typename T > const T & MooseBaseParameterInterface::getParam (const std::string & name) const inherited
Retrieve a parameter for the object.
Parameters
name The name of the parameter
Returns
The value of the parameter
Definition at line 200 of file MooseBaseParameterInterface.h.
{
  return InputParameters::getParamHelper(name, _pars, static_cast<T *>(0));
}
Referenced by AddGeneralReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddPeriodicBCAction::act(), CreateDisplacedProblemAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), ConstraintWarehouse::addObject(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), ADNodalKernel::ADNodalKernel(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), PiecewiseTabularBase::buildFromJSON(), Console::Console(), FEProblemBase::createTagSolutions(), AccumulateReporter::declareLateValues(), DerivativeParsedMaterialTempl< is_ad >::DerivativeParsedMaterialTempl(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EigenKernel::EigenKernel(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), GenericConstantRankTwoTensorTempl< is_ad >::GenericConstantRankTwoTensorTempl(), MooseApp::getCheckpointDirectories(), ExecutorInterface::getExecutor(), AdvancedOutput::init(), IterationAdaptiveDT::init(), TimeSequenceStepper::init(), AttribThread::initFrom(), AttribSysNum::initFrom(), AttribResidualObject::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), Console::initialSetup(), IterationAdaptiveDT::limitDTToPostprocessorValue(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MortarConsumerInterface::MortarConsumerInterface(), NestedDivision::NestedDivision(), ConsoleUtils::outputExecutionInformation(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedMaterialTempl< is_ad >::ParsedMaterialTempl(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), ParsedODEKernel::ParsedODEKernel(), ParsedPostprocessor::ParsedPostprocessor(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), Moose::FV::setInterpolationMethod(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), TimePeriod::TimePeriod(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), VariableCondensationPreconditioner(), and VectorOfPostprocessors::VectorOfPostprocessors().
getParam() [2/2]
template<typename T1 , typename T2 > std::vector< std::pair< T1, T2 > > MooseBaseParameterInterface::getParam (const std::string & param1, const std::string & param2) const inherited
Retrieve two parameters and provide pair of parameters for the object.
Parameters
param1 The name of first parameter
param2 The name of second parameter
Returns
Vector of pairs of first and second parameters
Definition at line 257 of file MooseBaseParameterInterface.h.
{
  return _pars.get<T1, T2>(param1, param2);
}
getRenamedParam()
template<typename T > const T & MooseBaseParameterInterface::getRenamedParam (const std::string & old_name, const std::string & new_name) const inherited
Retrieve a renamed parameter for the object.
This helper makes sure we check both names before erroring, and that only one parameter is passed to avoid silent errors
Parameters
old_name the old name for the parameter
new_name the new name for the parameter
Definition at line 207 of file MooseBaseParameterInterface.h.
{
  // this enables having a default on the new parameter but bypassing it with the old one
  // Most important: accept new parameter
  if (isParamSetByUser(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Second most: accept old parameter
  else if (isParamValid(old_name) && !isParamSetByUser(new_name))
    return InputParameters::getParamHelper(old_name, _pars, static_cast<T *>(0));
  // Third most: accept default for new parameter
  else if (isParamValid(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Refuse: no default, no value passed
  else if (!isParamValid(old_name) && !isParamValid(new_name))
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' is being retrieved without being set.\n"
               "Did you misspell it?");
  // Refuse: both old and new parameters set by user
  else
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' may not be provided alongside former parameter '" + old_name + "'");
}
getRestartableData()
template<typename T , typename... Args> const T & Restartable::getRestartableData (const std::string & data_name) const protected inherited
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
Forwarded arguments are not allowed in this case because we assume that the object is restarted and we won't need different constructors to initialize it.
NOTE: This returns a const reference! Make sure you store it in a const reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
Definition at line 287 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, nullptr).get();
}
init()
void VariableCondensationPreconditioner::init () virtual
Initialize data structures if not done so already.
Definition at line 331 of file VariableCondensationPreconditioner.C.
{
  TIME_SECTION(_init_timer);
  if (!_preconditioner)
    _preconditioner =
        Preconditioner<Number>::build_preconditioner(MoosePreconditioner::_communicator);
  _is_initialized = true;
}
isParamSetByUser()
bool MooseBaseParameterInterface::isParamSetByUser (const std::string & nm) const inline inherited
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
Parameters
nm The name of the parameter to test
Definition at line 108 of file MooseBaseParameterInterface.h.
{ return _pars.isParamSetByUser(nm); }
Referenced by SetAdaptivityOptionsAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), LibtorchNeuralNetControl::conditionalParameterError(), MooseBaseParameterInterface::getRenamedParam(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), PiecewiseTabularBase::PiecewiseTabularBase(), MooseMesh::prepare(), and SolutionUserObject::readXda().
isParamValid()
bool MooseBaseParameterInterface::isParamValid (const std::string & name) const inline inherited
Test if the supplied parameter is valid.
Parameters
name The name of the parameter to test
Definition at line 102 of file MooseBaseParameterInterface.h.
{ return _pars.isParamValid(name); }
Referenced by AddDriftDiffusionAction::act(), AddSpecies::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CopyNodalVarsAction::act(), CreateDisplacedProblemAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), AddGeneralReactions::AddGeneralReactions(), AddZapdosReactions::AddZapdosReactions(), AdvectiveFluxAux::AdvectiveFluxAux(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), GeneratedMesh::buildMesh(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), ChemicalReactionsBase::ChemicalReactionsBase(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), CombinerGenerator::CombinerGenerator(), CSVReader::CSVReader(), ConstantReporter::declareConstantReporterValues(), DGKernelBase::DGKernelBase(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EEDFEnergyTownsendLog::EEDFEnergyTownsendLog(), Eigenvalue::Eigenvalue(), ElectronEnergyTermRate::ElectronEnergyTermRate(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), PIDTransientControl::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FileOutput::FileOutput(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FunctionDT::FunctionDT(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getRenamedParam(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), Terminator::handleMessage(), HeavySpeciesTempl< is_ad >::HeavySpeciesTempl(), HFEMDirichletBC::HFEMDirichletBC(), EigenExecutionerBase::init(), Eigenvalue::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), MooseParsedFunction::initialSetup(), MooseParsedGradFunction::initialSetup(), MooseParsedVectorFunction::initialSetup(), PiecewiseTabularBase::initialSetup(), SolutionFunction::initialSetup(), Console::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), IterationAdaptiveDT::IterationAdaptiveDT(), LeastSquaresFit::LeastSquaresFit(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MatCoupledForce::MatCoupledForce(), MooseMesh::MooseMesh(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarConsumerInterface::MortarConsumerInterface(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalExtremeValue::NodalExtremeValue(), EigenExecutionerBase::normalizeSolution(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PetscOutput::PetscOutput(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), PicardSolve::PicardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseTabularBase::PiecewiseTabularBase(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), MooseMesh::prepare(), MultiApp::readCommandLineArguments(), SolutionUserObject::readExodusII(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), MooseMesh::setCoordSystem(), FileOutput::setFileBase(), FileOutput::setFileBaseInternal(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SideDiffusiveFluxIntegralTempl< is_ad, T >::SideDiffusiveFluxIntegralTempl(), SideExtremeValue::SideExtremeValue(), SolutionUserObject::SolutionUserObject(), Terminator::Terminator(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), MultiAppDofCopyTransfer::transfer(), TransformGenerator::TransformGenerator(), VariableCondensationPreconditioner(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
mergeArrays()
void VariableCondensationPreconditioner::mergeArrays (const PetscInt * a, const PetscInt * b, const PetscInt & na, const PetscInt & nb, std::vector< PetscInt > & c) private
Find the common part of arrays a and b and save it in c.
The na and nb are the number of entries for the arrays. This function is used in the preallocateCondensedJacobian step.
Definition at line 574 of file VariableCondensationPreconditioner.C.
{
  c.clear();
  // use map to store unique elements.
  std::map<PetscInt, bool> mp;
  // Inserting values to a map.
  for (const auto & i : make_range(na))
    mp[a[i]] = true;
  for (const auto & i : make_range(nb))
    mp[b[i]] = true;
  // Save the merged values to c, if only the value also exist in gcols
  for (const auto & i : mp)
    c.push_back(i.first);
}
Referenced by preallocateCondensedJacobian().
mooseDeprecated()
template<typename... Args> void MooseBaseErrorInterface::mooseDeprecated (Args &&... args) const inline inherited
Definition at line 78 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseDeprecatedStream(_console, false, true, std::forward<Args>(args)...);
  }
Referenced by FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::advanceMultiApps(), MultiApp::appProblem(), Executioner::augmentedPicardConvergenceCheck(), MooseMesh::buildSideList(), FEProblemBase::computeResidual(), AddVariableAction::determineType(), Eigenvalue::Eigenvalue(), MooseMesh::elem(), FunctionDT::FunctionDT(), RandomICBase::generateRandom(), MooseMesh::getBoundariesToElems(), Control::getExecuteOptions(), FEProblemBase::getNonlinearSystem(), FEProblemBase::getUserObjects(), FEProblemBase::hasPostprocessor(), MooseMesh::node(), FixedPointSolve::numPicardIts(), RelationshipManager::operator>=(), Executioner::picardSolve(), and MooseMesh::setBoundaryToNormalMap().
mooseError()
template<typename... Args> void MooseBaseErrorInterface::mooseError (Args &&... args) const inline inherited
Emits an error prefixed with object name and type.
Definition at line 38 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, errorPrefix("error"), std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
Referenced by HierarchicalGridPartitioner::_do_partition(), PetscExternalPartitioner::_do_partition(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AdaptivityAction::act(), AddFVICAction::act(), AddICAction::act(), AddMeshGeneratorAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVectorPostprocessorAction::act(), CheckFVBCAction::act(), CheckIntegrityAction::act(), CommonOutputAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DeprecatedBlockAction::act(), InitProblemAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetAdaptivityOptionsAction::act(), SetupMeshAction::act(), SetupMeshCompleteAction::act(), SetupPredictorAction::act(), SetupTimeStepperAction::act(), SplitMeshAction::act(), FEProblemBase::adaptMesh(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::addConstraint(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFVInitialCondition(), AddGeneralReactions::AddGeneralReactions(), FEProblemBase::addInitialCondition(), FEProblemBase::addLineSearch(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addOutput(), SubProblem::addPiecewiseByBlockLambdaFunctor(), DistributedRectilinearMeshGenerator::addPoint(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), FEProblemBase::addPostprocessor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseMesh::addQuadratureNode(), FEProblemBase::addReporter(), AddVariableAction::addVariable(), FEProblemBase::addVectorPostprocessor(), SubProblem::addVectorTag(), AddZapdosReactions::AddZapdosReactions(), ADEEDFRateConstantTownsend::ADEEDFRateConstantTownsend(), ADGasElectronMoments::ADGasElectronMoments(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), MooseVariableScalar::adUDot(), Output::advancedExecuteOn(), AdvectiveFluxAux::AdvectiveFluxAux(), ADZapdosEEDFRateConstant::ADZapdosEEDFRateConstant(), MooseVariableBase::allDofIndices(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayConstantIC::ArrayConstantIC(), ArrayFunctionIC::ArrayFunctionIC(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), Function::average(), Axisymmetric2D3DSolutionFunction::Axisymmetric2D3DSolutionFunction(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), BoltzmannSolverScalar::BoltzmannSolverScalar(), BoundingValueElementDamper::BoundingValueElementDamper(), BoundingValueNodalDamper::BoundingValueNodalDamper(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), MooseMesh::buildCoarseningMap(), MultiApp::buildComm(), DistributedRectilinearMeshGenerator::buildCube(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), PiecewiseTabularBase::buildFromXY(), MooseMesh::buildLowerDMesh(), GeneratedMesh::buildMesh(), MeshGeneratorMesh::buildMesh(), SpiralAnnularMesh::buildMesh(), TiledMesh::buildMesh(), ImageMesh::buildMesh3D(), ImageMeshGenerator::buildMesh3D(), MooseMesh::buildRefinementMap(), MaterialBase::buildRequiredMaterials(), MooseMesh::buildSideList(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), UserObjectInterface::castUserObject(), EigenExecutionerBase::chebyshev(), SubProblem::checkBlockMatProps(), SubProblem::checkBoundaryMatProps(), MooseMesh::checkCoordinateSystems(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkDisplacementOrders(), FEProblemBase::checkDuplicatePostprocessorVariableNames(), MooseMesh::checkDuplicateSubdomainNames(), MaterialBase::checkExecutionStage(), MeshGenerator::checkGetMesh(), ReporterTransferInterface::checkHasReporterValue(), FEProblemBase::checkICRestartError(), EigenExecutionerBase::checkIntegrity(), Eigenvalue::checkIntegrity(), Steady::checkIntegrity(), ExplicitTimeIntegrator::checkLinearConvergence(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), PostprocessorInterface::checkParam(), FEProblemBase::checkProblemIntegrity(), Sampler::checkReinitStatus(), MaterialBase::checkStatefulSanity(), FEProblemBase::checkUserObjects(), MultiAppTransfer::checkVariable(), DomainUserObject::checkVariable(), ChemicalReactionsBase::ChemicalReactionsBase(), MooseMesh::clone(), LibmeshPartitioner::clone(), CombinerGenerator::CombinerGenerator(), ElementSubdomainModifier::complementMovingBoundaryID(), ElementSubdomainModifier::complementMovingBoundaryName(), MooseVariableFieldBase::componentName(), CompositeFunction::CompositeFunction(), NodalPatchRecovery::compute(), computeDInverseDiag(), CompositionDT::computeDT(), MooseVariableFieldBase::computeFaceValues(), TimeStepper::computeFailedDT(), IterationAdaptiveDT::computeFailedDT(), TimeSequenceStepperBase::computeFailedDT(), MooseMesh::computeFiniteVolumeCoords(), FVFluxKernel::computeJacobian(), ArrayKernel::computeJacobian(), ArrayKernel::computeOffDiagJacobian(), FVElementalKernel::computeOffDiagJacobian(), MaterialBase::computeProperties(), ScalarKernel::computeQpJacobian(), ScalarKernel::computeQpResidual(), FVFluxKernel::computeResidual(), ArrayKernel::computeResidual(), FVFluxBC::computeResidual(), ResidualObject::computeResidualAndJacobian(), FVFluxKernel::computeResidualAndJacobian(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualL2Norm(), FEProblemBase::computeResidualTag(), FEProblemBase::computeResidualType(), TimeStepper::computeStep(), ActuallyExplicitEuler::computeTimeDerivatives(), AStableDirk4::computeTimeDerivatives(), BDF2::computeTimeDerivatives(), CrankNicolson::computeTimeDerivatives(), ExplicitEuler::computeTimeDerivatives(), ExplicitRK2::computeTimeDerivatives(), ExplicitTVDRK2::computeTimeDerivatives(), ImplicitEuler::computeTimeDerivatives(), ImplicitMidpoint::computeTimeDerivatives(), LStableDirk2::computeTimeDerivatives(), LStableDirk3::computeTimeDerivatives(), LStableDirk4::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), FEProblemBase::computeUserObjectsInternal(), BolsigValueScalar::computeValue(), PenetrationAux::computeValue(), BuildArrayVariableAux::computeValue(), TagVectorArrayVariableAux::computeValue(), ConcentricCircleMesh::ConcentricCircleMesh(), ConditionalEnableControl::ConditionalEnableControl(), TimeStepper::constrainStep(), LibtorchNeuralNetControl::controlNeuralNet(), AddVariableAction::createInitialConditionAction(), DataRead::DataRead(), ReporterTransferInterface::declareClone(), MeshGenerator::declareMeshProperty(), ReporterTransferInterface::declareVectorClone(), FunctorRelationshipManager::delete_remote_elements(), MooseMesh::deleteRemoteElements(), BicubicSplineFunction::derivative(), MooseMesh::detectPairedSidesets(), FEProblemBase::determineNonlinearSystem(), MeshDiagnosticsGenerator::diagnosticsLog(), DiffusionRateTemp::DiffusionRateTemp(), FunctorBinnedValuesDivision::divisionIndex(), FunctorRelationshipManager::dofmap_reinit(), FEProblemBase::duplicateVariableCheck(), EEDFRateConstant::EEDFRateConstant(), EEDFRateConstantTownsend::EEDFRateConstantTownsend(), Eigenvalue::Eigenvalue(), ElectricField::ElectricField(), ElectronMobility::ElectronMobility(), ElementIntegerAux::ElementIntegerAux(), ElementQualityAux::ElementQualityAux(), ElementUOAux::ElementUOAux(), DistributedRectilinearMeshGenerator::elemId(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), MooseMesh::errorIfDistributedMesh(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), BoltzmannSolverScalar::execute(), Eigenvalue::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), ElementQualityChecker::execute(), DiscreteElementUserObject::execute(), DomainUserObject::execute(), FEProblemBase::execute(), FEProblemBase::executeControls(), MultiAppVectorPostprocessorTransfer::executeFromMultiapp(), MultiAppVectorPostprocessorTransfer::executeToMultiapp(), ExplicitSSPRungeKutta::ExplicitSSPRungeKutta(), FileOutput::FileOutput(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), ElementQualityChecker::finalize(), VerifyElementUniqueID::finalize(), VerifyNodalUniqueID::finalize(), DiscreteElementUserObject::finalize(), Transfer::find_sys(), BreakMeshByBlockGeneratorBase::findFreeBoundaryId(), FunctionDT::FunctionDT(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), GapValueAux::GapValueAux(), Gas::Gas(), GasBase::GasBase(), GasElectronMoments::GasElectronMoments(), AllSideSetsByNormalsGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundingBoxNodeSetGenerator::generate(), BreakMeshByBlockGenerator::generate(), CombinerGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshCollectionGenerator::generate(), MeshDiagnosticsGenerator::generate(), MeshExtruderGenerator::generate(), MeshRepairGenerator::generate(), MoveNodeGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), SideSetsFromNormalsGenerator::generate(), SideSetsFromPointsGenerator::generate(), SmoothMeshGenerator::generate(), SpiralAnnularMeshGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), TiledMeshGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GeneratedMesh::GeneratedMesh(), GeneratedMeshGenerator::GeneratedMeshGenerator(), MeshGenerator::generateInternal(), CircularBoundaryCorrectionGenerator::generateRadialCorrectionFactor(), RandomICBase::generateRandom(), GenericConstantMaterialTempl< is_ad >::GenericConstantMaterialTempl(), GenericConstantVectorMaterialTempl< is_ad >::GenericConstantVectorMaterialTempl(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), DisplacedProblem::getActualFieldVariable(), FEProblemBase::getActualFieldVariable(), DisplacedProblem::getArrayVariable(), FEProblemBase::getArrayVariable(), MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::getBlockConnectedBlocks(), VariableOldValueBoundsAux::getBound(), MooseMesh::getBoundaryID(), MultiApp::getBoundingBox(), MooseMesh::getCoarseningMap(), MooseVariableBase::getContinuity(), Control::getControllableParameterByName(), MooseMesh::getCoordSystem(), PropertyReadFile::getData(), TransfiniteMeshGenerator::getDiscreteEdge(), FEProblemBase::getDistribution(), MooseVariableBase::getDofIndices(), getDofToCondense(), TransfiniteMeshGenerator::getEdge(), GhostingUserObject::getElementalValue(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), PropertyReadFile::getElementData(), MooseMesh::getElementIDIndex(), Material::getElementIDNeighbor(), Material::getElementIDNeighborByName(), MooseMesh::getElemIDMapping(), MooseMesh::getElemIDsOnBlocks(), MultiAppFieldTransfer::getEquationSystem(), MultiApp::getExecutioner(), MultiAppTransfer::getFromMultiApp(), MultiAppTransfer::getFromMultiAppInfo(), FEProblemBase::getFunction(), SubProblem::getFunctor(), MooseMesh::getGeneralAxisymmetricCoordAxis(), DistributedRectilinearMeshGenerator::getGhostNeighbors(), BatchMaterial< Tuple, Output, Input >::getIndex(), DistributedRectilinearMeshGenerator::getIndices(), SolutionUserObject::getLocalVarIndex(), Material::getMaterialByName(), FEProblemBase::getMaterialData(), SubProblem::getMatrixTagID(), AnnularMesh::getMaxInDimension(), GeneratedMesh::getMaxInDimension(), FEProblemBase::getMaxQps(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), AnnularMesh::getMinInDimension(), GeneratedMesh::getMinInDimension(), MultiAppTransfer::getMultiApp(), DistributedRectilinearMeshGenerator::getNeighbors(), MooseMesh::getNodeBlockIds(), PropertyReadFile::getNodeData(), MooseMesh::getNodeList(), FEProblemBase::getNonlinearSystem(), MooseMesh::getPairedBoundaryMapping(), ImageMesh::GetPixelInfo(), ImageMeshGenerator::GetPixelInfo(), PlaneIDMeshGenerator::getPlaneID(), FEProblemBase::getPositionsObject(), PostprocessorInterface::getPostprocessorValueByNameInternal(), MooseMesh::getRefinementMap(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), FEProblemBase::getSampler(), JSONFileReader::getScalar(), DisplacedProblem::getScalarVariable(), FEProblemBase::getScalarVariable(), DisplacedProblem::getStandardVariable(), FEProblemBase::getStandardVariable(), MooseMesh::getSubdomainBoundaryIds(), DisplacedProblem::getSystem(), FEProblemBase::getSystem(), FEProblemBase::getTimeFromStateArg(), Transient::getTimeIntegratorName(), MultiAppTransfer::getToMultiApp(), MultiAppTransfer::getToMultiAppInfo(), MooseMesh::getUniqueCoordSystem(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::getUserObjectName(), JSONFileReader::getVector(), VectorPostprocessorInterface::getVectorPostprocessorName(), SubProblem::getVectorTag(), SubProblem::getVectorTagID(), DisplacedProblem::getVectorVariable(), FEProblemBase::getVectorVariable(), GhostingAux::GhostingAux(), MultiApp::globalAppToLocal(), Function::gradient(), MooseParsedVectorFunction::gradient(), Terminator::handleMessage(), MooseVariableBase::hasDoFsOnNodes(), PostprocessorInterface::hasPostprocessor(), PostprocessorInterface::hasPostprocessorByName(), ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), AddVariableAction::init(), MooseMesh::init(), Sampler::init(), AddAuxVariableAction::init(), EigenExecutionerBase::init(), Eigenvalue::init(), Transient::init(), FEProblemBase::init(), CrankNicolson::init(), ExplicitTimeIntegrator::init(), CSVTimeSequenceStepper::init(), IterationAdaptiveDT::init(), MultiApp::init(), FEProblemBase::initialAdaptMesh(), BoltzmannSolverScalar::initialize(), PolynomialCoefficients::initialize(), CartesianGridDivision::initialize(), CylindricalGridDivision::initialize(), NestedDivision::initialize(), SphericalGridDivision::initialize(), SubProblem::initialSetup(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), Axisymmetric2D3DSolutionFunction::initialSetup(), MooseParsedFunction::initialSetup(), SolutionFunction::initialSetup(), SolutionIC::initialSetup(), FullSolveMultiApp::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), SolutionUserObject::initialSetup(), Function::integral(), InterpolatedCoefficientLinear::InterpolatedCoefficientLinear(), InterpolatedCoefficientSpline::InterpolatedCoefficientSpline(), EigenExecutionerBase::inversePowerIteration(), InversePowerMethod::InversePowerMethod(), Sampler::isAdaptiveSamplingCompleted(), MooseMesh::isBoundaryFullyExternalToSubdomains(), MooseVariableBase::isNodal(), IterationAdaptiveDT::IterationAdaptiveDT(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LineSearch::lineSearch(), ReporterPointMarker::markerSetup(), Material::Material(), MaterialOutputAction::materialOutputHelper(), MaterialRealTensorValueAux::MaterialRealTensorValueAux(), MaterialRealVectorValueAuxTempl< is_ad >::MaterialRealVectorValueAuxTempl(), Distribution::median(), FunctorRelationshipManager::mesh_reinit(), SubProblem::meshChanged(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshExtruderGenerator::MeshExtruderGenerator(), MeshRepairGenerator::MeshRepairGenerator(), SetupMeshAction::modifyParamsForUseSplit(), MeshMetaDataInterface::mooseErrorInternal(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MoveNodeGenerator::MoveNodeGenerator(), ElementSubdomainModifier::movingBoundaryID(), ElementSubdomainModifier::movingBoundaryName(), MultiApp::MultiApp(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NearestNodeDistanceAux::NearestNodeDistanceAux(), NearestNodeValueAux::NearestNodeValueAux(), FEProblemBase::needsPreviousNewtonIteration(), NewmarkBeta::NewmarkBeta(), NodalPatchRecoveryBase::nodalPatchRecovery(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), DistributedRectilinearMeshGenerator::nodeId(), DistributedRectilinearMeshGenerator::numNeighbors(), Output::onInterval(), FunctorRelationshipManager::operator()(), RelationshipManager::operator==(), MortarNodalGeometryOutput::output(), Output::Output(), DistributedRectilinearMeshGenerator::paritionSquarely(), PiecewiseBilinear::parse(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), ExplicitTimeIntegrator::performExplicitSolve(), PetscExternalPartitioner::PetscExternalPartitioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), Executioner::picardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseMulticonstant::PiecewiseMulticonstant(), PiecewiseTabularBase::PiecewiseTabularBase(), SolutionUserObject::pointValueGradientWrapper(), SolutionUserObject::pointValueWrapper(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName(), AStableDirk4::postResidual(), ExplicitRK2::postResidual(), ExplicitTVDRK2::postResidual(), ImplicitMidpoint::postResidual(), LStableDirk2::postResidual(), LStableDirk3::postResidual(), LStableDirk4::postResidual(), preallocateCondensedJacobian(), Predictor::Predictor(), Transient::preExecute(), MooseMesh::prepare(), MooseMesh::prepared(), FixedPointSolve::printFixedPointConvergenceReason(), RateCoefficientProvider::RateCoefficientProvider(), RateCoefficientProvider::reaction_coefficient(), RateCoefficientProvider::reaction_coefficient_derivative(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readExodusII(), SolutionUserObject::readXda(), FunctorRelationshipManager::redistribute(), Sampler::reinit(), RinglebMesh::RinglebMesh(), RinglebMeshGenerator::RinglebMeshGenerator(), PiecewiseMultiInterpolation::sample(), ScalarComponentIC::ScalarComponentIC(), ScalarLinearInterpolation::ScalarLinearInterpolation(), ScalarSplineInterpolation::ScalarSplineInterpolation(), DistributedRectilinearMeshGenerator::scaleNodalPositions(), BicubicSplineFunction::secondDerivative(), FunctorRelationshipManager::set_mesh(), MooseVariableBase::setActiveTags(), DistributedRectilinearMeshGenerator::setBoundaryNames(), MooseMesh::setCoordSystem(), FEProblemBase::setCoupling(), PiecewiseBase::setData(), FileOutput::setFileBaseInternal(), MooseMesh::setGeneralAxisymmetricCoordAxes(), FEProblemSolve::setInnerSolve(), MeshGenerator::setMeshProperty(), FEProblemBase::setNonlocalCouplingMatrix(), Sampler::setNumberOfCols(), Sampler::setNumberOfRandomSeeds(), Sampler::setNumberOfRows(), Split::setup(), TransientMultiApp::setupApp(), SetupMeshAction::setupMesh(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), TimePeriodBase::setupTimes(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SideSetsFromNormalsGenerator::SideSetsFromNormalsGenerator(), SideSetsFromPointsGenerator::SideSetsFromPointsGenerator(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), SolutionTimeAdaptiveDT::SolutionTimeAdaptiveDT(), SolutionUserObject::SolutionUserObject(), FullSolveMultiApp::solveStep(), UserObject::spatialPoints(), UserObject::spatialValue(), SpiralAnnularMesh::SpiralAnnularMesh(), SpiralAnnularMeshGenerator::SpiralAnnularMeshGenerator(), StitchedMesh::StitchedMesh(), MaterialBase::subdomainSetup(), GeneralUserObject::subdomainSetup(), NodalUserObject::subdomainSetup(), Constraint::subdomainSetup(), SuperelasticReactionRate::SuperelasticReactionRate(), FEProblemBase::swapBackMaterialsNeighbor(), Terminator::Terminator(), GeneralUserObject::threadJoin(), ThreadedGeneralUserObject::threadJoin(), DiscreteElementUserObject::threadJoin(), TimePeriodBase::TimePeriodBase(), VectorPostprocessorVisualizationAux::timestepSetup(), FEProblemBase::trustUserCouplingMatrix(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), FEProblemBase::uDotDotOldRequested(), MooseVariableScalar::uDotOld(), FEProblemBase::uDotOldRequested(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), SolutionUserObject::updateExodusBracketingTimeIndices(), FEProblemBase::updateMaxQps(), BoundingBoxIC::value(), Function::value(), Axisymmetric2D3DSolutionFunction::value(), PiecewiseConstantFromCSV::value(), ValueProvider::ValueProvider(), ValueRangeMarker::ValueRangeMarker(), ValueThresholdMarker::ValueThresholdMarker(), VariableCondensationPreconditioner(), MultiAppTransfer::variableIntegrityCheck(), VariableTimeIntegrationAux::VariableTimeIntegrationAux(), AddVariableAction::variableType(), Function::vectorCurl(), SubProblem::vectorTagName(), SubProblem::vectorTagType(), Function::vectorValue(), MooseParsedFunction::vectorValue(), MooseParsedGradFunction::vectorValue(), SubProblem::verifyVectorTags(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
mooseErrorNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseErrorNonPrefixed (Args &&... args) const inline inherited
Emits an error without the prefixing included in mooseError().
Definition at line 50 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
mooseInfo()
template<typename... Args> void MooseBaseErrorInterface::mooseInfo (Args &&... args) const inline inherited
Definition at line 84 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseInfoStream(_console, std::forward<Args>(args)...);
  }
Referenced by AddZapdosReactions::act(), SetupRecoverFileBaseAction::act(), AStableDirk4::AStableDirk4(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), BoltzmannSolverScalar::execute(), ExplicitRK2::ExplicitRK2(), ExplicitTVDRK2::ExplicitTVDRK2(), MultiAppTransfer::getPointInTargetAppFrame(), ImplicitMidpoint::ImplicitMidpoint(), InversePowerMethod::InversePowerMethod(), LStableDirk2::LStableDirk2(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), NonlinearEigen::NonlinearEigen(), ProjectionAux::ProjectionAux(), FEProblemBase::setRestartFile(), and SymmetryTransformGenerator::SymmetryTransformGenerator().
mooseWarning()
template<typename... Args> void MooseBaseErrorInterface::mooseWarning (Args &&... args) const inline inherited
Emits a warning prefixed with object name and type.
Definition at line 62 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(
        _console, errorPrefix("warning"), std::forward<Args>(args)...);
  }
Referenced by AddFunctionAction::act(), AddKernelAction::act(), CommonOutputAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupMeshAction::act(), DumpObjectsProblem::addAuxVariable(), DiracKernelBase::addPoint(), BoundaryMarker::BoundaryMarker(), BoundsAuxBase::BoundsAuxBase(), DistributedRectilinearMeshGenerator::buildCube(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), CartesianMeshGenerator::CartesianMeshGenerator(), CheckOutputAction::checkConsoleOutput(), MultiAppTransfer::checkMultiAppExecuteOn(), GapValueAux::computeValue(), MeshDiagnosticsGenerator::diagnosticsLog(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), Postprocessor::evaluateDotWarning(), ElementQualityChecker::finalize(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FixedPointSolve::FixedPointSolve(), ElementSubdomainIDGenerator::generate(), ParsedGenerateSideset::generate(), MultiAppTransfer::getAppInfo(), FunctorBinnedValuesDivision::getBinIndex(), FEProblemBase::getMaterial(), Terminator::handleMessage(), MaterialBase::initStatefulProperties(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::mesh(), NewmarkBeta::NewmarkBeta(), NodalPatchRecovery::NodalPatchRecovery(), Output::Output(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), Executioner::problem(), PropertyReadFile::readData(), TestSourceStepper::rejectStep(), MaterialBase::resetQpProperties(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setCoordSystem(), FEProblemBase::sizeZeroes(), TransientMultiApp::solveStep(), TimeDerivativeAux::TimeDerivativeAux(), PiecewiseConstantFromCSV::value(), and VariableCondensationPreconditioner().
mooseWarningNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseWarningNonPrefixed (Args &&... args) const inline inherited
Emits a warning without the prefixing included in mooseWarning().
Definition at line 72 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(_console, std::forward<Args>(args)...);
  }
name()
virtual const std::string & MooseBase::name () const inline virtual inherited
Get the name of the class.
Returns
The name of the class
Reimplemented in MooseVariableBase.
Definition at line 47 of file MooseBase.h.
{ return _name; }
Referenced by HierarchicalGridPartitioner::_do_partition(), AdaptivityAction::act(), AddElementalFieldAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVariableAction::act(), CopyNodalVarsAction::act(), DeprecatedBlockAction::act(), DisplayGhostingAction::act(), MaterialOutputAction::act(), AddDriftDiffusionAction::addADKernels(), FEProblemBase::addAnyRedistributers(), Executioner::addAttributeReporter(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFunctorMaterial(), FunctorMaterial::addFunctorProperty(), FunctorMaterial::addFunctorPropertyByBlocks(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), ADDGKernel::ADDGKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), SubProblem::addPiecewiseByBlockLambdaFunctor(), FEProblemBase::addPostprocessor(), UserObject::addPostprocessorDependencyHelper(), InitialConditionBase::addPostprocessorDependencyHelper(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), UserObject::addUserObjectDependencyHelper(), AuxKernelTempl< ComputeValueType >::addUserObjectDependencyHelper(), InitialConditionBase::addUserObjectDependencyHelper(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), UserObject::addVectorPostprocessorDependencyHelper(), FVFluxKernel::adjustRMGhostLayers(), ADSurfaceCharge::ADSurfaceCharge(), Output::advancedExecuteOn(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayDGKernel::ArrayDGKernel(), ArrayParsedAux::ArrayParsedAux(), AStableDirk4::AStableDirk4(), Function::average(), MultiApp::backup(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), PiecewiseTabularBase::buildFromFile(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkICRestartError(), Damper::checkMinDamping(), Coupleable::checkWritableVar(), CompositeFunction::CompositeFunction(), MaterialBase::computeProperties(), FEProblemBase::computeUserObjectByName(), VectorPostprocessorVisualizationAux::computeValue(), MooseBaseParameterInterface::connectControllableParams(), BatchMaterial< Tuple, Output, Input >::construct(), MultiApp::createApp(), AddVariableAction::createInitialConditionAction(), MultiApp::createLocalApp(), MeshGeneratorSystem::createMeshGeneratorOrder(), MaterialBase::declareADProperty(), MeshGenerator::declareMeshesForSubByName(), MeshGenerator::declareNullMeshName(), MaterialBase::declareProperty(), DOFMapOutput::demangle(), DerivativeSumMaterialTempl< is_ad >::DerivativeSumMaterialTempl(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DomainUserObject::DomainUserObject(), DumpObjectsProblem::dumpObjectHelper(), EconomouDielectricBC::EconomouDielectricBC(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementValueSampler::ElementValueSampler(), MooseMesh::errorIfDistributedMesh(), MooseBaseErrorInterface::errorPrefix(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), PointValue::execute(), RestartableDataReporter::execute(), MultiAppNearestNodeTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), MultiApp::fillPositions(), PointSamplerBase::finalize(), FunctionDT::FunctionDT(), FVFunctionIC::functionName(), FunctionIC::functionName(), FunctorPositions::FunctorPositions(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), BoundaryDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), GeneratedMeshGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MeshGenerator::generateInternal(), InterfaceMaterial::getADMaterialProperty(), Material::getADMaterialProperty(), MultiAppTransfer::getAppInfo(), MultiApp::getBoundingBox(), Control::getControllableParameterByName(), Control::getControllableValue(), Control::getControllableValueByName(), UserObject::getDependObjects(), FEProblemBase::getDistribution(), DistributionInterface::getDistribution(), DistributionInterface::getDistributionByName(), AddZapdosReactions::getElectronImpactKernelName(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), MultiApp::getExecutioner(), FEProblemBase::getExecutor(), OutputWarehouse::getFileNumbers(), FEProblemBase::getFunction(), SubProblem::getFunctor(), AuxKernelTempl< ComputeValueType >::getGenericMaterialProperty(), NodalPatchRecovery::getGenericMaterialProperty(), InterfaceMaterial::getGenericMaterialProperty(), Material::getGenericMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialPropertyByName(), Material::getGenericOptionalMaterialProperty(), MaterialBase::getGenericZeroMaterialProperty(), BatchMaterial< Tuple, Output, Input >::getIndex(), AddZapdosReactions::getKernelName(), SolutionUserObject::getLocalVarIndex(), Marker::getMarkerValue(), Material::getMaterial(), FEProblemBase::getMaterial(), Material::getMaterialByName(), AuxKernelTempl< ComputeValueType >::getMaterialProperty(), NodalPatchRecovery::getMaterialProperty(), InterfaceMaterial::getMaterialProperty(), Material::getMaterialProperty(), SubProblem::getMaterialPropertyBlockNames(), SubProblem::getMaterialPropertyBoundaryNames(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOld(), NodalPatchRecovery::getMaterialPropertyOld(), InterfaceMaterial::getMaterialPropertyOld(), Material::getMaterialPropertyOld(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOlder(), NodalPatchRecovery::getMaterialPropertyOlder(), InterfaceMaterial::getMaterialPropertyOlder(), Material::getMaterialPropertyOlder(), MeshGenerator::getMesh(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshesByName(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MultiAppTransfer::getMultiApp(), InterfaceMaterial::getNeighborADMaterialProperty(), InterfaceMaterial::getNeighborMaterialProperty(), InterfaceMaterial::getNeighborMaterialPropertyOld(), InterfaceMaterial::getNeighborMaterialPropertyOlder(), Material::getOptionalADMaterialProperty(), Material::getOptionalMaterialProperty(), Material::getOptionalMaterialPropertyOld(), Material::getOptionalMaterialPropertyOlder(), FEProblemBase::getPositionsObject(), FEProblemBase::getPostprocessorValueByName(), AddReactions::getReactionKernelName(), ReporterData::getReporterInfo(), FEProblemBase::getSampler(), Transient::getTimeStepperName(), ProjectedStatefulMaterialStorageAction::getTypeEnum(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), Terminator::handleMessage(), FEProblemBase::hasFunction(), SubProblem::hasFunctor(), SubProblem::hasFunctorWithType(), AdvancedOutput::hasOutputHelper(), FEProblemBase::hasPostprocessor(), FEProblemBase::hasPostprocessorValueByName(), FEProblemBase::hasUserObject(), AdvancedOutput::init(), FEProblemBase::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), AttribName::initFrom(), NestedDivision::initialize(), SolutionScalarAux::initialSetup(), NodalVariableValue::initialSetup(), MultiAppProjectionTransfer::initialSetup(), SolutionUserObject::initialSetup(), AdvancedOutput::initOutputList(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MaterialBase::initStatefulProperties(), Function::integral(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), MeshGenerator::isChildMeshGenerator(), MeshGenerator::isNullMeshName(), MeshGenerator::isParentMeshGenerator(), LinearCombinationFunction::LinearCombinationFunction(), FEProblemBase::logAdd(), LymberopoulosElectronBC::LymberopoulosElectronBC(), Marker::Marker(), Material::Material(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), Distribution::median(), MemoryUsageReporter::MemoryUsageReporter(), MeshGenerator::meshPropertyPrefix(), MooseVariableInterface< T >::MooseVariableInterface(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), NeumannCircuitVoltageMoles_KV::NeumannCircuitVoltageMoles_KV(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), NodalValueSampler::NodalValueSampler(), MooseBaseParameterInterface::objectErrorPrefix(), MeshGenerator::Comparator::operator()(), DOFMapOutput::output(), ProgressOutput::output(), Output::Output(), AdvancedOutput::outputElementalVariables(), ConsoleUtils::outputExecutionInformation(), AdvancedOutput::outputInput(), AdvancedOutput::outputNodalVariables(), AdvancedOutput::outputPostprocessors(), Exodus::outputPostprocessors(), Nemesis::outputPostprocessors(), TableOutput::outputReporter(), AdvancedOutput::outputReporters(), AdvancedOutput::outputScalarVariables(), AdvancedOutput::outputSystemInformation(), AdvancedOutput::outputVectorPostprocessors(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedODEKernel::ParsedODEKernel(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PointVariableSamplerBase::PointVariableSamplerBase(), MultiApp::readCommandLineArguments(), Receiver::Receiver(), Executor::Result::record(), FEProblemBase::registerRandomInterface(), GlobalParamsAction::remove(), MaterialBase::resetQpProperties(), MultiApp::restore(), SakiyamaEnergySecondaryElectronBC::SakiyamaEnergySecondaryElectronBC(), SakiyamaSecondaryElectronBC::SakiyamaSecondaryElectronBC(), ScalarComponentIC::ScalarComponentIC(), SecondaryElectronBC::SecondaryElectronBC(), SecondaryElectronEnergyBC::SecondaryElectronEnergyBC(), MultiApp::setAppOutputFileBase(), MooseMesh::setBoundaryName(), Control::setControllableValue(), Control::setControllableValueByName(), GlobalParamsAction::setDoubleIndexParam(), OutputWarehouse::setFileNumbers(), GlobalParamsAction::setParam(), FEProblemBase::setPostprocessorValueByName(), GlobalParamsAction::setScalarParam(), MooseMesh::setSubdomainName(), GlobalParamsAction::setTripleIndexParam(), Split::setup(), TransientMultiApp::setupApp(), GlobalParamsAction::setVectorParam(), SideCurrent::SideCurrent(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SideValueSampler::SideValueSampler(), TransientMultiApp::solveStep(), UserObject::spatialValue(), StitchedMesh::StitchedMesh(), SubProblem::storeBoundaryDelayedCheckMatProp(), SubProblem::storeBoundaryMatPropName(), SubProblem::storeBoundaryZeroMatProp(), SubProblem::storeSubdomainDelayedCheckMatProp(), SubProblem::storeSubdomainMatPropName(), SubProblem::storeSubdomainZeroMatProp(), MaterialBase::subdomainSetup(), TaggingInterface::TaggingInterface(), VectorPostprocessorVisualizationAux::timestepSetup(), MultiAppDofCopyTransfer::transfer(), TransientMultiApp::TransientMultiApp(), MooseBase::typeAndName(), MooseBaseParameterInterface::uniqueParameterName(), UserObject::UserObject(), UserObjectInterface::userObjectName(), MultiAppTransfer::variableIntegrityCheck(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), AdvancedOutput::wantOutput(), Coupleable::writableCoupledValue(), and Coupleable::writableVariable().
objectErrorPrefix()
std::string MooseBaseParameterInterface::objectErrorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for an object.
Definition at line 58 of file MooseBaseParameterInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the class \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseParameterInterface::paramErrorMsg().
paramError()
template<typename... Args> void MooseBaseParameterInterface::paramError (const std::string & param, Args... args) const inherited
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseError - only printing a message using the given args.
Definition at line 233 of file MooseBaseParameterInterface.h.
{
  Moose::show_trace = false;
  std::string msg = paramErrorMsg(param, std::forward<Args>(args)...);
  callMooseErrorRaw(msg, &_moose_base->getMooseApp());
  Moose::show_trace = true;
}
Referenced by HierarchicalGridPartitioner::_do_partition(), SetupDebugAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), ADDGKernel::ADDGKernel(), ReporterPointSource::addPoints(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ADNodalKernel::ADNodalKernel(), ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), AdvectiveFluxAux::AdvectiveFluxAux(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), ArrayBodyForce::ArrayBodyForce(), ArrayDGKernel::ArrayDGKernel(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayDirichletBC::ArrayDirichletBC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), ArrayPenaltyDirichletBC::ArrayPenaltyDirichletBC(), ArrayVacuumBC::ArrayVacuumBC(), BlockDeletionGenerator::BlockDeletionGenerator(), BlockWeightedPartitioner::BlockWeightedPartitioner(), BoundsAuxBase::BoundsAuxBase(), BreakMeshByBlockGenerator::BreakMeshByBlockGenerator(), BuildArrayVariableAux::BuildArrayVariableAux(), PiecewiseTabularBase::buildFromFile(), CartesianGridDivision::CartesianGridDivision(), UserObjectInterface::castUserObject(), checkComponent(), MeshGenerator::checkGetMesh(), PostprocessorInterface::checkParam(), Coupleable::checkVar(), MultiAppTransfer::checkVariable(), CircularBoundaryCorrectionGenerator::CircularBoundaryCorrectionGenerator(), CircularBoundaryCorrectionGenerator::circularCenterCalculator(), MultiAppGeneralFieldTransfer::closestToPosition(), CombinerGenerator::CombinerGenerator(), CompositionDT::CompositionDT(), ConcentricCircleMeshGenerator::ConcentricCircleMeshGenerator(), LibtorchNeuralNetControl::conditionalParameterError(), ConstantVectorPostprocessor::ConstantVectorPostprocessor(), ContainsPointAux::ContainsPointAux(), CopyValueAux::CopyValueAux(), Coupleable::Coupleable(), CoupledForceTempl< is_ad >::CoupledForceTempl(), CoupledValueFunctionMaterialTempl< is_ad >::CoupledValueFunctionMaterialTempl(), MultiApp::createApp(), MeshGeneratorSystem::createMeshGenerator(), CylindricalGridDivision::CylindricalGridDivision(), ConstantReporter::declareConstantReporterValues(), AccumulateReporter::declareLateValues(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DGLowerDKernel::DGLowerDKernel(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementLengthAux::ElementLengthAux(), ElementLpNormAux::ElementLpNormAux(), ElementValueSampler::ElementValueSampler(), ReporterPointSource::errorCheck(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), ExtraElementIDAux::ExtraElementIDAux(), ExtraElementIntegerDivision::ExtraElementIntegerDivision(), FEProblemSolve::FEProblemSolve(), FillBetweenCurvesGenerator::FillBetweenCurvesGenerator(), FillBetweenSidesetsGenerator::FillBetweenSidesetsGenerator(), ReporterPointSource::fillPoint(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), InternalSideIndicator::finalize(), FixedPointSolve::FixedPointSolve(), ForcingFunctionAux::ForcingFunctionAux(), FunctionArrayAux::FunctionArrayAux(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorAux::FunctorAux(), FunctorBinnedValuesDivision::FunctorBinnedValuesDivision(), FunctorElementalGradientAuxTempl< is_ad >::FunctorElementalGradientAuxTempl(), FunctorPositions::FunctorPositions(), FunctorVectorElementalAuxTempl< is_ad >::FunctorVectorElementalAuxTempl(), FVFluxBC::FVFluxBC(), FVInterfaceKernel::FVInterfaceKernel(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), FVTwoVarContinuityConstraint::FVTwoVarContinuityConstraint(), AdvancedExtruderGenerator::generate(), BlockDeletionGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundaryDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), BreakMeshByBlockGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), CombinerGenerator::generate(), ExplodeMeshGenerator::generate(), ExtraNodesetGenerator::generate(), FillBetweenCurvesGenerator::generate(), FillBetweenSidesetsGenerator::generate(), GeneratedMeshGenerator::generate(), MeshCollectionGenerator::generate(), MeshExtruderGenerator::generate(), ParsedCurveGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), PropertyReadFile::getBlockData(), PropertyReadFile::getData(), Sampler::getGlobalSamples(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), Sampler::getLocalSamples(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), Sampler::getNextLocalRow(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectName(), HFEMDirichletBC::HFEMDirichletBC(), MultiApp::init(), BlockWeightedPartitioner::initialize(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), PiecewiseConstantFromCSV::initialSetup(), LibtorchControlValuePostprocessor::initialSetup(), ReferenceResidualProblem::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), HistogramVectorPostprocessor::initialSetup(), AddMetaDataGenerator::inputChecker(), IntegratedBC::IntegratedBC(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceValueUserObjectAux::InterfaceValueUserObjectAux(), InterpolatedStatefulMaterialTempl< T >::InterpolatedStatefulMaterialTempl(), InversePowerMethod::InversePowerMethod(), IterationAdaptiveDT::IterationAdaptiveDT(), MultiApp::keepSolutionDuringRestore(), Kernel::Kernel(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LinearCombinationFunction::LinearCombinationFunction(), LowerDIntegratedBC::LowerDIntegratedBC(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), MaterialADConverterTempl< T >::MaterialADConverterTempl(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), PatternedMeshGenerator::mergeSubdomainNameMaps(), MeshCollectionGenerator::MeshCollectionGenerator(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshDivisionAux::MeshDivisionAux(), MeshGenerator::MeshGenerator(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarNodalAuxKernelTempl< ComputeValueType >::MortarNodalAuxKernelTempl(), MultiApp::moveApp(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), NestedDivision::NestedDivision(), NodalBC::NodalBC(), NodalEqualValueConstraint::NodalEqualValueConstraint(), NodalKernel::NodalKernel(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), NodalValueSampler::NodalValueSampler(), Output::Output(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), PatchMeshGenerator::PatchMeshGenerator(), PatternedMeshGenerator::PatternedMeshGenerator(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), PeriodicSegmentalConstraint::PeriodicSegmentalConstraint(), PIDTransientControl::PIDTransientControl(), PlaneDeletionGenerator::PlaneDeletionGenerator(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), PolyLineMeshGenerator::PolyLineMeshGenerator(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), LibmeshPartitioner::prepareBlocksForSubdomainPartitioner(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), PropertyReadFile::PropertyReadFile(), RandomIC::RandomIC(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readXda(), ReferenceResidualProblem::ReferenceResidualProblem(), RefineBlockGenerator::RefineBlockGenerator(), RefineSidesetGenerator::RefineSidesetGenerator(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setPartitioner(), TimeSequenceStepperBase::setupSequence(), SingleRankPartitioner::SingleRankPartitioner(), SphericalGridDivision::SphericalGridDivision(), SymmetryTransformGenerator::SymmetryTransformGenerator(), Terminator::Terminator(), TimeDerivativeAux::TimeDerivativeAux(), Transfer::Transfer(), TransformGenerator::TransformGenerator(), TransientMultiApp::TransientMultiApp(), ParsedCurveGenerator::tSectionSpaceDefiner(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), UserObject::UserObject(), VariableCondensationPreconditioner(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), VolumeAux::VolumeAux(), XYDelaunayGenerator::XYDelaunayGenerator(), and XYMeshLineCutter::XYMeshLineCutter().
paramErrorMsg()
template<typename... Args> std::string MooseBaseParameterInterface::paramErrorMsg (const std::string & param, Args... args) const inline private inherited
Definition at line 171 of file MooseBaseParameterInterface.h.
  {
    auto param_prefix = paramErrorPrefix(_pars, param);
    // With no input location information, append object info (name + type)
    const std::string object_prefix =
        _pars.inputLocation(param).empty() ? objectErrorPrefix("parameter error") : "";
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    // Wrap error message to a separate line from param_prefix if it is about to
    // blow past 100 chars.  But only wrap if the param_prefix is long enough (12
    // chars) for the wrap to buy us much extra length. We don't check object_prefix
    // here because it will go before the parameter error
    if ((param_prefix.size() > 12 && msg.size() + param_prefix.size() > 99) ||
        msg.find("\n") != std::string::npos)
    {
      if (param_prefix.size() > 0 && param_prefix[param_prefix.size() - 1] != ':')
        param_prefix += ":";
      return object_prefix + param_prefix + "\n    " + MooseUtils::replaceAll(msg, "\n", "\n    ");
    }
    return object_prefix + param_prefix + " " + msg;
  }
Referenced by MooseBaseParameterInterface::paramError(), MooseBaseParameterInterface::paramInfo(), and MooseBaseParameterInterface::paramWarning().
parameters()
const InputParameters & MooseBaseParameterInterface::parameters () const inline inherited
Get the parameters of the object.
Returns
The parameters of the object
Definition at line 53 of file MooseBaseParameterInterface.h.
{ return _pars; }
Referenced by SetupDebugAction::act(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), FEProblemBase::addPostprocessor(), FEProblemBase::addPredictor(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), AdvancedOutput::AdvancedOutput(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), Moose::assemble_matrix(), AuxScalarKernel::AuxScalarKernel(), BoundsAuxBase::BoundsAuxBase(), MooseMesh::buildTypedMesh(), UserObjectInterface::castUserObject(), PostprocessorInterface::checkParam(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), Moose::compute_bounds(), Moose::compute_jacobian(), Moose::compute_nearnullspace(), Moose::compute_nullspace(), Moose::compute_postcheck(), Moose::compute_transpose_nullspace(), LibtorchNeuralNetControl::conditionalParameterError(), Console::Console(), MultiApp::createApp(), Postprocessor::declareValue(), DumpObjectsProblem::deduceNecessaryParameters(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), DumpObjectsProblem::dumpObjectHelper(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElectronsFromIonization::ElectronsFromIonization(), Executor::Executor(), Exodus::Exodus(), FEProblem::FEProblem(), FEProblemBase::FEProblemBase(), FixedPointSolve::FixedPointSolve(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GapValueAux::GapValueAux(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), MooseBaseParameterInterface::getCheckedPointerParam(), ExecutorInterface::getExecutor(), Material::getMaterial(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), UserObjectInterface::getUserObjectName(), VectorPostprocessorInterface::getVectorPostprocessorName(), GhostingUserObject::GhostingUserObject(), HphiRadialInterface::HphiRadialInterface(), AttribSystem::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), FullSolveMultiApp::initialSetup(), FEProblemBase::initNullSpaceVectors(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), isValid(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseAppCoordTransform::MooseAppCoordTransform(), MooseVariableInterface< T >::MooseVariableInterface(), MultiApp::MultiApp(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodeFaceConstraint::NodeFaceConstraint(), PatchMeshGenerator::PatchMeshGenerator(), PenetrationAux::PenetrationAux(), PicardSolve::PicardSolve(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), ProjectedStatefulMaterialStorageAction::processProperty(), MultiAppProjectionTransfer::projectSolution(), PropertyReadFile::PropertyReadFile(), PseudoTimestep::PseudoTimestep(), RandomIC::RandomIC(), InputParameterWarehouse::removeInputParameters(), OutputWarehouse::resetFileBase(), MooseAppCoordTransform::setCoordinateSystem(), FEProblemBase::setInputParametersFEProblem(), FEProblem::setInputParametersFEProblem(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SteffensenSolve::SteffensenSolve(), DumpObjectsProblem::stringifyParameters(), TaggingInterface::TaggingInterface(), Transfer::Transfer(), Transient::Transient(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
paramInfo()
template<typename... Args> void MooseBaseParameterInterface::paramInfo (const std::string & param, Args... args) const inherited
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseInfo - only printing a message using the given args.
Definition at line 250 of file MooseBaseParameterInterface.h.
{
  mooseInfo(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by TransientMultiApp::TransientMultiApp().
paramWarning()
template<typename... Args> void MooseBaseParameterInterface::paramWarning (const std::string & param, Args... args) const inherited
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseWarning - only printing a message using the given args.
Definition at line 243 of file MooseBaseParameterInterface.h.
{
  mooseWarning(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by MultiAppNearestNodeTransfer::execute(), FEProblemSolve::FEProblemSolve(), PlaneIDMeshGenerator::generate(), UniqueExtraIDMeshGenerator::generate(), Terminator::initialSetup(), and MooseMesh::MooseMesh().
perfGraph()
PerfGraph & PerfGraphInterface::perfGraph () inherited
Get the PerfGraph.
Definition at line 78 of file PerfGraphInterface.C.
{
  return _pg_moose_app.perfGraph();
}
Referenced by CommonOutputAction::act(), PerfGraphData::finalize(), and PerfGraphOutput::output().
preallocateCondensedJacobian()
void VariableCondensationPreconditioner::preallocateCondensedJacobian (PetscMatrix< Number > & condensed_mat, PetscMatrix< Number > & original_mat, const std::vector< dof_id_type > & rows, const std::vector< dof_id_type > & cols, const std::vector< dof_id_type > & grows, const std::vector< dof_id_type > & gcols, PetscMatrix< Number > & block_mat) private
Preallocate memory for the condensed Jacobian matrix.
Definition at line 483 of file VariableCondensationPreconditioner.C.
{
  // quantities from the original matrix and the block matrix
  PetscInt ncols = 0, block_ncols = 0;
  const PetscInt * col_vals;
  const PetscInt * block_col_vals;
  const PetscScalar * vals;
  const PetscScalar * block_vals;
  std::vector<PetscInt> block_cols_to_org; // stores the nonzero column indices of the block
                                           // matrix w.r.t original matrix
  std::vector<PetscInt>
      merged_cols; // stores the nonzero column indices estimate of the condensed matrix
  // number of nonzeros in each row of the DIAGONAL and OFF-DIAGONAL portion of the local
  // condensed matrix
  std::vector<dof_id_type> n_nz, n_oz;
  PetscErrorCode ierr = 0;
  // Get number of nonzeros from original_mat and block_mat for each row
  for (const auto & row_id : _rows)
  {
    // get number of non-zeros in the original matrix
    ierr = MatGetRow(original_mat.mat(), row_id, &ncols, &col_vals, &vals);
    LIBMESH_CHKERR(ierr);
    // get number of non-zeros in the block matrix
    dof_id_type block_row_id; // row id in the block matrix
    if (_global_rows_to_idx.find(row_id) != _global_rows_to_idx.end())
      block_row_id = _global_rows_to_idx[row_id];
    else
      mooseError("DoF ", row_id, " does not exist in the rows of condensed_mat");
    ierr = MatGetRow(block_mat.mat(), block_row_id, &block_ncols, &block_col_vals, &block_vals);
    LIBMESH_CHKERR(ierr);
    // make sure the block index is transformed in terms of the original mat
    block_cols_to_org.clear();
    for (PetscInt i = 0; i < block_ncols; ++i)
    {
      auto idx = gcols[block_col_vals[i]];
      block_cols_to_org.push_back(idx);
    }
    // Now store nonzero column indices for the condensed Jacobian
    // merge `col_vals` and `block_cols_to_org` and save the common indices in `merged_cols`.
    mergeArrays(col_vals, block_cols_to_org.data(), ncols, block_ncols, merged_cols);
    ierr = MatRestoreRow(block_mat.mat(), block_row_id, &block_ncols, &block_col_vals, &block_vals);
    LIBMESH_CHKERR(ierr);
    ierr = MatRestoreRow(original_mat.mat(), row_id, &ncols, &col_vals, &vals);
    LIBMESH_CHKERR(ierr);
    // Count the nnz for DIAGONAL and OFF-DIAGONAL parts
    PetscInt row_n_nz = 0, row_n_oz = 0;
    for (const auto & merged_col : merged_cols)
    {
      // find corresponding index in the block mat and skip the cols that do not exist in the
      // condensed system
      if (_global_cols_to_idx.find(merged_col) == _global_cols_to_idx.end())
        continue;
      dof_id_type col_idx = _global_cols_to_idx[merged_col];
      // find the corresponding row index
      dof_id_type row_idx = grows[col_idx];
      // check whether the index is local;
      // yes - DIAGONAL, no - OFF-DIAGONAL
      if (_rows_to_idx.find(row_idx) != _rows_to_idx.end())
        row_n_nz++;
      else
        row_n_oz++;
    }
    n_nz.push_back(cast_int<dof_id_type>(row_n_nz));
    n_oz.push_back(cast_int<dof_id_type>(row_n_oz));
  }
  // Then initialize and allocate memory for the condensed system matrix
  condensed_mat.init(grows.size(), gcols.size(), rows.size(), cols.size(), n_nz, n_oz);
}
Referenced by condenseSystem().
registerRestartableDataOnApp()
RestartableDataValue & Restartable::registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const private inherited
Helper function for actually registering the restartable data.
Definition at line 51 of file Restartable.C.
{
  return _restartable_app.registerRestartableData(
      std::move(data), tid, _restartable_read_only, _metaname);
}
Referenced by Restartable::declareRestartableDataHelper().
registerRestartableNameWithFilterOnApp()
void Restartable::registerRestartableNameWithFilterOnApp (const std::string & name, Moose::RESTARTABLE_FILTER filter) private inherited
Helper function for actually registering the restartable data.
Definition at line 59 of file Restartable.C.
{
  _restartable_app.registerRestartableNameWithFilter(name, filter);
}
Referenced by Restartable::declareRecoverableData().
registerTimedSection() [1/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
Returns
The ID of the section - use when starting timing
Definition at line 53 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(timed_section_name, level);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
registerTimedSection() [2/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level, const std::string & live_message, const bool print_dots = true) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
live_message The message to be printed to the screen during execution
print_dots Whether or not progress dots should be printed for this section
Returns
The ID of the section - use when starting timing
Definition at line 64 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(
        timedSectionName(section_name), level, live_message, print_dots);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
restartableName()
std::string Restartable::restartableName (const std::string & data_name) const protected inherited
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
This should only be used in this interface and in testing.
Definition at line 66 of file Restartable.C.
{
  return _restartable_system_name + "/" + _restartable_name + "/" + data_name;
}
Referenced by Restartable::declareRecoverableData(), and Restartable::declareRestartableDataHelper().
setCouplingMatrix()
void MoosePreconditioner::setCouplingMatrix (std::unique_ptr< CouplingMatrix > cm) protected inherited
Setup the coupling matrix on the finite element problem.
Definition at line 137 of file MoosePreconditioner.C.
{
  for (const auto i : make_range(_fe_problem.numNonlinearSystems()))
  {
    if (i == libMesh::cast_int<unsigned int>(_fe_problem.numNonlinearSystems() - 1))
      // This is the last nonlinear system, so it's safe now to move the object
      _fe_problem.setCouplingMatrix(std::move(cm), i);
    else
      _fe_problem.setCouplingMatrix(std::make_unique<CouplingMatrix>(*cm), i);
  }
}
Referenced by FieldSplitPreconditioner::FieldSplitPreconditioner(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), and VariableCondensationPreconditioner().
setup()
void VariableCondensationPreconditioner::setup () virtual
This is called every time the "operator might have changed".
This is essentially where you need to fill in your preconditioning matrix.
Definition at line 598 of file VariableCondensationPreconditioner.C.
{
  if (_adaptive_condensation)
    findZeroDiagonals(*_matrix, _zero_rows);
  // save dofs that are to be condensed out
  getDofToCondense();
  // solve the condensed system only when needed, otherwise solve the original system
  if (_need_condense)
  {
    // get condensed dofs for rows and cols
    getDofColRow();
    condenseSystem();
    // make sure diagonal entries are not empty
    for (const auto & i : make_range(_J_condensed->row_start(), _J_condensed->row_stop()))
      _J_condensed->add(i, i, 0.0);
    _J_condensed->close();
    _preconditioner->set_matrix(*_J_condensed);
  }
  else
    _preconditioner->set_matrix(*_matrix);
  _preconditioner->set_type(_pre_type);
  _preconditioner->init();
}
timedSectionName()
std::string PerfGraphInterface::timedSectionName (const std::string & section_name) const protected inherited
Returns
The name of the timed section with the name section_name.
Optionally adds a prefix if one is defined.
Definition at line 47 of file PerfGraphInterface.C.
{
  return _prefix.empty() ? "" : (_prefix + "::") + section_name;
}
Referenced by PerfGraphInterface::registerTimedSection().
type()
const std::string & MooseBase::type () const inline inherited
Get the type of this class.
Returns
the name of the type of this class
Definition at line 41 of file MooseBase.h.
{ return _type; }
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), CreateProblemDefaultAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetupDebugAction::act(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::addDistribution(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addObject(), DistributedRectilinearMeshGenerator::addPoint(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), PhysicsBasedPreconditioner::addSystem(), FEProblemBase::addTimeIntegrator(), SubProblem::addVectorTag(), DisplacedProblem::addVectorTag(), FEProblemBase::advanceMultiApps(), FEProblemBase::backupMultiApps(), BoundaryPreservedMarker::BoundaryPreservedMarker(), DistributedRectilinearMeshGenerator::buildCube(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildPRefinementAndCoarseningMaps(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), FEProblemBase::computeAuxiliaryKernels(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpJacobian(), HFEMDirichletBC::computeLowerDQpJacobian(), ArrayHFEMDiffusion::computeLowerDQpJacobian(), HFEMDiffusion::computeLowerDQpJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), FEProblemBase::computeMultiAppsDT(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), DGCoupledAdvection::computeOffDiagJacobianHelper(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ScalarKernel::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueBoundaryConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), LinearNodalConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), DGConvection::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), InterfaceDiffusion::computeQpJacobian(), InterfaceReaction::computeQpJacobian(), DGCoupledAdvection::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), DGFunctionTemperatureAdvection::computeQpJacobian(), DGTemperatureAdvection::computeQpJacobian(), InterTemperatureAdvection::computeQpJacobian(), CoupledTiedValueConstraint::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), HFEMTestJump::computeQpOffDiagJacobian(), HFEMTrialJump::computeQpOffDiagJacobian(), DGCoupledAdvection::computeQpOffDiagJacobian(), ScalarKernel::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), EqualValueBoundaryConstraint::computeQpResidual(), EqualValueEmbeddedConstraint::computeQpResidual(), LinearNodalConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), DGConvection::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), DGEFieldAdvection::computeQpResidual(), HphiRadialInterface::computeQpResidual(), InterfaceAdvection::computeQpResidual(), InterfaceLogDiffusionElectrons::computeQpResidual(), PotentialSurfaceCharge::computeQpResidual(), ADDGAdvection::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), HFEMDiffusion::computeQpResidual(), HFEMTestJump::computeQpResidual(), HFEMTrialJump::computeQpResidual(), InterfaceDiffusion::computeQpResidual(), InterfaceReaction::computeQpResidual(), DGCoupledAdvection::computeQpResidual(), DGFunctionConvection::computeQpResidual(), DGFunctionTemperatureAdvection::computeQpResidual(), DGTemperatureAdvection::computeQpResidual(), InterTemperatureAdvection::computeQpResidual(), ArrayDGDiffusion::computeQpResidual(), ArrayHFEMDiffusion::computeQpResidual(), FEProblemBase::computeUserObjectByName(), FEProblemBase::computeUserObjects(), FEProblemBase::computeUserObjectsInternal(), BatchMaterial< Tuple, Output, Input >::construct(), DisplacedProblem::createQRules(), FEProblemBase::createQRules(), MeshGenerator::declareMeshProperty(), DumpObjectsProblem::deduceNecessaryParameters(), DumpObjectsProblem::dumpObjectHelper(), FEProblemBase::duplicateVariableCheck(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), MooseBaseErrorInterface::errorPrefix(), AB2PredictorCorrector::estimateTimeError(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finishMultiAppStep(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), ElementSubdomainIDGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), PatternedMeshGenerator::generate(), MeshGenerator::generateInternal(), MultiAppTransfer::getAppInfo(), TransfiniteMeshGenerator::getEdge(), ElementGenerator::getElemType(), FEProblemBase::getMaterial(), FEProblemBase::getMaterialData(), MaterialOutputAction::getParams(), ReporterData::getReporterInfo(), Transient::getTimeIntegratorName(), FEProblemBase::getTransfers(), SubProblem::getVectorTags(), DisplacedProblem::getVectorTags(), CommonOutputAction::hasConsole(), FEProblemBase::hasMultiApps(), AdvancedOutput::hasOutput(), FEProblemBase::incrementMultiAppTStep(), AdvancedOutput::initAvailableLists(), FunctorPositions::initialize(), FunctorTimes::initialize(), MultiAppConservativeTransfer::initialSetup(), ArrayDGDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), RelationshipManager::isType(), FEProblemBase::logAdd(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), SubProblem::numVectorTags(), DisplacedProblem::numVectorTags(), MooseBaseParameterInterface::objectErrorPrefix(), AdvancedOutput::output(), Console::output(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), ProjectedStatefulMaterialStorageAction::processProperty(), SolutionInvalidInterface::registerInvalidSolutionInternal(), FEProblemBase::restoreMultiApps(), MeshRepairGenerator::separateSubdomainsByElementType(), FEProblemBase::setCoupling(), MooseBase::typeAndName(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), DisplacedProblem::updateGeomSearch(), FEProblemBase::updateGeomSearch(), UserObjectInterface::userObjectType(), and AdvancedOutput::wantOutput().
typeAndName()
std::string MooseBase::typeAndName () const inline inherited
Get the class's combined type and name; useful in error handling.
Returns
The type and name of this class in the form '<type()> "<name()>"'.
Definition at line 53 of file MooseBase.h.
  {
    return type() + std::string(" \"") + name() + std::string("\"");
  }
Referenced by ReporterContext< T >::finalize(), and ReporterData::getReporterInfo().
uniqueName()
MooseObjectName MooseBaseParameterInterface::uniqueName () const inline inherited
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
Definition at line 58 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectName(_pars.get<std::string>("_unique_name"));
  }
Referenced by MooseBaseParameterInterface::connectControllableParams(), and Action::uniqueActionName().
uniqueParameterName()
MooseObjectParameterName MooseBaseParameterInterface::uniqueParameterName (const std::string & parameter_name) const inline inherited
The unique parameter name of a valid parameter of this object for accessing parameter controls.
Definition at line 43 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectParameterName(
        _pars.get<std::string>("_moose_base"), _moose_base->name(), parameter_name);
  }
validParams()
InputParameters VariableCondensationPreconditioner::validParams () static
Definition at line 41 of file VariableCondensationPreconditioner.C.
{
  InputParameters params = MoosePreconditioner::validParams();
  params.addClassDescription(
      "Varialble condensation preconditioner (VCP) condenses out specified variable(s) "
      "from the Jacobian matrix and produces a system of equations with less unkowns to "
      "be solved by the underlying preconditioners.");
  params.addParam<std::vector<NonlinearVariableName>>(
      "coupled_groups",
      {},
      "List multiple space separated groups of comma separated variables. "
      "Off-diagonal jacobians will be generated for all pairs within a group.");
  params.addParam<bool>(
      "is_lm_coupling_diagonal",
      false,
      "Set to true if you are sure the coupling matrix between Lagrange multiplier variable and "
      "the coupled primal variable is strict diagonal. This will speedup the linear solve. "
      "Otherwise set to false to ensure linear solve accuracy.");
  params.addParam<bool>(
      "adaptive_condensation",
      true,
      "By default VCP will check the Jacobian and only condense the rows with zero diagonals. Set "
      "to false if you want to condense out all the specified variable dofs.");
  params.addRequiredParam<std::vector<std::string>>("preconditioner", "Preconditioner type.");
  params.addRequiredParam<std::vector<std::string>>(
      "lm_variable",
      "Name of the variable(s) that is to be condensed out. Usually "
      "this will be the Lagrange multiplier variable(s).");
  params.addRequiredParam<std::vector<std::string>>(
      "primary_variable",
      "Name of the variable(s) that couples with the variable(s) specified in the `variable` "
      "block. Usually this is the primary variable that the Lagrange multiplier correspond to.");
  return params;
}
Member Data Documentation
_action_factory
ActionFactory& MooseBaseParameterInterface::_action_factory protected inherited
Builds Actions.
Definition at line 164 of file MooseBaseParameterInterface.h.
Referenced by CommonOutputAction::create(), AddVariableAction::createInitialConditionAction(), AddSpecies::createInitialConditions(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
_adaptive_condensation
const bool VariableCondensationPreconditioner::_adaptive_condensation private
Whether to condense all specified variable.
Definition at line 153 of file VariableCondensationPreconditioner.h.
Referenced by getDofToCondense(), and setup().
_app
MooseApp& MooseBase::_app protected inherited
The MOOSE application this is associated with.
Definition at line 60 of file MooseBase.h.
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), MeshGenerator::addChildMeshGenerator(), FEProblemBase::addMaterialHelper(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addOutput(), MeshGenerator::addParentMeshGenerator(), FVFluxKernel::adjustRMGhostLayers(), FEProblemBase::allowOutput(), AStableDirk4::AStableDirk4(), FileMesh::buildMesh(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), MeshGenerator::checkGetMesh(), FEProblemBase::checkICRestartError(), FEProblemBase::checkNonlinearConvergence(), OversampleOutput::cloneMesh(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), Console::Console(), TimeStepper::constrainStep(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::createLocalApp(), FEProblemBase::customSetup(), MeshGenerator::declareMeshProperty(), MeshGenerator::declareNullMeshName(), MooseMesh::determineUseDistributedMesh(), DumpObjectsProblem::dumpObjectHelper(), DumpObjectsProblem::dumpVariableHelper(), EigenExecutionerBase::EigenExecutionerBase(), EigenKernel::EigenKernel(), PIDTransientControl::execute(), Eigenvalue::execute(), InversePowerMethod::execute(), NonlinearEigen::execute(), Steady::execute(), Transient::execute(), PseudoTimestep::execute(), IterationInfo::execute(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FileOutput::FileOutput(), ChangeOverFixedPointPostprocessor::finalize(), RadialAverage::finalize(), FixedPointSolve::FixedPointSolve(), FEProblemBase::forceOutput(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), SideSetsFromNormalsGenerator::generate(), MeshGenerator::generateInternal(), FEProblemBase::getExecutor(), MeshGenerator::getMeshByName(), NumFixedPointIterations::getValue(), NumRelationshipManagers::getValue(), GhostingUserObject::GhostingUserObject(), MooseMesh::init(), InversePowerMethod::init(), NonlinearEigen::init(), Transient::init(), FEProblemBase::init(), TimePeriod::initialSetup(), Console::initialSetup(), AdvancedOutput::initOutputList(), FEProblemBase::initPetscOutput(), EigenProblem::initPetscOutput(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MeshGenerator::MeshGenerator(), EigenExecutionerBase::normalizeSolution(), NumFailedTimeSteps::NumFailedTimeSteps(), AugmentSparsityOnInterface::operator()(), Checkpoint::output(), Exodus::output(), Nemesis::output(), PerfGraphOutput::output(), Tecplot::output(), MortarNodalGeometryOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Exodus::outputEmptyTimestep(), Console::outputInput(), Exodus::outputInput(), Exodus::outputNodalVariables(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), Console::outputSystemInformation(), JSONOutput::outputSystemInformation(), MultiApp::parentOutputPositionChanged(), PIDTransientControl::PIDTransientControl(), Transient::preExecute(), Eigenvalue::prepareSolverOptions(), FEProblemBase::projectSolution(), MultiApp::setAppOutputFileBase(), FileOutput::setFileBaseInternal(), MeshGenerator::setMeshProperty(), MeshGenerator::setMeshPropertyHelper(), FEProblemBase::setRestartFile(), TransientMultiApp::setupApp(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SolutionInvalidityReporter::SolutionInvalidityReporter(), FEProblemBase::solve(), EigenProblem::solve(), PetscOutput::solveSetup(), TransientMultiApp::solveStep(), FEProblemBase::subdomainSetup(), FEProblemBase::theWarehouse(), TimeExtremeValue::TimeExtremeValue(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), Transient::Transient(), FEProblemBase::updateMortarMesh(), Console::write(), and FEProblemBase::~FEProblemBase().
_apply_timer
PerfID VariableCondensationPreconditioner::_apply_timer private
Definition at line 220 of file VariableCondensationPreconditioner.h.
Referenced by apply().
_cols
std::vector<dof_id_type> VariableCondensationPreconditioner::_cols private
Definition at line 207 of file VariableCondensationPreconditioner.h.
Referenced by condenseSystem(), and getDofColRow().
_cols_to_idx
std::unordered_map<dof_id_type, dof_id_type> VariableCondensationPreconditioner::_cols_to_idx private
Definition at line 211 of file VariableCondensationPreconditioner.h.
Referenced by getDofColRow().
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_D
std::unique_ptr<PetscMatrix<Number> > VariableCondensationPreconditioner::_D private
Submatrices that are frequently needed while computing the condensed system _D: the submatrix that couples the primary variable with the Lagrange multiplier variable _M: the columns that correspond to the Lagrange multiplier DoFs _K: the rows that correspond to the primary variable DoFs.
Definition at line 170 of file VariableCondensationPreconditioner.h.
Referenced by computeCondensedVariables(), computeDInverse(), computeDInverseDiag(), and condenseSystem().
_dinv
Mat VariableCondensationPreconditioner::_dinv private
inverse of _D
Definition at line 172 of file VariableCondensationPreconditioner.h.
Referenced by clear(), computeCondensedVariables(), condenseSystem(), and getCondensedXY().
_dofmap
const DofMap& VariableCondensationPreconditioner::_dofmap private
DofMap for easy reference.
Definition at line 147 of file VariableCondensationPreconditioner.h.
Referenced by getDofColRow(), and getDofToCondense().
_enabled
const bool& MooseObject::_enabled protected inherited
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
Definition at line 58 of file MooseObject.h.
Referenced by MooseObject::enabled().
_factory
Factory& MooseBaseParameterInterface::_factory protected inherited
The Factory associated with the MooseApp.
Definition at line 161 of file MooseBaseParameterInterface.h.
Referenced by AddGeneralReactions::act(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), ElementIDOutputAction::act(), AddSpecies::act(), AdaptivityAction::act(), AddControlAction::act(), AddNodalNormalsAction::act(), AddPeriodicBCAction::act(), AutoCheckpointAction::act(), ComposeTimeStepperAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DisplayGhostingAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), PartitionerAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SetupPreconditionerAction::act(), SetupPredictorAction::act(), SetupResidualDebugAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddGeneralReactions::addEEDFReactionKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddDriftDiffusionAction::addPosition(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), MooseBaseParameterInterface::connectControllableParams(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), MaterialOutputAction::getParams(), and ProjectedStatefulMaterialStorageAction::processProperty().
_fe_problem
FEProblemBase& MoosePreconditioner::_fe_problem protected inherited
Subproblem this preconditioner is part of.
Definition at line 60 of file MoosePreconditioner.h.
Referenced by PhysicsBasedPreconditioner::addSystem(), PhysicsBasedPreconditioner::apply(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), MoosePreconditioner::setCouplingMatrix(), PhysicsBasedPreconditioner::setup(), and SingleMatrixPreconditioner::SingleMatrixPreconditioner().
_global_cols
std::vector<dof_id_type> VariableCondensationPreconditioner::_global_cols private
Definition at line 207 of file VariableCondensationPreconditioner.h.
Referenced by condenseSystem(), getCondensedXY(), getDofColRow(), and getFullSolution().
_global_cols_to_idx
std::unordered_map<dof_id_type, dof_id_type> VariableCondensationPreconditioner::_global_cols_to_idx private
Definition at line 211 of file VariableCondensationPreconditioner.h.
Referenced by computeCondensedJacobian(), getDofColRow(), and preallocateCondensedJacobian().
_global_lm_dofs
std::vector<dof_id_type> VariableCondensationPreconditioner::_global_lm_dofs private
Vectors of DoFs: indices associated with lagrange multipliers, and its coupled primary variable global<variable_name>_dofs represents the indices that are owned by all processors _<variable_name>_dofs represents the indices that are owned only by each processor lm: the Lagrange multiplier primary: the primal variable DoFs that couples with the Lagrange multiplier Note: the global index sets may not be scalable and necessary memory optimization will be investigated later.
Definition at line 204 of file VariableCondensationPreconditioner.h.
Referenced by getDofToCondense(), and getFullSolution().
_global_primary_dofs
std::vector<dof_id_type> VariableCondensationPreconditioner::_global_primary_dofs private
Definition at line 204 of file VariableCondensationPreconditioner.h.
Referenced by computeDInverseDiag(), condenseSystem(), getCondensedXY(), getDofColRow(), and getDofToCondense().
_global_rows
std::vector<dof_id_type> VariableCondensationPreconditioner::_global_rows private
row and column indices for the condensed system
Definition at line 207 of file VariableCondensationPreconditioner.h.
Referenced by condenseSystem(), getCondensedXY(), and getDofColRow().
_global_rows_to_idx
std::unordered_map<dof_id_type, dof_id_type> VariableCondensationPreconditioner::_global_rows_to_idx private
Maps to keep track of row and col indices from the original Jacobian matrix to the condensed Jacobian matrix.
Definition at line 210 of file VariableCondensationPreconditioner.h.
Referenced by getDofColRow(), and preallocateCondensedJacobian().
_init_timer
PerfID VariableCondensationPreconditioner::_init_timer private
Timers.
Definition at line 219 of file VariableCondensationPreconditioner.h.
Referenced by init().
_is_lm_coupling_diagonal
const bool VariableCondensationPreconditioner::_is_lm_coupling_diagonal private
Whether the coupling is diagonal.
Definition at line 150 of file VariableCondensationPreconditioner.h.
Referenced by condenseSystem().
_J_condensed
std::unique_ptr<PetscMatrix<Number> > VariableCondensationPreconditioner::_J_condensed private
Condensed Jacobian.
Definition at line 175 of file VariableCondensationPreconditioner.h.
Referenced by condenseSystem(), getCondensedXY(), and setup().
_K
std::unique_ptr<PetscMatrix<Number> > VariableCondensationPreconditioner::_K private
Definition at line 170 of file VariableCondensationPreconditioner.h.
Referenced by computeCondensedVariables(), and condenseSystem().
_lm_dofs
std::vector<dof_id_type> VariableCondensationPreconditioner::_lm_dofs private
Definition at line 204 of file VariableCondensationPreconditioner.h.
Referenced by condenseSystem(), and getDofToCondense().
_lm_sol_vec
std::unique_ptr<NumericVector<Number> > VariableCondensationPreconditioner::_lm_sol_vec private
Definition at line 180 of file VariableCondensationPreconditioner.h.
Referenced by computeCondensedVariables(), and getFullSolution().
_lm_var_ids
std::vector<unsigned int> VariableCondensationPreconditioner::_lm_var_ids private
Definition at line 160 of file VariableCondensationPreconditioner.h.
Referenced by getDofToCondense(), and VariableCondensationPreconditioner().
_lm_var_names
const std::vector<std::string> VariableCondensationPreconditioner::_lm_var_names private
Name and ID of the variables that are to be condensed out (usually the Lagrange multiplier variable)
Definition at line 159 of file VariableCondensationPreconditioner.h.
Referenced by VariableCondensationPreconditioner().
_M
std::unique_ptr<PetscMatrix<Number> > VariableCondensationPreconditioner::_M private
Definition at line 170 of file VariableCondensationPreconditioner.h.
Referenced by condenseSystem(), and getCondensedXY().
_map_global_lm_primary
std::unordered_map<dof_id_type, dof_id_type> VariableCondensationPreconditioner::_map_global_lm_primary private
Maps to keep track of the dof orders for keeping nonzero diagonal entries of the condensed system _map_global_lm_primary: map between _global_lm_dofs and _global_primary_dofs.
_map_global_primary_order: map between _global_primary_dofs and the corresponding row index in _D
Definition at line 216 of file VariableCondensationPreconditioner.h.
Referenced by getDofColRow(), and getDofToCondense().
_map_global_primary_order
std::unordered_map<dof_id_type, dof_id_type> VariableCondensationPreconditioner::_map_global_primary_order private
Definition at line 216 of file VariableCondensationPreconditioner.h.
Referenced by computeDInverseDiag(), and getDofToCondense().
_mesh
MooseMesh& VariableCondensationPreconditioner::_mesh private
Mesh object for easy reference.
Definition at line 144 of file VariableCondensationPreconditioner.h.
Referenced by getDofToCondense(), and VariableCondensationPreconditioner().
_metaname
const RestartableDataMapName Restartable::_metaname private inherited
Restartable metadata name.
Definition at line 240 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_moose_base
const MooseBase* const MooseBaseParameterInterface::_moose_base private inherited
The MooseBase object that inherits this class.
Definition at line 168 of file MooseBaseParameterInterface.h.
Referenced by MooseBaseParameterInterface::connectControllableParams(), MooseBaseParameterInterface::objectErrorPrefix(), MooseBaseParameterInterface::paramError(), and MooseBaseParameterInterface::uniqueParameterName().
_n_vars
const unsigned int VariableCondensationPreconditioner::_n_vars private
Number of variables.
Definition at line 156 of file VariableCondensationPreconditioner.h.
Referenced by VariableCondensationPreconditioner().
_name
const std::string& MooseBase::_name protected inherited
The name of this class, reference to value stored in InputParameters.
Definition at line 66 of file MooseBase.h.
Referenced by AddFieldSplitAction::act(), AddBCAction::act(), AddConstraintAction::act(), AddControlAction::act(), AddDamperAction::act(), AddDGKernelAction::act(), AddDiracKernelAction::act(), AddDistributionAction::act(), AddFunctionAction::act(), AddFunctorMaterialAction::act(), AddFVBCAction::act(), AddFVInitialConditionAction::act(), AddFVInterfaceKernelAction::act(), AddFVKernelAction::act(), AddIndicatorAction::act(), AddInitialConditionAction::act(), AddInterfaceKernelAction::act(), AddKernelAction::act(), AddMarkerAction::act(), AddMaterialAction::act(), AddMeshDivisionAction::act(), AddMeshGeneratorAction::act(), AddMultiAppAction::act(), AddNodalKernelAction::act(), AddOutputAction::act(), AddPeriodicBCAction::act(), AddPositionsAction::act(), AddPostprocessorAction::act(), AddReporterAction::act(), AddSamplerAction::act(), AddScalarKernelAction::act(), AddTimesAction::act(), AddTimeStepperAction::act(), AddTransferAction::act(), AddUserObjectAction::act(), AddVectorPostprocessorAction::act(), PartitionerAction::act(), ReadExecutorParamsAction::act(), SetupPreconditionerAction::act(), SetupTimeIntegratorAction::act(), AddDriftDiffusionAction::addADKernels(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromXY(), PiecewiseLinearBase::buildInterpolation(), CombinerGenerator::CombinerGenerator(), Executor::Executor(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), FunctionDT::FunctionDT(), FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), MooseBase::name(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), PiecewiseBase::setData(), and Split::setup().
_need_condense
bool VariableCondensationPreconditioner::_need_condense mutable private
Whether the DoFs associated the variable are to be condensed.
If the DoF list for the variable to be condensed is empty, we do not carry out static condensation
Definition at line 188 of file VariableCondensationPreconditioner.h.
Referenced by apply(), getDofToCondense(), and setup().
_nl
NonlinearSystemBase& VariableCondensationPreconditioner::_nl private
The nonlinear system this PC is associated with (convenience reference)
Definition at line 141 of file VariableCondensationPreconditioner.h.
Referenced by VariableCondensationPreconditioner().
_nl_sys_num
const unsigned int MoosePreconditioner::_nl_sys_num protected inherited
The nonlinear system number whose linearization this preconditioner should be applied to.
Definition at line 63 of file MoosePreconditioner.h.
Referenced by FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), and SingleMatrixPreconditioner::SingleMatrixPreconditioner().
_parent
const MooseObject & DataFileInterface< MooseObject >::_parent private inherited
Definition at line 46 of file DataFileInterface.h.
_pars
const InputParameters& MooseBaseParameterInterface::_pars protected inherited
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Definition at line 158 of file MooseBaseParameterInterface.h.
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), AddPeriodicBCAction::act(), AddVariableAction::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), FunctorMaterial::addFunctorPropertyByBlocks(), FVFluxKernel::adjustRMGhostLayers(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), PiecewiseTabularBase::buildFromFile(), PNGOutput::calculateRescalingValues(), BlockWeightedPartitioner::clone(), GridPartitioner::clone(), HierarchicalGridPartitioner::clone(), PetscExternalPartitioner::clone(), RandomPartitioner::clone(), SingleRankPartitioner::clone(), MooseBaseParameterInterface::connectControllableParams(), Console::Console(), AddVariableAction::createInitialConditionAction(), MaterialBase::declareADProperty(), MaterialBase::declareProperty(), FEProblemSolve::FEProblemSolve(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), FileMeshGenerator::generate(), MaterialBase::getGenericZeroMaterialProperty(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getParam(), MooseBaseParameterInterface::getRenamedParam(), AddVariableAction::init(), AdvancedOutput::initExecutionTypes(), Console::initialSetup(), MooseBaseParameterInterface::isParamSetByUser(), MooseBaseParameterInterface::isParamValid(), MultiApp::keepSolutionDuringRestore(), MooseBaseParameterInterface::paramErrorMsg(), GlobalParamsAction::parameters(), MooseBaseParameterInterface::parameters(), MooseMesh::prepare(), Eigenvalue::prepareSolverOptions(), MooseMesh::setCoordSystem(), MooseMesh::setPartitionerHelper(), SetupMeshAction::setupMesh(), Transient::setupTimeIntegrator(), MooseBaseParameterInterface::uniqueName(), and MooseBaseParameterInterface::uniqueParameterName().
_pg_moose_app
MooseApp& PerfGraphInterface::_pg_moose_app protected inherited
The MooseApp that owns the PerfGraph.
Definition at line 124 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::perfGraph().
_pre_type
PreconditionerType VariableCondensationPreconditioner::_pre_type private
Which preconditioner to use for the solve.
Definition at line 191 of file VariableCondensationPreconditioner.h.
Referenced by setup(), and VariableCondensationPreconditioner().
_preconditioner
std::unique_ptr<Preconditioner<Number> > VariableCondensationPreconditioner::_preconditioner private
Holds one Preconditioner object for the condensed system to solve.
Definition at line 194 of file VariableCondensationPreconditioner.h.
Referenced by apply(), init(), and setup().
_prefix
const std::string PerfGraphInterface::_prefix protected inherited
A prefix to use for all sections.
Definition at line 127 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::timedSectionName().
_primary_dofs
std::vector<dof_id_type> VariableCondensationPreconditioner::_primary_dofs private
Definition at line 204 of file VariableCondensationPreconditioner.h.
Referenced by condenseSystem(), and getDofToCondense().
_primary_rhs_vec
std::unique_ptr<NumericVector<Number> > VariableCondensationPreconditioner::_primary_rhs_vec private
Definition at line 180 of file VariableCondensationPreconditioner.h.
Referenced by computeCondensedVariables(), and getCondensedXY().
_primary_var_ids
std::vector<unsigned int> VariableCondensationPreconditioner::_primary_var_ids private
Definition at line 164 of file VariableCondensationPreconditioner.h.
Referenced by getDofToCondense(), and VariableCondensationPreconditioner().
_primary_var_names
const std::vector<std::string> VariableCondensationPreconditioner::_primary_var_names private
Name and ID of the corresponding coupled variable.
Definition at line 163 of file VariableCondensationPreconditioner.h.
Referenced by VariableCondensationPreconditioner().
_restartable_app
MooseApp& Restartable::_restartable_app protected inherited
Reference to the application.
Definition at line 227 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp(), and Restartable::registerRestartableNameWithFilterOnApp().
_restartable_name
std::string Restartable::_restartable_name private inherited
The name of the object.
Definition at line 243 of file Restartable.h.
Referenced by Restartable::declareRestartableDataWithObjectNameWithContext(), and Restartable::restartableName().
_restartable_read_only
const bool Restartable::_restartable_read_only protected inherited
Flag for toggling read only status (see ReporterData)
Definition at line 236 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_restartable_system_name
const std::string Restartable::_restartable_system_name protected inherited
The system name this object is in.
Definition at line 230 of file Restartable.h.
Referenced by Restartable::restartableName().
_restartable_tid
const THREAD_ID Restartable::_restartable_tid protected inherited
The thread ID for this object.
Definition at line 233 of file Restartable.h.
Referenced by Restartable::declareRestartableDataHelper().
_rows
std::vector<dof_id_type> VariableCondensationPreconditioner::_rows private
Definition at line 207 of file VariableCondensationPreconditioner.h.
Referenced by condenseSystem(), getDofColRow(), and preallocateCondensedJacobian().
_rows_to_idx
std::unordered_map<dof_id_type, dof_id_type> VariableCondensationPreconditioner::_rows_to_idx private
Definition at line 210 of file VariableCondensationPreconditioner.h.
Referenced by getDofColRow(), and preallocateCondensedJacobian().
_type
const std::string& MooseBase::_type protected inherited
The type of this class.
Definition at line 63 of file MooseBase.h.
Referenced by FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), FEProblemBase::init(), FEProblemBase::solverTypeString(), and MooseBase::type().
_x_hat
std::unique_ptr<NumericVector<Number> > VariableCondensationPreconditioner::_x_hat private
_x_hat, _y_hat: condensed solution and RHS vectors _primary_rhs_vec: part of the RHS vector that correspond to the primary variable DoFs _lm_sol_vec: solution vector that corresponds to the LM variable
Definition at line 180 of file VariableCondensationPreconditioner.h.
Referenced by apply(), computeCondensedVariables(), getCondensedXY(), and getFullSolution().
_y_hat
std::unique_ptr<NumericVector<Number> > VariableCondensationPreconditioner::_y_hat private
Definition at line 180 of file VariableCondensationPreconditioner.h.
Referenced by apply(), and getCondensedXY().
_zero_rows
std::vector<dof_id_type> VariableCondensationPreconditioner::_zero_rows private
The row indices that correspond to the zero diagonal entries in the original Jacobian matrix This is only used when _adaptive_condensation = true.
Definition at line 184 of file VariableCondensationPreconditioner.h.
Referenced by getDofToCondense(), and setup().
The documentation for this class was generated from the following files:
moose/framework/include/preconditioners/VariableCondensationPreconditioner.h
moose/framework/src/preconditioners/VariableCondensationPreconditioner.C