Zapdos: MooseVariableDependencyInterface Class Reference
MooseVariableDependencyInterface Class Reference
#include <MooseVariableDependencyInterface.h>
Public Member Functions
MooseVariableDependencyInterface (const MooseObject *)
const std::set< MooseVariableFieldBase * > & getMooseVariableDependencies () const
Retrieve the set of MooseVariableFieldBase that this object depends on.
template<typename DofObjectType >
std::set< MooseVariableFieldBase * > checkAllVariables (const DofObjectType &dof_object, const std::set< MooseVariableFieldBase * > &vars_to_omit={})
Check whether all of the variable dependencies have degree of freedom indices on the supplied degree of freedom object.
template<typename DofObjectType >
std::set< MooseVariableFieldBase * > checkVariables (const DofObjectType &dof_object, const std::set< MooseVariableFieldBase * > &vars_to_check)
Check whether all of the supplied variables have degree of freedom indices on the supplied degree of freedom object.
Protected Member Functions
void addMooseVariableDependency (MooseVariableFieldBase *var)
Call this function to add the passed in MooseVariableFieldBase as a variable that this object depends on.
void addMooseVariableDependency (const std::vector< MooseVariableFieldBase * > &vars)
Private Attributes
std::set< MooseVariableFieldBase * > _moose_variable_dependencies
std::vector< libMesh::dof_id_type > _dof_indices
A container for holding dof indices in order to avoid constant memory reallocation.
Detailed Description
Definition at line 25 of file MooseVariableDependencyInterface.h.
Constructor & Destructor Documentation
MooseVariableDependencyInterface()
MooseVariableDependencyInterface::MooseVariableDependencyInterface (const MooseObject *)
Definition at line 21 of file MooseVariableDependencyInterface.C.
{}
Member Function Documentation
addMooseVariableDependency() [1/2]
void MooseVariableDependencyInterface::addMooseVariableDependency (const std::vector< MooseVariableFieldBase * > & vars) inline protected
Definition at line 77 of file MooseVariableDependencyInterface.h.
  {
    _moose_variable_dependencies.insert(vars.begin(), vars.end());
  }
addMooseVariableDependency() [2/2]
void MooseVariableDependencyInterface::addMooseVariableDependency (MooseVariableFieldBase * var) inline protected
Call this function to add the passed in MooseVariableFieldBase as a variable that this object depends on.
Definition at line 73 of file MooseVariableDependencyInterface.h.
  {
    _moose_variable_dependencies.insert(var);
  }
Referenced by ADDGKernel::ADDGKernel(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADInterfaceKernelTempl< T >::ADInterfaceKernelTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayNodalBC::ArrayNodalBC(), AuxNodalScalarKernel::AuxNodalScalarKernel(), CoupleableMooseVariableDependencyIntermediateInterface::CoupleableMooseVariableDependencyIntermediateInterface(), DGKernel::DGKernel(), DiracKernelTempl< T >::DiracKernelTempl(), DomainUserObject::DomainUserObject(), ElemElemConstraint::ElemElemConstraint(), ElementIndicator::ElementIndicator(), ElementIntegralArrayVariablePostprocessor::ElementIntegralArrayVariablePostprocessor(), ElementIntegralVariablePostprocessor::ElementIntegralVariablePostprocessor(), ElementIntegralVariableUserObject::ElementIntegralVariableUserObject(), ElementUserObject::ElementUserObject(), ElementVariablePostprocessor::ElementVariablePostprocessor(), FVBoundaryCondition::FVBoundaryCondition(), FVInterfaceKernel::FVInterfaceKernel(), IntegratedBC::IntegratedBC(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceMaterial::InterfaceMaterial(), InterfaceUserObjectBase::InterfaceUserObjectBase(), InternalSideIndicator::InternalSideIndicator(), InternalSideIntegralVariablePostprocessor::InternalSideIntegralVariablePostprocessor(), InternalSideUserObject::InternalSideUserObject(), Kernel::Kernel(), Marker::Marker(), Material::Material(), MortarConstraintBase::MortarConstraintBase(), NeighborCoupleableMooseVariableDependencyIntermediateInterface::NeighborCoupleableMooseVariableDependencyIntermediateInterface(), NodalBC::NodalBC(), NodalConstraint::NodalConstraint(), NodalKernel::NodalKernel(), NodalScalarKernel::NodalScalarKernel(), NodalUserObject::NodalUserObject(), NodeElemConstraint::NodeElemConstraint(), NodeFaceConstraint::NodeFaceConstraint(), PointVariableSamplerBase::PointVariableSamplerBase(), QuadraturePointMarker::QuadraturePointMarker(), SideIntegralVariablePostprocessor::SideIntegralVariablePostprocessor(), SideIntegralVariableUserObject::SideIntegralVariableUserObject(), SideUserObject::SideUserObject(), SideVariablePostprocessor::SideVariablePostprocessor(), VectorIntegratedBC::VectorIntegratedBC(), VectorKernel::VectorKernel(), and VectorNodalBC::VectorNodalBC().
checkAllVariables()
template<typename DofObjectType > std::set< MooseVariableFieldBase * > MooseVariableDependencyInterface::checkAllVariables (const DofObjectType & dof_object, const std::set< MooseVariableFieldBase * > & vars_to_omit = {})
Check whether all of the variable dependencies have degree of freedom indices on the supplied degree of freedom object.
Parameters
dof_object The degree of freedom object (an element or node) that we want to check for existence of variable degrees of freedom on
vars_to_omit Variables that we can omit from checking
Returns
Any variables that do not have degrees of freedom on the supplied degree of freedom object
Definition at line 91 of file MooseVariableDependencyInterface.h.
{
  if (vars_to_omit.empty())
    return checkVariables(dof_object, _moose_variable_dependencies);
  std::set<MooseVariableFieldBase *> vars_to_check;
  std::set_difference(_moose_variable_dependencies.begin(),
                      _moose_variable_dependencies.end(),
                      vars_to_omit.begin(),
                      vars_to_omit.end(),
                      std::inserter(vars_to_check, vars_to_check.begin()));
  return checkVariables(dof_object, vars_to_check);
}
checkVariables()
template<typename DofObjectType > template std::set< MooseVariableFieldBase * > MooseVariableDependencyInterface::checkVariables (const DofObjectType & dof_object, const std::set< MooseVariableFieldBase * > & vars_to_check)
Check whether all of the supplied variables have degree of freedom indices on the supplied degree of freedom object.
Parameters
dof_object The degree of freedom object (an element or node) that we want to check for existence of variable degrees of freedom on
vars_to_check the variables to check
Returns
Any variables that do not have degrees of freedom on the supplied degree of freedom object
Definition at line 25 of file MooseVariableDependencyInterface.C.
{
  std::set<MooseVariableFieldBase *> vars_without_indices;
  for (auto * const var : vars_to_check)
  {
    var->sys().dofMap().dof_indices(&dof_object, _dof_indices, var->number());
    if (_dof_indices.empty())
      vars_without_indices.insert(var);
  }
  return vars_without_indices;
}
Referenced by checkAllVariables().
getMooseVariableDependencies()
const std::set< MooseVariableFieldBase * > & MooseVariableDependencyInterface::getMooseVariableDependencies () const inline
Retrieve the set of MooseVariableFieldBase that this object depends on.
Returns
The MooseVariableFieldBase that MUST be reinited before evaluating this object
Definition at line 35 of file MooseVariableDependencyInterface.h.
  {
    return _moose_variable_dependencies;
  }
Referenced by ComputeUserObjectsThread::subdomainChanged(), and MooseObjectWarehouseBase< T >::updateVariableDependencyHelper().
Member Data Documentation
_dof_indices
std::vector<libMesh::dof_id_type> MooseVariableDependencyInterface::_dof_indices private
A container for holding dof indices in order to avoid constant memory reallocation.
Definition at line 86 of file MooseVariableDependencyInterface.h.
Referenced by checkVariables().
_moose_variable_dependencies
std::set<MooseVariableFieldBase *> MooseVariableDependencyInterface::_moose_variable_dependencies private
Definition at line 83 of file MooseVariableDependencyInterface.h.
Referenced by addMooseVariableDependency(), checkAllVariables(), and getMooseVariableDependencies().
The documentation for this class was generated from the following files:
moose/framework/include/variables/MooseVariableDependencyInterface.h
moose/framework/src/variables/MooseVariableDependencyInterface.C