Zapdos: AuxiliarySystem Class Reference
AuxiliarySystem Class Reference
A system that holds auxiliary variables.
#include <AuxiliarySystem.h>
Public Member Functions
AuxiliarySystem (FEProblemBase &subproblem, const std::string &name)
virtual ~AuxiliarySystem ()
virtual void initialSetup () override
Setup Functions.
virtual void timestepSetup () override
virtual void customSetup (const ExecFlagType &exec_type) override
virtual void subdomainSetup () override
virtual void residualSetup () override
virtual void jacobianSetup () override
virtual void updateActive (THREAD_ID tid)
virtual void addVariable (const std::string &var_type, const std::string &name, InputParameters &parameters) override
Canonical method for adding a variable.
void addTimeIntegrator (const std::string &type, const std::string &name, InputParameters &parameters) override
Add a time integrator.
void addDotVectors ()
Adds u_dot, u_dotdot, u_dot_old and u_dotdot_old vectors if requested by the time integrator.
void addKernel (const std::string &kernel_name, const std::string &name, InputParameters &parameters)
Adds an auxiliary kernel.
void addScalarKernel (const std::string &kernel_name, const std::string &name, InputParameters &parameters)
Adds a scalar kernel.
virtual void reinitElem (const Elem *elem, THREAD_ID tid) override
Reinit an element assembly info.
virtual void reinitElemFace (const Elem *elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid) override
Reinit assembly info for a side of an element.
const NumericVector< Number > *const & currentSolution () const override
The solution vector that is currently being operated on.
NumericVector< Number > * solutionUDot () override
NumericVector< Number > * solutionUDotDot () override
NumericVector< Number > * solutionUDotOld () override
NumericVector< Number > * solutionUDotDotOld () override
const NumericVector< Number > * solutionUDot () const override
const NumericVector< Number > * solutionUDotDot () const override
const NumericVector< Number > * solutionUDotOld () const override
const NumericVector< Number > * solutionUDotDotOld () const override
virtual void serializeSolution ()
virtual NumericVector< Number > & serializedSolution () override
Returns a reference to a serialized version of the solution vector for this subproblem.
virtual void augmentSparsity (SparsityPattern::Graph &, std::vector< dof_id_type > &, std::vector< dof_id_type > &) override
Will modify the sparsity pattern to add logical geometric connections.
virtual void compute (ExecFlagType type)
Compute auxiliary variables.
std::set< std::string > getDependObjects (ExecFlagType type)
Get a list of dependent UserObjects for this exec type.
std::set< std::string > getDependObjects ()
virtual Order getMinQuadratureOrder () override
Get the minimum quadrature order for evaluating elemental auxiliary variables.
bool needMaterialOnSide (BoundaryID bnd_id)
Indicated whether this system needs material properties on boundaries.
virtual System & sys ()
virtual System & system () override
Get the reference to the libMesh system.
virtual const System & system () const override
virtual void setPreviousNewtonSolution ()
void setScalarVariableCoupleableTags (ExecFlagType type)
void clearScalarVariableCoupleableTags ()
const ExecuteMooseObjectWarehouse< AuxKernel > & nodalAuxWarehouse () const
const ExecuteMooseObjectWarehouse< VectorAuxKernel > & nodalVectorAuxWarehouse () const
const ExecuteMooseObjectWarehouse< ArrayAuxKernel > & nodalArrayAuxWarehouse () const
const ExecuteMooseObjectWarehouse< AuxKernel > & elemAuxWarehouse () const
const ExecuteMooseObjectWarehouse< VectorAuxKernel > & elemVectorAuxWarehouse () const
const ExecuteMooseObjectWarehouse< ArrayAuxKernel > & elemArrayAuxWarehouse () const
virtual void addTimeIntegrator (const std::string &, const std::string &, InputParameters &)
virtual void addTimeIntegrator (std::shared_ptr< TimeIntegrator >)
unsigned int number () const
Gets the number of this system.
virtual MooseMesh & mesh ()
virtual const MooseMesh & mesh () const
virtual SubProblem & subproblem ()
virtual const SubProblem & subproblem () const
void applyScalingFactors (const std::vector< Real > &inverse_scaling_factors)
Applies scaling factors to the system's variables.
bool computingScalingJacobian () const
Whether we are computing an initial Jacobian for automatic variable scaling.
bool automaticScaling () const
Getter for whether we are performing automatic scaling.
void automaticScaling (bool automatic_scaling)
Setter for whether we are performing automatic scaling.
void setVerboseFlag (const bool &verbose)
Sets the verbose flag.
virtual DofMap & dofMap ()
Gets writeable reference to the dof map.
virtual const DofMap & dofMap () const
Gets const reference to the dof map.
virtual void init ()
Initialize the system.
virtual void initializeObjects ()
Called only once, just before the solve begins so objects can do some precalculations.
virtual void update (bool update_libmesh_system=true)
Update the system (doing libMesh magic)
virtual void solve ()
Solve the system (using libMesh magic)
virtual void copyOldSolutions ()
Shifts the solutions backwards in time.
virtual void restoreSolutions ()
Restore current solutions (call after your solve failed)
NumericVector< Number > & solution ()
const NumericVector< Number > & solution () const
NumericVector< Number > & solutionOld ()
const NumericVector< Number > & solutionOld () const
NumericVector< Number > & solutionOlder ()
const NumericVector< Number > & solutionOlder () const
virtual const NumericVector< Number > * solutionPreviousNewton () const
virtual NumericVector< Number > * solutionPreviousNewton ()
virtual void initSolutionState ()
Initializes the solution state.
virtual NumericVector< Number > & solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time)
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
virtual const NumericVector< Number > & solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time) const
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
virtual void needSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time)
Registers that the solution state state is needed.
virtual bool hasSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time) const
Whether or not the system has the solution state (0 = current, 1 = old, 2 = older, etc).
virtual Number & duDotDu ()
virtual const Number & duDotDu () const
virtual Number & duDotDotDu ()
virtual const Number & duDotDotDu () const
virtual void saveOldSolutions ()
Save the old and older solutions.
virtual void restoreOldSolutions ()
Restore the old and older solutions when the saved solutions present.
bool hasVector (const std::string &tag_name) const
Check if the named vector exists in the system.
virtual bool hasVector (TagID tag_id) const
Check if the tagged vector exists in the system.
virtual TagID timeVectorTag () const
Ideally, we should not need this API.
virtual TagID systemMatrixTag () const
Return the Matrix Tag ID for System.
virtual TagID nonTimeVectorTag () const
virtual TagID residualVectorTag () const
virtual std::set< TagID > defaultVectorTags () const
Get the default vector tags associated with this system.
virtual std::set< TagID > defaultMatrixTags () const
Get the default matrix tags associted with this system.
virtual void associateVectorToTag (NumericVector< Number > &vec, TagID tag)
Associate a vector for a given tag.
virtual void disassociateVectorFromTag (NumericVector< Number > &vec, TagID tag)
Disassociate a given vector from a given tag.
virtual void disassociateVectorFromTag (TagID tag)
Disassociate any vector that is associated with a given tag.
virtual void disassociateDefaultVectorTags ()
Disassociate the vectors associated with the default vector tags of this system.
virtual bool hasMatrix (TagID tag) const
Check if the tagged matrix exists in the system.
virtual SparseMatrix< Number > & getMatrix (TagID tag)
Get a raw SparseMatrix.
virtual const SparseMatrix< Number > & getMatrix (TagID tag) const
Get a raw SparseMatrix.
virtual void activeAllMatrixTags ()
Make all exsiting matrices ative.
virtual void activeMatrixTag (TagID tag)
Active a matrix for tag.
virtual bool matrixTagActive (TagID tag) const
If or not a matrix tag is active.
virtual void deactiveMatrixTag (TagID tag)
deactive a matrix for tag
virtual void deactiveAllMatrixTags ()
Make matrices inactive.
void closeTaggedMatrices (const std::set< TagID > &tags)
Close all matrices associated the tags.
void flushTaggedMatrices (const std::set< TagID > &tags)
flushes all matrices associated to tags.
virtual void associateMatrixToTag (SparseMatrix< Number > &matrix, TagID tag)
Associate a matrix to a tag.
virtual void disassociateMatrixFromTag (SparseMatrix< Number > &matrix, TagID tag)
Disassociate a matrix from a tag.
virtual void disassociateMatrixFromTag (TagID tag)
Disassociate any matrix that is associated with a given tag.
virtual void disassociateDefaultMatrixTags ()
Disassociate the matrices associated with the default matrix tags of this system.
virtual NumericVector< Number > & residualCopy ()
virtual NumericVector< Number > & residualGhosted ()
virtual void augmentSendList (std::vector< dof_id_type > &send_list)
Will modify the send_list to add all of the extra ghosted dofs for this system.
virtual bool isArrayVariable (const std::string &var_name) const
If a variable is an array variable.
virtual bool isScalarVariable (unsigned int var_name) const
MooseVariableFieldBase & getVariable (THREAD_ID tid, const std::string &var_name) const
Gets a reference to a variable of with specified name.
MooseVariableFieldBase & getVariable (THREAD_ID tid, unsigned int var_number) const
Gets a reference to a variable with specified number.
template<typename T >
MooseVariableFE< T > & getFieldVariable (THREAD_ID tid, const std::string &var_name)
Gets a reference to a variable of with specified name.
template<typename T >
MooseVariableFE< T > & getFieldVariable (THREAD_ID tid, unsigned int var_number)
Gets a reference to a variable with specified number.
template<typename T >
MooseVariableField< T > & getActualFieldVariable (THREAD_ID tid, const std::string &var_name)
Returns a field variable pointer - this includes finite volume variables.
template<typename T >
MooseVariableField< T > & getActualFieldVariable (THREAD_ID tid, unsigned int var_number)
Returns a field variable pointer - this includes finite volume variables.
template<typename T >
MooseVariableFV< T > & getFVVariable (THREAD_ID tid, const std::string &var_name)
Return a finite volume variable.
virtual MooseVariableScalar & getScalarVariable (THREAD_ID tid, const std::string &var_name) const
Gets a reference to a scalar variable with specified number.
virtual MooseVariableScalar & getScalarVariable (THREAD_ID tid, unsigned int var_number) const
Gets a reference to a variable with specified number.
virtual const std::set< SubdomainID > * getVariableBlocks (unsigned int var_number)
Get the block where a variable of this system is defined.
virtual unsigned int nVariables () const
Get the number of variables in this system.
unsigned int nFieldVariables () const
Get the number of field variables in this system.
unsigned int nFVVariables () const
Get the number of finite volume variables in this system.
std::size_t getMaxVarNDofsPerElem () const
Gets the maximum number of dofs used by any one variable on any one element.
std::size_t getMaxVarNDofsPerNode () const
Gets the maximum number of dofs used by any one variable on any one node.
void assignMaxVarNDofsPerElem (std::size_t max_dofs)
assign the maximum element dofs
void assignMaxVarNDofsPerNode (std::size_t max_dofs)
assign the maximum node dofs
virtual void addVariableToZeroOnResidual (std::string var_name)
Adds this variable to the list of variables to be zeroed during each residual evaluation.
virtual void addVariableToZeroOnJacobian (std::string var_name)
Adds this variable to the list of variables to be zeroed during each Jacobian evaluation.
virtual void zeroVariables (std::vector< std::string > &vars_to_be_zeroed)
Zero out the solution for the list of variables passed in.
virtual void zeroVariablesForResidual ()
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on residual evaluation by a call to addVariableToZeroOnResidual()
virtual void zeroVariablesForJacobian ()
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on Jacobian evaluation by a call to addVariableToZeroOnResidual()
virtual void prepare (THREAD_ID tid)
Prepare the system for use.
virtual void prepareFace (THREAD_ID tid, bool resize_data)
Prepare the system for use on sides.
virtual void prepareNeighbor (THREAD_ID tid)
Prepare the system for use.
virtual void prepareLowerD (THREAD_ID tid)
Prepare the system for use for lower dimensional elements.
virtual void reinitNeighborFace (const Elem *elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid)
Compute the values of the variables at all the current points.
virtual void reinitNeighbor (const Elem *elem, THREAD_ID tid)
Compute the values of the variables at all the current points.
virtual void reinitLowerD (THREAD_ID tid)
Compute the values of the variables on the lower dimensional element.
virtual void reinitNode (const Node *node, THREAD_ID tid)
Reinit nodal assembly info.
virtual void reinitNodeFace (const Node *node, BoundaryID bnd_id, THREAD_ID tid)
Reinit nodal assembly info on a face.
virtual void reinitNodes (const std::vector< dof_id_type > &nodes, THREAD_ID tid)
Reinit variables at a set of nodes.
virtual void reinitNodesNeighbor (const std::vector< dof_id_type > &nodes, THREAD_ID tid)
Reinit variables at a set of neighbor nodes.
virtual void reinitScalars (THREAD_ID tid, bool reinit_for_derivative_reordering=false)
Reinit scalar varaibles.
virtual void addVariableToCopy (const std::string &dest_name, const std::string &source_name, const std::string &timestep)
Add info about variable that will be copied.
const std::vector< MooseVariableFieldBase * > & getVariables (THREAD_ID tid)
const std::vector< MooseVariableScalar * > & getScalarVariables (THREAD_ID tid)
const std::set< SubdomainID > & getSubdomainsForVar (unsigned int var_number) const
const std::set< SubdomainID > & getSubdomainsForVar (const std::string &var_name) const
Get the block where a variable of this system is defined.
void removeVector (const std::string &name)
Remove a vector from the system with the given name.
void removeVector (TagID tag_id)
Remove a solution length vector from the system with the specified TagID.
NumericVector< Number > & addVector (const std::string &vector_name, const bool project, const ParallelType type)
Adds a solution length vector to the system.
NumericVector< Number > & addVector (TagID tag, const bool project, const ParallelType type)
Adds a solution length vector to the system with the specified TagID.
void closeTaggedVector (const TagID tag)
Close vector with the given tag.
void closeTaggedVectors (const std::set< TagID > &tags)
Close all vectors for given tags.
void zeroTaggedVector (const TagID tag)
Zero vector with the given tag.
void zeroTaggedVectors (const std::set< TagID > &tags)
Zero all vectors for given tags.
void setVariableGlobalDoFs (const std::string &var_name)
set all the global dof indices for a variable
const std::vector< dof_id_type > & getVariableGlobalDoFs ()
Get the global dof indices of a variable, this needs to be called after the indices have been set by setVariableGlobalDoFs
SparseMatrix< Number > & addMatrix (TagID tag)
Adds a matrix with a given tag.
void removeMatrix (TagID tag)
Removes a matrix with a given tag.
virtual const std::string & name () const
const std::vector< VariableName > & getVariableNames () const
void getStandardFieldVariableNames (std::vector< VariableName > &std_field_variables) const
unsigned int getMaxVariableNumber () const
Returns the maximum number of all variables on the system.
virtual void computeVariables (const NumericVector< Number > &)
void copyVars (ExodusII_IO &io)
virtual void copySolutionsBackwards ()
Copy current solution into old and older.
TimeIntegrator * getTimeIntegrator ()
const TimeIntegrator * getTimeIntegrator () const
std::shared_ptr< TimeIntegrator > getSharedTimeIntegrator ()
bool hasVarCopy () const
Whether or not there are variables to be restarted from an Exodus mesh file.
void addScalingVector ()
Add the scaling factor vector to the system.
bool solutionStatesInitialized () const
Whether or not the solution states have been initialized via initSolutionState()
void clearAllDofIndices ()
Clear all dof indices from moose variables.
void setActiveVariableCoupleableVectorTags (const std::set< TagID > &vtags, THREAD_ID tid)
Set the active vector tags for the variables.
void setActiveScalarVariableCoupleableVectorTags (const std::set< TagID > &vtags, THREAD_ID tid)
Set the active vector tags for the scalar variables.
Moose::VarKindType varKind () const
PerfGraph & perfGraph ()
Get the PerfGraph.
virtual NumericVector< Number > & getVector (const std::string &name)
Get a raw NumericVector by name.
virtual const NumericVector< Number > & getVector (const std::string &name) const
virtual NumericVector< Number > & getVector (TagID tag)
Get a raw NumericVector by tag.
virtual const NumericVector< Number > & getVector (TagID tag) const
virtual bool hasVariable (const std::string &var_name) const
Query a system for a variable.
virtual bool hasScalarVariable (const std::string &var_name) const
Static Public Member Functions
static InputParameters validParams ()
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Member Functions
void computeScalarVars (ExecFlagType type)
void computeNodalVars (ExecFlagType type)
void computeMortarNodalVars (ExecFlagType type)
void computeNodalVecVars (ExecFlagType type)
void computeNodalArrayVars (ExecFlagType type)
void computeElementalVars (ExecFlagType type)
void computeElementalVecVars (ExecFlagType type)
void computeElementalArrayVars (ExecFlagType type)
template<typename AuxKernelType >
void computeElementalVarsHelper (const MooseObjectWarehouse< AuxKernelType > &warehouse)
template<typename AuxKernelType >
void computeNodalVarsHelper (const MooseObjectWarehouse< AuxKernelType > &warehouse)
NumericVector< Number > & solutionInternal () const override
Internal getter for solution owned by libMesh.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level) const
Call to register a named section for timing.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level, const std::string &live_message, const bool print_dots=true) const
Call to register a named section for timing.
std::string timedSectionName (const std::string &section_name) const
Protected Attributes
FEProblemBase & _fe_problem
System & _sys
const NumericVector< Number > * _current_solution
solution vector from nonlinear solver
std::unique_ptr< NumericVector< Number > > _serialized_solution
Serialized version of the solution vector, or nullptr if a serialized solution is not needed.
NumericVector< Number > * _u_dot
solution vector for u^dot
NumericVector< Number > * _u_dotdot
solution vector for u^dotdot
NumericVector< Number > * _u_dot_old
Old solution vector for u^dot.
NumericVector< Number > * _u_dotdot_old
Old solution vector for u^dotdot.
std::vector< NumericVector< Number > * > _solution_state
The current states of the solution (0 = current, 1 = old, etc)
std::vector< std::vector< MooseVariableFEBase * > > _nodal_vars
ExecuteMooseObjectWarehouse< AuxScalarKernel > _aux_scalar_storage
ExecuteMooseObjectWarehouse< AuxKernel > _nodal_aux_storage
ExecuteMooseObjectWarehouse< AuxKernel > _mortar_nodal_aux_storage
ExecuteMooseObjectWarehouse< AuxKernel > _elemental_aux_storage
ExecuteMooseObjectWarehouse< VectorAuxKernel > _nodal_vec_aux_storage
ExecuteMooseObjectWarehouse< VectorAuxKernel > _elemental_vec_aux_storage
ExecuteMooseObjectWarehouse< ArrayAuxKernel > _nodal_array_aux_storage
ExecuteMooseObjectWarehouse< ArrayAuxKernel > _elemental_array_aux_storage
SubProblem & _subproblem
MooseApp & _app
Factory & _factory
MooseMesh & _mesh
std::string _name
The name of this system.
std::vector< VariableWarehouse > _vars
Variable warehouses (one for each thread)
std::map< unsigned int, std::set< SubdomainID > > _var_map
Map of variables (variable id -> array of subdomains where it lives)
unsigned int _max_var_number
Maximum variable number.
std::vector< std::string > _vars_to_be_zeroed_on_residual
std::vector< std::string > _vars_to_be_zeroed_on_jacobian
Real _du_dot_du
Real _du_dotdot_du
std::vector< NumericVector< Number > * > _tagged_vectors
Tagged vectors (pointer)
std::vector< SparseMatrix< Number > * > _tagged_matrices
Tagged matrices (pointer)
std::vector< bool > _matrix_tag_active_flags
Active flags for tagged matrices.
NumericVector< Real > * _saved_old
NumericVector< Real > * _saved_older
NumericVector< Real > * _saved_dot_old
NumericVector< Real > * _saved_dotdot_old
Moose::VarKindType _var_kind
default kind of variables in this system
std::vector< VarCopyInfo > _var_to_copy
size_t _max_var_n_dofs_per_elem
Maximum number of dofs for any one variable on any one element.
size_t _max_var_n_dofs_per_node
Maximum number of dofs for any one variable on any one node.
std::shared_ptr< TimeIntegrator > _time_integrator
Time integrator.
std::vector< std::vector< MooseVariableFieldBase * > > _numbered_vars
Map variable number to its pointer.
bool _automatic_scaling
Whether to automatically scale the variables.
bool _verbose
True if printing out additional information.
bool _solution_states_initialized
Whether or not the solution states have been initialized.
std::vector< dof_id_type > _var_all_dof_indices
Container for the dof indices of a given variable.
MooseApp & _pg_moose_app
The MooseApp that owns the PerfGraph.
const std::string _prefix
A prefix to use for all sections.
std::vector< std::vector< MooseVariableFieldBase * > > _elem_vars
Elemental variables.
Private Member Functions
TagName oldSolutionStateVectorName (const unsigned int, Moose::SolutionIterationType iteration_type) const
Gets the vector name used for an old (not current) solution state.
Private Attributes
std::array< std::vector< NumericVector< Number > * >, 2 > _solution_states
The solution states (0 = current, 1 = old, 2 = older, etc)
std::vector< NumericVector< Number > * > _saved_solution_states
The saved solution states (0 = current, 1 = old, 2 = older, etc)
Friends
class ComputeIndicatorThread
class ComputeMarkerThread
class FlagElementsThread
class ComputeNodalKernelsThread
class ComputeNodalKernelBcsThread
class ComputeNodalKernelJacobiansThread
class ComputeNodalKernelBCJacobiansThread
Detailed Description
A system that holds auxiliary variables.
Definition at line 41 of file AuxiliarySystem.h.
Constructor & Destructor Documentation
AuxiliarySystem()
AuxiliarySystem::AuxiliarySystem (FEProblemBase & subproblem, const std::string & name)
Definition at line 35 of file AuxiliarySystem.C.
  : SystemBase(subproblem, name, Moose::VAR_AUXILIARY),
    PerfGraphInterface(subproblem.getMooseApp().perfGraph(), "AuxiliarySystem"),
    _fe_problem(subproblem),
    _sys(subproblem.es().add_system<System>(name)),
    _current_solution(_sys.current_local_solution.get()),
    _u_dot(NULL),
    _u_dotdot(NULL),
    _u_dot_old(NULL),
    _u_dotdot_old(NULL),
    _aux_scalar_storage(_app.getExecuteOnEnum()),
    _nodal_aux_storage(_app.getExecuteOnEnum()),
    _mortar_nodal_aux_storage(_app.getExecuteOnEnum()),
    _elemental_aux_storage(_app.getExecuteOnEnum()),
    _nodal_vec_aux_storage(_app.getExecuteOnEnum()),
    _elemental_vec_aux_storage(_app.getExecuteOnEnum()),
    _nodal_array_aux_storage(_app.getExecuteOnEnum()),
    _elemental_array_aux_storage(_app.getExecuteOnEnum())
{
  _nodal_vars.resize(libMesh::n_threads());
  _elem_vars.resize(libMesh::n_threads());
  if (!_fe_problem.defaultGhosting())
  {
    auto & dof_map = _sys.get_dof_map();
    dof_map.remove_algebraic_ghosting_functor(dof_map.default_algebraic_ghosting());
    dof_map.set_implicit_neighbor_dofs(false);
  }
}
~AuxiliarySystem()
AuxiliarySystem::~AuxiliarySystem () virtual default
Member Function Documentation
activeAllMatrixTags()
void SystemBase::activeAllMatrixTags () virtual inherited
Make all exsiting matrices ative.
Definition at line 1103 of file SystemBase.C.
{
  auto num_matrix_tags = _subproblem.numMatrixTags();
  _matrix_tag_active_flags.resize(num_matrix_tags);
  for (decltype(num_matrix_tags) tag = 0; tag < num_matrix_tags; tag++)
    if (hasMatrix(tag))
      _matrix_tag_active_flags[tag] = true;
    else
      _matrix_tag_active_flags[tag] = false;
}
Referenced by NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualAndJacobianInternal(), and NonlinearSystemBase::computeResidualTags().
activeMatrixTag()
void SystemBase::activeMatrixTag (TagID tag) virtual inherited
Active a matrix for tag.
Definition at line 1068 of file SystemBase.C.
{
  mooseAssert(_subproblem.matrixTagExists(tag),
              "Cannot active Matrix with matrix_tag : " << tag << "that does not exist");
  if (_matrix_tag_active_flags.size() < tag + 1)
    _matrix_tag_active_flags.resize(tag + 1);
  _matrix_tag_active_flags[tag] = true;
}
addDotVectors()
void AuxiliarySystem::addDotVectors ()
Adds u_dot, u_dotdot, u_dot_old and u_dotdot_old vectors if requested by the time integrator.
Definition at line 68 of file AuxiliarySystem.C.
{
  if (_fe_problem.uDotRequested())
    _u_dot = &addVector("u_dot", true, GHOSTED);
  if (_fe_problem.uDotDotRequested())
    _u_dotdot = &addVector("u_dotdot", true, GHOSTED);
  if (_fe_problem.uDotOldRequested())
    _u_dot_old = &addVector("u_dot_old", true, GHOSTED);
  if (_fe_problem.uDotDotOldRequested())
    _u_dotdot_old = &addVector("u_dotdot_old", true, GHOSTED);
}
addKernel()
void AuxiliarySystem::addKernel (const std::string & kernel_name, const std::string & name, InputParameters & parameters)
Adds an auxiliary kernel.
Parameters
kernel_name The type of the kernel
name The name of the kernel
parameters Parameters for this kernel
Definition at line 284 of file AuxiliarySystem.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    if (parameters.get<std::string>("_moose_base") == "AuxKernel")
    {
      std::shared_ptr<AuxKernel> kernel =
          _factory.create<AuxKernel>(kernel_name, name, parameters, tid);
      if (kernel->isNodal())
      {
        if (kernel->isMortar())
          _mortar_nodal_aux_storage.addObject(kernel, tid);
        else
          _nodal_aux_storage.addObject(kernel, tid);
      }
      else
        _elemental_aux_storage.addObject(kernel, tid);
    }
    else if (parameters.get<std::string>("_moose_base") == "VectorAuxKernel")
    {
      std::shared_ptr<VectorAuxKernel> kernel =
          _factory.create<VectorAuxKernel>(kernel_name, name, parameters, tid);
      if (kernel->isNodal())
      {
        if (kernel->isMortar())
          mooseError("Vector mortar aux kernels not yet implemented");
        _nodal_vec_aux_storage.addObject(kernel, tid);
      }
      else
        _elemental_vec_aux_storage.addObject(kernel, tid);
    }
    else if (parameters.get<std::string>("_moose_base") == "ArrayAuxKernel")
    {
      std::shared_ptr<ArrayAuxKernel> kernel =
          _factory.create<ArrayAuxKernel>(kernel_name, name, parameters, tid);
      if (kernel->isNodal())
      {
        if (kernel->isMortar())
          mooseError("Vector mortar aux kernels not yet implemented");
        _nodal_array_aux_storage.addObject(kernel, tid);
      }
      else
        _elemental_array_aux_storage.addObject(kernel, tid);
    }
  }
}
addMatrix()
SparseMatrix< Number > & SystemBase::addMatrix (TagID tag) inherited
Adds a matrix with a given tag.
Parameters
tag_name The name of the tag
Definition at line 559 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag))
    mooseError("Cannot add tagged matrix with TagID ",
               tag,
               " in system '",
               name(),
               "' because the tag does not exist in the problem");
  if (hasMatrix(tag))
    return getMatrix(tag);
  const auto matrix_name = _subproblem.matrixTagName(tag);
  SparseMatrix<Number> & mat = system().add_matrix(matrix_name);
  associateMatrixToTag(mat, tag);
  return mat;
}
addScalarKernel()
void AuxiliarySystem::addScalarKernel (const std::string & kernel_name, const std::string & name, InputParameters & parameters)
Adds a scalar kernel.
Parameters
kernel_name The type of the kernel
name The name of the kernel
parameters Kernel parameters
Definition at line 336 of file AuxiliarySystem.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    std::shared_ptr<AuxScalarKernel> kernel =
        _factory.create<AuxScalarKernel>(kernel_name, name, parameters, tid);
    _aux_scalar_storage.addObject(kernel, tid);
  }
}
addScalingVector()
void SystemBase::addScalingVector () inherited
Add the scaling factor vector to the system.
Definition at line 1464 of file SystemBase.C.
{
  addVector("scaling_factors", /*project=*/false, libMesh::ParallelType::GHOSTED);
  _subproblem.hasScalingVector();
}
Referenced by MooseVariableBase::initialSetup().
addTimeIntegrator() [1/3]
virtual void SystemBase::addTimeIntegrator (const std::string & , const std::string & , InputParameters &) inline virtual
Reimplemented from SystemBase.
Definition at line 861 of file SystemBase.h.
  {
  }
addTimeIntegrator() [2/3]
void AuxiliarySystem::addTimeIntegrator (const std::string & type, const std::string & name, InputParameters & parameters) override virtual
Add a time integrator.
Parameters
type Type of the integrator
name The name of the integrator
parameters Integrator params
Reimplemented from SystemBase.
Definition at line 274 of file AuxiliarySystem.C.
{
  parameters.set<SystemBase *>("_sys") = this;
  std::shared_ptr<TimeIntegrator> ti = _factory.create<TimeIntegrator>(type, name, parameters);
  _time_integrator = ti;
}
addTimeIntegrator() [3/3]
virtual void SystemBase::addTimeIntegrator (std::shared_ptr< TimeIntegrator >) inline virtual
Reimplemented from SystemBase.
Definition at line 867 of file SystemBase.h.
{}
addVariable()
void AuxiliarySystem::addVariable (const std::string & var_type, const std::string & var_name, InputParameters & parameters) override virtual
Canonical method for adding a variable.
Parameters
var_type the type of the variable, e.g. MooseVariableScalar
var_name the variable name, e.g. 'u'
params the InputParameters from which to construct the variable
Reimplemented from SystemBase.
Definition at line 219 of file AuxiliarySystem.C.
{
  SystemBase::addVariable(var_type, name, parameters);
  auto fe_type = FEType(Utility::string_to_enum<Order>(parameters.get<MooseEnum>("order")),
                        Utility::string_to_enum<FEFamily>(parameters.get<MooseEnum>("family")));
  if (var_type == "MooseVariableScalar")
    return;
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    if (fe_type.family == LAGRANGE_VEC || fe_type.family == NEDELEC_ONE ||
        fe_type.family == MONOMIAL_VEC || fe_type.family == RAVIART_THOMAS)
    {
      auto * var = _vars[tid].getActualFieldVariable<RealVectorValue>(name);
      if (var)
      {
        if (var->feType().family == LAGRANGE_VEC)
          _nodal_vars[tid].push_back(var);
        else
          _elem_vars[tid].push_back(var);
      }
    }
    else
    {
      MooseVariableBase * var_base = _vars[tid].getVariable(name);
      auto * const var = dynamic_cast<MooseVariableField<Real> *>(var_base);
      if (var)
      {
        if (var->feType().family == LAGRANGE)
          _nodal_vars[tid].push_back(var);
        else
          _elem_vars[tid].push_back(var);
      }
      auto * const avar = dynamic_cast<MooseVariableField<RealEigenVector> *>(var_base);
      if (avar)
      {
        if (avar->feType().family == LAGRANGE)
          _nodal_vars[tid].push_back(avar);
        else
          _elem_vars[tid].push_back(avar);
      }
    }
  }
}
addVariableToCopy()
void SystemBase::addVariableToCopy (const std::string & dest_name, const std::string & source_name, const std::string & timestep) virtual inherited
Add info about variable that will be copied.
Parameters
dest_name Name of the nodal variable being used for copying into (name is from the exodusII file)
source_name Name of the nodal variable being used for copying from (name is from the exodusII file)
timestep Timestep in the file being used
Definition at line 1143 of file SystemBase.C.
{
  _var_to_copy.push_back(VarCopyInfo(dest_name, source_name, timestep));
}
Referenced by CopyNodalVarsAction::act().
addVariableToZeroOnJacobian()
void SystemBase::addVariableToZeroOnJacobian (std::string var_name) virtual inherited
Adds this variable to the list of variables to be zeroed during each Jacobian evaluation.
Parameters
var_name The name of the variable to be zeroed.
Reimplemented in DisplacedSystem.
Definition at line 169 of file SystemBase.C.
{
  _vars_to_be_zeroed_on_jacobian.push_back(var_name);
}
Referenced by ADDGKernel::ADDGKernel(), DisplacedSystem::addVariableToZeroOnJacobian(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), DGKernel::DGKernel(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), NodalBC::NodalBC(), and NodalKernel::NodalKernel().
addVariableToZeroOnResidual()
void SystemBase::addVariableToZeroOnResidual (std::string var_name) virtual inherited
Adds this variable to the list of variables to be zeroed during each residual evaluation.
Parameters
var_name The name of the variable to be zeroed.
Reimplemented in DisplacedSystem.
Definition at line 163 of file SystemBase.C.
{
  _vars_to_be_zeroed_on_residual.push_back(var_name);
}
Referenced by ADDGKernel::ADDGKernel(), DisplacedSystem::addVariableToZeroOnResidual(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), DGKernel::DGKernel(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), NodalBC::NodalBC(), and NodalKernel::NodalKernel().
addVector() [1/2]
NumericVector< Number > & SystemBase::addVector (const std::string & vector_name, const bool project, const ParallelType type) inherited
Adds a solution length vector to the system.
Parameters
vector_name The name of the vector.
project Whether or not to project this vector when doing mesh refinement. If the vector is just going to be recomputed then there is no need to project it.
type What type of parallel vector. This is usually either PARALLEL or GHOSTED. GHOSTED is needed if you are going to be accessing off-processor entries. The ghosting pattern is the same as the solution vector.
Definition at line 597 of file SystemBase.C.
{
  if (hasVector(vector_name))
    return getVector(vector_name);
  NumericVector<Number> & vec = system().add_vector(vector_name, project, type);
  return vec;
}
Referenced by addDotVectors(), NonlinearSystemBase::addDotVectors(), SystemBase::addScalingVector(), PicardSolve::allocateStorage(), SecantSolve::allocateStorage(), SteffensenSolve::allocateStorage(), AStableDirk4::AStableDirk4(), ExplicitTimeIntegrator::ExplicitTimeIntegrator(), NonlinearSystemBase::getResidualNonTimeVector(), NonlinearSystemBase::getResidualTimeVector(), CentralDifference::initialSetup(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), SystemBase::needSolutionState(), NonlinearSystemBase::residualGhosted(), and SystemBase::saveOldSolutions().
addVector() [2/2]
NumericVector< Number > & SystemBase::addVector (TagID tag, const bool project, const ParallelType type) inherited
Adds a solution length vector to the system with the specified TagID.
Parameters
tag_name The name of the tag
project Whether or not to project this vector when doing mesh refinement. If the vector is just going to be recomputed then there is no need to project it.
type What type of parallel vector. This is usually either PARALLEL or GHOSTED. GHOSTED is needed if you are going to be accessing off-processor entries. The ghosting pattern is the same as the solution vector.
Definition at line 607 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot add tagged vector with TagID ",
               tag,
               " in system '",
               name(),
               "' because the tag does not exist in the problem");
  if (hasVector(tag))
  {
    auto & vec = getVector(tag);
    if (type != ParallelType::AUTOMATIC && vec.type() != type)
      mooseError("Cannot add tagged vector '",
                 _subproblem.vectorTagName(tag),
                 "', in system '",
                 name(),
                 "' because a vector with the same name was found with a different parallel type");
    return vec;
  }
  const auto vector_name = _subproblem.vectorTagName(tag);
  NumericVector<Number> & vec = system().add_vector(vector_name, project, type);
  associateVectorToTag(vec, tag);
  return vec;
}
applyScalingFactors()
void SystemBase::applyScalingFactors (const std::vector< Real > & inverse_scaling_factors) inherited
Applies scaling factors to the system's variables.
Parameters
inverse_scaling_factors A vector containing the inverse of each variable's scaling factor, e.g. 1 / scaling_factor
Definition at line 1424 of file SystemBase.C.
{
  for (MooseIndex(_vars) thread = 0; thread < _vars.size(); ++thread)
  {
    auto & field_variables = _vars[thread].fieldVariables();
    for (MooseIndex(field_variables) i = 0; i < field_variables.size(); ++i)
      field_variables[i]->scalingFactor(1. / inverse_scaling_factors[i] *
                                        field_variables[i]->scalingFactor());
    auto offset = field_variables.size();
    auto & scalar_variables = _vars[thread].scalars();
    for (MooseIndex(scalar_variables) i = 0; i < scalar_variables.size(); ++i)
      scalar_variables[i]->scalingFactor(1. / inverse_scaling_factors[offset + i] *
                                         scalar_variables[i]->scalingFactor());
    if (thread == 0 && _verbose)
    {
      _console << "Automatic scaling factors:\n";
      auto original_flags = _console.flags();
      auto original_precision = _console.precision();
      _console.unsetf(std::ios_base::floatfield);
      _console.precision(6);
      for (const auto & field_variable : field_variables)
        _console << "  " << field_variable->name() << ": " << field_variable->scalingFactor()
                 << "\n";
      for (const auto & scalar_variable : scalar_variables)
        _console << "  " << scalar_variable->name() << ": " << scalar_variable->scalingFactor()
                 << "\n";
      _console << "\n" << std::endl;
      // restore state
      _console.flags(original_flags);
      _console.precision(original_precision);
    }
  }
}
Referenced by NonlinearSystemBase::computeScaling().
assignMaxVarNDofsPerElem()
void SystemBase::assignMaxVarNDofsPerElem (std::size_t max_dofs) inline inherited
assign the maximum element dofs
Definition at line 575 of file SystemBase.h.
{ _max_var_n_dofs_per_elem = max_dofs; }
assignMaxVarNDofsPerNode()
void SystemBase::assignMaxVarNDofsPerNode (std::size_t max_dofs) inline inherited
assign the maximum node dofs
Definition at line 580 of file SystemBase.h.
{ _max_var_n_dofs_per_node = max_dofs; }
associateMatrixToTag()
void SystemBase::associateMatrixToTag (SparseMatrix< Number > & matrix, TagID tag) virtual inherited
Associate a matrix to a tag.
Reimplemented in DisplacedSystem.
Definition at line 1025 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag))
    mooseError("Cannot associate matrix to tag ", tag, " because that tag does not exist");
  if (_tagged_matrices.size() < tag + 1)
    _tagged_matrices.resize(tag + 1);
  _tagged_matrices[tag] = &matrix;
}
Referenced by SystemBase::addMatrix(), DisplacedSystem::associateMatrixToTag(), NonlinearSystemBase::computeJacobian(), FEProblemBase::computeJacobianInternal(), FEProblemBase::computeJacobianTag(), and FEProblemBase::computeResidualAndJacobian().
associateVectorToTag()
void SystemBase::associateVectorToTag (NumericVector< Number > & vec, TagID tag) virtual inherited
Associate a vector for a given tag.
Reimplemented in DisplacedSystem.
Definition at line 930 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot associate vector to tag ", tag, " because that tag does not exist");
  if (_tagged_vectors.size() < tag + 1)
    _tagged_vectors.resize(tag + 1);
  _tagged_vectors[tag] = &vec;
}
Referenced by SystemBase::addVector(), DisplacedSystem::associateVectorToTag(), NonlinearSystemBase::computeNodalBCs(), FEProblemBase::computeResidual(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualTag(), NonlinearSystemBase::computeResidualTag(), FEProblemBase::computeResidualType(), and NonlinearSystemBase::setSolution().
augmentSendList()
void SystemBase::augmentSendList (std::vector< dof_id_type > & send_list) virtual inherited
Will modify the send_list to add all of the extra ghosted dofs for this system.
Reimplemented in DisplacedSystem.
Definition at line 441 of file SystemBase.C.
{
  std::set<dof_id_type> & ghosted_elems = _subproblem.ghostedElems();
  DofMap & dof_map = dofMap();
  std::vector<dof_id_type> dof_indices;
  System & sys = system();
  unsigned int sys_num = sys.number();
  unsigned int n_vars = sys.n_vars();
  for (const auto & elem_id : ghosted_elems)
  {
    Elem * elem = _mesh.elemPtr(elem_id);
    if (elem->active())
    {
      dof_map.dof_indices(elem, dof_indices);
      // Only need to ghost it if it's actually not on this processor
      for (const auto & dof : dof_indices)
        if (dof < dof_map.first_dof() || dof >= dof_map.end_dof())
          send_list.push_back(dof);
      // Now add the DoFs from all of the nodes.  This is necessary because of block
      // restricted variables.  A variable might not live _on_ this element but it
      // might live on nodes connected to this element.
      for (unsigned int n = 0; n < elem->n_nodes(); n++)
      {
        Node * node = elem->node_ptr(n);
        // Have to get each variable's dofs
        for (unsigned int v = 0; v < n_vars; v++)
        {
          const Variable & var = sys.variable(v);
          unsigned int var_num = var.number();
          unsigned int n_comp = var.n_components();
          // See if this variable has any dofs at this node
          if (node->n_dofs(sys_num, var_num) > 0)
          {
            // Loop over components of the variable
            for (unsigned int c = 0; c < n_comp; c++)
              send_list.push_back(node->dof_number(sys_num, var_num, c));
          }
        }
      }
    }
  }
}
Referenced by DisplacedSystem::augmentSendList(), and extraSendList().
augmentSparsity()
void AuxiliarySystem::augmentSparsity (SparsityPattern::Graph & sparsity, std::vector< dof_id_type > & n_nz, std::vector< dof_id_type > & n_oz) override virtual
Will modify the sparsity pattern to add logical geometric connections.
Implements SystemBase.
Definition at line 785 of file AuxiliarySystem.C.
{
}
automaticScaling() [1/2]
bool SystemBase::automaticScaling () const inline inherited
Getter for whether we are performing automatic scaling.
Returns
whether we are performing automatic scaling
Definition at line 117 of file SystemBase.h.
{ return _automatic_scaling; }
Referenced by SubProblem::automaticScaling().
automaticScaling() [2/2]
void SystemBase::automaticScaling (bool automatic_scaling) inline inherited
Setter for whether we are performing automatic scaling.
Parameters
automatic_scaling A boolean representing whether we are performing automatic scaling
Definition at line 123 of file SystemBase.h.
{ _automatic_scaling = automatic_scaling; }
clearAllDofIndices()
void SystemBase::clearAllDofIndices () inherited
Clear all dof indices from moose variables.
Definition at line 1519 of file SystemBase.C.
{
  for (auto & var_warehouse : _vars)
    var_warehouse.clearAllDofIndices();
}
Referenced by SubProblem::clearAllDofIndices().
clearScalarVariableCoupleableTags()
void AuxiliarySystem::clearScalarVariableCoupleableTags ()
Definition at line 639 of file AuxiliarySystem.C.
{
  _fe_problem.clearActiveScalarVariableCoupleableMatrixTags(0);
  _fe_problem.clearActiveScalarVariableCoupleableVectorTags(0);
}
Referenced by computeScalarVars().
closeTaggedMatrices()
void SystemBase::closeTaggedMatrices (const std::set< TagID > & tags) inherited
Close all matrices associated the tags.
Definition at line 1009 of file SystemBase.C.
{
  for (auto tag : tags)
    if (hasMatrix(tag))
      getMatrix(tag).close();
}
Referenced by NonlinearSystemBase::computeJacobianInternal(), and NonlinearSystemBase::computeResidualAndJacobianTags().
closeTaggedVector()
void SystemBase::closeTaggedVector (const TagID tag) inherited
Close vector with the given tag.
Definition at line 638 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot close vector with TagID ",
               tag,
               " in system '",
               name(),
               "' because that tag does not exist in the problem");
  else if (!hasVector(tag))
    mooseError("Cannot close vector tag with name '",
               _subproblem.vectorTagName(tag),
               "' in system '",
               name(),
               "' because there is no vector associated with that tag");
  getVector(tag).close();
}
Referenced by SystemBase::closeTaggedVectors().
closeTaggedVectors()
void SystemBase::closeTaggedVectors (const std::set< TagID > & tags) inherited
Close all vectors for given tags.
Definition at line 657 of file SystemBase.C.
{
  for (const auto tag : tags)
    closeTaggedVector(tag);
}
Referenced by NonlinearSystemBase::computeResidualAndJacobianTags(), and NonlinearSystemBase::computeResidualTags().
compute()
void AuxiliarySystem::compute (ExecFlagType type) virtual
Compute auxiliary variables.
Parameters
type Time flag of which variables should be computed
Definition at line 407 of file AuxiliarySystem.C.
{
  // avoid division by dt which might be zero.
  if (_fe_problem.dt() > 0. && _time_integrator)
    _time_integrator->preStep();
  // We need to compute time derivatives every time each kind of the variables is finished, because:
  //
  //  a) the user might want to use the aux variable value somewhere, thus we need to provide the
  //  up-to-date value
  //  b) time integration system works with the whole vectors of solutions, thus we cannot update
  //  only a part of the vector
  //
  if (_vars[0].scalars().size() > 0)
  {
    computeScalarVars(type);
    // compute time derivatives of scalar aux variables _after_ the values were updated
    if (_fe_problem.dt() > 0. && _time_integrator)
      _time_integrator->computeTimeDerivatives();
  }
  if (_vars[0].fieldVariables().size() > 0)
  {
    computeNodalArrayVars(type);
    computeNodalVecVars(type);
    computeNodalVars(type);
    computeMortarNodalVars(type);
    computeElementalArrayVars(type);
    computeElementalVecVars(type);
    computeElementalVars(type);
    // compute time derivatives of nodal aux variables _after_ the values were updated
    if (_fe_problem.dt() > 0. && _time_integrator)
      _time_integrator->computeTimeDerivatives();
  }
  if (_serialized_solution.get())
    serializeSolution();
}
Referenced by setPreviousNewtonSolution().
computeElementalArrayVars()
void AuxiliarySystem::computeElementalArrayVars (ExecFlagType type) protected
Definition at line 778 of file AuxiliarySystem.C.
{
  const MooseObjectWarehouse<ArrayAuxKernel> & elemental = _elemental_array_aux_storage[type];
  computeElementalVarsHelper<ArrayAuxKernel>(elemental);
}
Referenced by compute().
computeElementalVars()
void AuxiliarySystem::computeElementalVars (ExecFlagType type) protected
Definition at line 760 of file AuxiliarySystem.C.
{
  TIME_SECTION("computeElementalVars", 3);
  const MooseObjectWarehouse<AuxKernel> & elemental = _elemental_aux_storage[type];
  computeElementalVarsHelper<AuxKernel>(elemental);
}
Referenced by compute().
computeElementalVarsHelper()
template<typename AuxKernelType > template void AuxiliarySystem::computeElementalVarsHelper< VectorAuxKernel > (const MooseObjectWarehouse< AuxKernelType > & warehouse) protected
Definition at line 826 of file AuxiliarySystem.C.
{
  if (warehouse.hasActiveBlockObjects())
  {
    // Block Elemental AuxKernels
    PARALLEL_TRY
    {
      ConstElemRange & range = *_mesh.getActiveLocalElementRange();
      ComputeElemAuxVarsThread<AuxKernelType> eavt(_fe_problem, warehouse, true);
      try
      {
        Threads::parallel_reduce(range, eavt);
      }
      catch (MooseException & e)
      {
        _fe_problem.setException(e.what());
      }
    }
    PARALLEL_CATCH;
    // We need to make sure we propagate exceptions to all processes before trying to close
    // here, which is a parallel operation
    solution().close();
    _sys.update();
  }
  // Boundary Elemental AuxKernels
  if (warehouse.hasActiveBoundaryObjects())
  {
    TIME_SECTION("computeElementalVecVars", 3);
    PARALLEL_TRY
    {
      ConstBndElemRange & bnd_elems = *_mesh.getBoundaryElementRange();
      ComputeElemAuxBcsThread<AuxKernelType> eabt(_fe_problem, warehouse, true);
      try
      {
        Threads::parallel_reduce(bnd_elems, eabt);
      }
      catch (MooseException & e)
      {
        _fe_problem.setException(e.what());
      }
    }
    PARALLEL_CATCH;
    // We need to make sure we propagate exceptions to all processes before trying to close
    // here, which is a parallel operation
    solution().close();
    _sys.update();
  }
}
computeElementalVecVars()
void AuxiliarySystem::computeElementalVecVars (ExecFlagType type) protected
Definition at line 769 of file AuxiliarySystem.C.
{
  TIME_SECTION("computeElementalVecVars", 3);
  const MooseObjectWarehouse<VectorAuxKernel> & elemental = _elemental_vec_aux_storage[type];
  computeElementalVarsHelper<VectorAuxKernel>(elemental);
}
Referenced by compute().
computeMortarNodalVars()
void AuxiliarySystem::computeMortarNodalVars (ExecFlagType type) protected
Definition at line 712 of file AuxiliarySystem.C.
{
  TIME_SECTION("computeMortarNodalVars", 3);
  const MooseObjectWarehouse<AuxKernel> & mortar_nodal_warehouse = _mortar_nodal_aux_storage[type];
  mooseAssert(!mortar_nodal_warehouse.hasActiveBlockObjects(),
              "We don't allow creation of block restricted mortar nodal aux kernels.");
  if (mortar_nodal_warehouse.hasActiveBoundaryObjects())
  {
    ConstBndNodeRange & bnd_nodes = *_mesh.getBoundaryNodeRange();
    for (const auto & [bnd_id, mortar_nodal_auxes] :
         mortar_nodal_warehouse.getActiveBoundaryObjects())
      for (const auto index : index_range(mortar_nodal_auxes))
      {
        PARALLEL_TRY
        {
          try
          {
            ComputeMortarNodalAuxBndThread<AuxKernel> mnabt(
                _fe_problem, mortar_nodal_warehouse, bnd_id, index);
            Threads::parallel_reduce(bnd_nodes, mnabt);
          }
          catch (MooseException & e)
          {
            _fe_problem.setException(e.what());
          }
          catch (libMesh::LogicError & e)
          {
            _fe_problem.setException("We caught a libMesh::LogicError:" + std::string(e.what()));
          }
          catch (MetaPhysicL::LogicError & e)
          {
            moose::translateMetaPhysicLError(e);
          }
        }
        PARALLEL_CATCH;
        // We need to make sure we propagate exceptions to all processes before trying to close
        // here, which is a parallel operation
        solution().close();
        _sys.update();
      }
  }
}
Referenced by compute().
computeNodalArrayVars()
void AuxiliarySystem::computeNodalArrayVars (ExecFlagType type) protected
Definition at line 705 of file AuxiliarySystem.C.
{
  const MooseObjectWarehouse<ArrayAuxKernel> & nodal = _nodal_array_aux_storage[type];
  computeNodalVarsHelper<ArrayAuxKernel>(nodal);
}
Referenced by compute().
computeNodalVars()
void AuxiliarySystem::computeNodalVars (ExecFlagType type) protected
Definition at line 687 of file AuxiliarySystem.C.
{
  TIME_SECTION("computeNodalVars", 3);
  const MooseObjectWarehouse<AuxKernel> & nodal = _nodal_aux_storage[type];
  computeNodalVarsHelper<AuxKernel>(nodal);
}
Referenced by compute().
computeNodalVarsHelper()
template<typename AuxKernelType > template void AuxiliarySystem::computeNodalVarsHelper< VectorAuxKernel > (const MooseObjectWarehouse< AuxKernelType > & warehouse) protected
Definition at line 881 of file AuxiliarySystem.C.
{
  if (warehouse.hasActiveBlockObjects())
  {
    // Block Nodal AuxKernels
    PARALLEL_TRY
    {
      ConstNodeRange & range = *_mesh.getLocalNodeRange();
      ComputeNodalAuxVarsThread<AuxKernelType> navt(_fe_problem, warehouse);
      Threads::parallel_reduce(range, navt);
      solution().close();
      _sys.update();
    }
    PARALLEL_CATCH;
  }
  if (warehouse.hasActiveBoundaryObjects())
  {
    TIME_SECTION("computeBoundaryObjects", 3);
    // Boundary Nodal AuxKernels
    PARALLEL_TRY
    {
      ConstBndNodeRange & bnd_nodes = *_mesh.getBoundaryNodeRange();
      ComputeNodalAuxBcsThread<AuxKernelType> nabt(_fe_problem, warehouse);
      Threads::parallel_reduce(bnd_nodes, nabt);
      solution().close();
      _sys.update();
    }
    PARALLEL_CATCH;
  }
}
computeNodalVecVars()
void AuxiliarySystem::computeNodalVecVars (ExecFlagType type) protected
Definition at line 696 of file AuxiliarySystem.C.
{
  TIME_SECTION("computeNodalVecVars", 3);
  const MooseObjectWarehouse<VectorAuxKernel> & nodal = _nodal_vec_aux_storage[type];
  computeNodalVarsHelper<VectorAuxKernel>(nodal);
}
Referenced by compute().
computeScalarVars()
void AuxiliarySystem::computeScalarVars (ExecFlagType type) protected
Definition at line 646 of file AuxiliarySystem.C.
{
  setScalarVariableCoupleableTags(type);
  // Reference to the current storage container
  const MooseObjectWarehouse<AuxScalarKernel> & storage = _aux_scalar_storage[type];
  if (storage.hasActiveObjects())
  {
    TIME_SECTION("computeScalarVars", 1);
    PARALLEL_TRY
    {
      // FIXME: run multi-threaded
      THREAD_ID tid = 0;
      if (storage.hasActiveObjects())
      {
        _fe_problem.reinitScalars(tid);
        const std::vector<std::shared_ptr<AuxScalarKernel>> & objects =
            storage.getActiveObjects(tid);
        // Call compute() method on all active AuxScalarKernel objects
        for (const auto & obj : objects)
          obj->compute();
        const std::vector<MooseVariableScalar *> & scalar_vars = getScalarVariables(tid);
        for (const auto & var : scalar_vars)
          var->insert(solution());
      }
    }
    PARALLEL_CATCH;
    solution().close();
    _sys.update();
  }
  clearScalarVariableCoupleableTags();
}
Referenced by compute().
computeVariables()
virtual void SystemBase::computeVariables (const NumericVector< Number > &) inline virtual inherited
Definition at line 852 of file SystemBase.h.
{}
computingScalingJacobian()
bool SystemBase::computingScalingJacobian () const inherited
Whether we are computing an initial Jacobian for automatic variable scaling.
Definition at line 1471 of file SystemBase.C.
{
  return _subproblem.computingScalingJacobian();
}
Referenced by Assembly::addJacobianBlock(), Assembly::addJacobianBlockNonlocal(), Assembly::addJacobianNeighbor(), Assembly::cacheJacobianBlock(), EigenKernel::computeJacobian(), Kernel::computeJacobian(), VectorKernel::computeJacobian(), and FEProblemBase::computeJacobianTags().
copyOldSolutions()
void SystemBase::copyOldSolutions () virtual inherited
Shifts the solutions backwards in time.
Definition at line 1254 of file SystemBase.C.
{
  const auto states =
      _solution_states[static_cast<unsigned short>(Moose::SolutionIterationType::Time)].size();
  if (states > 1)
    for (unsigned int i = states - 1; i > 0; --i)
      solutionState(i) = solutionState(i - 1);
  if (solutionUDotOld())
    *solutionUDotOld() = *solutionUDot();
  if (solutionUDotDotOld())
    *solutionUDotDotOld() = *solutionUDotDot();
  if (solutionPreviousNewton())
    *solutionPreviousNewton() = *currentSolution();
}
Referenced by EigenExecutionerBase::inversePowerIteration().
copySolutionsBackwards()
void SystemBase::copySolutionsBackwards () virtual inherited
Copy current solution into old and older.
Definition at line 1227 of file SystemBase.C.
{
  system().update();
  // Copying the solutions backward so the current solution will become the old, and the old will
  // become older. The same applies to the nonlinear iterates.
  for (const auto iteration_index : index_range(_solution_states))
  {
    const auto states = _solution_states[iteration_index].size();
    if (states > 1)
      for (unsigned int i = states - 1; i > 0; --i)
        solutionState(i, Moose::SolutionIterationType(iteration_index)) =
            solutionState(i - 1, Moose::SolutionIterationType(iteration_index));
  }
  if (solutionUDotOld())
    *solutionUDotOld() = *solutionUDot();
  if (solutionUDotDotOld())
    *solutionUDotDotOld() = *solutionUDotDot();
  if (solutionPreviousNewton())
    *solutionPreviousNewton() = *currentSolution();
}
copyVars()
void SystemBase::copyVars (ExodusII_IO & io) inherited
Definition at line 1151 of file SystemBase.C.
{
  int n_steps = io.get_num_time_steps();
  bool did_copy = false;
  for (const auto & vci : _var_to_copy)
  {
    int timestep = -1;
    if (vci._timestep == "LATEST")
      // Use the last time step in the file from which to retrieve the solution
      timestep = n_steps;
    else
    {
      timestep = MooseUtils::convert<int>(vci._timestep);
      if (timestep > n_steps)
        mooseError("Invalid value passed as \"initial_from_file_timestep\". Expected \"LATEST\" or "
                   "a valid integer between 1 and ",
                   n_steps,
                   " inclusive, received ",
                   vci._timestep);
    }
    did_copy = true;
    if (hasVariable(vci._dest_name))
    {
      const auto & var = getVariable(0, vci._dest_name);
      if (var.isArray())
      {
        const auto & array_var = getFieldVariable<RealEigenVector>(0, vci._dest_name);
        for (MooseIndex(var.count()) i = 0; i < var.count(); ++i)
        {
          const auto exodus_var = _subproblem.arrayVariableComponent(vci._source_name, i);
          const auto system_var = array_var.componentName(i);
          if (var.isNodal())
            io.copy_nodal_solution(system(), exodus_var, system_var, timestep);
          else
            io.copy_elemental_solution(system(), exodus_var, system_var, timestep);
        }
      }
      else
      {
        if (var.isNodal())
          io.copy_nodal_solution(system(), vci._dest_name, vci._source_name, timestep);
        else
          io.copy_elemental_solution(system(), vci._dest_name, vci._source_name, timestep);
      }
    }
    else if (hasScalarVariable(vci._dest_name))
      io.copy_scalar_solution(system(), {vci._dest_name}, {vci._source_name}, timestep);
    else
      mooseError("Unrecognized variable ", vci._dest_name, " in variables to copy.");
  }
  if (did_copy)
    solution().close();
}
currentSolution()
const NumericVector< Number > *const & AuxiliarySystem::currentSolution () const inline override virtual
The solution vector that is currently being operated on.
This is typically a ghosted vector that comes in from the Nonlinear solver.
Implements SystemBase.
Definition at line 99 of file AuxiliarySystem.h.
  {
    return _current_solution;
  }
Referenced by FlagElementsThread::onElement(), AB2PredictorCorrector::step(), and DisplacedProblem::syncSolutions().
customSetup()
void AuxiliarySystem::customSetup (const ExecFlagType & exec_type) override virtual
Reimplemented from SystemBase.
Definition at line 134 of file AuxiliarySystem.C.
{
  SystemBase::customSetup(exec_type);
  for (unsigned int tid = 0; tid < libMesh::n_threads(); tid++)
  {
    _aux_scalar_storage.customSetup(exec_type, tid);
    _nodal_aux_storage.customSetup(exec_type, tid);
    _mortar_nodal_aux_storage.customSetup(exec_type, tid);
    _nodal_vec_aux_storage.customSetup(exec_type, tid);
    _nodal_array_aux_storage.customSetup(exec_type, tid);
    _elemental_aux_storage.customSetup(exec_type, tid);
    _elemental_vec_aux_storage.customSetup(exec_type, tid);
    _elemental_array_aux_storage.customSetup(exec_type, tid);
  }
}
deactiveAllMatrixTags()
void SystemBase::deactiveAllMatrixTags () virtual inherited
Make matrices inactive.
Definition at line 1092 of file SystemBase.C.
{
  auto num_matrix_tags = _subproblem.numMatrixTags();
  _matrix_tag_active_flags.resize(num_matrix_tags);
  for (decltype(num_matrix_tags) tag = 0; tag < num_matrix_tags; tag++)
    _matrix_tag_active_flags[tag] = false;
}
Referenced by NonlinearSystemBase::computeResidualTags(), and NonlinearSystemBase::setInitialSolution().
deactiveMatrixTag()
void SystemBase::deactiveMatrixTag (TagID tag) virtual inherited
deactive a matrix for tag
Definition at line 1080 of file SystemBase.C.
{
  mooseAssert(_subproblem.matrixTagExists(tag),
              "Cannot deactivate Matrix with matrix_tag : " << tag << "that does not exist");
  if (_matrix_tag_active_flags.size() < tag + 1)
    _matrix_tag_active_flags.resize(tag + 1);
  _matrix_tag_active_flags[tag] = false;
}
defaultMatrixTags()
virtual std::set< TagID > SystemBase::defaultMatrixTags () const inline virtual inherited
Get the default matrix tags associted with this system.
Reimplemented in DisplacedSystem, and NonlinearEigenSystem.
Definition at line 287 of file SystemBase.h.
{ return {systemMatrixTag()}; }
Referenced by DisplacedSystem::defaultMatrixTags(), NonlinearEigenSystem::defaultMatrixTags(), and SystemBase::disassociateDefaultMatrixTags().
defaultVectorTags()
virtual std::set< TagID > SystemBase::defaultVectorTags () const inline virtual inherited
Get the default vector tags associated with this system.
Reimplemented in DisplacedSystem, and NonlinearEigenSystem.
Definition at line 280 of file SystemBase.h.
  {
    return {timeVectorTag(), nonTimeVectorTag(), residualVectorTag()};
  }
Referenced by DisplacedSystem::defaultVectorTags(), NonlinearEigenSystem::defaultVectorTags(), and SystemBase::disassociateDefaultVectorTags().
disassociateDefaultMatrixTags()
void SystemBase::disassociateDefaultMatrixTags () virtual inherited
Disassociate the matrices associated with the default matrix tags of this system.
Reimplemented in DisplacedSystem.
Definition at line 1059 of file SystemBase.C.
{
  const auto tags = defaultMatrixTags();
  for (const auto tag : tags)
    if (_subproblem.matrixTagExists(tag))
      disassociateMatrixFromTag(tag);
}
Referenced by DisplacedSystem::disassociateDefaultMatrixTags().
disassociateDefaultVectorTags()
void SystemBase::disassociateDefaultVectorTags () virtual inherited
Disassociate the vectors associated with the default vector tags of this system.
Reimplemented in DisplacedSystem.
Definition at line 964 of file SystemBase.C.
{
  const auto tags = defaultVectorTags();
  for (const auto tag : tags)
    if (_subproblem.vectorTagExists(tag))
      disassociateVectorFromTag(tag);
}
Referenced by DisplacedSystem::disassociateDefaultVectorTags().
disassociateMatrixFromTag() [1/2]
void SystemBase::disassociateMatrixFromTag (SparseMatrix< Number > & matrix, TagID tag) virtual inherited
Disassociate a matrix from a tag.
Reimplemented in DisplacedSystem.
Definition at line 1037 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag))
    mooseError("Cannot disassociate matrix from tag ", tag, " because that tag does not exist");
  if (hasMatrix(tag) && &getMatrix(tag) != &matrix)
    mooseError("You can not disassociate a matrix from a tag which it was not associated to");
  disassociateMatrixFromTag(tag);
}
Referenced by NonlinearSystemBase::computeJacobian(), FEProblemBase::computeJacobianInternal(), FEProblemBase::computeJacobianTag(), FEProblemBase::computeResidualAndJacobian(), SystemBase::disassociateDefaultMatrixTags(), SystemBase::disassociateMatrixFromTag(), and DisplacedSystem::disassociateMatrixFromTag().
disassociateMatrixFromTag() [2/2]
void SystemBase::disassociateMatrixFromTag (TagID tag) virtual inherited
Disassociate any matrix that is associated with a given tag.
Reimplemented in DisplacedSystem.
Definition at line 1048 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag))
    mooseError("Cannot disassociate matrix from tag ", tag, " because that tag does not exist");
  if (_tagged_matrices.size() < tag + 1)
    _tagged_matrices.resize(tag + 1);
  _tagged_matrices[tag] = nullptr;
}
disassociateVectorFromTag() [1/2]
void SystemBase::disassociateVectorFromTag (NumericVector< Number > & vec, TagID tag) virtual inherited
Disassociate a given vector from a given tag.
Reimplemented in DisplacedSystem.
Definition at line 942 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot disassociate vector from tag ", tag, " because that tag does not exist");
  if (hasVector(tag) && &getVector(tag) != &vec)
    mooseError("You can not disassociate a vector from a tag which it was not associated to");
  disassociateVectorFromTag(tag);
}
Referenced by NonlinearSystemBase::computeNodalBCs(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualTag(), NonlinearSystemBase::computeResidualTag(), FEProblemBase::computeResidualType(), SystemBase::disassociateDefaultVectorTags(), SystemBase::disassociateVectorFromTag(), DisplacedSystem::disassociateVectorFromTag(), and CentralDifference::initialSetup().
disassociateVectorFromTag() [2/2]
void SystemBase::disassociateVectorFromTag (TagID tag) virtual inherited
Disassociate any vector that is associated with a given tag.
Reimplemented in DisplacedSystem.
Definition at line 953 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot disassociate vector from tag ", tag, " because that tag does not exist");
  if (_tagged_vectors.size() < tag + 1)
    _tagged_vectors.resize(tag + 1);
  _tagged_vectors[tag] = nullptr;
}
dofMap() [1/2]
DofMap & SystemBase::dofMap () virtual inherited
Gets writeable reference to the dof map.
Definition at line 1131 of file SystemBase.C.
{
  return system().get_dof_map();
}
Referenced by NonlinearSystemBase::assembleScalingVector(), MooseApp::attachRelationshipManagers(), SystemBase::augmentSendList(), NonlinearSystemBase::augmentSparsity(), NonlinearSystemBase::computeScaling(), NonlinearSystemBase::findImplicitGeometricCouplingEntries(), Adaptivity::init(), ActivateElementsUserObjectBase::initSolutions(), PNGOutput::makeMeshFunc(), GhostingUserObject::meshChanged(), Exodus::outputScalarVariables(), Nemesis::outputScalarVariables(), TableOutput::outputScalarVariables(), and ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes().
dofMap() [2/2]
const DofMap & SystemBase::dofMap () const virtual inherited
Gets const reference to the dof map.
Definition at line 1137 of file SystemBase.C.
{
  return system().get_dof_map();
}
duDotDotDu() [1/2]
virtual Number & SystemBase::duDotDotDu () inline virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 223 of file SystemBase.h.
{ return _du_dotdot_du; }
Referenced by DisplacedSystem::duDotDotDu(), and MooseVariableScalar::reinit().
duDotDotDu() [2/2]
virtual const Number & SystemBase::duDotDotDu () const inline virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 225 of file SystemBase.h.
{ return _du_dotdot_du; }
duDotDu() [1/2]
virtual Number & SystemBase::duDotDu () inline virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 222 of file SystemBase.h.
{ return _du_dot_du; }
Referenced by DisplacedSystem::duDotDu(), and MooseVariableScalar::reinit().
duDotDu() [2/2]
virtual const Number & SystemBase::duDotDu () const inline virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 224 of file SystemBase.h.
{ return _du_dot_du; }
elemArrayAuxWarehouse()
const ExecuteMooseObjectWarehouse< ArrayAuxKernel > & AuxiliarySystem::elemArrayAuxWarehouse () const inline
Definition at line 271 of file AuxiliarySystem.h.
{
  return _elemental_array_aux_storage;
}
elemAuxWarehouse()
const ExecuteMooseObjectWarehouse< AuxKernel > & AuxiliarySystem::elemAuxWarehouse () const inline
Definition at line 259 of file AuxiliarySystem.h.
{
  return _elemental_aux_storage;
}
elemVectorAuxWarehouse()
const ExecuteMooseObjectWarehouse< VectorAuxKernel > & AuxiliarySystem::elemVectorAuxWarehouse () const inline
Definition at line 265 of file AuxiliarySystem.h.
{
  return _elemental_vec_aux_storage;
}
flushTaggedMatrices()
void SystemBase::flushTaggedMatrices (const std::set< TagID > & tags) inherited
flushes all matrices associated to tags.
Flush assembles the matrix but doesn't shrink memory allocation
Definition at line 1017 of file SystemBase.C.
{
  for (auto tag : tags)
    if (hasMatrix(tag))
      getMatrix(tag).flush();
}
getActualFieldVariable() [1/2]
template<typename T > template MooseVariableField< RealEigenVector > & SystemBase::getActualFieldVariable< RealEigenVector > (THREAD_ID tid, const std::string & var_name) inherited
Returns a field variable pointer - this includes finite volume variables.
Definition at line 107 of file SystemBase.C.
{
  return *_vars[tid].getActualFieldVariable<T>(var_name);
}
Referenced by BoundsAuxBase::BoundsAuxBase(), Assembly::copyFaceShapes(), Assembly::copyNeighborShapes(), and Assembly::copyShapes().
getActualFieldVariable() [2/2]
template<typename T > template MooseVariableField< RealEigenVector > & SystemBase::getActualFieldVariable< RealEigenVector > (THREAD_ID tid, unsigned int var_number) inherited
Returns a field variable pointer - this includes finite volume variables.
Definition at line 128 of file SystemBase.C.
{
  return *_vars[tid].getActualFieldVariable<T>(var_number);
}
getDependObjects() [1/2]
std::set< std::string > AuxiliarySystem::getDependObjects ()
Definition at line 534 of file AuxiliarySystem.C.
{
  std::set<std::string> depend_objects;
  // Elemental AuxKernels
  {
    const std::vector<std::shared_ptr<AuxKernel>> & auxs =
        _elemental_aux_storage.getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  // Elemental VectorAuxKernels
  {
    const std::vector<std::shared_ptr<VectorAuxKernel>> & auxs =
        _elemental_vec_aux_storage.getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  // Elemental ArrayAuxKernels
  {
    const std::vector<std::shared_ptr<ArrayAuxKernel>> & auxs =
        _elemental_array_aux_storage.getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  // Nodal AuxKernels
  {
    const std::vector<std::shared_ptr<AuxKernel>> & auxs = _nodal_aux_storage.getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  // Mortar Nodal AuxKernels
  {
    const std::vector<std::shared_ptr<AuxKernel>> & auxs =
        _mortar_nodal_aux_storage.getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  // Nodal VectorAuxKernels
  {
    const std::vector<std::shared_ptr<VectorAuxKernel>> & auxs =
        _nodal_vec_aux_storage.getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  // Nodal ArrayAuxKernels
  {
    const std::vector<std::shared_ptr<ArrayAuxKernel>> & auxs =
        _nodal_array_aux_storage.getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  return depend_objects;
}
getDependObjects() [2/2]
std::set< std::string > AuxiliarySystem::getDependObjects (ExecFlagType type)
Get a list of dependent UserObjects for this exec type.
Parameters
type Execution flag type
Returns
a set of dependent user objects
Definition at line 449 of file AuxiliarySystem.C.
{
  std::set<std::string> depend_objects;
  // Elemental AuxKernels
  {
    const std::vector<std::shared_ptr<AuxKernel>> & auxs =
        _elemental_aux_storage[type].getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  // Elemental VectorAuxKernels
  {
    const std::vector<std::shared_ptr<VectorAuxKernel>> & auxs =
        _elemental_vec_aux_storage[type].getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  // Elemental ArrayAuxKernels
  {
    const std::vector<std::shared_ptr<ArrayAuxKernel>> & auxs =
        _elemental_array_aux_storage[type].getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  // Nodal AuxKernels
  {
    const std::vector<std::shared_ptr<AuxKernel>> & auxs =
        _nodal_aux_storage[type].getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  // Mortar Nodal AuxKernels
  {
    const std::vector<std::shared_ptr<AuxKernel>> & auxs =
        _mortar_nodal_aux_storage[type].getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  // Nodal VectorAuxKernels
  {
    const std::vector<std::shared_ptr<VectorAuxKernel>> & auxs =
        _nodal_vec_aux_storage[type].getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  // Nodal ArrayAuxKernels
  {
    const std::vector<std::shared_ptr<ArrayAuxKernel>> & auxs =
        _nodal_array_aux_storage[type].getActiveObjects();
    for (const auto & aux : auxs)
    {
      const std::set<UserObjectName> & uo = aux->getDependObjects();
      depend_objects.insert(uo.begin(), uo.end());
    }
  }
  return depend_objects;
}
Referenced by groupUserObjects().
getFieldVariable() [1/2]
template<typename T > template MooseVariableFE< RealEigenVector > & SystemBase::getFieldVariable< RealEigenVector > (THREAD_ID tid, const std::string & var_name) inherited
Gets a reference to a variable of with specified name.
This excludes and cannot return finite volume variables.
Parameters
tid Thread id
var_name variable name
Returns
reference the variable (class)
Definition at line 100 of file SystemBase.C.
{
  return *_vars[tid].getFieldVariable<T>(var_name);
}
Referenced by Marker::getMarkerValue().
getFieldVariable() [2/2]
template<typename T > template MooseVariableFE< RealEigenVector > & SystemBase::getFieldVariable< RealEigenVector > (THREAD_ID tid, unsigned int var_number) inherited
Gets a reference to a variable with specified number.
This excludes and cannot return finite volume variables.
Parameters
tid Thread id
var_number libMesh variable number
Returns
reference the variable (class)
Definition at line 121 of file SystemBase.C.
{
  return *_vars[tid].getFieldVariable<T>(var_number);
}
getFVVariable()
template<typename T > template MooseVariableFV< Real > & SystemBase::getFVVariable< Real > (THREAD_ID tid, const std::string & var_name) inherited
Return a finite volume variable.
Definition at line 114 of file SystemBase.C.
{
  return *_vars[tid].getFVVariable<T>(var_name);
}
getMatrix() [1/2]
SparseMatrix< Number > & SystemBase::getMatrix (TagID tag) virtual inherited
Get a raw SparseMatrix.
Reimplemented in DisplacedSystem.
Definition at line 973 of file SystemBase.C.
{
  if (!hasMatrix(tag))
  {
    if (!_subproblem.matrixTagExists(tag))
      mooseError("Cannot retreive matrix with tag ", tag, " because that tag does not exist");
    else
      mooseError("Cannot retreive matrix with tag ",
                 tag,
                 " in system '",
                 name(),
                 "'\nbecause a matrix has not been associated with that tag.");
  }
  return *_tagged_matrices[tag];
}
Referenced by Assembly::addCachedJacobian(), NonlinearSystemBase::addImplicitGeometricCouplingEntries(), Assembly::addJacobianCoupledVarPair(), Assembly::addJacobianLowerD(), Assembly::addJacobianNeighbor(), Assembly::addJacobianNeighborLowerD(), Assembly::addJacobianNonlocal(), SystemBase::addMatrix(), SystemBase::closeTaggedMatrices(), NonlinearSystemBase::computeJacobianInternal(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::constraintJacobians(), SystemBase::disassociateMatrixFromTag(), NonlinearSystemBase::enforceNodalConstraintsJacobian(), SystemBase::flushTaggedMatrices(), DisplacedSystem::getMatrix(), MooseVariableScalar::reinit(), Assembly::setCachedJacobian(), and Assembly::zeroCachedJacobian().
getMatrix() [2/2]
const SparseMatrix< Number > & SystemBase::getMatrix (TagID tag) const virtual inherited
Get a raw SparseMatrix.
Reimplemented in DisplacedSystem.
Definition at line 991 of file SystemBase.C.
{
  if (!hasMatrix(tag))
  {
    if (!_subproblem.matrixTagExists(tag))
      mooseError("Cannot retreive matrix with tag ", tag, " because that tag does not exist");
    else
      mooseError("Cannot retreive matrix with tag ",
                 tag,
                 " in system '",
                 name(),
                 "'\nbecause a matrix has not been associated with that tag.");
  }
  return *_tagged_matrices[tag];
}
getMaxVariableNumber()
unsigned int SystemBase::getMaxVariableNumber () const inline inherited
Returns the maximum number of all variables on the system.
Definition at line 850 of file SystemBase.h.
{ return _max_var_number; }
getMaxVarNDofsPerElem()
std::size_t SystemBase::getMaxVarNDofsPerElem () const inline inherited
Gets the maximum number of dofs used by any one variable on any one element.
Returns
The max
Definition at line 563 of file SystemBase.h.
{ return _max_var_n_dofs_per_elem; }
Referenced by Moose::globalDofIndexToDerivative().
getMaxVarNDofsPerNode()
std::size_t SystemBase::getMaxVarNDofsPerNode () const inline inherited
Gets the maximum number of dofs used by any one variable on any one node.
Returns
The max
Definition at line 570 of file SystemBase.h.
{ return _max_var_n_dofs_per_node; }
getMinQuadratureOrder()
Order AuxiliarySystem::getMinQuadratureOrder () override virtual
Get the minimum quadrature order for evaluating elemental auxiliary variables.
Reimplemented from SystemBase.
Definition at line 793 of file AuxiliarySystem.C.
{
  Order order = CONSTANT;
  std::vector<MooseVariableFEBase *> vars = _vars[0].fieldVariables();
  for (const auto & var : vars)
  {
    if (!var->isNodal()) // nodal aux variables do not need quadrature
    {
      FEType fe_type = var->feType();
      if (fe_type.default_quadrature_order() > order)
        order = fe_type.default_quadrature_order();
    }
  }
  return order;
}
getScalarVariable() [1/2]
MooseVariableScalar & SystemBase::getScalarVariable (THREAD_ID tid, const std::string & var_name) const virtual inherited
Gets a reference to a scalar variable with specified number.
Parameters
tid Thread id
var_name A string which is the name of the variable to get.
Returns
reference the variable (class)
Definition at line 134 of file SystemBase.C.
{
  MooseVariableScalar * var = dynamic_cast<MooseVariableScalar *>(_vars[tid].getVariable(var_name));
  if (!var)
    mooseError("Scalar variable '" + var_name + "' does not exist in this system");
  return *var;
}
Referenced by Assembly::addJacobianOffDiagScalar(), MortarScalarBase::computeOffDiagJacobianScalar(), ArrayIntegratedBC::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), ArrayKernel::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), DMMooseSetVariables(), Assembly::init(), ReferenceResidualProblem::initialSetup(), and NonlinearSystemBase::setupScalingData().
getScalarVariable() [2/2]
MooseVariableScalar & SystemBase::getScalarVariable (THREAD_ID tid, unsigned int var_number) const virtual inherited
Gets a reference to a variable with specified number.
Parameters
tid Thread id
var_number libMesh variable number
Returns
reference the variable (class)
Definition at line 143 of file SystemBase.C.
{
  MooseVariableScalar * var =
      dynamic_cast<MooseVariableScalar *>(_vars[tid].getVariable(var_number));
  if (!var)
    mooseError("variable #" + Moose::stringify(var_number) + " does not exist in this system");
  return *var;
}
getScalarVariables()
const std::vector< MooseVariableScalar * > & SystemBase::getScalarVariables (THREAD_ID tid) inline inherited
Definition at line 737 of file SystemBase.h.
  {
    return _vars[tid].scalars();
  }
Referenced by Assembly::addResidualScalar(), ODEKernel::computeJacobian(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), computeScalarVars(), Assembly::init(), SystemBase::initSolutionState(), NonlinearThread::onElement(), Assembly::prepareOffDiagScalar(), and Assembly::prepareScalar().
getSharedTimeIntegrator()
std::shared_ptr< TimeIntegrator > SystemBase::getSharedTimeIntegrator () inline inherited
Definition at line 872 of file SystemBase.h.
{ return _time_integrator; }
Referenced by DisplacedProblem::DisplacedProblem().
getStandardFieldVariableNames()
void SystemBase::getStandardFieldVariableNames (std::vector< VariableName > & std_field_variables) const inherited
getSubdomainsForVar() [1/2]
const std::set< SubdomainID > & SystemBase::getSubdomainsForVar (const std::string & var_name) const inline inherited
Get the block where a variable of this system is defined.
Parameters
var_name The name of the variable
Returns
the set of subdomain ids where the variable is active (defined)
Definition at line 753 of file SystemBase.h.
  {
    return getSubdomainsForVar(getVariable(0, var_name).number());
  }
getSubdomainsForVar() [2/2]
const std::set< SubdomainID > & SystemBase::getSubdomainsForVar (unsigned int var_number) const inline inherited
Definition at line 742 of file SystemBase.h.
  {
    return _var_map.at(var_number);
  }
Referenced by NonlinearSystemBase::checkKernelCoverage(), and SystemBase::getSubdomainsForVar().
getTimeIntegrator() [1/2]
TimeIntegrator * SystemBase::getTimeIntegrator () inline inherited
Definition at line 869 of file SystemBase.h.
{ return _time_integrator.get(); }
Referenced by Transient::endStep(), AB2PredictorCorrector::estimateTimeError(), Transient::getTimeIntegratorName(), MooseVariableData< OutputType >::MooseVariableData(), and Transient::preExecute().
getTimeIntegrator() [2/2]
const TimeIntegrator * SystemBase::getTimeIntegrator () const inline inherited
Definition at line 870 of file SystemBase.h.
{ return _time_integrator.get(); }
getVariable() [1/2]
MooseVariableFieldBase & SystemBase::getVariable (THREAD_ID tid, const std::string & var_name) const inherited
Gets a reference to a variable of with specified name.
Parameters
tid Thread id
var_name variable name
Returns
reference the variable (class)
Definition at line 79 of file SystemBase.C.
{
  MooseVariableFieldBase * var =
      dynamic_cast<MooseVariableFieldBase *>(_vars[tid].getVariable(var_name));
  if (!var)
    mooseError("Variable '", var_name, "' does not exist in this system");
  return *var;
}
Referenced by AdaptivityAction::act(), Assembly::addJacobianBlock(), Assembly::addJacobianBlockNonlocal(), FEProblemBase::addJacobianBlockTags(), Assembly::addJacobianNeighbor(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), Assembly::copyFaceShapes(), Assembly::copyNeighborShapes(), Assembly::copyShapes(), SystemBase::copyVars(), DMMooseSetVariables(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), NodeElemConstraint::getConnectedDofIndices(), NodeFaceConstraint::getConnectedDofIndices(), SystemBase::getSubdomainsForVar(), ResidualObject::getVariable(), Assembly::init(), NodalNormalsPreprocessor::initialize(), ReferenceResidualProblem::initialSetup(), Assembly::initNonlocalCoupling(), PNGOutput::makeMeshFunc(), FEProblemBase::prepare(), Assembly::prepareBlock(), Assembly::prepareBlockNonlocal(), AddPeriodicBCAction::setPeriodicVars(), NonlinearSystemBase::setupScalingData(), UpdateErrorVectorsThread::UpdateErrorVectorsThread(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
getVariable() [2/2]
MooseVariableFieldBase & SystemBase::getVariable (THREAD_ID tid, unsigned int var_number) const inherited
Gets a reference to a variable with specified number.
Parameters
tid Thread id
var_number libMesh variable number
Returns
reference the variable (class)
Definition at line 89 of file SystemBase.C.
{
  if (var_number < _numbered_vars[tid].size())
    if (_numbered_vars[tid][var_number])
      return *_numbered_vars[tid][var_number];
  mooseError("Variable #", Moose::stringify(var_number), " does not exist in this system");
}
getVariableBlocks()
const std::set< SubdomainID > * SystemBase::getVariableBlocks (unsigned int var_number) virtual inherited
Get the block where a variable of this system is defined.
Parameters
var_number The number of the variable
Returns
the set of subdomain ids where the variable is active (defined)
Definition at line 153 of file SystemBase.C.
{
  mooseAssert(_var_map.find(var_number) != _var_map.end(), "Variable does not exist.");
  if (_var_map[var_number].empty())
    return nullptr;
  else
    return &_var_map[var_number];
}
Referenced by PhysicsBasedPreconditioner::addSystem().
getVariableGlobalDoFs()
const std::vector< dof_id_type > & SystemBase::getVariableGlobalDoFs () inline inherited
Get the global dof indices of a variable, this needs to be called after the indices have been set by setVariableGlobalDoFs
Definition at line 825 of file SystemBase.h.
{ return _var_all_dof_indices; }
getVariableNames()
const std::vector< VariableName > & SystemBase::getVariableNames () const inline inherited
Definition at line 843 of file SystemBase.h.
{ return _vars[0].names(); }
Referenced by MooseEigenSystem::buildSystemDoFIndices(), NonlinearSystemBase::checkKernelCoverage(), SystemBase::hasVariable(), SystemBase::isArrayVariable(), AddPeriodicBCAction::setPeriodicVars(), and SingleMatrixPreconditioner::SingleMatrixPreconditioner().
getVariables()
const std::vector< MooseVariableFieldBase * > & SystemBase::getVariables (THREAD_ID tid) inline inherited
Definition at line 732 of file SystemBase.h.
  {
    return _vars[tid].fieldVariables();
  }
Referenced by Assembly::addJacobianOffDiagScalar(), Assembly::addResidual(), Assembly::addResidualLower(), Assembly::addResidualNeighbor(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), Assembly::cacheResidual(), Assembly::cacheResidualLower(), Assembly::cacheResidualNeighbor(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), Assembly::init(), Assembly::initNonlocalCoupling(), SystemBase::initSolutionState(), Assembly::prepareLowerD(), Assembly::prepareNeighbor(), Assembly::prepareOffDiagScalar(), Assembly::prepareResidual(), Assembly::setResidual(), and Assembly::setResidualNeighbor().
getVector() [1/4]
NumericVector< Number > & SystemBase::getVector (const std::string & name) virtual inherited
Get a raw NumericVector by name.
Get a raw NumericVector with the given name.
Reimplemented in DisplacedSystem.
Definition at line 882 of file SystemBase.C.
{
  return system().get_vector(name);
}
Referenced by Assembly::addCachedResiduals(), Assembly::addResidual(), Assembly::addResidualLower(), Assembly::addResidualNeighbor(), Assembly::addResidualScalar(), SystemBase::addVector(), NonlinearSystemBase::assembleScalingVector(), SystemBase::closeTaggedVector(), FEProblemBase::computeBounds(), FEProblemBase::computeNearNullSpace(), FEProblemBase::computeNullSpace(), NonlinearSystemBase::computeResidualAndJacobianTags(), NonlinearSystemBase::computeResidualTags(), CentralDifference::computeTimeDerivatives(), FEProblemBase::computeTransposeNullSpace(), SystemBase::disassociateVectorFromTag(), DisplacedSystem::getVector(), Assembly::hasScalingVector(), SystemBase::needSolutionState(), ReferenceResidualProblem::ReferenceResidualProblem(), MooseVariableScalar::reinit(), PicardSolve::saveVariableValues(), SecantSolve::saveVariableValues(), SteffensenSolve::saveVariableValues(), NonlinearSystemBase::setPreviousNewtonSolution(), TaggingInterface::setResidual(), SystemBase::solutionPreviousNewton(), SystemBase::solutionState(), MultiAppDofCopyTransfer::transfer(), PicardSolve::transformVariables(), SecantSolve::transformVariables(), SteffensenSolve::transformVariables(), and SystemBase::zeroTaggedVector().
getVector() [2/4]
const NumericVector< Number > & SystemBase::getVector (const std::string & name) const virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 888 of file SystemBase.C.
{
  return system().get_vector(name);
}
getVector() [3/4]
NumericVector< Number > & SystemBase::getVector (TagID tag) virtual inherited
Get a raw NumericVector by tag.
Reimplemented in DisplacedSystem.
Definition at line 894 of file SystemBase.C.
{
  if (!hasVector(tag))
  {
    if (!_subproblem.vectorTagExists(tag))
      mooseError("Cannot retreive vector with tag ", tag, " because that tag does not exist");
    else
      mooseError("Cannot retreive vector with tag ",
                 tag,
                 " in system '",
                 name(),
                 "'\nbecause a vector has not been associated with that tag.");
  }
  return *_tagged_vectors[tag];
}
getVector() [4/4]
const NumericVector< Number > & SystemBase::getVector (TagID tag) const virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 912 of file SystemBase.C.
{
  if (!hasVector(tag))
  {
    if (!_subproblem.vectorTagExists(tag))
      mooseError("Cannot retreive vector with tag ", tag, " because that tag does not exist");
    else
      mooseError("Cannot retreive vector with tag ",
                 tag,
                 " in system '",
                 name(),
                 "'\nbecause a vector has not been associated with that tag.");
  }
  return *_tagged_vectors[tag];
}
hasMatrix()
virtual bool SystemBase::hasMatrix (TagID tag) const inline virtual inherited
Check if the tagged matrix exists in the system.
Reimplemented in DisplacedSystem.
Definition at line 328 of file SystemBase.h.
  {
    return tag < _tagged_matrices.size() && _tagged_matrices[tag];
  }
Referenced by SystemBase::activeAllMatrixTags(), Assembly::addCachedJacobian(), NonlinearSystemBase::addImplicitGeometricCouplingEntries(), Assembly::addJacobianCoupledVarPair(), Assembly::addJacobianLowerD(), Assembly::addJacobianNeighbor(), Assembly::addJacobianNeighborLowerD(), Assembly::addJacobianNonlocal(), SystemBase::addMatrix(), Assembly::cacheJacobian(), Assembly::cacheJacobianBlock(), Assembly::cacheJacobianBlockNonzero(), Assembly::cacheJacobianCoupledVarPair(), Assembly::cacheJacobianMortar(), Assembly::cacheJacobianNeighbor(), Assembly::cacheJacobianNonlocal(), SystemBase::closeTaggedMatrices(), NonlinearSystemBase::computeJacobianInternal(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::constraintJacobians(), SystemBase::disassociateMatrixFromTag(), NonlinearSystemBase::enforceNodalConstraintsJacobian(), SystemBase::flushTaggedMatrices(), SystemBase::getMatrix(), DisplacedSystem::hasMatrix(), MooseVariableScalar::reinit(), SystemBase::removeMatrix(), Assembly::setCachedJacobian(), and Assembly::zeroCachedJacobian().
hasScalarVariable()
bool SystemBase::hasScalarVariable (const std::string & var_name) const virtual inherited
Definition at line 825 of file SystemBase.C.
{
  if (system().has_variable(var_name))
    return system().variable_type(var_name).family == SCALAR;
  else
    return false;
}
Referenced by MortarScalarBase::computeJacobian(), NonlinearSystemBase::computeJacobianInternal(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), SystemBase::copyVars(), NonlinearEigenSystem::postAddResidualObject(), AddPeriodicBCAction::setPeriodicVars(), and NonlinearSystemBase::setupScalingData().
hasSolutionState()
bool SystemBase::hasSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) const inline virtual inherited
Whether or not the system has the solution state (0 = current, 1 = old, 2 = older, etc).
Reimplemented in DisplacedSystem.
Definition at line 1004 of file SystemBase.h.
{
  return _solution_states[static_cast<unsigned short>(iteration_type)].size() > state;
}
Referenced by PointwiseRenormalizeVector::execute(), PointwiseRenormalizeVector::finalize(), DisplacedSystem::hasSolutionState(), SystemBase::needSolutionState(), SystemBase::restoreSolutions(), ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes(), and SystemBase::solutionState().
hasVarCopy()
bool SystemBase::hasVarCopy () const inline inherited
Whether or not there are variables to be restarted from an Exodus mesh file.
Definition at line 875 of file SystemBase.h.
{ return _var_to_copy.size() > 0; }
hasVariable()
bool SystemBase::hasVariable (const std::string & var_name) const virtual inherited
Query a system for a variable.
Parameters
var_name name of the variable
Returns
true if the variable exists
Definition at line 800 of file SystemBase.C.
{
  auto & names = getVariableNames();
  if (system().has_variable(var_name))
    return system().variable_type(var_name).family != SCALAR;
  if (std::find(names.begin(), names.end(), var_name) != names.end())
    // array variable
    return true;
  else
    return false;
}
Referenced by ADDGKernel::ADDGKernel(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayKernel::ArrayKernel(), SystemBase::copyVars(), DGKernel::DGKernel(), DMMooseSetVariables(), FEProblemBase::duplicateVariableCheck(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), PNGOutput::makeMeshFunc(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NonlinearSystemBase::setupScalingData(), and Coupleable::writableCoupledValue().
hasVector() [1/2]
bool SystemBase::hasVector (const std::string & tag_name) const inherited
Check if the named vector exists in the system.
Definition at line 873 of file SystemBase.C.
{
  return system().have_vector(name);
}
Referenced by FEProblemBase::addCachedResidualDirectly(), Assembly::addCachedResiduals(), Assembly::addResidual(), Assembly::addResidualLower(), Assembly::addResidualNeighbor(), Assembly::addResidualScalar(), SystemBase::addVector(), NonlinearSystemBase::assembleScalingVector(), Assembly::cacheResidual(), Assembly::cacheResidualLower(), Assembly::cacheResidualNeighbor(), SystemBase::closeTaggedVector(), FEProblemBase::computeBounds(), NonlinearSystemBase::computeResidualTags(), CentralDifference::computeTimeDerivatives(), SystemBase::disassociateVectorFromTag(), SystemBase::getVector(), DisplacedSystem::hasVector(), MooseVariableScalar::reinit(), SystemBase::removeVector(), SubProblem::selectVectorTagsFromSystem(), NonlinearSystemBase::setPreviousNewtonSolution(), TaggingInterface::setResidual(), SystemBase::solutionPreviousNewton(), and SystemBase::zeroTaggedVector().
hasVector() [2/2]
virtual bool SystemBase::hasVector (TagID tag_id) const inline virtual inherited
Check if the tagged vector exists in the system.
Reimplemented in DisplacedSystem.
Definition at line 249 of file SystemBase.h.
  {
    return tag_id < _tagged_vectors.size() && _tagged_vectors[tag_id];
  }
init()
virtual void SystemBase::init () inline virtual inherited
Initialize the system.
Reimplemented in NonlinearSystem, and NonlinearSystemBase.
Definition at line 150 of file SystemBase.h.
{};
Referenced by NonlinearSystemBase::init().
initializeObjects()
virtual void SystemBase::initializeObjects () inline virtual inherited
Called only once, just before the solve begins so objects can do some precalculations.
Definition at line 155 of file SystemBase.h.
{};
initialSetup()
void AuxiliarySystem::initialSetup () override virtual
Setup Functions.
Reimplemented from SystemBase.
Definition at line 81 of file AuxiliarySystem.C.
{
  TIME_SECTION("initialSetup", 3, "Initializing Auxiliary System");
  SystemBase::initialSetup();
  for (unsigned int tid = 0; tid < libMesh::n_threads(); tid++)
  {
    _aux_scalar_storage.sort(tid);
    _aux_scalar_storage.initialSetup(tid);
    _nodal_aux_storage.sort(tid);
    _nodal_aux_storage.initialSetup(tid);
    _mortar_nodal_aux_storage.sort(tid);
    _mortar_nodal_aux_storage.initialSetup(tid);
    _nodal_vec_aux_storage.sort(tid);
    _nodal_vec_aux_storage.initialSetup(tid);
    _nodal_array_aux_storage.sort(tid);
    _nodal_array_aux_storage.initialSetup(tid);
    _elemental_aux_storage.sort(tid);
    _elemental_aux_storage.initialSetup(tid);
    _elemental_vec_aux_storage.sort(tid);
    _elemental_vec_aux_storage.initialSetup(tid);
    _elemental_array_aux_storage.sort(tid);
    _elemental_array_aux_storage.initialSetup(tid);
  }
}
initSolutionState()
void SystemBase::initSolutionState () virtual inherited
Initializes the solution state.
Reimplemented in DisplacedSystem.
Definition at line 1321 of file SystemBase.C.
{
  // Default is the current solution
  unsigned int state = 0;
  // Add additional states as required by the variable states requested
  for (const auto & var : getVariables(/* tid = */ 0))
    state = std::max(state, var->oldestSolutionStateRequested());
  for (const auto & var : getScalarVariables(/* tid = */ 0))
    state = std::max(state, var->oldestSolutionStateRequested());
  needSolutionState(state, Moose::SolutionIterationType::Time);
  _solution_states_initialized = true;
}
Referenced by DisplacedSystem::initSolutionState().
isArrayVariable()
bool SystemBase::isArrayVariable (const std::string & var_name) const virtual inherited
If a variable is an array variable.
Definition at line 813 of file SystemBase.C.
{
  auto & names = getVariableNames();
  if (!system().has_variable(var_name) &&
      std::find(names.begin(), names.end(), var_name) != names.end())
    // array variable
    return true;
  else
    return false;
}
isScalarVariable()
bool SystemBase::isScalarVariable (unsigned int var_name) const virtual inherited
Definition at line 834 of file SystemBase.C.
{
  return (system().variable(var_num).type().family == SCALAR);
}
Referenced by Assembly::init(), ReferenceResidualProblem::initialSetup(), and Assembly::initNonlocalCoupling().
jacobianSetup()
void AuxiliarySystem::jacobianSetup () override virtual
Reimplemented from SystemBase.
Definition at line 170 of file AuxiliarySystem.C.
{
  SystemBase::jacobianSetup();
  for (unsigned int tid = 0; tid < libMesh::n_threads(); tid++)
  {
    _aux_scalar_storage.jacobianSetup(tid);
    _nodal_aux_storage.jacobianSetup(tid);
    _mortar_nodal_aux_storage.jacobianSetup(tid);
    _nodal_vec_aux_storage.jacobianSetup(tid);
    _nodal_array_aux_storage.jacobianSetup(tid);
    _elemental_aux_storage.jacobianSetup(tid);
    _elemental_vec_aux_storage.jacobianSetup(tid);
    _elemental_array_aux_storage.jacobianSetup(tid);
  }
}
matrixTagActive()
bool SystemBase::matrixTagActive (TagID tag) const virtual inherited
If or not a matrix tag is active.
Definition at line 1117 of file SystemBase.C.
{
  mooseAssert(_subproblem.matrixTagExists(tag), "Matrix tag " << tag << " does not exist");
  return tag < _matrix_tag_active_flags.size() && _matrix_tag_active_flags[tag];
}
mesh() [1/2]
virtual MooseMesh & SystemBase::mesh () inline virtual inherited
Definition at line 96 of file SystemBase.h.
{ return _mesh; }
Referenced by CreateDisplacedProblemAction::addProxyRelationshipManagers(), NonlinearSystemBase::computeScaling(), DMMooseGetEmbedding_Private(), DMSetUp_Moose_Pre(), SolutionIC::initialSetup(), MooseVariableData< OutputType >::MooseVariableData(), ComputeNodalKernelJacobiansThread::onNode(), ComputeNodalKernelsThread::onNode(), and ComputeNodalUserObjectsThread::onNode().
mesh() [2/2]
virtual const MooseMesh & SystemBase::mesh () const inline virtual inherited
Definition at line 97 of file SystemBase.h.
{ return _mesh; }
name()
const std::string & SystemBase::name () const virtual inherited
Definition at line 1297 of file SystemBase.C.
{
  return system().name();
}
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addConstraint(), NonlinearSystemBase::addDamper(), NonlinearSystemBase::addDGKernel(), NonlinearSystemBase::addDiracKernel(), NonlinearSystemBase::addInterfaceKernel(), addKernel(), MooseEigenSystem::addKernel(), NonlinearSystemBase::addKernel(), SystemBase::addMatrix(), NonlinearSystemBase::addNodalKernel(), addScalarKernel(), NonlinearSystemBase::addScalarKernel(), NonlinearSystemBase::addSplit(), addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), addVariable(), SystemBase::addVariable(), SystemBase::addVector(), NonlinearSystemBase::checkKernelCoverage(), SystemBase::closeTaggedVector(), DisplacedProblem::DisplacedProblem(), SystemBase::getMatrix(), NonlinearSystemBase::getSplit(), SystemBase::getVector(), DisplacedSystem::getVector(), SystemBase::hasVector(), NonlinearEigenSystem::postAddResidualObject(), SystemBase::removeMatrix(), SystemBase::removeVector(), NonlinearSystemBase::setupScalingData(), SystemBase::solutionState(), and SystemBase::zeroTaggedVector().
needMaterialOnSide()
bool AuxiliarySystem::needMaterialOnSide (BoundaryID bnd_id)
Indicated whether this system needs material properties on boundaries.
Returns
Boolean if IntegratedBCs are active
Definition at line 811 of file AuxiliarySystem.C.
{
  return _elemental_aux_storage.hasActiveBoundaryObjects(bnd_id) ||
         _elemental_vec_aux_storage.hasActiveBoundaryObjects(bnd_id);
}
needSolutionState()
void SystemBase::needSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) virtual inherited
Registers that the solution state state is needed.
Reimplemented in DisplacedSystem.
Definition at line 1393 of file SystemBase.C.
{
  libmesh_parallel_only(this->comm());
  if (hasSolutionState(state, iteration_type))
    return;
  auto & solution_states = _solution_states[static_cast<unsigned short>(iteration_type)];
  solution_states.resize(state + 1);
  // The 0-th (current) solution state is owned by libMesh
  if (!solution_states[0])
    solution_states[0] = &solutionInternal();
  else
    mooseAssert(solution_states[0] == &solutionInternal(), "Inconsistent current solution");
  // We will manually add all states past current
  for (unsigned int i = 1; i <= state; ++i)
    if (!solution_states[i])
    {
      auto tag = _subproblem.addVectorTag(oldSolutionStateVectorName(i, iteration_type),
                                          Moose::VECTOR_TAG_SOLUTION);
      solution_states[i] = &addVector(tag, true, GHOSTED);
    }
    else
      mooseAssert(solution_states[i] == &getVector(oldSolutionStateVectorName(i, iteration_type)),
                  "Inconsistent solution state");
}
Referenced by EigenExecutionerBase::EigenExecutionerBase(), SystemBase::initSolutionState(), DisplacedSystem::needSolutionState(), and SystemBase::solutionState().
nFieldVariables()
unsigned int SystemBase::nFieldVariables () const inherited
Get the number of field variables in this system.
Returns
the number of field variables
Definition at line 849 of file SystemBase.C.
{
  unsigned int n = 0;
  for (auto & var : _vars[0].fieldVariables())
    n += var->count();
  return n;
}
Referenced by SystemBase::nVariables().
nFVVariables()
unsigned int SystemBase::nFVVariables () const inherited
Get the number of finite volume variables in this system.
Returns
the number of finite volume variables
Definition at line 859 of file SystemBase.C.
{
  unsigned int n = 0;
  for (auto & var : _vars[0].fieldVariables())
    if (var->isFV())
      n += var->count();
  return n;
}
Referenced by MooseMesh::cacheFVElementalDoFs().
nodalArrayAuxWarehouse()
const ExecuteMooseObjectWarehouse< ArrayAuxKernel > & AuxiliarySystem::nodalArrayAuxWarehouse () const inline
Definition at line 253 of file AuxiliarySystem.h.
{
  return _nodal_array_aux_storage;
}
nodalAuxWarehouse()
const ExecuteMooseObjectWarehouse< AuxKernel > & AuxiliarySystem::nodalAuxWarehouse () const inline
Definition at line 241 of file AuxiliarySystem.h.
{
  return _nodal_aux_storage;
}
nodalVectorAuxWarehouse()
const ExecuteMooseObjectWarehouse< VectorAuxKernel > & AuxiliarySystem::nodalVectorAuxWarehouse () const inline
Definition at line 247 of file AuxiliarySystem.h.
{
  return _nodal_vec_aux_storage;
}
nonTimeVectorTag()
virtual TagID SystemBase::nonTimeVectorTag () const inline virtual inherited
Reimplemented in DisplacedSystem, and NonlinearSystemBase.
Definition at line 270 of file SystemBase.h.
{ mooseError("Not implemented yet"); }
Referenced by SystemBase::defaultVectorTags(), and DisplacedSystem::nonTimeVectorTag().
number()
unsigned int SystemBase::number () const inherited
Gets the number of this system.
Returns
The number of this system
Definition at line 1125 of file SystemBase.C.
{
  return system().number();
}
Referenced by FEProblemBase::addCachedResidualDirectly(), FEProblemBase::addJacobian(), FEProblemBase::addJacobianBlockTags(), FEProblemBase::addJacobianLowerD(), FEProblemBase::addJacobianNeighbor(), FEProblemBase::addJacobianNeighborLowerD(), FEProblemBase::addJacobianOffDiagScalar(), FEProblemBase::addJacobianScalar(), FEProblemBase::addResidual(), FEProblemBase::addResidualLower(), FEProblemBase::addResidualNeighbor(), FEProblemBase::addResidualScalar(), ADKernelTempl< T >::ADKernelTempl(), ArrayKernel::ArrayKernel(), NonlinearSystemBase::assembleScalingVector(), MooseMesh::cacheFaceInfoVariableOwnership(), ComputeResidualAndJacobianThread::compute(), MooseVariableScalar::computeAD(), FEProblemBase::computeBounds(), Assembly::computeFaceMap(), ArrayNodalBC::computeJacobian(), NodalBC::computeJacobian(), VectorNodalBC::computeJacobian(), FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FEProblemBase::computeJacobianBlock(), NonlinearSystemBase::computeJacobianInternal(), FEProblemBase::computeNearNullSpace(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), FEProblemBase::computeNullSpace(), ArrayNodalBC::computeOffDiagJacobian(), NodalBC::computeOffDiagJacobian(), VectorNodalBC::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), ComputeFullJacobianThread::computeOnInterface(), ComputeFullJacobianThread::computeOnInternalFace(), FEProblemBase::computePostCheck(), EqualValueEmbeddedConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), FVFluxBC::computeResidual(), FVInterfaceKernel::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), IntegratedBC::computeResidualAndJacobian(), NodalBC::computeResidualAndJacobian(), Kernel::computeResidualAndJacobian(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Assembly::computeSinglePointMapAD(), FEProblemBase::computeTransposeNullSpace(), DebugResidualAux::computeValue(), NearestNodeValueAux::computeValue(), NonlinearSystemBase::constraintJacobians(), Coupleable::coupled(), FEProblemBase::currentNlSysNum(), PseudoTimestep::currentResidualNorm(), Moose::FV::determineElemOneAndTwo(), ComputeResidualAndJacobianThread::determineObjectWarehouses(), ComputeResidualThread::determineObjectWarehouses(), Moose::doDerivatives(), GreaterThanLessThanPostprocessor::execute(), VariableResidual::execute(), NodalNormalsCorner::execute(), NodalNormalsEvaluator::execute(), NodalNormalsPreprocessor::execute(), NumNonlinearIterations::finalize(), ElementSubdomainModifier::finalize(), BoundsAuxBase::getDoFIndex(), NonlinearSystemBase::getNodeDofs(), SystemBase::getSubdomainsForVar(), NumLinearIterations::getValue(), NumResidualEvaluations::getValue(), Residual::getValue(), Moose::globalDofIndexToDerivative(), FVBoundaryCondition::hasFaceSide(), NonlinearSystemBase::initialSetup(), ActivateElementsUserObjectBase::initSolutions(), EigenExecutionerBase::inversePowerIteration(), Kernel::Kernel(), EigenExecutionerBase::nonlinearSolve(), ComputeDiracThread::onElement(), ComputeNodalKernelBCJacobiansThread::onNode(), ComputeNodalKernelJacobiansThread::onNode(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), FEProblemBase::prepare(), FEProblemBase::prepareAssembly(), SystemBase::prepareFace(), FEProblemBase::prepareFaceShapes(), FEProblemBase::prepareNeighborShapes(), FEProblemBase::prepareShapes(), EqualValueEmbeddedConstraint::reinitConstraint(), FEProblemBase::reinitDirac(), FEProblemBase::reinitNeighborPhys(), FEProblemBase::reinitOffDiagScalars(), FEProblemBase::setResidual(), FEProblemBase::setResidualNeighbor(), PhysicsBasedPreconditioner::setup(), FVInterfaceKernel::setupData(), FEProblemSolve::solve(), ActuallyExplicitEuler::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), ExplicitSSPRungeKutta::solveStage(), UserObject::systemNumber(), MultiAppDofCopyTransfer::transferDofObject(), FVFluxBC::uOnGhost(), FVFluxBC::uOnUSub(), and MortarConstraintBase::zeroInactiveLMDofs().
nVariables()
unsigned int SystemBase::nVariables () const virtual inherited
Get the number of variables in this system.
Returns
the number of variables
Definition at line 840 of file SystemBase.C.
{
  unsigned int n = nFieldVariables();
  n += _vars[0].scalars().size();
  return n;
}
Referenced by AdaptivityAction::act(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), NonlinearSystemBase::getNodeDofs(), Assembly::init(), MaxVarNDofsPerElem::onElement(), MaxVarNDofsPerNode::onNode(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), and SingleMatrixPreconditioner::SingleMatrixPreconditioner().
oldSolutionStateVectorName()
TagName SystemBase::oldSolutionStateVectorName (const unsigned int state, Moose::SolutionIterationType iteration_type) const private inherited
Gets the vector name used for an old (not current) solution state.
Definition at line 1338 of file SystemBase.C.
{
  mooseAssert(state != 0, "Not an old state");
  if (iteration_type == Moose::SolutionIterationType::Time)
  {
    if (state == 1)
      return Moose::OLD_SOLUTION_TAG;
    else if (state == 2)
      return Moose::OLDER_SOLUTION_TAG;
  }
  else if (iteration_type == Moose::SolutionIterationType::Nonlinear && state == 1)
    return Moose::PREVIOUS_NL_SOLUTION_TAG;
  return "solution_state_" + std::to_string(state) + "_" + Moose::stringify(iteration_type);
}
Referenced by SystemBase::needSolutionState(), and SystemBase::solutionState().
perfGraph()
PerfGraph & PerfGraphInterface::perfGraph () inherited
Get the PerfGraph.
Definition at line 78 of file PerfGraphInterface.C.
{
  return _pg_moose_app.perfGraph();
}
Referenced by CommonOutputAction::act(), PerfGraphData::finalize(), and PerfGraphOutput::output().
prepare()
void SystemBase::prepare (THREAD_ID tid) virtual inherited
Prepare the system for use.
Parameters
tid ID of the thread
Definition at line 245 of file SystemBase.C.
{
  if (_subproblem.hasActiveElementalMooseVariables(tid))
  {
    const std::set<MooseVariableFieldBase *> & active_elemental_moose_variables =
        _subproblem.getActiveElementalMooseVariables(tid);
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
      var->clearDofIndices();
    for (const auto & var : active_elemental_moose_variables)
      if (&(var->sys()) == this)
        var->prepare();
  }
  else
  {
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
      var->prepare();
  }
}
Referenced by SubProblem::reinitElemFaceRef().
prepareFace()
void SystemBase::prepareFace (THREAD_ID tid, bool resize_data) virtual inherited
Prepare the system for use on sides.
This will try to reuse the preparation done on the element.
Parameters
tid ID of the thread
resize_data Pass True if this system needs to resize residual and jacobian datastructures based on preparing this face
Definition at line 268 of file SystemBase.C.
{
  // We only need to do something if the element prepare was restricted
  if (_subproblem.hasActiveElementalMooseVariables(tid))
  {
    const std::set<MooseVariableFieldBase *> & active_elemental_moose_variables =
        _subproblem.getActiveElementalMooseVariables(tid);
    std::vector<MooseVariableFieldBase *> newly_prepared_vars;
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
    {
      mooseAssert(&var->sys() == this,
                  "I will cry if we store variables in our warehouse that don't belong to us");
      // If it wasn't in the active list, we need to prepare it. This has the potential to duplicate
      // prepare if we have these conditions:
      //
      // 1. We have a displaced problem
      // 2. We are using AD
      // 3. We are not using global AD indexing
      //
      // But I think I would rather risk duplicate prepare than introduce an additional member set
      // variable for tracking prepared variables. Set insertion is slow and some simulations have a
      // ton of variables
      if (!active_elemental_moose_variables.count(var))
      {
        var->prepare();
        newly_prepared_vars.push_back(var);
      }
    }
    // Make sure to resize the residual and jacobian datastructures for all the new variables
    if (resize_data)
      for (const auto var_ptr : newly_prepared_vars)
      {
        _subproblem.assembly(tid, number()).prepareVariable(var_ptr);
        if (_subproblem.checkNonlocalCouplingRequirement())
          _subproblem.assembly(tid, number()).prepareVariableNonlocal(var_ptr);
      }
  }
}
prepareLowerD()
void SystemBase::prepareLowerD (THREAD_ID tid) virtual inherited
Prepare the system for use for lower dimensional elements.
Parameters
tid ID of the thread
Definition at line 321 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->prepareLowerD();
}
prepareNeighbor()
void SystemBase::prepareNeighbor (THREAD_ID tid) virtual inherited
Prepare the system for use.
Parameters
tid ID of the thread
Definition at line 313 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->prepareNeighbor();
}
Referenced by SubProblem::reinitNeighborFaceRef().
registerTimedSection() [1/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
Returns
The ID of the section - use when starting timing
Definition at line 53 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(timed_section_name, level);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
registerTimedSection() [2/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level, const std::string & live_message, const bool print_dots = true) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
live_message The message to be printed to the screen during execution
print_dots Whether or not progress dots should be printed for this section
Returns
The ID of the section - use when starting timing
Definition at line 64 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(
        timedSectionName(section_name), level, live_message, print_dots);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
reinitElem()
void AuxiliarySystem::reinitElem (const Elem * elem, THREAD_ID tid) override virtual
Reinit an element assembly info.
Parameters
elem Which element we are reinitializing for
tid ID of the thread
Reimplemented from SystemBase.
Definition at line 349 of file AuxiliarySystem.C.
{
  for (auto * var : _nodal_vars[tid])
    var->computeElemValues();
  for (auto * var : _elem_vars[tid])
  {
    var->reinitAux();
    var->computeElemValues();
  }
}
reinitElemFace()
void AuxiliarySystem::reinitElemFace (const Elem * elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid) override virtual
Reinit assembly info for a side of an element.
Parameters
elem The element
side Side of of the element
bnd_id Boundary id on that side
tid Thread ID
Reimplemented from SystemBase.
Definition at line 362 of file AuxiliarySystem.C.
{
  for (auto * var : _nodal_vars[tid])
    var->computeElemValuesFace();
  for (auto * var : _elem_vars[tid])
  {
    var->reinitAux();
    var->reinitAuxNeighbor();
    var->computeElemValuesFace();
  }
}
reinitLowerD()
void SystemBase::reinitLowerD (THREAD_ID tid) virtual inherited
Compute the values of the variables on the lower dimensional element.
Definition at line 379 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeLowerDValues();
}
reinitNeighbor()
void SystemBase::reinitNeighbor (const Elem * elem, THREAD_ID tid) virtual inherited
Compute the values of the variables at all the current points.
Definition at line 371 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeNeighborValues();
}
reinitNeighborFace()
void SystemBase::reinitNeighborFace (const Elem * elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid) virtual inherited
Compute the values of the variables at all the current points.
Definition at line 360 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeNeighborValuesFace();
}
Referenced by SubProblem::reinitNeighborFaceRef().
reinitNode()
void SystemBase::reinitNode (const Node * node, THREAD_ID tid) virtual inherited
Reinit nodal assembly info.
Parameters
node Node to reinit for
tid Thread ID
Definition at line 387 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNode();
    if (var->isNodalDefined())
      var->computeNodalValues();
  }
}
reinitNodeFace()
void SystemBase::reinitNodeFace (const Node * node, BoundaryID bnd_id, THREAD_ID tid) virtual inherited
Reinit nodal assembly info on a face.
Parameters
node Node to reinit
bnd_id Boundary ID
tid Thread ID
Definition at line 399 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNode();
    if (var->isNodalDefined())
      var->computeNodalValues();
  }
}
reinitNodes()
void SystemBase::reinitNodes (const std::vector< dof_id_type > & nodes, THREAD_ID tid) virtual inherited
Reinit variables at a set of nodes.
Parameters
nodes List of node ids to reinit
tid Thread ID
Definition at line 411 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNodes(nodes);
    var->computeNodalValues();
  }
}
reinitNodesNeighbor()
void SystemBase::reinitNodesNeighbor (const std::vector< dof_id_type > & nodes, THREAD_ID tid) virtual inherited
Reinit variables at a set of neighbor nodes.
Parameters
nodes List of node ids to reinit
tid Thread ID
Definition at line 422 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNodesNeighbor(nodes);
    var->computeNodalNeighborValues();
  }
}
reinitScalars()
void SystemBase::reinitScalars (THREAD_ID tid, bool reinit_for_derivative_reordering = false) virtual inherited
Reinit scalar varaibles.
Parameters
tid Thread ID
reinit_for_derivative_reordering A flag indicating whether we are reinitializing for the purpose of re-ordering derivative information for ADNodalBCs
Definition at line 433 of file SystemBase.C.
{
  const std::vector<MooseVariableScalar *> & vars = _vars[tid].scalars();
  for (const auto & var : vars)
    var->reinit(reinit_for_derivative_reordering);
}
removeMatrix()
void SystemBase::removeMatrix (TagID tag) inherited
Removes a matrix with a given tag.
Parameters
tag_name The name of the tag
Definition at line 579 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag_id))
    mooseError("Cannot remove the matrix with TagID ",
               tag_id,
               "\nin system '",
               name(),
               "', because that tag does not exist in the problem");
  if (hasMatrix(tag_id))
  {
    const auto matrix_name = _subproblem.matrixTagName(tag_id);
    system().remove_matrix(matrix_name);
    _tagged_matrices[tag_id] = nullptr;
  }
}
removeVector() [1/2]
void SystemBase::removeVector (const std::string & name) inherited
Remove a vector from the system with the given name.
Definition at line 1291 of file SystemBase.C.
{
  system().remove_vector(name);
}
Referenced by SystemBase::restoreOldSolutions().
removeVector() [2/2]
void SystemBase::removeVector (TagID tag_id) inherited
Remove a solution length vector from the system with the specified TagID.
Parameters
tag_id Tag ID
Definition at line 690 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag_id))
    mooseError("Cannot remove the vector with TagID ",
               tag_id,
               "\nin system '",
               name(),
               "', because that tag does not exist in the problem");
  if (hasVector(tag_id))
  {
    auto vector_name = _subproblem.vectorTagName(tag_id);
    system().remove_vector(vector_name);
    _tagged_vectors[tag_id] = nullptr;
  }
}
residualCopy()
virtual NumericVector< Number > & SystemBase::residualCopy () inline virtual inherited
Reimplemented in DisplacedSystem, and NonlinearSystemBase.
Definition at line 404 of file SystemBase.h.
  {
    mooseError("This system does not support getting a copy of the residual");
  }
Referenced by DisplacedSystem::residualCopy().
residualGhosted()
virtual NumericVector< Number > & SystemBase::residualGhosted () inline virtual inherited
Reimplemented in DisplacedSystem, and NonlinearSystemBase.
Definition at line 408 of file SystemBase.h.
  {
    mooseError("This system does not support getting a ghosted copy of the residual");
  }
Referenced by DisplacedSystem::residualGhosted().
residualSetup()
void AuxiliarySystem::residualSetup () override virtual
Reimplemented from SystemBase.
Definition at line 188 of file AuxiliarySystem.C.
{
  SystemBase::residualSetup();
  for (unsigned int tid = 0; tid < libMesh::n_threads(); tid++)
  {
    _aux_scalar_storage.residualSetup(tid);
    _nodal_aux_storage.residualSetup(tid);
    _mortar_nodal_aux_storage.residualSetup(tid);
    _nodal_vec_aux_storage.residualSetup(tid);
    _nodal_array_aux_storage.residualSetup(tid);
    _elemental_aux_storage.residualSetup(tid);
    _elemental_vec_aux_storage.residualSetup(tid);
    _elemental_array_aux_storage.residualSetup(tid);
  }
}
residualVectorTag()
virtual TagID SystemBase::residualVectorTag () const inline virtual inherited
Reimplemented in DisplacedSystem, and NonlinearSystemBase.
Definition at line 275 of file SystemBase.h.
{ mooseError("Not implemented yet"); }
Referenced by SystemBase::defaultVectorTags(), and DisplacedSystem::residualVectorTag().
restoreOldSolutions()
void SystemBase::restoreOldSolutions () virtual inherited
Restore the old and older solutions when the saved solutions present.
Definition at line 531 of file SystemBase.C.
{
  const auto states =
      _solution_states[static_cast<unsigned short>(Moose::SolutionIterationType::Time)].size();
  if (states > 1)
    for (unsigned int i = 1; i <= states - 1; ++i)
      if (_saved_solution_states[i])
      {
        solutionState(i) = *(_saved_solution_states[i]);
        removeVector("save_solution_state_" + std::to_string(i));
        _saved_solution_states[i] = nullptr;
      }
  if (_saved_dot_old && solutionUDotOld())
  {
    *solutionUDotOld() = *_saved_dot_old;
    removeVector("save_solution_dot_old");
    _saved_dot_old = nullptr;
  }
  if (_saved_dotdot_old && solutionUDotDotOld())
  {
    *solutionUDotDotOld() = *_saved_dotdot_old;
    removeVector("save_solution_dotdot_old");
    _saved_dotdot_old = nullptr;
  }
}
restoreSolutions()
void SystemBase::restoreSolutions () virtual inherited
Restore current solutions (call after your solve failed)
Reimplemented in NonlinearSystemBase.
Definition at line 1274 of file SystemBase.C.
{
  if (!hasSolutionState(1))
    mooseError("Cannot restore solutions without old solution");
  *(const_cast<NumericVector<Number> *&>(currentSolution())) = solutionOld();
  solution() = solutionOld();
  if (solutionUDotOld())
    *solutionUDot() = *solutionUDotOld();
  if (solutionUDotDotOld())
    *solutionUDotDot() = *solutionUDotDotOld();
  if (solutionPreviousNewton())
    *solutionPreviousNewton() = solutionOld();
  system().update();
}
Referenced by NonlinearSystemBase::restoreSolutions().
saveOldSolutions()
void SystemBase::saveOldSolutions () virtual inherited
Save the old and older solutions.
Definition at line 499 of file SystemBase.C.
{
  const auto states =
      _solution_states[static_cast<unsigned short>(Moose::SolutionIterationType::Time)].size();
  if (states > 1)
  {
    _saved_solution_states.resize(states);
    for (unsigned int i = 1; i <= states - 1; ++i)
      if (!_saved_solution_states[i])
        _saved_solution_states[i] =
            &addVector("save_solution_state_" + std::to_string(i), false, PARALLEL);
    for (unsigned int i = 1; i <= states - 1; ++i)
      *(_saved_solution_states[i]) = solutionState(i);
  }
  if (!_saved_dot_old && solutionUDotOld())
    _saved_dot_old = &addVector("save_solution_dot_old", false, PARALLEL);
  if (!_saved_dotdot_old && solutionUDotDotOld())
    _saved_dotdot_old = &addVector("save_solution_dotdot_old", false, PARALLEL);
  if (solutionUDotOld())
    *_saved_dot_old = *solutionUDotOld();
  if (solutionUDotDotOld())
    *_saved_dotdot_old = *solutionUDotDotOld();
}
serializedSolution()
NumericVector< Number > & AuxiliarySystem::serializedSolution () override virtual
Returns a reference to a serialized version of the solution vector for this subproblem.
Implements SystemBase.
Definition at line 379 of file AuxiliarySystem.C.
{
  if (!_serialized_solution.get())
  {
    _serialized_solution = NumericVector<Number>::build(_fe_problem.comm());
    _serialized_solution->init(_sys.n_dofs(), false, SERIAL);
  }
  return *_serialized_solution;
}
Referenced by PNGOutput::calculateRescalingValues(), and PNGOutput::makeMeshFunc().
serializeSolution()
void AuxiliarySystem::serializeSolution () virtual
Definition at line 391 of file AuxiliarySystem.C.
{
  if (_serialized_solution.get() &&
      _sys.n_dofs() > 0) // libMesh does not like serializing of empty vectors
  {
    if (!_serialized_solution->initialized() || _serialized_solution->size() != _sys.n_dofs())
    {
      _serialized_solution->clear();
      _serialized_solution->init(_sys.n_dofs(), false, SERIAL);
    }
    solution().localize(*_serialized_solution);
  }
}
Referenced by compute().
setActiveScalarVariableCoupleableVectorTags()
void SystemBase::setActiveScalarVariableCoupleableVectorTags (const std::set< TagID > & vtags, THREAD_ID tid) inherited
Set the active vector tags for the scalar variables.
Definition at line 1532 of file SystemBase.C.
{
  _vars[tid].setActiveScalarVariableCoupleableVectorTags(vtags);
}
Referenced by SubProblem::setActiveScalarVariableCoupleableVectorTags().
setActiveVariableCoupleableVectorTags()
void SystemBase::setActiveVariableCoupleableVectorTags (const std::set< TagID > & vtags, THREAD_ID tid) inherited
Set the active vector tags for the variables.
Definition at line 1526 of file SystemBase.C.
{
  _vars[tid].setActiveVariableCoupleableVectorTags(vtags);
}
Referenced by SubProblem::setActiveFEVariableCoupleableVectorTags().
setPreviousNewtonSolution()
void AuxiliarySystem::setPreviousNewtonSolution () virtual
Definition at line 818 of file AuxiliarySystem.C.
{
  // Evaluate aux variables to get the solution vector
  compute(EXEC_LINEAR);
}
setScalarVariableCoupleableTags()
void AuxiliarySystem::setScalarVariableCoupleableTags (ExecFlagType type)
Definition at line 618 of file AuxiliarySystem.C.
{
  const MooseObjectWarehouse<AuxScalarKernel> & storage = _aux_scalar_storage[type];
  const std::vector<std::shared_ptr<AuxScalarKernel>> & objects = storage.getActiveObjects(0);
  std::set<TagID> needed_sc_var_matrix_tags;
  std::set<TagID> needed_sc_var_vector_tags;
  for (const auto & obj : objects)
  {
    auto & sc_var_coup_vtags = obj->getScalarVariableCoupleableVectorTags();
    needed_sc_var_vector_tags.insert(sc_var_coup_vtags.begin(), sc_var_coup_vtags.end());
    auto & sc_var_coup_mtags = obj->getScalarVariableCoupleableMatrixTags();
    needed_sc_var_matrix_tags.insert(sc_var_coup_mtags.begin(), sc_var_coup_mtags.end());
  }
  _fe_problem.setActiveScalarVariableCoupleableMatrixTags(needed_sc_var_matrix_tags, 0);
  _fe_problem.setActiveScalarVariableCoupleableVectorTags(needed_sc_var_vector_tags, 0);
}
Referenced by computeScalarVars().
setVariableGlobalDoFs()
void SystemBase::setVariableGlobalDoFs (const std::string & var_name) inherited
set all the global dof indices for a variable
Parameters
var_name The name of the variable
Definition at line 175 of file SystemBase.C.
{
  AllLocalDofIndicesThread aldit(_subproblem, {var_name});
  ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();
  Threads::parallel_reduce(elem_range, aldit);
  // Gather the dof indices across procs to get all the dof indices for var_name
  aldit.dofIndicesSetUnion();
  const auto & all_dof_indices = aldit.getDofIndices();
  _var_all_dof_indices.assign(all_dof_indices.begin(), all_dof_indices.end());
}
setVerboseFlag()
void SystemBase::setVerboseFlag (const bool & verbose) inline inherited
Sets the verbose flag.
Parameters
[in] verbose Verbose flag
Definition at line 129 of file SystemBase.h.
{ _verbose = verbose; }
Referenced by Executioner::Executioner().
solution() [1/2]
NumericVector< Number > & SystemBase::solution () inline inherited
Definition at line 176 of file SystemBase.h.
{ return solutionState(0); }
Referenced by Adaptivity::adaptMesh(), TransientMultiApp::appTransferVector(), MooseEigenSystem::combineSystemSolution(), NonlinearSystemBase::computeDamping(), computeElementalVarsHelper(), NonlinearSystemBase::computeJacobianInternal(), computeMortarNodalVars(), NonlinearSystemBase::computeNodalBCs(), computeNodalVarsHelper(), NonlinearSystemBase::computeResidualTags(), computeScalarVars(), SystemBase::copyVars(), GreaterThanLessThanPostprocessor::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), NodalNormalsCorner::execute(), NodalNormalsEvaluator::execute(), NodalNormalsPreprocessor::execute(), NodalNormalsCorner::finalize(), NodalNormalsEvaluator::finalize(), NodalNormalsPreprocessor::finalize(), NodalNormalsCorner::initialize(), NodalNormalsEvaluator::initialize(), NodalNormalsPreprocessor::initialize(), MooseEigenSystem::initSystemSolution(), ComputeIndicatorThread::onElement(), ComputeMarkerThread::onElement(), ComputeUserObjectsThread::onElement(), ComputeNodalUserObjectsThread::onNode(), FEProblemBase::projectInitialConditionOnCustomRange(), FEProblemBase::projectSolution(), Transient::relativeSolutionDifferenceNorm(), SystemBase::restoreSolutions(), PicardSolve::saveVariableValues(), SecantSolve::saveVariableValues(), SteffensenSolve::saveVariableValues(), MooseEigenSystem::scaleSystemSolution(), serializeSolution(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::setInitialSolution(), DisplacedSystem::solutionInternal(), NonlinearEigenSystem::solve(), MultiAppDofCopyTransfer::transfer(), PicardSolve::transformVariables(), SecantSolve::transformVariables(), SteffensenSolve::transformVariables(), and SystemBase::zeroVariables().
solution() [2/2]
const NumericVector< Number > & SystemBase::solution () const inline inherited
Definition at line 179 of file SystemBase.h.
{ return solutionState(0); }
solutionInternal()
NumericVector< Number > & AuxiliarySystem::solutionInternal () const inline override protected virtual
Internal getter for solution owned by libMesh.
Implements SystemBase.
Definition at line 237 of file AuxiliarySystem.h.
{ return *_sys.solution; }
solutionOld() [1/2]
NumericVector< Number > & SystemBase::solutionOld () inline inherited
Definition at line 177 of file SystemBase.h.
{ return solutionState(1); }
Referenced by MooseEigenSystem::combineSystemSolution(), CentralDifference::computeTimeDerivatives(), ActivateElementsUserObjectBase::initSolutions(), MooseEigenSystem::initSystemSolutionOld(), MooseVariableScalar::reinit(), Transient::relativeSolutionDifferenceNorm(), SystemBase::restoreSolutions(), ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes(), ActuallyExplicitEuler::solve(), and AdamsPredictor::timestepSetup().
solutionOld() [2/2]
const NumericVector< Number > & SystemBase::solutionOld () const inline inherited
Definition at line 180 of file SystemBase.h.
{ return solutionState(1); }
solutionOlder() [1/2]
NumericVector< Number > & SystemBase::solutionOlder () inline inherited
Definition at line 178 of file SystemBase.h.
{ return solutionState(2); }
Referenced by MooseEigenSystem::combineSystemSolution(), CentralDifference::computeTimeDerivatives(), ActivateElementsUserObjectBase::initSolutions(), MooseVariableScalar::reinit(), and ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes().
solutionOlder() [2/2]
const NumericVector< Number > & SystemBase::solutionOlder () const inline inherited
Definition at line 181 of file SystemBase.h.
{ return solutionState(2); }
solutionPreviousNewton() [1/2]
NumericVector< Number > * SystemBase::solutionPreviousNewton () virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 1303 of file SystemBase.C.
{
  if (hasVector(Moose::PREVIOUS_NL_SOLUTION_TAG))
    return &getVector(Moose::PREVIOUS_NL_SOLUTION_TAG);
  else
    return nullptr;
}
solutionPreviousNewton() [2/2]
const NumericVector< Number > * SystemBase::solutionPreviousNewton () const virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 1312 of file SystemBase.C.
{
  if (hasVector(Moose::PREVIOUS_NL_SOLUTION_TAG))
    return &getVector(Moose::PREVIOUS_NL_SOLUTION_TAG);
  else
    return nullptr;
}
Referenced by SystemBase::copyOldSolutions(), SystemBase::copySolutionsBackwards(), and SystemBase::restoreSolutions().
solutionState() [1/2]
NumericVector< Number > & SystemBase::solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) virtual inherited
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
If the state does not exist, it will be initialized in addition to any newer states before it that have not been initialized.
Reimplemented in DisplacedSystem.
Definition at line 1384 of file SystemBase.C.
{
  if (!hasSolutionState(state, iteration_type))
    needSolutionState(state, iteration_type);
  return *_solution_states[static_cast<unsigned short>(iteration_type)][state];
}
Referenced by SystemBase::copyOldSolutions(), SystemBase::copySolutionsBackwards(), PointwiseRenormalizeVector::execute(), PointwiseRenormalizeVector::finalize(), SystemBase::restoreOldSolutions(), SystemBase::saveOldSolutions(), SystemBase::solution(), SystemBase::solutionOld(), SystemBase::solutionOlder(), and DisplacedSystem::solutionState().
solutionState() [2/2]
const NumericVector< Number > & SystemBase::solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) const virtual inherited
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
Reimplemented in DisplacedSystem.
Definition at line 1357 of file SystemBase.C.
{
  if (!hasSolutionState(state, iteration_type))
    mooseError("For iteration type '",
               Moose::stringify(iteration_type),
               "': solution state ",
               state,
               " was requested in ",
               name(),
               " but only up to state ",
               _solution_states[static_cast<unsigned short>(iteration_type)].size() - 1,
               " is available.");
  const auto & solution_states = _solution_states[static_cast<unsigned short>(iteration_type)];
  if (state == 0)
    mooseAssert(solution_states[0] == &solutionInternal(), "Inconsistent current solution");
  else
    mooseAssert(solution_states[state] ==
                    &getVector(oldSolutionStateVectorName(state, iteration_type)),
                "Inconsistent solution state");
  return *solution_states[state];
}
solutionStatesInitialized()
bool SystemBase::solutionStatesInitialized () const inline inherited
Whether or not the solution states have been initialized via initSolutionState()
After the solution states have been initialized, additional solution states cannot be added.
Definition at line 888 of file SystemBase.h.
{ return _solution_states_initialized; }
Referenced by AuxScalarKernel::uOld(), and ScalarKernelBase::uOld().
solutionUDot() [1/2]
const NumericVector< Number > * AuxiliarySystem::solutionUDot () const inline override virtual
Implements SystemBase.
Definition at line 108 of file AuxiliarySystem.h.
{ return _u_dot; }
solutionUDot() [2/2]
NumericVector< Number > * AuxiliarySystem::solutionUDot () inline override virtual
Implements SystemBase.
Definition at line 104 of file AuxiliarySystem.h.
{ return _u_dot; }
solutionUDotDot() [1/2]
const NumericVector< Number > * AuxiliarySystem::solutionUDotDot () const inline override virtual
Implements SystemBase.
Definition at line 109 of file AuxiliarySystem.h.
{ return _u_dotdot; }
solutionUDotDot() [2/2]
NumericVector< Number > * AuxiliarySystem::solutionUDotDot () inline override virtual
Implements SystemBase.
Definition at line 105 of file AuxiliarySystem.h.
{ return _u_dotdot; }
solutionUDotDotOld() [1/2]
const NumericVector< Number > * AuxiliarySystem::solutionUDotDotOld () const inline override virtual
Implements SystemBase.
Definition at line 111 of file AuxiliarySystem.h.
{ return _u_dotdot_old; }
solutionUDotDotOld() [2/2]
NumericVector< Number > * AuxiliarySystem::solutionUDotDotOld () inline override virtual
Implements SystemBase.
Definition at line 107 of file AuxiliarySystem.h.
{ return _u_dotdot_old; }
solutionUDotOld() [1/2]
const NumericVector< Number > * AuxiliarySystem::solutionUDotOld () const inline override virtual
Implements SystemBase.
Definition at line 110 of file AuxiliarySystem.h.
{ return _u_dot_old; }
solutionUDotOld() [2/2]
NumericVector< Number > * AuxiliarySystem::solutionUDotOld () inline override virtual
Implements SystemBase.
Definition at line 106 of file AuxiliarySystem.h.
{ return _u_dot_old; }
solve()
void SystemBase::solve () virtual inherited
Solve the system (using libMesh magic)
Reimplemented in DumpObjectsNonlinearSystem, NonlinearEigenSystem, NonlinearSystem, and NonlinearSystemBase.
Definition at line 1218 of file SystemBase.C.
{
  system().solve();
}
subdomainSetup()
void AuxiliarySystem::subdomainSetup () override virtual
Reimplemented from SystemBase.
Definition at line 152 of file AuxiliarySystem.C.
{
  SystemBase::subdomainSetup();
  for (unsigned int tid = 0; tid < libMesh::n_threads(); tid++)
  {
    _aux_scalar_storage.subdomainSetup(tid);
    _nodal_aux_storage.subdomainSetup(tid);
    _mortar_nodal_aux_storage.subdomainSetup(tid);
    _nodal_vec_aux_storage.subdomainSetup(tid);
    _nodal_array_aux_storage.subdomainSetup(tid);
    _elemental_aux_storage.subdomainSetup(tid);
    _elemental_vec_aux_storage.subdomainSetup(tid);
    _elemental_array_aux_storage.subdomainSetup(tid);
  }
}
subproblem() [1/2]
virtual SubProblem & SystemBase::subproblem () inline virtual inherited
Definition at line 98 of file SystemBase.h.
{ return _subproblem; }
Referenced by CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseVariableBase::allDofIndices(), NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), Moose::globalDofIndexToDerivative(), NonlinearSystemBase::initialSetup(), MooseVariableScalar::MooseVariableScalar(), MooseVariableScalar::reinit(), and NonlinearSystemBase::setConstraintSecondaryValues().
subproblem() [2/2]
virtual const SubProblem & SystemBase::subproblem () const inline virtual inherited
Definition at line 99 of file SystemBase.h.
{ return _subproblem; }
sys()
virtual System & AuxiliarySystem::sys () inline virtual
Definition at line 146 of file AuxiliarySystem.h.
{ return _sys; }
Referenced by ReferenceResidualProblem::initialSetup(), and ReferenceResidualProblem::updateReferenceResidual().
system() [1/2]
virtual const System & AuxiliarySystem::system () const inline override virtual
Implements SystemBase.
Definition at line 149 of file AuxiliarySystem.h.
{ return _sys; }
system() [2/2]
virtual System & AuxiliarySystem::system () inline override virtual
Get the reference to the libMesh system.
Implements SystemBase.
Definition at line 148 of file AuxiliarySystem.h.
{ return _sys; }
Referenced by TransientMultiApp::appTransferVector(), NodalNormalsPreprocessor::initialize(), ActivateElementsUserObjectBase::initSolutions(), ConsoleUtils::outputAuxiliarySystemInformation(), TransientMultiApp::setupApp(), and TransientMultiApp::solveStep().
systemMatrixTag()
virtual TagID SystemBase::systemMatrixTag () const inline virtual inherited
Return the Matrix Tag ID for System.
Reimplemented in DisplacedSystem, and NonlinearSystemBase.
Definition at line 265 of file SystemBase.h.
{ mooseError("Not implemented yet"); }
Referenced by SystemBase::defaultMatrixTags(), and DisplacedSystem::systemMatrixTag().
timedSectionName()
std::string PerfGraphInterface::timedSectionName (const std::string & section_name) const protected inherited
Returns
The name of the timed section with the name section_name.
Optionally adds a prefix if one is defined.
Definition at line 47 of file PerfGraphInterface.C.
{
  return _prefix.empty() ? "" : (_prefix + "::") + section_name;
}
Referenced by PerfGraphInterface::registerTimedSection().
timestepSetup()
void AuxiliarySystem::timestepSetup () override virtual
Reimplemented from SystemBase.
Definition at line 116 of file AuxiliarySystem.C.
{
  SystemBase::timestepSetup();
  for (unsigned int tid = 0; tid < libMesh::n_threads(); tid++)
  {
    _aux_scalar_storage.timestepSetup(tid);
    _nodal_aux_storage.timestepSetup(tid);
    _mortar_nodal_aux_storage.timestepSetup(tid);
    _nodal_vec_aux_storage.timestepSetup(tid);
    _nodal_array_aux_storage.timestepSetup(tid);
    _elemental_aux_storage.timestepSetup(tid);
    _elemental_vec_aux_storage.timestepSetup(tid);
    _elemental_array_aux_storage.timestepSetup(tid);
  }
}
timeVectorTag()
virtual TagID SystemBase::timeVectorTag () const inline virtual inherited
Ideally, we should not need this API.
There exists a really bad API "addCachedResidualDirectly " in FEProblem and DisplacedProblem This API should go away once addCachedResidualDirectly is removed in the future Return Tag ID for Time
Reimplemented in DisplacedSystem, and NonlinearSystemBase.
Definition at line 260 of file SystemBase.h.
{ mooseError("Not implemented yet"); }
Referenced by SystemBase::defaultVectorTags(), and DisplacedSystem::timeVectorTag().
update()
void SystemBase::update (bool update_libmesh_system = true) virtual inherited
Update the system (doing libMesh magic)
Definition at line 1211 of file SystemBase.C.
{
  if (update_libmesh_system)
    system().update();
}
Referenced by Adaptivity::adaptMesh(), MooseEigenSystem::combineSystemSolution(), NonlinearSystemBase::computeDamping(), NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualTags(), EigenProblem::doFreeNonlinearPowerIterations(), PointwiseRenormalizeVector::finalize(), MooseEigenSystem::initSystemSolution(), MooseEigenSystem::initSystemSolutionOld(), MooseEigenSystem::scaleSystemSolution(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::setInitialSolution(), FEProblemBase::solve(), EigenProblem::solve(), DisplacedProblem::syncSolutions(), MultiAppDofCopyTransfer::transfer(), PicardSolve::transformVariables(), SecantSolve::transformVariables(), and SteffensenSolve::transformVariables().
updateActive()
void AuxiliarySystem::updateActive (THREAD_ID tid) virtual
Definition at line 206 of file AuxiliarySystem.C.
{
  _aux_scalar_storage.updateActive(tid);
  _nodal_aux_storage.updateActive(tid);
  _mortar_nodal_aux_storage.updateActive(tid);
  _nodal_vec_aux_storage.updateActive(tid);
  _nodal_array_aux_storage.updateActive(tid);
  _elemental_aux_storage.updateActive(tid);
  _elemental_vec_aux_storage.updateActive(tid);
  _elemental_array_aux_storage.updateActive(tid);
}
validParams()
InputParameters PerfGraphInterface::validParams () static inherited
Definition at line 16 of file PerfGraphInterface.C.
{
  InputParameters params = emptyInputParameters();
  return params;
}
varKind()
Moose::VarKindType SystemBase::varKind () const inline inherited
Returns
the type of variables this system holds, e.g. nonlinear or auxiliary
Definition at line 916 of file SystemBase.h.
{ return _var_kind; }
Referenced by Coupleable::coupled(), and UserObject::UserObject().
zeroTaggedVector()
void SystemBase::zeroTaggedVector (const TagID tag) inherited
Zero vector with the given tag.
Definition at line 664 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot zero vector with TagID ",
               tag,
               " in system '",
               name(),
               "' because that tag does not exist in the problem");
  else if (!hasVector(tag))
    mooseError("Cannot zero vector tag with name '",
               _subproblem.vectorTagName(tag),
               "' in system '",
               name(),
               "' because there is no vector associated with that tag");
  getVector(tag).zero();
}
Referenced by SystemBase::zeroTaggedVectors().
zeroTaggedVectors()
void SystemBase::zeroTaggedVectors (const std::set< TagID > & tags) inherited
Zero all vectors for given tags.
Definition at line 683 of file SystemBase.C.
{
  for (const auto tag : tags)
    zeroTaggedVector(tag);
}
Referenced by NonlinearSystemBase::computeResidualAndJacobianTags(), and NonlinearSystemBase::computeResidualTags().
zeroVariables()
void SystemBase::zeroVariables (std::vector< std::string > & vars_to_be_zeroed) virtual inherited
Zero out the solution for the list of variables passed in.
@ param vars_to_be_zeroed The variable names in this vector will have their solutions set to zero after this call
Reimplemented in DisplacedSystem.
Definition at line 189 of file SystemBase.C.
{
  if (vars_to_be_zeroed.size() > 0)
  {
    NumericVector<Number> & solution = this->solution();
    auto problem = dynamic_cast<FEProblemBase *>(&_subproblem);
    if (!problem)
      mooseError("System needs to be registered in FEProblemBase for using zeroVariables.");
    AllLocalDofIndicesThread aldit(*problem, vars_to_be_zeroed, true);
    ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();
    Threads::parallel_reduce(elem_range, aldit);
    const auto & dof_indices_to_zero = aldit.getDofIndices();
    solution.close();
    for (const auto & dof : dof_indices_to_zero)
      solution.set(dof, 0);
    solution.close();
    // Call update to update the current_local_solution for this system
    system().update();
  }
}
Referenced by DisplacedSystem::zeroVariables(), SystemBase::zeroVariablesForJacobian(), and SystemBase::zeroVariablesForResidual().
zeroVariablesForJacobian()
void SystemBase::zeroVariablesForJacobian () virtual inherited
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on Jacobian evaluation by a call to addVariableToZeroOnResidual()
Definition at line 224 of file SystemBase.C.
{
  zeroVariables(_vars_to_be_zeroed_on_jacobian);
}
zeroVariablesForResidual()
void SystemBase::zeroVariablesForResidual () virtual inherited
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on residual evaluation by a call to addVariableToZeroOnResidual()
Definition at line 218 of file SystemBase.C.
{
  zeroVariables(_vars_to_be_zeroed_on_residual);
}
Friends And Related Function Documentation
ComputeIndicatorThread
friend class ComputeIndicatorThread friend
Definition at line 229 of file AuxiliarySystem.h.
ComputeMarkerThread
friend class ComputeMarkerThread friend
Definition at line 230 of file AuxiliarySystem.h.
ComputeNodalKernelBCJacobiansThread
friend class ComputeNodalKernelBCJacobiansThread friend
Definition at line 235 of file AuxiliarySystem.h.
ComputeNodalKernelBcsThread
friend class ComputeNodalKernelBcsThread friend
Definition at line 233 of file AuxiliarySystem.h.
ComputeNodalKernelJacobiansThread
friend class ComputeNodalKernelJacobiansThread friend
Definition at line 234 of file AuxiliarySystem.h.
ComputeNodalKernelsThread
friend class ComputeNodalKernelsThread friend
Definition at line 232 of file AuxiliarySystem.h.
FlagElementsThread
friend class FlagElementsThread friend
Definition at line 231 of file AuxiliarySystem.h.
Member Data Documentation
_app
MooseApp& SystemBase::_app protected inherited
Definition at line 926 of file SystemBase.h.
Referenced by NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeJacobianTags(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), and NonlinearSystem::solve().
_automatic_scaling
bool SystemBase::_automatic_scaling protected inherited
Whether to automatically scale the variables.
Definition at line 979 of file SystemBase.h.
Referenced by SystemBase::automaticScaling(), NonlinearSystem::init(), NonlinearSystemBase::initialSetup(), NonlinearEigenSystem::solve(), and NonlinearSystem::solve().
_aux_scalar_storage
ExecuteMooseObjectWarehouse<AuxScalarKernel> AuxiliarySystem::_aux_scalar_storage protected
Definition at line 214 of file AuxiliarySystem.h.
Referenced by addScalarKernel(), computeScalarVars(), customSetup(), initialSetup(), jacobianSetup(), residualSetup(), setScalarVariableCoupleableTags(), subdomainSetup(), timestepSetup(), and updateActive().
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_current_solution
const NumericVector<Number>* AuxiliarySystem::_current_solution protected
solution vector from nonlinear solver
Definition at line 186 of file AuxiliarySystem.h.
Referenced by currentSolution().
_du_dot_du
Real SystemBase::_du_dot_du protected inherited
Definition at line 943 of file SystemBase.h.
Referenced by SystemBase::duDotDu().
_du_dotdot_du
Real SystemBase::_du_dotdot_du protected inherited
Definition at line 944 of file SystemBase.h.
Referenced by SystemBase::duDotDotDu().
_elem_vars
std::vector<std::vector<MooseVariableFieldBase *> > AuxiliarySystem::_elem_vars protected
Elemental variables.
These may be either finite element or finite volume variables
Definition at line 210 of file AuxiliarySystem.h.
Referenced by addVariable(), AuxiliarySystem(), ComputeIndicatorThread::onElement(), ComputeMarkerThread::onElement(), ComputeIndicatorThread::onInternalSide(), reinitElem(), reinitElemFace(), and ComputeMarkerThread::subdomainChanged().
_elemental_array_aux_storage
ExecuteMooseObjectWarehouse<ArrayAuxKernel> AuxiliarySystem::_elemental_array_aux_storage protected
Definition at line 227 of file AuxiliarySystem.h.
Referenced by addKernel(), computeElementalArrayVars(), customSetup(), elemArrayAuxWarehouse(), getDependObjects(), initialSetup(), jacobianSetup(), residualSetup(), subdomainSetup(), timestepSetup(), and updateActive().
_elemental_aux_storage
ExecuteMooseObjectWarehouse<AuxKernel> AuxiliarySystem::_elemental_aux_storage protected
Definition at line 219 of file AuxiliarySystem.h.
Referenced by addKernel(), computeElementalVars(), customSetup(), elemAuxWarehouse(), getDependObjects(), initialSetup(), jacobianSetup(), needMaterialOnSide(), residualSetup(), subdomainSetup(), timestepSetup(), and updateActive().
_elemental_vec_aux_storage
ExecuteMooseObjectWarehouse<VectorAuxKernel> AuxiliarySystem::_elemental_vec_aux_storage protected
Definition at line 223 of file AuxiliarySystem.h.
Referenced by addKernel(), computeElementalVecVars(), customSetup(), elemVectorAuxWarehouse(), getDependObjects(), initialSetup(), jacobianSetup(), needMaterialOnSide(), residualSetup(), subdomainSetup(), timestepSetup(), and updateActive().
_factory
Factory& SystemBase::_factory protected inherited
Definition at line 927 of file SystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addConstraint(), NonlinearSystemBase::addDamper(), NonlinearSystemBase::addDGKernel(), NonlinearSystemBase::addDiracKernel(), NonlinearSystemBase::addInterfaceKernel(), addKernel(), MooseEigenSystem::addKernel(), NonlinearSystemBase::addKernel(), NonlinearSystemBase::addNodalKernel(), addScalarKernel(), NonlinearSystemBase::addScalarKernel(), NonlinearSystemBase::addSplit(), addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), and SystemBase::addVariable().
_fe_problem
FEProblemBase& AuxiliarySystem::_fe_problem protected
Definition at line 181 of file AuxiliarySystem.h.
Referenced by addDotVectors(), AuxiliarySystem(), clearScalarVariableCoupleableTags(), compute(), computeElementalVarsHelper(), computeMortarNodalVars(), computeNodalVarsHelper(), computeScalarVars(), serializedSolution(), and setScalarVariableCoupleableTags().
_matrix_tag_active_flags
std::vector<bool> SystemBase::_matrix_tag_active_flags protected inherited
Active flags for tagged matrices.
Definition at line 951 of file SystemBase.h.
Referenced by SystemBase::activeAllMatrixTags(), SystemBase::activeMatrixTag(), SystemBase::deactiveAllMatrixTags(), SystemBase::deactiveMatrixTag(), and SystemBase::matrixTagActive().
_max_var_n_dofs_per_elem
size_t SystemBase::_max_var_n_dofs_per_elem protected inherited
Maximum number of dofs for any one variable on any one element.
Definition at line 967 of file SystemBase.h.
Referenced by SystemBase::assignMaxVarNDofsPerElem(), and SystemBase::getMaxVarNDofsPerElem().
_max_var_n_dofs_per_node
size_t SystemBase::_max_var_n_dofs_per_node protected inherited
Maximum number of dofs for any one variable on any one node.
Definition at line 970 of file SystemBase.h.
Referenced by SystemBase::assignMaxVarNDofsPerNode(), and SystemBase::getMaxVarNDofsPerNode().
_max_var_number
unsigned int SystemBase::_max_var_number protected inherited
Maximum variable number.
Definition at line 938 of file SystemBase.h.
Referenced by SystemBase::addVariable(), and SystemBase::getMaxVariableNumber().
_mesh
MooseMesh& SystemBase::_mesh protected inherited
Definition at line 929 of file SystemBase.h.
Referenced by SystemBase::addVariable(), NonlinearSystemBase::assembleScalingVector(), SystemBase::augmentSendList(), NonlinearSystemBase::checkKernelCoverage(), NonlinearSystemBase::computeDamping(), computeElementalVarsHelper(), NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), computeMortarNodalVars(), NonlinearSystemBase::computeNodalBCs(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), computeNodalVarsHelper(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), NonlinearSystemBase::findImplicitGeometricCouplingEntries(), NonlinearSystemBase::getNodeDofs(), SystemBase::mesh(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::setInitialSolution(), SystemBase::setVariableGlobalDoFs(), and SystemBase::zeroVariables().
_mortar_nodal_aux_storage
ExecuteMooseObjectWarehouse<AuxKernel> AuxiliarySystem::_mortar_nodal_aux_storage protected
Definition at line 218 of file AuxiliarySystem.h.
Referenced by addKernel(), computeMortarNodalVars(), customSetup(), getDependObjects(), initialSetup(), jacobianSetup(), residualSetup(), subdomainSetup(), timestepSetup(), and updateActive().
_name
std::string SystemBase::_name protected inherited
The name of this system.
Definition at line 931 of file SystemBase.h.
_nodal_array_aux_storage
ExecuteMooseObjectWarehouse<ArrayAuxKernel> AuxiliarySystem::_nodal_array_aux_storage protected
Definition at line 226 of file AuxiliarySystem.h.
Referenced by addKernel(), computeNodalArrayVars(), customSetup(), getDependObjects(), initialSetup(), jacobianSetup(), nodalArrayAuxWarehouse(), residualSetup(), subdomainSetup(), timestepSetup(), and updateActive().
_nodal_aux_storage
ExecuteMooseObjectWarehouse<AuxKernel> AuxiliarySystem::_nodal_aux_storage protected
Definition at line 217 of file AuxiliarySystem.h.
Referenced by addKernel(), computeNodalVars(), customSetup(), getDependObjects(), initialSetup(), jacobianSetup(), nodalAuxWarehouse(), residualSetup(), subdomainSetup(), timestepSetup(), and updateActive().
_nodal_vars
std::vector<std::vector<MooseVariableFEBase *> > AuxiliarySystem::_nodal_vars protected
Definition at line 204 of file AuxiliarySystem.h.
Referenced by addVariable(), AuxiliarySystem(), ComputeNodalKernelBCJacobiansThread::onNode(), ComputeNodalKernelBcsThread::onNode(), ComputeNodalKernelJacobiansThread::onNode(), ComputeNodalKernelsThread::onNode(), reinitElem(), and reinitElemFace().
_nodal_vec_aux_storage
ExecuteMooseObjectWarehouse<VectorAuxKernel> AuxiliarySystem::_nodal_vec_aux_storage protected
Definition at line 222 of file AuxiliarySystem.h.
Referenced by addKernel(), computeNodalVecVars(), customSetup(), getDependObjects(), initialSetup(), jacobianSetup(), nodalVectorAuxWarehouse(), residualSetup(), subdomainSetup(), timestepSetup(), and updateActive().
_numbered_vars
std::vector<std::vector<MooseVariableFieldBase *> > SystemBase::_numbered_vars protected inherited
Map variable number to its pointer.
Definition at line 976 of file SystemBase.h.
Referenced by SystemBase::addVariable(), and SystemBase::getVariable().
_pg_moose_app
MooseApp& PerfGraphInterface::_pg_moose_app protected inherited
The MooseApp that owns the PerfGraph.
Definition at line 124 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::perfGraph().
_prefix
const std::string PerfGraphInterface::_prefix protected inherited
A prefix to use for all sections.
Definition at line 127 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::timedSectionName().
_saved_dot_old
NumericVector<Real>* SystemBase::_saved_dot_old protected inherited
Definition at line 958 of file SystemBase.h.
Referenced by SystemBase::restoreOldSolutions(), and SystemBase::saveOldSolutions().
_saved_dotdot_old
NumericVector<Real>* SystemBase::_saved_dotdot_old protected inherited
Definition at line 959 of file SystemBase.h.
Referenced by SystemBase::restoreOldSolutions(), and SystemBase::saveOldSolutions().
_saved_old
NumericVector<Real>* SystemBase::_saved_old protected inherited
Definition at line 954 of file SystemBase.h.
_saved_older
NumericVector<Real>* SystemBase::_saved_older protected inherited
Definition at line 955 of file SystemBase.h.
_saved_solution_states
std::vector<NumericVector<Number> *> SystemBase::_saved_solution_states private inherited
The saved solution states (0 = current, 1 = old, 2 = older, etc)
Definition at line 1000 of file SystemBase.h.
Referenced by SystemBase::restoreOldSolutions(), and SystemBase::saveOldSolutions().
_serialized_solution
std::unique_ptr<NumericVector<Number> > AuxiliarySystem::_serialized_solution protected
Serialized version of the solution vector, or nullptr if a serialized solution is not needed.
Definition at line 189 of file AuxiliarySystem.h.
Referenced by compute(), serializedSolution(), and serializeSolution().
_solution_state
std::vector<NumericVector<Number> *> AuxiliarySystem::_solution_state protected
The current states of the solution (0 = current, 1 = old, etc)
Definition at line 201 of file AuxiliarySystem.h.
_solution_states
std::array<std::vector<NumericVector<Number> *>, 2> SystemBase::_solution_states private inherited
The solution states (0 = current, 1 = old, 2 = older, etc)
Definition at line 998 of file SystemBase.h.
Referenced by SystemBase::copyOldSolutions(), SystemBase::copySolutionsBackwards(), SystemBase::hasSolutionState(), SystemBase::needSolutionState(), SystemBase::restoreOldSolutions(), SystemBase::saveOldSolutions(), and SystemBase::solutionState().
_solution_states_initialized
bool SystemBase::_solution_states_initialized protected inherited
Whether or not the solution states have been initialized.
Definition at line 985 of file SystemBase.h.
Referenced by SystemBase::initSolutionState(), and SystemBase::solutionStatesInitialized().
_subproblem
SubProblem& SystemBase::_subproblem protected inherited
Definition at line 924 of file SystemBase.h.
Referenced by SystemBase::activeAllMatrixTags(), SystemBase::activeMatrixTag(), SystemBase::addMatrix(), SystemBase::addScalingVector(), SystemBase::addVariable(), SystemBase::addVector(), SystemBase::associateMatrixToTag(), SystemBase::associateVectorToTag(), SystemBase::augmentSendList(), SystemBase::closeTaggedVector(), SystemBase::computingScalingJacobian(), SystemBase::copyVars(), SystemBase::deactiveAllMatrixTags(), SystemBase::deactiveMatrixTag(), SystemBase::disassociateDefaultMatrixTags(), SystemBase::disassociateDefaultVectorTags(), SystemBase::disassociateMatrixFromTag(), SystemBase::disassociateVectorFromTag(), SystemBase::getMatrix(), NonlinearSystemBase::getResidualNonTimeVector(), NonlinearSystemBase::getResidualTimeVector(), SystemBase::getVector(), SystemBase::matrixTagActive(), SystemBase::needSolutionState(), SystemBase::prepare(), SystemBase::prepareFace(), SystemBase::reinitElem(), SystemBase::removeMatrix(), SystemBase::removeVector(), NonlinearSystemBase::residualGhosted(), NonlinearSystemBase::setSolution(), SystemBase::setVariableGlobalDoFs(), SystemBase::subproblem(), SystemBase::zeroTaggedVector(), and SystemBase::zeroVariables().
_sys
System& AuxiliarySystem::_sys protected
Definition at line 183 of file AuxiliarySystem.h.
Referenced by AuxiliarySystem(), computeElementalVarsHelper(), computeMortarNodalVars(), computeNodalVarsHelper(), computeScalarVars(), serializedSolution(), serializeSolution(), solutionInternal(), sys(), and system().
_tagged_matrices
std::vector<SparseMatrix<Number> *> SystemBase::_tagged_matrices protected inherited
Tagged matrices (pointer)
Definition at line 949 of file SystemBase.h.
Referenced by SystemBase::associateMatrixToTag(), SystemBase::disassociateMatrixFromTag(), SystemBase::getMatrix(), SystemBase::hasMatrix(), and SystemBase::removeMatrix().
_tagged_vectors
std::vector<NumericVector<Number> *> SystemBase::_tagged_vectors protected inherited
Tagged vectors (pointer)
Definition at line 947 of file SystemBase.h.
Referenced by SystemBase::associateVectorToTag(), SystemBase::disassociateVectorFromTag(), SystemBase::getVector(), SystemBase::hasVector(), and SystemBase::removeVector().
_time_integrator
std::shared_ptr<TimeIntegrator> SystemBase::_time_integrator protected inherited
Time integrator.
Definition at line 973 of file SystemBase.h.
Referenced by addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), DisplacedSystem::addTimeIntegrator(), compute(), NonlinearSystemBase::computeResidualAndJacobianTags(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::computeTimeDerivatives(), SystemBase::getSharedTimeIntegrator(), SystemBase::getTimeIntegrator(), NonlinearSystemBase::onTimestepBegin(), NonlinearEigenSystem::solve(), and NonlinearSystem::solve().
_u_dot
NumericVector<Number>* AuxiliarySystem::_u_dot protected
solution vector for u^dot
Definition at line 191 of file AuxiliarySystem.h.
Referenced by addDotVectors(), and solutionUDot().
_u_dot_old
NumericVector<Number>* AuxiliarySystem::_u_dot_old protected
Old solution vector for u^dot.
Definition at line 196 of file AuxiliarySystem.h.
Referenced by addDotVectors(), and solutionUDotOld().
_u_dotdot
NumericVector<Number>* AuxiliarySystem::_u_dotdot protected
solution vector for u^dotdot
Definition at line 193 of file AuxiliarySystem.h.
Referenced by addDotVectors(), and solutionUDotDot().
_u_dotdot_old
NumericVector<Number>* AuxiliarySystem::_u_dotdot_old protected
Old solution vector for u^dotdot.
Definition at line 198 of file AuxiliarySystem.h.
Referenced by addDotVectors(), and solutionUDotDotOld().
_var_all_dof_indices
std::vector<dof_id_type> SystemBase::_var_all_dof_indices protected inherited
Container for the dof indices of a given variable.
Definition at line 988 of file SystemBase.h.
Referenced by SystemBase::getVariableGlobalDoFs(), and SystemBase::setVariableGlobalDoFs().
_var_kind
Moose::VarKindType SystemBase::_var_kind protected inherited
default kind of variables in this system
Definition at line 962 of file SystemBase.h.
Referenced by SystemBase::varKind().
_var_map
std::map<unsigned int, std::set<SubdomainID> > SystemBase::_var_map protected inherited
Map of variables (variable id -> array of subdomains where it lives)
Definition at line 936 of file SystemBase.h.
Referenced by SystemBase::addVariable(), SystemBase::getSubdomainsForVar(), and SystemBase::getVariableBlocks().
_var_to_copy
std::vector<VarCopyInfo> SystemBase::_var_to_copy protected inherited
Definition at line 964 of file SystemBase.h.
Referenced by SystemBase::addVariableToCopy(), SystemBase::copyVars(), and SystemBase::hasVarCopy().
_vars
std::vector<VariableWarehouse> SystemBase::_vars protected inherited
Variable warehouses (one for each thread)
Definition at line 934 of file SystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addInterfaceKernel(), addVariable(), SystemBase::addVariable(), SystemBase::applyScalingFactors(), NonlinearSystemBase::assembleScalingVector(), SystemBase::clearAllDofIndices(), compute(), SystemBase::customSetup(), SystemBase::getActualFieldVariable(), SystemBase::getFieldVariable(), SystemBase::getFVVariable(), SystemBase::getMinQuadratureOrder(), getMinQuadratureOrder(), SystemBase::getScalarVariable(), SystemBase::getScalarVariables(), SystemBase::getVariable(), SystemBase::getVariableNames(), SystemBase::getVariables(), SystemBase::initialSetup(), SystemBase::jacobianSetup(), SystemBase::nFieldVariables(), SystemBase::nFVVariables(), SystemBase::nVariables(), SystemBase::prepare(), SystemBase::prepareFace(), SystemBase::prepareLowerD(), SystemBase::prepareNeighbor(), SystemBase::reinitElem(), SystemBase::reinitElemFace(), SystemBase::reinitLowerD(), SystemBase::reinitNeighbor(), SystemBase::reinitNeighborFace(), SystemBase::reinitNode(), SystemBase::reinitNodeFace(), SystemBase::reinitNodes(), SystemBase::reinitNodesNeighbor(), SystemBase::reinitScalars(), SystemBase::residualSetup(), SystemBase::setActiveScalarVariableCoupleableVectorTags(), SystemBase::setActiveVariableCoupleableVectorTags(), NonlinearSystemBase::setupScalingData(), SystemBase::subdomainSetup(), and SystemBase::timestepSetup().
_vars_to_be_zeroed_on_jacobian
std::vector<std::string> SystemBase::_vars_to_be_zeroed_on_jacobian protected inherited
Definition at line 941 of file SystemBase.h.
Referenced by SystemBase::addVariableToZeroOnJacobian(), and SystemBase::zeroVariablesForJacobian().
_vars_to_be_zeroed_on_residual
std::vector<std::string> SystemBase::_vars_to_be_zeroed_on_residual protected inherited
Definition at line 940 of file SystemBase.h.
Referenced by SystemBase::addVariableToZeroOnResidual(), and SystemBase::zeroVariablesForResidual().
_verbose
bool SystemBase::_verbose protected inherited
True if printing out additional information.
Definition at line 982 of file SystemBase.h.
Referenced by SystemBase::applyScalingFactors(), and SystemBase::setVerboseFlag().
The documentation for this class was generated from the following files:
moose/framework/include/systems/AuxiliarySystem.h
moose/framework/src/systems/AuxiliarySystem.C