Zapdos: FileLineInfo Class Reference
FileLineInfo Class Reference
Holds file and line information.
#include <FileLineInfo.h>
Public Member Functions
FileLineInfo ()
FileLineInfo (const std::string &f, int l)
bool isValid () const
int line () const
std::string file () const
Protected Attributes
int _line
std::string _file
Detailed Description
Holds file and line information.
Definition at line 18 of file FileLineInfo.h.
Constructor & Destructor Documentation
FileLineInfo() [1/2]
FileLineInfo::FileLineInfo ()
Definition at line 12 of file FileLineInfo.C.
: _line(-1) {}
FileLineInfo() [2/2]
FileLineInfo::FileLineInfo (const std::string & f, int l)
Definition at line 14 of file FileLineInfo.C.
: _line(l), _file(f) {}
Member Function Documentation
file()
std::string FileLineInfo::file () const
Definition at line 29 of file FileLineInfo.C.
{
  return _file;
}
Referenced by JsonSyntaxTree::addActionTask(), JsonSyntaxTree::addParameters(), MooseServer::gatherDocumentDefinitionLocations(), and Factory::reg().
isValid()
bool FileLineInfo::isValid () const
Returns
Whether this holds valid file line information.
Definition at line 17 of file FileLineInfo.C.
{
  return !_file.empty() && _line >= 0;
}
Referenced by JsonSyntaxTree::addActionTask(), FileLineInfoMap::addInfo(), JsonSyntaxTree::addParameters(), and MooseServer::gatherDocumentDefinitionLocations().
line()
int FileLineInfo::line () const
Definition at line 23 of file FileLineInfo.C.
{
  return _line;
}
Referenced by JsonSyntaxTree::addActionTask(), JsonSyntaxTree::addParameters(), and MooseServer::gatherDocumentDefinitionLocations().
Member Data Documentation
_file
std::string FileLineInfo::_file protected
Definition at line 32 of file FileLineInfo.h.
Referenced by file(), and isValid().
_line
int FileLineInfo::_line protected
Definition at line 31 of file FileLineInfo.h.
Referenced by isValid(), and line().
The documentation for this class was generated from the following files:
moose/framework/include/utils/FileLineInfo.h
moose/framework/src/utils/FileLineInfo.C