Zapdos: CommandLine Class Reference
CommandLine Class Reference
This class wraps provides and tracks access to command line parameters.
#include <CommandLine.h>
Classes
struct Option
Public Types
enum ARGUMENT { NONE , OPTIONAL , REQUIRED }
Type of argument for a given option.
Public Member Functions
CommandLine (int argc, char *argv[])
CommandLine (const CommandLine &other)
virtual ~CommandLine ()
void addArguments (int argc, char *argv[])
void addArgument (std::string)
void initForMultiApp (const std::string &)
Removes multiapp parameters not associated with the supplied name.
const std::vector< std::string > & getArguments ()
Return the raw argv arguments as a vector.
void addCommandLineOptionsFromParams (InputParameters &params)
void populateInputParams (InputParameters &params)
void addOption (const std::string &name, Option cli_opt)
bool search (const std::string &option_name)
This routine searches the command line for the given option "handle" and returns a boolean indicating whether it was found.
template<typename T >
bool search (const std::string &option_name, T &argument)
template<typename T >
bool search (const std::string &option_name, std::vector< T > &argument)
std::vector< std::string >::const_iterator find (const std::string &option_name) const
Returns an iterator to the underlying argument vector to the position of the option or end if the option is not on the command line.
std::vector< std::string >::const_iterator begin () const
std::vector< std::string >::const_iterator end () const
std::string getExecutableName () const
Get the executable name.
void printUsage () const
Print the usage info for this command line.
void markHitParamUsed (int argi)
void markHitParam (int argi)
std::set< int > unused (const Parallel::Communicator &comm)
Protected Member Functions
template<typename T >
void setArgument (std::stringstream &stream, T &argument)
Used to set the argument value, allows specialization.
Protected Attributes
std::map< std::string, Option > _cli_options
Command line options.
Private Attributes
std::set< int > _used_hiti
indices of CLI args that have been marked as used
std::set< int > _hiti
indices of CLI args that are HIT syntax parameters
std::vector< std::string > _argv
Storage for the raw argv.
std::vector< std::string > _args
Detailed Description
This class wraps provides and tracks access to command line parameters.
Definition at line 31 of file CommandLine.h.
Member Enumeration Documentation
ARGUMENT
enum CommandLine::ARGUMENT
Type of argument for a given option.
Enumerator
NONE
OPTIONAL
REQUIRED
Definition at line 35 of file CommandLine.h.
  {
    NONE,
    OPTIONAL,
    REQUIRED
  };
Constructor & Destructor Documentation
CommandLine() [1/2]
CommandLine::CommandLine (int argc, char * argv[])
Definition at line 22 of file CommandLine.C.
{ addArguments(argc, argv); }
CommandLine() [2/2]
CommandLine::CommandLine (const CommandLine & other)
Definition at line 24 of file CommandLine.C.
  : _cli_options(other._cli_options),
    _used_hiti(other._used_hiti),
    _hiti(other._hiti),
    _argv(other._argv),
    _args(other._args)
{
}
~CommandLine()
CommandLine::~CommandLine () virtual
Definition at line 61 of file CommandLine.C.
{}
Member Function Documentation
addArgument()
void CommandLine::addArgument (std::string arg)
Definition at line 41 of file CommandLine.C.
{
  _argv.push_back(arg);
  auto arg_value = std::string(arg);
  // Handle using a "="
  if (arg_value.find("=") != std::string::npos)
  {
    std::vector<std::string> arg_split;
    MooseUtils::tokenize(arg_value, arg_split, 1, "=");
    for (auto & arg_piece : arg_split)
      _args.push_back(MooseUtils::trim(arg_piece));
  }
  else
    _args.push_back(arg_value);
}
Referenced by addArguments().
addArguments()
void CommandLine::addArguments (int argc, char * argv[])
Definition at line 34 of file CommandLine.C.
{
  for (int i = 0; i < argc; i++)
    addArgument(argv[i]);
}
Referenced by CommandLine().
addCommandLineOptionsFromParams()
void CommandLine::addCommandLineOptionsFromParams (InputParameters & params)
Definition at line 113 of file CommandLine.C.
{
  for (const auto & it : params)
  {
    Option cli_opt;
    std::vector<std::string> syntax;
    std::string orig_name = it.first;
    cli_opt.description = params.getDocString(orig_name);
    if (!params.isPrivate(orig_name))
      // If a param is private then it shouldn't have any command line syntax.
      syntax = params.getSyntax(orig_name);
    cli_opt.cli_syntax = syntax;
    cli_opt.required = false;
    if (params.have_parameter<bool>(orig_name))
      cli_opt.argument_type = CommandLine::NONE;
    else
      cli_opt.argument_type = CommandLine::REQUIRED;
    addOption(orig_name, cli_opt);
  }
}
addOption()
void CommandLine::addOption (const std::string & name, Option cli_opt)
Definition at line 191 of file CommandLine.C.
{
  for (const auto & stx : cli_opt.cli_syntax)
    cli_opt.cli_switch.push_back(stx.substr(0, stx.find_first_of(" =")));
  _cli_options[name] = cli_opt;
}
Referenced by addCommandLineOptionsFromParams().
begin()
std::vector< std::string >::const_iterator CommandLine::begin () const
Definition at line 219 of file CommandLine.C.
{
  return _args.begin();
}
end()
std::vector< std::string >::const_iterator CommandLine::end () const
Definition at line 225 of file CommandLine.C.
{
  return _args.end();
}
find()
std::vector< std::string >::const_iterator CommandLine::find (const std::string & option_name) const
Returns an iterator to the underlying argument vector to the position of the option or end if the option is not on the command line.
Definition at line 200 of file CommandLine.C.
{
  auto pos = _cli_options.find(option_name);
  auto it = _args.end();
  if (pos != _cli_options.end())
  {
    for (const auto & search_string : pos->second.cli_switch)
    {
      auto it = std::find(_args.begin(), _args.end(), search_string);
      if (it != _args.end())
        return it;
    }
  }
  return it;
}
getArguments()
const std::vector< std::string > & CommandLine::getArguments () inline
Return the raw argv arguments as a vector.
Definition at line 74 of file CommandLine.h.
{ return _argv; }
Referenced by Moose::PetscSupport::petscSetupOutput().
getExecutableName()
std::string CommandLine::getExecutableName () const
Get the executable name.
Definition at line 252 of file CommandLine.C.
{
  // Grab the first item out of argv
  std::string command(_args[0]);
  return command.substr(command.find_last_of("/\\") + 1);
}
Referenced by printUsage().
initForMultiApp()
void CommandLine::initForMultiApp (const std::string & subapp_full_name)
Removes multiapp parameters not associated with the supplied name.
When a sub-application is created the CommandLine object from the master application is copied and supplied to the sub-app. This method cleans up the copy so it is ready to be used for a sub-application by removing parameters that are not associated with the provided sub-application name.
See MultiApp::createApp
Definition at line 64 of file CommandLine.C.
{
  // Get the name and number for the current sub-application
  std::string sub_name;
  int sub_num = std::numeric_limits<int>::min(); // this initial value should never be used
  pcrecpp::RE("(\\S*?)(\\d*)").FullMatch(subapp_full_name, &sub_name, &sub_num);
  if (sub_num == std::numeric_limits<int>::min())
    mooseError("The sub-application name '", subapp_full_name, "' must contain a number.");
  // "remove" CLI args for other sub-applications; remove_if just moves items to the end, so
  // an erase is needed to actually remove the items
  auto new_end = std::remove_if(
      _argv.begin(),
      _argv.end(),
      [&sub_name, sub_num](const std::string & arg)
      {
        // Determine if the current command line argument ('arg') and extract the sub-application
        // name and number. If 'arg' is not command line argument for sub-application then the regex
        // match fails and the argument is retained.
        std::string arg_sub_name;
        int arg_sub_num = -1;
        pcrecpp::RE("(\\S*?)(\\d*):").PartialMatch(arg, &arg_sub_name, &arg_sub_num);
        if (!arg_sub_name.empty())
        {
          // The argument should be retained if names match and the current argument doesn't have
          // a number or the supplied sub-application number and the current argument number match
          bool keep = (sub_name == arg_sub_name && (arg_sub_num == -1 || arg_sub_num == sub_num));
          return !keep;
        }
        return false;
      });
  _argv.erase(new_end, _argv.end());
  // If there is an argument meant for a nested subapp, we will want to remove
  // the leading app name
  for (auto & arg : _argv)
  {
    auto pos = arg.find(":", 0);
    if (pos != std::string::npos && arg.find(":", pos + 1) != std::string::npos)
      arg = subapp_full_name + "_" + arg.substr(pos + 1, arg.length() - pos - 1);
  }
  // Clear hit CLI arguments, these will be populated after the sub-application is created
  _hiti.clear();
  _used_hiti.clear();
}
markHitParam()
void CommandLine::markHitParam (int argi) inline
Definition at line 121 of file CommandLine.h.
{ _hiti.insert(argi); }
markHitParamUsed()
void CommandLine::markHitParamUsed (int argi) inline
Definition at line 120 of file CommandLine.h.
{ _used_hiti.insert(argi); };
populateInputParams()
void CommandLine::populateInputParams (InputParameters & params)
Definition at line 138 of file CommandLine.C.
{
  for (const auto & it : params)
  {
    std::string orig_name = it.first;
    if (search(orig_name))
    {
      if (params.have_parameter<std::string>(orig_name))
      {
        search(orig_name, params.set<std::string>(orig_name));
        continue;
      }
      if (params.have_parameter<std::vector<std::string>>(orig_name))
      {
        search(orig_name, params.set<std::vector<std::string>>(orig_name));
        continue;
      }
      if (params.have_parameter<Real>(orig_name))
      {
        search(orig_name, params.set<Real>(orig_name));
        continue;
      }
      if (params.have_parameter<unsigned int>(orig_name))
      {
        search(orig_name, params.set<unsigned int>(orig_name));
        continue;
      }
      if (params.have_parameter<int>(orig_name))
      {
        search(orig_name, params.set<int>(orig_name));
        continue;
      }
      if (params.have_parameter<bool>(orig_name))
      {
        search(orig_name, params.set<bool>(orig_name));
        continue;
      }
    }
    else if (params.isParamRequired(orig_name))
      mooseError("Missing required command-line parameter: ",
                 orig_name,
                 "\nDoc String: ",
                 params.getDocString(orig_name));
  }
}
printUsage()
void CommandLine::printUsage () const
Print the usage info for this command line.
Definition at line 260 of file CommandLine.C.
{
  Moose::out << "Usage: " << getExecutableName() << " [<options>]\n\n"
             << "Options:\n"
             << std::left;
  for (const auto & i : _cli_options)
  {
    if (i.second.cli_syntax.empty())
      continue;
    std::stringstream oss;
    for (unsigned int j = 0; j < i.second.cli_syntax.size(); ++j)
    {
      if (j)
        oss << " ";
      oss << i.second.cli_syntax[j];
    }
    Moose::out << "  " << std::setw(50) << oss.str() << i.second.description << "\n";
  }
  Moose::out << "\nSolver Options:\n"
             << "  See solver manual for details (Petsc or Trilinos)" << std::endl;
}
Referenced by search().
search() [1/3]
bool CommandLine::search (const std::string & option_name)
This routine searches the command line for the given option "handle" and returns a boolean indicating whether it was found.
If the given option has an argument it is also filled in.
Definition at line 231 of file CommandLine.C.
{
  auto pos = _cli_options.find(option_name);
  if (pos != _cli_options.end())
  {
    for (const auto & search_string : pos->second.cli_switch)
      for (auto & arg : _args)
        if (arg == search_string)
          return true;
    if (pos->second.required)
    {
      printUsage();
      mooseError("Required parameter: ", option_name, " missing");
    }
    return false;
  }
  mooseError("Unrecognized option name: ", option_name);
}
Referenced by populateInputParams().
search() [2/3]
template<typename T > bool CommandLine::search (const std::string & option_name, std::vector< T > & argument)
Definition at line 217 of file CommandLine.h.
{
  std::map<std::string, Option>::iterator pos = _cli_options.find(option_name);
  if (pos != _cli_options.end())
  {
    for (unsigned int i = 0; i < pos->second.cli_switch.size(); ++i)
    {
      for (size_t j = 0; j < _argv.size(); j++)
      {
        auto arg = _argv[j];
        if (arg == pos->second.cli_switch[i])
        {
          // "Flag" CLI options added vector of Boolean types may apprear multiple times on the
          // command line (like a repeated verbosity flag to increase verbosity), when we see them
          // we append a true value to the vector.
          if (pos->second.argument_type == NONE)
            argument.push_back(T());
          else
            while (j + 1 < _argv.size() && _argv[j + 1][0] != '-' &&
                   _argv[j + 1].find("=") == std::string::npos)
            {
              std::stringstream ss;
              ss << _argv[j + 1];
              T item;
              setArgument(ss, item);
              argument.push_back(item);
              ++j;
            }
        }
      }
    }
    if (pos->second.required && argument.empty())
    {
      Moose::err << "Required parameter: " << option_name << " missing\n";
      printUsage();
    }
    return false;
  }
  mooseError("Unrecognized option name");
}
search() [3/3]
template<typename T > bool CommandLine::search (const std::string & option_name, T & argument)
Definition at line 176 of file CommandLine.h.
{
  std::map<std::string, Option>::iterator pos = _cli_options.find(option_name);
  if (pos != _cli_options.end())
  {
    for (unsigned int i = 0; i < pos->second.cli_switch.size(); ++i)
    {
      for (size_t j = 0; j < _args.size(); j++)
      {
        auto arg = _args[j];
        if (arg == pos->second.cli_switch[i])
        {
          // "Flag" CLI options are added as Boolean types, when we see them
          // we set the Boolean argument to true
          if (pos->second.argument_type == NONE)
            argument = true;
          else if (j + 1 < _args.size())
          {
            std::stringstream ss;
            ss << _args[j + 1];
            setArgument(ss, argument);
          }
          return true;
        }
      }
    }
    if (pos->second.required)
    {
      Moose::err << "Required parameter: " << option_name << " missing\n";
      printUsage();
    }
    return false;
  }
  mooseError("Unrecognized option name");
}
setArgument()
template<typename T > void CommandLine::setArgument (std::stringstream & stream, T & argument) protected
Used to set the argument value, allows specialization.
Definition at line 165 of file CommandLine.h.
{
  stream >> argument;
}
Referenced by search().
unused()
std::set< int > CommandLine::unused (const Parallel::Communicator & comm) inline
Definition at line 126 of file CommandLine.h.
  {
    comm.set_union(_hiti);
    comm.set_union(_used_hiti);
    std::set<int> unused;
    for (int i : _hiti)
    {
      if (_used_hiti.count(i) == 0)
        unused.insert(i);
    }
    return unused;
  }
Referenced by unused().
Member Data Documentation
_args
std::vector<std::string> CommandLine::_args private
Definition at line 160 of file CommandLine.h.
Referenced by addArgument(), begin(), end(), find(), getExecutableName(), and search().
_argv
std::vector<std::string> CommandLine::_argv private
Storage for the raw argv.
Definition at line 158 of file CommandLine.h.
Referenced by addArgument(), getArguments(), initForMultiApp(), and search().
_cli_options
std::map<std::string, Option> CommandLine::_cli_options protected
Command line options.
Definition at line 148 of file CommandLine.h.
Referenced by addOption(), find(), printUsage(), and search().
_hiti
std::set<int> CommandLine::_hiti private
indices of CLI args that are HIT syntax parameters
Definition at line 155 of file CommandLine.h.
Referenced by markHitParam(), and unused().
_used_hiti
std::set<int> CommandLine::_used_hiti private
indices of CLI args that have been marked as used
Definition at line 152 of file CommandLine.h.
Referenced by markHitParamUsed(), and unused().
The documentation for this class was generated from the following files:
moose/framework/include/parser/CommandLine.h
moose/framework/src/parser/CommandLine.C