Zapdos: ReporterProducerEnum Class Reference
ReporterProducerEnum Class Reference
MooseEnum designed for the ReporterContext objects to define how a ReporterValue can and is being produced.
#include <ReporterMode.h>
Public Types
enum class CompareMode { COMPARE_NAME , COMPARE_ID , COMPARE_BOTH }
Enum item for controlling comparison in the compareCurrent method.
Public Member Functions
ReporterProducerEnum ()
void clear ()
Clear all available items (i.e., create an empty MooseEnum)
operator int () const
Cast operators to make this object behave as value_types and std::string these methods can be used so that this class behaves more like a normal value_type enumeration.
operator std::string () const
bool operator== (const char *value) const
Comparison operators for comparing with character constants, MooseEnums or integer values.
bool operator== (int value) const
bool operator== (unsigned short value) const
bool operator== (const MooseEnum &value) const
bool operator!= (const char *value) const
bool operator!= (int value) const
bool operator!= (unsigned short value) const
bool operator!= (const MooseEnum &value) const
bool compareCurrent (const MooseEnum &other, CompareMode mode=CompareMode::COMPARE_NAME) const
Method for comparing currently set values between MooseEnum.
virtual bool isValid () const override
IsValid.
template<typename T >
T getEnum () const
get the current value cast to the enum type T
virtual void deprecate (const std::string &name, const std::string &raw_name="")
Deprecates various options in the MOOSE enum.
std::vector< std::string > getNames () const
Method for returning a vector of all valid enumeration names for this instance.
std::string getRawNames () const
Method for returning the raw name strings for this instance.
std::vector< int > getIDs () const
Method for returning a vector of ids for this instance.
bool isOutOfRangeAllowed () const
isOutOfRangeAllowed
const std::set< MooseEnumItem > & items () const
Return the complete set of available flags.
void addDocumentation (const std::string &name, const std::string &doc)
Add an item documentation string.
const std::map< MooseEnumItem, std::string > & getItemDocumentation () const
Get the map containing each item's documentation string.
int getNextValidID () const
Compute the next valid ID.
MooseEnumBase & operator+= (const std::string &name)
Adds an enumeration item from name.
MooseEnumBase & operator+= (const std::initializer_list< std::string > &names)
Adds enumeration items from a list of names.
template<typename... Args>
void insert (const ReporterMode &mode, Args... modes)
void insert (const ReporterMode &mode)
void assign (const std::string &name)
void assign (int value)
void assign (const MooseEnumItem &item)
std::set< MooseEnumItem >::const_iterator find (const MooseEnumItem &other) const
Locate an item.
std::set< MooseEnumItem >::const_iterator find (const std::string &name) const
std::set< MooseEnumItem >::const_iterator find (int id) const
Protected Member Functions
virtual void checkDeprecated () const override
Check whether the current value is deprecated when called.
void checkDeprecated (const MooseEnumItem &item) const
Check and warn deprecated values.
void addEnumerationNames (const std::string &names)
Methods to add possible enumeration value to the enum.
const MooseEnumItem & addEnumerationName (const std::string &raw_name)
const MooseEnumItem & addEnumerationName (const std::string &name, const int &value)
const MooseEnumItem & addEnumerationItem (const MooseEnumItem &item)
Protected Attributes
std::set< MooseEnumItem > _items
Storage for the assigned items.
std::map< MooseEnumItem, MooseEnumItem > _deprecated_items
The map of deprecated names and optional replacements.
bool _allow_out_of_range
Flag to enable enumeration items not previously defined.
std::map< MooseEnumItem, std::string > _item_documentation
The map of items and their respective documentation strings.
Private Attributes
MooseEnumItem _current
The current id.
Detailed Description
MooseEnum designed for the ReporterContext objects to define how a ReporterValue can and is being produced.
The available items indicate how it can be produced and the current item is how the value is being produced.
See also
ReporterContext.h
Definition at line 61 of file ReporterMode.h.
Member Enumeration Documentation
CompareMode
enum class MooseEnum::CompareMode strong inherited
Enum item for controlling comparison in the compareCurrent method.
Enumerator
COMPARE_NAME
COMPARE_ID
COMPARE_BOTH
Definition at line 37 of file MooseEnum.h.
  {
    COMPARE_NAME,
    COMPARE_ID,
    COMPARE_BOTH
  };
Constructor & Destructor Documentation
ReporterProducerEnum()
ReporterProducerEnum::ReporterProducerEnum ()
Definition at line 20 of file ReporterMode.C.
: MooseEnum() {}
Member Function Documentation
addDocumentation()
void MooseEnumBase::addDocumentation (const std::string & name, const std::string & doc) inherited
Add an item documentation string.
Definition at line 175 of file MooseEnumBase.C.
{
  auto it = find(name);
  if (it == _items.end())
    mooseError("Item '", name, "' not found in addDocumentation.");
  _item_documentation[*it] = doc;
}
Referenced by PseudoTimestep::validParams(), and ReferenceResidualProblem::validParams().
addEnumerationItem()
const MooseEnumItem & MooseEnumBase::addEnumerationItem (const MooseEnumItem & item) protected inherited
Definition at line 117 of file MooseEnumBase.C.
{
  const auto & item_it = find(item);
  if (item_it != _items.end()) // do nothing for identical insertions
    return *item_it;
  if (find(item.id()) != _items.end())
    mooseError("The supplied id ",
               item.id(),
               " already exists in the enumeration, cannot not add '",
               item,
               "'.");
  if (find(item.name()) != _items.end())
    mooseError("The name '", item.name(), "' already exists in the enumeration.");
  return *_items.insert(item).first;
}
Referenced by ExecFlagEnum::addAvailableFlags(), MooseEnumBase::addEnumerationName(), MultiMooseEnum::assign(), and insert().
addEnumerationName() [1/2]
const MooseEnumItem & MooseEnumBase::addEnumerationName (const std::string & name, const int & value) protected inherited
Definition at line 111 of file MooseEnumBase.C.
{
  return addEnumerationItem(MooseEnumItem(name, value));
}
addEnumerationName() [2/2]
const MooseEnumItem & MooseEnumBase::addEnumerationName (const std::string & raw_name) protected inherited
Definition at line 73 of file MooseEnumBase.C.
{
  // Make sure the option is not malformed
  if (raw_name.find_first_of('=') == 0 || raw_name.find_last_of('=') == raw_name.length() - 1)
    mooseError("You cannot place whitespace around the '=' character in MooseEnumBase");
  // Split on equals sign
  std::vector<std::string> name_value;
  MooseUtils::tokenize(MooseUtils::trim(raw_name), name_value, 1, "=");
  // There should be one or two items in the name_value
  if (name_value.size() < 1 || name_value.size() > 2)
    mooseError("Invalid option supplied in MooseEnumBase: ", raw_name);
  // Remove un-wanted space around string
  name_value[0] = MooseUtils::trim(name_value[0]);
  // See if there is a value supplied for this option
  // strtol allows for proper conversions of both int and hex strings
  int value;
  if (name_value.size() == 2)
    value = std::strtol(name_value[1].c_str(), NULL, 0);
  else
    value = getNextValidID();
  return addEnumerationName(name_value[0], value);
}
Referenced by MooseEnumBase::addEnumerationName(), MooseEnumBase::addEnumerationNames(), and MooseEnumBase::operator+=().
addEnumerationNames()
void MooseEnumBase::addEnumerationNames (const std::string & names) protected inherited
Methods to add possible enumeration value to the enum.
The MooseEnum/MultiMooseEnum are not designed to be modified, with respect to the list of possible values. However, this is not the case for the ExecFlagEnum which is a special type of MultiMooseEnum for managing the "execute_on" flags. These methods are used by ExecFlagEnum to allow users to modify the available execute flags for their object.
Definition at line 64 of file MooseEnumBase.C.
{
  std::vector<std::string> elements;
  MooseUtils::tokenize(names, elements, 1, " ");
  for (const std::string & raw_name : elements)
    addEnumerationName(raw_name);
}
Referenced by MooseEnumBase::MooseEnumBase().
assign() [1/3]
void MooseEnum::assign (const MooseEnumItem & item) inherited
Definition at line 112 of file MooseEnum.C.
{
  std::set<MooseEnumItem>::const_iterator iter = find(item);
  if (iter == _items.end())
    mooseError("Invalid item \"",
               item,
               "\" in MooseEnum. Valid ids are \"",
               Moose::stringify(items()),
               "\".");
  else
    _current = *iter;
  checkDeprecated();
}
assign() [2/3]
void MooseEnum::assign (const std::string & name) inherited
Definition at line 60 of file MooseEnum.C.
{
  if (name == "")
  {
    _current = MooseEnumItem("", MooseEnumItem::INVALID_ID);
    return;
  }
  std::set<MooseEnumItem>::const_iterator iter = find(name);
  if (iter == _items.end())
  {
    if (!_allow_out_of_range) // Are out of range values allowed?
      mooseError("Invalid option \"",
                 name,
                 "\" in MooseEnum.  Valid options (not case-sensitive) are \"",
                 getRawNames(),
                 "\".");
    else
    {
      _current = MooseEnumItem(name, getNextValidID());
      _items.insert(_current);
    }
  }
  else
    _current = *iter;
  checkDeprecated();
}
Referenced by ReporterContextBase::init(), and MooseEnum::operator=().
assign() [3/3]
void MooseEnum::assign (int value) inherited
Definition at line 90 of file MooseEnum.C.
{
  if (value == MooseEnumItem::INVALID_ID)
  {
    _current = MooseEnumItem("", MooseEnumItem::INVALID_ID);
    return;
  }
  std::set<MooseEnumItem>::const_iterator iter = find(value);
  if (iter == _items.end())
    mooseError("Invalid id \"",
               value,
               "\" in MooseEnum. Valid ids are \"",
               Moose::stringify(getIDs()),
               "\".");
  else
    _current = *iter;
  checkDeprecated();
}
checkDeprecated() [1/2]
void MooseEnum::checkDeprecated () const override protected virtual inherited
Check whether the current value is deprecated when called.
Implements MooseEnumBase.
Definition at line 202 of file MooseEnum.C.
{
  MooseEnumBase::checkDeprecated(_current);
}
Referenced by MooseEnum::assign().
checkDeprecated() [2/2]
void MooseEnumBase::checkDeprecated (const MooseEnumItem & item) const protected inherited
Check and warn deprecated values.
Definition at line 136 of file MooseEnumBase.C.
{
  std::map<MooseEnumItem, MooseEnumItem>::const_iterator it = _deprecated_items.find(item);
  if (it != _deprecated_items.end())
  {
    if (it->second.name().empty())
      mooseWarning(item.name() + " is deprecated");
    else
      mooseWarning(item.name() + " is deprecated, consider using " + it->second.name());
  }
}
clear()
void ReporterProducerEnum::clear ()
Clear all available items (i.e., create an empty MooseEnum)
Definition at line 29 of file ReporterMode.C.
{
  _items.clear();
}
Referenced by ReporterBroadcastContext< T >::ReporterBroadcastContext(), ReporterGatherContext< T >::ReporterGatherContext(), and ReporterScatterContext< T >::ReporterScatterContext().
compareCurrent()
bool MooseEnum::compareCurrent (const MooseEnum & other, CompareMode mode = CompareMode::COMPARE_NAME) const inherited
Method for comparing currently set values between MooseEnum.
Definition at line 171 of file MooseEnum.C.
{
  switch (mode)
  {
    case CompareMode::COMPARE_BOTH:
      return (_current.id() == other._current.id()) && (_current.name() == other._current.name());
    case CompareMode::COMPARE_NAME:
      return _current.name() == other._current.name();
    case CompareMode::COMPARE_ID:
      return _current.id() == other._current.id();
  }
  return false;
}
Referenced by AddVariableAction::init().
deprecate()
void MooseEnumBase::deprecate (const std::string & name, const std::string & raw_name = "") virtual inherited
Deprecates various options in the MOOSE enum.
For each deprecated option, you may supply an optional new option that will be used in a message telling the user which new option replaces the old one.
Definition at line 45 of file MooseEnumBase.C.
{
  std::set<MooseEnumItem>::const_iterator deprecated = find(name);
  if (deprecated == _items.end())
    mooseError("Cannot deprecate the enum item ", name, ", is not an available value.");
  std::set<MooseEnumItem>::const_iterator replaced = find(raw_name);
  if (replaced == _items.end())
    mooseError("Cannot deprecate the enum item ",
               name,
               ", since the replaced item ",
               raw_name,
               " it is not an available value.");
  _deprecated_items.emplace(std::make_pair(*deprecated, *replaced));
  checkDeprecated();
}
find() [1/3]
std::set< MooseEnumItem >::const_iterator MooseEnumBase::find (const MooseEnumItem & other) const inherited
Locate an item.
Definition at line 206 of file MooseEnumBase.C.
{
  const auto upper = MooseUtils::toUpper(other.name());
  return std::find_if(_items.begin(),
                      _items.end(),
                      [&other, &upper](MooseEnumItem const & item)
                      { return item.id() == other.id() && item.name() == upper; });
}
Referenced by MooseEnumBase::addDocumentation(), MooseEnumBase::addEnumerationItem(), ExecFlagEnum::appendCurrent(), MooseEnum::assign(), MultiMooseEnum::assign(), MooseEnumBase::deprecate(), MooseEnum::operator==(), moose::internal::ExecFlagRegistry::registerFlag(), ExecFlagEnum::removeAvailableFlags(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
find() [2/3]
std::set< MooseEnumItem >::const_iterator MooseEnumBase::find (const std::string & name) const inherited
Definition at line 190 of file MooseEnumBase.C.
{
  std::string upper = MooseUtils::toUpper(name);
  return std::find_if(_items.begin(),
                      _items.end(),
                      [&upper](MooseEnumItem const & item) { return item.name() == upper; });
}
find() [3/3]
std::set< MooseEnumItem >::const_iterator MooseEnumBase::find (int id) const inherited
Definition at line 199 of file MooseEnumBase.C.
{
  return std::find_if(
      _items.begin(), _items.end(), [&id](MooseEnumItem const & item) { return item.id() == id; });
}
getEnum()
template<typename T > T MooseEnum::getEnum inherited
get the current value cast to the enum type T
Definition at line 149 of file MooseEnum.h.
{
#ifdef LIBMESH_HAVE_CXX11_TYPE_TRAITS
  static_assert(std::is_enum<T>::value == true,
                "The type requested from MooseEnum::getEnum must be an enum type!\n\n");
#endif
  return static_cast<T>(_current.id());
}
Referenced by PiecewiseTabularBase::buildFromFile().
getIDs()
std::vector< int > MooseEnumBase::getIDs () const inherited
Method for returning a vector of ids for this instance.
Returns
a vector of ints containing the possible ids for this enumeration
Definition at line 165 of file MooseEnumBase.C.
{
  std::vector<int> out;
  out.reserve(_items.size());
  for (const auto & item : _items)
    out.push_back(item.id());
  return out;
}
Referenced by MooseEnum::assign().
getItemDocumentation()
const std::map< MooseEnumItem, std::string > & MooseEnumBase::getItemDocumentation () const inherited
Get the map containing each item's documentation string.
Definition at line 184 of file MooseEnumBase.C.
{
  return _item_documentation;
}
getNames()
std::vector< std::string > MooseEnumBase::getNames () const inherited
Method for returning a vector of all valid enumeration names for this instance.
Returns
a vector of names
Definition at line 149 of file MooseEnumBase.C.
{
  std::vector<std::string> out;
  out.reserve(_items.size());
  for (const auto & item : _items)
    out.push_back(item.name());
  return out;
}
Referenced by ExecFlagEnum::getDocString().
getNextValidID()
int MooseEnumBase::getNextValidID () const inherited
Compute the next valid ID.
Definition at line 102 of file MooseEnumBase.C.
{
  int value = -1; // Use -1 so if no values exist the first will be zero
  for (const auto & item : _items)
    value = std::max(value, item.id());
  return ++value;
}
Referenced by MooseEnumBase::addEnumerationName(), MooseEnum::assign(), MultiMooseEnum::assign(), and moose::internal::ExecFlagRegistry::registerFlag().
getRawNames()
std::string MooseEnumBase::getRawNames () const inherited
Method for returning the raw name strings for this instance.
Returns
a space separated list of names
Definition at line 159 of file MooseEnumBase.C.
{
  return Moose::stringify(_items, " ");
}
Referenced by MooseEnum::assign(), MultiMooseEnum::assign(), AdvancedOutput::enableOutputTypes(), MooseEnum::operator==(), PiecewiseConstant::validParams(), and ComparisonPostprocessor::validParams().
insert() [1/2]
void ReporterProducerEnum::insert (const ReporterMode & mode)
Definition at line 23 of file ReporterMode.C.
{
  addEnumerationItem(mode);
}
insert() [2/2]
template<typename... Args> void ReporterProducerEnum::insert (const ReporterMode & mode, Args... modes)
Add possible items to the enumeration.
Definition at line 79 of file ReporterMode.h.
{
  insert(mode);
  insert(modes...);
}
Referenced by insert(), ReporterBroadcastContext< T >::ReporterBroadcastContext(), ReporterContext< T >::ReporterContext(), ReporterGatherContext< T >::ReporterGatherContext(), and ReporterScatterContext< T >::ReporterScatterContext().
isOutOfRangeAllowed()
bool MooseEnumBase::isOutOfRangeAllowed () const inline inherited
isOutOfRangeAllowed
Returns
- a Boolean indicating whether enum names out of range are allowed
Definition at line 88 of file MooseEnumBase.h.
{ return _allow_out_of_range; }
isValid()
virtual bool MooseEnum::isValid () const inline override virtual inherited
IsValid.
Returns
- a Boolean indicating whether this Enumeration has been set
Implements MooseEnumBase.
Definition at line 116 of file MooseEnum.h.
{ return _current.id() > MooseEnumItem::INVALID_ID; }
Referenced by MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer().
items()
const std::set< MooseEnumItem > & MooseEnumBase::items () const inline inherited
Return the complete set of available flags.
Definition at line 93 of file MooseEnumBase.h.
{ return _items; }
Referenced by MooseEnum::assign(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
operator int()
MooseEnum::operator int () const inline inherited
Cast operators to make this object behave as value_types and std::string these methods can be used so that this class behaves more like a normal value_type enumeration.
Definition at line 72 of file MooseEnum.h.
{ return _current.id(); }
operator std::string()
MooseEnum::operator std::string () const inline inherited
Definition at line 73 of file MooseEnum.h.
{ return _current.rawName(); }
operator!=() [1/4]
bool MooseEnum::operator!= (const char * value) const inherited
Definition at line 141 of file MooseEnum.C.
{
  return !(*this == name);
}
operator!=() [2/4]
bool MooseEnum::operator!= (const MooseEnum & value) const inherited
Definition at line 194 of file MooseEnum.C.
{
  mooseDeprecated("This method will be removed because the meaning is not well defined, please use "
                  "the 'compareCurrent' method instead.");
  return value._current.name() != _current.name();
}
operator!=() [3/4]
bool MooseEnum::operator!= (int value) const inherited
Definition at line 153 of file MooseEnum.C.
{
  return value != _current;
}
operator!=() [4/4]
bool MooseEnum::operator!= (unsigned short value) const inherited
Definition at line 165 of file MooseEnum.C.
{
  return value != _current;
}
operator+=() [1/2]
MooseEnumBase & MooseEnumBase::operator+= (const std::initializer_list< std::string > & names) inherited
Adds enumeration items from a list of names.
Definition at line 224 of file MooseEnumBase.C.
{
  for (const auto & name : names)
    *this += name;
  return *this;
}
operator+=() [2/2]
MooseEnumBase & MooseEnumBase::operator+= (const std::string & name) inherited
Adds an enumeration item from name.
Definition at line 216 of file MooseEnumBase.C.
{
  addEnumerationName(name);
  checkDeprecated();
  return *this;
}
operator==() [1/4]
bool MooseEnum::operator== (const char * value) const inherited
Comparison operators for comparing with character constants, MooseEnums or integer values.
Parameters
value - RHS value to compare against
Returns
bool - the truth value for the comparison
Definition at line 128 of file MooseEnum.C.
{
  std::string upper(MooseUtils::toUpper(name));
  mooseAssert(_allow_out_of_range || find(upper) != _items.end(),
              "Invalid string comparison \"" + upper +
                  "\" in MooseEnum.  Valid options (not case-sensitive) are \"" + getRawNames() +
                  "\".");
  return _current == upper;
}
operator==() [2/4]
bool MooseEnum::operator== (const MooseEnum & value) const inherited
Definition at line 186 of file MooseEnum.C.
{
  mooseDeprecated("This method will be removed because the meaning is not well defined, please use "
                  "the 'compareCurrent' method instead.");
  return value._current.name() == _current.name();
}
operator==() [3/4]
bool MooseEnum::operator== (int value) const inherited
Definition at line 147 of file MooseEnum.C.
{
  return value == _current;
}
operator==() [4/4]
bool MooseEnum::operator== (unsigned short value) const inherited
Definition at line 159 of file MooseEnum.C.
{
  return value == _current;
}
Member Data Documentation
_allow_out_of_range
bool MooseEnumBase::_allow_out_of_range protected inherited
Flag to enable enumeration items not previously defined.
Definition at line 163 of file MooseEnumBase.h.
Referenced by MooseEnum::assign(), MultiMooseEnum::assign(), MooseEnumBase::isOutOfRangeAllowed(), and MooseEnum::operator==().
_current
MooseEnumItem MooseEnum::_current private inherited
The current id.
Definition at line 144 of file MooseEnum.h.
Referenced by MooseEnum::assign(), MooseEnum::checkDeprecated(), MooseEnum::compareCurrent(), MooseEnum::getEnum(), MooseEnum::isValid(), MooseEnum::operator int(), MooseEnum::operator std::string(), MooseEnum::operator!=(), and MooseEnum::operator==().
_deprecated_items
std::map<MooseEnumItem, MooseEnumItem> MooseEnumBase::_deprecated_items protected inherited
The map of deprecated names and optional replacements.
Definition at line 160 of file MooseEnumBase.h.
Referenced by MooseEnumBase::checkDeprecated(), and MooseEnumBase::deprecate().
_item_documentation
std::map<MooseEnumItem, std::string> MooseEnumBase::_item_documentation protected inherited
The map of items and their respective documentation strings.
Definition at line 166 of file MooseEnumBase.h.
Referenced by MooseEnumBase::addDocumentation(), and MooseEnumBase::getItemDocumentation().
_items
std::set<MooseEnumItem> MooseEnumBase::_items protected inherited
Storage for the assigned items.
Definition at line 157 of file MooseEnumBase.h.
Referenced by MooseEnumBase::addDocumentation(), MooseEnumBase::addEnumerationItem(), ExecFlagEnum::appendCurrent(), MooseEnum::assign(), MultiMooseEnum::assign(), clear(), MooseEnumBase::deprecate(), MooseEnumBase::find(), MooseEnumBase::getIDs(), MooseEnumBase::getNames(), MooseEnumBase::getNextValidID(), MooseEnumBase::getRawNames(), ExecFlagEnum::items(), MooseEnumBase::items(), MooseEnum::operator==(), and ExecFlagEnum::removeAvailableFlags().
The documentation for this class was generated from the following files:
moose/framework/include/reporters/ReporterMode.h
moose/framework/src/reporters/ReporterMode.C