Zapdos: MultiIndex< T >::const_noconst_iterator< is_const > Class Template Reference
MultiIndex< T >::const_noconst_iterator< is_const > Class Template Reference
MultiIndex container iterator.
#include <MultiIndex.h>
Public Types
typedef std::conditional< is_const, constMultiIndex< T > &, MultiIndex< T > & >::type reference_type
Public Member Functions
const_noconst_iterator (reference_type multi_index, unsigned int position)
unsigned int flatIndex () const
reference_type getMultiIndexObject () const
const_noconst_iterator & operator= (const const_noconst_iterator &other)
const_noconst_iterator (const const_noconst_iterator &)=default
const_noconst_iterator & operator++ ()
const_noconst_iterator & operator++ (int)
const_noconst_iterator & operator-- ()
const_noconst_iterator & operator-- (int)
bool operator== (const const_noconst_iterator &other) const
to be equal both iterators must hold a reference to the same MultiIndexObject and be at the same _flat_index
bool operator!= (const const_noconst_iterator &other) const
std::pair< const size_type &, T & > operator* ()
dereferencing operator
std::pair< const size_type &, const T & > operator* () const
Protected Attributes
reference_type _multi_index
unsigned int _flat_index
size_type _shape
size_type _indices
Detailed Description
template<class T>
template<bool is_const>
class MultiIndex< T >::const_noconst_iterator< is_const >
MultiIndex container iterator.
Nested iterator class for MultiIndex containers.
Definition at line 128 of file MultiIndex.h.
Member Typedef Documentation
reference_type
template<class T > template<bool is_const> typedef std::conditional<is_const,constMultiIndex<T>&,MultiIndex<T>&>::type MultiIndex< T >::const_noconst_iterator< is_const >::reference_type
Definition at line 132 of file MultiIndex.h.
Constructor & Destructor Documentation
const_noconst_iterator() [1/2]
template<class T > template<bool is_const> MultiIndex< T >::const_noconst_iterator< is_const >::const_noconst_iterator (reference_type multi_index, unsigned int position) inline
Definition at line 134 of file MultiIndex.h.
    : _multi_index(multi_index), _flat_index(position), _shape(multi_index.size())
  {
    _multi_index.findIndexVector(position, _indices);
  }
const_noconst_iterator() [2/2]
template<class T > template<bool is_const> MultiIndex< T >::const_noconst_iterator< is_const >::const_noconst_iterator (const const_noconst_iterator< is_const > &) default
Member Function Documentation
flatIndex()
template<class T > template<bool is_const> unsigned int MultiIndex< T >::const_noconst_iterator< is_const >::flatIndex () const inline
Definition at line 141 of file MultiIndex.h.
{ return _flat_index; }
Referenced by MultiIndex< T >::const_noconst_iterator< is_const >::operator=(), and MultiIndex< T >::const_noconst_iterator< is_const >::operator==().
getMultiIndexObject()
template<class T > template<bool is_const> reference_type MultiIndex< T >::const_noconst_iterator< is_const >::getMultiIndexObject () const inline
Definition at line 142 of file MultiIndex.h.
{ return _multi_index; }
Referenced by MultiIndex< T >::const_noconst_iterator< is_const >::operator=(), and MultiIndex< T >::const_noconst_iterator< is_const >::operator==().
operator!=()
template<class T > template<bool is_const> bool MultiIndex< T >::const_noconst_iterator< is_const >::operator!= (const const_noconst_iterator< is_const > & other) const inline
Definition at line 229 of file MultiIndex.h.
{ return !(*this == other); }
operator*() [1/2]
template<class T > template<bool is_const> std::pair< const size_type &, T & > MultiIndex< T >::const_noconst_iterator< is_const >::operator* () inline
dereferencing operator
Definition at line 232 of file MultiIndex.h.
  {
    return std::pair<const size_type &, T &>(_indices, _multi_index._data[_flat_index]);
  }
operator*() [2/2]
template<class T > template<bool is_const> std::pair< const size_type &, const T & > MultiIndex< T >::const_noconst_iterator< is_const >::operator* () const inline
Definition at line 236 of file MultiIndex.h.
  {
    return std::pair<const size_type &, const T &>(_indices, _multi_index._data[_flat_index]);
  }
operator++() [1/2]
template<class T > template<bool is_const> const_noconst_iterator & MultiIndex< T >::const_noconst_iterator< is_const >::operator++ () inline
Definition at line 157 of file MultiIndex.h.
  {
    ++_flat_index;
    // increment indices
    for (unsigned int j = 0; j < _indices.size(); ++j)
    {
      _indices[_indices.size() - j - 1] =
          (_indices[_indices.size() - j - 1] + 1) % _shape[_indices.size() - j - 1];
      if (_indices[_indices.size() - j - 1] != 0)
        break;
    }
    return *this;
  }
operator++() [2/2]
template<class T > template<bool is_const> const_noconst_iterator & MultiIndex< T >::const_noconst_iterator< is_const >::operator++ (int) inline
Definition at line 172 of file MultiIndex.h.
  {
    const_noconst_iterator clone(*this);
    ++_flat_index;
    // increment indices
    for (unsigned int j = 0; j < _indices.size(); ++j)
    {
      _indices[_indices.size() - j - 1] =
          (_indices[_indices.size() - j - 1] + 1) % _shape[_indices.size() - j - 1];
      if (_indices[_indices.size() - j - 1] != 0)
        break;
    }
    return clone;
  }
operator--() [1/2]
template<class T > template<bool is_const> const_noconst_iterator & MultiIndex< T >::const_noconst_iterator< is_const >::operator-- () inline
Definition at line 188 of file MultiIndex.h.
  {
    --_flat_index;
    // decrement indices
    for (unsigned int j = 0; j < _indices.size(); ++j)
    {
      if (_indices[_indices.size() - j - 1] == 0)
        _indices[_indices.size() - j - 1] = _shape[_indices.size() - j - 1] - 1;
      else
      {
        --_indices[_indices.size() - j - 1];
        break;
      }
    }
    return *this;
  }
operator--() [2/2]
template<class T > template<bool is_const> const_noconst_iterator & MultiIndex< T >::const_noconst_iterator< is_const >::operator-- (int) inline
Definition at line 206 of file MultiIndex.h.
  {
    const_noconst_iterator clone(*this);
    --_flat_index;
    // decrement indices
    for (unsigned int j = 0; j < _indices.size(); ++j)
    {
      if (_indices[_indices.size() - j - 1] == 0)
        _indices[_indices.size() - j - 1] = _shape[_indices.size() - j - 1] - 1;
      else
      {
        --_indices[_indices.size() - j - 1];
        break;
      }
    }
    return clone;
  }
operator=()
template<class T > template<bool is_const> const_noconst_iterator & MultiIndex< T >::const_noconst_iterator< is_const >::operator= (const const_noconst_iterator< is_const > & other) inline
Definition at line 145 of file MultiIndex.h.
  {
    _multi_index = other.getMultiIndexObject();
    _flat_index = other.flatIndex();
    _multi_index.findIndexVector(_flat_index, _indices);
    return *this;
  }
operator==()
template<class T > template<bool is_const> bool MultiIndex< T >::const_noconst_iterator< is_const >::operator== (const const_noconst_iterator< is_const > & other) const inline
to be equal both iterators must hold a reference to the same MultiIndexObject and be at the same _flat_index
Definition at line 225 of file MultiIndex.h.
  {
    return _flat_index == other.flatIndex() && &_multi_index == &other.getMultiIndexObject();
  }
Member Data Documentation
_flat_index
template<class T > template<bool is_const> unsigned int MultiIndex< T >::const_noconst_iterator< is_const >::_flat_index protected
Definition at line 243 of file MultiIndex.h.
_indices
template<class T > template<bool is_const> size_type MultiIndex< T >::const_noconst_iterator< is_const >::_indices protected
Definition at line 245 of file MultiIndex.h.
_multi_index
template<class T > template<bool is_const> reference_type MultiIndex< T >::const_noconst_iterator< is_const >::_multi_index protected
Definition at line 242 of file MultiIndex.h.
_shape
template<class T > template<bool is_const> size_type MultiIndex< T >::const_noconst_iterator< is_const >::_shape protected
Definition at line 244 of file MultiIndex.h.
The documentation for this class was generated from the following file:
moose/framework/include/utils/MultiIndex.h