Zapdos: Moose::FV::Limiter< T > Class Template Reference
Moose::FV::Limiter< T > Class Template Reference abstract
Base class for defining slope limiters for finite volume or potentially reconstructed Discontinuous-Galerkin applications.
#include <Limiter.h>
Public Member Functions
virtual T limit (const T &phi_upwind, const T &phi_downwind, const VectorValue< T > *grad_phi_upwind, const RealVectorValue &dCD) const =0
Defines the slope limiter function $\beta(r_f)$ where $r_f$ represents the ratio of upstream to downstream gradients.
virtual bool constant () const =0
virtual InterpMethod interpMethod () const =0
T operator() (const T &phi_upwind, const T &phi_downwind, const VectorValue< T > *grad_phi_upwind, const RealVectorValue &dCD) const
Limiter ()=default
virtual ~Limiter ()=default
Static Public Member Functions
static std::unique_ptr< Limiter > build (LimiterType limiter)
Detailed Description
template<typename T>
class Moose::FV::Limiter< T >
Base class for defining slope limiters for finite volume or potentially reconstructed Discontinuous-Galerkin applications.
Definition at line 60 of file Limiter.h.
Constructor & Destructor Documentation
Limiter()
template<typename T > Moose::FV::Limiter< T >::Limiter () default
~Limiter()
template<typename T > virtual Moose::FV::Limiter< T >::~Limiter () virtual default
Member Function Documentation
build()
template<typename T > template std::unique_ptr< Limiter< ADReal > > Moose::FV::Limiter< T >::build (LimiterType limiter) static
Definition at line 31 of file Limiter.C.
{
  switch (limiter)
  {
    case LimiterType::VanLeer:
      return std::make_unique<VanLeerLimiter<T>>();
    case LimiterType::Upwind:
      return std::make_unique<UpwindLimiter<T>>();
    case LimiterType::CentralDifference:
      return std::make_unique<CentralDifferenceLimiter<T>>();
    case LimiterType::MinMod:
      return std::make_unique<MinModLimiter<T>>();
    case LimiterType::SOU:
      return std::make_unique<SOULimiter<T>>();
    case LimiterType::QUICK:
      return std::make_unique<QUICKLimiter<T>>();
    default:
      mooseError("Unrecognized limiter type ", unsigned(limiter));
  }
}
Referenced by Moose::FV::containerInterpolate().
constant()
template<typename T > virtual bool Moose::FV::Limiter< T >::constant () const pure virtual
Implemented in Moose::FV::CentralDifferenceLimiter< T >, Moose::FV::MinModLimiter< T >, Moose::FV::QUICKLimiter< T >, Moose::FV::SOULimiter< T >, Moose::FV::UpwindLimiter< T >, and Moose::FV::VanLeerLimiter< T >.
Referenced by Moose::FV::interpolate().
interpMethod()
template<typename T > virtual InterpMethod Moose::FV::Limiter< T >::interpMethod () const pure virtual
Implemented in Moose::FV::CentralDifferenceLimiter< T >, Moose::FV::MinModLimiter< T >, Moose::FV::QUICKLimiter< T >, Moose::FV::SOULimiter< T >, Moose::FV::UpwindLimiter< T >, and Moose::FV::VanLeerLimiter< T >.
limit()
template<typename T > virtual T Moose::FV::Limiter< T >::limit (const T & phi_upwind, const T & phi_downwind, const VectorValue< T > * grad_phi_upwind, const RealVectorValue & dCD) const pure virtual
Defines the slope limiter function $\beta(r_f)$ where $r_f$ represents the ratio of upstream to downstream gradients.
Implemented in Moose::FV::CentralDifferenceLimiter< T >, Moose::FV::UpwindLimiter< T >, Moose::FV::MinModLimiter< T >, Moose::FV::QUICKLimiter< T >, Moose::FV::SOULimiter< T >, and Moose::FV::VanLeerLimiter< T >.
Referenced by Moose::FV::Limiter< T >::operator()().
operator()()
template<typename T > T Moose::FV::Limiter< T >::operator() (const T & phi_upwind, const T & phi_downwind, const VectorValue< T > * grad_phi_upwind, const RealVectorValue & dCD) const inline
Definition at line 73 of file Limiter.h.
  {
    return std::max(T(0), std::min(T(2), limit(phi_upwind, phi_downwind, grad_phi_upwind, dCD)));
  }
The documentation for this class was generated from the following files:
moose/framework/include/limiters/Limiter.h
moose/framework/src/limiters/Limiter.C