Zapdos: PiecewiseByBlockLambdaFunctor< T > Class Template Reference
PiecewiseByBlockLambdaFunctor< T > Class Template Reference
A material property that is evaluated on-the-fly via calls to various overloads of operator()
#include <PiecewiseByBlockLambdaFunctor.h>
Public Types
using FunctorType = FunctorBase< T >
using FunctorReturnType = T
using ValueType = T
using GradientType = typename MetaPhysicL::ReplaceAlgebraicType< T, typename TensorTools::IncrementRank< typename MetaPhysicL::ValueType< T >::type >::type >::type
This rigmarole makes it so that a user can create functors that return containers (std::vector, std::array).
using DotType = ValueType
Public Member Functions
template<typename PolymorphicLambda >
PiecewiseByBlockLambdaFunctor (const std::string &name, PolymorphicLambda my_lammy, const std::set< ExecFlagType > &clearance_schedule, const MooseMesh &mesh, const std::set< SubdomainID > &block_ids)
template<typename PolymorphicLambda >
void setFunctor (const MooseMesh &mesh, const std::set< SubdomainID > &block_ids, PolymorphicLambda my_lammy)
Set the functor that will be used in calls to evaluate overloads.
virtual ~PiecewiseByBlockLambdaFunctor ()=default
bool isExtrapolatedBoundaryFace (const FaceInfo &fi, const Elem *elem, const Moose::StateArg &time) const override
Returns whether this (sided) face is an extrapolated boundary face for this functor.
bool hasBlocks (SubdomainID id) const override
Returns whether the functor is defined on this block.
template<typename PolymorphicLambda >
void setFunctor (const MooseMesh &libmesh_dbg_var(mesh), const std::set< SubdomainID > &block_ids, PolymorphicLambda my_lammy)
const MooseFunctorName & functorName () const
Return the functor name.
virtual void residualSetup () override
virtual void jacobianSetup () override
virtual void timestepSetup () override
virtual void customSetup (const ExecFlagType &exec_type) override
void setCacheClearanceSchedule (const std::set< ExecFlagType > &clearance_schedule)
Set how often to clear the functor evaluation cache.
bool isInternalFace (const FaceInfo &) const
Returns true if the face is an internal face.
virtual bool isConstant () const
Returns true if this functor is a constant.
virtual bool hasFaceSide (const FaceInfo &fi, const bool fi_elem_side) const override
Moose::FaceArg checkFace (const Moose::FaceArg &face) const
Examines the incoming face argument.
ValueType operator() (const ElemArg &elem, const StateArg &state) const
Same as their evaluate overloads with the same arguments but allows for caching implementation.
ValueType operator() (const FaceArg &face, const StateArg &state) const
ValueType operator() (const ElemQpArg &qp, const StateArg &state) const
ValueType operator() (const ElemSideQpArg &qp, const StateArg &state) const
ValueType operator() (const ElemPointArg &elem_point, const StateArg &state) const
ValueType operator() (const NodeArg &node, const StateArg &state) const
GradientType gradient (const ElemArg &elem, const StateArg &state) const
Same as their evaluateGradient overloads with the same arguments but allows for caching implementation.
GradientType gradient (const FaceArg &face, const StateArg &state) const
GradientType gradient (const ElemQpArg &qp, const StateArg &state) const
GradientType gradient (const ElemSideQpArg &qp, const StateArg &state) const
GradientType gradient (const ElemPointArg &elem_point, const StateArg &state) const
GradientType gradient (const NodeArg &node, const StateArg &state) const
DotType dot (const ElemArg &elem, const StateArg &state) const
Same as their evaluateDot overloads with the same arguments but allows for caching implementation.
DotType dot (const FaceArg &face, const StateArg &state) const
DotType dot (const ElemQpArg &qp, const StateArg &state) const
DotType dot (const ElemSideQpArg &qp, const StateArg &state) const
DotType dot (const ElemPointArg &elem_point, const StateArg &state) const
DotType dot (const NodeArg &node, const StateArg &state) const
GradientType gradDot (const ElemArg &elem, const StateArg &state) const
Same as their evaluateGradDot overloads with the same arguments but allows for caching implementation.
GradientType gradDot (const FaceArg &face, const StateArg &state) const
GradientType gradDot (const ElemQpArg &qp, const StateArg &state) const
GradientType gradDot (const ElemSideQpArg &qp, const StateArg &state) const
GradientType gradDot (const ElemPointArg &elem_point, const StateArg &state) const
GradientType gradDot (const NodeArg &node, const StateArg &state) const
Protected Types
using ElemFn = std::function< T(const Moose::ElemArg &, const Moose::StateArg &)>
using FaceFn = std::function< T(const Moose::FaceArg &, const Moose::StateArg &)>
using ElemQpFn = std::function< T(const Moose::ElemQpArg &, const Moose::StateArg &)>
using ElemSideQpFn = std::function< T(const Moose::ElemSideQpArg &, const Moose::StateArg &)>
using ElemPointFn = std::function< T(const Moose::ElemPointArg &, const Moose::StateArg &)>
using NodeFn = std::function< T(const Moose::NodeArg &, const Moose::StateArg &)>
Protected Member Functions
ValueType evaluate (const Moose::ElemArg &elem_arg, const Moose::StateArg &time) const override
Evaluate the functor with a given element.
ValueType evaluate (const Moose::FaceArg &face, const Moose::StateArg &time) const override
ValueType evaluate (const Moose::ElemQpArg &elem_qp, const Moose::StateArg &time) const override
ValueType evaluate (const Moose::ElemSideQpArg &elem_side_qp, const Moose::StateArg &time) const override
ValueType evaluate (const Moose::ElemPointArg &elem_point, const Moose::StateArg &time) const override
Evaluate the functor with a given element and point.
ValueType evaluate (const Moose::NodeArg &node_arg, const Moose::StateArg &time) const override
GradientType evaluateGradient (const Moose::ElemArg &elem_arg, const Moose::StateArg &) const override
Evaluate the functor gradient with a given element.
GradientType evaluateGradient (const Moose::FaceArg &face_arg, const Moose::StateArg &) const override
Functor evaluation routines
These methods are all for evaluating functors with different kinds of spatial arguments.
Each of these methods also takes a state argument. For a description of the state argument, please see the StateArg doxygen
virtual GradientType evaluateGradient (const ElemQpArg &, const StateArg &) const
virtual GradientType evaluateGradient (const ElemSideQpArg &, const StateArg &) const
virtual GradientType evaluateGradient (const ElemPointArg &, const StateArg &) const
Evaluate the functor gradient with a given element and point.
virtual GradientType evaluateGradient (const NodeArg &, const StateArg &) const
virtual DotType evaluateDot (const ElemArg &, const StateArg &) const
Evaluate the functor time derivative with a given element.
virtual DotType evaluateDot (const FaceArg &, const StateArg &) const
virtual DotType evaluateDot (const ElemQpArg &, const StateArg &) const
virtual DotType evaluateDot (const ElemSideQpArg &, const StateArg &) const
virtual DotType evaluateDot (const ElemPointArg &, const StateArg &) const
Evaluate the functor time derivative with a given element and point.
virtual DotType evaluateDot (const NodeArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemArg &, const StateArg &) const
Evaluate the functor gradient-dot with a given element.
virtual GradientType evaluateGradDot (const FaceArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemQpArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemSideQpArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemPointArg &, const StateArg &) const
Evaluate the functor gradient-dot with a given element and point.
virtual GradientType evaluateGradDot (const NodeArg &, const StateArg &) const
Private Member Functions
void subdomainErrorMessage (SubdomainID sub_id) const
Provide a useful error message about lack of functor material property on the provided subdomain sub_id.
void clearCacheData ()
clear cache data
template<typename SpaceArg , typename StateArg >
ValueType queryQpCache (unsigned int qp, const QBase &qrule, std::vector< std::pair< bool, T > > &qp_cache_data, const SpaceArg &space, const StateArg &state) const
check a qp cache and if invalid then evaluate
template<typename SpaceArg >
ValueType queryFVArgCache (std::map< SpaceArg, ValueType > &cache_data, const SpaceArg &space) const
check a finite volume spatial argument cache and if invalid then evaluate
Private Attributes
std::unordered_map< SubdomainID, ElemFn > _elem_functor
Functors that return element average values (or cell centroid values or whatever the implementer wants to return for a given element argument)
std::unordered_map< SubdomainID, FaceFn > _face_functor
Functors that return the property value on the requested side of the face (e.g.
std::unordered_map< SubdomainID, ElemQpFn > _elem_qp_functor
Functors that will evaluate elements at quadrature points.
std::unordered_map< SubdomainID, ElemSideQpFn > _elem_side_qp_functor
Functors that will evaluate elements at side quadrature points.
std::unordered_map< SubdomainID, ElemPointFn > _elem_point_functor
Functors that return evaluations at an arbitrary physical point in an element.
std::unordered_map< SubdomainID, NodeFn > _node_functor
Functors that return nodal values.
const MooseMesh & _mesh
The mesh that this functor operates on.
std::set< ExecFlagType > _clearance_schedule
How often to clear the material property cache.
dof_id_type _current_qp_map_key = DofObject::invalid_id
Current key for qp map cache.
std::vector< std::pair< bool, ValueType > > * _current_qp_map_value = nullptr
Current value for qp map cache.
std::unordered_map< dof_id_type, std::vector< std::pair< bool, ValueType > > > _qp_to_value
Cached element quadrature point functor property evaluations.
dof_id_type _current_side_qp_map_key = DofObject::invalid_id
Current key for side-qp map cache.
std::vector< std::vector< std::pair< bool, ValueType > > > * _current_side_qp_map_value
Current value for side-qp map cache.
std::unordered_map< dof_id_type, std::vector< std::vector< std::pair< bool, ValueType > > > > _side_qp_to_value
Cached element quadrature point functor property evaluations.
std::map< ElemArg, ValueType > _elem_arg_to_value
Map from element arguments to their cached evaluations.
std::map< FaceArg, ValueType > _face_arg_to_value
Map from face arguments to their cached evaluations.
std::map< NodeArg, ValueType > _node_arg_to_value
Map from nodal arguments to their cached evaluations.
MooseFunctorName _functor_name
name of the functor
Detailed Description
template<typename T>
class PiecewiseByBlockLambdaFunctor< T >
A material property that is evaluated on-the-fly via calls to various overloads of operator()
Definition at line 32 of file PiecewiseByBlockLambdaFunctor.h.
Member Typedef Documentation
DotType
template<typename T > using Moose::FunctorBase< T >::DotType = ValueType inherited
Definition at line 67 of file MooseFunctor.h.
ElemFn
template<typename T > using PiecewiseByBlockLambdaFunctor< T >::ElemFn = std::function<T(const Moose::ElemArg &, const Moose::StateArg &)> protected
Definition at line 68 of file PiecewiseByBlockLambdaFunctor.h.
ElemPointFn
template<typename T > using PiecewiseByBlockLambdaFunctor< T >::ElemPointFn = std::function<T(const Moose::ElemPointArg &, const Moose::StateArg &)> protected
Definition at line 72 of file PiecewiseByBlockLambdaFunctor.h.
ElemQpFn
template<typename T > using PiecewiseByBlockLambdaFunctor< T >::ElemQpFn = std::function<T(const Moose::ElemQpArg &, const Moose::StateArg &)> protected
Definition at line 70 of file PiecewiseByBlockLambdaFunctor.h.
ElemSideQpFn
template<typename T > using PiecewiseByBlockLambdaFunctor< T >::ElemSideQpFn = std::function<T(const Moose::ElemSideQpArg &, const Moose::StateArg &)> protected
Definition at line 71 of file PiecewiseByBlockLambdaFunctor.h.
FaceFn
template<typename T > using PiecewiseByBlockLambdaFunctor< T >::FaceFn = std::function<T(const Moose::FaceArg &, const Moose::StateArg &)> protected
Definition at line 69 of file PiecewiseByBlockLambdaFunctor.h.
FunctorReturnType
template<typename T > using Moose::FunctorBase< T >::FunctorReturnType = T inherited
Definition at line 55 of file MooseFunctor.h.
FunctorType
template<typename T > using Moose::FunctorBase< T >::FunctorType = FunctorBase<T> inherited
Definition at line 54 of file MooseFunctor.h.
GradientType
template<typename T > using Moose::FunctorBase< T >::GradientType = typename MetaPhysicL::ReplaceAlgebraicType< T, typename TensorTools::IncrementRank<typename MetaPhysicL::ValueType<T>::type>::type>::type inherited
This rigmarole makes it so that a user can create functors that return containers (std::vector, std::array).
This logic will make it such that if a user requests a functor type T that is a container of algebraic types, for example Reals, then the GradientType will be a container of the gradients of those algebraic types, in this example VectorValue<Reals>. So if T is std::vector<Real>, then GradientType will be std::vector<VectorValue<Real>>. As another example: T = std::array<VectorValue<Real>, 1> -> GradientType = std::array<TensorValue<Real>, 1>
Definition at line 64 of file MooseFunctor.h.
NodeFn
template<typename T > using PiecewiseByBlockLambdaFunctor< T >::NodeFn = std::function<T(const Moose::NodeArg &, const Moose::StateArg &)> protected
Definition at line 73 of file PiecewiseByBlockLambdaFunctor.h.
ValueType
template<typename T > using Moose::FunctorBase< T >::ValueType = T inherited
Definition at line 56 of file MooseFunctor.h.
Constructor & Destructor Documentation
PiecewiseByBlockLambdaFunctor()
template<typename T > template<typename PolymorphicLambda > PiecewiseByBlockLambdaFunctor< T >::PiecewiseByBlockLambdaFunctor (const std::string & name, PolymorphicLambda my_lammy, const std::set< ExecFlagType > & clearance_schedule, const MooseMesh & mesh, const std::set< SubdomainID > & block_ids)
Definition at line 123 of file PiecewiseByBlockLambdaFunctor.h.
  : Moose::FunctorBase<T>(name, clearance_schedule), _mesh(mesh)
{
  setFunctor(mesh, block_ids, my_lammy);
}
~PiecewiseByBlockLambdaFunctor()
template<typename T > virtual PiecewiseByBlockLambdaFunctor< T >::~PiecewiseByBlockLambdaFunctor () virtual default
Member Function Documentation
checkFace()
template<typename T > FaceArg Moose::FunctorBase< T >::checkFace (const Moose::FaceArg & face) const inherited
Examines the incoming face argument.
If the face argument producer (residual object, postprocessor, etc.) did not indicate a sidedness to the face, e.g. if the face_side member of the FaceArg is nullptr, then we may "modify" the sidedness of the argument if we are only defined on one side of the face. If the face argument producer \emph has indicated a sidedness and we are not defined on that side, then we will error
Parameters
face The face argument created by the face argument producer, likely a residual object
Returns
A face with possibly changed sidedness depending on whether we aren't defined on both sides of the face
Definition at line 622 of file MooseFunctor.h.
{
  const Elem * const elem = face.face_side;
  const FaceInfo * const fi = face.fi;
  mooseAssert(fi, "face info should be non-null");
  auto ret_face = face;
  bool check_elem_def = false;
  bool check_neighbor_def = false;
  if (!elem)
  {
    if (!hasFaceSide(*fi, true))
    {
      ret_face.face_side = fi->neighborPtr();
      check_neighbor_def = true;
    }
    else if (!hasFaceSide(*fi, false))
    {
      ret_face.face_side = fi->elemPtr();
      check_elem_def = true;
    }
  }
  else if (elem == fi->elemPtr())
    check_elem_def = true;
  else
  {
    mooseAssert(elem == fi->neighborPtr(), "This has to match something");
    check_neighbor_def = true;
  }
  if (check_elem_def && !hasFaceSide(*fi, true))
  {
    std::string additional_message = "It is not defined on the neighbor side either.";
    if (hasFaceSide(*fi, false))
      additional_message = "It is however defined on the neighbor side.";
    additional_message += " Face centroid: " + Moose::stringify(fi->faceCentroid());
    mooseError(_functor_name,
               " is not defined on the element side of the face information, but a face argument "
               "producer "
               "(e.g. residual object, postprocessor, etc.) has requested evaluation there.\n",
               additional_message);
  }
  if (check_neighbor_def && !hasFaceSide(*fi, false))
  {
    std::string additional_message = "It is not defined on the element side either.";
    if (hasFaceSide(*fi, true))
      additional_message = "It is however defined on the element side.";
    additional_message += " Face centroid: " + Moose::stringify(fi->faceCentroid());
    mooseError(
        _functor_name,
        " is not defined on the neighbor side of the face information, but a face argument "
        "producer (e.g. residual object, postprocessor, etc.) has requested evaluation there.\n",
        additional_message);
  }
  return ret_face;
}
clearCacheData()
template<typename T > void Moose::FunctorBase< T >::clearCacheData private inherited
clear cache data
Definition at line 681 of file MooseFunctor.h.
{
  for (auto & map_pr : _qp_to_value)
    for (auto & pr : map_pr.second)
      pr.first = false;
  for (auto & map_pr : _side_qp_to_value)
  {
    auto & side_vector = map_pr.second;
    for (auto & qp_vector : side_vector)
      for (auto & pr : qp_vector)
        pr.first = false;
  }
  _current_qp_map_key = DofObject::invalid_id;
  _current_qp_map_value = nullptr;
  _current_side_qp_map_key = DofObject::invalid_id;
  _current_side_qp_map_value = nullptr;
  _elem_arg_to_value.clear();
  _face_arg_to_value.clear();
  _node_arg_to_value.clear();
}
customSetup()
template<typename T > void Moose::FunctorBase< T >::customSetup (const ExecFlagType & exec_type) override virtual inherited
Implements Moose::FunctorAbstract.
Reimplemented in Function.
Definition at line 731 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(exec_type))
    clearCacheData();
}
Referenced by Function::customSetup().
dot() [1/6]
template<typename T > FunctorBase< T >::DotType Moose::FunctorBase< T >::dot (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluateDot overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 781 of file MooseFunctor.h.
{
  return evaluateDot(elem, state);
}
Referenced by FVFunctorTimeKernel::computeQpResidual(), and Moose::ADWrapperFunctor< T >::evaluateDot().
dot() [2/6]
template<typename T > FunctorBase< T >::DotType Moose::FunctorBase< T >::dot (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 809 of file MooseFunctor.h.
{
  return evaluateDot(elem_point, state);
}
dot() [3/6]
template<typename T > FunctorBase< T >::DotType Moose::FunctorBase< T >::dot (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 795 of file MooseFunctor.h.
{
  return evaluateDot(elem_qp, state);
}
dot() [4/6]
template<typename T > FunctorBase< T >::DotType Moose::FunctorBase< T >::dot (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 802 of file MooseFunctor.h.
{
  return evaluateDot(elem_side_qp, state);
}
dot() [5/6]
template<typename T > FunctorBase< T >::DotType Moose::FunctorBase< T >::dot (const FaceArg & face, const StateArg & state) const inherited
Definition at line 788 of file MooseFunctor.h.
{
  return evaluateDot(checkFace(face), state);
}
dot() [6/6]
template<typename T > FunctorBase< T >::DotType Moose::FunctorBase< T >::dot (const NodeArg & node, const StateArg & state) const inherited
Definition at line 816 of file MooseFunctor.h.
{
  return evaluateDot(node, state);
}
evaluate() [1/6]
template<typename T > PiecewiseByBlockLambdaFunctor< T >::ValueType PiecewiseByBlockLambdaFunctor< T >::evaluate (const Moose::ElemArg & elem, const Moose::StateArg & state) const override protected virtual
Evaluate the functor with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Implements Moose::FunctorBase< T >.
Definition at line 212 of file PiecewiseByBlockLambdaFunctor.h.
{
  const Elem * const elem = elem_arg.elem;
  mooseAssert(elem && elem != libMesh::remote_elem,
              "The element must be non-null and non-remote in functor material properties");
  auto it = _elem_functor.find(elem->subdomain_id());
  if (it == _elem_functor.end())
    subdomainErrorMessage(elem->subdomain_id());
  return it->second(elem_arg, time);
}
evaluate() [2/6]
template<typename T > PiecewiseByBlockLambdaFunctor< T >::ValueType PiecewiseByBlockLambdaFunctor< T >::evaluate (const Moose::ElemPointArg & elem_point, const Moose::StateArg & state) const override protected virtual
Evaluate the functor with a given element and point.
Some example implementations of this method could perform a two-term Taylor expansion using cell-centered value and gradient
Implements Moose::FunctorBase< T >.
Definition at line 275 of file PiecewiseByBlockLambdaFunctor.h.
{
  const Elem * const elem = elem_point_arg.elem;
  mooseAssert(elem && elem != libMesh::remote_elem,
              "The element must be non-null and non-remote in functor material properties");
  auto it = _elem_point_functor.find(elem->subdomain_id());
  if (it == _elem_point_functor.end())
    subdomainErrorMessage(elem->subdomain_id());
  return it->second(elem_point_arg, time);
}
evaluate() [3/6]
template<typename T > PiecewiseByBlockLambdaFunctor< T >::ValueType PiecewiseByBlockLambdaFunctor< T >::evaluate (const Moose::ElemQpArg & qp, const Moose::StateArg & state) const override protected virtual
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor evaluated at the requested state and space
Implements Moose::FunctorBase< T >.
Definition at line 249 of file PiecewiseByBlockLambdaFunctor.h.
{
  const auto sub_id = elem_qp.elem->subdomain_id();
  auto it = _elem_qp_functor.find(sub_id);
  if (it == _elem_qp_functor.end())
    subdomainErrorMessage(sub_id);
  return it->second(elem_qp, time);
}
evaluate() [4/6]
template<typename T > PiecewiseByBlockLambdaFunctor< T >::ValueType PiecewiseByBlockLambdaFunctor< T >::evaluate (const Moose::ElemSideQpArg & side_qp, const Moose::StateArg & state) const override protected virtual
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor evaluated at the requested state and space
Implements Moose::FunctorBase< T >.
Definition at line 262 of file PiecewiseByBlockLambdaFunctor.h.
{
  const auto sub_id = elem_side_qp.elem->subdomain_id();
  auto it = _elem_side_qp_functor.find(sub_id);
  if (it == _elem_side_qp_functor.end())
    subdomainErrorMessage(sub_id);
  return it->second(elem_side_qp, time);
}
evaluate() [5/6]
template<typename T > PiecewiseByBlockLambdaFunctor< T >::ValueType PiecewiseByBlockLambdaFunctor< T >::evaluate (const Moose::FaceArg & face, const Moose::StateArg & state) const override protected virtual
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor evaluated at the requested state and space
Implements Moose::FunctorBase< T >.
Definition at line 227 of file PiecewiseByBlockLambdaFunctor.h.
{
  using namespace Moose::FV;
  if (face.face_side)
  {
    const auto sub_id = face.face_side->subdomain_id();
    auto it = _face_functor.find(sub_id);
    if (it == _face_functor.end())
      subdomainErrorMessage(sub_id);
    return it->second(face, time);
  }
  mooseAssert(this->isInternalFace(*face.fi),
              "If we did not have a face side, then we must be an internal face");
  return interpolate(*this, face, time);
}
evaluate() [6/6]
template<typename T > PiecewiseByBlockLambdaFunctor< T >::ValueType PiecewiseByBlockLambdaFunctor< T >::evaluate (const Moose::NodeArg & node_arg, const Moose::StateArg & time) const override protected virtual
Implements Moose::FunctorBase< T >.
Definition at line 290 of file PiecewiseByBlockLambdaFunctor.h.
{
  mooseAssert(node_arg.node, "The node must be non-null in functor material properties");
  auto it = _node_functor.find(node_arg.subdomain_id);
  if (it == _node_functor.end())
    subdomainErrorMessage(node_arg.subdomain_id);
  return it->second(node_arg, time);
}
evaluateDot() [1/6]
template<typename T > virtual DotType Moose::FunctorBase< T >::evaluateDot (const ElemArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor time derivative with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Reimplemented in Moose::ConstantFunctor< T >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, Function, Postprocessor, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, MooseVariableFV< T >, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, Moose::RawValueFunctor< T >, and Moose::VectorCompositeFunctor< T >.
Definition at line 282 of file MooseFunctor.h.
  {
    mooseError("Element time derivative not implemented for functor " + functorName());
  }
evaluateDot() [2/6]
template<typename T > virtual DotType Moose::FunctorBase< T >::evaluateDot (const ElemPointArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor time derivative with a given element and point.
Reimplemented in Moose::ConstantFunctor< T >, Function, Postprocessor, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, and Moose::RawValueFunctor< T >.
Definition at line 322 of file MooseFunctor.h.
  {
    mooseError("Element-point time derivative not implemented for functor " + functorName());
  }
evaluateDot() [3/6]
template<typename T > virtual DotType Moose::FunctorBase< T >::evaluateDot (const ElemQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor time derivative evaluated at the requested state and space
Reimplemented in Moose::ConstantFunctor< T >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, Function, Postprocessor, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, and Moose::RawValueFunctor< T >.
Definition at line 302 of file MooseFunctor.h.
  {
    mooseError("Element quadrature point time derivative not implemented for functor " +
               functorName());
  }
evaluateDot() [4/6]
template<typename T > virtual DotType Moose::FunctorBase< T >::evaluateDot (const ElemSideQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor time derivative evaluated at the requested state and space
Reimplemented in Moose::ConstantFunctor< T >, Function, Postprocessor, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, and Moose::RawValueFunctor< T >.
Definition at line 313 of file MooseFunctor.h.
  {
    mooseError("Element side quadrature point time derivative not implemented for functor " +
               functorName());
  }
evaluateDot() [5/6]
template<typename T > virtual DotType Moose::FunctorBase< T >::evaluateDot (const FaceArg & , const StateArg &) const inline protected virtual inherited
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor time derivative evaluated at the requested state and space
Reimplemented in Moose::ConstantFunctor< T >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, Function, Postprocessor, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, Moose::RawValueFunctor< T >, and Moose::VectorCompositeFunctor< T >.
Definition at line 292 of file MooseFunctor.h.
  {
    mooseError("Face time derivative not implemented for functor " + functorName());
  }
evaluateDot() [6/6]
template<typename T > virtual DotType Moose::FunctorBase< T >::evaluateDot (const NodeArg & , const StateArg &) const inline protected virtual inherited
Reimplemented in Moose::ConstantFunctor< T >, Function, Postprocessor, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, and Moose::RawValueFunctor< T >.
Definition at line 327 of file MooseFunctor.h.
  {
    mooseError("Time derivative at node not implemented for functor " + functorName());
  }
evaluateGradDot() [1/6]
template<typename T > virtual GradientType Moose::FunctorBase< T >::evaluateGradDot (const ElemArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor gradient-dot with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Reimplemented in Moose::ConstantFunctor< T >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, Moose::RawValueFunctor< T >, and Moose::VectorComponentFunctor< T >.
Definition at line 336 of file MooseFunctor.h.
  {
    mooseError("Element gradient-dot not implemented for functor " + functorName());
  }
evaluateGradDot() [2/6]
template<typename T > virtual GradientType Moose::FunctorBase< T >::evaluateGradDot (const ElemPointArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor gradient-dot with a given element and point.
Reimplemented in Moose::ConstantFunctor< T >, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, and Moose::RawValueFunctor< T >.
Definition at line 376 of file MooseFunctor.h.
  {
    mooseError("Element-point gradient-dot not implemented for functor " + functorName());
  }
evaluateGradDot() [3/6]
template<typename T > virtual GradientType Moose::FunctorBase< T >::evaluateGradDot (const ElemQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient-dot evaluated at the requested state and space
Reimplemented in Moose::ConstantFunctor< T >, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, and Moose::RawValueFunctor< T >.
Definition at line 356 of file MooseFunctor.h.
  {
    mooseError("Element quadrature point gradient-dot not implemented for functor " +
               functorName());
  }
evaluateGradDot() [4/6]
template<typename T > virtual GradientType Moose::FunctorBase< T >::evaluateGradDot (const ElemSideQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient-dot evaluated at the requested state and space
Reimplemented in Moose::ConstantFunctor< T >, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, and Moose::RawValueFunctor< T >.
Definition at line 367 of file MooseFunctor.h.
  {
    mooseError("Element side quadrature point gradient-dot not implemented for functor " +
               functorName());
  }
evaluateGradDot() [5/6]
template<typename T > virtual GradientType Moose::FunctorBase< T >::evaluateGradDot (const FaceArg & , const StateArg &) const inline protected virtual inherited
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor gradient-dot evaluated at the requested state and space
Reimplemented in Moose::ConstantFunctor< T >, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, Moose::RawValueFunctor< T >, and Moose::VectorComponentFunctor< T >.
Definition at line 346 of file MooseFunctor.h.
  {
    mooseError("Face gradient-dot not implemented for functor " + functorName());
  }
evaluateGradDot() [6/6]
template<typename T > virtual GradientType Moose::FunctorBase< T >::evaluateGradDot (const NodeArg & , const StateArg &) const inline protected virtual inherited
Reimplemented in Moose::ConstantFunctor< T >, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, and Moose::RawValueFunctor< T >.
Definition at line 381 of file MooseFunctor.h.
  {
    mooseError("Gradient-dot at node not implemented for functor " + functorName());
  }
evaluateGradient() [1/6]
template<typename T > virtual GradientType Moose::FunctorBase< T >::evaluateGradient (const ElemPointArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor gradient with a given element and point.
Reimplemented in Moose::ConstantFunctor< T >, Function, Postprocessor, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, and Moose::RawValueFunctor< T >.
Definition at line 268 of file MooseFunctor.h.
  {
    mooseError("Element-point gradient not implemented for functor " + functorName());
  }
evaluateGradient() [2/6]
template<typename T > virtual GradientType Moose::FunctorBase< T >::evaluateGradient (const ElemQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient evaluated at the requested state and space
Reimplemented in Moose::ConstantFunctor< T >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, Function, Postprocessor, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, Moose::RawValueFunctor< T >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 249 of file MooseFunctor.h.
  {
    mooseError("Element quadrature point gradient not implemented for functor " + functorName());
  }
evaluateGradient() [3/6]
template<typename T > virtual GradientType Moose::FunctorBase< T >::evaluateGradient (const ElemSideQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient evaluated at the requested state and space
Reimplemented in Moose::ConstantFunctor< T >, Function, Postprocessor, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, and Moose::RawValueFunctor< T >.
Definition at line 259 of file MooseFunctor.h.
  {
    mooseError("Element side quadrature point gradient not implemented for functor " +
               functorName());
  }
evaluateGradient() [4/6]
template<typename T > PiecewiseByBlockLambdaFunctor< T >::GradientType PiecewiseByBlockLambdaFunctor< T >::evaluateGradient (const Moose::ElemArg & , const Moose::StateArg &) const override protected virtual
Evaluate the functor gradient with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Reimplemented from Moose::FunctorBase< T >.
Definition at line 303 of file PiecewiseByBlockLambdaFunctor.h.
{
  return Moose::FV::greenGaussGradient(elem_arg, time, *this, true, _mesh);
}
evaluateGradient() [5/6]
template<typename T > PiecewiseByBlockLambdaFunctor< T >::GradientType PiecewiseByBlockLambdaFunctor< T >::evaluateGradient (const Moose::FaceArg & , const Moose::StateArg &) const override protected virtual
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor gradient evaluated at the requested state and space
Reimplemented from Moose::FunctorBase< T >.
Definition at line 311 of file PiecewiseByBlockLambdaFunctor.h.
{
  return Moose::FV::greenGaussGradient(face_arg, time, *this, true, _mesh);
}
evaluateGradient() [6/6]
template<typename T > virtual GradientType Moose::FunctorBase< T >::evaluateGradient (const NodeArg & , const StateArg &) const inline protected virtual inherited
Reimplemented in Moose::ConstantFunctor< T >, Function, Postprocessor, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ADWrapperFunctor< T >, Moose::RawValueFunctor< T >, and Moose::ArrayComponentFunctor< T, ArrayTypeFunctor >.
Definition at line 273 of file MooseFunctor.h.
  {
    mooseError("Gradient at node not implemented for functor " + functorName());
  }
functorName()
template<typename T > const MooseFunctorName & Moose::FunctorBase< T >::functorName () const inline inherited
Return the functor name.
Definition at line 77 of file MooseFunctor.h.
{ return _functor_name; }
Referenced by Moose::FunctorBase< T >::evaluateDot(), Moose::FunctorBase< T >::evaluateGradDot(), Moose::FunctorBase< T >::evaluateGradient(), and Moose::FunctorBase< T >::hasBlocks().
gradDot() [1/6]
template<typename T > FunctorBase< T >::GradientType Moose::FunctorBase< T >::gradDot (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluateGradDot overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 823 of file MooseFunctor.h.
{
  return evaluateGradDot(elem, state);
}
Referenced by Moose::ADWrapperFunctor< T >::evaluateGradDot(), and Moose::VectorComponentFunctor< T >::evaluateGradDot().
gradDot() [2/6]
template<typename T > FunctorBase< T >::GradientType Moose::FunctorBase< T >::gradDot (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 851 of file MooseFunctor.h.
{
  return evaluateGradDot(elem_point, state);
}
gradDot() [3/6]
template<typename T > FunctorBase< T >::GradientType Moose::FunctorBase< T >::gradDot (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 837 of file MooseFunctor.h.
{
  return evaluateGradDot(elem_qp, state);
}
gradDot() [4/6]
template<typename T > FunctorBase< T >::GradientType Moose::FunctorBase< T >::gradDot (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 844 of file MooseFunctor.h.
{
  return evaluateGradDot(elem_side_qp, state);
}
gradDot() [5/6]
template<typename T > FunctorBase< T >::GradientType Moose::FunctorBase< T >::gradDot (const FaceArg & face, const StateArg & state) const inherited
Definition at line 830 of file MooseFunctor.h.
{
  return evaluateGradDot(checkFace(face), state);
}
gradDot() [6/6]
template<typename T > FunctorBase< T >::GradientType Moose::FunctorBase< T >::gradDot (const NodeArg & node, const StateArg & state) const inherited
Definition at line 858 of file MooseFunctor.h.
{
  return evaluateGradDot(node, state);
}
gradient() [1/6]
template<typename T > FunctorBase< T >::GradientType Moose::FunctorBase< T >::gradient (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluateGradient overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 739 of file MooseFunctor.h.
{
  return evaluateGradient(elem, state);
}
Referenced by GradientJumpIndicator::computeQpIntegral(), Moose::FV::containerInterpolate(), Moose::ADWrapperFunctor< T >::evaluateGradient(), Moose::VectorComponentFunctor< T >::evaluateGradient(), Moose::FV::greenGaussGradient(), Moose::FV::interpCoeffsAndAdvected(), and Moose::FV::linearInterpolation().
gradient() [2/6]
template<typename T > FunctorBase< T >::GradientType Moose::FunctorBase< T >::gradient (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 767 of file MooseFunctor.h.
{
  return evaluateGradient(elem_point, state);
}
gradient() [3/6]
template<typename T > FunctorBase< T >::GradientType Moose::FunctorBase< T >::gradient (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 753 of file MooseFunctor.h.
{
  return evaluateGradient(elem_qp, state);
}
gradient() [4/6]
template<typename T > FunctorBase< T >::GradientType Moose::FunctorBase< T >::gradient (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 760 of file MooseFunctor.h.
{
  return evaluateGradient(elem_side_qp, state);
}
gradient() [5/6]
template<typename T > FunctorBase< T >::GradientType Moose::FunctorBase< T >::gradient (const FaceArg & face, const StateArg & state) const inherited
Definition at line 746 of file MooseFunctor.h.
{
  return evaluateGradient(checkFace(face), state);
}
gradient() [6/6]
template<typename T > FunctorBase< T >::GradientType Moose::FunctorBase< T >::gradient (const NodeArg & node, const StateArg & state) const inherited
Definition at line 774 of file MooseFunctor.h.
{
  return evaluateGradient(node, state);
}
hasBlocks()
template<typename T > bool PiecewiseByBlockLambdaFunctor< T >::hasBlocks (SubdomainID) const override virtual
Returns whether the functor is defined on this block.
Reimplemented from Moose::FunctorBase< T >.
Definition at line 185 of file PiecewiseByBlockLambdaFunctor.h.
{
  // If any of the maps has a functor for that block, it has the block
  const bool has_blocks = _elem_functor.count(id);
  mooseAssert(has_blocks == _face_functor.count(id),
              "All functor sets should agree on whether we have this sub id");
  mooseAssert(has_blocks == _elem_qp_functor.count(id),
              "All functor sets should agree on whether we have this sub id");
  mooseAssert(has_blocks == _elem_side_qp_functor.count(id),
              "All functor sets should agree on whether we have this sub id");
  return has_blocks;
}
hasFaceSide()
template<typename T > bool Moose::FunctorBase< T >::hasFaceSide (const FaceInfo & fi, const bool fi_elem_side) const override virtual inherited
Implements FaceArgInterface.
Reimplemented in Moose::NullFunctor< T >, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, InterfaceIntegralVariableValuePostprocessor, InternalSideIntegralVariablePostprocessor, SideIntegralFunctorPostprocessorTempl< is_ad >, SideIntegralVariablePostprocessor, Moose::ADWrapperFunctor< T >, and Moose::RawValueFunctor< T >.
Definition at line 865 of file MooseFunctor.h.
{
  if (fi_elem_side)
    return hasBlocks(fi.elem().subdomain_id());
  else
    return fi.neighborPtr() && hasBlocks(fi.neighbor().subdomain_id());
}
Referenced by InternalSideIntegralVariablePostprocessor::hasFaceSide(), SideIntegralVariablePostprocessor::hasFaceSide(), and Moose::ADWrapperFunctor< T >::hasFaceSide().
isConstant()
template<typename T > virtual bool Moose::FunctorBase< T >::isConstant () const inline virtual inherited
Returns true if this functor is a constant.
Reimplemented in Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, Moose::ConstantFunctor< T >, Moose::ADWrapperFunctor< T >, and Moose::RawValueFunctor< T >.
Definition at line 167 of file MooseFunctor.h.
{ return false; }
Referenced by Moose::ADWrapperFunctor< T >::isConstant().
isExtrapolatedBoundaryFace()
template<typename T > bool PiecewiseByBlockLambdaFunctor< T >::isExtrapolatedBoundaryFace (const FaceInfo & , const Elem * , const Moose::StateArg &) const override virtual
Returns whether this (sided) face is an extrapolated boundary face for this functor.
Reimplemented from Moose::FunctorBase< T >.
Definition at line 167 of file PiecewiseByBlockLambdaFunctor.h.
{
  if (!fi.neighborPtr())
    return true;
  const bool defined_on_elem = _elem_functor.count(fi.elem().subdomain_id());
  const bool defined_on_neighbor = _elem_functor.count(fi.neighbor().subdomain_id());
  const bool extrapolated = (defined_on_elem + defined_on_neighbor) == 1;
  mooseAssert(defined_on_elem || defined_on_neighbor,
              "This shouldn't be called if we aren't defined on either side.");
  return extrapolated;
}
isInternalFace()
template<typename T > bool Moose::FunctorBase< T >::isInternalFace (const FaceInfo & fi) const inherited
Returns true if the face is an internal face.
Definition at line 463 of file MooseFunctor.h.
{
  if (!fi.neighborPtr())
    return false;
  return hasBlocks(fi.elem().subdomain_id()) && hasBlocks(fi.neighborPtr()->subdomain_id());
}
Referenced by FVAnisotropicDiffusion::computeQpResidual(), and FVDiffusion::computeQpResidual().
jacobianSetup()
template<typename T > void Moose::FunctorBase< T >::jacobianSetup override virtual inherited
Implements Moose::FunctorAbstract.
Reimplemented in Function, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 723 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_NONLINEAR))
    clearCacheData();
}
Referenced by Function::jacobianSetup().
operator()() [1/6]
template<typename T > FunctorBase< T >::ValueType Moose::FunctorBase< T >::operator() (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluate overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 491 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(elem, state);
  mooseAssert(state.state == 0,
              "Cached evaluations are only currently supported for the current state.");
  return queryFVArgCache(_elem_arg_to_value, elem);
}
operator()() [2/6]
template<typename T > FunctorBase< T >::ValueType Moose::FunctorBase< T >::operator() (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 601 of file MooseFunctor.h.
{
  return evaluate(elem_point, state);
}
operator()() [3/6]
template<typename T > FunctorBase< T >::ValueType Moose::FunctorBase< T >::operator() (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 550 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(elem_qp, state);
  const auto elem_id = elem_qp.elem->id();
  if (elem_id != _current_qp_map_key)
  {
    _current_qp_map_key = elem_id;
    _current_qp_map_value = &_qp_to_value[elem_id];
  }
  auto & qp_data = *_current_qp_map_value;
  const auto qp = elem_qp.qp;
  const auto * const qrule = elem_qp.qrule;
  mooseAssert(qrule, "qrule must be non-null");
  return queryQpCache(qp, *qrule, qp_data, elem_qp, state);
}
operator()() [4/6]
template<typename T > FunctorBase< T >::ValueType Moose::FunctorBase< T >::operator() (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 571 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(elem_side_qp, state);
  const Elem * const elem = elem_side_qp.elem;
  mooseAssert(elem, "elem must be non-null");
  const auto elem_id = elem->id();
  if (elem_id != _current_side_qp_map_key)
  {
    _current_side_qp_map_key = elem_id;
    _current_side_qp_map_value = &_side_qp_to_value[elem_id];
  }
  auto & side_qp_data = *_current_side_qp_map_value;
  const auto side = elem_side_qp.side;
  const auto qp = elem_side_qp.qp;
  const auto * const qrule = elem_side_qp.qrule;
  mooseAssert(qrule, "qrule must be non-null");
  // Check and see whether we even have sized for this side
  if (side >= side_qp_data.size())
    side_qp_data.resize(elem->n_sides());
  // Ok we were sized enough for our side
  auto & qp_data = side_qp_data[side];
  return queryQpCache(qp, *qrule, qp_data, elem_side_qp, state);
}
operator()() [5/6]
template<typename T > FunctorBase< T >::ValueType Moose::FunctorBase< T >::operator() (const FaceArg & face, const StateArg & state) const inherited
Definition at line 504 of file MooseFunctor.h.
{
  const auto face = checkFace(face_in);
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(face, state);
  mooseAssert(state.state == 0,
              "Cached evaluations are only currently supported for the current state.");
  return queryFVArgCache(_face_arg_to_value, face);
}
operator()() [6/6]
template<typename T > FunctorBase< T >::ValueType Moose::FunctorBase< T >::operator() (const NodeArg & node, const StateArg & state) const inherited
Definition at line 615 of file MooseFunctor.h.
{
  return evaluate(node, state);
}
queryFVArgCache()
template<typename T > template<typename SpaceArg > FunctorBase< T >::ValueType Moose::FunctorBase< T >::queryFVArgCache (std::map< SpaceArg, ValueType > & cache_data, const SpaceArg & space) const private inherited
check a finite volume spatial argument cache and if invalid then evaluate
Definition at line 474 of file MooseFunctor.h.
{
  // We don't want to evaluate if the key already exists, so instead we value initialize
  auto [it, inserted] = cache_data.try_emplace(space, ValueType());
  auto & value = it->second;
  if (inserted)
    // value not ready to go
    // this function is only called from functions that assert we are in the current time state
    value = evaluate(space, currentState());
  return value;
}
queryQpCache()
template<typename T > template<typename SpaceArg , typename StateArg > FunctorBase< T >::ValueType Moose::FunctorBase< T >::queryQpCache (unsigned int qp, const QBase & qrule, std::vector< std::pair< bool, T > > & qp_cache_data, const SpaceArg & space, const StateArg & state) const private inherited
check a qp cache and if invalid then evaluate
Definition at line 520 of file MooseFunctor.h.
{
  // Check and see whether we even have sized for this quadrature point. If we haven't then we
  // must evaluate
  if (qp >= qp_cache_data.size())
  {
    qp_cache_data.resize(qrule.n_points(), std::make_pair(false, ValueType()));
    auto & pr = qp_cache_data[qp];
    pr.second = evaluate(space, state);
    pr.first = true;
    return pr.second;
  }
  // We've already sized for this qp, so let's see whether we have a valid cache value
  auto & pr = qp_cache_data[qp];
  if (pr.first)
    return pr.second;
  // No valid cache value so evaluate
  pr.second = evaluate(space, state);
  pr.first = true;
  return pr.second;
}
residualSetup()
template<typename T > void Moose::FunctorBase< T >::residualSetup override virtual inherited
Implements Moose::FunctorAbstract.
Reimplemented in Function, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 715 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_LINEAR))
    clearCacheData();
}
Referenced by Function::residualSetup().
setCacheClearanceSchedule()
template<typename T > void Moose::FunctorBase< T >::setCacheClearanceSchedule (const std::set< ExecFlagType > & clearance_schedule) inherited
Set how often to clear the functor evaluation cache.
Definition at line 608 of file MooseFunctor.h.
{
  _clearance_schedule = clearance_schedule;
}
setFunctor() [1/2]
template<typename T > template<typename PolymorphicLambda > void PiecewiseByBlockLambdaFunctor< T >::setFunctor (const MooseMesh & libmesh_dbg_varmesh, const std::set< SubdomainID > & block_ids, PolymorphicLambda my_lammy)
Definition at line 137 of file PiecewiseByBlockLambdaFunctor.h.
{
  mooseAssert(&mesh == &_mesh,
              "We should always be setting this functor with the same mesh. We may relax this "
              "assertion later");
  auto add_lammy = [this, my_lammy](const SubdomainID block_id)
  {
    auto pr = _elem_functor.emplace(block_id, my_lammy);
    if (!pr.second)
      mooseError("No insertion for the functor material property '",
                 this->functorName(),
                 "' for block id ",
                 block_id,
                 ". Another material must already declare this property on that block.");
    _face_functor.emplace(block_id, my_lammy);
    _elem_qp_functor.emplace(block_id, my_lammy);
    _elem_side_qp_functor.emplace(block_id, my_lammy);
    _elem_point_functor.emplace(block_id, my_lammy);
    _node_functor.emplace(block_id, my_lammy);
  };
  for (const auto block_id : block_ids)
    add_lammy(block_id);
}
setFunctor() [2/2]
template<typename T > template<typename PolymorphicLambda > void PiecewiseByBlockLambdaFunctor< T >::setFunctor (const MooseMesh & mesh, const std::set< SubdomainID > & block_ids, PolymorphicLambda my_lammy)
Set the functor that will be used in calls to evaluate overloads.
Parameters
mesh The mesh that the functor is defined on
block_ids The block/subdomain IDs that the user-provided functor is valid for
my_lammy The functor that defines how this object is evaluated
Referenced by PiecewiseByBlockLambdaFunctor< T >::PiecewiseByBlockLambdaFunctor().
subdomainErrorMessage()
template<typename T > void PiecewiseByBlockLambdaFunctor< T >::subdomainErrorMessage (SubdomainID sub_id) const private
Provide a useful error message about lack of functor material property on the provided subdomain sub_id.
Definition at line 200 of file PiecewiseByBlockLambdaFunctor.h.
{
  mooseError("The provided subdomain ID ",
             std::to_string(sub_id),
             " doesn't exist in the map for lambda functor '",
             this->functorName(),
             "'! This is likely because you did not provide a functor material "
             "definition on that subdomain");
}
timestepSetup()
template<typename T > void Moose::FunctorBase< T >::timestepSetup override virtual inherited
Implements Moose::FunctorAbstract.
Reimplemented in Function, MemoryUsage, NumNonlinearIterations, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 707 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_TIMESTEP_BEGIN))
    clearCacheData();
}
Referenced by Function::timestepSetup().
Member Data Documentation
_clearance_schedule
template<typename T > std::set<ExecFlagType> Moose::FunctorBase< T >::_clearance_schedule private inherited
How often to clear the material property cache.
Definition at line 411 of file MooseFunctor.h.
_current_qp_map_key
template<typename T > dof_id_type Moose::FunctorBase< T >::_current_qp_map_key = DofObject::invalid_id mutable private inherited
Current key for qp map cache.
Definition at line 417 of file MooseFunctor.h.
_current_qp_map_value
template<typename T > std::vector<std::pair<bool, ValueType> >* Moose::FunctorBase< T >::_current_qp_map_value = nullptr mutable private inherited
Current value for qp map cache.
Definition at line 420 of file MooseFunctor.h.
_current_side_qp_map_key
template<typename T > dof_id_type Moose::FunctorBase< T >::_current_side_qp_map_key = DofObject::invalid_id mutable private inherited
Current key for side-qp map cache.
Definition at line 433 of file MooseFunctor.h.
_current_side_qp_map_value
template<typename T > std::vector<std::vector<std::pair<bool, ValueType> > >* Moose::FunctorBase< T >::_current_side_qp_map_value mutable private inherited
Initial value:
=
      nullptr
Current value for side-qp map cache.
Definition at line 436 of file MooseFunctor.h.
_elem_arg_to_value
template<typename T > std::map<ElemArg, ValueType> Moose::FunctorBase< T >::_elem_arg_to_value mutable private inherited
Map from element arguments to their cached evaluations.
Definition at line 449 of file MooseFunctor.h.
_elem_functor
template<typename T > std::unordered_map<SubdomainID, ElemFn> PiecewiseByBlockLambdaFunctor< T >::_elem_functor private
Functors that return element average values (or cell centroid values or whatever the implementer wants to return for a given element argument)
Definition at line 99 of file PiecewiseByBlockLambdaFunctor.h.
_elem_point_functor
template<typename T > std::unordered_map<SubdomainID, ElemPointFn> PiecewiseByBlockLambdaFunctor< T >::_elem_point_functor private
Functors that return evaluations at an arbitrary physical point in an element.
Definition at line 112 of file PiecewiseByBlockLambdaFunctor.h.
_elem_qp_functor
template<typename T > std::unordered_map<SubdomainID, ElemQpFn> PiecewiseByBlockLambdaFunctor< T >::_elem_qp_functor private
Functors that will evaluate elements at quadrature points.
Definition at line 106 of file PiecewiseByBlockLambdaFunctor.h.
_elem_side_qp_functor
template<typename T > std::unordered_map<SubdomainID, ElemSideQpFn> PiecewiseByBlockLambdaFunctor< T >::_elem_side_qp_functor private
Functors that will evaluate elements at side quadrature points.
Definition at line 109 of file PiecewiseByBlockLambdaFunctor.h.
_face_arg_to_value
template<typename T > std::map<FaceArg, ValueType> Moose::FunctorBase< T >::_face_arg_to_value mutable private inherited
Map from face arguments to their cached evaluations.
Definition at line 452 of file MooseFunctor.h.
_face_functor
template<typename T > std::unordered_map<SubdomainID, FaceFn> PiecewiseByBlockLambdaFunctor< T >::_face_functor private
Functors that return the property value on the requested side of the face (e.g.
the infinitesimal + or - side of the face)
Definition at line 103 of file PiecewiseByBlockLambdaFunctor.h.
_functor_name
template<typename T > MooseFunctorName Moose::FunctorBase< T >::_functor_name private inherited
name of the functor
Definition at line 458 of file MooseFunctor.h.
Referenced by Moose::FunctorBase< T >::functorName().
_mesh
template<typename T > const MooseMesh& PiecewiseByBlockLambdaFunctor< T >::_mesh private
The mesh that this functor operates on.
Definition at line 118 of file PiecewiseByBlockLambdaFunctor.h.
_node_arg_to_value
template<typename T > std::map<NodeArg, ValueType> Moose::FunctorBase< T >::_node_arg_to_value mutable private inherited
Map from nodal arguments to their cached evaluations.
Definition at line 455 of file MooseFunctor.h.
_node_functor
template<typename T > std::unordered_map<SubdomainID, NodeFn> PiecewiseByBlockLambdaFunctor< T >::_node_functor private
Functors that return nodal values.
Definition at line 115 of file PiecewiseByBlockLambdaFunctor.h.
_qp_to_value
template<typename T > std::unordered_map<dof_id_type, std::vector<std::pair<bool, ValueType> > > Moose::FunctorBase< T >::_qp_to_value mutable private inherited
Cached element quadrature point functor property evaluations.
The map key is the element id. The map values should have size corresponding to the number of quadrature points on the element. The vector elements are pairs. The first member of the pair indicates whether a cached value has been computed. The second member of the pair is the (cached) value. If the boolean is false, then the value cannot be trusted
Definition at line 427 of file MooseFunctor.h.
_side_qp_to_value
template<typename T > std::unordered_map<dof_id_type, std::vector<std::vector<std::pair<bool, ValueType> > > > Moose::FunctorBase< T >::_side_qp_to_value mutable private inherited
Cached element quadrature point functor property evaluations.
The map key is the element id. The map values are a multi-dimensional vector (or vector of vectors) with the first index corresponding to the side and the second index corresponding to the quadrature point index. The elements returned after double indexing are pairs. The first member of the pair indicates whether a cached value has been computed. The second member of the pair is the (cached) value. If the boolean is false, then the value cannot be trusted
Definition at line 446 of file MooseFunctor.h.
The documentation for this class was generated from the following file:
moose/framework/include/utils/PiecewiseByBlockLambdaFunctor.h