Zapdos: MooseEnumItem Class Reference
MooseEnumItem Class Reference
Class for containing MooseEnum item information.
#include <MooseEnumItem.h>
Public Member Functions
MooseEnumItem ()
MooseEnumItem (const std::string &name, const int &id=INVALID_ID)
~MooseEnumItem ()=default
MooseEnumItem (const MooseEnumItem &other)
MooseEnumItem (MooseEnumItem &&)=default
MooseEnumItem & operator= (const MooseEnumItem &other)
MooseEnumItem & operator= (MooseEnumItem &&)=default
bool operator< (const MooseEnumItem &other) const
Less than operator.
void setID (const int &id)
Method to change the ID of the item, but only if it is an INVALID_ID.
const int & id () const
Return the numeric, name, or raw name.
const std::string & name () const
const std::string & rawName () const
operator int () const
Operator to allow this class to be used directly as a string for int.
operator std::string () const
bool operator== (const char *value) const
Comparison operators.
bool operator!= (const char *value) const
bool operator== (const std::string &value) const
bool operator!= (const std::string &value) const
bool operator== (int value) const
bool operator!= (int value) const
bool operator== (unsigned short value) const
bool operator!= (unsigned short value) const
bool operator== (const MooseEnumItem &) const
bool operator!= (const MooseEnumItem &) const
Static Public Attributes
static const int INVALID_ID = std::numeric_limits<int>::min()
Private Attributes
std::string _raw_name
The name as provided in constructor.
std::string _name
Upper case name.
int _id
The numeric value for item.
Friends
std::ostream & operator<< (std::ostream &out, const MooseEnumItem &item)
ostream operator for string printing.
Detailed Description
Class for containing MooseEnum item information.
Definition at line 18 of file MooseEnumItem.h.
Constructor & Destructor Documentation
MooseEnumItem() [1/4]
MooseEnumItem::MooseEnumItem ()
Definition at line 14 of file MooseEnumItem.C.
: _raw_name("INVALID"), _name("INVALID"), _id(INVALID_ID) {}
MooseEnumItem() [2/4]
MooseEnumItem::MooseEnumItem (const std::string & name, const int & id = INVALID_ID)
Definition at line 16 of file MooseEnumItem.C.
  : _raw_name(MooseUtils::trim(name)), _name(MooseUtils::toUpper(_raw_name)), _id(id)
{
}
~MooseEnumItem()
MooseEnumItem::~MooseEnumItem () default
MooseEnumItem() [3/4]
MooseEnumItem::MooseEnumItem (const MooseEnumItem & other)
Definition at line 21 of file MooseEnumItem.C.
  : _raw_name(other._raw_name), _name(other._name), _id(other._id)
{
}
MooseEnumItem() [4/4]
MooseEnumItem::MooseEnumItem (MooseEnumItem &&) default
Member Function Documentation
id()
const int & MooseEnumItem::id () const inline
Return the numeric, name, or raw name.
Definition at line 34 of file MooseEnumItem.h.
{ return _id; }
Referenced by MooseEnumBase::addEnumerationItem(), AttribExecOns::AttribExecOns(), MooseEnum::compareCurrent(), MooseEnum::getEnum(), MooseEnum::isValid(), MooseEnum::operator int(), operator!=(), operator==(), and setID().
name()
const std::string & MooseEnumItem::name () const inline
Definition at line 35 of file MooseEnumItem.h.
{ return _name; }
Referenced by MooseEnumBase::addEnumerationItem(), MooseEnumBase::checkDeprecated(), MooseEnum::compareCurrent(), Transient::constrainDTFromMultiApp(), MooseEnumBase::find(), FEProblemBase::joinAndFinalize(), operator!=(), MooseEnum::operator!=(), operator==(), MooseEnum::operator==(), and ComputeDiracThread::printGeneralExecutionInformation().
operator int()
MooseEnumItem::operator int () const inline
Operator to allow this class to be used directly as a string for int.
Definition at line 43 of file MooseEnumItem.h.
{ return _id; }
operator std::string()
MooseEnumItem::operator std::string () const inline
Definition at line 44 of file MooseEnumItem.h.
{ return _name; }
operator!=() [1/5]
bool MooseEnumItem::operator!= (const char * value) const
Definition at line 43 of file MooseEnumItem.C.
{
  std::string name(MooseUtils::toUpper(value));
  return _name != name;
}
operator!=() [2/5]
bool MooseEnumItem::operator!= (const MooseEnumItem & item) const
Definition at line 70 of file MooseEnumItem.C.
{
  return _id != item.id() && _name != MooseUtils::toUpper(item.name());
}
operator!=() [3/5]
bool MooseEnumItem::operator!= (const std::string & value) const
Definition at line 57 of file MooseEnumItem.C.
{
  std::string name(MooseUtils::toUpper(value));
  return _name != name;
}
operator!=() [4/5]
bool MooseEnumItem::operator!= (int value) const inline
Definition at line 60 of file MooseEnumItem.h.
{ return _id != value; }
operator!=() [5/5]
bool MooseEnumItem::operator!= (unsigned short value) const inline
Definition at line 63 of file MooseEnumItem.h.
{ return _id != value; }
operator<()
bool MooseEnumItem::operator< (const MooseEnumItem & other) const inline
Less than operator.
This is required for this class to work in maps and sets.
Definition at line 72 of file MooseEnumItem.h.
  {
    return _id != other._id ? _id < other._id : _name < other._name;
  }
operator=() [1/2]
MooseEnumItem & MooseEnumItem::operator= (const MooseEnumItem & other)
Definition at line 27 of file MooseEnumItem.C.
{
  _raw_name = other._raw_name;
  _name = other._name;
  _id = other._id;
  return *this;
}
operator=() [2/2]
MooseEnumItem & MooseEnumItem::operator= (MooseEnumItem &&) default
operator==() [1/5]
bool MooseEnumItem::operator== (const char * value) const
Comparison operators.
The comparison operators using the char * and string are case sensitive.
Definition at line 36 of file MooseEnumItem.C.
{
  std::string name(MooseUtils::toUpper(value));
  return _name == name;
}
operator==() [2/5]
bool MooseEnumItem::operator== (const MooseEnumItem & item) const
Definition at line 64 of file MooseEnumItem.C.
{
  return _id == item.id() && _name == MooseUtils::toUpper(item.name());
}
operator==() [3/5]
bool MooseEnumItem::operator== (const std::string & value) const
Definition at line 50 of file MooseEnumItem.C.
{
  std::string name(MooseUtils::toUpper(value));
  return _name == name;
}
operator==() [4/5]
bool MooseEnumItem::operator== (int value) const inline
Definition at line 59 of file MooseEnumItem.h.
{ return _id == value; }
operator==() [5/5]
bool MooseEnumItem::operator== (unsigned short value) const inline
Definition at line 62 of file MooseEnumItem.h.
{ return _id == value; }
rawName()
const std::string & MooseEnumItem::rawName () const inline
Definition at line 36 of file MooseEnumItem.h.
{ return _raw_name; }
Referenced by MooseEnum::operator std::string().
setID()
void MooseEnumItem::setID (const int & id)
Method to change the ID of the item, but only if it is an INVALID_ID.
An error is produced if the ID is valid and this method is called.
This is needed to allow ExecFlagType objects to be created without an ID being provided, the ID is assigned when ExecFlagEnum::addAvailableFlags is called.
Definition at line 83 of file MooseEnumItem.C.
{
  if (_id != INVALID_ID)
    mooseError("The ID of a MooseEnumItem can not be changed if it is valid, the item ",
               _name,
               " has a valid id of ",
               _id,
               ".");
  _id = id;
}
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const MooseEnumItem & item) friend
ostream operator for string printing.
Definition at line 75 of file MooseEnumItem.C.
{
  out << item.rawName();
  return out;
}
Member Data Documentation
_id
int MooseEnumItem::_id private
The numeric value for item.
Definition at line 99 of file MooseEnumItem.h.
Referenced by id(), operator int(), operator!=(), operator<(), operator=(), operator==(), and setID().
_name
std::string MooseEnumItem::_name private
Upper case name.
Definition at line 96 of file MooseEnumItem.h.
Referenced by name(), operator std::string(), operator!=(), operator<(), operator=(), operator==(), and setID().
_raw_name
std::string MooseEnumItem::_raw_name private
The name as provided in constructor.
Definition at line 93 of file MooseEnumItem.h.
Referenced by operator=(), and rawName().
INVALID_ID
const int MooseEnumItem::INVALID_ID = std::numeric_limits<int>::min() static
Definition at line 21 of file MooseEnumItem.h.
Referenced by MooseEnum::assign(), MooseEnum::isValid(), and setID().
The documentation for this class was generated from the following files:
moose/framework/include/utils/MooseEnumItem.h
moose/framework/src/utils/MooseEnumItem.C