Zapdos: ReporterState< T > Class Template Reference
ReporterState< T > Class Template Reference
A special version of RestartableData to aid in storing Reporter values.
#include <ReporterState.h>
Public Member Functions
ReporterState (const ReporterName &name)
void copyValuesBack ()
Copy stored values back in time to old/older etc.
std::string valueType () const override final
const ReporterName & getReporterName () const
Return the ReporterName that this state is associated with.
void addConsumer (ReporterMode mode, const MooseObject &moose_object)
Add a consumer for this ReporterState.
const std::set< std::pair< ReporterMode, const MooseObject * > > & getConsumers () const
Returns the consumers for this state; a pair that consists of the mode that the state is being consumed by, and the object consuming it.
void setIsPostprocessor ()
Sets the special Reporter type to a Postprocessor.
void setIsVectorPostprocessor ()
Sets the special Reporter type to a VectorPostprocessor.
const std::list< T > & get () const
std::list< T > & set ()
void reset ()
Resets (destructs) the underlying data.
virtual std::string type () const override final
String identifying the type of parameter stored.
virtual const std::type_info & typeId () const override final
The type ID of the underlying data.
virtual bool hasStoreJSON () const override final
const std::string & name () const
The full (unique) name of this particular piece of data.
void * context ()
A context pointer for helping with load / store.
bool hasContext () const
bool declared () const
Whether or not this data has been declared.
void setDeclared (const SetDeclaredKey)
Sets that this restartable value has been declared.
bool loaded () const
Whether or not this data has been loaded.
void setNotLoaded (const SetNotLoadedKey)
Sets that this restartable value has been loaded.
bool stored () const
Whether or not this data has been loaded.
void setNotStored (const SetNotStoredKey)
Sets that this restartable value has been loaded.
void store (std::ostream &stream)
Stores the value into the stream stream and sets it as stored.
void store (nlohmann::json &json, const StoreJSONParams &params=StoreJSONParams{}) const
Stores this restartable data in the JSON entry json, with the options set by params (optional; defaults to just the type and underlying value)
void load (std::istream &stream)
Loads the value from the stream stream and sets it as loaded.
T & value (const std::size_t time_index=0)
Return a reference to the current value or one of the old values.
const T & value (const std::size_t time_index=0) const
void storeInternal (std::ostream &stream) override final
Loads and stores the data from/to a stream for restart.
void loadInternal (std::istream &stream) override final
Load the RestartableData from a binary stream.
Static Public Attributes
static constexpr bool has_store_json
Whether or not this type has a JSON store method implemented.
Protected Member Functions
virtual void storeJSONValue (nlohmann::json &json) const override final
Internal method for storing the underlying JSON value.
Protected Attributes
const std::string _name
The full (unique) name of this particular piece of data.
void *const _context
A context pointer for helping with load and store.
Private Attributes
ReporterName _reporter_name
Name of data that state is associated.
std::set< std::pair< ReporterMode, const MooseObject * > > _consumers
The consumers for this state; we store the MooseObject for detailed error reporting.
std::unique_ptr< std::list< T > > _value
Stored value.
bool _declared
Whether or not this data has been declared (true) or only retreived (false)
bool _loaded
Whether or not this has value has been loaded.
bool _stored
Whether or not this has value has been stored.
Detailed Description
template<typename T>
class ReporterState< T >
A special version of RestartableData to aid in storing Reporter values.
This object is used by the ReporterData object. The objects provides a convenient method to define Reporter data that has a value as well as some number of old data values. Please refer to ReporterData.h for more information regarding the use of this class.
Parameters
name The name of the Reporter value
This class stores the current/old/older/... data using a std::list to allow values to be inserted into the data structure without corrupting references to the other values. This allows for arbitrary time data to be stored.
NOTE: Access to the data should be through the value() method to ensure the data is allocated correctly
Definition at line 110 of file ReporterState.h.
Constructor & Destructor Documentation
ReporterState()
template<typename T > ReporterState< T >::ReporterState (const ReporterName & name)
Definition at line 153 of file ReporterState.h.
  : ReporterStateBase(name), RestartableData<std::list<T>>(name.getRestartableName(), nullptr)
{
}
Member Function Documentation
addConsumer()
void ReporterStateBase::addConsumer (ReporterMode mode, const MooseObject & moose_object) inherited
Add a consumer for this ReporterState.
Parameters
mode The mode that the object will consume the Reporter value
moose_object The MooseObject doing the consuming (for error reporting)
See also
ReporterData
Definition at line 17 of file ReporterState.C.
{
  _consumers.emplace(mode, &moose_object);
}
Referenced by ReporterTransferInterface::addReporterTransferMode().
context()
void * RestartableDataValue::context () inline inherited
A context pointer for helping with load / store.
Definition at line 65 of file RestartableData.h.
{ return _context; }
copyValuesBack()
template<typename T > void ReporterState< T >::copyValuesBack
Copy stored values back in time to old/older etc.
Definition at line 191 of file ReporterState.h.
{
  std::list<T> & values = this->set();
  for (typename std::list<T>::reverse_iterator iter = values.rbegin();
       std::next(iter) != values.rend();
       ++iter)
    (*iter) = (*std::next(iter));
}
declared()
bool RestartableDataValue::declared () const inline inherited
Whether or not this data has been declared.
Definition at line 85 of file RestartableData.h.
{ return _declared; }
Referenced by RestartableDataValue::store().
get()
const std::list< T > & RestartableData< std::list< T > >::get inline inherited
Returns
a read-only reference to the parameter value.
Definition at line 237 of file RestartableData.h.
{
  mooseAssert(_value, "Not valid");
  return *_value;
}
getConsumers()
const std::set< std::pair< ReporterMode, const MooseObject * > > & ReporterStateBase::getConsumers () const inline inherited
Returns the consumers for this state; a pair that consists of the mode that the state is being consumed by, and the object consuming it.
See also
ReporterContext
Definition at line 56 of file ReporterState.h.
  {
    return _consumers;
  }
Referenced by ReporterData::getReporterInfo(), and ReporterContextBase::requiresConsumerModes().
getReporterName()
const ReporterName & ReporterStateBase::getReporterName () const inline inherited
Return the ReporterName that this state is associated with.
Definition at line 41 of file ReporterState.h.
{ return _reporter_name; }
Referenced by ReporterData::getReporterInfo().
hasContext()
bool RestartableDataValue::hasContext () const inline inherited
Returns
Whether or not the data has context set.
Definition at line 70 of file RestartableData.h.
{ return _context != nullptr; }
Referenced by RestartableDataValue::store().
hasStoreJSON()
virtual bool RestartableData< std::list< T > >::hasStoreJSON () const inline final override virtual inherited
Returns
Whether or not this value supports storing JSON via store
Implements RestartableDataValue.
Definition at line 256 of file RestartableData.h.
{ return has_store_json; }
load()
void RestartableDataValue::load (std::istream & stream) inherited
Loads the value from the stream stream and sets it as loaded.
Definition at line 32 of file RestartableData.C.
{
  loadInternal(stream);
  _loaded = true;
}
loaded()
bool RestartableDataValue::loaded () const inline inherited
Whether or not this data has been loaded.
This is typically reset on a call to RestartableDataReader::restore()
Definition at line 98 of file RestartableData.h.
{ return _loaded; }
Referenced by RestartableDataValue::store().
loadInternal()
template<typename T > void ReporterState< T >::loadInternal (std::istream & stream) final override virtual
Load the RestartableData from a binary stream.
Reimplemented from RestartableData< std::list< T > >.
Definition at line 215 of file ReporterState.h.
{
  // Read the container size
  std::size_t size = 0;
  dataLoad(stream, size, nullptr);
  auto & values = this->set();
  // If the current container is undersized, expand it to fit the loaded data
  if (values.size() < size)
    values.resize(size);
  // Load each entry of the list directly into the storage
  // Because we don't shrink the container if the stored size is smaller than
  // our declared size, we have the odd iterator combo you see below
  for (auto & val : as_range(values.begin(), std::next(values.begin(), size)))
    loadHelper(stream, val, nullptr);
}
name()
const std::string & RestartableDataValue::name () const inline inherited
The full (unique) name of this particular piece of data.
Definition at line 60 of file RestartableData.h.
{ return _name; }
Referenced by RestartableDataMap::addData(), RestartableDataMap::findData(), and RestartableDataValue::store().
reset()
void RestartableData< std::list< T > >::reset inline inherited
Resets (destructs) the underlying data.
Definition at line 247 of file RestartableData.h.
{
  mooseAssert(_value, "Not valid"); // shouldn't really call this twice
  _value.reset();
}
set()
std::list< T > & RestartableData< std::list< T > >::set inline inherited
Returns
a writable reference to the parameter value.
Definition at line 242 of file RestartableData.h.
{
  mooseAssert(_value, "Not valid");
  return *_value;
}
setDeclared()
void RestartableDataValue::setDeclared (const SetDeclaredKey) inherited
Sets that this restartable value has been declared.
Definition at line 18 of file RestartableData.C.
{
  mooseAssert(!_declared, "Already declared");
  _declared = true;
}
Referenced by MooseApp::registerRestartableData().
setIsPostprocessor()
void ReporterStateBase::setIsPostprocessor () inline inherited
Sets the special Reporter type to a Postprocessor.
See ReporterData::declareReporterValue.
Definition at line 71 of file ReporterState.h.
{ _reporter_name.setIsPostprocessor(); }
setIsVectorPostprocessor()
void ReporterStateBase::setIsVectorPostprocessor () inline inherited
Sets the special Reporter type to a VectorPostprocessor.
See ReporterData::declareReporterValue.
Definition at line 77 of file ReporterState.h.
{ _reporter_name.setIsVectorPostprocessor(); }
setNotLoaded()
void RestartableDataValue::setNotLoaded (const SetNotLoadedKey) inline inherited
Sets that this restartable value has been loaded.
Definition at line 113 of file RestartableData.h.
{ _loaded = false; }
setNotStored()
void RestartableDataValue::setNotStored (const SetNotStoredKey) inline inherited
Sets that this restartable value has been loaded.
Definition at line 136 of file RestartableData.h.
{ _stored = false; }
store() [1/2]
void RestartableDataValue::store (nlohmann::json & json, const StoreJSONParams & params = StoreJSONParams{}) const inherited
Stores this restartable data in the JSON entry json, with the options set by params (optional; defaults to just the type and underlying value)
If the underlying type is not supported for JSON output (if hasStoreJSON() == false), and the parameters have the value output as enabled, this will error.
Definition at line 39 of file RestartableData.C.
{
  if (params.value)
  {
    if (hasStoreJSON())
      storeJSONValue(json["value"]);
    else
      mooseError("Failed to output restartable data '",
                 name(),
                 "' as JSON because a to_json method is not implemented for the type '",
                 type(),
                 "'");
  }
  if (params.type)
    json["type"] = type();
  if (params.name)
    json["name"] = name();
  if (params.declared)
    json["declared"] = declared();
  if (params.loaded)
    json["loaded"] = loaded();
  if (params.stored)
    json["stored"] = stored();
  if (params.has_context)
    json["has_context"] = hasContext();
}
store() [2/2]
void RestartableDataValue::store (std::ostream & stream) inherited
Stores the value into the stream stream and sets it as stored.
Definition at line 25 of file RestartableData.C.
{
  storeInternal(stream);
  _stored = true;
}
stored()
bool RestartableDataValue::stored () const inline inherited
Whether or not this data has been loaded.
This is typically reset on a call to RestartableDataWriter::write()
Definition at line 121 of file RestartableData.h.
{ return _stored; }
Referenced by RestartableDataValue::store().
storeInternal()
template<typename T > void ReporterState< T >::storeInternal (std::ostream & stream) final override virtual
Loads and stores the data from/to a stream for restart.
This is a special version that handles the fact that the calls declare/getReporterValue occur within the constructor of objects. As such, the storage list already contains data and the references to this data must remain valid.
The default dataLoad assumes the list being populated is empty and simply uses push_back. Therefore, this function loads the data directly into the container to avoid this problem and unnecessary copies.
The default dataStore is very similar, but to ensure consistency (because we're re-defining the load), we implement it again here.
Reimplemented from RestartableData< std::list< T > >.
Definition at line 202 of file ReporterState.h.
{
  // Store the container size
  std::size_t size = this->get().size();
  dataStore(stream, size, nullptr);
  // Store each entry of the list directly into the storage
  for (auto & val : this->set())
    storeHelper(stream, val, nullptr);
}
storeJSONValue()
void RestartableData< std::list< T > >::storeJSONValue (nlohmann::json & json) const inline final override protected virtual inherited
Internal method for storing the underlying JSON value.
Implements RestartableDataValue.
Definition at line 269 of file RestartableData.h.
{
  if constexpr (RestartableData<T>::has_store_json)
    nlohmann::to_json(json, get());
  else
    mooseAssert(false, "Should not be called");
}
type()
std::string RestartableData< std::list< T > >::type inline final override virtual inherited
String identifying the type of parameter stored.
Implements RestartableDataValue.
Definition at line 252 of file RestartableData.h.
{
  return MooseUtils::prettyCppType<T>();
}
typeId()
virtual const std::type_info & RestartableData< std::list< T > >::typeId () const inline final override virtual inherited
The type ID of the underlying data.
Implements RestartableDataValue.
Definition at line 254 of file RestartableData.h.
{ return typeid(T); }
value() [1/2]
template<typename T > T & ReporterState< T >::value (const std::size_t time_index = 0)
Return a reference to the current value or one of the old values.
The time_index of 0 returns the current value, 1 returns old, 2 returns older, etc.
Definition at line 160 of file ReporterState.h.
{
  // Initialize the data; the first entry is the "current" data
  if (this->get().empty())
    this->set().resize(1);
  // Initialize old, older, ... data
  if (this->get().size() <= time_index)
    this->set().resize(time_index + 1, this->get().back());
  return *(std::next(this->set().begin(), time_index));
}
Referenced by ReporterVectorContext< T >::resize().
value() [2/2]
template<typename T > const T & ReporterState< T >::value (const std::size_t time_index = 0) const
Definition at line 175 of file ReporterState.h.
{
  if (this->get().size() <= time_index)
    mooseError("The desired time index ",
               time_index,
               " does not exists for the '",
               getReporterName(),
               "' Reporter value, which contains ",
               this->get().size(),
               " old value(s). The getReporterValue method must be called with the desired time "
               "index to be able to access data.");
  return *(std::next(this->get().begin(), time_index));
}
valueType()
template<typename T > std::string ReporterState< T >::valueType () const inline final override virtual
Returns
The type associated with this state
Implements ReporterStateBase.
Definition at line 130 of file ReporterState.h.
{ return MooseUtils::prettyCppType<T>(); }
Member Data Documentation
_consumers
std::set<std::pair<ReporterMode, const MooseObject *> > ReporterStateBase::_consumers private inherited
The consumers for this state; we store the MooseObject for detailed error reporting.
Definition at line 84 of file ReporterState.h.
Referenced by ReporterStateBase::addConsumer(), and ReporterStateBase::getConsumers().
_context
void* const RestartableDataValue::_context protected inherited
A context pointer for helping with load and store.
Definition at line 197 of file RestartableData.h.
Referenced by RestartableDataValue::context(), and RestartableDataValue::hasContext().
_declared
bool RestartableDataValue::_declared private inherited
Whether or not this data has been declared (true) or only retreived (false)
Definition at line 201 of file RestartableData.h.
Referenced by RestartableDataValue::declared(), and RestartableDataValue::setDeclared().
_loaded
bool RestartableDataValue::_loaded private inherited
Whether or not this has value has been loaded.
Definition at line 204 of file RestartableData.h.
Referenced by RestartableDataValue::load(), RestartableDataValue::loaded(), and RestartableDataValue::setNotLoaded().
_name
const std::string RestartableDataValue::_name protected inherited
The full (unique) name of this particular piece of data.
Definition at line 194 of file RestartableData.h.
Referenced by RestartableDataValue::name().
_reporter_name
ReporterName ReporterStateBase::_reporter_name private inherited
Name of data that state is associated.
Definition at line 81 of file ReporterState.h.
Referenced by ReporterStateBase::getReporterName(), ReporterStateBase::setIsPostprocessor(), and ReporterStateBase::setIsVectorPostprocessor().
_stored
bool RestartableDataValue::_stored private inherited
Whether or not this has value has been stored.
Definition at line 207 of file RestartableData.h.
Referenced by RestartableDataValue::setNotStored(), RestartableDataValue::store(), and RestartableDataValue::stored().
_value
std::unique_ptr<std::list< T > > RestartableData< std::list< T > >::_value private inherited
Stored value.
Definition at line 273 of file RestartableData.h.
has_store_json
constexpr bool RestartableData< std::list< T > >::has_store_json static constexpr inherited
Whether or not this type has a JSON store method implemented.
Definition at line 219 of file RestartableData.h.
The documentation for this class was generated from the following file:
moose/framework/include/reporters/ReporterState.h