Zapdos: MooseVariableConstMonomial Class Reference
MooseVariableConstMonomial Class Reference
#include <MooseVariableConstMonomial.h>
Public Types
using OutputGradient = typename MooseVariableField< Real >::OutputGradient
using OutputSecond = typename MooseVariableField< Real >::OutputSecond
using OutputDivergence = typename MooseVariableField< Real >::OutputDivergence
using FieldVariableValue = typename MooseVariableField< Real >::FieldVariableValue
using FieldVariableGradient = typename MooseVariableField< Real >::FieldVariableGradient
using FieldVariableSecond = typename MooseVariableField< Real >::FieldVariableSecond
using FieldVariableCurl = typename MooseVariableField< Real >::FieldVariableCurl
using FieldVariableDivergence = typename MooseVariableField< Real >::FieldVariableDivergence
using OutputShape = typename MooseVariableField< Real >::OutputShape
using OutputShapeGradient = typename MooseVariableField< Real >::OutputShapeGradient
using OutputShapeSecond = typename MooseVariableField< Real >::OutputShapeSecond
using OutputShapeDivergence = typename MooseVariableField< Real >::OutputShapeDivergence
using FieldVariablePhiValue = typename MooseVariableField< Real >::FieldVariablePhiValue
using FieldVariablePhiGradient = typename MooseVariableField< Real >::FieldVariablePhiGradient
using FieldVariablePhiSecond = typename MooseVariableField< Real >::FieldVariablePhiSecond
using FieldVariablePhiCurl = typename MooseVariableField< Real >::FieldVariablePhiCurl
using FieldVariablePhiDivergence = typename MooseVariableField< Real >::FieldVariablePhiDivergence
using FieldVariableTestValue = typename MooseVariableField< Real >::FieldVariableTestValue
using FieldVariableTestGradient = typename MooseVariableField< Real >::FieldVariableTestGradient
using FieldVariableTestSecond = typename MooseVariableField< Real >::FieldVariableTestSecond
using FieldVariableTestCurl = typename MooseVariableField< Real >::FieldVariableTestCurl
using FieldVariableTestDivergence = typename MooseVariableField< Real >::FieldVariableTestDivergence
using OutputData = typename MooseVariableField< Real >::OutputData
using DoFValue = typename MooseVariableField< Real >::DoFValue
using FunctorArg = typename Moose::ADType< Real >::type
using FunctorType = FunctorBase< Moose::ADType< OutputType >::type >
using FunctorReturnType = Moose::ADType< OutputType >::type
using ValueType = Moose::ADType< OutputType >::type
using GradientType = typename MetaPhysicL::ReplaceAlgebraicType< Moose::ADType< OutputType >::type, typename TensorTools::IncrementRank< typename MetaPhysicL::ValueType< Moose::ADType< OutputType >::type >::type >::type >::type
This rigmarole makes it so that a user can create functors that return containers (std::vector, std::array).
using DotType = ValueType
Public Member Functions
MooseVariableConstMonomial (const InputParameters &parameters)
virtual void computeElemValues () override
Actually compute variable values from the solution vectors.
virtual void computeElemValuesFace () override
Compute values at facial quadrature points.
virtual void computeNeighborValuesFace () override
Compute values at facial quadrature points for the neighbor.
virtual void computeNeighborValues () override
Compute values at quadrature points for the neighbor.
void clearDofIndices () override
Clear out the dof indices.
void prepare () override
Prepare the elemental degrees of freedom.
void prepareNeighbor () override
Prepare the neighbor element degrees of freedom.
void prepareLowerD () override
Prepare a lower dimensional element's degrees of freedom.
virtual void prepareIC () override
Prepare the initial condition.
void prepareAux () override
void reinitNode () override
void reinitAux () override
void reinitAuxNeighbor () override
void reinitNodes (const std::vector< dof_id_type > &nodes) override
void reinitNodesNeighbor (const std::vector< dof_id_type > &nodes) override
bool usesPhi () const
Whether or not this variable is actually using the shape function value.
bool usesGradPhi () const
Whether or not this variable is actually using the shape function gradient.
bool usesSecondPhi () const
Whether or not this variable is computing any second derivatives.
bool usesSecondPhiNeighbor () const override final
Whether or not this variable is actually using the shape function second derivative on a neighbor.
bool computingSecond () const override final
Whether or not this variable is computing any second derivatives.
bool computingCurl () const override final
Whether or not this variable is computing the curl.
bool computingDiv () const override final
Whether or not this variable is computing the divergence.
bool isNodal () const override
Is this variable nodal.
bool hasDoFsOnNodes () const override
Does this variable have DoFs on nodes.
FEContinuity getContinuity () const override
Return the continuity of this variable.
Moose::VarFieldType fieldType () const override
Filed type of this variable.
bool isArray () const override
bool isVector () const override
const Node *const & node () const
const dof_id_type & nodalDofIndex () const override
virtual bool isNodalDefined () const override
Is this variable defined at nodes.
const Node *const & nodeNeighbor () const
const dof_id_type & nodalDofIndexNeighbor () const override
bool isNodalNeighborDefined () const
const Elem *const & currentElem () const override
Current element this variable is evaluated at.
const unsigned int & currentSide () const
Current side this variable is being evaluated on.
const Elem *const & neighbor () const
Current neighboring element.
virtual void getDofIndices (const Elem *elem, std::vector< dof_id_type > &dof_indices) const override
const std::vector< dof_id_type > & dofIndices () const final
Get local DoF indices.
unsigned int numberOfDofs () const final
Get the number of local DoFs.
const std::vector< dof_id_type > & dofIndicesNeighbor () const final
Get neighbor DOF indices for currently selected element.
const std::vector< dof_id_type > & dofIndicesLower () const final
Get dof indices for the current lower dimensional element (this is meaningful when performing mortar FEM)
void clearAllDofIndices () final
unsigned int numberOfDofsNeighbor () override
const FieldVariablePhiValue & phi () const override
Return the variable's elemental shape functions.
const FieldVariablePhiGradient & gradPhi () const override final
Return the gradients of the variable's elemental shape functions.
const MappedArrayVariablePhiGradient & arrayGradPhi () const
const FieldVariablePhiSecond & secondPhi () const override final
Return the rank-2 tensor of second derivatives of the variable's elemental shape functions.
const FieldVariablePhiCurl & curlPhi () const override final
Curl of the shape functions.
const FieldVariablePhiDivergence & divPhi () const override final
Divergence of the shape functions.
const FieldVariablePhiValue & phiFace () const override final
Return the variable's shape functions on an element face.
const FieldVariablePhiGradient & gradPhiFace () const override final
Return the gradients of the variable's shape functions on an element face.
const MappedArrayVariablePhiGradient & arrayGradPhiFace () const
const FieldVariablePhiSecond & secondPhiFace () const override final
Return the rank-2 tensor of second derivatives of the variable's shape functions on an element face.
const FieldVariablePhiCurl & curlPhiFace () const
const FieldVariablePhiDivergence & divPhiFace () const
const FieldVariablePhiValue & phiNeighbor () const override final
Return the variable's shape functions on a neighboring element.
const FieldVariablePhiGradient & gradPhiNeighbor () const override final
Return the gradients of the variable's shape functions on a neighboring element.
const MappedArrayVariablePhiGradient & arrayGradPhiNeighbor () const
const FieldVariablePhiSecond & secondPhiNeighbor () const override final
Return the rank-2 tensor of second derivatives of the variable's shape functions on a neighboring element.
const FieldVariablePhiCurl & curlPhiNeighbor () const
const FieldVariablePhiDivergence & divPhiNeighbor () const
const FieldVariablePhiValue & phiFaceNeighbor () const override final
Return the variable's shape functions on a neighboring element face.
const FieldVariablePhiGradient & gradPhiFaceNeighbor () const override final
Return the gradients of the variable's shape functions on a neighboring element face.
const MappedArrayVariablePhiGradient & arrayGradPhiFaceNeighbor () const
const FieldVariablePhiSecond & secondPhiFaceNeighbor () const override final
Return the rank-2 tensor of second derivatives of the variable's shape functions on a neighboring element face.
const FieldVariablePhiCurl & curlPhiFaceNeighbor () const
const FieldVariablePhiDivergence & divPhiFaceNeighbor () const
virtual const FieldVariablePhiValue & phiLower () const override
Return the variable's shape functions on a lower-dimensional element.
const FieldVariablePhiGradient & gradPhiLower () const
const ADTemplateVariableTestGradient< OutputShape > & adGradPhi () const
const ADTemplateVariableTestGradient< OutputShape > & adGradPhiFace () const
const ADTemplateVariableTestGradient< OutputShape > & adGradPhiFaceNeighbor () const
const FieldVariableValue & increment () const
const FieldVariableValue & vectorTagValue (TagID tag) const override
tag values getters
const FieldVariableGradient & vectorTagGradient (TagID tag) const
const DoFValue & vectorTagDofValue (TagID tag) const override
const FieldVariableValue & matrixTagValue (TagID tag) const
const FieldVariableValue & sln () const override
element solutions
const FieldVariableValue & slnOld () const override
const FieldVariableValue & slnOlder () const override
const FieldVariableValue & slnPreviousNL () const
const FieldVariableGradient & gradSln () const override
element gradients
const FieldVariableGradient & gradSlnOld () const override
const FieldVariableGradient & gradSlnOlder () const
const FieldVariableGradient & gradSlnPreviousNL () const
const FieldVariableGradient & gradSlnDot () const
element gradient dots
const FieldVariableGradient & gradSlnDotDot () const
const FieldVariableSecond & secondSln () const
element seconds
const FieldVariableSecond & secondSlnOld () const
const FieldVariableSecond & secondSlnOlder () const
const FieldVariableSecond & secondSlnPreviousNL () const
const FieldVariableCurl & curlSln () const
element curls
const FieldVariableCurl & curlSlnOld () const
const FieldVariableCurl & curlSlnOlder () const
const FieldVariableDivergence & divSln () const
element divergence
const FieldVariableDivergence & divSlnOld () const
const FieldVariableDivergence & divSlnOlder () const
const ADTemplateVariableValue< Real > & adSln () const override
AD.
const ADTemplateVariableGradient< Real > & adGradSln () const override
AD grad solution getter.
const ADTemplateVariableSecond< Real > & adSecondSln () const override
AD second solution getter.
const ADTemplateVariableValue< Real > & adUDot () const override
AD time derivative getter.
const ADTemplateVariableValue< Real > & adUDotDot () const override
AD second time derivative getter.
const ADTemplateVariableGradient< Real > & adGradSlnDot () const override
AD grad of time derivative solution getter.
const ADTemplateVariableValue< Real > & adSlnNeighbor () const override
neighbor AD
const ADTemplateVariableGradient< Real > & adGradSlnNeighbor () const override
AD grad neighbor solution getter.
const ADTemplateVariableSecond< Real > & adSecondSlnNeighbor () const override
AD second neighbor solution getter.
const ADTemplateVariableValue< Real > & adUDotNeighbor () const override
AD neighbor time derivative getter.
const ADTemplateVariableValue< Real > & adUDotDotNeighbor () const override
AD neighbor second time derivative getter.
const ADTemplateVariableGradient< Real > & adGradSlnNeighborDot () const override
AD grad of time derivative neighbor solution getter.
const FieldVariableValue & uDot () const
element dots
const FieldVariableValue & uDotDot () const
const FieldVariableValue & uDotOld () const
const FieldVariableValue & uDotDotOld () const
const VariableValue & duDotDu () const
const VariableValue & duDotDotDu () const
const FieldVariableValue & slnNeighbor () const override
neighbor solutions
const FieldVariableValue & slnOldNeighbor () const override
const FieldVariableValue & slnOlderNeighbor () const
const FieldVariableValue & slnPreviousNLNeighbor () const
const FieldVariableGradient & gradSlnNeighbor () const override
neighbor solution gradients
const FieldVariableGradient & gradSlnOldNeighbor () const override
const FieldVariableGradient & gradSlnOlderNeighbor () const
const FieldVariableGradient & gradSlnPreviousNLNeighbor () const
const FieldVariableGradient & gradSlnNeighborDot () const
neighbor grad dots
const FieldVariableGradient & gradSlnNeighborDotDot () const
const FieldVariableSecond & secondSlnNeighbor () const
neighbor solution seconds
const FieldVariableSecond & secondSlnOldNeighbor () const
const FieldVariableSecond & secondSlnOlderNeighbor () const
const FieldVariableSecond & secondSlnPreviousNLNeighbor () const
const FieldVariableCurl & curlSlnNeighbor () const
neighbor solution curls
const FieldVariableCurl & curlSlnOldNeighbor () const
const FieldVariableCurl & curlSlnOlderNeighbor () const
const FieldVariableDivergence & divSlnNeighbor () const
neighbor solution divergence
const FieldVariableDivergence & divSlnOldNeighbor () const
const FieldVariableDivergence & divSlnOlderNeighbor () const
const FieldVariableValue & uDotNeighbor () const
neighbor dots
const FieldVariableValue & uDotDotNeighbor () const
const FieldVariableValue & uDotOldNeighbor () const
const FieldVariableValue & uDotDotOldNeighbor () const
const VariableValue & duDotDuNeighbor () const
const VariableValue & duDotDotDuNeighbor () const
const ADTemplateVariableValue< Real > & adSlnLower () const
lower-d element solution
const FieldVariableValue & slnLower () const
const FieldVariableValue & slnLowerOld () const
virtual void computeLowerDValues () override
compute values at quadrature points on the lower dimensional element
virtual void setNodalValue (const Real &value, unsigned int idx=0) override
virtual void setDofValue (const OutputData &value, unsigned int index) override
Degree of freedom value setters.
void setDofValues (const DenseVector< OutputData > &values) override
Set local DOF values and evaluate the values on quadrature points.
void insertNodalValue (NumericVector< Number > &residual, const OutputData &v)
Write a nodal value to the passed-in solution vector.
OutputData getNodalValue (const Node &node) const
Get the value of this variable at given node.
OutputData getNodalValueOld (const Node &node) const
Get the old value of this variable at given node.
OutputData getNodalValueOlder (const Node &node) const
Get the t-2 value of this variable at given node.
OutputData getElementalValue (const Elem *elem, unsigned int idx=0) const
Get the current value of this variable on an element.
OutputData getElementalValueOld (const Elem *elem, unsigned int idx=0) const
Get the old value of this variable on an element.
OutputData getElementalValueOlder (const Elem *elem, unsigned int idx=0) const
Get the older value of this variable on an element.
void insert (NumericVector< Number > &residual) override
Set the current local DOF values to the input vector.
void add (NumericVector< Number > &residual) override
Add the current local DOF values to the input vector.
void addSolution (const DenseVector< Number > &v)
Add passed in local DOF values onto the current solution.
void addSolutionNeighbor (const DenseVector< Number > &v)
Add passed in local neighbor DOF values onto the current solution.
const DoFValue & dofValue () const
const DoFValue & dofValues () const override
dof values getters
const DoFValue & dofValuesOld () const override
const DoFValue & dofValuesOlder () const override
const DoFValue & dofValuesPreviousNL () const override
const DoFValue & dofValuesNeighbor () const override
const DoFValue & dofValuesOldNeighbor () const override
const DoFValue & dofValuesOlderNeighbor () const override
const DoFValue & dofValuesPreviousNLNeighbor () const override
const DoFValue & dofValuesDot () const override
const DoFValue & dofValuesDotNeighbor () const override
const DoFValue & dofValuesDotNeighborResidual () const
const DoFValue & dofValuesDotOld () const override
const DoFValue & dofValuesDotOldNeighbor () const override
const DoFValue & dofValuesDotDot () const override
const DoFValue & dofValuesDotDotNeighbor () const override
const DoFValue & dofValuesDotDotNeighborResidual () const
const DoFValue & dofValuesDotDotOld () const override
const DoFValue & dofValuesDotDotOldNeighbor () const override
const MooseArray< Number > & dofValuesDuDotDu () const override
const MooseArray< Number > & dofValuesDuDotDuNeighbor () const override
const MooseArray< Number > & dofValuesDuDotDotDu () const override
const MooseArray< Number > & dofValuesDuDotDotDuNeighbor () const override
const MooseArray< ADReal > & adDofValues () const override
Return the AD dof values.
const MooseArray< ADReal > & adDofValuesNeighbor () const override
Return the AD neignbor dof values.
void computeIncrementAtQps (const NumericVector< Number > &increment_vec)
Compute and store incremental change in solution at QPs based on increment_vec.
void computeIncrementAtNode (const NumericVector< Number > &increment_vec)
Compute and store incremental change at the current node based on increment_vec.
Real getValue (const Elem *elem, const std::vector< std::vector< OutputShape > > &phi) const
Compute the variable value at a point on an element.
OutputTools< Real >::OutputGradient getGradient (const Elem *elem, const std::vector< std::vector< typename OutputTools< Real >::OutputShapeGradient > > &grad_phi) const
Compute the variable gradient value at a point on an element.
virtual std::size_t phiSize () const final
Return phi size.
virtual std::size_t phiFaceSize () const final
Return phiFace size.
virtual std::size_t phiNeighborSize () const final
Return phiNeighbor size.
virtual std::size_t phiFaceNeighborSize () const final
Return phiFaceNeighbor size.
std::size_t phiLowerSize () const final
Return the number of shape functions on the lower dimensional element for this variable.
const Real & nodalValue () const
Methods for retrieving values of variables at the nodes.
const Real & nodalValueOld () const
const Real & nodalValueOlder () const
const Real & nodalValuePreviousNL () const
const Real & nodalValueDot () const
const Real & nodalValueDotDot () const
const Real & nodalValueDotOld () const
const Real & nodalValueDotDotOld () const
const Real & nodalValueDuDotDu () const
const Real & nodalValueDuDotDotDu () const
const Real & nodalValueNeighbor () const
const Real & nodalValueOldNeighbor () const
const Real & nodalValueOlderNeighbor () const
const Real & nodalValuePreviousNLNeighbor () const
const Real & nodalValueDotNeighbor () const
const Real & nodalValueDotNeighborResidual () const
const Real & nodalValueDotDotNeighbor () const
const Real & nodalValueDotDotNeighborResidual () const
const Real & nodalValueDotOldNeighbor () const
const Real & nodalValueDotDotOldNeighbor () const
const Real & nodalValueDuDotDuNeighbor () const
const Real & nodalValueDuDotDotDuNeighbor () const
const MooseArray< Real > & nodalValueArray () const override
Methods for retrieving values of variables at the nodes in a MooseArray for AuxKernelBase.
const MooseArray< Real > & nodalValueOldArray () const override
const MooseArray< Real > & nodalValueOlderArray () const override
const DoFValue & nodalVectorTagValue (TagID tag) const override
const DoFValue & nodalMatrixTagValue (TagID tag) const
const Moose::ADType< Real >::type & adNodalValue () const
virtual void computeNodalValues () override
Compute nodal values of this variable.
virtual void computeNodalNeighborValues () override
Compute nodal values of this variable in the neighbor.
unsigned int oldestSolutionStateRequested () const override final
The oldest solution state that is requested for this variable (0 = current, 1 = old, 2 = older, etc).
void setActiveTags (const std::set< TagID > &vtags) override
Set the active vector tags.
virtual void meshChanged () override
Called on this object when the mesh changes.
virtual void residualSetup () override
virtual void jacobianSetup () override
bool usesPhiNeighbor () const
Whether or not this variable is actually using the shape function value.
bool usesGradPhiNeighbor () const
Whether or not this variable is actually using the shape function gradient.
bool hasBlocks (const SubdomainName &name) const
Test if the supplied block name is valid for this object.
bool hasBlocks (const std::vector< SubdomainName > &names) const
Test if the supplied vector of block names are valid for this object.
bool hasBlocks (const std::vector< SubdomainID > &ids) const
Test if the supplied vector block ids are valid for this object.
bool hasBlocks (const std::set< SubdomainID > &ids) const
Test if the supplied set of block ids are valid for this object.
std::string componentName (const unsigned int comp) const
Get the variable name of a component in libMesh.
virtual bool isFV () const
const std::set< SubdomainID > & activeSubdomains () const
The subdomains the variable is active on.
bool activeOnSubdomain (SubdomainID subdomain) const
Is the variable active on the subdomain?
bool activeOnSubdomains (const std::set< SubdomainID > &subdomains) const
Is the variable active on the subdomains?
virtual void computeFaceValues (const FaceInfo &)
Compute values at face quadrature points for the element+neighbor (both sides of the face).
unsigned int number () const
Get variable number coming from libMesh.
const FEType & feType () const
Get the type of finite element object.
SystemBase & sys ()
Get the system this variable is part of.
const SystemBase & sys () const
Get the system this variable is part of.
const std::string & name () const override
Get the variable name.
bool useDual () const
Get dual mortar option.
const std::vector< dof_id_type > & allDofIndices () const
Get all global dofindices for the variable.
unsigned int totalVarDofs ()
Moose::VarKindType kind () const
Kind of the variable (Nonlinear, Auxiliary, ...)
void scalingFactor (Real factor)
Set the scaling factor for this variable.
void scalingFactor (const std::vector< Real > &factor)
Real scalingFactor () const
Get the scaling factor for this variable.
const std::vector< Real > & arrayScalingFactor () const
Order order () const
Get the order of this variable Note: Order enum can be implicitly converted to unsigned int.
unsigned int count () const
Get the number of components Note: For standard and vector variables, the number is one.
const DofMap & dofMap () const
The DofMap associated with the system this variable is in.
std::vector< dof_id_type > componentDofIndices (const std::vector< dof_id_type > &dof_indices, unsigned int component) const
Obtain DoF indices of a component with the indices of the 0th component.
bool eigen () const
Whether or not this variable operates on an eigen kernel.
void eigen (bool eigen)
Mark this variable as an eigen var or non-eigen var.
void initialSetup () override
Gets called at the beginning of the simulation before this object is asked to do its job.
virtual bool enabled () const
Return the enabled status of the object.
MooseApp & getMooseApp () const
Get the MooseApp this class is associated with.
const std::string & type () const
Get the type of this class.
std::string typeAndName () const
Get the class's combined type and name; useful in error handling.
MooseObjectParameterName uniqueParameterName (const std::string &parameter_name) const
The unique parameter name of a valid parameter of this object for accessing parameter controls.
const InputParameters & parameters () const
Get the parameters of the object.
MooseObjectName uniqueName () const
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
template<typename T >
const T & getParam (const std::string &name) const
Retrieve a parameter for the object.
template<typename T1 , typename T2 >
std::vector< std::pair< T1, T2 > > getParam (const std::string &param1, const std::string &param2) const
Retrieve two parameters and provide pair of parameters for the object.
template<typename T >
const T & getRenamedParam (const std::string &old_name, const std::string &new_name) const
Retrieve a renamed parameter for the object.
template<typename T >
T getCheckedPointerParam (const std::string &name, const std::string &error_string="") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
bool isParamValid (const std::string &name) const
Test if the supplied parameter is valid.
bool isParamSetByUser (const std::string &nm) const
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
template<typename... Args>
void paramError (const std::string &param, Args... args) const
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramWarning (const std::string &param, Args... args) const
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramInfo (const std::string &param, Args... args) const
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
std::string objectErrorPrefix (const std::string &error_type) const
A descriptive prefix for errors for an object.
void connectControllableParams (const std::string &parameter, const std::string &object_type, const std::string &object_name, const std::string &object_parameter) const
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
template<typename... Args>
void mooseError (Args &&... args) const
Emits an error prefixed with object name and type.
template<typename... Args>
void mooseErrorNonPrefixed (Args &&... args) const
Emits an error without the prefixing included in mooseError().
template<typename... Args>
void mooseWarning (Args &&... args) const
Emits a warning prefixed with object name and type.
template<typename... Args>
void mooseWarningNonPrefixed (Args &&... args) const
Emits a warning without the prefixing included in mooseWarning().
template<typename... Args>
void mooseDeprecated (Args &&... args) const
template<typename... Args>
void mooseInfo (Args &&... args) const
std::string errorPrefix (const std::string &error_type) const
A descriptive prefix for errors for this object:
std::string getDataFileName (const std::string &param) const
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
std::string getDataFileNameByName (const std::string &name, const std::string *param=nullptr) const
Returns the path of a data file for a given relative file path.
const std::vector< SubdomainName > & blocks () const
Return the block names for this object.
unsigned int numBlocks () const
Return the number of blocks for this object.
virtual const std::set< SubdomainID > & blockIDs () const
Return the block subdomain ids for this object Note, if this is not block restricted, this function returns all mesh subdomain ids.
unsigned int blocksMaxDimension () const
Return the largest mesh dimension of the elements in the blocks for this object.
bool isBlockSubset (const std::set< SubdomainID > &ids) const
Test if the class block ids are a subset of the supplied objects.
bool isBlockSubset (const std::vector< SubdomainID > &ids) const
Test if the class block ids are a subset of the supplied objects.
template<typename T , bool is_ad = false>
bool hasBlockMaterialProperty (const std::string &prop_name)
Check if a material property is valid for all blocks of this object.
const std::set< SubdomainID > & meshBlockIDs () const
Return all of the SubdomainIDs for the mesh.
virtual bool blockRestricted () const
Returns true if this object has been restricted to a block.
virtual void checkVariable (const MooseVariableFieldBase &variable) const
Helper for checking that the ids for this object are in agreement with the variables on the supplied variable.
void buildOutputHideVariableList (std::set< std::string > variable_names)
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
const std::set< OutputName > & getOutputs ()
Get the list of output objects that this class is restricted.
virtual void subdomainSetup ()
Gets called when the subdomain changes (i.e.
virtual void customSetup (const ExecFlagType &)
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
virtual void customSetup (const ExecFlagType &exec_type) override
const ExecFlagEnum & getExecuteOnEnum () const
Return the execute on MultiMooseEnum for this object.
const MooseFunctorName & functorName () const
Return the functor name.
void setCacheClearanceSchedule (const std::set< ExecFlagType > &clearance_schedule)
Set how often to clear the functor evaluation cache.
virtual bool isExtrapolatedBoundaryFace (const FaceInfo &, const Elem *, const StateArg &) const
Returns whether this (sided) face is an extrapolated boundary face for this functor.
bool isInternalFace (const FaceInfo &) const
Returns true if the face is an internal face.
virtual bool isConstant () const
Returns true if this functor is a constant.
virtual bool hasFaceSide (const FaceInfo &fi, const bool fi_elem_side) const override
Moose::FaceArg checkFace (const Moose::FaceArg &face) const
Examines the incoming face argument.
ValueType operator() (const ElemArg &elem, const StateArg &state) const
Same as their evaluate overloads with the same arguments but allows for caching implementation.
ValueType operator() (const FaceArg &face, const StateArg &state) const
ValueType operator() (const ElemQpArg &qp, const StateArg &state) const
ValueType operator() (const ElemSideQpArg &qp, const StateArg &state) const
ValueType operator() (const ElemPointArg &elem_point, const StateArg &state) const
ValueType operator() (const NodeArg &node, const StateArg &state) const
GradientType gradient (const ElemArg &elem, const StateArg &state) const
Same as their evaluateGradient overloads with the same arguments but allows for caching implementation.
GradientType gradient (const FaceArg &face, const StateArg &state) const
GradientType gradient (const ElemQpArg &qp, const StateArg &state) const
GradientType gradient (const ElemSideQpArg &qp, const StateArg &state) const
GradientType gradient (const ElemPointArg &elem_point, const StateArg &state) const
GradientType gradient (const NodeArg &node, const StateArg &state) const
DotType dot (const ElemArg &elem, const StateArg &state) const
Same as their evaluateDot overloads with the same arguments but allows for caching implementation.
DotType dot (const FaceArg &face, const StateArg &state) const
DotType dot (const ElemQpArg &qp, const StateArg &state) const
DotType dot (const ElemSideQpArg &qp, const StateArg &state) const
DotType dot (const ElemPointArg &elem_point, const StateArg &state) const
DotType dot (const NodeArg &node, const StateArg &state) const
GradientType gradDot (const ElemArg &elem, const StateArg &state) const
Same as their evaluateGradDot overloads with the same arguments but allows for caching implementation.
GradientType gradDot (const FaceArg &face, const StateArg &state) const
GradientType gradDot (const ElemQpArg &qp, const StateArg &state) const
GradientType gradDot (const ElemSideQpArg &qp, const StateArg &state) const
GradientType gradDot (const ElemPointArg &elem_point, const StateArg &state) const
GradientType gradDot (const NodeArg &node, const StateArg &state) const
Static Public Member Functions
static InputParameters validParams ()
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Types
using ElemArg = Moose::ElemArg
using ElemQpArg = Moose::ElemQpArg
using ElemSideQpArg = Moose::ElemSideQpArg
using FaceArg = Moose::FaceArg
using StateArg = Moose::StateArg
using NodeArg = Moose::NodeArg
using ElemPointArg = Moose::ElemPointArg
Protected Member Functions
ValueType faceEvaluate (const FaceArg &, const StateArg &, const std::vector< ValueType > &cache_data) const
A common method that both evaluate(FaceArg) and evaluateDot(FaceArg) can call.
ValueType evaluate (const ElemQpArg &elem_qp, const StateArg &state) const override final
ValueType evaluate (const ElemSideQpArg &elem_side_qp, const StateArg &state) const override final
ValueType evaluate (const ElemArg &, const StateArg &) const override final
Evaluate the functor with a given element.
ValueType evaluate (const ElemPointArg &, const StateArg &) const override final
Evaluate the functor with a given element and point.
ValueType evaluate (const NodeArg &node_arg, const StateArg &state) const override final
ValueType evaluate (const FaceArg &, const StateArg &) const override final
GradientType evaluateGradient (const ElemQpArg &elem_qp, const StateArg &state) const override
GradientType evaluateGradient (const ElemSideQpArg &elem_side_qp, const StateArg &state) const override final
GradientType evaluateGradient (const ElemArg &, const StateArg &) const override final
Evaluate the functor gradient with a given element.
DotType evaluateDot (const ElemQpArg &elem_qp, const StateArg &state) const override final
DotType evaluateDot (const ElemSideQpArg &elem_side_qp, const StateArg &state) const override final
DotType evaluateDot (const ElemArg &, const StateArg &) const override final
Evaluate the functor time derivative with a given element.
DotType evaluateDot (const FaceArg &, const StateArg &) const override final
GradientType evaluateGradDot (const ElemArg &, const StateArg &) const override final
Evaluate the functor gradient-dot with a given element.
bool doDerivatives () const
virtual bool hasBlockMaterialPropertyHelper (const std::string &prop_name)
A helper method to allow the Material object to specialize the behavior of hasBlockMaterialProperty.
void initializeBlockRestrictable (const MooseObject *moose_object)
An initialization routine needed for dual constructors.
Moose::CoordinateSystemType getBlockCoordSystem ()
Check if the blocks this object operates on all have the same coordinate system, and if so return it.
Functor evaluation routines
These methods are all for evaluating functors with different kinds of spatial arguments.
Each of these methods also takes a state argument. For a description of the state argument, please see the StateArg doxygen
virtual GradientType evaluateGradient (const FaceArg &, const StateArg &) const
virtual GradientType evaluateGradient (const ElemPointArg &, const StateArg &) const
Evaluate the functor gradient with a given element and point.
virtual GradientType evaluateGradient (const NodeArg &, const StateArg &) const
virtual DotType evaluateDot (const ElemPointArg &, const StateArg &) const
Evaluate the functor time derivative with a given element and point.
virtual DotType evaluateDot (const NodeArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const FaceArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemQpArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemSideQpArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemPointArg &, const StateArg &) const
Evaluate the functor gradient-dot with a given element and point.
virtual GradientType evaluateGradDot (const NodeArg &, const StateArg &) const
Protected Attributes
usingMooseVariableFieldMembers
std::unique_ptr< MooseVariableData< Real > > _element_data
Holder for all the data associated with the "main" element.
std::unique_ptr< MooseVariableData< Real > > _neighbor_data
Holder for all the data associated with the neighbor element.
std::unique_ptr< MooseVariableData< Real > > _lower_data
Holder for all the data associated with the lower dimeensional element.
SystemBase & _sys
System this variable is part of.
FEType _fe_type
The FEType associated with this variable.
unsigned int _var_num
variable number (from libMesh)
unsigned int _index
variable number within MOOSE
bool _is_eigen
Whether or not this variable operates on eigen kernels.
Moose::VarKindType _var_kind
Variable type (see MooseTypes.h)
SubProblem & _subproblem
Problem this variable is part of.
const Variable & _variable
libMesh variable object for this variable
Assembly & _assembly
Assembly data.
const DofMap & _dof_map
DOF map.
std::vector< dof_id_type > _dof_indices
DOF indices.
MooseMesh & _mesh
mesh the variable is active in
THREAD_ID _tid
Thread ID.
const unsigned int _count
Number of variables in the array.
std::vector< Real > _scaling_factor
scaling factor for this variable
std::string _var_name
Variable name.
bool _use_dual
If dual mortar approach is used.
const bool _is_array
Whether this is an array variable.
const bool & _enabled
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
MooseApp & _app
The MOOSE application this is associated with.
const std::string & _type
The type of this class.
const std::string & _name
The name of this class, reference to value stored in InputParameters.
const InputParameters & _pars
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Factory & _factory
The Factory associated with the MooseApp.
ActionFactory & _action_factory
Builds Actions.
const MaterialData * _blk_material_data
Pointer to the MaterialData class for this object.
const ExecFlagEnum & _execute_enum
Execute settings for this object.
const ExecFlagType & _current_execute_flag
Reference to FEProblemBase.
FEProblemBase & _mci_feproblem
Reference to FEProblemBase instance.
Private Member Functions
void computeSolution (const Elem *elem, unsigned int n_qp, const StateArg &state, const Shapes &phi, Solution &local_soln, const GradShapes &grad_phi, GradSolution &grad_local_soln, Solution &dot_local_soln, GradSolution &grad_dot_local_soln) const
Compute the solution, gradient, time derivative, and gradient of the time derivative with provided shape functions.
void evaluateOnElement (const ElemQpArg &elem_qp, const StateArg &state, bool cache_eligible) const
Evaluate solution and gradient for the elem_qp argument.
void evaluateOnElementSide (const ElemSideQpArg &elem_side_qp, const StateArg &state, bool cache_eligible) const
Evaluate solution and gradient for the elem_side_qp argument.
template<typename... Args>
std::string paramErrorMsg (const std::string &param, Args... args) const
void clearCacheData ()
clear cache data
ValueType queryQpCache (unsigned int qp, const QBase &qrule, std::vector< std::pair< bool, Moose::ADType< OutputType >::type > > &qp_cache_data, const SpaceArg &space, const StateArg &state) const
check a qp cache and if invalid then evaluate
ValueType queryFVArgCache (std::map< SpaceArg, ValueType > &cache_data, const SpaceArg &space) const
check a finite volume spatial argument cache and if invalid then evaluate
Private Attributes
const Elem * _current_elem_qp_functor_elem
Keep track of the current elem-qp functor element in order to enable local caching (e.g.
std::vector< ValueType > _current_elem_qp_functor_sln
The values of the solution for the _current_elem_qp_functor_elem.
std::vector< GradientType > _current_elem_qp_functor_gradient
The values of the gradient for the _current_elem_qp_functor_elem.
std::vector< DotType > _current_elem_qp_functor_dot
The values of the time derivative for the _current_elem_qp_functor_elem.
std::vector< GradientType > _current_elem_qp_functor_grad_dot
The values of the gradient of the time derivative for the _current_elem_qp_functor_elem.
std::pair< const Elem *, unsigned int > _current_elem_side_qp_functor_elem_side
Keep track of the current elem-side-qp functor element and side in order to enable local caching (e.g.
std::vector< ValueType > _current_elem_side_qp_functor_sln
The values of the solution for the _current_elem_side_qp_functor_elem_side.
std::vector< GradientType > _current_elem_side_qp_functor_gradient
The values of the gradient for the _current_elem_side_qp_functor_elem_side.
std::vector< DotType > _current_elem_side_qp_functor_dot
The values of the time derivative for the _current_elem_side_qp_functor_elem_side.
std::vector< GradientType > _current_elem_side_qp_functor_grad_dot
The values of the gradient of the time derivative for the _current_elem_side_qp_functor_elem_side.
const MooseBase *const _moose_base
The MooseBase object that inherits this class.
const MooseObject & _parent
std::set< SubdomainID > _blk_ids
Set of block ids supplied by the user via the input file (for error checking)
std::vector< SubdomainID > _vec_ids
Vector of block ids supplied by the user via the input file (for error reporting)
std::vector< SubdomainName > _blocks
Vector the block names supplied by the user via the input file.
const bool _blk_dual_restrictable
Flag for allowing dual restriction.
FEProblemBase * _blk_feproblem
Pointer to FEProblemBase.
MooseMesh * _blk_mesh
Pointer to Mesh.
const std::set< BoundaryID > _empty_boundary_ids
An empty set for referencing when boundary_ids is not included.
const std::set< BoundaryID > & _boundary_ids
Reference to the boundary_ids, defaults to an empty set if not provided.
THREAD_ID _blk_tid
Thread id for this object.
const std::string & _blk_name
Name of the object.
unsigned int _blk_dim
Largest mesh dimension of the elements in the blocks for this object.
MooseApp & _oi_moose_app
Reference the the MooseApp; neede for access to the OutputWarehouse.
OutputWarehouse & _oi_output_warehouse
Reference to the OutputWarehouse for populating the Output object hide lists.
std::set< OutputName > _oi_outputs
The set of Output object names listed in the 'outputs' parameter.
ExecFlagEnum _empty_execute_enum
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
std::set< ExecFlagType > _clearance_schedule
How often to clear the material property cache.
dof_id_type _current_qp_map_key
Current key for qp map cache.
std::vector< std::pair< bool, ValueType > > * _current_qp_map_value
Current value for qp map cache.
std::unordered_map< dof_id_type, std::vector< std::pair< bool, ValueType > > > _qp_to_value
Cached element quadrature point functor property evaluations.
dof_id_type _current_side_qp_map_key
Current key for side-qp map cache.
std::vector< std::vector< std::pair< bool, ValueType > > > * _current_side_qp_map_value
Current value for side-qp map cache.
std::unordered_map< dof_id_type, std::vector< std::vector< std::pair< bool, ValueType > > > > _side_qp_to_value
Cached element quadrature point functor property evaluations.
std::map< ElemArg, ValueType > _elem_arg_to_value
Map from element arguments to their cached evaluations.
std::map< FaceArg, ValueType > _face_arg_to_value
Map from face arguments to their cached evaluations.
std::map< NodeArg, ValueType > _node_arg_to_value
Map from nodal arguments to their cached evaluations.
MooseFunctorName _functor_name
name of the functor
virtual void timestepSetup () override
bool hasBlocks (const SubdomainID id) const override
Returns whether the functor is defined on this block.
const TimeIntegrator *const _time_integrator
the time integrator used for computing time derivatives
ADReal _ad_real_dummy = 0
A dummy ADReal variable.
const NumericVector< Number > & getSolution (const Moose::StateArg &state) const
Get the solution corresponding to the provided state.
Detailed Description
Definition at line 14 of file MooseVariableConstMonomial.h.
Member Typedef Documentation
DoFValue
using MooseVariableFE< Real >::DoFValue = typename MooseVariableField<Real >::DoFValue inherited
Definition at line 81 of file MooseVariableFE.h.
DotType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::DotType = ValueType inherited
Definition at line 67 of file MooseFunctor.h.
ElemArg
using MooseVariableFE< Real >::ElemArg = Moose::ElemArg protected inherited
Definition at line 724 of file MooseVariableFE.h.
ElemPointArg
using MooseVariableFE< Real >::ElemPointArg = Moose::ElemPointArg protected inherited
Definition at line 730 of file MooseVariableFE.h.
ElemQpArg
using MooseVariableFE< Real >::ElemQpArg = Moose::ElemQpArg protected inherited
Definition at line 725 of file MooseVariableFE.h.
ElemSideQpArg
using MooseVariableFE< Real >::ElemSideQpArg = Moose::ElemSideQpArg protected inherited
Definition at line 726 of file MooseVariableFE.h.
FaceArg
using MooseVariableFE< Real >::FaceArg = Moose::FaceArg protected inherited
Definition at line 727 of file MooseVariableFE.h.
FieldVariableCurl
using MooseVariableFE< Real >::FieldVariableCurl = typename MooseVariableField<Real >::FieldVariableCurl inherited
Definition at line 56 of file MooseVariableFE.h.
FieldVariableDivergence
using MooseVariableFE< Real >::FieldVariableDivergence = typename MooseVariableField<Real >::FieldVariableDivergence inherited
Definition at line 57 of file MooseVariableFE.h.
FieldVariableGradient
using MooseVariableFE< Real >::FieldVariableGradient = typename MooseVariableField<Real >::FieldVariableGradient inherited
Definition at line 54 of file MooseVariableFE.h.
FieldVariablePhiCurl
using MooseVariableFE< Real >::FieldVariablePhiCurl = typename MooseVariableField<Real >::FieldVariablePhiCurl inherited
Definition at line 68 of file MooseVariableFE.h.
FieldVariablePhiDivergence
using MooseVariableFE< Real >::FieldVariablePhiDivergence = typename MooseVariableField<Real >::FieldVariablePhiDivergence inherited
Definition at line 69 of file MooseVariableFE.h.
FieldVariablePhiGradient
using MooseVariableFE< Real >::FieldVariablePhiGradient = typename MooseVariableField<Real >::FieldVariablePhiGradient inherited
Definition at line 65 of file MooseVariableFE.h.
FieldVariablePhiSecond
using MooseVariableFE< Real >::FieldVariablePhiSecond = typename MooseVariableField<Real >::FieldVariablePhiSecond inherited
Definition at line 67 of file MooseVariableFE.h.
FieldVariablePhiValue
using MooseVariableFE< Real >::FieldVariablePhiValue = typename MooseVariableField<Real >::FieldVariablePhiValue inherited
Definition at line 64 of file MooseVariableFE.h.
FieldVariableSecond
using MooseVariableFE< Real >::FieldVariableSecond = typename MooseVariableField<Real >::FieldVariableSecond inherited
Definition at line 55 of file MooseVariableFE.h.
FieldVariableTestCurl
using MooseVariableFE< Real >::FieldVariableTestCurl = typename MooseVariableField<Real >::FieldVariableTestCurl inherited
Definition at line 76 of file MooseVariableFE.h.
FieldVariableTestDivergence
using MooseVariableFE< Real >::FieldVariableTestDivergence = typename MooseVariableField<Real >::FieldVariableTestDivergence inherited
Definition at line 77 of file MooseVariableFE.h.
FieldVariableTestGradient
using MooseVariableFE< Real >::FieldVariableTestGradient = typename MooseVariableField<Real >::FieldVariableTestGradient inherited
Definition at line 73 of file MooseVariableFE.h.
FieldVariableTestSecond
using MooseVariableFE< Real >::FieldVariableTestSecond = typename MooseVariableField<Real >::FieldVariableTestSecond inherited
Definition at line 75 of file MooseVariableFE.h.
FieldVariableTestValue
using MooseVariableFE< Real >::FieldVariableTestValue = typename MooseVariableField<Real >::FieldVariableTestValue inherited
Definition at line 72 of file MooseVariableFE.h.
FieldVariableValue
using MooseVariableFE< Real >::FieldVariableValue = typename MooseVariableField<Real >::FieldVariableValue inherited
Definition at line 53 of file MooseVariableFE.h.
FunctorArg
using MooseVariableFE< Real >::FunctorArg = typename Moose::ADType<Real >::type inherited
Definition at line 83 of file MooseVariableFE.h.
FunctorReturnType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::FunctorReturnType = Moose::ADType< OutputType >::type inherited
Definition at line 55 of file MooseFunctor.h.
FunctorType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::FunctorType = FunctorBase<Moose::ADType< OutputType >::type > inherited
Definition at line 54 of file MooseFunctor.h.
GradientType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::GradientType = typename MetaPhysicL::ReplaceAlgebraicType< Moose::ADType< OutputType >::type , typename TensorTools::IncrementRank<typename MetaPhysicL::ValueType<Moose::ADType< OutputType >::type >::type>::type>::type inherited
This rigmarole makes it so that a user can create functors that return containers (std::vector, std::array).
This logic will make it such that if a user requests a functor type T that is a container of algebraic types, for example Reals, then the GradientType will be a container of the gradients of those algebraic types, in this example VectorValue<Reals>. So if T is std::vector<Real>, then GradientType will be std::vector<VectorValue<Real>>. As another example: T = std::array<VectorValue<Real>, 1> -> GradientType = std::array<TensorValue<Real>, 1>
Definition at line 64 of file MooseFunctor.h.
NodeArg
using MooseVariableFE< Real >::NodeArg = Moose::NodeArg protected inherited
Definition at line 729 of file MooseVariableFE.h.
OutputData
using MooseVariableFE< Real >::OutputData = typename MooseVariableField<Real >::OutputData inherited
Definition at line 80 of file MooseVariableFE.h.
OutputDivergence
using MooseVariableFE< Real >::OutputDivergence = typename MooseVariableField<Real >::OutputDivergence inherited
Definition at line 51 of file MooseVariableFE.h.
OutputGradient
using MooseVariableFE< Real >::OutputGradient = typename MooseVariableField<Real >::OutputGradient inherited
Definition at line 49 of file MooseVariableFE.h.
OutputSecond
using MooseVariableFE< Real >::OutputSecond = typename MooseVariableField<Real >::OutputSecond inherited
Definition at line 50 of file MooseVariableFE.h.
OutputShape
using MooseVariableFE< Real >::OutputShape = typename MooseVariableField<Real >::OutputShape inherited
Definition at line 59 of file MooseVariableFE.h.
OutputShapeDivergence
using MooseVariableFE< Real >::OutputShapeDivergence = typename MooseVariableField<Real >::OutputShapeDivergence inherited
Definition at line 62 of file MooseVariableFE.h.
OutputShapeGradient
using MooseVariableFE< Real >::OutputShapeGradient = typename MooseVariableField<Real >::OutputShapeGradient inherited
Definition at line 60 of file MooseVariableFE.h.
OutputShapeSecond
using MooseVariableFE< Real >::OutputShapeSecond = typename MooseVariableField<Real >::OutputShapeSecond inherited
Definition at line 61 of file MooseVariableFE.h.
StateArg
using MooseVariableFE< Real >::StateArg = Moose::StateArg protected inherited
Definition at line 728 of file MooseVariableFE.h.
ValueType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::ValueType = Moose::ADType< OutputType >::type inherited
Definition at line 56 of file MooseFunctor.h.
Constructor & Destructor Documentation
MooseVariableConstMonomial()
MooseVariableConstMonomial::MooseVariableConstMonomial (const InputParameters & parameters)
Definition at line 30 of file MooseVariableConstMonomial.C.
  : MooseVariable(parameters)
{
  if (_fe_type.order != CONSTANT || _fe_type.family != MONOMIAL)
    mooseError("This type is only meant for a CONSTANT "
               "MONOMIAL finite element basis. You have requested a ",
               Utility::enum_to_string(_fe_type.family),
               " family and order ",
               Utility::enum_to_string(Order(_fe_type.order)));
}
Member Function Documentation
activeOnSubdomain()
bool MooseVariableFieldBase::activeOnSubdomain (SubdomainID subdomain) const inherited
Is the variable active on the subdomain?
Parameters
subdomain The subdomain id in question
Returns
true if active on subdomain, false otherwise
Definition at line 45 of file MooseVariableFieldBase.C.
{
  return this->_sys.system().variable(_var_num).active_on_subdomain(subdomain);
}
Referenced by ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), ComputeFullJacobianThread::computeOnInternalFace(), ComputeDiracThread::onElement(), and FlagElementsThread::onElement().
activeOnSubdomains()
bool MooseVariableFieldBase::activeOnSubdomains (const std::set< SubdomainID > & subdomains) const inherited
Is the variable active on the subdomains?
Parameters
subdomains The subdomain ids in question
Returns
true if active on all provided subdomains, false otherwise
Definition at line 51 of file MooseVariableFieldBase.C.
{
  const auto & active_subs = activeSubdomains();
  return std::includes(
      active_subs.begin(), active_subs.end(), subdomains.begin(), subdomains.end());
}
activeSubdomains()
const std::set< SubdomainID > & MooseVariableFieldBase::activeSubdomains () const inherited
The subdomains the variable is active on.
Definition at line 39 of file MooseVariableFieldBase.C.
{
  return this->_sys.system().variable(_var_num).active_subdomains();
}
Referenced by SetupResidualDebugAction::act(), MooseVariableFieldBase::activeOnSubdomains(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), BlockRestrictable::checkVariable(), DGLowerDKernel::DGLowerDKernel(), HFEMDirichletBC::HFEMDirichletBC(), and LowerDIntegratedBC::LowerDIntegratedBC().
add()
void MooseVariableFE< Real >::add (NumericVector< Number > & residual) override virtual inherited
Add the current local DOF values to the input vector.
Implements MooseVariableFieldBase.
Definition at line 561 of file MooseVariableFE.C.
{
  _element_data->add(residual);
}
adDofValues()
const MooseArray< ADReal > & MooseVariableFE< Real >::adDofValues inline override virtual inherited
Return the AD dof values.
Implements MooseVariableField< OutputType >.
Definition at line 598 of file MooseVariableFE.h.
{
  return _element_data->adDofValues();
}
adDofValuesNeighbor()
const MooseArray< ADReal > & MooseVariableFE< Real >::adDofValuesNeighbor inline override virtual inherited
Return the AD neignbor dof values.
Implements MooseVariableField< OutputType >.
Definition at line 603 of file MooseVariableFE.h.
{
  return _neighbor_data->adDofValues();
}
addSolution()
void MooseVariableFE< Real >::addSolution (const DenseVector< Number > & v) inherited
Add passed in local DOF values onto the current solution.
Definition at line 565 of file MooseVariableFE.C.
{
  _element_data->addSolution(this->_sys.solution(), v);
}
addSolutionNeighbor()
void MooseVariableFE< Real >::addSolutionNeighbor (const DenseVector< Number > & v) inherited
Add passed in local neighbor DOF values onto the current solution.
Definition at line 569 of file MooseVariableFE.C.
{
  _neighbor_data->addSolution(this->_sys.solution(), v);
}
adGradPhi()
const ADTemplateVariableTestGradient< OutputShape > & MooseVariableFE< Real >::adGradPhi () const inline inherited
Definition at line 252 of file MooseVariableFE.h.
  {
    return _element_data->adGradPhi();
  }
adGradPhiFace()
const ADTemplateVariableTestGradient< OutputShape > & MooseVariableFE< Real >::adGradPhiFace () const inline inherited
Definition at line 257 of file MooseVariableFE.h.
  {
    return _element_data->adGradPhiFace();
  }
adGradPhiFaceNeighbor()
const ADTemplateVariableTestGradient< OutputShape > & MooseVariableFE< Real >::adGradPhiFaceNeighbor () const inline inherited
Definition at line 262 of file MooseVariableFE.h.
  {
    return _neighbor_data->adGradPhiFace();
  }
adGradSln()
const ADTemplateVariableGradient< Real > & MooseVariableFE< Real >::adGradSln () const inline override virtual inherited
AD grad solution getter.
Implements MooseVariableField< OutputType >.
Definition at line 346 of file MooseVariableFE.h.
  {
    return _element_data->adGradSln();
  }
adGradSlnDot()
const ADTemplateVariableGradient< Real > & MooseVariableFE< Real >::adGradSlnDot () const inline override virtual inherited
AD grad of time derivative solution getter.
Implements MooseVariableField< OutputType >.
Definition at line 362 of file MooseVariableFE.h.
  {
    return _element_data->adGradSlnDot();
  }
adGradSlnNeighbor()
const ADTemplateVariableGradient< Real > & MooseVariableFE< Real >::adGradSlnNeighbor () const inline override virtual inherited
AD grad neighbor solution getter.
Implements MooseVariableField< OutputType >.
Definition at line 372 of file MooseVariableFE.h.
  {
    return _neighbor_data->adGradSln();
  }
adGradSlnNeighborDot()
const ADTemplateVariableGradient< Real > & MooseVariableFE< Real >::adGradSlnNeighborDot () const inline override virtual inherited
AD grad of time derivative neighbor solution getter.
Implements MooseVariableField< OutputType >.
Definition at line 388 of file MooseVariableFE.h.
  {
    return _neighbor_data->adGradSlnDot();
  }
adNodalValue()
const Moose::ADType< Real >::type & MooseVariableFE< Real >::adNodalValue inline inherited
Definition at line 695 of file MooseVariableFE.h.
{
  return _element_data->adNodalValue();
}
adSecondSln()
const ADTemplateVariableSecond< Real > & MooseVariableFE< Real >::adSecondSln () const inline override virtual inherited
AD second solution getter.
Implements MooseVariableField< OutputType >.
Definition at line 350 of file MooseVariableFE.h.
  {
    return _element_data->adSecondSln();
  }
adSecondSlnNeighbor()
const ADTemplateVariableSecond< Real > & MooseVariableFE< Real >::adSecondSlnNeighbor () const inline override virtual inherited
AD second neighbor solution getter.
Implements MooseVariableField< OutputType >.
Definition at line 376 of file MooseVariableFE.h.
  {
    return _neighbor_data->adSecondSln();
  }
adSln()
const ADTemplateVariableValue< Real > & MooseVariableFE< Real >::adSln () const inline override virtual inherited
AD.
Implements MooseVariableField< OutputType >.
Definition at line 341 of file MooseVariableFE.h.
  {
    return _element_data->adSln();
  }
adSlnLower()
const ADTemplateVariableValue< Real > & MooseVariableFE< Real >::adSlnLower () const inline inherited
lower-d element solution
Definition at line 496 of file MooseVariableFE.h.
{ return _lower_data->adSln(); }
adSlnNeighbor()
const ADTemplateVariableValue< Real > & MooseVariableFE< Real >::adSlnNeighbor () const inline override virtual inherited
neighbor AD
Implements MooseVariableField< OutputType >.
Definition at line 368 of file MooseVariableFE.h.
  {
    return _neighbor_data->adSln();
  }
adUDot()
const ADTemplateVariableValue< Real > & MooseVariableFE< Real >::adUDot () const inline override virtual inherited
AD time derivative getter.
Implements MooseVariableField< OutputType >.
Definition at line 354 of file MooseVariableFE.h.
  {
    return _element_data->adUDot();
  }
adUDotDot()
const ADTemplateVariableValue< Real > & MooseVariableFE< Real >::adUDotDot () const inline override virtual inherited
AD second time derivative getter.
Implements MooseVariableField< OutputType >.
Definition at line 358 of file MooseVariableFE.h.
  {
    return _element_data->adUDotDot();
  }
adUDotDotNeighbor()
const ADTemplateVariableValue< Real > & MooseVariableFE< Real >::adUDotDotNeighbor () const inline override virtual inherited
AD neighbor second time derivative getter.
Implements MooseVariableField< OutputType >.
Definition at line 384 of file MooseVariableFE.h.
  {
    return _neighbor_data->adUDotDot();
  }
adUDotNeighbor()
const ADTemplateVariableValue< Real > & MooseVariableFE< Real >::adUDotNeighbor () const inline override virtual inherited
AD neighbor time derivative getter.
Implements MooseVariableField< OutputType >.
Definition at line 380 of file MooseVariableFE.h.
  {
    return _neighbor_data->adUDot();
  }
allDofIndices()
const std::vector< dof_id_type > & MooseVariableBase::allDofIndices () const inherited
Get all global dofindices for the variable.
Definition at line 137 of file MooseVariableBase.C.
{
  const auto it = _sys.subproblem()._var_dof_map.find(name());
  if (it != _sys.subproblem()._var_dof_map.end())
    return it->second;
  else
    mooseError("VariableAllDoFMap not prepared for ",
               name(),
               " . Check nonlocal coupling requirement for the variable.");
}
Referenced by FEProblemBase::addJacobianBlockTags(), NonlocalIntegratedBC::computeNonlocalJacobian(), NonlocalKernel::computeNonlocalJacobian(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), FEProblemBase::prepare(), Assembly::prepareNonlocal(), Assembly::prepareVariableNonlocal(), and MooseVariableBase::totalVarDofs().
arrayGradPhi()
const MappedArrayVariablePhiGradient & MooseVariableFE< Real >::arrayGradPhi () const inline inherited
Definition at line 199 of file MooseVariableFE.h.
  {
    return _element_data->arrayGradPhi();
  }
arrayGradPhiFace()
const MappedArrayVariablePhiGradient & MooseVariableFE< Real >::arrayGradPhiFace () const inline inherited
Definition at line 212 of file MooseVariableFE.h.
  {
    return _element_data->arrayGradPhiFace();
  }
arrayGradPhiFaceNeighbor()
const MappedArrayVariablePhiGradient & MooseVariableFE< Real >::arrayGradPhiFaceNeighbor () const inline inherited
Definition at line 241 of file MooseVariableFE.h.
  {
    return _neighbor_data->arrayGradPhiFace();
  }
arrayGradPhiNeighbor()
const MappedArrayVariablePhiGradient & MooseVariableFE< Real >::arrayGradPhiNeighbor () const inline inherited
Definition at line 225 of file MooseVariableFE.h.
  {
    return _neighbor_data->arrayGradPhi();
  }
arrayScalingFactor()
const std::vector< Real > & MooseVariableBase::arrayScalingFactor () const inline inherited
Definition at line 97 of file MooseVariableBase.h.
{ return _scaling_factor; }
Referenced by Assembly::addJacobianBlock(), Assembly::addJacobianBlockNonlocal(), Assembly::addJacobianNeighbor(), Assembly::cacheJacobianBlock(), and Assembly::cacheJacobianBlockNonzero().
blockIDs()
const std::set< SubdomainID > & BlockRestrictable::blockIDs () const virtual inherited
Return the block subdomain ids for this object Note, if this is not block restricted, this function returns all mesh subdomain ids.
Returns
a set of SubdomainIDs that are valid for this object
Definition at line 190 of file BlockRestrictable.C.
{
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return _blk_mesh->meshSubdomains();
  else
    return _blk_ids;
}
Referenced by FunctorMaterial::addFunctorProperty(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), NodalPatchRecoveryAuxBase::blockRestrictElements(), MooseMesh::cacheFaceInfoVariableOwnership(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), BlockRestrictable::getBlockCoordSystem(), MaterialBase::getGenericZeroMaterialPropertyByName(), BlockRestrictable::hasBlockMaterialPropertyHelper(), SubdomainsDivision::initialize(), ElementCentroidPositions::initialize(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), MaterialBase::registerPropName(), and FVPointValueConstraint::setMyElem().
blockRestricted()
bool BlockRestrictable::blockRestricted () const virtual inherited
Returns true if this object has been restricted to a block.
See also
MooseObject
Definition at line 178 of file BlockRestrictable.C.
{
  return _blk_ids.find(Moose::ANY_BLOCK_ID) == _blk_ids.end();
}
Referenced by NodalPatchRecoveryAuxBase::blockRestrictElements(), BlockRestrictable::checkVariable(), SubdomainsDivision::divisionIndex(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), SubdomainsDivision::initialize(), ElementCentroidPositions::initialize(), BlockRestrictable::initializeBlockRestrictable(), SolutionIC::initialSetup(), and FVPointValueConstraint::setMyElem().
blocks()
const std::vector< SubdomainName > & BlockRestrictable::blocks () const inherited
Return the block names for this object.
Note, if the 'blocks' input parameter was not utilized this will return an empty vector.
Returns
vector of SubdomainNames that are valid for this object
Definition at line 184 of file BlockRestrictable.C.
{
  return _blocks;
}
Referenced by MaterialOutputAction::getParams(), BlockAverageValue::initialize(), SubdomainsDivision::initialize(), and SolutionIC::initialSetup().
blocksMaxDimension()
unsigned int BlockRestrictable::blocksMaxDimension () const inherited
Return the largest mesh dimension of the elements in the blocks for this object.
Definition at line 360 of file BlockRestrictable.C.
{
  mooseAssert(_blk_dim != libMesh::invalid_uint, "Block restriction not initialized");
  return _blk_dim;
}
buildOutputHideVariableList()
void OutputInterface::buildOutputHideVariableList (std::set< std::string > variable_names) inherited
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
Parameters
variable_names A set of variables for which the 'outputs' parameter controls
By default this is called by the constructor and passes the block name as the list of variables. This needs to be called explicitly if the build_list flag is set to False in the constructor. The latter cases is needed by the Material object to work correctly with the automatic material output capability.
Definition at line 61 of file OutputInterface.C.
{
  // Set of available names
  const std::set<OutputName> & avail = _oi_output_warehouse.getOutputNames();
  // Check for 'none'; hide variables on all outputs
  if (_oi_outputs.find("none") != _oi_outputs.end())
    for (const auto & name : avail)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  // Check for empty and 'all' in 'outputs' parameter; do not perform any variable restrictions in
  // these cases
  else if (_oi_outputs.empty() || _oi_outputs.find("all") != _oi_outputs.end())
    return;
  // Limit the variable output to Output objects listed
  else
  {
    // Create a list of outputs where the variable should be hidden
    std::set<OutputName> hide;
    std::set_difference(avail.begin(),
                        avail.end(),
                        _oi_outputs.begin(),
                        _oi_outputs.end(),
                        std::inserter(hide, hide.begin()));
    // If 'outputs' is specified add the object name to the list of items to hide
    for (const auto & name : hide)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  }
}
Referenced by ReporterTransferInterface::hideVariableHelper(), and OutputInterface::OutputInterface().
checkFace()
FaceArg Moose::FunctorBase< Moose::ADType< OutputType >::type >::checkFace (const Moose::FaceArg & face) const inherited
Examines the incoming face argument.
If the face argument producer (residual object, postprocessor, etc.) did not indicate a sidedness to the face, e.g. if the face_side member of the FaceArg is nullptr, then we may "modify" the sidedness of the argument if we are only defined on one side of the face. If the face argument producer \emph has indicated a sidedness and we are not defined on that side, then we will error
Parameters
face The face argument created by the face argument producer, likely a residual object
Returns
A face with possibly changed sidedness depending on whether we aren't defined on both sides of the face
Definition at line 181 of file MooseFunctor.h.
{
  const Elem * const elem = face.face_side;
  const FaceInfo * const fi = face.fi;
  mooseAssert(fi, "face info should be non-null");
  auto ret_face = face;
  bool check_elem_def = false;
  bool check_neighbor_def = false;
  if (!elem)
  {
    if (!hasFaceSide(*fi, true))
    {
      ret_face.face_side = fi->neighborPtr();
      check_neighbor_def = true;
    }
    else if (!hasFaceSide(*fi, false))
    {
      ret_face.face_side = fi->elemPtr();
      check_elem_def = true;
    }
  }
  else if (elem == fi->elemPtr())
    check_elem_def = true;
  else
  {
    mooseAssert(elem == fi->neighborPtr(), "This has to match something");
    check_neighbor_def = true;
  }
  if (check_elem_def && !hasFaceSide(*fi, true))
  {
    std::string additional_message = "It is not defined on the neighbor side either.";
    if (hasFaceSide(*fi, false))
      additional_message = "It is however defined on the neighbor side.";
    additional_message += " Face centroid: " + Moose::stringify(fi->faceCentroid());
    mooseError(_functor_name,
               " is not defined on the element side of the face information, but a face argument "
               "producer "
               "(e.g. residual object, postprocessor, etc.) has requested evaluation there.\n",
               additional_message);
  }
  if (check_neighbor_def && !hasFaceSide(*fi, false))
  {
    std::string additional_message = "It is not defined on the element side either.";
    if (hasFaceSide(*fi, true))
      additional_message = "It is however defined on the element side.";
    additional_message += " Face centroid: " + Moose::stringify(fi->faceCentroid());
    mooseError(
        _functor_name,
        " is not defined on the neighbor side of the face information, but a face argument "
        "producer (e.g. residual object, postprocessor, etc.) has requested evaluation there.\n",
        additional_message);
  }
  return ret_face;
}
checkVariable()
void BlockRestrictable::checkVariable (const MooseVariableFieldBase & variable) const virtual inherited
Helper for checking that the ids for this object are in agreement with the variables on the supplied variable.
Parameters
variable The variable to check against.
Reimplemented in DomainUserObject.
Definition at line 333 of file BlockRestrictable.C.
{
  // a variable defined on all internal sides does not need this check because
  // it can be coupled with other variables in DG kernels
  if (variable.activeSubdomains().count(Moose::INTERNAL_SIDE_LOWERD_ID) > 0)
    return;
  if (!isBlockSubset(variable.activeSubdomains()))
  {
    std::string var_ids = Moose::stringify(variable.activeSubdomains(), ", ");
    std::string obj_ids = Moose::stringify(blockRestricted() ? _blk_ids : meshBlockIDs(), ", ");
    mooseError("The 'block' parameter of the object '",
               _blk_name,
               "' must be a subset of the 'block' parameter of the variable '",
               variable.name(),
               "':\n    Object '",
               _blk_name,
               "': ",
               obj_ids,
               "\n    Variable '",
               variable.name(),
               "': ",
               var_ids);
  }
}
Referenced by DomainUserObject::checkVariable().
clearAllDofIndices()
void MooseVariableFE< Real >::clearAllDofIndices final virtual inherited
Reimplemented from MooseVariableBase.
Definition at line 190 of file MooseVariableFE.C.
{
  _element_data->clearDofIndices();
  _neighbor_data->clearDofIndices();
  _lower_data->clearDofIndices();
}
clearCacheData()
void Moose::FunctorBase< Moose::ADType< OutputType >::type >::clearCacheData private inherited
clear cache data
Definition at line 391 of file MooseFunctor.h.
{
  for (auto & map_pr : _qp_to_value)
    for (auto & pr : map_pr.second)
      pr.first = false;
  for (auto & map_pr : _side_qp_to_value)
  {
    auto & side_vector = map_pr.second;
    for (auto & qp_vector : side_vector)
      for (auto & pr : qp_vector)
        pr.first = false;
  }
  _current_qp_map_key = DofObject::invalid_id;
  _current_qp_map_value = nullptr;
  _current_side_qp_map_key = DofObject::invalid_id;
  _current_side_qp_map_value = nullptr;
  _elem_arg_to_value.clear();
  _face_arg_to_value.clear();
  _node_arg_to_value.clear();
}
clearDofIndices()
void MooseVariableFE< Real >::clearDofIndices override virtual inherited
Clear out the dof indices.
We do this in case this variable is not going to be prepared at all...
Implements MooseVariableFieldBase.
Definition at line 93 of file MooseVariableFE.C.
{
  _element_data->clearDofIndices();
}
componentDofIndices()
std::vector< dof_id_type > MooseVariableBase::componentDofIndices (const std::vector< dof_id_type > & dof_indices, unsigned int component) const inherited
Obtain DoF indices of a component with the indices of the 0th component.
Definition at line 155 of file MooseVariableBase.C.
{
  std::vector<dof_id_type> new_dof_indices(dof_indices);
  if (component != 0)
  {
    if (isNodal())
      for (auto & id : new_dof_indices)
        id += component;
    else
    {
      unsigned int n = dof_indices.size();
      for (auto & id : new_dof_indices)
        id += component * n;
    }
  }
  return new_dof_indices;
}
Referenced by Assembly::addJacobianBlock(), Assembly::cacheJacobianBlock(), and Assembly::cacheJacobianBlockNonzero().
componentName()
std::string MooseVariableFieldBase::componentName (const unsigned int comp) const inherited
Get the variable name of a component in libMesh.
Definition at line 27 of file MooseVariableFieldBase.C.
{
  if (comp >= _count)
    mooseError("Component index must be less than the number of components of variable ",
               _var_name);
  if (isArray())
    return this->_subproblem.arrayVariableComponent(_var_name, comp);
  else
    return _var_name;
}
computeElemValues()
void MooseVariableConstMonomial::computeElemValues () override virtual
Actually compute variable values from the solution vectors.
Reimplemented from MooseVariableFE< Real >.
Definition at line 42 of file MooseVariableConstMonomial.C.
{
  _element_data->setGeometry(Moose::Volume);
  // We have not optimized AD calculations for const monomials yet, so we fall back on the
  // non-optimized routine
  if (_element_data->needsAD())
    _element_data->computeValues();
  else
    _element_data->computeMonomialValues();
}
computeElemValuesFace()
void MooseVariableConstMonomial::computeElemValuesFace () override virtual
Compute values at facial quadrature points.
Reimplemented from MooseVariableFE< Real >.
Definition at line 55 of file MooseVariableConstMonomial.C.
{
  _element_data->setGeometry(Moose::Face);
  // We have not optimized AD calculations for const monomials yet, so we fall back on the
  // non-optimized routine
  if (_element_data->needsAD())
    _element_data->computeValues();
  else
    _element_data->computeMonomialValues();
}
computeFaceValues()
virtual void MooseVariableFieldBase::computeFaceValues (const FaceInfo &) inline virtual inherited
Compute values at face quadrature points for the element+neighbor (both sides of the face).
Reimplemented in MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 130 of file MooseVariableFieldBase.h.
{ mooseError("not implemented"); }
computeIncrementAtNode()
void MooseVariableFE< Real >::computeIncrementAtNode (const NumericVector< Number > & increment_vec) inherited
Compute and store incremental change at the current node based on increment_vec.
Definition at line 613 of file MooseVariableFE.C.
{
  _element_data->computeIncrementAtNode(increment_vec);
}
computeIncrementAtQps()
void MooseVariableFE< Real >::computeIncrementAtQps (const NumericVector< Number > & increment_vec) inherited
Compute and store incremental change in solution at QPs based on increment_vec.
Definition at line 608 of file MooseVariableFE.C.
{
  _element_data->computeIncrementAtQps(increment_vec);
}
computeLowerDValues()
void MooseVariableFE< Real >::computeLowerDValues override virtual inherited
compute values at quadrature points on the lower dimensional element
Implements MooseVariableFieldBase.
Definition at line 505 of file MooseVariableFE.C.
{
  _lower_data->setGeometry(Moose::Volume);
  _lower_data->computeValues();
}
computeNeighborValues()
void MooseVariableConstMonomial::computeNeighborValues () override virtual
Compute values at quadrature points for the neighbor.
Reimplemented from MooseVariableFE< Real >.
Definition at line 68 of file MooseVariableConstMonomial.C.
{
  _neighbor_data->setGeometry(Moose::Volume);
  // We have not optimized AD calculations for const monomials yet, so we fall back on the
  // non-optimized routine
  if (_neighbor_data->needsAD())
    _neighbor_data->computeValues();
  else
    _neighbor_data->computeMonomialValues();
}
computeNeighborValuesFace()
void MooseVariableConstMonomial::computeNeighborValuesFace () override virtual
Compute values at facial quadrature points for the neighbor.
Reimplemented from MooseVariableFE< Real >.
Definition at line 81 of file MooseVariableConstMonomial.C.
{
  _neighbor_data->setGeometry(Moose::Face);
  // We have not optimized AD calculations for const monomials yet, so we fall back on the
  // non-optimized routine
  if (_neighbor_data->needsAD())
    _neighbor_data->computeValues();
  else
    _neighbor_data->computeMonomialValues();
}
computeNodalNeighborValues()
void MooseVariableFE< Real >::computeNodalNeighborValues override virtual inherited
Compute nodal values of this variable in the neighbor.
Implements MooseVariableFieldBase.
Definition at line 698 of file MooseVariableFE.C.
{
  _neighbor_data->computeNodalValues();
}
computeNodalValues()
void MooseVariableFE< Real >::computeNodalValues override virtual inherited
Compute nodal values of this variable.
Implements MooseVariableFieldBase.
Definition at line 697 of file MooseVariableFE.C.
{
  _element_data->computeNodalValues();
}
computeSolution()
void MooseVariableFE< Real >::computeSolution (const Elem * elem, unsigned int n_qp, const StateArg & state, const Shapes & phi, Solution & local_soln, const GradShapes & grad_phi, GradSolution & grad_local_soln, Solution & dot_local_soln, GradSolution & grad_dot_local_soln) const private inherited
Compute the solution, gradient, time derivative, and gradient of the time derivative with provided shape functions.
Definition at line 768 of file MooseVariableFE.C.
{
  std::vector<dof_id_type> dof_indices;
  this->_dof_map.dof_indices(elem, dof_indices, _var_num);
  std::vector<ADReal> dof_values;
  std::vector<ADReal> dof_values_dot;
  dof_values.reserve(dof_indices.size());
  const bool computing_dot = _time_integrator && _time_integrator->dt();
  if (computing_dot)
    dof_values_dot.reserve(dof_indices.size());
  const bool do_derivatives = Moose::doDerivatives(_subproblem, _sys);
  const auto & global_soln = getSolution(state);
  for (const auto dof_index : dof_indices)
  {
    dof_values.push_back(ADReal(global_soln(dof_index)));
    if (do_derivatives && state.state == 0)
      Moose::derivInsert(dof_values.back().derivatives(), dof_index, 1.);
    if (computing_dot)
    {
      if (_var_kind == Moose::VAR_NONLINEAR)
      {
        dof_values_dot.push_back(dof_values.back());
        _time_integrator->computeADTimeDerivatives(
            dof_values_dot.back(), dof_index, _ad_real_dummy);
      }
      else
        dof_values_dot.push_back((*this->_sys.solutionUDot())(dof_index));
    }
  }
  local_soln.resize(n_qp);
  grad_local_soln.resize(n_qp);
  if (computing_dot)
  {
    dot_local_soln.resize(n_qp);
    grad_dot_local_soln.resize(n_qp);
  }
  for (const auto qp : make_range(n_qp))
  {
    local_soln[qp] = 0;
    grad_local_soln[qp] = 0;
    if (computing_dot)
    {
      dot_local_soln[qp] = 0;
      grad_dot_local_soln[qp] = GradientType{};
    }
    for (const auto i : index_range(dof_indices))
    {
      local_soln[qp] += dof_values[i] * phi[i][qp];
      grad_local_soln[qp] += dof_values[i] * grad_phi[i][qp];
      if (computing_dot)
      {
        dot_local_soln[qp] += dof_values_dot[i] * phi[i][qp];
        grad_dot_local_soln[qp] += dof_values_dot[i] * grad_phi[i][qp];
      }
    }
  }
}
computingCurl()
bool MooseVariableFE< Real >::computingCurl final override virtual inherited
Whether or not this variable is computing the curl.
Implements MooseVariableField< OutputType >.
Definition at line 141 of file MooseVariableFE.C.
{
  return _element_data->computingCurl();
}
computingDiv()
bool MooseVariableFE< Real >::computingDiv final override virtual inherited
Whether or not this variable is computing the divergence.
Implements MooseVariableField< OutputType >.
Definition at line 146 of file MooseVariableFE.C.
{
  return _element_data->computingDiv();
}
computingSecond()
bool MooseVariableFE< Real >::computingSecond () const inline final override virtual inherited
Whether or not this variable is computing any second derivatives.
Implements MooseVariableField< OutputType >.
Definition at line 136 of file MooseVariableFE.h.
{ return usesSecondPhi(); }
connectControllableParams()
void MooseBaseParameterInterface::connectControllableParams (const std::string & parameter, const std::string & object_type, const std::string & object_name, const std::string & object_parameter) const inherited
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
Parameters
parameter Name of the controllable parameter of this action
object_type Type of the object added by this action.
object_name Name of the object added by this action.
object_parameter Name of the parameter of the object.
Definition at line 34 of file MooseBaseParameterInterface.C.
{
  MooseObjectParameterName primary_name(uniqueName(), parameter);
  const auto base_type = _factory.getValidParams(object_type).get<std::string>("_moose_base");
  MooseObjectParameterName secondary_name(base_type, object_name, object_parameter);
  _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
      primary_name, secondary_name);
  const auto & tags = _pars.get<std::vector<std::string>>("control_tags");
  for (const auto & tag : tags)
  {
    if (!tag.empty())
    {
      MooseObjectParameterName tagged_name(tag, _moose_base->name(), parameter);
      _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
          tagged_name, secondary_name);
    }
  }
}
count()
unsigned int MooseVariableBase::count () const inline inherited
Get the number of components Note: For standard and vector variables, the number is one.
Definition at line 109 of file MooseVariableBase.h.
{ return _count; }
Referenced by Assembly::addJacobianBlock(), EigenProblem::adjustEigenVector(), ArrayBodyForce::ArrayBodyForce(), ArrayConstantIC::ArrayConstantIC(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayFunctionIC::ArrayFunctionIC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), BuildArrayVariableAux::BuildArrayVariableAux(), Assembly::cacheJacobianBlock(), Assembly::cacheJacobianBlockNonzero(), TagAuxBase< T >::checkCoupledVariable(), BuildArrayVariableAux::compute(), ArrayNodalBC::computeJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), ArrayNodalBC::computeOffDiagJacobian(), ArrayIntegratedBC::computeQpJacobian(), ArrayNodalBC::computeQpJacobian(), ArrayKernel::computeQpJacobian(), EigenArrayDirichletBC::computeQpJacobian(), ArrayCoupledTimeDerivative::computeQpJacobian(), ArrayDiffusion::computeQpJacobian(), ArrayReaction::computeQpJacobian(), ArrayTimeDerivative::computeQpJacobian(), ArrayIntegratedBC::computeQpOffDiagJacobian(), ArrayKernel::computeQpOffDiagJacobian(), ArrayCoupledTimeDerivative::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), ArrayNodalBC::computeQpOffDiagJacobian(), EigenArrayDirichletBC::computeQpOffDiagJacobian(), Kernel::computeQpOffDiagJacobianArray(), ArrayIntegratedBC::computeQpOffDiagJacobianScalar(), ArrayKernel::computeQpOffDiagJacobianScalar(), ArrayCoupledTimeDerivative::computeQpResidual(), ArrayReaction::computeQpResidual(), ArrayTimeDerivative::computeQpResidual(), ArrayParsedAux::computeValue(), FunctionArrayAux::computeValue(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), FunctionArrayAux::FunctionArrayAux(), ArrayFunctionIC::gradient(), AdvancedOutput::initAvailableLists(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), ArrayDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), Assembly::prepareJacobianBlock(), Assembly::prepareLowerD(), Assembly::prepareNeighbor(), Assembly::prepareNonlocal(), Assembly::prepareVariable(), Assembly::prepareVariableNonlocal(), MultiAppDofCopyTransfer::transfer(), MultiAppDofCopyTransfer::transferDofObject(), and ArrayFunctionIC::value().
curlPhi()
const MooseVariableFE< Real >::FieldVariablePhiCurl & MooseVariableFE< Real >::curlPhi final override virtual inherited
Curl of the shape functions.
Implements MooseVariableField< OutputType >.
Definition at line 204 of file MooseVariableFE.C.
{
  return _element_data->curlPhi();
}
curlPhiFace()
const MooseVariableFE< Real >::FieldVariablePhiCurl & MooseVariableFE< Real >::curlPhiFace inherited
Definition at line 217 of file MooseVariableFE.C.
{
  return _element_data->curlPhiFace();
}
curlPhiFaceNeighbor()
const MooseVariableFE< Real >::FieldVariablePhiCurl & MooseVariableFE< Real >::curlPhiFaceNeighbor inherited
Definition at line 246 of file MooseVariableFE.C.
{
  return _neighbor_data->curlPhiFace();
}
curlPhiNeighbor()
const MooseVariableFE< Real >::FieldVariablePhiCurl & MooseVariableFE< Real >::curlPhiNeighbor inherited
Definition at line 230 of file MooseVariableFE.C.
{
  return _neighbor_data->curlPhi();
}
curlSln()
const FieldVariableCurl & MooseVariableFE< Real >::curlSln () const inline inherited
element curls
Definition at line 328 of file MooseVariableFE.h.
{ return _element_data->curlSln(Moose::Current); }
curlSlnNeighbor()
const FieldVariableCurl & MooseVariableFE< Real >::curlSlnNeighbor () const inline inherited
neighbor solution curls
Definition at line 460 of file MooseVariableFE.h.
  {
    return _neighbor_data->curlSln(Moose::Current);
  }
curlSlnOld()
const FieldVariableCurl & MooseVariableFE< Real >::curlSlnOld () const inline inherited
Definition at line 329 of file MooseVariableFE.h.
{ return _element_data->curlSln(Moose::Old); }
curlSlnOlder()
const FieldVariableCurl & MooseVariableFE< Real >::curlSlnOlder () const inline inherited
Definition at line 330 of file MooseVariableFE.h.
{ return _element_data->curlSln(Moose::Older); }
curlSlnOlderNeighbor()
const FieldVariableCurl & MooseVariableFE< Real >::curlSlnOlderNeighbor () const inline inherited
Definition at line 468 of file MooseVariableFE.h.
  {
    return _neighbor_data->curlSln(Moose::Older);
  }
curlSlnOldNeighbor()
const FieldVariableCurl & MooseVariableFE< Real >::curlSlnOldNeighbor () const inline inherited
Definition at line 464 of file MooseVariableFE.h.
  {
    return _neighbor_data->curlSln(Moose::Old);
  }
currentElem()
const Elem *const & MooseVariableFE< Real >::currentElem () const inline override virtual inherited
Current element this variable is evaluated at.
Implements MooseVariableFieldBase.
Definition at line 165 of file MooseVariableFE.h.
{ return _element_data->currentElem(); }
currentSide()
const unsigned int & MooseVariableFE< Real >::currentSide () const inline inherited
Current side this variable is being evaluated on.
Definition at line 170 of file MooseVariableFE.h.
{ return _element_data->currentSide(); }
customSetup() [1/2]
virtual void SetupInterface::customSetup (const ExecFlagType &) inline virtual inherited
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
Reimplemented in Function.
Definition at line 61 of file SetupInterface.h.
{}
customSetup() [2/2]
void Moose::FunctorBase< Moose::ADType< OutputType >::type >::customSetup (const ExecFlagType & exec_type) override virtual inherited
Implements Moose::FunctorAbstract.
Definition at line 134 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(exec_type))
    clearCacheData();
}
divPhi()
const MooseVariableFE< Real >::FieldVariablePhiDivergence & MooseVariableFE< Real >::divPhi final override virtual inherited
Divergence of the shape functions.
Implements MooseVariableField< OutputType >.
Definition at line 205 of file MooseVariableFE.C.
{
  return _element_data->divPhi();
}
divPhiFace()
const MooseVariableFE< Real >::FieldVariablePhiDivergence & MooseVariableFE< Real >::divPhiFace inherited
Definition at line 218 of file MooseVariableFE.C.
{
  return _element_data->divPhiFace();
}
divPhiFaceNeighbor()
const MooseVariableFE< Real >::FieldVariablePhiDivergence & MooseVariableFE< Real >::divPhiFaceNeighbor inherited
Definition at line 247 of file MooseVariableFE.C.
{
  return _neighbor_data->divPhiFace();
}
divPhiNeighbor()
const MooseVariableFE< Real >::FieldVariablePhiDivergence & MooseVariableFE< Real >::divPhiNeighbor inherited
Definition at line 231 of file MooseVariableFE.C.
{
  return _neighbor_data->divPhi();
}
divSln()
const FieldVariableDivergence & MooseVariableFE< Real >::divSln () const inline inherited
element divergence
Definition at line 333 of file MooseVariableFE.h.
{ return _element_data->divSln(Moose::Current); }
divSlnNeighbor()
const FieldVariableDivergence & MooseVariableFE< Real >::divSlnNeighbor () const inline inherited
neighbor solution divergence
Definition at line 474 of file MooseVariableFE.h.
  {
    return _neighbor_data->divSln(Moose::Current);
  }
divSlnOld()
const FieldVariableDivergence & MooseVariableFE< Real >::divSlnOld () const inline inherited
Definition at line 334 of file MooseVariableFE.h.
{ return _element_data->divSln(Moose::Old); }
divSlnOlder()
const FieldVariableDivergence & MooseVariableFE< Real >::divSlnOlder () const inline inherited
Definition at line 335 of file MooseVariableFE.h.
  {
    return _element_data->divSln(Moose::Older);
  }
divSlnOlderNeighbor()
const FieldVariableDivergence & MooseVariableFE< Real >::divSlnOlderNeighbor () const inline inherited
Definition at line 482 of file MooseVariableFE.h.
  {
    return _neighbor_data->divSln(Moose::Older);
  }
divSlnOldNeighbor()
const FieldVariableDivergence & MooseVariableFE< Real >::divSlnOldNeighbor () const inline inherited
Definition at line 478 of file MooseVariableFE.h.
  {
    return _neighbor_data->divSln(Moose::Old);
  }
doDerivatives()
bool MooseVariableBase::doDerivatives () const protected inherited
Returns
whether we should insert derivatives
dofIndices()
const std::vector< dof_id_type > & MooseVariableFE< Real >::dofIndices () const inline final virtual inherited
Get local DoF indices.
Reimplemented from MooseVariableBase.
Definition at line 179 of file MooseVariableFE.h.
{ return _element_data->dofIndices(); }
dofIndicesLower()
const std::vector< dof_id_type > & MooseVariableFE< Real >::dofIndicesLower () const inline final virtual inherited
Get dof indices for the current lower dimensional element (this is meaningful when performing mortar FEM)
Returns
the lower dimensional element's dofs
Implements MooseVariableFieldBase.
Definition at line 185 of file MooseVariableFE.h.
  {
    return _lower_data->dofIndices();
  }
dofIndicesNeighbor()
const std::vector< dof_id_type > & MooseVariableFE< Real >::dofIndicesNeighbor () const inline final virtual inherited
Get neighbor DOF indices for currently selected element.
Returns
the neighbor degree of freedom indices
Implements MooseVariableFieldBase.
Definition at line 181 of file MooseVariableFE.h.
  {
    return _neighbor_data->dofIndices();
  }
dofMap()
const DofMap & MooseVariableBase::dofMap () const inline inherited
The DofMap associated with the system this variable is in.
Definition at line 131 of file MooseVariableBase.h.
{ return _dof_map; }
Referenced by AuxScalarKernel::compute(), and ScalarVariable::execute().
dofValue()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValue inherited
Definition at line 571 of file MooseVariableFE.C.
{
  mooseDeprecated("Use dofValues instead of dofValue");
  return dofValues();
}
dofValues()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValues override virtual inherited
dof values getters
Implements MooseVariableField< OutputType >.
Definition at line 572 of file MooseVariableFE.C.
{
  return _element_data->dofValues();
}
dofValuesDot()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesDot override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 580 of file MooseVariableFE.C.
{
  return _element_data->dofValuesDot();
}
dofValuesDotDot()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesDotDot override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 585 of file MooseVariableFE.C.
{
  return _element_data->dofValuesDotDot();
}
dofValuesDotDotNeighbor()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesDotDotNeighbor override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 586 of file MooseVariableFE.C.
{
  return _neighbor_data->dofValuesDotDot();
}
dofValuesDotDotNeighborResidual()
const DoFValue & MooseVariableFE< Real >::dofValuesDotDotNeighborResidual () const inherited
dofValuesDotDotOld()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesDotDotOld override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 588 of file MooseVariableFE.C.
{
  return _element_data->dofValuesDotDotOld();
}
dofValuesDotDotOldNeighbor()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesDotDotOldNeighbor override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 589 of file MooseVariableFE.C.
{
  return _neighbor_data->dofValuesDotDotOld();
}
dofValuesDotNeighbor()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesDotNeighbor override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 581 of file MooseVariableFE.C.
{
  return _neighbor_data->dofValuesDot();
}
dofValuesDotNeighborResidual()
const DoFValue & MooseVariableFE< Real >::dofValuesDotNeighborResidual () const inherited
dofValuesDotOld()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesDotOld override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 583 of file MooseVariableFE.C.
{
  return _element_data->dofValuesDotOld();
}
dofValuesDotOldNeighbor()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesDotOldNeighbor override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 584 of file MooseVariableFE.C.
{
  return _neighbor_data->dofValuesDotOld();
}
dofValuesDuDotDotDu()
const MooseArray< Number > & MooseVariableFE< Real >::dofValuesDuDotDotDu override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 592 of file MooseVariableFE.C.
{
  return _element_data->dofValuesDuDotDotDu();
}
dofValuesDuDotDotDuNeighbor()
const MooseArray< Number > & MooseVariableFE< Real >::dofValuesDuDotDotDuNeighbor override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 593 of file MooseVariableFE.C.
{
  return _neighbor_data->dofValuesDuDotDotDu();
}
dofValuesDuDotDu()
const MooseArray< Number > & MooseVariableFE< Real >::dofValuesDuDotDu override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 590 of file MooseVariableFE.C.
{
  return _element_data->dofValuesDuDotDu();
}
dofValuesDuDotDuNeighbor()
const MooseArray< Number > & MooseVariableFE< Real >::dofValuesDuDotDuNeighbor override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 591 of file MooseVariableFE.C.
{
  return _neighbor_data->dofValuesDuDotDu();
}
dofValuesNeighbor()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesNeighbor override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 576 of file MooseVariableFE.C.
{
  return _neighbor_data->dofValues();
}
dofValuesOld()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesOld override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 573 of file MooseVariableFE.C.
{
  return _element_data->dofValuesOld();
}
dofValuesOlder()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesOlder override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 574 of file MooseVariableFE.C.
{
  return _element_data->dofValuesOlder();
}
dofValuesOlderNeighbor()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesOlderNeighbor override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 578 of file MooseVariableFE.C.
{
  return _neighbor_data->dofValuesOlder();
}
dofValuesOldNeighbor()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesOldNeighbor override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 577 of file MooseVariableFE.C.
{
  return _neighbor_data->dofValuesOld();
}
dofValuesPreviousNL()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesPreviousNL override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 575 of file MooseVariableFE.C.
{
  return _element_data->dofValuesPreviousNL();
}
dofValuesPreviousNLNeighbor()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::dofValuesPreviousNLNeighbor override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 579 of file MooseVariableFE.C.
{
  return _neighbor_data->dofValuesPreviousNL();
}
dot() [1/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluateDot overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 110 of file MooseFunctor.h.
{
  return evaluateDot(elem, state);
}
dot() [2/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 114 of file MooseFunctor.h.
{
  return evaluateDot(elem_point, state);
}
dot() [3/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 112 of file MooseFunctor.h.
{
  return evaluateDot(elem_qp, state);
}
dot() [4/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 113 of file MooseFunctor.h.
{
  return evaluateDot(elem_side_qp, state);
}
dot() [5/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const FaceArg & face, const StateArg & state) const inherited
Definition at line 111 of file MooseFunctor.h.
{
  return evaluateDot(checkFace(face), state);
}
dot() [6/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const NodeArg & node, const StateArg & state) const inherited
Definition at line 115 of file MooseFunctor.h.
{
  return evaluateDot(node, state);
}
duDotDotDu()
const VariableValue & MooseVariableFE< Real >::duDotDotDu () const inline inherited
Definition at line 399 of file MooseVariableFE.h.
{ return _element_data->duDotDotDu(); }
duDotDotDuNeighbor()
const VariableValue & MooseVariableFE< Real >::duDotDotDuNeighbor () const inline inherited
Definition at line 493 of file MooseVariableFE.h.
{ return _neighbor_data->duDotDotDu(); }
duDotDu()
const VariableValue & MooseVariableFE< Real >::duDotDu () const inline inherited
Definition at line 398 of file MooseVariableFE.h.
{ return _element_data->duDotDu(); }
duDotDuNeighbor()
const VariableValue & MooseVariableFE< Real >::duDotDuNeighbor () const inline inherited
Definition at line 492 of file MooseVariableFE.h.
{ return _neighbor_data->duDotDu(); }
eigen() [1/2]
bool MooseVariableBase::eigen () const inline inherited
Whether or not this variable operates on an eigen kernel.
Definition at line 158 of file MooseVariableBase.h.
{ return _is_eigen; }
Referenced by EigenProblem::adjustEigenVector().
eigen() [2/2]
void MooseVariableBase::eigen (bool eigen) inline inherited
Mark this variable as an eigen var or non-eigen var.
Definition at line 163 of file MooseVariableBase.h.
{ _is_eigen = eigen; }
Referenced by MooseVariableBase::eigen().
enabled()
virtual bool MooseObject::enabled () const inline virtual inherited
Return the enabled status of the object.
Reimplemented in EigenKernel.
Definition at line 54 of file MooseObject.h.
{ return _enabled; }
Referenced by EigenKernel::enabled().
errorPrefix()
std::string MooseBaseErrorInterface::errorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for this object:
The following <error_type> occurred in the object "<name>", of type "<type>".
Definition at line 15 of file MooseBaseErrorInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the object \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseErrorInterface::mooseError(), and MooseBaseErrorInterface::mooseWarning().
evaluate() [1/6]
MooseVariableFE< Real >::ValueType MooseVariableFE< Real >::evaluate (const ElemArg & elem_arg, const StateArg & state) const final override protected virtual inherited
Evaluate the functor with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Implements Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 744 of file MooseVariableFE.C.
{
  const QMonomial qrule(elem_arg.elem->dim(), CONSTANT);
  // We can use whatever we want for the point argument since it won't be used
  const ElemQpArg elem_qp_arg{elem_arg.elem, /*qp=*/0, &qrule, Point(0, 0, 0)};
  evaluateOnElement(elem_qp_arg, state, /*cache_eligible=*/false);
  return _current_elem_qp_functor_sln[0];
}
evaluate() [2/6]
MooseVariableFE< Real >::ValueType MooseVariableFE< Real >::evaluate (const ElemPointArg & elem_point_arg, const StateArg & state) const final override protected virtual inherited
Evaluate the functor with a given element and point.
Some example implementations of this method could perform a two-term Taylor expansion using cell-centered value and gradient
Implements Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 745 of file MooseVariableFE.C.
{
  mooseAssert(elem_point_arg.elem, "We need an Elem");
  const Elem & elem = *elem_point_arg.elem;
  const auto dim = elem.dim();
  ArbitraryQuadrature qrule(dim);
  const std::vector<Point> ref_point = {FEMap::inverse_map(dim, &elem, elem_point_arg.point)};
  qrule.setPoints(ref_point);
  // We can use whatever we want for the point argument since it won't be used
  const ElemQpArg elem_qp_arg{elem_point_arg.elem, /*qp=*/0, &qrule, elem_point_arg.point};
  evaluateOnElement(elem_qp_arg, state, /*cache_eligible=*/false);
  return _current_elem_qp_functor_sln[0];
}
evaluate() [3/6]
MooseVariableFE< Real >::ValueType MooseVariableFE< Real >::evaluate (const ElemQpArg & elem_qp, const StateArg & state) const final override protected virtual inherited
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor evaluated at the requested state and space
Implements Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 741 of file MooseVariableFE.C.
{
  evaluateOnElement(elem_qp, state, /*query_cache=*/true);
  const auto qp = elem_qp.qp;
  mooseAssert(qp < _current_elem_qp_functor_sln.size(),
              "The requested " << qp << " is outside our solution size");
  return _current_elem_qp_functor_sln[qp];
}
evaluate() [4/6]
MooseVariableFE< Real >::ValueType MooseVariableFE< Real >::evaluate (const ElemSideQpArg & elem_side_qp, const StateArg & state) const final override protected virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor evaluated at the requested state and space
Implements Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 742 of file MooseVariableFE.C.
{
  evaluateOnElementSide(elem_side_qp, state, true);
  const auto qp = elem_side_qp.qp;
  mooseAssert(qp < _current_elem_side_qp_functor_sln.size(),
              "The requested " << qp << " is outside our solution size");
  return _current_elem_side_qp_functor_sln[qp];
}
evaluate() [5/6]
MooseVariableFE< Real >::ValueType MooseVariableFE< Real >::evaluate (const FaceArg & face_arg, const StateArg & state) const final override protected virtual inherited
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor evaluated at the requested state and space
Implements Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 747 of file MooseVariableFE.C.
{
  return faceEvaluate(face_arg, state, _current_elem_side_qp_functor_sln);
}
evaluate() [6/6]
MooseVariableFE< Real >::ValueType MooseVariableFE< Real >::evaluate (const NodeArg & node_arg, const StateArg & state) const final override protected virtual inherited
Implements Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 746 of file MooseVariableFE.C.
{
  mooseAssert(node_arg.node, "Must have a node");
  mooseAssert(this->hasBlocks(node_arg.subdomain_id),
              "Our variable should be defined on the requested subdomain ID");
  const Node & node = *node_arg.node;
  mooseAssert(node.n_dofs(this->_sys.number(), this->number()),
              "Our variable must have dofs on the requested node");
  const auto & soln = this->getSolution(state);
  if constexpr (std::is_same<OutputType, Real>::value)
  {
    const auto dof_number = node.dof_number(this->_sys.number(), this->number(), 0);
    ValueType ret = soln(dof_number);
    if (Moose::doDerivatives(_subproblem, _sys))
      Moose::derivInsert(ret.derivatives(), dof_number, 1);
    return ret;
  }
  else if constexpr (std::is_same<OutputType, RealVectorValue>::value)
  {
    ValueType ret;
    const auto do_derivatives = Moose::doDerivatives(_subproblem, _sys);
    for (const auto d : make_range(this->_mesh.dimension()))
    {
      const auto dof_number = node.dof_number(this->_sys.number(), this->number(), d);
      auto & component = ret(d);
      component = soln(dof_number);
      if (do_derivatives)
        Moose::derivInsert(component.derivatives(), dof_number, 1);
    }
    return ret;
  }
  else
    mooseError("RealEigenVector not yet supported for functors");
}
evaluateDot() [1/6]
MooseVariableFE< Real >::DotType MooseVariableFE< Real >::evaluateDot (const ElemArg & elem_arg, const StateArg & state) const final override protected virtual inherited
Evaluate the functor time derivative with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 757 of file MooseVariableFE.C.
{
  mooseAssert(_time_integrator && _time_integrator->dt(),
              "A time derivative is being requested but we do not have a time integrator so we'll "
              "have no idea how to compute it");
  const QMonomial qrule(elem_arg.elem->dim(), CONSTANT);
  // We can use whatever we want for the point argument since it won't be used
  const ElemQpArg elem_qp_arg{elem_arg.elem, /*qp=*/0, &qrule, Point(0, 0, 0)};
  evaluateOnElement(elem_qp_arg, state, /*cache_eligible=*/false);
  return _current_elem_qp_functor_dot[0];
}
evaluateDot() [2/6]
virtual DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateDot (const ElemPointArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor time derivative with a given element and point.
Definition at line 322 of file MooseFunctor.h.
  {
    mooseError("Element-point time derivative not implemented for functor " + functorName());
  }
evaluateDot() [3/6]
MooseVariableFE< Real >::DotType MooseVariableFE< Real >::evaluateDot (const ElemQpArg & elem_qp, const StateArg & state) const final override protected virtual inherited
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor time derivative evaluated at the requested state and space
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 754 of file MooseVariableFE.C.
{
  mooseAssert(_time_integrator && _time_integrator->dt(),
              "A time derivative is being requested but we do not have a time integrator so we'll "
              "have no idea how to compute it");
  evaluateOnElement(elem_qp, state, /*query_cache=*/true);
  const auto qp = elem_qp.qp;
  mooseAssert(qp < _current_elem_qp_functor_dot.size(),
              "The requested " << qp << " is outside our dot size");
  return _current_elem_qp_functor_dot[qp];
}
evaluateDot() [4/6]
MooseVariableFE< Real >::DotType MooseVariableFE< Real >::evaluateDot (const ElemSideQpArg & elem_side_qp, const StateArg & state) const final override protected virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor time derivative evaluated at the requested state and space
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 755 of file MooseVariableFE.C.
{
  mooseAssert(_time_integrator && _time_integrator->dt(),
              "A time derivative is being requested but we do not have a time integrator so we'll "
              "have no idea how to compute it");
  evaluateOnElementSide(elem_side_qp, state, true);
  const auto qp = elem_side_qp.qp;
  mooseAssert(qp < _current_elem_side_qp_functor_dot.size(),
              "The requested " << qp << " is outside our dot size");
  return _current_elem_side_qp_functor_dot[qp];
}
evaluateDot() [5/6]
MooseVariableFE< Real >::DotType MooseVariableFE< Real >::evaluateDot (const FaceArg & face_arg, const StateArg & state) const final override protected virtual inherited
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor time derivative evaluated at the requested state and space
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 758 of file MooseVariableFE.C.
{
  mooseAssert(_time_integrator && _time_integrator->dt(),
              "A time derivative is being requested but we do not have a time integrator so we'll "
              "have no idea how to compute it");
  return faceEvaluate(face_arg, state, _current_elem_side_qp_functor_dot);
}
evaluateDot() [6/6]
virtual DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateDot (const NodeArg & , const StateArg &) const inline protected virtual inherited
Definition at line 327 of file MooseFunctor.h.
  {
    mooseError("Time derivative at node not implemented for functor " + functorName());
  }
evaluateGradDot() [1/6]
MooseVariableFE< Real >::GradientType MooseVariableFE< Real >::evaluateGradDot (const ElemArg & elem_arg, const StateArg & state) const final override protected virtual inherited
Evaluate the functor gradient-dot with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 760 of file MooseVariableFE.C.
{
  mooseAssert(_time_integrator && _time_integrator->dt(),
              "A time derivative is being requested but we do not have a time integrator so we'll "
              "have no idea how to compute it");
  const QMonomial qrule(elem_arg.elem->dim(), CONSTANT);
  // We can use whatever we want for the point argument since it won't be used
  const ElemQpArg elem_qp_arg{elem_arg.elem, /*qp=*/0, &qrule, Point(0, 0, 0)};
  evaluateOnElement(elem_qp_arg, state, /*cache_eligible=*/false);
  return _current_elem_qp_functor_grad_dot[0];
}
evaluateGradDot() [2/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const ElemPointArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor gradient-dot with a given element and point.
Definition at line 376 of file MooseFunctor.h.
  {
    mooseError("Element-point gradient-dot not implemented for functor " + functorName());
  }
evaluateGradDot() [3/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const ElemQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient-dot evaluated at the requested state and space
Definition at line 356 of file MooseFunctor.h.
  {
    mooseError("Element quadrature point gradient-dot not implemented for functor " +
               functorName());
  }
evaluateGradDot() [4/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const ElemSideQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient-dot evaluated at the requested state and space
Definition at line 367 of file MooseFunctor.h.
  {
    mooseError("Element side quadrature point gradient-dot not implemented for functor " +
               functorName());
  }
evaluateGradDot() [5/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const FaceArg & , const StateArg &) const inline protected virtual inherited
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor gradient-dot evaluated at the requested state and space
Definition at line 346 of file MooseFunctor.h.
  {
    mooseError("Face gradient-dot not implemented for functor " + functorName());
  }
evaluateGradDot() [6/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const NodeArg & , const StateArg &) const inline protected virtual inherited
Definition at line 381 of file MooseFunctor.h.
  {
    mooseError("Gradient-dot at node not implemented for functor " + functorName());
  }
evaluateGradient() [1/6]
MooseVariableFE< Real >::GradientType MooseVariableFE< Real >::evaluateGradient (const ElemArg & elem_arg, const StateArg & state) const final override protected virtual inherited
Evaluate the functor gradient with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 752 of file MooseVariableFE.C.
{
  const QMonomial qrule(elem_arg.elem->dim(), CONSTANT);
  // We can use whatever we want for the point argument since it won't be used
  const ElemQpArg elem_qp_arg{elem_arg.elem, /*qp=*/0, &qrule, Point(0, 0, 0)};
  evaluateOnElement(elem_qp_arg, state, /*cache_eligible=*/false);
  return _current_elem_qp_functor_gradient[0];
}
evaluateGradient() [2/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradient (const ElemPointArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor gradient with a given element and point.
Definition at line 268 of file MooseFunctor.h.
  {
    mooseError("Element-point gradient not implemented for functor " + functorName());
  }
evaluateGradient() [3/6]
MooseVariableFE< Real >::GradientType MooseVariableFE< Real >::evaluateGradient (const ElemQpArg & elem_qp, const StateArg & state) const override protected virtual inherited
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient evaluated at the requested state and space
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 749 of file MooseVariableFE.C.
{
  evaluateOnElement(elem_qp, state, /*query_cache=*/true);
  const auto qp = elem_qp.qp;
  mooseAssert(qp < _current_elem_qp_functor_gradient.size(),
              "The requested " << qp << " is outside our gradient size");
  return _current_elem_qp_functor_gradient[qp];
}
evaluateGradient() [4/6]
MooseVariableFE< Real >::GradientType MooseVariableFE< Real >::evaluateGradient (const ElemSideQpArg & elem_side_qp, const StateArg & state) const final override protected virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient evaluated at the requested state and space
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 750 of file MooseVariableFE.C.
{
  evaluateOnElementSide(elem_side_qp, state, true);
  const auto qp = elem_side_qp.qp;
  mooseAssert(qp < _current_elem_side_qp_functor_gradient.size(),
              "The requested " << qp << " is outside our gradient size");
  return _current_elem_side_qp_functor_gradient[qp];
}
evaluateGradient() [5/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradient (const FaceArg & , const StateArg &) const inline protected virtual inherited
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor gradient evaluated at the requested state and space
Reimplemented in MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 239 of file MooseFunctor.h.
  {
    mooseError("Face gradient not implemented for functor " + functorName());
  }
evaluateGradient() [6/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradient (const NodeArg & , const StateArg &) const inline protected virtual inherited
Definition at line 273 of file MooseFunctor.h.
  {
    mooseError("Gradient at node not implemented for functor " + functorName());
  }
evaluateOnElement()
void MooseVariableFE< Real >::evaluateOnElement (const ElemQpArg & elem_qp, const StateArg & state, bool cache_eligible) const private inherited
Evaluate solution and gradient for the elem_qp argument.
Definition at line 782 of file MooseVariableFE.C.
{
  mooseAssert(this->hasBlocks(elem_qp.elem->subdomain_id()),
              "Variable " + this->name() + " doesn't exist on block " +
                  std::to_string(elem_qp.elem->subdomain_id()));
  const Elem * const elem = elem_qp.elem;
  if (!cache_eligible || (elem != _current_elem_qp_functor_elem))
  {
    const QBase * const qrule_template = elem_qp.qrule;
    using FEBaseType = typename FEBaseHelper<OutputType>::type;
    std::unique_ptr<FEBaseType> fe(FEBaseType::build(elem->dim(), _fe_type));
    auto qrule = qrule_template->clone();
    const auto & phi = fe->get_phi();
    const auto & dphi = fe->get_dphi();
    fe->attach_quadrature_rule(qrule.get());
    fe->reinit(elem);
    computeSolution(elem,
                    qrule->n_points(),
                    state,
                    phi,
                    _current_elem_qp_functor_sln,
                    dphi,
                    _current_elem_qp_functor_gradient,
                    _current_elem_qp_functor_dot,
                    _current_elem_qp_functor_grad_dot);
  }
  if (cache_eligible)
    _current_elem_qp_functor_elem = elem;
  else
    // These evaluations are not eligible for caching, e.g. maybe this is a single point quadrature
    // rule evaluation at an arbitrary point and we don't want those evaluations to potentially be
    // re-used when this function is called with a standard quadrature rule or a different point
    _current_elem_qp_functor_elem = nullptr;
}
evaluateOnElementSide()
void MooseVariableFE< Real >::evaluateOnElementSide (const ElemSideQpArg & elem_side_qp, const StateArg & state, bool cache_eligible) const private inherited
Evaluate solution and gradient for the elem_side_qp argument.
Definition at line 787 of file MooseVariableFE.C.
{
  mooseAssert(this->hasBlocks(elem_side_qp.elem->subdomain_id()),
              "Variable " + this->name() + " doesn't exist on block " +
                  std::to_string(elem_side_qp.elem->subdomain_id()));
  const Elem * const elem = elem_side_qp.elem;
  const auto side = elem_side_qp.side;
  if (!cache_eligible || elem != _current_elem_side_qp_functor_elem_side.first ||
      side != _current_elem_side_qp_functor_elem_side.second)
  {
    const QBase * const qrule_template = elem_side_qp.qrule;
    using FEBaseType = typename FEBaseHelper<OutputType>::type;
    std::unique_ptr<FEBaseType> fe(FEBaseType::build(elem->dim(), _fe_type));
    auto qrule = qrule_template->clone();
    const auto & phi = fe->get_phi();
    const auto & dphi = fe->get_dphi();
    fe->attach_quadrature_rule(qrule.get());
    fe->reinit(elem, side);
    computeSolution(elem,
                    qrule->n_points(),
                    state,
                    phi,
                    _current_elem_side_qp_functor_sln,
                    dphi,
                    _current_elem_side_qp_functor_gradient,
                    _current_elem_side_qp_functor_dot,
                    _current_elem_side_qp_functor_grad_dot);
  }
  if (cache_eligible)
    _current_elem_side_qp_functor_elem_side = std::make_pair(elem, side);
  else
    // These evaluations are not eligible for caching, e.g. maybe this is a single point quadrature
    // rule evaluation at an arbitrary point and we don't want those evaluations to potentially be
    // re-used when this function is called with a standard quadrature rule or a different point
    _current_elem_side_qp_functor_elem_side = std::make_pair(nullptr, libMesh::invalid_uint);
}
faceEvaluate()
MooseVariableFE< Real >::ValueType MooseVariableFE< Real >::faceEvaluate (const FaceArg & face_arg, const StateArg & state, const std::vector< ValueType > & cache_data) const protected inherited
A common method that both evaluate(FaceArg) and evaluateDot(FaceArg) can call.
A value evaluation vs dot evaluation is delineated via the passed-in cache_data, e.g. if the passed-in cache data is the sln data member then this will return a value evaluation and if the cache data is the dot data member then this will return a dot evaluation
Definition at line 739 of file MooseVariableFE.C.
{
  const QMonomial qrule(face_arg.fi->elem().dim() - 1, CONSTANT);
  auto side_evaluate =
      [this, &qrule, &state, &cache_data](const Elem * const elem, const unsigned int side)
  {
    // We can use whatever we want for the point argument since it won't be used
    const ElemSideQpArg elem_side_qp_arg{elem, side, /*qp=*/0, &qrule, Point(0, 0, 0)};
    evaluateOnElementSide(elem_side_qp_arg, state, /*cache_eligible=*/false);
    return cache_data[0];
  };
  const auto continuity = this->getContinuity();
  const bool on_elem = !face_arg.face_side || (face_arg.face_side == face_arg.fi->elemPtr());
  const bool on_neighbor =
      !face_arg.face_side || (face_arg.face_side == face_arg.fi->neighborPtr());
  if (on_neighbor)
    mooseAssert(
        face_arg.fi->neighborPtr(),
        "If we are signaling we should evaluate on the neighbor, we better have a neighbor");
  // Only do multiple evaluations if we are not continuous and we are on an internal face
  if ((continuity != C_ZERO && continuity != C_ONE) && on_elem && on_neighbor)
    return (side_evaluate(face_arg.fi->elemPtr(), face_arg.fi->elemSideID()) +
            side_evaluate(face_arg.fi->neighborPtr(), face_arg.fi->neighborSideID())) /
           2;
  else if (on_elem)
    return side_evaluate(face_arg.fi->elemPtr(), face_arg.fi->elemSideID());
  else if (on_neighbor)
    return side_evaluate(face_arg.fi->neighborPtr(), face_arg.fi->neighborSideID());
  else
    mooseError(
        "Attempted to evaluate a moose finite element variable on a face where it is not defined");
}
feType()
const FEType & MooseVariableBase::feType () const inline inherited
Get the type of finite element object.
Definition at line 54 of file MooseVariableBase.h.
{ return _fe_type; }
Referenced by SetupResidualDebugAction::act(), ADDGKernel::ADDGKernel(), Assembly::adGradPhi(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), BoundsAuxBase::BoundsAuxBase(), BuildArrayVariableAux::BuildArrayVariableAux(), TagAuxBase< T >::checkCoupledVariable(), GapValueAux::computeValue(), CopyValueAux::CopyValueAux(), DGKernel::DGKernel(), MultiAppNearestNodeTransfer::execute(), moose::internal::incompatVarMsg(), AdvancedOutput::initAvailableLists(), MultiAppProjectionTransfer::initialSetup(), AdvancedOutput::initShowHideLists(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), MeshDivisionAux::MeshDivisionAux(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodalBC::NodalBC(), NodalKernel::NodalKernel(), SolutionUserObject::pointValueWrapper(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), MultiAppDofCopyTransfer::transfer(), and VectorNodalBC::VectorNodalBC().
fieldType()
Moose::VarFieldType MooseVariableFE< Real >::fieldType override virtual inherited
Filed type of this variable.
Implements MooseVariableFieldBase.
Definition at line 151 of file MooseVariableFE.C.
{
  if (std::is_same<OutputType, Real>::value)
    return Moose::VarFieldType::VAR_FIELD_STANDARD;
  else if (std::is_same<OutputType, RealVectorValue>::value)
    return Moose::VarFieldType::VAR_FIELD_VECTOR;
  else if (std::is_same<OutputType, RealEigenVector>::value)
    return Moose::VarFieldType::VAR_FIELD_ARRAY;
  else
    mooseError("Unknown variable field type");
}
functorName()
const MooseFunctorName & Moose::FunctorBase< Moose::ADType< OutputType >::type >::functorName () const inline inherited
Return the functor name.
Definition at line 77 of file MooseFunctor.h.
{ return _functor_name; }
getBlockCoordSystem()
Moose::CoordinateSystemType BlockRestrictable::getBlockCoordSystem () protected inherited
Check if the blocks this object operates on all have the same coordinate system, and if so return it.
Definition at line 311 of file BlockRestrictable.C.
{
  if (!_blk_mesh)
    mooseError("No mesh available in BlockRestrictable::checkCoordSystem()");
  if (!_blk_feproblem)
    mooseError("No problem available in BlockRestrictable::checkCoordSystem()");
  const auto & subdomains = blockRestricted() ? blockIDs() : meshBlockIDs();
  if (subdomains.empty())
    mooseError("No subdomains found in the problem.");
  // make sure all subdomains are using the same coordinate system
  auto coord_system = _blk_feproblem->getCoordSystem(*subdomains.begin());
  for (auto subdomain : subdomains)
    if (_blk_feproblem->getCoordSystem(subdomain) != coord_system)
      mooseError("This object requires all subdomains to have the same coordinate system.");
  return coord_system;
}
getCheckedPointerParam()
template<typename T > T MooseBaseParameterInterface::getCheckedPointerParam (const std::string & name, const std::string & error_string = "") const inherited
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
The template parameter must be a pointer or an error will be thrown.
Definition at line 264 of file MooseBaseParameterInterface.h.
{
  return parameters().getCheckedPointerParam<T>(name, error_string);
}
getContinuity()
FEContinuity MooseVariableFE< Real >::getContinuity () const inline override virtual inherited
Return the continuity of this variable.
Reimplemented from MooseVariableBase.
Definition at line 150 of file MooseVariableFE.h.
{ return _element_data->getContinuity(); };
getDataFileName()
std::string DataFileInterface< MooseObject >::getDataFileName (const std::string & param) const inherited
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
relative to the input file directory
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
relative to the input file directory
Definition at line 34 of file DataFileInterface.C.
{
  {
    const auto & absolute_path = _parent.template getParam<FileName>(param);
    if (MooseUtils::checkFileReadable(absolute_path, false, false, false))
    {
      _parent.paramInfo(param, "Data file '", absolute_path, "' found relative to the input file.");
      return absolute_path;
    }
  }
  const auto & relative_path = _parent.parameters().rawParamVal(param);
  return getDataFileNameByName(relative_path, &param);
}
getDataFileNameByName()
std::string DataFileInterface< MooseObject >::getDataFileNameByName (const std::string & name, const std::string * param = nullptr) const inherited
Returns the path of a data file for a given relative file path.
This can be used for hardcoded datafile names and will search the same locations as getDataFileName. The optional param pointer can be used to turn the mooseErrors this function emits into paramErrors
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
Definition at line 42 of file DataFileInterface.C.
{
  const auto share_dir = MooseUtils::pathjoin(Moose::getExecutablePath(), "..", "share");
  if (MooseUtils::pathIsDirectory(share_dir))
  {
    const auto dirs = MooseUtils::listDir(share_dir, false);
    for (const auto & data_dir : dirs)
    {
      const auto path = MooseUtils::pathjoin(data_dir, "data", relative_path);
      if (MooseUtils::checkFileReadable(path, false, false, false))
      {
        if (param)
          _parent.paramInfo(
              *param, "Data file '", path, "' found in an installed app distribution.");
        else
          mooseInfo("Data file '", path, "' found in an installed app distribution.");
        return path;
      }
    }
  }
  for (const auto & data_dir : Registry::getRegistry().getDataFilePaths())
  {
    const auto path = MooseUtils::pathjoin(data_dir, relative_path);
    if (MooseUtils::checkFileReadable(path, false, false, false))
    {
      if (param)
        _parent.paramInfo(*param, "Data file '", path, "' found in a source repository.");
      else
        mooseInfo("Data file '", path, "' found in a source repository.");
      return path;
    }
  }
  mooseException(param ? _parent.parameters().inputLocation(*param) : _parent.name(),
                 ": Unable to find data file '",
                 relative_path,
                 "' anywhere");
}
getDofIndices()
void MooseVariableFE< Real >::getDofIndices (const Elem * elem, std::vector< dof_id_type > & dof_indices) const override virtual inherited
Reimplemented from MooseVariableBase.
Definition at line 177 of file MooseVariableFE.C.
{
  _element_data->getDofIndices(elem, dof_indices);
}
getElementalValue()
MooseVariableFE< Real >::OutputData MooseVariableFE< Real >::getElementalValue (const Elem * elem, unsigned int idx = 0) const inherited
Get the current value of this variable on an element.
Parameters
[in] elem Element at which to get value
[in] idx Local index of this variable's element DoFs
Returns
Variable value
Definition at line 539 of file MooseVariableFE.C.
{
  return _element_data->getElementalValue(elem, Moose::Current, idx);
}
getElementalValueOld()
MooseVariableFE< Real >::OutputData MooseVariableFE< Real >::getElementalValueOld (const Elem * elem, unsigned int idx = 0) const inherited
Get the old value of this variable on an element.
Parameters
[in] elem Element at which to get value
[in] idx Local index of this variable's element DoFs
Returns
Variable value
Definition at line 546 of file MooseVariableFE.C.
{
  return _element_data->getElementalValue(elem, Moose::Old, idx);
}
getElementalValueOlder()
MooseVariableFE< Real >::OutputData MooseVariableFE< Real >::getElementalValueOlder (const Elem * elem, unsigned int idx = 0) const inherited
Get the older value of this variable on an element.
Parameters
[in] elem Element at which to get value
[in] idx Local index of this variable's element DoFs
Returns
Variable value
Definition at line 553 of file MooseVariableFE.C.
{
  return _element_data->getElementalValue(elem, Moose::Older, idx);
}
getExecuteOnEnum()
const ExecFlagEnum & SetupInterface::getExecuteOnEnum () const inherited
Return the execute on MultiMooseEnum for this object.
Definition at line 65 of file SetupInterface.C.
{
  return _execute_enum;
}
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), MultiAppTransfer::checkMultiAppExecuteOn(), IntegralPreservingFunctionIC::initialSetup(), MultiAppConservativeTransfer::initialSetup(), Terminator::initialSetup(), ElementReporter::shouldStore(), GeneralReporter::shouldStore(), and NodalReporter::shouldStore().
getGradient()
OutputTools< Real >::OutputGradient MooseVariableFE< Real >::getGradient (const Elem * elem, const std::vector< std::vector< typename OutputTools< Real >::OutputShapeGradient > > & grad_phi) const inherited
Compute the variable gradient value at a point on an element.
Parameters
elem The element we are computing on
phi Evaluated shape functions at a point
Returns
The variable gradient value
Definition at line 629 of file MooseVariableFE.C.
{
  std::vector<dof_id_type> dof_indices;
  this->_dof_map.dof_indices(elem, dof_indices, _var_num);
  typename OutputTools<OutputType>::OutputGradient value;
  if (isNodal())
  {
    for (unsigned int i = 0; i < dof_indices.size(); ++i)
    {
      // The zero index is because we only have one point that the phis are evaluated at
      value += grad_phi[i][0] * (*this->_sys.currentSolution())(dof_indices[i]);
    }
  }
  else
  {
    mooseAssert(dof_indices.size() == 1, "Wrong size for dof indices");
    value = 0.0;
  }
  return value;
}
getMooseApp()
MooseApp & MooseBase::getMooseApp () const inline inherited
Get the MooseApp this class is associated with.
Definition at line 35 of file MooseBase.h.
{ return _app; }
Referenced by ReporterTransferInterface::checkHasReporterValue(), Coupleable::checkWritableVar(), MooseBaseParameterInterface::connectControllableParams(), Coupleable::Coupleable(), MortarData::createMortarInterface(), EigenProblem::doFreeNonlinearPowerIterations(), Terminator::execute(), FEProblemSolve::FEProblemSolve(), SolutionInvalidInterface::flagInvalidSolutionInternal(), MaterialPropertyInterface::MaterialPropertyInterface(), MooseVariableDataFV< OutputType >::MooseVariableDataFV(), ProgressOutput::output(), MooseBaseParameterInterface::paramError(), PetscOutputInterface::petscLinearOutput(), PetscOutputInterface::petscNonlinearOutput(), PetscOutputInterface::PetscOutputInterface(), PostprocessorInterface::postprocessorsAdded(), MultiApp::preTransfer(), Reporter::Reporter(), ReporterInterface::reportersAdded(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
getNodalValue()
MooseVariableFE< Real >::OutputData MooseVariableFE< Real >::getNodalValue (const Node & node) const inherited
Get the value of this variable at given node.
Definition at line 524 of file MooseVariableFE.C.
{
  return _element_data->getNodalValue(node, Moose::Current);
}
getNodalValueOld()
MooseVariableFE< Real >::OutputData MooseVariableFE< Real >::getNodalValueOld (const Node & node) const inherited
Get the old value of this variable at given node.
Definition at line 528 of file MooseVariableFE.C.
{
  return _element_data->getNodalValue(node, Moose::Old);
}
getNodalValueOlder()
MooseVariableFE< Real >::OutputData MooseVariableFE< Real >::getNodalValueOlder (const Node & node) const inherited
Get the t-2 value of this variable at given node.
Definition at line 532 of file MooseVariableFE.C.
{
  return _element_data->getNodalValue(node, Moose::Older);
}
getOutputs()
const std::set< OutputName > & OutputInterface::getOutputs () inherited
Get the list of output objects that this class is restricted.
Returns
A set of OutputNames
Definition at line 94 of file OutputInterface.C.
{
  return _oi_outputs;
}
getParam() [1/2]
template<typename T > const T & MooseBaseParameterInterface::getParam (const std::string & name) const inherited
Retrieve a parameter for the object.
Parameters
name The name of the parameter
Returns
The value of the parameter
Definition at line 200 of file MooseBaseParameterInterface.h.
{
  return InputParameters::getParamHelper(name, _pars, static_cast<T *>(0));
}
Referenced by AddGeneralReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddPeriodicBCAction::act(), CreateDisplacedProblemAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), ConstraintWarehouse::addObject(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), ADNodalKernel::ADNodalKernel(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), PiecewiseTabularBase::buildFromJSON(), Console::Console(), FEProblemBase::createTagSolutions(), AccumulateReporter::declareLateValues(), DerivativeParsedMaterialTempl< is_ad >::DerivativeParsedMaterialTempl(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EigenKernel::EigenKernel(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), GenericConstantRankTwoTensorTempl< is_ad >::GenericConstantRankTwoTensorTempl(), MooseApp::getCheckpointDirectories(), ExecutorInterface::getExecutor(), AdvancedOutput::init(), IterationAdaptiveDT::init(), TimeSequenceStepper::init(), AttribThread::initFrom(), AttribSysNum::initFrom(), AttribResidualObject::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), Console::initialSetup(), IterationAdaptiveDT::limitDTToPostprocessorValue(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MortarConsumerInterface::MortarConsumerInterface(), NestedDivision::NestedDivision(), ConsoleUtils::outputExecutionInformation(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedMaterialTempl< is_ad >::ParsedMaterialTempl(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), ParsedODEKernel::ParsedODEKernel(), ParsedPostprocessor::ParsedPostprocessor(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), Moose::FV::setInterpolationMethod(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), TimePeriod::TimePeriod(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and VectorOfPostprocessors::VectorOfPostprocessors().
getParam() [2/2]
template<typename T1 , typename T2 > std::vector< std::pair< T1, T2 > > MooseBaseParameterInterface::getParam (const std::string & param1, const std::string & param2) const inherited
Retrieve two parameters and provide pair of parameters for the object.
Parameters
param1 The name of first parameter
param2 The name of second parameter
Returns
Vector of pairs of first and second parameters
Definition at line 257 of file MooseBaseParameterInterface.h.
{
  return _pars.get<T1, T2>(param1, param2);
}
getRenamedParam()
template<typename T > const T & MooseBaseParameterInterface::getRenamedParam (const std::string & old_name, const std::string & new_name) const inherited
Retrieve a renamed parameter for the object.
This helper makes sure we check both names before erroring, and that only one parameter is passed to avoid silent errors
Parameters
old_name the old name for the parameter
new_name the new name for the parameter
Definition at line 207 of file MooseBaseParameterInterface.h.
{
  // this enables having a default on the new parameter but bypassing it with the old one
  // Most important: accept new parameter
  if (isParamSetByUser(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Second most: accept old parameter
  else if (isParamValid(old_name) && !isParamSetByUser(new_name))
    return InputParameters::getParamHelper(old_name, _pars, static_cast<T *>(0));
  // Third most: accept default for new parameter
  else if (isParamValid(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Refuse: no default, no value passed
  else if (!isParamValid(old_name) && !isParamValid(new_name))
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' is being retrieved without being set.\n"
               "Did you misspell it?");
  // Refuse: both old and new parameters set by user
  else
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' may not be provided alongside former parameter '" + old_name + "'");
}
getSolution()
template<typename OutputType > const NumericVector< Number > & MooseVariableField< OutputType >::getSolution (const Moose::StateArg & state) const protected inherited
Get the solution corresponding to the provided state.
Definition at line 60 of file MooseVariableField.C.
{
  // It's not safe to use solutionState(0) because it returns the libMesh System solution member
  // which is wrong during things like finite difference Jacobian evaluation, e.g. when PETSc
  // perturbs the solution vector we feed these perturbations into the current_local_solution
  // while the libMesh solution is frozen in the non-perturbed state
  return (state.state == 0) ? *this->_sys.currentSolution()
                            : this->_sys.solutionState(state.state, state.iteration_type);
}
getValue()
Real MooseVariableFE< Real >::getValue (const Elem * elem, const std::vector< std::vector< OutputShape > > & phi) const inherited
Compute the variable value at a point on an element.
Parameters
elem The element we are computing on
phi Evaluated shape functions at a point
Returns
The variable value
Definition at line 621 of file MooseVariableFE.C.
{
  std::vector<dof_id_type> dof_indices;
  this->_dof_map.dof_indices(elem, dof_indices, _var_num);
  OutputType value = 0;
  if (isNodal())
  {
    mooseAssert(dof_indices.size() == phi.size(),
                "The number of shapes does not match the number of dof indices on the elem");
    for (unsigned int i = 0; i < dof_indices.size(); ++i)
    {
      // The zero index is because we only have one point that the phis are evaluated at
      value += phi[i][0] * (*this->_sys.currentSolution())(dof_indices[i]);
    }
  }
  else
  {
    mooseAssert(dof_indices.size() == 1, "Wrong size for dof indices");
    value = (*this->_sys.currentSolution())(dof_indices[0]);
  }
  return value;
}
gradDot() [1/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluateGradDot overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 123 of file MooseFunctor.h.
{
  return evaluateGradDot(elem, state);
}
gradDot() [2/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 127 of file MooseFunctor.h.
{
  return evaluateGradDot(elem_point, state);
}
gradDot() [3/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 125 of file MooseFunctor.h.
{
  return evaluateGradDot(elem_qp, state);
}
gradDot() [4/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 126 of file MooseFunctor.h.
{
  return evaluateGradDot(elem_side_qp, state);
}
gradDot() [5/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const FaceArg & face, const StateArg & state) const inherited
Definition at line 124 of file MooseFunctor.h.
{
  return evaluateGradDot(checkFace(face), state);
}
gradDot() [6/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const NodeArg & node, const StateArg & state) const inherited
Definition at line 128 of file MooseFunctor.h.
{
  return evaluateGradDot(node, state);
}
gradient() [1/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluateGradient overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 97 of file MooseFunctor.h.
{
  return evaluateGradient(elem, state);
}
gradient() [2/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 101 of file MooseFunctor.h.
{
  return evaluateGradient(elem_point, state);
}
gradient() [3/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 99 of file MooseFunctor.h.
{
  return evaluateGradient(elem_qp, state);
}
gradient() [4/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 100 of file MooseFunctor.h.
{
  return evaluateGradient(elem_side_qp, state);
}
gradient() [5/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const FaceArg & face, const StateArg & state) const inherited
Definition at line 98 of file MooseFunctor.h.
{
  return evaluateGradient(checkFace(face), state);
}
gradient() [6/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const NodeArg & node, const StateArg & state) const inherited
Definition at line 102 of file MooseFunctor.h.
{
  return evaluateGradient(node, state);
}
gradPhi()
const FieldVariablePhiGradient & MooseVariableFE< Real >::gradPhi () const inline final override virtual inherited
Return the gradients of the variable's elemental shape functions.
Implements MooseVariableField< OutputType >.
Definition at line 195 of file MooseVariableFE.h.
  {
    return _element_data->gradPhi();
  }
gradPhiFace()
const FieldVariablePhiGradient & MooseVariableFE< Real >::gradPhiFace () const inline final override virtual inherited
Return the gradients of the variable's shape functions on an element face.
Implements MooseVariableField< OutputType >.
Definition at line 208 of file MooseVariableFE.h.
  {
    return _element_data->gradPhiFace();
  }
gradPhiFaceNeighbor()
const FieldVariablePhiGradient & MooseVariableFE< Real >::gradPhiFaceNeighbor () const inline final override virtual inherited
Return the gradients of the variable's shape functions on a neighboring element face.
Implements MooseVariableField< OutputType >.
Definition at line 237 of file MooseVariableFE.h.
  {
    return _neighbor_data->gradPhiFace();
  }
gradPhiLower()
const FieldVariablePhiGradient & MooseVariableFE< Real >::gradPhiLower () const inline inherited
Definition at line 250 of file MooseVariableFE.h.
{ return _lower_data->gradPhi(); }
gradPhiNeighbor()
const FieldVariablePhiGradient & MooseVariableFE< Real >::gradPhiNeighbor () const inline final override virtual inherited
Return the gradients of the variable's shape functions on a neighboring element.
Implements MooseVariableField< OutputType >.
Definition at line 221 of file MooseVariableFE.h.
  {
    return _neighbor_data->gradPhi();
  }
gradSln()
const FieldVariableGradient & MooseVariableFE< Real >::gradSln () const inline override virtual inherited
element gradients
Implements MooseVariableField< OutputType >.
Definition at line 294 of file MooseVariableFE.h.
  {
    return _element_data->gradSln(Moose::Current);
  }
gradSlnDot()
const FieldVariableGradient & MooseVariableFE< Real >::gradSlnDot () const inline inherited
element gradient dots
Definition at line 312 of file MooseVariableFE.h.
{ return _element_data->gradSlnDot(); }
gradSlnDotDot()
const FieldVariableGradient & MooseVariableFE< Real >::gradSlnDotDot () const inline inherited
Definition at line 313 of file MooseVariableFE.h.
{ return _element_data->gradSlnDotDot(); }
gradSlnNeighbor()
const FieldVariableGradient & MooseVariableFE< Real >::gradSlnNeighbor () const inline override virtual inherited
neighbor solution gradients
Implements MooseVariableField< OutputType >.
Definition at line 417 of file MooseVariableFE.h.
  {
    return _neighbor_data->gradSln(Moose::Current);
  }
gradSlnNeighborDot()
const FieldVariableGradient & MooseVariableFE< Real >::gradSlnNeighborDot () const inline inherited
neighbor grad dots
Definition at line 435 of file MooseVariableFE.h.
{ return _neighbor_data->gradSlnDot(); }
gradSlnNeighborDotDot()
const FieldVariableGradient & MooseVariableFE< Real >::gradSlnNeighborDotDot () const inline inherited
Definition at line 436 of file MooseVariableFE.h.
  {
    return _neighbor_data->gradSlnDotDot();
  }
gradSlnOld()
const FieldVariableGradient & MooseVariableFE< Real >::gradSlnOld () const inline override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 298 of file MooseVariableFE.h.
  {
    return _element_data->gradSln(Moose::Old);
  }
gradSlnOlder()
const FieldVariableGradient & MooseVariableFE< Real >::gradSlnOlder () const inline inherited
Definition at line 302 of file MooseVariableFE.h.
  {
    return _element_data->gradSln(Moose::Older);
  }
gradSlnOlderNeighbor()
const FieldVariableGradient & MooseVariableFE< Real >::gradSlnOlderNeighbor () const inline inherited
Definition at line 425 of file MooseVariableFE.h.
  {
    return _neighbor_data->gradSln(Moose::Older);
  }
gradSlnOldNeighbor()
const FieldVariableGradient & MooseVariableFE< Real >::gradSlnOldNeighbor () const inline override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 421 of file MooseVariableFE.h.
  {
    return _neighbor_data->gradSln(Moose::Old);
  }
gradSlnPreviousNL()
const FieldVariableGradient & MooseVariableFE< Real >::gradSlnPreviousNL () const inline inherited
Definition at line 306 of file MooseVariableFE.h.
  {
    return _element_data->gradSln(Moose::PreviousNL);
  }
gradSlnPreviousNLNeighbor()
const FieldVariableGradient & MooseVariableFE< Real >::gradSlnPreviousNLNeighbor () const inline inherited
Definition at line 429 of file MooseVariableFE.h.
  {
    return _neighbor_data->gradSln(Moose::PreviousNL);
  }
hasBlockMaterialProperty()
template<typename T , bool is_ad> bool BlockRestrictable::hasBlockMaterialProperty (const std::string & prop_name) inherited
Check if a material property is valid for all blocks of this object.
This method returns true if the supplied property name has been declared in a Material object on the block ids for this object.
Template Parameters
T The type of material property
Parameters
prop_name the name of the property to query
Returns
true if the property exists for all block ids of the object, otherwise false
See also
Material::hasBlockMaterialProperty
Definition at line 264 of file BlockRestrictable.h.
{
  mooseAssert(_blk_material_data != NULL, "MaterialData pointer is not defined");
  return hasBlockMaterialPropertyHelper(prop_name) &&
         _blk_material_data->haveGenericProperty<T, is_ad>(prop_name);
}
hasBlockMaterialPropertyHelper()
bool BlockRestrictable::hasBlockMaterialPropertyHelper (const std::string & prop_name) protected virtual inherited
A helper method to allow the Material object to specialize the behavior of hasBlockMaterialProperty.
It also avoid circular #include problems.
See also
hasBlockMaterialProperty
Definition at line 275 of file BlockRestrictable.C.
{
  // Reference to MaterialWarehouse for testing and retrieving block ids
  const MaterialWarehouse & warehouse = _blk_feproblem->getMaterialWarehouse();
  // Complete set of ids that this object is active
  const std::set<SubdomainID> & ids = blockRestricted() ? blockIDs() : meshBlockIDs();
  // Loop over each id for this object
  for (const auto & id : ids)
  {
    // Storage of material properties that have been DECLARED on this id
    std::set<std::string> declared_props;
    // If block materials exist, populated the set of properties that were declared
    if (warehouse.hasActiveBlockObjects(id))
    {
      const std::vector<std::shared_ptr<MaterialBase>> & mats = warehouse.getActiveBlockObjects(id);
      for (const auto & mat : mats)
      {
        const std::set<std::string> & mat_props = mat->getSuppliedItems();
        declared_props.insert(mat_props.begin(), mat_props.end());
      }
    }
    // If the supplied property is not in the list of properties on the current id, return false
    if (declared_props.find(prop_name) == declared_props.end())
      return false;
  }
  // If you get here the supplied property is defined on all blocks
  return true;
}
Referenced by BlockRestrictable::hasBlockMaterialProperty().
hasBlocks() [1/5]
bool BlockRestrictable::hasBlocks (const std::set< SubdomainID > & ids) const inherited
Test if the supplied set of block ids are valid for this object.
Parameters
ids A std::set of SubdomainIDs to check
Returns
True if all of the given ids are found within the ids for this object
See also
isSubset
Definition at line 237 of file BlockRestrictable.C.
{
  if (_blk_ids.empty() || _blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return true;
  else
    return std::includes(_blk_ids.begin(), _blk_ids.end(), ids.begin(), ids.end());
}
hasBlocks() [2/5]
bool BlockRestrictable::hasBlocks (const std::vector< SubdomainID > & ids) const inherited
Test if the supplied vector block ids are valid for this object.
Parameters
ids A vector of SubdomainIDs ids to check
Returns
True if all of the given ids are found within the ids for this object
Definition at line 230 of file BlockRestrictable.C.
{
  std::set<SubdomainID> ids_set(ids.begin(), ids.end());
  return hasBlocks(ids_set);
}
hasBlocks() [3/5]
bool BlockRestrictable::hasBlocks (const std::vector< SubdomainName > & names) const inherited
Test if the supplied vector of block names are valid for this object.
Parameters
names A vector of SubdomainNames to check
Returns
True if the given ids are valid for this object
Definition at line 215 of file BlockRestrictable.C.
{
  return hasBlocks(_blk_mesh->getSubdomainIDs(names));
}
hasBlocks() [4/5]
template<typename OutputType > bool MooseVariableField< OutputType >::hasBlocks (const SubdomainID) const inline override virtual inherited
Returns whether the functor is defined on this block.
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 370 of file MooseVariableField.h.
{ return BlockRestrictable::hasBlocks(id); }
Referenced by Coupleable::checkWritableVar(), GradientJumpIndicator::computeQpIntegral(), ProjectionAux::computeValue(), Moose::FV::determineElemOneAndTwo(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), and FVInterfaceKernel::FVInterfaceKernel().
hasBlocks() [5/5]
bool BlockRestrictable::hasBlocks (const SubdomainName & name) const inherited
Test if the supplied block name is valid for this object.
Parameters
name A SubdomainName to check
Returns
True if the given id is valid for this object
Definition at line 205 of file BlockRestrictable.C.
{
  // Create a vector and utilize the getSubdomainIDs function, which
  // handles the ANY_BLOCK_ID (getSubdomainID does not)
  std::vector<SubdomainName> names(1);
  names[0] = name;
  return hasBlocks(_blk_mesh->getSubdomainIDs(names));
}
Referenced by DiracKernelBase::addPoint(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), DomainUserObject::checkVariable(), ComputeJacobianThread::compute(), DomainUserObject::DomainUserObject(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), ExtraIDIntegralVectorPostprocessor::execute(), MeshDivisionFunctorReductionVectorPostprocessor::execute(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), MooseVariableField< OutputType >::hasBlocks(), BlockRestrictable::hasBlocks(), FVFluxKernel::hasFaceSide(), and PointwiseRenormalizeVector::PointwiseRenormalizeVector().
hasDoFsOnNodes()
bool MooseVariableFE< Real >::hasDoFsOnNodes () const inline override virtual inherited
Does this variable have DoFs on nodes.
Returns
true if it does, false if not.
Reimplemented from MooseVariableBase.
Definition at line 149 of file MooseVariableFE.h.
{ return _element_data->hasDoFsOnNodes(); }
hasFaceSide()
bool Moose::FunctorBase< Moose::ADType< OutputType >::type >::hasFaceSide (const FaceInfo & fi, const bool fi_elem_side) const override virtual inherited
Implements FaceArgInterface.
Definition at line 169 of file MooseFunctor.h.
{
  if (fi_elem_side)
    return hasBlocks(fi.elem().subdomain_id());
  else
    return fi.neighborPtr() && hasBlocks(fi.neighbor().subdomain_id());
}
increment()
const FieldVariableValue & MooseVariableFE< Real >::increment () const inline inherited
Definition at line 268 of file MooseVariableFE.h.
{ return _element_data->increment(); }
initializeBlockRestrictable()
void BlockRestrictable::initializeBlockRestrictable (const MooseObject * moose_object) protected inherited
An initialization routine needed for dual constructors.
Definition at line 74 of file BlockRestrictable.C.
{
  // If the mesh pointer is not defined, but FEProblemBase is, get it from there
  if (_blk_feproblem != NULL && _blk_mesh == NULL)
    _blk_mesh = &_blk_feproblem->mesh();
  // Check that the mesh pointer was defined, it is required for this class to operate
  if (_blk_mesh == NULL)
    mooseError("The input parameters must contain a pointer to FEProblem via '_fe_problem' or a "
               "pointer to the MooseMesh via '_mesh'");
  // Populate the MaterialData pointer
  if (_blk_feproblem != NULL)
    _blk_material_data = &_blk_feproblem->getMaterialData(Moose::BLOCK_MATERIAL_DATA, _blk_tid);
  // The 'block' input is defined
  if (moose_object->isParamValid("block"))
  {
    // Extract the blocks from the input
    _blocks = moose_object->getParam<std::vector<SubdomainName>>("block");
    // Store the IDs in a set, handling ANY_BLOCK_ID if supplied
    if (std::find(_blocks.begin(), _blocks.end(), "ANY_BLOCK_ID") != _blocks.end())
      _blk_ids.insert(Moose::ANY_BLOCK_ID);
    else
    {
      // Get the IDs from the supplied names
      _vec_ids = _blk_mesh->getSubdomainIDs(_blocks);
      _blk_ids.insert(_vec_ids.begin(), _vec_ids.end());
    }
  }
  // When 'blocks' is not set and there is a "variable", use the blocks from the variable
  else if (moose_object->isParamValid("variable"))
  {
    std::string variable_name = moose_object->parameters().getMooseType("variable");
    if (!variable_name.empty())
      _blk_ids = _blk_feproblem
                     ->getVariable(_blk_tid,
                                   variable_name,
                                   Moose::VarKindType::VAR_ANY,
                                   Moose::VarFieldType::VAR_FIELD_ANY)
                     .activeSubdomains();
  }
  // Produce error if the object is not allowed to be both block and boundary restricted
  if (!_blk_dual_restrictable && !_boundary_ids.empty() && !_boundary_ids.empty())
    if (!_boundary_ids.empty() && _boundary_ids.find(Moose::ANY_BOUNDARY_ID) == _boundary_ids.end())
      moose_object->paramError("block",
                               "Attempted to restrict the object '",
                               _blk_name,
                               "' to a block, but the object is already restricted by boundary");
  // If no blocks were defined above, specify that it is valid on all blocks
  if (_blk_ids.empty() && !moose_object->isParamValid("boundary"))
  {
    _blk_ids.insert(Moose::ANY_BLOCK_ID);
    _blocks = {"ANY_BLOCK_ID"};
  }
  // If this object is block restricted, check that defined blocks exist on the mesh
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) == _blk_ids.end())
  {
    const std::set<SubdomainID> & valid_ids = _blk_mesh->meshSubdomains();
    std::vector<SubdomainID> diff;
    std::set_difference(_blk_ids.begin(),
                        _blk_ids.end(),
                        valid_ids.begin(),
                        valid_ids.end(),
                        std::back_inserter(diff));
    if (!diff.empty())
    {
      std::ostringstream msg;
      auto sep = " ";
      msg << "the following blocks (ids) do not exist on the mesh:";
      for (const auto & id : diff)
      {
        if (_blk_name.size() > 0)
        {
          auto & name =
              _blocks.at(std::find(_vec_ids.begin(), _vec_ids.end(), id) - _vec_ids.begin());
          if (std::to_string(id) != name)
            msg << sep << name << " (" << id << ")";
          else
            msg << sep << id;
        }
        else
          msg << sep << id;
        sep = ", ";
      }
      moose_object->paramError("block", msg.str());
    }
  }
  // Get the mesh dimension for the blocks
  if (blockRestricted())
    _blk_dim = _blk_mesh->getBlocksMaxDimension(_blocks);
  else
    _blk_dim = _blk_mesh->dimension();
}
Referenced by BlockRestrictable::BlockRestrictable().
initialSetup()
void MooseVariableBase::initialSetup () override virtual inherited
Gets called at the beginning of the simulation before this object is asked to do its job.
Reimplemented from SetupInterface.
Definition at line 187 of file MooseVariableBase.C.
{
  // Currently the scaling vector is only used through AD residual computing objects
  if (_subproblem.haveADObjects() &&
      (_subproblem.automaticScaling() || (std::find_if(_scaling_factor.begin(),
                                                       _scaling_factor.end(),
                                                       [](const Real element) {
                                                         return !MooseUtils::absoluteFuzzyEqual(
                                                             element, 1.);
                                                       }) != _scaling_factor.end())))
    _sys.addScalingVector();
}
insert()
void MooseVariableFE< Real >::insert (NumericVector< Number > & residual) override virtual inherited
Set the current local DOF values to the input vector.
Implements MooseVariableFieldBase.
Definition at line 557 of file MooseVariableFE.C.
{
  _element_data->insert(residual);
}
insertNodalValue()
void MooseVariableFE< Real >::insertNodalValue (NumericVector< Number > & residual, const OutputData & v) inherited
Write a nodal value to the passed-in solution vector.
Definition at line 519 of file MooseVariableFE.C.
{
  _element_data->insertNodalValue(residual, v);
}
isArray()
bool MooseVariableFE< Real >::isArray override virtual inherited
Returns
true if this is an array variable, false otherwise.
Implements MooseVariableFieldBase.
Definition at line 152 of file MooseVariableFE.C.
{
  return std::is_same<OutputType, RealEigenVector>::value;
}
isBlockSubset() [1/2]
bool BlockRestrictable::isBlockSubset (const std::set< SubdomainID > & ids) const inherited
Test if the class block ids are a subset of the supplied objects.
Parameters
ids A std::set of Subdomains to check
Returns
True if all of the block ids for this class are found within the given ids (opposite of hasBlocks)
See also
hasBlocks
Definition at line 246 of file BlockRestrictable.C.
{
  // An empty input is assumed to be ANY_BLOCK_ID
  if (ids.empty() || ids.find(Moose::ANY_BLOCK_ID) != ids.end())
    return true;
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return std::includes(ids.begin(),
                         ids.end(),
                         _blk_mesh->meshSubdomains().begin(),
                         _blk_mesh->meshSubdomains().end());
  else
    return std::includes(ids.begin(), ids.end(), _blk_ids.begin(), _blk_ids.end());
}
Referenced by BlockRestrictable::checkVariable(), BlockRestrictable::isBlockSubset(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), and ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux().
isBlockSubset() [2/2]
bool BlockRestrictable::isBlockSubset (const std::vector< SubdomainID > & ids) const inherited
Test if the class block ids are a subset of the supplied objects.
Parameters
ids A std::vector of Subdomains to check
Returns
True if all of the block ids for this class are found within the given ids (opposite of hasBlocks)
See also
hasBlocks
Definition at line 262 of file BlockRestrictable.C.
{
  std::set<SubdomainID> ids_set(ids.begin(), ids.end());
  return isBlockSubset(ids_set);
}
isConstant()
virtual bool Moose::FunctorBase< Moose::ADType< OutputType >::type >::isConstant () const inline virtual inherited
Returns true if this functor is a constant.
Definition at line 167 of file MooseFunctor.h.
{ return false; }
isExtrapolatedBoundaryFace()
virtual bool Moose::FunctorBase< Moose::ADType< OutputType >::type >::isExtrapolatedBoundaryFace (const FaceInfo & , const Elem * , const StateArg &) const inline virtual inherited
Returns whether this (sided) face is an extrapolated boundary face for this functor.
Reimplemented in MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 154 of file MooseFunctor.h.
  {
    mooseError("not implemented");
  }
isFV()
virtual bool MooseVariableFieldBase::isFV () const inline virtual inherited
Reimplemented in MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 86 of file MooseVariableFieldBase.h.
{ return false; }
Referenced by ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), ComputeFullJacobianThread::computeOnInterface(), ComputeFullJacobianThread::computeOnInternalFace(), GradientJumpIndicator::computeQpIntegral(), InternalSideIndicator::finalize(), and FVInitialConditionTempl< T >::FVInitialConditionTempl().
isInternalFace()
bool Moose::FunctorBase< Moose::ADType< OutputType >::type >::isInternalFace (const FaceInfo & fi) const inherited
Returns true if the face is an internal face.
Definition at line 162 of file MooseFunctor.h.
{
  if (!fi.neighborPtr())
    return false;
  return hasBlocks(fi.elem().subdomain_id()) && hasBlocks(fi.neighborPtr()->subdomain_id());
}
isNodal()
bool MooseVariableFE< Real >::isNodal () const inline override virtual inherited
Is this variable nodal.
Returns
true if it nodal, otherwise false
Reimplemented from MooseVariableBase.
Definition at line 148 of file MooseVariableFE.h.
{ return _element_data->isNodal(); }
isNodalDefined()
bool MooseVariableFE< Real >::isNodalDefined override virtual inherited
Is this variable defined at nodes.
Returns
true if it the variable is defined at nodes, otherwise false
Implements MooseVariableFieldBase.
Definition at line 156 of file MooseVariableFE.C.
{
  return _element_data->isNodalDefined();
}
isNodalNeighborDefined()
bool MooseVariableFE< Real >::isNodalNeighborDefined inherited
Definition at line 163 of file MooseVariableFE.C.
{
  return _neighbor_data->isNodalDefined();
}
isParamSetByUser()
bool MooseBaseParameterInterface::isParamSetByUser (const std::string & nm) const inline inherited
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
Parameters
nm The name of the parameter to test
Definition at line 108 of file MooseBaseParameterInterface.h.
{ return _pars.isParamSetByUser(nm); }
Referenced by SetAdaptivityOptionsAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), LibtorchNeuralNetControl::conditionalParameterError(), MooseBaseParameterInterface::getRenamedParam(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), PiecewiseTabularBase::PiecewiseTabularBase(), MooseMesh::prepare(), and SolutionUserObject::readXda().
isParamValid()
bool MooseBaseParameterInterface::isParamValid (const std::string & name) const inline inherited
Test if the supplied parameter is valid.
Parameters
name The name of the parameter to test
Definition at line 102 of file MooseBaseParameterInterface.h.
{ return _pars.isParamValid(name); }
Referenced by AddDriftDiffusionAction::act(), AddSpecies::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CopyNodalVarsAction::act(), CreateDisplacedProblemAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), AddGeneralReactions::AddGeneralReactions(), AddZapdosReactions::AddZapdosReactions(), AdvectiveFluxAux::AdvectiveFluxAux(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), GeneratedMesh::buildMesh(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), ChemicalReactionsBase::ChemicalReactionsBase(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), CombinerGenerator::CombinerGenerator(), CSVReader::CSVReader(), ConstantReporter::declareConstantReporterValues(), DGKernelBase::DGKernelBase(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EEDFEnergyTownsendLog::EEDFEnergyTownsendLog(), Eigenvalue::Eigenvalue(), ElectronEnergyTermRate::ElectronEnergyTermRate(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), PIDTransientControl::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FileOutput::FileOutput(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FunctionDT::FunctionDT(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getRenamedParam(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), Terminator::handleMessage(), HeavySpeciesTempl< is_ad >::HeavySpeciesTempl(), HFEMDirichletBC::HFEMDirichletBC(), EigenExecutionerBase::init(), Eigenvalue::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), MooseParsedFunction::initialSetup(), MooseParsedGradFunction::initialSetup(), MooseParsedVectorFunction::initialSetup(), PiecewiseTabularBase::initialSetup(), SolutionFunction::initialSetup(), Console::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), IterationAdaptiveDT::IterationAdaptiveDT(), LeastSquaresFit::LeastSquaresFit(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MatCoupledForce::MatCoupledForce(), MooseMesh::MooseMesh(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarConsumerInterface::MortarConsumerInterface(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalExtremeValue::NodalExtremeValue(), EigenExecutionerBase::normalizeSolution(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PetscOutput::PetscOutput(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), PicardSolve::PicardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseTabularBase::PiecewiseTabularBase(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), MooseMesh::prepare(), MultiApp::readCommandLineArguments(), SolutionUserObject::readExodusII(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), MooseMesh::setCoordSystem(), FileOutput::setFileBase(), FileOutput::setFileBaseInternal(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SideDiffusiveFluxIntegralTempl< is_ad, T >::SideDiffusiveFluxIntegralTempl(), SideExtremeValue::SideExtremeValue(), SolutionUserObject::SolutionUserObject(), Terminator::Terminator(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), MultiAppDofCopyTransfer::transfer(), TransformGenerator::TransformGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
isVector()
bool MooseVariableFE< Real >::isVector override virtual inherited
Returns
true if this is a vector-valued element, false otherwise.
Implements MooseVariableFieldBase.
Definition at line 153 of file MooseVariableFE.C.
{
  return std::is_same<OutputType, RealVectorValue>::value;
}
jacobianSetup()
void MooseVariableFE< Real >::jacobianSetup override virtual inherited
Reimplemented from MooseVariableField< OutputType >.
Definition at line 706 of file MooseVariableFE.C.
{
  _current_elem_qp_functor_elem = nullptr;
  _current_elem_side_qp_functor_elem_side = std::make_pair(nullptr, libMesh::invalid_uint);
  MooseVariableField<OutputType>::jacobianSetup();
}
kind()
Moose::VarKindType MooseVariableBase::kind () const inline inherited
Kind of the variable (Nonlinear, Auxiliary, ...)
Definition at line 85 of file MooseVariableBase.h.
{ return _var_kind; }
Referenced by ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), FVFluxBC::FVFluxBC(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), and PeriodicSegmentalConstraint::PeriodicSegmentalConstraint().
matrixTagValue()
const FieldVariableValue & MooseVariableFE< Real >::matrixTagValue (TagID tag) const inline inherited
Definition at line 282 of file MooseVariableFE.h.
  {
    return _element_data->matrixTagValue(tag);
  }
meshBlockIDs()
const std::set< SubdomainID > & BlockRestrictable::meshBlockIDs () const inherited
Return all of the SubdomainIDs for the mesh.
Returns
A set of all subdomians for the entire mesh
Definition at line 269 of file BlockRestrictable.C.
{
  return _blk_mesh->meshSubdomains();
}
Referenced by BlockRestrictable::checkVariable(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), and SolutionIC::initialSetup().
meshChanged()
void MooseVariableFE< Real >::meshChanged override virtual inherited
Called on this object when the mesh changes.
Reimplemented from MeshChangedInterface.
Definition at line 704 of file MooseVariableFE.C.
{
  _current_elem_qp_functor_elem = nullptr;
  _current_elem_side_qp_functor_elem_side = std::make_pair(nullptr, libMesh::invalid_uint);
  MooseVariableField<OutputType>::meshChanged();
}
mooseDeprecated()
template<typename... Args> void MooseBaseErrorInterface::mooseDeprecated (Args &&... args) const inline inherited
Definition at line 78 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseDeprecatedStream(_console, false, true, std::forward<Args>(args)...);
  }
Referenced by FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::advanceMultiApps(), MultiApp::appProblem(), Executioner::augmentedPicardConvergenceCheck(), MooseMesh::buildSideList(), FEProblemBase::computeResidual(), AddVariableAction::determineType(), Eigenvalue::Eigenvalue(), MooseMesh::elem(), FunctionDT::FunctionDT(), RandomICBase::generateRandom(), MooseMesh::getBoundariesToElems(), Control::getExecuteOptions(), FEProblemBase::getNonlinearSystem(), FEProblemBase::getUserObjects(), FEProblemBase::hasPostprocessor(), MooseMesh::node(), FixedPointSolve::numPicardIts(), RelationshipManager::operator>=(), Executioner::picardSolve(), and MooseMesh::setBoundaryToNormalMap().
mooseError()
template<typename... Args> void MooseBaseErrorInterface::mooseError (Args &&... args) const inline inherited
Emits an error prefixed with object name and type.
Definition at line 38 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, errorPrefix("error"), std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
Referenced by HierarchicalGridPartitioner::_do_partition(), PetscExternalPartitioner::_do_partition(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AdaptivityAction::act(), AddFVICAction::act(), AddICAction::act(), AddMeshGeneratorAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVectorPostprocessorAction::act(), CheckFVBCAction::act(), CheckIntegrityAction::act(), CommonOutputAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DeprecatedBlockAction::act(), InitProblemAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetAdaptivityOptionsAction::act(), SetupMeshAction::act(), SetupMeshCompleteAction::act(), SetupPredictorAction::act(), SetupTimeStepperAction::act(), SplitMeshAction::act(), FEProblemBase::adaptMesh(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::addConstraint(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFVInitialCondition(), AddGeneralReactions::AddGeneralReactions(), FEProblemBase::addInitialCondition(), FEProblemBase::addLineSearch(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addOutput(), SubProblem::addPiecewiseByBlockLambdaFunctor(), DistributedRectilinearMeshGenerator::addPoint(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), FEProblemBase::addPostprocessor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseMesh::addQuadratureNode(), FEProblemBase::addReporter(), AddVariableAction::addVariable(), FEProblemBase::addVectorPostprocessor(), SubProblem::addVectorTag(), AddZapdosReactions::AddZapdosReactions(), ADEEDFRateConstantTownsend::ADEEDFRateConstantTownsend(), ADGasElectronMoments::ADGasElectronMoments(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), MooseVariableScalar::adUDot(), Output::advancedExecuteOn(), AdvectiveFluxAux::AdvectiveFluxAux(), ADZapdosEEDFRateConstant::ADZapdosEEDFRateConstant(), MooseVariableBase::allDofIndices(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayConstantIC::ArrayConstantIC(), ArrayFunctionIC::ArrayFunctionIC(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), Function::average(), Axisymmetric2D3DSolutionFunction::Axisymmetric2D3DSolutionFunction(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), BoltzmannSolverScalar::BoltzmannSolverScalar(), BoundingValueElementDamper::BoundingValueElementDamper(), BoundingValueNodalDamper::BoundingValueNodalDamper(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), MooseMesh::buildCoarseningMap(), MultiApp::buildComm(), DistributedRectilinearMeshGenerator::buildCube(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), PiecewiseTabularBase::buildFromXY(), MooseMesh::buildLowerDMesh(), GeneratedMesh::buildMesh(), MeshGeneratorMesh::buildMesh(), SpiralAnnularMesh::buildMesh(), TiledMesh::buildMesh(), ImageMesh::buildMesh3D(), ImageMeshGenerator::buildMesh3D(), MooseMesh::buildRefinementMap(), MaterialBase::buildRequiredMaterials(), MooseMesh::buildSideList(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), UserObjectInterface::castUserObject(), EigenExecutionerBase::chebyshev(), SubProblem::checkBlockMatProps(), SubProblem::checkBoundaryMatProps(), MooseMesh::checkCoordinateSystems(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkDisplacementOrders(), FEProblemBase::checkDuplicatePostprocessorVariableNames(), MooseMesh::checkDuplicateSubdomainNames(), MaterialBase::checkExecutionStage(), MeshGenerator::checkGetMesh(), ReporterTransferInterface::checkHasReporterValue(), FEProblemBase::checkICRestartError(), EigenExecutionerBase::checkIntegrity(), Eigenvalue::checkIntegrity(), Steady::checkIntegrity(), ExplicitTimeIntegrator::checkLinearConvergence(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), PostprocessorInterface::checkParam(), FEProblemBase::checkProblemIntegrity(), Sampler::checkReinitStatus(), MaterialBase::checkStatefulSanity(), FEProblemBase::checkUserObjects(), MultiAppTransfer::checkVariable(), DomainUserObject::checkVariable(), ChemicalReactionsBase::ChemicalReactionsBase(), MooseMesh::clone(), LibmeshPartitioner::clone(), CombinerGenerator::CombinerGenerator(), ElementSubdomainModifier::complementMovingBoundaryID(), ElementSubdomainModifier::complementMovingBoundaryName(), MooseVariableFieldBase::componentName(), CompositeFunction::CompositeFunction(), NodalPatchRecovery::compute(), VariableCondensationPreconditioner::computeDInverseDiag(), CompositionDT::computeDT(), MooseVariableFieldBase::computeFaceValues(), TimeStepper::computeFailedDT(), IterationAdaptiveDT::computeFailedDT(), TimeSequenceStepperBase::computeFailedDT(), MooseMesh::computeFiniteVolumeCoords(), FVFluxKernel::computeJacobian(), ArrayKernel::computeJacobian(), ArrayKernel::computeOffDiagJacobian(), FVElementalKernel::computeOffDiagJacobian(), MaterialBase::computeProperties(), ScalarKernel::computeQpJacobian(), ScalarKernel::computeQpResidual(), FVFluxKernel::computeResidual(), ArrayKernel::computeResidual(), FVFluxBC::computeResidual(), ResidualObject::computeResidualAndJacobian(), FVFluxKernel::computeResidualAndJacobian(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualL2Norm(), FEProblemBase::computeResidualTag(), FEProblemBase::computeResidualType(), TimeStepper::computeStep(), ActuallyExplicitEuler::computeTimeDerivatives(), AStableDirk4::computeTimeDerivatives(), BDF2::computeTimeDerivatives(), CrankNicolson::computeTimeDerivatives(), ExplicitEuler::computeTimeDerivatives(), ExplicitRK2::computeTimeDerivatives(), ExplicitTVDRK2::computeTimeDerivatives(), ImplicitEuler::computeTimeDerivatives(), ImplicitMidpoint::computeTimeDerivatives(), LStableDirk2::computeTimeDerivatives(), LStableDirk3::computeTimeDerivatives(), LStableDirk4::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), FEProblemBase::computeUserObjectsInternal(), BolsigValueScalar::computeValue(), PenetrationAux::computeValue(), BuildArrayVariableAux::computeValue(), TagVectorArrayVariableAux::computeValue(), ConcentricCircleMesh::ConcentricCircleMesh(), ConditionalEnableControl::ConditionalEnableControl(), TimeStepper::constrainStep(), LibtorchNeuralNetControl::controlNeuralNet(), AddVariableAction::createInitialConditionAction(), DataRead::DataRead(), ReporterTransferInterface::declareClone(), MeshGenerator::declareMeshProperty(), ReporterTransferInterface::declareVectorClone(), FunctorRelationshipManager::delete_remote_elements(), MooseMesh::deleteRemoteElements(), BicubicSplineFunction::derivative(), MooseMesh::detectPairedSidesets(), FEProblemBase::determineNonlinearSystem(), MeshDiagnosticsGenerator::diagnosticsLog(), DiffusionRateTemp::DiffusionRateTemp(), FunctorBinnedValuesDivision::divisionIndex(), FunctorRelationshipManager::dofmap_reinit(), FEProblemBase::duplicateVariableCheck(), EEDFRateConstant::EEDFRateConstant(), EEDFRateConstantTownsend::EEDFRateConstantTownsend(), Eigenvalue::Eigenvalue(), ElectricField::ElectricField(), ElectronMobility::ElectronMobility(), ElementIntegerAux::ElementIntegerAux(), ElementQualityAux::ElementQualityAux(), ElementUOAux::ElementUOAux(), DistributedRectilinearMeshGenerator::elemId(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), MooseMesh::errorIfDistributedMesh(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), BoltzmannSolverScalar::execute(), Eigenvalue::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), ElementQualityChecker::execute(), DiscreteElementUserObject::execute(), DomainUserObject::execute(), FEProblemBase::execute(), FEProblemBase::executeControls(), MultiAppVectorPostprocessorTransfer::executeFromMultiapp(), MultiAppVectorPostprocessorTransfer::executeToMultiapp(), ExplicitSSPRungeKutta::ExplicitSSPRungeKutta(), FileOutput::FileOutput(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), ElementQualityChecker::finalize(), VerifyElementUniqueID::finalize(), VerifyNodalUniqueID::finalize(), DiscreteElementUserObject::finalize(), Transfer::find_sys(), BreakMeshByBlockGeneratorBase::findFreeBoundaryId(), FunctionDT::FunctionDT(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), GapValueAux::GapValueAux(), Gas::Gas(), GasBase::GasBase(), GasElectronMoments::GasElectronMoments(), AllSideSetsByNormalsGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundingBoxNodeSetGenerator::generate(), BreakMeshByBlockGenerator::generate(), CombinerGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshCollectionGenerator::generate(), MeshDiagnosticsGenerator::generate(), MeshExtruderGenerator::generate(), MeshRepairGenerator::generate(), MoveNodeGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), SideSetsFromNormalsGenerator::generate(), SideSetsFromPointsGenerator::generate(), SmoothMeshGenerator::generate(), SpiralAnnularMeshGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), TiledMeshGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GeneratedMesh::GeneratedMesh(), GeneratedMeshGenerator::GeneratedMeshGenerator(), MeshGenerator::generateInternal(), CircularBoundaryCorrectionGenerator::generateRadialCorrectionFactor(), RandomICBase::generateRandom(), GenericConstantMaterialTempl< is_ad >::GenericConstantMaterialTempl(), GenericConstantVectorMaterialTempl< is_ad >::GenericConstantVectorMaterialTempl(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), DisplacedProblem::getActualFieldVariable(), FEProblemBase::getActualFieldVariable(), DisplacedProblem::getArrayVariable(), FEProblemBase::getArrayVariable(), MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::getBlockConnectedBlocks(), VariableOldValueBoundsAux::getBound(), MooseMesh::getBoundaryID(), MultiApp::getBoundingBox(), MooseMesh::getCoarseningMap(), MooseVariableBase::getContinuity(), Control::getControllableParameterByName(), MooseMesh::getCoordSystem(), PropertyReadFile::getData(), TransfiniteMeshGenerator::getDiscreteEdge(), FEProblemBase::getDistribution(), MooseVariableBase::getDofIndices(), VariableCondensationPreconditioner::getDofToCondense(), TransfiniteMeshGenerator::getEdge(), GhostingUserObject::getElementalValue(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), PropertyReadFile::getElementData(), MooseMesh::getElementIDIndex(), Material::getElementIDNeighbor(), Material::getElementIDNeighborByName(), MooseMesh::getElemIDMapping(), MooseMesh::getElemIDsOnBlocks(), MultiAppFieldTransfer::getEquationSystem(), MultiApp::getExecutioner(), MultiAppTransfer::getFromMultiApp(), MultiAppTransfer::getFromMultiAppInfo(), FEProblemBase::getFunction(), SubProblem::getFunctor(), MooseMesh::getGeneralAxisymmetricCoordAxis(), DistributedRectilinearMeshGenerator::getGhostNeighbors(), BatchMaterial< Tuple, Output, Input >::getIndex(), DistributedRectilinearMeshGenerator::getIndices(), SolutionUserObject::getLocalVarIndex(), Material::getMaterialByName(), FEProblemBase::getMaterialData(), SubProblem::getMatrixTagID(), AnnularMesh::getMaxInDimension(), GeneratedMesh::getMaxInDimension(), FEProblemBase::getMaxQps(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), AnnularMesh::getMinInDimension(), GeneratedMesh::getMinInDimension(), MultiAppTransfer::getMultiApp(), DistributedRectilinearMeshGenerator::getNeighbors(), MooseMesh::getNodeBlockIds(), PropertyReadFile::getNodeData(), MooseMesh::getNodeList(), FEProblemBase::getNonlinearSystem(), MooseMesh::getPairedBoundaryMapping(), ImageMesh::GetPixelInfo(), ImageMeshGenerator::GetPixelInfo(), PlaneIDMeshGenerator::getPlaneID(), FEProblemBase::getPositionsObject(), PostprocessorInterface::getPostprocessorValueByNameInternal(), MooseMesh::getRefinementMap(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), FEProblemBase::getSampler(), JSONFileReader::getScalar(), DisplacedProblem::getScalarVariable(), FEProblemBase::getScalarVariable(), DisplacedProblem::getStandardVariable(), FEProblemBase::getStandardVariable(), MooseMesh::getSubdomainBoundaryIds(), DisplacedProblem::getSystem(), FEProblemBase::getSystem(), FEProblemBase::getTimeFromStateArg(), Transient::getTimeIntegratorName(), MultiAppTransfer::getToMultiApp(), MultiAppTransfer::getToMultiAppInfo(), MooseMesh::getUniqueCoordSystem(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::getUserObjectName(), JSONFileReader::getVector(), VectorPostprocessorInterface::getVectorPostprocessorName(), SubProblem::getVectorTag(), SubProblem::getVectorTagID(), DisplacedProblem::getVectorVariable(), FEProblemBase::getVectorVariable(), GhostingAux::GhostingAux(), MultiApp::globalAppToLocal(), Function::gradient(), MooseParsedVectorFunction::gradient(), Terminator::handleMessage(), MooseVariableBase::hasDoFsOnNodes(), PostprocessorInterface::hasPostprocessor(), PostprocessorInterface::hasPostprocessorByName(), ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), AddVariableAction::init(), MooseMesh::init(), Sampler::init(), AddAuxVariableAction::init(), EigenExecutionerBase::init(), Eigenvalue::init(), Transient::init(), FEProblemBase::init(), CrankNicolson::init(), ExplicitTimeIntegrator::init(), CSVTimeSequenceStepper::init(), IterationAdaptiveDT::init(), MultiApp::init(), FEProblemBase::initialAdaptMesh(), BoltzmannSolverScalar::initialize(), PolynomialCoefficients::initialize(), CartesianGridDivision::initialize(), CylindricalGridDivision::initialize(), NestedDivision::initialize(), SphericalGridDivision::initialize(), SubProblem::initialSetup(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), Axisymmetric2D3DSolutionFunction::initialSetup(), MooseParsedFunction::initialSetup(), SolutionFunction::initialSetup(), SolutionIC::initialSetup(), FullSolveMultiApp::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), SolutionUserObject::initialSetup(), Function::integral(), InterpolatedCoefficientLinear::InterpolatedCoefficientLinear(), InterpolatedCoefficientSpline::InterpolatedCoefficientSpline(), EigenExecutionerBase::inversePowerIteration(), InversePowerMethod::InversePowerMethod(), Sampler::isAdaptiveSamplingCompleted(), MooseMesh::isBoundaryFullyExternalToSubdomains(), MooseVariableBase::isNodal(), IterationAdaptiveDT::IterationAdaptiveDT(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LineSearch::lineSearch(), ReporterPointMarker::markerSetup(), Material::Material(), MaterialOutputAction::materialOutputHelper(), MaterialRealTensorValueAux::MaterialRealTensorValueAux(), MaterialRealVectorValueAuxTempl< is_ad >::MaterialRealVectorValueAuxTempl(), Distribution::median(), FunctorRelationshipManager::mesh_reinit(), SubProblem::meshChanged(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshExtruderGenerator::MeshExtruderGenerator(), MeshRepairGenerator::MeshRepairGenerator(), SetupMeshAction::modifyParamsForUseSplit(), MeshMetaDataInterface::mooseErrorInternal(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MoveNodeGenerator::MoveNodeGenerator(), ElementSubdomainModifier::movingBoundaryID(), ElementSubdomainModifier::movingBoundaryName(), MultiApp::MultiApp(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NearestNodeDistanceAux::NearestNodeDistanceAux(), NearestNodeValueAux::NearestNodeValueAux(), FEProblemBase::needsPreviousNewtonIteration(), NewmarkBeta::NewmarkBeta(), NodalPatchRecoveryBase::nodalPatchRecovery(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), DistributedRectilinearMeshGenerator::nodeId(), DistributedRectilinearMeshGenerator::numNeighbors(), Output::onInterval(), FunctorRelationshipManager::operator()(), RelationshipManager::operator==(), MortarNodalGeometryOutput::output(), Output::Output(), DistributedRectilinearMeshGenerator::paritionSquarely(), PiecewiseBilinear::parse(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), ExplicitTimeIntegrator::performExplicitSolve(), PetscExternalPartitioner::PetscExternalPartitioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), Executioner::picardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseMulticonstant::PiecewiseMulticonstant(), PiecewiseTabularBase::PiecewiseTabularBase(), SolutionUserObject::pointValueGradientWrapper(), SolutionUserObject::pointValueWrapper(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName(), AStableDirk4::postResidual(), ExplicitRK2::postResidual(), ExplicitTVDRK2::postResidual(), ImplicitMidpoint::postResidual(), LStableDirk2::postResidual(), LStableDirk3::postResidual(), LStableDirk4::postResidual(), VariableCondensationPreconditioner::preallocateCondensedJacobian(), Predictor::Predictor(), Transient::preExecute(), MooseMesh::prepare(), MooseMesh::prepared(), FixedPointSolve::printFixedPointConvergenceReason(), RateCoefficientProvider::RateCoefficientProvider(), RateCoefficientProvider::reaction_coefficient(), RateCoefficientProvider::reaction_coefficient_derivative(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readExodusII(), SolutionUserObject::readXda(), FunctorRelationshipManager::redistribute(), Sampler::reinit(), RinglebMesh::RinglebMesh(), RinglebMeshGenerator::RinglebMeshGenerator(), PiecewiseMultiInterpolation::sample(), ScalarComponentIC::ScalarComponentIC(), ScalarLinearInterpolation::ScalarLinearInterpolation(), ScalarSplineInterpolation::ScalarSplineInterpolation(), DistributedRectilinearMeshGenerator::scaleNodalPositions(), BicubicSplineFunction::secondDerivative(), FunctorRelationshipManager::set_mesh(), MooseVariableBase::setActiveTags(), DistributedRectilinearMeshGenerator::setBoundaryNames(), MooseMesh::setCoordSystem(), FEProblemBase::setCoupling(), PiecewiseBase::setData(), FileOutput::setFileBaseInternal(), MooseMesh::setGeneralAxisymmetricCoordAxes(), FEProblemSolve::setInnerSolve(), MeshGenerator::setMeshProperty(), FEProblemBase::setNonlocalCouplingMatrix(), Sampler::setNumberOfCols(), Sampler::setNumberOfRandomSeeds(), Sampler::setNumberOfRows(), Split::setup(), TransientMultiApp::setupApp(), SetupMeshAction::setupMesh(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), TimePeriodBase::setupTimes(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SideSetsFromNormalsGenerator::SideSetsFromNormalsGenerator(), SideSetsFromPointsGenerator::SideSetsFromPointsGenerator(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), SolutionTimeAdaptiveDT::SolutionTimeAdaptiveDT(), SolutionUserObject::SolutionUserObject(), FullSolveMultiApp::solveStep(), UserObject::spatialPoints(), UserObject::spatialValue(), SpiralAnnularMesh::SpiralAnnularMesh(), SpiralAnnularMeshGenerator::SpiralAnnularMeshGenerator(), StitchedMesh::StitchedMesh(), MaterialBase::subdomainSetup(), GeneralUserObject::subdomainSetup(), NodalUserObject::subdomainSetup(), Constraint::subdomainSetup(), SuperelasticReactionRate::SuperelasticReactionRate(), FEProblemBase::swapBackMaterialsNeighbor(), Terminator::Terminator(), GeneralUserObject::threadJoin(), ThreadedGeneralUserObject::threadJoin(), DiscreteElementUserObject::threadJoin(), TimePeriodBase::TimePeriodBase(), VectorPostprocessorVisualizationAux::timestepSetup(), FEProblemBase::trustUserCouplingMatrix(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), FEProblemBase::uDotDotOldRequested(), MooseVariableScalar::uDotOld(), FEProblemBase::uDotOldRequested(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), SolutionUserObject::updateExodusBracketingTimeIndices(), FEProblemBase::updateMaxQps(), BoundingBoxIC::value(), Function::value(), Axisymmetric2D3DSolutionFunction::value(), PiecewiseConstantFromCSV::value(), ValueProvider::ValueProvider(), ValueRangeMarker::ValueRangeMarker(), ValueThresholdMarker::ValueThresholdMarker(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), MultiAppTransfer::variableIntegrityCheck(), VariableTimeIntegrationAux::VariableTimeIntegrationAux(), AddVariableAction::variableType(), Function::vectorCurl(), SubProblem::vectorTagName(), SubProblem::vectorTagType(), Function::vectorValue(), MooseParsedFunction::vectorValue(), MooseParsedGradFunction::vectorValue(), SubProblem::verifyVectorTags(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
mooseErrorNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseErrorNonPrefixed (Args &&... args) const inline inherited
Emits an error without the prefixing included in mooseError().
Definition at line 50 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
mooseInfo()
template<typename... Args> void MooseBaseErrorInterface::mooseInfo (Args &&... args) const inline inherited
Definition at line 84 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseInfoStream(_console, std::forward<Args>(args)...);
  }
Referenced by AddZapdosReactions::act(), SetupRecoverFileBaseAction::act(), AStableDirk4::AStableDirk4(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), BoltzmannSolverScalar::execute(), ExplicitRK2::ExplicitRK2(), ExplicitTVDRK2::ExplicitTVDRK2(), MultiAppTransfer::getPointInTargetAppFrame(), ImplicitMidpoint::ImplicitMidpoint(), InversePowerMethod::InversePowerMethod(), LStableDirk2::LStableDirk2(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), NonlinearEigen::NonlinearEigen(), ProjectionAux::ProjectionAux(), FEProblemBase::setRestartFile(), and SymmetryTransformGenerator::SymmetryTransformGenerator().
mooseWarning()
template<typename... Args> void MooseBaseErrorInterface::mooseWarning (Args &&... args) const inline inherited
Emits a warning prefixed with object name and type.
Definition at line 62 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(
        _console, errorPrefix("warning"), std::forward<Args>(args)...);
  }
Referenced by AddFunctionAction::act(), AddKernelAction::act(), CommonOutputAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupMeshAction::act(), DumpObjectsProblem::addAuxVariable(), DiracKernelBase::addPoint(), BoundaryMarker::BoundaryMarker(), BoundsAuxBase::BoundsAuxBase(), DistributedRectilinearMeshGenerator::buildCube(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), CartesianMeshGenerator::CartesianMeshGenerator(), CheckOutputAction::checkConsoleOutput(), MultiAppTransfer::checkMultiAppExecuteOn(), GapValueAux::computeValue(), MeshDiagnosticsGenerator::diagnosticsLog(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), Postprocessor::evaluateDotWarning(), ElementQualityChecker::finalize(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FixedPointSolve::FixedPointSolve(), ElementSubdomainIDGenerator::generate(), ParsedGenerateSideset::generate(), MultiAppTransfer::getAppInfo(), FunctorBinnedValuesDivision::getBinIndex(), FEProblemBase::getMaterial(), Terminator::handleMessage(), MaterialBase::initStatefulProperties(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::mesh(), NewmarkBeta::NewmarkBeta(), NodalPatchRecovery::NodalPatchRecovery(), Output::Output(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), Executioner::problem(), PropertyReadFile::readData(), TestSourceStepper::rejectStep(), MaterialBase::resetQpProperties(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setCoordSystem(), FEProblemBase::sizeZeroes(), TransientMultiApp::solveStep(), TimeDerivativeAux::TimeDerivativeAux(), PiecewiseConstantFromCSV::value(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
mooseWarningNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseWarningNonPrefixed (Args &&... args) const inline inherited
Emits a warning without the prefixing included in mooseWarning().
Definition at line 72 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(_console, std::forward<Args>(args)...);
  }
name()
const std::string & MooseVariableBase::name () const inline override virtual inherited
Get the variable name.
Reimplemented from MooseBase.
Definition at line 69 of file MooseVariableBase.h.
{ return _var_name; }
Referenced by SetupResidualDebugAction::act(), InitialConditionWarehouse::addObject(), MooseVariableBase::allDofIndices(), ArrayParsedAux::ArrayParsedAux(), BlockRestrictable::checkVariable(), DomainUserObject::checkVariable(), Coupleable::checkWritableVar(), Coupleable::coupledName(), Moose::FV::determineElemOneAndTwo(), GreaterThanLessThanPostprocessor::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppGeometricInterpolationTransfer::fillSourceInterpolationPoints(), FunctionArrayAux::FunctionArrayAux(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), GapValueAux::GapValueAux(), MultiAppGeometricInterpolationTransfer::interpolateTargetPoints(), DerivativeMaterialInterface< T >::isNotObjectVariable(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedODEKernel::ParsedODEKernel(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ConstraintWarehouse::subdomainsCovered(), MultiAppDofCopyTransfer::transfer(), MultiAppShapeEvaluationTransfer::transferVariable(), FVFluxBC::uOnGhost(), and FVFluxBC::uOnUSub().
neighbor()
const Elem *const & MooseVariableFE< Real >::neighbor () const inline inherited
Current neighboring element.
Definition at line 175 of file MooseVariableFE.h.
{ return _neighbor_data->currentElem(); }
nodalDofIndex()
const dof_id_type & MooseVariableFE< Real >::nodalDofIndex () const inline override virtual inherited
Implements MooseVariableFieldBase.
Definition at line 155 of file MooseVariableFE.h.
{ return _element_data->nodalDofIndex(); }
nodalDofIndexNeighbor()
const dof_id_type & MooseVariableFE< Real >::nodalDofIndexNeighbor () const inline override virtual inherited
Implements MooseVariableFieldBase.
Definition at line 159 of file MooseVariableFE.h.
  {
    return _neighbor_data->nodalDofIndex();
  }
nodalMatrixTagValue()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::nodalMatrixTagValue (TagID tag) const inherited
Definition at line 693 of file MooseVariableFE.C.
{
  return _element_data->nodalMatrixTagValue(tag);
}
nodalValue()
const Real & MooseVariableFE< Real >::nodalValue inherited
Methods for retrieving values of variables at the nodes.
Definition at line 656 of file MooseVariableFE.C.
{
  return _element_data->nodalValue(Moose::Current);
}
nodalValueArray()
const MooseArray< Real > & MooseVariableFE< Real >::nodalValueArray () const inline override virtual inherited
Methods for retrieving values of variables at the nodes in a MooseArray for AuxKernelBase.
Implements MooseVariableField< OutputType >.
Definition at line 679 of file MooseVariableFE.h.
  {
    return _element_data->nodalValueArray(Moose::Current);
  }
nodalValueDot()
const Real & MooseVariableFE< Real >::nodalValueDot inherited
Definition at line 660 of file MooseVariableFE.C.
{
  return _element_data->nodalValueDot();
}
nodalValueDotDot()
const Real & MooseVariableFE< Real >::nodalValueDotDot inherited
Definition at line 661 of file MooseVariableFE.C.
{
  return _element_data->nodalValueDotDot();
}
nodalValueDotDotNeighbor()
const Real & MooseVariableFE< Real >::nodalValueDotDotNeighbor () const inherited
nodalValueDotDotNeighborResidual()
const Real & MooseVariableFE< Real >::nodalValueDotDotNeighborResidual () const inherited
nodalValueDotDotOld()
const Real & MooseVariableFE< Real >::nodalValueDotDotOld inherited
Definition at line 663 of file MooseVariableFE.C.
{
  return _element_data->nodalValueDotDotOld();
}
nodalValueDotDotOldNeighbor()
const Real & MooseVariableFE< Real >::nodalValueDotDotOldNeighbor () const inherited
nodalValueDotNeighbor()
const Real & MooseVariableFE< Real >::nodalValueDotNeighbor () const inherited
nodalValueDotNeighborResidual()
const Real & MooseVariableFE< Real >::nodalValueDotNeighborResidual () const inherited
nodalValueDotOld()
const Real & MooseVariableFE< Real >::nodalValueDotOld inherited
Definition at line 662 of file MooseVariableFE.C.
{
  return _element_data->nodalValueDotOld();
}
nodalValueDotOldNeighbor()
const Real & MooseVariableFE< Real >::nodalValueDotOldNeighbor () const inherited
nodalValueDuDotDotDu()
const Real & MooseVariableFE< Real >::nodalValueDuDotDotDu () const inherited
nodalValueDuDotDotDuNeighbor()
const Real & MooseVariableFE< Real >::nodalValueDuDotDotDuNeighbor () const inherited
nodalValueDuDotDu()
const Real & MooseVariableFE< Real >::nodalValueDuDotDu () const inherited
nodalValueDuDotDuNeighbor()
const Real & MooseVariableFE< Real >::nodalValueDuDotDuNeighbor () const inherited
nodalValueNeighbor()
const Real & MooseVariableFE< Real >::nodalValueNeighbor inherited
Definition at line 666 of file MooseVariableFE.C.
{
  return _neighbor_data->nodalValue(Moose::Current);
}
nodalValueOld()
const Real & MooseVariableFE< Real >::nodalValueOld inherited
Definition at line 657 of file MooseVariableFE.C.
{
  return _element_data->nodalValue(Moose::Old);
}
nodalValueOldArray()
const MooseArray< Real > & MooseVariableFE< Real >::nodalValueOldArray () const inline override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 683 of file MooseVariableFE.h.
  {
    return _element_data->nodalValueArray(Moose::Old);
  }
nodalValueOlder()
const Real & MooseVariableFE< Real >::nodalValueOlder inherited
Definition at line 658 of file MooseVariableFE.C.
{
  return _element_data->nodalValue(Moose::Older);
}
nodalValueOlderArray()
const MooseArray< Real > & MooseVariableFE< Real >::nodalValueOlderArray () const inline override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 687 of file MooseVariableFE.h.
  {
    return _element_data->nodalValueArray(Moose::Older);
  }
nodalValueOlderNeighbor()
const Real & MooseVariableFE< Real >::nodalValueOlderNeighbor inherited
Definition at line 668 of file MooseVariableFE.C.
{
  return _neighbor_data->nodalValue(Moose::Older);
}
nodalValueOldNeighbor()
const Real & MooseVariableFE< Real >::nodalValueOldNeighbor inherited
Definition at line 667 of file MooseVariableFE.C.
{
  return _neighbor_data->nodalValue(Moose::Old);
}
nodalValuePreviousNL()
const Real & MooseVariableFE< Real >::nodalValuePreviousNL inherited
Definition at line 659 of file MooseVariableFE.C.
{
  return _element_data->nodalValue(Moose::PreviousNL);
}
nodalValuePreviousNLNeighbor()
const Real & MooseVariableFE< Real >::nodalValuePreviousNLNeighbor inherited
Definition at line 669 of file MooseVariableFE.C.
{
  return _neighbor_data->nodalValue(Moose::PreviousNL);
}
nodalVectorTagValue()
const MooseVariableFE< Real >::DoFValue & MooseVariableFE< Real >::nodalVectorTagValue (TagID tag) const override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 692 of file MooseVariableFE.C.
{
  return _element_data->nodalVectorTagValue(tag);
}
node()
const Node *const & MooseVariableFE< Real >::node () const inline inherited
Definition at line 154 of file MooseVariableFE.h.
{ return _element_data->node(); }
nodeNeighbor()
const Node *const & MooseVariableFE< Real >::nodeNeighbor () const inline inherited
Definition at line 158 of file MooseVariableFE.h.
{ return _neighbor_data->node(); }
number()
unsigned int MooseVariableBase::number () const inline inherited
Get variable number coming from libMesh.
Returns
the libmesh variable number
Definition at line 49 of file MooseVariableBase.h.
{ return _var_num; }
Referenced by AdaptivityAction::act(), Assembly::addJacobianBlock(), Assembly::addJacobianCoupledVarPair(), EigenProblem::adjustEigenVector(), MooseMesh::cacheFaceInfoVariableOwnership(), Assembly::cacheJacobianBlock(), Assembly::cacheJacobianBlockNonzero(), Assembly::cacheJacobianCoupledVarPair(), ComputeJacobianThread::compute(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayIntegratedBC::computeJacobian(), IntegratedBC::computeJacobian(), NonlocalIntegratedBC::computeJacobian(), VectorIntegratedBC::computeJacobian(), NodeElemConstraint::computeJacobian(), NodeFaceConstraint::computeJacobian(), ArrayKernel::computeJacobian(), EigenKernel::computeJacobian(), Kernel::computeJacobian(), KernelGrad::computeJacobian(), KernelValue::computeJacobian(), MassLumpedTimeDerivative::computeJacobian(), NonlocalKernel::computeJacobian(), ODEKernel::computeJacobian(), TimeDerivative::computeJacobian(), VectorKernel::computeJacobian(), VectorTimeDerivative::computeJacobian(), NodalEqualValueConstraint::computeJacobian(), ScalarKernel::computeJacobian(), FVFluxBC::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), MortarConstraint::computeJacobian(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDResidual(), DGLowerDKernel::computeLowerDResidual(), NonlocalIntegratedBC::computeNonlocalJacobian(), NonlocalKernel::computeNonlocalJacobian(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ArrayIntegratedBC::computeOffDiagJacobian(), IntegratedBC::computeOffDiagJacobian(), LowerDIntegratedBC::computeOffDiagJacobian(), NodalBC::computeOffDiagJacobian(), NonlocalIntegratedBC::computeOffDiagJacobian(), VectorIntegratedBC::computeOffDiagJacobian(), VectorNodalBC::computeOffDiagJacobian(), NodeElemConstraint::computeOffDiagJacobian(), NodeFaceConstraint::computeOffDiagJacobian(), DGLowerDKernel::computeOffDiagJacobian(), ADKernelScalarBase::computeOffDiagJacobian(), ArrayKernel::computeOffDiagJacobian(), EigenKernel::computeOffDiagJacobian(), Kernel::computeOffDiagJacobian(), KernelGrad::computeOffDiagJacobian(), KernelValue::computeOffDiagJacobian(), NonlocalKernel::computeOffDiagJacobian(), VectorKernel::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), ADDGKernel::computeOffDiagJacobian(), ADNodalKernel::computeOffDiagJacobian(), ArrayIntegratedBC::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), ArrayKernel::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), NodalScalarKernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), ComputeFullJacobianThread::computeOnInterface(), ComputeFullJacobianThread::computeOnInternalFace(), EEDFReactionLog::computeQpJacobian(), EEDFReactionTownsendLog::computeQpJacobian(), OldEqualValueConstraint::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), ArrayIntegratedBC::computeQpOffDiagJacobian(), ArrayKernel::computeQpOffDiagJacobian(), ArrayCoupledTimeDerivative::computeQpOffDiagJacobian(), ArrayDiffusion::computeQpOffDiagJacobian(), ArrayReaction::computeQpOffDiagJacobian(), ArrayTimeDerivative::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), ArrayNodalBC::computeQpOffDiagJacobian(), EEDFReactionTownsendLog::computeQpOffDiagJacobian(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), ArrayIntegratedBC::computeResidual(), ArrayLowerDIntegratedBC::computeResidual(), IntegratedBC::computeResidual(), LowerDIntegratedBC::computeResidual(), VectorIntegratedBC::computeResidual(), NodeElemConstraint::computeResidual(), NodeFaceConstraint::computeResidual(), FVElementalKernel::computeResidual(), ArrayKernel::computeResidual(), EigenKernel::computeResidual(), Kernel::computeResidual(), KernelGrad::computeResidual(), KernelValue::computeResidual(), ODEKernel::computeResidual(), ODETimeKernel::computeResidual(), TimeKernel::computeResidual(), VectorKernel::computeResidual(), VectorTimeKernel::computeResidual(), ADScalarKernel::computeResidual(), NodalEqualValueConstraint::computeResidual(), ScalarKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVFluxBC::computeResidual(), FVInterfaceKernel::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), FVScalarLagrangeMultiplierInterface::computeResidual(), ADMortarConstraint::computeResidual(), MortarConstraint::computeResidual(), IntegratedBC::computeResidualAndJacobian(), NodalBC::computeResidualAndJacobian(), Kernel::computeResidualAndJacobian(), MortarScalarBase::computeScalarOffDiagJacobian(), PenaltyPeriodicSegmentalConstraint::computeScalarQpOffDiagJacobian(), PeriodicSegmentalConstraint::computeScalarQpOffDiagJacobian(), DebugResidualAux::computeValue(), ProjectionAux::computeValue(), CoupledForceNodalKernel::CoupledForceNodalKernel(), CoupledForceTempl< is_ad >::CoupledForceTempl(), ScalarCoupleable::coupledScalar(), Moose::FV::determineElemOneAndTwo(), EconomouDielectricBC::EconomouDielectricBC(), VariableResidual::execute(), NodalNormalsCorner::execute(), NodalNormalsEvaluator::execute(), NodalNormalsPreprocessor::execute(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), ConservativeAdvection::fullUpwind(), BoundsAuxBase::getDoFIndex(), FVBoundaryCondition::hasFaceSide(), LazyCoupleable::init(), NodalNormalsPreprocessor::initialize(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), ArrayKernel::initQpOffDiagJacobian(), LowerBoundNodalKernel::LowerBoundNodalKernel(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), ComputeDiracThread::onElement(), ComputeNodalKernelBCJacobiansThread::onNode(), ComputeNodalKernelJacobiansThread::onNode(), Assembly::prepareBlock(), Assembly::prepareBlockNonlocal(), Assembly::prepareJacobianBlock(), Assembly::prepareLowerD(), Assembly::prepareNeighbor(), Assembly::prepareNonlocal(), Assembly::prepareVariable(), Assembly::prepareVariableNonlocal(), MultiAppProjectionTransfer::projectSolution(), EqualValueEmbeddedConstraint::reinitConstraint(), AddPeriodicBCAction::setPeriodicVars(), FVInterfaceKernel::setupData(), NonlinearSystemBase::setupScalingData(), MultiAppDofCopyTransfer::transferDofObject(), FVFluxBC::uOnGhost(), FVFluxBC::uOnUSub(), UpdateErrorVectorsThread::UpdateErrorVectorsThread(), UpperBoundNodalKernel::UpperBoundNodalKernel(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and MortarConstraintBase::zeroInactiveLMDofs().
numberOfDofs()
unsigned int MooseVariableFE< Real >::numberOfDofs () const inline final virtual inherited
Get the number of local DoFs.
Reimplemented from MooseVariableBase.
Definition at line 180 of file MooseVariableFE.h.
{ return _element_data->numberOfDofs(); }
numberOfDofsNeighbor()
unsigned int MooseVariableFE< Real >::numberOfDofsNeighbor () inline override virtual inherited
Implements MooseVariableFieldBase.
Definition at line 192 of file MooseVariableFE.h.
{ return _neighbor_data->dofIndices().size(); }
numBlocks()
unsigned int BlockRestrictable::numBlocks () const inherited
Return the number of blocks for this object.
Returns
The number of subdomains
Definition at line 199 of file BlockRestrictable.C.
{
  return (unsigned int)_blk_ids.size();
}
Referenced by ElementCentroidPositions::initialize().
objectErrorPrefix()
std::string MooseBaseParameterInterface::objectErrorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for an object.
Definition at line 58 of file MooseBaseParameterInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the class \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseParameterInterface::paramErrorMsg().
oldestSolutionStateRequested()
unsigned int MooseVariableFE< Real >::oldestSolutionStateRequested final override virtual inherited
The oldest solution state that is requested for this variable (0 = current, 1 = old, 2 = older, etc).
Implements MooseVariableFieldBase.
Definition at line 700 of file MooseVariableFE.C.
{
  unsigned int state = 0;
  state = std::max(state, _element_data->oldestSolutionStateRequested());
  state = std::max(state, _neighbor_data->oldestSolutionStateRequested());
  state = std::max(state, _lower_data->oldestSolutionStateRequested());
  return state;
}
operator()() [1/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluate overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 84 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(elem, state);
  mooseAssert(state.state == 0,
              "Cached evaluations are only currently supported for the current state.");
  return queryFVArgCache(_elem_arg_to_value, elem);
}
operator()() [2/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 88 of file MooseFunctor.h.
{
  return evaluate(elem_point, state);
}
operator()() [3/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 86 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(elem_qp, state);
  const auto elem_id = elem_qp.elem->id();
  if (elem_id != _current_qp_map_key)
  {
    _current_qp_map_key = elem_id;
    _current_qp_map_value = &_qp_to_value[elem_id];
  }
  auto & qp_data = *_current_qp_map_value;
  const auto qp = elem_qp.qp;
  const auto * const qrule = elem_qp.qrule;
  mooseAssert(qrule, "qrule must be non-null");
  return queryQpCache(qp, *qrule, qp_data, elem_qp, state);
}
operator()() [4/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 87 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(elem_side_qp, state);
  const Elem * const elem = elem_side_qp.elem;
  mooseAssert(elem, "elem must be non-null");
  const auto elem_id = elem->id();
  if (elem_id != _current_side_qp_map_key)
  {
    _current_side_qp_map_key = elem_id;
    _current_side_qp_map_value = &_side_qp_to_value[elem_id];
  }
  auto & side_qp_data = *_current_side_qp_map_value;
  const auto side = elem_side_qp.side;
  const auto qp = elem_side_qp.qp;
  const auto * const qrule = elem_side_qp.qrule;
  mooseAssert(qrule, "qrule must be non-null");
  // Check and see whether we even have sized for this side
  if (side >= side_qp_data.size())
    side_qp_data.resize(elem->n_sides());
  // Ok we were sized enough for our side
  auto & qp_data = side_qp_data[side];
  return queryQpCache(qp, *qrule, qp_data, elem_side_qp, state);
}
operator()() [5/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const FaceArg & face, const StateArg & state) const inherited
Definition at line 85 of file MooseFunctor.h.
{
  const auto face = checkFace(face_in);
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(face, state);
  mooseAssert(state.state == 0,
              "Cached evaluations are only currently supported for the current state.");
  return queryFVArgCache(_face_arg_to_value, face);
}
operator()() [6/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const NodeArg & node, const StateArg & state) const inherited
Definition at line 89 of file MooseFunctor.h.
{
  return evaluate(node, state);
}
order()
Order MooseVariableBase::order () const inherited
Get the order of this variable Note: Order enum can be implicitly converted to unsigned int.
Definition at line 149 of file MooseVariableBase.C.
{
  return _fe_type.order;
}
Referenced by FEProblemBase::checkDisplacementOrders(), AuxScalarKernel::compute(), ScalarInitialCondition::compute(), ADScalarKernel::computeADJacobian(), ODEKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVScalarLagrangeMultiplierConstraint::computeOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), DGFunctionDiffusionDirichletBC::computeQpJacobian(), DGDiffusionPostprocessorDirichletBC::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), ArrayIntegratedBC::computeQpOffDiagJacobianScalar(), ArrayKernel::computeQpOffDiagJacobianScalar(), DGFunctionDiffusionDirichletBC::computeQpResidual(), DGDiffusionPostprocessorDirichletBC::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), ODEKernel::computeResidual(), ODETimeKernel::computeResidual(), ADScalarKernel::computeResidual(), ScalarKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), ProjectionAux::computeValue(), ScalarCoupleable::coupledScalarOrder(), MultiAppPostprocessorToAuxScalarTransfer::execute(), FunctionScalarAux::FunctionScalarAux(), GapValueAux::GapValueAux(), ArrayDGDiffusion::initQpResidual(), NodalPatchRecovery::NodalPatchRecovery(), FEProblemBase::projectInitialConditionOnCustomRange(), ProjectionAux::ProjectionAux(), FEProblemBase::projectSolution(), ScalarComponentIC::ScalarComponentIC(), and MooseVariableBase::validParams().
paramError()
template<typename... Args> void MooseBaseParameterInterface::paramError (const std::string & param, Args... args) const inherited
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseError - only printing a message using the given args.
Definition at line 233 of file MooseBaseParameterInterface.h.
{
  Moose::show_trace = false;
  std::string msg = paramErrorMsg(param, std::forward<Args>(args)...);
  callMooseErrorRaw(msg, &_moose_base->getMooseApp());
  Moose::show_trace = true;
}
Referenced by HierarchicalGridPartitioner::_do_partition(), SetupDebugAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), ADDGKernel::ADDGKernel(), ReporterPointSource::addPoints(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ADNodalKernel::ADNodalKernel(), ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), AdvectiveFluxAux::AdvectiveFluxAux(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), ArrayBodyForce::ArrayBodyForce(), ArrayDGKernel::ArrayDGKernel(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayDirichletBC::ArrayDirichletBC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), ArrayPenaltyDirichletBC::ArrayPenaltyDirichletBC(), ArrayVacuumBC::ArrayVacuumBC(), BlockDeletionGenerator::BlockDeletionGenerator(), BlockWeightedPartitioner::BlockWeightedPartitioner(), BoundsAuxBase::BoundsAuxBase(), BreakMeshByBlockGenerator::BreakMeshByBlockGenerator(), BuildArrayVariableAux::BuildArrayVariableAux(), PiecewiseTabularBase::buildFromFile(), CartesianGridDivision::CartesianGridDivision(), UserObjectInterface::castUserObject(), checkComponent(), MeshGenerator::checkGetMesh(), PostprocessorInterface::checkParam(), Coupleable::checkVar(), MultiAppTransfer::checkVariable(), CircularBoundaryCorrectionGenerator::CircularBoundaryCorrectionGenerator(), CircularBoundaryCorrectionGenerator::circularCenterCalculator(), MultiAppGeneralFieldTransfer::closestToPosition(), CombinerGenerator::CombinerGenerator(), CompositionDT::CompositionDT(), ConcentricCircleMeshGenerator::ConcentricCircleMeshGenerator(), LibtorchNeuralNetControl::conditionalParameterError(), ConstantVectorPostprocessor::ConstantVectorPostprocessor(), ContainsPointAux::ContainsPointAux(), CopyValueAux::CopyValueAux(), Coupleable::Coupleable(), CoupledForceTempl< is_ad >::CoupledForceTempl(), CoupledValueFunctionMaterialTempl< is_ad >::CoupledValueFunctionMaterialTempl(), MultiApp::createApp(), MeshGeneratorSystem::createMeshGenerator(), CylindricalGridDivision::CylindricalGridDivision(), ConstantReporter::declareConstantReporterValues(), AccumulateReporter::declareLateValues(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DGLowerDKernel::DGLowerDKernel(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementLengthAux::ElementLengthAux(), ElementLpNormAux::ElementLpNormAux(), ElementValueSampler::ElementValueSampler(), ReporterPointSource::errorCheck(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), ExtraElementIDAux::ExtraElementIDAux(), ExtraElementIntegerDivision::ExtraElementIntegerDivision(), FEProblemSolve::FEProblemSolve(), FillBetweenCurvesGenerator::FillBetweenCurvesGenerator(), FillBetweenSidesetsGenerator::FillBetweenSidesetsGenerator(), ReporterPointSource::fillPoint(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), InternalSideIndicator::finalize(), FixedPointSolve::FixedPointSolve(), ForcingFunctionAux::ForcingFunctionAux(), FunctionArrayAux::FunctionArrayAux(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorAux::FunctorAux(), FunctorBinnedValuesDivision::FunctorBinnedValuesDivision(), FunctorElementalGradientAuxTempl< is_ad >::FunctorElementalGradientAuxTempl(), FunctorPositions::FunctorPositions(), FunctorVectorElementalAuxTempl< is_ad >::FunctorVectorElementalAuxTempl(), FVFluxBC::FVFluxBC(), FVInterfaceKernel::FVInterfaceKernel(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), FVTwoVarContinuityConstraint::FVTwoVarContinuityConstraint(), AdvancedExtruderGenerator::generate(), BlockDeletionGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundaryDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), BreakMeshByBlockGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), CombinerGenerator::generate(), ExplodeMeshGenerator::generate(), ExtraNodesetGenerator::generate(), FillBetweenCurvesGenerator::generate(), FillBetweenSidesetsGenerator::generate(), GeneratedMeshGenerator::generate(), MeshCollectionGenerator::generate(), MeshExtruderGenerator::generate(), ParsedCurveGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), PropertyReadFile::getBlockData(), PropertyReadFile::getData(), Sampler::getGlobalSamples(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), Sampler::getLocalSamples(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), Sampler::getNextLocalRow(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectName(), HFEMDirichletBC::HFEMDirichletBC(), MultiApp::init(), BlockWeightedPartitioner::initialize(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), PiecewiseConstantFromCSV::initialSetup(), LibtorchControlValuePostprocessor::initialSetup(), ReferenceResidualProblem::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), HistogramVectorPostprocessor::initialSetup(), AddMetaDataGenerator::inputChecker(), IntegratedBC::IntegratedBC(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceValueUserObjectAux::InterfaceValueUserObjectAux(), InterpolatedStatefulMaterialTempl< T >::InterpolatedStatefulMaterialTempl(), InversePowerMethod::InversePowerMethod(), IterationAdaptiveDT::IterationAdaptiveDT(), MultiApp::keepSolutionDuringRestore(), Kernel::Kernel(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LinearCombinationFunction::LinearCombinationFunction(), LowerDIntegratedBC::LowerDIntegratedBC(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), MaterialADConverterTempl< T >::MaterialADConverterTempl(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), PatternedMeshGenerator::mergeSubdomainNameMaps(), MeshCollectionGenerator::MeshCollectionGenerator(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshDivisionAux::MeshDivisionAux(), MeshGenerator::MeshGenerator(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarNodalAuxKernelTempl< ComputeValueType >::MortarNodalAuxKernelTempl(), MultiApp::moveApp(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), NestedDivision::NestedDivision(), NodalBC::NodalBC(), NodalEqualValueConstraint::NodalEqualValueConstraint(), NodalKernel::NodalKernel(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), NodalValueSampler::NodalValueSampler(), Output::Output(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), PatchMeshGenerator::PatchMeshGenerator(), PatternedMeshGenerator::PatternedMeshGenerator(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), PeriodicSegmentalConstraint::PeriodicSegmentalConstraint(), PIDTransientControl::PIDTransientControl(), PlaneDeletionGenerator::PlaneDeletionGenerator(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), PolyLineMeshGenerator::PolyLineMeshGenerator(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), LibmeshPartitioner::prepareBlocksForSubdomainPartitioner(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), PropertyReadFile::PropertyReadFile(), RandomIC::RandomIC(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readXda(), ReferenceResidualProblem::ReferenceResidualProblem(), RefineBlockGenerator::RefineBlockGenerator(), RefineSidesetGenerator::RefineSidesetGenerator(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setPartitioner(), TimeSequenceStepperBase::setupSequence(), SingleRankPartitioner::SingleRankPartitioner(), SphericalGridDivision::SphericalGridDivision(), SymmetryTransformGenerator::SymmetryTransformGenerator(), Terminator::Terminator(), TimeDerivativeAux::TimeDerivativeAux(), Transfer::Transfer(), TransformGenerator::TransformGenerator(), TransientMultiApp::TransientMultiApp(), ParsedCurveGenerator::tSectionSpaceDefiner(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), UserObject::UserObject(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), VolumeAux::VolumeAux(), XYDelaunayGenerator::XYDelaunayGenerator(), and XYMeshLineCutter::XYMeshLineCutter().
paramErrorMsg()
template<typename... Args> std::string MooseBaseParameterInterface::paramErrorMsg (const std::string & param, Args... args) const inline private inherited
Definition at line 171 of file MooseBaseParameterInterface.h.
  {
    auto param_prefix = paramErrorPrefix(_pars, param);
    // With no input location information, append object info (name + type)
    const std::string object_prefix =
        _pars.inputLocation(param).empty() ? objectErrorPrefix("parameter error") : "";
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    // Wrap error message to a separate line from param_prefix if it is about to
    // blow past 100 chars.  But only wrap if the param_prefix is long enough (12
    // chars) for the wrap to buy us much extra length. We don't check object_prefix
    // here because it will go before the parameter error
    if ((param_prefix.size() > 12 && msg.size() + param_prefix.size() > 99) ||
        msg.find("\n") != std::string::npos)
    {
      if (param_prefix.size() > 0 && param_prefix[param_prefix.size() - 1] != ':')
        param_prefix += ":";
      return object_prefix + param_prefix + "\n    " + MooseUtils::replaceAll(msg, "\n", "\n    ");
    }
    return object_prefix + param_prefix + " " + msg;
  }
Referenced by MooseBaseParameterInterface::paramError(), MooseBaseParameterInterface::paramInfo(), and MooseBaseParameterInterface::paramWarning().
parameters()
const InputParameters & MooseBaseParameterInterface::parameters () const inline inherited
Get the parameters of the object.
Returns
The parameters of the object
Definition at line 53 of file MooseBaseParameterInterface.h.
{ return _pars; }
Referenced by SetupDebugAction::act(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), FEProblemBase::addPostprocessor(), FEProblemBase::addPredictor(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), AdvancedOutput::AdvancedOutput(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), Moose::assemble_matrix(), AuxScalarKernel::AuxScalarKernel(), BoundsAuxBase::BoundsAuxBase(), MooseMesh::buildTypedMesh(), UserObjectInterface::castUserObject(), PostprocessorInterface::checkParam(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), Moose::compute_bounds(), Moose::compute_jacobian(), Moose::compute_nearnullspace(), Moose::compute_nullspace(), Moose::compute_postcheck(), Moose::compute_transpose_nullspace(), LibtorchNeuralNetControl::conditionalParameterError(), Console::Console(), MultiApp::createApp(), Postprocessor::declareValue(), DumpObjectsProblem::deduceNecessaryParameters(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), DumpObjectsProblem::dumpObjectHelper(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElectronsFromIonization::ElectronsFromIonization(), Executor::Executor(), Exodus::Exodus(), FEProblem::FEProblem(), FEProblemBase::FEProblemBase(), FixedPointSolve::FixedPointSolve(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GapValueAux::GapValueAux(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), MooseBaseParameterInterface::getCheckedPointerParam(), ExecutorInterface::getExecutor(), Material::getMaterial(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), UserObjectInterface::getUserObjectName(), VectorPostprocessorInterface::getVectorPostprocessorName(), GhostingUserObject::GhostingUserObject(), HphiRadialInterface::HphiRadialInterface(), AttribSystem::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), FullSolveMultiApp::initialSetup(), FEProblemBase::initNullSpaceVectors(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), isValid(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseAppCoordTransform::MooseAppCoordTransform(), MooseVariableInterface< T >::MooseVariableInterface(), MultiApp::MultiApp(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodeFaceConstraint::NodeFaceConstraint(), PatchMeshGenerator::PatchMeshGenerator(), PenetrationAux::PenetrationAux(), PicardSolve::PicardSolve(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), ProjectedStatefulMaterialStorageAction::processProperty(), MultiAppProjectionTransfer::projectSolution(), PropertyReadFile::PropertyReadFile(), PseudoTimestep::PseudoTimestep(), RandomIC::RandomIC(), InputParameterWarehouse::removeInputParameters(), OutputWarehouse::resetFileBase(), MooseAppCoordTransform::setCoordinateSystem(), FEProblemBase::setInputParametersFEProblem(), FEProblem::setInputParametersFEProblem(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SteffensenSolve::SteffensenSolve(), DumpObjectsProblem::stringifyParameters(), TaggingInterface::TaggingInterface(), Transfer::Transfer(), Transient::Transient(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
paramInfo()
template<typename... Args> void MooseBaseParameterInterface::paramInfo (const std::string & param, Args... args) const inherited
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseInfo - only printing a message using the given args.
Definition at line 250 of file MooseBaseParameterInterface.h.
{
  mooseInfo(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by TransientMultiApp::TransientMultiApp().
paramWarning()
template<typename... Args> void MooseBaseParameterInterface::paramWarning (const std::string & param, Args... args) const inherited
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseWarning - only printing a message using the given args.
Definition at line 243 of file MooseBaseParameterInterface.h.
{
  mooseWarning(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by MultiAppNearestNodeTransfer::execute(), FEProblemSolve::FEProblemSolve(), PlaneIDMeshGenerator::generate(), UniqueExtraIDMeshGenerator::generate(), Terminator::initialSetup(), and MooseMesh::MooseMesh().
phi()
const FieldVariablePhiValue & MooseVariableFE< Real >::phi () const inline override virtual inherited
Return the variable's elemental shape functions.
Implements MooseVariableField< OutputType >.
Definition at line 194 of file MooseVariableFE.h.
{ return _element_data->phi(); }
phiFace()
const FieldVariablePhiValue & MooseVariableFE< Real >::phiFace () const inline final override virtual inherited
Return the variable's shape functions on an element face.
Implements MooseVariableField< OutputType >.
Definition at line 207 of file MooseVariableFE.h.
{ return _element_data->phiFace(); }
phiFaceNeighbor()
const FieldVariablePhiValue & MooseVariableFE< Real >::phiFaceNeighbor () const inline final override virtual inherited
Return the variable's shape functions on a neighboring element face.
Implements MooseVariableField< OutputType >.
Definition at line 233 of file MooseVariableFE.h.
  {
    return _neighbor_data->phiFace();
  }
phiFaceNeighborSize()
virtual std::size_t MooseVariableFE< Real >::phiFaceNeighborSize () const inline final virtual inherited
Return phiFaceNeighbor size.
Implements MooseVariableFieldBase.
Definition at line 649 of file MooseVariableFE.h.
{ return _neighbor_data->phiFaceSize(); }
phiFaceSize()
virtual std::size_t MooseVariableFE< Real >::phiFaceSize () const inline final virtual inherited
Return phiFace size.
Implements MooseVariableFieldBase.
Definition at line 641 of file MooseVariableFE.h.
{ return _element_data->phiFaceSize(); }
phiLower()
virtual const FieldVariablePhiValue & MooseVariableFE< Real >::phiLower () const inline override virtual inherited
Return the variable's shape functions on a lower-dimensional element.
Implements MooseVariableField< OutputType >.
Definition at line 249 of file MooseVariableFE.h.
{ return _lower_data->phi(); }
phiLowerSize()
std::size_t MooseVariableFE< Real >::phiLowerSize () const inline final virtual inherited
Return the number of shape functions on the lower dimensional element for this variable.
Implements MooseVariableFieldBase.
Definition at line 651 of file MooseVariableFE.h.
{ return _lower_data->phiSize(); }
phiNeighbor()
const FieldVariablePhiValue & MooseVariableFE< Real >::phiNeighbor () const inline final override virtual inherited
Return the variable's shape functions on a neighboring element.
Implements MooseVariableField< OutputType >.
Definition at line 220 of file MooseVariableFE.h.
{ return _neighbor_data->phi(); }
phiNeighborSize()
virtual std::size_t MooseVariableFE< Real >::phiNeighborSize () const inline final virtual inherited
Return phiNeighbor size.
Implements MooseVariableFieldBase.
Definition at line 645 of file MooseVariableFE.h.
{ return _neighbor_data->phiSize(); }
phiSize()
virtual std::size_t MooseVariableFE< Real >::phiSize () const inline final virtual inherited
Return phi size.
Implements MooseVariableFieldBase.
Definition at line 637 of file MooseVariableFE.h.
{ return _element_data->phiSize(); }
prepare()
void MooseVariableFE< Real >::prepare override virtual inherited
Prepare the elemental degrees of freedom.
Implements MooseVariableFieldBase.
Definition at line 95 of file MooseVariableFE.C.
{
  _element_data->prepare();
}
prepareAux()
void MooseVariableFE< Real >::prepareAux override virtual inherited
Implements MooseVariableFieldBase.
Definition at line 100 of file MooseVariableFE.C.
{
  _element_data->prepareAux();
  _neighbor_data->prepareAux();
  _lower_data->prepareAux();
}
prepareIC()
void MooseVariableFE< Real >::prepareIC override virtual inherited
Prepare the initial condition.
Implements MooseVariableFieldBase.
Definition at line 98 of file MooseVariableFE.C.
{
  _element_data->prepareIC();
}
prepareLowerD()
void MooseVariableFE< Real >::prepareLowerD override virtual inherited
Prepare a lower dimensional element's degrees of freedom.
Implements MooseVariableFieldBase.
Definition at line 97 of file MooseVariableFE.C.
{
  _lower_data->prepare();
}
prepareNeighbor()
void MooseVariableFE< Real >::prepareNeighbor override virtual inherited
Prepare the neighbor element degrees of freedom.
Implements MooseVariableFieldBase.
Definition at line 96 of file MooseVariableFE.C.
{
  _neighbor_data->prepare();
}
queryFVArgCache()
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::queryFVArgCache (std::map< SpaceArg, ValueType > & cache_data, const SpaceArg & space) const private inherited
check a finite volume spatial argument cache and if invalid then evaluate
Definition at line 407 of file MooseFunctor.h.
{
  // We don't want to evaluate if the key already exists, so instead we value initialize
  auto [it, inserted] = cache_data.try_emplace(space, ValueType());
  auto & value = it->second;
  if (inserted)
    // value not ready to go
    // this function is only called from functions that assert we are in the current time state
    value = evaluate(space, currentState());
  return value;
}
queryQpCache()
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::queryQpCache (unsigned int qp, const QBase & qrule, std::vector< std::pair< bool, Moose::ADType< OutputType >::type > > & qp_cache_data, const SpaceArg & space, const StateArg & state) const private inherited
check a qp cache and if invalid then evaluate
Definition at line 397 of file MooseFunctor.h.
{
  // Check and see whether we even have sized for this quadrature point. If we haven't then we
  // must evaluate
  if (qp >= qp_cache_data.size())
  {
    qp_cache_data.resize(qrule.n_points(), std::make_pair(false, ValueType()));
    auto & pr = qp_cache_data[qp];
    pr.second = evaluate(space, state);
    pr.first = true;
    return pr.second;
  }
  // We've already sized for this qp, so let's see whether we have a valid cache value
  auto & pr = qp_cache_data[qp];
  if (pr.first)
    return pr.second;
  // No valid cache value so evaluate
  pr.second = evaluate(space, state);
  pr.first = true;
  return pr.second;
}
reinitAux()
void MooseVariableFE< Real >::reinitAux override virtual inherited
Implements MooseVariableFieldBase.
Definition at line 103 of file MooseVariableFE.C.
{
  _element_data->reinitAux();
}
reinitAuxNeighbor()
void MooseVariableFE< Real >::reinitAuxNeighbor override virtual inherited
Implements MooseVariableFieldBase.
Definition at line 104 of file MooseVariableFE.C.
{
  _neighbor_data->reinitAux();
}
reinitNode()
void MooseVariableFE< Real >::reinitNode override virtual inherited
Implements MooseVariableFieldBase.
Definition at line 102 of file MooseVariableFE.C.
{
  _element_data->reinitNode();
}
reinitNodes()
void MooseVariableFE< Real >::reinitNodes (const std::vector< dof_id_type > & nodes) override virtual inherited
Implements MooseVariableFieldBase.
Definition at line 106 of file MooseVariableFE.C.
{
  _element_data->reinitNodes(nodes);
}
reinitNodesNeighbor()
void MooseVariableFE< Real >::reinitNodesNeighbor (const std::vector< dof_id_type > & nodes) override virtual inherited
Implements MooseVariableFieldBase.
Definition at line 107 of file MooseVariableFE.C.
{
  _neighbor_data->reinitNodes(nodes);
}
residualSetup()
void MooseVariableFE< Real >::residualSetup override virtual inherited
Reimplemented from MooseVariableField< OutputType >.
Definition at line 705 of file MooseVariableFE.C.
{
  _current_elem_qp_functor_elem = nullptr;
  _current_elem_side_qp_functor_elem_side = std::make_pair(nullptr, libMesh::invalid_uint);
  MooseVariableField<OutputType>::residualSetup();
}
scalingFactor() [1/3]
Real MooseVariableBase::scalingFactor () const inline inherited
Get the scaling factor for this variable.
Definition at line 96 of file MooseVariableBase.h.
{ return _scaling_factor[0]; }
Referenced by MooseVariableBase::MooseVariableBase().
scalingFactor() [2/3]
void MooseVariableBase::scalingFactor (const std::vector< Real > & factor) inherited
Definition at line 181 of file MooseVariableBase.C.
{
  _scaling_factor = factor;
}
scalingFactor() [3/3]
void MooseVariableBase::scalingFactor (Real factor) inherited
Set the scaling factor for this variable.
Definition at line 175 of file MooseVariableBase.C.
{
  _scaling_factor.assign(_count, factor);
}
Referenced by ADScalarKernel::computeADJacobian(), ADDGKernel::computeElemNeighJacobian(), ADMortarScalarBase::computeJacobian(), FVElementalKernel::computeJacobian(), ADKernelScalarBase::computeJacobian(), ADNodalKernel::computeJacobian(), NodalKernel::computeJacobian(), FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVScalarLagrangeMultiplierInterface::computeJacobian(), ADMortarConstraint::computeJacobian(), NodalConstraint::computeJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), FVScalarLagrangeMultiplierConstraint::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), ADMortarScalarBase::computeResidual(), MortarScalarBase::computeResidual(), ADKernelScalarBase::computeResidual(), ADNodalKernel::computeResidual(), NodalKernel::computeResidual(), TimeNodalKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), FVScalarLagrangeMultiplierInterface::computeResidual(), NodalConstraint::computeResidual(), FVElementalKernel::computeResidualAndJacobian(), ADKernelScalarBase::computeResidualAndJacobian(), FVScalarLagrangeMultiplierConstraint::computeResidualAndJacobian(), MortarScalarBase::computeScalarJacobian(), KernelScalarBase::computeScalarJacobian(), MortarScalarBase::computeScalarOffDiagJacobian(), KernelScalarBase::computeScalarOffDiagJacobian(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarResidual(), ScalarTagMatrixAux::computeValue(), ScalarTagVectorAux::computeValue(), TagMatrixAux::computeValue(), TagVectorAux::computeValue(), and ReferenceResidualProblem::initialSetup().
secondPhi()
const MooseVariableFE< Real >::FieldVariablePhiSecond & MooseVariableFE< Real >::secondPhi final override virtual inherited
Return the rank-2 tensor of second derivatives of the variable's elemental shape functions.
Implements MooseVariableField< OutputType >.
Definition at line 203 of file MooseVariableFE.C.
{
  return _element_data->secondPhi();
}
secondPhiFace()
const MooseVariableFE< Real >::FieldVariablePhiSecond & MooseVariableFE< Real >::secondPhiFace final override virtual inherited
Return the rank-2 tensor of second derivatives of the variable's shape functions on an element face.
Implements MooseVariableField< OutputType >.
Definition at line 216 of file MooseVariableFE.C.
{
  return _element_data->secondPhiFace();
}
secondPhiFaceNeighbor()
const MooseVariableFE< Real >::FieldVariablePhiSecond & MooseVariableFE< Real >::secondPhiFaceNeighbor final override virtual inherited
Return the rank-2 tensor of second derivatives of the variable's shape functions on a neighboring element face.
Implements MooseVariableField< OutputType >.
Definition at line 245 of file MooseVariableFE.C.
{
  return _neighbor_data->secondPhiFace();
}
secondPhiNeighbor()
const MooseVariableFE< Real >::FieldVariablePhiSecond & MooseVariableFE< Real >::secondPhiNeighbor final override virtual inherited
Return the rank-2 tensor of second derivatives of the variable's shape functions on a neighboring element.
Implements MooseVariableField< OutputType >.
Definition at line 229 of file MooseVariableFE.C.
{
  return _neighbor_data->secondPhi();
}
secondSln()
const FieldVariableSecond & MooseVariableFE< Real >::secondSln () const inline inherited
element seconds
Definition at line 316 of file MooseVariableFE.h.
{ return _element_data->secondSln(Moose::Current); }
secondSlnNeighbor()
const FieldVariableSecond & MooseVariableFE< Real >::secondSlnNeighbor () const inline inherited
neighbor solution seconds
Definition at line 442 of file MooseVariableFE.h.
  {
    return _neighbor_data->secondSln(Moose::Current);
  }
secondSlnOld()
const FieldVariableSecond & MooseVariableFE< Real >::secondSlnOld () const inline inherited
Definition at line 317 of file MooseVariableFE.h.
{ return _element_data->secondSln(Moose::Old); }
secondSlnOlder()
const FieldVariableSecond & MooseVariableFE< Real >::secondSlnOlder () const inline inherited
Definition at line 318 of file MooseVariableFE.h.
  {
    return _element_data->secondSln(Moose::Older);
  }
secondSlnOlderNeighbor()
const FieldVariableSecond & MooseVariableFE< Real >::secondSlnOlderNeighbor () const inline inherited
Definition at line 450 of file MooseVariableFE.h.
  {
    return _neighbor_data->secondSln(Moose::Older);
  }
secondSlnOldNeighbor()
const FieldVariableSecond & MooseVariableFE< Real >::secondSlnOldNeighbor () const inline inherited
Definition at line 446 of file MooseVariableFE.h.
  {
    return _neighbor_data->secondSln(Moose::Old);
  }
secondSlnPreviousNL()
const FieldVariableSecond & MooseVariableFE< Real >::secondSlnPreviousNL () const inline inherited
Definition at line 322 of file MooseVariableFE.h.
  {
    return _element_data->secondSln(Moose::PreviousNL);
  }
secondSlnPreviousNLNeighbor()
const FieldVariableSecond & MooseVariableFE< Real >::secondSlnPreviousNLNeighbor () const inline inherited
Definition at line 454 of file MooseVariableFE.h.
  {
    return _neighbor_data->secondSln(Moose::PreviousNL);
  }
setActiveTags()
void MooseVariableFE< Real >::setActiveTags (const std::set< TagID > & vtags) override virtual inherited
Set the active vector tags.
Parameters
vtags Additional vector tags that this variable will need to query at dof indices for, in addition to our own required solution tags
Reimplemented from MooseVariableBase.
Definition at line 702 of file MooseVariableFE.h.
{
  _element_data->setActiveTags(vtags);
  _neighbor_data->setActiveTags(vtags);
  _lower_data->setActiveTags(vtags);
}
setCacheClearanceSchedule()
void Moose::FunctorBase< Moose::ADType< OutputType >::type >::setCacheClearanceSchedule (const std::set< ExecFlagType > & clearance_schedule) inherited
Set how often to clear the functor evaluation cache.
Definition at line 139 of file MooseFunctor.h.
{
  _clearance_schedule = clearance_schedule;
}
setDofValue()
void MooseVariableFE< Real >::setDofValue (const OutputData & value, unsigned int index) override virtual inherited
Degree of freedom value setters.
Implements MooseVariableField< OutputType >.
Definition at line 509 of file MooseVariableFE.C.
{
  _element_data->setDofValue(value, index);
}
setDofValues()
void MooseVariableFE< Real >::setDofValues (const DenseVector< OutputData > & values) override virtual inherited
Set local DOF values and evaluate the values on quadrature points.
Implements MooseVariableField< OutputType >.
Definition at line 514 of file MooseVariableFE.C.
{
  _element_data->setDofValues(values);
}
setNodalValue()
void MooseVariableFE< Real >::setNodalValue (const Real & value, unsigned int idx = 0) override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 507 of file MooseVariableFE.C.
{
  _element_data->setNodalValue(value, idx);
}
sln()
const FieldVariableValue & MooseVariableFE< Real >::sln () const inline override virtual inherited
element solutions
Implements MooseVariableField< OutputType >.
Definition at line 288 of file MooseVariableFE.h.
{ return _element_data->sln(Moose::Current); }
slnLower()
const FieldVariableValue & MooseVariableFE< Real >::slnLower () const inline inherited
Definition at line 497 of file MooseVariableFE.h.
{ return _lower_data->sln(Moose::Current); }
slnLowerOld()
const FieldVariableValue & MooseVariableFE< Real >::slnLowerOld () const inline inherited
Definition at line 498 of file MooseVariableFE.h.
{ return _lower_data->sln(Moose::Old); }
slnNeighbor()
const FieldVariableValue & MooseVariableFE< Real >::slnNeighbor () const inline override virtual inherited
neighbor solutions
Implements MooseVariableField< OutputType >.
Definition at line 402 of file MooseVariableFE.h.
  {
    return _neighbor_data->sln(Moose::Current);
  }
slnOld()
const FieldVariableValue & MooseVariableFE< Real >::slnOld () const inline override virtual inherited
Returns
the old elemental solution, e.g. that of the previous timestep
Implements MooseVariableField< OutputType >.
Definition at line 289 of file MooseVariableFE.h.
{ return _element_data->sln(Moose::Old); }
slnOlder()
const FieldVariableValue & MooseVariableFE< Real >::slnOlder () const inline override virtual inherited
Returns
the older elemental solution, e.g. that of two timesteps ago
Implements MooseVariableField< OutputType >.
Definition at line 290 of file MooseVariableFE.h.
{ return _element_data->sln(Moose::Older); }
slnOlderNeighbor()
const FieldVariableValue & MooseVariableFE< Real >::slnOlderNeighbor () const inline inherited
Definition at line 410 of file MooseVariableFE.h.
{ return _neighbor_data->sln(Moose::Older); }
slnOldNeighbor()
const FieldVariableValue & MooseVariableFE< Real >::slnOldNeighbor () const inline override virtual inherited
Returns
the old neighbor solution, e.g. that of the previous timestep
Implements MooseVariableField< OutputType >.
Definition at line 406 of file MooseVariableFE.h.
  {
    return _neighbor_data->sln(Moose::Old);
  }
slnPreviousNL()
const FieldVariableValue & MooseVariableFE< Real >::slnPreviousNL () const inline inherited
Definition at line 291 of file MooseVariableFE.h.
{ return _element_data->sln(Moose::PreviousNL); }
slnPreviousNLNeighbor()
const FieldVariableValue & MooseVariableFE< Real >::slnPreviousNLNeighbor () const inline inherited
Definition at line 411 of file MooseVariableFE.h.
  {
    return _neighbor_data->sln(Moose::PreviousNL);
  }
subdomainSetup()
void SetupInterface::subdomainSetup () virtual inherited
Gets called when the subdomain changes (i.e.
in a Jacobian or residual loop) and before this object is asked to do its job
Reimplemented in Material, MaterialBase, GeneralUserObject, NodalUserObject, ThreadedGeneralUserObject, and Constraint.
Definition at line 60 of file SetupInterface.C.
{
}
sys() [1/2]
SystemBase & MooseVariableBase::sys () inline inherited
Get the system this variable is part of.
Definition at line 59 of file MooseVariableBase.h.
{ return _sys; }
Referenced by ADDGKernel::ADDGKernel(), FEProblemBase::addInitialCondition(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), MultiAppConservativeTransfer::adjustTransferredSolution(), MultiAppConservativeTransfer::adjustTransferredSolutionNearestPoint(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldShapeEvaluationTransfer::buildMeshFunctions(), MooseMesh::cacheFaceInfoVariableOwnership(), FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), FVFluxBC::computeResidual(), FVInterfaceKernel::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), Moose::FV::determineElemOneAndTwo(), DGKernel::DGKernel(), MultiAppGeometricInterpolationTransfer::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), MultiAppGeometricInterpolationTransfer::fillSourceInterpolationPoints(), FVBoundaryCondition::hasFaceSide(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), MultiAppGeometricInterpolationTransfer::interpolateTargetPoints(), Kernel::Kernel(), NodalBC::NodalBC(), NodalKernel::NodalKernel(), Exodus::outputScalarVariables(), Nemesis::outputScalarVariables(), TableOutput::outputScalarVariables(), FEProblemBase::projectInitialConditionOnCustomRange(), FEProblemBase::projectSolution(), MultiAppProjectionTransfer::projectSolution(), MooseVariableScalar::reinit(), FVInterfaceKernel::setupData(), MultiAppDofCopyTransfer::transfer(), MultiAppDofCopyTransfer::transferDofObject(), MultiAppShapeEvaluationTransfer::transferVariable(), FVFluxBC::uOnGhost(), and FVFluxBC::uOnUSub().
sys() [2/2]
const SystemBase & MooseVariableBase::sys () const inline inherited
Get the system this variable is part of.
Definition at line 64 of file MooseVariableBase.h.
{ return _sys; }
timestepSetup()
template<typename OutputType > void MooseVariableField< OutputType >::timestepSetup override virtual inherited
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Reimplemented in MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 52 of file MooseVariableField.C.
{
  MooseVariableFieldBase::timestepSetup();
  FunctorBase<typename Moose::ADType<OutputType>::type>::timestepSetup();
}
Referenced by MooseVariableFV< OutputType >::timestepSetup().
totalVarDofs()
unsigned int MooseVariableBase::totalVarDofs () inline inherited
Definition at line 80 of file MooseVariableBase.h.
{ return allDofIndices().size(); }
type()
const std::string & MooseBase::type () const inline inherited
Get the type of this class.
Returns
the name of the type of this class
Definition at line 41 of file MooseBase.h.
{ return _type; }
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), CreateProblemDefaultAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetupDebugAction::act(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::addDistribution(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addObject(), DistributedRectilinearMeshGenerator::addPoint(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), PhysicsBasedPreconditioner::addSystem(), FEProblemBase::addTimeIntegrator(), SubProblem::addVectorTag(), DisplacedProblem::addVectorTag(), FEProblemBase::advanceMultiApps(), FEProblemBase::backupMultiApps(), BoundaryPreservedMarker::BoundaryPreservedMarker(), DistributedRectilinearMeshGenerator::buildCube(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildPRefinementAndCoarseningMaps(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), FEProblemBase::computeAuxiliaryKernels(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpJacobian(), HFEMDirichletBC::computeLowerDQpJacobian(), ArrayHFEMDiffusion::computeLowerDQpJacobian(), HFEMDiffusion::computeLowerDQpJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), FEProblemBase::computeMultiAppsDT(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), DGCoupledAdvection::computeOffDiagJacobianHelper(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ScalarKernel::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueBoundaryConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), LinearNodalConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), DGConvection::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), InterfaceDiffusion::computeQpJacobian(), InterfaceReaction::computeQpJacobian(), DGCoupledAdvection::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), DGFunctionTemperatureAdvection::computeQpJacobian(), DGTemperatureAdvection::computeQpJacobian(), InterTemperatureAdvection::computeQpJacobian(), CoupledTiedValueConstraint::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), HFEMTestJump::computeQpOffDiagJacobian(), HFEMTrialJump::computeQpOffDiagJacobian(), DGCoupledAdvection::computeQpOffDiagJacobian(), ScalarKernel::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), EqualValueBoundaryConstraint::computeQpResidual(), EqualValueEmbeddedConstraint::computeQpResidual(), LinearNodalConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), DGConvection::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), DGEFieldAdvection::computeQpResidual(), HphiRadialInterface::computeQpResidual(), InterfaceAdvection::computeQpResidual(), InterfaceLogDiffusionElectrons::computeQpResidual(), PotentialSurfaceCharge::computeQpResidual(), ADDGAdvection::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), HFEMDiffusion::computeQpResidual(), HFEMTestJump::computeQpResidual(), HFEMTrialJump::computeQpResidual(), InterfaceDiffusion::computeQpResidual(), InterfaceReaction::computeQpResidual(), DGCoupledAdvection::computeQpResidual(), DGFunctionConvection::computeQpResidual(), DGFunctionTemperatureAdvection::computeQpResidual(), DGTemperatureAdvection::computeQpResidual(), InterTemperatureAdvection::computeQpResidual(), ArrayDGDiffusion::computeQpResidual(), ArrayHFEMDiffusion::computeQpResidual(), FEProblemBase::computeUserObjectByName(), FEProblemBase::computeUserObjects(), FEProblemBase::computeUserObjectsInternal(), BatchMaterial< Tuple, Output, Input >::construct(), DisplacedProblem::createQRules(), FEProblemBase::createQRules(), MeshGenerator::declareMeshProperty(), DumpObjectsProblem::deduceNecessaryParameters(), DumpObjectsProblem::dumpObjectHelper(), FEProblemBase::duplicateVariableCheck(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), MooseBaseErrorInterface::errorPrefix(), AB2PredictorCorrector::estimateTimeError(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finishMultiAppStep(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), ElementSubdomainIDGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), PatternedMeshGenerator::generate(), MeshGenerator::generateInternal(), MultiAppTransfer::getAppInfo(), TransfiniteMeshGenerator::getEdge(), ElementGenerator::getElemType(), FEProblemBase::getMaterial(), FEProblemBase::getMaterialData(), MaterialOutputAction::getParams(), ReporterData::getReporterInfo(), Transient::getTimeIntegratorName(), FEProblemBase::getTransfers(), SubProblem::getVectorTags(), DisplacedProblem::getVectorTags(), CommonOutputAction::hasConsole(), FEProblemBase::hasMultiApps(), AdvancedOutput::hasOutput(), FEProblemBase::incrementMultiAppTStep(), AdvancedOutput::initAvailableLists(), FunctorPositions::initialize(), FunctorTimes::initialize(), MultiAppConservativeTransfer::initialSetup(), ArrayDGDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), RelationshipManager::isType(), FEProblemBase::logAdd(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), SubProblem::numVectorTags(), DisplacedProblem::numVectorTags(), MooseBaseParameterInterface::objectErrorPrefix(), AdvancedOutput::output(), Console::output(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), ProjectedStatefulMaterialStorageAction::processProperty(), SolutionInvalidInterface::registerInvalidSolutionInternal(), FEProblemBase::restoreMultiApps(), MeshRepairGenerator::separateSubdomainsByElementType(), FEProblemBase::setCoupling(), MooseBase::typeAndName(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), DisplacedProblem::updateGeomSearch(), FEProblemBase::updateGeomSearch(), UserObjectInterface::userObjectType(), and AdvancedOutput::wantOutput().
typeAndName()
std::string MooseBase::typeAndName () const inline inherited
Get the class's combined type and name; useful in error handling.
Returns
The type and name of this class in the form '<type()> "<name()>"'.
Definition at line 53 of file MooseBase.h.
  {
    return type() + std::string(" \"") + name() + std::string("\"");
  }
Referenced by ReporterContext< T >::finalize(), and ReporterData::getReporterInfo().
uDot()
const FieldVariableValue & MooseVariableFE< Real >::uDot () const inline inherited
element dots
Definition at line 394 of file MooseVariableFE.h.
{ return _element_data->uDot(); }
uDotDot()
const FieldVariableValue & MooseVariableFE< Real >::uDotDot () const inline inherited
Definition at line 395 of file MooseVariableFE.h.
{ return _element_data->uDotDot(); }
uDotDotNeighbor()
const FieldVariableValue & MooseVariableFE< Real >::uDotDotNeighbor () const inline inherited
Definition at line 489 of file MooseVariableFE.h.
{ return _neighbor_data->uDotDot(); }
uDotDotOld()
const FieldVariableValue & MooseVariableFE< Real >::uDotDotOld () const inline inherited
Definition at line 397 of file MooseVariableFE.h.
{ return _element_data->uDotDotOld(); }
uDotDotOldNeighbor()
const FieldVariableValue & MooseVariableFE< Real >::uDotDotOldNeighbor () const inline inherited
Definition at line 491 of file MooseVariableFE.h.
{ return _neighbor_data->uDotDotOld(); }
uDotNeighbor()
const FieldVariableValue & MooseVariableFE< Real >::uDotNeighbor () const inline inherited
neighbor dots
Definition at line 488 of file MooseVariableFE.h.
{ return _neighbor_data->uDot(); }
uDotOld()
const FieldVariableValue & MooseVariableFE< Real >::uDotOld () const inline inherited
Definition at line 396 of file MooseVariableFE.h.
{ return _element_data->uDotOld(); }
uDotOldNeighbor()
const FieldVariableValue & MooseVariableFE< Real >::uDotOldNeighbor () const inline inherited
Definition at line 490 of file MooseVariableFE.h.
{ return _neighbor_data->uDotOld(); }
uniqueName()
MooseObjectName MooseBaseParameterInterface::uniqueName () const inline inherited
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
Definition at line 58 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectName(_pars.get<std::string>("_unique_name"));
  }
Referenced by MooseBaseParameterInterface::connectControllableParams(), and Action::uniqueActionName().
uniqueParameterName()
MooseObjectParameterName MooseBaseParameterInterface::uniqueParameterName (const std::string & parameter_name) const inline inherited
The unique parameter name of a valid parameter of this object for accessing parameter controls.
Definition at line 43 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectParameterName(
        _pars.get<std::string>("_moose_base"), _moose_base->name(), parameter_name);
  }
useDual()
bool MooseVariableBase::useDual () const inline inherited
Get dual mortar option.
Definition at line 74 of file MooseVariableBase.h.
{ return _use_dual; }
Referenced by MortarConstraintBase::MortarConstraintBase().
usesGradPhi()
bool MooseVariableFE< Real >::usesGradPhi () const inline inherited
Whether or not this variable is actually using the shape function gradient.
Currently hardcoded to true because we always compute the value.
Definition at line 120 of file MooseVariableFE.h.
{ return true; }
usesGradPhiNeighbor()
template<typename OutputType > bool MooseVariableField< OutputType >::usesGradPhiNeighbor () const inline inherited
Whether or not this variable is actually using the shape function gradient.
Currently hardcoded to true because we always compute the value.
Definition at line 319 of file MooseVariableField.h.
{ return true; }
Referenced by Assembly::copyNeighborShapes().
usesPhi()
bool MooseVariableFE< Real >::usesPhi () const inline inherited
Whether or not this variable is actually using the shape function value.
Currently hardcoded to true because we always compute the value.
Definition at line 114 of file MooseVariableFE.h.
{ return true; }
usesPhiNeighbor()
template<typename OutputType > bool MooseVariableField< OutputType >::usesPhiNeighbor () const inline inherited
Whether or not this variable is actually using the shape function value.
Currently hardcoded to true because we always compute the value.
Definition at line 312 of file MooseVariableField.h.
{ return true; }
Referenced by Assembly::copyNeighborShapes().
usesSecondPhi()
bool MooseVariableFE< Real >::usesSecondPhi inherited
Whether or not this variable is computing any second derivatives.
Definition at line 125 of file MooseVariableFE.C.
{
  return _element_data->usesSecondPhi();
}
usesSecondPhiNeighbor()
bool MooseVariableFE< Real >::usesSecondPhiNeighbor final override virtual inherited
Whether or not this variable is actually using the shape function second derivative on a neighbor.
Implements MooseVariableField< OutputType >.
Definition at line 131 of file MooseVariableFE.C.
{
  return _neighbor_data->usesSecondPhi();
}
validParams()
InputParameters MooseVariableConstMonomial::validParams () static
Definition at line 21 of file MooseVariableConstMonomial.C.
{
  auto params = MooseVariableBase::validParams();
  params.addClassDescription("Specialization for constant monomials that avoids unnecessary loops");
  params.set<MooseEnum>("family") = "MONOMIAL";
  params.set<MooseEnum>("order") = "CONSTANT";
  return params;
}
vectorTagDofValue()
const DoFValue & MooseVariableFE< Real >::vectorTagDofValue (TagID tag) const inline override virtual inherited
Implements MooseVariableField< OutputType >.
Definition at line 278 of file MooseVariableFE.h.
  {
    return _element_data->vectorTagDofValue(tag);
  }
vectorTagGradient()
const FieldVariableGradient & MooseVariableFE< Real >::vectorTagGradient (TagID tag) const inline inherited
Definition at line 274 of file MooseVariableFE.h.
  {
    return _element_data->vectorTagGradient(tag);
  }
vectorTagValue()
const FieldVariableValue & MooseVariableFE< Real >::vectorTagValue (TagID tag) const inline override virtual inherited
tag values getters
Implements MooseVariableField< OutputType >.
Definition at line 270 of file MooseVariableFE.h.
  {
    return _element_data->vectorTagValue(tag);
  }
Member Data Documentation
_action_factory
ActionFactory& MooseBaseParameterInterface::_action_factory protected inherited
Builds Actions.
Definition at line 164 of file MooseBaseParameterInterface.h.
Referenced by CommonOutputAction::create(), AddVariableAction::createInitialConditionAction(), AddSpecies::createInitialConditions(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
_ad_real_dummy
template<typename OutputType > ADReal MooseVariableField< OutputType >::_ad_real_dummy = 0 mutable protected inherited
A dummy ADReal variable.
Definition at line 382 of file MooseVariableField.h.
_app
MooseApp& MooseBase::_app protected inherited
The MOOSE application this is associated with.
Definition at line 60 of file MooseBase.h.
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), MeshGenerator::addChildMeshGenerator(), FEProblemBase::addMaterialHelper(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addOutput(), MeshGenerator::addParentMeshGenerator(), FVFluxKernel::adjustRMGhostLayers(), FEProblemBase::allowOutput(), AStableDirk4::AStableDirk4(), FileMesh::buildMesh(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), MeshGenerator::checkGetMesh(), FEProblemBase::checkICRestartError(), FEProblemBase::checkNonlinearConvergence(), OversampleOutput::cloneMesh(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), Console::Console(), TimeStepper::constrainStep(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::createLocalApp(), FEProblemBase::customSetup(), MeshGenerator::declareMeshProperty(), MeshGenerator::declareNullMeshName(), MooseMesh::determineUseDistributedMesh(), DumpObjectsProblem::dumpObjectHelper(), DumpObjectsProblem::dumpVariableHelper(), EigenExecutionerBase::EigenExecutionerBase(), EigenKernel::EigenKernel(), PIDTransientControl::execute(), Eigenvalue::execute(), InversePowerMethod::execute(), NonlinearEigen::execute(), Steady::execute(), Transient::execute(), PseudoTimestep::execute(), IterationInfo::execute(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FileOutput::FileOutput(), ChangeOverFixedPointPostprocessor::finalize(), RadialAverage::finalize(), FixedPointSolve::FixedPointSolve(), FEProblemBase::forceOutput(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), SideSetsFromNormalsGenerator::generate(), MeshGenerator::generateInternal(), FEProblemBase::getExecutor(), MeshGenerator::getMeshByName(), NumFixedPointIterations::getValue(), NumRelationshipManagers::getValue(), GhostingUserObject::GhostingUserObject(), MooseMesh::init(), InversePowerMethod::init(), NonlinearEigen::init(), Transient::init(), FEProblemBase::init(), TimePeriod::initialSetup(), Console::initialSetup(), AdvancedOutput::initOutputList(), FEProblemBase::initPetscOutput(), EigenProblem::initPetscOutput(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MeshGenerator::MeshGenerator(), EigenExecutionerBase::normalizeSolution(), NumFailedTimeSteps::NumFailedTimeSteps(), AugmentSparsityOnInterface::operator()(), Checkpoint::output(), Exodus::output(), Nemesis::output(), PerfGraphOutput::output(), Tecplot::output(), MortarNodalGeometryOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Exodus::outputEmptyTimestep(), Console::outputInput(), Exodus::outputInput(), Exodus::outputNodalVariables(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), Console::outputSystemInformation(), JSONOutput::outputSystemInformation(), MultiApp::parentOutputPositionChanged(), PIDTransientControl::PIDTransientControl(), Transient::preExecute(), Eigenvalue::prepareSolverOptions(), FEProblemBase::projectSolution(), MultiApp::setAppOutputFileBase(), FileOutput::setFileBaseInternal(), MeshGenerator::setMeshProperty(), MeshGenerator::setMeshPropertyHelper(), FEProblemBase::setRestartFile(), TransientMultiApp::setupApp(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SolutionInvalidityReporter::SolutionInvalidityReporter(), FEProblemBase::solve(), EigenProblem::solve(), PetscOutput::solveSetup(), TransientMultiApp::solveStep(), FEProblemBase::subdomainSetup(), FEProblemBase::theWarehouse(), TimeExtremeValue::TimeExtremeValue(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), Transient::Transient(), FEProblemBase::updateMortarMesh(), Console::write(), and FEProblemBase::~FEProblemBase().
_assembly
Assembly& MooseVariableBase::_assembly protected inherited
Assembly data.
Definition at line 212 of file MooseVariableBase.h.
Referenced by MooseVariableFE< OutputType >::MooseVariableFE(), and MooseVariableFV< OutputType >::MooseVariableFV().
_blk_dim
unsigned int BlockRestrictable::_blk_dim private inherited
Largest mesh dimension of the elements in the blocks for this object.
Definition at line 259 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blocksMaxDimension(), and BlockRestrictable::initializeBlockRestrictable().
_blk_dual_restrictable
const bool BlockRestrictable::_blk_dual_restrictable private inherited
Flag for allowing dual restriction.
Definition at line 238 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_blk_feproblem
FEProblemBase* BlockRestrictable::_blk_feproblem private inherited
Pointer to FEProblemBase.
Definition at line 241 of file BlockRestrictable.h.
Referenced by BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), and BlockRestrictable::initializeBlockRestrictable().
_blk_ids
std::set<SubdomainID> BlockRestrictable::_blk_ids private inherited
Set of block ids supplied by the user via the input file (for error checking)
Definition at line 229 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blockIDs(), BlockRestrictable::blockRestricted(), BlockRestrictable::checkVariable(), BlockRestrictable::hasBlocks(), BlockRestrictable::initializeBlockRestrictable(), BlockRestrictable::isBlockSubset(), and BlockRestrictable::numBlocks().
_blk_material_data
const MaterialData* BlockRestrictable::_blk_material_data protected inherited
Pointer to the MaterialData class for this object.
Definition at line 207 of file BlockRestrictable.h.
Referenced by BlockRestrictable::hasBlockMaterialProperty(), and BlockRestrictable::initializeBlockRestrictable().
_blk_mesh
MooseMesh* BlockRestrictable::_blk_mesh private inherited
Pointer to Mesh.
Definition at line 244 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blockIDs(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlocks(), BlockRestrictable::initializeBlockRestrictable(), BlockRestrictable::isBlockSubset(), and BlockRestrictable::meshBlockIDs().
_blk_name
const std::string& BlockRestrictable::_blk_name private inherited
Name of the object.
Definition at line 256 of file BlockRestrictable.h.
Referenced by BlockRestrictable::checkVariable(), and BlockRestrictable::initializeBlockRestrictable().
_blk_tid
THREAD_ID BlockRestrictable::_blk_tid private inherited
Thread id for this object.
Definition at line 253 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_blocks
std::vector<SubdomainName> BlockRestrictable::_blocks private inherited
Vector the block names supplied by the user via the input file.
Definition at line 235 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blocks(), and BlockRestrictable::initializeBlockRestrictable().
_boundary_ids
const std::set<BoundaryID>& BlockRestrictable::_boundary_ids private inherited
Reference to the boundary_ids, defaults to an empty set if not provided.
Definition at line 250 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_clearance_schedule
std::set<ExecFlagType> Moose::FunctorBase< Moose::ADType< OutputType >::type >::_clearance_schedule private inherited
How often to clear the material property cache.
Definition at line 411 of file MooseFunctor.h.
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_count
const unsigned int MooseVariableBase::_count protected inherited
Number of variables in the array.
Definition at line 227 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::componentName(), MooseVariableBase::count(), MooseVariableBase::MooseVariableBase(), and MooseVariableBase::scalingFactor().
_current_elem_qp_functor_dot
std::vector<DotType> MooseVariableFE< Real >::_current_elem_qp_functor_dot mutable private inherited
The values of the time derivative for the _current_elem_qp_functor_elem.
Definition at line 803 of file MooseVariableFE.h.
_current_elem_qp_functor_elem
const Elem* MooseVariableFE< Real >::_current_elem_qp_functor_elem mutable private inherited
Keep track of the current elem-qp functor element in order to enable local caching (e.g.
if we call evaluate on the same element, but just with a different quadrature point, we can return previously computed results indexed at the different qp
Definition at line 794 of file MooseVariableFE.h.
_current_elem_qp_functor_grad_dot
std::vector<GradientType> MooseVariableFE< Real >::_current_elem_qp_functor_grad_dot mutable private inherited
The values of the gradient of the time derivative for the _current_elem_qp_functor_elem.
Definition at line 806 of file MooseVariableFE.h.
_current_elem_qp_functor_gradient
std::vector<GradientType> MooseVariableFE< Real >::_current_elem_qp_functor_gradient mutable private inherited
The values of the gradient for the _current_elem_qp_functor_elem.
Definition at line 800 of file MooseVariableFE.h.
_current_elem_qp_functor_sln
std::vector<ValueType> MooseVariableFE< Real >::_current_elem_qp_functor_sln mutable private inherited
The values of the solution for the _current_elem_qp_functor_elem.
Definition at line 797 of file MooseVariableFE.h.
_current_elem_side_qp_functor_dot
std::vector<DotType> MooseVariableFE< Real >::_current_elem_side_qp_functor_dot mutable private inherited
The values of the time derivative for the _current_elem_side_qp_functor_elem_side.
Definition at line 821 of file MooseVariableFE.h.
_current_elem_side_qp_functor_elem_side
std::pair<const Elem *, unsigned int> MooseVariableFE< Real >::_current_elem_side_qp_functor_elem_side mutable private inherited
Keep track of the current elem-side-qp functor element and side in order to enable local caching (e.g.
if we call evaluate with the same element and side, but just with a different quadrature point, we can return previously computed results indexed at the different qp
Definition at line 811 of file MooseVariableFE.h.
_current_elem_side_qp_functor_grad_dot
std::vector<GradientType> MooseVariableFE< Real >::_current_elem_side_qp_functor_grad_dot mutable private inherited
The values of the gradient of the time derivative for the _current_elem_side_qp_functor_elem_side.
Definition at line 825 of file MooseVariableFE.h.
_current_elem_side_qp_functor_gradient
std::vector<GradientType> MooseVariableFE< Real >::_current_elem_side_qp_functor_gradient mutable private inherited
The values of the gradient for the _current_elem_side_qp_functor_elem_side.
Definition at line 818 of file MooseVariableFE.h.
_current_elem_side_qp_functor_sln
std::vector<ValueType> MooseVariableFE< Real >::_current_elem_side_qp_functor_sln mutable private inherited
The values of the solution for the _current_elem_side_qp_functor_elem_side.
Definition at line 815 of file MooseVariableFE.h.
_current_execute_flag
const ExecFlagType& SetupInterface::_current_execute_flag protected inherited
Reference to FEProblemBase.
Definition at line 78 of file SetupInterface.h.
Referenced by PseudoTimestep::execute().
_current_qp_map_key
dof_id_type Moose::FunctorBase< Moose::ADType< OutputType >::type >::_current_qp_map_key mutable private inherited
Current key for qp map cache.
Definition at line 417 of file MooseFunctor.h.
_current_qp_map_value
std::vector<std::pair<bool, ValueType> >* Moose::FunctorBase< Moose::ADType< OutputType >::type >::_current_qp_map_value mutable private inherited
Current value for qp map cache.
Definition at line 420 of file MooseFunctor.h.
_current_side_qp_map_key
dof_id_type Moose::FunctorBase< Moose::ADType< OutputType >::type >::_current_side_qp_map_key mutable private inherited
Current key for side-qp map cache.
Definition at line 433 of file MooseFunctor.h.
_current_side_qp_map_value
std::vector<std::vector<std::pair<bool, ValueType> > >* Moose::FunctorBase< Moose::ADType< OutputType >::type >::_current_side_qp_map_value mutable private inherited
Current value for side-qp map cache.
Definition at line 436 of file MooseFunctor.h.
_dof_indices
std::vector<dof_id_type> MooseVariableBase::_dof_indices protected inherited
DOF indices.
Definition at line 218 of file MooseVariableBase.h.
Referenced by MooseVariableBase::clearAllDofIndices(), MooseVariableScalar::computeAD(), MooseVariableBase::dofIndices(), MooseVariableScalar::insert(), MooseVariableBase::numberOfDofs(), MooseVariableScalar::reinit(), MooseVariableScalar::setValue(), and MooseVariableScalar::setValues().
_dof_map
const DofMap& MooseVariableBase::_dof_map protected inherited
DOF map.
Definition at line 215 of file MooseVariableBase.h.
Referenced by MooseVariableBase::dofMap(), MooseVariableScalar::insert(), and MooseVariableScalar::reinit().
_elem_arg_to_value
std::map<ElemArg, ValueType> Moose::FunctorBase< Moose::ADType< OutputType >::type >::_elem_arg_to_value mutable private inherited
Map from element arguments to their cached evaluations.
Definition at line 449 of file MooseFunctor.h.
_element_data
std::unique_ptr<MooseVariableData<Real > > MooseVariableFE< Real >::_element_data protected inherited
Holder for all the data associated with the "main" element.
Definition at line 712 of file MooseVariableFE.h.
_empty_boundary_ids
const std::set<BoundaryID> BlockRestrictable::_empty_boundary_ids private inherited
An empty set for referencing when boundary_ids is not included.
Definition at line 247 of file BlockRestrictable.h.
_empty_execute_enum
ExecFlagEnum SetupInterface::_empty_execute_enum private inherited
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
This is private because others should not be messing with it.
Definition at line 71 of file SetupInterface.h.
Referenced by SetupInterface::SetupInterface().
_enabled
const bool& MooseObject::_enabled protected inherited
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
Definition at line 58 of file MooseObject.h.
Referenced by MooseObject::enabled().
_execute_enum
const ExecFlagEnum& SetupInterface::_execute_enum protected inherited
Execute settings for this object.
Definition at line 75 of file SetupInterface.h.
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), SetupInterface::getExecuteOnEnum(), JSONOutput::outputReporters(), XMLOutput::outputVectorPostprocessors(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
_face_arg_to_value
std::map<FaceArg, ValueType> Moose::FunctorBase< Moose::ADType< OutputType >::type >::_face_arg_to_value mutable private inherited
Map from face arguments to their cached evaluations.
Definition at line 452 of file MooseFunctor.h.
_factory
Factory& MooseBaseParameterInterface::_factory protected inherited
The Factory associated with the MooseApp.
Definition at line 161 of file MooseBaseParameterInterface.h.
Referenced by AddGeneralReactions::act(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), ElementIDOutputAction::act(), AddSpecies::act(), AdaptivityAction::act(), AddControlAction::act(), AddNodalNormalsAction::act(), AddPeriodicBCAction::act(), AutoCheckpointAction::act(), ComposeTimeStepperAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DisplayGhostingAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), PartitionerAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SetupPreconditionerAction::act(), SetupPredictorAction::act(), SetupResidualDebugAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddGeneralReactions::addEEDFReactionKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddDriftDiffusionAction::addPosition(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), MooseBaseParameterInterface::connectControllableParams(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), MaterialOutputAction::getParams(), and ProjectedStatefulMaterialStorageAction::processProperty().
_fe_type
FEType MooseVariableBase::_fe_type protected inherited
The FEType associated with this variable.
Definition at line 191 of file MooseVariableBase.h.
Referenced by MooseVariableBase::feType(), MooseVariableBase::MooseVariableBase(), MooseVariableConstMonomial(), and MooseVariableBase::order().
_functor_name
MooseFunctorName Moose::FunctorBase< Moose::ADType< OutputType >::type >::_functor_name private inherited
name of the functor
Definition at line 458 of file MooseFunctor.h.
_index
unsigned int MooseVariableBase::_index protected inherited
variable number within MOOSE
Definition at line 197 of file MooseVariableBase.h.
_is_array
const bool MooseVariableBase::_is_array protected inherited
Whether this is an array variable.
Definition at line 239 of file MooseVariableBase.h.
Referenced by MooseVariableBase::isArray(), and MooseVariableBase::MooseVariableBase().
_is_eigen
bool MooseVariableBase::_is_eigen protected inherited
Whether or not this variable operates on eigen kernels.
Definition at line 200 of file MooseVariableBase.h.
Referenced by MooseVariableBase::eigen().
_lower_data
std::unique_ptr<MooseVariableData<Real > > MooseVariableFE< Real >::_lower_data protected inherited
Holder for all the data associated with the lower dimeensional element.
Definition at line 718 of file MooseVariableFE.h.
_mci_feproblem
FEProblemBase& MeshChangedInterface::_mci_feproblem protected inherited
Reference to FEProblemBase instance.
Definition at line 38 of file MeshChangedInterface.h.
Referenced by MeshChangedInterface::MeshChangedInterface().
_mesh
MooseMesh& MooseVariableBase::_mesh protected inherited
mesh the variable is active in
Definition at line 221 of file MooseVariableBase.h.
_moose_base
const MooseBase* const MooseBaseParameterInterface::_moose_base private inherited
The MooseBase object that inherits this class.
Definition at line 168 of file MooseBaseParameterInterface.h.
Referenced by MooseBaseParameterInterface::connectControllableParams(), MooseBaseParameterInterface::objectErrorPrefix(), MooseBaseParameterInterface::paramError(), and MooseBaseParameterInterface::uniqueParameterName().
_name
const std::string& MooseBase::_name protected inherited
The name of this class, reference to value stored in InputParameters.
Definition at line 66 of file MooseBase.h.
Referenced by AddFieldSplitAction::act(), AddBCAction::act(), AddConstraintAction::act(), AddControlAction::act(), AddDamperAction::act(), AddDGKernelAction::act(), AddDiracKernelAction::act(), AddDistributionAction::act(), AddFunctionAction::act(), AddFunctorMaterialAction::act(), AddFVBCAction::act(), AddFVInitialConditionAction::act(), AddFVInterfaceKernelAction::act(), AddFVKernelAction::act(), AddIndicatorAction::act(), AddInitialConditionAction::act(), AddInterfaceKernelAction::act(), AddKernelAction::act(), AddMarkerAction::act(), AddMaterialAction::act(), AddMeshDivisionAction::act(), AddMeshGeneratorAction::act(), AddMultiAppAction::act(), AddNodalKernelAction::act(), AddOutputAction::act(), AddPeriodicBCAction::act(), AddPositionsAction::act(), AddPostprocessorAction::act(), AddReporterAction::act(), AddSamplerAction::act(), AddScalarKernelAction::act(), AddTimesAction::act(), AddTimeStepperAction::act(), AddTransferAction::act(), AddUserObjectAction::act(), AddVectorPostprocessorAction::act(), PartitionerAction::act(), ReadExecutorParamsAction::act(), SetupPreconditionerAction::act(), SetupTimeIntegratorAction::act(), AddDriftDiffusionAction::addADKernels(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromXY(), PiecewiseLinearBase::buildInterpolation(), CombinerGenerator::CombinerGenerator(), Executor::Executor(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), FunctionDT::FunctionDT(), FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), MooseBase::name(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), PiecewiseBase::setData(), and Split::setup().
_neighbor_data
std::unique_ptr<MooseVariableData<Real > > MooseVariableFE< Real >::_neighbor_data protected inherited
Holder for all the data associated with the neighbor element.
Definition at line 715 of file MooseVariableFE.h.
_node_arg_to_value
std::map<NodeArg, ValueType> Moose::FunctorBase< Moose::ADType< OutputType >::type >::_node_arg_to_value mutable private inherited
Map from nodal arguments to their cached evaluations.
Definition at line 455 of file MooseFunctor.h.
_oi_moose_app
MooseApp& OutputInterface::_oi_moose_app private inherited
Reference the the MooseApp; neede for access to the OutputWarehouse.
Definition at line 66 of file OutputInterface.h.
_oi_output_warehouse
OutputWarehouse& OutputInterface::_oi_output_warehouse private inherited
Reference to the OutputWarehouse for populating the Output object hide lists.
Definition at line 69 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList().
_oi_outputs
std::set<OutputName> OutputInterface::_oi_outputs private inherited
The set of Output object names listed in the 'outputs' parameter.
Definition at line 72 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList(), and OutputInterface::getOutputs().
_parent
const MooseObject & DataFileInterface< MooseObject >::_parent private inherited
Definition at line 46 of file DataFileInterface.h.
_pars
const InputParameters& MooseBaseParameterInterface::_pars protected inherited
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Definition at line 158 of file MooseBaseParameterInterface.h.
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), AddPeriodicBCAction::act(), AddVariableAction::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), FunctorMaterial::addFunctorPropertyByBlocks(), FVFluxKernel::adjustRMGhostLayers(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), PiecewiseTabularBase::buildFromFile(), PNGOutput::calculateRescalingValues(), BlockWeightedPartitioner::clone(), GridPartitioner::clone(), HierarchicalGridPartitioner::clone(), PetscExternalPartitioner::clone(), RandomPartitioner::clone(), SingleRankPartitioner::clone(), MooseBaseParameterInterface::connectControllableParams(), Console::Console(), AddVariableAction::createInitialConditionAction(), MaterialBase::declareADProperty(), MaterialBase::declareProperty(), FEProblemSolve::FEProblemSolve(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), FileMeshGenerator::generate(), MaterialBase::getGenericZeroMaterialProperty(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getParam(), MooseBaseParameterInterface::getRenamedParam(), AddVariableAction::init(), AdvancedOutput::initExecutionTypes(), Console::initialSetup(), MooseBaseParameterInterface::isParamSetByUser(), MooseBaseParameterInterface::isParamValid(), MultiApp::keepSolutionDuringRestore(), MooseBaseParameterInterface::paramErrorMsg(), GlobalParamsAction::parameters(), MooseBaseParameterInterface::parameters(), MooseMesh::prepare(), Eigenvalue::prepareSolverOptions(), MooseMesh::setCoordSystem(), MooseMesh::setPartitionerHelper(), SetupMeshAction::setupMesh(), Transient::setupTimeIntegrator(), MooseBaseParameterInterface::uniqueName(), and MooseBaseParameterInterface::uniqueParameterName().
_qp_to_value
std::unordered_map<dof_id_type, std::vector<std::pair<bool, ValueType> > > Moose::FunctorBase< Moose::ADType< OutputType >::type >::_qp_to_value mutable private inherited
Cached element quadrature point functor property evaluations.
The map key is the element id. The map values should have size corresponding to the number of quadrature points on the element. The vector elements are pairs. The first member of the pair indicates whether a cached value has been computed. The second member of the pair is the (cached) value. If the boolean is false, then the value cannot be trusted
Definition at line 427 of file MooseFunctor.h.
_scaling_factor
std::vector<Real> MooseVariableBase::_scaling_factor protected inherited
scaling factor for this variable
Definition at line 230 of file MooseVariableBase.h.
Referenced by MooseVariableBase::arrayScalingFactor(), MooseVariableBase::initialSetup(), and MooseVariableBase::scalingFactor().
_side_qp_to_value
std::unordered_map<dof_id_type, std::vector<std::vector<std::pair<bool, ValueType> > > > Moose::FunctorBase< Moose::ADType< OutputType >::type >::_side_qp_to_value mutable private inherited
Cached element quadrature point functor property evaluations.
The map key is the element id. The map values are a multi-dimensional vector (or vector of vectors) with the first index corresponding to the side and the second index corresponding to the quadrature point index. The elements returned after double indexing are pairs. The first member of the pair indicates whether a cached value has been computed. The second member of the pair is the (cached) value. If the boolean is false, then the value cannot be trusted
Definition at line 446 of file MooseFunctor.h.
_subproblem
SubProblem& MooseVariableBase::_subproblem protected inherited
Problem this variable is part of.
Definition at line 206 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::componentName(), MooseVariableScalar::computeAD(), and MooseVariableBase::initialSetup().
_sys
SystemBase& MooseVariableBase::_sys protected inherited
System this variable is part of.
Definition at line 188 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::activeOnSubdomain(), MooseVariableFieldBase::activeSubdomains(), MooseVariableScalar::adUDot(), MooseVariableBase::allDofIndices(), MooseVariableScalar::computeAD(), MooseVariableBase::initialSetup(), MooseVariableBase::MooseVariableBase(), MooseVariableFE< OutputType >::MooseVariableFE(), MooseVariableFV< OutputType >::MooseVariableFV(), MooseVariableScalar::MooseVariableScalar(), MooseVariableScalar::reinit(), MooseVariableBase::sys(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), and MooseVariableScalar::uDotOld().
_tid
THREAD_ID MooseVariableBase::_tid protected inherited
Thread ID.
Definition at line 224 of file MooseVariableBase.h.
Referenced by MooseVariableFE< OutputType >::MooseVariableFE(), MooseVariableFV< OutputType >::MooseVariableFV(), and MooseVariableScalar::reinit().
_time_integrator
template<typename OutputType > const TimeIntegrator* const MooseVariableField< OutputType >::_time_integrator protected inherited
the time integrator used for computing time derivatives
Definition at line 379 of file MooseVariableField.h.
_type
const std::string& MooseBase::_type protected inherited
The type of this class.
Definition at line 63 of file MooseBase.h.
Referenced by FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), FEProblemBase::init(), FEProblemBase::solverTypeString(), and MooseBase::type().
_use_dual
bool MooseVariableBase::_use_dual protected inherited
If dual mortar approach is used.
Definition at line 236 of file MooseVariableBase.h.
Referenced by MooseVariableBase::useDual().
_var_kind
Moose::VarKindType MooseVariableBase::_var_kind protected inherited
Variable type (see MooseTypes.h)
Definition at line 203 of file MooseVariableBase.h.
Referenced by MooseVariableBase::kind().
_var_name
std::string MooseVariableBase::_var_name protected inherited
Variable name.
Definition at line 233 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::componentName(), MooseVariableBase::MooseVariableBase(), and MooseVariableBase::name().
_var_num
unsigned int MooseVariableBase::_var_num protected inherited
variable number (from libMesh)
Definition at line 194 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::activeOnSubdomain(), MooseVariableFieldBase::activeSubdomains(), MooseVariableBase::MooseVariableBase(), MooseVariableBase::number(), and MooseVariableScalar::reinit().
_variable
const Variable& MooseVariableBase::_variable protected inherited
libMesh variable object for this variable
Definition at line 209 of file MooseVariableBase.h.
_vec_ids
std::vector<SubdomainID> BlockRestrictable::_vec_ids private inherited
Vector of block ids supplied by the user via the input file (for error reporting)
Definition at line 232 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
usingMooseVariableFieldMembers
MooseVariableFE< Real >::usingMooseVariableFieldMembers protected inherited
Definition at line 709 of file MooseVariableFE.h.
The documentation for this class was generated from the following files:
moose/framework/include/variables/MooseVariableConstMonomial.h
moose/framework/src/variables/MooseVariableConstMonomial.C