Zapdos: OrientedBoxInterface Class Reference
OrientedBoxInterface Class Reference
#include <OrientedBoxInterface.h>
Public Member Functions
OrientedBoxInterface (const InputParameters &parameters)
virtual ~OrientedBoxInterface ()=default
Class destructor.
Static Public Member Functions
static InputParameters validParams ()
Class constructor.
Protected Member Functions
bool containsPoint (const Point &point)
Test if the supplied point is within the defined oriented bounding box.
Private Attributes
Point _center
Center of the defined bounding box.
std::unique_ptr< RealTensorValue > _rot_matrix
Rotation matrix for transforming the bounding box.
std::unique_ptr< BoundingBox > _bounding_box
The bounding box used to test if the point is contained within.
Detailed Description
Definition at line 38 of file OrientedBoxInterface.h.
Constructor & Destructor Documentation
OrientedBoxInterface()
OrientedBoxInterface::OrientedBoxInterface (const InputParameters & parameters)
Definition at line 36 of file OrientedBoxInterface.C.
  : _center(parameters.get<Point>("center"))
{
  const std::string & name = parameters.get<std::string>("_object_name");
  // Define the bounding box
  Real xmax = 0.5 * parameters.get<Real>("width");
  Real ymax = 0.5 * parameters.get<Real>("length");
  Real zmax = 0.5 * parameters.get<Real>("height");
  Point bottom_left(-xmax, -ymax, -zmax);
  Point top_right(xmax, ymax, zmax);
  _bounding_box = std::make_unique<BoundingBox>(bottom_left, top_right);
  /*
   * now create the rotation matrix that rotates the oriented
   * box's width direction to "x", its length direction to "y"
   * and its height direction to "z"
   */
  RealVectorValue w = parameters.get<RealVectorValue>("width_direction");
  RealVectorValue l = parameters.get<RealVectorValue>("length_direction");
  /*
   * Normalize the width and length directions in readiness for
   * insertion into the rotation matrix
   */
  Real len = w.norm();
  if (len == 0.0)
    mooseError("Length of width_direction vector is zero in ", name);
  w /= len;
  len = l.norm();
  if (len == 0.0)
    mooseError("Length of length_direction vector is zero in ", name);
  l /= len;
  if (w * l > 1E-10)
    mooseError("width_direction and length_direction are not perpendicular in ", name);
  // The rotation matrix!
  _rot_matrix = std::make_unique<RealTensorValue>(w, l, w.cross(l));
}
~OrientedBoxInterface()
virtual OrientedBoxInterface::~OrientedBoxInterface () virtual default
Class destructor.
Member Function Documentation
containsPoint()
bool OrientedBoxInterface::containsPoint (const Point & point) protected
Test if the supplied point is within the defined oriented bounding box.
Parameters
point The point to test
Returns
True if the supplied point is within the bounding box
Definition at line 81 of file OrientedBoxInterface.C.
{
  // Translate the point to the origin, and then rotate
  return _bounding_box->contains_point((*_rot_matrix) * (point - _center));
}
Referenced by OrientedBoxMarker::computeElementMarker(), and OrientedSubdomainBoundingBoxGenerator::generate().
validParams()
InputParameters OrientedBoxInterface::validParams () static
Class constructor.
Definition at line 19 of file OrientedBoxInterface.C.
{
  InputParameters params = emptyInputParameters();
  params.addRequiredParam<Point>("center",
                                 "The center (many people spell this 'center') of the box.");
  params.addRequiredParam<Real>("width", "The width of the box");
  params.addRequiredParam<Real>("length", "The length of the box");
  params.addRequiredParam<Real>("height", "The height of the box");
  params.addRequiredParam<RealVectorValue>("width_direction",
                                           "The direction along which the width is oriented.");
  params.addRequiredParam<RealVectorValue>("length_direction",
                                           "The direction along which the length is oriented (must "
                                           "be perpendicular to width_direction).");
  return params;
}
Referenced by OrientedBoxMarker::validParams(), and OrientedSubdomainBoundingBoxGenerator::validParams().
Member Data Documentation
_bounding_box
std::unique_ptr<BoundingBox> OrientedBoxInterface::_bounding_box private
The bounding box used to test if the point is contained within.
Definition at line 69 of file OrientedBoxInterface.h.
Referenced by containsPoint(), and OrientedBoxInterface().
_center
Point OrientedBoxInterface::_center private
Center of the defined bounding box.
Definition at line 63 of file OrientedBoxInterface.h.
Referenced by containsPoint().
_rot_matrix
std::unique_ptr<RealTensorValue> OrientedBoxInterface::_rot_matrix private
Rotation matrix for transforming the bounding box.
Definition at line 66 of file OrientedBoxInterface.h.
Referenced by containsPoint(), and OrientedBoxInterface().
The documentation for this class was generated from the following files:
moose/framework/include/interfaces/OrientedBoxInterface.h
moose/framework/src/interfaces/OrientedBoxInterface.C