Zapdos: AttribExecOns Class Reference
AttribExecOns Class Reference abstract
#include <Attributes.h>
Public Types
typedef int Key
Public Member Functions
void setFrom (Key k)
AttribExecOns (TheWarehouse &w)
AttribExecOns (TheWarehouse &w, const int id)
AttribExecOns (TheWarehouse &w, const ExecFlagType &exec_flag)
virtual void initFrom (const MooseObject *obj) override
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
virtual bool isMatch (const Attribute &other) const override
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
virtual bool isEqual (const Attribute &other) const override
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
hashfunc (_vals)
clonefunc (AttribExecOns)
bool operator== (const Attribute &other) const
bool operator!= (const Attribute &other) const
unsigned int id () const
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
virtual std::size_t hash () const =0
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
virtual std::unique_ptr< Attribute > clone () const =0
clone creates and returns and identical (deep) copy of this attribute - i.e.
Static Public Attributes
static const ExecFlagType EXEC_ALL = registerExecFlag("ALL")
Execute flag that is used to represent all flags when querying AttribExecOns.
Private Attributes
std::vector< Key > _vals
int _id = -1
Detailed Description
Definition at line 131 of file Attributes.h.
Member Typedef Documentation
Key
typedef int AttribExecOns::Key
Definition at line 137 of file Attributes.h.
Constructor & Destructor Documentation
AttribExecOns() [1/3]
AttribExecOns::AttribExecOns (TheWarehouse & w) inline
Definition at line 144 of file Attributes.h.
: Attribute(w, "exec_ons") {}
AttribExecOns() [2/3]
AttribExecOns::AttribExecOns (TheWarehouse & w, const int id) inline
Definition at line 145 of file Attributes.h.
: Attribute(w, "exec_ons"), _vals({id}) {}
AttribExecOns() [3/3]
AttribExecOns::AttribExecOns (TheWarehouse & w, const ExecFlagType & exec_flag) inline
Definition at line 146 of file Attributes.h.
    : Attribute(w, "exec_ons"), _vals({exec_flag.id()})
  {
  }
Member Function Documentation
clone()
virtual std::unique_ptr< Attribute > Attribute::clone () const pure virtual inherited
clone creates and returns and identical (deep) copy of this attribute - i.e.
the result of clone should return true if passed into isMatch.
Referenced by FEProblemBase::computeUserObjectsInternal(), and TheWarehouse::update().
clonefunc()
AttribExecOns::clonefunc (AttribExecOns)
hash()
virtual std::size_t Attribute::hash () const pure virtual inherited
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
is initialized with). Ideally, the data should be uniformly and randomly distributed across the domain of size_t values - e.g. 1 and 2 should hash to completely unrelated values. Use of std::hash for POD is encouraged. A convenience hash_combine function is also provided to combine the results an existing hash with one or more other values.
Referenced by std::hash< Attribute >::operator()().
hashfunc()
AttribExecOns::hashfunc (_vals)
id()
unsigned int Attribute::id () const inline inherited
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
This ID is determined at construction time this
Definition at line 66 of file TheWarehouse.h.
{ return _id; }
Referenced by std::hash< Attribute >::operator()().
initFrom()
void AttribExecOns::initFrom (const MooseObject * obj) override virtual
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
Implements Attribute.
Definition at line 130 of file Attributes.C.
{
  _vals.clear();
  if (const auto sup = dynamic_cast<const SetupInterface *>(obj))
  {
    const auto & current_items = sup->getExecuteOnEnum();
    _vals.reserve(current_items.size());
    for (auto & on : current_items)
      _vals.push_back(on);
  }
}
isEqual()
bool AttribExecOns::isEqual (const Attribute & other) const override virtual
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
isEqual does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 159 of file Attributes.C.
{
  auto a = dynamic_cast<const AttribExecOns *>(&other);
  if (!a || a->_vals.size() != _vals.size())
    return false;
  for (size_t i = 0; i < a->_vals.size(); i++)
    if (a->_vals[i] != _vals[i])
      return false;
  return true;
}
isMatch()
bool AttribExecOns::isMatch (const Attribute & other) const override virtual
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
This is is for query matching - not exact equivalence. isMatch does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 143 of file Attributes.C.
{
  auto a = dynamic_cast<const AttribExecOns *>(&other);
  if (!a || a->_vals.empty())
    return false;
  auto cond = a->_vals[0];
  if (cond == EXEC_ALL)
    return true;
  for (const auto val : _vals)
    if (val == EXEC_ALL || val == cond)
      return true;
  return false;
}
operator!=()
bool Attribute::operator!= (const Attribute & other) const inline inherited
Definition at line 61 of file TheWarehouse.h.
{ return !(*this == other); }
operator==()
bool Attribute::operator== (const Attribute & other) const inline inherited
Definition at line 57 of file TheWarehouse.h.
  {
    return _id == other._id && isEqual(other);
  }
setFrom()
void AttribExecOns::setFrom (Key k) inline
Definition at line 138 of file Attributes.h.
  {
    _vals.clear();
    _vals.push_back(k);
  }
Member Data Documentation
_id
int Attribute::_id = -1 private inherited
Definition at line 91 of file TheWarehouse.h.
Referenced by Attribute::id(), and Attribute::operator==().
_vals
std::vector<Key> AttribExecOns::_vals private
Definition at line 157 of file Attributes.h.
Referenced by initFrom(), isEqual(), isMatch(), and setFrom().
EXEC_ALL
const ExecFlagType AttribExecOns::EXEC_ALL = registerExecFlag("ALL") static
Execute flag that is used to represent all flags when querying AttribExecOns.
Definition at line 135 of file Attributes.h.
Referenced by isMatch().
The documentation for this class was generated from the following files:
moose/framework/include/base/Attributes.h
moose/framework/src/base/Attributes.C