Zapdos: OutputWarehouse Class Reference
OutputWarehouse Class Reference
Class for storing and utilizing output objects.
#include <OutputWarehouse.h>
Public Member Functions
OutputWarehouse (MooseApp &app)
Class constructor.
virtual ~OutputWarehouse ()
void addOutput (std::shared_ptr< Output > output)
Adds an existing output object to the warehouse.
const std::set< OutputName > & getOutputNames ()
Get a complete set of all output object names.
bool hasOutput (const std::string &name) const
Returns true if the output object exists.
void meshChanged ()
Calls the meshChanged method for every output object.
void buildInterfaceHideVariables (const std::string &output_name, std::set< std::string > &hide)
Return the list of hidden variables for the given output name.
void setFileNumbers (std::map< std::string, unsigned int > input, unsigned int offset=0)
Calls the setFileNumber method for every FileOutput output object.
std::map< std::string, unsigned int > getFileNumbers ()
Extracts the file numbers from the output objects.
void setCommonParameters (const InputParameters *params_ptr)
Stores the common InputParameters object.
const InputParameters * getCommonParameters () const
Get a reference to the common output parameters.
std::set< Real > & getSyncTimes ()
Return the sync times for all objects.
void checkOutputs (const std::set< OutputName > &names)
Test that the output names exist.
template<typename T >
T * getOutput (const OutputName &name)
Return an Output object by name.
template<typename T >
std::vector< T * > getOutputs (const std::vector< OutputName > &names)
Return a vector of objects by names.
template<typename T >
std::vector< T * > getOutputs () const
Return a vector of objects of a given type.
template<typename T >
std::vector< OutputName > getOutputNames ()
Return a list of output objects with a given type.
const std::set< std::string > & getReservedNames () const
Return a set of reserved output names.
bool isReservedName (const std::string &name)
Test if the given name is reserved.
void mooseConsole ()
Send current output buffer to Console output objects.
void mooseConsole (std::ostringstream &buffer)
Send a buffer to Console output objects.
std::ostringstream & consoleBuffer ()
The buffered messages stream for Console objects.
void bufferConsoleOutputsBeforeConstruction (bool buffer)
Set if the outputs to Console before its construction are to be buffered or to screen directly.
void reset ()
Reset the output system.
void solveSetup ()
Calls the timestepSetup function for each of the output objects.
unsigned long long int numPrinted () const
The number of times something has been printed.
Protected Member Functions
PerfGraph & perfGraph ()
Get the PerfGraph.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level) const
Call to register a named section for timing.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level, const std::string &live_message, const bool print_dots=true) const
Call to register a named section for timing.
std::string timedSectionName (const std::string &section_name) const
Static Protected Member Functions
static InputParameters validParams ()
Protected Attributes
MooseApp & _pg_moose_app
The MooseApp that owns the PerfGraph.
const std::string _prefix
A prefix to use for all sections.
Private Member Functions
void outputStep (ExecFlagType type)
Calls the outputStep method for each output object.
void forceOutput ()
Indicates that the next call to outputStep should be forced This is private, users should utilize FEProblemBase::forceOutput()
void addOutputFilename (const OutputName &obj_name, const OutFileBase &filename)
Adds the file name to the map of filenames being output with an associated object The main function of this object is to test that the same output file does not already exist in another object to protect against output files overwriting each other.
void initialSetup ()
Calls the initialSetup function for each of the output objects.
void timestepSetup ()
Calls the timestepSetup function for each of the output objects.
void customSetup (const ExecFlagType &exec_type)
Calls the setup function for each of the output objects.
void jacobianSetup ()
Calls the jacobianSetup function for each of the output objects.
void residualSetup ()
Calls the residualSetup function for each of the output objects.
void subdomainSetup ()
Calls the subdomainSetup function for each of the output objects.
void addInterfaceHideVariables (const std::string &output_name, const std::set< std::string > &variable_names)
Insert variable names for hiding via the OutoutInterface.
void setOutputExecutionType (ExecFlagType type)
Sets the execution flag type.
void flushConsoleBuffer ()
If content exists in the buffer, write it.
void resetFileBase ()
Resets the file base for all FileOutput objects.
void allowOutput (bool state)
Ability to enable/disable output calls This is private, users should utilize FEProblemBase::allowOutput()
template<typename T >
void allowOutput (bool state)
Private Attributes
std::vector< std::shared_ptr< Output > > _all_ptrs
We are using std::shared_ptr to handle the cleanup of the pointers at the end of execution.
MooseApp & _app
MooseApp.
std::vector< Output * > _all_objects
All instances of objects (raw pointers)
bool _buffer_action_console_outputs
True to buffer console outputs in actions.
std::map< OutputName, Output * > _object_map
A map of the output pointers.
std::set< OutputName > _object_names
A set of output names.
std::map< OutputName, std::set< OutFileBase > > _file_base_map
List of object names.
const InputParameters * _common_params_ptr
Pointer to the common InputParameters (.
std::set< Real > _sync_times
Sync times for all objects.
std::string _input_file_name
Input file name for this output object.
std::map< OutputName, std::set< AuxVariableName > > _material_output_map
Map of output name and AuxVariable names to be output (used by auto Material output)
std::set< AuxVariableName > _all_material_output_variables
List of all variable created by auto material output.
std::set< std::string > _reserved
List of reserved names.
std::ostringstream _console_buffer
The stream for holding messages passed to _console prior to Output object construction.
std::map< std::string, std::set< std::string > > _interface_map
Storage for variables to hide as prescribed by the object via the OutputInterface.
ExecFlagType _output_exec_flag
The current output execution flag.
bool _force_output
Flag indicating that next call to outputStep is forced.
bool _last_message_ended_in_newline
Whether or not the last thing output by mooseConsole had a newline as the last character.
const std::ostringstream * _last_buffer
What the last buffer was that was printed.
std::atomic< unsigned long long int > _num_printed
Number of times the stream has been printed to.
Friends
class FEProblemBase
class MaterialOutputAction
class OutputInterface
class PetscOutputInterface
class MooseApp
Detailed Description
Class for storing and utilizing output objects.
Definition at line 26 of file OutputWarehouse.h.
Constructor & Destructor Documentation
OutputWarehouse()
OutputWarehouse::OutputWarehouse (MooseApp & app)
Class constructor.
Definition at line 25 of file OutputWarehouse.C.
  : PerfGraphInterface(app, "OutputWarehouse"),
    _app(app),
    _buffer_action_console_outputs(false),
    _common_params_ptr(NULL),
    _output_exec_flag(EXEC_CUSTOM),
    _force_output(false),
    _last_message_ended_in_newline(true),
    _last_buffer(NULL),
    _num_printed(0)
{
  // Set the reserved names
  _reserved.insert("none"); // allows 'none' to be used as a keyword in 'outputs' parameter
  _reserved.insert("all");  // allows 'all' to be used as a keyword in 'outputs' parameter
}
~OutputWarehouse()
OutputWarehouse::~OutputWarehouse () virtual
Definition at line 41 of file OutputWarehouse.C.
{
  // If the output buffer is not empty, it needs to be written
  if (_console_buffer.str().length())
    mooseConsole();
}
Member Function Documentation
addInterfaceHideVariables()
void OutputWarehouse::addInterfaceHideVariables (const std::string & output_name, const std::set< std::string > & variable_names) private
Insert variable names for hiding via the OutoutInterface.
Parameters
output_name The name of the output object on which the variable is to be hidden
variable_names The names of the variables to be hidden
This is a private method used by the OutputInterface system, it is not intended for any other purpose.
Definition at line 300 of file OutputWarehouse.C.
{
  _interface_map[output_name].insert(variable_names.begin(), variable_names.end());
}
Referenced by MaterialOutputAction::act(), and OutputInterface::buildOutputHideVariableList().
addOutput()
void OutputWarehouse::addOutput (std::shared_ptr< Output > output)
Adds an existing output object to the warehouse.
Parameters
output Pointer to the output object It is the responsibility of the OutputWarehouse to delete the output objects add using this method
Definition at line 102 of file OutputWarehouse.C.
{
  _all_ptrs.push_back(output);
  // Add the object to the warehouse storage, Checkpoint placed at end so they are called last
  Checkpoint * cp = dynamic_cast<Checkpoint *>(output.get());
  if (cp != NULL)
    _all_objects.push_back(output.get());
  else
    _all_objects.insert(_all_objects.begin(), output.get());
  // Store the name and pointer
  _object_map[output->name()] = output.get();
  _object_names.insert(output->name());
  // Insert object sync times to the global set
  const std::set<Real> & sync_times = output->getSyncTimes();
  _sync_times.insert(sync_times.begin(), sync_times.end());
}
Referenced by FEProblemBase::addOutput(), and AutomaticMortarGeneration::initOutput().
addOutputFilename()
void OutputWarehouse::addOutputFilename (const OutputName & obj_name, const OutFileBase & filename) private
Adds the file name to the map of filenames being output with an associated object The main function of this object is to test that the same output file does not already exist in another object to protect against output files overwriting each other.
Parameters
obj_name Name of an FileOutput object
filename Name of an output file (extracted from filename() method of the objects)
Definition at line 141 of file OutputWarehouse.C.
{
  _file_base_map[obj_name].insert(filename);
  for (const auto & it : _file_base_map)
    if (it.first != obj_name && it.second.find(filename) != it.second.end())
      mooseError("An output file with the name, ", filename, ", already exists.");
}
Referenced by resetFileBase().
allowOutput() [1/2]
void OutputWarehouse::allowOutput (bool state) private
Ability to enable/disable output calls This is private, users should utilize FEProblemBase::allowOutput()
See also
FEProblemBase::allowOutput()
Definition at line 343 of file OutputWarehouse.C.
{
  for (const auto & obj : _all_objects)
    obj->allowOutput(state);
}
Referenced by FEProblemBase::allowOutput().
allowOutput() [2/2]
template<typename T > void OutputWarehouse::allowOutput (bool state) private
Definition at line 475 of file OutputWarehouse.h.
{
  std::vector<T *> outputs = getOutputs<T>();
  for (typename std::vector<T *>::iterator it = outputs.begin(); it != outputs.end(); ++it)
    (*it)->allowOutput(state);
}
bufferConsoleOutputsBeforeConstruction()
void OutputWarehouse::bufferConsoleOutputsBeforeConstruction (bool buffer) inline
Set if the outputs to Console before its construction are to be buffered or to screen directly.
Parameters
buffer Ture to buffer
Definition at line 192 of file OutputWarehouse.h.
  {
    _buffer_action_console_outputs = buffer;
  }
buildInterfaceHideVariables()
void OutputWarehouse::buildInterfaceHideVariables (const std::string & output_name, std::set< std::string > & hide)
Return the list of hidden variables for the given output name.
Parameters
output_name The name of the output object for which the variables should be returned
hide The set of variables to hide which is built by this method
Objects inheriting from the OutputInterface have the ability to control the output of variables associated with the objects (i.e., Marker elemental variable). This method returns a list of variables that should be hidden for the supplied object name due to the 'outputs' parameter being set by the object(s).
This method is used by Output::initOutputList to populate the correct hide lists for the output object, it is not intended for general use.
Definition at line 307 of file OutputWarehouse.C.
{
  std::map<std::string, std::set<std::string>>::const_iterator it =
      _interface_map.find(output_name);
  if (it != _interface_map.end())
    hide = it->second;
}
Referenced by AdvancedOutput::initOutputList().
checkOutputs()
void OutputWarehouse::checkOutputs (const std::set< OutputName > & names)
Test that the output names exist.
Parameters
names A vector of names to check This method will produce an error if any of the supplied names do not exist in the warehouse. Reserved names are not considered.
Definition at line 317 of file OutputWarehouse.C.
{
  for (const auto & name : names)
    if (!isReservedName(name) && !hasOutput(name))
      mooseError("The output object '", name, "' is not a defined output object");
}
Referenced by CheckOutputAction::checkMaterialOutput(), CheckOutputAction::checkVariableOutput(), and AdvancedOutput::initPostprocessorOrVectorPostprocessorLists().
consoleBuffer()
std::ostringstream & OutputWarehouse::consoleBuffer () inline
The buffered messages stream for Console objects.
Returns
Reference to the stream storing cached messages from calls to _console
Definition at line 186 of file OutputWarehouse.h.
{ return _console_buffer; }
customSetup()
void OutputWarehouse::customSetup (const ExecFlagType & exec_type) private
Calls the setup function for each of the output objects.
See also
FEProblemBase::customSetup(const ExecFlagType & exec_type)
Definition at line 67 of file OutputWarehouse.C.
{
  for (const auto & obj : _all_objects)
    obj->customSetup(exec_type);
}
Referenced by FEProblemBase::customSetup().
flushConsoleBuffer()
void OutputWarehouse::flushConsoleBuffer () private
If content exists in the buffer, write it.
This is used by Console to make sure PETSc related output does not dump before buffered content. It is private because people shouldn't be messing with it.
Definition at line 240 of file OutputWarehouse.C.
{
  if (!_console_buffer.str().empty())
    mooseConsole();
}
Referenced by outputStep().
forceOutput()
void OutputWarehouse::forceOutput () private
Indicates that the next call to outputStep should be forced This is private, users should utilize FEProblemBase::forceOutput()
See also
FEProblemBase::forceOutput()
Definition at line 350 of file OutputWarehouse.C.
{
  _force_output = true;
}
Referenced by FEProblemBase::forceOutput().
getCommonParameters()
const InputParameters * OutputWarehouse::getCommonParameters () const
Get a reference to the common output parameters.
Returns
Pointer to the common InputParameters object
Definition at line 288 of file OutputWarehouse.C.
{
  return _common_params_ptr;
}
Referenced by FEProblemBase::addOutput().
getFileNumbers()
std::map< std::string, unsigned int > OutputWarehouse::getFileNumbers ()
Extracts the file numbers from the output objects.
Returns
Map of file numbers for the output objects
Definition at line 268 of file OutputWarehouse.C.
{
  std::map<std::string, unsigned int> output;
  for (const auto & obj : _all_objects)
  {
    FileOutput * ptr = dynamic_cast<FileOutput *>(obj);
    if (ptr != NULL)
      output[ptr->name()] = ptr->getFileNumber();
  }
  return output;
}
Referenced by MultiApp::createApp().
getOutput()
template<typename T > T * OutputWarehouse::getOutput (const OutputName & name)
Return an Output object by name.
Template Parameters
T The Out put object type to return
Parameters
name The name of the output object
Returns
A pointer to the output object
Definition at line 399 of file OutputWarehouse.h.
{
  // Check that the object exists
  if (!hasOutput(name))
    mooseError("An output object with the name '", name, "' does not exist.");
  // Attempt to cast the object to the correct type
  T * output = dynamic_cast<T *>(_object_map[name]);
  // Error if the cast fails
  if (output == NULL)
    mooseError("An output object with the name '", name, "' for the specified type does not exist");
  // Return the object
  return output;
}
getOutputNames() [1/2]
const std::set< OutputName > & OutputWarehouse::getOutputNames ()
Get a complete set of all output object names.
Returns
A set of output names for each output object
Note, if this method is called prior to the creation of outputs in AddOutputAction it will create the proxy list of names from the action system. The main use is for the OutputInterface, specifically, when used with Postprocessors in the UserObjects block of the input file. UserObjects are created prior to Outputs objects, but OutputInterface needs the list of output names to operate correctly.
Definition at line 129 of file OutputWarehouse.C.
{
  if (_object_names.empty() && _app.actionWarehouse().hasActions("add_output"))
  {
    const auto & actions = _app.actionWarehouse().getActionListByName("add_output");
    for (const auto & act : actions)
      _object_names.insert(act->name());
  }
  return _object_names;
}
Referenced by OutputInterface::buildOutputHideVariableList().
getOutputNames() [2/2]
template<typename T > std::vector< OutputName > OutputWarehouse::getOutputNames
Return a list of output objects with a given type.
Template Parameters
T The output object type
Returns
A vector of names
Definition at line 454 of file OutputWarehouse.h.
{
  // The output vector
  std::vector<OutputName> names;
  // Loop through the objects and store the name if the type cast succeeds
  for (std::map<OutputName, Output *>::const_iterator it = _object_map.begin();
       it != _object_map.end();
       ++it)
  {
    T * output = dynamic_cast<T *>(it->second);
    if (output != NULL)
      names.push_back(it->first);
  }
  // Return the names
  return names;
}
getOutputs() [1/2]
template<typename T > std::vector< T * > OutputWarehouse::getOutputs
Return a vector of objects of a given type.
Template Parameters
T The Output object type to return
Returns
A pointer to the output object
Definition at line 433 of file OutputWarehouse.h.
{
  // The vector to output
  std::vector<T *> outputs;
  // Populate the vector
  for (std::map<OutputName, Output *>::const_iterator it = _object_map.begin();
       it != _object_map.end();
       ++it)
  {
    T * output = dynamic_cast<T *>(it->second);
    if (output != NULL)
      outputs.push_back(output);
  }
  // Return the objects
  return outputs;
}
getOutputs() [2/2]
template<typename T > std::vector< T * > OutputWarehouse::getOutputs (const std::vector< OutputName > & names)
Return a vector of objects by names.
Template Parameters
T The Output object type to return
Parameters
names A vector of names of the output object
Returns
A pointer to the output object
Definition at line 418 of file OutputWarehouse.h.
{
  // The vector to output
  std::vector<T *> outputs;
  // Populate the vector
  for (std::vector<OutputName>::const_iterator it = names.begin(); it != names.end(); ++it)
    outputs.push_back(getOutput<T>(*it));
  // Return the objects
  return outputs;
}
Referenced by AutoCheckpointAction::act(), CheckOutputAction::checkConsoleOutput(), CheckOutputAction::checkPerfLogOutput(), and ConsoleUtils::outputOutputInformation().
getReservedNames()
const std::set< std::string > & OutputWarehouse::getReservedNames () const
Return a set of reserved output names.
Returns
A std::set of reserved names
Definition at line 325 of file OutputWarehouse.C.
{
  return _reserved;
}
getSyncTimes()
std::set< Real > & OutputWarehouse::getSyncTimes ()
Return the sync times for all objects.
Definition at line 294 of file OutputWarehouse.C.
{
  return _sync_times;
}
Referenced by TimePeriod::initialSetup().
hasOutput()
bool OutputWarehouse::hasOutput (const std::string & name) const
Returns true if the output object exists.
Parameters
name The name of the output object for which to test for existence within the warehouse
Definition at line 123 of file OutputWarehouse.C.
{
  return _object_map.find(name) != _object_map.end();
}
Referenced by FEProblemBase::addOutput(), checkOutputs(), and getOutput().
initialSetup()
void OutputWarehouse::initialSetup () private
Calls the initialSetup function for each of the output objects.
See also
FEProblemBase::initialSetup()
Definition at line 49 of file OutputWarehouse.C.
{
  TIME_SECTION("initialSetup", 5, "Setting Up Outputs");
  resetFileBase();
  for (const auto & obj : _all_objects)
    obj->initialSetup();
}
Referenced by DumpObjectsProblem::addAuxVariable().
isReservedName()
bool OutputWarehouse::isReservedName (const std::string & name)
Test if the given name is reserved.
Parameters
name The name to test
Returns
True if the name is reserved
Definition at line 331 of file OutputWarehouse.C.
{
  return _reserved.find(name) != _reserved.end();
}
Referenced by FEProblemBase::addOutput(), and checkOutputs().
jacobianSetup()
void OutputWarehouse::jacobianSetup () private
Calls the jacobianSetup function for each of the output objects.
See also
FEProblemBase::computeJacobian
Definition at line 81 of file OutputWarehouse.C.
{
  for (const auto & obj : _all_objects)
    obj->jacobianSetup();
}
Referenced by FEProblemBase::computeJacobianTags().
meshChanged()
void OutputWarehouse::meshChanged ()
Calls the meshChanged method for every output object.
Definition at line 176 of file OutputWarehouse.C.
{
  for (const auto & obj : _all_objects)
    obj->meshChanged();
}
Referenced by MooseApp::setOutputPosition().
mooseConsole() [1/2]
void OutputWarehouse::mooseConsole ()
Send current output buffer to Console output objects.
Definition at line 185 of file OutputWarehouse.C.
{
  mooseConsole(_console_buffer);
}
Referenced by DumpObjectsProblem::addAuxVariable(), callMooseErrorRaw(), flushConsoleBuffer(), mooseConsole(), ConsoleStream::operator<<(), and ~OutputWarehouse().
mooseConsole() [2/2]
void OutputWarehouse::mooseConsole (std::ostringstream & buffer)
Send a buffer to Console output objects.
Definition at line 191 of file OutputWarehouse.C.
{
  std::lock_guard<std::mutex> lock(moose_console_mutex);
  std::string message = buffer.str();
  // If someone else is writing - then we may need a newline
  if (&buffer != _last_buffer && !_last_message_ended_in_newline)
    message = '\n' + message;
  // Loop through all Console Output objects and pass the current output buffer
  std::vector<Console *> objects = getOutputs<Console>();
  if (!objects.empty())
  {
    for (const auto & obj : objects)
      obj->mooseConsole(message);
    // Reset
    buffer.clear();
    buffer.str("");
  }
  else if (!_app.actionWarehouse().isTaskComplete("add_output"))
  {
    if (!_buffer_action_console_outputs)
    {
      // this will cause messages to console before its construction immediately flushed and
      // cleared.
      bool this_message_ends_in_newline = message.empty() ? true : message.back() == '\n';
      // If that last message ended in newline then this one may need
      // to start with indenting
      // Note that we only indent the first line if the last message ended in new line
      if (_app.multiAppLevel() > 0)
        MooseUtils::indentMessage(_app.name(), message, COLOR_CYAN, _last_message_ended_in_newline);
      Moose::out << message << std::flush;
      buffer.clear();
      buffer.str("");
      _last_message_ended_in_newline = this_message_ends_in_newline;
    }
  }
  _last_buffer = &buffer;
  _num_printed++;
}
numPrinted()
unsigned long long int OutputWarehouse::numPrinted () const inline
The number of times something has been printed.
Definition at line 212 of file OutputWarehouse.h.
{ return _num_printed; }
Referenced by ConsoleStream::numPrinted().
outputStep()
void OutputWarehouse::outputStep (ExecFlagType type) private
Calls the outputStep method for each output object.
Parameters
type The type execution flag (see Moose.h)
This is private, users should utilize FEProblemBase::outputStep()
This is one of three locations where we explicitly flush the output buffers during a simulation: PetscOutput::petscNonlinearOutput() PetscOutput::petscLinearOutput() OutputWarehouse::outputStep()
All other Console output should be using newlines to avoid covering buffer errors and to avoid excessive I/O
Definition at line 150 of file OutputWarehouse.C.
{
  if (_force_output)
    type = EXEC_FORCED;
  for (const auto & obj : _all_objects)
    if (obj->enabled())
      obj->outputStep(type);
  flushConsoleBuffer();
  // Reset force output flag
  _force_output = false;
}
Referenced by FEProblemBase::outputStep().
perfGraph()
PerfGraph & PerfGraphInterface::perfGraph () inherited
Get the PerfGraph.
Definition at line 78 of file PerfGraphInterface.C.
{
  return _pg_moose_app.perfGraph();
}
Referenced by CommonOutputAction::act(), PerfGraphData::finalize(), and PerfGraphOutput::output().
registerTimedSection() [1/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
Returns
The ID of the section - use when starting timing
Definition at line 53 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(timed_section_name, level);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
registerTimedSection() [2/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level, const std::string & live_message, const bool print_dots = true) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
live_message The message to be printed to the screen during execution
print_dots Whether or not progress dots should be printed for this section
Returns
The ID of the section - use when starting timing
Definition at line 64 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(
        timedSectionName(section_name), level, live_message, print_dots);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
reset()
void OutputWarehouse::reset ()
Reset the output system.
Definition at line 356 of file OutputWarehouse.C.
{
  for (const auto & pair : _object_map)
  {
    auto * table = dynamic_cast<TableOutput *>(pair.second);
    if (table != NULL)
      table->clear();
    auto * exodus = dynamic_cast<Exodus *>(pair.second);
    if (exodus != NULL)
      exodus->clear();
  }
}
resetFileBase()
void OutputWarehouse::resetFileBase () private
Resets the file base for all FileOutput objects.
Definition at line 370 of file OutputWarehouse.C.
{
  // Set the file base from the application to FileOutputs and add associated filenames
  for (const auto & obj : _all_objects)
  {
    FileOutput * file_output = dynamic_cast<FileOutput *>(obj);
    if (file_output)
    {
      const std::string file_base = obj->parameters().get<bool>("_built_by_moose")
                                        ? _app.getOutputFileBase()
                                        : (_app.getOutputFileBase(true) + "_" + obj->name());
      file_output->setFileBase(file_base);
      addOutputFilename(obj->name(), file_output->filename());
    }
  }
}
Referenced by initialSetup(), and MooseApp::setOutputFileBase().
residualSetup()
void OutputWarehouse::residualSetup () private
Calls the residualSetup function for each of the output objects.
See also
FEProblemBase::computeResidualTyp
Definition at line 88 of file OutputWarehouse.C.
{
  for (const auto & obj : _all_objects)
    obj->residualSetup();
}
Referenced by FEProblemBase::computeResidualAndJacobian(), and FEProblemBase::computeResidualTags().
setCommonParameters()
void OutputWarehouse::setCommonParameters (const InputParameters * params_ptr)
Stores the common InputParameters object.
Parameters
params_ptr A pointer to the common parameters object to be stored
See also
CommonOutputAction
Definition at line 282 of file OutputWarehouse.C.
{
  _common_params_ptr = params_ptr;
}
Referenced by CommonOutputAction::act().
setFileNumbers()
void OutputWarehouse::setFileNumbers (std::map< std::string, unsigned int > input, unsigned int offset = 0)
Calls the setFileNumber method for every FileOutput output object.
Definition at line 247 of file OutputWarehouse.C.
{
  for (const auto & obj : _all_objects)
  {
    FileOutput * ptr = dynamic_cast<FileOutput *>(obj);
    if (ptr != NULL)
    {
      std::map<std::string, unsigned int>::const_iterator it = input.find(ptr->name());
      if (it != input.end())
      {
        int value = it->second + offset;
        if (value < 0)
          ptr->setFileNumber(0);
        else
          ptr->setFileNumber(it->second + offset);
      }
    }
  }
}
setOutputExecutionType()
void OutputWarehouse::setOutputExecutionType (ExecFlagType type) private
Sets the execution flag type.
This is a private method used by FEProblemBase, it is not intended for any other purpose
Definition at line 337 of file OutputWarehouse.C.
{
  _output_exec_flag = type;
}
solveSetup()
void OutputWarehouse::solveSetup ()
Calls the timestepSetup function for each of the output objects.
See also
FEProblemBase::solve() timestepSetup is too early for solver setup where we try to hook up monitor, change prefix, etc. SLEPc solver does not exist yet when we call timestepSetup. Moved this method from the private region to the public region so we can call this function from EigenProblem with no need to make EigenProblem as friend of OutputWarehouse.
Definition at line 74 of file OutputWarehouse.C.
{
  for (const auto & obj : _all_objects)
    obj->solveSetup();
}
Referenced by FEProblemBase::initPetscOutput(), and EigenProblem::initPetscOutput().
subdomainSetup()
void OutputWarehouse::subdomainSetup () private
Calls the subdomainSetup function for each of the output objects.
See also
FEProblemBase::setupSubdomain
Definition at line 95 of file OutputWarehouse.C.
{
  for (const auto & obj : _all_objects)
    obj->subdomainSetup();
}
Referenced by FEProblemBase::subdomainSetup().
timedSectionName()
std::string PerfGraphInterface::timedSectionName (const std::string & section_name) const protected inherited
Returns
The name of the timed section with the name section_name.
Optionally adds a prefix if one is defined.
Definition at line 47 of file PerfGraphInterface.C.
{
  return _prefix.empty() ? "" : (_prefix + "::") + section_name;
}
Referenced by PerfGraphInterface::registerTimedSection().
timestepSetup()
void OutputWarehouse::timestepSetup () private
Calls the timestepSetup function for each of the output objects.
See also
FEProblemBase::timestepSetup()
Definition at line 60 of file OutputWarehouse.C.
{
  for (const auto & obj : _all_objects)
    obj->timestepSetup();
}
validParams()
InputParameters PerfGraphInterface::validParams () static inherited
Definition at line 16 of file PerfGraphInterface.C.
{
  InputParameters params = emptyInputParameters();
  return params;
}
Friends And Related Function Documentation
FEProblemBase
friend class FEProblemBase friend
Definition at line 382 of file OutputWarehouse.h.
MaterialOutputAction
friend class MaterialOutputAction friend
Definition at line 385 of file OutputWarehouse.h.
MooseApp
friend class MooseApp friend
Definition at line 394 of file OutputWarehouse.h.
OutputInterface
friend class OutputInterface friend
Definition at line 388 of file OutputWarehouse.h.
PetscOutputInterface
friend class PetscOutputInterface friend
Definition at line 391 of file OutputWarehouse.h.
Member Data Documentation
_all_material_output_variables
std::set<AuxVariableName> OutputWarehouse::_all_material_output_variables private
List of all variable created by auto material output.
Definition at line 354 of file OutputWarehouse.h.
_all_objects
std::vector<Output *> OutputWarehouse::_all_objects private
All instances of objects (raw pointers)
Definition at line 327 of file OutputWarehouse.h.
Referenced by addOutput(), allowOutput(), customSetup(), getFileNumbers(), initialSetup(), jacobianSetup(), meshChanged(), outputStep(), resetFileBase(), residualSetup(), setFileNumbers(), solveSetup(), subdomainSetup(), and timestepSetup().
_all_ptrs
std::vector<std::shared_ptr<Output> > OutputWarehouse::_all_ptrs private
We are using std::shared_ptr to handle the cleanup of the pointers at the end of execution.
This is necessary since several warehouses might be sharing a single instance of a MooseObject.
Definition at line 245 of file OutputWarehouse.h.
Referenced by addOutput().
_app
MooseApp& OutputWarehouse::_app private
MooseApp.
Definition at line 324 of file OutputWarehouse.h.
Referenced by getOutputNames(), mooseConsole(), and resetFileBase().
_buffer_action_console_outputs
bool OutputWarehouse::_buffer_action_console_outputs private
True to buffer console outputs in actions.
Definition at line 330 of file OutputWarehouse.h.
Referenced by bufferConsoleOutputsBeforeConstruction(), and mooseConsole().
_common_params_ptr
const InputParameters* OutputWarehouse::_common_params_ptr private
Pointer to the common InputParameters (.
See also
CommonOutputAction)
Definition at line 342 of file OutputWarehouse.h.
Referenced by getCommonParameters(), and setCommonParameters().
_console_buffer
std::ostringstream OutputWarehouse::_console_buffer private
The stream for holding messages passed to _console prior to Output object construction.
Definition at line 360 of file OutputWarehouse.h.
Referenced by consoleBuffer(), flushConsoleBuffer(), mooseConsole(), and ~OutputWarehouse().
_file_base_map
std::map<OutputName, std::set<OutFileBase> > OutputWarehouse::_file_base_map private
List of object names.
Definition at line 339 of file OutputWarehouse.h.
Referenced by addOutputFilename().
_force_output
bool OutputWarehouse::_force_output private
Flag indicating that next call to outputStep is forced.
Definition at line 369 of file OutputWarehouse.h.
Referenced by forceOutput(), and outputStep().
_input_file_name
std::string OutputWarehouse::_input_file_name private
Input file name for this output object.
Definition at line 348 of file OutputWarehouse.h.
_interface_map
std::map<std::string, std::set<std::string> > OutputWarehouse::_interface_map private
Storage for variables to hide as prescribed by the object via the OutputInterface.
Definition at line 363 of file OutputWarehouse.h.
Referenced by addInterfaceHideVariables(), and buildInterfaceHideVariables().
_last_buffer
const std::ostringstream* OutputWarehouse::_last_buffer private
What the last buffer was that was printed.
Definition at line 375 of file OutputWarehouse.h.
Referenced by mooseConsole().
_last_message_ended_in_newline
bool OutputWarehouse::_last_message_ended_in_newline private
Whether or not the last thing output by mooseConsole had a newline as the last character.
Definition at line 372 of file OutputWarehouse.h.
Referenced by mooseConsole().
_material_output_map
std::map<OutputName, std::set<AuxVariableName> > OutputWarehouse::_material_output_map private
Map of output name and AuxVariable names to be output (used by auto Material output)
Definition at line 351 of file OutputWarehouse.h.
_num_printed
std::atomic<unsigned long long int> OutputWarehouse::_num_printed private
Number of times the stream has been printed to.
Definition at line 378 of file OutputWarehouse.h.
Referenced by mooseConsole(), and numPrinted().
_object_map
std::map<OutputName, Output *> OutputWarehouse::_object_map private
A map of the output pointers.
Definition at line 333 of file OutputWarehouse.h.
Referenced by addOutput(), getOutput(), getOutputNames(), getOutputs(), hasOutput(), and reset().
_object_names
std::set<OutputName> OutputWarehouse::_object_names private
A set of output names.
Definition at line 336 of file OutputWarehouse.h.
Referenced by addOutput(), and getOutputNames().
_output_exec_flag
ExecFlagType OutputWarehouse::_output_exec_flag private
The current output execution flag.
Definition at line 366 of file OutputWarehouse.h.
Referenced by setOutputExecutionType().
_pg_moose_app
MooseApp& PerfGraphInterface::_pg_moose_app protected inherited
The MooseApp that owns the PerfGraph.
Definition at line 124 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::perfGraph().
_prefix
const std::string PerfGraphInterface::_prefix protected inherited
A prefix to use for all sections.
Definition at line 127 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::timedSectionName().
_reserved
std::set<std::string> OutputWarehouse::_reserved private
List of reserved names.
Definition at line 357 of file OutputWarehouse.h.
Referenced by getReservedNames(), isReservedName(), and OutputWarehouse().
_sync_times
std::set<Real> OutputWarehouse::_sync_times private
Sync times for all objects.
Definition at line 345 of file OutputWarehouse.h.
Referenced by addOutput(), and getSyncTimes().
The documentation for this class was generated from the following files:
moose/framework/include/outputs/OutputWarehouse.h
moose/framework/src/outputs/OutputWarehouse.C