Zapdos: RestartableDataMap Class Reference
RestartableDataMap Class Reference
Storage for restartable data that is ordered based on insertion order.
#include <RestartableDataMap.h>
Classes
class Data
Protected storage for restartable data.
Public Member Functions
RestartableDataMap ()
RestartableDataValue & addData (std::unique_ptr< RestartableDataValue > data)
Adds the restartable data data to the map.
bool hasData (const std::string &name) const
RestartableDataValue & data (const std::string &name)
auto size () const
auto empty () const
const RestartableDataValue * findData (const std::string &name) const
Tries to find data with the name name; returns nullptr if not found.
RestartableDataValue * findData (const std::string &name)
auto begin ()
Begin and end iterators to the data.
auto end ()
auto begin () const
auto end () const
Private Attributes
RestartableDataMap::Data _data
The registered data.
std::unordered_map< std::string, std::size_t > _name_to_data_index
Mapping from data name -> index in _data for quick indexing.
Detailed Description
Storage for restartable data that is ordered based on insertion order.
The intent here is to be able to load declared restartable data in the order that it is instantiated.
Definition at line 27 of file RestartableDataMap.h.
Constructor & Destructor Documentation
RestartableDataMap()
RestartableDataMap::RestartableDataMap ()
Definition at line 14 of file RestartableDataMap.C.
{}
Member Function Documentation
addData()
RestartableDataValue & RestartableDataMap::addData (std::unique_ptr< RestartableDataValue > data)
Adds the restartable data data to the map.
Definition at line 17 of file RestartableDataMap.C.
{
  mooseAssert(data, "Not set");
  mooseAssert(!hasData(data->name()), "Name is already added");
  const auto & name = data->name();
  auto & inserted_data = _data.addPointer(std::move(data), {});
  _name_to_data_index.emplace(name, _data.size() - 1);
  mooseAssert(hasData(name), "Doesn't have data");
  return inserted_data;
}
Referenced by RestartableDataReader::restoreData().
begin() [1/2]
auto RestartableDataMap::begin () inline
Begin and end iterators to the data.
Definition at line 78 of file RestartableDataMap.h.
{ return _data.begin(); }
begin() [2/2]
auto RestartableDataMap::begin () const inline
Definition at line 80 of file RestartableDataMap.h.
{ return _data.begin(); }
data()
RestartableDataValue & RestartableDataMap::data (const std::string & name)
Returns
The data with the name name
Definition at line 65 of file RestartableDataMap.C.
{
  auto find_data = findData(name);
  if (!find_data)
    mooseError("Restartable data with the name ", name, " is not registered");
  return *find_data;
}
Referenced by addData(), and findData().
empty()
auto RestartableDataMap::empty () const inline
Returns
Whether or not there is no registered data
Definition at line 91 of file RestartableDataMap.h.
{ return _data.empty(); }
end() [1/2]
auto RestartableDataMap::end () inline
Definition at line 79 of file RestartableDataMap.h.
{ return _data.end(); }
end() [2/2]
auto RestartableDataMap::end () const inline
Definition at line 81 of file RestartableDataMap.h.
{ return _data.end(); }
findData() [1/2]
RestartableDataValue * RestartableDataMap::findData (const std::string & name)
Definition at line 58 of file RestartableDataMap.C.
{
  return const_cast<RestartableDataValue *>(
      const_cast<const RestartableDataMap *>(this)->findData(name));
}
findData() [2/2]
const RestartableDataValue * RestartableDataMap::findData (const std::string & name) const
Tries to find data with the name name; returns nullptr if not found.
Definition at line 32 of file RestartableDataMap.C.
{
  auto find_index = _name_to_data_index.find(name);
#ifndef NDEBUG
  auto find_it = std::find_if(
      _data.begin(), _data.end(), [&name](const auto & data) { return data.name() == name; });
#endif
  if (find_index == _name_to_data_index.end())
  {
    mooseAssert(find_it == _data.end(), "Inconsistent map");
    return nullptr;
  }
  const auto index = find_index->second;
  mooseAssert(index == (std::size_t)std::distance(_data.begin(), find_it), "Inconsistent map");
  mooseAssert(_data.size() > index, "Invalid index");
  auto & data = _data[index];
  mooseAssert(data.name() == name, "Inconsistent name");
  return &data;
}
Referenced by data(), findData(), and hasData().
hasData()
bool RestartableDataMap::hasData (const std::string & name) const
Returns
Whether or not data with the name name is added
Definition at line 74 of file RestartableDataMap.C.
{
  return findData(name) != nullptr;
}
Referenced by addData().
size()
auto RestartableDataMap::size () const inline
Returns
The size of registered data
Definition at line 87 of file RestartableDataMap.h.
{ return _data.size(); }
Referenced by RestartableDataWriter::write().
Member Data Documentation
_data
RestartableDataMap::Data RestartableDataMap::_data private
The registered data.
Definition at line 95 of file RestartableDataMap.h.
Referenced by addData(), begin(), empty(), end(), findData(), and size().
_name_to_data_index
std::unordered_map<std::string, std::size_t> RestartableDataMap::_name_to_data_index private
Mapping from data name -> index in _data for quick indexing.
Definition at line 97 of file RestartableDataMap.h.
Referenced by addData(), and findData().
The documentation for this class was generated from the following files:
moose/framework/include/restart/RestartableDataMap.h
moose/framework/src/restart/RestartableDataMap.C