Zapdos: MortarData Class Reference
MortarData Class Reference
#include <MortarData.h>
Public Member Functions
MortarData (const libMesh::ParallelObject &other)
void createMortarInterface (const std::pair< BoundaryID, BoundaryID > &boundary_key, const std::pair< SubdomainID, SubdomainID > &subdomain_key, SubProblem &subproblem, bool on_displaced, bool periodic, const bool debug, const bool correct_edge_dropping, const Real minimum_projection_angle)
Create mortar generation object.
const AutomaticMortarGeneration & getMortarInterface (const std::pair< BoundaryID, BoundaryID > &boundary_key, const std::pair< SubdomainID, SubdomainID > &, bool on_displaced) const
Getter to retrieve the AutomaticMortarGeneration object corresponding to the boundary and subdomain keys.
AutomaticMortarGeneration & getMortarInterface (const std::pair< BoundaryID, BoundaryID > &boundary_key, const std::pair< SubdomainID, SubdomainID > &, bool on_displaced)
Non-const getter to retrieve the AutomaticMortarGeneration object corresponding to the boundary and subdomain keys.
const std::unordered_map< std::pair< BoundaryID, BoundaryID >, AutomaticMortarGeneration > & getMortarInterfaces (bool on_displaced) const
Return all automatic mortar generation objects on either the displaced or undisplaced mesh.
const std::set< SubdomainID > & getMortarSubdomainIDs () const
Returns the mortar covered subdomains.
const std::set< BoundaryID > & getMortarBoundaryIDs () const
Returns the mortar covered boundaries.
void update ()
Builds mortar segment meshes for each mortar interface.
bool hasDisplacedObjects () const
Returns whether any of the AutomaticMortarGeneration objects are running on a displaced mesh.
bool hasObjects () const
Returns whether we have any active AutomaticMortarGeneration objects.
const std::set< SubdomainID > & getHigherDimSubdomainIDs (SubdomainID lower_d_subdomain_id) const
Returns the higher dimensional subdomain ids of the interior parents of the given lower-d subdomain id.
void notifyWhenMortarSetup (MortarExecutorInterface *mei)
Adds mei to the container of objects that will have their mortarSetup method called as soon as the mortar mesh has been generated for the first time
void dontNotifyWhenMortarSetup (MortarExecutorInterface *mei)
Removes mei from the container of objects that will have their mortarSetup method called as soon as the mortar mesh has been generated for the first time
bool initialized () const
Private Types
typedef std::pair< BoundaryID, BoundaryID > MortarKey
Private Member Functions
void update (AutomaticMortarGeneration &amg)
Builds mortar segment mesh from specific AutomaticMortarGeneration object.
Private Attributes
std::unordered_map< MortarKey, AutomaticMortarGeneration > _mortar_interfaces
Map from primary-secondary (in that order) boundary ID pair to the corresponding undisplaced AutomaticMortarGeneration object.
std::unordered_map< MortarKey, AutomaticMortarGeneration > _displaced_mortar_interfaces
Map from primary-secondary (in that order) boundary ID pair to the corresponding displaced AutomaticMortarGeneration object.
std::set< SubdomainID > _mortar_subdomain_coverage
A set containing the subdomain ids covered by all the mortar interfaces in this MortarData object.
std::set< BoundaryID > _mortar_boundary_coverage
A set containing the boundary ids covered by all the mortar interfaces in this MortarData object.
std::unordered_map< MortarKey, bool > _periodic_map
Map from undisplaced AMG key to whether the undisplaced AMG object is enforcing periodic constraints.
std::unordered_map< MortarKey, bool > _displaced_periodic_map
Map from displaced AMG key to whether the displaced AMG object is enforcing periodic constraints.
std::unordered_map< MortarKey, bool > _debug_flag_map
Map from undisplaced AMG key to whether the undisplaced AMG object is to output mortar segment mesh.
std::unordered_map< MortarKey, bool > _displaced_debug_flag_map
Map from displaced AMG key to whether the displaced AMG object is to output mortar segment mesh.
std::unordered_map< SubdomainID, std::set< SubdomainID > > _lower_d_sub_to_higher_d_subs
Map from lower dimensional subdomain ids to corresponding higher simensional subdomain ids (e.g.
std::set< MortarExecutorInterface * > _mei_objs
A container of objects for whom the mortarSetup method will be called after the mortar mesh has been setup for the first time.
bool _mortar_initd
Whether we have performed any mortar mesh construction.
Detailed Description
Definition at line 23 of file MortarData.h.
Member Typedef Documentation
MortarKey
typedef std::pair<BoundaryID, BoundaryID> MortarData::MortarKey private
Definition at line 135 of file MortarData.h.
Constructor & Destructor Documentation
MortarData()
MortarData::MortarData (const libMesh::ParallelObject & other)
Definition at line 16 of file MortarData.C.
  : libMesh::ParallelObject(other), _mortar_initd(false)
{
}
Member Function Documentation
createMortarInterface()
void MortarData::createMortarInterface (const std::pair< BoundaryID, BoundaryID > & boundary_key, const std::pair< SubdomainID, SubdomainID > & subdomain_key, SubProblem & subproblem, bool on_displaced, bool periodic, const bool debug, const bool correct_edge_dropping, const Real minimum_projection_angle)
Create mortar generation object.
Parameters
boundary_key The primary-secondary boundary pair on which the AMG objects lives
subdomain_key The primary-secondary subdomain pair on which the AMG objects lives
subproblem A reference to the subproblem
on_displaced Whether the AMG object lives on the displaced mesh
periodic Whether the AMG object will be used for enforcing periodic constraints. Note that this changes the direction of the projection normals so one AMG object cannot be used to enforce both periodic and non-periodic constraints
debug whether to output mortar segment mesh exodus file for debugging purposes
correct_edge_dropping edge dropping treatment selection
minimum_projection_angle minimum projection angle allowed for building mortar segment mesh
Definition at line 22 of file MortarData.C.
{
  _mortar_subdomain_coverage.insert(subdomain_key.first);
  _mortar_subdomain_coverage.insert(subdomain_key.second);
  _mortar_boundary_coverage.insert(boundary_key.first);
  _mortar_boundary_coverage.insert(boundary_key.second);
  MeshBase & mesh = subproblem.mesh().getMesh();
  auto & periodic_map = on_displaced ? _displaced_periodic_map : _periodic_map;
  auto & debug_flag_map = on_displaced ? _displaced_debug_flag_map : _debug_flag_map;
  auto & mortar_interfaces = on_displaced ? _displaced_mortar_interfaces : _mortar_interfaces;
  // Periodic flag
  auto periodic_map_iterator = periodic_map.find(boundary_key);
  if (periodic_map_iterator != periodic_map.end() && periodic_map_iterator->second != periodic)
    mooseError("We do not currently support enforcing both periodic and non-periodic constraints "
               "on the same boundary primary-secondary pair");
  else
    periodic_map.insert(periodic_map_iterator, std::make_pair(boundary_key, periodic));
  // Debug mesh flag displaced
  auto debug_flag_map_iterator = debug_flag_map.find(boundary_key);
  if (debug_flag_map_iterator != debug_flag_map.end() && debug_flag_map_iterator->second != debug)
    mooseError(
        "We do not currently support generating and not generating debug output "
        "on the same boundary primary-secondary surface pair. Please set debug_mesh = true for "
        "all constraints sharing the same primary-secondary surface pairs");
  else
    debug_flag_map.insert(debug_flag_map_iterator, std::make_pair(boundary_key, debug));
  // Generate lower-d mesh
  if (mortar_interfaces.find(boundary_key) == mortar_interfaces.end())
  {
    auto [it, inserted] =
        mortar_interfaces.emplace(boundary_key,
                                  AutomaticMortarGeneration(subproblem.getMooseApp(),
                                                            mesh,
                                                            boundary_key,
                                                            subdomain_key,
                                                            on_displaced,
                                                            periodic,
                                                            debug,
                                                            correct_edge_dropping,
                                                            minimum_projection_angle));
    if (inserted)
      it->second.initOutput();
  }
  // See whether to query the mesh
  SubdomainID key1 = subdomain_key.first;
  SubdomainID key2 = subdomain_key.second;
  // it(1,2) is a a pair consisting of an iterator to the inserted element (or to the element that
  // prevented the insertion) and a bool denoting whether the insertion took place.
  auto it1 = _lower_d_sub_to_higher_d_subs.insert(std::make_pair(key1, std::set<SubdomainID>{}));
  auto it2 = _lower_d_sub_to_higher_d_subs.insert(std::make_pair(key2, std::set<SubdomainID>{}));
  // Each entry in this vector will be a pair. The first member of the pair corresponds to
  // the lower dimensional subomain ID. The second member of the pair corresponds to the higher
  // dimensional subdomain ids of the lower dimeionsal interior parents
  std::vector<std::pair<SubdomainID, std::set<SubdomainID> *>> subdomains_to_probe;
  if (it1.second)
    subdomains_to_probe.push_back(std::make_pair(key1, &it1.first->second));
  if (it2.second)
    subdomains_to_probe.push_back(std::make_pair(key2, &it2.first->second));
  for (auto & pr : subdomains_to_probe)
  {
    for (const Elem * lower_d_elem : as_range(mesh.active_local_subdomain_elements_begin(pr.first),
                                              mesh.active_local_subdomain_elements_end(pr.first)))
    {
      const Elem * ip = lower_d_elem->interior_parent();
      mooseAssert(
          ip,
          "Lower dimensional elements should always have an interior parent set when using mortar");
      pr.second->insert(ip->subdomain_id());
    }
    // Make sure that we get this right in parallel
    _communicator.set_union(*pr.second);
  }
}
Referenced by FEProblemBase::createMortarInterface().
dontNotifyWhenMortarSetup()
void MortarData::dontNotifyWhenMortarSetup (MortarExecutorInterface * mei)
Removes mei from the container of objects that will have their mortarSetup method called as soon as the mortar mesh has been generated for the first time
Definition at line 210 of file MortarData.C.
{
  _mei_objs.erase(mei_obj);
}
getHigherDimSubdomainIDs()
const std::set< SubdomainID > & MortarData::getHigherDimSubdomainIDs (SubdomainID lower_d_subdomain_id) const
Returns the higher dimensional subdomain ids of the interior parents of the given lower-d subdomain id.
Definition at line 194 of file MortarData.C.
{
  if (_lower_d_sub_to_higher_d_subs.find(lower_d_subdomain_id) ==
      _lower_d_sub_to_higher_d_subs.end())
    mooseError(
        "The lower dimensional ID ", lower_d_subdomain_id, " has not been added to MortarData yet");
  return _lower_d_sub_to_higher_d_subs.at(lower_d_subdomain_id);
}
Referenced by MortarConsumerInterface::MortarConsumerInterface().
getMortarBoundaryIDs()
const std::set< BoundaryID > & MortarData::getMortarBoundaryIDs () const inline
Returns the mortar covered boundaries.
Definition at line 89 of file MortarData.h.
{ return _mortar_boundary_coverage; }
getMortarInterface() [1/2]
AutomaticMortarGeneration & MortarData::getMortarInterface (const std::pair< BoundaryID, BoundaryID > & boundary_key, const std::pair< SubdomainID, SubdomainID > & subdomain_key, bool on_displaced)
Non-const getter to retrieve the AutomaticMortarGeneration object corresponding to the boundary and subdomain keys.
If the AutomaticMortarGeneration object does not yet exist, then we error
Definition at line 139 of file MortarData.C.
{
  return const_cast<AutomaticMortarGeneration &>(
      const_cast<const MortarData *>(this)->getMortarInterface(
          boundary_key, subdomain_key, on_displaced));
}
getMortarInterface() [2/2]
const AutomaticMortarGeneration & MortarData::getMortarInterface (const std::pair< BoundaryID, BoundaryID > & boundary_key, const std::pair< SubdomainID, SubdomainID > & , bool on_displaced) const
Getter to retrieve the AutomaticMortarGeneration object corresponding to the boundary and subdomain keys.
If the AutomaticMortarGeneration object does not yet exist, then we error
Definition at line 116 of file MortarData.C.
{
  if (on_displaced)
  {
    if (_displaced_mortar_interfaces.find(boundary_key) == _displaced_mortar_interfaces.end())
      mooseError(
          "The requested mortar interface AutomaticMortarGeneration object does not yet exist!");
    return _displaced_mortar_interfaces.at(boundary_key);
  }
  else
  {
    if (_mortar_interfaces.find(boundary_key) == _mortar_interfaces.end())
      mooseError(
          "The requested mortar interface AutomaticMortarGeneration object does not yet exist!");
    return _mortar_interfaces.at(boundary_key);
  }
}
Referenced by getMortarInterface(), and FEProblemBase::getMortarInterface().
getMortarInterfaces()
const std::unordered_map< std::pair< BoundaryID, BoundaryID >, AutomaticMortarGeneration > & MortarData::getMortarInterfaces (bool on_displaced) const inline
Return all automatic mortar generation objects on either the displaced or undisplaced mesh.
Definition at line 73 of file MortarData.h.
  {
    if (on_displaced)
      return _displaced_mortar_interfaces;
    else
      return _mortar_interfaces;
  }
Referenced by FEProblemBase::getMortarInterfaces().
getMortarSubdomainIDs()
const std::set< SubdomainID > & MortarData::getMortarSubdomainIDs () const inline
Returns the mortar covered subdomains.
Definition at line 84 of file MortarData.h.
{ return _mortar_subdomain_coverage; }
Referenced by FEProblemBase::checkProblemIntegrity().
hasDisplacedObjects()
bool MortarData::hasDisplacedObjects () const inline
Returns whether any of the AutomaticMortarGeneration objects are running on a displaced mesh.
Definition at line 99 of file MortarData.h.
{ return _displaced_mortar_interfaces.size(); }
Referenced by DumpObjectsProblem::addAuxVariable(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), and FEProblemBase::reinitBecauseOfGhostingOrNewGeomObjects().
hasObjects()
bool MortarData::hasObjects () const inline
Returns whether we have any active AutomaticMortarGeneration objects.
Definition at line 104 of file MortarData.h.
{ return _mortar_interfaces.size(); }
Referenced by FEProblemBase::reinitBecauseOfGhostingOrNewGeomObjects().
initialized()
bool MortarData::initialized () const inline
Returns
whether we have performed an initial mortar mesh construction
Definition at line 127 of file MortarData.h.
{ return _mortar_initd; }
Referenced by FEProblemBase::init().
notifyWhenMortarSetup()
void MortarData::notifyWhenMortarSetup (MortarExecutorInterface * mei)
Adds mei to the container of objects that will have their mortarSetup method called as soon as the mortar mesh has been generated for the first time
Definition at line 204 of file MortarData.C.
{
  _mei_objs.insert(mei_obj);
}
update() [1/2]
void MortarData::update ()
Builds mortar segment meshes for each mortar interface.
Definition at line 149 of file MortarData.C.
{
  for (auto & mortar_pair : _mortar_interfaces)
    update(mortar_pair.second);
  for (auto & mortar_pair : _displaced_mortar_interfaces)
    update(mortar_pair.second);
  _mortar_initd = true;
}
Referenced by update(), and FEProblemBase::updateMortarMesh().
update() [2/2]
void MortarData::update (AutomaticMortarGeneration & amg) private
Builds mortar segment mesh from specific AutomaticMortarGeneration object.
Definition at line 160 of file MortarData.C.
{
  // Clear exiting data
  amg.clear();
  // Construct maps from nodes -> lower dimensional elements on the primary and secondary
  // boundaries.
  amg.buildNodeToElemMaps();
  // Compute nodal geometry (normals and tangents).
  amg.computeNodalGeometry();
  const auto dim = amg.dim();
  if (dim == 2)
  {
    // Project secondary nodes (find xi^(2) values).
    amg.projectSecondaryNodes();
    // Project primary nodes (find xi^(1) values).
    amg.projectPrimaryNodes();
    // Build the mortar segment mesh on the secondary boundary.
    amg.buildMortarSegmentMesh();
  }
  else if (dim == 3)
    amg.buildMortarSegmentMesh3d();
  else
    mooseError("Invalid mesh dimension for mortar constraint");
  amg.computeInactiveLMNodes();
  amg.computeInactiveLMElems();
}
Member Data Documentation
_debug_flag_map
std::unordered_map<MortarKey, bool> MortarData::_debug_flag_map private
Map from undisplaced AMG key to whether the undisplaced AMG object is to output mortar segment mesh.
Definition at line 160 of file MortarData.h.
Referenced by createMortarInterface().
_displaced_debug_flag_map
std::unordered_map<MortarKey, bool> MortarData::_displaced_debug_flag_map private
Map from displaced AMG key to whether the displaced AMG object is to output mortar segment mesh.
Definition at line 163 of file MortarData.h.
Referenced by createMortarInterface().
_displaced_mortar_interfaces
std::unordered_map<MortarKey, AutomaticMortarGeneration> MortarData::_displaced_mortar_interfaces private
Map from primary-secondary (in that order) boundary ID pair to the corresponding displaced AutomaticMortarGeneration object.
Definition at line 143 of file MortarData.h.
Referenced by createMortarInterface(), getMortarInterface(), getMortarInterfaces(), hasDisplacedObjects(), and update().
_displaced_periodic_map
std::unordered_map<MortarKey, bool> MortarData::_displaced_periodic_map private
Map from displaced AMG key to whether the displaced AMG object is enforcing periodic constraints.
Definition at line 157 of file MortarData.h.
Referenced by createMortarInterface().
_lower_d_sub_to_higher_d_subs
std::unordered_map<SubdomainID, std::set<SubdomainID> > MortarData::_lower_d_sub_to_higher_d_subs private
Map from lower dimensional subdomain ids to corresponding higher simensional subdomain ids (e.g.
the ids of the interior parents)
Definition at line 167 of file MortarData.h.
Referenced by createMortarInterface(), and getHigherDimSubdomainIDs().
_mei_objs
std::set<MortarExecutorInterface *> MortarData::_mei_objs private
A container of objects for whom the mortarSetup method will be called after the mortar mesh has been setup for the first time.
Definition at line 171 of file MortarData.h.
Referenced by dontNotifyWhenMortarSetup(), and notifyWhenMortarSetup().
_mortar_boundary_coverage
std::set<BoundaryID> MortarData::_mortar_boundary_coverage private
A set containing the boundary ids covered by all the mortar interfaces in this MortarData object.
Definition at line 151 of file MortarData.h.
Referenced by createMortarInterface(), and getMortarBoundaryIDs().
_mortar_initd
bool MortarData::_mortar_initd private
Whether we have performed any mortar mesh construction.
Definition at line 174 of file MortarData.h.
Referenced by initialized(), and update().
_mortar_interfaces
std::unordered_map<MortarKey, AutomaticMortarGeneration> MortarData::_mortar_interfaces private
Map from primary-secondary (in that order) boundary ID pair to the corresponding undisplaced AutomaticMortarGeneration object.
Definition at line 139 of file MortarData.h.
Referenced by createMortarInterface(), getMortarInterface(), getMortarInterfaces(), hasObjects(), and update().
_mortar_subdomain_coverage
std::set<SubdomainID> MortarData::_mortar_subdomain_coverage private
A set containing the subdomain ids covered by all the mortar interfaces in this MortarData object.
Definition at line 147 of file MortarData.h.
Referenced by createMortarInterface(), and getMortarSubdomainIDs().
_periodic_map
std::unordered_map<MortarKey, bool> MortarData::_periodic_map private
Map from undisplaced AMG key to whether the undisplaced AMG object is enforcing periodic constraints.
Definition at line 154 of file MortarData.h.
Referenced by createMortarInterface().
The documentation for this class was generated from the following files:
moose/framework/include/constraints/MortarData.h
moose/framework/src/constraints/MortarData.C