Zapdos: PropertyValue Class Reference
PropertyValue Class Reference abstract
Abstract definition of a property value.
#include <MaterialProperty.h>
Public Types
typedef unsigned int id_type
The type for a material property ID.
Public Member Functions
PropertyValue (const id_type id)
virtual ~PropertyValue ()
id_type id () const
virtual const std::string & type () const =0
String identifying the type of parameter stored.
virtual std::unique_ptr< PropertyValue > clone (const std::size_t) const =0
Clone this value.
virtual unsigned int size () const =0
virtual void resize (const std::size_t size)=0
Resizes the property to the size n.
virtual void swap (PropertyValue &rhs)=0
virtual bool isAD () const =0
virtual void qpCopy (const unsigned int to_qp, const PropertyValue &rhs, const unsigned int from_qp)=0
Copy the value of a Property from one specific to a specific qp in this Property.
virtual void store (std::ostream &stream)=0
virtual void load (std::istream &stream)=0
virtual const std::type_info & typeID () const =0
Static Public Attributes
static constexpr id_type invalid_property_id = std::numeric_limits<id_type>::max() - 1
The material property ID for an invalid property We only have this because there are a few cases where folks want to instantiate their own fake materials, and we should at least force them to be consistent.
Protected Attributes
const id_type _id
The material property ID.
Detailed Description
Abstract definition of a property value.
Definition at line 38 of file MaterialProperty.h.
Member Typedef Documentation
id_type
typedef unsigned int PropertyValue::id_type
The type for a material property ID.
Definition at line 42 of file MaterialProperty.h.
Constructor & Destructor Documentation
PropertyValue()
PropertyValue::PropertyValue (const id_type id) inline
Definition at line 44 of file MaterialProperty.h.
: _id(id) {}
~PropertyValue()
virtual PropertyValue::~PropertyValue () inline virtual
Definition at line 46 of file MaterialProperty.h.
{};
Member Function Documentation
clone()
virtual std::unique_ptr< PropertyValue > PropertyValue::clone (const std::size_t) const pure virtual
Clone this value.
Useful in copy-construction.
Implemented in MaterialPropertyBase< T, is_ad >, MaterialPropertyBase< Real, true >, MaterialPropertyBase< T, true >, MaterialPropertyBase< Real, false >, MaterialPropertyBase< RankFourTensor, false >, MaterialPropertyBase< RankTwoTensor, false >, MaterialPropertyBase< T, false >, MaterialPropertyBase< RealVectorValue, true >, MaterialPropertyBase< RealEigenVector, false >, MaterialPropertyBase< RealEigenMatrix, false >, and MaterialPropertyBase< unsigned int, false >.
id()
id_type PropertyValue::id () const inline
Returns
The ID of the underlying material property
Definition at line 56 of file MaterialProperty.h.
{ return _id; }
Referenced by MaterialPropertyBase< T, is_ad >::swap().
isAD()
virtual bool PropertyValue::isAD () const pure virtual
Implemented in MaterialPropertyBase< T, is_ad >, MaterialPropertyBase< Real, true >, MaterialPropertyBase< T, true >, MaterialPropertyBase< Real, false >, MaterialPropertyBase< RankFourTensor, false >, MaterialPropertyBase< RankTwoTensor, false >, MaterialPropertyBase< T, false >, MaterialPropertyBase< RealVectorValue, true >, MaterialPropertyBase< RealEigenVector, false >, MaterialPropertyBase< RealEigenMatrix, false >, and MaterialPropertyBase< unsigned int, false >.
Referenced by MaterialPropertyBase< T, is_ad >::qpCopy(), and MaterialPropertyBase< T, is_ad >::swap().
load()
virtual void PropertyValue::load (std::istream & stream) pure virtual
Implemented in MaterialPropertyBase< T, is_ad >, MaterialPropertyBase< Real, true >, MaterialPropertyBase< T, true >, MaterialPropertyBase< Real, false >, MaterialPropertyBase< RankFourTensor, false >, MaterialPropertyBase< RankTwoTensor, false >, MaterialPropertyBase< T, false >, MaterialPropertyBase< RealVectorValue, true >, MaterialPropertyBase< RealEigenVector, false >, MaterialPropertyBase< RealEigenMatrix, false >, and MaterialPropertyBase< unsigned int, false >.
Referenced by dataLoad().
qpCopy()
virtual void PropertyValue::qpCopy (const unsigned int to_qp, const PropertyValue & rhs, const unsigned int from_qp) pure virtual
Copy the value of a Property from one specific to a specific qp in this Property.
Important note: this copy operation loses AD derivative information if either this or the rhs is not an AD material property
Parameters
to_qp The quadrature point in this Property that you want to copy to.
rhs The Property you want to copy from.
from_qp The quadrature point in rhs you want to copy from.
Implemented in MaterialPropertyBase< T, is_ad >, MaterialPropertyBase< Real, true >, MaterialPropertyBase< T, true >, MaterialPropertyBase< Real, false >, MaterialPropertyBase< RankFourTensor, false >, MaterialPropertyBase< RankTwoTensor, false >, MaterialPropertyBase< T, false >, MaterialPropertyBase< RealVectorValue, true >, MaterialPropertyBase< RealEigenVector, false >, MaterialPropertyBase< RealEigenMatrix, false >, and MaterialPropertyBase< unsigned int, false >.
resize()
virtual void PropertyValue::resize (const std::size_t size) pure virtual
Resizes the property to the size n.
Implemented in MaterialPropertyBase< T, is_ad >, MaterialPropertyBase< Real, true >, MaterialPropertyBase< T, true >, MaterialPropertyBase< Real, false >, MaterialPropertyBase< RankFourTensor, false >, MaterialPropertyBase< RankTwoTensor, false >, MaterialPropertyBase< T, false >, MaterialPropertyBase< RealVectorValue, true >, MaterialPropertyBase< RealEigenVector, false >, MaterialPropertyBase< RealEigenMatrix, false >, and MaterialPropertyBase< unsigned int, false >.
size()
virtual unsigned int PropertyValue::size () const pure virtual
Implemented in MaterialPropertyBase< T, is_ad >, MaterialPropertyBase< Real, true >, MaterialPropertyBase< T, true >, MaterialPropertyBase< Real, false >, MaterialPropertyBase< RankFourTensor, false >, MaterialPropertyBase< RankTwoTensor, false >, MaterialPropertyBase< T, false >, MaterialPropertyBase< RealVectorValue, true >, MaterialPropertyBase< RealEigenVector, false >, MaterialPropertyBase< RealEigenMatrix, false >, and MaterialPropertyBase< unsigned int, false >.
store()
virtual void PropertyValue::store (std::ostream & stream) pure virtual
Implemented in MaterialPropertyBase< T, is_ad >, MaterialPropertyBase< Real, true >, MaterialPropertyBase< T, true >, MaterialPropertyBase< Real, false >, MaterialPropertyBase< RankFourTensor, false >, MaterialPropertyBase< RankTwoTensor, false >, MaterialPropertyBase< T, false >, MaterialPropertyBase< RealVectorValue, true >, MaterialPropertyBase< RealEigenVector, false >, MaterialPropertyBase< RealEigenMatrix, false >, and MaterialPropertyBase< unsigned int, false >.
Referenced by dataStore().
swap()
virtual void PropertyValue::swap (PropertyValue & rhs) pure virtual
Implemented in MaterialPropertyBase< T, is_ad >, MaterialPropertyBase< Real, true >, MaterialPropertyBase< T, true >, MaterialPropertyBase< Real, false >, MaterialPropertyBase< RankFourTensor, false >, MaterialPropertyBase< RankTwoTensor, false >, MaterialPropertyBase< T, false >, MaterialPropertyBase< RealVectorValue, true >, MaterialPropertyBase< RealEigenVector, false >, MaterialPropertyBase< RealEigenMatrix, false >, and MaterialPropertyBase< unsigned int, false >.
type()
virtual const std::string & PropertyValue::type () const pure virtual
String identifying the type of parameter stored.
Implemented in MaterialPropertyBase< T, is_ad >, MaterialPropertyBase< Real, true >, MaterialPropertyBase< T, true >, MaterialPropertyBase< Real, false >, MaterialPropertyBase< RankFourTensor, false >, MaterialPropertyBase< RankTwoTensor, false >, MaterialPropertyBase< T, false >, MaterialPropertyBase< RealVectorValue, true >, MaterialPropertyBase< RealEigenVector, false >, MaterialPropertyBase< RealEigenMatrix, false >, and MaterialPropertyBase< unsigned int, false >.
typeID()
virtual const std::type_info & PropertyValue::typeID () const pure virtual
Returns
The type_info for the underlying stored type T
Implemented in MaterialPropertyBase< T, is_ad >, MaterialPropertyBase< Real, true >, MaterialPropertyBase< T, true >, MaterialPropertyBase< Real, false >, MaterialPropertyBase< RankFourTensor, false >, MaterialPropertyBase< RankTwoTensor, false >, MaterialPropertyBase< T, false >, MaterialPropertyBase< RealVectorValue, true >, MaterialPropertyBase< RealEigenVector, false >, MaterialPropertyBase< RealEigenMatrix, false >, and MaterialPropertyBase< unsigned int, false >.
Referenced by MaterialPropertyBase< T, is_ad >::swap().
Member Data Documentation
_id
const id_type PropertyValue::_id protected
The material property ID.
Definition at line 102 of file MaterialProperty.h.
Referenced by id().
invalid_property_id
constexpr id_type PropertyValue::invalid_property_id = std::numeric_limits<id_type>::max() - 1 static constexpr
The material property ID for an invalid property We only have this because there are a few cases where folks want to instantiate their own fake materials, and we should at least force them to be consistent.
Definition at line 51 of file MaterialProperty.h.
The documentation for this class was generated from the following file:
moose/framework/include/materials/MaterialProperty.h