Zapdos: ReporterMode Class Reference
ReporterMode Class Reference
MooseEnumItem that automatically creates the ID and doesn't allow the ID to be assigned.
#include <ReporterMode.h>
Public Member Functions
ReporterMode (const std::string &key)
bool operator< (const MooseEnumItem &other) const
Less than operator.
void setID (const int &id)
Method to change the ID of the item, but only if it is an INVALID_ID.
const int & id () const
Return the numeric, name, or raw name.
const std::string & name () const
const std::string & rawName () const
operator int () const
Operator to allow this class to be used directly as a string for int.
operator std::string () const
bool operator== (const char *value) const
Comparison operators.
bool operator== (const std::string &value) const
bool operator== (int value) const
bool operator== (unsigned short value) const
bool operator== (const MooseEnumItem &) const
bool operator!= (const char *value) const
bool operator!= (const std::string &value) const
bool operator!= (int value) const
bool operator!= (unsigned short value) const
bool operator!= (const MooseEnumItem &) const
Static Public Attributes
static const int INVALID_ID = std::numeric_limits<int>::min()
Private Attributes
std::string _raw_name
The name as provided in constructor.
std::string _name
Upper case name.
int _id
The numeric value for item.
Static Private Attributes
static int ID_COUNTER = 0
Detailed Description
MooseEnumItem that automatically creates the ID and doesn't allow the ID to be assigned.
This protects user from hitting an ID collision when creating custom modes.
Definition at line 44 of file ReporterMode.h.
Constructor & Destructor Documentation
ReporterMode()
ReporterMode::ReporterMode (const std::string & key)
Definition at line 16 of file ReporterMode.C.
: MooseEnumItem(key, ID_COUNTER++) {}
Member Function Documentation
id()
const int & MooseEnumItem::id () const inline inherited
Return the numeric, name, or raw name.
Definition at line 34 of file MooseEnumItem.h.
{ return _id; }
Referenced by MooseEnumBase::addEnumerationItem(), AttribExecOns::AttribExecOns(), MooseEnum::compareCurrent(), MooseEnum::getEnum(), MooseEnum::isValid(), MooseEnum::operator int(), MooseEnumItem::operator!=(), MooseEnumItem::operator==(), and MooseEnumItem::setID().
name()
const std::string & MooseEnumItem::name () const inline inherited
Definition at line 35 of file MooseEnumItem.h.
{ return _name; }
Referenced by MooseEnumBase::addEnumerationItem(), MooseEnumBase::checkDeprecated(), MooseEnum::compareCurrent(), Transient::constrainDTFromMultiApp(), MooseEnumBase::find(), FEProblemBase::joinAndFinalize(), MooseEnumItem::operator!=(), MooseEnum::operator!=(), MooseEnumItem::operator==(), MooseEnum::operator==(), and ComputeDiracThread::printGeneralExecutionInformation().
operator int()
MooseEnumItem::operator int () const inline inherited
Operator to allow this class to be used directly as a string for int.
Definition at line 43 of file MooseEnumItem.h.
{ return _id; }
operator std::string()
MooseEnumItem::operator std::string () const inline inherited
Definition at line 44 of file MooseEnumItem.h.
{ return _name; }
operator!=() [1/5]
bool MooseEnumItem::operator!= (const char * value) const inherited
Definition at line 43 of file MooseEnumItem.C.
{
  std::string name(MooseUtils::toUpper(value));
  return _name != name;
}
operator!=() [2/5]
bool MooseEnumItem::operator!= (const MooseEnumItem & item) const inherited
Definition at line 70 of file MooseEnumItem.C.
{
  return _id != item.id() && _name != MooseUtils::toUpper(item.name());
}
operator!=() [3/5]
bool MooseEnumItem::operator!= (const std::string & value) const inherited
Definition at line 57 of file MooseEnumItem.C.
{
  std::string name(MooseUtils::toUpper(value));
  return _name != name;
}
operator!=() [4/5]
bool MooseEnumItem::operator!= (int value) const inline inherited
Definition at line 60 of file MooseEnumItem.h.
{ return _id != value; }
operator!=() [5/5]
bool MooseEnumItem::operator!= (unsigned short value) const inline inherited
Definition at line 63 of file MooseEnumItem.h.
{ return _id != value; }
operator<()
bool MooseEnumItem::operator< (const MooseEnumItem & other) const inline inherited
Less than operator.
This is required for this class to work in maps and sets.
Definition at line 72 of file MooseEnumItem.h.
  {
    return _id != other._id ? _id < other._id : _name < other._name;
  }
operator==() [1/5]
bool MooseEnumItem::operator== (const char * value) const inherited
Comparison operators.
The comparison operators using the char * and string are case sensitive.
Definition at line 36 of file MooseEnumItem.C.
{
  std::string name(MooseUtils::toUpper(value));
  return _name == name;
}
operator==() [2/5]
bool MooseEnumItem::operator== (const MooseEnumItem & item) const inherited
Definition at line 64 of file MooseEnumItem.C.
{
  return _id == item.id() && _name == MooseUtils::toUpper(item.name());
}
operator==() [3/5]
bool MooseEnumItem::operator== (const std::string & value) const inherited
Definition at line 50 of file MooseEnumItem.C.
{
  std::string name(MooseUtils::toUpper(value));
  return _name == name;
}
operator==() [4/5]
bool MooseEnumItem::operator== (int value) const inline inherited
Definition at line 59 of file MooseEnumItem.h.
{ return _id == value; }
operator==() [5/5]
bool MooseEnumItem::operator== (unsigned short value) const inline inherited
Definition at line 62 of file MooseEnumItem.h.
{ return _id == value; }
rawName()
const std::string & MooseEnumItem::rawName () const inline inherited
Definition at line 36 of file MooseEnumItem.h.
{ return _raw_name; }
Referenced by MooseEnum::operator std::string().
setID()
void MooseEnumItem::setID (const int & id) inherited
Method to change the ID of the item, but only if it is an INVALID_ID.
An error is produced if the ID is valid and this method is called.
This is needed to allow ExecFlagType objects to be created without an ID being provided, the ID is assigned when ExecFlagEnum::addAvailableFlags is called.
Definition at line 83 of file MooseEnumItem.C.
{
  if (_id != INVALID_ID)
    mooseError("The ID of a MooseEnumItem can not be changed if it is valid, the item ",
               _name,
               " has a valid id of ",
               _id,
               ".");
  _id = id;
}
Member Data Documentation
_id
int MooseEnumItem::_id private inherited
The numeric value for item.
Definition at line 99 of file MooseEnumItem.h.
Referenced by MooseEnumItem::id(), MooseEnumItem::operator int(), MooseEnumItem::operator!=(), MooseEnumItem::operator<(), MooseEnumItem::operator=(), MooseEnumItem::operator==(), and MooseEnumItem::setID().
_name
std::string MooseEnumItem::_name private inherited
Upper case name.
Definition at line 96 of file MooseEnumItem.h.
Referenced by MooseEnumItem::name(), MooseEnumItem::operator std::string(), MooseEnumItem::operator!=(), MooseEnumItem::operator<(), MooseEnumItem::operator=(), MooseEnumItem::operator==(), and MooseEnumItem::setID().
_raw_name
std::string MooseEnumItem::_raw_name private inherited
The name as provided in constructor.
Definition at line 93 of file MooseEnumItem.h.
Referenced by MooseEnumItem::operator=(), and MooseEnumItem::rawName().
ID_COUNTER
int ReporterMode::ID_COUNTER = 0 static private
Definition at line 51 of file ReporterMode.h.
INVALID_ID
const int MooseEnumItem::INVALID_ID = std::numeric_limits<int>::min() static inherited
Definition at line 21 of file MooseEnumItem.h.
Referenced by MooseEnum::assign(), MooseEnum::isValid(), and MooseEnumItem::setID().
The documentation for this class was generated from the following files:
moose/framework/include/reporters/ReporterMode.h
moose/framework/src/reporters/ReporterMode.C