Zapdos: CyclicDependencyException< T, Compare > Class Template Reference
CyclicDependencyException< T, Compare > Class Template Reference
#include <DependencyResolver.h>
Public Member Functions
CyclicDependencyException (const std::string &error, const DependencyResolver< T, Compare > &graph) throw ()
CyclicDependencyException (const CyclicDependencyException &e) throw ()
~CyclicDependencyException () throw ()
const std::vector< T > & getCyclicDependencies () const
Private Attributes
std::vector< T > _cyclic_graph
Detailed Description
template<class T, class Compare = std::less<T>>
class CyclicDependencyException< T, Compare >
Definition at line 433 of file DependencyResolver.h.
Constructor & Destructor Documentation
CyclicDependencyException() [1/2]
template<class T , class Compare = std::less<T>> CyclicDependencyException< T, Compare >::CyclicDependencyException (const std::string & error, const DependencyResolver< T, Compare > & graph) throw () inline
Definition at line 436 of file DependencyResolver.h.
    : runtime_error(error)
  {
    const auto & sorted = graph._sorted_vector;
    auto first_occurence = std::find(sorted.begin(), sorted.end(), graph._circular_node);
    if (first_occurence == sorted.end())
      mooseError("We must have at least one occurence of the circular node");
    auto second_occurence = std::find(first_occurence + 1, sorted.end(), graph._circular_node);
    if (second_occurence == sorted.end())
      mooseError("We must have two occurences of the circular node");
    _cyclic_graph = std::vector<T>(first_occurence, second_occurence + 1);
  }
CyclicDependencyException() [2/2]
template<class T , class Compare = std::less<T>> CyclicDependencyException< T, Compare >::CyclicDependencyException (const CyclicDependencyException< T, Compare > & e) throw () inline
Definition at line 450 of file DependencyResolver.h.
    : runtime_error(e), _cyclic_graph(e._cyclic_graph)
  {
  }
~CyclicDependencyException()
template<class T , class Compare = std::less<T>> CyclicDependencyException< T, Compare >::~CyclicDependencyException () throw () inline
Definition at line 455 of file DependencyResolver.h.
{}
Member Function Documentation
getCyclicDependencies()
template<class T , class Compare = std::less<T>> const std::vector< T > & CyclicDependencyException< T, Compare >::getCyclicDependencies () const inline
Definition at line 457 of file DependencyResolver.h.
{ return _cyclic_graph; }
Referenced by MeshGeneratorSystem::createAddedMeshGenerators(), MeshGeneratorSystem::createMeshGeneratorOrder(), DependencyResolverInterface::cyclicDependencyError(), and Syntax::getSortedTask().
Member Data Documentation
_cyclic_graph
template<class T , class Compare = std::less<T>> std::vector<T> CyclicDependencyException< T, Compare >::_cyclic_graph private
Definition at line 460 of file DependencyResolver.h.
Referenced by CyclicDependencyException< T, Compare >::CyclicDependencyException(), and CyclicDependencyException< T, Compare >::getCyclicDependencies().
The documentation for this class was generated from the following file:
moose/framework/include/utils/DependencyResolver.h