Zapdos: NeighborCoupleableMooseVariableDependencyIntermediateInterface Class Reference
NeighborCoupleableMooseVariableDependencyIntermediateInterface Class Reference
Intermediate base class that ties together all the interfaces for getting MooseVariables with the MooseVariableDependencyInterface.
#include <NeighborCoupleableMooseVariableDependencyIntermediateInterface.h>
Public Member Functions
NeighborCoupleableMooseVariableDependencyIntermediateInterface (const MooseObject *moose_object, bool nodal, bool neighbor_nodal, bool is_fv=false)
virtual const VariableValue & coupledNeighborValue (const std::string &var_name, unsigned int comp=0) const
std::vector< const VariableValue * > coupledNeighborValues (const std::string &var_name) const
virtual const ADVariableValue & adCoupledNeighborValue (const std::string &var_name, unsigned int comp=0) const
Get the coupled neighbor variable value for var_name with derivative information for automatic differentiation objects.
template<bool is_ad>
const auto & coupledGenericNeighborValue (const std::string &var_name, unsigned int comp=0) const
Retrieve the coupled neighbor variable value whether AD or not.
template<bool is_ad>
const auto & coupledGenericNeighborGradient (const std::string &var_name, unsigned int comp=0) const
Retrieve the coupled neighbor variable gradient whether AD or not.
virtual const ADVariableValue & adCoupledNeighborValueDot (const std::string &var_name, unsigned int comp=0) const
Get the time derivative of the coupled neighbor variable value for var_name with derivative information for automatic differentiation objects.
std::vector< const ADVariableValue * > adCoupledNeighborValues (const std::string &var_name) const
virtual const ADVectorVariableValue & adCoupledVectorNeighborValue (const std::string &var_name, unsigned int comp=0) const
Get the coupled neighbor vector variable value for var_name with derivative information for automatic differentiation objects.
virtual const VariableValue & coupledNeighborValueDot (const std::string &var_name, unsigned int comp=0) const
virtual const VariableValue & coupledNeighborValueDotDu (const std::string &var_name, unsigned int comp=0) const
virtual const VariableValue & coupledNeighborValueOld (const std::string &var_name, unsigned int comp=0) const
virtual const VariableValue & coupledNeighborValueOlder (const std::string &var_name, unsigned int comp=0) const
virtual const VariableGradient & coupledNeighborGradient (const std::string &var_name, unsigned int comp=0) const
virtual std::vector< const VariableGradient * > coupledNeighborGradients (const std::string &var_name) const
virtual const VariableGradient & coupledNeighborGradientOld (const std::string &var_name, unsigned int comp=0) const
virtual const VariableGradient & coupledNeighborGradientOlder (const std::string &var_name, unsigned int comp=0) const
virtual const ADVariableGradient & adCoupledNeighborGradient (const std::string &var_name, unsigned int comp=0) const
Get the coupled neighbor variable gradient for var_name with derivative information for automatic differentiation objects.
virtual const VectorVariableGradient & coupledVectorNeighborGradient (const std::string &var_name, unsigned int comp=0) const
virtual const VectorVariableGradient & coupledVectorNeighborGradientOld (const std::string &var_name, unsigned int comp=0) const
virtual const VectorVariableGradient & coupledVectorNeighborGradientOlder (const std::string &var_name, unsigned int comp=0) const
virtual const ArrayVariableValue & coupledArrayNeighborValue (const std::string &var_name, unsigned int comp=0) const
virtual const ArrayVariableGradient & coupledArrayNeighborGradient (const std::string &var_name, unsigned int comp=0) const
virtual const ArrayVariableGradient & coupledArrayNeighborGradientOld (const std::string &var_name, unsigned int comp=0) const
virtual const ArrayVariableGradient & coupledArrayNeighborGradientOlder (const std::string &var_name, unsigned int comp=0) const
virtual const VariableSecond & coupledNeighborSecond (const std::string &var_name, unsigned int i=0) const
virtual const VariableValue & coupledNeighborDofValues (const std::string &var_name, unsigned int comp=0) const
virtual const VariableValue & coupledNeighborDofValuesOld (const std::string &var_name, unsigned int comp=0) const
virtual const VariableValue & coupledNeighborDofValuesOlder (const std::string &var_name, unsigned int comp=0) const
const std::unordered_map< std::string, std::vector< MooseVariableFieldBase * > > & getCoupledVars () const
Get the list of coupled variables.
const std::vector< MooseVariableFieldBase * > & getCoupledMooseVars () const
Get the list of all coupled variables.
const std::vector< MooseVariable * > & getCoupledStandardMooseVars () const
Get the list of standard coupled variables.
const std::vector< VectorMooseVariable * > & getCoupledVectorMooseVars () const
Get the list of vector coupled variables.
const std::vector< ArrayMooseVariable * > & getCoupledArrayMooseVars () const
Get the list of array coupled variables.
void addFEVariableCoupleableVectorTag (TagID tag)
void addFEVariableCoupleableMatrixTag (TagID tag)
std::set< TagID > & getFEVariableCoupleableVectorTags ()
const std::set< TagID > & getFEVariableCoupleableVectorTags () const
std::set< TagID > & getFEVariableCoupleableMatrixTags ()
const std::set< TagID > & getFEVariableCoupleableMatrixTags () const
auto & getWritableCoupledVariables () const
returns a reference to the set of writable coupled variables
bool hasWritableCoupledVariables () const
Checks whether the object has any writable coupled variables.
const ADVariableValue * getADDefaultValue (const std::string &var_name) const
Helper method to return (and insert if necessary) the default value for Automatic Differentiation for an uncoupled variable.
const ADVectorVariableValue * getADDefaultVectorValue (const std::string &var_name) const
Helper method to return (and insert if necessary) the default vector value for Automatic Differentiation for an uncoupled variable.
const ADVariableGradient & getADDefaultGradient () const
Helper method to return (and insert if necessary) the default gradient for Automatic Differentiation for an uncoupled variable.
const ADVectorVariableGradient & getADDefaultVectorGradient () const
Helper method to return (and insert if necessary) the default gradient for Automatic Differentiation for an uncoupled vector variable.
const ADVariableSecond & getADDefaultSecond () const
Helper method to return (and insert if necessary) the default second derivatives for Automatic Differentiation for an uncoupled variable.
const std::vector< MooseVariableScalar * > & getCoupledMooseScalarVars ()
Get the list of coupled scalar variables.
const std::set< TagID > & getScalarVariableCoupleableVectorTags () const
const std::set< TagID > & getScalarVariableCoupleableMatrixTags () const
const std::set< MooseVariableFieldBase * > & getMooseVariableDependencies () const
Retrieve the set of MooseVariableFieldBase that this object depends on.
template<typename DofObjectType >
std::set< MooseVariableFieldBase * > checkAllVariables (const DofObjectType &dof_object, const std::set< MooseVariableFieldBase * > &vars_to_omit={})
Check whether all of the variable dependencies have degree of freedom indices on the supplied degree of freedom object.
template<typename DofObjectType >
std::set< MooseVariableFieldBase * > checkVariables (const DofObjectType &dof_object, const std::set< MooseVariableFieldBase * > &vars_to_check)
Check whether all of the supplied variables have degree of freedom indices on the supplied degree of freedom object.
Static Public Member Functions
static InputParameters validParams ()
Protected Member Functions
virtual void coupledCallback (const std::string &, bool) const
A call-back function provided by the derived object for actions before coupling a variable with functions such as coupledValue.
virtual bool isCoupled (const std::string &var_name, unsigned int i=0) const
Returns true if a variables has been coupled as name.
virtual bool isCoupledConstant (const std::string &var_name) const
Returns true if a variable passed as a coupled value is really a constant.
unsigned int coupledComponents (const std::string &var_name) const
Number of coupled components.
VariableName coupledName (const std::string &var_name, unsigned int comp=0) const
Names of the variable in the Coupleable interface.
std::vector< VariableName > coupledNames (const std::string &var_name) const
Names of the variables in the Coupleable interface.
virtual unsigned int coupled (const std::string &var_name, unsigned int comp=0) const
Returns the index for a coupled variable by name.
std::vector< unsigned int > coupledIndices (const std::string &var_name) const
Returns the indices for a coupled variable's components.
virtual const VariableValue & coupledValue (const std::string &var_name, unsigned int comp=0) const
Returns value of a coupled variable.
std::vector< const VariableValue * > coupledValues (const std::string &var_name) const
Returns the values for all of a coupled variable components.
std::vector< const VectorVariableValue * > coupledVectorValues (const std::string &var_name) const
Returns the values for all of a coupled vector variable's components.
template<bool is_ad>
const GenericVariableValue< is_ad > & coupledGenericValue (const std::string &var_name, unsigned int comp=0) const
Returns value of a coupled variable for use in templated automatic differentiation classes.
template<>
const GenericVariableValue< false > & coupledGenericValue (const std::string &var_name, unsigned int comp) const
template<>
const GenericVariableValue< true > & coupledGenericValue (const std::string &var_name, unsigned int comp) const
template<bool is_ad>
std::vector< const GenericVariableValue< is_ad > * > coupledGenericValues (const std::string &var_name) const
Returns the values for all of a coupled variable's components for use in templated automatic differentiation classes.
template<>
std::vector< const GenericVariableValue< false > * > coupledGenericValues (const std::string &var_name) const
template<>
std::vector< const GenericVariableValue< true > * > coupledGenericValues (const std::string &var_name) const
template<bool is_ad>
const GenericVariableValue< is_ad > & coupledGenericDofValue (const std::string &var_name, unsigned int comp=0) const
Returns DOF value of a coupled variable for use in templated automatic differentiation classes.
template<>
const GenericVariableValue< false > & coupledGenericDofValue (const std::string &var_name, unsigned int comp) const
template<>
const GenericVariableValue< true > & coupledGenericDofValue (const std::string &var_name, unsigned int comp) const
virtual const VariableValue & coupledValueLower (const std::string &var_name, unsigned int comp=0) const
Returns value of a coupled lower-dimensional variable.
const ADVariableValue & adCoupledValue (const std::string &var_name, unsigned int comp=0) const
Returns value of a coupled variable for use in Automatic Differentiation.
std::vector< const ADVariableValue * > adCoupledValues (const std::string &var_name) const
Returns the values for all of a coupled variable's components for use in Automatic Differentiation.
const ADVariableValue & adCoupledLowerValue (const std::string &var_name, unsigned int comp=0) const
Returns value of a coupled lower-dimensional variable for use in Automatic Differentiation.
const ADVectorVariableValue & adCoupledVectorValue (const std::string &var_name, unsigned int comp=0) const
Returns value of a coupled vector variable for use in Automatic Differentiation.
std::vector< const ADVectorVariableValue * > adCoupledVectorValues (const std::string &var_name) const
Returns the values for all of a coupled vector variable's components for use in Automatic Differentiation.
virtual const VariableValue & coupledVectorTagValue (const std::string &var_names, TagID tag, unsigned int index=0) const
Returns value of a coupled variable for a given tag.
virtual const VariableValue & coupledVectorTagValue (const std::string &var_names, const std::string &tag_name, unsigned int index=0) const
std::vector< const VariableValue * > coupledVectorTagValues (const std::string &var_names, TagID tag) const
Returns the values for all the coupled variables desired for a given tag.
std::vector< const VariableValue * > coupledVectorTagValues (const std::string &var_names, const std::string &tag_name) const
virtual const ArrayVariableValue & coupledVectorTagArrayValue (const std::string &var_names, TagID tag, unsigned int index=0) const
Returns value of a coupled array variable for a given tag.
virtual const ArrayVariableValue & coupledVectorTagArrayValue (const std::string &var_names, const std::string &tag_name, unsigned int index=0) const
std::vector< const ArrayVariableValue * > coupledVectorTagArrayValues (const std::string &var_names, TagID tag) const
Returns the values for all the coupled variables desired for a given tag.
std::vector< const ArrayVariableValue * > coupledVectorTagArrayValues (const std::string &var_names, const std::string &tag_name) const
virtual const VariableGradient & coupledVectorTagGradient (const std::string &var_names, TagID tag, unsigned int index=0) const
Returns gradient of a coupled variable for a given tag.
virtual const VariableGradient & coupledVectorTagGradient (const std::string &var_names, const std::string &tag_name, unsigned int index=0) const
std::vector< const VariableGradient * > coupledVectorTagGradients (const std::string &var_names, TagID tag) const
Returns gradients for all the coupled variables desired for a given tag.
std::vector< const VariableGradient * > coupledVectorTagGradients (const std::string &var_names, const std::string &tag_name) const
virtual const ArrayVariableGradient & coupledVectorTagArrayGradient (const std::string &var_names, TagID tag, unsigned int index=0) const
Returns gradient of a coupled array variable for a given tag.
virtual const ArrayVariableGradient & coupledVectorTagArrayGradient (const std::string &var_names, const std::string &tag_name, unsigned int index=0) const
std::vector< const ArrayVariableGradient * > coupledVectorTagArrayGradients (const std::string &var_names, TagID tag) const
Returns gradients for all the coupled variables desired for a given tag.
std::vector< const ArrayVariableGradient * > coupledVectorTagArrayGradients (const std::string &var_names, const std::string &tag_name) const
virtual const VariableValue & coupledVectorTagDofValue (const std::string &var_name, TagID tag, unsigned int index=0) const
Returns dof value of a coupled variable for a given tag.
virtual const VariableValue & coupledVectorTagDofValue (const std::string &var_names, const std::string &tag_name, unsigned int index=0) const
const ArrayVariableValue & coupledVectorTagArrayDofValue (const std::string &var_name, const std::string &tag_name, unsigned int comp=0) const
Returns evaluations of a tagged vector at the requested variable's degree of freedom indices.
std::vector< const VariableValue * > coupledVectorTagDofValues (const std::string &var_names, TagID tag) const
Returns the dof values for all the coupled variables desired for a given tag.
std::vector< const VariableValue * > coupledVectorTagDofValues (const std::string &var_names, const std::string &tag_name) const
virtual const VariableValue & coupledMatrixTagValue (const std::string &var_names, TagID tag, unsigned int index=0) const
Returns value of a coupled variable for a given tag.
virtual const VariableValue & coupledMatrixTagValue (const std::string &var_names, const std::string &tag_name, unsigned int index=0) const
std::vector< const VariableValue * > coupledMatrixTagValues (const std::string &var_names, TagID tag) const
Returns the diagonal matrix values for all the coupled variables desired for a given tag.
std::vector< const VariableValue * > coupledMatrixTagValues (const std::string &var_names, const std::string &tag_name) const
virtual const VectorVariableValue & coupledVectorValue (const std::string &var_name, unsigned int comp=0) const
Returns value of a coupled vector variable.
virtual const ArrayVariableValue & coupledArrayValue (const std::string &var_name, unsigned int comp=0) const
Returns value of a coupled array variable.
std::vector< const ArrayVariableValue * > coupledArrayValues (const std::string &var_name) const
Returns the values for all of a coupled array variable's components.
MooseWritableVariable & writableVariable (const std::string &var_name, unsigned int comp=0)
Returns a writable MooseVariable object for a nodal or elemental variable.
virtual VariableValue & writableCoupledValue (const std::string &var_name, unsigned int comp=0)
Returns a writable reference to a coupled variable for writing to multiple AuxVariables from a single AuxKernel or a UserObject.
void checkWritableVar (MooseWritableVariable *var)
Checks that the passed in variable is only accessed writable by one object in a given subdomain.
virtual const VariableValue & coupledValueOld (const std::string &var_name, unsigned int comp=0) const
Returns an old value from previous time step of a coupled variable.
std::vector< const VariableValue * > coupledValuesOld (const std::string &var_name) const
Returns the old values for all of a coupled variable's components.
virtual const VariableValue & coupledValueOlder (const std::string &var_name, unsigned int comp=0) const
Returns an old value from two time steps previous of a coupled variable.
std::vector< const VariableValue * > coupledValuesOlder (const std::string &var_name) const
Returns the older values for all of a coupled variable's components.
virtual const VariableValue & coupledValuePreviousNL (const std::string &var_name, unsigned int comp=0) const
Returns value of previous Newton iterate of a coupled variable.
virtual const VectorVariableValue & coupledVectorValueOld (const std::string &var_name, unsigned int comp=0) const
Returns an old value from previous time step of a coupled vector variable.
virtual const VectorVariableValue & coupledVectorValueOlder (const std::string &var_name, unsigned int comp=0) const
Returns an old value from two time steps previous of a coupled vector variable.
virtual const ArrayVariableValue & coupledArrayValueOld (const std::string &var_name, unsigned int comp=0) const
Returns an old value from previous time step of a coupled array variable.
virtual const ArrayVariableValue & coupledArrayValueOlder (const std::string &var_name, unsigned int comp=0) const
Returns an old value from two time steps previous of a coupled array variable.
virtual const VariableGradient & coupledGradient (const std::string &var_name, unsigned int comp=0) const
Returns gradient of a coupled variable.
std::vector< const VariableGradient * > coupledGradients (const std::string &var_name) const
Returns the gradients for all of a coupled variable's components.
const ADVariableGradient & adCoupledGradient (const std::string &var_name, unsigned int comp=0) const
Returns gradient of a coupled variable for use in Automatic Differentiation.
const ADVariableGradient & adCoupledGradientDot (const std::string &var_name, unsigned int comp=0) const
Returns gradient of a coupled variable's time derivative for use in Automatic Differentiation.
std::vector< const ADVariableGradient * > adCoupledGradients (const std::string &var_name) const
Returns the gradients for all of a coupled variable's components for use in Automatic Differentiation.
template<bool is_ad>
const GenericVariableGradient< is_ad > & coupledGenericGradient (const std::string &var_name, unsigned int comp=0) const
Returns gradient of a coupled variable for use in templated automatic differentiation.
template<>
const GenericVariableGradient< false > & coupledGenericGradient (const std::string &var_name, unsigned int comp) const
template<>
const GenericVariableGradient< true > & coupledGenericGradient (const std::string &var_name, unsigned int comp) const
template<bool is_ad>
std::vector< const GenericVariableGradient< is_ad > * > coupledGenericGradients (const std::string &var_name) const
Returns the gradients for all of a coupled variable's components for use in templated automatic differentiation.
template<>
std::vector< const GenericVariableGradient< false > * > coupledGenericGradients (const std::string &var_name) const
template<>
std::vector< const GenericVariableGradient< true > * > coupledGenericGradients (const std::string &var_name) const
const ADVectorVariableGradient & adCoupledVectorGradient (const std::string &var_name, unsigned int comp=0) const
Returns gradient of a coupled vector variable for use in Automatic Differentiation.
const ADVariableSecond & adCoupledSecond (const std::string &var_name, unsigned int comp=0) const
Returns second derivatives of a coupled variable for use in Automatic Differentiation.
const ADVectorVariableSecond & adCoupledVectorSecond (const std::string &var_name, unsigned int comp=0) const
Returns second derivatives of a coupled vector variable for use in Automatic Differentiation.
virtual const VariableGradient & coupledGradientOld (const std::string &var_name, unsigned int comp=0) const
Returns an old gradient from previous time step of a coupled variable.
std::vector< const VariableGradient * > coupledGradientsOld (const std::string &var_name) const
Returns the old gradients for all of a coupled variable's components.
virtual const VariableGradient & coupledGradientOlder (const std::string &var_name, unsigned int comp=0) const
Returns an old gradient from two time steps previous of a coupled variable.
virtual const VariableGradient & coupledGradientPreviousNL (const std::string &var_name, unsigned int comp=0) const
Returns gradient of a coupled variable for previous Newton iterate.
virtual const VariableGradient & coupledGradientDot (const std::string &var_name, unsigned int comp=0) const
Time derivative of the gradient of a coupled variable.
virtual const VariableGradient & coupledGradientDotDot (const std::string &var_name, unsigned int comp=0) const
Second time derivative of the gradient of a coupled variable.
virtual const VectorVariableGradient & coupledVectorGradient (const std::string &var_name, unsigned int comp=0) const
Returns gradient of a coupled vector variable.
virtual const VectorVariableGradient & coupledVectorGradientOld (const std::string &var_name, unsigned int comp=0) const
Returns an old gradient from previous time step of a coupled vector variable.
virtual const VectorVariableGradient & coupledVectorGradientOlder (const std::string &var_name, unsigned int comp=0) const
Returns an old gradient from two time steps previous of a coupled vector variable.
virtual const ArrayVariableGradient & coupledArrayGradient (const std::string &var_name, unsigned int comp=0) const
Returns gradient of a coupled array variable.
virtual const ArrayVariableGradient & coupledArrayGradientOld (const std::string &var_name, unsigned int comp=0) const
Returns an old gradient from previous time step of a coupled array variable.
virtual const ArrayVariableGradient & coupledArrayGradientOlder (const std::string &var_name, unsigned int comp=0) const
Returns an old gradient from two time steps previous of a coupled array variable.
virtual const VectorVariableCurl & coupledCurl (const std::string &var_name, unsigned int comp=0) const
Returns curl of a coupled variable.
virtual const VectorVariableCurl & coupledCurlOld (const std::string &var_name, unsigned int comp=0) const
Returns an old curl from previous time step of a coupled variable.
virtual const VectorVariableCurl & coupledCurlOlder (const std::string &var_name, unsigned int comp=0) const
Returns an old curl from two time steps previous of a coupled variable.
virtual const VariableSecond & coupledSecond (const std::string &var_name, unsigned int comp=0) const
Returns second spatial derivatives of a coupled variable.
virtual const VariableSecond & coupledSecondOld (const std::string &var_name, unsigned int comp=0) const
Returns an old second spatial derivatives from previous time step of a coupled variable.
virtual const VariableSecond & coupledSecondOlder (const std::string &var_name, unsigned int comp=0) const
Returns an old second derivative from two time steps previous of a coupled variable.
virtual const VariableSecond & coupledSecondPreviousNL (const std::string &var_name, unsigned int comp=0) const
Returns second derivative of a coupled variable for the previous Newton iterate.
virtual const VariableValue & coupledDot (const std::string &var_name, unsigned int comp=0) const
Time derivative of a coupled variable.
std::vector< const VariableValue * > coupledDots (const std::string &var_name) const
Returns the time derivatives for all of a coupled variable's components.
virtual const VariableValue & coupledDotDot (const std::string &var_name, unsigned int comp=0) const
Second time derivative of a coupled variable.
virtual const VariableValue & coupledDotOld (const std::string &var_name, unsigned int comp=0) const
Old time derivative of a coupled variable.
virtual const VariableValue & coupledDotDotOld (const std::string &var_name, unsigned int comp=0) const
Old second time derivative of a coupled variable.
const ADVariableValue & adCoupledDot (const std::string &var_name, unsigned int comp=0) const
Time derivative of a coupled variable for ad simulations.
std::vector< const ADVariableValue * > adCoupledDots (const std::string &var_name) const
Returns the time derivatives for all of a coupled variable's components for ad simulations.
const ADVariableValue & adCoupledDotDot (const std::string &var_name, unsigned int comp=0) const
Second time derivative of a coupled variable for ad simulations.
const ADVectorVariableValue & adCoupledVectorDot (const std::string &var_name, unsigned int comp=0) const
Time derivative of a vector coupled variable for ad simulations.
virtual const VectorVariableValue & coupledVectorDot (const std::string &var_name, unsigned int comp=0) const
Time derivative of a coupled vector variable.
virtual const VectorVariableValue & coupledVectorDotDot (const std::string &var_name, unsigned int comp=0) const
Second time derivative of a coupled vector variable.
virtual const VectorVariableValue & coupledVectorDotOld (const std::string &var_name, unsigned int comp=0) const
Old time derivative of a coupled vector variable.
virtual const VectorVariableValue & coupledVectorDotDotOld (const std::string &var_name, unsigned int comp=0) const
Old second time derivative of a coupled vector variable.
virtual const VariableValue & coupledVectorDotDu (const std::string &var_name, unsigned int comp=0) const
Time derivative of a coupled vector variable with respect to the coefficients.
virtual const VariableValue & coupledVectorDotDotDu (const std::string &var_name, unsigned int comp=0) const
Second time derivative of a coupled vector variable with respect to the coefficients.
virtual const ArrayVariableValue & coupledArrayDot (const std::string &var_name, unsigned int comp=0) const
Time derivative of a coupled array variable.
virtual const ArrayVariableValue & coupledArrayDotDot (const std::string &var_name, unsigned int comp=0) const
Second time derivative of a coupled array variable.
virtual const ArrayVariableValue & coupledArrayDotOld (const std::string &var_name, unsigned int comp=0) const
Old time derivative of a coupled array variable.
virtual const ArrayVariableValue & coupledArrayDotDotOld (const std::string &var_name, unsigned int comp=0) const
Old second time derivative of a coupled array variable.
virtual const VariableValue & coupledDotDu (const std::string &var_name, unsigned int comp=0) const
Time derivative of a coupled variable with respect to the coefficients.
virtual const VariableValue & coupledDotDotDu (const std::string &var_name, unsigned int comp=0) const
Second time derivative of a coupled variable with respect to the coefficients.
const VariableValue & coupledArrayDotDu (const std::string &var_name, unsigned int comp=0) const
Time derivative of a coupled array variable with respect to the coefficients.
template<typename T >
const T & coupledNodalValue (const std::string &var_name, unsigned int comp=0) const
Returns nodal values of a coupled variable.
template<typename T >
const Moose::ADType< T >::type & adCoupledNodalValue (const std::string &var_name, unsigned int comp=0) const
Returns AD nodal values of a coupled variable.
template<typename T >
const T & coupledNodalValueOld (const std::string &var_name, unsigned int comp=0) const
Returns an old nodal value from previous time step of a coupled variable.
template<typename T >
const T & coupledNodalValueOlder (const std::string &var_name, unsigned int comp=0) const
Returns an old nodal value from two time steps previous of a coupled variable.
template<typename T >
const T & coupledNodalValuePreviousNL (const std::string &var_name, unsigned int comp=0) const
Returns nodal values of a coupled variable for previous Newton iterate.
template<typename T >
const T & coupledNodalDot (const std::string &var_name, unsigned int comp=0) const
Nodal values of time derivative of a coupled variable.
virtual const VariableValue & coupledNodalDotDot (const std::string &var_name, unsigned int comp=0) const
Nodal values of second time derivative of a coupled variable.
virtual const VariableValue & coupledNodalDotOld (const std::string &var_name, unsigned int comp=0) const
Nodal values of old time derivative of a coupled variable.
virtual const VariableValue & coupledNodalDotDotOld (const std::string &var_name, unsigned int comp=0) const
Nodal values of old second time derivative of a coupled variable.
virtual const VariableValue & coupledDofValues (const std::string &var_name, unsigned int comp=0) const
Returns DoFs in the current solution vector of a coupled variable for the local element.
std::vector< const VariableValue * > coupledAllDofValues (const std::string &var_name) const
Returns DoFs in the current solution vector of all of a coupled variable's components for the local element.
virtual const VariableValue & coupledDofValuesOld (const std::string &var_name, unsigned int comp=0) const
Returns DoFs in the old solution vector of a coupled variable for the local element.
std::vector< const VariableValue * > coupledAllDofValuesOld (const std::string &var_name) const
Returns DoFs in the old solution vector of all of a coupled variable's components for the local element.
virtual const VariableValue & coupledDofValuesOlder (const std::string &var_name, unsigned int comp=0) const
Returns DoFs in the older solution vector of a coupled variable for the local element.
std::vector< const VariableValue * > coupledAllDofValuesOlder (const std::string &var_name) const
Returns DoFs in the older solution vector of all of a coupled variable's components for the local element.
virtual const ArrayVariableValue & coupledArrayDofValues (const std::string &var_name, unsigned int comp=0) const
Returns DoFs in the current solution vector of a coupled array variable for the local element.
virtual const ADVariableValue & adCoupledDofValues (const std::string &var_name, unsigned int comp=0) const
Returns DOF value of a coupled variable for use in Automatic Differentiation.
const ADVariableValue & adZeroValue () const
method that returns _zero to RESIDUAL computing objects and _ad_zero to JACOBIAN computing objects
const ADVariableGradient & adZeroGradient () const
method that returns _grad_zero to RESIDUAL computing objects and _ad_grad_zero to JACOBIAN computing objects
const ADVariableSecond & adZeroSecond () const
Retrieve a zero second for automatic differentiation.
template<bool is_ad>
const GenericVariableValue< is_ad > & genericZeroValue ()
Returns zero value templated with automatic differentiation boolean.
template<>
const GenericVariableValue< false > & genericZeroValue ()
template<>
const GenericVariableValue< true > & genericZeroValue ()
template<bool is_ad>
const GenericVariableGradient< is_ad > & genericZeroGradient ()
Returns zero gradient templated with automatic differentiation boolean.
template<>
const GenericVariableGradient< false > & genericZeroGradient ()
template<>
const GenericVariableGradient< true > & genericZeroGradient ()
template<bool is_ad>
const GenericVariableSecond< is_ad > & genericZeroSecond ()
Returns zero second derivative templated with automatic differentiation boolean.
template<>
const GenericVariableSecond< false > & genericZeroSecond ()
template<>
const GenericVariableSecond< true > & genericZeroSecond ()
bool checkVar (const std::string &var_name, unsigned int comp=0, unsigned int comp_bound=0) const
Check that the right kind of variable is being coupled in.
const MooseVariableFieldBase * getFEVar (const std::string &var_name, unsigned int comp) const
Deprecated method.
const MooseVariableFieldBase * getFieldVar (const std::string &var_name, unsigned int comp) const
MooseVariableFieldBase * getFieldVar (const std::string &var_name, unsigned int comp)
template<typename T >
const T * getVarHelper (const std::string &var_name, unsigned int comp) const
Helper that that be used to retrieve a variable of arbitrary type T.
template<typename T >
T * getVarHelper (const std::string &var_name, unsigned int comp)
Helper that can be used to retrieve a variable of arbitrary type T.
MooseVariable * getVar (const std::string &var_name, unsigned int comp)
Extract pointer to a coupled variable.
const MooseVariable * getVar (const std::string &var_name, unsigned int comp) const
Extract pointer to a coupled variable.
VectorMooseVariable * getVectorVar (const std::string &var_name, unsigned int comp)
Extract pointer to a coupled vector variable.
const VectorMooseVariable * getVectorVar (const std::string &var_name, unsigned int comp) const
Extract pointer to a coupled vector variable.
ArrayMooseVariable * getArrayVar (const std::string &var_name, unsigned int comp)
Extract pointer to a coupled array variable.
const ArrayMooseVariable * getArrayVar (const std::string &var_name, unsigned int comp) const
Extract pointer to a coupled array variable.
void validateExecutionerType (const std::string &name, const std::string &fn_name) const
Checks to make sure that the current Executioner has set "_is_transient" when old/older values are coupled in.
template<typename T , typename Func >
std::vector< T > coupledVectorHelper (const std::string &var_name, const Func &func) const
bool isCoupledScalar (const std::string &var_name, unsigned int i=0) const
Returns true if a variables has been coupled_as name.
unsigned int coupledScalarComponents (const std::string &var_name) const
Return the number of components to the coupled scalar variable.
unsigned int coupledScalar (const std::string &var_name, unsigned int comp=0) const
Returns the index for a scalar coupled variable by name.
Order coupledScalarOrder (const std::string &var_name, unsigned int comp=0) const
Returns the order for a scalar coupled variable by name.
const VariableValue & coupledScalarValue (const std::string &var_name, unsigned int comp=0) const
Returns value of a scalar coupled variable.
const ADVariableValue & adCoupledScalarValue (const std::string &var_name, unsigned int comp=0) const
Returns AD value of a scalar coupled variable.
template<bool is_ad>
const GenericVariableValue< is_ad > & coupledGenericScalarValue (const std::string &var_name, unsigned int comp=0) const
Returns value of a coupled scalar variable for use in templated automatic differentiation classes.
template<>
const GenericVariableValue< false > & coupledGenericScalarValue (const std::string &var_name, unsigned int comp) const
template<>
const GenericVariableValue< true > & coupledGenericScalarValue (const std::string &var_name, unsigned int comp) const
const VariableValue & coupledVectorTagScalarValue (const std::string &var_name, TagID tag, unsigned int comp=0) const
Returns value of a scalar coupled variable.
const VariableValue & coupledMatrixTagScalarValue (const std::string &var_name, TagID tag, unsigned int comp=0) const
Returns value of a scalar coupled variable.
const VariableValue & coupledScalarValueOld (const std::string &var_name, unsigned int comp=0) const
Returns the old (previous time step) value of a scalar coupled variable.
const VariableValue & coupledScalarValueOlder (const std::string &var_name, unsigned int comp=0) const
Returns the older (two time steps previous) value of a scalar coupled variable.
const VariableValue & coupledScalarDot (const std::string &var_name, unsigned int comp=0) const
Returns the time derivative of a scalar coupled variable.
const VariableValue & coupledScalarDotDot (const std::string &var_name, unsigned int comp=0) const
Returns the second time derivative of a scalar coupled variable.
const VariableValue & coupledScalarDotOld (const std::string &var_name, unsigned int comp=0) const
Returns the old time derivative of a scalar coupled variable.
const VariableValue & coupledScalarDotDotOld (const std::string &var_name, unsigned int comp=0) const
Returns the old second time derivative of a scalar coupled variable.
const VariableValue & coupledScalarDotDu (const std::string &var_name, unsigned int comp=0) const
Time derivative of a scalar coupled variable with respect to the coefficients.
const VariableValue & coupledScalarDotDotDu (const std::string &var_name, unsigned int comp=0) const
Second time derivative of a scalar coupled variable with respect to the coefficients.
const MooseVariableScalar * getScalarVar (const std::string &var_name, unsigned int comp) const
Extract pointer to a scalar coupled variable.
void addMooseVariableDependency (MooseVariableFieldBase *var)
Call this function to add the passed in MooseVariableFieldBase as a variable that this object depends on.
void addMooseVariableDependency (const std::vector< MooseVariableFieldBase * > &vars)
Protected Attributes
bool _neighbor_nodal
const InputParameters & _c_parameters
const std::string & _c_name
The name of the object this interface is part of.
const std::string & _c_type
The type of the object this interface is part of.
FEProblemBase & _c_fe_problem
const SystemBase *const _c_sys
Pointer to the system object if the moose object this is an interface for has one.
std::unordered_map< std::string, std::vector< MooseVariableFieldBase * > > _coupled_vars
Coupled vars whose values we provide.
std::vector< MooseVariableFieldBase * > _coupled_moose_vars
Vector of all coupled variables.
std::vector< MooseVariable * > _coupled_standard_moose_vars
Vector of standard coupled variables.
std::vector< VectorMooseVariable * > _coupled_vector_moose_vars
Vector of vector coupled variables.
std::vector< ArrayMooseVariable * > _coupled_array_moose_vars
Vector of array coupled variables.
std::vector< MooseVariableFV< Real > * > _coupled_standard_fv_moose_vars
Vector of standard finite volume coupled variables.
const std::unordered_map< std::string, std::string > & _new_to_deprecated_coupled_vars
map from new to deprecated variable names
bool _c_nodal
True if we provide coupling to nodal values.
bool _c_is_implicit
True if implicit value is required.
const bool _c_allow_element_to_nodal_coupling
THREAD_ID _c_tid
Thread ID of the thread using this object.
std::unordered_map< std::string, std::vector< std::unique_ptr< VariableValue > > > _default_value
Will hold the default value for optional coupled variables.
std::unordered_map< std::string, std::unique_ptr< MooseArray< DualReal > > > _ad_default_value
Will hold the default value for optional coupled variables for automatic differentiation.
std::unordered_map< std::string, std::unique_ptr< VectorVariableValue > > _default_vector_value
Will hold the default value for optional vector coupled variables.
std::unordered_map< std::string, std::unique_ptr< ArrayVariableValue > > _default_array_value
Will hold the default value for optional array coupled variables.
std::unordered_map< std::string, std::unique_ptr< MooseArray< ADRealVectorValue > > > _ad_default_vector_value
Will hold the default value for optional vector coupled variables for automatic differentiation.
VariableValue _default_value_zero
This will always be zero because the default values for optionally coupled variables is always constant and this is used for time derivative info.
VariableGradient _default_gradient
This will always be zero because the default values for optionally coupled variables is always constant.
MooseArray< ADRealVectorValue > _ad_default_gradient
This will always be zero because the default values for optionally coupled variables is always constant.
MooseArray< ADRealTensorValue > _ad_default_vector_gradient
This will always be zero because the default values for optionally coupled vector variables is always constant.
VariableSecond _default_second
This will always be zero because the default values for optionally coupled variables is always constant.
MooseArray< ADRealTensorValue > _ad_default_second
This will always be zero because the default values for optionally coupled variables is always constant.
const VariableValue & _zero
Zero value of a variable.
const VariablePhiValue & _phi_zero
const MooseArray< DualReal > & _ad_zero
const VariableGradient & _grad_zero
Zero gradient of a variable.
const MooseArray< ADRealVectorValue > & _ad_grad_zero
const VariablePhiGradient & _grad_phi_zero
Zero gradient of trial function.
const VariableSecond & _second_zero
Zero second derivative of a variable.
const MooseArray< ADRealTensorValue > & _ad_second_zero
const VariablePhiSecond & _second_phi_zero
Zero second derivative of a test function.
const VectorVariableValue & _vector_zero
Zero value of a vector variable.
const VectorVariableCurl & _vector_curl_zero
Zero value of the curl of a vector variable.
VectorVariableValue _default_vector_value_zero
This will always be zero because the default values for optionally coupled variables is always constant and this is used for time derivative info.
VectorVariableGradient _default_vector_gradient
This will always be zero because the default values for optionally coupled variables is always constant.
VectorVariableCurl _default_vector_curl
This will always be zero because the default values for optionally coupled variables is always constant.
ArrayVariableValue _default_array_value_zero
This will always be zero because the default values for optionally coupled variables is always constant and this is used for time derivative info.
ArrayVariableGradient _default_array_gradient
This will always be zero because the default values for optionally coupled variables is always constant.
ArrayVariableCurl _default_array_curl
This will always be zero because the default values for optionally coupled variables is always constant.
bool _coupleable_neighbor
Whether or not this object is a "neighbor" object: ie all of it's coupled values should be neighbor values.
FEProblemBase & _sc_fe_problem
const THREAD_ID _sc_tid
Thread ID of the thread using this object.
const Real & _real_zero
Scalar zero.
const VariableValue & _scalar_zero
Zero value of a scalar variable.
const Point & _point_zero
Zero point.
Private Types
enum class FuncAge { Curr , Old , Older }
enum class VarType {
Ignore , Gradient , Second , GradientDot ,
Dot
}
Private Member Functions
template<typename T >
const OutputTools< T >::VariableValue & vectorTagValueHelper (const std::string &var_names, TagID tag, unsigned int index=0) const
Generic helper method to get vector tag values based on tag ID.
template<typename T >
const OutputTools< T >::VariableValue & vectorTagValueHelper (const std::string &var_names, const std::string &tag_name, unsigned int index=0) const
Generic helper method to get vector tag values based on tag name.
template<typename T >
const OutputTools< T >::VariableValue & vectorTagDofValueHelper (const std::string &var_name, TagID tag, unsigned int comp=0) const
Generic helper method to get vector tag degree of freedom values based on tag ID.
template<typename T >
const OutputTools< T >::VariableValue & vectorTagDofValueHelper (const std::string &var_name, const std::string &tag_name, unsigned int comp=0) const
Generic helper method to get vector tag degree of freedom values based on tag name.
template<typename T >
void requestStates (const std::string &var_name, const TagName &tag_name, const unsigned int comp)
Method that may request additional solution states from the variable's system depending on the value of tag_name.
void checkFuncType (const std::string var_name, VarType t, FuncAge age) const
const VariableValue * getDefaultValue (const std::string &var_name, unsigned int comp) const
Helper method to return (and insert if necessary) the default value for an uncoupled variable.
const VectorVariableValue * getDefaultVectorValue (const std::string &var_name) const
Helper method to return (and insert if necessary) the default value for an uncoupled vector variable.
const ArrayVariableValue * getDefaultArrayValue (const std::string &var_name) const
Helper method to return (and insert if necessary) the default value for an uncoupled array variable.
template<typename T >
const T & getDefaultNodalValue (const std::string &var_name, unsigned int comp=0) const
Get nodal default value.
template<>
const RealVectorValue & getDefaultNodalValue (const std::string &var_name, unsigned int) const
template<>
const RealEigenVector & getDefaultNodalValue (const std::string &var_name, unsigned int) const
template<typename T >
const Moose::Functor< T > & getDefaultFunctor (const std::string &var_name) const
Private Attributes
unsigned int _coupleable_max_qps
Maximum qps for any element in this system.
std::unordered_map< std::string, std::vector< unsigned int > > _optional_var_index
Unique indices for optionally coupled vars that weren't provided.
std::unordered_map< std::string, std::vector< MooseVariableScalar * > > _c_coupled_scalar_vars
Scalar variables coupled into this object (for error checking)
std::set< TagID > _fe_coupleable_vector_tags
std::set< TagID > _fe_coupleable_matrix_tags
const bool _is_fv
Whether the MooseObject is a finite volume object.
const MooseObject *const _obj
const std::set< std::string > _older_state_tags
vector tag names for which we need to request older solution states from the system
std::vector< std::set< MooseWritableVariable * > > _writable_coupled_variables
keep a set of allocated writable variable references to make sure only one object can obtain them per thread
const InputParameters & _sc_parameters
const std::string & _sc_name
The name of the object this interface is part of.
const bool _sc_is_implicit
True if implicit value is required.
std::unordered_map< std::string, std::vector< MooseVariableScalar * > > _coupled_scalar_vars
Coupled vars whose values we provide.
std::unordered_map< std::string, std::unique_ptr< ADVariableValue > > _dual_default_value
Will hold the default AD value for optional coupled scalar variables.
std::vector< MooseVariableScalar * > _coupled_moose_scalar_vars
Vector of coupled variables.
std::unordered_map< std::string, std::vector< MooseVariableFieldBase * > > _sc_coupled_vars
Field variables coupled into this object (for error checking)
std::set< TagID > _sc_coupleable_vector_tags
The scalar coupleable vector tags.
std::set< TagID > _sc_coupleable_matrix_tags
The scalar coupleable matrix tags.
std::set< MooseVariableFieldBase * > _moose_variable_dependencies
std::vector< libMesh::dof_id_type > _dof_indices
A container for holding dof indices in order to avoid constant memory reallocation.
Detailed Description
Intermediate base class that ties together all the interfaces for getting MooseVariables with the MooseVariableDependencyInterface.
Definition at line 22 of file NeighborCoupleableMooseVariableDependencyIntermediateInterface.h.
Member Enumeration Documentation
FuncAge
enum class Coupleable::FuncAge strong private inherited
Enumerator
Curr
Old
Older
Definition at line 1478 of file Coupleable.h.
  {
    Curr,
    Old,
    Older,
  };
VarType
enum class Coupleable::VarType strong private inherited
Enumerator
Ignore
Gradient
Second
GradientDot
Dot
Definition at line 1485 of file Coupleable.h.
  {
    Ignore,
    Gradient,
    Second,
    GradientDot,
    Dot,
  };
Constructor & Destructor Documentation
NeighborCoupleableMooseVariableDependencyIntermediateInterface()
NeighborCoupleableMooseVariableDependencyIntermediateInterface::NeighborCoupleableMooseVariableDependencyIntermediateInterface (const MooseObject * moose_object, bool nodal, bool neighbor_nodal, bool is_fv = false) inline
Definition at line 30 of file NeighborCoupleableMooseVariableDependencyIntermediateInterface.h.
    : NeighborCoupleable(moose_object, nodal, neighbor_nodal, is_fv),
      ScalarCoupleable(moose_object),
      MooseVariableDependencyInterface(moose_object)
  {
    for (MooseVariableFEBase * coupled_var : getCoupledMooseVars())
      addMooseVariableDependency(coupled_var);
  }
Member Function Documentation
adCoupledDofValues()
const ADVariableValue & Coupleable::adCoupledDofValues (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns DOF value of a coupled variable for use in Automatic Differentiation.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to an ADVariableValue for the DoFs of the coupled variable
Definition at line 1973 of file Coupleable.C.
{
  const auto * var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  if (!var)
    return *getADDefaultValue(var_name);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  if (!_c_is_implicit)
    mooseError("Not implemented");
  if (!_coupleable_neighbor)
    return var->adDofValues();
  return var->adDofValuesNeighbor();
}
Referenced by Coupleable::coupledGenericDofValue().
adCoupledDot()
const ADVariableValue & Coupleable::adCoupledDot (const std::string & var_name, unsigned int comp = 0) const protected inherited
Time derivative of a coupled variable for ad simulations.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the time derivative of the coupled variable
See also
Kernel::dot
Definition at line 2123 of file Coupleable.C.
{
  const auto * var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  if (!var)
    return *getADDefaultValue(var_name);
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (_c_nodal)
    mooseError("Not implemented");
  if (!_coupleable_neighbor)
    return var->adUDot();
  return var->adUDotNeighbor();
}
Referenced by Coupleable::adCoupledDots().
adCoupledDotDot()
const ADVariableValue & Coupleable::adCoupledDotDot (const std::string & var_name, unsigned int comp = 0) const protected inherited
Second time derivative of a coupled variable for ad simulations.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to an ADVariableValue containing the second time derivative of the coupled variable
Definition at line 2140 of file Coupleable.C.
{
  const auto * const var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  if (!var)
    return *getADDefaultValue(var_name);
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (_c_nodal)
    mooseError("Not implemented");
  if (!_coupleable_neighbor)
    return var->adUDotDot();
  return var->adUDotDotNeighbor();
}
adCoupledDots()
std::vector< const ADVariableValue * > Coupleable::adCoupledDots (const std::string & var_name) const protected inherited
Returns the time derivatives for all of a coupled variable's components for ad simulations.
Parameters
var_name Name of coupled variable
Returns
Vector of VariableValue pointers for each component of var_name
Definition at line 2605 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &adCoupledDot(var_name, comp); };
  return coupledVectorHelper<const ADVariableValue *>(var_name, func);
}
adCoupledGradient()
const ADVariableGradient & Coupleable::adCoupledGradient (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns gradient of a coupled variable for use in Automatic Differentiation.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to an ADVariableGradient containing the gradient of the coupled variable
See also
Kernel::gradient
Definition at line 2064 of file Coupleable.C.
{
  const auto * var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  if (!var)
    return getADDefaultGradient();
  checkFuncType(var_name, VarType::Gradient, FuncAge::Curr);
  if (!_c_is_implicit)
    mooseError("Not implemented");
  if (!_coupleable_neighbor)
    return var->adGradSln();
  return var->adGradSlnNeighbor();
}
Referenced by Coupleable::adCoupledGradients(), ADSurfaceCharge::ADSurfaceCharge(), Coupleable::coupledGenericGradient(), EconomouDielectricBC::EconomouDielectricBC(), NeumannCircuitVoltageMoles_KV::NeumannCircuitVoltageMoles_KV(), SecondaryElectronBC::SecondaryElectronBC(), and SecondaryElectronEnergyBC::SecondaryElectronEnergyBC().
adCoupledGradientDot()
const ADVariableGradient & Coupleable::adCoupledGradientDot (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns gradient of a coupled variable's time derivative for use in Automatic Differentiation.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to an ADVariableGradient containing the gradient of the coupled variable's time derivative
Definition at line 2081 of file Coupleable.C.
{
  const auto * var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  if (!var)
    return getADDefaultGradient();
  checkFuncType(var_name, VarType::GradientDot, FuncAge::Curr);
  if (!_c_is_implicit)
    mooseError("Not implemented");
  if (!_coupleable_neighbor)
    return var->adGradSlnDot();
  return var->adGradSlnNeighborDot();
}
adCoupledGradients()
std::vector< const ADVariableGradient * > Coupleable::adCoupledGradients (const std::string & var_name) const protected inherited
Returns the gradients for all of a coupled variable's components for use in Automatic Differentiation.
Parameters
var_name Name of coupled variable
Returns
Vector of ADVariableGradient pointers for each component of var_name
Definition at line 2584 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &adCoupledGradient(var_name, comp); };
  return coupledVectorHelper<const ADVariableGradient *>(var_name, func);
}
adCoupledLowerValue()
const ADVariableValue & Coupleable::adCoupledLowerValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns value of a coupled lower-dimensional variable for use in Automatic Differentiation.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a ADVariableValue for the coupled variable
Definition at line 2046 of file Coupleable.C.
{
  auto var = getVarHelper<MooseVariableFE<Real>>(var_name, comp);
  if (!var)
    return *getADDefaultValue(var_name);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  if (!_c_is_implicit)
    mooseError("adCoupledLowerValue cannot be called in a coupleable neighbor object");
  if (_c_nodal)
    return var->adDofValues();
  else
    return var->adSlnLower();
}
adCoupledNeighborGradient()
const ADVariableGradient & NeighborCoupleable::adCoupledNeighborGradient (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Get the coupled neighbor variable gradient for var_name with derivative information for automatic differentiation objects.
Definition at line 208 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("Nodal variables do not have gradients");
  if (!_c_is_implicit)
    mooseError(
        "adCoupledNeighborGradient returns a data structure with derivatives. Explicit schemes "
        "use old solution data which do not have derivatives so adCoupledNeighborGradient is "
        "not appropriate. Please use coupledNeighborGradient instead");
  const auto * var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  return var->adGradSlnNeighbor();
}
Referenced by NeighborCoupleable::coupledGenericNeighborGradient().
adCoupledNeighborValue()
const ADVariableValue & NeighborCoupleable::adCoupledNeighborValue (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Get the coupled neighbor variable value for var_name with derivative information for automatic differentiation objects.
Definition at line 45 of file NeighborCoupleable.C.
{
  const auto * var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  if (!var)
    return *getADDefaultValue(var_name);
  if (_neighbor_nodal)
    mooseError("adCoupledNeighborValue cannot be used for nodal compute objects at this time");
  if (!_c_is_implicit)
    mooseError("adCoupledNeighborValue returns a data structure with derivatives. Explicit schemes "
               "use old solution data which do not have derivatives so adCoupledNeighborValue is "
               "not appropriate. Please use coupledNeighborValue instead");
  return var->adSlnNeighbor();
}
Referenced by NeighborCoupleable::adCoupledNeighborValues(), and NeighborCoupleable::coupledGenericNeighborValue().
adCoupledNeighborValueDot()
const ADVariableValue & NeighborCoupleable::adCoupledNeighborValueDot (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Get the time derivative of the coupled neighbor variable value for var_name with derivative information for automatic differentiation objects.
Definition at line 63 of file NeighborCoupleable.C.
{
  const auto * var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  if (!_c_is_implicit)
    mooseError(
        "adCoupledNeighborValueDot returns a data structure with derivatives. Explicit schemes "
        "use old solution data which do not have derivatives so adCoupledNeighborValueDot is "
        "not appropriate. Please use coupledNeighborValueDot instead");
  if (_neighbor_nodal)
    mooseError("adCoupledNeighborValueDot cannot be used for nodal compute objects at this time");
  else
    return var->adUDotNeighbor();
}
adCoupledNeighborValues()
std::vector< const ADVariableValue * > NeighborCoupleable::adCoupledNeighborValues (const std::string & var_name) const inherited
Definition at line 80 of file NeighborCoupleable.C.
{
  auto func = [this, &var_name](unsigned int comp)
  { return &adCoupledNeighborValue(var_name, comp); };
  return coupledVectorHelper<const ADVariableValue *>(var_name, func);
}
adCoupledNodalValue()
template<typename T > template const ADRealVectorValue & Coupleable::adCoupledNodalValue< RealVectorValue > (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns AD nodal values of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
Definition at line 2004 of file Coupleable.C.
{
  static const typename Moose::ADType<T>::type zero = 0;
  if (!isCoupled(var_name))
    return zero;
  if (!_c_nodal)
    mooseError("The adCoupledNodalValue method should only be called for nodal computing objects");
  if (_coupleable_neighbor)
    mooseError(
        "The adCoupledNodalValue method shouldn't be called for neighbor computing objects. I "
        "don't even know what that would mean, although maybe someone could explain it to me.");
  if (!_c_is_implicit)
    mooseError("If you're going to use an explicit scheme, then use coupledNodalValue instead of "
               "adCoupledNodalValue");
  const auto * var = getVarHelper<MooseVariableFE<T>>(var_name, comp);
  return var->adNodalValue();
}
adCoupledScalarValue()
const ADVariableValue & ScalarCoupleable::adCoupledScalarValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns AD value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a ADVariableValue for the coupled variable
Definition at line 135 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getADDefaultValue(var_name);
  auto var = getScalarVar(var_name, comp);
  if (_sc_is_implicit)
    return var->adSln();
  else
    mooseError("adCoupledValue for non-implicit calculations is not currently supported. Use "
               "coupledValue instead for non-implicit");
}
Referenced by ScalarCoupleable::coupledGenericScalarValue().
adCoupledSecond()
const ADVariableSecond & Coupleable::adCoupledSecond (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns second derivatives of a coupled variable for use in Automatic Differentiation.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableSecond containing the second derivatives of the coupled variable
Definition at line 2098 of file Coupleable.C.
{
  const auto * var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  if (!var)
    return getADDefaultSecond();
  checkFuncType(var_name, VarType::Second, FuncAge::Curr);
  if (!_c_is_implicit)
    mooseError("Not implemented");
  if (!_coupleable_neighbor)
    return var->adSecondSln();
  else
    return var->adSecondSlnNeighbor();
}
adCoupledValue()
const ADVariableValue & Coupleable::adCoupledValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns value of a coupled variable for use in Automatic Differentiation.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a ADVariableValue for the coupled variable
Definition at line 2026 of file Coupleable.C.
{
  const auto * const var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  if (!var)
    return *getADDefaultValue(var_name);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  if (!_c_is_implicit)
    mooseError("Not implemented");
  if (_c_nodal)
    return var->adDofValues();
  if (!_coupleable_neighbor)
    return var->adSln();
  return var->adSlnNeighbor();
}
Referenced by Coupleable::adCoupledValues(), ADSurfaceCharge::ADSurfaceCharge(), Coupleable::coupledGenericValue(), EconomouDielectricBC::EconomouDielectricBC(), LymberopoulosElectronBC::LymberopoulosElectronBC(), NeumannCircuitVoltageMoles_KV::NeumannCircuitVoltageMoles_KV(), SakiyamaEnergySecondaryElectronBC::SakiyamaEnergySecondaryElectronBC(), SakiyamaSecondaryElectronBC::SakiyamaSecondaryElectronBC(), SecondaryElectronBC::SecondaryElectronBC(), and SecondaryElectronEnergyBC::SecondaryElectronEnergyBC().
adCoupledValues()
std::vector< const ADVariableValue * > Coupleable::adCoupledValues (const std::string & var_name) const protected inherited
Returns the values for all of a coupled variable's components for use in Automatic Differentiation.
Parameters
var_name Name of coupled variable
Returns
Vector of ADVariableValue pointers for each component of var_name
Definition at line 2395 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &adCoupledValue(var_name, comp); };
  return coupledVectorHelper<const ADVariableValue *>(var_name, func);
}
adCoupledVectorDot()
const ADVectorVariableValue & Coupleable::adCoupledVectorDot (const std::string & var_name, unsigned int comp = 0) const protected inherited
Time derivative of a vector coupled variable for ad simulations.
Parameters
var_name Name of vector coupled variable
comp Component number
Returns
Reference to a VectorVariableValue containing the time derivative of the coupled variable
See also
Kernel::dot
Definition at line 2157 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
    return *getADDefaultVectorValue(var_name);
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (_c_nodal)
    mooseError("Not implemented");
  if (!_coupleable_neighbor)
    return var->adUDot();
  return var->adUDotNeighbor();
}
adCoupledVectorGradient()
const ADVectorVariableGradient & Coupleable::adCoupledVectorGradient (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns gradient of a coupled vector variable for use in Automatic Differentiation.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a VectorVariableGradient containing the gradient of the coupled variable
See also
Kernel::gradient
Definition at line 2191 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
    return getADDefaultVectorGradient();
  checkFuncType(var_name, VarType::Gradient, FuncAge::Curr);
  if (!_c_is_implicit)
    mooseError("Not implemented");
  if (!_coupleable_neighbor)
    return var->adGradSln();
  return var->adGradSlnNeighbor();
}
adCoupledVectorNeighborValue()
const ADVectorVariableValue & NeighborCoupleable::adCoupledVectorNeighborValue (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Get the coupled neighbor vector variable value for var_name with derivative information for automatic differentiation objects.
Definition at line 88 of file NeighborCoupleable.C.
{
  auto var = getVarHelper<MooseVariableField<RealVectorValue>>(var_name, comp);
  if (!var)
    return *getADDefaultVectorValue(var_name);
  if (_neighbor_nodal)
    mooseError(
        "adCoupledVectorNeighborValue cannot be used for nodal compute objects at this time");
  if (!_c_is_implicit)
    mooseError(
        "adCoupledVectorNeighborValue returns a data structure with derivatives. Explicit schemes "
        "use old solution data which do not have derivatives so adCoupledVectorNeighborValue is "
        "not appropriate. Please use coupledNeighborValue instead");
  return var->adSlnNeighbor();
}
adCoupledVectorSecond()
const ADVectorVariableSecond & Coupleable::adCoupledVectorSecond (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns second derivatives of a coupled vector variable for use in Automatic Differentiation.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a VectorVariableSecond containing the second derivatives of the coupled variable
adCoupledVectorValue()
const ADVectorVariableValue & Coupleable::adCoupledVectorValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns value of a coupled vector variable for use in Automatic Differentiation.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
See also
Kernel::value
Definition at line 2173 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
    return *getADDefaultVectorValue(var_name);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  if (_c_nodal)
    mooseError("Not implemented");
  if (!_c_is_implicit)
    mooseError("Not implemented");
  if (!_coupleable_neighbor)
    return var->adSln();
  return var->adSlnNeighbor();
}
Referenced by Coupleable::adCoupledVectorValues().
adCoupledVectorValues()
std::vector< const ADVectorVariableValue * > Coupleable::adCoupledVectorValues (const std::string & var_name) const protected inherited
Returns the values for all of a coupled vector variable's components for use in Automatic Differentiation.
Parameters
var_name Name of coupled variable
Returns
Vector of ADVariableValue pointers for each component of var_name
Definition at line 2402 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp)
  { return &adCoupledVectorValue(var_name, comp); };
  return coupledVectorHelper<const ADVectorVariableValue *>(var_name, func);
}
addFEVariableCoupleableMatrixTag()
void Coupleable::addFEVariableCoupleableMatrixTag (TagID tag) inline inherited
Definition at line 103 of file Coupleable.h.
{ _fe_coupleable_matrix_tags.insert(tag); }
Referenced by Coupleable::coupledMatrixTagValue().
addFEVariableCoupleableVectorTag()
void Coupleable::addFEVariableCoupleableVectorTag (TagID tag) inline inherited
Definition at line 101 of file Coupleable.h.
{ _fe_coupleable_vector_tags.insert(tag); }
Referenced by Coupleable::coupledVectorTagArrayGradient(), Coupleable::coupledVectorTagGradient(), Coupleable::vectorTagDofValueHelper(), and Coupleable::vectorTagValueHelper().
addMooseVariableDependency() [1/2]
void MooseVariableDependencyInterface::addMooseVariableDependency (const std::vector< MooseVariableFieldBase * > & vars) inline protected inherited
Definition at line 77 of file MooseVariableDependencyInterface.h.
  {
    _moose_variable_dependencies.insert(vars.begin(), vars.end());
  }
addMooseVariableDependency() [2/2]
void MooseVariableDependencyInterface::addMooseVariableDependency (MooseVariableFieldBase * var) inline protected inherited
Call this function to add the passed in MooseVariableFieldBase as a variable that this object depends on.
Definition at line 73 of file MooseVariableDependencyInterface.h.
  {
    _moose_variable_dependencies.insert(var);
  }
Referenced by ADDGKernel::ADDGKernel(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADInterfaceKernelTempl< T >::ADInterfaceKernelTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayNodalBC::ArrayNodalBC(), AuxNodalScalarKernel::AuxNodalScalarKernel(), CoupleableMooseVariableDependencyIntermediateInterface::CoupleableMooseVariableDependencyIntermediateInterface(), DGKernel::DGKernel(), DiracKernelTempl< T >::DiracKernelTempl(), DomainUserObject::DomainUserObject(), ElemElemConstraint::ElemElemConstraint(), ElementIndicator::ElementIndicator(), ElementIntegralArrayVariablePostprocessor::ElementIntegralArrayVariablePostprocessor(), ElementIntegralVariablePostprocessor::ElementIntegralVariablePostprocessor(), ElementIntegralVariableUserObject::ElementIntegralVariableUserObject(), ElementUserObject::ElementUserObject(), ElementVariablePostprocessor::ElementVariablePostprocessor(), FVBoundaryCondition::FVBoundaryCondition(), FVInterfaceKernel::FVInterfaceKernel(), IntegratedBC::IntegratedBC(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceMaterial::InterfaceMaterial(), InterfaceUserObjectBase::InterfaceUserObjectBase(), InternalSideIndicator::InternalSideIndicator(), InternalSideIntegralVariablePostprocessor::InternalSideIntegralVariablePostprocessor(), InternalSideUserObject::InternalSideUserObject(), Kernel::Kernel(), Marker::Marker(), Material::Material(), MortarConstraintBase::MortarConstraintBase(), NeighborCoupleableMooseVariableDependencyIntermediateInterface(), NodalBC::NodalBC(), NodalConstraint::NodalConstraint(), NodalKernel::NodalKernel(), NodalScalarKernel::NodalScalarKernel(), NodalUserObject::NodalUserObject(), NodeElemConstraint::NodeElemConstraint(), NodeFaceConstraint::NodeFaceConstraint(), PointVariableSamplerBase::PointVariableSamplerBase(), QuadraturePointMarker::QuadraturePointMarker(), SideIntegralVariablePostprocessor::SideIntegralVariablePostprocessor(), SideIntegralVariableUserObject::SideIntegralVariableUserObject(), SideUserObject::SideUserObject(), SideVariablePostprocessor::SideVariablePostprocessor(), VectorIntegratedBC::VectorIntegratedBC(), VectorKernel::VectorKernel(), and VectorNodalBC::VectorNodalBC().
adZeroGradient()
const ADVariableGradient & Coupleable::adZeroGradient () const protected inherited
method that returns _grad_zero to RESIDUAL computing objects and _ad_grad_zero to JACOBIAN computing objects
Definition at line 2266 of file Coupleable.C.
{
  mooseDeprecated("Method adZeroGradient() is deprecated. Use '_ad_grad_zero' instead.");
  return _ad_grad_zero;
}
adZeroSecond()
const ADVariableSecond & Coupleable::adZeroSecond () const protected inherited
Retrieve a zero second for automatic differentiation.
Definition at line 2273 of file Coupleable.C.
{
  mooseDeprecated("Method adZeroSecond() is deprecated. Use '_ad_second_zero' instead.");
  return _ad_second_zero;
}
adZeroValue()
const ADVariableValue & Coupleable::adZeroValue () const protected inherited
method that returns _zero to RESIDUAL computing objects and _ad_zero to JACOBIAN computing objects
Definition at line 2259 of file Coupleable.C.
{
  mooseDeprecated("Method adZeroValue() is deprecated. Use '_ad_zero' instead.");
  return _ad_zero;
}
checkAllVariables()
template<typename DofObjectType > std::set< MooseVariableFieldBase * > MooseVariableDependencyInterface::checkAllVariables (const DofObjectType & dof_object, const std::set< MooseVariableFieldBase * > & vars_to_omit = {}) inherited
Check whether all of the variable dependencies have degree of freedom indices on the supplied degree of freedom object.
Parameters
dof_object The degree of freedom object (an element or node) that we want to check for existence of variable degrees of freedom on
vars_to_omit Variables that we can omit from checking
Returns
Any variables that do not have degrees of freedom on the supplied degree of freedom object
Definition at line 91 of file MooseVariableDependencyInterface.h.
{
  if (vars_to_omit.empty())
    return checkVariables(dof_object, _moose_variable_dependencies);
  std::set<MooseVariableFieldBase *> vars_to_check;
  std::set_difference(_moose_variable_dependencies.begin(),
                      _moose_variable_dependencies.end(),
                      vars_to_omit.begin(),
                      vars_to_omit.end(),
                      std::inserter(vars_to_check, vars_to_check.begin()));
  return checkVariables(dof_object, vars_to_check);
}
checkFuncType()
void Coupleable::checkFuncType (const std::string var_name, VarType t, FuncAge age) const private inherited
Definition at line 186 of file Coupleable.C.
{
  if (t == VarType::Gradient && _c_nodal)
    mooseError(_c_name, ": nodal variables do not have gradients at nodes");
  if (age == FuncAge::Old || age == FuncAge::Older || t == VarType::GradientDot ||
      t == VarType::Dot)
    validateExecutionerType(var_name, "coupled[Vector][Gradient/Dot]Old[er]");
  if (age == FuncAge::Older && !_c_is_implicit)
    mooseError("object '",
               _c_name,
               "' uses older variable values that are unavailable with explicit schemes");
  coupledCallback(var_name, age == FuncAge::Old || age == FuncAge::Older);
}
Referenced by Coupleable::adCoupledDofValues(), Coupleable::adCoupledDot(), Coupleable::adCoupledDotDot(), Coupleable::adCoupledGradient(), Coupleable::adCoupledGradientDot(), Coupleable::adCoupledLowerValue(), Coupleable::adCoupledSecond(), Coupleable::adCoupledValue(), Coupleable::adCoupledVectorDot(), Coupleable::adCoupledVectorGradient(), Coupleable::adCoupledVectorValue(), Coupleable::coupled(), Coupleable::coupledArrayDofValues(), Coupleable::coupledArrayDot(), Coupleable::coupledArrayDotDot(), Coupleable::coupledArrayDotDotOld(), Coupleable::coupledArrayDotDu(), Coupleable::coupledArrayDotOld(), Coupleable::coupledArrayGradient(), Coupleable::coupledArrayGradientOld(), Coupleable::coupledArrayGradientOlder(), Coupleable::coupledArrayValue(), Coupleable::coupledArrayValueOld(), Coupleable::coupledArrayValueOlder(), Coupleable::coupledCurl(), Coupleable::coupledCurlOld(), Coupleable::coupledCurlOlder(), Coupleable::coupledDofValues(), Coupleable::coupledDofValuesOld(), Coupleable::coupledDofValuesOlder(), Coupleable::coupledDot(), Coupleable::coupledDotDot(), Coupleable::coupledDotDotDu(), Coupleable::coupledDotDotOld(), Coupleable::coupledDotDu(), Coupleable::coupledDotOld(), Coupleable::coupledGradient(), Coupleable::coupledGradientDot(), Coupleable::coupledGradientDotDot(), Coupleable::coupledGradientOld(), Coupleable::coupledGradientOlder(), Coupleable::coupledGradientPreviousNL(), Coupleable::coupledMatrixTagValue(), Coupleable::coupledNodalDot(), Coupleable::coupledNodalDotDot(), Coupleable::coupledNodalDotDotOld(), Coupleable::coupledNodalDotOld(), Coupleable::coupledNodalValue(), Coupleable::coupledNodalValueOld(), Coupleable::coupledNodalValueOlder(), Coupleable::coupledNodalValuePreviousNL(), Coupleable::coupledSecond(), Coupleable::coupledSecondOld(), Coupleable::coupledSecondOlder(), Coupleable::coupledSecondPreviousNL(), Coupleable::coupledValue(), Coupleable::coupledValueLower(), Coupleable::coupledValueOld(), Coupleable::coupledValueOlder(), Coupleable::coupledValuePreviousNL(), Coupleable::coupledVectorDot(), Coupleable::coupledVectorDotDot(), Coupleable::coupledVectorDotDotDu(), Coupleable::coupledVectorDotDotOld(), Coupleable::coupledVectorDotDu(), Coupleable::coupledVectorDotOld(), Coupleable::coupledVectorGradient(), Coupleable::coupledVectorGradientOld(), Coupleable::coupledVectorGradientOlder(), Coupleable::coupledVectorTagArrayGradient(), Coupleable::coupledVectorTagGradient(), Coupleable::coupledVectorValue(), Coupleable::coupledVectorValueOld(), Coupleable::coupledVectorValueOlder(), Coupleable::vectorTagDofValueHelper(), and Coupleable::vectorTagValueHelper().
checkVar()
bool Coupleable::checkVar (const std::string & var_name, unsigned int comp = 0, unsigned int comp_bound = 0) const protected inherited
Check that the right kind of variable is being coupled in.
Parameters
var_name The name of the coupled variable
Definition at line 203 of file Coupleable.C.
{
  const auto var_name = _c_parameters.checkForRename(var_name_in);
  auto it = _c_coupled_scalar_vars.find(var_name);
  if (it != _c_coupled_scalar_vars.end())
  {
    std::string cvars;
    for (auto jt : it->second)
      cvars += " " + jt->name();
    _obj->paramError(var_name,
                     "cannot couple '",
                     var_name,
                     "' to a scalar variable (",
                     cvars,
                     ") where field variable is expected");
  }
  if (!isCoupled(var_name, comp))
    return false; // return false since variable is *not* coupled
  auto vars_vector_it = _coupled_vars.find(var_name);
  if (vars_vector_it == _coupled_vars.end())
    mooseError(_c_name, ": Trying to get a coupled var ", var_name, " that doesn't exist");
  const auto & vars_vector = vars_vector_it->second;
  auto bound = comp_bound ? comp_bound : vars_vector.size();
  checkComponent(_obj, comp, bound, var_name);
  // We should know we have a variable now
  const auto * var = vars_vector[comp];
  if (!var)
    mooseError(
        _c_name,
        ": We did all our checks for the existence of a var, yet we still don't have a var!?");
  // Only perform the following checks for objects that feed into residuals/Jacobians, e.g. objects
  // that inherit from the TaggingInterface
  if (_c_parameters.have_parameter<MultiMooseEnum>("vector_tags"))
  {
    // Are we attempting to couple to a non-FV var in an FV object?
    if (!var->isFV() && _is_fv)
      mooseError("Attempting to couple non-FV variable ",
                 var->name(),
                 " into an FV object ",
                 _c_name,
                 ". This is not currently supported");
  }
  if (!(vars_vector[comp])->isNodal() && _c_nodal && !_c_allow_element_to_nodal_coupling)
    mooseError(_c_name, ": cannot couple elemental variables into nodal objects");
  return true;
}
Referenced by Coupleable::getVarHelper().
checkVariables()
template<typename DofObjectType > template std::set< MooseVariableFieldBase * > MooseVariableDependencyInterface::checkVariables (const DofObjectType & dof_object, const std::set< MooseVariableFieldBase * > & vars_to_check) inherited
Check whether all of the supplied variables have degree of freedom indices on the supplied degree of freedom object.
Parameters
dof_object The degree of freedom object (an element or node) that we want to check for existence of variable degrees of freedom on
vars_to_check the variables to check
Returns
Any variables that do not have degrees of freedom on the supplied degree of freedom object
Definition at line 25 of file MooseVariableDependencyInterface.C.
{
  std::set<MooseVariableFieldBase *> vars_without_indices;
  for (auto * const var : vars_to_check)
  {
    var->sys().dofMap().dof_indices(&dof_object, _dof_indices, var->number());
    if (_dof_indices.empty())
      vars_without_indices.insert(var);
  }
  return vars_without_indices;
}
Referenced by MooseVariableDependencyInterface::checkAllVariables().
checkWritableVar()
void Coupleable::checkWritableVar (MooseWritableVariable * var) protected inherited
Checks that the passed in variable is only accessed writable by one object in a given subdomain.
Definition at line 930 of file Coupleable.C.
{
  // check block restrictions for compatibility
  const auto * br = dynamic_cast<const BlockRestrictable *>(this);
  if (!var->hasBlocks(br->blockIDs()))
    mooseError("The variable '",
               var->name(),
               "' must be defined on all blocks '",
               _obj->name(),
               "' is defined on");
  // make sure only one object can access a variable
  for (const auto & ci : _obj->getMooseApp().getInterfaceObjects<Coupleable>())
    if (ci != this && ci->_writable_coupled_variables[_c_tid].count(var))
    {
      // if both this and ci are block restrictable then we check if the block restrictions
      // are not overlapping. If they don't we permit the call.
      const auto * br_other = dynamic_cast<const BlockRestrictable *>(ci);
      if (br && br_other && br->blockRestricted() && br_other->blockRestricted() &&
          !MooseUtils::setsIntersect(br->blockIDs(), br_other->blockIDs()))
        continue;
      mooseError("'",
                 ci->_obj->name(),
                 "' already obtained a writable reference to '",
                 var->name(),
                 "'. Only one object can obtain such a reference per variable and subdomain in a "
                 "simulation.");
    }
  // var is unique across threads, so we could forego having a separate set per thread, but we
  // need quick access to the list of all variables that need to be inserted into the solution
  // vector by a given thread.
  _writable_coupled_variables[_c_tid].insert(var);
}
Referenced by Coupleable::writableCoupledValue(), and Coupleable::writableVariable().
coupled()
unsigned int Coupleable::coupled (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns the index for a coupled variable by name.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Index of coupled variable, if this is an optionally coupled variable that wasn't provided this will return a unique "invalid" index.
Reimplemented in ShapeUserObject< ElementUserObject >, and ShapeUserObject< SideUserObject >.
Definition at line 436 of file Coupleable.C.
{
  const auto * var = getFieldVar(var_name, comp);
  if (!var)
  {
    mooseAssert(_optional_var_index.find(var_name) != _optional_var_index.end(),
                "optional var index for " << var_name << " does not exist!");
    // make sure we don't try to access default var ids that were not provided
    checkComponent(_obj, comp, _optional_var_index.at(var_name).size(), var_name);
    return _optional_var_index.at(var_name)[comp];
  }
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  if (var->kind() == Moose::VAR_NONLINEAR &&
      // are we not an object that feeds into the nonlinear system?
      (!_c_sys || _c_sys->varKind() != Moose::VAR_NONLINEAR ||
       // are we an object that impacts the nonlinear system and this variable is within our
       // nonlinear system?
       var->sys().number() == _c_sys->number()))
    return var->number();
  else
    // Avoid registering coupling to variables outside of our system (e.g. avoid potentially
    // creating bad Jacobians)
    return std::numeric_limits<unsigned int>::max() - var->number();
}
Referenced by Coupleable::coupledIndices(), and KernelBase::KernelBase().
coupledAllDofValues()
std::vector< const VariableValue * > Coupleable::coupledAllDofValues (const std::string & var_name) const protected inherited
Returns DoFs in the current solution vector of all of a coupled variable's components for the local element.
Parameters
var_name Name of coupled variable
Returns
Vector of VariableValue pointers for each component of the coupled variable
Definition at line 1912 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &coupledDofValues(var_name, comp); };
  return coupledVectorHelper<const VariableValue *>(var_name, func);
}
coupledAllDofValuesOld()
std::vector< const VariableValue * > Coupleable::coupledAllDofValuesOld (const std::string & var_name) const protected inherited
Returns DoFs in the old solution vector of all of a coupled variable's components for the local element.
Parameters
var_name Name of coupled variable
Returns
Vector of VariableValue pointers for each compontnet of the coupled variable
Definition at line 1932 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &coupledDofValuesOld(var_name, comp); };
  return coupledVectorHelper<const VariableValue *>(var_name, func);
}
coupledAllDofValuesOlder()
std::vector< const VariableValue * > Coupleable::coupledAllDofValuesOlder (const std::string & var_name) const protected inherited
Returns DoFs in the older solution vector of all of a coupled variable's components for the local element.
Parameters
var_name Name of coupled variable
Returns
Vector of VariableValue pointers for each component of the coupled variable
Definition at line 1952 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp)
  { return &coupledDofValuesOlder(var_name, comp); };
  return coupledVectorHelper<const VariableValue *>(var_name, func);
}
coupledArrayDofValues()
const ArrayVariableValue & Coupleable::coupledArrayDofValues (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns DoFs in the current solution vector of a coupled array variable for the local element.
Parameters
var_name Name of coupled array variable
comp Component number for vector of coupled array variables
Returns
Reference to a VariableValue for the DoFs of the coupled variable
Definition at line 1960 of file Coupleable.C.
{
  const auto * var = getArrayVar(var_name, comp);
  if (!var)
    return *getDefaultArrayValue(var_name);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->dofValues() : var->dofValuesOld();
  return (_c_is_implicit) ? var->dofValuesNeighbor() : var->dofValuesOldNeighbor();
}
coupledArrayDot()
const ArrayVariableValue & Coupleable::coupledArrayDot (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Time derivative of a coupled array variable.
Parameters
var_name Name of coupled array variable
comp Component number for vector of coupled array variables
Returns
Reference to a ArrayVariableValue containing the time derivative of the coupled variable
Definition at line 1300 of file Coupleable.C.
{
  const auto * var = getArrayVar(var_name, comp);
  if (!var)
    return _default_array_value_zero;
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesDot();
    return var->uDot();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesDotNeighbor();
    return var->uDotNeighbor();
  }
}
coupledArrayDotDot()
const ArrayVariableValue & Coupleable::coupledArrayDotDot (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Second time derivative of a coupled array variable.
Parameters
var_name Name of coupled array variable
comp Component number for vector of coupled array variables
Returns
Reference to a ArrayVariableValue containing the time derivative of the coupled variable
Definition at line 1322 of file Coupleable.C.
{
  const auto * var = getArrayVar(var_name, comp);
  if (!var)
    return _default_array_value_zero;
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesDotDot();
    return var->uDotDot();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesDotDotNeighbor();
    return var->uDotDotNeighbor();
  }
}
coupledArrayDotDotOld()
const ArrayVariableValue & Coupleable::coupledArrayDotDotOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Old second time derivative of a coupled array variable.
Parameters
var_name Name of coupled array variable
comp Component number for vector of coupled array variables
Returns
Reference to a ArrayVariableValue containing the time derivative of the coupled variable
Definition at line 1366 of file Coupleable.C.
{
  const auto * var = getArrayVar(var_name, comp);
  if (!var)
    return _default_array_value_zero;
  checkFuncType(var_name, VarType::Dot, FuncAge::Old);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesDotDotOld();
    return var->uDotDotOld();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesDotDotOldNeighbor();
    return var->uDotDotOldNeighbor();
  }
}
coupledArrayDotDu()
const VariableValue & Coupleable::coupledArrayDotDu (const std::string & var_name, unsigned int comp = 0) const protected inherited
Time derivative of a coupled array variable with respect to the coefficients.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a ArrayVariableValue containing the time derivative of the coupled variable
Definition at line 1438 of file Coupleable.C.
{
  const auto * const var = getArrayVar(var_name, comp);
  if (!var)
  {
    _default_value_zero.resize(_coupleable_max_qps, 0);
    return _default_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesDuDotDu();
    return var->duDotDu();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesDuDotDuNeighbor();
    return var->duDotDuNeighbor();
  }
}
coupledArrayDotOld()
const ArrayVariableValue & Coupleable::coupledArrayDotOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Old time derivative of a coupled array variable.
Parameters
var_name Name of coupled array variable
comp Component number for vector of coupled array variables
Returns
Reference to a ArrayVariableValue containing the time derivative of the coupled variable
Definition at line 1344 of file Coupleable.C.
{
  const auto * var = getArrayVar(var_name, comp);
  if (!var)
    return _default_array_value_zero;
  checkFuncType(var_name, VarType::Dot, FuncAge::Old);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesDotOld();
    return var->uDotOld();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesDotOldNeighbor();
    return var->uDotOldNeighbor();
  }
}
coupledArrayGradient()
const ArrayVariableGradient & Coupleable::coupledArrayGradient (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns gradient of a coupled array variable.
Parameters
var_name Name of coupled array variable
comp Component number for vector of coupled array variables
Returns
Reference to a VectorVariableGradient containing the gradient of the coupled array variable
Definition at line 1608 of file Coupleable.C.
{
  const auto * var = getArrayVar(var_name, comp);
  if (!var)
    return _default_array_gradient;
  checkFuncType(var_name, VarType::Gradient, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->gradSln() : var->gradSlnOld();
  return (_c_is_implicit) ? var->gradSlnNeighbor() : var->gradSlnOldNeighbor();
}
coupledArrayGradientOld()
const ArrayVariableGradient & Coupleable::coupledArrayGradientOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old gradient from previous time step of a coupled array variable.
Parameters
var_name Name of coupled array variable
comp Component number for vector of coupled array variables
Returns
Reference to a VectorVariableGradient containing the old gradient of the coupled array variable
Definition at line 1621 of file Coupleable.C.
{
  const auto * var = getArrayVar(var_name, comp);
  if (!var)
    return _default_array_gradient;
  checkFuncType(var_name, VarType::Gradient, FuncAge::Old);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->gradSlnOld() : var->gradSlnOlder();
  return (_c_is_implicit) ? var->gradSlnOldNeighbor() : var->gradSlnOlderNeighbor();
}
coupledArrayGradientOlder()
const ArrayVariableGradient & Coupleable::coupledArrayGradientOlder (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old gradient from two time steps previous of a coupled array variable.
Parameters
var_name Name of coupled array variable
comp Component number for vector of coupled array variables
Returns
Reference to a ArrayVariableGradient containing the older gradient of the coupled array variable
Definition at line 1634 of file Coupleable.C.
{
  const auto * var = getArrayVar(var_name, comp);
  if (!var)
    return _default_array_gradient;
  checkFuncType(var_name, VarType::Gradient, FuncAge::Older);
  if (!_coupleable_neighbor)
    return var->gradSlnOlder();
  return var->gradSlnOlderNeighbor();
}
coupledArrayNeighborGradient()
const ArrayVariableGradient & NeighborCoupleable::coupledArrayNeighborGradient (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 271 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("Gradients are non-sensical with nodal compute objects");
  const auto * var = getArrayVar(var_name, comp);
  return (_c_is_implicit) ? var->gradSlnNeighbor() : var->gradSlnOldNeighbor();
}
coupledArrayNeighborGradientOld()
const ArrayVariableGradient & NeighborCoupleable::coupledArrayNeighborGradientOld (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 282 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("Gradients are non-sensical with nodal compute objects");
  validateExecutionerType(var_name, "coupledArrayNeighborGradientOld");
  const auto * var = getArrayVar(var_name, comp);
  return (_c_is_implicit) ? var->gradSlnOldNeighbor() : var->gradSlnOlderNeighbor();
}
coupledArrayNeighborGradientOlder()
const ArrayVariableGradient & NeighborCoupleable::coupledArrayNeighborGradientOlder (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 294 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("Gradients are non-sensical with nodal compute objects");
  validateExecutionerType(var_name, "coupledArrayNeighborGradientOlder");
  const auto * var = getArrayVar(var_name, comp);
  if (_c_is_implicit)
    return var->gradSlnOlderNeighbor();
  else
    mooseError("Older values not available for explicit schemes");
}
coupledArrayNeighborValue()
const ArrayVariableValue & NeighborCoupleable::coupledArrayNeighborValue (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 261 of file NeighborCoupleable.C.
{
  const auto * var = getArrayVar(var_name, comp);
  if (_neighbor_nodal)
    return (_c_is_implicit) ? var->dofValuesNeighbor() : var->dofValuesOldNeighbor();
  else
    return (_c_is_implicit) ? var->slnNeighbor() : var->slnOldNeighbor();
}
coupledArrayValue()
const ArrayVariableValue & Coupleable::coupledArrayValue (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns value of a coupled array variable.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a ArrayVariableValue for the coupled vector variable
See also
ArrayKernel::_u
Definition at line 829 of file Coupleable.C.
{
  const auto * var = getArrayVar(var_name, comp);
  if (!var)
    return *getDefaultArrayValue(var_name);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return (_c_is_implicit) ? var->dofValues() : var->dofValuesOld();
    return (_c_is_implicit) ? var->sln() : var->slnOld();
  }
  else
  {
    if (_c_nodal)
      return (_c_is_implicit) ? var->dofValuesNeighbor() : var->dofValuesOldNeighbor();
    return (_c_is_implicit) ? var->slnNeighbor() : var->slnOldNeighbor();
  }
}
Referenced by Coupleable::coupledArrayValues().
coupledArrayValueOld()
const ArrayVariableValue & Coupleable::coupledArrayValueOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old value from previous time step of a coupled array variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a ArrayVariableValue containing the old value of the coupled variable
See also
ArrayKernel::_u_old
Definition at line 1060 of file Coupleable.C.
{
  const auto * var = getArrayVar(var_name, comp);
  if (!var)
    return *getDefaultArrayValue(var_name);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Old);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return (_c_is_implicit) ? var->dofValuesOld() : var->dofValuesOlder();
    return (_c_is_implicit) ? var->slnOld() : var->slnOlder();
  }
  else
  {
    if (_c_nodal)
      return (_c_is_implicit) ? var->dofValuesOldNeighbor() : var->dofValuesOlderNeighbor();
    return (_c_is_implicit) ? var->slnOldNeighbor() : var->slnOlderNeighbor();
  }
}
coupledArrayValueOlder()
const ArrayVariableValue & Coupleable::coupledArrayValueOlder (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old value from two time steps previous of a coupled array variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a ArrayVariableValue containing the older value of the coupled variable
See also
ArrayKernel::_u_older
Definition at line 1082 of file Coupleable.C.
{
  const auto * var = getArrayVar(var_name, comp);
  if (!var)
    return *getDefaultArrayValue(var_name);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Older);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesOlder();
    return var->slnOlder();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesOlderNeighbor();
    return var->slnOlderNeighbor();
  }
}
coupledArrayValues()
std::vector< const ArrayVariableValue * > Coupleable::coupledArrayValues (const std::string & var_name) const protected inherited
Returns the values for all of a coupled array variable's components.
Parameters
var_name Name of coupled array variable
Returns
Vector of ArrayVariableValue pointers for each component of var_name
Definition at line 851 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &coupledArrayValue(var_name, comp); };
  return coupledVectorHelper<const ArrayVariableValue *>(var_name, func);
}
coupledCallback()
virtual void Coupleable::coupledCallback (const std::string & , bool) const inline protected virtual inherited
A call-back function provided by the derived object for actions before coupling a variable with functions such as coupledValue.
Reimplemented in AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, and AuxKernelTempl< RealVectorValue >.
Definition at line 134 of file Coupleable.h.
{}
Referenced by Coupleable::checkFuncType().
coupledComponents()
unsigned int Coupleable::coupledComponents (const std::string & var_name) const protected inherited
Number of coupled components.
Parameters
var_name Name of the variable
Returns
number of components this variable has (usually 1)
Definition at line 152 of file Coupleable.C.
{
  const auto var_name = _c_parameters.checkForRename(var_name_in);
  if (isCoupled(var_name))
  {
    mooseAssert(_coupled_vars.find(var_name) != _coupled_vars.end(),
                var_name << " must not actually be coupled!");
    return _coupled_vars.at(var_name).size();
  }
  else
  {
    if (_c_parameters.hasDefaultCoupledValue(var_name))
      return _c_parameters.numberDefaultCoupledValues(var_name);
    else
      return 0;
  }
}
Referenced by ADSurfaceCharge::ADSurfaceCharge(), Coupleable::coupledVectorHelper(), EconomouDielectricBC::EconomouDielectricBC(), KernelBase::KernelBase(), LymberopoulosElectronBC::LymberopoulosElectronBC(), NeumannCircuitVoltageMoles_KV::NeumannCircuitVoltageMoles_KV(), SakiyamaEnergySecondaryElectronBC::SakiyamaEnergySecondaryElectronBC(), SakiyamaSecondaryElectronBC::SakiyamaSecondaryElectronBC(), SecondaryElectronBC::SecondaryElectronBC(), SecondaryElectronEnergyBC::SecondaryElectronEnergyBC(), SideCurrent::SideCurrent(), SpatialAverageBase::SpatialAverageBase(), SpeciesSum::SpeciesSum(), and VariableValueVolumeHistogram::VariableValueVolumeHistogram().
coupledCurl()
const VectorVariableCurl & Coupleable::coupledCurl (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns curl of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VectorVariableCurl containing the curl of the coupled variable
See also
Kernel::_curl_u
Definition at line 1647 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
  {
    _default_vector_curl.resize(_coupleable_max_qps);
    return _default_vector_curl;
  }
  checkFuncType(var_name, VarType::Gradient, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->curlSln() : var->curlSlnOld();
  return (_c_is_implicit) ? var->curlSlnNeighbor() : var->curlSlnOldNeighbor();
}
coupledCurlOld()
const VectorVariableCurl & Coupleable::coupledCurlOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old curl from previous time step of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VectorVariableCurl containing the old curl of the coupled variable
See also
Kernel::_curl_u_old
Definition at line 1663 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
  {
    _default_vector_curl.resize(_coupleable_max_qps);
    return _default_vector_curl;
  }
  checkFuncType(var_name, VarType::Gradient, FuncAge::Old);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->curlSlnOld() : var->curlSlnOlder();
  return (_c_is_implicit) ? var->curlSlnOldNeighbor() : var->curlSlnOlderNeighbor();
}
coupledCurlOlder()
const VectorVariableCurl & Coupleable::coupledCurlOlder (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old curl from two time steps previous of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VectorVariableCurl containing the older curl of the coupled variable
See also
Kernel::_curl_u_older
Definition at line 1679 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
  {
    _default_vector_curl.resize(_coupleable_max_qps);
    return _default_vector_curl;
  }
  checkFuncType(var_name, VarType::Gradient, FuncAge::Older);
  if (!_coupleable_neighbor)
    return var->curlSlnOlder();
  return var->curlSlnOlderNeighbor();
}
coupledDofValues()
const VariableValue & Coupleable::coupledDofValues (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns DoFs in the current solution vector of a coupled variable for the local element.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the DoFs of the coupled variable
Definition at line 1899 of file Coupleable.C.
{
  const auto * var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  if (!var)
    return *getDefaultValue(var_name, comp);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->dofValues() : var->dofValuesOld();
  return (_c_is_implicit) ? var->dofValuesNeighbor() : var->dofValuesOldNeighbor();
}
Referenced by Coupleable::coupledAllDofValues(), and Coupleable::coupledGenericDofValue().
coupledDofValuesOld()
const VariableValue & Coupleable::coupledDofValuesOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns DoFs in the old solution vector of a coupled variable for the local element.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the old DoFs of the coupled variable
Definition at line 1919 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
    return *getDefaultValue(var_name, comp);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Old);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->dofValuesOld() : var->dofValuesOlder();
  return (_c_is_implicit) ? var->dofValuesOldNeighbor() : var->dofValuesOlderNeighbor();
}
Referenced by Coupleable::coupledAllDofValuesOld().
coupledDofValuesOlder()
const VariableValue & Coupleable::coupledDofValuesOlder (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns DoFs in the older solution vector of a coupled variable for the local element.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the older DoFs of the coupled variable
Definition at line 1939 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
    return *getDefaultValue(var_name, comp);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Older);
  if (!_coupleable_neighbor)
    return var->dofValuesOlder();
  return var->dofValuesOlderNeighbor();
}
Referenced by Coupleable::coupledAllDofValuesOlder().
coupledDot()
const VariableValue & Coupleable::coupledDot (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Time derivative of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the time derivative of the coupled variable
Reimplemented in AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, and AuxKernelTempl< RealVectorValue >.
Definition at line 1104 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_value_zero.resize(_coupleable_max_qps, 0);
    return _default_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesDot();
    return var->uDot();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesDotNeighbor();
    return var->uDotNeighbor();
  }
}
Referenced by Coupleable::coupledDots().
coupledDotDot()
const VariableValue & Coupleable::coupledDotDot (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Second time derivative of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the second time derivative of the coupled variable
Definition at line 1129 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_value_zero.resize(_coupleable_max_qps, 0);
    return _default_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesDotDot();
    return var->uDotDot();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesDotDotNeighbor();
    return var->uDotDotNeighbor();
  }
}
coupledDotDotDu()
const VariableValue & Coupleable::coupledDotDotDu (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Second time derivative of a coupled variable with respect to the coefficients.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the time derivative of the coupled variable with respect to the coefficients
Definition at line 1413 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_value_zero.resize(_coupleable_max_qps, 0);
    return _default_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesDuDotDotDu();
    return var->duDotDotDu();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesDuDotDotDuNeighbor();
    return var->duDotDotDuNeighbor();
  }
}
coupledDotDotOld()
const VariableValue & Coupleable::coupledDotDotOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Old second time derivative of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the old second time derivative of the coupled variable
Definition at line 1179 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_value_zero.resize(_coupleable_max_qps, 0);
    return _default_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Old);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesDotDotOld();
    return var->uDotDotOld();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesDotDotOldNeighbor();
    return var->uDotDotOldNeighbor();
  }
}
coupledDotDu()
const VariableValue & Coupleable::coupledDotDu (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Time derivative of a coupled variable with respect to the coefficients.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the time derivative of the coupled variable with respect to the coefficients
Reimplemented in AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, and AuxKernelTempl< RealVectorValue >.
Definition at line 1388 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_value_zero.resize(_coupleable_max_qps, 0);
    return _default_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesDuDotDu();
    return var->duDotDu();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesDuDotDuNeighbor();
    return var->duDotDuNeighbor();
  }
}
Referenced by AuxKernelTempl< ComputeValueType >::coupledDotDu().
coupledDotOld()
const VariableValue & Coupleable::coupledDotOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Old time derivative of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the old time derivative of the coupled variable
Definition at line 1154 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_value_zero.resize(_coupleable_max_qps, 0);
    return _default_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Old);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesDotOld();
    return var->uDotOld();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesDotOldNeighbor();
    return var->uDotOldNeighbor();
  }
}
coupledDots()
std::vector< const VariableValue * > Coupleable::coupledDots (const std::string & var_name) const protected inherited
Returns the time derivatives for all of a coupled variable's components.
Parameters
var_name Name of coupled variable
Returns
Vector of VariableValue pointers for each component of var_name
Definition at line 2598 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &coupledDot(var_name, comp); };
  return coupledVectorHelper<const VariableValue *>(var_name, func);
}
coupledGenericDofValue() [1/3]
template<> const GenericVariableValue< false > & Coupleable::coupledGenericDofValue (const std::string & var_name, unsigned int comp) const protected inherited
Definition at line 568 of file Coupleable.C.
{
  return coupledDofValues(var_name, comp);
}
coupledGenericDofValue() [2/3]
template<> const GenericVariableValue< true > & Coupleable::coupledGenericDofValue (const std::string & var_name, unsigned int comp) const protected inherited
Definition at line 575 of file Coupleable.C.
{
  return adCoupledDofValues(var_name, comp);
}
coupledGenericDofValue() [3/3]
template<bool is_ad> const GenericVariableValue< is_ad > & Coupleable::coupledGenericDofValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns DOF value of a coupled variable for use in templated automatic differentiation classes.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a GenericVariableValue for the coupled variable
coupledGenericGradient() [1/3]
template<> const GenericVariableGradient< false > & Coupleable::coupledGenericGradient (const std::string & var_name, unsigned int comp) const protected inherited
Definition at line 2322 of file Coupleable.C.
{
  return coupledGradient(var_name, comp);
}
coupledGenericGradient() [2/3]
template<> const GenericVariableGradient< true > & Coupleable::coupledGenericGradient (const std::string & var_name, unsigned int comp) const protected inherited
Definition at line 2329 of file Coupleable.C.
{
  return adCoupledGradient(var_name, comp);
}
coupledGenericGradient() [3/3]
template<bool is_ad> const GenericVariableGradient< is_ad > & Coupleable::coupledGenericGradient (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns gradient of a coupled variable for use in templated automatic differentiation.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableGradient containing the gradient of the coupled variable
See also
Kernel::gradient
coupledGenericGradients() [1/3]
template<bool is_ad> std::vector< const GenericVariableGradient< is_ad > * > Coupleable::coupledGenericGradients (const std::string & var_name) const protected inherited
Returns the gradients for all of a coupled variable's components for use in templated automatic differentiation.
Parameters
var_name Name of coupled variable
Returns
Vector of VariableGradient pointers for each component of var_name
coupledGenericGradients() [2/3]
template<> std::vector< const GenericVariableGradient< true > * > Coupleable::coupledGenericGradients (const std::string & var_name) const protected inherited
Definition at line 2562 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &adCoupledGradient(var_name, comp); };
  return coupledVectorHelper<const GenericVariableGradient<true> *>(var_name, func);
}
coupledGenericGradients() [3/3]
template<> std::vector< const GenericVariableGradient< false > * > Coupleable::coupledGenericGradients (const std::string & var_name) const protected inherited
Definition at line 2562 of file Coupleable.C.
{
  return coupledGradients(var_name);
}
coupledGenericNeighborGradient()
template<bool is_ad> const auto & NeighborCoupleable::coupledGenericNeighborGradient (const std::string & var_name, unsigned int comp = 0) const inherited
Retrieve the coupled neighbor variable gradient whether AD or not.
Definition at line 145 of file NeighborCoupleable.h.
{
  if constexpr (is_ad)
    return adCoupledNeighborGradient(var_name, comp);
  else
    return coupledNeighborGradient(var_name, comp);
}
coupledGenericNeighborValue()
template<bool is_ad> const auto & NeighborCoupleable::coupledGenericNeighborValue (const std::string & var_name, unsigned int comp = 0) const inherited
Retrieve the coupled neighbor variable value whether AD or not.
Definition at line 134 of file NeighborCoupleable.h.
{
  if constexpr (is_ad)
    return adCoupledNeighborValue(var_name, comp);
  else
    return coupledNeighborValue(var_name, comp);
}
coupledGenericScalarValue() [1/3]
template<> const GenericVariableValue< false > & ScalarCoupleable::coupledGenericScalarValue (const std::string & var_name, unsigned int comp) const protected inherited
Definition at line 151 of file ScalarCoupleable.C.
{
  return coupledScalarValue(var_name, comp);
}
coupledGenericScalarValue() [2/3]
template<> const GenericVariableValue< true > & ScalarCoupleable::coupledGenericScalarValue (const std::string & var_name, unsigned int comp) const protected inherited
Definition at line 159 of file ScalarCoupleable.C.
{
  return adCoupledScalarValue(var_name, comp);
}
coupledGenericScalarValue() [3/3]
template<bool is_ad> const GenericVariableValue< is_ad > & ScalarCoupleable::coupledGenericScalarValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns value of a coupled scalar variable for use in templated automatic differentiation classes.
Parameters
var_name Name of coupled scalar variable
comp Component number for vector of coupled scalar variables
Returns
Reference to a GenericVariableValue for the coupled scalar variable
coupledGenericValue() [1/3]
template<> const GenericVariableValue< false > & Coupleable::coupledGenericValue (const std::string & var_name, unsigned int comp) const protected inherited
Definition at line 463 of file Coupleable.C.
{
  return coupledValue(var_name, comp);
}
coupledGenericValue() [2/3]
template<> const GenericVariableValue< true > & Coupleable::coupledGenericValue (const std::string & var_name, unsigned int comp) const protected inherited
Definition at line 470 of file Coupleable.C.
{
  return adCoupledValue(var_name, comp);
}
coupledGenericValue() [3/3]
template<bool is_ad> const GenericVariableValue< is_ad > & Coupleable::coupledGenericValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns value of a coupled variable for use in templated automatic differentiation classes.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a GenericVariableValue for the coupled variable
coupledGenericValues() [1/3]
template<bool is_ad> std::vector< const GenericVariableValue< is_ad > * > Coupleable::coupledGenericValues (const std::string & var_name) const protected inherited
Returns the values for all of a coupled variable's components for use in templated automatic differentiation classes.
Parameters
var_name Name of coupled variable
Returns
Vector of GenericVariableValue pointers for each component of var_name
coupledGenericValues() [2/3]
template<> std::vector< const GenericVariableValue< true > * > Coupleable::coupledGenericValues (const std::string & var_name) const protected inherited
Definition at line 2374 of file Coupleable.C.
{
  return adCoupledValues(var_name);
}
coupledGenericValues() [3/3]
template<> std::vector< const GenericVariableValue< false > * > Coupleable::coupledGenericValues (const std::string & var_name) const protected inherited
Definition at line 2374 of file Coupleable.C.
{
  return coupledValues(var_name);
}
coupledGradient()
const VariableGradient & Coupleable::coupledGradient (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns gradient of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableGradient containing the gradient of the coupled variable
See also
Kernel::gradient
Definition at line 1463 of file Coupleable.C.
{
  const auto * const var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  if (!var)
  {
    _default_gradient.resize(_coupleable_max_qps);
    return _default_gradient;
  }
  checkFuncType(var_name, VarType::Gradient, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->gradSln() : var->gradSlnOld();
  return (_c_is_implicit) ? var->gradSlnNeighbor() : var->gradSlnOldNeighbor();
}
Referenced by Coupleable::coupledGenericGradient(), Coupleable::coupledGenericGradients(), NodeElemConstraint::coupledSecondaryGradient(), NodeFaceConstraint::coupledSecondaryGradient(), and SideCurrent::SideCurrent().
coupledGradientDot()
const VariableGradient & Coupleable::coupledGradientDot (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Time derivative of the gradient of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableGradient containing the time derivative of the gradient of a coupled variable
Definition at line 1528 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_gradient.resize(_coupleable_max_qps);
    return _default_gradient;
  }
  checkFuncType(var_name, VarType::GradientDot, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return var->gradSlnDot();
  return var->gradSlnNeighborDot();
}
coupledGradientDotDot()
const VariableGradient & Coupleable::coupledGradientDotDot (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Second time derivative of the gradient of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableGradient containing the time derivative of the gradient of a coupled variable
Definition at line 1544 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_gradient.resize(_coupleable_max_qps);
    return _default_gradient;
  }
  checkFuncType(var_name, VarType::GradientDot, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return var->gradSlnDotDot();
  return var->gradSlnNeighborDotDot();
}
coupledGradientOld()
const VariableGradient & Coupleable::coupledGradientOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old gradient from previous time step of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableGradient containing the old gradient of the coupled variable
See also
Kernel::gradientOld
Definition at line 1479 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_gradient.resize(_coupleable_max_qps);
    return _default_gradient;
  }
  checkFuncType(var_name, VarType::Gradient, FuncAge::Old);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->gradSlnOld() : var->gradSlnOlder();
  return (_c_is_implicit) ? var->gradSlnOldNeighbor() : var->gradSlnOlderNeighbor();
}
Referenced by Coupleable::coupledGradientsOld(), NodeElemConstraint::coupledSecondaryGradientOld(), and NodeFaceConstraint::coupledSecondaryGradientOld().
coupledGradientOlder()
const VariableGradient & Coupleable::coupledGradientOlder (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old gradient from two time steps previous of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableGradient containing the older gradient of the coupled variable
See also
Kernel::gradientOlder
Definition at line 1495 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_gradient.resize(_coupleable_max_qps);
    return _default_gradient;
  }
  checkFuncType(var_name, VarType::Gradient, FuncAge::Older);
  if (!_coupleable_neighbor)
    return var->gradSlnOlder();
  return var->gradSlnOlderNeighbor();
}
Referenced by NodeElemConstraint::coupledSecondaryGradientOlder(), and NodeFaceConstraint::coupledSecondaryGradientOlder().
coupledGradientPreviousNL()
const VariableGradient & Coupleable::coupledGradientPreviousNL (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns gradient of a coupled variable for previous Newton iterate.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableGradient containing the gradient of the coupled variable
Definition at line 1511 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  _c_fe_problem.needsPreviousNewtonIteration(true);
  if (!var)
  {
    _default_gradient.resize(_coupleable_max_qps);
    return _default_gradient;
  }
  checkFuncType(var_name, VarType::Gradient, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return var->gradSlnPreviousNL();
  return var->gradSlnPreviousNLNeighbor();
}
coupledGradients()
std::vector< const VariableGradient * > Coupleable::coupledGradients (const std::string & var_name) const protected inherited
Returns the gradients for all of a coupled variable's components.
Parameters
var_name Name of coupled variable
Returns
Vector of VariableGradient pointers for each component of var_name
Definition at line 2562 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &coupledGradient(var_name, comp); };
  return coupledVectorHelper<const VariableGradient *>(var_name, func);
}
coupledGradientsOld()
std::vector< const VariableGradient * > Coupleable::coupledGradientsOld (const std::string & var_name) const protected inherited
Returns the old gradients for all of a coupled variable's components.
Parameters
var_name Name of coupled variable
Returns
Vector of VariableGradient pointers for each component of var_name
Definition at line 2591 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &coupledGradientOld(var_name, comp); };
  return coupledVectorHelper<const VariableGradient *>(var_name, func);
}
coupledIndices()
std::vector< unsigned int > Coupleable::coupledIndices (const std::string & var_name) const protected inherited
Returns the indices for a coupled variable's components.
Parameters
var_name Name of coupled variable
Returns
Vector of the indices for all components of the coupled variable var_name.
Definition at line 2336 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return coupled(var_name, comp); };
  return coupledVectorHelper<unsigned int>(var_name, func);
}
coupledMatrixTagScalarValue()
const VariableValue & ScalarCoupleable::coupledMatrixTagScalarValue (const std::string & var_name, TagID tag, unsigned int comp = 0) const protected inherited
Returns value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
tag Tag ID of coupled matrix;
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
Definition at line 202 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  _sc_coupleable_matrix_tags.insert(tag);
  return getScalarVar(var_name, comp)->matrixTagSln(tag);
}
coupledMatrixTagValue() [1/2]
const VariableValue & Coupleable::coupledMatrixTagValue (const std::string & var_names, const std::string & tag_name, unsigned int index = 0) const protected virtual inherited
Definition at line 788 of file Coupleable.C.
{
  if (!_c_parameters.isParamValid(tag_name))
    mooseError("Tag name parameter '", tag_name, "' is invalid");
  TagName tagname = _c_parameters.get<TagName>(tag_name);
  if (!_c_fe_problem.matrixTagExists(tagname))
    mooseError("Matrix tag name '", tagname, "' does not exist");
  TagID tag = _c_fe_problem.getMatrixTagID(tagname);
  return coupledMatrixTagValue(var_names, tag, index);
}
coupledMatrixTagValue() [2/2]
const VariableValue & Coupleable::coupledMatrixTagValue (const std::string & var_names, TagID tag, unsigned int index = 0) const protected virtual inherited
Returns value of a coupled variable for a given tag.
This couples the diag vector of matrix
Parameters
var_names Name(s) of coupled variable(s)
tag matrix tag ID
index Index of the desired variable in the vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
See also
Kernel::_u
Definition at line 771 of file Coupleable.C.
{
  const auto * var = getVar(var_names, index);
  if (!var)
    mooseError(var_names, ": invalid variable name for coupledMatrixTagValue");
  checkFuncType(var_names, VarType::Ignore, FuncAge::Curr);
  const_cast<Coupleable *>(this)->addFEVariableCoupleableMatrixTag(tag);
  if (_c_nodal)
    return var->nodalMatrixTagValue(tag);
  return var->matrixTagValue(tag);
}
Referenced by Coupleable::coupledMatrixTagValue(), and Coupleable::coupledMatrixTagValues().
coupledMatrixTagValues() [1/2]
std::vector< const VariableValue * > Coupleable::coupledMatrixTagValues (const std::string & var_names, const std::string & tag_name) const protected inherited
Definition at line 2533 of file Coupleable.C.
{
  if (!_c_parameters.isParamValid(tag_name))
    mooseError("Tag name parameter '", tag_name, "' is invalid");
  TagName tagname = _c_parameters.get<TagName>(tag_name);
  if (!_c_fe_problem.matrixTagExists(tagname))
    mooseError("Matrix tag name '", tagname, "' does not exist");
  TagID tag = _c_fe_problem.getMatrixTagID(tagname);
  return coupledMatrixTagValues(var_names, tag);
}
coupledMatrixTagValues() [2/2]
std::vector< const VariableValue * > Coupleable::coupledMatrixTagValues (const std::string & var_names, TagID tag) const protected inherited
Returns the diagonal matrix values for all the coupled variables desired for a given tag.
Parameters
var_names Name(s) of coupled variable(s)
tag matrix tag ID
Returns
Vector of VariableValue pointers for each variable in var_name
Definition at line 2525 of file Coupleable.C.
{
  auto func = [this, &var_names, &tag](unsigned int comp)
  { return &coupledMatrixTagValue(var_names, tag, comp); };
  return coupledVectorHelper<const VariableValue *>(var_names, func);
}
Referenced by Coupleable::coupledMatrixTagValues().
coupledName()
VariableName Coupleable::coupledName (const std::string & var_name, unsigned int comp = 0) const protected inherited
Names of the variable in the Coupleable interface.
Parameters
var_name Name of the variable
comp the component of the variable
Returns
name the variable has been coupled as. For constants, returns the constant
Definition at line 2343 of file Coupleable.C.
{
  if (getFieldVar(var_name, comp))
    return getFieldVar(var_name, comp)->name();
  // Detect if we are in the case where a constant was passed in lieu of a variable
  else if (isCoupledConstant(var_name))
    mooseError(_c_name,
               ": a variable name was queried but a constant was passed for parameter '",
               var_name,
               "Either pass a true variable or contact a developer to shield the call to "
               "'coupledName' with 'isCoupledConstant'");
  else
    mooseError(
        _c_name, ": Variable '", var_name, "' does not exist, yet its coupled name is requested");
}
Referenced by Coupleable::coupledNames(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), and SpatialAverageBase::SpatialAverageBase().
coupledNames()
std::vector< VariableName > Coupleable::coupledNames (const std::string & var_name) const protected inherited
Names of the variables in the Coupleable interface.
Parameters
var_name Names of the variables
Returns
names the variables have been coupled as
Definition at line 2360 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return coupledName(var_name, comp); };
  return coupledVectorHelper<VariableName>(var_name, func);
}
coupledNeighborDofValues()
const VariableValue & NeighborCoupleable::coupledNeighborDofValues (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 319 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("nodal objects should not call coupledDofValues");
  const auto * var = getVar(var_name, comp);
  return (_c_is_implicit) ? var->dofValuesNeighbor() : var->dofValuesOldNeighbor();
}
coupledNeighborDofValuesOld()
const VariableValue & NeighborCoupleable::coupledNeighborDofValuesOld (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 329 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("nodal objects should not call coupledDofValuesOld");
  validateExecutionerType(var_name, "coupledNeighborDofValuesOld");
  const auto * var = getVar(var_name, comp);
  return (_c_is_implicit) ? var->dofValuesOldNeighbor() : var->dofValuesOlderNeighbor();
}
coupledNeighborDofValuesOlder()
const VariableValue & NeighborCoupleable::coupledNeighborDofValuesOlder (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 341 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("nodal objects should not call coupledDofValuesOlder");
  validateExecutionerType(var_name, "coupledNeighborDofValuesOlder");
  const auto * var = getVar(var_name, comp);
  if (_c_is_implicit)
    return var->dofValuesOlderNeighbor();
  else
    mooseError("Older values not available for explicit schemes");
}
coupledNeighborGradient()
const VariableGradient & NeighborCoupleable::coupledNeighborGradient (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 163 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("Nodal variables do not have gradients");
  const auto * var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  return (_c_is_implicit) ? var->gradSlnNeighbor() : var->gradSlnOldNeighbor();
}
Referenced by NeighborCoupleable::coupledGenericNeighborGradient(), NeighborCoupleable::coupledNeighborGradients(), NodeElemConstraint::coupledPrimaryGradient(), and NodeFaceConstraint::coupledPrimaryGradient().
coupledNeighborGradientOld()
const VariableGradient & NeighborCoupleable::coupledNeighborGradientOld (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 181 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("Nodal variables do not have gradients");
  validateExecutionerType(var_name, "coupledNeighborGradientOld");
  const auto * var = getVar(var_name, comp);
  return (_c_is_implicit) ? var->gradSlnOldNeighbor() : var->gradSlnOlderNeighbor();
}
Referenced by NodeElemConstraint::coupledPrimaryGradientOld(), and NodeFaceConstraint::coupledPrimaryGradientOld().
coupledNeighborGradientOlder()
const VariableGradient & NeighborCoupleable::coupledNeighborGradientOlder (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 193 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("Nodal variables do not have gradients");
  validateExecutionerType(var_name, "coupledNeighborGradientOlder");
  const auto * var = getVar(var_name, comp);
  if (_c_is_implicit)
    return var->gradSlnOlderNeighbor();
  else
    mooseError("Older values not available for explicit schemes");
}
Referenced by NodeElemConstraint::coupledPrimaryGradientOlder(), and NodeFaceConstraint::coupledPrimaryGradientOlder().
coupledNeighborGradients()
std::vector< const VariableGradient * > NeighborCoupleable::coupledNeighborGradients (const std::string & var_name) const virtual inherited
Definition at line 173 of file NeighborCoupleable.C.
{
  auto func = [this, &var_name](unsigned int comp)
  { return &coupledNeighborGradient(var_name, comp); };
  return coupledVectorHelper<const VariableGradient *>(var_name, func);
}
coupledNeighborSecond()
const VariableSecond & NeighborCoupleable::coupledNeighborSecond (const std::string & var_name, unsigned int i = 0) const virtual inherited
Definition at line 309 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("Nodal variables do not have second derivatives");
  const auto * var = getVar(var_name, comp);
  return (_c_is_implicit) ? var->secondSlnNeighbor() : var->secondSlnOldNeighbor();
}
Referenced by NodeElemConstraint::coupledPrimarySecond(), and NodeFaceConstraint::coupledPrimarySecond().
coupledNeighborValue()
const VariableValue & NeighborCoupleable::coupledNeighborValue (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 27 of file NeighborCoupleable.C.
{
  const auto * var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  if (_neighbor_nodal)
    return (_c_is_implicit) ? var->dofValuesNeighbor() : var->dofValuesOldNeighbor();
  else
    return (_c_is_implicit) ? var->slnNeighbor() : var->slnOldNeighbor();
}
Referenced by NeighborCoupleable::coupledGenericNeighborValue(), NeighborCoupleable::coupledNeighborValues(), NodeElemConstraint::coupledPrimaryValue(), and NodeFaceConstraint::coupledPrimaryValue().
coupledNeighborValueDot()
const VariableValue & NeighborCoupleable::coupledNeighborValueDot (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 109 of file NeighborCoupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (_neighbor_nodal)
    return var->dofValuesDotNeighbor();
  else
    return var->uDotNeighbor();
}
coupledNeighborValueDotDu()
const VariableValue & NeighborCoupleable::coupledNeighborValueDotDu (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 119 of file NeighborCoupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (_neighbor_nodal)
    return var->dofValuesDuDotDuNeighbor();
  else
    return var->duDotDuNeighbor();
}
coupledNeighborValueOld()
const VariableValue & NeighborCoupleable::coupledNeighborValueOld (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 129 of file NeighborCoupleable.C.
{
  validateExecutionerType(var_name, "coupledNeighborValueOld");
  const auto * var = getVar(var_name, comp);
  if (_neighbor_nodal)
    return (_c_is_implicit) ? var->dofValuesOldNeighbor() : var->dofValuesOlderNeighbor();
  else
    return (_c_is_implicit) ? var->slnOldNeighbor() : var->slnOlderNeighbor();
}
Referenced by NodeElemConstraint::coupledPrimaryValueOld(), and NodeFaceConstraint::coupledPrimaryValueOld().
coupledNeighborValueOlder()
const VariableValue & NeighborCoupleable::coupledNeighborValueOlder (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 141 of file NeighborCoupleable.C.
{
  validateExecutionerType(var_name, "coupledNeighborValueOlder");
  const auto * var = getVar(var_name, comp);
  if (_neighbor_nodal)
  {
    if (_c_is_implicit)
      return var->dofValuesOlderNeighbor();
    else
      mooseError("Older values not available for explicit schemes");
  }
  else
  {
    if (_c_is_implicit)
      return var->slnOlderNeighbor();
    else
      mooseError("Older values not available for explicit schemes");
  }
}
Referenced by NodeElemConstraint::coupledPrimaryValueOlder(), and NodeFaceConstraint::coupledPrimaryValueOlder().
coupledNeighborValues()
std::vector< const VariableValue * > NeighborCoupleable::coupledNeighborValues (const std::string & var_name) const inherited
Definition at line 37 of file NeighborCoupleable.C.
{
  auto func = [this, &var_name](unsigned int comp)
  { return &coupledNeighborValue(var_name, comp); };
  return coupledVectorHelper<const VariableValue *>(var_name, func);
}
coupledNodalDot()
template<typename T > template const RealVectorValue & Coupleable::coupledNodalDot< RealVectorValue > (const std::string & var_name, unsigned int comp = 0) const protected inherited
Nodal values of time derivative of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the nodal values of time derivative of the coupled variable
Definition at line 1837 of file Coupleable.C.
{
  static const T zero = 0;
  const auto * var = getVarHelper<MooseVariableFE<T>>(var_name, comp);
  if (!var)
    return zero;
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return var->nodalValueDot();
  mooseError("Neighbor version not implemented");
}
coupledNodalDotDot()
const VariableValue & Coupleable::coupledNodalDotDot (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Nodal values of second time derivative of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the nodal values of second time derivative of the coupled variable
Definition at line 1851 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_value_zero.resize(_coupleable_max_qps, 0);
    return _default_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return var->dofValuesDotDot();
  return var->dofValuesDotDotNeighbor();
}
coupledNodalDotDotOld()
const VariableValue & Coupleable::coupledNodalDotDotOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Nodal values of old second time derivative of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the nodal values of second time derivative of the coupled variable
Definition at line 1883 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_value_zero.resize(_coupleable_max_qps, 0);
    return _default_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Old);
  if (!_coupleable_neighbor)
    return var->dofValuesDotDotOld();
  return var->dofValuesDotDotOldNeighbor();
}
coupledNodalDotOld()
const VariableValue & Coupleable::coupledNodalDotOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Nodal values of old time derivative of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the nodal values of time derivative of the coupled variable
Definition at line 1867 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_value_zero.resize(_coupleable_max_qps, 0);
    return _default_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Old);
  if (!_coupleable_neighbor)
    return var->dofValuesDotOld();
  return var->dofValuesDotOldNeighbor();
}
coupledNodalValue()
template<typename T > template const RealVectorValue & Coupleable::coupledNodalValue< RealVectorValue > (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns nodal values of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
Definition at line 1761 of file Coupleable.C.
{
  const auto * var = getVarHelper<MooseVariableFE<T>>(var_name, comp);
  if (!var)
    return getDefaultNodalValue<T>(var_name, comp);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  if (!var->isNodal())
    mooseError(_c_name,
               ": Trying to get nodal values of variable '",
               var->name(),
               "', but it is not nodal.");
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->nodalValue() : var->nodalValueOld();
  return (_c_is_implicit) ? var->nodalValueNeighbor() : var->nodalValueOldNeighbor();
}
coupledNodalValueOld()
template<typename T > template const RealVectorValue & Coupleable::coupledNodalValueOld< RealVectorValue > (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns an old nodal value from previous time step of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the old value of the coupled variable
Definition at line 1781 of file Coupleable.C.
{
  const auto * var = getVarHelper<MooseVariableFE<T>>(var_name, comp);
  if (!var)
    return getDefaultNodalValue<T>(var_name, comp);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Old);
  if (!var->isNodal())
    mooseError(_c_name,
               ": Trying to get old nodal values of variable '",
               var->name(),
               "', but it is not nodal.");
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->nodalValueOld() : var->nodalValueOlder();
  return (_c_is_implicit) ? var->nodalValueOldNeighbor() : var->nodalValueOlderNeighbor();
}
coupledNodalValueOlder()
template<typename T > template const RealVectorValue & Coupleable::coupledNodalValueOlder< RealVectorValue > (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns an old nodal value from two time steps previous of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the older value of the coupled variable
Definition at line 1801 of file Coupleable.C.
{
  const auto * var = getVarHelper<MooseVariableFE<T>>(var_name, comp);
  if (!var)
    return getDefaultNodalValue<T>(var_name, comp);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Older);
  if (!var->isNodal())
    mooseError(_c_name,
               ": Trying to get older nodal values of variable '",
               var->name(),
               "', but it is not nodal.");
  if (!_coupleable_neighbor)
    return var->nodalValueOlder();
  return var->nodalValueOlderNeighbor();
}
coupledNodalValuePreviousNL()
template<typename T > template const RealVectorValue & Coupleable::coupledNodalValuePreviousNL< RealVectorValue > (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns nodal values of a coupled variable for previous Newton iterate.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
Definition at line 1821 of file Coupleable.C.
{
  const auto * var = getVarHelper<MooseVariableFE<T>>(var_name, comp);
  if (!var)
    return getDefaultNodalValue<T>(var_name, comp);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  _c_fe_problem.needsPreviousNewtonIteration(true);
  if (!_coupleable_neighbor)
    return var->nodalValuePreviousNL();
  return var->nodalValuePreviousNLNeighbor();
}
coupledScalar()
unsigned int ScalarCoupleable::coupledScalar (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the index for a scalar coupled variable by name.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Index of coupled variable
Definition at line 93 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  return getScalarVar(var_name, comp)->number();
}
Referenced by ParsedODEKernel::ParsedODEKernel().
coupledScalarComponents()
unsigned int ScalarCoupleable::coupledScalarComponents (const std::string & var_name) const protected inherited
Return the number of components to the coupled scalar variable.
Parameters
var_name The of the coupled variable
Definition at line 343 of file ScalarCoupleable.C.
{
  const auto var_name = _sc_parameters.checkForRename(var_name_in);
  const auto it = _coupled_scalar_vars.find(var_name);
  if (it != _coupled_scalar_vars.end())
    return it->second.size();
  mooseError(_sc_name, ": Trying to get a non-existent variable '", var_name, "'");
}
coupledScalarDot()
const VariableValue & ScalarCoupleable::coupledScalarDot (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the time derivative of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a time derivative VariableValue for the coupled variable
Definition at line 243 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDot");
  return getScalarVar(var_name, comp)->uDot();
}
coupledScalarDotDot()
const VariableValue & ScalarCoupleable::coupledScalarDotDot (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the second time derivative of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a time derivative VariableValue for the coupled variable
Definition at line 251 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotDot");
  return getScalarVar(var_name, comp)->uDotDot();
}
coupledScalarDotDotDu()
const VariableValue & ScalarCoupleable::coupledScalarDotDotDu (const std::string & var_name, unsigned int comp = 0) const protected inherited
Second time derivative of a scalar coupled variable with respect to the coefficients.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the time derivative of the coupled variable with respect to the coefficients
Definition at line 282 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotDotDu");
  return getScalarVar(var_name, comp)->duDotDotDu();
}
coupledScalarDotDotOld()
const VariableValue & ScalarCoupleable::coupledScalarDotDotOld (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the old second time derivative of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a time derivative VariableValue for the coupled variable
Definition at line 267 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotDotOld");
  return getScalarVar(var_name, comp)->uDotDotOld();
}
coupledScalarDotDu()
const VariableValue & ScalarCoupleable::coupledScalarDotDu (const std::string & var_name, unsigned int comp = 0) const protected inherited
Time derivative of a scalar coupled variable with respect to the coefficients.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the time derivative of the coupled variable with respect to the coefficients
Definition at line 274 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotDu");
  return getScalarVar(var_name, comp)->duDotDu();
}
coupledScalarDotOld()
const VariableValue & ScalarCoupleable::coupledScalarDotOld (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the old time derivative of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a time derivative VariableValue for the coupled variable
Definition at line 259 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotOld");
  return getScalarVar(var_name, comp)->uDotOld();
}
coupledScalarOrder()
Order ScalarCoupleable::coupledScalarOrder (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the order for a scalar coupled variable by name.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Order of coupled variable
Definition at line 100 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return _sc_fe_problem.getMaxScalarOrder();
  return getScalarVar(var_name, comp)->order();
}
coupledScalarValue()
const VariableValue & ScalarCoupleable::coupledScalarValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
Definition at line 124 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  auto var = getScalarVar(var_name, comp);
  return _sc_is_implicit ? var->sln() : var->slnOld();
}
Referenced by BoltzmannSolverScalar::BoltzmannSolverScalar(), VariableSum::computeValue(), VariableSumLog::computeValue(), ScalarCoupleable::coupledGenericScalarValue(), ParsedAuxScalar::ParsedAuxScalar(), ParsedODEKernel::ParsedODEKernel(), and ParsedScalarRateCoefficient::ParsedScalarRateCoefficient().
coupledScalarValueOld()
const VariableValue & ScalarCoupleable::coupledScalarValueOld (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the old (previous time step) value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a old VariableValue for the coupled variable
Definition at line 216 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  validateExecutionerType(var_name, "coupledScalarValueOld");
  auto var = getScalarVar(var_name, comp);
  return _sc_is_implicit ? var->slnOld() : var->slnOlder();
}
coupledScalarValueOlder()
const VariableValue & ScalarCoupleable::coupledScalarValueOlder (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the older (two time steps previous) value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a older VariableValue for the coupled variable
Definition at line 228 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  validateExecutionerType(var_name, "coupledScalarValueOlder");
  auto var = getScalarVar(var_name, comp);
  if (_sc_is_implicit)
    return var->slnOlder();
  else
    mooseError("Older values not available for explicit schemes");
}
coupledSecond()
const VariableSecond & Coupleable::coupledSecond (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns second spatial derivatives of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableSecond containing the second derivative of the coupled variable
See also
Kernel::second
Definition at line 1695 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_second.resize(_coupleable_max_qps);
    return _default_second;
  }
  checkFuncType(var_name, VarType::Second, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->secondSln() : var->secondSlnOlder();
  return (_c_is_implicit) ? var->secondSlnNeighbor() : var->secondSlnOlderNeighbor();
}
Referenced by NodeElemConstraint::coupledSecondarySecond(), and NodeFaceConstraint::coupledSecondarySecond().
coupledSecondOld()
const VariableSecond & Coupleable::coupledSecondOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old second spatial derivatives from previous time step of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableSecond containing the old second derivative of the coupled variable
See also
Kernel::secondOld
Definition at line 1711 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_second.resize(_coupleable_max_qps);
    return _default_second;
  }
  checkFuncType(var_name, VarType::Second, FuncAge::Old);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->secondSlnOld() : var->secondSlnOlder();
  return (_c_is_implicit) ? var->secondSlnOldNeighbor() : var->secondSlnOlderNeighbor();
}
coupledSecondOlder()
const VariableSecond & Coupleable::coupledSecondOlder (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old second derivative from two time steps previous of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableSecond containing the older second derivative of the coupled variable
See also
Kernel::secondOlder
Definition at line 1727 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
  {
    _default_second.resize(_coupleable_max_qps);
    return _default_second;
  }
  checkFuncType(var_name, VarType::Second, FuncAge::Older);
  if (!_coupleable_neighbor)
    return var->secondSlnOlder();
  return var->secondSlnOlderNeighbor();
}
coupledSecondPreviousNL()
const VariableSecond & Coupleable::coupledSecondPreviousNL (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns second derivative of a coupled variable for the previous Newton iterate.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableSecond containing the second derivative of the coupled variable
Definition at line 1743 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  _c_fe_problem.needsPreviousNewtonIteration(true);
  if (!var)
  {
    _default_second.resize(_coupleable_max_qps);
    return _default_second;
  }
  checkFuncType(var_name, VarType::Second, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return var->secondSlnPreviousNL();
  return var->secondSlnPreviousNLNeighbor();
}
coupledValue()
const VariableValue & Coupleable::coupledValue (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns value of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
See also
Kernel::_u
Definition at line 477 of file Coupleable.C.
{
  const auto * const var = getVarHelper<MooseVariableField<Real>>(var_name, comp);
  if (!var)
    return *getDefaultValue(var_name, comp);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return (_c_is_implicit) ? var->dofValues() : var->dofValuesOld();
    else
      return (_c_is_implicit) ? var->sln() : var->slnOld();
  }
  else
  {
    if (_c_nodal)
      return (_c_is_implicit) ? var->dofValuesNeighbor() : var->dofValuesOldNeighbor();
    else
      return (_c_is_implicit) ? var->slnNeighbor() : var->slnOldNeighbor();
  }
}
Referenced by Coupleable::coupledGenericValue(), NodeElemConstraint::coupledSecondaryValue(), NodeFaceConstraint::coupledSecondaryValue(), Coupleable::coupledValues(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), SideCurrent::SideCurrent(), SpeciesSum::SpeciesSum(), VariableTimeIntegrationAux::VariableTimeIntegrationAux(), and Coupleable::writableCoupledValue().
coupledValueLower()
const VariableValue & Coupleable::coupledValueLower (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns value of a coupled lower-dimensional variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
Definition at line 582 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
    return *getDefaultValue(var_name, comp);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  if (_coupleable_neighbor)
    mooseError(_c_name, ":coupledValueLower cannot be called in a coupleable neighbor object");
  if (_c_nodal)
    return (_c_is_implicit) ? var->dofValues() : var->dofValuesOld();
  else
    return (_c_is_implicit) ? var->slnLower() : var->slnLowerOld();
}
coupledValueOld()
const VariableValue & Coupleable::coupledValueOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old value from previous time step of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the old value of the coupled variable
See also
Kernel::valueOld
Definition at line 967 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
    return *getDefaultValue(var_name, comp);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Old);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return (_c_is_implicit) ? var->dofValuesOld() : var->dofValuesOlder();
    return (_c_is_implicit) ? var->slnOld() : var->slnOlder();
  }
  else
  {
    if (_c_nodal)
      return (_c_is_implicit) ? var->dofValuesOldNeighbor() : var->dofValuesOlderNeighbor();
    return (_c_is_implicit) ? var->slnOldNeighbor() : var->slnOlderNeighbor();
  }
}
Referenced by NodeElemConstraint::coupledSecondaryValueOld(), NodeFaceConstraint::coupledSecondaryValueOld(), Coupleable::coupledValuesOld(), and VariableTimeIntegrationAux::VariableTimeIntegrationAux().
coupledValueOlder()
const VariableValue & Coupleable::coupledValueOlder (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old value from two time steps previous of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the older value of the coupled variable
See also
Kernel::valueOlder
Definition at line 989 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
    return *getDefaultValue(var_name, comp);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Older);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesOlder();
    return var->slnOlder();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesOlderNeighbor();
    return var->slnOlderNeighbor();
  }
}
Referenced by NodeElemConstraint::coupledSecondaryValueOlder(), NodeFaceConstraint::coupledSecondaryValueOlder(), Coupleable::coupledValuesOlder(), and VariableTimeIntegrationAux::VariableTimeIntegrationAux().
coupledValuePreviousNL()
const VariableValue & Coupleable::coupledValuePreviousNL (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns value of previous Newton iterate of a coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the older value of the coupled variable
Definition at line 1011 of file Coupleable.C.
{
  const auto * var = getVar(var_name, comp);
  if (!var)
    return *getDefaultValue(var_name, comp);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  _c_fe_problem.needsPreviousNewtonIteration(true);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return var->dofValuesPreviousNL();
    return var->slnPreviousNL();
  }
  else
  {
    if (_c_nodal)
      return var->dofValuesPreviousNLNeighbor();
    return var->slnPreviousNLNeighbor();
  }
}
coupledValues()
std::vector< const VariableValue * > Coupleable::coupledValues (const std::string & var_name) const protected inherited
Returns the values for all of a coupled variable components.
Parameters
var_name Name of coupled variable
Returns
Vector of VariableValue pointers for each component of var_name
Definition at line 2367 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &coupledValue(var_name, comp); };
  return coupledVectorHelper<const VariableValue *>(var_name, func);
}
coupledValuesOld()
std::vector< const VariableValue * > Coupleable::coupledValuesOld (const std::string & var_name) const protected inherited
Returns the old values for all of a coupled variable's components.
Parameters
var_name Name of coupled variable
Returns
Vector of VariableValue pointers for each component of var_name
Definition at line 2548 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &coupledValueOld(var_name, comp); };
  return coupledVectorHelper<const VariableValue *>(var_name, func);
}
coupledValuesOlder()
std::vector< const VariableValue * > Coupleable::coupledValuesOlder (const std::string & var_name) const protected inherited
Returns the older values for all of a coupled variable's components.
Parameters
var_name Name of coupled variable
Returns
Vector of VariableValue pointers for each component of var_name
Definition at line 2555 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &coupledValueOlder(var_name, comp); };
  return coupledVectorHelper<const VariableValue *>(var_name, func);
}
coupledVectorDot()
const VectorVariableValue & Coupleable::coupledVectorDot (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Time derivative of a coupled vector variable.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a VectorVariableValue containing the time derivative of the coupled variable
Definition at line 1204 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
  {
    _default_vector_value_zero.resize(_coupleable_max_qps);
    return _default_vector_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return var->uDot();
  return var->uDotNeighbor();
}
coupledVectorDotDot()
const VectorVariableValue & Coupleable::coupledVectorDotDot (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Second time derivative of a coupled vector variable.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a VectorVariableValue containing the time derivative of the coupled variable
Definition at line 1220 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
  {
    _default_vector_value_zero.resize(_coupleable_max_qps);
    return _default_vector_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return var->uDotDot();
  return var->uDotDotNeighbor();
}
coupledVectorDotDotDu()
const VariableValue & Coupleable::coupledVectorDotDotDu (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Second time derivative of a coupled vector variable with respect to the coefficients.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a VariableValue containing the time derivative of the coupled vector variable with respect to the coefficients
Definition at line 1284 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
  {
    _default_value_zero.resize(_coupleable_max_qps, 0);
    return _default_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return var->duDotDotDu();
  return var->duDotDotDuNeighbor();
}
coupledVectorDotDotOld()
const VectorVariableValue & Coupleable::coupledVectorDotDotOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Old second time derivative of a coupled vector variable.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a VectorVariableValue containing the time derivative of the coupled variable
Definition at line 1252 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
  {
    _default_vector_value_zero.resize(_coupleable_max_qps);
    return _default_vector_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Old);
  if (!_coupleable_neighbor)
    return var->uDotDotOld();
  return var->uDotDotOldNeighbor();
}
coupledVectorDotDu()
const VariableValue & Coupleable::coupledVectorDotDu (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Time derivative of a coupled vector variable with respect to the coefficients.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a VariableValue containing the time derivative of the coupled vector variable with respect to the coefficients
Definition at line 1268 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
  {
    _default_value_zero.resize(_coupleable_max_qps, 0);
    return _default_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return var->duDotDu();
  return var->duDotDuNeighbor();
}
coupledVectorDotOld()
const VectorVariableValue & Coupleable::coupledVectorDotOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Old time derivative of a coupled vector variable.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a VectorVariableValue containing the time derivative of the coupled variable
Definition at line 1236 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
  {
    _default_vector_value_zero.resize(_coupleable_max_qps);
    return _default_vector_value_zero;
  }
  checkFuncType(var_name, VarType::Dot, FuncAge::Old);
  if (!_coupleable_neighbor)
    return var->uDotOld();
  return var->uDotOldNeighbor();
}
coupledVectorGradient()
const VectorVariableGradient & Coupleable::coupledVectorGradient (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns gradient of a coupled vector variable.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a VectorVariableGradient containing the gradient of the coupled vector variable
Definition at line 1560 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
  {
    _default_vector_gradient.resize(_coupleable_max_qps);
    return _default_vector_gradient;
  }
  checkFuncType(var_name, VarType::Gradient, FuncAge::Curr);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->gradSln() : var->gradSlnOld();
  return (_c_is_implicit) ? var->gradSlnNeighbor() : var->gradSlnOldNeighbor();
}
coupledVectorGradientOld()
const VectorVariableGradient & Coupleable::coupledVectorGradientOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old gradient from previous time step of a coupled vector variable.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a VectorVariableGradient containing the old gradient of the coupled vector variable
Definition at line 1576 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
  {
    _default_vector_gradient.resize(_coupleable_max_qps);
    return _default_vector_gradient;
  }
  checkFuncType(var_name, VarType::Gradient, FuncAge::Old);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->gradSlnOld() : var->gradSlnOlder();
  return (_c_is_implicit) ? var->gradSlnOldNeighbor() : var->gradSlnOlderNeighbor();
}
coupledVectorGradientOlder()
const VectorVariableGradient & Coupleable::coupledVectorGradientOlder (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old gradient from two time steps previous of a coupled vector variable.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a VectorVariableGradient containing the older gradient of the coupled vector variable
Definition at line 1592 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
  {
    _default_vector_gradient.resize(_coupleable_max_qps);
    return _default_vector_gradient;
  }
  checkFuncType(var_name, VarType::Gradient, FuncAge::Older);
  if (!_coupleable_neighbor)
    return var->gradSlnOlder();
  return var->gradSlnOlderNeighbor();
}
coupledVectorHelper()
template<typename T , typename Func > std::vector< T > Coupleable::coupledVectorHelper (const std::string & var_name, const Func & func) const inline protected inherited
Definition at line 1594 of file Coupleable.h.
  {
    const auto components = coupledComponents(var_name);
    std::vector<T> vals(components);
    for (MooseIndex(components) comp = 0; comp < components; ++comp)
      vals[comp] = func(comp);
    return vals;
  }
coupledVectorNeighborGradient()
const VectorVariableGradient & NeighborCoupleable::coupledVectorNeighborGradient (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 223 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("Gradients are non-sensical with nodal compute objects");
  const auto * var = getVectorVar(var_name, comp);
  return (_c_is_implicit) ? var->gradSlnNeighbor() : var->gradSlnOldNeighbor();
}
coupledVectorNeighborGradientOld()
const VectorVariableGradient & NeighborCoupleable::coupledVectorNeighborGradientOld (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 234 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("Gradients are non-sensical with nodal compute objects");
  validateExecutionerType(var_name, "coupledVectorNeighborGradientOld");
  const auto * var = getVectorVar(var_name, comp);
  return (_c_is_implicit) ? var->gradSlnOldNeighbor() : var->gradSlnOlderNeighbor();
}
coupledVectorNeighborGradientOlder()
const VectorVariableGradient & NeighborCoupleable::coupledVectorNeighborGradientOlder (const std::string & var_name, unsigned int comp = 0) const virtual inherited
Definition at line 246 of file NeighborCoupleable.C.
{
  if (_neighbor_nodal)
    mooseError("Gradients are non-sensical with nodal compute objects");
  validateExecutionerType(var_name, "coupledVectorNeighborGradientOlder");
  const auto * var = getVectorVar(var_name, comp);
  if (_c_is_implicit)
    return var->gradSlnOlderNeighbor();
  else
    mooseError("Older values not available for explicit schemes");
}
coupledVectorTagArrayDofValue()
const ArrayVariableValue & Coupleable::coupledVectorTagArrayDofValue (const std::string & var_name, const std::string & tag_name, unsigned int comp = 0) const protected inherited
Returns evaluations of a tagged vector at the requested variable's degree of freedom indices.
Parameters
var_name Name of coupled variable
tag_name vector tag name
Returns
Reference to a ArrayVariableValue for the coupled variable
Definition at line 763 of file Coupleable.C.
{
  return vectorTagDofValueHelper<RealEigenVector>(var_name, tag_name, comp);
}
coupledVectorTagArrayGradient() [1/2]
const ArrayVariableGradient & Coupleable::coupledVectorTagArrayGradient (const std::string & var_names, const std::string & tag_name, unsigned int index = 0) const protected virtual inherited
Definition at line 691 of file Coupleable.C.
{
  if (!_c_parameters.isParamValid(tag_name))
    mooseError("Tag name parameter '", tag_name, "' is invalid");
  TagName tagname = _c_parameters.get<TagName>(tag_name);
  if (!_c_fe_problem.vectorTagExists(tagname))
    mooseError("Tagged vector with tag name '", tagname, "' does not exist");
  TagID tag = _c_fe_problem.getVectorTagID(tagname);
  return coupledVectorTagArrayGradient(var_names, tag, index);
}
coupledVectorTagArrayGradient() [2/2]
const ArrayVariableGradient & Coupleable::coupledVectorTagArrayGradient (const std::string & var_names, TagID tag, unsigned int index = 0) const protected virtual inherited
Returns gradient of a coupled array variable for a given tag.
Parameters
var_names Name(s) of coupled array variable(s)
tag vector tag ID
index Index of the desired variable in the vector of coupled variables
Returns
Reference to a ArrayVariableGradient containing the gradient of the coupled array variable
See also
Kernel::gradient
Definition at line 669 of file Coupleable.C.
{
  const auto * var = getArrayVar(var_names, index);
  if (!var)
    mooseError(var_names, ": invalid variable name for coupledVectorTagArrayGradient");
  checkFuncType(var_names, VarType::Ignore, FuncAge::Curr);
  if (!_c_fe_problem.vectorTagExists(tag))
    mooseError("Attempting to couple to vector tag with ID ",
               tag,
               "in ",
               _c_name,
               ", but a vector tag with that ID does not exist");
  const_cast<Coupleable *>(this)->addFEVariableCoupleableVectorTag(tag);
  return var->vectorTagGradient(tag);
}
Referenced by Coupleable::coupledVectorTagArrayGradient(), and Coupleable::coupledVectorTagArrayGradients().
coupledVectorTagArrayGradients() [1/2]
std::vector< const ArrayVariableGradient * > Coupleable::coupledVectorTagArrayGradients (const std::string & var_names, const std::string & tag_name) const protected inherited
Definition at line 2487 of file Coupleable.C.
{
  if (!_c_parameters.isParamValid(tag_name))
    mooseError("Tag name parameter '", tag_name, "' is invalid");
  TagName tagname = _c_parameters.get<TagName>(tag_name);
  if (!_c_fe_problem.vectorTagExists(tagname))
    mooseError("Tagged vector with tag name '", tagname, "' does not exist");
  TagID tag = _c_fe_problem.getVectorTagID(tagname);
  return coupledVectorTagArrayGradients(var_names, tag);
}
coupledVectorTagArrayGradients() [2/2]
std::vector< const ArrayVariableGradient * > Coupleable::coupledVectorTagArrayGradients (const std::string & var_names, TagID tag) const protected inherited
Returns gradients for all the coupled variables desired for a given tag.
Parameters
var_names Name(s) of coupled array variable(s)
tag vector tag ID
Returns
Vector of ArrayVariableGradient pointers for each variable in var_name
Definition at line 2479 of file Coupleable.C.
{
  auto func = [this, &var_names, &tag](unsigned int index)
  { return &coupledVectorTagArrayGradient(var_names, tag, index); };
  return coupledVectorHelper<const ArrayVariableGradient *>(var_names, func);
}
Referenced by Coupleable::coupledVectorTagArrayGradients().
coupledVectorTagArrayValue() [1/2]
const ArrayVariableValue & Coupleable::coupledVectorTagArrayValue (const std::string & var_names, const std::string & tag_name, unsigned int index = 0) const protected virtual inherited
Definition at line 623 of file Coupleable.C.
{
  return vectorTagValueHelper<RealEigenVector>(var_names, tag_name, index);
}
coupledVectorTagArrayValue() [2/2]
const ArrayVariableValue & Coupleable::coupledVectorTagArrayValue (const std::string & var_names, TagID tag, unsigned int index = 0) const protected virtual inherited
Returns value of a coupled array variable for a given tag.
Parameters
var_names Name(s) of coupled array variable(s)
tag vector tag ID
index Index of the desired variable in the vector of coupled variables
Returns
Reference to a VariableValue for the coupled array variable
See also
Kernel::_u
Definition at line 615 of file Coupleable.C.
{
  return vectorTagValueHelper<RealEigenVector>(var_names, tag, index);
}
Referenced by Coupleable::coupledVectorTagArrayValues().
coupledVectorTagArrayValues() [1/2]
std::vector< const ArrayVariableValue * > Coupleable::coupledVectorTagArrayValues (const std::string & var_names, const std::string & tag_name) const protected inherited
Definition at line 2441 of file Coupleable.C.
{
  if (!_c_parameters.isParamValid(tag_name))
    mooseError("Tag name parameter '", tag_name, "' is invalid");
  TagName tagname = _c_parameters.get<TagName>(tag_name);
  if (!_c_fe_problem.vectorTagExists(tagname))
    mooseError("Tagged vector with tag name '", tagname, "' does not exist");
  TagID tag = _c_fe_problem.getVectorTagID(tagname);
  return coupledVectorTagArrayValues(var_names, tag);
}
coupledVectorTagArrayValues() [2/2]
std::vector< const ArrayVariableValue * > Coupleable::coupledVectorTagArrayValues (const std::string & var_names, TagID tag) const protected inherited
Returns the values for all the coupled variables desired for a given tag.
Parameters
var_name Name of array coupled variable
tag vector tag ID
Returns
Vector of ArrayVariableValue pointers for each variable in var_names
Definition at line 2433 of file Coupleable.C.
{
  auto func = [this, &var_names, &tag](unsigned int index)
  { return &coupledVectorTagArrayValue(var_names, tag, index); };
  return coupledVectorHelper<const ArrayVariableValue *>(var_names, func);
}
Referenced by Coupleable::coupledVectorTagArrayValues().
coupledVectorTagDofValue() [1/2]
const VariableValue & Coupleable::coupledVectorTagDofValue (const std::string & var_name, TagID tag, unsigned int index = 0) const protected virtual inherited
Returns dof value of a coupled variable for a given tag.
Parameters
var_names Name(s) of coupled variable(s)
tag vector tag ID
index Index of the desired variable in the vector of coupled variables
Returns
Reference to a DofValue for the coupled variable
Definition at line 747 of file Coupleable.C.
{
  return vectorTagDofValueHelper<Real>(var_name, tag, comp);
}
Referenced by Coupleable::coupledVectorTagDofValues().
coupledVectorTagDofValue() [2/2]
const VariableValue & Coupleable::coupledVectorTagDofValue (const std::string & var_names, const std::string & tag_name, unsigned int index = 0) const protected virtual inherited
Definition at line 755 of file Coupleable.C.
{
  return vectorTagDofValueHelper<Real>(var_name, tag_name, comp);
}
coupledVectorTagDofValues() [1/2]
std::vector< const VariableValue * > Coupleable::coupledVectorTagDofValues (const std::string & var_names, const std::string & tag_name) const protected inherited
Definition at line 2510 of file Coupleable.C.
{
  if (!_c_parameters.isParamValid(tag_name))
    mooseError("Tag name parameter '", tag_name, "' is invalid");
  TagName tagname = _c_parameters.get<TagName>(tag_name);
  if (!_c_fe_problem.vectorTagExists(tagname))
    mooseError("Tagged vector with tag name '", tagname, "' does not exist");
  TagID tag = _c_fe_problem.getVectorTagID(tagname);
  return coupledVectorTagDofValues(var_names, tag);
}
coupledVectorTagDofValues() [2/2]
std::vector< const VariableValue * > Coupleable::coupledVectorTagDofValues (const std::string & var_names, TagID tag) const protected inherited
Returns the dof values for all the coupled variables desired for a given tag.
Parameters
var_names Name(s) of coupled variable(s)
tag vector tag ID
Returns
Vector of VariableValue pointers for each variable in var_name
Definition at line 2502 of file Coupleable.C.
{
  auto func = [this, &var_names, &tag](unsigned int comp)
  { return &coupledVectorTagDofValue(var_names, tag, comp); };
  return coupledVectorHelper<const VariableValue *>(var_names, func);
}
Referenced by Coupleable::coupledVectorTagDofValues().
coupledVectorTagGradient() [1/2]
const VariableGradient & Coupleable::coupledVectorTagGradient (const std::string & var_names, const std::string & tag_name, unsigned int index = 0) const protected virtual inherited
Definition at line 653 of file Coupleable.C.
{
  if (!_c_parameters.isParamValid(tag_name))
    mooseError("Tag name parameter '", tag_name, "' is invalid");
  TagName tagname = _c_parameters.get<TagName>(tag_name);
  if (!_c_fe_problem.vectorTagExists(tagname))
    mooseError("Tagged vector with tag name '", tagname, "' does not exist");
  TagID tag = _c_fe_problem.getVectorTagID(tagname);
  return coupledVectorTagGradient(var_names, tag, index);
}
coupledVectorTagGradient() [2/2]
const VariableGradient & Coupleable::coupledVectorTagGradient (const std::string & var_names, TagID tag, unsigned int index = 0) const protected virtual inherited
Returns gradient of a coupled variable for a given tag.
Parameters
var_names Name(s) of coupled variable(s)
tag vector tag ID
index Index of the desired variable in the vector of coupled variables
Returns
Reference to a VariableGradient containing the gradient of the coupled variable
See also
Kernel::gradient
Definition at line 631 of file Coupleable.C.
{
  const auto * var = getVar(var_names, index);
  if (!var)
    mooseError(var_names, ": invalid variable name for coupledVectorTagGradient");
  checkFuncType(var_names, VarType::Ignore, FuncAge::Curr);
  if (!_c_fe_problem.vectorTagExists(tag))
    mooseError("Attempting to couple to vector tag with ID ",
               tag,
               "in ",
               _c_name,
               ", but a vector tag with that ID does not exist");
  const_cast<Coupleable *>(this)->addFEVariableCoupleableVectorTag(tag);
  return var->vectorTagGradient(tag);
}
Referenced by Coupleable::coupledVectorTagGradient(), and Coupleable::coupledVectorTagGradients().
coupledVectorTagGradients() [1/2]
std::vector< const VariableGradient * > Coupleable::coupledVectorTagGradients (const std::string & var_names, const std::string & tag_name) const protected inherited
Definition at line 2464 of file Coupleable.C.
{
  if (!_c_parameters.isParamValid(tag_name))
    mooseError("Tag name parameter '", tag_name, "' is invalid");
  TagName tagname = _c_parameters.get<TagName>(tag_name);
  if (!_c_fe_problem.vectorTagExists(tagname))
    mooseError("Tagged vector with tag name '", tagname, "' does not exist");
  TagID tag = _c_fe_problem.getVectorTagID(tagname);
  return coupledVectorTagGradients(var_names, tag);
}
coupledVectorTagGradients() [2/2]
std::vector< const VariableGradient * > Coupleable::coupledVectorTagGradients (const std::string & var_names, TagID tag) const protected inherited
Returns gradients for all the coupled variables desired for a given tag.
Parameters
var_names Name(s) of coupled array variable(s)
tag vector tag ID
Returns
Vector of VariableGradient pointers for each variables in var_name
Definition at line 2456 of file Coupleable.C.
{
  auto func = [this, &var_names, &tag](unsigned int index)
  { return &coupledVectorTagGradient(var_names, tag, index); };
  return coupledVectorHelper<const VariableGradient *>(var_names, func);
}
Referenced by Coupleable::coupledVectorTagGradients().
coupledVectorTagScalarValue()
const VariableValue & ScalarCoupleable::coupledVectorTagScalarValue (const std::string & var_name, TagID tag, unsigned int comp = 0) const protected inherited
Returns value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
tag Tag ID of coupled vector ;
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
Definition at line 181 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  if (!_sc_fe_problem.vectorTagExists(tag))
    mooseError("Attempting to couple to vector tag scalar with ID ",
               tag,
               "in ",
               _sc_name,
               ", but a vector tag with that ID does not exist");
  _sc_coupleable_vector_tags.insert(tag);
  return getScalarVar(var_name, comp)->vectorTagSln(tag);
}
coupledVectorTagValue() [1/2]
const VariableValue & Coupleable::coupledVectorTagValue (const std::string & var_names, const std::string & tag_name, unsigned int index = 0) const protected virtual inherited
Definition at line 607 of file Coupleable.C.
{
  return vectorTagValueHelper<Real>(var_names, tag_name, index);
}
coupledVectorTagValue() [2/2]
const VariableValue & Coupleable::coupledVectorTagValue (const std::string & var_names, TagID tag, unsigned int index = 0) const protected virtual inherited
Returns value of a coupled variable for a given tag.
Parameters
var_names Name(s) of coupled variable(s)
tag vector tag ID
index Index of the desired variable in the vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
See also
Kernel::_u
Definition at line 599 of file Coupleable.C.
{
  return vectorTagValueHelper<Real>(var_names, tag, index);
}
Referenced by Coupleable::coupledVectorTagValues().
coupledVectorTagValues() [1/2]
std::vector< const VariableValue * > Coupleable::coupledVectorTagValues (const std::string & var_names, const std::string & tag_name) const protected inherited
Definition at line 2418 of file Coupleable.C.
{
  if (!_c_parameters.isParamValid(tag_name))
    mooseError("Tag name parameter '", tag_name, "' is invalid");
  TagName tagname = _c_parameters.get<TagName>(tag_name);
  if (!_c_fe_problem.vectorTagExists(tagname))
    mooseError("Tagged vector with tag name '", tagname, "' does not exist");
  TagID tag = _c_fe_problem.getVectorTagID(tagname);
  return coupledVectorTagValues(var_names, tag);
}
coupledVectorTagValues() [2/2]
std::vector< const VariableValue * > Coupleable::coupledVectorTagValues (const std::string & var_names, TagID tag) const protected inherited
Returns the values for all the coupled variables desired for a given tag.
Parameters
var_names Name(s) of coupled variable(s)
tag vector tag ID
Returns
Vector of VariableValue pointers for each variable in var_names
Definition at line 2410 of file Coupleable.C.
{
  auto func = [this, &var_names, &tag](unsigned int comp)
  { return &coupledVectorTagValue(var_names, tag, comp); };
  return coupledVectorHelper<const VariableValue *>(var_names, func);
}
Referenced by Coupleable::coupledVectorTagValues().
coupledVectorValue()
const VectorVariableValue & Coupleable::coupledVectorValue (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns value of a coupled vector variable.
Parameters
var_name Name of coupled vector variable
comp Component number for vector of coupled vector variables
Returns
Reference to a VectorVariableValue for the coupled vector variable
See also
VectorKernel::_u
Definition at line 804 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
    return *getDefaultVectorValue(var_name);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  if (!_coupleable_neighbor)
  {
    if (_c_nodal)
      return _c_is_implicit ? var->nodalValueArray() : var->nodalValueOldArray();
    else
      return _c_is_implicit ? var->sln() : var->slnOld();
  }
  else
  {
    if (_c_nodal)
      // Since this is at a node, I don't feel like there should be any "neighbor" logic
      return _c_is_implicit ? var->nodalValueArray() : var->nodalValueOldArray();
    else
      return _c_is_implicit ? var->slnNeighbor() : var->slnOldNeighbor();
  }
}
Referenced by Coupleable::coupledGenericValues().
coupledVectorValueOld()
const VectorVariableValue & Coupleable::coupledVectorValueOld (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old value from previous time step of a coupled vector variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VectorVariableValue containing the old value of the coupled variable
See also
VectorKernel::_u_old
Definition at line 1034 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
    return *getDefaultVectorValue(var_name);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Old);
  if (!_coupleable_neighbor)
    return (_c_is_implicit) ? var->slnOld() : var->slnOlder();
  return (_c_is_implicit) ? var->slnOldNeighbor() : var->slnOlderNeighbor();
}
coupledVectorValueOlder()
const VectorVariableValue & Coupleable::coupledVectorValueOlder (const std::string & var_name, unsigned int comp = 0) const protected virtual inherited
Returns an old value from two time steps previous of a coupled vector variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VectorVariableValue containing the older value of the coupled variable
See also
VectorKernel::_u_older
Definition at line 1047 of file Coupleable.C.
{
  const auto * var = getVectorVar(var_name, comp);
  if (!var)
    return *getDefaultVectorValue(var_name);
  checkFuncType(var_name, VarType::Ignore, FuncAge::Older);
  if (!_coupleable_neighbor)
    return var->slnOlder();
  return var->slnOlderNeighbor();
}
coupledVectorValues()
std::vector< const VectorVariableValue * > Coupleable::coupledVectorValues (const std::string & var_name) const protected inherited
Returns the values for all of a coupled vector variable's components.
Parameters
var_name Name of coupled variable
Returns
Vector of VectorVariableValue pointers for each component of var_name
Definition at line 2374 of file Coupleable.C.
{
  auto func = [this, &var_name](unsigned int comp) { return &coupledVectorValue(var_name, comp); };
  return coupledVectorHelper<const VectorVariableValue *>(var_name, func);
}
genericZeroGradient() [1/3]
template<bool is_ad> const GenericVariableGradient< is_ad > & Coupleable::genericZeroGradient () protected inherited
Returns zero gradient templated with automatic differentiation boolean.
Returns
Reference to a const GenericVariableValue
genericZeroGradient() [2/3]
template<> const GenericVariableGradient< false > & Coupleable::genericZeroGradient () protected inherited
Definition at line 2294 of file Coupleable.C.
{
  return _grad_zero;
}
genericZeroGradient() [3/3]
template<> const GenericVariableGradient< true > & Coupleable::genericZeroGradient () protected inherited
Definition at line 2301 of file Coupleable.C.
{
  return _ad_grad_zero;
}
genericZeroSecond() [1/3]
template<bool is_ad> const GenericVariableSecond< is_ad > & Coupleable::genericZeroSecond () protected inherited
Returns zero second derivative templated with automatic differentiation boolean.
Returns
Reference to a const GenericVariableValue
genericZeroSecond() [2/3]
template<> const GenericVariableSecond< false > & Coupleable::genericZeroSecond () protected inherited
Definition at line 2308 of file Coupleable.C.
{
  return _second_zero;
}
genericZeroSecond() [3/3]
template<> const GenericVariableSecond< true > & Coupleable::genericZeroSecond () protected inherited
Definition at line 2315 of file Coupleable.C.
{
  return _ad_second_zero;
}
genericZeroValue() [1/3]
template<bool is_ad> const GenericVariableValue< is_ad > & Coupleable::genericZeroValue () protected inherited
Returns zero value templated with automatic differentiation boolean.
Returns
Reference to a const GenericVariableValue
genericZeroValue() [2/3]
template<> const GenericVariableValue< false > & Coupleable::genericZeroValue () protected inherited
Definition at line 2280 of file Coupleable.C.
{
  return _zero;
}
genericZeroValue() [3/3]
template<> const GenericVariableValue< true > & Coupleable::genericZeroValue () protected inherited
Definition at line 2287 of file Coupleable.C.
{
  return _ad_zero;
}
getADDefaultGradient()
const ADVariableGradient & Coupleable::getADDefaultGradient () const inherited
Helper method to return (and insert if necessary) the default gradient for Automatic Differentiation for an uncoupled variable.
Parameters
var_name the name of the variable for which to retrieve a default gradient
Returns
VariableGradient * a pointer to the associated VariableGradient.
Definition at line 2238 of file Coupleable.C.
{
  _ad_default_gradient.resize(_coupleable_max_qps);
  return _ad_default_gradient;
}
Referenced by Coupleable::adCoupledGradient(), and Coupleable::adCoupledGradientDot().
getADDefaultSecond()
const ADVariableSecond & Coupleable::getADDefaultSecond () const inherited
Helper method to return (and insert if necessary) the default second derivatives for Automatic Differentiation for an uncoupled variable.
Parameters
var_name the name of the variable for which to retrieve a default second derivative
Returns
VariableSecond * a pointer to the associated VariableSecond.
Definition at line 2252 of file Coupleable.C.
{
  _ad_default_second.resize(_coupleable_max_qps);
  return _ad_default_second;
}
Referenced by Coupleable::adCoupledSecond().
getADDefaultValue()
const ADVariableValue * Coupleable::getADDefaultValue (const std::string & var_name) const inherited
Helper method to return (and insert if necessary) the default value for Automatic Differentiation for an uncoupled variable.
Parameters
var_name the name of the variable for which to retrieve a default value
Returns
VariableValue * a pointer to the associated VarirableValue.
Definition at line 2207 of file Coupleable.C.
{
  auto default_value_it = _ad_default_value.find(var_name);
  if (default_value_it == _ad_default_value.end())
  {
    auto value = std::make_unique<ADVariableValue>(_coupleable_max_qps,
                                                   _c_parameters.defaultCoupledValue(var_name));
    default_value_it = _ad_default_value.insert(std::make_pair(var_name, std::move(value))).first;
  }
  return default_value_it->second.get();
}
Referenced by Coupleable::adCoupledDofValues(), Coupleable::adCoupledDot(), Coupleable::adCoupledDotDot(), Coupleable::adCoupledLowerValue(), NeighborCoupleable::adCoupledNeighborValue(), and Coupleable::adCoupledValue().
getADDefaultVectorGradient()
const ADVectorVariableGradient & Coupleable::getADDefaultVectorGradient () const inherited
Helper method to return (and insert if necessary) the default gradient for Automatic Differentiation for an uncoupled vector variable.
Parameters
var_name the name of the vector variable for which to retrieve a default gradient
Returns
VariableGradient * a pointer to the associated VectorVariableGradient.
Definition at line 2245 of file Coupleable.C.
{
  _ad_default_vector_gradient.resize(_coupleable_max_qps);
  return _ad_default_vector_gradient;
}
Referenced by Coupleable::adCoupledVectorGradient().
getADDefaultVectorValue()
const ADVectorVariableValue * Coupleable::getADDefaultVectorValue (const std::string & var_name) const inherited
Helper method to return (and insert if necessary) the default vector value for Automatic Differentiation for an uncoupled variable.
Parameters
var_name the name of the vector variable for which to retrieve a default value
Returns
VariableVectorValue * a pointer to the associated VarirableVectorValue.
Definition at line 2221 of file Coupleable.C.
{
  auto default_value_it = _ad_default_vector_value.find(var_name);
  if (default_value_it == _ad_default_vector_value.end())
  {
    RealVectorValue default_vec;
    for (unsigned int i = 0; i < _c_parameters.numberDefaultCoupledValues(var_name); ++i)
      default_vec(i) = _c_parameters.defaultCoupledValue(var_name, i);
    auto value = std::make_unique<ADVectorVariableValue>(_coupleable_max_qps, default_vec);
    default_value_it =
        _ad_default_vector_value.insert(std::make_pair(var_name, std::move(value))).first;
  }
  return default_value_it->second.get();
}
Referenced by Coupleable::adCoupledVectorDot(), NeighborCoupleable::adCoupledVectorNeighborValue(), and Coupleable::adCoupledVectorValue().
getArrayVar() [1/2]
ArrayMooseVariable * Coupleable::getArrayVar (const std::string & var_name, unsigned int comp) protected inherited
Extract pointer to a coupled array variable.
Parameters
var_name Name of parameter desired
comp Component number of multiple coupled variables
Returns
Pointer to the desired variable
Definition at line 300 of file Coupleable.C.
{
  return const_cast<ArrayMooseVariable *>(getVarHelper<ArrayMooseVariable>(var_name, comp));
}
Referenced by ArrayParsedAux::ArrayParsedAux(), Coupleable::coupledArrayDofValues(), Coupleable::coupledArrayDot(), Coupleable::coupledArrayDotDot(), Coupleable::coupledArrayDotDotOld(), Coupleable::coupledArrayDotDu(), Coupleable::coupledArrayDotOld(), Coupleable::coupledArrayGradient(), Coupleable::coupledArrayGradientOld(), Coupleable::coupledArrayGradientOlder(), NeighborCoupleable::coupledArrayNeighborGradient(), NeighborCoupleable::coupledArrayNeighborGradientOld(), NeighborCoupleable::coupledArrayNeighborGradientOlder(), NeighborCoupleable::coupledArrayNeighborValue(), Coupleable::coupledArrayValue(), Coupleable::coupledArrayValueOld(), Coupleable::coupledArrayValueOlder(), Coupleable::coupledVectorTagArrayGradient(), TagVectorArrayVariableAux::TagVectorArrayVariableAux(), and TagVectorArrayVariableValueAux::TagVectorArrayVariableValueAux().
getArrayVar() [2/2]
const ArrayMooseVariable * Coupleable::getArrayVar (const std::string & var_name, unsigned int comp) const protected inherited
Extract pointer to a coupled array variable.
Parameters
var_name Name of parameter desired
comp Component number of multiple coupled variables
Returns
Pointer to the desired variable
Definition at line 323 of file Coupleable.C.
{
  return getVarHelper<ArrayMooseVariable>(var_name, comp);
}
getCoupledArrayMooseVars()
const std::vector< ArrayMooseVariable * > & Coupleable::getCoupledArrayMooseVars () const inline inherited
Get the list of array coupled variables.
Returns
The list of array coupled variables
Definition at line 96 of file Coupleable.h.
  {
    return _coupled_array_moose_vars;
  }
getCoupledMooseScalarVars()
const std::vector< MooseVariableScalar * > & ScalarCoupleable::getCoupledMooseScalarVars () inline inherited
Get the list of coupled scalar variables.
Returns
The list of coupled variables
Definition at line 45 of file ScalarCoupleable.h.
  {
    return _coupled_moose_scalar_vars;
  }
Referenced by AuxScalarKernel::AuxScalarKernel(), MortarScalarBase::computeJacobian(), and ScalarInitialCondition::ScalarInitialCondition().
getCoupledMooseVars()
const std::vector< MooseVariableFieldBase * > & Coupleable::getCoupledMooseVars () const inline inherited
Get the list of all coupled variables.
Returns
The list of all coupled variables
Definition at line 69 of file Coupleable.h.
  {
    return _coupled_moose_vars;
  }
Referenced by AuxNodalScalarKernel::AuxNodalScalarKernel(), BuildArrayVariableAux::BuildArrayVariableAux(), CoupleableMooseVariableDependencyIntermediateInterface::CoupleableMooseVariableDependencyIntermediateInterface(), DomainUserObject::DomainUserObject(), ElementIndicator::ElementIndicator(), ElementUserObject::ElementUserObject(), InterfaceMaterial::InterfaceMaterial(), InterfaceUserObjectBase::InterfaceUserObjectBase(), InternalSideIndicator::InternalSideIndicator(), InternalSideUserObject::InternalSideUserObject(), Material::Material(), NeighborCoupleableMooseVariableDependencyIntermediateInterface(), NodalScalarKernel::NodalScalarKernel(), NodalUserObject::NodalUserObject(), and SideUserObject::SideUserObject().
getCoupledStandardMooseVars()
const std::vector< MooseVariable * > & Coupleable::getCoupledStandardMooseVars () const inline inherited
Get the list of standard coupled variables.
Returns
The list of standard coupled variables
Definition at line 78 of file Coupleable.h.
  {
    return _coupled_standard_moose_vars;
  }
getCoupledVars()
const std::unordered_map< std::string, std::vector< MooseVariableFieldBase * > > & Coupleable::getCoupledVars () const inline inherited
Get the list of coupled variables.
Returns
The list of coupled variables
Definition at line 60 of file Coupleable.h.
  {
    return _coupled_vars;
  }
Referenced by InitialConditionBase::InitialConditionBase().
getCoupledVectorMooseVars()
const std::vector< VectorMooseVariable * > & Coupleable::getCoupledVectorMooseVars () const inline inherited
Get the list of vector coupled variables.
Returns
The list of vector coupled variables
Definition at line 87 of file Coupleable.h.
  {
    return _coupled_vector_moose_vars;
  }
getDefaultArrayValue()
const ArrayVariableValue * Coupleable::getDefaultArrayValue (const std::string & var_name) const private inherited
Helper method to return (and insert if necessary) the default value for an uncoupled array variable.
Parameters
var_name the name of the vector variable for which to retrieve a default value
Returns
a pointer to the associated VectorVariableValue.
Definition at line 391 of file Coupleable.C.
{
  auto default_value_it = _default_array_value.find(var_name);
  if (default_value_it == _default_array_value.end())
  {
    auto value = std::make_unique<ArrayVariableValue>(_coupleable_max_qps);
    for (unsigned int qp = 0; qp < _coupleable_max_qps; ++qp)
    {
      auto n = _c_parameters.numberDefaultCoupledValues(var_name);
      (*value)[qp].resize(n);
      for (unsigned int i = 0; i < n; ++i)
        (*value)[qp](i) = _c_parameters.defaultCoupledValue(var_name, i);
    }
    default_value_it =
        _default_array_value.insert(std::make_pair(var_name, std::move(value))).first;
  }
  return default_value_it->second.get();
}
Referenced by Coupleable::coupledArrayDofValues(), Coupleable::coupledArrayValue(), Coupleable::coupledArrayValueOld(), Coupleable::coupledArrayValueOlder(), and Coupleable::getDefaultNodalValue().
getDefaultFunctor()
template<typename T > const Moose::Functor< T > & Coupleable::getDefaultFunctor (const std::string & var_name) const private inherited
getDefaultNodalValue() [1/3]
template<typename T > template const Real & Coupleable::getDefaultNodalValue< Real > (const std::string & var_name, unsigned int comp = 0) const private inherited
Get nodal default value.
Definition at line 413 of file Coupleable.C.
{
  auto && default_variable_value = getDefaultValue(var_name, comp);
  return *default_variable_value->data();
}
getDefaultNodalValue() [2/3]
template<> const RealVectorValue & Coupleable::getDefaultNodalValue (const std::string & var_name, unsigned int) const private inherited
Definition at line 420 of file Coupleable.C.
{
  auto && default_variable_value = getDefaultVectorValue(var_name);
  return *default_variable_value->data();
}
getDefaultNodalValue() [3/3]
template<> const RealEigenVector & Coupleable::getDefaultNodalValue (const std::string & var_name, unsigned int) const private inherited
Definition at line 428 of file Coupleable.C.
{
  auto && default_variable_value = getDefaultArrayValue(var_name);
  return *default_variable_value->data();
}
getDefaultValue()
const VariableValue * Coupleable::getDefaultValue (const std::string & var_name, unsigned int comp) const private inherited
Helper method to return (and insert if necessary) the default value for an uncoupled variable.
Parameters
var_name the name of the variable for which to retrieve a default value
Returns
a pointer to the associated VariableValue.
Definition at line 329 of file Coupleable.C.
{
  // make sure we don't access values that were not provided
  checkComponent(_obj, comp, _c_parameters.numberDefaultCoupledValues(var_name), var_name);
  auto default_value_it = _default_value.find(var_name);
  if (default_value_it == _default_value.end())
  {
    _default_value[var_name].emplace_back(std::make_unique<VariableValue>(
        _coupleable_max_qps, _c_parameters.defaultCoupledValue(var_name, 0)));
    for (unsigned int j = 1; j < _c_parameters.numberDefaultCoupledValues(var_name); ++j)
      _default_value[var_name].emplace_back(std::make_unique<VariableValue>(
          _coupleable_max_qps, _c_parameters.defaultCoupledValue(var_name, j)));
    default_value_it = _default_value.find(var_name);
  }
  const auto & default_value_vec = default_value_it->second;
  const auto n_default_vals = default_value_vec.size();
  if (comp >= n_default_vals)
    mooseError("Requested comp ",
               comp,
               " is equal to or greater than the number of default values ",
               n_default_vals);
  return default_value_vec[comp].get();
}
Referenced by Coupleable::coupledDofValues(), Coupleable::coupledDofValuesOld(), Coupleable::coupledDofValuesOlder(), Coupleable::coupledValue(), Coupleable::coupledValueLower(), Coupleable::coupledValueOld(), Coupleable::coupledValueOlder(), Coupleable::coupledValuePreviousNL(), and Coupleable::getDefaultNodalValue().
getDefaultVectorValue()
const VectorVariableValue * Coupleable::getDefaultVectorValue (const std::string & var_name) const private inherited
Helper method to return (and insert if necessary) the default value for an uncoupled vector variable.
Parameters
var_name the name of the vector variable for which to retrieve a default value
Returns
a pointer to the associated VectorVariableValue.
Definition at line 356 of file Coupleable.C.
{
  auto default_value_it = _default_vector_value.find(var_name);
  if (default_value_it == _default_vector_value.end())
  {
    auto value = std::make_unique<VectorVariableValue>(_coupleable_max_qps, 0);
    bool already_warned = false;
    for (unsigned int qp = 0; qp < _coupleable_max_qps; ++qp)
      for (const auto i : make_range(Moose::dim))
      {
        try
        {
          (*value)[qp](i) = _c_parameters.defaultCoupledValue(var_name, i);
        }
        catch (const std::out_of_range &)
        {
          if (!already_warned)
            mooseWarning(
                "You supplied less than 3 arguments for the default vector value for variable ",
                var_name,
                ". Did you accidently leave something off? We are going to assign 0s, assuming "
                "this "
                "was intentional.");
          already_warned = true;
          (*value)[qp](i) = 0;
        }
      }
    default_value_it =
        _default_vector_value.insert(std::make_pair(var_name, std::move(value))).first;
  }
  return default_value_it->second.get();
}
Referenced by Coupleable::coupledVectorValue(), Coupleable::coupledVectorValueOld(), Coupleable::coupledVectorValueOlder(), and Coupleable::getDefaultNodalValue().
getFEVar()
const MooseVariableFieldBase * Coupleable::getFEVar (const std::string & var_name, unsigned int comp) const protected inherited
Deprecated method.
Use getFieldVar instead Extract pointer to a base coupled field variable. Could be either a finite volume or finite element variable
Parameters
var_name Name of parameter desired
comp Component number of multiple coupled variables
Returns
Pointer to the desired variable
Definition at line 262 of file Coupleable.C.
{
  mooseDeprecated("Coupleable::getFEVar is deprecated. Please use Coupleable::getFieldVar instead. "
                  "Note that this method could potentially return a finite volume variable");
  return getFieldVar(var_name, comp);
}
getFEVariableCoupleableMatrixTags() [1/2]
std::set< TagID > & Coupleable::getFEVariableCoupleableMatrixTags () inline inherited
Definition at line 107 of file Coupleable.h.
{ return _fe_coupleable_matrix_tags; }
getFEVariableCoupleableMatrixTags() [2/2]
const std::set< TagID > & Coupleable::getFEVariableCoupleableMatrixTags () const inline inherited
Definition at line 114 of file Coupleable.h.
  {
    return _fe_coupleable_matrix_tags;
  }
getFEVariableCoupleableVectorTags() [1/2]
std::set< TagID > & Coupleable::getFEVariableCoupleableVectorTags () inline inherited
Definition at line 105 of file Coupleable.h.
{ return _fe_coupleable_vector_tags; }
Referenced by ComputeUserObjectsThread::subdomainChanged(), and MooseObjectWarehouseBase< T >::updateFEVariableCoupledVectorTagDependencyHelper().
getFEVariableCoupleableVectorTags() [2/2]
const std::set< TagID > & Coupleable::getFEVariableCoupleableVectorTags () const inline inherited
Definition at line 109 of file Coupleable.h.
  {
    return _fe_coupleable_vector_tags;
  }
getFieldVar() [1/2]
MooseVariableFieldBase * Coupleable::getFieldVar (const std::string & var_name, unsigned int comp) protected inherited
Definition at line 270 of file Coupleable.C.
{
  return getVarHelper<MooseVariableFieldBase>(var_name, comp);
}
getFieldVar() [2/2]
const MooseVariableFieldBase * Coupleable::getFieldVar (const std::string & var_name, unsigned int comp) const protected inherited
Definition at line 276 of file Coupleable.C.
{
  return getVarHelper<MooseVariableFieldBase>(var_name, comp);
}
Referenced by ArrayParsedAux::ArrayParsedAux(), Coupleable::coupled(), Coupleable::coupledName(), Coupleable::getFEVar(), DomainUserObject::getInterfaceFieldVar(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), and ParsedAux::ParsedAux().
getMooseVariableDependencies()
const std::set< MooseVariableFieldBase * > & MooseVariableDependencyInterface::getMooseVariableDependencies () const inline inherited
Retrieve the set of MooseVariableFieldBase that this object depends on.
Returns
The MooseVariableFieldBase that MUST be reinited before evaluating this object
Definition at line 35 of file MooseVariableDependencyInterface.h.
  {
    return _moose_variable_dependencies;
  }
Referenced by ComputeUserObjectsThread::subdomainChanged(), and MooseObjectWarehouseBase< T >::updateVariableDependencyHelper().
getScalarVar()
const MooseVariableScalar * ScalarCoupleable::getScalarVar (const std::string & var_name, unsigned int comp) const protected inherited
Extract pointer to a scalar coupled variable.
Parameters
var_name Name of parameter desired
comp Component number of multiple coupled variables
Returns
Pointer to the desired variable
Definition at line 311 of file ScalarCoupleable.C.
{
  const auto var_name = _sc_parameters.checkForRename(var_name_in);
  const auto it = _coupled_scalar_vars.find(var_name);
  if (it != _coupled_scalar_vars.end())
  {
    const auto & entry = it->second;
    if (comp < entry.size())
      return entry[comp];
    else
      mooseError(_sc_name, ": Trying to get a non-existent component of variable '", var_name, "'");
  }
  else
    mooseError(_sc_name, ": Trying to get a non-existent variable '", var_name, "'");
}
Referenced by ScalarCoupleable::adCoupledScalarValue(), ScalarCoupleable::coupledMatrixTagScalarValue(), ScalarCoupleable::coupledScalar(), ScalarCoupleable::coupledScalarDot(), ScalarCoupleable::coupledScalarDotDot(), ScalarCoupleable::coupledScalarDotDotDu(), ScalarCoupleable::coupledScalarDotDotOld(), ScalarCoupleable::coupledScalarDotDu(), ScalarCoupleable::coupledScalarDotOld(), ScalarCoupleable::coupledScalarOrder(), ScalarCoupleable::coupledScalarValue(), ScalarCoupleable::coupledScalarValueOld(), ScalarCoupleable::coupledScalarValueOlder(), ScalarCoupleable::coupledVectorTagScalarValue(), ParsedAuxScalar::ParsedAuxScalar(), ParsedODEKernel::ParsedODEKernel(), and ParsedScalarRateCoefficient::ParsedScalarRateCoefficient().
getScalarVariableCoupleableMatrixTags()
const std::set< TagID > & ScalarCoupleable::getScalarVariableCoupleableMatrixTags () const inline inherited
Definition at line 55 of file ScalarCoupleable.h.
  {
    return _sc_coupleable_matrix_tags;
  }
getScalarVariableCoupleableVectorTags()
const std::set< TagID > & ScalarCoupleable::getScalarVariableCoupleableVectorTags () const inline inherited
Definition at line 50 of file ScalarCoupleable.h.
  {
    return _sc_coupleable_vector_tags;
  }
getVar() [1/2]
MooseVariable * Coupleable::getVar (const std::string & var_name, unsigned int comp) protected inherited
Extract pointer to a coupled variable.
Parameters
var_name Name of parameter desired
comp Component number of multiple coupled variables
Returns
Pointer to the desired variable
Definition at line 282 of file Coupleable.C.
{
  return const_cast<MooseVariable *>(getVarHelper<MooseVariable>(var_name, comp));
}
Referenced by ADSurfaceCharge::ADSurfaceCharge(), Coupleable::coupledDofValuesOld(), Coupleable::coupledDofValuesOlder(), Coupleable::coupledDot(), Coupleable::coupledDotDot(), Coupleable::coupledDotDotDu(), Coupleable::coupledDotDotOld(), Coupleable::coupledDotDu(), Coupleable::coupledDotOld(), Coupleable::coupledGradientDot(), Coupleable::coupledGradientDotDot(), Coupleable::coupledGradientOld(), Coupleable::coupledGradientOlder(), Coupleable::coupledGradientPreviousNL(), Coupleable::coupledMatrixTagValue(), NeighborCoupleable::coupledNeighborDofValues(), NeighborCoupleable::coupledNeighborDofValuesOld(), NeighborCoupleable::coupledNeighborDofValuesOlder(), NeighborCoupleable::coupledNeighborGradientOld(), NeighborCoupleable::coupledNeighborGradientOlder(), NeighborCoupleable::coupledNeighborSecond(), NeighborCoupleable::coupledNeighborValueDot(), NeighborCoupleable::coupledNeighborValueDotDu(), NeighborCoupleable::coupledNeighborValueOld(), NeighborCoupleable::coupledNeighborValueOlder(), Coupleable::coupledNodalDotDot(), Coupleable::coupledNodalDotDotOld(), Coupleable::coupledNodalDotOld(), Coupleable::coupledSecond(), Coupleable::coupledSecondOld(), Coupleable::coupledSecondOlder(), Coupleable::coupledSecondPreviousNL(), Coupleable::coupledValueLower(), Coupleable::coupledValueOld(), Coupleable::coupledValueOlder(), Coupleable::coupledValuePreviousNL(), Coupleable::coupledVectorTagGradient(), EconomouDielectricBC::EconomouDielectricBC(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), LymberopoulosElectronBC::LymberopoulosElectronBC(), NeumannCircuitVoltageMoles_KV::NeumannCircuitVoltageMoles_KV(), SakiyamaEnergySecondaryElectronBC::SakiyamaEnergySecondaryElectronBC(), SakiyamaSecondaryElectronBC::SakiyamaSecondaryElectronBC(), SecondaryElectronBC::SecondaryElectronBC(), SecondaryElectronEnergyBC::SecondaryElectronEnergyBC(), SideCurrent::SideCurrent(), and Coupleable::writableCoupledValue().
getVar() [2/2]
const MooseVariable * Coupleable::getVar (const std::string & var_name, unsigned int comp) const protected inherited
Extract pointer to a coupled variable.
Parameters
var_name Name of parameter desired
comp Component number of multiple coupled variables
Returns
Pointer to the desired variable
Definition at line 306 of file Coupleable.C.
{
  return getVarHelper<MooseVariable>(var_name, comp);
}
getVarHelper() [1/2]
template<typename T > T * Coupleable::getVarHelper (const std::string & var_name, unsigned int comp) protected inherited
Helper that can be used to retrieve a variable of arbitrary type T.
Definition at line 1709 of file Coupleable.h.
{
  const auto var_name = _c_parameters.checkForRename(var_name_in);
  auto name_to_use = var_name;
  // First check for supplied name
  if (!checkVar(var_name, comp, 0))
  {
    // See if there is an associated deprecated name that the user may have used instead
    auto it = _new_to_deprecated_coupled_vars.find(var_name);
    if (it == _new_to_deprecated_coupled_vars.end())
      return nullptr;
    else
    {
      auto deprecated_name = it->second;
      if (checkVar(deprecated_name, comp, 0))
        name_to_use = deprecated_name;
      else
        return nullptr;
    }
  }
  auto coupled_vars_it = _coupled_vars.find(name_to_use);
  mooseAssert(coupled_vars_it != _coupled_vars.end(),
              "Trying to get a coupled var " << name_to_use << " that doesn't exist");
  if (auto coupled_var = dynamic_cast<T *>(coupled_vars_it->second[comp]))
    return coupled_var;
  else
  {
    for (auto & var : _coupled_standard_moose_vars)
      if (var->name() == name_to_use)
        mooseError("The named variable is a standard variable, try a "
                   "'coupled[Value/Gradient/Dot/etc]...' function instead");
    for (auto & var : _coupled_vector_moose_vars)
      if (var->name() == name_to_use)
        mooseError("The named variable is a vector variable, try a "
                   "'coupledVector[Value/Gradient/Dot/etc]...' function instead");
    for (auto & var : _coupled_array_moose_vars)
      if (var->name() == name_to_use)
        mooseError("The named variable is an array variable, try a "
                   "'coupledArray[Value/Gradient/Dot/etc]...' function instead");
    for (auto & var : _coupled_standard_fv_moose_vars)
      if (var->name() == name_to_use)
        mooseError("The named variable is a finite volume variable, which the coupled[...] routine "
                   "used does not support. Try using the functor system routines instead.");
    mooseError(
        "Variable '", name_to_use, "' is of a different C++ type than you tried to fetch it as.");
  }
}
getVarHelper() [2/2]
template<typename T > const T * Coupleable::getVarHelper (const std::string & var_name, unsigned int comp) const protected inherited
Helper that that be used to retrieve a variable of arbitrary type T.
Definition at line 1763 of file Coupleable.h.
{
  return const_cast<Coupleable *>(this)->getVarHelper<T>(var_name, comp);
}
getVectorVar() [1/2]
VectorMooseVariable * Coupleable::getVectorVar (const std::string & var_name, unsigned int comp) protected inherited
Extract pointer to a coupled vector variable.
Parameters
var_name Name of parameter desired
comp Component number of multiple coupled variables
Returns
Pointer to the desired variable
Definition at line 288 of file Coupleable.C.
{
  auto * const var =
      const_cast<VectorMooseVariable *>(getVarHelper<VectorMooseVariable>(var_name, comp));
  if (_c_nodal && var && var->feType().family != LAGRANGE_VEC)
    mooseError(_c_name, ": Only LAGRANGE_VEC vector variables are defined at nodes");
  return var;
}
Referenced by Coupleable::adCoupledVectorDot(), Coupleable::adCoupledVectorGradient(), Coupleable::adCoupledVectorValue(), Coupleable::coupledCurl(), Coupleable::coupledCurlOld(), Coupleable::coupledCurlOlder(), Coupleable::coupledVectorDot(), Coupleable::coupledVectorDotDot(), Coupleable::coupledVectorDotDotDu(), Coupleable::coupledVectorDotDotOld(), Coupleable::coupledVectorDotDu(), Coupleable::coupledVectorDotOld(), Coupleable::coupledVectorGradient(), Coupleable::coupledVectorGradientOld(), Coupleable::coupledVectorGradientOlder(), NeighborCoupleable::coupledVectorNeighborGradient(), NeighborCoupleable::coupledVectorNeighborGradientOld(), NeighborCoupleable::coupledVectorNeighborGradientOlder(), Coupleable::coupledVectorValue(), Coupleable::coupledVectorValueOld(), and Coupleable::coupledVectorValueOlder().
getVectorVar() [2/2]
const VectorMooseVariable * Coupleable::getVectorVar (const std::string & var_name, unsigned int comp) const protected inherited
Extract pointer to a coupled vector variable.
Parameters
var_name Name of parameter desired
comp Component number of multiple coupled variables
Returns
Pointer to the desired variable
Definition at line 312 of file Coupleable.C.
{
  const auto * const var = getVarHelper<VectorMooseVariable>(var_name, comp);
  if (_c_nodal && var && var->feType().family != LAGRANGE_VEC)
    mooseError(_c_name, ": Only LAGRANGE_VEC vector variables are defined at nodes");
  return var;
}
getWritableCoupledVariables()
auto & Coupleable::getWritableCoupledVariables () const inline inherited
returns a reference to the set of writable coupled variables
Definition at line 122 of file Coupleable.h.
{ return _writable_coupled_variables[_c_tid]; }
Referenced by Coupleable::hasWritableCoupledVariables().
hasWritableCoupledVariables()
bool Coupleable::hasWritableCoupledVariables () const inline inherited
Checks whether the object has any writable coupled variables.
Definition at line 127 of file Coupleable.h.
{ return !getWritableCoupledVariables().empty(); }
Referenced by FEProblemBase::computeUserObjectsInternal().
isCoupled()
bool Coupleable::isCoupled (const std::string & var_name, unsigned int i = 0) const protected virtual inherited
Returns true if a variables has been coupled as name.
Parameters
var_name The name the kernel wants to refer to the variable as.
i By default 0, in general the index to test in a vector of MooseVariable pointers.
Returns
True if a coupled variable has the supplied name
Definition at line 123 of file Coupleable.C.
{
  const auto var_name = _c_parameters.checkForRename(var_name_in);
  auto it = _coupled_vars.find(var_name);
  if (it != _coupled_vars.end())
    return (i < it->second.size());
  else
  {
    // Make sure the user originally requested this value in the InputParameter syntax
    if (!_c_parameters.hasCoupledValue(var_name))
      mooseError(_c_name,
                 ": The coupled variable \"",
                 var_name,
                 "\" was never added to this object's "
                 "InputParameters, please double-check your "
                 "spelling");
    return false;
  }
}
Referenced by Coupleable::adCoupledNodalValue(), Coupleable::checkVar(), ElectricField::computeQpProperties(), ElectronEnergyTermRate::computeQpResidual(), DataRead::computeValue(), Coupleable::coupledComponents(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), EEDFRateConstant::EEDFRateConstant(), ElectronsFromIonization::ElectronsFromIonization(), and ElectricField::initQpStatefulProperties().
isCoupledConstant()
bool Coupleable::isCoupledConstant (const std::string & var_name) const protected virtual inherited
Returns true if a variable passed as a coupled value is really a constant.
Parameters
var_name The name the kernel wants to refer to the variable as.
Returns
True if the variable is actually a constant
Definition at line 146 of file Coupleable.C.
{
  return _c_parameters.hasDefaultCoupledValue(var_name);
}
Referenced by Coupleable::coupledName().
isCoupledScalar()
bool ScalarCoupleable::isCoupledScalar (const std::string & var_name, unsigned int i = 0) const protected inherited
Returns true if a variables has been coupled_as name.
Parameters
var_name The of the coupled variable
i By default 0, in general the index to test in a vector of MooseVariable pointers.
Definition at line 70 of file ScalarCoupleable.C.
{
  const auto var_name = _sc_parameters.checkForRename(var_name_in);
  auto it = _coupled_scalar_vars.find(var_name);
  if (it != _coupled_scalar_vars.end())
    return (i < it->second.size());
  else
  {
    // Make sure the user originally requested this value in the InputParameter syntax
    if (!_sc_parameters.hasCoupledValue(var_name))
      mooseError(_sc_name,
                 ": The coupled scalar variable \"",
                 var_name,
                 "\" was never added to this object's "
                 "InputParameters, please double-check "
                 "your spelling");
    return false;
  }
}
Referenced by ScalarCoupleable::adCoupledScalarValue(), Product1BodyScalar::computeQpJacobian(), Product2BodyScalar::computeQpJacobian(), Product3BodyScalar::computeQpJacobian(), EnergyTermScalar::computeQpOffDiagJacobian(), Reactant3BodyScalar::computeQpOffDiagJacobian(), EnergyTermScalar::computeQpResidual(), ScalarLinearInterpolation::computeValue(), ScalarSplineInterpolation::computeValue(), SuperelasticRateCoefficientScalar::computeValue(), ScalarCoupleable::coupledMatrixTagScalarValue(), ScalarCoupleable::coupledScalarOrder(), ScalarCoupleable::coupledScalarValue(), ScalarCoupleable::coupledScalarValueOld(), ScalarCoupleable::coupledScalarValueOlder(), and ScalarCoupleable::coupledVectorTagScalarValue().
requestStates()
template<typename T > void Coupleable::requestStates (const std::string & var_name, const TagName & tag_name, const unsigned int comp) private inherited
Method that may request additional solution states from the variable's system depending on the value of tag_name.
E.g. if the tag name corresponds to old or older variable solution values, then we must request more states
Definition at line 528 of file Coupleable.C.
{
  auto var =
      const_cast<MooseVariableField<T> *>(getVarHelper<MooseVariableField<T>>(var_name, comp));
  if (!var)
    mooseError(var_name, ": invalid variable name for tag coupling");
  auto & var_sys = var->sys();
  if (tag_name == Moose::OLD_SOLUTION_TAG)
    var_sys.needSolutionState(1);
  else if (tag_name == Moose::OLDER_SOLUTION_TAG)
    var_sys.needSolutionState(2);
}
validateExecutionerType()
void Coupleable::validateExecutionerType (const std::string & name, const std::string & fn_name) const protected inherited
Checks to make sure that the current Executioner has set "_is_transient" when old/older values are coupled in.
Parameters
name the name of the variable
fn_name The name of the function that called this method - used in the error message
Definition at line 1990 of file Coupleable.C.
{
  if (!_c_fe_problem.isTransient())
    mooseError(_c_name,
               ": Calling \"",
               fn_name,
               "\" on variable \"",
               name,
               "\" when using a \"Steady\" executioner is not allowed. This value is available "
               "only in transient simulations.");
}
Referenced by Coupleable::checkFuncType(), NeighborCoupleable::coupledArrayNeighborGradientOld(), NeighborCoupleable::coupledArrayNeighborGradientOlder(), NeighborCoupleable::coupledNeighborDofValuesOld(), NeighborCoupleable::coupledNeighborDofValuesOlder(), NeighborCoupleable::coupledNeighborGradientOld(), NeighborCoupleable::coupledNeighborGradientOlder(), NeighborCoupleable::coupledNeighborValueOld(), NeighborCoupleable::coupledNeighborValueOlder(), NeighborCoupleable::coupledVectorNeighborGradientOld(), and NeighborCoupleable::coupledVectorNeighborGradientOlder().
validParams()
static InputParameters NeighborCoupleableMooseVariableDependencyIntermediateInterface::validParams () inline static
Definition at line 28 of file NeighborCoupleableMooseVariableDependencyIntermediateInterface.h.
{ return emptyInputParameters(); }
Referenced by FVInterfaceKernel::validParams().
vectorTagDofValueHelper() [1/2]
template<typename T > const OutputTools< T >::VariableValue & Coupleable::vectorTagDofValueHelper (const std::string & var_name, const std::string & tag_name, unsigned int comp = 0) const private inherited
Generic helper method to get vector tag degree of freedom values based on tag name.
Definition at line 724 of file Coupleable.C.
{
  if (!_c_parameters.isParamValid(tag_param_name))
    mooseError("Tag name parameter '", tag_param_name, "' is invalid");
  const TagName tag_name = MooseUtils::toUpper(_c_parameters.get<TagName>(tag_param_name));
  const bool older_state_tag = _older_state_tags.count(tag_name);
  if (older_state_tag)
    // We may need to add solution states and create vector tags
    const_cast<Coupleable *>(this)->requestStates<T>(var_name, tag_name, comp);
  if (!_c_fe_problem.vectorTagExists(tag_name))
    mooseError("Tagged vector with tag name '", tag_name, "' does not exist");
  TagID tag = _c_fe_problem.getVectorTagID(tag_name);
  return vectorTagDofValueHelper<T>(var_name, tag, comp);
}
vectorTagDofValueHelper() [2/2]
template<typename T > const OutputTools< T >::VariableValue & Coupleable::vectorTagDofValueHelper (const std::string & var_name, TagID tag, unsigned int comp = 0) const private inherited
Generic helper method to get vector tag degree of freedom values based on tag ID.
Definition at line 708 of file Coupleable.C.
{
  const auto * var = getVarHelper<MooseVariableField<T>>(var_name, comp);
  if (!var)
    mooseError(var_name, ": invalid variable name for coupledVectorTagDofValue");
  checkFuncType(var_name, VarType::Ignore, FuncAge::Curr);
  const_cast<Coupleable *>(this)->addFEVariableCoupleableVectorTag(tag);
  return var->vectorTagDofValue(tag);
}
vectorTagValueHelper() [1/2]
template<typename T > const OutputTools< T >::VariableValue & Coupleable::vectorTagValueHelper (const std::string & var_names, const std::string & tag_name, unsigned int index = 0) const private inherited
Generic helper method to get vector tag values based on tag name.
Definition at line 546 of file Coupleable.C.
{
  if (!_c_parameters.isParamValid(tag_param_name))
    mooseError("Tag name parameter '", tag_param_name, "' is invalid");
  const TagName tag_name = MooseUtils::toUpper(_c_parameters.get<TagName>(tag_param_name));
  const bool older_state_tag = _older_state_tags.count(tag_name);
  if (older_state_tag)
    // We may need to add solution states and create vector tags
    const_cast<Coupleable *>(this)->requestStates<T>(var_names, tag_name, index);
  if (!_c_fe_problem.vectorTagExists(tag_name))
    mooseError("Tagged vector with tag name '", tag_name, "' does not exist");
  TagID tag = _c_fe_problem.getVectorTagID(tag_name);
  return vectorTagValueHelper<T>(var_names, tag, index);
}
vectorTagValueHelper() [2/2]
template<typename T > const OutputTools< T >::VariableValue & Coupleable::vectorTagValueHelper (const std::string & var_names, TagID tag, unsigned int index = 0) const private inherited
Generic helper method to get vector tag values based on tag ID.
Definition at line 502 of file Coupleable.C.
{
  const auto * const var = getVarHelper<MooseVariableField<T>>(var_names, index);
  if (!var)
    mooseError(var_names, ": invalid variable name for coupledVectorTagValue");
  checkFuncType(var_names, VarType::Ignore, FuncAge::Curr);
  if (!_c_fe_problem.vectorTagExists(tag))
    mooseError("Attempting to couple to vector tag with ID ",
               tag,
               "in ",
               _c_name,
               ", but a vector tag with that ID does not exist");
  const_cast<Coupleable *>(this)->addFEVariableCoupleableVectorTag(tag);
  if (_c_nodal)
    return var->nodalVectorTagValue(tag);
  else
    return var->vectorTagValue(tag);
}
writableCoupledValue()
VariableValue & Coupleable::writableCoupledValue (const std::string & var_name, unsigned int comp = 0) protected virtual inherited
Returns a writable reference to a coupled variable for writing to multiple AuxVariables from a single AuxKernel or a UserObject.
Only one object can obtain a writable reference in a simulation.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
See also
Kernel::value
Definition at line 892 of file Coupleable.C.
{
  mooseDeprecated("Coupleable::writableCoupledValue is deprecated, please use "
                  "Coupleable::writableVariable instead. ");
  // check if the variable exists
  auto * const var = getVar(var_name, comp);
  if (!var)
    mooseError(
        "Unable to create a writable reference for '", var_name, "', is it a constant expression?");
  // is the requested variable an AuxiliaryVariable?
  if (!_c_fe_problem.getAuxiliarySystem().hasVariable(var->name()))
    mooseError(
        "'", var->name(), "' must be an auxiliary variable in Coupleable::writableCoupledValue");
  // check that the variable type (elemental/nodal) is compatible with the object type
  const auto * aux = dynamic_cast<const AuxKernel *>(this);
  if (!aux)
    mooseError("writableCoupledValue() can only be called from AuxKernels, but '",
               _obj->name(),
               "' is not an AuxKernel.");
  if (!aux->isNodal() && var->isNodal())
    mooseError("The elemental AuxKernel '",
               _obj->name(),
               "' cannot obtain a writable reference to the nodal variable '",
               var->name(),
               "'.");
  // make sure only one object can access a variable
  checkWritableVar(var);
  return const_cast<VariableValue &>(coupledValue(var_name, comp));
}
writableVariable()
MooseWritableVariable & Coupleable::writableVariable (const std::string & var_name, unsigned int comp = 0) protected inherited
Returns a writable MooseVariable object for a nodal or elemental variable.
Use var.setNodalValue(val[, idx]) in both cases (!) to set the solution DOF values. Only one object can obtain a writable reference in a simulation. Note that the written values will not ba available in the same system loop! E.g. values written using this API by a nodal AuxKernel will not be updated for other nodal AuxKernels during the same iteration over all nodes.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a MooseWritableVariable for the coupled variable
See also
Kernel::value
Definition at line 858 of file Coupleable.C.
{
  auto * var = getVarHelper<MooseWritableVariable>(var_name, comp);
  const auto * aux = dynamic_cast<const AuxKernel *>(this);
  const auto * euo = dynamic_cast<const ElementUserObject *>(this);
  const auto * nuo = dynamic_cast<const NodalUserObject *>(this);
  if (!aux && !euo && !nuo)
    mooseError("writableVariable() can only be called from AuxKernels, ElementUserObjects, or "
               "NodalUserObjects. '",
               _obj->name(),
               "' is neither of those.");
  if (aux && !aux->isNodal() && var->isNodal())
    mooseError("The elemental AuxKernel '",
               _obj->name(),
               "' cannot obtain a writable reference to the nodal variable '",
               var->name(),
               "'.");
  if (euo && var->isNodal())
    mooseError("The ElementUserObject '",
               _obj->name(),
               "' cannot obtain a writable reference to the nodal variable '",
               var->name(),
               "'.");
  // make sure only one object can access a variable
  checkWritableVar(var);
  return *var;
}
Member Data Documentation
_ad_default_gradient
MooseArray<ADRealVectorValue> Coupleable::_ad_default_gradient mutable protected inherited
This will always be zero because the default values for optionally coupled variables is always constant.
Definition at line 1374 of file Coupleable.h.
Referenced by Coupleable::getADDefaultGradient().
_ad_default_second
MooseArray<ADRealTensorValue> Coupleable::_ad_default_second mutable protected inherited
This will always be zero because the default values for optionally coupled variables is always constant.
Definition at line 1383 of file Coupleable.h.
Referenced by Coupleable::getADDefaultSecond().
_ad_default_value
std::unordered_map<std::string, std::unique_ptr<MooseArray<DualReal> > > Coupleable::_ad_default_value mutable protected inherited
Will hold the default value for optional coupled variables for automatic differentiation.
Definition at line 1351 of file Coupleable.h.
Referenced by Coupleable::getADDefaultValue().
_ad_default_vector_gradient
MooseArray<ADRealTensorValue> Coupleable::_ad_default_vector_gradient mutable protected inherited
This will always be zero because the default values for optionally coupled vector variables is always constant.
Definition at line 1377 of file Coupleable.h.
Referenced by Coupleable::getADDefaultVectorGradient().
_ad_default_vector_value
std::unordered_map<std::string, std::unique_ptr<MooseArray<ADRealVectorValue> > > Coupleable::_ad_default_vector_value mutable protected inherited
Will hold the default value for optional vector coupled variables for automatic differentiation.
Definition at line 1362 of file Coupleable.h.
Referenced by Coupleable::getADDefaultVectorValue().
_ad_grad_zero
const MooseArray<ADRealVectorValue>& Coupleable::_ad_grad_zero protected inherited
Definition at line 1392 of file Coupleable.h.
Referenced by Coupleable::adZeroGradient(), and Coupleable::genericZeroGradient().
_ad_second_zero
const MooseArray<ADRealTensorValue>& Coupleable::_ad_second_zero protected inherited
Definition at line 1399 of file Coupleable.h.
Referenced by Coupleable::adZeroSecond(), and Coupleable::genericZeroSecond().
_ad_zero
const MooseArray<DualReal>& Coupleable::_ad_zero protected inherited
Definition at line 1388 of file Coupleable.h.
Referenced by Coupleable::adZeroValue(), and Coupleable::genericZeroValue().
_c_allow_element_to_nodal_coupling
const bool Coupleable::_c_allow_element_to_nodal_coupling protected inherited
Definition at line 1341 of file Coupleable.h.
Referenced by Coupleable::checkVar().
_c_coupled_scalar_vars
std::unordered_map<std::string, std::vector<MooseVariableScalar *> > Coupleable::_c_coupled_scalar_vars private inherited
Scalar variables coupled into this object (for error checking)
Definition at line 1688 of file Coupleable.h.
Referenced by Coupleable::checkVar(), and Coupleable::Coupleable().
_c_fe_problem
FEProblemBase& Coupleable::_c_fe_problem protected inherited
Definition at line 1308 of file Coupleable.h.
Referenced by Coupleable::coupledGradientPreviousNL(), Coupleable::coupledMatrixTagValue(), Coupleable::coupledMatrixTagValues(), Coupleable::coupledNodalValuePreviousNL(), Coupleable::coupledSecondPreviousNL(), Coupleable::coupledValuePreviousNL(), Coupleable::coupledVectorTagArrayGradient(), Coupleable::coupledVectorTagArrayGradients(), Coupleable::coupledVectorTagArrayValues(), Coupleable::coupledVectorTagDofValues(), Coupleable::coupledVectorTagGradient(), Coupleable::coupledVectorTagGradients(), Coupleable::coupledVectorTagValues(), Coupleable::validateExecutionerType(), Coupleable::vectorTagDofValueHelper(), Coupleable::vectorTagValueHelper(), and Coupleable::writableCoupledValue().
_c_is_implicit
bool Coupleable::_c_is_implicit protected inherited
True if implicit value is required.
Definition at line 1338 of file Coupleable.h.
Referenced by Coupleable::adCoupledDofValues(), Coupleable::adCoupledGradient(), Coupleable::adCoupledGradientDot(), Coupleable::adCoupledLowerValue(), NeighborCoupleable::adCoupledNeighborGradient(), NeighborCoupleable::adCoupledNeighborValue(), NeighborCoupleable::adCoupledNeighborValueDot(), Coupleable::adCoupledNodalValue(), Coupleable::adCoupledSecond(), Coupleable::adCoupledValue(), Coupleable::adCoupledVectorGradient(), NeighborCoupleable::adCoupledVectorNeighborValue(), Coupleable::adCoupledVectorValue(), Coupleable::checkFuncType(), Coupleable::coupledArrayDofValues(), Coupleable::coupledArrayGradient(), Coupleable::coupledArrayGradientOld(), NeighborCoupleable::coupledArrayNeighborGradient(), NeighborCoupleable::coupledArrayNeighborGradientOld(), NeighborCoupleable::coupledArrayNeighborGradientOlder(), NeighborCoupleable::coupledArrayNeighborValue(), Coupleable::coupledArrayValue(), Coupleable::coupledArrayValueOld(), Coupleable::coupledCurl(), Coupleable::coupledCurlOld(), Coupleable::coupledDofValues(), Coupleable::coupledDofValuesOld(), Coupleable::coupledGradient(), Coupleable::coupledGradientOld(), NeighborCoupleable::coupledNeighborDofValues(), NeighborCoupleable::coupledNeighborDofValuesOld(), NeighborCoupleable::coupledNeighborDofValuesOlder(), NeighborCoupleable::coupledNeighborGradient(), NeighborCoupleable::coupledNeighborGradientOld(), NeighborCoupleable::coupledNeighborGradientOlder(), NeighborCoupleable::coupledNeighborSecond(), NeighborCoupleable::coupledNeighborValue(), NeighborCoupleable::coupledNeighborValueOld(), NeighborCoupleable::coupledNeighborValueOlder(), Coupleable::coupledNodalValue(), Coupleable::coupledNodalValueOld(), Coupleable::coupledSecond(), Coupleable::coupledSecondOld(), Coupleable::coupledValue(), Coupleable::coupledValueLower(), Coupleable::coupledValueOld(), Coupleable::coupledVectorGradient(), Coupleable::coupledVectorGradientOld(), NeighborCoupleable::coupledVectorNeighborGradient(), NeighborCoupleable::coupledVectorNeighborGradientOld(), NeighborCoupleable::coupledVectorNeighborGradientOlder(), Coupleable::coupledVectorValue(), and Coupleable::coupledVectorValueOld().
_c_name
const std::string& Coupleable::_c_name protected inherited
The name of the object this interface is part of.
Definition at line 1303 of file Coupleable.h.
Referenced by Coupleable::checkFuncType(), Coupleable::checkVar(), Coupleable::coupledName(), Coupleable::coupledNodalValue(), Coupleable::coupledNodalValueOld(), Coupleable::coupledNodalValueOlder(), Coupleable::coupledValueLower(), Coupleable::coupledVectorTagArrayGradient(), Coupleable::coupledVectorTagGradient(), Coupleable::getVectorVar(), Coupleable::isCoupled(), Coupleable::validateExecutionerType(), and Coupleable::vectorTagValueHelper().
_c_nodal
bool Coupleable::_c_nodal protected inherited
True if we provide coupling to nodal values.
Definition at line 1335 of file Coupleable.h.
Referenced by Coupleable::adCoupledDot(), Coupleable::adCoupledDotDot(), Coupleable::adCoupledLowerValue(), Coupleable::adCoupledNodalValue(), Coupleable::adCoupledValue(), Coupleable::adCoupledVectorDot(), Coupleable::adCoupledVectorValue(), Coupleable::checkFuncType(), Coupleable::checkVar(), Coupleable::coupledArrayDot(), Coupleable::coupledArrayDotDot(), Coupleable::coupledArrayDotDotOld(), Coupleable::coupledArrayDotDu(), Coupleable::coupledArrayDotOld(), Coupleable::coupledArrayValue(), Coupleable::coupledArrayValueOld(), Coupleable::coupledArrayValueOlder(), Coupleable::coupledDot(), Coupleable::coupledDotDot(), Coupleable::coupledDotDotDu(), Coupleable::coupledDotDotOld(), Coupleable::coupledDotDu(), Coupleable::coupledDotOld(), Coupleable::coupledMatrixTagValue(), Coupleable::coupledValue(), Coupleable::coupledValueLower(), Coupleable::coupledValueOld(), Coupleable::coupledValueOlder(), Coupleable::coupledValuePreviousNL(), Coupleable::coupledVectorValue(), Coupleable::getVectorVar(), and Coupleable::vectorTagValueHelper().
_c_parameters
const InputParameters& Coupleable::_c_parameters protected inherited
Definition at line 1300 of file Coupleable.h.
Referenced by Coupleable::checkVar(), Coupleable::Coupleable(), Coupleable::coupledComponents(), Coupleable::coupledMatrixTagValue(), Coupleable::coupledMatrixTagValues(), Coupleable::coupledVectorTagArrayGradient(), Coupleable::coupledVectorTagArrayGradients(), Coupleable::coupledVectorTagArrayValues(), Coupleable::coupledVectorTagDofValues(), Coupleable::coupledVectorTagGradient(), Coupleable::coupledVectorTagGradients(), Coupleable::coupledVectorTagValues(), Coupleable::getADDefaultValue(), Coupleable::getADDefaultVectorValue(), Coupleable::getDefaultArrayValue(), Coupleable::getDefaultValue(), Coupleable::getDefaultVectorValue(), Coupleable::getVarHelper(), Coupleable::isCoupled(), Coupleable::isCoupledConstant(), Coupleable::vectorTagDofValueHelper(), and Coupleable::vectorTagValueHelper().
_c_sys
const SystemBase* const Coupleable::_c_sys protected inherited
Pointer to the system object if the moose object this is an interface for has one.
Definition at line 1311 of file Coupleable.h.
Referenced by Coupleable::coupled().
_c_tid
THREAD_ID Coupleable::_c_tid protected inherited
Thread ID of the thread using this object.
Definition at line 1344 of file Coupleable.h.
Referenced by Coupleable::checkWritableVar(), Coupleable::Coupleable(), and Coupleable::getWritableCoupledVariables().
_c_type
const std::string& Coupleable::_c_type protected inherited
The type of the object this interface is part of.
Definition at line 1305 of file Coupleable.h.
_coupleable_max_qps
unsigned int Coupleable::_coupleable_max_qps private inherited
Maximum qps for any element in this system.
Definition at line 1682 of file Coupleable.h.
Referenced by Coupleable::coupledArrayDotDu(), Coupleable::coupledCurl(), Coupleable::coupledCurlOld(), Coupleable::coupledCurlOlder(), Coupleable::coupledDot(), Coupleable::coupledDotDot(), Coupleable::coupledDotDotDu(), Coupleable::coupledDotDotOld(), Coupleable::coupledDotDu(), Coupleable::coupledDotOld(), Coupleable::coupledGradient(), Coupleable::coupledGradientDot(), Coupleable::coupledGradientDotDot(), Coupleable::coupledGradientOld(), Coupleable::coupledGradientOlder(), Coupleable::coupledGradientPreviousNL(), Coupleable::coupledNodalDotDot(), Coupleable::coupledNodalDotDotOld(), Coupleable::coupledNodalDotOld(), Coupleable::coupledSecond(), Coupleable::coupledSecondOld(), Coupleable::coupledSecondOlder(), Coupleable::coupledSecondPreviousNL(), Coupleable::coupledVectorDot(), Coupleable::coupledVectorDotDot(), Coupleable::coupledVectorDotDotDu(), Coupleable::coupledVectorDotDotOld(), Coupleable::coupledVectorDotDu(), Coupleable::coupledVectorDotOld(), Coupleable::coupledVectorGradient(), Coupleable::coupledVectorGradientOld(), Coupleable::coupledVectorGradientOlder(), Coupleable::getADDefaultGradient(), Coupleable::getADDefaultSecond(), Coupleable::getADDefaultValue(), Coupleable::getADDefaultVectorGradient(), Coupleable::getADDefaultVectorValue(), Coupleable::getDefaultArrayValue(), Coupleable::getDefaultValue(), and Coupleable::getDefaultVectorValue().
_coupleable_neighbor
bool Coupleable::_coupleable_neighbor protected inherited
Whether or not this object is a "neighbor" object: ie all of it's coupled values should be neighbor values.
Definition at line 1604 of file Coupleable.h.
Referenced by Coupleable::adCoupledDofValues(), Coupleable::adCoupledDot(), Coupleable::adCoupledDotDot(), Coupleable::adCoupledGradient(), Coupleable::adCoupledGradientDot(), Coupleable::adCoupledNodalValue(), Coupleable::adCoupledSecond(), Coupleable::adCoupledValue(), Coupleable::adCoupledVectorDot(), Coupleable::adCoupledVectorGradient(), Coupleable::adCoupledVectorValue(), Coupleable::coupledArrayDofValues(), Coupleable::coupledArrayDot(), Coupleable::coupledArrayDotDot(), Coupleable::coupledArrayDotDotOld(), Coupleable::coupledArrayDotDu(), Coupleable::coupledArrayDotOld(), Coupleable::coupledArrayGradient(), Coupleable::coupledArrayGradientOld(), Coupleable::coupledArrayGradientOlder(), Coupleable::coupledArrayValue(), Coupleable::coupledArrayValueOld(), Coupleable::coupledArrayValueOlder(), Coupleable::coupledCurl(), Coupleable::coupledCurlOld(), Coupleable::coupledCurlOlder(), Coupleable::coupledDofValues(), Coupleable::coupledDofValuesOld(), Coupleable::coupledDofValuesOlder(), Coupleable::coupledDot(), Coupleable::coupledDotDot(), Coupleable::coupledDotDotDu(), Coupleable::coupledDotDotOld(), Coupleable::coupledDotDu(), Coupleable::coupledDotOld(), Coupleable::coupledGradient(), Coupleable::coupledGradientDot(), Coupleable::coupledGradientDotDot(), Coupleable::coupledGradientOld(), Coupleable::coupledGradientOlder(), Coupleable::coupledGradientPreviousNL(), Coupleable::coupledNodalDot(), Coupleable::coupledNodalDotDot(), Coupleable::coupledNodalDotDotOld(), Coupleable::coupledNodalDotOld(), Coupleable::coupledNodalValue(), Coupleable::coupledNodalValueOld(), Coupleable::coupledNodalValueOlder(), Coupleable::coupledNodalValuePreviousNL(), Coupleable::coupledSecond(), Coupleable::coupledSecondOld(), Coupleable::coupledSecondOlder(), Coupleable::coupledSecondPreviousNL(), Coupleable::coupledValue(), Coupleable::coupledValueLower(), Coupleable::coupledValueOld(), Coupleable::coupledValueOlder(), Coupleable::coupledValuePreviousNL(), Coupleable::coupledVectorDot(), Coupleable::coupledVectorDotDot(), Coupleable::coupledVectorDotDotDu(), Coupleable::coupledVectorDotDotOld(), Coupleable::coupledVectorDotDu(), Coupleable::coupledVectorDotOld(), Coupleable::coupledVectorGradient(), Coupleable::coupledVectorGradientOld(), Coupleable::coupledVectorGradientOlder(), Coupleable::coupledVectorValue(), Coupleable::coupledVectorValueOld(), and Coupleable::coupledVectorValueOlder().
_coupled_array_moose_vars
std::vector<ArrayMooseVariable *> Coupleable::_coupled_array_moose_vars protected inherited
Vector of array coupled variables.
Definition at line 1326 of file Coupleable.h.
Referenced by Coupleable::Coupleable(), Coupleable::getCoupledArrayMooseVars(), and Coupleable::getVarHelper().
_coupled_moose_scalar_vars
std::vector<MooseVariableScalar *> ScalarCoupleable::_coupled_moose_scalar_vars private inherited
Vector of coupled variables.
Definition at line 286 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::getCoupledMooseScalarVars(), and ScalarCoupleable::ScalarCoupleable().
_coupled_moose_vars
std::vector<MooseVariableFieldBase *> Coupleable::_coupled_moose_vars protected inherited
Vector of all coupled variables.
Definition at line 1317 of file Coupleable.h.
Referenced by Coupleable::Coupleable(), ElementValueSampler::ElementValueSampler(), PointVariableSamplerBase::execute(), ElementValueSampler::execute(), SideValueSampler::execute(), Coupleable::getCoupledMooseVars(), PointVariableSamplerBase::initialize(), InterfaceUserObject::InterfaceUserObject(), NodalValueSampler::NodalValueSampler(), PointVariableSamplerBase::PointVariableSamplerBase(), and SideValueSampler::SideValueSampler().
_coupled_scalar_vars
std::unordered_map<std::string, std::vector<MooseVariableScalar *> > ScalarCoupleable::_coupled_scalar_vars private inherited
Coupled vars whose values we provide.
Definition at line 277 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::coupledScalarComponents(), ScalarCoupleable::getScalarVar(), ScalarCoupleable::isCoupledScalar(), and ScalarCoupleable::ScalarCoupleable().
_coupled_standard_fv_moose_vars
std::vector<MooseVariableFV<Real> *> Coupleable::_coupled_standard_fv_moose_vars protected inherited
Vector of standard finite volume coupled variables.
Definition at line 1329 of file Coupleable.h.
Referenced by Coupleable::Coupleable(), ElementValueSampler::execute(), and Coupleable::getVarHelper().
_coupled_standard_moose_vars
std::vector<MooseVariable *> Coupleable::_coupled_standard_moose_vars protected inherited
Vector of standard coupled variables.
Definition at line 1320 of file Coupleable.h.
Referenced by Coupleable::Coupleable(), ElementValueSampler::execute(), NodalValueSampler::execute(), Coupleable::getCoupledStandardMooseVars(), and Coupleable::getVarHelper().
_coupled_vars
std::unordered_map<std::string, std::vector<MooseVariableFieldBase *> > Coupleable::_coupled_vars protected inherited
Coupled vars whose values we provide.
Definition at line 1314 of file Coupleable.h.
Referenced by Coupleable::checkVar(), Coupleable::Coupleable(), Coupleable::coupledComponents(), Coupleable::getCoupledVars(), Coupleable::getVarHelper(), and Coupleable::isCoupled().
_coupled_vector_moose_vars
std::vector<VectorMooseVariable *> Coupleable::_coupled_vector_moose_vars protected inherited
Vector of vector coupled variables.
Definition at line 1323 of file Coupleable.h.
Referenced by Coupleable::Coupleable(), Coupleable::getCoupledVectorMooseVars(), and Coupleable::getVarHelper().
_default_array_curl
ArrayVariableCurl Coupleable::_default_array_curl protected inherited
This will always be zero because the default values for optionally coupled variables is always constant.
Definition at line 1429 of file Coupleable.h.
_default_array_gradient
ArrayVariableGradient Coupleable::_default_array_gradient protected inherited
This will always be zero because the default values for optionally coupled variables is always constant.
Definition at line 1426 of file Coupleable.h.
Referenced by Coupleable::coupledArrayGradient(), Coupleable::coupledArrayGradientOld(), and Coupleable::coupledArrayGradientOlder().
_default_array_value
std::unordered_map<std::string, std::unique_ptr<ArrayVariableValue> > Coupleable::_default_array_value mutable protected inherited
Will hold the default value for optional array coupled variables.
Definition at line 1358 of file Coupleable.h.
Referenced by Coupleable::getDefaultArrayValue().
_default_array_value_zero
ArrayVariableValue Coupleable::_default_array_value_zero protected inherited
This will always be zero because the default values for optionally coupled variables is always constant and this is used for time derivative info.
Definition at line 1423 of file Coupleable.h.
Referenced by Coupleable::coupledArrayDot(), Coupleable::coupledArrayDotDot(), Coupleable::coupledArrayDotDotOld(), and Coupleable::coupledArrayDotOld().
_default_gradient
VariableGradient Coupleable::_default_gradient mutable protected inherited
This will always be zero because the default values for optionally coupled variables is always constant.
Definition at line 1371 of file Coupleable.h.
Referenced by Coupleable::coupledGradient(), Coupleable::coupledGradientDot(), Coupleable::coupledGradientDotDot(), Coupleable::coupledGradientOld(), Coupleable::coupledGradientOlder(), and Coupleable::coupledGradientPreviousNL().
_default_second
VariableSecond Coupleable::_default_second mutable protected inherited
This will always be zero because the default values for optionally coupled variables is always constant.
Definition at line 1380 of file Coupleable.h.
Referenced by Coupleable::coupledSecond(), Coupleable::coupledSecondOld(), Coupleable::coupledSecondOlder(), and Coupleable::coupledSecondPreviousNL().
_default_value
std::unordered_map<std::string, std::vector<std::unique_ptr<VariableValue> > > Coupleable::_default_value mutable protected inherited
Will hold the default value for optional coupled variables.
Definition at line 1348 of file Coupleable.h.
Referenced by Coupleable::getDefaultValue().
_default_value_zero
VariableValue Coupleable::_default_value_zero mutable protected inherited
This will always be zero because the default values for optionally coupled variables is always constant and this is used for time derivative info.
Definition at line 1368 of file Coupleable.h.
Referenced by Coupleable::coupledArrayDotDu(), Coupleable::coupledDot(), Coupleable::coupledDotDot(), Coupleable::coupledDotDotDu(), Coupleable::coupledDotDotOld(), Coupleable::coupledDotDu(), Coupleable::coupledDotOld(), Coupleable::coupledNodalDotDot(), Coupleable::coupledNodalDotDotOld(), Coupleable::coupledNodalDotOld(), Coupleable::coupledVectorDotDotDu(), and Coupleable::coupledVectorDotDu().
_default_vector_curl
VectorVariableCurl Coupleable::_default_vector_curl mutable protected inherited
This will always be zero because the default values for optionally coupled variables is always constant.
Definition at line 1417 of file Coupleable.h.
Referenced by Coupleable::coupledCurl(), Coupleable::coupledCurlOld(), and Coupleable::coupledCurlOlder().
_default_vector_gradient
VectorVariableGradient Coupleable::_default_vector_gradient mutable protected inherited
This will always be zero because the default values for optionally coupled variables is always constant.
Definition at line 1414 of file Coupleable.h.
Referenced by Coupleable::coupledVectorGradient(), Coupleable::coupledVectorGradientOld(), and Coupleable::coupledVectorGradientOlder().
_default_vector_value
std::unordered_map<std::string, std::unique_ptr<VectorVariableValue> > Coupleable::_default_vector_value mutable protected inherited
Will hold the default value for optional vector coupled variables.
Definition at line 1355 of file Coupleable.h.
Referenced by Coupleable::getDefaultVectorValue().
_default_vector_value_zero
VectorVariableValue Coupleable::_default_vector_value_zero mutable protected inherited
This will always be zero because the default values for optionally coupled variables is always constant and this is used for time derivative info.
Definition at line 1411 of file Coupleable.h.
Referenced by Coupleable::coupledVectorDot(), Coupleable::coupledVectorDotDot(), Coupleable::coupledVectorDotDotOld(), and Coupleable::coupledVectorDotOld().
_dof_indices
std::vector<libMesh::dof_id_type> MooseVariableDependencyInterface::_dof_indices private inherited
A container for holding dof indices in order to avoid constant memory reallocation.
Definition at line 86 of file MooseVariableDependencyInterface.h.
Referenced by MooseVariableDependencyInterface::checkVariables().
_dual_default_value
std::unordered_map<std::string, std::unique_ptr<ADVariableValue> > ScalarCoupleable::_dual_default_value mutable private inherited
Will hold the default AD value for optional coupled scalar variables.
Definition at line 283 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::getADDefaultValue().
_fe_coupleable_matrix_tags
std::set<TagID> Coupleable::_fe_coupleable_matrix_tags private inherited
Definition at line 1692 of file Coupleable.h.
Referenced by Coupleable::addFEVariableCoupleableMatrixTag(), and Coupleable::getFEVariableCoupleableMatrixTags().
_fe_coupleable_vector_tags
std::set<TagID> Coupleable::_fe_coupleable_vector_tags private inherited
Definition at line 1690 of file Coupleable.h.
Referenced by Coupleable::addFEVariableCoupleableVectorTag(), and Coupleable::getFEVariableCoupleableVectorTags().
_grad_phi_zero
const VariablePhiGradient& Coupleable::_grad_phi_zero protected inherited
Zero gradient of trial function.
Definition at line 1395 of file Coupleable.h.
_grad_zero
const VariableGradient& Coupleable::_grad_zero protected inherited
Zero gradient of a variable.
Definition at line 1391 of file Coupleable.h.
Referenced by Coupleable::genericZeroGradient().
_is_fv
const bool Coupleable::_is_fv private inherited
Whether the MooseObject is a finite volume object.
Definition at line 1695 of file Coupleable.h.
Referenced by Coupleable::checkVar().
_moose_variable_dependencies
std::set<MooseVariableFieldBase *> MooseVariableDependencyInterface::_moose_variable_dependencies private inherited
Definition at line 83 of file MooseVariableDependencyInterface.h.
Referenced by MooseVariableDependencyInterface::addMooseVariableDependency(), MooseVariableDependencyInterface::checkAllVariables(), and MooseVariableDependencyInterface::getMooseVariableDependencies().
_neighbor_nodal
bool NeighborCoupleable::_neighbor_nodal protected inherited
Definition at line 129 of file NeighborCoupleable.h.
Referenced by NeighborCoupleable::adCoupledNeighborGradient(), NeighborCoupleable::adCoupledNeighborValue(), NeighborCoupleable::adCoupledNeighborValueDot(), NeighborCoupleable::adCoupledVectorNeighborValue(), NeighborCoupleable::coupledArrayNeighborGradient(), NeighborCoupleable::coupledArrayNeighborGradientOld(), NeighborCoupleable::coupledArrayNeighborGradientOlder(), NeighborCoupleable::coupledArrayNeighborValue(), NeighborCoupleable::coupledNeighborDofValues(), NeighborCoupleable::coupledNeighborDofValuesOld(), NeighborCoupleable::coupledNeighborDofValuesOlder(), NeighborCoupleable::coupledNeighborGradient(), NeighborCoupleable::coupledNeighborGradientOld(), NeighborCoupleable::coupledNeighborGradientOlder(), NeighborCoupleable::coupledNeighborSecond(), NeighborCoupleable::coupledNeighborValue(), NeighborCoupleable::coupledNeighborValueDot(), NeighborCoupleable::coupledNeighborValueDotDu(), NeighborCoupleable::coupledNeighborValueOld(), NeighborCoupleable::coupledNeighborValueOlder(), NeighborCoupleable::coupledVectorNeighborGradient(), NeighborCoupleable::coupledVectorNeighborGradientOld(), and NeighborCoupleable::coupledVectorNeighborGradientOlder().
_new_to_deprecated_coupled_vars
const std::unordered_map<std::string, std::string>& Coupleable::_new_to_deprecated_coupled_vars protected inherited
map from new to deprecated variable names
Definition at line 1332 of file Coupleable.h.
Referenced by Coupleable::getVarHelper().
_obj
const MooseObject* const Coupleable::_obj private inherited
Definition at line 1697 of file Coupleable.h.
Referenced by Coupleable::checkVar(), Coupleable::checkWritableVar(), Coupleable::Coupleable(), Coupleable::coupled(), Coupleable::getDefaultValue(), Coupleable::writableCoupledValue(), and Coupleable::writableVariable().
_older_state_tags
const std::set<std::string> Coupleable::_older_state_tags private inherited
Initial value:
= {Moose::OLD_SOLUTION_TAG,
                                                   Moose::OLDER_SOLUTION_TAG}
vector tag names for which we need to request older solution states from the system
Definition at line 1700 of file Coupleable.h.
Referenced by Coupleable::vectorTagDofValueHelper(), and Coupleable::vectorTagValueHelper().
_optional_var_index
std::unordered_map<std::string, std::vector<unsigned int> > Coupleable::_optional_var_index private inherited
Unique indices for optionally coupled vars that weren't provided.
Definition at line 1685 of file Coupleable.h.
Referenced by Coupleable::Coupleable(), and Coupleable::coupled().
_phi_zero
const VariablePhiValue& Coupleable::_phi_zero protected inherited
Definition at line 1387 of file Coupleable.h.
_point_zero
const Point& ScalarCoupleable::_point_zero protected inherited
Zero point.
Definition at line 233 of file ScalarCoupleable.h.
Referenced by FunctionDT::computeDT(), FunctionScalarAux::computeValue(), and FunctionScalarIC::value().
_real_zero
const Real& ScalarCoupleable::_real_zero protected inherited
Scalar zero.
Definition at line 227 of file ScalarCoupleable.h.
_sc_coupleable_matrix_tags
std::set<TagID> ScalarCoupleable::_sc_coupleable_matrix_tags mutable private inherited
The scalar coupleable matrix tags.
Definition at line 294 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::coupledMatrixTagScalarValue(), and ScalarCoupleable::getScalarVariableCoupleableMatrixTags().
_sc_coupleable_vector_tags
std::set<TagID> ScalarCoupleable::_sc_coupleable_vector_tags mutable private inherited
The scalar coupleable vector tags.
Definition at line 292 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::coupledVectorTagScalarValue(), and ScalarCoupleable::getScalarVariableCoupleableVectorTags().
_sc_coupled_vars
std::unordered_map<std::string, std::vector<MooseVariableFieldBase *> > ScalarCoupleable::_sc_coupled_vars private inherited
Field variables coupled into this object (for error checking)
Definition at line 289 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::checkVar(), and ScalarCoupleable::ScalarCoupleable().
_sc_fe_problem
FEProblemBase& ScalarCoupleable::_sc_fe_problem protected inherited
Definition at line 221 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::coupledScalarOrder(), ScalarCoupleable::coupledVectorTagScalarValue(), ScalarCoupleable::getADDefaultValue(), ScalarCoupleable::getDefaultValue(), and ScalarCoupleable::validateExecutionerType().
_sc_is_implicit
const bool ScalarCoupleable::_sc_is_implicit private inherited
True if implicit value is required.
Definition at line 274 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::adCoupledScalarValue(), ScalarCoupleable::coupledScalarValue(), ScalarCoupleable::coupledScalarValueOld(), and ScalarCoupleable::coupledScalarValueOlder().
_sc_name
const std::string& ScalarCoupleable::_sc_name private inherited
The name of the object this interface is part of.
Definition at line 271 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::checkVar(), ScalarCoupleable::coupledScalarComponents(), ScalarCoupleable::coupledVectorTagScalarValue(), ScalarCoupleable::getScalarVar(), ScalarCoupleable::isCoupledScalar(), ScalarCoupleable::ScalarCoupleable(), and ScalarCoupleable::validateExecutionerType().
_sc_parameters
const InputParameters& ScalarCoupleable::_sc_parameters private inherited
Definition at line 268 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::checkVar(), ScalarCoupleable::coupledScalarComponents(), ScalarCoupleable::getADDefaultValue(), ScalarCoupleable::getDefaultValue(), ScalarCoupleable::getScalarVar(), ScalarCoupleable::isCoupledScalar(), and ScalarCoupleable::ScalarCoupleable().
_sc_tid
const THREAD_ID ScalarCoupleable::_sc_tid protected inherited
Thread ID of the thread using this object.
Definition at line 224 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::ScalarCoupleable().
_scalar_zero
const VariableValue& ScalarCoupleable::_scalar_zero protected inherited
Zero value of a scalar variable.
Definition at line 230 of file ScalarCoupleable.h.
_second_phi_zero
const VariablePhiSecond& Coupleable::_second_phi_zero protected inherited
Zero second derivative of a test function.
Definition at line 1401 of file Coupleable.h.
_second_zero
const VariableSecond& Coupleable::_second_zero protected inherited
Zero second derivative of a variable.
Definition at line 1398 of file Coupleable.h.
Referenced by Coupleable::genericZeroSecond().
_vector_curl_zero
const VectorVariableCurl& Coupleable::_vector_curl_zero protected inherited
Zero value of the curl of a vector variable.
Definition at line 1405 of file Coupleable.h.
_vector_zero
const VectorVariableValue& Coupleable::_vector_zero protected inherited
Zero value of a vector variable.
Definition at line 1403 of file Coupleable.h.
_writable_coupled_variables
std::vector<std::set<MooseWritableVariable *> > Coupleable::_writable_coupled_variables private inherited
keep a set of allocated writable variable references to make sure only one object can obtain them per thread
Definition at line 1704 of file Coupleable.h.
Referenced by Coupleable::checkWritableVar(), and Coupleable::getWritableCoupledVariables().
_zero
const VariableValue& Coupleable::_zero protected inherited
Zero value of a variable.
Definition at line 1386 of file Coupleable.h.
Referenced by Coupleable::genericZeroValue().
The documentation for this class was generated from the following file:
moose/framework/include/variables/NeighborCoupleableMooseVariableDependencyIntermediateInterface.h