Zapdos: VectorPostprocessorReporterName Class Reference
VectorPostprocessorReporterName Class Reference
A ReporterName that represents a VectorPostprocessor.
#include <ReporterName.h>
Public Member Functions
VectorPostprocessorReporterName (const VectorPostprocessorName &name, const std::string &vector_name)
const std::string & getObjectName () const
Return the object name that produces the Reporter value.
const std::string & getValueName () const
Return the data name for the Reporter value.
const std::string getCombinedName () const
Return the name of the object and data as object_name/data_name.
std::string getRestartableName () const
Return the name used for registration of this Reporter in the restartable data system.
operator std::string () const
std::string operator allows this object to behave as a std::sting object
bool operator== (const ReporterName &rhs) const
Compare with another object or string.
bool operator== (const std::string &combined_name) const
bool operator< (const ReporterName &rhs) const
Less than operator.
std::string specialTypeToName () const
Converts the special type to a usable name for error reporting.
bool isPostprocessor () const
bool isVectorPostprocessor () const
void setIsPostprocessor ()
Sets the special type to a Postprocessor.
void setIsVectorPostprocessor ()
Sets the special type to a VectorPostprocessor.
bool empty () const
Whether or not the ReporterName is empty, similar to std::string::empty()
Static Public Attributes
static const std::string REPORTER_RESTARTABLE_DATA_PREFIX = "ReporterData"
The prefix for reporter data in the restartable system.
Private Types
enum class SpecialType { ANY = 0 , POSTPROCESSOR = 1 , VECTORPOSTPROCESSOR = 2 }
Enum for storing a "special" type for this Reporter.
Private Attributes
ReporterName::SpecialType _special_type = ReporterName::SpecialType::ANY
The "special" type for this Reporter, used for identifying Postprocesors and VectorPostprocessors.
std::string _object_name
The object name.
std::string _value_name
The value name.
Detailed Description
A ReporterName that represents a VectorPostprocessor.
Definition at line 143 of file ReporterName.h.
Member Enumeration Documentation
SpecialType
enum class ReporterName::SpecialType strong private inherited
Enum for storing a "special" type for this Reporter.
This is used to designate Reporters that represent Postprocessors and VectorPostprocessors in output and error handling.
Enumerator
ANY
POSTPROCESSOR
VECTORPOSTPROCESSOR
Definition at line 115 of file ReporterName.h.
  {
    ANY = 0,
    POSTPROCESSOR = 1,
    VECTORPOSTPROCESSOR = 2
  };
Constructor & Destructor Documentation
VectorPostprocessorReporterName()
VectorPostprocessorReporterName::VectorPostprocessorReporterName (const VectorPostprocessorName & name, const std::string & vector_name)
Definition at line 104 of file ReporterName.C.
  : ReporterName(name, vector_name)
{
  setIsVectorPostprocessor();
}
Member Function Documentation
empty()
bool ReporterName::empty () const inline inherited
Whether or not the ReporterName is empty, similar to std::string::empty()
Definition at line 107 of file ReporterName.h.
{ return _object_name.empty() || _value_name.empty(); }
getCombinedName()
const std::string ReporterName::getCombinedName () const inherited
Return the name of the object and data as object_name/data_name.
Definition at line 46 of file ReporterName.C.
{
  return _object_name + "/" + _value_name;
}
Referenced by ReporterData::getAllRealReporterFullNames(), ReporterData::getAllRealReporterValues(), ReporterName::getRestartableName(), ReporterTransferInterface::hideVariableHelper(), ReporterName::operator<(), operator<<(), and ReporterName::operator==().
getObjectName()
const std::string & ReporterName::getObjectName () const inherited
Return the object name that produces the Reporter value.
Definition at line 34 of file ReporterName.C.
{
  return _object_name;
}
Referenced by UserObject::addReporterDependencyHelper(), AccumulateReporter::declareAccumulateHelper(), ReporterData::getReporterInfo(), ReporterTransferInterface::hideVariableHelper(), Exodus::outputReporters(), and TableOutput::outputReporters().
getRestartableName()
std::string ReporterName::getRestartableName () const inherited
Return the name used for registration of this Reporter in the restartable data system.
Definition at line 52 of file ReporterName.C.
{
  return REPORTER_RESTARTABLE_DATA_PREFIX + "/" + getCombinedName();
}
getValueName()
const std::string & ReporterName::getValueName () const inherited
Return the data name for the Reporter value.
Definition at line 40 of file ReporterName.C.
{
  return _value_name;
}
Referenced by AccumulateReporter::declareAccumulateHelper(), ReporterData::getReporterStateHelper(), and Exodus::outputReporters().
isPostprocessor()
bool ReporterName::isPostprocessor () const inline inherited
Returns
True if this ReporterName represents a Postprocessor
Definition at line 85 of file ReporterName.h.
{ return _special_type == SpecialType::POSTPROCESSOR; }
Referenced by ReporterData::declareReporterValue(), ReporterData::getReporterStateHelper(), and ReporterName::specialTypeToName().
isVectorPostprocessor()
bool ReporterName::isVectorPostprocessor () const inline inherited
Returns
True if this ReporterName represents a VectorPostprocessor
Definition at line 89 of file ReporterName.h.
{ return _special_type == SpecialType::VECTORPOSTPROCESSOR; }
Referenced by ReporterData::declareReporterValue(), ReporterData::getReporterStateHelper(), and ReporterName::specialTypeToName().
operator std::string()
ReporterName::operator std::string () const inherited
std::string operator allows this object to behave as a std::sting object
Definition at line 57 of file ReporterName.C.
{ return getCombinedName(); }
operator<()
bool ReporterName::operator< (const ReporterName & rhs) const inherited
Less than operator.
Definition at line 73 of file ReporterName.C.
{
  // Note here that we do not sort by _special_type. This is because
  // we want to store reporter names as a single name regardless of the type
  return getCombinedName() < rhs.getCombinedName();
}
operator==() [1/2]
bool ReporterName::operator== (const ReporterName & rhs) const inherited
Compare with another object or string.
Definition at line 60 of file ReporterName.C.
{
  // Note here that we do not check if _special_type is the same. This is because
  // we want to store reporter names as a single name regardless of the type
  return _object_name == rhs._object_name && _value_name == rhs._value_name;
}
operator==() [2/2]
bool ReporterName::operator== (const std::string & combined_name) const inherited
Definition at line 68 of file ReporterName.C.
{
  return getCombinedName() == combined_name;
}
setIsPostprocessor()
void ReporterName::setIsPostprocessor () inline inherited
Sets the special type to a Postprocessor.
See ReporterData::declareReporterValue.
Definition at line 96 of file ReporterName.h.
{ _special_type = SpecialType::POSTPROCESSOR; }
Referenced by PostprocessorReporterName::PostprocessorReporterName(), and ReporterStateBase::setIsPostprocessor().
setIsVectorPostprocessor()
void ReporterName::setIsVectorPostprocessor () inline inherited
Sets the special type to a VectorPostprocessor.
See ReporterData::declareReporterValue.
Definition at line 102 of file ReporterName.h.
{ _special_type = SpecialType::VECTORPOSTPROCESSOR; }
Referenced by ReporterStateBase::setIsVectorPostprocessor(), and VectorPostprocessorReporterName().
specialTypeToName()
std::string ReporterName::specialTypeToName () const inherited
Converts the special type to a usable name for error reporting.
Definition at line 82 of file ReporterName.C.
{
  if (isPostprocessor())
    return "Postprocessor";
  if (isVectorPostprocessor())
    return "VectorPostprocessor";
  return "Reporter";
}
Referenced by ReporterData::getReporterStateHelper().
Member Data Documentation
_object_name
std::string ReporterName::_object_name private inherited
The object name.
Definition at line 126 of file ReporterName.h.
Referenced by ReporterName::empty(), ReporterName::getCombinedName(), ReporterName::getObjectName(), ReporterName::operator==(), and ReporterName::ReporterName().
_special_type
ReporterName::SpecialType ReporterName::_special_type = ReporterName::SpecialType::ANY private inherited
The "special" type for this Reporter, used for identifying Postprocesors and VectorPostprocessors.
Definition at line 123 of file ReporterName.h.
Referenced by ReporterName::isPostprocessor(), ReporterName::isVectorPostprocessor(), ReporterName::setIsPostprocessor(), and ReporterName::setIsVectorPostprocessor().
_value_name
std::string ReporterName::_value_name private inherited
The value name.
Definition at line 128 of file ReporterName.h.
Referenced by ReporterName::empty(), ReporterName::getCombinedName(), ReporterName::getValueName(), ReporterName::operator==(), and ReporterName::ReporterName().
REPORTER_RESTARTABLE_DATA_PREFIX
const std::string ReporterName::REPORTER_RESTARTABLE_DATA_PREFIX = "ReporterData" static inherited
The prefix for reporter data in the restartable system.
Definition at line 54 of file ReporterName.h.
Referenced by RestartableDataReporter::execute(), and ReporterName::getRestartableName().
The documentation for this class was generated from the following files:
moose/framework/include/reporters/ReporterName.h
moose/framework/src/reporters/ReporterName.C