Zapdos: Factory Class Reference
Factory Class Reference
Generic factory class for build all sorts of objects.
#include <Factory.h>
Public Member Functions
Factory (MooseApp &app)
virtual ~Factory ()
void reg (std::shared_ptr< RegistryEntryBase > obj)
FileLineInfo getLineInfo (const std::string &name) const
Gets file and line information where an object was initially registered.
void associateNameToClass (const std::string &name, const std::string &class_name)
Associates an object name with a class name.
std::string associatedClassName (const std::string &name) const
Get the associated class name for an object name.
InputParameters getValidParams (const std::string &name)
Get valid parameters for the object.
std::shared_ptr< MooseObject > create (const std::string &obj_name, const std::string &name, const InputParameters &parameters, THREAD_ID tid=0, bool print_deprecated=true)
Build an object (must be registered) - THIS METHOD IS DEPRECATED (Use create<T>())
template<typename T >
std::shared_ptr< T > create (const std::string &obj_name, const std::string &name, const InputParameters &parameters, THREAD_ID tid=0)
Build an object (must be registered)
void releaseSharedObjects (const MooseObject &moose_object, THREAD_ID tid=0)
Releases any shared resources created as a side effect of creating an object through the Factory::create method(s).
void restrictRegisterableObjects (const std::vector< std::string > &names)
Calling this object with a non-empty vector will cause this factory to ignore registrations from any object not contained within the list.
const auto & registeredObjects () const
Returns a reference to the map from names to RegistryEntryBase pointers.
bool isRegistered (const std::string &obj_name) const
Returns a Boolean indicating whether an object type has been registered.
std::vector< std::string > getConstructedObjects () const
Get a list of all constructed Moose Object types.
MooseApp & app ()
Private Member Functions
std::time_t parseTime (std::string)
Parse time string (mm/dd/yyyy HH:MM)
void deprecatedMessage (const std::string obj_name)
Show the appropriate message for deprecated objects.
void reportUnregisteredError (const std::string &obj_name) const
Prints error information when an object is not registered.
Private Attributes
MooseApp & _app
Reference to the application.
std::map< std::string, std::shared_ptr< RegistryEntryBase > > _name_to_object
Storage for pointers to the object registry entry.
FileLineInfoMap _name_to_line
std::map< std::string, std::string > _name_to_class
Object name to class name association.
std::map< std::string, std::time_t > _deprecated_time
Storage for deprecated object experiation dates.
std::map< std::string, std::string > _deprecated_name
Storage for the deprecated objects that have replacements.
std::set< std::string > _registerable_objects
The list of objects that may be registered.
std::set< std::string > _constructed_types
Constructed Moose Object types.
std::set< std::string > _deprecated_types
Set of deprecated object types that have been printed.
std::set< std::pair< std::string, std::string > > _objects_by_label
set<label/appname, objectname> used to track if an object previously added is being added again - which is okay/allowed, while still allowing us to detect/reject cases of duplicate object name registration where the label/appname is not identical.
Detailed Description
Generic factory class for build all sorts of objects.
Definition at line 28 of file Factory.h.
Constructor & Destructor Documentation
Factory()
Factory::Factory (MooseApp & app)
Definition at line 17 of file Factory.C.
: _app(app) {}
~Factory()
Factory::~Factory () virtual
Definition at line 19 of file Factory.C.
{}
Member Function Documentation
app()
MooseApp & Factory::app () inline
Definition at line 134 of file Factory.h.
{ return _app; }
associatedClassName()
std::string Factory::associatedClassName (const std::string & name) const
Get the associated class name for an object name.
This will return an empty string if the name was not previously associated with a class name via associateNameToClass()
Definition at line 303 of file Factory.C.
{
  auto it = _name_to_class.find(name);
  if (it == _name_to_class.end())
    return "";
  else
    return it->second;
}
Referenced by Parser::buildJsonSyntaxTree().
associateNameToClass()
void Factory::associateNameToClass (const std::string & name, const std::string & class_name)
Associates an object name with a class name.
Primarily used with the registerNamed* macros to store the mapping between the object name and the class that implements the object.
Definition at line 297 of file Factory.C.
{
  _name_to_class[name] = class_name;
}
Referenced by Registry::registerObjectsTo().
create() [1/2]
template<typename T > std::shared_ptr< T > Factory::create (const std::string & obj_name, const std::string & name, const InputParameters & parameters, THREAD_ID tid = 0) inline
Build an object (must be registered)
Parameters
obj_name Type of the object being constructed
name Name for the object
parameters Parameters this object should have
tid The thread id that this copy will be created for
Returns
The created object
Definition at line 88 of file Factory.h.
  {
    std::shared_ptr<T> new_object =
        std::dynamic_pointer_cast<T>(create(obj_name, name, parameters, tid, false));
    if (!new_object)
      mooseError("We expected to create an object of type '" + demangle(typeid(T).name()) +
                 "'.\nInstead we received a parameters object for type '" + obj_name +
                 "'.\nDid you call the wrong \"add\" method in your Action?");
    return new_object;
  }
create() [2/2]
std::shared_ptr< MooseObject > Factory::create (const std::string & obj_name, const std::string & name, const InputParameters & parameters, THREAD_ID tid = 0, bool print_deprecated = true)
Build an object (must be registered) - THIS METHOD IS DEPRECATED (Use create<T>())
Parameters
obj_name Type of the object being constructed
name Name for the object
parameters Parameters this object should have
tid The thread id that this copy will be created for
print_deprecated controls the deprecated message
Returns
The created object
Definition at line 86 of file Factory.C.
{
  if (print_deprecated)
    mooseDeprecated("Factory::create() is deprecated, please use Factory::create<T>() instead");
  // Pointer to the object constructor
  const auto it = _name_to_object.find(obj_name);
  // Check if the object is registered
  if (it == _name_to_object.end())
    reportUnregisteredError(obj_name);
  // Print out deprecated message, if it exists
  deprecatedMessage(obj_name);
  // Create the actual parameters object that the object will reference
  InputParameters & params =
      _app.getInputParameterWarehouse().addInputParameters(name, parameters, tid);
  // Set the _type parameter
  params.set<std::string>("_type") = obj_name;
  // Check to make sure that all required parameters are supplied
  params.checkParams(name);
  // register type name as constructed
  _constructed_types.insert(obj_name);
  // add FEProblem pointers to object's params object
  if (_app.actionWarehouse().problemBase())
    _app.actionWarehouse().problemBase()->setInputParametersFEProblem(params);
  // call the function pointer to build the object
  auto obj = it->second->build(params);
  auto fep = std::dynamic_pointer_cast<FEProblemBase>(obj);
  if (fep)
    _app.actionWarehouse().problemBase() = fep;
  // Make sure no unexpected parameters were added by the object's constructor or by the action
  // initiating this create call.  All parameters modified by the constructor must have already
  // been specified in the object's validParams function.
  InputParameters orig_params = getValidParams(obj_name);
  if (orig_params.n_parameters() != parameters.n_parameters())
  {
    std::set<std::string> orig, populated;
    for (const auto & it : orig_params)
      orig.emplace(it.first);
    for (const auto & it : parameters)
      populated.emplace(it.first);
    std::set<std::string> diff;
    std::set_difference(populated.begin(),
                        populated.end(),
                        orig.begin(),
                        orig.end(),
                        std::inserter(diff, diff.begin()));
    if (!diff.empty())
    {
      std::stringstream ss;
      for (const auto & name : diff)
        ss << ", " << name;
      mooseError("attempted to set unregistered parameter(s) for ",
                 obj_name,
                 " object:\n    ",
                 ss.str().substr(2));
    }
  }
  return obj;
}
Referenced by AdaptivityAction::act(), AddControlAction::act(), AddPeriodicBCAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), MaterialDerivativeTestAction::act(), PartitionerAction::act(), SetAdaptivityOptionsAction::act(), SetupMeshAction::act(), SetupPreconditionerAction::act(), SetupPredictorAction::act(), FEProblemBase::addAnyRedistributers(), NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addConstraint(), NonlinearSystemBase::addDamper(), NonlinearSystemBase::addDGKernel(), NonlinearSystemBase::addDiracKernel(), MooseApp::addExecutor(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), NonlinearSystemBase::addInterfaceKernel(), AuxiliarySystem::addKernel(), MooseEigenSystem::addKernel(), NonlinearSystemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), NonlinearSystemBase::addNodalKernel(), FEProblemBase::addObject(), FEProblemBase::addOutput(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), AuxiliarySystem::addScalarKernel(), NonlinearSystemBase::addScalarKernel(), NonlinearSystemBase::addSplit(), AuxiliarySystem::addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), SystemBase::addVariable(), AStableDirk4::AStableDirk4(), MooseObjectUnitTest::buildObjects(), create(), MooseApp::createExecutors(), and MeshGeneratorSystem::createMeshGenerator().
deprecatedMessage()
void Factory::deprecatedMessage (const std::string obj_name) private
Show the appropriate message for deprecated objects.
Parameters
obj_name Name of the deprecated object
Definition at line 198 of file Factory.C.
{
  const auto time_it = _deprecated_time.find(obj_name);
  // If the object is not deprecated return
  if (time_it == _deprecated_time.end())
    return;
  // If the message has already been printed, return
  if (_deprecated_types.count(obj_name))
    return;
  _deprecated_types.emplace(obj_name);
  // We dont need a backtrace on this, this is user-facing
  const auto current_show_trace = Moose::show_trace;
  Moose::show_trace = false;
  // Get the current time
  std::time_t now;
  time(&now);
  // Get the stop time
  std::time_t t_end = time_it->second;
  // Message storage
  std::ostringstream msg;
  const auto name_it = _deprecated_name.find(obj_name);
  // Expired object
  if (now > t_end)
  {
    msg << "***** Invalid Object: " << obj_name << " *****\n";
    msg << "Expired on " << ctime(&t_end);
    // Append replacement object, if it exists
    if (name_it != _deprecated_name.end())
      msg << "Update your application using the '" << name_it->second << "' object";
    // Produce the error message
    mooseDeprecationExpired(msg.str());
  }
  // Expiring object
  else
  {
    // Build the basic message
    msg << "Deprecated Object: " << obj_name << "\n";
    msg << "This object will be removed on " << ctime(&t_end);
    // Append replacement object, if it exists
    if (name_it != _deprecated_name.end())
      msg << "Replace " << obj_name << " with " << name_it->second;
    // Produce the error message
    mooseDeprecated(msg.str());
  }
  Moose::show_trace = current_show_trace;
}
Referenced by create(), and getValidParams().
getConstructedObjects()
std::vector< std::string > Factory::getConstructedObjects () const
Get a list of all constructed Moose Object types.
Definition at line 282 of file Factory.C.
{
  std::vector<std::string> list;
  for (const auto & name : _constructed_types)
    list.push_back(name);
  return list;
}
Referenced by MooseApp::runInputFile().
getLineInfo()
FileLineInfo Factory::getLineInfo (const std::string & name) const
Gets file and line information where an object was initially registered.
Parameters
name Object name
Returns
The FileLineInfo associated with name
Definition at line 291 of file Factory.C.
{
  return _name_to_line.getInfo(name);
}
Referenced by Parser::buildJsonSyntaxTree(), and MooseServer::gatherDocumentDefinitionLocations().
getValidParams()
InputParameters Factory::getValidParams (const std::string & name)
Get valid parameters for the object.
Parameters
name Name of the object whose parameter we are requesting
Returns
Parameters of the object
Definition at line 67 of file Factory.C.
{
  const auto it = _name_to_object.find(obj_name);
  // Check if the object is registered
  if (it == _name_to_object.end())
    reportUnregisteredError(obj_name);
  // Print out deprecated message, if it exists
  deprecatedMessage(obj_name);
  // Return the parameters
  auto params = it->second->buildParameters();
  params.addPrivateParam("_moose_app", &_app);
  return params;
}
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), AddGeneralReactions::act(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), ElementIDOutputAction::act(), AddSpecies::act(), AdaptivityAction::act(), AddNodalNormalsAction::act(), AddPeriodicBCAction::act(), AutoCheckpointAction::act(), ComposeTimeStepperAction::act(), CreateDisplacedProblemAction::act(), CreateProblemDefaultAction::act(), DisplayGhostingAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SetupResidualDebugAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), FEProblemBase::addAuxArrayVariable(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddGeneralReactions::addEEDFReactionKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), FEProblem::addLineSearch(), MeshGenerator::addMeshSubgenerator(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddDriftDiffusionAction::addPosition(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), FVFluxKernel::adjustRMGhostLayers(), AStableDirk4::AStableDirk4(), MooseObjectUnitTest::buildObjects(), MooseBaseParameterInterface::connectControllableParams(), create(), MooseApp::createExecutors(), DumpObjectsProblem::deduceNecessaryParameters(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), FEProblemBase::getFunction(), MooseServer::getObjectParameters(), MaterialOutputAction::getParams(), ProjectedStatefulMaterialStorageAction::processProperty(), Transient::setupTimeIntegrator(), and SideSetExtruderGenerator::SideSetExtruderGenerator().
isRegistered()
bool Factory::isRegistered (const std::string & obj_name) const inline
Returns a Boolean indicating whether an object type has been registered.
Definition at line 127 of file Factory.h.
{ return _name_to_object.count(obj_name); }
Referenced by MooseServer::gatherDocumentDefinitionLocations(), and MooseServer::getObjectParameters().
parseTime()
std::time_t Factory::parseTime (std::string t_str) private
Parse time string (mm/dd/yyyy HH:MM)
Parameters
t_str String with the object expiration date, this must be in the form mm/dd/yyyy HH:MM
Returns
A time_t object with the expiration date
Definition at line 176 of file Factory.C.
{
  // The string must be a certain length to be valid
  if (t_str.size() != 16)
    mooseError("The deprecated time not formatted correctly; it must be given as mm/dd/yyyy HH:MM");
  // Store the time, the time must be specified as: mm/dd/yyyy HH:MM
  std::time_t t_end;
  struct tm * t_end_info;
  time(&t_end);
  t_end_info = localtime(&t_end);
  t_end_info->tm_mon = std::atoi(t_str.substr(0, 2).c_str()) - 1;
  t_end_info->tm_mday = std::atoi(t_str.substr(3, 2).c_str());
  t_end_info->tm_year = std::atoi(t_str.substr(6, 4).c_str()) - 1900;
  t_end_info->tm_hour = std::atoi(t_str.substr(11, 2).c_str()) + 1;
  t_end_info->tm_min = std::atoi(t_str.substr(14, 2).c_str());
  t_end_info->tm_sec = 0;
  t_end = mktime(t_end_info);
  return t_end;
}
Referenced by reg().
reg()
void Factory::reg (std::shared_ptr< RegistryEntryBase > obj)
Definition at line 22 of file Factory.C.
{
  const std::string obj_name = obj->name();
  const std::string & label = obj->_label;
  const std::string & deprecated_time = obj->_deprecated_time;
  const std::string & replacement_name = obj->_replaced_by;
  const std::string & file = obj->_file;
  const int line = obj->_line;
  // do nothing if we have already added this exact object before
  auto key = std::make_pair(label, obj_name);
  if (_objects_by_label.find(key) != _objects_by_label.end())
    return;
  /*
   * If _registerable_objects has been set the user has requested that we only register some
   * subset
   * of the objects for a dynamically loaded application. The objects listed in *this*
   * application's
   * registerObjects() method will have already been registered before that member was set.
   *
   * If _registerable_objects is empty, the factory is unrestricted
   */
  if (_registerable_objects.empty() ||
      _registerable_objects.find(obj_name) != _registerable_objects.end())
  {
    if (_name_to_object.find(obj_name) != _name_to_object.end())
      mooseError("Object '" + obj_name + "' registered from multiple files: ",
                 file,
                 " and ",
                 _name_to_line.getInfo(obj_name).file());
    _name_to_object[obj_name] = obj;
    _objects_by_label.insert(key);
  }
  _name_to_line.addInfo(obj_name, file, line);
  if (!replacement_name.empty())
    _deprecated_name[obj_name] = replacement_name;
  if (!deprecated_time.empty())
    _deprecated_time[obj_name] = parseTime(deprecated_time);
  // TODO: Possibly store and print information about objects that are skipped here?
}
Referenced by Registry::registerObjectsTo().
registeredObjects()
const auto & Factory::registeredObjects () const inline
Returns a reference to the map from names to RegistryEntryBase pointers.
Definition at line 122 of file Factory.h.
{ return _name_to_object; }
Referenced by MooseServer::addValuesToList(), Parser::buildFullTree(), and Parser::buildJsonSyntaxTree().
releaseSharedObjects()
void Factory::releaseSharedObjects (const MooseObject & moose_object, THREAD_ID tid = 0)
Releases any shared resources created as a side effect of creating an object through the Factory::create method(s).
Currently, this object just moves the InputParameters object from the InputParameterWarehouse. Normally this method does not need to be explicitly called during a normal simulation.
Definition at line 164 of file Factory.C.
{
  _app.getInputParameterWarehouse().removeInputParameters(moose_object, tid);
}
Referenced by AdaptivityAction::act(), AddPeriodicBCAction::act(), SetAdaptivityOptionsAction::act(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), and MooseApp::removeRelationshipManager().
reportUnregisteredError()
void Factory::reportUnregisteredError (const std::string & obj_name) const private
Prints error information when an object is not registered.
Definition at line 259 of file Factory.C.
{
  std::ostringstream oss;
  std::set<std::string> paths = _app.getLoadedLibraryPaths();
  oss << "A '" + obj_name + "' is not a registered object.\n";
  if (!paths.empty())
  {
    oss << "\nWe loaded objects from the following libraries and still couldn't find your "
           "object:\n\t";
    std::copy(paths.begin(), paths.end(), infix_ostream_iterator<std::string>(oss, "\n\t"));
    oss << '\n';
  }
  oss << "\nIf you are trying to find this object in a dynamically loaded library, make sure that\n"
         "the library can be found either in your \"Problem/library_path\" parameter or in the\n"
         "MOOSE_LIBRARY_PATH environment variable.";
  mooseError(oss.str());
}
Referenced by create(), and getValidParams().
restrictRegisterableObjects()
void Factory::restrictRegisterableObjects (const std::vector< std::string > & names)
Calling this object with a non-empty vector will cause this factory to ignore registrations from any object not contained within the list.
Parameters
names a vector containing the names of objects that this factory will register
Definition at line 170 of file Factory.C.
{
  _registerable_objects.insert(names.begin(), names.end());
}
Referenced by DynamicObjectRegistrationAction::DynamicObjectRegistrationAction().
Member Data Documentation
_app
MooseApp& Factory::_app private
Reference to the application.
Definition at line 157 of file Factory.h.
Referenced by app(), create(), getValidParams(), releaseSharedObjects(), and reportUnregisteredError().
_constructed_types
std::set<std::string> Factory::_constructed_types private
Constructed Moose Object types.
Definition at line 177 of file Factory.h.
Referenced by create(), and getConstructedObjects().
_deprecated_name
std::map<std::string, std::string> Factory::_deprecated_name private
Storage for the deprecated objects that have replacements.
Definition at line 171 of file Factory.h.
Referenced by deprecatedMessage(), and reg().
_deprecated_time
std::map<std::string, std::time_t> Factory::_deprecated_time private
Storage for deprecated object experiation dates.
Definition at line 168 of file Factory.h.
Referenced by deprecatedMessage(), and reg().
_deprecated_types
std::set<std::string> Factory::_deprecated_types private
Set of deprecated object types that have been printed.
Definition at line 180 of file Factory.h.
Referenced by deprecatedMessage().
_name_to_class
std::map<std::string, std::string> Factory::_name_to_class private
Object name to class name association.
Definition at line 165 of file Factory.h.
Referenced by associatedClassName(), and associateNameToClass().
_name_to_line
FileLineInfoMap Factory::_name_to_line private
Definition at line 162 of file Factory.h.
Referenced by getLineInfo(), and reg().
_name_to_object
std::map<std::string, std::shared_ptr<RegistryEntryBase> > Factory::_name_to_object private
Storage for pointers to the object registry entry.
Definition at line 160 of file Factory.h.
Referenced by create(), getValidParams(), isRegistered(), reg(), and registeredObjects().
_objects_by_label
std::set<std::pair<std::string, std::string> > Factory::_objects_by_label private
set<label/appname, objectname> used to track if an object previously added is being added again - which is okay/allowed, while still allowing us to detect/reject cases of duplicate object name registration where the label/appname is not identical.
Definition at line 185 of file Factory.h.
Referenced by reg().
_registerable_objects
std::set<std::string> Factory::_registerable_objects private
The list of objects that may be registered.
Definition at line 174 of file Factory.h.
Referenced by reg(), and restrictRegisterableObjects().
The documentation for this class was generated from the following files:
moose/framework/include/base/Factory.h
moose/framework/src/base/Factory.C