Zapdos: SystemBase Class Reference
SystemBase Class Reference abstract
Base class for a system (of equations)
#include <SystemBase.h>
Public Member Functions
SystemBase (SubProblem &subproblem, const std::string &name, Moose::VarKindType var_kind)
virtual ~SystemBase ()
unsigned int number () const
Gets the number of this system.
virtual MooseMesh & mesh ()
virtual const MooseMesh & mesh () const
virtual SubProblem & subproblem ()
virtual const SubProblem & subproblem () const
void applyScalingFactors (const std::vector< Real > &inverse_scaling_factors)
Applies scaling factors to the system's variables.
bool computingScalingJacobian () const
Whether we are computing an initial Jacobian for automatic variable scaling.
bool automaticScaling () const
Getter for whether we are performing automatic scaling.
void automaticScaling (bool automatic_scaling)
Setter for whether we are performing automatic scaling.
void setVerboseFlag (const bool &verbose)
Sets the verbose flag.
virtual DofMap & dofMap ()
Gets writeable reference to the dof map.
virtual const DofMap & dofMap () const
Gets const reference to the dof map.
virtual System & system ()=0
Get the reference to the libMesh system.
virtual const System & system () const =0
virtual void init ()
Initialize the system.
virtual void initializeObjects ()
Called only once, just before the solve begins so objects can do some precalculations.
virtual void update (bool update_libmesh_system=true)
Update the system (doing libMesh magic)
virtual void solve ()
Solve the system (using libMesh magic)
virtual void copyOldSolutions ()
Shifts the solutions backwards in time.
virtual void restoreSolutions ()
Restore current solutions (call after your solve failed)
virtual const NumericVector< Number > *const & currentSolution () const =0
The solution vector that is currently being operated on.
NumericVector< Number > & solution ()
NumericVector< Number > & solutionOld ()
NumericVector< Number > & solutionOlder ()
const NumericVector< Number > & solution () const
const NumericVector< Number > & solutionOld () const
const NumericVector< Number > & solutionOlder () const
virtual const NumericVector< Number > * solutionPreviousNewton () const
virtual NumericVector< Number > * solutionPreviousNewton ()
virtual void initSolutionState ()
Initializes the solution state.
virtual NumericVector< Number > & solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time)
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
virtual const NumericVector< Number > & solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time) const
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
virtual void needSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time)
Registers that the solution state state is needed.
virtual bool hasSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time) const
Whether or not the system has the solution state (0 = current, 1 = old, 2 = older, etc).
virtual Number & duDotDu ()
virtual Number & duDotDotDu ()
virtual const Number & duDotDu () const
virtual const Number & duDotDotDu () const
virtual NumericVector< Number > * solutionUDot ()=0
virtual NumericVector< Number > * solutionUDotOld ()=0
virtual NumericVector< Number > * solutionUDotDot ()=0
virtual NumericVector< Number > * solutionUDotDotOld ()=0
virtual const NumericVector< Number > * solutionUDot () const =0
virtual const NumericVector< Number > * solutionUDotOld () const =0
virtual const NumericVector< Number > * solutionUDotDot () const =0
virtual const NumericVector< Number > * solutionUDotDotOld () const =0
virtual void saveOldSolutions ()
Save the old and older solutions.
virtual void restoreOldSolutions ()
Restore the old and older solutions when the saved solutions present.
bool hasVector (const std::string &tag_name) const
Check if the named vector exists in the system.
virtual bool hasVector (TagID tag_id) const
Check if the tagged vector exists in the system.
virtual TagID timeVectorTag () const
Ideally, we should not need this API.
virtual TagID systemMatrixTag () const
Return the Matrix Tag ID for System.
virtual TagID nonTimeVectorTag () const
virtual TagID residualVectorTag () const
virtual std::set< TagID > defaultVectorTags () const
Get the default vector tags associated with this system.
virtual std::set< TagID > defaultMatrixTags () const
Get the default matrix tags associted with this system.
virtual void associateVectorToTag (NumericVector< Number > &vec, TagID tag)
Associate a vector for a given tag.
virtual void disassociateVectorFromTag (NumericVector< Number > &vec, TagID tag)
Disassociate a given vector from a given tag.
virtual void disassociateVectorFromTag (TagID tag)
Disassociate any vector that is associated with a given tag.
virtual void disassociateDefaultVectorTags ()
Disassociate the vectors associated with the default vector tags of this system.
virtual bool hasMatrix (TagID tag) const
Check if the tagged matrix exists in the system.
virtual SparseMatrix< Number > & getMatrix (TagID tag)
Get a raw SparseMatrix.
virtual const SparseMatrix< Number > & getMatrix (TagID tag) const
Get a raw SparseMatrix.
virtual void activeAllMatrixTags ()
Make all exsiting matrices ative.
virtual void activeMatrixTag (TagID tag)
Active a matrix for tag.
virtual bool matrixTagActive (TagID tag) const
If or not a matrix tag is active.
virtual void deactiveMatrixTag (TagID tag)
deactive a matrix for tag
virtual void deactiveAllMatrixTags ()
Make matrices inactive.
void closeTaggedMatrices (const std::set< TagID > &tags)
Close all matrices associated the tags.
void flushTaggedMatrices (const std::set< TagID > &tags)
flushes all matrices associated to tags.
virtual void associateMatrixToTag (SparseMatrix< Number > &matrix, TagID tag)
Associate a matrix to a tag.
virtual void disassociateMatrixFromTag (SparseMatrix< Number > &matrix, TagID tag)
Disassociate a matrix from a tag.
virtual void disassociateMatrixFromTag (TagID tag)
Disassociate any matrix that is associated with a given tag.
virtual void disassociateDefaultMatrixTags ()
Disassociate the matrices associated with the default matrix tags of this system.
virtual NumericVector< Number > & serializedSolution ()=0
Returns a reference to a serialized version of the solution vector for this subproblem.
virtual NumericVector< Number > & residualCopy ()
virtual NumericVector< Number > & residualGhosted ()
virtual void augmentSendList (std::vector< dof_id_type > &send_list)
Will modify the send_list to add all of the extra ghosted dofs for this system.
virtual void augmentSparsity (SparsityPattern::Graph &sparsity, std::vector< dof_id_type > &n_nz, std::vector< dof_id_type > &n_oz)=0
Will modify the sparsity pattern to add logical geometric connections.
virtual void addVariable (const std::string &var_type, const std::string &var_name, InputParameters &parameters)
Canonical method for adding a variable.
virtual bool isArrayVariable (const std::string &var_name) const
If a variable is an array variable.
virtual bool isScalarVariable (unsigned int var_name) const
MooseVariableFieldBase & getVariable (THREAD_ID tid, const std::string &var_name) const
Gets a reference to a variable of with specified name.
MooseVariableFieldBase & getVariable (THREAD_ID tid, unsigned int var_number) const
Gets a reference to a variable with specified number.
template<typename T >
MooseVariableFE< T > & getFieldVariable (THREAD_ID tid, const std::string &var_name)
Gets a reference to a variable of with specified name.
template<typename T >
MooseVariableField< T > & getActualFieldVariable (THREAD_ID tid, const std::string &var_name)
Returns a field variable pointer - this includes finite volume variables.
template<typename T >
MooseVariableFE< T > & getFieldVariable (THREAD_ID tid, unsigned int var_number)
Gets a reference to a variable with specified number.
template<typename T >
MooseVariableField< T > & getActualFieldVariable (THREAD_ID tid, unsigned int var_number)
Returns a field variable pointer - this includes finite volume variables.
template<typename T >
MooseVariableFV< T > & getFVVariable (THREAD_ID tid, const std::string &var_name)
Return a finite volume variable.
virtual MooseVariableScalar & getScalarVariable (THREAD_ID tid, const std::string &var_name) const
Gets a reference to a scalar variable with specified number.
virtual MooseVariableScalar & getScalarVariable (THREAD_ID tid, unsigned int var_number) const
Gets a reference to a variable with specified number.
virtual const std::set< SubdomainID > * getVariableBlocks (unsigned int var_number)
Get the block where a variable of this system is defined.
virtual unsigned int nVariables () const
Get the number of variables in this system.
unsigned int nFieldVariables () const
Get the number of field variables in this system.
unsigned int nFVVariables () const
Get the number of finite volume variables in this system.
std::size_t getMaxVarNDofsPerElem () const
Gets the maximum number of dofs used by any one variable on any one element.
std::size_t getMaxVarNDofsPerNode () const
Gets the maximum number of dofs used by any one variable on any one node.
void assignMaxVarNDofsPerElem (std::size_t max_dofs)
assign the maximum element dofs
void assignMaxVarNDofsPerNode (std::size_t max_dofs)
assign the maximum node dofs
virtual void addVariableToZeroOnResidual (std::string var_name)
Adds this variable to the list of variables to be zeroed during each residual evaluation.
virtual void addVariableToZeroOnJacobian (std::string var_name)
Adds this variable to the list of variables to be zeroed during each Jacobian evaluation.
virtual void zeroVariables (std::vector< std::string > &vars_to_be_zeroed)
Zero out the solution for the list of variables passed in.
virtual void zeroVariablesForResidual ()
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on residual evaluation by a call to addVariableToZeroOnResidual()
virtual void zeroVariablesForJacobian ()
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on Jacobian evaluation by a call to addVariableToZeroOnResidual()
virtual Order getMinQuadratureOrder ()
Get minimal quadrature order needed for integrating variables in this system.
virtual void prepare (THREAD_ID tid)
Prepare the system for use.
virtual void prepareFace (THREAD_ID tid, bool resize_data)
Prepare the system for use on sides.
virtual void prepareNeighbor (THREAD_ID tid)
Prepare the system for use.
virtual void prepareLowerD (THREAD_ID tid)
Prepare the system for use for lower dimensional elements.
virtual void reinitElem (const Elem *elem, THREAD_ID tid)
Reinit an element assembly info.
virtual void reinitElemFace (const Elem *elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid)
Reinit assembly info for a side of an element.
virtual void reinitNeighborFace (const Elem *elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid)
Compute the values of the variables at all the current points.
virtual void reinitNeighbor (const Elem *elem, THREAD_ID tid)
Compute the values of the variables at all the current points.
virtual void reinitLowerD (THREAD_ID tid)
Compute the values of the variables on the lower dimensional element.
virtual void reinitNode (const Node *node, THREAD_ID tid)
Reinit nodal assembly info.
virtual void reinitNodeFace (const Node *node, BoundaryID bnd_id, THREAD_ID tid)
Reinit nodal assembly info on a face.
virtual void reinitNodes (const std::vector< dof_id_type > &nodes, THREAD_ID tid)
Reinit variables at a set of nodes.
virtual void reinitNodesNeighbor (const std::vector< dof_id_type > &nodes, THREAD_ID tid)
Reinit variables at a set of neighbor nodes.
virtual void reinitScalars (THREAD_ID tid, bool reinit_for_derivative_reordering=false)
Reinit scalar varaibles.
virtual void addVariableToCopy (const std::string &dest_name, const std::string &source_name, const std::string &timestep)
Add info about variable that will be copied.
const std::vector< MooseVariableFieldBase * > & getVariables (THREAD_ID tid)
const std::vector< MooseVariableScalar * > & getScalarVariables (THREAD_ID tid)
const std::set< SubdomainID > & getSubdomainsForVar (unsigned int var_number) const
const std::set< SubdomainID > & getSubdomainsForVar (const std::string &var_name) const
Get the block where a variable of this system is defined.
void removeVector (const std::string &name)
Remove a vector from the system with the given name.
NumericVector< Number > & addVector (const std::string &vector_name, const bool project, const ParallelType type)
Adds a solution length vector to the system.
NumericVector< Number > & addVector (TagID tag, const bool project, const ParallelType type)
Adds a solution length vector to the system with the specified TagID.
void closeTaggedVector (const TagID tag)
Close vector with the given tag.
void closeTaggedVectors (const std::set< TagID > &tags)
Close all vectors for given tags.
void zeroTaggedVector (const TagID tag)
Zero vector with the given tag.
void zeroTaggedVectors (const std::set< TagID > &tags)
Zero all vectors for given tags.
void removeVector (TagID tag_id)
Remove a solution length vector from the system with the specified TagID.
void setVariableGlobalDoFs (const std::string &var_name)
set all the global dof indices for a variable
const std::vector< dof_id_type > & getVariableGlobalDoFs ()
Get the global dof indices of a variable, this needs to be called after the indices have been set by setVariableGlobalDoFs
SparseMatrix< Number > & addMatrix (TagID tag)
Adds a matrix with a given tag.
void removeMatrix (TagID tag)
Removes a matrix with a given tag.
virtual const std::string & name () const
const std::vector< VariableName > & getVariableNames () const
void getStandardFieldVariableNames (std::vector< VariableName > &std_field_variables) const
unsigned int getMaxVariableNumber () const
Returns the maximum number of all variables on the system.
virtual void computeVariables (const NumericVector< Number > &)
void copyVars (ExodusII_IO &io)
virtual void copySolutionsBackwards ()
Copy current solution into old and older.
virtual void addTimeIntegrator (const std::string &, const std::string &, InputParameters &)
virtual void addTimeIntegrator (std::shared_ptr< TimeIntegrator >)
TimeIntegrator * getTimeIntegrator ()
const TimeIntegrator * getTimeIntegrator () const
std::shared_ptr< TimeIntegrator > getSharedTimeIntegrator ()
bool hasVarCopy () const
Whether or not there are variables to be restarted from an Exodus mesh file.
void addScalingVector ()
Add the scaling factor vector to the system.
bool solutionStatesInitialized () const
Whether or not the solution states have been initialized via initSolutionState()
virtual void initialSetup ()
Setup Functions.
virtual void timestepSetup ()
virtual void customSetup (const ExecFlagType &exec_type)
virtual void subdomainSetup ()
virtual void residualSetup ()
virtual void jacobianSetup ()
void clearAllDofIndices ()
Clear all dof indices from moose variables.
void setActiveVariableCoupleableVectorTags (const std::set< TagID > &vtags, THREAD_ID tid)
Set the active vector tags for the variables.
void setActiveScalarVariableCoupleableVectorTags (const std::set< TagID > &vtags, THREAD_ID tid)
Set the active vector tags for the scalar variables.
Moose::VarKindType varKind () const
virtual NumericVector< Number > & getVector (const std::string &name)
Get a raw NumericVector by name.
virtual const NumericVector< Number > & getVector (const std::string &name) const
virtual NumericVector< Number > & getVector (TagID tag)
Get a raw NumericVector by tag.
virtual const NumericVector< Number > & getVector (TagID tag) const
virtual bool hasVariable (const std::string &var_name) const
Query a system for a variable.
virtual bool hasScalarVariable (const std::string &var_name) const
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Member Functions
virtual NumericVector< Number > & solutionInternal () const =0
Internal getter for solution owned by libMesh.
Protected Attributes
SubProblem & _subproblem
MooseApp & _app
Factory & _factory
MooseMesh & _mesh
std::string _name
The name of this system.
std::vector< VariableWarehouse > _vars
Variable warehouses (one for each thread)
std::map< unsigned int, std::set< SubdomainID > > _var_map
Map of variables (variable id -> array of subdomains where it lives)
unsigned int _max_var_number
Maximum variable number.
std::vector< std::string > _vars_to_be_zeroed_on_residual
std::vector< std::string > _vars_to_be_zeroed_on_jacobian
Real _du_dot_du
Real _du_dotdot_du
std::vector< NumericVector< Number > * > _tagged_vectors
Tagged vectors (pointer)
std::vector< SparseMatrix< Number > * > _tagged_matrices
Tagged matrices (pointer)
std::vector< bool > _matrix_tag_active_flags
Active flags for tagged matrices.
NumericVector< Real > * _saved_old
NumericVector< Real > * _saved_older
NumericVector< Real > * _saved_dot_old
NumericVector< Real > * _saved_dotdot_old
Moose::VarKindType _var_kind
default kind of variables in this system
std::vector< VarCopyInfo > _var_to_copy
size_t _max_var_n_dofs_per_elem
Maximum number of dofs for any one variable on any one element.
size_t _max_var_n_dofs_per_node
Maximum number of dofs for any one variable on any one node.
std::shared_ptr< TimeIntegrator > _time_integrator
Time integrator.
std::vector< std::vector< MooseVariableFieldBase * > > _numbered_vars
Map variable number to its pointer.
bool _automatic_scaling
Whether to automatically scale the variables.
bool _verbose
True if printing out additional information.
bool _solution_states_initialized
Whether or not the solution states have been initialized.
std::vector< dof_id_type > _var_all_dof_indices
Container for the dof indices of a given variable.
Private Member Functions
TagName oldSolutionStateVectorName (const unsigned int, Moose::SolutionIterationType iteration_type) const
Gets the vector name used for an old (not current) solution state.
Private Attributes
std::array< std::vector< NumericVector< Number > * >, 2 > _solution_states
The solution states (0 = current, 1 = old, 2 = older, etc)
std::vector< NumericVector< Number > * > _saved_solution_states
The saved solution states (0 = current, 1 = old, 2 = older, etc)
Detailed Description
Base class for a system (of equations)
Definition at line 84 of file SystemBase.h.
Constructor & Destructor Documentation
SystemBase()
SystemBase::SystemBase (SubProblem & subproblem, const std::string & name, Moose::VarKindType var_kind)
Definition at line 51 of file SystemBase.C.
  : libMesh::ParallelObject(subproblem),
    ConsoleStreamInterface(subproblem.getMooseApp()),
    _subproblem(subproblem),
    _app(subproblem.getMooseApp()),
    _factory(_app.getFactory()),
    _mesh(subproblem.mesh()),
    _name(name),
    _vars(libMesh::n_threads()),
    _var_map(),
    _max_var_number(0),
    _saved_old(NULL),
    _saved_older(NULL),
    _saved_dot_old(NULL),
    _saved_dotdot_old(NULL),
    _var_kind(var_kind),
    _max_var_n_dofs_per_elem(0),
    _max_var_n_dofs_per_node(0),
    _time_integrator(nullptr),
    _automatic_scaling(false),
    _verbose(false),
    _solution_states_initialized(false)
{
}
~SystemBase()
virtual SystemBase::~SystemBase () inline virtual
Definition at line 89 of file SystemBase.h.
{}
Member Function Documentation
activeAllMatrixTags()
void SystemBase::activeAllMatrixTags () virtual
Make all exsiting matrices ative.
Definition at line 1103 of file SystemBase.C.
{
  auto num_matrix_tags = _subproblem.numMatrixTags();
  _matrix_tag_active_flags.resize(num_matrix_tags);
  for (decltype(num_matrix_tags) tag = 0; tag < num_matrix_tags; tag++)
    if (hasMatrix(tag))
      _matrix_tag_active_flags[tag] = true;
    else
      _matrix_tag_active_flags[tag] = false;
}
Referenced by NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualAndJacobianInternal(), and NonlinearSystemBase::computeResidualTags().
activeMatrixTag()
void SystemBase::activeMatrixTag (TagID tag) virtual
Active a matrix for tag.
Definition at line 1068 of file SystemBase.C.
{
  mooseAssert(_subproblem.matrixTagExists(tag),
              "Cannot active Matrix with matrix_tag : " << tag << "that does not exist");
  if (_matrix_tag_active_flags.size() < tag + 1)
    _matrix_tag_active_flags.resize(tag + 1);
  _matrix_tag_active_flags[tag] = true;
}
addMatrix()
SparseMatrix< Number > & SystemBase::addMatrix (TagID tag)
Adds a matrix with a given tag.
Parameters
tag_name The name of the tag
Definition at line 559 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag))
    mooseError("Cannot add tagged matrix with TagID ",
               tag,
               " in system '",
               name(),
               "' because the tag does not exist in the problem");
  if (hasMatrix(tag))
    return getMatrix(tag);
  const auto matrix_name = _subproblem.matrixTagName(tag);
  SparseMatrix<Number> & mat = system().add_matrix(matrix_name);
  associateMatrixToTag(mat, tag);
  return mat;
}
addScalingVector()
void SystemBase::addScalingVector ()
Add the scaling factor vector to the system.
Definition at line 1464 of file SystemBase.C.
{
  addVector("scaling_factors", /*project=*/false, libMesh::ParallelType::GHOSTED);
  _subproblem.hasScalingVector();
}
Referenced by MooseVariableBase::initialSetup().
addTimeIntegrator() [1/2]
virtual void SystemBase::addTimeIntegrator (const std::string & , const std::string & , InputParameters &) inline virtual
Reimplemented in AuxiliarySystem, DisplacedSystem, NonlinearSystemBase, AuxiliarySystem, and NonlinearSystemBase.
Definition at line 861 of file SystemBase.h.
  {
  }
addTimeIntegrator() [2/2]
virtual void SystemBase::addTimeIntegrator (std::shared_ptr< TimeIntegrator >) inline virtual
Reimplemented in DisplacedSystem, AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
Definition at line 867 of file SystemBase.h.
{}
addVariable()
void SystemBase::addVariable (const std::string & var_type, const std::string & var_name, InputParameters & parameters) virtual
Canonical method for adding a variable.
Parameters
var_type the type of the variable, e.g. MooseVariableScalar
var_name the variable name, e.g. 'u'
params the InputParameters from which to construct the variable
Reimplemented in AuxiliarySystem.
Definition at line 708 of file SystemBase.C.
{
  _numbered_vars.resize(libMesh::n_threads());
  auto components = parameters.get<unsigned int>("components");
  // Convert the std::vector parameter provided by the user into a std::set for use by libMesh's
  // System::add_variable method
  std::set<SubdomainID> blocks;
  const auto & block_param = parameters.get<std::vector<SubdomainName>>("block");
  for (const auto & subdomain_name : block_param)
  {
    SubdomainID blk_id = _mesh.getSubdomainID(subdomain_name);
    blocks.insert(blk_id);
  }
  auto fe_type = FEType(Utility::string_to_enum<Order>(parameters.get<MooseEnum>("order")),
                        Utility::string_to_enum<FEFamily>(parameters.get<MooseEnum>("family")));
  unsigned int var_num;
  if (var_type == "ArrayMooseVariable")
  {
    if (fe_type.family == NEDELEC_ONE || fe_type.family == LAGRANGE_VEC ||
        fe_type.family == MONOMIAL_VEC || fe_type.family == RAVIART_THOMAS)
      mooseError("Vector family type cannot be used in an array variable");
    // Build up the variable names
    std::vector<std::string> var_names;
    for (unsigned int i = 0; i < components; i++)
      var_names.push_back(SubProblem::arrayVariableComponent(name, i));
    // The number returned by libMesh is the _last_ variable number... we want to hold onto the
    // _first_
    var_num = system().add_variables(var_names, fe_type, &blocks) - (components - 1);
    // Set as array variable
    if (parameters.isParamSetByUser("array") && !parameters.get<bool>("array"))
      mooseError("Variable '",
                 name,
                 "' is an array variable ('components' > 1) but 'array' is set to false.");
    parameters.set<bool>("array") = true;
  }
  else
    var_num = system().add_variable(name, fe_type, &blocks);
  parameters.set<unsigned int>("_var_num") = var_num;
  parameters.set<SystemBase *>("_system_base") = this;
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    parameters.set<THREAD_ID>("tid") = tid;
    std::shared_ptr<MooseVariableBase> var =
        _factory.create<MooseVariableBase>(var_type, name, parameters, tid);
    _vars[tid].add(name, var);
    if (auto fe_var = dynamic_cast<MooseVariableFieldBase *>(var.get()))
    {
      auto required_size = var_num + components;
      if (required_size > _numbered_vars[tid].size())
        _numbered_vars[tid].resize(required_size);
      for (MooseIndex(components) component = 0; component < components; ++component)
        _numbered_vars[tid][var_num + component] = fe_var;
      if (auto * const functor = dynamic_cast<Moose::FunctorBase<ADReal> *>(fe_var))
        _subproblem.addFunctor(name, *functor, tid);
      else if (auto * const functor = dynamic_cast<Moose::FunctorBase<ADRealVectorValue> *>(fe_var))
        _subproblem.addFunctor(name, *functor, tid);
      else if (auto * const functor = dynamic_cast<Moose::FunctorBase<RealEigenVector> *>(fe_var))
        _subproblem.addFunctor(name, *functor, tid);
      else
        mooseError("This should be a functor");
    }
    if (var->blockRestricted())
      for (const SubdomainID & id : var->blockIDs())
        for (MooseIndex(components) component = 0; component < components; ++component)
          _var_map[var_num + component].insert(id);
    else
      for (MooseIndex(components) component = 0; component < components; ++component)
        _var_map[var_num + component] = std::set<SubdomainID>();
  }
  // getMaxVariableNumber is an API method used in Rattlesnake
  if (var_num > _max_var_number)
    _max_var_number = var_num;
}
Referenced by AuxiliarySystem::addVariable().
addVariableToCopy()
void SystemBase::addVariableToCopy (const std::string & dest_name, const std::string & source_name, const std::string & timestep) virtual
Add info about variable that will be copied.
Parameters
dest_name Name of the nodal variable being used for copying into (name is from the exodusII file)
source_name Name of the nodal variable being used for copying from (name is from the exodusII file)
timestep Timestep in the file being used
Definition at line 1143 of file SystemBase.C.
{
  _var_to_copy.push_back(VarCopyInfo(dest_name, source_name, timestep));
}
Referenced by CopyNodalVarsAction::act().
addVariableToZeroOnJacobian()
void SystemBase::addVariableToZeroOnJacobian (std::string var_name) virtual
Adds this variable to the list of variables to be zeroed during each Jacobian evaluation.
Parameters
var_name The name of the variable to be zeroed.
Reimplemented in DisplacedSystem.
Definition at line 169 of file SystemBase.C.
{
  _vars_to_be_zeroed_on_jacobian.push_back(var_name);
}
Referenced by ADDGKernel::ADDGKernel(), DisplacedSystem::addVariableToZeroOnJacobian(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), DGKernel::DGKernel(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), NodalBC::NodalBC(), and NodalKernel::NodalKernel().
addVariableToZeroOnResidual()
void SystemBase::addVariableToZeroOnResidual (std::string var_name) virtual
Adds this variable to the list of variables to be zeroed during each residual evaluation.
Parameters
var_name The name of the variable to be zeroed.
Reimplemented in DisplacedSystem.
Definition at line 163 of file SystemBase.C.
{
  _vars_to_be_zeroed_on_residual.push_back(var_name);
}
Referenced by ADDGKernel::ADDGKernel(), DisplacedSystem::addVariableToZeroOnResidual(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), DGKernel::DGKernel(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), NodalBC::NodalBC(), and NodalKernel::NodalKernel().
addVector() [1/2]
NumericVector< Number > & SystemBase::addVector (const std::string & vector_name, const bool project, const ParallelType type)
Adds a solution length vector to the system.
Parameters
vector_name The name of the vector.
project Whether or not to project this vector when doing mesh refinement. If the vector is just going to be recomputed then there is no need to project it.
type What type of parallel vector. This is usually either PARALLEL or GHOSTED. GHOSTED is needed if you are going to be accessing off-processor entries. The ghosting pattern is the same as the solution vector.
Definition at line 597 of file SystemBase.C.
{
  if (hasVector(vector_name))
    return getVector(vector_name);
  NumericVector<Number> & vec = system().add_vector(vector_name, project, type);
  return vec;
}
Referenced by AuxiliarySystem::addDotVectors(), NonlinearSystemBase::addDotVectors(), addScalingVector(), PicardSolve::allocateStorage(), SecantSolve::allocateStorage(), SteffensenSolve::allocateStorage(), AStableDirk4::AStableDirk4(), ExplicitTimeIntegrator::ExplicitTimeIntegrator(), NonlinearSystemBase::getResidualNonTimeVector(), NonlinearSystemBase::getResidualTimeVector(), CentralDifference::initialSetup(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), needSolutionState(), NonlinearSystemBase::residualGhosted(), and saveOldSolutions().
addVector() [2/2]
NumericVector< Number > & SystemBase::addVector (TagID tag, const bool project, const ParallelType type)
Adds a solution length vector to the system with the specified TagID.
Parameters
tag_name The name of the tag
project Whether or not to project this vector when doing mesh refinement. If the vector is just going to be recomputed then there is no need to project it.
type What type of parallel vector. This is usually either PARALLEL or GHOSTED. GHOSTED is needed if you are going to be accessing off-processor entries. The ghosting pattern is the same as the solution vector.
Definition at line 607 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot add tagged vector with TagID ",
               tag,
               " in system '",
               name(),
               "' because the tag does not exist in the problem");
  if (hasVector(tag))
  {
    auto & vec = getVector(tag);
    if (type != ParallelType::AUTOMATIC && vec.type() != type)
      mooseError("Cannot add tagged vector '",
                 _subproblem.vectorTagName(tag),
                 "', in system '",
                 name(),
                 "' because a vector with the same name was found with a different parallel type");
    return vec;
  }
  const auto vector_name = _subproblem.vectorTagName(tag);
  NumericVector<Number> & vec = system().add_vector(vector_name, project, type);
  associateVectorToTag(vec, tag);
  return vec;
}
applyScalingFactors()
void SystemBase::applyScalingFactors (const std::vector< Real > & inverse_scaling_factors)
Applies scaling factors to the system's variables.
Parameters
inverse_scaling_factors A vector containing the inverse of each variable's scaling factor, e.g. 1 / scaling_factor
Definition at line 1424 of file SystemBase.C.
{
  for (MooseIndex(_vars) thread = 0; thread < _vars.size(); ++thread)
  {
    auto & field_variables = _vars[thread].fieldVariables();
    for (MooseIndex(field_variables) i = 0; i < field_variables.size(); ++i)
      field_variables[i]->scalingFactor(1. / inverse_scaling_factors[i] *
                                        field_variables[i]->scalingFactor());
    auto offset = field_variables.size();
    auto & scalar_variables = _vars[thread].scalars();
    for (MooseIndex(scalar_variables) i = 0; i < scalar_variables.size(); ++i)
      scalar_variables[i]->scalingFactor(1. / inverse_scaling_factors[offset + i] *
                                         scalar_variables[i]->scalingFactor());
    if (thread == 0 && _verbose)
    {
      _console << "Automatic scaling factors:\n";
      auto original_flags = _console.flags();
      auto original_precision = _console.precision();
      _console.unsetf(std::ios_base::floatfield);
      _console.precision(6);
      for (const auto & field_variable : field_variables)
        _console << "  " << field_variable->name() << ": " << field_variable->scalingFactor()
                 << "\n";
      for (const auto & scalar_variable : scalar_variables)
        _console << "  " << scalar_variable->name() << ": " << scalar_variable->scalingFactor()
                 << "\n";
      _console << "\n" << std::endl;
      // restore state
      _console.flags(original_flags);
      _console.precision(original_precision);
    }
  }
}
Referenced by NonlinearSystemBase::computeScaling().
assignMaxVarNDofsPerElem()
void SystemBase::assignMaxVarNDofsPerElem (std::size_t max_dofs) inline
assign the maximum element dofs
Definition at line 575 of file SystemBase.h.
{ _max_var_n_dofs_per_elem = max_dofs; }
assignMaxVarNDofsPerNode()
void SystemBase::assignMaxVarNDofsPerNode (std::size_t max_dofs) inline
assign the maximum node dofs
Definition at line 580 of file SystemBase.h.
{ _max_var_n_dofs_per_node = max_dofs; }
associateMatrixToTag()
void SystemBase::associateMatrixToTag (SparseMatrix< Number > & matrix, TagID tag) virtual
Associate a matrix to a tag.
Reimplemented in DisplacedSystem.
Definition at line 1025 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag))
    mooseError("Cannot associate matrix to tag ", tag, " because that tag does not exist");
  if (_tagged_matrices.size() < tag + 1)
    _tagged_matrices.resize(tag + 1);
  _tagged_matrices[tag] = &matrix;
}
Referenced by addMatrix(), DisplacedSystem::associateMatrixToTag(), NonlinearSystemBase::computeJacobian(), FEProblemBase::computeJacobianInternal(), FEProblemBase::computeJacobianTag(), and FEProblemBase::computeResidualAndJacobian().
associateVectorToTag()
void SystemBase::associateVectorToTag (NumericVector< Number > & vec, TagID tag) virtual
Associate a vector for a given tag.
Reimplemented in DisplacedSystem.
Definition at line 930 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot associate vector to tag ", tag, " because that tag does not exist");
  if (_tagged_vectors.size() < tag + 1)
    _tagged_vectors.resize(tag + 1);
  _tagged_vectors[tag] = &vec;
}
Referenced by addVector(), DisplacedSystem::associateVectorToTag(), NonlinearSystemBase::computeNodalBCs(), FEProblemBase::computeResidual(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualTag(), NonlinearSystemBase::computeResidualTag(), FEProblemBase::computeResidualType(), and NonlinearSystemBase::setSolution().
augmentSendList()
void SystemBase::augmentSendList (std::vector< dof_id_type > & send_list) virtual
Will modify the send_list to add all of the extra ghosted dofs for this system.
Reimplemented in DisplacedSystem.
Definition at line 441 of file SystemBase.C.
{
  std::set<dof_id_type> & ghosted_elems = _subproblem.ghostedElems();
  DofMap & dof_map = dofMap();
  std::vector<dof_id_type> dof_indices;
  System & sys = system();
  unsigned int sys_num = sys.number();
  unsigned int n_vars = sys.n_vars();
  for (const auto & elem_id : ghosted_elems)
  {
    Elem * elem = _mesh.elemPtr(elem_id);
    if (elem->active())
    {
      dof_map.dof_indices(elem, dof_indices);
      // Only need to ghost it if it's actually not on this processor
      for (const auto & dof : dof_indices)
        if (dof < dof_map.first_dof() || dof >= dof_map.end_dof())
          send_list.push_back(dof);
      // Now add the DoFs from all of the nodes.  This is necessary because of block
      // restricted variables.  A variable might not live _on_ this element but it
      // might live on nodes connected to this element.
      for (unsigned int n = 0; n < elem->n_nodes(); n++)
      {
        Node * node = elem->node_ptr(n);
        // Have to get each variable's dofs
        for (unsigned int v = 0; v < n_vars; v++)
        {
          const Variable & var = sys.variable(v);
          unsigned int var_num = var.number();
          unsigned int n_comp = var.n_components();
          // See if this variable has any dofs at this node
          if (node->n_dofs(sys_num, var_num) > 0)
          {
            // Loop over components of the variable
            for (unsigned int c = 0; c < n_comp; c++)
              send_list.push_back(node->dof_number(sys_num, var_num, c));
          }
        }
      }
    }
  }
}
Referenced by DisplacedSystem::augmentSendList(), and extraSendList().
augmentSparsity()
virtual void SystemBase::augmentSparsity (SparsityPattern::Graph & sparsity, std::vector< dof_id_type > & n_nz, std::vector< dof_id_type > & n_oz) pure virtual
Will modify the sparsity pattern to add logical geometric connections.
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
Referenced by extraSparsity().
automaticScaling() [1/2]
bool SystemBase::automaticScaling () const inline
Getter for whether we are performing automatic scaling.
Returns
whether we are performing automatic scaling
Definition at line 117 of file SystemBase.h.
{ return _automatic_scaling; }
Referenced by SubProblem::automaticScaling().
automaticScaling() [2/2]
void SystemBase::automaticScaling (bool automatic_scaling) inline
Setter for whether we are performing automatic scaling.
Parameters
automatic_scaling A boolean representing whether we are performing automatic scaling
Definition at line 123 of file SystemBase.h.
{ _automatic_scaling = automatic_scaling; }
clearAllDofIndices()
void SystemBase::clearAllDofIndices ()
Clear all dof indices from moose variables.
Definition at line 1519 of file SystemBase.C.
{
  for (auto & var_warehouse : _vars)
    var_warehouse.clearAllDofIndices();
}
Referenced by SubProblem::clearAllDofIndices().
closeTaggedMatrices()
void SystemBase::closeTaggedMatrices (const std::set< TagID > & tags)
Close all matrices associated the tags.
Definition at line 1009 of file SystemBase.C.
{
  for (auto tag : tags)
    if (hasMatrix(tag))
      getMatrix(tag).close();
}
Referenced by NonlinearSystemBase::computeJacobianInternal(), and NonlinearSystemBase::computeResidualAndJacobianTags().
closeTaggedVector()
void SystemBase::closeTaggedVector (const TagID tag)
Close vector with the given tag.
Definition at line 638 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot close vector with TagID ",
               tag,
               " in system '",
               name(),
               "' because that tag does not exist in the problem");
  else if (!hasVector(tag))
    mooseError("Cannot close vector tag with name '",
               _subproblem.vectorTagName(tag),
               "' in system '",
               name(),
               "' because there is no vector associated with that tag");
  getVector(tag).close();
}
Referenced by closeTaggedVectors().
closeTaggedVectors()
void SystemBase::closeTaggedVectors (const std::set< TagID > & tags)
Close all vectors for given tags.
Definition at line 657 of file SystemBase.C.
{
  for (const auto tag : tags)
    closeTaggedVector(tag);
}
Referenced by NonlinearSystemBase::computeResidualAndJacobianTags(), and NonlinearSystemBase::computeResidualTags().
computeVariables()
virtual void SystemBase::computeVariables (const NumericVector< Number > &) inline virtual
Definition at line 852 of file SystemBase.h.
{}
computingScalingJacobian()
bool SystemBase::computingScalingJacobian () const
Whether we are computing an initial Jacobian for automatic variable scaling.
Definition at line 1471 of file SystemBase.C.
{
  return _subproblem.computingScalingJacobian();
}
Referenced by Assembly::addJacobianBlock(), Assembly::addJacobianBlockNonlocal(), Assembly::addJacobianNeighbor(), Assembly::cacheJacobianBlock(), EigenKernel::computeJacobian(), Kernel::computeJacobian(), VectorKernel::computeJacobian(), and FEProblemBase::computeJacobianTags().
copyOldSolutions()
void SystemBase::copyOldSolutions () virtual
Shifts the solutions backwards in time.
Definition at line 1254 of file SystemBase.C.
{
  const auto states =
      _solution_states[static_cast<unsigned short>(Moose::SolutionIterationType::Time)].size();
  if (states > 1)
    for (unsigned int i = states - 1; i > 0; --i)
      solutionState(i) = solutionState(i - 1);
  if (solutionUDotOld())
    *solutionUDotOld() = *solutionUDot();
  if (solutionUDotDotOld())
    *solutionUDotDotOld() = *solutionUDotDot();
  if (solutionPreviousNewton())
    *solutionPreviousNewton() = *currentSolution();
}
Referenced by EigenExecutionerBase::inversePowerIteration().
copySolutionsBackwards()
void SystemBase::copySolutionsBackwards () virtual
Copy current solution into old and older.
Definition at line 1227 of file SystemBase.C.
{
  system().update();
  // Copying the solutions backward so the current solution will become the old, and the old will
  // become older. The same applies to the nonlinear iterates.
  for (const auto iteration_index : index_range(_solution_states))
  {
    const auto states = _solution_states[iteration_index].size();
    if (states > 1)
      for (unsigned int i = states - 1; i > 0; --i)
        solutionState(i, Moose::SolutionIterationType(iteration_index)) =
            solutionState(i - 1, Moose::SolutionIterationType(iteration_index));
  }
  if (solutionUDotOld())
    *solutionUDotOld() = *solutionUDot();
  if (solutionUDotDotOld())
    *solutionUDotDotOld() = *solutionUDotDot();
  if (solutionPreviousNewton())
    *solutionPreviousNewton() = *currentSolution();
}
copyVars()
void SystemBase::copyVars (ExodusII_IO & io)
Definition at line 1151 of file SystemBase.C.
{
  int n_steps = io.get_num_time_steps();
  bool did_copy = false;
  for (const auto & vci : _var_to_copy)
  {
    int timestep = -1;
    if (vci._timestep == "LATEST")
      // Use the last time step in the file from which to retrieve the solution
      timestep = n_steps;
    else
    {
      timestep = MooseUtils::convert<int>(vci._timestep);
      if (timestep > n_steps)
        mooseError("Invalid value passed as \"initial_from_file_timestep\". Expected \"LATEST\" or "
                   "a valid integer between 1 and ",
                   n_steps,
                   " inclusive, received ",
                   vci._timestep);
    }
    did_copy = true;
    if (hasVariable(vci._dest_name))
    {
      const auto & var = getVariable(0, vci._dest_name);
      if (var.isArray())
      {
        const auto & array_var = getFieldVariable<RealEigenVector>(0, vci._dest_name);
        for (MooseIndex(var.count()) i = 0; i < var.count(); ++i)
        {
          const auto exodus_var = _subproblem.arrayVariableComponent(vci._source_name, i);
          const auto system_var = array_var.componentName(i);
          if (var.isNodal())
            io.copy_nodal_solution(system(), exodus_var, system_var, timestep);
          else
            io.copy_elemental_solution(system(), exodus_var, system_var, timestep);
        }
      }
      else
      {
        if (var.isNodal())
          io.copy_nodal_solution(system(), vci._dest_name, vci._source_name, timestep);
        else
          io.copy_elemental_solution(system(), vci._dest_name, vci._source_name, timestep);
      }
    }
    else if (hasScalarVariable(vci._dest_name))
      io.copy_scalar_solution(system(), {vci._dest_name}, {vci._source_name}, timestep);
    else
      mooseError("Unrecognized variable ", vci._dest_name, " in variables to copy.");
  }
  if (did_copy)
    solution().close();
}
currentSolution()
virtual const NumericVector< Number > *const & SystemBase::currentSolution () const pure virtual
The solution vector that is currently being operated on.
This is typically a ghosted vector that comes in from the Nonlinear solver.
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
Referenced by copyOldSolutions(), copySolutionsBackwards(), DisplacedSystem::currentSolution(), MooseVariableScalar::reinit(), and restoreSolutions().
customSetup()
void SystemBase::customSetup (const ExecFlagType & exec_type) virtual
Reimplemented in AuxiliarySystem, and NonlinearSystemBase.
Definition at line 1491 of file SystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _vars[tid].customSetup(exec_type);
}
Referenced by customSetup(), AuxiliarySystem::customSetup(), and NonlinearSystemBase::customSetup().
deactiveAllMatrixTags()
void SystemBase::deactiveAllMatrixTags () virtual
Make matrices inactive.
Definition at line 1092 of file SystemBase.C.
{
  auto num_matrix_tags = _subproblem.numMatrixTags();
  _matrix_tag_active_flags.resize(num_matrix_tags);
  for (decltype(num_matrix_tags) tag = 0; tag < num_matrix_tags; tag++)
    _matrix_tag_active_flags[tag] = false;
}
Referenced by NonlinearSystemBase::computeResidualTags(), and NonlinearSystemBase::setInitialSolution().
deactiveMatrixTag()
void SystemBase::deactiveMatrixTag (TagID tag) virtual
deactive a matrix for tag
Definition at line 1080 of file SystemBase.C.
{
  mooseAssert(_subproblem.matrixTagExists(tag),
              "Cannot deactivate Matrix with matrix_tag : " << tag << "that does not exist");
  if (_matrix_tag_active_flags.size() < tag + 1)
    _matrix_tag_active_flags.resize(tag + 1);
  _matrix_tag_active_flags[tag] = false;
}
defaultMatrixTags()
virtual std::set< TagID > SystemBase::defaultMatrixTags () const inline virtual
Get the default matrix tags associted with this system.
Reimplemented in DisplacedSystem, and NonlinearEigenSystem.
Definition at line 287 of file SystemBase.h.
{ return {systemMatrixTag()}; }
Referenced by DisplacedSystem::defaultMatrixTags(), NonlinearEigenSystem::defaultMatrixTags(), and disassociateDefaultMatrixTags().
defaultVectorTags()
virtual std::set< TagID > SystemBase::defaultVectorTags () const inline virtual
Get the default vector tags associated with this system.
Reimplemented in DisplacedSystem, and NonlinearEigenSystem.
Definition at line 280 of file SystemBase.h.
  {
    return {timeVectorTag(), nonTimeVectorTag(), residualVectorTag()};
  }
Referenced by DisplacedSystem::defaultVectorTags(), NonlinearEigenSystem::defaultVectorTags(), and disassociateDefaultVectorTags().
disassociateDefaultMatrixTags()
void SystemBase::disassociateDefaultMatrixTags () virtual
Disassociate the matrices associated with the default matrix tags of this system.
Reimplemented in DisplacedSystem.
Definition at line 1059 of file SystemBase.C.
{
  const auto tags = defaultMatrixTags();
  for (const auto tag : tags)
    if (_subproblem.matrixTagExists(tag))
      disassociateMatrixFromTag(tag);
}
Referenced by DisplacedSystem::disassociateDefaultMatrixTags().
disassociateDefaultVectorTags()
void SystemBase::disassociateDefaultVectorTags () virtual
Disassociate the vectors associated with the default vector tags of this system.
Reimplemented in DisplacedSystem.
Definition at line 964 of file SystemBase.C.
{
  const auto tags = defaultVectorTags();
  for (const auto tag : tags)
    if (_subproblem.vectorTagExists(tag))
      disassociateVectorFromTag(tag);
}
Referenced by DisplacedSystem::disassociateDefaultVectorTags().
disassociateMatrixFromTag() [1/2]
void SystemBase::disassociateMatrixFromTag (SparseMatrix< Number > & matrix, TagID tag) virtual
Disassociate a matrix from a tag.
Reimplemented in DisplacedSystem.
Definition at line 1037 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag))
    mooseError("Cannot disassociate matrix from tag ", tag, " because that tag does not exist");
  if (hasMatrix(tag) && &getMatrix(tag) != &matrix)
    mooseError("You can not disassociate a matrix from a tag which it was not associated to");
  disassociateMatrixFromTag(tag);
}
Referenced by NonlinearSystemBase::computeJacobian(), FEProblemBase::computeJacobianInternal(), FEProblemBase::computeJacobianTag(), FEProblemBase::computeResidualAndJacobian(), disassociateDefaultMatrixTags(), disassociateMatrixFromTag(), and DisplacedSystem::disassociateMatrixFromTag().
disassociateMatrixFromTag() [2/2]
void SystemBase::disassociateMatrixFromTag (TagID tag) virtual
Disassociate any matrix that is associated with a given tag.
Reimplemented in DisplacedSystem.
Definition at line 1048 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag))
    mooseError("Cannot disassociate matrix from tag ", tag, " because that tag does not exist");
  if (_tagged_matrices.size() < tag + 1)
    _tagged_matrices.resize(tag + 1);
  _tagged_matrices[tag] = nullptr;
}
disassociateVectorFromTag() [1/2]
void SystemBase::disassociateVectorFromTag (NumericVector< Number > & vec, TagID tag) virtual
Disassociate a given vector from a given tag.
Reimplemented in DisplacedSystem.
Definition at line 942 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot disassociate vector from tag ", tag, " because that tag does not exist");
  if (hasVector(tag) && &getVector(tag) != &vec)
    mooseError("You can not disassociate a vector from a tag which it was not associated to");
  disassociateVectorFromTag(tag);
}
Referenced by NonlinearSystemBase::computeNodalBCs(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualTag(), NonlinearSystemBase::computeResidualTag(), FEProblemBase::computeResidualType(), disassociateDefaultVectorTags(), disassociateVectorFromTag(), DisplacedSystem::disassociateVectorFromTag(), and CentralDifference::initialSetup().
disassociateVectorFromTag() [2/2]
void SystemBase::disassociateVectorFromTag (TagID tag) virtual
Disassociate any vector that is associated with a given tag.
Reimplemented in DisplacedSystem.
Definition at line 953 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot disassociate vector from tag ", tag, " because that tag does not exist");
  if (_tagged_vectors.size() < tag + 1)
    _tagged_vectors.resize(tag + 1);
  _tagged_vectors[tag] = nullptr;
}
dofMap() [1/2]
DofMap & SystemBase::dofMap () virtual
Gets writeable reference to the dof map.
Definition at line 1131 of file SystemBase.C.
{
  return system().get_dof_map();
}
Referenced by NonlinearSystemBase::assembleScalingVector(), MooseApp::attachRelationshipManagers(), augmentSendList(), NonlinearSystemBase::augmentSparsity(), NonlinearSystemBase::computeScaling(), NonlinearSystemBase::findImplicitGeometricCouplingEntries(), Adaptivity::init(), ActivateElementsUserObjectBase::initSolutions(), PNGOutput::makeMeshFunc(), GhostingUserObject::meshChanged(), Exodus::outputScalarVariables(), Nemesis::outputScalarVariables(), TableOutput::outputScalarVariables(), and ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes().
dofMap() [2/2]
const DofMap & SystemBase::dofMap () const virtual
Gets const reference to the dof map.
Definition at line 1137 of file SystemBase.C.
{
  return system().get_dof_map();
}
duDotDotDu() [1/2]
virtual Number & SystemBase::duDotDotDu () inline virtual
Reimplemented in DisplacedSystem.
Definition at line 223 of file SystemBase.h.
{ return _du_dotdot_du; }
Referenced by DisplacedSystem::duDotDotDu(), and MooseVariableScalar::reinit().
duDotDotDu() [2/2]
virtual const Number & SystemBase::duDotDotDu () const inline virtual
Reimplemented in DisplacedSystem.
Definition at line 225 of file SystemBase.h.
{ return _du_dotdot_du; }
duDotDu() [1/2]
virtual Number & SystemBase::duDotDu () inline virtual
Reimplemented in DisplacedSystem.
Definition at line 222 of file SystemBase.h.
{ return _du_dot_du; }
Referenced by DisplacedSystem::duDotDu(), and MooseVariableScalar::reinit().
duDotDu() [2/2]
virtual const Number & SystemBase::duDotDu () const inline virtual
Reimplemented in DisplacedSystem.
Definition at line 224 of file SystemBase.h.
{ return _du_dot_du; }
flushTaggedMatrices()
void SystemBase::flushTaggedMatrices (const std::set< TagID > & tags)
flushes all matrices associated to tags.
Flush assembles the matrix but doesn't shrink memory allocation
Definition at line 1017 of file SystemBase.C.
{
  for (auto tag : tags)
    if (hasMatrix(tag))
      getMatrix(tag).flush();
}
getActualFieldVariable() [1/2]
template<typename T > template MooseVariableField< RealEigenVector > & SystemBase::getActualFieldVariable< RealEigenVector > (THREAD_ID tid, const std::string & var_name)
Returns a field variable pointer - this includes finite volume variables.
Definition at line 107 of file SystemBase.C.
{
  return *_vars[tid].getActualFieldVariable<T>(var_name);
}
Referenced by BoundsAuxBase::BoundsAuxBase(), Assembly::copyFaceShapes(), Assembly::copyNeighborShapes(), and Assembly::copyShapes().
getActualFieldVariable() [2/2]
template<typename T > template MooseVariableField< RealEigenVector > & SystemBase::getActualFieldVariable< RealEigenVector > (THREAD_ID tid, unsigned int var_number)
Returns a field variable pointer - this includes finite volume variables.
Definition at line 128 of file SystemBase.C.
{
  return *_vars[tid].getActualFieldVariable<T>(var_number);
}
getFieldVariable() [1/2]
template<typename T > template MooseVariableFE< RealEigenVector > & SystemBase::getFieldVariable< RealEigenVector > (THREAD_ID tid, const std::string & var_name)
Gets a reference to a variable of with specified name.
This excludes and cannot return finite volume variables.
Parameters
tid Thread id
var_name variable name
Returns
reference the variable (class)
Definition at line 100 of file SystemBase.C.
{
  return *_vars[tid].getFieldVariable<T>(var_name);
}
Referenced by Marker::getMarkerValue().
getFieldVariable() [2/2]
template<typename T > template MooseVariableFE< RealEigenVector > & SystemBase::getFieldVariable< RealEigenVector > (THREAD_ID tid, unsigned int var_number)
Gets a reference to a variable with specified number.
This excludes and cannot return finite volume variables.
Parameters
tid Thread id
var_number libMesh variable number
Returns
reference the variable (class)
Definition at line 121 of file SystemBase.C.
{
  return *_vars[tid].getFieldVariable<T>(var_number);
}
getFVVariable()
template<typename T > template MooseVariableFV< Real > & SystemBase::getFVVariable< Real > (THREAD_ID tid, const std::string & var_name)
Return a finite volume variable.
Definition at line 114 of file SystemBase.C.
{
  return *_vars[tid].getFVVariable<T>(var_name);
}
getMatrix() [1/2]
SparseMatrix< Number > & SystemBase::getMatrix (TagID tag) virtual
Get a raw SparseMatrix.
Reimplemented in DisplacedSystem.
Definition at line 973 of file SystemBase.C.
{
  if (!hasMatrix(tag))
  {
    if (!_subproblem.matrixTagExists(tag))
      mooseError("Cannot retreive matrix with tag ", tag, " because that tag does not exist");
    else
      mooseError("Cannot retreive matrix with tag ",
                 tag,
                 " in system '",
                 name(),
                 "'\nbecause a matrix has not been associated with that tag.");
  }
  return *_tagged_matrices[tag];
}
Referenced by Assembly::addCachedJacobian(), NonlinearSystemBase::addImplicitGeometricCouplingEntries(), Assembly::addJacobianCoupledVarPair(), Assembly::addJacobianLowerD(), Assembly::addJacobianNeighbor(), Assembly::addJacobianNeighborLowerD(), Assembly::addJacobianNonlocal(), addMatrix(), closeTaggedMatrices(), NonlinearSystemBase::computeJacobianInternal(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::constraintJacobians(), disassociateMatrixFromTag(), NonlinearSystemBase::enforceNodalConstraintsJacobian(), flushTaggedMatrices(), DisplacedSystem::getMatrix(), MooseVariableScalar::reinit(), Assembly::setCachedJacobian(), and Assembly::zeroCachedJacobian().
getMatrix() [2/2]
const SparseMatrix< Number > & SystemBase::getMatrix (TagID tag) const virtual
Get a raw SparseMatrix.
Reimplemented in DisplacedSystem.
Definition at line 991 of file SystemBase.C.
{
  if (!hasMatrix(tag))
  {
    if (!_subproblem.matrixTagExists(tag))
      mooseError("Cannot retreive matrix with tag ", tag, " because that tag does not exist");
    else
      mooseError("Cannot retreive matrix with tag ",
                 tag,
                 " in system '",
                 name(),
                 "'\nbecause a matrix has not been associated with that tag.");
  }
  return *_tagged_matrices[tag];
}
getMaxVariableNumber()
unsigned int SystemBase::getMaxVariableNumber () const inline
Returns the maximum number of all variables on the system.
Definition at line 850 of file SystemBase.h.
{ return _max_var_number; }
getMaxVarNDofsPerElem()
std::size_t SystemBase::getMaxVarNDofsPerElem () const inline
Gets the maximum number of dofs used by any one variable on any one element.
Returns
The max
Definition at line 563 of file SystemBase.h.
{ return _max_var_n_dofs_per_elem; }
Referenced by Moose::globalDofIndexToDerivative().
getMaxVarNDofsPerNode()
std::size_t SystemBase::getMaxVarNDofsPerNode () const inline
Gets the maximum number of dofs used by any one variable on any one node.
Returns
The max
Definition at line 570 of file SystemBase.h.
{ return _max_var_n_dofs_per_node; }
getMinQuadratureOrder()
Order SystemBase::getMinQuadratureOrder () virtual
Get minimal quadrature order needed for integrating variables in this system.
Returns
The minimal order of quadrature
Reimplemented in AuxiliarySystem.
Definition at line 230 of file SystemBase.C.
{
  Order order = CONSTANT;
  const std::vector<MooseVariableFieldBase *> & vars = _vars[0].fieldVariables();
  for (const auto & var : vars)
  {
    FEType fe_type = var->feType();
    if (fe_type.default_quadrature_order() > order)
      order = fe_type.default_quadrature_order();
  }
  return order;
}
getScalarVariable() [1/2]
MooseVariableScalar & SystemBase::getScalarVariable (THREAD_ID tid, const std::string & var_name) const virtual
Gets a reference to a scalar variable with specified number.
Parameters
tid Thread id
var_name A string which is the name of the variable to get.
Returns
reference the variable (class)
Definition at line 134 of file SystemBase.C.
{
  MooseVariableScalar * var = dynamic_cast<MooseVariableScalar *>(_vars[tid].getVariable(var_name));
  if (!var)
    mooseError("Scalar variable '" + var_name + "' does not exist in this system");
  return *var;
}
Referenced by Assembly::addJacobianOffDiagScalar(), MortarScalarBase::computeOffDiagJacobianScalar(), ArrayIntegratedBC::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), ArrayKernel::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), DMMooseSetVariables(), Assembly::init(), ReferenceResidualProblem::initialSetup(), and NonlinearSystemBase::setupScalingData().
getScalarVariable() [2/2]
MooseVariableScalar & SystemBase::getScalarVariable (THREAD_ID tid, unsigned int var_number) const virtual
Gets a reference to a variable with specified number.
Parameters
tid Thread id
var_number libMesh variable number
Returns
reference the variable (class)
Definition at line 143 of file SystemBase.C.
{
  MooseVariableScalar * var =
      dynamic_cast<MooseVariableScalar *>(_vars[tid].getVariable(var_number));
  if (!var)
    mooseError("variable #" + Moose::stringify(var_number) + " does not exist in this system");
  return *var;
}
getScalarVariables()
const std::vector< MooseVariableScalar * > & SystemBase::getScalarVariables (THREAD_ID tid) inline
Definition at line 737 of file SystemBase.h.
  {
    return _vars[tid].scalars();
  }
Referenced by Assembly::addResidualScalar(), ODEKernel::computeJacobian(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), AuxiliarySystem::computeScalarVars(), Assembly::init(), initSolutionState(), NonlinearThread::onElement(), Assembly::prepareOffDiagScalar(), and Assembly::prepareScalar().
getSharedTimeIntegrator()
std::shared_ptr< TimeIntegrator > SystemBase::getSharedTimeIntegrator () inline
Definition at line 872 of file SystemBase.h.
{ return _time_integrator; }
Referenced by DisplacedProblem::DisplacedProblem().
getStandardFieldVariableNames()
void SystemBase::getStandardFieldVariableNames (std::vector< VariableName > & std_field_variables) const
getSubdomainsForVar() [1/2]
const std::set< SubdomainID > & SystemBase::getSubdomainsForVar (const std::string & var_name) const inline
Get the block where a variable of this system is defined.
Parameters
var_name The name of the variable
Returns
the set of subdomain ids where the variable is active (defined)
Definition at line 753 of file SystemBase.h.
  {
    return getSubdomainsForVar(getVariable(0, var_name).number());
  }
getSubdomainsForVar() [2/2]
const std::set< SubdomainID > & SystemBase::getSubdomainsForVar (unsigned int var_number) const inline
Definition at line 742 of file SystemBase.h.
  {
    return _var_map.at(var_number);
  }
Referenced by NonlinearSystemBase::checkKernelCoverage(), and getSubdomainsForVar().
getTimeIntegrator() [1/2]
TimeIntegrator * SystemBase::getTimeIntegrator () inline
Definition at line 869 of file SystemBase.h.
{ return _time_integrator.get(); }
Referenced by Transient::endStep(), AB2PredictorCorrector::estimateTimeError(), Transient::getTimeIntegratorName(), MooseVariableData< OutputType >::MooseVariableData(), and Transient::preExecute().
getTimeIntegrator() [2/2]
const TimeIntegrator * SystemBase::getTimeIntegrator () const inline
Definition at line 870 of file SystemBase.h.
{ return _time_integrator.get(); }
getVariable() [1/2]
MooseVariableFieldBase & SystemBase::getVariable (THREAD_ID tid, const std::string & var_name) const
Gets a reference to a variable of with specified name.
Parameters
tid Thread id
var_name variable name
Returns
reference the variable (class)
Definition at line 79 of file SystemBase.C.
{
  MooseVariableFieldBase * var =
      dynamic_cast<MooseVariableFieldBase *>(_vars[tid].getVariable(var_name));
  if (!var)
    mooseError("Variable '", var_name, "' does not exist in this system");
  return *var;
}
Referenced by AdaptivityAction::act(), Assembly::addJacobianBlock(), Assembly::addJacobianBlockNonlocal(), FEProblemBase::addJacobianBlockTags(), Assembly::addJacobianNeighbor(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), Assembly::copyFaceShapes(), Assembly::copyNeighborShapes(), Assembly::copyShapes(), copyVars(), DMMooseSetVariables(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), NodeElemConstraint::getConnectedDofIndices(), NodeFaceConstraint::getConnectedDofIndices(), getSubdomainsForVar(), ResidualObject::getVariable(), Assembly::init(), NodalNormalsPreprocessor::initialize(), ReferenceResidualProblem::initialSetup(), Assembly::initNonlocalCoupling(), PNGOutput::makeMeshFunc(), FEProblemBase::prepare(), Assembly::prepareBlock(), Assembly::prepareBlockNonlocal(), AddPeriodicBCAction::setPeriodicVars(), NonlinearSystemBase::setupScalingData(), UpdateErrorVectorsThread::UpdateErrorVectorsThread(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
getVariable() [2/2]
MooseVariableFieldBase & SystemBase::getVariable (THREAD_ID tid, unsigned int var_number) const
Gets a reference to a variable with specified number.
Parameters
tid Thread id
var_number libMesh variable number
Returns
reference the variable (class)
Definition at line 89 of file SystemBase.C.
{
  if (var_number < _numbered_vars[tid].size())
    if (_numbered_vars[tid][var_number])
      return *_numbered_vars[tid][var_number];
  mooseError("Variable #", Moose::stringify(var_number), " does not exist in this system");
}
getVariableBlocks()
const std::set< SubdomainID > * SystemBase::getVariableBlocks (unsigned int var_number) virtual
Get the block where a variable of this system is defined.
Parameters
var_number The number of the variable
Returns
the set of subdomain ids where the variable is active (defined)
Definition at line 153 of file SystemBase.C.
{
  mooseAssert(_var_map.find(var_number) != _var_map.end(), "Variable does not exist.");
  if (_var_map[var_number].empty())
    return nullptr;
  else
    return &_var_map[var_number];
}
Referenced by PhysicsBasedPreconditioner::addSystem().
getVariableGlobalDoFs()
const std::vector< dof_id_type > & SystemBase::getVariableGlobalDoFs () inline
Get the global dof indices of a variable, this needs to be called after the indices have been set by setVariableGlobalDoFs
Definition at line 825 of file SystemBase.h.
{ return _var_all_dof_indices; }
getVariableNames()
const std::vector< VariableName > & SystemBase::getVariableNames () const inline
Definition at line 843 of file SystemBase.h.
{ return _vars[0].names(); }
Referenced by MooseEigenSystem::buildSystemDoFIndices(), NonlinearSystemBase::checkKernelCoverage(), hasVariable(), isArrayVariable(), AddPeriodicBCAction::setPeriodicVars(), and SingleMatrixPreconditioner::SingleMatrixPreconditioner().
getVariables()
const std::vector< MooseVariableFieldBase * > & SystemBase::getVariables (THREAD_ID tid) inline
Definition at line 732 of file SystemBase.h.
  {
    return _vars[tid].fieldVariables();
  }
Referenced by Assembly::addJacobianOffDiagScalar(), Assembly::addResidual(), Assembly::addResidualLower(), Assembly::addResidualNeighbor(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), Assembly::cacheResidual(), Assembly::cacheResidualLower(), Assembly::cacheResidualNeighbor(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), Assembly::init(), Assembly::initNonlocalCoupling(), initSolutionState(), Assembly::prepareLowerD(), Assembly::prepareNeighbor(), Assembly::prepareOffDiagScalar(), Assembly::prepareResidual(), Assembly::setResidual(), and Assembly::setResidualNeighbor().
getVector() [1/4]
NumericVector< Number > & SystemBase::getVector (const std::string & name) virtual
Get a raw NumericVector by name.
Get a raw NumericVector with the given name.
Reimplemented in DisplacedSystem.
Definition at line 882 of file SystemBase.C.
{
  return system().get_vector(name);
}
Referenced by Assembly::addCachedResiduals(), Assembly::addResidual(), Assembly::addResidualLower(), Assembly::addResidualNeighbor(), Assembly::addResidualScalar(), addVector(), NonlinearSystemBase::assembleScalingVector(), closeTaggedVector(), FEProblemBase::computeBounds(), FEProblemBase::computeNearNullSpace(), FEProblemBase::computeNullSpace(), NonlinearSystemBase::computeResidualAndJacobianTags(), NonlinearSystemBase::computeResidualTags(), CentralDifference::computeTimeDerivatives(), FEProblemBase::computeTransposeNullSpace(), disassociateVectorFromTag(), DisplacedSystem::getVector(), Assembly::hasScalingVector(), needSolutionState(), ReferenceResidualProblem::ReferenceResidualProblem(), MooseVariableScalar::reinit(), PicardSolve::saveVariableValues(), SecantSolve::saveVariableValues(), SteffensenSolve::saveVariableValues(), NonlinearSystemBase::setPreviousNewtonSolution(), TaggingInterface::setResidual(), solutionPreviousNewton(), solutionState(), MultiAppDofCopyTransfer::transfer(), PicardSolve::transformVariables(), SecantSolve::transformVariables(), SteffensenSolve::transformVariables(), and zeroTaggedVector().
getVector() [2/4]
const NumericVector< Number > & SystemBase::getVector (const std::string & name) const virtual
Reimplemented in DisplacedSystem.
Definition at line 888 of file SystemBase.C.
{
  return system().get_vector(name);
}
getVector() [3/4]
NumericVector< Number > & SystemBase::getVector (TagID tag) virtual
Get a raw NumericVector by tag.
Reimplemented in DisplacedSystem.
Definition at line 894 of file SystemBase.C.
{
  if (!hasVector(tag))
  {
    if (!_subproblem.vectorTagExists(tag))
      mooseError("Cannot retreive vector with tag ", tag, " because that tag does not exist");
    else
      mooseError("Cannot retreive vector with tag ",
                 tag,
                 " in system '",
                 name(),
                 "'\nbecause a vector has not been associated with that tag.");
  }
  return *_tagged_vectors[tag];
}
getVector() [4/4]
const NumericVector< Number > & SystemBase::getVector (TagID tag) const virtual
Reimplemented in DisplacedSystem.
Definition at line 912 of file SystemBase.C.
{
  if (!hasVector(tag))
  {
    if (!_subproblem.vectorTagExists(tag))
      mooseError("Cannot retreive vector with tag ", tag, " because that tag does not exist");
    else
      mooseError("Cannot retreive vector with tag ",
                 tag,
                 " in system '",
                 name(),
                 "'\nbecause a vector has not been associated with that tag.");
  }
  return *_tagged_vectors[tag];
}
hasMatrix()
virtual bool SystemBase::hasMatrix (TagID tag) const inline virtual
Check if the tagged matrix exists in the system.
Reimplemented in DisplacedSystem.
Definition at line 328 of file SystemBase.h.
  {
    return tag < _tagged_matrices.size() && _tagged_matrices[tag];
  }
Referenced by activeAllMatrixTags(), Assembly::addCachedJacobian(), NonlinearSystemBase::addImplicitGeometricCouplingEntries(), Assembly::addJacobianCoupledVarPair(), Assembly::addJacobianLowerD(), Assembly::addJacobianNeighbor(), Assembly::addJacobianNeighborLowerD(), Assembly::addJacobianNonlocal(), addMatrix(), Assembly::cacheJacobian(), Assembly::cacheJacobianBlock(), Assembly::cacheJacobianBlockNonzero(), Assembly::cacheJacobianCoupledVarPair(), Assembly::cacheJacobianMortar(), Assembly::cacheJacobianNeighbor(), Assembly::cacheJacobianNonlocal(), closeTaggedMatrices(), NonlinearSystemBase::computeJacobianInternal(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::constraintJacobians(), disassociateMatrixFromTag(), NonlinearSystemBase::enforceNodalConstraintsJacobian(), flushTaggedMatrices(), getMatrix(), DisplacedSystem::hasMatrix(), MooseVariableScalar::reinit(), removeMatrix(), Assembly::setCachedJacobian(), and Assembly::zeroCachedJacobian().
hasScalarVariable()
bool SystemBase::hasScalarVariable (const std::string & var_name) const virtual
Definition at line 825 of file SystemBase.C.
{
  if (system().has_variable(var_name))
    return system().variable_type(var_name).family == SCALAR;
  else
    return false;
}
Referenced by MortarScalarBase::computeJacobian(), NonlinearSystemBase::computeJacobianInternal(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), copyVars(), NonlinearEigenSystem::postAddResidualObject(), AddPeriodicBCAction::setPeriodicVars(), and NonlinearSystemBase::setupScalingData().
hasSolutionState()
bool SystemBase::hasSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) const inline virtual
Whether or not the system has the solution state (0 = current, 1 = old, 2 = older, etc).
Reimplemented in DisplacedSystem.
Definition at line 1004 of file SystemBase.h.
{
  return _solution_states[static_cast<unsigned short>(iteration_type)].size() > state;
}
Referenced by PointwiseRenormalizeVector::execute(), PointwiseRenormalizeVector::finalize(), DisplacedSystem::hasSolutionState(), needSolutionState(), restoreSolutions(), ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes(), and solutionState().
hasVarCopy()
bool SystemBase::hasVarCopy () const inline
Whether or not there are variables to be restarted from an Exodus mesh file.
Definition at line 875 of file SystemBase.h.
{ return _var_to_copy.size() > 0; }
hasVariable()
bool SystemBase::hasVariable (const std::string & var_name) const virtual
Query a system for a variable.
Parameters
var_name name of the variable
Returns
true if the variable exists
Definition at line 800 of file SystemBase.C.
{
  auto & names = getVariableNames();
  if (system().has_variable(var_name))
    return system().variable_type(var_name).family != SCALAR;
  if (std::find(names.begin(), names.end(), var_name) != names.end())
    // array variable
    return true;
  else
    return false;
}
Referenced by ADDGKernel::ADDGKernel(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayKernel::ArrayKernel(), copyVars(), DGKernel::DGKernel(), DMMooseSetVariables(), FEProblemBase::duplicateVariableCheck(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), PNGOutput::makeMeshFunc(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NonlinearSystemBase::setupScalingData(), and Coupleable::writableCoupledValue().
hasVector() [1/2]
bool SystemBase::hasVector (const std::string & tag_name) const
Check if the named vector exists in the system.
Definition at line 873 of file SystemBase.C.
{
  return system().have_vector(name);
}
Referenced by FEProblemBase::addCachedResidualDirectly(), Assembly::addCachedResiduals(), Assembly::addResidual(), Assembly::addResidualLower(), Assembly::addResidualNeighbor(), Assembly::addResidualScalar(), addVector(), NonlinearSystemBase::assembleScalingVector(), Assembly::cacheResidual(), Assembly::cacheResidualLower(), Assembly::cacheResidualNeighbor(), closeTaggedVector(), FEProblemBase::computeBounds(), NonlinearSystemBase::computeResidualTags(), CentralDifference::computeTimeDerivatives(), disassociateVectorFromTag(), getVector(), DisplacedSystem::hasVector(), MooseVariableScalar::reinit(), removeVector(), SubProblem::selectVectorTagsFromSystem(), NonlinearSystemBase::setPreviousNewtonSolution(), TaggingInterface::setResidual(), solutionPreviousNewton(), and zeroTaggedVector().
hasVector() [2/2]
virtual bool SystemBase::hasVector (TagID tag_id) const inline virtual
Check if the tagged vector exists in the system.
Reimplemented in DisplacedSystem.
Definition at line 249 of file SystemBase.h.
  {
    return tag_id < _tagged_vectors.size() && _tagged_vectors[tag_id];
  }
init()
virtual void SystemBase::init () inline virtual
Initialize the system.
Reimplemented in NonlinearSystem, and NonlinearSystemBase.
Definition at line 150 of file SystemBase.h.
{};
Referenced by NonlinearSystemBase::init().
initializeObjects()
virtual void SystemBase::initializeObjects () inline virtual
Called only once, just before the solve begins so objects can do some precalculations.
Definition at line 155 of file SystemBase.h.
{};
initialSetup()
void SystemBase::initialSetup () virtual
Setup Functions.
Reimplemented in AuxiliarySystem, and NonlinearSystemBase.
Definition at line 1477 of file SystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _vars[tid].initialSetup();
}
Referenced by initialSetup(), AuxiliarySystem::initialSetup(), and NonlinearSystemBase::initialSetup().
initSolutionState()
void SystemBase::initSolutionState () virtual
Initializes the solution state.
Reimplemented in DisplacedSystem.
Definition at line 1321 of file SystemBase.C.
{
  // Default is the current solution
  unsigned int state = 0;
  // Add additional states as required by the variable states requested
  for (const auto & var : getVariables(/* tid = */ 0))
    state = std::max(state, var->oldestSolutionStateRequested());
  for (const auto & var : getScalarVariables(/* tid = */ 0))
    state = std::max(state, var->oldestSolutionStateRequested());
  needSolutionState(state, Moose::SolutionIterationType::Time);
  _solution_states_initialized = true;
}
Referenced by DisplacedSystem::initSolutionState().
isArrayVariable()
bool SystemBase::isArrayVariable (const std::string & var_name) const virtual
If a variable is an array variable.
Definition at line 813 of file SystemBase.C.
{
  auto & names = getVariableNames();
  if (!system().has_variable(var_name) &&
      std::find(names.begin(), names.end(), var_name) != names.end())
    // array variable
    return true;
  else
    return false;
}
isScalarVariable()
bool SystemBase::isScalarVariable (unsigned int var_name) const virtual
Definition at line 834 of file SystemBase.C.
{
  return (system().variable(var_num).type().family == SCALAR);
}
Referenced by Assembly::init(), ReferenceResidualProblem::initialSetup(), and Assembly::initNonlocalCoupling().
jacobianSetup()
void SystemBase::jacobianSetup () virtual
Reimplemented in AuxiliarySystem, and NonlinearSystemBase.
Definition at line 1512 of file SystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _vars[tid].jacobianSetup();
}
Referenced by jacobianSetup(), AuxiliarySystem::jacobianSetup(), and NonlinearSystemBase::jacobianSetup().
matrixTagActive()
bool SystemBase::matrixTagActive (TagID tag) const virtual
If or not a matrix tag is active.
Definition at line 1117 of file SystemBase.C.
{
  mooseAssert(_subproblem.matrixTagExists(tag), "Matrix tag " << tag << " does not exist");
  return tag < _matrix_tag_active_flags.size() && _matrix_tag_active_flags[tag];
}
mesh() [1/2]
virtual MooseMesh & SystemBase::mesh () inline virtual
Definition at line 96 of file SystemBase.h.
{ return _mesh; }
Referenced by CreateDisplacedProblemAction::addProxyRelationshipManagers(), NonlinearSystemBase::computeScaling(), DMMooseGetEmbedding_Private(), DMSetUp_Moose_Pre(), SolutionIC::initialSetup(), MooseVariableData< OutputType >::MooseVariableData(), ComputeNodalKernelJacobiansThread::onNode(), ComputeNodalKernelsThread::onNode(), and ComputeNodalUserObjectsThread::onNode().
mesh() [2/2]
virtual const MooseMesh & SystemBase::mesh () const inline virtual
Definition at line 97 of file SystemBase.h.
{ return _mesh; }
name()
const std::string & SystemBase::name () const virtual
Definition at line 1297 of file SystemBase.C.
{
  return system().name();
}
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addConstraint(), NonlinearSystemBase::addDamper(), NonlinearSystemBase::addDGKernel(), NonlinearSystemBase::addDiracKernel(), NonlinearSystemBase::addInterfaceKernel(), AuxiliarySystem::addKernel(), MooseEigenSystem::addKernel(), NonlinearSystemBase::addKernel(), addMatrix(), NonlinearSystemBase::addNodalKernel(), AuxiliarySystem::addScalarKernel(), NonlinearSystemBase::addScalarKernel(), NonlinearSystemBase::addSplit(), AuxiliarySystem::addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), AuxiliarySystem::addVariable(), addVariable(), addVector(), NonlinearSystemBase::checkKernelCoverage(), closeTaggedVector(), DisplacedProblem::DisplacedProblem(), getMatrix(), NonlinearSystemBase::getSplit(), getVector(), DisplacedSystem::getVector(), hasVector(), NonlinearEigenSystem::postAddResidualObject(), removeMatrix(), removeVector(), NonlinearSystemBase::setupScalingData(), solutionState(), and zeroTaggedVector().
needSolutionState()
void SystemBase::needSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) virtual
Registers that the solution state state is needed.
Reimplemented in DisplacedSystem.
Definition at line 1393 of file SystemBase.C.
{
  libmesh_parallel_only(this->comm());
  if (hasSolutionState(state, iteration_type))
    return;
  auto & solution_states = _solution_states[static_cast<unsigned short>(iteration_type)];
  solution_states.resize(state + 1);
  // The 0-th (current) solution state is owned by libMesh
  if (!solution_states[0])
    solution_states[0] = &solutionInternal();
  else
    mooseAssert(solution_states[0] == &solutionInternal(), "Inconsistent current solution");
  // We will manually add all states past current
  for (unsigned int i = 1; i <= state; ++i)
    if (!solution_states[i])
    {
      auto tag = _subproblem.addVectorTag(oldSolutionStateVectorName(i, iteration_type),
                                          Moose::VECTOR_TAG_SOLUTION);
      solution_states[i] = &addVector(tag, true, GHOSTED);
    }
    else
      mooseAssert(solution_states[i] == &getVector(oldSolutionStateVectorName(i, iteration_type)),
                  "Inconsistent solution state");
}
Referenced by EigenExecutionerBase::EigenExecutionerBase(), initSolutionState(), DisplacedSystem::needSolutionState(), and solutionState().
nFieldVariables()
unsigned int SystemBase::nFieldVariables () const
Get the number of field variables in this system.
Returns
the number of field variables
Definition at line 849 of file SystemBase.C.
{
  unsigned int n = 0;
  for (auto & var : _vars[0].fieldVariables())
    n += var->count();
  return n;
}
Referenced by nVariables().
nFVVariables()
unsigned int SystemBase::nFVVariables () const
Get the number of finite volume variables in this system.
Returns
the number of finite volume variables
Definition at line 859 of file SystemBase.C.
{
  unsigned int n = 0;
  for (auto & var : _vars[0].fieldVariables())
    if (var->isFV())
      n += var->count();
  return n;
}
Referenced by MooseMesh::cacheFVElementalDoFs().
nonTimeVectorTag()
virtual TagID SystemBase::nonTimeVectorTag () const inline virtual
Reimplemented in DisplacedSystem, and NonlinearSystemBase.
Definition at line 270 of file SystemBase.h.
{ mooseError("Not implemented yet"); }
Referenced by defaultVectorTags(), and DisplacedSystem::nonTimeVectorTag().
number()
unsigned int SystemBase::number () const
Gets the number of this system.
Returns
The number of this system
Definition at line 1125 of file SystemBase.C.
{
  return system().number();
}
Referenced by FEProblemBase::addCachedResidualDirectly(), FEProblemBase::addJacobian(), FEProblemBase::addJacobianBlockTags(), FEProblemBase::addJacobianLowerD(), FEProblemBase::addJacobianNeighbor(), FEProblemBase::addJacobianNeighborLowerD(), FEProblemBase::addJacobianOffDiagScalar(), FEProblemBase::addJacobianScalar(), FEProblemBase::addResidual(), FEProblemBase::addResidualLower(), FEProblemBase::addResidualNeighbor(), FEProblemBase::addResidualScalar(), ADKernelTempl< T >::ADKernelTempl(), ArrayKernel::ArrayKernel(), NonlinearSystemBase::assembleScalingVector(), MooseMesh::cacheFaceInfoVariableOwnership(), ComputeResidualAndJacobianThread::compute(), MooseVariableScalar::computeAD(), FEProblemBase::computeBounds(), Assembly::computeFaceMap(), ArrayNodalBC::computeJacobian(), NodalBC::computeJacobian(), VectorNodalBC::computeJacobian(), FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FEProblemBase::computeJacobianBlock(), NonlinearSystemBase::computeJacobianInternal(), FEProblemBase::computeNearNullSpace(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), FEProblemBase::computeNullSpace(), ArrayNodalBC::computeOffDiagJacobian(), NodalBC::computeOffDiagJacobian(), VectorNodalBC::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), ComputeFullJacobianThread::computeOnInterface(), ComputeFullJacobianThread::computeOnInternalFace(), FEProblemBase::computePostCheck(), EqualValueEmbeddedConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), FVFluxBC::computeResidual(), FVInterfaceKernel::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), IntegratedBC::computeResidualAndJacobian(), NodalBC::computeResidualAndJacobian(), Kernel::computeResidualAndJacobian(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Assembly::computeSinglePointMapAD(), FEProblemBase::computeTransposeNullSpace(), DebugResidualAux::computeValue(), NearestNodeValueAux::computeValue(), NonlinearSystemBase::constraintJacobians(), Coupleable::coupled(), FEProblemBase::currentNlSysNum(), PseudoTimestep::currentResidualNorm(), Moose::FV::determineElemOneAndTwo(), ComputeResidualAndJacobianThread::determineObjectWarehouses(), ComputeResidualThread::determineObjectWarehouses(), Moose::doDerivatives(), GreaterThanLessThanPostprocessor::execute(), VariableResidual::execute(), NodalNormalsCorner::execute(), NodalNormalsEvaluator::execute(), NodalNormalsPreprocessor::execute(), NumNonlinearIterations::finalize(), ElementSubdomainModifier::finalize(), BoundsAuxBase::getDoFIndex(), NonlinearSystemBase::getNodeDofs(), getSubdomainsForVar(), NumLinearIterations::getValue(), NumResidualEvaluations::getValue(), Residual::getValue(), Moose::globalDofIndexToDerivative(), FVBoundaryCondition::hasFaceSide(), NonlinearSystemBase::initialSetup(), ActivateElementsUserObjectBase::initSolutions(), EigenExecutionerBase::inversePowerIteration(), Kernel::Kernel(), EigenExecutionerBase::nonlinearSolve(), ComputeDiracThread::onElement(), ComputeNodalKernelBCJacobiansThread::onNode(), ComputeNodalKernelJacobiansThread::onNode(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), FEProblemBase::prepare(), FEProblemBase::prepareAssembly(), prepareFace(), FEProblemBase::prepareFaceShapes(), FEProblemBase::prepareNeighborShapes(), FEProblemBase::prepareShapes(), EqualValueEmbeddedConstraint::reinitConstraint(), FEProblemBase::reinitDirac(), FEProblemBase::reinitNeighborPhys(), FEProblemBase::reinitOffDiagScalars(), FEProblemBase::setResidual(), FEProblemBase::setResidualNeighbor(), PhysicsBasedPreconditioner::setup(), FVInterfaceKernel::setupData(), FEProblemSolve::solve(), ActuallyExplicitEuler::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), ExplicitSSPRungeKutta::solveStage(), UserObject::systemNumber(), MultiAppDofCopyTransfer::transferDofObject(), FVFluxBC::uOnGhost(), FVFluxBC::uOnUSub(), and MortarConstraintBase::zeroInactiveLMDofs().
nVariables()
unsigned int SystemBase::nVariables () const virtual
Get the number of variables in this system.
Returns
the number of variables
Definition at line 840 of file SystemBase.C.
{
  unsigned int n = nFieldVariables();
  n += _vars[0].scalars().size();
  return n;
}
Referenced by AdaptivityAction::act(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), NonlinearSystemBase::getNodeDofs(), Assembly::init(), MaxVarNDofsPerElem::onElement(), MaxVarNDofsPerNode::onNode(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), and SingleMatrixPreconditioner::SingleMatrixPreconditioner().
oldSolutionStateVectorName()
TagName SystemBase::oldSolutionStateVectorName (const unsigned int state, Moose::SolutionIterationType iteration_type) const private
Gets the vector name used for an old (not current) solution state.
Definition at line 1338 of file SystemBase.C.
{
  mooseAssert(state != 0, "Not an old state");
  if (iteration_type == Moose::SolutionIterationType::Time)
  {
    if (state == 1)
      return Moose::OLD_SOLUTION_TAG;
    else if (state == 2)
      return Moose::OLDER_SOLUTION_TAG;
  }
  else if (iteration_type == Moose::SolutionIterationType::Nonlinear && state == 1)
    return Moose::PREVIOUS_NL_SOLUTION_TAG;
  return "solution_state_" + std::to_string(state) + "_" + Moose::stringify(iteration_type);
}
Referenced by needSolutionState(), and solutionState().
prepare()
void SystemBase::prepare (THREAD_ID tid) virtual
Prepare the system for use.
Parameters
tid ID of the thread
Definition at line 245 of file SystemBase.C.
{
  if (_subproblem.hasActiveElementalMooseVariables(tid))
  {
    const std::set<MooseVariableFieldBase *> & active_elemental_moose_variables =
        _subproblem.getActiveElementalMooseVariables(tid);
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
      var->clearDofIndices();
    for (const auto & var : active_elemental_moose_variables)
      if (&(var->sys()) == this)
        var->prepare();
  }
  else
  {
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
      var->prepare();
  }
}
Referenced by SubProblem::reinitElemFaceRef().
prepareFace()
void SystemBase::prepareFace (THREAD_ID tid, bool resize_data) virtual
Prepare the system for use on sides.
This will try to reuse the preparation done on the element.
Parameters
tid ID of the thread
resize_data Pass True if this system needs to resize residual and jacobian datastructures based on preparing this face
Definition at line 268 of file SystemBase.C.
{
  // We only need to do something if the element prepare was restricted
  if (_subproblem.hasActiveElementalMooseVariables(tid))
  {
    const std::set<MooseVariableFieldBase *> & active_elemental_moose_variables =
        _subproblem.getActiveElementalMooseVariables(tid);
    std::vector<MooseVariableFieldBase *> newly_prepared_vars;
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
    {
      mooseAssert(&var->sys() == this,
                  "I will cry if we store variables in our warehouse that don't belong to us");
      // If it wasn't in the active list, we need to prepare it. This has the potential to duplicate
      // prepare if we have these conditions:
      //
      // 1. We have a displaced problem
      // 2. We are using AD
      // 3. We are not using global AD indexing
      //
      // But I think I would rather risk duplicate prepare than introduce an additional member set
      // variable for tracking prepared variables. Set insertion is slow and some simulations have a
      // ton of variables
      if (!active_elemental_moose_variables.count(var))
      {
        var->prepare();
        newly_prepared_vars.push_back(var);
      }
    }
    // Make sure to resize the residual and jacobian datastructures for all the new variables
    if (resize_data)
      for (const auto var_ptr : newly_prepared_vars)
      {
        _subproblem.assembly(tid, number()).prepareVariable(var_ptr);
        if (_subproblem.checkNonlocalCouplingRequirement())
          _subproblem.assembly(tid, number()).prepareVariableNonlocal(var_ptr);
      }
  }
}
prepareLowerD()
void SystemBase::prepareLowerD (THREAD_ID tid) virtual
Prepare the system for use for lower dimensional elements.
Parameters
tid ID of the thread
Definition at line 321 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->prepareLowerD();
}
prepareNeighbor()
void SystemBase::prepareNeighbor (THREAD_ID tid) virtual
Prepare the system for use.
Parameters
tid ID of the thread
Definition at line 313 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->prepareNeighbor();
}
Referenced by SubProblem::reinitNeighborFaceRef().
reinitElem()
void SystemBase::reinitElem (const Elem * elem, THREAD_ID tid) virtual
Reinit an element assembly info.
Parameters
elem Which element we are reinitializing for
tid ID of the thread
Reimplemented in AuxiliarySystem.
Definition at line 329 of file SystemBase.C.
{
  if (_subproblem.hasActiveElementalMooseVariables(tid))
  {
    const std::set<MooseVariableFieldBase *> & active_elemental_moose_variables =
        _subproblem.getActiveElementalMooseVariables(tid);
    for (const auto & var : active_elemental_moose_variables)
      if (&(var->sys()) == this)
        var->computeElemValues();
  }
  else
  {
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
      var->computeElemValues();
  }
}
reinitElemFace()
void SystemBase::reinitElemFace (const Elem * elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid) virtual
Reinit assembly info for a side of an element.
Parameters
elem The element
side Side of of the element
bnd_id Boundary id on that side
tid Thread ID
Reimplemented in AuxiliarySystem.
Definition at line 349 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeElemValuesFace();
}
Referenced by SubProblem::reinitElemFaceRef().
reinitLowerD()
void SystemBase::reinitLowerD (THREAD_ID tid) virtual
Compute the values of the variables on the lower dimensional element.
Definition at line 379 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeLowerDValues();
}
reinitNeighbor()
void SystemBase::reinitNeighbor (const Elem * elem, THREAD_ID tid) virtual
Compute the values of the variables at all the current points.
Definition at line 371 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeNeighborValues();
}
reinitNeighborFace()
void SystemBase::reinitNeighborFace (const Elem * elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid) virtual
Compute the values of the variables at all the current points.
Definition at line 360 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeNeighborValuesFace();
}
Referenced by SubProblem::reinitNeighborFaceRef().
reinitNode()
void SystemBase::reinitNode (const Node * node, THREAD_ID tid) virtual
Reinit nodal assembly info.
Parameters
node Node to reinit for
tid Thread ID
Definition at line 387 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNode();
    if (var->isNodalDefined())
      var->computeNodalValues();
  }
}
reinitNodeFace()
void SystemBase::reinitNodeFace (const Node * node, BoundaryID bnd_id, THREAD_ID tid) virtual
Reinit nodal assembly info on a face.
Parameters
node Node to reinit
bnd_id Boundary ID
tid Thread ID
Definition at line 399 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNode();
    if (var->isNodalDefined())
      var->computeNodalValues();
  }
}
reinitNodes()
void SystemBase::reinitNodes (const std::vector< dof_id_type > & nodes, THREAD_ID tid) virtual
Reinit variables at a set of nodes.
Parameters
nodes List of node ids to reinit
tid Thread ID
Definition at line 411 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNodes(nodes);
    var->computeNodalValues();
  }
}
reinitNodesNeighbor()
void SystemBase::reinitNodesNeighbor (const std::vector< dof_id_type > & nodes, THREAD_ID tid) virtual
Reinit variables at a set of neighbor nodes.
Parameters
nodes List of node ids to reinit
tid Thread ID
Definition at line 422 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNodesNeighbor(nodes);
    var->computeNodalNeighborValues();
  }
}
reinitScalars()
void SystemBase::reinitScalars (THREAD_ID tid, bool reinit_for_derivative_reordering = false) virtual
Reinit scalar varaibles.
Parameters
tid Thread ID
reinit_for_derivative_reordering A flag indicating whether we are reinitializing for the purpose of re-ordering derivative information for ADNodalBCs
Definition at line 433 of file SystemBase.C.
{
  const std::vector<MooseVariableScalar *> & vars = _vars[tid].scalars();
  for (const auto & var : vars)
    var->reinit(reinit_for_derivative_reordering);
}
removeMatrix()
void SystemBase::removeMatrix (TagID tag)
Removes a matrix with a given tag.
Parameters
tag_name The name of the tag
Definition at line 579 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag_id))
    mooseError("Cannot remove the matrix with TagID ",
               tag_id,
               "\nin system '",
               name(),
               "', because that tag does not exist in the problem");
  if (hasMatrix(tag_id))
  {
    const auto matrix_name = _subproblem.matrixTagName(tag_id);
    system().remove_matrix(matrix_name);
    _tagged_matrices[tag_id] = nullptr;
  }
}
removeVector() [1/2]
void SystemBase::removeVector (const std::string & name)
Remove a vector from the system with the given name.
Definition at line 1291 of file SystemBase.C.
{
  system().remove_vector(name);
}
Referenced by restoreOldSolutions().
removeVector() [2/2]
void SystemBase::removeVector (TagID tag_id)
Remove a solution length vector from the system with the specified TagID.
Parameters
tag_id Tag ID
Definition at line 690 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag_id))
    mooseError("Cannot remove the vector with TagID ",
               tag_id,
               "\nin system '",
               name(),
               "', because that tag does not exist in the problem");
  if (hasVector(tag_id))
  {
    auto vector_name = _subproblem.vectorTagName(tag_id);
    system().remove_vector(vector_name);
    _tagged_vectors[tag_id] = nullptr;
  }
}
residualCopy()
virtual NumericVector< Number > & SystemBase::residualCopy () inline virtual
Reimplemented in DisplacedSystem, and NonlinearSystemBase.
Definition at line 404 of file SystemBase.h.
  {
    mooseError("This system does not support getting a copy of the residual");
  }
Referenced by DisplacedSystem::residualCopy().
residualGhosted()
virtual NumericVector< Number > & SystemBase::residualGhosted () inline virtual
Reimplemented in DisplacedSystem, and NonlinearSystemBase.
Definition at line 408 of file SystemBase.h.
  {
    mooseError("This system does not support getting a ghosted copy of the residual");
  }
Referenced by DisplacedSystem::residualGhosted().
residualSetup()
void SystemBase::residualSetup () virtual
Reimplemented in AuxiliarySystem, and NonlinearSystemBase.
Definition at line 1505 of file SystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _vars[tid].residualSetup();
}
Referenced by residualSetup(), AuxiliarySystem::residualSetup(), and NonlinearSystemBase::residualSetup().
residualVectorTag()
virtual TagID SystemBase::residualVectorTag () const inline virtual
Reimplemented in DisplacedSystem, and NonlinearSystemBase.
Definition at line 275 of file SystemBase.h.
{ mooseError("Not implemented yet"); }
Referenced by defaultVectorTags(), and DisplacedSystem::residualVectorTag().
restoreOldSolutions()
void SystemBase::restoreOldSolutions () virtual
Restore the old and older solutions when the saved solutions present.
Definition at line 531 of file SystemBase.C.
{
  const auto states =
      _solution_states[static_cast<unsigned short>(Moose::SolutionIterationType::Time)].size();
  if (states > 1)
    for (unsigned int i = 1; i <= states - 1; ++i)
      if (_saved_solution_states[i])
      {
        solutionState(i) = *(_saved_solution_states[i]);
        removeVector("save_solution_state_" + std::to_string(i));
        _saved_solution_states[i] = nullptr;
      }
  if (_saved_dot_old && solutionUDotOld())
  {
    *solutionUDotOld() = *_saved_dot_old;
    removeVector("save_solution_dot_old");
    _saved_dot_old = nullptr;
  }
  if (_saved_dotdot_old && solutionUDotDotOld())
  {
    *solutionUDotDotOld() = *_saved_dotdot_old;
    removeVector("save_solution_dotdot_old");
    _saved_dotdot_old = nullptr;
  }
}
restoreSolutions()
void SystemBase::restoreSolutions () virtual
Restore current solutions (call after your solve failed)
Reimplemented in NonlinearSystemBase.
Definition at line 1274 of file SystemBase.C.
{
  if (!hasSolutionState(1))
    mooseError("Cannot restore solutions without old solution");
  *(const_cast<NumericVector<Number> *&>(currentSolution())) = solutionOld();
  solution() = solutionOld();
  if (solutionUDotOld())
    *solutionUDot() = *solutionUDotOld();
  if (solutionUDotDotOld())
    *solutionUDotDot() = *solutionUDotDotOld();
  if (solutionPreviousNewton())
    *solutionPreviousNewton() = solutionOld();
  system().update();
}
Referenced by NonlinearSystemBase::restoreSolutions().
saveOldSolutions()
void SystemBase::saveOldSolutions () virtual
Save the old and older solutions.
Definition at line 499 of file SystemBase.C.
{
  const auto states =
      _solution_states[static_cast<unsigned short>(Moose::SolutionIterationType::Time)].size();
  if (states > 1)
  {
    _saved_solution_states.resize(states);
    for (unsigned int i = 1; i <= states - 1; ++i)
      if (!_saved_solution_states[i])
        _saved_solution_states[i] =
            &addVector("save_solution_state_" + std::to_string(i), false, PARALLEL);
    for (unsigned int i = 1; i <= states - 1; ++i)
      *(_saved_solution_states[i]) = solutionState(i);
  }
  if (!_saved_dot_old && solutionUDotOld())
    _saved_dot_old = &addVector("save_solution_dot_old", false, PARALLEL);
  if (!_saved_dotdot_old && solutionUDotDotOld())
    _saved_dotdot_old = &addVector("save_solution_dotdot_old", false, PARALLEL);
  if (solutionUDotOld())
    *_saved_dot_old = *solutionUDotOld();
  if (solutionUDotDotOld())
    *_saved_dotdot_old = *solutionUDotDotOld();
}
serializedSolution()
virtual NumericVector< Number > & SystemBase::serializedSolution () pure virtual
Returns a reference to a serialized version of the solution vector for this subproblem.
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
Referenced by DisplacedSystem::serializedSolution().
setActiveScalarVariableCoupleableVectorTags()
void SystemBase::setActiveScalarVariableCoupleableVectorTags (const std::set< TagID > & vtags, THREAD_ID tid)
Set the active vector tags for the scalar variables.
Definition at line 1532 of file SystemBase.C.
{
  _vars[tid].setActiveScalarVariableCoupleableVectorTags(vtags);
}
Referenced by SubProblem::setActiveScalarVariableCoupleableVectorTags().
setActiveVariableCoupleableVectorTags()
void SystemBase::setActiveVariableCoupleableVectorTags (const std::set< TagID > & vtags, THREAD_ID tid)
Set the active vector tags for the variables.
Definition at line 1526 of file SystemBase.C.
{
  _vars[tid].setActiveVariableCoupleableVectorTags(vtags);
}
Referenced by SubProblem::setActiveFEVariableCoupleableVectorTags().
setVariableGlobalDoFs()
void SystemBase::setVariableGlobalDoFs (const std::string & var_name)
set all the global dof indices for a variable
Parameters
var_name The name of the variable
Definition at line 175 of file SystemBase.C.
{
  AllLocalDofIndicesThread aldit(_subproblem, {var_name});
  ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();
  Threads::parallel_reduce(elem_range, aldit);
  // Gather the dof indices across procs to get all the dof indices for var_name
  aldit.dofIndicesSetUnion();
  const auto & all_dof_indices = aldit.getDofIndices();
  _var_all_dof_indices.assign(all_dof_indices.begin(), all_dof_indices.end());
}
setVerboseFlag()
void SystemBase::setVerboseFlag (const bool & verbose) inline
Sets the verbose flag.
Parameters
[in] verbose Verbose flag
Definition at line 129 of file SystemBase.h.
{ _verbose = verbose; }
Referenced by Executioner::Executioner().
solution() [1/2]
NumericVector< Number > & SystemBase::solution () inline
Definition at line 176 of file SystemBase.h.
{ return solutionState(0); }
Referenced by Adaptivity::adaptMesh(), TransientMultiApp::appTransferVector(), MooseEigenSystem::combineSystemSolution(), NonlinearSystemBase::computeDamping(), AuxiliarySystem::computeElementalVarsHelper(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeMortarNodalVars(), NonlinearSystemBase::computeNodalBCs(), AuxiliarySystem::computeNodalVarsHelper(), NonlinearSystemBase::computeResidualTags(), AuxiliarySystem::computeScalarVars(), copyVars(), GreaterThanLessThanPostprocessor::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), NodalNormalsCorner::execute(), NodalNormalsEvaluator::execute(), NodalNormalsPreprocessor::execute(), NodalNormalsCorner::finalize(), NodalNormalsEvaluator::finalize(), NodalNormalsPreprocessor::finalize(), NodalNormalsCorner::initialize(), NodalNormalsEvaluator::initialize(), NodalNormalsPreprocessor::initialize(), MooseEigenSystem::initSystemSolution(), ComputeIndicatorThread::onElement(), ComputeMarkerThread::onElement(), ComputeUserObjectsThread::onElement(), ComputeNodalUserObjectsThread::onNode(), FEProblemBase::projectInitialConditionOnCustomRange(), FEProblemBase::projectSolution(), Transient::relativeSolutionDifferenceNorm(), restoreSolutions(), PicardSolve::saveVariableValues(), SecantSolve::saveVariableValues(), SteffensenSolve::saveVariableValues(), MooseEigenSystem::scaleSystemSolution(), AuxiliarySystem::serializeSolution(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::setInitialSolution(), DisplacedSystem::solutionInternal(), NonlinearEigenSystem::solve(), MultiAppDofCopyTransfer::transfer(), PicardSolve::transformVariables(), SecantSolve::transformVariables(), SteffensenSolve::transformVariables(), and zeroVariables().
solution() [2/2]
const NumericVector< Number > & SystemBase::solution () const inline
Definition at line 179 of file SystemBase.h.
{ return solutionState(0); }
solutionInternal()
virtual NumericVector< Number > & SystemBase::solutionInternal () const protected pure virtual
Internal getter for solution owned by libMesh.
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
Referenced by needSolutionState(), and solutionState().
solutionOld() [1/2]
NumericVector< Number > & SystemBase::solutionOld () inline
Definition at line 177 of file SystemBase.h.
{ return solutionState(1); }
Referenced by MooseEigenSystem::combineSystemSolution(), CentralDifference::computeTimeDerivatives(), ActivateElementsUserObjectBase::initSolutions(), MooseEigenSystem::initSystemSolutionOld(), MooseVariableScalar::reinit(), Transient::relativeSolutionDifferenceNorm(), restoreSolutions(), ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes(), ActuallyExplicitEuler::solve(), and AdamsPredictor::timestepSetup().
solutionOld() [2/2]
const NumericVector< Number > & SystemBase::solutionOld () const inline
Definition at line 180 of file SystemBase.h.
{ return solutionState(1); }
solutionOlder() [1/2]
NumericVector< Number > & SystemBase::solutionOlder () inline
Definition at line 178 of file SystemBase.h.
{ return solutionState(2); }
Referenced by MooseEigenSystem::combineSystemSolution(), CentralDifference::computeTimeDerivatives(), ActivateElementsUserObjectBase::initSolutions(), MooseVariableScalar::reinit(), and ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes().
solutionOlder() [2/2]
const NumericVector< Number > & SystemBase::solutionOlder () const inline
Definition at line 181 of file SystemBase.h.
{ return solutionState(2); }
solutionPreviousNewton() [1/2]
NumericVector< Number > * SystemBase::solutionPreviousNewton () virtual
Reimplemented in DisplacedSystem.
Definition at line 1303 of file SystemBase.C.
{
  if (hasVector(Moose::PREVIOUS_NL_SOLUTION_TAG))
    return &getVector(Moose::PREVIOUS_NL_SOLUTION_TAG);
  else
    return nullptr;
}
solutionPreviousNewton() [2/2]
const NumericVector< Number > * SystemBase::solutionPreviousNewton () const virtual
Reimplemented in DisplacedSystem.
Definition at line 1312 of file SystemBase.C.
{
  if (hasVector(Moose::PREVIOUS_NL_SOLUTION_TAG))
    return &getVector(Moose::PREVIOUS_NL_SOLUTION_TAG);
  else
    return nullptr;
}
Referenced by copyOldSolutions(), copySolutionsBackwards(), and restoreSolutions().
solutionState() [1/2]
NumericVector< Number > & SystemBase::solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) virtual
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
If the state does not exist, it will be initialized in addition to any newer states before it that have not been initialized.
Reimplemented in DisplacedSystem.
Definition at line 1384 of file SystemBase.C.
{
  if (!hasSolutionState(state, iteration_type))
    needSolutionState(state, iteration_type);
  return *_solution_states[static_cast<unsigned short>(iteration_type)][state];
}
Referenced by copyOldSolutions(), copySolutionsBackwards(), PointwiseRenormalizeVector::execute(), PointwiseRenormalizeVector::finalize(), restoreOldSolutions(), saveOldSolutions(), solution(), solutionOld(), solutionOlder(), and DisplacedSystem::solutionState().
solutionState() [2/2]
const NumericVector< Number > & SystemBase::solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) const virtual
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
Reimplemented in DisplacedSystem.
Definition at line 1357 of file SystemBase.C.
{
  if (!hasSolutionState(state, iteration_type))
    mooseError("For iteration type '",
               Moose::stringify(iteration_type),
               "': solution state ",
               state,
               " was requested in ",
               name(),
               " but only up to state ",
               _solution_states[static_cast<unsigned short>(iteration_type)].size() - 1,
               " is available.");
  const auto & solution_states = _solution_states[static_cast<unsigned short>(iteration_type)];
  if (state == 0)
    mooseAssert(solution_states[0] == &solutionInternal(), "Inconsistent current solution");
  else
    mooseAssert(solution_states[state] ==
                    &getVector(oldSolutionStateVectorName(state, iteration_type)),
                "Inconsistent solution state");
  return *solution_states[state];
}
solutionStatesInitialized()
bool SystemBase::solutionStatesInitialized () const inline
Whether or not the solution states have been initialized via initSolutionState()
After the solution states have been initialized, additional solution states cannot be added.
Definition at line 888 of file SystemBase.h.
{ return _solution_states_initialized; }
Referenced by AuxScalarKernel::uOld(), and ScalarKernelBase::uOld().
solutionUDot() [1/2]
virtual const NumericVector< Number > * SystemBase::solutionUDot () const pure virtual
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
solutionUDot() [2/2]
virtual NumericVector< Number > * SystemBase::solutionUDot () pure virtual
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
Referenced by MooseVariableScalar::adUDot(), ActuallyExplicitEuler::computeTimeDerivatives(), AStableDirk4::computeTimeDerivatives(), BDF2::computeTimeDerivatives(), CentralDifference::computeTimeDerivatives(), CrankNicolson::computeTimeDerivatives(), ExplicitEuler::computeTimeDerivatives(), ExplicitRK2::computeTimeDerivatives(), ExplicitTVDRK2::computeTimeDerivatives(), ImplicitEuler::computeTimeDerivatives(), ImplicitMidpoint::computeTimeDerivatives(), LStableDirk2::computeTimeDerivatives(), LStableDirk3::computeTimeDerivatives(), LStableDirk4::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), copyOldSolutions(), copySolutionsBackwards(), CrankNicolson::init(), MooseVariableScalar::reinit(), restoreSolutions(), DisplacedSystem::solutionUDot(), and MooseVariableScalar::uDot().
solutionUDotDot() [1/2]
virtual const NumericVector< Number > * SystemBase::solutionUDotDot () const pure virtual
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
solutionUDotDot() [2/2]
virtual NumericVector< Number > * SystemBase::solutionUDotDot () pure virtual
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
Referenced by CentralDifference::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), copyOldSolutions(), copySolutionsBackwards(), MooseVariableScalar::reinit(), restoreSolutions(), DisplacedSystem::solutionUDotDot(), and MooseVariableScalar::uDotDot().
solutionUDotDotOld() [1/2]
virtual const NumericVector< Number > * SystemBase::solutionUDotDotOld () const pure virtual
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
solutionUDotDotOld() [2/2]
virtual NumericVector< Number > * SystemBase::solutionUDotDotOld () pure virtual
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
Referenced by NewmarkBeta::computeADTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), copyOldSolutions(), copySolutionsBackwards(), MooseVariableScalar::reinit(), restoreOldSolutions(), restoreSolutions(), saveOldSolutions(), DisplacedSystem::solutionUDotDotOld(), and MooseVariableScalar::uDotDotOld().
solutionUDotOld() [1/2]
virtual const NumericVector< Number > * SystemBase::solutionUDotOld () const pure virtual
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
solutionUDotOld() [2/2]
virtual NumericVector< Number > * SystemBase::solutionUDotOld () pure virtual
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
Referenced by NewmarkBeta::computeADTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), copyOldSolutions(), copySolutionsBackwards(), MooseVariableScalar::reinit(), restoreOldSolutions(), restoreSolutions(), saveOldSolutions(), DisplacedSystem::solutionUDotOld(), and MooseVariableScalar::uDotOld().
solve()
void SystemBase::solve () virtual
Solve the system (using libMesh magic)
Reimplemented in DumpObjectsNonlinearSystem, NonlinearEigenSystem, NonlinearSystem, and NonlinearSystemBase.
Definition at line 1218 of file SystemBase.C.
{
  system().solve();
}
subdomainSetup()
void SystemBase::subdomainSetup () virtual
Reimplemented in NonlinearSystemBase, and AuxiliarySystem.
Definition at line 1498 of file SystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _vars[tid].subdomainSetup();
}
Referenced by subdomainSetup(), AuxiliarySystem::subdomainSetup(), and NonlinearSystemBase::subdomainSetup().
subproblem() [1/2]
virtual SubProblem & SystemBase::subproblem () inline virtual
Definition at line 98 of file SystemBase.h.
{ return _subproblem; }
Referenced by CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseVariableBase::allDofIndices(), NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), Moose::globalDofIndexToDerivative(), NonlinearSystemBase::initialSetup(), MooseVariableScalar::MooseVariableScalar(), MooseVariableScalar::reinit(), and NonlinearSystemBase::setConstraintSecondaryValues().
subproblem() [2/2]
virtual const SubProblem & SystemBase::subproblem () const inline virtual
Definition at line 99 of file SystemBase.h.
{ return _subproblem; }
system() [1/2]
virtual const System & SystemBase::system () const pure virtual
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
system() [2/2]
virtual System & SystemBase::system () pure virtual
Get the reference to the libMesh system.
Implemented in AuxiliarySystem, DisplacedSystem, and NonlinearSystemBase.
Referenced by MooseVariableFieldBase::activeOnSubdomain(), MooseVariableFieldBase::activeSubdomains(), SubProblem::addCouplingGhostingFunctor(), addMatrix(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), addVariable(), addVector(), MultiAppConservativeTransfer::adjustTransferredSolution(), MultiAppConservativeTransfer::adjustTransferredSolutionNearestPoint(), augmentSendList(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldShapeEvaluationTransfer::buildMeshFunctions(), SubProblem::cloneCouplingGhostingFunctor(), ProjectionAux::computeValue(), copySolutionsBackwards(), copyVars(), dofMap(), FEProblemBase::duplicateVariableCheck(), MultiAppGeometricInterpolationTransfer::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppUserObjectTransfer::execute(), PointwiseRenormalizeVector::execute(), MultiAppGeometricInterpolationTransfer::fillSourceInterpolationPoints(), getVector(), Moose::globalDofIndexToDerivative(), hasScalarVariable(), hasVariable(), hasVector(), PointwiseRenormalizeVector::initialize(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeometricInterpolationTransfer::interpolateTargetPoints(), isArrayVariable(), isScalarVariable(), MooseVariableBase::MooseVariableBase(), name(), number(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), MultiAppProjectionTransfer::projectSolution(), removeMatrix(), removeVector(), restoreSolutions(), ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes(), solve(), MultiAppShapeEvaluationTransfer::transferVariable(), update(), and zeroVariables().
systemMatrixTag()
virtual TagID SystemBase::systemMatrixTag () const inline virtual
Return the Matrix Tag ID for System.
Reimplemented in DisplacedSystem, and NonlinearSystemBase.
Definition at line 265 of file SystemBase.h.
{ mooseError("Not implemented yet"); }
Referenced by defaultMatrixTags(), and DisplacedSystem::systemMatrixTag().
timestepSetup()
void SystemBase::timestepSetup () virtual
Reimplemented in AuxiliarySystem, and NonlinearSystemBase.
Definition at line 1484 of file SystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _vars[tid].timestepSetup();
}
Referenced by timestepSetup(), AuxiliarySystem::timestepSetup(), and NonlinearSystemBase::timestepSetup().
timeVectorTag()
virtual TagID SystemBase::timeVectorTag () const inline virtual
Ideally, we should not need this API.
There exists a really bad API "addCachedResidualDirectly " in FEProblem and DisplacedProblem This API should go away once addCachedResidualDirectly is removed in the future Return Tag ID for Time
Reimplemented in DisplacedSystem, and NonlinearSystemBase.
Definition at line 260 of file SystemBase.h.
{ mooseError("Not implemented yet"); }
Referenced by defaultVectorTags(), and DisplacedSystem::timeVectorTag().
update()
void SystemBase::update (bool update_libmesh_system = true) virtual
Update the system (doing libMesh magic)
Definition at line 1211 of file SystemBase.C.
{
  if (update_libmesh_system)
    system().update();
}
Referenced by Adaptivity::adaptMesh(), MooseEigenSystem::combineSystemSolution(), NonlinearSystemBase::computeDamping(), NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualTags(), EigenProblem::doFreeNonlinearPowerIterations(), PointwiseRenormalizeVector::finalize(), MooseEigenSystem::initSystemSolution(), MooseEigenSystem::initSystemSolutionOld(), MooseEigenSystem::scaleSystemSolution(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::setInitialSolution(), FEProblemBase::solve(), EigenProblem::solve(), DisplacedProblem::syncSolutions(), MultiAppDofCopyTransfer::transfer(), PicardSolve::transformVariables(), SecantSolve::transformVariables(), and SteffensenSolve::transformVariables().
varKind()
Moose::VarKindType SystemBase::varKind () const inline
Returns
the type of variables this system holds, e.g. nonlinear or auxiliary
Definition at line 916 of file SystemBase.h.
{ return _var_kind; }
Referenced by Coupleable::coupled(), and UserObject::UserObject().
zeroTaggedVector()
void SystemBase::zeroTaggedVector (const TagID tag)
Zero vector with the given tag.
Definition at line 664 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot zero vector with TagID ",
               tag,
               " in system '",
               name(),
               "' because that tag does not exist in the problem");
  else if (!hasVector(tag))
    mooseError("Cannot zero vector tag with name '",
               _subproblem.vectorTagName(tag),
               "' in system '",
               name(),
               "' because there is no vector associated with that tag");
  getVector(tag).zero();
}
Referenced by zeroTaggedVectors().
zeroTaggedVectors()
void SystemBase::zeroTaggedVectors (const std::set< TagID > & tags)
Zero all vectors for given tags.
Definition at line 683 of file SystemBase.C.
{
  for (const auto tag : tags)
    zeroTaggedVector(tag);
}
Referenced by NonlinearSystemBase::computeResidualAndJacobianTags(), and NonlinearSystemBase::computeResidualTags().
zeroVariables()
void SystemBase::zeroVariables (std::vector< std::string > & vars_to_be_zeroed) virtual
Zero out the solution for the list of variables passed in.
@ param vars_to_be_zeroed The variable names in this vector will have their solutions set to zero after this call
Reimplemented in DisplacedSystem.
Definition at line 189 of file SystemBase.C.
{
  if (vars_to_be_zeroed.size() > 0)
  {
    NumericVector<Number> & solution = this->solution();
    auto problem = dynamic_cast<FEProblemBase *>(&_subproblem);
    if (!problem)
      mooseError("System needs to be registered in FEProblemBase for using zeroVariables.");
    AllLocalDofIndicesThread aldit(*problem, vars_to_be_zeroed, true);
    ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();
    Threads::parallel_reduce(elem_range, aldit);
    const auto & dof_indices_to_zero = aldit.getDofIndices();
    solution.close();
    for (const auto & dof : dof_indices_to_zero)
      solution.set(dof, 0);
    solution.close();
    // Call update to update the current_local_solution for this system
    system().update();
  }
}
Referenced by DisplacedSystem::zeroVariables(), zeroVariablesForJacobian(), and zeroVariablesForResidual().
zeroVariablesForJacobian()
void SystemBase::zeroVariablesForJacobian () virtual
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on Jacobian evaluation by a call to addVariableToZeroOnResidual()
Definition at line 224 of file SystemBase.C.
{
  zeroVariables(_vars_to_be_zeroed_on_jacobian);
}
zeroVariablesForResidual()
void SystemBase::zeroVariablesForResidual () virtual
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on residual evaluation by a call to addVariableToZeroOnResidual()
Definition at line 218 of file SystemBase.C.
{
  zeroVariables(_vars_to_be_zeroed_on_residual);
}
Member Data Documentation
_app
MooseApp& SystemBase::_app protected
Definition at line 926 of file SystemBase.h.
Referenced by NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeJacobianTags(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), and NonlinearSystem::solve().
_automatic_scaling
bool SystemBase::_automatic_scaling protected
Whether to automatically scale the variables.
Definition at line 979 of file SystemBase.h.
Referenced by automaticScaling(), NonlinearSystem::init(), NonlinearSystemBase::initialSetup(), NonlinearEigenSystem::solve(), and NonlinearSystem::solve().
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_du_dot_du
Real SystemBase::_du_dot_du protected
Definition at line 943 of file SystemBase.h.
Referenced by duDotDu().
_du_dotdot_du
Real SystemBase::_du_dotdot_du protected
Definition at line 944 of file SystemBase.h.
Referenced by duDotDotDu().
_factory
Factory& SystemBase::_factory protected
Definition at line 927 of file SystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addConstraint(), NonlinearSystemBase::addDamper(), NonlinearSystemBase::addDGKernel(), NonlinearSystemBase::addDiracKernel(), NonlinearSystemBase::addInterfaceKernel(), AuxiliarySystem::addKernel(), MooseEigenSystem::addKernel(), NonlinearSystemBase::addKernel(), NonlinearSystemBase::addNodalKernel(), AuxiliarySystem::addScalarKernel(), NonlinearSystemBase::addScalarKernel(), NonlinearSystemBase::addSplit(), AuxiliarySystem::addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), and addVariable().
_matrix_tag_active_flags
std::vector<bool> SystemBase::_matrix_tag_active_flags protected
Active flags for tagged matrices.
Definition at line 951 of file SystemBase.h.
Referenced by activeAllMatrixTags(), activeMatrixTag(), deactiveAllMatrixTags(), deactiveMatrixTag(), and matrixTagActive().
_max_var_n_dofs_per_elem
size_t SystemBase::_max_var_n_dofs_per_elem protected
Maximum number of dofs for any one variable on any one element.
Definition at line 967 of file SystemBase.h.
Referenced by assignMaxVarNDofsPerElem(), and getMaxVarNDofsPerElem().
_max_var_n_dofs_per_node
size_t SystemBase::_max_var_n_dofs_per_node protected
Maximum number of dofs for any one variable on any one node.
Definition at line 970 of file SystemBase.h.
Referenced by assignMaxVarNDofsPerNode(), and getMaxVarNDofsPerNode().
_max_var_number
unsigned int SystemBase::_max_var_number protected
Maximum variable number.
Definition at line 938 of file SystemBase.h.
Referenced by addVariable(), and getMaxVariableNumber().
_mesh
MooseMesh& SystemBase::_mesh protected
Definition at line 929 of file SystemBase.h.
Referenced by addVariable(), NonlinearSystemBase::assembleScalingVector(), augmentSendList(), NonlinearSystemBase::checkKernelCoverage(), NonlinearSystemBase::computeDamping(), AuxiliarySystem::computeElementalVarsHelper(), NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeMortarNodalVars(), NonlinearSystemBase::computeNodalBCs(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), AuxiliarySystem::computeNodalVarsHelper(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), NonlinearSystemBase::findImplicitGeometricCouplingEntries(), NonlinearSystemBase::getNodeDofs(), mesh(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::setInitialSolution(), setVariableGlobalDoFs(), and zeroVariables().
_name
std::string SystemBase::_name protected
The name of this system.
Definition at line 931 of file SystemBase.h.
_numbered_vars
std::vector<std::vector<MooseVariableFieldBase *> > SystemBase::_numbered_vars protected
Map variable number to its pointer.
Definition at line 976 of file SystemBase.h.
Referenced by addVariable(), and getVariable().
_saved_dot_old
NumericVector<Real>* SystemBase::_saved_dot_old protected
Definition at line 958 of file SystemBase.h.
Referenced by restoreOldSolutions(), and saveOldSolutions().
_saved_dotdot_old
NumericVector<Real>* SystemBase::_saved_dotdot_old protected
Definition at line 959 of file SystemBase.h.
Referenced by restoreOldSolutions(), and saveOldSolutions().
_saved_old
NumericVector<Real>* SystemBase::_saved_old protected
Definition at line 954 of file SystemBase.h.
_saved_older
NumericVector<Real>* SystemBase::_saved_older protected
Definition at line 955 of file SystemBase.h.
_saved_solution_states
std::vector<NumericVector<Number> *> SystemBase::_saved_solution_states private
The saved solution states (0 = current, 1 = old, 2 = older, etc)
Definition at line 1000 of file SystemBase.h.
Referenced by restoreOldSolutions(), and saveOldSolutions().
_solution_states
std::array<std::vector<NumericVector<Number> *>, 2> SystemBase::_solution_states private
The solution states (0 = current, 1 = old, 2 = older, etc)
Definition at line 998 of file SystemBase.h.
Referenced by copyOldSolutions(), copySolutionsBackwards(), hasSolutionState(), needSolutionState(), restoreOldSolutions(), saveOldSolutions(), and solutionState().
_solution_states_initialized
bool SystemBase::_solution_states_initialized protected
Whether or not the solution states have been initialized.
Definition at line 985 of file SystemBase.h.
Referenced by initSolutionState(), and solutionStatesInitialized().
_subproblem
SubProblem& SystemBase::_subproblem protected
Definition at line 924 of file SystemBase.h.
Referenced by activeAllMatrixTags(), activeMatrixTag(), addMatrix(), addScalingVector(), addVariable(), addVector(), associateMatrixToTag(), associateVectorToTag(), augmentSendList(), closeTaggedVector(), computingScalingJacobian(), copyVars(), deactiveAllMatrixTags(), deactiveMatrixTag(), disassociateDefaultMatrixTags(), disassociateDefaultVectorTags(), disassociateMatrixFromTag(), disassociateVectorFromTag(), getMatrix(), NonlinearSystemBase::getResidualNonTimeVector(), NonlinearSystemBase::getResidualTimeVector(), getVector(), matrixTagActive(), needSolutionState(), prepare(), prepareFace(), reinitElem(), removeMatrix(), removeVector(), NonlinearSystemBase::residualGhosted(), NonlinearSystemBase::setSolution(), setVariableGlobalDoFs(), subproblem(), zeroTaggedVector(), and zeroVariables().
_tagged_matrices
std::vector<SparseMatrix<Number> *> SystemBase::_tagged_matrices protected
Tagged matrices (pointer)
Definition at line 949 of file SystemBase.h.
Referenced by associateMatrixToTag(), disassociateMatrixFromTag(), getMatrix(), hasMatrix(), and removeMatrix().
_tagged_vectors
std::vector<NumericVector<Number> *> SystemBase::_tagged_vectors protected
Tagged vectors (pointer)
Definition at line 947 of file SystemBase.h.
Referenced by associateVectorToTag(), disassociateVectorFromTag(), getVector(), hasVector(), and removeVector().
_time_integrator
std::shared_ptr<TimeIntegrator> SystemBase::_time_integrator protected
Time integrator.
Definition at line 973 of file SystemBase.h.
Referenced by AuxiliarySystem::addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), DisplacedSystem::addTimeIntegrator(), AuxiliarySystem::compute(), NonlinearSystemBase::computeResidualAndJacobianTags(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::computeTimeDerivatives(), getSharedTimeIntegrator(), getTimeIntegrator(), NonlinearSystemBase::onTimestepBegin(), NonlinearEigenSystem::solve(), and NonlinearSystem::solve().
_var_all_dof_indices
std::vector<dof_id_type> SystemBase::_var_all_dof_indices protected
Container for the dof indices of a given variable.
Definition at line 988 of file SystemBase.h.
Referenced by getVariableGlobalDoFs(), and setVariableGlobalDoFs().
_var_kind
Moose::VarKindType SystemBase::_var_kind protected
default kind of variables in this system
Definition at line 962 of file SystemBase.h.
Referenced by varKind().
_var_map
std::map<unsigned int, std::set<SubdomainID> > SystemBase::_var_map protected
Map of variables (variable id -> array of subdomains where it lives)
Definition at line 936 of file SystemBase.h.
Referenced by addVariable(), getSubdomainsForVar(), and getVariableBlocks().
_var_to_copy
std::vector<VarCopyInfo> SystemBase::_var_to_copy protected
Definition at line 964 of file SystemBase.h.
Referenced by addVariableToCopy(), copyVars(), and hasVarCopy().
_vars
std::vector<VariableWarehouse> SystemBase::_vars protected
Variable warehouses (one for each thread)
Definition at line 934 of file SystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addInterfaceKernel(), AuxiliarySystem::addVariable(), addVariable(), applyScalingFactors(), NonlinearSystemBase::assembleScalingVector(), clearAllDofIndices(), AuxiliarySystem::compute(), customSetup(), getActualFieldVariable(), getFieldVariable(), getFVVariable(), getMinQuadratureOrder(), AuxiliarySystem::getMinQuadratureOrder(), getScalarVariable(), getScalarVariables(), getVariable(), getVariableNames(), getVariables(), initialSetup(), jacobianSetup(), nFieldVariables(), nFVVariables(), nVariables(), prepare(), prepareFace(), prepareLowerD(), prepareNeighbor(), reinitElem(), reinitElemFace(), reinitLowerD(), reinitNeighbor(), reinitNeighborFace(), reinitNode(), reinitNodeFace(), reinitNodes(), reinitNodesNeighbor(), reinitScalars(), residualSetup(), setActiveScalarVariableCoupleableVectorTags(), setActiveVariableCoupleableVectorTags(), NonlinearSystemBase::setupScalingData(), subdomainSetup(), and timestepSetup().
_vars_to_be_zeroed_on_jacobian
std::vector<std::string> SystemBase::_vars_to_be_zeroed_on_jacobian protected
Definition at line 941 of file SystemBase.h.
Referenced by addVariableToZeroOnJacobian(), and zeroVariablesForJacobian().
_vars_to_be_zeroed_on_residual
std::vector<std::string> SystemBase::_vars_to_be_zeroed_on_residual protected
Definition at line 940 of file SystemBase.h.
Referenced by addVariableToZeroOnResidual(), and zeroVariablesForResidual().
_verbose
bool SystemBase::_verbose protected
True if printing out additional information.
Definition at line 982 of file SystemBase.h.
Referenced by applyScalingFactors(), and setVerboseFlag().
The documentation for this class was generated from the following files:
moose/framework/include/systems/SystemBase.h
moose/framework/src/systems/SystemBase.C