Zapdos: MooseUtils::DelimitedFileReader Class Reference
MooseUtils::DelimitedFileReader Class Reference
Utility class for reading delimited data (e.g., CSV data).
#include <DelimitedFileReader.h>
Public Types
enum class HeaderFlag { OFF = 0 , ON = 1 , AUTO = 2 }
enum class FormatFlag { COLUMNS = 0 , ROWS = 1 }
Public Member Functions
DelimitedFileReader (const std::string &filename, const libMesh::Parallel::Communicator *comm=nullptr)
void read ()
Perform the actual data reading.
std::size_t numEntries () const
Get the total number of entries in the file.
const std::vector< std::string > & getNames () const
Return the column/row names.
const std::vector< std::vector< double > > & getData () const
Return the rows/columns of data.
const std::vector< Point > getDataAsPoints () const
Get the data in Point format.
void setIgnoreEmptyLines (bool value)
Set/Get methods for file format controls.
bool getIgnoreEmptyLines () const
void setFormatFlag (FormatFlag value)
FormatFlag getFormatFlag () const
void setDelimiter (const std::string &value)
const std::string & setDelimiter () const
void setHeaderFlag (HeaderFlag value)
HeaderFlag getHeaderFlag () const
void setComment (const std::string &value)
const std::string & getComment () const
const std::vector< double > & getData (const std::string &name) const
Return the row/column of data for a specified header entry.
const std::vector< double > & getData (std::size_t index) const
void setHeaderFlag (bool value)
Deprecated.
const std::vector< std::string > & getColumnNames () const
const std::vector< std::vector< double > > & getColumnData () const
const std::vector< double > & getColumnData (const std::string &name) const
DelimitedFileReader (const std::string &filename, const bool header, const std::string delimiter, const libMesh::Parallel::Communicator *comm=nullptr)
Public Attributes
const std::size_t INVALID_SIZE = std::numeric_limits<std::size_t>::max()
Protected Attributes
const std::string _filename
The supplied filename.
HeaderFlag _header_flag
Flag indicating if the file contains a header.
std::string _delimiter
The delimiter separating the supplied data entires.
bool _ignore_empty_lines
Flag for ignoring empty lines.
std::vector< std::string > _names
Storage for the read or generated column names.
std::vector< std::vector< double > > _data
Storage for the read data columns.
const libMesh::Parallel::Communicator *const _communicator
Communicator.
FormatFlag _format_flag
Format "rows" vs "columns".
std::vector< std::size_t > _row_offsets
Row offsets (only used with _format == "rows")
std::string _row_comment
Hide row comments.
Private Member Functions
void processLine (const std::string &line, std::vector< double > &row, const unsigned int &num)
Populate supplied vector with content from line.
bool preprocessLine (std::string &line, const unsigned int &num)
Check the content of the line and if it should be skipped.
const std::string & delimiter (const std::string &line)
Determine the delimiter.
bool header (const std::string &line)
Return the header flag, if it is set to AUTO attempt to determine if a header exists in line.
void readColumnData (std::ifstream &stream_data, std::vector< double > &output)
Read the numeric data as rows or columns into a single vector.
void readRowData (std::ifstream &stream_data, std::vector< double > &output)
Detailed Description
Utility class for reading delimited data (e.g., CSV data).
Parameters
filename A string for the filename to read.
comm A pointer to a Communicator object (see below).
This class assumes that all data is numeric and can be converted to a C++ double. If a Communicator is provide then it will only read on processor 0 and broadcast the data to all processors. If not provided it will read on all processors.
Definition at line 35 of file DelimitedFileReader.h.
Member Enumeration Documentation
FormatFlag
enum class MooseUtils::DelimitedFileReader::FormatFlag strong
Enumerator
COLUMNS
ROWS
Definition at line 45 of file DelimitedFileReader.h.
  {
    COLUMNS = 0,
    ROWS = 1
  };
HeaderFlag
enum class MooseUtils::DelimitedFileReader::HeaderFlag strong
Enumerator
OFF
ON
AUTO
Definition at line 38 of file DelimitedFileReader.h.
  {
    OFF = 0,
    ON = 1,
    AUTO = 2
  };
Constructor & Destructor Documentation
DelimitedFileReader() [1/2]
MooseUtils::DelimitedFileReader::DelimitedFileReader (const std::string & filename, const libMesh::Parallel::Communicator * comm = nullptr)
Definition at line 24 of file DelimitedFileReader.C.
  : _filename(filename),
    _header_flag(HeaderFlag::AUTO),
    _ignore_empty_lines(true),
    _communicator(comm),
    _format_flag(FormatFlag::COLUMNS)
{
}
DelimitedFileReader() [2/2]
MooseUtils::DelimitedFileReader::DelimitedFileReader (const std::string & filename, const bool header, const std::string delimiter, const libMesh::Parallel::Communicator * comm = nullptr)
Definition at line 398 of file DelimitedFileReader.C.
  : _filename(filename),
    _header_flag(header ? HeaderFlag::ON : HeaderFlag::AUTO),
    _delimiter(delimiter),
    _ignore_empty_lines(true),
    _communicator(comm),
    _format_flag(FormatFlag::COLUMNS)
{
  mooseDeprecated("Use setHeader and setDelimiter method rather than specifying in constructor.");
}
Member Function Documentation
delimiter()
const std::string & MooseUtils::DelimitedFileReader::delimiter (const std::string & line) private
Determine the delimiter.
If the setDelimiter method is not called the data is inspected, if a ',' is found it is assumed to be the delimiter as is the case for \t. Otherwise a space is used.
Definition at line 359 of file DelimitedFileReader.C.
{
  if (_delimiter.empty())
  {
    if (line.find(",") != std::string::npos)
      _delimiter = ",";
    else if (line.find("\t") != std::string::npos)
      _delimiter = "\t";
    else
      _delimiter = " ";
  }
  return _delimiter;
}
Referenced by header(), processLine(), readColumnData(), and readRowData().
getColumnData() [1/2]
const std::vector< std::vector< double > > & MooseUtils::DelimitedFileReader::getColumnData () const
Definition at line 420 of file DelimitedFileReader.C.
{
  mooseDeprecated("Use getData instead.");
  return getData();
}
getColumnData() [2/2]
const std::vector< double > & MooseUtils::DelimitedFileReader::getColumnData (const std::string & name) const
Definition at line 427 of file DelimitedFileReader.C.
{
  mooseDeprecated("Use getData instead.");
  return getData(name);
}
getColumnNames()
const std::vector< std::string > & MooseUtils::DelimitedFileReader::getColumnNames () const
Definition at line 413 of file DelimitedFileReader.C.
{
  mooseDeprecated("Use getNames instead.");
  return getNames();
}
getComment()
const std::string & MooseUtils::DelimitedFileReader::getComment () const inline
Definition at line 92 of file DelimitedFileReader.h.
{ return _row_comment; }
getData() [1/3]
const std::vector< std::vector< double > > & MooseUtils::DelimitedFileReader::getData () const
Return the rows/columns of data.
The outer vector is column and the inner the rows.
Definition at line 140 of file DelimitedFileReader.C.
{
  return _data;
}
Referenced by PiecewiseTabularBase::buildFromFile(), CSVFileTimes::CSVFileTimes(), CSVReader::CSVReader(), PropertyReadFile::getBlockData(), getColumnData(), PropertyReadFile::getElementData(), PropertyReadFile::getNodeData(), PropertyReadFile::getVoronoiData(), CSVTimeSequenceStepper::init(), PropertyReadFile::initVoronoiCenterPoints(), and PropertyReadFile::readData().
getData() [2/3]
const std::vector< double > & MooseUtils::DelimitedFileReader::getData (const std::string & name) const
Return the row/column of data for a specified header entry.
Definition at line 177 of file DelimitedFileReader.C.
{
  const auto it = find(_names.begin(), _names.end(), name);
  if (it == _names.end())
    mooseError("Could not find '", name, "' in header of file ", _filename, ".");
  return _data[std::distance(_names.begin(), it)];
}
getData() [3/3]
const std::vector< double > & MooseUtils::DelimitedFileReader::getData (std::size_t index) const
Definition at line 186 of file DelimitedFileReader.C.
{
  if (index >= _data.size())
    mooseError("The supplied index ",
               index,
               " is out-of-range for the available data in file '",
               _filename,
               "' which contains ",
               _data.size(),
               " items.");
  return _data[index];
}
getDataAsPoints()
const std::vector< Point > MooseUtils::DelimitedFileReader::getDataAsPoints () const
Get the data in Point format.
This performs checks that the data is of valid dimensions to do so.
Definition at line 146 of file DelimitedFileReader.C.
{
  std::vector<Point> point_data;
  for (std::size_t i = 0; i < _data.size(); ++i)
  {
    Point point;
    // Other checks in this class ensure that each data entry has the same number of values;
    // here we just need to check that each data set has LIBMESH_DIM entries (which we could do by
    // equivalently checking that the total number of entries is divisibly by LIBMESH_DIM
    // _and_ one of these data sets has LIBMESH_DIM entries (consider the fringe case where
    // LIBMESH_DIM is 3, but you accidentally put a point file like
    //   0 0
    //   1 0
    //   2 0
    // where each point is the same length _and_ the total points is still divisible by 3.
    // This check here is more exact.
    if (_data.at(i).size() != LIBMESH_DIM)
      mooseError("Each point in file ", _filename, " must have ", LIBMESH_DIM, " entries");
    for (std::size_t j = 0; j < LIBMESH_DIM; ++j)
      point(j) = _data.at(i).at(j);
    point_data.push_back(point);
  }
  return point_data;
}
Referenced by FilePositions::FilePositions(), NearestPointBase< UserObjectType, BaseType >::fillPoints(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), and MultiApp::fillPositions().
getFormatFlag()
FormatFlag MooseUtils::DelimitedFileReader::getFormatFlag () const inline
Definition at line 83 of file DelimitedFileReader.h.
{ return _format_flag; }
getHeaderFlag()
HeaderFlag MooseUtils::DelimitedFileReader::getHeaderFlag () const inline
Definition at line 89 of file DelimitedFileReader.h.
{ return _header_flag; }
getIgnoreEmptyLines()
bool MooseUtils::DelimitedFileReader::getIgnoreEmptyLines () const inline
Definition at line 80 of file DelimitedFileReader.h.
{ return _ignore_empty_lines; }
getNames()
const std::vector< std::string > & MooseUtils::DelimitedFileReader::getNames () const
Return the column/row names.
Definition at line 134 of file DelimitedFileReader.C.
{
  return _names;
}
Referenced by PiecewiseTabularBase::buildFromFile(), CSVReader::CSVReader(), and getColumnNames().
header()
bool MooseUtils::DelimitedFileReader::header (const std::string & line) private
Return the header flag, if it is set to AUTO attempt to determine if a header exists in line.
Definition at line 374 of file DelimitedFileReader.C.
{
  switch (_header_flag)
  {
    case HeaderFlag::OFF:
      return false;
    case HeaderFlag::ON:
      return true;
    default:
      // Attempt to convert the line, if it fails assume it is a header
      std::vector<double> row;
      bool contains_alpha = !MooseUtils::tokenizeAndConvert<double>(line, row, delimiter(line));
      // Based on auto detect set the flag to TRUE|FALSE to short-circuit this check for each line
      // in the case of row data.
      _header_flag = contains_alpha ? HeaderFlag::ON : HeaderFlag::OFF;
      return contains_alpha;
  }
}
Referenced by readColumnData(), and readRowData().
numEntries()
std::size_t MooseUtils::DelimitedFileReader::numEntries () const
Get the total number of entries in the file.
Returns
number of entries in file
Definition at line 124 of file DelimitedFileReader.C.
{
  std::size_t n_entries = 0;
  for (std::size_t i = 0; i < _data.size(); ++i)
    n_entries += _data[i].size();
  return n_entries;
}
preprocessLine()
bool MooseUtils::DelimitedFileReader::preprocessLine (std::string & line, const unsigned int & num) private
Check the content of the line and if it should be skipped.
Parameters
line Complete line being read.
num The current line number.
Returns
True if the line should be skipped.
Definition at line 323 of file DelimitedFileReader.C.
{
  // Handle row comments
  std::size_t index = _row_comment.empty() ? line.size() : line.find_first_of(_row_comment);
  line = MooseUtils::trim(line.substr(0, index));
  // Ignore empty lines
  if (line.empty())
  {
    if (_ignore_empty_lines)
      return true;
    else
      mooseError("Failed to read line ", num, " in file ", _filename, ". The line is empty.");
  }
  return false;
}
Referenced by readColumnData(), and readRowData().
processLine()
void MooseUtils::DelimitedFileReader::processLine (const std::string & line, std::vector< double > & row, const unsigned int & num) private
Populate supplied vector with content from line.
Parameters
line The line to extract data from.
row The vector to populate.
num The current line number.
Definition at line 341 of file DelimitedFileReader.C.
{
  // Separate the row and error if it fails
  bool status = MooseUtils::tokenizeAndConvert<double>(line, row, delimiter(line));
  if (!status)
    mooseError("Failed to convert a delimited data into double when reading line ",
               num,
               " in file ",
               _filename,
               ".\n  LINE ",
               num,
               ": ",
               line);
}
Referenced by readColumnData(), and readRowData().
read()
void MooseUtils::DelimitedFileReader::read ()
Perform the actual data reading.
This is a separate method to allow for the filename to be read multiple times.
Definition at line 35 of file DelimitedFileReader.C.
{
  // Number of columns
  std::size_t n_cols;
  // Storage for the raw data
  std::vector<double> raw;
  std::size_t size_raw = 0;
  std::size_t size_offsets = 0;
  // Read data
  if (_communicator == nullptr || _communicator->rank() == 0)
  {
    // Check the file
    MooseUtils::checkFileReadable(_filename);
    // Create the file stream and do nothing if the file is empty
    std::ifstream stream_data(_filename);
    if (stream_data.peek() == std::ifstream::traits_type::eof())
      return;
    // Read/generate the header
    if (_format_flag == FormatFlag::ROWS)
      readRowData(stream_data, raw);
    else
      readColumnData(stream_data, raw);
    // Set the number of columns
    n_cols = _names.size();
    // Close the stream
    stream_data.close();
    // Set raw data vector size
    size_raw = raw.size();
    size_offsets = _row_offsets.size();
  }
  if (_communicator != nullptr)
  {
    // Broadcast column names
    _communicator->broadcast(n_cols);
    _names.resize(n_cols);
    _communicator->broadcast(_names);
    // Broadcast raw data
    _communicator->broadcast(size_raw);
    raw.resize(size_raw);
    _communicator->broadcast(raw);
    // Broadcast row offsets
    if (_format_flag == FormatFlag::ROWS)
    {
      _communicator->broadcast(size_offsets);
      _row_offsets.resize(size_offsets);
      _communicator->broadcast(_row_offsets);
    }
  }
  // Resize the internal storage
  _data.resize(n_cols);
  // Process "row" formatted data
  if (_format_flag == FormatFlag::ROWS)
  {
    std::vector<double>::iterator start = raw.begin();
    for (std::size_t j = 0; j < n_cols; ++j)
    {
      _data[j] = std::vector<double>(start, start + _row_offsets[j]);
      std::advance(start, _row_offsets[j]);
    }
  }
  // Process "column" formatted data
  else
  {
    mooseAssert(raw.size() % n_cols == 0,
                "The raw data is not evenly divisible by the number of columns.");
    const std::size_t n_rows = raw.size() / n_cols;
    for (std::size_t j = 0; j < n_cols; ++j)
    {
      _data[j].resize(n_rows);
      for (std::size_t i = 0; i < n_rows; ++i)
        _data[j][i] = raw[i * n_cols + j];
    }
  }
}
Referenced by PiecewiseTabularBase::buildFromFile(), CSVFileTimes::CSVFileTimes(), CSVReader::CSVReader(), FilePositions::FilePositions(), NearestPointBase< UserObjectType, BaseType >::fillPoints(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), CSVTimeSequenceStepper::init(), and PropertyReadFile::readData().
readColumnData()
void MooseUtils::DelimitedFileReader::readColumnData (std::ifstream & stream_data, std::vector< double > & output) private
Read the numeric data as rows or columns into a single vector.
Definition at line 200 of file DelimitedFileReader.C.
{
  // Local storage for the data being read
  std::string line;
  std::vector<double> row;
  // Keep track of the line number for error reporting
  unsigned int count = 0;
  // Number of columns expected based on the first row of the data
  std::size_t n_cols = INVALID_SIZE;
  // Read the lines
  while (std::getline(stream_data, line))
  {
    // Increment line counter and clear any tokenized data
    count++;
    row.clear();
    // Ignore empty and/or comment lines, if applicable
    if (preprocessLine(line, count))
      continue;
    // Read header, if the header exists and the column names do not exist.
    if (_names.empty() && header(line))
    {
      MooseUtils::tokenize(line, _names, 1, delimiter(line));
      for (std::string & str : _names)
        str = MooseUtils::trim(str);
      continue;
    }
    // Separate the row and error if it fails
    processLine(line, row, count);
    // Set the number of columns
    if (n_cols == INVALID_SIZE)
      n_cols = row.size();
    // Check number of columns
    if (row.size() != n_cols)
      mooseError("The number of columns read (",
                 row.size(),
                 ") does not match the number of columns expected (",
                 n_cols,
                 ") based on the first row of the file when reading row ",
                 count,
                 " in file ",
                 _filename,
                 ".");
    // Append data
    output.insert(output.end(), row.begin(), row.end());
  }
  // If the names have not been assigned, create the default names
  if (_names.empty())
  {
    _names.resize(n_cols);
    int padding = MooseUtils::numDigits(n_cols);
    for (std::size_t i = 0; i < n_cols; ++i)
    {
      std::stringstream ss;
      ss << "column_" << std::setw(padding) << std::setfill('0') << i;
      _names[i] = ss.str();
    }
  }
}
Referenced by read().
readRowData()
void MooseUtils::DelimitedFileReader::readRowData (std::ifstream & stream_data, std::vector< double > & output) private
Definition at line 270 of file DelimitedFileReader.C.
{
  // Local storage for the data being read
  std::string line;
  std::vector<double> row;
  unsigned int linenum = 0; // line number in file
  // Clear existing data
  _names.clear();
  _row_offsets.clear();
  // Read the lines
  while (std::getline(stream_data, line))
  {
    // Increment line counter and clear any tokenized data
    linenum++;
    row.clear();
    // Ignore empty lines
    if (preprocessLine(line, linenum))
      continue;
    if (header(line))
    {
      std::size_t index = line.find_first_of(delimiter(line));
      _names.push_back(line.substr(0, index));
      line = line.substr(index);
    }
    // Separate the row and error if it fails
    processLine(line, row, linenum);
    // Store row offsets to allow for un-even rows
    _row_offsets.push_back(row.size());
    // Append data
    output.insert(output.end(), row.begin(), row.end());
  }
  // Assign row names if not provided via header
  if (_names.empty())
  {
    int padding = MooseUtils::numDigits(_row_offsets.size());
    for (std::size_t i = 0; i < _row_offsets.size(); ++i)
    {
      std::stringstream ss;
      ss << "row_" << std::setw(padding) << std::setfill('0') << i;
      _names.push_back(ss.str());
    }
  }
}
Referenced by read().
setComment()
void MooseUtils::DelimitedFileReader::setComment (const std::string & value) inline
Definition at line 91 of file DelimitedFileReader.h.
{ _row_comment = value; }
Referenced by PiecewiseTabularBase::buildFromFile().
setDelimiter() [1/2]
const std::string & MooseUtils::DelimitedFileReader::setDelimiter () const inline
Definition at line 86 of file DelimitedFileReader.h.
{ return _delimiter; }
setDelimiter() [2/2]
void MooseUtils::DelimitedFileReader::setDelimiter (const std::string & value) inline
Definition at line 85 of file DelimitedFileReader.h.
{ _delimiter = value; }
Referenced by CSVReader::CSVReader(), and CSVTimeSequenceStepper::init().
setFormatFlag()
void MooseUtils::DelimitedFileReader::setFormatFlag (FormatFlag value) inline
Definition at line 82 of file DelimitedFileReader.h.
{ _format_flag = value; }
Referenced by PiecewiseTabularBase::buildFromFile(), CSVFileTimes::CSVFileTimes(), FilePositions::FilePositions(), NearestPointBase< UserObjectType, BaseType >::fillPoints(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), and PropertyReadFile::readData().
setHeaderFlag() [1/2]
void MooseUtils::DelimitedFileReader::setHeaderFlag (bool value)
Deprecated.
Definition at line 434 of file DelimitedFileReader.C.
{
  mooseDeprecated("Use header method with HeaderFlag input.");
  _header_flag = value ? HeaderFlag::ON : HeaderFlag::OFF;
}
setHeaderFlag() [2/2]
void MooseUtils::DelimitedFileReader::setHeaderFlag (HeaderFlag value) inline
Definition at line 88 of file DelimitedFileReader.h.
{ _header_flag = value; }
Referenced by CSVReader::CSVReader(), and CSVTimeSequenceStepper::init().
setIgnoreEmptyLines()
void MooseUtils::DelimitedFileReader::setIgnoreEmptyLines (bool value) inline
Set/Get methods for file format controls.
IgnoreEmptyLines: When true all empty lines are ignored, when false an error is produced. FormatFlag: Set the file format (rows vs. columns). Delimiter: Set the file delimiter (if unset it will be detected). HeaderFlag: Set the header flag (TRUE used the first row has header, FALSE assumes no header, and AUTO will attempt to determine if a header exists). Comment: Set the comment character, by default no comment character is used.
Definition at line 79 of file DelimitedFileReader.h.
{ _ignore_empty_lines = value; }
Referenced by CSVReader::CSVReader().
Member Data Documentation
_communicator
const libMesh::Parallel::Communicator* const MooseUtils::DelimitedFileReader::_communicator protected
Communicator.
Definition at line 155 of file DelimitedFileReader.h.
Referenced by read().
_data
std::vector<std::vector<double> > MooseUtils::DelimitedFileReader::_data protected
Storage for the read data columns.
Definition at line 152 of file DelimitedFileReader.h.
Referenced by getData(), getDataAsPoints(), numEntries(), and read().
_delimiter
std::string MooseUtils::DelimitedFileReader::_delimiter protected
The delimiter separating the supplied data entires.
Definition at line 143 of file DelimitedFileReader.h.
Referenced by delimiter(), and setDelimiter().
_filename
const std::string MooseUtils::DelimitedFileReader::_filename protected
The supplied filename.
Definition at line 137 of file DelimitedFileReader.h.
Referenced by getData(), getDataAsPoints(), preprocessLine(), processLine(), read(), and readColumnData().
_format_flag
FormatFlag MooseUtils::DelimitedFileReader::_format_flag protected
Format "rows" vs "columns".
Definition at line 158 of file DelimitedFileReader.h.
Referenced by getFormatFlag(), read(), and setFormatFlag().
_header_flag
HeaderFlag MooseUtils::DelimitedFileReader::_header_flag protected
Flag indicating if the file contains a header.
Definition at line 140 of file DelimitedFileReader.h.
Referenced by getHeaderFlag(), header(), and setHeaderFlag().
_ignore_empty_lines
bool MooseUtils::DelimitedFileReader::_ignore_empty_lines protected
Flag for ignoring empty lines.
Definition at line 146 of file DelimitedFileReader.h.
Referenced by getIgnoreEmptyLines(), preprocessLine(), and setIgnoreEmptyLines().
_names
std::vector<std::string> MooseUtils::DelimitedFileReader::_names protected
Storage for the read or generated column names.
Definition at line 149 of file DelimitedFileReader.h.
Referenced by getData(), getNames(), read(), readColumnData(), and readRowData().
_row_comment
std::string MooseUtils::DelimitedFileReader::_row_comment protected
Hide row comments.
Definition at line 164 of file DelimitedFileReader.h.
Referenced by getComment(), preprocessLine(), and setComment().
_row_offsets
std::vector<std::size_t> MooseUtils::DelimitedFileReader::_row_offsets protected
Row offsets (only used with _format == "rows")
Definition at line 161 of file DelimitedFileReader.h.
Referenced by read(), and readRowData().
INVALID_SIZE
const std::size_t MooseUtils::DelimitedFileReader::INVALID_SIZE = std::numeric_limits<std::size_t>::max()
Definition at line 51 of file DelimitedFileReader.h.
Referenced by readColumnData().
The documentation for this class was generated from the following files:
moose/framework/include/utils/DelimitedFileReader.h
moose/framework/src/utils/DelimitedFileReader.C