Zapdos: ExodusFormatter Class Reference
ExodusFormatter Class Reference
#include <ExodusFormatter.h>
Public Member Functions
ExodusFormatter ()
void printInputFile (ActionWarehouse &wh)
void format ()
std::vector< std::string > & getInputFileRecord ()
virtual std::string printBlockOpen (const std::string &name, short depth, const std::string &) override
This method is called at the beginning of each Node in the tree.
virtual std::string printBlockClose (const std::string &name, short depth) const override
This method is called at the end of of each Node in the tree.
virtual std::string printParams (const std::string &prefix, const std::string &fully_qualified_name, InputParameters &params, short depth, const std::string &search_string, bool &found) override
This function is called for each InputParameters object stored at a particular node.
void insertNode (std::string syntax, const std::string &action, bool is_action_params=true, InputParameters *params=NULL)
std::string print (const std::string &search_string)
void seenIt (const std::string &prefix, const std::string &item)
bool haveSeenIt (const std::string &prefix, const std::string &item) const
virtual std::string preamble () const
This method is called once at the beginning of the tree traversal and can be used to build up header information.
virtual std::string postscript () const
This method is called once at the end of the tree traversal and can be used to add any necessary trailing information to the final formatted string.
virtual std::string preTraverse (short) const
This method is called once at each node in the syntax tree before traversing child nodes.
Protected Member Functions
bool isLongNames () const
Protected Attributes
std::stringstream _ss
std::vector< std::string > _input_file_record
bool _dump_mode
std::unique_ptr< TreeNode > _root
bool _use_long_names
Private Attributes
std::set< std::string > _params_printed
Detailed Description
Definition at line 23 of file ExodusFormatter.h.
Constructor & Destructor Documentation
ExodusFormatter()
ExodusFormatter::ExodusFormatter ()
Definition at line 24 of file ExodusFormatter.C.
: InputFileFormatter(false) {}
Member Function Documentation
format()
void ExodusFormatter::format ()
Definition at line 50 of file ExodusFormatter.C.
{
  std::string s;
  _input_file_record.clear();
  while (std::getline(_ss, s))
  {
    // MAX_LINE_LENGTH is from ExodusII
    if (s.length() > MAX_LINE_LENGTH)
    {
      const std::string continuation("...");
      const size_t cont_len = continuation.length();
      size_t num_lines = s.length() / (MAX_LINE_LENGTH - cont_len) + 1;
      std::string split_line;
      for (size_t j = 0, l_begin = 0; j < num_lines; ++j, l_begin += MAX_LINE_LENGTH - cont_len)
      {
        size_t l_len = MAX_LINE_LENGTH - cont_len;
        if (s.length() < l_begin + l_len)
          l_len = s.length() - l_begin;
        split_line = s.substr(l_begin, l_len);
        if (l_begin + l_len != s.length())
          split_line += continuation;
        _input_file_record.push_back(split_line);
      }
    }
    else
      _input_file_record.push_back(s);
  }
}
Referenced by Exodus::outputInput().
getInputFileRecord()
std::vector< std::string > & ExodusFormatter::getInputFileRecord () inline
Definition at line 32 of file ExodusFormatter.h.
{ return _input_file_record; }
Referenced by Exodus::outputInput().
haveSeenIt()
bool SyntaxTree::haveSeenIt (const std::string & prefix, const std::string & item) const inherited
Definition at line 63 of file SyntaxTree.C.
{
  return _params_printed.find(prefix + item) != _params_printed.end();
}
Referenced by InputFileFormatter::printParams(), and YAMLFormatter::printParams().
insertNode()
void SyntaxTree::insertNode (std::string syntax, const std::string & action, bool is_action_params = true, InputParameters * params = NULL) inherited
Definition at line 27 of file SyntaxTree.C.
{
  if (!_root)
    _root = std::make_unique<TreeNode>("", *this);
  _root->insertNode(syntax, action, is_action_params, params);
}
Referenced by ActionWarehouse::printInputFile().
isLongNames()
bool SyntaxTree::isLongNames () const protected inherited
Definition at line 227 of file SyntaxTree.C.
{
  return _use_long_names;
}
postscript()
virtual std::string SyntaxFormatterInterface::postscript () const inline virtual inherited
This method is called once at the end of the tree traversal and can be used to add any necessary trailing information to the final formatted string.
Returns
- The formatted postscript string
Reimplemented in YAMLFormatter.
Definition at line 41 of file SyntaxFormatterInterface.h.
{ return std::string(); }
Referenced by SyntaxTree::print().
preamble()
virtual std::string SyntaxFormatterInterface::preamble () const inline virtual inherited
This method is called once at the beginning of the tree traversal and can be used to build up header information.
Returns
- The formatted preamble string
Reimplemented in YAMLFormatter.
Definition at line 33 of file SyntaxFormatterInterface.h.
{ return std::string(); }
Referenced by SyntaxTree::print().
preTraverse()
virtual std::string SyntaxFormatterInterface::preTraverse (short) const inline virtual inherited
This method is called once at each node in the syntax tree before traversing child nodes.
Returns
- The formatted pre-node traversal string
Reimplemented in YAMLFormatter.
Definition at line 47 of file SyntaxFormatterInterface.h.
{ return std::string(); }
print()
std::string SyntaxTree::print (const std::string & search_string) inherited
Definition at line 39 of file SyntaxTree.C.
{
  bool found = false;
  std::string output;
  // Clear the list of "seen" parameters before printing the tree
  _params_printed.clear();
  if (_root)
    output = _root->print(-1, search_string, found);
  if (found)
    return preamble() + output + postscript();
  else
    return "";
}
Referenced by ActionWarehouse::printInputFile().
printBlockClose()
std::string InputFileFormatter::printBlockClose (const std::string & name, short depth) const override virtual inherited
This method is called at the end of of each Node in the tree.
It is typically used to provide formatting necessary when closing blocks.
Returns
- The formatted block close string
Implements SyntaxFormatterInterface.
Definition at line 35 of file InputFileFormatter.C.
{
  std::string indent(depth * 2, ' ');
  std::string closing_string;
  if (depth)
    closing_string = "../";
  return std::string("") + indent + "[" + closing_string + "]\n";
}
printBlockOpen()
std::string InputFileFormatter::printBlockOpen (const std::string & name, short depth, const std::string & doc) override virtual inherited
This method is called at the beginning of each Node in the tree.
It is typically used to provide formatting necessary when opening new blocks.
Returns
- The formatted block open string
Implements SyntaxFormatterInterface.
Definition at line 21 of file InputFileFormatter.C.
{
  std::string indent(depth * 2, ' ');
  std::string opening_string;
  if (depth)
    opening_string = "./";
  return std::string("\n") + indent + "[" + opening_string + name + "]\n";
}
printInputFile()
void ExodusFormatter::printInputFile (ActionWarehouse & wh)
Definition at line 27 of file ExodusFormatter.C.
{
  _ss << "####################\n"
      << "# Created by MOOSE #\n"
      << "####################\n";
  // Grab the command line arguments first
  _ss << "### Command Line Arguments ###\n";
  if (wh.mooseApp().commandLine())
  {
    for (const auto & arg : wh.mooseApp().commandLine()->getArguments())
      _ss << " " << arg;
  }
  if (wh.mooseApp().getSystemInfo() != NULL)
  {
    _ss << "### Version Info ###\n" << wh.mooseApp().getSystemInfo()->getInfo() << "\n";
  }
  _ss << "### Input File ###" << std::endl;
  wh.printInputFile(_ss);
}
Referenced by Exodus::outputInput().
printParams()
std::string InputFileFormatter::printParams (const std::string & prefix, const std::string & fully_qualified_name, InputParameters & params, short depth, const std::string & search_string, bool & found) override virtual inherited
This function is called for each InputParameters object stored at a particular node.
It is responsible for formatting the parameters for the current node.
Returns
- The formatted parameters string for a Node.
Implements SyntaxFormatterInterface.
Definition at line 47 of file InputFileFormatter.C.
{
  std::stringstream oss;
  std::string quotes = "";
  std::string spacing = "";
  std::string forward = "";
  std::string backdots = "";
  int offset = 30;
  for (int i = 0; i < depth; ++i)
  {
    spacing += "  ";
    forward = ".";
    offset -= 2;
  }
  for (const auto & iter : params)
  {
    // We only want non-private params and params that we haven't already seen
    if (params.isPrivate(iter.first) || haveSeenIt(fully_qualified_name, iter.first))
      continue;
    std::string value = "INVALID";
    if (params.isParamValid(iter.first))
    {
      // Print the parameter's value to a stringstream.
      std::ostringstream toss;
      iter.second->print(toss);
      value = MooseUtils::trim(toss.str());
    }
    else if (params.hasDefaultCoupledValue(iter.first))
    {
      std::ostringstream toss;
      toss << params.defaultCoupledValue(iter.first);
      value = toss.str();
    }
    // See if we match the search string
    if (MooseUtils::wildCardMatch(iter.first, search_string) ||
        MooseUtils::wildCardMatch(value, search_string))
    {
      // Don't print active if it is the default all, that means it's not in the input file - unless
      // of course we are in dump mode
      if (!_dump_mode && iter.first == "active")
      {
        if (params.have_parameter<std::vector<std::string>>(iter.first))
        {
          const auto & active = params.get<std::vector<std::string>>(iter.first);
          if (active.size() == 1 && active[0] == "__all__")
            continue;
        }
      }
      // Mark it as "seen"
      seenIt(fully_qualified_name, iter.first);
      // Don't print type if it is blank
      if (iter.first == "type")
      {
        if (params.have_parameter<std::string>(iter.first))
        {
          const auto & active = params.get<std::string>(iter.first);
          if (active == "")
            continue;
        }
      }
      found = true;
      oss << spacing << "  " << std::left << std::setw(offset) << iter.first << " = ";
      // std::setw() takes an int
      int l_offset = 30;
      if (!_dump_mode || value != "INVALID")
      {
        // If the value has spaces, surround it with quotes, otherwise no quotes
        if (value.find(' ') != std::string::npos)
        {
          quotes = "'";
          l_offset -= 2;
        }
        else
          quotes = "";
        if (value.size() == 0)
          value = "(no_default)";
        oss << quotes << value << quotes;
        l_offset -= value.size();
      }
      else if (_dump_mode && params.isParamRequired(iter.first))
      {
        oss << "(required)";
        l_offset -= 10;
      }
      // Documentation string
      if (_dump_mode)
      {
        std::vector<std::string> elements;
        std::string doc = params.getDocString(iter.first);
        if (MooseUtils::trim(doc) != "")
        {
          MooseUtils::tokenize(doc, elements, 68, " \t");
          for (auto & element : elements)
            MooseUtils::escape(element);
          oss << std::right << std::setw(l_offset) << "# " << elements[0];
          for (unsigned int i = 1; i < elements.size(); ++i)
            oss << " ...\n"
                << "  " << std::setw(63) << "# " << elements[i];
        }
        const std::string group = params.getGroupName(iter.first);
        if (!group.empty())
        {
          if (MooseUtils::trim(doc) != "")
            oss << " ...\n"
                << "  " << std::setw(70) << "# Group: " << group;
          else
            oss << std::right << std::setw(l_offset) << "# Group: " << group;
        }
      }
      oss << std::endl;
    }
  }
  return oss.str();
}
seenIt()
void SyntaxTree::seenIt (const std::string & prefix, const std::string & item) inherited
Definition at line 57 of file SyntaxTree.C.
{
  _params_printed.insert(prefix + item);
}
Referenced by InputFileFormatter::printParams(), and YAMLFormatter::printParams().
Member Data Documentation
_dump_mode
bool InputFileFormatter::_dump_mode protected inherited
Definition at line 34 of file InputFileFormatter.h.
Referenced by InputFileFormatter::printParams().
_input_file_record
std::vector<std::string> ExodusFormatter::_input_file_record protected
Definition at line 36 of file ExodusFormatter.h.
Referenced by format(), and getInputFileRecord().
_params_printed
std::set<std::string> SyntaxTree::_params_printed private inherited
Definition at line 80 of file SyntaxTree.h.
Referenced by SyntaxTree::haveSeenIt(), SyntaxTree::print(), and SyntaxTree::seenIt().
_root
std::unique_ptr<TreeNode> SyntaxTree::_root protected inherited
Definition at line 76 of file SyntaxTree.h.
Referenced by SyntaxTree::insertNode(), and SyntaxTree::print().
_ss
std::stringstream ExodusFormatter::_ss protected
Definition at line 35 of file ExodusFormatter.h.
Referenced by format(), and printInputFile().
_use_long_names
bool SyntaxTree::_use_long_names protected inherited
Definition at line 77 of file SyntaxTree.h.
Referenced by SyntaxTree::isLongNames().
The documentation for this class was generated from the following files:
moose/framework/include/outputs/formatters/ExodusFormatter.h
moose/framework/src/outputs/formatters/ExodusFormatter.C