Zapdos: AttribBoundaries Class Reference
AttribBoundaries Class Reference abstract
AttribBoundaries tracks all boundary IDs associated with an object.
#include <Attributes.h>
Public Types
typedef std::tuple< BoundaryID, bool > Key
Public Member Functions
void setFrom (Key k)
AttribBoundaries (TheWarehouse &w)
AttribBoundaries (TheWarehouse &w, BoundaryID id, bool must_be_restricted=false)
AttribBoundaries (TheWarehouse &w, const std::set< BoundaryID > &ids, bool must_be_restricted=false)
AttribBoundaries (TheWarehouse &w, const std::vector< BoundaryID > &ids, bool must_be_restricted=false)
virtual void initFrom (const MooseObject *obj) override
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
virtual bool isMatch (const Attribute &other) const override
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
virtual bool isEqual (const Attribute &other) const override
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
hashfunc (_vals, _must_be_restricted)
clonefunc (AttribBoundaries)
bool operator== (const Attribute &other) const
bool operator!= (const Attribute &other) const
unsigned int id () const
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
virtual std::size_t hash () const =0
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
virtual std::unique_ptr< Attribute > clone () const =0
clone creates and returns and identical (deep) copy of this attribute - i.e.
Private Attributes
std::vector< BoundaryID > _vals
bool _must_be_restricted = false
int _id = -1
Detailed Description
AttribBoundaries tracks all boundary IDs associated with an object.
When running queries, an object matches true if it has at least one boundary id in common with the boundary IDs in the query attribute.
Definition at line 188 of file Attributes.h.
Member Typedef Documentation
Key
typedef std::tuple<BoundaryID, bool> AttribBoundaries::Key
Definition at line 191 of file Attributes.h.
Constructor & Destructor Documentation
AttribBoundaries() [1/4]
AttribBoundaries::AttribBoundaries (TheWarehouse & w) inline
Definition at line 199 of file Attributes.h.
: Attribute(w, "boundaries") {}
AttribBoundaries() [2/4]
AttribBoundaries::AttribBoundaries (TheWarehouse & w, BoundaryID id, bool must_be_restricted = false) inline
Definition at line 200 of file Attributes.h.
    : Attribute(w, "boundaries"), _must_be_restricted(must_be_restricted)
  {
    _vals.push_back(id);
  }
AttribBoundaries() [3/4]
AttribBoundaries::AttribBoundaries (TheWarehouse & w, const std::set< BoundaryID > & ids, bool must_be_restricted = false) inline
Definition at line 205 of file Attributes.h.
    : Attribute(w, "boundaries"), _must_be_restricted(must_be_restricted)
  {
    for (auto id : ids)
      _vals.push_back(id);
  }
AttribBoundaries() [4/4]
AttribBoundaries::AttribBoundaries (TheWarehouse & w, const std::vector< BoundaryID > & ids, bool must_be_restricted = false) inline
Definition at line 213 of file Attributes.h.
    : Attribute(w, "boundaries"), _must_be_restricted(must_be_restricted)
  {
    _vals.reserve(ids.size());
    for (auto id : ids)
      _vals.push_back(id);
  }
Member Function Documentation
clone()
virtual std::unique_ptr< Attribute > Attribute::clone () const pure virtual inherited
clone creates and returns and identical (deep) copy of this attribute - i.e.
the result of clone should return true if passed into isMatch.
Referenced by FEProblemBase::computeUserObjectsInternal(), and TheWarehouse::update().
clonefunc()
AttribBoundaries::clonefunc (AttribBoundaries)
hash()
virtual std::size_t Attribute::hash () const pure virtual inherited
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
is initialized with). Ideally, the data should be uniformly and randomly distributed across the domain of size_t values - e.g. 1 and 2 should hash to completely unrelated values. Use of std::hash for POD is encouraged. A convenience hash_combine function is also provided to combine the results an existing hash with one or more other values.
Referenced by std::hash< Attribute >::operator()().
hashfunc()
AttribBoundaries::hashfunc (_vals , _must_be_restricted)
id()
unsigned int Attribute::id () const inline inherited
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
This ID is determined at construction time this
Definition at line 66 of file TheWarehouse.h.
{ return _id; }
Referenced by std::hash< Attribute >::operator()().
initFrom()
void AttribBoundaries::initFrom (const MooseObject * obj) override virtual
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
Implements Attribute.
Definition at line 220 of file Attributes.C.
{
  _vals.clear();
  auto bnd = dynamic_cast<const BoundaryRestrictable *>(obj);
  if (bnd && bnd->boundaryRestricted())
  {
    for (auto & bound : bnd->boundaryIDs())
      _vals.push_back(bound);
  }
  else
    _vals.push_back(Moose::ANY_BOUNDARY_ID);
}
isEqual()
bool AttribBoundaries::isEqual (const Attribute & other) const override virtual
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
isEqual does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 254 of file Attributes.C.
{
  auto a = dynamic_cast<const AttribBoundaries *>(&other);
  if (!a || a->_vals.size() != _vals.size())
    return false;
  for (size_t i = 0; i < a->_vals.size(); i++)
    if (a->_vals[i] != _vals[i])
      return false;
  return true;
}
isMatch()
bool AttribBoundaries::isMatch (const Attribute & other) const override virtual
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
This is is for query matching - not exact equivalence. isMatch does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 234 of file Attributes.C.
{
  auto a = dynamic_cast<const AttribBoundaries *>(&other);
  if (!a || a->_vals.size() < 1)
    return false;
  // return true if a single tag matches between the two attribute objects
  for (auto val : _vals)
  {
    if (!a->_must_be_restricted && (val == Moose::ANY_BOUNDARY_ID))
      return true;
    if (std::find(a->_vals.begin(), a->_vals.end(), val) != a->_vals.end())
      return true;
    else if (std::find(a->_vals.begin(), a->_vals.end(), Moose::ANY_BOUNDARY_ID) != a->_vals.end())
      return true;
  }
  return false;
}
operator!=()
bool Attribute::operator!= (const Attribute & other) const inline inherited
Definition at line 61 of file TheWarehouse.h.
{ return !(*this == other); }
operator==()
bool Attribute::operator== (const Attribute & other) const inline inherited
Definition at line 57 of file TheWarehouse.h.
  {
    return _id == other._id && isEqual(other);
  }
setFrom()
void AttribBoundaries::setFrom (Key k) inline
Definition at line 192 of file Attributes.h.
  {
    _vals.clear();
    _vals.push_back(std::get<0>(k));
    _must_be_restricted = std::get<1>(k);
  }
Member Data Documentation
_id
int Attribute::_id = -1 private inherited
Definition at line 91 of file TheWarehouse.h.
Referenced by Attribute::id(), and Attribute::operator==().
_must_be_restricted
bool AttribBoundaries::_must_be_restricted = false private
Definition at line 230 of file Attributes.h.
Referenced by setFrom().
_vals
std::vector<BoundaryID> AttribBoundaries::_vals private
Definition at line 229 of file Attributes.h.
Referenced by AttribBoundaries(), initFrom(), isEqual(), isMatch(), and setFrom().
The documentation for this class was generated from the following files:
moose/framework/include/base/Attributes.h
moose/framework/src/base/Attributes.C