Zapdos: SetupInterface Class Reference
SetupInterface Class Reference
#include <SetupInterface.h>
Public Member Functions
SetupInterface (const MooseObject *moose_object)
virtual ~SetupInterface ()
virtual void initialSetup ()
Gets called at the beginning of the simulation before this object is asked to do its job.
virtual void timestepSetup ()
Gets called at the beginning of the timestep before this object is asked to do its job.
virtual void jacobianSetup ()
Gets called just before the Jacobian is computed and before this object is asked to do its job.
virtual void residualSetup ()
Gets called just before the residual is computed and before this object is asked to do its job.
virtual void subdomainSetup ()
Gets called when the subdomain changes (i.e.
virtual void customSetup (const ExecFlagType &)
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
const ExecFlagEnum & getExecuteOnEnum () const
Return the execute on MultiMooseEnum for this object.
Static Public Member Functions
static InputParameters validParams ()
Protected Attributes
const ExecFlagEnum & _execute_enum
Execute settings for this object.
const ExecFlagType & _current_execute_flag
Reference to FEProblemBase.
Private Attributes
ExecFlagEnum _empty_execute_enum
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
Friends
class FEProblemBase
Detailed Description
Definition at line 23 of file SetupInterface.h.
Constructor & Destructor Documentation
SetupInterface()
SetupInterface::SetupInterface (const MooseObject * moose_object)
Definition at line 26 of file SetupInterface.C.
  : _execute_enum(moose_object->parameters().isParamValid("execute_on")
                      ? moose_object->parameters().get<ExecFlagEnum>("execute_on")
                      : _empty_execute_enum),
    _current_execute_flag(
        (moose_object->parameters().getCheckedPointerParam<FEProblemBase *>("_fe_problem_base"))
            ->getCurrentExecuteOnFlag())
{
  _empty_execute_enum.clear(); // remove any flags for the case when "execute_on" is not used
}
~SetupInterface()
SetupInterface::~SetupInterface () virtual
Definition at line 37 of file SetupInterface.C.
{}
Member Function Documentation
customSetup()
virtual void SetupInterface::customSetup (const ExecFlagType &) inline virtual
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
Reimplemented in Function.
Definition at line 61 of file SetupInterface.h.
{}
getExecuteOnEnum()
const ExecFlagEnum & SetupInterface::getExecuteOnEnum () const
Return the execute on MultiMooseEnum for this object.
Definition at line 65 of file SetupInterface.C.
{
  return _execute_enum;
}
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), MultiAppTransfer::checkMultiAppExecuteOn(), IntegralPreservingFunctionIC::initialSetup(), MultiAppConservativeTransfer::initialSetup(), Terminator::initialSetup(), ElementReporter::shouldStore(), GeneralReporter::shouldStore(), and NodalReporter::shouldStore().
initialSetup()
void SetupInterface::initialSetup () virtual
Gets called at the beginning of the simulation before this object is asked to do its job.
Reimplemented in DerivativeSumMaterialTempl< is_ad >, AdvancedOutput, MultiAppFieldTransfer, Transfer, MortarNodalAuxKernelTempl< ComputeValueType >, ProjectedStatefulMaterialAuxTempl< T, is_ad >, SolutionAux, SolutionScalarAux, TimePeriod, Axisymmetric2D3DSolutionFunction, CoarsenedPiecewiseLinear, ImageFunction, MooseParsedFunction, MooseParsedGradFunction, MooseParsedVectorFunction, PiecewiseConstantFromCSV, PiecewiseLinear, PiecewiseLinearBase, PiecewiseTabularBase, SolutionFunction, LibtorchControlValuePostprocessor, LibtorchArtificialNeuralNetParameters, DerivativeFunctionMaterialBaseTempl< is_ad >, DerivativeFunctionMaterialBaseTempl< is_ad >, FullSolveMultiApp, MultiApp, TransientMultiApp, Console, CSV, Exodus, Nemesis, OversampleOutput, NodalVariableValue, SideIntegralMaterialPropertyTempl< is_ad >, MultiAppCloneReporterTransfer, MultiAppConservativeTransfer, MultiAppDofCopyTransfer, MultiAppGeneralFieldNearestLocationTransfer, MultiAppGeneralFieldTransfer, MultiAppProjectionTransfer, MultiAppReporterTransfer, MultiAppTransfer, MultiAppVariableValueSamplePostprocessorTransfer, MultiAppVariableValueSampleTransfer, ElementSubdomainModifier, GhostingUserObject, InterfaceQpUserObjectBase, NodalPatchRecoveryMaterialProperty, ProjectedStatefulMaterialNodalPatchRecoveryTempl< T, is_ad >, RadialAverage, SolutionUserObject, Terminator, MooseVariableBase, HistogramVectorPostprocessor, and DGFunctionTemperatureAdvection.
Definition at line 40 of file SetupInterface.C.
{
}
Referenced by LibtorchControlValuePostprocessor::initialSetup(), Console::initialSetup(), CSV::initialSetup(), and Positions::meshChanged().
jacobianSetup()
void SetupInterface::jacobianSetup () virtual
Gets called just before the Jacobian is computed and before this object is asked to do its job.
Reimplemented in EqualValueEmbeddedConstraint, Function, ADKernelTempl< T >, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 50 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::jacobianSetup(), and ComputeFVFluxJacobianThread< RangeType >::setup().
residualSetup()
void SetupInterface::residualSetup () virtual
Gets called just before the residual is computed and before this object is asked to do its job.
Reimplemented in NodeFaceConstraint, Function, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 55 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::residualSetup(), ComputeFVFluxResidualThread< RangeType >::setup(), and ComputeFVFluxRJThread< RangeType >::setup().
subdomainSetup()
void SetupInterface::subdomainSetup () virtual
Gets called when the subdomain changes (i.e.
in a Jacobian or residual loop) and before this object is asked to do its job
Reimplemented in Material, MaterialBase, GeneralUserObject, NodalUserObject, ThreadedGeneralUserObject, and Constraint.
Definition at line 60 of file SetupInterface.C.
{
}
timestepSetup()
void SetupInterface::timestepSetup () virtual
Gets called at the beginning of the timestep before this object is asked to do its job.
Reimplemented in VectorPostprocessorVisualizationAux, EqualValueEmbeddedConstraint, Function, Console, JSONOutput, Positions, MemoryUsage, NumNonlinearIterations, Times, SolutionUserObject, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, MooseVariableFV< T >, and VectorMemoryUsage.
Definition at line 45 of file SetupInterface.C.
{
}
Referenced by JSONOutput::timestepSetup(), and MooseVariableField< OutputType >::timestepSetup().
validParams()
InputParameters SetupInterface::validParams () static
Definition at line 15 of file SetupInterface.C.
{
  InputParameters params = emptyInputParameters();
  // Add the 'execute_on' input parameter for users to set
  ExecFlagEnum execute_options = MooseUtils::getDefaultExecFlagEnum();
  execute_options = EXEC_LINEAR;
  params.addParam<ExecFlagEnum>("execute_on", execute_options, execute_options.getDocString());
  return params;
}
Referenced by AuxKernelTempl< ComputeValueType >::validParams(), AuxScalarKernel::validParams(), Control::validParams(), Function::validParams(), FunctorMaterial::validParams(), FVInterfaceKernel::validParams(), MultiApp::validParams(), Output::validParams(), Sampler::validParams(), Transfer::validParams(), and UserObject::validParams().
Friends And Related Function Documentation
FEProblemBase
friend class FEProblemBase friend
Definition at line 81 of file SetupInterface.h.
Member Data Documentation
_current_execute_flag
const ExecFlagType& SetupInterface::_current_execute_flag protected
Reference to FEProblemBase.
Definition at line 78 of file SetupInterface.h.
Referenced by PseudoTimestep::execute().
_empty_execute_enum
ExecFlagEnum SetupInterface::_empty_execute_enum private
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
This is private because others should not be messing with it.
Definition at line 71 of file SetupInterface.h.
Referenced by SetupInterface().
_execute_enum
const ExecFlagEnum& SetupInterface::_execute_enum protected
Execute settings for this object.
Definition at line 75 of file SetupInterface.h.
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), getExecuteOnEnum(), JSONOutput::outputReporters(), XMLOutput::outputVectorPostprocessors(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
The documentation for this class was generated from the following files:
moose/framework/include/interfaces/SetupInterface.h
moose/framework/src/interfaces/SetupInterface.C