Zapdos: DerivativeKernelInterface< T > Class Template Reference
DerivativeKernelInterface< T > Class Template Reference
Interface class ("Veneer") to provide generator methods for derivative material property names, and guarded getMaterialPropertyPointer calls.
#include <DerivativeKernelInterface.h>
Public Types
typedef DerivativeMaterialPropertyNameInterface::SymbolName SymbolName
Public Member Functions
DerivativeKernelInterface (const InputParameters &parameters)
template<typename U , bool is_ad = false>
const GenericMaterialProperty< U, is_ad > & getDefaultMaterialProperty (const std::string &name)
Fetch a material property if it exists, otherwise return getZeroMaterialProperty.
template<typename U , bool is_ad = false>
const GenericMaterialProperty< U, is_ad > & getDefaultMaterialPropertyByName (const std::string &name)
Fetch a material property by name if it exists, otherwise return getZeroMaterialProperty.
template<typename U , bool is_ad = false>
void validateDerivativeMaterialPropertyBase (const std::string &base)
Check if the material property base exists.
const MaterialPropertyName derivativePropertyName (const MaterialPropertyName &base, const std::vector< SymbolName > &c) const
Helper functions to generate the material property names for the arbitrary derivatives.
const MaterialPropertyName derivativePropertyNameFirst (const MaterialPropertyName &base, const SymbolName &c1) const
Helper functions to generate the material property names for the first derivatives.
const MaterialPropertyName derivativePropertyNameSecond (const MaterialPropertyName &base, const SymbolName &c1, const SymbolName &c2) const
Helper functions to generate the material property names for the second derivatives.
const MaterialPropertyName derivativePropertyNameThird (const MaterialPropertyName &base, const SymbolName &c1, const SymbolName &c2, const SymbolName &c3) const
Helper functions to generate the material property names for the third derivatives.
template<typename U , bool is_ad = false>
GenericMaterialProperty< U, is_ad > & declarePropertyDerivative (const std::string &base, const std::vector< VariableName > &c)
Methods for declaring derivative material properties.
template<typename U , bool is_ad = false>
GenericMaterialProperty< U, is_ad > & declarePropertyDerivative (const std::string &base, const std::vector< SymbolName > &c)
template<typename U , bool is_ad = false>
GenericMaterialProperty< U, is_ad > & declarePropertyDerivative (const std::string &base, const SymbolName &c1, const SymbolName &c2="", const SymbolName &c3="")
template<typename U , bool is_ad = false>
const GenericMaterialProperty< U, is_ad > & getMaterialPropertyDerivative (const std::string &base, const std::vector< VariableName > &c)
Methods for retrieving derivative material properties.
template<typename U , bool is_ad = false>
const GenericMaterialProperty< U, is_ad > & getMaterialPropertyDerivative (const std::string &base, const std::vector< SymbolName > &c)
template<typename U , bool is_ad = false>
const GenericMaterialProperty< U, is_ad > & getMaterialPropertyDerivative (const std::string &base, const SymbolName &c1, const SymbolName &c2="", const SymbolName &c3="")
template<typename U , bool is_ad = false>
const GenericMaterialProperty< U, is_ad > & getMaterialPropertyDerivative (const std::string &base, const SymbolName &c1, unsigned int v2, unsigned int v3=libMesh::invalid_uint)
Convenience methods for retrieving derivative material properties based on a mix of variable names c and indices v into the _coupled_standard_moose_vars vector.
template<typename U , bool is_ad = false>
const GenericMaterialProperty< U, is_ad > & getMaterialPropertyDerivative (const std::string &base, unsigned int v1, unsigned int v2=libMesh::invalid_uint, unsigned int v3=libMesh::invalid_uint)
template<typename U , bool is_ad = false>
const GenericMaterialProperty< U, is_ad > & getMaterialPropertyDerivativeByName (const MaterialPropertyName &base, const std::vector< VariableName > &c)
Methods for retrieving derivative material properties.
template<typename U , bool is_ad = false>
const GenericMaterialProperty< U, is_ad > & getMaterialPropertyDerivativeByName (const MaterialPropertyName &base, const std::vector< SymbolName > &c)
template<typename U , bool is_ad = false>
const GenericMaterialProperty< U, is_ad > & getMaterialPropertyDerivativeByName (const MaterialPropertyName &base, const SymbolName &c1, const SymbolName &c2="", const SymbolName &c3="")
template<typename U , bool is_ad = false>
void validateCoupling (const MaterialPropertyName &base, const std::vector< VariableName > &c, bool validate_aux=true)
check if derivatives of the passed in material property exist w.r.t a variable that is not coupled in to the current object
template<typename U , bool is_ad = false>
void validateCoupling (const MaterialPropertyName &base, const VariableName &c1="", const VariableName &c2="", const VariableName &c3="")
template<typename U , bool is_ad = false>
void validateNonlinearCoupling (const MaterialPropertyName &base, const VariableName &c1="", const VariableName &c2="", const VariableName &c3="")
const MaterialPropertyName propertyName (const MaterialPropertyName &base, const std::vector< SymbolName > &c) const
aliases for the deprecated old function names
const MaterialPropertyName propertyNameFirst (const MaterialPropertyName &base, const SymbolName &c1) const
const MaterialPropertyName propertyNameSecond (const MaterialPropertyName &base, const SymbolName &c1, const SymbolName &c2) const
const MaterialPropertyName propertyNameThird (const MaterialPropertyName &base, const SymbolName &c1, const SymbolName &c2, const SymbolName &c3) const
Static Public Member Functions
static InputParameters validParams ()
as partial template specialization is not allowed in C++ we have to implement this as a static method
Protected Attributes
unsigned int _nvar
std::string _F_name
Private Member Functions
template<typename U , bool is_ad = false>
bool haveMaterialProperty (const std::string &prop_name)
Check if a material property is present with the applicable restrictions.
std::vector< VariableName > buildVariableVector (const VariableName &c1, const VariableName &c2, const VariableName &c3)
helper method to combine multiple VariableNames into a vector (if they are != "")
template<typename U , bool is_ad = false>
void validateCouplingHelper (const MaterialPropertyName &base, const std::vector< VariableName > &c, const System &system, std::vector< VariableName > &missing)
helper method to compile list of missing coupled variables for a given system
bool isNotObjectVariable (const VariableName &name)
Private Attributes
FEProblemBase & _dmi_fe_problem
Reference to FEProblemBase.
Detailed Description
template<class T>
class DerivativeKernelInterface< T >
Interface class ("Veneer") to provide generator methods for derivative material property names, and guarded getMaterialPropertyPointer calls.
Definition at line 19 of file DerivativeKernelInterface.h.
Member Typedef Documentation
SymbolName
template<class T > typedef DerivativeMaterialPropertyNameInterface::SymbolName DerivativeMaterialInterface< T >::SymbolName inherited
Definition at line 35 of file DerivativeMaterialInterface.h.
Constructor & Destructor Documentation
DerivativeKernelInterface()
template<class T > DerivativeKernelInterface< T >::DerivativeKernelInterface (const InputParameters & parameters)
Definition at line 33 of file DerivativeKernelInterface.h.
  : DerivativeMaterialInterface<T>(parameters),
    _nvar(this->_coupled_moose_vars.size()),
    _F_name(this->template getRenamedParam<std::string>("f_name", "property_name"))
{
}
Member Function Documentation
buildVariableVector()
template<class T > std::vector< VariableName > DerivativeMaterialInterface< T >::buildVariableVector (const VariableName & c1, const VariableName & c2, const VariableName & c3) private inherited
helper method to combine multiple VariableNames into a vector (if they are != "")
Definition at line 494 of file DerivativeMaterialInterface.h.
{
  std::vector<VariableName> c;
  if (c1 != "")
  {
    c.push_back(c1);
    if (c2 != "")
    {
      c.push_back(c2);
      if (c3 != "")
        c.push_back(c3);
    }
  }
  return c;
}
declarePropertyDerivative() [1/3]
template<class T > template<typename U , bool is_ad> GenericMaterialProperty< U, is_ad > & DerivativeMaterialInterface< T >::declarePropertyDerivative (const std::string & base, const std::vector< SymbolName > & c) inherited
Definition at line 268 of file DerivativeMaterialInterface.h.
{
  return this->template declareGenericProperty<U, is_ad>(derivativePropertyName(base, c));
}
declarePropertyDerivative() [2/3]
template<class T > template<typename U , bool is_ad> GenericMaterialProperty< U, is_ad > & DerivativeMaterialInterface< T >::declarePropertyDerivative (const std::string & base, const std::vector< VariableName > & c) inherited
Methods for declaring derivative material properties.
Template Parameters
U The material property type
Parameters
base The name of the property to take the derivative of
c The variable(s) to take the derivatives with respect to
Definition at line 258 of file DerivativeMaterialInterface.h.
{
  std::vector<SymbolName> symbol_vector(c.begin(), c.end());
  return declarePropertyDerivative<U, is_ad>(base, symbol_vector);
}
declarePropertyDerivative() [3/3]
template<class T > template<typename U , bool is_ad> GenericMaterialProperty< U, is_ad > & DerivativeMaterialInterface< T >::declarePropertyDerivative (const std::string & base, const SymbolName & c1, const SymbolName & c2 = "", const SymbolName & c3 = "") inherited
Definition at line 277 of file DerivativeMaterialInterface.h.
{
  if (c3 != "")
    return this->template declareGenericProperty<U, is_ad>(
        derivativePropertyNameThird(base, c1, c2, c3));
  if (c2 != "")
    return this->template declareGenericProperty<U, is_ad>(
        derivativePropertyNameSecond(base, c1, c2));
  return this->template declareGenericProperty<U, is_ad>(derivativePropertyNameFirst(base, c1));
}
derivativePropertyName()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::derivativePropertyName (const MaterialPropertyName & base, const std::vector< SymbolName > & c) const inherited
Helper functions to generate the material property names for the arbitrary derivatives.
Definition at line 16 of file DerivativeMaterialPropertyNameInterface.C.
{
  // to obtain well defined names we sort alphabetically
  std::vector<SymbolName> a(c);
  std::sort(a.begin(), a.end());
  // derivative order
  unsigned int order = a.size();
  if (order == 0)
    return base;
  // build the property name as a stringstream
  std::stringstream name;
  // build numerator
  name << 'd';
  if (order > 1)
    name << '^' << order;
  name << base << '/';
  // build denominator with 'pretty' names using exponents rather than repeat multiplication
  unsigned int exponent = 1;
  for (unsigned i = 1; i <= order; ++i)
  {
    if (i == order || a[i - 1] != a[i])
    {
      name << 'd' << a[i - 1];
      if (exponent > 1)
        name << '^' << exponent;
      exponent = 1;
    }
    else
      exponent++;
  }
  return name.str();
}
Referenced by DerivativeMaterialPropertyNameInterface::derivativePropertyNameSecond(), DerivativeMaterialPropertyNameInterface::derivativePropertyNameThird(), and DerivativeMaterialPropertyNameInterface::propertyName().
derivativePropertyNameFirst()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::derivativePropertyNameFirst (const MaterialPropertyName & base, const SymbolName & c1) const inherited
Helper functions to generate the material property names for the first derivatives.
Definition at line 56 of file DerivativeMaterialPropertyNameInterface.C.
{
  return "d" + base + "/d" + c1;
}
Referenced by DerivativeMaterialPropertyNameInterface::propertyNameFirst().
derivativePropertyNameSecond()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::derivativePropertyNameSecond (const MaterialPropertyName & base, const SymbolName & c1, const SymbolName & c2) const inherited
Helper functions to generate the material property names for the second derivatives.
Definition at line 63 of file DerivativeMaterialPropertyNameInterface.C.
{
  return derivativePropertyName(base, {c1, c2});
}
Referenced by DerivativeMaterialPropertyNameInterface::propertyNameSecond().
derivativePropertyNameThird()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::derivativePropertyNameThird (const MaterialPropertyName & base, const SymbolName & c1, const SymbolName & c2, const SymbolName & c3) const inherited
Helper functions to generate the material property names for the third derivatives.
Definition at line 70 of file DerivativeMaterialPropertyNameInterface.C.
{
  return derivativePropertyName(base, {c1, c2, c3});
}
Referenced by DerivativeMaterialPropertyNameInterface::propertyNameThird().
getDefaultMaterialProperty()
template<class T > template<typename U , bool is_ad> const GenericMaterialProperty< U, is_ad > & DerivativeMaterialInterface< T >::getDefaultMaterialProperty (const std::string & name) inherited
Fetch a material property if it exists, otherwise return getZeroMaterialProperty.
Parameters
name The input parameter key of type MaterialPropertyName
Definition at line 231 of file DerivativeMaterialInterface.h.
{
  // get the base property name
  std::string prop_name = this->getMaterialPropertyName(name);
  // Check if it's just a constant
  const auto * default_property =
      this->template defaultGenericMaterialProperty<U, is_ad>(prop_name);
  if (default_property)
    return *default_property;
  // if found return the requested property
  return this->template getGenericZeroMaterialPropertyByName<U, is_ad>(prop_name);
}
getDefaultMaterialPropertyByName()
template<class T > template<typename U , bool is_ad> const GenericMaterialProperty< U, is_ad > & DerivativeMaterialInterface< T >::getDefaultMaterialPropertyByName (const std::string & name) inherited
Fetch a material property by name if it exists, otherwise return getZeroMaterialProperty.
Definition at line 249 of file DerivativeMaterialInterface.h.
{
  // TODO: deprecate this
  return this->template getGenericZeroMaterialPropertyByName<U, is_ad>(prop_name);
}
getMaterialPropertyDerivative() [1/5]
template<class T > template<typename U , bool is_ad> const GenericMaterialProperty< U, is_ad > & DerivativeMaterialInterface< T >::getMaterialPropertyDerivative (const std::string & base, const std::vector< SymbolName > & c) inherited
Check if base is a default property and shortcut to returning zero, as derivatives of constants are zero.
Definition at line 304 of file DerivativeMaterialInterface.h.
{
  // get the base property name
  std::string prop_name = this->getMaterialPropertyName(base);
  if (this->template defaultGenericMaterialProperty<U, is_ad>(prop_name))
    return this->template getGenericZeroMaterialProperty<U, is_ad>();
  return this->template getGenericZeroMaterialPropertyByName<U, is_ad>(
      derivativePropertyName(prop_name, c));
}
getMaterialPropertyDerivative() [2/5]
template<class T > template<typename U , bool is_ad> const GenericMaterialProperty< U, is_ad > & DerivativeMaterialInterface< T >::getMaterialPropertyDerivative (const std::string & base, const std::vector< VariableName > & c) inherited
Methods for retrieving derivative material properties.
Template Parameters
U The material property type
Parameters
base The name of the property to take the derivative of
c The variable(s) to take the derivatives with respect to
Definition at line 294 of file DerivativeMaterialInterface.h.
{
  std::vector<SymbolName> symbol_vector(c.begin(), c.end());
  return getMaterialPropertyDerivative(base, symbol_vector);
}
getMaterialPropertyDerivative() [3/5]
template<class T > template<typename U , bool is_ad> const GenericMaterialProperty< U, is_ad > & DerivativeMaterialInterface< T >::getMaterialPropertyDerivative (const std::string & base, const SymbolName & c1, const SymbolName & c2 = "", const SymbolName & c3 = "") inherited
Check if base is a default property and shortcut to returning zero, as derivatives of constants are zero.
Definition at line 324 of file DerivativeMaterialInterface.h.
{
  // get the base property name
  std::string prop_name = this->getMaterialPropertyName(base);
  if (this->template defaultGenericMaterialProperty<U, is_ad>(prop_name))
    return this->template getGenericZeroMaterialProperty<U, is_ad>();
  if (c3 != "")
    return this->template getGenericZeroMaterialPropertyByName<U, is_ad>(
        derivativePropertyNameThird(prop_name, c1, c2, c3));
  if (c2 != "")
    return this->template getGenericZeroMaterialPropertyByName<U, is_ad>(
        derivativePropertyNameSecond(prop_name, c1, c2));
  return this->template getGenericZeroMaterialPropertyByName<U, is_ad>(
      derivativePropertyNameFirst(prop_name, c1));
}
getMaterialPropertyDerivative() [4/5]
template<class T > template<typename U , bool is_ad> const GenericMaterialProperty< U, is_ad > & DerivativeMaterialInterface< T >::getMaterialPropertyDerivative (const std::string & base, const SymbolName & c1, unsigned int v2, unsigned int v3 = libMesh::invalid_uint) inherited
Convenience methods for retrieving derivative material properties based on a mix of variable names c and indices v into the _coupled_standard_moose_vars vector.
Definition at line 352 of file DerivativeMaterialInterface.h.
{
  return getMaterialPropertyDerivative<U, is_ad>(
      base,
      c1,
      this->_coupled_standard_moose_vars[v2]->name(),
      v3 == libMesh::invalid_uint ? "" : this->_coupled_standard_moose_vars[v3]->name());
}
getMaterialPropertyDerivative() [5/5]
template<class T > template<typename U , bool is_ad> const GenericMaterialProperty< U, is_ad > & DerivativeMaterialInterface< T >::getMaterialPropertyDerivative (const std::string & base, unsigned int v1, unsigned int v2 = libMesh::invalid_uint, unsigned int v3 = libMesh::invalid_uint) inherited
Definition at line 367 of file DerivativeMaterialInterface.h.
{
  return getMaterialPropertyDerivative<U, is_ad>(
      base,
      this->_coupled_standard_moose_vars[v1]->name(),
      v2 == libMesh::invalid_uint ? "" : this->_coupled_standard_moose_vars[v2]->name(),
      v3 == libMesh::invalid_uint ? "" : this->_coupled_standard_moose_vars[v3]->name());
}
getMaterialPropertyDerivativeByName() [1/3]
template<class T > template<typename U , bool is_ad> const GenericMaterialProperty< U, is_ad > & DerivativeMaterialInterface< T >::getMaterialPropertyDerivativeByName (const MaterialPropertyName & base, const std::vector< SymbolName > & c) inherited
Definition at line 392 of file DerivativeMaterialInterface.h.
{
  return this->template getGenericZeroMaterialPropertyByName<U, is_ad>(
      derivativePropertyName(base, c));
}
getMaterialPropertyDerivativeByName() [2/3]
template<class T > template<typename U , bool is_ad> const GenericMaterialProperty< U, is_ad > & DerivativeMaterialInterface< T >::getMaterialPropertyDerivativeByName (const MaterialPropertyName & base, const std::vector< VariableName > & c) inherited
Methods for retrieving derivative material properties.
Template Parameters
U The material property type
Parameters
base The name of the property to take the derivative of
c The variable(s) to take the derivatives with respect to
Definition at line 382 of file DerivativeMaterialInterface.h.
{
  std::vector<SymbolName> symbol_vector(c.begin(), c.end());
  return getMaterialPropertyDerivativeByName(base, symbol_vector);
}
getMaterialPropertyDerivativeByName() [3/3]
template<class T > template<typename U , bool is_ad> const GenericMaterialProperty< U, is_ad > & DerivativeMaterialInterface< T >::getMaterialPropertyDerivativeByName (const MaterialPropertyName & base, const SymbolName & c1, const SymbolName & c2 = "", const SymbolName & c3 = "") inherited
Definition at line 402 of file DerivativeMaterialInterface.h.
{
  if (c3 != "")
    return this->template getGenericZeroMaterialPropertyByName<U, is_ad>(
        derivativePropertyNameThird(base, c1, c2, c3));
  if (c2 != "")
    return this->template getGenericZeroMaterialPropertyByName<U, is_ad>(
        derivativePropertyNameSecond(base, c1, c2));
  return this->template getGenericZeroMaterialPropertyByName<U, is_ad>(
      derivativePropertyNameFirst(base, c1));
}
haveMaterialProperty()
template<class T > template<typename U , bool is_ad> bool DerivativeMaterialInterface< T >::haveMaterialProperty (const std::string & prop_name) private inherited
Check if a material property is present with the applicable restrictions.
Definition at line 217 of file DerivativeMaterialInterface.h.
{
  // Call the correct method to test for material property declarations
  BlockRestrictable * blk = dynamic_cast<BlockRestrictable *>(this);
  BoundaryRestrictable * bnd = dynamic_cast<BoundaryRestrictable *>(this);
  return ((bnd && bnd->boundaryRestricted() &&
           bnd->template hasBoundaryMaterialProperty<U, is_ad>(prop_name)) ||
          (blk && blk->template hasBlockMaterialProperty<U, is_ad>(prop_name)) ||
          (this->template hasGenericMaterialProperty<U, is_ad>(prop_name)));
}
isNotObjectVariable()
template<class T > bool DerivativeMaterialInterface< T >::isNotObjectVariable (const VariableName & name) inline private inherited
Definition at line 555 of file DerivativeMaterialInterface.h.
{
  // try to cast this to a Kernel pointer
  KernelBase * kernel_ptr = dynamic_cast<KernelBase *>(this);
  if (kernel_ptr != nullptr)
    return kernel_ptr->variable().name() != name;
  // try to cast this to a BoundaryCondition pointer
  BoundaryCondition * bc_ptr = dynamic_cast<BoundaryCondition *>(this);
  if (bc_ptr != nullptr)
    return bc_ptr->variable().name() != name;
  // This interface is not templated on a class derived from either Kernel or BC
  return true;
}
propertyName()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::propertyName (const MaterialPropertyName & base, const std::vector< SymbolName > & c) const inline inherited
aliases for the deprecated old function names
Definition at line 59 of file DerivativeMaterialPropertyNameInterface.h.
  {
    mooseDeprecated("This function was renamed to 'derivativePropertyName'");
    return derivativePropertyName(base, c);
  }
propertyNameFirst()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::propertyNameFirst (const MaterialPropertyName & base, const SymbolName & c1) const inline inherited
Definition at line 65 of file DerivativeMaterialPropertyNameInterface.h.
  {
    mooseDeprecated("This function was renamed to 'derivativePropertyNameFirst'");
    return derivativePropertyNameFirst(base, c1);
  }
propertyNameSecond()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::propertyNameSecond (const MaterialPropertyName & base, const SymbolName & c1, const SymbolName & c2) const inline inherited
Definition at line 71 of file DerivativeMaterialPropertyNameInterface.h.
  {
    mooseDeprecated("This function was renamed to 'derivativePropertyNameSecond'");
    return derivativePropertyNameSecond(base, c1, c2);
  }
propertyNameThird()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::propertyNameThird (const MaterialPropertyName & base, const SymbolName & c1, const SymbolName & c2, const SymbolName & c3) const inline inherited
Definition at line 78 of file DerivativeMaterialPropertyNameInterface.h.
  {
    mooseDeprecated("This function was renamed to 'derivativePropertyNameThird'");
    return derivativePropertyNameThird(base, c1, c2, c3);
  }
validateCoupling() [1/2]
template<class T > template<typename U , bool is_ad> void DerivativeMaterialInterface< T >::validateCoupling (const MaterialPropertyName & base, const std::vector< VariableName > & c, bool validate_aux = true) inherited
check if derivatives of the passed in material property exist w.r.t a variable that is not coupled in to the current object
Definition at line 461 of file DerivativeMaterialInterface.h.
{
  // get the base property name
  std::string prop_name = this->getMaterialPropertyName(base);
  // list of potentially missing coupled variables
  std::vector<VariableName> missing;
  // iterate over all variables in the both the non-linear and auxiliary system (optional)
  validateCouplingHelper<U, is_ad>(
      prop_name, c, _dmi_fe_problem.getNonlinearSystemBase(/*nl_sys=*/0).system(), missing);
  if (validate_aux)
    validateCouplingHelper<U, is_ad>(
        prop_name, c, _dmi_fe_problem.getAuxiliarySystem().system(), missing);
  if (missing.size() > 0)
  {
    // join list of missing variable names
    std::string list = missing[0];
    for (unsigned int i = 1; i < missing.size(); ++i)
      list += ", " + missing[i];
    mooseWarning("Missing coupled variables {",
                 list,
                 "} (add them to coupled_variables parameter of ",
                 this->name(),
                 ")");
  }
}
validateCoupling() [2/2]
template<class T > template<typename U , bool is_ad> void DerivativeMaterialInterface< T >::validateCoupling (const MaterialPropertyName & base, const VariableName & c1 = "", const VariableName & c2 = "", const VariableName & c3 = "") inherited
Definition at line 515 of file DerivativeMaterialInterface.h.
{
  validateCoupling<U, is_ad>(base, buildVariableVector(c1, c2, c3), true);
}
validateCouplingHelper()
template<class T > template<typename U , bool is_ad> void DerivativeMaterialInterface< T >::validateCouplingHelper (const MaterialPropertyName & base, const std::vector< VariableName > & c, const System & system, std::vector< VariableName > & missing) private inherited
helper method to compile list of missing coupled variables for a given system
Definition at line 421 of file DerivativeMaterialInterface.h.
{
  unsigned int ncoupled = this->_coupled_standard_moose_vars.size();
  // iterate over all variables in the current system (in groups)
  for (unsigned int i = 0; i < system.n_variable_groups(); ++i)
  {
    const VariableGroup & vg = system.variable_group(i);
    for (unsigned int j = 0; j < vg.n_variables(); ++j)
    {
      std::vector<SymbolName> cj(c.begin(), c.end());
      SymbolName jname = vg.name(j);
      cj.push_back(jname);
      // if the derivative exists make sure the variable is coupled
      if (haveMaterialProperty<U, is_ad>(derivativePropertyName(base, cj)))
      {
        // kernels and BCs to not have the variable they are acting on in coupled_moose_vars
        bool is_missing = isNotObjectVariable(jname);
        for (unsigned int k = 0; k < ncoupled; ++k)
          if (this->_coupled_standard_moose_vars[k]->name() == jname)
          {
            is_missing = false;
            break;
          }
        if (is_missing)
          missing.push_back(jname);
      }
    }
  }
}
validateDerivativeMaterialPropertyBase()
template<class T > template<typename U , bool is_ad> void DerivativeMaterialInterface< T >::validateDerivativeMaterialPropertyBase (const std::string & base) inherited
Check if the material property base exists.
Print a warning if it doesn't. This is useful in materials that pull in only derivative properties, which are optional. If the base property name has a typo all derivatives will be set to zero without the user ever knowing.
Definition at line 537 of file DerivativeMaterialInterface.h.
{
  // resolve the input parameter name base to the actual material property name
  const MaterialPropertyName prop_name = this->template getParam<MaterialPropertyName>(base);
  // check if the material property does not exist on the blocks of the current object,
  // and check if it is not a plain number in the input file
  if (!haveMaterialProperty<U, is_ad>(prop_name) &&
      this->template defaultGenericMaterialProperty<U, is_ad>(prop_name) == 0)
    mooseWarning("The material property '",
                 prop_name,
                 "' does not exist. The kernel '",
                 this->name(),
                 "' only needs its derivatives, but this may indicate a typo in the input file.");
}
validateNonlinearCoupling()
template<class T > template<typename U , bool is_ad> void DerivativeMaterialInterface< T >::validateNonlinearCoupling (const MaterialPropertyName & base, const VariableName & c1 = "", const VariableName & c2 = "", const VariableName & c3 = "") inherited
Definition at line 526 of file DerivativeMaterialInterface.h.
{
  validateCoupling<U, is_ad>(base, buildVariableVector(c1, c2, c3), false);
}
validParams()
template<class T > InputParameters DerivativeKernelInterface< T >::validParams static
as partial template specialization is not allowed in C++ we have to implement this as a static method
Definition at line 42 of file DerivativeKernelInterface.h.
{
  InputParameters params = T::validParams();
  params.addDeprecatedParam<std::string>(
      "f_name",
      "Base name of the free energy function F defined in a DerivativeParsedMaterial",
      "Deprecated, use property_name");
  // TODO Make required once deprecation is handled, see #20535
  params.addParam<std::string>(
      "property_name", "Base name of the material property defined in a DerivativeParsedMaterial");
  return params;
}
Member Data Documentation
_dmi_fe_problem
template<class T > FEProblemBase& DerivativeMaterialInterface< T >::_dmi_fe_problem private inherited
Reference to FEProblemBase.
Definition at line 194 of file DerivativeMaterialInterface.h.
_F_name
template<class T > std::string DerivativeKernelInterface< T >::_F_name protected
Definition at line 29 of file DerivativeKernelInterface.h.
_nvar
template<class T > unsigned int DerivativeKernelInterface< T >::_nvar protected
Definition at line 28 of file DerivativeKernelInterface.h.
The documentation for this class was generated from the following file:
moose/framework/include/utils/DerivativeKernelInterface.h