Zapdos: QuadraturePointMarker Class Reference
QuadraturePointMarker Class Reference abstract
#include <QuadraturePointMarker.h>
Public Types
enum MarkerValue { DONT_MARK = -1 , COARSEN , DO_NOTHING , REFINE }
This mirrors the main refinement flag values in libMesh in Elem::RefinementState but adds "dont_mark".
Public Member Functions
QuadraturePointMarker (const InputParameters &parameters)
virtual void computeMarker ()
bool isActive () const
virtual void markerSetup ()
Is called before any element looping is started so any "global" computation can be done.
virtual const std::set< std::string > & getRequestedItems () override
Return a set containing the names of items requested by the object.
virtual const std::set< std::string > & getSuppliedItems () override
Return a set containing the names of items owned by the object.
virtual bool enabled () const
Return the enabled status of the object.
MooseApp & getMooseApp () const
Get the MooseApp this class is associated with.
const std::string & type () const
Get the type of this class.
virtual const std::string & name () const
Get the name of the class.
std::string typeAndName () const
Get the class's combined type and name; useful in error handling.
MooseObjectParameterName uniqueParameterName (const std::string &parameter_name) const
The unique parameter name of a valid parameter of this object for accessing parameter controls.
const InputParameters & parameters () const
Get the parameters of the object.
MooseObjectName uniqueName () const
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
template<typename T >
const T & getParam (const std::string &name) const
Retrieve a parameter for the object.
template<typename T1 , typename T2 >
std::vector< std::pair< T1, T2 > > getParam (const std::string &param1, const std::string &param2) const
Retrieve two parameters and provide pair of parameters for the object.
template<typename T >
const T & getRenamedParam (const std::string &old_name, const std::string &new_name) const
Retrieve a renamed parameter for the object.
template<typename T >
T getCheckedPointerParam (const std::string &name, const std::string &error_string="") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
bool isParamValid (const std::string &name) const
Test if the supplied parameter is valid.
bool isParamSetByUser (const std::string &nm) const
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
template<typename... Args>
void paramError (const std::string &param, Args... args) const
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramWarning (const std::string &param, Args... args) const
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramInfo (const std::string &param, Args... args) const
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
std::string objectErrorPrefix (const std::string &error_type) const
A descriptive prefix for errors for an object.
void connectControllableParams (const std::string &parameter, const std::string &object_type, const std::string &object_name, const std::string &object_parameter) const
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
template<typename... Args>
void mooseError (Args &&... args) const
Emits an error prefixed with object name and type.
template<typename... Args>
void mooseErrorNonPrefixed (Args &&... args) const
Emits an error without the prefixing included in mooseError().
template<typename... Args>
void mooseWarning (Args &&... args) const
Emits a warning prefixed with object name and type.
template<typename... Args>
void mooseWarningNonPrefixed (Args &&... args) const
Emits a warning without the prefixing included in mooseWarning().
template<typename... Args>
void mooseDeprecated (Args &&... args) const
template<typename... Args>
void mooseInfo (Args &&... args) const
std::string errorPrefix (const std::string &error_type) const
A descriptive prefix for errors for this object:
std::string getDataFileName (const std::string &param) const
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
std::string getDataFileNameByName (const std::string &name, const std::string *param=nullptr) const
Returns the path of a data file for a given relative file path.
const std::vector< SubdomainName > & blocks () const
Return the block names for this object.
unsigned int numBlocks () const
Return the number of blocks for this object.
virtual const std::set< SubdomainID > & blockIDs () const
Return the block subdomain ids for this object Note, if this is not block restricted, this function returns all mesh subdomain ids.
unsigned int blocksMaxDimension () const
Return the largest mesh dimension of the elements in the blocks for this object.
bool hasBlocks (const SubdomainName &name) const
Test if the supplied block name is valid for this object.
bool hasBlocks (const std::vector< SubdomainName > &names) const
Test if the supplied vector of block names are valid for this object.
bool hasBlocks (SubdomainID id) const
Test if the supplied block ids are valid for this object.
bool hasBlocks (const std::vector< SubdomainID > &ids) const
Test if the supplied vector block ids are valid for this object.
bool hasBlocks (const std::set< SubdomainID > &ids) const
Test if the supplied set of block ids are valid for this object.
bool isBlockSubset (const std::set< SubdomainID > &ids) const
Test if the class block ids are a subset of the supplied objects.
bool isBlockSubset (const std::vector< SubdomainID > &ids) const
Test if the class block ids are a subset of the supplied objects.
template<typename T , bool is_ad = false>
bool hasBlockMaterialProperty (const std::string &prop_name)
Check if a material property is valid for all blocks of this object.
const std::set< SubdomainID > & meshBlockIDs () const
Return all of the SubdomainIDs for the mesh.
virtual bool blockRestricted () const
Returns true if this object has been restricted to a block.
virtual void checkVariable (const MooseVariableFieldBase &variable) const
Helper for checking that the ids for this object are in agreement with the variables on the supplied variable.
virtual void initialSetup ()
Gets called at the beginning of the simulation before this object is asked to do its job.
virtual void timestepSetup ()
Gets called at the beginning of the timestep before this object is asked to do its job.
virtual void jacobianSetup ()
Gets called just before the Jacobian is computed and before this object is asked to do its job.
virtual void residualSetup ()
Gets called just before the residual is computed and before this object is asked to do its job.
virtual void subdomainSetup ()
Gets called when the subdomain changes (i.e.
virtual void customSetup (const ExecFlagType &)
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
const ExecFlagEnum & getExecuteOnEnum () const
Return the execute on MultiMooseEnum for this object.
const std::set< MooseVariableFieldBase * > & getMooseVariableDependencies () const
Retrieve the set of MooseVariableFieldBase that this object depends on.
template<typename DofObjectType >
std::set< MooseVariableFieldBase * > checkAllVariables (const DofObjectType &dof_object, const std::set< MooseVariableFieldBase * > &vars_to_omit={})
Check whether all of the variable dependencies have degree of freedom indices on the supplied degree of freedom object.
template<typename DofObjectType >
std::set< MooseVariableFieldBase * > checkVariables (const DofObjectType &dof_object, const std::set< MooseVariableFieldBase * > &vars_to_check)
Check whether all of the supplied variables have degree of freedom indices on the supplied degree of freedom object.
UserObjectName getUserObjectName (const std::string &param_name) const
template<class T >
const T & getUserObject (const std::string &param_name, bool is_dependency=true) const
Get an user object with a given parameter param_name.
template<class T >
const T & getUserObjectByName (const UserObjectName &object_name, bool is_dependency=true) const
Get an user object with the name object_name.
const UserObject & getUserObjectBase (const std::string &param_name, bool is_dependency=true) const
Get an user object with a given parameter param_name.
const UserObject & getUserObjectBaseByName (const UserObjectName &object_name, bool is_dependency=true) const
Get an user object with the name object_name.
bool isDefaultPostprocessorValue (const std::string &param_name, const unsigned int index=0) const
Determine whether or not the Postprocessor is a default value.
bool hasPostprocessor (const std::string &param_name, const unsigned int index=0) const
Determine if the Postprocessor data exists.
bool hasPostprocessorByName (const PostprocessorName &name) const
Determine if the Postprocessor data exists.
std::size_t coupledPostprocessors (const std::string &param_name) const
Returns number of Postprocessors coupled under parameter name.
const PostprocessorName & getPostprocessorName (const std::string &param_name, const unsigned int index=0) const
Get the name of a postprocessor.
virtual void meshChanged ()
Called on this object when the mesh changes.
void buildOutputHideVariableList (std::set< std::string > variable_names)
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
const std::set< OutputName > & getOutputs ()
Get the list of output objects that this class is restricted.
MooseVariableBase * mooseVariableBase () const
Get the variable that this object is using.
MooseVariableField< Real > & mooseVariableField ()
Return the MooseVariableField<T> object that this interface acts on.
MooseVariableFE< Real > * mooseVariable () const
MooseVariableFV< Real > * mooseVariableFV () const
template<typename T , bool is_ad>
const GenericMaterialProperty< T, is_ad > & getGenericMaterialProperty (const std::string &name, MaterialData &material_data, const unsigned int state=0)
Retrieve the generic property named "name" for the specified material_data at state state.
template<typename T >
const MaterialProperty< T > & getMaterialProperty (const std::string &name, MaterialData &material_data, const unsigned int state=0)
Retrieve the property named "name" for the specified material_data.
template<typename T >
const ADMaterialProperty< T > & getADMaterialProperty (const std::string &name, MaterialData &material_data)
Retrieve the AD property named "name" for the specified material_data.
template<typename T >
const MaterialProperty< T > & getMaterialPropertyOld (const std::string &name, MaterialData &material_data)
Retrieve the old property deduced from the name name for the specified material_data.
template<typename T >
const MaterialProperty< T > & getMaterialPropertyOlder (const std::string &name, MaterialData &material_data)
Retrieve the older property deduced from the name name for the specified material_data.
template<typename T , bool is_ad>
const GenericMaterialProperty< T, is_ad > & getGenericMaterialPropertyByName (const MaterialPropertyName &name, MaterialData &material_data, const unsigned int state)
Retrieve the generic property named "name" without any deduction for the specified material_data for state state.
template<typename T >
const MaterialProperty< T > & getMaterialPropertyByName (const MaterialPropertyName &name, MaterialData &material_data, const unsigned int state=0)
Retrieve the property named "name" without any deduction for the specified material_data.
template<typename T >
const ADMaterialProperty< T > & getADMaterialPropertyByName (const MaterialPropertyName &name, MaterialData &material_data)
Retrieve the AD property named "name" without any deduction for the specified \q material_data.
template<typename T >
const MaterialProperty< T > & getMaterialPropertyOldByName (const MaterialPropertyName &name, MaterialData &material_data)
Retrieve the old property named name without any deduction for the specified material_data.
template<typename T >
const MaterialProperty< T > & getMaterialPropertyOlderByName (const MaterialPropertyName &name, MaterialData &material_data)
Retrieve the older property named name without any deduction for the specified material_data.
template<typename T >
std::pair< const MaterialProperty< T > *, std::set< SubdomainID > > getBlockMaterialProperty (const MaterialPropertyName &name)
Retrieve pointer to a material property with the mesh blocks where it is defined The name required by this method is the name defined in the input file.
template<typename T , bool is_ad>
const GenericMaterialProperty< T, is_ad > & getGenericZeroMaterialProperty (const std::string &name)
Return a material property that is initialized to zero by default and does not need to (but can) be declared by another material.
template<typename T , bool is_ad>
const GenericMaterialProperty< T, is_ad > & getGenericZeroMaterialProperty ()
Return a constant zero anonymous material property.
template<typename T , bool is_ad>
const GenericMaterialProperty< T, is_ad > & getGenericZeroMaterialPropertyByName (const std::string &prop_name)
template<typename T , typename... Ts>
const MaterialProperty< T > & getZeroMaterialProperty (Ts... args)
for backwards compatibility
std::set< SubdomainID > getMaterialPropertyBlocks (const std::string &name)
Retrieve the block ids that the material property is defined.
std::vector< SubdomainName > getMaterialPropertyBlockNames (const std::string &name)
Retrieve the block names that the material property is defined.
std::set< BoundaryID > getMaterialPropertyBoundaryIDs (const std::string &name)
Retrieve the boundary ids that the material property is defined.
std::vector< BoundaryName > getMaterialPropertyBoundaryNames (const std::string &name)
Retrieve the boundary namess that the material property is defined.
void checkBlockAndBoundaryCompatibility (std::shared_ptr< MaterialBase > discrete)
Check if block and boundary restrictions of a given material are compatible with the current material.
std::unordered_map< SubdomainID, std::vector< MaterialBase * > > buildRequiredMaterials (bool allow_stateful=true)
get a map of MaterialBase pointers for all material objects that this object depends on for each block
void statefulPropertiesAllowed (bool)
Derived classes can declare whether or not they work with stateful material properties.
bool getMaterialPropertyCalled () const
Returns true if getMaterialProperty() has been called, false otherwise.
const std::set< unsigned int > & getMatPropDependencies () const
Retrieve the set of material properties that this object depends on.
virtual void resolveOptionalProperties ()
resolve all optional properties
bool hasUserObject (const std::string &param_name) const
template<class T >
bool hasUserObject (const std::string &param_name) const
bool hasUserObjectByName (const UserObjectName &object_name) const
template<class T >
bool hasUserObjectByName (const UserObjectName &object_name) const
const PostprocessorValue & getPostprocessorValue (const std::string &param_name, const unsigned int index=0) const
doco-normal-methods-begin Retrieve the value of a Postprocessor or one of it's old or older values
const PostprocessorValue & getPostprocessorValueOld (const std::string &param_name, const unsigned int index=0) const
const PostprocessorValue & getPostprocessorValueOlder (const std::string &param_name, const unsigned int index=0) const
virtual const PostprocessorValue & getPostprocessorValueByName (const PostprocessorName &name) const
Retrieve the value of the Postprocessor.
const PostprocessorValue & getPostprocessorValueOldByName (const PostprocessorName &name) const
const PostprocessorValue & getPostprocessorValueOlderByName (const PostprocessorName &name) const
template<typename T , bool is_ad>
const GenericMaterialProperty< T, is_ad > & getGenericMaterialProperty (const std::string &name, const unsigned int state=0)
Retrieve reference to material property or one of it's old or older values.
template<typename T >
const MaterialProperty< T > & getMaterialProperty (const std::string &name, const unsigned int state=0)
template<typename T >
const ADMaterialProperty< T > & getADMaterialProperty (const std::string &name)
template<typename T >
const MaterialProperty< T > & getMaterialPropertyOld (const std::string &name)
template<typename T >
const MaterialProperty< T > & getMaterialPropertyOlder (const std::string &name)
template<typename T , bool is_ad>
const GenericMaterialProperty< T, is_ad > & getGenericMaterialPropertyByName (const MaterialPropertyName &name, const unsigned int state=0)
Retrieve reference to material property or its old or older value The name required by this method is the name defined in the input file.
template<typename T >
const MaterialProperty< T > & getMaterialPropertyByName (const MaterialPropertyName &name, const unsigned int state=0)
template<typename T >
const ADMaterialProperty< T > & getADMaterialPropertyByName (const MaterialPropertyName &name)
template<typename T >
const MaterialProperty< T > & getMaterialPropertyOldByName (const MaterialPropertyName &name)
template<typename T >
const MaterialProperty< T > & getMaterialPropertyOlderByName (const MaterialPropertyName &name)
template<typename T , bool is_ad>
const GenericOptionalMaterialProperty< T, is_ad > & getGenericOptionalMaterialProperty (const std::string &name, const unsigned int state=0)
template<typename T >
const OptionalMaterialProperty< T > & getOptionalMaterialProperty (const std::string &name, const unsigned int state=0)
template<typename T >
const OptionalADMaterialProperty< T > & getOptionalADMaterialProperty (const std::string &name)
template<typename T >
const OptionalMaterialProperty< T > & getOptionalMaterialPropertyOld (const std::string &name)
template<typename T >
const OptionalMaterialProperty< T > & getOptionalMaterialPropertyOlder (const std::string &name)
MaterialBase & getMaterial (const std::string &name)
Return a MaterialBase reference - usable for computing directly.
MaterialBase & getMaterialByName (const std::string &name, bool no_warn=false)
template<typename T >
bool hasMaterialProperty (const std::string &name)
Check if the material property exists.
template<typename T >
bool hasMaterialPropertyByName (const std::string &name)
template<typename T >
bool hasADMaterialProperty (const std::string &name)
template<typename T >
bool hasADMaterialPropertyByName (const std::string &name)
template<typename T , bool is_ad>
bool hasGenericMaterialProperty (const std::string &name)
generic hasMaterialProperty helper
template<typename T , bool is_ad>
bool hasGenericMaterialPropertyByName (const std::string &name)
Static Public Member Functions
static InputParameters validParams ()
static MooseEnum markerStates ()
Helper function for getting the valid refinement flag states a marker can use as a MooseEnum.
template<typename T >
static void sort (typename std::vector< T > &vector)
Given a vector, sort using the getRequested/SuppliedItems sets.
template<typename T >
static void sortDFS (typename std::vector< T > &vector)
Given a vector, sort using the depth-first search.
template<typename T , typename T2 >
static void cyclicDependencyError (CyclicDependencyException< T2 > &e, const std::string &header)
A helper method for cyclic errors.
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Static Public Attributes
static constexpr PropertyValue::id_type default_property_id
The material property ID for a default (parsed from input) property.
static constexpr PropertyValue::id_type zero_property_id = PropertyValue::invalid_property_id - 2
The material property ID for a zero property.
Protected Member Functions
virtual MarkerValue computeElementMarker () override
virtual MarkerValue computeQpMarker ()=0
Override this to compute a marker value at each quadrature point.
ErrorVector & getErrorVector (std::string indicator)
Get an ErrorVector that will be filled up with values corresponding to the indicator passed in.
const MooseArray< Real > & getMarkerValue (std::string name)
This is used to get the values of other Markers.
virtual bool hasBlockMaterialPropertyHelper (const std::string &prop_name)
A helper method to allow the Material object to specialize the behavior of hasBlockMaterialProperty.
void initializeBlockRestrictable (const MooseObject *moose_object)
An initialization routine needed for dual constructors.
Moose::CoordinateSystemType getBlockCoordSystem ()
Check if the blocks this object operates on all have the same coordinate system, and if so return it.
void addMooseVariableDependency (MooseVariableFieldBase *var)
Call this function to add the passed in MooseVariableFieldBase as a variable that this object depends on.
void addMooseVariableDependency (const std::vector< MooseVariableFieldBase * > &vars)
virtual void addUserObjectDependencyHelper (const UserObject &) const
Helper for deriving classes to override to add dependencies when a UserObject is requested.
template<typename T , typename... Args>
T & declareRestartableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
ManagedValue< T > declareManagedRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declares a piece of "managed" restartable data and initialize it.
template<typename T , typename... Args>
const T & getRestartableData (const std::string &data_name) const
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
template<typename T , typename... Args>
T & declareRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
T & declareRecoverableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "recoverable" and initialize it.
template<typename T , typename... Args>
T & declareRestartableDataWithObjectName (const std::string &data_name, const std::string &object_name, Args &&... args)
Declare a piece of data as "restartable".
template<typename T , typename... Args>
T & declareRestartableDataWithObjectNameWithContext (const std::string &data_name, const std::string &object_name, void *context, Args &&... args)
Declare a piece of data as "restartable".
std::string restartableName (const std::string &data_name) const
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
virtual void addPostprocessorDependencyHelper (const PostprocessorName &) const
Helper for deriving classes to override to add dependencies when a Postprocessor is requested.
virtual const OutputTools< Real >::VariableValue & value ()
The value of the variable this object is operating on.
virtual const OutputTools< Real >::VariableValue & valueOld ()
The old value of the variable this object is operating on.
virtual const OutputTools< Real >::VariableValue & valueOlder ()
The older value of the variable this object is operating on.
virtual const OutputTools< Real >::VariableValue & dot ()
The time derivative of the variable this object is operating on.
virtual const OutputTools< Real >::VariableValue & dotDot ()
The second time derivative of the variable this object is operating on.
virtual const OutputTools< Real >::VariableValue & dotOld ()
The old time derivative of the variable this object is operating on.
virtual const OutputTools< Real >::VariableValue & dotDotOld ()
The old second time derivative of the variable this object is operating on.
virtual const VariableValue & dotDu ()
The derivative of the time derivative of the variable this object is operating on with respect to this variable's coefficients.
virtual const VariableValue & dotDotDu ()
The derivative of the second time derivative of the variable this object is operating on with respect to this variable's coefficients.
virtual const OutputTools< Real >::VariableGradient & gradient ()
The gradient of the variable this object is operating on.
virtual const OutputTools< Real >::VariableGradient & gradientOld ()
The old gradient of the variable this object is operating on.
virtual const OutputTools< Real >::VariableGradient & gradientOlder ()
The older gradient of the variable this object is operating on.
virtual const OutputTools< Real >::VariableSecond & second ()
The second derivative of the variable this object is operating on.
virtual const OutputTools< Real >::VariableSecond & secondOld ()
The old second derivative of the variable this object is operating on.
virtual const OutputTools< Real >::VariableSecond & secondOlder ()
The older second derivative of the variable this object is operating on.
virtual const OutputTools< Real >::VariableTestSecond & secondTest ()
The second derivative of the test function.
virtual const OutputTools< Real >::VariableTestSecond & secondTestFace ()
The second derivative of the test function on the current face.
virtual const OutputTools< Real >::VariablePhiSecond & secondPhi ()
The second derivative of the trial function.
virtual const OutputTools< Real >::VariablePhiSecond & secondPhiFace ()
The second derivative of the trial function on the current face.
void checkMaterialProperty (const std::string &name, const unsigned int state)
A helper method for checking material properties This method was required to avoid a compiler problem with the template getMaterialProperty method.
void markMatPropRequested (const std::string &)
A proxy method for _mi_feproblem.markMatPropRequested(name)
MaterialPropertyName getMaterialPropertyName (const std::string &name) const
void checkExecutionStage ()
Check and throw an error if the execution has progressed past the construction stage.
template<typename T , bool is_ad>
const GenericMaterialProperty< T, is_ad > * defaultGenericMaterialProperty (const std::string &name)
template<typename T >
const MaterialProperty< T > * defaultMaterialProperty (const std::string &name)
template<typename T >
const ADMaterialProperty< T > * defaultADMaterialProperty (const std::string &name)
Protected Attributes
const VariableValue & _u
Holds the solution at current quadrature points.
const QBase *const & _qrule
The quadrature rule for the system.
const MooseArray< Point > & _q_point
Position of the current quadrature point.
unsigned int _qp
The current quadrature point.
MarkerValue _third_state
The behavior to use when "in-between" other states (what to do on the fringe)
SubProblem & _subproblem
FEProblemBase & _fe_problem
Adaptivity & _adaptivity
SystemBase & _sys
THREAD_ID _tid
Assembly & _assembly
MooseVariable & _field_var
const Elem *const & _current_elem
MooseMesh & _mesh
std::set< std::string > _depend
Depend Markers.
std::set< std::string > _supplied
const bool & _enabled
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
MooseApp & _app
The MOOSE application this is associated with.
const std::string & _type
The type of this class.
const std::string & _name
The name of this class, reference to value stored in InputParameters.
const InputParameters & _pars
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Factory & _factory
The Factory associated with the MooseApp.
ActionFactory & _action_factory
Builds Actions.
const MaterialData * _blk_material_data
Pointer to the MaterialData class for this object.
const ExecFlagEnum & _execute_enum
Execute settings for this object.
const ExecFlagType & _current_execute_flag
Reference to FEProblemBase.
MooseApp & _restartable_app
Reference to the application.
const std::string _restartable_system_name
The system name this object is in.
const THREAD_ID _restartable_tid
The thread ID for this object.
const bool _restartable_read_only
Flag for toggling read only status (see ReporterData)
FEProblemBase & _mci_feproblem
Reference to FEProblemBase instance.
bool _nodal
Whether or not this object is acting only at nodes.
MooseVariableBase * _var
The variable this object is acting on.
MooseVariableFE< Real > * _variable
MooseVariableFV< Real > * _fv_variable
Assembly * _mvi_assembly
const InputParameters & _mi_params
Parameters of the object with this interface.
const std::string _mi_name
The name of the object that this interface belongs to.
const MooseObjectName _mi_moose_object_name
The "complete" name of the object that this interface belongs for material property output.
FEProblemBase & _mi_feproblem
Reference to the FEProblemBase class.
SubProblem & _mi_subproblem
Reference to the subproblem.
const THREAD_ID _mi_tid
Current threaded it.
const Moose::MaterialDataType _material_data_type
The type of data.
MaterialData & _material_data
The material data class that stores properties.
bool _stateful_allowed
True by default.
bool _get_material_property_called
Initialized to false.
std::vector< std::unique_ptr< PropertyValue > > _default_properties
Storage vector for default properties.
std::set< unsigned int > _material_property_dependencies
The set of material properties (as given by their IDs) that this object depends on.
const MaterialPropertyName _get_suffix
const bool _use_interpolated_state
Use the interpolated state set up through the ProjectedStatefulMaterialStorageAction.
Static Protected Attributes
static const std::string _interpolated_old = "_interpolated_old"
name suffixes for interpolated old and older properties
static const std::string _interpolated_older = "_interpolated_older"
Private Member Functions
template<typename... Args>
std::string paramErrorMsg (const std::string &param, Args... args) const
template<class T >
const T & castUserObject (const UserObject &uo_base, const std::string &param_name="") const
Internal helper that casts the UserObject uo_base to the reqested type.
const std::string & userObjectType (const UserObject &uo) const
Gets a UserObject's type; avoids including UserObject.h in the UserObjectInterface.
const std::string & userObjectName (const UserObject &uo) const
Gets a UserObject's name; avoids including UserObject.h in the UserObjectInterface.
RestartableDataValue & registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const
Helper function for actually registering the restartable data.
void registerRestartableNameWithFilterOnApp (const std::string &name, Moose::RESTARTABLE_FILTER filter)
Helper function for actually registering the restartable data.
template<typename T , typename... Args>
RestartableData< T > & declareRestartableDataHelper (const std::string &data_name, void *context, Args &&... args) const
Helper function for declaring restartable data.
const PostprocessorName & getPostprocessorNameInternal (const std::string &param_name, const unsigned int index, const bool allow_default_value=true) const
Internal method for getting the PostprocessorName associated with a paremeter.
bool isDefaultPostprocessorValueByName (const PostprocessorName &name) const
PostprocessorValue getDefaultPostprocessorValueByName (const PostprocessorName &name) const
void checkParam (const std::string &param_name, const unsigned int index=std::numeric_limits< unsigned int >::max()) const
Checks the parameters relating to a Postprocessor.
bool postprocessorsAdded () const
Moose::MaterialDataType getMaterialDataType (const std::set< BoundaryID > &boundary_ids) const
unsigned int getMaxQps () const
void addConsumedPropertyName (const MooseObjectName &obj_name, const std::string &prop_name)
const PostprocessorValue & getPostprocessorValueInternal (const std::string &param_name, unsigned int index, std::size_t t_index) const
Internal methods for getting Postprocessor values.
const PostprocessorValue & getPostprocessorValueByNameInternal (const PostprocessorName &name, std::size_t t_index) const
Private Attributes
const MooseBase *const _moose_base
The MooseBase object that inherits this class.
const MooseObject & _parent
std::set< SubdomainID > _blk_ids
Set of block ids supplied by the user via the input file (for error checking)
std::vector< SubdomainID > _vec_ids
Vector of block ids supplied by the user via the input file (for error reporting)
std::vector< SubdomainName > _blocks
Vector the block names supplied by the user via the input file.
const bool _blk_dual_restrictable
Flag for allowing dual restriction.
FEProblemBase * _blk_feproblem
Pointer to FEProblemBase.
MooseMesh * _blk_mesh
Pointer to Mesh.
const std::set< BoundaryID > _empty_boundary_ids
An empty set for referencing when boundary_ids is not included.
const std::set< BoundaryID > & _boundary_ids
Reference to the boundary_ids, defaults to an empty set if not provided.
THREAD_ID _blk_tid
Thread id for this object.
const std::string & _blk_name
Name of the object.
unsigned int _blk_dim
Largest mesh dimension of the elements in the blocks for this object.
ExecFlagEnum _empty_execute_enum
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
std::set< MooseVariableFieldBase * > _moose_variable_dependencies
std::vector< libMesh::dof_id_type > _dof_indices
A container for holding dof indices in order to avoid constant memory reallocation.
const MooseObject & _uoi_moose_object
Moose object using the interface.
const FEProblemBase & _uoi_feproblem
Reference to the FEProblemBase instance.
const THREAD_ID _uoi_tid
Thread ID.
const RestartableDataMapName _metaname
Restartable metadata name.
std::string _restartable_name
The name of the object.
const MooseObject & _ppi_moose_object
The MooseObject that uses this interface.
const InputParameters & _ppi_params
PostprocessorInterface Parameters.
const FEProblemBase & _ppi_feproblem
Reference the the FEProblemBase class.
std::map< PostprocessorName, std::unique_ptr< PostprocessorValue > > _default_values
Holds the default postprocessor values that are requested (key is PostprocessorName)
MooseApp & _oi_moose_app
Reference the the MooseApp; neede for access to the OutputWarehouse.
OutputWarehouse & _oi_output_warehouse
Reference to the OutputWarehouse for populating the Output object hide lists.
std::set< OutputName > _oi_outputs
The set of Output object names listed in the 'outputs' parameter.
const MooseObject & _moose_object
const MooseObject & _mi_moose_object
The MooseObject creating the MaterialPropertyInterface.
const bool _mi_boundary_restricted
BoundaryRestricted flag.
const std::set< SubdomainID > & _mi_block_ids
Storage for the block ids created by BlockRestrictable.
const std::set< BoundaryID > & _mi_boundary_ids
Storage for the boundary ids created by BoundaryRestrictable.
std::vector< std::unique_ptr< OptionalMaterialPropertyProxyBase< MaterialPropertyInterface > > > _optional_property_proxies
optional material properties
Detailed Description
Definition at line 16 of file QuadraturePointMarker.h.
Member Enumeration Documentation
MarkerValue
enum Marker::MarkerValue inherited
This mirrors the main refinement flag values in libMesh in Elem::RefinementState but adds "dont_mark".
Enumerator
DONT_MARK
COARSEN
DO_NOTHING
REFINE
Definition at line 53 of file Marker.h.
  {
    DONT_MARK = -1,
    COARSEN,
    DO_NOTHING,
    REFINE
  };
Constructor & Destructor Documentation
QuadraturePointMarker()
QuadraturePointMarker::QuadraturePointMarker (const InputParameters & parameters)
Definition at line 39 of file QuadraturePointMarker.C.
  : Marker(parameters),
    MooseVariableInterface<Real>(this,
                                 false,
                                 "variable",
                                 Moose::VarKindType::VAR_ANY,
                                 Moose::VarFieldType::VAR_FIELD_STANDARD),
    MaterialPropertyInterface(this, blockIDs(), Moose::EMPTY_BOUNDARY_IDS),
    _u(mooseVariableField().sln()),
    _qrule(_assembly.qRule()),
    _q_point(_assembly.qPoints()),
    _qp(0),
    _third_state(getParam<MooseEnum>("third_state").getEnum<MarkerValue>())
{
  addMooseVariableDependency(&mooseVariableField());
}
Member Function Documentation
addConsumedPropertyName()
void MaterialPropertyInterface::addConsumedPropertyName (const MooseObjectName & obj_name, const std::string & prop_name) private inherited
Definition at line 111 of file MaterialPropertyInterface.C.
{
  return _mi_feproblem.addConsumedPropertyName(obj_name, prop_name);
}
Referenced by MaterialPropertyInterface::getBlockMaterialProperty(), and MaterialPropertyInterface::getGenericMaterialPropertyByName().
addMooseVariableDependency() [1/2]
void MooseVariableDependencyInterface::addMooseVariableDependency (const std::vector< MooseVariableFieldBase * > & vars) inline protected inherited
Definition at line 77 of file MooseVariableDependencyInterface.h.
  {
    _moose_variable_dependencies.insert(vars.begin(), vars.end());
  }
addMooseVariableDependency() [2/2]
void MooseVariableDependencyInterface::addMooseVariableDependency (MooseVariableFieldBase * var) inline protected inherited
Call this function to add the passed in MooseVariableFieldBase as a variable that this object depends on.
Definition at line 73 of file MooseVariableDependencyInterface.h.
  {
    _moose_variable_dependencies.insert(var);
  }
Referenced by ADDGKernel::ADDGKernel(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADInterfaceKernelTempl< T >::ADInterfaceKernelTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayNodalBC::ArrayNodalBC(), AuxNodalScalarKernel::AuxNodalScalarKernel(), CoupleableMooseVariableDependencyIntermediateInterface::CoupleableMooseVariableDependencyIntermediateInterface(), DGKernel::DGKernel(), DiracKernelTempl< T >::DiracKernelTempl(), DomainUserObject::DomainUserObject(), ElemElemConstraint::ElemElemConstraint(), ElementIndicator::ElementIndicator(), ElementIntegralArrayVariablePostprocessor::ElementIntegralArrayVariablePostprocessor(), ElementIntegralVariablePostprocessor::ElementIntegralVariablePostprocessor(), ElementIntegralVariableUserObject::ElementIntegralVariableUserObject(), ElementUserObject::ElementUserObject(), ElementVariablePostprocessor::ElementVariablePostprocessor(), FVBoundaryCondition::FVBoundaryCondition(), FVInterfaceKernel::FVInterfaceKernel(), IntegratedBC::IntegratedBC(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceMaterial::InterfaceMaterial(), InterfaceUserObjectBase::InterfaceUserObjectBase(), InternalSideIndicator::InternalSideIndicator(), InternalSideIntegralVariablePostprocessor::InternalSideIntegralVariablePostprocessor(), InternalSideUserObject::InternalSideUserObject(), Kernel::Kernel(), Marker::Marker(), Material::Material(), MortarConstraintBase::MortarConstraintBase(), NeighborCoupleableMooseVariableDependencyIntermediateInterface::NeighborCoupleableMooseVariableDependencyIntermediateInterface(), NodalBC::NodalBC(), NodalConstraint::NodalConstraint(), NodalKernel::NodalKernel(), NodalScalarKernel::NodalScalarKernel(), NodalUserObject::NodalUserObject(), NodeElemConstraint::NodeElemConstraint(), NodeFaceConstraint::NodeFaceConstraint(), PointVariableSamplerBase::PointVariableSamplerBase(), QuadraturePointMarker(), SideIntegralVariablePostprocessor::SideIntegralVariablePostprocessor(), SideIntegralVariableUserObject::SideIntegralVariableUserObject(), SideUserObject::SideUserObject(), SideVariablePostprocessor::SideVariablePostprocessor(), VectorIntegratedBC::VectorIntegratedBC(), VectorKernel::VectorKernel(), and VectorNodalBC::VectorNodalBC().
addPostprocessorDependencyHelper()
virtual void PostprocessorInterface::addPostprocessorDependencyHelper (const PostprocessorName &) const inline protected virtual inherited
Helper for deriving classes to override to add dependencies when a Postprocessor is requested.
Reimplemented in UserObject, AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, AuxKernelTempl< RealVectorValue >, and InitialConditionBase.
Definition at line 141 of file PostprocessorInterface.h.
{}
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal().
addUserObjectDependencyHelper()
virtual void UserObjectInterface::addUserObjectDependencyHelper (const UserObject &) const inline protected virtual inherited
Helper for deriving classes to override to add dependencies when a UserObject is requested.
Reimplemented in UserObject, AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, AuxKernelTempl< RealVectorValue >, and InitialConditionBase.
Definition at line 108 of file UserObjectInterface.h.
{}
Referenced by UserObjectInterface::getUserObjectBaseByName().
blockIDs()
const std::set< SubdomainID > & BlockRestrictable::blockIDs () const virtual inherited
Return the block subdomain ids for this object Note, if this is not block restricted, this function returns all mesh subdomain ids.
Returns
a set of SubdomainIDs that are valid for this object
Definition at line 190 of file BlockRestrictable.C.
{
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return _blk_mesh->meshSubdomains();
  else
    return _blk_ids;
}
Referenced by FunctorMaterial::addFunctorProperty(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), NodalPatchRecoveryAuxBase::blockRestrictElements(), MooseMesh::cacheFaceInfoVariableOwnership(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), BlockRestrictable::getBlockCoordSystem(), MaterialBase::getGenericZeroMaterialPropertyByName(), BlockRestrictable::hasBlockMaterialPropertyHelper(), SubdomainsDivision::initialize(), ElementCentroidPositions::initialize(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), MaterialBase::registerPropName(), and FVPointValueConstraint::setMyElem().
blockRestricted()
bool BlockRestrictable::blockRestricted () const virtual inherited
Returns true if this object has been restricted to a block.
See also
MooseObject
Definition at line 178 of file BlockRestrictable.C.
{
  return _blk_ids.find(Moose::ANY_BLOCK_ID) == _blk_ids.end();
}
Referenced by NodalPatchRecoveryAuxBase::blockRestrictElements(), BlockRestrictable::checkVariable(), SubdomainsDivision::divisionIndex(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), SubdomainsDivision::initialize(), ElementCentroidPositions::initialize(), BlockRestrictable::initializeBlockRestrictable(), SolutionIC::initialSetup(), and FVPointValueConstraint::setMyElem().
blocks()
const std::vector< SubdomainName > & BlockRestrictable::blocks () const inherited
Return the block names for this object.
Note, if the 'blocks' input parameter was not utilized this will return an empty vector.
Returns
vector of SubdomainNames that are valid for this object
Definition at line 184 of file BlockRestrictable.C.
{
  return _blocks;
}
Referenced by MaterialOutputAction::getParams(), BlockAverageValue::initialize(), SubdomainsDivision::initialize(), and SolutionIC::initialSetup().
blocksMaxDimension()
unsigned int BlockRestrictable::blocksMaxDimension () const inherited
Return the largest mesh dimension of the elements in the blocks for this object.
Definition at line 360 of file BlockRestrictable.C.
{
  mooseAssert(_blk_dim != libMesh::invalid_uint, "Block restriction not initialized");
  return _blk_dim;
}
buildOutputHideVariableList()
void OutputInterface::buildOutputHideVariableList (std::set< std::string > variable_names) inherited
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
Parameters
variable_names A set of variables for which the 'outputs' parameter controls
By default this is called by the constructor and passes the block name as the list of variables. This needs to be called explicitly if the build_list flag is set to False in the constructor. The latter cases is needed by the Material object to work correctly with the automatic material output capability.
Definition at line 61 of file OutputInterface.C.
{
  // Set of available names
  const std::set<OutputName> & avail = _oi_output_warehouse.getOutputNames();
  // Check for 'none'; hide variables on all outputs
  if (_oi_outputs.find("none") != _oi_outputs.end())
    for (const auto & name : avail)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  // Check for empty and 'all' in 'outputs' parameter; do not perform any variable restrictions in
  // these cases
  else if (_oi_outputs.empty() || _oi_outputs.find("all") != _oi_outputs.end())
    return;
  // Limit the variable output to Output objects listed
  else
  {
    // Create a list of outputs where the variable should be hidden
    std::set<OutputName> hide;
    std::set_difference(avail.begin(),
                        avail.end(),
                        _oi_outputs.begin(),
                        _oi_outputs.end(),
                        std::inserter(hide, hide.begin()));
    // If 'outputs' is specified add the object name to the list of items to hide
    for (const auto & name : hide)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  }
}
Referenced by ReporterTransferInterface::hideVariableHelper(), and OutputInterface::OutputInterface().
buildRequiredMaterials()
std::unordered_map< SubdomainID, std::vector< MaterialBase * > > MaterialPropertyInterface::buildRequiredMaterials (bool allow_stateful = true) inherited
get a map of MaterialBase pointers for all material objects that this object depends on for each block
Definition at line 205 of file MaterialPropertyInterface.C.
{
  std::unordered_map<SubdomainID, std::vector<MaterialBase *>> required_mats;
  const auto & mwh = _mi_feproblem.getMaterialWarehouse();
  for (const auto id : _mi_block_ids)
  {
    const auto & mats = mwh[_material_data_type].getActiveBlockObjects(id, _mi_tid);
    std::array<const MaterialPropertyInterface *, 1> consumers = {{this}};
    const auto block_required =
        MaterialBase::buildRequiredMaterials(consumers, mats, allow_stateful);
    required_mats[id].insert(
        required_mats[id].begin(), block_required.begin(), block_required.end());
  }
  return required_mats;
}
castUserObject()
template<class T > const T & UserObjectInterface::castUserObject (const UserObject & uo_base, const std::string & param_name = "") const private inherited
Internal helper that casts the UserObject uo_base to the reqested type.
Exits with a useful error if the casting failed. If the parameter param_name is provided and is valid, a paramError() will be used instead.
Definition at line 136 of file UserObjectInterface.h.
{
  const T * uo = dynamic_cast<const T *>(&uo_base);
  if (!uo)
  {
    std::stringstream oss;
    oss << "The provided UserObject \"" << userObjectName(uo_base) << "\" of type "
        << userObjectType(uo_base)
        << " is not derived from the required type.\n\nThe UserObject must derive from "
        << MooseUtils::prettyCppType<T>() << ".";
    if (_uoi_moose_object.parameters().isParamValid(param_name))
      _uoi_moose_object.paramError(param_name, oss.str());
    else
      _uoi_moose_object.mooseError(oss.str());
  }
  return *uo;
}
checkAllVariables()
template<typename DofObjectType > std::set< MooseVariableFieldBase * > MooseVariableDependencyInterface::checkAllVariables (const DofObjectType & dof_object, const std::set< MooseVariableFieldBase * > & vars_to_omit = {}) inherited
Check whether all of the variable dependencies have degree of freedom indices on the supplied degree of freedom object.
Parameters
dof_object The degree of freedom object (an element or node) that we want to check for existence of variable degrees of freedom on
vars_to_omit Variables that we can omit from checking
Returns
Any variables that do not have degrees of freedom on the supplied degree of freedom object
Definition at line 91 of file MooseVariableDependencyInterface.h.
{
  if (vars_to_omit.empty())
    return checkVariables(dof_object, _moose_variable_dependencies);
  std::set<MooseVariableFieldBase *> vars_to_check;
  std::set_difference(_moose_variable_dependencies.begin(),
                      _moose_variable_dependencies.end(),
                      vars_to_omit.begin(),
                      vars_to_omit.end(),
                      std::inserter(vars_to_check, vars_to_check.begin()));
  return checkVariables(dof_object, vars_to_check);
}
checkBlockAndBoundaryCompatibility()
void MaterialPropertyInterface::checkBlockAndBoundaryCompatibility (std::shared_ptr< MaterialBase > discrete) inherited
Check if block and boundary restrictions of a given material are compatible with the current material.
Error out otherwise.
Definition at line 147 of file MaterialPropertyInterface.C.
{
  // Check block compatibility
  if (!discrete->hasBlocks(_mi_block_ids))
  {
    std::ostringstream oss;
    oss << "Incompatible material and object blocks:";
    oss << "\n    " << paramErrorPrefix(discrete->parameters(), "block")
        << " material defined on blocks ";
    for (const auto & sbd_id : discrete->blockIDs())
      oss << sbd_id << ", ";
    oss << "\n    " << paramErrorPrefix(_mi_params, "block") << " object needs material on blocks ";
    for (const auto & block_id : _mi_block_ids)
      oss << block_id << ", ";
    mooseError(oss.str());
  }
  // Check boundary compatibility
  if (!discrete->hasBoundary(_mi_boundary_ids))
  {
    std::ostringstream oss;
    oss << "Incompatible material and object boundaries:";
    oss << "\n    " << paramErrorPrefix(discrete->parameters(), "boundary")
        << " material defined on boundaries ";
    for (const auto & bnd_id : discrete->boundaryIDs())
      oss << bnd_id << ", ";
    oss << "\n    " << paramErrorPrefix(_mi_params, "boundary")
        << " object needs material on boundaries ";
    for (const auto & bnd_id : _mi_boundary_ids)
      oss << bnd_id << ", ";
    mooseError(oss.str());
  }
}
Referenced by MaterialPropertyInterface::getMaterialByName().
checkExecutionStage()
void MaterialPropertyInterface::checkExecutionStage () protected inherited
Check and throw an error if the execution has progressed past the construction stage.
Definition at line 222 of file MaterialPropertyInterface.C.
{
  if (_mi_feproblem.startedInitialSetup())
    mooseError("Material properties must be retrieved during object construction. This is a code "
               "problem.");
}
Referenced by MaterialPropertyInterface::getGenericMaterialPropertyByName().
checkMaterialProperty()
void MaterialPropertyInterface::checkMaterialProperty (const std::string & name, const unsigned int state) protected inherited
A helper method for checking material properties This method was required to avoid a compiler problem with the template getMaterialProperty method.
Definition at line 118 of file MaterialPropertyInterface.C.
{
  if (state == 0)
  {
    // If the material property is boundary restrictable, add to the list of materials to check
    if (_mi_boundary_restricted)
      for (const auto & bnd_id : _mi_boundary_ids)
        _mi_feproblem.storeBoundaryDelayedCheckMatProp(_mi_name, bnd_id, name);
    // The default is to assume block restrictions
    else
      for (const auto & blk_ids : _mi_block_ids)
        _mi_feproblem.storeSubdomainDelayedCheckMatProp(_mi_name, blk_ids, name);
  }
}
Referenced by MaterialPropertyInterface::getGenericMaterialPropertyByName().
checkParam()
void PostprocessorInterface::checkParam (const std::string & param_name, const unsigned int index = std::numeric_limits<unsigned int>::max()) const private inherited
Checks the parameters relating to a Postprocessor.
If index is not set, index checking is not performed.
Definition at line 139 of file PostprocessorInterface.C.
{
  const bool check_index = index != std::numeric_limits<unsigned int>::max();
  if (!_ppi_params.isParamValid(param_name))
    _ppi_moose_object.mooseError(
        "When getting a Postprocessor, failed to get a parameter with the name \"",
        param_name,
        "\".",
        "\n\nKnown parameters:\n",
        _ppi_moose_object.parameters());
  if (_ppi_params.isType<PostprocessorName>(param_name))
  {
    if (check_index && index > 0)
      _ppi_moose_object.paramError(param_name,
                                   "A Postprocessor was requested with index ",
                                   index,
                                   " but a single Postprocessor is coupled.");
  }
  else if (_ppi_params.isType<std::vector<PostprocessorName>>(param_name))
  {
    const auto & names = _ppi_params.get<std::vector<PostprocessorName>>(param_name);
    if (check_index && names.size() <= index)
      _ppi_moose_object.paramError(param_name,
                                   "A Postprocessor was requested with index ",
                                   index,
                                   " but only ",
                                   names.size(),
                                   " Postprocessors are coupled.");
  }
  else
  {
    _ppi_moose_object.mooseError(
        "Supplied parameter with name \"",
        param_name,
        "\" of type \"",
        _ppi_params.type(param_name),
        "\" is not an expected type for getting a Postprocessor.\n\n",
        "Allowed types are \"PostprocessorName\" and \"std::vector<PostprocessorName>\".");
  }
}
Referenced by PostprocessorInterface::coupledPostprocessors(), and PostprocessorInterface::getPostprocessorNameInternal().
checkVariable()
void BlockRestrictable::checkVariable (const MooseVariableFieldBase & variable) const virtual inherited
Helper for checking that the ids for this object are in agreement with the variables on the supplied variable.
Parameters
variable The variable to check against.
Reimplemented in DomainUserObject.
Definition at line 333 of file BlockRestrictable.C.
{
  // a variable defined on all internal sides does not need this check because
  // it can be coupled with other variables in DG kernels
  if (variable.activeSubdomains().count(Moose::INTERNAL_SIDE_LOWERD_ID) > 0)
    return;
  if (!isBlockSubset(variable.activeSubdomains()))
  {
    std::string var_ids = Moose::stringify(variable.activeSubdomains(), ", ");
    std::string obj_ids = Moose::stringify(blockRestricted() ? _blk_ids : meshBlockIDs(), ", ");
    mooseError("The 'block' parameter of the object '",
               _blk_name,
               "' must be a subset of the 'block' parameter of the variable '",
               variable.name(),
               "':\n    Object '",
               _blk_name,
               "': ",
               obj_ids,
               "\n    Variable '",
               variable.name(),
               "': ",
               var_ids);
  }
}
Referenced by DomainUserObject::checkVariable().
checkVariables()
template<typename DofObjectType > template std::set< MooseVariableFieldBase * > MooseVariableDependencyInterface::checkVariables (const DofObjectType & dof_object, const std::set< MooseVariableFieldBase * > & vars_to_check) inherited
Check whether all of the supplied variables have degree of freedom indices on the supplied degree of freedom object.
Parameters
dof_object The degree of freedom object (an element or node) that we want to check for existence of variable degrees of freedom on
vars_to_check the variables to check
Returns
Any variables that do not have degrees of freedom on the supplied degree of freedom object
Definition at line 25 of file MooseVariableDependencyInterface.C.
{
  std::set<MooseVariableFieldBase *> vars_without_indices;
  for (auto * const var : vars_to_check)
  {
    var->sys().dofMap().dof_indices(&dof_object, _dof_indices, var->number());
    if (_dof_indices.empty())
      vars_without_indices.insert(var);
  }
  return vars_without_indices;
}
Referenced by MooseVariableDependencyInterface::checkAllVariables().
computeElementMarker()
Marker::MarkerValue QuadraturePointMarker::computeElementMarker () override protected virtual
Implements Marker.
Definition at line 57 of file QuadraturePointMarker.C.
{
  MarkerValue current_mark = DONT_MARK;
  for (_qp = 0; _qp < _qrule->n_points(); _qp++)
  {
    MarkerValue new_mark = computeQpMarker();
    current_mark = std::max(current_mark, new_mark);
  }
  return current_mark;
}
computeMarker()
void Marker::computeMarker () virtual inherited
Definition at line 70 of file Marker.C.
{
  int mark = computeElementMarker();
  _field_var.setNodalValue(mark);
}
computeQpMarker()
virtual MarkerValue QuadraturePointMarker::computeQpMarker () protected pure virtual
Override this to compute a marker value at each quadrature point.
The ultimate value for the element will be taken as the maximum (most conservative) value for all quadrature points on the element.
Returns
The MarkerValue at one quadrature point.
Implemented in ValueRangeMarker, and ValueThresholdMarker.
Referenced by computeElementMarker().
connectControllableParams()
void MooseBaseParameterInterface::connectControllableParams (const std::string & parameter, const std::string & object_type, const std::string & object_name, const std::string & object_parameter) const inherited
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
Parameters
parameter Name of the controllable parameter of this action
object_type Type of the object added by this action.
object_name Name of the object added by this action.
object_parameter Name of the parameter of the object.
Definition at line 34 of file MooseBaseParameterInterface.C.
{
  MooseObjectParameterName primary_name(uniqueName(), parameter);
  const auto base_type = _factory.getValidParams(object_type).get<std::string>("_moose_base");
  MooseObjectParameterName secondary_name(base_type, object_name, object_parameter);
  _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
      primary_name, secondary_name);
  const auto & tags = _pars.get<std::vector<std::string>>("control_tags");
  for (const auto & tag : tags)
  {
    if (!tag.empty())
    {
      MooseObjectParameterName tagged_name(tag, _moose_base->name(), parameter);
      _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
          tagged_name, secondary_name);
    }
  }
}
coupledPostprocessors()
std::size_t PostprocessorInterface::coupledPostprocessors (const std::string & param_name) const inherited
Returns number of Postprocessors coupled under parameter name.
Parameters
param_name The name of the Postprocessor parameter
Returns
Number of coupled post-processors, 1 if it's a single
Definition at line 129 of file PostprocessorInterface.C.
{
  checkParam(param_name);
  if (_ppi_params.isType<PostprocessorName>(param_name))
    return 1;
  return _ppi_params.get<std::vector<PostprocessorName>>(param_name).size();
}
Referenced by FunctionValuePostprocessor::FunctionValuePostprocessor().
customSetup()
virtual void SetupInterface::customSetup (const ExecFlagType &) inline virtual inherited
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
Reimplemented in Function.
Definition at line 61 of file SetupInterface.h.
{}
cyclicDependencyError()
template<typename T , typename T2 > void DependencyResolverInterface::cyclicDependencyError (CyclicDependencyException< T2 > & e, const std::string & header) static inherited
A helper method for cyclic errors.
Definition at line 118 of file DependencyResolverInterface.h.
{
  std::ostringstream oss;
  oss << header << ":\n";
  const auto cycle = e.getCyclicDependencies();
  std::vector<std::string> names(cycle.size());
  for (const auto i : index_range(cycle))
    names[i] = static_cast<T>(cycle[i])->name();
  oss << MooseUtils::join(names, " <- ");
  mooseError(oss.str());
}
declareManagedRestartableDataWithContext()
template<typename T , typename... Args> Restartable::ManagedValue< T > Restartable::declareManagedRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declares a piece of "managed" restartable data and initialize it.
Here, "managed" restartable data means that the caller can destruct this data upon destruction of the return value of this method. Therefore, this ManagedValue<T> wrapper should survive after the final calls to dataStore() for it. That is... at the very end.
This is needed for objects whose destruction ordering is important, and enables natural c++ destruction in reverse construction order of the object that declares it.
See delcareRestartableData and declareRestartableDataWithContext for more information.
Definition at line 276 of file Restartable.h.
{
  auto & data_ptr =
      declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...);
  return Restartable::ManagedValue<T>(data_ptr);
}
declareRecoverableData()
template<typename T , typename... Args> T & Restartable::declareRecoverableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "recoverable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
Note - this data will NOT be restored on Restart!
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 351 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  registerRestartableNameWithFilterOnApp(full_name, Moose::RESTARTABLE_FILTER::RECOVERABLE);
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableData()
template<typename T , typename... Args> T & Restartable::declareRestartableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 269 of file Restartable.h.
{
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataHelper()
template<typename T , typename... Args> RestartableData< T > & Restartable::declareRestartableDataHelper (const std::string & data_name, void * context, Args &&... args) const private inherited
Helper function for declaring restartable data.
We use this function to reduce code duplication when returning const/nonconst references to the data.
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 303 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  // Here we will create the RestartableData even though we may not use this instance.
  // If it's already in use, the App will return a reference to the existing instance and we'll
  // return that one instead. We might refactor this to have the app create the RestartableData
  // at a later date.
  auto data_ptr =
      std::make_unique<RestartableData<T>>(full_name, context, std::forward<Args>(args)...);
  auto & restartable_data_ref = static_cast<RestartableData<T> &>(
      registerRestartableDataOnApp(std::move(data_ptr), _restartable_tid));
  return restartable_data_ref;
}
declareRestartableDataWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 294 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...).set();
}
declareRestartableDataWithObjectName()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectName (const std::string & data_name, const std::string & object_name, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
args Arguments to forward to the constructor of the data
Definition at line 323 of file Restartable.h.
{
  return declareRestartableDataWithObjectNameWithContext<T>(
      data_name, object_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataWithObjectNameWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectNameWithContext (const std::string & data_name, const std::string & object_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 333 of file Restartable.h.
{
  std::string old_name = _restartable_name;
  _restartable_name = object_name;
  T & value = declareRestartableDataWithContext<T>(data_name, context, std::forward<Args>(args)...);
  _restartable_name = old_name;
  return value;
}
defaultADMaterialProperty()
template<typename T > const ADMaterialProperty< T > * MaterialPropertyInterface::defaultADMaterialProperty (const std::string & name) inline protected inherited
Definition at line 506 of file MaterialPropertyInterface.h.
  {
    return defaultGenericMaterialProperty<T, true>(name);
  }
defaultGenericMaterialProperty()
template<typename T , bool is_ad> const GenericMaterialProperty< T, is_ad > * MaterialPropertyInterface::defaultGenericMaterialProperty (const std::string & name) protected inherited
Returns
The default material property with the name name, if any.
"Default" properties are properties whose default values are set from within the name. That is, if we can cast name to a Real, and the prop type is a Real or RealVectorValue, we'll return said value.
Definition at line 603 of file MaterialPropertyInterface.h.
{
  if constexpr (std::is_same_v<T, Real> || std::is_same_v<T, RealVectorValue>)
  {
    std::istringstream ss(name);
    Real real_value;
    // check if the string parsed cleanly into a Real number
    if (ss >> real_value && ss.eof())
    {
      using prop_type = GenericMaterialProperty<T, is_ad>;
      const auto nqp = Moose::constMaxQpsPerElem;
      auto & property =
          _default_properties.emplace_back(std::make_unique<prop_type>(default_property_id));
      auto & T_property = static_cast<prop_type &>(*property);
      T_property.resize(nqp);
      for (const auto qp : make_range(nqp))
        T_property[qp] = real_value;
      return &T_property;
    }
  }
  return nullptr;
}
defaultMaterialProperty()
template<typename T > const MaterialProperty< T > * MaterialPropertyInterface::defaultMaterialProperty (const std::string & name) inline protected inherited
Definition at line 501 of file MaterialPropertyInterface.h.
  {
    return defaultGenericMaterialProperty<T, false>(name);
  }
dot()
const OutputTools< Real >::VariableValue & MooseVariableInterface< Real >::dot protected virtual inherited
The time derivative of the variable this object is operating on.
Returns
The reference to be stored off and used later.
Definition at line 90 of file MooseVariableInterface.C.
{
  if (_nodal)
    return _variable->dofValuesDot();
  else
    return _variable->uDot();
}
dotDot()
const OutputTools< Real >::VariableValue & MooseVariableInterface< Real >::dotDot protected virtual inherited
The second time derivative of the variable this object is operating on.
Returns
The reference to be stored off and used later.
Definition at line 97 of file MooseVariableInterface.C.
{
  if (_nodal)
    return _variable->dofValuesDotDot();
  else
    return _variable->uDotDot();
}
dotDotDu()
const VariableValue & MooseVariableInterface< Real >::dotDotDu protected virtual inherited
The derivative of the second time derivative of the variable this object is operating on with respect to this variable's coefficients.
This is useful for creating Jacobian entries for residual statements that use _u_dotdot
Returns
The reference to be stored off and used later.
Definition at line 131 of file MooseVariableInterface.C.
{
  if (_nodal)
    return _variable->dofValuesDuDotDotDu();
  else
    return _variable->duDotDotDu();
}
dotDotOld()
const OutputTools< Real >::VariableValue & MooseVariableInterface< Real >::dotDotOld protected virtual inherited
The old second time derivative of the variable this object is operating on.
Returns
The reference to be stored off and used later.
Definition at line 111 of file MooseVariableInterface.C.
{
  if (_nodal)
    return _variable->dofValuesDotDotOld();
  else
    return _variable->uDotDotOld();
}
dotDu()
const VariableValue & MooseVariableInterface< Real >::dotDu protected virtual inherited
The derivative of the time derivative of the variable this object is operating on with respect to this variable's coefficients.
This is useful for creating Jacobian entries for residual statements that use _u_dot
Returns
The reference to be stored off and used later.
Definition at line 121 of file MooseVariableInterface.C.
{
  if (_nodal)
    return _variable->dofValuesDuDotDu();
  else
    return _variable->duDotDu();
}
dotOld()
const OutputTools< Real >::VariableValue & MooseVariableInterface< Real >::dotOld protected virtual inherited
The old time derivative of the variable this object is operating on.
Returns
The reference to be stored off and used later.
Definition at line 104 of file MooseVariableInterface.C.
{
  if (_nodal)
    return _variable->dofValuesDotOld();
  else
    return _variable->uDotOld();
}
enabled()
virtual bool MooseObject::enabled () const inline virtual inherited
Return the enabled status of the object.
Reimplemented in EigenKernel.
Definition at line 54 of file MooseObject.h.
{ return _enabled; }
Referenced by EigenKernel::enabled().
errorPrefix()
std::string MooseBaseErrorInterface::errorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for this object:
The following <error_type> occurred in the object "<name>", of type "<type>".
Definition at line 15 of file MooseBaseErrorInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the object \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseErrorInterface::mooseError(), and MooseBaseErrorInterface::mooseWarning().
getADMaterialProperty() [1/2]
template<typename T > const ADMaterialProperty< T > & MaterialPropertyInterface::getADMaterialProperty (const std::string & name) inline inherited
Definition at line 99 of file MaterialPropertyInterface.h.
  {
    return getGenericMaterialProperty<T, true>(name, 0);
  }
getADMaterialProperty() [2/2]
template<typename T > const ADMaterialProperty< T > & MaterialPropertyInterface::getADMaterialProperty (const std::string & name, MaterialData & material_data) inline inherited
Retrieve the AD property named "name" for the specified material_data.
state is the property state; 0 = current, 1 = old, 2 = older, etc.
Definition at line 358 of file MaterialPropertyInterface.h.
  {
    return getGenericMaterialProperty<T, true>(name, material_data, 0);
  }
getADMaterialPropertyByName() [1/2]
template<typename T > const ADMaterialProperty< T > & MaterialPropertyInterface::getADMaterialPropertyByName (const MaterialPropertyName & name) inline inherited
Definition at line 136 of file MaterialPropertyInterface.h.
  {
    return getGenericMaterialPropertyByName<T, true>(name, 0);
  }
getADMaterialPropertyByName() [2/2]
template<typename T > const ADMaterialProperty< T > & MaterialPropertyInterface::getADMaterialPropertyByName (const MaterialPropertyName & name, MaterialData & material_data) inline inherited
Retrieve the AD property named "name" without any deduction for the specified \q material_data.
Definition at line 390 of file MaterialPropertyInterface.h.
  {
    return getGenericMaterialPropertyByName<T, true>(name, material_data, 0);
  }
getBlockCoordSystem()
Moose::CoordinateSystemType BlockRestrictable::getBlockCoordSystem () protected inherited
Check if the blocks this object operates on all have the same coordinate system, and if so return it.
Definition at line 311 of file BlockRestrictable.C.
{
  if (!_blk_mesh)
    mooseError("No mesh available in BlockRestrictable::checkCoordSystem()");
  if (!_blk_feproblem)
    mooseError("No problem available in BlockRestrictable::checkCoordSystem()");
  const auto & subdomains = blockRestricted() ? blockIDs() : meshBlockIDs();
  if (subdomains.empty())
    mooseError("No subdomains found in the problem.");
  // make sure all subdomains are using the same coordinate system
  auto coord_system = _blk_feproblem->getCoordSystem(*subdomains.begin());
  for (auto subdomain : subdomains)
    if (_blk_feproblem->getCoordSystem(subdomain) != coord_system)
      mooseError("This object requires all subdomains to have the same coordinate system.");
  return coord_system;
}
getBlockMaterialProperty()
template<typename T > std::pair< const MaterialProperty< T > *, std::set< SubdomainID > > MaterialPropertyInterface::getBlockMaterialProperty (const MaterialPropertyName & name) inherited
Retrieve pointer to a material property with the mesh blocks where it is defined The name required by this method is the name defined in the input file.
This function can be thought as the combination of getMaterialPropertyByName and getMaterialPropertyBlocks. It can be called after the action of all actions.
Parameters
name The name of the material property to retrieve
Returns
Pointer to the material property with the name 'name' and the set of blocks where the property is valid
Definition at line 633 of file MaterialPropertyInterface.h.
{
  const auto name = _get_suffix.empty()
                        ? static_cast<const std::string &>(name_in)
                        : MooseUtils::join(std::vector<std::string>({name_in, _get_suffix}), "_");
  if (_mi_block_ids.empty())
    mooseError("getBlockMaterialProperty must be called by a block restrictable object");
  using pair_type = std::pair<const MaterialProperty<T> *, std::set<SubdomainID>>;
  if (!hasMaterialPropertyByName<T>(name))
    return pair_type(nullptr, {});
  // Call first so that the ID gets registered
  const auto & prop = _material_data.getProperty<T, false>(name, 0, _mi_moose_object);
  auto blocks = getMaterialPropertyBlocks(name);
  auto prop_blocks_pair = pair_type(&prop, std::move(blocks));
  _material_property_dependencies.insert(_material_data.getPropertyId(name));
  // Update consumed properties in MaterialPropertyDebugOutput
  addConsumedPropertyName(_mi_moose_object_name, name);
  return prop_blocks_pair;
}
getCheckedPointerParam()
template<typename T > T MooseBaseParameterInterface::getCheckedPointerParam (const std::string & name, const std::string & error_string = "") const inherited
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
The template parameter must be a pointer or an error will be thrown.
Definition at line 264 of file MooseBaseParameterInterface.h.
{
  return parameters().getCheckedPointerParam<T>(name, error_string);
}
getDataFileName()
std::string DataFileInterface< MooseObject >::getDataFileName (const std::string & param) const inherited
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
relative to the input file directory
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
relative to the input file directory
Definition at line 34 of file DataFileInterface.C.
{
  {
    const auto & absolute_path = _parent.template getParam<FileName>(param);
    if (MooseUtils::checkFileReadable(absolute_path, false, false, false))
    {
      _parent.paramInfo(param, "Data file '", absolute_path, "' found relative to the input file.");
      return absolute_path;
    }
  }
  const auto & relative_path = _parent.parameters().rawParamVal(param);
  return getDataFileNameByName(relative_path, &param);
}
getDataFileNameByName()
std::string DataFileInterface< MooseObject >::getDataFileNameByName (const std::string & name, const std::string * param = nullptr) const inherited
Returns the path of a data file for a given relative file path.
This can be used for hardcoded datafile names and will search the same locations as getDataFileName. The optional param pointer can be used to turn the mooseErrors this function emits into paramErrors
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
Definition at line 42 of file DataFileInterface.C.
{
  const auto share_dir = MooseUtils::pathjoin(Moose::getExecutablePath(), "..", "share");
  if (MooseUtils::pathIsDirectory(share_dir))
  {
    const auto dirs = MooseUtils::listDir(share_dir, false);
    for (const auto & data_dir : dirs)
    {
      const auto path = MooseUtils::pathjoin(data_dir, "data", relative_path);
      if (MooseUtils::checkFileReadable(path, false, false, false))
      {
        if (param)
          _parent.paramInfo(
              *param, "Data file '", path, "' found in an installed app distribution.");
        else
          mooseInfo("Data file '", path, "' found in an installed app distribution.");
        return path;
      }
    }
  }
  for (const auto & data_dir : Registry::getRegistry().getDataFilePaths())
  {
    const auto path = MooseUtils::pathjoin(data_dir, relative_path);
    if (MooseUtils::checkFileReadable(path, false, false, false))
    {
      if (param)
        _parent.paramInfo(*param, "Data file '", path, "' found in a source repository.");
      else
        mooseInfo("Data file '", path, "' found in a source repository.");
      return path;
    }
  }
  mooseException(param ? _parent.parameters().inputLocation(*param) : _parent.name(),
                 ": Unable to find data file '",
                 relative_path,
                 "' anywhere");
}
getDefaultPostprocessorValueByName()
PostprocessorValue PostprocessorInterface::getDefaultPostprocessorValueByName (const PostprocessorName & name) const private inherited
Returns
The default value stored in the PostprocessorName name.
Definition at line 96 of file PostprocessorInterface.C.
{
  mooseAssert(isDefaultPostprocessorValueByName(name), "Not a default value");
  Real real_value = -std::numeric_limits<Real>::max();
  std::istringstream ss(name);
  ss >> real_value;
  return real_value;
}
Referenced by PostprocessorInterface::getPostprocessorValueInternal().
getErrorVector()
ErrorVector & Marker::getErrorVector (std::string indicator) protected inherited
Get an ErrorVector that will be filled up with values corresponding to the indicator passed in.
Note that this returns a reference... and the return value should be stored as a reference!
Parameters
indicator The name of the indicator to get an ErrorVector for.
Definition at line 77 of file Marker.C.
{
  return _adaptivity.getErrorVector(indicator);
}
getExecuteOnEnum()
const ExecFlagEnum & SetupInterface::getExecuteOnEnum () const inherited
Return the execute on MultiMooseEnum for this object.
Definition at line 65 of file SetupInterface.C.
{
  return _execute_enum;
}
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), MultiAppTransfer::checkMultiAppExecuteOn(), IntegralPreservingFunctionIC::initialSetup(), MultiAppConservativeTransfer::initialSetup(), Terminator::initialSetup(), ElementReporter::shouldStore(), GeneralReporter::shouldStore(), and NodalReporter::shouldStore().
getGenericMaterialProperty() [1/2]
template<typename T , bool is_ad> const GenericMaterialProperty< T, is_ad > & MaterialPropertyInterface::getGenericMaterialProperty (const std::string & name, const unsigned int state = 0) inline inherited
Retrieve reference to material property or one of it's old or older values.
The name required by this method is the name that is hard-coded into your source code as the input parameter key. If no input parameter is found this behaves like the getMaterialPropertyByName family as a fall back.
Parameters
name The name of the parameter key of the material property to retrieve
state The state (current = 0, old = 1, older = 2)
Returns
Reference to the desired material property
Definition at line 87 of file MaterialPropertyInterface.h.
  {
    return getGenericMaterialProperty<T, is_ad>(name, _material_data, state);
  }
getGenericMaterialProperty() [2/2]
template<typename T , bool is_ad> const GenericMaterialProperty< T, is_ad > & MaterialPropertyInterface::getGenericMaterialProperty (const std::string & name, MaterialData & material_data, const unsigned int state = 0) inherited
Retrieve the generic property named "name" for the specified material_data at state state.
Definition at line 751 of file MaterialPropertyInterface.h.
{
  // Check if the supplied parameter is a valid input parameter key
  const auto prop_name = getMaterialPropertyName(name);
  // Check if it's just a constant
  if (const auto * default_property = defaultGenericMaterialProperty<T, is_ad>(prop_name))
    return *default_property;
  if (state > 0 && !_stateful_allowed)
    mooseError("Stateful material properties not allowed for this object."
               " State ",
               state,
               " property for \"",
               name,
               "\" was requested.");
  return this->getGenericMaterialPropertyByName<T, is_ad>(prop_name, material_data, state);
}
getGenericMaterialPropertyByName() [1/2]
template<typename T , bool is_ad> const GenericMaterialProperty< T, is_ad > & MaterialPropertyInterface::getGenericMaterialPropertyByName (const MaterialPropertyName & name, const unsigned int state = 0) inline inherited
Retrieve reference to material property or its old or older value The name required by this method is the name defined in the input file.
Parameters
name The name of the material property to retrieve
state The state (current = 0, old = 1, older = 2)
Returns
Reference to the material property with the name 'name'
Definition at line 125 of file MaterialPropertyInterface.h.
  {
    return getGenericMaterialPropertyByName<T, is_ad>(name, _material_data, state);
  }
getGenericMaterialPropertyByName() [2/2]
template<typename T , bool is_ad> const GenericMaterialProperty< T, is_ad > & MaterialPropertyInterface::getGenericMaterialPropertyByName (const MaterialPropertyName & name, MaterialData & material_data, const unsigned int state) inherited
Retrieve the generic property named "name" without any deduction for the specified material_data for state state.
Definition at line 775 of file MaterialPropertyInterface.h.
{
  if (_use_interpolated_state)
  {
    if (state == 1)
      return getGenericMaterialPropertyByName<T, is_ad>(
          name_in + _interpolated_old, material_data, 0);
    if (state == 2)
      return getGenericMaterialPropertyByName<T, is_ad>(
          name_in + _interpolated_older, material_data, 0);
  }
  const auto name = _get_suffix.empty()
                        ? static_cast<const std::string &>(name_in)
                        : MooseUtils::join(std::vector<std::string>({name_in, _get_suffix}), "_");
  checkExecutionStage();
  checkMaterialProperty(name, state);
  // mark property as requested
  markMatPropRequested(name);
  // Update the boolean flag.
  _get_material_property_called = true;
  // Call first so that the ID gets registered
  auto & prop = material_data.getProperty<T, is_ad>(name, state, _mi_moose_object);
  // Does the material data used here matter?
  _material_property_dependencies.insert(material_data.getPropertyId(name));
  if (state == 0)
    addConsumedPropertyName(_mi_moose_object_name, name);
  return prop;
}
getGenericOptionalMaterialProperty()
template<typename T , bool is_ad> const GenericOptionalMaterialProperty< T, is_ad > & MaterialPropertyInterface::getGenericOptionalMaterialProperty (const std::string & name, const unsigned int state = 0) inherited
Optional material property getters state is the property state; 0 = current, 1 = old, 2 = older, etc.
Definition at line 739 of file MaterialPropertyInterface.h.
{
  auto proxy = std::make_unique<OptionalMaterialPropertyProxy<MaterialPropertyInterface, T, is_ad>>(
      name, state);
  auto & optional_property = proxy->value();
  _optional_property_proxies.push_back(std::move(proxy));
  return optional_property;
}
getGenericZeroMaterialProperty() [1/2]
template<typename T , bool is_ad> const GenericMaterialProperty< T, is_ad > & MaterialPropertyInterface::getGenericZeroMaterialProperty inherited
Return a constant zero anonymous material property.
Definition at line 700 of file MaterialPropertyInterface.h.
{
  // static zero property storage
  static GenericMaterialProperty<T, is_ad> zero(zero_property_id);
  // resize to accomodate maximum number of qpoints
  // (in multiapp scenarios getMaxQps can return different values in each app; we need the max)
  unsigned int nqp = getMaxQps();
  if (nqp > zero.size())
    zero.resize(nqp);
  // set values for all qpoints to zero
  for (unsigned int qp = 0; qp < nqp; ++qp)
    MathUtils::mooseSetToZero(zero[qp]);
  return zero;
}
getGenericZeroMaterialProperty() [2/2]
template<typename T , bool is_ad> const GenericMaterialProperty< T, is_ad > & MaterialPropertyInterface::getGenericZeroMaterialProperty (const std::string & name) inherited
Return a material property that is initialized to zero by default and does not need to (but can) be declared by another material.
Definition at line 681 of file MaterialPropertyInterface.h.
{
  const auto prop_name = getMaterialPropertyName(name);
  return getGenericZeroMaterialPropertyByName<T, is_ad>(prop_name);
}
getGenericZeroMaterialPropertyByName()
template<typename T , bool is_ad> const GenericMaterialProperty< T, is_ad > & MaterialPropertyInterface::getGenericZeroMaterialPropertyByName (const std::string & prop_name) inherited
Definition at line 689 of file MaterialPropertyInterface.h.
{
  // if found return the requested property
  if (hasGenericMaterialPropertyByName<T, is_ad>(prop_name))
    return getGenericMaterialPropertyByName<T, is_ad>(prop_name);
  return getGenericZeroMaterialProperty<T, is_ad>();
}
getMarkerValue()
const MooseArray< Real > & Marker::getMarkerValue (std::string name) protected inherited
This is used to get the values of other Markers.
This is useful for making combo-markers that take multiple markers and combine them to make one.
Parameters
name The name of the other Marker that you want to have access to.
Returns
A reference that will hold the value of the marker in it's 0 (zeroth) position.
Definition at line 83 of file Marker.C.
{
  _depend.insert(name);
  return _sys.getFieldVariable<Real>(_tid, name).dofValues();
}
Referenced by ComboMarker::ComboMarker().
getMaterial()
MaterialBase & MaterialPropertyInterface::getMaterial (const std::string & name) inherited
Return a MaterialBase reference - usable for computing directly.
Parameters
name The name of the input parameter or explicit material name.
no_warn If true, suppress warning about retrieving the material potentially during its calculation. If you don't know what this is/means, then you don't need it.
Definition at line 189 of file MaterialPropertyInterface.C.
{
  return getMaterialByName(_mi_params.get<MaterialName>(name));
}
getMaterialByName()
MaterialBase & MaterialPropertyInterface::getMaterialByName (const std::string & name, bool no_warn = false) inherited
Definition at line 195 of file MaterialPropertyInterface.C.
{
  std::shared_ptr<MaterialBase> discrete =
      _mi_feproblem.getMaterial(name, _material_data_type, _mi_tid, no_warn);
  checkBlockAndBoundaryCompatibility(discrete);
  return *discrete;
}
Referenced by MaterialPropertyInterface::getMaterial(), Material::getMaterialByName(), and MaterialVectorPostprocessor::MaterialVectorPostprocessor().
getMaterialDataType()
Moose::MaterialDataType MaterialPropertyInterface::getMaterialDataType (const std::set< BoundaryID > & boundary_ids) const private inherited
Returns
The MaterialDataType given the interface's parameters
Definition at line 237 of file MaterialPropertyInterface.C.
{
  if (_mi_params.isParamValid("_material_data_type"))
    return _mi_params.get<Moose::MaterialDataType>("_material_data_type");
  if (moose::internal::boundaryRestricted(boundary_ids))
    return Moose::BOUNDARY_MATERIAL_DATA;
  return Moose::BLOCK_MATERIAL_DATA;
}
getMaterialProperty() [1/2]
template<typename T > const MaterialProperty< T > & MaterialPropertyInterface::getMaterialProperty (const std::string & name, const unsigned int state = 0) inline inherited
Definition at line 93 of file MaterialPropertyInterface.h.
  {
    return getGenericMaterialProperty<T, false>(name, state);
  }
getMaterialProperty() [2/2]
template<typename T > const MaterialProperty< T > & MaterialPropertyInterface::getMaterialProperty (const std::string & name, MaterialData & material_data, const unsigned int state = 0) inline inherited
Retrieve the property named "name" for the specified material_data.
state is the property state; 0 = current, 1 = old, 2 = older, etc.
Definition at line 345 of file MaterialPropertyInterface.h.
  {
    return getGenericMaterialProperty<T, false>(name, material_data, state);
  }
getMaterialPropertyBlockNames()
std::vector< SubdomainName > MaterialPropertyInterface::getMaterialPropertyBlockNames (const std::string & name) inherited
Retrieve the block names that the material property is defined.
Parameters
name The name of the material property
Returns
A vector the the block names for the property
Definition at line 87 of file MaterialPropertyInterface.C.
{
  return _mi_feproblem.getMaterialPropertyBlockNames(name);
}
getMaterialPropertyBlocks()
std::set< SubdomainID > MaterialPropertyInterface::getMaterialPropertyBlocks (const std::string & name) inherited
Retrieve the block ids that the material property is defined.
Parameters
name The name of the material property
Returns
A vector the the block ids for the property
Definition at line 81 of file MaterialPropertyInterface.C.
{
  return _mi_feproblem.getMaterialPropertyBlocks(name);
}
Referenced by MaterialPropertyInterface::getBlockMaterialProperty().
getMaterialPropertyBoundaryIDs()
std::set< BoundaryID > MaterialPropertyInterface::getMaterialPropertyBoundaryIDs (const std::string & name) inherited
Retrieve the boundary ids that the material property is defined.
Parameters
name The name of the material property
Returns
A vector the the boundary ids for the property
Definition at line 93 of file MaterialPropertyInterface.C.
{
  return _mi_feproblem.getMaterialPropertyBoundaryIDs(name);
}
getMaterialPropertyBoundaryNames()
std::vector< BoundaryName > MaterialPropertyInterface::getMaterialPropertyBoundaryNames (const std::string & name) inherited
Retrieve the boundary namess that the material property is defined.
Parameters
name The name of the material property
Returns
A vector the the boundary names for the property
Definition at line 99 of file MaterialPropertyInterface.C.
{
  return _mi_feproblem.getMaterialPropertyBoundaryNames(name);
}
getMaterialPropertyByName() [1/2]
template<typename T > const MaterialProperty< T > & MaterialPropertyInterface::getMaterialPropertyByName (const MaterialPropertyName & name, const unsigned int state = 0) inline inherited
Definition at line 130 of file MaterialPropertyInterface.h.
  {
    return getGenericMaterialPropertyByName<T, false>(name, state);
  }
getMaterialPropertyByName() [2/2]
template<typename T > const MaterialProperty< T > & MaterialPropertyInterface::getMaterialPropertyByName (const MaterialPropertyName & name, MaterialData & material_data, const unsigned int state = 0) inline inherited
Retrieve the property named "name" without any deduction for the specified material_data.
state is the property state; 0 = current, 1 = old, 2 = older, etc.
Definition at line 378 of file MaterialPropertyInterface.h.
  {
    return getGenericMaterialPropertyByName<T, false>(name, material_data, state);
  }
getMaterialPropertyCalled()
bool MaterialPropertyInterface::getMaterialPropertyCalled () const inline inherited
Returns true if getMaterialProperty() has been called, false otherwise.
Definition at line 316 of file MaterialPropertyInterface.h.
{ return _get_material_property_called; }
getMaterialPropertyName()
MaterialPropertyName MaterialPropertyInterface::getMaterialPropertyName (const std::string & name) const protected inherited
Returns
The name of the material property associated with name name.
If name is the name of a material property parameter and the parameter is valid, this will return the value of said parameter. Otherwise, it will just return the name.
Definition at line 73 of file MaterialPropertyInterface.C.
{
  if (_mi_params.have_parameter<MaterialPropertyName>(name) && _mi_params.isParamValid(name))
    return _mi_params.get<MaterialPropertyName>(name);
  return name;
}
Referenced by InterfaceMaterial::getGenericMaterialProperty(), Material::getGenericMaterialProperty(), MaterialPropertyInterface::getGenericMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialProperty(), MaterialPropertyInterface::getGenericZeroMaterialProperty(), MaterialPropertyInterface::hasADMaterialProperty(), and MaterialPropertyInterface::hasMaterialProperty().
getMaterialPropertyOld() [1/2]
template<typename T > const MaterialProperty< T > & MaterialPropertyInterface::getMaterialPropertyOld (const std::string & name) inline inherited
Definition at line 104 of file MaterialPropertyInterface.h.
  {
    return getMaterialProperty<T>(name, 1);
  }
getMaterialPropertyOld() [2/2]
template<typename T > const MaterialProperty< T > & MaterialPropertyInterface::getMaterialPropertyOld (const std::string & name, MaterialData & material_data) inline inherited
Retrieve the old property deduced from the name name for the specified material_data.
Definition at line 400 of file MaterialPropertyInterface.h.
  {
    return getMaterialProperty<T>(name, material_data, 1);
  }
getMaterialPropertyOldByName() [1/2]
template<typename T > const MaterialProperty< T > & MaterialPropertyInterface::getMaterialPropertyOldByName (const MaterialPropertyName & name) inline inherited
Definition at line 141 of file MaterialPropertyInterface.h.
  {
    return getMaterialPropertyByName<T>(name, 1);
  }
getMaterialPropertyOldByName() [2/2]
template<typename T > const MaterialProperty< T > & MaterialPropertyInterface::getMaterialPropertyOldByName (const MaterialPropertyName & name, MaterialData & material_data) inline inherited
Retrieve the old property named name without any deduction for the specified material_data.
Definition at line 422 of file MaterialPropertyInterface.h.
  {
    return getMaterialPropertyByName<T>(name, material_data, 1);
  }
getMaterialPropertyOlder() [1/2]
template<typename T > const MaterialProperty< T > & MaterialPropertyInterface::getMaterialPropertyOlder (const std::string & name) inline inherited
Definition at line 109 of file MaterialPropertyInterface.h.
  {
    return getMaterialProperty<T>(name, 2);
  }
getMaterialPropertyOlder() [2/2]
template<typename T > const MaterialProperty< T > & MaterialPropertyInterface::getMaterialPropertyOlder (const std::string & name, MaterialData & material_data) inline inherited
Retrieve the older property deduced from the name name for the specified material_data.
Definition at line 411 of file MaterialPropertyInterface.h.
  {
    return getMaterialProperty<T>(name, material_data, 2);
  }
getMaterialPropertyOlderByName() [1/2]
template<typename T > const MaterialProperty< T > & MaterialPropertyInterface::getMaterialPropertyOlderByName (const MaterialPropertyName & name) inline inherited
Definition at line 146 of file MaterialPropertyInterface.h.
  {
    return getMaterialPropertyByName<T>(name, 2);
  }
getMaterialPropertyOlderByName() [2/2]
template<typename T > const MaterialProperty< T > & MaterialPropertyInterface::getMaterialPropertyOlderByName (const MaterialPropertyName & name, MaterialData & material_data) inline inherited
Retrieve the older property named name without any deduction for the specified material_data.
Definition at line 433 of file MaterialPropertyInterface.h.
  {
    return getMaterialPropertyByName<T>(name, material_data, 2);
  }
getMatPropDependencies()
const std::set< unsigned int > & MaterialPropertyInterface::getMatPropDependencies () const inline inherited
Retrieve the set of material properties that this object depends on.
Returns
The IDs corresponding to the material properties that MUST be reinited before evaluating this object
Definition at line 324 of file MaterialPropertyInterface.h.
  {
    return _material_property_dependencies;
  }
Referenced by InterfaceMaterial::getMatPropDependencies(), Material::getMatPropDependencies(), NodalPatchRecovery::reinitPatch(), ComputeUserObjectsThread::subdomainChanged(), and MooseObjectWarehouseBase< T >::updateMatPropDependencyHelper().
getMaxQps()
unsigned int MaterialPropertyInterface::getMaxQps () const private inherited
Definition at line 105 of file MaterialPropertyInterface.C.
{
  return _mi_feproblem.getMaxQps();
}
Referenced by MaterialPropertyInterface::getGenericZeroMaterialProperty().
getMooseApp()
MooseApp & MooseBase::getMooseApp () const inline inherited
Get the MooseApp this class is associated with.
Definition at line 35 of file MooseBase.h.
{ return _app; }
Referenced by ReporterTransferInterface::checkHasReporterValue(), Coupleable::checkWritableVar(), MooseBaseParameterInterface::connectControllableParams(), Coupleable::Coupleable(), MortarData::createMortarInterface(), EigenProblem::doFreeNonlinearPowerIterations(), Terminator::execute(), FEProblemSolve::FEProblemSolve(), SolutionInvalidInterface::flagInvalidSolutionInternal(), MaterialPropertyInterface::MaterialPropertyInterface(), MooseVariableDataFV< OutputType >::MooseVariableDataFV(), ProgressOutput::output(), MooseBaseParameterInterface::paramError(), PetscOutputInterface::petscLinearOutput(), PetscOutputInterface::petscNonlinearOutput(), PetscOutputInterface::PetscOutputInterface(), PostprocessorInterface::postprocessorsAdded(), MultiApp::preTransfer(), Reporter::Reporter(), ReporterInterface::reportersAdded(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
getMooseVariableDependencies()
const std::set< MooseVariableFieldBase * > & MooseVariableDependencyInterface::getMooseVariableDependencies () const inline inherited
Retrieve the set of MooseVariableFieldBase that this object depends on.
Returns
The MooseVariableFieldBase that MUST be reinited before evaluating this object
Definition at line 35 of file MooseVariableDependencyInterface.h.
  {
    return _moose_variable_dependencies;
  }
Referenced by ComputeUserObjectsThread::subdomainChanged(), and MooseObjectWarehouseBase< T >::updateVariableDependencyHelper().
getOptionalADMaterialProperty()
template<typename T > const OptionalADMaterialProperty< T > & MaterialPropertyInterface::getOptionalADMaterialProperty (const std::string & name) inline inherited
Definition at line 165 of file MaterialPropertyInterface.h.
  {
    return getGenericOptionalMaterialProperty<T, true>(name);
  }
getOptionalMaterialProperty()
template<typename T > const OptionalMaterialProperty< T > & MaterialPropertyInterface::getOptionalMaterialProperty (const std::string & name, const unsigned int state = 0) inline inherited
Definition at line 159 of file MaterialPropertyInterface.h.
  {
    return getGenericOptionalMaterialProperty<T, false>(name, state);
  }
getOptionalMaterialPropertyOld()
template<typename T > const OptionalMaterialProperty< T > & MaterialPropertyInterface::getOptionalMaterialPropertyOld (const std::string & name) inline inherited
Definition at line 171 of file MaterialPropertyInterface.h.
  {
    return getOptionalMaterialProperty<T>(name, 1);
  }
getOptionalMaterialPropertyOlder()
template<typename T > const OptionalMaterialProperty< T > & MaterialPropertyInterface::getOptionalMaterialPropertyOlder (const std::string & name) inline inherited
Definition at line 176 of file MaterialPropertyInterface.h.
  {
    return getOptionalMaterialProperty<T>(name, 2);
  }
getOutputs()
const std::set< OutputName > & OutputInterface::getOutputs () inherited
Get the list of output objects that this class is restricted.
Returns
A set of OutputNames
Definition at line 94 of file OutputInterface.C.
{
  return _oi_outputs;
}
getParam() [1/2]
template<typename T > const T & MooseBaseParameterInterface::getParam (const std::string & name) const inherited
Retrieve a parameter for the object.
Parameters
name The name of the parameter
Returns
The value of the parameter
Definition at line 200 of file MooseBaseParameterInterface.h.
{
  return InputParameters::getParamHelper(name, _pars, static_cast<T *>(0));
}
Referenced by AddGeneralReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddPeriodicBCAction::act(), CreateDisplacedProblemAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), ConstraintWarehouse::addObject(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), ADNodalKernel::ADNodalKernel(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), PiecewiseTabularBase::buildFromJSON(), Console::Console(), FEProblemBase::createTagSolutions(), AccumulateReporter::declareLateValues(), DerivativeParsedMaterialTempl< is_ad >::DerivativeParsedMaterialTempl(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EigenKernel::EigenKernel(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), GenericConstantRankTwoTensorTempl< is_ad >::GenericConstantRankTwoTensorTempl(), MooseApp::getCheckpointDirectories(), ExecutorInterface::getExecutor(), AdvancedOutput::init(), IterationAdaptiveDT::init(), TimeSequenceStepper::init(), AttribThread::initFrom(), AttribSysNum::initFrom(), AttribResidualObject::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), Console::initialSetup(), IterationAdaptiveDT::limitDTToPostprocessorValue(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MortarConsumerInterface::MortarConsumerInterface(), NestedDivision::NestedDivision(), ConsoleUtils::outputExecutionInformation(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedMaterialTempl< is_ad >::ParsedMaterialTempl(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), ParsedODEKernel::ParsedODEKernel(), ParsedPostprocessor::ParsedPostprocessor(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), Moose::FV::setInterpolationMethod(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), TimePeriod::TimePeriod(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and VectorOfPostprocessors::VectorOfPostprocessors().
getParam() [2/2]
template<typename T1 , typename T2 > std::vector< std::pair< T1, T2 > > MooseBaseParameterInterface::getParam (const std::string & param1, const std::string & param2) const inherited
Retrieve two parameters and provide pair of parameters for the object.
Parameters
param1 The name of first parameter
param2 The name of second parameter
Returns
Vector of pairs of first and second parameters
Definition at line 257 of file MooseBaseParameterInterface.h.
{
  return _pars.get<T1, T2>(param1, param2);
}
getPostprocessorName()
const PostprocessorName & PostprocessorInterface::getPostprocessorName (const std::string & param_name, const unsigned int index = 0) const inherited
Get the name of a postprocessor.
This can only be used if the postprocessor parameter does not have a default value set (see isDefaultPostprocessorValue()), in which case the "name" is actually the default value.
Parameters
param_name The name of the Postprocessor parameter
index The index of the Postprocessor
Returns
The name of the given Postprocessor
Definition at line 185 of file PostprocessorInterface.C.
{
  return getPostprocessorNameInternal(param_name, index, /* allow_default_value = */ false);
}
Referenced by EigenKernel::EigenKernel().
getPostprocessorNameInternal()
const PostprocessorName & PostprocessorInterface::getPostprocessorNameInternal (const std::string & param_name, const unsigned int index, const bool allow_default_value = true) const private inherited
Internal method for getting the PostprocessorName associated with a paremeter.
Needed in order to allow the return of a name that is a default value.
Definition at line 192 of file PostprocessorInterface.C.
{
  checkParam(param_name, index);
  const auto & name = _ppi_params.isType<PostprocessorName>(param_name)
                          ? _ppi_params.get<PostprocessorName>(param_name)
                          : _ppi_params.get<std::vector<PostprocessorName>>(param_name)[index];
  if (!allow_default_value && isDefaultPostprocessorValueByName(name))
  {
    std::stringstream oss;
    oss << "Cannot get the name associated with PostprocessorName parameter \"" << param_name
        << "\"";
    if (index)
      oss << " at index " << index;
    oss << ",\nbecause said parameter is a default Postprocessor value.";
    _ppi_moose_object.paramError(param_name, oss.str());
  }
  return name;
}
Referenced by PostprocessorInterface::getPostprocessorName(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), and PostprocessorInterface::isDefaultPostprocessorValue().
getPostprocessorValue()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValue (const std::string & param_name, const unsigned int index = 0) const inherited
doco-normal-methods-begin Retrieve the value of a Postprocessor or one of it's old or older values
Parameters
param_name The name of the Postprocessor parameter (see below)
index The index of the Postprocessor
Returns
A reference to the desired value
The name required by this method is the name that is hard-coded into your source code. For example, if you have a Kernel that requires a Postprocessor you may have an input file with "pp = my_pp", this function requires the "pp" name as input (see .../moose_test/functions/PostprocessorFunction.C)
see getPostprocessorValueByName getPostprocessorValueOldByName getPostprocessorValueOlderByName
Definition at line 36 of file PostprocessorInterface.C.
{
  return getPostprocessorValueInternal(param_name, index, /* t_index = */ 0);
}
Referenced by EigenKernel::EigenKernel(), FunctionValuePostprocessor::FunctionValuePostprocessor(), LinearCombinationPostprocessor::LinearCombinationPostprocessor(), ParsedPostprocessor::ParsedPostprocessor(), and PicardSolve::PicardSolve().
getPostprocessorValueByName()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueByName (const PostprocessorName & name) const virtual inherited
Retrieve the value of the Postprocessor.
Parameters
name Postprocessor name (see below)
Returns
A reference to the desired value
The name required by this method is the name defined in the input file. For example, if you have a Kernel that requires a Postprocessor you may have an input file with "pp = my_pp", this method requires the "my_pp" name as input (see .../moose_test/functions/PostprocessorFunction.C)
see getPostprocessorValue getPostprocessorValueOld getPostprocessorValueOlder
Definition at line 57 of file PostprocessorInterface.C.
{
  return getPostprocessorValueByNameInternal(name, /* t_index = */ 0);
}
Referenced by EigenKernel::EigenKernel(), PIDTransientControl::execute(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), ParsedODEKernel::ParsedODEKernel(), PicardSolve::savePostprocessorValues(), SecantSolve::savePostprocessorValues(), SteffensenSolve::savePostprocessorValues(), Terminator::Terminator(), PicardSolve::transformPostprocessors(), SecantSolve::transformPostprocessors(), SteffensenSolve::transformPostprocessors(), and VectorOfPostprocessors::VectorOfPostprocessors().
getPostprocessorValueByNameInternal()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueByNameInternal (const PostprocessorName & name, std::size_t t_index) const private inherited
Definition at line 246 of file PostprocessorInterface.C.
{
  mooseAssert(t_index < 3, "Invalid time index");
  mooseAssert(!isDefaultPostprocessorValueByName(name), "Should not be default");
  // If all pps have been added, we can check for existance
  if (postprocessorsAdded() && !hasPostprocessorByName(name))
    _ppi_moose_object.mooseError("A Postprocessor with the name \"", name, "\" was not found.");
  if (t_index == 0)
    addPostprocessorDependencyHelper(name);
  return _ppi_feproblem.getReporterData().getReporterValue<PostprocessorValue>(
      PostprocessorReporterName(name), _ppi_moose_object, REPORTER_MODE_ROOT, t_index);
}
Referenced by PostprocessorInterface::getPostprocessorValueByName(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::getPostprocessorValueOldByName(), and PostprocessorInterface::getPostprocessorValueOlderByName().
getPostprocessorValueInternal()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueInternal (const std::string & param_name, unsigned int index, std::size_t t_index) const private inherited
Internal methods for getting Postprocessor values.
Definition at line 218 of file PostprocessorInterface.C.
{
  const auto & name = getPostprocessorNameInternal(param_name, index);
  // If the Postprocessor is a default value (either set by addParam or set to a constant
  // value by the user in input/an action), we covert the name to a value, store said
  // value locally, and return it so that it fits in with the rest of the interface
  // (needing a reference to a value)
  if (isDefaultPostprocessorValueByName(name))
  {
    const auto value = getDefaultPostprocessorValueByName(name);
    const auto & value_ref =
        *_default_values.emplace(name, std::make_unique<PostprocessorValue>(value))
             .first->second; // first is inserted pair, second is value in pair
    mooseAssert(value == value_ref, "Inconsistent default value");
    return value_ref;
  }
  // If not a default and all pps have been added, we check check for existance
  else if (postprocessorsAdded() && !hasPostprocessorByName(name))
    _ppi_moose_object.paramError(
        param_name, "A Postprocessor with the name \"", name, "\" was not found.");
  return getPostprocessorValueByNameInternal(name, t_index);
}
Referenced by PostprocessorInterface::getPostprocessorValue(), PostprocessorInterface::getPostprocessorValueOld(), and PostprocessorInterface::getPostprocessorValueOlder().
getPostprocessorValueOld()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOld (const std::string & param_name, const unsigned int index = 0) const inherited
Definition at line 43 of file PostprocessorInterface.C.
{
  return getPostprocessorValueInternal(param_name, index, /* t_index = */ 1);
}
getPostprocessorValueOldByName()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOldByName (const PostprocessorName & name) const inherited
Definition at line 63 of file PostprocessorInterface.C.
{
  return getPostprocessorValueByNameInternal(name, /* t_index = */ 1);
}
Referenced by EigenKernel::EigenKernel().
getPostprocessorValueOlder()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOlder (const std::string & param_name, const unsigned int index = 0) const inherited
Definition at line 50 of file PostprocessorInterface.C.
{
  return getPostprocessorValueInternal(param_name, index, /* t_index = */ 2);
}
getPostprocessorValueOlderByName()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOlderByName (const PostprocessorName & name) const inherited
Definition at line 69 of file PostprocessorInterface.C.
{
  return getPostprocessorValueByNameInternal(name, /* t_index = */ 2);
}
getRenamedParam()
template<typename T > const T & MooseBaseParameterInterface::getRenamedParam (const std::string & old_name, const std::string & new_name) const inherited
Retrieve a renamed parameter for the object.
This helper makes sure we check both names before erroring, and that only one parameter is passed to avoid silent errors
Parameters
old_name the old name for the parameter
new_name the new name for the parameter
Definition at line 207 of file MooseBaseParameterInterface.h.
{
  // this enables having a default on the new parameter but bypassing it with the old one
  // Most important: accept new parameter
  if (isParamSetByUser(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Second most: accept old parameter
  else if (isParamValid(old_name) && !isParamSetByUser(new_name))
    return InputParameters::getParamHelper(old_name, _pars, static_cast<T *>(0));
  // Third most: accept default for new parameter
  else if (isParamValid(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Refuse: no default, no value passed
  else if (!isParamValid(old_name) && !isParamValid(new_name))
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' is being retrieved without being set.\n"
               "Did you misspell it?");
  // Refuse: both old and new parameters set by user
  else
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' may not be provided alongside former parameter '" + old_name + "'");
}
getRequestedItems()
const std::set< std::string > & Marker::getRequestedItems () override virtual inherited
Return a set containing the names of items requested by the object.
Implements DependencyResolverInterface.
Definition at line 101 of file Marker.C.
{
  return _depend;
}
getRestartableData()
template<typename T , typename... Args> const T & Restartable::getRestartableData (const std::string & data_name) const protected inherited
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
Forwarded arguments are not allowed in this case because we assume that the object is restarted and we won't need different constructors to initialize it.
NOTE: This returns a const reference! Make sure you store it in a const reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
Definition at line 287 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, nullptr).get();
}
getSuppliedItems()
const std::set< std::string > & Marker::getSuppliedItems () override virtual inherited
Return a set containing the names of items owned by the object.
Implements DependencyResolverInterface.
Definition at line 107 of file Marker.C.
{
  return _supplied;
}
getUserObject()
template<class T > const T & UserObjectInterface::getUserObject (const std::string & param_name, bool is_dependency = true) const inherited
Get an user object with a given parameter param_name.
Parameters
param_name The name of the parameter key of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with name associated with the parameter param_name
Definition at line 160 of file UserObjectInterface.h.
{
  return castUserObject<T>(getUserObjectBase(param_name, is_dependency), param_name);
}
getUserObjectBase()
const UserObject & UserObjectInterface::getUserObjectBase (const std::string & param_name, bool is_dependency = true) const inherited
Get an user object with a given parameter param_name.
Parameters
param_name The name of the parameter key of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with name associated with the parameter param_name
Definition at line 79 of file UserObjectInterface.C.
{
  const auto object_name = getUserObjectName(param_name);
  if (!hasUserObjectByName(object_name))
    _uoi_moose_object.paramError(
        param_name, "The requested UserObject with the name \"", object_name, "\" was not found.");
  return getUserObjectBaseByName(object_name, is_dependency);
}
Referenced by UserObjectInterface::getUserObject().
getUserObjectBaseByName()
const UserObject & UserObjectInterface::getUserObjectBaseByName (const UserObjectName & object_name, bool is_dependency = true) const inherited
Get an user object with the name object_name.
Parameters
object_name The name of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with the name object_name
Definition at line 91 of file UserObjectInterface.C.
{
  if (!hasUserObjectByName(object_name))
    _uoi_moose_object.mooseError(
        "The requested UserObject with the name \"", object_name, "\" was not found.");
  const auto & uo_base_tid0 = _uoi_feproblem.getUserObjectBase(object_name, /* tid = */ 0);
  if (is_dependency)
    addUserObjectDependencyHelper(uo_base_tid0);
  const THREAD_ID tid = uo_base_tid0.needThreadedCopy() ? _uoi_tid : 0;
  return _uoi_feproblem.getUserObjectBase(object_name, tid);
}
Referenced by UserObject::getDependObjects(), UserObjectInterface::getUserObjectBase(), and UserObjectInterface::getUserObjectByName().
getUserObjectByName()
template<class T > const T & UserObjectInterface::getUserObjectByName (const UserObjectName & object_name, bool is_dependency = true) const inherited
Get an user object with the name object_name.
Parameters
object_name The name of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with the name object_name
Definition at line 167 of file UserObjectInterface.h.
{
  return castUserObject<T>(getUserObjectBaseByName(object_name, is_dependency));
}
getUserObjectName()
UserObjectName UserObjectInterface::getUserObjectName (const std::string & param_name) const inherited
Returns
The name of the user object associated with the parameter param_name
Definition at line 34 of file UserObjectInterface.C.
{
  const auto & params = _uoi_moose_object.parameters();
  if (!params.isParamValid(param_name))
    _uoi_moose_object.mooseError("Failed to get a parameter with the name \"",
                                 param_name,
                                 "\" when getting a UserObjectName.",
                                 "\n\nKnown parameters:\n",
                                 _uoi_moose_object.parameters());
  // Other interfaces will use this interface (PostprocessorInterface, VectorPostprocessorInterface)
  // to grab UOs with a specialized name, so we need to check them all
  UserObjectName name;
  if (params.isType<UserObjectName>(param_name))
    name = params.get<UserObjectName>(param_name);
  else if (params.isType<PostprocessorName>(param_name))
    name = params.get<PostprocessorName>(param_name);
  else if (params.isType<VectorPostprocessorName>(param_name))
    name = params.get<VectorPostprocessorName>(param_name);
  else if (params.isType<std::string>(param_name))
    name = params.get<std::string>(param_name);
  else
    _uoi_moose_object.paramError(
        param_name,
        "Parameter of type \"",
        params.type(param_name),
        "\" is not an expected type for getting the name of a UserObject.");
  return name;
}
Referenced by UserObjectInterface::getUserObjectBase(), and UserObjectInterface::hasUserObject().
getZeroMaterialProperty()
template<typename T , typename... Ts> const MaterialProperty< T > & MaterialPropertyInterface::getZeroMaterialProperty (Ts... args) inline inherited
for backwards compatibility
Definition at line 215 of file MaterialPropertyInterface.h.
  {
    return getGenericZeroMaterialProperty<T, false>(args...);
  }
gradient()
const OutputTools< Real >::VariableGradient & MooseVariableInterface< Real >::gradient protected virtual inherited
The gradient of the variable this object is operating on.
This is computed by default and should already be available as _grad_u
Returns
The reference to be stored off and used later.
Definition at line 140 of file MooseVariableInterface.C.
{
  if (_nodal)
    mooseError("gradients are not defined at nodes");
  return _variable->gradSln();
}
gradientOld()
const OutputTools< Real >::VariableGradient & MooseVariableInterface< Real >::gradientOld protected virtual inherited
The old gradient of the variable this object is operating on.
Returns
The reference to be stored off and used later.
Definition at line 147 of file MooseVariableInterface.C.
{
  if (_nodal)
    mooseError("gradients are not defined at nodes");
  return _variable->gradSlnOld();
}
gradientOlder()
const OutputTools< Real >::VariableGradient & MooseVariableInterface< Real >::gradientOlder protected virtual inherited
The older gradient of the variable this object is operating on.
Returns
The reference to be stored off and used later.
Definition at line 154 of file MooseVariableInterface.C.
{
  if (_nodal)
    mooseError("gradients are not defined at nodes");
  return _variable->gradSlnOlder();
}
hasADMaterialProperty()
template<typename T > bool MaterialPropertyInterface::hasADMaterialProperty (const std::string & name) inherited
Definition at line 720 of file MaterialPropertyInterface.h.
{
  // Check if the supplied parameter is a valid input parameter key
  const auto prop_name = getMaterialPropertyName(name);
  return hasADMaterialPropertyByName<T>(prop_name);
}
hasADMaterialPropertyByName()
template<typename T > bool MaterialPropertyInterface::hasADMaterialPropertyByName (const std::string & name) inherited
Definition at line 729 of file MaterialPropertyInterface.h.
{
  const auto name = _get_suffix.empty()
                        ? name_in
                        : MooseUtils::join(std::vector<std::string>({name_in, _get_suffix}), "_");
  return _material_data.haveADProperty<T>(name);
}
hasBlockMaterialProperty()
template<typename T , bool is_ad> bool BlockRestrictable::hasBlockMaterialProperty (const std::string & prop_name) inherited
Check if a material property is valid for all blocks of this object.
This method returns true if the supplied property name has been declared in a Material object on the block ids for this object.
Template Parameters
T The type of material property
Parameters
prop_name the name of the property to query
Returns
true if the property exists for all block ids of the object, otherwise false
See also
Material::hasBlockMaterialProperty
Definition at line 264 of file BlockRestrictable.h.
{
  mooseAssert(_blk_material_data != NULL, "MaterialData pointer is not defined");
  return hasBlockMaterialPropertyHelper(prop_name) &&
         _blk_material_data->haveGenericProperty<T, is_ad>(prop_name);
}
hasBlockMaterialPropertyHelper()
bool BlockRestrictable::hasBlockMaterialPropertyHelper (const std::string & prop_name) protected virtual inherited
A helper method to allow the Material object to specialize the behavior of hasBlockMaterialProperty.
It also avoid circular #include problems.
See also
hasBlockMaterialProperty
Definition at line 275 of file BlockRestrictable.C.
{
  // Reference to MaterialWarehouse for testing and retrieving block ids
  const MaterialWarehouse & warehouse = _blk_feproblem->getMaterialWarehouse();
  // Complete set of ids that this object is active
  const std::set<SubdomainID> & ids = blockRestricted() ? blockIDs() : meshBlockIDs();
  // Loop over each id for this object
  for (const auto & id : ids)
  {
    // Storage of material properties that have been DECLARED on this id
    std::set<std::string> declared_props;
    // If block materials exist, populated the set of properties that were declared
    if (warehouse.hasActiveBlockObjects(id))
    {
      const std::vector<std::shared_ptr<MaterialBase>> & mats = warehouse.getActiveBlockObjects(id);
      for (const auto & mat : mats)
      {
        const std::set<std::string> & mat_props = mat->getSuppliedItems();
        declared_props.insert(mat_props.begin(), mat_props.end());
      }
    }
    // If the supplied property is not in the list of properties on the current id, return false
    if (declared_props.find(prop_name) == declared_props.end())
      return false;
  }
  // If you get here the supplied property is defined on all blocks
  return true;
}
Referenced by BlockRestrictable::hasBlockMaterialProperty().
hasBlocks() [1/5]
bool BlockRestrictable::hasBlocks (const std::set< SubdomainID > & ids) const inherited
Test if the supplied set of block ids are valid for this object.
Parameters
ids A std::set of SubdomainIDs to check
Returns
True if all of the given ids are found within the ids for this object
See also
isSubset
Definition at line 237 of file BlockRestrictable.C.
{
  if (_blk_ids.empty() || _blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return true;
  else
    return std::includes(_blk_ids.begin(), _blk_ids.end(), ids.begin(), ids.end());
}
hasBlocks() [2/5]
bool BlockRestrictable::hasBlocks (const std::vector< SubdomainID > & ids) const inherited
Test if the supplied vector block ids are valid for this object.
Parameters
ids A vector of SubdomainIDs ids to check
Returns
True if all of the given ids are found within the ids for this object
Definition at line 230 of file BlockRestrictable.C.
{
  std::set<SubdomainID> ids_set(ids.begin(), ids.end());
  return hasBlocks(ids_set);
}
hasBlocks() [3/5]
bool BlockRestrictable::hasBlocks (const std::vector< SubdomainName > & names) const inherited
Test if the supplied vector of block names are valid for this object.
Parameters
names A vector of SubdomainNames to check
Returns
True if the given ids are valid for this object
Definition at line 215 of file BlockRestrictable.C.
{
  return hasBlocks(_blk_mesh->getSubdomainIDs(names));
}
hasBlocks() [4/5]
bool BlockRestrictable::hasBlocks (const SubdomainName & name) const inherited
Test if the supplied block name is valid for this object.
Parameters
name A SubdomainName to check
Returns
True if the given id is valid for this object
Definition at line 205 of file BlockRestrictable.C.
{
  // Create a vector and utilize the getSubdomainIDs function, which
  // handles the ANY_BLOCK_ID (getSubdomainID does not)
  std::vector<SubdomainName> names(1);
  names[0] = name;
  return hasBlocks(_blk_mesh->getSubdomainIDs(names));
}
Referenced by DiracKernelBase::addPoint(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), DomainUserObject::checkVariable(), ComputeJacobianThread::compute(), DomainUserObject::DomainUserObject(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), ExtraIDIntegralVectorPostprocessor::execute(), MeshDivisionFunctorReductionVectorPostprocessor::execute(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), MooseVariableField< OutputType >::hasBlocks(), BlockRestrictable::hasBlocks(), FVFluxKernel::hasFaceSide(), and PointwiseRenormalizeVector::PointwiseRenormalizeVector().
hasBlocks() [5/5]
bool BlockRestrictable::hasBlocks (SubdomainID id) const inherited
Test if the supplied block ids are valid for this object.
Parameters
id A SubdomainID to check
Returns
True if the given id is valid for this object
Definition at line 221 of file BlockRestrictable.C.
{
  if (_blk_ids.empty() || _blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return true;
  else
    return _blk_ids.find(id) != _blk_ids.end();
}
hasGenericMaterialProperty()
template<typename T , bool is_ad> bool MaterialPropertyInterface::hasGenericMaterialProperty (const std::string & name) inline inherited
generic hasMaterialProperty helper
Definition at line 289 of file MaterialPropertyInterface.h.
  {
    if constexpr (is_ad)
      return hasADMaterialProperty<T>(name);
    else
      return hasMaterialProperty<T>(name);
  }
hasGenericMaterialPropertyByName()
template<typename T , bool is_ad> bool MaterialPropertyInterface::hasGenericMaterialPropertyByName (const std::string & name) inline inherited
Definition at line 297 of file MaterialPropertyInterface.h.
  {
    if constexpr (is_ad)
      return hasADMaterialPropertyByName<T>(name);
    else
      return hasMaterialPropertyByName<T>(name);
  }
hasMaterialProperty()
template<typename T > bool MaterialPropertyInterface::hasMaterialProperty (const std::string & name) inherited
Check if the material property exists.
Parameters
name the name of the property to query
Returns
true if the property exists, otherwise false
Definition at line 662 of file MaterialPropertyInterface.h.
{
  // Check if the supplied parameter is a valid input parameter key
  const auto prop_name = getMaterialPropertyName(name);
  return hasMaterialPropertyByName<T>(prop_name);
}
hasMaterialPropertyByName()
template<typename T > bool MaterialPropertyInterface::hasMaterialPropertyByName (const std::string & name) inherited
Definition at line 671 of file MaterialPropertyInterface.h.
{
  const auto name = _get_suffix.empty()
                        ? name_in
                        : MooseUtils::join(std::vector<std::string>({name_in, _get_suffix}), "_");
  return _material_data.haveProperty<T>(name);
}
hasPostprocessor()
bool PostprocessorInterface::hasPostprocessor (const std::string & param_name, const unsigned int index = 0) const inherited
Determine if the Postprocessor data exists.
Parameters
param_name The name of the Postprocessor parameter
index The index of the Postprocessor
Returns
True if the Postprocessor exists
See also
hasPostprocessorByName getPostprocessorValue
Definition at line 107 of file PostprocessorInterface.C.
{
  if (!postprocessorsAdded())
    _ppi_moose_object.mooseError(
        "Cannot call hasPostprocessor() until all Postprocessors have been constructed.");
  return hasPostprocessorByName(getPostprocessorNameInternal(param_name, index));
}
hasPostprocessorByName()
bool PostprocessorInterface::hasPostprocessorByName (const PostprocessorName & name) const inherited
Determine if the Postprocessor data exists.
Parameters
name The name of the Postprocessor
Returns
True if the Postprocessor exists
See also
hasPostprocessor getPostprocessorValueByName
Definition at line 118 of file PostprocessorInterface.C.
{
  if (!postprocessorsAdded())
    _ppi_moose_object.mooseError(
        "Cannot call hasPostprocessorByName() until all Postprocessors have been constructed.");
  return _ppi_feproblem.getReporterData().hasReporterValue<PostprocessorValue>(
      PostprocessorReporterName(name));
}
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), AdvancedOutput::initShowHideLists(), Exodus::outputReporters(), and TableOutput::outputReporters().
hasUserObject() [1/2]
bool UserObjectInterface::hasUserObject (const std::string & param_name) const inherited
Returns
Whether or not a UserObject exists with the name given by the parameter param_name.
Definition at line 67 of file UserObjectInterface.C.
{
  return hasUserObjectByName(getUserObjectName(param_name));
}
hasUserObject() [2/2]
template<class T > bool UserObjectInterface::hasUserObject (const std::string & param_name) const inherited
Definition at line 175 of file UserObjectInterface.h.
{
  return hasUserObjectByName<T>(getUserObjectName(param_name));
}
hasUserObjectByName() [1/2]
bool UserObjectInterface::hasUserObjectByName (const UserObjectName & object_name) const inherited
Definition at line 73 of file UserObjectInterface.C.
{
  return _uoi_feproblem.hasUserObject(object_name);
}
Referenced by UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::hasUserObject(), and UserObjectInterface::hasUserObjectByName().
hasUserObjectByName() [2/2]
template<class T > bool UserObjectInterface::hasUserObjectByName (const UserObjectName & object_name) const inherited
Definition at line 182 of file UserObjectInterface.h.
{
  if (!hasUserObjectByName(object_name))
    return false;
  return dynamic_cast<const T *>(&_uoi_feproblem.getUserObjectBase(object_name));
}
initializeBlockRestrictable()
void BlockRestrictable::initializeBlockRestrictable (const MooseObject * moose_object) protected inherited
An initialization routine needed for dual constructors.
Definition at line 74 of file BlockRestrictable.C.
{
  // If the mesh pointer is not defined, but FEProblemBase is, get it from there
  if (_blk_feproblem != NULL && _blk_mesh == NULL)
    _blk_mesh = &_blk_feproblem->mesh();
  // Check that the mesh pointer was defined, it is required for this class to operate
  if (_blk_mesh == NULL)
    mooseError("The input parameters must contain a pointer to FEProblem via '_fe_problem' or a "
               "pointer to the MooseMesh via '_mesh'");
  // Populate the MaterialData pointer
  if (_blk_feproblem != NULL)
    _blk_material_data = &_blk_feproblem->getMaterialData(Moose::BLOCK_MATERIAL_DATA, _blk_tid);
  // The 'block' input is defined
  if (moose_object->isParamValid("block"))
  {
    // Extract the blocks from the input
    _blocks = moose_object->getParam<std::vector<SubdomainName>>("block");
    // Store the IDs in a set, handling ANY_BLOCK_ID if supplied
    if (std::find(_blocks.begin(), _blocks.end(), "ANY_BLOCK_ID") != _blocks.end())
      _blk_ids.insert(Moose::ANY_BLOCK_ID);
    else
    {
      // Get the IDs from the supplied names
      _vec_ids = _blk_mesh->getSubdomainIDs(_blocks);
      _blk_ids.insert(_vec_ids.begin(), _vec_ids.end());
    }
  }
  // When 'blocks' is not set and there is a "variable", use the blocks from the variable
  else if (moose_object->isParamValid("variable"))
  {
    std::string variable_name = moose_object->parameters().getMooseType("variable");
    if (!variable_name.empty())
      _blk_ids = _blk_feproblem
                     ->getVariable(_blk_tid,
                                   variable_name,
                                   Moose::VarKindType::VAR_ANY,
                                   Moose::VarFieldType::VAR_FIELD_ANY)
                     .activeSubdomains();
  }
  // Produce error if the object is not allowed to be both block and boundary restricted
  if (!_blk_dual_restrictable && !_boundary_ids.empty() && !_boundary_ids.empty())
    if (!_boundary_ids.empty() && _boundary_ids.find(Moose::ANY_BOUNDARY_ID) == _boundary_ids.end())
      moose_object->paramError("block",
                               "Attempted to restrict the object '",
                               _blk_name,
                               "' to a block, but the object is already restricted by boundary");
  // If no blocks were defined above, specify that it is valid on all blocks
  if (_blk_ids.empty() && !moose_object->isParamValid("boundary"))
  {
    _blk_ids.insert(Moose::ANY_BLOCK_ID);
    _blocks = {"ANY_BLOCK_ID"};
  }
  // If this object is block restricted, check that defined blocks exist on the mesh
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) == _blk_ids.end())
  {
    const std::set<SubdomainID> & valid_ids = _blk_mesh->meshSubdomains();
    std::vector<SubdomainID> diff;
    std::set_difference(_blk_ids.begin(),
                        _blk_ids.end(),
                        valid_ids.begin(),
                        valid_ids.end(),
                        std::back_inserter(diff));
    if (!diff.empty())
    {
      std::ostringstream msg;
      auto sep = " ";
      msg << "the following blocks (ids) do not exist on the mesh:";
      for (const auto & id : diff)
      {
        if (_blk_name.size() > 0)
        {
          auto & name =
              _blocks.at(std::find(_vec_ids.begin(), _vec_ids.end(), id) - _vec_ids.begin());
          if (std::to_string(id) != name)
            msg << sep << name << " (" << id << ")";
          else
            msg << sep << id;
        }
        else
          msg << sep << id;
        sep = ", ";
      }
      moose_object->paramError("block", msg.str());
    }
  }
  // Get the mesh dimension for the blocks
  if (blockRestricted())
    _blk_dim = _blk_mesh->getBlocksMaxDimension(_blocks);
  else
    _blk_dim = _blk_mesh->dimension();
}
Referenced by BlockRestrictable::BlockRestrictable().
initialSetup()
void SetupInterface::initialSetup () virtual inherited
Gets called at the beginning of the simulation before this object is asked to do its job.
Reimplemented in DerivativeSumMaterialTempl< is_ad >, AdvancedOutput, MultiAppFieldTransfer, Transfer, MortarNodalAuxKernelTempl< ComputeValueType >, ProjectedStatefulMaterialAuxTempl< T, is_ad >, SolutionAux, SolutionScalarAux, TimePeriod, Axisymmetric2D3DSolutionFunction, CoarsenedPiecewiseLinear, ImageFunction, MooseParsedFunction, MooseParsedGradFunction, MooseParsedVectorFunction, PiecewiseConstantFromCSV, PiecewiseLinear, PiecewiseLinearBase, PiecewiseTabularBase, SolutionFunction, LibtorchControlValuePostprocessor, LibtorchArtificialNeuralNetParameters, DerivativeFunctionMaterialBaseTempl< is_ad >, DerivativeFunctionMaterialBaseTempl< is_ad >, FullSolveMultiApp, MultiApp, TransientMultiApp, Console, CSV, Exodus, Nemesis, OversampleOutput, NodalVariableValue, SideIntegralMaterialPropertyTempl< is_ad >, MultiAppCloneReporterTransfer, MultiAppConservativeTransfer, MultiAppDofCopyTransfer, MultiAppGeneralFieldNearestLocationTransfer, MultiAppGeneralFieldTransfer, MultiAppProjectionTransfer, MultiAppReporterTransfer, MultiAppTransfer, MultiAppVariableValueSamplePostprocessorTransfer, MultiAppVariableValueSampleTransfer, ElementSubdomainModifier, GhostingUserObject, InterfaceQpUserObjectBase, NodalPatchRecoveryMaterialProperty, ProjectedStatefulMaterialNodalPatchRecoveryTempl< T, is_ad >, RadialAverage, SolutionUserObject, Terminator, MooseVariableBase, HistogramVectorPostprocessor, and DGFunctionTemperatureAdvection.
Definition at line 40 of file SetupInterface.C.
{
}
Referenced by LibtorchControlValuePostprocessor::initialSetup(), Console::initialSetup(), CSV::initialSetup(), and Positions::meshChanged().
isActive()
bool Marker::isActive () const inherited
Definition at line 90 of file Marker.C.
{
  return true;
}
isBlockSubset() [1/2]
bool BlockRestrictable::isBlockSubset (const std::set< SubdomainID > & ids) const inherited
Test if the class block ids are a subset of the supplied objects.
Parameters
ids A std::set of Subdomains to check
Returns
True if all of the block ids for this class are found within the given ids (opposite of hasBlocks)
See also
hasBlocks
Definition at line 246 of file BlockRestrictable.C.
{
  // An empty input is assumed to be ANY_BLOCK_ID
  if (ids.empty() || ids.find(Moose::ANY_BLOCK_ID) != ids.end())
    return true;
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return std::includes(ids.begin(),
                         ids.end(),
                         _blk_mesh->meshSubdomains().begin(),
                         _blk_mesh->meshSubdomains().end());
  else
    return std::includes(ids.begin(), ids.end(), _blk_ids.begin(), _blk_ids.end());
}
Referenced by BlockRestrictable::checkVariable(), BlockRestrictable::isBlockSubset(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), and ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux().
isBlockSubset() [2/2]
bool BlockRestrictable::isBlockSubset (const std::vector< SubdomainID > & ids) const inherited
Test if the class block ids are a subset of the supplied objects.
Parameters
ids A std::vector of Subdomains to check
Returns
True if all of the block ids for this class are found within the given ids (opposite of hasBlocks)
See also
hasBlocks
Definition at line 262 of file BlockRestrictable.C.
{
  std::set<SubdomainID> ids_set(ids.begin(), ids.end());
  return isBlockSubset(ids_set);
}
isDefaultPostprocessorValue()
bool PostprocessorInterface::isDefaultPostprocessorValue (const std::string & param_name, const unsigned int index = 0) const inherited
Determine whether or not the Postprocessor is a default value.
A default value is when the value is either the value set by addParam, or is a user-set value in input instead of a name to a postprocessor.
Parameters
param_name The name of the Postprocessor parameter
index The index of the postprocessor
Returns
True if the Postprocessor is a default value, false if the Postprocessor is the name of a Postprocessor
Definition at line 75 of file PostprocessorInterface.C.
{
  return isDefaultPostprocessorValueByName(getPostprocessorNameInternal(param_name, index));
}
Referenced by EigenKernel::EigenKernel().
isDefaultPostprocessorValueByName()
bool PostprocessorInterface::isDefaultPostprocessorValueByName (const PostprocessorName & name) const private inherited
Returns
True if the PostprocessorName name repesents a default value: the name converts to a value (set by addParam or set via input), and a Postprocessor does not exist with the same name (we do allow Postprocessors with numbered names...)
Definition at line 82 of file PostprocessorInterface.C.
{
  // We do allow actual Postprocessor objects to have names that will succeed in being
  // represented as a double... so if the name does actually exist as a PP, it's not a default
  if (_ppi_feproblem.getReporterData().hasReporterValue<PostprocessorValue>(
          PostprocessorReporterName(name)))
    return false;
  std::istringstream ss(name);
  Real real_value = -std::numeric_limits<Real>::max();
  return (ss >> real_value && ss.eof());
}
Referenced by PostprocessorInterface::getDefaultPostprocessorValueByName(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), and PostprocessorInterface::isDefaultPostprocessorValue().
isParamSetByUser()
bool MooseBaseParameterInterface::isParamSetByUser (const std::string & nm) const inline inherited
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
Parameters
nm The name of the parameter to test
Definition at line 108 of file MooseBaseParameterInterface.h.
{ return _pars.isParamSetByUser(nm); }
Referenced by SetAdaptivityOptionsAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), LibtorchNeuralNetControl::conditionalParameterError(), MooseBaseParameterInterface::getRenamedParam(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), PiecewiseTabularBase::PiecewiseTabularBase(), MooseMesh::prepare(), and SolutionUserObject::readXda().
isParamValid()
bool MooseBaseParameterInterface::isParamValid (const std::string & name) const inline inherited
Test if the supplied parameter is valid.
Parameters
name The name of the parameter to test
Definition at line 102 of file MooseBaseParameterInterface.h.
{ return _pars.isParamValid(name); }
Referenced by AddDriftDiffusionAction::act(), AddSpecies::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CopyNodalVarsAction::act(), CreateDisplacedProblemAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), AddGeneralReactions::AddGeneralReactions(), AddZapdosReactions::AddZapdosReactions(), AdvectiveFluxAux::AdvectiveFluxAux(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), GeneratedMesh::buildMesh(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), ChemicalReactionsBase::ChemicalReactionsBase(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), CombinerGenerator::CombinerGenerator(), CSVReader::CSVReader(), ConstantReporter::declareConstantReporterValues(), DGKernelBase::DGKernelBase(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EEDFEnergyTownsendLog::EEDFEnergyTownsendLog(), Eigenvalue::Eigenvalue(), ElectronEnergyTermRate::ElectronEnergyTermRate(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), PIDTransientControl::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FileOutput::FileOutput(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FunctionDT::FunctionDT(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getRenamedParam(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), Terminator::handleMessage(), HeavySpeciesTempl< is_ad >::HeavySpeciesTempl(), HFEMDirichletBC::HFEMDirichletBC(), EigenExecutionerBase::init(), Eigenvalue::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), MooseParsedFunction::initialSetup(), MooseParsedGradFunction::initialSetup(), MooseParsedVectorFunction::initialSetup(), PiecewiseTabularBase::initialSetup(), SolutionFunction::initialSetup(), Console::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), IterationAdaptiveDT::IterationAdaptiveDT(), LeastSquaresFit::LeastSquaresFit(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MatCoupledForce::MatCoupledForce(), MooseMesh::MooseMesh(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarConsumerInterface::MortarConsumerInterface(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalExtremeValue::NodalExtremeValue(), EigenExecutionerBase::normalizeSolution(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PetscOutput::PetscOutput(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), PicardSolve::PicardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseTabularBase::PiecewiseTabularBase(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), MooseMesh::prepare(), MultiApp::readCommandLineArguments(), SolutionUserObject::readExodusII(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), MooseMesh::setCoordSystem(), FileOutput::setFileBase(), FileOutput::setFileBaseInternal(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SideDiffusiveFluxIntegralTempl< is_ad, T >::SideDiffusiveFluxIntegralTempl(), SideExtremeValue::SideExtremeValue(), SolutionUserObject::SolutionUserObject(), Terminator::Terminator(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), MultiAppDofCopyTransfer::transfer(), TransformGenerator::TransformGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
jacobianSetup()
void SetupInterface::jacobianSetup () virtual inherited
Gets called just before the Jacobian is computed and before this object is asked to do its job.
Reimplemented in EqualValueEmbeddedConstraint, Function, ADKernelTempl< T >, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 50 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::jacobianSetup(), and ComputeFVFluxJacobianThread< RangeType >::setup().
markerSetup()
void Marker::markerSetup () virtual inherited
Is called before any element looping is started so any "global" computation can be done.
Reimplemented in ErrorFractionMarker, and ReporterPointMarker.
Definition at line 96 of file Marker.C.
{
}
markerStates()
MooseEnum Marker::markerStates () static inherited
Helper function for getting the valid refinement flag states a marker can use as a MooseEnum.
Returns
A MooseEnum that is filled with the valid states. These are perfectly transferable to libMesh Elem::RefinementStates.
Definition at line 62 of file Marker.C.
{
  MooseEnum marker_states("DONT_MARK=-1 COARSEN DO_NOTHING REFINE");
  return marker_states;
}
Referenced by BoundaryMarker::validParams(), BoxMarker::validParams(), OrientedBoxMarker::validParams(), ReporterPointMarker::validParams(), and UniformMarker::validParams().
markMatPropRequested()
void MaterialPropertyInterface::markMatPropRequested (const std::string & name) protected inherited
A proxy method for _mi_feproblem.markMatPropRequested(name)
Definition at line 135 of file MaterialPropertyInterface.C.
{
  _mi_feproblem.markMatPropRequested(name);
}
Referenced by MaterialPropertyInterface::getGenericMaterialPropertyByName().
meshBlockIDs()
const std::set< SubdomainID > & BlockRestrictable::meshBlockIDs () const inherited
Return all of the SubdomainIDs for the mesh.
Returns
A set of all subdomians for the entire mesh
Definition at line 269 of file BlockRestrictable.C.
{
  return _blk_mesh->meshSubdomains();
}
Referenced by BlockRestrictable::checkVariable(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), and SolutionIC::initialSetup().
meshChanged()
virtual void MeshChangedInterface::meshChanged () inline virtual inherited
Called on this object when the mesh changes.
Reimplemented in GeometryBase, EqualValueBoundaryConstraint, DiracKernelBase, FVPointValueConstraint, MeshDivision, Console, Exodus, Nemesis, OversampleOutput, Positions, ExplicitTimeIntegrator, MultiAppVariableValueSamplePostprocessorTransfer, GhostingUserObject, NearestNodeNumberUO, RadialAverage, MooseVariableDataFV< OutputType >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 34 of file MeshChangedInterface.h.
{}
Referenced by MooseVariableFE< OutputType >::meshChanged(), and MooseVariableFV< OutputType >::meshChanged().
mooseDeprecated()
template<typename... Args> void MooseBaseErrorInterface::mooseDeprecated (Args &&... args) const inline inherited
Definition at line 78 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseDeprecatedStream(_console, false, true, std::forward<Args>(args)...);
  }
Referenced by FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::advanceMultiApps(), MultiApp::appProblem(), Executioner::augmentedPicardConvergenceCheck(), MooseMesh::buildSideList(), FEProblemBase::computeResidual(), AddVariableAction::determineType(), Eigenvalue::Eigenvalue(), MooseMesh::elem(), FunctionDT::FunctionDT(), RandomICBase::generateRandom(), MooseMesh::getBoundariesToElems(), Control::getExecuteOptions(), FEProblemBase::getNonlinearSystem(), FEProblemBase::getUserObjects(), FEProblemBase::hasPostprocessor(), MooseMesh::node(), FixedPointSolve::numPicardIts(), RelationshipManager::operator>=(), Executioner::picardSolve(), and MooseMesh::setBoundaryToNormalMap().
mooseError()
template<typename... Args> void MooseBaseErrorInterface::mooseError (Args &&... args) const inline inherited
Emits an error prefixed with object name and type.
Definition at line 38 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, errorPrefix("error"), std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
Referenced by HierarchicalGridPartitioner::_do_partition(), PetscExternalPartitioner::_do_partition(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AdaptivityAction::act(), AddFVICAction::act(), AddICAction::act(), AddMeshGeneratorAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVectorPostprocessorAction::act(), CheckFVBCAction::act(), CheckIntegrityAction::act(), CommonOutputAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DeprecatedBlockAction::act(), InitProblemAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetAdaptivityOptionsAction::act(), SetupMeshAction::act(), SetupMeshCompleteAction::act(), SetupPredictorAction::act(), SetupTimeStepperAction::act(), SplitMeshAction::act(), FEProblemBase::adaptMesh(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::addConstraint(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFVInitialCondition(), AddGeneralReactions::AddGeneralReactions(), FEProblemBase::addInitialCondition(), FEProblemBase::addLineSearch(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addOutput(), SubProblem::addPiecewiseByBlockLambdaFunctor(), DistributedRectilinearMeshGenerator::addPoint(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), FEProblemBase::addPostprocessor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseMesh::addQuadratureNode(), FEProblemBase::addReporter(), AddVariableAction::addVariable(), FEProblemBase::addVectorPostprocessor(), SubProblem::addVectorTag(), AddZapdosReactions::AddZapdosReactions(), ADEEDFRateConstantTownsend::ADEEDFRateConstantTownsend(), ADGasElectronMoments::ADGasElectronMoments(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), MooseVariableScalar::adUDot(), Output::advancedExecuteOn(), AdvectiveFluxAux::AdvectiveFluxAux(), ADZapdosEEDFRateConstant::ADZapdosEEDFRateConstant(), MooseVariableBase::allDofIndices(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayConstantIC::ArrayConstantIC(), ArrayFunctionIC::ArrayFunctionIC(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), Function::average(), Axisymmetric2D3DSolutionFunction::Axisymmetric2D3DSolutionFunction(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), BoltzmannSolverScalar::BoltzmannSolverScalar(), BoundingValueElementDamper::BoundingValueElementDamper(), BoundingValueNodalDamper::BoundingValueNodalDamper(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), MooseMesh::buildCoarseningMap(), MultiApp::buildComm(), DistributedRectilinearMeshGenerator::buildCube(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), PiecewiseTabularBase::buildFromXY(), MooseMesh::buildLowerDMesh(), GeneratedMesh::buildMesh(), MeshGeneratorMesh::buildMesh(), SpiralAnnularMesh::buildMesh(), TiledMesh::buildMesh(), ImageMesh::buildMesh3D(), ImageMeshGenerator::buildMesh3D(), MooseMesh::buildRefinementMap(), MaterialBase::buildRequiredMaterials(), MooseMesh::buildSideList(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), UserObjectInterface::castUserObject(), EigenExecutionerBase::chebyshev(), SubProblem::checkBlockMatProps(), SubProblem::checkBoundaryMatProps(), MooseMesh::checkCoordinateSystems(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkDisplacementOrders(), FEProblemBase::checkDuplicatePostprocessorVariableNames(), MooseMesh::checkDuplicateSubdomainNames(), MaterialBase::checkExecutionStage(), MeshGenerator::checkGetMesh(), ReporterTransferInterface::checkHasReporterValue(), FEProblemBase::checkICRestartError(), EigenExecutionerBase::checkIntegrity(), Eigenvalue::checkIntegrity(), Steady::checkIntegrity(), ExplicitTimeIntegrator::checkLinearConvergence(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), PostprocessorInterface::checkParam(), FEProblemBase::checkProblemIntegrity(), Sampler::checkReinitStatus(), MaterialBase::checkStatefulSanity(), FEProblemBase::checkUserObjects(), MultiAppTransfer::checkVariable(), DomainUserObject::checkVariable(), ChemicalReactionsBase::ChemicalReactionsBase(), MooseMesh::clone(), LibmeshPartitioner::clone(), CombinerGenerator::CombinerGenerator(), ElementSubdomainModifier::complementMovingBoundaryID(), ElementSubdomainModifier::complementMovingBoundaryName(), MooseVariableFieldBase::componentName(), CompositeFunction::CompositeFunction(), NodalPatchRecovery::compute(), VariableCondensationPreconditioner::computeDInverseDiag(), CompositionDT::computeDT(), MooseVariableFieldBase::computeFaceValues(), TimeStepper::computeFailedDT(), IterationAdaptiveDT::computeFailedDT(), TimeSequenceStepperBase::computeFailedDT(), MooseMesh::computeFiniteVolumeCoords(), FVFluxKernel::computeJacobian(), ArrayKernel::computeJacobian(), ArrayKernel::computeOffDiagJacobian(), FVElementalKernel::computeOffDiagJacobian(), MaterialBase::computeProperties(), ScalarKernel::computeQpJacobian(), ScalarKernel::computeQpResidual(), FVFluxKernel::computeResidual(), ArrayKernel::computeResidual(), FVFluxBC::computeResidual(), ResidualObject::computeResidualAndJacobian(), FVFluxKernel::computeResidualAndJacobian(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualL2Norm(), FEProblemBase::computeResidualTag(), FEProblemBase::computeResidualType(), TimeStepper::computeStep(), ActuallyExplicitEuler::computeTimeDerivatives(), AStableDirk4::computeTimeDerivatives(), BDF2::computeTimeDerivatives(), CrankNicolson::computeTimeDerivatives(), ExplicitEuler::computeTimeDerivatives(), ExplicitRK2::computeTimeDerivatives(), ExplicitTVDRK2::computeTimeDerivatives(), ImplicitEuler::computeTimeDerivatives(), ImplicitMidpoint::computeTimeDerivatives(), LStableDirk2::computeTimeDerivatives(), LStableDirk3::computeTimeDerivatives(), LStableDirk4::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), FEProblemBase::computeUserObjectsInternal(), BolsigValueScalar::computeValue(), PenetrationAux::computeValue(), BuildArrayVariableAux::computeValue(), TagVectorArrayVariableAux::computeValue(), ConcentricCircleMesh::ConcentricCircleMesh(), ConditionalEnableControl::ConditionalEnableControl(), TimeStepper::constrainStep(), LibtorchNeuralNetControl::controlNeuralNet(), AddVariableAction::createInitialConditionAction(), DataRead::DataRead(), ReporterTransferInterface::declareClone(), MeshGenerator::declareMeshProperty(), ReporterTransferInterface::declareVectorClone(), FunctorRelationshipManager::delete_remote_elements(), MooseMesh::deleteRemoteElements(), BicubicSplineFunction::derivative(), MooseMesh::detectPairedSidesets(), FEProblemBase::determineNonlinearSystem(), MeshDiagnosticsGenerator::diagnosticsLog(), DiffusionRateTemp::DiffusionRateTemp(), FunctorBinnedValuesDivision::divisionIndex(), FunctorRelationshipManager::dofmap_reinit(), FEProblemBase::duplicateVariableCheck(), EEDFRateConstant::EEDFRateConstant(), EEDFRateConstantTownsend::EEDFRateConstantTownsend(), Eigenvalue::Eigenvalue(), ElectricField::ElectricField(), ElectronMobility::ElectronMobility(), ElementIntegerAux::ElementIntegerAux(), ElementQualityAux::ElementQualityAux(), ElementUOAux::ElementUOAux(), DistributedRectilinearMeshGenerator::elemId(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), MooseMesh::errorIfDistributedMesh(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), BoltzmannSolverScalar::execute(), Eigenvalue::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), ElementQualityChecker::execute(), DiscreteElementUserObject::execute(), DomainUserObject::execute(), FEProblemBase::execute(), FEProblemBase::executeControls(), MultiAppVectorPostprocessorTransfer::executeFromMultiapp(), MultiAppVectorPostprocessorTransfer::executeToMultiapp(), ExplicitSSPRungeKutta::ExplicitSSPRungeKutta(), FileOutput::FileOutput(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), ElementQualityChecker::finalize(), VerifyElementUniqueID::finalize(), VerifyNodalUniqueID::finalize(), DiscreteElementUserObject::finalize(), Transfer::find_sys(), BreakMeshByBlockGeneratorBase::findFreeBoundaryId(), FunctionDT::FunctionDT(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), GapValueAux::GapValueAux(), Gas::Gas(), GasBase::GasBase(), GasElectronMoments::GasElectronMoments(), AllSideSetsByNormalsGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundingBoxNodeSetGenerator::generate(), BreakMeshByBlockGenerator::generate(), CombinerGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshCollectionGenerator::generate(), MeshDiagnosticsGenerator::generate(), MeshExtruderGenerator::generate(), MeshRepairGenerator::generate(), MoveNodeGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), SideSetsFromNormalsGenerator::generate(), SideSetsFromPointsGenerator::generate(), SmoothMeshGenerator::generate(), SpiralAnnularMeshGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), TiledMeshGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GeneratedMesh::GeneratedMesh(), GeneratedMeshGenerator::GeneratedMeshGenerator(), MeshGenerator::generateInternal(), CircularBoundaryCorrectionGenerator::generateRadialCorrectionFactor(), RandomICBase::generateRandom(), GenericConstantMaterialTempl< is_ad >::GenericConstantMaterialTempl(), GenericConstantVectorMaterialTempl< is_ad >::GenericConstantVectorMaterialTempl(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), DisplacedProblem::getActualFieldVariable(), FEProblemBase::getActualFieldVariable(), DisplacedProblem::getArrayVariable(), FEProblemBase::getArrayVariable(), MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::getBlockConnectedBlocks(), VariableOldValueBoundsAux::getBound(), MooseMesh::getBoundaryID(), MultiApp::getBoundingBox(), MooseMesh::getCoarseningMap(), MooseVariableBase::getContinuity(), Control::getControllableParameterByName(), MooseMesh::getCoordSystem(), PropertyReadFile::getData(), TransfiniteMeshGenerator::getDiscreteEdge(), FEProblemBase::getDistribution(), MooseVariableBase::getDofIndices(), VariableCondensationPreconditioner::getDofToCondense(), TransfiniteMeshGenerator::getEdge(), GhostingUserObject::getElementalValue(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), PropertyReadFile::getElementData(), MooseMesh::getElementIDIndex(), Material::getElementIDNeighbor(), Material::getElementIDNeighborByName(), MooseMesh::getElemIDMapping(), MooseMesh::getElemIDsOnBlocks(), MultiAppFieldTransfer::getEquationSystem(), MultiApp::getExecutioner(), MultiAppTransfer::getFromMultiApp(), MultiAppTransfer::getFromMultiAppInfo(), FEProblemBase::getFunction(), SubProblem::getFunctor(), MooseMesh::getGeneralAxisymmetricCoordAxis(), DistributedRectilinearMeshGenerator::getGhostNeighbors(), BatchMaterial< Tuple, Output, Input >::getIndex(), DistributedRectilinearMeshGenerator::getIndices(), SolutionUserObject::getLocalVarIndex(), Material::getMaterialByName(), FEProblemBase::getMaterialData(), SubProblem::getMatrixTagID(), AnnularMesh::getMaxInDimension(), GeneratedMesh::getMaxInDimension(), FEProblemBase::getMaxQps(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), AnnularMesh::getMinInDimension(), GeneratedMesh::getMinInDimension(), MultiAppTransfer::getMultiApp(), DistributedRectilinearMeshGenerator::getNeighbors(), MooseMesh::getNodeBlockIds(), PropertyReadFile::getNodeData(), MooseMesh::getNodeList(), FEProblemBase::getNonlinearSystem(), MooseMesh::getPairedBoundaryMapping(), ImageMesh::GetPixelInfo(), ImageMeshGenerator::GetPixelInfo(), PlaneIDMeshGenerator::getPlaneID(), FEProblemBase::getPositionsObject(), PostprocessorInterface::getPostprocessorValueByNameInternal(), MooseMesh::getRefinementMap(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), FEProblemBase::getSampler(), JSONFileReader::getScalar(), DisplacedProblem::getScalarVariable(), FEProblemBase::getScalarVariable(), DisplacedProblem::getStandardVariable(), FEProblemBase::getStandardVariable(), MooseMesh::getSubdomainBoundaryIds(), DisplacedProblem::getSystem(), FEProblemBase::getSystem(), FEProblemBase::getTimeFromStateArg(), Transient::getTimeIntegratorName(), MultiAppTransfer::getToMultiApp(), MultiAppTransfer::getToMultiAppInfo(), MooseMesh::getUniqueCoordSystem(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::getUserObjectName(), JSONFileReader::getVector(), VectorPostprocessorInterface::getVectorPostprocessorName(), SubProblem::getVectorTag(), SubProblem::getVectorTagID(), DisplacedProblem::getVectorVariable(), FEProblemBase::getVectorVariable(), GhostingAux::GhostingAux(), MultiApp::globalAppToLocal(), Function::gradient(), MooseParsedVectorFunction::gradient(), Terminator::handleMessage(), MooseVariableBase::hasDoFsOnNodes(), PostprocessorInterface::hasPostprocessor(), PostprocessorInterface::hasPostprocessorByName(), ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), AddVariableAction::init(), MooseMesh::init(), Sampler::init(), AddAuxVariableAction::init(), EigenExecutionerBase::init(), Eigenvalue::init(), Transient::init(), FEProblemBase::init(), CrankNicolson::init(), ExplicitTimeIntegrator::init(), CSVTimeSequenceStepper::init(), IterationAdaptiveDT::init(), MultiApp::init(), FEProblemBase::initialAdaptMesh(), BoltzmannSolverScalar::initialize(), PolynomialCoefficients::initialize(), CartesianGridDivision::initialize(), CylindricalGridDivision::initialize(), NestedDivision::initialize(), SphericalGridDivision::initialize(), SubProblem::initialSetup(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), Axisymmetric2D3DSolutionFunction::initialSetup(), MooseParsedFunction::initialSetup(), SolutionFunction::initialSetup(), SolutionIC::initialSetup(), FullSolveMultiApp::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), SolutionUserObject::initialSetup(), Function::integral(), InterpolatedCoefficientLinear::InterpolatedCoefficientLinear(), InterpolatedCoefficientSpline::InterpolatedCoefficientSpline(), EigenExecutionerBase::inversePowerIteration(), InversePowerMethod::InversePowerMethod(), Sampler::isAdaptiveSamplingCompleted(), MooseMesh::isBoundaryFullyExternalToSubdomains(), MooseVariableBase::isNodal(), IterationAdaptiveDT::IterationAdaptiveDT(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LineSearch::lineSearch(), ReporterPointMarker::markerSetup(), Material::Material(), MaterialOutputAction::materialOutputHelper(), MaterialRealTensorValueAux::MaterialRealTensorValueAux(), MaterialRealVectorValueAuxTempl< is_ad >::MaterialRealVectorValueAuxTempl(), Distribution::median(), FunctorRelationshipManager::mesh_reinit(), SubProblem::meshChanged(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshExtruderGenerator::MeshExtruderGenerator(), MeshRepairGenerator::MeshRepairGenerator(), SetupMeshAction::modifyParamsForUseSplit(), MeshMetaDataInterface::mooseErrorInternal(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MoveNodeGenerator::MoveNodeGenerator(), ElementSubdomainModifier::movingBoundaryID(), ElementSubdomainModifier::movingBoundaryName(), MultiApp::MultiApp(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NearestNodeDistanceAux::NearestNodeDistanceAux(), NearestNodeValueAux::NearestNodeValueAux(), FEProblemBase::needsPreviousNewtonIteration(), NewmarkBeta::NewmarkBeta(), NodalPatchRecoveryBase::nodalPatchRecovery(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), DistributedRectilinearMeshGenerator::nodeId(), DistributedRectilinearMeshGenerator::numNeighbors(), Output::onInterval(), FunctorRelationshipManager::operator()(), RelationshipManager::operator==(), MortarNodalGeometryOutput::output(), Output::Output(), DistributedRectilinearMeshGenerator::paritionSquarely(), PiecewiseBilinear::parse(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), ExplicitTimeIntegrator::performExplicitSolve(), PetscExternalPartitioner::PetscExternalPartitioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), Executioner::picardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseMulticonstant::PiecewiseMulticonstant(), PiecewiseTabularBase::PiecewiseTabularBase(), SolutionUserObject::pointValueGradientWrapper(), SolutionUserObject::pointValueWrapper(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName(), AStableDirk4::postResidual(), ExplicitRK2::postResidual(), ExplicitTVDRK2::postResidual(), ImplicitMidpoint::postResidual(), LStableDirk2::postResidual(), LStableDirk3::postResidual(), LStableDirk4::postResidual(), VariableCondensationPreconditioner::preallocateCondensedJacobian(), Predictor::Predictor(), Transient::preExecute(), MooseMesh::prepare(), MooseMesh::prepared(), FixedPointSolve::printFixedPointConvergenceReason(), RateCoefficientProvider::RateCoefficientProvider(), RateCoefficientProvider::reaction_coefficient(), RateCoefficientProvider::reaction_coefficient_derivative(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readExodusII(), SolutionUserObject::readXda(), FunctorRelationshipManager::redistribute(), Sampler::reinit(), RinglebMesh::RinglebMesh(), RinglebMeshGenerator::RinglebMeshGenerator(), PiecewiseMultiInterpolation::sample(), ScalarComponentIC::ScalarComponentIC(), ScalarLinearInterpolation::ScalarLinearInterpolation(), ScalarSplineInterpolation::ScalarSplineInterpolation(), DistributedRectilinearMeshGenerator::scaleNodalPositions(), BicubicSplineFunction::secondDerivative(), FunctorRelationshipManager::set_mesh(), MooseVariableBase::setActiveTags(), DistributedRectilinearMeshGenerator::setBoundaryNames(), MooseMesh::setCoordSystem(), FEProblemBase::setCoupling(), PiecewiseBase::setData(), FileOutput::setFileBaseInternal(), MooseMesh::setGeneralAxisymmetricCoordAxes(), FEProblemSolve::setInnerSolve(), MeshGenerator::setMeshProperty(), FEProblemBase::setNonlocalCouplingMatrix(), Sampler::setNumberOfCols(), Sampler::setNumberOfRandomSeeds(), Sampler::setNumberOfRows(), Split::setup(), TransientMultiApp::setupApp(), SetupMeshAction::setupMesh(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), TimePeriodBase::setupTimes(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SideSetsFromNormalsGenerator::SideSetsFromNormalsGenerator(), SideSetsFromPointsGenerator::SideSetsFromPointsGenerator(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), SolutionTimeAdaptiveDT::SolutionTimeAdaptiveDT(), SolutionUserObject::SolutionUserObject(), FullSolveMultiApp::solveStep(), UserObject::spatialPoints(), UserObject::spatialValue(), SpiralAnnularMesh::SpiralAnnularMesh(), SpiralAnnularMeshGenerator::SpiralAnnularMeshGenerator(), StitchedMesh::StitchedMesh(), MaterialBase::subdomainSetup(), GeneralUserObject::subdomainSetup(), NodalUserObject::subdomainSetup(), Constraint::subdomainSetup(), SuperelasticReactionRate::SuperelasticReactionRate(), FEProblemBase::swapBackMaterialsNeighbor(), Terminator::Terminator(), GeneralUserObject::threadJoin(), ThreadedGeneralUserObject::threadJoin(), DiscreteElementUserObject::threadJoin(), TimePeriodBase::TimePeriodBase(), VectorPostprocessorVisualizationAux::timestepSetup(), FEProblemBase::trustUserCouplingMatrix(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), FEProblemBase::uDotDotOldRequested(), MooseVariableScalar::uDotOld(), FEProblemBase::uDotOldRequested(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), SolutionUserObject::updateExodusBracketingTimeIndices(), FEProblemBase::updateMaxQps(), BoundingBoxIC::value(), Function::value(), Axisymmetric2D3DSolutionFunction::value(), PiecewiseConstantFromCSV::value(), ValueProvider::ValueProvider(), ValueRangeMarker::ValueRangeMarker(), ValueThresholdMarker::ValueThresholdMarker(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), MultiAppTransfer::variableIntegrityCheck(), VariableTimeIntegrationAux::VariableTimeIntegrationAux(), AddVariableAction::variableType(), Function::vectorCurl(), SubProblem::vectorTagName(), SubProblem::vectorTagType(), Function::vectorValue(), MooseParsedFunction::vectorValue(), MooseParsedGradFunction::vectorValue(), SubProblem::verifyVectorTags(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
mooseErrorNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseErrorNonPrefixed (Args &&... args) const inline inherited
Emits an error without the prefixing included in mooseError().
Definition at line 50 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
mooseInfo()
template<typename... Args> void MooseBaseErrorInterface::mooseInfo (Args &&... args) const inline inherited
Definition at line 84 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseInfoStream(_console, std::forward<Args>(args)...);
  }
Referenced by AddZapdosReactions::act(), SetupRecoverFileBaseAction::act(), AStableDirk4::AStableDirk4(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), BoltzmannSolverScalar::execute(), ExplicitRK2::ExplicitRK2(), ExplicitTVDRK2::ExplicitTVDRK2(), MultiAppTransfer::getPointInTargetAppFrame(), ImplicitMidpoint::ImplicitMidpoint(), InversePowerMethod::InversePowerMethod(), LStableDirk2::LStableDirk2(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), NonlinearEigen::NonlinearEigen(), ProjectionAux::ProjectionAux(), FEProblemBase::setRestartFile(), and SymmetryTransformGenerator::SymmetryTransformGenerator().
mooseVariable()
MooseVariableFE< Real > * MooseVariableInterface< Real >::mooseVariable inherited
Definition at line 55 of file MooseVariableInterface.C.
{
  if (!_variable)
    mooseError(
        "_variable is null in ", _moose_object.name(), ". Are you using a finite volume variable?");
  return _variable;
}
mooseVariableBase()
MooseVariableBase * MooseVariableInterface< Real >::mooseVariableBase () const inline inherited
Get the variable that this object is using.
Returns
The variable this object is using.
Definition at line 48 of file MooseVariableInterface.h.
{ return _var; };
mooseVariableField()
MooseVariableField< Real > & MooseVariableInterface< Real >::mooseVariableField inherited
Return the MooseVariableField<T> object that this interface acts on.
Definition at line 53 of file MooseVariableInterface.C.
{
  if (_variable)
    return *_variable;
  else
  {
    if (!_fv_variable)
      mooseError("Either _variable or _fv_variable must be non-null in MooseVariableInterface");
    return *_fv_variable;
  }
}
mooseVariableFV()
MooseVariableFV< Real > * MooseVariableInterface< Real >::mooseVariableFV inherited
Definition at line 57 of file MooseVariableInterface.C.
{
  if (!_fv_variable)
    mooseError("_fv_variable is null in ",
               _moose_object.name(),
               ". Did you forget to set fv = true in the Variables block?");
  return _fv_variable;
}
mooseWarning()
template<typename... Args> void MooseBaseErrorInterface::mooseWarning (Args &&... args) const inline inherited
Emits a warning prefixed with object name and type.
Definition at line 62 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(
        _console, errorPrefix("warning"), std::forward<Args>(args)...);
  }
Referenced by AddFunctionAction::act(), AddKernelAction::act(), CommonOutputAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupMeshAction::act(), DumpObjectsProblem::addAuxVariable(), DiracKernelBase::addPoint(), BoundaryMarker::BoundaryMarker(), BoundsAuxBase::BoundsAuxBase(), DistributedRectilinearMeshGenerator::buildCube(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), CartesianMeshGenerator::CartesianMeshGenerator(), CheckOutputAction::checkConsoleOutput(), MultiAppTransfer::checkMultiAppExecuteOn(), GapValueAux::computeValue(), MeshDiagnosticsGenerator::diagnosticsLog(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), Postprocessor::evaluateDotWarning(), ElementQualityChecker::finalize(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FixedPointSolve::FixedPointSolve(), ElementSubdomainIDGenerator::generate(), ParsedGenerateSideset::generate(), MultiAppTransfer::getAppInfo(), FunctorBinnedValuesDivision::getBinIndex(), FEProblemBase::getMaterial(), Terminator::handleMessage(), MaterialBase::initStatefulProperties(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::mesh(), NewmarkBeta::NewmarkBeta(), NodalPatchRecovery::NodalPatchRecovery(), Output::Output(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), Executioner::problem(), PropertyReadFile::readData(), TestSourceStepper::rejectStep(), MaterialBase::resetQpProperties(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setCoordSystem(), FEProblemBase::sizeZeroes(), TransientMultiApp::solveStep(), TimeDerivativeAux::TimeDerivativeAux(), PiecewiseConstantFromCSV::value(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
mooseWarningNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseWarningNonPrefixed (Args &&... args) const inline inherited
Emits a warning without the prefixing included in mooseWarning().
Definition at line 72 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(_console, std::forward<Args>(args)...);
  }
name()
virtual const std::string & MooseBase::name () const inline virtual inherited
Get the name of the class.
Returns
The name of the class
Reimplemented in MooseVariableBase.
Definition at line 47 of file MooseBase.h.
{ return _name; }
Referenced by HierarchicalGridPartitioner::_do_partition(), AdaptivityAction::act(), AddElementalFieldAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVariableAction::act(), CopyNodalVarsAction::act(), DeprecatedBlockAction::act(), DisplayGhostingAction::act(), MaterialOutputAction::act(), AddDriftDiffusionAction::addADKernels(), FEProblemBase::addAnyRedistributers(), Executioner::addAttributeReporter(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFunctorMaterial(), FunctorMaterial::addFunctorProperty(), FunctorMaterial::addFunctorPropertyByBlocks(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), ADDGKernel::ADDGKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), SubProblem::addPiecewiseByBlockLambdaFunctor(), FEProblemBase::addPostprocessor(), UserObject::addPostprocessorDependencyHelper(), InitialConditionBase::addPostprocessorDependencyHelper(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), UserObject::addUserObjectDependencyHelper(), AuxKernelTempl< ComputeValueType >::addUserObjectDependencyHelper(), InitialConditionBase::addUserObjectDependencyHelper(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), UserObject::addVectorPostprocessorDependencyHelper(), FVFluxKernel::adjustRMGhostLayers(), ADSurfaceCharge::ADSurfaceCharge(), Output::advancedExecuteOn(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayDGKernel::ArrayDGKernel(), ArrayParsedAux::ArrayParsedAux(), AStableDirk4::AStableDirk4(), Function::average(), MultiApp::backup(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), PiecewiseTabularBase::buildFromFile(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkICRestartError(), Damper::checkMinDamping(), Coupleable::checkWritableVar(), CompositeFunction::CompositeFunction(), MaterialBase::computeProperties(), FEProblemBase::computeUserObjectByName(), VectorPostprocessorVisualizationAux::computeValue(), MooseBaseParameterInterface::connectControllableParams(), BatchMaterial< Tuple, Output, Input >::construct(), MultiApp::createApp(), AddVariableAction::createInitialConditionAction(), MultiApp::createLocalApp(), MeshGeneratorSystem::createMeshGeneratorOrder(), MaterialBase::declareADProperty(), MeshGenerator::declareMeshesForSubByName(), MeshGenerator::declareNullMeshName(), MaterialBase::declareProperty(), DOFMapOutput::demangle(), DerivativeSumMaterialTempl< is_ad >::DerivativeSumMaterialTempl(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DomainUserObject::DomainUserObject(), DumpObjectsProblem::dumpObjectHelper(), EconomouDielectricBC::EconomouDielectricBC(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementValueSampler::ElementValueSampler(), MooseMesh::errorIfDistributedMesh(), MooseBaseErrorInterface::errorPrefix(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), PointValue::execute(), RestartableDataReporter::execute(), MultiAppNearestNodeTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), MultiApp::fillPositions(), PointSamplerBase::finalize(), FunctionDT::FunctionDT(), FVFunctionIC::functionName(), FunctionIC::functionName(), FunctorPositions::FunctorPositions(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), BoundaryDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), GeneratedMeshGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MeshGenerator::generateInternal(), InterfaceMaterial::getADMaterialProperty(), Material::getADMaterialProperty(), MultiAppTransfer::getAppInfo(), MultiApp::getBoundingBox(), Control::getControllableParameterByName(), Control::getControllableValue(), Control::getControllableValueByName(), UserObject::getDependObjects(), FEProblemBase::getDistribution(), DistributionInterface::getDistribution(), DistributionInterface::getDistributionByName(), AddZapdosReactions::getElectronImpactKernelName(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), MultiApp::getExecutioner(), FEProblemBase::getExecutor(), OutputWarehouse::getFileNumbers(), FEProblemBase::getFunction(), SubProblem::getFunctor(), AuxKernelTempl< ComputeValueType >::getGenericMaterialProperty(), NodalPatchRecovery::getGenericMaterialProperty(), InterfaceMaterial::getGenericMaterialProperty(), Material::getGenericMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialPropertyByName(), Material::getGenericOptionalMaterialProperty(), MaterialBase::getGenericZeroMaterialProperty(), BatchMaterial< Tuple, Output, Input >::getIndex(), AddZapdosReactions::getKernelName(), SolutionUserObject::getLocalVarIndex(), Marker::getMarkerValue(), Material::getMaterial(), FEProblemBase::getMaterial(), Material::getMaterialByName(), AuxKernelTempl< ComputeValueType >::getMaterialProperty(), NodalPatchRecovery::getMaterialProperty(), InterfaceMaterial::getMaterialProperty(), Material::getMaterialProperty(), SubProblem::getMaterialPropertyBlockNames(), SubProblem::getMaterialPropertyBoundaryNames(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOld(), NodalPatchRecovery::getMaterialPropertyOld(), InterfaceMaterial::getMaterialPropertyOld(), Material::getMaterialPropertyOld(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOlder(), NodalPatchRecovery::getMaterialPropertyOlder(), InterfaceMaterial::getMaterialPropertyOlder(), Material::getMaterialPropertyOlder(), MeshGenerator::getMesh(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshesByName(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MultiAppTransfer::getMultiApp(), InterfaceMaterial::getNeighborADMaterialProperty(), InterfaceMaterial::getNeighborMaterialProperty(), InterfaceMaterial::getNeighborMaterialPropertyOld(), InterfaceMaterial::getNeighborMaterialPropertyOlder(), Material::getOptionalADMaterialProperty(), Material::getOptionalMaterialProperty(), Material::getOptionalMaterialPropertyOld(), Material::getOptionalMaterialPropertyOlder(), FEProblemBase::getPositionsObject(), FEProblemBase::getPostprocessorValueByName(), AddReactions::getReactionKernelName(), ReporterData::getReporterInfo(), FEProblemBase::getSampler(), Transient::getTimeStepperName(), ProjectedStatefulMaterialStorageAction::getTypeEnum(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), Terminator::handleMessage(), FEProblemBase::hasFunction(), SubProblem::hasFunctor(), SubProblem::hasFunctorWithType(), AdvancedOutput::hasOutputHelper(), FEProblemBase::hasPostprocessor(), FEProblemBase::hasPostprocessorValueByName(), FEProblemBase::hasUserObject(), AdvancedOutput::init(), FEProblemBase::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), AttribName::initFrom(), NestedDivision::initialize(), SolutionScalarAux::initialSetup(), NodalVariableValue::initialSetup(), MultiAppProjectionTransfer::initialSetup(), SolutionUserObject::initialSetup(), AdvancedOutput::initOutputList(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MaterialBase::initStatefulProperties(), Function::integral(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), MeshGenerator::isChildMeshGenerator(), MeshGenerator::isNullMeshName(), MeshGenerator::isParentMeshGenerator(), LinearCombinationFunction::LinearCombinationFunction(), FEProblemBase::logAdd(), LymberopoulosElectronBC::LymberopoulosElectronBC(), Marker::Marker(), Material::Material(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), Distribution::median(), MemoryUsageReporter::MemoryUsageReporter(), MeshGenerator::meshPropertyPrefix(), MooseVariableInterface< T >::MooseVariableInterface(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), NeumannCircuitVoltageMoles_KV::NeumannCircuitVoltageMoles_KV(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), NodalValueSampler::NodalValueSampler(), MooseBaseParameterInterface::objectErrorPrefix(), MeshGenerator::Comparator::operator()(), DOFMapOutput::output(), ProgressOutput::output(), Output::Output(), AdvancedOutput::outputElementalVariables(), ConsoleUtils::outputExecutionInformation(), AdvancedOutput::outputInput(), AdvancedOutput::outputNodalVariables(), AdvancedOutput::outputPostprocessors(), Exodus::outputPostprocessors(), Nemesis::outputPostprocessors(), TableOutput::outputReporter(), AdvancedOutput::outputReporters(), AdvancedOutput::outputScalarVariables(), AdvancedOutput::outputSystemInformation(), AdvancedOutput::outputVectorPostprocessors(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedODEKernel::ParsedODEKernel(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PointVariableSamplerBase::PointVariableSamplerBase(), MultiApp::readCommandLineArguments(), Receiver::Receiver(), Executor::Result::record(), FEProblemBase::registerRandomInterface(), GlobalParamsAction::remove(), MaterialBase::resetQpProperties(), MultiApp::restore(), SakiyamaEnergySecondaryElectronBC::SakiyamaEnergySecondaryElectronBC(), SakiyamaSecondaryElectronBC::SakiyamaSecondaryElectronBC(), ScalarComponentIC::ScalarComponentIC(), SecondaryElectronBC::SecondaryElectronBC(), SecondaryElectronEnergyBC::SecondaryElectronEnergyBC(), MultiApp::setAppOutputFileBase(), MooseMesh::setBoundaryName(), Control::setControllableValue(), Control::setControllableValueByName(), GlobalParamsAction::setDoubleIndexParam(), OutputWarehouse::setFileNumbers(), GlobalParamsAction::setParam(), FEProblemBase::setPostprocessorValueByName(), GlobalParamsAction::setScalarParam(), MooseMesh::setSubdomainName(), GlobalParamsAction::setTripleIndexParam(), Split::setup(), TransientMultiApp::setupApp(), GlobalParamsAction::setVectorParam(), SideCurrent::SideCurrent(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SideValueSampler::SideValueSampler(), TransientMultiApp::solveStep(), UserObject::spatialValue(), StitchedMesh::StitchedMesh(), SubProblem::storeBoundaryDelayedCheckMatProp(), SubProblem::storeBoundaryMatPropName(), SubProblem::storeBoundaryZeroMatProp(), SubProblem::storeSubdomainDelayedCheckMatProp(), SubProblem::storeSubdomainMatPropName(), SubProblem::storeSubdomainZeroMatProp(), MaterialBase::subdomainSetup(), TaggingInterface::TaggingInterface(), VectorPostprocessorVisualizationAux::timestepSetup(), MultiAppDofCopyTransfer::transfer(), TransientMultiApp::TransientMultiApp(), MooseBase::typeAndName(), MooseBaseParameterInterface::uniqueParameterName(), UserObject::UserObject(), UserObjectInterface::userObjectName(), MultiAppTransfer::variableIntegrityCheck(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), AdvancedOutput::wantOutput(), Coupleable::writableCoupledValue(), and Coupleable::writableVariable().
numBlocks()
unsigned int BlockRestrictable::numBlocks () const inherited
Return the number of blocks for this object.
Returns
The number of subdomains
Definition at line 199 of file BlockRestrictable.C.
{
  return (unsigned int)_blk_ids.size();
}
Referenced by ElementCentroidPositions::initialize().
objectErrorPrefix()
std::string MooseBaseParameterInterface::objectErrorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for an object.
Definition at line 58 of file MooseBaseParameterInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the class \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseParameterInterface::paramErrorMsg().
paramError()
template<typename... Args> void MooseBaseParameterInterface::paramError (const std::string & param, Args... args) const inherited
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseError - only printing a message using the given args.
Definition at line 233 of file MooseBaseParameterInterface.h.
{
  Moose::show_trace = false;
  std::string msg = paramErrorMsg(param, std::forward<Args>(args)...);
  callMooseErrorRaw(msg, &_moose_base->getMooseApp());
  Moose::show_trace = true;
}
Referenced by HierarchicalGridPartitioner::_do_partition(), SetupDebugAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), ADDGKernel::ADDGKernel(), ReporterPointSource::addPoints(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ADNodalKernel::ADNodalKernel(), ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), AdvectiveFluxAux::AdvectiveFluxAux(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), ArrayBodyForce::ArrayBodyForce(), ArrayDGKernel::ArrayDGKernel(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayDirichletBC::ArrayDirichletBC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), ArrayPenaltyDirichletBC::ArrayPenaltyDirichletBC(), ArrayVacuumBC::ArrayVacuumBC(), BlockDeletionGenerator::BlockDeletionGenerator(), BlockWeightedPartitioner::BlockWeightedPartitioner(), BoundsAuxBase::BoundsAuxBase(), BreakMeshByBlockGenerator::BreakMeshByBlockGenerator(), BuildArrayVariableAux::BuildArrayVariableAux(), PiecewiseTabularBase::buildFromFile(), CartesianGridDivision::CartesianGridDivision(), UserObjectInterface::castUserObject(), checkComponent(), MeshGenerator::checkGetMesh(), PostprocessorInterface::checkParam(), Coupleable::checkVar(), MultiAppTransfer::checkVariable(), CircularBoundaryCorrectionGenerator::CircularBoundaryCorrectionGenerator(), CircularBoundaryCorrectionGenerator::circularCenterCalculator(), MultiAppGeneralFieldTransfer::closestToPosition(), CombinerGenerator::CombinerGenerator(), CompositionDT::CompositionDT(), ConcentricCircleMeshGenerator::ConcentricCircleMeshGenerator(), LibtorchNeuralNetControl::conditionalParameterError(), ConstantVectorPostprocessor::ConstantVectorPostprocessor(), ContainsPointAux::ContainsPointAux(), CopyValueAux::CopyValueAux(), Coupleable::Coupleable(), CoupledForceTempl< is_ad >::CoupledForceTempl(), CoupledValueFunctionMaterialTempl< is_ad >::CoupledValueFunctionMaterialTempl(), MultiApp::createApp(), MeshGeneratorSystem::createMeshGenerator(), CylindricalGridDivision::CylindricalGridDivision(), ConstantReporter::declareConstantReporterValues(), AccumulateReporter::declareLateValues(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DGLowerDKernel::DGLowerDKernel(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementLengthAux::ElementLengthAux(), ElementLpNormAux::ElementLpNormAux(), ElementValueSampler::ElementValueSampler(), ReporterPointSource::errorCheck(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), ExtraElementIDAux::ExtraElementIDAux(), ExtraElementIntegerDivision::ExtraElementIntegerDivision(), FEProblemSolve::FEProblemSolve(), FillBetweenCurvesGenerator::FillBetweenCurvesGenerator(), FillBetweenSidesetsGenerator::FillBetweenSidesetsGenerator(), ReporterPointSource::fillPoint(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), InternalSideIndicator::finalize(), FixedPointSolve::FixedPointSolve(), ForcingFunctionAux::ForcingFunctionAux(), FunctionArrayAux::FunctionArrayAux(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorAux::FunctorAux(), FunctorBinnedValuesDivision::FunctorBinnedValuesDivision(), FunctorElementalGradientAuxTempl< is_ad >::FunctorElementalGradientAuxTempl(), FunctorPositions::FunctorPositions(), FunctorVectorElementalAuxTempl< is_ad >::FunctorVectorElementalAuxTempl(), FVFluxBC::FVFluxBC(), FVInterfaceKernel::FVInterfaceKernel(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), FVTwoVarContinuityConstraint::FVTwoVarContinuityConstraint(), AdvancedExtruderGenerator::generate(), BlockDeletionGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundaryDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), BreakMeshByBlockGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), CombinerGenerator::generate(), ExplodeMeshGenerator::generate(), ExtraNodesetGenerator::generate(), FillBetweenCurvesGenerator::generate(), FillBetweenSidesetsGenerator::generate(), GeneratedMeshGenerator::generate(), MeshCollectionGenerator::generate(), MeshExtruderGenerator::generate(), ParsedCurveGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), PropertyReadFile::getBlockData(), PropertyReadFile::getData(), Sampler::getGlobalSamples(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), Sampler::getLocalSamples(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), Sampler::getNextLocalRow(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectName(), HFEMDirichletBC::HFEMDirichletBC(), MultiApp::init(), BlockWeightedPartitioner::initialize(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), PiecewiseConstantFromCSV::initialSetup(), LibtorchControlValuePostprocessor::initialSetup(), ReferenceResidualProblem::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), HistogramVectorPostprocessor::initialSetup(), AddMetaDataGenerator::inputChecker(), IntegratedBC::IntegratedBC(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceValueUserObjectAux::InterfaceValueUserObjectAux(), InterpolatedStatefulMaterialTempl< T >::InterpolatedStatefulMaterialTempl(), InversePowerMethod::InversePowerMethod(), IterationAdaptiveDT::IterationAdaptiveDT(), MultiApp::keepSolutionDuringRestore(), Kernel::Kernel(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LinearCombinationFunction::LinearCombinationFunction(), LowerDIntegratedBC::LowerDIntegratedBC(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), MaterialADConverterTempl< T >::MaterialADConverterTempl(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), PatternedMeshGenerator::mergeSubdomainNameMaps(), MeshCollectionGenerator::MeshCollectionGenerator(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshDivisionAux::MeshDivisionAux(), MeshGenerator::MeshGenerator(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarNodalAuxKernelTempl< ComputeValueType >::MortarNodalAuxKernelTempl(), MultiApp::moveApp(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), NestedDivision::NestedDivision(), NodalBC::NodalBC(), NodalEqualValueConstraint::NodalEqualValueConstraint(), NodalKernel::NodalKernel(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), NodalValueSampler::NodalValueSampler(), Output::Output(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), PatchMeshGenerator::PatchMeshGenerator(), PatternedMeshGenerator::PatternedMeshGenerator(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), PeriodicSegmentalConstraint::PeriodicSegmentalConstraint(), PIDTransientControl::PIDTransientControl(), PlaneDeletionGenerator::PlaneDeletionGenerator(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), PolyLineMeshGenerator::PolyLineMeshGenerator(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), LibmeshPartitioner::prepareBlocksForSubdomainPartitioner(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), PropertyReadFile::PropertyReadFile(), RandomIC::RandomIC(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readXda(), ReferenceResidualProblem::ReferenceResidualProblem(), RefineBlockGenerator::RefineBlockGenerator(), RefineSidesetGenerator::RefineSidesetGenerator(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setPartitioner(), TimeSequenceStepperBase::setupSequence(), SingleRankPartitioner::SingleRankPartitioner(), SphericalGridDivision::SphericalGridDivision(), SymmetryTransformGenerator::SymmetryTransformGenerator(), Terminator::Terminator(), TimeDerivativeAux::TimeDerivativeAux(), Transfer::Transfer(), TransformGenerator::TransformGenerator(), TransientMultiApp::TransientMultiApp(), ParsedCurveGenerator::tSectionSpaceDefiner(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), UserObject::UserObject(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), VolumeAux::VolumeAux(), XYDelaunayGenerator::XYDelaunayGenerator(), and XYMeshLineCutter::XYMeshLineCutter().
paramErrorMsg()
template<typename... Args> std::string MooseBaseParameterInterface::paramErrorMsg (const std::string & param, Args... args) const inline private inherited
Definition at line 171 of file MooseBaseParameterInterface.h.
  {
    auto param_prefix = paramErrorPrefix(_pars, param);
    // With no input location information, append object info (name + type)
    const std::string object_prefix =
        _pars.inputLocation(param).empty() ? objectErrorPrefix("parameter error") : "";
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    // Wrap error message to a separate line from param_prefix if it is about to
    // blow past 100 chars.  But only wrap if the param_prefix is long enough (12
    // chars) for the wrap to buy us much extra length. We don't check object_prefix
    // here because it will go before the parameter error
    if ((param_prefix.size() > 12 && msg.size() + param_prefix.size() > 99) ||
        msg.find("\n") != std::string::npos)
    {
      if (param_prefix.size() > 0 && param_prefix[param_prefix.size() - 1] != ':')
        param_prefix += ":";
      return object_prefix + param_prefix + "\n    " + MooseUtils::replaceAll(msg, "\n", "\n    ");
    }
    return object_prefix + param_prefix + " " + msg;
  }
Referenced by MooseBaseParameterInterface::paramError(), MooseBaseParameterInterface::paramInfo(), and MooseBaseParameterInterface::paramWarning().
parameters()
const InputParameters & MooseBaseParameterInterface::parameters () const inline inherited
Get the parameters of the object.
Returns
The parameters of the object
Definition at line 53 of file MooseBaseParameterInterface.h.
{ return _pars; }
Referenced by SetupDebugAction::act(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), FEProblemBase::addPostprocessor(), FEProblemBase::addPredictor(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), AdvancedOutput::AdvancedOutput(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), Moose::assemble_matrix(), AuxScalarKernel::AuxScalarKernel(), BoundsAuxBase::BoundsAuxBase(), MooseMesh::buildTypedMesh(), UserObjectInterface::castUserObject(), PostprocessorInterface::checkParam(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), Moose::compute_bounds(), Moose::compute_jacobian(), Moose::compute_nearnullspace(), Moose::compute_nullspace(), Moose::compute_postcheck(), Moose::compute_transpose_nullspace(), LibtorchNeuralNetControl::conditionalParameterError(), Console::Console(), MultiApp::createApp(), Postprocessor::declareValue(), DumpObjectsProblem::deduceNecessaryParameters(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), DumpObjectsProblem::dumpObjectHelper(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElectronsFromIonization::ElectronsFromIonization(), Executor::Executor(), Exodus::Exodus(), FEProblem::FEProblem(), FEProblemBase::FEProblemBase(), FixedPointSolve::FixedPointSolve(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GapValueAux::GapValueAux(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), MooseBaseParameterInterface::getCheckedPointerParam(), ExecutorInterface::getExecutor(), Material::getMaterial(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), UserObjectInterface::getUserObjectName(), VectorPostprocessorInterface::getVectorPostprocessorName(), GhostingUserObject::GhostingUserObject(), HphiRadialInterface::HphiRadialInterface(), AttribSystem::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), FullSolveMultiApp::initialSetup(), FEProblemBase::initNullSpaceVectors(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), isValid(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseAppCoordTransform::MooseAppCoordTransform(), MooseVariableInterface< T >::MooseVariableInterface(), MultiApp::MultiApp(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodeFaceConstraint::NodeFaceConstraint(), PatchMeshGenerator::PatchMeshGenerator(), PenetrationAux::PenetrationAux(), PicardSolve::PicardSolve(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), ProjectedStatefulMaterialStorageAction::processProperty(), MultiAppProjectionTransfer::projectSolution(), PropertyReadFile::PropertyReadFile(), PseudoTimestep::PseudoTimestep(), RandomIC::RandomIC(), InputParameterWarehouse::removeInputParameters(), OutputWarehouse::resetFileBase(), MooseAppCoordTransform::setCoordinateSystem(), FEProblemBase::setInputParametersFEProblem(), FEProblem::setInputParametersFEProblem(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SteffensenSolve::SteffensenSolve(), DumpObjectsProblem::stringifyParameters(), TaggingInterface::TaggingInterface(), Transfer::Transfer(), Transient::Transient(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
paramInfo()
template<typename... Args> void MooseBaseParameterInterface::paramInfo (const std::string & param, Args... args) const inherited
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseInfo - only printing a message using the given args.
Definition at line 250 of file MooseBaseParameterInterface.h.
{
  mooseInfo(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by TransientMultiApp::TransientMultiApp().
paramWarning()
template<typename... Args> void MooseBaseParameterInterface::paramWarning (const std::string & param, Args... args) const inherited
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseWarning - only printing a message using the given args.
Definition at line 243 of file MooseBaseParameterInterface.h.
{
  mooseWarning(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by MultiAppNearestNodeTransfer::execute(), FEProblemSolve::FEProblemSolve(), PlaneIDMeshGenerator::generate(), UniqueExtraIDMeshGenerator::generate(), Terminator::initialSetup(), and MooseMesh::MooseMesh().
postprocessorsAdded()
bool PostprocessorInterface::postprocessorsAdded () const private inherited
Returns
True if all pps have been added (the task associated with adding them is complete)
Definition at line 264 of file PostprocessorInterface.C.
{
  return _ppi_feproblem.getMooseApp().actionWarehouse().isTaskComplete("add_postprocessor");
}
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), and PostprocessorInterface::hasPostprocessorByName().
registerRestartableDataOnApp()
RestartableDataValue & Restartable::registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const private inherited
Helper function for actually registering the restartable data.
Definition at line 51 of file Restartable.C.
{
  return _restartable_app.registerRestartableData(
      std::move(data), tid, _restartable_read_only, _metaname);
}
Referenced by Restartable::declareRestartableDataHelper().
registerRestartableNameWithFilterOnApp()
void Restartable::registerRestartableNameWithFilterOnApp (const std::string & name, Moose::RESTARTABLE_FILTER filter) private inherited
Helper function for actually registering the restartable data.
Definition at line 59 of file Restartable.C.
{
  _restartable_app.registerRestartableNameWithFilter(name, filter);
}
Referenced by Restartable::declareRecoverableData().
residualSetup()
void SetupInterface::residualSetup () virtual inherited
Gets called just before the residual is computed and before this object is asked to do its job.
Reimplemented in NodeFaceConstraint, Function, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 55 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::residualSetup(), ComputeFVFluxResidualThread< RangeType >::setup(), and ComputeFVFluxRJThread< RangeType >::setup().
resolveOptionalProperties()
void MaterialPropertyInterface::resolveOptionalProperties () virtual inherited
resolve all optional properties
Reimplemented in Material.
Definition at line 230 of file MaterialPropertyInterface.C.
{
  for (auto & proxy : _optional_property_proxies)
    proxy->resolve(*this);
}
restartableName()
std::string Restartable::restartableName (const std::string & data_name) const protected inherited
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
This should only be used in this interface and in testing.
Definition at line 66 of file Restartable.C.
{
  return _restartable_system_name + "/" + _restartable_name + "/" + data_name;
}
Referenced by Restartable::declareRecoverableData(), and Restartable::declareRestartableDataHelper().
second()
const OutputTools< Real >::VariableSecond & MooseVariableInterface< Real >::second protected virtual inherited
The second derivative of the variable this object is operating on.
Returns
The reference to be stored off and used later.
Definition at line 161 of file MooseVariableInterface.C.
{
  if (_nodal)
    mooseError("second derivatives are not defined at nodes");
  return _variable->secondSln();
}
secondOld()
const OutputTools< Real >::VariableSecond & MooseVariableInterface< Real >::secondOld protected virtual inherited
The old second derivative of the variable this object is operating on.
Returns
The reference to be stored off and used later.
Definition at line 168 of file MooseVariableInterface.C.
{
  if (_nodal)
    mooseError("second derivatives are not defined at nodes");
  return _variable->secondSlnOld();
}
secondOlder()
const OutputTools< Real >::VariableSecond & MooseVariableInterface< Real >::secondOlder protected virtual inherited
The older second derivative of the variable this object is operating on.
Returns
The reference to be stored off and used later.
Definition at line 175 of file MooseVariableInterface.C.
{
  if (_nodal)
    mooseError("second derivatives are not defined at nodes");
  return _variable->secondSlnOlder();
}
secondPhi()
const OutputTools< Real >::VariablePhiSecond & MooseVariableInterface< Real >::secondPhi protected virtual inherited
The second derivative of the trial function.
Returns
The reference to be stored off and used later.
Definition at line 198 of file MooseVariableInterface.C.
{
  if (_nodal)
    mooseError("second derivatives are not defined at nodes");
  return _mvi_assembly->secondPhi(*_variable);
}
secondPhiFace()
const OutputTools< Real >::VariablePhiSecond & MooseVariableInterface< Real >::secondPhiFace protected virtual inherited
The second derivative of the trial function on the current face.
This should be called in e.g. IntegratedBC when you need second derivatives of the trial function function on the boundary.
Returns
The reference to be stored off and used later.
Definition at line 207 of file MooseVariableInterface.C.
{
  if (_nodal)
    mooseError("second derivatives are not defined at nodes");
  return _mvi_assembly->secondPhiFace(*_variable);
}
secondTest()
const OutputTools< Real >::VariableTestSecond & MooseVariableInterface< Real >::secondTest protected virtual inherited
The second derivative of the test function.
Returns
The reference to be stored off and used later.
Definition at line 182 of file MooseVariableInterface.C.
{
  if (_nodal)
    mooseError("second derivatives are not defined at nodes");
  return _variable->secondPhi();
}
secondTestFace()
const OutputTools< Real >::VariableTestSecond & MooseVariableInterface< Real >::secondTestFace protected virtual inherited
The second derivative of the test function on the current face.
This should be called in e.g. IntegratedBC when you need second derivatives of the test function function on the boundary.
Returns
The reference to be stored off and used later.
Definition at line 191 of file MooseVariableInterface.C.
{
  if (_nodal)
    mooseError("second derivatives are not defined at nodes");
  return _variable->secondPhiFace();
}
sort()
template<typename T > void DependencyResolverInterface::sort (typename std::vector< T > & vector) static inherited
Given a vector, sort using the getRequested/SuppliedItems sets.
Definition at line 64 of file DependencyResolverInterface.h.
{
  sortDFS(vector);
}
Referenced by TheWarehouse::prepare().
sortDFS()
template<typename T > void DependencyResolverInterface::sortDFS (typename std::vector< T > & vector) static inherited
Given a vector, sort using the depth-first search.
Class that represents the dependency as a graph
Definition at line 71 of file DependencyResolverInterface.h.
{
  if (vector.size() <= 1)
    return;
  DependencyResolver<T> graph;
  // Map of suppliers: what is supplied -> by what object
  std::multimap<std::string, T> suppliers_map;
  for (auto & v : vector)
  {
    for (const auto & supplied_item : v->getSuppliedItems())
    {
      suppliers_map.emplace(supplied_item, v);
      graph.addNode(v);
    }
  }
  // build the dependency graph
  for (auto & v : vector)
  {
    for (const auto & requested_item : v->getRequestedItems())
    {
      const auto & [begin_it, end_it] = suppliers_map.equal_range(requested_item);
      if (begin_it == end_it)
        graph.addNode(v);
      else
        for (const auto & [supplier_name, supplier_object] : as_range(begin_it, end_it))
        {
          libmesh_ignore(supplier_name);
          if (supplier_object == v)
            // We allow an object to have a circular dependency within itself; e.g. we choose to
            // trust a developer knows what they are doing within a single object
            continue;
          graph.addEdge(supplier_object, v);
        }
    }
  }
  vector = graph.dfs();
}
Referenced by DependencyResolverInterface::sort().
statefulPropertiesAllowed()
void MaterialPropertyInterface::statefulPropertiesAllowed (bool stateful_allowed) inherited
Derived classes can declare whether or not they work with stateful material properties.
See, for example, DiracKernel. By default, they are allowed.
Definition at line 141 of file MaterialPropertyInterface.C.
{
  _stateful_allowed = stateful_allowed;
}
Referenced by DiracKernelBase::DiracKernelBase(), and DiracKernelTempl< T >::DiracKernelTempl().
subdomainSetup()
void SetupInterface::subdomainSetup () virtual inherited
Gets called when the subdomain changes (i.e.
in a Jacobian or residual loop) and before this object is asked to do its job
Reimplemented in Material, MaterialBase, GeneralUserObject, NodalUserObject, ThreadedGeneralUserObject, and Constraint.
Definition at line 60 of file SetupInterface.C.
{
}
timestepSetup()
void SetupInterface::timestepSetup () virtual inherited
Gets called at the beginning of the timestep before this object is asked to do its job.
Reimplemented in VectorPostprocessorVisualizationAux, EqualValueEmbeddedConstraint, Function, Console, JSONOutput, Positions, MemoryUsage, NumNonlinearIterations, Times, SolutionUserObject, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, MooseVariableFV< T >, and VectorMemoryUsage.
Definition at line 45 of file SetupInterface.C.
{
}
Referenced by JSONOutput::timestepSetup(), and MooseVariableField< OutputType >::timestepSetup().
type()
const std::string & MooseBase::type () const inline inherited
Get the type of this class.
Returns
the name of the type of this class
Definition at line 41 of file MooseBase.h.
{ return _type; }
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), CreateProblemDefaultAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetupDebugAction::act(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::addDistribution(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addObject(), DistributedRectilinearMeshGenerator::addPoint(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), PhysicsBasedPreconditioner::addSystem(), FEProblemBase::addTimeIntegrator(), SubProblem::addVectorTag(), DisplacedProblem::addVectorTag(), FEProblemBase::advanceMultiApps(), FEProblemBase::backupMultiApps(), BoundaryPreservedMarker::BoundaryPreservedMarker(), DistributedRectilinearMeshGenerator::buildCube(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildPRefinementAndCoarseningMaps(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), FEProblemBase::computeAuxiliaryKernels(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpJacobian(), HFEMDirichletBC::computeLowerDQpJacobian(), ArrayHFEMDiffusion::computeLowerDQpJacobian(), HFEMDiffusion::computeLowerDQpJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), FEProblemBase::computeMultiAppsDT(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), DGCoupledAdvection::computeOffDiagJacobianHelper(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ScalarKernel::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueBoundaryConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), LinearNodalConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), DGConvection::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), InterfaceDiffusion::computeQpJacobian(), InterfaceReaction::computeQpJacobian(), DGCoupledAdvection::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), DGFunctionTemperatureAdvection::computeQpJacobian(), DGTemperatureAdvection::computeQpJacobian(), InterTemperatureAdvection::computeQpJacobian(), CoupledTiedValueConstraint::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), HFEMTestJump::computeQpOffDiagJacobian(), HFEMTrialJump::computeQpOffDiagJacobian(), DGCoupledAdvection::computeQpOffDiagJacobian(), ScalarKernel::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), EqualValueBoundaryConstraint::computeQpResidual(), EqualValueEmbeddedConstraint::computeQpResidual(), LinearNodalConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), DGConvection::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), DGEFieldAdvection::computeQpResidual(), HphiRadialInterface::computeQpResidual(), InterfaceAdvection::computeQpResidual(), InterfaceLogDiffusionElectrons::computeQpResidual(), PotentialSurfaceCharge::computeQpResidual(), ADDGAdvection::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), HFEMDiffusion::computeQpResidual(), HFEMTestJump::computeQpResidual(), HFEMTrialJump::computeQpResidual(), InterfaceDiffusion::computeQpResidual(), InterfaceReaction::computeQpResidual(), DGCoupledAdvection::computeQpResidual(), DGFunctionConvection::computeQpResidual(), DGFunctionTemperatureAdvection::computeQpResidual(), DGTemperatureAdvection::computeQpResidual(), InterTemperatureAdvection::computeQpResidual(), ArrayDGDiffusion::computeQpResidual(), ArrayHFEMDiffusion::computeQpResidual(), FEProblemBase::computeUserObjectByName(), FEProblemBase::computeUserObjects(), FEProblemBase::computeUserObjectsInternal(), BatchMaterial< Tuple, Output, Input >::construct(), DisplacedProblem::createQRules(), FEProblemBase::createQRules(), MeshGenerator::declareMeshProperty(), DumpObjectsProblem::deduceNecessaryParameters(), DumpObjectsProblem::dumpObjectHelper(), FEProblemBase::duplicateVariableCheck(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), MooseBaseErrorInterface::errorPrefix(), AB2PredictorCorrector::estimateTimeError(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finishMultiAppStep(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), ElementSubdomainIDGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), PatternedMeshGenerator::generate(), MeshGenerator::generateInternal(), MultiAppTransfer::getAppInfo(), TransfiniteMeshGenerator::getEdge(), ElementGenerator::getElemType(), FEProblemBase::getMaterial(), FEProblemBase::getMaterialData(), MaterialOutputAction::getParams(), ReporterData::getReporterInfo(), Transient::getTimeIntegratorName(), FEProblemBase::getTransfers(), SubProblem::getVectorTags(), DisplacedProblem::getVectorTags(), CommonOutputAction::hasConsole(), FEProblemBase::hasMultiApps(), AdvancedOutput::hasOutput(), FEProblemBase::incrementMultiAppTStep(), AdvancedOutput::initAvailableLists(), FunctorPositions::initialize(), FunctorTimes::initialize(), MultiAppConservativeTransfer::initialSetup(), ArrayDGDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), RelationshipManager::isType(), FEProblemBase::logAdd(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), SubProblem::numVectorTags(), DisplacedProblem::numVectorTags(), MooseBaseParameterInterface::objectErrorPrefix(), AdvancedOutput::output(), Console::output(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), ProjectedStatefulMaterialStorageAction::processProperty(), SolutionInvalidInterface::registerInvalidSolutionInternal(), FEProblemBase::restoreMultiApps(), MeshRepairGenerator::separateSubdomainsByElementType(), FEProblemBase::setCoupling(), MooseBase::typeAndName(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), DisplacedProblem::updateGeomSearch(), FEProblemBase::updateGeomSearch(), UserObjectInterface::userObjectType(), and AdvancedOutput::wantOutput().
typeAndName()
std::string MooseBase::typeAndName () const inline inherited
Get the class's combined type and name; useful in error handling.
Returns
The type and name of this class in the form '<type()> "<name()>"'.
Definition at line 53 of file MooseBase.h.
  {
    return type() + std::string(" \"") + name() + std::string("\"");
  }
Referenced by ReporterContext< T >::finalize(), and ReporterData::getReporterInfo().
uniqueName()
MooseObjectName MooseBaseParameterInterface::uniqueName () const inline inherited
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
Definition at line 58 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectName(_pars.get<std::string>("_unique_name"));
  }
Referenced by MooseBaseParameterInterface::connectControllableParams(), and Action::uniqueActionName().
uniqueParameterName()
MooseObjectParameterName MooseBaseParameterInterface::uniqueParameterName (const std::string & parameter_name) const inline inherited
The unique parameter name of a valid parameter of this object for accessing parameter controls.
Definition at line 43 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectParameterName(
        _pars.get<std::string>("_moose_base"), _moose_base->name(), parameter_name);
  }
userObjectName()
const std::string & UserObjectInterface::userObjectName (const UserObject & uo) const private inherited
Gets a UserObject's name; avoids including UserObject.h in the UserObjectInterface.
Definition at line 113 of file UserObjectInterface.C.
{
  return uo.name();
}
Referenced by UserObjectInterface::castUserObject().
userObjectType()
const std::string & UserObjectInterface::userObjectType (const UserObject & uo) const private inherited
Gets a UserObject's type; avoids including UserObject.h in the UserObjectInterface.
Definition at line 107 of file UserObjectInterface.C.
{
  return uo.type();
}
Referenced by UserObjectInterface::castUserObject().
validParams()
InputParameters QuadraturePointMarker::validParams () static
Definition at line 18 of file QuadraturePointMarker.C.
{
  InputParameters params = Marker::validParams();
  params += MaterialPropertyInterface::validParams();
  MooseEnum third_state("DONT_MARK=-1 COARSEN DO_NOTHING REFINE", "DONT_MARK");
  params.addParam<MooseEnum>(
      "third_state",
      third_state,
      "The Marker state to apply to values falling in-between the coarsen and refine thresholds.");
  params.addParam<bool>("invert",
                        false,
                        "If this is true then values _below_ 'refine' will be "
                        "refined and _above_ 'coarsen' will be coarsened.");
  params.addRequiredParam<VariableName>("variable",
                                        "The values of this variable will be compared "
                                        "to 'refine' and 'coarsen' to see what should "
                                        "be done with the element");
  return params;
}
Referenced by ValueRangeMarker::validParams(), and ValueThresholdMarker::validParams().
value()
const OutputTools< Real >::VariableValue & MooseVariableInterface< Real >::value protected virtual inherited
The value of the variable this object is operating on.
This is computed by default and should already be available as _u
Returns
The reference to be stored off and used later.
Definition at line 69 of file MooseVariableInterface.C.
{
  if (_nodal)
    return _variable->dofValues();
  else
    return _variable->sln();
}
valueOld()
const OutputTools< Real >::VariableValue & MooseVariableInterface< Real >::valueOld protected virtual inherited
The old value of the variable this object is operating on.
Returns
The reference to be stored off and used later.
Definition at line 76 of file MooseVariableInterface.C.
{
  if (_nodal)
    return _variable->dofValuesOld();
  else
    return _variable->slnOld();
}
valueOlder()
const OutputTools< Real >::VariableValue & MooseVariableInterface< Real >::valueOlder protected virtual inherited
The older value of the variable this object is operating on.
Returns
The reference to be stored off and used later.
Definition at line 83 of file MooseVariableInterface.C.
{
  if (_nodal)
    return _variable->dofValuesOlder();
  else
    return _variable->slnOlder();
}
Member Data Documentation
_action_factory
ActionFactory& MooseBaseParameterInterface::_action_factory protected inherited
Builds Actions.
Definition at line 164 of file MooseBaseParameterInterface.h.
Referenced by CommonOutputAction::create(), AddVariableAction::createInitialConditionAction(), AddSpecies::createInitialConditions(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
_adaptivity
Adaptivity& Marker::_adaptivity protected inherited
Definition at line 105 of file Marker.h.
Referenced by Marker::getErrorVector().
_app
MooseApp& MooseBase::_app protected inherited
The MOOSE application this is associated with.
Definition at line 60 of file MooseBase.h.
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), MeshGenerator::addChildMeshGenerator(), FEProblemBase::addMaterialHelper(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addOutput(), MeshGenerator::addParentMeshGenerator(), FVFluxKernel::adjustRMGhostLayers(), FEProblemBase::allowOutput(), AStableDirk4::AStableDirk4(), FileMesh::buildMesh(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), MeshGenerator::checkGetMesh(), FEProblemBase::checkICRestartError(), FEProblemBase::checkNonlinearConvergence(), OversampleOutput::cloneMesh(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), Console::Console(), TimeStepper::constrainStep(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::createLocalApp(), FEProblemBase::customSetup(), MeshGenerator::declareMeshProperty(), MeshGenerator::declareNullMeshName(), MooseMesh::determineUseDistributedMesh(), DumpObjectsProblem::dumpObjectHelper(), DumpObjectsProblem::dumpVariableHelper(), EigenExecutionerBase::EigenExecutionerBase(), EigenKernel::EigenKernel(), PIDTransientControl::execute(), Eigenvalue::execute(), InversePowerMethod::execute(), NonlinearEigen::execute(), Steady::execute(), Transient::execute(), PseudoTimestep::execute(), IterationInfo::execute(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FileOutput::FileOutput(), ChangeOverFixedPointPostprocessor::finalize(), RadialAverage::finalize(), FixedPointSolve::FixedPointSolve(), FEProblemBase::forceOutput(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), SideSetsFromNormalsGenerator::generate(), MeshGenerator::generateInternal(), FEProblemBase::getExecutor(), MeshGenerator::getMeshByName(), NumFixedPointIterations::getValue(), NumRelationshipManagers::getValue(), GhostingUserObject::GhostingUserObject(), MooseMesh::init(), InversePowerMethod::init(), NonlinearEigen::init(), Transient::init(), FEProblemBase::init(), TimePeriod::initialSetup(), Console::initialSetup(), AdvancedOutput::initOutputList(), FEProblemBase::initPetscOutput(), EigenProblem::initPetscOutput(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MeshGenerator::MeshGenerator(), EigenExecutionerBase::normalizeSolution(), NumFailedTimeSteps::NumFailedTimeSteps(), AugmentSparsityOnInterface::operator()(), Checkpoint::output(), Exodus::output(), Nemesis::output(), PerfGraphOutput::output(), Tecplot::output(), MortarNodalGeometryOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Exodus::outputEmptyTimestep(), Console::outputInput(), Exodus::outputInput(), Exodus::outputNodalVariables(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), Console::outputSystemInformation(), JSONOutput::outputSystemInformation(), MultiApp::parentOutputPositionChanged(), PIDTransientControl::PIDTransientControl(), Transient::preExecute(), Eigenvalue::prepareSolverOptions(), FEProblemBase::projectSolution(), MultiApp::setAppOutputFileBase(), FileOutput::setFileBaseInternal(), MeshGenerator::setMeshProperty(), MeshGenerator::setMeshPropertyHelper(), FEProblemBase::setRestartFile(), TransientMultiApp::setupApp(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SolutionInvalidityReporter::SolutionInvalidityReporter(), FEProblemBase::solve(), EigenProblem::solve(), PetscOutput::solveSetup(), TransientMultiApp::solveStep(), FEProblemBase::subdomainSetup(), FEProblemBase::theWarehouse(), TimeExtremeValue::TimeExtremeValue(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), Transient::Transient(), FEProblemBase::updateMortarMesh(), Console::write(), and FEProblemBase::~FEProblemBase().
_assembly
Assembly& Marker::_assembly protected inherited
Definition at line 110 of file Marker.h.
_blk_dim
unsigned int BlockRestrictable::_blk_dim private inherited
Largest mesh dimension of the elements in the blocks for this object.
Definition at line 259 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blocksMaxDimension(), and BlockRestrictable::initializeBlockRestrictable().
_blk_dual_restrictable
const bool BlockRestrictable::_blk_dual_restrictable private inherited
Flag for allowing dual restriction.
Definition at line 238 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_blk_feproblem
FEProblemBase* BlockRestrictable::_blk_feproblem private inherited
Pointer to FEProblemBase.
Definition at line 241 of file BlockRestrictable.h.
Referenced by BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), and BlockRestrictable::initializeBlockRestrictable().
_blk_ids
std::set<SubdomainID> BlockRestrictable::_blk_ids private inherited
Set of block ids supplied by the user via the input file (for error checking)
Definition at line 229 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blockIDs(), BlockRestrictable::blockRestricted(), BlockRestrictable::checkVariable(), BlockRestrictable::hasBlocks(), BlockRestrictable::initializeBlockRestrictable(), BlockRestrictable::isBlockSubset(), and BlockRestrictable::numBlocks().
_blk_material_data
const MaterialData* BlockRestrictable::_blk_material_data protected inherited
Pointer to the MaterialData class for this object.
Definition at line 207 of file BlockRestrictable.h.
Referenced by BlockRestrictable::hasBlockMaterialProperty(), and BlockRestrictable::initializeBlockRestrictable().
_blk_mesh
MooseMesh* BlockRestrictable::_blk_mesh private inherited
Pointer to Mesh.
Definition at line 244 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blockIDs(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlocks(), BlockRestrictable::initializeBlockRestrictable(), BlockRestrictable::isBlockSubset(), and BlockRestrictable::meshBlockIDs().
_blk_name
const std::string& BlockRestrictable::_blk_name private inherited
Name of the object.
Definition at line 256 of file BlockRestrictable.h.
Referenced by BlockRestrictable::checkVariable(), and BlockRestrictable::initializeBlockRestrictable().
_blk_tid
THREAD_ID BlockRestrictable::_blk_tid private inherited
Thread id for this object.
Definition at line 253 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_blocks
std::vector<SubdomainName> BlockRestrictable::_blocks private inherited
Vector the block names supplied by the user via the input file.
Definition at line 235 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blocks(), and BlockRestrictable::initializeBlockRestrictable().
_boundary_ids
const std::set<BoundaryID>& BlockRestrictable::_boundary_ids private inherited
Reference to the boundary_ids, defaults to an empty set if not provided.
Definition at line 250 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_current_elem
const Elem* const& Marker::_current_elem protected inherited
Definition at line 113 of file Marker.h.
Referenced by BoundaryMarker::computeElementMarker(), BoundaryPreservedMarker::computeElementMarker(), BoxMarker::computeElementMarker(), ErrorFractionMarker::computeElementMarker(), ErrorToleranceMarker::computeElementMarker(), OrientedBoxMarker::computeElementMarker(), and ReporterPointMarker::computeElementMarker().
_current_execute_flag
const ExecFlagType& SetupInterface::_current_execute_flag protected inherited
Reference to FEProblemBase.
Definition at line 78 of file SetupInterface.h.
Referenced by PseudoTimestep::execute().
_default_properties
std::vector<std::unique_ptr<PropertyValue> > MaterialPropertyInterface::_default_properties protected inherited
Storage vector for default properties.
Definition at line 531 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::defaultGenericMaterialProperty().
_default_values
std::map<PostprocessorName, std::unique_ptr<PostprocessorValue> > PostprocessorInterface::_default_values mutable private inherited
Holds the default postprocessor values that are requested (key is PostprocessorName)
Definition at line 154 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::getPostprocessorValueInternal().
_depend
std::set<std::string> Marker::_depend protected inherited
Depend Markers.
Definition at line 118 of file Marker.h.
Referenced by Marker::getMarkerValue(), and Marker::getRequestedItems().
_dof_indices
std::vector<libMesh::dof_id_type> MooseVariableDependencyInterface::_dof_indices private inherited
A container for holding dof indices in order to avoid constant memory reallocation.
Definition at line 86 of file MooseVariableDependencyInterface.h.
Referenced by MooseVariableDependencyInterface::checkVariables().
_empty_boundary_ids
const std::set<BoundaryID> BlockRestrictable::_empty_boundary_ids private inherited
An empty set for referencing when boundary_ids is not included.
Definition at line 247 of file BlockRestrictable.h.
_empty_execute_enum
ExecFlagEnum SetupInterface::_empty_execute_enum private inherited
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
This is private because others should not be messing with it.
Definition at line 71 of file SetupInterface.h.
Referenced by SetupInterface::SetupInterface().
_enabled
const bool& MooseObject::_enabled protected inherited
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
Definition at line 58 of file MooseObject.h.
Referenced by MooseObject::enabled().
_execute_enum
const ExecFlagEnum& SetupInterface::_execute_enum protected inherited
Execute settings for this object.
Definition at line 75 of file SetupInterface.h.
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), SetupInterface::getExecuteOnEnum(), JSONOutput::outputReporters(), XMLOutput::outputVectorPostprocessors(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
_factory
Factory& MooseBaseParameterInterface::_factory protected inherited
The Factory associated with the MooseApp.
Definition at line 161 of file MooseBaseParameterInterface.h.
Referenced by AddGeneralReactions::act(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), ElementIDOutputAction::act(), AddSpecies::act(), AdaptivityAction::act(), AddControlAction::act(), AddNodalNormalsAction::act(), AddPeriodicBCAction::act(), AutoCheckpointAction::act(), ComposeTimeStepperAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DisplayGhostingAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), PartitionerAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SetupPreconditionerAction::act(), SetupPredictorAction::act(), SetupResidualDebugAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddGeneralReactions::addEEDFReactionKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddDriftDiffusionAction::addPosition(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), MooseBaseParameterInterface::connectControllableParams(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), MaterialOutputAction::getParams(), and ProjectedStatefulMaterialStorageAction::processProperty().
_fe_problem
FEProblemBase& Marker::_fe_problem protected inherited
Definition at line 104 of file Marker.h.
Referenced by ReporterPointMarker::markerSetup().
_field_var
MooseVariable& Marker::_field_var protected inherited
Definition at line 112 of file Marker.h.
Referenced by Marker::computeMarker(), and Marker::Marker().
_fv_variable
MooseVariableFV<Real >* MooseVariableInterface< Real >::_fv_variable protected inherited
Definition at line 215 of file MooseVariableInterface.h.
_get_material_property_called
bool MaterialPropertyInterface::_get_material_property_called protected inherited
Initialized to false.
Gets set to true when getMaterialProperty() is called. Clients of this class can inquire whether getMaterialProperty() has been called by calling getMaterialPropertyCalled().
Definition at line 528 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::getGenericMaterialPropertyByName(), and MaterialPropertyInterface::getMaterialPropertyCalled().
_get_suffix
const MaterialPropertyName MaterialPropertyInterface::_get_suffix protected inherited
Definition at line 536 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::getBlockMaterialProperty(), MaterialPropertyInterface::getGenericMaterialPropertyByName(), Material::getGenericMaterialPropertyByName(), MaterialPropertyInterface::hasADMaterialPropertyByName(), and MaterialPropertyInterface::hasMaterialPropertyByName().
_interpolated_old
const std::string MaterialPropertyInterface::_interpolated_old = "_interpolated_old" static protected inherited
name suffixes for interpolated old and older properties
Definition at line 542 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::getGenericMaterialPropertyByName(), and Material::getGenericMaterialPropertyByName().
_interpolated_older
const std::string MaterialPropertyInterface::_interpolated_older = "_interpolated_older" static protected inherited
Definition at line 543 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::getGenericMaterialPropertyByName(), and Material::getGenericMaterialPropertyByName().
_material_data
MaterialData& MaterialPropertyInterface::_material_data protected inherited
The material data class that stores properties.
Definition at line 466 of file MaterialPropertyInterface.h.
Referenced by Material::computeProperties(), MaterialPropertyInterface::getBlockMaterialProperty(), MaterialPropertyInterface::getGenericMaterialProperty(), MaterialPropertyInterface::getGenericMaterialPropertyByName(), MaterialPropertyInterface::hasADMaterialPropertyByName(), MaterialPropertyInterface::hasMaterialPropertyByName(), InterfaceMaterial::materialData(), and Material::materialData().
_material_data_type
const Moose::MaterialDataType MaterialPropertyInterface::_material_data_type protected inherited
The type of data.
Definition at line 463 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::buildRequiredMaterials(), ADSurfaceCharge::computeQpProperties(), and MaterialPropertyInterface::getMaterialByName().
_material_property_dependencies
std::set<unsigned int> MaterialPropertyInterface::_material_property_dependencies protected inherited
The set of material properties (as given by their IDs) that this object depends on.
Definition at line 534 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::getBlockMaterialProperty(), MaterialPropertyInterface::getGenericMaterialPropertyByName(), and MaterialPropertyInterface::getMatPropDependencies().
_mci_feproblem
FEProblemBase& MeshChangedInterface::_mci_feproblem protected inherited
Reference to FEProblemBase instance.
Definition at line 38 of file MeshChangedInterface.h.
Referenced by MeshChangedInterface::MeshChangedInterface().
_mesh
MooseMesh& Marker::_mesh protected inherited
Definition at line 115 of file Marker.h.
Referenced by BoundaryMarker::BoundaryMarker(), BoundaryPreservedMarker::BoundaryPreservedMarker(), BoundaryMarker::computeElementMarker(), and BoundaryPreservedMarker::preserveBoundary().
_metaname
const RestartableDataMapName Restartable::_metaname private inherited
Restartable metadata name.
Definition at line 240 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_mi_block_ids
const std::set<SubdomainID>& MaterialPropertyInterface::_mi_block_ids private inherited
Storage for the block ids created by BlockRestrictable.
Definition at line 566 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::buildRequiredMaterials(), MaterialPropertyInterface::checkBlockAndBoundaryCompatibility(), MaterialPropertyInterface::checkMaterialProperty(), and MaterialPropertyInterface::getBlockMaterialProperty().
_mi_boundary_ids
const std::set<BoundaryID>& MaterialPropertyInterface::_mi_boundary_ids private inherited
Storage for the boundary ids created by BoundaryRestrictable.
Definition at line 569 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::checkBlockAndBoundaryCompatibility(), and MaterialPropertyInterface::checkMaterialProperty().
_mi_boundary_restricted
const bool MaterialPropertyInterface::_mi_boundary_restricted private inherited
BoundaryRestricted flag.
Definition at line 563 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::checkMaterialProperty().
_mi_feproblem
FEProblemBase& MaterialPropertyInterface::_mi_feproblem protected inherited
Reference to the FEProblemBase class.
Definition at line 454 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::addConsumedPropertyName(), MaterialPropertyInterface::buildRequiredMaterials(), MaterialPropertyInterface::checkExecutionStage(), MaterialPropertyInterface::checkMaterialProperty(), MaterialPropertyInterface::getMaterialByName(), Material::getMaterialByName(), MaterialPropertyInterface::getMaterialPropertyBlockNames(), MaterialPropertyInterface::getMaterialPropertyBlocks(), MaterialPropertyInterface::getMaterialPropertyBoundaryIDs(), MaterialPropertyInterface::getMaterialPropertyBoundaryNames(), MaterialPropertyInterface::getMaxQps(), and MaterialPropertyInterface::markMatPropRequested().
_mi_moose_object
const MooseObject& MaterialPropertyInterface::_mi_moose_object private inherited
The MooseObject creating the MaterialPropertyInterface.
Definition at line 441 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::getBlockMaterialProperty(), and MaterialPropertyInterface::getGenericMaterialPropertyByName().
_mi_moose_object_name
const MooseObjectName MaterialPropertyInterface::_mi_moose_object_name protected inherited
The "complete" name of the object that this interface belongs for material property output.
Definition at line 451 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::getBlockMaterialProperty(), and MaterialPropertyInterface::getGenericMaterialPropertyByName().
_mi_name
const std::string MaterialPropertyInterface::_mi_name protected inherited
The name of the object that this interface belongs to.
Definition at line 448 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::checkMaterialProperty().
_mi_params
const InputParameters& MaterialPropertyInterface::_mi_params protected inherited
Parameters of the object with this interface.
Definition at line 445 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::checkBlockAndBoundaryCompatibility(), MaterialPropertyInterface::getMaterial(), MaterialPropertyInterface::getMaterialDataType(), and MaterialPropertyInterface::getMaterialPropertyName().
_mi_subproblem
SubProblem& MaterialPropertyInterface::_mi_subproblem protected inherited
Reference to the subproblem.
Definition at line 457 of file MaterialPropertyInterface.h.
_mi_tid
const THREAD_ID MaterialPropertyInterface::_mi_tid protected inherited
Current threaded it.
Definition at line 460 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::buildRequiredMaterials(), and MaterialPropertyInterface::getMaterialByName().
_moose_base
const MooseBase* const MooseBaseParameterInterface::_moose_base private inherited
The MooseBase object that inherits this class.
Definition at line 168 of file MooseBaseParameterInterface.h.
Referenced by MooseBaseParameterInterface::connectControllableParams(), MooseBaseParameterInterface::objectErrorPrefix(), MooseBaseParameterInterface::paramError(), and MooseBaseParameterInterface::uniqueParameterName().
_moose_object
const MooseObject& MooseVariableInterface< Real >::_moose_object private inherited
Definition at line 221 of file MooseVariableInterface.h.
_moose_variable_dependencies
std::set<MooseVariableFieldBase *> MooseVariableDependencyInterface::_moose_variable_dependencies private inherited
Definition at line 83 of file MooseVariableDependencyInterface.h.
Referenced by MooseVariableDependencyInterface::addMooseVariableDependency(), MooseVariableDependencyInterface::checkAllVariables(), and MooseVariableDependencyInterface::getMooseVariableDependencies().
_mvi_assembly
Assembly* MooseVariableInterface< Real >::_mvi_assembly protected inherited
Definition at line 218 of file MooseVariableInterface.h.
_name
const std::string& MooseBase::_name protected inherited
The name of this class, reference to value stored in InputParameters.
Definition at line 66 of file MooseBase.h.
Referenced by AddFieldSplitAction::act(), AddBCAction::act(), AddConstraintAction::act(), AddControlAction::act(), AddDamperAction::act(), AddDGKernelAction::act(), AddDiracKernelAction::act(), AddDistributionAction::act(), AddFunctionAction::act(), AddFunctorMaterialAction::act(), AddFVBCAction::act(), AddFVInitialConditionAction::act(), AddFVInterfaceKernelAction::act(), AddFVKernelAction::act(), AddIndicatorAction::act(), AddInitialConditionAction::act(), AddInterfaceKernelAction::act(), AddKernelAction::act(), AddMarkerAction::act(), AddMaterialAction::act(), AddMeshDivisionAction::act(), AddMeshGeneratorAction::act(), AddMultiAppAction::act(), AddNodalKernelAction::act(), AddOutputAction::act(), AddPeriodicBCAction::act(), AddPositionsAction::act(), AddPostprocessorAction::act(), AddReporterAction::act(), AddSamplerAction::act(), AddScalarKernelAction::act(), AddTimesAction::act(), AddTimeStepperAction::act(), AddTransferAction::act(), AddUserObjectAction::act(), AddVectorPostprocessorAction::act(), PartitionerAction::act(), ReadExecutorParamsAction::act(), SetupPreconditionerAction::act(), SetupTimeIntegratorAction::act(), AddDriftDiffusionAction::addADKernels(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromXY(), PiecewiseLinearBase::buildInterpolation(), CombinerGenerator::CombinerGenerator(), Executor::Executor(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), FunctionDT::FunctionDT(), FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), MooseBase::name(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), PiecewiseBase::setData(), and Split::setup().
_nodal
bool MooseVariableInterface< Real >::_nodal protected inherited
Whether or not this object is acting only at nodes.
Definition at line 210 of file MooseVariableInterface.h.
_oi_moose_app
MooseApp& OutputInterface::_oi_moose_app private inherited
Reference the the MooseApp; neede for access to the OutputWarehouse.
Definition at line 66 of file OutputInterface.h.
_oi_output_warehouse
OutputWarehouse& OutputInterface::_oi_output_warehouse private inherited
Reference to the OutputWarehouse for populating the Output object hide lists.
Definition at line 69 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList().
_oi_outputs
std::set<OutputName> OutputInterface::_oi_outputs private inherited
The set of Output object names listed in the 'outputs' parameter.
Definition at line 72 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList(), and OutputInterface::getOutputs().
_optional_property_proxies
std::vector<std::unique_ptr<OptionalMaterialPropertyProxyBase<MaterialPropertyInterface> > > MaterialPropertyInterface::_optional_property_proxies private inherited
optional material properties
Definition at line 573 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::getGenericOptionalMaterialProperty(), and MaterialPropertyInterface::resolveOptionalProperties().
_parent
const MooseObject & DataFileInterface< MooseObject >::_parent private inherited
Definition at line 46 of file DataFileInterface.h.
_pars
const InputParameters& MooseBaseParameterInterface::_pars protected inherited
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Definition at line 158 of file MooseBaseParameterInterface.h.
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), AddPeriodicBCAction::act(), AddVariableAction::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), FunctorMaterial::addFunctorPropertyByBlocks(), FVFluxKernel::adjustRMGhostLayers(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), PiecewiseTabularBase::buildFromFile(), PNGOutput::calculateRescalingValues(), BlockWeightedPartitioner::clone(), GridPartitioner::clone(), HierarchicalGridPartitioner::clone(), PetscExternalPartitioner::clone(), RandomPartitioner::clone(), SingleRankPartitioner::clone(), MooseBaseParameterInterface::connectControllableParams(), Console::Console(), AddVariableAction::createInitialConditionAction(), MaterialBase::declareADProperty(), MaterialBase::declareProperty(), FEProblemSolve::FEProblemSolve(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), FileMeshGenerator::generate(), MaterialBase::getGenericZeroMaterialProperty(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getParam(), MooseBaseParameterInterface::getRenamedParam(), AddVariableAction::init(), AdvancedOutput::initExecutionTypes(), Console::initialSetup(), MooseBaseParameterInterface::isParamSetByUser(), MooseBaseParameterInterface::isParamValid(), MultiApp::keepSolutionDuringRestore(), MooseBaseParameterInterface::paramErrorMsg(), GlobalParamsAction::parameters(), MooseBaseParameterInterface::parameters(), MooseMesh::prepare(), Eigenvalue::prepareSolverOptions(), MooseMesh::setCoordSystem(), MooseMesh::setPartitionerHelper(), SetupMeshAction::setupMesh(), Transient::setupTimeIntegrator(), MooseBaseParameterInterface::uniqueName(), and MooseBaseParameterInterface::uniqueParameterName().
_ppi_feproblem
const FEProblemBase& PostprocessorInterface::_ppi_feproblem private inherited
Reference the the FEProblemBase class.
Definition at line 151 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::hasPostprocessorByName(), PostprocessorInterface::isDefaultPostprocessorValueByName(), and PostprocessorInterface::postprocessorsAdded().
_ppi_moose_object
const MooseObject& PostprocessorInterface::_ppi_moose_object private inherited
The MooseObject that uses this interface.
Definition at line 145 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::checkParam(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), and PostprocessorInterface::hasPostprocessorByName().
_ppi_params
const InputParameters& PostprocessorInterface::_ppi_params private inherited
PostprocessorInterface Parameters.
Definition at line 148 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::checkParam(), PostprocessorInterface::coupledPostprocessors(), and PostprocessorInterface::getPostprocessorNameInternal().
_q_point
const MooseArray<Point>& QuadraturePointMarker::_q_point protected
Position of the current quadrature point.
Definition at line 45 of file QuadraturePointMarker.h.
_qp
unsigned int QuadraturePointMarker::_qp protected
The current quadrature point.
Definition at line 48 of file QuadraturePointMarker.h.
Referenced by computeElementMarker(), ValueRangeMarker::computeQpMarker(), and ValueThresholdMarker::computeQpMarker().
_qrule
const QBase* const& QuadraturePointMarker::_qrule protected
The quadrature rule for the system.
Definition at line 42 of file QuadraturePointMarker.h.
Referenced by computeElementMarker().
_restartable_app
MooseApp& Restartable::_restartable_app protected inherited
Reference to the application.
Definition at line 227 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp(), and Restartable::registerRestartableNameWithFilterOnApp().
_restartable_name
std::string Restartable::_restartable_name private inherited
The name of the object.
Definition at line 243 of file Restartable.h.
Referenced by Restartable::declareRestartableDataWithObjectNameWithContext(), and Restartable::restartableName().
_restartable_read_only
const bool Restartable::_restartable_read_only protected inherited
Flag for toggling read only status (see ReporterData)
Definition at line 236 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_restartable_system_name
const std::string Restartable::_restartable_system_name protected inherited
The system name this object is in.
Definition at line 230 of file Restartable.h.
Referenced by Restartable::restartableName().
_restartable_tid
const THREAD_ID Restartable::_restartable_tid protected inherited
The thread ID for this object.
Definition at line 233 of file Restartable.h.
Referenced by Restartable::declareRestartableDataHelper().
_stateful_allowed
bool MaterialPropertyInterface::_stateful_allowed protected inherited
True by default.
If false, this class throws an error if any of the stateful material properties interfaces are used.
Definition at line 521 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::getGenericMaterialProperty(), and MaterialPropertyInterface::statefulPropertiesAllowed().
_subproblem
SubProblem& Marker::_subproblem protected inherited
Definition at line 103 of file Marker.h.
_supplied
std::set<std::string> Marker::_supplied protected inherited
Definition at line 119 of file Marker.h.
Referenced by Marker::getSuppliedItems(), and Marker::Marker().
_sys
SystemBase& Marker::_sys protected inherited
Definition at line 106 of file Marker.h.
Referenced by Marker::getMarkerValue().
_third_state
MarkerValue QuadraturePointMarker::_third_state protected
The behavior to use when "in-between" other states (what to do on the fringe)
Definition at line 51 of file QuadraturePointMarker.h.
Referenced by ValueRangeMarker::computeQpMarker(), and ValueThresholdMarker::computeQpMarker().
_tid
THREAD_ID Marker::_tid protected inherited
Definition at line 108 of file Marker.h.
Referenced by Marker::getMarkerValue().
_type
const std::string& MooseBase::_type protected inherited
The type of this class.
Definition at line 63 of file MooseBase.h.
Referenced by FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), FEProblemBase::init(), FEProblemBase::solverTypeString(), and MooseBase::type().
_u
const VariableValue& QuadraturePointMarker::_u protected
Holds the solution at current quadrature points.
Definition at line 39 of file QuadraturePointMarker.h.
Referenced by ValueRangeMarker::computeQpMarker(), and ValueThresholdMarker::computeQpMarker().
_uoi_feproblem
const FEProblemBase& UserObjectInterface::_uoi_feproblem private inherited
Reference to the FEProblemBase instance.
Definition at line 128 of file UserObjectInterface.h.
Referenced by UserObjectInterface::getUserObjectBaseByName(), and UserObjectInterface::hasUserObjectByName().
_uoi_moose_object
const MooseObject& UserObjectInterface::_uoi_moose_object private inherited
Moose object using the interface.
Definition at line 125 of file UserObjectInterface.h.
Referenced by UserObjectInterface::castUserObject(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), and UserObjectInterface::getUserObjectName().
_uoi_tid
const THREAD_ID UserObjectInterface::_uoi_tid private inherited
Thread ID.
Definition at line 131 of file UserObjectInterface.h.
Referenced by UserObjectInterface::getUserObjectBaseByName().
_use_interpolated_state
const bool MaterialPropertyInterface::_use_interpolated_state protected inherited
Use the interpolated state set up through the ProjectedStatefulMaterialStorageAction.
Definition at line 539 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::getGenericMaterialPropertyByName(), and Material::getGenericMaterialPropertyByName().
_var
MooseVariableBase* MooseVariableInterface< Real >::_var protected inherited
The variable this object is acting on.
Definition at line 213 of file MooseVariableInterface.h.
_variable
MooseVariableFE<Real >* MooseVariableInterface< Real >::_variable protected inherited
Definition at line 214 of file MooseVariableInterface.h.
_vec_ids
std::vector<SubdomainID> BlockRestrictable::_vec_ids private inherited
Vector of block ids supplied by the user via the input file (for error reporting)
Definition at line 232 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
default_property_id
constexpr PropertyValue::id_type MaterialPropertyInterface::default_property_id static constexpr inherited
Initial value:
=
      PropertyValue::invalid_property_id - 1
The material property ID for a default (parsed from input) property.
Definition at line 71 of file MaterialPropertyInterface.h.
Referenced by MaterialPropertyInterface::defaultGenericMaterialProperty().
zero_property_id
constexpr PropertyValue::id_type MaterialPropertyInterface::zero_property_id = PropertyValue::invalid_property_id - 2 static constexpr inherited
The material property ID for a zero property.
Definition at line 74 of file MaterialPropertyInterface.h.
Referenced by MaterialBase::getGenericZeroMaterialProperty(), and MaterialPropertyInterface::getGenericZeroMaterialProperty().
The documentation for this class was generated from the following files:
moose/framework/include/markers/QuadraturePointMarker.h
moose/framework/src/markers/QuadraturePointMarker.C