Zapdos: DerivativeMaterialPropertyNameInterface Class Reference
DerivativeMaterialPropertyNameInterface Class Reference
#include <DerivativeMaterialPropertyNameInterface.h>
Public Types
typedef std::string SymbolName
Public Member Functions
const MaterialPropertyName derivativePropertyName (const MaterialPropertyName &base, const std::vector< SymbolName > &c) const
Helper functions to generate the material property names for the arbitrary derivatives.
const MaterialPropertyName derivativePropertyNameFirst (const MaterialPropertyName &base, const SymbolName &c1) const
Helper functions to generate the material property names for the first derivatives.
const MaterialPropertyName derivativePropertyNameSecond (const MaterialPropertyName &base, const SymbolName &c1, const SymbolName &c2) const
Helper functions to generate the material property names for the second derivatives.
const MaterialPropertyName derivativePropertyNameThird (const MaterialPropertyName &base, const SymbolName &c1, const SymbolName &c2, const SymbolName &c3) const
Helper functions to generate the material property names for the third derivatives.
const MaterialPropertyName propertyName (const MaterialPropertyName &base, const std::vector< SymbolName > &c) const
aliases for the deprecated old function names
const MaterialPropertyName propertyNameFirst (const MaterialPropertyName &base, const SymbolName &c1) const
const MaterialPropertyName propertyNameSecond (const MaterialPropertyName &base, const SymbolName &c1, const SymbolName &c2) const
const MaterialPropertyName propertyNameThird (const MaterialPropertyName &base, const SymbolName &c1, const SymbolName &c2, const SymbolName &c3) const
Detailed Description
Definition at line 22 of file DerivativeMaterialPropertyNameInterface.h.
Member Typedef Documentation
SymbolName
typedef std::string DerivativeMaterialPropertyNameInterface::SymbolName
Definition at line 25 of file DerivativeMaterialPropertyNameInterface.h.
Member Function Documentation
derivativePropertyName()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::derivativePropertyName (const MaterialPropertyName & base, const std::vector< SymbolName > & c) const
Helper functions to generate the material property names for the arbitrary derivatives.
Definition at line 16 of file DerivativeMaterialPropertyNameInterface.C.
{
  // to obtain well defined names we sort alphabetically
  std::vector<SymbolName> a(c);
  std::sort(a.begin(), a.end());
  // derivative order
  unsigned int order = a.size();
  if (order == 0)
    return base;
  // build the property name as a stringstream
  std::stringstream name;
  // build numerator
  name << 'd';
  if (order > 1)
    name << '^' << order;
  name << base << '/';
  // build denominator with 'pretty' names using exponents rather than repeat multiplication
  unsigned int exponent = 1;
  for (unsigned i = 1; i <= order; ++i)
  {
    if (i == order || a[i - 1] != a[i])
    {
      name << 'd' << a[i - 1];
      if (exponent > 1)
        name << '^' << exponent;
      exponent = 1;
    }
    else
      exponent++;
  }
  return name.str();
}
Referenced by derivativePropertyNameSecond(), derivativePropertyNameThird(), and propertyName().
derivativePropertyNameFirst()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::derivativePropertyNameFirst (const MaterialPropertyName & base, const SymbolName & c1) const
Helper functions to generate the material property names for the first derivatives.
Definition at line 56 of file DerivativeMaterialPropertyNameInterface.C.
{
  return "d" + base + "/d" + c1;
}
Referenced by propertyNameFirst().
derivativePropertyNameSecond()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::derivativePropertyNameSecond (const MaterialPropertyName & base, const SymbolName & c1, const SymbolName & c2) const
Helper functions to generate the material property names for the second derivatives.
Definition at line 63 of file DerivativeMaterialPropertyNameInterface.C.
{
  return derivativePropertyName(base, {c1, c2});
}
Referenced by propertyNameSecond().
derivativePropertyNameThird()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::derivativePropertyNameThird (const MaterialPropertyName & base, const SymbolName & c1, const SymbolName & c2, const SymbolName & c3) const
Helper functions to generate the material property names for the third derivatives.
Definition at line 70 of file DerivativeMaterialPropertyNameInterface.C.
{
  return derivativePropertyName(base, {c1, c2, c3});
}
Referenced by propertyNameThird().
propertyName()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::propertyName (const MaterialPropertyName & base, const std::vector< SymbolName > & c) const inline
aliases for the deprecated old function names
Definition at line 59 of file DerivativeMaterialPropertyNameInterface.h.
  {
    mooseDeprecated("This function was renamed to 'derivativePropertyName'");
    return derivativePropertyName(base, c);
  }
propertyNameFirst()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::propertyNameFirst (const MaterialPropertyName & base, const SymbolName & c1) const inline
Definition at line 65 of file DerivativeMaterialPropertyNameInterface.h.
  {
    mooseDeprecated("This function was renamed to 'derivativePropertyNameFirst'");
    return derivativePropertyNameFirst(base, c1);
  }
propertyNameSecond()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::propertyNameSecond (const MaterialPropertyName & base, const SymbolName & c1, const SymbolName & c2) const inline
Definition at line 71 of file DerivativeMaterialPropertyNameInterface.h.
  {
    mooseDeprecated("This function was renamed to 'derivativePropertyNameSecond'");
    return derivativePropertyNameSecond(base, c1, c2);
  }
propertyNameThird()
const MaterialPropertyName DerivativeMaterialPropertyNameInterface::propertyNameThird (const MaterialPropertyName & base, const SymbolName & c1, const SymbolName & c2, const SymbolName & c3) const inline
Definition at line 78 of file DerivativeMaterialPropertyNameInterface.h.
  {
    mooseDeprecated("This function was renamed to 'derivativePropertyNameThird'");
    return derivativePropertyNameThird(base, c1, c2, c3);
  }
The documentation for this class was generated from the following files:
moose/framework/include/materials/DerivativeMaterialPropertyNameInterface.h
moose/framework/src/materials/DerivativeMaterialPropertyNameInterface.C