Zapdos: MaterialPropertyRegistry Class Reference
MaterialPropertyRegistry Class Reference
Registry class for material property IDs and names.
#include <MaterialPropertyRegistry.h>
Classes
class WriteKey
Key that restricts writing data to the registry.
Public Member Functions
bool hasProperty (const std::string &name) const
bool hasProperty (const unsigned int id) const
unsigned int addOrGetID (const std::string &name, const WriteKey)
unsigned int getID (const std::string &name) const
std::optional< unsigned int > queryID (const std::string &name) const
const std::string & getName (const unsigned int id) const
auto idsToNamesBegin () const
auto idsToNamesEnd () const
auto idsToNamesRange () const
Private Attributes
std::unordered_map< std::string, unsigned int > _name_to_id
Map of material property name -> material property id.
std::vector< std::string > _id_to_name
Map of material property id -> material property name.
Detailed Description
Registry class for material property IDs and names.
Not thread safe.
Definition at line 26 of file MaterialPropertyRegistry.h.
Member Function Documentation
addOrGetID()
unsigned int MaterialPropertyRegistry::addOrGetID (const std::string & name, const WriteKey)
Returns
The property ID for the given name, adding the property and creating a new ID if it hasn't already been created.
Protected with the MaterialPropertyRegistry::WriteKey.
Definition at line 15 of file MaterialPropertyRegistry.C.
{
  const auto it = _name_to_id.find(name);
  if (it != _name_to_id.end())
    return it->second;
  const auto id = _id_to_name.size();
  _name_to_id.emplace(name, id);
  _id_to_name.push_back(name);
  return id;
}
Referenced by MaterialPropertyStorage::addProperty().
getID()
unsigned int MaterialPropertyRegistry::getID (const std::string & name) const
Returns
The property ID for the property with the name name
Will not create an ID if one does not exist, unlike addOrGetPropertyId
Definition at line 29 of file MaterialPropertyRegistry.C.
{
  const auto id = queryID(name);
  if (!id)
    mooseError("MaterialPropertyRegistry: Property '" + name + "' is not declared");
  return *id;
}
Referenced by MaterialData::getPropertyId(), and MaterialPropertyStorage::isStatefulProp().
getName()
const std::string & MaterialPropertyRegistry::getName (const unsigned int id) const
Returns
The property name for the property with the ID id
Definition at line 47 of file MaterialPropertyRegistry.C.
{
  if (!hasProperty(id))
    mooseError("MaterialPropertyRegistry: Property with ID ", id, " is not declared");
  return _id_to_name[id];
}
Referenced by MaterialBase::checkStatefulSanity().
hasProperty() [1/2]
bool MaterialPropertyRegistry::hasProperty (const std::string & name) const inline
Returns
True if a material property is registered with the name name
Definition at line 32 of file MaterialPropertyRegistry.h.
{ return _name_to_id.count(name); }
Referenced by getName(), and MaterialPropertyStorage::hasProperty().
hasProperty() [2/2]
bool MaterialPropertyRegistry::hasProperty (const unsigned int id) const inline
Returns
True if a material property is registered with the ID id
Definition at line 37 of file MaterialPropertyRegistry.h.
{ return id < _id_to_name.size(); }
idsToNamesBegin()
auto MaterialPropertyRegistry::idsToNamesBegin () const inline
Returns
A beginning iterator to the property ID to name map
Definition at line 78 of file MaterialPropertyRegistry.h.
{ return _id_to_name.begin(); }
Referenced by idsToNamesRange().
idsToNamesEnd()
auto MaterialPropertyRegistry::idsToNamesEnd () const inline
Returns
An end iterator to the property ID to name map
Definition at line 82 of file MaterialPropertyRegistry.h.
{ return _id_to_name.end(); }
Referenced by idsToNamesRange().
idsToNamesRange()
auto MaterialPropertyRegistry::idsToNamesRange () const inline
Returns
An iterator range to the property ID to name map
Definition at line 86 of file MaterialPropertyRegistry.h.
{ return libMesh::SimpleRange(idsToNamesBegin(), idsToNamesEnd()); }
queryID()
std::optional< unsigned int > MaterialPropertyRegistry::queryID (const std::string & name) const
Returns
The property ID for the property with the name name if a propery exists with the name, otherwise an empty optional
Definition at line 38 of file MaterialPropertyRegistry.C.
{
  const auto it = _name_to_id.find(name);
  if (it == _name_to_id.end())
    return {};
  return it->second;
}
Referenced by getID().
Member Data Documentation
_id_to_name
std::vector<std::string> MaterialPropertyRegistry::_id_to_name private
Map of material property id -> material property name.
Definition at line 92 of file MaterialPropertyRegistry.h.
Referenced by addOrGetID(), getName(), hasProperty(), idsToNamesBegin(), and idsToNamesEnd().
_name_to_id
std::unordered_map<std::string, unsigned int> MaterialPropertyRegistry::_name_to_id private
Map of material property name -> material property id.
Definition at line 90 of file MaterialPropertyRegistry.h.
Referenced by addOrGetID(), hasProperty(), and queryID().
The documentation for this class was generated from the following files:
moose/framework/include/materials/MaterialPropertyRegistry.h
moose/framework/src/materials/MaterialPropertyRegistry.C