Zapdos: TheWarehouse::QueryCache< Attribs > Class Template Reference
TheWarehouse::QueryCache< Attribs > Class Template Reference
QueryCache is a convenient way to construct and pass around (possible partially constructed) warehouse queries.
#include <TheWarehouse.h>
Public Types
typedef std::tuple< KeyType< Attribs >... > KeyTuple
typedef std::tuple< AttribType< Attribs >... > AttribTuple
Public Member Functions
QueryCache ()
QueryCache (TheWarehouse &w)
Creates a new query operating on the given warehouse w.
template<typename T >
QueryCache (const T &q)
QueryCache & operator= (const QueryCache &other)
template<typename T >
QueryCache & operator= (const T &q)
Copy constructor from another Query.
QueryCache (const QueryCache &other)
template<typename T , typename... Args>
QueryCache & condition (Args &&... args)
Adds a new condition to the query.
QueryCache clone () const
clone creates and returns an independent copy of the query in its current state.
std::size_t count ()
count returns the number of results that match the query (this requires actually running the query).
TheWarehouse & warehouse () const
std::vector< std::unique_ptr< Attribute > > attributes () const
attribs returns a copy of the constructed Attribute list for the query in its current state.
template<typename T , typename... Args>
std::vector< T * > & queryInto (std::vector< T * > &results, Args &&... args)
queryInto executes the query and stores the results in the given vector.
template<typename T , typename... Args>
std::vector< T * > & queryIntoUnsorted (std::vector< T * > &results, Args &&... args)
queryInto executes the query and stores the results in the given vector.
std::size_t numAttribs () const
Gets the number of attributes associated with the cached query.
Private Member Functions
template<typename T , typename... Args>
std::vector< T * > & queryIntoHelper (std::vector< T * > &results, const bool sort, Args &&... args)
queryInto executes the query and stores the results in the given vector.
template<int Index, typename A , typename... As>
void addAttribs ()
template<int Index>
void addAttribs ()
template<int Index, typename K , typename... Args>
void setKeysInner (K &k, Args &... args)
template<int Index>
void setKeysInner ()
template<int Index, typename K , typename... Args>
void setAttribsInner (K k, Args &... args)
template<int Index>
void setAttribsInner ()
Private Attributes
TheWarehouse * _w = nullptr
std::vector< std::unique_ptr< Attribute > > _attribs
KeyTuple _key_tup
AttribTuple _attrib_tup
std::map< std::pair< bool, KeyTuple >, std::size_t > _cache
std::mutex _cache_mutex
Detailed Description
template<typename... Attribs>
class TheWarehouse::QueryCache< Attribs >
QueryCache is a convenient way to construct and pass around (possible partially constructed) warehouse queries.
The warehouse's "query()" or "queryCache(...)" functions should generally be used to create new Query objects rather than constructing them directly. A Query object holds a list of persistent conditions used to filter/select objects from the warehouse. When the query is executed/run, results are filtered by "and"ing each condition together - i.e. only objects that match all conditions are returned.
Template arguments (i.e. Attribs) are used to specify parametrized query conditions. The passed template parameters should be the Attribute classes you want to use for parameterization (i.e. the values that will change from query to query).
Definition at line 207 of file TheWarehouse.h.
Member Typedef Documentation
AttribTuple
template<typename... Attribs> typedef std::tuple<AttribType<Attribs>...> TheWarehouse::QueryCache< Attribs >::AttribTuple
Definition at line 211 of file TheWarehouse.h.
KeyTuple
template<typename... Attribs> typedef std::tuple<KeyType<Attribs>...> TheWarehouse::QueryCache< Attribs >::KeyTuple
Definition at line 210 of file TheWarehouse.h.
Constructor & Destructor Documentation
QueryCache() [1/4]
template<typename... Attribs> TheWarehouse::QueryCache< Attribs >::QueryCache () inline
Definition at line 213 of file TheWarehouse.h.
{}
QueryCache() [2/4]
template<typename... Attribs> TheWarehouse::QueryCache< Attribs >::QueryCache (TheWarehouse & w) inline
Creates a new query operating on the given warehouse w.
You should generally use TheWarehouse::query() instead.
Definition at line 217 of file TheWarehouse.h.
                                 : _w(&w)
    {
      addAttribs<0, Attribs...>();
      _attribs.reserve(5);
    }
QueryCache() [3/4]
template<typename... Attribs> template<typename T > TheWarehouse::QueryCache< Attribs >::QueryCache (const T & q) inline
Definition at line 224 of file TheWarehouse.h.
                            : _w(&q.warehouse())
    {
      addAttribs<0, Attribs...>();
      _attribs.reserve(5);
      for (auto & attrib : q.attributes())
        _attribs.push_back(attrib->clone());
    }
QueryCache() [4/4]
template<typename... Attribs> TheWarehouse::QueryCache< Attribs >::QueryCache (const QueryCache< Attribs > & other) inline
Definition at line 268 of file TheWarehouse.h.
                                         : _w(other._w), _key_tup(other._key_tup)
    {
      // do NOT copy the cache.
      // initialize parametrized attributes and tuple:
      addAttribs<0, Attribs...>(); // MUST have own pointers to attribs to avoid data races.
      for (std::size_t i = std::tuple_size<AttribTuple>::value; i < other._attribs.size(); i++)
        _attribs.push_back(other._attribs[i]->clone());
    }
Member Function Documentation
addAttribs() [1/2]
template<typename... Attribs> template<int Index, typename A , typename... As> void TheWarehouse::QueryCache< Attribs >::addAttribs () inline private
Definition at line 366 of file TheWarehouse.h.
    {
      std::get<Index>(_attrib_tup) = new A(*_w);
      _attribs.emplace_back(std::get<Index>(_attrib_tup));
      addAttribs<Index + 1, As...>();
    }
Referenced by TheWarehouse::QueryCache< Attribs >::addAttribs(), TheWarehouse::QueryCache< Attribs >::operator=(), and TheWarehouse::QueryCache< Attribs >::QueryCache().
addAttribs() [2/2]
template<typename... Attribs> template<int Index> void TheWarehouse::QueryCache< Attribs >::addAttribs () inline private
Definition at line 373 of file TheWarehouse.h.
    {
    }
attributes()
template<typename... Attribs> std::vector< std::unique_ptr< Attribute > > TheWarehouse::QueryCache< Attribs >::attributes () const inline
attribs returns a copy of the constructed Attribute list for the query in its current state.
Definition at line 299 of file TheWarehouse.h.
{ return clone()._attribs; }
clone()
template<typename... Attribs> QueryCache TheWarehouse::QueryCache< Attribs >::clone () const inline
clone creates and returns an independent copy of the query in its current state.
Definition at line 291 of file TheWarehouse.h.
{ return Query(*this); }
Referenced by TheWarehouse::QueryCache< Attribs >::attributes(), FEProblemBase::computeUserObjectsInternal(), BoundaryNodeIntegrityCheckThread::onNode(), ComputeNodalUserObjectsThread::onNode(), BoundaryElemIntegrityCheckThread::operator()(), ComputeNodalUserObjectsThread::printGeneralExecutionInformation(), ComputeNodalUserObjectsThread::subdomainChanged(), and ComputeUserObjectsThread::subdomainChanged().
condition()
template<typename... Attribs> template<typename T , typename... Args> QueryCache & TheWarehouse::QueryCache< Attribs >::condition (Args &&... args) inline
Adds a new condition to the query.
The template parameter T is the Attribute class of interest and args are forwarded to T's constructor to build+add the attribute in-situ. Conditions represent persistent query conditions that do not change from query to query for a particular QueryCache instance.
Definition at line 283 of file TheWarehouse.h.
    {
      _attribs.emplace_back(new T(*_w, std::forward<Args>(args)...));
      _cache.clear(); // invalidate cache if base query changes.
      return *this;
    }
Referenced by DumpObjectsProblem::addAuxVariable(), FEProblemBase::checkUserObjectJacobianRequirement(), FEProblemBase::checkUserObjects(), NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::computeResidualInternal(), FEProblemBase::computeUserObjectByName(), FEProblemBase::computeUserObjects(), FEProblemBase::computeUserObjectsInternal(), FEProblemBase::customSetup(), FEProblemBase::executeSamplers(), FEProblemBase::getDistribution(), FEProblemBase::getMortarUserObjects(), FEProblemBase::getPositionsObject(), FEProblemBase::getSampler(), CompositionDT::getTimeSteppers(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), FEProblemBase::hasUserObject(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), FEProblemBase::joinAndFinalize(), BoundaryNodeIntegrityCheckThread::onNode(), ComputeNodalUserObjectsThread::onNode(), BoundaryElemIntegrityCheckThread::operator()(), JSONOutput::outputReporters(), ComputeNodalUserObjectsThread::printGeneralExecutionInformation(), ComputeNodalUserObjectsThread::subdomainChanged(), and ComputeUserObjectsThread::subdomainChanged().
count()
template<typename... Attribs> std::size_t TheWarehouse::QueryCache< Attribs >::count () inline
count returns the number of results that match the query (this requires actually running the query).
Definition at line 294 of file TheWarehouse.h.
{ return _w->count(_attribs); }
numAttribs()
template<typename... Attribs> std::size_t TheWarehouse::QueryCache< Attribs >::numAttribs () const inline
Gets the number of attributes associated with the cached query.
Definition at line 329 of file TheWarehouse.h.
{ return _attribs.size(); }
operator=() [1/2]
template<typename... Attribs> QueryCache & TheWarehouse::QueryCache< Attribs >::operator= (const QueryCache< Attribs > & other) inline
Definition at line 233 of file TheWarehouse.h.
    {
      if (this == &other)
        return *this;
      _attribs.clear();
      _w = other._w;
      // MUST have own pointers to attribs to avoid data races - don't copy _key_attribs.
      // initialize parametrized attributes and tuple:
      addAttribs<0, Attribs...>();
      _key_tup = other._key_tup;
      // do NOT copy the cache.
      // only copy over non-parametrized attributes
      for (std::size_t i = std::tuple_size<AttribTuple>::value; i < other._attribs.size(); i++)
        _attribs.push_back(other._attribs[i]->clone());
      return *this;
    }
operator=() [2/2]
template<typename... Attribs> template<typename T > QueryCache & TheWarehouse::QueryCache< Attribs >::operator= (const T & q) inline
Copy constructor from another Query.
Definition at line 254 of file TheWarehouse.h.
    {
      _attribs.clear();
      _w = &q.warehouse();
      addAttribs<0, Attribs...>();
      _attribs.reserve(5);
      for (auto & attrib : q.attributes())
        _attribs.push_back(attrib->clone());
      return *this;
    }
queryInto()
template<typename... Attribs> template<typename T , typename... Args> std::vector< T * > & TheWarehouse::QueryCache< Attribs >::queryInto (std::vector< T * > & results, Args &&... args) inline
queryInto executes the query and stores the results in the given vector.
For parametrized queries (i.e. QueryCaches created with more than zero template arguments) args must contain one value for each parametrized query attribute - the types of args should be equal to the ::Key typedef specified for each corresponding parametrized attribute. All results must be castable to the templated type T. If the objects we are querying into inherit from the dependency resolver interface, then they will be sorted
Definition at line 310 of file TheWarehouse.h.
    {
      return queryIntoHelper(results, true, args...);
    }
Referenced by CheckFVBCAction::act(), DumpObjectsProblem::addAuxVariable(), NonlinearSystemBase::checkKernelCoverage(), ComputeResidualAndJacobianThread::compute(), NonlinearSystemBase::customSetup(), ComputeResidualAndJacobianThread::determineObjectWarehouses(), ComputeResidualThread::determineObjectWarehouses(), NonlinearSystemBase::initialSetup(), FEProblemBase::joinAndFinalize(), ComputeUserObjectsThread::queryBoundary(), ComputeUserObjectsThread::querySubdomain(), and NonlinearSystemBase::timestepSetup().
queryIntoHelper()
template<typename... Attribs> template<typename T , typename... Args> std::vector< T * > & TheWarehouse::QueryCache< Attribs >::queryIntoHelper (std::vector< T * > & results, const bool sort, Args &&... args) inline private
queryInto executes the query and stores the results in the given vector.
For parametrized queries (i.e. QueryCaches created with more than zero template arguments) args must contain one value for each parametrized query attribute - the types of args should be equal to the ::Key typedef specified for each corresponding parametrized attribute. All results must be castable to the templated type T. If the objects we are querying into inherit from the dependency resolver interface, then they will be sorted if sort is true
Definition at line 341 of file TheWarehouse.h.
    {
      std::lock_guard<std::mutex> lock(_cache_mutex);
      setKeysInner<0, KeyType<Attribs>...>(args...);
      std::size_t query_id;
      const auto entry = _cache.find(std::make_pair(sort, _key_tup));
      if (entry == _cache.end())
      {
        setAttribsInner<0, KeyType<Attribs>...>(args...);
        // add the sort attribute. No need (I think) to clear the cache because the base query is
        // not changing
        _attribs.emplace_back(new AttribSorted(*_w, sort));
        query_id = _w->queryID(_attribs);
        _cache[std::make_pair(sort, _key_tup)] = query_id;
        // remove the sort attribute
        _attribs.pop_back();
      }
      else
        query_id = entry->second;
      return _w->queryInto(query_id, results);
    }
Referenced by TheWarehouse::QueryCache< Attribs >::queryInto(), and TheWarehouse::QueryCache< Attribs >::queryIntoUnsorted().
queryIntoUnsorted()
template<typename... Attribs> template<typename T , typename... Args> std::vector< T * > & TheWarehouse::QueryCache< Attribs >::queryIntoUnsorted (std::vector< T * > & results, Args &&... args) inline
queryInto executes the query and stores the results in the given vector.
For parametrized queries (i.e. QueryCaches created with more than zero template arguments) args must contain one value for each parametrized query attribute - the types of args should be equal to the ::Key typedef specified for each corresponding parametrized attribute. All results must be castable to the templated type T. These objects will not be sorted
Definition at line 323 of file TheWarehouse.h.
    {
      return queryIntoHelper(results, false, args...);
    }
Referenced by FEProblemBase::computeUserObjectsInternal().
setAttribsInner() [1/2]
template<typename... Attribs> template<int Index> void TheWarehouse::QueryCache< Attribs >::setAttribsInner () inline private
Definition at line 395 of file TheWarehouse.h.
    {
    }
Referenced by TheWarehouse::QueryCache< Attribs >::setAttribsInner().
setAttribsInner() [2/2]
template<typename... Attribs> template<int Index, typename K , typename... Args> void TheWarehouse::QueryCache< Attribs >::setAttribsInner (K k, Args &... args) inline private
Definition at line 389 of file TheWarehouse.h.
    {
      std::get<Index>(_attrib_tup)->setFrom(k);
      setAttribsInner<Index + 1, Args...>(args...);
    }
setKeysInner() [1/2]
template<typename... Attribs> template<int Index> void TheWarehouse::QueryCache< Attribs >::setKeysInner () inline private
Definition at line 384 of file TheWarehouse.h.
    {
    }
Referenced by TheWarehouse::QueryCache< Attribs >::setKeysInner().
setKeysInner() [2/2]
template<typename... Attribs> template<int Index, typename K , typename... Args> void TheWarehouse::QueryCache< Attribs >::setKeysInner (K & k, Args &... args) inline private
Definition at line 378 of file TheWarehouse.h.
    {
      std::get<Index>(_key_tup) = k;
      setKeysInner<Index + 1, Args...>(args...);
    }
warehouse()
template<typename... Attribs> TheWarehouse & TheWarehouse::QueryCache< Attribs >::warehouse () const inline
Definition at line 296 of file TheWarehouse.h.
{ return *_w; }
Member Data Documentation
_attrib_tup
template<typename... Attribs> AttribTuple TheWarehouse::QueryCache< Attribs >::_attrib_tup private
Definition at line 403 of file TheWarehouse.h.
Referenced by TheWarehouse::QueryCache< Attribs >::addAttribs(), and TheWarehouse::QueryCache< Attribs >::setAttribsInner().
_attribs
template<typename... Attribs> std::vector<std::unique_ptr<Attribute> > TheWarehouse::QueryCache< Attribs >::_attribs private
Definition at line 400 of file TheWarehouse.h.
Referenced by TheWarehouse::QueryCache< Attribs >::addAttribs(), TheWarehouse::QueryCache< Attribs >::attributes(), TheWarehouse::QueryCache< Attribs >::condition(), TheWarehouse::QueryCache< Attribs >::count(), TheWarehouse::QueryCache< Attribs >::numAttribs(), TheWarehouse::QueryCache< Attribs >::operator=(), TheWarehouse::QueryCache< Attribs >::QueryCache(), and TheWarehouse::QueryCache< Attribs >::queryIntoHelper().
_cache
template<typename... Attribs> std::map<std::pair<bool, KeyTuple>, std::size_t> TheWarehouse::QueryCache< Attribs >::_cache private
Definition at line 404 of file TheWarehouse.h.
Referenced by TheWarehouse::QueryCache< Attribs >::condition(), and TheWarehouse::QueryCache< Attribs >::queryIntoHelper().
_cache_mutex
template<typename... Attribs> std::mutex TheWarehouse::QueryCache< Attribs >::_cache_mutex private
Definition at line 405 of file TheWarehouse.h.
Referenced by TheWarehouse::QueryCache< Attribs >::queryIntoHelper().
_key_tup
template<typename... Attribs> KeyTuple TheWarehouse::QueryCache< Attribs >::_key_tup private
Definition at line 402 of file TheWarehouse.h.
Referenced by TheWarehouse::QueryCache< Attribs >::operator=(), TheWarehouse::QueryCache< Attribs >::queryIntoHelper(), and TheWarehouse::QueryCache< Attribs >::setKeysInner().
_w
template<typename... Attribs> TheWarehouse* TheWarehouse::QueryCache< Attribs >::_w = nullptr private
Definition at line 399 of file TheWarehouse.h.
Referenced by TheWarehouse::QueryCache< Attribs >::addAttribs(), TheWarehouse::QueryCache< Attribs >::condition(), TheWarehouse::QueryCache< Attribs >::count(), TheWarehouse::QueryCache< Attribs >::operator=(), TheWarehouse::QueryCache< Attribs >::queryIntoHelper(), and TheWarehouse::QueryCache< Attribs >::warehouse().
The documentation for this class was generated from the following file:
moose/framework/include/base/TheWarehouse.h