Zapdos: AttribSorted Class Reference
AttribSorted Class Reference abstract
This attribute describes sorting state.
#include <TheWarehouse.h>
Public Types
typedef bool Key
Public Member Functions
void setFrom (const Key &k)
AttribSorted (TheWarehouse &w)
AttribSorted (TheWarehouse &w, bool is_sorted)
AttribSorted (const AttribSorted &)=default
AttribSorted (AttribSorted &&)=default
AttribSorted & operator= (const AttribSorted &)=default
AttribSorted & operator= (AttribSorted &&)=default
virtual void initFrom (const MooseObject *obj) override
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
virtual bool isMatch (const Attribute &other) const override
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
virtual bool isEqual (const Attribute &other) const override
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
hashfunc (_val)
clonefunc (AttribSorted)
bool operator== (const Attribute &other) const
bool operator!= (const Attribute &other) const
unsigned int id () const
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
virtual std::size_t hash () const =0
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
virtual std::unique_ptr< Attribute > clone () const =0
clone creates and returns and identical (deep) copy of this attribute - i.e.
Private Attributes
bool _val
bool _initd
int _id = -1
Detailed Description
This attribute describes sorting state.
Definition at line 111 of file TheWarehouse.h.
Member Typedef Documentation
Key
typedef bool AttribSorted::Key
Definition at line 114 of file TheWarehouse.h.
Constructor & Destructor Documentation
AttribSorted() [1/4]
AttribSorted::AttribSorted (TheWarehouse & w) inline
Definition at line 117 of file TheWarehouse.h.
: Attribute(w, "sorted"), _val(false), _initd(false) {}
AttribSorted() [2/4]
AttribSorted::AttribSorted (TheWarehouse & w, bool is_sorted) inline
Definition at line 118 of file TheWarehouse.h.
    : Attribute(w, "sorted"), _val(is_sorted), _initd(true)
  {
  }
AttribSorted() [3/4]
AttribSorted::AttribSorted (const AttribSorted &) default
AttribSorted() [4/4]
AttribSorted::AttribSorted (AttribSorted &&) default
Member Function Documentation
clone()
virtual std::unique_ptr< Attribute > Attribute::clone () const pure virtual inherited
clone creates and returns and identical (deep) copy of this attribute - i.e.
the result of clone should return true if passed into isMatch.
Referenced by FEProblemBase::computeUserObjectsInternal(), and TheWarehouse::update().
clonefunc()
AttribSorted::clonefunc (AttribSorted)
hash()
virtual std::size_t Attribute::hash () const pure virtual inherited
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
is initialized with). Ideally, the data should be uniformly and randomly distributed across the domain of size_t values - e.g. 1 and 2 should hash to completely unrelated values. Use of std::hash for POD is encouraged. A convenience hash_combine function is also provided to combine the results an existing hash with one or more other values.
Referenced by std::hash< Attribute >::operator()().
hashfunc()
AttribSorted::hashfunc (_val)
id()
unsigned int Attribute::id () const inline inherited
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
This ID is determined at construction time this
Definition at line 66 of file TheWarehouse.h.
{ return _id; }
Referenced by std::hash< Attribute >::operator()().
initFrom()
void AttribSorted::initFrom (const MooseObject * obj) override virtual
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
Implements Attribute.
Definition at line 39 of file TheWarehouse.C.
{
}
isEqual()
bool AttribSorted::isEqual (const Attribute & other) const override virtual
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
isEqual does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 51 of file TheWarehouse.C.
{
  return isMatch(other);
}
isMatch()
bool AttribSorted::isMatch (const Attribute & other) const override virtual
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
This is is for query matching - not exact equivalence. isMatch does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 44 of file TheWarehouse.C.
{
  auto a = dynamic_cast<const AttribSorted *>(&other);
  return _initd && a && a->_initd && (a->_val == _val);
}
Referenced by isEqual().
operator!=()
bool Attribute::operator!= (const Attribute & other) const inline inherited
Definition at line 61 of file TheWarehouse.h.
{ return !(*this == other); }
operator=() [1/2]
AttribSorted & AttribSorted::operator= (AttribSorted &&) default
operator=() [2/2]
AttribSorted & AttribSorted::operator= (const AttribSorted &) default
operator==()
bool Attribute::operator== (const Attribute & other) const inline inherited
Definition at line 57 of file TheWarehouse.h.
  {
    return _id == other._id && isEqual(other);
  }
setFrom()
void AttribSorted::setFrom (const Key & k) inline
Definition at line 115 of file TheWarehouse.h.
{ _val = k; }
Member Data Documentation
_id
int Attribute::_id = -1 private inherited
Definition at line 91 of file TheWarehouse.h.
Referenced by Attribute::id(), and Attribute::operator==().
_initd
bool AttribSorted::_initd private
Definition at line 135 of file TheWarehouse.h.
Referenced by isMatch().
_val
bool AttribSorted::_val private
Definition at line 134 of file TheWarehouse.h.
Referenced by isMatch(), and setFrom().
The documentation for this class was generated from the following files:
moose/framework/include/base/TheWarehouse.h
moose/framework/src/base/TheWarehouse.C