Zapdos: FileLineInfoMap Class Reference
FileLineInfoMap Class Reference
A mapping between a series of keys to a FileLineInfo.
#include <FileLineInfo.h>
Public Member Functions
void addInfo (const std::string &key0, const std::string &file, int line)
Associate a key with file/line info.
void addInfo (const std::string &key0, const std::string &key1, const std::string &file, int line)
Associate a key with file/line info.
void addInfo (const std::string &key0, const std::string &key1, const std::string &key2, const std::string &file, int line)
Associate a key with file/line info.
FileLineInfo getInfo (const std::string &key0) const
Get file/line info for a key.
FileLineInfo getInfo (const std::string &key0, const std::string &key1) const
Get file/line info for a pair of keys.
FileLineInfo getInfo (const std::string &key0, const std::string &key1, const std::string &key2) const
Get file/line info for a pair of keys.
Protected Member Functions
std::string makeKey (const std::string &key0, const std::string &key1) const
Makes a unique key for the map given two strings.
std::string makeKey (const std::string &key0, const std::string &key1, const std::string &key2) const
Makes a unique key given three strings.
Protected Attributes
std::map< std::string, FileLineInfo > _map
Detailed Description
A mapping between a series of keys to a FileLineInfo.
This is intended to replace having a std::pair or a std::tuple as a key to a map holding the FileLineInfo.
Definition at line 40 of file FileLineInfo.h.
Member Function Documentation
addInfo() [1/3]
void FileLineInfoMap::addInfo (const std::string & key0, const std::string & file, int line)
Associate a key with file/line info.
Parameters
key0 Key
file file
line line number
Definition at line 35 of file FileLineInfo.C.
{
  FileLineInfo f(file, line);
  if (f.isValid())
    _map[key0] = f;
}
Referenced by addInfo(), ActionFactory::reg(), Factory::reg(), and Syntax::registerActionSyntax().
addInfo() [2/3]
void FileLineInfoMap::addInfo (const std::string & key0, const std::string & key1, const std::string & file, int line)
Associate a key with file/line info.
Parameters
key0 Key
key1 Key
file file
line line number
Definition at line 43 of file FileLineInfo.C.
{
  addInfo(makeKey(key0, key1), file, line);
}
addInfo() [3/3]
void FileLineInfoMap::addInfo (const std::string & key0, const std::string & key1, const std::string & key2, const std::string & file, int line)
Associate a key with file/line info.
Parameters
key0 Key
key1 Key
key2 Key
file file
line line number
Definition at line 52 of file FileLineInfo.C.
{
  addInfo(makeKey(key0, key1, key2), file, line);
}
getInfo() [1/3]
FileLineInfo FileLineInfoMap::getInfo (const std::string & key0) const
Get file/line info for a key.
Parameters
key0 Key
Returns
FileLineInfo
Definition at line 76 of file FileLineInfo.C.
{
  auto it = _map.find(key0);
  if (it == _map.end())
    return FileLineInfo();
  return it->second;
}
Referenced by getInfo(), Factory::getLineInfo(), ActionFactory::getLineInfo(), Syntax::getLineInfo(), and Factory::reg().
getInfo() [2/3]
FileLineInfo FileLineInfoMap::getInfo (const std::string & key0, const std::string & key1) const
Get file/line info for a pair of keys.
Parameters
key0 Key
key1 Key
Returns
FileLineInfo
Definition at line 85 of file FileLineInfo.C.
{
  return getInfo(makeKey(key0, key1));
}
getInfo() [3/3]
FileLineInfo FileLineInfoMap::getInfo (const std::string & key0, const std::string & key1, const std::string & key2) const
Get file/line info for a pair of keys.
Parameters
key0 Key
key1 Key
key2 Key
Returns
FileLineInfo
Definition at line 91 of file FileLineInfo.C.
{
  return getInfo(makeKey(key0, key1, key2));
}
makeKey() [1/2]
std::string FileLineInfoMap::makeKey (const std::string & key0, const std::string & key1) const protected
Makes a unique key for the map given two strings.
Definition at line 62 of file FileLineInfo.C.
{
  return key0 + "%" + key1;
}
Referenced by addInfo(), and getInfo().
makeKey() [2/2]
std::string FileLineInfoMap::makeKey (const std::string & key0, const std::string & key1, const std::string & key2) const protected
Makes a unique key given three strings.
Definition at line 68 of file FileLineInfo.C.
{
  return key0 + "%" + key1 + "%" + key2;
}
Member Data Documentation
_map
std::map<std::string, FileLineInfo> FileLineInfoMap::_map protected
Definition at line 111 of file FileLineInfo.h.
Referenced by addInfo(), and getInfo().
The documentation for this class was generated from the following files:
moose/framework/include/utils/FileLineInfo.h
moose/framework/src/utils/FileLineInfo.C