Zapdos: SplineInterpolation Class Reference
SplineInterpolation Class Reference
This class interpolates tabulated functions with cubic splines.
#include <SplineInterpolation.h>
Public Member Functions
SplineInterpolation ()
SplineInterpolation (const std::vector< Real > &x, const std::vector< Real > &y, Real yp1=_deriv_bound, Real ypn=_deriv_bound)
Construct the object.
virtual ~SplineInterpolation ()=default
void setData (const std::vector< Real > &x, const std::vector< Real > &y, Real yp1=_deriv_bound, Real ypn=_deriv_bound)
Set the x-, y- values and first derivatives.
void errorCheck ()
Real sample (Real x) const
This function will take an independent variable input and will return the dependent variable based on the generated fit.
ADReal sample (const ADReal &x) const
Real sampleDerivative (Real x) const
Real sample2ndDerivative (Real x) const
unsigned int getSampleSize ()
This function returns the size of the array holding the points, i.e.
Real domain (int i) const
Real range (int i) const
Real sample (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, Real x_int) const
ADReal sample (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, const ADReal &x_int) const
Real sampleDerivative (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, Real x_int) const
Real sample2ndDerivative (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, Real x_int) const
Protected Member Functions
void solve ()
template<typename T >
T sample (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, const T &x_int, unsigned int klo, unsigned int khi) const
Sample value at point x_int given the indices of the vector of dependent values that bound the point.
void spline (const std::vector< Real > &x, const std::vector< Real > &y, std::vector< Real > &y2, Real yp1=_deriv_bound, Real ypn=_deriv_bound)
This function calculates the second derivatives based on supplied x and y-vectors.
void findInterval (const std::vector< Real > &x, Real x_int, unsigned int &klo, unsigned int &khi) const
template<typename T >
void computeCoeffs (const std::vector< Real > &x, unsigned int klo, unsigned int khi, const T &x_int, Real &h, T &a, T &b) const
Protected Attributes
std::vector< Real > _x
std::vector< Real > _y
Real _yp1
boundary conditions
Real _ypn
std::vector< Real > _y2
Second derivatives.
Static Protected Attributes
static int _file_number = 0
static const Real _deriv_bound = std::numeric_limits<Real>::max()
Detailed Description
This class interpolates tabulated functions with cubic splines.
Adopted from Numerical Recipes in C (section 3.3).
Definition at line 20 of file SplineInterpolation.h.
Constructor & Destructor Documentation
SplineInterpolation() [1/2]
SplineInterpolation::SplineInterpolation ()
Definition at line 20 of file SplineInterpolation.C.
{}
SplineInterpolation() [2/2]
SplineInterpolation::SplineInterpolation (const std::vector< Real > & x, const std::vector< Real > & y, Real yp1 = _deriv_bound, Real ypn = _deriv_bound)
Construct the object.
Parameters
x Tabulated function (x-positions)
y Tabulated function (y-positions)
yp1 First derivative of the interpolating function at point 1
ypn First derivative of the interpolating function at point n
If yp1, ypn are not specified or greater or equal that _deriv_bound, we use natural spline
Definition at line 22 of file SplineInterpolation.C.
  : SplineInterpolationBase(), _x(x), _y(y), _yp1(yp1), _ypn(ypn)
{
  errorCheck();
  solve();
}
~SplineInterpolation()
virtual SplineInterpolation::~SplineInterpolation () virtual default
Member Function Documentation
computeCoeffs()
template<typename T > void SplineInterpolationBase::computeCoeffs (const std::vector< Real > & x, unsigned int klo, unsigned int khi, const T & x_int, Real & h, T & a, T & b) const protected inherited
Definition at line 85 of file SplineInterpolationBase.C.
{
  h = x[khi] - x[klo];
  if (h == 0)
    mooseError("The values of x must be distinct");
  a = (x[khi] - x_int) / h;
  b = (x_int - x[klo]) / h;
}
Referenced by SplineInterpolationBase::sample(), SplineInterpolationBase::sample2ndDerivative(), and SplineInterpolationBase::sampleDerivative().
domain()
Real SplineInterpolation::domain (int i) const
Definition at line 92 of file SplineInterpolation.C.
{
  return _x[i];
}
errorCheck()
void SplineInterpolation::errorCheck ()
Definition at line 47 of file SplineInterpolation.C.
{
  if (_x.size() != _y.size())
    mooseError("SplineInterpolation: vectors are not the same length");
  bool error = false;
  for (unsigned i = 0; !error && i + 1 < _x.size(); ++i)
    if (_x[i] >= _x[i + 1])
      error = true;
  if (error)
    mooseError("x-values are not strictly increasing");
}
Referenced by setData(), and SplineInterpolation().
findInterval()
void SplineInterpolationBase::findInterval (const std::vector< Real > & x, Real x_int, unsigned int & klo, unsigned int & khi) const protected inherited
Definition at line 65 of file SplineInterpolationBase.C.
{
  klo = 0;
  mooseAssert(x.size() >= 2, "You must have at least two knots to create a spline.");
  khi = x.size() - 1;
  while (khi - klo > 1)
  {
    unsigned int k = (khi + klo) >> 1;
    if (x[k] > x_int)
      khi = k;
    else
      klo = k;
  }
}
Referenced by BicubicSplineInterpolation::constructColumnSpline(), BicubicSplineInterpolation::constructRowSpline(), SplineInterpolationBase::sample(), SplineInterpolationBase::sample2ndDerivative(), and SplineInterpolationBase::sampleDerivative().
getSampleSize()
unsigned int SplineInterpolation::getSampleSize ()
This function returns the size of the array holding the points, i.e.
the number of sample points
Definition at line 104 of file SplineInterpolation.C.
{
  return _x.size();
}
range()
Real SplineInterpolation::range (int i) const
Definition at line 98 of file SplineInterpolation.C.
{
  return _y[i];
}
sample() [1/5]
ADReal SplineInterpolation::sample (const ADReal & x) const
Definition at line 74 of file SplineInterpolation.C.
{
  return SplineInterpolationBase::sample(_x, _y, _y2, x);
}
sample() [2/5]
ADReal SplineInterpolationBase::sample (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, const ADReal & x_int) const inherited
Definition at line 113 of file SplineInterpolationBase.C.
{
  unsigned int klo, khi;
  findInterval(x, MetaPhysicL::raw_value(x_int), klo, khi);
  return sample(x, y, y2, x_int, klo, khi);
}
sample() [3/5]
template<typename T > T SplineInterpolationBase::sample (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, const T & x_int, unsigned int klo, unsigned int khi) const protected inherited
Sample value at point x_int given the indices of the vector of dependent values that bound the point.
This method is useful in bicubic spline interpolation, where several spline evaluations are needed to sample from a 2D point.
Definition at line 157 of file SplineInterpolationBase.C.
{
  Real h;
  T a, b;
  computeCoeffs(x, klo, khi, x_int, h, a, b);
  return a * y[klo] + b * y[khi] +
         ((a * a * a - a) * y2[klo] + (b * b * b - b) * y2[khi]) * (h * h) / 6.0;
}
sample() [4/5]
Real SplineInterpolationBase::sample (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, Real x_int) const inherited
Definition at line 101 of file SplineInterpolationBase.C.
{
  unsigned int klo, khi;
  findInterval(x, x_int, klo, khi);
  return sample(x, y, y2, x_int, klo, khi);
}
Referenced by BicubicSplineInterpolation::constructColumnSpline(), BicubicSplineInterpolation::constructRowSpline(), SplineInterpolationBase::sample(), sample(), BicubicSplineInterpolation::sample(), and BicubicSplineInterpolation::sampleValueAndDerivatives().
sample() [5/5]
Real SplineInterpolation::sample (Real x) const
This function will take an independent variable input and will return the dependent variable based on the generated fit.
Definition at line 68 of file SplineInterpolation.C.
{
  return SplineInterpolationBase::sample(_x, _y, _y2, x);
}
Referenced by ADEEDFRateConstantTownsend::computeQpProperties(), ADZapdosEEDFRateConstant::computeQpProperties(), EEDFRateConstant::computeQpProperties(), EEDFRateConstantTownsend::computeQpProperties(), InterpolatedCoefficientSpline::computeQpProperties(), ZapdosEEDFRateConstant::computeQpProperties(), ElectricField::computeQpProperties(), ADGasElectronMoments::computeQpProperties(), Gas::computeQpProperties(), GasBase::computeQpProperties(), GasElectronMoments::computeQpProperties(), DataRead::computeValue(), ElectronMobility::computeValue(), ScalarSplineInterpolation::computeValue(), BoltzmannSolverScalar::electron_mobility_sample(), ValueProvider::electron_temperature(), BoltzmannSolverScalar::electron_temperature_sample(), RateCoefficientProvider::reaction_coefficient(), and SplineFunction::value().
sample2ndDerivative() [1/2]
Real SplineInterpolationBase::sample2ndDerivative (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, Real x_int) const inherited
Definition at line 141 of file SplineInterpolationBase.C.
{
  unsigned int klo, khi;
  findInterval(x, x_int, klo, khi);
  Real h, a, b;
  computeCoeffs(x, klo, khi, x_int, h, a, b);
  return a * y2[klo] + b * y2[khi];
}
Referenced by sample2ndDerivative(), and BicubicSplineInterpolation::sample2ndDerivative().
sample2ndDerivative() [2/2]
Real SplineInterpolation::sample2ndDerivative (Real x) const
Definition at line 86 of file SplineInterpolation.C.
{
  return SplineInterpolationBase::sample2ndDerivative(_x, _y, _y2, x);
}
Referenced by SplineFunction::secondDerivative().
sampleDerivative() [1/2]
Real SplineInterpolationBase::sampleDerivative (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, Real x_int) const inherited
Definition at line 125 of file SplineInterpolationBase.C.
{
  unsigned int klo, khi;
  findInterval(x, x_int, klo, khi);
  Real h, a, b;
  computeCoeffs(x, klo, khi, x_int, h, a, b);
  return (y[khi] - y[klo]) / h -
         (((3.0 * a * a - 1.0) * y2[klo] + (3.0 * b * b - 1.0) * -y2[khi]) * h / 6.0);
}
Referenced by sampleDerivative(), BicubicSplineInterpolation::sampleDerivative(), and BicubicSplineInterpolation::sampleValueAndDerivatives().
sampleDerivative() [2/2]
Real SplineInterpolation::sampleDerivative (Real x) const
Definition at line 80 of file SplineInterpolation.C.
{
  return SplineInterpolationBase::sampleDerivative(_x, _y, _y2, x);
}
Referenced by ADEEDFRateConstantTownsend::computeQpProperties(), ADZapdosEEDFRateConstant::computeQpProperties(), EEDFRateConstant::computeQpProperties(), EEDFRateConstantTownsend::computeQpProperties(), InterpolatedCoefficientSpline::computeQpProperties(), ZapdosEEDFRateConstant::computeQpProperties(), ADGasElectronMoments::computeQpProperties(), Gas::computeQpProperties(), GasBase::computeQpProperties(), GasElectronMoments::computeQpProperties(), SplineFunction::derivative(), RateCoefficientProvider::electron_temperature(), and RateCoefficientProvider::reaction_coefficient_derivative().
setData()
void SplineInterpolation::setData (const std::vector< Real > & x, const std::vector< Real > & y, Real yp1 = _deriv_bound, Real ypn = _deriv_bound)
Set the x-, y- values and first derivatives.
Definition at line 33 of file SplineInterpolation.C.
{
  _x = x;
  _y = y;
  _yp1 = yp1;
  _ypn = ypn;
  errorCheck();
  solve();
}
Referenced by ADEEDFRateConstantTownsend::ADEEDFRateConstantTownsend(), ADGasElectronMoments::ADGasElectronMoments(), ADZapdosEEDFRateConstant::ADZapdosEEDFRateConstant(), DataRead::DataRead(), DiffusionRateTemp::DiffusionRateTemp(), EEDFRateConstant::EEDFRateConstant(), EEDFRateConstantTownsend::EEDFRateConstantTownsend(), ElectricField::ElectricField(), ElectronMobility::ElectronMobility(), BoltzmannSolverScalar::execute(), Gas::Gas(), GasBase::GasBase(), GasElectronMoments::GasElectronMoments(), InterpolatedCoefficientSpline::InterpolatedCoefficientSpline(), ParsedScalarReaction::ParsedScalarReaction(), RateCoefficientProvider::RateCoefficientProvider(), ScalarSplineInterpolation::ScalarSplineInterpolation(), ValueProvider::ValueProvider(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
solve()
void SplineInterpolation::solve () protected
Definition at line 62 of file SplineInterpolation.C.
{
  spline(_x, _y, _y2, _yp1, _ypn);
}
Referenced by setData(), and SplineInterpolation().
spline()
void SplineInterpolationBase::spline (const std::vector< Real > & x, const std::vector< Real > & y, std::vector< Real > & y2, Real yp1 = _deriv_bound, Real ypn = _deriv_bound) protected inherited
This function calculates the second derivatives based on supplied x and y-vectors.
Definition at line 19 of file SplineInterpolationBase.C.
{
  auto n = x.size();
  if (n < 2)
    mooseError("You must have at least two knots to create a spline.");
  std::vector<Real> u(n, 0.);
  y2.assign(n, 0.);
  if (yp1 >= 1e30)
    y2[0] = u[0] = 0.;
  else
  {
    y2[0] = -0.5;
    u[0] = (3.0 / (x[1] - x[0])) * ((y[1] - y[0]) / (x[1] - x[0]) - yp1);
  }
  // decomposition of tri-diagonal algorithm (y2 and u are used for temporary storage)
  for (decltype(n) i = 1; i < n - 1; i++)
  {
    Real sig = (x[i] - x[i - 1]) / (x[i + 1] - x[i - 1]);
    Real p = sig * y2[i - 1] + 2.0;
    y2[i] = (sig - 1.0) / p;
    u[i] = (y[i + 1] - y[i]) / (x[i + 1] - x[i]) - (y[i] - y[i - 1]) / (x[i] - x[i - 1]);
    u[i] = (6.0 * u[i] / (x[i + 1] - x[i - 1]) - sig * u[i - 1]) / p;
  }
  Real qn, un;
  if (ypn >= 1e30)
    qn = un = 0.;
  else
  {
    qn = 0.5;
    un = (3.0 / (x[n - 1] - x[n - 2])) * (ypn - (y[n - 1] - y[n - 2]) / (x[n - 1] - x[n - 2]));
  }
  y2[n - 1] = (un - qn * u[n - 2]) / (qn * y2[n - 2] + 1.);
  // back substitution
  for (auto k = n - 1; k >= 1; k--)
    y2[k - 1] = y2[k - 1] * y2[k] + u[k - 1];
}
Referenced by BicubicSplineInterpolation::constructColumnSpline(), BicubicSplineInterpolation::constructColumnSplineSecondDerivativeTable(), BicubicSplineInterpolation::constructRowSpline(), BicubicSplineInterpolation::constructRowSplineSecondDerivativeTable(), and solve().
Member Data Documentation
_deriv_bound
const Real SplineInterpolationBase::_deriv_bound = std::numeric_limits<Real>::max() static protected inherited
Definition at line 79 of file SplineInterpolationBase.h.
Referenced by BicubicSplineInterpolation::errorCheck().
_file_number
int SplineInterpolation::_file_number = 0 static protected
Definition at line 80 of file SplineInterpolation.h.
_x
std::vector<Real> SplineInterpolation::_x protected
Definition at line 71 of file SplineInterpolation.h.
Referenced by domain(), errorCheck(), getSampleSize(), sample(), sample2ndDerivative(), sampleDerivative(), setData(), and solve().
_y
std::vector<Real> SplineInterpolation::_y protected
Definition at line 72 of file SplineInterpolation.h.
Referenced by errorCheck(), range(), sample(), sample2ndDerivative(), sampleDerivative(), setData(), and solve().
_y2
std::vector<Real> SplineInterpolation::_y2 protected
Second derivatives.
Definition at line 76 of file SplineInterpolation.h.
Referenced by sample(), sample2ndDerivative(), sampleDerivative(), and solve().
_yp1
Real SplineInterpolation::_yp1 protected
boundary conditions
Definition at line 74 of file SplineInterpolation.h.
Referenced by setData(), and solve().
_ypn
Real SplineInterpolation::_ypn protected
Definition at line 74 of file SplineInterpolation.h.
Referenced by setData(), and solve().
The documentation for this class was generated from the following files:
moose/framework/include/utils/SplineInterpolation.h
moose/framework/src/utils/SplineInterpolation.C