Zapdos: ConstraintWarehouse Class Reference
ConstraintWarehouse Class Reference
Warehouse for storing constraints.
#include <ConstraintWarehouse.h>
Public Member Functions
ConstraintWarehouse ()
void addObject (std::shared_ptr< Constraint > object, THREAD_ID tid=0, bool recurse=true) override
Add Constraint object to the warehouse.
void subdomainsCovered (std::set< SubdomainID > &subdomains_covered, std::set< std::string > &unique_variables, THREAD_ID tid=0) const
Update supplied subdomain and variable coverate containters.
void updateActive (THREAD_ID tid=0) override
Update the various active lists.
virtual void residualEnd (THREAD_ID tid=0) const
virtual void addObject (std::shared_ptr< Constraint > object, THREAD_ID tid=0, bool recurse=true) override
Adds an object to the storage structure.
unsigned int size (THREAD_ID tid=0) const
Return how many kernels we store in the current warehouse.
std::set< SubdomainID > getActiveBlocks (THREAD_ID tid=0) const
Return a set of active SubdomainsIDs.
void sort (THREAD_ID tid=0)
Sort the objects using the DependencyResolver.
THREAD_ID numThreads () const
Return the number of threads.
std::string activeObjectsToFormattedString (THREAD_ID tid=0, const std::string &prefix="[DBG]") const
Output the active content of the warehouse to a string, meant to be output to the console.
const std::vector< std::shared_ptr< NodalConstraint > > & getActiveNodalConstraints () const
Access methods for active objects.
const std::vector< std::shared_ptr< MortarConstraintBase > > & getActiveMortarConstraints (const std::pair< BoundaryID, BoundaryID > &mortar_interface_key, bool displaced) const
const std::vector< std::shared_ptr< ElemElemConstraint > > & getActiveElemElemConstraints (InterfaceID interface_id, bool displaced) const
const std::vector< std::shared_ptr< NodeFaceConstraint > > & getActiveNodeFaceConstraints (BoundaryID boundary_id, bool displaced) const
const std::vector< std::shared_ptr< NodeElemConstraint > > & getActiveNodeElemConstraints (SubdomainID secondary_id, SubdomainID primary_id, bool displaced) const
bool hasActiveNodalConstraints () const
Deterimine if active objects exist.
bool hasActiveMortarConstraints (const std::pair< BoundaryID, BoundaryID > &mortar_interface_key, bool displaced) const
bool hasActiveElemElemConstraints (const InterfaceID interface_id, bool displaced) const
bool hasActiveNodeFaceConstraints (BoundaryID boundary_id, bool displaced) const
bool hasActiveNodeElemConstraints (SubdomainID secondary_id, SubdomainID primary_id, bool displaced) const
virtual void initialSetup (THREAD_ID tid=0) const
Convenience methods for calling object setup methods.
virtual void timestepSetup (THREAD_ID tid=0) const
virtual void customSetup (const ExecFlagType &exec_type, THREAD_ID tid=0) const
virtual void subdomainSetup (THREAD_ID tid=0) const
virtual void subdomainSetup (SubdomainID id, THREAD_ID tid=0) const
virtual void jacobianSetup (THREAD_ID tid=0) const
virtual void residualSetup (THREAD_ID tid=0) const
bool hasActiveVariableBlockObjects (unsigned int variable_id, SubdomainID block_id, THREAD_ID tid=0) const
Methods for checking/getting variable kernels for a variable and SubdomainID.
const std::vector< std::shared_ptr< Constraint > > & getActiveVariableBlockObjects (unsigned int variable_id, SubdomainID block_id, THREAD_ID tid=0) const
const std::vector< std::shared_ptr< T > > & getObjects (THREAD_ID tid=0) const
Retrieve complete vector to the all/block/boundary restricted objects for a given thread.
const std::map< SubdomainID, std::vector< std::shared_ptr< T > > > & getBlockObjects (THREAD_ID tid=0) const
const std::vector< std::shared_ptr< T > > & getBlockObjects (SubdomainID id, THREAD_ID tid=0) const
const std::map< BoundaryID, std::vector< std::shared_ptr< T > > > & getBoundaryObjects (THREAD_ID tid=0) const
const std::vector< std::shared_ptr< T > > & getBoundaryObjects (BoundaryID id, THREAD_ID tid=0) const
const std::vector< std::shared_ptr< T > > & getActiveObjects (THREAD_ID tid=0) const
Retrieve complete vector to the active all/block/boundary restricted objects for a given thread.
const std::map< SubdomainID, std::vector< std::shared_ptr< T > > > & getActiveBlockObjects (THREAD_ID tid=0) const
const std::vector< std::shared_ptr< T > > & getActiveBlockObjects (SubdomainID id, THREAD_ID tid=0) const
const std::map< BoundaryID, std::vector< std::shared_ptr< T > > > & getActiveBoundaryObjects (THREAD_ID tid=0) const
const std::vector< std::shared_ptr< T > > & getActiveBoundaryObjects (BoundaryID id, THREAD_ID tid=0) const
bool hasObjects (THREAD_ID tid=0) const
Convenience functions for determining if objects exist.
bool hasActiveObjects (THREAD_ID tid=0) const
bool hasActiveBlockObjects (THREAD_ID tid=0) const
bool hasActiveBlockObjects (SubdomainID id, THREAD_ID tid=0) const
bool hasActiveBoundaryObjects (THREAD_ID tid=0) const
bool hasActiveBoundaryObjects (BoundaryID id, THREAD_ID tid=0) const
bool hasBoundaryObjects (BoundaryID id, THREAD_ID tid=0) const
bool hasActiveObject (const std::string &name, THREAD_ID tid=0) const
Convenience functions for checking/getting specific objects.
std::shared_ptr< T > getObject (const std::string &name, THREAD_ID tid=0) const
std::shared_ptr< T > getActiveObject (const std::string &name, THREAD_ID tid=0) const
void updateVariableDependency (std::set< MooseVariableFieldBase * > &needed_moose_vars, THREAD_ID tid=0) const
Update variable dependency vector.
void updateBlockVariableDependency (SubdomainID id, std::set< MooseVariableFieldBase * > &needed_moose_vars, THREAD_ID tid=0) const
void updateBoundaryVariableDependency (std::set< MooseVariableFieldBase * > &needed_moose_vars, THREAD_ID tid=0) const
void updateBoundaryVariableDependency (BoundaryID id, std::set< MooseVariableFieldBase * > &needed_moose_vars, THREAD_ID tid=0) const
void updateBlockFEVariableCoupledVectorTagDependency (SubdomainID id, std::set< TagID > &needed_fe_var_vector_tags, THREAD_ID tid=0) const
Update FE variable coupleable vector tag vector.
void updateBoundaryFEVariableCoupledVectorTagDependency (BoundaryID id, std::set< TagID > &needed_fe_var_vector_tags, THREAD_ID tid=0) const
void updateMatPropDependency (std::set< unsigned int > &needed_mat_props, THREAD_ID tid=0) const
Update material property dependency vector.
void updateBlockMatPropDependency (SubdomainID id, std::set< unsigned int > &needed_mat_props, THREAD_ID tid=0) const
void updateBoundaryMatPropDependency (std::set< unsigned int > &needed_mat_props, THREAD_ID tid=0) const
void updateBoundaryMatPropDependency (BoundaryID id, std::set< unsigned int > &needed_mat_props, THREAD_ID tid=0) const
Protected Member Functions
void checkThreadID (THREAD_ID tid) const
Calls assert on thread id.
Static Protected Member Functions
static void updateActiveHelper (std::vector< std::shared_ptr< T > > &active, const std::vector< std::shared_ptr< T > > &all)
Helper method for updating active vectors.
static void sortHelper (std::vector< std::shared_ptr< T > > &objects)
Helper method for sorting vectors of objects.
static void updateVariableDependencyHelper (std::set< MooseVariableFieldBase * > &needed_moose_vars, const std::vector< std::shared_ptr< T > > &objects)
Helper method for updating variable dependency vector.
static void updateFEVariableCoupledVectorTagDependencyHelper (std::set< TagID > &needed_fe_var_vector_tags, const std::vector< std::shared_ptr< T > > &objects)
Helper method for updating FE variable coupleable vector tag vector.
static void updateMatPropDependencyHelper (std::set< unsigned int > &needed_mat_props, const std::vector< std::shared_ptr< T > > &objects)
Helper method for updating material property dependency vector.
Protected Attributes
MooseObjectWarehouse< NodalConstraint > _nodal_constraints
NodalConstraint objects.
std::map< BoundaryID, MooseObjectWarehouse< NodeFaceConstraint > > _node_face_constraints
NodeFaceConstraint objects (non-displaced)
std::map< BoundaryID, MooseObjectWarehouse< NodeFaceConstraint > > _displaced_node_face_constraints
NodeFaceConstraint objects (displaced)
std::map< std::pair< BoundaryID, BoundaryID >, MooseObjectWarehouse< MortarConstraintBase > > _mortar_constraints
Undisplaced MortarConstraints.
std::map< std::pair< BoundaryID, BoundaryID >, MooseObjectWarehouse< MortarConstraintBase > > _displaced_mortar_constraints
Displaced MortarConstraints.
std::map< unsigned int, MooseObjectWarehouse< ElemElemConstraint > > _element_constraints
ElemElemConstraints (non-displaced)
std::map< unsigned int, MooseObjectWarehouse< ElemElemConstraint > > _displaced_element_constraints
ElemElemConstraints (displaced)
std::map< std::pair< SubdomainID, SubdomainID >, MooseObjectWarehouse< NodeElemConstraint > > _node_elem_constraints
NodeElemConstraint objects.
std::map< std::pair< SubdomainID, SubdomainID >, MooseObjectWarehouse< NodeElemConstraint > > _displaced_node_elem_constraints
NodeElemConstraint objects.
std::map< unsigned int, MooseObjectWarehouse< Constraint > > _variable_objects
Variable based storage.
const THREAD_ID _num_threads
Convenience member storing the number of threads used for storage (1 or libMesh::n_threads)
std::vector< std::vector< std::shared_ptr< T > > > _all_objects
Storage container for the ALL pointers (THREAD_ID on outer vector)
std::vector< std::vector< std::shared_ptr< T > > > _active_objects
All active objects (THREAD_ID on outer vector)
std::vector< std::map< SubdomainID, std::vector< std::shared_ptr< T > > > > _all_block_objects
std::vector< std::map< SubdomainID, std::vector< std::shared_ptr< T > > > > _active_block_objects
Active block restricted objects (THREAD_ID on outer vector)
std::vector< std::map< BoundaryID, std::vector< std::shared_ptr< T > > > > _all_boundary_objects
std::vector< std::map< BoundaryID, std::vector< std::shared_ptr< T > > > > _active_boundary_objects
Active boundary restricted objects (THREAD_ID on outer vector)
Detailed Description
Warehouse for storing constraints.
Definition at line 26 of file ConstraintWarehouse.h.
Constructor & Destructor Documentation
ConstraintWarehouse()
ConstraintWarehouse::ConstraintWarehouse ()
Definition at line 20 of file ConstraintWarehouse.C.
: MooseObjectWarehouse<Constraint>(/*threaded=*/false) {}
Member Function Documentation
activeObjectsToFormattedString()
template<typename T > std::string MooseObjectWarehouseBase< T >::activeObjectsToFormattedString (THREAD_ID tid = 0, const std::string & prefix = "[DBG]") const inherited
Output the active content of the warehouse to a string, meant to be output to the console.
Parameters
tid the thread id
prefix a string to prepend to the string
Definition at line 756 of file MooseObjectWarehouseBase.h.
{
  std::vector<std::string> output;
  for (const auto & object : _active_objects[tid])
    output.push_back(object->name());
  return ConsoleUtils::formatString(MooseUtils::join(output, " "), prefix);
}
Referenced by NonlinearThread::printBlockExecutionInformation(), NonlinearThread::printBoundaryExecutionInformation(), ComputeNodalKernelBCJacobiansThread::printGeneralExecutionInformation(), ComputeNodalKernelBcsThread::printGeneralExecutionInformation(), ComputeNodalKernelJacobiansThread::printGeneralExecutionInformation(), and ComputeNodalKernelsThread::printGeneralExecutionInformation().
addObject() [1/2]
void ConstraintWarehouse::addObject (std::shared_ptr< Constraint > object, THREAD_ID tid = 0, bool recurse = true) override
Add Constraint object to the warehouse.
Parameters
object A std::shared_ptr of the object
tid Not used.
Definition at line 23 of file ConstraintWarehouse.C.
{
  // Adds to the storage of _all_objects
  MooseObjectWarehouse<Constraint>::addObject(object);
  // Cast the the possible Contraint types
  std::shared_ptr<NodeFaceConstraint> nfc = std::dynamic_pointer_cast<NodeFaceConstraint>(object);
  std::shared_ptr<MortarConstraintBase> mc =
      std::dynamic_pointer_cast<MortarConstraintBase>(object);
  std::shared_ptr<NodalConstraint> nc = std::dynamic_pointer_cast<NodalConstraint>(object);
  std::shared_ptr<ElemElemConstraint> ec = std::dynamic_pointer_cast<ElemElemConstraint>(object);
  std::shared_ptr<NodeElemConstraint> nec = std::dynamic_pointer_cast<NodeElemConstraint>(object);
  // NodeFaceConstraint
  if (nfc)
  {
    MooseMesh & mesh = nfc->getParam<FEProblemBase *>("_fe_problem_base")->mesh();
    unsigned int secondary = mesh.getBoundaryID(nfc->getParam<BoundaryName>("secondary"));
    bool displaced = nfc->parameters().have_parameter<bool>("use_displaced_mesh") &&
                     nfc->getParam<bool>("use_displaced_mesh");
    if (displaced)
      _displaced_node_face_constraints[secondary].addObject(nfc);
    else
      _node_face_constraints[secondary].addObject(nfc);
  }
  // MortarConstraint
  else if (mc)
  {
    MooseMesh & mesh = mc->getParam<FEProblemBase *>("_fe_problem_base")->mesh();
    bool displaced = mc->getParam<bool>("use_displaced_mesh");
    auto secondary_boundary_id =
        mesh.getBoundaryID(mc->getParam<BoundaryName>("secondary_boundary"));
    auto primary_boundary_id = mesh.getBoundaryID(mc->getParam<BoundaryName>("primary_boundary"));
    auto key = std::make_pair(primary_boundary_id, secondary_boundary_id);
    if (displaced)
      _displaced_mortar_constraints[key].addObject(mc);
    else
      _mortar_constraints[key].addObject(mc);
  }
  // ElemElemConstraint
  else if (ec)
  {
    bool displaced = ec->parameters().have_parameter<bool>("use_displaced_mesh") &&
                     ec->getParam<bool>("use_displaced_mesh");
    const InterfaceID interface_id = ec->getInterfaceID();
    if (displaced)
      _displaced_element_constraints[interface_id].addObject(ec);
    else
      _element_constraints[interface_id].addObject(ec);
  }
  // NodeElemConstraint
  else if (nec)
  {
    MooseMesh & mesh = nec->getParam<FEProblemBase *>("_fe_problem_base")->mesh();
    SubdomainID secondary = mesh.getSubdomainID(nec->getParam<SubdomainName>("secondary"));
    SubdomainID primary = mesh.getSubdomainID(nec->getParam<SubdomainName>("primary"));
    bool displaced = nec->parameters().have_parameter<bool>("use_displaced_mesh") &&
                     nec->getParam<bool>("use_displaced_mesh");
    if (displaced)
      _displaced_node_elem_constraints[std::make_pair(secondary, primary)].addObject(nec);
    else
      _node_elem_constraints[std::make_pair(secondary, primary)].addObject(nec);
  }
  // NodalConstraint
  else if (nc)
    _nodal_constraints.addObject(nc);
  else
    mooseError("Unknown type of Constraint object");
}
Referenced by NonlinearSystemBase::addConstraint().
addObject() [2/2]
void MooseObjectWarehouse< Constraint >::addObject (std::shared_ptr< Constraint > object, THREAD_ID tid = 0, bool recurse = true) override virtual inherited
Adds an object to the storage structure.
Parameters
object A shared pointer to the object being added
tid The thread ID (default is 0)
recurse Whether or not to build recusive warehouses (typically for Kernels)
Reimplemented from MooseObjectWarehouseBase< T >.
Definition at line 48 of file MooseObjectWarehouse.h.
{
  MooseObjectWarehouseBase<T>::addObject(object, tid, recurse);
  if (recurse)
  {
    {
      auto mvi = std::dynamic_pointer_cast<MooseVariableInterface<Real>>(object);
      if (mvi)
        _variable_objects[mvi->mooseVariableBase()->number()].addObject(object, tid, false);
    }
    {
      auto mvi = std::dynamic_pointer_cast<MooseVariableInterface<RealVectorValue>>(object);
      if (mvi)
        _variable_objects[mvi->mooseVariableBase()->number()].addObject(object, tid, false);
    }
    {
      auto mvi = std::dynamic_pointer_cast<MooseVariableInterface<RealEigenVector>>(object);
      if (mvi)
        _variable_objects[mvi->mooseVariableBase()->number()].addObject(object, tid, false);
    }
  }
}
checkThreadID()
template<typename T > void MooseObjectWarehouseBase< T >::checkThreadID (THREAD_ID tid) const inline protected inherited
Calls assert on thread id.
Definition at line 787 of file MooseObjectWarehouseBase.h.
{
  mooseAssert(tid < _num_threads,
              "Attempting to access a thread id ("
                  << tid << ") greater than the number allowed by the storage item ("
                  << _num_threads << ")");
}
Referenced by MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getActiveBlockObjects(), MooseObjectWarehouseBase< T >::getActiveBlocks(), MooseObjectWarehouseBase< T >::getActiveBoundaryObjects(), MooseObjectWarehouseBase< T >::getActiveObject(), MooseObjectWarehouseBase< T >::getActiveObjects(), MooseObjectWarehouseBase< T >::getBlockObjects(), MooseObjectWarehouseBase< T >::getBoundaryObjects(), MooseObjectWarehouseBase< T >::getObject(), MooseObjectWarehouseBase< T >::getObjects(), MooseObjectWarehouseBase< T >::hasActiveBlockObjects(), MooseObjectWarehouseBase< T >::hasActiveBoundaryObjects(), MooseObjectWarehouseBase< T >::hasActiveObject(), MooseObjectWarehouseBase< T >::hasActiveObjects(), MooseObjectWarehouseBase< T >::hasBoundaryObjects(), MooseObjectWarehouseBase< T >::hasObjects(), residualEnd(), MooseObjectWarehouseBase< T >::size(), MaterialWarehouse::sort(), MooseObjectWarehouseBase< T >::sort(), and MooseObjectWarehouseBase< T >::updateActive().
customSetup()
void MooseObjectWarehouse< Constraint >::customSetup (const ExecFlagType & exec_type, THREAD_ID tid = 0) const virtual inherited
Definition at line 56 of file MooseObjectWarehouse.h.
{
  checkThreadID(tid);
  for (const auto & object : _active_objects[tid])
    object->customSetup(exec_type);
}
getActiveBlockObjects() [1/2]
template<typename T > const std::vector< std::shared_ptr< T > > & MooseObjectWarehouseBase< T >::getActiveBlockObjects (SubdomainID id, THREAD_ID tid = 0) const inherited
Definition at line 434 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  const auto iter = _active_block_objects[tid].find(id);
  mooseAssert(iter != _active_block_objects[tid].end(),
              "Unable to located active block objects for the given id: " << id << ".");
  return iter->second;
}
getActiveBlockObjects() [2/2]
template<typename T > const std::map< SubdomainID, std::vector< std::shared_ptr< T > > > & MooseObjectWarehouseBase< T >::getActiveBlockObjects (THREAD_ID tid = 0) const inline inherited
Definition at line 426 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _active_block_objects[tid];
}
Referenced by MaterialPropertyInterface::buildRequiredMaterials(), FEProblemBase::checkProblemIntegrity(), NonlinearThread::computeOnElement(), NonlinearThread::computeOnInternalFace(), ComputeFullJacobianThread::computeOnInternalFace(), FEProblemBase::getFVMatsAndDependencies(), BlockRestrictable::hasBlockMaterialPropertyHelper(), ComputeIndicatorThread::onElement(), ComputeMarkerThread::onElement(), ComputeMaterialsObjectThread::onElement(), ComputeIndicatorThread::onInternalSide(), ComputeNodalKernelJacobiansThread::onNode(), ComputeNodalKernelsThread::onNode(), ComputeInitialConditionThread::operator()(), ComputeFVInitialConditionThread::operator()(), ComputeDiracThread::printBlockExecutionInformation(), ComputeIndicatorThread::printBlockExecutionInformation(), ComputeMarkerThread::printBlockExecutionInformation(), FEProblemBase::reinitMaterials(), Moose::Mortar::setupMortarMaterials(), MooseObjectWarehouseBase< T >::updateBlockFEVariableCoupledVectorTagDependency(), MooseObjectWarehouseBase< T >::updateBlockMatPropDependency(), and MooseObjectWarehouseBase< T >::updateBlockVariableDependency().
getActiveBlocks()
template<typename T > std::set< SubdomainID > MooseObjectWarehouseBase< T >::getActiveBlocks (THREAD_ID tid = 0) const inherited
Return a set of active SubdomainsIDs.
Definition at line 534 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  std::set<SubdomainID> ids;
  for (const auto & object_pair : _active_block_objects[tid])
    ids.insert(object_pair.first);
  return ids;
}
Referenced by FEProblemBase::checkProblemIntegrity().
getActiveBoundaryObjects() [1/2]
template<typename T > const std::vector< std::shared_ptr< T > > & MooseObjectWarehouseBase< T >::getActiveBoundaryObjects (BoundaryID id, THREAD_ID tid = 0) const inherited
Definition at line 415 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  const auto iter = _active_boundary_objects[tid].find(id);
  mooseAssert(iter != _active_boundary_objects[tid].end(),
              "Unable to located active boundary objects for the given id: " << id << ".");
  return iter->second;
}
getActiveBoundaryObjects() [2/2]
template<typename T > const std::map< BoundaryID, std::vector< std::shared_ptr< T > > > & MooseObjectWarehouseBase< T >::getActiveBoundaryObjects (THREAD_ID tid = 0) const inline inherited
Definition at line 407 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _active_boundary_objects[tid];
}
Referenced by NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeMortarNodalVars(), NonlinearSystemBase::computeNodalBCs(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), NonlinearThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnBoundary(), NonlinearThread::computeOnInterface(), ComputeFullJacobianThread::computeOnInterface(), BoundaryRestrictable::hasBoundaryMaterialPropertyHelper(), ComputeMaterialsObjectThread::onBoundary(), ComputeMaterialsObjectThread::onInterface(), ComputeBoundaryInitialConditionThread::onNode(), ComputeNodalKernelBCJacobiansThread::onNode(), ComputeNodalKernelBcsThread::onNode(), FEProblemBase::reinitMaterialsBoundary(), FEProblemBase::reinitMaterialsInterface(), NonlinearSystemBase::setInitialSolution(), MooseObjectWarehouseBase< T >::updateBoundaryFEVariableCoupledVectorTagDependency(), MooseObjectWarehouseBase< T >::updateBoundaryMatPropDependency(), and MooseObjectWarehouseBase< T >::updateBoundaryVariableDependency().
getActiveElemElemConstraints()
const std::vector< std::shared_ptr< ElemElemConstraint > > & ConstraintWarehouse::getActiveElemElemConstraints (InterfaceID interface_id, bool displaced) const
Definition at line 170 of file ConstraintWarehouse.C.
{
  std::map<unsigned int, MooseObjectWarehouse<ElemElemConstraint>>::const_iterator it, end_it;
  if (displaced)
  {
    it = _displaced_element_constraints.find(interface_id);
    end_it = _displaced_element_constraints.end();
  }
  else
  {
    it = _element_constraints.find(interface_id);
    end_it = _element_constraints.end();
  }
  mooseAssert(it != end_it,
              "Unable to locate storage for ElemElemConstraint objects for the given interface id: "
                  << interface_id);
  return it->second.getActiveObjects();
}
Referenced by NonlinearSystemBase::constraintJacobians(), and NonlinearSystemBase::constraintResiduals().
getActiveMortarConstraints()
const std::vector< std::shared_ptr< MortarConstraintBase > > & ConstraintWarehouse::getActiveMortarConstraints (const std::pair< BoundaryID, BoundaryID > & mortar_interface_key, bool displaced) const
Definition at line 143 of file ConstraintWarehouse.C.
{
  std::map<std::pair<BoundaryID, BoundaryID>,
           MooseObjectWarehouse<MortarConstraintBase>>::const_iterator it,
      end_it;
  if (displaced)
  {
    it = _displaced_mortar_constraints.find(mortar_interface_key);
    end_it = _displaced_mortar_constraints.end();
  }
  else
  {
    it = _mortar_constraints.find(mortar_interface_key);
    end_it = _mortar_constraints.end();
  }
  mooseAssert(
      it != end_it,
      "No MortarConstraints exist for the specified primary-secondary boundary pair, primary "
          << mortar_interface_key.first << " and secondary " << mortar_interface_key.second);
  return it->second.getActiveObjects();
}
Referenced by NonlinearSystemBase::initialSetup().
getActiveNodalConstraints()
const std::vector< std::shared_ptr< NodalConstraint > > & ConstraintWarehouse::getActiveNodalConstraints () const
Access methods for active objects.
Definition at line 106 of file ConstraintWarehouse.C.
{
  return _nodal_constraints.getActiveObjects();
}
Referenced by NonlinearSystemBase::enforceNodalConstraintsJacobian(), NonlinearSystemBase::enforceNodalConstraintsResidual(), and NonlinearSystemBase::findImplicitGeometricCouplingEntries().
getActiveNodeElemConstraints()
const std::vector< std::shared_ptr< NodeElemConstraint > > & ConstraintWarehouse::getActiveNodeElemConstraints (SubdomainID secondary_id, SubdomainID primary_id, bool displaced) const
Definition at line 194 of file ConstraintWarehouse.C.
{
  std::map<std::pair<SubdomainID, SubdomainID>,
           MooseObjectWarehouse<NodeElemConstraint>>::const_iterator it,
      end_it;
  if (displaced)
  {
    it = _displaced_node_elem_constraints.find(std::make_pair(secondary_id, primary_id));
    end_it = _displaced_node_elem_constraints.end();
  }
  else
  {
    it = _node_elem_constraints.find(std::make_pair(secondary_id, primary_id));
    end_it = _node_elem_constraints.end();
  }
  mooseAssert(it != end_it,
              "Unable to locate storage for NodeElemConstraint objects for the given secondary and "
              "primary id pair: ["
                  << secondary_id << ", " << primary_id << "]");
  return it->second.getActiveObjects();
}
Referenced by NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), and NonlinearSystemBase::setConstraintSecondaryValues().
getActiveNodeFaceConstraints()
const std::vector< std::shared_ptr< NodeFaceConstraint > > & ConstraintWarehouse::getActiveNodeFaceConstraints (BoundaryID boundary_id, bool displaced) const
Definition at line 112 of file ConstraintWarehouse.C.
{
  std::map<BoundaryID, MooseObjectWarehouse<NodeFaceConstraint>>::const_iterator it, end_it;
  if (displaced)
  {
    it = _displaced_node_face_constraints.find(boundary_id);
    end_it = _displaced_node_face_constraints.end();
  }
  else
  {
    it = _node_face_constraints.find(boundary_id);
    end_it = _node_face_constraints.end();
  }
  mooseAssert(it != end_it,
              "Unable to locate storage for NodeFaceConstraint objects for the given boundary id: "
                  << boundary_id);
  return it->second.getActiveObjects();
}
Referenced by NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), and NonlinearSystemBase::setConstraintSecondaryValues().
getActiveObject()
template<typename T > std::shared_ptr< T > MooseObjectWarehouseBase< T >::getActiveObject (const std::string & name, THREAD_ID tid = 0) const inherited
Definition at line 523 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  for (const auto & object : _active_objects[tid])
    if (object->name() == name)
      return object;
  mooseError("Unable to locate active object: ", name, ".");
}
Referenced by DerivativeParsedMaterialHelperTempl< is_ad >::assembleDerivatives(), FEProblemBase::getFunction(), FEProblemBase::getMaterial(), FEProblemBase::getMeshDivision(), NonlinearSystemBase::getSplit(), LibtorchControlValuePostprocessor::initialSetup(), and LibtorchArtificialNeuralNetParameters::initialSetup().
getActiveObjects()
template<typename T > const std::vector< std::shared_ptr< T > > & MooseObjectWarehouseBase< T >::getActiveObjects (THREAD_ID tid = 0) const inline inherited
Retrieve complete vector to the active all/block/boundary restricted objects for a given thread.
Parameters
tid The thread id to retrieve objects from
Definition at line 399 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _active_objects[tid];
}
Referenced by DumpObjectsProblem::addAuxVariable(), FEProblemBase::backupMultiApps(), NonlinearEigenSystem::checkIntegrity(), FEProblemBase::checkProblemIntegrity(), NonlinearSystemBase::computeDamping(), NonlinearSystemBase::computeDiracContributions(), FEProblemBase::computeIndicators(), FEProblemBase::computeMarkers(), FEProblemBase::computeMultiAppsDT(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeScalarKernelsJacobians(), AuxiliarySystem::computeScalarVars(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finalizeMultiApps(), FEProblemBase::finishMultiAppStep(), getActiveNodalConstraints(), FEProblemBase::getTransfers(), FEProblemBase::incrementMultiAppTStep(), ComputeDiracThread::onElement(), ComputeElemDampingThread::onElement(), ComputeNodalDampingThread::onNode(), FEProblemBase::postExecute(), FEProblemBase::projectInitialConditionOnCustomRange(), FEProblemBase::projectSolution(), FEProblemBase::restoreMultiApps(), and AuxiliarySystem::setScalarVariableCoupleableTags().
getActiveVariableBlockObjects()
const std::vector< std::shared_ptr< Constraint > > & MooseObjectWarehouse< Constraint >::getActiveVariableBlockObjects (unsigned int variable_id, SubdomainID block_id, THREAD_ID tid = 0) const inherited
Definition at line 70 of file MooseObjectWarehouse.h.
{
  checkThreadID(tid);
  const auto iter = _variable_objects.find(variable_id);
  mooseAssert(iter != _variable_objects.end(),
              "Unable to locate variable kernels for the given variable id: " << variable_id
                                                                              << ".");
  return iter->second.getActiveBlockObjects(block_id, tid);
}
getBlockObjects() [1/2]
template<typename T > const std::vector< std::shared_ptr< T > > & MooseObjectWarehouseBase< T >::getBlockObjects (SubdomainID id, THREAD_ID tid = 0) const inherited
Definition at line 388 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  const auto iter = _all_block_objects[tid].find(id);
  mooseAssert(iter != _all_block_objects[tid].end(),
              "Unable to located active block objects for the given id: " << id << ".");
  return iter->second;
}
getBlockObjects() [2/2]
template<typename T > const std::map< SubdomainID, std::vector< std::shared_ptr< T > > > & MooseObjectWarehouseBase< T >::getBlockObjects (THREAD_ID tid = 0) const inline inherited
Definition at line 380 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _all_block_objects[tid];
}
Referenced by MaterialPropertyDebugOutput::printMaterialMap().
getBoundaryObjects() [1/2]
template<typename T > const std::vector< std::shared_ptr< T > > & MooseObjectWarehouseBase< T >::getBoundaryObjects (BoundaryID id, THREAD_ID tid = 0) const inherited
Definition at line 369 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  const auto iter = _all_boundary_objects[tid].find(id);
  mooseAssert(iter != _all_boundary_objects[tid].end(),
              "Unable to located active boundary objects for the given id: " << id << ".");
  return iter->second;
}
getBoundaryObjects() [2/2]
template<typename T > const std::map< BoundaryID, std::vector< std::shared_ptr< T > > > & MooseObjectWarehouseBase< T >::getBoundaryObjects (THREAD_ID tid = 0) const inline inherited
Definition at line 353 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _all_boundary_objects[tid];
}
Referenced by ComputeFullJacobianThread::computeOnBoundary(), and MaterialPropertyDebugOutput::printMaterialMap().
getObject()
template<typename T > std::shared_ptr< T > MooseObjectWarehouseBase< T >::getObject (const std::string & name, THREAD_ID tid = 0) const inherited
Definition at line 512 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  for (const auto & object : _all_objects[tid])
    if (object->name() == name)
      return object;
  mooseError("Unable to locate object: ", name, ".");
}
Referenced by FEProblemBase::getMultiApp().
getObjects()
template<typename T > const std::vector< std::shared_ptr< T > > & MooseObjectWarehouseBase< T >::getObjects (THREAD_ID tid = 0) const inline inherited
Retrieve complete vector to the all/block/boundary restricted objects for a given thread.
Parameters
tid The thread id to retrieve objects from
Definition at line 345 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _all_objects[tid];
}
Referenced by FEProblemBase::checkNonlocalCoupling(), MooseApp::errorCheck(), MooseObjectTagWarehouse< T >::getMatrixTagObjectWarehouse(), MooseObjectTagWarehouse< T >::getMatrixTagsObjectWarehouse(), MooseObjectTagWarehouse< T >::getVectorTagObjectWarehouse(), MooseObjectTagWarehouse< T >::getVectorTagsObjectWarehouse(), and FEProblemBase::setNonlocalCouplingMatrix().
hasActiveBlockObjects() [1/2]
template<typename T > bool MooseObjectWarehouseBase< T >::hasActiveBlockObjects (SubdomainID id, THREAD_ID tid = 0) const inherited
Definition at line 472 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  const auto iter = _active_block_objects[tid].find(id);
  return iter != _active_block_objects[tid].end();
}
hasActiveBlockObjects() [2/2]
template<typename T > bool MooseObjectWarehouseBase< T >::hasActiveBlockObjects (THREAD_ID tid = 0) const inherited
Definition at line 461 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  bool has_active_block_objects = false;
  for (const auto & object_pair : _active_block_objects[tid])
    has_active_block_objects |= !(object_pair.second.empty());
  return has_active_block_objects;
}
Referenced by AuxiliarySystem::computeElementalVarsHelper(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeMortarNodalVars(), AuxiliarySystem::computeNodalVarsHelper(), NonlinearThread::computeOnElement(), ComputeFullJacobianThread::computeOnInternalFace(), NonlinearSystemBase::computeResidualInternal(), BlockRestrictable::hasBlockMaterialPropertyHelper(), ComputeIndicatorThread::onElement(), ComputeMarkerThread::onElement(), ComputeMaterialsObjectThread::onElement(), ProjectMaterialProperties::onElement(), ComputeIndicatorThread::onInternalSide(), NonlinearThread::onInternalSide(), ComputeNodalKernelJacobiansThread::onNode(), ComputeNodalKernelsThread::onNode(), ComputeInitialConditionThread::operator()(), ComputeFVInitialConditionThread::operator()(), ComputeJacobianBlocksThread::postInternalSide(), FEProblemBase::prepareMaterials(), ComputeDiracThread::printBlockExecutionInformation(), ComputeIndicatorThread::printBlockExecutionInformation(), ComputeMarkerThread::printBlockExecutionInformation(), NonlinearThread::printBlockExecutionInformation(), FEProblemBase::reinitMaterials(), MooseObjectWarehouseBase< T >::updateBlockFEVariableCoupledVectorTagDependency(), MooseObjectWarehouseBase< T >::updateBlockMatPropDependency(), and MooseObjectWarehouseBase< T >::updateBlockVariableDependency().
hasActiveBoundaryObjects() [1/2]
template<typename T > bool MooseObjectWarehouseBase< T >::hasActiveBoundaryObjects (BoundaryID id, THREAD_ID tid = 0) const inherited
Definition at line 492 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  const auto iter = _active_boundary_objects[tid].find(id);
  return iter != _active_boundary_objects[tid].end();
}
hasActiveBoundaryObjects() [2/2]
template<typename T > bool MooseObjectWarehouseBase< T >::hasActiveBoundaryObjects (THREAD_ID tid = 0) const inherited
Definition at line 481 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  bool has_active_boundary_objects = false;
  for (const auto & object_pair : _active_boundary_objects[tid])
    has_active_boundary_objects |= !(object_pair.second.empty());
  return has_active_boundary_objects;
}
Referenced by AuxiliarySystem::computeElementalVarsHelper(), NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeMortarNodalVars(), NonlinearSystemBase::computeNodalBCs(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), AuxiliarySystem::computeNodalVarsHelper(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnInterface(), NonlinearSystemBase::computeResidualInternal(), BoundaryRestrictable::hasBoundaryMaterialPropertyHelper(), NonlinearSystemBase::needBoundaryMaterialOnSide(), FEProblemBase::needInterfaceMaterialOnSide(), NonlinearSystemBase::needInterfaceMaterialOnSide(), ComputeMaterialsObjectThread::onBoundary(), NonlinearThread::onBoundary(), ComputeMaterialsObjectThread::onInterface(), NonlinearThread::onInterface(), ComputeBoundaryInitialConditionThread::onNode(), ComputeNodalKernelBCJacobiansThread::onNode(), ComputeNodalKernelBcsThread::onNode(), NonlinearThread::printBoundaryExecutionInformation(), ComputeNodalKernelBCJacobiansThread::printGeneralExecutionInformation(), FEProblemBase::reinitMaterialsBoundary(), FEProblemBase::reinitMaterialsInterface(), NonlinearSystemBase::setInitialSolution(), MooseObjectWarehouseBase< T >::updateBoundaryFEVariableCoupledVectorTagDependency(), MooseObjectWarehouseBase< T >::updateBoundaryMatPropDependency(), and MooseObjectWarehouseBase< T >::updateBoundaryVariableDependency().
hasActiveElemElemConstraints()
bool ConstraintWarehouse::hasActiveElemElemConstraints (const InterfaceID interface_id, bool displaced) const
Definition at line 227 of file ConstraintWarehouse.C.
{
  std::map<unsigned int, MooseObjectWarehouse<ElemElemConstraint>>::const_iterator it, end_it;
  if (displaced)
  {
    it = _displaced_element_constraints.find(interface_id);
    end_it = _displaced_element_constraints.end();
  }
  else
  {
    it = _element_constraints.find(interface_id);
    end_it = _element_constraints.end();
  }
  return (it != end_it && it->second.hasActiveObjects());
}
Referenced by NonlinearSystemBase::constraintJacobians(), and NonlinearSystemBase::constraintResiduals().
hasActiveMortarConstraints()
bool ConstraintWarehouse::hasActiveMortarConstraints (const std::pair< BoundaryID, BoundaryID > & mortar_interface_key, bool displaced) const
Definition at line 135 of file ConstraintWarehouse.C.
{
  const auto & constraints = displaced ? _displaced_mortar_constraints : _mortar_constraints;
  return constraints.find(mortar_interface_key) != constraints.end();
}
Referenced by NonlinearSystemBase::initialSetup().
hasActiveNodalConstraints()
bool ConstraintWarehouse::hasActiveNodalConstraints () const
Deterimine if active objects exist.
Definition at line 221 of file ConstraintWarehouse.C.
{
  return _nodal_constraints.hasActiveObjects();
}
Referenced by NonlinearSystemBase::enforceNodalConstraintsJacobian(), and NonlinearSystemBase::enforceNodalConstraintsResidual().
hasActiveNodeElemConstraints()
bool ConstraintWarehouse::hasActiveNodeElemConstraints (SubdomainID secondary_id, SubdomainID primary_id, bool displaced) const
Definition at line 268 of file ConstraintWarehouse.C.
{
  std::map<std::pair<SubdomainID, SubdomainID>,
           MooseObjectWarehouse<NodeElemConstraint>>::const_iterator it,
      end_it;
  if (displaced)
  {
    it = _displaced_node_elem_constraints.find(std::make_pair(secondary_id, primary_id));
    end_it = _displaced_node_elem_constraints.end();
  }
  else
  {
    it = _node_elem_constraints.find(std::make_pair(secondary_id, primary_id));
    end_it = _node_elem_constraints.end();
  }
  return (it != end_it && it->second.hasActiveObjects());
}
Referenced by NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), and NonlinearSystemBase::setConstraintSecondaryValues().
hasActiveNodeFaceConstraints()
bool ConstraintWarehouse::hasActiveNodeFaceConstraints (BoundaryID boundary_id, bool displaced) const
Definition at line 248 of file ConstraintWarehouse.C.
{
  std::map<BoundaryID, MooseObjectWarehouse<NodeFaceConstraint>>::const_iterator it, end_it;
  if (displaced)
  {
    it = _displaced_node_face_constraints.find(boundary_id);
    end_it = _displaced_node_face_constraints.end();
  }
  else
  {
    it = _node_face_constraints.find(boundary_id);
    end_it = _node_face_constraints.end();
  }
  return (it != end_it && it->second.hasActiveObjects());
}
Referenced by NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), and NonlinearSystemBase::setConstraintSecondaryValues().
hasActiveObject()
template<typename T > bool MooseObjectWarehouseBase< T >::hasActiveObject (const std::string & name, THREAD_ID tid = 0) const inherited
Convenience functions for checking/getting specific objects.
Definition at line 501 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  for (const auto & object : _active_objects[tid])
    if (object->name() == name)
      return true;
  return false;
}
Referenced by FEProblemBase::hasFunction(), and FEProblemBase::hasMultiApp().
hasActiveObjects()
template<typename T > bool MooseObjectWarehouseBase< T >::hasActiveObjects (THREAD_ID tid = 0) const inherited
Definition at line 453 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return !_active_objects[tid].empty();
}
Referenced by DumpObjectsProblem::addAuxVariable(), NonlinearEigenSystem::checkIntegrity(), NonlinearSystemBase::checkKernelCoverage(), NonlinearSystemBase::computeDamping(), NonlinearSystemBase::computeDiracContributions(), FEProblemBase::computeIndicators(), NonlinearSystemBase::computeJacobianInternal(), FEProblemBase::computeMarkers(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeScalarKernelsJacobians(), AuxiliarySystem::computeScalarVars(), NonlinearSystemBase::containsTimeKernel(), FEProblemBase::execMultiAppTransfers(), hasActiveNodalConstraints(), FEProblemBase::hasMultiApps(), ComputeNodalKernelBcsThread::printGeneralExecutionInformation(), ComputeNodalKernelJacobiansThread::printGeneralExecutionInformation(), ComputeNodalKernelsThread::printGeneralExecutionInformation(), FEProblemBase::projectInitialConditionOnCustomRange(), FEProblemBase::projectSolution(), MooseObjectWarehouseBase< T >::updateMatPropDependency(), and MooseObjectWarehouseBase< T >::updateVariableDependency().
hasActiveVariableBlockObjects()
bool MooseObjectWarehouse< Constraint >::hasActiveVariableBlockObjects (unsigned int variable_id, SubdomainID block_id, THREAD_ID tid = 0) const inherited
Methods for checking/getting variable kernels for a variable and SubdomainID.
Definition at line 67 of file MooseObjectWarehouse.h.
{
  auto iter = _variable_objects.find(variable_id);
  return (iter != _variable_objects.end() && iter->second.hasActiveBlockObjects(block_id, tid));
}
hasBoundaryObjects()
template<typename T > bool MooseObjectWarehouseBase< T >::hasBoundaryObjects (BoundaryID id, THREAD_ID tid = 0) const inherited
Definition at line 361 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _all_boundary_objects[tid].find(id) != _all_boundary_objects[tid].end();
}
hasObjects()
template<typename T > bool MooseObjectWarehouseBase< T >::hasObjects (THREAD_ID tid = 0) const inherited
Convenience functions for determining if objects exist.
Definition at line 445 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return !_all_objects[tid].empty();
}
Referenced by DumpObjectsProblem::addAuxVariable().
initialSetup()
void MooseObjectWarehouse< Constraint >::initialSetup (THREAD_ID tid = 0) const virtual inherited
Convenience methods for calling object setup methods.
Definition at line 54 of file MooseObjectWarehouse.h.
{
  checkThreadID(tid);
  // Initial Setup should be called on all objects because they may become active later
  for (const auto & object : _all_objects[tid])
    object->initialSetup();
}
jacobianSetup()
void MooseObjectWarehouse< Constraint >::jacobianSetup (THREAD_ID tid = 0) const virtual inherited
Definition at line 59 of file MooseObjectWarehouse.h.
{
  checkThreadID(tid);
  for (const auto & object : _active_objects[tid])
    object->jacobianSetup();
}
numThreads()
template<typename T > THREAD_ID MooseObjectWarehouseBase< T >::numThreads () const inline inherited
Return the number of threads.
Definition at line 176 of file MooseObjectWarehouseBase.h.
{ return _num_threads; }
residualEnd()
void ConstraintWarehouse::residualEnd (THREAD_ID tid = 0) const virtual
Definition at line 354 of file ConstraintWarehouse.C.
{
  checkThreadID(tid);
  for (const auto & object : _active_objects[tid])
    object->residualEnd();
}
Referenced by NonlinearSystemBase::computeResidualInternal().
residualSetup()
void MooseObjectWarehouse< Constraint >::residualSetup (THREAD_ID tid = 0) const virtual inherited
Definition at line 60 of file MooseObjectWarehouse.h.
{
  checkThreadID(tid);
  for (const auto & object : _active_objects[tid])
    object->residualSetup();
}
size()
template<typename T > unsigned int MooseObjectWarehouseBase< T >::size (THREAD_ID tid = 0) const inherited
Return how many kernels we store in the current warehouse.
Definition at line 265 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _all_objects[tid].size();
}
Referenced by NonlinearThread::printBlockExecutionInformation().
sort()
template<typename T > void MooseObjectWarehouseBase< T >::sort (THREAD_ID tid = 0) inherited
Sort the objects using the DependencyResolver.
Definition at line 574 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  for (auto & object_pair : _all_block_objects[tid])
    sortHelper(object_pair.second);
  for (auto & object_pair : _all_boundary_objects[tid])
    sortHelper(object_pair.second);
  sortHelper(_all_objects[tid]);
  // The active lists now must be update to reflect the order changes
  updateActive(tid);
}
Referenced by DumpObjectsProblem::addAuxVariable(), ScalarInitialConditionWarehouse::initialSetup(), FVInitialConditionWarehouse::initialSetup(), and InitialConditionWarehouse::initialSetup().
sortHelper()
template<typename T > void MooseObjectWarehouseBase< T >::sortHelper (std::vector< std::shared_ptr< T > > & objects) static protected inherited
Helper method for sorting vectors of objects.
Definition at line 767 of file MooseObjectWarehouseBase.h.
{
  // Do nothing if the vector is empty
  if (objects.empty())
    return;
  try
  {
    // Sort based on dependencies
    DependencyResolverInterface::sort<std::shared_ptr<T>>(objects);
  }
  catch (CyclicDependencyException<std::shared_ptr<T>> & e)
  {
    DependencyResolverInterface::cyclicDependencyError<std::shared_ptr<T>>(
        e, "Cyclic dependency detected in object ordering");
  }
}
Referenced by MaterialWarehouse::sort(), and MooseObjectWarehouseBase< T >::sort().
subdomainsCovered()
void ConstraintWarehouse::subdomainsCovered (std::set< SubdomainID > & subdomains_covered, std::set< std::string > & unique_variables, THREAD_ID tid = 0) const
Update supplied subdomain and variable coverate containters.
Definition at line 314 of file ConstraintWarehouse.C.
{
  // Loop over undisplaced
  for (const auto & pr : _mortar_constraints)
  {
    const auto & objects = pr.second.getActiveObjects();
    for (const auto & mc : objects)
    {
      const MooseVariableFEBase * lm_var = mc->variablePtr();
      if (lm_var)
        unique_variables.insert(lm_var->name());
      // Mortar constraints will cover primary and secondary subdomains regardless of whether we
      // have a Lagrange multiplier associated.
      subdomains_covered.insert(mc->primarySubdomain());
      subdomains_covered.insert(mc->secondarySubdomain());
    }
  }
  // Loop over displaced
  for (const auto & pr : _displaced_mortar_constraints)
  {
    const auto & objects = pr.second.getActiveObjects();
    for (const auto & mc : objects)
    {
      const MooseVariableFEBase * lm_var = mc->variablePtr();
      if (lm_var)
        unique_variables.insert(lm_var->name());
      // Mortar constraints will cover primary and secondary subdomains regardless of whether we
      // have a Lagrange multiplier associated.
      subdomains_covered.insert(mc->primarySubdomain());
      subdomains_covered.insert(mc->secondarySubdomain());
    }
  }
}
Referenced by NonlinearSystemBase::checkKernelCoverage().
subdomainSetup() [1/2]
void MooseObjectWarehouse< Constraint >::subdomainSetup (SubdomainID id, THREAD_ID tid = 0) const virtual inherited
Definition at line 58 of file MooseObjectWarehouse.h.
{
  checkThreadID(tid);
  if (hasActiveBlockObjects(id, tid))
  {
    const auto & objects = getActiveBlockObjects(id, tid);
    for (const auto & object : objects)
      object->subdomainSetup();
  }
}
subdomainSetup() [2/2]
void MooseObjectWarehouse< Constraint >::subdomainSetup (THREAD_ID tid = 0) const virtual inherited
Definition at line 57 of file MooseObjectWarehouse.h.
{
  checkThreadID(tid);
  for (const auto & object : _active_objects[tid])
    object->subdomainSetup();
}
timestepSetup()
void MooseObjectWarehouse< Constraint >::timestepSetup (THREAD_ID tid = 0) const virtual inherited
Definition at line 55 of file MooseObjectWarehouse.h.
{
  checkThreadID(tid);
  for (const auto & object : _active_objects[tid])
    object->timestepSetup();
}
updateActive()
void ConstraintWarehouse::updateActive (THREAD_ID tid = 0) override virtual
Update the various active lists.
Reimplemented from MooseObjectWarehouse< Constraint >.
Definition at line 291 of file ConstraintWarehouse.C.
{
  MooseObjectWarehouse<Constraint>::updateActive();
  _nodal_constraints.updateActive();
  for (auto & it : _node_face_constraints)
    it.second.updateActive();
  for (auto & it : _displaced_node_face_constraints)
    it.second.updateActive();
  // FIXME: We call updateActive() on the NodeFaceConstraints again?
  for (auto & it : _node_face_constraints)
    it.second.updateActive();
  for (auto & it : _element_constraints)
    it.second.updateActive();
  for (auto & it : _node_elem_constraints)
    it.second.updateActive();
}
Referenced by NonlinearSystemBase::updateActive().
updateActiveHelper()
template<typename T > void MooseObjectWarehouseBase< T >::updateActiveHelper (std::vector< std::shared_ptr< T > > & active, const std::vector< std::shared_ptr< T > > & all) static protected inherited
Helper method for updating active vectors.
Definition at line 560 of file MooseObjectWarehouseBase.h.
{
  // Clear the active list
  active.clear();
  std::copy_if(all.begin(),
               all.end(),
               std::back_inserter(active),
               [](const std::shared_ptr<T> & object) { return object->enabled(); });
}
Referenced by MooseObjectWarehouseBase< T >::updateActive().
updateBlockFEVariableCoupledVectorTagDependency()
template<typename T > void MooseObjectWarehouseBase< T >::updateBlockFEVariableCoupledVectorTagDependency (SubdomainID id, std::set< TagID > & needed_fe_var_vector_tags, THREAD_ID tid = 0) const inherited
Update FE variable coupleable vector tag vector.
Definition at line 653 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBlockObjects(id, tid))
    updateFEVariableCoupledVectorTagDependencyHelper(needed_fe_var_vector_tags,
                                                     getActiveBlockObjects(id, tid));
}
Referenced by ComputeNodalKernelsThread::onNode(), ComputeIndicatorThread::subdomainChanged(), ComputeMaterialsObjectThread::subdomainChanged(), and ComputeUserObjectsThread::subdomainChanged().
updateBlockMatPropDependency()
template<typename T > void MooseObjectWarehouseBase< T >::updateBlockMatPropDependency (SubdomainID id, std::set< unsigned int > & needed_mat_props, THREAD_ID tid = 0) const inherited
Definition at line 698 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBlockObjects(id, tid))
    updateMatPropDependencyHelper(needed_mat_props, getActiveBlockObjects(id, tid));
}
Referenced by FEProblemBase::prepareMaterials().
updateBlockVariableDependency()
template<typename T > void MooseObjectWarehouseBase< T >::updateBlockVariableDependency (SubdomainID id, std::set< MooseVariableFieldBase * > & needed_moose_vars, THREAD_ID tid = 0) const inherited
Definition at line 601 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBlockObjects(id, tid))
    updateVariableDependencyHelper(needed_moose_vars, getActiveBlockObjects(id, tid));
}
updateBoundaryFEVariableCoupledVectorTagDependency()
template<typename T > void MooseObjectWarehouseBase< T >::updateBoundaryFEVariableCoupledVectorTagDependency (BoundaryID id, std::set< TagID > & needed_fe_var_vector_tags, THREAD_ID tid = 0) const inherited
Definition at line 663 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBoundaryObjects(id, tid))
    updateFEVariableCoupledVectorTagDependencyHelper(needed_fe_var_vector_tags,
                                                     getActiveBoundaryObjects(id, tid));
}
Referenced by ComputeNodalKernelBcsThread::onNode().
updateBoundaryMatPropDependency() [1/2]
template<typename T > void MooseObjectWarehouseBase< T >::updateBoundaryMatPropDependency (BoundaryID id, std::set< unsigned int > & needed_mat_props, THREAD_ID tid = 0) const inherited
Definition at line 718 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBoundaryObjects(id, tid))
    updateMatPropDependencyHelper(needed_mat_props, getActiveBoundaryObjects(id, tid));
}
updateBoundaryMatPropDependency() [2/2]
template<typename T > void MooseObjectWarehouseBase< T >::updateBoundaryMatPropDependency (std::set< unsigned int > & needed_mat_props, THREAD_ID tid = 0) const inherited
Definition at line 708 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBoundaryObjects(tid))
    for (auto & active_bnd_object : _active_boundary_objects[tid])
      updateMatPropDependencyHelper(needed_mat_props, active_bnd_object.second);
}
Referenced by FEProblemBase::prepareMaterials().
updateBoundaryVariableDependency() [1/2]
template<typename T > void MooseObjectWarehouseBase< T >::updateBoundaryVariableDependency (BoundaryID id, std::set< MooseVariableFieldBase * > & needed_moose_vars, THREAD_ID tid = 0) const inherited
Definition at line 625 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBoundaryObjects(id, tid))
    updateVariableDependencyHelper(needed_moose_vars, getActiveBoundaryObjects(id, tid));
}
updateBoundaryVariableDependency() [2/2]
template<typename T > void MooseObjectWarehouseBase< T >::updateBoundaryVariableDependency (std::set< MooseVariableFieldBase * > & needed_moose_vars, THREAD_ID tid = 0) const inherited
Definition at line 612 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBoundaryObjects(tid))
  {
    typename std::map<BoundaryID, std::vector<std::shared_ptr<T>>>::const_iterator it;
    for (const auto & object_pair : _active_boundary_objects[tid])
      updateVariableDependencyHelper(needed_moose_vars, object_pair.second);
  }
}
Referenced by FEProblemBase::prepareMaterials().
updateFEVariableCoupledVectorTagDependencyHelper()
template<typename T > void MooseObjectWarehouseBase< T >::updateFEVariableCoupledVectorTagDependencyHelper (std::set< TagID > & needed_fe_var_vector_tags, const std::vector< std::shared_ptr< T > > & objects) static protected inherited
Helper method for updating FE variable coupleable vector tag vector.
Definition at line 673 of file MooseObjectWarehouseBase.h.
{
  for (const auto & object : objects)
  {
    auto c = dynamic_cast<const Coupleable *>(object.get());
    if (c)
    {
      const auto & tag_deps = c->getFEVariableCoupleableVectorTags();
      needed_fe_var_vector_tags.insert(tag_deps.begin(), tag_deps.end());
    }
  }
}
Referenced by MooseObjectWarehouseBase< T >::updateBlockFEVariableCoupledVectorTagDependency(), and MooseObjectWarehouseBase< T >::updateBoundaryFEVariableCoupledVectorTagDependency().
updateMatPropDependency()
template<typename T > void MooseObjectWarehouseBase< T >::updateMatPropDependency (std::set< unsigned int > & needed_mat_props, THREAD_ID tid = 0) const inherited
Update material property dependency vector.
Definition at line 689 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveObjects(tid))
    updateMatPropDependencyHelper(needed_mat_props, _all_objects[tid]);
}
Referenced by ComputeDiracThread::subdomainChanged(), and ComputeIndicatorThread::subdomainChanged().
updateMatPropDependencyHelper()
template<typename T > void MooseObjectWarehouseBase< T >::updateMatPropDependencyHelper (std::set< unsigned int > & needed_mat_props, const std::vector< std::shared_ptr< T > > & objects) static protected inherited
Helper method for updating material property dependency vector.
Definition at line 727 of file MooseObjectWarehouseBase.h.
{
  for (auto & object : objects)
  {
    auto c = dynamic_cast<const MaterialPropertyInterface *>(object.get());
    if (c)
    {
      auto & mp_deps = c->getMatPropDependencies();
      needed_mat_props.insert(mp_deps.begin(), mp_deps.end());
    }
  }
}
Referenced by MooseObjectWarehouseBase< T >::updateBlockMatPropDependency(), MooseObjectWarehouseBase< T >::updateBoundaryMatPropDependency(), and MooseObjectWarehouseBase< T >::updateMatPropDependency().
updateVariableDependency()
template<typename T > void MooseObjectWarehouseBase< T >::updateVariableDependency (std::set< MooseVariableFieldBase * > & needed_moose_vars, THREAD_ID tid = 0) const inherited
Update variable dependency vector.
Definition at line 592 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveObjects(tid))
    updateVariableDependencyHelper(needed_moose_vars, _all_objects[tid]);
}
Referenced by FEProblemBase::prepareMaterials(), ComputeDiracThread::subdomainChanged(), ComputeIndicatorThread::subdomainChanged(), ComputeMarkerThread::subdomainChanged(), and ComputeMaterialsObjectThread::subdomainChanged().
updateVariableDependencyHelper()
template<typename T > void MooseObjectWarehouseBase< T >::updateVariableDependencyHelper (std::set< MooseVariableFieldBase * > & needed_moose_vars, const std::vector< std::shared_ptr< T > > & objects) static protected inherited
Helper method for updating variable dependency vector.
Definition at line 636 of file MooseObjectWarehouseBase.h.
{
  for (const auto & object : objects)
  {
    auto c = dynamic_cast<const MooseVariableDependencyInterface *>(object.get());
    if (c)
    {
      const auto & mv_deps = c->getMooseVariableDependencies();
      needed_moose_vars.insert(mv_deps.begin(), mv_deps.end());
    }
  }
}
Referenced by MooseObjectWarehouseBase< T >::updateBlockVariableDependency(), MooseObjectWarehouseBase< T >::updateBoundaryVariableDependency(), and MooseObjectWarehouseBase< T >::updateVariableDependency().
Member Data Documentation
_active_block_objects
template<typename T > std::vector<std::map<SubdomainID, std::vector<std::shared_ptr<T> > > > MooseObjectWarehouseBase< T >::_active_block_objects protected inherited
Active block restricted objects (THREAD_ID on outer vector)
Definition at line 200 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getActiveBlockObjects(), MooseObjectWarehouseBase< T >::getActiveBlocks(), MooseObjectWarehouseBase< T >::hasActiveBlockObjects(), MooseObjectWarehouseBase< T >::subdomainsCovered(), and MooseObjectWarehouseBase< T >::updateActive().
_active_boundary_objects
template<typename T > std::vector<std::map<BoundaryID, std::vector<std::shared_ptr<T> > > > MooseObjectWarehouseBase< T >::_active_boundary_objects protected inherited
Active boundary restricted objects (THREAD_ID on outer vector)
Definition at line 206 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getActiveBoundaryObjects(), MooseObjectWarehouseBase< T >::hasActiveBoundaryObjects(), MooseObjectWarehouseBase< T >::updateActive(), MooseObjectWarehouseBase< T >::updateBoundaryMatPropDependency(), and MooseObjectWarehouseBase< T >::updateBoundaryVariableDependency().
_active_objects
template<typename T > std::vector<std::vector<std::shared_ptr<T> > > MooseObjectWarehouseBase< T >::_active_objects protected inherited
All active objects (THREAD_ID on outer vector)
Definition at line 194 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::activeObjectsToFormattedString(), MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getActiveObject(), MooseObjectWarehouseBase< T >::getActiveObjects(), MooseObjectWarehouseBase< T >::hasActiveObject(), MooseObjectWarehouseBase< T >::hasActiveObjects(), residualEnd(), MooseObjectWarehouseBase< T >::subdomainsCovered(), and MooseObjectWarehouseBase< T >::updateActive().
_all_block_objects
template<typename T > std::vector<std::map<SubdomainID, std::vector<std::shared_ptr<T> > > > MooseObjectWarehouseBase< T >::_all_block_objects protected inherited
Definition at line 197 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getBlockObjects(), MaterialWarehouse::sort(), MooseObjectWarehouseBase< T >::sort(), and MooseObjectWarehouseBase< T >::updateActive().
_all_boundary_objects
template<typename T > std::vector<std::map<BoundaryID, std::vector<std::shared_ptr<T> > > > MooseObjectWarehouseBase< T >::_all_boundary_objects protected inherited
Definition at line 203 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getBoundaryObjects(), MooseObjectWarehouseBase< T >::hasBoundaryObjects(), MaterialWarehouse::sort(), MooseObjectWarehouseBase< T >::sort(), and MooseObjectWarehouseBase< T >::updateActive().
_all_objects
template<typename T > std::vector<std::vector<std::shared_ptr<T> > > MooseObjectWarehouseBase< T >::_all_objects protected inherited
Storage container for the ALL pointers (THREAD_ID on outer vector)
Definition at line 191 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getObject(), MooseObjectWarehouseBase< T >::getObjects(), MooseObjectWarehouseBase< T >::hasObjects(), MooseObjectWarehouseBase< T >::size(), MooseObjectWarehouseBase< T >::sort(), MooseObjectWarehouseBase< T >::updateActive(), MooseObjectWarehouseBase< T >::updateMatPropDependency(), and MooseObjectWarehouseBase< T >::updateVariableDependency().
_displaced_element_constraints
std::map<unsigned int, MooseObjectWarehouse<ElemElemConstraint> > ConstraintWarehouse::_displaced_element_constraints protected
ElemElemConstraints (displaced)
Definition at line 105 of file ConstraintWarehouse.h.
Referenced by addObject(), getActiveElemElemConstraints(), and hasActiveElemElemConstraints().
_displaced_mortar_constraints
std::map<std::pair<BoundaryID, BoundaryID>, MooseObjectWarehouse<MortarConstraintBase> > ConstraintWarehouse::_displaced_mortar_constraints protected
Displaced MortarConstraints.
Definition at line 99 of file ConstraintWarehouse.h.
Referenced by addObject(), getActiveMortarConstraints(), hasActiveMortarConstraints(), and subdomainsCovered().
_displaced_node_elem_constraints
std::map<std::pair<SubdomainID, SubdomainID>, MooseObjectWarehouse<NodeElemConstraint> > ConstraintWarehouse::_displaced_node_elem_constraints protected
NodeElemConstraint objects.
Definition at line 113 of file ConstraintWarehouse.h.
Referenced by addObject(), getActiveNodeElemConstraints(), and hasActiveNodeElemConstraints().
_displaced_node_face_constraints
std::map<BoundaryID, MooseObjectWarehouse<NodeFaceConstraint> > ConstraintWarehouse::_displaced_node_face_constraints protected
NodeFaceConstraint objects (displaced)
Definition at line 91 of file ConstraintWarehouse.h.
Referenced by addObject(), getActiveNodeFaceConstraints(), hasActiveNodeFaceConstraints(), and updateActive().
_element_constraints
std::map<unsigned int, MooseObjectWarehouse<ElemElemConstraint> > ConstraintWarehouse::_element_constraints protected
ElemElemConstraints (non-displaced)
Definition at line 102 of file ConstraintWarehouse.h.
Referenced by addObject(), getActiveElemElemConstraints(), hasActiveElemElemConstraints(), and updateActive().
_mortar_constraints
std::map<std::pair<BoundaryID, BoundaryID>, MooseObjectWarehouse<MortarConstraintBase> > ConstraintWarehouse::_mortar_constraints protected
Undisplaced MortarConstraints.
Definition at line 95 of file ConstraintWarehouse.h.
Referenced by addObject(), getActiveMortarConstraints(), hasActiveMortarConstraints(), and subdomainsCovered().
_nodal_constraints
MooseObjectWarehouse<NodalConstraint> ConstraintWarehouse::_nodal_constraints protected
NodalConstraint objects.
Definition at line 85 of file ConstraintWarehouse.h.
Referenced by addObject(), getActiveNodalConstraints(), hasActiveNodalConstraints(), and updateActive().
_node_elem_constraints
std::map<std::pair<SubdomainID, SubdomainID>, MooseObjectWarehouse<NodeElemConstraint> > ConstraintWarehouse::_node_elem_constraints protected
NodeElemConstraint objects.
Definition at line 109 of file ConstraintWarehouse.h.
Referenced by addObject(), getActiveNodeElemConstraints(), hasActiveNodeElemConstraints(), and updateActive().
_node_face_constraints
std::map<BoundaryID, MooseObjectWarehouse<NodeFaceConstraint> > ConstraintWarehouse::_node_face_constraints protected
NodeFaceConstraint objects (non-displaced)
Definition at line 88 of file ConstraintWarehouse.h.
Referenced by addObject(), getActiveNodeFaceConstraints(), hasActiveNodeFaceConstraints(), and updateActive().
_num_threads
template<typename T > const THREAD_ID MooseObjectWarehouseBase< T >::_num_threads protected inherited
Convenience member storing the number of threads used for storage (1 or libMesh::n_threads)
Definition at line 188 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::checkThreadID(), and MooseObjectWarehouseBase< T >::numThreads().
_variable_objects
std::map<unsigned int, MooseObjectWarehouse<Constraint > > MooseObjectWarehouse< Constraint >::_variable_objects protected inherited
Variable based storage.
Definition at line 82 of file MooseObjectWarehouse.h.
The documentation for this class was generated from the following files:
moose/framework/include/constraints/ConstraintWarehouse.h
moose/framework/src/constraints/ConstraintWarehouse.C