Zapdos: RestartableDataValue Class Reference
RestartableDataValue Class Reference abstract
Abstract definition of a RestartableData value.
#include <RestartableData.h>
Classes
class SetDeclaredKey
Helper that protects access to setDeclared() to only MooseApp.
class SetNotLoadedKey
Helper that protects access to setNotLoaded() to only RestartableDataReader.
class SetNotStoredKey
Helper that protects access to setNotStored() to only RestartableDataWriter.
struct StoreJSONParams
Struct that represents parameters for how to store the JSON value via store.
Public Member Functions
RestartableDataValue (const std::string &name, void *const context)
Constructor.
virtual ~RestartableDataValue ()=default
Destructor.
virtual std::string type () const =0
String identifying the type of parameter stored.
virtual const std::type_info & typeId () const =0
The type ID of the underlying data.
const std::string & name () const
The full (unique) name of this particular piece of data.
void * context ()
A context pointer for helping with load / store.
bool hasContext () const
bool declared () const
Whether or not this data has been declared.
void setDeclared (const SetDeclaredKey)
Sets that this restartable value has been declared.
bool loaded () const
Whether or not this data has been loaded.
void setNotLoaded (const SetNotLoadedKey)
Sets that this restartable value has been loaded.
bool stored () const
Whether or not this data has been loaded.
void setNotStored (const SetNotStoredKey)
Sets that this restartable value has been loaded.
void store (std::ostream &stream)
Stores the value into the stream stream and sets it as stored.
void load (std::istream &stream)
Loads the value from the stream stream and sets it as loaded.
virtual void storeInternal (std::ostream &stream)=0
Internal method that stores the value into the stream stream in the specialized class.
virtual void loadInternal (std::istream &stream)=0
Internal method that loads the value from the stream stream in the specialized class.
virtual bool hasStoreJSON () const =0
void store (nlohmann::json &json, const StoreJSONParams &params=StoreJSONParams{}) const
Stores this restartable data in the JSON entry json, with the options set by params (optional; defaults to just the type and underlying value)
Protected Member Functions
virtual void storeJSONValue (nlohmann::json &json) const =0
Internal method for storing the underlying JSON value.
Protected Attributes
const std::string _name
The full (unique) name of this particular piece of data.
void *const _context
A context pointer for helping with load and store.
Private Attributes
bool _declared
Whether or not this data has been declared (true) or only retreived (false)
bool _loaded
Whether or not this has value has been loaded.
bool _stored
Whether or not this has value has been stored.
Detailed Description
Abstract definition of a RestartableData value.
Definition at line 31 of file RestartableData.h.
Constructor & Destructor Documentation
RestartableDataValue()
RestartableDataValue::RestartableDataValue (const std::string & name, void *const context)
Constructor.
Parameters
name The full (unique) name for this piece of data.
context 'typeless' pointer to user-specific data.
Definition at line 12 of file RestartableData.C.
  : _name(name), _context(context), _declared(false), _loaded(false), _stored(false)
{
}
~RestartableDataValue()
virtual RestartableDataValue::~RestartableDataValue () virtual default
Destructor.
Member Function Documentation
context()
void * RestartableDataValue::context () inline
A context pointer for helping with load / store.
Definition at line 65 of file RestartableData.h.
{ return _context; }
declared()
bool RestartableDataValue::declared () const inline
Whether or not this data has been declared.
Definition at line 85 of file RestartableData.h.
{ return _declared; }
Referenced by store().
hasContext()
bool RestartableDataValue::hasContext () const inline
Returns
Whether or not the data has context set.
Definition at line 70 of file RestartableData.h.
{ return _context != nullptr; }
Referenced by store().
hasStoreJSON()
virtual bool RestartableDataValue::hasStoreJSON () const pure virtual
Returns
Whether or not this value supports storing JSON via store
Implemented in RestartableData< T >, RestartableData< std::list< T > >, RestartableData< std::list< std::vector< T > > >, and RestartableData< RestartableEquationSystems >.
Referenced by store().
load()
void RestartableDataValue::load (std::istream & stream)
Loads the value from the stream stream and sets it as loaded.
Definition at line 32 of file RestartableData.C.
{
  loadInternal(stream);
  _loaded = true;
}
loaded()
bool RestartableDataValue::loaded () const inline
Whether or not this data has been loaded.
This is typically reset on a call to RestartableDataReader::restore()
Definition at line 98 of file RestartableData.h.
{ return _loaded; }
Referenced by store().
loadInternal()
virtual void RestartableDataValue::loadInternal (std::istream & stream) pure virtual
Internal method that loads the value from the stream stream in the specialized class.
Implemented in RestartableData< T >, RestartableData< std::list< T > >, RestartableData< std::list< std::vector< T > > >, RestartableData< RestartableEquationSystems >, ReporterState< T >, and ReporterState< std::vector< T > >.
Referenced by load().
name()
const std::string & RestartableDataValue::name () const inline
The full (unique) name of this particular piece of data.
Definition at line 60 of file RestartableData.h.
{ return _name; }
Referenced by RestartableDataMap::addData(), RestartableDataMap::findData(), and store().
setDeclared()
void RestartableDataValue::setDeclared (const SetDeclaredKey)
Sets that this restartable value has been declared.
Definition at line 18 of file RestartableData.C.
{
  mooseAssert(!_declared, "Already declared");
  _declared = true;
}
Referenced by MooseApp::registerRestartableData().
setNotLoaded()
void RestartableDataValue::setNotLoaded (const SetNotLoadedKey) inline
Sets that this restartable value has been loaded.
Definition at line 113 of file RestartableData.h.
{ _loaded = false; }
setNotStored()
void RestartableDataValue::setNotStored (const SetNotStoredKey) inline
Sets that this restartable value has been loaded.
Definition at line 136 of file RestartableData.h.
{ _stored = false; }
store() [1/2]
void RestartableDataValue::store (nlohmann::json & json, const StoreJSONParams & params = StoreJSONParams{}) const
Stores this restartable data in the JSON entry json, with the options set by params (optional; defaults to just the type and underlying value)
If the underlying type is not supported for JSON output (if hasStoreJSON() == false), and the parameters have the value output as enabled, this will error.
Definition at line 39 of file RestartableData.C.
{
  if (params.value)
  {
    if (hasStoreJSON())
      storeJSONValue(json["value"]);
    else
      mooseError("Failed to output restartable data '",
                 name(),
                 "' as JSON because a to_json method is not implemented for the type '",
                 type(),
                 "'");
  }
  if (params.type)
    json["type"] = type();
  if (params.name)
    json["name"] = name();
  if (params.declared)
    json["declared"] = declared();
  if (params.loaded)
    json["loaded"] = loaded();
  if (params.stored)
    json["stored"] = stored();
  if (params.has_context)
    json["has_context"] = hasContext();
}
store() [2/2]
void RestartableDataValue::store (std::ostream & stream)
Stores the value into the stream stream and sets it as stored.
Definition at line 25 of file RestartableData.C.
{
  storeInternal(stream);
  _stored = true;
}
stored()
bool RestartableDataValue::stored () const inline
Whether or not this data has been loaded.
This is typically reset on a call to RestartableDataWriter::write()
Definition at line 121 of file RestartableData.h.
{ return _stored; }
Referenced by store().
storeInternal()
virtual void RestartableDataValue::storeInternal (std::ostream & stream) pure virtual
Internal method that stores the value into the stream stream in the specialized class.
Implemented in RestartableData< T >, RestartableData< std::list< T > >, RestartableData< std::list< std::vector< T > > >, RestartableData< RestartableEquationSystems >, ReporterState< T >, and ReporterState< std::vector< T > >.
Referenced by store().
storeJSONValue()
virtual void RestartableDataValue::storeJSONValue (nlohmann::json & json) const protected pure virtual
Internal method for storing the underlying JSON value.
Implemented in RestartableData< T >, RestartableData< std::list< T > >, RestartableData< std::list< std::vector< T > > >, and RestartableData< RestartableEquationSystems >.
Referenced by store().
type()
virtual std::string RestartableDataValue::type () const pure virtual
String identifying the type of parameter stored.
Must be reimplemented in derived classes.
Implemented in RestartableData< T >, RestartableData< std::list< T > >, RestartableData< std::list< std::vector< T > > >, and RestartableData< RestartableEquationSystems >.
Referenced by MooseApp::registerRestartableData(), and store().
typeId()
virtual const std::type_info & RestartableDataValue::typeId () const pure virtual
The type ID of the underlying data.
Implemented in RestartableData< T >, RestartableData< std::list< T > >, RestartableData< std::list< std::vector< T > > >, and RestartableData< RestartableEquationSystems >.
Referenced by MooseApp::registerRestartableData().
Member Data Documentation
_context
void* const RestartableDataValue::_context protected
A context pointer for helping with load and store.
Definition at line 197 of file RestartableData.h.
Referenced by context(), and hasContext().
_declared
bool RestartableDataValue::_declared private
Whether or not this data has been declared (true) or only retreived (false)
Definition at line 201 of file RestartableData.h.
Referenced by declared(), and setDeclared().
_loaded
bool RestartableDataValue::_loaded private
Whether or not this has value has been loaded.
Definition at line 204 of file RestartableData.h.
Referenced by load(), loaded(), and setNotLoaded().
_name
const std::string RestartableDataValue::_name protected
The full (unique) name of this particular piece of data.
Definition at line 194 of file RestartableData.h.
Referenced by name().
_stored
bool RestartableDataValue::_stored private
Whether or not this has value has been stored.
Definition at line 207 of file RestartableData.h.
Referenced by setNotStored(), store(), and stored().
The documentation for this class was generated from the following files:
moose/framework/include/restart/RestartableData.h
moose/framework/src/restart/RestartableData.C