Zapdos: PointListAdaptor< PointObject > Class Template Reference
PointListAdaptor< PointObject > Class Template Reference
#include <PointListAdaptor.h>
Public Types
using Iterator = typename std::vector< PointObject >::const_iterator
using coord_t = Real
libMesh Point coordinate type
Public Member Functions
PointListAdaptor (Iterator begin, Iterator end)
size_t kdtree_get_point_count () const
Must return the number of data points.
const Point & getPoint (const PointObject &item) const
get a Point reference from the PointData object at index idx in the list
coord_t kdtree_distance (const coord_t *p1, const size_t idx_p2, size_t) const
Returns the distance between the vector "p1[0:size-1]" and the data point with index "idx_p2" stored in the class.
coord_t kdtree_get_pt (const size_t idx, int dim) const
Returns the dim'th component of the idx'th point in the class.
template<class BBOX >
bool kdtree_get_bbox (BBOX &) const
Optional bounding-box computation.
const Point & getPoint (const MooseMesh::PeriodicNodeInfo &item) const
const Point & getPoint (const RadialAverage::QPData &item) const
Private Attributes
const Iterator _begin
begin iterator of the underlying point type vector
const Iterator _end
end iterator of the underlying point type vector
std::size_t _size
number of elements pointed to
Detailed Description
template<typename PointObject>
class PointListAdaptor< PointObject >
Definition at line 19 of file PointListAdaptor.h.
Member Typedef Documentation
coord_t
template<typename PointObject > using PointListAdaptor< PointObject >::coord_t = Real
libMesh Point coordinate type
Definition at line 43 of file PointListAdaptor.h.
Iterator
template<typename PointObject > using PointListAdaptor< PointObject >::Iterator = typename std::vector<PointObject>::const_iterator
Definition at line 22 of file PointListAdaptor.h.
Constructor & Destructor Documentation
PointListAdaptor()
template<typename PointObject > PointListAdaptor< PointObject >::PointListAdaptor (Iterator begin, Iterator end) inline
Definition at line 24 of file PointListAdaptor.h.
    : _begin(begin), _end(end), _size(std::distance(begin, end))
  {
  }
Member Function Documentation
getPoint() [1/3]
const Point & PointListAdaptor< MooseMesh::PeriodicNodeInfo >::getPoint (const MooseMesh::PeriodicNodeInfo & item) const inline
Definition at line 1570 of file MooseMesh.C.
{
  return *(item.first);
}
getPoint() [2/3]
template<typename PointObject > const Point & PointListAdaptor< PointObject >::getPoint (const PointObject & item) const
get a Point reference from the PointData object at index idx in the list
Referenced by PointListAdaptor< PointObject >::kdtree_distance(), and PointListAdaptor< PointObject >::kdtree_get_pt().
getPoint() [3/3]
const Point & PointListAdaptor< RadialAverage::QPData >::getPoint (const RadialAverage::QPData & item) const
Definition at line 39 of file RadialAverage.C.
{
  return item._q_point;
}
kdtree_distance()
template<typename PointObject > coord_t PointListAdaptor< PointObject >::kdtree_distance (const coord_t * p1, const size_t idx_p2, size_t) const inline
Returns the distance between the vector "p1[0:size-1]" and the data point with index "idx_p2" stored in the class.
Definition at line 59 of file PointListAdaptor.h.
  {
    mooseAssert(idx_p2 < _size,
                "The point index should be less than"
                "total number of points used to build"
                "the KDTree.");
    auto it = _begin;
    std::advance(it, idx_p2);
    const Point & p2 = getPoint(*it);
    coord_t dist = 0.0;
    for (const auto i : make_range(Moose::dim))
      dist += Utility::pow<2>(p1[i] - p2(i));
    return dist;
  }
kdtree_get_bbox()
template<typename PointObject > template<class BBOX > bool PointListAdaptor< PointObject >::kdtree_get_bbox (BBOX &) const inline
Optional bounding-box computation.
This function is called by the nanoflann library. If the return value is false, the standard bbox computation loop in the nanoflann library is activated.
Definition at line 103 of file PointListAdaptor.h.
  {
    return false;
  }
kdtree_get_point_count()
template<typename PointObject > size_t PointListAdaptor< PointObject >::kdtree_get_point_count () const inline
Must return the number of data points.
Definition at line 48 of file PointListAdaptor.h.
{ return _size; }
Referenced by KDTree::numberCandidatePoints().
kdtree_get_pt()
template<typename PointObject > coord_t PointListAdaptor< PointObject >::kdtree_get_pt (const size_t idx, int dim) const inline
Returns the dim'th component of the idx'th point in the class.
Definition at line 81 of file PointListAdaptor.h.
  {
    mooseAssert(dim < (int)Moose::dim,
                "The required component number should be less than the LIBMESH_DIM.");
    mooseAssert(idx < _size,
                "The index of the point should be less"
                "than total number of points used to"
                "construct the KDTree.");
    auto it = _begin;
    std::advance(it, idx);
    const Point & p = getPoint(*it);
    return p(dim);
  }
Member Data Documentation
_begin
template<typename PointObject > const Iterator PointListAdaptor< PointObject >::_begin private
begin iterator of the underlying point type vector
Definition at line 31 of file PointListAdaptor.h.
Referenced by PointListAdaptor< PointObject >::kdtree_distance(), and PointListAdaptor< PointObject >::kdtree_get_pt().
_end
template<typename PointObject > const Iterator PointListAdaptor< PointObject >::_end private
end iterator of the underlying point type vector
Definition at line 34 of file PointListAdaptor.h.
_size
template<typename PointObject > std::size_t PointListAdaptor< PointObject >::_size private
number of elements pointed to
Definition at line 37 of file PointListAdaptor.h.
Referenced by PointListAdaptor< PointObject >::kdtree_distance(), PointListAdaptor< PointObject >::kdtree_get_point_count(), and PointListAdaptor< PointObject >::kdtree_get_pt().
The documentation for this class was generated from the following file:
moose/framework/include/utils/PointListAdaptor.h