Zapdos: AppFactory Class Reference
AppFactory Class Reference
Generic AppFactory class for building Application objects.
#include <AppFactory.h>
Public Member Functions
virtual ~AppFactory ()
template<typename T >
void reg (const std::string &name)
Register a new object.
InputParameters getValidParams (const std::string &name)
Get valid parameters for the object.
MooseAppPtr createShared (const std::string &app_type, const std::string &name, InputParameters parameters, MPI_Comm COMM_WORLD_IN)
Build an application object (must be registered)
const auto & registeredObjects () const
Returns a reference to the map from names to AppFactoryBuildInfo pointers.
bool isRegistered (const std::string &app_name) const
Returns a Boolean indicating whether an application type has been registered.
std::size_t createdAppCount (const std::string &app_type) const
const AppFactoryBuildInfoMap & registeredObjectBuildInfos () const
Returns the map of object name to a function pointer for building said object's input parameters.
AppFactory (AppFactory const &)=delete
Don't allow creation through copy/move construction or assignment.
Registry & operator= (AppFactory const &)=delete
AppFactory (AppFactory &&)=delete
Registry & operator= (AppFactory &&)=delete
Static Public Member Functions
static AppFactory & instance ()
Get the instance of the AppFactory.
static MooseAppPtr createAppShared (const std::string &default_app_type, int argc, char **argv, MPI_Comm comm_word=MPI_COMM_WORLD)
Helper function for creating a MooseApp from command-line arguments.
Protected Attributes
AppFactoryBuildInfoMap _name_to_build_info
Private Member Functions
AppFactory ()
Detailed Description
Generic AppFactory class for building Application objects.
Definition at line 55 of file AppFactory.h.
Constructor & Destructor Documentation
~AppFactory()
AppFactory::~AppFactory () virtual
Definition at line 26 of file AppFactory.C.
{}
AppFactory() [1/3]
AppFactory::AppFactory (AppFactory const &) delete
Don't allow creation through copy/move construction or assignment.
AppFactory() [2/3]
AppFactory::AppFactory (AppFactory &&) delete
AppFactory() [3/3]
AppFactory::AppFactory () inline private
Definition at line 137 of file AppFactory.h.
{}
Referenced by instance().
Member Function Documentation
createAppShared()
MooseAppPtr AppFactory::createAppShared (const std::string & default_app_type, int argc, char ** argv, MPI_Comm comm_word = MPI_COMM_WORLD) static
Helper function for creating a MooseApp from command-line arguments.
Definition at line 38 of file AppFactory.C.
{
  auto command_line = std::make_shared<CommandLine>(argc, argv);
  auto which_app_param = emptyInputParameters();
  MooseApp::addAppParam(which_app_param);
  command_line->addCommandLineOptionsFromParams(which_app_param);
  std::string app_type;
  if (!command_line->search("app_to_run", app_type))
    app_type = default_app_type;
  auto app_params = AppFactory::instance().getValidParams(app_type);
  app_params.set<int>("_argc") = argc;
  app_params.set<char **>("_argv") = argv;
  app_params.set<std::shared_ptr<CommandLine>>("_command_line") = command_line;
  return AppFactory::instance().createShared(app_type, "main", app_params, comm_world_in);
}
Referenced by main().
createdAppCount()
std::size_t AppFactory::createdAppCount (const std::string & app_type) const
Returns
the amount of times the AppFactory created the named App-type
Definition at line 97 of file AppFactory.C.
{
  // Error if the application type is not located
  const auto it = _name_to_build_info.find(app_type);
  if (it == _name_to_build_info.end())
    mooseError("AppFactory::createdAppCount(): '", app_type, "' is not a registered app");
  return it->second->_app_creation_count;
}
createShared()
MooseAppPtr AppFactory::createShared (const std::string & app_type, const std::string & name, InputParameters parameters, MPI_Comm COMM_WORLD_IN)
Build an application object (must be registered)
Parameters
app_type Type of the application being constructed
name Name for the object
parameters Parameters this object should have
Returns
The created object
Definition at line 61 of file AppFactory.C.
{
  // Error if the application type is not located
  const auto it = _name_to_build_info.find(app_type);
  if (it == _name_to_build_info.end())
    mooseError("Object '" + app_type + "' was not registered.");
  auto & build_info = it->second;
  // Take the app_type and add it to the parameters so that it can be retrieved in the Application
  parameters.set<std::string>("_type") = app_type;
  // Check to make sure that all required parameters are supplied
  parameters.checkParams("");
  auto comm = std::make_shared<Parallel::Communicator>(comm_world_in);
  parameters.set<std::shared_ptr<Parallel::Communicator>>("_comm") = comm;
  parameters.set<std::string>("_app_name") = name;
  if (!parameters.isParamValid("_command_line"))
    mooseError("Valid CommandLine object required");
  std::shared_ptr<CommandLine> command_line =
      parameters.get<std::shared_ptr<CommandLine>>("_command_line");
  command_line->addCommandLineOptionsFromParams(parameters);
  command_line->populateInputParams(parameters);
  build_info->_app_creation_count++;
  return build_info->build(parameters);
}
Referenced by MultiApp::createApp(), createAppShared(), and MooseServer::parseDocumentForDiagnostics().
getValidParams()
InputParameters AppFactory::getValidParams (const std::string & name)
Get valid parameters for the object.
Parameters
name Name of the object whose parameter we are requesting
Returns
Parameters of the object
Definition at line 29 of file AppFactory.C.
{
  if (const auto it = _name_to_build_info.find(name); it != _name_to_build_info.end())
    return it->second->buildParameters();
  mooseError(std::string("A '") + name + "' is not a registered object\n\n");
}
Referenced by MultiApp::createApp(), and createAppShared().
instance()
AppFactory & AppFactory::instance () static
Get the instance of the AppFactory.
Returns
Pointer to the AppFactory instance
Definition at line 16 of file AppFactory.C.
{
  // We need a naked new here (_not_ a smart pointer or object instance) due to what seems like a
  // bug in clang's static object destruction when using dynamic library loading.
  static AppFactory * instance = nullptr;
  if (!instance)
    instance = new AppFactory;
  return *instance;
}
Referenced by JsonSyntaxTree::addGlobal(), MultiApp::createApp(), MultiApp::createApps(), createAppShared(), MooseApp::dynamicAppRegistration(), instance(), MooseServer::parseDocumentForDiagnostics(), and MultiApp::validParams().
isRegistered()
bool AppFactory::isRegistered (const std::string & app_name) const inline
Returns a Boolean indicating whether an application type has been registered.
Definition at line 108 of file AppFactory.h.
  {
    return _name_to_build_info.count(app_name);
  }
Referenced by reg().
operator=() [1/2]
Registry & AppFactory::operator= (AppFactory &&) delete
operator=() [2/2]
Registry & AppFactory::operator= (AppFactory const &) delete
reg()
template<typename T > void AppFactory::reg (const std::string & name)
Register a new object.
Parameters
name Name of the object to register
Definition at line 142 of file AppFactory.h.
{
  if (isRegistered(name))
    return;
  _name_to_build_info[name] = std::make_unique<AppFactoryBuildInfo<T>>();
}
registeredObjectBuildInfos()
const AppFactoryBuildInfoMap & AppFactory::registeredObjectBuildInfos () const inline
Returns the map of object name to a function pointer for building said object's input parameters.
Definition at line 122 of file AppFactory.h.
{ return _name_to_build_info; }
registeredObjects()
const auto & AppFactory::registeredObjects () const inline
Returns a reference to the map from names to AppFactoryBuildInfo pointers.
Definition at line 103 of file AppFactory.h.
{ return _name_to_build_info; }
Referenced by MultiApp::validParams().
Member Data Documentation
_name_to_build_info
AppFactoryBuildInfoMap AppFactory::_name_to_build_info protected
Definition at line 133 of file AppFactory.h.
Referenced by createdAppCount(), createShared(), getValidParams(), isRegistered(), reg(), registeredObjectBuildInfos(), and registeredObjects().
The documentation for this class was generated from the following files:
moose/framework/include/base/AppFactory.h
moose/framework/src/base/AppFactory.C