Zapdos: FVFaceResidualObject Class Reference
FVFaceResidualObject Class Reference abstract
Interface class for a finite volume residual object whose residuals are based on faces.
#include <FVFaceResidualObject.h>
Public Member Functions
virtual void computeResidual (const FaceInfo &fi)=0
Compute the residual on the supplied face.
virtual void computeJacobian (const FaceInfo &fi)=0
Compute the jacobian on the supplied face.
virtual void computeResidualAndJacobian (const FaceInfo &fi)=0
Compute the residual and Jacobian on the supplied face.
Detailed Description
Interface class for a finite volume residual object whose residuals are based on faces.
Definition at line 17 of file FVFaceResidualObject.h.
Member Function Documentation
computeJacobian()
virtual void FVFaceResidualObject::computeJacobian (const FaceInfo & fi) pure virtual
Compute the jacobian on the supplied face.
Implemented in FVFluxBC, FVInterfaceKernel, FVFluxKernel, FVBoundaryScalarLagrangeMultiplierConstraint, and FVScalarLagrangeMultiplierInterface.
Referenced by ComputeFVFluxJacobianThread< RangeType >::compute().
computeResidual()
virtual void FVFaceResidualObject::computeResidual (const FaceInfo & fi) pure virtual
Compute the residual on the supplied face.
Implemented in FVFluxBC, FVInterfaceKernel, FVFluxKernel, FVBoundaryScalarLagrangeMultiplierConstraint, and FVScalarLagrangeMultiplierInterface.
Referenced by ComputeFVFluxResidualThread< RangeType >::compute().
computeResidualAndJacobian()
virtual void FVFaceResidualObject::computeResidualAndJacobian (const FaceInfo & fi) pure virtual
Compute the residual and Jacobian on the supplied face.
Implemented in FVFluxBC, FVInterfaceKernel, and FVFluxKernel.
Referenced by ComputeFVFluxRJThread< RangeType >::compute().
The documentation for this class was generated from the following file:
moose/framework/include/fvkernels/FVFaceResidualObject.h