Zapdos: SplineInterpolationBase Class Reference
SplineInterpolationBase Class Reference
#include <SplineInterpolationBase.h>
Public Member Functions
SplineInterpolationBase ()
virtual ~SplineInterpolationBase ()=default
Real sample (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, Real x_int) const
ADReal sample (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, const ADReal &x_int) const
Real sampleDerivative (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, Real x_int) const
Real sample2ndDerivative (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, Real x_int) const
Protected Member Functions
void spline (const std::vector< Real > &x, const std::vector< Real > &y, std::vector< Real > &y2, Real yp1=_deriv_bound, Real ypn=_deriv_bound)
This function calculates the second derivatives based on supplied x and y-vectors.
void findInterval (const std::vector< Real > &x, Real x_int, unsigned int &klo, unsigned int &khi) const
template<typename T >
void computeCoeffs (const std::vector< Real > &x, unsigned int klo, unsigned int khi, const T &x_int, Real &h, T &a, T &b) const
template<typename T >
T sample (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, const T &x_int, unsigned int klo, unsigned int khi) const
Sample value at point x_int given the indices of the vector of dependent values that bound the point.
Static Protected Attributes
static const Real _deriv_bound = std::numeric_limits<Real>::max()
Detailed Description
Definition at line 15 of file SplineInterpolationBase.h.
Constructor & Destructor Documentation
SplineInterpolationBase()
SplineInterpolationBase::SplineInterpolationBase ()
Definition at line 16 of file SplineInterpolationBase.C.
{}
~SplineInterpolationBase()
virtual SplineInterpolationBase::~SplineInterpolationBase () virtual default
Member Function Documentation
computeCoeffs()
template<typename T > void SplineInterpolationBase::computeCoeffs (const std::vector< Real > & x, unsigned int klo, unsigned int khi, const T & x_int, Real & h, T & a, T & b) const protected
Definition at line 85 of file SplineInterpolationBase.C.
{
  h = x[khi] - x[klo];
  if (h == 0)
    mooseError("The values of x must be distinct");
  a = (x[khi] - x_int) / h;
  b = (x_int - x[klo]) / h;
}
Referenced by sample(), sample2ndDerivative(), and sampleDerivative().
findInterval()
void SplineInterpolationBase::findInterval (const std::vector< Real > & x, Real x_int, unsigned int & klo, unsigned int & khi) const protected
Definition at line 65 of file SplineInterpolationBase.C.
{
  klo = 0;
  mooseAssert(x.size() >= 2, "You must have at least two knots to create a spline.");
  khi = x.size() - 1;
  while (khi - klo > 1)
  {
    unsigned int k = (khi + klo) >> 1;
    if (x[k] > x_int)
      khi = k;
    else
      klo = k;
  }
}
Referenced by BicubicSplineInterpolation::constructColumnSpline(), BicubicSplineInterpolation::constructRowSpline(), sample(), sample2ndDerivative(), and sampleDerivative().
sample() [1/3]
ADReal SplineInterpolationBase::sample (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, const ADReal & x_int) const
Definition at line 113 of file SplineInterpolationBase.C.
{
  unsigned int klo, khi;
  findInterval(x, MetaPhysicL::raw_value(x_int), klo, khi);
  return sample(x, y, y2, x_int, klo, khi);
}
sample() [2/3]
template<typename T > T SplineInterpolationBase::sample (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, const T & x_int, unsigned int klo, unsigned int khi) const protected
Sample value at point x_int given the indices of the vector of dependent values that bound the point.
This method is useful in bicubic spline interpolation, where several spline evaluations are needed to sample from a 2D point.
Definition at line 157 of file SplineInterpolationBase.C.
{
  Real h;
  T a, b;
  computeCoeffs(x, klo, khi, x_int, h, a, b);
  return a * y[klo] + b * y[khi] +
         ((a * a * a - a) * y2[klo] + (b * b * b - b) * y2[khi]) * (h * h) / 6.0;
}
sample() [3/3]
Real SplineInterpolationBase::sample (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, Real x_int) const
Definition at line 101 of file SplineInterpolationBase.C.
{
  unsigned int klo, khi;
  findInterval(x, x_int, klo, khi);
  return sample(x, y, y2, x_int, klo, khi);
}
Referenced by BicubicSplineInterpolation::constructColumnSpline(), BicubicSplineInterpolation::constructRowSpline(), sample(), SplineInterpolation::sample(), BicubicSplineInterpolation::sample(), and BicubicSplineInterpolation::sampleValueAndDerivatives().
sample2ndDerivative()
Real SplineInterpolationBase::sample2ndDerivative (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, Real x_int) const
Definition at line 141 of file SplineInterpolationBase.C.
{
  unsigned int klo, khi;
  findInterval(x, x_int, klo, khi);
  Real h, a, b;
  computeCoeffs(x, klo, khi, x_int, h, a, b);
  return a * y2[klo] + b * y2[khi];
}
Referenced by SplineInterpolation::sample2ndDerivative(), and BicubicSplineInterpolation::sample2ndDerivative().
sampleDerivative()
Real SplineInterpolationBase::sampleDerivative (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, Real x_int) const
Definition at line 125 of file SplineInterpolationBase.C.
{
  unsigned int klo, khi;
  findInterval(x, x_int, klo, khi);
  Real h, a, b;
  computeCoeffs(x, klo, khi, x_int, h, a, b);
  return (y[khi] - y[klo]) / h -
         (((3.0 * a * a - 1.0) * y2[klo] + (3.0 * b * b - 1.0) * -y2[khi]) * h / 6.0);
}
Referenced by SplineInterpolation::sampleDerivative(), BicubicSplineInterpolation::sampleDerivative(), and BicubicSplineInterpolation::sampleValueAndDerivatives().
spline()
void SplineInterpolationBase::spline (const std::vector< Real > & x, const std::vector< Real > & y, std::vector< Real > & y2, Real yp1 = _deriv_bound, Real ypn = _deriv_bound) protected
This function calculates the second derivatives based on supplied x and y-vectors.
Definition at line 19 of file SplineInterpolationBase.C.
{
  auto n = x.size();
  if (n < 2)
    mooseError("You must have at least two knots to create a spline.");
  std::vector<Real> u(n, 0.);
  y2.assign(n, 0.);
  if (yp1 >= 1e30)
    y2[0] = u[0] = 0.;
  else
  {
    y2[0] = -0.5;
    u[0] = (3.0 / (x[1] - x[0])) * ((y[1] - y[0]) / (x[1] - x[0]) - yp1);
  }
  // decomposition of tri-diagonal algorithm (y2 and u are used for temporary storage)
  for (decltype(n) i = 1; i < n - 1; i++)
  {
    Real sig = (x[i] - x[i - 1]) / (x[i + 1] - x[i - 1]);
    Real p = sig * y2[i - 1] + 2.0;
    y2[i] = (sig - 1.0) / p;
    u[i] = (y[i + 1] - y[i]) / (x[i + 1] - x[i]) - (y[i] - y[i - 1]) / (x[i] - x[i - 1]);
    u[i] = (6.0 * u[i] / (x[i + 1] - x[i - 1]) - sig * u[i - 1]) / p;
  }
  Real qn, un;
  if (ypn >= 1e30)
    qn = un = 0.;
  else
  {
    qn = 0.5;
    un = (3.0 / (x[n - 1] - x[n - 2])) * (ypn - (y[n - 1] - y[n - 2]) / (x[n - 1] - x[n - 2]));
  }
  y2[n - 1] = (un - qn * u[n - 2]) / (qn * y2[n - 2] + 1.);
  // back substitution
  for (auto k = n - 1; k >= 1; k--)
    y2[k - 1] = y2[k - 1] * y2[k] + u[k - 1];
}
Referenced by BicubicSplineInterpolation::constructColumnSpline(), BicubicSplineInterpolation::constructColumnSplineSecondDerivativeTable(), BicubicSplineInterpolation::constructRowSpline(), BicubicSplineInterpolation::constructRowSplineSecondDerivativeTable(), and SplineInterpolation::solve().
Member Data Documentation
_deriv_bound
const Real SplineInterpolationBase::_deriv_bound = std::numeric_limits<Real>::max() static protected
Definition at line 79 of file SplineInterpolationBase.h.
Referenced by BicubicSplineInterpolation::errorCheck().
The documentation for this class was generated from the following files:
moose/framework/include/utils/SplineInterpolationBase.h
moose/framework/src/utils/SplineInterpolationBase.C