Zapdos: StringInputStream Class Reference
StringInputStream Class Reference
Helper class that hands out input streams to a stringstream.
#include <StringInputStream.h>
Public Member Functions
StringInputStream (std::unique_ptr< std::stringstream > stream)
virtual std::shared_ptr< std::istream > get () const override final
Gets an input stream to the underlying stream.
std::unique_ptr< std::stringstream > release ()
Releases the owned stringstream.
bool inUse () const
Whether or not anything is still using this stream.
virtual std::optional< std::filesystem::path > getFilename () const
Gets the underlying filename, if any.
Protected Member Functions
void addSharedStream (const std::weak_ptr< std::istream > stream) const
Internal method to be called by derived classes to add a shared stream to _shared_streams (so that it can be tracked).
Private Attributes
std::unique_ptr< std::stringstream > _stream
The underlying stringstream.
std::vector< std::weak_ptr< std::istream > > _shared_streams
The streams that have been handed out by get()
Detailed Description
Helper class that hands out input streams to a stringstream.
Definition at line 19 of file StringInputStream.h.
Constructor & Destructor Documentation
StringInputStream()
StringInputStream::StringInputStream (std::unique_ptr< std::stringstream > stream)
Definition at line 14 of file StringInputStream.C.
  : InputStream(), _stream(std::move(stream))
{
}
Member Function Documentation
addSharedStream()
void InputStream::addSharedStream (const std::weak_ptr< std::istream > stream) const protected inherited
Internal method to be called by derived classes to add a shared stream to _shared_streams (so that it can be tracked).
Should be called in the overridden get() by derived classes.
Definition at line 21 of file InputStream.C.
{
  mooseAssert(!stream.expired(), "Stream is expired");
  for (auto & entry : _shared_streams)
    if (entry.expired())
    {
      entry = stream;
      return;
    }
  _shared_streams.push_back(stream);
}
Referenced by FileInputStream::get(), and get().
get()
std::shared_ptr< std::istream > StringInputStream::get () const final override virtual
Gets an input stream to the underlying stream.
This is returned as a shared_ptr so that this class can tell whether or not another object is still using the stream.
Implements InputStream.
Definition at line 20 of file StringInputStream.C.
{
  mooseAssert(_stream, "Not valid");
  std::shared_ptr<std::istream> stream = std::make_unique<std::istream>(_stream->rdbuf());
  addSharedStream(stream);
  return stream;
}
getFilename()
std::optional< std::filesystem::path > InputStream::getFilename () const virtual inherited
Gets the underlying filename, if any.
Reimplemented in FileInputStream.
Definition at line 44 of file InputStream.C.
{
  return {};
}
Referenced by RestartableDataReader::deserializeValue(), and RestartableDataReader::readHeader().
inUse()
bool InputStream::inUse () const inherited
Whether or not anything is still using this stream.
This is checked by seeing whether or not the use count of any of the streams handed out by get() is > 1 (with the only use count being the one stored in _shared_streams)
Definition at line 35 of file InputStream.C.
{
  for (auto & stream : _shared_streams)
    if (!stream.expired())
      return true;
  return false;
}
Referenced by release(), and InputStream::~InputStream().
release()
std::unique_ptr< std::stringstream > StringInputStream::release ()
Releases the owned stringstream.
Will error if an object still has access to a stream obtained via get().
Leaves the owned stream in an undefined state.
Definition at line 30 of file StringInputStream.C.
{
  if (inUse())
    mooseError("StringInputStream::release(): Cannot release; still in use");
  return std::move(_stream);
}
Member Data Documentation
_shared_streams
std::vector<std::weak_ptr<std::istream> > InputStream::_shared_streams mutable private inherited
The streams that have been handed out by get()
Definition at line 60 of file InputStream.h.
Referenced by InputStream::addSharedStream(), and InputStream::inUse().
_stream
std::unique_ptr<std::stringstream> StringInputStream::_stream private
The underlying stringstream.
Definition at line 37 of file StringInputStream.h.
Referenced by get(), and release().
The documentation for this class was generated from the following files:
moose/framework/include/restart/StringInputStream.h
moose/framework/src/restart/StringInputStream.C