Zapdos: MooseRandom Class Reference
MooseRandom Class Reference
This class encapsulates a useful, consistent, cross-platform random number generator with multiple utilities.
#include <MooseRandom.h>
Public Member Functions
void seed (std::size_t i, unsigned int seed)
The method seeds one of the independent random number generators.
Real rand (std::size_t i)
This method returns the next random number (Real format) from the specified generator.
Real randNormal (std::size_t i, Real mean, Real sigma)
This method returns the next random number (Real format) from the specified generator, drawn from a normal distribution centered around mean, with a width of sigma.
Real randNormal (std::size_t i)
Return next random number drawn from a standard distribution.
uint32_t randl (std::size_t i)
This method returns the next random number (long format) from the specified generator.
uint32_t randl (std::size_t i, uint32_t lower, uint32_t upper)
This method returns the next random number (long format) from the specified generator within the supplied range.
void saveState ()
This method saves the current state of all generators which can be restored at a later time (i.e.
void restoreState ()
This method restores the last saved generator state.
std::size_t size ()
Return the number of states.
Static Public Member Functions
static void seed (unsigned int seed)
The method seeds the random number generator.
static Real rand ()
This method returns the next random number (Real format) from the generator.
static Real randNormal (Real mean, Real sigma)
This method returns the next random number (Real format) from the generator, drawn from a normal distribution centered around mean, with a width of sigma.
static Real randNormal ()
Return next random number drawn from a standard distribution.
static uint32_t randl ()
This method returns the next random number (long format) from the generator.
Private Attributes
std::unordered_map< std::size_t, std::pair< mt_state, mt_state > > _states
We store a pair of states in this map.
bool _saved = false
Flag to make certain that saveState is called prior to restoreState.
Friends
void dataStore (std::ostream &stream, MooseRandom &v, void *context)
void dataLoad (std::istream &stream, MooseRandom &v, void *context)
Detailed Description
This class encapsulates a useful, consistent, cross-platform random number generator with multiple utilities.
SIMPLE INTERFACE: There are three static functions that are suitable as a drop in replacement for the random number capabilities available in the standard C++ library.
ADVANCED INTERFACE: When creating an instance of this class, one can maintain an arbitrary number of multiple independent streams of random numbers. Furthermore, the state of these generators can be saved and restored for all streams by using the "saveState" and "restoreState" methods. Finally, this class uses a fast hash map so that indexes for the generators are not required to be contiguous.
Definition at line 36 of file MooseRandom.h.
Member Function Documentation
rand() [1/2]
static Real MooseRandom::rand () inline static
This method returns the next random number (Real format) from the generator.
Returns
the next random number in the range [0,1) with 64-bit precision
Definition at line 49 of file MooseRandom.h.
{ return mt_ldrand(); }
Referenced by RandomPartitioner::_do_partition(), RandomICBase::generateRandom(), RankTwoTensorTempl< T >::genRandomSymmTensor(), SymmetricRankTwoTensorTempl< T >::genRandomSymmTensor(), RankTwoTensorTempl< T >::genRandomTensor(), Sampler::getRand(), RandomInterface::getRandomReal(), and PropertyReadFile::initVoronoiCenterPoints().
rand() [2/2]
Real MooseRandom::rand (std::size_t i) inline
This method returns the next random number (Real format) from the specified generator.
Parameters
i the index of the generator
Returns
the next random number in the range [0,1) with 64-bit precision
Definition at line 84 of file MooseRandom.h.
  {
    // mooseAssert(_states.find(i) != _states.end(), "No random state initialized for id: " << i);
    return mts_ldrand(&(_states[i].first));
  }
randl() [1/3]
static uint32_t MooseRandom::randl () inline static
This method returns the next random number (long format) from the generator.
Returns
the next random number in the range [0,max(uinit32_t)) with 32-bit number
Definition at line 70 of file MooseRandom.h.
{ return mt_lrand(); }
Referenced by Sampler::getRandl(), RandomInterface::getRandomLong(), Sampler::init(), RandomICBase::RandomICBase(), MooseUtils::resample(), MooseUtils::resampleWithFunctor(), MooseUtils::shuffle(), and RandomData::updateGenerators().
randl() [2/3]
uint32_t MooseRandom::randl (std::size_t i) inline
This method returns the next random number (long format) from the specified generator.
Parameters
i the index of the generator
Returns
the next random number in the range [0,max(uinit32_t)) with 32-bit number
Definition at line 115 of file MooseRandom.h.
  {
    mooseAssert(_states.find(i) != _states.end(), "No random state initialized for id: " << i);
    return mts_lrand(&(_states[i].first));
  }
randl() [3/3]
uint32_t MooseRandom::randl (std::size_t i, uint32_t lower, uint32_t upper) inline
This method returns the next random number (long format) from the specified generator within the supplied range.
Parameters
lower lower bounds of value
upper upper bounds of value
i the index of the generator
Returns
the next random number in the range [0,max(uinit32_t)) with 32-bit number
Definition at line 130 of file MooseRandom.h.
  {
    mooseAssert(_states.find(i) != _states.end(), "No random state initialized for id: " << i);
    return rds_iuniform(&(_states[i].first), lower, upper);
  }
randNormal() [1/4]
static Real MooseRandom::randNormal () inline static
Return next random number drawn from a standard distribution.
Definition at line 64 of file MooseRandom.h.
{ return randNormal(0.0, 1.0); }
Referenced by randNormal().
randNormal() [2/4]
static Real MooseRandom::randNormal (Real mean, Real sigma) inline static
This method returns the next random number (Real format) from the generator, drawn from a normal distribution centered around mean, with a width of sigma.
Parameters
mean center of the random number distribution
sigma width of the random number distribution
Returns
the next random number following a normal distribution of width sigma around mean with 64-bit precision
Definition at line 59 of file MooseRandom.h.
{ return rd_normal(mean, sigma); }
randNormal() [3/4]
Real MooseRandom::randNormal (std::size_t i) inline
Return next random number drawn from a standard distribution.
Definition at line 108 of file MooseRandom.h.
{ return randNormal(i, 0.0, 1.0); }
Referenced by randNormal().
randNormal() [4/4]
Real MooseRandom::randNormal (std::size_t i, Real mean, Real sigma) inline
This method returns the next random number (Real format) from the specified generator, drawn from a normal distribution centered around mean, with a width of sigma.
Parameters
i the index of the generator
mean center of the random number distribution
sigma width of the random number distribution
Returns
the next random number following a normal distribution of width sigma around mean with 64-bit precision
Definition at line 99 of file MooseRandom.h.
  {
    mooseAssert(_states.find(i) != _states.end(), "No random state initialized for id: " << i);
    return rds_normal(&(_states[i].first), mean, sigma);
  }
restoreState()
void MooseRandom::restoreState () inline
This method restores the last saved generator state.
Definition at line 152 of file MooseRandom.h.
  {
    mooseAssert(_saved, "saveState() must be called prior to restoreState().");
    std::for_each(_states.begin(),
                  _states.end(),
                  [](std::pair<const std::size_t, std::pair<mt_state, mt_state>> & pair)
                  { pair.second.first = pair.second.second; });
  }
Referenced by Sampler::restoreGeneratorState(), and RandomData::updateSeeds().
saveState()
void MooseRandom::saveState () inline
This method saves the current state of all generators which can be restored at a later time (i.e.
re-generate the same sequence of random numbers of this generator
Definition at line 140 of file MooseRandom.h.
  {
    _saved = true;
    std::for_each(_states.begin(),
                  _states.end(),
                  [](std::pair<const std::size_t, std::pair<mt_state, mt_state>> & pair)
                  { pair.second.second = pair.second.first; });
  }
Referenced by Sampler::saveGeneratorState(), and RandomData::updateSeeds().
seed() [1/2]
void MooseRandom::seed (std::size_t i, unsigned int seed) inline
The method seeds one of the independent random number generators.
Parameters
i the index of the generator
seed the seed number
Definition at line 77 of file MooseRandom.h.
{ mts_seed32new(&(_states[i].first), seed); }
seed() [2/2]
static void MooseRandom::seed (unsigned int seed) inline static
The method seeds the random number generator.
Parameters
seed the seed number
Definition at line 43 of file MooseRandom.h.
{ mt_seed32new(seed); }
Referenced by Sampler::init(), RankTwoTensorTempl< T >::initRandom(), SymmetricRankTwoTensorTempl< T >::initRandom(), PropertyReadFile::initVoronoiCenterPoints(), MooseInit::MooseInit(), RandomICBase::RandomICBase(), RandomPartitioner::RandomPartitioner(), seed(), and RandomData::updateGenerators().
size()
std::size_t MooseRandom::size () inline
Return the number of states.
Definition at line 164 of file MooseRandom.h.
{ return _states.size(); }
Referenced by Sampler::advanceGenerators(), Sampler::getRand(), and Sampler::getRandl().
Friends And Related Function Documentation
dataLoad
void dataLoad (std::istream & stream, MooseRandom & v, void * context) friend
Definition at line 190 of file MooseRandom.h.
{
  loadHelper(stream, v._states, context);
}
dataStore
void dataStore (std::ostream & stream, MooseRandom & v, void * context) friend
Definition at line 184 of file MooseRandom.h.
{
  storeHelper(stream, v._states, context);
}
Member Data Documentation
_saved
bool MooseRandom::_saved = false private
Flag to make certain that saveState is called prior to restoreState.
Definition at line 179 of file MooseRandom.h.
Referenced by restoreState(), and saveState().
_states
std::unordered_map<std::size_t, std::pair<mt_state, mt_state> > MooseRandom::_states private
We store a pair of states in this map.
The first one is the active state, the second is the backup state. It is used to restore state at a later time to the active state.
Definition at line 172 of file MooseRandom.h.
Referenced by rand(), randl(), randNormal(), restoreState(), saveState(), seed(), and size().
The documentation for this class was generated from the following file:
moose/framework/include/utils/MooseRandom.h