Zapdos: FunctionParserUtils< is_ad > Class Template Reference
FunctionParserUtils< is_ad > Class Template Reference
#include <FunctionParserUtils.h>
Public Types
typedef GenericSymFunction< is_ad > SymFunction
Shorthand for an autodiff function parser object.
typedef std::shared_ptr< SymFunction > SymFunctionPtr
Shorthand for an smart pointer to an autodiff function parser object.
Public Member Functions
FunctionParserUtils (const InputParameters &parameters)
void setParserFeatureFlags (SymFunctionPtr &)
apply input paramters to internal feature flags of the parser object
Static Public Member Functions
static InputParameters validParams ()
Protected Types
enum class FailureMethod { nan , nan_warning , error , exception }
Enum for failure method.
Protected Member Functions
GenericReal< is_ad > evaluate (SymFunctionPtr &, const std::string &object_name="")
Evaluate FParser object and check EvalError.
void addFParserConstants (SymFunctionPtr &parser, const std::vector< std::string > &constant_names, const std::vector< std::string > &constant_expressions)
add constants (which can be complex expressions) to the parser object
virtual void functionsOptimize (SymFunctionPtr &parsed_function)
void functionsOptimize (SymFunctionPtr &parsed_function)
void functionsOptimize (SymFunctionPtr &parsed_function)
Protected Attributes
bool _enable_jit
bool _enable_ad_cache
bool _disable_fpoptimizer
bool _enable_auto_optimize
enum FunctionParserUtils::FailureMethod _evalerror_behavior
const Real _quiet_nan
appropriate not a number value to return
std::vector< GenericReal< is_ad > > _func_params
Array to stage the parameters passed to the functions when calling Eval.
Static Protected Attributes
static const char * _eval_error_msg []
table of FParser eval error codes
Detailed Description
template<bool is_ad = false>
class FunctionParserUtils< is_ad >
Definition at line 54 of file FunctionParserUtils.h.
Member Typedef Documentation
SymFunction
template<bool is_ad = false> typedef GenericSymFunction<is_ad> FunctionParserUtils< is_ad >::SymFunction
Shorthand for an autodiff function parser object.
Definition at line 62 of file FunctionParserUtils.h.
SymFunctionPtr
template<bool is_ad = false> typedef std::shared_ptr<SymFunction> FunctionParserUtils< is_ad >::SymFunctionPtr
Shorthand for an smart pointer to an autodiff function parser object.
Definition at line 65 of file FunctionParserUtils.h.
Member Enumeration Documentation
FailureMethod
template<bool is_ad = false> enum class FunctionParserUtils::FailureMethod strong protected
Enum for failure method.
Enumerator
nan
nan_warning
error
exception
Definition at line 90 of file FunctionParserUtils.h.
{ nan, nan_warning, error, exception } _evalerror_behavior;
Constructor & Destructor Documentation
FunctionParserUtils()
template<bool is_ad = false> FunctionParserUtils< is_ad >::FunctionParserUtils (const InputParameters & parameters)
Member Function Documentation
addFParserConstants()
template<bool is_ad = false> void FunctionParserUtils< is_ad >::addFParserConstants (SymFunctionPtr & parser, const std::vector< std::string > & constant_names, const std::vector< std::string > & constant_expressions) protected
add constants (which can be complex expressions) to the parser object
evaluate()
template<bool is_ad = false> GenericReal< is_ad > FunctionParserUtils< is_ad >::evaluate (SymFunctionPtr & , const std::string & object_name = "") protected
Evaluate FParser object and check EvalError.
functionsOptimize() [1/3]
template<bool is_ad = false> virtual void FunctionParserUtils< is_ad >::functionsOptimize (SymFunctionPtr & parsed_function) protected virtual
functionsOptimize() [2/3]
void FunctionParserUtils< true >::functionsOptimize (SymFunctionPtr & parsed_function) protected
functionsOptimize() [3/3]
void FunctionParserUtils< true >::functionsOptimize (SymFunctionPtr & parsed_function) protected
Definition at line 184 of file FunctionParserUtils.C.
{
  // base function
  if (!_disable_fpoptimizer)
    parsed_function->Optimize();
  if (!_enable_jit || !parsed_function->JITCompile())
    mooseError("AD parsed objects require JIT compilation to be enabled and working.");
}
setParserFeatureFlags()
template<bool is_ad = false> void FunctionParserUtils< is_ad >::setParserFeatureFlags (SymFunctionPtr &)
apply input paramters to internal feature flags of the parser object
validParams()
template<bool is_ad = false> static InputParameters FunctionParserUtils< is_ad >::validParams () static
Referenced by ParsedAuxScalar::validParams(), ParsedScalarRateCoefficient::validParams(), ArrayParsedAux::validParams(), ParsedAux::validParams(), ParsedVectorAux::validParams(), ParsedFunctorMaterialTempl< is_ad >::validParams(), ParsedMaterialHelper< is_ad >::validParams(), ParsedCurveGenerator::validParams(), ParsedElementDeletionGenerator::validParams(), ParsedGenerateSideset::validParams(), ParsedNodeTransformGenerator::validParams(), ParsedSubdomainMeshGenerator::validParams(), TransfiniteMeshGenerator::validParams(), ParsedPostprocessor::validParams(), and ParsedODEKernel::validParams().
Member Data Documentation
_disable_fpoptimizer
template<bool is_ad = false> bool FunctionParserUtils< is_ad >::_disable_fpoptimizer protected
Definition at line 85 of file FunctionParserUtils.h.
_enable_ad_cache
template<bool is_ad = false> bool FunctionParserUtils< is_ad >::_enable_ad_cache protected
Definition at line 84 of file FunctionParserUtils.h.
_enable_auto_optimize
template<bool is_ad = false> bool FunctionParserUtils< is_ad >::_enable_auto_optimize protected
Definition at line 86 of file FunctionParserUtils.h.
_enable_jit
template<bool is_ad = false> bool FunctionParserUtils< is_ad >::_enable_jit protected
Definition at line 83 of file FunctionParserUtils.h.
_eval_error_msg
template<bool is_ad = false> const char* FunctionParserUtils< is_ad >::_eval_error_msg[] static protected
table of FParser eval error codes
Definition at line 96 of file FunctionParserUtils.h.
_evalerror_behavior
template<bool is_ad = false> enum FunctionParserUtils::FailureMethod FunctionParserUtils< is_ad >::_evalerror_behavior protected
_func_params
template<bool is_ad = false> std::vector<GenericReal<is_ad> > FunctionParserUtils< is_ad >::_func_params protected
Array to stage the parameters passed to the functions when calling Eval.
Definition at line 99 of file FunctionParserUtils.h.
_quiet_nan
template<bool is_ad = false> const Real FunctionParserUtils< is_ad >::_quiet_nan protected
appropriate not a number value to return
Definition at line 93 of file FunctionParserUtils.h.
The documentation for this class was generated from the following file:
moose/framework/include/utils/FunctionParserUtils.h