Zapdos: Registry Class Reference
Registry Class Reference
The registry is used as a global singleton to collect information on all available MooseObject and Action classes for use in a moose app/simulation.
#include <Registry.h>
Public Member Functions
Registry (Registry const &)=delete
Don't allow creation through copy/move construction or assignment.
Registry & operator= (Registry const &)=delete
Registry (Registry &&)=delete
Registry & operator= (Registry &&)=delete
Static Public Member Functions
static Registry & getRegistry ()
Get the global Registry singleton.
template<typename T >
static char add (const RegistryEntryData &base_info)
Adds information on a MooseObject to the registry.
template<typename T >
static char addAction (const RegistryEntryData &base_info)
Adds information on an Action object to the registry.
template<typename T >
static std::string getClassName ()
static void registerObjectsTo (Factory &f, const std::set< std::string > &labels)
This registers all MooseObjects known to the registry that have the given label(s) with the factory f.
static void registerActionsTo (ActionFactory &f, const std::set< std::string > &labels)
This registers all Actions known to the registry that have the given label(s) with the factory f.
static char addKnownLabel (const std::string &label)
addKnownLabel whitelists a label as valid for purposes of the checkLabels function.
static void addDataFilePath (const std::string &path)
register search paths for built-in data files
static const std::map< std::string, std::vector< std::shared_ptr< RegistryEntryBase > > > & allObjects ()
Returns a per-label keyed map of all MooseObjects in the registry.
static const std::map< std::string, std::vector< std::shared_ptr< RegistryEntryBase > > > & allActions ()
Returns a per-label keyed map of all Actions in the registry.
static const RegistryEntryBase & objData (const std::string &name)
static bool isRegisteredObj (const std::string &name)
static const std::vector< std::string > & getDataFilePaths ()
Returns a vector of all registered data file paths.
template<typename T >
static std::string getRegisteredName ()
returns the name() for a registered class
Private Member Functions
Registry ()
Private Attributes
std::map< std::string, std::shared_ptr< RegistryEntryBase > > _name_to_entry
std::map< std::string, std::vector< std::shared_ptr< RegistryEntryBase > > > _per_label_objects
std::map< std::string, std::vector< std::shared_ptr< RegistryEntryBase > > > _per_label_actions
std::set< std::string > _known_labels
std::vector< std::string > _data_file_paths
std::map< std::string, std::string > _type_to_classname
Detailed Description
The registry is used as a global singleton to collect information on all available MooseObject and Action classes for use in a moose app/simulation.
It must be global because we want+need to be able to register objects in global scope during static initialization time before other parts of the moose app execution have started running. This allows us to distribute registration across all the files that define the actual classes being registered so we don't have to have any central location with a bajillion includes that makes (especially incremental) compiles slow. The registry collects the app, name, and other information for each objects and makes it available to the moose object and action factories and others for general use. All public functions in this class modify and return data from the global singleton.
Definition at line 150 of file Registry.h.
Constructor & Destructor Documentation
Registry() [1/3]
Registry::Registry (Registry const &) delete
Don't allow creation through copy/move construction or assignment.
Registry() [2/3]
Registry::Registry (Registry &&) delete
Registry() [3/3]
Registry::Registry () inline private
Definition at line 242 of file Registry.h.
{};
Referenced by getRegistry().
Member Function Documentation
add()
template<typename T > static char Registry::add (const RegistryEntryData & base_info) inline static
Adds information on a MooseObject to the registry.
The _build_ptr, _build_action_ptr, and _params_ptr objects of the info object should all be nullptr - these are set automatically by the add function itself using the templated type T.
Definition at line 162 of file Registry.h.
  {
    const auto info = std::make_shared<RegistryEntry<T>>(base_info);
    getRegistry()._per_label_objects[info->_label].push_back(info);
    getRegistry()._type_to_classname[typeid(T).name()] = info->name();
    return 0;
  }
addAction()
template<typename T > static char Registry::addAction (const RegistryEntryData & base_info) inline static
Adds information on an Action object to the registry.
The _build_ptr, _build_action_ptr, and _params_ptr objects of the info object should all be nullptr - these are set automatically by the addAction function itself using the templated type T.
Definition at line 174 of file Registry.h.
  {
    const auto info = std::make_shared<RegistryEntry<T>>(base_info);
    getRegistry()._per_label_actions[info->_label].push_back(info);
    getRegistry()._type_to_classname[typeid(T).name()] = info->_classname;
    return 0;
  }
addDataFilePath()
void Registry::addDataFilePath (const std::string & path) static
register search paths for built-in data files
Definition at line 89 of file Registry.C.
{
  auto & dfp = getRegistry()._data_file_paths;
  // split the *App.C filename from its containing directory
  const auto path = MooseUtils::splitFileName(fullpath).first;
  // This works for both build/unity_src/ and src/base/ as the *App.C file location,
  // in case __FILE__ doesn't get overriden in unity build
  const auto data_dir = MooseUtils::pathjoin(path, "../../data");
  // if the data directory exists and hasn't been added before, add it
  if (MooseUtils::pathIsDirectory(data_dir) &&
      std::find(dfp.begin(), dfp.end(), data_dir) == dfp.end())
    dfp.push_back(data_dir);
}
addKnownLabel()
char Registry::addKnownLabel (const std::string & label) static
addKnownLabel whitelists a label as valid for purposes of the checkLabels function.
Definition at line 82 of file Registry.C.
{
  getRegistry()._known_labels.insert(label);
  return 0;
}
Referenced by MooseApp::MooseApp().
allActions()
static const std::map< std::string, std::vector< std::shared_ptr< RegistryEntryBase > > > & Registry::allActions () inline static
Returns a per-label keyed map of all Actions in the registry.
Definition at line 208 of file Registry.h.
  {
    return getRegistry()._per_label_actions;
  }
Referenced by JsonSyntaxTree::JsonSyntaxTree(), and MooseApp::setupOptions().
allObjects()
static const std::map< std::string, std::vector< std::shared_ptr< RegistryEntryBase > > > & Registry::allObjects () inline static
Returns a per-label keyed map of all MooseObjects in the registry.
Definition at line 203 of file Registry.h.
  {
    return getRegistry()._per_label_objects;
  }
Referenced by JsonSyntaxTree::JsonSyntaxTree(), and MooseApp::setupOptions().
getClassName()
template<typename T > static std::string Registry::getClassName () inline static
Definition at line 183 of file Registry.h.
  {
    return libmesh_map_find(getRegistry()._type_to_classname, typeid(T).name());
  }
getDataFilePaths()
static const std::vector< std::string > & Registry::getDataFilePaths () inline static
Returns a vector of all registered data file paths.
Definition at line 224 of file Registry.h.
  {
    return getRegistry()._data_file_paths;
  }
getRegisteredName()
template<typename T > std::string Registry::getRegisteredName static
returns the name() for a registered class
Definition at line 254 of file Registry.h.
{
  mooseDeprecated("Use Registry::getClassName() instead.");
  return getClassName<T>();
}
getRegistry()
Registry & Registry::getRegistry () static
Get the global Registry singleton.
Definition at line 21 of file Registry.C.
{
  // We need a naked new here (_not_ a smart pointer or object instance) due to what seems like a
  // bug in clang's static object destruction when using dynamic library loading.
  static Registry * registry_singleton = nullptr;
  if (!registry_singleton)
    registry_singleton = new Registry();
  return *registry_singleton;
}
Referenced by add(), addAction(), addDataFilePath(), addKnownLabel(), allActions(), allObjects(), getClassName(), DataFileInterface< Action >::getDataFileNameByName(), getDataFilePaths(), isRegisteredObj(), objData(), registerActionsTo(), and registerObjectsTo().
isRegisteredObj()
static bool Registry::isRegisteredObj (const std::string & name) inline static
Returns
true if an object with the given name is registered
Definition at line 218 of file Registry.h.
  {
    return getRegistry()._name_to_entry.count(name);
  }
objData()
const RegistryEntryBase & Registry::objData (const std::string & name) static
Definition at line 55 of file Registry.C.
{
  auto & r = getRegistry();
  if (const auto it = r._name_to_entry.find(name); it != r._name_to_entry.end())
    return *it->second;
  else
    mooseError("Object ", name, " is not registered yet");
}
operator=() [1/2]
Registry & Registry::operator= (Registry &&) delete
operator=() [2/2]
Registry & Registry::operator= (Registry const &) delete
registerActionsTo()
void Registry::registerActionsTo (ActionFactory & f, const std::set< std::string > & labels) static
This registers all Actions known to the registry that have the given label(s) with the factory f.
Definition at line 66 of file Registry.C.
{
  auto & r = getRegistry();
  for (const auto & label : labels)
  {
    r._known_labels.insert(label);
    if (r._per_label_actions.count(label) == 0)
      continue;
    for (const auto & obj : r._per_label_actions[label])
      f.reg(obj);
  }
}
Referenced by Moose::registerActions(), CraneApp::registerAll(), ZapdosApp::registerAll(), and SquirrelApp::registerAll().
registerObjectsTo()
void Registry::registerObjectsTo (Factory & f, const std::set< std::string > & labels) static
This registers all MooseObjects known to the registry that have the given label(s) with the factory f.
Definition at line 32 of file Registry.C.
{
  auto & r = getRegistry();
  for (const auto & label : labels)
  {
    r._known_labels.insert(label);
    if (r._per_label_objects.count(label) == 0)
      continue;
    for (const auto & obj : r._per_label_objects[label])
    {
      const auto name = obj->name();
      r._name_to_entry[name] = obj;
      f.reg(obj);
      if (!obj->_alias.empty())
        f.associateNameToClass(name, obj->_classname);
    }
  }
}
Referenced by CraneApp::registerAll(), ZapdosApp::registerAll(), SquirrelApp::registerAll(), and Moose::registerObjects().
Member Data Documentation
_data_file_paths
std::vector<std::string> Registry::_data_file_paths private
Definition at line 248 of file Registry.h.
Referenced by addDataFilePath(), and getDataFilePaths().
_known_labels
std::set<std::string> Registry::_known_labels private
Definition at line 247 of file Registry.h.
Referenced by addKnownLabel().
_name_to_entry
std::map<std::string, std::shared_ptr<RegistryEntryBase> > Registry::_name_to_entry private
Definition at line 244 of file Registry.h.
Referenced by isRegisteredObj().
_per_label_actions
std::map<std::string, std::vector<std::shared_ptr<RegistryEntryBase> > > Registry::_per_label_actions private
Definition at line 246 of file Registry.h.
Referenced by addAction(), and allActions().
_per_label_objects
std::map<std::string, std::vector<std::shared_ptr<RegistryEntryBase> > > Registry::_per_label_objects private
Definition at line 245 of file Registry.h.
Referenced by add(), and allObjects().
_type_to_classname
std::map<std::string, std::string> Registry::_type_to_classname private
Definition at line 249 of file Registry.h.
Referenced by add(), addAction(), and getClassName().
The documentation for this class was generated from the following files:
moose/framework/include/base/Registry.h
moose/framework/src/base/Registry.C