Zapdos: UserObjectInterface Class Reference
UserObjectInterface Class Reference
Interface for objects that need to use UserObjects.
#include <UserObjectInterface.h>
Public Member Functions
UserObjectInterface (const MooseObject *moose_object)
UserObjectName getUserObjectName (const std::string &param_name) const
template<class T >
const T & getUserObject (const std::string &param_name, bool is_dependency=true) const
Get an user object with a given parameter param_name.
template<class T >
const T & getUserObjectByName (const UserObjectName &object_name, bool is_dependency=true) const
Get an user object with the name object_name.
const UserObject & getUserObjectBase (const std::string &param_name, bool is_dependency=true) const
Get an user object with a given parameter param_name.
const UserObject & getUserObjectBaseByName (const UserObjectName &object_name, bool is_dependency=true) const
Get an user object with the name object_name.
bool hasUserObject (const std::string &param_name) const
template<class T >
bool hasUserObject (const std::string &param_name) const
bool hasUserObjectByName (const UserObjectName &object_name) const
template<class T >
bool hasUserObjectByName (const UserObjectName &object_name) const
Static Public Member Functions
static InputParameters validParams ()
Protected Member Functions
virtual void addUserObjectDependencyHelper (const UserObject &) const
Helper for deriving classes to override to add dependencies when a UserObject is requested.
Private Member Functions
template<class T >
const T & castUserObject (const UserObject &uo_base, const std::string &param_name="") const
Internal helper that casts the UserObject uo_base to the reqested type.
const std::string & userObjectType (const UserObject &uo) const
Gets a UserObject's type; avoids including UserObject.h in the UserObjectInterface.
const std::string & userObjectName (const UserObject &uo) const
Gets a UserObject's name; avoids including UserObject.h in the UserObjectInterface.
Private Attributes
const MooseObject & _uoi_moose_object
Moose object using the interface.
const FEProblemBase & _uoi_feproblem
Reference to the FEProblemBase instance.
const THREAD_ID _uoi_tid
Thread ID.
Detailed Description
Interface for objects that need to use UserObjects.
Definition at line 22 of file UserObjectInterface.h.
Constructor & Destructor Documentation
UserObjectInterface()
UserObjectInterface::UserObjectInterface (const MooseObject * moose_object)
Parameters
params The parameters used by the object being instantiated. This class needs them so it can get the user object named in the input file, but the object calling getUserObject only needs to use the name on the left hand side of the statement "user_object = user_object_name"
Definition at line 23 of file UserObjectInterface.C.
  : _uoi_moose_object(*moose_object),
    _uoi_feproblem(*_uoi_moose_object.parameters().getCheckedPointerParam<FEProblemBase *>(
        "_fe_problem_base")),
    _uoi_tid(_uoi_moose_object.parameters().have_parameter<THREAD_ID>("_tid")
                 ? _uoi_moose_object.parameters().get<THREAD_ID>("_tid")
                 : 0)
{
}
Member Function Documentation
addUserObjectDependencyHelper()
virtual void UserObjectInterface::addUserObjectDependencyHelper (const UserObject &) const inline protected virtual
Helper for deriving classes to override to add dependencies when a UserObject is requested.
Reimplemented in UserObject, AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, AuxKernelTempl< RealVectorValue >, and InitialConditionBase.
Definition at line 108 of file UserObjectInterface.h.
{}
Referenced by getUserObjectBaseByName().
castUserObject()
template<class T > const T & UserObjectInterface::castUserObject (const UserObject & uo_base, const std::string & param_name = "") const private
Internal helper that casts the UserObject uo_base to the reqested type.
Exits with a useful error if the casting failed. If the parameter param_name is provided and is valid, a paramError() will be used instead.
Definition at line 136 of file UserObjectInterface.h.
{
  const T * uo = dynamic_cast<const T *>(&uo_base);
  if (!uo)
  {
    std::stringstream oss;
    oss << "The provided UserObject \"" << userObjectName(uo_base) << "\" of type "
        << userObjectType(uo_base)
        << " is not derived from the required type.\n\nThe UserObject must derive from "
        << MooseUtils::prettyCppType<T>() << ".";
    if (_uoi_moose_object.parameters().isParamValid(param_name))
      _uoi_moose_object.paramError(param_name, oss.str());
    else
      _uoi_moose_object.mooseError(oss.str());
  }
  return *uo;
}
getUserObject()
template<class T > const T & UserObjectInterface::getUserObject (const std::string & param_name, bool is_dependency = true) const
Get an user object with a given parameter param_name.
Parameters
param_name The name of the parameter key of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with name associated with the parameter param_name
Definition at line 160 of file UserObjectInterface.h.
{
  return castUserObject<T>(getUserObjectBase(param_name, is_dependency), param_name);
}
getUserObjectBase()
const UserObject & UserObjectInterface::getUserObjectBase (const std::string & param_name, bool is_dependency = true) const
Get an user object with a given parameter param_name.
Parameters
param_name The name of the parameter key of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with name associated with the parameter param_name
Definition at line 79 of file UserObjectInterface.C.
{
  const auto object_name = getUserObjectName(param_name);
  if (!hasUserObjectByName(object_name))
    _uoi_moose_object.paramError(
        param_name, "The requested UserObject with the name \"", object_name, "\" was not found.");
  return getUserObjectBaseByName(object_name, is_dependency);
}
Referenced by getUserObject().
getUserObjectBaseByName()
const UserObject & UserObjectInterface::getUserObjectBaseByName (const UserObjectName & object_name, bool is_dependency = true) const
Get an user object with the name object_name.
Parameters
object_name The name of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with the name object_name
Definition at line 91 of file UserObjectInterface.C.
{
  if (!hasUserObjectByName(object_name))
    _uoi_moose_object.mooseError(
        "The requested UserObject with the name \"", object_name, "\" was not found.");
  const auto & uo_base_tid0 = _uoi_feproblem.getUserObjectBase(object_name, /* tid = */ 0);
  if (is_dependency)
    addUserObjectDependencyHelper(uo_base_tid0);
  const THREAD_ID tid = uo_base_tid0.needThreadedCopy() ? _uoi_tid : 0;
  return _uoi_feproblem.getUserObjectBase(object_name, tid);
}
Referenced by UserObject::getDependObjects(), getUserObjectBase(), and getUserObjectByName().
getUserObjectByName()
template<class T > const T & UserObjectInterface::getUserObjectByName (const UserObjectName & object_name, bool is_dependency = true) const
Get an user object with the name object_name.
Parameters
object_name The name of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with the name object_name
Definition at line 167 of file UserObjectInterface.h.
{
  return castUserObject<T>(getUserObjectBaseByName(object_name, is_dependency));
}
getUserObjectName()
UserObjectName UserObjectInterface::getUserObjectName (const std::string & param_name) const
Returns
The name of the user object associated with the parameter param_name
Definition at line 34 of file UserObjectInterface.C.
{
  const auto & params = _uoi_moose_object.parameters();
  if (!params.isParamValid(param_name))
    _uoi_moose_object.mooseError("Failed to get a parameter with the name \"",
                                 param_name,
                                 "\" when getting a UserObjectName.",
                                 "\n\nKnown parameters:\n",
                                 _uoi_moose_object.parameters());
  // Other interfaces will use this interface (PostprocessorInterface, VectorPostprocessorInterface)
  // to grab UOs with a specialized name, so we need to check them all
  UserObjectName name;
  if (params.isType<UserObjectName>(param_name))
    name = params.get<UserObjectName>(param_name);
  else if (params.isType<PostprocessorName>(param_name))
    name = params.get<PostprocessorName>(param_name);
  else if (params.isType<VectorPostprocessorName>(param_name))
    name = params.get<VectorPostprocessorName>(param_name);
  else if (params.isType<std::string>(param_name))
    name = params.get<std::string>(param_name);
  else
    _uoi_moose_object.paramError(
        param_name,
        "Parameter of type \"",
        params.type(param_name),
        "\" is not an expected type for getting the name of a UserObject.");
  return name;
}
Referenced by getUserObjectBase(), and hasUserObject().
hasUserObject() [1/2]
bool UserObjectInterface::hasUserObject (const std::string & param_name) const
Returns
Whether or not a UserObject exists with the name given by the parameter param_name.
Definition at line 67 of file UserObjectInterface.C.
{
  return hasUserObjectByName(getUserObjectName(param_name));
}
hasUserObject() [2/2]
template<class T > bool UserObjectInterface::hasUserObject (const std::string & param_name) const
Definition at line 175 of file UserObjectInterface.h.
{
  return hasUserObjectByName<T>(getUserObjectName(param_name));
}
hasUserObjectByName() [1/2]
bool UserObjectInterface::hasUserObjectByName (const UserObjectName & object_name) const
Definition at line 73 of file UserObjectInterface.C.
{
  return _uoi_feproblem.hasUserObject(object_name);
}
Referenced by getUserObjectBase(), getUserObjectBaseByName(), hasUserObject(), and hasUserObjectByName().
hasUserObjectByName() [2/2]
template<class T > bool UserObjectInterface::hasUserObjectByName (const UserObjectName & object_name) const
Definition at line 182 of file UserObjectInterface.h.
{
  if (!hasUserObjectByName(object_name))
    return false;
  return dynamic_cast<const T *>(&_uoi_feproblem.getUserObjectBase(object_name));
}
userObjectName()
const std::string & UserObjectInterface::userObjectName (const UserObject & uo) const private
Gets a UserObject's name; avoids including UserObject.h in the UserObjectInterface.
Definition at line 113 of file UserObjectInterface.C.
{
  return uo.name();
}
Referenced by castUserObject().
userObjectType()
const std::string & UserObjectInterface::userObjectType (const UserObject & uo) const private
Gets a UserObject's type; avoids including UserObject.h in the UserObjectInterface.
Definition at line 107 of file UserObjectInterface.C.
{
  return uo.type();
}
Referenced by castUserObject().
validParams()
InputParameters UserObjectInterface::validParams () static
Definition at line 18 of file UserObjectInterface.C.
{
  return emptyInputParameters();
}
Referenced by FVInterfaceKernel::validParams().
Member Data Documentation
_uoi_feproblem
const FEProblemBase& UserObjectInterface::_uoi_feproblem private
Reference to the FEProblemBase instance.
Definition at line 128 of file UserObjectInterface.h.
Referenced by getUserObjectBaseByName(), and hasUserObjectByName().
_uoi_moose_object
const MooseObject& UserObjectInterface::_uoi_moose_object private
Moose object using the interface.
Definition at line 125 of file UserObjectInterface.h.
Referenced by castUserObject(), getUserObjectBase(), getUserObjectBaseByName(), and getUserObjectName().
_uoi_tid
const THREAD_ID UserObjectInterface::_uoi_tid private
Thread ID.
Definition at line 131 of file UserObjectInterface.h.
Referenced by getUserObjectBaseByName().
The documentation for this class was generated from the following files:
moose/framework/include/userobjects/UserObjectInterface.h
moose/framework/src/userobjects/UserObjectInterface.C