Zapdos: AdvancedOutput Class Reference
AdvancedOutput Class Reference
Based class for output objects.
#include <AdvancedOutput.h>
Public Member Functions
AdvancedOutput (const InputParameters &parameters)
Class constructor.
virtual ~AdvancedOutput ()
Class destructor.
virtual bool hasOutput ()
Returns true if any of the other has methods return true.
bool hasOutput (const ExecFlagType &type)
Tests that any output exist for the given output type.
bool hasNodalVariableOutput ()
Returns true if there exists nodal nonlinear variables for output.
const std::set< std::string > & getNodalVariableOutput ()
The list of nodal nonlinear variables names that are set for output.
bool hasElementalVariableOutput ()
Returns true if there exists elemental nonlinear variables for output.
const std::set< std::string > & getElementalVariableOutput ()
The list of elemental nonlinear variables names that are set for output.
bool hasScalarOutput ()
Returns true if there exists scalar variables for output.
const std::set< std::string > & getScalarOutput ()
The list of scalar variables names that are set for output.
bool hasPostprocessorOutput ()
Returns true if there exists postprocessors for output.
const std::set< std::string > & getPostprocessorOutput ()
The list of postprocessor names that are set for output.
bool hasVectorPostprocessorOutput ()
Returns true if there exists VectorPostprocessors for output.
const std::set< std::string > & getVectorPostprocessorOutput ()
The list of VectorPostprocessor names that are set for output.
bool hasReporterOutput ()
Returns true if there exists Reporter for output.
const std::set< std::string > & getReporterOutput ()
The list of Reporter names that are set for output.
const OutputOnWarehouse & advancedExecuteOn () const
Get the current advanced 'execute_on' selections for display.
virtual std::string filename ()
The filename for the output file.
void setFileBase (const std::string &file_base)
Sets the file base string if the 'file_base' parameter is not set.
void setFileNumber (unsigned int num)
Sets the file number manually.
unsigned int getFileNumber ()
Return the current file number for this outputter.
virtual Real time () override
Get the output time.
virtual Real timeOld ()
Get the old output time.
virtual Real dt ()
Get the current time step size.
virtual Real dtOld ()
Get old time step size.
virtual int timeStep ()
Get the current time step.
const unsigned int & interval () const
Get the output interval.
const MultiMooseEnum & executeOn () const
Get the current 'execute_on' selections for display.
bool isAdvanced ()
Returns true if this object is an AdvancedOutput object.
void allowOutput (bool state)
Method for controlling the allow output state.
virtual void outputStep (const ExecFlagType &type)
A single call to this function should output all the necessary data for a single timestep.
const std::set< Real > & getSyncTimes ()
virtual bool enabled () const
Return the enabled status of the object.
MooseApp & getMooseApp () const
Get the MooseApp this class is associated with.
const std::string & type () const
Get the type of this class.
virtual const std::string & name () const
Get the name of the class.
std::string typeAndName () const
Get the class's combined type and name; useful in error handling.
MooseObjectParameterName uniqueParameterName (const std::string &parameter_name) const
The unique parameter name of a valid parameter of this object for accessing parameter controls.
const InputParameters & parameters () const
Get the parameters of the object.
MooseObjectName uniqueName () const
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
template<typename T >
const T & getParam (const std::string &name) const
Retrieve a parameter for the object.
template<typename T1 , typename T2 >
std::vector< std::pair< T1, T2 > > getParam (const std::string &param1, const std::string &param2) const
Retrieve two parameters and provide pair of parameters for the object.
template<typename T >
const T & getRenamedParam (const std::string &old_name, const std::string &new_name) const
Retrieve a renamed parameter for the object.
template<typename T >
T getCheckedPointerParam (const std::string &name, const std::string &error_string="") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
bool isParamValid (const std::string &name) const
Test if the supplied parameter is valid.
bool isParamSetByUser (const std::string &nm) const
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
template<typename... Args>
void paramError (const std::string &param, Args... args) const
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramWarning (const std::string &param, Args... args) const
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramInfo (const std::string &param, Args... args) const
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
std::string objectErrorPrefix (const std::string &error_type) const
A descriptive prefix for errors for an object.
void connectControllableParams (const std::string &parameter, const std::string &object_type, const std::string &object_name, const std::string &object_parameter) const
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
template<typename... Args>
void mooseError (Args &&... args) const
Emits an error prefixed with object name and type.
template<typename... Args>
void mooseErrorNonPrefixed (Args &&... args) const
Emits an error without the prefixing included in mooseError().
template<typename... Args>
void mooseWarning (Args &&... args) const
Emits a warning prefixed with object name and type.
template<typename... Args>
void mooseWarningNonPrefixed (Args &&... args) const
Emits a warning without the prefixing included in mooseWarning().
template<typename... Args>
void mooseDeprecated (Args &&... args) const
template<typename... Args>
void mooseInfo (Args &&... args) const
std::string errorPrefix (const std::string &error_type) const
A descriptive prefix for errors for this object:
std::string getDataFileName (const std::string &param) const
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
std::string getDataFileNameByName (const std::string &name, const std::string *param=nullptr) const
Returns the path of a data file for a given relative file path.
virtual void meshChanged ()
Called on this object when the mesh changes.
virtual void timestepSetup ()
Gets called at the beginning of the timestep before this object is asked to do its job.
virtual void jacobianSetup ()
Gets called just before the Jacobian is computed and before this object is asked to do its job.
virtual void residualSetup ()
Gets called just before the residual is computed and before this object is asked to do its job.
virtual void subdomainSetup ()
Gets called when the subdomain changes (i.e.
virtual void customSetup (const ExecFlagType &)
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
const ExecFlagEnum & getExecuteOnEnum () const
Return the execute on MultiMooseEnum for this object.
const Function & getFunction (const std::string &name) const
Get a function with a given name.
const Function & getFunctionByName (const FunctionName &name) const
Get a function with a given name.
bool hasFunction (const std::string &param_name) const
Determine if the function exists.
bool hasFunctionByName (const FunctionName &name) const
Determine if the function exists.
bool isDefaultPostprocessorValue (const std::string &param_name, const unsigned int index=0) const
Determine whether or not the Postprocessor is a default value.
bool hasPostprocessor (const std::string &param_name, const unsigned int index=0) const
Determine if the Postprocessor data exists.
bool hasPostprocessorByName (const PostprocessorName &name) const
Determine if the Postprocessor data exists.
std::size_t coupledPostprocessors (const std::string &param_name) const
Returns number of Postprocessors coupled under parameter name.
const PostprocessorName & getPostprocessorName (const std::string &param_name, const unsigned int index=0) const
Get the name of a postprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValue (const std::string &param_name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValue (const std::string &param_name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the value of a VectorPostprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValueByName (const VectorPostprocessorName &name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValueByName (const VectorPostprocessorName &name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the value of the VectorPostprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValueOld (const std::string &param_name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValueOld (const std::string &param_name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the old value of a VectorPostprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValueOldByName (const VectorPostprocessorName &name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValueOldByName (const VectorPostprocessorName &name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the old value of a VectorPostprocessor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValue (const std::string &param_name, const std::string &vector_name) const
Return the scatter value for the post processor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValueByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Return the scatter value for the post processor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValueOld (const std::string &param_name, const std::string &vector_name) const
Return the old scatter value for the post processor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValueOldByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Return the old scatter value for the post processor.
bool hasVectorPostprocessor (const std::string &param_name, const std::string &vector_name) const
Determine if the VectorPostprocessor data exists by parameter.
bool hasVectorPostprocessor (const std::string &param_name) const
Determine if the VectorPostprocessor exists by parameter.
bool hasVectorPostprocessorByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Determine if the VectorPostprocessor data exists by name.
bool hasVectorPostprocessorByName (const VectorPostprocessorName &name) const
Determine if the VectorPostprocessor exists by name.
const VectorPostprocessorName & getVectorPostprocessorName (const std::string &param_name) const
Get the name of a VectorPostprocessor associated with a parameter.
PerfGraph & perfGraph ()
Get the PerfGraph.
const PostprocessorValue & getPostprocessorValue (const std::string &param_name, const unsigned int index=0) const
doco-normal-methods-begin Retrieve the value of a Postprocessor or one of it's old or older values
const PostprocessorValue & getPostprocessorValueOld (const std::string &param_name, const unsigned int index=0) const
const PostprocessorValue & getPostprocessorValueOlder (const std::string &param_name, const unsigned int index=0) const
virtual const PostprocessorValue & getPostprocessorValueByName (const PostprocessorName &name) const
Retrieve the value of the Postprocessor.
const PostprocessorValue & getPostprocessorValueOldByName (const PostprocessorName &name) const
const PostprocessorValue & getPostprocessorValueOlderByName (const PostprocessorName &name) const
bool isVectorPostprocessorDistributed (const std::string &param_name) const
Return true if the VectorPostprocessor is marked with parallel_type as DISTRIBUTED.
bool isVectorPostprocessorDistributedByName (const VectorPostprocessorName &name) const
Static Public Member Functions
static InputParameters validParams ()
static InputParameters enableOutputTypes (const std::string &names=std::string())
A method for enabling individual output type control.
static ExecFlagEnum getDefaultExecFlagEnum ()
Return an ExecFlagEnum object with the available execution flags for Output objects.
static void addDeprecatedInputParameters (InputParameters &params)
A static helper for injecting deprecated parameters.
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Member Functions
virtual void initialSetup ()
Call init() method on setup.
virtual void init ()
Populates the various data structures needed to control the output.
virtual bool shouldOutput ()
Handles logic for determining if a step should be output.
virtual void output ()
A single call to this function should output all the necessary data for a single timestep.
virtual void outputNodalVariables ()
Performs output of nodal nonlinear variables The child class must define this method to output the nonlinear variables as desired.
virtual void outputElementalVariables ()
Performs output of elemental nonlinear variables The child class must define this method to output the nonlinear variables as desired.
virtual void outputScalarVariables ()
Performs output of scalar variables The child class must define this method to output the scalar variables as desired.
virtual void outputPostprocessors ()
Performs output of postprocessors The child class must define this method to output the postprocessors as desired.
virtual void outputVectorPostprocessors ()
Performs output of VectorPostprocessors The child class must define this method to output the VectorPostprocessors as desired.
virtual void outputInput ()
Performs the output of the input file By default this method does nothing and is not called, the individual Output objects are responsible for calling it.
virtual void outputSystemInformation ()
virtual void outputReporters ()
Output Reporter values.
bool checkFilename ()
Checks the filename for output Checks the output against the 'output_if_base_contians' list.
virtual void setFileBaseInternal (const std::string &file_base)
Internal function that sets the file_base.
bool inNonlinearTimeWindow ()
bool inLinearTimeWindow ()
virtual Real getOutputTime ()
Get the time that will be used for stream/file outputting.
virtual bool onInterval ()
Returns true if the output interval is satisfied.
template<typename T , typename... Args>
T & declareRestartableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
ManagedValue< T > declareManagedRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declares a piece of "managed" restartable data and initialize it.
template<typename T , typename... Args>
const T & getRestartableData (const std::string &data_name) const
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
template<typename T , typename... Args>
T & declareRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
T & declareRecoverableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "recoverable" and initialize it.
template<typename T , typename... Args>
T & declareRestartableDataWithObjectName (const std::string &data_name, const std::string &object_name, Args &&... args)
Declare a piece of data as "restartable".
template<typename T , typename... Args>
T & declareRestartableDataWithObjectNameWithContext (const std::string &data_name, const std::string &object_name, void *context, Args &&... args)
Declare a piece of data as "restartable".
std::string restartableName (const std::string &data_name) const
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
virtual void addPostprocessorDependencyHelper (const PostprocessorName &) const
Helper for deriving classes to override to add dependencies when a Postprocessor is requested.
virtual void addVectorPostprocessorDependencyHelper (const VectorPostprocessorName &) const
Helper for deriving classes to override to add dependencies when a VectorPostprocessor is requested.
const ReporterName & getReporterName (const std::string &param_name) const
virtual void addReporterDependencyHelper (const ReporterName &)
A method that can be overridden to update the UO dependencies.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level) const
Call to register a named section for timing.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level, const std::string &live_message, const bool print_dots=true) const
Call to register a named section for timing.
std::string timedSectionName (const std::string &section_name) const
template<typename T >
const T & getReporterValue (const std::string &param_name, const std::size_t time_index=0)
doco-normal-methods-begin Returns read-only reference to a Reporter value that is provided by an input parameter.
template<typename T >
const T & getReporterValue (const std::string &param_name, ReporterMode mode, const std::size_t time_index=0)
template<typename T >
const T & getReporterValueByName (const ReporterName &reporter_name, const std::size_t time_index=0)
Returns read-only reference to a Reporter value that is provided by name directly.
template<typename T >
const T & getReporterValueByName (const ReporterName &reporter_name, ReporterMode mode, const std::size_t time_index=0)
bool hasReporterValue (const std::string &param_name) const
Return True if the Reporter value exists.
template<typename T >
bool hasReporterValue (const std::string &param_name) const
bool hasReporterValueByName (const ReporterName &reporter_name) const
template<typename T >
bool hasReporterValueByName (const ReporterName &reporter_name) const
Static Protected Member Functions
static PetscErrorCode petscNonlinearOutput (SNES, PetscInt its, PetscReal fnorm, void *void_ptr)
Performs the output on non-linear iterations This is the monitor method that PETSc will call on non-linear iterations.
static PetscErrorCode petscLinearOutput (KSP, PetscInt its, PetscReal fnorm, void *void_ptr)
Performs the output onlinear iterations This is the monitor method that PETSc will call on linear iterations.
Protected Attributes
bool _elemental_as_nodal
Flags to control nodal output.
bool _scalar_as_nodal
const ReporterData & _reporter_data
Storage for Reporter values.
unsigned int & _file_num
A file number counter, initialized to 0 (this must be controlled by the child class, see Exodus)
unsigned int _padding
Number of digits to pad the extensions.
std::vector< std::string > _output_if_base_contains
Storage for 'output_if_base_contains'.
std::string _file_base
The base filename from the input paramaters.
Real _norm
Current norm returned from PETSc.
PetscInt _nonlinear_iter
Current non-linear iteration returned from PETSc.
PetscInt _linear_iter
Current linear iteration returned from PETSc.
bool _on_linear_residual
True if current output calls is on the linear residual (used by time())
bool _on_nonlinear_residual
True if current output call is on the non-linear residual (used by time())
FEProblemBase * _problem_ptr
Pointer the the FEProblemBase object for output object (use this)
bool _transient
Transient flag (true = transient)
bool _use_displaced
Flag for using displaced mesh.
EquationSystems * _es_ptr
Reference the the libMesh::EquationSystems object that contains the data.
MooseMesh * _mesh_ptr
A convenience pointer to the current mesh (reference or displaced depending on "use_displaced")
bool _sequence
Flag for forcing call to outputSetup() with every call to output() (restartable)
ExecFlagEnum _execute_on
The common Execution types; this is used as the default execution type for everything except system information and input.
ExecFlagType _current_execute_flag
Current execute on flag.
Real & _time
The current time for output purposes.
Real & _time_old
The old time.
int & _t_step
The current time step.
Real & _dt
Time step delta.
Real & _dt_old
Old time step delta.
unsigned int _num
The number of outputs written.
const unsigned int _interval
The output time step interval.
const Real _minimum_time_interval
Minimum simulation time between outputs.
std::set< Real > _sync_times
Sync times for this outputter.
const Times *const _sync_times_object
Sync times object for this outputter.
Real _start_time
Start outputting time.
Real _end_time
End outputting time.
int _start_step
Start outputting at this time step.
int _end_step
End outputting at this time step.
Real _t_tol
Time checking tolerance.
bool _sync_only
Flag for only executing at sync times.
bool _allow_output
Flag for disabling output.
bool _is_advanced
Flag for advanced output testing.
OutputOnWarehouse _advanced_execute_on
Storage for the individual component execute flags.
Real & _last_output_time
last simulation time an output has occured
const bool & _enabled
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
MooseApp & _app
The MOOSE application this is associated with.
const std::string & _type
The type of this class.
const std::string & _name
The name of this class, reference to value stored in InputParameters.
const InputParameters & _pars
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Factory & _factory
The Factory associated with the MooseApp.
ActionFactory & _action_factory
Builds Actions.
MooseApp & _restartable_app
Reference to the application.
const std::string _restartable_system_name
The system name this object is in.
const THREAD_ID _restartable_tid
The thread ID for this object.
const bool _restartable_read_only
Flag for toggling read only status (see ReporterData)
FEProblemBase & _mci_feproblem
Reference to FEProblemBase instance.
const ExecFlagEnum & _execute_enum
Execute settings for this object.
MooseApp & _pg_moose_app
The MooseApp that owns the PerfGraph.
const std::string _prefix
A prefix to use for all sections.
PetscOutput * _petsc_output
Private Member Functions
void initAvailableLists ()
Initializes the available lists for each of the output types.
void initExecutionTypes (const std::string &name, ExecFlagEnum &input)
Initialize the possible execution types.
void initShowHideLists (const std::vector< VariableName > &show, const std::vector< VariableName > &hide)
Parses the user-supplied input for hiding and showing variables and postprocessors into a list for each type of output.
template<typename postprocessor_type >
void initPostprocessorOrVectorPostprocessorLists (const std::string &execute_data_name)
Helper function for initAvailableLists, templated on warehouse type and postprocessor_type.
void initOutputList (OutputData &data)
Initializes the list of items to be output using the available, show, and hide lists.
bool wantOutput (const std::string &name, const ExecFlagType &type)
Handles logic for determining if a step should be output.
bool hasOutputHelper (const std::string &name)
Helper method for checking if output types exists.
void solveSetup () override
Internal setup function that executes at the beginning of the time step.
template<typename... Args>
std::string paramErrorMsg (const std::string &param, Args... args) const
RestartableDataValue & registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const
Helper function for actually registering the restartable data.
void registerRestartableNameWithFilterOnApp (const std::string &name, Moose::RESTARTABLE_FILTER filter)
Helper function for actually registering the restartable data.
template<typename T , typename... Args>
RestartableData< T > & declareRestartableDataHelper (const std::string &data_name, void *context, Args &&... args) const
Helper function for declaring restartable data.
const PostprocessorName & getPostprocessorNameInternal (const std::string &param_name, const unsigned int index, const bool allow_default_value=true) const
Internal method for getting the PostprocessorName associated with a paremeter.
bool isDefaultPostprocessorValueByName (const PostprocessorName &name) const
PostprocessorValue getDefaultPostprocessorValueByName (const PostprocessorName &name) const
void checkParam (const std::string &param_name, const unsigned int index=std::numeric_limits< unsigned int >::max()) const
Checks the parameters relating to a Postprocessor.
bool postprocessorsAdded () const
const VectorPostprocessorValue & getVectorPostprocessorByNameHelper (const VectorPostprocessorName &name, const std::string &vector_name, bool broadcast, std::size_t t_index) const
Helper function for extracting VPP data from ReporterData object.
const VectorPostprocessorContext< VectorPostprocessorValue > & getVectorPostprocessorContextByNameHelper (const VectorPostprocessorName &name, const std::string &vector_name) const
Helper for getting the VPP context that handles scatter values.
bool vectorPostprocessorsAdded () const
bool reportersAdded () const
template<typename T >
void possiblyCheckHasReporter (const ReporterName &reporter_name, const std::string &param_name="") const
Helpers for "possibly" checking if a Reporter value exists.
const PostprocessorValue & getPostprocessorValueInternal (const std::string &param_name, unsigned int index, std::size_t t_index) const
Internal methods for getting Postprocessor values.
const PostprocessorValue & getPostprocessorValueByNameInternal (const PostprocessorName &name, std::size_t t_index) const
void possiblyCheckHasVectorPostprocessor (const std::string &param_name, const std::string &vector_name) const
Helpers for "possibly" checking if a vpp exists.
void possiblyCheckHasVectorPostprocessorByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Static Private Member Functions
static void addValidParams (InputParameters &params, const MultiMooseEnum &types)
Method for defining the available parameters based on the types of outputs.
static MultiMooseEnum getOutputTypes ()
Get the supported types of output (e.g., postprocessors, etc.)
Private Attributes
OutputDataWarehouse _execute_data
Storage structures for the various output types.
std::map< std::string, Real > _last_execute_time
Storage for the last output time for the various output types, this is used to avoid duplicate output when using OUTPUT_FINAL flag.
const bool _postprocessors_as_reporters
Flags for outputting PP/VPP data as a reporter.
const bool _vectorpostprocessors_as_reporters
Real _nonlinear_time
The psuedo non-linear time.
Real _nonlinear_dt
The pseuedo non-linear time step.
Real _linear_time
Psuedo linear time.
Real _linear_dt
Psuedo linear time step.
Real _nonlinear_dt_divisor
Pseudo non-linear timestep divisor.
Real _linear_dt_divisor
Pseudo linear timestep divisor.
Real _nonlinear_start_time
Non-linear residual output start time.
Real _linear_start_time
Linear residual output start time.
Real _nonlinear_end_time
Non-linear residual output end time.
Real _linear_end_time
Linear residual output end time.
const MooseBase *const _moose_base
The MooseBase object that inherits this class.
const MooseObject & _parent
const RestartableDataMapName _metaname
Restartable metadata name.
std::string _restartable_name
The name of the object.
ExecFlagEnum _empty_execute_enum
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
const InputParameters & _fni_params
Parameters of the object with this interface.
FEProblemBase & _fni_feproblem
Reference to FEProblemBase instance.
const THREAD_ID _fni_tid
Thread ID.
const MooseObject & _ppi_moose_object
The MooseObject that uses this interface.
const InputParameters & _ppi_params
PostprocessorInterface Parameters.
const FEProblemBase & _ppi_feproblem
Reference the the FEProblemBase class.
std::map< PostprocessorName, std::unique_ptr< PostprocessorValue > > _default_values
Holds the default postprocessor values that are requested (key is PostprocessorName)
const bool _broadcast_by_default
Whether or not to force broadcasting by default.
const MooseObject & _vpi_moose_object
The MooseObject that uses this interface.
const FEProblemBase & _vpi_feproblem
Reference the FEProblemBase class.
const THREAD_ID _vpi_tid
Thread ID.
const InputParameters & _ri_params
Parameters for the MooseObject inherting from this interface.
FEProblemBase & _ri_fe_problem_base
Provides access to FEProblemBase::getReporterData.
const ReporterData & _ri_reporter_data
The ReporterData.
const MooseObject & _ri_moose_object
The MooseObject needing this interface.
Friends
class OutputWarehouse
class Console
class TransientMultiApp
Detailed Description
Based class for output objects.
Each output class (e.g., Exodus) should inherit from this base class. At a minimum, the pure virtual methods for the various types of output must be defined in the child class.
See also
Exodus Console CSV
Definition at line 34 of file AdvancedOutput.h.
Constructor & Destructor Documentation
AdvancedOutput()
AdvancedOutput::AdvancedOutput (const InputParameters & parameters)
Class constructor.
The constructor performs all of the necessary initialization of the various output lists required for the various output types.
Parameters
parameters The InputParameters for the object
Definition at line 133 of file AdvancedOutput.C.
  : FileOutput(parameters),
    _elemental_as_nodal(isParamValid("elemental_as_nodal") ? getParam<bool>("elemental_as_nodal")
                                                           : false),
    _scalar_as_nodal(isParamValid("scalar_as_nodal") ? getParam<bool>("scalar_as_nodal") : false),
    _reporter_data(_problem_ptr->getReporterData()),
    _postprocessors_as_reporters(getParam<bool>("postprocessors_as_reporters")),
    _vectorpostprocessors_as_reporters(getParam<bool>("vectorpostprocessors_as_reporters"))
{
  _is_advanced = true;
  _advanced_execute_on = OutputOnWarehouse(_execute_on, parameters);
}
~AdvancedOutput()
AdvancedOutput::~AdvancedOutput () virtual
Class destructor.
Definition at line 196 of file AdvancedOutput.C.
{}
Member Function Documentation
addDeprecatedInputParameters()
static void Output::addDeprecatedInputParameters (InputParameters & params) static inherited
A static helper for injecting deprecated parameters.
addPostprocessorDependencyHelper()
virtual void PostprocessorInterface::addPostprocessorDependencyHelper (const PostprocessorName &) const inline protected virtual inherited
Helper for deriving classes to override to add dependencies when a Postprocessor is requested.
Reimplemented in UserObject, AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, AuxKernelTempl< RealVectorValue >, and InitialConditionBase.
Definition at line 141 of file PostprocessorInterface.h.
{}
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal().
addReporterDependencyHelper()
virtual void ReporterInterface::addReporterDependencyHelper (const ReporterName &) inline protected virtual inherited
A method that can be overridden to update the UO dependencies.
This is needed because the get methods for this interface cannot be virtual because of the template parameter. See GeneralUserObject for how it is utilized.
Reimplemented in UserObject.
Definition at line 97 of file ReporterInterface.h.
{}
Referenced by ReporterInterface::getReporterValueByName().
addValidParams()
void AdvancedOutput::addValidParams (InputParameters & params, const MultiMooseEnum & types) static private
Method for defining the available parameters based on the types of outputs.
Parameters
params The InputParamters object to add parameters to
types The types of output this object should support (see Output::enableOutputTypes)
Each output object may have a varying set of supported output types (e.g., elemental variables may not be supported). This private, static method populates the InputParameters object with the correct parameters based on the items contained in the ExecFlagEnum.
This method is private, users should utilize the Output::enableOutputTypes method
See also
Output::enableOutputTypes
Definition at line 684 of file AdvancedOutput.C.
{
  ExecFlagEnum empty_execute_on = MooseUtils::getDefaultExecFlagEnum();
  empty_execute_on.addAvailableFlags(EXEC_FAILED);
  // Nodal output
  if (types.contains("nodal"))
  {
    params.addParam<ExecFlagEnum>(
        "execute_nodal_on", empty_execute_on, "Control the output of nodal variables");
    params.addParamNamesToGroup("execute_nodal_on", "Selection/restriction of output");
  }
  // Elemental output
  if (types.contains("elemental"))
  {
    params.addParam<ExecFlagEnum>(
        "execute_elemental_on", empty_execute_on, "Control the output of elemental variables");
    params.addParamNamesToGroup("execute_elemental_on", "Selection/restriction of output");
    // Add material output control, which are output via elemental variables
    params.addParam<bool>("output_material_properties",
                          false,
                          "Flag indicating if material properties should be output");
    params.addParam<std::vector<std::string>>(
        "show_material_properties",
        "List of material properties that should be written to the output");
    params.addParamNamesToGroup("output_material_properties show_material_properties", "Materials");
    // Add mesh extra element id control, which are output via elemental variables
    params.addParam<bool>(
        "output_extra_element_ids",
        false,
        "Flag indicating if extra element ids defined on the mesh should be outputted");
    params.addParam<std::vector<std::string>>(
        "extra_element_ids_to_output",
        "List of extra element ids defined on the mesh that should be written to the output.");
    params.addParamNamesToGroup("output_extra_element_ids extra_element_ids_to_output", "Mesh");
  }
  // Scalar variable output
  if (types.contains("scalar"))
  {
    params.addParam<ExecFlagEnum>(
        "execute_scalars_on", empty_execute_on, "Control the output of scalar variables");
    params.addParamNamesToGroup("execute_scalars_on", "Selection/restriction of output");
  }
  // Nodal and scalar output
  if (types.contains("nodal") && types.contains("scalar"))
  {
    params.addParam<bool>("scalar_as_nodal", false, "Output scalar variables as nodal");
    params.addParamNamesToGroup("scalar_as_nodal", "Conversions before output");
  }
  // Elemental and nodal
  if (types.contains("elemental") && types.contains("nodal"))
  {
    params.addParam<bool>(
        "elemental_as_nodal", false, "Output elemental nonlinear variables as nodal");
    params.addParamNamesToGroup("elemental_as_nodal", "Conversions before output");
  }
  // Postprocessors
  if (types.contains("postprocessor"))
  {
    params.addParam<ExecFlagEnum>(
        "execute_postprocessors_on", empty_execute_on, "Control of when postprocessors are output");
    params.addParamNamesToGroup("execute_postprocessors_on", "Selection/restriction of output");
  }
  // Vector Postprocessors
  if (types.contains("vector_postprocessor"))
  {
    params.addParam<ExecFlagEnum>("execute_vector_postprocessors_on",
                                  empty_execute_on,
                                  "Enable/disable the output of VectorPostprocessors");
    params.addParamNamesToGroup("execute_vector_postprocessors_on",
                                "Selection/restriction of output");
  }
  // Reporters
  if (types.contains("reporter"))
  {
    params.addParam<ExecFlagEnum>(
        "execute_reporters_on", empty_execute_on, "Control of when Reporter values are output");
    params.addParamNamesToGroup("execute_reporters_on", "Selection/restriction of output");
  }
  // Input file
  if (types.contains("input"))
  {
    params.addParam<ExecFlagEnum>(
        "execute_input_on", empty_execute_on, "Enable/disable the output of the input file");
    params.addParamNamesToGroup("execute_input_on", "Selection/restriction of output");
  }
  // System Information
  if (types.contains("system_information"))
  {
    params.addParam<ExecFlagEnum>("execute_system_information_on",
                                  empty_execute_on,
                                  "Control when the output of the simulation information occurs");
    params.addParamNamesToGroup("execute_system_information_on", "Selection/restriction of output");
  }
}
Referenced by enableOutputTypes().
addVectorPostprocessorDependencyHelper()
virtual void VectorPostprocessorInterface::addVectorPostprocessorDependencyHelper (const VectorPostprocessorName &) const inline protected virtual inherited
Helper for deriving classes to override to add dependencies when a VectorPostprocessor is requested.
Reimplemented in UserObject, AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, and AuxKernelTempl< RealVectorValue >.
Definition at line 311 of file VectorPostprocessorInterface.h.
  {
  }
Referenced by VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), and VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper().
advancedExecuteOn()
const OutputOnWarehouse & AdvancedOutput::advancedExecuteOn () const virtual
Get the current advanced 'execute_on' selections for display.
Reimplemented from Output.
Definition at line 871 of file AdvancedOutput.C.
{
  return _advanced_execute_on;
}
Referenced by CSV::initialSetup().
allowOutput()
void Output::allowOutput (bool state) inline inherited
Method for controlling the allow output state.
Parameters
state The state to set the allow flag to
Definition at line 127 of file Output.h.
{ _allow_output = state; }
checkFilename()
bool FileOutput::checkFilename () protected inherited
Checks the filename for output Checks the output against the 'output_if_base_contians' list.
Returns
Returns true if the filename is valid for output
Definition at line 87 of file FileOutput.C.
{
  // Return true if 'output_if_base_contains' is not utilized
  if (_output_if_base_contains.empty())
    return true;
  // Assumed output is false
  bool output = false;
  // Loop through each string in the list
  for (const auto & search_string : _output_if_base_contains)
  {
    // Search for the string in the file base, if found set the output to true and break the loop
    if (_file_base.find(search_string) != std::string::npos)
    {
      output = true;
      break;
    }
  }
  // Return the value
  return output;
}
Referenced by shouldOutput(), and FileOutput::shouldOutput().
checkParam()
void PostprocessorInterface::checkParam (const std::string & param_name, const unsigned int index = std::numeric_limits<unsigned int>::max()) const private inherited
Checks the parameters relating to a Postprocessor.
If index is not set, index checking is not performed.
Definition at line 139 of file PostprocessorInterface.C.
{
  const bool check_index = index != std::numeric_limits<unsigned int>::max();
  if (!_ppi_params.isParamValid(param_name))
    _ppi_moose_object.mooseError(
        "When getting a Postprocessor, failed to get a parameter with the name \"",
        param_name,
        "\".",
        "\n\nKnown parameters:\n",
        _ppi_moose_object.parameters());
  if (_ppi_params.isType<PostprocessorName>(param_name))
  {
    if (check_index && index > 0)
      _ppi_moose_object.paramError(param_name,
                                   "A Postprocessor was requested with index ",
                                   index,
                                   " but a single Postprocessor is coupled.");
  }
  else if (_ppi_params.isType<std::vector<PostprocessorName>>(param_name))
  {
    const auto & names = _ppi_params.get<std::vector<PostprocessorName>>(param_name);
    if (check_index && names.size() <= index)
      _ppi_moose_object.paramError(param_name,
                                   "A Postprocessor was requested with index ",
                                   index,
                                   " but only ",
                                   names.size(),
                                   " Postprocessors are coupled.");
  }
  else
  {
    _ppi_moose_object.mooseError(
        "Supplied parameter with name \"",
        param_name,
        "\" of type \"",
        _ppi_params.type(param_name),
        "\" is not an expected type for getting a Postprocessor.\n\n",
        "Allowed types are \"PostprocessorName\" and \"std::vector<PostprocessorName>\".");
  }
}
Referenced by PostprocessorInterface::coupledPostprocessors(), and PostprocessorInterface::getPostprocessorNameInternal().
connectControllableParams()
void MooseBaseParameterInterface::connectControllableParams (const std::string & parameter, const std::string & object_type, const std::string & object_name, const std::string & object_parameter) const inherited
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
Parameters
parameter Name of the controllable parameter of this action
object_type Type of the object added by this action.
object_name Name of the object added by this action.
object_parameter Name of the parameter of the object.
Definition at line 34 of file MooseBaseParameterInterface.C.
{
  MooseObjectParameterName primary_name(uniqueName(), parameter);
  const auto base_type = _factory.getValidParams(object_type).get<std::string>("_moose_base");
  MooseObjectParameterName secondary_name(base_type, object_name, object_parameter);
  _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
      primary_name, secondary_name);
  const auto & tags = _pars.get<std::vector<std::string>>("control_tags");
  for (const auto & tag : tags)
  {
    if (!tag.empty())
    {
      MooseObjectParameterName tagged_name(tag, _moose_base->name(), parameter);
      _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
          tagged_name, secondary_name);
    }
  }
}
coupledPostprocessors()
std::size_t PostprocessorInterface::coupledPostprocessors (const std::string & param_name) const inherited
Returns number of Postprocessors coupled under parameter name.
Parameters
param_name The name of the Postprocessor parameter
Returns
Number of coupled post-processors, 1 if it's a single
Definition at line 129 of file PostprocessorInterface.C.
{
  checkParam(param_name);
  if (_ppi_params.isType<PostprocessorName>(param_name))
    return 1;
  return _ppi_params.get<std::vector<PostprocessorName>>(param_name).size();
}
Referenced by FunctionValuePostprocessor::FunctionValuePostprocessor().
customSetup()
virtual void SetupInterface::customSetup (const ExecFlagType &) inline virtual inherited
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
Reimplemented in Function.
Definition at line 61 of file SetupInterface.h.
{}
declareManagedRestartableDataWithContext()
template<typename T , typename... Args> Restartable::ManagedValue< T > Restartable::declareManagedRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declares a piece of "managed" restartable data and initialize it.
Here, "managed" restartable data means that the caller can destruct this data upon destruction of the return value of this method. Therefore, this ManagedValue<T> wrapper should survive after the final calls to dataStore() for it. That is... at the very end.
This is needed for objects whose destruction ordering is important, and enables natural c++ destruction in reverse construction order of the object that declares it.
See delcareRestartableData and declareRestartableDataWithContext for more information.
Definition at line 276 of file Restartable.h.
{
  auto & data_ptr =
      declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...);
  return Restartable::ManagedValue<T>(data_ptr);
}
declareRecoverableData()
template<typename T , typename... Args> T & Restartable::declareRecoverableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "recoverable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
Note - this data will NOT be restored on Restart!
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 351 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  registerRestartableNameWithFilterOnApp(full_name, Moose::RESTARTABLE_FILTER::RECOVERABLE);
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableData()
template<typename T , typename... Args> T & Restartable::declareRestartableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 269 of file Restartable.h.
{
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataHelper()
template<typename T , typename... Args> RestartableData< T > & Restartable::declareRestartableDataHelper (const std::string & data_name, void * context, Args &&... args) const private inherited
Helper function for declaring restartable data.
We use this function to reduce code duplication when returning const/nonconst references to the data.
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 303 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  // Here we will create the RestartableData even though we may not use this instance.
  // If it's already in use, the App will return a reference to the existing instance and we'll
  // return that one instead. We might refactor this to have the app create the RestartableData
  // at a later date.
  auto data_ptr =
      std::make_unique<RestartableData<T>>(full_name, context, std::forward<Args>(args)...);
  auto & restartable_data_ref = static_cast<RestartableData<T> &>(
      registerRestartableDataOnApp(std::move(data_ptr), _restartable_tid));
  return restartable_data_ref;
}
declareRestartableDataWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 294 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...).set();
}
declareRestartableDataWithObjectName()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectName (const std::string & data_name, const std::string & object_name, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
args Arguments to forward to the constructor of the data
Definition at line 323 of file Restartable.h.
{
  return declareRestartableDataWithObjectNameWithContext<T>(
      data_name, object_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataWithObjectNameWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectNameWithContext (const std::string & data_name, const std::string & object_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 333 of file Restartable.h.
{
  std::string old_name = _restartable_name;
  _restartable_name = object_name;
  T & value = declareRestartableDataWithContext<T>(data_name, context, std::forward<Args>(args)...);
  _restartable_name = old_name;
  return value;
}
dt()
Real Output::dt () virtual inherited
Get the current time step size.
Definition at line 302 of file Output.C.
{
  if (_transient)
    return _dt;
  else
    return 1;
}
Referenced by Console::writeTimestepInformation().
dtOld()
Real Output::dtOld () virtual inherited
Get old time step size.
Definition at line 311 of file Output.C.
{
  if (_transient)
    return _dt_old;
  else
    return 1;
}
enabled()
virtual bool MooseObject::enabled () const inline virtual inherited
Return the enabled status of the object.
Reimplemented in EigenKernel.
Definition at line 54 of file MooseObject.h.
{ return _enabled; }
Referenced by EigenKernel::enabled().
enableOutputTypes()
InputParameters AdvancedOutput::enableOutputTypes (const std::string & names = std::string()) static
A method for enabling individual output type control.
Parameters
names (optional) Space separated of output type names that are supported by this Output object, if this is omitted all outputs types will be supported. The list of available output types is given below.
Output objects vary widely in what type of outputs they support (e.g., elemental variables, or postprocessor data). This method provides the user a means for controlling the types of outputs that are supported for the object being created. This is a static method that MUST be used to append parameters inside the objects validParams function.
List of Output Types and Method Names The output system is designed around overloading virtual method calls to output the various output types, the following list gives the name of the output type and the associated virtual method that should be overloaded to perform the output in the object being created.
Type virtual Method Name
nodal outputNodalVariables() elemental outputElementalVariables() scalar outputScalarVariables() postprocessor outputPostprocessors() vector_postprocessor outputVectorPostprocessors() input outputInput() system_information outputSystemInformation()
See also
CSV Exodus
Definition at line 113 of file AdvancedOutput.C.
{
  // The parameters object that will be returned
  InputParameters params = emptyInputParameters();
  // Get the MultiEnum of output types
  MultiMooseEnum output_types = getOutputTypes();
  // Update the enum of output types to append
  if (names.empty())
    output_types = output_types.getRawNames();
  else
    output_types = names;
  // Add the parameters and return them
  addValidParams(params, output_types);
  return params;
}
Referenced by Console::validParams(), Exodus::validParams(), JSONOutput::validParams(), Nemesis::validParams(), TableOutput::validParams(), and XMLOutput::validParams().
errorPrefix()
std::string MooseBaseErrorInterface::errorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for this object:
The following <error_type> occurred in the object "<name>", of type "<type>".
Definition at line 15 of file MooseBaseErrorInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the object \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseErrorInterface::mooseError(), and MooseBaseErrorInterface::mooseWarning().
executeOn()
const MultiMooseEnum & Output::executeOn () const inherited
Get the current 'execute_on' selections for display.
Definition at line 326 of file Output.C.
{
  return _execute_on;
}
filename()
std::string FileOutput::filename () virtual inherited
The filename for the output file.
Returns
A string of output file including the extension, by default this returns _file_base
Reimplemented in Checkpoint, Console, CSV, DOFMapOutput, Exodus, GMVOutput, Gnuplot, JSONOutput, Nemesis, SolutionHistory, Tecplot, VTKOutput, XDA, and XMLOutput.
Definition at line 112 of file FileOutput.C.
{
  return _file_base;
}
Referenced by OutputWarehouse::resetFileBase().
getCheckedPointerParam()
template<typename T > T MooseBaseParameterInterface::getCheckedPointerParam (const std::string & name, const std::string & error_string = "") const inherited
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
The template parameter must be a pointer or an error will be thrown.
Definition at line 264 of file MooseBaseParameterInterface.h.
{
  return parameters().getCheckedPointerParam<T>(name, error_string);
}
getDataFileName()
std::string DataFileInterface< MooseObject >::getDataFileName (const std::string & param) const inherited
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
relative to the input file directory
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
relative to the input file directory
Definition at line 34 of file DataFileInterface.C.
{
  {
    const auto & absolute_path = _parent.template getParam<FileName>(param);
    if (MooseUtils::checkFileReadable(absolute_path, false, false, false))
    {
      _parent.paramInfo(param, "Data file '", absolute_path, "' found relative to the input file.");
      return absolute_path;
    }
  }
  const auto & relative_path = _parent.parameters().rawParamVal(param);
  return getDataFileNameByName(relative_path, &param);
}
getDataFileNameByName()
std::string DataFileInterface< MooseObject >::getDataFileNameByName (const std::string & name, const std::string * param = nullptr) const inherited
Returns the path of a data file for a given relative file path.
This can be used for hardcoded datafile names and will search the same locations as getDataFileName. The optional param pointer can be used to turn the mooseErrors this function emits into paramErrors
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
Definition at line 42 of file DataFileInterface.C.
{
  const auto share_dir = MooseUtils::pathjoin(Moose::getExecutablePath(), "..", "share");
  if (MooseUtils::pathIsDirectory(share_dir))
  {
    const auto dirs = MooseUtils::listDir(share_dir, false);
    for (const auto & data_dir : dirs)
    {
      const auto path = MooseUtils::pathjoin(data_dir, "data", relative_path);
      if (MooseUtils::checkFileReadable(path, false, false, false))
      {
        if (param)
          _parent.paramInfo(
              *param, "Data file '", path, "' found in an installed app distribution.");
        else
          mooseInfo("Data file '", path, "' found in an installed app distribution.");
        return path;
      }
    }
  }
  for (const auto & data_dir : Registry::getRegistry().getDataFilePaths())
  {
    const auto path = MooseUtils::pathjoin(data_dir, relative_path);
    if (MooseUtils::checkFileReadable(path, false, false, false))
    {
      if (param)
        _parent.paramInfo(*param, "Data file '", path, "' found in a source repository.");
      else
        mooseInfo("Data file '", path, "' found in a source repository.");
      return path;
    }
  }
  mooseException(param ? _parent.parameters().inputLocation(*param) : _parent.name(),
                 ": Unable to find data file '",
                 relative_path,
                 "' anywhere");
}
getDefaultExecFlagEnum()
ExecFlagEnum Output::getDefaultExecFlagEnum () static inherited
Return an ExecFlagEnum object with the available execution flags for Output objects.
Definition at line 92 of file Output.C.
{
  ExecFlagEnum exec_enum = MooseUtils::getDefaultExecFlagEnum();
  exec_enum.addAvailableFlags(EXEC_FAILED);
  return exec_enum;
}
Referenced by CommonOutputAction::validParams(), and Output::validParams().
getDefaultPostprocessorValueByName()
PostprocessorValue PostprocessorInterface::getDefaultPostprocessorValueByName (const PostprocessorName & name) const private inherited
Returns
The default value stored in the PostprocessorName name.
Definition at line 96 of file PostprocessorInterface.C.
{
  mooseAssert(isDefaultPostprocessorValueByName(name), "Not a default value");
  Real real_value = -std::numeric_limits<Real>::max();
  std::istringstream ss(name);
  ss >> real_value;
  return real_value;
}
Referenced by PostprocessorInterface::getPostprocessorValueInternal().
getElementalVariableOutput()
const std::set< std::string > & AdvancedOutput::getElementalVariableOutput ()
The list of elemental nonlinear variables names that are set for output.
Returns
A vector of strings containing the names of the nonlinear variables for output
See also
hasElementalVariableOutput
Definition at line 817 of file AdvancedOutput.C.
{
  return _execute_data["elemental"].output;
}
Referenced by Nemesis::output(), and Exodus::outputElementalVariables().
getExecuteOnEnum()
const ExecFlagEnum & SetupInterface::getExecuteOnEnum () const inherited
Return the execute on MultiMooseEnum for this object.
Definition at line 65 of file SetupInterface.C.
{
  return _execute_enum;
}
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), MultiAppTransfer::checkMultiAppExecuteOn(), IntegralPreservingFunctionIC::initialSetup(), MultiAppConservativeTransfer::initialSetup(), Terminator::initialSetup(), ElementReporter::shouldStore(), GeneralReporter::shouldStore(), and NodalReporter::shouldStore().
getFileNumber()
unsigned int FileOutput::getFileNumber () inherited
Return the current file number for this outputter.
This method was implemented for the MultiApp system, particularly when reseting an application and a new output file is desired after the reset.
Definition at line 181 of file FileOutput.C.
{
  return _file_num;
}
Referenced by OutputWarehouse::getFileNumbers().
getFunction()
const Function & FunctionInterface::getFunction (const std::string & name) const inherited
Get a function with a given name.
Parameters
name The name of the parameter key of the function to retrieve
Returns
The function with name associated with the parameter 'name'
Definition at line 30 of file FunctionInterface.C.
{
  return _fni_feproblem.getFunction(_fni_params.get<FunctionName>(name), _fni_tid);
}
Referenced by FunctionDT::FunctionDT(), and Output::Output().
getFunctionByName()
const Function & FunctionInterface::getFunctionByName (const FunctionName & name) const inherited
Get a function with a given name.
Parameters
name The name of the function to retrieve
Returns
The function with name 'name'
Definition at line 36 of file FunctionInterface.C.
{
  return _fni_feproblem.getFunction(name, _fni_tid);
}
Referenced by ArrayBodyForce::ArrayBodyForce(), ArrayFunctionIC::ArrayFunctionIC(), CompositeFunction::CompositeFunction(), FunctionArrayAux::FunctionArrayAux(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionRankTwoTensorTempl< is_ad >::GenericFunctionRankTwoTensorTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), LinearCombinationFunction::LinearCombinationFunction(), and LineFunctionSampler::LineFunctionSampler().
getMooseApp()
MooseApp & MooseBase::getMooseApp () const inline inherited
Get the MooseApp this class is associated with.
Definition at line 35 of file MooseBase.h.
{ return _app; }
Referenced by ReporterTransferInterface::checkHasReporterValue(), Coupleable::checkWritableVar(), MooseBaseParameterInterface::connectControllableParams(), Coupleable::Coupleable(), MortarData::createMortarInterface(), EigenProblem::doFreeNonlinearPowerIterations(), Terminator::execute(), FEProblemSolve::FEProblemSolve(), SolutionInvalidInterface::flagInvalidSolutionInternal(), MaterialPropertyInterface::MaterialPropertyInterface(), MooseVariableDataFV< OutputType >::MooseVariableDataFV(), ProgressOutput::output(), MooseBaseParameterInterface::paramError(), PetscOutputInterface::petscLinearOutput(), PetscOutputInterface::petscNonlinearOutput(), PetscOutputInterface::PetscOutputInterface(), PostprocessorInterface::postprocessorsAdded(), MultiApp::preTransfer(), Reporter::Reporter(), ReporterInterface::reportersAdded(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
getNodalVariableOutput()
const std::set< std::string > & AdvancedOutput::getNodalVariableOutput ()
The list of nodal nonlinear variables names that are set for output.
Returns
A vector of strings containing the names of the nodal nonlinear variables for output
Note: The list returned by this will contain the names of both elemental and nodal variable names if 'elemental_as_nodal = true' in the input file. The libMesh output system (EquationSystems::build_solution_vector) performs the correct action within the solution vector by setting the nodal values as the average of the values for each of the element that the node shares.
See also
hasNodalVariableOutput
Definition at line 805 of file AdvancedOutput.C.
{
  return _execute_data["nodal"].output;
}
Referenced by Nemesis::output(), and Exodus::outputNodalVariables().
getOutputTime()
Real PetscOutput::getOutputTime () protected virtual inherited
Get the time that will be used for stream/file outputting.
This method is intended to override the output given by time() for cases that do not conform to the linear, nonlinear, time step pattern. For example, this can be used for optimization or fixed point iteration solves. If you override this method for your application, replace time() calls with getOutputTime() calls and ensure output consistency.
Definition at line 265 of file PetscOutput.C.
{
  return time();
}
Referenced by Nemesis::output(), Tecplot::output(), Exodus::outputEmptyTimestep(), Exodus::outputNodalVariables(), TableOutput::outputPostprocessors(), TableOutput::outputReporter(), TableOutput::outputScalarVariables(), and Console::writeTimestepInformation().
getOutputTypes()
MultiMooseEnum AdvancedOutput::getOutputTypes () static private
Get the supported types of output (e.g., postprocessors, etc.)
Definition at line 105 of file AdvancedOutput.C.
{
  return MultiMooseEnum("nodal=0 elemental=1 scalar=2 postprocessor=3 vector_postprocessor=4 "
                        "input=5 system_information=6 reporter=7");
}
Referenced by enableOutputTypes().
getParam() [1/2]
template<typename T > const T & MooseBaseParameterInterface::getParam (const std::string & name) const inherited
Retrieve a parameter for the object.
Parameters
name The name of the parameter
Returns
The value of the parameter
Definition at line 200 of file MooseBaseParameterInterface.h.
{
  return InputParameters::getParamHelper(name, _pars, static_cast<T *>(0));
}
Referenced by AddGeneralReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddPeriodicBCAction::act(), CreateDisplacedProblemAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), ConstraintWarehouse::addObject(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), ADNodalKernel::ADNodalKernel(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), PiecewiseTabularBase::buildFromJSON(), Console::Console(), FEProblemBase::createTagSolutions(), AccumulateReporter::declareLateValues(), DerivativeParsedMaterialTempl< is_ad >::DerivativeParsedMaterialTempl(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EigenKernel::EigenKernel(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), GenericConstantRankTwoTensorTempl< is_ad >::GenericConstantRankTwoTensorTempl(), MooseApp::getCheckpointDirectories(), ExecutorInterface::getExecutor(), init(), IterationAdaptiveDT::init(), TimeSequenceStepper::init(), AttribThread::initFrom(), AttribSysNum::initFrom(), AttribResidualObject::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), Console::initialSetup(), IterationAdaptiveDT::limitDTToPostprocessorValue(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MortarConsumerInterface::MortarConsumerInterface(), NestedDivision::NestedDivision(), ConsoleUtils::outputExecutionInformation(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedMaterialTempl< is_ad >::ParsedMaterialTempl(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), ParsedODEKernel::ParsedODEKernel(), ParsedPostprocessor::ParsedPostprocessor(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), Moose::FV::setInterpolationMethod(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), TimePeriod::TimePeriod(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and VectorOfPostprocessors::VectorOfPostprocessors().
getParam() [2/2]
template<typename T1 , typename T2 > std::vector< std::pair< T1, T2 > > MooseBaseParameterInterface::getParam (const std::string & param1, const std::string & param2) const inherited
Retrieve two parameters and provide pair of parameters for the object.
Parameters
param1 The name of first parameter
param2 The name of second parameter
Returns
Vector of pairs of first and second parameters
Definition at line 257 of file MooseBaseParameterInterface.h.
{
  return _pars.get<T1, T2>(param1, param2);
}
getPostprocessorName()
const PostprocessorName & PostprocessorInterface::getPostprocessorName (const std::string & param_name, const unsigned int index = 0) const inherited
Get the name of a postprocessor.
This can only be used if the postprocessor parameter does not have a default value set (see isDefaultPostprocessorValue()), in which case the "name" is actually the default value.
Parameters
param_name The name of the Postprocessor parameter
index The index of the Postprocessor
Returns
The name of the given Postprocessor
Definition at line 185 of file PostprocessorInterface.C.
{
  return getPostprocessorNameInternal(param_name, index, /* allow_default_value = */ false);
}
Referenced by EigenKernel::EigenKernel().
getPostprocessorNameInternal()
const PostprocessorName & PostprocessorInterface::getPostprocessorNameInternal (const std::string & param_name, const unsigned int index, const bool allow_default_value = true) const private inherited
Internal method for getting the PostprocessorName associated with a paremeter.
Needed in order to allow the return of a name that is a default value.
Definition at line 192 of file PostprocessorInterface.C.
{
  checkParam(param_name, index);
  const auto & name = _ppi_params.isType<PostprocessorName>(param_name)
                          ? _ppi_params.get<PostprocessorName>(param_name)
                          : _ppi_params.get<std::vector<PostprocessorName>>(param_name)[index];
  if (!allow_default_value && isDefaultPostprocessorValueByName(name))
  {
    std::stringstream oss;
    oss << "Cannot get the name associated with PostprocessorName parameter \"" << param_name
        << "\"";
    if (index)
      oss << " at index " << index;
    oss << ",\nbecause said parameter is a default Postprocessor value.";
    _ppi_moose_object.paramError(param_name, oss.str());
  }
  return name;
}
Referenced by PostprocessorInterface::getPostprocessorName(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), and PostprocessorInterface::isDefaultPostprocessorValue().
getPostprocessorOutput()
const std::set< std::string > & AdvancedOutput::getPostprocessorOutput ()
The list of postprocessor names that are set for output.
Returns
A vector of strings containing the names of the postprocessor variables for output
See also
hasPostprocessorOutput
Definition at line 841 of file AdvancedOutput.C.
{
  return _execute_data["postprocessors"].output;
}
Referenced by CSV::initialSetup(), Exodus::outputPostprocessors(), Nemesis::outputPostprocessors(), and TableOutput::outputPostprocessors().
getPostprocessorValue()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValue (const std::string & param_name, const unsigned int index = 0) const inherited
doco-normal-methods-begin Retrieve the value of a Postprocessor or one of it's old or older values
Parameters
param_name The name of the Postprocessor parameter (see below)
index The index of the Postprocessor
Returns
A reference to the desired value
The name required by this method is the name that is hard-coded into your source code. For example, if you have a Kernel that requires a Postprocessor you may have an input file with "pp = my_pp", this function requires the "pp" name as input (see .../moose_test/functions/PostprocessorFunction.C)
see getPostprocessorValueByName getPostprocessorValueOldByName getPostprocessorValueOlderByName
Definition at line 36 of file PostprocessorInterface.C.
{
  return getPostprocessorValueInternal(param_name, index, /* t_index = */ 0);
}
Referenced by EigenKernel::EigenKernel(), FunctionValuePostprocessor::FunctionValuePostprocessor(), LinearCombinationPostprocessor::LinearCombinationPostprocessor(), ParsedPostprocessor::ParsedPostprocessor(), and PicardSolve::PicardSolve().
getPostprocessorValueByName()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueByName (const PostprocessorName & name) const virtual inherited
Retrieve the value of the Postprocessor.
Parameters
name Postprocessor name (see below)
Returns
A reference to the desired value
The name required by this method is the name defined in the input file. For example, if you have a Kernel that requires a Postprocessor you may have an input file with "pp = my_pp", this method requires the "my_pp" name as input (see .../moose_test/functions/PostprocessorFunction.C)
see getPostprocessorValue getPostprocessorValueOld getPostprocessorValueOlder
Definition at line 57 of file PostprocessorInterface.C.
{
  return getPostprocessorValueByNameInternal(name, /* t_index = */ 0);
}
Referenced by EigenKernel::EigenKernel(), PIDTransientControl::execute(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), ParsedODEKernel::ParsedODEKernel(), PicardSolve::savePostprocessorValues(), SecantSolve::savePostprocessorValues(), SteffensenSolve::savePostprocessorValues(), Terminator::Terminator(), PicardSolve::transformPostprocessors(), SecantSolve::transformPostprocessors(), SteffensenSolve::transformPostprocessors(), and VectorOfPostprocessors::VectorOfPostprocessors().
getPostprocessorValueByNameInternal()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueByNameInternal (const PostprocessorName & name, std::size_t t_index) const private inherited
Definition at line 246 of file PostprocessorInterface.C.
{
  mooseAssert(t_index < 3, "Invalid time index");
  mooseAssert(!isDefaultPostprocessorValueByName(name), "Should not be default");
  // If all pps have been added, we can check for existance
  if (postprocessorsAdded() && !hasPostprocessorByName(name))
    _ppi_moose_object.mooseError("A Postprocessor with the name \"", name, "\" was not found.");
  if (t_index == 0)
    addPostprocessorDependencyHelper(name);
  return _ppi_feproblem.getReporterData().getReporterValue<PostprocessorValue>(
      PostprocessorReporterName(name), _ppi_moose_object, REPORTER_MODE_ROOT, t_index);
}
Referenced by PostprocessorInterface::getPostprocessorValueByName(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::getPostprocessorValueOldByName(), and PostprocessorInterface::getPostprocessorValueOlderByName().
getPostprocessorValueInternal()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueInternal (const std::string & param_name, unsigned int index, std::size_t t_index) const private inherited
Internal methods for getting Postprocessor values.
Definition at line 218 of file PostprocessorInterface.C.
{
  const auto & name = getPostprocessorNameInternal(param_name, index);
  // If the Postprocessor is a default value (either set by addParam or set to a constant
  // value by the user in input/an action), we covert the name to a value, store said
  // value locally, and return it so that it fits in with the rest of the interface
  // (needing a reference to a value)
  if (isDefaultPostprocessorValueByName(name))
  {
    const auto value = getDefaultPostprocessorValueByName(name);
    const auto & value_ref =
        *_default_values.emplace(name, std::make_unique<PostprocessorValue>(value))
             .first->second; // first is inserted pair, second is value in pair
    mooseAssert(value == value_ref, "Inconsistent default value");
    return value_ref;
  }
  // If not a default and all pps have been added, we check check for existance
  else if (postprocessorsAdded() && !hasPostprocessorByName(name))
    _ppi_moose_object.paramError(
        param_name, "A Postprocessor with the name \"", name, "\" was not found.");
  return getPostprocessorValueByNameInternal(name, t_index);
}
Referenced by PostprocessorInterface::getPostprocessorValue(), PostprocessorInterface::getPostprocessorValueOld(), and PostprocessorInterface::getPostprocessorValueOlder().
getPostprocessorValueOld()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOld (const std::string & param_name, const unsigned int index = 0) const inherited
Definition at line 43 of file PostprocessorInterface.C.
{
  return getPostprocessorValueInternal(param_name, index, /* t_index = */ 1);
}
getPostprocessorValueOldByName()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOldByName (const PostprocessorName & name) const inherited
Definition at line 63 of file PostprocessorInterface.C.
{
  return getPostprocessorValueByNameInternal(name, /* t_index = */ 1);
}
Referenced by EigenKernel::EigenKernel().
getPostprocessorValueOlder()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOlder (const std::string & param_name, const unsigned int index = 0) const inherited
Definition at line 50 of file PostprocessorInterface.C.
{
  return getPostprocessorValueInternal(param_name, index, /* t_index = */ 2);
}
getPostprocessorValueOlderByName()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOlderByName (const PostprocessorName & name) const inherited
Definition at line 69 of file PostprocessorInterface.C.
{
  return getPostprocessorValueByNameInternal(name, /* t_index = */ 2);
}
getRenamedParam()
template<typename T > const T & MooseBaseParameterInterface::getRenamedParam (const std::string & old_name, const std::string & new_name) const inherited
Retrieve a renamed parameter for the object.
This helper makes sure we check both names before erroring, and that only one parameter is passed to avoid silent errors
Parameters
old_name the old name for the parameter
new_name the new name for the parameter
Definition at line 207 of file MooseBaseParameterInterface.h.
{
  // this enables having a default on the new parameter but bypassing it with the old one
  // Most important: accept new parameter
  if (isParamSetByUser(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Second most: accept old parameter
  else if (isParamValid(old_name) && !isParamSetByUser(new_name))
    return InputParameters::getParamHelper(old_name, _pars, static_cast<T *>(0));
  // Third most: accept default for new parameter
  else if (isParamValid(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Refuse: no default, no value passed
  else if (!isParamValid(old_name) && !isParamValid(new_name))
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' is being retrieved without being set.\n"
               "Did you misspell it?");
  // Refuse: both old and new parameters set by user
  else
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' may not be provided alongside former parameter '" + old_name + "'");
}
getReporterName()
const ReporterName & ReporterInterface::getReporterName (const std::string & param_name) const protected inherited
Returns
The ReporterName associated with the parametre param_name.
Performs error checking to mak sure that the parameter is valid.
Definition at line 49 of file ReporterInterface.C.
{
  if (!_ri_params.isParamValid(param_name))
    _ri_moose_object.mooseError(
        "When getting a Reporter, failed to get a parameter with the name \"",
        param_name,
        "\".",
        "\n\nKnown parameters:\n",
        _ri_moose_object.parameters());
  if (_ri_params.isType<ReporterName>(param_name))
    return _ri_params.get<ReporterName>(param_name);
  _ri_moose_object.mooseError("Supplied parameter with name \"",
                              param_name,
                              "\" of type \"",
                              _ri_params.type(param_name),
                              "\" is not an expected type for getting a Reporter.\n\n",
                              "The expected type is \"ReporterName\".");
}
Referenced by ReporterInterface::getReporterValue(), and ReporterInterface::hasReporterValue().
getReporterOutput()
const std::set< std::string > & AdvancedOutput::getReporterOutput ()
The list of Reporter names that are set for output.
Returns
A vector containing the names of the Reporter names for output
See also
hasReporterOutput
Definition at line 865 of file AdvancedOutput.C.
{
  return _execute_data["reporters"].output;
}
Referenced by CSV::initialSetup(), Exodus::outputReporters(), JSONOutput::outputReporters(), and TableOutput::outputReporters().
getReporterValue() [1/2]
template<typename T > const T & ReporterInterface::getReporterValue (const std::string & param_name, const std::size_t time_index = 0) protected inherited
doco-normal-methods-begin Returns read-only reference to a Reporter value that is provided by an input parameter.
Template Parameters
T The C++ type of the Reporter value being consumed
Parameters
param_name The name of the parameter that gives the name of the Reporter, which must be a ReporterName parameter (i.e., getParam<ReporterName>(param_name)).
mode The mode that the object will consume the Reporter value @pararm time_index (optional) If zero is provided the current value is returned. Use a positive index to return previous values (1 = older, 2 = older, etc.). The maximum number of old values is dictated by the ReporterData object.
Definition at line 133 of file ReporterInterface.h.
{
  return getReporterValue<T>(param_name, REPORTER_MODE_UNSET, time_index);
}
getReporterValue() [2/2]
template<typename T > const T & ReporterInterface::getReporterValue (const std::string & param_name, ReporterMode mode, const std::size_t time_index = 0) protected inherited
Definition at line 140 of file ReporterInterface.h.
{
  const auto & reporter_name = getReporterName(param_name);
  possiblyCheckHasReporter<T>(reporter_name, param_name);
  return getReporterValueByName<T>(reporter_name, mode, time_index);
}
getReporterValueByName() [1/2]
template<typename T > const T & ReporterInterface::getReporterValueByName (const ReporterName & reporter_name, const std::size_t time_index = 0) protected inherited
Returns read-only reference to a Reporter value that is provided by name directly.
Template Parameters
T The C++ type of the Reporter value being consumed
Parameters
reporter_name A ReporterName object that for the desired Reporter value.
mode The mode that the object will consume the Reporter value @pararm time_index (optional) If zero is provided the current value is returned. Use a positive index to return previous values (1 = older, 2 = older, etc.). The maximum number of old values is dictated by the ReporterData object.
Definition at line 153 of file ReporterInterface.h.
{
  return getReporterValueByName<T>(reporter_name, REPORTER_MODE_UNSET, time_index);
}
getReporterValueByName() [2/2]
template<typename T > const T & ReporterInterface::getReporterValueByName (const ReporterName & reporter_name, ReporterMode mode, const std::size_t time_index = 0) protected inherited
Definition at line 161 of file ReporterInterface.h.
{
  possiblyCheckHasReporter<T>(reporter_name);
  addReporterDependencyHelper(reporter_name);
  return _ri_reporter_data.getReporterValue<T>(reporter_name, _ri_moose_object, mode, time_index);
}
getRestartableData()
template<typename T , typename... Args> const T & Restartable::getRestartableData (const std::string & data_name) const protected inherited
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
Forwarded arguments are not allowed in this case because we assume that the object is restarted and we won't need different constructors to initialize it.
NOTE: This returns a const reference! Make sure you store it in a const reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
Definition at line 287 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, nullptr).get();
}
getScalarOutput()
const std::set< std::string > & AdvancedOutput::getScalarOutput ()
The list of scalar variables names that are set for output.
Returns
A vector of strings containing the names of the scalar variables for output
See also
hasScalarVariableOutput
Definition at line 829 of file AdvancedOutput.C.
{
  return _execute_data["scalars"].output;
}
Referenced by CSV::initialSetup(), Exodus::outputScalarVariables(), Nemesis::outputScalarVariables(), and TableOutput::outputScalarVariables().
getScatterVectorPostprocessorValue()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValue (const std::string & param_name, const std::string & vector_name) const inherited
Return the scatter value for the post processor.
This is only valid when you expec the vector to be of lenghth "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
param_name The name of the parameter holding the vpp name
vector_name The name of the vector
Returns
The reference to the current scatter value
Definition at line 106 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getScatterVectorPostprocessorValueByName(getVectorPostprocessorName(param_name),
                                                  vector_name);
}
getScatterVectorPostprocessorValueByName()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValueByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
Return the scatter value for the post processor.
This is only valid when you expec the vector to be of lenghth "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
name The name of the VectorPostprocessor
vector_name The name of the vector
Returns
The reference to the current scatter value
Definition at line 115 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorContextByNameHelper(name, vector_name).getScatterValue();
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValue().
getScatterVectorPostprocessorValueOld()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValueOld (const std::string & param_name, const std::string & vector_name) const inherited
Return the old scatter value for the post processor.
This is only valid when you expec the vector to be of lenghth "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
param_name The name of the parameter holding the vpp name
vector_name The name of the vector
Returns
The reference to the old scatter value
Definition at line 122 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getScatterVectorPostprocessorValueOldByName(getVectorPostprocessorName(param_name),
                                                     vector_name);
}
getScatterVectorPostprocessorValueOldByName()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValueOldByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
Return the old scatter value for the post processor.
This is only valid when you expect the vector to be of length "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
name The name of the VectorPostprocessor
vector_name The name of the vector
Returns
The reference to the old scatter value
Definition at line 131 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorContextByNameHelper(name, vector_name).getScatterValueOld();
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValueOld().
getSyncTimes()
const std::set< Real > & Output::getSyncTimes () inline inherited
Definition at line 142 of file Output.h.
{ return _sync_times; }
getVectorPostprocessorByNameHelper()
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorByNameHelper (const VectorPostprocessorName & name, const std::string & vector_name, bool broadcast, std::size_t t_index) const private inherited
Helper function for extracting VPP data from ReporterData object.
Definition at line 269 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessorByName(name, vector_name);
  addVectorPostprocessorDependencyHelper(name);
  const ReporterMode mode = broadcast ? REPORTER_MODE_REPLICATED : REPORTER_MODE_ROOT;
  return _vpi_feproblem.getReporterData().getReporterValue<VectorPostprocessorValue>(
      VectorPostprocessorReporterName(name, vector_name), _vpi_moose_object, mode, t_index);
}
Referenced by VectorPostprocessorInterface::getVectorPostprocessorValueByName(), and VectorPostprocessorInterface::getVectorPostprocessorValueOldByName().
getVectorPostprocessorContextByNameHelper()
const VectorPostprocessorContext< VectorPostprocessorValue > & VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper (const VectorPostprocessorName & name, const std::string & vector_name) const private inherited
Helper for getting the VPP context that handles scatter values.
Definition at line 284 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessorByName(name, vector_name);
  addVectorPostprocessorDependencyHelper(name);
  // The complete name of the store Reporter value
  const VectorPostprocessorReporterName r_name(name, vector_name);
  // Indicate the scatter value is desired, so the the VectorPostprocessorContext will do scatter
  _vpi_feproblem.getReporterData().getReporterValue<VectorPostprocessorValue>(
      r_name, _vpi_moose_object, REPORTER_MODE_VPP_SCATTER, 0);
  // Retrieve the VectorPostprocessorContext which contains the scattered value to be referenced
  const auto & context = _vpi_feproblem.getReporterData().getReporterContextBase(r_name);
  auto vpp_context_ptr =
      dynamic_cast<const VectorPostprocessorContext<VectorPostprocessorValue> *>(&context);
  mooseAssert(vpp_context_ptr, "Failed to get the VectorPostprocessorContext");
  return *vpp_context_ptr;
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValueByName(), and VectorPostprocessorInterface::getScatterVectorPostprocessorValueOldByName().
getVectorPostprocessorName()
const VectorPostprocessorName & VectorPostprocessorInterface::getVectorPostprocessorName (const std::string & param_name) const inherited
Get the name of a VectorPostprocessor associated with a parameter.
Parameters
param_name The name of the VectorPostprocessor parameter
Returns
The name of the given VectorPostprocessor
Definition at line 203 of file VectorPostprocessorInterface.C.
{
  const auto & params = _vpi_moose_object.parameters();
  if (!params.isParamValid(param_name))
    _vpi_moose_object.mooseError(
        "When getting a VectorPostprocessor, failed to get a parameter with the name \"",
        param_name,
        "\".",
        "\n\nKnown parameters:\n",
        _vpi_moose_object.parameters());
  if (!params.isType<VectorPostprocessorName>(param_name))
    _vpi_moose_object.mooseError(
        "Supplied parameter with name \"",
        param_name,
        "\" of type \"",
        params.type(param_name),
        "\" is not an expected type for getting a VectorPostprocessor.\n\n",
        "The allowed type is \"VectorPostprocessorName\".");
  return params.get<VectorPostprocessorName>(param_name);
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValue(), VectorPostprocessorInterface::getScatterVectorPostprocessorValueOld(), VectorPostprocessorInterface::getVectorPostprocessorValue(), VectorPostprocessorInterface::getVectorPostprocessorValueOld(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::isVectorPostprocessorDistributed(), and VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor().
getVectorPostprocessorOutput()
const std::set< std::string > & AdvancedOutput::getVectorPostprocessorOutput ()
The list of VectorPostprocessor names that are set for output.
Returns
A vector of strings containing the names of the VectorPostprocessor variables for output
See also
hasVectorPostprocessorOutput
Definition at line 853 of file AdvancedOutput.C.
{
  return _execute_data["vector_postprocessors"].output;
}
Referenced by CSV::initialSetup(), TableOutput::outputReporters(), TableOutput::outputVectorPostprocessors(), and XMLOutput::outputVectorPostprocessors().
getVectorPostprocessorValue() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValue (const std::string & param_name, const std::string & vector_name) const inherited
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the value of a VectorPostprocessor
Parameters
param_name The name of the VectorPostprocessor parameter (see below)
vector_name The name of the particular vector you want.
Returns
A reference to the desired value
The name required by this method is the name that is hard-coded into your source code. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this function requires the "pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValueOld getVectorPostprocessorValueByName getVectorPostprocessorValueOldByName
Definition at line 36 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueByName(getVectorPostprocessorName(param_name), vector_name);
}
getVectorPostprocessorValue() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValue (const std::string & param_name, const std::string & vector_name, bool needs_broadcast) const inherited
Retrieve the value of a VectorPostprocessor.
Parameters
param_name The name of the VectorPostprocessor parameter (see below)
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
A reference to the desired value
The name required by this method is the name that is hard-coded into your source code. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this function requires the "pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValueOld getVectorPostprocessorValueByName getVectorPostprocessorValueOldByName
Definition at line 66 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueByName(
      getVectorPostprocessorName(param_name), vector_name, needs_broadcast);
}
getVectorPostprocessorValueByName() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the value of the VectorPostprocessor
Parameters
name VectorPostprocessor name (see below)
vector_name The name of the particular vector you want.
Returns
A reference to the desired value
The name required by this method is the name defined in the input file. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this method requires the "my_pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValue getVectorPostprocessorValueOldByName getVectorPostprocessorValueByName
Definition at line 44 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(name, vector_name, _broadcast_by_default, 0);
}
Referenced by VectorPostprocessorInterface::getVectorPostprocessorValue().
getVectorPostprocessorValueByName() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueByName (const VectorPostprocessorName & name, const std::string & vector_name, bool needs_broadcast) const inherited
Retrieve the value of the VectorPostprocessor.
Parameters
name VectorPostprocessor name (see below)
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
A reference to the desired value
The name required by this method is the name defined in the input file. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this method requires the "my_pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValue getVectorPostprocessorValueOldByName getVectorPostprocessorValueByName
Definition at line 76 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(
      name, vector_name, needs_broadcast || _broadcast_by_default, 0);
}
getVectorPostprocessorValueOld() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOld (const std::string & param_name, const std::string & vector_name) const inherited
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the old value of a VectorPostprocessor
Parameters
param_name The name of the VectorPostprocessor parameter
vector_name The name of the particular vector you want.
Returns
The value of the VectorPostprocessor
see getVectorPostprocessorValue
Definition at line 51 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueOldByName(getVectorPostprocessorName(param_name), vector_name);
}
getVectorPostprocessorValueOld() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOld (const std::string & param_name, const std::string & vector_name, bool needs_broadcast) const inherited
Retrieve the old value of a VectorPostprocessor.
Parameters
param_name The name of the VectorPostprocessor parameter
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
The value of the VectorPostprocessor
see getVectorPostprocessorValue
Definition at line 86 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueOldByName(
      getVectorPostprocessorName(param_name), vector_name, needs_broadcast);
}
getVectorPostprocessorValueOldByName() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOldByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the old value of a VectorPostprocessor
Parameters
name The name of the VectorPostprocessor
vector_name The name of the particular vector you want.
Returns
The value of the VectorPostprocessor
If within the validParams for the object the addVectorPostprocessorParam was called this method will retun a reference to the default value specified in the call to the addVectorPostprocessorParam function if the postVectorPostprocessor does not exist.
see getVectorPostprocessorValueByName
Definition at line 59 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(name, vector_name, _broadcast_by_default, 1);
}
Referenced by VectorPostprocessorInterface::getVectorPostprocessorValueOld().
getVectorPostprocessorValueOldByName() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOldByName (const VectorPostprocessorName & name, const std::string & vector_name, bool needs_broadcast) const inherited
Retrieve the old value of a VectorPostprocessor.
Parameters
name The name of the VectorPostprocessor
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
The value of the VectorPostprocessor
If within the validParams for the object the addVectorPostprocessorParam was called this method will retun a reference to the default value specified in the call to the addVectorPostprocessorParam function if the postVectorPostprocessor does not exist.
see getVectorPostprocessorValueByName
Definition at line 96 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(
      name, vector_name, needs_broadcast || _broadcast_by_default, 1);
}
hasElementalVariableOutput()
bool AdvancedOutput::hasElementalVariableOutput ()
Returns true if there exists elemental nonlinear variables for output.
Returns
True if nonlinear variable output exists
See also
getElementalVariableOutput
Definition at line 811 of file AdvancedOutput.C.
{
  return hasOutputHelper("elemental");
}
Referenced by Exodus::initialSetup().
hasFunction()
bool FunctionInterface::hasFunction (const std::string & param_name) const inherited
Determine if the function exists.
Parameters
param_name The name of the function parameter
index The index of the function
Returns
True if the function exists
Definition at line 42 of file FunctionInterface.C.
{
  return hasFunctionByName(_fni_params.get<FunctionName>(param_name));
}
hasFunctionByName()
bool FunctionInterface::hasFunctionByName (const FunctionName & name) const inherited
Determine if the function exists.
Parameters
name The name of the function
Returns
True if the function exists
Definition at line 48 of file FunctionInterface.C.
{
  return _fni_feproblem.hasFunction(name, _fni_tid);
}
Referenced by FunctionInterface::hasFunction().
hasNodalVariableOutput()
bool AdvancedOutput::hasNodalVariableOutput ()
Returns true if there exists nodal nonlinear variables for output.
Returns
True if nonlinear variable output exists
See also
getNodalVariableOutput
Definition at line 799 of file AdvancedOutput.C.
{
  return hasOutputHelper("nodal");
}
Referenced by Exodus::initialSetup(), and Exodus::outputElementalVariables().
hasOutput() [1/2]
bool AdvancedOutput::hasOutput () virtual
Returns true if any of the other has methods return true.
Definition at line 383 of file AdvancedOutput.C.
{
  // Test that variables exist for output AND that output execution flags are valid
  for (const auto & it : _execute_data)
    if (!(it.second).output.empty() && _advanced_execute_on.contains(it.first) &&
        _advanced_execute_on[it.first].isValid())
      return true;
  // Test execution flags for non-variable output
  if (_advanced_execute_on.contains("system_information") &&
      _advanced_execute_on["system_information"].isValid())
    return true;
  if (_advanced_execute_on.contains("input") && _advanced_execute_on["input"].isValid())
    return true;
  return false;
}
Referenced by Exodus::initialSetup(), and shouldOutput().
hasOutput() [2/2]
bool AdvancedOutput::hasOutput (const ExecFlagType & type)
Tests that any output exist for the given output type.
See also
Exodus
Definition at line 371 of file AdvancedOutput.C.
{
  // If any of the component outputs are true, then there is some output to perform
  for (const auto & it : _advanced_execute_on)
    if (wantOutput(it.first, type))
      return true;
  // There is nothing to output
  return false;
}
hasOutputHelper()
bool AdvancedOutput::hasOutputHelper (const std::string & name) private
Helper method for checking if output types exists.
Parameters
name The name of the output type to test (e.g., postprocessors)
Definition at line 792 of file AdvancedOutput.C.
{
  return !_execute_data[name].output.empty() && _advanced_execute_on.contains(name) &&
         _advanced_execute_on[name].isValid() && !_advanced_execute_on[name].contains("none");
}
Referenced by hasElementalVariableOutput(), hasNodalVariableOutput(), hasPostprocessorOutput(), hasReporterOutput(), hasScalarOutput(), and hasVectorPostprocessorOutput().
hasPostprocessor()
bool PostprocessorInterface::hasPostprocessor (const std::string & param_name, const unsigned int index = 0) const inherited
Determine if the Postprocessor data exists.
Parameters
param_name The name of the Postprocessor parameter
index The index of the Postprocessor
Returns
True if the Postprocessor exists
See also
hasPostprocessorByName getPostprocessorValue
Definition at line 107 of file PostprocessorInterface.C.
{
  if (!postprocessorsAdded())
    _ppi_moose_object.mooseError(
        "Cannot call hasPostprocessor() until all Postprocessors have been constructed.");
  return hasPostprocessorByName(getPostprocessorNameInternal(param_name, index));
}
hasPostprocessorByName()
bool PostprocessorInterface::hasPostprocessorByName (const PostprocessorName & name) const inherited
Determine if the Postprocessor data exists.
Parameters
name The name of the Postprocessor
Returns
True if the Postprocessor exists
See also
hasPostprocessor getPostprocessorValueByName
Definition at line 118 of file PostprocessorInterface.C.
{
  if (!postprocessorsAdded())
    _ppi_moose_object.mooseError(
        "Cannot call hasPostprocessorByName() until all Postprocessors have been constructed.");
  return _ppi_feproblem.getReporterData().hasReporterValue<PostprocessorValue>(
      PostprocessorReporterName(name));
}
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), initShowHideLists(), Exodus::outputReporters(), and TableOutput::outputReporters().
hasPostprocessorOutput()
bool AdvancedOutput::hasPostprocessorOutput ()
Returns true if there exists postprocessors for output.
Returns
True if postprocessor output exists
See also
getPostprocessorOutput
Definition at line 835 of file AdvancedOutput.C.
{
  return hasOutputHelper("postprocessors");
}
Referenced by Exodus::initialSetup().
hasReporterOutput()
bool AdvancedOutput::hasReporterOutput ()
Returns true if there exists Reporter for output.
Returns
True if Reporter output exists
See also
getReporterOutput
Definition at line 859 of file AdvancedOutput.C.
{
  return hasOutputHelper("reporters");
}
hasReporterValue() [1/2]
bool ReporterInterface::hasReporterValue (const std::string & param_name) const protected inherited
Return True if the Reporter value exists.
Template Parameters
T The C++ type of the Reporter value being consumed
Parameters
reporter_name A ReporterName object that for the desired Reporter value.
Definition at line 29 of file ReporterInterface.C.
{
  if (!reportersAdded())
    _ri_moose_object.mooseError(
        "Cannot call hasReporterValue() until all Reporters have been constructed.");
  return hasReporterValueByName(getReporterName(param_name));
}
hasReporterValue() [2/2]
template<typename T > bool ReporterInterface::hasReporterValue (const std::string & param_name) const protected inherited
Definition at line 174 of file ReporterInterface.h.
{
  if (!reportersAdded())
    _ri_moose_object.mooseError(
        "Cannot call hasReporterValue() until all Reporters have been constructed.");
  return hasReporterValueByName<T>(getReporterName(param_name));
}
hasReporterValueByName() [1/2]
bool ReporterInterface::hasReporterValueByName (const ReporterName & reporter_name) const protected inherited
Definition at line 39 of file ReporterInterface.C.
{
  if (!reportersAdded())
    _ri_moose_object.mooseError(
        "Cannot call hasReporterValueByName() until all Reporters have been constructed.");
  return _ri_reporter_data.hasReporterValue(reporter_name);
}
Referenced by ReporterInterface::hasReporterValue(), and initShowHideLists().
hasReporterValueByName() [2/2]
template<typename T > bool ReporterInterface::hasReporterValueByName (const ReporterName & reporter_name) const protected inherited
Definition at line 185 of file ReporterInterface.h.
{
  if (!reportersAdded())
    _ri_moose_object.mooseError(
        "Cannot call hasReporterValueByName() until all Reporters have been constructed.");
  return _ri_reporter_data.hasReporterValue<T>(reporter_name);
}
hasScalarOutput()
bool AdvancedOutput::hasScalarOutput ()
Returns true if there exists scalar variables for output.
Returns
True if scalar variable output exists
See also
getScalarVariableOutput
Definition at line 823 of file AdvancedOutput.C.
{
  return hasOutputHelper("scalars");
}
Referenced by Exodus::initialSetup().
hasVectorPostprocessor() [1/2]
bool VectorPostprocessorInterface::hasVectorPostprocessor (const std::string & param_name) const inherited
Determine if the VectorPostprocessor exists by parameter.
Parameters
name The name of the VectorPostprocessor parameter
Returns
True if the VectorPostprocessor exists
Definition at line 168 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessor() until all "
                              "VectorPostprocessors have been constructed.");
  return hasVectorPostprocessorByName(getVectorPostprocessorName(param_name));
}
hasVectorPostprocessor() [2/2]
bool VectorPostprocessorInterface::hasVectorPostprocessor (const std::string & param_name, const std::string & vector_name) const inherited
Determine if the VectorPostprocessor data exists by parameter.
Parameters
param_name The name of the VectorPostprocessor parameter
vector_name The vector name within the VectorPostprocessor
Returns
True if the VectorPostprocessor data exists
See also
hasVectorPostprocessorByName getVectorPostprocessorValue
Definition at line 138 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessor() until all VectorPostprocessors "
                              "have been constructed.");
  return hasVectorPostprocessorByName(getVectorPostprocessorName(param_name), vector_name);
}
Referenced by VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor().
hasVectorPostprocessorByName() [1/2]
bool VectorPostprocessorInterface::hasVectorPostprocessorByName (const VectorPostprocessorName & name) const inherited
Determine if the VectorPostprocessor exists by name.
Parameters
name The name of the VectorPostprocessor
Returns
True if the VectorPostprocessor exists
Definition at line 178 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessorByName() until all "
                              "VectorPostprocessors have been constructed.");
  return _vpi_feproblem.hasUserObject(name) &&
         dynamic_cast<const VectorPostprocessor *>(&_vpi_feproblem.getUserObjectBase(name));
}
hasVectorPostprocessorByName() [2/2]
bool VectorPostprocessorInterface::hasVectorPostprocessorByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
Determine if the VectorPostprocessor data exists by name.
Parameters
name The name of the VectorPostprocessor
vector_name The vector name within the VectorPostprocessor
Returns
True if the VectorPostprocessor data exists
See also
hasVectorPostprocessor getVectorPostprocessorValueByName
Definition at line 149 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessorByName() until all "
                              "VectorPostprocessors have been constructed.");
  const bool has_vpp = _vpi_feproblem.getReporterData().hasReporterValue<VectorPostprocessorValue>(
      VectorPostprocessorReporterName(name, vector_name));
  if (has_vpp)
    mooseAssert(_vpi_feproblem.hasUserObject(name) && dynamic_cast<const VectorPostprocessor *>(
                                                          &_vpi_feproblem.getUserObjectBase(name)),
                "Has reporter VectorPostprocessor Reporter value but not VectorPostprocessor UO");
  return has_vpp;
}
Referenced by VectorPostprocessorInterface::hasVectorPostprocessor(), initShowHideLists(), CSV::output(), and VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName().
hasVectorPostprocessorOutput()
bool AdvancedOutput::hasVectorPostprocessorOutput ()
Returns true if there exists VectorPostprocessors for output.
Returns
True if VectorPostprocessor output exists
See also
getVectorPostprocessorOutput
Definition at line 847 of file AdvancedOutput.C.
{
  return hasOutputHelper("vector_postprocessors");
}
init()
void AdvancedOutput::init () protected virtual
Populates the various data structures needed to control the output.
Definition at line 153 of file AdvancedOutput.C.
{
  // Initialize the execution flags
  for (auto & [name, input] : _advanced_execute_on)
    initExecutionTypes(name, input);
  // Clear existing execute information lists
  _execute_data.reset();
  // Initialize the available output
  initAvailableLists();
  // Separate the hide/show list into components
  initShowHideLists(getParam<std::vector<VariableName>>("show"),
                    getParam<std::vector<VariableName>>("hide"));
  // If 'elemental_as_nodal = true' the elemental variable names must be appended to the
  // nodal variable names. Thus, when libMesh::EquationSystem::build_solution_vector is called
  // it will create the correct nodal variable from the elemental
  if (_elemental_as_nodal)
  {
    OutputData & nodal = _execute_data["nodal"];
    OutputData & elemental = _execute_data["elemental"];
    nodal.show.insert(elemental.show.begin(), elemental.show.end());
    nodal.hide.insert(elemental.hide.begin(), elemental.hide.end());
    nodal.available.insert(elemental.available.begin(), elemental.available.end());
  }
  // Similarly as above, if 'scalar_as_nodal = true' append the elemental variable lists
  if (_scalar_as_nodal)
  {
    OutputData & nodal = _execute_data["nodal"];
    OutputData & scalar = _execute_data["scalars"];
    nodal.show.insert(scalar.show.begin(), scalar.show.end());
    nodal.hide.insert(scalar.hide.begin(), scalar.hide.end());
    nodal.available.insert(scalar.available.begin(), scalar.available.end());
  }
  // Initialize the show/hide/output lists for each of the types of output
  for (auto & it : _execute_data)
    initOutputList(it.second);
}
Referenced by initialSetup(), and output().
initAvailableLists()
void AdvancedOutput::initAvailableLists () private
Initializes the available lists for each of the output types.
Definition at line 402 of file AdvancedOutput.C.
{
  // Initialize Postprocessor list
  // This flag is set to true if any postprocessor has the 'outputs' parameter set, it is then used
  // to produce an warning if postprocessor output is disabled
  if (!_postprocessors_as_reporters)
    initPostprocessorOrVectorPostprocessorLists<Postprocessor>("postprocessors");
  // Initialize vector postprocessor list
  // This flag is set to true if any vector postprocessor has the 'outputs' parameter set, it is
  // then used
  // to produce an warning if vector postprocessor output is disabled
  if (!_vectorpostprocessors_as_reporters)
    initPostprocessorOrVectorPostprocessorLists<VectorPostprocessor>("vector_postprocessors");
  // Get a list of the available variables
  std::vector<VariableName> variables = _problem_ptr->getVariableNames();
  // Loop through the variables and store the names in the correct available lists
  for (const auto & var_name : variables)
  {
    if (_problem_ptr->hasVariable(var_name))
    {
      MooseVariableFEBase & var = _problem_ptr->getVariable(
          0, var_name, Moose::VarKindType::VAR_ANY, Moose::VarFieldType::VAR_FIELD_ANY);
      const FEType type = var.feType();
      for (unsigned int i = 0; i < var.count(); ++i)
      {
        VariableName vname = var_name;
        if (var.isArray())
          vname = SubProblem::arrayVariableComponent(var_name, i);
        // A note that if we have p-refinement we assume "worst-case" scenario that our constant
        // monomial/monomial-vec families have been refined and we can no longer write them as
        // elemental
        if (type.order == CONSTANT && !_problem_ptr->havePRefinement() &&
            type.family != MONOMIAL_VEC)
          _execute_data["elemental"].available.insert(vname);
        else if (type.family == NEDELEC_ONE || type.family == LAGRANGE_VEC ||
                 type.family == MONOMIAL_VEC || type.family == RAVIART_THOMAS)
        {
          const auto geom_type = ((type.family == MONOMIAL_VEC) && (type.order == CONSTANT) &&
                                  !_problem_ptr->havePRefinement())
                                     ? "elemental"
                                     : "nodal";
          switch (_es_ptr->get_mesh().spatial_dimension())
          {
            case 0:
            case 1:
              _execute_data[geom_type].available.insert(vname);
              break;
            case 2:
              _execute_data[geom_type].available.insert(vname + "_x");
              _execute_data[geom_type].available.insert(vname + "_y");
              break;
            case 3:
              _execute_data[geom_type].available.insert(vname + "_x");
              _execute_data[geom_type].available.insert(vname + "_y");
              _execute_data[geom_type].available.insert(vname + "_z");
              break;
          }
        }
        else
          _execute_data["nodal"].available.insert(vname);
      }
    }
    else if (_problem_ptr->hasScalarVariable(var_name))
      _execute_data["scalars"].available.insert(var_name);
  }
  // Initialize Reporter name list
  for (auto && r_name : _reporter_data.getReporterNames())
    if ((_postprocessors_as_reporters || !r_name.isPostprocessor()) &&
        (_vectorpostprocessors_as_reporters || !r_name.isVectorPostprocessor()))
      _execute_data["reporters"].available.insert(r_name);
}
Referenced by init().
initExecutionTypes()
void AdvancedOutput::initExecutionTypes (const std::string & name, ExecFlagEnum & input) private
Initialize the possible execution types.
Parameters
name The name of the supplied MultiMoose enum from the _execute_on std::map (e.g., scalars)
input The ExecFlagEnum for output type flags to initialize
Definition at line 481 of file AdvancedOutput.C.
{
  // Build the input paramemter name
  std::string param_name = "execute_";
  param_name += name + "_on";
  // The parameters exists and has been set by the user
  if (_pars.have_parameter<ExecFlagEnum>(param_name) && isParamValid(param_name))
    input = getParam<ExecFlagEnum>(param_name);
  // If the parameter does not exists; set it to a state where no valid entries exists so nothing
  // gets executed
  else if (!_pars.have_parameter<ExecFlagEnum>(param_name))
  {
    input = _execute_on;
    input.clear();
  }
}
Referenced by init().
initialSetup()
void AdvancedOutput::initialSetup () protected virtual
Call init() method on setup.
Reimplemented from SetupInterface.
Reimplemented in Console, CSV, Exodus, Nemesis, and OversampleOutput.
Definition at line 147 of file AdvancedOutput.C.
{
  init();
}
Referenced by Nemesis::initialSetup(), and OversampleOutput::initialSetup().
initOutputList()
void AdvancedOutput::initOutputList (OutputData & data) private
Initializes the list of items to be output using the available, show, and hide lists.
Parameters
data The OutputData to operate on
Definition at line 634 of file AdvancedOutput.C.
{
  // References to the vectors of variable names
  std::set<std::string> & hide = data.hide;
  std::set<std::string> & show = data.show;
  std::set<std::string> & avail = data.available;
  std::set<std::string> & output = data.output;
  // Append to the hide list from OutputInterface objects
  std::set<std::string> interface_hide;
  _app.getOutputWarehouse().buildInterfaceHideVariables(name(), interface_hide);
  hide.insert(interface_hide.begin(), interface_hide.end());
  // Both show and hide are empty and no show/hide settings were provided (show all available)
  if (show.empty() && hide.empty() && !_execute_data.hasShowList())
    output = avail;
  // Only hide is empty (show all the variables listed)
  else if (!show.empty() && hide.empty())
    output = show;
  // Only show is empty (show all except those hidden)
  else if (show.empty() && !hide.empty())
    std::set_difference(avail.begin(),
                        avail.end(),
                        hide.begin(),
                        hide.end(),
                        std::inserter(output, output.begin()));
  // Both hide and show are present (show all those listed)
  else
  {
    // Check if variables are in both, which is invalid
    std::vector<std::string> tmp;
    std::set_intersection(
        hide.begin(), hide.end(), show.begin(), show.end(), std::inserter(tmp, tmp.begin()));
    if (!tmp.empty())
    {
      std::ostringstream oss;
      oss << "Output(s) specified to be both shown and hidden: ";
      std::copy(tmp.begin(), tmp.end(), infix_ostream_iterator<std::string>(oss, " "));
      mooseError(oss.str());
    }
    // Define the output variable list
    output = show;
  }
}
Referenced by init().
initPostprocessorOrVectorPostprocessorLists()
template<typename postprocessor_type > void AdvancedOutput::initPostprocessorOrVectorPostprocessorLists (const std::string & execute_data_name) private
Helper function for initAvailableLists, templated on warehouse type and postprocessor_type.
Parameters
execute_data_name Name of the OutputData struct to initialize
warehouse Reference to the postprocessor or vector postprocessor warehouse
Definition at line 371 of file AdvancedOutput.h.
{
  // Convenience reference to the OutputData being operated on (should used "postprocessors" or
  // "vector_postprocessors")
  OutputData & execute_data = _execute_data[execute_data_name];
  // Build the input file parameter name (i.e. "output_postprocessors_on" or
  // "output_vector_postprocessors_on")
  std::ostringstream oss;
  oss << "execute_" << execute_data_name << "_on";
  std::string execute_on_name = oss.str();
  std::vector<UserObject *> objs;
  _problem_ptr->theWarehouse()
      .query()
      .condition<AttribSystem>("UserObject")
      .condition<AttribThread>(0)
      .queryIntoUnsorted(objs);
  for (const auto & obj : objs)
  {
    auto pps = dynamic_cast<postprocessor_type *>(obj);
    if (!pps)
      continue;
    execute_data.available.insert(pps->PPName());
    // Extract the list of outputs
    const auto & pps_outputs = pps->getOutputs();
    // Check that the outputs lists are valid
    _app.getOutputWarehouse().checkOutputs(pps_outputs);
    // Check that the output object allows postprocessor output,
    // account for "all" keyword (if it is present assume "all" was desired)
    if (pps_outputs.find(name()) != pps_outputs.end() ||
        pps_outputs.find("all") != pps_outputs.end())
    {
      if (!_advanced_execute_on.contains(execute_data_name) ||
          (_advanced_execute_on[execute_data_name].isValid() &&
           _advanced_execute_on[execute_data_name].contains("none")))
      {
        const bool is_pp_type = (execute_data_name == "postprocessors");
        const std::string pp_type_str = is_pp_type ? "post-processor" : "vector post-processor";
        mooseWarning("The ",
                     pp_type_str,
                     " '",
                     pps->PPName(),
                     "' has requested to be output by the '",
                     name(),
                     "' output, but ",
                     pp_type_str,
                     " output is disabled for that output object.");
      }
    }
  }
}
initShowHideLists()
void AdvancedOutput::initShowHideLists (const std::vector< VariableName > & show, const std::vector< VariableName > & hide) private
Parses the user-supplied input for hiding and showing variables and postprocessors into a list for each type of output.
Parameters
show The vector of names that are to be output
hide The vector of names that are to be suppressed from the output
Definition at line 501 of file AdvancedOutput.C.
{
  // Storage for user-supplied input that is unknown as a variable or postprocessor
  std::set<std::string> unknown;
  // If a show hide/list exists, let the data warehouse know about it. This allows for the proper
  // handling of output lists (see initOutputList)
  if (show.size() > 0)
    _execute_data.setHasShowList(true);
  // Populate the show lists
  for (const auto & var_name : show)
  {
    if (_problem_ptr->hasVariable(var_name))
    {
      MooseVariableFEBase & var = _problem_ptr->getVariable(
          0, var_name, Moose::VarKindType::VAR_ANY, Moose::VarFieldType::VAR_FIELD_ANY);
      const FEType type = var.feType();
      for (unsigned int i = 0; i < var.count(); ++i)
      {
        VariableName vname = var_name;
        if (var.isArray())
          vname = SubProblem::arrayVariableComponent(var_name, i);
        if (type.order == CONSTANT)
          _execute_data["elemental"].show.insert(vname);
        else if (type.family == NEDELEC_ONE || type.family == LAGRANGE_VEC ||
                 type.family == MONOMIAL_VEC || type.family == RAVIART_THOMAS)
        {
          const auto geom_type =
              ((type.family == MONOMIAL_VEC) && (type.order == CONSTANT)) ? "elemental" : "nodal";
          switch (_es_ptr->get_mesh().spatial_dimension())
          {
            case 0:
            case 1:
              _execute_data[geom_type].show.insert(vname);
              break;
            case 2:
              _execute_data[geom_type].show.insert(vname + "_x");
              _execute_data[geom_type].show.insert(vname + "_y");
              break;
            case 3:
              _execute_data[geom_type].show.insert(vname + "_x");
              _execute_data[geom_type].show.insert(vname + "_y");
              _execute_data[geom_type].show.insert(vname + "_z");
              break;
          }
        }
        else
          _execute_data["nodal"].show.insert(vname);
      }
    }
    else if (_problem_ptr->hasScalarVariable(var_name))
      _execute_data["scalars"].show.insert(var_name);
    else if (hasPostprocessorByName(var_name))
      _execute_data["postprocessors"].show.insert(var_name);
    else if (hasVectorPostprocessorByName(var_name))
      _execute_data["vector_postprocessors"].show.insert(var_name);
    else if ((var_name.find("/") != std::string::npos) &&
             (hasReporterValueByName(ReporterName(var_name))))
      _execute_data["reporters"].show.insert(var_name);
    else
      unknown.insert(var_name);
  }
  // Populate the hide lists
  for (const auto & var_name : hide)
  {
    if (_problem_ptr->hasVariable(var_name))
    {
      MooseVariableFEBase & var = _problem_ptr->getVariable(
          0, var_name, Moose::VarKindType::VAR_ANY, Moose::VarFieldType::VAR_FIELD_ANY);
      const FEType type = var.feType();
      for (unsigned int i = 0; i < var.count(); ++i)
      {
        VariableName vname = var_name;
        if (var.isArray())
          vname = SubProblem::arrayVariableComponent(var_name, i);
        if (type.order == CONSTANT)
          _execute_data["elemental"].hide.insert(vname);
        else if (type.family == NEDELEC_ONE || type.family == LAGRANGE_VEC ||
                 type.family == MONOMIAL_VEC || type.family == RAVIART_THOMAS)
        {
          switch (_es_ptr->get_mesh().spatial_dimension())
          {
            case 0:
            case 1:
              _execute_data["nodal"].hide.insert(vname);
              break;
            case 2:
              _execute_data["nodal"].hide.insert(vname + "_x");
              _execute_data["nodal"].hide.insert(vname + "_y");
              break;
            case 3:
              _execute_data["nodal"].hide.insert(vname + "_x");
              _execute_data["nodal"].hide.insert(vname + "_y");
              _execute_data["nodal"].hide.insert(vname + "_z");
              break;
          }
        }
        else
          _execute_data["nodal"].hide.insert(vname);
      }
    }
    else if (_problem_ptr->hasScalarVariable(var_name))
      _execute_data["scalars"].hide.insert(var_name);
    else if (hasPostprocessorByName(var_name))
      _execute_data["postprocessors"].hide.insert(var_name);
    else if (hasVectorPostprocessorByName(var_name))
      _execute_data["vector_postprocessors"].hide.insert(var_name);
    else if ((var_name.find("/") != std::string::npos) &&
             (hasReporterValueByName(ReporterName(var_name))))
      _execute_data["reporters"].hide.insert(var_name);
    else
      unknown.insert(var_name);
  }
  // Error if an unknown variable or postprocessor is found
  if (!unknown.empty())
  {
    std::ostringstream oss;
    oss << "Output(s) do not exist (must be variable, scalar, postprocessor, or vector "
           "postprocessor): ";
    std::copy(unknown.begin(), unknown.end(), infix_ostream_iterator<std::string>(oss, " "));
    mooseError(oss.str());
  }
}
Referenced by init().
inLinearTimeWindow()
bool PetscOutput::inLinearTimeWindow () inline protected inherited
Definition at line 67 of file PetscOutput.h.
  {
    return _time >= _linear_start_time - _t_tol && _time <= _linear_end_time + _t_tol;
  }
inNonlinearTimeWindow()
bool PetscOutput::inNonlinearTimeWindow () inline protected inherited
Definition at line 63 of file PetscOutput.h.
  {
    return _time >= _nonlinear_start_time - _t_tol && _time <= _nonlinear_end_time + _t_tol;
  }
interval()
const unsigned int & Output::interval () const inherited
Get the output interval.
isAdvanced()
bool Output::isAdvanced () inherited
Returns true if this object is an AdvancedOutput object.
Definition at line 332 of file Output.C.
{
  return _is_advanced;
}
isDefaultPostprocessorValue()
bool PostprocessorInterface::isDefaultPostprocessorValue (const std::string & param_name, const unsigned int index = 0) const inherited
Determine whether or not the Postprocessor is a default value.
A default value is when the value is either the value set by addParam, or is a user-set value in input instead of a name to a postprocessor.
Parameters
param_name The name of the Postprocessor parameter
index The index of the postprocessor
Returns
True if the Postprocessor is a default value, false if the Postprocessor is the name of a Postprocessor
Definition at line 75 of file PostprocessorInterface.C.
{
  return isDefaultPostprocessorValueByName(getPostprocessorNameInternal(param_name, index));
}
Referenced by EigenKernel::EigenKernel().
isDefaultPostprocessorValueByName()
bool PostprocessorInterface::isDefaultPostprocessorValueByName (const PostprocessorName & name) const private inherited
Returns
True if the PostprocessorName name repesents a default value: the name converts to a value (set by addParam or set via input), and a Postprocessor does not exist with the same name (we do allow Postprocessors with numbered names...)
Definition at line 82 of file PostprocessorInterface.C.
{
  // We do allow actual Postprocessor objects to have names that will succeed in being
  // represented as a double... so if the name does actually exist as a PP, it's not a default
  if (_ppi_feproblem.getReporterData().hasReporterValue<PostprocessorValue>(
          PostprocessorReporterName(name)))
    return false;
  std::istringstream ss(name);
  Real real_value = -std::numeric_limits<Real>::max();
  return (ss >> real_value && ss.eof());
}
Referenced by PostprocessorInterface::getDefaultPostprocessorValueByName(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), and PostprocessorInterface::isDefaultPostprocessorValue().
isParamSetByUser()
bool MooseBaseParameterInterface::isParamSetByUser (const std::string & nm) const inline inherited
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
Parameters
nm The name of the parameter to test
Definition at line 108 of file MooseBaseParameterInterface.h.
{ return _pars.isParamSetByUser(nm); }
Referenced by SetAdaptivityOptionsAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), LibtorchNeuralNetControl::conditionalParameterError(), MooseBaseParameterInterface::getRenamedParam(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), PiecewiseTabularBase::PiecewiseTabularBase(), MooseMesh::prepare(), and SolutionUserObject::readXda().
isParamValid()
bool MooseBaseParameterInterface::isParamValid (const std::string & name) const inline inherited
Test if the supplied parameter is valid.
Parameters
name The name of the parameter to test
Definition at line 102 of file MooseBaseParameterInterface.h.
{ return _pars.isParamValid(name); }
Referenced by AddDriftDiffusionAction::act(), AddSpecies::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CopyNodalVarsAction::act(), CreateDisplacedProblemAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), AddGeneralReactions::AddGeneralReactions(), AddZapdosReactions::AddZapdosReactions(), AdvectiveFluxAux::AdvectiveFluxAux(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), GeneratedMesh::buildMesh(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), ChemicalReactionsBase::ChemicalReactionsBase(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), CombinerGenerator::CombinerGenerator(), CSVReader::CSVReader(), ConstantReporter::declareConstantReporterValues(), DGKernelBase::DGKernelBase(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EEDFEnergyTownsendLog::EEDFEnergyTownsendLog(), Eigenvalue::Eigenvalue(), ElectronEnergyTermRate::ElectronEnergyTermRate(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), PIDTransientControl::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FileOutput::FileOutput(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FunctionDT::FunctionDT(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getRenamedParam(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), Terminator::handleMessage(), HeavySpeciesTempl< is_ad >::HeavySpeciesTempl(), HFEMDirichletBC::HFEMDirichletBC(), EigenExecutionerBase::init(), Eigenvalue::init(), IterationAdaptiveDT::init(), initExecutionTypes(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), MooseParsedFunction::initialSetup(), MooseParsedGradFunction::initialSetup(), MooseParsedVectorFunction::initialSetup(), PiecewiseTabularBase::initialSetup(), SolutionFunction::initialSetup(), Console::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), IterationAdaptiveDT::IterationAdaptiveDT(), LeastSquaresFit::LeastSquaresFit(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MatCoupledForce::MatCoupledForce(), MooseMesh::MooseMesh(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarConsumerInterface::MortarConsumerInterface(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalExtremeValue::NodalExtremeValue(), EigenExecutionerBase::normalizeSolution(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PetscOutput::PetscOutput(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), PicardSolve::PicardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseTabularBase::PiecewiseTabularBase(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), MooseMesh::prepare(), MultiApp::readCommandLineArguments(), SolutionUserObject::readExodusII(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), MooseMesh::setCoordSystem(), FileOutput::setFileBase(), FileOutput::setFileBaseInternal(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SideDiffusiveFluxIntegralTempl< is_ad, T >::SideDiffusiveFluxIntegralTempl(), SideExtremeValue::SideExtremeValue(), SolutionUserObject::SolutionUserObject(), Terminator::Terminator(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), MultiAppDofCopyTransfer::transfer(), TransformGenerator::TransformGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
isVectorPostprocessorDistributed()
bool VectorPostprocessorInterface::isVectorPostprocessorDistributed (const std::string & param_name) const inherited
Return true if the VectorPostprocessor is marked with parallel_type as DISTRIBUTED.
Definition at line 190 of file VectorPostprocessorInterface.C.
{
  return isVectorPostprocessorDistributedByName(getVectorPostprocessorName(param_name));
}
isVectorPostprocessorDistributedByName()
bool VectorPostprocessorInterface::isVectorPostprocessorDistributedByName (const VectorPostprocessorName & name) const inherited
Definition at line 196 of file VectorPostprocessorInterface.C.
{
  return _vpi_feproblem.getVectorPostprocessorObjectByName(name).isDistributed();
}
Referenced by VectorPostprocessorInterface::isVectorPostprocessorDistributed().
jacobianSetup()
void SetupInterface::jacobianSetup () virtual inherited
Gets called just before the Jacobian is computed and before this object is asked to do its job.
Reimplemented in EqualValueEmbeddedConstraint, Function, ADKernelTempl< T >, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 50 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::jacobianSetup(), and ComputeFVFluxJacobianThread< RangeType >::setup().
meshChanged()
virtual void MeshChangedInterface::meshChanged () inline virtual inherited
Called on this object when the mesh changes.
Reimplemented in GeometryBase, EqualValueBoundaryConstraint, DiracKernelBase, FVPointValueConstraint, MeshDivision, Console, Exodus, Nemesis, OversampleOutput, Positions, ExplicitTimeIntegrator, MultiAppVariableValueSamplePostprocessorTransfer, GhostingUserObject, NearestNodeNumberUO, RadialAverage, MooseVariableDataFV< OutputType >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 34 of file MeshChangedInterface.h.
{}
Referenced by MooseVariableFE< OutputType >::meshChanged(), and MooseVariableFV< OutputType >::meshChanged().
mooseDeprecated()
template<typename... Args> void MooseBaseErrorInterface::mooseDeprecated (Args &&... args) const inline inherited
Definition at line 78 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseDeprecatedStream(_console, false, true, std::forward<Args>(args)...);
  }
Referenced by FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::advanceMultiApps(), MultiApp::appProblem(), Executioner::augmentedPicardConvergenceCheck(), MooseMesh::buildSideList(), FEProblemBase::computeResidual(), AddVariableAction::determineType(), Eigenvalue::Eigenvalue(), MooseMesh::elem(), FunctionDT::FunctionDT(), RandomICBase::generateRandom(), MooseMesh::getBoundariesToElems(), Control::getExecuteOptions(), FEProblemBase::getNonlinearSystem(), FEProblemBase::getUserObjects(), FEProblemBase::hasPostprocessor(), MooseMesh::node(), FixedPointSolve::numPicardIts(), RelationshipManager::operator>=(), Executioner::picardSolve(), and MooseMesh::setBoundaryToNormalMap().
mooseError()
template<typename... Args> void MooseBaseErrorInterface::mooseError (Args &&... args) const inline inherited
Emits an error prefixed with object name and type.
Definition at line 38 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, errorPrefix("error"), std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
Referenced by HierarchicalGridPartitioner::_do_partition(), PetscExternalPartitioner::_do_partition(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AdaptivityAction::act(), AddFVICAction::act(), AddICAction::act(), AddMeshGeneratorAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVectorPostprocessorAction::act(), CheckFVBCAction::act(), CheckIntegrityAction::act(), CommonOutputAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DeprecatedBlockAction::act(), InitProblemAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetAdaptivityOptionsAction::act(), SetupMeshAction::act(), SetupMeshCompleteAction::act(), SetupPredictorAction::act(), SetupTimeStepperAction::act(), SplitMeshAction::act(), FEProblemBase::adaptMesh(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::addConstraint(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFVInitialCondition(), AddGeneralReactions::AddGeneralReactions(), FEProblemBase::addInitialCondition(), FEProblemBase::addLineSearch(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addOutput(), SubProblem::addPiecewiseByBlockLambdaFunctor(), DistributedRectilinearMeshGenerator::addPoint(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), FEProblemBase::addPostprocessor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseMesh::addQuadratureNode(), FEProblemBase::addReporter(), AddVariableAction::addVariable(), FEProblemBase::addVectorPostprocessor(), SubProblem::addVectorTag(), AddZapdosReactions::AddZapdosReactions(), ADEEDFRateConstantTownsend::ADEEDFRateConstantTownsend(), ADGasElectronMoments::ADGasElectronMoments(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), MooseVariableScalar::adUDot(), Output::advancedExecuteOn(), AdvectiveFluxAux::AdvectiveFluxAux(), ADZapdosEEDFRateConstant::ADZapdosEEDFRateConstant(), MooseVariableBase::allDofIndices(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayConstantIC::ArrayConstantIC(), ArrayFunctionIC::ArrayFunctionIC(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), Function::average(), Axisymmetric2D3DSolutionFunction::Axisymmetric2D3DSolutionFunction(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), BoltzmannSolverScalar::BoltzmannSolverScalar(), BoundingValueElementDamper::BoundingValueElementDamper(), BoundingValueNodalDamper::BoundingValueNodalDamper(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), MooseMesh::buildCoarseningMap(), MultiApp::buildComm(), DistributedRectilinearMeshGenerator::buildCube(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), PiecewiseTabularBase::buildFromXY(), MooseMesh::buildLowerDMesh(), GeneratedMesh::buildMesh(), MeshGeneratorMesh::buildMesh(), SpiralAnnularMesh::buildMesh(), TiledMesh::buildMesh(), ImageMesh::buildMesh3D(), ImageMeshGenerator::buildMesh3D(), MooseMesh::buildRefinementMap(), MaterialBase::buildRequiredMaterials(), MooseMesh::buildSideList(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), UserObjectInterface::castUserObject(), EigenExecutionerBase::chebyshev(), SubProblem::checkBlockMatProps(), SubProblem::checkBoundaryMatProps(), MooseMesh::checkCoordinateSystems(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkDisplacementOrders(), FEProblemBase::checkDuplicatePostprocessorVariableNames(), MooseMesh::checkDuplicateSubdomainNames(), MaterialBase::checkExecutionStage(), MeshGenerator::checkGetMesh(), ReporterTransferInterface::checkHasReporterValue(), FEProblemBase::checkICRestartError(), EigenExecutionerBase::checkIntegrity(), Eigenvalue::checkIntegrity(), Steady::checkIntegrity(), ExplicitTimeIntegrator::checkLinearConvergence(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), PostprocessorInterface::checkParam(), FEProblemBase::checkProblemIntegrity(), Sampler::checkReinitStatus(), MaterialBase::checkStatefulSanity(), FEProblemBase::checkUserObjects(), MultiAppTransfer::checkVariable(), DomainUserObject::checkVariable(), ChemicalReactionsBase::ChemicalReactionsBase(), MooseMesh::clone(), LibmeshPartitioner::clone(), CombinerGenerator::CombinerGenerator(), ElementSubdomainModifier::complementMovingBoundaryID(), ElementSubdomainModifier::complementMovingBoundaryName(), MooseVariableFieldBase::componentName(), CompositeFunction::CompositeFunction(), NodalPatchRecovery::compute(), VariableCondensationPreconditioner::computeDInverseDiag(), CompositionDT::computeDT(), MooseVariableFieldBase::computeFaceValues(), TimeStepper::computeFailedDT(), IterationAdaptiveDT::computeFailedDT(), TimeSequenceStepperBase::computeFailedDT(), MooseMesh::computeFiniteVolumeCoords(), FVFluxKernel::computeJacobian(), ArrayKernel::computeJacobian(), ArrayKernel::computeOffDiagJacobian(), FVElementalKernel::computeOffDiagJacobian(), MaterialBase::computeProperties(), ScalarKernel::computeQpJacobian(), ScalarKernel::computeQpResidual(), FVFluxKernel::computeResidual(), ArrayKernel::computeResidual(), FVFluxBC::computeResidual(), ResidualObject::computeResidualAndJacobian(), FVFluxKernel::computeResidualAndJacobian(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualL2Norm(), FEProblemBase::computeResidualTag(), FEProblemBase::computeResidualType(), TimeStepper::computeStep(), ActuallyExplicitEuler::computeTimeDerivatives(), AStableDirk4::computeTimeDerivatives(), BDF2::computeTimeDerivatives(), CrankNicolson::computeTimeDerivatives(), ExplicitEuler::computeTimeDerivatives(), ExplicitRK2::computeTimeDerivatives(), ExplicitTVDRK2::computeTimeDerivatives(), ImplicitEuler::computeTimeDerivatives(), ImplicitMidpoint::computeTimeDerivatives(), LStableDirk2::computeTimeDerivatives(), LStableDirk3::computeTimeDerivatives(), LStableDirk4::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), FEProblemBase::computeUserObjectsInternal(), BolsigValueScalar::computeValue(), PenetrationAux::computeValue(), BuildArrayVariableAux::computeValue(), TagVectorArrayVariableAux::computeValue(), ConcentricCircleMesh::ConcentricCircleMesh(), ConditionalEnableControl::ConditionalEnableControl(), TimeStepper::constrainStep(), LibtorchNeuralNetControl::controlNeuralNet(), AddVariableAction::createInitialConditionAction(), DataRead::DataRead(), ReporterTransferInterface::declareClone(), MeshGenerator::declareMeshProperty(), ReporterTransferInterface::declareVectorClone(), FunctorRelationshipManager::delete_remote_elements(), MooseMesh::deleteRemoteElements(), BicubicSplineFunction::derivative(), MooseMesh::detectPairedSidesets(), FEProblemBase::determineNonlinearSystem(), MeshDiagnosticsGenerator::diagnosticsLog(), DiffusionRateTemp::DiffusionRateTemp(), FunctorBinnedValuesDivision::divisionIndex(), FunctorRelationshipManager::dofmap_reinit(), FEProblemBase::duplicateVariableCheck(), EEDFRateConstant::EEDFRateConstant(), EEDFRateConstantTownsend::EEDFRateConstantTownsend(), Eigenvalue::Eigenvalue(), ElectricField::ElectricField(), ElectronMobility::ElectronMobility(), ElementIntegerAux::ElementIntegerAux(), ElementQualityAux::ElementQualityAux(), ElementUOAux::ElementUOAux(), DistributedRectilinearMeshGenerator::elemId(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), MooseMesh::errorIfDistributedMesh(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), BoltzmannSolverScalar::execute(), Eigenvalue::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), ElementQualityChecker::execute(), DiscreteElementUserObject::execute(), DomainUserObject::execute(), FEProblemBase::execute(), FEProblemBase::executeControls(), MultiAppVectorPostprocessorTransfer::executeFromMultiapp(), MultiAppVectorPostprocessorTransfer::executeToMultiapp(), ExplicitSSPRungeKutta::ExplicitSSPRungeKutta(), FileOutput::FileOutput(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), ElementQualityChecker::finalize(), VerifyElementUniqueID::finalize(), VerifyNodalUniqueID::finalize(), DiscreteElementUserObject::finalize(), Transfer::find_sys(), BreakMeshByBlockGeneratorBase::findFreeBoundaryId(), FunctionDT::FunctionDT(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), GapValueAux::GapValueAux(), Gas::Gas(), GasBase::GasBase(), GasElectronMoments::GasElectronMoments(), AllSideSetsByNormalsGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundingBoxNodeSetGenerator::generate(), BreakMeshByBlockGenerator::generate(), CombinerGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshCollectionGenerator::generate(), MeshDiagnosticsGenerator::generate(), MeshExtruderGenerator::generate(), MeshRepairGenerator::generate(), MoveNodeGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), SideSetsFromNormalsGenerator::generate(), SideSetsFromPointsGenerator::generate(), SmoothMeshGenerator::generate(), SpiralAnnularMeshGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), TiledMeshGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GeneratedMesh::GeneratedMesh(), GeneratedMeshGenerator::GeneratedMeshGenerator(), MeshGenerator::generateInternal(), CircularBoundaryCorrectionGenerator::generateRadialCorrectionFactor(), RandomICBase::generateRandom(), GenericConstantMaterialTempl< is_ad >::GenericConstantMaterialTempl(), GenericConstantVectorMaterialTempl< is_ad >::GenericConstantVectorMaterialTempl(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), DisplacedProblem::getActualFieldVariable(), FEProblemBase::getActualFieldVariable(), DisplacedProblem::getArrayVariable(), FEProblemBase::getArrayVariable(), MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::getBlockConnectedBlocks(), VariableOldValueBoundsAux::getBound(), MooseMesh::getBoundaryID(), MultiApp::getBoundingBox(), MooseMesh::getCoarseningMap(), MooseVariableBase::getContinuity(), Control::getControllableParameterByName(), MooseMesh::getCoordSystem(), PropertyReadFile::getData(), TransfiniteMeshGenerator::getDiscreteEdge(), FEProblemBase::getDistribution(), MooseVariableBase::getDofIndices(), VariableCondensationPreconditioner::getDofToCondense(), TransfiniteMeshGenerator::getEdge(), GhostingUserObject::getElementalValue(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), PropertyReadFile::getElementData(), MooseMesh::getElementIDIndex(), Material::getElementIDNeighbor(), Material::getElementIDNeighborByName(), MooseMesh::getElemIDMapping(), MooseMesh::getElemIDsOnBlocks(), MultiAppFieldTransfer::getEquationSystem(), MultiApp::getExecutioner(), MultiAppTransfer::getFromMultiApp(), MultiAppTransfer::getFromMultiAppInfo(), FEProblemBase::getFunction(), SubProblem::getFunctor(), MooseMesh::getGeneralAxisymmetricCoordAxis(), DistributedRectilinearMeshGenerator::getGhostNeighbors(), BatchMaterial< Tuple, Output, Input >::getIndex(), DistributedRectilinearMeshGenerator::getIndices(), SolutionUserObject::getLocalVarIndex(), Material::getMaterialByName(), FEProblemBase::getMaterialData(), SubProblem::getMatrixTagID(), AnnularMesh::getMaxInDimension(), GeneratedMesh::getMaxInDimension(), FEProblemBase::getMaxQps(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), AnnularMesh::getMinInDimension(), GeneratedMesh::getMinInDimension(), MultiAppTransfer::getMultiApp(), DistributedRectilinearMeshGenerator::getNeighbors(), MooseMesh::getNodeBlockIds(), PropertyReadFile::getNodeData(), MooseMesh::getNodeList(), FEProblemBase::getNonlinearSystem(), MooseMesh::getPairedBoundaryMapping(), ImageMesh::GetPixelInfo(), ImageMeshGenerator::GetPixelInfo(), PlaneIDMeshGenerator::getPlaneID(), FEProblemBase::getPositionsObject(), PostprocessorInterface::getPostprocessorValueByNameInternal(), MooseMesh::getRefinementMap(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), FEProblemBase::getSampler(), JSONFileReader::getScalar(), DisplacedProblem::getScalarVariable(), FEProblemBase::getScalarVariable(), DisplacedProblem::getStandardVariable(), FEProblemBase::getStandardVariable(), MooseMesh::getSubdomainBoundaryIds(), DisplacedProblem::getSystem(), FEProblemBase::getSystem(), FEProblemBase::getTimeFromStateArg(), Transient::getTimeIntegratorName(), MultiAppTransfer::getToMultiApp(), MultiAppTransfer::getToMultiAppInfo(), MooseMesh::getUniqueCoordSystem(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::getUserObjectName(), JSONFileReader::getVector(), VectorPostprocessorInterface::getVectorPostprocessorName(), SubProblem::getVectorTag(), SubProblem::getVectorTagID(), DisplacedProblem::getVectorVariable(), FEProblemBase::getVectorVariable(), GhostingAux::GhostingAux(), MultiApp::globalAppToLocal(), Function::gradient(), MooseParsedVectorFunction::gradient(), Terminator::handleMessage(), MooseVariableBase::hasDoFsOnNodes(), PostprocessorInterface::hasPostprocessor(), PostprocessorInterface::hasPostprocessorByName(), ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), AddVariableAction::init(), MooseMesh::init(), Sampler::init(), AddAuxVariableAction::init(), EigenExecutionerBase::init(), Eigenvalue::init(), Transient::init(), FEProblemBase::init(), CrankNicolson::init(), ExplicitTimeIntegrator::init(), CSVTimeSequenceStepper::init(), IterationAdaptiveDT::init(), MultiApp::init(), FEProblemBase::initialAdaptMesh(), BoltzmannSolverScalar::initialize(), PolynomialCoefficients::initialize(), CartesianGridDivision::initialize(), CylindricalGridDivision::initialize(), NestedDivision::initialize(), SphericalGridDivision::initialize(), SubProblem::initialSetup(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), Axisymmetric2D3DSolutionFunction::initialSetup(), MooseParsedFunction::initialSetup(), SolutionFunction::initialSetup(), SolutionIC::initialSetup(), FullSolveMultiApp::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), SolutionUserObject::initialSetup(), Function::integral(), InterpolatedCoefficientLinear::InterpolatedCoefficientLinear(), InterpolatedCoefficientSpline::InterpolatedCoefficientSpline(), EigenExecutionerBase::inversePowerIteration(), InversePowerMethod::InversePowerMethod(), Sampler::isAdaptiveSamplingCompleted(), MooseMesh::isBoundaryFullyExternalToSubdomains(), MooseVariableBase::isNodal(), IterationAdaptiveDT::IterationAdaptiveDT(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LineSearch::lineSearch(), ReporterPointMarker::markerSetup(), Material::Material(), MaterialOutputAction::materialOutputHelper(), MaterialRealTensorValueAux::MaterialRealTensorValueAux(), MaterialRealVectorValueAuxTempl< is_ad >::MaterialRealVectorValueAuxTempl(), Distribution::median(), FunctorRelationshipManager::mesh_reinit(), SubProblem::meshChanged(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshExtruderGenerator::MeshExtruderGenerator(), MeshRepairGenerator::MeshRepairGenerator(), SetupMeshAction::modifyParamsForUseSplit(), MeshMetaDataInterface::mooseErrorInternal(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MoveNodeGenerator::MoveNodeGenerator(), ElementSubdomainModifier::movingBoundaryID(), ElementSubdomainModifier::movingBoundaryName(), MultiApp::MultiApp(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NearestNodeDistanceAux::NearestNodeDistanceAux(), NearestNodeValueAux::NearestNodeValueAux(), FEProblemBase::needsPreviousNewtonIteration(), NewmarkBeta::NewmarkBeta(), NodalPatchRecoveryBase::nodalPatchRecovery(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), DistributedRectilinearMeshGenerator::nodeId(), DistributedRectilinearMeshGenerator::numNeighbors(), Output::onInterval(), FunctorRelationshipManager::operator()(), RelationshipManager::operator==(), MortarNodalGeometryOutput::output(), Output::Output(), DistributedRectilinearMeshGenerator::paritionSquarely(), PiecewiseBilinear::parse(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), ExplicitTimeIntegrator::performExplicitSolve(), PetscExternalPartitioner::PetscExternalPartitioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), Executioner::picardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseMulticonstant::PiecewiseMulticonstant(), PiecewiseTabularBase::PiecewiseTabularBase(), SolutionUserObject::pointValueGradientWrapper(), SolutionUserObject::pointValueWrapper(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName(), AStableDirk4::postResidual(), ExplicitRK2::postResidual(), ExplicitTVDRK2::postResidual(), ImplicitMidpoint::postResidual(), LStableDirk2::postResidual(), LStableDirk3::postResidual(), LStableDirk4::postResidual(), VariableCondensationPreconditioner::preallocateCondensedJacobian(), Predictor::Predictor(), Transient::preExecute(), MooseMesh::prepare(), MooseMesh::prepared(), FixedPointSolve::printFixedPointConvergenceReason(), RateCoefficientProvider::RateCoefficientProvider(), RateCoefficientProvider::reaction_coefficient(), RateCoefficientProvider::reaction_coefficient_derivative(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readExodusII(), SolutionUserObject::readXda(), FunctorRelationshipManager::redistribute(), Sampler::reinit(), RinglebMesh::RinglebMesh(), RinglebMeshGenerator::RinglebMeshGenerator(), PiecewiseMultiInterpolation::sample(), ScalarComponentIC::ScalarComponentIC(), ScalarLinearInterpolation::ScalarLinearInterpolation(), ScalarSplineInterpolation::ScalarSplineInterpolation(), DistributedRectilinearMeshGenerator::scaleNodalPositions(), BicubicSplineFunction::secondDerivative(), FunctorRelationshipManager::set_mesh(), MooseVariableBase::setActiveTags(), DistributedRectilinearMeshGenerator::setBoundaryNames(), MooseMesh::setCoordSystem(), FEProblemBase::setCoupling(), PiecewiseBase::setData(), FileOutput::setFileBaseInternal(), MooseMesh::setGeneralAxisymmetricCoordAxes(), FEProblemSolve::setInnerSolve(), MeshGenerator::setMeshProperty(), FEProblemBase::setNonlocalCouplingMatrix(), Sampler::setNumberOfCols(), Sampler::setNumberOfRandomSeeds(), Sampler::setNumberOfRows(), Split::setup(), TransientMultiApp::setupApp(), SetupMeshAction::setupMesh(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), TimePeriodBase::setupTimes(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SideSetsFromNormalsGenerator::SideSetsFromNormalsGenerator(), SideSetsFromPointsGenerator::SideSetsFromPointsGenerator(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), SolutionTimeAdaptiveDT::SolutionTimeAdaptiveDT(), SolutionUserObject::SolutionUserObject(), FullSolveMultiApp::solveStep(), UserObject::spatialPoints(), UserObject::spatialValue(), SpiralAnnularMesh::SpiralAnnularMesh(), SpiralAnnularMeshGenerator::SpiralAnnularMeshGenerator(), StitchedMesh::StitchedMesh(), MaterialBase::subdomainSetup(), GeneralUserObject::subdomainSetup(), NodalUserObject::subdomainSetup(), Constraint::subdomainSetup(), SuperelasticReactionRate::SuperelasticReactionRate(), FEProblemBase::swapBackMaterialsNeighbor(), Terminator::Terminator(), GeneralUserObject::threadJoin(), ThreadedGeneralUserObject::threadJoin(), DiscreteElementUserObject::threadJoin(), TimePeriodBase::TimePeriodBase(), VectorPostprocessorVisualizationAux::timestepSetup(), FEProblemBase::trustUserCouplingMatrix(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), FEProblemBase::uDotDotOldRequested(), MooseVariableScalar::uDotOld(), FEProblemBase::uDotOldRequested(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), SolutionUserObject::updateExodusBracketingTimeIndices(), FEProblemBase::updateMaxQps(), BoundingBoxIC::value(), Function::value(), Axisymmetric2D3DSolutionFunction::value(), PiecewiseConstantFromCSV::value(), ValueProvider::ValueProvider(), ValueRangeMarker::ValueRangeMarker(), ValueThresholdMarker::ValueThresholdMarker(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), MultiAppTransfer::variableIntegrityCheck(), VariableTimeIntegrationAux::VariableTimeIntegrationAux(), AddVariableAction::variableType(), Function::vectorCurl(), SubProblem::vectorTagName(), SubProblem::vectorTagType(), Function::vectorValue(), MooseParsedFunction::vectorValue(), MooseParsedGradFunction::vectorValue(), SubProblem::verifyVectorTags(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
mooseErrorNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseErrorNonPrefixed (Args &&... args) const inline inherited
Emits an error without the prefixing included in mooseError().
Definition at line 50 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
mooseInfo()
template<typename... Args> void MooseBaseErrorInterface::mooseInfo (Args &&... args) const inline inherited
Definition at line 84 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseInfoStream(_console, std::forward<Args>(args)...);
  }
Referenced by AddZapdosReactions::act(), SetupRecoverFileBaseAction::act(), AStableDirk4::AStableDirk4(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), BoltzmannSolverScalar::execute(), ExplicitRK2::ExplicitRK2(), ExplicitTVDRK2::ExplicitTVDRK2(), MultiAppTransfer::getPointInTargetAppFrame(), ImplicitMidpoint::ImplicitMidpoint(), InversePowerMethod::InversePowerMethod(), LStableDirk2::LStableDirk2(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), NonlinearEigen::NonlinearEigen(), ProjectionAux::ProjectionAux(), FEProblemBase::setRestartFile(), and SymmetryTransformGenerator::SymmetryTransformGenerator().
mooseWarning()
template<typename... Args> void MooseBaseErrorInterface::mooseWarning (Args &&... args) const inline inherited
Emits a warning prefixed with object name and type.
Definition at line 62 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(
        _console, errorPrefix("warning"), std::forward<Args>(args)...);
  }
Referenced by AddFunctionAction::act(), AddKernelAction::act(), CommonOutputAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupMeshAction::act(), DumpObjectsProblem::addAuxVariable(), DiracKernelBase::addPoint(), BoundaryMarker::BoundaryMarker(), BoundsAuxBase::BoundsAuxBase(), DistributedRectilinearMeshGenerator::buildCube(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), CartesianMeshGenerator::CartesianMeshGenerator(), CheckOutputAction::checkConsoleOutput(), MultiAppTransfer::checkMultiAppExecuteOn(), GapValueAux::computeValue(), MeshDiagnosticsGenerator::diagnosticsLog(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), Postprocessor::evaluateDotWarning(), ElementQualityChecker::finalize(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FixedPointSolve::FixedPointSolve(), ElementSubdomainIDGenerator::generate(), ParsedGenerateSideset::generate(), MultiAppTransfer::getAppInfo(), FunctorBinnedValuesDivision::getBinIndex(), FEProblemBase::getMaterial(), Terminator::handleMessage(), MaterialBase::initStatefulProperties(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::mesh(), NewmarkBeta::NewmarkBeta(), NodalPatchRecovery::NodalPatchRecovery(), Output::Output(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), Executioner::problem(), PropertyReadFile::readData(), TestSourceStepper::rejectStep(), MaterialBase::resetQpProperties(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setCoordSystem(), FEProblemBase::sizeZeroes(), TransientMultiApp::solveStep(), TimeDerivativeAux::TimeDerivativeAux(), PiecewiseConstantFromCSV::value(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
mooseWarningNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseWarningNonPrefixed (Args &&... args) const inline inherited
Emits a warning without the prefixing included in mooseWarning().
Definition at line 72 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(_console, std::forward<Args>(args)...);
  }
name()
virtual const std::string & MooseBase::name () const inline virtual inherited
Get the name of the class.
Returns
The name of the class
Reimplemented in MooseVariableBase.
Definition at line 47 of file MooseBase.h.
{ return _name; }
Referenced by HierarchicalGridPartitioner::_do_partition(), AdaptivityAction::act(), AddElementalFieldAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVariableAction::act(), CopyNodalVarsAction::act(), DeprecatedBlockAction::act(), DisplayGhostingAction::act(), MaterialOutputAction::act(), AddDriftDiffusionAction::addADKernels(), FEProblemBase::addAnyRedistributers(), Executioner::addAttributeReporter(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFunctorMaterial(), FunctorMaterial::addFunctorProperty(), FunctorMaterial::addFunctorPropertyByBlocks(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), ADDGKernel::ADDGKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), SubProblem::addPiecewiseByBlockLambdaFunctor(), FEProblemBase::addPostprocessor(), UserObject::addPostprocessorDependencyHelper(), InitialConditionBase::addPostprocessorDependencyHelper(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), UserObject::addUserObjectDependencyHelper(), AuxKernelTempl< ComputeValueType >::addUserObjectDependencyHelper(), InitialConditionBase::addUserObjectDependencyHelper(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), UserObject::addVectorPostprocessorDependencyHelper(), FVFluxKernel::adjustRMGhostLayers(), ADSurfaceCharge::ADSurfaceCharge(), Output::advancedExecuteOn(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayDGKernel::ArrayDGKernel(), ArrayParsedAux::ArrayParsedAux(), AStableDirk4::AStableDirk4(), Function::average(), MultiApp::backup(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), PiecewiseTabularBase::buildFromFile(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkICRestartError(), Damper::checkMinDamping(), Coupleable::checkWritableVar(), CompositeFunction::CompositeFunction(), MaterialBase::computeProperties(), FEProblemBase::computeUserObjectByName(), VectorPostprocessorVisualizationAux::computeValue(), MooseBaseParameterInterface::connectControllableParams(), BatchMaterial< Tuple, Output, Input >::construct(), MultiApp::createApp(), AddVariableAction::createInitialConditionAction(), MultiApp::createLocalApp(), MeshGeneratorSystem::createMeshGeneratorOrder(), MaterialBase::declareADProperty(), MeshGenerator::declareMeshesForSubByName(), MeshGenerator::declareNullMeshName(), MaterialBase::declareProperty(), DOFMapOutput::demangle(), DerivativeSumMaterialTempl< is_ad >::DerivativeSumMaterialTempl(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DomainUserObject::DomainUserObject(), DumpObjectsProblem::dumpObjectHelper(), EconomouDielectricBC::EconomouDielectricBC(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementValueSampler::ElementValueSampler(), MooseMesh::errorIfDistributedMesh(), MooseBaseErrorInterface::errorPrefix(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), PointValue::execute(), RestartableDataReporter::execute(), MultiAppNearestNodeTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), MultiApp::fillPositions(), PointSamplerBase::finalize(), FunctionDT::FunctionDT(), FVFunctionIC::functionName(), FunctionIC::functionName(), FunctorPositions::FunctorPositions(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), BoundaryDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), GeneratedMeshGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MeshGenerator::generateInternal(), InterfaceMaterial::getADMaterialProperty(), Material::getADMaterialProperty(), MultiAppTransfer::getAppInfo(), MultiApp::getBoundingBox(), Control::getControllableParameterByName(), Control::getControllableValue(), Control::getControllableValueByName(), UserObject::getDependObjects(), FEProblemBase::getDistribution(), DistributionInterface::getDistribution(), DistributionInterface::getDistributionByName(), AddZapdosReactions::getElectronImpactKernelName(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), MultiApp::getExecutioner(), FEProblemBase::getExecutor(), OutputWarehouse::getFileNumbers(), FEProblemBase::getFunction(), SubProblem::getFunctor(), AuxKernelTempl< ComputeValueType >::getGenericMaterialProperty(), NodalPatchRecovery::getGenericMaterialProperty(), InterfaceMaterial::getGenericMaterialProperty(), Material::getGenericMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialPropertyByName(), Material::getGenericOptionalMaterialProperty(), MaterialBase::getGenericZeroMaterialProperty(), BatchMaterial< Tuple, Output, Input >::getIndex(), AddZapdosReactions::getKernelName(), SolutionUserObject::getLocalVarIndex(), Marker::getMarkerValue(), Material::getMaterial(), FEProblemBase::getMaterial(), Material::getMaterialByName(), AuxKernelTempl< ComputeValueType >::getMaterialProperty(), NodalPatchRecovery::getMaterialProperty(), InterfaceMaterial::getMaterialProperty(), Material::getMaterialProperty(), SubProblem::getMaterialPropertyBlockNames(), SubProblem::getMaterialPropertyBoundaryNames(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOld(), NodalPatchRecovery::getMaterialPropertyOld(), InterfaceMaterial::getMaterialPropertyOld(), Material::getMaterialPropertyOld(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOlder(), NodalPatchRecovery::getMaterialPropertyOlder(), InterfaceMaterial::getMaterialPropertyOlder(), Material::getMaterialPropertyOlder(), MeshGenerator::getMesh(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshesByName(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MultiAppTransfer::getMultiApp(), InterfaceMaterial::getNeighborADMaterialProperty(), InterfaceMaterial::getNeighborMaterialProperty(), InterfaceMaterial::getNeighborMaterialPropertyOld(), InterfaceMaterial::getNeighborMaterialPropertyOlder(), Material::getOptionalADMaterialProperty(), Material::getOptionalMaterialProperty(), Material::getOptionalMaterialPropertyOld(), Material::getOptionalMaterialPropertyOlder(), FEProblemBase::getPositionsObject(), FEProblemBase::getPostprocessorValueByName(), AddReactions::getReactionKernelName(), ReporterData::getReporterInfo(), FEProblemBase::getSampler(), Transient::getTimeStepperName(), ProjectedStatefulMaterialStorageAction::getTypeEnum(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), Terminator::handleMessage(), FEProblemBase::hasFunction(), SubProblem::hasFunctor(), SubProblem::hasFunctorWithType(), hasOutputHelper(), FEProblemBase::hasPostprocessor(), FEProblemBase::hasPostprocessorValueByName(), FEProblemBase::hasUserObject(), init(), FEProblemBase::init(), IterationAdaptiveDT::init(), initExecutionTypes(), AttribName::initFrom(), NestedDivision::initialize(), SolutionScalarAux::initialSetup(), NodalVariableValue::initialSetup(), MultiAppProjectionTransfer::initialSetup(), SolutionUserObject::initialSetup(), initOutputList(), initPostprocessorOrVectorPostprocessorLists(), MaterialBase::initStatefulProperties(), Function::integral(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), MeshGenerator::isChildMeshGenerator(), MeshGenerator::isNullMeshName(), MeshGenerator::isParentMeshGenerator(), LinearCombinationFunction::LinearCombinationFunction(), FEProblemBase::logAdd(), LymberopoulosElectronBC::LymberopoulosElectronBC(), Marker::Marker(), Material::Material(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), Distribution::median(), MemoryUsageReporter::MemoryUsageReporter(), MeshGenerator::meshPropertyPrefix(), MooseVariableInterface< T >::MooseVariableInterface(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), NeumannCircuitVoltageMoles_KV::NeumannCircuitVoltageMoles_KV(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), NodalValueSampler::NodalValueSampler(), MooseBaseParameterInterface::objectErrorPrefix(), MeshGenerator::Comparator::operator()(), DOFMapOutput::output(), ProgressOutput::output(), Output::Output(), outputElementalVariables(), ConsoleUtils::outputExecutionInformation(), outputInput(), outputNodalVariables(), outputPostprocessors(), Exodus::outputPostprocessors(), Nemesis::outputPostprocessors(), TableOutput::outputReporter(), outputReporters(), outputScalarVariables(), outputSystemInformation(), outputVectorPostprocessors(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedODEKernel::ParsedODEKernel(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PointVariableSamplerBase::PointVariableSamplerBase(), MultiApp::readCommandLineArguments(), Receiver::Receiver(), Executor::Result::record(), FEProblemBase::registerRandomInterface(), GlobalParamsAction::remove(), MaterialBase::resetQpProperties(), MultiApp::restore(), SakiyamaEnergySecondaryElectronBC::SakiyamaEnergySecondaryElectronBC(), SakiyamaSecondaryElectronBC::SakiyamaSecondaryElectronBC(), ScalarComponentIC::ScalarComponentIC(), SecondaryElectronBC::SecondaryElectronBC(), SecondaryElectronEnergyBC::SecondaryElectronEnergyBC(), MultiApp::setAppOutputFileBase(), MooseMesh::setBoundaryName(), Control::setControllableValue(), Control::setControllableValueByName(), GlobalParamsAction::setDoubleIndexParam(), OutputWarehouse::setFileNumbers(), GlobalParamsAction::setParam(), FEProblemBase::setPostprocessorValueByName(), GlobalParamsAction::setScalarParam(), MooseMesh::setSubdomainName(), GlobalParamsAction::setTripleIndexParam(), Split::setup(), TransientMultiApp::setupApp(), GlobalParamsAction::setVectorParam(), SideCurrent::SideCurrent(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SideValueSampler::SideValueSampler(), TransientMultiApp::solveStep(), UserObject::spatialValue(), StitchedMesh::StitchedMesh(), SubProblem::storeBoundaryDelayedCheckMatProp(), SubProblem::storeBoundaryMatPropName(), SubProblem::storeBoundaryZeroMatProp(), SubProblem::storeSubdomainDelayedCheckMatProp(), SubProblem::storeSubdomainMatPropName(), SubProblem::storeSubdomainZeroMatProp(), MaterialBase::subdomainSetup(), TaggingInterface::TaggingInterface(), VectorPostprocessorVisualizationAux::timestepSetup(), MultiAppDofCopyTransfer::transfer(), TransientMultiApp::TransientMultiApp(), MooseBase::typeAndName(), MooseBaseParameterInterface::uniqueParameterName(), UserObject::UserObject(), UserObjectInterface::userObjectName(), MultiAppTransfer::variableIntegrityCheck(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), wantOutput(), Coupleable::writableCoupledValue(), and Coupleable::writableVariable().
objectErrorPrefix()
std::string MooseBaseParameterInterface::objectErrorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for an object.
Definition at line 58 of file MooseBaseParameterInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the class \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseParameterInterface::paramErrorMsg().
onInterval()
bool Output::onInterval () protected virtual inherited
Returns true if the output interval is satisfied.
Definition at line 247 of file Output.C.
{
  // The output flag to return
  bool output = false;
  // Return true if the current step on the current output interval and within the output time range
  // and within the output step range
  if (_time >= _start_time && _time <= _end_time && _t_step >= _start_step &&
      _t_step <= _end_step && (_t_step % _interval) == 0)
    output = true;
  // Return false if 'sync_only' is set to true
  if (_sync_only)
    output = false;
  if (_sync_times_object)
  {
    const auto & sync_times = _sync_times_object->getUniqueTimes();
    if (sync_times != _sync_times)
      mooseError("The provided sync times object has changing time values. Only static time "
                 "values are supported since time steppers take sync times from the output "
                 "warehouse which determines its sync times at output construction time.");
  }
  // If sync times are not skipped, return true if the current time is a sync_time
  if (_sync_times.find(_time) != _sync_times.end())
    output = true;
  // check if enough time has passed between outputs
  if (_time > _last_output_time && _last_output_time + _minimum_time_interval > _time + _t_tol)
    return false;
  // Return the output status
  return output;
}
Referenced by Console::output(), Output::outputStep(), OversampleOutput::outputStep(), and Checkpoint::shouldOutput().
output()
void AdvancedOutput::output () protected virtual
A single call to this function should output all the necessary data for a single timestep.
By default this function performs calls each of the four virtual output methods: outputScalarVariables(), outputPostprocessors(), outputElementalVariables(), and outputNodalVariables(). But, only if output exists for each type.
See also
outputNodalVariables outputElementalVariables outputScalarVariables outputPostprocessors
Implements Output.
Reimplemented in Console, CSV, Exodus, GMVOutput, Gnuplot, JSONOutput, Nemesis, Tecplot, VTKOutput, XDA, XMLOutput, and CSV.
Definition at line 274 of file AdvancedOutput.C.
{
  const auto & type = _current_execute_flag;
  // (re)initialize the list of available items for output
  init();
  // Call the various output types, if data exists
  if (wantOutput("nodal", type))
  {
    outputNodalVariables();
    _last_execute_time["nodal"] = _time;
  }
  if (wantOutput("elemental", type))
  {
    outputElementalVariables();
    _last_execute_time["elemental"] = _time;
  }
  if (wantOutput("postprocessors", type))
  {
    outputPostprocessors();
    _last_execute_time["postprocessors"] = _time;
  }
  if (wantOutput("vector_postprocessors", type))
  {
    outputVectorPostprocessors();
    _last_execute_time["vector_postprocessors"] = _time;
  }
  if (wantOutput("scalars", type))
  {
    outputScalarVariables();
    _last_execute_time["scalars"] = _time;
  }
  if (wantOutput("system_information", type))
  {
    outputSystemInformation();
    _last_execute_time["system_information"] = _time;
  }
  if (wantOutput("input", type))
  {
    outputInput();
    _last_execute_time["input"] = _time;
  }
  if (wantOutput("reporters", type))
  {
    outputReporters();
    _last_execute_time["reporters"] = _time;
  }
}
Referenced by initOutputList(), CSV::output(), Exodus::output(), Gnuplot::output(), JSONOutput::output(), Nemesis::output(), XMLOutput::output(), and OversampleOutput::outputStep().
outputElementalVariables()
void AdvancedOutput::outputElementalVariables () protected virtual
Performs output of elemental nonlinear variables The child class must define this method to output the nonlinear variables as desired.
See also
Exodus::outputElementalVariables
Reimplemented in Exodus.
Definition at line 207 of file AdvancedOutput.C.
{
  mooseError(
      "Individual output of elemental variables is not support for this output object named '",
      name(),
      "'");
}
Referenced by output().
outputInput()
void AdvancedOutput::outputInput () protected virtual
Performs the output of the input file By default this method does nothing and is not called, the individual Output objects are responsible for calling it.
Reimplemented in Console, and Exodus.
Definition at line 247 of file AdvancedOutput.C.
{
  mooseError("Output of the input file information is not support for this output object named '",
             name(),
             "'");
}
Referenced by output().
outputNodalVariables()
void AdvancedOutput::outputNodalVariables () protected virtual
Performs output of nodal nonlinear variables The child class must define this method to output the nonlinear variables as desired.
See also
Exodus::outputNodalVariables
Reimplemented in Exodus.
Definition at line 199 of file AdvancedOutput.C.
{
  mooseError("Individual output of nodal variables is not support for the output object named '",
             name(),
             "'");
}
Referenced by output().
outputPostprocessors()
void AdvancedOutput::outputPostprocessors () protected virtual
Performs output of postprocessors The child class must define this method to output the postprocessors as desired.
See also
Exodus::outputPostprocessors
Reimplemented in Console, CSV, Exodus, Nemesis, and TableOutput.
Definition at line 216 of file AdvancedOutput.C.
{
  mooseError("Individual output of postprocessors is not support for this output object named '",
             name(),
             "'");
}
Referenced by output().
outputReporters()
void AdvancedOutput::outputReporters () protected virtual
Output Reporter values.
The child class must define this method to output the Reporter values as desired
See also
CSV::outputReporters
Reimplemented in Console, CSV, Exodus, JSONOutput, and TableOutput.
Definition at line 255 of file AdvancedOutput.C.
{
  mooseError(
      "Output of the Reporter value(s) is not support for this output object named '", name(), "'");
}
Referenced by output().
outputScalarVariables()
void AdvancedOutput::outputScalarVariables () protected virtual
Performs output of scalar variables The child class must define this method to output the scalar variables as desired.
See also
Exodus::outputScalarVariables
Reimplemented in Console, CSV, Exodus, Nemesis, and TableOutput.
Definition at line 233 of file AdvancedOutput.C.
{
  mooseError(
      "Individual output of scalars is not support for this output object named '", name(), "'");
}
Referenced by output().
outputStep()
void Output::outputStep (const ExecFlagType & type) virtual inherited
A single call to this function should output all the necessary data for a single timestep.
Parameters
type The type execution flag (see Moose.h)
See also
outputNodalVariables outputElementalVariables outputScalarVariables outputPostprocessors
Reimplemented in Checkpoint, and OversampleOutput.
Definition at line 208 of file Output.C.
{
  // Output is not allowed
  if (!_allow_output && type != EXEC_FORCED)
    return;
  // If recovering disable output of initial condition, it was already output
  if (type == EXEC_INITIAL && _app.isRecovering())
    return;
  // Return if the current output is not on the desired interval
  if (type != EXEC_FINAL && !onInterval())
    return;
  // store current simulation time
  _last_output_time = _time;
  // set current type
  _current_execute_flag = type;
  // Call the output method
  if (shouldOutput())
  {
    TIME_SECTION("outputStep", 2, "Outputting Step");
    output();
  }
  _current_execute_flag = EXEC_NONE;
}
outputSystemInformation()
void AdvancedOutput::outputSystemInformation () protected virtual
Reimplemented in Console, and JSONOutput.
Definition at line 240 of file AdvancedOutput.C.
{
  mooseError(
      "Output of system information is not support for this output object named '", name(), "'");
}
Referenced by output().
outputVectorPostprocessors()
void AdvancedOutput::outputVectorPostprocessors () protected virtual
Performs output of VectorPostprocessors The child class must define this method to output the VectorPostprocessors as desired.
Reimplemented in Console, CSV, TableOutput, and XMLOutput.
Definition at line 224 of file AdvancedOutput.C.
{
  mooseError(
      "Individual output of VectorPostprocessors is not support for this output object named '",
      name(),
      "'");
}
Referenced by output().
paramError()
template<typename... Args> void MooseBaseParameterInterface::paramError (const std::string & param, Args... args) const inherited
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseError - only printing a message using the given args.
Definition at line 233 of file MooseBaseParameterInterface.h.
{
  Moose::show_trace = false;
  std::string msg = paramErrorMsg(param, std::forward<Args>(args)...);
  callMooseErrorRaw(msg, &_moose_base->getMooseApp());
  Moose::show_trace = true;
}
Referenced by HierarchicalGridPartitioner::_do_partition(), SetupDebugAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), ADDGKernel::ADDGKernel(), ReporterPointSource::addPoints(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ADNodalKernel::ADNodalKernel(), ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), AdvectiveFluxAux::AdvectiveFluxAux(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), ArrayBodyForce::ArrayBodyForce(), ArrayDGKernel::ArrayDGKernel(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayDirichletBC::ArrayDirichletBC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), ArrayPenaltyDirichletBC::ArrayPenaltyDirichletBC(), ArrayVacuumBC::ArrayVacuumBC(), BlockDeletionGenerator::BlockDeletionGenerator(), BlockWeightedPartitioner::BlockWeightedPartitioner(), BoundsAuxBase::BoundsAuxBase(), BreakMeshByBlockGenerator::BreakMeshByBlockGenerator(), BuildArrayVariableAux::BuildArrayVariableAux(), PiecewiseTabularBase::buildFromFile(), CartesianGridDivision::CartesianGridDivision(), UserObjectInterface::castUserObject(), checkComponent(), MeshGenerator::checkGetMesh(), PostprocessorInterface::checkParam(), Coupleable::checkVar(), MultiAppTransfer::checkVariable(), CircularBoundaryCorrectionGenerator::CircularBoundaryCorrectionGenerator(), CircularBoundaryCorrectionGenerator::circularCenterCalculator(), MultiAppGeneralFieldTransfer::closestToPosition(), CombinerGenerator::CombinerGenerator(), CompositionDT::CompositionDT(), ConcentricCircleMeshGenerator::ConcentricCircleMeshGenerator(), LibtorchNeuralNetControl::conditionalParameterError(), ConstantVectorPostprocessor::ConstantVectorPostprocessor(), ContainsPointAux::ContainsPointAux(), CopyValueAux::CopyValueAux(), Coupleable::Coupleable(), CoupledForceTempl< is_ad >::CoupledForceTempl(), CoupledValueFunctionMaterialTempl< is_ad >::CoupledValueFunctionMaterialTempl(), MultiApp::createApp(), MeshGeneratorSystem::createMeshGenerator(), CylindricalGridDivision::CylindricalGridDivision(), ConstantReporter::declareConstantReporterValues(), AccumulateReporter::declareLateValues(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DGLowerDKernel::DGLowerDKernel(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementLengthAux::ElementLengthAux(), ElementLpNormAux::ElementLpNormAux(), ElementValueSampler::ElementValueSampler(), ReporterPointSource::errorCheck(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), ExtraElementIDAux::ExtraElementIDAux(), ExtraElementIntegerDivision::ExtraElementIntegerDivision(), FEProblemSolve::FEProblemSolve(), FillBetweenCurvesGenerator::FillBetweenCurvesGenerator(), FillBetweenSidesetsGenerator::FillBetweenSidesetsGenerator(), ReporterPointSource::fillPoint(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), InternalSideIndicator::finalize(), FixedPointSolve::FixedPointSolve(), ForcingFunctionAux::ForcingFunctionAux(), FunctionArrayAux::FunctionArrayAux(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorAux::FunctorAux(), FunctorBinnedValuesDivision::FunctorBinnedValuesDivision(), FunctorElementalGradientAuxTempl< is_ad >::FunctorElementalGradientAuxTempl(), FunctorPositions::FunctorPositions(), FunctorVectorElementalAuxTempl< is_ad >::FunctorVectorElementalAuxTempl(), FVFluxBC::FVFluxBC(), FVInterfaceKernel::FVInterfaceKernel(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), FVTwoVarContinuityConstraint::FVTwoVarContinuityConstraint(), AdvancedExtruderGenerator::generate(), BlockDeletionGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundaryDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), BreakMeshByBlockGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), CombinerGenerator::generate(), ExplodeMeshGenerator::generate(), ExtraNodesetGenerator::generate(), FillBetweenCurvesGenerator::generate(), FillBetweenSidesetsGenerator::generate(), GeneratedMeshGenerator::generate(), MeshCollectionGenerator::generate(), MeshExtruderGenerator::generate(), ParsedCurveGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), PropertyReadFile::getBlockData(), PropertyReadFile::getData(), Sampler::getGlobalSamples(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), Sampler::getLocalSamples(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), Sampler::getNextLocalRow(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectName(), HFEMDirichletBC::HFEMDirichletBC(), MultiApp::init(), BlockWeightedPartitioner::initialize(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), PiecewiseConstantFromCSV::initialSetup(), LibtorchControlValuePostprocessor::initialSetup(), ReferenceResidualProblem::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), HistogramVectorPostprocessor::initialSetup(), AddMetaDataGenerator::inputChecker(), IntegratedBC::IntegratedBC(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceValueUserObjectAux::InterfaceValueUserObjectAux(), InterpolatedStatefulMaterialTempl< T >::InterpolatedStatefulMaterialTempl(), InversePowerMethod::InversePowerMethod(), IterationAdaptiveDT::IterationAdaptiveDT(), MultiApp::keepSolutionDuringRestore(), Kernel::Kernel(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LinearCombinationFunction::LinearCombinationFunction(), LowerDIntegratedBC::LowerDIntegratedBC(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), MaterialADConverterTempl< T >::MaterialADConverterTempl(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), PatternedMeshGenerator::mergeSubdomainNameMaps(), MeshCollectionGenerator::MeshCollectionGenerator(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshDivisionAux::MeshDivisionAux(), MeshGenerator::MeshGenerator(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarNodalAuxKernelTempl< ComputeValueType >::MortarNodalAuxKernelTempl(), MultiApp::moveApp(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), NestedDivision::NestedDivision(), NodalBC::NodalBC(), NodalEqualValueConstraint::NodalEqualValueConstraint(), NodalKernel::NodalKernel(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), NodalValueSampler::NodalValueSampler(), Output::Output(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), PatchMeshGenerator::PatchMeshGenerator(), PatternedMeshGenerator::PatternedMeshGenerator(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), PeriodicSegmentalConstraint::PeriodicSegmentalConstraint(), PIDTransientControl::PIDTransientControl(), PlaneDeletionGenerator::PlaneDeletionGenerator(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), PolyLineMeshGenerator::PolyLineMeshGenerator(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), LibmeshPartitioner::prepareBlocksForSubdomainPartitioner(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), PropertyReadFile::PropertyReadFile(), RandomIC::RandomIC(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readXda(), ReferenceResidualProblem::ReferenceResidualProblem(), RefineBlockGenerator::RefineBlockGenerator(), RefineSidesetGenerator::RefineSidesetGenerator(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setPartitioner(), TimeSequenceStepperBase::setupSequence(), SingleRankPartitioner::SingleRankPartitioner(), SphericalGridDivision::SphericalGridDivision(), SymmetryTransformGenerator::SymmetryTransformGenerator(), Terminator::Terminator(), TimeDerivativeAux::TimeDerivativeAux(), Transfer::Transfer(), TransformGenerator::TransformGenerator(), TransientMultiApp::TransientMultiApp(), ParsedCurveGenerator::tSectionSpaceDefiner(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), UserObject::UserObject(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), VolumeAux::VolumeAux(), XYDelaunayGenerator::XYDelaunayGenerator(), and XYMeshLineCutter::XYMeshLineCutter().
paramErrorMsg()
template<typename... Args> std::string MooseBaseParameterInterface::paramErrorMsg (const std::string & param, Args... args) const inline private inherited
Definition at line 171 of file MooseBaseParameterInterface.h.
  {
    auto param_prefix = paramErrorPrefix(_pars, param);
    // With no input location information, append object info (name + type)
    const std::string object_prefix =
        _pars.inputLocation(param).empty() ? objectErrorPrefix("parameter error") : "";
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    // Wrap error message to a separate line from param_prefix if it is about to
    // blow past 100 chars.  But only wrap if the param_prefix is long enough (12
    // chars) for the wrap to buy us much extra length. We don't check object_prefix
    // here because it will go before the parameter error
    if ((param_prefix.size() > 12 && msg.size() + param_prefix.size() > 99) ||
        msg.find("\n") != std::string::npos)
    {
      if (param_prefix.size() > 0 && param_prefix[param_prefix.size() - 1] != ':')
        param_prefix += ":";
      return object_prefix + param_prefix + "\n    " + MooseUtils::replaceAll(msg, "\n", "\n    ");
    }
    return object_prefix + param_prefix + " " + msg;
  }
Referenced by MooseBaseParameterInterface::paramError(), MooseBaseParameterInterface::paramInfo(), and MooseBaseParameterInterface::paramWarning().
parameters()
const InputParameters & MooseBaseParameterInterface::parameters () const inline inherited
Get the parameters of the object.
Returns
The parameters of the object
Definition at line 53 of file MooseBaseParameterInterface.h.
{ return _pars; }
Referenced by SetupDebugAction::act(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), FEProblemBase::addPostprocessor(), FEProblemBase::addPredictor(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), AdvancedOutput(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), Moose::assemble_matrix(), AuxScalarKernel::AuxScalarKernel(), BoundsAuxBase::BoundsAuxBase(), MooseMesh::buildTypedMesh(), UserObjectInterface::castUserObject(), PostprocessorInterface::checkParam(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), Moose::compute_bounds(), Moose::compute_jacobian(), Moose::compute_nearnullspace(), Moose::compute_nullspace(), Moose::compute_postcheck(), Moose::compute_transpose_nullspace(), LibtorchNeuralNetControl::conditionalParameterError(), Console::Console(), MultiApp::createApp(), Postprocessor::declareValue(), DumpObjectsProblem::deduceNecessaryParameters(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), DumpObjectsProblem::dumpObjectHelper(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElectronsFromIonization::ElectronsFromIonization(), Executor::Executor(), Exodus::Exodus(), FEProblem::FEProblem(), FEProblemBase::FEProblemBase(), FixedPointSolve::FixedPointSolve(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GapValueAux::GapValueAux(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), MooseBaseParameterInterface::getCheckedPointerParam(), ExecutorInterface::getExecutor(), Material::getMaterial(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), UserObjectInterface::getUserObjectName(), VectorPostprocessorInterface::getVectorPostprocessorName(), GhostingUserObject::GhostingUserObject(), HphiRadialInterface::HphiRadialInterface(), AttribSystem::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), FullSolveMultiApp::initialSetup(), FEProblemBase::initNullSpaceVectors(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), isValid(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseAppCoordTransform::MooseAppCoordTransform(), MooseVariableInterface< T >::MooseVariableInterface(), MultiApp::MultiApp(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodeFaceConstraint::NodeFaceConstraint(), PatchMeshGenerator::PatchMeshGenerator(), PenetrationAux::PenetrationAux(), PicardSolve::PicardSolve(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), ProjectedStatefulMaterialStorageAction::processProperty(), MultiAppProjectionTransfer::projectSolution(), PropertyReadFile::PropertyReadFile(), PseudoTimestep::PseudoTimestep(), RandomIC::RandomIC(), InputParameterWarehouse::removeInputParameters(), OutputWarehouse::resetFileBase(), MooseAppCoordTransform::setCoordinateSystem(), FEProblemBase::setInputParametersFEProblem(), FEProblem::setInputParametersFEProblem(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SteffensenSolve::SteffensenSolve(), DumpObjectsProblem::stringifyParameters(), TaggingInterface::TaggingInterface(), Transfer::Transfer(), Transient::Transient(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
paramInfo()
template<typename... Args> void MooseBaseParameterInterface::paramInfo (const std::string & param, Args... args) const inherited
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseInfo - only printing a message using the given args.
Definition at line 250 of file MooseBaseParameterInterface.h.
{
  mooseInfo(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by TransientMultiApp::TransientMultiApp().
paramWarning()
template<typename... Args> void MooseBaseParameterInterface::paramWarning (const std::string & param, Args... args) const inherited
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseWarning - only printing a message using the given args.
Definition at line 243 of file MooseBaseParameterInterface.h.
{
  mooseWarning(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by MultiAppNearestNodeTransfer::execute(), FEProblemSolve::FEProblemSolve(), PlaneIDMeshGenerator::generate(), UniqueExtraIDMeshGenerator::generate(), Terminator::initialSetup(), and MooseMesh::MooseMesh().
perfGraph()
PerfGraph & PerfGraphInterface::perfGraph () inherited
Get the PerfGraph.
Definition at line 78 of file PerfGraphInterface.C.
{
  return _pg_moose_app.perfGraph();
}
Referenced by CommonOutputAction::act(), PerfGraphData::finalize(), and PerfGraphOutput::output().
petscLinearOutput()
PetscErrorCode PetscOutputInterface::petscLinearOutput (KSP , PetscInt its, PetscReal fnorm, void * void_ptr) static protected inherited
Performs the output onlinear iterations This is the monitor method that PETSc will call on linear iterations.
This is one of three locations where we explicitly flush the output buffers during a simulation: PetscOutput::petscNonlinearOutput() PetscOutput::petscLinearOutput() OutputWarehouse::outputStep()
All other Console output should be using newlines to avoid covering buffer errors and to avoid excessive I/O. This call is necessary. In the PETSc callback the context bypasses the OutputWarehouse.
Definition at line 75 of file PetscOutput.C.
{
  // Get the primary outputter object
  PetscOutput * primary_ptr = static_cast<PetscOutput *>(void_ptr);
  // loop over all interface objects
  for (const auto poi_ptr : primary_ptr->getMooseApp().getInterfaceObjects<PetscOutputInterface>())
  {
    auto ptr = poi_ptr->_petsc_output;
    // check time
    if (!ptr->inLinearTimeWindow())
      continue;
    // Update the pseudo time
    ptr->_linear_time += ptr->_linear_dt;
    // Set the current norm and iteration number
    ptr->_norm = norm;
    ptr->_linear_iter = its;
    // Set the flag indicating that output is occurring on the non-linear residual
    ptr->_on_linear_residual = true;
    // Perform the output
    ptr->outputStep(EXEC_LINEAR);
    ptr->_app.getOutputWarehouse().flushConsoleBuffer();
    // Reset the linear output flag and the simulation time
    ptr->_on_linear_residual = false;
  }
  // Done
  return 0;
}
Referenced by PetscOutput::solveSetup().
petscNonlinearOutput()
PetscErrorCode PetscOutputInterface::petscNonlinearOutput (SNES , PetscInt its, PetscReal fnorm, void * void_ptr) static protected inherited
Performs the output on non-linear iterations This is the monitor method that PETSc will call on non-linear iterations.
This is one of three locations where we explicitly flush the output buffers during a simulation: PetscOutput::petscNonlinearOutput() PetscOutput::petscLinearOutput() OutputWarehouse::outputStep()
All other Console output should be using newlines to avoid covering buffer errors and to avoid excessive I/O. This call is necessary. In the PETSc callback the context bypasses the OutputWarehouse.
Definition at line 25 of file PetscOutput.C.
{
  // Get the primary outputter object
  PetscOutput * primary_ptr = static_cast<PetscOutput *>(void_ptr);
  // loop over all interface objects
  for (const auto poi_ptr : primary_ptr->getMooseApp().getInterfaceObjects<PetscOutputInterface>())
  {
    auto ptr = poi_ptr->_petsc_output;
    // check time
    if (!ptr->inNonlinearTimeWindow())
      continue;
    // Update the pseudo times
    ptr->_nonlinear_time += ptr->_nonlinear_dt;
    ptr->_linear_time = ptr->_nonlinear_time;
    // Set the current norm and iteration number
    ptr->_norm = norm;
    ptr->_nonlinear_iter = its;
    // Set the flag indicating that output is occurring on the non-linear residual
    ptr->_on_nonlinear_residual = true;
    // Perform the output
    ptr->outputStep(EXEC_NONLINEAR);
    ptr->_app.getOutputWarehouse().flushConsoleBuffer();
    // Reset the non-linear output flag and the simulation time
    ptr->_on_nonlinear_residual = false;
  }
  // Done
  return 0;
}
Referenced by PetscOutput::solveSetup().
possiblyCheckHasReporter()
template<typename T > void ReporterInterface::possiblyCheckHasReporter (const ReporterName & reporter_name, const std::string & param_name = "") const private inherited
Helpers for "possibly" checking if a Reporter value exists.
This is only able to check for existance after all Reporters have been added (after the task creating them has been called). If called before said task, this will do nothing, hence the "possibly". This allows us to have errors reported directly by the object requesting the Reporter instead of through a system with less context.
Definition at line 196 of file ReporterInterface.h.
{
  if (reportersAdded() && !hasReporterValueByName<T>(reporter_name))
  {
    std::stringstream oss;
    oss << "A Reporter value with the name \"" << reporter_name << "\" and type \""
        << MooseUtils::prettyCppType<T>() << "\" was not found.";
    if (_ri_params.isParamValid(param_name))
      _ri_moose_object.paramError(param_name, oss.str());
    else
      _ri_moose_object.mooseError(oss.str());
  }
}
possiblyCheckHasVectorPostprocessor()
void VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor (const std::string & param_name, const std::string & vector_name) const private inherited
Helpers for "possibly" checking if a vpp exists.
This is only able to check for existance after all vpps have been added (after the task creating them has been called). If called before said task, this will do nothing, hence the "possibly". This allows us to have errors reported directly by the object requesting the vpp instead of through a system with less context.
Definition at line 228 of file VectorPostprocessorInterface.C.
{
  // Can't do checking if vpps have not been added
  if (!vectorPostprocessorsAdded())
    return;
  if (!hasVectorPostprocessor(param_name))
    _vpi_moose_object.paramError(param_name,
                                 "A VectorPostprocessor with the name \"",
                                 getVectorPostprocessorName(param_name),
                                 "\" was not found.");
  if (!hasVectorPostprocessor(param_name, vector_name))
    _vpi_moose_object.paramError(param_name,
                                 "The VectorPostprocessor \"",
                                 getVectorPostprocessorName(param_name),
                                 "\" does not have a vector named \"",
                                 vector_name,
                                 "\".");
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValue(), VectorPostprocessorInterface::getScatterVectorPostprocessorValueOld(), VectorPostprocessorInterface::getVectorPostprocessorValue(), and VectorPostprocessorInterface::getVectorPostprocessorValueOld().
possiblyCheckHasVectorPostprocessorByName()
void VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName (const VectorPostprocessorName & name, const std::string & vector_name) const private inherited
Definition at line 250 of file VectorPostprocessorInterface.C.
{
  // Can't do checking if vpps have not been added
  if (!vectorPostprocessorsAdded())
    return;
  if (!hasVectorPostprocessorByName(name))
    _vpi_moose_object.mooseError(
        "A VectorPostprocessor with the name \"", name, "\" was not found.");
  if (!hasVectorPostprocessorByName(name, vector_name))
    _vpi_moose_object.mooseError("The VectorPostprocessor \"",
                                 name,
                                 "\" does not have a vector named \"",
                                 vector_name,
                                 "\".");
}
Referenced by VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), and VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper().
postprocessorsAdded()
bool PostprocessorInterface::postprocessorsAdded () const private inherited
Returns
True if all pps have been added (the task associated with adding them is complete)
Definition at line 264 of file PostprocessorInterface.C.
{
  return _ppi_feproblem.getMooseApp().actionWarehouse().isTaskComplete("add_postprocessor");
}
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), and PostprocessorInterface::hasPostprocessorByName().
registerRestartableDataOnApp()
RestartableDataValue & Restartable::registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const private inherited
Helper function for actually registering the restartable data.
Definition at line 51 of file Restartable.C.
{
  return _restartable_app.registerRestartableData(
      std::move(data), tid, _restartable_read_only, _metaname);
}
Referenced by Restartable::declareRestartableDataHelper().
registerRestartableNameWithFilterOnApp()
void Restartable::registerRestartableNameWithFilterOnApp (const std::string & name, Moose::RESTARTABLE_FILTER filter) private inherited
Helper function for actually registering the restartable data.
Definition at line 59 of file Restartable.C.
{
  _restartable_app.registerRestartableNameWithFilter(name, filter);
}
Referenced by Restartable::declareRecoverableData().
registerTimedSection() [1/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
Returns
The ID of the section - use when starting timing
Definition at line 53 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(timed_section_name, level);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
registerTimedSection() [2/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level, const std::string & live_message, const bool print_dots = true) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
live_message The message to be printed to the screen during execution
print_dots Whether or not progress dots should be printed for this section
Returns
The ID of the section - use when starting timing
Definition at line 64 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(
        timedSectionName(section_name), level, live_message, print_dots);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
reportersAdded()
bool ReporterInterface::reportersAdded () const private inherited
Returns
True if all Reporters have been added (the task associated with adding them is complete)
Definition at line 71 of file ReporterInterface.C.
{
  return _ri_fe_problem_base.getMooseApp().actionWarehouse().isTaskComplete("add_reporter");
}
Referenced by ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), and ReporterInterface::possiblyCheckHasReporter().
residualSetup()
void SetupInterface::residualSetup () virtual inherited
Gets called just before the residual is computed and before this object is asked to do its job.
Reimplemented in NodeFaceConstraint, Function, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 55 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::residualSetup(), ComputeFVFluxResidualThread< RangeType >::setup(), and ComputeFVFluxRJThread< RangeType >::setup().
restartableName()
std::string Restartable::restartableName (const std::string & data_name) const protected inherited
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
This should only be used in this interface and in testing.
Definition at line 66 of file Restartable.C.
{
  return _restartable_system_name + "/" + _restartable_name + "/" + data_name;
}
Referenced by Restartable::declareRecoverableData(), and Restartable::declareRestartableDataHelper().
setFileBase()
void FileOutput::setFileBase (const std::string & file_base) inherited
Sets the file base string if the 'file_base' parameter is not set.
Parameters
file_base The new file base string
Definition at line 118 of file FileOutput.C.
{
  if (!isParamValid("file_base"))
    setFileBaseInternal(file_base);
}
Referenced by OutputWarehouse::resetFileBase().
setFileBaseInternal()
void FileOutput::setFileBaseInternal (const std::string & file_base) protected virtual inherited
Internal function that sets the file_base.
Parameters
file_base The new file base string
Reimplemented in OversampleOutput.
Definition at line 125 of file FileOutput.C.
{
  _file_base = file_base;
  // Append the date/time
  if (getParam<bool>("append_date"))
  {
    std::string format;
    if (isParamValid("append_date_format"))
      format = getParam<std::string>("append_date_format");
    else
      format = "%Y-%m-%dT%T%z";
    // Get the current time
    std::time_t now;
    ::time(&now); // need :: to avoid confusion with time() method of Output class
    // Format the time
    char buffer[80];
    strftime(buffer, 80, format.c_str(), localtime(&now));
    _file_base += "_";
    _file_base += buffer;
  }
  // Check the file directory of file_base and create if needed
  // Check if _file_base is an absolute path
  std::string base;
  if (_file_base.find_first_of("/", 0) == 0)
    base = "./" + MooseUtils::relativepath(_file_base);
  else
    base = "./" + _file_base;
  base = base.substr(0, base.find_last_of('/'));
  if (_app.processor_id() == 0 && access(base.c_str(), W_OK) == -1)
  {
    // Directory does not exist. Loop through incremental directories and create as needed.
    std::vector<std::string> path_names;
    MooseUtils::tokenize(base, path_names);
    std::string inc_path = path_names[0];
    for (unsigned int i = 1; i < path_names.size(); ++i)
    {
      inc_path += '/' + path_names[i];
      if (access(inc_path.c_str(), W_OK) == -1)
        if (Utility::mkdir(inc_path.c_str()) == -1)
          mooseError("Could not create directory: " + inc_path + " for file base: " + _file_base);
    }
  }
}
Referenced by FileOutput::FileOutput(), FileOutput::setFileBase(), and OversampleOutput::setFileBaseInternal().
setFileNumber()
void FileOutput::setFileNumber (unsigned int num) inherited
Sets the file number manually.
This method was implemented for the MultiApp system, particularly when reseting an application and a new output file is desired after the reset.
Definition at line 175 of file FileOutput.C.
{
  _file_num = num;
}
Referenced by OutputWarehouse::setFileNumbers().
shouldOutput()
bool AdvancedOutput::shouldOutput () protected virtual
Handles logic for determining if a step should be output.
Returns
True if a call if output should be performed
Reimplemented from FileOutput.
Definition at line 262 of file AdvancedOutput.C.
{
  if (!checkFilename())
    return false;
  if (hasOutput(_current_execute_flag))
    return true;
  else
    return Output::shouldOutput();
}
Referenced by OversampleOutput::outputStep().
solveSetup()
void PetscOutput::solveSetup () override private virtual inherited
Internal setup function that executes at the beginning of the time step.
Reimplemented from Output.
Definition at line 217 of file PetscOutput.C.
{
  // Update the pseudo times
  _nonlinear_time = _time_old; // non-linear time starts with the previous time step
  if (_dt != 0)
    // set the pseudo non-linear timestep as fraction
    // of real timestep for transient executioners
    _nonlinear_dt = _dt / _nonlinear_dt_divisor;
  else
    // set the pseudo non-linear timestep for steady
    // executioners (here _dt==0)
    _nonlinear_dt = 1. / _nonlinear_dt_divisor;
  _linear_dt = _nonlinear_dt / _linear_dt_divisor; // set the pseudo linear timestep
  // only the first PetscOutput object registers a DM monitor for linear and nonlinear
  // all other PetscOutput objects are dispatched from that one monitor (per app).
  if (_app.getInterfaceObjects<PetscOutputInterface>()[0] != this)
    return;
  // Extract the non-linear and linear solvers from PETSc
  NonlinearSystemBase & nl = _problem_ptr->currentNonlinearSystem();
  SNES snes = nl.getSNES();
  KSP ksp;
  SNESGetKSP(snes, &ksp);
  // Set the PETSc monitor functions (register the nonlinear callback so that linear outputs
  // get an updated nonlinear iteration number)
  // Not every Output should register its own DM monitor! Just register one each of nonlinear
  // and linear and dispatch all Outputs from there!
  auto ierr1 = SNESMonitorSet(snes, petscNonlinearOutput, this, LIBMESH_PETSC_NULLPTR);
  CHKERRABORT(_communicator.get(), ierr1);
  auto ierr2 = KSPMonitorSet(ksp, petscLinearOutput, this, LIBMESH_PETSC_NULLPTR);
  CHKERRABORT(_communicator.get(), ierr2);
}
subdomainSetup()
void SetupInterface::subdomainSetup () virtual inherited
Gets called when the subdomain changes (i.e.
in a Jacobian or residual loop) and before this object is asked to do its job
Reimplemented in Material, MaterialBase, GeneralUserObject, NodalUserObject, ThreadedGeneralUserObject, and Constraint.
Definition at line 60 of file SetupInterface.C.
{
}
time()
Real PetscOutput::time () override virtual inherited
Get the output time.
This outputter enables the ability to perform output on the nonlinear and linear iterations performed by PETSc. To separate theses outputs within the output a pseudo time is defined, this function provides this time and it should be used in place of _time from Outputter.
Reimplemented from Output.
Definition at line 254 of file PetscOutput.C.
{
  if (_on_nonlinear_residual)
    return _nonlinear_time;
  else if (_on_linear_residual)
    return _linear_time;
  else
    return Output::time();
}
Referenced by PetscOutput::getOutputTime(), and FileOutput::setFileBaseInternal().
timedSectionName()
std::string PerfGraphInterface::timedSectionName (const std::string & section_name) const protected inherited
Returns
The name of the timed section with the name section_name.
Optionally adds a prefix if one is defined.
Definition at line 47 of file PerfGraphInterface.C.
{
  return _prefix.empty() ? "" : (_prefix + "::") + section_name;
}
Referenced by PerfGraphInterface::registerTimedSection().
timeOld()
Real Output::timeOld () virtual inherited
Get the old output time.
Returns
The old output time, which may be different than the simulation time
See also
time()
Definition at line 293 of file Output.C.
{
  if (_transient)
    return _time_old;
  else
    return _t_step - 1;
}
Referenced by Console::writeTimestepInformation().
timeStep()
int Output::timeStep () virtual inherited
Get the current time step.
Definition at line 320 of file Output.C.
{
  return _t_step;
}
Referenced by Checkpoint::filename(), JSONOutput::filename(), CSV::getVectorPostprocessorFileName(), Checkpoint::shouldOutput(), and Console::writeTimestepInformation().
timestepSetup()
void SetupInterface::timestepSetup () virtual inherited
Gets called at the beginning of the timestep before this object is asked to do its job.
Reimplemented in VectorPostprocessorVisualizationAux, EqualValueEmbeddedConstraint, Function, Console, JSONOutput, Positions, MemoryUsage, NumNonlinearIterations, Times, SolutionUserObject, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, MooseVariableFV< T >, and VectorMemoryUsage.
Definition at line 45 of file SetupInterface.C.
{
}
Referenced by JSONOutput::timestepSetup(), and MooseVariableField< OutputType >::timestepSetup().
type()
const std::string & MooseBase::type () const inline inherited
Get the type of this class.
Returns
the name of the type of this class
Definition at line 41 of file MooseBase.h.
{ return _type; }
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), CreateProblemDefaultAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetupDebugAction::act(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::addDistribution(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addObject(), DistributedRectilinearMeshGenerator::addPoint(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), PhysicsBasedPreconditioner::addSystem(), FEProblemBase::addTimeIntegrator(), SubProblem::addVectorTag(), DisplacedProblem::addVectorTag(), FEProblemBase::advanceMultiApps(), FEProblemBase::backupMultiApps(), BoundaryPreservedMarker::BoundaryPreservedMarker(), DistributedRectilinearMeshGenerator::buildCube(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildPRefinementAndCoarseningMaps(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), FEProblemBase::computeAuxiliaryKernels(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpJacobian(), HFEMDirichletBC::computeLowerDQpJacobian(), ArrayHFEMDiffusion::computeLowerDQpJacobian(), HFEMDiffusion::computeLowerDQpJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), FEProblemBase::computeMultiAppsDT(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), DGCoupledAdvection::computeOffDiagJacobianHelper(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ScalarKernel::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueBoundaryConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), LinearNodalConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), DGConvection::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), InterfaceDiffusion::computeQpJacobian(), InterfaceReaction::computeQpJacobian(), DGCoupledAdvection::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), DGFunctionTemperatureAdvection::computeQpJacobian(), DGTemperatureAdvection::computeQpJacobian(), InterTemperatureAdvection::computeQpJacobian(), CoupledTiedValueConstraint::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), HFEMTestJump::computeQpOffDiagJacobian(), HFEMTrialJump::computeQpOffDiagJacobian(), DGCoupledAdvection::computeQpOffDiagJacobian(), ScalarKernel::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), EqualValueBoundaryConstraint::computeQpResidual(), EqualValueEmbeddedConstraint::computeQpResidual(), LinearNodalConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), DGConvection::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), DGEFieldAdvection::computeQpResidual(), HphiRadialInterface::computeQpResidual(), InterfaceAdvection::computeQpResidual(), InterfaceLogDiffusionElectrons::computeQpResidual(), PotentialSurfaceCharge::computeQpResidual(), ADDGAdvection::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), HFEMDiffusion::computeQpResidual(), HFEMTestJump::computeQpResidual(), HFEMTrialJump::computeQpResidual(), InterfaceDiffusion::computeQpResidual(), InterfaceReaction::computeQpResidual(), DGCoupledAdvection::computeQpResidual(), DGFunctionConvection::computeQpResidual(), DGFunctionTemperatureAdvection::computeQpResidual(), DGTemperatureAdvection::computeQpResidual(), InterTemperatureAdvection::computeQpResidual(), ArrayDGDiffusion::computeQpResidual(), ArrayHFEMDiffusion::computeQpResidual(), FEProblemBase::computeUserObjectByName(), FEProblemBase::computeUserObjects(), FEProblemBase::computeUserObjectsInternal(), BatchMaterial< Tuple, Output, Input >::construct(), DisplacedProblem::createQRules(), FEProblemBase::createQRules(), MeshGenerator::declareMeshProperty(), DumpObjectsProblem::deduceNecessaryParameters(), DumpObjectsProblem::dumpObjectHelper(), FEProblemBase::duplicateVariableCheck(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), MooseBaseErrorInterface::errorPrefix(), AB2PredictorCorrector::estimateTimeError(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finishMultiAppStep(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), ElementSubdomainIDGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), PatternedMeshGenerator::generate(), MeshGenerator::generateInternal(), MultiAppTransfer::getAppInfo(), TransfiniteMeshGenerator::getEdge(), ElementGenerator::getElemType(), FEProblemBase::getMaterial(), FEProblemBase::getMaterialData(), MaterialOutputAction::getParams(), ReporterData::getReporterInfo(), Transient::getTimeIntegratorName(), FEProblemBase::getTransfers(), SubProblem::getVectorTags(), DisplacedProblem::getVectorTags(), CommonOutputAction::hasConsole(), FEProblemBase::hasMultiApps(), hasOutput(), FEProblemBase::incrementMultiAppTStep(), initAvailableLists(), FunctorPositions::initialize(), FunctorTimes::initialize(), MultiAppConservativeTransfer::initialSetup(), ArrayDGDiffusion::initQpResidual(), initShowHideLists(), RelationshipManager::isType(), FEProblemBase::logAdd(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), SubProblem::numVectorTags(), DisplacedProblem::numVectorTags(), MooseBaseParameterInterface::objectErrorPrefix(), output(), Console::output(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), ProjectedStatefulMaterialStorageAction::processProperty(), SolutionInvalidInterface::registerInvalidSolutionInternal(), FEProblemBase::restoreMultiApps(), MeshRepairGenerator::separateSubdomainsByElementType(), FEProblemBase::setCoupling(), MooseBase::typeAndName(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), DisplacedProblem::updateGeomSearch(), FEProblemBase::updateGeomSearch(), UserObjectInterface::userObjectType(), and wantOutput().
typeAndName()
std::string MooseBase::typeAndName () const inline inherited
Get the class's combined type and name; useful in error handling.
Returns
The type and name of this class in the form '<type()> "<name()>"'.
Definition at line 53 of file MooseBase.h.
  {
    return type() + std::string(" \"") + name() + std::string("\"");
  }
Referenced by ReporterContext< T >::finalize(), and ReporterData::getReporterInfo().
uniqueName()
MooseObjectName MooseBaseParameterInterface::uniqueName () const inline inherited
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
Definition at line 58 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectName(_pars.get<std::string>("_unique_name"));
  }
Referenced by MooseBaseParameterInterface::connectControllableParams(), and Action::uniqueActionName().
uniqueParameterName()
MooseObjectParameterName MooseBaseParameterInterface::uniqueParameterName (const std::string & parameter_name) const inline inherited
The unique parameter name of a valid parameter of this object for accessing parameter controls.
Definition at line 43 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectParameterName(
        _pars.get<std::string>("_moose_base"), _moose_base->name(), parameter_name);
  }
validParams()
InputParameters AdvancedOutput::validParams () static
Definition at line 95 of file AdvancedOutput.C.
{
  // Get the parameters from the parent object
  InputParameters params = FileOutput::validParams();
  addAdvancedOutputParams(params);
  return params;
}
Referenced by JSONOutput::validParams(), Nemesis::validParams(), OversampleOutput::validParams(), TableOutput::validParams(), and XMLOutput::validParams().
vectorPostprocessorsAdded()
bool VectorPostprocessorInterface::vectorPostprocessorsAdded () const private inherited
Returns
True if all vpps have been added (the task associated with adding them is complete)
Definition at line 306 of file VectorPostprocessorInterface.C.
{
  return _vpi_feproblem.getMooseApp().actionWarehouse().isTaskComplete("add_vector_postprocessor");
}
Referenced by VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), and VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName().
wantOutput()
bool AdvancedOutput::wantOutput (const std::string & name, const ExecFlagType & type) private
Handles logic for determining if a step should be output.
Returns
True if a call if output should be performed
Definition at line 332 of file AdvancedOutput.C.
{
  // Ignore EXEC_FORCED for system information and input, there is no reason to force this
  if (type == EXEC_FORCED && (name == "system_information" || name == "input"))
    return false;
  // Do not output if the 'none' is contained by the execute_on
  if (_advanced_execute_on.contains(name) && _advanced_execute_on[name].contains("none"))
    return false;
  // Data output flag, true if data exists to be output
  bool execute_data_flag = true;
  // Set flag to false, if the OutputData exists and the output variable list is empty
  std::map<std::string, OutputData>::const_iterator iter = _execute_data.find(name);
  if (iter != _execute_data.end() && iter->second.output.empty())
    execute_data_flag = false;
  // Set flag to false, if the OutputOnWarehouse DOES NOT contain an entry
  if (!_advanced_execute_on.contains(name))
    execute_data_flag = false;
  // Force the output, if there is something to output and the time has not been output
  if (type == EXEC_FORCED && execute_data_flag && _last_execute_time[name] != _time)
    return true;
  // Return true (output should occur) if three criteria are satisfied, else do not output:
  //   (1) The execute_data_flag = true (i.e, there is data to output)
  //   (2) The current output type is contained in the list of output execution types
  //   (3) The current execution time is "final" or "forced" and the data has not already been
  //   output
  if (execute_data_flag && _advanced_execute_on[name].contains(type) &&
      !(type == EXEC_FINAL && _last_execute_time[name] == _time))
    return true;
  else
    return false;
}
Referenced by hasOutput(), Console::initialSetup(), output(), and Console::output().
Friends And Related Function Documentation
Console
friend class Console friend
Definition at line 364 of file AdvancedOutput.h.
OutputWarehouse
friend class OutputWarehouse friend
Definition at line 363 of file AdvancedOutput.h.
TransientMultiApp
friend class TransientMultiApp friend
Definition at line 365 of file AdvancedOutput.h.
Member Data Documentation
_action_factory
ActionFactory& MooseBaseParameterInterface::_action_factory protected inherited
Builds Actions.
Definition at line 164 of file MooseBaseParameterInterface.h.
Referenced by CommonOutputAction::create(), AddVariableAction::createInitialConditionAction(), AddSpecies::createInitialConditions(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
_advanced_execute_on
OutputOnWarehouse Output::_advanced_execute_on protected inherited
Storage for the individual component execute flags.
Definition at line 255 of file Output.h.
Referenced by advancedExecuteOn(), Output::advancedExecuteOn(), AdvancedOutput(), hasOutput(), hasOutputHelper(), init(), Console::initialSetup(), initPostprocessorOrVectorPostprocessorLists(), and wantOutput().
_allow_output
bool Output::_allow_output protected inherited
Flag for disabling output.
Definition at line 246 of file Output.h.
Referenced by Output::allowOutput(), Output::outputStep(), Checkpoint::outputStep(), and OversampleOutput::outputStep().
_app
MooseApp& MooseBase::_app protected inherited
The MOOSE application this is associated with.
Definition at line 60 of file MooseBase.h.
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), MeshGenerator::addChildMeshGenerator(), FEProblemBase::addMaterialHelper(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addOutput(), MeshGenerator::addParentMeshGenerator(), FVFluxKernel::adjustRMGhostLayers(), FEProblemBase::allowOutput(), AStableDirk4::AStableDirk4(), FileMesh::buildMesh(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), MeshGenerator::checkGetMesh(), FEProblemBase::checkICRestartError(), FEProblemBase::checkNonlinearConvergence(), OversampleOutput::cloneMesh(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), Console::Console(), TimeStepper::constrainStep(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::createLocalApp(), FEProblemBase::customSetup(), MeshGenerator::declareMeshProperty(), MeshGenerator::declareNullMeshName(), MooseMesh::determineUseDistributedMesh(), DumpObjectsProblem::dumpObjectHelper(), DumpObjectsProblem::dumpVariableHelper(), EigenExecutionerBase::EigenExecutionerBase(), EigenKernel::EigenKernel(), PIDTransientControl::execute(), Eigenvalue::execute(), InversePowerMethod::execute(), NonlinearEigen::execute(), Steady::execute(), Transient::execute(), PseudoTimestep::execute(), IterationInfo::execute(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FileOutput::FileOutput(), ChangeOverFixedPointPostprocessor::finalize(), RadialAverage::finalize(), FixedPointSolve::FixedPointSolve(), FEProblemBase::forceOutput(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), SideSetsFromNormalsGenerator::generate(), MeshGenerator::generateInternal(), FEProblemBase::getExecutor(), MeshGenerator::getMeshByName(), NumFixedPointIterations::getValue(), NumRelationshipManagers::getValue(), GhostingUserObject::GhostingUserObject(), MooseMesh::init(), InversePowerMethod::init(), NonlinearEigen::init(), Transient::init(), FEProblemBase::init(), TimePeriod::initialSetup(), Console::initialSetup(), initOutputList(), FEProblemBase::initPetscOutput(), EigenProblem::initPetscOutput(), initPostprocessorOrVectorPostprocessorLists(), MeshGenerator::MeshGenerator(), EigenExecutionerBase::normalizeSolution(), NumFailedTimeSteps::NumFailedTimeSteps(), AugmentSparsityOnInterface::operator()(), Checkpoint::output(), Exodus::output(), Nemesis::output(), PerfGraphOutput::output(), Tecplot::output(), MortarNodalGeometryOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Exodus::outputEmptyTimestep(), Console::outputInput(), Exodus::outputInput(), Exodus::outputNodalVariables(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), Console::outputSystemInformation(), JSONOutput::outputSystemInformation(), MultiApp::parentOutputPositionChanged(), PIDTransientControl::PIDTransientControl(), Transient::preExecute(), Eigenvalue::prepareSolverOptions(), FEProblemBase::projectSolution(), MultiApp::setAppOutputFileBase(), FileOutput::setFileBaseInternal(), MeshGenerator::setMeshProperty(), MeshGenerator::setMeshPropertyHelper(), FEProblemBase::setRestartFile(), TransientMultiApp::setupApp(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SolutionInvalidityReporter::SolutionInvalidityReporter(), FEProblemBase::solve(), EigenProblem::solve(), PetscOutput::solveSetup(), TransientMultiApp::solveStep(), FEProblemBase::subdomainSetup(), FEProblemBase::theWarehouse(), TimeExtremeValue::TimeExtremeValue(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), Transient::Transient(), FEProblemBase::updateMortarMesh(), Console::write(), and FEProblemBase::~FEProblemBase().
_broadcast_by_default
const bool VectorPostprocessorInterface::_broadcast_by_default private inherited
Whether or not to force broadcasting by default.
Definition at line 352 of file VectorPostprocessorInterface.h.
Referenced by VectorPostprocessorInterface::getVectorPostprocessorValueByName(), and VectorPostprocessorInterface::getVectorPostprocessorValueOldByName().
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_current_execute_flag
ExecFlagType Output::_current_execute_flag protected inherited
Current execute on flag.
This is different from the flag provided by FEProblemBase::getCurrentExecuteOnFlag() const, as outputs are triggered in PETSc callbacks which cannot update FEProblemBase::_current_execute_on_flag so we shadow it with a new member of the same name.
Definition at line 195 of file Output.h.
Referenced by CSV::getVectorPostprocessorFileName(), output(), Console::output(), ControlOutput::output(), CSV::output(), ProgressOutput::output(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), shouldOutput(), Output::shouldOutput(), Checkpoint::shouldOutput(), and PerfGraphOutput::shouldOutput().
_default_values
std::map<PostprocessorName, std::unique_ptr<PostprocessorValue> > PostprocessorInterface::_default_values mutable private inherited
Holds the default postprocessor values that are requested (key is PostprocessorName)
Definition at line 154 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::getPostprocessorValueInternal().
_dt
Real& Output::_dt protected inherited
Time step delta.
Definition at line 207 of file Output.h.
Referenced by Output::dt(), and PetscOutput::solveSetup().
_dt_old
Real& Output::_dt_old protected inherited
Old time step delta.
Definition at line 210 of file Output.h.
Referenced by Output::dtOld(), and Console::writeTimestepInformation().
_elemental_as_nodal
bool AdvancedOutput::_elemental_as_nodal protected
Flags to control nodal output.
Definition at line 279 of file AdvancedOutput.h.
Referenced by Exodus::Exodus(), and init().
_empty_execute_enum
ExecFlagEnum SetupInterface::_empty_execute_enum private inherited
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
This is private because others should not be messing with it.
Definition at line 71 of file SetupInterface.h.
Referenced by SetupInterface::SetupInterface().
_enabled
const bool& MooseObject::_enabled protected inherited
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
Definition at line 58 of file MooseObject.h.
Referenced by MooseObject::enabled().
_end_step
int Output::_end_step protected inherited
End outputting at this time step.
Definition at line 237 of file Output.h.
Referenced by Output::onInterval().
_end_time
Real Output::_end_time protected inherited
End outputting time.
Definition at line 231 of file Output.h.
_es_ptr
EquationSystems* Output::_es_ptr protected inherited
Reference the the libMesh::EquationSystems object that contains the data.
Definition at line 178 of file Output.h.
Referenced by initAvailableLists(), OversampleOutput::initOversample(), initShowHideLists(), PNGOutput::makeMeshFunc(), Checkpoint::output(), GMVOutput::output(), Nemesis::output(), Tecplot::output(), VTKOutput::output(), XDA::output(), Output::Output(), Exodus::outputElementalVariables(), Exodus::outputEmptyTimestep(), Exodus::outputNodalVariables(), and Exodus::outputSetup().
_execute_data
OutputDataWarehouse AdvancedOutput::_execute_data private
Storage structures for the various output types.
Definition at line 354 of file AdvancedOutput.h.
Referenced by getElementalVariableOutput(), getNodalVariableOutput(), getPostprocessorOutput(), getReporterOutput(), getScalarOutput(), getVectorPostprocessorOutput(), hasOutput(), hasOutputHelper(), init(), initAvailableLists(), initOutputList(), initPostprocessorOrVectorPostprocessorLists(), initShowHideLists(), and wantOutput().
_execute_enum
const ExecFlagEnum& SetupInterface::_execute_enum protected inherited
Execute settings for this object.
Definition at line 75 of file SetupInterface.h.
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), SetupInterface::getExecuteOnEnum(), JSONOutput::outputReporters(), XMLOutput::outputVectorPostprocessors(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
_execute_on
ExecFlagEnum Output::_execute_on protected inherited
The common Execution types; this is used as the default execution type for everything except system information and input.
Definition at line 187 of file Output.h.
Referenced by AdvancedOutput(), Console::Console(), Output::executeOn(), initExecutionTypes(), Console::initialSetup(), Console::output(), Output::Output(), PetscOutput::PetscOutput(), Output::shouldOutput(), and PerfGraphOutput::shouldOutput().
_factory
Factory& MooseBaseParameterInterface::_factory protected inherited
The Factory associated with the MooseApp.
Definition at line 161 of file MooseBaseParameterInterface.h.
Referenced by AddGeneralReactions::act(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), ElementIDOutputAction::act(), AddSpecies::act(), AdaptivityAction::act(), AddControlAction::act(), AddNodalNormalsAction::act(), AddPeriodicBCAction::act(), AutoCheckpointAction::act(), ComposeTimeStepperAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DisplayGhostingAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), PartitionerAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SetupPreconditionerAction::act(), SetupPredictorAction::act(), SetupResidualDebugAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddGeneralReactions::addEEDFReactionKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddDriftDiffusionAction::addPosition(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), MooseBaseParameterInterface::connectControllableParams(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), MaterialOutputAction::getParams(), and ProjectedStatefulMaterialStorageAction::processProperty().
_file_base
std::string FileOutput::_file_base protected inherited
The base filename from the input paramaters.
Definition at line 89 of file FileOutput.h.
Referenced by FileOutput::checkFilename(), Checkpoint::directory(), FileOutput::filename(), Console::filename(), CSV::filename(), DOFMapOutput::filename(), Exodus::filename(), GMVOutput::filename(), Gnuplot::filename(), JSONOutput::filename(), Nemesis::filename(), SolutionHistory::filename(), Tecplot::filename(), VTKOutput::filename(), XDA::filename(), XMLOutput::filename(), CSV::getVectorPostprocessorFileName(), CSV::getVectorPostprocessorFilePrefix(), CSV::initialSetup(), PNGOutput::makePNG(), FileOutput::setFileBaseInternal(), and OversampleOutput::setFileBaseInternal().
_file_num
unsigned int& FileOutput::_file_num protected inherited
A file number counter, initialized to 0 (this must be controlled by the child class, see Exodus)
Definition at line 80 of file FileOutput.h.
Referenced by Exodus::customizeFileOutput(), DOFMapOutput::filename(), Exodus::filename(), GMVOutput::filename(), Tecplot::filename(), VTKOutput::filename(), XDA::filename(), FileOutput::FileOutput(), FileOutput::getFileNumber(), GMVOutput::output(), Gnuplot::output(), Tecplot::output(), VTKOutput::output(), XDA::output(), FileOutput::setFileNumber(), and DOFMapOutput::writeStreamToFile().
_fni_feproblem
FEProblemBase& FunctionInterface::_fni_feproblem private inherited
Reference to FEProblemBase instance.
Definition at line 84 of file FunctionInterface.h.
Referenced by FunctionInterface::getFunction(), FunctionInterface::getFunctionByName(), and FunctionInterface::hasFunctionByName().
_fni_params
const InputParameters& FunctionInterface::_fni_params private inherited
Parameters of the object with this interface.
Definition at line 81 of file FunctionInterface.h.
Referenced by FunctionInterface::getFunction(), and FunctionInterface::hasFunction().
_fni_tid
const THREAD_ID FunctionInterface::_fni_tid private inherited
Thread ID.
Definition at line 87 of file FunctionInterface.h.
Referenced by FunctionInterface::getFunction(), FunctionInterface::getFunctionByName(), and FunctionInterface::hasFunctionByName().
_interval
const unsigned int Output::_interval protected inherited
The output time step interval.
Definition at line 216 of file Output.h.
Referenced by Output::onInterval().
_is_advanced
bool Output::_is_advanced protected inherited
Flag for advanced output testing.
Definition at line 249 of file Output.h.
Referenced by AdvancedOutput(), and Output::isAdvanced().
_last_execute_time
std::map<std::string, Real> AdvancedOutput::_last_execute_time private
Storage for the last output time for the various output types, this is used to avoid duplicate output when using OUTPUT_FINAL flag.
Definition at line 357 of file AdvancedOutput.h.
Referenced by output(), and wantOutput().
_last_output_time
Real& Output::_last_output_time protected inherited
last simulation time an output has occured
Definition at line 258 of file Output.h.
Referenced by Output::onInterval(), Output::outputStep(), Checkpoint::outputStep(), and OversampleOutput::outputStep().
_linear_dt
Real PetscOutput::_linear_dt private inherited
Psuedo linear time step.
Definition at line 111 of file PetscOutput.h.
Referenced by PetscOutput::solveSetup().
_linear_dt_divisor
Real PetscOutput::_linear_dt_divisor private inherited
Pseudo linear timestep divisor.
Definition at line 117 of file PetscOutput.h.
Referenced by PetscOutput::solveSetup().
_linear_end_time
Real PetscOutput::_linear_end_time private inherited
Linear residual output end time.
Definition at line 129 of file PetscOutput.h.
Referenced by PetscOutput::inLinearTimeWindow(), and PetscOutput::PetscOutput().
_linear_iter
PetscInt PetscOutput::_linear_iter protected inherited
Current linear iteration returned from PETSc.
Definition at line 87 of file PetscOutput.h.
Referenced by CSV::getVectorPostprocessorFileName(), Console::output(), JSONOutput::outputReporters(), and XMLOutput::outputVectorPostprocessors().
_linear_start_time
Real PetscOutput::_linear_start_time private inherited
Linear residual output start time.
Definition at line 123 of file PetscOutput.h.
Referenced by PetscOutput::inLinearTimeWindow(), and PetscOutput::PetscOutput().
_linear_time
Real PetscOutput::_linear_time private inherited
Psuedo linear time.
Definition at line 108 of file PetscOutput.h.
Referenced by PetscOutputInterface::petscLinearOutput(), and PetscOutput::time().
_mci_feproblem
FEProblemBase& MeshChangedInterface::_mci_feproblem protected inherited
Reference to FEProblemBase instance.
Definition at line 38 of file MeshChangedInterface.h.
Referenced by MeshChangedInterface::MeshChangedInterface().
_mesh_ptr
MooseMesh* Output::_mesh_ptr protected inherited
A convenience pointer to the current mesh (reference or displaced depending on "use_displaced")
Definition at line 181 of file Output.h.
Referenced by OversampleOutput::cloneMesh(), OversampleOutput::initOversample(), PNGOutput::output(), Tecplot::output(), XDA::output(), Output::Output(), Exodus::outputSetup(), and OversampleOutput::updateOversample().
_metaname
const RestartableDataMapName Restartable::_metaname private inherited
Restartable metadata name.
Definition at line 240 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_minimum_time_interval
const Real Output::_minimum_time_interval protected inherited
Minimum simulation time between outputs.
Definition at line 219 of file Output.h.
Referenced by Output::onInterval().
_moose_base
const MooseBase* const MooseBaseParameterInterface::_moose_base private inherited
The MooseBase object that inherits this class.
Definition at line 168 of file MooseBaseParameterInterface.h.
Referenced by MooseBaseParameterInterface::connectControllableParams(), MooseBaseParameterInterface::objectErrorPrefix(), MooseBaseParameterInterface::paramError(), and MooseBaseParameterInterface::uniqueParameterName().
_name
const std::string& MooseBase::_name protected inherited
The name of this class, reference to value stored in InputParameters.
Definition at line 66 of file MooseBase.h.
Referenced by AddFieldSplitAction::act(), AddBCAction::act(), AddConstraintAction::act(), AddControlAction::act(), AddDamperAction::act(), AddDGKernelAction::act(), AddDiracKernelAction::act(), AddDistributionAction::act(), AddFunctionAction::act(), AddFunctorMaterialAction::act(), AddFVBCAction::act(), AddFVInitialConditionAction::act(), AddFVInterfaceKernelAction::act(), AddFVKernelAction::act(), AddIndicatorAction::act(), AddInitialConditionAction::act(), AddInterfaceKernelAction::act(), AddKernelAction::act(), AddMarkerAction::act(), AddMaterialAction::act(), AddMeshDivisionAction::act(), AddMeshGeneratorAction::act(), AddMultiAppAction::act(), AddNodalKernelAction::act(), AddOutputAction::act(), AddPeriodicBCAction::act(), AddPositionsAction::act(), AddPostprocessorAction::act(), AddReporterAction::act(), AddSamplerAction::act(), AddScalarKernelAction::act(), AddTimesAction::act(), AddTimeStepperAction::act(), AddTransferAction::act(), AddUserObjectAction::act(), AddVectorPostprocessorAction::act(), PartitionerAction::act(), ReadExecutorParamsAction::act(), SetupPreconditionerAction::act(), SetupTimeIntegratorAction::act(), AddDriftDiffusionAction::addADKernels(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromXY(), PiecewiseLinearBase::buildInterpolation(), CombinerGenerator::CombinerGenerator(), Executor::Executor(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), FunctionDT::FunctionDT(), FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), MooseBase::name(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), PiecewiseBase::setData(), and Split::setup().
_nonlinear_dt
Real PetscOutput::_nonlinear_dt private inherited
The pseuedo non-linear time step.
Definition at line 105 of file PetscOutput.h.
Referenced by PetscOutput::solveSetup().
_nonlinear_dt_divisor
Real PetscOutput::_nonlinear_dt_divisor private inherited
Pseudo non-linear timestep divisor.
Definition at line 114 of file PetscOutput.h.
Referenced by PetscOutput::solveSetup().
_nonlinear_end_time
Real PetscOutput::_nonlinear_end_time private inherited
Non-linear residual output end time.
Definition at line 126 of file PetscOutput.h.
Referenced by PetscOutput::inNonlinearTimeWindow(), and PetscOutput::PetscOutput().
_nonlinear_iter
PetscInt PetscOutput::_nonlinear_iter protected inherited
Current non-linear iteration returned from PETSc.
Definition at line 84 of file PetscOutput.h.
Referenced by CSV::getVectorPostprocessorFileName(), Console::output(), JSONOutput::outputReporters(), and XMLOutput::outputVectorPostprocessors().
_nonlinear_start_time
Real PetscOutput::_nonlinear_start_time private inherited
Non-linear residual output start time.
Definition at line 120 of file PetscOutput.h.
Referenced by PetscOutput::inNonlinearTimeWindow(), and PetscOutput::PetscOutput().
_nonlinear_time
Real PetscOutput::_nonlinear_time private inherited
The psuedo non-linear time.
Definition at line 102 of file PetscOutput.h.
Referenced by PetscOutputInterface::petscNonlinearOutput(), PetscOutput::solveSetup(), and PetscOutput::time().
_norm
Real PetscOutput::_norm protected inherited
Current norm returned from PETSc.
Definition at line 81 of file PetscOutput.h.
Referenced by Console::output().
_num
unsigned int Output::_num protected inherited
The number of outputs written.
Definition at line 213 of file Output.h.
_on_linear_residual
bool PetscOutput::_on_linear_residual protected inherited
True if current output calls is on the linear residual (used by time())
Definition at line 90 of file PetscOutput.h.
Referenced by PetscOutput::time().
_on_nonlinear_residual
bool PetscOutput::_on_nonlinear_residual protected inherited
True if current output call is on the non-linear residual (used by time())
Definition at line 93 of file PetscOutput.h.
Referenced by JSONOutput::outputReporters(), XMLOutput::outputVectorPostprocessors(), and PetscOutput::time().
_output_if_base_contains
std::vector<std::string> FileOutput::_output_if_base_contains protected inherited
Storage for 'output_if_base_contains'.
Definition at line 86 of file FileOutput.h.
Referenced by FileOutput::checkFilename().
_padding
unsigned int FileOutput::_padding protected inherited
Number of digits to pad the extensions.
Definition at line 83 of file FileOutput.h.
Referenced by Checkpoint::filename(), Exodus::filename(), GMVOutput::filename(), JSONOutput::filename(), Nemesis::filename(), Tecplot::filename(), VTKOutput::filename(), XDA::filename(), and CSV::getVectorPostprocessorFileName().
_parent
const MooseObject & DataFileInterface< MooseObject >::_parent private inherited
Definition at line 46 of file DataFileInterface.h.
_pars
const InputParameters& MooseBaseParameterInterface::_pars protected inherited
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Definition at line 158 of file MooseBaseParameterInterface.h.
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), AddPeriodicBCAction::act(), AddVariableAction::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), FunctorMaterial::addFunctorPropertyByBlocks(), FVFluxKernel::adjustRMGhostLayers(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), PiecewiseTabularBase::buildFromFile(), PNGOutput::calculateRescalingValues(), BlockWeightedPartitioner::clone(), GridPartitioner::clone(), HierarchicalGridPartitioner::clone(), PetscExternalPartitioner::clone(), RandomPartitioner::clone(), SingleRankPartitioner::clone(), MooseBaseParameterInterface::connectControllableParams(), Console::Console(), AddVariableAction::createInitialConditionAction(), MaterialBase::declareADProperty(), MaterialBase::declareProperty(), FEProblemSolve::FEProblemSolve(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), FileMeshGenerator::generate(), MaterialBase::getGenericZeroMaterialProperty(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getParam(), MooseBaseParameterInterface::getRenamedParam(), AddVariableAction::init(), initExecutionTypes(), Console::initialSetup(), MooseBaseParameterInterface::isParamSetByUser(), MooseBaseParameterInterface::isParamValid(), MultiApp::keepSolutionDuringRestore(), MooseBaseParameterInterface::paramErrorMsg(), GlobalParamsAction::parameters(), MooseBaseParameterInterface::parameters(), MooseMesh::prepare(), Eigenvalue::prepareSolverOptions(), MooseMesh::setCoordSystem(), MooseMesh::setPartitionerHelper(), SetupMeshAction::setupMesh(), Transient::setupTimeIntegrator(), MooseBaseParameterInterface::uniqueName(), and MooseBaseParameterInterface::uniqueParameterName().
_petsc_output
PetscOutput* PetscOutputInterface::_petsc_output protected inherited
Definition at line 23 of file PetscOutput.h.
Referenced by PetscOutputInterface::petscLinearOutput(), and PetscOutputInterface::petscNonlinearOutput().
_pg_moose_app
MooseApp& PerfGraphInterface::_pg_moose_app protected inherited
The MooseApp that owns the PerfGraph.
Definition at line 124 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::perfGraph().
_postprocessors_as_reporters
const bool AdvancedOutput::_postprocessors_as_reporters private
Flags for outputting PP/VPP data as a reporter.
Definition at line 360 of file AdvancedOutput.h.
Referenced by initAvailableLists().
_ppi_feproblem
const FEProblemBase& PostprocessorInterface::_ppi_feproblem private inherited
Reference the the FEProblemBase class.
Definition at line 151 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::hasPostprocessorByName(), PostprocessorInterface::isDefaultPostprocessorValueByName(), and PostprocessorInterface::postprocessorsAdded().
_ppi_moose_object
const MooseObject& PostprocessorInterface::_ppi_moose_object private inherited
The MooseObject that uses this interface.
Definition at line 145 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::checkParam(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), and PostprocessorInterface::hasPostprocessorByName().
_ppi_params
const InputParameters& PostprocessorInterface::_ppi_params private inherited
PostprocessorInterface Parameters.
Definition at line 148 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::checkParam(), PostprocessorInterface::coupledPostprocessors(), and PostprocessorInterface::getPostprocessorNameInternal().
_prefix
const std::string PerfGraphInterface::_prefix protected inherited
A prefix to use for all sections.
Definition at line 127 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::timedSectionName().
_problem_ptr
FEProblemBase* Output::_problem_ptr protected inherited
Pointer the the FEProblemBase object for output object (use this)
Definition at line 169 of file Output.h.
Referenced by PNGOutput::calculateRescalingValues(), Exodus::handleExodusIOMeshRenumbering(), initAvailableLists(), Exodus::initialSetup(), OversampleOutput::initOversample(), initPostprocessorOrVectorPostprocessorLists(), initShowHideLists(), PNGOutput::makeMeshFunc(), Console::meshChanged(), Nemesis::meshChanged(), CSV::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), ReporterDebugOutput::output(), SolutionHistory::output(), Output::Output(), Exodus::outputPostprocessors(), Nemesis::outputPostprocessors(), TableOutput::outputPostprocessors(), JSONOutput::outputReporters(), Exodus::outputScalarVariables(), Nemesis::outputScalarVariables(), TableOutput::outputScalarVariables(), Exodus::outputSetup(), Console::outputSystemInformation(), XMLOutput::outputVectorPostprocessors(), MaterialPropertyDebugOutput::printMaterialMap(), TopResidualDebugOutput::printTopResiduals(), PetscOutput::solveSetup(), Checkpoint::updateCheckpointFiles(), OversampleOutput::updateOversample(), and Console::writeVariableNorms().
_reporter_data
const ReporterData& AdvancedOutput::_reporter_data protected
Storage for Reporter values.
Definition at line 282 of file AdvancedOutput.h.
Referenced by initAvailableLists(), CSV::output(), TableOutput::outputReporter(), Exodus::outputReporters(), TableOutput::outputVectorPostprocessors(), and XMLOutput::outputVectorPostprocessors().
_restartable_app
MooseApp& Restartable::_restartable_app protected inherited
Reference to the application.
Definition at line 227 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp(), and Restartable::registerRestartableNameWithFilterOnApp().
_restartable_name
std::string Restartable::_restartable_name private inherited
The name of the object.
Definition at line 243 of file Restartable.h.
Referenced by Restartable::declareRestartableDataWithObjectNameWithContext(), and Restartable::restartableName().
_restartable_read_only
const bool Restartable::_restartable_read_only protected inherited
Flag for toggling read only status (see ReporterData)
Definition at line 236 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_restartable_system_name
const std::string Restartable::_restartable_system_name protected inherited
The system name this object is in.
Definition at line 230 of file Restartable.h.
Referenced by Restartable::restartableName().
_restartable_tid
const THREAD_ID Restartable::_restartable_tid protected inherited
The thread ID for this object.
Definition at line 233 of file Restartable.h.
Referenced by Restartable::declareRestartableDataHelper().
_ri_fe_problem_base
FEProblemBase& ReporterInterface::_ri_fe_problem_base private inherited
Provides access to FEProblemBase::getReporterData.
Definition at line 122 of file ReporterInterface.h.
Referenced by ReporterInterface::reportersAdded().
_ri_moose_object
const MooseObject& ReporterInterface::_ri_moose_object private inherited
The MooseObject needing this interface.
Definition at line 128 of file ReporterInterface.h.
Referenced by ReporterInterface::getReporterName(), ReporterInterface::getReporterValueByName(), ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), and ReporterInterface::possiblyCheckHasReporter().
_ri_params
const InputParameters& ReporterInterface::_ri_params private inherited
Parameters for the MooseObject inherting from this interface.
Definition at line 119 of file ReporterInterface.h.
Referenced by ReporterInterface::getReporterName(), and ReporterInterface::possiblyCheckHasReporter().
_ri_reporter_data
const ReporterData& ReporterInterface::_ri_reporter_data private inherited
The ReporterData.
Definition at line 125 of file ReporterInterface.h.
Referenced by ReporterInterface::getReporterValueByName(), and ReporterInterface::hasReporterValueByName().
_scalar_as_nodal
bool AdvancedOutput::_scalar_as_nodal protected
Definition at line 279 of file AdvancedOutput.h.
Referenced by init().
_sequence
bool Output::_sequence protected inherited
Flag for forcing call to outputSetup() with every call to output() (restartable)
Definition at line 184 of file Output.h.
_start_step
int Output::_start_step protected inherited
Start outputting at this time step.
Definition at line 234 of file Output.h.
Referenced by Output::onInterval().
_start_time
Real Output::_start_time protected inherited
Start outputting time.
Definition at line 228 of file Output.h.
Referenced by Output::onInterval().
_sync_only
bool Output::_sync_only protected inherited
Flag for only executing at sync times.
Definition at line 243 of file Output.h.
Referenced by Output::onInterval().
_sync_times
std::set<Real> Output::_sync_times protected inherited
Sync times for this outputter.
Definition at line 222 of file Output.h.
Referenced by Output::getSyncTimes(), Output::onInterval(), and Output::Output().
_sync_times_object
const Times* const Output::_sync_times_object protected inherited
Sync times object for this outputter.
Definition at line 225 of file Output.h.
Referenced by Output::onInterval(), and Output::Output().
_t_step
int& Output::_t_step protected inherited
The current time step.
Definition at line 204 of file Output.h.
Referenced by PNGOutput::makePNG(), Output::onInterval(), Console::output(), TableOutput::outputReporter(), TableOutput::outputVectorPostprocessors(), Output::time(), Output::timeOld(), and Output::timeStep().
_t_tol
Real Output::_t_tol protected inherited
Time checking tolerance.
Definition at line 240 of file Output.h.
Referenced by PetscOutput::inLinearTimeWindow(), PetscOutput::inNonlinearTimeWindow(), and Output::onInterval().
_time
Real& Output::_time protected inherited
The current time for output purposes.
Definition at line 198 of file Output.h.
Referenced by PetscOutput::inLinearTimeWindow(), PetscOutput::inNonlinearTimeWindow(), PNGOutput::makePNG(), Output::onInterval(), output(), TableOutput::outputReporter(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), TableOutput::outputVectorPostprocessors(), Output::time(), and wantOutput().
_time_old
Real& Output::_time_old protected inherited
The old time.
Definition at line 201 of file Output.h.
Referenced by PetscOutput::solveSetup(), and Output::timeOld().
_transient
bool Output::_transient protected inherited
Transient flag (true = transient)
Definition at line 172 of file Output.h.
Referenced by Output::dt(), Output::dtOld(), Output::time(), Output::timeOld(), and Console::writeTimestepInformation().
_type
const std::string& MooseBase::_type protected inherited
The type of this class.
Definition at line 63 of file MooseBase.h.
Referenced by FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), FEProblemBase::init(), FEProblemBase::solverTypeString(), and MooseBase::type().
_use_displaced
bool Output::_use_displaced protected inherited
Flag for using displaced mesh.
Definition at line 175 of file Output.h.
Referenced by Output::Output().
_vectorpostprocessors_as_reporters
const bool AdvancedOutput::_vectorpostprocessors_as_reporters private
Definition at line 360 of file AdvancedOutput.h.
Referenced by initAvailableLists().
_vpi_feproblem
const FEProblemBase& VectorPostprocessorInterface::_vpi_feproblem private inherited
Reference the FEProblemBase class.
Definition at line 358 of file VectorPostprocessorInterface.h.
Referenced by VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), VectorPostprocessorInterface::isVectorPostprocessorDistributedByName(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
_vpi_moose_object
const MooseObject& VectorPostprocessorInterface::_vpi_moose_object private inherited
The MooseObject that uses this interface.
Definition at line 355 of file VectorPostprocessorInterface.h.
Referenced by VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper(), VectorPostprocessorInterface::getVectorPostprocessorName(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), and VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName().
_vpi_tid
const THREAD_ID VectorPostprocessorInterface::_vpi_tid private inherited
Thread ID.
Definition at line 361 of file VectorPostprocessorInterface.h.
The documentation for this class was generated from the following files:
moose/framework/include/outputs/AdvancedOutput.h
moose/framework/src/outputs/AdvancedOutput.C