Zapdos: SymmetricRankTwoTensorTempl< T > Class Template Reference
SymmetricRankTwoTensorTempl< T > Class Template Reference
SymmetricRankTwoTensorTempl is designed to handle the Stress or Strain Tensor for an anisotropic material.
#include <SymmetricRankTwoTensor.h>
Public Types
enum InitMethod { initNone , initIdentity }
enum FillMethod { autodetect = 0 , isotropic1 = 1 , diagonal3 = 3 , symmetric6 = 6 }
To fill up the 6 entries in the 2nd-order tensor, fillFromInputVector is called with one of the following fill_methods.
typedef T value_type
For generic programming.
Public Member Functions
SymmetricRankTwoTensorTempl ()
Default constructor; fills to zero.
SymmetricRankTwoTensorTempl (const InitMethod)
Select specific initialization pattern.
SymmetricRankTwoTensorTempl (const std::vector< T > &input)
Constructor that proxies the fillFromInputVector method.
SymmetricRankTwoTensorTempl (const T &S11, const T &S22, const T &S33, const T &S23, const T &S13, const T &S12)
Initialization list replacement constructors, 6 arguments.
operator RankTwoTensorTempl< T > ()
SymmetricRankTwoTensorTempl (const TensorValue< T > &a)
Copy constructor from TensorValue<T>
SymmetricRankTwoTensorTempl (const TypeTensor< T > &a)
Copy constructor from TypeTensor<T>
template<typename T2 >
SymmetricRankTwoTensorTempl (const SymmetricRankTwoTensorTempl< T2 > &a)
Construct from other template.
void fillFromInputVector (const std::vector< T > &input, FillMethod fill_method=autodetect)
fillFromInputVector takes 1, 3, or 6 inputs to fill in the symmmetric Rank-2 tensor.
void fillFromScalarVariable (const VariableValue &scalar_variable)
fillFromScalarVariable takes FIRST/THIRD/SIXTH order scalar variable to fill in the Rank-2 tensor.
T & operator() (unsigned int i)
Gets the raw value for the index specified. Takes index = 0,1,2,3,4,5.
T operator() (unsigned int i) const
Gets the raw value for the index specified.
T operator() (unsigned int i, unsigned int j) const
Gets the value for the index specified.
VectorValue< T > row (const unsigned int n) const
get the specified row of the tensor
VectorValue< T > column (const unsigned int n) const
get the specified column of the tensor
SymmetricRankTwoTensorTempl< T > square () const
Returns the matrix squared.
T tr () const
Returns the trace.
void zero ()
Set all components to zero.
void rotate (const TypeTensor< T > &R)
rotates the tensor data given a rank two tensor rotation tensor _vals[i][j] = R_ij * R_jl * _vals[k][l]
SymmetricRankTwoTensorTempl< T > transpose () const
Returns a matrix that is the transpose of the matrix this was called on.
template<typename T2 >
SymmetricRankTwoTensorTempl< T > & operator= (const SymmetricRankTwoTensorTempl< T2 > &a)
sets _vals to a, and returns _vals
template<typename Scalar >
boostcopy::enable_if_c< ScalarTraits< Scalar >::value, SymmetricRankTwoTensorTempl & >::type operator= (const Scalar &libmesh_dbg_var(p))
Assignment-from-scalar operator.
SymmetricRankTwoTensorTempl< T > & operator+= (const SymmetricRankTwoTensorTempl< T > &a)
adds a to _vals
template<typename T2 >
SymmetricRankTwoTensorTempl< typename CompareTypes< T, T2 >::supertype > operator+ (const SymmetricRankTwoTensorTempl< T2 > &a) const
returns _vals + a
SymmetricRankTwoTensorTempl< T > & operator-= (const SymmetricRankTwoTensorTempl< T > &a)
sets _vals -= a and returns vals
template<typename T2 >
SymmetricRankTwoTensorTempl< typename CompareTypes< T, T2 >::supertype > operator- (const SymmetricRankTwoTensorTempl< T2 > &a) const
returns _vals - a
SymmetricRankTwoTensorTempl< T > operator- () const
returns -_vals
SymmetricRankTwoTensorTempl< T > & operator*= (const T &a)
performs _vals *= a
template<typename T2 >
auto operator* (const T2 &a) const -> typename std::enable_if< ScalarTraits< T2 >::value, SymmetricRankTwoTensorTempl< decltype(T() *T2())> >::type
returns _vals*a
SymmetricRankTwoTensorTempl< T > & operator/= (const T &a)
performs _vals /= a
template<typename T2 >
auto operator/ (const T2 &a) const -> typename std::enable_if< ScalarTraits< T2 >::value, SymmetricRankTwoTensorTempl< decltype(T()/T2())> >::type
returns _vals/a
template<typename T2 >
TypeVector< typename CompareTypes< T, T2 >::supertype > operator* (const TypeVector< T2 > &a) const
Defines multiplication with a vector to get a vector.
template<typename T2 >
bool operator== (const SymmetricRankTwoTensorTempl< T2 > &a) const
Defines logical equality with another SymmetricRankTwoTensorTempl<T2>
bool isSymmetric () const
Test for symmetry. Surprisingly this is always true.
template<typename T2 >
bool operator!= (const SymmetricRankTwoTensorTempl< T2 > &a) const
Defines logical inequality with another SymmetricRankTwoTensorTempl<T2>
SymmetricRankTwoTensorTempl< T > & operator= (const ColumnMajorMatrixTempl< T > &a)
Sets _vals to the values in a ColumnMajorMatrix (must be 3x3)
T doubleContraction (const SymmetricRankTwoTensorTempl< T > &a) const
returns _vals_ij * a_ij (sum on i, j)
SymmetricRankFourTensorTempl< T > outerProduct (const SymmetricRankTwoTensorTempl< T > &a) const
returns C_ijkl = a_ij * b_kl
SymmetricRankFourTensorTempl< T > positiveProjectionEigenDecomposition (std::vector< T > &, RankTwoTensorTempl< T > &) const
return positive projection tensor of eigen-decomposition
SymmetricRankTwoTensorTempl< T > deviatoric () const
returns A_ij - de_ij*tr(A)/3, where A are the _vals
T trace () const
returns the trace of the tensor, ie _vals[i][i] (sum i = 0, 1, 2)
SymmetricRankTwoTensorTempl< T > inverse () const
retuns the inverse of the tensor
SymmetricRankTwoTensorTempl< T > dtrace () const
Denote the _vals[i][j] by A_ij, then this returns d(trace)/dA_ij.
T generalSecondInvariant () const
Calculates the second invariant (I2) of a tensor.
T secondInvariant () const
Denote the _vals[i][j] by A_ij, then S_ij = A_ij - de_ij*tr(A)/3 Then this returns (S_ij + S_ji)*(S_ij + S_ji)/8 Note the explicit symmeterisation.
SymmetricRankTwoTensorTempl< T > dsecondInvariant () const
Denote the _vals[i][j] by A_ij, then this returns d(secondInvariant)/dA_ij.
SymmetricRankFourTensorTempl< T > d2secondInvariant () const
Denote the _vals[i][j] by A_ij, then this returns d^2(secondInvariant)/dA_ij/dA_kl.
T sin3Lode (const T &r0, const T &r0_value) const
Sin(3*Lode_angle) If secondInvariant() <= r0 then return r0_value This is to gaurd against precision-loss errors.
SymmetricRankTwoTensorTempl< T > dsin3Lode (const T &r0) const
d(sin3Lode)/dA_ij If secondInvariant() <= r0 then return zero This is to gaurd against precision-loss errors.
T thirdInvariant () const
Denote the _vals[i][j] by A_ij, then S_ij = A_ij - de_ij*tr(A)/3 Then this returns det(S + S.transpose())/2 Note the explicit symmeterisation.
SymmetricRankTwoTensorTempl< T > dthirdInvariant () const
Denote the _vals[i][j] by A_ij, then this returns d(thirdInvariant()/dA_ij.
SymmetricRankFourTensorTempl< T > d2thirdInvariant () const
Denote the _vals[i][j] by A_ij, then this returns d^2(thirdInvariant)/dA_ij/dA_kl.
T det () const
SymmetricRankTwoTensorTempl< T > ddet () const
Denote the _vals[i][j] by A_ij, then this returns d(det)/dA_ij.
void print (std::ostream &stm=Moose::out) const
Print the rank two tensor.
void printReal (std::ostream &stm=Moose::out) const
Print the Real part of the DualReal rank two tensor.
void printDualReal (unsigned int nDual, std::ostream &stm=Moose::out) const
Print the Real part of the DualReal rank two tensor along with its first nDual dual numbers.
void addIa (const T &a)
Add identity times a to _vals.
T L2norm () const
Sqrt(_vals[i][j]*_vals[i][j])
void surfaceFillFromInputVector (const std::vector< T > &input)
sets _vals[0][0], _vals[0][1], _vals[1][0], _vals[1][1] to input, and the remainder to zero
void symmetricEigenvalues (std::vector< T > &eigvals) const
computes eigenvalues, assuming tens is symmetric, and places them in ascending order in eigvals
void symmetricEigenvaluesEigenvectors (std::vector< T > &eigvals, RankTwoTensorTempl< T > &eigvecs) const
computes eigenvalues and eigenvectors, assuming tens is symmetric, and places them in ascending order in eigvals.
SymmetricRankTwoTensorTempl< T > initialContraction (const SymmetricRankFourTensorTempl< T > &b) const
returns this_ij * b_ijkl
void setToIdentity ()
set the tensor to the identity matrix
Static Public Member Functions
static constexpr Real mandelFactor (unsigned int i)
returns the 1 or sqrt(2) prefactor in the Mandel notation for the index i ranging from 0-5.
static SymmetricRankTwoTensorTempl identity ()
static SymmetricRankTwoTensorTempl initializeSymmetric (const TypeVector< T > &v0, const TypeVector< T > &v1, const TypeVector< T > &v2)
named constructor for initializing symmetrically
static MooseEnum fillMethodEnum ()
Static method for use in validParams for getting the "fill_method".
static SymmetricRankTwoTensorTempl< T > timesTranspose (const RankTwoTensorTempl< T > &)
return the matrix multiplied with its transpose A*A^T (guaranteed symmetric)
static SymmetricRankTwoTensorTempl< T > timesTranspose (const SymmetricRankTwoTensorTempl< T > &)
static SymmetricRankTwoTensorTempl< T > transposeTimes (const RankTwoTensorTempl< T > &)
return the matrix multiplied with its transpose A^T*A (guaranteed symmetric)
static SymmetricRankTwoTensorTempl< T > transposeTimes (const SymmetricRankTwoTensorTempl< T > &)
static SymmetricRankTwoTensorTempl< T > plusTranspose (const RankTwoTensorTempl< T > &)
return the matrix plus its transpose A-A^T (guaranteed symmetric)
static SymmetricRankTwoTensorTempl< T > plusTranspose (const SymmetricRankTwoTensorTempl< T > &)
static void initRandom (unsigned int)
This function initializes random seed based on a user-defined number.
static SymmetricRankTwoTensorTempl< T > genRandomSymmTensor (T, T)
This function generates a random symmetric rank two tensor.
static SymmetricRankTwoTensorTempl< T > selfOuterProduct (const TypeVector< T > &)
SymmetricRankTwoTensorTempl<T> from outer product of a vector with itself.
Static Public Attributes
static constexpr unsigned int full_index [6][2] = {{0, 0}, {1, 1}, {2, 2}, {1, 2}, {0, 2}, {0, 1}}
static constexpr unsigned int reverse_index [3][3] = {{0, 5, 4}, {5, 1, 3}, {4, 3, 2}}
static constexpr unsigned int Ndim = Moose::dim
tensor dimension and Mandel vector length
static constexpr unsigned int N = Ndim + (Ndim * (Ndim - 1)) / 2
Protected Member Functions
void syev (const char *calculation_type, std::vector< T > &eigvals, std::vector< T > &a) const
Uses the petscblaslapack.h LAPACKsyev_ routine to find, for symmetric _vals: (1) the eigenvalues (if calculation_type == "N") (2) the eigenvalues and eigenvectors (if calculation_type == "V")
Private Member Functions
SymmetricRankTwoTensorTempl (const T &S11, const T &S21, const T &S31, const T &S12, const T &S22, const T &S32, const T &S13, const T &S23, const T &S33)
Initialization list replacement constructors, 9 arguments (for internal use only)
Static Private Member Functions
static SymmetricRankTwoTensorTempl fromRawComponents (const T &S11, const T &S22, const T &S33, const T &S23, const T &S13, const T &S12)
Private Attributes
std::array< T, N > _vals
Static Private Attributes
static constexpr std::array< Real, N > identityCoords = {{1, 1, 1, 0, 0, 0}}
Friends
template<class T2 >
class SymmetricRankFourTensorTempl
template<class T2 >
void dataStore (std::ostream &, SymmetricRankTwoTensorTempl< T2 > &, void *)
template<class T2 >
void dataLoad (std::istream &, SymmetricRankTwoTensorTempl< T2 > &, void *)
Detailed Description
template<typename T>
class SymmetricRankTwoTensorTempl< T >
SymmetricRankTwoTensorTempl is designed to handle the Stress or Strain Tensor for an anisotropic material.
It is designed to reduce the redundancies of the Complete tensor classes for regular mechanics problems and to enable use of the Mandel notation.
Definition at line 73 of file SymmetricRankTwoTensor.h.
Member Typedef Documentation
value_type
template<typename T > typedef T SymmetricRankTwoTensorTempl< T >::value_type
For generic programming.
Definition at line 77 of file SymmetricRankTwoTensor.h.
Member Enumeration Documentation
FillMethod
template<typename T > enum SymmetricRankTwoTensorTempl::FillMethod
To fill up the 6 entries in the 2nd-order tensor, fillFromInputVector is called with one of the following fill_methods.
See the fill*FromInputVector functions for more details
Enumerator
autodetect
isotropic1
diagonal3
symmetric6
Definition at line 111 of file SymmetricRankTwoTensor.h.
  {
    autodetect = 0,
    isotropic1 = 1,
    diagonal3 = 3,
    symmetric6 = 6
  };
InitMethod
template<typename T > enum SymmetricRankTwoTensorTempl::InitMethod
Enumerator
initNone
initIdentity
Definition at line 94 of file SymmetricRankTwoTensor.h.
  {
    initNone,
    initIdentity
  };
Constructor & Destructor Documentation
SymmetricRankTwoTensorTempl() [1/8]
template<typename T > SymmetricRankTwoTensorTempl< T >::SymmetricRankTwoTensorTempl
Default constructor; fills to zero.
Definition at line 54 of file SymmetricRankTwoTensorImplementation.h.
{
  std::fill(_vals.begin(), _vals.end(), 0.0);
}
Referenced by SymmetricRankTwoTensorTempl< T >::identity().
SymmetricRankTwoTensorTempl() [2/8]
template<typename T > SymmetricRankTwoTensorTempl< T >::SymmetricRankTwoTensorTempl (const InitMethod init)
Select specific initialization pattern.
Definition at line 60 of file SymmetricRankTwoTensorImplementation.h.
{
  switch (init)
  {
    case initNone:
      break;
    case initIdentity:
      setToIdentity();
      break;
    default:
      mooseError("Unknown SymmetricRankTwoTensorTempl initialization pattern.");
  }
}
SymmetricRankTwoTensorTempl() [3/8]
template<typename T > SymmetricRankTwoTensorTempl< T >::SymmetricRankTwoTensorTempl (const std::vector< T > & input) inline
Constructor that proxies the fillFromInputVector method.
Definition at line 120 of file SymmetricRankTwoTensor.h.
{ this->fillFromInputVector(input); };
SymmetricRankTwoTensorTempl() [4/8]
template<typename T > SymmetricRankTwoTensorTempl< T >::SymmetricRankTwoTensorTempl (const T & S11, const T & S22, const T & S33, const T & S23, const T & S13, const T & S12)
Initialization list replacement constructors, 6 arguments.
Definition at line 77 of file SymmetricRankTwoTensorImplementation.h.
{
  _vals[0] = S11;
  _vals[1] = S22;
  _vals[2] = S33;
  _vals[3] = mandelFactor(3) * S23;
  _vals[4] = mandelFactor(4) * S13;
  _vals[5] = mandelFactor(5) * S12;
}
SymmetricRankTwoTensorTempl() [5/8]
template<typename T > SymmetricRankTwoTensorTempl< T >::SymmetricRankTwoTensorTempl (const T & S11, const T & S21, const T & S31, const T & S12, const T & S22, const T & S32, const T & S13, const T & S23, const T & S33) private
Initialization list replacement constructors, 9 arguments (for internal use only)
Definition at line 103 of file SymmetricRankTwoTensorImplementation.h.
{
  _vals[0] = S11;
  _vals[1] = S22;
  _vals[2] = S33;
  _vals[3] = (S23 + S32) / mandelFactor(3);
  _vals[4] = (S13 + S31) / mandelFactor(4);
  _vals[5] = (S12 + S21) / mandelFactor(5);
}
SymmetricRankTwoTensorTempl() [6/8]
template<typename T > SymmetricRankTwoTensorTempl< T >::SymmetricRankTwoTensorTempl (const TensorValue< T > & a) explicit
Copy constructor from TensorValue<T>
Definition at line 137 of file SymmetricRankTwoTensorImplementation.h.
{
  _vals[0] = a(0, 0);
  _vals[1] = a(1, 1);
  _vals[2] = a(2, 2);
  _vals[3] = (a(1, 2) + a(2, 1)) / mandelFactor(3);
  _vals[4] = (a(0, 2) + a(2, 0)) / mandelFactor(4);
  _vals[5] = (a(0, 1) + a(1, 0)) / mandelFactor(5);
}
SymmetricRankTwoTensorTempl() [7/8]
template<typename T > SymmetricRankTwoTensorTempl< T >::SymmetricRankTwoTensorTempl (const TypeTensor< T > & a) explicit
Copy constructor from TypeTensor<T>
Definition at line 148 of file SymmetricRankTwoTensorImplementation.h.
{
  _vals[0] = a(0, 0);
  _vals[1] = a(1, 1);
  _vals[2] = a(2, 2);
  _vals[3] = (a(1, 2) + a(2, 1)) / mandelFactor(3);
  _vals[4] = (a(0, 2) + a(2, 0)) / mandelFactor(4);
  _vals[5] = (a(0, 1) + a(1, 0)) / mandelFactor(5);
}
SymmetricRankTwoTensorTempl() [8/8]
template<typename T > template<typename T2 > SymmetricRankTwoTensorTempl< T >::SymmetricRankTwoTensorTempl (const SymmetricRankTwoTensorTempl< T2 > & a) inline
Construct from other template.
Definition at line 154 of file SymmetricRankTwoTensor.h.
  {
    for (const auto i : make_range(N))
      _vals[i] = a(i);
  }
Member Function Documentation
addIa()
template<typename T > void SymmetricRankTwoTensorTempl< T >::addIa (const T & a)
Add identity times a to _vals.
Definition at line 652 of file SymmetricRankTwoTensorImplementation.h.
{
  for (unsigned int i = 0; i < 3; ++i)
    _vals[i] += a;
}
Referenced by SymmetricRankTwoTensorTempl< T >::deviatoric().
column()
template<typename T > VectorValue< T > SymmetricRankTwoTensorTempl< T >::column (const unsigned int n) const inline
get the specified column of the tensor
Definition at line 204 of file SymmetricRankTwoTensor.h.
{ return row(n); }
d2secondInvariant()
template<typename T > SymmetricRankFourTensorTempl< T > SymmetricRankTwoTensorTempl< T >::d2secondInvariant
Denote the _vals[i][j] by A_ij, then this returns d^2(secondInvariant)/dA_ij/dA_kl.
Definition at line 496 of file SymmetricRankTwoTensorImplementation.h.
{
  SymmetricRankFourTensorTempl<T> result;
  for (auto i : make_range(N))
    for (auto j : make_range(N))
      result(i, j) = 0.5 * (i == j) + 0.5 * (i == j) - (1.0 / 3.0) * (i < 3) * (j < 3);
  return result;
}
d2thirdInvariant()
template<typename T > SymmetricRankFourTensorTempl< T > SymmetricRankTwoTensorTempl< T >::d2thirdInvariant
Denote the _vals[i][j] by A_ij, then this returns d^2(thirdInvariant)/dA_ij/dA_kl.
Definition at line 566 of file SymmetricRankTwoTensorImplementation.h.
{
  const auto s = SymmetricRankTwoTensorTempl<T>::plusTranspose(deviatoric()) * 0.5;
  SymmetricRankFourTensorTempl<T> d2;
  for (auto i : make_range(N))
    for (auto j : make_range(N))
      d2(i, j) = Real(i < 3) * s(j) / 3.0 / (j < 3 ? 1 : MathUtils::sqrt2) +
                 Real(j < 3) * s(i) / 3.0 / (i < 3 ? 1 : MathUtils::sqrt2);
  d2(0, 1) += s(2);
  d2(0, 2) += s(1);
  d2(0, 3) -= s(3) / MathUtils::sqrt2;
  d2(1, 0) += s(2);
  d2(1, 2) += s(0);
  d2(1, 4) -= s(4) / MathUtils::sqrt2;
  d2(2, 0) += s(1);
  d2(2, 1) += s(0);
  d2(2, 5) -= s(5) / MathUtils::sqrt2;
  d2(3, 0) -= s(3) / MathUtils::sqrt2;
  d2(3, 3) -= s(0) / 2.0;
  d2(3, 4) += s(5) / 2.0 / MathUtils::sqrt2;
  d2(3, 5) += s(4) / 2.0 / MathUtils::sqrt2;
  d2(4, 1) -= s(4) / MathUtils::sqrt2;
  d2(4, 3) += s(5) / 2.0 / MathUtils::sqrt2;
  d2(4, 4) -= s(1) / 2.0;
  d2(4, 5) += s(3) / 2.0 / MathUtils::sqrt2;
  d2(5, 2) -= s(5) / MathUtils::sqrt2;
  d2(5, 3) += s(4) / 2.0 / MathUtils::sqrt2;
  d2(5, 4) += s(3) / 2.0 / MathUtils::sqrt2;
  d2(5, 5) -= s(2) / 2.0;
  for (auto i : make_range(N))
    for (auto j : make_range(N))
      d2(i, j) *= SymmetricRankFourTensorTempl<T>::mandelFactor(i, j);
  return d2;
}
ddet()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::ddet
Denote the _vals[i][j] by A_ij, then this returns d(det)/dA_ij.
Definition at line 623 of file SymmetricRankTwoTensorImplementation.h.
{
  return SymmetricRankTwoTensorTempl<T>(
      _vals[2] * _vals[1] - _vals[3] * _vals[3] / 2.0,
      _vals[0] * _vals[2] - _vals[4] * _vals[4] / 2.0,
      _vals[0] * _vals[1] - _vals[5] * _vals[5] / 2.0,
      _vals[4] * _vals[5] / 2.0 - _vals[0] * _vals[3] / MathUtils::sqrt2,
      _vals[5] * _vals[3] / 2.0 - _vals[4] * _vals[1] / MathUtils::sqrt2,
      _vals[4] * _vals[3] / 2.0 - _vals[5] * _vals[2] / MathUtils::sqrt2);
}
det()
template<typename T > T SymmetricRankTwoTensorTempl< T >::det
Definition at line 612 of file SymmetricRankTwoTensorImplementation.h.
{
  return _vals[0] * (_vals[2] * _vals[1] - _vals[3] * _vals[3] / 2.0) -
         _vals[5] / MathUtils::sqrt2 *
             (_vals[2] * _vals[5] / MathUtils::sqrt2 - _vals[3] * _vals[4] / 2.0) +
         _vals[4] / MathUtils::sqrt2 *
             (_vals[3] * _vals[5] / 2.0 - _vals[1] * _vals[4] / MathUtils::sqrt2);
}
deviatoric()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::deviatoric
returns A_ij - de_ij*tr(A)/3, where A are the _vals
Definition at line 458 of file SymmetricRankTwoTensorImplementation.h.
{
  SymmetricRankTwoTensorTempl<T> deviatoric(*this);
  deviatoric.addIa(-1.0 / 3.0 * this->tr());
  return deviatoric;
}
doubleContraction()
template<typename T > T SymmetricRankTwoTensorTempl< T >::doubleContraction (const SymmetricRankTwoTensorTempl< T > & a) const
returns _vals_ij * a_ij (sum on i, j)
Definition at line 433 of file SymmetricRankTwoTensorImplementation.h.
{
  T sum = 0;
  for (unsigned int i = 0; i < N; ++i)
    sum += _vals[i] * b._vals[i];
  return sum;
}
dsecondInvariant()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::dsecondInvariant
Denote the _vals[i][j] by A_ij, then this returns d(secondInvariant)/dA_ij.
Definition at line 489 of file SymmetricRankTwoTensorImplementation.h.
{
  return SymmetricRankTwoTensorTempl<T>::plusTranspose(deviatoric()) * 0.5;
}
dsin3Lode()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::dsin3Lode (const T & r0) const
d(sin3Lode)/dA_ij If secondInvariant() <= r0 then return zero This is to gaurd against precision-loss errors.
Note that sin(3*Lode_angle) is not defined for secondInvariant() = 0
Definition at line 658 of file SymmetricRankTwoTensor.h.
{
  if (MooseUtils::IsLikeReal<T>::value)
  {
    T bar = secondInvariant();
    if (bar <= r0)
      return SymmetricRankTwoTensorTempl<T>();
    else
      return -1.5 * std::sqrt(3.0) *
             (dthirdInvariant() / std::pow(bar, 1.5) -
              1.5 * dsecondInvariant() * thirdInvariant() / std::pow(bar, 2.5));
  }
  else
    mooseError("dsin3Lode is only available for ordered tensor component types");
}
dthirdInvariant()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::dthirdInvariant
Denote the _vals[i][j] by A_ij, then this returns d(thirdInvariant()/dA_ij.
Definition at line 552 of file SymmetricRankTwoTensorImplementation.h.
{
  const auto s = SymmetricRankTwoTensorTempl<T>::plusTranspose(deviatoric()) * 0.5;
  const T s3 = secondInvariant() / 3.0;
  return SymmetricRankTwoTensorTempl<T>(s(1) * s(2) - s(3) * s(3) / 2.0 + s3,
                                        s(0) * s(2) - s(4) * s(4) / 2.0 + s3,
                                        s(0) * s(1) - s(5) * s(5) / 2.0 + s3,
                                        s(5) * s(4) / 2.0 - s(0) * s(3) / MathUtils::sqrt2,
                                        s(5) * s(3) / 2.0 - s(1) * s(4) / MathUtils::sqrt2,
                                        s(4) * s(3) / 2.0 - s(5) * s(2) / MathUtils::sqrt2);
}
dtrace()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::dtrace
Denote the _vals[i][j] by A_ij, then this returns d(trace)/dA_ij.
Definition at line 533 of file SymmetricRankTwoTensorImplementation.h.
{
  return SymmetricRankTwoTensorTempl<T>(1, 1, 1, 0, 0, 0);
}
fillFromInputVector()
template<typename T > void SymmetricRankTwoTensorTempl< T >::fillFromInputVector (const std::vector< T > & input, FillMethod fill_method = autodetect)
fillFromInputVector takes 1, 3, or 6 inputs to fill in the symmmetric Rank-2 tensor.
Definition at line 171 of file SymmetricRankTwoTensorImplementation.h.
{
  if (fill_method != autodetect && fill_method != input.size())
    mooseError("Expected an input vector size of ",
               fill_method,
               " to fill the SymmetricRankTwoTensorTempl");
  switch (input.size())
  {
    case 1:
      _vals[0] = input[0];
      _vals[1] = input[0];
      _vals[2] = input[0];
      _vals[3] = 0.0;
      _vals[4] = 0.0;
      _vals[5] = 0.0;
      break;
    case 3:
      _vals[0] = input[0];
      _vals[1] = input[1];
      _vals[2] = input[2];
      _vals[3] = 0.0;
      _vals[4] = 0.0;
      _vals[5] = 0.0;
      break;
    case 6:
      _vals[0] = input[0];
      _vals[1] = input[1];
      _vals[2] = input[2];
      _vals[3] = mandelFactor(3) * input[3];
      _vals[4] = mandelFactor(4) * input[4];
      _vals[5] = mandelFactor(5) * input[5];
      break;
    default:
      mooseError("Please check the number of entries in the input vector for building "
                 "a SymmetricRankTwoTensorTempl. It must be 1, 3, 6");
  }
}
Referenced by SymmetricRankTwoTensorTempl< T >::SymmetricRankTwoTensorTempl().
fillFromScalarVariable()
template<typename T > void SymmetricRankTwoTensorTempl< T >::fillFromScalarVariable (const VariableValue & scalar_variable)
fillFromScalarVariable takes FIRST/THIRD/SIXTH order scalar variable to fill in the Rank-2 tensor.
Definition at line 216 of file SymmetricRankTwoTensorImplementation.h.
{
  switch (scalar_variable.size())
  {
    case 1:
      _vals[0] = scalar_variable[0];
      _vals[1] = 0.0;
      _vals[2] = 0.0;
      _vals[3] = 0.0;
      _vals[4] = 0.0;
      _vals[5] = 0.0;
      break;
    case 3:
      _vals[0] = scalar_variable[0];
      _vals[1] = scalar_variable[1];
      _vals[2] = 0.0;
      _vals[3] = 0.0;
      _vals[4] = 0.0;
      _vals[5] = mandelFactor(5) * scalar_variable[2];
      break;
    case 6:
      _vals[0] = scalar_variable[0];
      _vals[1] = scalar_variable[1];
      _vals[2] = scalar_variable[2];
      _vals[3] = mandelFactor(3) * scalar_variable[3];
      _vals[4] = mandelFactor(4) * scalar_variable[4];
      _vals[5] = mandelFactor(5) * scalar_variable[5];
      break;
    default:
      mooseError("Only FIRST, THIRD, or SIXTH order scalar variable can be used to build "
                 "a SymmetricRankTwoTensorTempl.");
  }
}
fillMethodEnum()
template<typename T > MooseEnum SymmetricRankTwoTensorTempl< T >::fillMethodEnum static
Static method for use in validParams for getting the "fill_method".
Definition at line 48 of file SymmetricRankTwoTensorImplementation.h.
{
  return MooseEnum("autodetect=0 isotropic1=1 diagonal3=3 symmetric6=6", "autodetect");
}
fromRawComponents()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::fromRawComponents (const T & S11, const T & S22, const T & S33, const T & S23, const T & S13, const T & S12) static private
Definition at line 123 of file SymmetricRankTwoTensorImplementation.h.
{
  SymmetricRankTwoTensorTempl<T> ret(SymmetricRankTwoTensorTempl<T>::initNone);
  ret._vals[0] = S11;
  ret._vals[1] = S22;
  ret._vals[2] = S33;
  ret._vals[3] = S23;
  ret._vals[4] = S13;
  ret._vals[5] = S12;
  return ret;
}
Referenced by SymmetricRankTwoTensorTempl< T >::timesTranspose().
generalSecondInvariant()
template<typename T > T SymmetricRankTwoTensorTempl< T >::generalSecondInvariant
Calculates the second invariant (I2) of a tensor.
Definition at line 467 of file SymmetricRankTwoTensorImplementation.h.
{
  return _vals[0] * _vals[1] + _vals[0] * _vals[2] + _vals[1] * _vals[2] -
         (_vals[3] * _vals[3] + _vals[4] * _vals[4] + _vals[5] * _vals[5]) / 2.0;
}
genRandomSymmTensor()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::genRandomSymmTensor (T scale, T offset) static
This function generates a random symmetric rank two tensor.
The first real scales the random number. The second real offsets the uniform random number
Definition at line 756 of file SymmetricRankTwoTensorImplementation.h.
{
  auto r = [&]() { return (MooseRandom::rand() + offset) * scale; };
  return SymmetricRankTwoTensorTempl<T>(r(), r(), r(), r(), r(), r());
}
identity()
template<typename T > static SymmetricRankTwoTensorTempl SymmetricRankTwoTensorTempl< T >::identity () inline static
Definition at line 161 of file SymmetricRankTwoTensor.h.
  {
    return SymmetricRankTwoTensorTempl(initIdentity);
  }
initialContraction()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::initialContraction (const SymmetricRankFourTensorTempl< T > & b) const
returns this_ij * b_ijkl
Definition at line 772 of file SymmetricRankTwoTensorImplementation.h.
{
  SymmetricRankTwoTensorTempl<T> result;
  for (auto i : make_range(N))
    for (auto j : make_range(N))
      result(j) += (*this)(i)*b(i, j);
  return result;
}
initializeSymmetric()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::initializeSymmetric (const TypeVector< T > & v0, const TypeVector< T > & v1, const TypeVector< T > & v2) static
named constructor for initializing symmetrically
Definition at line 161 of file SymmetricRankTwoTensorImplementation.h.
{
  return SymmetricRankTwoTensorTempl<T>(
      v0(0), v1(0), v2(0), v0(1), v1(1), v2(1), v0(2), v1(2), v2(2));
}
initRandom()
template<typename T > void SymmetricRankTwoTensorTempl< T >::initRandom (unsigned int rand_seed) static
This function initializes random seed based on a user-defined number.
Definition at line 749 of file SymmetricRankTwoTensorImplementation.h.
{
  MooseRandom::seed(rand_seed);
}
inverse()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::inverse
retuns the inverse of the tensor
Definition at line 516 of file SymmetricRankTwoTensorImplementation.h.
{
  const auto d = det();
  if (d == 0.0)
    mooseException("Matrix not invertible");
  const SymmetricRankTwoTensorTempl<T> inv(
      _vals[2] * _vals[1] - _vals[3] * _vals[3] / 2.0,
      _vals[2] * _vals[0] - _vals[4] * _vals[4] / 2.0,
      _vals[0] * _vals[1] - _vals[5] * _vals[5] / 2.0,
      _vals[5] * _vals[4] / 2.0 - _vals[0] * _vals[3] / MathUtils::sqrt2,
      _vals[5] * _vals[3] / 2.0 - _vals[4] * _vals[1] / MathUtils::sqrt2,
      _vals[4] * _vals[3] / 2.0 - _vals[2] * _vals[5] / MathUtils::sqrt2);
  return inv * 1.0 / d;
}
isSymmetric()
template<typename T > bool SymmetricRankTwoTensorTempl< T >::isSymmetric () const inline
Test for symmetry. Surprisingly this is always true.
Definition at line 305 of file SymmetricRankTwoTensor.h.
{ return true; }
L2norm()
template<typename T > T SymmetricRankTwoTensorTempl< T >::L2norm
Sqrt(_vals[i][j]*_vals[i][j])
Definition at line 660 of file SymmetricRankTwoTensorImplementation.h.
{
  T norm = _vals[0] * _vals[0];
  for (unsigned int i = 1; i < N; ++i)
    norm += _vals[i] * _vals[i];
  return norm == 0.0 ? 0.0 : std::sqrt(norm);
}
mandelFactor()
template<typename T > static constexpr Real SymmetricRankTwoTensorTempl< T >::mandelFactor (unsigned int i) inline static constexpr
returns the 1 or sqrt(2) prefactor in the Mandel notation for the index i ranging from 0-5.
Definition at line 91 of file SymmetricRankTwoTensor.h.
{ return i < Ndim ? 1.0 : MathUtils::sqrt2; }
Referenced by SymmetricRankFourTensorTempl< T >::mandelFactor(), and SymmetricRankTwoTensorTempl< T >::operator()().
operator RankTwoTensorTempl< T >()
template<typename T > SymmetricRankTwoTensorTempl< T >::operator RankTwoTensorTempl< T > explicit
Definition at line 89 of file SymmetricRankTwoTensorImplementation.h.
{
  return RankTwoTensorTempl<T>(_vals[0],
                               _vals[5] / mandelFactor(5),
                               _vals[4] / mandelFactor(4),
                               _vals[5] / mandelFactor(5),
                               _vals[1],
                               _vals[3] / mandelFactor(3),
                               _vals[4] / mandelFactor(4),
                               _vals[3] / mandelFactor(3),
                               _vals[2]);
}
operator!=()
template<typename T > template<typename T2 > bool SymmetricRankTwoTensorTempl< T >::operator!= (const SymmetricRankTwoTensorTempl< T2 > & a) const
Defines logical inequality with another SymmetricRankTwoTensorTempl<T2>
Definition at line 563 of file SymmetricRankTwoTensor.h.
{
  for (std::size_t i = 0; i < N; ++i)
    if (_vals[i] != a._vals[i])
      return true;
  return false;
}
operator()() [1/3]
template<typename T > T & SymmetricRankTwoTensorTempl< T >::operator() (unsigned int i) inline
Gets the raw value for the index specified. Takes index = 0,1,2,3,4,5.
Definition at line 183 of file SymmetricRankTwoTensor.h.
{ return _vals[i]; }
operator()() [2/3]
template<typename T > T SymmetricRankTwoTensorTempl< T >::operator() (unsigned int i) const inline
Gets the raw value for the index specified.
Takes index = 0,1,2 used for const
Definition at line 189 of file SymmetricRankTwoTensor.h.
{ return _vals[i]; }
operator()() [3/3]
template<typename T > T SymmetricRankTwoTensorTempl< T >::operator() (unsigned int i, unsigned int j) const inline
Gets the value for the index specified.
Takes index = 0,1,2
Definition at line 194 of file SymmetricRankTwoTensor.h.
  {
    const auto a = reverse_index[i][j];
    return _vals[a] / mandelFactor(a);
  }
operator*() [1/2]
template<typename T > template<typename T2 > auto SymmetricRankTwoTensorTempl< T >::operator* (const T2 & a) const -> typename std::enable_if<ScalarTraits<T2>::value, SymmetricRankTwoTensorTempl<decltype(T() * T2())>>::type
returns _vals*a
Definition at line 514 of file SymmetricRankTwoTensor.h.
{
  SymmetricRankTwoTensorTempl<decltype(T() * T2())> result;
  for (const auto i : make_range(N))
    result._vals[i] = _vals[i] * a;
  return result;
}
operator*() [2/2]
template<typename T > template<typename T2 > TypeVector< typename CompareTypes< T, T2 >::supertype > SymmetricRankTwoTensorTempl< T >::operator* (const TypeVector< T2 > & a) const
Defines multiplication with a vector to get a vector.
Definition at line 541 of file SymmetricRankTwoTensor.h.
{
  TypeVector<typename CompareTypes<T, T2>::supertype> ret;
  ret(0) = a(0) * _vals[0] + a(1) * _vals[5] + a(2) * _vals[4];
  ret(1) = a(0) * _vals[5] + a(1) * _vals[1] + a(2) * _vals[3];
  ret(2) = a(0) * _vals[4] + a(1) * _vals[3] + a(2) * _vals[2];
}
operator*=()
template<typename T > SymmetricRankTwoTensorTempl< T > & SymmetricRankTwoTensorTempl< T >::operator*= (const T & a)
performs _vals *= a
Definition at line 415 of file SymmetricRankTwoTensorImplementation.h.
{
  for (std::size_t i = 0; i < N; ++i)
    _vals[i] *= a;
  return *this;
}
operator+()
template<typename T > template<typename T2 > SymmetricRankTwoTensorTempl< typename CompareTypes< T, T2 >::supertype > SymmetricRankTwoTensorTempl< T >::operator+ (const SymmetricRankTwoTensorTempl< T2 > & a) const
returns _vals + a
Definition at line 385 of file SymmetricRankTwoTensorImplementation.h.
{
  SymmetricRankTwoTensorTempl<typename CompareTypes<T, T2>::supertype> result;
  for (std::size_t i = 0; i < N; ++i)
    result(i) = _vals[i] + a(i);
  return result;
}
operator+=()
template<typename T > SymmetricRankTwoTensorTempl< T > & SymmetricRankTwoTensorTempl< T >::operator+= (const SymmetricRankTwoTensorTempl< T > & a)
adds a to _vals
Definition at line 366 of file SymmetricRankTwoTensorImplementation.h.
{
  for (std::size_t i = 0; i < N; ++i)
    _vals[i] += a._vals[i];
  return *this;
}
operator-() [1/2]
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::operator-
returns -_vals
Definition at line 408 of file SymmetricRankTwoTensorImplementation.h.
{
  return (*this) * -1.0;
}
operator-() [2/2]
template<typename T > template<typename T2 > SymmetricRankTwoTensorTempl< typename CompareTypes< T, T2 >::supertype > SymmetricRankTwoTensorTempl< T >::operator- (const SymmetricRankTwoTensorTempl< T2 > & a) const
returns _vals - a
Definition at line 396 of file SymmetricRankTwoTensorImplementation.h.
{
  SymmetricRankTwoTensorTempl<typename CompareTypes<T, T2>::supertype> result(
      SymmetricRankTwoTensorTempl<typename CompareTypes<T, T2>::supertype>::initNone);
  for (std::size_t i = 0; i < N; ++i)
    result(i) = _vals[i] - a(i);
  return result;
}
operator-=()
template<typename T > SymmetricRankTwoTensorTempl< T > & SymmetricRankTwoTensorTempl< T >::operator-= (const SymmetricRankTwoTensorTempl< T > & a)
sets _vals -= a and returns vals
Definition at line 375 of file SymmetricRankTwoTensorImplementation.h.
{
  for (std::size_t i = 0; i < N; ++i)
    _vals[i] -= a._vals[i];
  return *this;
}
operator/()
template<typename T > template<typename T2 > auto SymmetricRankTwoTensorTempl< T >::operator/ (const T2 & a) const -> typename std::enable_if<ScalarTraits<T2>::value, SymmetricRankTwoTensorTempl<decltype(T() / T2())>>::type
returns _vals/a
Definition at line 527 of file SymmetricRankTwoTensor.h.
{
  SymmetricRankTwoTensorTempl<decltype(T() / T2())> result;
  for (const auto i : make_range(N))
    result._vals[i] = _vals[i] / a;
  return result;
}
operator/=()
template<typename T > SymmetricRankTwoTensorTempl< T > & SymmetricRankTwoTensorTempl< T >::operator/= (const T & a)
performs _vals /= a
Definition at line 424 of file SymmetricRankTwoTensorImplementation.h.
{
  for (std::size_t i = 0; i < N; ++i)
    _vals[i] /= a;
  return *this;
}
operator=() [1/3]
template<typename T > SymmetricRankTwoTensorTempl< T > & SymmetricRankTwoTensorTempl< T >::operator= (const ColumnMajorMatrixTempl< T > & a)
Sets _vals to the values in a ColumnMajorMatrix (must be 3x3)
operator=() [2/3]
template<typename T > template<typename Scalar > boostcopy::enable_if_c< ScalarTraits< Scalar >::value, SymmetricRankTwoTensorTempl & >::type SymmetricRankTwoTensorTempl< T >::operator= (const Scalar & libmesh_dbg_varp) inline
Assignment-from-scalar operator.
Used only to zero out vectors.
Definition at line 252 of file SymmetricRankTwoTensor.h.
  {
    libmesh_assert_equal_to(p, Scalar(0));
    this->zero();
    return *this;
  }
operator=() [3/3]
template<typename T > template<typename T2 > SymmetricRankTwoTensorTempl< T > & SymmetricRankTwoTensorTempl< T >::operator= (const SymmetricRankTwoTensorTempl< T2 > & a)
sets _vals to a, and returns _vals
Definition at line 677 of file SymmetricRankTwoTensor.h.
{
  for (const auto i : make_range(N))
    (*this)(i) = a(i);
  return *this;
}
operator==()
template<typename T > template<typename T2 > bool SymmetricRankTwoTensorTempl< T >::operator== (const SymmetricRankTwoTensorTempl< T2 > & a) const
Defines logical equality with another SymmetricRankTwoTensorTempl<T2>
Definition at line 552 of file SymmetricRankTwoTensor.h.
{
  for (std::size_t i = 0; i < N; ++i)
    if (_vals[i] != a._vals[i])
      return false;
  return true;
}
outerProduct()
template<typename T > SymmetricRankFourTensorTempl< T > SymmetricRankTwoTensorTempl< T >::outerProduct (const SymmetricRankTwoTensorTempl< T > & a) const
returns C_ijkl = a_ij * b_kl
Definition at line 443 of file SymmetricRankTwoTensorImplementation.h.
{
  SymmetricRankFourTensorTempl<T> result;
  unsigned int index = 0;
  for (unsigned int i = 0; i < N; ++i)
  {
    const T & a = _vals[i];
    for (unsigned int j = 0; j < N; ++j)
      result._vals[index++] = a * b._vals[j];
  }
  return result;
}
plusTranspose() [1/2]
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::plusTranspose (const RankTwoTensorTempl< T > & a) static
return the matrix plus its transpose A-A^T (guaranteed symmetric)
Definition at line 335 of file SymmetricRankTwoTensorImplementation.h.
{
  return SymmetricRankTwoTensorTempl<T>(
             a(0, 0), a(0, 1), a(0, 2), a(1, 0), a(1, 1), a(1, 2), a(2, 0), a(2, 1), a(2, 2)) *
         2.0;
}
Referenced by SymmetricRankTwoTensorTempl< T >::d2thirdInvariant(), SymmetricRankTwoTensorTempl< T >::dsecondInvariant(), SymmetricRankTwoTensorTempl< T >::dthirdInvariant(), and SymmetricRankTwoTensorTempl< T >::thirdInvariant().
plusTranspose() [2/2]
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::plusTranspose (const SymmetricRankTwoTensorTempl< T > & a) static
Definition at line 344 of file SymmetricRankTwoTensorImplementation.h.
{
  return a * 2.0;
}
positiveProjectionEigenDecomposition()
template<typename T > SymmetricRankFourTensorTempl< T > SymmetricRankTwoTensorTempl< T >::positiveProjectionEigenDecomposition (std::vector< T > & eigval, RankTwoTensorTempl< T > & eigvec) const
return positive projection tensor of eigen-decomposition
Definition at line 573 of file SymmetricRankTwoTensor.h.
{
  // The calculate of projection tensor follows
  // C. Miehe and M. Lambrecht, Commun. Numer. Meth. Engng 2001; 17:337~353
  // Compute eigenvectors and eigenvalues of this tensor
  if (MooseUtils::IsLikeReal<T>::value)
  {
    this->symmetricEigenvaluesEigenvectors(eigval, eigvec);
    // Separate out positive and negative eigen values
    std::array<T, N> epos;
    std::array<T, N> d;
    for (unsigned int i = 0; i < N; ++i)
    {
      epos[i] = (std::abs(eigval[i]) + eigval[i]) / 2.0;
      d[i] = 0 < eigval[i] ? 1.0 : 0.0;
    }
    // projection tensor
    SymmetricRankFourTensorTempl<T> proj_pos;
    for (unsigned int a = 0; a < Ndim; ++a)
    {
      const auto Ma = SymmetricRankTwoTensorTempl<T>::selfOuterProduct(eigvec.column(a));
      proj_pos += d[a] * Ma.outerProduct(Ma);
    }
    for (const auto a : make_range(Ndim))
      for (const auto b : make_range(a))
      {
        const auto Ma = SymmetricRankTwoTensorTempl<T>::selfOuterProduct(eigvec.column(a));
        const auto Mb = SymmetricRankTwoTensorTempl<T>::selfOuterProduct(eigvec.column(b));
        SymmetricRankFourTensorTempl<T> Gabba(SymmetricRankFourTensorTempl<T>::initNone);
        for (const auto aa : make_range(N))
          for (const auto bb : make_range(N))
          {
            const auto i = SymmetricRankFourTensorTempl<T>::full_index[aa][bb][0];
            const auto j = SymmetricRankFourTensorTempl<T>::full_index[aa][bb][1];
            const auto k = SymmetricRankFourTensorTempl<T>::full_index[aa][bb][2];
            const auto l = SymmetricRankFourTensorTempl<T>::full_index[aa][bb][3];
            Gabba(aa, bb) = (Ma(i, k) * Mb(j, l) + Ma(i, l) * Mb(j, k) + Ma(j, l) * Mb(i, k) +
                             Ma(j, k) * Mb(i, l)) *
                            SymmetricRankFourTensorTempl<T>::mandelFactor(aa, bb);
          }
        T theta_ab;
        if (!MooseUtils::relativeFuzzyEqual(eigval[a], eigval[b]))
          theta_ab = 0.5 * (epos[a] - epos[b]) / (eigval[a] - eigval[b]);
        else
          theta_ab = 0.25 * (d[a] + d[b]);
        proj_pos += theta_ab * Gabba;
      }
    return proj_pos;
  }
  else
    mooseError("positiveProjectionEigenDecomposition is only available for ordered tensor "
               "component types");
}
print()
template<typename T > void SymmetricRankTwoTensorTempl< T >::print (std::ostream & stm = Moose::out) const
Print the rank two tensor.
Definition at line 636 of file SymmetricRankTwoTensorImplementation.h.
{
  for (std::size_t i = 0; i < N; ++i)
    stm << std::setw(15) << _vals[i] << std::endl;
}
printDualReal()
template<typename T > void SymmetricRankTwoTensorTempl< T >::printDualReal (unsigned int nDual, std::ostream & stm = Moose::out) const
Print the Real part of the DualReal rank two tensor along with its first nDual dual numbers.
printReal()
template<typename T > void SymmetricRankTwoTensorTempl< T >::printReal (std::ostream & stm = Moose::out) const
Print the Real part of the DualReal rank two tensor.
Definition at line 644 of file SymmetricRankTwoTensorImplementation.h.
{
  for (std::size_t i = 0; i < N; ++i)
    stm << std::setw(15) << MetaPhysicL::raw_value(_vals[i]) << std::endl;
}
rotate()
template<typename T > void SymmetricRankTwoTensorTempl< T >::rotate (const TypeTensor< T > & R)
rotates the tensor data given a rank two tensor rotation tensor _vals[i][j] = R_ij * R_jl * _vals[k][l]
Parameters
R rotation matrix as a TypeTensor
Definition at line 255 of file SymmetricRankTwoTensorImplementation.h.
{
  auto M = SymmetricRankFourTensorTempl<T>::rotationMatrix(R);
  *this = M * (*this);
}
row()
template<typename T > VectorValue< T > SymmetricRankTwoTensorTempl< T >::row (const unsigned int n) const
get the specified row of the tensor
multiply vector v with row n of this tensor
Definition at line 271 of file SymmetricRankTwoTensorImplementation.h.
{
  switch (n)
  {
    case 0:
      return VectorValue<T>(_vals[0], _vals[5] / mandelFactor(5), _vals[4] / mandelFactor(4));
    case 1:
      return VectorValue<T>(_vals[5] / mandelFactor(5), _vals[1], _vals[3] / mandelFactor(3));
    case 2:
      return VectorValue<T>(_vals[4] / mandelFactor(4), _vals[3] / mandelFactor(3), _vals[2]);
    default:
      mooseError("Invalid row");
  }
}
Referenced by SymmetricRankTwoTensorTempl< T >::column().
secondInvariant()
template<typename T > T SymmetricRankTwoTensorTempl< T >::secondInvariant
Denote the _vals[i][j] by A_ij, then S_ij = A_ij - de_ij*tr(A)/3 Then this returns (S_ij + S_ji)*(S_ij + S_ji)/8 Note the explicit symmeterisation.
Definition at line 475 of file SymmetricRankTwoTensorImplementation.h.
{
  T result;
  result = Utility::pow<2>(_vals[0] - _vals[1]) / 6.0;
  result += Utility::pow<2>(_vals[0] - _vals[2]) / 6.0;
  result += Utility::pow<2>(_vals[1] - _vals[2]) / 6.0;
  result += Utility::pow<2>(_vals[5]) / 2.0;
  result += Utility::pow<2>(_vals[4]) / 2.0;
  result += Utility::pow<2>(_vals[3]) / 2.0;
  return result;
}
selfOuterProduct()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::selfOuterProduct (const TypeVector< T > & v) static
SymmetricRankTwoTensorTempl<T> from outer product of a vector with itself.
Definition at line 764 of file SymmetricRankTwoTensorImplementation.h.
{
  return SymmetricRankTwoTensorTempl<T>(
      v(0) * v(0), v(1) * v(1), v(2) * v(2), v(1) * v(2), v(0) * v(2), v(0) * v(1));
}
Referenced by SymmetricRankTwoTensorTempl< T >::positiveProjectionEigenDecomposition().
setToIdentity()
template<typename T > void SymmetricRankTwoTensorTempl< T >::setToIdentity
set the tensor to the identity matrix
Definition at line 783 of file SymmetricRankTwoTensorImplementation.h.
{
  std::copy(identityCoords.begin(), identityCoords.end(), _vals.begin());
}
sin3Lode()
template<typename T > T SymmetricRankTwoTensorTempl< T >::sin3Lode (const T & r0, const T & r0_value) const
Sin(3*Lode_angle) If secondInvariant() <= r0 then return r0_value This is to gaurd against precision-loss errors.
Note that sin(3*Lode_angle) is not defined for secondInvariant() = 0
Definition at line 639 of file SymmetricRankTwoTensor.h.
{
  if (MooseUtils::IsLikeReal<T>::value)
  {
    T bar = secondInvariant();
    if (bar <= r0)
      // in this case the Lode angle is not defined
      return r0_value;
    else
      // the min and max here gaurd against precision-loss when bar is tiny but nonzero.
      return std::max(std::min(thirdInvariant() * -1.5 * std::sqrt(3.0) / std::pow(bar, 1.5), 1.0),
                      -1.0);
  }
  else
    mooseError("sin3Lode is only available for ordered tensor component types");
}
square()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::square
Returns the matrix squared.
Definition at line 351 of file SymmetricRankTwoTensorImplementation.h.
{
  return SymmetricRankTwoTensorTempl<T>::timesTranspose(*this);
}
surfaceFillFromInputVector()
template<typename T > void SymmetricRankTwoTensorTempl< T >::surfaceFillFromInputVector (const std::vector< T > & input)
sets _vals[0][0], _vals[0][1], _vals[1][0], _vals[1][1] to input, and the remainder to zero
syev()
template<typename T > void SymmetricRankTwoTensorTempl< T >::syev (const char * calculation_type, std::vector< T > & eigvals, std::vector< T > & a) const protected
Uses the petscblaslapack.h LAPACKsyev_ routine to find, for symmetric _vals: (1) the eigenvalues (if calculation_type == "N") (2) the eigenvalues and eigenvectors (if calculation_type == "V")
Parameters
calculation_type If "N" then calculation eigenvalues only
eigvals Eigenvalues are placed in this array, in ascending order
a Eigenvectors are placed in this array if calculation_type == "V". See code in dsymmetricEigenvalues for extracting eigenvectors from the a output.
Definition at line 670 of file SymmetricRankTwoTensorImplementation.h.
{
  mooseError("The syev method is only supported for Real valued tensors");
}
symmetricEigenvalues()
template<typename T > void SymmetricRankTwoTensorTempl< T >::symmetricEigenvalues (std::vector< T > & eigvals) const
computes eigenvalues, assuming tens is symmetric, and places them in ascending order in eigvals
Definition at line 711 of file SymmetricRankTwoTensorImplementation.h.
{
  RankTwoTensorTempl<T> a;
  symmetricEigenvaluesEigenvectors(eigvals, a);
}
symmetricEigenvaluesEigenvectors()
template<typename T > void SymmetricRankTwoTensorTempl< T >::symmetricEigenvaluesEigenvectors (std::vector< T > & eigvals, RankTwoTensorTempl< T > & eigvecs) const
computes eigenvalues and eigenvectors, assuming tens is symmetric, and places them in ascending order in eigvals.
eigvecs is a matrix with the first column being the first eigenvector, the second column being the second, etc.
Definition at line 727 of file SymmetricRankTwoTensorImplementation.h.
{
  mooseError(
      "symmetricEigenvaluesEigenvectors is only available for ordered tensor component types");
}
thirdInvariant()
template<typename T > T SymmetricRankTwoTensorTempl< T >::thirdInvariant
Denote the _vals[i][j] by A_ij, then S_ij = A_ij - de_ij*tr(A)/3 Then this returns det(S + S.transpose())/2 Note the explicit symmeterisation.
Definition at line 540 of file SymmetricRankTwoTensorImplementation.h.
{
  const auto s = SymmetricRankTwoTensorTempl<T>::plusTranspose(deviatoric()) * 0.5;
  return s(0) * (s(1) * s(2) - s(3) / MathUtils::sqrt2 * s(3) / MathUtils::sqrt2) -
         s(5) / MathUtils::sqrt2 *
             (s(5) / MathUtils::sqrt2 * s(2) - s(3) / MathUtils::sqrt2 * s(4) / MathUtils::sqrt2) +
         s(4) / MathUtils::sqrt2 *
             (s(5) / MathUtils::sqrt2 * s(3) / MathUtils::sqrt2 - s(1) * s(4) / MathUtils::sqrt2);
}
timesTranspose() [1/2]
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::timesTranspose (const RankTwoTensorTempl< T > & a) static
return the matrix multiplied with its transpose A*A^T (guaranteed symmetric)
Definition at line 288 of file SymmetricRankTwoTensorImplementation.h.
{
  return SymmetricRankTwoTensorTempl<T>(a(0, 0) * a(0, 0) + a(0, 1) * a(0, 1) + a(0, 2) * a(0, 2),
                                        a(1, 0) * a(1, 0) + a(1, 1) * a(1, 1) + a(1, 2) * a(1, 2),
                                        a(2, 0) * a(2, 0) + a(2, 1) * a(2, 1) + a(2, 2) * a(2, 2),
                                        a(1, 0) * a(2, 0) + a(1, 1) * a(2, 1) + a(1, 2) * a(2, 2),
                                        a(0, 0) * a(2, 0) + a(0, 1) * a(2, 1) + a(0, 2) * a(2, 2),
                                        a(0, 0) * a(1, 0) + a(0, 1) * a(1, 1) + a(0, 2) * a(1, 2));
}
Referenced by SymmetricRankTwoTensorTempl< T >::square().
timesTranspose() [2/2]
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::timesTranspose (const SymmetricRankTwoTensorTempl< T > & a) static
Definition at line 300 of file SymmetricRankTwoTensorImplementation.h.
{
  return SymmetricRankTwoTensorTempl<T>::fromRawComponents(
      a._vals[0] * a._vals[0] + a._vals[4] * a._vals[4] / 2.0 + a._vals[5] * a._vals[5] / 2.0,
      a._vals[1] * a._vals[1] + a._vals[3] * a._vals[3] / 2.0 + a._vals[5] * a._vals[5] / 2.0,
      a._vals[2] * a._vals[2] + a._vals[3] * a._vals[3] / 2.0 + a._vals[4] * a._vals[4] / 2.0,
      a._vals[1] * a._vals[3] + a._vals[2] * a._vals[3] +
          a._vals[4] * a._vals[5] / MathUtils::sqrt2,
      a._vals[0] * a._vals[4] + a._vals[2] * a._vals[4] +
          a._vals[3] * a._vals[5] / MathUtils::sqrt2,
      a._vals[0] * a._vals[5] + a._vals[1] * a._vals[5] +
          a._vals[3] * a._vals[4] / MathUtils::sqrt2);
}
tr()
template<typename T > T SymmetricRankTwoTensorTempl< T >::tr () const inline
Returns the trace.
Definition at line 225 of file SymmetricRankTwoTensor.h.
{ return _vals[0] + _vals[1] + _vals[2]; }
trace()
template<typename T > T SymmetricRankTwoTensorTempl< T >::trace
returns the trace of the tensor, ie _vals[i][i] (sum i = 0, 1, 2)
Definition at line 509 of file SymmetricRankTwoTensorImplementation.h.
{
  return tr();
}
transpose()
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::transpose
Returns a matrix that is the transpose of the matrix this was called on.
This is a non-operation.
Definition at line 263 of file SymmetricRankTwoTensorImplementation.h.
{
  return *this;
}
transposeTimes() [1/2]
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::transposeTimes (const RankTwoTensorTempl< T > & a) static
return the matrix multiplied with its transpose A^T*A (guaranteed symmetric)
Definition at line 316 of file SymmetricRankTwoTensorImplementation.h.
{
  return SymmetricRankTwoTensorTempl<T>(a(0, 0) * a(0, 0) + a(1, 0) * a(1, 0) + a(2, 0) * a(2, 0),
                                        a(0, 1) * a(0, 1) + a(1, 1) * a(1, 1) + a(2, 1) * a(2, 1),
                                        a(0, 2) * a(0, 2) + a(1, 2) * a(1, 2) + a(2, 2) * a(2, 2),
                                        a(0, 1) * a(0, 2) + a(1, 1) * a(1, 2) + a(2, 1) * a(2, 2),
                                        a(0, 0) * a(0, 2) + a(1, 0) * a(1, 2) + a(2, 0) * a(2, 2),
                                        a(0, 0) * a(0, 1) + a(1, 0) * a(1, 1) + a(2, 0) * a(2, 1));
}
transposeTimes() [2/2]
template<typename T > SymmetricRankTwoTensorTempl< T > SymmetricRankTwoTensorTempl< T >::transposeTimes (const SymmetricRankTwoTensorTempl< T > & a) static
Definition at line 328 of file SymmetricRankTwoTensorImplementation.h.
{
  return timesTranspose(a);
}
zero()
template<typename T > void SymmetricRankTwoTensorTempl< T >::zero
Set all components to zero.
Definition at line 358 of file SymmetricRankTwoTensorImplementation.h.
{
  for (std::size_t i = 0; i < N; ++i)
    _vals[i] = 0.0;
}
Referenced by MathUtils::mooseSetToZero< ADSymmetricRankTwoTensor >(), MathUtils::mooseSetToZero< SymmetricRankTwoTensor >(), and SymmetricRankTwoTensorTempl< T >::operator=().
Friends And Related Function Documentation
dataLoad
template<typename T > template<class T2 > void dataLoad (std::istream & , SymmetricRankTwoTensorTempl< T2 > & , void *) friend
dataStore
template<typename T > template<class T2 > void dataStore (std::ostream & , SymmetricRankTwoTensorTempl< T2 > & , void *) friend
SymmetricRankFourTensorTempl
template<typename T > template<class T2 > friend class SymmetricRankFourTensorTempl friend
Definition at line 490 of file SymmetricRankTwoTensor.h.
Member Data Documentation
_vals
template<typename T > std::array<T, N> SymmetricRankTwoTensorTempl< T >::_vals private
Definition at line 482 of file SymmetricRankTwoTensor.h.
Referenced by dataLoad(), dataStore(), SymmetricRankTwoTensorTempl< T >::doubleContraction(), SymmetricRankTwoTensorTempl< T >::fromRawComponents(), SymmetricRankTwoTensorTempl< T >::operator!=(), SymmetricRankTwoTensorTempl< T >::operator()(), SymmetricRankFourTensorTempl< T >::operator*(), SymmetricRankTwoTensorTempl< T >::operator*(), SymmetricRankTwoTensorTempl< T >::operator+=(), SymmetricRankTwoTensorTempl< T >::operator-=(), SymmetricRankTwoTensorTempl< T >::operator/(), SymmetricRankTwoTensorTempl< T >::operator==(), SymmetricRankTwoTensorTempl< T >::outerProduct(), SymmetricRankTwoTensorTempl< T >::SymmetricRankTwoTensorTempl(), SymmetricRankTwoTensorTempl< T >::timesTranspose(), and SymmetricRankTwoTensorTempl< T >::tr().
full_index
template<typename T > constexpr unsigned int SymmetricRankTwoTensorTempl< T >::full_index[6][2] = {{0, 0}, {1, 1}, {2, 2}, {1, 2}, {0, 2}, {0, 1}} static constexpr
Definition at line 85 of file SymmetricRankTwoTensor.h.
identityCoords
template<typename T > constexpr std::array< Real, SymmetricRankTwoTensorTempl< T >::N > SymmetricRankTwoTensorTempl< T >::identityCoords = {{1, 1, 1, 0, 0, 0}} static constexpr private
Definition at line 479 of file SymmetricRankTwoTensor.h.
N
template<typename T > constexpr unsigned int SymmetricRankTwoTensorTempl< T >::N = Ndim + (Ndim * (Ndim - 1)) / 2 static constexpr
Definition at line 81 of file SymmetricRankTwoTensor.h.
Referenced by SymmetricRankTwoTensorTempl< T >::SymmetricRankTwoTensorTempl().
Ndim
template<typename T > constexpr unsigned int SymmetricRankTwoTensorTempl< T >::Ndim = Moose::dim static constexpr
tensor dimension and Mandel vector length
Definition at line 80 of file SymmetricRankTwoTensor.h.
Referenced by SymmetricRankTwoTensorTempl< T >::mandelFactor().
reverse_index
template<typename T > constexpr unsigned int SymmetricRankTwoTensorTempl< T >::reverse_index[3][3] = {{0, 5, 4}, {5, 1, 3}, {4, 3, 2}} static constexpr
Definition at line 88 of file SymmetricRankTwoTensor.h.
Referenced by SymmetricRankTwoTensorTempl< T >::operator()().
The documentation for this class was generated from the following files:
moose/framework/include/utils_nonunity/SymmetricRankTwoTensor.h
moose/framework/include/utils_nonunity/SymmetricRankTwoTensorImplementation.h