Zapdos: MeshChangedInterface Class Reference
MeshChangedInterface Class Reference
Interface for notifications that the mesh has changed.
#include <MeshChangedInterface.h>
Public Member Functions
MeshChangedInterface (const InputParameters &params)
virtual ~MeshChangedInterface ()=default
virtual void meshChanged ()
Called on this object when the mesh changes.
Static Public Member Functions
static InputParameters validParams ()
Protected Attributes
FEProblemBase & _mci_feproblem
Reference to FEProblemBase instance.
Detailed Description
Interface for notifications that the mesh has changed.
Definition at line 23 of file MeshChangedInterface.h.
Constructor & Destructor Documentation
MeshChangedInterface()
MeshChangedInterface::MeshChangedInterface (const InputParameters & params)
Definition at line 22 of file MeshChangedInterface.C.
  : _mci_feproblem(*params.getCheckedPointerParam<FEProblemBase *>("_fe_problem_base"))
{
  _mci_feproblem.notifyWhenMeshChanges(this);
}
~MeshChangedInterface()
virtual MeshChangedInterface::~MeshChangedInterface () virtual default
Member Function Documentation
meshChanged()
virtual void MeshChangedInterface::meshChanged () inline virtual
Called on this object when the mesh changes.
Reimplemented in GeometryBase, EqualValueBoundaryConstraint, DiracKernelBase, FVPointValueConstraint, MeshDivision, Console, Exodus, Nemesis, OversampleOutput, Positions, ExplicitTimeIntegrator, MultiAppVariableValueSamplePostprocessorTransfer, GhostingUserObject, NearestNodeNumberUO, RadialAverage, MooseVariableDataFV< OutputType >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 34 of file MeshChangedInterface.h.
{}
Referenced by MooseVariableFE< OutputType >::meshChanged(), and MooseVariableFV< OutputType >::meshChanged().
validParams()
InputParameters MeshChangedInterface::validParams () static
Definition at line 15 of file MeshChangedInterface.C.
{
  InputParameters params = emptyInputParameters();
  return params;
}
Referenced by AuxKernelTempl< ComputeValueType >::validParams(), AuxScalarKernel::validParams(), ResidualObject::validParams(), and FVInterfaceKernel::validParams().
Member Data Documentation
_mci_feproblem
FEProblemBase& MeshChangedInterface::_mci_feproblem protected
Reference to FEProblemBase instance.
Definition at line 38 of file MeshChangedInterface.h.
Referenced by MeshChangedInterface().
The documentation for this class was generated from the following files:
moose/framework/include/interfaces/MeshChangedInterface.h
moose/framework/src/interfaces/MeshChangedInterface.C