Zapdos: NonADFunctorInterface Class Reference
NonADFunctorInterface Class Reference
An interface for accessing Moose::Functors for systems that do not care about automatic differentiation, e.g.
#include <NonADFunctorInterface.h>
Public Member Functions
NonADFunctorInterface (const MooseObject *moose_object)
template<>
const Moose::Functor< Real > * defaultFunctor (const std::string &name)
Static Public Member Functions
static InputParameters validParams ()
static std::string deduceFunctorName (const std::string &name, const InputParameters &params)
Helper to look up a functor name through the input parameter keys.
Protected Member Functions
std::string deduceFunctorName (const std::string &name) const
Small helper to look up a functor name through the input parameter keys.
template<typename T >
const Moose::Functor< T > & getFunctor (const std::string &name)
Retrieves a functor from the subproblem.
template<typename T >
const Moose::Functor< T > & getFunctor (const std::string &name, THREAD_ID tid)
Retrieves a functor from the subproblem.
template<typename T >
const Moose::Functor< T > & getFunctor (const std::string &name, SubProblem &subproblem)
Retrieves a functor from the passed-in subproblem.
template<typename T >
const Moose::Functor< T > & getFunctor (const std::string &name, SubProblem &subproblem, THREAD_ID tid)
Retrieves a functor from the passed-in subproblem.
bool isFunctor (const std::string &name) const
Checks the subproblem for the given functor.
bool isFunctor (const std::string &name, const SubProblem &subproblem) const
Checks the passed-in subproblem for the given functor.
Moose::ElemArg makeElemArg (const Elem *elem, bool correct_skewnewss=false) const
Helper method to create an elemental argument for a functor that includes whether to perform skewness corrections.
Private Member Functions
virtual bool isADObject () const override
Whether this interface is for an AD object.
template<typename T >
const Moose::Functor< T > & getFunctorByName (const std::string &name, SubProblem &subproblem, THREAD_ID tid)
Retrieves a functor from the passed-in subproblem.
template<typename T >
const Moose::Functor< T > * defaultFunctor (const std::string &name)
Helper function to parse default functor values.
template<>
const Moose::Functor< Real > * defaultFunctor (const std::string &name)
template<>
const Moose::Functor< ADReal > * defaultFunctor (const std::string &name)
Private Attributes
const InputParameters & _fi_params
Parameters of the object with this interface.
const std::string _fi_name
The name of the object that this interface belongs to.
SubProblem *const _fi_subproblem
Pointer to subproblem if the subproblem pointer parameter was set.
const THREAD_ID _fi_tid
Current threaded it.
std::vector< std::unique_ptr< Moose::Functor< Real > > > _default_real_functors
Storage vector for Moose::Functor<Real> default objects.
std::vector< std::unique_ptr< Moose::Functor< ADReal > > > _default_ad_real_functors
Storage vector for Moose::Functor<ADReal> default objects.
Detailed Description
An interface for accessing Moose::Functors for systems that do not care about automatic differentiation, e.g.
auxiliary kernels
Definition at line 19 of file NonADFunctorInterface.h.
Constructor & Destructor Documentation
NonADFunctorInterface()
NonADFunctorInterface::NonADFunctorInterface (const MooseObject * moose_object)
Definition at line 18 of file NonADFunctorInterface.C.
  : FunctorInterface(moose_object)
{
}
Member Function Documentation
deduceFunctorName() [1/2]
std::string FunctorInterface::deduceFunctorName (const std::string & name) const protected inherited
Small helper to look up a functor name through the input parameter keys.
Definition at line 60 of file FunctorInterface.C.
{
  return deduceFunctorName(name, _fi_params);
}
deduceFunctorName() [2/2]
std::string FunctorInterface::deduceFunctorName (const std::string & name, const InputParameters & params) static inherited
Helper to look up a functor name through the input parameter keys.
Parameters
name The input parameter name that we are trying to deduce the functor name for
params The input parameters object that we will be checking for parameters named name
Returns
The functor name
Definition at line 28 of file FunctorInterface.C.
{
  if (params.isParamValid(name))
  {
    if (params.have_parameter<MooseFunctorName>(name))
      return params.get<MooseFunctorName>(name);
    // variables, functor material properties, functions, and post-processors are also functors
    else if (params.have_parameter<MaterialPropertyName>(name))
      return params.get<MaterialPropertyName>(name);
    else if (params.have_parameter<VariableName>(name))
      return params.get<VariableName>(name);
    else if (params.have_parameter<std::vector<VariableName>>(name))
    {
      const auto & var_names = params.get<std::vector<VariableName>>(name);
      if (var_names.size() != 1)
        mooseError("We only support a single variable name for retrieving a functor");
      return var_names[0];
    }
    else if (params.have_parameter<NonlinearVariableName>(name))
      return params.get<NonlinearVariableName>(name);
    else if (params.have_parameter<FunctionName>(name))
      return params.get<FunctionName>(name);
    else if (params.have_parameter<PostprocessorName>(name))
      return params.get<PostprocessorName>(name);
    else
      mooseError("Invalid parameter type for retrieving a functor");
  }
  else
    return name;
}
Referenced by FunctorInterface::deduceFunctorName(), FunctorInterface::getFunctor(), and FunctorInterface::isFunctor().
defaultFunctor() [1/4]
template<typename T > const Moose::Functor< T > * FunctorInterface::defaultFunctor (const std::string & name) private inherited
Helper function to parse default functor values.
This is implemented as a specialization for supported types and returns NULL in all other cases.
Definition at line 220 of file FunctorInterface.h.
{
  return nullptr;
}
defaultFunctor() [2/4]
template<> const Moose::Functor< Real > * FunctorInterface::defaultFunctor (const std::string & name) private inherited
defaultFunctor() [3/4]
template<> const Moose::Functor< ADReal > * FunctorInterface::defaultFunctor (const std::string & name) private inherited
defaultFunctor() [4/4]
template<> const Moose::Functor< ADReal > * FunctorInterface::defaultFunctor (const std::string & name) inherited
Definition at line 67 of file FunctorInterface.C.
{
  std::istringstream ss(name);
  Real real_value;
  // check if the string parsed cleanly into a Real number
  if (ss >> real_value && ss.eof())
  {
    _default_real_functors.emplace_back(std::make_unique<Moose::Functor<Real>>(
        std::make_unique<Moose::ConstantFunctor<Real>>(real_value)));
    auto & default_property = _default_real_functors.back();
    return default_property.get();
  }
  return nullptr;
}
getFunctor() [1/4]
template<typename T > const Moose::Functor< T > & FunctorInterface::getFunctor (const std::string & name) protected inherited
Retrieves a functor from the subproblem.
This method also leverages the ability to create default functors if the user passed an integer or real in the input file
Parameters
name The name of the functor to retrieve. This should match the functor parameter name, \emph not the actual name of the functor created in the input file
Returns
The functor
Definition at line 191 of file FunctorInterface.h.
{
  mooseAssert(_fi_subproblem, "This must be non-null");
  return getFunctor<T>(name, *_fi_subproblem, _fi_tid);
}
Referenced by MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl().
getFunctor() [2/4]
template<typename T > const Moose::Functor< T > & FunctorInterface::getFunctor (const std::string & name, SubProblem & subproblem) protected inherited
Retrieves a functor from the passed-in subproblem.
This method also leverages the ability to create default functors if the user passed an integer or real in the input file
Parameters
name The name of the functor to retrieve. This should match the functor parameter name, \emph not the actual name of the functor created in the input file
subproblem The subproblem to query for the functor
Returns
The functor
Definition at line 176 of file FunctorInterface.h.
{
  return getFunctor<T>(name, subproblem, _fi_tid);
}
getFunctor() [3/4]
template<typename T > const Moose::Functor< T > & FunctorInterface::getFunctor (const std::string & name, SubProblem & subproblem, THREAD_ID tid) protected inherited
Retrieves a functor from the passed-in subproblem.
This method also leverages the ability to create default functors if the user passed an integer or real in the input file
Parameters
name The name of the functor to retrieve. This should match the functor parameter name, \emph not the actual name of the functor created in the input file
subproblem The subproblem to query for the functor
tid The thread ID used to retrieve the functor from the subproblem
Returns
The functor
Definition at line 167 of file FunctorInterface.h.
{
  // Check if the supplied parameter is a valid input parameter key
  std::string functor_name = deduceFunctorName(name);
  return getFunctorByName<T>(functor_name, subproblem, tid);
}
getFunctor() [4/4]
template<typename T > const Moose::Functor< T > & FunctorInterface::getFunctor (const std::string & name, THREAD_ID tid) protected inherited
Retrieves a functor from the subproblem.
This method also leverages the ability to create default functors if the user passed an integer or real in the input file
Parameters
name The name of the functor to retrieve. This should match the functor parameter name, \emph not the actual name of the functor created in the input file
tid The thread ID used to retrieve the functor from this interface's subproblem
Returns
The functor
Definition at line 183 of file FunctorInterface.h.
{
  mooseAssert(_fi_subproblem, "This must be non-null");
  return getFunctor<T>(name, *_fi_subproblem, tid);
}
getFunctorByName()
template<typename T > const Moose::Functor< T > & FunctorInterface::getFunctorByName (const std::string & name, SubProblem & subproblem, THREAD_ID tid) private inherited
Retrieves a functor from the passed-in subproblem.
This method also leverages the ability to create default functors if the user passed an integer or real in the input file
Parameters
name The actual name of the functor to retrieve instead of the parameter name
subproblem The subproblem to query for the functor
tid The thread ID used to retrieve the functor from the subproblem
Returns
The functor
Definition at line 199 of file FunctorInterface.h.
{
  // Check if it's just a constant
  const auto * const default_functor = defaultFunctor<T>(name);
  if (default_functor)
    return *default_functor;
  return subproblem.getFunctor<T>(name, tid, _fi_name, isADObject());
}
isADObject()
virtual bool NonADFunctorInterface::isADObject () const inline override private virtual
Whether this interface is for an AD object.
Implements FunctorInterface.
Definition at line 27 of file NonADFunctorInterface.h.
{ return false; }
isFunctor() [1/2]
bool FunctorInterface::isFunctor (const std::string & name) const protected inherited
Checks the subproblem for the given functor.
This will not query default functors potentially stored in this object, e.g. this method will return false if the user passed an int or real to the functor param in the input file
Parameters
name The name of the functor to check. This should match the functor parameter name, \emph not the actual name of the functor created in the input file
Returns
Whether the subproblem has the specified functor
Definition at line 113 of file FunctorInterface.C.
{
  mooseAssert(_fi_subproblem, "This must be non-null");
  return isFunctor(name, *_fi_subproblem);
}
Referenced by FunctorInterface::isFunctor().
isFunctor() [2/2]
bool FunctorInterface::isFunctor (const std::string & name, const SubProblem & subproblem) const protected inherited
Checks the passed-in subproblem for the given functor.
This will not query default functors potentially stored in this object, e.g. this method will return false if the user passed an int or real to the functor param in the input file
Parameters
name The name of the functor to check. This should match the functor parameter name, \emph not the actual name of the functor created in the input file
subproblem The subproblem to query for the functor
Returns
Whether the subproblem has the specified functor
Definition at line 104 of file FunctorInterface.C.
{
  // Check if the supplied parameter is a valid input parameter key
  std::string functor_name = deduceFunctorName(name);
  return subproblem.hasFunctor(functor_name, _fi_tid);
}
makeElemArg()
Moose::ElemArg FunctorInterface::makeElemArg (const Elem * elem, bool correct_skewnewss = false) const protected inherited
Helper method to create an elemental argument for a functor that includes whether to perform skewness corrections.
Definition at line 120 of file FunctorInterface.C.
{
  return {elem, correct_skewness};
}
Referenced by FVCoupledForce::computeQpResidual(), FVFunctorTimeKernel::computeQpResidual(), FVBoundedValueConstraint::computeQpResidual(), FVIntegralValueConstraint::computeQpResidual(), FVPointValueConstraint::computeQpResidual(), FunctorAux::computeValue(), SecondTimeDerivativeAux::computeValue(), TimeDerivativeAux::computeValue(), and FunctorTimes::initialize().
validParams()
InputParameters NonADFunctorInterface::validParams () static
Definition at line 13 of file NonADFunctorInterface.C.
{
  return FunctorInterface::validParams();
}
Referenced by FunctorPositions::validParams(), Postprocessor::validParams(), FunctorTimes::validParams(), and SideIntegralFunctorUserObject::validParams().
Member Data Documentation
_default_ad_real_functors
std::vector<std::unique_ptr<Moose::Functor<ADReal> > > FunctorInterface::_default_ad_real_functors private inherited
Storage vector for Moose::Functor<ADReal> default objects.
Definition at line 162 of file FunctorInterface.h.
_default_real_functors
std::vector<std::unique_ptr<Moose::Functor<Real> > > FunctorInterface::_default_real_functors private inherited
Storage vector for Moose::Functor<Real> default objects.
Definition at line 159 of file FunctorInterface.h.
Referenced by FunctorInterface::defaultFunctor().
_fi_name
const std::string FunctorInterface::_fi_name private inherited
The name of the object that this interface belongs to.
Definition at line 150 of file FunctorInterface.h.
Referenced by FunctorInterface::getFunctorByName().
_fi_params
const InputParameters& FunctorInterface::_fi_params private inherited
Parameters of the object with this interface.
Definition at line 147 of file FunctorInterface.h.
Referenced by FunctorInterface::deduceFunctorName().
_fi_subproblem
SubProblem* const FunctorInterface::_fi_subproblem private inherited
Pointer to subproblem if the subproblem pointer parameter was set.
Definition at line 153 of file FunctorInterface.h.
Referenced by FunctorInterface::getFunctor(), and FunctorInterface::isFunctor().
_fi_tid
const THREAD_ID FunctorInterface::_fi_tid private inherited
Current threaded it.
Definition at line 156 of file FunctorInterface.h.
Referenced by FunctorInterface::getFunctor(), and FunctorInterface::isFunctor().
The documentation for this class was generated from the following files:
moose/framework/include/interfaces/NonADFunctorInterface.h
moose/framework/src/interfaces/NonADFunctorInterface.C