Zapdos: MaterialPropertyStorage Class Reference
MaterialPropertyStorage Class Reference
Stores the stateful material properties computed by materials.
#include <MaterialPropertyStorage.h>
Public Types
typedef HashMap< const Elem *, HashMap< unsigned int, MaterialProperties > > PropsType
Accessible type of the stored material property data.
Public Member Functions
MaterialPropertyStorage (MaterialPropertyRegistry &registry)
void prolongStatefulProps (processor_id_type pid, const std::vector< std::vector< QpMap > > &refinement_map, const QBase &qrule, const QBase &qrule_face, MaterialPropertyStorage &parent_material_props, const THREAD_ID tid, const Elem &elem, const int input_parent_side, const int input_child, const int input_child_side)
Creates storage for newly created elements from mesh Adaptivity.
void updateStatefulPropsForPRefinement (const processor_id_type pid, const std::vector< QpMap > &p_refinement_map, const QBase &qrule, const QBase &qrule_face, const THREAD_ID tid, const Elem &elem, const int input_side)
Based on the p-refinement flag of elem, either prolong (for refinement) or restrict (for coarsening) the stateful material property data.
void restrictStatefulProps (const std::vector< std::pair< unsigned int, QpMap > > &coarsening_map, const std::vector< const Elem * > &coarsened_element_children, const QBase &qrule, const QBase &qrule_face, const THREAD_ID tid, const Elem &elem, int input_side=-1)
Creates storage for newly created elements from mesh Adaptivity.
void initStatefulProps (const THREAD_ID tid, const std::vector< std::shared_ptr< MaterialBase > > &mats, const unsigned int n_qpoints, const Elem &elem, const unsigned int side=0)
Initialize stateful material properties.
void shift ()
Shift the material properties in time.
void copy (const THREAD_ID tid, const Elem &elem_to, const Elem &elem_from, unsigned int side, unsigned int n_qpoints)
Copy material properties from elem_from to elem_to.
void copy (const THREAD_ID tid, const Elem *elem_to, const Elem *elem_from, unsigned int side, unsigned int n_qpoints)
Copy material properties from elem_from to elem_to.
void swap (const THREAD_ID tid, const Elem &elem, unsigned int side)
Swap (shallow copy) material properties in MaterialData and MaterialPropertyStorage Thread safe.
void swapBack (const THREAD_ID tid, const Elem &elem, unsigned int side)
Swap (shallow copy) material properties in MaterialPropertyStorage and MaterialDat Thread safe.
bool hasStatefulProperties () const
bool hasOlderProperties () const
bool hasProperty (const std::string &prop_name) const
unsigned int addProperty (const std::string &prop_name, const unsigned int state)
Adds a property with the name prop_name and state state (0 = current, 1 = old, etc)
const std::vector< unsigned int > & statefulProps () const
const std::unordered_map< unsigned int, std::string > & statefulPropNames () const
const MaterialPropertyRegistry & getMaterialPropertyRegistry () const
bool isStatefulProp (const std::string &prop_name) const
void eraseProperty (const Elem *elem)
Remove the property storage and element pointer from internal data structures Use this when elements are deleted so we don't end up with invalid elem pointers (for e.g.
unsigned int maxState () const
unsigned int numStates () const
IntRange< unsigned int > stateIndexRange () const
IntRange< unsigned int > statefulIndexRange () const
MaterialData & getMaterialData (const THREAD_ID tid)
const PropsType & props (const unsigned int state=0) const
Access methods to the stored material property data with the given state state.
const MaterialProperties & props (const Elem *elem, unsigned int side, const unsigned int state=0) const
MaterialProperties & setProps (const Elem *elem, unsigned int side, const unsigned int state=0)
Protected Member Functions
void sizeProps (MaterialProperties &mp, unsigned int size)
Protected Attributes
std::array< PropsType, MaterialData::max_state+1 > _storage
The actual storage.
std::unordered_map< unsigned int, std::string > _stateful_prop_names
Mapping from stateful property ID to property name.
std::vector< unsigned int > _stateful_prop_id_to_prop_id
the vector of stateful property ids (the vector index is the map to stateful prop_id)
Private Member Functions
void initProps (const THREAD_ID tid, const Elem *elem, unsigned int side, unsigned int n_qpoints)
Initializes hashmap entries for element and side to proper qpoint and property count sizes.
void initProps (const THREAD_ID tid, const unsigned int state, const Elem *elem, unsigned int side, unsigned int n_qpoints)
Initializes just one hashmap's entries.
PropsType & setProps (const unsigned int state)
MaterialProperties & initAndSetProps (const Elem *elem, const unsigned int side, const unsigned int state)
Static Private Member Functions
static void shallowSwapData (const std::vector< unsigned int > &stateful_prop_ids, MaterialProperties &data, MaterialProperties &data_from)
Shallow copies of material properties.
static void shallowSwapDataBack (const std::vector< unsigned int > &stateful_prop_ids, MaterialProperties &data, MaterialProperties &data_from)
Private Attributes
unsigned int _max_state
The maximum state (0 = current, 1 = old, 2 = older)
libMesh::Threads::spin_mutex & _spin_mtx
MaterialPropertyRegistry & _registry
Shared registry (across storage objects) for property names and IDs.
std::vector< MaterialData > _material_data
The threaded material data.
Friends
class ProjectMaterialProperties
class RedistributeProperties
void dataLoad (std::istream &, MaterialPropertyStorage &, void *)
void dataStore (std::ostream &, MaterialPropertyStorage &, void *)
Detailed Description
Stores the stateful material properties computed by materials.
Thread-safe
Definition at line 40 of file MaterialPropertyStorage.h.
Member Typedef Documentation
PropsType
typedef HashMap<const Elem *, HashMap<unsigned int, MaterialProperties> > MaterialPropertyStorage::PropsType
Accessible type of the stored material property data.
This probably should have been returned as a proxy class; only access it via foo[elem][side] and maybe we'll be able to refactor it in the future without breaking your code.
Definition at line 230 of file MaterialPropertyStorage.h.
Constructor & Destructor Documentation
MaterialPropertyStorage()
MaterialPropertyStorage::MaterialPropertyStorage (MaterialPropertyRegistry & registry)
Definition at line 21 of file MaterialPropertyStorage.C.
  : _max_state(0), _spin_mtx(libMesh::Threads::spin_mtx), _registry(registry)
{
  _material_data.reserve(libMesh::n_threads());
  for (const auto tid : make_range(libMesh::n_threads()))
    _material_data.emplace_back(*this, tid);
}
Member Function Documentation
addProperty()
unsigned int MaterialPropertyStorage::addProperty (const std::string & prop_name, const unsigned int state)
Adds a property with the name prop_name and state state (0 = current, 1 = old, etc)
This is idempotent - calling multiple times with the same name will provide the same id and works fine.
Definition at line 355 of file MaterialPropertyStorage.C.
{
  if (state > MaterialData::max_state)
    mooseError("Material property state of ",
               state,
               " is not supported. Max state supported: ",
               MaterialData::max_state);
  // Increment state as needed
  if (maxState() < state)
    _max_state = state;
  const auto prop_id = _registry.addOrGetID(prop_name, {});
  if (state > 0)
  {
    if (std::find(_stateful_prop_id_to_prop_id.begin(),
                  _stateful_prop_id_to_prop_id.end(),
                  prop_id) == _stateful_prop_id_to_prop_id.end())
      _stateful_prop_id_to_prop_id.push_back(prop_id);
    _stateful_prop_names[prop_id] = prop_name;
  }
  return prop_id;
}
Referenced by MaterialData::addPropertyHelper().
copy() [1/2]
void MaterialPropertyStorage::copy (const THREAD_ID tid, const Elem & elem_to, const Elem & elem_from, unsigned int side, unsigned int n_qpoints)
Copy material properties from elem_from to elem_to.
Thread safe.
WARNING: This is not capable of copying material data to/from elements on other processors. It only works if both elem_to and elem_from are both on the local processor. We can't currently check to ensure that they're on processor here because this isn't a ParallelObject.
Parameters
tid The thread ID
elem_to Element to copy data to
elem_from Element to copy data from
side Side number (elemental material properties have this equal to zero)
n_qpoints number of quadrature points to work with
Definition at line 297 of file MaterialPropertyStorage.C.
{
  copy(tid, &elem_to, &elem_from, side, n_qpoints);
}
Referenced by MaterialData::copy(), and copy().
copy() [2/2]
void MaterialPropertyStorage::copy (const THREAD_ID tid, const Elem * elem_to, const Elem * elem_from, unsigned int side, unsigned int n_qpoints)
Copy material properties from elem_from to elem_to.
Similar to the other method but using pointers to elements instead of references.
Parameters
tid The thread ID
elem_to Pointer to the element to copy data to
elem_from Pointer to the element to copy data from
side Side number (elemental material properties have this equal to zero)
n_qpoints number of quadrature points to work with
Definition at line 307 of file MaterialPropertyStorage.C.
{
  initProps(tid, elem_to, side, n_qpoints);
  for (const auto state : stateIndexRange())
  {
    const auto & from_props = props(elem_from, side, state);
    auto & to_props = setProps(elem_to, side, state);
    for (const auto i : index_range(_stateful_prop_id_to_prop_id))
      for (const auto qp : make_range(n_qpoints))
        to_props[i].qpCopy(qp, from_props[i], qp);
  }
}
eraseProperty()
void MaterialPropertyStorage::eraseProperty (const Elem * elem)
Remove the property storage and element pointer from internal data structures Use this when elements are deleted so we don't end up with invalid elem pointers (for e.g.
stateful properties) hanging around in our data structures
Definition at line 60 of file MaterialPropertyStorage.C.
{
  for (const auto state : stateIndexRange())
    setProps(state).erase(elem);
}
Referenced by MaterialData::eraseProperty(), and FEProblemBase::meshChangedHelper().
getMaterialData()
MaterialData & MaterialPropertyStorage::getMaterialData (const THREAD_ID tid) inline
Returns
The MaterialData for thread tid
Definition at line 301 of file MaterialPropertyStorage.h.
{ return _material_data[tid]; }
Referenced by FEProblemBase::getMaterialData(), ComputeMaterialsObjectThread::onBoundary(), ComputeMaterialsObjectThread::onElement(), ComputeMaterialsObjectThread::onInterface(), ComputeMaterialsObjectThread::onInternalSide(), prolongStatefulProps(), FEProblemBase::reinitMaterials(), FEProblemBase::reinitMaterialsBoundary(), FEProblemBase::reinitMaterialsFace(), FEProblemBase::reinitMaterialsInterface(), FEProblemBase::reinitMaterialsNeighbor(), swap(), swapBack(), FEProblemBase::swapBackMaterials(), FEProblemBase::swapBackMaterialsFace(), FEProblemBase::swapBackMaterialsNeighbor(), and updateStatefulPropsForPRefinement().
getMaterialPropertyRegistry()
const MaterialPropertyRegistry & MaterialPropertyStorage::getMaterialPropertyRegistry () const inline
Definition at line 258 of file MaterialPropertyStorage.h.
{ return _registry; }
Referenced by MaterialData::getPropertyId().
hasOlderProperties()
bool MaterialPropertyStorage::hasOlderProperties () const inline
Returns
a Boolean indicating whether or not this material has older properties declared
Definition at line 221 of file MaterialPropertyStorage.h.
{ return maxState() > 1; }
hasProperty()
bool MaterialPropertyStorage::hasProperty (const std::string & prop_name) const inline
Definition at line 242 of file MaterialPropertyStorage.h.
{ return _registry.hasProperty(prop_name); }
Referenced by MaterialData::hasProperty().
hasStatefulProperties()
bool MaterialPropertyStorage::hasStatefulProperties () const inline
Returns
a Boolean indicating whether stateful properties exist on this material
Definition at line 216 of file MaterialPropertyStorage.h.
{ return maxState() > 0; }
Referenced by FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::advanceState(), FEProblemBase::checkProblemIntegrity(), initStatefulProps(), FEProblemBase::meshChangedHelper(), ProjectMaterialProperties::onBoundary(), shift(), MaterialData::swap(), and MaterialData::swapBack().
initAndSetProps()
MaterialProperties & MaterialPropertyStorage::initAndSetProps (const Elem * elem, const unsigned int side, const unsigned int state) inline private
Returns
A writeable reference to the properties for elem elem, side side, and state state.
Similar to setProps, but will initialize (default construct) the entry if it does not exist.
Definition at line 403 of file MaterialPropertyStorage.h.
{
  return setProps(state)[elem][side];
}
Referenced by swap().
initProps() [1/2]
void MaterialPropertyStorage::initProps (const THREAD_ID tid, const Elem * elem, unsigned int side, unsigned int n_qpoints) private
Initializes hashmap entries for element and side to proper qpoint and property count sizes.
Definition at line 382 of file MaterialPropertyStorage.C.
{
  for (const auto state : stateIndexRange())
    this->initProps(tid, state, elem, side, n_qpoints);
}
Referenced by copy(), initProps(), initStatefulProps(), prolongStatefulProps(), restrictStatefulProps(), and updateStatefulPropsForPRefinement().
initProps() [2/2]
void MaterialPropertyStorage::initProps (const THREAD_ID tid, const unsigned int state, const Elem * elem, unsigned int side, unsigned int n_qpoints) private
Initializes just one hashmap's entries.
Definition at line 392 of file MaterialPropertyStorage.C.
{
  auto & material_data = getMaterialData(tid);
  material_data.resize(n_qpoints);
  auto & mat_props = initAndSetProps(elem, side, state);
  // In some special cases, material_data might be larger than n_qpoints
  if (material_data.isOnlyResizeIfSmaller())
    n_qpoints = material_data.nQPoints();
  const auto n_props = _stateful_prop_id_to_prop_id.size();
  if (mat_props.size() < n_props)
    mat_props.resize(n_props, {});
  // init properties (allocate memory. etc)
  for (const auto i : index_range(_stateful_prop_id_to_prop_id))
    if (!mat_props.hasValue(i))
    {
      const auto prop_id = _stateful_prop_id_to_prop_id[i];
      mat_props.setPointer(i, material_data.props(0)[prop_id].clone(n_qpoints), {});
      mooseAssert(mat_props[i].id() == prop_id, "Inconsistent id");
    }
}
initStatefulProps()
void MaterialPropertyStorage::initStatefulProps (const THREAD_ID tid, const std::vector< std::shared_ptr< MaterialBase > > & mats, const unsigned int n_qpoints, const Elem & elem, const unsigned int side = 0)
Initialize stateful material properties.
Parameters
tid The thread ID
mats Materials that will compute the initial values
n_qpoints Number of quadrature points
elem Element we are on
side Side of the element 'elem' (0 for volumetric material properties)
Definition at line 239 of file MaterialPropertyStorage.C.
{
  // NOTE: since materials are storing their computed properties in MaterialData class, we need to
  // juggle the memory between MaterialData and MaterialProperyStorage classes
  initProps(tid, &elem, side, n_qpoints);
  // copy from storage to material data
  swap(tid, elem, side);
  // run custom init on properties
  for (const auto & mat : mats)
    mat->initStatefulProperties(n_qpoints);
  swapBack(tid, elem, side);
  if (!hasStatefulProperties())
    return;
  // This second call to initProps covers cases where code in
  // "init[Qp]StatefulProperties" may have called a get/declare for a stateful
  // property affecting the _stateful_prop_id_to_prop_id vector among other
  // things.  This is necessary because a call to
  // getMaterialProperty[Old/Older] can potentially trigger a material to
  // become stateful that previously wasn't.  This needs to go after the
  // swapBack.
  initProps(tid, &elem, side, n_qpoints);
  // Copy to older states as needed
  const auto & current_props = props(&elem, side, 0);
  for (const auto state : statefulIndexRange())
  {
    auto & to_props = setProps(&elem, side, state);
    for (const auto i : index_range(_stateful_prop_id_to_prop_id))
      for (const auto qp : make_range(n_qpoints))
        to_props[i].qpCopy(qp, current_props[i], qp);
  }
}
Referenced by ComputeMaterialsObjectThread::onBoundary(), ComputeMaterialsObjectThread::onElement(), ComputeMaterialsObjectThread::onInterface(), and ComputeMaterialsObjectThread::onInternalSide().
isStatefulProp()
bool MaterialPropertyStorage::isStatefulProp (const std::string & prop_name) const inline
Definition at line 260 of file MaterialPropertyStorage.h.
  {
    return _stateful_prop_names.count(_registry.getID(prop_name));
  }
maxState()
unsigned int MaterialPropertyStorage::maxState () const inline
Returns
The current maximum stored state (0 = none, 1 = old, 2 = older)
Definition at line 275 of file MaterialPropertyStorage.h.
  {
    mooseAssert(_max_state < _storage.size(), "Too big");
    return _max_state;
  }
Referenced by addProperty(), hasOlderProperties(), hasStatefulProperties(), numStates(), and shift().
numStates()
unsigned int MaterialPropertyStorage::numStates () const inline
Returns
The number of stored states (2 = up to old, 3 = up to older)
Definition at line 283 of file MaterialPropertyStorage.h.
{ return maxState() + 1; }
Referenced by restrictStatefulProps(), statefulIndexRange(), and stateIndexRange().
prolongStatefulProps()
void MaterialPropertyStorage::prolongStatefulProps (processor_id_type pid, const std::vector< std::vector< QpMap > > & refinement_map, const QBase & qrule, const QBase & qrule_face, MaterialPropertyStorage & parent_material_props, const THREAD_ID tid, const Elem & elem, const int input_parent_side, const int input_child, const int input_child_side)
Creates storage for newly created elements from mesh Adaptivity.
Also, copies values from the parent qps to the new children.
Note - call this on the MaterialPropertyStorage object for the children that you want to project to. ie, if you are trying to project to the sides of the children, then call this on the boundary MaterialPropertyStorage. Pass in the parent MaterialPropertyStorage you are projecting from. ie the volume one if you are projecting to "internal" child element faces.
There are 3 cases here:
Volume to volume (parent_side = -1, child = -1, child_side = -1) Call on volume MaterialPropertyStorage and pass volume MaterialPropertyStorage for parent_material_props
Parent side to child side (parent_side = 0+, child = -1, child_side = 0+) where parent_side == child_side Call on boundary MaterialPropertyStorage and pass boundary MaterialPropertyStorage for parent_material_props
Child side to parent volume (parent_side = -1, child = 0+, child_side = 0+) Call on boundary MaterialPropertyStorage and pass volume MaterialPropertyStorage for parent_material_props
Parameters
pid - processor id of children to prolong to
refinement_map - 2D array of QpMap objects
qrule The current quadrature rule
qrule_face The current face qrule
parent_material_props The place to pull parent material property values from
tid The thread ID
elem The parent element that was just refined
input_parent_side - the side of the parent for which material properties are prolonged
input_child - the number of the child
input_child_side - the side on the child where material properties will be prolonged
Definition at line 115 of file MaterialPropertyStorage.C.
{
  mooseAssert(input_child != -1 || input_parent_side == input_child_side, "Invalid inputs!");
  unsigned int n_qpoints = 0;
  // If we passed in -1 for these then we really need to store properties at 0
  unsigned int parent_side = input_parent_side == -1 ? 0 : input_parent_side;
  unsigned int child_side = input_child_side == -1 ? 0 : input_child_side;
  if (input_child_side == -1) // Not doing side projection (ie, doing volume projection)
    n_qpoints = qrule.n_points();
  else
    n_qpoints = qrule_face.n_points();
  getMaterialData(tid).resize(n_qpoints);
  unsigned int n_children = elem.n_children();
  std::vector<unsigned int> children;
  if (input_child != -1) // Passed in a child explicitly
    children.push_back(input_child);
  else
  {
    children.resize(n_children);
    for (unsigned int child = 0; child < n_children; child++)
      children[child] = child;
  }
  for (const auto & child : children)
  {
    // If we're not projecting an internal child side, but we are projecting sides, see if this
    // child is on that side
    if (input_child == -1 && input_child_side != -1 && !elem.is_child_on_side(child, parent_side))
      continue;
    const Elem * child_elem = elem.child_ptr(child);
    // If it's not a local child then it'll be prolonged where it is
    // local
    if (child_elem->processor_id() != pid)
      continue;
    mooseAssert(child < refinement_map.size(), "Refinement_map vector not initialized");
    const std::vector<QpMap> & child_map = refinement_map[child];
    initProps(tid, child_elem, child_side, n_qpoints);
    for (const auto state : stateIndexRange())
    {
      const auto & parent_props = parent_material_props.props(&elem, parent_side, state);
      auto & child_props = setProps(child_elem, child_side, state);
      for (const auto i : index_range(_stateful_prop_id_to_prop_id))
        for (const auto qp : index_range(refinement_map[child]))
          child_props[i].qpCopy(qp, parent_props[i], child_map[qp]._to);
    }
  }
}
Referenced by ProjectMaterialProperties::onBoundary(), ProjectMaterialProperties::onElement(), and ProjectMaterialProperties::onInternalSide().
props() [1/2]
const MaterialProperties & MaterialPropertyStorage::props (const Elem * elem, unsigned int side, const unsigned int state = 0) const inline
Definition at line 387 of file MaterialPropertyStorage.h.
{
  const auto find_elem = props(state).find(elem);
  mooseAssert(find_elem != props(state).end(), "Material property does not have elem entry");
  const auto find_side = find_elem->second.find(side);
  mooseAssert(find_side != find_elem->second.end(), "Material property does not have side entry");
  return find_side->second;
}
props() [2/2]
const MaterialPropertyStorage::PropsType & MaterialPropertyStorage::props (const unsigned int state = 0) const inline
Access methods to the stored material property data with the given state state.
Definition at line 380 of file MaterialPropertyStorage.h.
{
  mooseAssert(state < _storage.size(), "Invalid material property state " + std::to_string(state));
  return _storage[state];
}
Referenced by copy(), initStatefulProps(), prolongStatefulProps(), props(), restrictStatefulProps(), swap(), swapBack(), and updateStatefulPropsForPRefinement().
restrictStatefulProps()
void MaterialPropertyStorage::restrictStatefulProps (const std::vector< std::pair< unsigned int, QpMap > > & coarsening_map, const std::vector< const Elem * > & coarsened_element_children, const QBase & qrule, const QBase & qrule_face, const THREAD_ID tid, const Elem & elem, int input_side = -1)
Creates storage for newly created elements from mesh Adaptivity.
Also, copies values from the children to the parent.
Parameters
coarsening_map - map from unsigned ints to QpMap's
coarsened_element_children - a pointer to a vector of coarsened element children
qrule The current quadrature rule
qrule_face The current face qrule
tid The thread ID
elem The parent element that was just refined
input_side Side of the element 'elem' (0 for volumetric material properties)
Definition at line 186 of file MaterialPropertyStorage.C.
{
  unsigned int side;
  bool doing_a_side = input_side != -1;
  unsigned int n_qpoints = 0;
  if (!doing_a_side)
  {
    side = 0; // Use 0 for the elem
    n_qpoints = qrule.n_points();
  }
  else
  {
    side = input_side;
    n_qpoints = qrule_face.n_points();
  }
  initProps(tid, &elem, side, n_qpoints);
  std::vector<MaterialProperties *> parent_props(numStates());
  for (const auto state : stateIndexRange())
    parent_props[state] = &setProps(&elem, side, state);
  // Copy from the child stateful properties
  for (const auto qp : index_range(coarsening_map))
  {
    const std::pair<unsigned int, QpMap> & qp_pair = coarsening_map[qp];
    unsigned int child = qp_pair.first;
    mooseAssert(child < coarsened_element_children.size(),
                "Coarsened element children vector not initialized");
    const Elem * child_elem = coarsened_element_children[child];
    const QpMap & qp_map = qp_pair.second;
    for (const auto state : stateIndexRange())
    {
      const auto & child_props = props(child_elem, side, state);
      for (const auto i : index_range(_stateful_prop_id_to_prop_id))
        (*parent_props[state])[i].qpCopy(qp, child_props[i], qp_map._to);
    }
  }
}
Referenced by ProjectMaterialProperties::onBoundary(), and ProjectMaterialProperties::onElement().
setProps() [1/2]
MaterialProperties & MaterialPropertyStorage::setProps (const Elem * elem, unsigned int side, const unsigned int state = 0) inline
Definition at line 397 of file MaterialPropertyStorage.h.
{
  return const_cast<MaterialProperties &>(std::as_const(*this).props(elem, side, state));
}
Referenced by copy(), eraseProperty(), initAndSetProps(), initStatefulProps(), prolongStatefulProps(), restrictStatefulProps(), shift(), swapBack(), and updateStatefulPropsForPRefinement().
setProps() [2/2]
MaterialPropertyStorage::PropsType & MaterialPropertyStorage::setProps (const unsigned int state) inline private
Returns
A writeable reference to the properties at state state.
Definition at line 411 of file MaterialPropertyStorage.h.
{
  return const_cast<MaterialPropertyStorage::PropsType &>(std::as_const(*this).props(state));
}
shallowSwapData()
void MaterialPropertyStorage::shallowSwapData (const std::vector< unsigned int > & stateful_prop_ids, MaterialProperties & data, MaterialProperties & data_from) static private
Shallow copies of material properties.
Definition at line 30 of file MaterialPropertyStorage.C.
{
  for (const auto i : make_range(std::min(stateful_prop_ids.size(), data_from.size())))
    if (stateful_prop_ids[i] < data.size() && data.hasValue(stateful_prop_ids[i]) &&
        data_from.hasValue(i))
    {
      auto & prop = data[stateful_prop_ids[i]];
      auto & prop_from = data_from[i];
      prop.swap(prop_from);
    }
}
Referenced by swap().
shallowSwapDataBack()
void MaterialPropertyStorage::shallowSwapDataBack (const std::vector< unsigned int > & stateful_prop_ids, MaterialProperties & data, MaterialProperties & data_from) static private
Definition at line 45 of file MaterialPropertyStorage.C.
{
  for (const auto i : make_range(std::min(stateful_prop_ids.size(), data.size())))
    if (stateful_prop_ids[i] < data_from.size() && data.hasValue(i) &&
        data_from.hasValue(stateful_prop_ids[i]))
    {
      auto & prop = data[i];
      auto & prop_from = data_from[stateful_prop_ids[i]];
      prop.swap(prop_from);
    }
}
Referenced by swapBack().
shift()
void MaterialPropertyStorage::shift ()
Shift the material properties in time.
Old material properties become older, current material properties become old. Older material properties are reused for computing current properties. This is called when solve succeeded.
Shift properties back in time and reuse older data for current (save reallocations etc.) With current, old, and older this can be accomplished by two swaps: older <-> old old <-> current
Definition at line 282 of file MaterialPropertyStorage.C.
{
  mooseAssert(hasStatefulProperties(), "Doesn't have stateful props");
  for (unsigned int state = maxState(); state != 0; state--)
    std::swap(setProps(state), setProps(state - 1));
}
Referenced by FEProblemBase::advanceState().
sizeProps()
void MaterialPropertyStorage::sizeProps (MaterialProperties & mp, unsigned int size) protected
statefulIndexRange()
IntRange< unsigned int > MaterialPropertyStorage::statefulIndexRange () const inline
Returns
A range over stateful states to be used in range-based for loops
Will be an empty range if there are no stateful states
Definition at line 293 of file MaterialPropertyStorage.h.
  {
    return IntRange<unsigned int>(1, numStates());
  }
Referenced by initStatefulProps().
statefulPropNames()
const std::unordered_map< unsigned int, std::string > & MaterialPropertyStorage::statefulPropNames () const inline
Definition at line 253 of file MaterialPropertyStorage.h.
  {
    return _stateful_prop_names;
  }
Referenced by FEProblemBase::checkDependMaterialsHelper().
statefulProps()
const std::vector< unsigned int > & MaterialPropertyStorage::statefulProps () const inline
Definition at line 252 of file MaterialPropertyStorage.h.
{ return _stateful_prop_id_to_prop_id; }
stateIndexRange()
IntRange< unsigned int > MaterialPropertyStorage::stateIndexRange () const inline
Returns
A range over states to be used in range-based for loops
Definition at line 287 of file MaterialPropertyStorage.h.
{ return IntRange<unsigned int>(0, numStates()); }
Referenced by copy(), eraseProperty(), initProps(), prolongStatefulProps(), MaterialData::resize(), restrictStatefulProps(), swap(), swapBack(), and updateStatefulPropsForPRefinement().
swap()
void MaterialPropertyStorage::swap (const THREAD_ID tid, const Elem & elem, unsigned int side)
Swap (shallow copy) material properties in MaterialData and MaterialPropertyStorage Thread safe.
Parameters
tid The thread id
elem Element id
side Side number (elemental material properties have this equal to zero)
Definition at line 326 of file MaterialPropertyStorage.C.
{
  Threads::spin_mutex::scoped_lock lock(this->_spin_mtx);
  for (const auto state : stateIndexRange())
    shallowSwapData(_stateful_prop_id_to_prop_id,
                    getMaterialData(tid).props(state),
                    // Would be nice to make this setProps()
                    initAndSetProps(&elem, side, state));
}
Referenced by initStatefulProps(), and MaterialData::swap().
swapBack()
void MaterialPropertyStorage::swapBack (const THREAD_ID tid, const Elem & elem, unsigned int side)
Swap (shallow copy) material properties in MaterialPropertyStorage and MaterialDat Thread safe.
Parameters
tid The thread id
elem Element id
side Side number (elemental material properties have this equal to zero)
Definition at line 338 of file MaterialPropertyStorage.C.
{
  Threads::spin_mutex::scoped_lock lock(this->_spin_mtx);
  for (const auto state : stateIndexRange())
    shallowSwapDataBack(_stateful_prop_id_to_prop_id,
                        setProps(&elem, side, state),
                        getMaterialData(tid).props(state));
  // Workaround for MOOSE difficulties in keeping materialless
  // elements (e.g. Lower D elements in Mortar code) materials
  for (const auto state : stateIndexRange())
    if (props(&elem, side, state).empty())
      setProps(state)[&elem].erase(side);
}
Referenced by initStatefulProps(), and MaterialData::swapBack().
updateStatefulPropsForPRefinement()
void MaterialPropertyStorage::updateStatefulPropsForPRefinement (const processor_id_type pid, const std::vector< QpMap > & p_refinement_map, const QBase & qrule, const QBase & qrule_face, const THREAD_ID tid, const Elem & elem, const int input_side)
Based on the p-refinement flag of elem, either prolong (for refinement) or restrict (for coarsening) the stateful material property data.
Parameters
pid The rank returned by the mesh. This is used to assert that we are only prolonging/restricting for elements that our process owns
p_refinement_map A map that describes, for each quadrature point on the current level which quadrature point on the previous level it is closest to
qrule The volumetric quadrature rule
qrule_face The face quadrature rule
tid The thread ID
elem The element that was just p-refined or coarsened that we are performing material property prolongation/restriction for
input_side Which element side we are performing material property prolongation/restriction for. Pass in -1 for doing volumetric prolongation/restriction
Definition at line 67 of file MaterialPropertyStorage.C.
{
  unsigned int n_qpoints = 0;
  // If we passed in -1 for these then we really need to store properties at 0
  unsigned int side = input_side == -1 ? 0 : input_side;
  if (input_side == -1) // Not doing side projection (ie, doing volume projection)
    n_qpoints = qrule.n_points();
  else
    n_qpoints = qrule_face.n_points();
  getMaterialData(tid).resize(n_qpoints);
  mooseAssert(elem.active(), "We should be doing p-refinement on active elements only");
  mooseAssert(elem.processor_id() == pid, "Prolongation should be occurring locally");
  mooseAssert(p_refinement_map.size() == n_qpoints, "Refinement map not proper size");
  initProps(tid, &elem, side, n_qpoints);
  for (const auto state : stateIndexRange())
  {
    auto & props = setProps(&elem, side, state);
    for (const auto i : index_range(_stateful_prop_id_to_prop_id))
    {
      auto & current_p_level_prop = props[i];
      // We need to clone this property in order to not overwrite the values we're going to be
      // reading from
      auto previous_p_level_prop = current_p_level_prop.clone(current_p_level_prop.size());
      // Cloning, despite its name, does not copy the data. Luckily since we are about to overwrite
      // all of the current_p_level_prop data, we can just swap its data over to our
      // previous_p_level_prop
      previous_p_level_prop->swap(current_p_level_prop);
      current_p_level_prop.resize(n_qpoints);
      for (const auto qp : index_range(p_refinement_map))
        current_p_level_prop.qpCopy(qp, *previous_p_level_prop, p_refinement_map[qp]._to);
    }
  }
}
Referenced by ProjectMaterialProperties::onBoundary(), and ProjectMaterialProperties::onElement().
Friends And Related Function Documentation
dataLoad
void dataLoad (std::istream & , MaterialPropertyStorage & , void *) friend
Definition at line 476 of file MaterialPropertyStorage.C.
{
  const auto & registry = storage.getMaterialPropertyRegistry();
  decltype(storage.numStates()) num_states;
  dataLoad(stream, num_states, nullptr);
  if (num_states != storage.numStates())
    mooseError("Stateful material properties up to state ",
               num_states,
               " were stored in checkpoint/backup,\nbut state ",
               storage.numStates(),
               " is now the maximum state requested.\n\nThis mismatch is not currently supported.");
  std::vector<std::string> from_prop_ids_to_names;
  dataLoad(stream, from_prop_ids_to_names, nullptr);
  decltype(storage._stateful_prop_id_to_prop_id) from_stateful_prop_id_to_prop_id;
  dataLoad(stream, from_stateful_prop_id_to_prop_id, nullptr);
  decltype(storage._stateful_prop_names) from_stateful_prop_names;
  dataLoad(stream, from_stateful_prop_names, nullptr);
  {
    const auto fill_names = [](const auto & from)
    {
      std::set<std::string> names;
      for (const auto & id_name_pair : from)
        names.insert(id_name_pair.second);
      return names;
    };
    const auto from_names = fill_names(from_stateful_prop_names);
    const auto to_names = fill_names(storage.statefulPropNames());
    // This requirement currently comes from the fact that now when we do restart/recover,
    // we do not call initStatefulQpProperties() anymore on each material. Which means that
    // if you add more stateful properties, they would never be initialized. It seems like
    // this capability (adding props) isn't currently used, so we're going to make it an
    // error for now. There are plenty of ways around this, but the priority at the moment
    // is enabling more flexible restart/recover, and this is one of the costs.
    // TODO: check types
    if (from_names != to_names)
    {
      std::stringstream err;
      err << "There is a mismatch in the stateful material properties stored during "
             "checkpoint/backup and declared in restart/recover.\n"
          << "The current system requires that the stateful properties be equivalent.\n\n";
      auto add_props = [&err](const auto & names)
      {
        for (const auto & name : names)
          err << "  " << name << "\n";
      };
      err << "Stored stateful properties:\n";
      add_props(from_names);
      err << "\nDeclared stateful properties:\n";
      add_props(to_names);
      mooseError(err.str());
    }
  }
  std::vector<std::optional<unsigned int>> to_stateful_ids(storage.statefulProps().size());
  // Fill the mapping from previous ID to current stateful ID
  for (const auto from_stateful_id : index_range(from_stateful_prop_id_to_prop_id))
  {
    const auto from_prop_id = from_stateful_prop_id_to_prop_id[from_stateful_id];
    mooseAssert(from_prop_id < from_prop_ids_to_names.size(), "Invalid ID map");
    const auto & from_name = from_prop_ids_to_names[from_prop_id];
    const auto to_prop_id = registry.getID(from_name);
    const auto find_prop_id = std::find(storage._stateful_prop_id_to_prop_id.begin(),
                                        storage._stateful_prop_id_to_prop_id.end(),
                                        to_prop_id);
    mooseAssert(find_prop_id != storage._stateful_prop_id_to_prop_id.end(), "Not found");
    const std::size_t to_stateful_id =
        std::distance(storage._stateful_prop_id_to_prop_id.begin(), find_prop_id);
    to_stateful_ids[from_stateful_id] = to_stateful_id;
  }
  // Load the properties
  for (const auto state : storage.stateIndexRange())
  {
    std::size_t num_elems;
    dataLoad(stream, num_elems, nullptr);
    for (std::size_t i_elem = 0; i_elem < num_elems; ++i_elem)
    {
      const Elem * elem;
      dataLoad(stream, elem, context);
      mooseAssert(elem, "Null element");
      std::size_t num_sides;
      dataLoad(stream, num_sides, nullptr);
      for (std::size_t i_side = 0; i_side < num_sides; ++i_side)
      {
        unsigned int side;
        dataLoad(stream, side, nullptr);
        std::size_t num_props;
        dataLoad(stream, num_props, nullptr);
        std::size_t num_q_points;
        dataLoad(stream, num_q_points, nullptr);
        storage.initProps(0, state, elem, side, num_q_points);
        auto & props = storage.setProps(elem, side, state);
        for (const auto from_stateful_id : make_range(num_props))
        {
          const auto to_stateful_id = to_stateful_ids[from_stateful_id];
          mooseAssert(to_stateful_id, "Skipping not supported");
          // Eventually we should support skipping, and this will be how it's done
          // if (!to_stateful_id)
          //   dataLoadSkip(stream);
          // else
          dataLoadSkippable(stream, props[*to_stateful_id], nullptr);
        }
      }
    }
  }
}
dataStore
void dataStore (std::ostream & , MaterialPropertyStorage & , void *) friend
Definition at line 422 of file MaterialPropertyStorage.C.
{
  const auto num_states = storage.numStates();
  dataStore(stream, num_states, nullptr);
  // Store the material property ID -> name map for mapping back
  const auto & registry = storage.getMaterialPropertyRegistry();
  std::vector<std::string> ids_to_names(registry.idsToNamesBegin(), registry.idsToNamesEnd());
  dataStore(stream, ids_to_names, nullptr);
  // Store the stateful ID -> property ID map for mapping back
  dataStore(stream, storage._stateful_prop_id_to_prop_id, nullptr);
  // Store the stateful id -> name map
  dataStore(stream, storage._stateful_prop_names, nullptr);
  // Store every property
  for (const auto state : storage.stateIndexRange())
  {
    std::size_t num_elems = storage.setProps(state).size();
    dataStore(stream, num_elems, nullptr);
    for (auto & elem_side_map_pair : storage.setProps(state))
    {
      const Elem * elem = elem_side_map_pair.first;
      mooseAssert(elem, "Null element");
      dataStore(stream, elem, context);
      auto & side_map = elem_side_map_pair.second;
      std::size_t num_sides = side_map.size();
      dataStore(stream, num_sides, nullptr);
      for (auto & [side, props] : side_map)
      {
        dataStore(stream, side, nullptr);
        std::size_t num_props = props.size();
        dataStore(stream, num_props, nullptr);
        mooseAssert(num_props > 0, "No properties");
        std::size_t n_q_points = 0;
        for (const auto & entry : props)
          if (entry.size() > n_q_points)
            n_q_points = entry.size();
        dataStore(stream, n_q_points, nullptr);
        for (auto & entry : props)
          dataStoreSkippable(stream, entry, nullptr);
      }
    }
  }
}
ProjectMaterialProperties
friend class ProjectMaterialProperties friend
Definition at line 369 of file MaterialPropertyStorage.h.
RedistributeProperties
friend class RedistributeProperties friend
Definition at line 372 of file MaterialPropertyStorage.h.
Member Data Documentation
_material_data
std::vector<MaterialData> MaterialPropertyStorage::_material_data private
The threaded material data.
Definition at line 366 of file MaterialPropertyStorage.h.
Referenced by getMaterialData(), and MaterialPropertyStorage().
_max_state
unsigned int MaterialPropertyStorage::_max_state private
The maximum state (0 = current, 1 = old, 2 = older)
Definition at line 355 of file MaterialPropertyStorage.h.
Referenced by addProperty(), and maxState().
_registry
MaterialPropertyRegistry& MaterialPropertyStorage::_registry private
Shared registry (across storage objects) for property names and IDs.
Definition at line 363 of file MaterialPropertyStorage.h.
Referenced by addProperty(), getMaterialPropertyRegistry(), hasProperty(), and isStatefulProp().
_spin_mtx
libMesh::Threads::spin_mutex& MaterialPropertyStorage::_spin_mtx private
Definition at line 360 of file MaterialPropertyStorage.h.
Referenced by swap(), and swapBack().
_stateful_prop_id_to_prop_id
std::vector<unsigned int> MaterialPropertyStorage::_stateful_prop_id_to_prop_id protected
the vector of stateful property ids (the vector index is the map to stateful prop_id)
Definition at line 310 of file MaterialPropertyStorage.h.
Referenced by addProperty(), copy(), initStatefulProps(), prolongStatefulProps(), restrictStatefulProps(), statefulProps(), swap(), swapBack(), and updateStatefulPropsForPRefinement().
_stateful_prop_names
std::unordered_map<unsigned int, std::string> MaterialPropertyStorage::_stateful_prop_names protected
Mapping from stateful property ID to property name.
Definition at line 308 of file MaterialPropertyStorage.h.
Referenced by addProperty(), isStatefulProp(), and statefulPropNames().
_storage
std::array<PropsType, MaterialData::max_state + 1> MaterialPropertyStorage::_storage protected
The actual storage.
Definition at line 305 of file MaterialPropertyStorage.h.
Referenced by maxState(), and props().
The documentation for this class was generated from the following files:
moose/framework/include/materials/MaterialPropertyStorage.h
moose/framework/src/materials/MaterialPropertyStorage.C