Zapdos: SyntaxTree Class Reference
SyntaxTree Class Reference abstract
#include <SyntaxTree.h>
Classes
class TreeNode
This class represents a single node in our tree.
Public Member Functions
SyntaxTree (bool use_long_names=false)
virtual ~SyntaxTree ()
void insertNode (std::string syntax, const std::string &action, bool is_action_params=true, InputParameters *params=NULL)
std::string print (const std::string &search_string)
void seenIt (const std::string &prefix, const std::string &item)
bool haveSeenIt (const std::string &prefix, const std::string &item) const
virtual std::string preamble () const
This method is called once at the beginning of the tree traversal and can be used to build up header information.
virtual std::string postscript () const
This method is called once at the end of the tree traversal and can be used to add any necessary trailing information to the final formatted string.
virtual std::string preTraverse (short) const
This method is called once at each node in the syntax tree before traversing child nodes.
virtual std::string printBlockOpen (const std::string &name, short depth, const std::string &doc)=0
This method is called at the beginning of each Node in the tree.
virtual std::string printBlockClose (const std::string &name, short depth) const =0
This method is called at the end of of each Node in the tree.
virtual std::string printParams (const std::string &prefix, const std::string &fully_qualified_name, InputParameters &params, short depth, const std::string &search_string, bool &found)=0
This function is called for each InputParameters object stored at a particular node.
Protected Member Functions
bool isLongNames () const
Protected Attributes
std::unique_ptr< TreeNode > _root
bool _use_long_names
Private Attributes
std::set< std::string > _params_printed
Detailed Description
Definition at line 23 of file SyntaxTree.h.
Constructor & Destructor Documentation
SyntaxTree()
SyntaxTree::SyntaxTree (bool use_long_names = false)
Definition at line 19 of file SyntaxTree.C.
  : SyntaxFormatterInterface(), _use_long_names(use_long_names)
{
}
~SyntaxTree()
SyntaxTree::~SyntaxTree () virtual default
Member Function Documentation
haveSeenIt()
bool SyntaxTree::haveSeenIt (const std::string & prefix, const std::string & item) const
Definition at line 63 of file SyntaxTree.C.
{
  return _params_printed.find(prefix + item) != _params_printed.end();
}
Referenced by InputFileFormatter::printParams(), and YAMLFormatter::printParams().
insertNode()
void SyntaxTree::insertNode (std::string syntax, const std::string & action, bool is_action_params = true, InputParameters * params = NULL)
Definition at line 27 of file SyntaxTree.C.
{
  if (!_root)
    _root = std::make_unique<TreeNode>("", *this);
  _root->insertNode(syntax, action, is_action_params, params);
}
Referenced by ActionWarehouse::printInputFile().
isLongNames()
bool SyntaxTree::isLongNames () const protected
Definition at line 227 of file SyntaxTree.C.
{
  return _use_long_names;
}
postscript()
virtual std::string SyntaxFormatterInterface::postscript () const inline virtual inherited
This method is called once at the end of the tree traversal and can be used to add any necessary trailing information to the final formatted string.
Returns
- The formatted postscript string
Reimplemented in YAMLFormatter.
Definition at line 41 of file SyntaxFormatterInterface.h.
{ return std::string(); }
Referenced by print().
preamble()
virtual std::string SyntaxFormatterInterface::preamble () const inline virtual inherited
This method is called once at the beginning of the tree traversal and can be used to build up header information.
Returns
- The formatted preamble string
Reimplemented in YAMLFormatter.
Definition at line 33 of file SyntaxFormatterInterface.h.
{ return std::string(); }
Referenced by print().
preTraverse()
virtual std::string SyntaxFormatterInterface::preTraverse (short) const inline virtual inherited
This method is called once at each node in the syntax tree before traversing child nodes.
Returns
- The formatted pre-node traversal string
Reimplemented in YAMLFormatter.
Definition at line 47 of file SyntaxFormatterInterface.h.
{ return std::string(); }
print()
std::string SyntaxTree::print (const std::string & search_string)
Definition at line 39 of file SyntaxTree.C.
{
  bool found = false;
  std::string output;
  // Clear the list of "seen" parameters before printing the tree
  _params_printed.clear();
  if (_root)
    output = _root->print(-1, search_string, found);
  if (found)
    return preamble() + output + postscript();
  else
    return "";
}
Referenced by ActionWarehouse::printInputFile().
printBlockClose()
virtual std::string SyntaxFormatterInterface::printBlockClose (const std::string & name, short depth) const pure virtual inherited
This method is called at the end of of each Node in the tree.
It is typically used to provide formatting necessary when closing blocks.
Returns
- The formatted block close string
Implemented in InputFileFormatter, and YAMLFormatter.
printBlockOpen()
virtual std::string SyntaxFormatterInterface::printBlockOpen (const std::string & name, short depth, const std::string & doc) pure virtual inherited
This method is called at the beginning of each Node in the tree.
It is typically used to provide formatting necessary when opening new blocks.
Returns
- The formatted block open string
Implemented in InputFileFormatter, and YAMLFormatter.
printParams()
virtual std::string SyntaxFormatterInterface::printParams (const std::string & prefix, const std::string & fully_qualified_name, InputParameters & params, short depth, const std::string & search_string, bool & found) pure virtual inherited
This function is called for each InputParameters object stored at a particular node.
It is responsible for formatting the parameters for the current node.
Returns
- The formatted parameters string for a Node.
Implemented in InputFileFormatter, and YAMLFormatter.
seenIt()
void SyntaxTree::seenIt (const std::string & prefix, const std::string & item)
Definition at line 57 of file SyntaxTree.C.
{
  _params_printed.insert(prefix + item);
}
Referenced by InputFileFormatter::printParams(), and YAMLFormatter::printParams().
Member Data Documentation
_params_printed
std::set<std::string> SyntaxTree::_params_printed private
Definition at line 80 of file SyntaxTree.h.
Referenced by haveSeenIt(), print(), and seenIt().
_root
std::unique_ptr<TreeNode> SyntaxTree::_root protected
Definition at line 76 of file SyntaxTree.h.
Referenced by insertNode(), and print().
_use_long_names
bool SyntaxTree::_use_long_names protected
Definition at line 77 of file SyntaxTree.h.
Referenced by isLongNames().
The documentation for this class was generated from the following files:
moose/framework/include/utils/SyntaxTree.h
moose/framework/src/utils/SyntaxTree.C