Zapdos: RestartableData< T > Class Template Reference
RestartableData< T > Class Template Reference
Concrete definition of a parameter value for a specified type.
#include <RestartableData.h>
Public Member Functions
template<typename... Params>
RestartableData (const std::string &name, void *const context, Params &&... args)
Constructor.
const T & get () const
T & set ()
void reset ()
Resets (destructs) the underlying data.
virtual std::string type () const override final
String identifying the type of parameter stored.
virtual const std::type_info & typeId () const override final
The type ID of the underlying data.
virtual bool hasStoreJSON () const override final
const std::string & name () const
The full (unique) name of this particular piece of data.
void * context ()
A context pointer for helping with load / store.
bool hasContext () const
bool declared () const
Whether or not this data has been declared.
void setDeclared (const SetDeclaredKey)
Sets that this restartable value has been declared.
bool loaded () const
Whether or not this data has been loaded.
void setNotLoaded (const SetNotLoadedKey)
Sets that this restartable value has been loaded.
bool stored () const
Whether or not this data has been loaded.
void setNotStored (const SetNotStoredKey)
Sets that this restartable value has been loaded.
void store (std::ostream &stream)
Stores the value into the stream stream and sets it as stored.
void store (nlohmann::json &json, const StoreJSONParams &params=StoreJSONParams{}) const
Stores this restartable data in the JSON entry json, with the options set by params (optional; defaults to just the type and underlying value)
void load (std::istream &stream)
Loads the value from the stream stream and sets it as loaded.
Static Public Attributes
static constexpr bool has_store_json = std::is_constructible_v<nlohmann::json, T>
Whether or not this type has a JSON store method implemented.
Protected Member Functions
virtual void storeInternal (std::ostream &stream) override
Store the RestartableData into a binary stream.
virtual void loadInternal (std::istream &stream) override
Load the RestartableData from a binary stream.
virtual void storeJSONValue (nlohmann::json &json) const override final
Internal method for storing the underlying JSON value.
Protected Attributes
const std::string _name
The full (unique) name of this particular piece of data.
void *const _context
A context pointer for helping with load and store.
Private Attributes
std::unique_ptr< T > _value
Stored value.
bool _declared
Whether or not this data has been declared (true) or only retreived (false)
bool _loaded
Whether or not this has value has been loaded.
bool _stored
Whether or not this has value has been stored.
Detailed Description
template<typename T>
class RestartableData< T >
Concrete definition of a parameter value for a specified type.
Definition at line 215 of file RestartableData.h.
Constructor & Destructor Documentation
RestartableData()
template<typename T > template<typename... Params> RestartableData< T >::RestartableData (const std::string & name, void *const context, Params &&... args) inline
Constructor.
Parameters
name The full (unique) name for this piece of data.
context 'typeless' pointer to user-specific data.
arg Forwarded arguments that are passed to the constructor of the data.
Definition at line 228 of file RestartableData.h.
    : RestartableDataValue(name, context),
      _value(std::make_unique<T>(std::forward<Params>(args)...))
  {
  }
Member Function Documentation
context()
void * RestartableDataValue::context () inline inherited
A context pointer for helping with load / store.
Definition at line 65 of file RestartableData.h.
{ return _context; }
declared()
bool RestartableDataValue::declared () const inline inherited
Whether or not this data has been declared.
Definition at line 85 of file RestartableData.h.
{ return _declared; }
Referenced by RestartableDataValue::store().
get()
template<typename T > const T & RestartableData< T >::get inline
Returns
a read-only reference to the parameter value.
Definition at line 280 of file RestartableData.h.
{
  mooseAssert(_value, "Not valid");
  return *_value;
}
Referenced by MeshMetaDataInterface::getMeshProperty().
hasContext()
bool RestartableDataValue::hasContext () const inline inherited
Returns
Whether or not the data has context set.
Definition at line 70 of file RestartableData.h.
{ return _context != nullptr; }
Referenced by RestartableDataValue::store().
hasStoreJSON()
template<typename T > virtual bool RestartableData< T >::hasStoreJSON () const inline final override virtual
Returns
Whether or not this value supports storing JSON via store
Implements RestartableDataValue.
Definition at line 256 of file RestartableData.h.
{ return has_store_json; }
load()
void RestartableDataValue::load (std::istream & stream) inherited
Loads the value from the stream stream and sets it as loaded.
Definition at line 32 of file RestartableData.C.
{
  loadInternal(stream);
  _loaded = true;
}
loaded()
bool RestartableDataValue::loaded () const inline inherited
Whether or not this data has been loaded.
This is typically reset on a call to RestartableDataReader::restore()
Definition at line 98 of file RestartableData.h.
{ return _loaded; }
Referenced by RestartableDataValue::store().
loadInternal()
template<typename T > void RestartableData< T >::loadInternal (std::istream & stream) inline override protected virtual
Load the RestartableData from a binary stream.
Implements RestartableDataValue.
Reimplemented in ReporterState< T >, and ReporterState< std::vector< T > >.
Definition at line 318 of file RestartableData.h.
{
  loadHelper(stream, set(), _context);
}
name()
const std::string & RestartableDataValue::name () const inline inherited
The full (unique) name of this particular piece of data.
Definition at line 60 of file RestartableData.h.
{ return _name; }
Referenced by RestartableDataMap::addData(), RestartableDataMap::findData(), and RestartableDataValue::store().
reset()
template<typename T > void RestartableData< T >::reset inline
Resets (destructs) the underlying data.
Definition at line 296 of file RestartableData.h.
{
  mooseAssert(_value, "Not valid"); // shouldn't really call this twice
  _value.reset();
}
set()
template<typename T > T & RestartableData< T >::set inline
Returns
a writable reference to the parameter value.
Definition at line 288 of file RestartableData.h.
{
  mooseAssert(_value, "Not valid");
  return *_value;
}
Referenced by MeshGenerator::declareMeshProperty(), and MeshGenerator::setMeshProperty().
setDeclared()
void RestartableDataValue::setDeclared (const SetDeclaredKey) inherited
Sets that this restartable value has been declared.
Definition at line 18 of file RestartableData.C.
{
  mooseAssert(!_declared, "Already declared");
  _declared = true;
}
Referenced by MooseApp::registerRestartableData().
setNotLoaded()
void RestartableDataValue::setNotLoaded (const SetNotLoadedKey) inline inherited
Sets that this restartable value has been loaded.
Definition at line 113 of file RestartableData.h.
{ _loaded = false; }
setNotStored()
void RestartableDataValue::setNotStored (const SetNotStoredKey) inline inherited
Sets that this restartable value has been loaded.
Definition at line 136 of file RestartableData.h.
{ _stored = false; }
store() [1/2]
void RestartableDataValue::store (nlohmann::json & json, const StoreJSONParams & params = StoreJSONParams{}) const inherited
Stores this restartable data in the JSON entry json, with the options set by params (optional; defaults to just the type and underlying value)
If the underlying type is not supported for JSON output (if hasStoreJSON() == false), and the parameters have the value output as enabled, this will error.
Definition at line 39 of file RestartableData.C.
{
  if (params.value)
  {
    if (hasStoreJSON())
      storeJSONValue(json["value"]);
    else
      mooseError("Failed to output restartable data '",
                 name(),
                 "' as JSON because a to_json method is not implemented for the type '",
                 type(),
                 "'");
  }
  if (params.type)
    json["type"] = type();
  if (params.name)
    json["name"] = name();
  if (params.declared)
    json["declared"] = declared();
  if (params.loaded)
    json["loaded"] = loaded();
  if (params.stored)
    json["stored"] = stored();
  if (params.has_context)
    json["has_context"] = hasContext();
}
store() [2/2]
void RestartableDataValue::store (std::ostream & stream) inherited
Stores the value into the stream stream and sets it as stored.
Definition at line 25 of file RestartableData.C.
{
  storeInternal(stream);
  _stored = true;
}
stored()
bool RestartableDataValue::stored () const inline inherited
Whether or not this data has been loaded.
This is typically reset on a call to RestartableDataWriter::write()
Definition at line 121 of file RestartableData.h.
{ return _stored; }
Referenced by RestartableDataValue::store().
storeInternal()
template<typename T > void RestartableData< T >::storeInternal (std::ostream & stream) inline override protected virtual
Store the RestartableData into a binary stream.
Implements RestartableDataValue.
Reimplemented in ReporterState< T >, and ReporterState< std::vector< T > >.
Definition at line 311 of file RestartableData.h.
{
  storeHelper(stream, set(), _context);
}
storeJSONValue()
template<typename T > void RestartableData< T >::storeJSONValue (nlohmann::json & json) const inline final override protected virtual
Internal method for storing the underlying JSON value.
Implements RestartableDataValue.
Definition at line 325 of file RestartableData.h.
{
  if constexpr (RestartableData<T>::has_store_json)
    nlohmann::to_json(json, get());
  else
    mooseAssert(false, "Should not be called");
}
type()
template<typename T > std::string RestartableData< T >::type inline final override virtual
String identifying the type of parameter stored.
Implements RestartableDataValue.
Definition at line 304 of file RestartableData.h.
{
  return MooseUtils::prettyCppType<T>();
}
typeId()
template<typename T > virtual const std::type_info & RestartableData< T >::typeId () const inline final override virtual
The type ID of the underlying data.
Implements RestartableDataValue.
Definition at line 254 of file RestartableData.h.
{ return typeid(T); }
Member Data Documentation
_context
void* const RestartableDataValue::_context protected inherited
A context pointer for helping with load and store.
Definition at line 197 of file RestartableData.h.
Referenced by RestartableDataValue::context(), and RestartableDataValue::hasContext().
_declared
bool RestartableDataValue::_declared private inherited
Whether or not this data has been declared (true) or only retreived (false)
Definition at line 201 of file RestartableData.h.
Referenced by RestartableDataValue::declared(), and RestartableDataValue::setDeclared().
_loaded
bool RestartableDataValue::_loaded private inherited
Whether or not this has value has been loaded.
Definition at line 204 of file RestartableData.h.
Referenced by RestartableDataValue::load(), RestartableDataValue::loaded(), and RestartableDataValue::setNotLoaded().
_name
const std::string RestartableDataValue::_name protected inherited
The full (unique) name of this particular piece of data.
Definition at line 194 of file RestartableData.h.
Referenced by RestartableDataValue::name().
_stored
bool RestartableDataValue::_stored private inherited
Whether or not this has value has been stored.
Definition at line 207 of file RestartableData.h.
Referenced by RestartableDataValue::setNotStored(), RestartableDataValue::store(), and RestartableDataValue::stored().
_value
template<typename T > std::unique_ptr<T> RestartableData< T >::_value private
Stored value.
Definition at line 273 of file RestartableData.h.
has_store_json
template<typename T > constexpr bool RestartableData< T >::has_store_json = std::is_constructible_v<nlohmann::json, T> static constexpr
Whether or not this type has a JSON store method implemented.
Definition at line 219 of file RestartableData.h.
Referenced by RestartableData< T >::hasStoreJSON().
The documentation for this class was generated from the following file:
moose/framework/include/restart/RestartableData.h