Zapdos: RandomInterface Class Reference
RandomInterface Class Reference
Interface for objects that need parallel consistent random numbers without patterns over the course of multiple runs.
#include <RandomInterface.h>
Public Member Functions
RandomInterface (const InputParameters &parameters, FEProblemBase &problem, THREAD_ID tid, bool is_nodal)
~RandomInterface ()
void setRandomResetFrequency (ExecFlagType exec_flag)
This interface should be called from a derived class to enable random number generation in this object.
unsigned long getRandomLong () const
Returns the next random number (long) from the generator tied to this object (elem/node).
Real getRandomReal () const
Returns the next random number (Real) from the generator tied to this object (elem/node).
unsigned int getSeed (std::size_t id)
Get the seed for the passed in elem/node id.
unsigned int getMasterSeed () const
bool isNodal () const
ExecFlagType getResetOnTime () const
void setRandomDataPointer (RandomData *random_data)
Static Public Member Functions
static InputParameters validParams ()
Private Attributes
RandomData * _random_data
MooseRandom * _generator
FEProblemBase & _ri_problem
const std::string _ri_name
unsigned int _master_seed
bool _is_nodal
ExecFlagType _reset_on
const Node *const & _curr_node
const Elem *const & _curr_element
Detailed Description
Interface for objects that need parallel consistent random numbers without patterns over the course of multiple runs.
Definition at line 28 of file RandomInterface.h.
Constructor & Destructor Documentation
RandomInterface()
RandomInterface::RandomInterface (const InputParameters & parameters, FEProblemBase & problem, THREAD_ID tid, bool is_nodal)
Definition at line 28 of file RandomInterface.C.
  : _random_data(nullptr),
    _generator(nullptr),
    _ri_problem(problem),
    _ri_name(parameters.get<std::string>("_object_name")),
    _master_seed(parameters.get<unsigned int>("seed")),
    _is_nodal(is_nodal),
    _reset_on(EXEC_LINEAR),
    _curr_node(problem.assembly(tid, 0).node()),
    _curr_element(problem.assembly(tid, 0).elem())
{
}
~RandomInterface()
RandomInterface::~RandomInterface ()
Definition at line 44 of file RandomInterface.C.
{}
Member Function Documentation
getMasterSeed()
unsigned int RandomInterface::getMasterSeed () const inline
Definition at line 66 of file RandomInterface.h.
{ return _master_seed; }
getRandomLong()
unsigned long RandomInterface::getRandomLong () const
Returns the next random number (long) from the generator tied to this object (elem/node).
Definition at line 69 of file RandomInterface.C.
{
  mooseAssert(_generator, "Random Generator is NULL, did you call setRandomResetFrequency()?");
  dof_id_type id;
  if (_is_nodal)
    id = _curr_node->id();
  else
    id = _curr_element->id();
  return _generator->randl(id);
}
getRandomReal()
Real RandomInterface::getRandomReal () const
Returns the next random number (Real) from the generator tied to this object (elem/node).
Definition at line 83 of file RandomInterface.C.
{
  mooseAssert(_generator, "Random Generator is NULL, did you call setRandomResetFrequency()?");
  dof_id_type id;
  if (_is_nodal)
    id = _curr_node->id();
  else
    id = _curr_element->id();
  return _generator->rand(id);
}
getResetOnTime()
ExecFlagType RandomInterface::getResetOnTime () const inline
Definition at line 68 of file RandomInterface.h.
{ return _reset_on; }
getSeed()
unsigned int RandomInterface::getSeed (std::size_t id)
Get the seed for the passed in elem/node id.
Parameters
id - dof object id
Returns
current seed for this id
Definition at line 61 of file RandomInterface.C.
{
  mooseAssert(_random_data, "RandomData object is NULL!");
  return _random_data->getSeed(id);
}
isNodal()
bool RandomInterface::isNodal () const inline
Definition at line 67 of file RandomInterface.h.
{ return _is_nodal; }
Referenced by ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementValueSampler::ElementValueSampler(), and NodalValueSampler::NodalValueSampler().
setRandomDataPointer()
void RandomInterface::setRandomDataPointer (RandomData * random_data)
Definition at line 54 of file RandomInterface.C.
{
  _random_data = random_data;
  _generator = &_random_data->getGenerator();
}
Referenced by FEProblemBase::registerRandomInterface().
setRandomResetFrequency()
void RandomInterface::setRandomResetFrequency (ExecFlagType exec_flag)
This interface should be called from a derived class to enable random number generation in this object.
Definition at line 47 of file RandomInterface.C.
{
  _reset_on = exec_flag;
  _ri_problem.registerRandomInterface(*this, _ri_name);
}
validParams()
InputParameters RandomInterface::validParams () static
Definition at line 18 of file RandomInterface.C.
{
  InputParameters params = emptyInputParameters();
  params.addParam<unsigned int>("seed", 0, "The seed for the master random number generator");
  params.addParamNamesToGroup("seed", "Advanced");
  return params;
}
Referenced by AuxKernelTempl< ComputeValueType >::validParams(), ResidualObject::validParams(), MaterialBase::validParams(), DomainUserObject::validParams(), ElementUserObject::validParams(), and NodalUserObject::validParams().
Member Data Documentation
_curr_element
const Elem* const& RandomInterface::_curr_element private
Definition at line 84 of file RandomInterface.h.
Referenced by getRandomLong(), and getRandomReal().
_curr_node
const Node* const& RandomInterface::_curr_node private
Definition at line 83 of file RandomInterface.h.
Referenced by getRandomLong(), and getRandomReal().
_generator
MooseRandom* RandomInterface::_generator mutable private
Definition at line 74 of file RandomInterface.h.
Referenced by getRandomLong(), getRandomReal(), and setRandomDataPointer().
_is_nodal
bool RandomInterface::_is_nodal private
Definition at line 80 of file RandomInterface.h.
Referenced by getRandomLong(), getRandomReal(), and isNodal().
_master_seed
unsigned int RandomInterface::_master_seed private
Definition at line 79 of file RandomInterface.h.
Referenced by getMasterSeed().
_random_data
RandomData* RandomInterface::_random_data private
Definition at line 73 of file RandomInterface.h.
Referenced by getSeed(), and setRandomDataPointer().
_reset_on
ExecFlagType RandomInterface::_reset_on private
Definition at line 81 of file RandomInterface.h.
Referenced by getResetOnTime(), and setRandomResetFrequency().
_ri_name
const std::string RandomInterface::_ri_name private
Definition at line 77 of file RandomInterface.h.
Referenced by setRandomResetFrequency().
_ri_problem
FEProblemBase& RandomInterface::_ri_problem private
Definition at line 76 of file RandomInterface.h.
Referenced by setRandomResetFrequency().
The documentation for this class was generated from the following files:
moose/framework/include/interfaces/RandomInterface.h
moose/framework/src/interfaces/RandomInterface.C