Zapdos: AttribSubdomains Class Reference
AttribSubdomains Class Reference abstract
#include <Attributes.h>
Public Types
typedef SubdomainID Key
Public Member Functions
void setFrom (Key k)
AttribSubdomains (TheWarehouse &w)
AttribSubdomains (TheWarehouse &w, SubdomainID id)
virtual void initFrom (const MooseObject *obj) override
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
virtual bool isMatch (const Attribute &other) const override
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
virtual bool isEqual (const Attribute &other) const override
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
hashfunc (_vals)
clonefunc (AttribSubdomains)
bool operator== (const Attribute &other) const
bool operator!= (const Attribute &other) const
unsigned int id () const
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
virtual std::size_t hash () const =0
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
virtual std::unique_ptr< Attribute > clone () const =0
clone creates and returns and identical (deep) copy of this attribute - i.e.
Private Attributes
std::vector< SubdomainID > _vals
int _id = -1
Detailed Description
Definition at line 160 of file Attributes.h.
Member Typedef Documentation
Key
typedef SubdomainID AttribSubdomains::Key
Definition at line 163 of file Attributes.h.
Constructor & Destructor Documentation
AttribSubdomains() [1/2]
AttribSubdomains::AttribSubdomains (TheWarehouse & w) inline
Definition at line 170 of file Attributes.h.
: Attribute(w, "subdomains") {}
AttribSubdomains() [2/2]
AttribSubdomains::AttribSubdomains (TheWarehouse & w, SubdomainID id) inline
Definition at line 171 of file Attributes.h.
                                                     : Attribute(w, "subdomains")
  {
    _vals.push_back(id);
  }
Member Function Documentation
clone()
virtual std::unique_ptr< Attribute > Attribute::clone () const pure virtual inherited
clone creates and returns and identical (deep) copy of this attribute - i.e.
the result of clone should return true if passed into isMatch.
Referenced by FEProblemBase::computeUserObjectsInternal(), and TheWarehouse::update().
clonefunc()
AttribSubdomains::clonefunc (AttribSubdomains)
hash()
virtual std::size_t Attribute::hash () const pure virtual inherited
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
is initialized with). Ideally, the data should be uniformly and randomly distributed across the domain of size_t values - e.g. 1 and 2 should hash to completely unrelated values. Use of std::hash for POD is encouraged. A convenience hash_combine function is also provided to combine the results an existing hash with one or more other values.
Referenced by std::hash< Attribute >::operator()().
hashfunc()
AttribSubdomains::hashfunc (_vals)
id()
unsigned int Attribute::id () const inline inherited
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
This ID is determined at construction time this
Definition at line 66 of file TheWarehouse.h.
{ return _id; }
Referenced by std::hash< Attribute >::operator()().
initFrom()
void AttribSubdomains::initFrom (const MooseObject * obj) override virtual
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
Implements Attribute.
Definition at line 172 of file Attributes.C.
{
  _vals.clear();
  auto blk = dynamic_cast<const BlockRestrictable *>(obj);
  if (blk && blk->blockRestricted())
  {
    for (auto id : blk->blockIDs())
      _vals.push_back(id);
  }
  else
    _vals.push_back(Moose::ANY_BLOCK_ID);
}
isEqual()
bool AttribSubdomains::isEqual (const Attribute & other) const override virtual
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
isEqual does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 207 of file Attributes.C.
{
  auto a = dynamic_cast<const AttribSubdomains *>(&other);
  if (!a || a->_vals.size() != _vals.size())
    return false;
  for (size_t i = 0; i < a->_vals.size(); i++)
    if (a->_vals[i] != _vals[i])
      return false;
  return true;
}
isMatch()
bool AttribSubdomains::isMatch (const Attribute & other) const override virtual
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
This is is for query matching - not exact equivalence. isMatch does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 186 of file Attributes.C.
{
  auto a = dynamic_cast<const AttribSubdomains *>(&other);
  if (!a || a->_vals.size() < 1)
    return false;
  auto cond = a->_vals[0];
  if (cond == Moose::ANY_BLOCK_ID)
    return true;
  else if (cond == Moose::INVALID_BLOCK_ID)
    return false;
  for (auto id : _vals)
  {
    if (id == cond || id == Moose::ANY_BLOCK_ID)
      return true;
  }
  return false;
}
operator!=()
bool Attribute::operator!= (const Attribute & other) const inline inherited
Definition at line 61 of file TheWarehouse.h.
{ return !(*this == other); }
operator==()
bool Attribute::operator== (const Attribute & other) const inline inherited
Definition at line 57 of file TheWarehouse.h.
  {
    return _id == other._id && isEqual(other);
  }
setFrom()
void AttribSubdomains::setFrom (Key k) inline
Definition at line 164 of file Attributes.h.
  {
    _vals.clear();
    _vals.push_back(k);
  }
Member Data Documentation
_id
int Attribute::_id = -1 private inherited
Definition at line 91 of file TheWarehouse.h.
Referenced by Attribute::id(), and Attribute::operator==().
_vals
std::vector<SubdomainID> AttribSubdomains::_vals private
Definition at line 182 of file Attributes.h.
Referenced by AttribSubdomains(), initFrom(), isEqual(), isMatch(), and setFrom().
The documentation for this class was generated from the following files:
moose/framework/include/base/Attributes.h
moose/framework/src/base/Attributes.C