Zapdos: QuadraturePointMultiApp Class Reference
QuadraturePointMultiApp Class Reference
Automatically generates sub-App positions with elemental quadrature points of the parent mesh.
#include <QuadraturePointMultiApp.h>
Public Member Functions
QuadraturePointMultiApp (const InputParameters &parameters)
virtual NumericVector< Number > & appTransferVector (unsigned int app, std::string var_name) override
Get the vector to transfer to for this MultiApp.
virtual void initialSetup () override
Method to be called in main-app initial setup for create sub-apps if using positions is false.
virtual bool solveStep (Real dt, Real target_time, bool auto_advance=true) override
Re-solve all of the Apps.
virtual void incrementTStep (Real target_time) override
Advances the multi-apps time step which is important for dt selection.
virtual void finishStep (bool recurse_through_multiapp_levels=false) override
Calls multi-apps executioners' endStep and postStep methods which creates output and advances time (not the time step; see incrementTStep()) among other things.
virtual bool needsRestoration () override
Whether or not this MultiApp should be restored at the beginning of each Picard iteration.
virtual void resetApp (unsigned int global_app, Real time) override
"Reset" the App corresponding to the global App number passed in.
Real computeDT ()
Finds the smallest dt from among any of the apps.
virtual void preExecute ()
virtual void finalize ()
Method called towards the end of the simulation to execute on final.
virtual void postExecute ()
Method called at the end of the simulation (after finalize).
void setupPositions ()
Called just after construction to allow derived classes to set _positions and create sub-apps accordingly.
virtual void createLocalApp (const unsigned int i)
Create the i-th local app.
virtual void preTransfer (Real dt, Real target_time)
Gets called just before transfers are done to the MultiApp (Which is just before the MultiApp is solved).
virtual void backup ()
Save off the state of every Sub App.
virtual void restore (bool force=true)
Restore the state of every Sub App.
virtual Executioner * getExecutioner (unsigned int app)
virtual BoundingBox getBoundingBox (unsigned int app, bool displaced_mesh, const MultiAppCoordTransform *coord_transform=nullptr)
Get the BoundingBox for the mesh associated with app The bounding box will be shifted to be in the correct position within the master domain.
FEProblemBase & problemBase ()
Get the FEProblemBase this MultiApp is part of.
FEProblemBase & appProblemBase (unsigned int app)
Get the FEProblemBase for the global app desired.
FEProblem & appProblem (unsigned int app)
Get the FEProblem for the global app is part of.
const UserObject & appUserObjectBase (unsigned int app, const std::string &name)
Get a UserObject base for a specific global app.
Real appPostprocessorValue (unsigned int app, const std::string &name)
Get a Postprocessor value for a specified global app.
unsigned int numGlobalApps () const
unsigned int numLocalApps ()
unsigned int firstLocalApp ()
bool isFirstLocalRank () const
bool hasApp ()
Whether or not this MultiApp has an app on this processor.
bool hasLocalApp (unsigned int global_app) const
Whether or not the given global app number is on this processor.
MooseApp * localApp (unsigned int local_app)
Get the local MooseApp object.
const Point & position (unsigned int app) const
The physical position of a global App number.
virtual void moveApp (unsigned int global_app, Point p)
Move the global_app to Point p.
virtual void parentOutputPositionChanged ()
For apps outputting in position we need to change their output positions if their parent app moves.
MPI_Comm & comm ()
Get the MPI communicator this MultiApp is operating on.
bool isRootProcessor ()
Whether or not this processor is the "root" processor for the sub communicator.
bool usingPositions () const
Whether or not this MultiApp is using positions or its own way for constructing sub-apps.
bool runningInPosition () const
Whether or not this MultiApp is being run in position, eg with the coordinate transform already applied.
void addAssociatedTransfer (MultiAppTransfer &transfer)
Add a transfer that is associated with this multiapp.
void setAppOutputFileBase ()
Sets all the app's output file bases.
virtual bool enabled () const
Return the enabled status of the object.
MooseApp & getMooseApp () const
Get the MooseApp this class is associated with.
const std::string & type () const
Get the type of this class.
virtual const std::string & name () const
Get the name of the class.
std::string typeAndName () const
Get the class's combined type and name; useful in error handling.
MooseObjectParameterName uniqueParameterName (const std::string &parameter_name) const
The unique parameter name of a valid parameter of this object for accessing parameter controls.
const InputParameters & parameters () const
Get the parameters of the object.
MooseObjectName uniqueName () const
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
template<typename T >
const T & getParam (const std::string &name) const
Retrieve a parameter for the object.
template<typename T1 , typename T2 >
std::vector< std::pair< T1, T2 > > getParam (const std::string &param1, const std::string &param2) const
Retrieve two parameters and provide pair of parameters for the object.
template<typename T >
const T & getRenamedParam (const std::string &old_name, const std::string &new_name) const
Retrieve a renamed parameter for the object.
template<typename T >
T getCheckedPointerParam (const std::string &name, const std::string &error_string="") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
bool isParamValid (const std::string &name) const
Test if the supplied parameter is valid.
bool isParamSetByUser (const std::string &nm) const
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
template<typename... Args>
void paramError (const std::string &param, Args... args) const
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramWarning (const std::string &param, Args... args) const
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramInfo (const std::string &param, Args... args) const
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
std::string objectErrorPrefix (const std::string &error_type) const
A descriptive prefix for errors for an object.
void connectControllableParams (const std::string &parameter, const std::string &object_type, const std::string &object_name, const std::string &object_parameter) const
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
template<typename... Args>
void mooseError (Args &&... args) const
Emits an error prefixed with object name and type.
template<typename... Args>
void mooseErrorNonPrefixed (Args &&... args) const
Emits an error without the prefixing included in mooseError().
template<typename... Args>
void mooseWarning (Args &&... args) const
Emits a warning prefixed with object name and type.
template<typename... Args>
void mooseWarningNonPrefixed (Args &&... args) const
Emits a warning without the prefixing included in mooseWarning().
template<typename... Args>
void mooseDeprecated (Args &&... args) const
template<typename... Args>
void mooseInfo (Args &&... args) const
std::string errorPrefix (const std::string &error_type) const
A descriptive prefix for errors for this object:
std::string getDataFileName (const std::string &param) const
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
std::string getDataFileNameByName (const std::string &name, const std::string *param=nullptr) const
Returns the path of a data file for a given relative file path.
virtual void timestepSetup ()
Gets called at the beginning of the timestep before this object is asked to do its job.
virtual void jacobianSetup ()
Gets called just before the Jacobian is computed and before this object is asked to do its job.
virtual void residualSetup ()
Gets called just before the residual is computed and before this object is asked to do its job.
virtual void subdomainSetup ()
Gets called when the subdomain changes (i.e.
virtual void customSetup (const ExecFlagType &)
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
const ExecFlagEnum & getExecuteOnEnum () const
Return the execute on MultiMooseEnum for this object.
PerfGraph & perfGraph ()
Get the PerfGraph.
const std::vector< SubdomainName > & blocks () const
Return the block names for this object.
unsigned int numBlocks () const
Return the number of blocks for this object.
virtual const std::set< SubdomainID > & blockIDs () const
Return the block subdomain ids for this object Note, if this is not block restricted, this function returns all mesh subdomain ids.
unsigned int blocksMaxDimension () const
Return the largest mesh dimension of the elements in the blocks for this object.
bool hasBlocks (const SubdomainName &name) const
Test if the supplied block name is valid for this object.
bool hasBlocks (const std::vector< SubdomainName > &names) const
Test if the supplied vector of block names are valid for this object.
bool hasBlocks (SubdomainID id) const
Test if the supplied block ids are valid for this object.
bool hasBlocks (const std::vector< SubdomainID > &ids) const
Test if the supplied vector block ids are valid for this object.
bool hasBlocks (const std::set< SubdomainID > &ids) const
Test if the supplied set of block ids are valid for this object.
bool isBlockSubset (const std::set< SubdomainID > &ids) const
Test if the class block ids are a subset of the supplied objects.
bool isBlockSubset (const std::vector< SubdomainID > &ids) const
Test if the class block ids are a subset of the supplied objects.
template<typename T , bool is_ad = false>
bool hasBlockMaterialProperty (const std::string &prop_name)
Check if a material property is valid for all blocks of this object.
const std::set< SubdomainID > & meshBlockIDs () const
Return all of the SubdomainIDs for the mesh.
virtual bool blockRestricted () const
Returns true if this object has been restricted to a block.
virtual void checkVariable (const MooseVariableFieldBase &variable) const
Helper for checking that the ids for this object are in agreement with the variables on the supplied variable.
Static Public Member Functions
static InputParameters validParams ()
static void transformBoundingBox (BoundingBox &box, const MultiAppCoordTransform &transform)
Transform a bounding box according to the transformations in the provided coordinate transformation object.
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Member Functions
void fillPositions () override
must fill in _positions with the positions of the sub-aps
void setAppOutputFileBase (unsigned int index)
Set the output file base of the application which corresponds to the index passed to the function.
virtual std::vector< std::string > cliArgs () const
function that provides cli_args to subapps
void readCommandLineArguments ()
Fill command line arguments for sub apps.
void createApp (unsigned int i, Real start_time)
Helper function for creating an App instance.
void buildComm ()
Create an MPI communicator suitable for each app.
unsigned int globalAppToLocal (unsigned int global_app)
Map a global App number to the local number.
virtual void preRunInputFile ()
call back executed right before app->runInputFile()
virtual std::string getCommandLineArgsParamHelper (unsigned int local_app)
Method to aid in getting the "cli_args" parameters.
void init (unsigned int num_apps, bool batch_mode=false)
Build communicators and reserve backups.
void init (unsigned int num_apps, const LocalRankConfig &config)
Same as other init method, except defining a custom rank configuration.
void createApps ()
Create the provided number of apps.
void keepSolutionDuringRestore (bool keep_solution_during_restore)
Reserve the solution from the previous simulation, and it is used as an initial guess for the next run.
template<typename T , typename... Args>
T & declareRestartableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
ManagedValue< T > declareManagedRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declares a piece of "managed" restartable data and initialize it.
template<typename T , typename... Args>
const T & getRestartableData (const std::string &data_name) const
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
template<typename T , typename... Args>
T & declareRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
T & declareRecoverableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "recoverable" and initialize it.
template<typename T , typename... Args>
T & declareRestartableDataWithObjectName (const std::string &data_name, const std::string &object_name, Args &&... args)
Declare a piece of data as "restartable".
template<typename T , typename... Args>
T & declareRestartableDataWithObjectNameWithContext (const std::string &data_name, const std::string &object_name, void *context, Args &&... args)
Declare a piece of data as "restartable".
std::string restartableName (const std::string &data_name) const
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level) const
Call to register a named section for timing.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level, const std::string &live_message, const bool print_dots=true) const
Call to register a named section for timing.
std::string timedSectionName (const std::string &section_name) const
virtual bool hasBlockMaterialPropertyHelper (const std::string &prop_name)
A helper method to allow the Material object to specialize the behavior of hasBlockMaterialProperty.
void initializeBlockRestrictable (const MooseObject *moose_object)
An initialization routine needed for dual constructors.
Moose::CoordinateSystemType getBlockCoordSystem ()
Check if the blocks this object operates on all have the same coordinate system, and if so return it.
Static Protected Member Functions
static std::string getMultiAppName (const std::string &base_name, dof_id_type index, dof_id_type total)
Helper for constructing the name of the multiapp.
Protected Attributes
FEProblemBase & _fe_problem
The FEProblemBase this MultiApp is part of.
std::string _app_type
The type of application to build.
std::vector< Point > _positions
The positions of all of the apps, using input constant vectors (to be deprecated)
std::vector< const Positions * > _positions_objs
The positions of all of the apps, using the Positions system.
std::vector< unsigned int > _positions_index_offsets
The offsets, in case multiple Positions objects are specified.
const bool _use_positions
Toggle use of "positions".
std::vector< FileName > _input_files
The input file for each app's simulation.
const bool & _wait_for_first_app_init
Whether to create the first app on rank 0 while all other MPI ranks are idle.
std::vector< unsigned int > _npositions_inputfile
Number of positions for each input file.
std::string _output_base
The output file basename for each multiapp.
unsigned int _total_num_apps
The total number of apps to simulate.
unsigned int _my_num_apps
The number of apps this object is involved in simulating.
unsigned int _first_local_app
The number of the first app on this processor.
const MPI_Comm & _orig_comm
The original comm handle.
libMesh::Parallel::Communicator _my_communicator
The communicator object that holds the MPI_Comm that we're going to use.
MPI_Comm & _my_comm
The MPI communicator this object is going to use.
int _orig_num_procs
The number of processors in the original comm.
int _orig_rank
The mpi "rank" of this processor in the original communicator.
std::string _node_name
Node Name.
int _my_rank
The mpi "rank" of this processor in the sub communicator.
std::vector< std::shared_ptr< MooseApp > > _apps
Pointers to each of the Apps.
std::vector< bool > _has_bounding_box
Flag if this multi-app computed its bounding box (valid only for non-displaced meshes)
std::vector< BoundingBox > _bounding_box
This multi-app's bounding box.
Real _inflation
Relative bounding box inflation.
Point _bounding_box_padding
Additional padding added to the bounding box, useful for 1D meshes.
processor_id_type _max_procs_per_app
Maximum number of processors to give to each app.
processor_id_type _min_procs_per_app
Minimum number of processors to give to each app.
bool _output_in_position
Whether or not to move the output of the MultiApp into position.
const Real _global_time_offset
The offset time so the MultiApp local time relative to the global time.
std::vector< Real > _reset_times
The times at which to reset apps.
std::vector< unsigned int > _reset_apps
The apps to be reset.
std::vector< bool > _reset_happened
Whether or not apps have been reset at each time.
Real _move_time
The time at which to move apps.
std::vector< unsigned int > _move_apps
The apps to be moved.
std::vector< Point > _move_positions
The new positions for the apps to be moved.
bool _move_happened
Whether or not the move has happened.
bool _has_an_app
Whether or not this processor as an App at all
const std::vector< CLIArgString > & _cli_args
CommandLine arguments.
std::vector< std::string > _cli_args_from_file
CommandLine arguments from files.
bool _keep_solution_during_restore
Flag indicates if or not restart from the latest solution.
std::vector< std::unique_ptr< NumericVector< Real > > > _end_solutions
The solution from the end of the previous solve, this is cloned from the Nonlinear solution during restore.
LocalRankConfig _rank_config
The app configuration resulting from calling init.
std::vector< MultiAppTransfer * > _associated_transfers
Transfers associated with this multiapp.
const bool _run_in_position
Whether to run the child apps with their meshes transformed with the coordinate transforms.
SubAppBackups & _sub_app_backups
The cached subapp backups (passed from the parent app)
const PerfID _solve_step_timer
Timers.
const PerfID _init_timer
const PerfID _backup_timer
const PerfID _restore_timer
const PerfID _reset_timer
const bool & _enabled
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
MooseApp & _app
The MOOSE application this is associated with.
const std::string & _type
The type of this class.
const std::string & _name
The name of this class, reference to value stored in InputParameters.
const InputParameters & _pars
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Factory & _factory
The Factory associated with the MooseApp.
ActionFactory & _action_factory
Builds Actions.
const ExecFlagEnum & _execute_enum
Execute settings for this object.
const ExecFlagType & _current_execute_flag
Reference to FEProblemBase.
MooseApp & _restartable_app
Reference to the application.
const std::string _restartable_system_name
The system name this object is in.
const THREAD_ID _restartable_tid
The thread ID for this object.
const bool _restartable_read_only
Flag for toggling read only status (see ReporterData)
MooseApp & _pg_moose_app
The MooseApp that owns the PerfGraph.
const std::string _prefix
A prefix to use for all sections.
const MaterialData * _blk_material_data
Pointer to the MaterialData class for this object.
Private Member Functions
void setupApp (unsigned int i, Real time=0.0)
Setup the executioner for the local app.
template<typename... Args>
std::string paramErrorMsg (const std::string &param, Args... args) const
RestartableDataValue & registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const
Helper function for actually registering the restartable data.
void registerRestartableNameWithFilterOnApp (const std::string &name, Moose::RESTARTABLE_FILTER filter)
Helper function for actually registering the restartable data.
template<typename T , typename... Args>
RestartableData< T > & declareRestartableDataHelper (const std::string &data_name, void *context, Args &&... args) const
Helper function for declaring restartable data.
Private Attributes
std::vector< Transient * > _transient_executioners
bool _sub_cycling
bool _interpolate_transfers
bool _detect_steady_state
Real _steady_state_tol
bool _output_sub_cycles
unsigned int _max_failures
bool _tolerate_failure
unsigned int _failures
bool _catch_up
Real _max_catch_up_steps
bool & _first
Is it our first time through the execution loop?
std::vector< std::string > _transferred_vars
The variables that have been transferred to. Used when doing transfer interpolation. This will be cleared after each solve.
std::set< dof_id_type > _transferred_dofs
The DoFs associated with all of the currently transferred variables.
std::vector< std::map< std::string, unsigned int > > _output_file_numbers
bool _auto_advance
std::set< unsigned int > _reset
bool _print_sub_cycles
Flag for toggling console output on sub cycles.
const MooseBase *const _moose_base
The MooseBase object that inherits this class.
const MooseObject & _parent
ExecFlagEnum _empty_execute_enum
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
const RestartableDataMapName _metaname
Restartable metadata name.
std::string _restartable_name
The name of the object.
std::set< SubdomainID > _blk_ids
Set of block ids supplied by the user via the input file (for error checking)
std::vector< SubdomainID > _vec_ids
Vector of block ids supplied by the user via the input file (for error reporting)
std::vector< SubdomainName > _blocks
Vector the block names supplied by the user via the input file.
const bool _blk_dual_restrictable
Flag for allowing dual restriction.
FEProblemBase * _blk_feproblem
Pointer to FEProblemBase.
MooseMesh * _blk_mesh
Pointer to Mesh.
const std::set< BoundaryID > _empty_boundary_ids
An empty set for referencing when boundary_ids is not included.
const std::set< BoundaryID > & _boundary_ids
Reference to the boundary_ids, defaults to an empty set if not provided.
THREAD_ID _blk_tid
Thread id for this object.
const std::string & _blk_name
Name of the object.
unsigned int _blk_dim
Largest mesh dimension of the elements in the blocks for this object.
Detailed Description
Automatically generates sub-App positions with elemental quadrature points of the parent mesh.
Definition at line 18 of file QuadraturePointMultiApp.h.
Constructor & Destructor Documentation
QuadraturePointMultiApp()
QuadraturePointMultiApp::QuadraturePointMultiApp (const InputParameters & parameters)
Definition at line 38 of file QuadraturePointMultiApp.C.
  : TransientMultiApp(parameters), BlockRestrictable(this)
{
}
Member Function Documentation
addAssociatedTransfer()
void MultiApp::addAssociatedTransfer (MultiAppTransfer & transfer) inherited
Add a transfer that is associated with this multiapp.
Definition at line 1328 of file MultiApp.C.
{
  _associated_transfers.push_back(&transfer);
}
appPostprocessorValue()
Real MultiApp::appPostprocessorValue (unsigned int app, const std::string & name) inherited
Get a Postprocessor value for a specified global app.
Parameters
app The global app number you want to get a Postprocessor from.
name The name of the Postprocessor.
Definition at line 968 of file MultiApp.C.
{
  if (!_has_an_app)
    mooseError("No app for ", MultiApp::name(), " on processor ", _orig_rank);
  return appProblemBase(app).getPostprocessorValueByName(name);
}
appProblem()
FEProblem & MultiApp::appProblem (unsigned int app) inherited
Get the FEProblem for the global app is part of.
Parameters
app The global app number
Definition at line 946 of file MultiApp.C.
{
  mooseDeprecated(
      "MultiApp::appProblem() is deprecated, call MultiApp::appProblemBase() instead.\n");
  if (!_has_an_app)
    mooseError("No app for ", name(), " on processor ", _orig_rank);
  unsigned int local_app = globalAppToLocal(app);
  return dynamic_cast<FEProblem &>(_apps[local_app]->getExecutioner()->feProblem());
}
appProblemBase()
FEProblemBase & MultiApp::appProblemBase (unsigned int app) inherited
Get the FEProblemBase for the global app desired.
Parameters
app The global app number
Definition at line 935 of file MultiApp.C.
{
  if (!_has_an_app)
    mooseError("No app for ", name(), " on processor ", _orig_rank);
  unsigned int local_app = globalAppToLocal(app);
  return _apps[local_app]->getExecutioner()->feProblem();
}
Referenced by MultiApp::appPostprocessorValue(), MultiApp::appTransferVector(), TransientMultiApp::appTransferVector(), MultiApp::appUserObjectBase(), TransientMultiApp::resetApp(), TransientMultiApp::setupApp(), and TransientMultiApp::solveStep().
appTransferVector()
NumericVector< Number > & TransientMultiApp::appTransferVector (unsigned int app, std::string var_name) override virtual inherited
Get the vector to transfer to for this MultiApp.
In general this is the Auxiliary system solution vector.
Parameters
app The global app number you want the transfer vector for.
var_name The name of the variable you are going to be transferring to.
Returns
The vector to fill.
Reimplemented from MultiApp.
Definition at line 149 of file TransientMultiApp.C.
{
  if (std::find(_transferred_vars.begin(), _transferred_vars.end(), var_name) ==
      _transferred_vars.end())
    _transferred_vars.push_back(var_name);
  if (_interpolate_transfers)
    return appProblemBase(app).getAuxiliarySystem().system().get_vector("transfer");
  return appProblemBase(app).getAuxiliarySystem().solution();
}
appUserObjectBase()
const UserObject & MultiApp::appUserObjectBase (unsigned int app, const std::string & name) inherited
Get a UserObject base for a specific global app.
Parameters
app The global app number you want to get a UserObject from.
name The name of the UserObject.
Definition at line 959 of file MultiApp.C.
{
  if (!_has_an_app)
    mooseError("No app for ", MultiApp::name(), " on processor ", _orig_rank);
  return appProblemBase(app).getUserObjectBase(name);
}
backup()
void MultiApp::backup () virtual inherited
Save off the state of every Sub App.
This allows us to "Restore" this state later
Reimplemented in FullSolveMultiApp.
Definition at line 721 of file MultiApp.C.
{
  TIME_SECTION(_backup_timer);
  if (_fe_problem.verboseMultiApps())
    _console << "Backed up MultiApp ... ";
  for (unsigned int i = 0; i < _my_num_apps; i++)
    _sub_app_backups[i] = _apps[i]->backup();
  if (_fe_problem.verboseMultiApps())
    _console << name() << std::endl;
}
Referenced by MultiApp::backup(), FullSolveMultiApp::backup(), and dataStore().
blockIDs()
const std::set< SubdomainID > & BlockRestrictable::blockIDs () const virtual inherited
Return the block subdomain ids for this object Note, if this is not block restricted, this function returns all mesh subdomain ids.
Returns
a set of SubdomainIDs that are valid for this object
Definition at line 190 of file BlockRestrictable.C.
{
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return _blk_mesh->meshSubdomains();
  else
    return _blk_ids;
}
Referenced by FunctorMaterial::addFunctorProperty(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), NodalPatchRecoveryAuxBase::blockRestrictElements(), MooseMesh::cacheFaceInfoVariableOwnership(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), BlockRestrictable::getBlockCoordSystem(), MaterialBase::getGenericZeroMaterialPropertyByName(), BlockRestrictable::hasBlockMaterialPropertyHelper(), SubdomainsDivision::initialize(), ElementCentroidPositions::initialize(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), MaterialBase::registerPropName(), and FVPointValueConstraint::setMyElem().
blockRestricted()
bool BlockRestrictable::blockRestricted () const virtual inherited
Returns true if this object has been restricted to a block.
See also
MooseObject
Definition at line 178 of file BlockRestrictable.C.
{
  return _blk_ids.find(Moose::ANY_BLOCK_ID) == _blk_ids.end();
}
Referenced by NodalPatchRecoveryAuxBase::blockRestrictElements(), BlockRestrictable::checkVariable(), SubdomainsDivision::divisionIndex(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), SubdomainsDivision::initialize(), ElementCentroidPositions::initialize(), BlockRestrictable::initializeBlockRestrictable(), SolutionIC::initialSetup(), and FVPointValueConstraint::setMyElem().
blocks()
const std::vector< SubdomainName > & BlockRestrictable::blocks () const inherited
Return the block names for this object.
Note, if the 'blocks' input parameter was not utilized this will return an empty vector.
Returns
vector of SubdomainNames that are valid for this object
Definition at line 184 of file BlockRestrictable.C.
{
  return _blocks;
}
Referenced by MaterialOutputAction::getParams(), BlockAverageValue::initialize(), SubdomainsDivision::initialize(), and SolutionIC::initialSetup().
blocksMaxDimension()
unsigned int BlockRestrictable::blocksMaxDimension () const inherited
Return the largest mesh dimension of the elements in the blocks for this object.
Definition at line 360 of file BlockRestrictable.C.
{
  mooseAssert(_blk_dim != libMesh::invalid_uint, "Block restriction not initialized");
  return _blk_dim;
}
buildComm()
void MultiApp::buildComm () protected inherited
Create an MPI communicator suitable for each app.
Also find out which communicator we are using and what our first local app is.
Definition at line 1262 of file MultiApp.C.
{
  int ierr;
  ierr = MPI_Comm_size(_communicator.get(), &_orig_num_procs);
  mooseCheckMPIErr(ierr);
  ierr = MPI_Comm_rank(_communicator.get(), &_orig_rank);
  mooseCheckMPIErr(ierr);
#ifdef LIBMESH_HAVE_SYS_UTSNAME_H
  struct utsname sysInfo;
  uname(&sysInfo);
  _node_name = sysInfo.nodename;
#else
  _node_name = "Unknown";
#endif
  int rank;
  ierr = MPI_Comm_rank(_communicator.get(), &rank);
  mooseCheckMPIErr(ierr);
  _my_num_apps = _rank_config.num_local_apps;
  _first_local_app = _rank_config.first_local_app_index;
  _has_an_app = _rank_config.num_local_apps > 0;
  if (_rank_config.first_local_app_index >= _total_num_apps)
    mooseError("Internal error, a processor has an undefined app.");
  if (_has_an_app)
  {
    _communicator.split(_rank_config.first_local_app_index, rank, _my_communicator);
    ierr = MPI_Comm_rank(_my_comm, &_my_rank);
    mooseCheckMPIErr(ierr);
  }
  else
  {
    _communicator.split(MPI_UNDEFINED, rank, _my_communicator);
    _my_rank = 0;
  }
}
Referenced by MultiApp::init().
checkVariable()
void BlockRestrictable::checkVariable (const MooseVariableFieldBase & variable) const virtual inherited
Helper for checking that the ids for this object are in agreement with the variables on the supplied variable.
Parameters
variable The variable to check against.
Reimplemented in DomainUserObject.
Definition at line 333 of file BlockRestrictable.C.
{
  // a variable defined on all internal sides does not need this check because
  // it can be coupled with other variables in DG kernels
  if (variable.activeSubdomains().count(Moose::INTERNAL_SIDE_LOWERD_ID) > 0)
    return;
  if (!isBlockSubset(variable.activeSubdomains()))
  {
    std::string var_ids = Moose::stringify(variable.activeSubdomains(), ", ");
    std::string obj_ids = Moose::stringify(blockRestricted() ? _blk_ids : meshBlockIDs(), ", ");
    mooseError("The 'block' parameter of the object '",
               _blk_name,
               "' must be a subset of the 'block' parameter of the variable '",
               variable.name(),
               "':\n    Object '",
               _blk_name,
               "': ",
               obj_ids,
               "\n    Variable '",
               variable.name(),
               "': ",
               var_ids);
  }
}
Referenced by DomainUserObject::checkVariable().
cliArgs()
virtual std::vector< std::string > MultiApp::cliArgs () const inline protected virtual inherited
function that provides cli_args to subapps
Definition at line 387 of file MultiApp.h.
  {
    return std::vector<std::string>(_cli_args.begin(), _cli_args.end());
  }
Referenced by MultiApp::createApp(), MultiApp::getCommandLineArgsParamHelper(), MultiApp::init(), and MultiApp::readCommandLineArguments().
comm()
MPI_Comm & MultiApp::comm () inline inherited
Get the MPI communicator this MultiApp is operating on.
Returns
The MPI comm for this MultiApp
Definition at line 350 of file MultiApp.h.
{ return _my_comm; }
computeDT()
Real TransientMultiApp::computeDT () inherited
Finds the smallest dt from among any of the apps.
Definition at line 607 of file TransientMultiApp.C.
{
  if (_sub_cycling) // Bow out of the timestep selection dance
    return std::numeric_limits<Real>::max();
  Real smallest_dt = std::numeric_limits<Real>::max();
  if (_has_an_app)
  {
    Moose::ScopedCommSwapper swapper(_my_comm);
    for (unsigned int i = 0; i < _my_num_apps; i++)
    {
      Transient * ex = _transient_executioners[i];
      ex->computeDT();
      Real dt = ex->getDT();
      smallest_dt = std::min(dt, smallest_dt);
    }
  }
  if (_tolerate_failure) // Bow out of the timestep selection dance, we do this down here because we
                         // need to call computeConstrainedDT at least once for these
                         // executioners...
    return std::numeric_limits<Real>::max();
  _communicator.min(smallest_dt);
  return smallest_dt;
}
connectControllableParams()
void MooseBaseParameterInterface::connectControllableParams (const std::string & parameter, const std::string & object_type, const std::string & object_name, const std::string & object_parameter) const inherited
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
Parameters
parameter Name of the controllable parameter of this action
object_type Type of the object added by this action.
object_name Name of the object added by this action.
object_parameter Name of the parameter of the object.
Definition at line 34 of file MooseBaseParameterInterface.C.
{
  MooseObjectParameterName primary_name(uniqueName(), parameter);
  const auto base_type = _factory.getValidParams(object_type).get<std::string>("_moose_base");
  MooseObjectParameterName secondary_name(base_type, object_name, object_parameter);
  _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
      primary_name, secondary_name);
  const auto & tags = _pars.get<std::vector<std::string>>("control_tags");
  for (const auto & tag : tags)
  {
    if (!tag.empty())
    {
      MooseObjectParameterName tagged_name(tag, _moose_base->name(), parameter);
      _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
          tagged_name, secondary_name);
    }
  }
}
createApp()
void MultiApp::createApp (unsigned int i, Real start_time) protected inherited
Helper function for creating an App instance.
Parameters
i The local app number to create.
start_time The initial time for the App
Definition at line 1054 of file MultiApp.C.
{
  // Define the app name
  const std::string multiapp_name = getMultiAppName(name(), _first_local_app + i, _total_num_apps);
  std::string full_name;
  // Only add parent name if the parent is not the main app
  if (_app.multiAppLevel() > 0)
    full_name = _app.name() + "_" + multiapp_name;
  else
    full_name = multiapp_name;
  InputParameters app_params = AppFactory::instance().getValidParams(_app_type);
  app_params.set<FEProblemBase *>("_parent_fep") = &_fe_problem;
  app_params.set<std::unique_ptr<Backup> *>("_initial_backup") = &_sub_app_backups[i];
  // Set the command line parameters with a copy of the main application command line parameters,
  // the copy is required so that the addArgument command below doesn't accumulate more and more
  // of the same cli_args, which is important when running in batch mode.
  std::shared_ptr<CommandLine> app_cli = std::make_shared<CommandLine>(*_app.commandLine());
  if (cliArgs().size() > 0 || _cli_args_from_file.size() > 0)
  {
    for (const std::string & str : MooseUtils::split(getCommandLineArgsParamHelper(i), ";"))
    {
      std::ostringstream oss;
      oss << full_name << ":" << str;
      app_cli->addArgument(oss.str());
    }
  }
  app_cli->initForMultiApp(full_name);
  app_params.set<std::shared_ptr<CommandLine>>("_command_line") = app_cli;
  if (_fe_problem.verboseMultiApps())
    _console << COLOR_CYAN << "Creating MultiApp " << name() << " of type " << _app_type
             << " of level " << _app.multiAppLevel() + 1 << " and number " << _first_local_app + i
             << " on processor " << processor_id() << " with full name " << full_name
             << COLOR_DEFAULT << std::endl;
  app_params.set<unsigned int>("_multiapp_level") = _app.multiAppLevel() + 1;
  app_params.set<unsigned int>("_multiapp_number") = _first_local_app + i;
  if (getParam<bool>("clone_master_mesh") || getParam<bool>("clone_parent_mesh"))
  {
    if (_fe_problem.verboseMultiApps())
      _console << COLOR_CYAN << "Cloned parent app mesh will be used for MultiApp " << name()
               << COLOR_DEFAULT << std::endl;
    app_params.set<const MooseMesh *>("_master_mesh") = &_fe_problem.mesh();
    auto displaced_problem = _fe_problem.getDisplacedProblem();
    if (displaced_problem)
      app_params.set<const MooseMesh *>("_master_displaced_mesh") = &displaced_problem->mesh();
  }
  _apps[i] = AppFactory::instance().createShared(_app_type, full_name, app_params, _my_comm);
  auto & app = _apps[i];
  std::string input_file = "";
  if (_input_files.size() == 1) // If only one input file was provided, use it for all the solves
    input_file = _input_files[0];
  else
    input_file = _input_files[_first_local_app + i];
  app->setGlobalTimeOffset(start_time);
  app->setInputFileName(input_file);
  app->setOutputFileNumbers(_app.getOutputWarehouse().getFileNumbers());
  app->setRestart(_app.isRestarting());
  app->setRecover(_app.isRecovering());
  if (_use_positions && getParam<bool>("output_in_position"))
    app->setOutputPosition(_app.getOutputPosition() + _positions[_first_local_app + i]);
  if (_output_in_position && _run_in_position)
    paramError("run_in_position",
               "Sub-apps are already displaced, so they are already output in position");
  // Update the MultiApp level for the app that was just created
  app->setupOptions();
  // if multiapp does not have file base in Outputs input block, output file base will
  // be empty here since setupOptions() does not set the default file base with the multiapp
  // input file name. Parent app will create the default file base for multiapp by taking the
  // output base of the parent app problem and appending the name of the multiapp plus a number to
  // it
  if (app->getOutputFileBase().empty())
    setAppOutputFileBase(i);
  preRunInputFile();
  // Transfer coupling relaxation information to the subapps
  _apps[i]->fixedPointConfig().sub_relaxation_factor = getParam<Real>("relaxation_factor");
  _apps[i]->fixedPointConfig().sub_transformed_vars =
      getParam<std::vector<std::string>>("transformed_variables");
  // Handle deprecated parameter
  if (!parameters().isParamSetByAddParam("relaxed_variables"))
    _apps[i]->fixedPointConfig().sub_transformed_vars =
        getParam<std::vector<std::string>>("relaxed_variables");
  _apps[i]->fixedPointConfig().sub_transformed_pps =
      getParam<std::vector<PostprocessorName>>("transformed_postprocessors");
  app->runInputFile();
  auto fixed_point_solve = &(_apps[i]->getExecutioner()->fixedPointSolve());
  if (fixed_point_solve)
    fixed_point_solve->allocateStorage(false);
  // Transform the app mesh if requested
  if (_run_in_position)
  {
    if (usingPositions())
      app->getExecutioner()->feProblem().coordTransform().transformMesh(
          app->getExecutioner()->feProblem().mesh(), _positions[_first_local_app + i]);
    else
      app->getExecutioner()->feProblem().coordTransform().transformMesh(
          app->getExecutioner()->feProblem().mesh(), Point(0, 0, 0));
  }
}
Referenced by MultiApp::createLocalApp(), and MultiApp::resetApp().
createApps()
void MultiApp::createApps () protected inherited
Create the provided number of apps.
This is called in the setupPositions().
Definition at line 361 of file MultiApp.C.
{
  if (!_has_an_app)
    return;
  TIME_SECTION("createApps", 2, "Instantiating Sub-Apps", false);
  // Read commandLine arguments that will be used when creating apps
  readCommandLineArguments();
  Moose::ScopedCommSwapper swapper(_my_comm);
  _apps.resize(_my_num_apps);
  // If the user provided an unregistered app type, see if we can load it dynamically
  if (!AppFactory::instance().isRegistered(_app_type))
    _app.dynamicAppRegistration(_app_type,
                                getParam<std::string>("library_path"),
                                getParam<std::string>("library_name"),
                                getParam<bool>("library_load_dependencies"));
  bool rank_did_quiet_init = false;
  unsigned int local_app = libMesh::invalid_uint;
  if (_wait_for_first_app_init)
  {
    if (hasLocalApp(0))
    {
      rank_did_quiet_init = true;
      local_app = globalAppToLocal(0);
      createLocalApp(local_app);
    }
    MPI_Barrier(_orig_comm);
  }
  for (unsigned int i = 0; i < _my_num_apps; i++)
  {
    if (rank_did_quiet_init && i == local_app)
      continue;
    createLocalApp(i);
  }
}
Referenced by MultiApp::initialSetup(), and MultiApp::setupPositions().
createLocalApp()
void MultiApp::createLocalApp (const unsigned int i) virtual inherited
Create the i-th local app.
Parameters
[in] i local app index
Definition at line 405 of file MultiApp.C.
{
  createApp(i, _global_time_offset);
  _app.parser().hitCLIFilter(_apps[i]->name(), _app.commandLine()->getArguments());
}
Referenced by MultiApp::createApps().
customSetup()
virtual void SetupInterface::customSetup (const ExecFlagType &) inline virtual inherited
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
Reimplemented in Function.
Definition at line 61 of file SetupInterface.h.
{}
declareManagedRestartableDataWithContext()
template<typename T , typename... Args> Restartable::ManagedValue< T > Restartable::declareManagedRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declares a piece of "managed" restartable data and initialize it.
Here, "managed" restartable data means that the caller can destruct this data upon destruction of the return value of this method. Therefore, this ManagedValue<T> wrapper should survive after the final calls to dataStore() for it. That is... at the very end.
This is needed for objects whose destruction ordering is important, and enables natural c++ destruction in reverse construction order of the object that declares it.
See delcareRestartableData and declareRestartableDataWithContext for more information.
Definition at line 276 of file Restartable.h.
{
  auto & data_ptr =
      declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...);
  return Restartable::ManagedValue<T>(data_ptr);
}
declareRecoverableData()
template<typename T , typename... Args> T & Restartable::declareRecoverableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "recoverable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
Note - this data will NOT be restored on Restart!
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 351 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  registerRestartableNameWithFilterOnApp(full_name, Moose::RESTARTABLE_FILTER::RECOVERABLE);
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableData()
template<typename T , typename... Args> T & Restartable::declareRestartableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 269 of file Restartable.h.
{
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataHelper()
template<typename T , typename... Args> RestartableData< T > & Restartable::declareRestartableDataHelper (const std::string & data_name, void * context, Args &&... args) const private inherited
Helper function for declaring restartable data.
We use this function to reduce code duplication when returning const/nonconst references to the data.
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 303 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  // Here we will create the RestartableData even though we may not use this instance.
  // If it's already in use, the App will return a reference to the existing instance and we'll
  // return that one instead. We might refactor this to have the app create the RestartableData
  // at a later date.
  auto data_ptr =
      std::make_unique<RestartableData<T>>(full_name, context, std::forward<Args>(args)...);
  auto & restartable_data_ref = static_cast<RestartableData<T> &>(
      registerRestartableDataOnApp(std::move(data_ptr), _restartable_tid));
  return restartable_data_ref;
}
declareRestartableDataWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 294 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...).set();
}
declareRestartableDataWithObjectName()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectName (const std::string & data_name, const std::string & object_name, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
args Arguments to forward to the constructor of the data
Definition at line 323 of file Restartable.h.
{
  return declareRestartableDataWithObjectNameWithContext<T>(
      data_name, object_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataWithObjectNameWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectNameWithContext (const std::string & data_name, const std::string & object_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 333 of file Restartable.h.
{
  std::string old_name = _restartable_name;
  _restartable_name = object_name;
  T & value = declareRestartableDataWithContext<T>(data_name, context, std::forward<Args>(args)...);
  _restartable_name = old_name;
  return value;
}
enabled()
virtual bool MooseObject::enabled () const inline virtual inherited
Return the enabled status of the object.
Reimplemented in EigenKernel.
Definition at line 54 of file MooseObject.h.
{ return _enabled; }
Referenced by EigenKernel::enabled().
errorPrefix()
std::string MooseBaseErrorInterface::errorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for this object:
The following <error_type> occurred in the object "<name>", of type "<type>".
Definition at line 15 of file MooseBaseErrorInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the object \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseErrorInterface::mooseError(), and MooseBaseErrorInterface::mooseWarning().
fillPositions()
void QuadraturePointMultiApp::fillPositions () override protected virtual
must fill in _positions with the positions of the sub-aps
Reimplemented from MultiApp.
Definition at line 44 of file QuadraturePointMultiApp.C.
{
  MooseMesh & main_mesh = _fe_problem.mesh();
  auto & mesh = main_mesh.getMesh();
  for (auto & elem : mesh.active_local_element_ptr_range())
  {
    // FEType is local to the element, supporting mixed order meshes
    const FEFamily mapping_family = FEMap::map_fe_type(*elem);
    FEType fe_type(elem->default_order(), mapping_family);
    const auto qrule = fe_type.default_quadrature_rule(elem->dim());
    // Build a Finite Element object of the specified type
    std::unique_ptr<FEBase> fe(FEBase::build(elem->dim(), fe_type));
    // Tell the finite element object to use our quadrature rule.
    fe->attach_quadrature_rule(qrule.get());
    // The physical XY locations of the quadrature points on the element.
    // These might be useful for evaluating spatially varying material
    // properties at the quadrature points.
    const std::vector<Point> & q_points = fe->get_xyz();
    fe->reinit(elem);
    if (hasBlocks(elem->subdomain_id()))
      for (const auto & q : q_points)
        _positions.push_back(q);
  }
  // Remove local duplicates from the vector of positions as transfers will not handle them
  std::sort(_positions.begin(), _positions.end());
  _positions.erase(std::unique(_positions.begin(), _positions.end()), _positions.end());
  // Use the comm from the problem this MultiApp is part of
  libMesh::ParallelObject::comm().allgather(_positions);
  // Remove duplicates occurring at process boundaries
  std::sort(_positions.begin(), _positions.end());
  _positions.erase(std::unique(_positions.begin(), _positions.end()), _positions.end());
  if (_positions.empty())
    mooseError("No positions found for QuadraturePointMultiApp ", _name);
}
finalize()
void MultiApp::finalize () virtual inherited
Method called towards the end of the simulation to execute on final.
Reimplemented in FullSolveMultiApp.
Definition at line 696 of file MultiApp.C.
{
  for (const auto & app_ptr : _apps)
  {
    auto * executioner = app_ptr->getExecutioner();
    mooseAssert(executioner, "Executioner is nullptr");
    executioner->feProblem().execute(EXEC_FINAL);
    executioner->feProblem().outputStep(EXEC_FINAL);
  }
}
finishStep()
void TransientMultiApp::finishStep (bool = false) override virtual inherited
Calls multi-apps executioners' endStep and postStep methods which creates output and advances time (not the time step; see incrementTStep()) among other things.
This method is only called for Picard calculations because for loosely coupled calculations the executioners' endStep and postStep methods are called from solveStep(). This may be called with the optional flag recurse_through_multiapp_levels which may be useful if this method is being called for the final time of program execution
Reimplemented from MultiApp.
Definition at line 580 of file TransientMultiApp.C.
{
  if (!_sub_cycling)
  {
    for (unsigned int i = 0; i < _my_num_apps; i++)
    {
      Transient * ex = _transient_executioners[i];
      ex->endStep();
      ex->postStep();
      if (recurse_through_multiapp_levels)
      {
        ex->feProblem().finishMultiAppStep(EXEC_TIMESTEP_BEGIN,
                                           /*recurse_through_multiapp_levels=*/true);
        ex->feProblem().finishMultiAppStep(EXEC_TIMESTEP_END,
                                           /*recurse_through_multiapp_levels=*/true);
      }
    }
  }
}
firstLocalApp()
unsigned int MultiApp::firstLocalApp () inline inherited
Returns
The global number of the first app on the local processor.
Definition at line 286 of file MultiApp.h.
{ return _first_local_app; }
getBlockCoordSystem()
Moose::CoordinateSystemType BlockRestrictable::getBlockCoordSystem () protected inherited
Check if the blocks this object operates on all have the same coordinate system, and if so return it.
Definition at line 311 of file BlockRestrictable.C.
{
  if (!_blk_mesh)
    mooseError("No mesh available in BlockRestrictable::checkCoordSystem()");
  if (!_blk_feproblem)
    mooseError("No problem available in BlockRestrictable::checkCoordSystem()");
  const auto & subdomains = blockRestricted() ? blockIDs() : meshBlockIDs();
  if (subdomains.empty())
    mooseError("No subdomains found in the problem.");
  // make sure all subdomains are using the same coordinate system
  auto coord_system = _blk_feproblem->getCoordSystem(*subdomains.begin());
  for (auto subdomain : subdomains)
    if (_blk_feproblem->getCoordSystem(subdomain) != coord_system)
      mooseError("This object requires all subdomains to have the same coordinate system.");
  return coord_system;
}
getBoundingBox()
BoundingBox MultiApp::getBoundingBox (unsigned int app, bool displaced_mesh, const MultiAppCoordTransform * coord_transform = nullptr) virtual inherited
Get the BoundingBox for the mesh associated with app The bounding box will be shifted to be in the correct position within the master domain.
If the MultiApp is in an RZ coordinate system the box will be the size it would be if the geometry were 3D (ie if you were to revolve the geometry around the axis to create the 3D geometry).
Parameters
app The global app number you want to get the bounding box for
displaced_mesh True if the bounding box is retrieved for the displaced mesh, other false
coord_transform An optional coordinate transformation object
Definition at line 861 of file MultiApp.C.
{
  if (!_has_an_app)
    mooseError("No app for ", name(), " on processor ", _orig_rank);
  unsigned int local_app = globalAppToLocal(app);
  FEProblemBase & fe_problem_base = _apps[local_app]->getExecutioner()->feProblem();
  MooseMesh & mesh = (displaced_mesh && fe_problem_base.getDisplacedProblem().get() != NULL)
                         ? fe_problem_base.getDisplacedProblem()->mesh()
                         : fe_problem_base.mesh();
  {
    Moose::ScopedCommSwapper swapper(_my_comm);
    if (displaced_mesh)
      _bounding_box[local_app] = MeshTools::create_bounding_box(mesh);
    else
    {
      if (!_has_bounding_box[local_app])
      {
        _bounding_box[local_app] = MeshTools::create_bounding_box(mesh);
        _has_bounding_box[local_app] = true;
      }
    }
  }
  BoundingBox bbox = _bounding_box[local_app];
  Point min = bbox.min();
  min -= _bounding_box_padding;
  Point max = bbox.max();
  max += _bounding_box_padding;
  Point inflation_amount = (max - min) * _inflation;
  Point inflated_min = min - inflation_amount;
  Point inflated_max = max + inflation_amount;
  Point shifted_min = inflated_min;
  Point shifted_max = inflated_max;
  if ((!coord_transform || coord_transform->skipCoordinateCollapsing()) &&
      fe_problem_base.getCoordSystem(*(mesh.meshSubdomains().begin())) == Moose::COORD_RZ)
  {
    // If the problem is RZ then we're going to invent a box that would cover the whole "3D" app
    // FIXME: Assuming all subdomains are the same coordinate system type!
    shifted_min(0) = -inflated_max(0);
    shifted_min(1) = inflated_min(1);
    shifted_min(2) = -inflated_max(0);
    shifted_max(0) = inflated_max(0);
    shifted_max(1) = inflated_max(1);
    shifted_max(2) = inflated_max(0);
  }
  if (coord_transform)
  {
    BoundingBox transformed_bbox(shifted_min, shifted_max);
    transformBoundingBox(transformed_bbox, *coord_transform);
    return transformed_bbox;
  }
  else
  {
    // This is where the app is located.  We need to shift by this amount.
    Point p = position(app);
    // Shift them to the position they're supposed to be
    shifted_min += p;
    shifted_max += p;
    return BoundingBox(shifted_min, shifted_max);
  }
}
getCheckedPointerParam()
template<typename T > T MooseBaseParameterInterface::getCheckedPointerParam (const std::string & name, const std::string & error_string = "") const inherited
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
The template parameter must be a pointer or an error will be thrown.
Definition at line 264 of file MooseBaseParameterInterface.h.
{
  return parameters().getCheckedPointerParam<T>(name, error_string);
}
getCommandLineArgsParamHelper()
std::string MultiApp::getCommandLineArgsParamHelper (unsigned int local_app) protected virtual inherited
Method to aid in getting the "cli_args" parameters.
The method is virtual because it is needed to allow for batch runs within the stochastic tools module, see SamplerFullSolveMultiApp for an example.
Definition at line 1165 of file MultiApp.C.
{
  auto cla = cliArgs();
  mooseAssert(cla.size() || _cli_args_from_file.size(), "There is no commandLine argument \n");
  // Single set of "cli_args" to be applied to all sub apps
  if (cla.size() == 1)
    return cla[0];
  else if (_cli_args_from_file.size() == 1)
    return _cli_args_from_file[0];
  else if (cla.size())
    // Unique set of "cli_args" to be applied to each sub apps
    return cla[local_app + _first_local_app];
  else
    return _cli_args_from_file[local_app + _first_local_app];
}
Referenced by MultiApp::createApp().
getDataFileName()
std::string DataFileInterface< MooseObject >::getDataFileName (const std::string & param) const inherited
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
relative to the input file directory
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
relative to the input file directory
Definition at line 34 of file DataFileInterface.C.
{
  {
    const auto & absolute_path = _parent.template getParam<FileName>(param);
    if (MooseUtils::checkFileReadable(absolute_path, false, false, false))
    {
      _parent.paramInfo(param, "Data file '", absolute_path, "' found relative to the input file.");
      return absolute_path;
    }
  }
  const auto & relative_path = _parent.parameters().rawParamVal(param);
  return getDataFileNameByName(relative_path, &param);
}
getDataFileNameByName()
std::string DataFileInterface< MooseObject >::getDataFileNameByName (const std::string & name, const std::string * param = nullptr) const inherited
Returns the path of a data file for a given relative file path.
This can be used for hardcoded datafile names and will search the same locations as getDataFileName. The optional param pointer can be used to turn the mooseErrors this function emits into paramErrors
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
Definition at line 42 of file DataFileInterface.C.
{
  const auto share_dir = MooseUtils::pathjoin(Moose::getExecutablePath(), "..", "share");
  if (MooseUtils::pathIsDirectory(share_dir))
  {
    const auto dirs = MooseUtils::listDir(share_dir, false);
    for (const auto & data_dir : dirs)
    {
      const auto path = MooseUtils::pathjoin(data_dir, "data", relative_path);
      if (MooseUtils::checkFileReadable(path, false, false, false))
      {
        if (param)
          _parent.paramInfo(
              *param, "Data file '", path, "' found in an installed app distribution.");
        else
          mooseInfo("Data file '", path, "' found in an installed app distribution.");
        return path;
      }
    }
  }
  for (const auto & data_dir : Registry::getRegistry().getDataFilePaths())
  {
    const auto path = MooseUtils::pathjoin(data_dir, relative_path);
    if (MooseUtils::checkFileReadable(path, false, false, false))
    {
      if (param)
        _parent.paramInfo(*param, "Data file '", path, "' found in a source repository.");
      else
        mooseInfo("Data file '", path, "' found in a source repository.");
      return path;
    }
  }
  mooseException(param ? _parent.parameters().inputLocation(*param) : _parent.name(),
                 ": Unable to find data file '",
                 relative_path,
                 "' anywhere");
}
getExecuteOnEnum()
const ExecFlagEnum & SetupInterface::getExecuteOnEnum () const inherited
Return the execute on MultiMooseEnum for this object.
Definition at line 65 of file SetupInterface.C.
{
  return _execute_enum;
}
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), MultiAppTransfer::checkMultiAppExecuteOn(), IntegralPreservingFunctionIC::initialSetup(), MultiAppConservativeTransfer::initialSetup(), Terminator::initialSetup(), ElementReporter::shouldStore(), GeneralReporter::shouldStore(), and NodalReporter::shouldStore().
getExecutioner()
Executioner * MultiApp::getExecutioner (unsigned int app) virtual inherited
Parameters
app The global app number to get the Executioner for
Returns
The Executioner associated with that App.
Definition at line 687 of file MultiApp.C.
{
  if (!_has_an_app)
    mooseError("No app for ", name(), " on processor ", _orig_rank);
  return _apps[globalAppToLocal(app)]->getExecutioner();
}
Referenced by MultiApp::restore().
getMooseApp()
MooseApp & MooseBase::getMooseApp () const inline inherited
Get the MooseApp this class is associated with.
Definition at line 35 of file MooseBase.h.
{ return _app; }
Referenced by ReporterTransferInterface::checkHasReporterValue(), Coupleable::checkWritableVar(), MooseBaseParameterInterface::connectControllableParams(), Coupleable::Coupleable(), MortarData::createMortarInterface(), EigenProblem::doFreeNonlinearPowerIterations(), Terminator::execute(), FEProblemSolve::FEProblemSolve(), SolutionInvalidInterface::flagInvalidSolutionInternal(), MaterialPropertyInterface::MaterialPropertyInterface(), MooseVariableDataFV< OutputType >::MooseVariableDataFV(), ProgressOutput::output(), MooseBaseParameterInterface::paramError(), PetscOutputInterface::petscLinearOutput(), PetscOutputInterface::petscNonlinearOutput(), PetscOutputInterface::PetscOutputInterface(), PostprocessorInterface::postprocessorsAdded(), MultiApp::preTransfer(), Reporter::Reporter(), ReporterInterface::reportersAdded(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
getMultiAppName()
std::string MultiApp::getMultiAppName (const std::string & base_name, dof_id_type index, dof_id_type total) static protected inherited
Helper for constructing the name of the multiapp.
Parameters
base_name The base name of the multiapp, usually name()
index The index of the app
total The total number of apps, which is used to pad the name with zeros
Returns
std::string The name of the multiapp
Definition at line 1349 of file MultiApp.C.
{
  std::ostringstream multiapp_name;
  multiapp_name << base_name << std::setw(std::ceil(std::log10(total))) << std::setprecision(0)
                << std::setfill('0') << std::right << index;
  return multiapp_name.str();
}
Referenced by MultiApp::createApp(), and MultiApp::setAppOutputFileBase().
getParam() [1/2]
template<typename T > const T & MooseBaseParameterInterface::getParam (const std::string & name) const inherited
Retrieve a parameter for the object.
Parameters
name The name of the parameter
Returns
The value of the parameter
Definition at line 200 of file MooseBaseParameterInterface.h.
{
  return InputParameters::getParamHelper(name, _pars, static_cast<T *>(0));
}
Referenced by AddGeneralReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddPeriodicBCAction::act(), CreateDisplacedProblemAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), ConstraintWarehouse::addObject(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), ADNodalKernel::ADNodalKernel(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), PiecewiseTabularBase::buildFromJSON(), Console::Console(), FEProblemBase::createTagSolutions(), AccumulateReporter::declareLateValues(), DerivativeParsedMaterialTempl< is_ad >::DerivativeParsedMaterialTempl(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EigenKernel::EigenKernel(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), GenericConstantRankTwoTensorTempl< is_ad >::GenericConstantRankTwoTensorTempl(), MooseApp::getCheckpointDirectories(), ExecutorInterface::getExecutor(), AdvancedOutput::init(), IterationAdaptiveDT::init(), TimeSequenceStepper::init(), AttribThread::initFrom(), AttribSysNum::initFrom(), AttribResidualObject::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), Console::initialSetup(), IterationAdaptiveDT::limitDTToPostprocessorValue(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MortarConsumerInterface::MortarConsumerInterface(), NestedDivision::NestedDivision(), ConsoleUtils::outputExecutionInformation(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedMaterialTempl< is_ad >::ParsedMaterialTempl(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), ParsedODEKernel::ParsedODEKernel(), ParsedPostprocessor::ParsedPostprocessor(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), Moose::FV::setInterpolationMethod(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), TimePeriod::TimePeriod(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and VectorOfPostprocessors::VectorOfPostprocessors().
getParam() [2/2]
template<typename T1 , typename T2 > std::vector< std::pair< T1, T2 > > MooseBaseParameterInterface::getParam (const std::string & param1, const std::string & param2) const inherited
Retrieve two parameters and provide pair of parameters for the object.
Parameters
param1 The name of first parameter
param2 The name of second parameter
Returns
Vector of pairs of first and second parameters
Definition at line 257 of file MooseBaseParameterInterface.h.
{
  return _pars.get<T1, T2>(param1, param2);
}
getRenamedParam()
template<typename T > const T & MooseBaseParameterInterface::getRenamedParam (const std::string & old_name, const std::string & new_name) const inherited
Retrieve a renamed parameter for the object.
This helper makes sure we check both names before erroring, and that only one parameter is passed to avoid silent errors
Parameters
old_name the old name for the parameter
new_name the new name for the parameter
Definition at line 207 of file MooseBaseParameterInterface.h.
{
  // this enables having a default on the new parameter but bypassing it with the old one
  // Most important: accept new parameter
  if (isParamSetByUser(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Second most: accept old parameter
  else if (isParamValid(old_name) && !isParamSetByUser(new_name))
    return InputParameters::getParamHelper(old_name, _pars, static_cast<T *>(0));
  // Third most: accept default for new parameter
  else if (isParamValid(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Refuse: no default, no value passed
  else if (!isParamValid(old_name) && !isParamValid(new_name))
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' is being retrieved without being set.\n"
               "Did you misspell it?");
  // Refuse: both old and new parameters set by user
  else
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' may not be provided alongside former parameter '" + old_name + "'");
}
getRestartableData()
template<typename T , typename... Args> const T & Restartable::getRestartableData (const std::string & data_name) const protected inherited
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
Forwarded arguments are not allowed in this case because we assume that the object is restarted and we won't need different constructors to initialize it.
NOTE: This returns a const reference! Make sure you store it in a const reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
Definition at line 287 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, nullptr).get();
}
globalAppToLocal()
unsigned int MultiApp::globalAppToLocal (unsigned int global_app) protected inherited
Map a global App number to the local number.
Note: This will error if given a global number that doesn't map to a local number.
Parameters
global_app The global app number.
Returns
The local app number.
Definition at line 1304 of file MultiApp.C.
{
  if (global_app >= _first_local_app && global_app <= _first_local_app + (_my_num_apps - 1))
    return global_app - _first_local_app;
  std::stringstream ss;
  ss << "Requesting app " << global_app << ", but processor " << processor_id() << " ";
  if (_my_num_apps == 0)
    ss << "does not own any apps";
  else if (_my_num_apps == 1)
    ss << "owns app " << _first_local_app;
  else
    ss << "owns apps " << _first_local_app << "-" << _first_local_app + (_my_num_apps - 1);
  ss << ".";
  mooseError("Invalid global_app!\n", ss.str());
  return 0;
}
Referenced by MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::createApps(), MultiApp::getBoundingBox(), MultiApp::getExecutioner(), MultiApp::moveApp(), TransientMultiApp::resetApp(), and MultiApp::resetApp().
hasApp()
bool MultiApp::hasApp () inline inherited
Whether or not this MultiApp has an app on this processor.
Definition at line 296 of file MultiApp.h.
{ return _has_an_app; }
hasBlockMaterialProperty()
template<typename T , bool is_ad> bool BlockRestrictable::hasBlockMaterialProperty (const std::string & prop_name) inherited
Check if a material property is valid for all blocks of this object.
This method returns true if the supplied property name has been declared in a Material object on the block ids for this object.
Template Parameters
T The type of material property
Parameters
prop_name the name of the property to query
Returns
true if the property exists for all block ids of the object, otherwise false
See also
Material::hasBlockMaterialProperty
Definition at line 264 of file BlockRestrictable.h.
{
  mooseAssert(_blk_material_data != NULL, "MaterialData pointer is not defined");
  return hasBlockMaterialPropertyHelper(prop_name) &&
         _blk_material_data->haveGenericProperty<T, is_ad>(prop_name);
}
hasBlockMaterialPropertyHelper()
bool BlockRestrictable::hasBlockMaterialPropertyHelper (const std::string & prop_name) protected virtual inherited
A helper method to allow the Material object to specialize the behavior of hasBlockMaterialProperty.
It also avoid circular #include problems.
See also
hasBlockMaterialProperty
Definition at line 275 of file BlockRestrictable.C.
{
  // Reference to MaterialWarehouse for testing and retrieving block ids
  const MaterialWarehouse & warehouse = _blk_feproblem->getMaterialWarehouse();
  // Complete set of ids that this object is active
  const std::set<SubdomainID> & ids = blockRestricted() ? blockIDs() : meshBlockIDs();
  // Loop over each id for this object
  for (const auto & id : ids)
  {
    // Storage of material properties that have been DECLARED on this id
    std::set<std::string> declared_props;
    // If block materials exist, populated the set of properties that were declared
    if (warehouse.hasActiveBlockObjects(id))
    {
      const std::vector<std::shared_ptr<MaterialBase>> & mats = warehouse.getActiveBlockObjects(id);
      for (const auto & mat : mats)
      {
        const std::set<std::string> & mat_props = mat->getSuppliedItems();
        declared_props.insert(mat_props.begin(), mat_props.end());
      }
    }
    // If the supplied property is not in the list of properties on the current id, return false
    if (declared_props.find(prop_name) == declared_props.end())
      return false;
  }
  // If you get here the supplied property is defined on all blocks
  return true;
}
Referenced by BlockRestrictable::hasBlockMaterialProperty().
hasBlocks() [1/5]
bool BlockRestrictable::hasBlocks (const std::set< SubdomainID > & ids) const inherited
Test if the supplied set of block ids are valid for this object.
Parameters
ids A std::set of SubdomainIDs to check
Returns
True if all of the given ids are found within the ids for this object
See also
isSubset
Definition at line 237 of file BlockRestrictable.C.
{
  if (_blk_ids.empty() || _blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return true;
  else
    return std::includes(_blk_ids.begin(), _blk_ids.end(), ids.begin(), ids.end());
}
hasBlocks() [2/5]
bool BlockRestrictable::hasBlocks (const std::vector< SubdomainID > & ids) const inherited
Test if the supplied vector block ids are valid for this object.
Parameters
ids A vector of SubdomainIDs ids to check
Returns
True if all of the given ids are found within the ids for this object
Definition at line 230 of file BlockRestrictable.C.
{
  std::set<SubdomainID> ids_set(ids.begin(), ids.end());
  return hasBlocks(ids_set);
}
hasBlocks() [3/5]
bool BlockRestrictable::hasBlocks (const std::vector< SubdomainName > & names) const inherited
Test if the supplied vector of block names are valid for this object.
Parameters
names A vector of SubdomainNames to check
Returns
True if the given ids are valid for this object
Definition at line 215 of file BlockRestrictable.C.
{
  return hasBlocks(_blk_mesh->getSubdomainIDs(names));
}
hasBlocks() [4/5]
bool BlockRestrictable::hasBlocks (const SubdomainName & name) const inherited
Test if the supplied block name is valid for this object.
Parameters
name A SubdomainName to check
Returns
True if the given id is valid for this object
Definition at line 205 of file BlockRestrictable.C.
{
  // Create a vector and utilize the getSubdomainIDs function, which
  // handles the ANY_BLOCK_ID (getSubdomainID does not)
  std::vector<SubdomainName> names(1);
  names[0] = name;
  return hasBlocks(_blk_mesh->getSubdomainIDs(names));
}
Referenced by DiracKernelBase::addPoint(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), DomainUserObject::checkVariable(), ComputeJacobianThread::compute(), DomainUserObject::DomainUserObject(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), ExtraIDIntegralVectorPostprocessor::execute(), MeshDivisionFunctorReductionVectorPostprocessor::execute(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), CentroidMultiApp::fillPositions(), fillPositions(), MooseVariableField< OutputType >::hasBlocks(), BlockRestrictable::hasBlocks(), FVFluxKernel::hasFaceSide(), and PointwiseRenormalizeVector::PointwiseRenormalizeVector().
hasBlocks() [5/5]
bool BlockRestrictable::hasBlocks (SubdomainID id) const inherited
Test if the supplied block ids are valid for this object.
Parameters
id A SubdomainID to check
Returns
True if the given id is valid for this object
Definition at line 221 of file BlockRestrictable.C.
{
  if (_blk_ids.empty() || _blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return true;
  else
    return _blk_ids.find(id) != _blk_ids.end();
}
hasLocalApp()
bool MultiApp::hasLocalApp (unsigned int global_app) const inherited
Whether or not the given global app number is on this processor.
Parameters
global_app The global app number in question
Returns
True if the global app is on this processor
Definition at line 989 of file MultiApp.C.
{
  if (_has_an_app && global_app >= _first_local_app &&
      global_app <= _first_local_app + (_my_num_apps - 1))
    return true;
  return false;
}
Referenced by MultiApp::createApps(), MultiApp::moveApp(), TransientMultiApp::resetApp(), and MultiApp::resetApp().
incrementTStep()
void TransientMultiApp::incrementTStep (Real) override virtual inherited
Advances the multi-apps time step which is important for dt selection.
(Note this does not advance the time. That is done in Transient::endStep, which is called either directly from solveStep() for loose coupling cases or through finishStep() for Picard coupling cases)
Reimplemented from MultiApp.
Definition at line 560 of file TransientMultiApp.C.
{
  if (!_sub_cycling)
  {
    for (unsigned int i = 0; i < _my_num_apps; i++)
    {
      Transient * ex = _transient_executioners[i];
      // The App might have a different local time from the rest of the problem
      Real app_time_offset = _apps[i]->getGlobalTimeOffset();
      // Only increment the step if we are after (target_time) the
      // start_time (added to app_time_offset) of this sub_app.
      if (_apps[i]->getStartTime() + app_time_offset < target_time)
        ex->incrementStepOrReject();
    }
  }
}
init() [1/2]
void MultiApp::init (unsigned int num_apps, bool batch_mode = false) protected inherited
Build communicators and reserve backups.
Definition at line 313 of file MultiApp.C.
{
  auto config = rankConfig(
      processor_id(), n_processors(), num_apps, _min_procs_per_app, _max_procs_per_app, batch_mode);
  init(num_apps, config);
}
Referenced by MultiApp::init(), and MultiApp::setupPositions().
init() [2/2]
void MultiApp::init (unsigned int num_apps, const LocalRankConfig & config) protected inherited
Same as other init method, except defining a custom rank configuration.
Definition at line 321 of file MultiApp.C.
{
  TIME_SECTION(_init_timer);
  _total_num_apps = num_apps;
  _rank_config = config;
  buildComm();
  _sub_app_backups.resize(_my_num_apps);
  _has_bounding_box.resize(_my_num_apps, false);
  _reset_happened.resize(_reset_times.size(), false);
  _bounding_box.resize(_my_num_apps);
  if ((_cli_args.size() > 1) && (_total_num_apps != _cli_args.size()))
    paramError("cli_args",
               "The number of items supplied must be 1 or equal to the number of sub apps.");
  // if cliArgs() != _cli_args, then cliArgs() was overridden and we need to check it
  auto cla = cliArgs();
  if (cla != std::vector<std::string>(_cli_args.begin(), _cli_args.end()))
  {
    if ((cla.size() > 1) && (_total_num_apps != cla.size()))
      mooseError("The number of items supplied as command line argument to subapps must be 1 or "
                 "equal to the number of sub apps. Note: you use a multiapp that provides its own "
                 "command line parameters so the error is not in cli_args");
  }
}
initializeBlockRestrictable()
void BlockRestrictable::initializeBlockRestrictable (const MooseObject * moose_object) protected inherited
An initialization routine needed for dual constructors.
Definition at line 74 of file BlockRestrictable.C.
{
  // If the mesh pointer is not defined, but FEProblemBase is, get it from there
  if (_blk_feproblem != NULL && _blk_mesh == NULL)
    _blk_mesh = &_blk_feproblem->mesh();
  // Check that the mesh pointer was defined, it is required for this class to operate
  if (_blk_mesh == NULL)
    mooseError("The input parameters must contain a pointer to FEProblem via '_fe_problem' or a "
               "pointer to the MooseMesh via '_mesh'");
  // Populate the MaterialData pointer
  if (_blk_feproblem != NULL)
    _blk_material_data = &_blk_feproblem->getMaterialData(Moose::BLOCK_MATERIAL_DATA, _blk_tid);
  // The 'block' input is defined
  if (moose_object->isParamValid("block"))
  {
    // Extract the blocks from the input
    _blocks = moose_object->getParam<std::vector<SubdomainName>>("block");
    // Store the IDs in a set, handling ANY_BLOCK_ID if supplied
    if (std::find(_blocks.begin(), _blocks.end(), "ANY_BLOCK_ID") != _blocks.end())
      _blk_ids.insert(Moose::ANY_BLOCK_ID);
    else
    {
      // Get the IDs from the supplied names
      _vec_ids = _blk_mesh->getSubdomainIDs(_blocks);
      _blk_ids.insert(_vec_ids.begin(), _vec_ids.end());
    }
  }
  // When 'blocks' is not set and there is a "variable", use the blocks from the variable
  else if (moose_object->isParamValid("variable"))
  {
    std::string variable_name = moose_object->parameters().getMooseType("variable");
    if (!variable_name.empty())
      _blk_ids = _blk_feproblem
                     ->getVariable(_blk_tid,
                                   variable_name,
                                   Moose::VarKindType::VAR_ANY,
                                   Moose::VarFieldType::VAR_FIELD_ANY)
                     .activeSubdomains();
  }
  // Produce error if the object is not allowed to be both block and boundary restricted
  if (!_blk_dual_restrictable && !_boundary_ids.empty() && !_boundary_ids.empty())
    if (!_boundary_ids.empty() && _boundary_ids.find(Moose::ANY_BOUNDARY_ID) == _boundary_ids.end())
      moose_object->paramError("block",
                               "Attempted to restrict the object '",
                               _blk_name,
                               "' to a block, but the object is already restricted by boundary");
  // If no blocks were defined above, specify that it is valid on all blocks
  if (_blk_ids.empty() && !moose_object->isParamValid("boundary"))
  {
    _blk_ids.insert(Moose::ANY_BLOCK_ID);
    _blocks = {"ANY_BLOCK_ID"};
  }
  // If this object is block restricted, check that defined blocks exist on the mesh
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) == _blk_ids.end())
  {
    const std::set<SubdomainID> & valid_ids = _blk_mesh->meshSubdomains();
    std::vector<SubdomainID> diff;
    std::set_difference(_blk_ids.begin(),
                        _blk_ids.end(),
                        valid_ids.begin(),
                        valid_ids.end(),
                        std::back_inserter(diff));
    if (!diff.empty())
    {
      std::ostringstream msg;
      auto sep = " ";
      msg << "the following blocks (ids) do not exist on the mesh:";
      for (const auto & id : diff)
      {
        if (_blk_name.size() > 0)
        {
          auto & name =
              _blocks.at(std::find(_vec_ids.begin(), _vec_ids.end(), id) - _vec_ids.begin());
          if (std::to_string(id) != name)
            msg << sep << name << " (" << id << ")";
          else
            msg << sep << id;
        }
        else
          msg << sep << id;
        sep = ", ";
      }
      moose_object->paramError("block", msg.str());
    }
  }
  // Get the mesh dimension for the blocks
  if (blockRestricted())
    _blk_dim = _blk_mesh->getBlocksMaxDimension(_blocks);
  else
    _blk_dim = _blk_mesh->dimension();
}
Referenced by BlockRestrictable::BlockRestrictable().
initialSetup()
void TransientMultiApp::initialSetup () override virtual inherited
Method to be called in main-app initial setup for create sub-apps if using positions is false.
Reimplemented from MultiApp.
Definition at line 162 of file TransientMultiApp.C.
{
  MultiApp::initialSetup();
  if (!_has_an_app)
    return;
  Moose::ScopedCommSwapper swapper(_my_comm);
  if (_has_an_app)
  {
    _transient_executioners.resize(_my_num_apps);
    // Grab Transient Executioners from each app
    for (unsigned int i = 0; i < _my_num_apps; i++)
      setupApp(i);
  }
}
isBlockSubset() [1/2]
bool BlockRestrictable::isBlockSubset (const std::set< SubdomainID > & ids) const inherited
Test if the class block ids are a subset of the supplied objects.
Parameters
ids A std::set of Subdomains to check
Returns
True if all of the block ids for this class are found within the given ids (opposite of hasBlocks)
See also
hasBlocks
Definition at line 246 of file BlockRestrictable.C.
{
  // An empty input is assumed to be ANY_BLOCK_ID
  if (ids.empty() || ids.find(Moose::ANY_BLOCK_ID) != ids.end())
    return true;
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return std::includes(ids.begin(),
                         ids.end(),
                         _blk_mesh->meshSubdomains().begin(),
                         _blk_mesh->meshSubdomains().end());
  else
    return std::includes(ids.begin(), ids.end(), _blk_ids.begin(), _blk_ids.end());
}
Referenced by BlockRestrictable::checkVariable(), BlockRestrictable::isBlockSubset(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), and ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux().
isBlockSubset() [2/2]
bool BlockRestrictable::isBlockSubset (const std::vector< SubdomainID > & ids) const inherited
Test if the class block ids are a subset of the supplied objects.
Parameters
ids A std::vector of Subdomains to check
Returns
True if all of the block ids for this class are found within the given ids (opposite of hasBlocks)
See also
hasBlocks
Definition at line 262 of file BlockRestrictable.C.
{
  std::set<SubdomainID> ids_set(ids.begin(), ids.end());
  return isBlockSubset(ids_set);
}
isFirstLocalRank()
bool MultiApp::isFirstLocalRank () const inherited
Returns
Whether this rank is the first rank of the subapp(s) it's involved in
Definition at line 983 of file MultiApp.C.
{
  return _rank_config.is_first_local_rank;
}
isParamSetByUser()
bool MooseBaseParameterInterface::isParamSetByUser (const std::string & nm) const inline inherited
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
Parameters
nm The name of the parameter to test
Definition at line 108 of file MooseBaseParameterInterface.h.
{ return _pars.isParamSetByUser(nm); }
Referenced by SetAdaptivityOptionsAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), LibtorchNeuralNetControl::conditionalParameterError(), MooseBaseParameterInterface::getRenamedParam(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), PiecewiseTabularBase::PiecewiseTabularBase(), MooseMesh::prepare(), and SolutionUserObject::readXda().
isParamValid()
bool MooseBaseParameterInterface::isParamValid (const std::string & name) const inline inherited
Test if the supplied parameter is valid.
Parameters
name The name of the parameter to test
Definition at line 102 of file MooseBaseParameterInterface.h.
{ return _pars.isParamValid(name); }
Referenced by AddDriftDiffusionAction::act(), AddSpecies::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CopyNodalVarsAction::act(), CreateDisplacedProblemAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), AddGeneralReactions::AddGeneralReactions(), AddZapdosReactions::AddZapdosReactions(), AdvectiveFluxAux::AdvectiveFluxAux(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), GeneratedMesh::buildMesh(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), ChemicalReactionsBase::ChemicalReactionsBase(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), CombinerGenerator::CombinerGenerator(), CSVReader::CSVReader(), ConstantReporter::declareConstantReporterValues(), DGKernelBase::DGKernelBase(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EEDFEnergyTownsendLog::EEDFEnergyTownsendLog(), Eigenvalue::Eigenvalue(), ElectronEnergyTermRate::ElectronEnergyTermRate(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), PIDTransientControl::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FileOutput::FileOutput(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FunctionDT::FunctionDT(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getRenamedParam(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), Terminator::handleMessage(), HeavySpeciesTempl< is_ad >::HeavySpeciesTempl(), HFEMDirichletBC::HFEMDirichletBC(), EigenExecutionerBase::init(), Eigenvalue::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), MooseParsedFunction::initialSetup(), MooseParsedGradFunction::initialSetup(), MooseParsedVectorFunction::initialSetup(), PiecewiseTabularBase::initialSetup(), SolutionFunction::initialSetup(), Console::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), IterationAdaptiveDT::IterationAdaptiveDT(), LeastSquaresFit::LeastSquaresFit(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MatCoupledForce::MatCoupledForce(), MooseMesh::MooseMesh(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarConsumerInterface::MortarConsumerInterface(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalExtremeValue::NodalExtremeValue(), EigenExecutionerBase::normalizeSolution(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PetscOutput::PetscOutput(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), PicardSolve::PicardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseTabularBase::PiecewiseTabularBase(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), MooseMesh::prepare(), MultiApp::readCommandLineArguments(), SolutionUserObject::readExodusII(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), MooseMesh::setCoordSystem(), FileOutput::setFileBase(), FileOutput::setFileBaseInternal(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SideDiffusiveFluxIntegralTempl< is_ad, T >::SideDiffusiveFluxIntegralTempl(), SideExtremeValue::SideExtremeValue(), SolutionUserObject::SolutionUserObject(), Terminator::Terminator(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), MultiAppDofCopyTransfer::transfer(), TransformGenerator::TransformGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
isRootProcessor()
bool MultiApp::isRootProcessor () inline inherited
Whether or not this processor is the "root" processor for the sub communicator.
The "root" processor has rank 0 in the sub communicator
Definition at line 356 of file MultiApp.h.
{ return _my_rank == 0; }
jacobianSetup()
void SetupInterface::jacobianSetup () virtual inherited
Gets called just before the Jacobian is computed and before this object is asked to do its job.
Reimplemented in EqualValueEmbeddedConstraint, Function, ADKernelTempl< T >, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 50 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::jacobianSetup(), and ComputeFVFluxJacobianThread< RangeType >::setup().
keepSolutionDuringRestore()
void MultiApp::keepSolutionDuringRestore (bool keep_solution_during_restore) protected inherited
Reserve the solution from the previous simulation, and it is used as an initial guess for the next run.
Definition at line 811 of file MultiApp.C.
{
  if (_pars.isParamSetByUser("keep_solution_during_restore"))
    paramError("keep_solution_during_restore",
               "This parameter should only be provided in parent app");
  _keep_solution_during_restore = keep_solution_during_restore;
}
localApp()
MooseApp * MultiApp::localApp (unsigned int local_app) inherited
Get the local MooseApp object.
Parameters
local_app The local app number
Definition at line 999 of file MultiApp.C.
{
  mooseAssert(local_app < _apps.size(), "Index out of range: " + Moose::stringify(local_app));
  return _apps[local_app].get();
}
meshBlockIDs()
const std::set< SubdomainID > & BlockRestrictable::meshBlockIDs () const inherited
Return all of the SubdomainIDs for the mesh.
Returns
A set of all subdomians for the entire mesh
Definition at line 269 of file BlockRestrictable.C.
{
  return _blk_mesh->meshSubdomains();
}
Referenced by BlockRestrictable::checkVariable(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), and SolutionIC::initialSetup().
mooseDeprecated()
template<typename... Args> void MooseBaseErrorInterface::mooseDeprecated (Args &&... args) const inline inherited
Definition at line 78 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseDeprecatedStream(_console, false, true, std::forward<Args>(args)...);
  }
Referenced by FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::advanceMultiApps(), MultiApp::appProblem(), Executioner::augmentedPicardConvergenceCheck(), MooseMesh::buildSideList(), FEProblemBase::computeResidual(), AddVariableAction::determineType(), Eigenvalue::Eigenvalue(), MooseMesh::elem(), FunctionDT::FunctionDT(), RandomICBase::generateRandom(), MooseMesh::getBoundariesToElems(), Control::getExecuteOptions(), FEProblemBase::getNonlinearSystem(), FEProblemBase::getUserObjects(), FEProblemBase::hasPostprocessor(), MooseMesh::node(), FixedPointSolve::numPicardIts(), RelationshipManager::operator>=(), Executioner::picardSolve(), and MooseMesh::setBoundaryToNormalMap().
mooseError()
template<typename... Args> void MooseBaseErrorInterface::mooseError (Args &&... args) const inline inherited
Emits an error prefixed with object name and type.
Definition at line 38 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, errorPrefix("error"), std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
Referenced by HierarchicalGridPartitioner::_do_partition(), PetscExternalPartitioner::_do_partition(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AdaptivityAction::act(), AddFVICAction::act(), AddICAction::act(), AddMeshGeneratorAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVectorPostprocessorAction::act(), CheckFVBCAction::act(), CheckIntegrityAction::act(), CommonOutputAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DeprecatedBlockAction::act(), InitProblemAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetAdaptivityOptionsAction::act(), SetupMeshAction::act(), SetupMeshCompleteAction::act(), SetupPredictorAction::act(), SetupTimeStepperAction::act(), SplitMeshAction::act(), FEProblemBase::adaptMesh(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::addConstraint(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFVInitialCondition(), AddGeneralReactions::AddGeneralReactions(), FEProblemBase::addInitialCondition(), FEProblemBase::addLineSearch(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addOutput(), SubProblem::addPiecewiseByBlockLambdaFunctor(), DistributedRectilinearMeshGenerator::addPoint(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), FEProblemBase::addPostprocessor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseMesh::addQuadratureNode(), FEProblemBase::addReporter(), AddVariableAction::addVariable(), FEProblemBase::addVectorPostprocessor(), SubProblem::addVectorTag(), AddZapdosReactions::AddZapdosReactions(), ADEEDFRateConstantTownsend::ADEEDFRateConstantTownsend(), ADGasElectronMoments::ADGasElectronMoments(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), MooseVariableScalar::adUDot(), Output::advancedExecuteOn(), AdvectiveFluxAux::AdvectiveFluxAux(), ADZapdosEEDFRateConstant::ADZapdosEEDFRateConstant(), MooseVariableBase::allDofIndices(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayConstantIC::ArrayConstantIC(), ArrayFunctionIC::ArrayFunctionIC(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), Function::average(), Axisymmetric2D3DSolutionFunction::Axisymmetric2D3DSolutionFunction(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), BoltzmannSolverScalar::BoltzmannSolverScalar(), BoundingValueElementDamper::BoundingValueElementDamper(), BoundingValueNodalDamper::BoundingValueNodalDamper(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), MooseMesh::buildCoarseningMap(), MultiApp::buildComm(), DistributedRectilinearMeshGenerator::buildCube(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), PiecewiseTabularBase::buildFromXY(), MooseMesh::buildLowerDMesh(), GeneratedMesh::buildMesh(), MeshGeneratorMesh::buildMesh(), SpiralAnnularMesh::buildMesh(), TiledMesh::buildMesh(), ImageMesh::buildMesh3D(), ImageMeshGenerator::buildMesh3D(), MooseMesh::buildRefinementMap(), MaterialBase::buildRequiredMaterials(), MooseMesh::buildSideList(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), UserObjectInterface::castUserObject(), EigenExecutionerBase::chebyshev(), SubProblem::checkBlockMatProps(), SubProblem::checkBoundaryMatProps(), MooseMesh::checkCoordinateSystems(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkDisplacementOrders(), FEProblemBase::checkDuplicatePostprocessorVariableNames(), MooseMesh::checkDuplicateSubdomainNames(), MaterialBase::checkExecutionStage(), MeshGenerator::checkGetMesh(), ReporterTransferInterface::checkHasReporterValue(), FEProblemBase::checkICRestartError(), EigenExecutionerBase::checkIntegrity(), Eigenvalue::checkIntegrity(), Steady::checkIntegrity(), ExplicitTimeIntegrator::checkLinearConvergence(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), PostprocessorInterface::checkParam(), FEProblemBase::checkProblemIntegrity(), Sampler::checkReinitStatus(), MaterialBase::checkStatefulSanity(), FEProblemBase::checkUserObjects(), MultiAppTransfer::checkVariable(), DomainUserObject::checkVariable(), ChemicalReactionsBase::ChemicalReactionsBase(), MooseMesh::clone(), LibmeshPartitioner::clone(), CombinerGenerator::CombinerGenerator(), ElementSubdomainModifier::complementMovingBoundaryID(), ElementSubdomainModifier::complementMovingBoundaryName(), MooseVariableFieldBase::componentName(), CompositeFunction::CompositeFunction(), NodalPatchRecovery::compute(), VariableCondensationPreconditioner::computeDInverseDiag(), CompositionDT::computeDT(), MooseVariableFieldBase::computeFaceValues(), TimeStepper::computeFailedDT(), IterationAdaptiveDT::computeFailedDT(), TimeSequenceStepperBase::computeFailedDT(), MooseMesh::computeFiniteVolumeCoords(), FVFluxKernel::computeJacobian(), ArrayKernel::computeJacobian(), ArrayKernel::computeOffDiagJacobian(), FVElementalKernel::computeOffDiagJacobian(), MaterialBase::computeProperties(), ScalarKernel::computeQpJacobian(), ScalarKernel::computeQpResidual(), FVFluxKernel::computeResidual(), ArrayKernel::computeResidual(), FVFluxBC::computeResidual(), ResidualObject::computeResidualAndJacobian(), FVFluxKernel::computeResidualAndJacobian(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualL2Norm(), FEProblemBase::computeResidualTag(), FEProblemBase::computeResidualType(), TimeStepper::computeStep(), ActuallyExplicitEuler::computeTimeDerivatives(), AStableDirk4::computeTimeDerivatives(), BDF2::computeTimeDerivatives(), CrankNicolson::computeTimeDerivatives(), ExplicitEuler::computeTimeDerivatives(), ExplicitRK2::computeTimeDerivatives(), ExplicitTVDRK2::computeTimeDerivatives(), ImplicitEuler::computeTimeDerivatives(), ImplicitMidpoint::computeTimeDerivatives(), LStableDirk2::computeTimeDerivatives(), LStableDirk3::computeTimeDerivatives(), LStableDirk4::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), FEProblemBase::computeUserObjectsInternal(), BolsigValueScalar::computeValue(), PenetrationAux::computeValue(), BuildArrayVariableAux::computeValue(), TagVectorArrayVariableAux::computeValue(), ConcentricCircleMesh::ConcentricCircleMesh(), ConditionalEnableControl::ConditionalEnableControl(), TimeStepper::constrainStep(), LibtorchNeuralNetControl::controlNeuralNet(), AddVariableAction::createInitialConditionAction(), DataRead::DataRead(), ReporterTransferInterface::declareClone(), MeshGenerator::declareMeshProperty(), ReporterTransferInterface::declareVectorClone(), FunctorRelationshipManager::delete_remote_elements(), MooseMesh::deleteRemoteElements(), BicubicSplineFunction::derivative(), MooseMesh::detectPairedSidesets(), FEProblemBase::determineNonlinearSystem(), MeshDiagnosticsGenerator::diagnosticsLog(), DiffusionRateTemp::DiffusionRateTemp(), FunctorBinnedValuesDivision::divisionIndex(), FunctorRelationshipManager::dofmap_reinit(), FEProblemBase::duplicateVariableCheck(), EEDFRateConstant::EEDFRateConstant(), EEDFRateConstantTownsend::EEDFRateConstantTownsend(), Eigenvalue::Eigenvalue(), ElectricField::ElectricField(), ElectronMobility::ElectronMobility(), ElementIntegerAux::ElementIntegerAux(), ElementQualityAux::ElementQualityAux(), ElementUOAux::ElementUOAux(), DistributedRectilinearMeshGenerator::elemId(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), MooseMesh::errorIfDistributedMesh(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), BoltzmannSolverScalar::execute(), Eigenvalue::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), ElementQualityChecker::execute(), DiscreteElementUserObject::execute(), DomainUserObject::execute(), FEProblemBase::execute(), FEProblemBase::executeControls(), MultiAppVectorPostprocessorTransfer::executeFromMultiapp(), MultiAppVectorPostprocessorTransfer::executeToMultiapp(), ExplicitSSPRungeKutta::ExplicitSSPRungeKutta(), FileOutput::FileOutput(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), fillPositions(), ElementQualityChecker::finalize(), VerifyElementUniqueID::finalize(), VerifyNodalUniqueID::finalize(), DiscreteElementUserObject::finalize(), Transfer::find_sys(), BreakMeshByBlockGeneratorBase::findFreeBoundaryId(), FunctionDT::FunctionDT(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), GapValueAux::GapValueAux(), Gas::Gas(), GasBase::GasBase(), GasElectronMoments::GasElectronMoments(), AllSideSetsByNormalsGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundingBoxNodeSetGenerator::generate(), BreakMeshByBlockGenerator::generate(), CombinerGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshCollectionGenerator::generate(), MeshDiagnosticsGenerator::generate(), MeshExtruderGenerator::generate(), MeshRepairGenerator::generate(), MoveNodeGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), SideSetsFromNormalsGenerator::generate(), SideSetsFromPointsGenerator::generate(), SmoothMeshGenerator::generate(), SpiralAnnularMeshGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), TiledMeshGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GeneratedMesh::GeneratedMesh(), GeneratedMeshGenerator::GeneratedMeshGenerator(), MeshGenerator::generateInternal(), CircularBoundaryCorrectionGenerator::generateRadialCorrectionFactor(), RandomICBase::generateRandom(), GenericConstantMaterialTempl< is_ad >::GenericConstantMaterialTempl(), GenericConstantVectorMaterialTempl< is_ad >::GenericConstantVectorMaterialTempl(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), DisplacedProblem::getActualFieldVariable(), FEProblemBase::getActualFieldVariable(), DisplacedProblem::getArrayVariable(), FEProblemBase::getArrayVariable(), MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::getBlockConnectedBlocks(), VariableOldValueBoundsAux::getBound(), MooseMesh::getBoundaryID(), MultiApp::getBoundingBox(), MooseMesh::getCoarseningMap(), MooseVariableBase::getContinuity(), Control::getControllableParameterByName(), MooseMesh::getCoordSystem(), PropertyReadFile::getData(), TransfiniteMeshGenerator::getDiscreteEdge(), FEProblemBase::getDistribution(), MooseVariableBase::getDofIndices(), VariableCondensationPreconditioner::getDofToCondense(), TransfiniteMeshGenerator::getEdge(), GhostingUserObject::getElementalValue(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), PropertyReadFile::getElementData(), MooseMesh::getElementIDIndex(), Material::getElementIDNeighbor(), Material::getElementIDNeighborByName(), MooseMesh::getElemIDMapping(), MooseMesh::getElemIDsOnBlocks(), MultiAppFieldTransfer::getEquationSystem(), MultiApp::getExecutioner(), MultiAppTransfer::getFromMultiApp(), MultiAppTransfer::getFromMultiAppInfo(), FEProblemBase::getFunction(), SubProblem::getFunctor(), MooseMesh::getGeneralAxisymmetricCoordAxis(), DistributedRectilinearMeshGenerator::getGhostNeighbors(), BatchMaterial< Tuple, Output, Input >::getIndex(), DistributedRectilinearMeshGenerator::getIndices(), SolutionUserObject::getLocalVarIndex(), Material::getMaterialByName(), FEProblemBase::getMaterialData(), SubProblem::getMatrixTagID(), AnnularMesh::getMaxInDimension(), GeneratedMesh::getMaxInDimension(), FEProblemBase::getMaxQps(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), AnnularMesh::getMinInDimension(), GeneratedMesh::getMinInDimension(), MultiAppTransfer::getMultiApp(), DistributedRectilinearMeshGenerator::getNeighbors(), MooseMesh::getNodeBlockIds(), PropertyReadFile::getNodeData(), MooseMesh::getNodeList(), FEProblemBase::getNonlinearSystem(), MooseMesh::getPairedBoundaryMapping(), ImageMesh::GetPixelInfo(), ImageMeshGenerator::GetPixelInfo(), PlaneIDMeshGenerator::getPlaneID(), FEProblemBase::getPositionsObject(), PostprocessorInterface::getPostprocessorValueByNameInternal(), MooseMesh::getRefinementMap(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), FEProblemBase::getSampler(), JSONFileReader::getScalar(), DisplacedProblem::getScalarVariable(), FEProblemBase::getScalarVariable(), DisplacedProblem::getStandardVariable(), FEProblemBase::getStandardVariable(), MooseMesh::getSubdomainBoundaryIds(), DisplacedProblem::getSystem(), FEProblemBase::getSystem(), FEProblemBase::getTimeFromStateArg(), Transient::getTimeIntegratorName(), MultiAppTransfer::getToMultiApp(), MultiAppTransfer::getToMultiAppInfo(), MooseMesh::getUniqueCoordSystem(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::getUserObjectName(), JSONFileReader::getVector(), VectorPostprocessorInterface::getVectorPostprocessorName(), SubProblem::getVectorTag(), SubProblem::getVectorTagID(), DisplacedProblem::getVectorVariable(), FEProblemBase::getVectorVariable(), GhostingAux::GhostingAux(), MultiApp::globalAppToLocal(), Function::gradient(), MooseParsedVectorFunction::gradient(), Terminator::handleMessage(), MooseVariableBase::hasDoFsOnNodes(), PostprocessorInterface::hasPostprocessor(), PostprocessorInterface::hasPostprocessorByName(), ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), AddVariableAction::init(), MooseMesh::init(), Sampler::init(), AddAuxVariableAction::init(), EigenExecutionerBase::init(), Eigenvalue::init(), Transient::init(), FEProblemBase::init(), CrankNicolson::init(), ExplicitTimeIntegrator::init(), CSVTimeSequenceStepper::init(), IterationAdaptiveDT::init(), MultiApp::init(), FEProblemBase::initialAdaptMesh(), BoltzmannSolverScalar::initialize(), PolynomialCoefficients::initialize(), CartesianGridDivision::initialize(), CylindricalGridDivision::initialize(), NestedDivision::initialize(), SphericalGridDivision::initialize(), SubProblem::initialSetup(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), Axisymmetric2D3DSolutionFunction::initialSetup(), MooseParsedFunction::initialSetup(), SolutionFunction::initialSetup(), SolutionIC::initialSetup(), FullSolveMultiApp::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), SolutionUserObject::initialSetup(), Function::integral(), InterpolatedCoefficientLinear::InterpolatedCoefficientLinear(), InterpolatedCoefficientSpline::InterpolatedCoefficientSpline(), EigenExecutionerBase::inversePowerIteration(), InversePowerMethod::InversePowerMethod(), Sampler::isAdaptiveSamplingCompleted(), MooseMesh::isBoundaryFullyExternalToSubdomains(), MooseVariableBase::isNodal(), IterationAdaptiveDT::IterationAdaptiveDT(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LineSearch::lineSearch(), ReporterPointMarker::markerSetup(), Material::Material(), MaterialOutputAction::materialOutputHelper(), MaterialRealTensorValueAux::MaterialRealTensorValueAux(), MaterialRealVectorValueAuxTempl< is_ad >::MaterialRealVectorValueAuxTempl(), Distribution::median(), FunctorRelationshipManager::mesh_reinit(), SubProblem::meshChanged(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshExtruderGenerator::MeshExtruderGenerator(), MeshRepairGenerator::MeshRepairGenerator(), SetupMeshAction::modifyParamsForUseSplit(), MeshMetaDataInterface::mooseErrorInternal(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MoveNodeGenerator::MoveNodeGenerator(), ElementSubdomainModifier::movingBoundaryID(), ElementSubdomainModifier::movingBoundaryName(), MultiApp::MultiApp(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NearestNodeDistanceAux::NearestNodeDistanceAux(), NearestNodeValueAux::NearestNodeValueAux(), FEProblemBase::needsPreviousNewtonIteration(), NewmarkBeta::NewmarkBeta(), NodalPatchRecoveryBase::nodalPatchRecovery(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), DistributedRectilinearMeshGenerator::nodeId(), DistributedRectilinearMeshGenerator::numNeighbors(), Output::onInterval(), FunctorRelationshipManager::operator()(), RelationshipManager::operator==(), MortarNodalGeometryOutput::output(), Output::Output(), DistributedRectilinearMeshGenerator::paritionSquarely(), PiecewiseBilinear::parse(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), ExplicitTimeIntegrator::performExplicitSolve(), PetscExternalPartitioner::PetscExternalPartitioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), Executioner::picardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseMulticonstant::PiecewiseMulticonstant(), PiecewiseTabularBase::PiecewiseTabularBase(), SolutionUserObject::pointValueGradientWrapper(), SolutionUserObject::pointValueWrapper(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName(), AStableDirk4::postResidual(), ExplicitRK2::postResidual(), ExplicitTVDRK2::postResidual(), ImplicitMidpoint::postResidual(), LStableDirk2::postResidual(), LStableDirk3::postResidual(), LStableDirk4::postResidual(), VariableCondensationPreconditioner::preallocateCondensedJacobian(), Predictor::Predictor(), Transient::preExecute(), MooseMesh::prepare(), MooseMesh::prepared(), FixedPointSolve::printFixedPointConvergenceReason(), RateCoefficientProvider::RateCoefficientProvider(), RateCoefficientProvider::reaction_coefficient(), RateCoefficientProvider::reaction_coefficient_derivative(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readExodusII(), SolutionUserObject::readXda(), FunctorRelationshipManager::redistribute(), Sampler::reinit(), RinglebMesh::RinglebMesh(), RinglebMeshGenerator::RinglebMeshGenerator(), PiecewiseMultiInterpolation::sample(), ScalarComponentIC::ScalarComponentIC(), ScalarLinearInterpolation::ScalarLinearInterpolation(), ScalarSplineInterpolation::ScalarSplineInterpolation(), DistributedRectilinearMeshGenerator::scaleNodalPositions(), BicubicSplineFunction::secondDerivative(), FunctorRelationshipManager::set_mesh(), MooseVariableBase::setActiveTags(), DistributedRectilinearMeshGenerator::setBoundaryNames(), MooseMesh::setCoordSystem(), FEProblemBase::setCoupling(), PiecewiseBase::setData(), FileOutput::setFileBaseInternal(), MooseMesh::setGeneralAxisymmetricCoordAxes(), FEProblemSolve::setInnerSolve(), MeshGenerator::setMeshProperty(), FEProblemBase::setNonlocalCouplingMatrix(), Sampler::setNumberOfCols(), Sampler::setNumberOfRandomSeeds(), Sampler::setNumberOfRows(), Split::setup(), TransientMultiApp::setupApp(), SetupMeshAction::setupMesh(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), TimePeriodBase::setupTimes(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SideSetsFromNormalsGenerator::SideSetsFromNormalsGenerator(), SideSetsFromPointsGenerator::SideSetsFromPointsGenerator(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), SolutionTimeAdaptiveDT::SolutionTimeAdaptiveDT(), SolutionUserObject::SolutionUserObject(), FullSolveMultiApp::solveStep(), UserObject::spatialPoints(), UserObject::spatialValue(), SpiralAnnularMesh::SpiralAnnularMesh(), SpiralAnnularMeshGenerator::SpiralAnnularMeshGenerator(), StitchedMesh::StitchedMesh(), MaterialBase::subdomainSetup(), GeneralUserObject::subdomainSetup(), NodalUserObject::subdomainSetup(), Constraint::subdomainSetup(), SuperelasticReactionRate::SuperelasticReactionRate(), FEProblemBase::swapBackMaterialsNeighbor(), Terminator::Terminator(), GeneralUserObject::threadJoin(), ThreadedGeneralUserObject::threadJoin(), DiscreteElementUserObject::threadJoin(), TimePeriodBase::TimePeriodBase(), VectorPostprocessorVisualizationAux::timestepSetup(), FEProblemBase::trustUserCouplingMatrix(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), FEProblemBase::uDotDotOldRequested(), MooseVariableScalar::uDotOld(), FEProblemBase::uDotOldRequested(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), SolutionUserObject::updateExodusBracketingTimeIndices(), FEProblemBase::updateMaxQps(), BoundingBoxIC::value(), Function::value(), Axisymmetric2D3DSolutionFunction::value(), PiecewiseConstantFromCSV::value(), ValueProvider::ValueProvider(), ValueRangeMarker::ValueRangeMarker(), ValueThresholdMarker::ValueThresholdMarker(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), MultiAppTransfer::variableIntegrityCheck(), VariableTimeIntegrationAux::VariableTimeIntegrationAux(), AddVariableAction::variableType(), Function::vectorCurl(), SubProblem::vectorTagName(), SubProblem::vectorTagType(), Function::vectorValue(), MooseParsedFunction::vectorValue(), MooseParsedGradFunction::vectorValue(), SubProblem::verifyVectorTags(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
mooseErrorNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseErrorNonPrefixed (Args &&... args) const inline inherited
Emits an error without the prefixing included in mooseError().
Definition at line 50 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
mooseInfo()
template<typename... Args> void MooseBaseErrorInterface::mooseInfo (Args &&... args) const inline inherited
Definition at line 84 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseInfoStream(_console, std::forward<Args>(args)...);
  }
Referenced by AddZapdosReactions::act(), SetupRecoverFileBaseAction::act(), AStableDirk4::AStableDirk4(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), BoltzmannSolverScalar::execute(), ExplicitRK2::ExplicitRK2(), ExplicitTVDRK2::ExplicitTVDRK2(), MultiAppTransfer::getPointInTargetAppFrame(), ImplicitMidpoint::ImplicitMidpoint(), InversePowerMethod::InversePowerMethod(), LStableDirk2::LStableDirk2(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), NonlinearEigen::NonlinearEigen(), ProjectionAux::ProjectionAux(), FEProblemBase::setRestartFile(), and SymmetryTransformGenerator::SymmetryTransformGenerator().
mooseWarning()
template<typename... Args> void MooseBaseErrorInterface::mooseWarning (Args &&... args) const inline inherited
Emits a warning prefixed with object name and type.
Definition at line 62 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(
        _console, errorPrefix("warning"), std::forward<Args>(args)...);
  }
Referenced by AddFunctionAction::act(), AddKernelAction::act(), CommonOutputAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupMeshAction::act(), DumpObjectsProblem::addAuxVariable(), DiracKernelBase::addPoint(), BoundaryMarker::BoundaryMarker(), BoundsAuxBase::BoundsAuxBase(), DistributedRectilinearMeshGenerator::buildCube(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), CartesianMeshGenerator::CartesianMeshGenerator(), CheckOutputAction::checkConsoleOutput(), MultiAppTransfer::checkMultiAppExecuteOn(), GapValueAux::computeValue(), MeshDiagnosticsGenerator::diagnosticsLog(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), Postprocessor::evaluateDotWarning(), ElementQualityChecker::finalize(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FixedPointSolve::FixedPointSolve(), ElementSubdomainIDGenerator::generate(), ParsedGenerateSideset::generate(), MultiAppTransfer::getAppInfo(), FunctorBinnedValuesDivision::getBinIndex(), FEProblemBase::getMaterial(), Terminator::handleMessage(), MaterialBase::initStatefulProperties(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::mesh(), NewmarkBeta::NewmarkBeta(), NodalPatchRecovery::NodalPatchRecovery(), Output::Output(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), Executioner::problem(), PropertyReadFile::readData(), TestSourceStepper::rejectStep(), MaterialBase::resetQpProperties(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setCoordSystem(), FEProblemBase::sizeZeroes(), TransientMultiApp::solveStep(), TimeDerivativeAux::TimeDerivativeAux(), PiecewiseConstantFromCSV::value(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
mooseWarningNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseWarningNonPrefixed (Args &&... args) const inline inherited
Emits a warning without the prefixing included in mooseWarning().
Definition at line 72 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(_console, std::forward<Args>(args)...);
  }
moveApp()
void MultiApp::moveApp (unsigned int global_app, Point p) virtual inherited
Move the global_app to Point p.
Parameters
global_app The global app number in question
p The new position of the App.
Definition at line 1027 of file MultiApp.C.
{
  if (_use_positions)
  {
    _positions[global_app] = p;
    if (hasLocalApp(global_app))
    {
      unsigned int local_app = globalAppToLocal(global_app);
      if (_output_in_position)
        _apps[local_app]->setOutputPosition(p);
      if (_run_in_position)
        paramError("run_in_position", "Moving apps and running apps in position is not supported");
    }
  }
}
Referenced by MultiApp::preTransfer().
name()
virtual const std::string & MooseBase::name () const inline virtual inherited
Get the name of the class.
Returns
The name of the class
Reimplemented in MooseVariableBase.
Definition at line 47 of file MooseBase.h.
{ return _name; }
Referenced by HierarchicalGridPartitioner::_do_partition(), AdaptivityAction::act(), AddElementalFieldAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVariableAction::act(), CopyNodalVarsAction::act(), DeprecatedBlockAction::act(), DisplayGhostingAction::act(), MaterialOutputAction::act(), AddDriftDiffusionAction::addADKernels(), FEProblemBase::addAnyRedistributers(), Executioner::addAttributeReporter(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFunctorMaterial(), FunctorMaterial::addFunctorProperty(), FunctorMaterial::addFunctorPropertyByBlocks(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), ADDGKernel::ADDGKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), SubProblem::addPiecewiseByBlockLambdaFunctor(), FEProblemBase::addPostprocessor(), UserObject::addPostprocessorDependencyHelper(), InitialConditionBase::addPostprocessorDependencyHelper(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), UserObject::addUserObjectDependencyHelper(), AuxKernelTempl< ComputeValueType >::addUserObjectDependencyHelper(), InitialConditionBase::addUserObjectDependencyHelper(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), UserObject::addVectorPostprocessorDependencyHelper(), FVFluxKernel::adjustRMGhostLayers(), ADSurfaceCharge::ADSurfaceCharge(), Output::advancedExecuteOn(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayDGKernel::ArrayDGKernel(), ArrayParsedAux::ArrayParsedAux(), AStableDirk4::AStableDirk4(), Function::average(), MultiApp::backup(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), PiecewiseTabularBase::buildFromFile(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkICRestartError(), Damper::checkMinDamping(), Coupleable::checkWritableVar(), CompositeFunction::CompositeFunction(), MaterialBase::computeProperties(), FEProblemBase::computeUserObjectByName(), VectorPostprocessorVisualizationAux::computeValue(), MooseBaseParameterInterface::connectControllableParams(), BatchMaterial< Tuple, Output, Input >::construct(), MultiApp::createApp(), AddVariableAction::createInitialConditionAction(), MultiApp::createLocalApp(), MeshGeneratorSystem::createMeshGeneratorOrder(), MaterialBase::declareADProperty(), MeshGenerator::declareMeshesForSubByName(), MeshGenerator::declareNullMeshName(), MaterialBase::declareProperty(), DOFMapOutput::demangle(), DerivativeSumMaterialTempl< is_ad >::DerivativeSumMaterialTempl(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DomainUserObject::DomainUserObject(), DumpObjectsProblem::dumpObjectHelper(), EconomouDielectricBC::EconomouDielectricBC(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementValueSampler::ElementValueSampler(), MooseMesh::errorIfDistributedMesh(), MooseBaseErrorInterface::errorPrefix(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), PointValue::execute(), RestartableDataReporter::execute(), MultiAppNearestNodeTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), MultiApp::fillPositions(), PointSamplerBase::finalize(), FunctionDT::FunctionDT(), FVFunctionIC::functionName(), FunctionIC::functionName(), FunctorPositions::FunctorPositions(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), BoundaryDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), GeneratedMeshGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MeshGenerator::generateInternal(), InterfaceMaterial::getADMaterialProperty(), Material::getADMaterialProperty(), MultiAppTransfer::getAppInfo(), MultiApp::getBoundingBox(), Control::getControllableParameterByName(), Control::getControllableValue(), Control::getControllableValueByName(), UserObject::getDependObjects(), FEProblemBase::getDistribution(), DistributionInterface::getDistribution(), DistributionInterface::getDistributionByName(), AddZapdosReactions::getElectronImpactKernelName(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), MultiApp::getExecutioner(), FEProblemBase::getExecutor(), OutputWarehouse::getFileNumbers(), FEProblemBase::getFunction(), SubProblem::getFunctor(), AuxKernelTempl< ComputeValueType >::getGenericMaterialProperty(), NodalPatchRecovery::getGenericMaterialProperty(), InterfaceMaterial::getGenericMaterialProperty(), Material::getGenericMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialPropertyByName(), Material::getGenericOptionalMaterialProperty(), MaterialBase::getGenericZeroMaterialProperty(), BatchMaterial< Tuple, Output, Input >::getIndex(), AddZapdosReactions::getKernelName(), SolutionUserObject::getLocalVarIndex(), Marker::getMarkerValue(), Material::getMaterial(), FEProblemBase::getMaterial(), Material::getMaterialByName(), AuxKernelTempl< ComputeValueType >::getMaterialProperty(), NodalPatchRecovery::getMaterialProperty(), InterfaceMaterial::getMaterialProperty(), Material::getMaterialProperty(), SubProblem::getMaterialPropertyBlockNames(), SubProblem::getMaterialPropertyBoundaryNames(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOld(), NodalPatchRecovery::getMaterialPropertyOld(), InterfaceMaterial::getMaterialPropertyOld(), Material::getMaterialPropertyOld(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOlder(), NodalPatchRecovery::getMaterialPropertyOlder(), InterfaceMaterial::getMaterialPropertyOlder(), Material::getMaterialPropertyOlder(), MeshGenerator::getMesh(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshesByName(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MultiAppTransfer::getMultiApp(), InterfaceMaterial::getNeighborADMaterialProperty(), InterfaceMaterial::getNeighborMaterialProperty(), InterfaceMaterial::getNeighborMaterialPropertyOld(), InterfaceMaterial::getNeighborMaterialPropertyOlder(), Material::getOptionalADMaterialProperty(), Material::getOptionalMaterialProperty(), Material::getOptionalMaterialPropertyOld(), Material::getOptionalMaterialPropertyOlder(), FEProblemBase::getPositionsObject(), FEProblemBase::getPostprocessorValueByName(), AddReactions::getReactionKernelName(), ReporterData::getReporterInfo(), FEProblemBase::getSampler(), Transient::getTimeStepperName(), ProjectedStatefulMaterialStorageAction::getTypeEnum(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), Terminator::handleMessage(), FEProblemBase::hasFunction(), SubProblem::hasFunctor(), SubProblem::hasFunctorWithType(), AdvancedOutput::hasOutputHelper(), FEProblemBase::hasPostprocessor(), FEProblemBase::hasPostprocessorValueByName(), FEProblemBase::hasUserObject(), AdvancedOutput::init(), FEProblemBase::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), AttribName::initFrom(), NestedDivision::initialize(), SolutionScalarAux::initialSetup(), NodalVariableValue::initialSetup(), MultiAppProjectionTransfer::initialSetup(), SolutionUserObject::initialSetup(), AdvancedOutput::initOutputList(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MaterialBase::initStatefulProperties(), Function::integral(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), MeshGenerator::isChildMeshGenerator(), MeshGenerator::isNullMeshName(), MeshGenerator::isParentMeshGenerator(), LinearCombinationFunction::LinearCombinationFunction(), FEProblemBase::logAdd(), LymberopoulosElectronBC::LymberopoulosElectronBC(), Marker::Marker(), Material::Material(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), Distribution::median(), MemoryUsageReporter::MemoryUsageReporter(), MeshGenerator::meshPropertyPrefix(), MooseVariableInterface< T >::MooseVariableInterface(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), NeumannCircuitVoltageMoles_KV::NeumannCircuitVoltageMoles_KV(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), NodalValueSampler::NodalValueSampler(), MooseBaseParameterInterface::objectErrorPrefix(), MeshGenerator::Comparator::operator()(), DOFMapOutput::output(), ProgressOutput::output(), Output::Output(), AdvancedOutput::outputElementalVariables(), ConsoleUtils::outputExecutionInformation(), AdvancedOutput::outputInput(), AdvancedOutput::outputNodalVariables(), AdvancedOutput::outputPostprocessors(), Exodus::outputPostprocessors(), Nemesis::outputPostprocessors(), TableOutput::outputReporter(), AdvancedOutput::outputReporters(), AdvancedOutput::outputScalarVariables(), AdvancedOutput::outputSystemInformation(), AdvancedOutput::outputVectorPostprocessors(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedODEKernel::ParsedODEKernel(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PointVariableSamplerBase::PointVariableSamplerBase(), MultiApp::readCommandLineArguments(), Receiver::Receiver(), Executor::Result::record(), FEProblemBase::registerRandomInterface(), GlobalParamsAction::remove(), MaterialBase::resetQpProperties(), MultiApp::restore(), SakiyamaEnergySecondaryElectronBC::SakiyamaEnergySecondaryElectronBC(), SakiyamaSecondaryElectronBC::SakiyamaSecondaryElectronBC(), ScalarComponentIC::ScalarComponentIC(), SecondaryElectronBC::SecondaryElectronBC(), SecondaryElectronEnergyBC::SecondaryElectronEnergyBC(), MultiApp::setAppOutputFileBase(), MooseMesh::setBoundaryName(), Control::setControllableValue(), Control::setControllableValueByName(), GlobalParamsAction::setDoubleIndexParam(), OutputWarehouse::setFileNumbers(), GlobalParamsAction::setParam(), FEProblemBase::setPostprocessorValueByName(), GlobalParamsAction::setScalarParam(), MooseMesh::setSubdomainName(), GlobalParamsAction::setTripleIndexParam(), Split::setup(), TransientMultiApp::setupApp(), GlobalParamsAction::setVectorParam(), SideCurrent::SideCurrent(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SideValueSampler::SideValueSampler(), TransientMultiApp::solveStep(), UserObject::spatialValue(), StitchedMesh::StitchedMesh(), SubProblem::storeBoundaryDelayedCheckMatProp(), SubProblem::storeBoundaryMatPropName(), SubProblem::storeBoundaryZeroMatProp(), SubProblem::storeSubdomainDelayedCheckMatProp(), SubProblem::storeSubdomainMatPropName(), SubProblem::storeSubdomainZeroMatProp(), MaterialBase::subdomainSetup(), TaggingInterface::TaggingInterface(), VectorPostprocessorVisualizationAux::timestepSetup(), MultiAppDofCopyTransfer::transfer(), TransientMultiApp::TransientMultiApp(), MooseBase::typeAndName(), MooseBaseParameterInterface::uniqueParameterName(), UserObject::UserObject(), UserObjectInterface::userObjectName(), MultiAppTransfer::variableIntegrityCheck(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), AdvancedOutput::wantOutput(), Coupleable::writableCoupledValue(), and Coupleable::writableVariable().
needsRestoration()
bool TransientMultiApp::needsRestoration () override virtual inherited
Whether or not this MultiApp should be restored at the beginning of each Picard iteration.
Reimplemented from MultiApp.
Definition at line 601 of file TransientMultiApp.C.
{
  return _sub_cycling || _catch_up || _auto_advance || _tolerate_failure || _detect_steady_state;
}
numBlocks()
unsigned int BlockRestrictable::numBlocks () const inherited
Return the number of blocks for this object.
Returns
The number of subdomains
Definition at line 199 of file BlockRestrictable.C.
{
  return (unsigned int)_blk_ids.size();
}
Referenced by ElementCentroidPositions::initialize().
numGlobalApps()
unsigned int MultiApp::numGlobalApps () const inline inherited
Returns
Number of Global Apps in this MultiApp
Definition at line 276 of file MultiApp.h.
{ return _total_num_apps; }
numLocalApps()
unsigned int MultiApp::numLocalApps () inline inherited
Returns
Number of Apps on local processor.
Definition at line 281 of file MultiApp.h.
{ return _apps.size(); }
objectErrorPrefix()
std::string MooseBaseParameterInterface::objectErrorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for an object.
Definition at line 58 of file MooseBaseParameterInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the class \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseParameterInterface::paramErrorMsg().
paramError()
template<typename... Args> void MooseBaseParameterInterface::paramError (const std::string & param, Args... args) const inherited
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseError - only printing a message using the given args.
Definition at line 233 of file MooseBaseParameterInterface.h.
{
  Moose::show_trace = false;
  std::string msg = paramErrorMsg(param, std::forward<Args>(args)...);
  callMooseErrorRaw(msg, &_moose_base->getMooseApp());
  Moose::show_trace = true;
}
Referenced by HierarchicalGridPartitioner::_do_partition(), SetupDebugAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), ADDGKernel::ADDGKernel(), ReporterPointSource::addPoints(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ADNodalKernel::ADNodalKernel(), ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), AdvectiveFluxAux::AdvectiveFluxAux(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), ArrayBodyForce::ArrayBodyForce(), ArrayDGKernel::ArrayDGKernel(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayDirichletBC::ArrayDirichletBC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), ArrayPenaltyDirichletBC::ArrayPenaltyDirichletBC(), ArrayVacuumBC::ArrayVacuumBC(), BlockDeletionGenerator::BlockDeletionGenerator(), BlockWeightedPartitioner::BlockWeightedPartitioner(), BoundsAuxBase::BoundsAuxBase(), BreakMeshByBlockGenerator::BreakMeshByBlockGenerator(), BuildArrayVariableAux::BuildArrayVariableAux(), PiecewiseTabularBase::buildFromFile(), CartesianGridDivision::CartesianGridDivision(), UserObjectInterface::castUserObject(), checkComponent(), MeshGenerator::checkGetMesh(), PostprocessorInterface::checkParam(), Coupleable::checkVar(), MultiAppTransfer::checkVariable(), CircularBoundaryCorrectionGenerator::CircularBoundaryCorrectionGenerator(), CircularBoundaryCorrectionGenerator::circularCenterCalculator(), MultiAppGeneralFieldTransfer::closestToPosition(), CombinerGenerator::CombinerGenerator(), CompositionDT::CompositionDT(), ConcentricCircleMeshGenerator::ConcentricCircleMeshGenerator(), LibtorchNeuralNetControl::conditionalParameterError(), ConstantVectorPostprocessor::ConstantVectorPostprocessor(), ContainsPointAux::ContainsPointAux(), CopyValueAux::CopyValueAux(), Coupleable::Coupleable(), CoupledForceTempl< is_ad >::CoupledForceTempl(), CoupledValueFunctionMaterialTempl< is_ad >::CoupledValueFunctionMaterialTempl(), MultiApp::createApp(), MeshGeneratorSystem::createMeshGenerator(), CylindricalGridDivision::CylindricalGridDivision(), ConstantReporter::declareConstantReporterValues(), AccumulateReporter::declareLateValues(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DGLowerDKernel::DGLowerDKernel(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementLengthAux::ElementLengthAux(), ElementLpNormAux::ElementLpNormAux(), ElementValueSampler::ElementValueSampler(), ReporterPointSource::errorCheck(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), ExtraElementIDAux::ExtraElementIDAux(), ExtraElementIntegerDivision::ExtraElementIntegerDivision(), FEProblemSolve::FEProblemSolve(), FillBetweenCurvesGenerator::FillBetweenCurvesGenerator(), FillBetweenSidesetsGenerator::FillBetweenSidesetsGenerator(), ReporterPointSource::fillPoint(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), InternalSideIndicator::finalize(), FixedPointSolve::FixedPointSolve(), ForcingFunctionAux::ForcingFunctionAux(), FunctionArrayAux::FunctionArrayAux(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorAux::FunctorAux(), FunctorBinnedValuesDivision::FunctorBinnedValuesDivision(), FunctorElementalGradientAuxTempl< is_ad >::FunctorElementalGradientAuxTempl(), FunctorPositions::FunctorPositions(), FunctorVectorElementalAuxTempl< is_ad >::FunctorVectorElementalAuxTempl(), FVFluxBC::FVFluxBC(), FVInterfaceKernel::FVInterfaceKernel(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), FVTwoVarContinuityConstraint::FVTwoVarContinuityConstraint(), AdvancedExtruderGenerator::generate(), BlockDeletionGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundaryDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), BreakMeshByBlockGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), CombinerGenerator::generate(), ExplodeMeshGenerator::generate(), ExtraNodesetGenerator::generate(), FillBetweenCurvesGenerator::generate(), FillBetweenSidesetsGenerator::generate(), GeneratedMeshGenerator::generate(), MeshCollectionGenerator::generate(), MeshExtruderGenerator::generate(), ParsedCurveGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), PropertyReadFile::getBlockData(), PropertyReadFile::getData(), Sampler::getGlobalSamples(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), Sampler::getLocalSamples(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), Sampler::getNextLocalRow(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectName(), HFEMDirichletBC::HFEMDirichletBC(), MultiApp::init(), BlockWeightedPartitioner::initialize(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), PiecewiseConstantFromCSV::initialSetup(), LibtorchControlValuePostprocessor::initialSetup(), ReferenceResidualProblem::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), HistogramVectorPostprocessor::initialSetup(), AddMetaDataGenerator::inputChecker(), IntegratedBC::IntegratedBC(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceValueUserObjectAux::InterfaceValueUserObjectAux(), InterpolatedStatefulMaterialTempl< T >::InterpolatedStatefulMaterialTempl(), InversePowerMethod::InversePowerMethod(), IterationAdaptiveDT::IterationAdaptiveDT(), MultiApp::keepSolutionDuringRestore(), Kernel::Kernel(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LinearCombinationFunction::LinearCombinationFunction(), LowerDIntegratedBC::LowerDIntegratedBC(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), MaterialADConverterTempl< T >::MaterialADConverterTempl(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), PatternedMeshGenerator::mergeSubdomainNameMaps(), MeshCollectionGenerator::MeshCollectionGenerator(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshDivisionAux::MeshDivisionAux(), MeshGenerator::MeshGenerator(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarNodalAuxKernelTempl< ComputeValueType >::MortarNodalAuxKernelTempl(), MultiApp::moveApp(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), NestedDivision::NestedDivision(), NodalBC::NodalBC(), NodalEqualValueConstraint::NodalEqualValueConstraint(), NodalKernel::NodalKernel(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), NodalValueSampler::NodalValueSampler(), Output::Output(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), PatchMeshGenerator::PatchMeshGenerator(), PatternedMeshGenerator::PatternedMeshGenerator(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), PeriodicSegmentalConstraint::PeriodicSegmentalConstraint(), PIDTransientControl::PIDTransientControl(), PlaneDeletionGenerator::PlaneDeletionGenerator(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), PolyLineMeshGenerator::PolyLineMeshGenerator(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), LibmeshPartitioner::prepareBlocksForSubdomainPartitioner(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), PropertyReadFile::PropertyReadFile(), RandomIC::RandomIC(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readXda(), ReferenceResidualProblem::ReferenceResidualProblem(), RefineBlockGenerator::RefineBlockGenerator(), RefineSidesetGenerator::RefineSidesetGenerator(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setPartitioner(), TimeSequenceStepperBase::setupSequence(), SingleRankPartitioner::SingleRankPartitioner(), SphericalGridDivision::SphericalGridDivision(), SymmetryTransformGenerator::SymmetryTransformGenerator(), Terminator::Terminator(), TimeDerivativeAux::TimeDerivativeAux(), Transfer::Transfer(), TransformGenerator::TransformGenerator(), TransientMultiApp::TransientMultiApp(), ParsedCurveGenerator::tSectionSpaceDefiner(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), UserObject::UserObject(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), VolumeAux::VolumeAux(), XYDelaunayGenerator::XYDelaunayGenerator(), and XYMeshLineCutter::XYMeshLineCutter().
paramErrorMsg()
template<typename... Args> std::string MooseBaseParameterInterface::paramErrorMsg (const std::string & param, Args... args) const inline private inherited
Definition at line 171 of file MooseBaseParameterInterface.h.
  {
    auto param_prefix = paramErrorPrefix(_pars, param);
    // With no input location information, append object info (name + type)
    const std::string object_prefix =
        _pars.inputLocation(param).empty() ? objectErrorPrefix("parameter error") : "";
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    // Wrap error message to a separate line from param_prefix if it is about to
    // blow past 100 chars.  But only wrap if the param_prefix is long enough (12
    // chars) for the wrap to buy us much extra length. We don't check object_prefix
    // here because it will go before the parameter error
    if ((param_prefix.size() > 12 && msg.size() + param_prefix.size() > 99) ||
        msg.find("\n") != std::string::npos)
    {
      if (param_prefix.size() > 0 && param_prefix[param_prefix.size() - 1] != ':')
        param_prefix += ":";
      return object_prefix + param_prefix + "\n    " + MooseUtils::replaceAll(msg, "\n", "\n    ");
    }
    return object_prefix + param_prefix + " " + msg;
  }
Referenced by MooseBaseParameterInterface::paramError(), MooseBaseParameterInterface::paramInfo(), and MooseBaseParameterInterface::paramWarning().
parameters()
const InputParameters & MooseBaseParameterInterface::parameters () const inline inherited
Get the parameters of the object.
Returns
The parameters of the object
Definition at line 53 of file MooseBaseParameterInterface.h.
{ return _pars; }
Referenced by SetupDebugAction::act(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), FEProblemBase::addPostprocessor(), FEProblemBase::addPredictor(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), AdvancedOutput::AdvancedOutput(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), Moose::assemble_matrix(), AuxScalarKernel::AuxScalarKernel(), BoundsAuxBase::BoundsAuxBase(), MooseMesh::buildTypedMesh(), UserObjectInterface::castUserObject(), PostprocessorInterface::checkParam(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), Moose::compute_bounds(), Moose::compute_jacobian(), Moose::compute_nearnullspace(), Moose::compute_nullspace(), Moose::compute_postcheck(), Moose::compute_transpose_nullspace(), LibtorchNeuralNetControl::conditionalParameterError(), Console::Console(), MultiApp::createApp(), Postprocessor::declareValue(), DumpObjectsProblem::deduceNecessaryParameters(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), DumpObjectsProblem::dumpObjectHelper(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElectronsFromIonization::ElectronsFromIonization(), Executor::Executor(), Exodus::Exodus(), FEProblem::FEProblem(), FEProblemBase::FEProblemBase(), FixedPointSolve::FixedPointSolve(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GapValueAux::GapValueAux(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), MooseBaseParameterInterface::getCheckedPointerParam(), ExecutorInterface::getExecutor(), Material::getMaterial(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), UserObjectInterface::getUserObjectName(), VectorPostprocessorInterface::getVectorPostprocessorName(), GhostingUserObject::GhostingUserObject(), HphiRadialInterface::HphiRadialInterface(), AttribSystem::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), FullSolveMultiApp::initialSetup(), FEProblemBase::initNullSpaceVectors(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), isValid(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseAppCoordTransform::MooseAppCoordTransform(), MooseVariableInterface< T >::MooseVariableInterface(), MultiApp::MultiApp(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodeFaceConstraint::NodeFaceConstraint(), PatchMeshGenerator::PatchMeshGenerator(), PenetrationAux::PenetrationAux(), PicardSolve::PicardSolve(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), ProjectedStatefulMaterialStorageAction::processProperty(), MultiAppProjectionTransfer::projectSolution(), PropertyReadFile::PropertyReadFile(), PseudoTimestep::PseudoTimestep(), RandomIC::RandomIC(), InputParameterWarehouse::removeInputParameters(), OutputWarehouse::resetFileBase(), MooseAppCoordTransform::setCoordinateSystem(), FEProblemBase::setInputParametersFEProblem(), FEProblem::setInputParametersFEProblem(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SteffensenSolve::SteffensenSolve(), DumpObjectsProblem::stringifyParameters(), TaggingInterface::TaggingInterface(), Transfer::Transfer(), Transient::Transient(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
paramInfo()
template<typename... Args> void MooseBaseParameterInterface::paramInfo (const std::string & param, Args... args) const inherited
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseInfo - only printing a message using the given args.
Definition at line 250 of file MooseBaseParameterInterface.h.
{
  mooseInfo(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by TransientMultiApp::TransientMultiApp().
paramWarning()
template<typename... Args> void MooseBaseParameterInterface::paramWarning (const std::string & param, Args... args) const inherited
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseWarning - only printing a message using the given args.
Definition at line 243 of file MooseBaseParameterInterface.h.
{
  mooseWarning(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by MultiAppNearestNodeTransfer::execute(), FEProblemSolve::FEProblemSolve(), PlaneIDMeshGenerator::generate(), UniqueExtraIDMeshGenerator::generate(), Terminator::initialSetup(), and MooseMesh::MooseMesh().
parentOutputPositionChanged()
void MultiApp::parentOutputPositionChanged () virtual inherited
For apps outputting in position we need to change their output positions if their parent app moves.
Definition at line 1046 of file MultiApp.C.
{
  if (_use_positions && _output_in_position)
    for (unsigned int i = 0; i < _apps.size(); i++)
      _apps[i]->setOutputPosition(_app.getOutputPosition() + _positions[_first_local_app + i]);
}
perfGraph()
PerfGraph & PerfGraphInterface::perfGraph () inherited
Get the PerfGraph.
Definition at line 78 of file PerfGraphInterface.C.
{
  return _pg_moose_app.perfGraph();
}
Referenced by CommonOutputAction::act(), PerfGraphData::finalize(), and PerfGraphOutput::output().
position()
const Point & MultiApp::position (unsigned int app) const inherited
The physical position of a global App number.
Parameters
app The global app number you want the position for.
Returns
the position
Definition at line 1358 of file MultiApp.C.
{
  // If we're not using positions, it won't have changed
  if (_positions_objs.empty())
    return _positions[app];
  else
    // Find which Positions object is specifying it, and query a potentially updated value
    return _positions_objs[app]->getPosition(app - _positions_index_offsets[app], false);
}
Referenced by MultiApp::getBoundingBox().
postExecute()
void MultiApp::postExecute () virtual inherited
Method called at the end of the simulation (after finalize).
Reimplemented in FullSolveMultiApp.
Definition at line 709 of file MultiApp.C.
{
  for (const auto & app_ptr : _apps)
  {
    auto * executioner = app_ptr->getExecutioner();
    mooseAssert(executioner, "Executioner is nullptr");
    executioner->postExecute();
  }
}
preExecute()
virtual void MultiApp::preExecute () inline virtual inherited
Definition at line 122 of file MultiApp.h.
{}
preRunInputFile()
void MultiApp::preRunInputFile () protected virtual inherited
call back executed right before app->runInputFile()
Definition at line 1323 of file MultiApp.C.
{
}
Referenced by MultiApp::createApp().
preTransfer()
void MultiApp::preTransfer (Real dt, Real target_time) virtual inherited
Gets called just before transfers are done to the MultiApp (Which is just before the MultiApp is solved).
Definition at line 631 of file MultiApp.C.
{
  // Get a transient executioner to get a user-set tolerance
  Real timestep_tol = 1e-13;
  if (dynamic_cast<Transient *>(_fe_problem.getMooseApp().getExecutioner()))
    timestep_tol =
        dynamic_cast<Transient *>(_fe_problem.getMooseApp().getExecutioner())->timestepTol();
  // First, see if any Apps need to be reset
  for (unsigned int i = 0; i < _reset_times.size(); i++)
  {
    if (!_reset_happened[i] && (target_time + timestep_tol >= _reset_times[i]))
    {
      _reset_happened[i] = true;
      if (_reset_apps.size() > 0)
        for (auto & app : _reset_apps)
          resetApp(app);
      // If we reset an application, then we delete the old objects, including the coordinate
      // transformation classes. Consequently we need to reset the coordinate transformation classes
      // in the associated transfer classes
      for (auto * const transfer : _associated_transfers)
        transfer->getAppInfo();
      // Similarly we need to transform the mesh again
      if (_run_in_position)
        for (const auto i : make_range(_my_num_apps))
        {
          auto app_ptr = _apps[i];
          if (usingPositions())
            app_ptr->getExecutioner()->feProblem().coordTransform().transformMesh(
                app_ptr->getExecutioner()->feProblem().mesh(), _positions[_first_local_app + i]);
          else
            app_ptr->getExecutioner()->feProblem().coordTransform().transformMesh(
                app_ptr->getExecutioner()->feProblem().mesh(), Point(0, 0, 0));
        }
      // If the time step covers multiple reset times, set them all as having 'happened'
      for (unsigned int j = i; j < _reset_times.size(); j++)
        if (target_time + timestep_tol >= _reset_times[j])
          _reset_happened[j] = true;
      break;
    }
  }
  // Now move any apps that should be moved
  if (_use_positions && !_move_happened && target_time + timestep_tol >= _move_time)
  {
    _move_happened = true;
    for (unsigned int i = 0; i < _move_apps.size(); i++)
      moveApp(_move_apps[i], _move_positions[i]);
  }
}
problemBase()
FEProblemBase & MultiApp::problemBase () inline inherited
Get the FEProblemBase this MultiApp is part of.
Definition at line 236 of file MultiApp.h.
{ return _fe_problem; }
readCommandLineArguments()
void MultiApp::readCommandLineArguments () protected inherited
Fill command line arguments for sub apps.
Definition at line 421 of file MultiApp.C.
{
  if (isParamValid("cli_args_files"))
  {
    _cli_args_from_file.clear();
    std::vector<FileName> cli_args_files = getParam<std::vector<FileName>>("cli_args_files");
    std::vector<FileName> input_files = getParam<std::vector<FileName>>("input_files");
    // If we use parameter "cli_args_files", at least one file should be provided
    if (!cli_args_files.size())
      paramError("cli_args_files", "You need to provide at least one commandLine argument file ");
    // If we multiple input files, then we need to check if the number of input files
    // match with the number of argument files
    if (cli_args_files.size() != 1 && cli_args_files.size() != input_files.size())
      paramError("cli_args_files",
                 "The number of commandLine argument files ",
                 cli_args_files.size(),
                 " for MultiApp ",
                 name(),
                 " must either be only one or match the number of input files ",
                 input_files.size());
    // Go through all argument files
    std::vector<std::string> cli_args;
    for (unsigned int p_file_it = 0; p_file_it < cli_args_files.size(); p_file_it++)
    {
      std::string cli_args_file = cli_args_files[p_file_it];
      // Clear up
      cli_args.clear();
      // Read the file on the root processor then broadcast it
      if (processor_id() == 0)
      {
        MooseUtils::checkFileReadable(cli_args_file);
        std::ifstream is(cli_args_file.c_str());
        std::copy(std::istream_iterator<std::string>(is),
                  std::istream_iterator<std::string>(),
                  std::back_inserter(cli_args));
        // We do not allow empty files
        if (!cli_args.size())
          paramError("cli_args_files",
                     "There is no commandLine argument in the commandLine argument file ",
                     cli_args_file);
        // If we have position files, we need to
        // make sure the number of commandLine argument strings
        // match with the number of positions
        if (_npositions_inputfile.size())
        {
          auto num_positions = _npositions_inputfile[p_file_it];
          // Check if the number of commandLine argument strings equal to
          // the number of positions
          if (cli_args.size() == 1)
            for (MooseIndex(num_positions) num = 0; num < num_positions; num++)
              _cli_args_from_file.push_back(cli_args.front());
          else if (cli_args.size() == num_positions)
            for (auto && cli_arg : cli_args)
              _cli_args_from_file.push_back(cli_arg);
          else if (cli_args.size() != num_positions)
            paramError("cli_args_files",
                       "The number of commandLine argument strings ",
                       cli_args.size(),
                       " in the file ",
                       cli_args_file,
                       " must either be only one or match the number of positions ",
                       num_positions);
        }
        else
        {
          // If we do not have position files, we will check if the number of
          // commandLine argument strings match with the total number of subapps
          for (auto && cli_arg : cli_args)
            _cli_args_from_file.push_back(cli_arg);
        }
      }
    }
    // Broad cast all arguments to everyone
    _communicator.broadcast(_cli_args_from_file);
  }
  if (_cli_args_from_file.size() && _cli_args_from_file.size() != 1 &&
      _cli_args_from_file.size() != _total_num_apps)
    mooseError(" The number of commandLine argument strings ",
               _cli_args_from_file.size(),
               " must either be only one or match the total "
               "number of sub apps ",
               _total_num_apps);
  if (_cli_args_from_file.size() && cliArgs().size())
    mooseError("Cannot set commandLine arguments from both input_file and external files");
}
Referenced by MultiApp::createApps().
registerRestartableDataOnApp()
RestartableDataValue & Restartable::registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const private inherited
Helper function for actually registering the restartable data.
Definition at line 51 of file Restartable.C.
{
  return _restartable_app.registerRestartableData(
      std::move(data), tid, _restartable_read_only, _metaname);
}
Referenced by Restartable::declareRestartableDataHelper().
registerRestartableNameWithFilterOnApp()
void Restartable::registerRestartableNameWithFilterOnApp (const std::string & name, Moose::RESTARTABLE_FILTER filter) private inherited
Helper function for actually registering the restartable data.
Definition at line 59 of file Restartable.C.
{
  _restartable_app.registerRestartableNameWithFilter(name, filter);
}
Referenced by Restartable::declareRecoverableData().
registerTimedSection() [1/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
Returns
The ID of the section - use when starting timing
Definition at line 53 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(timed_section_name, level);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
registerTimedSection() [2/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level, const std::string & live_message, const bool print_dots = true) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
live_message The message to be printed to the screen during execution
print_dots Whether or not progress dots should be printed for this section
Returns
The ID of the section - use when starting timing
Definition at line 64 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(
        timedSectionName(section_name), level, live_message, print_dots);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
resetApp()
void TransientMultiApp::resetApp (unsigned int global_app, Real time) override virtual inherited
"Reset" the App corresponding to the global App number passed in.
"Reset" means that the App will be deleted and recreated. The time for the new App will be set to the current simulation time. This might be handy if some sub-app in your simulation needs to get replaced by a "new" piece of material.
Parameters
global_app The global app number to reset.
time The time to set as the the time for the new app, this should really be the time the old app was at.
Reimplemented from MultiApp.
Definition at line 638 of file TransientMultiApp.C.
{
  if (hasLocalApp(global_app))
  {
    unsigned int local_app = globalAppToLocal(global_app);
    // Grab the current time the App is at so we can start the new one at the same place
    Real time =
        _transient_executioners[local_app]->getTime() + _apps[local_app]->getGlobalTimeOffset();
    // Reset the Multiapp
    MultiApp::resetApp(global_app, time);
    Moose::ScopedCommSwapper swapper(_my_comm);
    // Setup the app, disable the output so that the initial condition does not output
    // When an app is reset the initial condition was effectively already output before reset
    FEProblemBase & problem = appProblemBase(local_app);
    problem.allowOutput(false);
    setupApp(local_app, time);
    problem.allowOutput(true);
  }
}
residualSetup()
void SetupInterface::residualSetup () virtual inherited
Gets called just before the residual is computed and before this object is asked to do its job.
Reimplemented in NodeFaceConstraint, Function, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 55 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::residualSetup(), ComputeFVFluxResidualThread< RangeType >::setup(), and ComputeFVFluxRJThread< RangeType >::setup().
restartableName()
std::string Restartable::restartableName (const std::string & data_name) const protected inherited
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
This should only be used in this interface and in testing.
Definition at line 66 of file Restartable.C.
{
  return _restartable_system_name + "/" + _restartable_name + "/" + data_name;
}
Referenced by Restartable::declareRecoverableData(), and Restartable::declareRestartableDataHelper().
restore()
void MultiApp::restore (bool force = true) virtual inherited
Restore the state of every Sub App.
This allows us to "Restore" this state later If the app is not forced to restore, it is only done as needed (and also for the apps underneath as needed)
Parameters
force Whether the restoration has to happen no matter what.
Reimplemented in FullSolveMultiApp.
Definition at line 736 of file MultiApp.C.
{
  TIME_SECTION(_restore_timer);
  if (force || needsRestoration())
  {
    // Must be restarting / recovering from main app so hold off on restoring
    // Instead - the restore will happen in sub-apps' initialSetup()
    // Note that _backups was already populated by dataLoad() in the main app
    if (_fe_problem.getCurrentExecuteOnFlag() == EXEC_INITIAL)
      return;
    // We temporarily copy and store solutions for all subapps
    if (_keep_solution_during_restore)
    {
      _end_solutions.resize(_my_num_apps);
      for (unsigned int i = 0; i < _my_num_apps; i++)
      {
        _end_solutions[i] = _apps[i]
                                ->getExecutioner()
                                ->feProblem()
                                .getNonlinearSystemBase(/*nl_sys=*/0)
                                .solution()
                                .clone();
        auto & sub_multiapps =
            _apps[i]->getExecutioner()->feProblem().getMultiAppWarehouse().getObjects();
        // multiapps of each subapp should do the same things
        // It is implemented recursively
        for (auto & multi_app : sub_multiapps)
          multi_app->keepSolutionDuringRestore(_keep_solution_during_restore);
      }
    }
    if (_fe_problem.verboseMultiApps())
      _console << "Restoring MultiApp ... ";
    for (unsigned int i = 0; i < _my_num_apps; i++)
    {
      _apps[i]->restore(std::move(_sub_app_backups[i]), false);
      _sub_app_backups[i] = _apps[i]->finalizeRestore();
      mooseAssert(_sub_app_backups[i], "Should have a backup");
    }
    if (_fe_problem.verboseMultiApps())
      _console << name() << std::endl;
    // Now copy the latest solutions back for each subapp
    if (_keep_solution_during_restore)
    {
      for (unsigned int i = 0; i < _my_num_apps; i++)
      {
        _apps[i]->getExecutioner()->feProblem().getNonlinearSystemBase(/*nl_sys=*/0).solution() =
            *_end_solutions[i];
        // We need to synchronize solution so that local_solution has the right values
        _apps[i]->getExecutioner()->feProblem().getNonlinearSystemBase(/*nl_sys=*/0).update();
      }
      _end_solutions.clear();
    }
  }
  else
  {
    for (unsigned int i = 0; i < _my_num_apps; i++)
    {
      for (auto & sub_app :
           _apps[i]->getExecutioner()->feProblem().getMultiAppWarehouse().getObjects())
        sub_app->restore(false);
    }
  }
}
Referenced by dataLoad(), and FullSolveMultiApp::restore().
runningInPosition()
bool MultiApp::runningInPosition () const inline inherited
Whether or not this MultiApp is being run in position, eg with the coordinate transform already applied.
Definition at line 367 of file MultiApp.h.
{ return _run_in_position; }
setAppOutputFileBase() [1/2]
void MultiApp::setAppOutputFileBase () inherited
Sets all the app's output file bases.
See also
MooseApp::setOutputFileBase for usage
Definition at line 1334 of file MultiApp.C.
{
  for (unsigned int i = 0; i < _my_num_apps; ++i)
    setAppOutputFileBase(i);
}
Referenced by MultiApp::createApp(), and MultiApp::setAppOutputFileBase().
setAppOutputFileBase() [2/2]
void MultiApp::setAppOutputFileBase (unsigned int index) protected inherited
Set the output file base of the application which corresponds to the index passed to the function.
Parameters
index The sub-application index
Definition at line 1341 of file MultiApp.C.
{
  const std::string multiapp_name =
      getMultiAppName(name(), _first_local_app + index, _total_num_apps);
  _apps[index]->setOutputFileBase(_app.getOutputFileBase() + "_" + multiapp_name);
}
setupApp()
void TransientMultiApp::setupApp (unsigned int i, Real time = 0.0) private inherited
Setup the executioner for the local app.
Parameters
i The local app number for the app that needs to be setup.
time The time to set as the current time for the App
Definition at line 665 of file TransientMultiApp.C.
{
  auto & app = _apps[i];
  Transient * ex = dynamic_cast<Transient *>(app->getExecutioner());
  if (!ex)
    mooseError("MultiApp ", name(), " is not using a Transient Executioner!");
  // Get the FEProblemBase for the current MultiApp
  FEProblemBase & problem = appProblemBase(_first_local_app + i);
  // Update the file numbers for the outputs from the parent application
  app->getOutputWarehouse().setFileNumbers(_app.getOutputFileNumbers());
  // Add these vectors before we call init on the executioner because that will try to restore these
  // vectors in a restart context
  if (_interpolate_transfers)
  {
    AuxiliarySystem & aux_system = problem.getAuxiliarySystem();
    System & libmesh_aux_system = aux_system.system();
    // We'll store a copy of the auxiliary system's solution at the old time in here
    libmesh_aux_system.add_vector("transfer_old", false);
    // This will be where we'll transfer the value to for the "target" time
    libmesh_aux_system.add_vector("transfer", false);
  }
  // Call initialization method of Executioner (Note, this performs the output of the initial time
  // step, if desired)
  ex->init();
  ex->preExecute();
  if (!_app.isRecovering())
  {
    problem.timeStep()++;
    problem.advanceState();
  }
  _transient_executioners[i] = ex;
}
Referenced by TransientMultiApp::initialSetup(), and TransientMultiApp::resetApp().
setupPositions()
void MultiApp::setupPositions () inherited
Called just after construction to allow derived classes to set _positions and create sub-apps accordingly.
Definition at line 350 of file MultiApp.C.
{
  if (_use_positions)
  {
    fillPositions();
    init(_positions.size());
    createApps();
  }
}
solveStep()
bool TransientMultiApp::solveStep (Real dt, Real target_time, bool auto_advance = true) override virtual inherited
Re-solve all of the Apps.
Can be called multiple times to resolve the same timestep if auto_advance=false. Time is not actually advanced until advanceStep() is called.
Note that auto_advance=false might not be compatible with the options for the MultiApp
Returns
Whether or not all of the solves were successful (i.e. all solves made it to the target_time)
Implements MultiApp.
Definition at line 181 of file TransientMultiApp.C.
{
  if (!_has_an_app)
    return true;
  TIME_SECTION(_solve_step_timer);
  _auto_advance = auto_advance;
  if (_fe_problem.verboseMultiApps())
    _console << COLOR_CYAN << "Solving MultiApp '" << name() << "' with target time " << target_time
             << " and dt " << dt << " with auto-advance " << (auto_advance ? "on" : "off")
             << COLOR_DEFAULT << std::endl;
  // "target_time" must always be in global time
  target_time += _app.getGlobalTimeOffset();
  Moose::ScopedCommSwapper swapper(_my_comm);
  bool return_value = true;
  // Make sure we swap back the communicator regardless of how this routine is exited
  try
  {
    int rank;
    int ierr;
    ierr = MPI_Comm_rank(_communicator.get(), &rank);
    mooseCheckMPIErr(ierr);
    for (unsigned int i = 0; i < _my_num_apps; i++)
    {
      FEProblemBase & problem = appProblemBase(_first_local_app + i);
      Transient * ex = _transient_executioners[i];
      // The App might have a different local time from the rest of the problem
      Real app_time_offset = _apps[i]->getGlobalTimeOffset();
      // Maybe this MultiApp was already solved
      if ((ex->getTime() + app_time_offset + ex->timestepTol() >= target_time) ||
          (ex->getTime() >= ex->endTime()))
        continue;
      // Examine global time synchronization
      if (!_sub_cycling && !_reset_happened.size())
      {
        // The multi-app general offset is substracted to go into local time.
        if (std::abs(target_time - _app.getGlobalTimeOffset() - ex->getTime() - dt) >
            ex->timestepTol())
          mooseDoOnce(mooseWarning(
              "The target time (time a multiapp must reach at the end of the time step) "
              "is desynchronized between this app and subapp ",
              i,
              ".\n If this is desired: use the 'global_time_offset' multiapp parameter to "
              "declare a constant offset\n"
              "If the apps should (eventually) be synchronized in time, please either: \n"
              "  - match the 'start_time' in the main app and the multiapp, in the Executioner "
              "block\n"
              "  - set 'sub_cycling' to true in the multiapp parameters\n"
              "This message will only print once for all apps and all time steps."));
      }
      if (_sub_cycling)
      {
        Real time_old = ex->getTime() + app_time_offset;
        if (_interpolate_transfers)
        {
          AuxiliarySystem & aux_system = problem.getAuxiliarySystem();
          System & libmesh_aux_system = aux_system.system();
          NumericVector<Number> & solution = *libmesh_aux_system.solution;
          NumericVector<Number> & transfer_old = libmesh_aux_system.get_vector("transfer_old");
          solution.close();
          // Save off the current auxiliary solution
          transfer_old = solution;
          transfer_old.close();
          // Snag all of the local dof indices for all of these variables
          AllLocalDofIndicesThread aldit(problem, _transferred_vars);
          ConstElemRange & elem_range = *problem.mesh().getActiveLocalElementRange();
          Threads::parallel_reduce(elem_range, aldit);
          _transferred_dofs = aldit.getDofIndices();
        }
        // Disable/enable output for sub cycling
        problem.allowOutput(_output_sub_cycles);         // disables all outputs, including console
        problem.allowOutput<Console>(_print_sub_cycles); // re-enables Console to print, if desired
        ex->setTargetTime(target_time - app_time_offset);
        //      unsigned int failures = 0;
        bool at_steady = false;
        // ADL: During restart, there is already an FEProblemBase::advanceState that occurs at the
        // end of TransientMultiApp::setupApp. advanceState, along with copying the solutions
        // backwards in time/state, also *moves* (note it doesn't copy!) stateful material
        // properties backwards (through swapping). So if restarting from a full-solve steady
        // multi-app for example, then after one advance state, we will have good information in old
        // and no information in current. But then if we advance again we no longer have good data
        // in the old material properties, so don't advance here if we're restarting
        if (_first && !_app.isRecovering() && !_app.isRestarting())
          problem.advanceState();
        bool local_first = _first;
        // Now do all of the solves we need
        while ((!at_steady && ex->getTime() + app_time_offset + ex->timestepTol() < target_time) ||
               !ex->lastSolveConverged())
        {
          if (local_first != true)
            ex->incrementStepOrReject();
          local_first = false;
          ex->preStep();
          ex->computeDT();
          if (_interpolate_transfers)
          {
            // See what time this executioner is going to go to.
            Real future_time = ex->getTime() + app_time_offset + ex->getDT();
            // How far along we are towards the target time:
            Real step_percent = (future_time - time_old) / (target_time - time_old);
            Real one_minus_step_percent = 1.0 - step_percent;
            // Do the interpolation for each variable that was transferred to
            FEProblemBase & problem = appProblemBase(_first_local_app + i);
            AuxiliarySystem & aux_system = problem.getAuxiliarySystem();
            System & libmesh_aux_system = aux_system.system();
            NumericVector<Number> & solution = *libmesh_aux_system.solution;
            NumericVector<Number> & transfer = libmesh_aux_system.get_vector("transfer");
            NumericVector<Number> & transfer_old = libmesh_aux_system.get_vector("transfer_old");
            solution.close(); // Just to be sure
            transfer.close();
            transfer_old.close();
            for (const auto & dof : _transferred_dofs)
            {
              solution.set(dof,
                           (transfer_old(dof) * one_minus_step_percent) +
                               (transfer(dof) * step_percent));
              //            solution.set(dof, transfer_old(dof));
              //            solution.set(dof, transfer(dof));
              //            solution.set(dof, 1);
            }
            solution.close();
          }
          ex->takeStep();
          bool converged = ex->lastSolveConverged();
          if (!converged)
          {
            mooseWarning(
                "While sub_cycling ", name(), _first_local_app + i, " failed to converge!\n");
            _failures++;
            if (_failures > _max_failures)
            {
              std::stringstream oss;
              oss << "While sub_cycling " << name() << _first_local_app << i << " REALLY failed!";
              throw MultiAppSolveFailure(oss.str());
            }
          }
          Real solution_change_norm = ex->getSolutionChangeNorm();
          if (_detect_steady_state && _fe_problem.verboseMultiApps())
            _console << "Solution change norm: " << solution_change_norm << std::endl;
          if (converged && _detect_steady_state && solution_change_norm < _steady_state_tol)
          {
            if (_fe_problem.verboseMultiApps())
              _console << "Detected Steady State! Fast-forwarding to " << target_time << std::endl;
            at_steady = true;
            // Indicate that the next output call (occurs in ex->endStep()) should output,
            // regardless of intervals etc...
            problem.forceOutput();
            // Clean up the end
            ex->endStep(target_time - app_time_offset);
            ex->postStep();
          }
          else
          {
            ex->endStep();
            ex->postStep();
          }
        }
        // If we were looking for a steady state, but didn't reach one, we still need to output one
        // more time, regardless of interval
        // Note: if we turn off the output for all time steps for sub-cycling, we still need to
        // have one output at the end.
        if ((!at_steady && _detect_steady_state) || !_output_sub_cycles)
          problem.outputStep(EXEC_FORCED);
      } // sub_cycling
      else if (_tolerate_failure)
      {
        ex->takeStep(dt);
        ex->endStep(target_time - app_time_offset);
        ex->postStep();
      }
      else
      {
        // ADL: During restart, there is already an FEProblemBase::advanceState that occurs at the
        // end of TransientMultiApp::setupApp. advanceState, along with copying the solutions
        // backwards in time/state, also *moves* (note it doesn't copy!) stateful material
        // properties backwards (through swapping). So if restarting from a full-solve steady
        // multi-app for example, then after one advance state, we will have good information in old
        // and no information in current. But then if we advance again we no longer have good data
        // in the old material properties, so don't advance here if we're restarting
        if (_first && !_app.isRecovering() && !_app.isRestarting())
          problem.advanceState();
        if (auto_advance)
          problem.allowOutput(true);
        ex->takeStep(dt);
        if (auto_advance)
        {
          ex->endStep();
          ex->postStep();
          if (!ex->lastSolveConverged())
          {
            mooseWarning(name(), _first_local_app + i, " failed to converge!\n");
            if (_catch_up)
            {
              if (_fe_problem.verboseMultiApps())
                _console << "Starting time step catch up!" << std::endl;
              bool caught_up = false;
              unsigned int catch_up_step = 0;
              // Cut the timestep in half to first try two half-step solves
              Real catch_up_dt = dt / 2;
              Real catch_up_time = 0;
              while (!caught_up && catch_up_step < _max_catch_up_steps)
              {
                if (_fe_problem.verboseMultiApps())
                  _console << "Solving " << name() << " catch up step " << catch_up_step
                           << std::endl;
                ex->incrementStepOrReject();
                // Avoid numerical precision errors on target time
                if (catch_up_time + catch_up_dt > dt)
                  catch_up_dt = dt - catch_up_time;
                ex->computeDT();
                ex->takeStep(catch_up_dt);
                ex->endStep();
                if (ex->lastSolveConverged())
                {
                  catch_up_time += catch_up_dt;
                  if (std::abs(catch_up_time - dt) <
                      (1 + std::abs(ex->getTime())) * ex->timestepTol())
                  {
                    problem.outputStep(EXEC_FORCED);
                    caught_up = true;
                  }
                }
                else
                  // Keep cutting time step in half until it converges
                  catch_up_dt /= 2.0;
                ex->postStep();
                catch_up_step++;
              }
              if (!caught_up)
                throw MultiAppSolveFailure(name() + " Failed to catch up!\n");
            }
          }
        }
        else // auto_advance == false
        {
          if (!ex->lastSolveConverged())
          {
            // Even if we don't allow auto_advance - we can still catch up to the current time if
            // possible
            if (_catch_up)
            {
              if (_fe_problem.verboseMultiApps())
                _console << "Starting Catch Up!" << std::endl;
              bool caught_up = false;
              unsigned int catch_up_step = 0;
              Real catch_up_dt = dt / 2;
              // Note: this loop will _break_ if target_time is satisfied
              while (catch_up_step < _max_catch_up_steps)
              {
                if (_fe_problem.verboseMultiApps())
                  _console << "Solving " << name() << " catch up step " << catch_up_step
                           << std::endl;
                ex->incrementStepOrReject();
                ex->computeDT();
                ex->takeStep(catch_up_dt); // Cut the timestep in half to try two half-step solves
                // This is required because we can't call endStep() yet
                // (which normally increments time)
                Real current_time = ex->getTime() + ex->getDT();
                if (ex->lastSolveConverged())
                {
                  if (current_time + app_time_offset +
                          (ex->timestepTol() * std::abs(current_time)) >=
                      target_time)
                  {
                    caught_up = true;
                    break; // break here so that we don't run endStep() or postStep() since this
                           // MultiApp should NOT be auto_advanced
                  }
                }
                else
                  catch_up_dt /= 2.0;
                ex->endStep();
                ex->postStep();
                catch_up_step++;
              }
              if (!caught_up)
                throw MultiAppSolveFailure(name() + " Failed to catch up!\n");
            }
            else
              throw MultiAppSolveFailure(name() + " failed to converge");
          }
        }
      }
      // Re-enable all output (it may of been disabled by sub-cycling)
      problem.allowOutput(true);
    }
    _first = false;
    if (_fe_problem.verboseMultiApps())
      _console << "Successfully Solved MultiApp " << name() << "." << std::endl;
  }
  catch (MultiAppSolveFailure & e)
  {
    mooseWarning(e.what());
    _console << "Failed to Solve MultiApp " << name() << ", attempting to recover." << std::endl;
    return_value = false;
  }
  _transferred_vars.clear();
  return return_value;
}
subdomainSetup()
void SetupInterface::subdomainSetup () virtual inherited
Gets called when the subdomain changes (i.e.
in a Jacobian or residual loop) and before this object is asked to do its job
Reimplemented in Material, MaterialBase, GeneralUserObject, NodalUserObject, ThreadedGeneralUserObject, and Constraint.
Definition at line 60 of file SetupInterface.C.
{
}
timedSectionName()
std::string PerfGraphInterface::timedSectionName (const std::string & section_name) const protected inherited
Returns
The name of the timed section with the name section_name.
Optionally adds a prefix if one is defined.
Definition at line 47 of file PerfGraphInterface.C.
{
  return _prefix.empty() ? "" : (_prefix + "::") + section_name;
}
Referenced by PerfGraphInterface::registerTimedSection().
timestepSetup()
void SetupInterface::timestepSetup () virtual inherited
Gets called at the beginning of the timestep before this object is asked to do its job.
Reimplemented in VectorPostprocessorVisualizationAux, EqualValueEmbeddedConstraint, Function, Console, JSONOutput, Positions, MemoryUsage, NumNonlinearIterations, Times, SolutionUserObject, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, MooseVariableFV< T >, and VectorMemoryUsage.
Definition at line 45 of file SetupInterface.C.
{
}
Referenced by JSONOutput::timestepSetup(), and MooseVariableField< OutputType >::timestepSetup().
transformBoundingBox()
void MultiApp::transformBoundingBox (BoundingBox & box, const MultiAppCoordTransform & transform) static inherited
Transform a bounding box according to the transformations in the provided coordinate transformation object.
Definition at line 821 of file MultiApp.C.
{
  const Real min_x = box.first(0);
  const Real max_x = box.second(0);
  const Real min_y = box.first(1);
  const Real max_y = box.second(1);
  const Real min_z = box.first(2);
  const Real max_z = box.second(2);
  std::array<Point, 8> box_corners = {{Point(min_x, min_y, min_z),
                                       Point(max_x, min_y, min_z),
                                       Point(min_x, max_y, min_z),
                                       Point(max_x, max_y, min_z),
                                       Point(min_x, min_y, max_z),
                                       Point(max_x, min_y, max_z),
                                       Point(min_x, max_y, max_z),
                                       Point(max_x, max_y, max_z)}};
  // transform each corner
  for (auto & corner : box_corners)
    corner = transform(corner);
  // Create new bounding box
  Point new_box_min = box_corners[0];
  Point new_box_max = new_box_min;
  for (const auto p : make_range(1, 8))
    for (const auto d : make_range(Moose::dim))
    {
      const Point & pt = box_corners[p];
      if (new_box_min(d) > pt(d))
        new_box_min(d) = pt(d);
      if (new_box_max(d) < pt(d))
        new_box_max(d) = pt(d);
    }
  box.first = new_box_min;
  box.second = new_box_max;
}
Referenced by MultiApp::getBoundingBox(), and MultiAppTransfer::transformBoundingBox().
type()
const std::string & MooseBase::type () const inline inherited
Get the type of this class.
Returns
the name of the type of this class
Definition at line 41 of file MooseBase.h.
{ return _type; }
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), CreateProblemDefaultAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetupDebugAction::act(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::addDistribution(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addObject(), DistributedRectilinearMeshGenerator::addPoint(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), PhysicsBasedPreconditioner::addSystem(), FEProblemBase::addTimeIntegrator(), SubProblem::addVectorTag(), DisplacedProblem::addVectorTag(), FEProblemBase::advanceMultiApps(), FEProblemBase::backupMultiApps(), BoundaryPreservedMarker::BoundaryPreservedMarker(), DistributedRectilinearMeshGenerator::buildCube(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildPRefinementAndCoarseningMaps(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), FEProblemBase::computeAuxiliaryKernels(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpJacobian(), HFEMDirichletBC::computeLowerDQpJacobian(), ArrayHFEMDiffusion::computeLowerDQpJacobian(), HFEMDiffusion::computeLowerDQpJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), FEProblemBase::computeMultiAppsDT(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), DGCoupledAdvection::computeOffDiagJacobianHelper(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ScalarKernel::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueBoundaryConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), LinearNodalConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), DGConvection::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), InterfaceDiffusion::computeQpJacobian(), InterfaceReaction::computeQpJacobian(), DGCoupledAdvection::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), DGFunctionTemperatureAdvection::computeQpJacobian(), DGTemperatureAdvection::computeQpJacobian(), InterTemperatureAdvection::computeQpJacobian(), CoupledTiedValueConstraint::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), HFEMTestJump::computeQpOffDiagJacobian(), HFEMTrialJump::computeQpOffDiagJacobian(), DGCoupledAdvection::computeQpOffDiagJacobian(), ScalarKernel::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), EqualValueBoundaryConstraint::computeQpResidual(), EqualValueEmbeddedConstraint::computeQpResidual(), LinearNodalConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), DGConvection::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), DGEFieldAdvection::computeQpResidual(), HphiRadialInterface::computeQpResidual(), InterfaceAdvection::computeQpResidual(), InterfaceLogDiffusionElectrons::computeQpResidual(), PotentialSurfaceCharge::computeQpResidual(), ADDGAdvection::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), HFEMDiffusion::computeQpResidual(), HFEMTestJump::computeQpResidual(), HFEMTrialJump::computeQpResidual(), InterfaceDiffusion::computeQpResidual(), InterfaceReaction::computeQpResidual(), DGCoupledAdvection::computeQpResidual(), DGFunctionConvection::computeQpResidual(), DGFunctionTemperatureAdvection::computeQpResidual(), DGTemperatureAdvection::computeQpResidual(), InterTemperatureAdvection::computeQpResidual(), ArrayDGDiffusion::computeQpResidual(), ArrayHFEMDiffusion::computeQpResidual(), FEProblemBase::computeUserObjectByName(), FEProblemBase::computeUserObjects(), FEProblemBase::computeUserObjectsInternal(), BatchMaterial< Tuple, Output, Input >::construct(), DisplacedProblem::createQRules(), FEProblemBase::createQRules(), MeshGenerator::declareMeshProperty(), DumpObjectsProblem::deduceNecessaryParameters(), DumpObjectsProblem::dumpObjectHelper(), FEProblemBase::duplicateVariableCheck(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), MooseBaseErrorInterface::errorPrefix(), AB2PredictorCorrector::estimateTimeError(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finishMultiAppStep(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), ElementSubdomainIDGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), PatternedMeshGenerator::generate(), MeshGenerator::generateInternal(), MultiAppTransfer::getAppInfo(), TransfiniteMeshGenerator::getEdge(), ElementGenerator::getElemType(), FEProblemBase::getMaterial(), FEProblemBase::getMaterialData(), MaterialOutputAction::getParams(), ReporterData::getReporterInfo(), Transient::getTimeIntegratorName(), FEProblemBase::getTransfers(), SubProblem::getVectorTags(), DisplacedProblem::getVectorTags(), CommonOutputAction::hasConsole(), FEProblemBase::hasMultiApps(), AdvancedOutput::hasOutput(), FEProblemBase::incrementMultiAppTStep(), AdvancedOutput::initAvailableLists(), FunctorPositions::initialize(), FunctorTimes::initialize(), MultiAppConservativeTransfer::initialSetup(), ArrayDGDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), RelationshipManager::isType(), FEProblemBase::logAdd(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), SubProblem::numVectorTags(), DisplacedProblem::numVectorTags(), MooseBaseParameterInterface::objectErrorPrefix(), AdvancedOutput::output(), Console::output(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), ProjectedStatefulMaterialStorageAction::processProperty(), SolutionInvalidInterface::registerInvalidSolutionInternal(), FEProblemBase::restoreMultiApps(), MeshRepairGenerator::separateSubdomainsByElementType(), FEProblemBase::setCoupling(), MooseBase::typeAndName(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), DisplacedProblem::updateGeomSearch(), FEProblemBase::updateGeomSearch(), UserObjectInterface::userObjectType(), and AdvancedOutput::wantOutput().
typeAndName()
std::string MooseBase::typeAndName () const inline inherited
Get the class's combined type and name; useful in error handling.
Returns
The type and name of this class in the form '<type()> "<name()>"'.
Definition at line 53 of file MooseBase.h.
  {
    return type() + std::string(" \"") + name() + std::string("\"");
  }
Referenced by ReporterContext< T >::finalize(), and ReporterData::getReporterInfo().
uniqueName()
MooseObjectName MooseBaseParameterInterface::uniqueName () const inline inherited
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
Definition at line 58 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectName(_pars.get<std::string>("_unique_name"));
  }
Referenced by MooseBaseParameterInterface::connectControllableParams(), and Action::uniqueActionName().
uniqueParameterName()
MooseObjectParameterName MooseBaseParameterInterface::uniqueParameterName (const std::string & parameter_name) const inline inherited
The unique parameter name of a valid parameter of this object for accessing parameter controls.
Definition at line 43 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectParameterName(
        _pars.get<std::string>("_moose_base"), _moose_base->name(), parameter_name);
  }
usingPositions()
bool MultiApp::usingPositions () const inline inherited
Whether or not this MultiApp is using positions or its own way for constructing sub-apps.
Definition at line 361 of file MultiApp.h.
{ return _use_positions; }
Referenced by MultiApp::createApp(), and MultiApp::preTransfer().
validParams()
InputParameters QuadraturePointMultiApp::validParams () static
Definition at line 25 of file QuadraturePointMultiApp.C.
{
  InputParameters params = TransientMultiApp::validParams();
  params += BlockRestrictable::validParams();
  params.addClassDescription(
      "Automatically generates sub-App positions from the elemental quadrature points, with the "
      "default quadrature, in the parent mesh.");
  params.suppressParameter<std::vector<Point>>("positions");
  params.suppressParameter<std::vector<FileName>>("positions_file");
  params.suppressParameter<std::vector<PositionsName>>("positions_objects");
  return params;
}
Member Data Documentation
_action_factory
ActionFactory& MooseBaseParameterInterface::_action_factory protected inherited
Builds Actions.
Definition at line 164 of file MooseBaseParameterInterface.h.
Referenced by CommonOutputAction::create(), AddVariableAction::createInitialConditionAction(), AddSpecies::createInitialConditions(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
_app
MooseApp& MooseBase::_app protected inherited
The MOOSE application this is associated with.
Definition at line 60 of file MooseBase.h.
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), MeshGenerator::addChildMeshGenerator(), FEProblemBase::addMaterialHelper(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addOutput(), MeshGenerator::addParentMeshGenerator(), FVFluxKernel::adjustRMGhostLayers(), FEProblemBase::allowOutput(), AStableDirk4::AStableDirk4(), FileMesh::buildMesh(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), MeshGenerator::checkGetMesh(), FEProblemBase::checkICRestartError(), FEProblemBase::checkNonlinearConvergence(), OversampleOutput::cloneMesh(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), Console::Console(), TimeStepper::constrainStep(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::createLocalApp(), FEProblemBase::customSetup(), MeshGenerator::declareMeshProperty(), MeshGenerator::declareNullMeshName(), MooseMesh::determineUseDistributedMesh(), DumpObjectsProblem::dumpObjectHelper(), DumpObjectsProblem::dumpVariableHelper(), EigenExecutionerBase::EigenExecutionerBase(), EigenKernel::EigenKernel(), PIDTransientControl::execute(), Eigenvalue::execute(), InversePowerMethod::execute(), NonlinearEigen::execute(), Steady::execute(), Transient::execute(), PseudoTimestep::execute(), IterationInfo::execute(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FileOutput::FileOutput(), ChangeOverFixedPointPostprocessor::finalize(), RadialAverage::finalize(), FixedPointSolve::FixedPointSolve(), FEProblemBase::forceOutput(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), SideSetsFromNormalsGenerator::generate(), MeshGenerator::generateInternal(), FEProblemBase::getExecutor(), MeshGenerator::getMeshByName(), NumFixedPointIterations::getValue(), NumRelationshipManagers::getValue(), GhostingUserObject::GhostingUserObject(), MooseMesh::init(), InversePowerMethod::init(), NonlinearEigen::init(), Transient::init(), FEProblemBase::init(), TimePeriod::initialSetup(), Console::initialSetup(), AdvancedOutput::initOutputList(), FEProblemBase::initPetscOutput(), EigenProblem::initPetscOutput(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MeshGenerator::MeshGenerator(), EigenExecutionerBase::normalizeSolution(), NumFailedTimeSteps::NumFailedTimeSteps(), AugmentSparsityOnInterface::operator()(), Checkpoint::output(), Exodus::output(), Nemesis::output(), PerfGraphOutput::output(), Tecplot::output(), MortarNodalGeometryOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Exodus::outputEmptyTimestep(), Console::outputInput(), Exodus::outputInput(), Exodus::outputNodalVariables(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), Console::outputSystemInformation(), JSONOutput::outputSystemInformation(), MultiApp::parentOutputPositionChanged(), PIDTransientControl::PIDTransientControl(), Transient::preExecute(), Eigenvalue::prepareSolverOptions(), FEProblemBase::projectSolution(), MultiApp::setAppOutputFileBase(), FileOutput::setFileBaseInternal(), MeshGenerator::setMeshProperty(), MeshGenerator::setMeshPropertyHelper(), FEProblemBase::setRestartFile(), TransientMultiApp::setupApp(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SolutionInvalidityReporter::SolutionInvalidityReporter(), FEProblemBase::solve(), EigenProblem::solve(), PetscOutput::solveSetup(), TransientMultiApp::solveStep(), FEProblemBase::subdomainSetup(), FEProblemBase::theWarehouse(), TimeExtremeValue::TimeExtremeValue(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), Transient::Transient(), FEProblemBase::updateMortarMesh(), Console::write(), and FEProblemBase::~FEProblemBase().
_app_type
std::string MultiApp::_app_type protected inherited
The type of application to build.
Definition at line 482 of file MultiApp.h.
Referenced by MultiApp::createApp(), and MultiApp::createApps().
_apps
std::vector<std::shared_ptr<MooseApp> > MultiApp::_apps protected inherited
Pointers to each of the Apps.
Definition at line 538 of file MultiApp.h.
Referenced by MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::backup(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::createLocalApp(), MultiApp::finalize(), MultiApp::getBoundingBox(), MultiApp::getExecutioner(), TransientMultiApp::incrementTStep(), FullSolveMultiApp::initialSetup(), MultiApp::localApp(), MultiApp::moveApp(), MultiApp::numLocalApps(), MultiApp::parentOutputPositionChanged(), MultiApp::postExecute(), MultiApp::preTransfer(), TransientMultiApp::resetApp(), MultiApp::resetApp(), MultiApp::restore(), MultiApp::setAppOutputFileBase(), TransientMultiApp::setupApp(), FullSolveMultiApp::showStatusMessage(), FullSolveMultiApp::solveStep(), and TransientMultiApp::solveStep().
_associated_transfers
std::vector<MultiAppTransfer *> MultiApp::_associated_transfers protected inherited
Transfers associated with this multiapp.
Definition at line 604 of file MultiApp.h.
Referenced by MultiApp::addAssociatedTransfer(), and MultiApp::preTransfer().
_auto_advance
bool TransientMultiApp::_auto_advance private inherited
Definition at line 86 of file TransientMultiApp.h.
Referenced by TransientMultiApp::needsRestoration(), and TransientMultiApp::solveStep().
_backup_timer
const PerfID MultiApp::_backup_timer protected inherited
Definition at line 615 of file MultiApp.h.
Referenced by MultiApp::backup().
_blk_dim
unsigned int BlockRestrictable::_blk_dim private inherited
Largest mesh dimension of the elements in the blocks for this object.
Definition at line 259 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blocksMaxDimension(), and BlockRestrictable::initializeBlockRestrictable().
_blk_dual_restrictable
const bool BlockRestrictable::_blk_dual_restrictable private inherited
Flag for allowing dual restriction.
Definition at line 238 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_blk_feproblem
FEProblemBase* BlockRestrictable::_blk_feproblem private inherited
Pointer to FEProblemBase.
Definition at line 241 of file BlockRestrictable.h.
Referenced by BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), and BlockRestrictable::initializeBlockRestrictable().
_blk_ids
std::set<SubdomainID> BlockRestrictable::_blk_ids private inherited
Set of block ids supplied by the user via the input file (for error checking)
Definition at line 229 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blockIDs(), BlockRestrictable::blockRestricted(), BlockRestrictable::checkVariable(), BlockRestrictable::hasBlocks(), BlockRestrictable::initializeBlockRestrictable(), BlockRestrictable::isBlockSubset(), and BlockRestrictable::numBlocks().
_blk_material_data
const MaterialData* BlockRestrictable::_blk_material_data protected inherited
Pointer to the MaterialData class for this object.
Definition at line 207 of file BlockRestrictable.h.
Referenced by BlockRestrictable::hasBlockMaterialProperty(), and BlockRestrictable::initializeBlockRestrictable().
_blk_mesh
MooseMesh* BlockRestrictable::_blk_mesh private inherited
Pointer to Mesh.
Definition at line 244 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blockIDs(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlocks(), BlockRestrictable::initializeBlockRestrictable(), BlockRestrictable::isBlockSubset(), and BlockRestrictable::meshBlockIDs().
_blk_name
const std::string& BlockRestrictable::_blk_name private inherited
Name of the object.
Definition at line 256 of file BlockRestrictable.h.
Referenced by BlockRestrictable::checkVariable(), and BlockRestrictable::initializeBlockRestrictable().
_blk_tid
THREAD_ID BlockRestrictable::_blk_tid private inherited
Thread id for this object.
Definition at line 253 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_blocks
std::vector<SubdomainName> BlockRestrictable::_blocks private inherited
Vector the block names supplied by the user via the input file.
Definition at line 235 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blocks(), and BlockRestrictable::initializeBlockRestrictable().
_boundary_ids
const std::set<BoundaryID>& BlockRestrictable::_boundary_ids private inherited
Reference to the boundary_ids, defaults to an empty set if not provided.
Definition at line 250 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_bounding_box
std::vector<BoundingBox> MultiApp::_bounding_box protected inherited
This multi-app's bounding box.
Definition at line 544 of file MultiApp.h.
Referenced by MultiApp::getBoundingBox(), and MultiApp::init().
_bounding_box_padding
Point MultiApp::_bounding_box_padding protected inherited
Additional padding added to the bounding box, useful for 1D meshes.
Definition at line 550 of file MultiApp.h.
Referenced by MultiApp::getBoundingBox().
_catch_up
bool TransientMultiApp::_catch_up private inherited
Definition at line 72 of file TransientMultiApp.h.
Referenced by TransientMultiApp::needsRestoration(), TransientMultiApp::solveStep(), and TransientMultiApp::TransientMultiApp().
_cli_args
const std::vector<CLIArgString>& MultiApp::_cli_args protected inherited
CommandLine arguments.
Definition at line 589 of file MultiApp.h.
Referenced by MultiApp::cliArgs(), and MultiApp::init().
_cli_args_from_file
std::vector<std::string> MultiApp::_cli_args_from_file protected inherited
CommandLine arguments from files.
Definition at line 592 of file MultiApp.h.
Referenced by MultiApp::createApp(), MultiApp::getCommandLineArgsParamHelper(), and MultiApp::readCommandLineArguments().
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_current_execute_flag
const ExecFlagType& SetupInterface::_current_execute_flag protected inherited
Reference to FEProblemBase.
Definition at line 78 of file SetupInterface.h.
Referenced by PseudoTimestep::execute().
_detect_steady_state
bool TransientMultiApp::_detect_steady_state private inherited
Definition at line 63 of file TransientMultiApp.h.
Referenced by TransientMultiApp::needsRestoration(), and TransientMultiApp::solveStep().
_empty_boundary_ids
const std::set<BoundaryID> BlockRestrictable::_empty_boundary_ids private inherited
An empty set for referencing when boundary_ids is not included.
Definition at line 247 of file BlockRestrictable.h.
_empty_execute_enum
ExecFlagEnum SetupInterface::_empty_execute_enum private inherited
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
This is private because others should not be messing with it.
Definition at line 71 of file SetupInterface.h.
Referenced by SetupInterface::SetupInterface().
_enabled
const bool& MooseObject::_enabled protected inherited
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
Definition at line 58 of file MooseObject.h.
Referenced by MooseObject::enabled().
_end_solutions
std::vector<std::unique_ptr<NumericVector<Real> > > MultiApp::_end_solutions protected inherited
The solution from the end of the previous solve, this is cloned from the Nonlinear solution during restore.
Definition at line 598 of file MultiApp.h.
Referenced by MultiApp::restore().
_execute_enum
const ExecFlagEnum& SetupInterface::_execute_enum protected inherited
Execute settings for this object.
Definition at line 75 of file SetupInterface.h.
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), SetupInterface::getExecuteOnEnum(), JSONOutput::outputReporters(), XMLOutput::outputVectorPostprocessors(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
_factory
Factory& MooseBaseParameterInterface::_factory protected inherited
The Factory associated with the MooseApp.
Definition at line 161 of file MooseBaseParameterInterface.h.
Referenced by AddGeneralReactions::act(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), ElementIDOutputAction::act(), AddSpecies::act(), AdaptivityAction::act(), AddControlAction::act(), AddNodalNormalsAction::act(), AddPeriodicBCAction::act(), AutoCheckpointAction::act(), ComposeTimeStepperAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DisplayGhostingAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), PartitionerAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SetupPreconditionerAction::act(), SetupPredictorAction::act(), SetupResidualDebugAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddGeneralReactions::addEEDFReactionKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddDriftDiffusionAction::addPosition(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), MooseBaseParameterInterface::connectControllableParams(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), MaterialOutputAction::getParams(), and ProjectedStatefulMaterialStorageAction::processProperty().
_failures
unsigned int TransientMultiApp::_failures private inherited
Definition at line 70 of file TransientMultiApp.h.
Referenced by TransientMultiApp::solveStep().
_fe_problem
FEProblemBase& MultiApp::_fe_problem protected inherited
The FEProblemBase this MultiApp is part of.
Definition at line 479 of file MultiApp.h.
Referenced by MultiApp::backup(), MultiApp::createApp(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), fillPositions(), MultiApp::preTransfer(), MultiApp::problemBase(), MultiApp::restore(), FullSolveMultiApp::showStatusMessage(), and TransientMultiApp::solveStep().
_first
bool& TransientMultiApp::_first private inherited
Is it our first time through the execution loop?
Definition at line 76 of file TransientMultiApp.h.
Referenced by TransientMultiApp::solveStep().
_first_local_app
unsigned int MultiApp::_first_local_app protected inherited
The number of the first app on this processor.
Definition at line 514 of file MultiApp.h.
Referenced by MultiApp::buildComm(), MultiApp::createApp(), MultiApp::firstLocalApp(), MultiApp::getCommandLineArgsParamHelper(), MultiApp::globalAppToLocal(), MultiApp::hasLocalApp(), MultiApp::parentOutputPositionChanged(), MultiApp::preTransfer(), MultiApp::setAppOutputFileBase(), TransientMultiApp::setupApp(), and TransientMultiApp::solveStep().
_global_time_offset
const Real MultiApp::_global_time_offset protected inherited
The offset time so the MultiApp local time relative to the global time.
Definition at line 562 of file MultiApp.h.
Referenced by MultiApp::createLocalApp().
_has_an_app
bool MultiApp::_has_an_app protected inherited
Whether or not this processor as an App at all
Definition at line 586 of file MultiApp.h.
Referenced by MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), MultiApp::buildComm(), TransientMultiApp::computeDT(), MultiApp::createApps(), MultiApp::getBoundingBox(), MultiApp::getExecutioner(), MultiApp::hasApp(), MultiApp::hasLocalApp(), FullSolveMultiApp::initialSetup(), TransientMultiApp::initialSetup(), FullSolveMultiApp::solveStep(), and TransientMultiApp::solveStep().
_has_bounding_box
std::vector<bool> MultiApp::_has_bounding_box protected inherited
Flag if this multi-app computed its bounding box (valid only for non-displaced meshes)
Definition at line 541 of file MultiApp.h.
Referenced by MultiApp::getBoundingBox(), and MultiApp::init().
_inflation
Real MultiApp::_inflation protected inherited
Relative bounding box inflation.
Definition at line 547 of file MultiApp.h.
Referenced by MultiApp::getBoundingBox().
_init_timer
const PerfID MultiApp::_init_timer protected inherited
Definition at line 614 of file MultiApp.h.
Referenced by MultiApp::init().
_input_files
std::vector<FileName> MultiApp::_input_files protected inherited
The input file for each app's simulation.
Definition at line 496 of file MultiApp.h.
Referenced by MultiApp::createApp(), and MultiApp::fillPositions().
_interpolate_transfers
bool TransientMultiApp::_interpolate_transfers private inherited
Definition at line 62 of file TransientMultiApp.h.
Referenced by TransientMultiApp::appTransferVector(), TransientMultiApp::setupApp(), TransientMultiApp::solveStep(), and TransientMultiApp::TransientMultiApp().
_keep_solution_during_restore
bool MultiApp::_keep_solution_during_restore protected inherited
Flag indicates if or not restart from the latest solution.
Definition at line 595 of file MultiApp.h.
Referenced by MultiApp::keepSolutionDuringRestore(), MultiApp::restore(), and TransientMultiApp::TransientMultiApp().
_max_catch_up_steps
Real TransientMultiApp::_max_catch_up_steps private inherited
Definition at line 73 of file TransientMultiApp.h.
Referenced by TransientMultiApp::solveStep().
_max_failures
unsigned int TransientMultiApp::_max_failures private inherited
Definition at line 67 of file TransientMultiApp.h.
Referenced by TransientMultiApp::solveStep().
_max_procs_per_app
processor_id_type MultiApp::_max_procs_per_app protected inherited
Maximum number of processors to give to each app.
Definition at line 553 of file MultiApp.h.
Referenced by MultiApp::init().
_metaname
const RestartableDataMapName Restartable::_metaname private inherited
Restartable metadata name.
Definition at line 240 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_min_procs_per_app
processor_id_type MultiApp::_min_procs_per_app protected inherited
Minimum number of processors to give to each app.
Definition at line 556 of file MultiApp.h.
Referenced by MultiApp::init().
_moose_base
const MooseBase* const MooseBaseParameterInterface::_moose_base private inherited
The MooseBase object that inherits this class.
Definition at line 168 of file MooseBaseParameterInterface.h.
Referenced by MooseBaseParameterInterface::connectControllableParams(), MooseBaseParameterInterface::objectErrorPrefix(), MooseBaseParameterInterface::paramError(), and MooseBaseParameterInterface::uniqueParameterName().
_move_apps
std::vector<unsigned int> MultiApp::_move_apps protected inherited
The apps to be moved.
Definition at line 577 of file MultiApp.h.
Referenced by MultiApp::fillPositions(), and MultiApp::preTransfer().
_move_happened
bool MultiApp::_move_happened protected inherited
Whether or not the move has happened.
Definition at line 583 of file MultiApp.h.
Referenced by MultiApp::preTransfer().
_move_positions
std::vector<Point> MultiApp::_move_positions protected inherited
The new positions for the apps to be moved.
Definition at line 580 of file MultiApp.h.
Referenced by MultiApp::fillPositions(), and MultiApp::preTransfer().
_move_time
Real MultiApp::_move_time protected inherited
The time at which to move apps.
Definition at line 574 of file MultiApp.h.
Referenced by MultiApp::preTransfer().
_my_comm
MPI_Comm& MultiApp::_my_comm protected inherited
The MPI communicator this object is going to use.
Definition at line 523 of file MultiApp.h.
Referenced by MultiApp::buildComm(), MultiApp::comm(), TransientMultiApp::computeDT(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::getBoundingBox(), FullSolveMultiApp::initialSetup(), TransientMultiApp::initialSetup(), TransientMultiApp::resetApp(), MultiApp::resetApp(), FullSolveMultiApp::solveStep(), and TransientMultiApp::solveStep().
_my_communicator
libMesh::Parallel::Communicator MultiApp::_my_communicator protected inherited
The communicator object that holds the MPI_Comm that we're going to use.
Definition at line 520 of file MultiApp.h.
Referenced by MultiApp::buildComm().
_my_num_apps
unsigned int MultiApp::_my_num_apps protected inherited
The number of apps this object is involved in simulating.
Definition at line 511 of file MultiApp.h.
Referenced by MultiApp::backup(), MultiApp::buildComm(), TransientMultiApp::computeDT(), MultiApp::createApps(), TransientMultiApp::finishStep(), MultiApp::globalAppToLocal(), MultiApp::hasLocalApp(), TransientMultiApp::incrementTStep(), MultiApp::init(), FullSolveMultiApp::initialSetup(), TransientMultiApp::initialSetup(), MultiApp::preTransfer(), MultiApp::restore(), MultiApp::setAppOutputFileBase(), FullSolveMultiApp::solveStep(), and TransientMultiApp::solveStep().
_my_rank
int MultiApp::_my_rank protected inherited
The mpi "rank" of this processor in the sub communicator.
Definition at line 535 of file MultiApp.h.
Referenced by MultiApp::buildComm(), and MultiApp::isRootProcessor().
_name
const std::string& MooseBase::_name protected inherited
The name of this class, reference to value stored in InputParameters.
Definition at line 66 of file MooseBase.h.
Referenced by AddFieldSplitAction::act(), AddBCAction::act(), AddConstraintAction::act(), AddControlAction::act(), AddDamperAction::act(), AddDGKernelAction::act(), AddDiracKernelAction::act(), AddDistributionAction::act(), AddFunctionAction::act(), AddFunctorMaterialAction::act(), AddFVBCAction::act(), AddFVInitialConditionAction::act(), AddFVInterfaceKernelAction::act(), AddFVKernelAction::act(), AddIndicatorAction::act(), AddInitialConditionAction::act(), AddInterfaceKernelAction::act(), AddKernelAction::act(), AddMarkerAction::act(), AddMaterialAction::act(), AddMeshDivisionAction::act(), AddMeshGeneratorAction::act(), AddMultiAppAction::act(), AddNodalKernelAction::act(), AddOutputAction::act(), AddPeriodicBCAction::act(), AddPositionsAction::act(), AddPostprocessorAction::act(), AddReporterAction::act(), AddSamplerAction::act(), AddScalarKernelAction::act(), AddTimesAction::act(), AddTimeStepperAction::act(), AddTransferAction::act(), AddUserObjectAction::act(), AddVectorPostprocessorAction::act(), PartitionerAction::act(), ReadExecutorParamsAction::act(), SetupPreconditionerAction::act(), SetupTimeIntegratorAction::act(), AddDriftDiffusionAction::addADKernels(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromXY(), PiecewiseLinearBase::buildInterpolation(), CombinerGenerator::CombinerGenerator(), Executor::Executor(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), fillPositions(), FunctionDT::FunctionDT(), FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), MooseBase::name(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), PiecewiseBase::setData(), and Split::setup().
_node_name
std::string MultiApp::_node_name protected inherited
Node Name.
Definition at line 532 of file MultiApp.h.
Referenced by MultiApp::buildComm().
_npositions_inputfile
std::vector<unsigned int> MultiApp::_npositions_inputfile protected inherited
Number of positions for each input file.
Definition at line 502 of file MultiApp.h.
Referenced by MultiApp::fillPositions(), and MultiApp::readCommandLineArguments().
_orig_comm
const MPI_Comm& MultiApp::_orig_comm protected inherited
The original comm handle.
Definition at line 517 of file MultiApp.h.
Referenced by MultiApp::createApps().
_orig_num_procs
int MultiApp::_orig_num_procs protected inherited
The number of processors in the original comm.
Definition at line 526 of file MultiApp.h.
Referenced by MultiApp::buildComm().
_orig_rank
int MultiApp::_orig_rank protected inherited
The mpi "rank" of this processor in the original communicator.
Definition at line 529 of file MultiApp.h.
Referenced by MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), MultiApp::buildComm(), MultiApp::getBoundingBox(), and MultiApp::getExecutioner().
_output_base
std::string MultiApp::_output_base protected inherited
The output file basename for each multiapp.
Definition at line 505 of file MultiApp.h.
_output_file_numbers
std::vector<std::map<std::string, unsigned int> > TransientMultiApp::_output_file_numbers private inherited
Definition at line 84 of file TransientMultiApp.h.
_output_in_position
bool MultiApp::_output_in_position protected inherited
Whether or not to move the output of the MultiApp into position.
Definition at line 559 of file MultiApp.h.
Referenced by MultiApp::createApp(), MultiApp::moveApp(), and MultiApp::parentOutputPositionChanged().
_output_sub_cycles
bool TransientMultiApp::_output_sub_cycles private inherited
Definition at line 65 of file TransientMultiApp.h.
Referenced by TransientMultiApp::solveStep().
_parent
const MooseObject & DataFileInterface< MooseObject >::_parent private inherited
Definition at line 46 of file DataFileInterface.h.
_pars
const InputParameters& MooseBaseParameterInterface::_pars protected inherited
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Definition at line 158 of file MooseBaseParameterInterface.h.
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), AddPeriodicBCAction::act(), AddVariableAction::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), FunctorMaterial::addFunctorPropertyByBlocks(), FVFluxKernel::adjustRMGhostLayers(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), PiecewiseTabularBase::buildFromFile(), PNGOutput::calculateRescalingValues(), BlockWeightedPartitioner::clone(), GridPartitioner::clone(), HierarchicalGridPartitioner::clone(), PetscExternalPartitioner::clone(), RandomPartitioner::clone(), SingleRankPartitioner::clone(), MooseBaseParameterInterface::connectControllableParams(), Console::Console(), AddVariableAction::createInitialConditionAction(), MaterialBase::declareADProperty(), MaterialBase::declareProperty(), FEProblemSolve::FEProblemSolve(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), FileMeshGenerator::generate(), MaterialBase::getGenericZeroMaterialProperty(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getParam(), MooseBaseParameterInterface::getRenamedParam(), AddVariableAction::init(), AdvancedOutput::initExecutionTypes(), Console::initialSetup(), MooseBaseParameterInterface::isParamSetByUser(), MooseBaseParameterInterface::isParamValid(), MultiApp::keepSolutionDuringRestore(), MooseBaseParameterInterface::paramErrorMsg(), GlobalParamsAction::parameters(), MooseBaseParameterInterface::parameters(), MooseMesh::prepare(), Eigenvalue::prepareSolverOptions(), MooseMesh::setCoordSystem(), MooseMesh::setPartitionerHelper(), SetupMeshAction::setupMesh(), Transient::setupTimeIntegrator(), MooseBaseParameterInterface::uniqueName(), and MooseBaseParameterInterface::uniqueParameterName().
_pg_moose_app
MooseApp& PerfGraphInterface::_pg_moose_app protected inherited
The MooseApp that owns the PerfGraph.
Definition at line 124 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::perfGraph().
_positions
std::vector<Point> MultiApp::_positions protected inherited
The positions of all of the apps, using input constant vectors (to be deprecated)
Definition at line 485 of file MultiApp.h.
Referenced by MultiApp::createApp(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), fillPositions(), MultiApp::moveApp(), MultiApp::parentOutputPositionChanged(), MultiApp::position(), MultiApp::preTransfer(), and MultiApp::setupPositions().
_positions_index_offsets
std::vector<unsigned int> MultiApp::_positions_index_offsets protected inherited
The offsets, in case multiple Positions objects are specified.
Definition at line 489 of file MultiApp.h.
Referenced by MultiApp::fillPositions(), and MultiApp::position().
_positions_objs
std::vector<const Positions *> MultiApp::_positions_objs protected inherited
The positions of all of the apps, using the Positions system.
Definition at line 487 of file MultiApp.h.
Referenced by MultiApp::fillPositions(), and MultiApp::position().
_prefix
const std::string PerfGraphInterface::_prefix protected inherited
A prefix to use for all sections.
Definition at line 127 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::timedSectionName().
_print_sub_cycles
bool TransientMultiApp::_print_sub_cycles private inherited
Flag for toggling console output on sub cycles.
Definition at line 91 of file TransientMultiApp.h.
Referenced by TransientMultiApp::solveStep().
_rank_config
LocalRankConfig MultiApp::_rank_config protected inherited
The app configuration resulting from calling init.
Definition at line 601 of file MultiApp.h.
Referenced by MultiApp::buildComm(), MultiApp::init(), and MultiApp::isFirstLocalRank().
_reset
std::set<unsigned int> TransientMultiApp::_reset private inherited
Definition at line 88 of file TransientMultiApp.h.
_reset_apps
std::vector<unsigned int> MultiApp::_reset_apps protected inherited
The apps to be reset.
Definition at line 568 of file MultiApp.h.
Referenced by MultiApp::MultiApp(), and MultiApp::preTransfer().
_reset_happened
std::vector<bool> MultiApp::_reset_happened protected inherited
Whether or not apps have been reset at each time.
Definition at line 571 of file MultiApp.h.
Referenced by MultiApp::init(), MultiApp::preTransfer(), and TransientMultiApp::solveStep().
_reset_timer
const PerfID MultiApp::_reset_timer protected inherited
Definition at line 617 of file MultiApp.h.
Referenced by MultiApp::resetApp().
_reset_times
std::vector<Real> MultiApp::_reset_times protected inherited
The times at which to reset apps.
Definition at line 565 of file MultiApp.h.
Referenced by MultiApp::init(), MultiApp::MultiApp(), and MultiApp::preTransfer().
_restartable_app
MooseApp& Restartable::_restartable_app protected inherited
Reference to the application.
Definition at line 227 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp(), and Restartable::registerRestartableNameWithFilterOnApp().
_restartable_name
std::string Restartable::_restartable_name private inherited
The name of the object.
Definition at line 243 of file Restartable.h.
Referenced by Restartable::declareRestartableDataWithObjectNameWithContext(), and Restartable::restartableName().
_restartable_read_only
const bool Restartable::_restartable_read_only protected inherited
Flag for toggling read only status (see ReporterData)
Definition at line 236 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_restartable_system_name
const std::string Restartable::_restartable_system_name protected inherited
The system name this object is in.
Definition at line 230 of file Restartable.h.
Referenced by Restartable::restartableName().
_restartable_tid
const THREAD_ID Restartable::_restartable_tid protected inherited
The thread ID for this object.
Definition at line 233 of file Restartable.h.
Referenced by Restartable::declareRestartableDataHelper().
_restore_timer
const PerfID MultiApp::_restore_timer protected inherited
Definition at line 616 of file MultiApp.h.
Referenced by MultiApp::restore().
_run_in_position
const bool MultiApp::_run_in_position protected inherited
Whether to run the child apps with their meshes transformed with the coordinate transforms.
Definition at line 607 of file MultiApp.h.
Referenced by MultiApp::createApp(), MultiApp::moveApp(), MultiApp::preTransfer(), and MultiApp::runningInPosition().
_solve_step_timer
const PerfID MultiApp::_solve_step_timer protected inherited
Timers.
Definition at line 613 of file MultiApp.h.
Referenced by FullSolveMultiApp::solveStep(), and TransientMultiApp::solveStep().
_steady_state_tol
Real TransientMultiApp::_steady_state_tol private inherited
Definition at line 64 of file TransientMultiApp.h.
Referenced by TransientMultiApp::solveStep().
_sub_app_backups
SubAppBackups& MultiApp::_sub_app_backups protected inherited
The cached subapp backups (passed from the parent app)
Definition at line 610 of file MultiApp.h.
Referenced by MultiApp::backup(), MultiApp::createApp(), MultiApp::init(), and MultiApp::restore().
_sub_cycling
bool TransientMultiApp::_sub_cycling private inherited
Definition at line 61 of file TransientMultiApp.h.
Referenced by TransientMultiApp::computeDT(), TransientMultiApp::finishStep(), TransientMultiApp::incrementTStep(), TransientMultiApp::needsRestoration(), TransientMultiApp::solveStep(), and TransientMultiApp::TransientMultiApp().
_tolerate_failure
bool TransientMultiApp::_tolerate_failure private inherited
Definition at line 68 of file TransientMultiApp.h.
Referenced by TransientMultiApp::computeDT(), TransientMultiApp::needsRestoration(), TransientMultiApp::solveStep(), and TransientMultiApp::TransientMultiApp().
_total_num_apps
unsigned int MultiApp::_total_num_apps protected inherited
The total number of apps to simulate.
Definition at line 508 of file MultiApp.h.
Referenced by MultiApp::buildComm(), MultiApp::createApp(), MultiApp::init(), MultiApp::numGlobalApps(), MultiApp::readCommandLineArguments(), and MultiApp::setAppOutputFileBase().
_transferred_dofs
std::set<dof_id_type> TransientMultiApp::_transferred_dofs private inherited
The DoFs associated with all of the currently transferred variables.
Definition at line 82 of file TransientMultiApp.h.
Referenced by TransientMultiApp::solveStep().
_transferred_vars
std::vector<std::string> TransientMultiApp::_transferred_vars private inherited
The variables that have been transferred to. Used when doing transfer interpolation. This will be cleared after each solve.
Definition at line 79 of file TransientMultiApp.h.
Referenced by TransientMultiApp::appTransferVector(), and TransientMultiApp::solveStep().
_transient_executioners
std::vector<Transient *> TransientMultiApp::_transient_executioners private inherited
Definition at line 59 of file TransientMultiApp.h.
Referenced by TransientMultiApp::computeDT(), TransientMultiApp::finishStep(), TransientMultiApp::incrementTStep(), TransientMultiApp::initialSetup(), TransientMultiApp::resetApp(), TransientMultiApp::setupApp(), and TransientMultiApp::solveStep().
_type
const std::string& MooseBase::_type protected inherited
The type of this class.
Definition at line 63 of file MooseBase.h.
Referenced by FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), FEProblemBase::init(), FEProblemBase::solverTypeString(), and MooseBase::type().
_use_positions
const bool MultiApp::_use_positions protected inherited
Toggle use of "positions".
Subapps are created at each different position. List of positions can be created using the Positions system
Definition at line 493 of file MultiApp.h.
Referenced by MultiApp::createApp(), MultiApp::initialSetup(), MultiApp::moveApp(), MultiApp::MultiApp(), MultiApp::parentOutputPositionChanged(), MultiApp::preTransfer(), MultiApp::setupPositions(), and MultiApp::usingPositions().
_vec_ids
std::vector<SubdomainID> BlockRestrictable::_vec_ids private inherited
Vector of block ids supplied by the user via the input file (for error reporting)
Definition at line 232 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_wait_for_first_app_init
const bool& MultiApp::_wait_for_first_app_init protected inherited
Whether to create the first app on rank 0 while all other MPI ranks are idle.
Definition at line 499 of file MultiApp.h.
Referenced by MultiApp::createApps().
The documentation for this class was generated from the following files:
moose/framework/include/multiapps/QuadraturePointMultiApp.h
moose/framework/src/multiapps/QuadraturePointMultiApp.C