Zapdos: ElementIDInterface Class Reference
ElementIDInterface Class Reference
#include <ElementIDInterface.h>
Public Member Functions
ElementIDInterface (const MooseObject *moose_object)
virtual ~ElementIDInterface ()
virtual unsigned int getElementIDIndex (const std::string &id_parameter_name, unsigned int comp=0) const
Gets index of an element integer with a parameter of the object derived from this interface.
virtual unsigned int getElementIDIndexByName (const std::string &id_name) const
Return the accessing integer for an extra element integer with its name.
virtual const dof_id_type & getElementID (const std::string &id_parameter_name, unsigned int comp=0) const
Gets an element integer with a parameter of the object derived from this interface.
virtual const dof_id_type & getElementIDNeighbor (const std::string &id_parameter_name, unsigned int comp=0) const
Gets a neighbor element integer with a parameter of the object derived from this interface.
virtual const dof_id_type & getElementIDByName (const std::string &id_name) const
Gets an element integer with the element integer name.
virtual const dof_id_type & getElementIDNeighborByName (const std::string &id_name) const
Gets a neighbor element integer with the element integer name.
bool hasElementID (const std::string &id_name) const
Whether mesh has an element integer with a given name.
dof_id_type maxElementID (unsigned int elem_id_index) const
Return the maximum element ID for an element integer with its index.
dof_id_type minElementID (unsigned int elem_id_index) const
Return the minimum element ID for an element integer with its index.
bool areElemIDsIdentical (const std::string &id_name1, const std::string &id_name2) const
Whether two element integers are identical for all elements.
std::unordered_map< dof_id_type, std::set< dof_id_type > > getElemIDMapping (const std::string &id_name1, const std::string &id_name2) const
Get the mapping from IDs of one extra element integer to another given the two integer names.
std::set< dof_id_type > getAllElemIDs (unsigned int elem_id_index) const
Return all the unique element IDs for an element integer with its index on the entire domain.
std::set< dof_id_type > getElemIDsOnBlocks (unsigned int elem_id_index, const std::set< SubdomainID > &blks) const
Return all the unique element IDs for an extra element integer with its index on a set of subdomains.
dof_id_type getElementID (const Elem *elem, unsigned int elem_id_index) const
Get an element integer for an element.
Static Public Member Functions
static InputParameters validParams ()
Private Attributes
const InputParameters & _obj_parameters
Reference to the object's input parameters.
std::shared_ptr< MooseMesh > & _id_mesh
References to the mesh and displaced mesh (currently in the ActionWarehouse)
const std::string & _ei_name
Name of the object using this interface.
Detailed Description
Definition at line 23 of file ElementIDInterface.h.
Constructor & Destructor Documentation
ElementIDInterface()
ElementIDInterface::ElementIDInterface (const MooseObject * moose_object)
Definition at line 28 of file ElementIDInterface.C.
  : _obj_parameters(moose_object->parameters()),
    _id_mesh(moose_object->getMooseApp().actionWarehouse().mesh()),
    _ei_name(moose_object->name())
{
}
~ElementIDInterface()
virtual ElementIDInterface::~ElementIDInterface () inline virtual
Definition at line 29 of file ElementIDInterface.h.
{}
Member Function Documentation
areElemIDsIdentical()
bool ElementIDInterface::areElemIDsIdentical (const std::string & id_name1, const std::string & id_name2) const inline
Whether two element integers are identical for all elements.
Definition at line 103 of file ElementIDInterface.h.
  {
    return _id_mesh->areElemIDsIdentical(id_name1, id_name2);
  }
getAllElemIDs()
std::set< dof_id_type > ElementIDInterface::getAllElemIDs (unsigned int elem_id_index) const inline
Return all the unique element IDs for an element integer with its index on the entire domain.
Definition at line 120 of file ElementIDInterface.h.
  {
    return _id_mesh->getAllElemIDs(elem_id_index);
  }
getElementID() [1/2]
dof_id_type ElementIDInterface::getElementID (const Elem * elem, unsigned int elem_id_index) const inline
Get an element integer for an element.
Definition at line 138 of file ElementIDInterface.h.
  {
    if (elem_id_index == elem->n_extra_integers())
      return elem->subdomain_id();
    return elem->get_extra_integer(elem_id_index);
  }
getElementID() [2/2]
const dof_id_type & ElementIDInterface::getElementID (const std::string & id_parameter_name, unsigned int comp = 0) const virtual
Gets an element integer with a parameter of the object derived from this interface.
Parameters
id_parameter_name Name of object parameter
comp Component number for vector of integer names
Returns
Integer for the current element
Reimplemented in Material.
Definition at line 72 of file ElementIDInterface.C.
{
  auto id = getElementIDIndex(id_parameter_name, comp);
  auto & _subproblem = *_obj_parameters.getCheckedPointerParam<SubProblem *>("_subproblem");
  auto tid = _obj_parameters.get<THREAD_ID>("_tid");
  auto & assembly = _subproblem.assembly(tid, 0);
  return assembly.extraElemID(id);
}
Referenced by Material::getElementID().
getElementIDByName()
const dof_id_type & ElementIDInterface::getElementIDByName (const std::string & id_name) const virtual
Gets an element integer with the element integer name.
Parameters
id_name Name of element integer
Returns
Integer for the current element
Reimplemented in Material.
Definition at line 101 of file ElementIDInterface.C.
{
  auto id = getElementIDIndexByName(id_name);
  auto & _subproblem = *_obj_parameters.getCheckedPointerParam<SubProblem *>("_subproblem");
  auto tid = _obj_parameters.get<THREAD_ID>("_tid");
  auto & assembly = _subproblem.assembly(tid, 0);
  return assembly.extraElemID(id);
}
Referenced by Material::getElementIDByName().
getElementIDIndex()
unsigned int ElementIDInterface::getElementIDIndex (const std::string & id_parameter_name, unsigned int comp = 0) const virtual
Gets index of an element integer with a parameter of the object derived from this interface.
Parameters
id_parameter_name Name of object parameter
comp Component number for vector of integer names
Returns
Index of the element integer
Definition at line 36 of file ElementIDInterface.C.
{
  auto & p = _obj_parameters.get<std::vector<ExtraElementIDName>>(id_parameter_name);
  if (comp >= p.size())
    mooseError(id_parameter_name, " does not have enough integer names");
  return getElementIDIndexByName(p[comp]);
}
Referenced by getElementID(), and getElementIDNeighbor().
getElementIDIndexByName()
unsigned int ElementIDInterface::getElementIDIndexByName (const std::string & id_name) const virtual
Return the accessing integer for an extra element integer with its name.
Parameters
id_name Name of element integer
Returns
Index of the element integer
Definition at line 47 of file ElementIDInterface.C.
{
  if (!_id_mesh.get())
    mooseError("Mesh is not available for getting element integers");
  auto & mesh_base = _id_mesh->getMesh();
  if (id_name == "subdomain_id")
  {
    if (mesh_base.has_elem_integer(id_name))
      mooseError("MOOSE does not allow 'subdomain_id' element integer in a mesh. 'subdomain_id' is "
                 "reserved for element subdomain ID");
    return mesh_base.n_elem_integers();
  }
  if (!mesh_base.has_elem_integer(id_name))
    mooseError(
        "Mesh does not have an element integer names as ", id_name, " but required by ", _ei_name);
  auto id = mesh_base.get_elem_integer_index(id_name);
  return id;
}
Referenced by ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), getElementIDByName(), getElementIDIndex(), and getElementIDNeighborByName().
getElementIDNeighbor()
const dof_id_type & ElementIDInterface::getElementIDNeighbor (const std::string & id_parameter_name, unsigned int comp = 0) const virtual
Gets a neighbor element integer with a parameter of the object derived from this interface.
Parameters
id_parameter_name Name of object parameter
comp Component number for vector of integer names
Returns
Integer for the neighbor element
Reimplemented in Material.
Definition at line 86 of file ElementIDInterface.C.
{
  auto id = getElementIDIndex(id_parameter_name, comp);
  auto & _subproblem = *_obj_parameters.getCheckedPointerParam<SubProblem *>("_subproblem");
  auto tid = _obj_parameters.get<THREAD_ID>("_tid");
  auto & assembly = _subproblem.assembly(tid, 0);
  return assembly.extraElemIDNeighbor(id);
}
Referenced by Material::getElementID(), and Material::getElementIDNeighbor().
getElementIDNeighborByName()
const dof_id_type & ElementIDInterface::getElementIDNeighborByName (const std::string & id_name) const virtual
Gets a neighbor element integer with the element integer name.
Parameters
id_name Name of element integer
Returns
Integer for the neighbor element
Reimplemented in Material.
Definition at line 115 of file ElementIDInterface.C.
{
  auto id = getElementIDIndexByName(id_name);
  auto & _subproblem = *_obj_parameters.getCheckedPointerParam<SubProblem *>("_subproblem");
  auto tid = _obj_parameters.get<THREAD_ID>("_tid");
  auto & assembly = _subproblem.assembly(tid, 0);
  return assembly.extraElemIDNeighbor(id);
}
Referenced by Material::getElementIDByName(), and Material::getElementIDNeighborByName().
getElemIDMapping()
std::unordered_map< dof_id_type, std::set< dof_id_type > > ElementIDInterface::getElemIDMapping (const std::string & id_name1, const std::string & id_name2) const inline
Get the mapping from IDs of one extra element integer to another given the two integer names.
Definition at line 112 of file ElementIDInterface.h.
  {
    return _id_mesh->getElemIDMapping(id_name1, id_name2);
  }
getElemIDsOnBlocks()
std::set< dof_id_type > ElementIDInterface::getElemIDsOnBlocks (unsigned int elem_id_index, const std::set< SubdomainID > & blks) const inline
Return all the unique element IDs for an extra element integer with its index on a set of subdomains.
Definition at line 129 of file ElementIDInterface.h.
  {
    return _id_mesh->getElemIDsOnBlocks(elem_id_index, blks);
  }
hasElementID()
bool ElementIDInterface::hasElementID (const std::string & id_name) const inline
Whether mesh has an element integer with a given name.
Definition at line 82 of file ElementIDInterface.h.
{ return _id_mesh->hasElementID(id_name); }
maxElementID()
dof_id_type ElementIDInterface::maxElementID (unsigned int elem_id_index) const inline
Return the maximum element ID for an element integer with its index.
Definition at line 87 of file ElementIDInterface.h.
  {
    return _id_mesh->maxElementID(elem_id_index);
  }
minElementID()
dof_id_type ElementIDInterface::minElementID (unsigned int elem_id_index) const inline
Return the minimum element ID for an element integer with its index.
Definition at line 95 of file ElementIDInterface.h.
  {
    return _id_mesh->minElementID(elem_id_index);
  }
validParams()
InputParameters ElementIDInterface::validParams () static
Definition at line 23 of file ElementIDInterface.C.
{
  return emptyInputParameters();
}
Member Data Documentation
_ei_name
const std::string& ElementIDInterface::_ei_name private
Name of the object using this interface.
Definition at line 154 of file ElementIDInterface.h.
Referenced by getElementIDIndexByName().
_id_mesh
std::shared_ptr<MooseMesh>& ElementIDInterface::_id_mesh private
References to the mesh and displaced mesh (currently in the ActionWarehouse)
Definition at line 151 of file ElementIDInterface.h.
Referenced by areElemIDsIdentical(), getAllElemIDs(), getElementIDIndexByName(), getElemIDMapping(), getElemIDsOnBlocks(), hasElementID(), maxElementID(), and minElementID().
_obj_parameters
const InputParameters& ElementIDInterface::_obj_parameters private
Reference to the object's input parameters.
Definition at line 148 of file ElementIDInterface.h.
Referenced by getElementID(), getElementIDByName(), getElementIDIndex(), getElementIDNeighbor(), and getElementIDNeighborByName().
The documentation for this class was generated from the following files:
moose/framework/include/interfaces/ElementIDInterface.h
moose/framework/src/interfaces/ElementIDInterface.C