Zapdos: UniqueStorage< T > Class Template Reference
UniqueStorage< T > Class Template Reference
Storage container that stores a vector of unique pointers of T, but represents most of the public facing accessors (iterators, operator[]) as a vector of T.
#include <UniqueStorage.h>
Classes
struct DereferenceIterator
Iterator that adds an additional dereference to BaseIterator.
Public Types
using values_type = typename std::vector< std::unique_ptr< T > >
using iterator = DereferenceIterator< typename values_type::iterator >
using const_iterator = DereferenceIterator< typename values_type::const_iterator >
Public Member Functions
UniqueStorage ()=default
UniqueStorage (UniqueStorage &&)=default
UniqueStorage (const UniqueStorage &mp)=delete
UniqueStorage & operator= (const UniqueStorage &)=delete
std::size_t size () const
bool empty () const
bool hasValue (const std::size_t i) const
iterator begin ()
Begin and end iterators to the underlying data.
iterator end ()
const_iterator begin () const
const_iterator end () const
const T & operator[] (const std::size_t i) const
T & operator[] (const std::size_t i)
const T * queryValue (const std::size_t i) const
T * queryValue (const std::size_t i)
Protected Member Functions
void setPointer (const std::size_t i, std::unique_ptr< T > &&ptr)
Sets the underlying unique_ptr at index i to ptr.
T & addPointer (std::unique_ptr< T > &&ptr)
Adds the given object in ptr to the storage.
void resize (const std::size_t size)
Resizes the underlying vector.
Private Member Functions
const std::unique_ptr< T > & pointerValue (const std::size_t i) const
Returns a read-only reference to the underlying unique pointer at index i.
Private Attributes
values_type _values
The underlying data.
Detailed Description
template<class T>
class UniqueStorage< T >
Storage container that stores a vector of unique pointers of T, but represents most of the public facing accessors (iterators, operator[]) as a vector of T.
That is, these accessors dereference the underlying storage. More importantly, if data is not properly initialized using setValue(), this dereferencing will either lead to an assertion or a nullptr dereference.
Definition at line 27 of file UniqueStorage.h.
Member Typedef Documentation
const_iterator
template<class T > using UniqueStorage< T >::const_iterator = DereferenceIterator<typename values_type::const_iterator>
Definition at line 64 of file UniqueStorage.h.
iterator
template<class T > using UniqueStorage< T >::iterator = DereferenceIterator<typename values_type::iterator>
Definition at line 63 of file UniqueStorage.h.
values_type
template<class T > using UniqueStorage< T >::values_type = typename std::vector<std::unique_ptr<T> >
Definition at line 62 of file UniqueStorage.h.
Constructor & Destructor Documentation
UniqueStorage() [1/3]
template<class T > UniqueStorage< T >::UniqueStorage () default
UniqueStorage() [2/3]
template<class T > UniqueStorage< T >::UniqueStorage (UniqueStorage< T > &&) default
UniqueStorage() [3/3]
template<class T > UniqueStorage< T >::UniqueStorage (const UniqueStorage< T > & mp) delete
Member Function Documentation
addPointer()
template<class T > T & UniqueStorage< T >::addPointer (std::unique_ptr< T > && ptr) inline protected
Adds the given object in ptr to the storage.
Definition at line 148 of file UniqueStorage.h.
  {
    mooseAssert(ptr, "Null object");
    return *_values.emplace_back(std::move(ptr));
  }
Referenced by RestartableDataMap::Data::addPointer().
begin() [1/2]
template<class T > iterator UniqueStorage< T >::begin () inline
Begin and end iterators to the underlying data.
Note that dereferencing these iterators may lead to an assertion or the dereference of a nullptr whether or not the underlying data is initialized.
Definition at line 74 of file UniqueStorage.h.
{ return iterator(_values.begin()); }
Referenced by RestartableDataMap::begin(), and RestartableDataMap::findData().
begin() [2/2]
template<class T > const_iterator UniqueStorage< T >::begin () const inline
Definition at line 76 of file UniqueStorage.h.
{ return const_iterator(_values.begin()); }
empty()
template<class T > bool UniqueStorage< T >::empty () const inline
Returns
Whether or not the underlying storage is empty.
Definition at line 108 of file UniqueStorage.h.
{ return _values.empty(); }
Referenced by RestartableDataMap::empty().
end() [1/2]
template<class T > iterator UniqueStorage< T >::end () inline
Definition at line 75 of file UniqueStorage.h.
{ return iterator(_values.end()); }
Referenced by RestartableDataMap::end(), and RestartableDataMap::findData().
end() [2/2]
template<class T > const_iterator UniqueStorage< T >::end () const inline
Definition at line 77 of file UniqueStorage.h.
{ return const_iterator(_values.end()); }
hasValue()
template<class T > bool UniqueStorage< T >::hasValue (const std::size_t i) const inline
Returns
whether or not the underlying object at index is initialized
Definition at line 113 of file UniqueStorage.h.
{ return pointerValue(i) != nullptr; }
Referenced by UniqueStorage< T >::operator[](), MaterialPropertyStorage::shallowSwapData(), and MaterialPropertyStorage::shallowSwapDataBack().
operator=()
template<class T > UniqueStorage & UniqueStorage< T >::operator= (const UniqueStorage< T > &) delete
operator[]() [1/2]
template<class T > T & UniqueStorage< T >::operator[] (const std::size_t i) inline
Definition at line 95 of file UniqueStorage.h.
{ return const_cast<T &>(std::as_const(*this)[i]); }
operator[]() [2/2]
template<class T > const T & UniqueStorage< T >::operator[] (const std::size_t i) const inline
Returns
A reference to the underlying data at index i.
Note that the underlying data may not necessarily be initialized, in which case this will throw an assertion or dereference a nullptr.
You can check whether or not the underlying data is intialized with hasValue(i).
Definition at line 90 of file UniqueStorage.h.
  {
    mooseAssert(hasValue(i), "Null object");
    return *pointerValue(i);
  }
pointerValue()
template<class T > const std::unique_ptr< T > & UniqueStorage< T >::pointerValue (const std::size_t i) const inline private
Returns a read-only reference to the underlying unique pointer at index i.
We hope to only expose the underlying unique_ptr to this API, and not in derived classes. Hopefully it can stay that way.
Definition at line 170 of file UniqueStorage.h.
  {
    mooseAssert(size() > i, "Invalid size");
    return _values[i];
  }
Referenced by UniqueStorage< T >::hasValue(), UniqueStorage< T >::operator[](), and UniqueStorage< T >::queryValue().
queryValue() [1/2]
template<class T > T * UniqueStorage< T >::queryValue (const std::size_t i) inline
Definition at line 123 of file UniqueStorage.h.
  {
    return const_cast<T *>(std::as_const(*this).queryValue(i));
  }
queryValue() [2/2]
template<class T > const T * UniqueStorage< T >::queryValue (const std::size_t i) const inline
Returns
A pointer to the underlying data at index i
The pointer will be nullptr if !hasValue(i), that is, if the unique_ptr at index i is not initialized
Definition at line 122 of file UniqueStorage.h.
{ return pointerValue(i).get(); }
Referenced by MaterialData::haveGenericProperty().
resize()
template<class T > void UniqueStorage< T >::resize (const std::size_t size) inline protected
Resizes the underlying vector.
This is the only method that allows for modification of the underlying container. Protect it wisely.
Definition at line 160 of file UniqueStorage.h.
{ _values.resize(size); }
Referenced by MaterialProperties::resize().
setPointer()
template<class T > void UniqueStorage< T >::setPointer (const std::size_t i, std::unique_ptr< T > && ptr) inline protected
Sets the underlying unique_ptr at index i to ptr.
This can be used to construct objects in the storage, i.e., setPointer(0, std::make_unique<T>(...));
This is the only method that allows for the modification of ownership in the underlying vector. Protect it wisely.
Definition at line 139 of file UniqueStorage.h.
  {
    mooseAssert(size() > i, "Invalid size");
    _values[i] = std::move(ptr);
  }
Referenced by MaterialProperties::setPointer().
size()
template<class T > std::size_t UniqueStorage< T >::size () const inline
Returns
The size of the underlying storage.
Note that this is not necessarily the size of constructed objects, as underlying objects could be uninitialized
Definition at line 104 of file UniqueStorage.h.
{ return _values.size(); }
Referenced by RestartableDataMap::addData(), dataLoad(), dataStore(), RestartableDataMap::findData(), UniqueStorage< T >::pointerValue(), UniqueStorage< T >::resize(), UniqueStorage< T >::setPointer(), MaterialPropertyStorage::shallowSwapData(), MaterialPropertyStorage::shallowSwapDataBack(), and RestartableDataMap::size().
Member Data Documentation
_values
template<class T > values_type UniqueStorage< T >::_values private
The underlying data.
Definition at line 177 of file UniqueStorage.h.
Referenced by UniqueStorage< T >::addPointer(), UniqueStorage< T >::begin(), UniqueStorage< T >::empty(), UniqueStorage< T >::end(), UniqueStorage< T >::pointerValue(), UniqueStorage< T >::resize(), UniqueStorage< T >::setPointer(), and UniqueStorage< T >::size().
The documentation for this class was generated from the following file:
moose/framework/include/utils/UniqueStorage.h