Zapdos: Reporter Class Reference
Reporter Class Reference
Reporter objects allow for the declaration of arbitrary data types that are aggregate values for a simulation.
#include <Reporter.h>
Classes
struct UnusedWrapper
Internal struct for storing a unused value.
struct UnusedWrapperBase
Internal base struct for use in storing unused values.
Public Member Functions
Reporter (const MooseObject *moose_object)
virtual ~Reporter ()=default
virtual void store (nlohmann::json &json) const
virtual bool shouldStore () const
virtual void declareLateValues ()
Method that can be overriden to declare "late" Reporter values.
void buildOutputHideVariableList (std::set< std::string > variable_names)
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
const std::set< OutputName > & getOutputs ()
Get the list of output objects that this class is restricted.
Static Public Member Functions
static InputParameters validParams ()
Protected Member Functions
template<typename T , typename... Args>
T & declareUnusedValue (Args &&... args)
Declare a unused value with type T.
template<typename T , template< typename > class S = ReporterGeneralContext, typename... Args>
T & declareValue (const std::string &param_name, Args &&... args)
Method to define a value that the Reporter object is to produced.
template<typename T , template< typename > class S = ReporterGeneralContext, typename... Args>
T & declareValue (const std::string &param_name, ReporterMode mode, Args &&... args)
template<typename T , template< typename > class S = ReporterGeneralContext, typename... Args>
T & declareValueByName (const ReporterValueName &value_name, Args &&... args)
template<typename T , template< typename > class S = ReporterGeneralContext, typename... Args>
T & declareValueByName (const ReporterValueName &value_name, ReporterMode mode, Args &&... args)
template<typename T , typename S , typename... Args>
T & declareValue (const std::string &param_name, Args &&... args)
template<typename T , typename S , typename... Args>
T & declareValue (const std::string &param_name, ReporterMode mode, Args &&... args)
template<typename T , typename S , typename... Args>
T & declareValueByName (const ReporterValueName &value_name, Args &&... args)
template<typename T , typename S , typename... Args>
T & declareValueByName (const ReporterValueName &value_name, ReporterMode mode, Args &&... args)
Private Member Functions
const ReporterValueName & getReporterValueName (const std::string &param_name) const
Private Attributes
const MooseObject & _reporter_moose_object
The MooseObject creating this Reporter.
const InputParameters & _reporter_params
Ref. to MooseObject params.
const std::string & _reporter_name
The name of the MooseObject, from "_object_name" param.
FEProblemBase & _reporter_fe_problem
Needed for access to FEProblemBase::getReporterData.
ReporterData & _reporter_data
Data storage.
std::vector< std::unique_ptr< UnusedWrapperBase > > _unused_values
Storage for unused values declared with declareUnusedValue().
MooseApp & _oi_moose_app
Reference the the MooseApp; neede for access to the OutputWarehouse.
OutputWarehouse & _oi_output_warehouse
Reference to the OutputWarehouse for populating the Output object hide lists.
std::set< OutputName > _oi_outputs
The set of Output object names listed in the 'outputs' parameter.
Detailed Description
Reporter objects allow for the declaration of arbitrary data types that are aggregate values for a simulation.
These aggregate values are then available to other objects for use. They operate with the typical producer/consumer relationship. The Reporter object produces values that other objects consume.
Originally, MOOSE included a Postprocessor system that allowed for an object to produce a single scalar value for consumption by other objects. Then a companion system was created, the VectorPostprocessor system, that allowed for an object to produce many std::vector<Real> values. The Reporter system is the generalization of these two ideas and follows closely the original design of the VectorPostprocessor system.
In practice, the Reporter system provided the following features over the two previous systems.
It can create arbitrary data types rather than only Real and std::vector<Real>
It can create many values per object. This was possible for VectorPostprocessor objects but not for Postprocessors. Therefore, this allows a single Reporter to provide multiple values and consolidate similar items. For example, a "counter" object replaced several individual Postprocessor objects.
The ReporterContext system allows for each data value to have special operation within a single object. Previously the VectorPostprocessor system had capability to perform broadcasting, but it was applied to all vectors in the object.
Definition at line 47 of file Reporter.h.
Constructor & Destructor Documentation
Reporter()
Reporter::Reporter (const MooseObject * moose_object)
Definition at line 29 of file Reporter.C.
  : OutputInterface(moose_object->parameters(), /*build_list=*/false),
    _reporter_moose_object(*moose_object),
    _reporter_params(_reporter_moose_object.parameters()),
    _reporter_name(_reporter_params.get<std::string>("_object_name")),
    _reporter_fe_problem(
        *_reporter_params.getCheckedPointerParam<FEProblemBase *>("_fe_problem_base")),
    _reporter_data(_reporter_fe_problem.getReporterData(ReporterData::WriteKey()))
{
  // For the callback to declareLateValues()
  _reporter_moose_object.getMooseApp().registerInterfaceObject(*this);
}
~Reporter()
virtual Reporter::~Reporter () virtual default
Member Function Documentation
buildOutputHideVariableList()
void OutputInterface::buildOutputHideVariableList (std::set< std::string > variable_names) inherited
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
Parameters
variable_names A set of variables for which the 'outputs' parameter controls
By default this is called by the constructor and passes the block name as the list of variables. This needs to be called explicitly if the build_list flag is set to False in the constructor. The latter cases is needed by the Material object to work correctly with the automatic material output capability.
Definition at line 61 of file OutputInterface.C.
{
  // Set of available names
  const std::set<OutputName> & avail = _oi_output_warehouse.getOutputNames();
  // Check for 'none'; hide variables on all outputs
  if (_oi_outputs.find("none") != _oi_outputs.end())
    for (const auto & name : avail)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  // Check for empty and 'all' in 'outputs' parameter; do not perform any variable restrictions in
  // these cases
  else if (_oi_outputs.empty() || _oi_outputs.find("all") != _oi_outputs.end())
    return;
  // Limit the variable output to Output objects listed
  else
  {
    // Create a list of outputs where the variable should be hidden
    std::set<OutputName> hide;
    std::set_difference(avail.begin(),
                        avail.end(),
                        _oi_outputs.begin(),
                        _oi_outputs.end(),
                        std::inserter(hide, hide.begin()));
    // If 'outputs' is specified add the object name to the list of items to hide
    for (const auto & name : hide)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  }
}
Referenced by ReporterTransferInterface::hideVariableHelper(), and OutputInterface::OutputInterface().
declareLateValues()
virtual void Reporter::declareLateValues () inline virtual
Method that can be overriden to declare "late" Reporter values.
Values are considered "late" when they need to be declared after all other Reporters have been instantiated. This is called by the "declare_late_reporters" task, which should be called right after the "add_reporters" task.
Reimplemented in AccumulateReporter.
Definition at line 71 of file Reporter.h.
{}
declareUnusedValue()
template<typename T , typename... Args> T & Reporter::declareUnusedValue (Args &&... args) protected
Declare a unused value with type T.
This is useful when you have a reporter that has optional values. In this case, you want to create references to all reporter values. However, because some values are optional, you need something to fill into the reference. This helper will create a unused value. It also allows for the passing of arguments in the case that your value is not trivially default constructable (constructable by default without arguments).
Definition at line 270 of file Reporter.h.
{
  _unused_values.emplace_back(std::make_unique<UnusedWrapper<T>>(std::forward(args)...));
  UnusedWrapper<T> * wrapper = dynamic_cast<UnusedWrapper<T> *>(_unused_values.back().get());
  return wrapper->value;
}
declareValue() [1/4]
template<typename T , typename S , typename... Args> T & Reporter::declareValue (const std::string & param_name, Args &&... args) protected
Method to define a value that the Reporter object is to produced.
Template Parameters
T The C++ type of the value to be produced
S (optional) Context type for performing special operations. For example using the ReporterBroadcastContext will automatically broadcast the produced value from the root processor.
Parameters
name A unique name for the value to be produced.
mode (optional) The mode that indicates how the value produced is represented in parallel, there is more information about this below
args (optional) Any number of optional arguments passed into the ReporterContext given by the S template parameter. If S = ReporterContext then the first argument can be used as the default value (see ReporterContext.h).
The 'mode' indicates how the value that is produced is represented in parallel. It is the responsibility of the Reporter object to get it to that state. The ReporterContext objects are designed to help with this. The mode can be one of the following:
ReporterMode::ROOT Indicates that the value produced is complete/correct on the
                   root processor for the object.
ReporterMode::REPLICATED Indicates that the value produced is complete/correct on
                         all processors AND that the value is the same on all
                         processors
ReporterMode::DISTRIBUTED Indicates that the value produced is complete/correct on
                          all processors AND that the value is NOT the same on all
                          processors
WARNING! Using the "default value" in ReporterContext: The Reporter system, like the systems before it, allow for objects that consume values to be constructed prior to the produce objects. When a value is requested either by a producer (Reporter) or consumer (ReporterInterface) the data is allocated. As such the assigned default value from the producer should not be relied upon on the consumer side during object construction.
NOTE: The ReporterContext is just a mechanism to allow for handling of values in special ways. In practice it might be better to have specific methods for these special cases. For example, a declareBroadcastValue, etc. Please refer to the ReporterData object for more information on how the data system operates for Reporter values.
Definition at line 198 of file Reporter.h.
{
  return declareValue<T, S<T>>(param_name, REPORTER_MODE_UNSET, args...);
}
declareValue() [2/4]
template<typename T , typename S , typename... Args> T & Reporter::declareValue (const std::string & param_name, Args &&... args) protected
declareValue() [3/4]
template<typename T , typename S , typename... Args> T & Reporter::declareValue (const std::string & param_name, ReporterMode mode, Args &&... args) protected
Definition at line 205 of file Reporter.h.
{
  return declareValue<T, S<T>>(param_name, mode, args...);
}
declareValue() [4/4]
template<typename T , typename S , typename... Args> T & Reporter::declareValue (const std::string & param_name, ReporterMode mode, Args &&... args) protected
declareValueByName() [1/4]
template<typename T , typename S , typename... Args> T & Reporter::declareValueByName (const ReporterValueName & value_name, Args &&... args) protected
Definition at line 226 of file Reporter.h.
{
  return declareValueByName<T, S<T>>(value_name, REPORTER_MODE_UNSET, args...);
}
declareValueByName() [2/4]
template<typename T , typename S , typename... Args> T & Reporter::declareValueByName (const ReporterValueName & value_name, Args &&... args) protected
declareValueByName() [3/4]
template<typename T , typename S , typename... Args> T & Reporter::declareValueByName (const ReporterValueName & value_name, ReporterMode mode, Args &&... args) protected
Definition at line 233 of file Reporter.h.
{
  return declareValueByName<T, S<T>>(value_name, mode, args...);
}
declareValueByName() [4/4]
template<typename T , typename S , typename... Args> T & Reporter::declareValueByName (const ReporterValueName & value_name, ReporterMode mode, Args &&... args) protected
getOutputs()
const std::set< OutputName > & OutputInterface::getOutputs () inherited
Get the list of output objects that this class is restricted.
Returns
A set of OutputNames
Definition at line 94 of file OutputInterface.C.
{
  return _oi_outputs;
}
getReporterValueName()
const ReporterValueName & Reporter::getReporterValueName (const std::string & param_name) const private
Returns
The ReporterValueName associated with the parameter param_name.
Performs error checking on if the parameter is valid.
Definition at line 49 of file Reporter.C.
{
  if (!_reporter_params.isParamValid(param_name))
    _reporter_moose_object.mooseError(
        "When getting a ReporterValueName, failed to get a parameter with the name \"",
        param_name,
        "\".",
        "\n\nKnown parameters:\n",
        _reporter_moose_object.parameters());
  if (_reporter_params.isType<ReporterValueName>(param_name))
    return _reporter_params.get<ReporterValueName>(param_name);
  _reporter_moose_object.mooseError("Supplied parameter with name \"",
                                    param_name,
                                    "\" of type \"",
                                    _reporter_params.type(param_name),
                                    "\" is not an expected type for getting a Reporter value.\n\n",
                                    "The expected type is \"ReporterValueName\".");
}
shouldStore()
virtual bool Reporter::shouldStore () const inline virtual
Returns
Whether or not this Reporter should store its value at this specific time.
Basic Reporters (those that are not GeneralReporters) will store at all times when requested.
Reimplemented in ElementReporter, GeneralReporter, and NodalReporter.
Definition at line 61 of file Reporter.h.
{ return true; }
store()
void Reporter::store (nlohmann::json & json) const virtual
Definition at line 43 of file Reporter.C.
{
  json["type"] = _reporter_params.get<std::string>("_type");
}
validParams()
InputParameters Reporter::validParams () static
Definition at line 16 of file Reporter.C.
{
  InputParameters params = emptyInputParameters();
  params += OutputInterface::validParams();
  params.registerBase("Reporter");
  return params;
}
Referenced by Executioner::validParams(), ElementReporter::validParams(), GeneralReporter::validParams(), and NodalReporter::validParams().
Member Data Documentation
_oi_moose_app
MooseApp& OutputInterface::_oi_moose_app private inherited
Reference the the MooseApp; neede for access to the OutputWarehouse.
Definition at line 66 of file OutputInterface.h.
_oi_output_warehouse
OutputWarehouse& OutputInterface::_oi_output_warehouse private inherited
Reference to the OutputWarehouse for populating the Output object hide lists.
Definition at line 69 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList().
_oi_outputs
std::set<OutputName> OutputInterface::_oi_outputs private inherited
The set of Output object names listed in the 'outputs' parameter.
Definition at line 72 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList(), and OutputInterface::getOutputs().
_reporter_data
ReporterData& Reporter::_reporter_data private
Data storage.
Definition at line 190 of file Reporter.h.
_reporter_fe_problem
FEProblemBase& Reporter::_reporter_fe_problem private
Needed for access to FEProblemBase::getReporterData.
Definition at line 187 of file Reporter.h.
_reporter_moose_object
const MooseObject& Reporter::_reporter_moose_object private
The MooseObject creating this Reporter.
Definition at line 178 of file Reporter.h.
Referenced by getReporterValueName(), and Reporter().
_reporter_name
const std::string& Reporter::_reporter_name private
The name of the MooseObject, from "_object_name" param.
Definition at line 184 of file Reporter.h.
_reporter_params
const InputParameters& Reporter::_reporter_params private
Ref. to MooseObject params.
Definition at line 181 of file Reporter.h.
Referenced by getReporterValueName(), and store().
_unused_values
std::vector<std::unique_ptr<UnusedWrapperBase> > Reporter::_unused_values private
Storage for unused values declared with declareUnusedValue().
Definition at line 193 of file Reporter.h.
Referenced by declareUnusedValue().
The documentation for this class was generated from the following files:
moose/framework/include/reporters/Reporter.h
moose/framework/src/reporters/Reporter.C