Zapdos: DisplacedSystem Class Reference
DisplacedSystem Class Reference
#include <DisplacedSystem.h>
Public Member Functions
DisplacedSystem (DisplacedSystem &&)=delete
DisplacedSystem & operator= (DisplacedSystem &&)=delete
DisplacedSystem (DisplacedProblem &problem, SystemBase &undisplaced_system, const std::string &name, Moose::VarKindType var_kind)
virtual ~DisplacedSystem ()
virtual NumericVector< Number > & getVector (TagID tag_id) override
Get a raw NumericVector by tag.
virtual const NumericVector< Number > & getVector (TagID tag_id) const override
virtual TagID residualVectorTag () const override
virtual TagID systemMatrixTag () const override
Return the Matrix Tag ID for System.
virtual TagID timeVectorTag () const override
Ideally, we should not need this API.
virtual TagID nonTimeVectorTag () const override
virtual std::set< TagID > defaultVectorTags () const override
Get the default vector tags associated with this system.
virtual std::set< TagID > defaultMatrixTags () const override
Get the default matrix tags associted with this system.
virtual void associateVectorToTag (NumericVector< Number > &vec, TagID tag) override
Associate a vector for a given tag.
virtual void disassociateVectorFromTag (NumericVector< Number > &vec, TagID tag) override
Disassociate a given vector from a given tag.
virtual void disassociateVectorFromTag (TagID tag) override
Disassociate any vector that is associated with a given tag.
virtual void disassociateDefaultVectorTags () override
Disassociate the vectors associated with the default vector tags of this system.
virtual void associateMatrixToTag (SparseMatrix< Number > &matrix, TagID tag) override
Associate a matrix to a tag.
virtual void disassociateMatrixFromTag (SparseMatrix< Number > &matrix, TagID tag) override
Disassociate a matrix from a tag.
virtual void disassociateMatrixFromTag (TagID tag) override
Disassociate any matrix that is associated with a given tag.
virtual void disassociateDefaultMatrixTags () override
Disassociate the matrices associated with the default matrix tags of this system.
virtual NumericVector< Number > & getVector (const std::string &name) override
Get a raw NumericVector by name.
virtual const NumericVector< Number > & getVector (const std::string &name) const override
virtual NumericVector< Number > & serializedSolution () override
Returns a reference to a serialized version of the solution vector for this subproblem.
const NumericVector< Number > *const & currentSolution () const override
The solution vector that is currently being operated on.
NumericVector< Number > * solutionPreviousNewton () override
const NumericVector< Number > * solutionPreviousNewton () const override
NumericVector< Number > * solutionUDot () override
NumericVector< Number > * solutionUDotDot () override
NumericVector< Number > * solutionUDotOld () override
NumericVector< Number > * solutionUDotDotOld () override
const NumericVector< Number > * solutionUDot () const override
const NumericVector< Number > * solutionUDotDot () const override
const NumericVector< Number > * solutionUDotOld () const override
const NumericVector< Number > * solutionUDotDotOld () const override
virtual Number & duDotDu () override
virtual Number & duDotDotDu () override
virtual const Number & duDotDu () const override
virtual const Number & duDotDotDu () const override
virtual NumericVector< Number > & residualCopy () override
Return the residual copy from the NonlinearSystem.
virtual NumericVector< Number > & residualGhosted () override
virtual void augmentSendList (std::vector< dof_id_type > &send_list) override
Will modify the send_list to add all of the extra ghosted dofs for this system.
virtual void augmentSparsity (SparsityPattern::Graph &, std::vector< dof_id_type > &, std::vector< dof_id_type > &) override
This is an empty function since the displaced system doesn't have a matrix! All sparsity pattern modification will be taken care of by the undisplaced system directly.
virtual void addVariableToZeroOnResidual (std::string var_name) override
Adds this variable to the list of variables to be zeroed during each residual evaluation.
virtual void addVariableToZeroOnJacobian (std::string var_name) override
Adds this variable to the list of variables to be zeroed during each jacobian evaluation.
virtual void zeroVariables (std::vector< std::string > &vars_to_be_zeroed) override
Zero out the solution for the list of variables passed in.
virtual bool hasVector (TagID tag_id) const override
Check if the tagged vector exists in the system.
virtual bool hasMatrix (TagID tag_id) const override
Check if the tagged matrix exists in the system.
virtual void initSolutionState () override
Initializes the solution state.
virtual NumericVector< Number > & solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time) override
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
virtual const NumericVector< Number > & solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time) const override
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
virtual void needSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time) override
Registers that the solution state state is needed.
virtual bool hasSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time) const override
Whether or not the system has the solution state (0 = current, 1 = old, 2 = older, etc).
virtual SparseMatrix< Number > & getMatrix (TagID tag) override
Get a raw SparseMatrix.
virtual const SparseMatrix< Number > & getMatrix (TagID tag) const override
Get a raw SparseMatrix.
virtual TransientExplicitSystem & sys ()
virtual System & system () override
Get the reference to the libMesh system.
virtual const System & system () const override
void addTimeIntegrator (std::shared_ptr< TimeIntegrator > ti) override
virtual void addTimeIntegrator (const std::string &, const std::string &, InputParameters &)
virtual void addTimeIntegrator (std::shared_ptr< TimeIntegrator >)
unsigned int number () const
Gets the number of this system.
virtual MooseMesh & mesh ()
virtual const MooseMesh & mesh () const
virtual SubProblem & subproblem ()
virtual const SubProblem & subproblem () const
void applyScalingFactors (const std::vector< Real > &inverse_scaling_factors)
Applies scaling factors to the system's variables.
bool computingScalingJacobian () const
Whether we are computing an initial Jacobian for automatic variable scaling.
bool automaticScaling () const
Getter for whether we are performing automatic scaling.
void automaticScaling (bool automatic_scaling)
Setter for whether we are performing automatic scaling.
void setVerboseFlag (const bool &verbose)
Sets the verbose flag.
virtual DofMap & dofMap ()
Gets writeable reference to the dof map.
virtual const DofMap & dofMap () const
Gets const reference to the dof map.
virtual void init ()
Initialize the system.
virtual void initializeObjects ()
Called only once, just before the solve begins so objects can do some precalculations.
virtual void update (bool update_libmesh_system=true)
Update the system (doing libMesh magic)
virtual void solve ()
Solve the system (using libMesh magic)
virtual void copyOldSolutions ()
Shifts the solutions backwards in time.
virtual void restoreSolutions ()
Restore current solutions (call after your solve failed)
NumericVector< Number > & solution ()
const NumericVector< Number > & solution () const
NumericVector< Number > & solutionOld ()
const NumericVector< Number > & solutionOld () const
NumericVector< Number > & solutionOlder ()
const NumericVector< Number > & solutionOlder () const
virtual void saveOldSolutions ()
Save the old and older solutions.
virtual void restoreOldSolutions ()
Restore the old and older solutions when the saved solutions present.
bool hasVector (const std::string &tag_name) const
Check if the named vector exists in the system.
virtual void activeAllMatrixTags ()
Make all exsiting matrices ative.
virtual void activeMatrixTag (TagID tag)
Active a matrix for tag.
virtual bool matrixTagActive (TagID tag) const
If or not a matrix tag is active.
virtual void deactiveMatrixTag (TagID tag)
deactive a matrix for tag
virtual void deactiveAllMatrixTags ()
Make matrices inactive.
void closeTaggedMatrices (const std::set< TagID > &tags)
Close all matrices associated the tags.
void flushTaggedMatrices (const std::set< TagID > &tags)
flushes all matrices associated to tags.
virtual void addVariable (const std::string &var_type, const std::string &var_name, InputParameters &parameters)
Canonical method for adding a variable.
virtual bool isArrayVariable (const std::string &var_name) const
If a variable is an array variable.
virtual bool isScalarVariable (unsigned int var_name) const
MooseVariableFieldBase & getVariable (THREAD_ID tid, const std::string &var_name) const
Gets a reference to a variable of with specified name.
MooseVariableFieldBase & getVariable (THREAD_ID tid, unsigned int var_number) const
Gets a reference to a variable with specified number.
template<typename T >
MooseVariableFE< T > & getFieldVariable (THREAD_ID tid, const std::string &var_name)
Gets a reference to a variable of with specified name.
template<typename T >
MooseVariableFE< T > & getFieldVariable (THREAD_ID tid, unsigned int var_number)
Gets a reference to a variable with specified number.
template<typename T >
MooseVariableField< T > & getActualFieldVariable (THREAD_ID tid, const std::string &var_name)
Returns a field variable pointer - this includes finite volume variables.
template<typename T >
MooseVariableField< T > & getActualFieldVariable (THREAD_ID tid, unsigned int var_number)
Returns a field variable pointer - this includes finite volume variables.
template<typename T >
MooseVariableFV< T > & getFVVariable (THREAD_ID tid, const std::string &var_name)
Return a finite volume variable.
virtual MooseVariableScalar & getScalarVariable (THREAD_ID tid, const std::string &var_name) const
Gets a reference to a scalar variable with specified number.
virtual MooseVariableScalar & getScalarVariable (THREAD_ID tid, unsigned int var_number) const
Gets a reference to a variable with specified number.
virtual const std::set< SubdomainID > * getVariableBlocks (unsigned int var_number)
Get the block where a variable of this system is defined.
virtual unsigned int nVariables () const
Get the number of variables in this system.
unsigned int nFieldVariables () const
Get the number of field variables in this system.
unsigned int nFVVariables () const
Get the number of finite volume variables in this system.
std::size_t getMaxVarNDofsPerElem () const
Gets the maximum number of dofs used by any one variable on any one element.
std::size_t getMaxVarNDofsPerNode () const
Gets the maximum number of dofs used by any one variable on any one node.
void assignMaxVarNDofsPerElem (std::size_t max_dofs)
assign the maximum element dofs
void assignMaxVarNDofsPerNode (std::size_t max_dofs)
assign the maximum node dofs
virtual void zeroVariablesForResidual ()
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on residual evaluation by a call to addVariableToZeroOnResidual()
virtual void zeroVariablesForJacobian ()
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on Jacobian evaluation by a call to addVariableToZeroOnResidual()
virtual Order getMinQuadratureOrder ()
Get minimal quadrature order needed for integrating variables in this system.
virtual void prepare (THREAD_ID tid)
Prepare the system for use.
virtual void prepareFace (THREAD_ID tid, bool resize_data)
Prepare the system for use on sides.
virtual void prepareNeighbor (THREAD_ID tid)
Prepare the system for use.
virtual void prepareLowerD (THREAD_ID tid)
Prepare the system for use for lower dimensional elements.
virtual void reinitElem (const Elem *elem, THREAD_ID tid)
Reinit an element assembly info.
virtual void reinitElemFace (const Elem *elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid)
Reinit assembly info for a side of an element.
virtual void reinitNeighborFace (const Elem *elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid)
Compute the values of the variables at all the current points.
virtual void reinitNeighbor (const Elem *elem, THREAD_ID tid)
Compute the values of the variables at all the current points.
virtual void reinitLowerD (THREAD_ID tid)
Compute the values of the variables on the lower dimensional element.
virtual void reinitNode (const Node *node, THREAD_ID tid)
Reinit nodal assembly info.
virtual void reinitNodeFace (const Node *node, BoundaryID bnd_id, THREAD_ID tid)
Reinit nodal assembly info on a face.
virtual void reinitNodes (const std::vector< dof_id_type > &nodes, THREAD_ID tid)
Reinit variables at a set of nodes.
virtual void reinitNodesNeighbor (const std::vector< dof_id_type > &nodes, THREAD_ID tid)
Reinit variables at a set of neighbor nodes.
virtual void reinitScalars (THREAD_ID tid, bool reinit_for_derivative_reordering=false)
Reinit scalar varaibles.
virtual void addVariableToCopy (const std::string &dest_name, const std::string &source_name, const std::string &timestep)
Add info about variable that will be copied.
const std::vector< MooseVariableFieldBase * > & getVariables (THREAD_ID tid)
const std::vector< MooseVariableScalar * > & getScalarVariables (THREAD_ID tid)
const std::set< SubdomainID > & getSubdomainsForVar (unsigned int var_number) const
const std::set< SubdomainID > & getSubdomainsForVar (const std::string &var_name) const
Get the block where a variable of this system is defined.
void removeVector (const std::string &name)
Remove a vector from the system with the given name.
void removeVector (TagID tag_id)
Remove a solution length vector from the system with the specified TagID.
NumericVector< Number > & addVector (const std::string &vector_name, const bool project, const ParallelType type)
Adds a solution length vector to the system.
NumericVector< Number > & addVector (TagID tag, const bool project, const ParallelType type)
Adds a solution length vector to the system with the specified TagID.
void closeTaggedVector (const TagID tag)
Close vector with the given tag.
void closeTaggedVectors (const std::set< TagID > &tags)
Close all vectors for given tags.
void zeroTaggedVector (const TagID tag)
Zero vector with the given tag.
void zeroTaggedVectors (const std::set< TagID > &tags)
Zero all vectors for given tags.
void setVariableGlobalDoFs (const std::string &var_name)
set all the global dof indices for a variable
const std::vector< dof_id_type > & getVariableGlobalDoFs ()
Get the global dof indices of a variable, this needs to be called after the indices have been set by setVariableGlobalDoFs
SparseMatrix< Number > & addMatrix (TagID tag)
Adds a matrix with a given tag.
void removeMatrix (TagID tag)
Removes a matrix with a given tag.
virtual const std::string & name () const
const std::vector< VariableName > & getVariableNames () const
void getStandardFieldVariableNames (std::vector< VariableName > &std_field_variables) const
unsigned int getMaxVariableNumber () const
Returns the maximum number of all variables on the system.
virtual void computeVariables (const NumericVector< Number > &)
void copyVars (ExodusII_IO &io)
virtual void copySolutionsBackwards ()
Copy current solution into old and older.
TimeIntegrator * getTimeIntegrator ()
const TimeIntegrator * getTimeIntegrator () const
std::shared_ptr< TimeIntegrator > getSharedTimeIntegrator ()
bool hasVarCopy () const
Whether or not there are variables to be restarted from an Exodus mesh file.
void addScalingVector ()
Add the scaling factor vector to the system.
bool solutionStatesInitialized () const
Whether or not the solution states have been initialized via initSolutionState()
virtual void initialSetup ()
Setup Functions.
virtual void timestepSetup ()
virtual void customSetup (const ExecFlagType &exec_type)
virtual void subdomainSetup ()
virtual void residualSetup ()
virtual void jacobianSetup ()
void clearAllDofIndices ()
Clear all dof indices from moose variables.
void setActiveVariableCoupleableVectorTags (const std::set< TagID > &vtags, THREAD_ID tid)
Set the active vector tags for the variables.
void setActiveScalarVariableCoupleableVectorTags (const std::set< TagID > &vtags, THREAD_ID tid)
Set the active vector tags for the scalar variables.
Moose::VarKindType varKind () const
virtual bool hasVariable (const std::string &var_name) const
Query a system for a variable.
virtual bool hasScalarVariable (const std::string &var_name) const
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Member Functions
NumericVector< Number > & solutionInternal () const override
Internal getter for solution owned by libMesh.
Protected Attributes
SystemBase & _undisplaced_system
TransientExplicitSystem & _sys
SubProblem & _subproblem
MooseApp & _app
Factory & _factory
MooseMesh & _mesh
std::string _name
The name of this system.
std::vector< VariableWarehouse > _vars
Variable warehouses (one for each thread)
std::map< unsigned int, std::set< SubdomainID > > _var_map
Map of variables (variable id -> array of subdomains where it lives)
unsigned int _max_var_number
Maximum variable number.
std::vector< std::string > _vars_to_be_zeroed_on_residual
std::vector< std::string > _vars_to_be_zeroed_on_jacobian
Real _du_dot_du
Real _du_dotdot_du
std::vector< NumericVector< Number > * > _tagged_vectors
Tagged vectors (pointer)
std::vector< SparseMatrix< Number > * > _tagged_matrices
Tagged matrices (pointer)
std::vector< bool > _matrix_tag_active_flags
Active flags for tagged matrices.
NumericVector< Real > * _saved_old
NumericVector< Real > * _saved_older
NumericVector< Real > * _saved_dot_old
NumericVector< Real > * _saved_dotdot_old
Moose::VarKindType _var_kind
default kind of variables in this system
std::vector< VarCopyInfo > _var_to_copy
size_t _max_var_n_dofs_per_elem
Maximum number of dofs for any one variable on any one element.
size_t _max_var_n_dofs_per_node
Maximum number of dofs for any one variable on any one node.
std::shared_ptr< TimeIntegrator > _time_integrator
Time integrator.
std::vector< std::vector< MooseVariableFieldBase * > > _numbered_vars
Map variable number to its pointer.
bool _automatic_scaling
Whether to automatically scale the variables.
bool _verbose
True if printing out additional information.
bool _solution_states_initialized
Whether or not the solution states have been initialized.
std::vector< dof_id_type > _var_all_dof_indices
Container for the dof indices of a given variable.
Private Member Functions
TagName oldSolutionStateVectorName (const unsigned int, Moose::SolutionIterationType iteration_type) const
Gets the vector name used for an old (not current) solution state.
Private Attributes
std::array< std::vector< NumericVector< Number > * >, 2 > _solution_states
The solution states (0 = current, 1 = old, 2 = older, etc)
std::vector< NumericVector< Number > * > _saved_solution_states
The saved solution states (0 = current, 1 = old, 2 = older, etc)
Detailed Description
Definition at line 24 of file DisplacedSystem.h.
Constructor & Destructor Documentation
DisplacedSystem() [1/2]
DisplacedSystem::DisplacedSystem (DisplacedSystem &&) delete
DisplacedSystem() [2/2]
DisplacedSystem::DisplacedSystem (DisplacedProblem & problem, SystemBase & undisplaced_system, const std::string & name, Moose::VarKindType var_kind)
Definition at line 18 of file DisplacedSystem.C.
  : SystemBase(problem, name, var_kind),
    _undisplaced_system(undisplaced_system),
    _sys(problem.es().add_system<TransientExplicitSystem>(name))
{
  if (!problem.defaultGhosting())
  {
    auto & dof_map = _sys.get_dof_map();
    dof_map.remove_algebraic_ghosting_functor(dof_map.default_algebraic_ghosting());
    dof_map.set_implicit_neighbor_dofs(false);
  }
}
~DisplacedSystem()
DisplacedSystem::~DisplacedSystem () virtual
Definition at line 34 of file DisplacedSystem.C.
{}
Member Function Documentation
activeAllMatrixTags()
void SystemBase::activeAllMatrixTags () virtual inherited
Make all exsiting matrices ative.
Definition at line 1103 of file SystemBase.C.
{
  auto num_matrix_tags = _subproblem.numMatrixTags();
  _matrix_tag_active_flags.resize(num_matrix_tags);
  for (decltype(num_matrix_tags) tag = 0; tag < num_matrix_tags; tag++)
    if (hasMatrix(tag))
      _matrix_tag_active_flags[tag] = true;
    else
      _matrix_tag_active_flags[tag] = false;
}
Referenced by NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualAndJacobianInternal(), and NonlinearSystemBase::computeResidualTags().
activeMatrixTag()
void SystemBase::activeMatrixTag (TagID tag) virtual inherited
Active a matrix for tag.
Definition at line 1068 of file SystemBase.C.
{
  mooseAssert(_subproblem.matrixTagExists(tag),
              "Cannot active Matrix with matrix_tag : " << tag << "that does not exist");
  if (_matrix_tag_active_flags.size() < tag + 1)
    _matrix_tag_active_flags.resize(tag + 1);
  _matrix_tag_active_flags[tag] = true;
}
addMatrix()
SparseMatrix< Number > & SystemBase::addMatrix (TagID tag) inherited
Adds a matrix with a given tag.
Parameters
tag_name The name of the tag
Definition at line 559 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag))
    mooseError("Cannot add tagged matrix with TagID ",
               tag,
               " in system '",
               name(),
               "' because the tag does not exist in the problem");
  if (hasMatrix(tag))
    return getMatrix(tag);
  const auto matrix_name = _subproblem.matrixTagName(tag);
  SparseMatrix<Number> & mat = system().add_matrix(matrix_name);
  associateMatrixToTag(mat, tag);
  return mat;
}
addScalingVector()
void SystemBase::addScalingVector () inherited
Add the scaling factor vector to the system.
Definition at line 1464 of file SystemBase.C.
{
  addVector("scaling_factors", /*project=*/false, libMesh::ParallelType::GHOSTED);
  _subproblem.hasScalingVector();
}
Referenced by MooseVariableBase::initialSetup().
addTimeIntegrator() [1/3]
virtual void SystemBase::addTimeIntegrator (const std::string & , const std::string & , InputParameters &) inline virtual
Reimplemented from SystemBase.
Definition at line 861 of file SystemBase.h.
  {
  }
addTimeIntegrator() [2/3]
void DisplacedSystem::addTimeIntegrator (std::shared_ptr< TimeIntegrator > ti) override virtual
Reimplemented from SystemBase.
Definition at line 55 of file DisplacedSystem.C.
{
  _time_integrator = ti;
}
addTimeIntegrator() [3/3]
virtual void SystemBase::addTimeIntegrator (std::shared_ptr< TimeIntegrator >) inline virtual
Reimplemented from SystemBase.
Definition at line 867 of file SystemBase.h.
{}
addVariable()
void SystemBase::addVariable (const std::string & var_type, const std::string & var_name, InputParameters & parameters) virtual inherited
Canonical method for adding a variable.
Parameters
var_type the type of the variable, e.g. MooseVariableScalar
var_name the variable name, e.g. 'u'
params the InputParameters from which to construct the variable
Reimplemented in AuxiliarySystem.
Definition at line 708 of file SystemBase.C.
{
  _numbered_vars.resize(libMesh::n_threads());
  auto components = parameters.get<unsigned int>("components");
  // Convert the std::vector parameter provided by the user into a std::set for use by libMesh's
  // System::add_variable method
  std::set<SubdomainID> blocks;
  const auto & block_param = parameters.get<std::vector<SubdomainName>>("block");
  for (const auto & subdomain_name : block_param)
  {
    SubdomainID blk_id = _mesh.getSubdomainID(subdomain_name);
    blocks.insert(blk_id);
  }
  auto fe_type = FEType(Utility::string_to_enum<Order>(parameters.get<MooseEnum>("order")),
                        Utility::string_to_enum<FEFamily>(parameters.get<MooseEnum>("family")));
  unsigned int var_num;
  if (var_type == "ArrayMooseVariable")
  {
    if (fe_type.family == NEDELEC_ONE || fe_type.family == LAGRANGE_VEC ||
        fe_type.family == MONOMIAL_VEC || fe_type.family == RAVIART_THOMAS)
      mooseError("Vector family type cannot be used in an array variable");
    // Build up the variable names
    std::vector<std::string> var_names;
    for (unsigned int i = 0; i < components; i++)
      var_names.push_back(SubProblem::arrayVariableComponent(name, i));
    // The number returned by libMesh is the _last_ variable number... we want to hold onto the
    // _first_
    var_num = system().add_variables(var_names, fe_type, &blocks) - (components - 1);
    // Set as array variable
    if (parameters.isParamSetByUser("array") && !parameters.get<bool>("array"))
      mooseError("Variable '",
                 name,
                 "' is an array variable ('components' > 1) but 'array' is set to false.");
    parameters.set<bool>("array") = true;
  }
  else
    var_num = system().add_variable(name, fe_type, &blocks);
  parameters.set<unsigned int>("_var_num") = var_num;
  parameters.set<SystemBase *>("_system_base") = this;
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    parameters.set<THREAD_ID>("tid") = tid;
    std::shared_ptr<MooseVariableBase> var =
        _factory.create<MooseVariableBase>(var_type, name, parameters, tid);
    _vars[tid].add(name, var);
    if (auto fe_var = dynamic_cast<MooseVariableFieldBase *>(var.get()))
    {
      auto required_size = var_num + components;
      if (required_size > _numbered_vars[tid].size())
        _numbered_vars[tid].resize(required_size);
      for (MooseIndex(components) component = 0; component < components; ++component)
        _numbered_vars[tid][var_num + component] = fe_var;
      if (auto * const functor = dynamic_cast<Moose::FunctorBase<ADReal> *>(fe_var))
        _subproblem.addFunctor(name, *functor, tid);
      else if (auto * const functor = dynamic_cast<Moose::FunctorBase<ADRealVectorValue> *>(fe_var))
        _subproblem.addFunctor(name, *functor, tid);
      else if (auto * const functor = dynamic_cast<Moose::FunctorBase<RealEigenVector> *>(fe_var))
        _subproblem.addFunctor(name, *functor, tid);
      else
        mooseError("This should be a functor");
    }
    if (var->blockRestricted())
      for (const SubdomainID & id : var->blockIDs())
        for (MooseIndex(components) component = 0; component < components; ++component)
          _var_map[var_num + component].insert(id);
    else
      for (MooseIndex(components) component = 0; component < components; ++component)
        _var_map[var_num + component] = std::set<SubdomainID>();
  }
  // getMaxVariableNumber is an API method used in Rattlesnake
  if (var_num > _max_var_number)
    _max_var_number = var_num;
}
Referenced by AuxiliarySystem::addVariable().
addVariableToCopy()
void SystemBase::addVariableToCopy (const std::string & dest_name, const std::string & source_name, const std::string & timestep) virtual inherited
Add info about variable that will be copied.
Parameters
dest_name Name of the nodal variable being used for copying into (name is from the exodusII file)
source_name Name of the nodal variable being used for copying from (name is from the exodusII file)
timestep Timestep in the file being used
Definition at line 1143 of file SystemBase.C.
{
  _var_to_copy.push_back(VarCopyInfo(dest_name, source_name, timestep));
}
Referenced by CopyNodalVarsAction::act().
addVariableToZeroOnJacobian()
virtual void DisplacedSystem::addVariableToZeroOnJacobian (std::string var_name) inline override virtual
Adds this variable to the list of variables to be zeroed during each jacobian evaluation.
Parameters
var_name The name of the variable to be zeroed.
Reimplemented from SystemBase.
Definition at line 197 of file DisplacedSystem.h.
  {
    _undisplaced_system.addVariableToZeroOnJacobian(var_name);
  }
addVariableToZeroOnResidual()
virtual void DisplacedSystem::addVariableToZeroOnResidual (std::string var_name) inline override virtual
Adds this variable to the list of variables to be zeroed during each residual evaluation.
Parameters
var_name The name of the variable to be zeroed.
Reimplemented from SystemBase.
Definition at line 188 of file DisplacedSystem.h.
  {
    _undisplaced_system.addVariableToZeroOnResidual(var_name);
  }
addVector() [1/2]
NumericVector< Number > & SystemBase::addVector (const std::string & vector_name, const bool project, const ParallelType type) inherited
Adds a solution length vector to the system.
Parameters
vector_name The name of the vector.
project Whether or not to project this vector when doing mesh refinement. If the vector is just going to be recomputed then there is no need to project it.
type What type of parallel vector. This is usually either PARALLEL or GHOSTED. GHOSTED is needed if you are going to be accessing off-processor entries. The ghosting pattern is the same as the solution vector.
Definition at line 597 of file SystemBase.C.
{
  if (hasVector(vector_name))
    return getVector(vector_name);
  NumericVector<Number> & vec = system().add_vector(vector_name, project, type);
  return vec;
}
Referenced by AuxiliarySystem::addDotVectors(), NonlinearSystemBase::addDotVectors(), SystemBase::addScalingVector(), PicardSolve::allocateStorage(), SecantSolve::allocateStorage(), SteffensenSolve::allocateStorage(), AStableDirk4::AStableDirk4(), ExplicitTimeIntegrator::ExplicitTimeIntegrator(), NonlinearSystemBase::getResidualNonTimeVector(), NonlinearSystemBase::getResidualTimeVector(), CentralDifference::initialSetup(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), SystemBase::needSolutionState(), NonlinearSystemBase::residualGhosted(), and SystemBase::saveOldSolutions().
addVector() [2/2]
NumericVector< Number > & SystemBase::addVector (TagID tag, const bool project, const ParallelType type) inherited
Adds a solution length vector to the system with the specified TagID.
Parameters
tag_name The name of the tag
project Whether or not to project this vector when doing mesh refinement. If the vector is just going to be recomputed then there is no need to project it.
type What type of parallel vector. This is usually either PARALLEL or GHOSTED. GHOSTED is needed if you are going to be accessing off-processor entries. The ghosting pattern is the same as the solution vector.
Definition at line 607 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot add tagged vector with TagID ",
               tag,
               " in system '",
               name(),
               "' because the tag does not exist in the problem");
  if (hasVector(tag))
  {
    auto & vec = getVector(tag);
    if (type != ParallelType::AUTOMATIC && vec.type() != type)
      mooseError("Cannot add tagged vector '",
                 _subproblem.vectorTagName(tag),
                 "', in system '",
                 name(),
                 "' because a vector with the same name was found with a different parallel type");
    return vec;
  }
  const auto vector_name = _subproblem.vectorTagName(tag);
  NumericVector<Number> & vec = system().add_vector(vector_name, project, type);
  associateVectorToTag(vec, tag);
  return vec;
}
applyScalingFactors()
void SystemBase::applyScalingFactors (const std::vector< Real > & inverse_scaling_factors) inherited
Applies scaling factors to the system's variables.
Parameters
inverse_scaling_factors A vector containing the inverse of each variable's scaling factor, e.g. 1 / scaling_factor
Definition at line 1424 of file SystemBase.C.
{
  for (MooseIndex(_vars) thread = 0; thread < _vars.size(); ++thread)
  {
    auto & field_variables = _vars[thread].fieldVariables();
    for (MooseIndex(field_variables) i = 0; i < field_variables.size(); ++i)
      field_variables[i]->scalingFactor(1. / inverse_scaling_factors[i] *
                                        field_variables[i]->scalingFactor());
    auto offset = field_variables.size();
    auto & scalar_variables = _vars[thread].scalars();
    for (MooseIndex(scalar_variables) i = 0; i < scalar_variables.size(); ++i)
      scalar_variables[i]->scalingFactor(1. / inverse_scaling_factors[offset + i] *
                                         scalar_variables[i]->scalingFactor());
    if (thread == 0 && _verbose)
    {
      _console << "Automatic scaling factors:\n";
      auto original_flags = _console.flags();
      auto original_precision = _console.precision();
      _console.unsetf(std::ios_base::floatfield);
      _console.precision(6);
      for (const auto & field_variable : field_variables)
        _console << "  " << field_variable->name() << ": " << field_variable->scalingFactor()
                 << "\n";
      for (const auto & scalar_variable : scalar_variables)
        _console << "  " << scalar_variable->name() << ": " << scalar_variable->scalingFactor()
                 << "\n";
      _console << "\n" << std::endl;
      // restore state
      _console.flags(original_flags);
      _console.precision(original_precision);
    }
  }
}
Referenced by NonlinearSystemBase::computeScaling().
assignMaxVarNDofsPerElem()
void SystemBase::assignMaxVarNDofsPerElem (std::size_t max_dofs) inline inherited
assign the maximum element dofs
Definition at line 575 of file SystemBase.h.
{ _max_var_n_dofs_per_elem = max_dofs; }
assignMaxVarNDofsPerNode()
void SystemBase::assignMaxVarNDofsPerNode (std::size_t max_dofs) inline inherited
assign the maximum node dofs
Definition at line 580 of file SystemBase.h.
{ _max_var_n_dofs_per_node = max_dofs; }
associateMatrixToTag()
virtual void DisplacedSystem::associateMatrixToTag (SparseMatrix< Number > & matrix, TagID tag) inline override virtual
Associate a matrix to a tag.
Reimplemented from SystemBase.
Definition at line 85 of file DisplacedSystem.h.
  {
    _undisplaced_system.associateMatrixToTag(matrix, tag);
  }
associateVectorToTag()
virtual void DisplacedSystem::associateVectorToTag (NumericVector< Number > & vec, TagID tag) inline override virtual
Associate a vector for a given tag.
Reimplemented from SystemBase.
Definition at line 65 of file DisplacedSystem.h.
  {
    _undisplaced_system.associateVectorToTag(vec, tag);
  }
augmentSendList()
virtual void DisplacedSystem::augmentSendList (std::vector< dof_id_type > & send_list) inline override virtual
Will modify the send_list to add all of the extra ghosted dofs for this system.
Reimplemented from SystemBase.
Definition at line 169 of file DisplacedSystem.h.
  {
    _undisplaced_system.augmentSendList(send_list);
  }
augmentSparsity()
virtual void DisplacedSystem::augmentSparsity (SparsityPattern::Graph & , std::vector< dof_id_type > & , std::vector< dof_id_type > &) inline override virtual
This is an empty function since the displaced system doesn't have a matrix! All sparsity pattern modification will be taken care of by the undisplaced system directly.
Implements SystemBase.
Definition at line 178 of file DisplacedSystem.h.
  {
  }
automaticScaling() [1/2]
bool SystemBase::automaticScaling () const inline inherited
Getter for whether we are performing automatic scaling.
Returns
whether we are performing automatic scaling
Definition at line 117 of file SystemBase.h.
{ return _automatic_scaling; }
Referenced by SubProblem::automaticScaling().
automaticScaling() [2/2]
void SystemBase::automaticScaling (bool automatic_scaling) inline inherited
Setter for whether we are performing automatic scaling.
Parameters
automatic_scaling A boolean representing whether we are performing automatic scaling
Definition at line 123 of file SystemBase.h.
{ _automatic_scaling = automatic_scaling; }
clearAllDofIndices()
void SystemBase::clearAllDofIndices () inherited
Clear all dof indices from moose variables.
Definition at line 1519 of file SystemBase.C.
{
  for (auto & var_warehouse : _vars)
    var_warehouse.clearAllDofIndices();
}
Referenced by SubProblem::clearAllDofIndices().
closeTaggedMatrices()
void SystemBase::closeTaggedMatrices (const std::set< TagID > & tags) inherited
Close all matrices associated the tags.
Definition at line 1009 of file SystemBase.C.
{
  for (auto tag : tags)
    if (hasMatrix(tag))
      getMatrix(tag).close();
}
Referenced by NonlinearSystemBase::computeJacobianInternal(), and NonlinearSystemBase::computeResidualAndJacobianTags().
closeTaggedVector()
void SystemBase::closeTaggedVector (const TagID tag) inherited
Close vector with the given tag.
Definition at line 638 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot close vector with TagID ",
               tag,
               " in system '",
               name(),
               "' because that tag does not exist in the problem");
  else if (!hasVector(tag))
    mooseError("Cannot close vector tag with name '",
               _subproblem.vectorTagName(tag),
               "' in system '",
               name(),
               "' because there is no vector associated with that tag");
  getVector(tag).close();
}
Referenced by SystemBase::closeTaggedVectors().
closeTaggedVectors()
void SystemBase::closeTaggedVectors (const std::set< TagID > & tags) inherited
Close all vectors for given tags.
Definition at line 657 of file SystemBase.C.
{
  for (const auto tag : tags)
    closeTaggedVector(tag);
}
Referenced by NonlinearSystemBase::computeResidualAndJacobianTags(), and NonlinearSystemBase::computeResidualTags().
computeVariables()
virtual void SystemBase::computeVariables (const NumericVector< Number > &) inline virtual inherited
Definition at line 852 of file SystemBase.h.
{}
computingScalingJacobian()
bool SystemBase::computingScalingJacobian () const inherited
Whether we are computing an initial Jacobian for automatic variable scaling.
Definition at line 1471 of file SystemBase.C.
{
  return _subproblem.computingScalingJacobian();
}
Referenced by Assembly::addJacobianBlock(), Assembly::addJacobianBlockNonlocal(), Assembly::addJacobianNeighbor(), Assembly::cacheJacobianBlock(), EigenKernel::computeJacobian(), Kernel::computeJacobian(), VectorKernel::computeJacobian(), and FEProblemBase::computeJacobianTags().
copyOldSolutions()
void SystemBase::copyOldSolutions () virtual inherited
Shifts the solutions backwards in time.
Definition at line 1254 of file SystemBase.C.
{
  const auto states =
      _solution_states[static_cast<unsigned short>(Moose::SolutionIterationType::Time)].size();
  if (states > 1)
    for (unsigned int i = states - 1; i > 0; --i)
      solutionState(i) = solutionState(i - 1);
  if (solutionUDotOld())
    *solutionUDotOld() = *solutionUDot();
  if (solutionUDotDotOld())
    *solutionUDotDotOld() = *solutionUDotDot();
  if (solutionPreviousNewton())
    *solutionPreviousNewton() = *currentSolution();
}
Referenced by EigenExecutionerBase::inversePowerIteration().
copySolutionsBackwards()
void SystemBase::copySolutionsBackwards () virtual inherited
Copy current solution into old and older.
Definition at line 1227 of file SystemBase.C.
{
  system().update();
  // Copying the solutions backward so the current solution will become the old, and the old will
  // become older. The same applies to the nonlinear iterates.
  for (const auto iteration_index : index_range(_solution_states))
  {
    const auto states = _solution_states[iteration_index].size();
    if (states > 1)
      for (unsigned int i = states - 1; i > 0; --i)
        solutionState(i, Moose::SolutionIterationType(iteration_index)) =
            solutionState(i - 1, Moose::SolutionIterationType(iteration_index));
  }
  if (solutionUDotOld())
    *solutionUDotOld() = *solutionUDot();
  if (solutionUDotDotOld())
    *solutionUDotDotOld() = *solutionUDotDot();
  if (solutionPreviousNewton())
    *solutionPreviousNewton() = *currentSolution();
}
copyVars()
void SystemBase::copyVars (ExodusII_IO & io) inherited
Definition at line 1151 of file SystemBase.C.
{
  int n_steps = io.get_num_time_steps();
  bool did_copy = false;
  for (const auto & vci : _var_to_copy)
  {
    int timestep = -1;
    if (vci._timestep == "LATEST")
      // Use the last time step in the file from which to retrieve the solution
      timestep = n_steps;
    else
    {
      timestep = MooseUtils::convert<int>(vci._timestep);
      if (timestep > n_steps)
        mooseError("Invalid value passed as \"initial_from_file_timestep\". Expected \"LATEST\" or "
                   "a valid integer between 1 and ",
                   n_steps,
                   " inclusive, received ",
                   vci._timestep);
    }
    did_copy = true;
    if (hasVariable(vci._dest_name))
    {
      const auto & var = getVariable(0, vci._dest_name);
      if (var.isArray())
      {
        const auto & array_var = getFieldVariable<RealEigenVector>(0, vci._dest_name);
        for (MooseIndex(var.count()) i = 0; i < var.count(); ++i)
        {
          const auto exodus_var = _subproblem.arrayVariableComponent(vci._source_name, i);
          const auto system_var = array_var.componentName(i);
          if (var.isNodal())
            io.copy_nodal_solution(system(), exodus_var, system_var, timestep);
          else
            io.copy_elemental_solution(system(), exodus_var, system_var, timestep);
        }
      }
      else
      {
        if (var.isNodal())
          io.copy_nodal_solution(system(), vci._dest_name, vci._source_name, timestep);
        else
          io.copy_elemental_solution(system(), vci._dest_name, vci._source_name, timestep);
      }
    }
    else if (hasScalarVariable(vci._dest_name))
      io.copy_scalar_solution(system(), {vci._dest_name}, {vci._source_name}, timestep);
    else
      mooseError("Unrecognized variable ", vci._dest_name, " in variables to copy.");
  }
  if (did_copy)
    solution().close();
}
currentSolution()
const NumericVector< Number > *const & DisplacedSystem::currentSolution () const inline override virtual
The solution vector that is currently being operated on.
This is typically a ghosted vector that comes in from the Nonlinear solver.
Implements SystemBase.
Definition at line 113 of file DisplacedSystem.h.
  {
    return _undisplaced_system.currentSolution();
  }
customSetup()
void SystemBase::customSetup (const ExecFlagType & exec_type) virtual inherited
Reimplemented in AuxiliarySystem, and NonlinearSystemBase.
Definition at line 1491 of file SystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _vars[tid].customSetup(exec_type);
}
Referenced by SystemBase::customSetup(), AuxiliarySystem::customSetup(), and NonlinearSystemBase::customSetup().
deactiveAllMatrixTags()
void SystemBase::deactiveAllMatrixTags () virtual inherited
Make matrices inactive.
Definition at line 1092 of file SystemBase.C.
{
  auto num_matrix_tags = _subproblem.numMatrixTags();
  _matrix_tag_active_flags.resize(num_matrix_tags);
  for (decltype(num_matrix_tags) tag = 0; tag < num_matrix_tags; tag++)
    _matrix_tag_active_flags[tag] = false;
}
Referenced by NonlinearSystemBase::computeResidualTags(), and NonlinearSystemBase::setInitialSolution().
deactiveMatrixTag()
void SystemBase::deactiveMatrixTag (TagID tag) virtual inherited
deactive a matrix for tag
Definition at line 1080 of file SystemBase.C.
{
  mooseAssert(_subproblem.matrixTagExists(tag),
              "Cannot deactivate Matrix with matrix_tag : " << tag << "that does not exist");
  if (_matrix_tag_active_flags.size() < tag + 1)
    _matrix_tag_active_flags.resize(tag + 1);
  _matrix_tag_active_flags[tag] = false;
}
defaultMatrixTags()
virtual std::set< TagID > DisplacedSystem::defaultMatrixTags () const inline override virtual
Get the default matrix tags associted with this system.
Reimplemented from SystemBase.
Definition at line 60 of file DisplacedSystem.h.
  {
    return _undisplaced_system.defaultMatrixTags();
  }
defaultVectorTags()
virtual std::set< TagID > DisplacedSystem::defaultVectorTags () const inline override virtual
Get the default vector tags associated with this system.
Reimplemented from SystemBase.
Definition at line 56 of file DisplacedSystem.h.
  {
    return _undisplaced_system.defaultVectorTags();
  }
disassociateDefaultMatrixTags()
virtual void DisplacedSystem::disassociateDefaultMatrixTags () inline override virtual
Disassociate the matrices associated with the default matrix tags of this system.
Reimplemented from SystemBase.
Definition at line 100 of file DisplacedSystem.h.
  {
    _undisplaced_system.disassociateDefaultMatrixTags();
  }
disassociateDefaultVectorTags()
virtual void DisplacedSystem::disassociateDefaultVectorTags () inline override virtual
Disassociate the vectors associated with the default vector tags of this system.
Reimplemented from SystemBase.
Definition at line 80 of file DisplacedSystem.h.
  {
    _undisplaced_system.disassociateDefaultVectorTags();
  }
disassociateMatrixFromTag() [1/2]
virtual void DisplacedSystem::disassociateMatrixFromTag (SparseMatrix< Number > & matrix, TagID tag) inline override virtual
Disassociate a matrix from a tag.
Reimplemented from SystemBase.
Definition at line 90 of file DisplacedSystem.h.
  {
    _undisplaced_system.disassociateMatrixFromTag(matrix, tag);
  }
disassociateMatrixFromTag() [2/2]
virtual void DisplacedSystem::disassociateMatrixFromTag (TagID tag) inline override virtual
Disassociate any matrix that is associated with a given tag.
Reimplemented from SystemBase.
Definition at line 95 of file DisplacedSystem.h.
  {
    _undisplaced_system.disassociateMatrixFromTag(tag);
  }
disassociateVectorFromTag() [1/2]
virtual void DisplacedSystem::disassociateVectorFromTag (NumericVector< Number > & vec, TagID tag) inline override virtual
Disassociate a given vector from a given tag.
Reimplemented from SystemBase.
Definition at line 70 of file DisplacedSystem.h.
  {
    _undisplaced_system.disassociateVectorFromTag(vec, tag);
  }
disassociateVectorFromTag() [2/2]
virtual void DisplacedSystem::disassociateVectorFromTag (TagID tag) inline override virtual
Disassociate any vector that is associated with a given tag.
Reimplemented from SystemBase.
Definition at line 75 of file DisplacedSystem.h.
  {
    _undisplaced_system.disassociateVectorFromTag(tag);
  }
dofMap() [1/2]
DofMap & SystemBase::dofMap () virtual inherited
Gets writeable reference to the dof map.
Definition at line 1131 of file SystemBase.C.
{
  return system().get_dof_map();
}
Referenced by NonlinearSystemBase::assembleScalingVector(), MooseApp::attachRelationshipManagers(), SystemBase::augmentSendList(), NonlinearSystemBase::augmentSparsity(), NonlinearSystemBase::computeScaling(), NonlinearSystemBase::findImplicitGeometricCouplingEntries(), Adaptivity::init(), ActivateElementsUserObjectBase::initSolutions(), PNGOutput::makeMeshFunc(), GhostingUserObject::meshChanged(), Exodus::outputScalarVariables(), Nemesis::outputScalarVariables(), TableOutput::outputScalarVariables(), and ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes().
dofMap() [2/2]
const DofMap & SystemBase::dofMap () const virtual inherited
Gets const reference to the dof map.
Definition at line 1137 of file SystemBase.C.
{
  return system().get_dof_map();
}
duDotDotDu() [1/2]
virtual const Number & DisplacedSystem::duDotDotDu () const inline override virtual
Reimplemented from SystemBase.
Definition at line 154 of file DisplacedSystem.h.
{ return _undisplaced_system.duDotDotDu(); }
duDotDotDu() [2/2]
virtual Number & DisplacedSystem::duDotDotDu () inline override virtual
Reimplemented from SystemBase.
Definition at line 152 of file DisplacedSystem.h.
{ return _undisplaced_system.duDotDotDu(); }
duDotDu() [1/2]
virtual const Number & DisplacedSystem::duDotDu () const inline override virtual
Reimplemented from SystemBase.
Definition at line 153 of file DisplacedSystem.h.
{ return _undisplaced_system.duDotDu(); }
duDotDu() [2/2]
virtual Number & DisplacedSystem::duDotDu () inline override virtual
Reimplemented from SystemBase.
Definition at line 151 of file DisplacedSystem.h.
{ return _undisplaced_system.duDotDu(); }
flushTaggedMatrices()
void SystemBase::flushTaggedMatrices (const std::set< TagID > & tags) inherited
flushes all matrices associated to tags.
Flush assembles the matrix but doesn't shrink memory allocation
Definition at line 1017 of file SystemBase.C.
{
  for (auto tag : tags)
    if (hasMatrix(tag))
      getMatrix(tag).flush();
}
getActualFieldVariable() [1/2]
template<typename T > template MooseVariableField< RealEigenVector > & SystemBase::getActualFieldVariable< RealEigenVector > (THREAD_ID tid, const std::string & var_name) inherited
Returns a field variable pointer - this includes finite volume variables.
Definition at line 107 of file SystemBase.C.
{
  return *_vars[tid].getActualFieldVariable<T>(var_name);
}
Referenced by BoundsAuxBase::BoundsAuxBase(), Assembly::copyFaceShapes(), Assembly::copyNeighborShapes(), and Assembly::copyShapes().
getActualFieldVariable() [2/2]
template<typename T > template MooseVariableField< RealEigenVector > & SystemBase::getActualFieldVariable< RealEigenVector > (THREAD_ID tid, unsigned int var_number) inherited
Returns a field variable pointer - this includes finite volume variables.
Definition at line 128 of file SystemBase.C.
{
  return *_vars[tid].getActualFieldVariable<T>(var_number);
}
getFieldVariable() [1/2]
template<typename T > template MooseVariableFE< RealEigenVector > & SystemBase::getFieldVariable< RealEigenVector > (THREAD_ID tid, const std::string & var_name) inherited
Gets a reference to a variable of with specified name.
This excludes and cannot return finite volume variables.
Parameters
tid Thread id
var_name variable name
Returns
reference the variable (class)
Definition at line 100 of file SystemBase.C.
{
  return *_vars[tid].getFieldVariable<T>(var_name);
}
Referenced by Marker::getMarkerValue().
getFieldVariable() [2/2]
template<typename T > template MooseVariableFE< RealEigenVector > & SystemBase::getFieldVariable< RealEigenVector > (THREAD_ID tid, unsigned int var_number) inherited
Gets a reference to a variable with specified number.
This excludes and cannot return finite volume variables.
Parameters
tid Thread id
var_number libMesh variable number
Returns
reference the variable (class)
Definition at line 121 of file SystemBase.C.
{
  return *_vars[tid].getFieldVariable<T>(var_number);
}
getFVVariable()
template<typename T > template MooseVariableFV< Real > & SystemBase::getFVVariable< Real > (THREAD_ID tid, const std::string & var_name) inherited
Return a finite volume variable.
Definition at line 114 of file SystemBase.C.
{
  return *_vars[tid].getFVVariable<T>(var_name);
}
getMatrix() [1/2]
virtual const SparseMatrix< Number > & DisplacedSystem::getMatrix (TagID tag) const inline override virtual
Get a raw SparseMatrix.
Reimplemented from SystemBase.
Definition at line 239 of file DisplacedSystem.h.
  {
    return _undisplaced_system.getMatrix(tag);
  }
getMatrix() [2/2]
virtual SparseMatrix< Number > & DisplacedSystem::getMatrix (TagID tag) inline override virtual
Get a raw SparseMatrix.
Reimplemented from SystemBase.
Definition at line 235 of file DisplacedSystem.h.
  {
    return _undisplaced_system.getMatrix(tag);
  }
getMaxVariableNumber()
unsigned int SystemBase::getMaxVariableNumber () const inline inherited
Returns the maximum number of all variables on the system.
Definition at line 850 of file SystemBase.h.
{ return _max_var_number; }
getMaxVarNDofsPerElem()
std::size_t SystemBase::getMaxVarNDofsPerElem () const inline inherited
Gets the maximum number of dofs used by any one variable on any one element.
Returns
The max
Definition at line 563 of file SystemBase.h.
{ return _max_var_n_dofs_per_elem; }
Referenced by Moose::globalDofIndexToDerivative().
getMaxVarNDofsPerNode()
std::size_t SystemBase::getMaxVarNDofsPerNode () const inline inherited
Gets the maximum number of dofs used by any one variable on any one node.
Returns
The max
Definition at line 570 of file SystemBase.h.
{ return _max_var_n_dofs_per_node; }
getMinQuadratureOrder()
Order SystemBase::getMinQuadratureOrder () virtual inherited
Get minimal quadrature order needed for integrating variables in this system.
Returns
The minimal order of quadrature
Reimplemented in AuxiliarySystem.
Definition at line 230 of file SystemBase.C.
{
  Order order = CONSTANT;
  const std::vector<MooseVariableFieldBase *> & vars = _vars[0].fieldVariables();
  for (const auto & var : vars)
  {
    FEType fe_type = var->feType();
    if (fe_type.default_quadrature_order() > order)
      order = fe_type.default_quadrature_order();
  }
  return order;
}
getScalarVariable() [1/2]
MooseVariableScalar & SystemBase::getScalarVariable (THREAD_ID tid, const std::string & var_name) const virtual inherited
Gets a reference to a scalar variable with specified number.
Parameters
tid Thread id
var_name A string which is the name of the variable to get.
Returns
reference the variable (class)
Definition at line 134 of file SystemBase.C.
{
  MooseVariableScalar * var = dynamic_cast<MooseVariableScalar *>(_vars[tid].getVariable(var_name));
  if (!var)
    mooseError("Scalar variable '" + var_name + "' does not exist in this system");
  return *var;
}
Referenced by Assembly::addJacobianOffDiagScalar(), MortarScalarBase::computeOffDiagJacobianScalar(), ArrayIntegratedBC::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), ArrayKernel::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), DMMooseSetVariables(), Assembly::init(), ReferenceResidualProblem::initialSetup(), and NonlinearSystemBase::setupScalingData().
getScalarVariable() [2/2]
MooseVariableScalar & SystemBase::getScalarVariable (THREAD_ID tid, unsigned int var_number) const virtual inherited
Gets a reference to a variable with specified number.
Parameters
tid Thread id
var_number libMesh variable number
Returns
reference the variable (class)
Definition at line 143 of file SystemBase.C.
{
  MooseVariableScalar * var =
      dynamic_cast<MooseVariableScalar *>(_vars[tid].getVariable(var_number));
  if (!var)
    mooseError("variable #" + Moose::stringify(var_number) + " does not exist in this system");
  return *var;
}
getScalarVariables()
const std::vector< MooseVariableScalar * > & SystemBase::getScalarVariables (THREAD_ID tid) inline inherited
Definition at line 737 of file SystemBase.h.
  {
    return _vars[tid].scalars();
  }
Referenced by Assembly::addResidualScalar(), ODEKernel::computeJacobian(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), AuxiliarySystem::computeScalarVars(), Assembly::init(), SystemBase::initSolutionState(), NonlinearThread::onElement(), Assembly::prepareOffDiagScalar(), and Assembly::prepareScalar().
getSharedTimeIntegrator()
std::shared_ptr< TimeIntegrator > SystemBase::getSharedTimeIntegrator () inline inherited
Definition at line 872 of file SystemBase.h.
{ return _time_integrator; }
Referenced by DisplacedProblem::DisplacedProblem().
getStandardFieldVariableNames()
void SystemBase::getStandardFieldVariableNames (std::vector< VariableName > & std_field_variables) const inherited
getSubdomainsForVar() [1/2]
const std::set< SubdomainID > & SystemBase::getSubdomainsForVar (const std::string & var_name) const inline inherited
Get the block where a variable of this system is defined.
Parameters
var_name The name of the variable
Returns
the set of subdomain ids where the variable is active (defined)
Definition at line 753 of file SystemBase.h.
  {
    return getSubdomainsForVar(getVariable(0, var_name).number());
  }
getSubdomainsForVar() [2/2]
const std::set< SubdomainID > & SystemBase::getSubdomainsForVar (unsigned int var_number) const inline inherited
Definition at line 742 of file SystemBase.h.
  {
    return _var_map.at(var_number);
  }
Referenced by NonlinearSystemBase::checkKernelCoverage(), and SystemBase::getSubdomainsForVar().
getTimeIntegrator() [1/2]
TimeIntegrator * SystemBase::getTimeIntegrator () inline inherited
Definition at line 869 of file SystemBase.h.
{ return _time_integrator.get(); }
Referenced by Transient::endStep(), AB2PredictorCorrector::estimateTimeError(), Transient::getTimeIntegratorName(), MooseVariableData< OutputType >::MooseVariableData(), and Transient::preExecute().
getTimeIntegrator() [2/2]
const TimeIntegrator * SystemBase::getTimeIntegrator () const inline inherited
Definition at line 870 of file SystemBase.h.
{ return _time_integrator.get(); }
getVariable() [1/2]
MooseVariableFieldBase & SystemBase::getVariable (THREAD_ID tid, const std::string & var_name) const inherited
Gets a reference to a variable of with specified name.
Parameters
tid Thread id
var_name variable name
Returns
reference the variable (class)
Definition at line 79 of file SystemBase.C.
{
  MooseVariableFieldBase * var =
      dynamic_cast<MooseVariableFieldBase *>(_vars[tid].getVariable(var_name));
  if (!var)
    mooseError("Variable '", var_name, "' does not exist in this system");
  return *var;
}
Referenced by AdaptivityAction::act(), Assembly::addJacobianBlock(), Assembly::addJacobianBlockNonlocal(), FEProblemBase::addJacobianBlockTags(), Assembly::addJacobianNeighbor(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), Assembly::copyFaceShapes(), Assembly::copyNeighborShapes(), Assembly::copyShapes(), SystemBase::copyVars(), DMMooseSetVariables(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), NodeElemConstraint::getConnectedDofIndices(), NodeFaceConstraint::getConnectedDofIndices(), SystemBase::getSubdomainsForVar(), ResidualObject::getVariable(), Assembly::init(), NodalNormalsPreprocessor::initialize(), ReferenceResidualProblem::initialSetup(), Assembly::initNonlocalCoupling(), PNGOutput::makeMeshFunc(), FEProblemBase::prepare(), Assembly::prepareBlock(), Assembly::prepareBlockNonlocal(), AddPeriodicBCAction::setPeriodicVars(), NonlinearSystemBase::setupScalingData(), UpdateErrorVectorsThread::UpdateErrorVectorsThread(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
getVariable() [2/2]
MooseVariableFieldBase & SystemBase::getVariable (THREAD_ID tid, unsigned int var_number) const inherited
Gets a reference to a variable with specified number.
Parameters
tid Thread id
var_number libMesh variable number
Returns
reference the variable (class)
Definition at line 89 of file SystemBase.C.
{
  if (var_number < _numbered_vars[tid].size())
    if (_numbered_vars[tid][var_number])
      return *_numbered_vars[tid][var_number];
  mooseError("Variable #", Moose::stringify(var_number), " does not exist in this system");
}
getVariableBlocks()
const std::set< SubdomainID > * SystemBase::getVariableBlocks (unsigned int var_number) virtual inherited
Get the block where a variable of this system is defined.
Parameters
var_number The number of the variable
Returns
the set of subdomain ids where the variable is active (defined)
Definition at line 153 of file SystemBase.C.
{
  mooseAssert(_var_map.find(var_number) != _var_map.end(), "Variable does not exist.");
  if (_var_map[var_number].empty())
    return nullptr;
  else
    return &_var_map[var_number];
}
Referenced by PhysicsBasedPreconditioner::addSystem().
getVariableGlobalDoFs()
const std::vector< dof_id_type > & SystemBase::getVariableGlobalDoFs () inline inherited
Get the global dof indices of a variable, this needs to be called after the indices have been set by setVariableGlobalDoFs
Definition at line 825 of file SystemBase.h.
{ return _var_all_dof_indices; }
getVariableNames()
const std::vector< VariableName > & SystemBase::getVariableNames () const inline inherited
Definition at line 843 of file SystemBase.h.
{ return _vars[0].names(); }
Referenced by MooseEigenSystem::buildSystemDoFIndices(), NonlinearSystemBase::checkKernelCoverage(), SystemBase::hasVariable(), SystemBase::isArrayVariable(), AddPeriodicBCAction::setPeriodicVars(), and SingleMatrixPreconditioner::SingleMatrixPreconditioner().
getVariables()
const std::vector< MooseVariableFieldBase * > & SystemBase::getVariables (THREAD_ID tid) inline inherited
Definition at line 732 of file SystemBase.h.
  {
    return _vars[tid].fieldVariables();
  }
Referenced by Assembly::addJacobianOffDiagScalar(), Assembly::addResidual(), Assembly::addResidualLower(), Assembly::addResidualNeighbor(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), Assembly::cacheResidual(), Assembly::cacheResidualLower(), Assembly::cacheResidualNeighbor(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), Assembly::init(), Assembly::initNonlocalCoupling(), SystemBase::initSolutionState(), Assembly::prepareLowerD(), Assembly::prepareNeighbor(), Assembly::prepareOffDiagScalar(), Assembly::prepareResidual(), Assembly::setResidual(), and Assembly::setResidualNeighbor().
getVector() [1/4]
const NumericVector< Number > & DisplacedSystem::getVector (const std::string & name) const override virtual
Reimplemented from SystemBase.
Definition at line 46 of file DisplacedSystem.C.
{
  if (_sys.have_vector(name))
    return _sys.get_vector(name);
  else
    return _undisplaced_system.getVector(name);
}
getVector() [2/4]
NumericVector< Number > & DisplacedSystem::getVector (const std::string & name) override virtual
Get a raw NumericVector by name.
Get a raw NumericVector with the given name.
Reimplemented from SystemBase.
Definition at line 37 of file DisplacedSystem.C.
{
  if (_sys.have_vector(name))
    return _sys.get_vector(name);
  else
    return _undisplaced_system.getVector(name);
}
getVector() [3/4]
virtual const NumericVector< Number > & DisplacedSystem::getVector (TagID tag_id) const inline override virtual
Reimplemented from SystemBase.
Definition at line 40 of file DisplacedSystem.h.
  {
    return _undisplaced_system.getVector(tag_id);
  }
getVector() [4/4]
virtual NumericVector< Number > & DisplacedSystem::getVector (TagID tag) inline override virtual
Get a raw NumericVector by tag.
Reimplemented from SystemBase.
Definition at line 36 of file DisplacedSystem.h.
  {
    return _undisplaced_system.getVector(tag_id);
  }
hasMatrix()
virtual bool DisplacedSystem::hasMatrix (TagID tag) const inline override virtual
Check if the tagged matrix exists in the system.
Reimplemented from SystemBase.
Definition at line 215 of file DisplacedSystem.h.
  {
    return _undisplaced_system.hasMatrix(tag_id);
  }
hasScalarVariable()
bool SystemBase::hasScalarVariable (const std::string & var_name) const virtual inherited
Definition at line 825 of file SystemBase.C.
{
  if (system().has_variable(var_name))
    return system().variable_type(var_name).family == SCALAR;
  else
    return false;
}
Referenced by MortarScalarBase::computeJacobian(), NonlinearSystemBase::computeJacobianInternal(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), SystemBase::copyVars(), NonlinearEigenSystem::postAddResidualObject(), AddPeriodicBCAction::setPeriodicVars(), and NonlinearSystemBase::setupScalingData().
hasSolutionState()
bool DisplacedSystem::hasSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) const inline override virtual
Whether or not the system has the solution state (0 = current, 1 = old, 2 = older, etc).
Reimplemented from SystemBase.
Definition at line 290 of file DisplacedSystem.h.
{
  return _undisplaced_system.hasSolutionState(state, iteration_type);
}
hasVarCopy()
bool SystemBase::hasVarCopy () const inline inherited
Whether or not there are variables to be restarted from an Exodus mesh file.
Definition at line 875 of file SystemBase.h.
{ return _var_to_copy.size() > 0; }
hasVariable()
bool SystemBase::hasVariable (const std::string & var_name) const virtual inherited
Query a system for a variable.
Parameters
var_name name of the variable
Returns
true if the variable exists
Definition at line 800 of file SystemBase.C.
{
  auto & names = getVariableNames();
  if (system().has_variable(var_name))
    return system().variable_type(var_name).family != SCALAR;
  if (std::find(names.begin(), names.end(), var_name) != names.end())
    // array variable
    return true;
  else
    return false;
}
Referenced by ADDGKernel::ADDGKernel(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayKernel::ArrayKernel(), SystemBase::copyVars(), DGKernel::DGKernel(), DMMooseSetVariables(), FEProblemBase::duplicateVariableCheck(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), PNGOutput::makeMeshFunc(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NonlinearSystemBase::setupScalingData(), and Coupleable::writableCoupledValue().
hasVector() [1/2]
bool SystemBase::hasVector (const std::string & tag_name) const inherited
Check if the named vector exists in the system.
Definition at line 873 of file SystemBase.C.
{
  return system().have_vector(name);
}
Referenced by FEProblemBase::addCachedResidualDirectly(), Assembly::addCachedResiduals(), Assembly::addResidual(), Assembly::addResidualLower(), Assembly::addResidualNeighbor(), Assembly::addResidualScalar(), SystemBase::addVector(), NonlinearSystemBase::assembleScalingVector(), Assembly::cacheResidual(), Assembly::cacheResidualLower(), Assembly::cacheResidualNeighbor(), SystemBase::closeTaggedVector(), FEProblemBase::computeBounds(), NonlinearSystemBase::computeResidualTags(), CentralDifference::computeTimeDerivatives(), SystemBase::disassociateVectorFromTag(), SystemBase::getVector(), hasVector(), MooseVariableScalar::reinit(), SystemBase::removeVector(), SubProblem::selectVectorTagsFromSystem(), NonlinearSystemBase::setPreviousNewtonSolution(), TaggingInterface::setResidual(), SystemBase::solutionPreviousNewton(), and SystemBase::zeroTaggedVector().
hasVector() [2/2]
virtual bool DisplacedSystem::hasVector (TagID tag_id) const inline override virtual
Check if the tagged vector exists in the system.
Reimplemented from SystemBase.
Definition at line 210 of file DisplacedSystem.h.
  {
    return _undisplaced_system.hasVector(tag_id);
  }
init()
virtual void SystemBase::init () inline virtual inherited
Initialize the system.
Reimplemented in NonlinearSystem, and NonlinearSystemBase.
Definition at line 150 of file SystemBase.h.
{};
Referenced by NonlinearSystemBase::init().
initializeObjects()
virtual void SystemBase::initializeObjects () inline virtual inherited
Called only once, just before the solve begins so objects can do some precalculations.
Definition at line 155 of file SystemBase.h.
{};
initialSetup()
void SystemBase::initialSetup () virtual inherited
Setup Functions.
Reimplemented in AuxiliarySystem, and NonlinearSystemBase.
Definition at line 1477 of file SystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _vars[tid].initialSetup();
}
Referenced by SystemBase::initialSetup(), AuxiliarySystem::initialSetup(), and NonlinearSystemBase::initialSetup().
initSolutionState()
void DisplacedSystem::initSolutionState () inline override virtual
Initializes the solution state.
Reimplemented from SystemBase.
Definition at line 263 of file DisplacedSystem.h.
{
  _undisplaced_system.initSolutionState();
}
isArrayVariable()
bool SystemBase::isArrayVariable (const std::string & var_name) const virtual inherited
If a variable is an array variable.
Definition at line 813 of file SystemBase.C.
{
  auto & names = getVariableNames();
  if (!system().has_variable(var_name) &&
      std::find(names.begin(), names.end(), var_name) != names.end())
    // array variable
    return true;
  else
    return false;
}
isScalarVariable()
bool SystemBase::isScalarVariable (unsigned int var_name) const virtual inherited
Definition at line 834 of file SystemBase.C.
{
  return (system().variable(var_num).type().family == SCALAR);
}
Referenced by Assembly::init(), ReferenceResidualProblem::initialSetup(), and Assembly::initNonlocalCoupling().
jacobianSetup()
void SystemBase::jacobianSetup () virtual inherited
Reimplemented in AuxiliarySystem, and NonlinearSystemBase.
Definition at line 1512 of file SystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _vars[tid].jacobianSetup();
}
Referenced by SystemBase::jacobianSetup(), AuxiliarySystem::jacobianSetup(), and NonlinearSystemBase::jacobianSetup().
matrixTagActive()
bool SystemBase::matrixTagActive (TagID tag) const virtual inherited
If or not a matrix tag is active.
Definition at line 1117 of file SystemBase.C.
{
  mooseAssert(_subproblem.matrixTagExists(tag), "Matrix tag " << tag << " does not exist");
  return tag < _matrix_tag_active_flags.size() && _matrix_tag_active_flags[tag];
}
mesh() [1/2]
virtual MooseMesh & SystemBase::mesh () inline virtual inherited
Definition at line 96 of file SystemBase.h.
{ return _mesh; }
Referenced by CreateDisplacedProblemAction::addProxyRelationshipManagers(), NonlinearSystemBase::computeScaling(), DMMooseGetEmbedding_Private(), DMSetUp_Moose_Pre(), SolutionIC::initialSetup(), MooseVariableData< OutputType >::MooseVariableData(), ComputeNodalKernelJacobiansThread::onNode(), ComputeNodalKernelsThread::onNode(), and ComputeNodalUserObjectsThread::onNode().
mesh() [2/2]
virtual const MooseMesh & SystemBase::mesh () const inline virtual inherited
Definition at line 97 of file SystemBase.h.
{ return _mesh; }
name()
const std::string & SystemBase::name () const virtual inherited
Definition at line 1297 of file SystemBase.C.
{
  return system().name();
}
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addConstraint(), NonlinearSystemBase::addDamper(), NonlinearSystemBase::addDGKernel(), NonlinearSystemBase::addDiracKernel(), NonlinearSystemBase::addInterfaceKernel(), AuxiliarySystem::addKernel(), MooseEigenSystem::addKernel(), NonlinearSystemBase::addKernel(), SystemBase::addMatrix(), NonlinearSystemBase::addNodalKernel(), AuxiliarySystem::addScalarKernel(), NonlinearSystemBase::addScalarKernel(), NonlinearSystemBase::addSplit(), AuxiliarySystem::addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), AuxiliarySystem::addVariable(), SystemBase::addVariable(), SystemBase::addVector(), NonlinearSystemBase::checkKernelCoverage(), SystemBase::closeTaggedVector(), DisplacedProblem::DisplacedProblem(), SystemBase::getMatrix(), NonlinearSystemBase::getSplit(), SystemBase::getVector(), getVector(), SystemBase::hasVector(), NonlinearEigenSystem::postAddResidualObject(), SystemBase::removeMatrix(), SystemBase::removeVector(), NonlinearSystemBase::setupScalingData(), SystemBase::solutionState(), and SystemBase::zeroTaggedVector().
needSolutionState()
void DisplacedSystem::needSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) inline override virtual
Registers that the solution state state is needed.
Reimplemented from SystemBase.
Definition at line 283 of file DisplacedSystem.h.
{
  _undisplaced_system.needSolutionState(state, iteration_type);
}
nFieldVariables()
unsigned int SystemBase::nFieldVariables () const inherited
Get the number of field variables in this system.
Returns
the number of field variables
Definition at line 849 of file SystemBase.C.
{
  unsigned int n = 0;
  for (auto & var : _vars[0].fieldVariables())
    n += var->count();
  return n;
}
Referenced by SystemBase::nVariables().
nFVVariables()
unsigned int SystemBase::nFVVariables () const inherited
Get the number of finite volume variables in this system.
Returns
the number of finite volume variables
Definition at line 859 of file SystemBase.C.
{
  unsigned int n = 0;
  for (auto & var : _vars[0].fieldVariables())
    if (var->isFV())
      n += var->count();
  return n;
}
Referenced by MooseMesh::cacheFVElementalDoFs().
nonTimeVectorTag()
virtual TagID DisplacedSystem::nonTimeVectorTag () const inline override virtual
Reimplemented from SystemBase.
Definition at line 54 of file DisplacedSystem.h.
{ return _undisplaced_system.nonTimeVectorTag(); }
number()
unsigned int SystemBase::number () const inherited
Gets the number of this system.
Returns
The number of this system
Definition at line 1125 of file SystemBase.C.
{
  return system().number();
}
Referenced by FEProblemBase::addCachedResidualDirectly(), FEProblemBase::addJacobian(), FEProblemBase::addJacobianBlockTags(), FEProblemBase::addJacobianLowerD(), FEProblemBase::addJacobianNeighbor(), FEProblemBase::addJacobianNeighborLowerD(), FEProblemBase::addJacobianOffDiagScalar(), FEProblemBase::addJacobianScalar(), FEProblemBase::addResidual(), FEProblemBase::addResidualLower(), FEProblemBase::addResidualNeighbor(), FEProblemBase::addResidualScalar(), ADKernelTempl< T >::ADKernelTempl(), ArrayKernel::ArrayKernel(), NonlinearSystemBase::assembleScalingVector(), MooseMesh::cacheFaceInfoVariableOwnership(), ComputeResidualAndJacobianThread::compute(), MooseVariableScalar::computeAD(), FEProblemBase::computeBounds(), Assembly::computeFaceMap(), ArrayNodalBC::computeJacobian(), NodalBC::computeJacobian(), VectorNodalBC::computeJacobian(), FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FEProblemBase::computeJacobianBlock(), NonlinearSystemBase::computeJacobianInternal(), FEProblemBase::computeNearNullSpace(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), FEProblemBase::computeNullSpace(), ArrayNodalBC::computeOffDiagJacobian(), NodalBC::computeOffDiagJacobian(), VectorNodalBC::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), ComputeFullJacobianThread::computeOnInterface(), ComputeFullJacobianThread::computeOnInternalFace(), FEProblemBase::computePostCheck(), EqualValueEmbeddedConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), FVFluxBC::computeResidual(), FVInterfaceKernel::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), IntegratedBC::computeResidualAndJacobian(), NodalBC::computeResidualAndJacobian(), Kernel::computeResidualAndJacobian(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Assembly::computeSinglePointMapAD(), FEProblemBase::computeTransposeNullSpace(), DebugResidualAux::computeValue(), NearestNodeValueAux::computeValue(), NonlinearSystemBase::constraintJacobians(), Coupleable::coupled(), FEProblemBase::currentNlSysNum(), PseudoTimestep::currentResidualNorm(), Moose::FV::determineElemOneAndTwo(), ComputeResidualAndJacobianThread::determineObjectWarehouses(), ComputeResidualThread::determineObjectWarehouses(), Moose::doDerivatives(), GreaterThanLessThanPostprocessor::execute(), VariableResidual::execute(), NodalNormalsCorner::execute(), NodalNormalsEvaluator::execute(), NodalNormalsPreprocessor::execute(), NumNonlinearIterations::finalize(), ElementSubdomainModifier::finalize(), BoundsAuxBase::getDoFIndex(), NonlinearSystemBase::getNodeDofs(), SystemBase::getSubdomainsForVar(), NumLinearIterations::getValue(), NumResidualEvaluations::getValue(), Residual::getValue(), Moose::globalDofIndexToDerivative(), FVBoundaryCondition::hasFaceSide(), NonlinearSystemBase::initialSetup(), ActivateElementsUserObjectBase::initSolutions(), EigenExecutionerBase::inversePowerIteration(), Kernel::Kernel(), EigenExecutionerBase::nonlinearSolve(), ComputeDiracThread::onElement(), ComputeNodalKernelBCJacobiansThread::onNode(), ComputeNodalKernelJacobiansThread::onNode(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), FEProblemBase::prepare(), FEProblemBase::prepareAssembly(), SystemBase::prepareFace(), FEProblemBase::prepareFaceShapes(), FEProblemBase::prepareNeighborShapes(), FEProblemBase::prepareShapes(), EqualValueEmbeddedConstraint::reinitConstraint(), FEProblemBase::reinitDirac(), FEProblemBase::reinitNeighborPhys(), FEProblemBase::reinitOffDiagScalars(), FEProblemBase::setResidual(), FEProblemBase::setResidualNeighbor(), PhysicsBasedPreconditioner::setup(), FVInterfaceKernel::setupData(), FEProblemSolve::solve(), ActuallyExplicitEuler::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), ExplicitSSPRungeKutta::solveStage(), UserObject::systemNumber(), MultiAppDofCopyTransfer::transferDofObject(), FVFluxBC::uOnGhost(), FVFluxBC::uOnUSub(), and MortarConstraintBase::zeroInactiveLMDofs().
nVariables()
unsigned int SystemBase::nVariables () const virtual inherited
Get the number of variables in this system.
Returns
the number of variables
Definition at line 840 of file SystemBase.C.
{
  unsigned int n = nFieldVariables();
  n += _vars[0].scalars().size();
  return n;
}
Referenced by AdaptivityAction::act(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), NonlinearSystemBase::getNodeDofs(), Assembly::init(), MaxVarNDofsPerElem::onElement(), MaxVarNDofsPerNode::onNode(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), and SingleMatrixPreconditioner::SingleMatrixPreconditioner().
oldSolutionStateVectorName()
TagName SystemBase::oldSolutionStateVectorName (const unsigned int state, Moose::SolutionIterationType iteration_type) const private inherited
Gets the vector name used for an old (not current) solution state.
Definition at line 1338 of file SystemBase.C.
{
  mooseAssert(state != 0, "Not an old state");
  if (iteration_type == Moose::SolutionIterationType::Time)
  {
    if (state == 1)
      return Moose::OLD_SOLUTION_TAG;
    else if (state == 2)
      return Moose::OLDER_SOLUTION_TAG;
  }
  else if (iteration_type == Moose::SolutionIterationType::Nonlinear && state == 1)
    return Moose::PREVIOUS_NL_SOLUTION_TAG;
  return "solution_state_" + std::to_string(state) + "_" + Moose::stringify(iteration_type);
}
Referenced by SystemBase::needSolutionState(), and SystemBase::solutionState().
operator=()
DisplacedSystem & DisplacedSystem::operator= (DisplacedSystem &&) delete
prepare()
void SystemBase::prepare (THREAD_ID tid) virtual inherited
Prepare the system for use.
Parameters
tid ID of the thread
Definition at line 245 of file SystemBase.C.
{
  if (_subproblem.hasActiveElementalMooseVariables(tid))
  {
    const std::set<MooseVariableFieldBase *> & active_elemental_moose_variables =
        _subproblem.getActiveElementalMooseVariables(tid);
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
      var->clearDofIndices();
    for (const auto & var : active_elemental_moose_variables)
      if (&(var->sys()) == this)
        var->prepare();
  }
  else
  {
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
      var->prepare();
  }
}
Referenced by SubProblem::reinitElemFaceRef().
prepareFace()
void SystemBase::prepareFace (THREAD_ID tid, bool resize_data) virtual inherited
Prepare the system for use on sides.
This will try to reuse the preparation done on the element.
Parameters
tid ID of the thread
resize_data Pass True if this system needs to resize residual and jacobian datastructures based on preparing this face
Definition at line 268 of file SystemBase.C.
{
  // We only need to do something if the element prepare was restricted
  if (_subproblem.hasActiveElementalMooseVariables(tid))
  {
    const std::set<MooseVariableFieldBase *> & active_elemental_moose_variables =
        _subproblem.getActiveElementalMooseVariables(tid);
    std::vector<MooseVariableFieldBase *> newly_prepared_vars;
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
    {
      mooseAssert(&var->sys() == this,
                  "I will cry if we store variables in our warehouse that don't belong to us");
      // If it wasn't in the active list, we need to prepare it. This has the potential to duplicate
      // prepare if we have these conditions:
      //
      // 1. We have a displaced problem
      // 2. We are using AD
      // 3. We are not using global AD indexing
      //
      // But I think I would rather risk duplicate prepare than introduce an additional member set
      // variable for tracking prepared variables. Set insertion is slow and some simulations have a
      // ton of variables
      if (!active_elemental_moose_variables.count(var))
      {
        var->prepare();
        newly_prepared_vars.push_back(var);
      }
    }
    // Make sure to resize the residual and jacobian datastructures for all the new variables
    if (resize_data)
      for (const auto var_ptr : newly_prepared_vars)
      {
        _subproblem.assembly(tid, number()).prepareVariable(var_ptr);
        if (_subproblem.checkNonlocalCouplingRequirement())
          _subproblem.assembly(tid, number()).prepareVariableNonlocal(var_ptr);
      }
  }
}
prepareLowerD()
void SystemBase::prepareLowerD (THREAD_ID tid) virtual inherited
Prepare the system for use for lower dimensional elements.
Parameters
tid ID of the thread
Definition at line 321 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->prepareLowerD();
}
prepareNeighbor()
void SystemBase::prepareNeighbor (THREAD_ID tid) virtual inherited
Prepare the system for use.
Parameters
tid ID of the thread
Definition at line 313 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->prepareNeighbor();
}
Referenced by SubProblem::reinitNeighborFaceRef().
reinitElem()
void SystemBase::reinitElem (const Elem * elem, THREAD_ID tid) virtual inherited
Reinit an element assembly info.
Parameters
elem Which element we are reinitializing for
tid ID of the thread
Reimplemented in AuxiliarySystem.
Definition at line 329 of file SystemBase.C.
{
  if (_subproblem.hasActiveElementalMooseVariables(tid))
  {
    const std::set<MooseVariableFieldBase *> & active_elemental_moose_variables =
        _subproblem.getActiveElementalMooseVariables(tid);
    for (const auto & var : active_elemental_moose_variables)
      if (&(var->sys()) == this)
        var->computeElemValues();
  }
  else
  {
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
      var->computeElemValues();
  }
}
reinitElemFace()
void SystemBase::reinitElemFace (const Elem * elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid) virtual inherited
Reinit assembly info for a side of an element.
Parameters
elem The element
side Side of of the element
bnd_id Boundary id on that side
tid Thread ID
Reimplemented in AuxiliarySystem.
Definition at line 349 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeElemValuesFace();
}
Referenced by SubProblem::reinitElemFaceRef().
reinitLowerD()
void SystemBase::reinitLowerD (THREAD_ID tid) virtual inherited
Compute the values of the variables on the lower dimensional element.
Definition at line 379 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeLowerDValues();
}
reinitNeighbor()
void SystemBase::reinitNeighbor (const Elem * elem, THREAD_ID tid) virtual inherited
Compute the values of the variables at all the current points.
Definition at line 371 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeNeighborValues();
}
reinitNeighborFace()
void SystemBase::reinitNeighborFace (const Elem * elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid) virtual inherited
Compute the values of the variables at all the current points.
Definition at line 360 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeNeighborValuesFace();
}
Referenced by SubProblem::reinitNeighborFaceRef().
reinitNode()
void SystemBase::reinitNode (const Node * node, THREAD_ID tid) virtual inherited
Reinit nodal assembly info.
Parameters
node Node to reinit for
tid Thread ID
Definition at line 387 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNode();
    if (var->isNodalDefined())
      var->computeNodalValues();
  }
}
reinitNodeFace()
void SystemBase::reinitNodeFace (const Node * node, BoundaryID bnd_id, THREAD_ID tid) virtual inherited
Reinit nodal assembly info on a face.
Parameters
node Node to reinit
bnd_id Boundary ID
tid Thread ID
Definition at line 399 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNode();
    if (var->isNodalDefined())
      var->computeNodalValues();
  }
}
reinitNodes()
void SystemBase::reinitNodes (const std::vector< dof_id_type > & nodes, THREAD_ID tid) virtual inherited
Reinit variables at a set of nodes.
Parameters
nodes List of node ids to reinit
tid Thread ID
Definition at line 411 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNodes(nodes);
    var->computeNodalValues();
  }
}
reinitNodesNeighbor()
void SystemBase::reinitNodesNeighbor (const std::vector< dof_id_type > & nodes, THREAD_ID tid) virtual inherited
Reinit variables at a set of neighbor nodes.
Parameters
nodes List of node ids to reinit
tid Thread ID
Definition at line 422 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNodesNeighbor(nodes);
    var->computeNodalNeighborValues();
  }
}
reinitScalars()
void SystemBase::reinitScalars (THREAD_ID tid, bool reinit_for_derivative_reordering = false) virtual inherited
Reinit scalar varaibles.
Parameters
tid Thread ID
reinit_for_derivative_reordering A flag indicating whether we are reinitializing for the purpose of re-ordering derivative information for ADNodalBCs
Definition at line 433 of file SystemBase.C.
{
  const std::vector<MooseVariableScalar *> & vars = _vars[tid].scalars();
  for (const auto & var : vars)
    var->reinit(reinit_for_derivative_reordering);
}
removeMatrix()
void SystemBase::removeMatrix (TagID tag) inherited
Removes a matrix with a given tag.
Parameters
tag_name The name of the tag
Definition at line 579 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag_id))
    mooseError("Cannot remove the matrix with TagID ",
               tag_id,
               "\nin system '",
               name(),
               "', because that tag does not exist in the problem");
  if (hasMatrix(tag_id))
  {
    const auto matrix_name = _subproblem.matrixTagName(tag_id);
    system().remove_matrix(matrix_name);
    _tagged_matrices[tag_id] = nullptr;
  }
}
removeVector() [1/2]
void SystemBase::removeVector (const std::string & name) inherited
Remove a vector from the system with the given name.
Definition at line 1291 of file SystemBase.C.
{
  system().remove_vector(name);
}
Referenced by SystemBase::restoreOldSolutions().
removeVector() [2/2]
void SystemBase::removeVector (TagID tag_id) inherited
Remove a solution length vector from the system with the specified TagID.
Parameters
tag_id Tag ID
Definition at line 690 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag_id))
    mooseError("Cannot remove the vector with TagID ",
               tag_id,
               "\nin system '",
               name(),
               "', because that tag does not exist in the problem");
  if (hasVector(tag_id))
  {
    auto vector_name = _subproblem.vectorTagName(tag_id);
    system().remove_vector(vector_name);
    _tagged_vectors[tag_id] = nullptr;
  }
}
residualCopy()
virtual NumericVector< Number > & DisplacedSystem::residualCopy () inline override virtual
Return the residual copy from the NonlinearSystem.
Returns
Residual copy
Reimplemented from SystemBase.
Definition at line 160 of file DisplacedSystem.h.
  {
    return _undisplaced_system.residualCopy();
  }
residualGhosted()
virtual NumericVector< Number > & DisplacedSystem::residualGhosted () inline override virtual
Reimplemented from SystemBase.
Definition at line 164 of file DisplacedSystem.h.
  {
    return _undisplaced_system.residualGhosted();
  }
residualSetup()
void SystemBase::residualSetup () virtual inherited
Reimplemented in AuxiliarySystem, and NonlinearSystemBase.
Definition at line 1505 of file SystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _vars[tid].residualSetup();
}
Referenced by SystemBase::residualSetup(), AuxiliarySystem::residualSetup(), and NonlinearSystemBase::residualSetup().
residualVectorTag()
virtual TagID DisplacedSystem::residualVectorTag () const inline override virtual
Reimplemented from SystemBase.
Definition at line 45 of file DisplacedSystem.h.
  {
    return _undisplaced_system.residualVectorTag();
  }
restoreOldSolutions()
void SystemBase::restoreOldSolutions () virtual inherited
Restore the old and older solutions when the saved solutions present.
Definition at line 531 of file SystemBase.C.
{
  const auto states =
      _solution_states[static_cast<unsigned short>(Moose::SolutionIterationType::Time)].size();
  if (states > 1)
    for (unsigned int i = 1; i <= states - 1; ++i)
      if (_saved_solution_states[i])
      {
        solutionState(i) = *(_saved_solution_states[i]);
        removeVector("save_solution_state_" + std::to_string(i));
        _saved_solution_states[i] = nullptr;
      }
  if (_saved_dot_old && solutionUDotOld())
  {
    *solutionUDotOld() = *_saved_dot_old;
    removeVector("save_solution_dot_old");
    _saved_dot_old = nullptr;
  }
  if (_saved_dotdot_old && solutionUDotDotOld())
  {
    *solutionUDotDotOld() = *_saved_dotdot_old;
    removeVector("save_solution_dotdot_old");
    _saved_dotdot_old = nullptr;
  }
}
restoreSolutions()
void SystemBase::restoreSolutions () virtual inherited
Restore current solutions (call after your solve failed)
Reimplemented in NonlinearSystemBase.
Definition at line 1274 of file SystemBase.C.
{
  if (!hasSolutionState(1))
    mooseError("Cannot restore solutions without old solution");
  *(const_cast<NumericVector<Number> *&>(currentSolution())) = solutionOld();
  solution() = solutionOld();
  if (solutionUDotOld())
    *solutionUDot() = *solutionUDotOld();
  if (solutionUDotDotOld())
    *solutionUDotDot() = *solutionUDotDotOld();
  if (solutionPreviousNewton())
    *solutionPreviousNewton() = solutionOld();
  system().update();
}
Referenced by NonlinearSystemBase::restoreSolutions().
saveOldSolutions()
void SystemBase::saveOldSolutions () virtual inherited
Save the old and older solutions.
Definition at line 499 of file SystemBase.C.
{
  const auto states =
      _solution_states[static_cast<unsigned short>(Moose::SolutionIterationType::Time)].size();
  if (states > 1)
  {
    _saved_solution_states.resize(states);
    for (unsigned int i = 1; i <= states - 1; ++i)
      if (!_saved_solution_states[i])
        _saved_solution_states[i] =
            &addVector("save_solution_state_" + std::to_string(i), false, PARALLEL);
    for (unsigned int i = 1; i <= states - 1; ++i)
      *(_saved_solution_states[i]) = solutionState(i);
  }
  if (!_saved_dot_old && solutionUDotOld())
    _saved_dot_old = &addVector("save_solution_dot_old", false, PARALLEL);
  if (!_saved_dotdot_old && solutionUDotDotOld())
    _saved_dotdot_old = &addVector("save_solution_dotdot_old", false, PARALLEL);
  if (solutionUDotOld())
    *_saved_dot_old = *solutionUDotOld();
  if (solutionUDotDotOld())
    *_saved_dotdot_old = *solutionUDotDotOld();
}
serializedSolution()
virtual NumericVector< Number > & DisplacedSystem::serializedSolution () inline override virtual
Returns a reference to a serialized version of the solution vector for this subproblem.
Implements SystemBase.
Definition at line 108 of file DisplacedSystem.h.
  {
    return _undisplaced_system.serializedSolution();
  }
setActiveScalarVariableCoupleableVectorTags()
void SystemBase::setActiveScalarVariableCoupleableVectorTags (const std::set< TagID > & vtags, THREAD_ID tid) inherited
Set the active vector tags for the scalar variables.
Definition at line 1532 of file SystemBase.C.
{
  _vars[tid].setActiveScalarVariableCoupleableVectorTags(vtags);
}
Referenced by SubProblem::setActiveScalarVariableCoupleableVectorTags().
setActiveVariableCoupleableVectorTags()
void SystemBase::setActiveVariableCoupleableVectorTags (const std::set< TagID > & vtags, THREAD_ID tid) inherited
Set the active vector tags for the variables.
Definition at line 1526 of file SystemBase.C.
{
  _vars[tid].setActiveVariableCoupleableVectorTags(vtags);
}
Referenced by SubProblem::setActiveFEVariableCoupleableVectorTags().
setVariableGlobalDoFs()
void SystemBase::setVariableGlobalDoFs (const std::string & var_name) inherited
set all the global dof indices for a variable
Parameters
var_name The name of the variable
Definition at line 175 of file SystemBase.C.
{
  AllLocalDofIndicesThread aldit(_subproblem, {var_name});
  ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();
  Threads::parallel_reduce(elem_range, aldit);
  // Gather the dof indices across procs to get all the dof indices for var_name
  aldit.dofIndicesSetUnion();
  const auto & all_dof_indices = aldit.getDofIndices();
  _var_all_dof_indices.assign(all_dof_indices.begin(), all_dof_indices.end());
}
setVerboseFlag()
void SystemBase::setVerboseFlag (const bool & verbose) inline inherited
Sets the verbose flag.
Parameters
[in] verbose Verbose flag
Definition at line 129 of file SystemBase.h.
{ _verbose = verbose; }
Referenced by Executioner::Executioner().
solution() [1/2]
NumericVector< Number > & SystemBase::solution () inline inherited
Definition at line 176 of file SystemBase.h.
{ return solutionState(0); }
Referenced by Adaptivity::adaptMesh(), TransientMultiApp::appTransferVector(), MooseEigenSystem::combineSystemSolution(), NonlinearSystemBase::computeDamping(), AuxiliarySystem::computeElementalVarsHelper(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeMortarNodalVars(), NonlinearSystemBase::computeNodalBCs(), AuxiliarySystem::computeNodalVarsHelper(), NonlinearSystemBase::computeResidualTags(), AuxiliarySystem::computeScalarVars(), SystemBase::copyVars(), GreaterThanLessThanPostprocessor::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), NodalNormalsCorner::execute(), NodalNormalsEvaluator::execute(), NodalNormalsPreprocessor::execute(), NodalNormalsCorner::finalize(), NodalNormalsEvaluator::finalize(), NodalNormalsPreprocessor::finalize(), NodalNormalsCorner::initialize(), NodalNormalsEvaluator::initialize(), NodalNormalsPreprocessor::initialize(), MooseEigenSystem::initSystemSolution(), ComputeIndicatorThread::onElement(), ComputeMarkerThread::onElement(), ComputeUserObjectsThread::onElement(), ComputeNodalUserObjectsThread::onNode(), FEProblemBase::projectInitialConditionOnCustomRange(), FEProblemBase::projectSolution(), Transient::relativeSolutionDifferenceNorm(), SystemBase::restoreSolutions(), PicardSolve::saveVariableValues(), SecantSolve::saveVariableValues(), SteffensenSolve::saveVariableValues(), MooseEigenSystem::scaleSystemSolution(), AuxiliarySystem::serializeSolution(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::setInitialSolution(), solutionInternal(), NonlinearEigenSystem::solve(), MultiAppDofCopyTransfer::transfer(), PicardSolve::transformVariables(), SecantSolve::transformVariables(), SteffensenSolve::transformVariables(), and SystemBase::zeroVariables().
solution() [2/2]
const NumericVector< Number > & SystemBase::solution () const inline inherited
Definition at line 179 of file SystemBase.h.
{ return solutionState(0); }
solutionInternal()
NumericVector< Number > & DisplacedSystem::solutionInternal () const inline override protected virtual
Internal getter for solution owned by libMesh.
Implements SystemBase.
Definition at line 253 of file DisplacedSystem.h.
  {
    return _undisplaced_system.solution();
  }
solutionOld() [1/2]
NumericVector< Number > & SystemBase::solutionOld () inline inherited
Definition at line 177 of file SystemBase.h.
{ return solutionState(1); }
Referenced by MooseEigenSystem::combineSystemSolution(), CentralDifference::computeTimeDerivatives(), ActivateElementsUserObjectBase::initSolutions(), MooseEigenSystem::initSystemSolutionOld(), MooseVariableScalar::reinit(), Transient::relativeSolutionDifferenceNorm(), SystemBase::restoreSolutions(), ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes(), ActuallyExplicitEuler::solve(), and AdamsPredictor::timestepSetup().
solutionOld() [2/2]
const NumericVector< Number > & SystemBase::solutionOld () const inline inherited
Definition at line 180 of file SystemBase.h.
{ return solutionState(1); }
solutionOlder() [1/2]
NumericVector< Number > & SystemBase::solutionOlder () inline inherited
Definition at line 178 of file SystemBase.h.
{ return solutionState(2); }
Referenced by MooseEigenSystem::combineSystemSolution(), CentralDifference::computeTimeDerivatives(), ActivateElementsUserObjectBase::initSolutions(), MooseVariableScalar::reinit(), and ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes().
solutionOlder() [2/2]
const NumericVector< Number > & SystemBase::solutionOlder () const inline inherited
Definition at line 181 of file SystemBase.h.
{ return solutionState(2); }
solutionPreviousNewton() [1/2]
const NumericVector< Number > * DisplacedSystem::solutionPreviousNewton () const inline override virtual
Reimplemented from SystemBase.
Definition at line 119 of file DisplacedSystem.h.
{ return nullptr; }
solutionPreviousNewton() [2/2]
NumericVector< Number > * DisplacedSystem::solutionPreviousNewton () inline override virtual
Reimplemented from SystemBase.
Definition at line 118 of file DisplacedSystem.h.
{ return nullptr; }
solutionState() [1/2]
const NumericVector< Number > & DisplacedSystem::solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) const inline override virtual
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
Reimplemented from SystemBase.
Definition at line 276 of file DisplacedSystem.h.
{
  return _undisplaced_system.solutionState(state, iteration_type);
}
solutionState() [2/2]
NumericVector< Number > & DisplacedSystem::solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) inline override virtual
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
If the state does not exist, it will be initialized in addition to any newer states before it that have not been initialized.
Reimplemented from SystemBase.
Definition at line 269 of file DisplacedSystem.h.
{
  return _undisplaced_system.solutionState(state, iteration_type);
}
solutionStatesInitialized()
bool SystemBase::solutionStatesInitialized () const inline inherited
Whether or not the solution states have been initialized via initSolutionState()
After the solution states have been initialized, additional solution states cannot be added.
Definition at line 888 of file SystemBase.h.
{ return _solution_states_initialized; }
Referenced by AuxScalarKernel::uOld(), and ScalarKernelBase::uOld().
solutionUDot() [1/2]
const NumericVector< Number > * DisplacedSystem::solutionUDot () const inline override virtual
Implements SystemBase.
Definition at line 134 of file DisplacedSystem.h.
  {
    return _undisplaced_system.solutionUDot();
  }
solutionUDot() [2/2]
NumericVector< Number > * DisplacedSystem::solutionUDot () inline override virtual
Implements SystemBase.
Definition at line 121 of file DisplacedSystem.h.
{ return _undisplaced_system.solutionUDot(); }
solutionUDotDot() [1/2]
const NumericVector< Number > * DisplacedSystem::solutionUDotDot () const inline override virtual
Implements SystemBase.
Definition at line 138 of file DisplacedSystem.h.
  {
    return _undisplaced_system.solutionUDotDot();
  }
solutionUDotDot() [2/2]
NumericVector< Number > * DisplacedSystem::solutionUDotDot () inline override virtual
Implements SystemBase.
Definition at line 122 of file DisplacedSystem.h.
  {
    return _undisplaced_system.solutionUDotDot();
  }
solutionUDotDotOld() [1/2]
const NumericVector< Number > * DisplacedSystem::solutionUDotDotOld () const inline override virtual
Implements SystemBase.
Definition at line 146 of file DisplacedSystem.h.
  {
    return _undisplaced_system.solutionUDotDotOld();
  }
solutionUDotDotOld() [2/2]
NumericVector< Number > * DisplacedSystem::solutionUDotDotOld () inline override virtual
Implements SystemBase.
Definition at line 130 of file DisplacedSystem.h.
  {
    return _undisplaced_system.solutionUDotDotOld();
  }
solutionUDotOld() [1/2]
const NumericVector< Number > * DisplacedSystem::solutionUDotOld () const inline override virtual
Implements SystemBase.
Definition at line 142 of file DisplacedSystem.h.
  {
    return _undisplaced_system.solutionUDotOld();
  }
solutionUDotOld() [2/2]
NumericVector< Number > * DisplacedSystem::solutionUDotOld () inline override virtual
Implements SystemBase.
Definition at line 126 of file DisplacedSystem.h.
  {
    return _undisplaced_system.solutionUDotOld();
  }
solve()
void SystemBase::solve () virtual inherited
Solve the system (using libMesh magic)
Reimplemented in DumpObjectsNonlinearSystem, NonlinearEigenSystem, NonlinearSystem, and NonlinearSystemBase.
Definition at line 1218 of file SystemBase.C.
{
  system().solve();
}
subdomainSetup()
void SystemBase::subdomainSetup () virtual inherited
Reimplemented in NonlinearSystemBase, and AuxiliarySystem.
Definition at line 1498 of file SystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _vars[tid].subdomainSetup();
}
Referenced by SystemBase::subdomainSetup(), AuxiliarySystem::subdomainSetup(), and NonlinearSystemBase::subdomainSetup().
subproblem() [1/2]
virtual SubProblem & SystemBase::subproblem () inline virtual inherited
Definition at line 98 of file SystemBase.h.
{ return _subproblem; }
Referenced by CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseVariableBase::allDofIndices(), NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), Moose::globalDofIndexToDerivative(), NonlinearSystemBase::initialSetup(), MooseVariableScalar::MooseVariableScalar(), MooseVariableScalar::reinit(), and NonlinearSystemBase::setConstraintSecondaryValues().
subproblem() [2/2]
virtual const SubProblem & SystemBase::subproblem () const inline virtual inherited
Definition at line 99 of file SystemBase.h.
{ return _subproblem; }
sys()
virtual TransientExplicitSystem & DisplacedSystem::sys () inline virtual
Definition at line 244 of file DisplacedSystem.h.
{ return _sys; }
system() [1/2]
const System & DisplacedSystem::system () const override virtual
Implements SystemBase.
Definition at line 67 of file DisplacedSystem.C.
{
  return _sys;
}
system() [2/2]
System & DisplacedSystem::system () override virtual
Get the reference to the libMesh system.
Implements SystemBase.
Definition at line 61 of file DisplacedSystem.C.
{
  return _sys;
}
systemMatrixTag()
virtual TagID DisplacedSystem::systemMatrixTag () const inline override virtual
Return the Matrix Tag ID for System.
Reimplemented from SystemBase.
Definition at line 50 of file DisplacedSystem.h.
{ return _undisplaced_system.systemMatrixTag(); }
timestepSetup()
void SystemBase::timestepSetup () virtual inherited
Reimplemented in AuxiliarySystem, and NonlinearSystemBase.
Definition at line 1484 of file SystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _vars[tid].timestepSetup();
}
Referenced by SystemBase::timestepSetup(), AuxiliarySystem::timestepSetup(), and NonlinearSystemBase::timestepSetup().
timeVectorTag()
virtual TagID DisplacedSystem::timeVectorTag () const inline override virtual
Ideally, we should not need this API.
There exists a really bad API "addCachedResidualDirectly " in FEProblem and DisplacedProblem This API should go away once addCachedResidualDirectly is removed in the future Return Tag ID for Time
Reimplemented from SystemBase.
Definition at line 52 of file DisplacedSystem.h.
{ return _undisplaced_system.timeVectorTag(); }
update()
void SystemBase::update (bool update_libmesh_system = true) virtual inherited
Update the system (doing libMesh magic)
Definition at line 1211 of file SystemBase.C.
{
  if (update_libmesh_system)
    system().update();
}
Referenced by Adaptivity::adaptMesh(), MooseEigenSystem::combineSystemSolution(), NonlinearSystemBase::computeDamping(), NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualTags(), EigenProblem::doFreeNonlinearPowerIterations(), PointwiseRenormalizeVector::finalize(), MooseEigenSystem::initSystemSolution(), MooseEigenSystem::initSystemSolutionOld(), MooseEigenSystem::scaleSystemSolution(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::setInitialSolution(), FEProblemBase::solve(), EigenProblem::solve(), DisplacedProblem::syncSolutions(), MultiAppDofCopyTransfer::transfer(), PicardSolve::transformVariables(), SecantSolve::transformVariables(), and SteffensenSolve::transformVariables().
varKind()
Moose::VarKindType SystemBase::varKind () const inline inherited
Returns
the type of variables this system holds, e.g. nonlinear or auxiliary
Definition at line 916 of file SystemBase.h.
{ return _var_kind; }
Referenced by Coupleable::coupled(), and UserObject::UserObject().
zeroTaggedVector()
void SystemBase::zeroTaggedVector (const TagID tag) inherited
Zero vector with the given tag.
Definition at line 664 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot zero vector with TagID ",
               tag,
               " in system '",
               name(),
               "' because that tag does not exist in the problem");
  else if (!hasVector(tag))
    mooseError("Cannot zero vector tag with name '",
               _subproblem.vectorTagName(tag),
               "' in system '",
               name(),
               "' because there is no vector associated with that tag");
  getVector(tag).zero();
}
Referenced by SystemBase::zeroTaggedVectors().
zeroTaggedVectors()
void SystemBase::zeroTaggedVectors (const std::set< TagID > & tags) inherited
Zero all vectors for given tags.
Definition at line 683 of file SystemBase.C.
{
  for (const auto tag : tags)
    zeroTaggedVector(tag);
}
Referenced by NonlinearSystemBase::computeResidualAndJacobianTags(), and NonlinearSystemBase::computeResidualTags().
zeroVariables()
virtual void DisplacedSystem::zeroVariables (std::vector< std::string > & vars_to_be_zeroed) inline override virtual
Zero out the solution for the list of variables passed in.
Reimplemented from SystemBase.
Definition at line 205 of file DisplacedSystem.h.
  {
    _undisplaced_system.zeroVariables(vars_to_be_zeroed);
  }
zeroVariablesForJacobian()
void SystemBase::zeroVariablesForJacobian () virtual inherited
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on Jacobian evaluation by a call to addVariableToZeroOnResidual()
Definition at line 224 of file SystemBase.C.
{
  zeroVariables(_vars_to_be_zeroed_on_jacobian);
}
zeroVariablesForResidual()
void SystemBase::zeroVariablesForResidual () virtual inherited
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on residual evaluation by a call to addVariableToZeroOnResidual()
Definition at line 218 of file SystemBase.C.
{
  zeroVariables(_vars_to_be_zeroed_on_residual);
}
Member Data Documentation
_app
MooseApp& SystemBase::_app protected inherited
Definition at line 926 of file SystemBase.h.
Referenced by NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeJacobianTags(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), and NonlinearSystem::solve().
_automatic_scaling
bool SystemBase::_automatic_scaling protected inherited
Whether to automatically scale the variables.
Definition at line 979 of file SystemBase.h.
Referenced by SystemBase::automaticScaling(), NonlinearSystem::init(), NonlinearSystemBase::initialSetup(), NonlinearEigenSystem::solve(), and NonlinearSystem::solve().
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_du_dot_du
Real SystemBase::_du_dot_du protected inherited
Definition at line 943 of file SystemBase.h.
Referenced by SystemBase::duDotDu().
_du_dotdot_du
Real SystemBase::_du_dotdot_du protected inherited
Definition at line 944 of file SystemBase.h.
Referenced by SystemBase::duDotDotDu().
_factory
Factory& SystemBase::_factory protected inherited
Definition at line 927 of file SystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addConstraint(), NonlinearSystemBase::addDamper(), NonlinearSystemBase::addDGKernel(), NonlinearSystemBase::addDiracKernel(), NonlinearSystemBase::addInterfaceKernel(), AuxiliarySystem::addKernel(), MooseEigenSystem::addKernel(), NonlinearSystemBase::addKernel(), NonlinearSystemBase::addNodalKernel(), AuxiliarySystem::addScalarKernel(), NonlinearSystemBase::addScalarKernel(), NonlinearSystemBase::addSplit(), AuxiliarySystem::addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), and SystemBase::addVariable().
_matrix_tag_active_flags
std::vector<bool> SystemBase::_matrix_tag_active_flags protected inherited
Active flags for tagged matrices.
Definition at line 951 of file SystemBase.h.
Referenced by SystemBase::activeAllMatrixTags(), SystemBase::activeMatrixTag(), SystemBase::deactiveAllMatrixTags(), SystemBase::deactiveMatrixTag(), and SystemBase::matrixTagActive().
_max_var_n_dofs_per_elem
size_t SystemBase::_max_var_n_dofs_per_elem protected inherited
Maximum number of dofs for any one variable on any one element.
Definition at line 967 of file SystemBase.h.
Referenced by SystemBase::assignMaxVarNDofsPerElem(), and SystemBase::getMaxVarNDofsPerElem().
_max_var_n_dofs_per_node
size_t SystemBase::_max_var_n_dofs_per_node protected inherited
Maximum number of dofs for any one variable on any one node.
Definition at line 970 of file SystemBase.h.
Referenced by SystemBase::assignMaxVarNDofsPerNode(), and SystemBase::getMaxVarNDofsPerNode().
_max_var_number
unsigned int SystemBase::_max_var_number protected inherited
Maximum variable number.
Definition at line 938 of file SystemBase.h.
Referenced by SystemBase::addVariable(), and SystemBase::getMaxVariableNumber().
_mesh
MooseMesh& SystemBase::_mesh protected inherited
Definition at line 929 of file SystemBase.h.
Referenced by SystemBase::addVariable(), NonlinearSystemBase::assembleScalingVector(), SystemBase::augmentSendList(), NonlinearSystemBase::checkKernelCoverage(), NonlinearSystemBase::computeDamping(), AuxiliarySystem::computeElementalVarsHelper(), NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeMortarNodalVars(), NonlinearSystemBase::computeNodalBCs(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), AuxiliarySystem::computeNodalVarsHelper(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), NonlinearSystemBase::findImplicitGeometricCouplingEntries(), NonlinearSystemBase::getNodeDofs(), SystemBase::mesh(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::setInitialSolution(), SystemBase::setVariableGlobalDoFs(), and SystemBase::zeroVariables().
_name
std::string SystemBase::_name protected inherited
The name of this system.
Definition at line 931 of file SystemBase.h.
_numbered_vars
std::vector<std::vector<MooseVariableFieldBase *> > SystemBase::_numbered_vars protected inherited
Map variable number to its pointer.
Definition at line 976 of file SystemBase.h.
Referenced by SystemBase::addVariable(), and SystemBase::getVariable().
_saved_dot_old
NumericVector<Real>* SystemBase::_saved_dot_old protected inherited
Definition at line 958 of file SystemBase.h.
Referenced by SystemBase::restoreOldSolutions(), and SystemBase::saveOldSolutions().
_saved_dotdot_old
NumericVector<Real>* SystemBase::_saved_dotdot_old protected inherited
Definition at line 959 of file SystemBase.h.
Referenced by SystemBase::restoreOldSolutions(), and SystemBase::saveOldSolutions().
_saved_old
NumericVector<Real>* SystemBase::_saved_old protected inherited
Definition at line 954 of file SystemBase.h.
_saved_older
NumericVector<Real>* SystemBase::_saved_older protected inherited
Definition at line 955 of file SystemBase.h.
_saved_solution_states
std::vector<NumericVector<Number> *> SystemBase::_saved_solution_states private inherited
The saved solution states (0 = current, 1 = old, 2 = older, etc)
Definition at line 1000 of file SystemBase.h.
Referenced by SystemBase::restoreOldSolutions(), and SystemBase::saveOldSolutions().
_solution_states
std::array<std::vector<NumericVector<Number> *>, 2> SystemBase::_solution_states private inherited
The solution states (0 = current, 1 = old, 2 = older, etc)
Definition at line 998 of file SystemBase.h.
Referenced by SystemBase::copyOldSolutions(), SystemBase::copySolutionsBackwards(), SystemBase::hasSolutionState(), SystemBase::needSolutionState(), SystemBase::restoreOldSolutions(), SystemBase::saveOldSolutions(), and SystemBase::solutionState().
_solution_states_initialized
bool SystemBase::_solution_states_initialized protected inherited
Whether or not the solution states have been initialized.
Definition at line 985 of file SystemBase.h.
Referenced by SystemBase::initSolutionState(), and SystemBase::solutionStatesInitialized().
_subproblem
SubProblem& SystemBase::_subproblem protected inherited
Definition at line 924 of file SystemBase.h.
Referenced by SystemBase::activeAllMatrixTags(), SystemBase::activeMatrixTag(), SystemBase::addMatrix(), SystemBase::addScalingVector(), SystemBase::addVariable(), SystemBase::addVector(), SystemBase::associateMatrixToTag(), SystemBase::associateVectorToTag(), SystemBase::augmentSendList(), SystemBase::closeTaggedVector(), SystemBase::computingScalingJacobian(), SystemBase::copyVars(), SystemBase::deactiveAllMatrixTags(), SystemBase::deactiveMatrixTag(), SystemBase::disassociateDefaultMatrixTags(), SystemBase::disassociateDefaultVectorTags(), SystemBase::disassociateMatrixFromTag(), SystemBase::disassociateVectorFromTag(), SystemBase::getMatrix(), NonlinearSystemBase::getResidualNonTimeVector(), NonlinearSystemBase::getResidualTimeVector(), SystemBase::getVector(), SystemBase::matrixTagActive(), SystemBase::needSolutionState(), SystemBase::prepare(), SystemBase::prepareFace(), SystemBase::reinitElem(), SystemBase::removeMatrix(), SystemBase::removeVector(), NonlinearSystemBase::residualGhosted(), NonlinearSystemBase::setSolution(), SystemBase::setVariableGlobalDoFs(), SystemBase::subproblem(), SystemBase::zeroTaggedVector(), and SystemBase::zeroVariables().
_sys
TransientExplicitSystem& DisplacedSystem::_sys protected
Definition at line 259 of file DisplacedSystem.h.
Referenced by DisplacedSystem(), getVector(), sys(), and system().
_tagged_matrices
std::vector<SparseMatrix<Number> *> SystemBase::_tagged_matrices protected inherited
Tagged matrices (pointer)
Definition at line 949 of file SystemBase.h.
Referenced by SystemBase::associateMatrixToTag(), SystemBase::disassociateMatrixFromTag(), SystemBase::getMatrix(), SystemBase::hasMatrix(), and SystemBase::removeMatrix().
_tagged_vectors
std::vector<NumericVector<Number> *> SystemBase::_tagged_vectors protected inherited
Tagged vectors (pointer)
Definition at line 947 of file SystemBase.h.
Referenced by SystemBase::associateVectorToTag(), SystemBase::disassociateVectorFromTag(), SystemBase::getVector(), SystemBase::hasVector(), and SystemBase::removeVector().
_time_integrator
std::shared_ptr<TimeIntegrator> SystemBase::_time_integrator protected inherited
Time integrator.
Definition at line 973 of file SystemBase.h.
Referenced by AuxiliarySystem::addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), addTimeIntegrator(), AuxiliarySystem::compute(), NonlinearSystemBase::computeResidualAndJacobianTags(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::computeTimeDerivatives(), SystemBase::getSharedTimeIntegrator(), SystemBase::getTimeIntegrator(), NonlinearSystemBase::onTimestepBegin(), NonlinearEigenSystem::solve(), and NonlinearSystem::solve().
_undisplaced_system
SystemBase& DisplacedSystem::_undisplaced_system protected
Definition at line 258 of file DisplacedSystem.h.
Referenced by addVariableToZeroOnJacobian(), addVariableToZeroOnResidual(), associateMatrixToTag(), associateVectorToTag(), augmentSendList(), currentSolution(), defaultMatrixTags(), defaultVectorTags(), disassociateDefaultMatrixTags(), disassociateDefaultVectorTags(), disassociateMatrixFromTag(), disassociateVectorFromTag(), duDotDotDu(), duDotDu(), getMatrix(), getVector(), hasMatrix(), hasSolutionState(), hasVector(), initSolutionState(), needSolutionState(), nonTimeVectorTag(), residualCopy(), residualGhosted(), residualVectorTag(), serializedSolution(), solutionInternal(), solutionState(), solutionUDot(), solutionUDotDot(), solutionUDotDotOld(), solutionUDotOld(), systemMatrixTag(), timeVectorTag(), and zeroVariables().
_var_all_dof_indices
std::vector<dof_id_type> SystemBase::_var_all_dof_indices protected inherited
Container for the dof indices of a given variable.
Definition at line 988 of file SystemBase.h.
Referenced by SystemBase::getVariableGlobalDoFs(), and SystemBase::setVariableGlobalDoFs().
_var_kind
Moose::VarKindType SystemBase::_var_kind protected inherited
default kind of variables in this system
Definition at line 962 of file SystemBase.h.
Referenced by SystemBase::varKind().
_var_map
std::map<unsigned int, std::set<SubdomainID> > SystemBase::_var_map protected inherited
Map of variables (variable id -> array of subdomains where it lives)
Definition at line 936 of file SystemBase.h.
Referenced by SystemBase::addVariable(), SystemBase::getSubdomainsForVar(), and SystemBase::getVariableBlocks().
_var_to_copy
std::vector<VarCopyInfo> SystemBase::_var_to_copy protected inherited
Definition at line 964 of file SystemBase.h.
Referenced by SystemBase::addVariableToCopy(), SystemBase::copyVars(), and SystemBase::hasVarCopy().
_vars
std::vector<VariableWarehouse> SystemBase::_vars protected inherited
Variable warehouses (one for each thread)
Definition at line 934 of file SystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addInterfaceKernel(), AuxiliarySystem::addVariable(), SystemBase::addVariable(), SystemBase::applyScalingFactors(), NonlinearSystemBase::assembleScalingVector(), SystemBase::clearAllDofIndices(), AuxiliarySystem::compute(), SystemBase::customSetup(), SystemBase::getActualFieldVariable(), SystemBase::getFieldVariable(), SystemBase::getFVVariable(), SystemBase::getMinQuadratureOrder(), AuxiliarySystem::getMinQuadratureOrder(), SystemBase::getScalarVariable(), SystemBase::getScalarVariables(), SystemBase::getVariable(), SystemBase::getVariableNames(), SystemBase::getVariables(), SystemBase::initialSetup(), SystemBase::jacobianSetup(), SystemBase::nFieldVariables(), SystemBase::nFVVariables(), SystemBase::nVariables(), SystemBase::prepare(), SystemBase::prepareFace(), SystemBase::prepareLowerD(), SystemBase::prepareNeighbor(), SystemBase::reinitElem(), SystemBase::reinitElemFace(), SystemBase::reinitLowerD(), SystemBase::reinitNeighbor(), SystemBase::reinitNeighborFace(), SystemBase::reinitNode(), SystemBase::reinitNodeFace(), SystemBase::reinitNodes(), SystemBase::reinitNodesNeighbor(), SystemBase::reinitScalars(), SystemBase::residualSetup(), SystemBase::setActiveScalarVariableCoupleableVectorTags(), SystemBase::setActiveVariableCoupleableVectorTags(), NonlinearSystemBase::setupScalingData(), SystemBase::subdomainSetup(), and SystemBase::timestepSetup().
_vars_to_be_zeroed_on_jacobian
std::vector<std::string> SystemBase::_vars_to_be_zeroed_on_jacobian protected inherited
Definition at line 941 of file SystemBase.h.
Referenced by SystemBase::addVariableToZeroOnJacobian(), and SystemBase::zeroVariablesForJacobian().
_vars_to_be_zeroed_on_residual
std::vector<std::string> SystemBase::_vars_to_be_zeroed_on_residual protected inherited
Definition at line 940 of file SystemBase.h.
Referenced by SystemBase::addVariableToZeroOnResidual(), and SystemBase::zeroVariablesForResidual().
_verbose
bool SystemBase::_verbose protected inherited
True if printing out additional information.
Definition at line 982 of file SystemBase.h.
Referenced by SystemBase::applyScalingFactors(), and SystemBase::setVerboseFlag().
The documentation for this class was generated from the following files:
moose/framework/include/systems/DisplacedSystem.h
moose/framework/src/systems/DisplacedSystem.C