Zapdos: ReporterInterface Class Reference
ReporterInterface Class Reference
Interface to allow object to consume Reporter values.
#include <ReporterInterface.h>
Public Member Functions
ReporterInterface (const MooseObject *moose_object)
Static Public Member Functions
static InputParameters validParams ()
Protected Member Functions
const ReporterName & getReporterName (const std::string &param_name) const
virtual void addReporterDependencyHelper (const ReporterName &)
A method that can be overridden to update the UO dependencies.
template<typename T >
const T & getReporterValue (const std::string &param_name, const std::size_t time_index=0)
doco-normal-methods-begin Returns read-only reference to a Reporter value that is provided by an input parameter.
template<typename T >
const T & getReporterValue (const std::string &param_name, ReporterMode mode, const std::size_t time_index=0)
template<typename T >
const T & getReporterValueByName (const ReporterName &reporter_name, const std::size_t time_index=0)
Returns read-only reference to a Reporter value that is provided by name directly.
template<typename T >
const T & getReporterValueByName (const ReporterName &reporter_name, ReporterMode mode, const std::size_t time_index=0)
bool hasReporterValue (const std::string &param_name) const
Return True if the Reporter value exists.
bool hasReporterValueByName (const ReporterName &reporter_name) const
template<typename T >
bool hasReporterValue (const std::string &param_name) const
template<typename T >
bool hasReporterValueByName (const ReporterName &reporter_name) const
Private Member Functions
bool reportersAdded () const
template<typename T >
void possiblyCheckHasReporter (const ReporterName &reporter_name, const std::string &param_name="") const
Helpers for "possibly" checking if a Reporter value exists.
Private Attributes
const InputParameters & _ri_params
Parameters for the MooseObject inherting from this interface.
FEProblemBase & _ri_fe_problem_base
Provides access to FEProblemBase::getReporterData.
const ReporterData & _ri_reporter_data
The ReporterData.
const MooseObject & _ri_moose_object
The MooseObject needing this interface.
Detailed Description
Interface to allow object to consume Reporter values.
Definition at line 22 of file ReporterInterface.h.
Constructor & Destructor Documentation
ReporterInterface()
ReporterInterface::ReporterInterface (const MooseObject * moose_object)
Definition at line 20 of file ReporterInterface.C.
  : _ri_params(moose_object->parameters()),
    _ri_fe_problem_base(*_ri_params.getCheckedPointerParam<FEProblemBase *>("_fe_problem_base")),
    _ri_reporter_data(_ri_fe_problem_base.getReporterData()),
    _ri_moose_object(*moose_object)
{
}
Member Function Documentation
addReporterDependencyHelper()
virtual void ReporterInterface::addReporterDependencyHelper (const ReporterName &) inline protected virtual
A method that can be overridden to update the UO dependencies.
This is needed because the get methods for this interface cannot be virtual because of the template parameter. See GeneralUserObject for how it is utilized.
Reimplemented in UserObject.
Definition at line 97 of file ReporterInterface.h.
{}
Referenced by getReporterValueByName().
getReporterName()
const ReporterName & ReporterInterface::getReporterName (const std::string & param_name) const protected
Returns
The ReporterName associated with the parametre param_name.
Performs error checking to mak sure that the parameter is valid.
Definition at line 49 of file ReporterInterface.C.
{
  if (!_ri_params.isParamValid(param_name))
    _ri_moose_object.mooseError(
        "When getting a Reporter, failed to get a parameter with the name \"",
        param_name,
        "\".",
        "\n\nKnown parameters:\n",
        _ri_moose_object.parameters());
  if (_ri_params.isType<ReporterName>(param_name))
    return _ri_params.get<ReporterName>(param_name);
  _ri_moose_object.mooseError("Supplied parameter with name \"",
                              param_name,
                              "\" of type \"",
                              _ri_params.type(param_name),
                              "\" is not an expected type for getting a Reporter.\n\n",
                              "The expected type is \"ReporterName\".");
}
Referenced by getReporterValue(), and hasReporterValue().
getReporterValue() [1/2]
template<typename T > const T & ReporterInterface::getReporterValue (const std::string & param_name, const std::size_t time_index = 0) protected
doco-normal-methods-begin Returns read-only reference to a Reporter value that is provided by an input parameter.
Template Parameters
T The C++ type of the Reporter value being consumed
Parameters
param_name The name of the parameter that gives the name of the Reporter, which must be a ReporterName parameter (i.e., getParam<ReporterName>(param_name)).
mode The mode that the object will consume the Reporter value @pararm time_index (optional) If zero is provided the current value is returned. Use a positive index to return previous values (1 = older, 2 = older, etc.). The maximum number of old values is dictated by the ReporterData object.
Definition at line 133 of file ReporterInterface.h.
{
  return getReporterValue<T>(param_name, REPORTER_MODE_UNSET, time_index);
}
getReporterValue() [2/2]
template<typename T > const T & ReporterInterface::getReporterValue (const std::string & param_name, ReporterMode mode, const std::size_t time_index = 0) protected
Definition at line 140 of file ReporterInterface.h.
{
  const auto & reporter_name = getReporterName(param_name);
  possiblyCheckHasReporter<T>(reporter_name, param_name);
  return getReporterValueByName<T>(reporter_name, mode, time_index);
}
getReporterValueByName() [1/2]
template<typename T > const T & ReporterInterface::getReporterValueByName (const ReporterName & reporter_name, const std::size_t time_index = 0) protected
Returns read-only reference to a Reporter value that is provided by name directly.
Template Parameters
T The C++ type of the Reporter value being consumed
Parameters
reporter_name A ReporterName object that for the desired Reporter value.
mode The mode that the object will consume the Reporter value @pararm time_index (optional) If zero is provided the current value is returned. Use a positive index to return previous values (1 = older, 2 = older, etc.). The maximum number of old values is dictated by the ReporterData object.
Definition at line 153 of file ReporterInterface.h.
{
  return getReporterValueByName<T>(reporter_name, REPORTER_MODE_UNSET, time_index);
}
getReporterValueByName() [2/2]
template<typename T > const T & ReporterInterface::getReporterValueByName (const ReporterName & reporter_name, ReporterMode mode, const std::size_t time_index = 0) protected
Definition at line 161 of file ReporterInterface.h.
{
  possiblyCheckHasReporter<T>(reporter_name);
  addReporterDependencyHelper(reporter_name);
  return _ri_reporter_data.getReporterValue<T>(reporter_name, _ri_moose_object, mode, time_index);
}
hasReporterValue() [1/2]
bool ReporterInterface::hasReporterValue (const std::string & param_name) const protected
Return True if the Reporter value exists.
Template Parameters
T The C++ type of the Reporter value being consumed
Parameters
reporter_name A ReporterName object that for the desired Reporter value.
Definition at line 29 of file ReporterInterface.C.
{
  if (!reportersAdded())
    _ri_moose_object.mooseError(
        "Cannot call hasReporterValue() until all Reporters have been constructed.");
  return hasReporterValueByName(getReporterName(param_name));
}
hasReporterValue() [2/2]
template<typename T > bool ReporterInterface::hasReporterValue (const std::string & param_name) const protected
Definition at line 174 of file ReporterInterface.h.
{
  if (!reportersAdded())
    _ri_moose_object.mooseError(
        "Cannot call hasReporterValue() until all Reporters have been constructed.");
  return hasReporterValueByName<T>(getReporterName(param_name));
}
hasReporterValueByName() [1/2]
bool ReporterInterface::hasReporterValueByName (const ReporterName & reporter_name) const protected
Definition at line 39 of file ReporterInterface.C.
{
  if (!reportersAdded())
    _ri_moose_object.mooseError(
        "Cannot call hasReporterValueByName() until all Reporters have been constructed.");
  return _ri_reporter_data.hasReporterValue(reporter_name);
}
Referenced by hasReporterValue(), and AdvancedOutput::initShowHideLists().
hasReporterValueByName() [2/2]
template<typename T > bool ReporterInterface::hasReporterValueByName (const ReporterName & reporter_name) const protected
Definition at line 185 of file ReporterInterface.h.
{
  if (!reportersAdded())
    _ri_moose_object.mooseError(
        "Cannot call hasReporterValueByName() until all Reporters have been constructed.");
  return _ri_reporter_data.hasReporterValue<T>(reporter_name);
}
possiblyCheckHasReporter()
template<typename T > void ReporterInterface::possiblyCheckHasReporter (const ReporterName & reporter_name, const std::string & param_name = "") const private
Helpers for "possibly" checking if a Reporter value exists.
This is only able to check for existance after all Reporters have been added (after the task creating them has been called). If called before said task, this will do nothing, hence the "possibly". This allows us to have errors reported directly by the object requesting the Reporter instead of through a system with less context.
Definition at line 196 of file ReporterInterface.h.
{
  if (reportersAdded() && !hasReporterValueByName<T>(reporter_name))
  {
    std::stringstream oss;
    oss << "A Reporter value with the name \"" << reporter_name << "\" and type \""
        << MooseUtils::prettyCppType<T>() << "\" was not found.";
    if (_ri_params.isParamValid(param_name))
      _ri_moose_object.paramError(param_name, oss.str());
    else
      _ri_moose_object.mooseError(oss.str());
  }
}
reportersAdded()
bool ReporterInterface::reportersAdded () const private
Returns
True if all Reporters have been added (the task associated with adding them is complete)
Definition at line 71 of file ReporterInterface.C.
{
  return _ri_fe_problem_base.getMooseApp().actionWarehouse().isTaskComplete("add_reporter");
}
Referenced by hasReporterValue(), hasReporterValueByName(), and possiblyCheckHasReporter().
validParams()
InputParameters ReporterInterface::validParams () static
Definition at line 15 of file ReporterInterface.C.
{
  return emptyInputParameters();
}
Referenced by Executioner::validParams(), and UserObject::validParams().
Member Data Documentation
_ri_fe_problem_base
FEProblemBase& ReporterInterface::_ri_fe_problem_base private
Provides access to FEProblemBase::getReporterData.
Definition at line 122 of file ReporterInterface.h.
Referenced by reportersAdded().
_ri_moose_object
const MooseObject& ReporterInterface::_ri_moose_object private
The MooseObject needing this interface.
Definition at line 128 of file ReporterInterface.h.
Referenced by getReporterName(), getReporterValueByName(), hasReporterValue(), hasReporterValueByName(), and possiblyCheckHasReporter().
_ri_params
const InputParameters& ReporterInterface::_ri_params private
Parameters for the MooseObject inherting from this interface.
Definition at line 119 of file ReporterInterface.h.
Referenced by getReporterName(), and possiblyCheckHasReporter().
_ri_reporter_data
const ReporterData& ReporterInterface::_ri_reporter_data private
The ReporterData.
Definition at line 125 of file ReporterInterface.h.
Referenced by getReporterValueByName(), and hasReporterValueByName().
The documentation for this class was generated from the following files:
moose/framework/include/reporters/ReporterInterface.h
moose/framework/src/reporters/ReporterInterface.C