Zapdos: MooseArray< T > Class Template Reference
MooseArray< T > Class Template Reference
forward declarations
#include <MooseArray.h>
Public Types
typedef T value_type
Public Member Functions
MooseArray ()
Default constructor.
MooseArray (const unsigned int size)
MooseArray (const unsigned int size, const T &default_value)
MooseArray (const MooseArray &rhs)
~MooseArray ()=default
void setAllValues (const T &value)
Sets all values of the array to the passed in value.
void release ()
Manually deallocates the data pointer.
void clear ()
Change the number of elements the array can store to zero.
template<bool value_initialize = false>
void resize (unsigned int size)
Change the number of elements the array can store.
void resize (unsigned int size, const T &default_value)
Change the number of elements the array can store.
unsigned int size () const
The number of elements that can currently be stored in the array.
T & operator[] (const unsigned int i)
Get element i out of the array.
const T & operator[] (const unsigned int i) const
Get element i out of the array.
void swap (MooseArray &rhs)
Swap memory in this object with the 'rhs' object.
void shallowCopy (const MooseArray &rhs)
Doesn't actually make a copy of the data.
void shallowCopy (std::vector< T > &rhs)
Doesn't actually make a copy of the data.
MooseArray< T > & operator= (const std::vector< T > &rhs)
Actual operator=... really does make a copy of the data.
MooseArray< T > & operator= (const MooseArray< T > &rhs)
Actual operator=... really does make a copy of the data.
std::vector< T > stdVector () const
Extremely inefficient way to produce a std::vector from a MooseArray!
const T * data () const
Reference to first element of array.
Private Attributes
std::unique_ptr< T[]> _data_ptr
Smart pointer storage.
T * _data
unsigned int _size
The current number of elements the array can hold.
unsigned int _allocated_size
Number of allocated memory positions for storage.
Detailed Description
template<typename T>
class MooseArray< T >
forward declarations
Definition at line 17 of file MooseArray.h.
Member Typedef Documentation
value_type
template<typename T > typedef T MooseArray< T >::value_type
Definition at line 20 of file MooseArray.h.
Constructor & Destructor Documentation
MooseArray() [1/4]
template<typename T > MooseArray< T >::MooseArray () inline
Default constructor.
Doesn't initialize anything.
Definition at line 25 of file MooseArray.h.
: _data(nullptr), _size(0), _allocated_size(0) {}
MooseArray() [2/4]
template<typename T > MooseArray< T >::MooseArray (const unsigned int size) inline explicit
Parameters
size The initial size of the array.
Definition at line 30 of file MooseArray.h.
                                               : _data(nullptr), _size(0), _allocated_size(0)
  {
    resize(size);
  }
MooseArray() [3/4]
template<typename T > MooseArray< T >::MooseArray (const unsigned int size, const T & default_value) inline explicit
Parameters
size The initial size of the array.
default_value The default value to set.
Definition at line 39 of file MooseArray.h.
    : _data(nullptr), _size(0), _allocated_size(0)
  {
    resize(size);
    setAllValues(default_value);
  }
MooseArray() [4/4]
template<typename T > MooseArray< T >::MooseArray (const MooseArray< T > & rhs) inline explicit
Definition at line 47 of file MooseArray.h.
                                              : _data(nullptr), _size(0), _allocated_size(0)
  {
    resize(rhs._size);
    for (unsigned int i = 0; i < _size; i++)
      _data[i] = rhs._data[i];
  }
~MooseArray()
template<typename T > MooseArray< T >::~MooseArray () default
Member Function Documentation
clear()
template<typename T > void MooseArray< T >::clear inline
Change the number of elements the array can store to zero.
Will destroy data currently in array!
Note that this does not free unused memory. This is done for speed.
Definition at line 205 of file MooseArray.h.
{
  _size = 0;
}
data()
template<typename T > const T * MooseArray< T >::data () const inline
Reference to first element of array.
Definition at line 179 of file MooseArray.h.
{ return _data; }
operator=() [1/2]
template<typename T > MooseArray< T > & MooseArray< T >::operator= (const MooseArray< T > & rhs) inline
Actual operator=... really does make a copy of the data.
If you don't want a copy use shallowCopy()
Definition at line 327 of file MooseArray.h.
{
  //  mooseError("Shouldn't be doing this!");
  resize(rhs._size);
  //  memcpy(_data,rhs._data,sizeof(T)*_size);
  for (unsigned int i = 0; i < _size; i++)
    _data[i] = rhs._data[i];
  return *this;
}
operator=() [2/2]
template<typename T > MooseArray< T > & MooseArray< T >::operator= (const std::vector< T > & rhs) inline
Actual operator=... really does make a copy of the data.
If you don't want a copy use shallowCopy()
Definition at line 313 of file MooseArray.h.
{
  unsigned int rhs_size = rhs.size();
  resize(rhs_size);
  for (unsigned int i = 0; i < rhs_size; i++)
    _data[i] = rhs[i];
  return *this;
}
operator[]() [1/2]
template<typename T > T & MooseArray< T >::operator[] (const unsigned int i) inline
Get element i out of the array.
Definition at line 263 of file MooseArray.h.
{
  mooseAssert(i < _size,
              "Access out of bounds in MooseArray (i: " << i << " size: " << _size << ")");
  return _data[i];
}
operator[]() [2/2]
template<typename T > const T & MooseArray< T >::operator[] (const unsigned int i) const inline
Get element i out of the array.
Definition at line 273 of file MooseArray.h.
{
  mooseAssert(i < _size,
              "Access out of bounds in MooseArray (i: " << i << " size: " << _size << ")");
  return _data[i];
}
release()
template<typename T > void MooseArray< T >::release () inline
Manually deallocates the data pointer.
Definition at line 66 of file MooseArray.h.
  {
    if (_data_ptr)
    {
      _data_ptr.reset();
      _data = nullptr;
      _allocated_size = _size = 0;
    }
  }
Referenced by Assembly::modifyFaceWeightsDueToXFEM(), Assembly::modifyWeightsDueToXFEM(), and Assembly::~Assembly().
resize() [1/2]
template<typename T > template<bool value_initialize> void MooseArray< T >::resize (unsigned int size) inline
Change the number of elements the array can store.
Will allocate more memory if necessary.
Can destroy data currently in array! Basically, data retention not guaranteed.
Note that this does not free unused memory. This is done for speed.
Parameters
size The new size of the array
Template Parameters
value_initialize Whether to perform value initialization of the array instead of default initialization
Definition at line 213 of file MooseArray.h.
{
  if (size > _allocated_size)
  {
    if constexpr (value_initialize)
      _data_ptr.reset(new T[size]());
    else
      _data_ptr = std::make_unique<T[]>(size);
    mooseAssert(_data_ptr, "Failed to allocate MooseArray memory!");
    _data = _data_ptr.get();
    _allocated_size = size;
  }
  _size = size;
}
Referenced by MooseVariableScalar::computeAD(), Assembly::computeADFace(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), ElectronsFromIonization::ElectronsFromIonization(), Coupleable::getADDefaultGradient(), MooseVariableDataBase< OutputType >::getArrayDoFValues(), MooseVariableDataBase< OutputType >::matrixTagValue(), MooseArray< T >::MooseArray(), MooseVariableDataBase< OutputType >::MooseVariableDataBase(), MooseVariableDataBase< OutputType >::nodalMatrixTagValue(), Assembly::reinitFVFace(), Assembly::reinitNeighborAtPhysical(), and Assembly::resizeADMappingObjects().
resize() [2/2]
template<typename T > void MooseArray< T >::resize (unsigned int size, const T & default_value) inline
Change the number of elements the array can store.
Will allocate more memory if necessary.
Can destroy data currently in array! Basically, data retention not guaranteed.
Note that this does not free unused memory. This is done for speed.
Also note that default_value is only applied to NEW entries.
Definition at line 232 of file MooseArray.h.
{
  if (size > _allocated_size)
  {
    auto new_pointer = std::make_unique<T[]>(size);
    mooseAssert(new_pointer, "Failed to allocate MooseArray memory!");
    if (_data)
      for (unsigned int i = 0; i < _size; i++)
        new_pointer[i] = _data[i];
    _data_ptr = std::move(new_pointer);
    _data = _data_ptr.get();
    _allocated_size = size;
  }
  for (unsigned int i = _size; i < size; i++)
    _data[i] = default_value;
  _size = size;
}
setAllValues()
template<typename T > void MooseArray< T >::setAllValues (const T & value) inline
Sets all values of the array to the passed in value.
Parameters
value The value every entry of the array will be set to.
Definition at line 197 of file MooseArray.h.
{
  for (unsigned int i = 0; i < _size; i++)
    _data[i] = value;
}
Referenced by MooseArray< T >::MooseArray().
shallowCopy() [1/2]
template<typename T > void MooseArray< T >::shallowCopy (const MooseArray< T > & rhs) inline
Doesn't actually make a copy of the data.
Just makes this object operate on the same data.
Definition at line 293 of file MooseArray.h.
{
  _data_ptr.reset();
  _data = rhs._data;
  _size = rhs._size;
  _allocated_size = rhs._allocated_size;
}
Referenced by Assembly::reinitElemFaceRef(), Assembly::reinitFE(), Assembly::reinitFEFace(), Assembly::reinitFEFaceNeighbor(), Assembly::reinitMortarElem(), Assembly::reinitNeighbor(), and Assembly::reinitNeighborFaceRef().
shallowCopy() [2/2]
template<typename T > void MooseArray< T >::shallowCopy (std::vector< T > & rhs) inline
Doesn't actually make a copy of the data.
Just makes this object operate on the same data.
Definition at line 303 of file MooseArray.h.
{
  _data_ptr.reset();
  _data = &rhs[0];
  _size = rhs.size();
  _allocated_size = rhs.size();
}
size()
template<typename T > unsigned int MooseArray< T >::size inline
The number of elements that can currently be stored in the array.
Definition at line 256 of file MooseArray.h.
{
  return _size;
}
Referenced by NodalPatchRecovery::compute(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVScalarLagrangeMultiplierConstraint::computeOffDiagJacobian(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), RankTwoTensorTempl< T >::fillFromScalarVariable(), SymmetricRankTwoTensorTempl< T >::fillFromScalarVariable(), Assembly::modifyArbitraryWeights(), Assembly::modifyFaceWeightsDueToXFEM(), Assembly::modifyWeightsDueToXFEM(), MooseArray< T >::MooseArray(), NodalPatchRecoveryBase::nodalPatchRecovery(), MooseVariableData< OutputType >::phiFaceSize(), MooseVariableData< OutputType >::phiSize(), Assembly::reinitFEFace(), and MaterialPropertyBase< T, is_ad >::size().
stdVector()
template<class T > std::vector< T > MooseArray< T >::stdVector
Extremely inefficient way to produce a std::vector from a MooseArray!
Returns
A copy of the MooseArray contents.
Definition at line 341 of file MooseArray.h.
{
  return std::vector<T>(_data, _data + _size);
}
Referenced by Assembly::reinitElemAndNeighbor().
swap()
template<typename T > void MooseArray< T >::swap (MooseArray< T > & rhs) inline
Swap memory in this object with the 'rhs' object.
Parameters
rhs The object we are swapping with
Definition at line 283 of file MooseArray.h.
{
  _data_ptr.swap(rhs._data_ptr);
  std::swap(_data, rhs._data);
  std::swap(_size, rhs._size);
  std::swap(_allocated_size, rhs._allocated_size);
}
Member Data Documentation
_allocated_size
template<typename T > unsigned int MooseArray< T >::_allocated_size private
Number of allocated memory positions for storage.
Definition at line 192 of file MooseArray.h.
Referenced by MooseArray< T >::release(), MooseArray< T >::shallowCopy(), and MooseArray< T >::swap().
_data
template<typename T > T* MooseArray< T >::_data private
Definition at line 186 of file MooseArray.h.
Referenced by MooseArray< T >::data(), MooseArray< T >::MooseArray(), MooseArray< T >::operator=(), MooseArray< T >::release(), MooseArray< T >::shallowCopy(), and MooseArray< T >::swap().
_data_ptr
template<typename T > std::unique_ptr<T[]> MooseArray< T >::_data_ptr private
Smart pointer storage.
Definition at line 183 of file MooseArray.h.
Referenced by MooseArray< T >::release(), and MooseArray< T >::swap().
_size
template<typename T > unsigned int MooseArray< T >::_size private
The current number of elements the array can hold.
Definition at line 189 of file MooseArray.h.
Referenced by MooseArray< T >::MooseArray(), MooseArray< T >::operator=(), MooseArray< T >::release(), MooseArray< T >::shallowCopy(), and MooseArray< T >::swap().
The documentation for this class was generated from the following file:
moose/framework/include/utils/MooseArray.h