Zapdos: FileInputStream Class Reference
FileInputStream Class Reference
Helper class that hands out input streams to a file.
#include <FileInputStream.h>
Public Member Functions
FileInputStream (const std::string &filename)
virtual std::shared_ptr< std::istream > get () const override final
Gets an input stream to the underlying stream.
virtual std::optional< std::filesystem::path > getFilename () const override final
Gets the underlying filename, if any.
bool inUse () const
Whether or not anything is still using this stream.
Protected Member Functions
void addSharedStream (const std::weak_ptr< std::istream > stream) const
Internal method to be called by derived classes to add a shared stream to _shared_streams (so that it can be tracked).
Protected Attributes
const std::filesystem::path _filename
The name of the file.
Private Attributes
std::vector< std::weak_ptr< std::istream > > _shared_streams
The streams that have been handed out by get()
Detailed Description
Helper class that hands out input streams to a file.
Definition at line 17 of file FileInputStream.h.
Constructor & Destructor Documentation
FileInputStream()
FileInputStream::FileInputStream (const std::string & filename)
Definition at line 16 of file FileInputStream.C.
                                                           : InputStream(), _filename(filename)
{
}
Member Function Documentation
addSharedStream()
void InputStream::addSharedStream (const std::weak_ptr< std::istream > stream) const protected inherited
Internal method to be called by derived classes to add a shared stream to _shared_streams (so that it can be tracked).
Should be called in the overridden get() by derived classes.
Definition at line 21 of file InputStream.C.
{
  mooseAssert(!stream.expired(), "Stream is expired");
  for (auto & entry : _shared_streams)
    if (entry.expired())
    {
      entry = stream;
      return;
    }
  _shared_streams.push_back(stream);
}
Referenced by get(), and StringInputStream::get().
get()
std::shared_ptr< std::istream > FileInputStream::get () const final override virtual
Gets an input stream to the underlying stream.
This is returned as a shared_ptr so that this class can tell whether or not another object is still using the stream.
Implements InputStream.
Definition at line 21 of file FileInputStream.C.
{
  std::shared_ptr<std::istream> stream = std::make_unique<std::ifstream>();
  addSharedStream(stream);
  auto & in = *static_cast<std::ifstream *>(stream.get());
  in.open(_filename.c_str(), std::ios::in | std::ios::binary);
  if (in.fail())
    mooseError("Unable to open file ", std::filesystem::absolute(_filename));
  return stream;
}
getFilename()
std::optional< std::filesystem::path > FileInputStream::getFilename () const final override virtual
Gets the underlying filename, if any.
Reimplemented from InputStream.
Definition at line 35 of file FileInputStream.C.
{
  return _filename;
}
inUse()
bool InputStream::inUse () const inherited
Whether or not anything is still using this stream.
This is checked by seeing whether or not the use count of any of the streams handed out by get() is > 1 (with the only use count being the one stored in _shared_streams)
Definition at line 35 of file InputStream.C.
{
  for (auto & stream : _shared_streams)
    if (!stream.expired())
      return true;
  return false;
}
Referenced by StringInputStream::release(), and InputStream::~InputStream().
Member Data Documentation
_filename
const std::filesystem::path FileInputStream::_filename protected
The name of the file.
Definition at line 28 of file FileInputStream.h.
Referenced by get(), and getFilename().
_shared_streams
std::vector<std::weak_ptr<std::istream> > InputStream::_shared_streams mutable private inherited
The streams that have been handed out by get()
Definition at line 60 of file InputStream.h.
Referenced by InputStream::addSharedStream(), and InputStream::inUse().
The documentation for this class was generated from the following files:
moose/framework/include/restart/FileInputStream.h
moose/framework/src/restart/FileInputStream.C