Zapdos: ElemInfo Class Reference
ElemInfo Class Reference
Class used for caching additional information for elements such as the volume and centroid.
#include <ElemInfo.h>
Public Member Functions
ElemInfo (const Elem *const elem)
Constructor using a real element from libmesh.
ElemInfo ()
Default constructor.
const Elem * elem () const
Real volume () const
const Point & centroid () const
Real coordFactor () const
Real & coordFactor ()
const std::vector< std::vector< dof_id_type > > & dofIndices () const
std::vector< std::vector< dof_id_type > > & dofIndices ()
SubdomainID subdomain_id () const
We return the subdomain ID of the corresponding libmesh element.
Protected Attributes
const Elem *const _elem
Reference to the element in libmesh.
Real _volume
Volume of the element.
Point _centroid
Centroid of the element.
Real _coord_transform_factor
Cached coordinate transformation factor.
std::vector< std::vector< dof_id_type > > _dof_indices
Cached dof indices mainly for segregated linear FV evaluations with the following structure: _dof_indices[system_number][variable_number] = dof_index Systems with no FV variables will store an empty vector and should not be accessed.
Detailed Description
Class used for caching additional information for elements such as the volume and centroid.
This also supports the ghost elements used in the finite volume setting (for the time being).
Definition at line 25 of file ElemInfo.h.
Constructor & Destructor Documentation
ElemInfo() [1/2]
ElemInfo::ElemInfo (const Elem *const elem)
Constructor using a real element from libmesh.
Definition at line 14 of file ElemInfo.C.
  : _elem(elem),
    _volume(_elem->volume()),
    _centroid(_elem->vertex_average()),
    _coord_transform_factor(1.0),
    _dof_indices(std::vector<std::vector<dof_id_type>>())
{
}
ElemInfo() [2/2]
ElemInfo::ElemInfo () inline
Default constructor.
Definition at line 32 of file ElemInfo.h.
: _elem(nullptr) {}
Member Function Documentation
centroid()
const Point & ElemInfo::centroid () const inline
Definition at line 36 of file ElemInfo.h.
{ return _centroid; }
Referenced by FaceInfo::computeBoundaryCoefficients(), FVInitialConditionTempl< T >::computeElement(), FaceInfo::computeInternalCoefficients(), FaceInfo::elemCentroid(), FaceInfo::neighborCentroid(), and FaceInfo::skewnessCorrectionVector().
coordFactor() [1/2]
Real & ElemInfo::coordFactor () inline
Definition at line 38 of file ElemInfo.h.
{ return _coord_transform_factor; }
coordFactor() [2/2]
Real ElemInfo::coordFactor () const inline
Definition at line 37 of file ElemInfo.h.
{ return _coord_transform_factor; }
dofIndices() [1/2]
std::vector< std::vector< dof_id_type > > & ElemInfo::dofIndices () inline
Definition at line 40 of file ElemInfo.h.
{ return _dof_indices; }
dofIndices() [2/2]
const std::vector< std::vector< dof_id_type > > & ElemInfo::dofIndices () const inline
Definition at line 39 of file ElemInfo.h.
{ return _dof_indices; }
Referenced by MooseMesh::cacheFVElementalDoFs(), and FVInitialConditionTempl< T >::computeElement().
elem()
const Elem * ElemInfo::elem () const inline
Definition at line 34 of file ElemInfo.h.
{ return _elem; }
Referenced by MooseMesh::cacheFVElementalDoFs(), FaceInfo::computeInternalCoefficients(), FaceInfo::elem(), FaceInfo::elemPtr(), FaceInfo::FaceInfo(), FaceInfo::neighbor(), and FaceInfo::neighborPtr().
subdomain_id()
SubdomainID ElemInfo::subdomain_id () const inline
We return the subdomain ID of the corresponding libmesh element.
Definition at line 43 of file ElemInfo.h.
{ return _elem->subdomain_id(); }
Referenced by MooseMesh::cacheFVElementalDoFs(), FaceInfo::elemSubdomainID(), and FaceInfo::neighborSubdomainID().
volume()
Real ElemInfo::volume () const inline
Definition at line 35 of file ElemInfo.h.
{ return _volume; }
Referenced by FaceInfo::elemVolume(), and FaceInfo::neighborVolume().
Member Data Documentation
_centroid
Point ElemInfo::_centroid protected
Centroid of the element.
Definition at line 51 of file ElemInfo.h.
Referenced by centroid().
_coord_transform_factor
Real ElemInfo::_coord_transform_factor protected
Cached coordinate transformation factor.
Definition at line 53 of file ElemInfo.h.
Referenced by coordFactor().
_dof_indices
std::vector<std::vector<dof_id_type> > ElemInfo::_dof_indices protected
Cached dof indices mainly for segregated linear FV evaluations with the following structure: _dof_indices[system_number][variable_number] = dof_index Systems with no FV variables will store an empty vector and should not be accessed.
This will be checked through multiple asserts in the assembly routines. Furthermore, if the current variable is not active on the subdomain or if it is an FE variable of this element, we return an invalid_dof_index.
Definition at line 60 of file ElemInfo.h.
Referenced by dofIndices().
_elem
const Elem* const ElemInfo::_elem protected
Reference to the element in libmesh.
Definition at line 47 of file ElemInfo.h.
Referenced by elem(), and subdomain_id().
_volume
Real ElemInfo::_volume protected
Volume of the element.
Definition at line 49 of file ElemInfo.h.
Referenced by volume().
The documentation for this class was generated from the following files:
moose/framework/include/mesh/ElemInfo.h
moose/framework/src/mesh/ElemInfo.C