Zapdos: AttribSysNum Class Reference
AttribSysNum Class Reference abstract
Tracks the libmesh system number that a MooseObject is associated with.
#include <Attributes.h>
Public Types
typedef unsigned int Key
Public Member Functions
void setFrom (Key k)
AttribSysNum (TheWarehouse &w)
AttribSysNum (TheWarehouse &w, unsigned int t)
virtual void initFrom (const MooseObject *obj) override
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
virtual bool isMatch (const Attribute &other) const override
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
virtual bool isEqual (const Attribute &other) const override
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
hashfunc (_val)
clonefunc (AttribSysNum)
bool operator== (const Attribute &other) const
bool operator!= (const Attribute &other) const
unsigned int id () const
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
virtual std::size_t hash () const =0
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
virtual std::unique_ptr< Attribute > clone () const =0
clone creates and returns and identical (deep) copy of this attribute - i.e.
Private Attributes
unsigned int _val = libMesh::invalid_uint
int _id = -1
Detailed Description
Tracks the libmesh system number that a MooseObject is associated with.
Definition at line 275 of file Attributes.h.
Member Typedef Documentation
Key
typedef unsigned int AttribSysNum::Key
Definition at line 278 of file Attributes.h.
Constructor & Destructor Documentation
AttribSysNum() [1/2]
AttribSysNum::AttribSysNum (TheWarehouse & w) inline
Definition at line 281 of file Attributes.h.
: Attribute(w, "sys_num") {}
AttribSysNum() [2/2]
AttribSysNum::AttribSysNum (TheWarehouse & w, unsigned int t) inline
Definition at line 282 of file Attributes.h.
: Attribute(w, "sys_num"), _val(t) {}
Member Function Documentation
clone()
virtual std::unique_ptr< Attribute > Attribute::clone () const pure virtual inherited
clone creates and returns and identical (deep) copy of this attribute - i.e.
the result of clone should return true if passed into isMatch.
Referenced by FEProblemBase::computeUserObjectsInternal(), and TheWarehouse::update().
clonefunc()
AttribSysNum::clonefunc (AttribSysNum)
hash()
virtual std::size_t Attribute::hash () const pure virtual inherited
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
is initialized with). Ideally, the data should be uniformly and randomly distributed across the domain of size_t values - e.g. 1 and 2 should hash to completely unrelated values. Use of std::hash for POD is encouraged. A convenience hash_combine function is also provided to combine the results an existing hash with one or more other values.
Referenced by std::hash< Attribute >::operator()().
hashfunc()
AttribSysNum::hashfunc (_val)
id()
unsigned int Attribute::id () const inline inherited
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
This ID is determined at construction time this
Definition at line 66 of file TheWarehouse.h.
{ return _id; }
Referenced by std::hash< Attribute >::operator()().
initFrom()
void AttribSysNum::initFrom (const MooseObject * obj) override virtual
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
Implements Attribute.
Definition at line 302 of file Attributes.C.
{
  auto * sys = obj->getParam<SystemBase *>("_sys");
  if (sys)
    _val = sys->number();
}
isEqual()
bool AttribSysNum::isEqual (const Attribute & other) const override virtual
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
isEqual does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 318 of file Attributes.C.
{
  return isMatch(other);
}
isMatch()
bool AttribSysNum::isMatch (const Attribute & other) const override virtual
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
This is is for query matching - not exact equivalence. isMatch does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 311 of file Attributes.C.
{
  auto a = dynamic_cast<const AttribSysNum *>(&other);
  return a && (a->_val == _val);
}
Referenced by isEqual().
operator!=()
bool Attribute::operator!= (const Attribute & other) const inline inherited
Definition at line 61 of file TheWarehouse.h.
{ return !(*this == other); }
operator==()
bool Attribute::operator== (const Attribute & other) const inline inherited
Definition at line 57 of file TheWarehouse.h.
  {
    return _id == other._id && isEqual(other);
  }
setFrom()
void AttribSysNum::setFrom (Key k) inline
Definition at line 279 of file Attributes.h.
{ _val = k; }
Member Data Documentation
_id
int Attribute::_id = -1 private inherited
Definition at line 91 of file TheWarehouse.h.
Referenced by Attribute::id(), and Attribute::operator==().
_val
unsigned int AttribSysNum::_val = libMesh::invalid_uint private
Definition at line 290 of file Attributes.h.
Referenced by initFrom(), isMatch(), and setFrom().
The documentation for this class was generated from the following files:
moose/framework/include/base/Attributes.h
moose/framework/src/base/Attributes.C