Zapdos: FunctionInterface Class Reference
FunctionInterface Class Reference
Interface for objects that need to use functions.
#include <FunctionInterface.h>
Public Member Functions
FunctionInterface (const MooseObject *moose_object)
const Function & getFunction (const std::string &name) const
Get a function with a given name.
const Function & getFunctionByName (const FunctionName &name) const
Get a function with a given name.
bool hasFunction (const std::string &param_name) const
Determine if the function exists.
bool hasFunctionByName (const FunctionName &name) const
Determine if the function exists.
Static Public Member Functions
static InputParameters validParams ()
Private Attributes
const InputParameters & _fni_params
Parameters of the object with this interface.
FEProblemBase & _fni_feproblem
Reference to FEProblemBase instance.
const THREAD_ID _fni_tid
Thread ID.
Detailed Description
Interface for objects that need to use functions.
Inherit from this class at a very low level to make the getFunction method available.
Definition at line 35 of file FunctionInterface.h.
Constructor & Destructor Documentation
FunctionInterface()
FunctionInterface::FunctionInterface (const MooseObject * moose_object)
Parameters
params The parameters used by the object being instantiated. This class needs them so it can get the function named in the input file, but the object calling getFunction only needs to use the name on the left hand side of the statement "function = func_name"
Definition at line 22 of file FunctionInterface.C.
  : _fni_params(moose_object->parameters()),
    _fni_feproblem(*_fni_params.getCheckedPointerParam<FEProblemBase *>("_fe_problem_base")),
    _fni_tid(_fni_params.have_parameter<THREAD_ID>("_tid") ? _fni_params.get<THREAD_ID>("_tid") : 0)
{
}
Member Function Documentation
getFunction()
const Function & FunctionInterface::getFunction (const std::string & name) const
Get a function with a given name.
Parameters
name The name of the parameter key of the function to retrieve
Returns
The function with name associated with the parameter 'name'
Definition at line 30 of file FunctionInterface.C.
{
  return _fni_feproblem.getFunction(_fni_params.get<FunctionName>(name), _fni_tid);
}
Referenced by FunctionDT::FunctionDT(), and Output::Output().
getFunctionByName()
const Function & FunctionInterface::getFunctionByName (const FunctionName & name) const
Get a function with a given name.
Parameters
name The name of the function to retrieve
Returns
The function with name 'name'
Definition at line 36 of file FunctionInterface.C.
{
  return _fni_feproblem.getFunction(name, _fni_tid);
}
Referenced by ArrayBodyForce::ArrayBodyForce(), ArrayFunctionIC::ArrayFunctionIC(), CompositeFunction::CompositeFunction(), FunctionArrayAux::FunctionArrayAux(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionRankTwoTensorTempl< is_ad >::GenericFunctionRankTwoTensorTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), LinearCombinationFunction::LinearCombinationFunction(), and LineFunctionSampler::LineFunctionSampler().
hasFunction()
bool FunctionInterface::hasFunction (const std::string & param_name) const
Determine if the function exists.
Parameters
param_name The name of the function parameter
index The index of the function
Returns
True if the function exists
Definition at line 42 of file FunctionInterface.C.
{
  return hasFunctionByName(_fni_params.get<FunctionName>(param_name));
}
hasFunctionByName()
bool FunctionInterface::hasFunctionByName (const FunctionName & name) const
Determine if the function exists.
Parameters
name The name of the function
Returns
True if the function exists
Definition at line 48 of file FunctionInterface.C.
{
  return _fni_feproblem.hasFunction(name, _fni_tid);
}
Referenced by hasFunction().
validParams()
InputParameters FunctionInterface::validParams () static
Definition at line 17 of file FunctionInterface.C.
{
  return emptyInputParameters();
}
Referenced by Control::validParams(), and FVInterfaceKernel::validParams().
Member Data Documentation
_fni_feproblem
FEProblemBase& FunctionInterface::_fni_feproblem private
Reference to FEProblemBase instance.
Definition at line 84 of file FunctionInterface.h.
Referenced by getFunction(), getFunctionByName(), and hasFunctionByName().
_fni_params
const InputParameters& FunctionInterface::_fni_params private
Parameters of the object with this interface.
Definition at line 81 of file FunctionInterface.h.
Referenced by getFunction(), and hasFunction().
_fni_tid
const THREAD_ID FunctionInterface::_fni_tid private
Thread ID.
Definition at line 87 of file FunctionInterface.h.
Referenced by getFunction(), getFunctionByName(), and hasFunctionByName().
The documentation for this class was generated from the following files:
moose/framework/include/functions/FunctionInterface.h
moose/framework/src/functions/FunctionInterface.C