Zapdos: FaceArgProducerInterface Class Reference
FaceArgProducerInterface Class Reference abstract
An interface for producers of functor face arguments, e.g.
#include <FaceArgInterface.h>
Public Member Functions
Moose::FaceArg makeFace (const FaceInfo &fi, const Moose::FV::LimiterType limiter_type, const bool elem_is_upwind, const bool correct_skewness=false) const
Create a functor face argument from provided component arguments.
Moose::FaceArg makeCDFace (const FaceInfo &fi, const bool correct_skewness=false) const
Make a functor face argument with a central differencing limiter, e.g.
virtual bool hasFaceSide (const FaceInfo &fi, const bool fi_elem_side) const =0
Detailed Description
An interface for producers of functor face arguments, e.g.
objects such as residual objects and postprocessors
Definition at line 32 of file FaceArgInterface.h.
Member Function Documentation
hasFaceSide()
virtual bool FaceArgInterface::hasFaceSide (const FaceInfo & fi, const bool fi_elem_side) const pure virtual inherited
Implemented in FVBoundaryCondition, FVInterfaceKernel, Moose::NullFunctor< T >, Moose::FunctorBase< T >, Moose::FunctorBase< Moose::ADType< Real >::type >, Moose::FunctorBase< Moose::ADType< T >::type >, Moose::FunctorBase< Moose::ADType< RealVectorValue >::type >, Moose::FunctorBase< Moose::ADType< RealEigenVector >::type >, Moose::FunctorBase< Moose::ADType< ComputeValueType >::type >, Moose::FunctorBase< Real >, Moose::FunctorBase< VectorValue< T > >, Moose::FunctorBase< Moose::ADType< OutputType >::type >, Moose::FunctorBase< Moose::GenericType< Real, is_ad > >, Moose::FunctorBase< GenericReal< is_ad > >, Moose::FunctorBase< ADReal >, Moose::FunctorBase< libMesh::VectorValue >, Moose::FunctorBase< GenericRealVectorValue< is_ad > >, Moose::FunctorBase< typename MetaPhysicL::RawType< T >::value_type >, Moose::FunctorBase< typename Moose::ADType< T >::type >, Moose::FunctorBase< Moose::GenericType< T, is_ad > >, Moose::FunctorBase< VectorValue< GenericReal< is_ad > > >, Moose::FunctorEnvelope< T >, Moose::FunctorEnvelope< Moose::GenericType< Real, is_ad > >, Moose::FunctorEnvelope< Real >, Moose::FunctorEnvelope< GenericReal< is_ad > >, Moose::FunctorEnvelope< ADReal >, Moose::FunctorEnvelope< libMesh::VectorValue >, Moose::FunctorEnvelope< GenericRealVectorValue< is_ad > >, Moose::FunctorEnvelope< Moose::GenericType< T, is_ad > >, Moose::FunctorEnvelope< VectorValue< GenericReal< is_ad > > >, FVFluxKernel, InterfaceIntegralVariableValuePostprocessor, InternalSideIntegralVariablePostprocessor, SideIntegralFunctorPostprocessorTempl< is_ad >, SideIntegralVariablePostprocessor, Moose::ADWrapperFunctor< T >, and Moose::RawValueFunctor< T >.
Referenced by makeFace().
makeCDFace()
Moose::FaceArg FaceArgProducerInterface::makeCDFace (const FaceInfo & fi, const bool correct_skewness = false) const inline
Make a functor face argument with a central differencing limiter, e.g.
compose a face argument that will tell functors to perform (possibly skew-corrected) linear interpolations from cell center values to faces
Parameters
fi the face information
correct_skewness whether to apply skew correction
Returns
a face argument for functors
Definition at line 61 of file FaceArgInterface.h.
{
  return makeFace(fi, Moose::FV::LimiterType::CentralDifference, true, correct_skewness);
}
Referenced by InternalSideIntegralVariablePostprocessor::computeFaceInfoIntegral(), SideIntegralVariablePostprocessor::computeFaceInfoIntegral(), and InterfaceIntegralVariableValuePostprocessor::computeQpIntegral().
makeFace()
Moose::FaceArg FaceArgProducerInterface::makeFace (const FaceInfo & fi, const Moose::FV::LimiterType limiter_type, const bool elem_is_upwind, const bool correct_skewness = false) const
Create a functor face argument from provided component arguments.
Parameters
fi the face information object
limiter_type the limiter that defines how to perform interpolations to the faces
elem_is_upwind whether the face information element is the upwind element (the value of this doesn't matter when the limiter type is CentralDifference)
correct_skewness whether to apply skew correction
Returns
the functor face argument
Definition at line 13 of file FaceArgInterface.C.
{
  const bool defined_on_elem_side = hasFaceSide(fi, true);
  const bool defined_on_neighbor_side = hasFaceSide(fi, false);
  const Elem * const elem = defined_on_elem_side && defined_on_neighbor_side
                                ? nullptr
                                : (defined_on_elem_side ? &fi.elem() : fi.neighborPtr());
  if (!defined_on_elem_side && !defined_on_neighbor_side)
    mooseError("No definition on either side");
  return {&fi, limiter_type, elem_is_upwind, correct_skewness, elem};
}
Referenced by FVAdvection::computeQpResidual(), FVDivergence::computeQpResidual(), FVMatAdvection::computeQpResidual(), FVBoundaryIntegralValueConstraint::computeQpResidual(), makeCDFace(), FVBoundaryCondition::singleSidedFaceArg(), FVFluxKernel::singleSidedFaceArg(), and FVInterfaceKernel::singleSidedFaceArg().
The documentation for this class was generated from the following files:
moose/framework/include/interfaces/FaceArgInterface.h
moose/framework/src/interfaces/FaceArgInterface.C