Zapdos: YAMLFormatter Class Reference
YAMLFormatter Class Reference
This class produces produces a yaml dump of the InputParameters that is machine parsable by any YAML formatter.
#include <YAMLFormatter.h>
Public Member Functions
YAMLFormatter (bool dump_mode)
virtual std::string preamble () const override
This method is called once at the beginning of the tree traversal and can be used to build up header information.
virtual std::string postscript () const override
This method is called once at the end of the tree traversal and can be used to add any necessary trailing information to the final formatted string.
virtual std::string preTraverse (short depth) const override
This method is called once at each node in the syntax tree before traversing child nodes.
virtual std::string printBlockOpen (const std::string &name, short depth, const std::string &doc) override
This method is called at the beginning of each Node in the tree.
virtual std::string printBlockClose (const std::string &name, short depth) const override
This method is called at the end of of each Node in the tree.
virtual std::string printParams (const std::string &prefix, const std::string &fully_qualified_name, InputParameters &params, short depth, const std::string &search_string, bool &found) override
This function is called for each InputParameters object stored at a particular node.
template<typename T >
void addEnumOptionsAndDocs (std::ostringstream &oss, T &param, const std::string &indent)
void insertNode (std::string syntax, const std::string &action, bool is_action_params=true, InputParameters *params=NULL)
std::string print (const std::string &search_string)
void seenIt (const std::string &prefix, const std::string &item)
bool haveSeenIt (const std::string &prefix, const std::string &item) const
Protected Member Functions
void buildOutputString (std::ostringstream &output, const std::iterator_traits< InputParameters::iterator >::value_type &p)
Method for building an output string that accounts for specific types (e.g., Point)
bool isLongNames () const
Protected Attributes
bool _dump_mode
std::unique_ptr< TreeNode > _root
bool _use_long_names
Private Attributes
std::set< std::string > _params_printed
Detailed Description
This class produces produces a yaml dump of the InputParameters that is machine parsable by any YAML formatter.
Definition at line 22 of file YAMLFormatter.h.
Constructor & Destructor Documentation
YAMLFormatter()
YAMLFormatter::YAMLFormatter (bool dump_mode)
Definition at line 24 of file YAMLFormatter.C.
: SyntaxTree(true), _dump_mode(dump_mode) {}
Member Function Documentation
addEnumOptionsAndDocs()
template<typename T > void YAMLFormatter::addEnumOptionsAndDocs (std::ostringstream & oss, T & param, const std::string & indent)
Definition at line 122 of file YAMLFormatter.C.
{
  oss << indent << "    options: " << param.getRawNames() << '\n';
  const auto & docs = param.getItemDocumentation();
  if (!docs.empty())
  {
    oss << indent << "    option_docs:\n";
    for (const auto & doc : docs)
    {
      oss << indent << "    - name: " << doc.first.name() << "\n";
      oss << indent << "      description: |\n";
      oss << indent << "        " << doc.second << "\n";
    }
  }
}
Referenced by printParams().
buildOutputString()
void YAMLFormatter::buildOutputString (std::ostringstream & output, const std::iterator_traits< InputParameters::iterator >::value_type & p) protected
Method for building an output string that accounts for specific types (e.g., Point)
Parameters
output Reference to the output string
iter InputParameters iterator that is being output
Definition at line 171 of file YAMLFormatter.C.
{
  libMesh::Parameters::Value * val = MooseUtils::get(p.second);
  // Account for Point
  InputParameters::Parameter<Point> * ptr0 = dynamic_cast<InputParameters::Parameter<Point> *>(val);
  // Account for RealVectorValues
  InputParameters::Parameter<RealVectorValue> * ptr1 =
      dynamic_cast<InputParameters::Parameter<RealVectorValue> *>(val);
  // Output the Point components
  if (ptr0)
    output << ptr0->get().operator()(0) << " " << ptr0->get().operator()(1) << " "
           << ptr0->get().operator()(2);
  // Output the RealVectorValue components
  else if (ptr1)
    output << ptr1->get().operator()(0) << " " << ptr1->get().operator()(1) << " "
           << ptr1->get().operator()(2);
  // General case, call the print operator
  else
    p.second->print(output);
}
Referenced by printParams().
haveSeenIt()
bool SyntaxTree::haveSeenIt (const std::string & prefix, const std::string & item) const inherited
Definition at line 63 of file SyntaxTree.C.
{
  return _params_printed.find(prefix + item) != _params_printed.end();
}
Referenced by InputFileFormatter::printParams(), and printParams().
insertNode()
void SyntaxTree::insertNode (std::string syntax, const std::string & action, bool is_action_params = true, InputParameters * params = NULL) inherited
Definition at line 27 of file SyntaxTree.C.
{
  if (!_root)
    _root = std::make_unique<TreeNode>("", *this);
  _root->insertNode(syntax, action, is_action_params, params);
}
Referenced by ActionWarehouse::printInputFile().
isLongNames()
bool SyntaxTree::isLongNames () const protected inherited
Definition at line 227 of file SyntaxTree.C.
{
  return _use_long_names;
}
postscript()
std::string YAMLFormatter::postscript () const override virtual
This method is called once at the end of the tree traversal and can be used to add any necessary trailing information to the final formatted string.
Returns
- The formatted postscript string
Reimplemented from SyntaxFormatterInterface.
Definition at line 34 of file YAMLFormatter.C.
{
  return "**END YAML DATA**\n";
}
preamble()
std::string YAMLFormatter::preamble () const override virtual
This method is called once at the beginning of the tree traversal and can be used to build up header information.
Returns
- The formatted preamble string
Reimplemented from SyntaxFormatterInterface.
Definition at line 27 of file YAMLFormatter.C.
{
  // important: start and end yaml data delimiters used by python
  return "**START YAML DATA**\n";
}
preTraverse()
std::string YAMLFormatter::preTraverse (short) const override virtual
This method is called once at each node in the syntax tree before traversing child nodes.
Returns
- The formatted pre-node traversal string
Reimplemented from SyntaxFormatterInterface.
Definition at line 141 of file YAMLFormatter.C.
{
  std::string indent(depth * 2, ' ');
  return indent + "  subblocks:\n";
}
print()
std::string SyntaxTree::print (const std::string & search_string) inherited
Definition at line 39 of file SyntaxTree.C.
{
  bool found = false;
  std::string output;
  // Clear the list of "seen" parameters before printing the tree
  _params_printed.clear();
  if (_root)
    output = _root->print(-1, search_string, found);
  if (found)
    return preamble() + output + postscript();
  else
    return "";
}
Referenced by ActionWarehouse::printInputFile().
printBlockClose()
std::string YAMLFormatter::printBlockClose (const std::string & name, short depth) const override virtual
This method is called at the end of of each Node in the tree.
It is typically used to provide formatting necessary when closing blocks.
Returns
- The formatted block close string
Implements SyntaxFormatterInterface.
Definition at line 165 of file YAMLFormatter.C.
{
  return std::string();
}
printBlockOpen()
std::string YAMLFormatter::printBlockOpen (const std::string & name, short depth, const std::string & doc) override virtual
This method is called at the beginning of each Node in the tree.
It is typically used to provide formatting necessary when opening new blocks.
Returns
- The formatted block open string
Implements SyntaxFormatterInterface.
Definition at line 149 of file YAMLFormatter.C.
{
  std::ostringstream oss;
  std::string indent(depth * 2, ' ');
  std::string docEscaped = doc;
  MooseUtils::escape(docEscaped);
  oss << indent << "- name: " << name << "\n";
  oss << indent << "  description: |\n" << indent << "    " << docEscaped << "\n";
  oss << indent << "  parameters:\n";
  return oss.str();
}
printParams()
std::string YAMLFormatter::printParams (const std::string & prefix, const std::string & fully_qualified_name, InputParameters & params, short depth, const std::string & search_string, bool & found) override virtual
This function is called for each InputParameters object stored at a particular node.
It is responsible for formatting the parameters for the current node.
Returns
- The formatted parameters string for a Node.
Implements SyntaxFormatterInterface.
Definition at line 40 of file YAMLFormatter.C.
{
  std::ostringstream oss;
  std::string indent(depth * 2, ' ');
  for (auto & iter : params)
  {
    std::string name = iter.first;
    // First make sure we want to see this parameter, also block active and type
    if (params.isPrivate(iter.first) || name == "active" ||
        (search_string != "" && search_string != iter.first) || haveSeenIt(prefix, iter.first))
      continue;
    found = true;
    // Mark it as "seen"
    seenIt(prefix, iter.first);
    // Block params may be required and will have a doc string
    std::string required = params.isParamRequired(iter.first) ? "Yes" : "No";
    oss << indent << "  - name: " << name << "\n";
    oss << indent << "    required: " << required << "\n";
    oss << indent << "    default: !!str ";
    // Only output default if it has one
    if (params.isParamValid(iter.first))
    {
      // prints the value, which is the default value when dumping the tree
      // because it hasn't been changed
      // Output stream, performing special operations for writing objects such as Points and
      // RealVectorValues
      std::ostringstream toss;
      buildOutputString(toss, iter);
      // remove additional '\n' possibly generated in output (breaks YAML parsing)
      std::string tmp_str = toss.str();
      for (auto & ch : tmp_str)
        if (ch == '\n')
          ch = ' ';
      if (tmp_str == ",")
        oss << "\"" << tmp_str << "\"";
      else
        oss << tmp_str;
    }
    else if (params.hasDefaultCoupledValue(iter.first))
      oss << params.defaultCoupledValue(iter.first);
    std::string doc = params.getDocString(iter.first);
    MooseUtils::escape(doc);
    // Print the type
    oss << "\n"
        << indent << "    cpp_type: " << params.type(iter.first) << "\n"
        << indent << "    group_name: ";
    std::string group_name = params.getGroupName(iter.first);
    if (!group_name.empty())
      oss << "'" << group_name << "'";
    oss << "\n";
    if (params.have_parameter<MooseEnum>(name))
      addEnumOptionsAndDocs(oss, params.get<MooseEnum>(name), indent);
    if (params.have_parameter<MultiMooseEnum>(name))
      addEnumOptionsAndDocs(oss, params.get<MultiMooseEnum>(name), indent);
    if (params.have_parameter<ExecFlagEnum>(name))
      addEnumOptionsAndDocs(oss, params.get<ExecFlagEnum>(name), indent);
    if (params.have_parameter<std::vector<MooseEnum>>(name))
      addEnumOptionsAndDocs(oss, params.get<std::vector<MooseEnum>>(name)[0], indent);
    oss << indent << "    description: |\n      " << indent << doc << std::endl;
  }
  return oss.str();
}
seenIt()
void SyntaxTree::seenIt (const std::string & prefix, const std::string & item) inherited
Definition at line 57 of file SyntaxTree.C.
{
  _params_printed.insert(prefix + item);
}
Referenced by InputFileFormatter::printParams(), and printParams().
Member Data Documentation
_dump_mode
bool YAMLFormatter::_dump_mode protected
Definition at line 44 of file YAMLFormatter.h.
_params_printed
std::set<std::string> SyntaxTree::_params_printed private inherited
Definition at line 80 of file SyntaxTree.h.
Referenced by SyntaxTree::haveSeenIt(), SyntaxTree::print(), and SyntaxTree::seenIt().
_root
std::unique_ptr<TreeNode> SyntaxTree::_root protected inherited
Definition at line 76 of file SyntaxTree.h.
Referenced by SyntaxTree::insertNode(), and SyntaxTree::print().
_use_long_names
bool SyntaxTree::_use_long_names protected inherited
Definition at line 77 of file SyntaxTree.h.
Referenced by SyntaxTree::isLongNames().
The documentation for this class was generated from the following files:
moose/framework/include/outputs/formatters/YAMLFormatter.h
moose/framework/src/outputs/formatters/YAMLFormatter.C