Zapdos: DisplacedProblem Class Reference
DisplacedProblem Class Reference abstract
#include <DisplacedProblem.h>
Public Member Functions
DisplacedProblem (DisplacedProblem &&)=delete
DisplacedProblem & operator= (DisplacedProblem &&)=delete
DisplacedProblem (const InputParameters &parameters)
~DisplacedProblem ()
virtual EquationSystems & es () override
virtual MooseMesh & mesh () override
virtual const MooseMesh & mesh () const override
const MooseMesh & mesh (bool libmesh_dbg_var(use_displaced)) const override
MooseMesh & refMesh ()
DisplacedSystem & nlSys (const unsigned int sys_num)
DisplacedSystem & auxSys ()
virtual const SystemBase & systemBaseNonlinear (const unsigned int sys_num) const override
Return the nonlinear system object as a base class reference given the system number.
virtual SystemBase & systemBaseNonlinear (const unsigned int sys_num) override
virtual const SystemBase & systemBaseAuxiliary () const override
Return the auxiliary system object as a base class reference.
virtual SystemBase & systemBaseAuxiliary () override
const std::vector< std::string > & getDisplacementVarNames () const
virtual void createQRules (QuadratureType type, Order order, Order volume_order, Order face_order, SubdomainID block, bool allow_negative_qweights=true)
void bumpVolumeQRuleOrder (Order order, SubdomainID block)
void bumpAllQRuleOrder (Order order, SubdomainID block)
virtual void init () override
virtual bool nlConverged (const unsigned int nl_sys_num) override
virtual unsigned int nlSysNum (const NonlinearSystemName &nl_sys_name) const override
virtual void saveOldSolutions ()
Allocate vectors and save old solutions into them.
virtual void restoreOldSolutions ()
Restore old solutions from the backup vectors and deallocate them.
virtual void syncSolutions ()
Copy the solutions on the undisplaced systems to the displaced systems.
virtual void syncSolutions (const std::map< unsigned int, const NumericVector< Number > * > &nl_solns, const NumericVector< Number > &aux_soln)
Synchronize the solutions on the displaced systems to the given solutions.
virtual void updateMesh (bool mesh_changing=false)
Copy the solutions on the undisplaced systems to the displaced systems and reinitialize the geometry search data and Dirac kernel information due to mesh displacement.
virtual void updateMesh (const std::map< unsigned int, const NumericVector< Number > * > &nl_soln, const NumericVector< Number > &aux_soln)
Synchronize the solutions on the displaced systems to the given solutions and reinitialize the geometry search data and Dirac kernel information due to mesh displacement.
virtual TagID addVectorTag (const TagName &tag_name, const Moose::VectorTagType type=Moose::VECTOR_TAG_RESIDUAL) override
Create a Tag.
virtual const VectorTag & getVectorTag (const TagID tag_id) const override
Get a VectorTag from a TagID.
virtual TagID getVectorTagID (const TagName &tag_name) const override
Get a TagID from a TagName.
virtual TagName vectorTagName (const TagID tag_id) const override
Retrieve the name associated with a TagID.
virtual bool vectorTagExists (const TagID tag_id) const override
Check to see if a particular Tag exists.
virtual bool vectorTagExists (const TagName &tag_name) const override
Check to see if a particular Tag exists by using Tag name.
virtual unsigned int numVectorTags (const Moose::VectorTagType type=Moose::VECTOR_TAG_ANY) const override
The total number of tags, which can be limited to the tag type.
virtual const std::vector< VectorTag > & getVectorTags (const Moose::VectorTagType type=Moose::VECTOR_TAG_ANY) const override
Return all vector tags, where a tag is represented by a map from name to ID.
virtual Moose::VectorTagType vectorTagType (const TagID tag_id) const override
virtual TagID addMatrixTag (TagName tag_name) override
Create a Tag.
virtual TagID getMatrixTagID (const TagName &tag_name) override
Get a TagID from a TagName.
virtual TagName matrixTagName (TagID tag) override
Retrieve the name associated with a TagID.
virtual bool matrixTagExists (const TagName &tag_name) override
Check to see if a particular Tag exists.
virtual bool matrixTagExists (TagID tag_id) override
Check to see if a particular Tag exists.
virtual unsigned int numMatrixTags () const override
The total number of tags.
virtual bool safeAccessTaggedMatrices () const override
Is it safe to access the tagged matrices.
virtual bool safeAccessTaggedVectors () const override
Is it safe to access the tagged vectors.
virtual bool isTransient () const override
virtual bool hasVariable (const std::string &var_name) const override
Whether or not this problem has the variable.
virtual const MooseVariableFieldBase & getVariable (const THREAD_ID tid, const std::string &var_name, Moose::VarKindType expected_var_type=Moose::VarKindType::VAR_ANY, Moose::VarFieldType expected_var_field_type=Moose::VarFieldType::VAR_FIELD_ANY) const override
Returns the variable reference for requested variable which must be of the expected_var_type (Nonlinear vs.
virtual MooseVariable & getStandardVariable (const THREAD_ID tid, const std::string &var_name) override
Returns the variable reference for requested MooseVariable which may be in any system.
virtual MooseVariableFieldBase & getActualFieldVariable (const THREAD_ID tid, const std::string &var_name) override
Returns the variable reference for requested MooseVariableField which may be in any system.
virtual VectorMooseVariable & getVectorVariable (const THREAD_ID tid, const std::string &var_name) override
Returns the variable reference for requested VectorMooseVariable which may be in any system.
virtual ArrayMooseVariable & getArrayVariable (const THREAD_ID tid, const std::string &var_name) override
Returns the variable reference for requested ArrayMooseVariable which may be in any system.
virtual bool hasScalarVariable (const std::string &var_name) const override
Returns a Boolean indicating whether any system contains a variable with the name provided.
virtual MooseVariableScalar & getScalarVariable (const THREAD_ID tid, const std::string &var_name) override
Returns the scalar variable reference from whichever system contains it.
virtual System & getSystem (const std::string &var_name) override
Returns the equation system containing the variable provided.
virtual void addVariable (const std::string &var_type, const std::string &name, InputParameters &parameters, unsigned int nl_system_number)
virtual void addAuxVariable (const std::string &var_type, const std::string &name, InputParameters &parameters)
virtual void initAdaptivity ()
virtual void meshChanged () override
virtual void prepare (const Elem *elem, const THREAD_ID tid) override
virtual void prepareNonlocal (const THREAD_ID tid)
virtual void prepareFace (const Elem *elem, const THREAD_ID tid) override
virtual void prepare (const Elem *elem, unsigned int ivar, unsigned int jvar, const std::vector< dof_id_type > &dof_indices, const THREAD_ID tid) override
virtual void setCurrentSubdomainID (const Elem *elem, const THREAD_ID tid) override
virtual void setNeighborSubdomainID (const Elem *elem, unsigned int side, const THREAD_ID tid) override
virtual void prepareBlockNonlocal (unsigned int ivar, unsigned int jvar, const std::vector< dof_id_type > &idof_indices, const std::vector< dof_id_type > &jdof_indices, const THREAD_ID tid)
virtual void prepareAssembly (const THREAD_ID tid) override
virtual void prepareAssemblyNeighbor (const THREAD_ID tid)
virtual bool reinitDirac (const Elem *elem, const THREAD_ID tid) override
Returns true if the Problem has Dirac kernels it needs to compute on elem.
virtual void reinitElem (const Elem *elem, const THREAD_ID tid) override
virtual void reinitElemPhys (const Elem *elem, const std::vector< Point > &phys_points_in_elem, const THREAD_ID tid) override
virtual void reinitElemFace (const Elem *elem, unsigned int side, BoundaryID bnd_id, const THREAD_ID tid) override
virtual void reinitNode (const Node *node, const THREAD_ID tid) override
virtual void reinitNodeFace (const Node *node, BoundaryID bnd_id, const THREAD_ID tid) override
virtual void reinitNodes (const std::vector< dof_id_type > &nodes, const THREAD_ID tid) override
virtual void reinitNodesNeighbor (const std::vector< dof_id_type > &nodes, const THREAD_ID tid) override
virtual void reinitNeighbor (const Elem *elem, unsigned int side, const THREAD_ID tid) override
void reinitNeighbor (const Elem *elem, unsigned int side, const THREAD_ID tid, const std::vector< Point > *neighbor_reference_points)
reinitialize neighbor routine
virtual void reinitNeighborPhys (const Elem *neighbor, unsigned int neighbor_side, const std::vector< Point > &physical_points, const THREAD_ID tid) override
virtual void reinitNeighborPhys (const Elem *neighbor, const std::vector< Point > &physical_points, const THREAD_ID tid) override
virtual void reinitElemNeighborAndLowerD (const Elem *elem, unsigned int side, const THREAD_ID tid) override
virtual void reinitScalars (const THREAD_ID tid, bool reinit_for_derivative_reordering=false) override
fills the VariableValue arrays for scalar variables from the solution vector
virtual void reinitOffDiagScalars (const THREAD_ID tid) override
virtual void getDiracElements (std::set< const Elem * > &elems) override
Fills "elems" with the elements that should be looped over for Dirac Kernels.
virtual void clearDiracInfo () override
Gets called before Dirac Kernels are asked to add the points they are supposed to be evaluated in.
virtual void addResidual (const THREAD_ID tid) override
virtual void addResidualNeighbor (const THREAD_ID tid) override
virtual void addResidualLower (const THREAD_ID tid) override
virtual void addCachedResidualDirectly (NumericVector< Number > &residual, const THREAD_ID tid)
virtual void setResidual (NumericVector< Number > &residual, const THREAD_ID tid) override
virtual void setResidualNeighbor (NumericVector< Number > &residual, const THREAD_ID tid) override
virtual void addJacobian (const THREAD_ID tid) override
virtual void addJacobianNonlocal (const THREAD_ID tid)
virtual void addJacobianNeighbor (const THREAD_ID tid) override
virtual void addJacobianNeighborLowerD (const THREAD_ID tid) override
virtual void addJacobianLowerD (const THREAD_ID tid) override
virtual void addJacobianBlockTags (SparseMatrix< Number > &jacobian, unsigned int ivar, unsigned int jvar, const DofMap &dof_map, std::vector< dof_id_type > &dof_indices, const std::set< TagID > &tags, const THREAD_ID tid)
void addJacobianBlockNonlocal (SparseMatrix< Number > &jacobian, unsigned int ivar, unsigned int jvar, const DofMap &dof_map, const std::vector< dof_id_type > &idof_indices, const std::vector< dof_id_type > &jdof_indices, const std::set< TagID > &tags, const THREAD_ID tid)
virtual void addJacobianNeighbor (SparseMatrix< Number > &jacobian, unsigned int ivar, unsigned int jvar, const DofMap &dof_map, std::vector< dof_id_type > &dof_indices, std::vector< dof_id_type > &neighbor_dof_indices, const std::set< TagID > &tags, const THREAD_ID tid) override
virtual void cacheJacobianNonlocal (const THREAD_ID tid)
virtual void prepareShapes (unsigned int var, const THREAD_ID tid) override
virtual void prepareFaceShapes (unsigned int var, const THREAD_ID tid) override
virtual void prepareNeighborShapes (unsigned int var, const THREAD_ID tid) override
Assembly & assembly (const THREAD_ID tid, const unsigned int nl_sys_num) override
const Assembly & assembly (const THREAD_ID tid, const unsigned int nl_sys_num) const override
virtual void updateGeomSearch (GeometricSearchData::GeometricSearchType type=GeometricSearchData::ALL) override
virtual GeometricSearchData & geomSearchData () override
virtual bool computingInitialResidual (const unsigned int nl_sys_num) const override
Returns true if the problem is in the process of computing it's initial residual.
virtual void onTimestepBegin () override
virtual void onTimestepEnd () override
virtual std::set< dof_id_type > & ghostedElems () override
Return the list of elements that should have their DoFs ghosted to this processor.
virtual void addGhostedElem (dof_id_type elem_id) override
Will make sure that all dofs connected to elem_id are ghosted to this processor.
virtual void addGhostedBoundary (BoundaryID boundary_id) override
Will make sure that all necessary elements from boundary_id are ghosted to this processor.
virtual void ghostGhostedBoundaries () override
Causes the boundaries added using addGhostedBoundary to actually be ghosted.
void undisplaceMesh ()
Resets the displaced mesh to the reference mesh.
LineSearch * getLineSearch () override
const CouplingMatrix * couplingMatrix (const unsigned int nl_sys_num) const override
The coupling matrix defining what blocks exist in the preconditioning matrix.
bool haveDisplaced () const override final
Whether we have a displaced problem in our simulation.
bool computingScalingJacobian () const override final
Getter for whether we're computing the scaling jacobian.
bool computingScalingResidual () const override final
Getter for whether we're computing the scaling residual.
void initialSetup () override
void timestepSetup () override
void customSetup (const ExecFlagType &exec_type) override
void residualSetup () override
void jacobianSetup () override
void haveADObjects (bool have_ad_objects) override
Method for setting whether we have any ad objects.
std::size_t numNonlinearSystems () const override
unsigned int currentNlSysNum () const override
virtual const std::vector< VectorTag > & currentResidualVectorTags () const override
Return the residual vector tags we are currently computing.
virtual void needFV () override
marks this problem as including/needing finite volume functionality.
virtual bool haveFV () const override
returns true if this problem includes/needs finite volume functionality.
virtual bool hasNonlocalCoupling () const override
Whether the simulation has nonlocal coupling which should be accounted for in the Jacobian.
virtual const MooseVariableFieldBase & getVariable (const THREAD_ID tid, const std::string &var_name, Moose::VarKindType expected_var_type=Moose::VarKindType::VAR_ANY, Moose::VarFieldType expected_var_field_type=Moose::VarFieldType::VAR_FIELD_ANY) const=0
Returns the variable reference for requested variable which must be of the expected_var_type (Nonlinear vs.
virtual MooseVariableFieldBase & getVariable (const THREAD_ID tid, const std::string &var_name, Moose::VarKindType expected_var_type=Moose::VarKindType::VAR_ANY, Moose::VarFieldType expected_var_field_type=Moose::VarFieldType::VAR_FIELD_ANY)
virtual void haveADObjects (bool have_ad_objects)
Method for setting whether we have any ad objects.
bool haveADObjects () const
Method for reading wehther we have any ad objects.
virtual const MooseMesh & mesh (bool use_displaced) const =0
virtual bool checkNonlocalCouplingRequirement ()
virtual bool converged (const unsigned int nl_sys_num)
Eventually we want to convert this virtual over to taking a nonlinear system number argument.
bool defaultGhosting ()
Whether or not the user has requested default ghosting ot be on.
std::vector< VectorTag > getVectorTags (const std::set< TagID > &tag_ids) const
virtual std::map< TagName, TagID > & getMatrixTags ()
Return all matrix tags in the system, where a tag is represented by a map from name to ID.
virtual void setActiveElementalMooseVariables (const std::set< MooseVariableFieldBase * > &moose_vars, const THREAD_ID tid)
Set the MOOSE variables to be reinited on each element.
virtual const std::set< MooseVariableFieldBase * > & getActiveElementalMooseVariables (const THREAD_ID tid) const
Get the MOOSE variables to be reinited on each element.
virtual bool hasActiveElementalMooseVariables (const THREAD_ID tid) const
Whether or not a list of active elemental moose variables has been set.
virtual void clearActiveElementalMooseVariables (const THREAD_ID tid)
Clear the active elemental MooseVariableFieldBase.
Moose::CoordinateSystemType getCoordSystem (SubdomainID sid) const
unsigned int getAxisymmetricRadialCoord () const
Returns the desired radial direction for RZ coordinate transformation.
virtual DiracKernelInfo & diracKernelInfo ()
virtual Real finalNonlinearResidual (const unsigned int nl_sys_num) const
virtual unsigned int nNonlinearIterations (const unsigned int nl_sys_num) const
virtual unsigned int nLinearIterations (const unsigned int nl_sys_num) const
virtual void cacheResidual (const THREAD_ID tid)
virtual void cacheResidualNeighbor (const THREAD_ID tid)
virtual void addCachedResidual (const THREAD_ID tid)
virtual void cacheJacobian (const THREAD_ID tid)
virtual void cacheJacobianNeighbor (const THREAD_ID tid)
virtual void addCachedJacobian (const THREAD_ID tid)
virtual void reinitLowerDElem (const Elem *lower_d_elem, const THREAD_ID tid, const std::vector< Point > *const pts=nullptr, const std::vector< Real > *const weights=nullptr)
void setCurrentBoundaryID (BoundaryID bid, const THREAD_ID tid)
sets the current boundary ID in assembly
virtual void reinitElemFaceRef (const Elem *elem, unsigned int side, BoundaryID bnd_id, Real tolerance, const std::vector< Point > *const pts, const std::vector< Real > *const weights=nullptr, const THREAD_ID tid=0)
reinitialize FE objects on a given element on a given side at a given set of reference points and then compute variable data.
virtual void reinitNeighborFaceRef (const Elem *neighbor_elem, unsigned int neighbor_side, BoundaryID bnd_id, Real tolerance, const std::vector< Point > *const pts, const std::vector< Real > *const weights=nullptr, const THREAD_ID tid=0)
reinitialize FE objects on a given neighbor element on a given side at a given set of reference points and then compute variable data.
void reinitNeighborLowerDElem (const Elem *elem, const THREAD_ID tid=0)
reinitialize a neighboring lower dimensional element
void reinitMortarElem (const Elem *elem, const THREAD_ID tid=0)
Reinit a mortar element to obtain a valid JxW.
virtual void storeSubdomainMatPropName (SubdomainID block_id, const std::string &name)
Adds the given material property to a storage map based on block ids.
virtual void storeBoundaryMatPropName (BoundaryID boundary_id, const std::string &name)
Adds the given material property to a storage map based on boundary ids.
virtual void storeSubdomainZeroMatProp (SubdomainID block_id, const MaterialPropertyName &name)
Adds to a map based on block ids of material properties for which a zero value can be returned.
virtual void storeBoundaryZeroMatProp (BoundaryID boundary_id, const MaterialPropertyName &name)
Adds to a map based on boundary ids of material properties for which a zero value can be returned.
virtual void storeSubdomainDelayedCheckMatProp (const std::string &requestor, SubdomainID block_id, const std::string &name)
Adds to a map based on block ids of material properties to validate.
virtual void storeBoundaryDelayedCheckMatProp (const std::string &requestor, BoundaryID boundary_id, const std::string &name)
Adds to a map based on boundary ids of material properties to validate.
virtual void checkBlockMatProps ()
Checks block material properties integrity.
virtual void checkBoundaryMatProps ()
Checks boundary material properties integrity.
virtual void markMatPropRequested (const std::string &)
Helper method for adding a material property name to the _material_property_requested set.
virtual bool isMatPropRequested (const std::string &prop_name) const
Find out if a material property has been requested by any object.
void addConsumedPropertyName (const MooseObjectName &obj_name, const std::string &prop_name)
Helper for tracking the object that is consuming a property for MaterialPropertyDebugOutput.
const std::map< MooseObjectName, std::set< std::string > > & getConsumedPropertyMap () const
Return the map that tracks the object with consumed material properties.
virtual std::set< SubdomainID > getMaterialPropertyBlocks (const std::string &prop_name)
Get a vector containing the block ids the material property is defined on.
virtual std::vector< SubdomainName > getMaterialPropertyBlockNames (const std::string &prop_name)
Get a vector of block id equivalences that the material property is defined on.
virtual bool hasBlockMaterialProperty (SubdomainID block_id, const std::string &prop_name)
Check if a material property is defined on a block.
virtual std::set< BoundaryID > getMaterialPropertyBoundaryIDs (const std::string &prop_name)
Get a vector containing the block ids the material property is defined on.
virtual std::vector< BoundaryName > getMaterialPropertyBoundaryNames (const std::string &prop_name)
Get a vector of block id equivalences that the material property is defined on.
virtual bool hasBoundaryMaterialProperty (BoundaryID boundary_id, const std::string &prop_name)
Check if a material property is defined on a block.
const CouplingMatrix & nonlocalCouplingMatrix (const unsigned i) const
const bool & currentlyComputingJacobian () const
Returns true if the problem is in the process of computing the Jacobian.
void setCurrentlyComputingJacobian (const bool currently_computing_jacobian)
Set whether or not the problem is in the process of computing the Jacobian.
const bool & currentlyComputingResidualAndJacobian () const
Returns true if the problem is in the process of computing the residual and the Jacobian.
void setCurrentlyComputingResidualAndJacobian (bool currently_computing_residual_and_jacobian)
Set whether or not the problem is in the process of computing the Jacobian.
bool computingNonlinearResid () const
Returns true if the problem is in the process of computing the nonlinear residual.
virtual void computingNonlinearResid (const bool computing_nonlinear_residual)
Set whether or not the problem is in the process of computing the nonlinear residual.
const bool & currentlyComputingResidual () const
Returns true if the problem is in the process of computing the residual.
virtual void setCurrentlyComputingResidual (const bool currently_computing_residual)
Set whether or not the problem is in the process of computing the residual.
virtual void clearActiveFEVariableCoupleableMatrixTags (const THREAD_ID tid)
virtual void clearActiveFEVariableCoupleableVectorTags (const THREAD_ID tid)
virtual void setActiveFEVariableCoupleableVectorTags (std::set< TagID > &vtags, const THREAD_ID tid)
virtual void setActiveFEVariableCoupleableMatrixTags (std::set< TagID > &mtags, const THREAD_ID tid)
virtual void clearActiveScalarVariableCoupleableMatrixTags (const THREAD_ID tid)
virtual void clearActiveScalarVariableCoupleableVectorTags (const THREAD_ID tid)
virtual void setActiveScalarVariableCoupleableVectorTags (std::set< TagID > &vtags, const THREAD_ID tid)
virtual void setActiveScalarVariableCoupleableMatrixTags (std::set< TagID > &mtags, const THREAD_ID tid)
const std::set< TagID > & getActiveScalarVariableCoupleableVectorTags (const THREAD_ID tid) const
const std::set< TagID > & getActiveScalarVariableCoupleableMatrixTags (const THREAD_ID tid) const
const std::set< TagID > & getActiveFEVariableCoupleableVectorTags (const THREAD_ID tid) const
const std::set< TagID > & getActiveFEVariableCoupleableMatrixTags (const THREAD_ID tid) const
void addAlgebraicGhostingFunctor (GhostingFunctor &algebraic_gf, bool to_mesh=true)
Add an algebraic ghosting functor to this problem's DofMaps.
void addCouplingGhostingFunctor (GhostingFunctor &coupling_gf, bool to_mesh=true)
Add a coupling functor to this problem's DofMaps.
void removeAlgebraicGhostingFunctor (GhostingFunctor &algebraic_gf)
Remove an algebraic ghosting functor from this problem's DofMaps.
void removeCouplingGhostingFunctor (GhostingFunctor &coupling_gf)
Remove a coupling ghosting functor from this problem's DofMaps.
virtual void automaticScaling (bool automatic_scaling)
Automatic scaling setter.
bool automaticScaling () const
Automatic scaling getter.
void hasScalingVector ()
Tells this problem that assembly involves a scaling vector.
void clearAllDofIndices ()
Clear dof indices from variables in nl and aux systems.
template<typename T >
const Moose::Functor< T > & getFunctor (const std::string &name, const THREAD_ID tid, const std::string &requestor_name, bool requestor_is_ad)
bool hasFunctor (const std::string &name, const THREAD_ID tid) const
checks whether we have a functor corresponding to name on the thread id tid
template<typename T >
bool hasFunctorWithType (const std::string &name, const THREAD_ID tid) const
checks whether we have a functor of type T corresponding to name on the thread id tid
template<typename T >
void addFunctor (const std::string &name, const Moose::FunctorBase< T > &functor, const THREAD_ID tid)
add a functor to the problem functor container
template<typename T , typename PolymorphicLambda >
const Moose::FunctorBase< T > & addPiecewiseByBlockLambdaFunctor (const std::string &name, PolymorphicLambda my_lammy, const std::set< ExecFlagType > &clearance_schedule, const MooseMesh &mesh, const std::set< SubdomainID > &block_ids, const THREAD_ID tid)
Add a functor that has block-wise lambda definitions, e.g.
void setFunctorOutput (bool set_output)
Setter for debug functor output.
template<typename T >
void registerUnfilledFunctorRequest (T *functor_interface, const std::string &functor_name, const THREAD_ID tid)
Register an unfulfilled functor request.
void reinitFVFace (const THREAD_ID tid, const FaceInfo &fi)
reinitialize the finite volume assembly data for the provided face and thread
virtual void doingPRefinement (bool doing_p_refinement, const MultiMooseEnum &disable_p_refinement_for_families)
Indicate whether the kind of adaptivity we're doing is p-refinement.
bool doingPRefinement () const
bool havePRefinement () const
Query whether p-refinement has been requested at any point during the simulation.
template<typename T >
MooseVariableFEBase & getVariableHelper (const THREAD_ID tid, const std::string &var_name, Moose::VarKindType expected_var_type, Moose::VarFieldType expected_var_field_type, const std::vector< T > &nls, const SystemBase &aux) const
void _setCLIOption ()
For Internal Use.
virtual void terminateSolve ()
Allow objects to request clean termination of the solve.
virtual bool isSolveTerminationRequested () const
Check of termination has been requested.
const ConsoleStream & console () const
Return console handle.
virtual bool enabled () const
Return the enabled status of the object.
MooseApp & getMooseApp () const
Get the MooseApp this class is associated with.
const std::string & type () const
Get the type of this class.
virtual const std::string & name () const
Get the name of the class.
std::string typeAndName () const
Get the class's combined type and name; useful in error handling.
MooseObjectParameterName uniqueParameterName (const std::string &parameter_name) const
The unique parameter name of a valid parameter of this object for accessing parameter controls.
const InputParameters & parameters () const
Get the parameters of the object.
MooseObjectName uniqueName () const
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
template<typename T >
const T & getParam (const std::string &name) const
Retrieve a parameter for the object.
template<typename T1 , typename T2 >
std::vector< std::pair< T1, T2 > > getParam (const std::string &param1, const std::string &param2) const
Retrieve two parameters and provide pair of parameters for the object.
template<typename T >
const T & getRenamedParam (const std::string &old_name, const std::string &new_name) const
Retrieve a renamed parameter for the object.
template<typename T >
T getCheckedPointerParam (const std::string &name, const std::string &error_string="") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
bool isParamValid (const std::string &name) const
Test if the supplied parameter is valid.
bool isParamSetByUser (const std::string &nm) const
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
template<typename... Args>
void paramError (const std::string &param, Args... args) const
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramWarning (const std::string &param, Args... args) const
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramInfo (const std::string &param, Args... args) const
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
std::string objectErrorPrefix (const std::string &error_type) const
A descriptive prefix for errors for an object.
void connectControllableParams (const std::string &parameter, const std::string &object_type, const std::string &object_name, const std::string &object_parameter) const
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
template<typename... Args>
void mooseError (Args &&... args) const
Emits an error prefixed with object name and type.
template<typename... Args>
void mooseErrorNonPrefixed (Args &&... args) const
Emits an error without the prefixing included in mooseError().
template<typename... Args>
void mooseWarning (Args &&... args) const
Emits a warning prefixed with object name and type.
template<typename... Args>
void mooseWarningNonPrefixed (Args &&... args) const
Emits a warning without the prefixing included in mooseWarning().
template<typename... Args>
void mooseDeprecated (Args &&... args) const
template<typename... Args>
void mooseInfo (Args &&... args) const
std::string errorPrefix (const std::string &error_type) const
A descriptive prefix for errors for this object:
std::string getDataFileName (const std::string &param) const
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
std::string getDataFileNameByName (const std::string &name, const std::string *param=nullptr) const
Returns the path of a data file for a given relative file path.
PerfGraph & perfGraph ()
Get the PerfGraph.
Static Public Member Functions
static InputParameters validParams ()
static std::string arrayVariableComponent (const std::string &var_name, unsigned int i)
Returns the variable name of a component of an array variable.
static void selectVectorTagsFromSystem (const SystemBase &system, const std::vector< VectorTag > &input_vector_tags, std::set< TagID > &selected_tags)
Select the vector tags which belong to a specific system.
Public Attributes
std::map< std::string, std::vector< dof_id_type > > _var_dof_map
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Member Functions
template<typename T >
MooseVariableFieldBase & getVariableHelper (const THREAD_ID tid, const std::string &var_name, Moose::VarKindType expected_var_type, Moose::VarFieldType expected_var_field_type, const std::vector< T > &nls, const SystemBase &aux) const
Helper function called by getVariable that handles the logic for checking whether Variables of the requested type are available.
bool verifyVectorTags () const
Verify the integrity of _vector_tags and _typed_vector_tags.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level) const
Call to register a named section for timing.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level, const std::string &live_message, const bool print_dots=true) const
Call to register a named section for timing.
std::string timedSectionName (const std::string &section_name) const
Protected Attributes
FEProblemBase & _mproblem
MooseMesh & _mesh
EquationSystems _eq
MooseMesh & _ref_mesh
reference mesh
std::vector< std::string > _displacements
std::vector< std::unique_ptr< DisplacedSystem > > _displaced_nl
std::unique_ptr< DisplacedSystem > _displaced_aux
std::vector< const NumericVector< Number > * > _nl_solution
The nonlinear system solutions.
const NumericVector< Number > * _aux_solution
The auxiliary system solution.
std::vector< std::vector< std::unique_ptr< Assembly > > > _assembly
GeometricSearchData _geometric_search_data
std::map< TagName, TagID > _matrix_tag_name_to_tag_id
The currently declared tags.
std::map< TagID, TagName > _matrix_tag_id_to_tag_name
Reverse map.
Factory & _factory
The Factory for building objects.
std::vector< CouplingMatrix > _nonlocal_cm
DiracKernelInfo _dirac_kernel_info
nonlocal coupling matrix;
std::map< SubdomainID, std::set< std::string > > _map_block_material_props
Map of material properties (block_id -> list of properties)
std::map< BoundaryID, std::set< std::string > > _map_boundary_material_props
Map for boundary material properties (boundary_id -> list of properties)
std::map< SubdomainID, std::set< MaterialPropertyName > > _zero_block_material_props
Set of properties returned as zero properties.
std::map< BoundaryID, std::set< MaterialPropertyName > > _zero_boundary_material_props
std::set< std::string > _material_property_requested
set containing all material property names that have been requested by getMaterialProperty*
std::vector< std::set< MooseVariableFieldBase * > > _active_elemental_moose_variables
This is the set of MooseVariableFieldBase that will actually get reinited by a call to reinit(elem)
std::vector< unsigned int > _has_active_elemental_moose_variables
Whether or not there is currently a list of active elemental moose variables.
std::vector< std::set< unsigned int > > _active_material_property_ids
Set of material property ids that determine whether materials get reinited.
std::vector< std::set< TagID > > _active_fe_var_coupleable_matrix_tags
std::vector< std::set< TagID > > _active_fe_var_coupleable_vector_tags
std::vector< std::set< TagID > > _active_sc_var_coupleable_matrix_tags
std::vector< std::set< TagID > > _active_sc_var_coupleable_vector_tags
bool _requires_nonlocal_coupling
nonlocal coupling requirement flag
bool _default_ghosting
Whether or not to use default libMesh coupling.
std::set< dof_id_type > _ghosted_elems
Elements that should have Dofs ghosted to the local processor.
bool _currently_computing_jacobian
Flag to determine whether the problem is currently computing Jacobian.
bool _currently_computing_residual_and_jacobian
Flag to determine whether the problem is currently computing the residual and Jacobian.
bool _computing_nonlinear_residual
Whether the non-linear residual is being evaluated.
bool _currently_computing_residual
Whether the residual is being evaluated.
bool _safe_access_tagged_matrices
Is it safe to retrieve data from tagged matrices.
bool _safe_access_tagged_vectors
Is it safe to retrieve data from tagged vectors.
bool _have_ad_objects
AD flag indicating whether any AD objects have been added.
bool _cli_option_found
True if the CLI option is found.
bool _color_output
True if we're going to attempt to write color output.
bool _termination_requested
True if termination of the solve has been requested.
const bool & _enabled
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
MooseApp & _app
The MOOSE application this is associated with.
const std::string & _type
The type of this class.
const std::string & _name
The name of this class, reference to value stored in InputParameters.
const InputParameters & _pars
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
ActionFactory & _action_factory
Builds Actions.
MooseApp & _pg_moose_app
The MooseApp that owns the PerfGraph.
const std::string _prefix
A prefix to use for all sections.
std::map< SubdomainID, std::multimap< std::string, std::string > > _map_block_material_props_check
Data structures of the requested material properties.
std::map< BoundaryID, std::multimap< std::string, std::string > > _map_boundary_material_props_check
Private Types
enum class TrueFunctorIs { UNSET , NONAD , AD }
Private Member Functions
std::pair< bool, unsigned int > determineNonlinearSystem (const std::string &var_name, bool error_if_not_found=false) const override
void cloneAlgebraicGhostingFunctor (GhostingFunctor &algebraic_gf, bool to_mesh=true)
Creates (n_sys - 1) clones of the provided algebraic ghosting functor (corresponding to the nonlinear system algebraic ghosting functor), initializes the clone with the appropriate DofMap, and then adds the clone to said DofMap.
void cloneCouplingGhostingFunctor (GhostingFunctor &coupling_gf, bool to_mesh=true)
Creates (n_sys - 1) clones of the provided coupling ghosting functor (corresponding to the nonlinear system coupling ghosting functor), initializes the clone with the appropriate DofMap, and then adds the clone to said DofMap.
void showFunctors () const
Lists all functors in the problem.
void showFunctorRequestors () const
Lists all functors and all the objects that requested them.
template<typename... Args>
std::string paramErrorMsg (const std::string &param, Args... args) const
std::string restrictionSubdomainCheckName (SubdomainID check_id)
Helper functions for checking MaterialProperties.
std::string restrictionBoundaryCheckName (BoundaryID check_id)
Private Attributes
std::vector< std::multimap< std::string, std::tuple< TrueFunctorIs, std::unique_ptr< Moose::FunctorEnvelopeBase >, std::unique_ptr< Moose::FunctorEnvelopeBase > > > > _functors
A container holding pointers to all the functors in our problem.
std::vector< std::map< std::string, std::unique_ptr< Moose::FunctorAbstract > > > _pbblf_functors
Container to hold PiecewiseByBlockLambdaFunctors.
std::map< std::string, std::set< std::string > > _functor_to_requestors
The requestors of functors where the key is the prop name and the value is a set of names of requestors.
std::vector< std::multimap< std::string, std::pair< bool, bool > > > _functor_to_request_info
A multimap (for each thread) from unfilled functor requests to whether the requests were for AD functors and whether the requestor was an AD object.
bool _output_functors
Whether to output a list of the functors used and requested (currently only at initialSetup)
std::vector< VectorTag > _vector_tags
The declared vector tags.
std::vector< std::vector< VectorTag > > _typed_vector_tags
The vector tags associated with each VectorTagType This is kept separate from _vector_tags for quick access into typed vector tags in places where we don't want to build a new vector every call (like in residual evaluation)
std::map< TagName, TagID > _vector_tags_name_map
Map of vector tag TagName to TagID.
std::map< MooseObjectName, std::set< std::string > > _consumed_material_properties
std::unordered_map< GhostingFunctor *, std::vector< std::shared_ptr< GhostingFunctor > > > _root_alg_gf_to_sys_clones
A map from a root algebraic ghosting functor, e.g.
std::unordered_map< GhostingFunctor *, std::vector< std::shared_ptr< GhostingFunctor > > > _root_coupling_gf_to_sys_clones
A map from a root coupling ghosting functor, e.g.
bool _have_p_refinement
Whether p-refinement has been requested at any point during the simulation.
const MooseBase *const _moose_base
The MooseBase object that inherits this class.
const MooseObject & _parent
Friends
class UpdateDisplacedMeshThread
class Restartable
Detailed Description
Definition at line 35 of file DisplacedProblem.h.
Member Enumeration Documentation
TrueFunctorIs
enum class SubProblem::TrueFunctorIs strong private inherited
Enumerator
UNSET
NONAD
AD
Definition at line 1053 of file SubProblem.h.
  {
    UNSET,
    NONAD,
    AD
  };
Constructor & Destructor Documentation
DisplacedProblem() [1/2]
DisplacedProblem::DisplacedProblem (DisplacedProblem &&) delete
DisplacedProblem() [2/2]
DisplacedProblem::DisplacedProblem (const InputParameters & parameters)
Definition at line 41 of file DisplacedProblem.C.
  : SubProblem(parameters),
    _mproblem(parameters.have_parameter<FEProblemBase *>("_fe_problem_base")
                  ? *getParam<FEProblemBase *>("_fe_problem_base")
                  : *getParam<FEProblem *>("_fe_problem")),
    _mesh(*getParam<MooseMesh *>("mesh")),
    _eq(_mesh),
    _ref_mesh(_mproblem.mesh()),
    _displacements(getParam<std::vector<std::string>>("displacements")),
    _geometric_search_data(*this, _mesh)
{
  // TODO: Move newAssemblyArray further up to SubProblem so that we can use it here
  unsigned int n_threads = libMesh::n_threads();
  _assembly.resize(n_threads);
  for (const auto nl_sys_num : make_range(_mproblem.numNonlinearSystems()))
  {
    _displaced_nl.emplace_back(std::make_unique<DisplacedSystem>(
        *this,
        _mproblem.getNonlinearSystemBase(nl_sys_num),
        "displaced_" + _mproblem.getNonlinearSystemBase(nl_sys_num).name() + "_" +
            std::to_string(nl_sys_num),
        Moose::VAR_NONLINEAR));
    auto & displaced_nl = _displaced_nl.back();
    for (unsigned int i = 0; i < n_threads; ++i)
      _assembly[i].emplace_back(std::make_unique<Assembly>(*displaced_nl, i));
    displaced_nl->addTimeIntegrator(
        _mproblem.getNonlinearSystemBase(nl_sys_num).getSharedTimeIntegrator());
  }
  _nl_solution.resize(_displaced_nl.size(), nullptr);
  _displaced_aux =
      std::make_unique<DisplacedSystem>(*this,
                                        _mproblem.getAuxiliarySystem(),
                                        "displaced_" + _mproblem.getAuxiliarySystem().name(),
                                        Moose::VAR_AUXILIARY);
  _displaced_aux->addTimeIntegrator(_mproblem.getAuxiliarySystem().getSharedTimeIntegrator());
  // // Generally speaking, the mesh is prepared for use, and consequently remote elements are deleted
  // // well before our Problem(s) are constructed. Historically, in MooseMesh we have a bunch of
  // // needs_prepare type flags that make it so we never call prepare_for_use (and consequently
  // // delete_remote_elements) again. So the below line, historically, has had no impact. HOWEVER:
  // // I've added some code in SetupMeshCompleteAction for deleting remote elements post
  // // EquationSystems::init. If I execute that code without default ghosting, then I get > 40 MOOSE
  // // test failures, so we clearly have some simulations that are not yet covered properly by
  // // relationship managers. Until that is resolved, I am going to retain default geometric ghosting
  // if (!_default_ghosting)
  //   _mesh.getMesh().remove_ghosting_functor(_mesh.getMesh().default_ghosting());
  automaticScaling(_mproblem.automaticScaling());
  _mesh.setCoordData(_ref_mesh);
}
~DisplacedProblem()
DisplacedProblem::~DisplacedProblem () default
Member Function Documentation
_setCLIOption()
void Problem::_setCLIOption () inline inherited
For Internal Use.
Definition at line 32 of file Problem.h.
{ _cli_option_found = true; }
addAlgebraicGhostingFunctor()
void SubProblem::addAlgebraicGhostingFunctor (GhostingFunctor & algebraic_gf, bool to_mesh = true) inherited
Add an algebraic ghosting functor to this problem's DofMaps.
Definition at line 975 of file SubProblem.C.
{
  EquationSystems & eq = es();
  const auto n_sys = eq.n_systems();
  if (!n_sys)
    return;
  eq.get_system(0).get_dof_map().add_algebraic_ghosting_functor(algebraic_gf, to_mesh);
  cloneAlgebraicGhostingFunctor(algebraic_gf, to_mesh);
}
addAuxVariable()
void DisplacedProblem::addAuxVariable (const std::string & var_type, const std::string & name, InputParameters & parameters) virtual
Definition at line 570 of file DisplacedProblem.C.
{
  _displaced_aux->addVariable(var_type, name, parameters);
}
addCachedJacobian()
void SubProblem::addCachedJacobian (const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 1273 of file SubProblem.C.
{
  assembly(tid, currentNlSysNum()).addCachedJacobian(Assembly::GlobalDataKey{});
}
Referenced by FEProblemBase::addCachedJacobian().
addCachedResidual()
void SubProblem::addCachedResidual (const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 1252 of file SubProblem.C.
{
  assembly(tid, currentNlSysNum())
      .addCachedResiduals(Assembly::GlobalDataKey{}, currentResidualVectorTags());
}
Referenced by FEProblemBase::addCachedResidual().
addCachedResidualDirectly()
void DisplacedProblem::addCachedResidualDirectly (NumericVector< Number > & residual, const THREAD_ID tid) virtual
Definition at line 938 of file DisplacedProblem.C.
{
  if (_displaced_nl[currentNlSysNum()]->hasVector(
          _displaced_nl[currentNlSysNum()]->timeVectorTag()))
    _assembly[tid][currentNlSysNum()]->addCachedResidualDirectly(
        residual,
        Assembly::GlobalDataKey{},
        getVectorTag(_displaced_nl[currentNlSysNum()]->timeVectorTag()));
  if (_displaced_nl[currentNlSysNum()]->hasVector(
          _displaced_nl[currentNlSysNum()]->nonTimeVectorTag()))
    _assembly[tid][currentNlSysNum()]->addCachedResidualDirectly(
        residual,
        Assembly::GlobalDataKey{},
        getVectorTag(_displaced_nl[currentNlSysNum()]->nonTimeVectorTag()));
  // We do this because by adding the cached residual directly, we cannot ensure that all of the
  // cached residuals are emptied after only the two add calls above
  _assembly[tid][currentNlSysNum()]->clearCachedResiduals(Assembly::GlobalDataKey{});
}
addConsumedPropertyName()
void SubProblem::addConsumedPropertyName (const MooseObjectName & obj_name, const std::string & prop_name) inherited
Helper for tracking the object that is consuming a property for MaterialPropertyDebugOutput.
Definition at line 695 of file SubProblem.C.
{
  _consumed_material_properties[obj_name].insert(prop_name);
}
Referenced by MaterialPropertyInterface::addConsumedPropertyName().
addCouplingGhostingFunctor()
void SubProblem::addCouplingGhostingFunctor (GhostingFunctor & coupling_gf, bool to_mesh = true) inherited
Add a coupling functor to this problem's DofMaps.
Definition at line 1008 of file SubProblem.C.
{
  const auto num_nl_sys = numNonlinearSystems();
  if (!num_nl_sys)
    return;
  systemBaseNonlinear(0).system().get_dof_map().add_coupling_functor(coupling_gf, to_mesh);
  cloneCouplingGhostingFunctor(coupling_gf, to_mesh);
}
addFunctor()
template<typename T > void SubProblem::addFunctor (const std::string & name, const Moose::FunctorBase< T > & functor, const THREAD_ID tid) inherited
add a functor to the problem functor container
Definition at line 1286 of file SubProblem.h.
{
  constexpr bool added_functor_is_ad =
      !std::is_same<T, typename MetaPhysicL::RawType<T>::value_type>::value;
  mooseAssert(tid < _functors.size(), "Too large a thread ID");
  auto & functor_to_request_info = _functor_to_request_info[tid];
  auto & functors = _functors[tid];
  auto it = functors.find("wraps_" + name);
  if (it != functors.end())
  {
    // We have this functor already. If it's a null functor, we want to replace it with the valid
    // functor we have now. If it's not then we'll add a new entry into the multimap and then we'll
    // error later if a user requests a functor because their request is ambiguous. This is the
    // reason that the functors container is a multimap: for nice error messages
    auto * const existing_wrapper_base =
        added_functor_is_ad ? std::get<2>(it->second).get() : std::get<1>(it->second).get();
    auto * const existing_wrapper = dynamic_cast<Moose::Functor<T> *>(existing_wrapper_base);
    if (existing_wrapper && existing_wrapper->template wrapsType<Moose::NullFunctor<T>>())
    {
      // Sanity check
      auto [request_info_it, request_info_end_it] = functor_to_request_info.equal_range(name);
      if (request_info_it == request_info_end_it)
        mooseError("We are wrapping a NullFunctor but we don't have any unfilled functor request "
                   "info. This doesn't make sense.");
      // Check for valid requests
      while (request_info_it != request_info_end_it)
      {
        auto & [requested_functor_is_ad, requestor_is_ad] = request_info_it->second;
        if (!requested_functor_is_ad && requestor_is_ad && added_functor_is_ad)
          mooseError("We are requesting a non-AD functor from an AD object, but the true functor "
                     "is AD. This means we could be dropping important derivatives. We will not "
                     "allow this");
        // We're going to eventually check whether we've fulfilled all functor requests and our
        // check will be that the multimap is empty. This request is fulfilled, so erase it from the
        // map now
        request_info_it = functor_to_request_info.erase(request_info_it);
      }
      // Ok we didn't have the functor before, so we will add it now
      std::get<0>(it->second) =
          added_functor_is_ad ? SubProblem::TrueFunctorIs::AD : SubProblem::TrueFunctorIs::NONAD;
      existing_wrapper->assign(functor);
      // Finally we create the non-AD or AD complement of the just added functor
      if constexpr (added_functor_is_ad)
      {
        typedef typename MetaPhysicL::RawType<T>::value_type NonADType;
        auto * const existing_non_ad_wrapper_base = std::get<1>(it->second).get();
        auto * const existing_non_ad_wrapper =
            dynamic_cast<Moose::Functor<NonADType> *>(existing_non_ad_wrapper_base);
        mooseAssert(existing_non_ad_wrapper->template wrapsType<Moose::NullFunctor<NonADType>>(),
                    "Both members of pair should have been wrapping a NullFunctor");
        existing_non_ad_wrapper->assign(
            std::make_unique<Moose::RawValueFunctor<NonADType>>(functor));
      }
      else
      {
        typedef typename Moose::ADType<T>::type ADType;
        auto * const existing_ad_wrapper_base = std::get<2>(it->second).get();
        auto * const existing_ad_wrapper =
            dynamic_cast<Moose::Functor<ADType> *>(existing_ad_wrapper_base);
        mooseAssert(existing_ad_wrapper->template wrapsType<Moose::NullFunctor<ADType>>(),
                    "Both members of pair should have been wrapping a NullFunctor");
        existing_ad_wrapper->assign(std::make_unique<Moose::ADWrapperFunctor<ADType>>(functor));
      }
      return;
    }
  }
  // We are a new functor, create the opposite ADType one and store it with other functors
  if constexpr (added_functor_is_ad)
  {
    typedef typename MetaPhysicL::RawType<T>::value_type NonADType;
    auto new_non_ad_wrapper = std::make_unique<Moose::Functor<NonADType>>(
        std::make_unique<Moose::RawValueFunctor<NonADType>>(functor));
    auto new_ad_wrapper = std::make_unique<Moose::Functor<T>>(functor);
    _functors[tid].emplace("wraps_" + name,
                           std::make_tuple(SubProblem::TrueFunctorIs::AD,
                                           std::move(new_non_ad_wrapper),
                                           std::move(new_ad_wrapper)));
  }
  else
  {
    typedef typename Moose::ADType<T>::type ADType;
    auto new_non_ad_wrapper = std::make_unique<Moose::Functor<T>>((functor));
    auto new_ad_wrapper = std::make_unique<Moose::Functor<ADType>>(
        std::make_unique<Moose::ADWrapperFunctor<ADType>>(functor));
    _functors[tid].emplace("wraps_" + name,
                           std::make_tuple(SubProblem::TrueFunctorIs::NONAD,
                                           std::move(new_non_ad_wrapper),
                                           std::move(new_ad_wrapper)));
  }
}
Referenced by FEProblemBase::addFunction(), SubProblem::addPiecewiseByBlockLambdaFunctor(), FEProblemBase::addUserObject(), and SystemBase::addVariable().
addGhostedBoundary()
void DisplacedProblem::addGhostedBoundary (BoundaryID boundary_id) override virtual
Will make sure that all necessary elements from boundary_id are ghosted to this processor.
Parameters
boundary_id Boundary ID
Implements SubProblem.
Definition at line 1120 of file DisplacedProblem.C.
{
  _mproblem.addGhostedBoundary(boundary_id);
}
addGhostedElem()
void DisplacedProblem::addGhostedElem (dof_id_type elem_id) override virtual
Will make sure that all dofs connected to elem_id are ghosted to this processor.
Implements SubProblem.
Definition at line 1114 of file DisplacedProblem.C.
{
  _mproblem.addGhostedElem(elem_id);
}
addJacobian()
void DisplacedProblem::addJacobian (const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 978 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->addJacobian(Assembly::GlobalDataKey{});
}
addJacobianBlockNonlocal()
void DisplacedProblem::addJacobianBlockNonlocal (SparseMatrix< Number > & jacobian, unsigned int ivar, unsigned int jvar, const DofMap & dof_map, const std::vector< dof_id_type > & idof_indices, const std::vector< dof_id_type > & jdof_indices, const std::set< TagID > & tags, const THREAD_ID tid)
Definition at line 1027 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->addJacobianBlockNonlocalTags(
      jacobian, ivar, jvar, dof_map, idof_indices, jdof_indices, Assembly::GlobalDataKey{}, tags);
}
addJacobianBlockTags()
void DisplacedProblem::addJacobianBlockTags (SparseMatrix< Number > & jacobian, unsigned int ivar, unsigned int jvar, const DofMap & dof_map, std::vector< dof_id_type > & dof_indices, const std::set< TagID > & tags, const THREAD_ID tid) virtual
Definition at line 1014 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->addJacobianBlockTags(
      jacobian, ivar, jvar, dof_map, dof_indices, Assembly::GlobalDataKey{}, tags);
}
addJacobianLowerD()
void DisplacedProblem::addJacobianLowerD (const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 1002 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->addJacobianLowerD(Assembly::GlobalDataKey{});
}
addJacobianNeighbor() [1/2]
void DisplacedProblem::addJacobianNeighbor (const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 990 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->addJacobianNeighbor(Assembly::GlobalDataKey{});
}
addJacobianNeighbor() [2/2]
void DisplacedProblem::addJacobianNeighbor (SparseMatrix< Number > & jacobian, unsigned int ivar, unsigned int jvar, const DofMap & dof_map, std::vector< dof_id_type > & dof_indices, std::vector< dof_id_type > & neighbor_dof_indices, const std::set< TagID > & tags, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 1041 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->addJacobianNeighborTags(jacobian,
                                                             ivar,
                                                             jvar,
                                                             dof_map,
                                                             dof_indices,
                                                             neighbor_dof_indices,
                                                             Assembly::GlobalDataKey{},
                                                             tags);
}
addJacobianNeighborLowerD()
void DisplacedProblem::addJacobianNeighborLowerD (const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 996 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->addJacobianNeighborLowerD(Assembly::GlobalDataKey{});
}
addJacobianNonlocal()
void DisplacedProblem::addJacobianNonlocal (const THREAD_ID tid) virtual
Definition at line 984 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->addJacobianNonlocal(Assembly::GlobalDataKey{});
}
addMatrixTag()
TagID DisplacedProblem::addMatrixTag (TagName tag_name) override virtual
Create a Tag.
Tags can be associated with Vectors and Matrices and allow objects (such as Kernels) to arbitrarily contribute values to any set of vectors/matrics
Note: If the tag is already present then this will simply return the TagID of that Tag
Parameters
tag_name The name of the tag to create, the TagID will get automatically generated
Reimplemented from SubProblem.
Definition at line 418 of file DisplacedProblem.C.
{
  return _mproblem.addMatrixTag(tag_name);
}
addPiecewiseByBlockLambdaFunctor()
template<typename T , typename PolymorphicLambda > const Moose::FunctorBase< T > & SubProblem::addPiecewiseByBlockLambdaFunctor (const std::string & name, PolymorphicLambda my_lammy, const std::set< ExecFlagType > & clearance_schedule, const MooseMesh & mesh, const std::set< SubdomainID > & block_ids, const THREAD_ID tid) inherited
Add a functor that has block-wise lambda definitions, e.g.
the evaluations of the functor are based on a user-provided lambda expression.
Parameters
name The name of the functor to add
my_lammy The lambda expression that will be called when the functor is evaluated
clearance_schedule How often to clear functor evaluations. The default value is always, which means that the functor will be re-evaluated every time it is called. If it is something other than always, than cached values may be returned
mesh The mesh on which this functor operates
block_ids The blocks on which the lambda expression is defined
tid The thread on which the functor we are adding will run
Returns
The added functor
Definition at line 1249 of file SubProblem.h.
{
  auto & pbblf_functors = _pbblf_functors[tid];
  auto [it, first_time_added] =
      pbblf_functors.emplace(name,
                             std::make_unique<PiecewiseByBlockLambdaFunctor<T>>(
                                 name, my_lammy, clearance_schedule, mesh, block_ids));
  auto * functor = dynamic_cast<PiecewiseByBlockLambdaFunctor<T> *>(it->second.get());
  if (!functor)
  {
    if (first_time_added)
      mooseError("This should be impossible. If this was the first time we added the functor, then "
                 "the dynamic cast absolutely should have succeeded");
    else
      mooseError("Attempted to add a lambda functor with the name '",
                 name,
                 "' but another lambda functor of that name returns a different type");
  }
  if (first_time_added)
    addFunctor(name, *functor, tid);
  else
    // The functor already exists
    functor->setFunctor(mesh, block_ids, my_lammy);
  return *functor;
}
Referenced by FunctorMaterial::addFunctorPropertyByBlocks().
addResidual()
void DisplacedProblem::addResidual (const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 917 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->addResidual(Assembly::GlobalDataKey{},
                                                 currentResidualVectorTags());
}
addResidualLower()
void DisplacedProblem::addResidualLower (const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 931 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->addResidualLower(Assembly::GlobalDataKey{},
                                                      currentResidualVectorTags());
}
addResidualNeighbor()
void DisplacedProblem::addResidualNeighbor (const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 924 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->addResidualNeighbor(Assembly::GlobalDataKey{},
                                                         currentResidualVectorTags());
}
addVariable()
void DisplacedProblem::addVariable (const std::string & var_type, const std::string & name, InputParameters & parameters, unsigned int nl_system_number) virtual
Definition at line 561 of file DisplacedProblem.C.
{
  _displaced_nl[nl_system_number]->addVariable(var_type, name, parameters);
}
addVectorTag()
TagID DisplacedProblem::addVectorTag (const TagName & tag_name, const Moose::VectorTagType type = Moose::VECTOR_TAG_RESIDUAL) override virtual
Create a Tag.
Tags can be associated with Vectors and Matrices and allow objects (such as Kernels) to arbitrarily contribute values to any set of vectors/matrics
Note: If the tag is already present then this will simply return the TagID of that Tag, but the type must be the same.
Parameters
tag_name The name of the tag to create, the TagID will get automatically generated
type The type of the tag
Reimplemented from SubProblem.
Definition at line 363 of file DisplacedProblem.C.
{
  return _mproblem.addVectorTag(tag_name, type);
}
arrayVariableComponent()
static std::string SubProblem::arrayVariableComponent (const std::string & var_name, unsigned int i) inline static inherited
Returns the variable name of a component of an array variable.
Definition at line 261 of file SubProblem.h.
  {
    return var_name + "_" + std::to_string(i);
  }
Referenced by SystemBase::addVariable(), MooseVariableFieldBase::componentName(), SystemBase::copyVars(), DMMooseSetVariables(), AdvancedOutput::initAvailableLists(), and AdvancedOutput::initShowHideLists().
assembly() [1/2]
const Assembly & DisplacedProblem::assembly (const THREAD_ID tid, const unsigned int nl_sys_num) const override virtual
Implements SubProblem.
Definition at line 1287 of file DisplacedProblem.C.
{
  mooseAssert(tid < _assembly.size(), "Assembly objects not initialized");
  mooseAssert(nl_sys_num < _assembly[tid].size(),
              "Nonlinear system number larger than the assembly container size");
  return *_assembly[tid][nl_sys_num];
}
assembly() [2/2]
Assembly & DisplacedProblem::assembly (const THREAD_ID tid, const unsigned int nl_sys_num) override virtual
Implements SubProblem.
Definition at line 1278 of file DisplacedProblem.C.
{
  mooseAssert(tid < _assembly.size(), "Assembly objects not initialized");
  mooseAssert(nl_sys_num < _assembly[tid].size(),
              "Nonlinear system number larger than the assembly container size");
  return *_assembly[tid][nl_sys_num];
}
Referenced by setCurrentSubdomainID(), and setNeighborSubdomainID().
automaticScaling() [1/2]
bool SubProblem::automaticScaling () const inherited
Automatic scaling getter.
Returns
A boolean representing whether we are performing automatic scaling
Definition at line 1108 of file SubProblem.C.
{
  // Currently going to assume that we are applying or not applying automatic scaling consistently
  // across nonlinear systems
  return systemBaseNonlinear(0).automaticScaling();
}
Referenced by FEProblemBase::automaticScaling(), and DisplacedProblem().
automaticScaling() [2/2]
void SubProblem::automaticScaling (bool automatic_scaling) virtual inherited
Automatic scaling setter.
Parameters
automatic_scaling A boolean representing whether we are performing automatic scaling
Reimplemented in FEProblemBase, and FEProblemBase.
Definition at line 1101 of file SubProblem.C.
{
  for (const auto nl_sys_num : make_range(numNonlinearSystems()))
    systemBaseNonlinear(nl_sys_num).automaticScaling(automatic_scaling);
}
Referenced by MooseVariableBase::initialSetup().
auxSys()
DisplacedSystem & DisplacedProblem::auxSys () inline
Definition at line 57 of file DisplacedProblem.h.
{ return *_displaced_aux; }
bumpAllQRuleOrder()
void DisplacedProblem::bumpAllQRuleOrder (Order order, SubdomainID block)
Definition at line 135 of file DisplacedProblem.C.
{
  for (unsigned int tid = 0; tid < libMesh::n_threads(); ++tid)
    for (const auto nl_sys_num : index_range(_assembly[tid]))
      _assembly[tid][nl_sys_num]->bumpAllQRuleOrder(order, block);
}
Referenced by bumpAllQRuleOrder().
bumpVolumeQRuleOrder()
void DisplacedProblem::bumpVolumeQRuleOrder (Order order, SubdomainID block)
Definition at line 127 of file DisplacedProblem.C.
{
  for (unsigned int tid = 0; tid < libMesh::n_threads(); ++tid)
    for (const auto nl_sys_num : index_range(_assembly[tid]))
      _assembly[tid][nl_sys_num]->bumpVolumeQRuleOrder(order, block);
}
Referenced by bumpVolumeQRuleOrder().
cacheJacobian()
void SubProblem::cacheJacobian (const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 1259 of file SubProblem.C.
{
  assembly(tid, currentNlSysNum()).cacheJacobian(Assembly::GlobalDataKey{});
  if (hasNonlocalCoupling())
    assembly(tid, currentNlSysNum()).cacheJacobianNonlocal(Assembly::GlobalDataKey{});
}
Referenced by FEProblemBase::cacheJacobian().
cacheJacobianNeighbor()
void SubProblem::cacheJacobianNeighbor (const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 1267 of file SubProblem.C.
{
  assembly(tid, currentNlSysNum()).cacheJacobianNeighbor(Assembly::GlobalDataKey{});
}
Referenced by FEProblemBase::cacheJacobianNeighbor().
cacheJacobianNonlocal()
void DisplacedProblem::cacheJacobianNonlocal (const THREAD_ID tid) virtual
Definition at line 1008 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->cacheJacobianNonlocal(Assembly::GlobalDataKey{});
}
cacheResidual()
void SubProblem::cacheResidual (const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 1238 of file SubProblem.C.
{
  assembly(tid, currentNlSysNum())
      .cacheResidual(Assembly::GlobalDataKey{}, currentResidualVectorTags());
}
Referenced by FEProblemBase::cacheResidual().
cacheResidualNeighbor()
void SubProblem::cacheResidualNeighbor (const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 1245 of file SubProblem.C.
{
  assembly(tid, currentNlSysNum())
      .cacheResidualNeighbor(Assembly::GlobalDataKey{}, currentResidualVectorTags());
}
Referenced by FEProblemBase::cacheResidualNeighbor().
checkBlockMatProps()
void SubProblem::checkBlockMatProps () virtual inherited
Checks block material properties integrity.
See also
FEProblemBase::checkProblemIntegrity
Definition at line 590 of file SubProblem.C.
{
  // Variable for storing all available blocks/boundaries from the mesh
  std::set<SubdomainID> all_ids(mesh().meshSubdomains());
  std::stringstream errors;
  // Loop through the properties to check
  for (const auto & check_it : _map_block_material_props_check)
  {
    // The current id for the property being checked (BoundaryID || BlockID)
    SubdomainID check_id = check_it.first;
    std::set<SubdomainID> check_ids = {check_id};
    // Loop through all the block/boundary ids
    for (const auto & id : check_ids)
    {
      // Loop through all the stored properties
      for (const auto & prop_it : check_it.second)
      {
        // Produce an error if the material property is not defined on the current block/boundary
        // and any block/boundary
        // and not is not a zero material property.
        if (_map_block_material_props[id].count(prop_it.second) == 0 &&
            _zero_block_material_props[id].count(prop_it.second) == 0)
        {
          std::string check_name = restrictionSubdomainCheckName(id);
          if (check_name.empty())
            check_name = std::to_string(id);
          errors << "Material property '" << prop_it.second << "', requested by '" << prop_it.first
                 << "' is not defined on block " << check_name << "\n";
        }
      }
    }
  }
  if (!errors.str().empty())
    mooseError(errors.str());
}
Referenced by FEProblemBase::checkProblemIntegrity().
checkBoundaryMatProps()
void SubProblem::checkBoundaryMatProps () virtual inherited
Checks boundary material properties integrity.
See also
FEProblemBase::checkProblemIntegrity
Definition at line 632 of file SubProblem.C.
{
  // Variable for storing the value for ANY_BOUNDARY_ID
  BoundaryID any_id = Moose::ANY_BOUNDARY_ID;
  // Variable for storing all available blocks/boundaries from the mesh
  std::set<BoundaryID> all_ids(mesh().getBoundaryIDs());
  std::stringstream errors;
  // Loop through the properties to check
  for (const auto & check_it : _map_boundary_material_props_check)
  {
    // The current id for the property being checked (BoundaryID || BlockID)
    BoundaryID check_id = check_it.first;
    // In the case when the material being checked has an ID is set to ANY, then loop through all
    // the possible ids and verify that the material property is defined.
    std::set<BoundaryID> check_ids{check_id};
    if (check_id == any_id)
      check_ids = all_ids;
    // Loop through all the block/boundary ids
    for (const auto & id : check_ids)
    {
      // Loop through all the stored properties
      for (const auto & prop_it : check_it.second)
      {
        // Produce an error if the material property is not defined on the current block/boundary
        // and any block/boundary
        // and not is not a zero material property.
        if (_map_boundary_material_props[id].count(prop_it.second) == 0 &&
            _map_boundary_material_props[any_id].count(prop_it.second) == 0 &&
            _zero_boundary_material_props[id].count(prop_it.second) == 0 &&
            _zero_boundary_material_props[any_id].count(prop_it.second) == 0)
        {
          std::string check_name = restrictionBoundaryCheckName(id);
          if (check_name.empty())
            check_name = std::to_string(id);
          errors << "Material property '" << prop_it.second << "', requested by '" << prop_it.first
                 << "' is not defined on boundary " << check_name << "\n";
        }
      }
    }
  }
  if (!errors.str().empty())
    mooseError(errors.str());
}
Referenced by FEProblemBase::checkProblemIntegrity().
checkNonlocalCouplingRequirement()
virtual bool SubProblem::checkNonlocalCouplingRequirement () inline virtual inherited
Definition at line 88 of file SubProblem.h.
{ return _requires_nonlocal_coupling; }
Referenced by Assembly::addCachedJacobian(), ComputeJacobianThread::compute(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), and SystemBase::prepareFace().
clearActiveElementalMooseVariables()
void SubProblem::clearActiveElementalMooseVariables (const THREAD_ID tid) virtual inherited
Clear the active elemental MooseVariableFieldBase.
If there are no active variables then they will all be reinited. Call this after finishing the computation that was using a restricted set of MooseVariableFieldBase
Parameters
tid The thread id
Reimplemented in FEProblemBase.
Definition at line 433 of file SubProblem.C.
{
  _has_active_elemental_moose_variables[tid] = 0;
  _active_elemental_moose_variables[tid].clear();
}
Referenced by FEProblemBase::clearActiveElementalMooseVariables().
clearActiveFEVariableCoupleableMatrixTags()
void SubProblem::clearActiveFEVariableCoupleableMatrixTags (const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 351 of file SubProblem.C.
{
  _active_fe_var_coupleable_matrix_tags[tid].clear();
}
Referenced by FEProblemBase::clearActiveFEVariableCoupleableMatrixTags().
clearActiveFEVariableCoupleableVectorTags()
void SubProblem::clearActiveFEVariableCoupleableVectorTags (const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 345 of file SubProblem.C.
{
  _active_fe_var_coupleable_vector_tags[tid].clear();
}
Referenced by FEProblemBase::clearActiveFEVariableCoupleableVectorTags().
clearActiveScalarVariableCoupleableMatrixTags()
void SubProblem::clearActiveScalarVariableCoupleableMatrixTags (const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 392 of file SubProblem.C.
{
  _active_sc_var_coupleable_matrix_tags[tid].clear();
}
Referenced by FEProblemBase::clearActiveScalarVariableCoupleableMatrixTags().
clearActiveScalarVariableCoupleableVectorTags()
void SubProblem::clearActiveScalarVariableCoupleableVectorTags (const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 386 of file SubProblem.C.
{
  _active_sc_var_coupleable_vector_tags[tid].clear();
}
Referenced by FEProblemBase::clearActiveScalarVariableCoupleableVectorTags().
clearAllDofIndices()
void SubProblem::clearAllDofIndices () inherited
Clear dof indices from variables in nl and aux systems.
Definition at line 1124 of file SubProblem.C.
{
  for (const auto nl_sys_num : make_range(numNonlinearSystems()))
    systemBaseNonlinear(nl_sys_num).clearAllDofIndices();
  systemBaseAuxiliary().clearAllDofIndices();
}
Referenced by FEProblemBase::solve().
clearDiracInfo()
void DisplacedProblem::clearDiracInfo () override virtual
Gets called before Dirac Kernels are asked to add the points they are supposed to be evaluated in.
Implements SubProblem.
Definition at line 911 of file DisplacedProblem.C.
{
  _dirac_kernel_info.clearPoints();
}
cloneAlgebraicGhostingFunctor()
void SubProblem::cloneAlgebraicGhostingFunctor (GhostingFunctor & algebraic_gf, bool to_mesh = true) private inherited
Creates (n_sys - 1) clones of the provided algebraic ghosting functor (corresponding to the nonlinear system algebraic ghosting functor), initializes the clone with the appropriate DofMap, and then adds the clone to said DofMap.
Parameters
algebraic_gf the (nonlinear system's) algebraic ghosting functor to clone
to_mesh whether the clone should be added to the corresponding DofMap's underlying MeshBase (the underlying MeshBase will be the same for every system held by this object's EquationSystems object)
Definition at line 953 of file SubProblem.C.
{
  EquationSystems & eq = es();
  const auto n_sys = eq.n_systems();
  auto pr = _root_alg_gf_to_sys_clones.emplace(
      &algebraic_gf, std::vector<std::shared_ptr<GhostingFunctor>>(n_sys - 1));
  mooseAssert(pr.second, "We are adding a duplicate algebraic ghosting functor");
  auto & clones_vec = pr.first->second;
  for (MooseIndex(n_sys) i = 1; i < n_sys; ++i)
  {
    DofMap & dof_map = eq.get_system(i).get_dof_map();
    std::shared_ptr<GhostingFunctor> clone_alg_gf = algebraic_gf.clone();
    std::dynamic_pointer_cast<RelationshipManager>(clone_alg_gf)
        ->init(*algebraic_gf.get_mesh(), &dof_map);
    dof_map.add_algebraic_ghosting_functor(clone_alg_gf, to_mesh);
    clones_vec[i - 1] = clone_alg_gf;
  }
}
Referenced by SubProblem::addAlgebraicGhostingFunctor().
cloneCouplingGhostingFunctor()
void SubProblem::cloneCouplingGhostingFunctor (GhostingFunctor & coupling_gf, bool to_mesh = true) private inherited
Creates (n_sys - 1) clones of the provided coupling ghosting functor (corresponding to the nonlinear system coupling ghosting functor), initializes the clone with the appropriate DofMap, and then adds the clone to said DofMap.
Parameters
coupling_gf the (nonlinear system's) coupling ghosting functor to clone
to_mesh whether the clone should be added to the corresponding DofMap's underlying MeshBase (the underlying MeshBase will be the same for every system held by this object's EquationSystems object)
Definition at line 987 of file SubProblem.C.
{
  const std::size_t num_nl_sys = numNonlinearSystems();
  auto pr = _root_coupling_gf_to_sys_clones.emplace(
      &coupling_gf, std::vector<std::shared_ptr<GhostingFunctor>>(num_nl_sys - 1));
  mooseAssert(pr.second, "We are adding a duplicate coupling functor");
  auto & clones_vec = pr.first->second;
  for (const auto i : make_range(std::size_t(1), num_nl_sys))
  {
    DofMap & dof_map = systemBaseNonlinear(i).system().get_dof_map();
    std::shared_ptr<GhostingFunctor> clone_coupling_gf = coupling_gf.clone();
    std::dynamic_pointer_cast<RelationshipManager>(clone_coupling_gf)
        ->init(*coupling_gf.get_mesh(), &dof_map);
    dof_map.add_coupling_functor(clone_coupling_gf, to_mesh);
    clones_vec[i - 1] = clone_coupling_gf;
  }
}
Referenced by SubProblem::addCouplingGhostingFunctor().
computingInitialResidual()
bool DisplacedProblem::computingInitialResidual (const unsigned int nl_sys_num) const override virtual
Returns true if the problem is in the process of computing it's initial residual.
Returns
Whether or not the problem is currently computing the initial residual.
Implements SubProblem.
Definition at line 1144 of file DisplacedProblem.C.
{
  return _mproblem.computingInitialResidual(nl_sys_num);
}
computingNonlinearResid() [1/2]
bool SubProblem::computingNonlinearResid () const inline inherited
Returns true if the problem is in the process of computing the nonlinear residual.
Definition at line 662 of file SubProblem.h.
{ return _computing_nonlinear_residual; }
computingNonlinearResid() [2/2]
virtual void SubProblem::computingNonlinearResid (const bool computing_nonlinear_residual) inline virtual inherited
Set whether or not the problem is in the process of computing the nonlinear residual.
Reimplemented in FEProblemBase, and FEProblemBase.
Definition at line 667 of file SubProblem.h.
  {
    _computing_nonlinear_residual = computing_nonlinear_residual;
  }
computingScalingJacobian()
bool DisplacedProblem::computingScalingJacobian () const final override virtual
Getter for whether we're computing the scaling jacobian.
Implements SubProblem.
Definition at line 1202 of file DisplacedProblem.C.
{
  return _mproblem.computingScalingJacobian();
}
computingScalingResidual()
bool DisplacedProblem::computingScalingResidual () const final override virtual
Getter for whether we're computing the scaling residual.
Implements SubProblem.
Definition at line 1208 of file DisplacedProblem.C.
{
  return _mproblem.computingScalingResidual();
}
connectControllableParams()
void MooseBaseParameterInterface::connectControllableParams (const std::string & parameter, const std::string & object_type, const std::string & object_name, const std::string & object_parameter) const inherited
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
Parameters
parameter Name of the controllable parameter of this action
object_type Type of the object added by this action.
object_name Name of the object added by this action.
object_parameter Name of the parameter of the object.
Definition at line 34 of file MooseBaseParameterInterface.C.
{
  MooseObjectParameterName primary_name(uniqueName(), parameter);
  const auto base_type = _factory.getValidParams(object_type).get<std::string>("_moose_base");
  MooseObjectParameterName secondary_name(base_type, object_name, object_parameter);
  _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
      primary_name, secondary_name);
  const auto & tags = _pars.get<std::vector<std::string>>("control_tags");
  for (const auto & tag : tags)
  {
    if (!tag.empty())
    {
      MooseObjectParameterName tagged_name(tag, _moose_base->name(), parameter);
      _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
          tagged_name, secondary_name);
    }
  }
}
console()
const ConsoleStream & Problem::console () const inline inherited
Return console handle.
Definition at line 48 of file Problem.h.
{ return _console; }
Referenced by Moose::SlepcSupport::mooseSlepcEPSMonitor(), ComputeDiracThread::printBlockExecutionInformation(), ComputeIndicatorThread::printBlockExecutionInformation(), ComputeMarkerThread::printBlockExecutionInformation(), ComputeUserObjectsThread::printBlockExecutionInformation(), NonlinearThread::printBlockExecutionInformation(), NonlinearThread::printBoundaryExecutionInformation(), ComputeFVInitialConditionThread::printGeneralExecutionInformation(), ComputeInitialConditionThread::printGeneralExecutionInformation(), ComputeDiracThread::printGeneralExecutionInformation(), ComputeElemDampingThread::printGeneralExecutionInformation(), ComputeIndicatorThread::printGeneralExecutionInformation(), ComputeMarkerThread::printGeneralExecutionInformation(), ComputeNodalDampingThread::printGeneralExecutionInformation(), ComputeNodalKernelBCJacobiansThread::printGeneralExecutionInformation(), ComputeNodalKernelBcsThread::printGeneralExecutionInformation(), ComputeNodalKernelJacobiansThread::printGeneralExecutionInformation(), ComputeNodalKernelsThread::printGeneralExecutionInformation(), ComputeNodalUserObjectsThread::printGeneralExecutionInformation(), ComputeUserObjectsThread::printGeneralExecutionInformation(), NonlinearThread::printGeneralExecutionInformation(), and ComputeThreadedGeneralUserObjectsThread::printGeneralExecutionInformation().
converged()
virtual bool SubProblem::converged (const unsigned int nl_sys_num) inline virtual inherited
Eventually we want to convert this virtual over to taking a nonlinear system number argument.
We will have to first convert apps to use nlConverged, and then once that is done, we can change this signature. Then we can go through the apps again and convert back to this changed API
Definition at line 101 of file SubProblem.h.
{ return nlConverged(nl_sys_num); }
Referenced by DumpObjectsProblem::addAuxVariable(), EigenExecutionerBase::inversePowerIteration(), SubProblem::nlConverged(), nlConverged(), EigenExecutionerBase::nonlinearSolve(), FEProblemSolve::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), and AB2PredictorCorrector::step().
couplingMatrix()
const CouplingMatrix * DisplacedProblem::couplingMatrix (const unsigned int nl_sys_num) const override virtual
The coupling matrix defining what blocks exist in the preconditioning matrix.
Implements SubProblem.
Definition at line 1196 of file DisplacedProblem.C.
{
  return _mproblem.couplingMatrix(nl_sys_num);
}
createQRules()
void DisplacedProblem::createQRules (QuadratureType type, Order order, Order volume_order, Order face_order, SubdomainID block, bool allow_negative_qweights = true) virtual
Definition at line 113 of file DisplacedProblem.C.
{
  for (unsigned int tid = 0; tid < libMesh::n_threads(); ++tid)
    for (const auto nl_sys_num : index_range(_assembly[tid]))
      _assembly[tid][nl_sys_num]->createQRules(
          type, order, volume_order, face_order, block, allow_negative_qweights);
}
Referenced by createQRules().
currentlyComputingJacobian()
const bool & SubProblem::currentlyComputingJacobian () const inline inherited
Returns true if the problem is in the process of computing the Jacobian.
Definition at line 639 of file SubProblem.h.
{ return _currently_computing_jacobian; };
Referenced by PenetrationLocator::detectPenetration(), CurrentDensityShapeSideUserObject::finalize(), DenomShapeSideUserObject::finalize(), NumShapeSideUserObject::finalize(), CurrentDensityShapeSideUserObject::initialize(), DenomShapeSideUserObject::initialize(), NumShapeSideUserObject::initialize(), ComputeUserObjectsThread::onBoundary(), ComputeUserObjectsThread::onElement(), FEProblemBase::prepare(), ComputeUserObjectsThread::printBlockExecutionInformation(), SubProblem::reinitElemFaceRef(), CurrentDensityShapeSideUserObject::threadJoin(), DenomShapeSideUserObject::threadJoin(), and NumShapeSideUserObject::threadJoin().
currentlyComputingResidual()
const bool & SubProblem::currentlyComputingResidual () const inline inherited
Returns true if the problem is in the process of computing the residual.
Definition at line 675 of file SubProblem.h.
{ return _currently_computing_residual; }
currentlyComputingResidualAndJacobian()
const bool & SubProblem::currentlyComputingResidualAndJacobian () const inline inherited
Returns true if the problem is in the process of computing the residual and the Jacobian.
Definition at line 1385 of file SubProblem.h.
{
  return _currently_computing_residual_and_jacobian;
}
Referenced by SubProblem::reinitElemFaceRef().
currentNlSysNum()
unsigned int DisplacedProblem::currentNlSysNum () const override virtual
Returns
the current nonlinear system number
Implements SubProblem.
Definition at line 578 of file DisplacedProblem.C.
{
  return _mproblem.currentNlSysNum();
}
Referenced by addCachedResidualDirectly(), addJacobian(), addJacobianBlockNonlocal(), addJacobianBlockTags(), addJacobianLowerD(), addJacobianNeighbor(), addJacobianNeighborLowerD(), addJacobianNonlocal(), addResidual(), addResidualLower(), addResidualNeighbor(), cacheJacobianNonlocal(), prepare(), prepareAssembly(), prepareAssemblyNeighbor(), prepareBlockNonlocal(), prepareFaceShapes(), prepareNeighborShapes(), prepareNonlocal(), prepareShapes(), reinitDirac(), reinitElemNeighborAndLowerD(), reinitOffDiagScalars(), setResidual(), and setResidualNeighbor().
currentResidualVectorTags()
const std::vector< VectorTag > & DisplacedProblem::currentResidualVectorTags () const override virtual
Return the residual vector tags we are currently computing.
Implements SubProblem.
Definition at line 1302 of file DisplacedProblem.C.
{
  return _mproblem.currentResidualVectorTags();
}
Referenced by addResidual(), addResidualLower(), and addResidualNeighbor().
customSetup()
void DisplacedProblem::customSetup (const ExecFlagType & exec_type) override virtual
Reimplemented from SubProblem.
Definition at line 1234 of file DisplacedProblem.C.
{
  SubProblem::customSetup(exec_type);
  for (auto & nl : _displaced_nl)
    nl->customSetup(exec_type);
  _displaced_aux->customSetup(exec_type);
}
defaultGhosting()
bool SubProblem::defaultGhosting () inline inherited
Whether or not the user has requested default ghosting ot be on.
Definition at line 122 of file SubProblem.h.
{ return _default_ghosting; }
Referenced by AuxiliarySystem::AuxiliarySystem(), DisplacedSystem::DisplacedSystem(), and NonlinearSystemBase::NonlinearSystemBase().
determineNonlinearSystem()
std::pair< bool, unsigned int > DisplacedProblem::determineNonlinearSystem (const std::string & var_name, bool error_if_not_found = false) const override private virtual
Returns
whether a given variable name is in the nonlinear systems (reflected the first member of the returned paired which is a boolean) and if so, what nonlinear system number it is in (the second member of the returned pair; if the variable is not in the nonlinear systems, then this will be an invalid unsigned integer)
Implements SubProblem.
Definition at line 1271 of file DisplacedProblem.C.
{
  return _mproblem.determineNonlinearSystem(var_name, error_if_not_found);
}
diracKernelInfo()
DiracKernelInfo & SubProblem::diracKernelInfo () virtual inherited
Definition at line 707 of file SubProblem.C.
{
  return _dirac_kernel_info;
}
doingPRefinement() [1/2]
bool SubProblem::doingPRefinement () const inherited
Returns
whether the kind of adaptivity we're doing is p-refinement
Definition at line 1314 of file SubProblem.C.
{
  return mesh().doingPRefinement();
}
Referenced by FEProblemBase::doingPRefinement().
doingPRefinement() [2/2]
void SubProblem::doingPRefinement (bool doing_p_refinement, const MultiMooseEnum & disable_p_refinement_for_families) virtual inherited
Indicate whether the kind of adaptivity we're doing is p-refinement.
Parameters
doing_p_refinement Whether we're doing p-refinement
disable_p_refinement_for_families Families to disable p-refinement for
Reimplemented in FEProblemBase, and FEProblemBase.
Definition at line 1279 of file SubProblem.C.
{
  mesh().doingPRefinement(doing_p_refinement);
  if (doing_p_refinement)
  {
    std::vector<FEFamily> disable_families(disable_p_refinement_for_families_enum.size());
    for (const auto i : index_range(disable_families))
      disable_families[i] =
          Utility::string_to_enum<FEFamily>(disable_p_refinement_for_families_enum[i]);
    for (const auto tid : make_range(libMesh::n_threads()))
      for (const auto s : make_range(numNonlinearSystems()))
        assembly(tid, s).havePRefinement(disable_families);
    auto & eq = es();
    for (const auto family : disable_families)
      for (const auto i : make_range(eq.n_systems()))
      {
        auto & system = eq.get_system(i);
        auto & dof_map = system.get_dof_map();
        for (const auto vg : make_range(system.n_variable_groups()))
        {
          const auto & var_group = system.variable_group(vg);
          if (var_group.type().family == family)
            dof_map.should_p_refine(vg, false);
        }
      }
    _have_p_refinement = true;
  }
}
enabled()
virtual bool MooseObject::enabled () const inline virtual inherited
Return the enabled status of the object.
Reimplemented in EigenKernel.
Definition at line 54 of file MooseObject.h.
{ return _enabled; }
Referenced by EigenKernel::enabled().
errorPrefix()
std::string MooseBaseErrorInterface::errorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for this object:
The following <error_type> occurred in the object "<name>", of type "<type>".
Definition at line 15 of file MooseBaseErrorInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the object \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseErrorInterface::mooseError(), and MooseBaseErrorInterface::mooseWarning().
es()
virtual EquationSystems & DisplacedProblem::es () inline override virtual
Implements SubProblem.
Definition at line 46 of file DisplacedProblem.h.
{ return _eq; }
Referenced by UpdateDisplacedMeshThread::init().
finalNonlinearResidual()
Real SubProblem::finalNonlinearResidual (const unsigned int nl_sys_num) const virtual inherited
Reimplemented in FEProblemBase.
Definition at line 713 of file SubProblem.C.
{
  return 0;
}
Referenced by Residual::getValue().
geomSearchData()
virtual GeometricSearchData & DisplacedProblem::geomSearchData () inline override virtual
Implements SubProblem.
Definition at line 301 of file DisplacedProblem.h.
{ return _geometric_search_data; }
getActiveElementalMooseVariables()
const std::set< MooseVariableFEBase * > & SubProblem::getActiveElementalMooseVariables (const THREAD_ID tid) const virtual inherited
Get the MOOSE variables to be reinited on each element.
Parameters
tid The thread id
Definition at line 421 of file SubProblem.C.
{
  return _active_elemental_moose_variables[tid];
}
Referenced by SystemBase::prepare(), SystemBase::prepareFace(), FEProblemBase::prepareMaterials(), and SystemBase::reinitElem().
getActiveFEVariableCoupleableMatrixTags()
const std::set< TagID > & SubProblem::getActiveFEVariableCoupleableMatrixTags (const THREAD_ID tid) const inherited
Definition at line 357 of file SubProblem.C.
{
  return _active_fe_var_coupleable_matrix_tags[tid];
}
getActiveFEVariableCoupleableVectorTags()
const std::set< TagID > & SubProblem::getActiveFEVariableCoupleableVectorTags (const THREAD_ID tid) const inherited
Definition at line 363 of file SubProblem.C.
{
  return _active_fe_var_coupleable_vector_tags[tid];
}
getActiveScalarVariableCoupleableMatrixTags()
const std::set< TagID > & SubProblem::getActiveScalarVariableCoupleableMatrixTags (const THREAD_ID tid) const inherited
Definition at line 398 of file SubProblem.C.
{
  return _active_sc_var_coupleable_matrix_tags[tid];
}
Referenced by MooseVariableScalar::reinit().
getActiveScalarVariableCoupleableVectorTags()
const std::set< TagID > & SubProblem::getActiveScalarVariableCoupleableVectorTags (const THREAD_ID tid) const inherited
Definition at line 404 of file SubProblem.C.
{
  return _active_sc_var_coupleable_vector_tags[tid];
}
getActualFieldVariable()
MooseVariableFieldBase & DisplacedProblem::getActualFieldVariable (const THREAD_ID tid, const std::string & var_name) override virtual
Returns the variable reference for requested MooseVariableField which may be in any system.
Implements SubProblem.
Definition at line 488 of file DisplacedProblem.C.
{
  for (auto & nl : _displaced_nl)
    if (nl->hasVariable(var_name))
      return nl->getActualFieldVariable<Real>(tid, var_name);
  if (_displaced_aux->hasVariable(var_name))
    return _displaced_aux->getActualFieldVariable<Real>(tid, var_name);
  mooseError("No variable with name '" + var_name + "'");
}
getArrayVariable()
ArrayMooseVariable & DisplacedProblem::getArrayVariable (const THREAD_ID tid, const std::string & var_name) override virtual
Returns the variable reference for requested ArrayMooseVariable which may be in any system.
Implements SubProblem.
Definition at line 512 of file DisplacedProblem.C.
{
  for (auto & nl : _displaced_nl)
    if (nl->hasVariable(var_name))
      return nl->getFieldVariable<RealEigenVector>(tid, var_name);
  if (_displaced_aux->hasVariable(var_name))
    return _displaced_aux->getFieldVariable<RealEigenVector>(tid, var_name);
  mooseError("No variable with name '" + var_name + "'");
}
getAxisymmetricRadialCoord()
unsigned int SubProblem::getAxisymmetricRadialCoord () const inherited
Returns the desired radial direction for RZ coordinate transformation.
Returns
The coordinate direction for the radial direction
Definition at line 761 of file SubProblem.C.
{
  return mesh().getAxisymmetricRadialCoord();
}
getCheckedPointerParam()
template<typename T > T MooseBaseParameterInterface::getCheckedPointerParam (const std::string & name, const std::string & error_string = "") const inherited
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
The template parameter must be a pointer or an error will be thrown.
Definition at line 264 of file MooseBaseParameterInterface.h.
{
  return parameters().getCheckedPointerParam<T>(name, error_string);
}
getConsumedPropertyMap()
const std::map< MooseObjectName, std::set< std::string > > & SubProblem::getConsumedPropertyMap () const inherited
Return the map that tracks the object with consumed material properties.
Definition at line 701 of file SubProblem.C.
{
  return _consumed_material_properties;
}
Referenced by MaterialPropertyDebugOutput::output().
getCoordSystem()
Moose::CoordinateSystemType SubProblem::getCoordSystem (SubdomainID sid) const inherited
Definition at line 1225 of file SubProblem.C.
{
  return mesh().getCoordSystem(sid);
}
Referenced by BlockRestrictable::getBlockCoordSystem(), MultiApp::getBoundingBox(), Assembly::reinitLowerDElem(), Assembly::reinitNeighborLowerDElem(), and Assembly::setCoordinateTransformation().
getDataFileName()
std::string DataFileInterface< MooseObject >::getDataFileName (const std::string & param) const inherited
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
relative to the input file directory
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
relative to the input file directory
Definition at line 34 of file DataFileInterface.C.
{
  {
    const auto & absolute_path = _parent.template getParam<FileName>(param);
    if (MooseUtils::checkFileReadable(absolute_path, false, false, false))
    {
      _parent.paramInfo(param, "Data file '", absolute_path, "' found relative to the input file.");
      return absolute_path;
    }
  }
  const auto & relative_path = _parent.parameters().rawParamVal(param);
  return getDataFileNameByName(relative_path, &param);
}
getDataFileNameByName()
std::string DataFileInterface< MooseObject >::getDataFileNameByName (const std::string & name, const std::string * param = nullptr) const inherited
Returns the path of a data file for a given relative file path.
This can be used for hardcoded datafile names and will search the same locations as getDataFileName. The optional param pointer can be used to turn the mooseErrors this function emits into paramErrors
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
Definition at line 42 of file DataFileInterface.C.
{
  const auto share_dir = MooseUtils::pathjoin(Moose::getExecutablePath(), "..", "share");
  if (MooseUtils::pathIsDirectory(share_dir))
  {
    const auto dirs = MooseUtils::listDir(share_dir, false);
    for (const auto & data_dir : dirs)
    {
      const auto path = MooseUtils::pathjoin(data_dir, "data", relative_path);
      if (MooseUtils::checkFileReadable(path, false, false, false))
      {
        if (param)
          _parent.paramInfo(
              *param, "Data file '", path, "' found in an installed app distribution.");
        else
          mooseInfo("Data file '", path, "' found in an installed app distribution.");
        return path;
      }
    }
  }
  for (const auto & data_dir : Registry::getRegistry().getDataFilePaths())
  {
    const auto path = MooseUtils::pathjoin(data_dir, relative_path);
    if (MooseUtils::checkFileReadable(path, false, false, false))
    {
      if (param)
        _parent.paramInfo(*param, "Data file '", path, "' found in a source repository.");
      else
        mooseInfo("Data file '", path, "' found in a source repository.");
      return path;
    }
  }
  mooseException(param ? _parent.parameters().inputLocation(*param) : _parent.name(),
                 ": Unable to find data file '",
                 relative_path,
                 "' anywhere");
}
getDiracElements()
void DisplacedProblem::getDiracElements (std::set< const Elem * > & elems) override virtual
Fills "elems" with the elements that should be looped over for Dirac Kernels.
Implements SubProblem.
Definition at line 905 of file DisplacedProblem.C.
{
  elems = _dirac_kernel_info.getElements();
}
getDisplacementVarNames()
const std::vector< std::string > & DisplacedProblem::getDisplacementVarNames () const inline
Definition at line 66 of file DisplacedProblem.h.
{ return _displacements; }
getFunctor()
template<typename T > const Moose::Functor< T > & SubProblem::getFunctor (const std::string & name, const THREAD_ID tid, const std::string & requestor_name, bool requestor_is_ad) inherited
Template Parameters
T The type that the functor will return when evaluated, e.g. ADReal or Real
Parameters
name The name of the functor to retrieve
tid The thread ID that we are retrieving the functor property for
requestor_name The name of the object that is requesting this functor property
requestor_is_ad Whether the requesting object is an AD object
Returns
a constant reference to the functor
Definition at line 1131 of file SubProblem.h.
{
  mooseAssert(tid < _functors.size(), "Too large a thread ID");
  // Log the requestor
  _functor_to_requestors["wraps_" + name].insert(requestor_name);
  constexpr bool requested_functor_is_ad =
      !std::is_same<T, typename MetaPhysicL::RawType<T>::value_type>::value;
  auto & functor_to_request_info = _functor_to_request_info[tid];
  // Get the requested functor if we already have it
  auto & functors = _functors[tid];
  if (auto find_ret = functors.find("wraps_" + name); find_ret != functors.end())
  {
    if (functors.count("wraps_" + name) > 1)
      mooseError("Attempted to get a functor with the name '",
                 name,
                 "' but multiple functors match. Make sure that you do not have functor material "
                 "properties, functions, postprocessors or variables with the same names");
    auto & [true_functor_is, non_ad_functor, ad_functor] = find_ret->second;
    auto & functor_wrapper = requested_functor_is_ad ? *ad_functor : *non_ad_functor;
    auto * const functor = dynamic_cast<Moose::Functor<T> *>(&functor_wrapper);
    if (!functor)
      mooseError("A call to SubProblem::getFunctor requested a functor named '",
                 name,
                 "' that returns the type: '",
                 libMesh::demangle(typeid(T).name()),
                 "'. However, that functor already exists and returns a different type: '",
                 functor_wrapper.returnType(),
                 "'");
    if (functor->template wrapsType<Moose::NullFunctor<T>>())
      // Store for future checking when the actual functor gets added
      functor_to_request_info.emplace(name,
                                      std::make_pair(requested_functor_is_ad, requestor_is_ad));
    else
    {
      // We already have the actual functor
      if (true_functor_is == SubProblem::TrueFunctorIs::UNSET)
        mooseError("We already have the functor; it should not be unset");
      // Check for whether this is a valid request
      if (!requested_functor_is_ad && requestor_is_ad &&
          true_functor_is == SubProblem::TrueFunctorIs::AD)
        mooseError("We are requesting a non-AD functor from an AD object, but the true functor is "
                   "AD. This "
                   "means we could be dropping important derivatives. We will not allow this");
    }
    return *functor;
  }
  // We don't have the functor yet but we could have it in the future. We'll create null functors
  // for now
  functor_to_request_info.emplace(name, std::make_pair(requested_functor_is_ad, requestor_is_ad));
  if constexpr (requested_functor_is_ad)
  {
    typedef typename MetaPhysicL::RawType<T>::value_type NonADType;
    typedef T ADType;
    auto emplace_ret =
        functors.emplace("wraps_" + name,
                         std::make_tuple(SubProblem::TrueFunctorIs::UNSET,
                                         std::make_unique<Moose::Functor<NonADType>>(
                                             std::make_unique<Moose::NullFunctor<NonADType>>()),
                                         std::make_unique<Moose::Functor<ADType>>(
                                             std::make_unique<Moose::NullFunctor<ADType>>())));
    return static_cast<Moose::Functor<T> &>(*(requested_functor_is_ad
                                                  ? std::get<2>(emplace_ret->second)
                                                  : std::get<1>(emplace_ret->second)));
  }
  else
  {
    typedef T NonADType;
    typedef typename Moose::ADType<T>::type ADType;
    auto emplace_ret =
        functors.emplace("wraps_" + name,
                         std::make_tuple(SubProblem::TrueFunctorIs::UNSET,
                                         std::make_unique<Moose::Functor<NonADType>>(
                                             std::make_unique<Moose::NullFunctor<NonADType>>()),
                                         std::make_unique<Moose::Functor<ADType>>(
                                             std::make_unique<Moose::NullFunctor<ADType>>())));
    return static_cast<Moose::Functor<T> &>(*(requested_functor_is_ad
                                                  ? std::get<2>(emplace_ret->second)
                                                  : std::get<1>(emplace_ret->second)));
  }
}
Referenced by FunctorInterface::getFunctorByName().
getLineSearch()
LineSearch * DisplacedProblem::getLineSearch () override virtual
Implements SubProblem.
Definition at line 1190 of file DisplacedProblem.C.
{
  return _mproblem.getLineSearch();
}
getMaterialPropertyBlockNames()
std::vector< SubdomainName > SubProblem::getMaterialPropertyBlockNames (const std::string & prop_name) virtual inherited
Get a vector of block id equivalences that the material property is defined on.
Definition at line 456 of file SubProblem.C.
{
  std::set<SubdomainID> blocks = getMaterialPropertyBlocks(prop_name);
  std::vector<SubdomainName> block_names;
  block_names.reserve(blocks.size());
  for (const auto & block_id : blocks)
  {
    SubdomainName name;
    name = mesh().getMesh().subdomain_name(block_id);
    if (name.empty())
    {
      std::ostringstream oss;
      oss << block_id;
      name = oss.str();
    }
    block_names.push_back(name);
  }
  return block_names;
}
Referenced by MaterialPropertyInterface::getMaterialPropertyBlockNames().
getMaterialPropertyBlocks()
std::set< SubdomainID > SubProblem::getMaterialPropertyBlocks (const std::string & prop_name) virtual inherited
Get a vector containing the block ids the material property is defined on.
Definition at line 440 of file SubProblem.C.
{
  std::set<SubdomainID> blocks;
  for (const auto & it : _map_block_material_props)
  {
    const std::set<std::string> & prop_names = it.second;
    std::set<std::string>::iterator name_it = prop_names.find(prop_name);
    if (name_it != prop_names.end())
      blocks.insert(it.first);
  }
  return blocks;
}
Referenced by SubProblem::getMaterialPropertyBlockNames(), and MaterialPropertyInterface::getMaterialPropertyBlocks().
getMaterialPropertyBoundaryIDs()
std::set< BoundaryID > SubProblem::getMaterialPropertyBoundaryIDs (const std::string & prop_name) virtual inherited
Get a vector containing the block ids the material property is defined on.
Definition at line 492 of file SubProblem.C.
{
  std::set<BoundaryID> boundaries;
  for (const auto & it : _map_boundary_material_props)
  {
    const std::set<std::string> & prop_names = it.second;
    std::set<std::string>::iterator name_it = prop_names.find(prop_name);
    if (name_it != prop_names.end())
      boundaries.insert(it.first);
  }
  return boundaries;
}
Referenced by MaterialPropertyInterface::getMaterialPropertyBoundaryIDs(), and SubProblem::getMaterialPropertyBoundaryNames().
getMaterialPropertyBoundaryNames()
std::vector< BoundaryName > SubProblem::getMaterialPropertyBoundaryNames (const std::string & prop_name) virtual inherited
Get a vector of block id equivalences that the material property is defined on.
Definition at line 508 of file SubProblem.C.
{
  std::set<BoundaryID> boundaries = getMaterialPropertyBoundaryIDs(prop_name);
  std::vector<BoundaryName> boundary_names;
  boundary_names.reserve(boundaries.size());
  const BoundaryInfo & boundary_info = mesh().getMesh().get_boundary_info();
  for (const auto & bnd_id : boundaries)
  {
    BoundaryName name;
    if (bnd_id == Moose::ANY_BOUNDARY_ID)
      name = "ANY_BOUNDARY_ID";
    else
    {
      name = boundary_info.get_sideset_name(bnd_id);
      if (name.empty())
      {
        std::ostringstream oss;
        oss << bnd_id;
        name = oss.str();
      }
    }
    boundary_names.push_back(name);
  }
  return boundary_names;
}
Referenced by MaterialPropertyInterface::getMaterialPropertyBoundaryNames().
getMatrixTagID()
TagID DisplacedProblem::getMatrixTagID (const TagName & tag_name) override virtual
Get a TagID from a TagName.
Reimplemented from SubProblem.
Definition at line 424 of file DisplacedProblem.C.
{
  return _mproblem.getMatrixTagID(tag_name);
}
getMatrixTags()
virtual std::map< TagName, TagID > & SubProblem::getMatrixTags () inline virtual inherited
Return all matrix tags in the system, where a tag is represented by a map from name to ID.
Definition at line 215 of file SubProblem.h.
{ return _matrix_tag_name_to_tag_id; }
Referenced by FEProblemBase::computeJacobian(), NonlinearSystemBase::computeJacobian(), EigenProblem::computeJacobianAB(), NonlinearSystemBase::computeJacobianBlocks(), EigenProblem::computeJacobianTag(), and FEProblemBase::computeResidualAndJacobian().
getMooseApp()
MooseApp & MooseBase::getMooseApp () const inline inherited
Get the MooseApp this class is associated with.
Definition at line 35 of file MooseBase.h.
{ return _app; }
Referenced by ReporterTransferInterface::checkHasReporterValue(), Coupleable::checkWritableVar(), MooseBaseParameterInterface::connectControllableParams(), Coupleable::Coupleable(), MortarData::createMortarInterface(), EigenProblem::doFreeNonlinearPowerIterations(), Terminator::execute(), FEProblemSolve::FEProblemSolve(), SolutionInvalidInterface::flagInvalidSolutionInternal(), MaterialPropertyInterface::MaterialPropertyInterface(), MooseVariableDataFV< OutputType >::MooseVariableDataFV(), ProgressOutput::output(), MooseBaseParameterInterface::paramError(), PetscOutputInterface::petscLinearOutput(), PetscOutputInterface::petscNonlinearOutput(), PetscOutputInterface::PetscOutputInterface(), PostprocessorInterface::postprocessorsAdded(), MultiApp::preTransfer(), Reporter::Reporter(), ReporterInterface::reportersAdded(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
getParam() [1/2]
template<typename T > const T & MooseBaseParameterInterface::getParam (const std::string & name) const inherited
Retrieve a parameter for the object.
Parameters
name The name of the parameter
Returns
The value of the parameter
Definition at line 200 of file MooseBaseParameterInterface.h.
{
  return InputParameters::getParamHelper(name, _pars, static_cast<T *>(0));
}
Referenced by AddGeneralReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddPeriodicBCAction::act(), CreateDisplacedProblemAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), ConstraintWarehouse::addObject(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), ADNodalKernel::ADNodalKernel(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), PiecewiseTabularBase::buildFromJSON(), Console::Console(), FEProblemBase::createTagSolutions(), AccumulateReporter::declareLateValues(), DerivativeParsedMaterialTempl< is_ad >::DerivativeParsedMaterialTempl(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EigenKernel::EigenKernel(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), GenericConstantRankTwoTensorTempl< is_ad >::GenericConstantRankTwoTensorTempl(), MooseApp::getCheckpointDirectories(), ExecutorInterface::getExecutor(), AdvancedOutput::init(), IterationAdaptiveDT::init(), TimeSequenceStepper::init(), AttribThread::initFrom(), AttribSysNum::initFrom(), AttribResidualObject::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), Console::initialSetup(), IterationAdaptiveDT::limitDTToPostprocessorValue(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MortarConsumerInterface::MortarConsumerInterface(), NestedDivision::NestedDivision(), ConsoleUtils::outputExecutionInformation(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedMaterialTempl< is_ad >::ParsedMaterialTempl(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), ParsedODEKernel::ParsedODEKernel(), ParsedPostprocessor::ParsedPostprocessor(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), Moose::FV::setInterpolationMethod(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), TimePeriod::TimePeriod(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and VectorOfPostprocessors::VectorOfPostprocessors().
getParam() [2/2]
template<typename T1 , typename T2 > std::vector< std::pair< T1, T2 > > MooseBaseParameterInterface::getParam (const std::string & param1, const std::string & param2) const inherited
Retrieve two parameters and provide pair of parameters for the object.
Parameters
param1 The name of first parameter
param2 The name of second parameter
Returns
Vector of pairs of first and second parameters
Definition at line 257 of file MooseBaseParameterInterface.h.
{
  return _pars.get<T1, T2>(param1, param2);
}
getRenamedParam()
template<typename T > const T & MooseBaseParameterInterface::getRenamedParam (const std::string & old_name, const std::string & new_name) const inherited
Retrieve a renamed parameter for the object.
This helper makes sure we check both names before erroring, and that only one parameter is passed to avoid silent errors
Parameters
old_name the old name for the parameter
new_name the new name for the parameter
Definition at line 207 of file MooseBaseParameterInterface.h.
{
  // this enables having a default on the new parameter but bypassing it with the old one
  // Most important: accept new parameter
  if (isParamSetByUser(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Second most: accept old parameter
  else if (isParamValid(old_name) && !isParamSetByUser(new_name))
    return InputParameters::getParamHelper(old_name, _pars, static_cast<T *>(0));
  // Third most: accept default for new parameter
  else if (isParamValid(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Refuse: no default, no value passed
  else if (!isParamValid(old_name) && !isParamValid(new_name))
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' is being retrieved without being set.\n"
               "Did you misspell it?");
  // Refuse: both old and new parameters set by user
  else
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' may not be provided alongside former parameter '" + old_name + "'");
}
getScalarVariable()
MooseVariableScalar & DisplacedProblem::getScalarVariable (const THREAD_ID tid, const std::string & var_name) override virtual
Returns the scalar variable reference from whichever system contains it.
Implements SubProblem.
Definition at line 536 of file DisplacedProblem.C.
{
  for (auto & nl : _displaced_nl)
    if (nl->hasScalarVariable(var_name))
      return nl->getScalarVariable(tid, var_name);
  if (_displaced_aux->hasScalarVariable(var_name))
    return _displaced_aux->getScalarVariable(tid, var_name);
  mooseError("No variable with name '" + var_name + "'");
}
getStandardVariable()
MooseVariable & DisplacedProblem::getStandardVariable (const THREAD_ID tid, const std::string & var_name) override virtual
Returns the variable reference for requested MooseVariable which may be in any system.
Implements SubProblem.
Definition at line 476 of file DisplacedProblem.C.
{
  for (auto & nl : _displaced_nl)
    if (nl->hasVariable(var_name))
      return nl->getFieldVariable<Real>(tid, var_name);
  if (_displaced_aux->hasVariable(var_name))
    return _displaced_aux->getFieldVariable<Real>(tid, var_name);
  mooseError("No variable with name '" + var_name + "'");
}
getSystem()
System & DisplacedProblem::getSystem (const std::string & var_name) override virtual
Returns the equation system containing the variable provided.
Implements SubProblem.
Definition at line 548 of file DisplacedProblem.C.
{
  for (const auto sys_num : make_range(_eq.n_systems()))
  {
    auto & sys = _eq.get_system(sys_num);
    if (sys.has_variable(var_name))
      return sys;
  }
  mooseError("Unable to find a system containing the variable " + var_name);
}
getVariable() [1/3]
virtual MooseVariableFieldBase & SubProblem::getVariable (const THREAD_ID tid, const std::string & var_name, Moose::VarKindType expected_var_type = Moose::VarKindType::VAR_ANY, Moose::VarFieldType expected_var_field_type = Moose::VarFieldType::VAR_FIELD_ANY) inline virtual
Reimplemented from SubProblem.
Definition at line 235 of file SubProblem.h.
  {
    return const_cast<MooseVariableFieldBase &>(const_cast<const SubProblem *>(this)->getVariable(
        tid, var_name, expected_var_type, expected_var_field_type));
  }
getVariable() [2/3]
const MooseVariableFieldBase & DisplacedProblem::getVariable (const THREAD_ID tid, const std::string & var_name, Moose::VarKindType expected_var_type = Moose::VarKindType::VAR_ANY, Moose::VarFieldType expected_var_field_type = Moose::VarFieldType::VAR_FIELD_ANY) const override virtual
Returns the variable reference for requested variable which must be of the expected_var_type (Nonlinear vs.
Auxiliary) and expected_var_field_type (standard, scalar, vector). The default values of VAR_ANY and VAR_FIELD_ANY should be used when "any" type of variable is acceptable. Throws an error if the variable in question is not in the expected System or of the expected type.
Implements SubProblem.
Definition at line 466 of file DisplacedProblem.C.
{
  return getVariableHelper(
      tid, var_name, expected_var_type, expected_var_field_type, _displaced_nl, *_displaced_aux);
}
Referenced by init().
getVariable() [3/3]
virtual const MooseVariableFieldBase & SubProblem::getVariable (const THREAD_ID tid, const std::string & var_name, Moose::VarKindType expected_var_type = Moose::VarKindType::VAR_ANY, Moose::VarFieldType expected_var_field_type = Moose::VarFieldType::VAR_FIELD_ANY) const virtual
Returns the variable reference for requested variable which must be of the expected_var_type (Nonlinear vs.
Auxiliary) and expected_var_field_type (standard, scalar, vector). The default values of VAR_ANY and VAR_FIELD_ANY should be used when "any" type of variable is acceptable. Throws an error if the variable in question is not in the expected System or of the expected type.
Implements SubProblem.
getVariableHelper() [1/2]
template<typename T > MooseVariableFieldBase & SubProblem::getVariableHelper (const THREAD_ID tid, const std::string & var_name, Moose::VarKindType expected_var_type, Moose::VarFieldType expected_var_field_type, const std::vector< T > & nls, const SystemBase & aux) const protected inherited
Helper function called by getVariable that handles the logic for checking whether Variables of the requested type are available.
Referenced by getVariable(), and FEProblemBase::getVariable().
getVariableHelper() [2/2]
template<typename T > MooseVariableFEBase & SubProblem::getVariableHelper (const THREAD_ID tid, const std::string & var_name, Moose::VarKindType expected_var_type, Moose::VarFieldType expected_var_field_type, const std::vector< T > & nls, const SystemBase & aux) const inherited
Definition at line 768 of file SubProblem.C.
{
  // Eventual return value
  MooseVariableFEBase * var = nullptr;
  const auto [var_in_nl, nl_sys_num] = determineNonlinearSystem(var_name);
  // First check that the variable is found on the expected system.
  if (expected_var_type == Moose::VarKindType::VAR_ANY)
  {
    if (var_in_nl)
      var = &(nls[nl_sys_num]->getVariable(tid, var_name));
    else if (aux.hasVariable(var_name))
      var = &(aux.getVariable(tid, var_name));
    else
      mooseError("Unknown variable " + var_name);
  }
  else if (expected_var_type == Moose::VarKindType::VAR_NONLINEAR && var_in_nl &&
           nls[nl_sys_num]->hasVariable(var_name))
    var = &(nls[nl_sys_num]->getVariable(tid, var_name));
  else if (expected_var_type == Moose::VarKindType::VAR_AUXILIARY && aux.hasVariable(var_name))
    var = &(aux.getVariable(tid, var_name));
  else
  {
    std::string expected_var_type_string =
        (expected_var_type == Moose::VarKindType::VAR_NONLINEAR ? "nonlinear" : "auxiliary");
    mooseError("No ",
               expected_var_type_string,
               " variable named ",
               var_name,
               " found. "
               "Did you specify an auxiliary variable when you meant to specify a nonlinear "
               "variable (or vice-versa)?");
  }
  // Now make sure the var found has the expected field type.
  if ((expected_var_field_type == Moose::VarFieldType::VAR_FIELD_ANY) ||
      (expected_var_field_type == var->fieldType()))
    return *var;
  else
  {
    std::string expected_var_field_type_string =
        MooseUtils::toLower(Moose::stringify(expected_var_field_type));
    std::string var_field_type_string = MooseUtils::toLower(Moose::stringify(var->fieldType()));
    mooseError("No ",
               expected_var_field_type_string,
               " variable named ",
               var_name,
               " found. "
               "Did you specify a ",
               var_field_type_string,
               " variable when you meant to specify a ",
               expected_var_field_type_string,
               " variable?");
  }
}
getVectorTag()
const VectorTag & DisplacedProblem::getVectorTag (const TagID tag_id) const override virtual
Get a VectorTag from a TagID.
Reimplemented from SubProblem.
Definition at line 370 of file DisplacedProblem.C.
{
  return _mproblem.getVectorTag(tag_id);
}
Referenced by addCachedResidualDirectly(), setResidual(), and setResidualNeighbor().
getVectorTagID()
TagID DisplacedProblem::getVectorTagID (const TagName & tag_name) const override virtual
Get a TagID from a TagName.
Reimplemented from SubProblem.
Definition at line 376 of file DisplacedProblem.C.
{
  return _mproblem.getVectorTagID(tag_name);
}
getVectorTags() [1/2]
const std::vector< VectorTag > & DisplacedProblem::getVectorTags (const Moose::VectorTagType type = Moose::VECTOR_TAG_ANY) const override virtual
Return all vector tags, where a tag is represented by a map from name to ID.
Can optionally be limited to a vector tag type.
Reimplemented from SubProblem.
Definition at line 406 of file DisplacedProblem.C.
{
  return _mproblem.getVectorTags(type);
}
getVectorTags() [2/2]
std::vector< VectorTag > SubProblem::getVectorTags (const std::set< TagID > & tag_ids) const inherited
Definition at line 150 of file SubProblem.C.
{
  mooseAssert(verifyVectorTags(), "Vector tag storage invalid");
  std::vector<VectorTag> tags;
  tags.reserve(tag_ids.size());
  for (const auto & tag_id : tag_ids)
    tags.push_back(getVectorTag(tag_id));
  return tags;
}
Referenced by NonlinearSystemBase::computeNodalBCs(), FEProblemBase::computeResidual(), EigenProblem::computeResidualAB(), FEProblemBase::computeResidualAndJacobian(), NonlinearSystemBase::computeResidualInternal(), EigenProblem::computeResidualTag(), ComputeResidualAndJacobianThread::determineObjectWarehouses(), getVectorTags(), SubProblem::numVectorTags(), ComputeMortarFunctor::operator()(), and FEProblemBase::setCurrentResidualVectorTags().
getVectorVariable()
VectorMooseVariable & DisplacedProblem::getVectorVariable (const THREAD_ID tid, const std::string & var_name) override virtual
Returns the variable reference for requested VectorMooseVariable which may be in any system.
Implements SubProblem.
Definition at line 500 of file DisplacedProblem.C.
{
  for (auto & nl : _displaced_nl)
    if (nl->hasVariable(var_name))
      return nl->getFieldVariable<RealVectorValue>(tid, var_name);
  if (_displaced_aux->hasVariable(var_name))
    return _displaced_aux->getFieldVariable<RealVectorValue>(tid, var_name);
  mooseError("No variable with name '" + var_name + "'");
}
ghostedElems()
std::set< dof_id_type > & DisplacedProblem::ghostedElems () override virtual
Return the list of elements that should have their DoFs ghosted to this processor.
Returns
The list
Reimplemented from SubProblem.
Definition at line 107 of file DisplacedProblem.C.
{
  return _mproblem.ghostedElems();
}
ghostGhostedBoundaries()
void DisplacedProblem::ghostGhostedBoundaries () override virtual
Causes the boundaries added using addGhostedBoundary to actually be ghosted.
Implements SubProblem.
Definition at line 1126 of file DisplacedProblem.C.
{
  _mproblem.ghostGhostedBoundaries();
}
hasActiveElementalMooseVariables()
bool SubProblem::hasActiveElementalMooseVariables (const THREAD_ID tid) const virtual inherited
Whether or not a list of active elemental moose variables has been set.
Returns
True if there has been a list of active elemental moose variables set, False otherwise
Definition at line 427 of file SubProblem.C.
{
  return _has_active_elemental_moose_variables[tid];
}
Referenced by SystemBase::prepare(), SystemBase::prepareFace(), and SystemBase::reinitElem().
hasBlockMaterialProperty()
bool SubProblem::hasBlockMaterialProperty (SubdomainID block_id, const std::string & prop_name) virtual inherited
Check if a material property is defined on a block.
Definition at line 478 of file SubProblem.C.
{
  auto it = _map_block_material_props.find(bid);
  if (it == _map_block_material_props.end())
    return false;
  if (it->second.count(prop_name) > 0)
    return true;
  else
    return false;
}
hasBoundaryMaterialProperty()
bool SubProblem::hasBoundaryMaterialProperty (BoundaryID boundary_id, const std::string & prop_name) virtual inherited
Check if a material property is defined on a block.
Definition at line 537 of file SubProblem.C.
{
  auto it = _map_boundary_material_props.find(bid);
  if (it == _map_boundary_material_props.end())
    return false;
  if (it->second.count(prop_name) > 0)
    return true;
  else
    return false;
}
hasFunctor()
bool SubProblem::hasFunctor (const std::string & name, const THREAD_ID tid) const inherited
checks whether we have a functor corresponding to name on the thread id tid
Definition at line 1217 of file SubProblem.C.
{
  mooseAssert(tid < _functors.size(), "Too large a thread ID");
  auto & functors = _functors[tid];
  return (functors.find("wraps_" + name) != functors.end());
}
Referenced by FunctorInterface::isFunctor().
hasFunctorWithType()
template<typename T > bool SubProblem::hasFunctorWithType (const std::string & name, const THREAD_ID tid) const inherited
checks whether we have a functor of type T corresponding to name on the thread id tid
Definition at line 1231 of file SubProblem.h.
{
  mooseAssert(tid < _functors.size(), "Too large a thread ID");
  auto & functors = _functors[tid];
  const auto & it = functors.find("wraps_" + name);
  constexpr bool requested_functor_is_ad =
      !std::is_same<T, typename MetaPhysicL::RawType<T>::value_type>::value;
  if (it == functors.end())
    return false;
  else
    return dynamic_cast<Moose::Functor<T> *>(
        requested_functor_is_ad ? std::get<2>(it->second).get() : std::get<1>(it->second).get());
}
hasNonlocalCoupling()
bool DisplacedProblem::hasNonlocalCoupling () const override virtual
Whether the simulation has nonlocal coupling which should be accounted for in the Jacobian.
Implements SubProblem.
Definition at line 1332 of file DisplacedProblem.C.
{
  return _mproblem.hasNonlocalCoupling();
}
hasScalarVariable()
bool DisplacedProblem::hasScalarVariable (const std::string & var_name) const override virtual
Returns a Boolean indicating whether any system contains a variable with the name provided.
Implements SubProblem.
Definition at line 524 of file DisplacedProblem.C.
{
  for (auto & nl : _displaced_nl)
    if (nl->hasScalarVariable(var_name))
      return true;
  if (_displaced_aux->hasScalarVariable(var_name))
    return true;
  return false;
}
hasScalingVector()
void SubProblem::hasScalingVector () inherited
Tells this problem that assembly involves a scaling vector.
Definition at line 1116 of file SubProblem.C.
{
  for (const THREAD_ID tid : make_range(libMesh::n_threads()))
    for (const auto nl_sys_num : make_range(numNonlinearSystems()))
      assembly(tid, nl_sys_num).hasScalingVector();
}
Referenced by SystemBase::addScalingVector().
hasVariable()
bool DisplacedProblem::hasVariable (const std::string & var_name) const override virtual
Whether or not this problem has the variable.
Implements SubProblem.
Definition at line 454 of file DisplacedProblem.C.
{
  for (auto & nl : _displaced_nl)
    if (nl->hasVariable(var_name))
      return true;
  if (_displaced_aux->hasVariable(var_name))
    return true;
  return false;
}
haveADObjects() [1/3]
bool SubProblem::haveADObjects () const inline
Method for reading wehther we have any ad objects.
Definition at line 726 of file SubProblem.h.
{ return _have_ad_objects; }
haveADObjects() [2/3]
virtual void SubProblem::haveADObjects (bool have_ad_objects) inline virtual
Method for setting whether we have any ad objects.
Reimplemented from SubProblem.
Definition at line 722 of file SubProblem.h.
{ _have_ad_objects = have_ad_objects; }
haveADObjects() [3/3]
void DisplacedProblem::haveADObjects (bool have_ad_objects) override virtual
Method for setting whether we have any ad objects.
Reimplemented from SubProblem.
Definition at line 1264 of file DisplacedProblem.C.
{
  _have_ad_objects = have_ad_objects;
  _mproblem.SubProblem::haveADObjects(have_ad_objects);
}
haveDisplaced()
bool DisplacedProblem::haveDisplaced () const inline final override virtual
Whether we have a displaced problem in our simulation.
Implements SubProblem.
Definition at line 340 of file DisplacedProblem.h.
{ return true; }
haveFV()
bool DisplacedProblem::haveFV () const override virtual
returns true if this problem includes/needs finite volume functionality.
Implements SubProblem.
Definition at line 1326 of file DisplacedProblem.C.
{
  return _mproblem.haveFV();
}
Referenced by init(), and updateMesh().
havePRefinement()
bool SubProblem::havePRefinement () const inline inherited
Query whether p-refinement has been requested at any point during the simulation.
Definition at line 939 of file SubProblem.h.
{ return _have_p_refinement; }
Referenced by AdvancedOutput::initAvailableLists(), and FEProblemBase::meshChangedHelper().
init()
void DisplacedProblem::init () override virtual
Get face types properly set for variables
Implements Problem.
Definition at line 143 of file DisplacedProblem.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); ++tid)
  {
    for (const auto nl_sys_num : index_range(_displaced_nl))
      _assembly[tid][nl_sys_num]->init(_mproblem.couplingMatrix(nl_sys_num));
    for (const auto nl_sys_num : index_range(_displaced_nl))
    {
      std::vector<std::pair<unsigned int, unsigned short>> disp_numbers_and_directions;
      for (const auto direction : index_range(_displacements))
      {
        const auto & disp_string = _displacements[direction];
        const auto & disp_variable = getVariable(tid, disp_string);
        if (disp_variable.sys().number() == nl_sys_num)
          disp_numbers_and_directions.push_back(
              std::make_pair(disp_variable.number(), cast_int<unsigned short>(direction)));
      }
      _assembly[tid][nl_sys_num]->assignDisplacements(std::move(disp_numbers_and_directions));
    }
  }
  for (auto & nl : _displaced_nl)
  {
    nl->dofMap().attach_extra_send_list_function(&extraSendList, nl.get());
    nl->init();
  }
  _displaced_aux->dofMap().attach_extra_send_list_function(&extraSendList, _displaced_aux.get());
  _displaced_aux->init();
  {
    TIME_SECTION("eq::init", 2, "Initializing Displaced Equation System");
    _eq.init();
  }
  for (auto & nl : _displaced_nl)
    nl->update(/*update_libmesh_system=*/false);
  _displaced_aux->update(/*update_libmesh_system=*/false);
  _mesh.meshChanged();
  if (haveFV())
    _mesh.setupFiniteVolumeMeshData();
}
Referenced by init().
initAdaptivity()
void DisplacedProblem::initAdaptivity () virtual
Definition at line 191 of file DisplacedProblem.C.
{
}
initialSetup()
void DisplacedProblem::initialSetup () override virtual
Reimplemented from SubProblem.
Definition at line 1214 of file DisplacedProblem.C.
{
  SubProblem::initialSetup();
  for (auto & nl : _displaced_nl)
    nl->initialSetup();
  _displaced_aux->initialSetup();
}
isMatPropRequested()
bool SubProblem::isMatPropRequested (const std::string & prop_name) const virtual inherited
Find out if a material property has been requested by any object.
Definition at line 689 of file SubProblem.C.
{
  return _material_property_requested.find(prop_name) != _material_property_requested.end();
}
isParamSetByUser()
bool MooseBaseParameterInterface::isParamSetByUser (const std::string & nm) const inline inherited
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
Parameters
nm The name of the parameter to test
Definition at line 108 of file MooseBaseParameterInterface.h.
{ return _pars.isParamSetByUser(nm); }
Referenced by SetAdaptivityOptionsAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), LibtorchNeuralNetControl::conditionalParameterError(), MooseBaseParameterInterface::getRenamedParam(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), PiecewiseTabularBase::PiecewiseTabularBase(), MooseMesh::prepare(), and SolutionUserObject::readXda().
isParamValid()
bool MooseBaseParameterInterface::isParamValid (const std::string & name) const inline inherited
Test if the supplied parameter is valid.
Parameters
name The name of the parameter to test
Definition at line 102 of file MooseBaseParameterInterface.h.
{ return _pars.isParamValid(name); }
Referenced by AddDriftDiffusionAction::act(), AddSpecies::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CopyNodalVarsAction::act(), CreateDisplacedProblemAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), AddGeneralReactions::AddGeneralReactions(), AddZapdosReactions::AddZapdosReactions(), AdvectiveFluxAux::AdvectiveFluxAux(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), GeneratedMesh::buildMesh(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), ChemicalReactionsBase::ChemicalReactionsBase(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), CombinerGenerator::CombinerGenerator(), CSVReader::CSVReader(), ConstantReporter::declareConstantReporterValues(), DGKernelBase::DGKernelBase(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EEDFEnergyTownsendLog::EEDFEnergyTownsendLog(), Eigenvalue::Eigenvalue(), ElectronEnergyTermRate::ElectronEnergyTermRate(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), PIDTransientControl::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FileOutput::FileOutput(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FunctionDT::FunctionDT(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getRenamedParam(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), Terminator::handleMessage(), HeavySpeciesTempl< is_ad >::HeavySpeciesTempl(), HFEMDirichletBC::HFEMDirichletBC(), EigenExecutionerBase::init(), Eigenvalue::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), MooseParsedFunction::initialSetup(), MooseParsedGradFunction::initialSetup(), MooseParsedVectorFunction::initialSetup(), PiecewiseTabularBase::initialSetup(), SolutionFunction::initialSetup(), Console::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), IterationAdaptiveDT::IterationAdaptiveDT(), LeastSquaresFit::LeastSquaresFit(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MatCoupledForce::MatCoupledForce(), MooseMesh::MooseMesh(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarConsumerInterface::MortarConsumerInterface(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalExtremeValue::NodalExtremeValue(), EigenExecutionerBase::normalizeSolution(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PetscOutput::PetscOutput(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), PicardSolve::PicardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseTabularBase::PiecewiseTabularBase(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), MooseMesh::prepare(), MultiApp::readCommandLineArguments(), SolutionUserObject::readExodusII(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), MooseMesh::setCoordSystem(), FileOutput::setFileBase(), FileOutput::setFileBaseInternal(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SideDiffusiveFluxIntegralTempl< is_ad, T >::SideDiffusiveFluxIntegralTempl(), SideExtremeValue::SideExtremeValue(), SolutionUserObject::SolutionUserObject(), Terminator::Terminator(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), MultiAppDofCopyTransfer::transfer(), TransformGenerator::TransformGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
isSolveTerminationRequested()
virtual bool Problem::isSolveTerminationRequested () const inline virtual inherited
Check of termination has been requested.
This should be called by transient Executioners in the keepGoing() member.
Definition at line 43 of file Problem.h.
{ return _termination_requested; };
Referenced by Transient::keepGoing().
isTransient()
bool DisplacedProblem::isTransient () const override virtual
Implements SubProblem.
Definition at line 101 of file DisplacedProblem.C.
{
  return _mproblem.isTransient();
}
jacobianSetup()
void DisplacedProblem::jacobianSetup () override virtual
Reimplemented from SubProblem.
Definition at line 1254 of file DisplacedProblem.C.
{
  SubProblem::jacobianSetup();
  for (auto & nl : _displaced_nl)
    nl->jacobianSetup();
  _displaced_aux->jacobianSetup();
}
markMatPropRequested()
void SubProblem::markMatPropRequested (const std::string & prop_name) virtual inherited
Helper method for adding a material property name to the _material_property_requested set.
Definition at line 683 of file SubProblem.C.
{
  _material_property_requested.insert(prop_name);
}
Referenced by MaterialBase::getGenericZeroMaterialPropertyByName(), and MaterialPropertyInterface::markMatPropRequested().
matrixTagExists() [1/2]
bool DisplacedProblem::matrixTagExists (const TagName & tag_name) override virtual
Check to see if a particular Tag exists.
Reimplemented from SubProblem.
Definition at line 436 of file DisplacedProblem.C.
{
  return _mproblem.matrixTagExists(tag_name);
}
matrixTagExists() [2/2]
bool DisplacedProblem::matrixTagExists (TagID tag_id) override virtual
Check to see if a particular Tag exists.
Reimplemented from SubProblem.
Definition at line 442 of file DisplacedProblem.C.
{
  return _mproblem.matrixTagExists(tag_id);
}
matrixTagName()
TagName DisplacedProblem::matrixTagName (TagID tag) override virtual
Retrieve the name associated with a TagID.
Reimplemented from SubProblem.
Definition at line 430 of file DisplacedProblem.C.
{
  return _mproblem.matrixTagName(tag);
}
mesh() [1/4]
virtual const MooseMesh & DisplacedProblem::mesh () const inline override virtual
Implements SubProblem.
Definition at line 48 of file DisplacedProblem.h.
{ return _mesh; }
mesh() [2/4]
virtual MooseMesh & DisplacedProblem::mesh () inline override virtual
Implements SubProblem.
Definition at line 47 of file DisplacedProblem.h.
{ return _mesh; }
Referenced by ElementSubdomainModifier::execute(), ElementSubdomainModifier::finalize(), ElementSubdomainModifier::initialSetup(), mesh(), and ElementSubdomainModifier::setAncestorsSubdomainIDs().
mesh() [3/4]
const MooseMesh & DisplacedProblem::mesh (bool libmesh_dbg_varuse_displaced) const inline override
Definition at line 49 of file DisplacedProblem.h.
  {
    mooseAssert(use_displaced, "An undisplaced mesh was queried from the displaced problem");
    return mesh();
  }
mesh() [4/4]
virtual const MooseMesh & SubProblem::mesh (bool use_displaced) const pure virtual inherited
Implemented in FEProblemBase.
meshChanged()
void DisplacedProblem::meshChanged () override virtual
Reimplemented from SubProblem.
Definition at line 1087 of file DisplacedProblem.C.
{
  // The mesh changed. The displaced equations system object only holds ExplicitSystems, so calling
  // EquationSystems::reinit only prolongs/restricts the solution vectors, which is something that
  // needs to happen for every step of mesh adaptivity.
  _eq.reinit();
  // We've performed some mesh adaptivity. We need to
  // clear any quadrature nodes such that when we build the boundary node lists in
  // MooseMesh::meshChanged we don't have any extraneous extra boundary nodes lying around
  _mesh.clearQuadratureNodes();
  _mesh.meshChanged();
  // Before performing mesh adaptivity we un-displaced the mesh. We need to re-displace the mesh and
  // then reinitialize GeometricSearchData such that we have all the correct geometric information
  // for the changed mesh
  updateMesh(/*mesh_changing=*/true);
  // Since the mesh has changed, we need to make sure that we update any of our
  // MOOSE-system specific data. libmesh system data has already been updated
  for (auto & nl : _displaced_nl)
    nl->update(/*update_libmesh_system=*/false);
  _displaced_aux->update(/*update_libmesh_system=*/false);
}
mooseDeprecated()
template<typename... Args> void MooseBaseErrorInterface::mooseDeprecated (Args &&... args) const inline inherited
Definition at line 78 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseDeprecatedStream(_console, false, true, std::forward<Args>(args)...);
  }
Referenced by FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::advanceMultiApps(), MultiApp::appProblem(), Executioner::augmentedPicardConvergenceCheck(), MooseMesh::buildSideList(), FEProblemBase::computeResidual(), AddVariableAction::determineType(), Eigenvalue::Eigenvalue(), MooseMesh::elem(), FunctionDT::FunctionDT(), RandomICBase::generateRandom(), MooseMesh::getBoundariesToElems(), Control::getExecuteOptions(), FEProblemBase::getNonlinearSystem(), FEProblemBase::getUserObjects(), FEProblemBase::hasPostprocessor(), MooseMesh::node(), FixedPointSolve::numPicardIts(), RelationshipManager::operator>=(), Executioner::picardSolve(), and MooseMesh::setBoundaryToNormalMap().
mooseError()
template<typename... Args> void MooseBaseErrorInterface::mooseError (Args &&... args) const inline inherited
Emits an error prefixed with object name and type.
Definition at line 38 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, errorPrefix("error"), std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
Referenced by HierarchicalGridPartitioner::_do_partition(), PetscExternalPartitioner::_do_partition(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AdaptivityAction::act(), AddFVICAction::act(), AddICAction::act(), AddMeshGeneratorAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVectorPostprocessorAction::act(), CheckFVBCAction::act(), CheckIntegrityAction::act(), CommonOutputAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DeprecatedBlockAction::act(), InitProblemAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetAdaptivityOptionsAction::act(), SetupMeshAction::act(), SetupMeshCompleteAction::act(), SetupPredictorAction::act(), SetupTimeStepperAction::act(), SplitMeshAction::act(), FEProblemBase::adaptMesh(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::addConstraint(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFVInitialCondition(), AddGeneralReactions::AddGeneralReactions(), FEProblemBase::addInitialCondition(), FEProblemBase::addLineSearch(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addOutput(), SubProblem::addPiecewiseByBlockLambdaFunctor(), DistributedRectilinearMeshGenerator::addPoint(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), FEProblemBase::addPostprocessor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseMesh::addQuadratureNode(), FEProblemBase::addReporter(), AddVariableAction::addVariable(), FEProblemBase::addVectorPostprocessor(), SubProblem::addVectorTag(), AddZapdosReactions::AddZapdosReactions(), ADEEDFRateConstantTownsend::ADEEDFRateConstantTownsend(), ADGasElectronMoments::ADGasElectronMoments(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), MooseVariableScalar::adUDot(), Output::advancedExecuteOn(), AdvectiveFluxAux::AdvectiveFluxAux(), ADZapdosEEDFRateConstant::ADZapdosEEDFRateConstant(), MooseVariableBase::allDofIndices(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayConstantIC::ArrayConstantIC(), ArrayFunctionIC::ArrayFunctionIC(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), Function::average(), Axisymmetric2D3DSolutionFunction::Axisymmetric2D3DSolutionFunction(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), BoltzmannSolverScalar::BoltzmannSolverScalar(), BoundingValueElementDamper::BoundingValueElementDamper(), BoundingValueNodalDamper::BoundingValueNodalDamper(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), MooseMesh::buildCoarseningMap(), MultiApp::buildComm(), DistributedRectilinearMeshGenerator::buildCube(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), PiecewiseTabularBase::buildFromXY(), MooseMesh::buildLowerDMesh(), GeneratedMesh::buildMesh(), MeshGeneratorMesh::buildMesh(), SpiralAnnularMesh::buildMesh(), TiledMesh::buildMesh(), ImageMesh::buildMesh3D(), ImageMeshGenerator::buildMesh3D(), MooseMesh::buildRefinementMap(), MaterialBase::buildRequiredMaterials(), MooseMesh::buildSideList(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), UserObjectInterface::castUserObject(), EigenExecutionerBase::chebyshev(), SubProblem::checkBlockMatProps(), SubProblem::checkBoundaryMatProps(), MooseMesh::checkCoordinateSystems(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkDisplacementOrders(), FEProblemBase::checkDuplicatePostprocessorVariableNames(), MooseMesh::checkDuplicateSubdomainNames(), MaterialBase::checkExecutionStage(), MeshGenerator::checkGetMesh(), ReporterTransferInterface::checkHasReporterValue(), FEProblemBase::checkICRestartError(), EigenExecutionerBase::checkIntegrity(), Eigenvalue::checkIntegrity(), Steady::checkIntegrity(), ExplicitTimeIntegrator::checkLinearConvergence(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), PostprocessorInterface::checkParam(), FEProblemBase::checkProblemIntegrity(), Sampler::checkReinitStatus(), MaterialBase::checkStatefulSanity(), FEProblemBase::checkUserObjects(), MultiAppTransfer::checkVariable(), DomainUserObject::checkVariable(), ChemicalReactionsBase::ChemicalReactionsBase(), MooseMesh::clone(), LibmeshPartitioner::clone(), CombinerGenerator::CombinerGenerator(), ElementSubdomainModifier::complementMovingBoundaryID(), ElementSubdomainModifier::complementMovingBoundaryName(), MooseVariableFieldBase::componentName(), CompositeFunction::CompositeFunction(), NodalPatchRecovery::compute(), VariableCondensationPreconditioner::computeDInverseDiag(), CompositionDT::computeDT(), MooseVariableFieldBase::computeFaceValues(), TimeStepper::computeFailedDT(), IterationAdaptiveDT::computeFailedDT(), TimeSequenceStepperBase::computeFailedDT(), MooseMesh::computeFiniteVolumeCoords(), FVFluxKernel::computeJacobian(), ArrayKernel::computeJacobian(), ArrayKernel::computeOffDiagJacobian(), FVElementalKernel::computeOffDiagJacobian(), MaterialBase::computeProperties(), ScalarKernel::computeQpJacobian(), ScalarKernel::computeQpResidual(), FVFluxKernel::computeResidual(), ArrayKernel::computeResidual(), FVFluxBC::computeResidual(), ResidualObject::computeResidualAndJacobian(), FVFluxKernel::computeResidualAndJacobian(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualL2Norm(), FEProblemBase::computeResidualTag(), FEProblemBase::computeResidualType(), TimeStepper::computeStep(), ActuallyExplicitEuler::computeTimeDerivatives(), AStableDirk4::computeTimeDerivatives(), BDF2::computeTimeDerivatives(), CrankNicolson::computeTimeDerivatives(), ExplicitEuler::computeTimeDerivatives(), ExplicitRK2::computeTimeDerivatives(), ExplicitTVDRK2::computeTimeDerivatives(), ImplicitEuler::computeTimeDerivatives(), ImplicitMidpoint::computeTimeDerivatives(), LStableDirk2::computeTimeDerivatives(), LStableDirk3::computeTimeDerivatives(), LStableDirk4::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), FEProblemBase::computeUserObjectsInternal(), BolsigValueScalar::computeValue(), PenetrationAux::computeValue(), BuildArrayVariableAux::computeValue(), TagVectorArrayVariableAux::computeValue(), ConcentricCircleMesh::ConcentricCircleMesh(), ConditionalEnableControl::ConditionalEnableControl(), TimeStepper::constrainStep(), LibtorchNeuralNetControl::controlNeuralNet(), AddVariableAction::createInitialConditionAction(), DataRead::DataRead(), ReporterTransferInterface::declareClone(), MeshGenerator::declareMeshProperty(), ReporterTransferInterface::declareVectorClone(), FunctorRelationshipManager::delete_remote_elements(), MooseMesh::deleteRemoteElements(), BicubicSplineFunction::derivative(), MooseMesh::detectPairedSidesets(), FEProblemBase::determineNonlinearSystem(), MeshDiagnosticsGenerator::diagnosticsLog(), DiffusionRateTemp::DiffusionRateTemp(), FunctorBinnedValuesDivision::divisionIndex(), FunctorRelationshipManager::dofmap_reinit(), FEProblemBase::duplicateVariableCheck(), EEDFRateConstant::EEDFRateConstant(), EEDFRateConstantTownsend::EEDFRateConstantTownsend(), Eigenvalue::Eigenvalue(), ElectricField::ElectricField(), ElectronMobility::ElectronMobility(), ElementIntegerAux::ElementIntegerAux(), ElementQualityAux::ElementQualityAux(), ElementUOAux::ElementUOAux(), DistributedRectilinearMeshGenerator::elemId(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), MooseMesh::errorIfDistributedMesh(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), BoltzmannSolverScalar::execute(), Eigenvalue::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), ElementQualityChecker::execute(), DiscreteElementUserObject::execute(), DomainUserObject::execute(), FEProblemBase::execute(), FEProblemBase::executeControls(), MultiAppVectorPostprocessorTransfer::executeFromMultiapp(), MultiAppVectorPostprocessorTransfer::executeToMultiapp(), ExplicitSSPRungeKutta::ExplicitSSPRungeKutta(), FileOutput::FileOutput(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), ElementQualityChecker::finalize(), VerifyElementUniqueID::finalize(), VerifyNodalUniqueID::finalize(), DiscreteElementUserObject::finalize(), Transfer::find_sys(), BreakMeshByBlockGeneratorBase::findFreeBoundaryId(), FunctionDT::FunctionDT(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), GapValueAux::GapValueAux(), Gas::Gas(), GasBase::GasBase(), GasElectronMoments::GasElectronMoments(), AllSideSetsByNormalsGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundingBoxNodeSetGenerator::generate(), BreakMeshByBlockGenerator::generate(), CombinerGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshCollectionGenerator::generate(), MeshDiagnosticsGenerator::generate(), MeshExtruderGenerator::generate(), MeshRepairGenerator::generate(), MoveNodeGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), SideSetsFromNormalsGenerator::generate(), SideSetsFromPointsGenerator::generate(), SmoothMeshGenerator::generate(), SpiralAnnularMeshGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), TiledMeshGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GeneratedMesh::GeneratedMesh(), GeneratedMeshGenerator::GeneratedMeshGenerator(), MeshGenerator::generateInternal(), CircularBoundaryCorrectionGenerator::generateRadialCorrectionFactor(), RandomICBase::generateRandom(), GenericConstantMaterialTempl< is_ad >::GenericConstantMaterialTempl(), GenericConstantVectorMaterialTempl< is_ad >::GenericConstantVectorMaterialTempl(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), getActualFieldVariable(), FEProblemBase::getActualFieldVariable(), getArrayVariable(), FEProblemBase::getArrayVariable(), MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::getBlockConnectedBlocks(), VariableOldValueBoundsAux::getBound(), MooseMesh::getBoundaryID(), MultiApp::getBoundingBox(), MooseMesh::getCoarseningMap(), MooseVariableBase::getContinuity(), Control::getControllableParameterByName(), MooseMesh::getCoordSystem(), PropertyReadFile::getData(), TransfiniteMeshGenerator::getDiscreteEdge(), FEProblemBase::getDistribution(), MooseVariableBase::getDofIndices(), VariableCondensationPreconditioner::getDofToCondense(), TransfiniteMeshGenerator::getEdge(), GhostingUserObject::getElementalValue(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), PropertyReadFile::getElementData(), MooseMesh::getElementIDIndex(), Material::getElementIDNeighbor(), Material::getElementIDNeighborByName(), MooseMesh::getElemIDMapping(), MooseMesh::getElemIDsOnBlocks(), MultiAppFieldTransfer::getEquationSystem(), MultiApp::getExecutioner(), MultiAppTransfer::getFromMultiApp(), MultiAppTransfer::getFromMultiAppInfo(), FEProblemBase::getFunction(), SubProblem::getFunctor(), MooseMesh::getGeneralAxisymmetricCoordAxis(), DistributedRectilinearMeshGenerator::getGhostNeighbors(), BatchMaterial< Tuple, Output, Input >::getIndex(), DistributedRectilinearMeshGenerator::getIndices(), SolutionUserObject::getLocalVarIndex(), Material::getMaterialByName(), FEProblemBase::getMaterialData(), SubProblem::getMatrixTagID(), AnnularMesh::getMaxInDimension(), GeneratedMesh::getMaxInDimension(), FEProblemBase::getMaxQps(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), AnnularMesh::getMinInDimension(), GeneratedMesh::getMinInDimension(), MultiAppTransfer::getMultiApp(), DistributedRectilinearMeshGenerator::getNeighbors(), MooseMesh::getNodeBlockIds(), PropertyReadFile::getNodeData(), MooseMesh::getNodeList(), FEProblemBase::getNonlinearSystem(), MooseMesh::getPairedBoundaryMapping(), ImageMesh::GetPixelInfo(), ImageMeshGenerator::GetPixelInfo(), PlaneIDMeshGenerator::getPlaneID(), FEProblemBase::getPositionsObject(), PostprocessorInterface::getPostprocessorValueByNameInternal(), MooseMesh::getRefinementMap(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), FEProblemBase::getSampler(), JSONFileReader::getScalar(), getScalarVariable(), FEProblemBase::getScalarVariable(), getStandardVariable(), FEProblemBase::getStandardVariable(), MooseMesh::getSubdomainBoundaryIds(), getSystem(), FEProblemBase::getSystem(), FEProblemBase::getTimeFromStateArg(), Transient::getTimeIntegratorName(), MultiAppTransfer::getToMultiApp(), MultiAppTransfer::getToMultiAppInfo(), MooseMesh::getUniqueCoordSystem(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::getUserObjectName(), JSONFileReader::getVector(), VectorPostprocessorInterface::getVectorPostprocessorName(), SubProblem::getVectorTag(), SubProblem::getVectorTagID(), getVectorVariable(), FEProblemBase::getVectorVariable(), GhostingAux::GhostingAux(), MultiApp::globalAppToLocal(), Function::gradient(), MooseParsedVectorFunction::gradient(), Terminator::handleMessage(), MooseVariableBase::hasDoFsOnNodes(), PostprocessorInterface::hasPostprocessor(), PostprocessorInterface::hasPostprocessorByName(), ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), AddVariableAction::init(), MooseMesh::init(), Sampler::init(), AddAuxVariableAction::init(), EigenExecutionerBase::init(), Eigenvalue::init(), Transient::init(), FEProblemBase::init(), CrankNicolson::init(), ExplicitTimeIntegrator::init(), CSVTimeSequenceStepper::init(), IterationAdaptiveDT::init(), MultiApp::init(), FEProblemBase::initialAdaptMesh(), BoltzmannSolverScalar::initialize(), PolynomialCoefficients::initialize(), CartesianGridDivision::initialize(), CylindricalGridDivision::initialize(), NestedDivision::initialize(), SphericalGridDivision::initialize(), SubProblem::initialSetup(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), Axisymmetric2D3DSolutionFunction::initialSetup(), MooseParsedFunction::initialSetup(), SolutionFunction::initialSetup(), SolutionIC::initialSetup(), FullSolveMultiApp::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), SolutionUserObject::initialSetup(), Function::integral(), InterpolatedCoefficientLinear::InterpolatedCoefficientLinear(), InterpolatedCoefficientSpline::InterpolatedCoefficientSpline(), EigenExecutionerBase::inversePowerIteration(), InversePowerMethod::InversePowerMethod(), Sampler::isAdaptiveSamplingCompleted(), MooseMesh::isBoundaryFullyExternalToSubdomains(), MooseVariableBase::isNodal(), IterationAdaptiveDT::IterationAdaptiveDT(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LineSearch::lineSearch(), ReporterPointMarker::markerSetup(), Material::Material(), MaterialOutputAction::materialOutputHelper(), MaterialRealTensorValueAux::MaterialRealTensorValueAux(), MaterialRealVectorValueAuxTempl< is_ad >::MaterialRealVectorValueAuxTempl(), Distribution::median(), FunctorRelationshipManager::mesh_reinit(), SubProblem::meshChanged(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshExtruderGenerator::MeshExtruderGenerator(), MeshRepairGenerator::MeshRepairGenerator(), SetupMeshAction::modifyParamsForUseSplit(), MeshMetaDataInterface::mooseErrorInternal(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MoveNodeGenerator::MoveNodeGenerator(), ElementSubdomainModifier::movingBoundaryID(), ElementSubdomainModifier::movingBoundaryName(), MultiApp::MultiApp(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NearestNodeDistanceAux::NearestNodeDistanceAux(), NearestNodeValueAux::NearestNodeValueAux(), FEProblemBase::needsPreviousNewtonIteration(), NewmarkBeta::NewmarkBeta(), NodalPatchRecoveryBase::nodalPatchRecovery(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), DistributedRectilinearMeshGenerator::nodeId(), DistributedRectilinearMeshGenerator::numNeighbors(), Output::onInterval(), FunctorRelationshipManager::operator()(), RelationshipManager::operator==(), MortarNodalGeometryOutput::output(), Output::Output(), DistributedRectilinearMeshGenerator::paritionSquarely(), PiecewiseBilinear::parse(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), ExplicitTimeIntegrator::performExplicitSolve(), PetscExternalPartitioner::PetscExternalPartitioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), Executioner::picardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseMulticonstant::PiecewiseMulticonstant(), PiecewiseTabularBase::PiecewiseTabularBase(), SolutionUserObject::pointValueGradientWrapper(), SolutionUserObject::pointValueWrapper(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName(), AStableDirk4::postResidual(), ExplicitRK2::postResidual(), ExplicitTVDRK2::postResidual(), ImplicitMidpoint::postResidual(), LStableDirk2::postResidual(), LStableDirk3::postResidual(), LStableDirk4::postResidual(), VariableCondensationPreconditioner::preallocateCondensedJacobian(), Predictor::Predictor(), Transient::preExecute(), MooseMesh::prepare(), MooseMesh::prepared(), FixedPointSolve::printFixedPointConvergenceReason(), RateCoefficientProvider::RateCoefficientProvider(), RateCoefficientProvider::reaction_coefficient(), RateCoefficientProvider::reaction_coefficient_derivative(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readExodusII(), SolutionUserObject::readXda(), FunctorRelationshipManager::redistribute(), Sampler::reinit(), RinglebMesh::RinglebMesh(), RinglebMeshGenerator::RinglebMeshGenerator(), PiecewiseMultiInterpolation::sample(), ScalarComponentIC::ScalarComponentIC(), ScalarLinearInterpolation::ScalarLinearInterpolation(), ScalarSplineInterpolation::ScalarSplineInterpolation(), DistributedRectilinearMeshGenerator::scaleNodalPositions(), BicubicSplineFunction::secondDerivative(), FunctorRelationshipManager::set_mesh(), MooseVariableBase::setActiveTags(), DistributedRectilinearMeshGenerator::setBoundaryNames(), MooseMesh::setCoordSystem(), FEProblemBase::setCoupling(), PiecewiseBase::setData(), FileOutput::setFileBaseInternal(), MooseMesh::setGeneralAxisymmetricCoordAxes(), FEProblemSolve::setInnerSolve(), MeshGenerator::setMeshProperty(), FEProblemBase::setNonlocalCouplingMatrix(), Sampler::setNumberOfCols(), Sampler::setNumberOfRandomSeeds(), Sampler::setNumberOfRows(), Split::setup(), TransientMultiApp::setupApp(), SetupMeshAction::setupMesh(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), TimePeriodBase::setupTimes(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SideSetsFromNormalsGenerator::SideSetsFromNormalsGenerator(), SideSetsFromPointsGenerator::SideSetsFromPointsGenerator(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), SolutionTimeAdaptiveDT::SolutionTimeAdaptiveDT(), SolutionUserObject::SolutionUserObject(), FullSolveMultiApp::solveStep(), UserObject::spatialPoints(), UserObject::spatialValue(), SpiralAnnularMesh::SpiralAnnularMesh(), SpiralAnnularMeshGenerator::SpiralAnnularMeshGenerator(), StitchedMesh::StitchedMesh(), MaterialBase::subdomainSetup(), GeneralUserObject::subdomainSetup(), NodalUserObject::subdomainSetup(), Constraint::subdomainSetup(), SuperelasticReactionRate::SuperelasticReactionRate(), FEProblemBase::swapBackMaterialsNeighbor(), Terminator::Terminator(), GeneralUserObject::threadJoin(), ThreadedGeneralUserObject::threadJoin(), DiscreteElementUserObject::threadJoin(), TimePeriodBase::TimePeriodBase(), VectorPostprocessorVisualizationAux::timestepSetup(), FEProblemBase::trustUserCouplingMatrix(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), FEProblemBase::uDotDotOldRequested(), MooseVariableScalar::uDotOld(), FEProblemBase::uDotOldRequested(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), SolutionUserObject::updateExodusBracketingTimeIndices(), FEProblemBase::updateMaxQps(), BoundingBoxIC::value(), Function::value(), Axisymmetric2D3DSolutionFunction::value(), PiecewiseConstantFromCSV::value(), ValueProvider::ValueProvider(), ValueRangeMarker::ValueRangeMarker(), ValueThresholdMarker::ValueThresholdMarker(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), MultiAppTransfer::variableIntegrityCheck(), VariableTimeIntegrationAux::VariableTimeIntegrationAux(), AddVariableAction::variableType(), Function::vectorCurl(), SubProblem::vectorTagName(), SubProblem::vectorTagType(), Function::vectorValue(), MooseParsedFunction::vectorValue(), MooseParsedGradFunction::vectorValue(), SubProblem::verifyVectorTags(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
mooseErrorNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseErrorNonPrefixed (Args &&... args) const inline inherited
Emits an error without the prefixing included in mooseError().
Definition at line 50 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
mooseInfo()
template<typename... Args> void MooseBaseErrorInterface::mooseInfo (Args &&... args) const inline inherited
Definition at line 84 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseInfoStream(_console, std::forward<Args>(args)...);
  }
Referenced by AddZapdosReactions::act(), SetupRecoverFileBaseAction::act(), AStableDirk4::AStableDirk4(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), BoltzmannSolverScalar::execute(), ExplicitRK2::ExplicitRK2(), ExplicitTVDRK2::ExplicitTVDRK2(), MultiAppTransfer::getPointInTargetAppFrame(), ImplicitMidpoint::ImplicitMidpoint(), InversePowerMethod::InversePowerMethod(), LStableDirk2::LStableDirk2(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), NonlinearEigen::NonlinearEigen(), ProjectionAux::ProjectionAux(), FEProblemBase::setRestartFile(), and SymmetryTransformGenerator::SymmetryTransformGenerator().
mooseWarning()
template<typename... Args> void MooseBaseErrorInterface::mooseWarning (Args &&... args) const inline inherited
Emits a warning prefixed with object name and type.
Definition at line 62 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(
        _console, errorPrefix("warning"), std::forward<Args>(args)...);
  }
Referenced by AddFunctionAction::act(), AddKernelAction::act(), CommonOutputAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupMeshAction::act(), DumpObjectsProblem::addAuxVariable(), DiracKernelBase::addPoint(), BoundaryMarker::BoundaryMarker(), BoundsAuxBase::BoundsAuxBase(), DistributedRectilinearMeshGenerator::buildCube(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), CartesianMeshGenerator::CartesianMeshGenerator(), CheckOutputAction::checkConsoleOutput(), MultiAppTransfer::checkMultiAppExecuteOn(), GapValueAux::computeValue(), MeshDiagnosticsGenerator::diagnosticsLog(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), Postprocessor::evaluateDotWarning(), ElementQualityChecker::finalize(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FixedPointSolve::FixedPointSolve(), ElementSubdomainIDGenerator::generate(), ParsedGenerateSideset::generate(), MultiAppTransfer::getAppInfo(), FunctorBinnedValuesDivision::getBinIndex(), FEProblemBase::getMaterial(), Terminator::handleMessage(), MaterialBase::initStatefulProperties(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::mesh(), NewmarkBeta::NewmarkBeta(), NodalPatchRecovery::NodalPatchRecovery(), Output::Output(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), Executioner::problem(), PropertyReadFile::readData(), TestSourceStepper::rejectStep(), MaterialBase::resetQpProperties(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setCoordSystem(), FEProblemBase::sizeZeroes(), TransientMultiApp::solveStep(), TimeDerivativeAux::TimeDerivativeAux(), PiecewiseConstantFromCSV::value(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
mooseWarningNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseWarningNonPrefixed (Args &&... args) const inline inherited
Emits a warning without the prefixing included in mooseWarning().
Definition at line 72 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(_console, std::forward<Args>(args)...);
  }
name()
virtual const std::string & MooseBase::name () const inline virtual inherited
Get the name of the class.
Returns
The name of the class
Reimplemented in MooseVariableBase.
Definition at line 47 of file MooseBase.h.
{ return _name; }
Referenced by HierarchicalGridPartitioner::_do_partition(), AdaptivityAction::act(), AddElementalFieldAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVariableAction::act(), CopyNodalVarsAction::act(), DeprecatedBlockAction::act(), DisplayGhostingAction::act(), MaterialOutputAction::act(), AddDriftDiffusionAction::addADKernels(), FEProblemBase::addAnyRedistributers(), Executioner::addAttributeReporter(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFunctorMaterial(), FunctorMaterial::addFunctorProperty(), FunctorMaterial::addFunctorPropertyByBlocks(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), ADDGKernel::ADDGKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), SubProblem::addPiecewiseByBlockLambdaFunctor(), FEProblemBase::addPostprocessor(), UserObject::addPostprocessorDependencyHelper(), InitialConditionBase::addPostprocessorDependencyHelper(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), UserObject::addUserObjectDependencyHelper(), AuxKernelTempl< ComputeValueType >::addUserObjectDependencyHelper(), InitialConditionBase::addUserObjectDependencyHelper(), addVariable(), FEProblemBase::addVectorPostprocessor(), UserObject::addVectorPostprocessorDependencyHelper(), FVFluxKernel::adjustRMGhostLayers(), ADSurfaceCharge::ADSurfaceCharge(), Output::advancedExecuteOn(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayDGKernel::ArrayDGKernel(), ArrayParsedAux::ArrayParsedAux(), AStableDirk4::AStableDirk4(), Function::average(), MultiApp::backup(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), PiecewiseTabularBase::buildFromFile(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkICRestartError(), Damper::checkMinDamping(), Coupleable::checkWritableVar(), CompositeFunction::CompositeFunction(), MaterialBase::computeProperties(), FEProblemBase::computeUserObjectByName(), VectorPostprocessorVisualizationAux::computeValue(), MooseBaseParameterInterface::connectControllableParams(), BatchMaterial< Tuple, Output, Input >::construct(), MultiApp::createApp(), AddVariableAction::createInitialConditionAction(), MultiApp::createLocalApp(), MeshGeneratorSystem::createMeshGeneratorOrder(), MaterialBase::declareADProperty(), MeshGenerator::declareMeshesForSubByName(), MeshGenerator::declareNullMeshName(), MaterialBase::declareProperty(), DOFMapOutput::demangle(), DerivativeSumMaterialTempl< is_ad >::DerivativeSumMaterialTempl(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DomainUserObject::DomainUserObject(), DumpObjectsProblem::dumpObjectHelper(), EconomouDielectricBC::EconomouDielectricBC(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementValueSampler::ElementValueSampler(), MooseMesh::errorIfDistributedMesh(), MooseBaseErrorInterface::errorPrefix(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), PointValue::execute(), RestartableDataReporter::execute(), MultiAppNearestNodeTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), MultiApp::fillPositions(), PointSamplerBase::finalize(), FunctionDT::FunctionDT(), FVFunctionIC::functionName(), FunctionIC::functionName(), FunctorPositions::FunctorPositions(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), BoundaryDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), GeneratedMeshGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MeshGenerator::generateInternal(), InterfaceMaterial::getADMaterialProperty(), Material::getADMaterialProperty(), MultiAppTransfer::getAppInfo(), MultiApp::getBoundingBox(), Control::getControllableParameterByName(), Control::getControllableValue(), Control::getControllableValueByName(), UserObject::getDependObjects(), FEProblemBase::getDistribution(), DistributionInterface::getDistribution(), DistributionInterface::getDistributionByName(), AddZapdosReactions::getElectronImpactKernelName(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), MultiApp::getExecutioner(), FEProblemBase::getExecutor(), OutputWarehouse::getFileNumbers(), FEProblemBase::getFunction(), SubProblem::getFunctor(), AuxKernelTempl< ComputeValueType >::getGenericMaterialProperty(), NodalPatchRecovery::getGenericMaterialProperty(), InterfaceMaterial::getGenericMaterialProperty(), Material::getGenericMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialPropertyByName(), Material::getGenericOptionalMaterialProperty(), MaterialBase::getGenericZeroMaterialProperty(), BatchMaterial< Tuple, Output, Input >::getIndex(), AddZapdosReactions::getKernelName(), SolutionUserObject::getLocalVarIndex(), Marker::getMarkerValue(), Material::getMaterial(), FEProblemBase::getMaterial(), Material::getMaterialByName(), AuxKernelTempl< ComputeValueType >::getMaterialProperty(), NodalPatchRecovery::getMaterialProperty(), InterfaceMaterial::getMaterialProperty(), Material::getMaterialProperty(), SubProblem::getMaterialPropertyBlockNames(), SubProblem::getMaterialPropertyBoundaryNames(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOld(), NodalPatchRecovery::getMaterialPropertyOld(), InterfaceMaterial::getMaterialPropertyOld(), Material::getMaterialPropertyOld(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOlder(), NodalPatchRecovery::getMaterialPropertyOlder(), InterfaceMaterial::getMaterialPropertyOlder(), Material::getMaterialPropertyOlder(), MeshGenerator::getMesh(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshesByName(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MultiAppTransfer::getMultiApp(), InterfaceMaterial::getNeighborADMaterialProperty(), InterfaceMaterial::getNeighborMaterialProperty(), InterfaceMaterial::getNeighborMaterialPropertyOld(), InterfaceMaterial::getNeighborMaterialPropertyOlder(), Material::getOptionalADMaterialProperty(), Material::getOptionalMaterialProperty(), Material::getOptionalMaterialPropertyOld(), Material::getOptionalMaterialPropertyOlder(), FEProblemBase::getPositionsObject(), FEProblemBase::getPostprocessorValueByName(), AddReactions::getReactionKernelName(), ReporterData::getReporterInfo(), FEProblemBase::getSampler(), Transient::getTimeStepperName(), ProjectedStatefulMaterialStorageAction::getTypeEnum(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), Terminator::handleMessage(), FEProblemBase::hasFunction(), SubProblem::hasFunctor(), SubProblem::hasFunctorWithType(), AdvancedOutput::hasOutputHelper(), FEProblemBase::hasPostprocessor(), FEProblemBase::hasPostprocessorValueByName(), FEProblemBase::hasUserObject(), AdvancedOutput::init(), FEProblemBase::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), AttribName::initFrom(), NestedDivision::initialize(), SolutionScalarAux::initialSetup(), NodalVariableValue::initialSetup(), MultiAppProjectionTransfer::initialSetup(), SolutionUserObject::initialSetup(), AdvancedOutput::initOutputList(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MaterialBase::initStatefulProperties(), Function::integral(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), MeshGenerator::isChildMeshGenerator(), MeshGenerator::isNullMeshName(), MeshGenerator::isParentMeshGenerator(), LinearCombinationFunction::LinearCombinationFunction(), FEProblemBase::logAdd(), LymberopoulosElectronBC::LymberopoulosElectronBC(), Marker::Marker(), Material::Material(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), Distribution::median(), MemoryUsageReporter::MemoryUsageReporter(), MeshGenerator::meshPropertyPrefix(), MooseVariableInterface< T >::MooseVariableInterface(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), NeumannCircuitVoltageMoles_KV::NeumannCircuitVoltageMoles_KV(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), NodalValueSampler::NodalValueSampler(), MooseBaseParameterInterface::objectErrorPrefix(), MeshGenerator::Comparator::operator()(), DOFMapOutput::output(), ProgressOutput::output(), Output::Output(), AdvancedOutput::outputElementalVariables(), ConsoleUtils::outputExecutionInformation(), AdvancedOutput::outputInput(), AdvancedOutput::outputNodalVariables(), AdvancedOutput::outputPostprocessors(), Exodus::outputPostprocessors(), Nemesis::outputPostprocessors(), TableOutput::outputReporter(), AdvancedOutput::outputReporters(), AdvancedOutput::outputScalarVariables(), AdvancedOutput::outputSystemInformation(), AdvancedOutput::outputVectorPostprocessors(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedODEKernel::ParsedODEKernel(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PointVariableSamplerBase::PointVariableSamplerBase(), MultiApp::readCommandLineArguments(), Receiver::Receiver(), Executor::Result::record(), FEProblemBase::registerRandomInterface(), GlobalParamsAction::remove(), MaterialBase::resetQpProperties(), MultiApp::restore(), SakiyamaEnergySecondaryElectronBC::SakiyamaEnergySecondaryElectronBC(), SakiyamaSecondaryElectronBC::SakiyamaSecondaryElectronBC(), ScalarComponentIC::ScalarComponentIC(), SecondaryElectronBC::SecondaryElectronBC(), SecondaryElectronEnergyBC::SecondaryElectronEnergyBC(), MultiApp::setAppOutputFileBase(), MooseMesh::setBoundaryName(), Control::setControllableValue(), Control::setControllableValueByName(), GlobalParamsAction::setDoubleIndexParam(), OutputWarehouse::setFileNumbers(), GlobalParamsAction::setParam(), FEProblemBase::setPostprocessorValueByName(), GlobalParamsAction::setScalarParam(), MooseMesh::setSubdomainName(), GlobalParamsAction::setTripleIndexParam(), Split::setup(), TransientMultiApp::setupApp(), GlobalParamsAction::setVectorParam(), SideCurrent::SideCurrent(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SideValueSampler::SideValueSampler(), TransientMultiApp::solveStep(), UserObject::spatialValue(), StitchedMesh::StitchedMesh(), SubProblem::storeBoundaryDelayedCheckMatProp(), SubProblem::storeBoundaryMatPropName(), SubProblem::storeBoundaryZeroMatProp(), SubProblem::storeSubdomainDelayedCheckMatProp(), SubProblem::storeSubdomainMatPropName(), SubProblem::storeSubdomainZeroMatProp(), MaterialBase::subdomainSetup(), TaggingInterface::TaggingInterface(), VectorPostprocessorVisualizationAux::timestepSetup(), MultiAppDofCopyTransfer::transfer(), TransientMultiApp::TransientMultiApp(), MooseBase::typeAndName(), MooseBaseParameterInterface::uniqueParameterName(), UserObject::UserObject(), UserObjectInterface::userObjectName(), MultiAppTransfer::variableIntegrityCheck(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), AdvancedOutput::wantOutput(), Coupleable::writableCoupledValue(), and Coupleable::writableVariable().
needFV()
void DisplacedProblem::needFV () override virtual
marks this problem as including/needing finite volume functionality.
Implements SubProblem.
Definition at line 1320 of file DisplacedProblem.C.
{
  _mproblem.needFV();
}
nlConverged()
bool DisplacedProblem::nlConverged (const unsigned int nl_sys_num) override virtual
Returns
whether the given nl_sys_num is converged
Reimplemented from SubProblem.
Definition at line 1138 of file DisplacedProblem.C.
{
  return _mproblem.converged(nl_sys_num);
}
nLinearIterations()
unsigned int SubProblem::nLinearIterations (const unsigned int nl_sys_num) const virtual inherited
Reimplemented in FEProblemBase.
Definition at line 725 of file SubProblem.C.
{
  return 0;
}
Referenced by IterationInfo::execute(), and NumLinearIterations::getValue().
nlSys()
DisplacedSystem & DisplacedProblem::nlSys (const unsigned int sys_num) inline
Definition at line 397 of file DisplacedProblem.h.
{
  mooseAssert(sys_num < _displaced_nl.size(),
              "System number greater than the number of nonlinear systems");
  return *_displaced_nl[sys_num];
}
nlSysNum()
unsigned int DisplacedProblem::nlSysNum (const NonlinearSystemName & nl_sys_name) const override virtual
Returns
the nonlinear system number corresponding to the provided nl_sys_name
Implements SubProblem.
Definition at line 1338 of file DisplacedProblem.C.
{
  return _mproblem.nlSysNum(nl_sys_name);
}
nNonlinearIterations()
unsigned int SubProblem::nNonlinearIterations (const unsigned int nl_sys_num) const virtual inherited
Reimplemented in FEProblemBase.
Definition at line 719 of file SubProblem.C.
{
  return 0;
}
Referenced by IterationInfo::execute(), and NumNonlinearIterations::finalize().
nonlocalCouplingMatrix()
const CouplingMatrix & SubProblem::nonlocalCouplingMatrix (const unsigned i) const inline inherited
Returns
the nonlocal coupling matrix for the i'th nonlinear system
Definition at line 634 of file SubProblem.h.
{ return _nonlocal_cm[i]; }
numMatrixTags()
unsigned int DisplacedProblem::numMatrixTags () const override virtual
The total number of tags.
Reimplemented from SubProblem.
Definition at line 448 of file DisplacedProblem.C.
{
  return _mproblem.numMatrixTags();
}
numNonlinearSystems()
std::size_t DisplacedProblem::numNonlinearSystems () const override virtual
Returns
the number of nonlinear systems in the problem
Implements SubProblem.
Definition at line 1296 of file DisplacedProblem.C.
{
  return _mproblem.numNonlinearSystems();
}
numVectorTags()
unsigned int DisplacedProblem::numVectorTags (const Moose::VectorTagType type = Moose::VECTOR_TAG_ANY) const override virtual
The total number of tags, which can be limited to the tag type.
Reimplemented from SubProblem.
Definition at line 400 of file DisplacedProblem.C.
{
  return _mproblem.numVectorTags(type);
}
objectErrorPrefix()
std::string MooseBaseParameterInterface::objectErrorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for an object.
Definition at line 58 of file MooseBaseParameterInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the class \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseParameterInterface::paramErrorMsg().
onTimestepBegin()
void DisplacedProblem::onTimestepBegin () override virtual
Implements SubProblem.
Definition at line 1150 of file DisplacedProblem.C.
{
}
onTimestepEnd()
void DisplacedProblem::onTimestepEnd () override virtual
Implements SubProblem.
Definition at line 1155 of file DisplacedProblem.C.
{
}
operator=()
DisplacedProblem & DisplacedProblem::operator= (DisplacedProblem &&) delete
paramError()
template<typename... Args> void MooseBaseParameterInterface::paramError (const std::string & param, Args... args) const inherited
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseError - only printing a message using the given args.
Definition at line 233 of file MooseBaseParameterInterface.h.
{
  Moose::show_trace = false;
  std::string msg = paramErrorMsg(param, std::forward<Args>(args)...);
  callMooseErrorRaw(msg, &_moose_base->getMooseApp());
  Moose::show_trace = true;
}
Referenced by HierarchicalGridPartitioner::_do_partition(), SetupDebugAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), ADDGKernel::ADDGKernel(), ReporterPointSource::addPoints(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ADNodalKernel::ADNodalKernel(), ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), AdvectiveFluxAux::AdvectiveFluxAux(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), ArrayBodyForce::ArrayBodyForce(), ArrayDGKernel::ArrayDGKernel(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayDirichletBC::ArrayDirichletBC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), ArrayPenaltyDirichletBC::ArrayPenaltyDirichletBC(), ArrayVacuumBC::ArrayVacuumBC(), BlockDeletionGenerator::BlockDeletionGenerator(), BlockWeightedPartitioner::BlockWeightedPartitioner(), BoundsAuxBase::BoundsAuxBase(), BreakMeshByBlockGenerator::BreakMeshByBlockGenerator(), BuildArrayVariableAux::BuildArrayVariableAux(), PiecewiseTabularBase::buildFromFile(), CartesianGridDivision::CartesianGridDivision(), UserObjectInterface::castUserObject(), checkComponent(), MeshGenerator::checkGetMesh(), PostprocessorInterface::checkParam(), Coupleable::checkVar(), MultiAppTransfer::checkVariable(), CircularBoundaryCorrectionGenerator::CircularBoundaryCorrectionGenerator(), CircularBoundaryCorrectionGenerator::circularCenterCalculator(), MultiAppGeneralFieldTransfer::closestToPosition(), CombinerGenerator::CombinerGenerator(), CompositionDT::CompositionDT(), ConcentricCircleMeshGenerator::ConcentricCircleMeshGenerator(), LibtorchNeuralNetControl::conditionalParameterError(), ConstantVectorPostprocessor::ConstantVectorPostprocessor(), ContainsPointAux::ContainsPointAux(), CopyValueAux::CopyValueAux(), Coupleable::Coupleable(), CoupledForceTempl< is_ad >::CoupledForceTempl(), CoupledValueFunctionMaterialTempl< is_ad >::CoupledValueFunctionMaterialTempl(), MultiApp::createApp(), MeshGeneratorSystem::createMeshGenerator(), CylindricalGridDivision::CylindricalGridDivision(), ConstantReporter::declareConstantReporterValues(), AccumulateReporter::declareLateValues(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DGLowerDKernel::DGLowerDKernel(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementLengthAux::ElementLengthAux(), ElementLpNormAux::ElementLpNormAux(), ElementValueSampler::ElementValueSampler(), ReporterPointSource::errorCheck(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), ExtraElementIDAux::ExtraElementIDAux(), ExtraElementIntegerDivision::ExtraElementIntegerDivision(), FEProblemSolve::FEProblemSolve(), FillBetweenCurvesGenerator::FillBetweenCurvesGenerator(), FillBetweenSidesetsGenerator::FillBetweenSidesetsGenerator(), ReporterPointSource::fillPoint(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), InternalSideIndicator::finalize(), FixedPointSolve::FixedPointSolve(), ForcingFunctionAux::ForcingFunctionAux(), FunctionArrayAux::FunctionArrayAux(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorAux::FunctorAux(), FunctorBinnedValuesDivision::FunctorBinnedValuesDivision(), FunctorElementalGradientAuxTempl< is_ad >::FunctorElementalGradientAuxTempl(), FunctorPositions::FunctorPositions(), FunctorVectorElementalAuxTempl< is_ad >::FunctorVectorElementalAuxTempl(), FVFluxBC::FVFluxBC(), FVInterfaceKernel::FVInterfaceKernel(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), FVTwoVarContinuityConstraint::FVTwoVarContinuityConstraint(), AdvancedExtruderGenerator::generate(), BlockDeletionGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundaryDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), BreakMeshByBlockGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), CombinerGenerator::generate(), ExplodeMeshGenerator::generate(), ExtraNodesetGenerator::generate(), FillBetweenCurvesGenerator::generate(), FillBetweenSidesetsGenerator::generate(), GeneratedMeshGenerator::generate(), MeshCollectionGenerator::generate(), MeshExtruderGenerator::generate(), ParsedCurveGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), PropertyReadFile::getBlockData(), PropertyReadFile::getData(), Sampler::getGlobalSamples(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), Sampler::getLocalSamples(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), Sampler::getNextLocalRow(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectName(), HFEMDirichletBC::HFEMDirichletBC(), MultiApp::init(), BlockWeightedPartitioner::initialize(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), PiecewiseConstantFromCSV::initialSetup(), LibtorchControlValuePostprocessor::initialSetup(), ReferenceResidualProblem::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), HistogramVectorPostprocessor::initialSetup(), AddMetaDataGenerator::inputChecker(), IntegratedBC::IntegratedBC(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceValueUserObjectAux::InterfaceValueUserObjectAux(), InterpolatedStatefulMaterialTempl< T >::InterpolatedStatefulMaterialTempl(), InversePowerMethod::InversePowerMethod(), IterationAdaptiveDT::IterationAdaptiveDT(), MultiApp::keepSolutionDuringRestore(), Kernel::Kernel(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LinearCombinationFunction::LinearCombinationFunction(), LowerDIntegratedBC::LowerDIntegratedBC(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), MaterialADConverterTempl< T >::MaterialADConverterTempl(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), PatternedMeshGenerator::mergeSubdomainNameMaps(), MeshCollectionGenerator::MeshCollectionGenerator(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshDivisionAux::MeshDivisionAux(), MeshGenerator::MeshGenerator(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarNodalAuxKernelTempl< ComputeValueType >::MortarNodalAuxKernelTempl(), MultiApp::moveApp(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), NestedDivision::NestedDivision(), NodalBC::NodalBC(), NodalEqualValueConstraint::NodalEqualValueConstraint(), NodalKernel::NodalKernel(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), NodalValueSampler::NodalValueSampler(), Output::Output(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), PatchMeshGenerator::PatchMeshGenerator(), PatternedMeshGenerator::PatternedMeshGenerator(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), PeriodicSegmentalConstraint::PeriodicSegmentalConstraint(), PIDTransientControl::PIDTransientControl(), PlaneDeletionGenerator::PlaneDeletionGenerator(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), PolyLineMeshGenerator::PolyLineMeshGenerator(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), LibmeshPartitioner::prepareBlocksForSubdomainPartitioner(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), PropertyReadFile::PropertyReadFile(), RandomIC::RandomIC(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readXda(), ReferenceResidualProblem::ReferenceResidualProblem(), RefineBlockGenerator::RefineBlockGenerator(), RefineSidesetGenerator::RefineSidesetGenerator(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setPartitioner(), TimeSequenceStepperBase::setupSequence(), SingleRankPartitioner::SingleRankPartitioner(), SphericalGridDivision::SphericalGridDivision(), SymmetryTransformGenerator::SymmetryTransformGenerator(), Terminator::Terminator(), TimeDerivativeAux::TimeDerivativeAux(), Transfer::Transfer(), TransformGenerator::TransformGenerator(), TransientMultiApp::TransientMultiApp(), ParsedCurveGenerator::tSectionSpaceDefiner(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), UserObject::UserObject(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), VolumeAux::VolumeAux(), XYDelaunayGenerator::XYDelaunayGenerator(), and XYMeshLineCutter::XYMeshLineCutter().
paramErrorMsg()
template<typename... Args> std::string MooseBaseParameterInterface::paramErrorMsg (const std::string & param, Args... args) const inline private inherited
Definition at line 171 of file MooseBaseParameterInterface.h.
  {
    auto param_prefix = paramErrorPrefix(_pars, param);
    // With no input location information, append object info (name + type)
    const std::string object_prefix =
        _pars.inputLocation(param).empty() ? objectErrorPrefix("parameter error") : "";
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    // Wrap error message to a separate line from param_prefix if it is about to
    // blow past 100 chars.  But only wrap if the param_prefix is long enough (12
    // chars) for the wrap to buy us much extra length. We don't check object_prefix
    // here because it will go before the parameter error
    if ((param_prefix.size() > 12 && msg.size() + param_prefix.size() > 99) ||
        msg.find("\n") != std::string::npos)
    {
      if (param_prefix.size() > 0 && param_prefix[param_prefix.size() - 1] != ':')
        param_prefix += ":";
      return object_prefix + param_prefix + "\n    " + MooseUtils::replaceAll(msg, "\n", "\n    ");
    }
    return object_prefix + param_prefix + " " + msg;
  }
Referenced by MooseBaseParameterInterface::paramError(), MooseBaseParameterInterface::paramInfo(), and MooseBaseParameterInterface::paramWarning().
parameters()
const InputParameters & MooseBaseParameterInterface::parameters () const inline inherited
Get the parameters of the object.
Returns
The parameters of the object
Definition at line 53 of file MooseBaseParameterInterface.h.
{ return _pars; }
Referenced by SetupDebugAction::act(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), FEProblemBase::addPostprocessor(), FEProblemBase::addPredictor(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), addVariable(), FEProblemBase::addVectorPostprocessor(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), AdvancedOutput::AdvancedOutput(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), Moose::assemble_matrix(), AuxScalarKernel::AuxScalarKernel(), BoundsAuxBase::BoundsAuxBase(), MooseMesh::buildTypedMesh(), UserObjectInterface::castUserObject(), PostprocessorInterface::checkParam(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), Moose::compute_bounds(), Moose::compute_jacobian(), Moose::compute_nearnullspace(), Moose::compute_nullspace(), Moose::compute_postcheck(), Moose::compute_transpose_nullspace(), LibtorchNeuralNetControl::conditionalParameterError(), Console::Console(), MultiApp::createApp(), Postprocessor::declareValue(), DumpObjectsProblem::deduceNecessaryParameters(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), DumpObjectsProblem::dumpObjectHelper(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElectronsFromIonization::ElectronsFromIonization(), Executor::Executor(), Exodus::Exodus(), FEProblem::FEProblem(), FEProblemBase::FEProblemBase(), FixedPointSolve::FixedPointSolve(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GapValueAux::GapValueAux(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), MooseBaseParameterInterface::getCheckedPointerParam(), ExecutorInterface::getExecutor(), Material::getMaterial(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), UserObjectInterface::getUserObjectName(), VectorPostprocessorInterface::getVectorPostprocessorName(), GhostingUserObject::GhostingUserObject(), HphiRadialInterface::HphiRadialInterface(), AttribSystem::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), FullSolveMultiApp::initialSetup(), FEProblemBase::initNullSpaceVectors(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), isValid(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseAppCoordTransform::MooseAppCoordTransform(), MooseVariableInterface< T >::MooseVariableInterface(), MultiApp::MultiApp(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodeFaceConstraint::NodeFaceConstraint(), PatchMeshGenerator::PatchMeshGenerator(), PenetrationAux::PenetrationAux(), PicardSolve::PicardSolve(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), ProjectedStatefulMaterialStorageAction::processProperty(), MultiAppProjectionTransfer::projectSolution(), PropertyReadFile::PropertyReadFile(), PseudoTimestep::PseudoTimestep(), RandomIC::RandomIC(), InputParameterWarehouse::removeInputParameters(), OutputWarehouse::resetFileBase(), MooseAppCoordTransform::setCoordinateSystem(), FEProblemBase::setInputParametersFEProblem(), FEProblem::setInputParametersFEProblem(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SteffensenSolve::SteffensenSolve(), DumpObjectsProblem::stringifyParameters(), TaggingInterface::TaggingInterface(), Transfer::Transfer(), Transient::Transient(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
paramInfo()
template<typename... Args> void MooseBaseParameterInterface::paramInfo (const std::string & param, Args... args) const inherited
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseInfo - only printing a message using the given args.
Definition at line 250 of file MooseBaseParameterInterface.h.
{
  mooseInfo(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by TransientMultiApp::TransientMultiApp().
paramWarning()
template<typename... Args> void MooseBaseParameterInterface::paramWarning (const std::string & param, Args... args) const inherited
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseWarning - only printing a message using the given args.
Definition at line 243 of file MooseBaseParameterInterface.h.
{
  mooseWarning(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by MultiAppNearestNodeTransfer::execute(), FEProblemSolve::FEProblemSolve(), PlaneIDMeshGenerator::generate(), UniqueExtraIDMeshGenerator::generate(), Terminator::initialSetup(), and MooseMesh::MooseMesh().
perfGraph()
PerfGraph & PerfGraphInterface::perfGraph () inherited
Get the PerfGraph.
Definition at line 78 of file PerfGraphInterface.C.
{
  return _pg_moose_app.perfGraph();
}
Referenced by CommonOutputAction::act(), PerfGraphData::finalize(), and PerfGraphOutput::output().
prepare() [1/2]
void DisplacedProblem::prepare (const Elem * elem, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 584 of file DisplacedProblem.C.
{
  for (const auto nl_sys_num : index_range(_displaced_nl))
  {
    _assembly[tid][nl_sys_num]->reinit(elem);
    _displaced_nl[nl_sys_num]->prepare(tid);
    // This method is called outside of residual/Jacobian callbacks during initial condition
    // evaluation
    if (!_mproblem.hasJacobian() || !_mproblem.constJacobian())
      _assembly[tid][nl_sys_num]->prepareJacobianBlock();
    _assembly[tid][nl_sys_num]->prepareResidual();
  }
  _displaced_aux->prepare(tid);
}
prepare() [2/2]
void DisplacedProblem::prepare (const Elem * elem, unsigned int ivar, unsigned int jvar, const std::vector< dof_id_type > & dof_indices, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 615 of file DisplacedProblem.C.
{
  for (const auto nl_sys_num : index_range(_displaced_nl))
  {
    _assembly[tid][nl_sys_num]->reinit(elem);
    _displaced_nl[nl_sys_num]->prepare(tid);
  }
  _displaced_aux->prepare(tid);
  _assembly[tid][currentNlSysNum()]->prepareBlock(ivar, jvar, dof_indices);
}
prepareAssembly()
void DisplacedProblem::prepareAssembly (const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 657 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->prepare();
}
prepareAssemblyNeighbor()
void DisplacedProblem::prepareAssemblyNeighbor (const THREAD_ID tid) virtual
Definition at line 663 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->prepareNeighbor();
}
Referenced by reinitNeighborPhys().
prepareBlockNonlocal()
void DisplacedProblem::prepareBlockNonlocal (unsigned int ivar, unsigned int jvar, const std::vector< dof_id_type > & idof_indices, const std::vector< dof_id_type > & jdof_indices, const THREAD_ID tid) virtual
Definition at line 647 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->prepareBlockNonlocal(ivar, jvar, idof_indices, jdof_indices);
}
prepareFace()
void DisplacedProblem::prepareFace (const Elem * elem, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 607 of file DisplacedProblem.C.
{
  for (auto & nl : _displaced_nl)
    nl->prepareFace(tid, true);
  _displaced_aux->prepareFace(tid, false);
}
prepareFaceShapes()
void DisplacedProblem::prepareFaceShapes (unsigned int var, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 1067 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->copyFaceShapes(var);
}
prepareNeighborShapes()
void DisplacedProblem::prepareNeighborShapes (unsigned int var, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 1073 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->copyNeighborShapes(var);
}
prepareNonlocal()
void DisplacedProblem::prepareNonlocal (const THREAD_ID tid) virtual
Definition at line 601 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->prepareNonlocal();
}
prepareShapes()
void DisplacedProblem::prepareShapes (unsigned int var, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 1061 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->copyShapes(var);
}
refMesh()
MooseMesh & DisplacedProblem::refMesh ()
Definition at line 1132 of file DisplacedProblem.C.
{
  return _ref_mesh;
}
Referenced by updateMesh().
registerTimedSection() [1/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
Returns
The ID of the section - use when starting timing
Definition at line 53 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(timed_section_name, level);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
registerTimedSection() [2/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level, const std::string & live_message, const bool print_dots = true) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
live_message The message to be printed to the screen during execution
print_dots Whether or not progress dots should be printed for this section
Returns
The ID of the section - use when starting timing
Definition at line 64 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(
        timedSectionName(section_name), level, live_message, print_dots);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
registerUnfilledFunctorRequest()
template<typename T > void SubProblem::registerUnfilledFunctorRequest (T * functor_interface, const std::string & functor_name, const THREAD_ID tid) inherited
Register an unfulfilled functor request.
reinitDirac()
bool DisplacedProblem::reinitDirac (const Elem * elem, const THREAD_ID tid) override virtual
Returns true if the Problem has Dirac kernels it needs to compute on elem.
Implements SubProblem.
Definition at line 669 of file DisplacedProblem.C.
{
  std::vector<Point> & points = _dirac_kernel_info.getPoints()[elem].first;
  unsigned int n_points = points.size();
  if (n_points)
  {
    for (const auto nl_sys_num : index_range(_displaced_nl))
    {
      _assembly[tid][nl_sys_num]->reinitAtPhysical(elem, points);
      _displaced_nl[nl_sys_num]->prepare(tid);
    }
    _displaced_aux->prepare(tid);
    reinitElem(elem, tid);
  }
  _assembly[tid][currentNlSysNum()]->prepare();
  return n_points > 0;
}
reinitElem()
void DisplacedProblem::reinitElem (const Elem * elem, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 693 of file DisplacedProblem.C.
{
  for (auto & nl : _displaced_nl)
    nl->reinitElem(elem, tid);
  _displaced_aux->reinitElem(elem, tid);
}
Referenced by reinitDirac(), and reinitElemPhys().
reinitElemFace()
void DisplacedProblem::reinitElemFace (const Elem * elem, unsigned int side, BoundaryID bnd_id, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 720 of file DisplacedProblem.C.
{
  for (const auto nl_sys_num : index_range(_displaced_nl))
  {
    _assembly[tid][nl_sys_num]->reinit(elem, side);
    _displaced_nl[nl_sys_num]->reinitElemFace(elem, side, bnd_id, tid);
  }
  _displaced_aux->reinitElemFace(elem, side, bnd_id, tid);
}
reinitElemFaceRef()
void SubProblem::reinitElemFaceRef (const Elem * elem, unsigned int side, BoundaryID bnd_id, Real tolerance, const std::vector< Point > *const pts, const std::vector< Real > *const weights = nullptr, const THREAD_ID tid = 0) virtual inherited
reinitialize FE objects on a given element on a given side at a given set of reference points and then compute variable data.
Note that this method makes no assumptions about what's been called beforehand, e.g. you don't have to call some prepare method before this one. This is an all-in-one reinit
Reimplemented in FEProblemBase.
Definition at line 832 of file SubProblem.C.
{
  for (const auto nl_sys_num : make_range(numNonlinearSystems()))
  {
    // - Set our _current_elem for proper dof index getting in the moose variables
    // - Reinitialize all of our FE objects so we have current phi, dphi, etc. data
    // Note that our number of shape functions will reflect the number of shapes associated with the
    // interior element while the number of quadrature points will be determined by the passed pts
    // parameter (which presumably will have a number of pts reflective of a facial quadrature rule)
    assembly(tid, nl_sys_num).reinitElemFaceRef(elem, side, tolerance, pts, weights);
    auto & nl = systemBaseNonlinear(nl_sys_num);
    // Actually get the dof indices in the moose variables
    nl.prepare(tid);
    // Let's finally compute our variable values!
    nl.reinitElemFace(elem, side, bnd_id, tid);
  }
  // do same for aux as for nl
  systemBaseAuxiliary().prepare(tid);
  systemBaseAuxiliary().reinitElemFace(elem, side, bnd_id, tid);
  // With the dof indices set in the moose variables, now let's properly size
  // our local residuals/Jacobians
  auto & current_assembly = assembly(tid, currentNlSysNum());
  if (currentlyComputingJacobian() || currentlyComputingResidualAndJacobian())
    current_assembly.prepareJacobianBlock();
  if (!currentlyComputingJacobian())
    current_assembly.prepareResidual();
}
Referenced by FEProblemBase::reinitElemFaceRef().
reinitElemNeighborAndLowerD()
void DisplacedProblem::reinitElemNeighborAndLowerD (const Elem * elem, unsigned int side, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 862 of file DisplacedProblem.C.
{
  reinitNeighbor(elem, side, tid);
  const Elem * lower_d_elem = _mesh.getLowerDElem(elem, side);
  if (lower_d_elem && lower_d_elem->subdomain_id() == Moose::INTERNAL_SIDE_LOWERD_ID)
    reinitLowerDElem(lower_d_elem, tid);
  else
  {
    // with mesh refinement, lower-dimensional element might be defined on neighbor side
    auto & neighbor = _assembly[tid][currentNlSysNum()]->neighbor();
    auto & neighbor_side = _assembly[tid][currentNlSysNum()]->neighborSide();
    const Elem * lower_d_elem_neighbor = _mesh.getLowerDElem(neighbor, neighbor_side);
    if (lower_d_elem_neighbor &&
        lower_d_elem_neighbor->subdomain_id() == Moose::INTERNAL_SIDE_LOWERD_ID)
    {
      auto qps = _assembly[tid][currentNlSysNum()]->qPointsFaceNeighbor().stdVector();
      std::vector<Point> reference_points;
      FEInterface::inverse_map(
          lower_d_elem_neighbor->dim(), FEType(), lower_d_elem_neighbor, qps, reference_points);
      reinitLowerDElem(lower_d_elem_neighbor, tid, &qps);
    }
  }
}
reinitElemPhys()
void DisplacedProblem::reinitElemPhys (const Elem * elem, const std::vector< Point > & phys_points_in_elem, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 701 of file DisplacedProblem.C.
{
  mooseAssert(_mesh.queryElemPtr(elem->id()) == elem,
              "Are you calling this method with a undisplaced mesh element?");
  for (const auto nl_sys_num : index_range(_displaced_nl))
  {
    _assembly[tid][nl_sys_num]->reinitAtPhysical(elem, phys_points_in_elem);
    _displaced_nl[nl_sys_num]->prepare(tid);
    _assembly[tid][nl_sys_num]->prepare();
  }
  _displaced_aux->prepare(tid);
  reinitElem(elem, tid);
}
reinitFVFace()
void SubProblem::reinitFVFace (const THREAD_ID tid, const FaceInfo & fi) inherited
reinitialize the finite volume assembly data for the provided face and thread
Definition at line 1231 of file SubProblem.C.
{
  for (const auto nl : make_range(numNonlinearSystems()))
    assembly(tid, nl).reinitFVFace(fi);
}
reinitLowerDElem()
void SubProblem::reinitLowerDElem (const Elem * lower_d_elem, const THREAD_ID tid, const std::vector< Point > *const pts = nullptr, const std::vector< Real > *const weights = nullptr) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 909 of file SubProblem.C.
{
  for (const auto nl_sys_num : make_range(numNonlinearSystems()))
  {
    // - Set our _current_lower_d_elem for proper dof index getting in the moose variables
    // - Reinitialize all of our lower-d FE objects so we have current phi, dphi, etc. data
    assembly(tid, nl_sys_num).reinitLowerDElem(elem, pts, weights);
    auto & nl = systemBaseNonlinear(nl_sys_num);
    // Actually get the dof indices in the moose variables
    nl.prepareLowerD(tid);
    // With the dof indices set in the moose variables, now let's properly size
    // our local residuals/Jacobians
    assembly(tid, nl_sys_num).prepareLowerD();
    // Let's finally compute our variable values!
    nl.reinitLowerD(tid);
  }
  // do same for aux as for nl
  systemBaseAuxiliary().prepareLowerD(tid);
  systemBaseAuxiliary().reinitLowerD(tid);
}
Referenced by Moose::Mortar::loopOverMortarSegments(), reinitElemNeighborAndLowerD(), and FEProblemBase::reinitLowerDElem().
reinitMortarElem()
void SubProblem::reinitMortarElem (const Elem * elem, const THREAD_ID tid = 0) inherited
Reinit a mortar element to obtain a valid JxW.
Definition at line 946 of file SubProblem.C.
{
  for (const auto nl_sys_num : make_range(numNonlinearSystems()))
    assembly(tid, nl_sys_num).reinitMortarElem(elem);
}
Referenced by Moose::Mortar::loopOverMortarSegments().
reinitNeighbor() [1/2]
void DisplacedProblem::reinitNeighbor (const Elem * elem, unsigned int side, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 772 of file DisplacedProblem.C.
{
  reinitNeighbor(elem, side, tid, nullptr);
}
Referenced by reinitElemNeighborAndLowerD(), and reinitNeighbor().
reinitNeighbor() [2/2]
void DisplacedProblem::reinitNeighbor (const Elem * elem, unsigned int side, const THREAD_ID tid, const std::vector< Point > * neighbor_reference_points)
reinitialize neighbor routine
Parameters
elem The element driving the reinit (note that this is not the neighbor)
side The side, e.g. face, of the elem that we want to reinit
tid The thread for which we are reiniting
neighbor_reference_points Specify the referrence points for the neighbor element. Useful if the element and neighbor faces are not coincident
Definition at line 778 of file DisplacedProblem.C.
{
  setNeighborSubdomainID(elem, side, tid);
  const Elem * neighbor = elem->neighbor_ptr(side);
  unsigned int neighbor_side = neighbor->which_neighbor_am_i(elem);
  for (const auto nl_sys_num : index_range(_displaced_nl))
  {
    _assembly[tid][nl_sys_num]->reinitElemAndNeighbor(
        elem, side, neighbor, neighbor_side, neighbor_reference_points);
    _displaced_nl[nl_sys_num]->prepareNeighbor(tid);
    // Called during stateful material property evaluation outside of solve
    _assembly[tid][nl_sys_num]->prepareNeighbor();
  }
  _displaced_aux->prepareNeighbor(tid);
  BoundaryID bnd_id = 0; // some dummy number (it is not really used for anything, right now)
  for (auto & nl : _displaced_nl)
  {
    nl->reinitElemFace(elem, side, bnd_id, tid);
    nl->reinitNeighborFace(neighbor, neighbor_side, bnd_id, tid);
  }
  _displaced_aux->reinitElemFace(elem, side, bnd_id, tid);
  _displaced_aux->reinitNeighborFace(neighbor, neighbor_side, bnd_id, tid);
}
reinitNeighborFaceRef()
void SubProblem::reinitNeighborFaceRef (const Elem * neighbor_elem, unsigned int neighbor_side, BoundaryID bnd_id, Real tolerance, const std::vector< Point > *const pts, const std::vector< Real > *const weights = nullptr, const THREAD_ID tid = 0) virtual inherited
reinitialize FE objects on a given neighbor element on a given side at a given set of reference points and then compute variable data.
Note that this method makes no assumptions about what's been called beforehand, e.g. you don't have to call some prepare method before this one. This is an all-in-one reinit
Reimplemented in FEProblemBase.
Definition at line 872 of file SubProblem.C.
{
  for (const auto nl_sys_num : make_range(numNonlinearSystems()))
  {
    // - Set our _current_neighbor_elem for proper dof index getting in the moose variables
    // - Reinitialize all of our FE objects so we have current phi, dphi, etc. data
    // Note that our number of shape functions will reflect the number of shapes associated with the
    // interior element while the number of quadrature points will be determined by the passed pts
    // parameter (which presumably will have a number of pts reflective of a facial quadrature rule)
    assembly(tid, nl_sys_num)
        .reinitNeighborFaceRef(neighbor_elem, neighbor_side, tolerance, pts, weights);
    auto & nl = systemBaseNonlinear(nl_sys_num);
    // Actually get the dof indices in the moose variables
    nl.prepareNeighbor(tid);
    // Let's finally compute our variable values!
    nl.reinitNeighborFace(neighbor_elem, neighbor_side, bnd_id, tid);
  }
  // do same for aux as for nl
  systemBaseAuxiliary().prepareNeighbor(tid);
  systemBaseAuxiliary().reinitNeighborFace(neighbor_elem, neighbor_side, bnd_id, tid);
  // With the dof indices set in the moose variables, now let's properly size
  // our local residuals/Jacobians
  assembly(tid, currentNlSysNum()).prepareNeighbor();
}
Referenced by FEProblemBase::reinitNeighborFaceRef().
reinitNeighborLowerDElem()
void SubProblem::reinitNeighborLowerDElem (const Elem * elem, const THREAD_ID tid = 0) inherited
reinitialize a neighboring lower dimensional element
Definition at line 939 of file SubProblem.C.
{
  for (const auto nl_sys_num : make_range(numNonlinearSystems()))
    assembly(tid, nl_sys_num).reinitNeighborLowerDElem(elem);
}
Referenced by Moose::Mortar::loopOverMortarSegments().
reinitNeighborPhys() [1/2]
void DisplacedProblem::reinitNeighborPhys (const Elem * neighbor, const std::vector< Point > & physical_points, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 836 of file DisplacedProblem.C.
{
  mooseAssert(_mesh.queryElemPtr(neighbor->id()) == neighbor,
              "Are you calling this method with a undisplaced mesh element?");
  for (const auto nl_sys_num : index_range(_displaced_nl))
  {
    // Reinit shape functions
    _assembly[tid][nl_sys_num]->reinitNeighborAtPhysical(neighbor, physical_points);
    // Set the neighbor dof indices
    _displaced_nl[nl_sys_num]->prepareNeighbor(tid);
  }
  _displaced_aux->prepareNeighbor(tid);
  prepareAssemblyNeighbor(tid);
  // Compute values at the points
  for (auto & nl : _displaced_nl)
    nl->reinitNeighbor(neighbor, tid);
  _displaced_aux->reinitNeighbor(neighbor, tid);
}
reinitNeighborPhys() [2/2]
void DisplacedProblem::reinitNeighborPhys (const Elem * neighbor, unsigned int neighbor_side, const std::vector< Point > & physical_points, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 809 of file DisplacedProblem.C.
{
  mooseAssert(_mesh.queryElemPtr(neighbor->id()) == neighbor,
              "Are you calling this method with a undisplaced mesh element?");
  for (const auto nl_sys_num : index_range(_displaced_nl))
  {
    // Reinit shape functions
    _assembly[tid][nl_sys_num]->reinitNeighborAtPhysical(neighbor, neighbor_side, physical_points);
    // Set the neighbor dof indices
    _displaced_nl[nl_sys_num]->prepareNeighbor(tid);
  }
  _displaced_aux->prepareNeighbor(tid);
  prepareAssemblyNeighbor(tid);
  // Compute values at the points
  for (auto & nl : _displaced_nl)
    nl->reinitNeighborFace(neighbor, neighbor_side, 0, tid);
  _displaced_aux->reinitNeighborFace(neighbor, neighbor_side, 0, tid);
}
reinitNode()
void DisplacedProblem::reinitNode (const Node * node, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 734 of file DisplacedProblem.C.
{
  for (const auto nl_sys_num : index_range(_displaced_nl))
  {
    _assembly[tid][nl_sys_num]->reinit(node);
    _displaced_nl[nl_sys_num]->reinitNode(node, tid);
  }
  _displaced_aux->reinitNode(node, tid);
}
reinitNodeFace()
void DisplacedProblem::reinitNodeFace (const Node * node, BoundaryID bnd_id, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 745 of file DisplacedProblem.C.
{
  for (const auto nl_sys_num : index_range(_displaced_nl))
  {
    _assembly[tid][nl_sys_num]->reinit(node);
    _displaced_nl[nl_sys_num]->reinitNodeFace(node, bnd_id, tid);
  }
  _displaced_aux->reinitNodeFace(node, bnd_id, tid);
}
reinitNodes()
void DisplacedProblem::reinitNodes (const std::vector< dof_id_type > & nodes, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 756 of file DisplacedProblem.C.
{
  for (auto & nl : _displaced_nl)
    nl->reinitNodes(nodes, tid);
  _displaced_aux->reinitNodes(nodes, tid);
}
reinitNodesNeighbor()
void DisplacedProblem::reinitNodesNeighbor (const std::vector< dof_id_type > & nodes, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 764 of file DisplacedProblem.C.
{
  for (auto & nl : _displaced_nl)
    nl->reinitNodesNeighbor(nodes, tid);
  _displaced_aux->reinitNodesNeighbor(nodes, tid);
}
reinitOffDiagScalars()
void DisplacedProblem::reinitOffDiagScalars (const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 899 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->prepareOffDiagScalar();
}
reinitScalars()
void DisplacedProblem::reinitScalars (const THREAD_ID tid, bool reinit_for_derivative_reordering = false) override virtual
fills the VariableValue arrays for scalar variables from the solution vector
Parameters
tid The thread id
reinit_for_derivative_reordering A flag indicating whether we are reinitializing for the purpose of re-ordering derivative information for ADNodalBCs
Implements SubProblem.
Definition at line 890 of file DisplacedProblem.C.
{
  for (auto & nl : _displaced_nl)
    nl->reinitScalars(tid, reinit_for_derivative_reordering);
  _displaced_aux->reinitScalars(tid, reinit_for_derivative_reordering);
}
removeAlgebraicGhostingFunctor()
void SubProblem::removeAlgebraicGhostingFunctor (GhostingFunctor & algebraic_gf) inherited
Remove an algebraic ghosting functor from this problem's DofMaps.
Definition at line 1019 of file SubProblem.C.
{
  EquationSystems & eq = es();
  const auto n_sys = eq.n_systems();
#ifndef NDEBUG
  const DofMap & nl_dof_map = eq.get_system(0).get_dof_map();
  const bool found_in_root_sys =
      std::find(nl_dof_map.algebraic_ghosting_functors_begin(),
                nl_dof_map.algebraic_ghosting_functors_end(),
                &algebraic_gf) != nl_dof_map.algebraic_ghosting_functors_end();
  const bool found_in_our_map =
      _root_alg_gf_to_sys_clones.find(&algebraic_gf) != _root_alg_gf_to_sys_clones.end();
  mooseAssert(found_in_root_sys == found_in_our_map,
              "If the ghosting functor exists in the root DofMap, then we need to have a key for "
              "it in our gf to clones map");
#endif
  eq.get_system(0).get_dof_map().remove_algebraic_ghosting_functor(algebraic_gf);
  auto it = _root_alg_gf_to_sys_clones.find(&algebraic_gf);
  if (it == _root_alg_gf_to_sys_clones.end())
    return;
  auto & clones_vec = it->second;
  mooseAssert((n_sys - 1) == clones_vec.size(),
              "The size of the gf clones vector doesn't match the number of systems minus one");
  if (clones_vec.empty())
  {
    mooseAssert(n_sys == 1, "The clones vector should only be empty if there is only one system");
    return;
  }
  for (const auto i : make_range(n_sys))
    eq.get_system(i + 1).get_dof_map().remove_algebraic_ghosting_functor(*clones_vec[i]);
  _root_alg_gf_to_sys_clones.erase(it->first);
}
removeCouplingGhostingFunctor()
void SubProblem::removeCouplingGhostingFunctor (GhostingFunctor & coupling_gf) inherited
Remove a coupling ghosting functor from this problem's DofMaps.
Definition at line 1059 of file SubProblem.C.
{
  EquationSystems & eq = es();
  const auto num_nl_sys = numNonlinearSystems();
  if (!num_nl_sys)
    return;
#ifndef NDEBUG
  const DofMap & nl_dof_map = eq.get_system(0).get_dof_map();
  const bool found_in_root_sys = std::find(nl_dof_map.coupling_functors_begin(),
                                           nl_dof_map.coupling_functors_end(),
                                           &coupling_gf) != nl_dof_map.coupling_functors_end();
  const bool found_in_our_map =
      _root_coupling_gf_to_sys_clones.find(&coupling_gf) != _root_coupling_gf_to_sys_clones.end();
  mooseAssert(found_in_root_sys == found_in_our_map,
              "If the ghosting functor exists in the root DofMap, then we need to have a key for "
              "it in our gf to clones map");
#endif
  eq.get_system(0).get_dof_map().remove_coupling_functor(coupling_gf);
  auto it = _root_coupling_gf_to_sys_clones.find(&coupling_gf);
  if (it == _root_coupling_gf_to_sys_clones.end())
    return;
  auto & clones_vec = it->second;
  mooseAssert((num_nl_sys - 1) == clones_vec.size(),
              "The size of the gf clones vector doesn't match the number of systems minus one");
  if (clones_vec.empty())
  {
    mooseAssert(num_nl_sys == 1,
                "The clones vector should only be empty if there is only one nonlinear system");
    return;
  }
  for (const auto i : make_range(num_nl_sys))
    eq.get_system(i + 1).get_dof_map().remove_coupling_functor(*clones_vec[i]);
  _root_coupling_gf_to_sys_clones.erase(it->first);
}
residualSetup()
void DisplacedProblem::residualSetup () override virtual
Reimplemented from SubProblem.
Definition at line 1244 of file DisplacedProblem.C.
{
  SubProblem::residualSetup();
  for (auto & nl : _displaced_nl)
    nl->residualSetup();
  _displaced_aux->residualSetup();
}
restoreOldSolutions()
void DisplacedProblem::restoreOldSolutions () virtual
Restore old solutions from the backup vectors and deallocate them.
Definition at line 204 of file DisplacedProblem.C.
{
  for (auto & displaced_nl : _displaced_nl)
    displaced_nl->restoreOldSolutions();
  _displaced_aux->restoreOldSolutions();
}
restrictionBoundaryCheckName()
std::string SubProblem::restrictionBoundaryCheckName (BoundaryID check_id) private inherited
Definition at line 748 of file SubProblem.C.
{
  return mesh().getMesh().get_boundary_info().sideset_name(check_id);
}
Referenced by SubProblem::checkBoundaryMatProps().
restrictionSubdomainCheckName()
std::string SubProblem::restrictionSubdomainCheckName (SubdomainID check_id) private inherited
Helper functions for checking MaterialProperties.
Definition at line 737 of file SubProblem.C.
{
  // TODO: Put a better a interface in MOOSE
  std::map<subdomain_id_type, std::string> & name_map = mesh().getMesh().set_subdomain_name_map();
  std::map<subdomain_id_type, std::string>::const_iterator pos = name_map.find(check_id);
  if (pos != name_map.end())
    return pos->second;
  return "";
}
Referenced by SubProblem::checkBlockMatProps().
safeAccessTaggedMatrices()
bool DisplacedProblem::safeAccessTaggedMatrices () const override virtual
Is it safe to access the tagged matrices.
Reimplemented from SubProblem.
Definition at line 1308 of file DisplacedProblem.C.
{
  return _mproblem.safeAccessTaggedMatrices();
}
safeAccessTaggedVectors()
bool DisplacedProblem::safeAccessTaggedVectors () const override virtual
Is it safe to access the tagged vectors.
Reimplemented from SubProblem.
Definition at line 1314 of file DisplacedProblem.C.
{
  return _mproblem.safeAccessTaggedVectors();
}
saveOldSolutions()
void DisplacedProblem::saveOldSolutions () virtual
Allocate vectors and save old solutions into them.
Definition at line 196 of file DisplacedProblem.C.
{
  for (auto & displaced_nl : _displaced_nl)
    displaced_nl->saveOldSolutions();
  _displaced_aux->saveOldSolutions();
}
selectVectorTagsFromSystem()
void SubProblem::selectVectorTagsFromSystem (const SystemBase & system, const std::vector< VectorTag > & input_vector_tags, std::set< TagID > & selected_tags) static inherited
Select the vector tags which belong to a specific system.
Parameters
system Reference to the nonlinear system
input_vector_tags A vector of vector tags
selected_tags A set which gets populated by the tag-ids that belong to the system
Definition at line 267 of file SubProblem.C.
{
  selected_tags.clear();
  for (const auto & vector_tag : input_vector_tags)
    if (system.hasVector(vector_tag._id))
      selected_tags.insert(vector_tag._id);
}
Referenced by FEProblemBase::computeResidual(), FEProblemBase::computeResidualAndJacobian(), and ComputeResidualAndJacobianThread::determineObjectWarehouses().
setActiveElementalMooseVariables()
void SubProblem::setActiveElementalMooseVariables (const std::set< MooseVariableFieldBase * > & moose_vars, const THREAD_ID tid) virtual inherited
Set the MOOSE variables to be reinited on each element.
Parameters
moose_vars A set of variables that need to be reinited each time reinit() is called.
tid The thread id
Reimplemented in FEProblemBase.
Definition at line 410 of file SubProblem.C.
{
  if (!moose_vars.empty())
  {
    _has_active_elemental_moose_variables[tid] = 1;
    _active_elemental_moose_variables[tid] = moose_vars;
  }
}
Referenced by FEProblemBase::setActiveElementalMooseVariables().
setActiveFEVariableCoupleableMatrixTags()
void SubProblem::setActiveFEVariableCoupleableMatrixTags (std::set< TagID > & mtags, const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 330 of file SubProblem.C.
{
  _active_fe_var_coupleable_matrix_tags[tid] = mtags;
}
Referenced by FEProblemBase::setActiveFEVariableCoupleableMatrixTags().
setActiveFEVariableCoupleableVectorTags()
void SubProblem::setActiveFEVariableCoupleableVectorTags (std::set< TagID > & vtags, const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 336 of file SubProblem.C.
{
  _active_fe_var_coupleable_vector_tags[tid] = vtags;
  for (const auto nl_sys_num : make_range(numNonlinearSystems()))
    systemBaseNonlinear(nl_sys_num).setActiveVariableCoupleableVectorTags(vtags, tid);
  systemBaseAuxiliary().setActiveVariableCoupleableVectorTags(vtags, tid);
}
Referenced by FEProblemBase::setActiveFEVariableCoupleableVectorTags().
setActiveScalarVariableCoupleableMatrixTags()
void SubProblem::setActiveScalarVariableCoupleableMatrixTags (std::set< TagID > & mtags, const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 369 of file SubProblem.C.
{
  _active_sc_var_coupleable_matrix_tags[tid] = mtags;
}
Referenced by FEProblemBase::setActiveScalarVariableCoupleableMatrixTags().
setActiveScalarVariableCoupleableVectorTags()
void SubProblem::setActiveScalarVariableCoupleableVectorTags (std::set< TagID > & vtags, const THREAD_ID tid) virtual inherited
Reimplemented in FEProblemBase.
Definition at line 376 of file SubProblem.C.
{
  _active_sc_var_coupleable_vector_tags[tid] = vtags;
  for (const auto nl_sys_num : make_range(numNonlinearSystems()))
    systemBaseNonlinear(nl_sys_num).setActiveScalarVariableCoupleableVectorTags(vtags, tid);
  systemBaseAuxiliary().setActiveScalarVariableCoupleableVectorTags(vtags, tid);
}
Referenced by FEProblemBase::setActiveScalarVariableCoupleableVectorTags().
setCurrentBoundaryID()
void SubProblem::setCurrentBoundaryID (BoundaryID bid, const THREAD_ID tid) inherited
sets the current boundary ID in assembly
Definition at line 754 of file SubProblem.C.
{
  for (const auto nl_sys_num : make_range(numNonlinearSystems()))
    assembly(tid, nl_sys_num).setCurrentBoundaryID(bid);
}
setCurrentlyComputingJacobian()
void SubProblem::setCurrentlyComputingJacobian (const bool currently_computing_jacobian) inline inherited
Set whether or not the problem is in the process of computing the Jacobian.
Definition at line 644 of file SubProblem.h.
  {
    _currently_computing_jacobian = currently_computing_jacobian;
  }
Referenced by FEProblemBase::computeResidualAndJacobian().
setCurrentlyComputingResidual()
virtual void SubProblem::setCurrentlyComputingResidual (const bool currently_computing_residual) inline virtual inherited
Set whether or not the problem is in the process of computing the residual.
Reimplemented in FEProblemBase.
Definition at line 680 of file SubProblem.h.
  {
    _currently_computing_residual = currently_computing_residual;
  }
setCurrentlyComputingResidualAndJacobian()
void SubProblem::setCurrentlyComputingResidualAndJacobian (bool currently_computing_residual_and_jacobian) inline inherited
Set whether or not the problem is in the process of computing the Jacobian.
Definition at line 1391 of file SubProblem.h.
{
  _currently_computing_residual_and_jacobian = currently_computing_residual_and_jacobian;
}
Referenced by FEProblemBase::computeResidualAndJacobian().
setCurrentSubdomainID()
void DisplacedProblem::setCurrentSubdomainID (const Elem * elem, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 631 of file DisplacedProblem.C.
{
  SubdomainID did = elem->subdomain_id();
  for (auto & assembly : _assembly[tid])
    assembly->setCurrentSubdomainID(did);
}
setFunctorOutput()
void SubProblem::setFunctorOutput (bool set_output) inline inherited
Setter for debug functor output.
Definition at line 878 of file SubProblem.h.
{ _output_functors = set_output; }
setNeighborSubdomainID()
void DisplacedProblem::setNeighborSubdomainID (const Elem * elem, unsigned int side, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 639 of file DisplacedProblem.C.
{
  SubdomainID did = elem->neighbor_ptr(side)->subdomain_id();
  for (auto & assembly : _assembly[tid])
    assembly->setCurrentNeighborSubdomainID(did);
}
Referenced by reinitNeighbor().
setResidual()
void DisplacedProblem::setResidual (NumericVector< Number > & residual, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 960 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->setResidual(
      residual,
      Assembly::GlobalDataKey{},
      getVectorTag(_displaced_nl[currentNlSysNum()]->residualVectorTag()));
}
setResidualNeighbor()
void DisplacedProblem::setResidualNeighbor (NumericVector< Number > & residual, const THREAD_ID tid) override virtual
Implements SubProblem.
Definition at line 969 of file DisplacedProblem.C.
{
  _assembly[tid][currentNlSysNum()]->setResidualNeighbor(
      residual,
      Assembly::GlobalDataKey{},
      getVectorTag(_displaced_nl[currentNlSysNum()]->residualVectorTag()));
}
showFunctorRequestors()
void SubProblem::showFunctorRequestors () const private inherited
Lists all functors and all the objects that requested them.
Definition at line 1206 of file SubProblem.C.
{
  for (const auto & [functor, requestors] : _functor_to_requestors)
  {
    _console << "[DBG] Requestors for wrapped functor "
             << std::regex_replace(functor, std::regex("wraps_"), "") << std::endl;
    _console << "[DBG] " << MooseUtils::join(requestors, " ") << std::endl;
  }
}
Referenced by SubProblem::initialSetup().
showFunctors()
void SubProblem::showFunctors () const private inherited
Lists all functors in the problem.
Definition at line 1194 of file SubProblem.C.
{
  _console << "[DBG] Wrapped functors found in Subproblem" << std::endl;
  std::string functor_names = "[DBG] ";
  for (const auto & functor_pair : _functors[0])
    functor_names += std::regex_replace(functor_pair.first, std::regex("wraps_"), "") + " ";
  if (functor_names.size())
    functor_names.pop_back();
  _console << functor_names << std::endl;
}
Referenced by SubProblem::initialSetup().
storeBoundaryDelayedCheckMatProp()
void SubProblem::storeBoundaryDelayedCheckMatProp (const std::string & requestor, BoundaryID boundary_id, const std::string & name) virtual inherited
Adds to a map based on boundary ids of material properties to validate.
Parameters
requestor The MOOSE object name requesting the material property
boundary_id The block id for the MaterialProperty
name The name of the property
Definition at line 582 of file SubProblem.C.
{
  _map_boundary_material_props_check[boundary_id].insert(std::make_pair(requestor, name));
}
Referenced by MaterialPropertyInterface::checkMaterialProperty().
storeBoundaryMatPropName()
void SubProblem::storeBoundaryMatPropName (BoundaryID boundary_id, const std::string & name) virtual inherited
Adds the given material property to a storage map based on boundary ids.
This is method is called from within the Material class when the property is first registered.
Parameters
boundary_id The block id for the MaterialProperty
name The name of the property
Definition at line 556 of file SubProblem.C.
{
  _map_boundary_material_props[boundary_id].insert(name);
}
Referenced by MaterialBase::registerPropName().
storeBoundaryZeroMatProp()
void SubProblem::storeBoundaryZeroMatProp (BoundaryID boundary_id, const MaterialPropertyName & name) virtual inherited
Adds to a map based on boundary ids of material properties for which a zero value can be returned.
Thes properties are optional and will not trigger a missing material property error.
Parameters
boundary_id The block id for the MaterialProperty
name The name of the property
Definition at line 568 of file SubProblem.C.
{
  _zero_boundary_material_props[boundary_id].insert(name);
}
Referenced by MaterialBase::getGenericZeroMaterialPropertyByName().
storeSubdomainDelayedCheckMatProp()
void SubProblem::storeSubdomainDelayedCheckMatProp (const std::string & requestor, SubdomainID block_id, const std::string & name) virtual inherited
Adds to a map based on block ids of material properties to validate.
Parameters
block_id The block id for the MaterialProperty
name The name of the property
Definition at line 574 of file SubProblem.C.
{
  _map_block_material_props_check[block_id].insert(std::make_pair(requestor, name));
}
Referenced by MaterialPropertyInterface::checkMaterialProperty().
storeSubdomainMatPropName()
void SubProblem::storeSubdomainMatPropName (SubdomainID block_id, const std::string & name) virtual inherited
Adds the given material property to a storage map based on block ids.
This is method is called from within the Material class when the property is first registered.
Parameters
block_id The block id for the MaterialProperty
name The name of the property
Definition at line 550 of file SubProblem.C.
{
  _map_block_material_props[block_id].insert(name);
}
Referenced by MaterialBase::registerPropName().
storeSubdomainZeroMatProp()
void SubProblem::storeSubdomainZeroMatProp (SubdomainID block_id, const MaterialPropertyName & name) virtual inherited
Adds to a map based on block ids of material properties for which a zero value can be returned.
Thes properties are optional and will not trigger a missing material property error.
Parameters
block_id The block id for the MaterialProperty
name The name of the property
Definition at line 562 of file SubProblem.C.
{
  _zero_block_material_props[block_id].insert(name);
}
Referenced by MaterialBase::getGenericZeroMaterialPropertyByName().
syncSolutions() [1/2]
void DisplacedProblem::syncSolutions () virtual
Copy the solutions on the undisplaced systems to the displaced systems.
Definition at line 212 of file DisplacedProblem.C.
{
  TIME_SECTION("syncSolutions", 5, "Syncing Displaced Solutions");
  for (const auto nl_sys_num : index_range(_displaced_nl))
  {
    auto & displaced_nl = _displaced_nl[nl_sys_num];
    mooseAssert(nl_sys_num == displaced_nl->number(),
                "We should have designed things such that the nl system numbers make their system "
                "numbering in the EquationSystems object");
    (*displaced_nl->sys().solution) =
        *_mproblem.getNonlinearSystemBase(displaced_nl->number()).currentSolution();
    displaced_nl->update();
  }
  (*_displaced_aux->sys().solution) = *_mproblem.getAuxiliarySystem().currentSolution();
}
Referenced by updateMesh().
syncSolutions() [2/2]
void DisplacedProblem::syncSolutions (const std::map< unsigned int, const NumericVector< Number > * > & nl_solns, const NumericVector< Number > & aux_soln) virtual
Synchronize the solutions on the displaced systems to the given solutions.
The nonlinear solutions argument is a map from the nonlinear system number to the solution that we want to set that nonlinear system's solution to
Definition at line 230 of file DisplacedProblem.C.
{
  TIME_SECTION("syncSolutions", 5, "Syncing Displaced Solutions");
  for (const auto [nl_sys_num, nl_soln] : nl_solns)
  {
    (*_displaced_nl[nl_sys_num]->sys().solution) = *nl_soln;
    _displaced_nl[nl_sys_num]->update();
  }
  (*_displaced_aux->sys().solution) = aux_soln;
}
systemBaseAuxiliary() [1/2]
virtual const SystemBase & DisplacedProblem::systemBaseAuxiliary () const inline override virtual
Return the auxiliary system object as a base class reference.
Implements SubProblem.
Definition at line 62 of file DisplacedProblem.h.
{ return *_displaced_aux; }
systemBaseAuxiliary() [2/2]
virtual SystemBase & DisplacedProblem::systemBaseAuxiliary () inline override virtual
Implements SubProblem.
Definition at line 63 of file DisplacedProblem.h.
{ return *_displaced_aux; }
systemBaseNonlinear() [1/2]
const SystemBase & DisplacedProblem::systemBaseNonlinear (const unsigned int sys_num) const inline override virtual
Return the nonlinear system object as a base class reference given the system number.
Implements SubProblem.
Definition at line 405 of file DisplacedProblem.h.
{
  mooseAssert(sys_num < _displaced_nl.size(),
              "System number greater than the number of nonlinear systems");
  return *_displaced_nl[sys_num];
}
systemBaseNonlinear() [2/2]
SystemBase & DisplacedProblem::systemBaseNonlinear (const unsigned int sys_num) inline override virtual
Implements SubProblem.
Definition at line 413 of file DisplacedProblem.h.
{
  mooseAssert(sys_num < _displaced_nl.size(),
              "System number greater than the number of nonlinear systems");
  return *_displaced_nl[sys_num];
}
terminateSolve()
virtual void Problem::terminateSolve () inline virtual inherited
Allow objects to request clean termination of the solve.
Definition at line 37 of file Problem.h.
{ _termination_requested = true; };
Referenced by Terminator::execute().
timedSectionName()
std::string PerfGraphInterface::timedSectionName (const std::string & section_name) const protected inherited
Returns
The name of the timed section with the name section_name.
Optionally adds a prefix if one is defined.
Definition at line 47 of file PerfGraphInterface.C.
{
  return _prefix.empty() ? "" : (_prefix + "::") + section_name;
}
Referenced by PerfGraphInterface::registerTimedSection().
timestepSetup()
void DisplacedProblem::timestepSetup () override virtual
Reimplemented from SubProblem.
Definition at line 1224 of file DisplacedProblem.C.
{
  SubProblem::timestepSetup();
  for (auto & nl : _displaced_nl)
    nl->timestepSetup();
  _displaced_aux->timestepSetup();
}
type()
const std::string & MooseBase::type () const inline inherited
Get the type of this class.
Returns
the name of the type of this class
Definition at line 41 of file MooseBase.h.
{ return _type; }
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), CreateProblemDefaultAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetupDebugAction::act(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::addDistribution(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addObject(), DistributedRectilinearMeshGenerator::addPoint(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), PhysicsBasedPreconditioner::addSystem(), FEProblemBase::addTimeIntegrator(), SubProblem::addVectorTag(), addVectorTag(), FEProblemBase::advanceMultiApps(), FEProblemBase::backupMultiApps(), BoundaryPreservedMarker::BoundaryPreservedMarker(), DistributedRectilinearMeshGenerator::buildCube(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildPRefinementAndCoarseningMaps(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), FEProblemBase::computeAuxiliaryKernels(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpJacobian(), HFEMDirichletBC::computeLowerDQpJacobian(), ArrayHFEMDiffusion::computeLowerDQpJacobian(), HFEMDiffusion::computeLowerDQpJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), FEProblemBase::computeMultiAppsDT(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), DGCoupledAdvection::computeOffDiagJacobianHelper(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ScalarKernel::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueBoundaryConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), LinearNodalConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), DGConvection::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), InterfaceDiffusion::computeQpJacobian(), InterfaceReaction::computeQpJacobian(), DGCoupledAdvection::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), DGFunctionTemperatureAdvection::computeQpJacobian(), DGTemperatureAdvection::computeQpJacobian(), InterTemperatureAdvection::computeQpJacobian(), CoupledTiedValueConstraint::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), HFEMTestJump::computeQpOffDiagJacobian(), HFEMTrialJump::computeQpOffDiagJacobian(), DGCoupledAdvection::computeQpOffDiagJacobian(), ScalarKernel::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), EqualValueBoundaryConstraint::computeQpResidual(), EqualValueEmbeddedConstraint::computeQpResidual(), LinearNodalConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), DGConvection::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), DGEFieldAdvection::computeQpResidual(), HphiRadialInterface::computeQpResidual(), InterfaceAdvection::computeQpResidual(), InterfaceLogDiffusionElectrons::computeQpResidual(), PotentialSurfaceCharge::computeQpResidual(), ADDGAdvection::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), HFEMDiffusion::computeQpResidual(), HFEMTestJump::computeQpResidual(), HFEMTrialJump::computeQpResidual(), InterfaceDiffusion::computeQpResidual(), InterfaceReaction::computeQpResidual(), DGCoupledAdvection::computeQpResidual(), DGFunctionConvection::computeQpResidual(), DGFunctionTemperatureAdvection::computeQpResidual(), DGTemperatureAdvection::computeQpResidual(), InterTemperatureAdvection::computeQpResidual(), ArrayDGDiffusion::computeQpResidual(), ArrayHFEMDiffusion::computeQpResidual(), FEProblemBase::computeUserObjectByName(), FEProblemBase::computeUserObjects(), FEProblemBase::computeUserObjectsInternal(), BatchMaterial< Tuple, Output, Input >::construct(), createQRules(), FEProblemBase::createQRules(), MeshGenerator::declareMeshProperty(), DumpObjectsProblem::deduceNecessaryParameters(), DumpObjectsProblem::dumpObjectHelper(), FEProblemBase::duplicateVariableCheck(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), MooseBaseErrorInterface::errorPrefix(), AB2PredictorCorrector::estimateTimeError(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finishMultiAppStep(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), ElementSubdomainIDGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), PatternedMeshGenerator::generate(), MeshGenerator::generateInternal(), MultiAppTransfer::getAppInfo(), TransfiniteMeshGenerator::getEdge(), ElementGenerator::getElemType(), FEProblemBase::getMaterial(), FEProblemBase::getMaterialData(), MaterialOutputAction::getParams(), ReporterData::getReporterInfo(), Transient::getTimeIntegratorName(), FEProblemBase::getTransfers(), SubProblem::getVectorTags(), getVectorTags(), CommonOutputAction::hasConsole(), FEProblemBase::hasMultiApps(), AdvancedOutput::hasOutput(), FEProblemBase::incrementMultiAppTStep(), AdvancedOutput::initAvailableLists(), FunctorPositions::initialize(), FunctorTimes::initialize(), MultiAppConservativeTransfer::initialSetup(), ArrayDGDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), RelationshipManager::isType(), FEProblemBase::logAdd(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), SubProblem::numVectorTags(), numVectorTags(), MooseBaseParameterInterface::objectErrorPrefix(), AdvancedOutput::output(), Console::output(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), ProjectedStatefulMaterialStorageAction::processProperty(), SolutionInvalidInterface::registerInvalidSolutionInternal(), FEProblemBase::restoreMultiApps(), MeshRepairGenerator::separateSubdomainsByElementType(), FEProblemBase::setCoupling(), MooseBase::typeAndName(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), updateGeomSearch(), FEProblemBase::updateGeomSearch(), UserObjectInterface::userObjectType(), and AdvancedOutput::wantOutput().
typeAndName()
std::string MooseBase::typeAndName () const inline inherited
Get the class's combined type and name; useful in error handling.
Returns
The type and name of this class in the form '<type()> "<name()>"'.
Definition at line 53 of file MooseBase.h.
  {
    return type() + std::string(" \"") + name() + std::string("\"");
  }
Referenced by ReporterContext< T >::finalize(), and ReporterData::getReporterInfo().
undisplaceMesh()
void DisplacedProblem::undisplaceMesh ()
Resets the displaced mesh to the reference mesh.
Required when refining the DisplacedMesh.
Definition at line 1160 of file DisplacedProblem.C.
{
  // If undisplaceMesh() is called during initial adaptivity, it is
  // not valid to call _mesh.getActiveSemiLocalNodeRange() since it is
  // not set up yet.  So we are creating the Range by hand.
  //
  // We must undisplace *all* our nodes to the _ref_mesh
  // configuration, not just the local ones, since the partitioners
  // require this.  We are using the GRAIN_SIZE=1 from MooseMesh.C,
  // not sure how this value was decided upon.
  //
  // (DRG: The grainsize parameter is ultimately passed to TBB to help
  // it choose how to split up the range.  A grainsize of 1 says "split
  // it as much as you want".  Years ago I experimentally found that it
  // didn't matter much and that using 1 was fine.)
  //
  // Note: we don't have to invalidate/update as much stuff as
  // DisplacedProblem::updateMesh() does, since this will be handled
  // by a later call to updateMesh().
  NodeRange node_range(_mesh.getMesh().nodes_begin(),
                       _mesh.getMesh().nodes_end(),
                       /*grainsize=*/1);
  ResetDisplacedMeshThread rdmt(_mproblem, *this);
  // Undisplace the mesh using threads.
  Threads::parallel_reduce(node_range, rdmt);
}
uniqueName()
MooseObjectName MooseBaseParameterInterface::uniqueName () const inline inherited
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
Definition at line 58 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectName(_pars.get<std::string>("_unique_name"));
  }
Referenced by MooseBaseParameterInterface::connectControllableParams(), and Action::uniqueActionName().
uniqueParameterName()
MooseObjectParameterName MooseBaseParameterInterface::uniqueParameterName (const std::string & parameter_name) const inline inherited
The unique parameter name of a valid parameter of this object for accessing parameter controls.
Definition at line 43 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectParameterName(
        _pars.get<std::string>("_moose_base"), _moose_base->name(), parameter_name);
  }
updateGeomSearch()
void DisplacedProblem::updateGeomSearch (GeometricSearchData::GeometricSearchType type = GeometricSearchData::ALL) override virtual
Implements SubProblem.
Definition at line 1079 of file DisplacedProblem.C.
{
  TIME_SECTION("updateGeometricSearch", 3, "Updating Displaced GeometricSearch");
  _geometric_search_data.update(type);
}
updateMesh() [1/2]
void DisplacedProblem::updateMesh (bool mesh_changing = false) virtual
Copy the solutions on the undisplaced systems to the displaced systems and reinitialize the geometry search data and Dirac kernel information due to mesh displacement.
The parameter mesh_changing indicates whether this method is getting called because of mesh changes, e.g. due to mesh adaptivity. If mesh_changing we need to renitialize the GeometricSearchData instead of simply update. Reinitialization operations are a super-set of update operations. Reinitialization for example re-generates neighbor nodes in NearestNodeLocators, while update does not. Additionally we do not want to use the undisplaced mesh solution because it may be out-of-sync, whereas our displaced mesh solution should be in the correct state after getting restricted/prolonged in EquationSystems::reinit
Definition at line 245 of file DisplacedProblem.C.
{
  TIME_SECTION("updateMesh", 3, "Updating Displaced Mesh");
  // If the mesh is changing, we are probably performing adaptivity. In that case, we do *not* want
  // to use the undisplaced mesh solution because it may be out-of-sync, whereas our displaced mesh
  // solution should be in the correct state after getting restricted/prolonged in
  // EquationSystems::reinit (must have been called before this method)
  if (!mesh_changing)
    syncSolutions();
  for (const auto nl_sys_num : index_range(_displaced_nl))
    _nl_solution[nl_sys_num] = _displaced_nl[nl_sys_num]->sys().solution.get();
  _aux_solution = _displaced_aux->sys().solution.get();
  // If the displaced mesh has been serialized to one processor (as
  // may have occurred if it was used for Exodus output), then we need
  // the reference mesh to be also.  For that matter, did anyone
  // somehow serialize the whole mesh?  Hopefully not but let's avoid
  // causing errors if so.
  if (_mesh.getMesh().is_serial() && !this->refMesh().getMesh().is_serial())
    this->refMesh().getMesh().allgather();
  if (_mesh.getMesh().is_serial_on_zero() && !this->refMesh().getMesh().is_serial_on_zero())
    this->refMesh().getMesh().gather_to_zero();
  UpdateDisplacedMeshThread udmt(_mproblem, *this);
  // We displace all nodes, not just semilocal nodes, because
  // parallel-inconsistent mesh geometry makes libMesh cry.
  NodeRange node_range(_mesh.getMesh().nodes_begin(),
                       _mesh.getMesh().nodes_end(),
                       /*grainsize=*/1);
  Threads::parallel_reduce(node_range, udmt);
  // Displacement of the mesh has invalidated the point locator data (e.g. bounding boxes)
  _mesh.getMesh().clear_point_locator();
  // The mesh has changed. Face information normals, areas, etc. must be re-calculated
  if (haveFV())
    _mesh.setupFiniteVolumeMeshData();
  for (auto & disp_nl : _displaced_nl)
    disp_nl->update(false);
  _displaced_aux->update(false);
  // Update the geometric searches that depend on the displaced mesh. This call can end up running
  // NearestNodeThread::operator() which has a throw inside of it. We need to catch it and make sure
  // it's propagated to all processes before updating the point locator because the latter requires
  // communication
  try
  {
    // We may need to re-run geometric operations like SecondaryNeighborhoodTread if, for instance,
    // we have performed mesh adaptivity
    if (mesh_changing)
      _geometric_search_data.reinit();
    else
      _geometric_search_data.update();
  }
  catch (MooseException & e)
  {
    _mproblem.setException(e.what());
  }
  // The below call will throw an exception on all processes if any of our processes had an
  // exception above. This exception will be caught higher up the call stack and the error message
  // will be printed there
  _mproblem.checkExceptionAndStopSolve(/*print_message=*/false);
  // Since the Mesh changed, update the PointLocator object used by DiracKernels.
  _dirac_kernel_info.updatePointLocator(_mesh);
}
Referenced by meshChanged().
updateMesh() [2/2]
void DisplacedProblem::updateMesh (const std::map< unsigned int, const NumericVector< Number > * > & nl_soln, const NumericVector< Number > & aux_soln) virtual
Synchronize the solutions on the displaced systems to the given solutions and reinitialize the geometry search data and Dirac kernel information due to mesh displacement.
Definition at line 319 of file DisplacedProblem.C.
{
  TIME_SECTION("updateMesh", 3, "Updating Displaced Mesh");
  syncSolutions(nl_solns, aux_soln);
  for (const auto nl_sys_num : index_range(_displaced_nl))
    _nl_solution[nl_sys_num] = _displaced_nl[nl_sys_num]->sys().solution.get();
  _aux_solution = _displaced_aux->sys().solution.get();
  UpdateDisplacedMeshThread udmt(_mproblem, *this);
  // We displace all nodes, not just semilocal nodes, because
  // parallel-inconsistent mesh geometry makes libMesh cry.
  NodeRange node_range(_mesh.getMesh().nodes_begin(),
                       _mesh.getMesh().nodes_end(),
                       /*grainsize=*/1);
  Threads::parallel_reduce(node_range, udmt);
  // Update the geometric searches that depend on the displaced mesh. This call can end up running
  // NearestNodeThread::operator() which has a throw inside of it. We need to catch it and make sure
  // it's propagated to all processes before updating the point locator because the latter requires
  // communication
  try
  {
    _geometric_search_data.update();
  }
  catch (MooseException & e)
  {
    _mproblem.setException(e.what());
  }
  // The below call will throw an exception on all processes if any of our processes had an
  // exception above. This exception will be caught higher up the call stack and the error message
  // will be printed there
  _mproblem.checkExceptionAndStopSolve(/*print_message=*/false);
  // Since the Mesh changed, update the PointLocator object used by DiracKernels.
  _dirac_kernel_info.updatePointLocator(_mesh);
}
validParams()
InputParameters DisplacedProblem::validParams () static
Definition at line 30 of file DisplacedProblem.C.
{
  InputParameters params = SubProblem::validParams();
  params.addClassDescription(
      "A Problem object for providing access to the displaced finite element "
      "mesh and associated variables.");
  params.addPrivateParam<MooseMesh *>("mesh");
  params.addPrivateParam<std::vector<std::string>>("displacements", {});
  return params;
}
vectorTagExists() [1/2]
bool DisplacedProblem::vectorTagExists (const TagID tag_id) const override virtual
Check to see if a particular Tag exists.
Reimplemented from SubProblem.
Definition at line 388 of file DisplacedProblem.C.
{
  return _mproblem.vectorTagExists(tag_id);
}
vectorTagExists() [2/2]
bool DisplacedProblem::vectorTagExists (const TagName & tag_name) const override virtual
Check to see if a particular Tag exists by using Tag name.
Reimplemented from SubProblem.
Definition at line 394 of file DisplacedProblem.C.
{
  return _mproblem.vectorTagExists(tag_name);
}
vectorTagName()
TagName DisplacedProblem::vectorTagName (const TagID tag) const override virtual
Retrieve the name associated with a TagID.
Reimplemented from SubProblem.
Definition at line 382 of file DisplacedProblem.C.
{
  return _mproblem.vectorTagName(tag_id);
}
vectorTagType()
Moose::VectorTagType DisplacedProblem::vectorTagType (const TagID tag_id) const override virtual
Reimplemented from SubProblem.
Definition at line 412 of file DisplacedProblem.C.
{
  return _mproblem.vectorTagType(tag_id);
}
verifyVectorTags()
bool SubProblem::verifyVectorTags () const protected inherited
Verify the integrity of _vector_tags and _typed_vector_tags.
Definition at line 219 of file SubProblem.C.
{
  for (TagID tag_id = 0; tag_id < _vector_tags.size(); ++tag_id)
  {
    const auto & vector_tag = _vector_tags[tag_id];
    if (vector_tag._id != tag_id)
      mooseError("Vector tag ", vector_tag._id, " id mismatch in _vector_tags");
    if (vector_tag._type == Moose::VECTOR_TAG_ANY)
      mooseError("Vector tag '", vector_tag._name, "' has type VECTOR_TAG_ANY");
    const auto search = _vector_tags_name_map.find(vector_tag._name);
    if (search == _vector_tags_name_map.end())
      mooseError("Vector tag ", vector_tag._id, " is not in _vector_tags_name_map");
    else if (search->second != tag_id)
      mooseError("Vector tag ", vector_tag._id, " has incorrect id in _vector_tags_name_map");
    unsigned int found_in_type = 0;
    for (TagTypeID tag_type_id = 0; tag_type_id < _typed_vector_tags[vector_tag._type].size();
         ++tag_type_id)
    {
      const auto & vector_tag_type = _typed_vector_tags[vector_tag._type][tag_type_id];
      if (vector_tag_type == vector_tag)
      {
        ++found_in_type;
        if (vector_tag_type._type_id != tag_type_id)
          mooseError("Type ID for Vector tag ", tag_id, " is incorrect");
      }
    }
    if (found_in_type == 0)
      mooseError("Vector tag ", tag_id, " not found in _typed_vector_tags");
    if (found_in_type > 1)
      mooseError("Vector tag ", tag_id, " found multiple times in _typed_vector_tags");
  }
  unsigned int num_typed_vector_tags = 0;
  for (const auto & typed_vector_tags : _typed_vector_tags)
    num_typed_vector_tags += typed_vector_tags.size();
  if (num_typed_vector_tags != _vector_tags.size())
    mooseError("Size mismatch between _vector_tags and _typed_vector_tags");
  if (_vector_tags_name_map.size() != _vector_tags.size())
    mooseError("Size mismatch between _vector_tags and _vector_tags_name_map");
  return true;
}
Referenced by SubProblem::addVectorTag(), SubProblem::getVectorTag(), SubProblem::getVectorTagID(), SubProblem::getVectorTags(), SubProblem::numVectorTags(), SubProblem::vectorTagExists(), SubProblem::vectorTagName(), and SubProblem::vectorTagType().
Friends And Related Function Documentation
Restartable
friend class Restartable friend
Definition at line 393 of file DisplacedProblem.h.
UpdateDisplacedMeshThread
friend class UpdateDisplacedMeshThread friend
Definition at line 392 of file DisplacedProblem.h.
Member Data Documentation
_action_factory
ActionFactory& MooseBaseParameterInterface::_action_factory protected inherited
Builds Actions.
Definition at line 164 of file MooseBaseParameterInterface.h.
Referenced by CommonOutputAction::create(), AddVariableAction::createInitialConditionAction(), AddSpecies::createInitialConditions(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
_active_elemental_moose_variables
std::vector<std::set<MooseVariableFieldBase *> > SubProblem::_active_elemental_moose_variables protected inherited
This is the set of MooseVariableFieldBase that will actually get reinited by a call to reinit(elem)
Definition at line 996 of file SubProblem.h.
Referenced by SubProblem::clearActiveElementalMooseVariables(), FEProblemBase::FEProblemBase(), SubProblem::getActiveElementalMooseVariables(), SubProblem::setActiveElementalMooseVariables(), and SubProblem::SubProblem().
_active_fe_var_coupleable_matrix_tags
std::vector<std::set<TagID> > SubProblem::_active_fe_var_coupleable_matrix_tags protected inherited
Definition at line 1005 of file SubProblem.h.
Referenced by SubProblem::clearActiveFEVariableCoupleableMatrixTags(), SubProblem::getActiveFEVariableCoupleableMatrixTags(), SubProblem::setActiveFEVariableCoupleableMatrixTags(), and SubProblem::SubProblem().
_active_fe_var_coupleable_vector_tags
std::vector<std::set<TagID> > SubProblem::_active_fe_var_coupleable_vector_tags protected inherited
Definition at line 1007 of file SubProblem.h.
Referenced by SubProblem::clearActiveFEVariableCoupleableVectorTags(), SubProblem::getActiveFEVariableCoupleableVectorTags(), SubProblem::setActiveFEVariableCoupleableVectorTags(), and SubProblem::SubProblem().
_active_material_property_ids
std::vector<std::set<unsigned int> > SubProblem::_active_material_property_ids protected inherited
Set of material property ids that determine whether materials get reinited.
Definition at line 1003 of file SubProblem.h.
Referenced by FEProblemBase::clearActiveMaterialProperties(), FEProblemBase::getActiveMaterialProperties(), FEProblemBase::hasActiveMaterialProperties(), FEProblemBase::setActiveMaterialProperties(), and SubProblem::SubProblem().
_active_sc_var_coupleable_matrix_tags
std::vector<std::set<TagID> > SubProblem::_active_sc_var_coupleable_matrix_tags protected inherited
Definition at line 1009 of file SubProblem.h.
Referenced by SubProblem::clearActiveScalarVariableCoupleableMatrixTags(), SubProblem::getActiveScalarVariableCoupleableMatrixTags(), SubProblem::setActiveScalarVariableCoupleableMatrixTags(), and SubProblem::SubProblem().
_active_sc_var_coupleable_vector_tags
std::vector<std::set<TagID> > SubProblem::_active_sc_var_coupleable_vector_tags protected inherited
Definition at line 1011 of file SubProblem.h.
Referenced by SubProblem::clearActiveScalarVariableCoupleableVectorTags(), SubProblem::getActiveScalarVariableCoupleableVectorTags(), SubProblem::setActiveScalarVariableCoupleableVectorTags(), and SubProblem::SubProblem().
_app
MooseApp& MooseBase::_app protected inherited
The MOOSE application this is associated with.
Definition at line 60 of file MooseBase.h.
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), MeshGenerator::addChildMeshGenerator(), FEProblemBase::addMaterialHelper(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addOutput(), MeshGenerator::addParentMeshGenerator(), FVFluxKernel::adjustRMGhostLayers(), FEProblemBase::allowOutput(), AStableDirk4::AStableDirk4(), FileMesh::buildMesh(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), MeshGenerator::checkGetMesh(), FEProblemBase::checkICRestartError(), FEProblemBase::checkNonlinearConvergence(), OversampleOutput::cloneMesh(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), Console::Console(), TimeStepper::constrainStep(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::createLocalApp(), FEProblemBase::customSetup(), MeshGenerator::declareMeshProperty(), MeshGenerator::declareNullMeshName(), MooseMesh::determineUseDistributedMesh(), DumpObjectsProblem::dumpObjectHelper(), DumpObjectsProblem::dumpVariableHelper(), EigenExecutionerBase::EigenExecutionerBase(), EigenKernel::EigenKernel(), PIDTransientControl::execute(), Eigenvalue::execute(), InversePowerMethod::execute(), NonlinearEigen::execute(), Steady::execute(), Transient::execute(), PseudoTimestep::execute(), IterationInfo::execute(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FileOutput::FileOutput(), ChangeOverFixedPointPostprocessor::finalize(), RadialAverage::finalize(), FixedPointSolve::FixedPointSolve(), FEProblemBase::forceOutput(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), SideSetsFromNormalsGenerator::generate(), MeshGenerator::generateInternal(), FEProblemBase::getExecutor(), MeshGenerator::getMeshByName(), NumFixedPointIterations::getValue(), NumRelationshipManagers::getValue(), GhostingUserObject::GhostingUserObject(), MooseMesh::init(), InversePowerMethod::init(), NonlinearEigen::init(), Transient::init(), FEProblemBase::init(), TimePeriod::initialSetup(), Console::initialSetup(), AdvancedOutput::initOutputList(), FEProblemBase::initPetscOutput(), EigenProblem::initPetscOutput(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MeshGenerator::MeshGenerator(), EigenExecutionerBase::normalizeSolution(), NumFailedTimeSteps::NumFailedTimeSteps(), AugmentSparsityOnInterface::operator()(), Checkpoint::output(), Exodus::output(), Nemesis::output(), PerfGraphOutput::output(), Tecplot::output(), MortarNodalGeometryOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Exodus::outputEmptyTimestep(), Console::outputInput(), Exodus::outputInput(), Exodus::outputNodalVariables(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), Console::outputSystemInformation(), JSONOutput::outputSystemInformation(), MultiApp::parentOutputPositionChanged(), PIDTransientControl::PIDTransientControl(), Transient::preExecute(), Eigenvalue::prepareSolverOptions(), FEProblemBase::projectSolution(), MultiApp::setAppOutputFileBase(), FileOutput::setFileBaseInternal(), MeshGenerator::setMeshProperty(), MeshGenerator::setMeshPropertyHelper(), FEProblemBase::setRestartFile(), TransientMultiApp::setupApp(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SolutionInvalidityReporter::SolutionInvalidityReporter(), FEProblemBase::solve(), EigenProblem::solve(), PetscOutput::solveSetup(), TransientMultiApp::solveStep(), FEProblemBase::subdomainSetup(), FEProblemBase::theWarehouse(), TimeExtremeValue::TimeExtremeValue(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), Transient::Transient(), FEProblemBase::updateMortarMesh(), Console::write(), and FEProblemBase::~FEProblemBase().
_assembly
std::vector<std::vector<std::unique_ptr<Assembly> > > DisplacedProblem::_assembly protected
Definition at line 383 of file DisplacedProblem.h.
Referenced by addCachedResidualDirectly(), addJacobian(), addJacobianBlockNonlocal(), addJacobianBlockTags(), addJacobianLowerD(), addJacobianNeighbor(), addJacobianNeighborLowerD(), addJacobianNonlocal(), addResidual(), addResidualLower(), addResidualNeighbor(), assembly(), bumpAllQRuleOrder(), bumpVolumeQRuleOrder(), cacheJacobianNonlocal(), createQRules(), DisplacedProblem(), init(), prepare(), prepareAssembly(), prepareAssemblyNeighbor(), prepareBlockNonlocal(), prepareFaceShapes(), prepareNeighborShapes(), prepareNonlocal(), prepareShapes(), reinitDirac(), reinitElemFace(), reinitElemNeighborAndLowerD(), reinitElemPhys(), reinitNeighbor(), reinitNeighborPhys(), reinitNode(), reinitNodeFace(), reinitOffDiagScalars(), setCurrentSubdomainID(), setNeighborSubdomainID(), setResidual(), and setResidualNeighbor().
_aux_solution
const NumericVector<Number>* DisplacedProblem::_aux_solution protected
The auxiliary system solution.
Definition at line 381 of file DisplacedProblem.h.
Referenced by updateMesh().
_cli_option_found
bool Problem::_cli_option_found protected inherited
True if the CLI option is found.
Definition at line 52 of file Problem.h.
Referenced by Problem::_setCLIOption().
_color_output
bool Problem::_color_output protected inherited
True if we're going to attempt to write color output.
Definition at line 55 of file Problem.h.
_computing_nonlinear_residual
bool SubProblem::_computing_nonlinear_residual protected inherited
Whether the non-linear residual is being evaluated.
Definition at line 1029 of file SubProblem.h.
Referenced by SubProblem::computingNonlinearResid(), and FEProblemBase::computingNonlinearResid().
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_consumed_material_properties
std::map<MooseObjectName, std::set<std::string> > SubProblem::_consumed_material_properties private inherited
Definition at line 1109 of file SubProblem.h.
Referenced by SubProblem::addConsumedPropertyName(), and SubProblem::getConsumedPropertyMap().
_currently_computing_jacobian
bool SubProblem::_currently_computing_jacobian protected inherited
Flag to determine whether the problem is currently computing Jacobian.
Definition at line 1023 of file SubProblem.h.
Referenced by FEProblemBase::computeJacobianBlocks(), EigenProblem::computeJacobianBlocks(), FEProblemBase::computeJacobianTags(), SubProblem::currentlyComputingJacobian(), and SubProblem::setCurrentlyComputingJacobian().
_currently_computing_residual
bool SubProblem::_currently_computing_residual protected inherited
Whether the residual is being evaluated.
Definition at line 1032 of file SubProblem.h.
Referenced by SubProblem::currentlyComputingResidual(), FEProblemBase::setCurrentlyComputingResidual(), and SubProblem::setCurrentlyComputingResidual().
_currently_computing_residual_and_jacobian
bool SubProblem::_currently_computing_residual_and_jacobian protected inherited
Flag to determine whether the problem is currently computing the residual and Jacobian.
Definition at line 1026 of file SubProblem.h.
Referenced by SubProblem::currentlyComputingResidualAndJacobian(), and SubProblem::setCurrentlyComputingResidualAndJacobian().
_default_ghosting
bool SubProblem::_default_ghosting protected inherited
Whether or not to use default libMesh coupling.
Definition at line 1017 of file SubProblem.h.
Referenced by SubProblem::defaultGhosting().
_dirac_kernel_info
DiracKernelInfo SubProblem::_dirac_kernel_info protected inherited
nonlocal coupling matrix;
Definition at line 970 of file SubProblem.h.
Referenced by clearDiracInfo(), FEProblemBase::clearDiracInfo(), SubProblem::diracKernelInfo(), getDiracElements(), FEProblemBase::getDiracElements(), FEProblemBase::meshChangedHelper(), reinitDirac(), FEProblemBase::reinitDirac(), and updateMesh().
_displaced_aux
std::unique_ptr<DisplacedSystem> DisplacedProblem::_displaced_aux protected
Definition at line 375 of file DisplacedProblem.h.
Referenced by addAuxVariable(), auxSys(), customSetup(), DisplacedProblem(), getActualFieldVariable(), getArrayVariable(), getScalarVariable(), getStandardVariable(), getVariable(), getVectorVariable(), hasScalarVariable(), hasVariable(), init(), initialSetup(), jacobianSetup(), meshChanged(), prepare(), prepareFace(), reinitDirac(), reinitElem(), reinitElemFace(), reinitElemPhys(), reinitNeighbor(), reinitNeighborPhys(), reinitNode(), reinitNodeFace(), reinitNodes(), reinitNodesNeighbor(), reinitScalars(), residualSetup(), restoreOldSolutions(), saveOldSolutions(), syncSolutions(), systemBaseAuxiliary(), timestepSetup(), and updateMesh().
_displaced_nl
std::vector<std::unique_ptr<DisplacedSystem> > DisplacedProblem::_displaced_nl protected
Definition at line 374 of file DisplacedProblem.h.
Referenced by addCachedResidualDirectly(), addVariable(), customSetup(), DisplacedProblem(), getActualFieldVariable(), getArrayVariable(), getScalarVariable(), getStandardVariable(), getVariable(), getVectorVariable(), hasScalarVariable(), hasVariable(), init(), initialSetup(), jacobianSetup(), meshChanged(), nlSys(), prepare(), prepareFace(), reinitDirac(), reinitElem(), reinitElemFace(), reinitElemPhys(), reinitNeighbor(), reinitNeighborPhys(), reinitNode(), reinitNodeFace(), reinitNodes(), reinitNodesNeighbor(), reinitScalars(), residualSetup(), restoreOldSolutions(), saveOldSolutions(), setResidual(), setResidualNeighbor(), syncSolutions(), systemBaseNonlinear(), timestepSetup(), and updateMesh().
_displacements
std::vector<std::string> DisplacedProblem::_displacements protected
Definition at line 372 of file DisplacedProblem.h.
Referenced by getDisplacementVarNames(), UpdateDisplacedMeshThread::init(), and init().
_enabled
const bool& MooseObject::_enabled protected inherited
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
Definition at line 58 of file MooseObject.h.
Referenced by MooseObject::enabled().
_eq
EquationSystems DisplacedProblem::_eq protected
Definition at line 369 of file DisplacedProblem.h.
Referenced by es(), getSystem(), init(), and meshChanged().
_factory
Factory& SubProblem::_factory protected inherited
The Factory for building objects.
Definition at line 966 of file SubProblem.h.
Referenced by FEProblemBase::addAnyRedistributers(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), FEProblemBase::addObject(), FEProblemBase::addOutput(), FEProblemBase::addPredictor(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), DumpObjectsProblem::deduceNecessaryParameters(), and FEProblemBase::getFunction().
_functor_to_request_info
std::vector<std::multimap<std::string, std::pair<bool, bool> > > SubProblem::_functor_to_request_info private inherited
A multimap (for each thread) from unfilled functor requests to whether the requests were for AD functors and whether the requestor was an AD object.
Definition at line 1085 of file SubProblem.h.
Referenced by SubProblem::addFunctor(), SubProblem::getFunctor(), and SubProblem::SubProblem().
_functor_to_requestors
std::map<std::string, std::set<std::string> > SubProblem::_functor_to_requestors private inherited
The requestors of functors where the key is the prop name and the value is a set of names of requestors.
Definition at line 1081 of file SubProblem.h.
Referenced by SubProblem::getFunctor(), SubProblem::initialSetup(), and SubProblem::showFunctorRequestors().
_functors
std::vector<std::multimap<std::string, std::tuple<TrueFunctorIs, std::unique_ptr<Moose::FunctorEnvelopeBase>, std::unique_ptr<Moose::FunctorEnvelopeBase> > > > SubProblem::_functors private inherited
A container holding pointers to all the functors in our problem.
We hold a tuple where the zeroth item in the tuple is an enumerator that describes what type of functor the "true" functor is (either NONAD or AD), the first item in the tuple is the non-AD version of the functor, and the second item in the tuple is the AD version of the functor
Definition at line 1068 of file SubProblem.h.
Referenced by SubProblem::addFunctor(), SubProblem::getFunctor(), SubProblem::hasFunctor(), SubProblem::hasFunctorWithType(), SubProblem::initialSetup(), SubProblem::showFunctors(), and SubProblem::SubProblem().
_geometric_search_data
GeometricSearchData DisplacedProblem::_geometric_search_data protected
Definition at line 385 of file DisplacedProblem.h.
Referenced by geomSearchData(), updateGeomSearch(), and updateMesh().
_ghosted_elems
std::set<dof_id_type> SubProblem::_ghosted_elems protected inherited
Elements that should have Dofs ghosted to the local processor.
Definition at line 1020 of file SubProblem.h.
Referenced by DumpObjectsProblem::addAuxVariable(), FEProblemBase::addGhostedElem(), SubProblem::ghostedElems(), FEProblemBase::meshChangedHelper(), FEProblemBase::possiblyRebuildGeomSearchPatches(), and FEProblemBase::reinitBecauseOfGhostingOrNewGeomObjects().
_has_active_elemental_moose_variables
std::vector<unsigned int> SubProblem::_has_active_elemental_moose_variables protected inherited
Whether or not there is currently a list of active elemental moose variables.
Definition at line 1000 of file SubProblem.h.
Referenced by SubProblem::clearActiveElementalMooseVariables(), SubProblem::hasActiveElementalMooseVariables(), SubProblem::setActiveElementalMooseVariables(), and SubProblem::SubProblem().
_have_ad_objects
bool SubProblem::_have_ad_objects protected inherited
AD flag indicating whether any AD objects have been added.
Definition at line 1041 of file SubProblem.h.
Referenced by SubProblem::haveADObjects(), haveADObjects(), and FEProblemBase::haveADObjects().
_have_p_refinement
bool SubProblem::_have_p_refinement private inherited
Whether p-refinement has been requested at any point during the simulation.
Definition at line 1124 of file SubProblem.h.
Referenced by SubProblem::doingPRefinement(), and SubProblem::havePRefinement().
_map_block_material_props
std::map<SubdomainID, std::set<std::string> > SubProblem::_map_block_material_props protected inherited
Map of material properties (block_id -> list of properties)
Definition at line 973 of file SubProblem.h.
Referenced by SubProblem::checkBlockMatProps(), SubProblem::getMaterialPropertyBlocks(), SubProblem::hasBlockMaterialProperty(), and SubProblem::storeSubdomainMatPropName().
_map_block_material_props_check
std::map<SubdomainID, std::multimap<std::string, std::string> > SubProblem::_map_block_material_props_check protected inherited
Data structures of the requested material properties.
We store them in a map from boundary/block id to multimap. Each of the multimaps is a list of requestor object names to material property names.
Definition at line 991 of file SubProblem.h.
Referenced by SubProblem::checkBlockMatProps(), and SubProblem::storeSubdomainDelayedCheckMatProp().
_map_boundary_material_props
std::map<BoundaryID, std::set<std::string> > SubProblem::_map_boundary_material_props protected inherited
Map for boundary material properties (boundary_id -> list of properties)
Definition at line 976 of file SubProblem.h.
Referenced by SubProblem::checkBoundaryMatProps(), SubProblem::getMaterialPropertyBoundaryIDs(), SubProblem::hasBoundaryMaterialProperty(), and SubProblem::storeBoundaryMatPropName().
_map_boundary_material_props_check
std::map<BoundaryID, std::multimap<std::string, std::string> > SubProblem::_map_boundary_material_props_check protected inherited
Definition at line 992 of file SubProblem.h.
Referenced by SubProblem::checkBoundaryMatProps(), and SubProblem::storeBoundaryDelayedCheckMatProp().
_material_property_requested
std::set<std::string> SubProblem::_material_property_requested protected inherited
set containing all material property names that have been requested by getMaterialProperty*
Definition at line 983 of file SubProblem.h.
Referenced by SubProblem::isMatPropRequested(), and SubProblem::markMatPropRequested().
_matrix_tag_id_to_tag_name
std::map<TagID, TagName> SubProblem::_matrix_tag_id_to_tag_name protected inherited
Reverse map.
Definition at line 963 of file SubProblem.h.
Referenced by SubProblem::addMatrixTag(), SubProblem::matrixTagExists(), and SubProblem::matrixTagName().
_matrix_tag_name_to_tag_id
std::map<TagName, TagID> SubProblem::_matrix_tag_name_to_tag_id protected inherited
The currently declared tags.
Definition at line 960 of file SubProblem.h.
Referenced by SubProblem::addMatrixTag(), SubProblem::getMatrixTagID(), SubProblem::getMatrixTags(), SubProblem::matrixTagExists(), and SubProblem::numMatrixTags().
_mesh
MooseMesh& DisplacedProblem::_mesh protected
Definition at line 368 of file DisplacedProblem.h.
Referenced by DisplacedProblem(), init(), mesh(), meshChanged(), reinitElemNeighborAndLowerD(), reinitElemPhys(), reinitNeighborPhys(), undisplaceMesh(), and updateMesh().
_moose_base
const MooseBase* const MooseBaseParameterInterface::_moose_base private inherited
The MooseBase object that inherits this class.
Definition at line 168 of file MooseBaseParameterInterface.h.
Referenced by MooseBaseParameterInterface::connectControllableParams(), MooseBaseParameterInterface::objectErrorPrefix(), MooseBaseParameterInterface::paramError(), and MooseBaseParameterInterface::uniqueParameterName().
_mproblem
FEProblemBase& DisplacedProblem::_mproblem protected
Definition at line 367 of file DisplacedProblem.h.
Referenced by addGhostedBoundary(), addGhostedElem(), addMatrixTag(), addVectorTag(), computingInitialResidual(), computingScalingJacobian(), computingScalingResidual(), couplingMatrix(), currentNlSysNum(), currentResidualVectorTags(), determineNonlinearSystem(), DisplacedProblem(), getLineSearch(), getMatrixTagID(), getVectorTag(), getVectorTagID(), getVectorTags(), ghostedElems(), ghostGhostedBoundaries(), hasNonlocalCoupling(), haveADObjects(), haveFV(), init(), isTransient(), matrixTagExists(), matrixTagName(), needFV(), nlConverged(), nlSysNum(), numMatrixTags(), numNonlinearSystems(), numVectorTags(), prepare(), safeAccessTaggedMatrices(), safeAccessTaggedVectors(), syncSolutions(), undisplaceMesh(), updateMesh(), vectorTagExists(), vectorTagName(), and vectorTagType().
_name
const std::string& MooseBase::_name protected inherited
The name of this class, reference to value stored in InputParameters.
Definition at line 66 of file MooseBase.h.
Referenced by AddFieldSplitAction::act(), AddBCAction::act(), AddConstraintAction::act(), AddControlAction::act(), AddDamperAction::act(), AddDGKernelAction::act(), AddDiracKernelAction::act(), AddDistributionAction::act(), AddFunctionAction::act(), AddFunctorMaterialAction::act(), AddFVBCAction::act(), AddFVInitialConditionAction::act(), AddFVInterfaceKernelAction::act(), AddFVKernelAction::act(), AddIndicatorAction::act(), AddInitialConditionAction::act(), AddInterfaceKernelAction::act(), AddKernelAction::act(), AddMarkerAction::act(), AddMaterialAction::act(), AddMeshDivisionAction::act(), AddMeshGeneratorAction::act(), AddMultiAppAction::act(), AddNodalKernelAction::act(), AddOutputAction::act(), AddPeriodicBCAction::act(), AddPositionsAction::act(), AddPostprocessorAction::act(), AddReporterAction::act(), AddSamplerAction::act(), AddScalarKernelAction::act(), AddTimesAction::act(), AddTimeStepperAction::act(), AddTransferAction::act(), AddUserObjectAction::act(), AddVectorPostprocessorAction::act(), PartitionerAction::act(), ReadExecutorParamsAction::act(), SetupPreconditionerAction::act(), SetupTimeIntegratorAction::act(), AddDriftDiffusionAction::addADKernels(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromXY(), PiecewiseLinearBase::buildInterpolation(), CombinerGenerator::CombinerGenerator(), Executor::Executor(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), FunctionDT::FunctionDT(), FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), MooseBase::name(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), PiecewiseBase::setData(), and Split::setup().
_nl_solution
std::vector<const NumericVector<Number> *> DisplacedProblem::_nl_solution protected
The nonlinear system solutions.
Definition at line 378 of file DisplacedProblem.h.
Referenced by DisplacedProblem(), and updateMesh().
_nonlocal_cm
std::vector<CouplingMatrix> SubProblem::_nonlocal_cm protected inherited
Definition at line 968 of file SubProblem.h.
Referenced by FEProblemBase::addJacobianBlockTags(), FEProblemBase::FEProblemBase(), SubProblem::nonlocalCouplingMatrix(), FEProblemBase::prepare(), and FEProblemBase::setNonlocalCouplingMatrix().
_output_functors
bool SubProblem::_output_functors private inherited
Whether to output a list of the functors used and requested (currently only at initialSetup)
Definition at line 1088 of file SubProblem.h.
Referenced by SubProblem::initialSetup(), and SubProblem::setFunctorOutput().
_parent
const MooseObject & DataFileInterface< MooseObject >::_parent private inherited
Definition at line 46 of file DataFileInterface.h.
_pars
const InputParameters& MooseBaseParameterInterface::_pars protected inherited
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Definition at line 158 of file MooseBaseParameterInterface.h.
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), AddPeriodicBCAction::act(), AddVariableAction::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), FunctorMaterial::addFunctorPropertyByBlocks(), FVFluxKernel::adjustRMGhostLayers(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), PiecewiseTabularBase::buildFromFile(), PNGOutput::calculateRescalingValues(), BlockWeightedPartitioner::clone(), GridPartitioner::clone(), HierarchicalGridPartitioner::clone(), PetscExternalPartitioner::clone(), RandomPartitioner::clone(), SingleRankPartitioner::clone(), MooseBaseParameterInterface::connectControllableParams(), Console::Console(), AddVariableAction::createInitialConditionAction(), MaterialBase::declareADProperty(), MaterialBase::declareProperty(), FEProblemSolve::FEProblemSolve(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), FileMeshGenerator::generate(), MaterialBase::getGenericZeroMaterialProperty(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getParam(), MooseBaseParameterInterface::getRenamedParam(), AddVariableAction::init(), AdvancedOutput::initExecutionTypes(), Console::initialSetup(), MooseBaseParameterInterface::isParamSetByUser(), MooseBaseParameterInterface::isParamValid(), MultiApp::keepSolutionDuringRestore(), MooseBaseParameterInterface::paramErrorMsg(), GlobalParamsAction::parameters(), MooseBaseParameterInterface::parameters(), MooseMesh::prepare(), Eigenvalue::prepareSolverOptions(), MooseMesh::setCoordSystem(), MooseMesh::setPartitionerHelper(), SetupMeshAction::setupMesh(), Transient::setupTimeIntegrator(), MooseBaseParameterInterface::uniqueName(), and MooseBaseParameterInterface::uniqueParameterName().
_pbblf_functors
std::vector<std::map<std::string, std::unique_ptr<Moose::FunctorAbstract> > > SubProblem::_pbblf_functors private inherited
Container to hold PiecewiseByBlockLambdaFunctors.
Definition at line 1071 of file SubProblem.h.
Referenced by SubProblem::addPiecewiseByBlockLambdaFunctor(), SubProblem::customSetup(), SubProblem::jacobianSetup(), SubProblem::residualSetup(), SubProblem::SubProblem(), and SubProblem::timestepSetup().
_pg_moose_app
MooseApp& PerfGraphInterface::_pg_moose_app protected inherited
The MooseApp that owns the PerfGraph.
Definition at line 124 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::perfGraph().
_prefix
const std::string PerfGraphInterface::_prefix protected inherited
A prefix to use for all sections.
Definition at line 127 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::timedSectionName().
_ref_mesh
MooseMesh& DisplacedProblem::_ref_mesh protected
reference mesh
Definition at line 371 of file DisplacedProblem.h.
Referenced by DisplacedProblem(), and refMesh().
_requires_nonlocal_coupling
bool SubProblem::_requires_nonlocal_coupling protected inherited
nonlocal coupling requirement flag
Definition at line 1014 of file SubProblem.h.
Referenced by DumpObjectsProblem::addAuxVariable(), FEProblemBase::checkNonlocalCoupling(), and SubProblem::checkNonlocalCouplingRequirement().
_root_alg_gf_to_sys_clones
std::unordered_map<GhostingFunctor *, std::vector<std::shared_ptr<GhostingFunctor> > > SubProblem::_root_alg_gf_to_sys_clones private inherited
A map from a root algebraic ghosting functor, e.g.
the ghosting functor passed into removeAlgebraicGhostingFunctor, to its clones in other systems, e.g. systems other than system 0
Definition at line 1115 of file SubProblem.h.
Referenced by SubProblem::cloneAlgebraicGhostingFunctor(), and SubProblem::removeAlgebraicGhostingFunctor().
_root_coupling_gf_to_sys_clones
std::unordered_map<GhostingFunctor *, std::vector<std::shared_ptr<GhostingFunctor> > > SubProblem::_root_coupling_gf_to_sys_clones private inherited
A map from a root coupling ghosting functor, e.g.
the ghosting functor passed into removeCouplingGhostingFunctor, to its clones in other systems, e.g. systems other than system 0
Definition at line 1121 of file SubProblem.h.
Referenced by SubProblem::cloneCouplingGhostingFunctor(), and SubProblem::removeCouplingGhostingFunctor().
_safe_access_tagged_matrices
bool SubProblem::_safe_access_tagged_matrices protected inherited
Is it safe to retrieve data from tagged matrices.
Definition at line 1035 of file SubProblem.h.
Referenced by FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), and SubProblem::safeAccessTaggedMatrices().
_safe_access_tagged_vectors
bool SubProblem::_safe_access_tagged_vectors protected inherited
Is it safe to retrieve data from tagged vectors.
Definition at line 1038 of file SubProblem.h.
Referenced by FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), and SubProblem::safeAccessTaggedVectors().
_termination_requested
bool Problem::_termination_requested protected inherited
True if termination of the solve has been requested.
Definition at line 58 of file Problem.h.
Referenced by Problem::isSolveTerminationRequested(), and Problem::terminateSolve().
_type
const std::string& MooseBase::_type protected inherited
The type of this class.
Definition at line 63 of file MooseBase.h.
Referenced by FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), FEProblemBase::init(), FEProblemBase::solverTypeString(), and MooseBase::type().
_typed_vector_tags
std::vector<std::vector<VectorTag> > SubProblem::_typed_vector_tags private inherited
The vector tags associated with each VectorTagType This is kept separate from _vector_tags for quick access into typed vector tags in places where we don't want to build a new vector every call (like in residual evaluation)
Definition at line 1098 of file SubProblem.h.
Referenced by SubProblem::addVectorTag(), SubProblem::getVectorTags(), and SubProblem::verifyVectorTags().
_var_dof_map
std::map<std::string, std::vector<dof_id_type> > SubProblem::_var_dof_map inherited
Definition at line 629 of file SubProblem.h.
Referenced by MooseVariableBase::allDofIndices(), FEProblemBase::setNonlocalCouplingMatrix(), and FEProblemBase::setVariableAllDoFMap().
_vector_tags
std::vector<VectorTag> SubProblem::_vector_tags private inherited
The declared vector tags.
Definition at line 1091 of file SubProblem.h.
Referenced by SubProblem::addVectorTag(), SubProblem::getVectorTag(), SubProblem::getVectorTags(), SubProblem::vectorTagExists(), SubProblem::vectorTagName(), SubProblem::vectorTagType(), and SubProblem::verifyVectorTags().
_vector_tags_name_map
std::map<TagName, TagID> SubProblem::_vector_tags_name_map private inherited
Map of vector tag TagName to TagID.
Definition at line 1101 of file SubProblem.h.
Referenced by SubProblem::addVectorTag(), SubProblem::getVectorTagID(), and SubProblem::verifyVectorTags().
_zero_block_material_props
std::map<SubdomainID, std::set<MaterialPropertyName> > SubProblem::_zero_block_material_props protected inherited
Set of properties returned as zero properties.
Definition at line 979 of file SubProblem.h.
Referenced by SubProblem::checkBlockMatProps(), FEProblemBase::checkDependMaterialsHelper(), and SubProblem::storeSubdomainZeroMatProp().
_zero_boundary_material_props
std::map<BoundaryID, std::set<MaterialPropertyName> > SubProblem::_zero_boundary_material_props protected inherited
Definition at line 980 of file SubProblem.h.
Referenced by SubProblem::checkBoundaryMatProps(), and SubProblem::storeBoundaryZeroMatProp().
The documentation for this class was generated from the following files:
moose/framework/include/problems/DisplacedProblem.h
moose/framework/src/problems/DisplacedProblem.C