Zapdos: ReporterStateBase Class Reference
ReporterStateBase Class Reference abstract
The base class for storing a Repoter's state.
#include <ReporterState.h>
Public Member Functions
ReporterStateBase (const ReporterName &name)
virtual ~ReporterStateBase ()=default
const ReporterName & getReporterName () const
Return the ReporterName that this state is associated with.
void addConsumer (ReporterMode mode, const MooseObject &moose_object)
Add a consumer for this ReporterState.
const std::set< std::pair< ReporterMode, const MooseObject * > > & getConsumers () const
Returns the consumers for this state; a pair that consists of the mode that the state is being consumed by, and the object consuming it.
virtual std::string valueType () const =0
void setIsPostprocessor ()
Sets the special Reporter type to a Postprocessor.
void setIsVectorPostprocessor ()
Sets the special Reporter type to a VectorPostprocessor.
Private Attributes
ReporterName _reporter_name
Name of data that state is associated.
std::set< std::pair< ReporterMode, const MooseObject * > > _consumers
The consumers for this state; we store the MooseObject for detailed error reporting.
Detailed Description
The base class for storing a Repoter's state.
The base class is needed in order to store the states without a template parameter so that they can be iterated through to observe the producers and consumers.
Definition at line 32 of file ReporterState.h.
Constructor & Destructor Documentation
ReporterStateBase()
ReporterStateBase::ReporterStateBase (const ReporterName & name)
Definition at line 14 of file ReporterState.C.
: _reporter_name(name) {}
~ReporterStateBase()
virtual ReporterStateBase::~ReporterStateBase () virtual default
Member Function Documentation
addConsumer()
void ReporterStateBase::addConsumer (ReporterMode mode, const MooseObject & moose_object)
Add a consumer for this ReporterState.
Parameters
mode The mode that the object will consume the Reporter value
moose_object The MooseObject doing the consuming (for error reporting)
See also
ReporterData
Definition at line 17 of file ReporterState.C.
{
  _consumers.emplace(mode, &moose_object);
}
Referenced by ReporterTransferInterface::addReporterTransferMode().
getConsumers()
const std::set< std::pair< ReporterMode, const MooseObject * > > & ReporterStateBase::getConsumers () const inline
Returns the consumers for this state; a pair that consists of the mode that the state is being consumed by, and the object consuming it.
See also
ReporterContext
Definition at line 56 of file ReporterState.h.
  {
    return _consumers;
  }
Referenced by ReporterData::getReporterInfo(), and ReporterContextBase::requiresConsumerModes().
getReporterName()
const ReporterName & ReporterStateBase::getReporterName () const inline
Return the ReporterName that this state is associated with.
Definition at line 41 of file ReporterState.h.
{ return _reporter_name; }
Referenced by ReporterData::getReporterInfo().
setIsPostprocessor()
void ReporterStateBase::setIsPostprocessor () inline
Sets the special Reporter type to a Postprocessor.
See ReporterData::declareReporterValue.
Definition at line 71 of file ReporterState.h.
{ _reporter_name.setIsPostprocessor(); }
setIsVectorPostprocessor()
void ReporterStateBase::setIsVectorPostprocessor () inline
Sets the special Reporter type to a VectorPostprocessor.
See ReporterData::declareReporterValue.
Definition at line 77 of file ReporterState.h.
{ _reporter_name.setIsVectorPostprocessor(); }
valueType()
virtual std::string ReporterStateBase::valueType () const pure virtual
Returns
The type associated with this state
Implemented in ReporterState< T >, and ReporterState< std::vector< T > >.
Referenced by ReporterData::getReporterInfo().
Member Data Documentation
_consumers
std::set<std::pair<ReporterMode, const MooseObject *> > ReporterStateBase::_consumers private
The consumers for this state; we store the MooseObject for detailed error reporting.
Definition at line 84 of file ReporterState.h.
Referenced by addConsumer(), and getConsumers().
_reporter_name
ReporterName ReporterStateBase::_reporter_name private
Name of data that state is associated.
Definition at line 81 of file ReporterState.h.
Referenced by getReporterName(), setIsPostprocessor(), and setIsVectorPostprocessor().
The documentation for this class was generated from the following files:
moose/framework/include/reporters/ReporterState.h
moose/framework/src/interfaces/ReporterState.C