Zapdos: MeshMetaDataInterface Class Reference
MeshMetaDataInterface Class Reference
The Interface used to retrieve mesh meta data (attributes) set by the MeshGenerator system.
#include <MeshMetaDataInterface.h>
Static Public Attributes
static constexpr auto SYSTEM = "MeshMetaData"
The system name used when initializing the Restartable interface.
static constexpr auto NAME = "<empty>"
The data name used when initializing the Restartable interface for non-MeshGenerator objects.
Protected Member Functions
MeshMetaDataInterface (const MooseObject *moose_object)
Interface for all objects reading MeshMetaData.
MeshMetaDataInterface (MooseApp &moose_app)
This class constructor is used for non-Moose-based objects like interfaces.
template<typename T >
const T & getMeshProperty (const std::string &data_name, const std::string &prefix)
Method for retrieving a property with the given type and name exists in the mesh meta-data store.
template<typename T >
const T & getMeshProperty (const std::string &data_name)
bool hasMeshProperty (const std::string &data_name, const std::string &prefix) const
template<typename T >
bool hasMeshProperty (const std::string &data_name, const std::string &prefix) const
bool hasMeshProperty (const std::string &data_name) const
template<typename T >
bool hasMeshProperty (const std::string &data_name) const
std::string meshPropertyName (const std::string &data_name) const
Static Protected Member Functions
static std::string meshPropertyName (const std::string &data_name, const std::string &prefix)
Private Member Functions
virtual std::string meshPropertyPrefix (const std::string &data_name) const
The default prefix to use for getting/seeing if mesh properties exist.
const RestartableDataValue & getMeshPropertyInternal (const std::string &data_name, const std::string &prefix) const
Helper for getting a mesh property.
template<typename... Args>
void mooseErrorInternal (Args &&... args) const
Helper for forwarding a mooseError to an object's mooseError if it is available (said error will provide more context: object name and type)
Private Attributes
MooseApp & _meta_data_app
Reference to the application.
const MooseObject *const _meta_data_object
The MooseObject (if any); used for better error handling.
Detailed Description
The Interface used to retrieve mesh meta data (attributes) set by the MeshGenerator system.
MOOSE objects should avoid retrieving and casting MeshGenerator objects since they are not re-created during a recover operation. This data is read from files early during the simulation setup an d can be used to make decisions about how to setup the rest of the problem.
Definition at line 26 of file MeshMetaDataInterface.h.
Constructor & Destructor Documentation
MeshMetaDataInterface() [1/2]
MeshMetaDataInterface::MeshMetaDataInterface (const MooseObject * moose_object) protected
Interface for all objects reading MeshMetaData.
The name of the object gets a bogus prefix, which is not intended to be used for storing data. Instead this value is overridden during retrieval.
Definition at line 14 of file MeshMetaDataInterface.C.
  : _meta_data_app(moose_object->getMooseApp()), _meta_data_object(moose_object)
{
}
MeshMetaDataInterface() [2/2]
MeshMetaDataInterface::MeshMetaDataInterface (MooseApp & moose_app) protected
This class constructor is used for non-Moose-based objects like interfaces.
A name for the storage as well as a system name must be passed in along with the thread ID explicitly.
Definition at line 19 of file MeshMetaDataInterface.C.
  : _meta_data_app(moose_app), _meta_data_object(nullptr)
{
}
Member Function Documentation
getMeshProperty() [1/2]
template<typename T > const T & MeshMetaDataInterface::getMeshProperty (const std::string & data_name) inline protected
Definition at line 56 of file MeshMetaDataInterface.h.
  {
    return getMeshProperty<T>(data_name, meshPropertyPrefix(data_name));
  }
getMeshProperty() [2/2]
template<typename T > const T & MeshMetaDataInterface::getMeshProperty (const std::string & data_name, const std::string & prefix) protected
Method for retrieving a property with the given type and name exists in the mesh meta-data store.
This method will throw an error if the property does not exist.
Definition at line 134 of file MeshMetaDataInterface.h.
{
  if (!hasMeshProperty(data_name, prefix))
    mooseErrorInternal("Failed to get mesh property '", prefix, "/", data_name, "'");
  auto value = &getMeshPropertyInternal(data_name, prefix);
  mooseAssert(value->declared(), "Value has not been declared");
  const RestartableData<T> * T_value = dynamic_cast<const RestartableData<T> *>(value);
  if (!T_value)
    mooseErrorInternal("While retrieving mesh property '",
                       prefix,
                       "/",
                       data_name,
                       "' with type '",
                       MooseUtils::prettyCppType<T>(),
                       "',\nthe property exists with different type '",
                       value->type(),
                       "'");
  return T_value->get();
}
getMeshPropertyInternal()
const RestartableDataValue & MeshMetaDataInterface::getMeshPropertyInternal (const std::string & data_name, const std::string & prefix) const private
Helper for getting a mesh property.
Definition at line 46 of file MeshMetaDataInterface.C.
{
  return _meta_data_app.getRestartableMetaData(
      meshPropertyName(data_name, prefix), MooseApp::MESH_META_DATA, 0);
}
Referenced by getMeshProperty(), and hasMeshProperty().
hasMeshProperty() [1/4]
bool MeshMetaDataInterface::hasMeshProperty (const std::string & data_name) const inline protected
Returns
Whether or not a mesh meta-data exists with the default prefix.
Definition at line 74 of file MeshMetaDataInterface.h.
  {
    return hasMeshProperty(data_name, meshPropertyPrefix(data_name));
  }
hasMeshProperty() [2/4]
template<typename T > bool MeshMetaDataInterface::hasMeshProperty (const std::string & data_name) const inline protected
Returns
Whether or not a mesh meta-data exists with the default prefix and the given type.
Definition at line 82 of file MeshMetaDataInterface.h.
  {
    return hasMeshProperty<T>(data_name, meshPropertyPrefix(data_name));
  }
hasMeshProperty() [3/4]
bool MeshMetaDataInterface::hasMeshProperty (const std::string & data_name, const std::string & prefix) const protected
Returns
Whether or not a mesh meta-data exists.
Definition at line 25 of file MeshMetaDataInterface.C.
{
  return _meta_data_app.hasRestartableMetaData(meshPropertyName(data_name, prefix),
                                               MooseApp::MESH_META_DATA);
}
Referenced by MeshGenerator::declareMeshProperty(), getMeshProperty(), hasMeshProperty(), and MeshGenerator::setMeshProperty().
hasMeshProperty() [4/4]
template<typename T > bool MeshMetaDataInterface::hasMeshProperty (const std::string & data_name, const std::string & prefix) const protected
Returns
Whether or not a mesh meta-data exists with the given type.
Definition at line 158 of file MeshMetaDataInterface.h.
{
  if (!hasMeshProperty(data_name, prefix))
    return false;
  const auto & value = getMeshPropertyInternal(data_name, prefix);
  return dynamic_cast<const RestartableData<T> *>(&value) != nullptr;
}
meshPropertyName() [1/2]
std::string MeshMetaDataInterface::meshPropertyName (const std::string & data_name) const inline protected
Returns
The default mesh property name for mesh property data
Definition at line 95 of file MeshMetaDataInterface.h.
  {
    return meshPropertyName(data_name, meshPropertyPrefix(data_name));
  }
meshPropertyName() [2/2]
std::string MeshMetaDataInterface::meshPropertyName (const std::string & data_name, const std::string & prefix) static protected
Returns
The full name for mesh property data.
Definition at line 33 of file MeshMetaDataInterface.C.
{
  return std::string(SYSTEM) + "/" + prefix + "/" + data_name;
}
Referenced by MeshGenerator::declareMeshProperty(), getMeshPropertyInternal(), hasMeshProperty(), meshPropertyName(), and MeshGenerator::setMeshPropertyHelper().
meshPropertyPrefix()
std::string MeshMetaDataInterface::meshPropertyPrefix (const std::string & data_name) const private virtual
The default prefix to use for getting/seeing if mesh properties exist.
For now, this is not supported except in MeshGenerators. In the future, we will automate looking for mesh properties.
Reimplemented in MeshGenerator.
Definition at line 39 of file MeshMetaDataInterface.C.
{
  mooseError("This object does not support obtaining a mesh property without a prefix.\n\nThis "
             "capability is upcoming.");
}
Referenced by getMeshProperty(), hasMeshProperty(), and meshPropertyName().
mooseErrorInternal()
template<typename... Args> void MeshMetaDataInterface::mooseErrorInternal (Args &&... args) const inline private
Helper for forwarding a mooseError to an object's mooseError if it is available (said error will provide more context: object name and type)
Definition at line 124 of file MeshMetaDataInterface.h.
  {
    if (_meta_data_object)
      _meta_data_object->mooseError(std::forward<Args>(args)...);
    mooseError(std::forward<Args>(args)...);
  }
Referenced by getMeshProperty().
Member Data Documentation
_meta_data_app
MooseApp& MeshMetaDataInterface::_meta_data_app private
Reference to the application.
Definition at line 114 of file MeshMetaDataInterface.h.
Referenced by getMeshPropertyInternal(), and hasMeshProperty().
_meta_data_object
const MooseObject* const MeshMetaDataInterface::_meta_data_object private
The MooseObject (if any); used for better error handling.
Definition at line 117 of file MeshMetaDataInterface.h.
Referenced by mooseErrorInternal().
NAME
constexpr auto MeshMetaDataInterface::NAME = "<empty>" static constexpr
The data name used when initializing the Restartable interface for non-MeshGenerator objects.
Definition at line 33 of file MeshMetaDataInterface.h.
SYSTEM
constexpr auto MeshMetaDataInterface::SYSTEM = "MeshMetaData" static constexpr
The system name used when initializing the Restartable interface.
Definition at line 30 of file MeshMetaDataInterface.h.
Referenced by meshPropertyName().
The documentation for this class was generated from the following files:
moose/framework/include/interfaces/MeshMetaDataInterface.h
moose/framework/src/interfaces/MeshMetaDataInterface.C