Zapdos: InputParameters Class Reference
InputParameters Class Reference
The main MOOSE class responsible for handling user-defined parameters in almost every MOOSE system.
#include <InputParameters.h>
Classes
struct Metadata
Public Member Functions
InputParameters (const InputParameters &rhs)
InputParameters (const Parameters &rhs)
virtual ~InputParameters ()=default
virtual void clear () override
void addClassDescription (const std::string &doc_string)
This method adds a description of the class that will be displayed in the input file syntax dump.
std::string getClassDescription () const
Returns the class description.
virtual void set_attributes (const std::string &name, bool inserted_only) override
Override from libMesh to set user-defined attributes on our parameter.
bool attemptPrintDeprecated (const std::string &name)
Prints the deprecated parameter message, assuming we have the right flags set.
template<typename T >
void setHelper (const std::string &name)
This functions is called in set as a 'callback' to avoid code duplication.
template<typename T >
T & set (const std::string &name, bool quiet_mode=false)
Returns a writable reference to the named parameters.
template<typename T , typename... Ts>
void setParameters (const std::string &name, const T &value, Ts... extra_input_parameters)
Given a series of parameters names and values, sets each name to the corresponding value.
template<typename T , typename UP_T >
void rangeCheck (const std::string &full_name, const std::string &short_name, InputParameters::Parameter< T > *param, std::ostream &oss=Moose::out)
Runs a range on the supplied parameter if it exists and throws an error if that check fails.
template<typename T , typename UP_T >
void rangeCheck (const std::string &full_name, const std::string &short_name, InputParameters::Parameter< std::vector< T > > *param, std::ostream &oss=Moose::out)
template<typename T >
T getCheckedPointerParam (const std::string &name, const std::string &error_string="") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
template<typename T >
void addRequiredParam (const std::string &name, const std::string &doc_string)
This method adds a parameter and documentation string to the InputParameters object that will be extracted from the input file.
template<typename T >
void addRequiredParam (const std::string &name, const T &moose_enum, const std::string &doc_string)
This version of addRequiredParam is here for a consistent use with MooseEnums.
template<typename T >
void addParam (const std::string &name, const std::initializer_list< typename T::value_type > &value, const std::string &doc_string)
Enable support for initializer lists as default arguments for container type.
template<typename T >
void addRequiredCustomTypeParam (const std::string &name, const std::string &custom_type, const std::string &doc_string)
These methods add an option parameter and with a customer type to the InputParameters object.
template<typename T >
void addCustomTypeParam (const std::string &name, const T &value, const std::string &custom_type, const std::string &doc_string)
template<typename T >
void addCustomTypeParam (const std::string &name, const std::string &custom_type, const std::string &doc_string)
template<typename T >
void addDeprecatedCustomTypeParam (const std::string &name, const std::string &custom_type, const std::string &doc_string, const std::string &deprecation_msg)
template<typename T >
void addPrivateParam (const std::string &name, const T &value)
These method add a parameter to the InputParameters object which can be retrieved like any other parameter.
template<typename T >
void addPrivateParam (const std::string &name)
template<typename T >
void addRequiredCommandLineParam (const std::string &name, const std::string &syntax, const std::string &doc_string)
Add parameters for retrieval from the command line.
template<typename T >
void addCommandLineParam (const std::string &name, const std::string &syntax, const std::string &doc_string)
template<typename T >
void addCommandLineParam (const std::string &name, const std::string &syntax, const T &value, const std::string &doc_string)
template<typename T >
void addDeprecatedParam (const std::string &name, const T &value, const std::string &doc_string, const std::string &deprecation_message)
template<typename T >
void addDeprecatedParam (const std::string &name, const std::string &doc_string, const std::string &deprecation_message)
template<typename T >
void checkConsistentType (const std::string &name) const
This method checks to make sure that we aren't adding a parameter with the same name but a different type.
std::vector< std::string > getSyntax (const std::string &name) const
Get the syntax for a command-line parameter.
const std::string & getDescription (const std::string &name) const
Get the documentation string for a parameter.
void addParamNamesToGroup (const std::string &space_delim_names, const std::string group_name)
This method takes a space delimited list of parameter names and adds them to the specified group name.
std::string getGroupName (const std::string &param_name) const
This method retrieves the group name for the passed parameter name if one exists.
template<typename T >
void suppressParameter (const std::string &name)
This method suppresses an inherited parameter so that it isn't required or valid in the derived class.
template<typename T >
void makeParamRequired (const std::string &name)
Changes the parameter to be required.
template<typename T >
void makeParamNotRequired (const std::string &name)
Changes the parameter to not be required.
void addCoupledVar (const std::string &name, const std::string &doc_string)
This method adds a coupled variable name pair.
void addDeprecatedCoupledVar (const std::string &old_name, const std::string &new_name, const std::string &removal_date="")
This method adds a deprecated coupled variable name pair.
void addCoupledVar (const std::string &name, const Real value, const std::string &doc_string)
This method adds a coupled variable name pair.
void addCoupledVar (const std::string &name, const std::vector< Real > &value, const std::string &doc_string)
This method adds a coupled variable name pair.
std::string getMooseType (const std::string &name) const
Utility functions for retrieving one of the MooseTypes variables into the common "string" base class.
std::vector< std::string > getVecMooseType (const std::string &name) const
void addRequiredCoupledVar (const std::string &name, const std::string &doc_string)
This method adds a coupled variable name pair.
std::string getDocString (const std::string &name) const
Returns the documentation string for the specified parameter name.
void setDocString (const std::string &name, const std::string &doc)
Set the doc string of a parameter.
bool isParamRequired (const std::string &name) const
Returns a boolean indicating whether the specified parameter is required or not.
void makeParamNotRequired (const std::string &name)
Forces parameter of given name to be not required regardless of type.
bool isParamValid (const std::string &name) const
This method returns parameters that have been initialized in one fashion or another, i.e.
bool isParamSetByAddParam (const std::string &name) const
Returns whether or not the parameter was set due to addParam.
bool isParamDeprecated (const std::string &name) const
Returns True if the parameters is deprecated.
bool areAllRequiredParamsValid () const
This method returns true if all of the parameters in this object are valid (i.e.
std::string type (const std::string &name) const
Prints the type of the requested parameter by name.
bool isPrivate (const std::string &name) const
Returns a Boolean indicating whether the specified parameter is private or not.
void declareControllable (const std::string &name, std::set< ExecFlagType > execute_flags={})
Declare the given parameters as controllable.
void markControlled (const std::string &name)
Marker a parameter that has been changed by the Control system (this is for output purposes)
bool isControllable (const std::string &name) const
Returns a Boolean indicating whether the specified parameter is controllable.
const std::set< ExecFlagType > & getControllableExecuteOnTypes (const std::string &name) const
Return the allowed execute flags for a controllable parameter.
void registerBase (const std::string &value)
This method must be called from every base "Moose System" to create linkage with the Action System.
void registerSystemAttributeName (const std::string &value)
This method is used to define the MOOSE system name that is used by the TheWarehouse object for storing objects to be retrieved for execution.
const std::string & getSystemAttributeName () const
Get the system attribute name if it was registered.
void registerBuildableTypes (const std::string &names)
This method is here to indicate which Moose types a particular Action may build.
void addRelationshipManager (const std::string &name, Moose::RelationshipManagerType rm_type, Moose::RelationshipManagerInputParameterCallback input_parameter_callback=nullptr)
Tells MOOSE about a RelationshipManager that this object needs.
void clearRelationshipManagers ()
Clears all currently registered RelationshipManagers.
const std::vector< std::string > & getBuildableTypes () const
Returns the list of buildable types as a std::vector<std::string>
const std::vector< std::tuple< std::string, Moose::RelationshipManagerType, Moose::RelationshipManagerInputParameterCallback > > & getBuildableRelationshipManagerTypes () const
Returns the list of buildable (or required) RelationshipManager object types for this object.
void checkParams (const std::string &parsing_syntax)
This function checks parameters stored in the object to make sure they are in the correct state as the user expects: Required parameters are verified as valid meaning that they were either initialized when they were created, or were read from an input file or some other valid source.
std::set< std::string >::const_iterator coupledVarsBegin () const
Methods returning iterators to the coupled variables names stored in this InputParameters object.
std::set< std::string >::const_iterator coupledVarsEnd () const
const std::set< std::string > & getCoupledVariableParamNames () const
Return the coupled variable parameter names.
const std::unordered_map< std::string, std::string > & getNewToDeprecatedVarMap () const
Return the new to deprecated variable name map.
bool isRangeChecked (const std::string &param_name) const
Return whether a parameter has a range check.
std::string rangeCheckedFunction (const std::string &name) const
Return the range check function for any parameter (empty string if it is not range checked)
bool hasDefault (const std::string &param_name) const
Return whether a parameter has a default.
bool hasCoupledValue (const std::string &coupling_name) const
Return whether or not the coupled variable exists.
bool hasDefaultCoupledValue (const std::string &coupling_name) const
Return whether or not the requested parameter has a default coupled value.
Real defaultCoupledValue (const std::string &coupling_name, unsigned int i=0) const
Get the default value for an optionally coupled variable.
unsigned int numberDefaultCoupledValues (const std::string &coupling_name) const
Get the number of defaulted coupled value entries.
void defaultCoupledValue (const std::string &coupling_name, Real value, unsigned int i=0)
Set the default value for an optionally coupled variable (called by the Parser).
std::map< std::string, std::pair< std::string, std::string > > getAutoBuildVectors () const
Returns the auto build vectors for all parameters.
void applyParameters (const InputParameters &common, std::vector< std::string > exclude=std::vector< std::string >())
Method for applying common parameters.
void applySpecificParameters (const InputParameters &common, const std::vector< std::string > &include, bool allow_private=false)
Method for applying common parameters.
void applyParameter (const InputParameters &common, const std::string &common_name, bool allow_private=false)
Apply values from a single parameter in common, to a single parameter stored in this object.
void applyCoupledVar (const InputParameters &common, const std::string &var_name)
Apply properties of a single coupled variable in common, to a single coupled variable stored in this object.
bool paramSetByUser (const std::string &name) const
Deprecated method.
bool isParamSetByUser (const std::string &name) const
Method returns true if the parameter was by the user.
template<typename R1 , typename R2 , typename V1 = typename std::conditional<std::is_same<R1, MooseEnumItem>::value, MultiMooseEnum, std::vector<R1>>::type, typename V2 = typename std::conditional<std::is_same<R2, MooseEnumItem>::value, MultiMooseEnum, std::vector<R2>>::type>
std::vector< std::pair< R1, R2 > > get (const std::string &param1, const std::string &param2) const
Combine two vector parameters into a single vector of pairs.
std::set< std::string > getParametersList () const
std::set< std::string > getControllableParameters () const
Return list of controllable parameters.
std::set< std::string > getGroupParameters (const std::string &group) const
Return names of parameters within a group.
void setReservedValues (const std::string &name, const std::set< std::string > &reserved)
Provide a set of reserved values for a parameter.
std::set< std::string > reservedValues (const std::string &name) const
Get a set of reserved parameter values.
std::string errorPrefix (const std::string &param) const
generate error message prefix with parameter name and location (if available)
std::string & rawParamVal (const std::string &param)
Get/set a string representing the raw, unmodified token text for the given param.
const std::string & rawParamVal (const std::string &param) const
template<typename T >
void ignoreParameter (const std::string &name)
Informs this object that values for this parameter set from the input file or from the command line should be ignored.
bool shouldIgnore (const std::string &name)
Whether to ignore the value of an input parameter set in the input file or from the command line.
template<typename T >
bool isType (const std::string &name) const
std::string varName (const std::string &var_param_name, const std::string &moose_object_with_var_param_name) const
Determine the actual variable name from the given variable \emph parameter name.
void renameParam (const std::string &old_name, const std::string &new_name, const std::string &new_docstring)
Rename a parameter and provide a new documentation string.
void renameCoupledVar (const std::string &old_name, const std::string &new_name, const std::string &new_docstring)
Rename a coupled variable and provide a new documentation string.
void deprecateParam (const std::string &old_name, const std::string &new_name, const std::string &removal_date)
void deprecateCoupledVar (const std::string &old_name, const std::string &new_name, const std::string &removal_date)
std::string checkForRename (const std::string &name) const
Checks whether the provided name is a renamed parameter name.
template<typename T >
const T & get (std::string_view name) const
A wrapper around the Parameters base class method.
template<typename T >
bool have_parameter (std::string_view name) const
A wrapper around the Parameters base class method.
template<typename T >
void transferParam (const InputParameters &source_param, const std::string &name, const std::string &new_description="")
A routine to transfer a parameter from one class' validParams to another.
std::vector< std::string > paramAliases (const std::string &param_name) const
Return all the aliased names associated with param_name.
template<>
void addRequiredParam (const std::string &name, const MooseEnum &moose_enum, const std::string &doc_string)
template<>
void addRequiredParam (const std::string &name, const MultiMooseEnum &moose_enum, const std::string &doc_string)
template<>
void addParam (const std::string &, const std::string &)
template<>
void addParam (const std::string &, const std::string &)
template<>
void addPrivateParam (const std::string &)
template<>
void addPrivateParam (const std::string &)
template<>
void addDeprecatedParam (const std::string &, const std::string &, const std::string &)
template<>
void addDeprecatedParam (const std::string &, const std::string &, const std::string &)
template<>
void addRequiredParam (const std::string &name, const MooseEnum &moose_enum, const std::string &doc_string)
template<>
void addRequiredParam (const std::string &name, const MultiMooseEnum &moose_enum, const std::string &doc_string)
template<>
void addParam (const std::string &, const std::string &)
template<>
void addParam (const std::string &, const std::string &)
template<>
void addPrivateParam (const std::string &)
template<>
void addPrivateParam (const std::string &)
template<>
void addDeprecatedParam (const std::string &name, const std::string &doc_string, const std::string &deprecation_message)
template<>
void addDeprecatedParam (const std::string &name, const std::string &doc_string, const std::string &deprecation_message)
template<typename T , typename S >
void addParam (const std::string &name, const S &value, const std::string &doc_string)
These methods add an option parameter and a documentation string to the InputParameters object.
template<typename T >
void addParam (const std::string &name, const std::string &doc_string)
template<typename T >
void addRequiredRangeCheckedParam (const std::string &name, const std::string &parsed_function, const std::string &doc_string)
These methods add an range checked parameters.
template<typename T >
void addRangeCheckedParam (const std::string &name, const T &value, const std::string &parsed_function, const std::string &doc_string)
template<typename T >
void addRangeCheckedParam (const std::string &name, const std::string &parsed_function, const std::string &doc_string)
void addCoupledVarWithAutoBuild (const std::string &name, const std::string &base_name, const std::string &num_name, const std::string &doc_string)
These methods add a coupled variable name pair.
void addRequiredCoupledVarWithAutoBuild (const std::string &name, const std::string &base_name, const std::string &num_name, const std::string &doc_string)
void collapseSyntaxNesting (bool collapse)
Mutators for controlling whether or not the outermost level of syntax will be collapsed when printed.
bool collapseSyntaxNesting () const
void mooseObjectSyntaxVisibility (bool visibility)
Mutators for controlling whether or not the outermost level of syntax will be collapsed when printed.
bool mooseObjectSyntaxVisibility () const
InputParameters & operator= (const InputParameters &rhs)
InputParameters & operator+= (const InputParameters &rhs)
std::string & blockLocation ()
Get/set a string representing the location (i.e.
const std::string & blockLocation () const
std::string & blockFullpath ()
Get/set a string representing the full HIT parameter path from the input file (e.g.
const std::string & blockFullpath () const
const std::string & inputLocation (const std::string &param) const
Get/set a string representing the location in the input text the parameter originated from (i.e.
std::string & inputLocation (const std::string &param)
const std::string & paramFullpath (const std::string &param) const
Get/set a string representing the full HIT parameter path from the input file (e.g.
std::string & paramFullpath (const std::string &param)
Static Public Member Functions
template<>
const MooseEnum & getParamHelper (const std::string &name_in, const InputParameters &pars, const MooseEnum *, const MooseObject *)
template<>
const MultiMooseEnum & getParamHelper (const std::string &name_in, const InputParameters &pars, const MultiMooseEnum *, const MooseObject *)
template<>
const MooseEnum & getParamHelper (const std::string &name, const InputParameters &pars, const MooseEnum *, const MooseObject *moose_object)
template<>
const MultiMooseEnum & getParamHelper (const std::string &name, const InputParameters &pars, const MultiMooseEnum *, const MooseObject *moose_object)
template<typename T >
static const T & getParamHelper (const std::string &name, const InputParameters &pars, const T *the_type, const MooseObject *moose_object=nullptr)
Private Member Functions
InputParameters ()
void setParameters ()
Method to terminate the recursive setParameters definition.
template<typename T >
void addCommandLineParamHelper (const std::string &name, const std::string &syntax, const std::string &doc_string, T *)
Helper that uses overloading to distinguish adding commandline parameters of a scalar and a vector kind.
template<typename T >
void addCommandLineParamHelper (const std::string &name, const std::string &syntax, const std::string &doc_string, std::vector< T > *)
void setDeprecatedVarDocString (const std::string &new_name, const std::string &doc_string)
Private method for setting deprecated coupled variable documentation strings.
void renameParamInternal (const std::string &old_name, const std::string &new_name, const std::string &docstring, const std::string &removal_date)
void renameCoupledVarInternal (const std::string &old_name, const std::string &new_name, const std::string &docstring, const std::string &removal_date)
Metadata & at (const std::string &param_name)
const Metadata & at (const std::string &param_name) const
void allowCopy (bool status)
Toggle the availability of the copy constructor.
void checkParamName (const std::string &name) const
Make sure the parameter name doesn't have any invalid characters.
template<typename T , typename S >
void setParamHelper (const std::string &name, T &l_value, const S &r_value)
This method is called when adding a Parameter with a default value, can be specialized for non-matching types.
template<>
void setParamHelper (const std::string &, PostprocessorName &l_value, const Real &r_value)
template<>
void setParamHelper (const std::string &, PostprocessorName &l_value, const int &r_value)
template<>
void setParamHelper (const std::string &, FunctionName &l_value, const Real &r_value)
template<>
void setParamHelper (const std::string &, FunctionName &l_value, const int &r_value)
template<>
void setParamHelper (const std::string &, MaterialPropertyName &l_value, const Real &r_value)
template<>
void setParamHelper (const std::string &, MaterialPropertyName &l_value, const int &r_value)
template<>
void setParamHelper (const std::string &, MooseFunctorName &l_value, const Real &r_value)
template<>
void setParamHelper (const std::string &, MooseFunctorName &l_value, const int &r_value)
template<>
void setParamHelper (const std::string &name, PostprocessorName &l_value, const Real &r_value)
template<>
void setParamHelper (const std::string &name, PostprocessorName &l_value, const int &r_value)
template<>
void setParamHelper (const std::string &, FunctionName &l_value, const Real &r_value)
template<>
void setParamHelper (const std::string &, FunctionName &l_value, const int &r_value)
template<>
void setParamHelper (const std::string &, MaterialPropertyName &l_value, const Real &r_value)
template<>
void setParamHelper (const std::string &, MaterialPropertyName &l_value, const int &r_value)
template<>
void setParamHelper (const std::string &, MooseFunctorName &l_value, const Real &r_value)
template<>
void setParamHelper (const std::string &, MooseFunctorName &l_value, const int &r_value)
Static Private Member Functions
static void callMooseErrorHelper (const MooseObject &object, const std::string &error)
Private Attributes
std::string _block_location
original location of input block (i.e. filename,linenum) - used for nice error messages.
std::string _block_fullpath
full HIT path of the block from the input file - used for nice error messages.
std::map< std::string, Metadata > _params
The actual parameter data.
std::set< std::string > _coupled_vars
The coupled variables set.
std::string _class_description
The class description for the owning object.
std::vector< std::string > _buildable_types
The parameter is used to restrict types that can be built.
std::vector< std::tuple< std::string, Moose::RelationshipManagerType, Moose::RelationshipManagerInputParameterCallback > > _buildable_rm_types
The RelationshipManagers that this object may either build or require.
bool _collapse_nesting
This parameter collapses one level of nesting in the syntax blocks.
bool _moose_object_syntax_visibility
This parameter hides derived MOOSE object types from appearing in syntax dumps.
bool _show_deprecated_message
Flag for disabling deprecated parameters message, this is used by applyParameters to avoid dumping messages.
bool _allow_copy
A flag for toggling the error message in the copy constructor.
std::unordered_map< std::string, std::string > _new_to_deprecated_coupled_vars
A map from deprecated coupled variable names to the new blessed name.
std::map< std::string, std::pair< std::string, std::string > > _old_to_new_name_and_dep
A map from base-class/deprecated parameter names to derived-class/blessed parameter names and the deprecation messages in the case that the "old" parameter name is a deprecated parameter name.
std::multimap< std::string, std::string > _new_to_old_names
A map from derived-class/blessed parameter names to associated base-class/deprecated parameter names.
Friends
class InputParameterWarehouse
class Parser
class ActionWarehouse
InputParameters emptyInputParameters ()
Detailed Description
The main MOOSE class responsible for handling user-defined parameters in almost every MOOSE system.
Definition at line 47 of file InputParameters.h.
Constructor & Destructor Documentation
InputParameters() [1/3]
InputParameters::InputParameters (const InputParameters & rhs)
Definition at line 43 of file InputParameters.C.
  : Parameters(), _show_deprecated_message(true), _allow_copy(true)
{
  *this = rhs;
}
InputParameters() [2/3]
InputParameters::InputParameters (const Parameters & rhs)
Definition at line 49 of file InputParameters.C.
  : _show_deprecated_message(true), _allow_copy(true)
{
  _params.clear();
  Parameters::operator=(rhs);
  _collapse_nesting = false;
  _moose_object_syntax_visibility = true;
}
~InputParameters()
virtual InputParameters::~InputParameters () virtual default
InputParameters() [3/3]
InputParameters::InputParameters () private
Definition at line 34 of file InputParameters.C.
  : Parameters(),
    _collapse_nesting(false),
    _moose_object_syntax_visibility(true),
    _show_deprecated_message(true),
    _allow_copy(true)
{
}
Member Function Documentation
addClassDescription()
void InputParameters::addClassDescription (const std::string & doc_string)
This method adds a description of the class that will be displayed in the input file syntax dump.
Definition at line 76 of file InputParameters.C.
{
  _class_description = doc_string;
}
Referenced by AddGeneralReactions::validParams(), AddReactions::validParams(), AddScalarReactions::validParams(), AddSpecies::validParams(), AddZapdosReactions::validParams(), ChemicalReactions::validParams(), ChemicalReactionsBase::validParams(), ParsedAuxScalar::validParams(), ParsedScalarRateCoefficient::validParams(), ReactionRateFirstOrder::validParams(), ReactionRateFirstOrderLog::validParams(), ReactionRateSecondOrder::validParams(), ReactionRateSecondOrderLog::validParams(), ReactionRateThirdOrder::validParams(), ReactionRateThirdOrderLog::validParams(), ADEEDFEnergyTownsendLog::validParams(), ADEEDFRateConstantTownsend::validParams(), InterpolatedCoefficientLinear::validParams(), InterpolatedCoefficientSpline::validParams(), AddPeriodicControllers::validParams(), AddPeriodicRelativeNodalDifference::validParams(), AbsValueAux::validParams(), CurrentTempl< is_ad >::validParams(), DensityMoles::validParams(), DensityNormalization::validParams(), DiffusiveFluxTempl< is_ad >::validParams(), DriftDiffusionFluxAux::validParams(), Efield::validParams(), EFieldAdvAuxTempl< is_ad >::validParams(), ElectronTemperature::validParams(), Position::validParams(), PowerDepTempl< is_ad >::validParams(), ProcRateTempl< is_ad >::validParams(), ProcRateForRateCoeffTempl< is_ad >::validParams(), ProcRateForRateCoeffThreeBodyTempl< is_ad >::validParams(), TotalFluxTempl< is_ad >::validParams(), CircuitDirichletPotential::validParams(), DCIonBC::validParams(), DriftDiffusionDoNothingBC::validParams(), EconomouDielectricBC::validParams(), ElectronAdvectionDoNothingBC::validParams(), ElectronDiffusionDoNothingBC::validParams(), ElectronTemperatureDirichletBC::validParams(), HagelaarElectronAdvectionBC::validParams(), HagelaarElectronBC::validParams(), HagelaarEnergyAdvectionBC::validParams(), HagelaarIonAdvectionBC::validParams(), HagelaarIonDiffusionBC::validParams(), LogDensityDirichletBC::validParams(), LymberopoulosElectronBC::validParams(), LymberopoulosIonBC::validParams(), MatchedValueLogBC::validParams(), NeumannCircuitVoltageNew::validParams(), PenaltyCircuitPotential::validParams(), SakiyamaElectronDiffusionBC::validParams(), SakiyamaEnergyDiffusionBC::validParams(), SakiyamaEnergySecondaryElectronBC::validParams(), SakiyamaIonAdvectionBC::validParams(), SakiyamaSecondaryElectronBC::validParams(), DGCoeffDiffusion::validParams(), DGEFieldAdvection::validParams(), AnalyticalDiffIndicator::validParams(), InterfaceAdvection::validParams(), InterfaceLogDiffusionElectrons::validParams(), AccelerationByAveraging::validParams(), ChargeSourceMoles_KV::validParams(), CoeffDiffusion::validParams(), CoeffDiffusionForShootMethod::validParams(), CoeffDiffusionLin::validParams(), DriftDiffusion::validParams(), EEDFReactionLogForShootMethod::validParams(), EFieldAdvection::validParams(), EFieldArtDiff::validParams(), EFieldMagnitudeSource::validParams(), ElectronEnergyLossFromElastic::validParams(), ElectronEnergyLossFromExcitation::validParams(), ElectronEnergyLossFromIonization::validParams(), ElectronEnergyTermElasticRate::validParams(), ElectronEnergyTermRate::validParams(), ElectronsFromIonization::validParams(), ElectronTimeDerivative::validParams(), ExcitationReaction::validParams(), IonsFromIonization::validParams(), JouleHeating::validParams(), LogStabilizationMoles::validParams(), PotentialGradientSource::validParams(), ProductAABBRxn::validParams(), ProductFirstOrderRxn::validParams(), ReactantAARxn::validParams(), ReactantFirstOrderRxn::validParams(), ReactionSecondOrderLogForShootMethod::validParams(), ReactionThirdOrderLogForShootMethod::validParams(), ScaledReaction::validParams(), ShootMethodLog::validParams(), UserSource::validParams(), ADGasElectronMoments::validParams(), ADSurfaceCharge::validParams(), Gas::validParams(), GasBase::validParams(), GasElectronMoments::validParams(), Water::validParams(), AverageNodalDensity::validParams(), AverageNodalDifference::validParams(), PeriodicComparisonCounter::validParams(), PlasmaFrequencyInverse::validParams(), RelativeElementL2Difference::validParams(), SideTotFluxIntegral::validParams(), BlockAverageValue::validParams(), CurrentDensityShapeSideUserObject::validParams(), ProvideMobility::validParams(), AdaptivityAction::validParams(), AddAuxVariableAction::validParams(), AddBCAction::validParams(), AddBoundsVectorsAction::validParams(), AddConstraintAction::validParams(), AddControlAction::validParams(), AddDamperAction::validParams(), AddDGKernelAction::validParams(), AddDiracKernelAction::validParams(), AddDistributionAction::validParams(), AddElementalFieldAction::validParams(), AddFieldSplitAction::validParams(), AddFunctionAction::validParams(), AddFunctorMaterialAction::validParams(), AddFVBCAction::validParams(), AddFVInitialConditionAction::validParams(), AddFVInterfaceKernelAction::validParams(), AddFVKernelAction::validParams(), AddIndicatorAction::validParams(), AddInitialConditionAction::validParams(), AddInterfaceKernelAction::validParams(), AddKernelAction::validParams(), AddMarkerAction::validParams(), AddMaterialAction::validParams(), AddMeshDivisionAction::validParams(), AddMeshGeneratorAction::validParams(), AddMultiAppAction::validParams(), AddNodalKernelAction::validParams(), AddNodalNormalsAction::validParams(), AddOutputAction::validParams(), AddPeriodicBCAction::validParams(), AddPositionsAction::validParams(), AddPostprocessorAction::validParams(), AddReporterAction::validParams(), AddSamplerAction::validParams(), AddScalarKernelAction::validParams(), AddTimesAction::validParams(), AddTimeStepperAction::validParams(), AddTransferAction::validParams(), AddUserObjectAction::validParams(), AddVectorPostprocessorAction::validParams(), CheckFVBCAction::validParams(), CommonOutputAction::validParams(), ComposeTimeStepperAction::validParams(), CopyNodalVarsAction::validParams(), CreateDisplacedProblemAction::validParams(), CreateExecutionerAction::validParams(), CreateProblemAction::validParams(), DeprecatedBlockAction::validParams(), DisplayGhostingAction::validParams(), DynamicObjectRegistrationAction::validParams(), ElementIDOutputAction::validParams(), GlobalParamsAction::validParams(), MaterialDerivativeTestAction::validParams(), MooseObjectAction::validParams(), PartitionerAction::validParams(), ProjectedStatefulMaterialStorageAction::validParams(), ReadExecutorParamsAction::validParams(), SetAdaptivityOptionsAction::validParams(), SetupDebugAction::validParams(), SetupMeshAction::validParams(), SetupMeshCompleteAction::validParams(), SetupPreconditionerAction::validParams(), SetupPredictorAction::validParams(), SetupQuadratureAction::validParams(), SetupResidualDebugAction::validParams(), SetupTimeIntegratorAction::validParams(), SetupTimeStepperAction::validParams(), AdvectiveFluxAux::validParams(), ArrayParsedAux::validParams(), ArrayVariableComponent::validParams(), ArrayVarReductionAux::validParams(), BuildArrayVariableAux::validParams(), ConstantAux::validParams(), ConstantBoundsAux::validParams(), ConstantScalarAux::validParams(), ContainsPointAux::validParams(), CopyValueAux::validParams(), DebugResidualAux::validParams(), DiffusionFluxAux::validParams(), DivergenceAuxTempl< is_ad >::validParams(), ElementH1ErrorFunctionAux::validParams(), ElementIntegerAux::validParams(), ElementL2ErrorFunctionAux::validParams(), ElementLengthAux::validParams(), ElementLpNormAux::validParams(), ElementQualityAux::validParams(), ElementUOAux::validParams(), ExtraElementIDAux::validParams(), ForcingFunctionAux::validParams(), FunctionArrayAux::validParams(), FunctionAux::validParams(), FunctionScalarAux::validParams(), FunctorAux::validParams(), FunctorElementalGradientAuxTempl< is_ad >::validParams(), FunctorVectorElementalAuxTempl< is_ad >::validParams(), GapValueAux::validParams(), GhostingAux::validParams(), HardwareIDAux::validParams(), InterfaceValueUserObjectAux::validParams(), MaterialRankFourTensorAux::validParams(), MaterialRankTwoTensorAuxTempl< is_ad >::validParams(), MaterialRateRealAuxTempl< is_ad >::validParams(), MaterialRealAuxTempl< is_ad >::validParams(), MaterialRealDenseMatrixAux::validParams(), MaterialRealTensorValueAux::validParams(), MaterialRealVectorValueAuxTempl< is_ad >::validParams(), MaterialStdVectorAuxTempl< is_ad >::validParams(), MaterialStdVectorRealGradientAux::validParams(), MeshDivisionAux::validParams(), NearestNodeDistanceAux::validParams(), NearestNodeValueAux::validParams(), NodalPatchRecoveryAuxBase::validParams(), NormalizationAux::validParams(), ParsedAux::validParams(), ParsedVectorAux::validParams(), PenetrationAux::validParams(), ProcessorIDAux::validParams(), ProjectionAux::validParams(), QuotientAux::validParams(), QuotientScalarAux::validParams(), ScalarTagMatrixAux::validParams(), ScalarTagVectorAux::validParams(), SecondTimeDerivativeAux::validParams(), SolutionAux::validParams(), SolutionScalarAux::validParams(), SpatialUserObjectAux::validParams(), TagMatrixAux::validParams(), TagVectorArrayVariableAux::validParams(), TagVectorArrayVariableValueAux::validParams(), TagVectorAux::validParams(), TimeDerivativeAux::validParams(), VariableGradientComponent::validParams(), VariableOldValueBoundsAux::validParams(), VariableTimeIntegrationAux::validParams(), VectorFunctionAux::validParams(), VectorMagnitudeAux::validParams(), VectorPostprocessorVisualizationAux::validParams(), VectorVariableComponentAux::validParams(), VectorVariableMagnitudeAux::validParams(), VolumeAux::validParams(), WeightedGapAux::validParams(), ADConservativeAdvectionBC::validParams(), ADDirichletBC::validParams(), ADFunctionDirichletBC::validParams(), ADFunctionNeumannBC::validParams(), ADFunctionPenaltyDirichletBC::validParams(), ADPenaltyDirichletBC::validParams(), ADRobinBC::validParams(), ADVectorFunctionDirichletBC::validParams(), ADVectorFunctionNeumannBC::validParams(), ADVectorMatchedValueBC::validParams(), ADVectorRobinBC::validParams(), ArrayDirichletBC::validParams(), ArrayHFEMDirichletBC::validParams(), ArrayNeumannBC::validParams(), ArrayPenaltyDirichletBC::validParams(), ArrayVacuumBC::validParams(), ConvectiveFluxBC::validParams(), CoupledVarNeumannBC::validParams(), DGFunctionDiffusionDirichletBC::validParams(), DiffusionFluxBC::validParams(), DirichletBC::validParams(), EigenArrayDirichletBC::validParams(), EigenDirichletBC::validParams(), FunctionDirichletBC::validParams(), FunctionGradientNeumannBC::validParams(), FunctionNeumannBC::validParams(), FunctionPenaltyDirichletBC::validParams(), FunctorDirichletBC::validParams(), FunctorNeumannBC::validParams(), HFEMDirichletBC::validParams(), MatchedValueBCTempl< is_ad >::validParams(), MatNeumannBCTempl< is_ad >::validParams(), NeumannBCTempl< is_ad >::validParams(), OneDEqualValueConstraintBC::validParams(), PenaltyDirichletBC::validParams(), PostprocessorDirichletBC::validParams(), PostprocessorNeumannBC::validParams(), SinDirichletBC::validParams(), SinNeumannBC::validParams(), VacuumBC::validParams(), VectorCurlPenaltyDirichletBC::validParams(), VectorDirichletBC::validParams(), VectorDivPenaltyDirichletBC::validParams(), VectorFunctionDirichletBC::validParams(), VectorNeumannBC::validParams(), VectorPenaltyDirichletBC::validParams(), WeakGradientBC::validParams(), ADPenaltyPeriodicSegmentalConstraint::validParams(), ADPeriodicSegmentalConstraint::validParams(), CoupledTiedValueConstraint::validParams(), EqualGradientConstraint::validParams(), EqualValueBoundaryConstraint::validParams(), EqualValueConstraint::validParams(), EqualValueEmbeddedConstraint::validParams(), LinearNodalConstraint::validParams(), OldEqualValueConstraint::validParams(), PenaltyEqualValueConstraintTempl< is_ad >::validParams(), PenaltyPeriodicSegmentalConstraint::validParams(), PeriodicSegmentalConstraint::validParams(), TiedValueConstraint::validParams(), BoolFunctionControl::validParams(), ConditionalFunctionEnableControl::validParams(), PIDTransientControl::validParams(), RealFunctionControl::validParams(), TimePeriod::validParams(), TimePeriodBase::validParams(), BoundingValueElementDamper::validParams(), BoundingValueNodalDamper::validParams(), ConstantDamper::validParams(), MaxIncrement::validParams(), ADDGAdvection::validParams(), ADDGDiffusion::validParams(), ADDGKernel::validParams(), ArrayDGDiffusion::validParams(), ArrayHFEMDiffusion::validParams(), DGConvection::validParams(), DGDiffusion::validParams(), HFEMDiffusion::validParams(), HFEMTestJump::validParams(), HFEMTrialJump::validParams(), ConstantPointSource::validParams(), FunctionDiracSource::validParams(), ReporterPointSource::validParams(), VectorConstantPointSource::validParams(), EigenExecutionerBase::validParams(), Eigenvalue::validParams(), InversePowerMethod::validParams(), Steady::validParams(), Transient::validParams(), NullExecutor::validParams(), Axisymmetric2D3DSolutionFunction::validParams(), BicubicSplineFunction::validParams(), CoarsenedPiecewiseLinear::validParams(), CompositeFunction::validParams(), ConstantFunction::validParams(), ImageFunction::validParams(), LinearCombinationFunction::validParams(), MooseParsedFunction::validParams(), MooseParsedGradFunction::validParams(), MooseParsedVectorFunction::validParams(), PeriodicFunction::validParams(), PiecewiseBilinear::validParams(), PiecewiseConstant::validParams(), PiecewiseConstantFromCSV::validParams(), PiecewiseLinear::validParams(), PiecewiseLinearBase::validParams(), PiecewiseLinearFromVectorPostprocessor::validParams(), PiecewiseMulticonstant::validParams(), PiecewiseMultilinear::validParams(), SolutionFunction::validParams(), SplineFunction::validParams(), FunctorADConverterTempl< T >::validParams(), FunctorSmootherTempl< T >::validParams(), GenericFunctorGradientMaterialTempl< is_ad >::validParams(), GenericFunctorMaterialTempl< is_ad >::validParams(), GenericVectorFunctorMaterialTempl< is_ad >::validParams(), ParsedFunctorMaterialTempl< is_ad >::validParams(), VectorMagnitudeFunctorMaterialTempl< is_ad >::validParams(), FVBoundaryIntegralValueConstraint::validParams(), FVBoundaryScalarLagrangeMultiplierConstraint::validParams(), FVConstantScalarOutflowBC::validParams(), FVDirichletBC::validParams(), FVDirichletBCBase::validParams(), FVFunctionDirichletBC::validParams(), FVFunctionNeumannBC::validParams(), FVFunctorDirichletBCTempl< is_ad >::validParams(), FVFunctorNeumannBC::validParams(), FVNeumannBC::validParams(), FVOrthogonalBoundaryDiffusion::validParams(), FVPostprocessorDirichletBC::validParams(), FVConstantIC::validParams(), FVFunctionIC::validParams(), FVDiffusionInterface::validParams(), FVOneVarDiffusionInterface::validParams(), FVScalarLagrangeMultiplierInterface::validParams(), FVTwoVarContinuityConstraint::validParams(), FVAdvection::validParams(), FVAnisotropicDiffusion::validParams(), FVBodyForce::validParams(), FVBoundedValueConstraint::validParams(), FVCoupledForce::validParams(), FVDiffusion::validParams(), FVDivergence::validParams(), FVFunctorTimeKernel::validParams(), FVIntegralValueConstraint::validParams(), FVMatAdvection::validParams(), FVOrthogonalDiffusion::validParams(), FVPointValueConstraint::validParams(), FVReaction::validParams(), FVScalarLagrangeMultiplierConstraint::validParams(), FVTimeKernel::validParams(), ArrayConstantIC::validParams(), ArrayFunctionIC::validParams(), BoundingBoxIC::validParams(), ConstantIC::validParams(), FunctionIC::validParams(), FunctionScalarIC::validParams(), IntegralPreservingFunctionIC::validParams(), RandomIC::validParams(), RandomICBase::validParams(), ScalarComponentIC::validParams(), ScalarConstantIC::validParams(), ScalarSolutionIC::validParams(), SolutionIC::validParams(), VectorConstantIC::validParams(), VectorFunctionIC::validParams(), AnalyticalIndicator::validParams(), GradientJumpIndicator::validParams(), LaplacianJumpIndicator::validParams(), ValueJumpIndicator::validParams(), InterfaceDiffusion::validParams(), InterfaceReaction::validParams(), PenaltyInterfaceDiffusionTempl< T, is_ad >::validParams(), OutputInterface::validParams(), ADConservativeAdvection::validParams(), ADMatCoupledForce::validParams(), ADMatDiffusionBase< T >::validParams(), ADMatReaction::validParams(), ADTimeDerivative::validParams(), ADVectorDiffusion::validParams(), ADVectorTimeDerivative::validParams(), AnisotropicDiffusion::validParams(), ArrayBodyForce::validParams(), ArrayCoupledTimeDerivative::validParams(), ArrayDiffusion::validParams(), ArrayReaction::validParams(), ArrayTimeDerivative::validParams(), BodyForceTempl< is_ad >::validParams(), CoefReactionTempl< is_ad >::validParams(), ConservativeAdvection::validParams(), CoupledForceTempl< is_ad >::validParams(), CoupledTimeDerivative::validParams(), Diffusion::validParams(), DivField::validParams(), FunctionDiffusion::validParams(), GradField::validParams(), MassEigenKernel::validParams(), MassLumpedTimeDerivative::validParams(), MatCoupledForce::validParams(), MatDiffusion::validParams(), MaterialDerivativeRankFourTestKernel::validParams(), MaterialDerivativeRankTwoTestKernel::validParams(), MaterialDerivativeTestKernel::validParams(), MaterialDerivativeTestKernelBase< T >::validParams(), MaterialPropertyValueTempl< is_ad >::validParams(), MatReaction::validParams(), NullKernel::validParams(), ReactionTempl< is_ad >::validParams(), ScalarLagrangeMultiplier::validParams(), ScalarLMKernelTempl< is_ad >::validParams(), TimeDerivative::validParams(), VectorBodyForce::validParams(), VectorCoupledTimeDerivative::validParams(), VectorDiffusion::validParams(), VectorFunctionReaction::validParams(), VectorTimeDerivative::validParams(), LibtorchNeuralNetControl::validParams(), LibtorchControlValuePostprocessor::validParams(), LibtorchArtificialNeuralNetParameters::validParams(), BoundaryMarker::validParams(), BoundaryPreservedMarker::validParams(), BoxMarker::validParams(), ComboMarker::validParams(), ErrorFractionMarker::validParams(), ErrorToleranceMarker::validParams(), OrientedBoxMarker::validParams(), ReporterPointMarker::validParams(), UniformMarker::validParams(), ValueRangeMarker::validParams(), ValueThresholdMarker::validParams(), ADPiecewiseLinearInterpolationMaterial::validParams(), CoupledValueFunctionMaterialTempl< is_ad >::validParams(), DerivativeParsedMaterialTempl< is_ad >::validParams(), DerivativeParsedMaterialHelperTempl< is_ad >::validParams(), DerivativeSumMaterialTempl< is_ad >::validParams(), GenericConstant2DArray::validParams(), GenericConstantArray::validParams(), GenericConstantMaterialTempl< is_ad >::validParams(), GenericConstantRankTwoTensorTempl< is_ad >::validParams(), GenericConstantVectorMaterialTempl< is_ad >::validParams(), GenericFunctionMaterialTempl< is_ad >::validParams(), GenericFunctionRankTwoTensorTempl< is_ad >::validParams(), GenericFunctionVectorMaterialTempl< is_ad >::validParams(), InterpolatedStatefulMaterialTempl< T >::validParams(), MaterialADConverterTempl< T >::validParams(), MaterialFunctorConverterTempl< T >::validParams(), ParsedMaterialTempl< is_ad >::validParams(), ParsedMaterialHelper< is_ad >::validParams(), PiecewiseLinearInterpolationMaterial::validParams(), VectorFromComponentVariablesMaterialTempl< is_ad >::validParams(), AnnularMesh::validParams(), ConcentricCircleMesh::validParams(), FileMesh::validParams(), GeneratedMesh::validParams(), ImageMesh::validParams(), MeshGeneratorMesh::validParams(), PatternedMesh::validParams(), RinglebMesh::validParams(), SpiralAnnularMesh::validParams(), StitchedMesh::validParams(), TiledMesh::validParams(), CartesianGridDivision::validParams(), CylindricalGridDivision::validParams(), ExtraElementIntegerDivision::validParams(), FunctorBinnedValuesDivision::validParams(), MeshDivision::validParams(), NearestPositionsDivision::validParams(), NestedDivision::validParams(), SphericalGridDivision::validParams(), SubdomainsDivision::validParams(), AddMetaDataGenerator::validParams(), AdvancedExtruderGenerator::validParams(), AllSideSetsByNormalsGenerator::validParams(), AnnularMeshGenerator::validParams(), BlockDeletionGenerator::validParams(), BlockToMeshConverterGenerator::validParams(), BoundaryDeletionGenerator::validParams(), BoundingBoxNodeSetGenerator::validParams(), BreakBoundaryOnSubdomainGenerator::validParams(), BreakMeshByBlockGenerator::validParams(), BreakMeshByBlockGeneratorBase::validParams(), CartesianMeshGenerator::validParams(), CircularBoundaryCorrectionGenerator::validParams(), CombinerGenerator::validParams(), ConcentricCircleMeshGenerator::validParams(), DistributedRectilinearMeshGenerator::validParams(), ElementGenerator::validParams(), ElementSubdomainIDGenerator::validParams(), ExplodeMeshGenerator::validParams(), ExtraNodesetGenerator::validParams(), FileMeshGenerator::validParams(), FillBetweenCurvesGenerator::validParams(), FillBetweenPointVectorsGenerator::validParams(), FillBetweenSidesetsGenerator::validParams(), GeneratedMeshGenerator::validParams(), ImageMeshGenerator::validParams(), ImageSubdomainGenerator::validParams(), LowerDBlockFromSidesetGenerator::validParams(), MeshCollectionGenerator::validParams(), MeshDiagnosticsGenerator::validParams(), MeshExtruderGenerator::validParams(), MeshRepairGenerator::validParams(), MoveNodeGenerator::validParams(), NodeSetsFromSideSetsGenerator::validParams(), OrientedSubdomainBoundingBoxGenerator::validParams(), ParsedCurveGenerator::validParams(), ParsedElementDeletionGenerator::validParams(), ParsedGenerateSideset::validParams(), ParsedNodeTransformGenerator::validParams(), ParsedSubdomainMeshGenerator::validParams(), PatchMeshGenerator::validParams(), PatternedMeshGenerator::validParams(), PlaneDeletionGenerator::validParams(), PlaneIDMeshGenerator::validParams(), PolyLineMeshGenerator::validParams(), RefineBlockGenerator::validParams(), RefineSidesetGenerator::validParams(), RenameBlockGenerator::validParams(), RenameBoundaryGenerator::validParams(), RinglebMeshGenerator::validParams(), SideSetExtruderGenerator::validParams(), SideSetsAroundSubdomainGenerator::validParams(), SideSetsBetweenSubdomainsGenerator::validParams(), SideSetsFromBoundingBoxGenerator::validParams(), SideSetsFromNodeSetsGenerator::validParams(), SideSetsFromNormalsGenerator::validParams(), SideSetsFromPointsGenerator::validParams(), SmoothMeshGenerator::validParams(), SphereMeshGenerator::validParams(), SpiralAnnularMeshGenerator::validParams(), StackGenerator::validParams(), StitchedMeshGenerator::validParams(), SubdomainBoundingBoxGenerator::validParams(), SubdomainIDGenerator::validParams(), SymmetryTransformGenerator::validParams(), TiledMeshGenerator::validParams(), TransfiniteMeshGenerator::validParams(), TransformGenerator::validParams(), UniqueExtraIDMeshGenerator::validParams(), XYDelaunayGenerator::validParams(), XYMeshLineCutter::validParams(), CentroidMultiApp::validParams(), FullSolveMultiApp::validParams(), QuadraturePointMultiApp::validParams(), TransientMultiApp::validParams(), ConstantRate::validParams(), CoupledForceNodalKernel::validParams(), LowerBoundNodalKernel::validParams(), PenaltyDirichletNodalKernel::validParams(), ReactionNodalKernel::validParams(), TimeDerivativeNodalKernel::validParams(), UpperBoundNodalKernel::validParams(), UserForcingFunctionNodalKernel::validParams(), Checkpoint::validParams(), Console::validParams(), ControlOutput::validParams(), CSV::validParams(), DOFMapOutput::validParams(), Exodus::validParams(), FileOutput::validParams(), GMVOutput::validParams(), Gnuplot::validParams(), JSONOutput::validParams(), MaterialPropertyDebugOutput::validParams(), Nemesis::validParams(), PerfGraphOutput::validParams(), PNGOutput::validParams(), ReporterDebugOutput::validParams(), SolutionHistory::validParams(), Tecplot::validParams(), TopResidualDebugOutput::validParams(), VariableResidualNormsDebugOutput::validParams(), VTKOutput::validParams(), XDA::validParams(), XMLOutput::validParams(), BlockWeightedPartitioner::validParams(), GridPartitioner::validParams(), LibmeshPartitioner::validParams(), PetscExternalPartitioner::validParams(), RandomPartitioner::validParams(), SingleRankPartitioner::validParams(), ElementCentroidPositions::validParams(), ElementGroupCentroidPositions::validParams(), FilePositions::validParams(), FunctorPositions::validParams(), InputPositions::validParams(), MultiAppPositions::validParams(), ReporterPositions::validParams(), AreaPostprocessor::validParams(), AverageElementSize::validParams(), AverageNodalVariableValue::validParams(), AxisymmetricCenterlineAverageValue::validParams(), ChangeOverFixedPointPostprocessor::validParams(), ChangeOverTimePostprocessor::validParams(), ConstantPostprocessor::validParams(), CumulativeValuePostprocessor::validParams(), DifferencePostprocessor::validParams(), ElementalVariableValue::validParams(), ElementArrayL2Norm::validParams(), ElementAverageMaterialPropertyTempl< is_ad >::validParams(), ElementAverageSecondTimeDerivative::validParams(), ElementAverageTimeDerivative::validParams(), ElementAverageValue::validParams(), ElementExtremeFunctorValueTempl< is_ad >::validParams(), ElementExtremeMaterialPropertyTempl< is_ad >::validParams(), ElementExtremeValue::validParams(), ElementH1Error::validParams(), ElementH1SemiError::validParams(), ElementIntegralArrayVariablePostprocessor::validParams(), ElementIntegralFunctorPostprocessorTempl< is_ad >::validParams(), ElementIntegralMaterialPropertyTempl< is_ad >::validParams(), ElementIntegralVariablePostprocessor::validParams(), ElementL1Error::validParams(), ElementL2Difference::validParams(), ElementL2Error::validParams(), ElementL2FunctorErrorTempl< is_ad >::validParams(), ElementSidesL2Norm::validParams(), ElementVectorL2Error::validParams(), ElementW1pError::validParams(), EmptyPostprocessor::validParams(), FindValueOnLine::validParams(), FunctionElementAverage::validParams(), FunctionElementIntegral::validParams(), FunctionSideAverage::validParams(), FunctionSideIntegral::validParams(), FunctionValuePostprocessor::validParams(), GreaterThanLessThanPostprocessor::validParams(), InterfaceAverageVariableValuePostprocessor::validParams(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::validParams(), InterfaceIntegralPostprocessor::validParams(), InterfaceIntegralVariableValuePostprocessor::validParams(), InterfacePostprocessor::validParams(), InternalSideIntegralVariablePostprocessor::validParams(), LinearCombinationPostprocessor::validParams(), MemoryUsage::validParams(), NearestNodeNumber::validParams(), NodalExtremeValue::validParams(), NodalL2Error::validParams(), NodalL2Norm::validParams(), NodalMaxValue::validParams(), NodalMaxValueId::validParams(), NodalSum::validParams(), NodalVariableValue::validParams(), NumDOFs::validParams(), NumElems::validParams(), NumFailedTimeSteps::validParams(), NumFixedPointIterations::validParams(), NumLinearIterations::validParams(), NumMeshDivisions::validParams(), NumNodes::validParams(), NumNonlinearIterations::validParams(), NumPositions::validParams(), NumRelationshipManagers::validParams(), NumResidualEvaluations::validParams(), NumVars::validParams(), ParsedPostprocessor::validParams(), PercentChangePostprocessor::validParams(), PerfGraphData::validParams(), PointValue::validParams(), PostprocessorComparison::validParams(), PseudoTimestep::validParams(), Receiver::validParams(), RelativeDifferencePostprocessor::validParams(), RelativeSolutionDifferenceNorm::validParams(), Residual::validParams(), ScalarL2Error::validParams(), ScalarVariable::validParams(), ScalePostprocessor::validParams(), SideAdvectiveFluxIntegralTempl< is_ad >::validParams(), SideAverageMaterialPropertyTempl< is_ad >::validParams(), SideAverageValue::validParams(), SideExtremeValue::validParams(), SideIntegralFunctorPostprocessorTempl< is_ad >::validParams(), SideIntegralMaterialPropertyTempl< is_ad >::validParams(), SideIntegralVariablePostprocessor::validParams(), TagVectorSum::validParams(), TimeExtremeValue::validParams(), TimeIntegratedPostprocessor::validParams(), TimePostprocessor::validParams(), TimestepSize::validParams(), VariableResidual::validParams(), VectorPostprocessorComparison::validParams(), VectorPostprocessorComponent::validParams(), VectorPostprocessorReductionValue::validParams(), VolumePostprocessor::validParams(), FieldSplitPreconditioner::validParams(), FiniteDifferencePreconditioner::validParams(), PhysicsBasedPreconditioner::validParams(), SingleMatrixPreconditioner::validParams(), VariableCondensationPreconditioner::validParams(), AdamsPredictor::validParams(), SimplePredictor::validParams(), DisplacedProblem::validParams(), DumpObjectsProblem::validParams(), EigenProblem::validParams(), ExternalProblem::validParams(), FEProblem::validParams(), ReferenceResidualProblem::validParams(), AccumulateReporter::validParams(), ConstantReporter::validParams(), ElementVariableStatistics::validParams(), ExtraIDIntegralReporter::validParams(), IterationInfo::validParams(), MeshInfo::validParams(), NodalVariableStatistics::validParams(), PerfGraphReporter::validParams(), RestartableDataReporter::validParams(), SolutionInvalidityReporter::validParams(), Sampler::validParams(), ADScalarTimeDerivative::validParams(), AverageValueConstraint::validParams(), CoupledODETimeDerivative::validParams(), NodalEqualValueConstraint::validParams(), NullScalarKernel::validParams(), ODETimeDerivative::validParams(), ParsedODEKernel::validParams(), Split::validParams(), ActuallyExplicitEuler::validParams(), AStableDirk4::validParams(), BDF2::validParams(), CentralDifference::validParams(), CrankNicolson::validParams(), ExplicitEuler::validParams(), ExplicitMidpoint::validParams(), ExplicitSSPRungeKutta::validParams(), ExplicitTVDRK2::validParams(), Heun::validParams(), ImplicitEuler::validParams(), ImplicitMidpoint::validParams(), LStableDirk2::validParams(), LStableDirk3::validParams(), LStableDirk4::validParams(), NewmarkBeta::validParams(), Ralston::validParams(), CSVFileTimes::validParams(), ExodusFileTimes::validParams(), FunctorTimes::validParams(), InputTimes::validParams(), ReporterTimes::validParams(), SimulationTimes::validParams(), TimeIntervalTimes::validParams(), AB2PredictorCorrector::validParams(), CompositionDT::validParams(), ConstantDT::validParams(), CSVTimeSequenceStepper::validParams(), ExodusTimeSequenceStepper::validParams(), FunctionDT::validParams(), IterationAdaptiveDT::validParams(), LogConstantDT::validParams(), PostprocessorDT::validParams(), SolutionTimeAdaptiveDT::validParams(), TestSourceStepper::validParams(), TimeSequenceFromTimes::validParams(), TimeSequenceStepper::validParams(), MultiAppCloneReporterTransfer::validParams(), MultiAppCopyTransfer::validParams(), MultiAppDofCopyTransfer::validParams(), MultiAppGeneralFieldNearestLocationTransfer::validParams(), MultiAppGeneralFieldShapeEvaluationTransfer::validParams(), MultiAppGeneralFieldUserObjectTransfer::validParams(), MultiAppGeometricInterpolationTransfer::validParams(), MultiAppNearestNodeTransfer::validParams(), MultiAppPostprocessorInterpolationTransfer::validParams(), MultiAppPostprocessorToAuxScalarTransfer::validParams(), MultiAppPostprocessorTransfer::validParams(), MultiAppProjectionTransfer::validParams(), MultiAppReporterTransfer::validParams(), MultiAppScalarToAuxScalarTransfer::validParams(), MultiAppShapeEvaluationTransfer::validParams(), MultiAppUserObjectTransfer::validParams(), MultiAppVariableValueSamplePostprocessorTransfer::validParams(), MultiAppVariableValueSampleTransfer::validParams(), MultiAppVectorPostprocessorTransfer::validParams(), ActivateElementsUserObjectBase::validParams(), ElementIntegralUserObject::validParams(), ElementIntegralVariableUserObject::validParams(), ElementQualityChecker::validParams(), ElementSubdomainModifier::validParams(), ElemSideNeighborLayersGeomTester::validParams(), ElemSideNeighborLayersTester::validParams(), FunctionElementIntegralUserObject::validParams(), FunctionLayeredIntegral::validParams(), GeometryBase::validParams(), GeometrySphere::validParams(), GhostingUserObject::validParams(), InterfaceQpMaterialPropertyBaseUserObject< T >::validParams(), InterfaceQpMaterialPropertyRealUO::validParams(), InterfaceQpUserObjectBase::validParams(), InterfaceQpValueUserObject::validParams(), InterfaceUserObject::validParams(), InterfaceUserObjectBase::validParams(), InterfaceValueUserObject::validParams(), JSONFileReader::validParams(), LayeredAverage::validParams(), LayeredExtremumMaterialProperty::validParams(), LayeredIntegral::validParams(), LayeredSideAverage::validParams(), LayeredSideAverageFunctor::validParams(), LayeredSideDiffusiveFluxAverage::validParams(), LayeredSideIntegral::validParams(), LayeredSideIntegralFunctor::validParams(), MessageFromInput::validParams(), NearestNodeNumberUO::validParams(), NearestPointAverage::validParams(), NearestPointIntegralVariablePostprocessor::validParams(), NearestPointLayeredAverage::validParams(), NearestPointLayeredIntegral::validParams(), NearestPointLayeredSideAverage::validParams(), NearestPointLayeredSideAverageFunctor::validParams(), NearestPointLayeredSideDiffusiveFluxAverage::validParams(), NearestPointLayeredSideIntegral::validParams(), NearestPointLayeredSideIntegralFunctor::validParams(), NearestRadiusLayeredAverage::validParams(), NodalNormalsCorner::validParams(), NodalNormalsEvaluator::validParams(), NodalNormalsPreprocessor::validParams(), NodalPatchRecoveryMaterialProperty::validParams(), PointwiseRenormalizeVector::validParams(), PostprocessorSpatialUserObject::validParams(), ProjectedStatefulMaterialNodalPatchRecoveryBase::validParams(), PropertyReadFile::validParams(), RadialAverage::validParams(), SolutionUserObject::validParams(), Terminator::validParams(), VerifyElementUniqueID::validParams(), VerifyNodalUniqueID::validParams(), MooseVariableBase::validParams(), ConstantVectorPostprocessor::validParams(), CSVReader::validParams(), CylindricalAverage::validParams(), Eigenvalues::validParams(), ElementsAlongLine::validParams(), ElementsAlongPlane::validParams(), ElementValueSampler::validParams(), ElementVariablesDifferenceMax::validParams(), ExtraIDIntegralVectorPostprocessor::validParams(), HistogramVectorPostprocessor::validParams(), IntersectionPointsAlongLine::validParams(), LeastSquaresFit::validParams(), LeastSquaresFitHistory::validParams(), LineFunctionSampler::validParams(), LineMaterialRealSampler::validParams(), LineValueSampler::validParams(), MaterialVectorPostprocessor::validParams(), MeshDivisionFunctorReductionVectorPostprocessor::validParams(), NodalValueSampler::validParams(), PointValueSampler::validParams(), PositionsFunctorValueSampler::validParams(), SidesetInfoVectorPostprocessor::validParams(), SideValueSampler::validParams(), SpatialUserObjectVectorPostprocessor::validParams(), SphericalAverage::validParams(), VariableValueVolumeHistogram::validParams(), VectorMemoryUsage::validParams(), VectorOfPostprocessors::validParams(), WorkBalance::validParams(), OutflowBC::validParams(), DGCoupledAdvection::validParams(), DGFunctionTemperatureAdvection::validParams(), DGTemperatureAdvection::validParams(), InterTemperatureAdvection::validParams(), and ChannelGradient::validParams().
addCommandLineParam() [1/2]
template<typename T > void InputParameters::addCommandLineParam (const std::string & name, const std::string & syntax, const std::string & doc_string)
Definition at line 1552 of file InputParameters.h.
{
  addParam<T>(name, doc_string);
  MooseUtils::tokenize(syntax, _params[name]._cli_flag_names, 1, " \t\n\v\f\r");
}
Referenced by MooseApp::addAppParam(), and MooseApp::validParams().
addCommandLineParam() [2/2]
template<typename T > void InputParameters::addCommandLineParam (const std::string & name, const std::string & syntax, const T & value, const std::string & doc_string)
Definition at line 1562 of file InputParameters.h.
{
  addParam<T>(name, value, doc_string);
  MooseUtils::tokenize(syntax, _params[name]._cli_flag_names, 1, " \t\n\v\f\r");
}
addCommandLineParamHelper() [1/2]
template<typename T > void InputParameters::addCommandLineParamHelper (const std::string & name, const std::string & syntax, const std::string & doc_string, std::vector< T > *) private
addCommandLineParamHelper() [2/2]
template<typename T > void InputParameters::addCommandLineParamHelper (const std::string & name, const std::string & syntax, const std::string & doc_string, T *) private
Helper that uses overloading to distinguish adding commandline parameters of a scalar and a vector kind.
Vector parameters are options that may appear multiple times on the command line (like -i).
addCoupledVar() [1/3]
void InputParameters::addCoupledVar (const std::string & name, const Real value, const std::string & doc_string)
This method adds a coupled variable name pair.
The parser will look for variable name pair in the input file and can return a reference to the storage location for the coupled variable if found
Also - you can provide a default value for this variable in the case that an actual variable is not provided.
Definition at line 220 of file InputParameters.C.
{
  addParam<std::vector<VariableName>>(name, doc_string);
  _coupled_vars.insert(name);
  auto & metadata = _params[name];
  metadata._coupled_default.assign(1, value);
  metadata._have_coupled_default = true;
  // Set the doc string for any associated deprecated coupled var
  setDeprecatedVarDocString(name, doc_string);
}
addCoupledVar() [2/3]
void InputParameters::addCoupledVar (const std::string & name, const std::string & doc_string)
This method adds a coupled variable name pair.
The parser will look for variable name pair in the input file and can return a reference to the storage location for the coupled variable if found
Definition at line 249 of file InputParameters.C.
{
  addParam<std::vector<VariableName>>(name, doc_string);
  _coupled_vars.insert(name);
  // Set the doc string for any associated deprecated coupled var
  setDeprecatedVarDocString(name, doc_string);
}
Referenced by applyCoupledVar(), transferParam(), BolsigValueScalar::validParams(), DataRead::validParams(), EEDFRateCoefficientScalar::validParams(), ElectronMobility::validParams(), MoleFraction::validParams(), ParsedAuxScalar::validParams(), ParsedScalarRateCoefficient::validParams(), ReactionRateEEDFTownsendLogTempl< is_ad >::validParams(), ReactionRateFirstOrder::validParams(), ReactionRateFirstOrderLog::validParams(), ReactionRateOneBodyScalar::validParams(), ReactionRateSecondOrder::validParams(), ReactionRateSecondOrderLog::validParams(), ReactionRateThirdOrder::validParams(), ReactionRateThirdOrderLog::validParams(), ReactionRateThreeBodyScalar::validParams(), ReactionRateTwoBodyScalar::validParams(), ReducedField::validParams(), ReducedFieldScalar::validParams(), ScalarLinearInterpolation::validParams(), ScalarSplineInterpolation::validParams(), SuperelasticRateCoefficientScalar::validParams(), VariableSum::validParams(), VariableSumLog::validParams(), ADEEDFEnergyTownsendLog::validParams(), EEDFEnergyLog::validParams(), EEDFEnergyTownsendLog::validParams(), EEDFReactionLog::validParams(), EEDFReactionTownsendLog::validParams(), ADZapdosEEDFRateConstant::validParams(), EEDFRateConstant::validParams(), EEDFRateConstantTownsend::validParams(), ElectricField::validParams(), HeatCapacityRatio::validParams(), SpeciesSum::validParams(), SuperelasticReactionRate::validParams(), ZapdosEEDFRateConstant::validParams(), ElectricFieldCalculator::validParams(), EnergyTermScalar::validParams(), Product1BodyScalar::validParams(), Product1BodyScalarLog::validParams(), Product2BodyScalar::validParams(), Product2BodyScalarLog::validParams(), Product3BodyScalar::validParams(), Product3BodyScalarLog::validParams(), Reactant1BodyScalar::validParams(), Reactant1BodyScalarLog::validParams(), Reactant2BodyScalar::validParams(), Reactant2BodyScalarLog::validParams(), Reactant3BodyScalar::validParams(), Reactant3BodyScalarLog::validParams(), BoltzmannSolverScalar::validParams(), RateCoefficientProvider::validParams(), ProcRateForRateCoeffTempl< is_ad >::validParams(), ProcRateForRateCoeffThreeBodyTempl< is_ad >::validParams(), DriftDiffusionDoNothingBC::validParams(), DriftDiffusion::validParams(), ElectronEnergyTermRate::validParams(), ElectronsFromIonization::validParams(), ReactionSecondOrderLogForShootMethod::validParams(), ReactionThirdOrderLogForShootMethod::validParams(), Gas::validParams(), GasBase::validParams(), GasElectronMoments::validParams(), Water::validParams(), ArrayParsedAux::validParams(), BuildArrayVariableAux::validParams(), ParsedAux::validParams(), ParsedVectorAux::validParams(), PenetrationAux::validParams(), QuotientAux::validParams(), QuotientScalarAux::validParams(), VectorMagnitudeAux::validParams(), ArrayHFEMDirichletBC::validParams(), BoundaryCondition::validParams(), CoupledVarNeumannBC::validParams(), HFEMDirichletBC::validParams(), NodalNormalBC::validParams(), ADMortarScalarBase::validParams(), MortarScalarBase::validParams(), NodeFaceConstraint::validParams(), FVBoundaryCondition::validParams(), FVInterfaceKernel::validParams(), ADKernelScalarBase::validParams(), ADKernelSUPGTempl< T >::validParams(), ADMatDiffusionBase< T >::validParams(), ADMatReaction::validParams(), FunctionDiffusion::validParams(), KernelScalarBase::validParams(), MatDiffusionBase< T >::validParams(), MatReaction::validParams(), CoupledValueFunctionMaterialTempl< is_ad >::validParams(), DerivativeSumMaterialTempl< is_ad >::validParams(), ParsedMaterialBase::validParams(), VectorFromComponentVariablesMaterialTempl< is_ad >::validParams(), ElementExtremeValue::validParams(), ElementVectorL2Error::validParams(), FindValueOnLine::validParams(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::validParams(), InterfaceIntegralVariableValuePostprocessor::validParams(), NodalExtremeValue::validParams(), SideAdvectiveFluxIntegralTempl< is_ad >::validParams(), SideExtremeValue::validParams(), ParsedODEKernel::validParams(), InterfaceQpValueUserObject::validParams(), PointwiseRenormalizeVector::validParams(), SpatialAverageBase::validParams(), VariableValueVolumeHistogram::validParams(), DGCoupledAdvection::validParams(), and PotentialAdvection::validParams().
addCoupledVar() [3/3]
void InputParameters::addCoupledVar (const std::string & name, const std::vector< Real > & value, const std::string & doc_string)
This method adds a coupled variable name pair.
The parser will look for variable name pair in the input file and can return a reference to the storage location for the coupled variable if found
Also - you can provide a vector of values for this variable in the case that an actual variable is not provided.
Definition at line 233 of file InputParameters.C.
{
  // std::vector<VariableName>(1, Moose::stringify(value)),
  addParam<std::vector<VariableName>>(name, doc_string);
  _coupled_vars.insert(name);
  auto & metadata = _params[name];
  metadata._coupled_default = value;
  metadata._have_coupled_default = true;
  // Set the doc string for any associated deprecated coupled var
  setDeprecatedVarDocString(name, doc_string);
}
addCoupledVarWithAutoBuild()
void InputParameters::addCoupledVarWithAutoBuild (const std::string & name, const std::string & base_name, const std::string & num_name, const std::string & doc_string)
These methods add a coupled variable name pair.
The parser will look for variable name pair in the input file and can return a reference to the storage location for the coupled variable if found.
This version of the method will build a vector if the given the base_name and num_name parameters exist in the input file: e.g. [./foo] ... some_base = base_ some_num = 5 [../]
The coupling parameter will be passed this vector: "base_0 base_1 base_2 base_3 base_4"
Definition at line 287 of file InputParameters.C.
{
  addParam<std::vector<VariableName>>(name, doc_string);
  _coupled_vars.insert(name);
  _params[name]._autobuild_vecs = std::make_pair(base_name, num_name);
  // Additionally there are two more parameters that need to be added:
  addParam<std::string>(base_name, doc_string + " (base_name)");
  addParam<unsigned int>(num_name, doc_string + " (num_name)");
}
Referenced by addRequiredCoupledVarWithAutoBuild().
addCustomTypeParam() [1/2]
template<typename T > void InputParameters::addCustomTypeParam (const std::string & name, const std::string & custom_type, const std::string & doc_string)
Definition at line 1492 of file InputParameters.h.
{
  addParam<T>(name, doc_string);
  _params[name]._custom_type = custom_type;
}
addCustomTypeParam() [2/2]
template<typename T > void InputParameters::addCustomTypeParam (const std::string & name, const T & value, const std::string & custom_type, const std::string & doc_string)
Definition at line 1481 of file InputParameters.h.
{
  addParam<T>(name, value, doc_string);
  _params[name]._custom_type = custom_type;
}
Referenced by ParsedVectorAux::validParams(), MooseParsedFunction::validParams(), and ParsedMaterialBase::validParams().
addDeprecatedCoupledVar()
void InputParameters::addDeprecatedCoupledVar (const std::string & old_name, const std::string & new_name, const std::string & removal_date = "")
This method adds a deprecated coupled variable name pair.
The parser will look for variable name pair in the input file and can return a reference to the storage location for the coupled variable if found. The doc string for the deprecated variable will be constructed from the doc string for the new variable. A deprecation message will also be automatically generated
Definition at line 259 of file InputParameters.C.
{
  mooseDeprecated("Please use 'deprecateCoupledVar'");
  _show_deprecated_message = false;
  // Set the doc string if we are adding the deprecated var after the new var has already been added
  auto params_it = _params.find(new_name);
  std::string doc_string;
  if (params_it != _params.end())
    doc_string = params_it->second._doc_string;
  addParam<std::vector<VariableName>>(old_name, doc_string);
  _coupled_vars.insert(old_name);
  _new_to_deprecated_coupled_vars.emplace(new_name, old_name);
  std::string deprecation_message =
      "The coupled variable parameter '" + old_name + "' has been deprecated";
  if (!removal_date.empty())
    deprecation_message += " and will be removed " + removal_date;
  deprecation_message += ". Please use the '" + new_name + "' coupled variable parameter instead.";
  _params[old_name]._deprecation_message = deprecation_message;
  _show_deprecated_message = true;
}
addDeprecatedCustomTypeParam()
template<typename T > void InputParameters::addDeprecatedCustomTypeParam (const std::string & name, const std::string & custom_type, const std::string & doc_string, const std::string & deprecation_msg)
Definition at line 1502 of file InputParameters.h.
{
  _show_deprecated_message = false;
  addParam<T>(name, doc_string);
  auto & metadata = _params[name];
  metadata._custom_type = custom_type;
  metadata._deprecation_message = deprecation_message;
  _show_deprecated_message = true;
}
Referenced by MooseParsedFunction::validParams(), and ParsedMaterialBase::validParams().
addDeprecatedParam() [1/6]
template<> void InputParameters::addDeprecatedParam (const std::string & , const std::string & , const std::string &)
Definition at line 1069 of file InputParameters.C.
{
  mooseError("You must supply a MooseEnum object and the deprecation string when using "
             "addDeprecatedParam, even if the parameter is not required!");
}
addDeprecatedParam() [2/6]
template<> void InputParameters::addDeprecatedParam (const std::string & , const std::string & , const std::string &)
Definition at line 1079 of file InputParameters.C.
{
  mooseError("You must supply a MultiMooseEnum object and the deprecation string when using "
             "addDeprecatedParam, even if the parameter is not required!");
}
addDeprecatedParam() [3/6]
template<typename T > void InputParameters::addDeprecatedParam (const std::string & name, const std::string & doc_string, const std::string & deprecation_message)
Definition at line 1657 of file InputParameters.h.
{
  _show_deprecated_message = false;
  addParam<T>(name, doc_string);
  _params[name]._deprecation_message = deprecation_message;
  _show_deprecated_message = true;
}
addDeprecatedParam() [4/6]
template<> void InputParameters::addDeprecatedParam (const std::string & name, const std::string & doc_string, const std::string & deprecation_message)
addDeprecatedParam() [5/6]
template<> void InputParameters::addDeprecatedParam (const std::string & name, const std::string & doc_string, const std::string & deprecation_message)
addDeprecatedParam() [6/6]
template<typename T > void InputParameters::addDeprecatedParam (const std::string & name, const T & value, const std::string & doc_string, const std::string & deprecation_message)
Parameters
name The name of the parameter
value The default value of this parameter if it requires one
doc_string Documentation. This will be shown for –help
deprecation_message The message that will will print about why this param was deprecated. It might mention the "new way".
Definition at line 1643 of file InputParameters.h.
{
  _show_deprecated_message = false;
  addParam<T>(name, value, doc_string);
  _params[name]._deprecation_message = deprecation_message;
  _show_deprecated_message = true;
}
Referenced by AdaptivityAction::validParams(), CommonOutputAction::validParams(), SetupDebugAction::validParams(), VectorFunctionDirichletBC::validParams(), Executioner::validParams(), FixedPointSolve::validParams(), PicardSolve::validParams(), Transient::validParams(), MooseParsedFunctionBase::validParams(), MooseParsedGradFunction::validParams(), MooseParsedVectorFunction::validParams(), MatDiffusionBase< T >::validParams(), AnnularMesh::validParams(), AnnularMeshGenerator::validParams(), BlockDeletionGenerator::validParams(), ParsedGenerateSideset::validParams(), ParsedSubdomainMeshGenerator::validParams(), RenameBlockGenerator::validParams(), RenameBoundaryGenerator::validParams(), SideSetsBetweenSubdomainsGenerator::validParams(), SideSetsFromBoundingBoxGenerator::validParams(), MultiApp::validParams(), Console::validParams(), Exodus::validParams(), Output::validParams(), OversampleOutput::validParams(), FEProblemBase::validParams(), PostprocessorDT::validParams(), MultiAppTransfer::validParams(), MultiAppUserObjectTransfer::validParams(), Transfer::validParams(), PropertyReadFile::validParams(), and DerivativeKernelInterface< T >::validParams().
addParam() [1/7]
template<> void InputParameters::addParam (const std::string & , const std::string &)
addParam() [2/7]
template<> void InputParameters::addParam (const std::string & , const std::string &)
addParam() [3/7]
template<> void InputParameters::addParam (const std::string & , const std::string &)
Definition at line 1026 of file InputParameters.C.
{
  mooseError("You must supply a MooseEnum object when using addParam, even if the parameter is not "
             "required!");
}
addParam() [4/7]
template<> void InputParameters::addParam (const std::string & , const std::string &)
Definition at line 1035 of file InputParameters.C.
{
  mooseError("You must supply a MultiMooseEnum object when using addParam, even if the parameter "
             "is not required!");
}
addParam() [5/7]
template<typename T , typename S > void InputParameters::addParam (const std::string & name, const S & value, const std::string & doc_string)
These methods add an option parameter and a documentation string to the InputParameters object.
The first version of this function takes a default value which is used if the parameter is not found in the input file. The second method will leave the parameter uninitialized but can be checked with "isParamValid" before use.
Definition at line 1402 of file InputParameters.h.
{
  checkParamName(name);
  checkConsistentType<T>(name);
  T & l_value = InputParameters::set<T>(name);
  auto & metadata = _params[name];
  metadata._doc_string = doc_string;
  // Set the parameter now
  setParamHelper(name, l_value, value);
  /* Indicate the default value, as set via addParam, is being used. The parameter is removed from
     the list whenever
     it changes, see set_attributes */
  metadata._set_by_add_param = true;
}
Referenced by ConstantReporter::addReporterTypeParams(), MultiAppTransfer::addSkipCoordCollapsingParam(), AdvancedOutput::addValidParams(), Moose::commonAdaptivityParams(), Moose::PetscSupport::getPetscValidParams(), Moose::SlepcSupport::getSlepcEigenProblemValidParams(), AddGeneralReactions::validParams(), AddReactions::validParams(), AddScalarReactions::validParams(), AddSpecies::validParams(), AddZapdosReactions::validParams(), ChemicalReactions::validParams(), ChemicalReactionsBase::validParams(), AuxInitialConditionScalar::validParams(), BolsigValueScalar::validParams(), DataRead::validParams(), EEDFRateCoefficientScalar::validParams(), ParsedAuxScalar::validParams(), ParsedScalarRateCoefficient::validParams(), ReactionRateFirstOrder::validParams(), ReactionRateFirstOrderLog::validParams(), ReactionRateSecondOrder::validParams(), ReactionRateSecondOrderLog::validParams(), ReactionRateThirdOrder::validParams(), ReactionRateThirdOrderLog::validParams(), ScalarLinearInterpolation::validParams(), ScalarSplineInterpolation::validParams(), SuperelasticRateCoefficientScalar::validParams(), ADEEDFElasticLog::validParams(), ADEEDFElasticTownsendLog::validParams(), ADEEDFEnergyLog::validParams(), ADEEDFEnergyTownsendLog::validParams(), ADEEDFReactionLog::validParams(), ADEEDFReactionTownsendLog::validParams(), EEDFElasticLog::validParams(), EEDFElasticTownsendLog::validParams(), EEDFEnergyLog::validParams(), EEDFEnergyTownsendLog::validParams(), EEDFReactionLog::validParams(), EEDFReactionTownsendLog::validParams(), ReactionFirstOrder::validParams(), ReactionFirstOrderEnergy::validParams(), ReactionFirstOrderEnergyLog::validParams(), ReactionFirstOrderLog::validParams(), ReactionSecondOrder::validParams(), ReactionSecondOrderEnergy::validParams(), ReactionSecondOrderEnergyLog::validParams(), ReactionSecondOrderLogTempl< is_ad >::validParams(), ReactionThirdOrder::validParams(), ReactionThirdOrderEnergy::validParams(), ReactionThirdOrderEnergyLog::validParams(), ReactionThirdOrderLogTempl< is_ad >::validParams(), ADEEDFRateConstantTownsend::validParams(), ADZapdosEEDFRateConstant::validParams(), EEDFRateConstant::validParams(), EEDFRateConstantTownsend::validParams(), ElectricField::validParams(), GenericRateConstantTempl< is_ad >::validParams(), InterpolatedCoefficientLinear::validParams(), InterpolatedCoefficientSpline::validParams(), ZapdosEEDFRateConstant::validParams(), ElectricFieldCalculator::validParams(), EnergyTermScalar::validParams(), ODETimeDerivativeLog::validParams(), ParsedScalarReaction::validParams(), Product1BodyScalar::validParams(), Product1BodyScalarLog::validParams(), Product2BodyScalar::validParams(), Product2BodyScalarLog::validParams(), Product3BodyScalar::validParams(), Product3BodyScalarLog::validParams(), Reactant1BodyScalar::validParams(), Reactant1BodyScalarLog::validParams(), Reactant2BodyScalar::validParams(), Reactant2BodyScalarLog::validParams(), Reactant3BodyScalar::validParams(), Reactant3BodyScalarLog::validParams(), BoltzmannSolverScalar::validParams(), RateCoefficientProvider::validParams(), ValueProvider::validParams(), AddDriftDiffusionAction::validParams(), AddPeriodicControllers::validParams(), AddPeriodicRelativeNodalDifference::validParams(), CurrentTempl< is_ad >::validParams(), DensityNormalization::validParams(), DriftDiffusionFluxAux::validParams(), Position::validParams(), PowerDepTempl< is_ad >::validParams(), TM0CylindricalErAux::validParams(), TM0CylindricalEzAux::validParams(), CircuitDirichletPotential::validParams(), DriftDiffusionDoNothingBC::validParams(), EconomouDielectricBC::validParams(), ElectronTemperatureDirichletBC::validParams(), FieldEmissionBC::validParams(), HagelaarIonDiffusionBC::validParams(), NeumannCircuitVoltageNew::validParams(), PenaltyCircuitPotential::validParams(), PotentialDriftOutflowBC::validParams(), SakiyamaEnergySecondaryElectronBC::validParams(), SakiyamaSecondaryElectronBC::validParams(), SchottkyEmissionBC::validParams(), SecondaryElectronBC::validParams(), SecondaryElectronEnergyBC::validParams(), TM0AntennaVertBC::validParams(), ArbitrarilyTiedValueConstraint::validParams(), PotentialSurfaceCharge::validParams(), DriftDiffusion::validParams(), EEDFReactionLogForShootMethod::validParams(), EFieldArtDiff::validParams(), ElectronEnergyTermRate::validParams(), ElectronsFromIonization::validParams(), ElectronTimeDerivative::validParams(), ReactionSecondOrderLogForShootMethod::validParams(), ReactionThirdOrderLogForShootMethod::validParams(), ShootMethodLog::validParams(), ADGasElectronMoments::validParams(), ADSurfaceCharge::validParams(), Gas::validParams(), GasBase::validParams(), GasElectronMoments::validParams(), HeavySpeciesTempl< is_ad >::validParams(), Water::validParams(), SideTotFluxIntegral::validParams(), Action::validParams(), AdaptivityAction::validParams(), AddFieldSplitAction::validParams(), AddNodalNormalsAction::validParams(), AddPeriodicBCAction::validParams(), CommonOutputAction::validParams(), CopyNodalVarsAction::validParams(), CreateDisplacedProblemAction::validParams(), CreateExecutionerAction::validParams(), CreateProblemAction::validParams(), DeprecatedBlockAction::validParams(), DisplayGhostingAction::validParams(), DynamicObjectRegistrationAction::validParams(), MaterialDerivativeTestAction::validParams(), MooseObjectAction::validParams(), ProjectedStatefulMaterialStorageAction::validParams(), ReadExecutorParamsAction::validParams(), SetAdaptivityOptionsAction::validParams(), SetupDebugAction::validParams(), SetupMeshAction::validParams(), SetupQuadratureAction::validParams(), SetupResidualDebugAction::validParams(), AdvectiveFluxAux::validParams(), ArrayParsedAux::validParams(), ArrayVariableComponent::validParams(), ArrayVarReductionAux::validParams(), AuxKernelTempl< ComputeValueType >::validParams(), AuxScalarKernel::validParams(), BoundsAuxBase::validParams(), ConstantAux::validParams(), DivergenceAuxTempl< is_ad >::validParams(), ElementIntegerAux::validParams(), ElementUOAux::validParams(), FunctorAux::validParams(), FunctorElementalGradientAuxTempl< is_ad >::validParams(), FunctorVectorElementalAuxTempl< is_ad >::validParams(), GapValueAux::validParams(), GhostingAux::validParams(), InterfaceValueUserObjectAux::validParams(), MaterialAuxBaseTempl< T, is_ad, RT >::validParams(), MaterialRealDenseMatrixAux::validParams(), MaterialRealTensorValueAux::validParams(), MaterialRealVectorValueAuxTempl< is_ad >::validParams(), MaterialStdVectorAuxTempl< is_ad >::validParams(), MaterialStdVectorAuxBaseTempl< T, is_ad >::validParams(), MaterialStdVectorRealGradientAux::validParams(), MeshDivisionAux::validParams(), MortarNodalAuxKernelTempl< ComputeValueType >::validParams(), NodalPatchRecovery::validParams(), NormalizationAux::validParams(), ParsedAux::validParams(), ParsedVectorAux::validParams(), PenetrationAux::validParams(), ProjectionAux::validParams(), ScalarTagMatrixAux::validParams(), ScalarTagVectorAux::validParams(), SecondTimeDerivativeAux::validParams(), SolutionAux::validParams(), SolutionScalarAux::validParams(), TagAuxBase< T >::validParams(), TagMatrixAux::validParams(), TimeDerivativeAux::validParams(), VariableGradientComponent::validParams(), VariableTimeIntegrationAux::validParams(), VectorPostprocessorVisualizationAux::validParams(), VectorVariableComponentAux::validParams(), MooseApp::validParams(), MooseObject::validParams(), ADConservativeAdvectionBC::validParams(), ADDirichletBCBase::validParams(), ADDirichletBCBaseTempl< T >::validParams(), ADFunctionDirichletBC::validParams(), ADPenaltyDirichletBC::validParams(), ADRobinBC::validParams(), ADVectorFunctionDirichletBC::validParams(), ADVectorFunctionNeumannBC::validParams(), ADVectorRobinBC::validParams(), ArrayHFEMDirichletBC::validParams(), ArrayNeumannBC::validParams(), ArrayPenaltyDirichletBC::validParams(), ArrayVacuumBC::validParams(), BoundaryCondition::validParams(), CoupledVarNeumannBC::validParams(), DGFunctionDiffusionDirichletBC::validParams(), DirichletBCBase::validParams(), FunctionGradientNeumannBC::validParams(), FunctorDirichletBC::validParams(), FunctorNeumannBC::validParams(), HFEMDirichletBC::validParams(), IntegratedBCBase::validParams(), MatchedValueBCTempl< is_ad >::validParams(), NeumannBCTempl< is_ad >::validParams(), NodalBCBase::validParams(), PenaltyDirichletBC::validParams(), PostprocessorNeumannBC::validParams(), SinNeumannBC::validParams(), VacuumBC::validParams(), VectorCurlPenaltyDirichletBC::validParams(), VectorDivPenaltyDirichletBC::validParams(), VectorFunctionDirichletBC::validParams(), VectorNeumannBC::validParams(), VectorPenaltyDirichletBC::validParams(), ADMortarScalarBase::validParams(), ADPenaltyPeriodicSegmentalConstraint::validParams(), Constraint::validParams(), CoupledTiedValueConstraint::validParams(), ElemElemConstraint::validParams(), EqualValueBoundaryConstraint::validParams(), EqualValueConstraint::validParams(), EqualValueEmbeddedConstraint::validParams(), LinearNodalConstraint::validParams(), MortarScalarBase::validParams(), NodalConstraint::validParams(), NodeFaceConstraint::validParams(), PenaltyPeriodicSegmentalConstraint::validParams(), TiedValueConstraint::validParams(), ConditionalEnableControl::validParams(), Control::validParams(), PIDTransientControl::validParams(), TimePeriod::validParams(), BoundingValueElementDamper::validParams(), BoundingValueNodalDamper::validParams(), Damper::validParams(), MaxIncrement::validParams(), ADDGAdvection::validParams(), ADDGDiffusion::validParams(), ArrayDGDiffusion::validParams(), DGDiffusion::validParams(), DGKernelBase::validParams(), DiracKernelBase::validParams(), ReporterPointSource::validParams(), EigenExecutionerBase::validParams(), Eigenvalue::validParams(), Executioner::validParams(), FEProblemSolve::validParams(), FixedPointSolve::validParams(), InversePowerMethod::validParams(), NonlinearEigen::validParams(), Steady::validParams(), Transient::validParams(), Executor::validParams(), Axisymmetric2D3DSolutionFunction::validParams(), BicubicSplineFunction::validParams(), CoarsenedPiecewiseLinear::validParams(), CompositeFunction::validParams(), ConstantFunction::validParams(), MooseParsedFunctionBase::validParams(), MooseParsedGradFunction::validParams(), MooseParsedVectorFunction::validParams(), PiecewiseBilinear::validParams(), PiecewiseConstant::validParams(), PiecewiseLinear::validParams(), PiecewiseLinearFromVectorPostprocessor::validParams(), PiecewiseMulticonstant::validParams(), PiecewiseMultiInterpolation::validParams(), PiecewiseMultilinear::validParams(), PiecewiseTabularBase::validParams(), SolutionFunction::validParams(), SplineFunction::validParams(), FunctorADConverterTempl< T >::validParams(), FunctorSmootherTempl< T >::validParams(), GenericFunctorGradientMaterialTempl< is_ad >::validParams(), GenericFunctorMaterialTempl< is_ad >::validParams(), GenericVectorFunctorMaterialTempl< is_ad >::validParams(), ParsedFunctorMaterialTempl< is_ad >::validParams(), VectorMagnitudeFunctorMaterialTempl< is_ad >::validParams(), FVBoundaryCondition::validParams(), FVBoundaryScalarLagrangeMultiplierConstraint::validParams(), FVFunctionNeumannBC::validParams(), FVFunctorDirichletBCTempl< is_ad >::validParams(), FVFunctorNeumannBC::validParams(), FVNeumannBC::validParams(), FVOrthogonalBoundaryDiffusion::validParams(), FVFunctionIC::validParams(), FVDiffusionInterface::validParams(), FVInterfaceKernel::validParams(), FVOneVarDiffusionInterface::validParams(), FVAnisotropicDiffusion::validParams(), FVBodyForce::validParams(), FVCoupledForce::validParams(), FVDiffusion::validParams(), FVFluxKernel::validParams(), FVFunctorTimeKernel::validParams(), FVKernel::validParams(), FVMatAdvection::validParams(), FVOrthogonalDiffusion::validParams(), FVReaction::validParams(), FVScalarLagrangeMultiplierConstraint::validParams(), BoundingBoxIC::validParams(), FunctionIC::validParams(), InitialConditionBase::validParams(), RandomIC::validParams(), RandomICBase::validParams(), ScalarInitialCondition::validParams(), VectorConstantIC::validParams(), VectorFunctionIC::validParams(), ElementIndicator::validParams(), Indicator::validParams(), InternalSideIndicator::validParams(), InterfaceDiffusion::validParams(), InterfaceKernelBase::validParams(), PenaltyInterfaceDiffusionTempl< T, is_ad >::validParams(), BlockRestrictable::validParams(), BoundaryRestrictable::validParams(), MortarConsumerInterface::validParams(), OutputInterface::validParams(), RandomInterface::validParams(), SetupInterface::validParams(), TaggingInterface::validParams(), TransientInterface::validParams(), ADConservativeAdvection::validParams(), ADKernelScalarBase::validParams(), ADKernelSUPGTempl< T >::validParams(), ADMatCoupledForce::validParams(), ADMatDiffusionBase< T >::validParams(), ADMatReaction::validParams(), ArrayTimeDerivative::validParams(), BodyForceTempl< is_ad >::validParams(), CoefReactionTempl< is_ad >::validParams(), CoefTimeDerivative::validParams(), ConservativeAdvection::validParams(), CoupledForceTempl< is_ad >::validParams(), DivField::validParams(), EigenKernel::validParams(), FunctionDiffusion::validParams(), GradField::validParams(), KernelScalarBase::validParams(), MassEigenKernel::validParams(), MatCoupledForce::validParams(), MatDiffusionBase< T >::validParams(), MaterialDerivativeTestKernelBase< T >::validParams(), MaterialPropertyValueTempl< is_ad >::validParams(), MatReaction::validParams(), NodalScalarKernel::validParams(), NullKernel::validParams(), ReactionTempl< is_ad >::validParams(), TimeDerivative::validParams(), VectorBodyForce::validParams(), VectorFunctionReaction::validParams(), VectorTimeDerivative::validParams(), LibtorchNeuralNetControl::validParams(), LibtorchControlValuePostprocessor::validParams(), BoundaryMarker::validParams(), ErrorFractionMarker::validParams(), ErrorToleranceMarker::validParams(), QuadraturePointMarker::validParams(), ValueRangeMarker::validParams(), ValueThresholdMarker::validParams(), ADPiecewiseLinearInterpolationMaterial::validParams(), CoupledValueFunctionMaterialTempl< is_ad >::validParams(), DerivativeParsedMaterialHelperTempl< is_ad >::validParams(), DerivativeSumMaterialTempl< is_ad >::validParams(), GenericFunctionMaterialTempl< is_ad >::validParams(), GenericFunctionVectorMaterialTempl< is_ad >::validParams(), Material::validParams(), MaterialADConverterTempl< T >::validParams(), MaterialBase::validParams(), MaterialFunctorConverterTempl< T >::validParams(), MaterialPropertyInterface::validParams(), ParsedMaterialBase::validParams(), ParsedMaterialHelper< is_ad >::validParams(), PiecewiseLinearInterpolationMaterial::validParams(), AnnularMesh::validParams(), ConcentricCircleMesh::validParams(), FileMesh::validParams(), GeneratedMesh::validParams(), ImageMesh::validParams(), MeshGeneratorMesh::validParams(), MooseMesh::validParams(), PatternedMesh::validParams(), RinglebMesh::validParams(), SpiralAnnularMesh::validParams(), StitchedMesh::validParams(), TiledMesh::validParams(), CartesianGridDivision::validParams(), CylindricalGridDivision::validParams(), FunctorBinnedValuesDivision::validParams(), SphericalGridDivision::validParams(), AddMetaDataGenerator::validParams(), AdvancedExtruderGenerator::validParams(), AnnularMeshGenerator::validParams(), BlockDeletionGenerator::validParams(), BoundingBoxNodeSetGenerator::validParams(), BreakBoundaryOnSubdomainGenerator::validParams(), BreakMeshByBlockGenerator::validParams(), BreakMeshByBlockGeneratorBase::validParams(), CartesianMeshGenerator::validParams(), CircularBoundaryCorrectionGenerator::validParams(), CombinerGenerator::validParams(), ConcentricCircleMeshGenerator::validParams(), DistributedRectilinearMeshGenerator::validParams(), ElementDeletionGeneratorBase::validParams(), ElementGenerator::validParams(), ElementSubdomainIDGenerator::validParams(), ExplodeMeshGenerator::validParams(), ExtraNodesetGenerator::validParams(), FileMeshGenerator::validParams(), FillBetweenCurvesGenerator::validParams(), FillBetweenPointVectorsGenerator::validParams(), FillBetweenSidesetsGenerator::validParams(), GeneratedMeshGenerator::validParams(), ImageMeshGenerator::validParams(), LowerDBlockFromSidesetGenerator::validParams(), MeshDiagnosticsGenerator::validParams(), MeshExtruderGenerator::validParams(), MeshGenerator::validParams(), MeshRepairGenerator::validParams(), MoveNodeGenerator::validParams(), OrientedSubdomainBoundingBoxGenerator::validParams(), ParsedCurveGenerator::validParams(), ParsedElementDeletionGenerator::validParams(), ParsedGenerateSideset::validParams(), ParsedNodeTransformGenerator::validParams(), ParsedSubdomainMeshGenerator::validParams(), PatchMeshGenerator::validParams(), PatternedMeshGenerator::validParams(), PlaneIDMeshGenerator::validParams(), PolyLineMeshGenerator::validParams(), RefineBlockGenerator::validParams(), RefineSidesetGenerator::validParams(), RenameBlockGenerator::validParams(), RenameBoundaryGenerator::validParams(), RinglebMeshGenerator::validParams(), SideSetExtruderGenerator::validParams(), SideSetsAroundSubdomainGenerator::validParams(), SideSetsBetweenSubdomainsGenerator::validParams(), SideSetsFromBoundingBoxGenerator::validParams(), SideSetsFromNormalsGenerator::validParams(), SideSetsGeneratorBase::validParams(), SmoothMeshGenerator::validParams(), SphereMeshGenerator::validParams(), SpiralAnnularMeshGenerator::validParams(), StackGenerator::validParams(), StitchedMeshGenerator::validParams(), SubdomainBoundingBoxGenerator::validParams(), TiledMeshGenerator::validParams(), TransfiniteMeshGenerator::validParams(), TransformGenerator::validParams(), UniqueExtraIDMeshGenerator::validParams(), XYDelaunayGenerator::validParams(), XYMeshLineCutter::validParams(), FullSolveMultiApp::validParams(), MultiApp::validParams(), TransientMultiApp::validParams(), CoupledForceNodalKernel::validParams(), LowerBoundNodalKernel::validParams(), NodalKernelBase::validParams(), PenaltyDirichletNodalKernel::validParams(), ReactionNodalKernel::validParams(), UpperBoundNodalKernel::validParams(), Checkpoint::validParams(), Console::validParams(), ControlOutput::validParams(), CSV::validParams(), DOFMapOutput::validParams(), Exodus::validParams(), FileOutput::validParams(), GMVOutput::validParams(), Gnuplot::validParams(), JSONOutput::validParams(), Output::validParams(), OversampleOutput::validParams(), PerfGraphOutput::validParams(), PetscOutput::validParams(), PNGOutput::validParams(), SolutionHistory::validParams(), TableOutput::validParams(), Tecplot::validParams(), TopResidualDebugOutput::validParams(), VariableResidualNormsDebugOutput::validParams(), VTKOutput::validParams(), Parser::validParams(), GridPartitioner::validParams(), LibmeshPartitioner::validParams(), PetscExternalPartitioner::validParams(), RandomPartitioner::validParams(), SingleRankPartitioner::validParams(), ElementGroupCentroidPositions::validParams(), MultiAppPositions::validParams(), Positions::validParams(), ChangeOverFixedPointPostprocessor::validParams(), ChangeOverTimePostprocessor::validParams(), ComparisonPostprocessor::validParams(), ConstantPostprocessor::validParams(), ElementExtremeFunctorValueTempl< is_ad >::validParams(), ElementIntegralArrayVariablePostprocessor::validParams(), ElementIntegralFunctorPostprocessorTempl< is_ad >::validParams(), ElementVectorL2Error::validParams(), FindValueOnLine::validParams(), FunctionSideIntegral::validParams(), FunctionValuePostprocessor::validParams(), GreaterThanLessThanPostprocessor::validParams(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::validParams(), InterfaceIntegralVariableValuePostprocessor::validParams(), LinearCombinationPostprocessor::validParams(), MemoryUsage::validParams(), NodalVariableValue::validParams(), NumDOFs::validParams(), NumElems::validParams(), NumNonlinearIterations::validParams(), NumRelationshipManagers::validParams(), NumVars::validParams(), ParsedPostprocessor::validParams(), PerfGraphData::validParams(), PseudoTimestep::validParams(), Receiver::validParams(), Residual::validParams(), ScalarVariable::validParams(), ScalePostprocessor::validParams(), SideAdvectiveFluxIntegralTempl< is_ad >::validParams(), SideIntegralFunctorPostprocessorTempl< is_ad >::validParams(), TimeExtremeValue::validParams(), TimeIntegratedPostprocessor::validParams(), VectorPostprocessorReductionValue::validParams(), FieldSplitPreconditioner::validParams(), FiniteDifferencePreconditioner::validParams(), MoosePreconditioner::validParams(), SingleMatrixPreconditioner::validParams(), VariableCondensationPreconditioner::validParams(), AdamsPredictor::validParams(), Predictor::validParams(), EigenProblem::validParams(), FEProblemBase::validParams(), ReferenceResidualProblem::validParams(), SubProblem::validParams(), AugmentSparsityOnInterface::validParams(), ElementSideNeighborLayers::validParams(), RelationshipManager::validParams(), ElementStatistics::validParams(), ExtraIDIntegralReporter::validParams(), IterationInfo::validParams(), MeshInfo::validParams(), NodalStatistics::validParams(), RestartableDataReporter::validParams(), Sampler::validParams(), NullScalarKernel::validParams(), ParsedODEKernel::validParams(), ScalarKernelBase::validParams(), Split::validParams(), ActuallyExplicitEuler::validParams(), AStableDirk4::validParams(), ExplicitTimeIntegrator::validParams(), NewmarkBeta::validParams(), CSVFileTimes::validParams(), FunctorTimes::validParams(), TimeIntervalTimes::validParams(), Times::validParams(), AB2PredictorCorrector::validParams(), CSVTimeSequenceStepper::validParams(), FunctionDT::validParams(), IterationAdaptiveDT::validParams(), PostprocessorDT::validParams(), SolutionTimeAdaptiveDT::validParams(), TimeSequenceStepperBase::validParams(), TimeStepper::validParams(), MultiAppCloneReporterTransfer::validParams(), MultiAppConservativeTransfer::validParams(), MultiAppDofCopyTransfer::validParams(), MultiAppGeneralFieldNearestLocationTransfer::validParams(), MultiAppGeneralFieldTransfer::validParams(), MultiAppGeometricInterpolationTransfer::validParams(), MultiAppNearestNodeTransfer::validParams(), MultiAppPostprocessorInterpolationTransfer::validParams(), MultiAppPostprocessorTransfer::validParams(), MultiAppProjectionTransfer::validParams(), MultiAppReporterTransfer::validParams(), MultiAppShapeEvaluationTransfer::validParams(), MultiAppTransfer::validParams(), MultiAppUserObjectTransfer::validParams(), MultiAppVariableValueSamplePostprocessorTransfer::validParams(), Transfer::validParams(), ActivateElementsByPath::validParams(), ActivateElementsCoupled::validParams(), ActivateElementsUserObjectBase::validParams(), DomainUserObject::validParams(), ElementQualityChecker::validParams(), ElementSubdomainModifier::validParams(), ElemSideNeighborLayersTester::validParams(), GeometryBase::validParams(), GeometrySphere::validParams(), GhostingUserObject::validParams(), InterfaceQpMaterialPropertyBaseUserObject< T >::validParams(), InterfaceQpUserObjectBase::validParams(), InterfaceValueUserObject::validParams(), LayeredBase::validParams(), NearestPointBase< UserObjectType, BaseType >::validParams(), NodalNormalsPreprocessor::validParams(), NodalUserObject::validParams(), PointwiseRenormalizeVector::validParams(), PropertyReadFile::validParams(), ShapeUserObject< T >::validParams(), SolutionUserObject::validParams(), Terminator::validParams(), ThresholdElementSubdomainModifier::validParams(), UserObject::validParams(), DerivativeKernelInterface< T >::validParams(), FileRangeBuilder::validParams(), ImageSampler::validParams(), MeshBaseImageSampler::validParams(), NestedSolveTempl< is_ad >::validParams(), MooseVariableBase::validParams(), ConstantVectorPostprocessor::validParams(), CSVReader::validParams(), Eigenvalues::validParams(), ElementVariablesDifferenceMax::validParams(), LeastSquaresFit::validParams(), LeastSquaresFitHistory::validParams(), MaterialVectorPostprocessor::validParams(), PointSamplerBase::validParams(), PointVariableSamplerBase::validParams(), PositionsFunctorValueSampler::validParams(), SidesetInfoVectorPostprocessor::validParams(), SpatialAverageBase::validParams(), SpatialUserObjectVectorPostprocessor::validParams(), VariableValueVolumeHistogram::validParams(), VectorMemoryUsage::validParams(), VectorPostprocessor::validParams(), WorkBalance::validParams(), ADNodalBCTempl< T, Base >::validParams(), ChannelGradientBC::validParams(), DGDiffusionPostprocessorDirichletBC::validParams(), DiffusiveFluxBC::validParams(), FlexiblePostprocessorDirichletBC::validParams(), InflowBC::validParams(), MatINSTemperatureNoBCBC::validParams(), PostprocessorInflowBC::validParams(), RobinBC::validParams(), InterTemperatureAdvection::validParams(), and PotentialAdvection::validParams().
addParam() [6/7]
template<typename T > void InputParameters::addParam (const std::string & name, const std::initializer_list< typename T::value_type > & value, const std::string & doc_string) inline
Enable support for initializer lists as default arguments for container type.
Definition at line 167 of file InputParameters.h.
  {
    addParam<T>(name, T{value}, doc_string);
  }
addParam() [7/7]
template<typename T > void InputParameters::addParam (const std::string & name, const std::string & doc_string)
Definition at line 1422 of file InputParameters.h.
{
  checkParamName(name);
  checkConsistentType<T>(name);
  InputParameters::insert<T>(name);
  _params[name]._doc_string = doc_string;
}
addParamNamesToGroup()
void InputParameters::addParamNamesToGroup (const std::string & space_delim_names, const std::string group_name)
This method takes a space delimited list of parameter names and adds them to the specified group name.
This information is used in the GUI to group parameters into logical sections.
Definition at line 775 of file InputParameters.C.
{
  std::vector<std::string> elements;
  MooseUtils::tokenize(space_delim_names, elements, 1, " \t\n\v\f\r"); // tokenize on whitespace
  // Since we don't require types (templates) for this method, we need
  // to get a raw list of parameter names to compare against.
  std::set<std::string> param_names;
  for (const auto & it : *this)
    param_names.insert(it.first);
  for (const auto & param_name : elements)
    if (_params.count(param_name) > 0)
      _params[param_name]._group = group_name;
    else
      mooseError("Unable to find a parameter with name: ",
                 param_name,
                 " when adding to group ",
                 group_name,
                 '.');
}
Referenced by MultiAppTransfer::addSkipCoordCollapsingParam(), AdvancedOutput::addValidParams(), Moose::PetscSupport::getPetscValidParams(), Moose::SlepcSupport::getSlepcEigenProblemValidParams(), CopyNodalVarsAction::validParams(), MooseObjectAction::validParams(), SetAdaptivityOptionsAction::validParams(), SetupMeshAction::validParams(), AuxKernelTempl< ComputeValueType >::validParams(), AuxScalarKernel::validParams(), MaterialStdVectorAuxTempl< is_ad >::validParams(), NodalPatchRecovery::validParams(), MooseObject::validParams(), BoundaryCondition::validParams(), IntegratedBCBase::validParams(), NodalBCBase::validParams(), Constraint::validParams(), DGKernelBase::validParams(), DiracKernelBase::validParams(), EigenExecutionerBase::validParams(), Eigenvalue::validParams(), Executioner::validParams(), FEProblemSolve::validParams(), FixedPointSolve::validParams(), Transient::validParams(), PiecewiseTabularBase::validParams(), FVBoundaryCondition::validParams(), FVInterfaceKernel::validParams(), FVFluxKernel::validParams(), FVKernel::validParams(), InitialConditionBase::validParams(), Indicator::validParams(), InterfaceKernelBase::validParams(), OutputInterface::validParams(), RandomInterface::validParams(), TaggingInterface::validParams(), TransientInterface::validParams(), DerivativeSumMaterialTempl< is_ad >::validParams(), Material::validParams(), MaterialBase::validParams(), GeneratedMesh::validParams(), MooseMesh::validParams(), AdvancedExtruderGenerator::validParams(), MeshGenerator::validParams(), TransfiniteMeshGenerator::validParams(), MultiApp::validParams(), TransientMultiApp::validParams(), NodalKernelBase::validParams(), Console::validParams(), CSV::validParams(), Exodus::validParams(), FileOutput::validParams(), GMVOutput::validParams(), Output::validParams(), OversampleOutput::validParams(), PetscOutput::validParams(), TableOutput::validParams(), Tecplot::validParams(), VTKOutput::validParams(), Positions::validParams(), Postprocessor::validParams(), FEProblemBase::validParams(), SubProblem::validParams(), ScalarKernelBase::validParams(), Times::validParams(), MultiAppConservativeTransfer::validParams(), Transfer::validParams(), LayeredBase::validParams(), NearestPointBase< UserObjectType, BaseType >::validParams(), NodalPatchRecoveryBase::validParams(), ProjectedStatefulMaterialNodalPatchRecoveryTempl< T, is_ad >::validParams(), RadialAverage::validParams(), ShapeUserObject< T >::validParams(), SolutionUserObject::validParams(), UserObject::validParams(), ImageSampler::validParams(), MeshBaseImageSampler::validParams(), MooseVariableBase::validParams(), LeastSquaresFitHistory::validParams(), and VectorPostprocessor::validParams().
addPrivateParam() [1/6]
template<> void InputParameters::addPrivateParam (const std::string &)
addPrivateParam() [2/6]
template<> void InputParameters::addPrivateParam (const std::string &)
addPrivateParam() [3/6]
template<> void InputParameters::addPrivateParam (const std::string &)
Definition at line 1053 of file InputParameters.C.
{
  mooseError("You must supply a MooseEnum object when using addPrivateParam, even if the parameter "
             "is not required!");
}
addPrivateParam() [4/6]
template<> void InputParameters::addPrivateParam (const std::string &)
Definition at line 1061 of file InputParameters.C.
{
  mooseError("You must supply a MultiMooseEnum object when using addPrivateParam, even if the "
             "parameter is not required!");
}
addPrivateParam() [5/6]
template<typename T > void InputParameters::addPrivateParam (const std::string & name)
Definition at line 1518 of file InputParameters.h.
{
  checkParamName(name);
  checkConsistentType<T>(name);
  InputParameters::insert<T>(name);
  _params[name]._is_private = true;
}
addPrivateParam() [6/6]
template<typename T > void InputParameters::addPrivateParam (const std::string & name, const T & value)
These method add a parameter to the InputParameters object which can be retrieved like any other parameter.
This parameter however is not printed in the Input file syntax dump or web page dump so does not take a documentation string. The first version of this function takes an optional default value.
Definition at line 1529 of file InputParameters.h.
{
  checkParamName(name);
  checkConsistentType<T>(name);
  InputParameters::set<T>(name) = value;
  auto & metadata = _params[name];
  metadata._is_private = true;
  metadata._set_by_add_param = true;
}
Referenced by AddControlAction::act(), FEProblemBase::addOutput(), ActionFactory::create(), ActionFactory::getValidParams(), Action::validParams(), CreateProblemDefaultAction::validParams(), GlobalParamsAction::validParams(), AuxKernelTempl< ComputeValueType >::validParams(), MooseApp::validParams(), MooseObject::validParams(), EigenExecutionerBase::validParams(), Eigenvalue::validParams(), InternalSideIndicator::validParams(), BlockRestrictable::validParams(), BoundaryRestrictable::validParams(), BoundaryRestrictableRequired::validParams(), MaterialBase::validParams(), MaterialPropertyInterface::validParams(), MooseMesh::validParams(), MultiApp::validParams(), Checkpoint::validParams(), Output::validParams(), XDA::validParams(), MoosePartitioner::validParams(), MoosePreconditioner::validParams(), DisplacedProblem::validParams(), FEProblemBase::validParams(), RelationshipManager::validParams(), ElementReporter::validParams(), GeneralReporter::validParams(), NodalReporter::validParams(), NodalNormalsPreprocessor::validParams(), MooseVariableBase::validParams(), and VectorPostprocessor::validParams().
addRangeCheckedParam() [1/2]
template<typename T > void InputParameters::addRangeCheckedParam (const std::string & name, const std::string & parsed_function, const std::string & doc_string)
Definition at line 1461 of file InputParameters.h.
{
  addParam<T>(name, doc_string);
  _params[name]._range_function = parsed_function;
}
addRangeCheckedParam() [2/2]
template<typename T > void InputParameters::addRangeCheckedParam (const std::string & name, const T & value, const std::string & parsed_function, const std::string & doc_string)
Definition at line 1450 of file InputParameters.h.
{
  addParam<T>(name, value, doc_string);
  _params[name]._range_function = parsed_function;
}
Referenced by MultiAppTransfer::addBBoxFactorParam(), Moose::commonAdaptivityParams(), ElementLpNormAux::validParams(), EqualValueConstraint::validParams(), FEProblemSolve::validParams(), FixedPointSolve::validParams(), PeriodicFunction::validParams(), ErrorFractionMarker::validParams(), AnnularMesh::validParams(), ConcentricCircleMesh::validParams(), GeneratedMesh::validParams(), ImageMesh::validParams(), PatternedMesh::validParams(), CylindricalGridDivision::validParams(), SphericalGridDivision::validParams(), AdvancedExtruderGenerator::validParams(), AnnularMeshGenerator::validParams(), CircularBoundaryCorrectionGenerator::validParams(), ConcentricCircleMeshGenerator::validParams(), DistributedRectilinearMeshGenerator::validParams(), FillBetweenCurvesGenerator::validParams(), FillBetweenPointVectorsGenerator::validParams(), FillBetweenSidesetsGenerator::validParams(), GeneratedMeshGenerator::validParams(), ImageMeshGenerator::validParams(), ParsedCurveGenerator::validParams(), PatternedMeshGenerator::validParams(), SideSetsAroundSubdomainGenerator::validParams(), TransfiniteMeshGenerator::validParams(), XYDelaunayGenerator::validParams(), MultiApp::validParams(), PNGOutput::validParams(), ElementW1pError::validParams(), ElementPointNeighborLayers::validParams(), ElementSideNeighborLayers::validParams(), NewmarkBeta::validParams(), ConstantDT::validParams(), IterationAdaptiveDT::validParams(), LogConstantDT::validParams(), TimeStepper::validParams(), MultiAppGeneralFieldTransfer::validParams(), RadialAverage::validParams(), and MooseVariableBase::validParams().
addRelationshipManager()
void InputParameters::addRelationshipManager (const std::string & name, Moose::RelationshipManagerType rm_type, Moose::RelationshipManagerInputParameterCallback input_parameter_callback = nullptr)
Tells MOOSE about a RelationshipManager that this object needs.
RelationshipManagers handle element "ghosting", "non-local DOF access" and "sparsity pattern" relationships.
Basically: if this object needs non-local (ie non-current-element) data access then you probably need a relationship manager
Parameters
name The name of the RelationshipManager type
rm_type The type (GEOMETRIC/ALGEBRAIC) of the RelationshipManger. Note: You can use boolean logic to to "or" RelationshipManagerTypes together to make a RelationshipManager that is multi-typed.
input_parameter_callback This is a function pointer that will get called to fill in the RelationShipManager's InputParameters. See MooseTypes.h for the signature of this function.
Definition at line 487 of file InputParameters.C.
{
  _buildable_rm_types.emplace_back(name, rm_type, input_parameter_callback);
}
Referenced by FunctorElementalGradientAuxTempl< is_ad >::validParams(), ProjectionAux::validParams(), MortarConstraintBase::validParams(), DGKernelBase::validParams(), FVFunctorDirichletBCTempl< is_ad >::validParams(), FVInterfaceKernel::validParams(), FVKernel::validParams(), InterfaceKernelBase::validParams(), MortarConsumerInterface::validParams(), InterfaceMaterial::validParams(), DistributedRectilinearMeshGenerator::validParams(), Exodus::validParams(), GMVOutput::validParams(), Tecplot::validParams(), MultiAppProjectionTransfer::validParams(), DomainUserObject::validParams(), ElemSideNeighborLayersGeomTester::validParams(), ElemSideNeighborLayersTester::validParams(), InterfaceUserObjectBase::validParams(), InternalSideUserObject::validParams(), NodalPatchRecoveryBase::validParams(), ProjectedStatefulMaterialNodalPatchRecoveryBase::validParams(), ProjectedStatefulMaterialNodalPatchRecoveryTempl< T, is_ad >::validParams(), RadialAverage::validParams(), SideUserObject::validParams(), and MooseVariableFV< OutputType >::validParams().
addRequiredCommandLineParam()
template<typename T > void InputParameters::addRequiredCommandLineParam (const std::string & name, const std::string & syntax, const std::string & doc_string)
Add parameters for retrieval from the command line.
NOTE: This ONLY works for App objects! This is not valid for normal MOOSE objects!
Parameters
name The name of the parameter
syntax Space separated list of command-line switch syntax that can set this option
doc_string Documentation. This will be shown for –help
Definition at line 1542 of file InputParameters.h.
{
  addRequiredParam<T>(name, doc_string);
  MooseUtils::tokenize(syntax, _params[name]._cli_flag_names, 1, " \t\n\v\f\r");
}
addRequiredCoupledVar()
void InputParameters::addRequiredCoupledVar (const std::string & name, const std::string & doc_string)
This method adds a coupled variable name pair.
The parser will look for variable name pair in the input file and can return a reference to the storage location for the coupled variable. If the coupled variable is not supplied in the input file, and error is thrown.
Version 2: An auto built vector will be built from the base_name and num_name param. See addCoupledVar for an example
Definition at line 313 of file InputParameters.C.
{
  addRequiredParam<std::vector<VariableName>>(name, doc_string);
  _coupled_vars.insert(name);
}
Referenced by transferParam(), DensityLogConvert::validParams(), DensityLogConvertScalar::validParams(), ReactionRateEEDFTownsendLogTempl< is_ad >::validParams(), ReactionRateOneBodyScalar::validParams(), ReactionRateThreeBodyScalar::validParams(), ReactionRateTwoBodyScalar::validParams(), SuperelasticRateCoefficientScalar::validParams(), ADEEDFElasticLog::validParams(), ADEEDFElasticTownsendLog::validParams(), ADEEDFEnergyLog::validParams(), ADEEDFEnergyTownsendLog::validParams(), ADEEDFReactionLog::validParams(), ADEEDFReactionTownsendLog::validParams(), EEDFElasticLog::validParams(), EEDFElasticTownsendLog::validParams(), EEDFEnergyLog::validParams(), EEDFEnergyTownsendLog::validParams(), EEDFReactionLog::validParams(), EEDFReactionTownsendLog::validParams(), ReactionFirstOrder::validParams(), ReactionFirstOrderEnergy::validParams(), ReactionFirstOrderEnergyLog::validParams(), ReactionFirstOrderLog::validParams(), ReactionSecondOrder::validParams(), ReactionSecondOrderEnergy::validParams(), ReactionSecondOrderEnergyLog::validParams(), ReactionSecondOrderLogTempl< is_ad >::validParams(), ReactionThirdOrder::validParams(), ReactionThirdOrderEnergy::validParams(), ReactionThirdOrderEnergyLog::validParams(), ReactionThirdOrderLogTempl< is_ad >::validParams(), ADEEDFRateConstantTownsend::validParams(), EEDFRateConstant::validParams(), EEDFRateConstantTownsend::validParams(), InterpolatedCoefficientLinear::validParams(), InterpolatedCoefficientSpline::validParams(), Product1BodyScalar::validParams(), Product1BodyScalarLog::validParams(), Product2BodyScalar::validParams(), Product2BodyScalarLog::validParams(), Product3BodyScalar::validParams(), Reactant2BodyScalar::validParams(), Reactant2BodyScalarLog::validParams(), Reactant3BodyScalar::validParams(), Reactant3BodyScalarLog::validParams(), AbsValueAux::validParams(), CurrentTempl< is_ad >::validParams(), DensityNormalization::validParams(), DiffusiveFluxTempl< is_ad >::validParams(), DriftDiffusionFluxAux::validParams(), Efield::validParams(), EFieldAdvAuxTempl< is_ad >::validParams(), ElectronTemperature::validParams(), PowerDepTempl< is_ad >::validParams(), ProcRateTempl< is_ad >::validParams(), Sigma::validParams(), TM0CylindricalErAux::validParams(), TM0CylindricalEzAux::validParams(), TotalFluxTempl< is_ad >::validParams(), DCIonBC::validParams(), EconomouDielectricBC::validParams(), ElectronAdvectionDoNothingBC::validParams(), ElectronDiffusionDoNothingBC::validParams(), ElectronTemperatureDirichletBC::validParams(), FieldEmissionBC::validParams(), HagelaarElectronAdvectionBC::validParams(), HagelaarElectronBC::validParams(), HagelaarEnergyAdvectionBC::validParams(), HagelaarEnergyBC::validParams(), HagelaarIonAdvectionBC::validParams(), LymberopoulosElectronBC::validParams(), LymberopoulosIonBC::validParams(), MatchedValueLogBC::validParams(), NeumannCircuitVoltageMoles_KV::validParams(), NeumannCircuitVoltageNew::validParams(), PenaltyCircuitPotential::validParams(), PotentialDriftOutflowBC::validParams(), SakiyamaElectronDiffusionBC::validParams(), SakiyamaEnergyDiffusionBC::validParams(), SakiyamaEnergySecondaryElectronBC::validParams(), SakiyamaIonAdvectionBC::validParams(), SakiyamaSecondaryElectronBC::validParams(), SchottkyEmissionBC::validParams(), SecondaryElectronBC::validParams(), SecondaryElectronEnergyBC::validParams(), DGEFieldAdvection::validParams(), InterfaceAdvection::validParams(), InterfaceLogDiffusionElectrons::validParams(), AccelerationByAveraging::validParams(), ChargeSourceMoles_KV::validParams(), CoeffDiffusionForShootMethod::validParams(), EEDFReactionLogForShootMethod::validParams(), EFieldAdvection::validParams(), EFieldArtDiff::validParams(), EFieldMagnitudeSource::validParams(), ElectronEnergyLossFromElastic::validParams(), ElectronEnergyLossFromExcitation::validParams(), ElectronEnergyLossFromIonization::validParams(), ElectronEnergyTermElasticRate::validParams(), ElectronEnergyTermRate::validParams(), ElectronsFromIonization::validParams(), ExcitationReaction::validParams(), IonsFromIonization::validParams(), JouleHeating::validParams(), PotentialGradientSource::validParams(), ProductAABBRxn::validParams(), ProductFirstOrderRxn::validParams(), ShootMethodLog::validParams(), TM0CylindricalEr::validParams(), TM0CylindricalEz::validParams(), ADGasElectronMoments::validParams(), ADSurfaceCharge::validParams(), AverageNodalDifference::validParams(), RelativeElementL2Difference::validParams(), SideCurrent::validParams(), SideTotFluxIntegral::validParams(), CurrentDensityShapeSideUserObject::validParams(), ArrayVariableComponent::validParams(), ArrayVarReductionAux::validParams(), CopyValueAux::validParams(), DiffusionFluxAux::validParams(), ElementLpNormAux::validParams(), NearestNodeValueAux::validParams(), NormalizationAux::validParams(), ProjectionAux::validParams(), ScalarTagMatrixAux::validParams(), SecondTimeDerivativeAux::validParams(), TagAuxBase< T >::validParams(), VariableGradientComponent::validParams(), VariableTimeIntegrationAux::validParams(), VectorMagnitudeAux::validParams(), VectorVariableComponentAux::validParams(), VectorVariableMagnitudeAux::validParams(), ADVectorMatchedValueBC::validParams(), ArrayLowerDIntegratedBC::validParams(), CoupledVarNeumannBC::validParams(), LowerDIntegratedBC::validParams(), MatchedValueBCTempl< is_ad >::validParams(), OneDEqualValueConstraintBC::validParams(), ADPenaltyPeriodicSegmentalConstraint::validParams(), ADPeriodicSegmentalConstraint::validParams(), NodeElemConstraint::validParams(), PenaltyPeriodicSegmentalConstraint::validParams(), PeriodicSegmentalConstraint::validParams(), ArrayDGLowerDKernel::validParams(), DGLowerDKernel::validParams(), HFEMTestJump::validParams(), HFEMTrialJump::validParams(), FVBoundaryScalarLagrangeMultiplierConstraint::validParams(), FVScalarLagrangeMultiplierInterface::validParams(), FVScalarLagrangeMultiplierConstraint::validParams(), InterfaceKernelBase::validParams(), ArrayCoupledTimeDerivative::validParams(), ConservativeAdvection::validParams(), CoupledForceTempl< is_ad >::validParams(), CoupledTimeDerivative::validParams(), DivField::validParams(), GradField::validParams(), MatCoupledForce::validParams(), MaterialDerivativeTestKernelBase< T >::validParams(), ScalarLagrangeMultiplier::validParams(), VectorCoupledTimeDerivative::validParams(), ADPiecewiseLinearInterpolationMaterial::validParams(), CompositeTensorBase< T, U >::validParams(), DerivativeSumMaterialTempl< is_ad >::validParams(), InterpolatedStatefulMaterialTempl< T >::validParams(), PiecewiseLinearInterpolationMaterial::validParams(), VectorFromComponentVariablesMaterialTempl< is_ad >::validParams(), CoupledForceNodalKernel::validParams(), LowerBoundNodalKernel::validParams(), UpperBoundNodalKernel::validParams(), ElementIntegralArrayVariablePostprocessor::validParams(), ElementIntegralVariablePostprocessor::validParams(), ElementL2Difference::validParams(), ElementVariablePostprocessor::validParams(), ElementVectorL2Error::validParams(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::validParams(), InterfaceIntegralVariableValuePostprocessor::validParams(), InternalSideIntegralVariablePostprocessor::validParams(), NodalVariablePostprocessor::validParams(), SideIntegralVariablePostprocessor::validParams(), SideVariablePostprocessor::validParams(), VariableInnerProduct::validParams(), ElementVariableStatistics::validParams(), NodalVariableStatistics::validParams(), CoupledODETimeDerivative::validParams(), NodalEqualValueConstraint::validParams(), ActivateElementsCoupled::validParams(), CoupledVarThresholdElementSubdomainModifier::validParams(), ElementIntegralVariableUserObject::validParams(), InterfaceQpValueUserObject::validParams(), SideIntegralVariableUserObject::validParams(), ElementVariablesDifferenceMax::validParams(), ElementVariableVectorPostprocessor::validParams(), NodalVariableVectorPostprocessor::validParams(), PointVariableSamplerBase::validParams(), SideValueSampler::validParams(), Density::validParams(), ExampleShapeSideIntegratedBC::validParams(), DGCoupledAdvection::validParams(), DenomShapeSideUserObject::validParams(), and NumShapeSideUserObject::validParams().
addRequiredCoupledVarWithAutoBuild()
void InputParameters::addRequiredCoupledVarWithAutoBuild (const std::string & name, const std::string & base_name, const std::string & num_name, const std::string & doc_string)
Definition at line 302 of file InputParameters.C.
{
  addRequiredParam<std::vector<VariableName>>(name, doc_string);
  addCoupledVarWithAutoBuild(name, base_name, num_name, doc_string);
}
addRequiredCustomTypeParam()
template<typename T > void InputParameters::addRequiredCustomTypeParam (const std::string & name, const std::string & custom_type, const std::string & doc_string)
These methods add an option parameter and with a customer type to the InputParameters object.
The custom type will be output in YAML dumps and can be used within the GUI application.
Definition at line 1471 of file InputParameters.h.
{
  addRequiredParam<T>(name, doc_string);
  _params[name]._custom_type = custom_type;
}
Referenced by ParsedAuxScalar::validParams(), ParsedScalarRateCoefficient::validParams(), ArrayParsedAux::validParams(), ParsedAux::validParams(), ParsedVectorAux::validParams(), ParsedFunctorMaterialTempl< is_ad >::validParams(), ParsedPostprocessor::validParams(), ParsedODEKernel::validParams(), and Terminator::validParams().
addRequiredParam() [1/6]
template<> void InputParameters::addRequiredParam (const std::string & name, const MooseEnum & moose_enum, const std::string & doc_string)
addRequiredParam() [2/6]
template<> void InputParameters::addRequiredParam (const std::string & name, const MooseEnum & moose_enum, const std::string & doc_string)
Definition at line 987 of file InputParameters.C.
{
  InputParameters::set<MooseEnum>(name) = moose_enum; // valid parameter is set by set_attributes
  auto & metadata = _params[name];
  metadata._required = true;
  metadata._doc_string = doc_string;
}
addRequiredParam() [3/6]
template<> void InputParameters::addRequiredParam (const std::string & name, const MultiMooseEnum & moose_enum, const std::string & doc_string)
addRequiredParam() [4/6]
template<> void InputParameters::addRequiredParam (const std::string & name, const MultiMooseEnum & moose_enum, const std::string & doc_string)
Definition at line 999 of file InputParameters.C.
{
  InputParameters::set<MultiMooseEnum>(name) =
      moose_enum; // valid parameter is set by set_attributes
  auto & metadata = _params[name];
  metadata._required = true;
  metadata._doc_string = doc_string;
}
addRequiredParam() [5/6]
template<typename T > void InputParameters::addRequiredParam (const std::string & name, const std::string & doc_string)
This method adds a parameter and documentation string to the InputParameters object that will be extracted from the input file.
If the parameter is missing in the input file, and error will be thrown
Definition at line 1379 of file InputParameters.h.
{
  checkParamName(name);
  checkConsistentType<T>(name);
  InputParameters::insert<T>(name);
  auto & metadata = _params[name];
  metadata._required = true;
  metadata._doc_string = doc_string;
}
Referenced by AddGeneralReactions::validParams(), AddSpecies::validParams(), AddZapdosReactions::validParams(), ChemicalReactions::validParams(), ChemicalReactionsBase::validParams(), BolsigValueScalar::validParams(), DensityLogConvert::validParams(), DensityLogConvertScalar::validParams(), EEDFRateCoefficientScalar::validParams(), ElectronMobility::validParams(), ReactionRateEEDFTownsendLogTempl< is_ad >::validParams(), ReactionRateFirstOrder::validParams(), ReactionRateFirstOrderLog::validParams(), ReactionRateOneBodyScalar::validParams(), ReactionRateSecondOrder::validParams(), ReactionRateSecondOrderLog::validParams(), ReactionRateThirdOrder::validParams(), ReactionRateThirdOrderLog::validParams(), ReactionRateThreeBodyScalar::validParams(), ReactionRateTwoBodyScalar::validParams(), SuperelasticRateCoefficientScalar::validParams(), ADEEDFElasticLog::validParams(), ADEEDFElasticTownsendLog::validParams(), ADEEDFEnergyLog::validParams(), ADEEDFEnergyTownsendLog::validParams(), ADEEDFReactionLog::validParams(), ADEEDFReactionTownsendLog::validParams(), EEDFElasticLog::validParams(), EEDFElasticTownsendLog::validParams(), EEDFEnergyLog::validParams(), EEDFEnergyTownsendLog::validParams(), EEDFReactionLog::validParams(), EEDFReactionTownsendLog::validParams(), LogStabilization::validParams(), ReactionFirstOrder::validParams(), ReactionFirstOrderEnergy::validParams(), ReactionFirstOrderEnergyLog::validParams(), ReactionFirstOrderLog::validParams(), ReactionSecondOrder::validParams(), ReactionSecondOrderEnergy::validParams(), ReactionSecondOrderEnergyLog::validParams(), ReactionSecondOrderLogTempl< is_ad >::validParams(), ReactionThirdOrder::validParams(), ReactionThirdOrderEnergy::validParams(), ReactionThirdOrderEnergyLog::validParams(), ReactionThirdOrderLogTempl< is_ad >::validParams(), ADEEDFRateConstantTownsend::validParams(), ADZapdosEEDFRateConstant::validParams(), DiffusionRateTemp::validParams(), EEDFRateConstant::validParams(), EEDFRateConstantTownsend::validParams(), ElectricField::validParams(), GenericRateConstantTempl< is_ad >::validParams(), HeatCapacityRatio::validParams(), InterpolatedCoefficientLinear::validParams(), InterpolatedCoefficientSpline::validParams(), SuperelasticReactionRate::validParams(), ZapdosEEDFRateConstant::validParams(), EnergyTermScalar::validParams(), LogStabilizationScalar::validParams(), ODETimeDerivativeTemperature::validParams(), Product1BodyScalar::validParams(), Product1BodyScalarLog::validParams(), Product2BodyScalar::validParams(), Product2BodyScalarLog::validParams(), Product3BodyScalar::validParams(), Product3BodyScalarLog::validParams(), Reactant1BodyScalar::validParams(), Reactant1BodyScalarLog::validParams(), Reactant2BodyScalar::validParams(), Reactant2BodyScalarLog::validParams(), Reactant3BodyScalar::validParams(), Reactant3BodyScalarLog::validParams(), ScalarDiffusion::validParams(), BoltzmannSolverScalar::validParams(), ObjTest::validParams(), PolynomialCoefficients::validParams(), AddDriftDiffusionAction::validParams(), AddPeriodicControllers::validParams(), AddPeriodicRelativeNodalDifference::validParams(), CurrentTempl< is_ad >::validParams(), DensityMoles::validParams(), DensityNormalization::validParams(), DiffusiveFluxTempl< is_ad >::validParams(), Efield::validParams(), EFieldAdvAuxTempl< is_ad >::validParams(), Position::validParams(), PowerDepTempl< is_ad >::validParams(), ProcRateTempl< is_ad >::validParams(), ProcRateForRateCoeffTempl< is_ad >::validParams(), ProcRateForRateCoeffThreeBodyTempl< is_ad >::validParams(), TM0CylindricalErAux::validParams(), TM0CylindricalEzAux::validParams(), CircuitDirichletPotential::validParams(), DCIonBC::validParams(), DriftDiffusionDoNothingBC::validParams(), EconomouDielectricBC::validParams(), ElectronAdvectionDoNothingBC::validParams(), ElectronDiffusionDoNothingBC::validParams(), ElectronTemperatureDirichletBC::validParams(), FieldEmissionBC::validParams(), HagelaarElectronAdvectionBC::validParams(), HagelaarElectronBC::validParams(), HagelaarEnergyAdvectionBC::validParams(), HagelaarEnergyBC::validParams(), HagelaarIonAdvectionBC::validParams(), HagelaarIonDiffusionBC::validParams(), LogDensityDirichletBC::validParams(), LymberopoulosElectronBC::validParams(), LymberopoulosIonBC::validParams(), MatchedValueLogBC::validParams(), NeumannCircuitVoltageMoles_KV::validParams(), NeumannCircuitVoltageNew::validParams(), PenaltyCircuitPotential::validParams(), SakiyamaElectronDiffusionBC::validParams(), SakiyamaEnergyDiffusionBC::validParams(), SakiyamaEnergySecondaryElectronBC::validParams(), SakiyamaIonAdvectionBC::validParams(), SakiyamaSecondaryElectronBC::validParams(), SchottkyEmissionBC::validParams(), SecondaryElectronBC::validParams(), SecondaryElectronEnergyBC::validParams(), TM0AntennaVertBC::validParams(), ArbitrarilyTiedValueConstraint::validParams(), DGCoeffDiffusion::validParams(), AnalyticalDiffIndicator::validParams(), InterfaceAdvection::validParams(), InterfaceLogDiffusionElectrons::validParams(), AccelerationByAveraging::validParams(), ChargeSourceMoles_KV::validParams(), CoeffDiffusion::validParams(), CoeffDiffusionForShootMethod::validParams(), CoeffDiffusionLin::validParams(), DriftDiffusion::validParams(), EEDFReactionLogForShootMethod::validParams(), EFieldAdvection::validParams(), EFieldArtDiff::validParams(), ElectronEnergyLossFromElastic::validParams(), ElectronEnergyLossFromExcitation::validParams(), ElectronEnergyLossFromIonization::validParams(), ElectronEnergyTermElasticRate::validParams(), ElectronEnergyTermRate::validParams(), ElectronsFromIonization::validParams(), ExcitationReaction::validParams(), IonsFromIonization::validParams(), JouleHeating::validParams(), LogStabilizationMoles::validParams(), ReactionSecondOrderLogForShootMethod::validParams(), ReactionThirdOrderLogForShootMethod::validParams(), ScaledReaction::validParams(), TM0Cylindrical::validParams(), TM0CylindricalEr::validParams(), TM0CylindricalEz::validParams(), UserSource::validParams(), ADGasElectronMoments::validParams(), ADSurfaceCharge::validParams(), Gas::validParams(), GasBase::validParams(), GasElectronMoments::validParams(), HeavySpeciesTempl< is_ad >::validParams(), PeriodicComparisonCounter::validParams(), PlasmaFrequencyInverse::validParams(), SideCurrent::validParams(), SideTotFluxIntegral::validParams(), CurrentDensityShapeSideUserObject::validParams(), ProvideMobility::validParams(), MaterialDerivativeTestAction::validParams(), MooseObjectAction::validParams(), AdvectiveFluxAux::validParams(), AuxKernelTempl< ComputeValueType >::validParams(), AuxNodalScalarKernel::validParams(), AuxScalarKernel::validParams(), BoundsAuxBase::validParams(), ConstantBoundsAux::validParams(), ConstantScalarAux::validParams(), ContainsPointAux::validParams(), DebugResidualAux::validParams(), DiffusionFluxAux::validParams(), DivergenceAuxTempl< is_ad >::validParams(), ElementL2ErrorFunctionAux::validParams(), ElementLengthAux::validParams(), ElementQualityAux::validParams(), ElementUOAux::validParams(), ExtraElementIDAux::validParams(), FunctionArrayAux::validParams(), FunctionAux::validParams(), FunctionScalarAux::validParams(), FunctorAux::validParams(), FunctorElementalGradientAuxTempl< is_ad >::validParams(), FunctorVectorElementalAuxTempl< is_ad >::validParams(), GapValueAux::validParams(), GhostingAux::validParams(), InterfaceValueUserObjectAux::validParams(), MaterialAuxBaseTempl< T, is_ad, RT >::validParams(), MaterialRankFourTensorAux::validParams(), MaterialRankTwoTensorAuxTempl< is_ad >::validParams(), MeshDivisionAux::validParams(), NearestNodeDistanceAux::validParams(), NearestNodeValueAux::validParams(), NodalPatchRecoveryAuxBase::validParams(), PenetrationAux::validParams(), ProjectedMaterialPropertyNodalPatchRecoveryAux::validParams(), SolutionAux::validParams(), SolutionScalarAux::validParams(), SpatialUserObjectAux::validParams(), TagVectorArrayVariableAux::validParams(), TagVectorArrayVariableValueAux::validParams(), TagVectorAux::validParams(), VectorFunctionAux::validParams(), VectorPostprocessorVisualizationAux::validParams(), ADDirichletBC::validParams(), ADFunctionNeumannBC::validParams(), ADFunctionPenaltyDirichletBC::validParams(), ADPenaltyDirichletBC::validParams(), ArrayDirichletBC::validParams(), ArrayPenaltyDirichletBC::validParams(), DGFunctionDiffusionDirichletBC::validParams(), DirichletBC::validParams(), FunctionDirichletBC::validParams(), FunctionGradientNeumannBC::validParams(), FunctionNeumannBC::validParams(), FunctionPenaltyDirichletBC::validParams(), FunctorDirichletBC::validParams(), FunctorNeumannBC::validParams(), MatNeumannBCTempl< is_ad >::validParams(), OneDEqualValueConstraintBC::validParams(), PenaltyDirichletBC::validParams(), PostprocessorDirichletBC::validParams(), VectorCurlPenaltyDirichletBC::validParams(), VectorDirichletBC::validParams(), VectorDivPenaltyDirichletBC::validParams(), VectorPenaltyDirichletBC::validParams(), EqualGradientConstraint::validParams(), EqualValueBoundaryConstraint::validParams(), EqualValueEmbeddedConstraint::validParams(), LinearNodalConstraint::validParams(), NodeElemConstraint::validParams(), BoolFunctionControl::validParams(), ConditionalFunctionEnableControl::validParams(), PIDTransientControl::validParams(), RealFunctionControl::validParams(), ConstantDamper::validParams(), ElementDamper::validParams(), NodalDamper::validParams(), ADDGAdvection::validParams(), ADDGDiffusion::validParams(), ArrayDGDiffusion::validParams(), DGConvection::validParams(), DGDiffusion::validParams(), ConstantPointSource::validParams(), FunctionDiracSource::validParams(), ReporterPointSource::validParams(), VectorConstantPointSource::validParams(), Distribution::validParams(), EigenExecutionerBase::validParams(), Axisymmetric2D3DSolutionFunction::validParams(), BicubicSplineFunction::validParams(), CoarsenedPiecewiseLinear::validParams(), LinearCombinationFunction::validParams(), PeriodicFunction::validParams(), PiecewiseConstantFromCSV::validParams(), PiecewiseLinearFromVectorPostprocessor::validParams(), SolutionFunction::validParams(), SplineFunction::validParams(), ParsedFunctorMaterialTempl< is_ad >::validParams(), VectorMagnitudeFunctorMaterialTempl< is_ad >::validParams(), FVBoundaryCondition::validParams(), FVConstantScalarOutflowBC::validParams(), FVDirichletBC::validParams(), FVFunctionDirichletBC::validParams(), FVFunctionNeumannBC::validParams(), FVFunctorDirichletBCTempl< is_ad >::validParams(), FVFunctorNeumannBC::validParams(), FVOrthogonalBoundaryDiffusion::validParams(), FVPostprocessorDirichletBC::validParams(), FVConstantIC::validParams(), FVFunctionIC::validParams(), FVInitialConditionBase::validParams(), FVDiffusionInterface::validParams(), FVInterfaceKernel::validParams(), FVOneVarDiffusionInterface::validParams(), FVAdvection::validParams(), FVAnisotropicDiffusion::validParams(), FVBoundedValueConstraint::validParams(), FVCoupledForce::validParams(), FVDiffusion::validParams(), FVDivergence::validParams(), FVMatAdvection::validParams(), FVOrthogonalDiffusion::validParams(), FVPointValueConstraint::validParams(), ArrayConstantIC::validParams(), ArrayFunctionIC::validParams(), BoundingBoxIC::validParams(), ConstantIC::validParams(), FunctionIC::validParams(), FunctionScalarIC::validParams(), InitialConditionBase::validParams(), IntegralPreservingFunctionIC::validParams(), ScalarComponentIC::validParams(), ScalarConstantIC::validParams(), ScalarSolutionIC::validParams(), SolutionIC::validParams(), VectorConstantIC::validParams(), AnalyticalIndicator::validParams(), ElementIndicator::validParams(), InternalSideIndicator::validParams(), InterfaceReaction::validParams(), PenaltyInterfaceDiffusionTempl< T, is_ad >::validParams(), BoundaryRestrictableRequired::validParams(), MortarConsumerInterface::validParams(), OrientedBoxInterface::validParams(), ADConservativeAdvection::validParams(), AnisotropicDiffusion::validParams(), ArrayBodyForce::validParams(), ArrayDiffusion::validParams(), ArrayReaction::validParams(), MaterialDerivativeRankFourTestKernel::validParams(), MaterialDerivativeRankTwoTestKernel::validParams(), MaterialDerivativeTestKernelBase< T >::validParams(), MaterialPropertyValueTempl< is_ad >::validParams(), ScalarLMKernelTempl< is_ad >::validParams(), LibtorchNeuralNetControl::validParams(), LibtorchControlValuePostprocessor::validParams(), LibtorchArtificialNeuralNetParameters::validParams(), BoundaryMarker::validParams(), BoundaryPreservedMarker::validParams(), BoxMarker::validParams(), ComboMarker::validParams(), IndicatorMarker::validParams(), OrientedBoxMarker::validParams(), QuadraturePointMarker::validParams(), ReporterPointMarker::validParams(), UniformMarker::validParams(), ValueRangeMarker::validParams(), ADPiecewiseLinearInterpolationMaterial::validParams(), CompositeTensorBase< T, U >::validParams(), CoupledValueFunctionMaterialTempl< is_ad >::validParams(), GenericConstant2DArray::validParams(), GenericConstantArray::validParams(), GenericConstantMaterialTempl< is_ad >::validParams(), GenericConstantRankTwoTensorTempl< is_ad >::validParams(), GenericConstantVectorMaterialTempl< is_ad >::validParams(), GenericFunctionRankTwoTensorTempl< is_ad >::validParams(), InterpolatedStatefulMaterialTempl< T >::validParams(), PiecewiseLinearInterpolationMaterial::validParams(), VectorFromComponentVariablesMaterialTempl< is_ad >::validParams(), AnnularMesh::validParams(), ConcentricCircleMesh::validParams(), FileMesh::validParams(), GeneratedMesh::validParams(), PatternedMesh::validParams(), RinglebMesh::validParams(), StitchedMesh::validParams(), TiledMesh::validParams(), CylindricalGridDivision::validParams(), ExtraElementIntegerDivision::validParams(), FunctorBinnedValuesDivision::validParams(), NearestPositionsDivision::validParams(), NestedDivision::validParams(), AddMetaDataGenerator::validParams(), AdvancedExtruderGenerator::validParams(), AllSideSetsByNormalsGenerator::validParams(), AnnularMeshGenerator::validParams(), BlockToMeshConverterGenerator::validParams(), BoundaryDeletionGenerator::validParams(), BoundingBoxNodeSetGenerator::validParams(), BreakBoundaryOnSubdomainGenerator::validParams(), BreakMeshByBlockGenerator::validParams(), CartesianMeshGenerator::validParams(), CircularBoundaryCorrectionGenerator::validParams(), CombinerGenerator::validParams(), ConcentricCircleMeshGenerator::validParams(), DistributedRectilinearMeshGenerator::validParams(), ElementDeletionGeneratorBase::validParams(), ElementGenerator::validParams(), ElementSubdomainIDGenerator::validParams(), ExplodeMeshGenerator::validParams(), ExtraNodesetGenerator::validParams(), FileMeshGenerator::validParams(), FillBetweenCurvesGenerator::validParams(), FillBetweenPointVectorsGenerator::validParams(), FillBetweenSidesetsGenerator::validParams(), GeneratedMeshGenerator::validParams(), ImageSubdomainGenerator::validParams(), LowerDBlockFromSidesetGenerator::validParams(), MeshCollectionGenerator::validParams(), MeshDiagnosticsGenerator::validParams(), MeshExtruderGenerator::validParams(), MeshRepairGenerator::validParams(), MoveNodeGenerator::validParams(), NodeSetsFromSideSetsGenerator::validParams(), OrientedSubdomainBoundingBoxGenerator::validParams(), ParsedCurveGenerator::validParams(), ParsedElementDeletionGenerator::validParams(), ParsedGenerateSideset::validParams(), ParsedNodeTransformGenerator::validParams(), ParsedSubdomainMeshGenerator::validParams(), PatternedMeshGenerator::validParams(), PlaneDeletionGenerator::validParams(), PlaneIDMeshGenerator::validParams(), RefineBlockGenerator::validParams(), RefineSidesetGenerator::validParams(), RenameBlockGenerator::validParams(), RenameBoundaryGenerator::validParams(), RinglebMeshGenerator::validParams(), SideSetExtruderGenerator::validParams(), SideSetsAroundSubdomainGenerator::validParams(), SideSetsBetweenSubdomainsGenerator::validParams(), SideSetsFromBoundingBoxGenerator::validParams(), SideSetsFromNodeSetsGenerator::validParams(), SideSetsFromNormalsGenerator::validParams(), SideSetsFromPointsGenerator::validParams(), SmoothMeshGenerator::validParams(), StackGenerator::validParams(), StitchedMeshGenerator::validParams(), SubdomainBoundingBoxGenerator::validParams(), SubdomainIDGenerator::validParams(), SymmetryTransformGenerator::validParams(), TiledMeshGenerator::validParams(), TransfiniteMeshGenerator::validParams(), TransformGenerator::validParams(), UniqueExtraIDMeshGenerator::validParams(), XYDelaunayGenerator::validParams(), XYMeshLineCutter::validParams(), MultiApp::validParams(), ConstantRate::validParams(), PenaltyDirichletNodalKernel::validParams(), UserForcingFunctionNodalKernel::validParams(), PNGOutput::validParams(), BlockWeightedPartitioner::validParams(), LibmeshPartitioner::validParams(), FilePositions::validParams(), FunctorPositions::validParams(), InputPositions::validParams(), MultiAppPositions::validParams(), Positions::validParams(), ReporterPositions::validParams(), ChangeOverFixedPointPostprocessor::validParams(), ChangeOverTimePostprocessor::validParams(), ComparisonPostprocessor::validParams(), CumulativeValuePostprocessor::validParams(), DifferencePostprocessor::validParams(), ElementalVariableValue::validParams(), ElementExtremeFunctorValueTempl< is_ad >::validParams(), ElementExtremeMaterialPropertyTempl< is_ad >::validParams(), ElementH1SemiError::validParams(), ElementIntegralFunctorPostprocessorTempl< is_ad >::validParams(), ElementIntegralMaterialPropertyTempl< is_ad >::validParams(), ElementL1Error::validParams(), ElementL2Error::validParams(), ElementL2FunctorErrorTempl< is_ad >::validParams(), ElementVectorL2Error::validParams(), ElementW1pError::validParams(), FunctionElementIntegral::validParams(), FunctionValuePostprocessor::validParams(), GreaterThanLessThanPostprocessor::validParams(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::validParams(), LinearCombinationPostprocessor::validParams(), NearestNodeNumber::validParams(), NodalL2Error::validParams(), NodalVariableValue::validParams(), NumMeshDivisions::validParams(), NumPositions::validParams(), ParsedPostprocessor::validParams(), PercentChangePostprocessor::validParams(), PerfGraphData::validParams(), PointValue::validParams(), PostprocessorComparison::validParams(), PseudoTimestep::validParams(), RelativeDifferencePostprocessor::validParams(), ScalarL2Error::validParams(), ScalarVariable::validParams(), ScalePostprocessor::validParams(), SideAdvectiveFluxIntegralTempl< is_ad >::validParams(), SideIntegralFunctorPostprocessorTempl< is_ad >::validParams(), TagVectorSum::validParams(), TimeExtremeValue::validParams(), VariableResidual::validParams(), VectorPostprocessorComparison::validParams(), VectorPostprocessorComponent::validParams(), VectorPostprocessorReductionValue::validParams(), FieldSplitPreconditioner::validParams(), PhysicsBasedPreconditioner::validParams(), VariableCondensationPreconditioner::validParams(), Predictor::validParams(), DumpObjectsProblem::validParams(), AugmentSparsityOnInterface::validParams(), ProxyRelationshipManager::validParams(), RelationshipManager::validParams(), AccumulateReporter::validParams(), ExtraIDIntegralReporter::validParams(), AverageValueConstraint::validParams(), ExplicitSSPRungeKutta::validParams(), CSVFileTimes::validParams(), ExodusFileTimes::validParams(), FunctorTimes::validParams(), InputTimes::validParams(), ReporterTimes::validParams(), Times::validParams(), AB2PredictorCorrector::validParams(), ConstantDT::validParams(), CSVTimeSequenceStepper::validParams(), ExodusTimeSequenceStepper::validParams(), IterationAdaptiveDT::validParams(), PostprocessorDT::validParams(), SolutionTimeAdaptiveDT::validParams(), TestSourceStepper::validParams(), TimeSequenceFromTimes::validParams(), TimeSequenceStepper::validParams(), MultiAppCloneReporterTransfer::validParams(), MultiAppConservativeTransfer::validParams(), MultiAppCopyTransfer::validParams(), MultiAppGeneralFieldUserObjectTransfer::validParams(), MultiAppPostprocessorInterpolationTransfer::validParams(), MultiAppPostprocessorToAuxScalarTransfer::validParams(), MultiAppPostprocessorTransfer::validParams(), MultiAppReporterTransfer::validParams(), MultiAppScalarToAuxScalarTransfer::validParams(), MultiAppUserObjectTransfer::validParams(), MultiAppVariableValueSamplePostprocessorTransfer::validParams(), MultiAppVariableValueSampleTransfer::validParams(), MultiAppVectorPostprocessorTransfer::validParams(), ActivateElementsCoupled::validParams(), ActivateElementsUserObjectBase::validParams(), ElementQualityChecker::validParams(), ElemSideNeighborLayersGeomTester::validParams(), ElemSideNeighborLayersTester::validParams(), FunctionElementIntegralUserObject::validParams(), InterfaceQpMaterialPropertyBaseUserObject< T >::validParams(), JSONFileReader::validParams(), LayeredBase::validParams(), LayeredSideDiffusiveFluxAverage::validParams(), MessageFromInput::validParams(), NearestNodeNumberUO::validParams(), NodalNormalsCorner::validParams(), NodalNormalsPreprocessor::validParams(), NodalPatchRecoveryBase::validParams(), PostprocessorSpatialUserObject::validParams(), ProjectedStatefulMaterialNodalPatchRecoveryTempl< T, is_ad >::validParams(), PropertyReadFile::validParams(), RadialAverage::validParams(), SideIntegralFunctorUserObject::validParams(), SolutionUserObject::validParams(), ThresholdElementSubdomainModifier::validParams(), ConstantVectorPostprocessor::validParams(), CSVReader::validParams(), CylindricalAverage::validParams(), ElementsAlongLine::validParams(), ElementsAlongPlane::validParams(), ExtraIDIntegralVectorPostprocessor::validParams(), HistogramVectorPostprocessor::validParams(), IntersectionPointsAlongLine::validParams(), LeastSquaresFit::validParams(), LeastSquaresFitHistory::validParams(), LineFunctionSampler::validParams(), LineMaterialSamplerBase< T >::validParams(), LineValueSampler::validParams(), MaterialVectorPostprocessor::validParams(), MeshDivisionFunctorReductionVectorPostprocessor::validParams(), PointValueSampler::validParams(), PositionsFunctorValueSampler::validParams(), SamplerBase::validParams(), SpatialAverageBase::validParams(), SpatialUserObjectVectorPostprocessor::validParams(), VariableValueVolumeHistogram::validParams(), VectorOfPostprocessors::validParams(), FunctionDerivativeAux::validParams(), ChannelGradientBC::validParams(), DGDiffusionPostprocessorDirichletBC::validParams(), ExampleShapeSideIntegratedBC::validParams(), FlexiblePostprocessorDirichletBC::validParams(), InflowBC::validParams(), OutflowBC::validParams(), PostprocessorInflowBC::validParams(), VelocityFunctionOutflowBC::validParams(), VelocityFunctionTemperatureOutflowBC::validParams(), DGFunctionConvection::validParams(), DGTemperatureAdvection::validParams(), CtrlConservativeAdvection::validParams(), NonConservativeAdvection::validParams(), VelocityFunctionTemperatureAdvection::validParams(), and ChannelGradient::validParams().
addRequiredParam() [6/6]
template<typename T > void InputParameters::addRequiredParam (const std::string & name, const T & moose_enum, const std::string & doc_string)
This version of addRequiredParam is here for a consistent use with MooseEnums.
Use of this function for any other type will throw an error.
Definition at line 1392 of file InputParameters.h.
{
  mooseError("You cannot call addRequiredParam and supply a default value for this type, please "
             "use addParam instead");
}
addRequiredRangeCheckedParam()
template<typename T > void InputParameters::addRequiredRangeCheckedParam (const std::string & name, const std::string & parsed_function, const std::string & doc_string)
These methods add an range checked parameters.
A lower and upper bound can be supplied and the supplied parameter will be checked to fall within that range.
Definition at line 1440 of file InputParameters.h.
{
  addRequiredParam<T>(name, doc_string);
  _params[name]._range_function = parsed_function;
}
Referenced by PenaltyEqualValueConstraintTempl< is_ad >::validParams(), MaxIncrement::validParams(), AnnularMesh::validParams(), SpiralAnnularMesh::validParams(), CartesianGridDivision::validParams(), CylindricalGridDivision::validParams(), FunctorBinnedValuesDivision::validParams(), SphericalGridDivision::validParams(), AnnularMeshGenerator::validParams(), FillBetweenCurvesGenerator::validParams(), FillBetweenPointVectorsGenerator::validParams(), FillBetweenSidesetsGenerator::validParams(), ParsedCurveGenerator::validParams(), SphereMeshGenerator::validParams(), SpiralAnnularMeshGenerator::validParams(), PseudoTimestep::validParams(), TimeIntervalTimes::validParams(), and LogConstantDT::validParams().
allowCopy()
void InputParameters::allowCopy (bool status) inline private
Toggle the availability of the copy constructor.
When MooseObject is created via the Factory this flag is set to false, so when a MooseObject is created if the constructor is not a const reference an error is produced. This method allows the InputParameterWarehouse to disable copying.
Definition at line 1091 of file InputParameters.h.
{ _allow_copy = status; }
Referenced by ActionWarehouse::printInputFile().
applyCoupledVar()
void InputParameters::applyCoupledVar (const InputParameters & common, const std::string & var_name)
Apply properties of a single coupled variable in common, to a single coupled variable stored in this object.
Parameters
common The set of InputParameters from which to extract the coupled variable's properties
var_name The name of the coupled variable whose properties are to be applied
In order to apply the properties, both the local parameters and the common parameters must have a coupled variable with name var_name
Definition at line 886 of file InputParameters.C.
{
  // Disable the display of deprecated message when applying common parameters, this avoids a dump
  // of messages
  _show_deprecated_message = false;
  // If the local parameters has a coupled variable, populate it with the value from the common
  // parameters, if the common parameters has the coupled variable too
  if (hasCoupledValue(var_name))
  {
    if (common.hasDefaultCoupledValue(var_name))
    {
      // prepare a vector of default coupled values
      std::vector<Real> defaults(common.numberDefaultCoupledValues(var_name));
      for (unsigned int j = 0; j < common.numberDefaultCoupledValues(var_name); ++j)
        defaults[j] = common.defaultCoupledValue(var_name, j);
      addCoupledVar(var_name, defaults, common.getDocString(var_name));
    }
    else if (common.hasCoupledValue(var_name))
      addCoupledVar(var_name, common.getDocString(var_name));
  }
  // Enable deprecated message printing
  _show_deprecated_message = true;
}
Referenced by applyParameters(), and applySpecificParameters().
applyParameter()
void InputParameters::applyParameter (const InputParameters & common, const std::string & common_name, bool allow_private = false)
Apply values from a single parameter in common, to a single parameter stored in this object.
Parameters
common The set of InputParameters from which to extract parameters from
common_name The name within common from which to get the parameter values
In order to apply common parameter 4 statements must be satisfied (1) A local parameter must exist with the same name as common parameter (2) Common parameter must valid (3) Local parameter must be invalid OR not have been set from its default (4) Both cannot be private
Definition at line 913 of file InputParameters.C.
{
  // Disable the display of deprecated message when applying common parameters, this avoids a dump
  // of messages
  _show_deprecated_message = false;
  const auto local_name = checkForRename(common_name);
  // Extract the properties from the local parameter for the current common parameter name
  const bool local_exist = _values.find(local_name) != _values.end();
  const bool local_set = _params.count(local_name) > 0 && !_params[local_name]._set_by_add_param;
  const bool local_priv = allow_private ? false : isPrivate(local_name);
  const bool local_valid = isParamValid(local_name);
  // Extract the properties from the common parameter
  const bool common_exist = common._values.find(common_name) != common._values.end();
  const bool common_priv = allow_private ? false : common.isPrivate(common_name);
  const bool common_valid = common.isParamValid(common_name);
  /* In order to apply common parameter 4 statements must be satisfied
   * (1) A local parameter must exist with the same name as common parameter
   * (2) Common parameter must valid and exist
   * (3) Local parameter must be invalid OR not have been set from its default
   * (4) Both cannot be private
   */
  if (local_exist && common_exist && common_valid && (!local_valid || !local_set) &&
      (!common_priv || !local_priv))
  {
    remove(local_name);
    _values[local_name] = common._values.find(common_name)->second->clone();
    set_attributes(local_name, false);
    _params[local_name]._set_by_add_param =
        libmesh_map_find(common._params, common_name)._set_by_add_param;
  }
  // Enable deprecated message printing
  _show_deprecated_message = true;
}
Referenced by ComposeTimeStepperAction::act(), applyParameters(), and applySpecificParameters().
applyParameters()
void InputParameters::applyParameters (const InputParameters & common, std::vector< std::string > exclude = std::vector<std::string>())
Method for applying common parameters.
Parameters
common The set of parameters to apply to the parameters stored in this object
exclude A vector of parameters to exclude
In order to apply common parameter 4 statements must be satisfied (1) A local parameter must exist with the same name as common parameter (2) Common parameter must valid (3) Local parameter must be invalid OR not have been set from its default (4) Both cannot be private
Output objects have a set of common parameters that are passed down to each of the output objects created. This method is used for applying those common parameters.
See also
CommonOutputAction AddOutputAction
Definition at line 819 of file InputParameters.C.
{
  // Loop through the common parameters
  for (const auto & it : common)
  {
    // Common parameter name
    const std::string & common_name = it.first;
    // Continue to next parameter, if the current is in list of  excluded parameters
    if (std::find(exclude.begin(), exclude.end(), common_name) != exclude.end())
      continue;
    applyParameter(common, common_name);
  }
  // Loop through the coupled variables
  for (std::set<std::string>::const_iterator it = common.coupledVarsBegin();
       it != common.coupledVarsEnd();
       ++it)
  {
    // Variable name
    const std::string var_name = *it;
    // Continue to next variable, if the current is in list of  excluded parameters
    if (std::find(exclude.begin(), exclude.end(), var_name) != exclude.end())
      continue;
    applyCoupledVar(common, var_name);
  }
}
Referenced by FEProblemBase::addOutput(), and ProjectedStatefulMaterialStorageAction::processProperty().
applySpecificParameters()
void InputParameters::applySpecificParameters (const InputParameters & common, const std::vector< std::string > & include, bool allow_private = false)
Method for applying common parameters.
Parameters
common The set of parameters to apply to the parameters stored in this object
include A vector of parameters to apply
In order to apply common parameter 4 statements must be satisfied (1) A local parameter must exist with the same name as common parameter (2) Common parameter must valid (3) Local parameter must be invalid OR not have been set from its default (4) Both cannot be private
Output objects have a set of common parameters that are passed down to each of the output objects created. This method is used for applying those common parameters.
See also
CommonOutputAction AddOutputAction
Definition at line 851 of file InputParameters.C.
{
  // Loop through the common parameters
  for (const auto & it : common)
  {
    // Common parameter name
    const std::string & common_name = it.first;
    // Continue to next parameter, if the current is not in list of included parameters
    if (std::find(include.begin(), include.end(), common_name) == include.end())
      continue;
    applyParameter(common, common_name, allow_private);
  }
  // Loop through the coupled variables
  for (std::set<std::string>::const_iterator it = common.coupledVarsBegin();
       it != common.coupledVarsEnd();
       ++it)
  {
    // Variable name
    const std::string var_name = *it;
    // Continue to next variable, if the current is not in list of included parameters
    if (std::find(include.begin(), include.end(), var_name) == include.end())
      continue;
    applyCoupledVar(common, var_name);
  }
}
Referenced by AddSpecies::act(), AddVariableAction::init(), and ProjectedStatefulMaterialStorageAction::processProperty().
areAllRequiredParamsValid()
bool InputParameters::areAllRequiredParamsValid () const
This method returns true if all of the parameters in this object are valid (i.e.
isParamValid(name) == true - for all parameters)
Definition at line 405 of file InputParameters.C.
{
  for (const auto & it : *this)
    if (isParamRequired(it.first) && !isParamValid(it.first))
      return false;
  return true;
}
Referenced by ActionWarehouse::buildBuildableActions().
at() [1/2]
Metadata & InputParameters::at (const std::string & param_name) inline private
Definition at line 1067 of file InputParameters.h.
  {
    const auto param = checkForRename(param_name);
    if (_params.count(param) == 0)
      mooseError("param '", param, "' not present in InputParams");
    return _params[param];
  }
Referenced by getControllableExecuteOnTypes(), inputLocation(), and paramFullpath().
at() [2/2]
const Metadata & InputParameters::at (const std::string & param_name) const inline private
Definition at line 1074 of file InputParameters.h.
  {
    const auto param = checkForRename(param_name);
    if (_params.count(param) == 0)
      mooseError("param '", param, "' not present in InputParams");
    return _params.at(param);
  }
attemptPrintDeprecated()
bool InputParameters::attemptPrintDeprecated (const std::string & name)
Prints the deprecated parameter message, assuming we have the right flags set.
Definition at line 104 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  if (_show_deprecated_message)
  {
    auto emit_deprecation_message =
        [this](const auto & deprecated_name, const auto & deprecation_message)
    {
      // This is user-facing, no need for a backtrace
      const auto current_show_trace = Moose::show_trace;
      Moose::show_trace = false;
      moose::internal::mooseDeprecatedStream(
          Moose::out, false, true, errorPrefix(deprecated_name), ":\n", deprecation_message, "\n");
      Moose::show_trace = current_show_trace;
      return true;
    };
    if (_params.count(name) && !libmesh_map_find(_params, name)._deprecation_message.empty())
      return emit_deprecation_message(name,
                                      "The parameter '" + name + "' is deprecated.\n" +
                                          libmesh_map_find(_params, name)._deprecation_message);
    else if (auto it = _old_to_new_name_and_dep.find(name_in);
             it != _old_to_new_name_and_dep.end() && !it->second.second.empty())
      return emit_deprecation_message(name_in, it->second.second);
  }
  return false;
}
Referenced by Parser::extractParams().
blockFullpath() [1/2]
std::string & InputParameters::blockFullpath () inline
Get/set a string representing the full HIT parameter path from the input file (e.g.
"Mesh/foo") for the block containing parameters for this object.
Definition at line 829 of file InputParameters.h.
{ return _block_fullpath; }
Referenced by AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), checkParams(), MooseApp::getRenamedParam(), MooseBaseParameterInterface::getRenamedParam(), MooseObjectAction::MooseObjectAction(), and Parser::walkRaw().
blockFullpath() [2/2]
const std::string & InputParameters::blockFullpath () const inline
Definition at line 830 of file InputParameters.h.
{ return _block_fullpath; }
blockLocation() [1/2]
std::string & InputParameters::blockLocation () inline
Get/set a string representing the location (i.e.
filename,linenum) in the input text for the block containing parameters for this object.
Definition at line 820 of file InputParameters.h.
{ return _block_location; }
Referenced by checkParams(), and Parser::walkRaw().
blockLocation() [2/2]
const std::string & InputParameters::blockLocation () const inline
Definition at line 821 of file InputParameters.h.
{ return _block_location; }
callMooseErrorHelper()
void InputParameters::callMooseErrorHelper (const MooseObject & object, const std::string & error) static private
Definition at line 1429 of file InputParameters.C.
{
  object.mooseError(error);
}
Referenced by getParamHelper().
checkConsistentType()
template<typename T > void InputParameters::checkConsistentType (const std::string & name) const
This method checks to make sure that we aren't adding a parameter with the same name but a different type.
It throws a MooseError if an inconsistent type is detected. While this state is supported by libMesh it brings nothing but blood and tears for those who try ;)
Parameters
name the name of the parameter
Definition at line 1573 of file InputParameters.h.
{
  const auto name = checkForRename(name_in);
  // If we don't currently have the Parameter, can't be any inconsistency
  InputParameters::const_iterator it = _values.find(name);
  if (it == _values.end())
    return;
  // Now, if we already have the Parameter, but it doesn't have the
  // right type, throw an error.
  if (!this->Parameters::have_parameter<T>(name))
    mooseError("Attempting to set parameter \"",
               name,
               "\" with type (",
               demangle(typeid(T).name()),
               ")\nbut the parameter already exists as type (",
               it->second->type(),
               ")");
}
checkForRename()
std::string InputParameters::checkForRename (const std::string & name) const
Checks whether the provided name is a renamed parameter name.
If so we return the 'new' name. If not we return the incoming name
Parameters
name The name to check for whether it is a renamed name
Returns
The new name if the incoming name is a renamed name, else name
Definition at line 1407 of file InputParameters.C.
{
  if (auto it = _old_to_new_name_and_dep.find(name); it != _old_to_new_name_and_dep.end())
    return it->second.first;
  else
    return name;
}
Referenced by applyParameter(), at(), attemptPrintDeprecated(), checkConsistentType(), checkParams(), ScalarCoupleable::checkVar(), Coupleable::checkVar(), Coupleable::coupledComponents(), ScalarCoupleable::coupledScalarComponents(), declareControllable(), get(), getCheckedPointerParam(), getControllableExecuteOnTypes(), getDescription(), getDocString(), getGroupName(), getMooseType(), getParamHelper(), ScalarCoupleable::getScalarVar(), getSyntax(), Coupleable::getVarHelper(), getVecMooseType(), hasDefault(), have_parameter(), ignoreParameter(), isControllable(), Coupleable::isCoupled(), ScalarCoupleable::isCoupledScalar(), isParamDeprecated(), isParamRequired(), isParamSetByAddParam(), isParamSetByUser(), isParamValid(), isPrivate(), isRangeChecked(), isType(), makeParamNotRequired(), makeParamRequired(), rangeCheckedFunction(), reservedValues(), set(), set_attributes(), setDocString(), setReservedValues(), shouldIgnore(), suppressParameter(), transferParam(), and type().
checkParamName()
void InputParameters::checkParamName (const std::string & name) const private
Make sure the parameter name doesn't have any invalid characters.
Definition at line 1236 of file InputParameters.C.
{
  const static pcrecpp::RE valid("[\\w:/]+");
  if (!valid.FullMatch(name))
    mooseError("Invalid parameter name: '", name, "'");
}
Referenced by addParam(), addPrivateParam(), addRequiredParam(), and set().
checkParams()
void InputParameters::checkParams (const std::string & parsing_syntax)
This function checks parameters stored in the object to make sure they are in the correct state as the user expects: Required parameters are verified as valid meaning that they were either initialized when they were created, or were read from an input file or some other valid source.
Definition at line 553 of file InputParameters.C.
{
  std::string parampath = blockFullpath() != "" ? blockFullpath() : parsing_syntax;
  std::ostringstream oss;
  // Required parameters
  for (const auto & it : *this)
  {
    const auto param_name = checkForRename(it.first);
    if (!isParamValid(param_name) && isParamRequired(param_name))
    {
      // check if an old, deprecated name exists for this parameter that may be specified
      auto oit = _new_to_deprecated_coupled_vars.find(param_name);
      if (oit != _new_to_deprecated_coupled_vars.end() && isParamValid(oit->second))
        continue;
      oss << blockLocation() << ": missing required parameter '" << parampath + "/" + param_name
          << "'\n";
      oss << "\tDoc String: \"" + getDocString(param_name) + "\"" << std::endl;
    }
  }
  // Range checked parameters
  for (const auto & it : *this)
  {
    std::string long_name(parampath + "/" + it.first);
    dynamicCastRangeCheck(Real, Real, long_name, it.first, it.second, oss);
    dynamicCastRangeCheck(int, long, long_name, it.first, it.second, oss);
    dynamicCastRangeCheck(long, long, long_name, it.first, it.second, oss);
    dynamicCastRangeCheck(unsigned int, long, long_name, it.first, it.second, oss);
  }
  // Controllable parameters
  for (const auto & param_name : getControllableParameters())
  {
    if (isPrivate(param_name))
      oss << inputLocation(param_name) << ": private parameter '" << paramFullpath(param_name)
          << "' marked controllable";
    checkMooseType(NonlinearVariableName, param_name);
    checkMooseType(AuxVariableName, param_name);
    checkMooseType(VariableName, param_name);
    checkMooseType(BoundaryName, param_name);
    checkMooseType(SubdomainName, param_name);
    checkMooseType(PostprocessorName, param_name);
    checkMooseType(VectorPostprocessorName, param_name);
    checkMooseType(UserObjectName, param_name);
    checkMooseType(MaterialPropertyName, param_name);
  }
  if (!oss.str().empty())
    mooseError(oss.str());
}
Referenced by FEProblemBase::addFVInitialCondition(), FEProblemBase::addInitialCondition(), ActionFactory::create(), Factory::create(), and AppFactory::createShared().
clear()
void InputParameters::clear () override virtual
Definition at line 59 of file InputParameters.C.
{
  Parameters::clear();
  _params.clear();
  _coupled_vars.clear();
  _new_to_deprecated_coupled_vars.clear();
  _collapse_nesting = false;
  _moose_object_syntax_visibility = true;
  _show_deprecated_message = true;
  _allow_copy = true;
  _block_fullpath = "";
  _block_location = "";
  _old_to_new_name_and_dep.clear();
  _new_to_old_names.clear();
}
clearRelationshipManagers()
void InputParameters::clearRelationshipManagers () inline
Clears all currently registered RelationshipManagers.
Definition at line 552 of file InputParameters.h.
{ _buildable_rm_types.clear(); }
Referenced by ElemSideNeighborLayersGeomTester::validParams().
collapseSyntaxNesting() [1/2]
bool InputParameters::collapseSyntaxNesting () const
Definition at line 516 of file InputParameters.C.
{
  return _collapse_nesting;
}
collapseSyntaxNesting() [2/2]
void InputParameters::collapseSyntaxNesting (bool collapse)
Mutators for controlling whether or not the outermost level of syntax will be collapsed when printed.
Definition at line 510 of file InputParameters.C.
{
  _collapse_nesting = collapse;
}
Referenced by Parser::buildFullTree(), and Parser::buildJsonSyntaxTree().
coupledVarsBegin()
std::set< std::string >::const_iterator InputParameters::coupledVarsBegin () const inline
Methods returning iterators to the coupled variables names stored in this InputParameters object.
Definition at line 607 of file InputParameters.h.
  {
    return _coupled_vars.begin();
  }
Referenced by applyParameters(), applySpecificParameters(), Coupleable::Coupleable(), LazyCoupleable::LazyCoupleable(), and ScalarCoupleable::ScalarCoupleable().
coupledVarsEnd()
std::set< std::string >::const_iterator InputParameters::coupledVarsEnd () const inline
Definition at line 611 of file InputParameters.h.
  {
    return _coupled_vars.end();
  }
Referenced by applyParameters(), applySpecificParameters(), Coupleable::Coupleable(), LazyCoupleable::LazyCoupleable(), and ScalarCoupleable::ScalarCoupleable().
declareControllable()
void InputParameters::declareControllable (const std::string & name, std::set< ExecFlagType > execute_flags = {})
Declare the given parameters as controllable.
Definition at line 421 of file InputParameters.C.
{
  std::vector<std::string> names;
  MooseUtils::tokenize<std::string>(input_names, names, 1, " ");
  for (auto & name_in : names)
  {
    const auto name = checkForRename(name_in);
    auto map_iter = _params.find(name);
    if (map_iter != _params.end()) // error is handled by checkParams method
    {
      map_iter->second._controllable = true;
      map_iter->second._controllable_flags = execute_flags;
    }
    else
      mooseError("The input parameter '",
                 name,
                 "' does not exist, thus cannot be marked as controllable.");
  }
}
Referenced by AuxKernelTempl< ComputeValueType >::validParams(), AuxScalarKernel::validParams(), ConstantAux::validParams(), ConstantScalarAux::validParams(), ADDirichletBC::validParams(), ADPenaltyDirichletBC::validParams(), ArrayDirichletBC::validParams(), DirichletBC::validParams(), NeumannBCTempl< is_ad >::validParams(), PenaltyDirichletBC::validParams(), VectorDirichletBC::validParams(), Damper::validParams(), ConstantPointSource::validParams(), DiracKernelBase::validParams(), VectorConstantPointSource::validParams(), ConstantFunction::validParams(), PiecewiseTabularBase::validParams(), FVBoundaryCondition::validParams(), FVInterfaceKernel::validParams(), FVBodyForce::validParams(), InterfaceKernelBase::validParams(), BodyForceTempl< is_ad >::validParams(), ReactionTempl< is_ad >::validParams(), VectorBodyForce::validParams(), GenericConstant2DArray::validParams(), GenericConstantArray::validParams(), GenericConstantMaterialTempl< is_ad >::validParams(), GenericConstantVectorMaterialTempl< is_ad >::validParams(), MaterialBase::validParams(), PiecewiseLinearInterpolationMaterial::validParams(), MultiApp::validParams(), ConstantRate::validParams(), PenaltyDirichletNodalKernel::validParams(), Output::validParams(), ConstantPostprocessor::validParams(), FunctionValuePostprocessor::validParams(), FEProblemBase::validParams(), IterationAdaptiveDT::validParams(), TimeStepper::validParams(), Transfer::validParams(), UserObject::validParams(), PostprocessorInflowBC::validParams(), InterTemperatureAdvection::validParams(), and CtrlConservativeAdvection::validParams().
defaultCoupledValue() [1/2]
void InputParameters::defaultCoupledValue (const std::string & coupling_name, Real value, unsigned int i = 0)
Set the default value for an optionally coupled variable (called by the Parser).
Parameters
coupling_name The name of the coupling parameter to get the default value for.
value Default value to set.
i By default 0, in general the index of the requested coupled default value.
Definition at line 650 of file InputParameters.C.
{
  _params[coupling_name]._coupled_default.resize(i + 1);
  _params[coupling_name]._coupled_default[i] = value;
  _params[coupling_name]._have_coupled_default = true;
}
defaultCoupledValue() [2/2]
Real InputParameters::defaultCoupledValue (const std::string & coupling_name, unsigned int i = 0) const
Get the default value for an optionally coupled variable.
Parameters
coupling_name The name of the coupling parameter to get the default value for.
i By default 0, in general the index of the requested coupled default value.
Definition at line 658 of file InputParameters.C.
{
  auto value_it = _params.find(coupling_name);
  if (value_it == _params.end() || !value_it->second._have_coupled_default)
    mooseError("Attempted to retrieve default value for coupled variable '",
               coupling_name,
               "' when none was provided. \n\nThere are three reasons why this may have "
               "occurred:\n 1. The other version of params.addCoupledVar() should be used in order "
               "to provide a default value. \n 2. This should have been a required coupled "
               "variable added with params.addRequiredCoupledVar() \n 3. The call to get the "
               "coupled value should have been properly guarded with isCoupled()\n");
  return value_it->second._coupled_default.at(i);
}
Referenced by MooseServer::addParametersToList(), applyCoupledVar(), Coupleable::getADDefaultValue(), ScalarCoupleable::getADDefaultValue(), Coupleable::getADDefaultVectorValue(), Coupleable::getDefaultArrayValue(), ScalarCoupleable::getDefaultValue(), Coupleable::getDefaultValue(), Coupleable::getDefaultVectorValue(), InputFileFormatter::printParams(), YAMLFormatter::printParams(), JsonSyntaxTree::setParams(), Parser::setVectorParameter(), and transferParam().
deprecateCoupledVar()
void InputParameters::deprecateCoupledVar (const std::string & old_name, const std::string & new_name, const std::string & removal_date)
Definition at line 1399 of file InputParameters.C.
{
  renameCoupledVarInternal(old_name, new_name, "", removal_date);
}
Referenced by ParsedAux::validParams(), MaterialDerivativeTestKernelBase< T >::validParams(), CompositeTensorBase< T, U >::validParams(), DerivativeSumMaterialTempl< is_ad >::validParams(), ParsedMaterialBase::validParams(), and ParsedODEKernel::validParams().
deprecateParam()
void InputParameters::deprecateParam (const std::string & old_name, const std::string & new_name, const std::string & removal_date)
Definition at line 1391 of file InputParameters.C.
{
  renameParamInternal(old_name, new_name, "", removal_date);
}
Referenced by ParsedAux::validParams(), PicardSolve::validParams(), and ParsedODEKernel::validParams().
errorPrefix()
std::string InputParameters::errorPrefix (const std::string & param) const
generate error message prefix with parameter name and location (if available)
Definition at line 1283 of file InputParameters.C.
{
  auto prefix = param + ":";
  if (!inputLocation(param).empty())
    prefix = inputLocation(param) + ": (" + paramFullpath(param) + ")";
  return prefix;
}
Referenced by attemptPrintDeprecated(), get(), and paramErrorPrefix().
get() [1/2]
template<typename R1 , typename R2 , typename V1 , typename V2 > std::vector< std::pair< R1, R2 > > InputParameters::get (const std::string & param1, const std::string & param2) const
Combine two vector parameters into a single vector of pairs.
Definition at line 1801 of file InputParameters.h.
{
  const auto param1 = checkForRename(param1_in);
  const auto param2 = checkForRename(param2_in);
  const auto & v1 = get<V1>(param1);
  const auto & v2 = get<V2>(param2);
  auto controllable = getControllableParameters();
  if (controllable.count(param1) || controllable.count(param2))
    mooseError(errorPrefix(param1),
               " and/or ",
               errorPrefix(param2) +
                   " are controllable parameters and cannot be retireved using "
                   "the MooseObject::getParam/InputParameters::get methods for pairs");
  if (v1.size() != v2.size())
    mooseError("Vector parameters ",
               errorPrefix(param1),
               "(size: ",
               v1.size(),
               ") and " + errorPrefix(param2),
               "(size: ",
               v2.size(),
               ") are of different lengths \n");
  std::vector<std::pair<R1, R2>> parameter_pairs;
  auto i1 = v1.begin();
  auto i2 = v2.begin();
  for (; i1 != v1.end() && i2 != v2.end(); ++i1, ++i2)
    parameter_pairs.emplace_back(std::make_pair(*i1, *i2));
  return parameter_pairs;
}
Referenced by ElementIDOutputAction::act(), AddMaterialAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SplitMeshAction::act(), ActionWarehouse::addActionBlock(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), FEProblemBase::addAuxVariable(), FEProblemBase::addBoundaryCondition(), NonlinearSystemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDGKernel(), NonlinearSystemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FunctorMaterial::addFunctorPropertyByBlocks(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addKernel(), AuxiliarySystem::addKernel(), MooseEigenSystem::addKernel(), NonlinearSystemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), NonlinearSystemBase::addNodalKernel(), MooseObjectWarehouseBase< T >::addObject(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), JsonSyntaxTree::addParameters(), MooseServer::addParametersToList(), MooseObjectAction::addRelationshipManagers(), FEProblemBase::addScalarKernel(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), MooseServer::addValuesToList(), AddVariableAction::addVariable(), AuxiliarySystem::addVariable(), SystemBase::addVariable(), FEProblemBase::addVariable(), FVFluxKernel::adjustRMGhostLayers(), Moose::assemble_matrix(), AuxScalarKernel::AuxScalarKernel(), BoundsAuxBase::BoundsAuxBase(), Parser::buildFullTree(), Parser::buildJsonSyntaxTree(), PostprocessorInterface::checkParam(), Moose::SlepcSupport::clearFreeNonlinearPowerIterations(), Moose::compute_bounds(), Moose::compute_jacobian(), Moose::compute_nearnullspace(), Moose::compute_nullspace(), Moose::compute_postcheck(), Moose::compute_transpose_nullspace(), ADMortarScalarBase::computeResidual(), MooseBaseParameterInterface::connectControllableParams(), Coupleable::coupledMatrixTagValue(), Coupleable::coupledMatrixTagValues(), PostprocessorInterface::coupledPostprocessors(), Coupleable::coupledVectorTagArrayGradient(), Coupleable::coupledVectorTagArrayGradients(), Coupleable::coupledVectorTagArrayValues(), Coupleable::coupledVectorTagDofValues(), Coupleable::coupledVectorTagGradient(), Coupleable::coupledVectorTagGradients(), Coupleable::coupledVectorTagValues(), ActionFactory::create(), AddVariableAction::createInitialConditionAction(), AppFactory::createShared(), MaterialBase::declareADProperty(), MaterialBase::declareProperty(), Postprocessor::declareValue(), FunctorInterface::deduceFunctorName(), Parser::extractParams(), AddVariableAction::feType(), FileRangeBuilder::FileRangeBuilder(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), GapValueAux::GapValueAux(), ParsedSubdomainMeshGenerator::generate(), MooseServer::getActionParameters(), MooseApp::getCheckpointDirectories(), DistributionInterface::getDistribution(), ElementIDInterface::getElementID(), ElementIDInterface::getElementIDByName(), ElementIDInterface::getElementIDIndex(), ElementIDInterface::getElementIDNeighbor(), ElementIDInterface::getElementIDNeighborByName(), FunctionInterface::getFunction(), MaterialBase::getGenericZeroMaterialProperty(), MaterialPropertyInterface::getMaterial(), MaterialPropertyInterface::getMaterialDataType(), MaterialPropertyInterface::getMaterialPropertyName(), MooseServer::getObjectParameters(), MooseBaseParameterInterface::getParam(), getParamHelper(), PostprocessorInterface::getPostprocessorNameInternal(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), SamplerInterface::getSampler(), AddVariableAction::getSubdomainIDs(), CommonOutputAction::hasConsole(), FunctionInterface::hasFunction(), ImageSampler::ImageSampler(), AddVariableAction::init(), FullSolveMultiApp::initialSetup(), FEProblemBase::initNullSpaceVectors(), isParamValid(), isValid(), IterationAdaptiveDT::IterationAdaptiveDT(), LayeredBase::LayeredBase(), SetupMeshAction::modifyParamsForUseSplit(), MooseApp::MooseApp(), MooseVariableInterface< T >::MooseVariableInterface(), NodeFaceConstraint::NodeFaceConstraint(), operator=(), OrientedBoxInterface::OrientedBoxInterface(), OutputInterface::OutputInterface(), ConsoleUtils::outputLegacyInformation(), ParsedMaterialBase::ParsedMaterialBase(), PenetrationAux::PenetrationAux(), InputFileFormatter::printParams(), YAMLFormatter::printParams(), ProjectedStatefulMaterialStorageAction::ProjectedStatefulMaterialStorageAction(), MultiAppProjectionTransfer::projectSolution(), ReferenceResidualProblem::ReferenceResidualProblem(), InputParameterWarehouse::removeInputParameters(), OutputWarehouse::resetFileBase(), Moose::SlepcSupport::setEigenProblemSolverParams(), Moose::SlepcSupport::setNewtonPetscOptions(), MooseMesh::setPartitioner(), FVKernel::setRMParams(), Moose::SlepcSupport::setSlepcEigenSolverTolerances(), CreateExecutionerAction::setupAutoPreconditioning(), ReadExecutorParamsAction::setupAutoPreconditioning(), MeshBaseImageSampler::setupImageSampler(), ImageSampler::setupImageSampler(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), Reporter::store(), Moose::PetscSupport::storePetscOptions(), Moose::SlepcSupport::storeSolveType(), DumpObjectsProblem::stringifyParameters(), TaggingInterface::TaggingInterface(), transferParam(), MooseBaseParameterInterface::uniqueName(), MooseBaseParameterInterface::uniqueParameterName(), AuxKernelTempl< Real >::uOld(), FunctorElementalGradientAuxTempl< is_ad >::validParams(), ProjectionAux::validParams(), FVFunctorDirichletBCTempl< is_ad >::validParams(), FVInterfaceKernel::validParams(), FVKernel::validParams(), MortarConsumerInterface::validParams(), DistributedRectilinearMeshGenerator::validParams(), ElemSideNeighborLayersGeomTester::validParams(), ElemSideNeighborLayersTester::validParams(), NearestRadiusLayeredAverage::validParams(), Coupleable::vectorTagDofValueHelper(), Coupleable::vectorTagValueHelper(), MeshBaseImageSampler::vtkFlip(), ImageSampler::vtkShiftAndScale(), MeshBaseImageSampler::vtkShiftAndScale(), ImageSampler::vtkThreshold(), MeshBaseImageSampler::vtkThreshold(), and Parser::walkRaw().
get() [2/2]
template<typename T > const T & InputParameters::get (std::string_view name) const
A wrapper around the Parameters base class method.
Checks for parameter rename before calling the base class method
Parameters
name The name to query the parameter values map with
Returns
The parameter value corresponding to the (possibly renamed) name
Definition at line 1850 of file InputParameters.h.
{
  const auto name = checkForRename(std::string(name_in));
  return Parameters::get<T>(name);
}
getAutoBuildVectors()
std::map< std::string, std::pair< std::string, std::string > > InputParameters::getAutoBuildVectors () const
Returns the auto build vectors for all parameters.
Definition at line 686 of file InputParameters.C.
{
  std::map<std::string, std::pair<std::string, std::string>> abv;
  for (auto it = _params.begin(); it != _params.end(); ++it)
  {
    if (!it->second._autobuild_vecs.first.empty())
      abv[it->first] = it->second._autobuild_vecs;
  }
  return abv;
}
Referenced by Parser::extractParams().
getBuildableRelationshipManagerTypes()
const std::vector< std::tuple< std::string, Moose::RelationshipManagerType, Moose::RelationshipManagerInputParameterCallback > > & InputParameters::getBuildableRelationshipManagerTypes () const
Returns the list of buildable (or required) RelationshipManager object types for this object.
Definition at line 504 of file InputParameters.C.
{
  return _buildable_rm_types;
}
Referenced by Action::addRelationshipManagers().
getBuildableTypes()
const std::vector< std::string > & InputParameters::getBuildableTypes () const
Returns the list of buildable types as a std::vector<std::string>
Definition at line 496 of file InputParameters.C.
{
  return _buildable_types;
}
Referenced by Parser::buildFullTree(), and Parser::buildJsonSyntaxTree().
getCheckedPointerParam()
template<typename T > T InputParameters::getCheckedPointerParam (const std::string & name, const std::string & error_string = "") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
The template parameter must be a pointer or an error will be thrown.
Definition at line 1363 of file InputParameters.h.
{
  const auto name = checkForRename(name_in);
  T param = this->get<T>(name);
  // Note: You will receive a compile error on this line if you attempt to pass a non-pointer
  // template type to this method
  if (param == NULL)
    mooseError("Parameter ", name, " is NULL.\n", error_string);
  return this->get<T>(name);
}
Referenced by Coupleable::Coupleable(), Postprocessor::declareValue(), MooseBaseParameterInterface::getCheckedPointerParam(), ElementIDInterface::getElementID(), ElementIDInterface::getElementIDByName(), ElementIDInterface::getElementIDNeighbor(), ElementIDInterface::getElementIDNeighborByName(), MooseVariableInterface< T >::MooseVariableInterface(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), ScalarCoupleable::ScalarCoupleable(), and TaggingInterface::TaggingInterface().
getClassDescription()
std::string InputParameters::getClassDescription () const
Returns the class description.
Definition at line 133 of file InputParameters.C.
{
  return _class_description;
}
Referenced by JsonSyntaxTree::addParameters(), and MooseServer::addValuesToList().
getControllableExecuteOnTypes()
const std::set< ExecFlagType > & InputParameters::getControllableExecuteOnTypes (const std::string & name) const
Return the allowed execute flags for a controllable parameter.
Definition at line 450 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  return at(name)._controllable_flags;
}
getControllableParameters()
std::set< std::string > InputParameters::getControllableParameters () const
Return list of controllable parameters.
Definition at line 1273 of file InputParameters.C.
{
  std::set<std::string> controllable;
  for (auto it = _params.begin(); it != _params.end(); ++it)
    if (it->second._controllable)
      controllable.emplace(it->first);
  return controllable;
}
Referenced by checkParams(), and get().
getCoupledVariableParamNames()
const std::set< std::string > & InputParameters::getCoupledVariableParamNames () const inline
Return the coupled variable parameter names.
Definition at line 619 of file InputParameters.h.
{ return _coupled_vars; }
getDescription()
const std::string & InputParameters::getDescription (const std::string & name) const
Get the documentation string for a parameter.
Definition at line 977 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  auto it = _params.find(name);
  if (it == _params.end())
    mooseError("No parameter exists with the name ", name);
  return it->second._doc_string;
}
Referenced by transferParam().
getDocString()
std::string InputParameters::getDocString (const std::string & name) const
Returns the documentation string for the specified parameter name.
Definition at line 320 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  std::string doc_string;
  auto it = _params.find(name);
  if (it != _params.end())
    for (const auto & ch : it->second._doc_string)
    {
      if (ch == '\n')
        doc_string += " ... ";
      else
        doc_string += ch;
    }
  return doc_string;
}
Referenced by CommandLine::addCommandLineOptionsFromParams(), MooseServer::addParametersToList(), applyCoupledVar(), checkParams(), CommandLine::populateInputParams(), InputFileFormatter::printParams(), YAMLFormatter::printParams(), and JsonSyntaxTree::setParams().
getGroupName()
std::string InputParameters::getGroupName (const std::string & param_name) const
This method retrieves the group name for the passed parameter name if one exists.
Otherwise an empty string is returned.
Definition at line 809 of file InputParameters.C.
{
  const auto param_name = checkForRename(param_name_in);
  auto it = _params.find(param_name);
  if (it != _params.end())
    return it->second._group;
  return std::string();
}
Referenced by InputFileFormatter::printParams(), YAMLFormatter::printParams(), and JsonSyntaxTree::setParams().
getGroupParameters()
std::set< std::string > InputParameters::getGroupParameters (const std::string & group) const
Return names of parameters within a group.
Definition at line 1254 of file InputParameters.C.
{
  std::set<std::string> names;
  for (auto it = _params.begin(); it != _params.end(); ++it)
    if (it->second._group == group)
      names.emplace(it->first);
  return names;
}
getMooseType()
std::string InputParameters::getMooseType (const std::string & name) const
Utility functions for retrieving one of the MooseTypes variables into the common "string" base class.
Scalar and Vector versions are supplied
Definition at line 712 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  std::string var;
  if (have_parameter<VariableName>(name))
    var = get<VariableName>(name);
  else if (have_parameter<NonlinearVariableName>(name))
    var = get<NonlinearVariableName>(name);
  else if (have_parameter<AuxVariableName>(name))
    var = get<AuxVariableName>(name);
  else if (have_parameter<PostprocessorName>(name))
    var = get<PostprocessorName>(name);
  else if (have_parameter<VectorPostprocessorName>(name))
    var = get<VectorPostprocessorName>(name);
  else if (have_parameter<FunctionName>(name))
    var = get<FunctionName>(name);
  else if (have_parameter<UserObjectName>(name))
    var = get<UserObjectName>(name);
  else if (have_parameter<MaterialPropertyName>(name))
    var = get<MaterialPropertyName>(name);
  else if (have_parameter<std::string>(name))
    var = get<std::string>(name);
  return var;
}
Referenced by MooseObjectWarehouseBase< T >::addObject(), BlockRestrictable::initializeBlockRestrictable(), isValid(), and varName().
getNewToDeprecatedVarMap()
const std::unordered_map< std::string, std::string > & InputParameters::getNewToDeprecatedVarMap () const inline
Return the new to deprecated variable name map.
Definition at line 624 of file InputParameters.h.
  {
    return _new_to_deprecated_coupled_vars;
  }
getParametersList()
std::set< std::string > InputParameters::getParametersList () const
Returns
list of all parameters
Definition at line 1264 of file InputParameters.C.
{
  std::set<std::string> param_set;
  for (auto it = _params.begin(); it != _params.end(); ++it)
    param_set.emplace(it->first);
  return param_set;
}
getParamHelper() [1/5]
template<> const MooseEnum & InputParameters::getParamHelper (const std::string & name, const InputParameters & pars, const MooseEnum * , const MooseObject * moose_object) static
getParamHelper() [2/5]
template<> const MultiMooseEnum & InputParameters::getParamHelper (const std::string & name, const InputParameters & pars, const MultiMooseEnum * , const MooseObject * moose_object) static
getParamHelper() [3/5]
template<typename T > const T & InputParameters::getParamHelper (const std::string & name, const InputParameters & pars, const T * the_type, const MooseObject * moose_object = nullptr) static
Definition at line 1762 of file InputParameters.h.
{
  const auto name = pars.checkForRename(name_in);
  if (!pars.isParamValid(name))
  {
    std::stringstream err;
    err << "The parameter \"" << name << "\" is being retrieved before being set.";
    if (moose_object)
      callMooseErrorHelper(*moose_object, err.str());
    else
      mooseError(err.str());
  }
  return pars.get<T>(name);
}
Referenced by MooseApp::getParam(), MooseBaseParameterInterface::getParam(), MooseApp::getRenamedParam(), and MooseBaseParameterInterface::getRenamedParam().
getParamHelper() [4/5]
template<> const MooseEnum & InputParameters::getParamHelper (const std::string & name_in, const InputParameters & pars, const MooseEnum * , const MooseObject *) static
Definition at line 1196 of file InputParameters.C.
{
  const auto name = pars.checkForRename(name_in);
  return pars.get<MooseEnum>(name);
}
getParamHelper() [5/5]
template<> const MultiMooseEnum & InputParameters::getParamHelper (const std::string & name_in, const InputParameters & pars, const MultiMooseEnum * , const MooseObject *) static
Definition at line 1207 of file InputParameters.C.
{
  const auto name = pars.checkForRename(name_in);
  return pars.get<MultiMooseEnum>(name);
}
getSyntax()
std::vector< std::string > InputParameters::getSyntax (const std::string & name) const
Get the syntax for a command-line parameter.
Definition at line 799 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  auto it = _params.find(name);
  if (it == _params.end())
    mooseError("No parameter exists with the name ", name);
  return it->second._cli_flag_names;
}
Referenced by CommandLine::addCommandLineOptionsFromParams(), MooseApp::copyInputs(), and MooseApp::showInputs().
getSystemAttributeName()
const std::string & InputParameters::getSystemAttributeName () const
Get the system attribute name if it was registered.
Otherwise throw an error. See the AttribSystem object for use Attribute.h/C.
Definition at line 471 of file InputParameters.C.
{
  mooseAssert(have_parameter<std::string>("_moose_warehouse_system_name"),
              "SystemAttributeName is not available! Call 'registerSystemAttributeName' (usually "
              "in the validParams function) before you try accessing it!");
  return Parameters::get<std::string>("_moose_warehouse_system_name");
}
Referenced by AttribSystem::initFrom().
getVecMooseType()
std::vector< std::string > InputParameters::getVecMooseType (const std::string & name) const
Definition at line 740 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  std::vector<std::string> svars;
  if (have_parameter<std::vector<VariableName>>(name))
  {
    std::vector<VariableName> vars = get<std::vector<VariableName>>(name);
    std::copy(vars.begin(), vars.end(), std::back_inserter(svars));
  }
  else if (have_parameter<std::vector<NonlinearVariableName>>(name))
  {
    std::vector<NonlinearVariableName> vars = get<std::vector<NonlinearVariableName>>(name);
    std::copy(vars.begin(), vars.end(), std::back_inserter(svars));
  }
  else if (have_parameter<std::vector<AuxVariableName>>(name))
  {
    std::vector<AuxVariableName> vars = get<std::vector<AuxVariableName>>(name);
    std::copy(vars.begin(), vars.end(), std::back_inserter(svars));
  }
  else if (have_parameter<std::vector<MaterialPropertyName>>(name))
  {
    std::vector<MaterialPropertyName> vars = get<std::vector<MaterialPropertyName>>(name);
    std::copy(vars.begin(), vars.end(), std::back_inserter(svars));
  }
  else if (have_parameter<std::vector<std::string>>(name))
  {
    std::vector<std::string> vars = get<std::vector<std::string>>(name);
    std::copy(vars.begin(), vars.end(), std::back_inserter(svars));
  }
  return svars;
}
Referenced by MooseObjectWarehouseBase< T >::addObject(), Coupleable::Coupleable(), isValid(), ScalarCoupleable::ScalarCoupleable(), and varName().
hasCoupledValue()
bool InputParameters::hasCoupledValue (const std::string & coupling_name) const
Return whether or not the coupled variable exists.
Parameters
coupling_name The name of the coupled variable to test for
Returns
True if the variable exists in the coupled variables for this InputParameters object
Definition at line 637 of file InputParameters.C.
{
  return _coupled_vars.find(coupling_name) != _coupled_vars.end();
}
Referenced by applyCoupledVar(), Coupleable::isCoupled(), ScalarCoupleable::isCoupledScalar(), and transferParam().
hasDefault()
bool InputParameters::hasDefault (const std::string & param_name) const
Return whether a parameter has a default.
Definition at line 622 of file InputParameters.C.
{
  const auto name = checkForRename(param_name);
  if (hasDefaultCoupledValue(name))
    return true;
  // If it has a default, it's already valid
  else if (isParamSetByAddParam(name))
    return true;
  else if (isParamValid(name))
    mooseError("No way to know if the parameter", param_name, "has a default");
  else
    return false;
}
Referenced by transferParam().
hasDefaultCoupledValue()
bool InputParameters::hasDefaultCoupledValue (const std::string & coupling_name) const
Return whether or not the requested parameter has a default coupled value.
Parameters
coupling_name The name of the coupling parameter to get the default value for.
Definition at line 643 of file InputParameters.C.
{
  return _params.count(coupling_name) > 0 && _params.at(coupling_name)._have_coupled_default &&
         _coupled_vars.count(coupling_name) > 0;
}
Referenced by MooseServer::addParametersToList(), applyCoupledVar(), Coupleable::coupledComponents(), hasDefault(), Coupleable::isCoupledConstant(), InputFileFormatter::printParams(), YAMLFormatter::printParams(), JsonSyntaxTree::setParams(), and transferParam().
have_parameter()
template<typename T > bool InputParameters::have_parameter (std::string_view name) const
A wrapper around the Parameters base class method.
Checks for parameter rename before calling the base class method
Parameters
name The name to query the parameter values map with
Returns
Whether there is a key in the parameter values map corresponding to the (possibly renamed) name
Definition at line 1859 of file InputParameters.h.
{
  const auto name = checkForRename(std::string(name_in));
  return Parameters::have_parameter<T>(name);
}
Referenced by ActionWarehouse::addActionBlock(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), FEProblemBase::addBoundaryCondition(), CommandLine::addCommandLineOptionsFromParams(), FEProblemBase::addConstraint(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FunctorMaterial::addFunctorPropertyByBlocks(), FEProblemBase::addIndicator(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addKernel(), MooseEigenSystem::addKernel(), FEProblemBase::addMarker(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObjectParamsHelper(), MooseServer::addParametersToList(), FEProblemBase::addScalarKernel(), FEProblemBase::addTransfer(), MooseServer::addValuesToList(), Parser::buildFullTree(), Parser::buildJsonSyntaxTree(), Coupleable::checkVar(), MaterialBase::declareADProperty(), MaterialBase::declareProperty(), FunctorInterface::deduceFunctorName(), MooseServer::getActionParameters(), MooseServer::getCompletionItemKind(), MaterialBase::getGenericZeroMaterialProperty(), MaterialPropertyInterface::getMaterialPropertyName(), MooseServer::getObjectParameters(), getVecMooseType(), AdvancedOutput::initExecutionTypes(), AttribDisplaced::initFrom(), isParamValid(), MooseApp::MooseApp(), OutputOnWarehouse::OutputOnWarehouse(), CommandLine::populateInputParams(), InputFileFormatter::printParams(), YAMLFormatter::printParams(), DumpObjectsProblem::stringifyParameters(), transferParam(), BlockRestrictable::validParams(), and Parser::walkRaw().
ignoreParameter()
template<typename T > void InputParameters::ignoreParameter (const std::string & name)
Informs this object that values for this parameter set from the input file or from the command line should be ignored.
Definition at line 1610 of file InputParameters.h.
{
  const auto name = checkForRename(name_in);
  suppressParameter<T>(name);
  _params[name]._ignore = true;
}
Referenced by AddElementalFieldAction::validParams().
inputLocation() [1/2]
std::string & InputParameters::inputLocation (const std::string & param) inline
Definition at line 842 of file InputParameters.h.
{ return at(param)._input_location; }
inputLocation() [2/2]
const std::string & InputParameters::inputLocation (const std::string & param) const inline
Get/set a string representing the location in the input text the parameter originated from (i.e.
filename,linenum) for the given param.
Definition at line 838 of file InputParameters.h.
  {
    return at(param)._input_location;
  }
Referenced by checkParams(), errorPrefix(), Parser::extractParams(), and MooseBaseParameterInterface::paramErrorMsg().
isControllable()
bool InputParameters::isControllable (const std::string & name) const
Returns a Boolean indicating whether the specified parameter is controllable.
Definition at line 443 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  return _params.count(name) > 0 && _params.at(name)._controllable;
}
Referenced by JsonSyntaxTree::setParams(), and transferParam().
isParamDeprecated()
bool InputParameters::isParamDeprecated (const std::string & name) const
Returns True if the parameters is deprecated.
Definition at line 398 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  return _params.count(name) > 0 && !_params.at(name)._deprecation_message.empty();
}
Referenced by MooseServer::addParametersToList(), and JsonSyntaxTree::setParams().
isParamRequired()
bool InputParameters::isParamRequired (const std::string & name) const
Returns a boolean indicating whether the specified parameter is required or not.
Definition at line 352 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  return _params.count(name) > 0 && _params.at(name)._required;
}
Referenced by areAllRequiredParamsValid(), checkParams(), MooseServer::getCompletionItemKind(), CommandLine::populateInputParams(), InputFileFormatter::printParams(), YAMLFormatter::printParams(), JsonSyntaxTree::setParams(), and transferParam().
isParamSetByAddParam()
bool InputParameters::isParamSetByAddParam (const std::string & name) const
Returns whether or not the parameter was set due to addParam.
If not then it was either set programmatically or was read through the input file.
Definition at line 391 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  return _params.count(name) > 0 && _params.at(name)._set_by_add_param;
}
Referenced by MultiApp::createApp(), hasDefault(), MooseApp::MooseApp(), and Transient::Transient().
isParamSetByUser()
bool InputParameters::isParamSetByUser (const std::string & name) const
Method returns true if the parameter was by the user.
Parameters
name The parameter name
Definition at line 963 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  if (!isParamValid(name))
    // if the parameter is invalid, it is for sure not set by the user
    return false;
  else
    // If the parameters is not located in the list, then it was set by the user
    // If the parameter is private, and present in global params, it is ignored, therefore not set
    return _params.count(name) > 0 && !_params.at(name)._set_by_add_param &&
           !_params.at(name)._is_private;
}
Referenced by CreateProblemAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SystemBase::addVariable(), ADVectorFunctionDirichletBC::ADVectorFunctionDirichletBC(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), PiecewiseTabularBase::buildFromFile(), PNGOutput::calculateRescalingValues(), Console::Console(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), ElectronsFromIonization::ElectronsFromIonization(), Executor::Executor(), Exodus::Exodus(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FileMeshGenerator::generate(), AddVariableAction::init(), Console::initialSetup(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), MooseApp::isParamSetByUser(), MooseBaseParameterInterface::isParamSetByUser(), MultiApp::keepSolutionDuringRestore(), LayeredBase::LayeredBase(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MultiApp::MultiApp(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NearestPointBase< UserObjectType, BaseType >::NearestPointBase(), paramSetByUser(), PatchMeshGenerator::PatchMeshGenerator(), MooseMesh::prepare(), PropertyReadFile::PropertyReadFile(), RandomIC::RandomIC(), MooseMesh::setCoordSystem(), Transient::setupTimeIntegrator(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), Transfer::Transfer(), Transient::Transient(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
isParamValid()
bool InputParameters::isParamValid (const std::string & name) const
This method returns parameters that have been initialized in one fashion or another, i.e.
The value was supplied as a default argument or read and properly converted from the input file
Definition at line 368 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  if (have_parameter<MooseEnum>(name))
    return get<MooseEnum>(name).isValid();
  else if (have_parameter<std::vector<MooseEnum>>(name))
  {
    for (auto it = get<std::vector<MooseEnum>>(name).begin();
         it != get<std::vector<MooseEnum>>(name).end();
         ++it)
      if (!it->isValid())
        return false;
    return true;
  }
  else if (have_parameter<MultiMooseEnum>(name))
    return get<MultiMooseEnum>(name).isValid();
  else if (have_parameter<ExecFlagEnum>(name))
    return get<ExecFlagEnum>(name).isValid();
  else
    return _params.count(name) > 0 && _params.at(name)._valid;
}
Referenced by ElementIDOutputAction::act(), AddPeriodicBCAction::act(), AddVariableAction::act(), CreateExecutionerAction::act(), CreateProblemDefaultAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), ReadExecutorParamsAction::act(), SetupMeshAction::act(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FunctorMaterial::addFunctorPropertyByBlocks(), FEProblem::addLineSearch(), MooseObjectWarehouseBase< T >::addObject(), FEProblemBase::addObjectParamsHelper(), JsonSyntaxTree::addParameters(), MooseServer::addParametersToList(), FEProblemBase::addTransfer(), AddVariableAction::addVariable(), ADInterfaceKernelTempl< T >::ADInterfaceKernelTempl(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), applyParameter(), areAllRequiredParamsValid(), UserObjectInterface::castUserObject(), PostprocessorInterface::checkParam(), checkParams(), Coupleable::coupledMatrixTagValue(), Coupleable::coupledMatrixTagValues(), Coupleable::coupledVectorTagArrayGradient(), Coupleable::coupledVectorTagArrayGradients(), Coupleable::coupledVectorTagArrayValues(), Coupleable::coupledVectorTagDofValues(), Coupleable::coupledVectorTagGradient(), Coupleable::coupledVectorTagGradients(), Coupleable::coupledVectorTagValues(), AppFactory::createShared(), FunctorInterface::deduceFunctorName(), Parser::extractParams(), FileRangeBuilder::FileRangeBuilder(), GapValueAux::GapValueAux(), MaterialPropertyInterface::getMaterialDataType(), MaterialPropertyInterface::getMaterialPropertyName(), getParamHelper(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), GhostingUserObject::GhostingUserObject(), hasDefault(), HphiRadialInterface::HphiRadialInterface(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), isParamSetByUser(), MooseApp::isParamValid(), MooseBaseParameterInterface::isParamValid(), isValid(), LayeredBase::LayeredBase(), LayeredSideIntegralBase< UserObjectType >::LayeredSideIntegralBase(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseAppCoordTransform::MooseAppCoordTransform(), MultiApp::MultiApp(), NodeFaceConstraint::NodeFaceConstraint(), ParsedMaterialBase::ParsedMaterialBase(), PenetrationAux::PenetrationAux(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), ReporterInterface::possiblyCheckHasReporter(), InputFileFormatter::printParams(), YAMLFormatter::printParams(), PseudoTimestep::PseudoTimestep(), rangeCheck(), ReferenceResidualProblem::ReferenceResidualProblem(), RenameBoundaryGenerator::RenameBoundaryGenerator(), JsonSyntaxTree::setParams(), MooseMesh::setPartitioner(), MeshBaseImageSampler::setupImageSampler(), ImageSampler::setupImageSampler(), SetupMeshAction::setupMesh(), Moose::PetscSupport::storePetscOptions(), Moose::SlepcSupport::storeSolveType(), DumpObjectsProblem::stringifyParameters(), BoundaryRestrictable::validParams(), BoundaryRestrictableRequired::validParams(), Coupleable::vectorTagDofValueHelper(), Coupleable::vectorTagValueHelper(), ImageSampler::vtkMagnitude(), MeshBaseImageSampler::vtkMagnitude(), ImageSampler::vtkThreshold(), and MeshBaseImageSampler::vtkThreshold().
isPrivate()
bool InputParameters::isPrivate (const std::string & name) const
Returns a Boolean indicating whether the specified parameter is private or not.
Definition at line 414 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  return _params.count(name) > 0 && _params.at(name)._is_private;
}
Referenced by CommandLine::addCommandLineOptionsFromParams(), MooseServer::addParametersToList(), applyParameter(), checkParams(), Parser::extractParams(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), InputFileFormatter::printParams(), YAMLFormatter::printParams(), JsonSyntaxTree::setParams(), DumpObjectsProblem::stringifyParameters(), and transferParam().
isRangeChecked()
bool InputParameters::isRangeChecked (const std::string & param_name) const
Return whether a parameter has a range check.
Definition at line 608 of file InputParameters.C.
{
  const auto name = checkForRename(param_name);
  return !_params.find(name)->second._range_function.empty();
}
Referenced by transferParam().
isType()
template<typename T > bool InputParameters::isType (const std::string & name) const
Returns
True if the parameter with name name is of type T.
Definition at line 1839 of file InputParameters.h.
{
  const auto name = checkForRename(name_in);
  if (!_params.count(name))
    mooseError("Parameter \"", name, "\" is not valid.");
  return have_parameter<T>(name);
}
Referenced by PostprocessorInterface::checkParam(), PostprocessorInterface::coupledPostprocessors(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), PostprocessorInterface::getPostprocessorNameInternal(), ReporterInterface::getReporterName(), and Reporter::getReporterValueName().
makeParamNotRequired() [1/2]
template<typename T > void InputParameters::makeParamNotRequired (const std::string & name)
Changes the parameter to not be required.
Parameters
name The parameter name
Definition at line 1631 of file InputParameters.h.
{
  const auto name = checkForRename(name_in);
  if (!this->have_parameter<T>(name))
    mooseError("Unable to un-require nonexistent parameter: ", name);
  _params[name]._required = false;
}
Referenced by MooseServer::getObjectParameters().
makeParamNotRequired() [2/2]
void InputParameters::makeParamNotRequired (const std::string & name)
Forces parameter of given name to be not required regardless of type.
Definition at line 359 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  if (_params.count(name))
    _params[name]._required = false;
}
makeParamRequired()
template<typename T > void InputParameters::makeParamRequired (const std::string & name)
Changes the parameter to be required.
Parameters
name The parameter name
Definition at line 1619 of file InputParameters.h.
{
  const auto name = checkForRename(name_in);
  if (!this->have_parameter<T>(name))
    mooseError("Unable to require nonexistent parameter: ", name);
  _params[name]._required = true;
}
markControlled()
void InputParameters::markControlled (const std::string & name)
Marker a parameter that has been changed by the Control system (this is for output purposes)
mooseObjectSyntaxVisibility() [1/2]
bool InputParameters::mooseObjectSyntaxVisibility () const
Definition at line 528 of file InputParameters.C.
{
  return _moose_object_syntax_visibility;
}
mooseObjectSyntaxVisibility() [2/2]
void InputParameters::mooseObjectSyntaxVisibility (bool visibility)
Mutators for controlling whether or not the outermost level of syntax will be collapsed when printed.
Definition at line 522 of file InputParameters.C.
{
  _moose_object_syntax_visibility = visibility;
}
Referenced by Parser::buildFullTree(), and Parser::buildJsonSyntaxTree().
numberDefaultCoupledValues()
unsigned int InputParameters::numberDefaultCoupledValues (const std::string & coupling_name) const
Get the number of defaulted coupled value entries.
Parameters
coupling_name The name of the coupling parameter to get the default value for.
Definition at line 675 of file InputParameters.C.
{
  auto value_it = _params.find(coupling_name);
  if (value_it == _params.end())
    mooseError("Attempted to retrieve default value for coupled variable '",
               coupling_name,
               "' when none was provided.");
  return value_it->second._coupled_default.size();
}
Referenced by applyCoupledVar(), Coupleable::Coupleable(), Coupleable::coupledComponents(), Coupleable::getADDefaultVectorValue(), Coupleable::getDefaultArrayValue(), Coupleable::getDefaultValue(), and transferParam().
operator+=()
InputParameters & InputParameters::operator+= (const InputParameters & rhs)
Definition at line 176 of file InputParameters.C.
{
  Parameters::operator+=(rhs);
  // TODO: this is not a proper merge - if a particular parameter exists in both this and rhs,
  // then we should actually smartly merge both metadata structs before storing in this.
  for (auto it = rhs._params.begin(); it != rhs._params.end(); ++it)
    _params[it->first] = it->second;
  _buildable_types.insert(
      _buildable_types.end(), rhs._buildable_types.begin(), rhs._buildable_types.end());
  _buildable_rm_types.insert(
      _buildable_rm_types.end(), rhs._buildable_rm_types.begin(), rhs._buildable_rm_types.end());
  // Collapse nesting and moose object syntax hiding are not modified with +=
  _coupled_vars.insert(rhs._coupled_vars.begin(), rhs._coupled_vars.end());
  _new_to_deprecated_coupled_vars.insert(rhs._new_to_deprecated_coupled_vars.begin(),
                                         rhs._new_to_deprecated_coupled_vars.end());
  _old_to_new_name_and_dep.insert(rhs._old_to_new_name_and_dep.begin(),
                                  rhs._old_to_new_name_and_dep.end());
  _new_to_old_names.insert(rhs._new_to_old_names.begin(), rhs._new_to_old_names.end());
  return *this;
}
operator=()
InputParameters & InputParameters::operator= (const InputParameters & rhs)
Definition at line 139 of file InputParameters.C.
{
  // An error to help minimize the segmentation faults that occure when MooseObjects do not have the
  // correct constructor
  if (!rhs._allow_copy)
  {
    const std::string & name =
        rhs.get<std::string>("_object_name"); // If _allow_parameter_copy is set then so is name
                                              // (see InputParameterWarehouse::addInputParameters)
    mooseError("Copying of the InputParameters object for the ",
               name,
               " object is not allowed.\n\nThe likely cause for this error ",
               "is having a constructor that does not use a const reference, all constructors\nfor "
               "MooseObject based classes should be as follows:\n\n",
               "    MyObject::MyObject(const InputParameters & parameters);");
  }
  Parameters::operator=(rhs);
  _params = rhs._params;
  _buildable_types = rhs._buildable_types;
  _buildable_rm_types = rhs._buildable_rm_types;
  _collapse_nesting = rhs._collapse_nesting;
  _moose_object_syntax_visibility = rhs._moose_object_syntax_visibility;
  _coupled_vars = rhs._coupled_vars;
  _new_to_deprecated_coupled_vars = rhs._new_to_deprecated_coupled_vars;
  _allow_copy = rhs._allow_copy;
  _block_fullpath = rhs._block_fullpath;
  _block_location = rhs._block_location;
  _old_to_new_name_and_dep = rhs._old_to_new_name_and_dep;
  _new_to_old_names = rhs._new_to_old_names;
  return *this;
}
paramAliases()
std::vector< std::string > InputParameters::paramAliases (const std::string & param_name) const
Return all the aliased names associated with param_name.
The returned container will always contain param_name itself. Other aliases in addition to param_name will include the base class parameter name if param_name is the derived class parameter name, or deprecated names that param_name is meant to replace.
Parameters
param_name The name of the parameter that we want to lookup aliases for. This parameter name must exist in our metadata and parameter names to values map, e.g. this parameter must represent the derived class parameter name if a base class parameter has been renamed or the blessed parameter name in situations where associated parameter names have been deprecated
Returns
All aliases which logically resolve-to/are-associated-with param_name, including param_name itself
Definition at line 1416 of file InputParameters.C.
{
  mooseAssert(_values.find(param_name) != _values.end(),
              "The parameter we are searching for aliases for should exist in our parameter map");
  std::vector<std::string> aliases = {param_name};
  for (const auto & pr : as_range(_new_to_old_names.equal_range(param_name)))
    aliases.push_back(pr.second);
  return aliases;
}
Referenced by Parser::extractParams().
paramFullpath() [1/2]
std::string & InputParameters::paramFullpath (const std::string & param) inline
Definition at line 854 of file InputParameters.h.
{ return at(param)._param_fullpath; }
paramFullpath() [2/2]
const std::string & InputParameters::paramFullpath (const std::string & param) const inline
Get/set a string representing the full HIT parameter path from the input file (e.g.
"Mesh/foo/bar" for param "bar") for the given param.
Definition at line 850 of file InputParameters.h.
  {
    return at(param)._param_fullpath;
  }
Referenced by checkParams(), errorPrefix(), and Parser::extractParams().
paramSetByUser()
bool InputParameters::paramSetByUser (const std::string & name) const
Deprecated method.
Use isParamSetByUser() instead.
Definition at line 956 of file InputParameters.C.
{
  mooseDeprecated("paramSetByUser() is deprecated. Use isParamSetByUser() instead.");
  return isParamSetByUser(name);
}
rangeCheck() [1/2]
template<typename T , typename UP_T > void InputParameters::rangeCheck (const std::string & full_name, const std::string & short_name, InputParameters::Parameter< std::vector< T > > * param, std::ostream & oss = Moose::out)
Automatically detect the variables used in the range checking expression. We allow the following variables (where snam is the short_name of the parameter)
snam : tests every component in the vector 'snam > 0' snam_size : the size of the vector 'snam_size = 5' snam_i : where i is a number from 0 to sname_size-1 tests a specific component 'snam_0 > snam_1'
Definition at line 1208 of file InputParameters.h.
{
  mooseAssert(param, "Parameter is NULL");
  if (!isParamValid(short_name) || _params[short_name]._range_function.empty())
    return;
  FunctionParserBase<UP_T> fp;
  std::vector<std::string> vars;
  if (fp.ParseAndDeduceVariables(_params[short_name]._range_function, vars) != -1) // -1 for success
  {
    oss << "Error parsing expression: " << _params[short_name]._range_function << '\n';
    return;
  }
  // Fparser parameter buffer
  std::vector<UP_T> parbuf(vars.size());
  // parameter vector
  const std::vector<T> & value = param->set();
  // iterate over all vector values (maybe ;)
  bool need_to_iterate = false;
  unsigned int i = 0;
  do
  {
    // set parameters
    for (unsigned int j = 0; j < vars.size(); j++)
    {
      if (vars[j] == short_name)
      {
        if (value.size() == 0)
        {
          oss << "Range checking empty vector: " << _params[short_name]._range_function << '\n';
          return;
        }
        parbuf[j] = value[i];
        need_to_iterate = true;
      }
      else if (vars[j] == short_name + "_size")
        parbuf[j] = value.size();
      else
      {
        if (vars[j].substr(0, short_name.size() + 1) != short_name + "_")
        {
          oss << "Error parsing expression: " << _params[short_name]._range_function << '\n';
          return;
        }
        std::istringstream iss(vars[j]);
        iss.seekg(short_name.size() + 1);
        size_t index;
        if (iss >> index && iss.eof())
        {
          if (index >= value.size())
          {
            oss << "Error parsing expression: " << _params[short_name]._range_function
                << "\nOut of range variable " << vars[j] << '\n';
            return;
          }
          parbuf[j] = value[index];
        }
        else
        {
          oss << "Error parsing expression: " << _params[short_name]._range_function
              << "\nInvalid variable " << vars[j] << '\n';
          return;
        }
      }
    }
    // ensure range-checked input file parameter comparison functions
    // do absolute floating point comparisons instead of using a default epsilon.
    auto tmp_eps = fp.epsilon();
    fp.setEpsilon(0);
    UP_T result = fp.Eval(&parbuf[0]);
    fp.setEpsilon(tmp_eps);
    // test function using the parameters determined above
    if (fp.EvalError())
    {
      oss << "Error evaluating expression: " << _params[short_name]._range_function << '\n';
      return;
    }
    if (!result)
    {
      oss << "Range check failed for parameter " << full_name
          << "\n\tExpression: " << _params[short_name]._range_function << "\n";
      if (need_to_iterate)
        oss << "\t Component: " << i << '\n';
    }
  } while (need_to_iterate && ++i < value.size());
}
rangeCheck() [2/2]
template<typename T , typename UP_T > void InputParameters::rangeCheck (const std::string & full_name, const std::string & short_name, InputParameters::Parameter< T > * param, std::ostream & oss = Moose::out)
Runs a range on the supplied parameter if it exists and throws an error if that check fails.
Returns
Boolean indicating whether range check exists
Definition at line 1321 of file InputParameters.h.
{
  mooseAssert(param, "Parameter is NULL");
  if (!isParamValid(short_name) || _params[short_name]._range_function.empty())
    return;
  // Parse the expression
  FunctionParserBase<UP_T> fp;
  if (fp.Parse(_params[short_name]._range_function, short_name) != -1) // -1 for success
  {
    oss << "Error parsing expression: " << _params[short_name]._range_function << '\n';
    return;
  }
  // ensure range-checked input file parameter comparison functions
  // do absolute floating point comparisons instead of using a default epsilon.
  auto tmp_eps = fp.epsilon();
  fp.setEpsilon(0);
  // We require a non-const value for the implicit upscaling of the parameter type
  std::vector<UP_T> value(1, param->set());
  UP_T result = fp.Eval(&value[0]);
  fp.setEpsilon(tmp_eps);
  if (fp.EvalError())
  {
    oss << "Error evaluating expression: " << _params[short_name]._range_function
        << "\nPerhaps you used the wrong variable name?\n";
    return;
  }
  if (!result)
    oss << "Range check failed for parameter " << full_name
        << "\n\tExpression: " << _params[short_name]._range_function << "\n\tValue: " << value[0]
        << '\n';
}
Referenced by Parser::setScalarValueTypeParameter().
rangeCheckedFunction()
std::string InputParameters::rangeCheckedFunction (const std::string & name) const
Return the range check function for any parameter (empty string if it is not range checked)
Definition at line 615 of file InputParameters.C.
{
  const auto name = checkForRename(param_name);
  return _params.at(name)._range_function;
}
Referenced by transferParam().
rawParamVal() [1/2]
std::string & InputParameters::rawParamVal (const std::string & param) inline
Get/set a string representing the raw, unmodified token text for the given param.
This is usually only set/useable for file-path type parameters.
Definition at line 864 of file InputParameters.h.
{ return _params[param]._raw_val; }
Referenced by Parser::setFilePathParam(), and Parser::setVectorFilePathParam().
rawParamVal() [2/2]
const std::string & InputParameters::rawParamVal (const std::string & param) const inline
Definition at line 865 of file InputParameters.h.
  {
    return _params.at(param)._raw_val;
  }
registerBase()
void InputParameters::registerBase (const std::string & value)
This method must be called from every base "Moose System" to create linkage with the Action System.
See "Moose.C" for the registerMooseObjectTask() calls.
Definition at line 457 of file InputParameters.C.
{
  InputParameters::set<std::string>("_moose_base") = value;
  _params["_moose_base"]._is_private = true;
}
Referenced by Action::validParams(), AuxKernelTempl< ComputeValueType >::validParams(), AuxScalarKernel::validParams(), BoundaryCondition::validParams(), Constraint::validParams(), Control::validParams(), Damper::validParams(), DGKernelBase::validParams(), DiracKernelTempl< T >::validParams(), Distribution::validParams(), Executioner::validParams(), Executor::validParams(), Function::validParams(), FVBoundaryCondition::validParams(), FVInitialConditionBase::validParams(), FVInterfaceKernel::validParams(), FVKernel::validParams(), InitialConditionBase::validParams(), ScalarInitialCondition::validParams(), Indicator::validParams(), ADInterfaceKernelTempl< T >::validParams(), InterfaceKernelTempl< T >::validParams(), ArrayKernel::validParams(), EigenKernel::validParams(), Kernel::validParams(), VectorKernel::validParams(), LineSearch::validParams(), Marker::validParams(), MaterialBase::validParams(), MooseMesh::validParams(), MeshDivision::validParams(), MeshGenerator::validParams(), MultiApp::validParams(), NodalKernelBase::validParams(), Output::validParams(), MoosePartitioner::validParams(), Positions::validParams(), Postprocessor::validParams(), MoosePreconditioner::validParams(), Predictor::validParams(), Problem::validParams(), RelationshipManager::validParams(), Reporter::validParams(), Sampler::validParams(), ScalarKernelBase::validParams(), Split::validParams(), TimeIntegrator::validParams(), Times::validParams(), TimeStepper::validParams(), Transfer::validParams(), LayeredExtremumMaterialProperty::validParams(), NearestPointIntegralVariablePostprocessor::validParams(), UserObject::validParams(), MooseVariableBase::validParams(), and VectorPostprocessor::validParams().
registerBuildableTypes()
void InputParameters::registerBuildableTypes (const std::string & names)
This method is here to indicate which Moose types a particular Action may build.
It takes a space delimited list of registered MooseObjects. TODO: For now we aren't actually checking this list when we build objects. Since individual actions can do whatever they want it's not exactly trivial to check this without changing the user API. This function properly restricts the syntax and YAML dumps.
Definition at line 480 of file InputParameters.C.
{
  _buildable_types.clear();
  MooseUtils::tokenize(names, _buildable_types, 1, " \t\n\v\f\r"); // tokenize on whitespace
}
registerSystemAttributeName()
void InputParameters::registerSystemAttributeName (const std::string & value)
This method is used to define the MOOSE system name that is used by the TheWarehouse object for storing objects to be retrieved for execution.
The base class of every object class that will be called for execution (e.g., UserObject objects) should call this method.
This is different from registerBase because the name supplied to registerBase is used to associate syntax, but the objects created often go to the same objects for execution, as is the case for Postprocessor object which are executed with UserObjects.
See the AttribSystem object for use Attribute.h/C.
Definition at line 464 of file InputParameters.C.
{
  InputParameters::set<std::string>("_moose_warehouse_system_name") = value;
  _params["_moose_warehouse_system_name"]._is_private = true;
}
Referenced by Distribution::validParams(), FVDirichletBCBase::validParams(), FVFluxBC::validParams(), FVInterfaceKernel::validParams(), FVElementalKernel::validParams(), FVFluxKernel::validParams(), Sampler::validParams(), TimeStepper::validParams(), and UserObject::validParams().
renameCoupledVar()
void InputParameters::renameCoupledVar (const std::string & old_name, const std::string & new_name, const std::string & new_docstring)
Rename a coupled variable and provide a new documentation string.
Parameters
old_name The old name of the coupled variable
new_name The new name of the coupled variable
new_docstring The new documentation string for the coupled variable
Definition at line 1383 of file InputParameters.C.
{
  renameCoupledVarInternal(old_name, new_name, new_docstring, "");
}
Referenced by ADPenaltyPeriodicSegmentalConstraint::validParams(), ADPeriodicSegmentalConstraint::validParams(), PenaltyPeriodicSegmentalConstraint::validParams(), PeriodicSegmentalConstraint::validParams(), and ScalarLMKernelTempl< is_ad >::validParams().
renameCoupledVarInternal()
void InputParameters::renameCoupledVarInternal (const std::string & old_name, const std::string & new_name, const std::string & docstring, const std::string & removal_date) private
Definition at line 1357 of file InputParameters.C.
{
  auto coupled_vars_it = _coupled_vars.find(old_name);
  if (coupled_vars_it == _coupled_vars.end())
    mooseError("Requested to rename coupled variable '",
               old_name,
               "' but that coupled variable name doesn't exist in the parameters object.");
  _coupled_vars.insert(new_name);
  _coupled_vars.erase(coupled_vars_it);
  renameParamInternal(old_name, new_name, docstring, removal_date);
}
Referenced by deprecateCoupledVar(), and renameCoupledVar().
renameParam()
void InputParameters::renameParam (const std::string & old_name, const std::string & new_name, const std::string & new_docstring)
Rename a parameter and provide a new documentation string.
Parameters
old_name The old name of the parameter
new_name The new name of the parameter
new_docstring The new documentation string for the parameter If left empty, uses the old docstring for the renamed parameter
Definition at line 1375 of file InputParameters.C.
{
  renameParamInternal(old_name, new_name, new_docstring, "");
}
renameParamInternal()
void InputParameters::renameParamInternal (const std::string & old_name, const std::string & new_name, const std::string & docstring, const std::string & removal_date) private
Definition at line 1323 of file InputParameters.C.
{
  auto params_it = _params.find(old_name);
  if (params_it == _params.end())
    mooseError("Requested to rename parameter '",
               old_name,
               "' but that parameter name doesn't exist in the parameters object.");
  auto new_metadata = std::move(params_it->second);
  if (!docstring.empty())
    new_metadata._doc_string = docstring;
  else
    new_metadata._doc_string = params_it->second._doc_string;
  _params.emplace(new_name, std::move(new_metadata));
  _params.erase(params_it);
  auto values_it = _values.find(old_name);
  auto new_value = std::move(values_it->second);
  _values.emplace(new_name, std::move(new_value));
  _values.erase(values_it);
  std::string deprecation_message;
  if (!removal_date.empty())
    deprecation_message = "'" + old_name + "' has been deprecated and will be removed on " +
                          removal_date + ". Please use '" + new_name + "' instead.";
  _old_to_new_name_and_dep.emplace(old_name, std::make_pair(new_name, deprecation_message));
  _new_to_old_names.emplace(new_name, old_name);
}
Referenced by deprecateParam(), renameCoupledVarInternal(), and renameParam().
reservedValues()
std::set< std::string > InputParameters::reservedValues (const std::string & name) const
Get a set of reserved parameter values.
Returns a set by value since we can return an empty set.
Definition at line 1226 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  auto it = _params.find(name);
  if (it == _params.end())
    return std::set<std::string>();
  return it->second._reserved_values;
}
Referenced by JsonSyntaxTree::setParams().
set()
template<typename T > T & InputParameters::set (const std::string & name, bool quiet_mode = false)
Returns a writable reference to the named parameters.
Note: This is not a virtual function! Use caution when comparing to the parent class implementation
Parameters
name The name of the parameter to set
quiet_mode When true the parameter is kept with set_by_add_param=true, this is generally not needed.
"quite_mode" returns a writable reference to the named parameter, without setting set_by_add_param to false. Using this method of set will make the parameter to continue to behave if its value where set ONLY by addParam and not by any other method.
This was added for handling parameters in the Output objects that have behavior dependent on whether the user modified the parameters.
Definition at line 1179 of file InputParameters.h.
{
  const auto name = checkForRename(name_in);
  checkParamName(name);
  checkConsistentType<T>(name);
  T & result = this->Parameters::set<T>(name);
  if (quiet_mode)
    _params[name]._set_by_add_param = true;
  setHelper<T>(name);
  return result;
}
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), AddGeneralReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), ElementIDOutputAction::act(), AddSpecies::act(), AdaptivityAction::act(), AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), AddNodalNormalsAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), DisplayGhostingAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), PartitionerAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupPredictorAction::act(), SetupResidualDebugAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), FEProblemBase::addAnyRedistributers(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxKernel(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), FEProblemBase::addAuxScalarKernel(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), FEProblemBase::addBoundaryCondition(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), FEProblemBase::addConstraint(), AddDriftDiffusionAction::addCurrent(), FEProblemBase::addDamper(), AddDriftDiffusionAction::addDensityLog(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddGeneralReactions::addEEDFReactionKernel(), AddDriftDiffusionAction::addEfield(), FEProblemBase::addFunction(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addKernel(), MooseEigenSystem::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddDriftDiffusionAction::addPosition(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), FEProblemBase::addScalarKernel(), AddZapdosReactions::addSuperelasticRateCoefficient(), FEProblemBase::addTimeIntegrator(), AuxiliarySystem::addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), FEProblemBase::addTransfer(), SystemBase::addVariable(), FEProblemBase::addVariable(), FVFluxKernel::adjustRMGhostLayers(), MeshGeneratorSystem::appendMeshGenerator(), AStableDirk4::AStableDirk4(), ActionWarehouse::buildBuildableActions(), MooseObjectUnitTest::buildObjects(), OversampleOutput::cloneMesh(), ADMortarScalarBase::computeResidual(), Factory::create(), CommonOutputAction::create(), MultiApp::createApp(), AppFactory::createAppShared(), AddVariableAction::createInitialConditionAction(), AddSpecies::createInitialConditions(), MooseApp::createMinimalApp(), AppFactory::createShared(), Parser::extractParams(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::getFunction(), MaterialOutputAction::getParams(), Moose::SlepcSupport::getSlepcValidParams(), AddElementalFieldAction::init(), SetupMeshAction::modifyParamsForUseSplit(), NearestPointBase< UserObjectType, BaseType >::NearestPointBase(), MooseServer::parseDocumentForDiagnostics(), CommandLine::populateInputParams(), GlobalParamsAction::setDoubleIndexParam(), FEProblemBase::setInputParametersFEProblem(), FEProblem::setInputParametersFEProblem(), GlobalParamsAction::setParam(), FVKernel::setRMParams(), GlobalParamsAction::setScalarParam(), GlobalParamsAction::setTripleIndexParam(), CreateExecutionerAction::setupAutoPreconditioning(), ReadExecutorParamsAction::setupAutoPreconditioning(), MooseApp::setupOptions(), GlobalParamsAction::setVectorParam(), SideSetExtruderGenerator::SideSetExtruderGenerator(), ZapdosApp::validParams(), ArbitrarilyTiedValueConstraint::validParams(), AverageNodalDifference::validParams(), BlockAverageValue::validParams(), AddAuxKernelAction::validParams(), AddFVICAction::validParams(), AddICAction::validParams(), AddOutputAction::validParams(), AuxKernelTempl< ComputeValueType >::validParams(), ElementUOAux::validParams(), FunctorElementalGradientAuxTempl< is_ad >::validParams(), GapValueAux::validParams(), GhostingAux::validParams(), MortarNodalAuxKernelTempl< ComputeValueType >::validParams(), NearestNodeDistanceAux::validParams(), NearestNodeValueAux::validParams(), PenetrationAux::validParams(), ProjectionAux::validParams(), TagAuxBase< T >::validParams(), WeightedGapAux::validParams(), ConvectiveFluxBC::validParams(), EigenArrayDirichletBC::validParams(), EigenDirichletBC::validParams(), IntegratedBCBase::validParams(), NodalBCBase::validParams(), NodalNormalBC::validParams(), SinDirichletBC::validParams(), CoupledTiedValueConstraint::validParams(), EqualValueEmbeddedConstraint::validParams(), TiedValueConstraint::validParams(), Control::validParams(), ReporterPointSource::validParams(), InversePowerMethod::validParams(), NonlinearEigen::validParams(), PiecewiseConstantFromCSV::validParams(), GenericFunctorGradientMaterialTempl< is_ad >::validParams(), GenericFunctorMaterialTempl< is_ad >::validParams(), GenericVectorFunctorMaterialTempl< is_ad >::validParams(), VectorMagnitudeFunctorMaterialTempl< is_ad >::validParams(), FVFluxBC::validParams(), FVFunctorDirichletBCTempl< is_ad >::validParams(), FVInterfaceKernel::validParams(), FVOneVarDiffusionInterface::validParams(), FVAnisotropicDiffusion::validParams(), FVDiffusion::validParams(), FVFunctorTimeKernel::validParams(), FVTimeKernel::validParams(), InterfaceKernelBase::validParams(), InterfaceTimeKernel::validParams(), MortarConsumerInterface::validParams(), ADTimeKernelTempl< T >::validParams(), ADTimeKernelGradTempl< T >::validParams(), ADTimeKernelValueTempl< T >::validParams(), ArrayTimeKernel::validParams(), KernelBase::validParams(), ODETimeKernel::validParams(), TimeKernel::validParams(), VectorTimeKernel::validParams(), Marker::validParams(), GenericConstant2DArray::validParams(), GenericConstantArray::validParams(), GenericConstantMaterialTempl< is_ad >::validParams(), GenericConstantRankTwoTensorTempl< is_ad >::validParams(), GenericConstantVectorMaterialTempl< is_ad >::validParams(), InterfaceMaterial::validParams(), MaterialBase::validParams(), ThreeMaterialPropertyInterface::validParams(), TwoMaterialPropertyInterface::validParams(), MeshGeneratorMesh::validParams(), DistributedRectilinearMeshGenerator::validParams(), MultiApp::validParams(), TimeNodalKernel::validParams(), Console::validParams(), ControlOutput::validParams(), DOFMapOutput::validParams(), Exodus::validParams(), JSONOutput::validParams(), MaterialPropertyDebugOutput::validParams(), Output::validParams(), PerfGraphOutput::validParams(), ReporterDebugOutput::validParams(), TopResidualDebugOutput::validParams(), VariableResidualNormsDebugOutput::validParams(), VTKOutput::validParams(), BlockWeightedPartitioner::validParams(), ElementCentroidPositions::validParams(), ElementGroupCentroidPositions::validParams(), FilePositions::validParams(), FunctorPositions::validParams(), InputPositions::validParams(), MultiAppPositions::validParams(), Positions::validParams(), ReporterPositions::validParams(), NodalL2Norm::validParams(), NodalSum::validParams(), Postprocessor::validParams(), PseudoTimestep::validParams(), ExternalProblem::validParams(), AugmentSparsityOnInterface::validParams(), GhostEverything::validParams(), GhostHigherDLowerDPointNeighbors::validParams(), GhostLowerDElems::validParams(), AccumulateReporter::validParams(), PerfGraphReporter::validParams(), Sampler::validParams(), ADScalarTimeKernel::validParams(), CSVFileTimes::validParams(), ExodusFileTimes::validParams(), FunctorTimes::validParams(), InputTimes::validParams(), ReporterTimes::validParams(), SimulationTimes::validParams(), TimeIntervalTimes::validParams(), MultiAppGeneralFieldNearestLocationTransfer::validParams(), MultiAppGeneralFieldUserObjectTransfer::validParams(), MultiAppTransfer::validParams(), MultiAppUserObjectTransfer::validParams(), Transfer::validParams(), DiscreteElementUserObject::validParams(), ElementQualityChecker::validParams(), ElementSubdomainModifier::validParams(), ElemSideNeighborLayersGeomTester::validParams(), ElemSideNeighborLayersTester::validParams(), GhostingUserObject::validParams(), InterfaceQpUserObjectBase::validParams(), JSONFileReader::validParams(), MessageFromInput::validParams(), NearestPointAverage::validParams(), NearestRadiusLayeredAverage::validParams(), NodalNormalsEvaluator::validParams(), NodalPatchRecoveryBase::validParams(), ProjectedStatefulMaterialNodalPatchRecoveryBase::validParams(), ProjectedStatefulMaterialNodalPatchRecoveryTempl< T, is_ad >::validParams(), RadialAverage::validParams(), UserObject::validParams(), MooseVariableFV< OutputType >::validParams(), CSVReader::validParams(), ElementVariablesDifferenceMax::validParams(), LeastSquaresFitHistory::validParams(), SamplerBase::validParams(), VectorOfPostprocessors::validParams(), SquirrelApp::validParams(), Parser::walkRaw(), and RelationshipManager::zeroLayerGhosting().
set_attributes()
void InputParameters::set_attributes (const std::string & name, bool inserted_only) override virtual
Override from libMesh to set user-defined attributes on our parameter.
"._set_by_add_param" and ".deprecated_params" are not populated until after the default value has already been set in libMesh (first callback to this method). Therefore if a variable is in/not in one of these sets, you can be assured it was put there outside of the "addParam*()" calls.
Definition at line 82 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  if (!inserted_only)
  {
    auto & metadata = _params[name];
    metadata._set_by_add_param = false;
    // valid_params don't make sense for MooseEnums
    if (!have_parameter<MooseEnum>(name) && !have_parameter<MultiMooseEnum>(name))
      metadata._valid = true;
  }
}
Referenced by applyParameter(), and Parser::extractParams().
setDeprecatedVarDocString()
void InputParameters::setDeprecatedVarDocString (const std::string & new_name, const std::string & doc_string) private
Private method for setting deprecated coupled variable documentation strings.
Definition at line 202 of file InputParameters.C.
{
  auto coupled_vars_it = _new_to_deprecated_coupled_vars.find(new_name);
  if (coupled_vars_it != _new_to_deprecated_coupled_vars.end())
  {
    auto params_it = _params.find(coupled_vars_it->second);
    if (params_it == _params.end())
      mooseError("There must have been a mistake in the construction of the new to deprecated "
                 "coupled vars map because the old name ",
                 coupled_vars_it->second,
                 " doesn't exist in the parameters data.");
    params_it->second._doc_string = doc_string;
  }
}
Referenced by addCoupledVar().
setDocString()
void InputParameters::setDocString (const std::string & name, const std::string & doc)
Set the doc string of a parameter.
This method is generally used from within the validParams function to modify the documentation for an existing parameter, such as a parameter that is supplied from an interface class.
Definition at line 339 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  auto it = _params.find(name);
  if (it == _params.end())
    mooseError("Unable to set the documentation string (using setDocString) for the \"",
               name,
               "\" parameter, the parameter does not exist.");
  it->second._doc_string = doc;
}
Referenced by Moose::SlepcSupport::getSlepcValidParams(), AuxKernelTempl< ComputeValueType >::validParams(), FVBoundedValueConstraint::validParams(), FVIntegralValueConstraint::validParams(), FVPointValueConstraint::validParams(), Output::validParams(), and MultiAppTransfer::validParams().
setHelper()
template<typename T > void InputParameters::setHelper (const std::string & name)
This functions is called in set as a 'callback' to avoid code duplication.
Definition at line 1172 of file InputParameters.h.
{
}
setParameters() [1/2]
void InputParameters::setParameters () inline private
Method to terminate the recursive setParameters definition.
Definition at line 987 of file InputParameters.h.
{}
Referenced by setParameters().
setParameters() [2/2]
template<typename T , typename... Ts> void InputParameters::setParameters (const std::string & name, const T & value, Ts... extra_input_parameters)
Given a series of parameters names and values, sets each name to the corresponding value.
Any number of name, value pairs can be supplied.
Note that each value must be of the correct type for the parameter of that name, not merely of a type convertible to the correct type.
Parameters
name The name of the first parameter to set
Definition at line 1198 of file InputParameters.h.
{
  this->set<T>(name) = value;
  this->setParameters(extra_input_parameters...);
}
Referenced by AutoCheckpointAction::act(), and MeshGenerator::addMeshSubgenerator().
setParamHelper() [1/17]
template<> void InputParameters::setParamHelper (const std::string & , FunctionName & l_value, const int & r_value) private
setParamHelper() [2/17]
template<> void InputParameters::setParamHelper (const std::string & , FunctionName & l_value, const int & r_value) private
Definition at line 1136 of file InputParameters.C.
{
  // Assign the default value so that it appears in the dump
  std::ostringstream oss;
  oss << r_value;
  l_value = oss.str();
}
setParamHelper() [3/17]
template<> void InputParameters::setParamHelper (const std::string & , FunctionName & l_value, const Real & r_value) private
setParamHelper() [4/17]
template<> void InputParameters::setParamHelper (const std::string & , FunctionName & l_value, const Real & r_value) private
Definition at line 1124 of file InputParameters.C.
{
  // Assign the default value so that it appears in the dump
  std::ostringstream oss;
  oss << r_value;
  l_value = oss.str();
}
setParamHelper() [5/17]
template<> void InputParameters::setParamHelper (const std::string & , MaterialPropertyName & l_value, const int & r_value) private
setParamHelper() [6/17]
template<> void InputParameters::setParamHelper (const std::string & , MaterialPropertyName & l_value, const int & r_value) private
Definition at line 1160 of file InputParameters.C.
{
  // Assign the default value so that it appears in the dump
  std::ostringstream oss;
  oss << r_value;
  l_value = oss.str();
}
setParamHelper() [7/17]
template<> void InputParameters::setParamHelper (const std::string & , MaterialPropertyName & l_value, const Real & r_value) private
setParamHelper() [8/17]
template<> void InputParameters::setParamHelper (const std::string & , MaterialPropertyName & l_value, const Real & r_value) private
Definition at line 1148 of file InputParameters.C.
{
  // Assign the default value so that it appears in the dump
  std::ostringstream oss;
  oss << r_value;
  l_value = oss.str();
}
setParamHelper() [9/17]
template<> void InputParameters::setParamHelper (const std::string & , MooseFunctorName & l_value, const int & r_value) private
setParamHelper() [10/17]
template<> void InputParameters::setParamHelper (const std::string & , MooseFunctorName & l_value, const int & r_value) private
Definition at line 1184 of file InputParameters.C.
{
  // Assign the default value so that it appears in the dump
  std::ostringstream oss;
  oss << r_value;
  l_value = oss.str();
}
setParamHelper() [11/17]
template<> void InputParameters::setParamHelper (const std::string & , MooseFunctorName & l_value, const Real & r_value) private
setParamHelper() [12/17]
template<> void InputParameters::setParamHelper (const std::string & , MooseFunctorName & l_value, const Real & r_value) private
Definition at line 1172 of file InputParameters.C.
{
  // Assign the default value so that it appears in the dump
  std::ostringstream oss;
  oss << r_value;
  l_value = oss.str();
}
setParamHelper() [13/17]
template<> void InputParameters::setParamHelper (const std::string & , PostprocessorName & l_value, const int & r_value) private
Definition at line 1112 of file InputParameters.C.
{
  // Assign the default value so that it appears in the dump
  std::ostringstream oss;
  oss << r_value;
  l_value = oss.str();
}
setParamHelper() [14/17]
template<> void InputParameters::setParamHelper (const std::string & , PostprocessorName & l_value, const Real & r_value) private
Definition at line 1100 of file InputParameters.C.
{
  // Assign the default value so that it appears in the dump
  std::ostringstream oss;
  oss << r_value;
  l_value = oss.str();
}
setParamHelper() [15/17]
template<> void InputParameters::setParamHelper (const std::string & name, PostprocessorName & l_value, const int & r_value) private
setParamHelper() [16/17]
template<> void InputParameters::setParamHelper (const std::string & name, PostprocessorName & l_value, const Real & r_value) private
setParamHelper() [17/17]
template<typename T , typename S > void InputParameters::setParamHelper (const std::string & name, T & l_value, const S & r_value) private
This method is called when adding a Parameter with a default value, can be specialized for non-matching types.
Definition at line 1433 of file InputParameters.h.
{
  l_value = r_value;
}
Referenced by addParam().
setReservedValues()
void InputParameters::setReservedValues (const std::string & name, const std::set< std::string > & reserved)
Provide a set of reserved values for a parameter.
These are values that are in addition to the normal set of values the parameter can take.
Definition at line 1218 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  _params[name]._reserved_values = reserved;
}
Referenced by OutputInterface::validParams().
shouldIgnore()
bool InputParameters::shouldIgnore (const std::string & name)
Whether to ignore the value of an input parameter set in the input file or from the command line.
Definition at line 1244 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  auto it = _params.find(name);
  if (it != _params.end())
    return it->second._ignore;
  mooseError("Parameter ", name, " does not exist");
}
Referenced by Parser::extractParams().
suppressParameter()
template<typename T > void InputParameters::suppressParameter (const std::string & name)
This method suppresses an inherited parameter so that it isn't required or valid in the derived class.
The parameter is added to the private parameter list. Suppressing a parameter can have dire consequences. Use at your own risk!
Definition at line 1596 of file InputParameters.h.
{
  const auto name = checkForRename(name_in);
  if (!this->have_parameter<T>(name))
    mooseError("Unable to suppress nonexistent parameter: ", name);
  auto & metadata = _params[name];
  metadata._required = false;
  metadata._is_private = true;
  metadata._controllable = false;
}
Referenced by MortarNodalAuxKernelTempl< ComputeValueType >::validParams(), ReporterPointSource::validParams(), Marker::validParams(), CentroidMultiApp::validParams(), QuadraturePointMultiApp::validParams(), CSV::validParams(), VariableResidualNormsDebugOutput::validParams(), PseudoTimestep::validParams(), ExternalProblem::validParams(), AccumulateReporter::validParams(), MultiAppCloneReporterTransfer::validParams(), MultiAppGeneralFieldNearestLocationTransfer::validParams(), MultiAppGeneralFieldShapeEvaluationTransfer::validParams(), MultiAppGeneralFieldUserObjectTransfer::validParams(), MultiAppUserObjectTransfer::validParams(), DiscreteElementUserObject::validParams(), ElementSubdomainModifier::validParams(), NearestRadiusLayeredAverage::validParams(), and CSVReader::validParams().
transferParam()
template<typename T > void InputParameters::transferParam (const InputParameters & source_param, const std::string & name, const std::string & new_description = "")
A routine to transfer a parameter from one class' validParams to another.
Parameters
source_param The parameters list holding the param we would like to transfer
name The name of the parameter to transfer
new_description A new description of the parameter. If unspecified, uses the source_params'
Definition at line 1868 of file InputParameters.h.
{
  const auto name = source_params.checkForRename(std::string(name_in));
  if (!source_params.have_parameter<T>(name) && !source_params.hasCoupledValue(name))
    mooseError("The '",
               name_in,
               "' parameter could not be transferred because it does not exist with type '",
               MooseUtils::prettyCppType<T>(),
               "' in the source parameters");
  if (name != name_in)
    mooseWarning("The transferred parameter " + name_in + " is deprecated in favor of " + name +
                 " in the source parameters. The new name should likely be used for the parameter "
                 "transfer instead.");
  const std::string description =
      new_description.empty() ? source_params.getDescription(name) : new_description;
  if (source_params.isParamRequired(name))
  {
    // Use the name_in that was specified in the transfer
    // Check for a variable parameter
    if (source_params.hasCoupledValue(name))
      addRequiredCoupledVar(name_in, description);
    // Enums parameters have a default list of options
    else if constexpr (std::is_same_v<MooseEnum, T> || std::is_same_v<MultiMooseEnum, T>)
      addRequiredParam<T>(name_in, source_params.get<T>(name), description);
    else if (source_params.isRangeChecked(name))
      addRequiredRangeCheckedParam<T>(
          name_in, source_params.rangeCheckedFunction(name), description);
    else
      addRequiredParam<T>(name_in, description);
  }
  else
  {
    // Check for a variable parameter
    if (source_params.hasCoupledValue(name))
    {
      if (!source_params.hasDefaultCoupledValue(name))
        addCoupledVar(name_in, description);
      else if (source_params.numberDefaultCoupledValues(name) == 1)
        addCoupledVar(name_in, source_params.defaultCoupledValue(name), description);
      else
      {
        std::vector<Real> coupled_values;
        for (const auto i : make_range(source_params.numberDefaultCoupledValues(name)))
          coupled_values.push_back(source_params.defaultCoupledValue(name, i));
        addCoupledVar(name_in, coupled_values, description);
      }
    }
    else if (source_params.isRangeChecked(name))
    {
      if (source_params.hasDefault(name))
        addRangeCheckedParam<T>(name_in,
                                source_params.get<T>(name),
                                source_params.rangeCheckedFunction(name),
                                description);
      else
        addRangeCheckedParam<T>(name_in, source_params.rangeCheckedFunction(name), description);
    }
    else if constexpr (std::is_same_v<MooseEnum, T> || std::is_same_v<MultiMooseEnum, T>)
      addParam<T>(name_in, source_params.get<T>(name_in), description);
    else
    {
      if (source_params.hasDefault(name))
        addParam<T>(name_in, source_params.get<T>(name), description);
      else
        addParam<T>(name_in, description);
    }
  }
  // Copy other attributes
  if (source_params.isPrivate(name))
    _params[name_in]._is_private = true;
  if (source_params.isControllable(name))
    _params[name_in]._controllable = true;
}
type()
std::string InputParameters::type (const std::string & name) const
Prints the type of the requested parameter by name.
Definition at line 698 of file InputParameters.C.
{
  const auto name = checkForRename(name_in);
  if (!_values.count(name))
    mooseError("Parameter \"", name, "\" not found.\n\n", *this);
  if (_coupled_vars.find(name) != _coupled_vars.end())
    return "std::vector<VariableName>";
  else if (_params.count(name) > 0 && !_params.at(name)._custom_type.empty())
    return _params.at(name)._custom_type;
  return _values.at(name)->type();
}
Referenced by MooseServer::addParametersToList(), MooseServer::addValuesToList(), PostprocessorInterface::checkParam(), MooseServer::gatherDocumentDefinitionLocations(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), YAMLFormatter::printParams(), and JsonSyntaxTree::setParams().
varName()
std::string InputParameters::varName (const std::string & var_param_name, const std::string & moose_object_with_var_param_name) const
Determine the actual variable name from the given variable \emph parameter name.
Parameters
var_param_name the name of the variable parameter, e.g. 'variable'
moose_object_with_var_param_name the name of the moose object holding the variable parameter. Used for potential error messaging
Definition at line 1292 of file InputParameters.C.
{
  // Try the scalar version first
  std::string variable_name = getMooseType(var_param_name);
  if (variable_name == "")
  {
    auto vec = getVecMooseType(var_param_name);
    // Catch the (very unlikely) case where a user specifies
    // variable = '' (the empty string)
    // in their input file. This could happen if e.g. something goes
    // wrong with dollar bracket expression expansion.
    if (vec.empty())
      mooseError("Error constructing object '",
                 moose_object_with_var_param_name,
                 "' while retrieving value for '",
                 var_param_name,
                 "' parameter! Did you forget to set '",
                 var_param_name,
                 "' or set it to '' (empty string) by accident?");
    // When using vector variables, we are only going to use the first one in the list at the
    // interface level...
    variable_name = vec[0];
  }
  return variable_name;
}
Referenced by FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addKernel(), FEProblemBase::addNodalKernel(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addScalarKernel(), and MooseVariableInterface< T >::MooseVariableInterface().
Friends And Related Function Documentation
ActionWarehouse
friend class ActionWarehouse friend
Definition at line 1167 of file InputParameters.h.
emptyInputParameters
InputParameters emptyInputParameters () friend
Definition at line 28 of file InputParameters.C.
{
  InputParameters params;
  return params;
}
InputParameterWarehouse
friend class InputParameterWarehouse friend
Definition at line 1164 of file InputParameters.h.
Parser
friend class Parser friend
Definition at line 1165 of file InputParameters.h.
Member Data Documentation
_allow_copy
bool InputParameters::_allow_copy private
A flag for toggling the error message in the copy constructor.
Definition at line 1147 of file InputParameters.h.
Referenced by allowCopy(), clear(), and operator=().
_block_fullpath
std::string InputParameters::_block_fullpath private
full HIT path of the block from the input file - used for nice error messages.
Definition at line 1109 of file InputParameters.h.
Referenced by blockFullpath(), clear(), and operator=().
_block_location
std::string InputParameters::_block_location private
original location of input block (i.e. filename,linenum) - used for nice error messages.
Definition at line 1106 of file InputParameters.h.
Referenced by blockLocation(), clear(), and operator=().
_buildable_rm_types
std::vector<std::tuple<std::string, Moose::RelationshipManagerType, Moose::RelationshipManagerInputParameterCallback> > InputParameters::_buildable_rm_types private
The RelationshipManagers that this object may either build or require.
The optional second argument may be supplied to "downgrade" the functionality of the corresponding relationship manager (e.g. An AlgebraicRelationshipManager could be only used as a GeometricRelationshipManager for a given simulation).
Definition at line 1133 of file InputParameters.h.
Referenced by addRelationshipManager(), clearRelationshipManagers(), getBuildableRelationshipManagerTypes(), operator+=(), and operator=().
_buildable_types
std::vector<std::string> InputParameters::_buildable_types private
The parameter is used to restrict types that can be built.
Typically this is used for MooseObjectAction derived Actions.
Definition at line 1124 of file InputParameters.h.
Referenced by getBuildableTypes(), operator+=(), operator=(), and registerBuildableTypes().
_class_description
std::string InputParameters::_class_description private
The class description for the owning object.
This string is used in many places including mouse-over events, and external documentation produced from the source code.
Definition at line 1120 of file InputParameters.h.
Referenced by addClassDescription(), and getClassDescription().
_collapse_nesting
bool InputParameters::_collapse_nesting private
This parameter collapses one level of nesting in the syntax blocks.
It is used in conjunction with MooseObjectAction derived Actions.
Definition at line 1137 of file InputParameters.h.
Referenced by clear(), collapseSyntaxNesting(), InputParameters(), and operator=().
_coupled_vars
std::set<std::string> InputParameters::_coupled_vars private
The coupled variables set.
Definition at line 1116 of file InputParameters.h.
Referenced by addCoupledVar(), addCoupledVarWithAutoBuild(), addDeprecatedCoupledVar(), addRequiredCoupledVar(), clear(), coupledVarsBegin(), coupledVarsEnd(), getCoupledVariableParamNames(), hasCoupledValue(), hasDefaultCoupledValue(), operator+=(), operator=(), renameCoupledVarInternal(), and type().
_moose_object_syntax_visibility
bool InputParameters::_moose_object_syntax_visibility private
This parameter hides derived MOOSE object types from appearing in syntax dumps.
Definition at line 1140 of file InputParameters.h.
Referenced by clear(), InputParameters(), mooseObjectSyntaxVisibility(), and operator=().
_new_to_deprecated_coupled_vars
std::unordered_map<std::string, std::string> InputParameters::_new_to_deprecated_coupled_vars private
A map from deprecated coupled variable names to the new blessed name.
Definition at line 1150 of file InputParameters.h.
Referenced by addDeprecatedCoupledVar(), checkParams(), clear(), getNewToDeprecatedVarMap(), operator+=(), operator=(), and setDeprecatedVarDocString().
_new_to_old_names
std::multimap<std::string, std::string> InputParameters::_new_to_old_names private
A map from derived-class/blessed parameter names to associated base-class/deprecated parameter names.
Definition at line 1160 of file InputParameters.h.
Referenced by clear(), operator+=(), operator=(), paramAliases(), and renameParamInternal().
_old_to_new_name_and_dep
std::map<std::string, std::pair<std::string, std::string> > InputParameters::_old_to_new_name_and_dep private
A map from base-class/deprecated parameter names to derived-class/blessed parameter names and the deprecation messages in the case that the "old" parameter name is a deprecated parameter name.
The deprecation message will be empty if the "old" parameter name represents a base class parameter name
Definition at line 1156 of file InputParameters.h.
Referenced by attemptPrintDeprecated(), checkForRename(), clear(), operator+=(), operator=(), and renameParamInternal().
_params
std::map<std::string, Metadata> InputParameters::_params private
The actual parameter data.
Each Metadata object contains attributes for the corresponding parameter.
Definition at line 1113 of file InputParameters.h.
Referenced by addCommandLineParam(), addCoupledVar(), addCoupledVarWithAutoBuild(), addCustomTypeParam(), addDeprecatedCoupledVar(), addDeprecatedCustomTypeParam(), addDeprecatedParam(), addParam(), addParamNamesToGroup(), addPrivateParam(), addRangeCheckedParam(), addRequiredCommandLineParam(), addRequiredCustomTypeParam(), addRequiredParam(), addRequiredRangeCheckedParam(), applyParameter(), at(), attemptPrintDeprecated(), clear(), declareControllable(), defaultCoupledValue(), getAutoBuildVectors(), getControllableParameters(), getDescription(), getDocString(), getGroupName(), getGroupParameters(), getParametersList(), getSyntax(), hasDefaultCoupledValue(), ignoreParameter(), InputParameters(), isControllable(), isParamDeprecated(), isParamRequired(), isParamSetByAddParam(), isParamSetByUser(), isParamValid(), isPrivate(), isRangeChecked(), isType(), makeParamNotRequired(), makeParamRequired(), numberDefaultCoupledValues(), operator+=(), operator=(), rangeCheck(), rangeCheckedFunction(), rawParamVal(), registerBase(), registerSystemAttributeName(), renameParamInternal(), reservedValues(), set(), set_attributes(), setDeprecatedVarDocString(), setDocString(), setReservedValues(), shouldIgnore(), suppressParameter(), transferParam(), and type().
_show_deprecated_message
bool InputParameters::_show_deprecated_message private
Flag for disabling deprecated parameters message, this is used by applyParameters to avoid dumping messages.
Definition at line 1144 of file InputParameters.h.
Referenced by addDeprecatedCoupledVar(), addDeprecatedCustomTypeParam(), addDeprecatedParam(), applyCoupledVar(), applyParameter(), attemptPrintDeprecated(), and clear().
The documentation for this class was generated from the following files:
moose/framework/include/utils/InputParameters.h
moose/framework/src/utils/InputParameters.C