Zapdos: ExecFlagEnum Class Reference
ExecFlagEnum Class Reference
A MultiMooseEnum object to hold "execute_on" flags.
#include <ExecFlagEnum.h>
Public Member Functions
ExecFlagEnum ()
ExecFlagEnum (const ExecFlagEnum &other)
ExecFlagEnum (const MultiMooseEnum &other)
ExecFlagEnum & operator= (const ExecFlagEnum &other)=default
std::string getDocString () const
Generate a documentation string for the "execute_on" parameter.
const std::set< ExecFlagType > & items () const
Reference the all the available items.
const std::string & operator[] (unsigned int i) const
Indexing operator Operator to retrieve an item from the MultiMooseEnum.
unsigned int get (unsigned int i) const
Indexing operator Operator to retrieve an item from the MultiMooseEnum.
void clear ()
Clear the MultiMooseEnum.
unsigned int size () const
Return the number of active items in the MultiMooseEnum.
virtual bool isValid () const override
IsValid.
virtual void deprecate (const std::string &name, const std::string &raw_name="")
Deprecates various options in the MOOSE enum.
std::vector< std::string > getNames () const
Method for returning a vector of all valid enumeration names for this instance.
std::string getRawNames () const
Method for returning the raw name strings for this instance.
std::vector< int > getIDs () const
Method for returning a vector of ids for this instance.
bool isOutOfRangeAllowed () const
isOutOfRangeAllowed
void addDocumentation (const std::string &name, const std::string &doc)
Add an item documentation string.
const std::map< MooseEnumItem, std::string > & getItemDocumentation () const
Get the map containing each item's documentation string.
int getNextValidID () const
Compute the next valid ID.
MooseEnumBase & operator+= (const std::string &name)
Adds an enumeration item from name.
MooseEnumBase & operator+= (const std::initializer_list< std::string > &names)
Adds enumeration items from a list of names.
template<typename... Args>
void addAvailableFlags (const ExecFlagType &flag, Args... flags)
Add additional execute_on flags to the list of possible flags.
const ExecFlagType & addAvailableFlags (const ExecFlagType &flag)
ExecFlagEnum & operator= (const std::initializer_list< ExecFlagType > &flags)
ExecFlagEnum & operator= (const ExecFlagType &flags)
ExecFlagEnum & operator+= (const std::initializer_list< ExecFlagType > &flags)
ExecFlagEnum & operator+= (const ExecFlagType &flags)
MultiMooseEnum & operator= (const MultiMooseEnum &other_enum)=default
Assignment operators for setting the current flags.
MultiMooseEnum & operator= (const std::string &names)
Assignment operators for setting the current flags.
MultiMooseEnum & operator= (const std::vector< std::string > &names)
Assignment operators for setting the current flags.
MultiMooseEnum & operator= (const std::set< std::string > &names)
Assignment operators for setting the current flags.
template<typename... Args>
void removeAvailableFlags (const ExecFlagType &flag, Args... flags)
Remove flags from being available.
void removeAvailableFlags (const ExecFlagType &flag)
bool operator== (const MultiMooseEnum &value) const
Comparison operators for comparing with character constants, MultiMooseEnums or integer values.
bool operator!= (const MultiMooseEnum &value) const
bool contains (const std::string &value) const
Contains methods for seeing if a value is in the MultiMooseEnum.
bool contains (int value) const
bool contains (unsigned short value) const
bool contains (const MultiMooseEnum &value) const
bool contains (const MooseEnumItem &value) const
void erase (const std::string &names)
Un-assign a value.
void erase (const std::vector< std::string > &names)
void erase (const std::set< std::string > &names)
void push_back (const std::string &names)
Insert operators Operator to insert (push_back) values into the enum.
void push_back (const std::vector< std::string > &names)
void push_back (const std::set< std::string > &names)
void push_back (const MultiMooseEnum &other_enum)
MooseEnumIterator begin () const
Returns a begin/end iterator to all of the items in the enum.
MooseEnumIterator end () const
std::set< MooseEnumItem >::const_iterator find (const MooseEnumItem &other) const
Locate an item.
std::set< MooseEnumItem >::const_iterator find (const std::string &name) const
std::set< MooseEnumItem >::const_iterator find (int id) const
Protected Member Functions
void appendCurrent (const ExecFlagType &item)
Append the list of current flags.
virtual void checkDeprecated () const override
Check whether any of the current values are deprecated when called.
void checkDeprecated (const MooseEnumItem &item) const
Check and warn deprecated values.
template<typename InputIterator >
MultiMooseEnum & assign (InputIterator first, InputIterator last, bool append)
Helper method for all inserts and assignment operators.
template<typename InputIterator >
void remove (InputIterator first, InputIterator last)
Helper method for un-assigning enumeration values.
void setCurrentItems (const std::vector< MooseEnumItem > &current)
Set the current items.
void addEnumerationNames (const std::string &names)
Methods to add possible enumeration value to the enum.
const MooseEnumItem & addEnumerationName (const std::string &raw_name)
const MooseEnumItem & addEnumerationName (const std::string &name, const int &value)
const MooseEnumItem & addEnumerationItem (const MooseEnumItem &item)
Protected Attributes
std::vector< MooseEnumItem > _current
The current id.
std::set< MooseEnumItem > _items
Storage for the assigned items.
std::map< MooseEnumItem, MooseEnumItem > _deprecated_items
The map of deprecated names and optional replacements.
bool _allow_out_of_range
Flag to enable enumeration items not previously defined.
std::map< MooseEnumItem, std::string > _item_documentation
The map of items and their respective documentation strings.
Detailed Description
A MultiMooseEnum object to hold "execute_on" flags.
This object allows available flags to be added or removed thus each object can control the flags that are available.
Definition at line 21 of file ExecFlagEnum.h.
Constructor & Destructor Documentation
ExecFlagEnum() [1/3]
ExecFlagEnum::ExecFlagEnum ()
Definition at line 14 of file ExecFlagEnum.C.
: MultiMooseEnum() {}
ExecFlagEnum() [2/3]
ExecFlagEnum::ExecFlagEnum (const ExecFlagEnum & other)
Definition at line 16 of file ExecFlagEnum.C.
: MultiMooseEnum(other) {}
ExecFlagEnum() [3/3]
ExecFlagEnum::ExecFlagEnum (const MultiMooseEnum & other)
Definition at line 15 of file ExecFlagEnum.C.
: MultiMooseEnum(other) {}
Member Function Documentation
addAvailableFlags() [1/2]
const ExecFlagType & ExecFlagEnum::addAvailableFlags (const ExecFlagType & flag)
Definition at line 19 of file ExecFlagEnum.C.
{
  return addEnumerationItem(flag);
}
addAvailableFlags() [2/2]
template<typename... Args> void ExecFlagEnum::addAvailableFlags (const ExecFlagType & flag, Args... flags)
Add additional execute_on flags to the list of possible flags.
Use a recursive variadic template function to allow for an arbitrary number arguments: addAvaiableFlags(EXEC_INITIAL); addAvaiableFlags(EXEC_INITIAL, EXEC_TIMESTEP_END);
Definition at line 82 of file ExecFlagEnum.h.
{
  addAvailableFlags(flag);
  addAvailableFlags(flags...);
}
Referenced by addAvailableFlags(), AdvancedOutput::addValidParams(), Output::getDefaultExecFlagEnum(), moose::internal::ExecFlagRegistry::registerFlag(), AuxKernelTempl< ComputeValueType >::validParams(), Control::validParams(), FunctorMaterial::validParams(), Postprocessor::validParams(), Sampler::validParams(), and MultiAppTransfer::validParams().
addDocumentation()
void MooseEnumBase::addDocumentation (const std::string & name, const std::string & doc) inherited
Add an item documentation string.
Definition at line 175 of file MooseEnumBase.C.
{
  auto it = find(name);
  if (it == _items.end())
    mooseError("Item '", name, "' not found in addDocumentation.");
  _item_documentation[*it] = doc;
}
Referenced by PseudoTimestep::validParams(), and ReferenceResidualProblem::validParams().
addEnumerationItem()
const MooseEnumItem & MooseEnumBase::addEnumerationItem (const MooseEnumItem & item) protected inherited
Definition at line 117 of file MooseEnumBase.C.
{
  const auto & item_it = find(item);
  if (item_it != _items.end()) // do nothing for identical insertions
    return *item_it;
  if (find(item.id()) != _items.end())
    mooseError("The supplied id ",
               item.id(),
               " already exists in the enumeration, cannot not add '",
               item,
               "'.");
  if (find(item.name()) != _items.end())
    mooseError("The name '", item.name(), "' already exists in the enumeration.");
  return *_items.insert(item).first;
}
Referenced by addAvailableFlags(), MooseEnumBase::addEnumerationName(), MultiMooseEnum::assign(), and ReporterProducerEnum::insert().
addEnumerationName() [1/2]
const MooseEnumItem & MooseEnumBase::addEnumerationName (const std::string & name, const int & value) protected inherited
Definition at line 111 of file MooseEnumBase.C.
{
  return addEnumerationItem(MooseEnumItem(name, value));
}
addEnumerationName() [2/2]
const MooseEnumItem & MooseEnumBase::addEnumerationName (const std::string & raw_name) protected inherited
Definition at line 73 of file MooseEnumBase.C.
{
  // Make sure the option is not malformed
  if (raw_name.find_first_of('=') == 0 || raw_name.find_last_of('=') == raw_name.length() - 1)
    mooseError("You cannot place whitespace around the '=' character in MooseEnumBase");
  // Split on equals sign
  std::vector<std::string> name_value;
  MooseUtils::tokenize(MooseUtils::trim(raw_name), name_value, 1, "=");
  // There should be one or two items in the name_value
  if (name_value.size() < 1 || name_value.size() > 2)
    mooseError("Invalid option supplied in MooseEnumBase: ", raw_name);
  // Remove un-wanted space around string
  name_value[0] = MooseUtils::trim(name_value[0]);
  // See if there is a value supplied for this option
  // strtol allows for proper conversions of both int and hex strings
  int value;
  if (name_value.size() == 2)
    value = std::strtol(name_value[1].c_str(), NULL, 0);
  else
    value = getNextValidID();
  return addEnumerationName(name_value[0], value);
}
Referenced by MooseEnumBase::addEnumerationName(), MooseEnumBase::addEnumerationNames(), and MooseEnumBase::operator+=().
addEnumerationNames()
void MooseEnumBase::addEnumerationNames (const std::string & names) protected inherited
Methods to add possible enumeration value to the enum.
The MooseEnum/MultiMooseEnum are not designed to be modified, with respect to the list of possible values. However, this is not the case for the ExecFlagEnum which is a special type of MultiMooseEnum for managing the "execute_on" flags. These methods are used by ExecFlagEnum to allow users to modify the available execute flags for their object.
Definition at line 64 of file MooseEnumBase.C.
{
  std::vector<std::string> elements;
  MooseUtils::tokenize(names, elements, 1, " ");
  for (const std::string & raw_name : elements)
    addEnumerationName(raw_name);
}
Referenced by MooseEnumBase::MooseEnumBase().
appendCurrent()
void ExecFlagEnum::appendCurrent (const ExecFlagType & item) protected
Append the list of current flags.
Definition at line 82 of file ExecFlagEnum.C.
{
  if (find(item) == _items.end())
    mooseError("The supplied item '",
               item,
               "' is not an available item for the "
               "ExecFlagEnum object, thus it cannot be set as current.");
  _current.push_back(item);
}
Referenced by operator+=().
assign()
template<typename InputIterator > MultiMooseEnum & MultiMooseEnum::assign (InputIterator first, InputIterator last, bool append) protected inherited
Helper method for all inserts and assignment operators.
Definition at line 193 of file MultiMooseEnum.C.
{
  if (!append)
    clear();
  for (InputIterator it = first; it != last; ++it)
  {
    const auto iter = find(*it);
    if (iter == _items.end())
    {
      if (!_allow_out_of_range) // Are out of range values allowed?
        mooseError("Invalid option \"",
                   *it,
                   "\" in MultiMooseEnum.  Valid options (not case-sensitive) are \"",
                   getRawNames(),
                   "\".");
      else
      {
        MooseEnumItem created(*it, getNextValidID());
        addEnumerationItem(created);
        _current.push_back(created);
      }
    }
    else
      _current.push_back(*iter);
  }
  checkDeprecated();
  return *this;
}
Referenced by MultiMooseEnum::operator=(), and MultiMooseEnum::push_back().
begin()
MooseEnumIterator MultiMooseEnum::begin () const inline inherited
Returns a begin/end iterator to all of the items in the enum.
Items will always be capitalized.
Definition at line 145 of file MultiMooseEnum.h.
{ return _current.begin(); }
Referenced by FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), MultiMooseEnum::push_back(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
checkDeprecated() [1/2]
void MultiMooseEnum::checkDeprecated () const override protected virtual inherited
Check whether any of the current values are deprecated when called.
Implements MooseEnumBase.
Definition at line 250 of file MultiMooseEnum.C.
{
  for (const auto & item : _current)
    MooseEnumBase::checkDeprecated(item);
}
Referenced by MultiMooseEnum::assign(), and operator+=().
checkDeprecated() [2/2]
void MooseEnumBase::checkDeprecated (const MooseEnumItem & item) const protected inherited
Check and warn deprecated values.
Definition at line 136 of file MooseEnumBase.C.
{
  std::map<MooseEnumItem, MooseEnumItem>::const_iterator it = _deprecated_items.find(item);
  if (it != _deprecated_items.end())
  {
    if (it->second.name().empty())
      mooseWarning(item.name() + " is deprecated");
    else
      mooseWarning(item.name() + " is deprecated, consider using " + it->second.name());
  }
}
clear()
void MultiMooseEnum::clear () inherited
Clear the MultiMooseEnum.
Definition at line 238 of file MultiMooseEnum.C.
{
  _current.clear();
}
Referenced by MultiMooseEnum::assign(), AdvancedOutput::initExecutionTypes(), operator=(), and SetupInterface::SetupInterface().
contains() [1/5]
bool MultiMooseEnum::contains (const MooseEnumItem & value) const inherited
Definition at line 97 of file MultiMooseEnum.C.
{
  return std::find_if(_current.begin(),
                      _current.end(),
                      [&value](const MooseEnumItem & item)
                      { return item == value; }) != _current.end();
}
contains() [2/5]
bool MultiMooseEnum::contains (const MultiMooseEnum & value) const inherited
Definition at line 88 of file MultiMooseEnum.C.
{
  for (const auto & item : value._current)
    if (!contains(item))
      return false;
  return true;
}
contains() [3/5]
bool MultiMooseEnum::contains (const std::string & value) const inherited
Contains methods for seeing if a value is in the MultiMooseEnum.
Returns
bool - the truth value indicating whether the value is present
Definition at line 61 of file MultiMooseEnum.C.
{
  return std::find_if(_current.begin(),
                      _current.end(),
                      [&value](const MooseEnumItem & item)
                      { return item == value; }) != _current.end();
}
Referenced by FEProblemBase::addTransfer(), AdvancedOutput::addValidParams(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), MultiMooseEnum::contains(), MeshInfo::declareHelper(), IterationInfo::declareHelper(), EigenExecutionerBase::init(), IntegralPreservingFunctionIC::initialSetup(), Console::initialSetup(), MultiAppReporterTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), EigenExecutionerBase::inversePowerIteration(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiMooseEnum::operator==(), Console::output(), JSONOutput::outputReporters(), Console::outputSystemInformation(), XMLOutput::outputVectorPostprocessors(), MeshInfo::possiblyAddSidesetInfo(), MeshInfo::possiblyAddSubdomainInfo(), EigenExecutionerBase::postExecute(), Moose::PetscSupport::processPetscFlags(), Moose::PetscSupport::processPetscPairs(), removeAvailableFlags(), MultiAppVariableValueSamplePostprocessorTransfer::setupPostprocessorCommunication(), Output::shouldOutput(), PerfGraphOutput::shouldOutput(), FEProblemBase::shouldPrintExecution(), ElementReporter::shouldStore(), GeneralReporter::shouldStore(), and NodalReporter::shouldStore().
contains() [4/5]
bool MultiMooseEnum::contains (int value) const inherited
Definition at line 70 of file MultiMooseEnum.C.
{
  return std::find_if(_current.begin(),
                      _current.end(),
                      [&value](const MooseEnumItem & item)
                      { return item == value; }) != _current.end();
}
contains() [5/5]
bool MultiMooseEnum::contains (unsigned short value) const inherited
Definition at line 79 of file MultiMooseEnum.C.
{
  return std::find_if(_current.begin(),
                      _current.end(),
                      [&value](const MooseEnumItem & item)
                      { return item == value; }) != _current.end();
}
deprecate()
void MooseEnumBase::deprecate (const std::string & name, const std::string & raw_name = "") virtual inherited
Deprecates various options in the MOOSE enum.
For each deprecated option, you may supply an optional new option that will be used in a message telling the user which new option replaces the old one.
Definition at line 45 of file MooseEnumBase.C.
{
  std::set<MooseEnumItem>::const_iterator deprecated = find(name);
  if (deprecated == _items.end())
    mooseError("Cannot deprecate the enum item ", name, ", is not an available value.");
  std::set<MooseEnumItem>::const_iterator replaced = find(raw_name);
  if (replaced == _items.end())
    mooseError("Cannot deprecate the enum item ",
               name,
               ", since the replaced item ",
               raw_name,
               " it is not an available value.");
  _deprecated_items.emplace(std::make_pair(*deprecated, *replaced));
  checkDeprecated();
}
end()
MooseEnumIterator MultiMooseEnum::end () const inline inherited
Definition at line 146 of file MultiMooseEnum.h.
{ return _current.end(); }
Referenced by FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), MultiMooseEnum::push_back(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
erase() [1/3]
void MultiMooseEnum::erase (const std::set< std::string > & names) inherited
Definition at line 140 of file MultiMooseEnum.C.
{
  remove(names.begin(), names.end());
}
erase() [2/3]
void MultiMooseEnum::erase (const std::string & names) inherited
Un-assign a value.
Parameters
names - a string, set, or vector giving the name to erase from the enumeration values
Definition at line 126 of file MultiMooseEnum.C.
{
  std::vector<std::string> names_vector;
  MooseUtils::tokenize(names, names_vector, 1, " ");
  remove(names_vector.begin(), names_vector.end());
}
Referenced by Console::Console(), Moose::PetscSupport::disableLinearConvergedReason(), and Moose::PetscSupport::disableNonlinearConvergedReason().
erase() [3/3]
void MultiMooseEnum::erase (const std::vector< std::string > & names) inherited
Definition at line 134 of file MultiMooseEnum.C.
{
  remove(names.begin(), names.end());
}
find() [1/3]
std::set< MooseEnumItem >::const_iterator MooseEnumBase::find (const MooseEnumItem & other) const inherited
Locate an item.
Definition at line 206 of file MooseEnumBase.C.
{
  const auto upper = MooseUtils::toUpper(other.name());
  return std::find_if(_items.begin(),
                      _items.end(),
                      [&other, &upper](MooseEnumItem const & item)
                      { return item.id() == other.id() && item.name() == upper; });
}
Referenced by MooseEnumBase::addDocumentation(), MooseEnumBase::addEnumerationItem(), appendCurrent(), MooseEnum::assign(), MultiMooseEnum::assign(), MooseEnumBase::deprecate(), MooseEnum::operator==(), moose::internal::ExecFlagRegistry::registerFlag(), removeAvailableFlags(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
find() [2/3]
std::set< MooseEnumItem >::const_iterator MooseEnumBase::find (const std::string & name) const inherited
Definition at line 190 of file MooseEnumBase.C.
{
  std::string upper = MooseUtils::toUpper(name);
  return std::find_if(_items.begin(),
                      _items.end(),
                      [&upper](MooseEnumItem const & item) { return item.name() == upper; });
}
find() [3/3]
std::set< MooseEnumItem >::const_iterator MooseEnumBase::find (int id) const inherited
Definition at line 199 of file MooseEnumBase.C.
{
  return std::find_if(
      _items.begin(), _items.end(), [&id](MooseEnumItem const & item) { return item.id() == id; });
}
get()
unsigned int MultiMooseEnum::get (unsigned int i) const inherited
Indexing operator Operator to retrieve an item from the MultiMooseEnum.
Parameters
i index
Returns
the id of the MooseEnumItem at the supplied index
Definition at line 182 of file MultiMooseEnum.C.
{
  mooseAssert(i < _current.size(),
              "Access out of bounds in MultiMooseEnum (i: " << i << " size: " << _current.size()
                                                            << ")");
  return _current[i].id();
}
Referenced by PiecewiseMulticonstant::sample(), Parser::setScalarParameter(), and Transfer::Transfer().
getDocString()
std::string ExecFlagEnum::getDocString () const
Generate a documentation string for the "execute_on" parameter.
Definition at line 39 of file ExecFlagEnum.C.
{
  std::string doc("The list of flag(s) indicating when this object should be executed, the "
                  "available options include ");
  doc += Moose::stringify(getNames(), ", ");
  doc += ".";
  return doc;
}
Referenced by AuxKernelTempl< ComputeValueType >::validParams(), and SetupInterface::validParams().
getIDs()
std::vector< int > MooseEnumBase::getIDs () const inherited
Method for returning a vector of ids for this instance.
Returns
a vector of ints containing the possible ids for this enumeration
Definition at line 165 of file MooseEnumBase.C.
{
  std::vector<int> out;
  out.reserve(_items.size());
  for (const auto & item : _items)
    out.push_back(item.id());
  return out;
}
Referenced by MooseEnum::assign().
getItemDocumentation()
const std::map< MooseEnumItem, std::string > & MooseEnumBase::getItemDocumentation () const inherited
Get the map containing each item's documentation string.
Definition at line 184 of file MooseEnumBase.C.
{
  return _item_documentation;
}
getNames()
std::vector< std::string > MooseEnumBase::getNames () const inherited
Method for returning a vector of all valid enumeration names for this instance.
Returns
a vector of names
Definition at line 149 of file MooseEnumBase.C.
{
  std::vector<std::string> out;
  out.reserve(_items.size());
  for (const auto & item : _items)
    out.push_back(item.name());
  return out;
}
Referenced by getDocString().
getNextValidID()
int MooseEnumBase::getNextValidID () const inherited
Compute the next valid ID.
Definition at line 102 of file MooseEnumBase.C.
{
  int value = -1; // Use -1 so if no values exist the first will be zero
  for (const auto & item : _items)
    value = std::max(value, item.id());
  return ++value;
}
Referenced by MooseEnumBase::addEnumerationName(), MooseEnum::assign(), MultiMooseEnum::assign(), and moose::internal::ExecFlagRegistry::registerFlag().
getRawNames()
std::string MooseEnumBase::getRawNames () const inherited
Method for returning the raw name strings for this instance.
Returns
a space separated list of names
Definition at line 159 of file MooseEnumBase.C.
{
  return Moose::stringify(_items, " ");
}
Referenced by MooseEnum::assign(), MultiMooseEnum::assign(), AdvancedOutput::enableOutputTypes(), MooseEnum::operator==(), PiecewiseConstant::validParams(), and ComparisonPostprocessor::validParams().
isOutOfRangeAllowed()
bool MooseEnumBase::isOutOfRangeAllowed () const inline inherited
isOutOfRangeAllowed
Returns
- a Boolean indicating whether enum names out of range are allowed
Definition at line 88 of file MooseEnumBase.h.
{ return _allow_out_of_range; }
isValid()
virtual bool MultiMooseEnum::isValid () const inline override virtual inherited
IsValid.
Returns
- a Boolean indicating whether this Enumeration has been set
Implements MooseEnumBase.
Definition at line 163 of file MultiMooseEnum.h.
{ return !_current.empty(); }
Referenced by MeshInfo::declareHelper(), IterationInfo::declareHelper(), MeshInfo::possiblyAddSidesetInfo(), and MeshInfo::possiblyAddSubdomainInfo().
items()
const std::set< ExecFlagType > & ExecFlagEnum::items () const inline
Reference the all the available items.
Definition at line 71 of file ExecFlagEnum.h.
{ return _items; }
Referenced by ExecuteMooseObjectWarehouse< T >::ExecuteMooseObjectWarehouse(), groupUserObjects(), EigenExecutionerBase::normalizeSolution(), and moose::internal::ExecFlagRegistry::registerFlag().
operator!=()
bool MultiMooseEnum::operator!= (const MultiMooseEnum & value) const inherited
Definition at line 55 of file MultiMooseEnum.C.
{
  return !(*this == value);
}
operator+=() [1/4]
ExecFlagEnum & ExecFlagEnum::operator+= (const ExecFlagType & flags)
Definition at line 74 of file ExecFlagEnum.C.
{
  appendCurrent(flag);
  checkDeprecated();
  return *this;
}
operator+=() [2/4]
ExecFlagEnum & ExecFlagEnum::operator+= (const std::initializer_list< ExecFlagType > & flags)
Definition at line 65 of file ExecFlagEnum.C.
{
  for (const ExecFlagType & flag : flags)
    appendCurrent(flag);
  checkDeprecated();
  return *this;
}
operator+=() [3/4]
MooseEnumBase & MooseEnumBase::operator+= (const std::initializer_list< std::string > & names) inherited
Adds enumeration items from a list of names.
Definition at line 224 of file MooseEnumBase.C.
{
  for (const auto & name : names)
    *this += name;
  return *this;
}
operator+=() [4/4]
MooseEnumBase & MooseEnumBase::operator+= (const std::string & name) inherited
Adds an enumeration item from name.
Definition at line 216 of file MooseEnumBase.C.
{
  addEnumerationName(name);
  checkDeprecated();
  return *this;
}
operator=() [1/7]
ExecFlagEnum & ExecFlagEnum::operator= (const ExecFlagEnum & other) default
operator=() [2/7]
ExecFlagEnum & ExecFlagEnum::operator= (const ExecFlagType & flags)
Definition at line 57 of file ExecFlagEnum.C.
{
  clear();
  *this += flag;
  return *this;
}
operator=() [3/7]
MultiMooseEnum & MultiMooseEnum::operator= (const MultiMooseEnum & other_enum) default
Assignment operators for setting the current flags.
operator=() [4/7]
ExecFlagEnum & ExecFlagEnum::operator= (const std::initializer_list< ExecFlagType > & flags)
Definition at line 49 of file ExecFlagEnum.C.
{
  clear();
  *this += flags;
  return *this;
}
operator=() [5/7]
MultiMooseEnum & MultiMooseEnum::operator= (const std::set< std::string > & names)
Assignment operators for setting the current flags.
Definition at line 97 of file MultiMooseEnum.C.
{
  return assign(names.begin(), names.end(), false);
}
operator=() [6/7]
MultiMooseEnum & MultiMooseEnum::operator= (const std::string & names)
Assignment operators for setting the current flags.
Definition at line 95 of file MultiMooseEnum.C.
{
  std::vector<std::string> names_vector;
  MooseUtils::tokenize(names, names_vector, 1, " ");
  return assign(names_vector.begin(), names_vector.end(), false);
}
operator=() [7/7]
MultiMooseEnum & MultiMooseEnum::operator= (const std::vector< std::string > & names)
Assignment operators for setting the current flags.
Definition at line 96 of file MultiMooseEnum.C.
{
  return assign(names.begin(), names.end(), false);
}
operator==()
bool MultiMooseEnum::operator== (const MultiMooseEnum & value) const inherited
Comparison operators for comparing with character constants, MultiMooseEnums or integer values.
Parameters
value - RHS value to compare against
Returns
bool - the truth value for the comparison
Definition at line 43 of file MultiMooseEnum.C.
{
  // Not the same if the lengths are different
  if (value.size() != size())
    return false;
  // Return false if this enum does not contain an item from the other, since they are the same
  // size at this point if this is true then they are equal.
  return contains(value);
}
operator[]()
const std::string & MultiMooseEnum::operator[] (unsigned int i) const inherited
Indexing operator Operator to retrieve an item from the MultiMooseEnum.
The reference may not be used to change the item.
Parameters
i index
Returns
a read/read-write reference to the item as a string.
Definition at line 172 of file MultiMooseEnum.C.
{
  mooseAssert(i < _current.size(),
              "Access out of bounds in MultiMooseEnum (i: " << i << " size: " << _current.size()
                                                            << ")");
  return _current[i].rawName();
}
push_back() [1/4]
void MultiMooseEnum::push_back (const MultiMooseEnum & other_enum) inherited
Definition at line 166 of file MultiMooseEnum.C.
{
  assign(other_enum.begin(), other_enum.end(), true);
}
push_back() [2/4]
void MultiMooseEnum::push_back (const std::set< std::string > & names) inherited
Definition at line 160 of file MultiMooseEnum.C.
{
  assign(names.begin(), names.end(), true);
}
push_back() [3/4]
void MultiMooseEnum::push_back (const std::string & names) inherited
Insert operators Operator to insert (push_back) values into the enum.
Existing values are preserved and duplicates are stored.
Parameters
names - a string, set, or vector representing one of the enumeration values.
Definition at line 146 of file MultiMooseEnum.C.
{
  std::vector<std::string> names_vector;
  MooseUtils::tokenize(names, names_vector, 1, " ");
  assign(names_vector.begin(), names_vector.end(), true);
}
Referenced by Console::Console(), MultiAppTransfer::MultiAppTransfer(), Output::Output(), PetscOutput::PetscOutput(), Moose::PetscSupport::processPetscFlags(), and Split::setup().
push_back() [4/4]
void MultiMooseEnum::push_back (const std::vector< std::string > & names) inherited
Definition at line 154 of file MultiMooseEnum.C.
{
  assign(names.begin(), names.end(), true);
}
remove()
template<typename InputIterator > void MultiMooseEnum::remove (InputIterator first, InputIterator last) protected inherited
Helper method for un-assigning enumeration values.
Definition at line 225 of file MultiMooseEnum.C.
{
  // Create a new list of enumerations by striping out the supplied values
  for (InputIterator it = first; it != last; ++it)
  {
    std::vector<MooseEnumItem>::iterator iter = std::find_if(
        _current.begin(), _current.end(), [it](const MooseEnumItem & item) { return item == *it; });
    if (iter != _current.end())
      _current.erase(iter);
  }
}
Referenced by MultiMooseEnum::erase().
removeAvailableFlags() [1/2]
void ExecFlagEnum::removeAvailableFlags (const ExecFlagType & flag)
Definition at line 25 of file ExecFlagEnum.C.
{
  if (find(flag) == _items.end())
    mooseError("The supplied item '",
               flag,
               "' is not an available enum item for the "
               "MultiMooseEnum object, thus it cannot be removed.");
  else if (contains(flag))
    mooseError("The supplied item '", flag, "' is a selected item, thus it can not be removed.");
  _items.erase(flag);
}
removeAvailableFlags() [2/2]
template<typename... Args> void ExecFlagEnum::removeAvailableFlags (const ExecFlagType & flag, Args... flags)
Remove flags from being available.
Definition at line 90 of file ExecFlagEnum.h.
{
  removeAvailableFlags(flag);
  removeAvailableFlags(flags...);
}
Referenced by removeAvailableFlags().
setCurrentItems()
void MultiMooseEnum::setCurrentItems (const std::vector< MooseEnumItem > & current) protected inherited
Set the current items.
size()
unsigned int MultiMooseEnum::size () const inherited
Return the number of active items in the MultiMooseEnum.
Definition at line 244 of file MultiMooseEnum.C.
{
  return _current.size();
}
Referenced by SubProblem::doingPRefinement(), Moose::LibtorchArtificialNeuralNet::forward(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Moose::LibtorchArtificialNeuralNet::LibtorchArtificialNeuralNet(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), MultiMooseEnum::operator==(), PiecewiseMulticonstant::PiecewiseMulticonstant(), MooseMesh::setCoordSystem(), SidesetInfoVectorPostprocessor::SidesetInfoVectorPostprocessor(), and Transfer::Transfer().
Member Data Documentation
_allow_out_of_range
bool MooseEnumBase::_allow_out_of_range protected inherited
Flag to enable enumeration items not previously defined.
Definition at line 163 of file MooseEnumBase.h.
Referenced by MooseEnum::assign(), MultiMooseEnum::assign(), MooseEnumBase::isOutOfRangeAllowed(), and MooseEnum::operator==().
_current
std::vector<MooseEnumItem> MultiMooseEnum::_current protected inherited
The current id.
Definition at line 194 of file MultiMooseEnum.h.
Referenced by appendCurrent(), MultiMooseEnum::assign(), MultiMooseEnum::begin(), MultiMooseEnum::checkDeprecated(), MultiMooseEnum::clear(), MultiMooseEnum::contains(), MultiMooseEnum::end(), MultiMooseEnum::get(), MultiMooseEnum::isValid(), MultiMooseEnum::operator[](), MultiMooseEnum::remove(), and MultiMooseEnum::size().
_deprecated_items
std::map<MooseEnumItem, MooseEnumItem> MooseEnumBase::_deprecated_items protected inherited
The map of deprecated names and optional replacements.
Definition at line 160 of file MooseEnumBase.h.
Referenced by MooseEnumBase::checkDeprecated(), and MooseEnumBase::deprecate().
_item_documentation
std::map<MooseEnumItem, std::string> MooseEnumBase::_item_documentation protected inherited
The map of items and their respective documentation strings.
Definition at line 166 of file MooseEnumBase.h.
Referenced by MooseEnumBase::addDocumentation(), and MooseEnumBase::getItemDocumentation().
_items
std::set<MooseEnumItem> MooseEnumBase::_items protected inherited
Storage for the assigned items.
Definition at line 157 of file MooseEnumBase.h.
Referenced by MooseEnumBase::addDocumentation(), MooseEnumBase::addEnumerationItem(), appendCurrent(), MooseEnum::assign(), MultiMooseEnum::assign(), ReporterProducerEnum::clear(), MooseEnumBase::deprecate(), MooseEnumBase::find(), MooseEnumBase::getIDs(), MooseEnumBase::getNames(), MooseEnumBase::getNextValidID(), MooseEnumBase::getRawNames(), items(), MooseEnumBase::items(), MooseEnum::operator==(), and removeAvailableFlags().
The documentation for this class was generated from the following files:
moose/framework/include/utils/ExecFlagEnum.h
moose/framework/src/utils/ExecFlagEnum.C