Zapdos: MaterialData Class Reference
MaterialData Class Reference
Proxy for accessing MaterialPropertyStorage.
#include <MaterialData.h>
Classes
class XFEMKey
Key that provides access to only the XFEM class.
Public Member Functions
MaterialData (MaterialPropertyStorage &storage, const THREAD_ID tid)
void resize (unsigned int n_qpoints)
Resize the data to hold properties for n_qpoints quadrature points.
unsigned int nQPoints () const
Returns the number of quadrature points the material properties support/hold.
void copy (const Elem &elem_to, const Elem &elem_from, unsigned int side)
copy material properties from one element to another
void swap (const Elem &elem, unsigned int side=0)
material properties for given element (and possible side)
template<typename MatContainer >
void reinit (const MatContainer &mats)
Reinit material properties for given element (and possible side)
void reset (const std::vector< std::shared_ptr< MaterialBase > > &mats)
Calls the reset method of Materials to ensure that they are in a proper state.
void swapBack (const Elem &elem, unsigned int side=0)
material properties for given element (and possible side)
const MaterialProperties & props (const unsigned int state=0) const
{
MaterialProperties & props (const unsigned int state=0)
template<typename T , bool is_ad>
bool haveGenericProperty (const std::string &prop_name) const
template<typename T >
bool haveProperty (const std::string &prop_name) const
Returns true if the regular material property exists - defined by any material.
template<typename T >
bool haveADProperty (const std::string &prop_name) const
Returns true if the AD material property exists - defined by any material.
template<typename T , bool is_ad = false>
GenericMaterialProperty< T, is_ad > & getProperty (const std::string &prop_name, const unsigned int state, const MooseObject &requestor)
Retrieves a material property.
template<typename T , bool is_ad>
GenericMaterialProperty< T, is_ad > & declareProperty (const std::string &prop_name, const MooseObject &requestor)
Declares a material property.
bool isSwapped () const
Returns true if the stateful material is in a swapped state.
const MaterialPropertyStorage & getMaterialPropertyStorage () const
Provide read-only access to the underlying MaterialPropertyStorage object.
MaterialPropertyStorage & getMaterialPropertyStorageForXFEM (const XFEMKey)
Provide write-only access to the underlying MaterialPropertyStorage object JUST FOR XFEM.
bool hasProperty (const std::string &prop_name) const
unsigned int getPropertyId (const std::string &prop_name) const
Wrapper for MaterialStorage::getPropertyId.
void onlyResizeIfSmaller (bool flag)
Set _resize_only_if_smaller to perform a non-destructive resize.
bool isOnlyResizeIfSmaller () const
Check value of _resize_only_if_smaller.
void eraseProperty (const Elem *elem)
Remove the property storage and element pointer from MaterialPropertyStorage data structures Use this when elements are deleted so we don't end up with invalid elem pointers (for e.g.
Static Public Attributes
static constexpr unsigned int max_state = 2
The max time state supported (2 = older)
Private Member Functions
unsigned int addPropertyHelper (const std::string &prop_name, const unsigned int state)
template<typename T , bool is_ad, bool declare>
GenericMaterialProperty< T, is_ad > & getPropertyHelper (const std::string &prop_name, const unsigned int state, const MooseObject &requestor)
Static Private Member Functions
static void mooseErrorHelper (const MooseObject &object, const std::string_view &error)
Private Attributes
MaterialPropertyStorage & _storage
Reference to the MaterialStorage class.
const THREAD_ID _tid
The thread id.
unsigned int _n_qpoints
Number of quadrature points.
std::array< MaterialProperties, max_state+1 > _props
The underlying property data.
bool _swapped
Status of storage swapping (calling swap sets this to true; swapBack sets it to false)
bool _resize_only_if_smaller
Use non-destructive resize of material data (calling resize() will not reduce size).
Detailed Description
Proxy for accessing MaterialPropertyStorage.
MaterialData stores the values associated with a particular material object
Definition at line 31 of file MaterialData.h.
Constructor & Destructor Documentation
MaterialData()
MaterialData::MaterialData (MaterialPropertyStorage & storage, const THREAD_ID tid)
Definition at line 14 of file MaterialData.C.
  : _storage(storage), _tid(tid), _n_qpoints(0), _swapped(false), _resize_only_if_smaller(false)
{
}
Member Function Documentation
addPropertyHelper()
unsigned int MaterialData::addPropertyHelper (const std::string & prop_name, const unsigned int state) private
Definition at line 91 of file MaterialData.C.
{
  return _storage.addProperty(prop_name, state);
}
Referenced by getPropertyHelper().
copy()
void MaterialData::copy (const Elem & elem_to, const Elem & elem_from, unsigned int side)
copy material properties from one element to another
Definition at line 34 of file MaterialData.C.
{
  _storage.copy(_tid, &elem_to, &elem_from, side, nQPoints());
}
declareProperty()
template<typename T , bool is_ad> GenericMaterialProperty< T, is_ad > & MaterialData::declareProperty (const std::string & prop_name, const MooseObject & requestor) inline
Declares a material property.
Template Parameters
T The type of the property
is_ad Whether or not the property is AD
Parameters
prop_name The name of the property
requestor The MooseObject declaring the property
Returns
The property for the supplied type and name
Definition at line 124 of file MaterialData.h.
  {
    return getPropertyHelper<T, is_ad, true>(prop_name, 0, requestor);
  }
Referenced by MaterialBase::declareGenericPropertyByName().
eraseProperty()
void MaterialData::eraseProperty (const Elem * elem)
Remove the property storage and element pointer from MaterialPropertyStorage data structures Use this when elements are deleted so we don't end up with invalid elem pointers (for e.g.
stateful properties) hanging around in our data structures
Definition at line 85 of file MaterialData.C.
{
  _storage.eraseProperty(elem);
}
getMaterialPropertyStorage()
const MaterialPropertyStorage & MaterialData::getMaterialPropertyStorage () const inline
Provide read-only access to the underlying MaterialPropertyStorage object.
Definition at line 138 of file MaterialData.h.
{ return _storage; }
getMaterialPropertyStorageForXFEM()
MaterialPropertyStorage & MaterialData::getMaterialPropertyStorageForXFEM (const XFEMKey) inline
Provide write-only access to the underlying MaterialPropertyStorage object JUST FOR XFEM.
This should be removed. To be clear - you should not ever expect to have write access to this data. It just turned out that XFEM got away with it when we were storing things as pointers instead of smart pointers...
These dirty reasons are why this method is named so egregiously.
Definition at line 159 of file MaterialData.h.
{ return _storage; }
getProperty()
template<typename T , bool is_ad = false> GenericMaterialProperty< T, is_ad > & MaterialData::getProperty (const std::string & prop_name, const unsigned int state, const MooseObject & requestor) inline
Retrieves a material property.
Template Parameters
T The type of the property
is_ad Whether or not the property is AD
Parameters
prop_name The name of the property
state The time state (0 = current, 1 = old, etc; defaults to 0)
requestor The MooseObject requesting the property
Returns
The property for the supplied type and name
Definition at line 109 of file MaterialData.h.
  {
    return getPropertyHelper<T, is_ad, false>(prop_name, state, requestor);
  }
Referenced by MaterialPropertyInterface::getBlockMaterialProperty(), MaterialPropertyInterface::getGenericMaterialPropertyByName(), and MaterialBase::getGenericZeroMaterialPropertyByName().
getPropertyHelper()
template<typename T , bool is_ad, bool declare> GenericMaterialProperty< T, is_ad > & MaterialData::getPropertyHelper (const std::string & prop_name, const unsigned int state, const MooseObject & requestor) private
Definition at line 256 of file MaterialData.h.
{
  if constexpr (is_ad)
    mooseAssert(state == 0, "Cannot request/declare AD properties for states other than zero");
  if constexpr (declare)
    mooseAssert(state == 0, "Cannot declare properties for states other than zero");
  // Register/get the ID of the property
  const auto prop_id = addPropertyHelper(prop_name, state);
  // Initialize the states that we need
  const auto size = prop_id + 1;
  for (const auto state_i : make_range(state + 1))
  {
    auto & entry = props(state_i);
    if (entry.size() < size)
      entry.resize(size, {});
    if (!entry.hasValue(prop_id))
    {
      std::unique_ptr<PropertyValue> value =
          state_i == 0 ? std::make_unique<GenericMaterialProperty<T, is_ad>>(prop_id)
                       : _props[0][prop_id].clone(0);
      entry.setPointer(prop_id, std::move(value), {});
    }
  }
  // Should be available now
  auto & base_prop = props(state)[prop_id];
  // In the event that this property was already declared/requested, make sure
  // that the types are consistent
  auto prop = dynamic_cast<GenericMaterialProperty<T, is_ad> *>(&base_prop);
  if (!prop)
  {
    constexpr std::string_view action = declare ? "declared" : "requested";
    constexpr auto is_ad_to_str = [](const bool is_ad_bool)
    { return std::string_view(is_ad_bool ? "AD" : "non-AD"); };
    constexpr std::string_view ad_type = is_ad_to_str(is_ad);
    std::stringstream error;
    error << "The " << action << " " << ad_type << " "
          << "material property '" + prop_name + "' of type '" << MooseUtils::prettyCppType<T>()
          << "'\nis already retrieved or declared as a " << is_ad_to_str(base_prop.isAD())
          << " property of type '" << base_prop.type() << "'.";
    mooseErrorHelper(requestor, error.str());
  }
  return *prop;
}
getPropertyId()
unsigned int MaterialData::getPropertyId (const std::string & prop_name) const
Wrapper for MaterialStorage::getPropertyId.
Allows classes with a MaterialData object (i.e. MaterialPropertyInterface) to access material property IDs.
Parameters
prop_name The name of the material property
Returns
An unsigned int corresponding to the property ID of the passed in prop_name
Definition at line 79 of file MaterialData.C.
{
  return _storage.getMaterialPropertyRegistry().getID(prop_name);
}
Referenced by MaterialPropertyInterface::getBlockMaterialProperty(), MaterialPropertyInterface::getGenericMaterialPropertyByName(), haveGenericProperty(), and MaterialBase::registerPropName().
hasProperty()
bool MaterialData::hasProperty (const std::string & prop_name) const
Returns
Whether or not a property exists with the name name
Definition at line 73 of file MaterialData.C.
{
  return _storage.hasProperty(prop_name);
}
Referenced by haveGenericProperty().
haveADProperty()
template<typename T > bool MaterialData::haveADProperty (const std::string & prop_name) const inline
Returns true if the AD material property exists - defined by any material.
Definition at line 94 of file MaterialData.h.
  {
    return haveGenericProperty<T, true>(prop_name);
  }
Referenced by MaterialPropertyInterface::hasADMaterialPropertyByName(), and MaterialOutputAction::hasADProperty().
haveGenericProperty()
template<typename T , bool is_ad> bool MaterialData::haveGenericProperty (const std::string & prop_name) const inline
Definition at line 240 of file MaterialData.h.
{
  if (!hasProperty(prop_name))
    return false;
  const auto prop_id = getPropertyId(prop_name);
  // the property id exists, but the property was not created in this instance of the material type
  if (prop_id >= props(0).size())
    return false;
  const PropertyValue * const base_prop = props(0).queryValue(prop_id);
  return dynamic_cast<const GenericMaterialProperty<T, is_ad> *>(base_prop) != nullptr;
}
Referenced by BlockRestrictable::hasBlockMaterialProperty(), and BoundaryRestrictable::hasBoundaryMaterialProperty().
haveProperty()
template<typename T > bool MaterialData::haveProperty (const std::string & prop_name) const inline
Returns true if the regular material property exists - defined by any material.
Definition at line 87 of file MaterialData.h.
  {
    return haveGenericProperty<T, false>(prop_name);
  }
Referenced by MaterialPropertyInterface::hasMaterialPropertyByName(), and MaterialOutputAction::hasProperty().
isOnlyResizeIfSmaller()
bool MaterialData::isOnlyResizeIfSmaller () const inline
Check value of _resize_only_if_smaller.
Definition at line 185 of file MaterialData.h.
{ return _resize_only_if_smaller; };
isSwapped()
bool MaterialData::isSwapped () const inline
Returns true if the stateful material is in a swapped state.
Definition at line 133 of file MaterialData.h.
{ return _swapped; }
Referenced by swap(), and swapBack().
mooseErrorHelper()
void MaterialData::mooseErrorHelper (const MooseObject & object, const std::string_view & error) static private
Definition at line 67 of file MaterialData.C.
{
  object.mooseError(error);
}
Referenced by getPropertyHelper().
nQPoints()
unsigned int MaterialData::nQPoints () const inline
Returns the number of quadrature points the material properties support/hold.
Definition at line 48 of file MaterialData.h.
{ return _n_qpoints; }
Referenced by copy(), and resize().
onlyResizeIfSmaller()
void MaterialData::onlyResizeIfSmaller (bool flag) inline
Set _resize_only_if_smaller to perform a non-destructive resize.
Setting this flag to true means that resize(n) will not decrease the size of _props if n is smaller than the size of the material data object.
Definition at line 180 of file MaterialData.h.
{ _resize_only_if_smaller = flag; };
props() [1/2]
MaterialProperties & MaterialData::props (const unsigned int state = 0) inline
Definition at line 232 of file MaterialData.h.
{
  mooseAssert(_props.size() > state, "Invalid state");
  return _props[state];
}
props() [2/2]
const MaterialProperties & MaterialData::props (const unsigned int state = 0) const inline
{
Returns
The properties for the state state (defaults to zero).
This should NEVER be used to modify the size of these objects.
Definition at line 225 of file MaterialData.h.
{
  mooseAssert(_props.size() > state, "Invalid state");
  return _props[state];
}
Referenced by Material::computeProperties(), getPropertyHelper(), haveGenericProperty(), resize(), and Material::subdomainSetup().
reinit()
template<typename MatContainer > void MaterialData::reinit (const MatContainer & mats)
Reinit material properties for given element (and possible side)
Parameters
mats The material objects for which to compute properties
execute_stateful Whether to execute material objects that have stateful properties. This should be false when for example executing material objects for mortar contexts in which stateful properties don't make sense
Definition at line 310 of file MaterialData.h.
{
  for (const auto & mat : mats)
    mat->computeProperties();
}
reset()
void MaterialData::reset (const std::vector< std::shared_ptr< MaterialBase > > & mats)
Calls the reset method of Materials to ensure that they are in a proper state.
Definition at line 50 of file MaterialData.C.
{
  for (const auto & mat : mats)
    mat->resetProperties();
}
resize()
void MaterialData::resize (unsigned int n_qpoints)
Resize the data to hold properties for n_qpoints quadrature points.
Definition at line 20 of file MaterialData.C.
{
  if (n_qpoints == nQPoints())
    return;
  if (_resize_only_if_smaller && n_qpoints < nQPoints())
    return;
  for (const auto state : _storage.stateIndexRange())
    props(state).resizeItems(n_qpoints, {});
  _n_qpoints = n_qpoints;
}
Referenced by ComputeMaterialsObjectThread::onBoundary(), ComputeMaterialsObjectThread::onInterface(), ComputeMaterialsObjectThread::onInternalSide(), MaterialPropertyStorage::prolongStatefulProps(), FEProblemBase::reinitMaterials(), FEProblemBase::reinitMaterialsBoundary(), FEProblemBase::reinitMaterialsFace(), FEProblemBase::reinitMaterialsInterface(), FEProblemBase::reinitMaterialsNeighbor(), FEProblemBase::resizeMaterialData(), and MaterialPropertyStorage::updateStatefulPropsForPRefinement().
swap()
void MaterialData::swap (const Elem & elem, unsigned int side = 0)
material properties for given element (and possible side)
Definition at line 40 of file MaterialData.C.
{
  if (!_storage.hasStatefulProperties() || isSwapped())
    return;
  _storage.swap(_tid, elem, side);
  _swapped = true;
}
swapBack()
void MaterialData::swapBack (const Elem & elem, unsigned int side = 0)
material properties for given element (and possible side)
Definition at line 57 of file MaterialData.C.
{
  if (isSwapped() && _storage.hasStatefulProperties())
  {
    _storage.swapBack(_tid, elem, side);
    _swapped = false;
  }
}
Referenced by FEProblemBase::swapBackMaterials(), FEProblemBase::swapBackMaterialsFace(), and FEProblemBase::swapBackMaterialsNeighbor().
Member Data Documentation
_n_qpoints
unsigned int MaterialData::_n_qpoints private
Number of quadrature points.
Definition at line 202 of file MaterialData.h.
Referenced by nQPoints(), and resize().
_props
std::array<MaterialProperties, max_state + 1> MaterialData::_props private
The underlying property data.
Definition at line 205 of file MaterialData.h.
Referenced by getPropertyHelper(), and props().
_resize_only_if_smaller
bool MaterialData::_resize_only_if_smaller private
Use non-destructive resize of material data (calling resize() will not reduce size).
Default is false (normal resize behaviour)
Definition at line 221 of file MaterialData.h.
Referenced by isOnlyResizeIfSmaller(), onlyResizeIfSmaller(), and resize().
_storage
MaterialPropertyStorage& MaterialData::_storage private
Reference to the MaterialStorage class.
Definition at line 196 of file MaterialData.h.
Referenced by addPropertyHelper(), copy(), eraseProperty(), getMaterialPropertyStorage(), getMaterialPropertyStorageForXFEM(), getPropertyId(), hasProperty(), resize(), swap(), and swapBack().
_swapped
bool MaterialData::_swapped private
Status of storage swapping (calling swap sets this to true; swapBack sets it to false)
Definition at line 217 of file MaterialData.h.
Referenced by isSwapped(), swap(), and swapBack().
_tid
const THREAD_ID MaterialData::_tid private
The thread id.
Definition at line 199 of file MaterialData.h.
Referenced by copy(), swap(), and swapBack().
max_state
constexpr unsigned int MaterialData::max_state = 2 static constexpr
The max time state supported (2 = older)
Definition at line 37 of file MaterialData.h.
Referenced by MaterialPropertyStorage::addProperty().
The documentation for this class was generated from the following files:
moose/framework/include/materials/MaterialData.h
moose/framework/src/materials/MaterialData.C