Zapdos: MaterialBase Class Reference
MaterialBase Class Reference abstract
MaterialBases compute MaterialProperties.
#include <MaterialBase.h>
Public Types
enum TEST_TYPE { ALL , ANY }
A flag changing the behavior of hasBoundary.
Public Member Functions
MaterialBase (const InputParameters &parameters)
virtual void initStatefulProperties (unsigned int n_points)
Initialize stateful properties (if material has some)
virtual bool isInterfaceMaterial ()
virtual void computeProperties ()=0
Performs the quadrature point loop, calling computeQpProperties.
virtual void resetProperties ()
Resets the properties at each quadrature point (see resetQpProperties), only called if 'compute = false'.
virtual void computePropertiesAtQp (unsigned int qp)
A method for (re)computing the properties of a MaterialBase.
template<typename T , bool is_ad>
const GenericMaterialProperty< T, is_ad > & getGenericZeroMaterialProperty (const std::string &name)
Return a material property that is initialized to zero by default and does not need to (but can) be declared by another material.
template<typename T , bool is_ad>
const GenericMaterialProperty< T, is_ad > & getGenericZeroMaterialPropertyByName (const std::string &prop_name)
template<typename T , bool is_ad>
const GenericMaterialProperty< T, is_ad > & getGenericZeroMaterialProperty ()
Return a constant zero anonymous material property.
template<typename T , typename... Ts>
const MaterialProperty< T > & getZeroMaterialProperty (Ts... args)
for backwards compatibility
template<typename T , typename... Ts>
const MaterialProperty< T > & getZeroMaterialPropertyByName (Ts... args)
for backwards compatibility
virtual const std::set< std::string > & getRequestedItems () override
Return a set of properties accessed with getMaterialProperty.
virtual const std::set< std::string > & getSuppliedItems () override
Return a set of properties accessed with declareProperty.
const std::set< unsigned int > & getSuppliedPropIDs ()
Get the prop ids corresponding to declareProperty.
void checkStatefulSanity () const
std::set< OutputName > getOutputs ()
Get the list of output objects that this class is restricted.
virtual bool isBoundaryMaterial () const =0
Returns true of the MaterialData type is not associated with volume data.
virtual void subdomainSetup () override
Subdomain setup evaluating material properties when required.
virtual const std::set< unsigned int > & getMatPropDependencies () const =0
Retrieve the set of material properties that this object depends on.
bool hasStatefulProperties () const
virtual bool ghostable () const
Whether this material supports ghosted computations.
void setFaceInfo (const FaceInfo &fi)
virtual bool enabled () const
Return the enabled status of the object.
MooseApp & getMooseApp () const
Get the MooseApp this class is associated with.
const std::string & type () const
Get the type of this class.
virtual const std::string & name () const
Get the name of the class.
std::string typeAndName () const
Get the class's combined type and name; useful in error handling.
MooseObjectParameterName uniqueParameterName (const std::string &parameter_name) const
The unique parameter name of a valid parameter of this object for accessing parameter controls.
const InputParameters & parameters () const
Get the parameters of the object.
MooseObjectName uniqueName () const
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
template<typename T >
const T & getParam (const std::string &name) const
Retrieve a parameter for the object.
template<typename T1 , typename T2 >
std::vector< std::pair< T1, T2 > > getParam (const std::string &param1, const std::string &param2) const
Retrieve two parameters and provide pair of parameters for the object.
template<typename T >
const T & getRenamedParam (const std::string &old_name, const std::string &new_name) const
Retrieve a renamed parameter for the object.
template<typename T >
T getCheckedPointerParam (const std::string &name, const std::string &error_string="") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
bool isParamValid (const std::string &name) const
Test if the supplied parameter is valid.
bool isParamSetByUser (const std::string &nm) const
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
template<typename... Args>
void paramError (const std::string &param, Args... args) const
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramWarning (const std::string &param, Args... args) const
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramInfo (const std::string &param, Args... args) const
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
std::string objectErrorPrefix (const std::string &error_type) const
A descriptive prefix for errors for an object.
void connectControllableParams (const std::string &parameter, const std::string &object_type, const std::string &object_name, const std::string &object_parameter) const
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
template<typename... Args>
void mooseError (Args &&... args) const
Emits an error prefixed with object name and type.
template<typename... Args>
void mooseErrorNonPrefixed (Args &&... args) const
Emits an error without the prefixing included in mooseError().
template<typename... Args>
void mooseWarning (Args &&... args) const
Emits a warning prefixed with object name and type.
template<typename... Args>
void mooseWarningNonPrefixed (Args &&... args) const
Emits a warning without the prefixing included in mooseWarning().
template<typename... Args>
void mooseDeprecated (Args &&... args) const
template<typename... Args>
void mooseInfo (Args &&... args) const
std::string errorPrefix (const std::string &error_type) const
A descriptive prefix for errors for this object:
std::string getDataFileName (const std::string &param) const
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
std::string getDataFileNameByName (const std::string &name, const std::string *param=nullptr) const
Returns the path of a data file for a given relative file path.
const std::vector< SubdomainName > & blocks () const
Return the block names for this object.
unsigned int numBlocks () const
Return the number of blocks for this object.
virtual const std::set< SubdomainID > & blockIDs () const
Return the block subdomain ids for this object Note, if this is not block restricted, this function returns all mesh subdomain ids.
unsigned int blocksMaxDimension () const
Return the largest mesh dimension of the elements in the blocks for this object.
bool hasBlocks (const SubdomainName &name) const
Test if the supplied block name is valid for this object.
bool hasBlocks (const std::vector< SubdomainName > &names) const
Test if the supplied vector of block names are valid for this object.
bool hasBlocks (SubdomainID id) const
Test if the supplied block ids are valid for this object.
bool hasBlocks (const std::vector< SubdomainID > &ids) const
Test if the supplied vector block ids are valid for this object.
bool hasBlocks (const std::set< SubdomainID > &ids) const
Test if the supplied set of block ids are valid for this object.
bool isBlockSubset (const std::set< SubdomainID > &ids) const
Test if the class block ids are a subset of the supplied objects.
bool isBlockSubset (const std::vector< SubdomainID > &ids) const
Test if the class block ids are a subset of the supplied objects.
template<typename T , bool is_ad = false>
bool hasBlockMaterialProperty (const std::string &prop_name)
Check if a material property is valid for all blocks of this object.
const std::set< SubdomainID > & meshBlockIDs () const
Return all of the SubdomainIDs for the mesh.
virtual bool blockRestricted () const
Returns true if this object has been restricted to a block.
virtual void checkVariable (const MooseVariableFieldBase &variable) const
Helper for checking that the ids for this object are in agreement with the variables on the supplied variable.
virtual const std::set< BoundaryID > & boundaryIDs () const
Return the boundary IDs for this object.
const std::vector< BoundaryName > & boundaryNames () const
Return the boundary names for this object.
unsigned int numBoundaryIDs () const
Return the number of boundaries for this object.
bool hasBoundary (const BoundaryName &name) const
Test if the supplied boundary name is valid for this object.
bool hasBoundary (const std::vector< BoundaryName > &names) const
Test if the supplied vector of boundary names are valid for this object.
bool hasBoundary (const BoundaryID &id) const
Test if the supplied boundary ids are valid for this object.
bool hasBoundary (const std::vector< BoundaryID > &ids, TEST_TYPE type=ALL) const
Test if the supplied vector boundary ids are valid for this object.
bool hasBoundary (const std::set< BoundaryID > &ids, TEST_TYPE type=ALL) const
Test if the supplied set of boundary ids are valid for this object.
bool isBoundarySubset (const std::set< BoundaryID > &ids) const
Test if the class boundary ids are a subset of the supplied objects.
bool isBoundarySubset (const std::vector< BoundaryID > &ids) const
template<typename T , bool is_ad = false>
bool hasBoundaryMaterialProperty (const std::string &prop_name) const
Check if a material property is valid for all boundaries of this object.
virtual bool boundaryRestricted () const
Returns true if this object has been restricted to a boundary.
const std::set< BoundaryID > & meshBoundaryIDs () const
Returns the set of all boundary ids for the entire mesh.
virtual bool checkVariableBoundaryIntegrity () const
Whether integrity/coverage checking should be conducted for moose variables used in this object.
virtual void initialSetup ()
Gets called at the beginning of the simulation before this object is asked to do its job.
virtual void timestepSetup ()
Gets called at the beginning of the timestep before this object is asked to do its job.
virtual void jacobianSetup ()
Gets called just before the Jacobian is computed and before this object is asked to do its job.
virtual void residualSetup ()
Gets called just before the residual is computed and before this object is asked to do its job.
virtual void customSetup (const ExecFlagType &)
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
const ExecFlagEnum & getExecuteOnEnum () const
Return the execute on MultiMooseEnum for this object.
const std::set< MooseVariableFieldBase * > & getMooseVariableDependencies () const
Retrieve the set of MooseVariableFieldBase that this object depends on.
template<typename DofObjectType >
std::set< MooseVariableFieldBase * > checkAllVariables (const DofObjectType &dof_object, const std::set< MooseVariableFieldBase * > &vars_to_omit={})
Check whether all of the variable dependencies have degree of freedom indices on the supplied degree of freedom object.
template<typename DofObjectType >
std::set< MooseVariableFieldBase * > checkVariables (const DofObjectType &dof_object, const std::set< MooseVariableFieldBase * > &vars_to_check)
Check whether all of the supplied variables have degree of freedom indices on the supplied degree of freedom object.
const std::vector< MooseVariableScalar * > & getCoupledMooseScalarVars ()
Get the list of coupled scalar variables.
const std::set< TagID > & getScalarVariableCoupleableVectorTags () const
const std::set< TagID > & getScalarVariableCoupleableMatrixTags () const
const Function & getFunction (const std::string &name) const
Get a function with a given name.
const Function & getFunctionByName (const FunctionName &name) const
Get a function with a given name.
bool hasFunction (const std::string &param_name) const
Determine if the function exists.
bool hasFunctionByName (const FunctionName &name) const
Determine if the function exists.
UserObjectName getUserObjectName (const std::string &param_name) const
template<class T >
const T & getUserObject (const std::string &param_name, bool is_dependency=true) const
Get an user object with a given parameter param_name.
template<class T >
const T & getUserObjectByName (const UserObjectName &object_name, bool is_dependency=true) const
Get an user object with the name object_name.
const UserObject & getUserObjectBase (const std::string &param_name, bool is_dependency=true) const
Get an user object with a given parameter param_name.
const UserObject & getUserObjectBaseByName (const UserObjectName &object_name, bool is_dependency=true) const
Get an user object with the name object_name.
bool isImplicit ()
bool isDefaultPostprocessorValue (const std::string &param_name, const unsigned int index=0) const
Determine whether or not the Postprocessor is a default value.
bool hasPostprocessor (const std::string &param_name, const unsigned int index=0) const
Determine if the Postprocessor data exists.
bool hasPostprocessorByName (const PostprocessorName &name) const
Determine if the Postprocessor data exists.
std::size_t coupledPostprocessors (const std::string &param_name) const
Returns number of Postprocessors coupled under parameter name.
const PostprocessorName & getPostprocessorName (const std::string &param_name, const unsigned int index=0) const
Get the name of a postprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValue (const std::string &param_name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValue (const std::string &param_name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the value of a VectorPostprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValueByName (const VectorPostprocessorName &name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValueByName (const VectorPostprocessorName &name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the value of the VectorPostprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValueOld (const std::string &param_name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValueOld (const std::string &param_name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the old value of a VectorPostprocessor.
const VectorPostprocessorValue & getVectorPostprocessorValueOldByName (const VectorPostprocessorName &name, const std::string &vector_name) const
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
const VectorPostprocessorValue & getVectorPostprocessorValueOldByName (const VectorPostprocessorName &name, const std::string &vector_name, bool needs_broadcast) const
Retrieve the old value of a VectorPostprocessor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValue (const std::string &param_name, const std::string &vector_name) const
Return the scatter value for the post processor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValueByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Return the scatter value for the post processor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValueOld (const std::string &param_name, const std::string &vector_name) const
Return the old scatter value for the post processor.
const ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValueOldByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Return the old scatter value for the post processor.
bool hasVectorPostprocessor (const std::string &param_name, const std::string &vector_name) const
Determine if the VectorPostprocessor data exists by parameter.
bool hasVectorPostprocessor (const std::string &param_name) const
Determine if the VectorPostprocessor exists by parameter.
bool hasVectorPostprocessorByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Determine if the VectorPostprocessor data exists by name.
bool hasVectorPostprocessorByName (const VectorPostprocessorName &name) const
Determine if the VectorPostprocessor exists by name.
const VectorPostprocessorName & getVectorPostprocessorName (const std::string &param_name) const
Get the name of a VectorPostprocessor associated with a parameter.
virtual void meshChanged ()
Called on this object when the mesh changes.
void buildOutputHideVariableList (std::set< std::string > variable_names)
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
void setRandomResetFrequency (ExecFlagType exec_flag)
This interface should be called from a derived class to enable random number generation in this object.
unsigned long getRandomLong () const
Returns the next random number (long) from the generator tied to this object (elem/node).
Real getRandomReal () const
Returns the next random number (Real) from the generator tied to this object (elem/node).
unsigned int getSeed (std::size_t id)
Get the seed for the passed in elem/node id.
unsigned int getMasterSeed () const
bool isNodal () const
ExecFlagType getResetOnTime () const
void setRandomDataPointer (RandomData *random_data)
virtual unsigned int getElementIDIndex (const std::string &id_parameter_name, unsigned int comp=0) const
Gets index of an element integer with a parameter of the object derived from this interface.
virtual unsigned int getElementIDIndexByName (const std::string &id_name) const
Return the accessing integer for an extra element integer with its name.
virtual const dof_id_type & getElementID (const std::string &id_parameter_name, unsigned int comp=0) const
Gets an element integer with a parameter of the object derived from this interface.
dof_id_type getElementID (const Elem *elem, unsigned int elem_id_index) const
Get an element integer for an element.
virtual const dof_id_type & getElementIDNeighbor (const std::string &id_parameter_name, unsigned int comp=0) const
Gets a neighbor element integer with a parameter of the object derived from this interface.
virtual const dof_id_type & getElementIDByName (const std::string &id_name) const
Gets an element integer with the element integer name.
virtual const dof_id_type & getElementIDNeighborByName (const std::string &id_name) const
Gets a neighbor element integer with the element integer name.
bool hasElementID (const std::string &id_name) const
Whether mesh has an element integer with a given name.
dof_id_type maxElementID (unsigned int elem_id_index) const
Return the maximum element ID for an element integer with its index.
dof_id_type minElementID (unsigned int elem_id_index) const
Return the minimum element ID for an element integer with its index.
bool areElemIDsIdentical (const std::string &id_name1, const std::string &id_name2) const
Whether two element integers are identical for all elements.
std::unordered_map< dof_id_type, std::set< dof_id_type > > getElemIDMapping (const std::string &id_name1, const std::string &id_name2) const
Get the mapping from IDs of one extra element integer to another given the two integer names.
std::set< dof_id_type > getAllElemIDs (unsigned int elem_id_index) const
Return all the unique element IDs for an element integer with its index on the entire domain.
std::set< dof_id_type > getElemIDsOnBlocks (unsigned int elem_id_index, const std::set< SubdomainID > &blks) const
Return all the unique element IDs for an extra element integer with its index on a set of subdomains.
template<typename T >
MaterialProperty< T > & declarePropertyByName (const std::string &prop_name)
Declare the property named "name".
template<typename T >
MaterialProperty< T > & declareProperty (const std::string &name)
template<typename T >
ADMaterialProperty< T > & declareADPropertyByName (const std::string &prop_name)
template<typename T >
ADMaterialProperty< T > & declareADProperty (const std::string &name)
template<typename T , bool is_ad>
auto & declareGenericProperty (const std::string &prop_name)
template<typename T , bool is_ad>
GenericMaterialProperty< T, is_ad > & declareGenericPropertyByName (const std::string &prop_name)
const Distribution & getDistribution (const std::string &name) const
Get a distribution with a given name.
template<typename T >
const T & getDistribution (const std::string &name) const
const Distribution & getDistributionByName (const DistributionName &name) const
Get a distribution with a given name.
template<typename T >
const T & getDistributionByName (const std::string &name) const
bool hasUserObject (const std::string &param_name) const
template<class T >
bool hasUserObject (const std::string &param_name) const
bool hasUserObjectByName (const UserObjectName &object_name) const
template<class T >
bool hasUserObjectByName (const UserObjectName &object_name) const
const PostprocessorValue & getPostprocessorValue (const std::string &param_name, const unsigned int index=0) const
doco-normal-methods-begin Retrieve the value of a Postprocessor or one of it's old or older values
const PostprocessorValue & getPostprocessorValueOld (const std::string &param_name, const unsigned int index=0) const
const PostprocessorValue & getPostprocessorValueOlder (const std::string &param_name, const unsigned int index=0) const
virtual const PostprocessorValue & getPostprocessorValueByName (const PostprocessorName &name) const
Retrieve the value of the Postprocessor.
const PostprocessorValue & getPostprocessorValueOldByName (const PostprocessorName &name) const
const PostprocessorValue & getPostprocessorValueOlderByName (const PostprocessorName &name) const
bool isVectorPostprocessorDistributed (const std::string &param_name) const
Return true if the VectorPostprocessor is marked with parallel_type as DISTRIBUTED.
bool isVectorPostprocessorDistributedByName (const VectorPostprocessorName &name) const
Static Public Member Functions
static InputParameters validParams ()
template<typename Consumers >
static std::deque< MaterialBase * > buildRequiredMaterials (const Consumers &mat_consumers, const std::vector< std::shared_ptr< MaterialBase > > &mats, const bool allow_stateful)
Build the materials required by a set of consumer objects.
static bool restricted (const std::set< BoundaryID > &ids)
Helper for determining if the object is boundary restricted.
template<typename T >
static void sort (typename std::vector< T > &vector)
Given a vector, sort using the getRequested/SuppliedItems sets.
template<typename T >
static void sortDFS (typename std::vector< T > &vector)
Given a vector, sort using the depth-first search.
template<typename T , typename T2 >
static void cyclicDependencyError (CyclicDependencyException< T2 > &e, const std::string &header)
A helper method for cyclic errors.
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Types
enum QP_Data_Type { CURR , PREV }
Protected Member Functions
virtual void computeQpProperties ()
Users must override this method.
virtual void resetQpProperties ()
Resets the properties prior to calculation of traditional materials (only if 'compute = false').
virtual void initQpStatefulProperties ()
Initialize stateful properties at quadrature points.
virtual const MaterialData & materialData () const =0
virtual MaterialData & materialData ()=0
virtual const FEProblemBase & miProblem () const
virtual FEProblemBase & miProblem ()
virtual const QBase & qRule () const =0
void registerPropName (const std::string &prop_name, bool is_get, const unsigned int state)
Small helper function to call store{Subdomain,Boundary}MatPropName.
void checkExecutionStage ()
Check and throw an error if the execution has progressed past the construction stage.
virtual bool hasBlockMaterialPropertyHelper (const std::string &prop_name)
A helper method to allow the Material object to specialize the behavior of hasBlockMaterialProperty.
void initializeBlockRestrictable (const MooseObject *moose_object)
An initialization routine needed for dual constructors.
Moose::CoordinateSystemType getBlockCoordSystem ()
Check if the blocks this object operates on all have the same coordinate system, and if so return it.
bool hasBoundaryMaterialPropertyHelper (const std::string &prop_name) const
A helper method to avoid circular #include problems.
void addMooseVariableDependency (MooseVariableFieldBase *var)
Call this function to add the passed in MooseVariableFieldBase as a variable that this object depends on.
void addMooseVariableDependency (const std::vector< MooseVariableFieldBase * > &vars)
bool isCoupledScalar (const std::string &var_name, unsigned int i=0) const
Returns true if a variables has been coupled_as name.
unsigned int coupledScalarComponents (const std::string &var_name) const
Return the number of components to the coupled scalar variable.
unsigned int coupledScalar (const std::string &var_name, unsigned int comp=0) const
Returns the index for a scalar coupled variable by name.
Order coupledScalarOrder (const std::string &var_name, unsigned int comp=0) const
Returns the order for a scalar coupled variable by name.
const VariableValue & coupledScalarValue (const std::string &var_name, unsigned int comp=0) const
Returns value of a scalar coupled variable.
const ADVariableValue & adCoupledScalarValue (const std::string &var_name, unsigned int comp=0) const
Returns AD value of a scalar coupled variable.
template<bool is_ad>
const GenericVariableValue< is_ad > & coupledGenericScalarValue (const std::string &var_name, unsigned int comp=0) const
Returns value of a coupled scalar variable for use in templated automatic differentiation classes.
template<>
const GenericVariableValue< false > & coupledGenericScalarValue (const std::string &var_name, unsigned int comp) const
template<>
const GenericVariableValue< true > & coupledGenericScalarValue (const std::string &var_name, unsigned int comp) const
const VariableValue & coupledVectorTagScalarValue (const std::string &var_name, TagID tag, unsigned int comp=0) const
Returns value of a scalar coupled variable.
const VariableValue & coupledMatrixTagScalarValue (const std::string &var_name, TagID tag, unsigned int comp=0) const
Returns value of a scalar coupled variable.
const VariableValue & coupledScalarValueOld (const std::string &var_name, unsigned int comp=0) const
Returns the old (previous time step) value of a scalar coupled variable.
const VariableValue & coupledScalarValueOlder (const std::string &var_name, unsigned int comp=0) const
Returns the older (two time steps previous) value of a scalar coupled variable.
const VariableValue & coupledScalarDot (const std::string &var_name, unsigned int comp=0) const
Returns the time derivative of a scalar coupled variable.
const VariableValue & coupledScalarDotDot (const std::string &var_name, unsigned int comp=0) const
Returns the second time derivative of a scalar coupled variable.
const VariableValue & coupledScalarDotOld (const std::string &var_name, unsigned int comp=0) const
Returns the old time derivative of a scalar coupled variable.
const VariableValue & coupledScalarDotDotOld (const std::string &var_name, unsigned int comp=0) const
Returns the old second time derivative of a scalar coupled variable.
const VariableValue & coupledScalarDotDu (const std::string &var_name, unsigned int comp=0) const
Time derivative of a scalar coupled variable with respect to the coefficients.
const VariableValue & coupledScalarDotDotDu (const std::string &var_name, unsigned int comp=0) const
Second time derivative of a scalar coupled variable with respect to the coefficients.
const MooseVariableScalar * getScalarVar (const std::string &var_name, unsigned int comp) const
Extract pointer to a scalar coupled variable.
virtual void addUserObjectDependencyHelper (const UserObject &) const
Helper for deriving classes to override to add dependencies when a UserObject is requested.
Moose::StateArg determineState () const
Create a functor state argument that corresponds to the implicit state of this object.
virtual void addPostprocessorDependencyHelper (const PostprocessorName &) const
Helper for deriving classes to override to add dependencies when a Postprocessor is requested.
virtual void addVectorPostprocessorDependencyHelper (const VectorPostprocessorName &) const
Helper for deriving classes to override to add dependencies when a VectorPostprocessor is requested.
template<typename T , typename... Args>
T & declareRestartableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
ManagedValue< T > declareManagedRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declares a piece of "managed" restartable data and initialize it.
template<typename T , typename... Args>
const T & getRestartableData (const std::string &data_name) const
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
template<typename T , typename... Args>
T & declareRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
T & declareRecoverableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "recoverable" and initialize it.
template<typename T , typename... Args>
T & declareRestartableDataWithObjectName (const std::string &data_name, const std::string &object_name, Args &&... args)
Declare a piece of data as "restartable".
template<typename T , typename... Args>
T & declareRestartableDataWithObjectNameWithContext (const std::string &data_name, const std::string &object_name, void *context, Args &&... args)
Declare a piece of data as "restartable".
std::string restartableName (const std::string &data_name) const
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
PenetrationLocator & getPenetrationLocator (const BoundaryName &primary, const BoundaryName &secondary, Order order)
Retrieve the PentrationLocator associated with the two sides.
PenetrationLocator & getQuadraturePenetrationLocator (const BoundaryName &primary, const BoundaryName &secondary, Order order)
Retrieve the Quadrature PentrationLocator associated with the two sides.
NearestNodeLocator & getNearestNodeLocator (const BoundaryName &primary, const BoundaryName &secondary)
Retrieve the PentrationLocator associated with the two sides.
NearestNodeLocator & getQuadratureNearestNodeLocator (const BoundaryName &primary, const BoundaryName &secondary)
Retrieve a Quadrature NearestNodeLocator associated with the two sides.
bool requiresGeometricSearch () const
Whether any of this interface's methods have been called, e.g.
std::string deduceFunctorName (const std::string &name) const
Small helper to look up a functor name through the input parameter keys.
template<typename T >
const Moose::Functor< T > & getFunctor (const std::string &name)
Retrieves a functor from the subproblem.
template<typename T >
const Moose::Functor< T > & getFunctor (const std::string &name, THREAD_ID tid)
Retrieves a functor from the subproblem.
template<typename T >
const Moose::Functor< T > & getFunctor (const std::string &name, SubProblem &subproblem)
Retrieves a functor from the passed-in subproblem.
template<typename T >
const Moose::Functor< T > & getFunctor (const std::string &name, SubProblem &subproblem, THREAD_ID tid)
Retrieves a functor from the passed-in subproblem.
bool isFunctor (const std::string &name) const
Checks the subproblem for the given functor.
bool isFunctor (const std::string &name, const SubProblem &subproblem) const
Checks the passed-in subproblem for the given functor.
Moose::ElemArg makeElemArg (const Elem *elem, bool correct_skewnewss=false) const
Helper method to create an elemental argument for a functor that includes whether to perform skewness corrections.
template<>
const Moose::Functor< Real > * defaultFunctor (const std::string &name)
void flagInvalidSolutionInternal (InvalidSolutionID _invalid_solution_id) const
Set solution invalid mark for the given solution ID.
InvalidSolutionID registerInvalidSolutionInternal (const std::string &message) const
Static Protected Member Functions
static std::string deduceFunctorName (const std::string &name, const InputParameters &params)
Helper to look up a functor name through the input parameter keys.
Protected Attributes
SubProblem & _subproblem
FEProblemBase & _fe_problem
THREAD_ID _tid
Assembly & _assembly
unsigned int _qp
const MooseArray< Real > & _coord
const MooseArray< Point > & _normals
normals at quadrature points (valid only in boundary materials)
MooseMesh & _mesh
const Moose::CoordinateSystemType & _coord_sys
Coordinate system.
std::set< std::string > _requested_props
Set of properties accessed via get method.
std::set< std::string > _supplied_props
Set of properties declared.
std::set< unsigned int > _supplied_prop_ids
The ids of the supplied properties, i.e.
const bool _compute
If False MOOSE does not compute this property.
std::unordered_map< unsigned int, unsigned int > _props_to_min_states
The minimum states requested (0 = current, 1 = old, 2 = older) This is sparse and is used to keep track of whether or not stateful properties are requested without state 0 being requested.
std::vector< unsigned int > _displacements
bool _has_stateful_property
bool _overrides_init_stateful_props = true
const FaceInfo * _face_info = nullptr
const bool & _enabled
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
MooseApp & _app
The MOOSE application this is associated with.
const std::string & _type
The type of this class.
const std::string & _name
The name of this class, reference to value stored in InputParameters.
const InputParameters & _pars
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Factory & _factory
The Factory associated with the MooseApp.
ActionFactory & _action_factory
Builds Actions.
const MaterialData * _blk_material_data
Pointer to the MaterialData class for this object.
const ExecFlagEnum & _execute_enum
Execute settings for this object.
const ExecFlagType & _current_execute_flag
Reference to FEProblemBase.
FEProblemBase & _sc_fe_problem
const THREAD_ID _sc_tid
Thread ID of the thread using this object.
const Real & _real_zero
Scalar zero.
const VariableValue & _scalar_zero
Zero value of a scalar variable.
const Point & _point_zero
Zero point.
const InputParameters & _ti_params
FEProblemBase & _ti_feproblem
bool _is_implicit
If the object is using implicit or explicit form.
Real & _t
Time.
int & _t_step
The number of the time step.
Real & _dt
Time step size.
Real & _dt_old
Size of the old time step.
bool _is_transient
MooseApp & _restartable_app
Reference to the application.
const std::string _restartable_system_name
The system name this object is in.
const THREAD_ID _restartable_tid
The thread ID for this object.
const bool _restartable_read_only
Flag for toggling read only status (see ReporterData)
FEProblemBase & _mci_feproblem
Reference to FEProblemBase instance.
GeometricSearchData & _geometric_search_data
bool _requires_geometric_search
Whether any of this interface's methods have been called, e.g.
Private Member Functions
template<typename... Args>
std::string paramErrorMsg (const std::string &param, Args... args) const
void initializeBoundaryRestrictable ()
An initialization routine needed for dual constructors.
const VariableValue * getDefaultValue (const std::string &var_name) const
Helper method to return (and insert if necessary) the default value for an uncoupled variable.
const ADVariableValue * getADDefaultValue (const std::string &var_name) const
Helper method to return (and insert if necessary) the AD default value for an uncoupled variable.
void checkVar (const std::string &var_name) const
Check that the right kind of variable is being coupled in.
void validateExecutionerType (const std::string &name, const std::string &fn_name) const
Checks to make sure that the current Executioner has set "_is_transient" when old/older values are coupled in.
template<class T >
const T & castUserObject (const UserObject &uo_base, const std::string &param_name="") const
Internal helper that casts the UserObject uo_base to the reqested type.
const std::string & userObjectType (const UserObject &uo) const
Gets a UserObject's type; avoids including UserObject.h in the UserObjectInterface.
const std::string & userObjectName (const UserObject &uo) const
Gets a UserObject's name; avoids including UserObject.h in the UserObjectInterface.
const PostprocessorName & getPostprocessorNameInternal (const std::string &param_name, const unsigned int index, const bool allow_default_value=true) const
Internal method for getting the PostprocessorName associated with a paremeter.
bool isDefaultPostprocessorValueByName (const PostprocessorName &name) const
PostprocessorValue getDefaultPostprocessorValueByName (const PostprocessorName &name) const
void checkParam (const std::string &param_name, const unsigned int index=std::numeric_limits< unsigned int >::max()) const
Checks the parameters relating to a Postprocessor.
bool postprocessorsAdded () const
const VectorPostprocessorValue & getVectorPostprocessorByNameHelper (const VectorPostprocessorName &name, const std::string &vector_name, bool broadcast, std::size_t t_index) const
Helper function for extracting VPP data from ReporterData object.
const VectorPostprocessorContext< VectorPostprocessorValue > & getVectorPostprocessorContextByNameHelper (const VectorPostprocessorName &name, const std::string &vector_name) const
Helper for getting the VPP context that handles scatter values.
bool vectorPostprocessorsAdded () const
RestartableDataValue & registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const
Helper function for actually registering the restartable data.
void registerRestartableNameWithFilterOnApp (const std::string &name, Moose::RESTARTABLE_FILTER filter)
Helper function for actually registering the restartable data.
template<typename T , typename... Args>
RestartableData< T > & declareRestartableDataHelper (const std::string &data_name, void *context, Args &&... args) const
Helper function for declaring restartable data.
virtual bool isADObject () const override
Whether this interface is for an AD object.
template<typename T >
const Moose::Functor< T > & getFunctorByName (const std::string &name, SubProblem &subproblem, THREAD_ID tid)
Retrieves a functor from the passed-in subproblem.
template<typename T >
const Moose::Functor< T > * defaultFunctor (const std::string &name)
Helper function to parse default functor values.
template<>
const Moose::Functor< Real > * defaultFunctor (const std::string &name)
template<>
const Moose::Functor< ADReal > * defaultFunctor (const std::string &name)
const PostprocessorValue & getPostprocessorValueInternal (const std::string &param_name, unsigned int index, std::size_t t_index) const
Internal methods for getting Postprocessor values.
const PostprocessorValue & getPostprocessorValueByNameInternal (const PostprocessorName &name, std::size_t t_index) const
void possiblyCheckHasVectorPostprocessor (const std::string &param_name, const std::string &vector_name) const
Helpers for "possibly" checking if a vpp exists.
void possiblyCheckHasVectorPostprocessorByName (const VectorPostprocessorName &name, const std::string &vector_name) const
Private Attributes
const MaterialPropertyName _declare_suffix
const MooseBase *const _moose_base
The MooseBase object that inherits this class.
const MooseObject & _parent
std::set< SubdomainID > _blk_ids
Set of block ids supplied by the user via the input file (for error checking)
std::vector< SubdomainID > _vec_ids
Vector of block ids supplied by the user via the input file (for error reporting)
std::vector< SubdomainName > _blocks
Vector the block names supplied by the user via the input file.
const bool _blk_dual_restrictable
Flag for allowing dual restriction.
FEProblemBase * _blk_feproblem
Pointer to FEProblemBase.
MooseMesh * _blk_mesh
Pointer to Mesh.
const std::set< BoundaryID > _empty_boundary_ids
An empty set for referencing when boundary_ids is not included.
const std::set< BoundaryID > & _boundary_ids
Reference to the boundary_ids, defaults to an empty set if not provided.
THREAD_ID _blk_tid
Thread id for this object.
const std::string & _blk_name
Name of the object.
unsigned int _blk_dim
Largest mesh dimension of the elements in the blocks for this object.
FEProblemBase * _bnd_feproblem
Pointer to FEProblemBase.
MooseMesh * _bnd_mesh
Point to mesh.
std::set< BoundaryID > _bnd_ids
Set of the boundary ids.
std::vector< BoundaryName > _boundary_names
Vector the the boundary names.
const bool _bnd_dual_restrictable
Flag for allowing dual restriction with BlockRestrictable.
const std::set< SubdomainID > _empty_block_ids
An empty set for referencing when block_ids is not included.
const std::set< SubdomainID > & _block_ids
Reference to the block_ids, defaults to an empty set if not provided.
THREAD_ID _bnd_tid
Thread id for this object.
const MaterialData & _bnd_material_data
Pointer to MaterialData for boundary (.
bool _bnd_nodal
Whether or not this object is restricted to nodesets.
const MooseObject & _moose_object
The moose object that this is an interface for.
ExecFlagEnum _empty_execute_enum
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
std::set< MooseVariableFieldBase * > _moose_variable_dependencies
std::vector< libMesh::dof_id_type > _dof_indices
A container for holding dof indices in order to avoid constant memory reallocation.
const InputParameters & _sc_parameters
const std::string & _sc_name
The name of the object this interface is part of.
const bool _sc_is_implicit
True if implicit value is required.
std::unordered_map< std::string, std::vector< MooseVariableScalar * > > _coupled_scalar_vars
Coupled vars whose values we provide.
std::unordered_map< std::string, std::unique_ptr< VariableValue > > _default_value
Will hold the default value for optional coupled scalar variables.
std::unordered_map< std::string, std::unique_ptr< ADVariableValue > > _dual_default_value
Will hold the default AD value for optional coupled scalar variables.
std::vector< MooseVariableScalar * > _coupled_moose_scalar_vars
Vector of coupled variables.
std::unordered_map< std::string, std::vector< MooseVariableFieldBase * > > _sc_coupled_vars
Field variables coupled into this object (for error checking)
std::set< TagID > _sc_coupleable_vector_tags
The scalar coupleable vector tags.
std::set< TagID > _sc_coupleable_matrix_tags
The scalar coupleable matrix tags.
const InputParameters & _fni_params
Parameters of the object with this interface.
FEProblemBase & _fni_feproblem
Reference to FEProblemBase instance.
const THREAD_ID _fni_tid
Thread ID.
const InputParameters & _dni_params
Parameters of the object with this interface.
FEProblemBase & _dni_feproblem
Reference to FEProblemBase instance.
const MooseObject *const _dni_moose_object_ptr
Pointer to the MooseObject.
const MooseObject & _uoi_moose_object
Moose object using the interface.
const FEProblemBase & _uoi_feproblem
Reference to the FEProblemBase instance.
const THREAD_ID _uoi_tid
Thread ID.
const std::string _ti_name
const MooseObject & _ppi_moose_object
The MooseObject that uses this interface.
const InputParameters & _ppi_params
PostprocessorInterface Parameters.
const FEProblemBase & _ppi_feproblem
Reference the the FEProblemBase class.
std::map< PostprocessorName, std::unique_ptr< PostprocessorValue > > _default_values
Holds the default postprocessor values that are requested (key is PostprocessorName)
const bool _broadcast_by_default
Whether or not to force broadcasting by default.
const MooseObject & _vpi_moose_object
The MooseObject that uses this interface.
const FEProblemBase & _vpi_feproblem
Reference the FEProblemBase class.
const THREAD_ID _vpi_tid
Thread ID.
const RestartableDataMapName _metaname
Restartable metadata name.
std::string _restartable_name
The name of the object.
MooseApp & _oi_moose_app
Reference the the MooseApp; neede for access to the OutputWarehouse.
OutputWarehouse & _oi_output_warehouse
Reference to the OutputWarehouse for populating the Output object hide lists.
std::set< OutputName > _oi_outputs
The set of Output object names listed in the 'outputs' parameter.
RandomData * _random_data
MooseRandom * _generator
FEProblemBase & _ri_problem
const std::string _ri_name
unsigned int _master_seed
bool _is_nodal
ExecFlagType _reset_on
const Node *const & _curr_node
const Elem *const & _curr_element
const InputParameters & _obj_parameters
Reference to the object's input parameters.
std::shared_ptr< MooseMesh > & _id_mesh
References to the mesh and displaced mesh (currently in the ActionWarehouse)
const std::string & _ei_name
Name of the object using this interface.
const InputParameters & _fi_params
Parameters of the object with this interface.
const std::string _fi_name
The name of the object that this interface belongs to.
SubProblem *const _fi_subproblem
Pointer to subproblem if the subproblem pointer parameter was set.
const THREAD_ID _fi_tid
Current threaded it.
std::vector< std::unique_ptr< Moose::Functor< Real > > > _default_real_functors
Storage vector for Moose::Functor<Real> default objects.
std::vector< std::unique_ptr< Moose::Functor< ADReal > > > _default_ad_real_functors
Storage vector for Moose::Functor<ADReal> default objects.
MooseObject & _si_moose_object
The MooseObject that owns this interface.
FEProblemBase & _si_problem
A reference to FEProblem base.
Detailed Description
MaterialBases compute MaterialProperties.
Definition at line 59 of file MaterialBase.h.
Member Enumeration Documentation
QP_Data_Type
enum MaterialBase::QP_Data_Type protected
Enumerator
CURR
PREV
Definition at line 315 of file MaterialBase.h.
  {
    CURR,
    PREV
  };
TEST_TYPE
enum BoundaryRestrictable::TEST_TYPE inherited
A flag changing the behavior of hasBoundary.
Enumerator
ALL
ANY
Definition at line 29 of file BoundaryRestrictable.h.
  {
    ALL,
    ANY
  };
Constructor & Destructor Documentation
MaterialBase()
MaterialBase::MaterialBase (const InputParameters & parameters)
Definition at line 71 of file MaterialBase.C.
  : MooseObject(parameters),
    BlockRestrictable(this),
    BoundaryRestrictable(this, blockIDs(), false), // false for being _not_ nodal
    SetupInterface(this),
    MooseVariableDependencyInterface(this),
    ScalarCoupleable(this),
    FunctionInterface(this),
    DistributionInterface(this),
    UserObjectInterface(this),
    TransientInterface(this),
    PostprocessorInterface(this),
    VectorPostprocessorInterface(this),
    DependencyResolverInterface(),
    Restartable(this, "MaterialBases"),
    MeshChangedInterface(parameters),
    // The false flag disables the automatic call buildOutputVariableHideList;
    // for MaterialBase objects the hide lists are handled by MaterialBaseOutputAction
    OutputInterface(parameters, false),
    RandomInterface(parameters,
                    *parameters.getCheckedPointerParam<FEProblemBase *>("_fe_problem_base"),
                    parameters.get<THREAD_ID>("_tid"),
                    false),
    ElementIDInterface(this),
    GeometricSearchInterface(this),
    ADFunctorInterface(this),
    SolutionInvalidInterface(this),
    _subproblem(*getCheckedPointerParam<SubProblem *>("_subproblem")),
    _fe_problem(*getCheckedPointerParam<FEProblemBase *>("_fe_problem_base")),
    _tid(parameters.get<THREAD_ID>("_tid")),
    _assembly(_subproblem.assembly(_tid, 0)),
    _qp(std::numeric_limits<unsigned int>::max()),
    _coord(_assembly.coordTransformation()),
    _normals(_assembly.normals()),
    _mesh(_subproblem.mesh()),
    _coord_sys(_assembly.coordSystem()),
    _compute(getParam<bool>("compute")),
    _has_stateful_property(false),
    _declare_suffix(getParam<MaterialPropertyName>("declare_suffix"))
{
}
Member Function Documentation
adCoupledScalarValue()
const ADVariableValue & ScalarCoupleable::adCoupledScalarValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns AD value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a ADVariableValue for the coupled variable
Definition at line 135 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getADDefaultValue(var_name);
  auto var = getScalarVar(var_name, comp);
  if (_sc_is_implicit)
    return var->adSln();
  else
    mooseError("adCoupledValue for non-implicit calculations is not currently supported. Use "
               "coupledValue instead for non-implicit");
}
Referenced by ScalarCoupleable::coupledGenericScalarValue().
addMooseVariableDependency() [1/2]
void MooseVariableDependencyInterface::addMooseVariableDependency (const std::vector< MooseVariableFieldBase * > & vars) inline protected inherited
Definition at line 77 of file MooseVariableDependencyInterface.h.
  {
    _moose_variable_dependencies.insert(vars.begin(), vars.end());
  }
addMooseVariableDependency() [2/2]
void MooseVariableDependencyInterface::addMooseVariableDependency (MooseVariableFieldBase * var) inline protected inherited
Call this function to add the passed in MooseVariableFieldBase as a variable that this object depends on.
Definition at line 73 of file MooseVariableDependencyInterface.h.
  {
    _moose_variable_dependencies.insert(var);
  }
Referenced by ADDGKernel::ADDGKernel(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADInterfaceKernelTempl< T >::ADInterfaceKernelTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayNodalBC::ArrayNodalBC(), AuxNodalScalarKernel::AuxNodalScalarKernel(), CoupleableMooseVariableDependencyIntermediateInterface::CoupleableMooseVariableDependencyIntermediateInterface(), DGKernel::DGKernel(), DiracKernelTempl< T >::DiracKernelTempl(), DomainUserObject::DomainUserObject(), ElemElemConstraint::ElemElemConstraint(), ElementIndicator::ElementIndicator(), ElementIntegralArrayVariablePostprocessor::ElementIntegralArrayVariablePostprocessor(), ElementIntegralVariablePostprocessor::ElementIntegralVariablePostprocessor(), ElementIntegralVariableUserObject::ElementIntegralVariableUserObject(), ElementUserObject::ElementUserObject(), ElementVariablePostprocessor::ElementVariablePostprocessor(), FVBoundaryCondition::FVBoundaryCondition(), FVInterfaceKernel::FVInterfaceKernel(), IntegratedBC::IntegratedBC(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceMaterial::InterfaceMaterial(), InterfaceUserObjectBase::InterfaceUserObjectBase(), InternalSideIndicator::InternalSideIndicator(), InternalSideIntegralVariablePostprocessor::InternalSideIntegralVariablePostprocessor(), InternalSideUserObject::InternalSideUserObject(), Kernel::Kernel(), Marker::Marker(), Material::Material(), MortarConstraintBase::MortarConstraintBase(), NeighborCoupleableMooseVariableDependencyIntermediateInterface::NeighborCoupleableMooseVariableDependencyIntermediateInterface(), NodalBC::NodalBC(), NodalConstraint::NodalConstraint(), NodalKernel::NodalKernel(), NodalScalarKernel::NodalScalarKernel(), NodalUserObject::NodalUserObject(), NodeElemConstraint::NodeElemConstraint(), NodeFaceConstraint::NodeFaceConstraint(), PointVariableSamplerBase::PointVariableSamplerBase(), QuadraturePointMarker::QuadraturePointMarker(), SideIntegralVariablePostprocessor::SideIntegralVariablePostprocessor(), SideIntegralVariableUserObject::SideIntegralVariableUserObject(), SideUserObject::SideUserObject(), SideVariablePostprocessor::SideVariablePostprocessor(), VectorIntegratedBC::VectorIntegratedBC(), VectorKernel::VectorKernel(), and VectorNodalBC::VectorNodalBC().
addPostprocessorDependencyHelper()
virtual void PostprocessorInterface::addPostprocessorDependencyHelper (const PostprocessorName &) const inline protected virtual inherited
Helper for deriving classes to override to add dependencies when a Postprocessor is requested.
Reimplemented in UserObject, AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, AuxKernelTempl< RealVectorValue >, and InitialConditionBase.
Definition at line 141 of file PostprocessorInterface.h.
{}
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal().
addUserObjectDependencyHelper()
virtual void UserObjectInterface::addUserObjectDependencyHelper (const UserObject &) const inline protected virtual inherited
Helper for deriving classes to override to add dependencies when a UserObject is requested.
Reimplemented in UserObject, AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, AuxKernelTempl< RealVectorValue >, and InitialConditionBase.
Definition at line 108 of file UserObjectInterface.h.
{}
Referenced by UserObjectInterface::getUserObjectBaseByName().
addVectorPostprocessorDependencyHelper()
virtual void VectorPostprocessorInterface::addVectorPostprocessorDependencyHelper (const VectorPostprocessorName &) const inline protected virtual inherited
Helper for deriving classes to override to add dependencies when a VectorPostprocessor is requested.
Reimplemented in UserObject, AuxKernelTempl< ComputeValueType >, AuxKernelTempl< Real >, and AuxKernelTempl< RealVectorValue >.
Definition at line 311 of file VectorPostprocessorInterface.h.
  {
  }
Referenced by VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), and VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper().
areElemIDsIdentical()
bool ElementIDInterface::areElemIDsIdentical (const std::string & id_name1, const std::string & id_name2) const inline inherited
Whether two element integers are identical for all elements.
Definition at line 103 of file ElementIDInterface.h.
  {
    return _id_mesh->areElemIDsIdentical(id_name1, id_name2);
  }
blockIDs()
const std::set< SubdomainID > & BlockRestrictable::blockIDs () const virtual inherited
Return the block subdomain ids for this object Note, if this is not block restricted, this function returns all mesh subdomain ids.
Returns
a set of SubdomainIDs that are valid for this object
Definition at line 190 of file BlockRestrictable.C.
{
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return _blk_mesh->meshSubdomains();
  else
    return _blk_ids;
}
Referenced by FunctorMaterial::addFunctorProperty(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), NodalPatchRecoveryAuxBase::blockRestrictElements(), MooseMesh::cacheFaceInfoVariableOwnership(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), BlockRestrictable::getBlockCoordSystem(), getGenericZeroMaterialPropertyByName(), BlockRestrictable::hasBlockMaterialPropertyHelper(), SubdomainsDivision::initialize(), ElementCentroidPositions::initialize(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), registerPropName(), and FVPointValueConstraint::setMyElem().
blockRestricted()
bool BlockRestrictable::blockRestricted () const virtual inherited
Returns true if this object has been restricted to a block.
See also
MooseObject
Definition at line 178 of file BlockRestrictable.C.
{
  return _blk_ids.find(Moose::ANY_BLOCK_ID) == _blk_ids.end();
}
Referenced by NodalPatchRecoveryAuxBase::blockRestrictElements(), BlockRestrictable::checkVariable(), SubdomainsDivision::divisionIndex(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), SubdomainsDivision::initialize(), ElementCentroidPositions::initialize(), BlockRestrictable::initializeBlockRestrictable(), SolutionIC::initialSetup(), and FVPointValueConstraint::setMyElem().
blocks()
const std::vector< SubdomainName > & BlockRestrictable::blocks () const inherited
Return the block names for this object.
Note, if the 'blocks' input parameter was not utilized this will return an empty vector.
Returns
vector of SubdomainNames that are valid for this object
Definition at line 184 of file BlockRestrictable.C.
{
  return _blocks;
}
Referenced by MaterialOutputAction::getParams(), BlockAverageValue::initialize(), SubdomainsDivision::initialize(), and SolutionIC::initialSetup().
blocksMaxDimension()
unsigned int BlockRestrictable::blocksMaxDimension () const inherited
Return the largest mesh dimension of the elements in the blocks for this object.
Definition at line 360 of file BlockRestrictable.C.
{
  mooseAssert(_blk_dim != libMesh::invalid_uint, "Block restriction not initialized");
  return _blk_dim;
}
boundaryIDs()
const std::set< BoundaryID > & BoundaryRestrictable::boundaryIDs () const virtual inherited
Return the boundary IDs for this object.
Returns
A set of all boundary ids for which the object is restricted
Definition at line 180 of file BoundaryRestrictable.C.
{
  return _bnd_ids;
}
Referenced by getGenericZeroMaterialPropertyByName(), BoundaryRestrictable::hasBoundaryMaterialPropertyHelper(), SidesetInfoVectorPostprocessor::initialize(), InterfaceQpUserObjectBase::initialSetup(), and registerPropName().
boundaryNames()
const std::vector< BoundaryName > & BoundaryRestrictable::boundaryNames () const inherited
Return the boundary names for this object.
Returns
A set of all boundary names for which the object is restricted
Definition at line 186 of file BoundaryRestrictable.C.
{
  return _boundary_names;
}
Referenced by MaterialOutputAction::getParams(), NearestNodeDistanceAux::NearestNodeDistanceAux(), and NearestNodeValueAux::NearestNodeValueAux().
boundaryRestricted()
bool BoundaryRestrictable::boundaryRestricted () const virtual inherited
Returns true if this object has been restricted to a boundary.
See also
MooseObject
Definition at line 198 of file BoundaryRestrictable.C.
{
  return BoundaryRestrictable::restricted(_bnd_ids);
}
Referenced by ADSurfaceCharge::computeQpProperties(), MaterialOutputAction::getParams(), and DerivativeMaterialInterface< T >::haveMaterialProperty().
buildOutputHideVariableList()
void OutputInterface::buildOutputHideVariableList (std::set< std::string > variable_names) inherited
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
Parameters
variable_names A set of variables for which the 'outputs' parameter controls
By default this is called by the constructor and passes the block name as the list of variables. This needs to be called explicitly if the build_list flag is set to False in the constructor. The latter cases is needed by the Material object to work correctly with the automatic material output capability.
Definition at line 61 of file OutputInterface.C.
{
  // Set of available names
  const std::set<OutputName> & avail = _oi_output_warehouse.getOutputNames();
  // Check for 'none'; hide variables on all outputs
  if (_oi_outputs.find("none") != _oi_outputs.end())
    for (const auto & name : avail)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  // Check for empty and 'all' in 'outputs' parameter; do not perform any variable restrictions in
  // these cases
  else if (_oi_outputs.empty() || _oi_outputs.find("all") != _oi_outputs.end())
    return;
  // Limit the variable output to Output objects listed
  else
  {
    // Create a list of outputs where the variable should be hidden
    std::set<OutputName> hide;
    std::set_difference(avail.begin(),
                        avail.end(),
                        _oi_outputs.begin(),
                        _oi_outputs.end(),
                        std::inserter(hide, hide.begin()));
    // If 'outputs' is specified add the object name to the list of items to hide
    for (const auto & name : hide)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  }
}
Referenced by ReporterTransferInterface::hideVariableHelper(), and OutputInterface::OutputInterface().
buildRequiredMaterials()
template<typename Consumers > std::deque< MaterialBase * > MaterialBase::buildRequiredMaterials (const Consumers & mat_consumers, const std::vector< std::shared_ptr< MaterialBase > > & mats, const bool allow_stateful) static
Build the materials required by a set of consumer objects.
Definition at line 449 of file MaterialBase.h.
{
  std::deque<MaterialBase *> required_mats;
  std::unordered_set<unsigned int> needed_mat_props;
  for (const auto & consumer : mat_consumers)
  {
    const auto & mp_deps = consumer->getMatPropDependencies();
    needed_mat_props.insert(mp_deps.begin(), mp_deps.end());
  }
  // A predicate of calling this function is that these materials come in already sorted by
  // dependency with the front of the container having no other material dependencies and following
  // materials potentially depending on the ones in front of them. So we can start at the back and
  // iterate forward checking whether the current material supplies anything that is needed, and if
  // not we discard it
  for (auto it = mats.rbegin(); it != mats.rend(); ++it)
  {
    auto * const mat = it->get();
    bool supplies_needed = false;
    const auto & supplied_props = mat->getSuppliedPropIDs();
    // Do O(N) with the small container
    for (const auto supplied_prop : supplied_props)
    {
      if (needed_mat_props.count(supplied_prop))
      {
        supplies_needed = true;
        break;
      }
    }
    if (!supplies_needed)
      continue;
    if (!allow_stateful && mat->hasStatefulProperties())
      ::mooseError(
          "Someone called buildRequiredMaterials with allow_stateful = false but a material "
          "dependency ",
          mat->name(),
          " computes stateful properties.");
    const auto & mp_deps = mat->getMatPropDependencies();
    needed_mat_props.insert(mp_deps.begin(), mp_deps.end());
    required_mats.push_front(mat);
  }
  return required_mats;
}
Referenced by MaterialPropertyInterface::buildRequiredMaterials(), and Moose::Mortar::setupMortarMaterials().
castUserObject()
template<class T > const T & UserObjectInterface::castUserObject (const UserObject & uo_base, const std::string & param_name = "") const private inherited
Internal helper that casts the UserObject uo_base to the reqested type.
Exits with a useful error if the casting failed. If the parameter param_name is provided and is valid, a paramError() will be used instead.
Definition at line 136 of file UserObjectInterface.h.
{
  const T * uo = dynamic_cast<const T *>(&uo_base);
  if (!uo)
  {
    std::stringstream oss;
    oss << "The provided UserObject \"" << userObjectName(uo_base) << "\" of type "
        << userObjectType(uo_base)
        << " is not derived from the required type.\n\nThe UserObject must derive from "
        << MooseUtils::prettyCppType<T>() << ".";
    if (_uoi_moose_object.parameters().isParamValid(param_name))
      _uoi_moose_object.paramError(param_name, oss.str());
    else
      _uoi_moose_object.mooseError(oss.str());
  }
  return *uo;
}
checkAllVariables()
template<typename DofObjectType > std::set< MooseVariableFieldBase * > MooseVariableDependencyInterface::checkAllVariables (const DofObjectType & dof_object, const std::set< MooseVariableFieldBase * > & vars_to_omit = {}) inherited
Check whether all of the variable dependencies have degree of freedom indices on the supplied degree of freedom object.
Parameters
dof_object The degree of freedom object (an element or node) that we want to check for existence of variable degrees of freedom on
vars_to_omit Variables that we can omit from checking
Returns
Any variables that do not have degrees of freedom on the supplied degree of freedom object
Definition at line 91 of file MooseVariableDependencyInterface.h.
{
  if (vars_to_omit.empty())
    return checkVariables(dof_object, _moose_variable_dependencies);
  std::set<MooseVariableFieldBase *> vars_to_check;
  std::set_difference(_moose_variable_dependencies.begin(),
                      _moose_variable_dependencies.end(),
                      vars_to_omit.begin(),
                      vars_to_omit.end(),
                      std::inserter(vars_to_check, vars_to_check.begin()));
  return checkVariables(dof_object, vars_to_check);
}
checkExecutionStage()
void MaterialBase::checkExecutionStage () protected
Check and throw an error if the execution has progressed past the construction stage.
Definition at line 228 of file MaterialBase.C.
{
  if (_fe_problem.startedInitialSetup())
    mooseError("Material properties must be retrieved during material object construction to "
               "ensure correct dependency resolution.");
}
Referenced by InterfaceMaterial::getGenericMaterialPropertyByName(), Material::getGenericMaterialPropertyByName(), InterfaceMaterial::getGenericNeighborMaterialPropertyByName(), and getGenericZeroMaterialPropertyByName().
checkParam()
void PostprocessorInterface::checkParam (const std::string & param_name, const unsigned int index = std::numeric_limits<unsigned int>::max()) const private inherited
Checks the parameters relating to a Postprocessor.
If index is not set, index checking is not performed.
Definition at line 139 of file PostprocessorInterface.C.
{
  const bool check_index = index != std::numeric_limits<unsigned int>::max();
  if (!_ppi_params.isParamValid(param_name))
    _ppi_moose_object.mooseError(
        "When getting a Postprocessor, failed to get a parameter with the name \"",
        param_name,
        "\".",
        "\n\nKnown parameters:\n",
        _ppi_moose_object.parameters());
  if (_ppi_params.isType<PostprocessorName>(param_name))
  {
    if (check_index && index > 0)
      _ppi_moose_object.paramError(param_name,
                                   "A Postprocessor was requested with index ",
                                   index,
                                   " but a single Postprocessor is coupled.");
  }
  else if (_ppi_params.isType<std::vector<PostprocessorName>>(param_name))
  {
    const auto & names = _ppi_params.get<std::vector<PostprocessorName>>(param_name);
    if (check_index && names.size() <= index)
      _ppi_moose_object.paramError(param_name,
                                   "A Postprocessor was requested with index ",
                                   index,
                                   " but only ",
                                   names.size(),
                                   " Postprocessors are coupled.");
  }
  else
  {
    _ppi_moose_object.mooseError(
        "Supplied parameter with name \"",
        param_name,
        "\" of type \"",
        _ppi_params.type(param_name),
        "\" is not an expected type for getting a Postprocessor.\n\n",
        "Allowed types are \"PostprocessorName\" and \"std::vector<PostprocessorName>\".");
  }
}
Referenced by PostprocessorInterface::coupledPostprocessors(), and PostprocessorInterface::getPostprocessorNameInternal().
checkStatefulSanity()
void MaterialBase::checkStatefulSanity () const
Definition at line 139 of file MaterialBase.C.
{
  for (const auto & [id, min_state] : _props_to_min_states)
    if (min_state > 0)
      mooseError("The stateful property '",
                 _fe_problem.getMaterialPropertyRegistry().getName(id),
                 "' is undefined");
}
checkVar()
void ScalarCoupleable::checkVar (const std::string & var_name) const private inherited
Check that the right kind of variable is being coupled in.
Parameters
var_name The name of the coupled variable
Definition at line 290 of file ScalarCoupleable.C.
{
  const auto var_name = _sc_parameters.checkForRename(var_name_in);
  auto it = _sc_coupled_vars.find(var_name);
  if (it != _sc_coupled_vars.end())
  {
    std::string cvars;
    for (auto jt : it->second)
      cvars += " " + jt->name();
    mooseError(_sc_name,
               ": Trying to couple a field variable where scalar variable is expected, '",
               var_name,
               " =",
               cvars,
               "'");
  }
  // NOTE: non-existent variables are handled in the constructor
}
Referenced by ScalarCoupleable::adCoupledScalarValue(), ScalarCoupleable::coupledMatrixTagScalarValue(), ScalarCoupleable::coupledScalar(), ScalarCoupleable::coupledScalarDot(), ScalarCoupleable::coupledScalarDotDot(), ScalarCoupleable::coupledScalarDotDotDu(), ScalarCoupleable::coupledScalarDotDotOld(), ScalarCoupleable::coupledScalarDotDu(), ScalarCoupleable::coupledScalarDotOld(), ScalarCoupleable::coupledScalarOrder(), ScalarCoupleable::coupledScalarValue(), ScalarCoupleable::coupledScalarValueOld(), ScalarCoupleable::coupledScalarValueOlder(), and ScalarCoupleable::coupledVectorTagScalarValue().
checkVariable()
void BlockRestrictable::checkVariable (const MooseVariableFieldBase & variable) const virtual inherited
Helper for checking that the ids for this object are in agreement with the variables on the supplied variable.
Parameters
variable The variable to check against.
Reimplemented in DomainUserObject.
Definition at line 333 of file BlockRestrictable.C.
{
  // a variable defined on all internal sides does not need this check because
  // it can be coupled with other variables in DG kernels
  if (variable.activeSubdomains().count(Moose::INTERNAL_SIDE_LOWERD_ID) > 0)
    return;
  if (!isBlockSubset(variable.activeSubdomains()))
  {
    std::string var_ids = Moose::stringify(variable.activeSubdomains(), ", ");
    std::string obj_ids = Moose::stringify(blockRestricted() ? _blk_ids : meshBlockIDs(), ", ");
    mooseError("The 'block' parameter of the object '",
               _blk_name,
               "' must be a subset of the 'block' parameter of the variable '",
               variable.name(),
               "':\n    Object '",
               _blk_name,
               "': ",
               obj_ids,
               "\n    Variable '",
               variable.name(),
               "': ",
               var_ids);
  }
}
Referenced by DomainUserObject::checkVariable().
checkVariableBoundaryIntegrity()
virtual bool BoundaryRestrictable::checkVariableBoundaryIntegrity () const inline virtual inherited
Whether integrity/coverage checking should be conducted for moose variables used in this object.
This should return true if variables are only evaluated locally, e.g. on the current node or element. This should return false if evaluation of this object entails non-local variable evaluations
Definition at line 179 of file BoundaryRestrictable.h.
{ return true; }
checkVariables()
template<typename DofObjectType > template std::set< MooseVariableFieldBase * > MooseVariableDependencyInterface::checkVariables (const DofObjectType & dof_object, const std::set< MooseVariableFieldBase * > & vars_to_check) inherited
Check whether all of the supplied variables have degree of freedom indices on the supplied degree of freedom object.
Parameters
dof_object The degree of freedom object (an element or node) that we want to check for existence of variable degrees of freedom on
vars_to_check the variables to check
Returns
Any variables that do not have degrees of freedom on the supplied degree of freedom object
Definition at line 25 of file MooseVariableDependencyInterface.C.
{
  std::set<MooseVariableFieldBase *> vars_without_indices;
  for (auto * const var : vars_to_check)
  {
    var->sys().dofMap().dof_indices(&dof_object, _dof_indices, var->number());
    if (_dof_indices.empty())
      vars_without_indices.insert(var);
  }
  return vars_without_indices;
}
Referenced by MooseVariableDependencyInterface::checkAllVariables().
computeProperties()
void MaterialBase::computeProperties () pure virtual
Performs the quadrature point loop, calling computeQpProperties.
Implemented in DerivativeSumMaterialTempl< is_ad >, DerivativeFunctionMaterialBaseTempl< is_ad >, DerivativeFunctionMaterialBaseTempl< is_ad >, InterfaceMaterial, Material, and FunctorMaterial.
Definition at line 192 of file MaterialBase.C.
{
  mooseError("MaterialBase::computeProperties in Material '", name(), "' needs to be implemented");
}
computePropertiesAtQp()
void MaterialBase::computePropertiesAtQp (unsigned int qp) virtual
A method for (re)computing the properties of a MaterialBase.
This is intended to be called from other objects, by first calling MaterialPropertyInterface::getMaterial and then calling this method on the MaterialBase object returned.
Definition at line 221 of file MaterialBase.C.
{
  _qp = qp;
  computeQpProperties();
}
computeQpProperties()
void MaterialBase::computeQpProperties () protected virtual
Users must override this method.
Reimplemented in ADEEDFRateConstantTownsend, ADZapdosEEDFRateConstant, DiffusionRateTemp, EEDFRateConstant, EEDFRateConstantTownsend, HeatCapacityRatio, InterpolatedCoefficientLinear, InterpolatedCoefficientSpline, SpeciesSum, SuperelasticReactionRate, ZapdosEEDFRateConstant, GenericRateConstantTempl< is_ad >, GenericRateConstantTempl< is_ad >, ElectricField, GenericRateConstantTempl< is_ad >, ADGasElectronMoments, ADSurfaceCharge, Gas, GasBase, GasElectronMoments, HeavySpeciesTempl< is_ad >, Water, ADPiecewiseLinearInterpolationMaterial, CoupledValueFunctionMaterialTempl< is_ad >, DerivativeParsedMaterialHelperTempl< is_ad >, GenericConstant2DArray, GenericConstantArray, GenericConstantMaterialTempl< is_ad >, GenericConstantRankTwoTensorTempl< is_ad >, GenericConstantVectorMaterialTempl< is_ad >, GenericFunctionMaterialTempl< is_ad >, GenericFunctionRankTwoTensorTempl< is_ad >, GenericFunctionVectorMaterialTempl< is_ad >, InterpolatedStatefulMaterialTempl< T >, MaterialADConverterTempl< T >, MaterialFunctorConverterTempl< T >, ParsedMaterialHelper< is_ad >, PiecewiseConstantByBlockMaterialTempl< is_ad >, PiecewiseLinearInterpolationMaterial, VectorFromComponentVariablesMaterialTempl< is_ad >, and FunctorMaterial.
Definition at line 198 of file MaterialBase.C.
{
}
Referenced by InterfaceMaterial::computeProperties(), Material::computeProperties(), computePropertiesAtQp(), and Material::subdomainSetup().
connectControllableParams()
void MooseBaseParameterInterface::connectControllableParams (const std::string & parameter, const std::string & object_type, const std::string & object_name, const std::string & object_parameter) const inherited
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
Parameters
parameter Name of the controllable parameter of this action
object_type Type of the object added by this action.
object_name Name of the object added by this action.
object_parameter Name of the parameter of the object.
Definition at line 34 of file MooseBaseParameterInterface.C.
{
  MooseObjectParameterName primary_name(uniqueName(), parameter);
  const auto base_type = _factory.getValidParams(object_type).get<std::string>("_moose_base");
  MooseObjectParameterName secondary_name(base_type, object_name, object_parameter);
  _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
      primary_name, secondary_name);
  const auto & tags = _pars.get<std::vector<std::string>>("control_tags");
  for (const auto & tag : tags)
  {
    if (!tag.empty())
    {
      MooseObjectParameterName tagged_name(tag, _moose_base->name(), parameter);
      _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
          tagged_name, secondary_name);
    }
  }
}
coupledGenericScalarValue() [1/3]
template<> const GenericVariableValue< false > & ScalarCoupleable::coupledGenericScalarValue (const std::string & var_name, unsigned int comp) const protected inherited
Definition at line 151 of file ScalarCoupleable.C.
{
  return coupledScalarValue(var_name, comp);
}
coupledGenericScalarValue() [2/3]
template<> const GenericVariableValue< true > & ScalarCoupleable::coupledGenericScalarValue (const std::string & var_name, unsigned int comp) const protected inherited
Definition at line 159 of file ScalarCoupleable.C.
{
  return adCoupledScalarValue(var_name, comp);
}
coupledGenericScalarValue() [3/3]
template<bool is_ad> const GenericVariableValue< is_ad > & ScalarCoupleable::coupledGenericScalarValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns value of a coupled scalar variable for use in templated automatic differentiation classes.
Parameters
var_name Name of coupled scalar variable
comp Component number for vector of coupled scalar variables
Returns
Reference to a GenericVariableValue for the coupled scalar variable
coupledMatrixTagScalarValue()
const VariableValue & ScalarCoupleable::coupledMatrixTagScalarValue (const std::string & var_name, TagID tag, unsigned int comp = 0) const protected inherited
Returns value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
tag Tag ID of coupled matrix;
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
Definition at line 202 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  _sc_coupleable_matrix_tags.insert(tag);
  return getScalarVar(var_name, comp)->matrixTagSln(tag);
}
coupledPostprocessors()
std::size_t PostprocessorInterface::coupledPostprocessors (const std::string & param_name) const inherited
Returns number of Postprocessors coupled under parameter name.
Parameters
param_name The name of the Postprocessor parameter
Returns
Number of coupled post-processors, 1 if it's a single
Definition at line 129 of file PostprocessorInterface.C.
{
  checkParam(param_name);
  if (_ppi_params.isType<PostprocessorName>(param_name))
    return 1;
  return _ppi_params.get<std::vector<PostprocessorName>>(param_name).size();
}
Referenced by FunctionValuePostprocessor::FunctionValuePostprocessor().
coupledScalar()
unsigned int ScalarCoupleable::coupledScalar (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the index for a scalar coupled variable by name.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Index of coupled variable
Definition at line 93 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  return getScalarVar(var_name, comp)->number();
}
Referenced by ParsedODEKernel::ParsedODEKernel().
coupledScalarComponents()
unsigned int ScalarCoupleable::coupledScalarComponents (const std::string & var_name) const protected inherited
Return the number of components to the coupled scalar variable.
Parameters
var_name The of the coupled variable
Definition at line 343 of file ScalarCoupleable.C.
{
  const auto var_name = _sc_parameters.checkForRename(var_name_in);
  const auto it = _coupled_scalar_vars.find(var_name);
  if (it != _coupled_scalar_vars.end())
    return it->second.size();
  mooseError(_sc_name, ": Trying to get a non-existent variable '", var_name, "'");
}
coupledScalarDot()
const VariableValue & ScalarCoupleable::coupledScalarDot (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the time derivative of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a time derivative VariableValue for the coupled variable
Definition at line 243 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDot");
  return getScalarVar(var_name, comp)->uDot();
}
coupledScalarDotDot()
const VariableValue & ScalarCoupleable::coupledScalarDotDot (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the second time derivative of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a time derivative VariableValue for the coupled variable
Definition at line 251 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotDot");
  return getScalarVar(var_name, comp)->uDotDot();
}
coupledScalarDotDotDu()
const VariableValue & ScalarCoupleable::coupledScalarDotDotDu (const std::string & var_name, unsigned int comp = 0) const protected inherited
Second time derivative of a scalar coupled variable with respect to the coefficients.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the time derivative of the coupled variable with respect to the coefficients
Definition at line 282 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotDotDu");
  return getScalarVar(var_name, comp)->duDotDotDu();
}
coupledScalarDotDotOld()
const VariableValue & ScalarCoupleable::coupledScalarDotDotOld (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the old second time derivative of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a time derivative VariableValue for the coupled variable
Definition at line 267 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotDotOld");
  return getScalarVar(var_name, comp)->uDotDotOld();
}
coupledScalarDotDu()
const VariableValue & ScalarCoupleable::coupledScalarDotDu (const std::string & var_name, unsigned int comp = 0) const protected inherited
Time derivative of a scalar coupled variable with respect to the coefficients.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue containing the time derivative of the coupled variable with respect to the coefficients
Definition at line 274 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotDu");
  return getScalarVar(var_name, comp)->duDotDu();
}
coupledScalarDotOld()
const VariableValue & ScalarCoupleable::coupledScalarDotOld (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the old time derivative of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a time derivative VariableValue for the coupled variable
Definition at line 259 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  validateExecutionerType(var_name, "coupledScalarDotOld");
  return getScalarVar(var_name, comp)->uDotOld();
}
coupledScalarOrder()
Order ScalarCoupleable::coupledScalarOrder (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the order for a scalar coupled variable by name.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Order of coupled variable
Definition at line 100 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return _sc_fe_problem.getMaxScalarOrder();
  return getScalarVar(var_name, comp)->order();
}
coupledScalarValue()
const VariableValue & ScalarCoupleable::coupledScalarValue (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
Definition at line 124 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  auto var = getScalarVar(var_name, comp);
  return _sc_is_implicit ? var->sln() : var->slnOld();
}
Referenced by BoltzmannSolverScalar::BoltzmannSolverScalar(), VariableSum::computeValue(), VariableSumLog::computeValue(), ScalarCoupleable::coupledGenericScalarValue(), ParsedAuxScalar::ParsedAuxScalar(), ParsedODEKernel::ParsedODEKernel(), and ParsedScalarRateCoefficient::ParsedScalarRateCoefficient().
coupledScalarValueOld()
const VariableValue & ScalarCoupleable::coupledScalarValueOld (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the old (previous time step) value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a old VariableValue for the coupled variable
Definition at line 216 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  validateExecutionerType(var_name, "coupledScalarValueOld");
  auto var = getScalarVar(var_name, comp);
  return _sc_is_implicit ? var->slnOld() : var->slnOlder();
}
coupledScalarValueOlder()
const VariableValue & ScalarCoupleable::coupledScalarValueOlder (const std::string & var_name, unsigned int comp = 0) const protected inherited
Returns the older (two time steps previous) value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
comp Component number for vector of coupled variables
Returns
Reference to a older VariableValue for the coupled variable
Definition at line 228 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  validateExecutionerType(var_name, "coupledScalarValueOlder");
  auto var = getScalarVar(var_name, comp);
  if (_sc_is_implicit)
    return var->slnOlder();
  else
    mooseError("Older values not available for explicit schemes");
}
coupledVectorTagScalarValue()
const VariableValue & ScalarCoupleable::coupledVectorTagScalarValue (const std::string & var_name, TagID tag, unsigned int comp = 0) const protected inherited
Returns value of a scalar coupled variable.
Parameters
var_name Name of coupled variable
tag Tag ID of coupled vector ;
comp Component number for vector of coupled variables
Returns
Reference to a VariableValue for the coupled variable
Definition at line 181 of file ScalarCoupleable.C.
{
  checkVar(var_name);
  if (!isCoupledScalar(var_name, comp))
    return *getDefaultValue(var_name);
  if (!_sc_fe_problem.vectorTagExists(tag))
    mooseError("Attempting to couple to vector tag scalar with ID ",
               tag,
               "in ",
               _sc_name,
               ", but a vector tag with that ID does not exist");
  _sc_coupleable_vector_tags.insert(tag);
  return getScalarVar(var_name, comp)->vectorTagSln(tag);
}
customSetup()
virtual void SetupInterface::customSetup (const ExecFlagType &) inline virtual inherited
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
Reimplemented in Function.
Definition at line 61 of file SetupInterface.h.
{}
cyclicDependencyError()
template<typename T , typename T2 > void DependencyResolverInterface::cyclicDependencyError (CyclicDependencyException< T2 > & e, const std::string & header) static inherited
A helper method for cyclic errors.
Definition at line 118 of file DependencyResolverInterface.h.
{
  std::ostringstream oss;
  oss << header << ":\n";
  const auto cycle = e.getCyclicDependencies();
  std::vector<std::string> names(cycle.size());
  for (const auto i : index_range(cycle))
    names[i] = static_cast<T>(cycle[i])->name();
  oss << MooseUtils::join(names, " <- ");
  mooseError(oss.str());
}
declareADProperty()
template<typename T > ADMaterialProperty< T > & MaterialBase::declareADProperty (const std::string & name)
Definition at line 437 of file MaterialBase.h.
{
  // Check if the supplied parameter is a valid input parameter key
  std::string prop_name = name;
  if (_pars.have_parameter<MaterialPropertyName>(name))
    prop_name = _pars.get<MaterialPropertyName>(name);
  return declareADPropertyByName<T>(prop_name);
}
declareADPropertyByName()
template<typename T > ADMaterialProperty< T > & MaterialBase::declareADPropertyByName (const std::string & prop_name) inline
Definition at line 126 of file MaterialBase.h.
  {
    return declareGenericPropertyByName<T, true>(prop_name);
  }
declareGenericProperty()
template<typename T , bool is_ad> auto & MaterialBase::declareGenericProperty (const std::string & prop_name) inline
Definition at line 134 of file MaterialBase.h.
  {
    if constexpr (is_ad)
      return declareADProperty<T>(prop_name);
    else
      return declareProperty<T>(prop_name);
  }
declareGenericPropertyByName()
template<typename T , bool is_ad> GenericMaterialProperty< T, is_ad > & MaterialBase::declareGenericPropertyByName (const std::string & prop_name)
Definition at line 359 of file MaterialBase.h.
{
  const auto prop_name_modified =
      _declare_suffix.empty()
          ? prop_name
          : MooseUtils::join(std::vector<std::string>({prop_name, _declare_suffix}), "_");
  // Call this before so that the ID is valid
  auto & prop = materialData().declareProperty<T, is_ad>(prop_name_modified, *this);
  registerPropName(prop_name_modified, false, 0);
  return prop;
}
declareManagedRestartableDataWithContext()
template<typename T , typename... Args> Restartable::ManagedValue< T > Restartable::declareManagedRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declares a piece of "managed" restartable data and initialize it.
Here, "managed" restartable data means that the caller can destruct this data upon destruction of the return value of this method. Therefore, this ManagedValue<T> wrapper should survive after the final calls to dataStore() for it. That is... at the very end.
This is needed for objects whose destruction ordering is important, and enables natural c++ destruction in reverse construction order of the object that declares it.
See delcareRestartableData and declareRestartableDataWithContext for more information.
Definition at line 276 of file Restartable.h.
{
  auto & data_ptr =
      declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...);
  return Restartable::ManagedValue<T>(data_ptr);
}
declareProperty()
template<typename T > MaterialProperty< T > & MaterialBase::declareProperty (const std::string & name)
Definition at line 347 of file MaterialBase.h.
{
  // Check if the supplied parameter is a valid input parameter key
  std::string prop_name = name;
  if (_pars.have_parameter<MaterialPropertyName>(name))
    prop_name = _pars.get<MaterialPropertyName>(name);
  return declarePropertyByName<T>(prop_name);
}
declarePropertyByName()
template<typename T > MaterialProperty< T > & MaterialBase::declarePropertyByName (const std::string & prop_name) inline
Declare the property named "name".
Definition at line 119 of file MaterialBase.h.
  {
    return declareGenericPropertyByName<T, false>(prop_name);
  }
declareRecoverableData()
template<typename T , typename... Args> T & Restartable::declareRecoverableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "recoverable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
Note - this data will NOT be restored on Restart!
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 351 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  registerRestartableNameWithFilterOnApp(full_name, Moose::RESTARTABLE_FILTER::RECOVERABLE);
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableData()
template<typename T , typename... Args> T & Restartable::declareRestartableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 269 of file Restartable.h.
{
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataHelper()
template<typename T , typename... Args> RestartableData< T > & Restartable::declareRestartableDataHelper (const std::string & data_name, void * context, Args &&... args) const private inherited
Helper function for declaring restartable data.
We use this function to reduce code duplication when returning const/nonconst references to the data.
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 303 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  // Here we will create the RestartableData even though we may not use this instance.
  // If it's already in use, the App will return a reference to the existing instance and we'll
  // return that one instead. We might refactor this to have the app create the RestartableData
  // at a later date.
  auto data_ptr =
      std::make_unique<RestartableData<T>>(full_name, context, std::forward<Args>(args)...);
  auto & restartable_data_ref = static_cast<RestartableData<T> &>(
      registerRestartableDataOnApp(std::move(data_ptr), _restartable_tid));
  return restartable_data_ref;
}
declareRestartableDataWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 294 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...).set();
}
declareRestartableDataWithObjectName()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectName (const std::string & data_name, const std::string & object_name, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
args Arguments to forward to the constructor of the data
Definition at line 323 of file Restartable.h.
{
  return declareRestartableDataWithObjectNameWithContext<T>(
      data_name, object_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataWithObjectNameWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectNameWithContext (const std::string & data_name, const std::string & object_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 333 of file Restartable.h.
{
  std::string old_name = _restartable_name;
  _restartable_name = object_name;
  T & value = declareRestartableDataWithContext<T>(data_name, context, std::forward<Args>(args)...);
  _restartable_name = old_name;
  return value;
}
deduceFunctorName() [1/2]
std::string FunctorInterface::deduceFunctorName (const std::string & name) const protected inherited
Small helper to look up a functor name through the input parameter keys.
Definition at line 60 of file FunctorInterface.C.
{
  return deduceFunctorName(name, _fi_params);
}
deduceFunctorName() [2/2]
std::string FunctorInterface::deduceFunctorName (const std::string & name, const InputParameters & params) static inherited
Helper to look up a functor name through the input parameter keys.
Parameters
name The input parameter name that we are trying to deduce the functor name for
params The input parameters object that we will be checking for parameters named name
Returns
The functor name
Definition at line 28 of file FunctorInterface.C.
{
  if (params.isParamValid(name))
  {
    if (params.have_parameter<MooseFunctorName>(name))
      return params.get<MooseFunctorName>(name);
    // variables, functor material properties, functions, and post-processors are also functors
    else if (params.have_parameter<MaterialPropertyName>(name))
      return params.get<MaterialPropertyName>(name);
    else if (params.have_parameter<VariableName>(name))
      return params.get<VariableName>(name);
    else if (params.have_parameter<std::vector<VariableName>>(name))
    {
      const auto & var_names = params.get<std::vector<VariableName>>(name);
      if (var_names.size() != 1)
        mooseError("We only support a single variable name for retrieving a functor");
      return var_names[0];
    }
    else if (params.have_parameter<NonlinearVariableName>(name))
      return params.get<NonlinearVariableName>(name);
    else if (params.have_parameter<FunctionName>(name))
      return params.get<FunctionName>(name);
    else if (params.have_parameter<PostprocessorName>(name))
      return params.get<PostprocessorName>(name);
    else
      mooseError("Invalid parameter type for retrieving a functor");
  }
  else
    return name;
}
Referenced by FunctorInterface::deduceFunctorName(), FunctorInterface::getFunctor(), and FunctorInterface::isFunctor().
defaultFunctor() [1/4]
template<typename T > const Moose::Functor< T > * FunctorInterface::defaultFunctor (const std::string & name) private inherited
Helper function to parse default functor values.
This is implemented as a specialization for supported types and returns NULL in all other cases.
Definition at line 220 of file FunctorInterface.h.
{
  return nullptr;
}
defaultFunctor() [2/4]
template<> const Moose::Functor< Real > * FunctorInterface::defaultFunctor (const std::string & name) private inherited
defaultFunctor() [3/4]
template<> const Moose::Functor< ADReal > * FunctorInterface::defaultFunctor (const std::string & name) private inherited
defaultFunctor() [4/4]
template<> const Moose::Functor< ADReal > * FunctorInterface::defaultFunctor (const std::string & name) inherited
Definition at line 67 of file FunctorInterface.C.
{
  std::istringstream ss(name);
  Real real_value;
  // check if the string parsed cleanly into a Real number
  if (ss >> real_value && ss.eof())
  {
    _default_real_functors.emplace_back(std::make_unique<Moose::Functor<Real>>(
        std::make_unique<Moose::ConstantFunctor<Real>>(real_value)));
    auto & default_property = _default_real_functors.back();
    return default_property.get();
  }
  return nullptr;
}
determineState()
Moose::StateArg TransientInterface::determineState () const inline protected inherited
Create a functor state argument that corresponds to the implicit state of this object.
If we are implicit then we will return the current state. If we are not, then we will return the old state
Definition at line 80 of file TransientInterface.h.
{
  return _is_implicit ? Moose::currentState() : Moose::oldState();
}
Referenced by InternalSideIntegralVariablePostprocessor::computeFaceInfoIntegral(), SideIntegralVariablePostprocessor::computeFaceInfoIntegral(), InterfaceIntegralVariableValuePostprocessor::computeQpIntegral(), LayeredSideDiffusiveFluxAverage::computeQpIntegral(), SideIntegralFunctorUserObject::computeQpIntegral(), SideIntegralVariableUserObject::computeQpIntegral(), FVConstantScalarOutflowBC::computeQpResidual(), FVFunctorNeumannBC::computeQpResidual(), FVDiffusionInterface::computeQpResidual(), FVOneVarDiffusionInterface::computeQpResidual(), FVTwoVarContinuityConstraint::computeQpResidual(), FVAdvection::computeQpResidual(), FVAnisotropicDiffusion::computeQpResidual(), FVCoupledForce::computeQpResidual(), FVDiffusion::computeQpResidual(), FVDivergence::computeQpResidual(), FVFunctorTimeKernel::computeQpResidual(), FVMatAdvection::computeQpResidual(), FVBoundaryIntegralValueConstraint::computeQpResidual(), FVBoundedValueConstraint::computeQpResidual(), FVIntegralValueConstraint::computeQpResidual(), FVPointValueConstraint::computeQpResidual(), AdvectiveFluxAux::computeValue(), FunctorAux::computeValue(), SecondTimeDerivativeAux::computeValue(), TimeDerivativeAux::computeValue(), MeshDivisionFunctorReductionVectorPostprocessor::execute(), PositionsFunctorValueSampler::execute(), FunctorPositions::initialize(), and FunctorTimes::initialize().
enabled()
virtual bool MooseObject::enabled () const inline virtual inherited
Return the enabled status of the object.
Reimplemented in EigenKernel.
Definition at line 54 of file MooseObject.h.
{ return _enabled; }
Referenced by EigenKernel::enabled().
errorPrefix()
std::string MooseBaseErrorInterface::errorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for this object:
The following <error_type> occurred in the object "<name>", of type "<type>".
Definition at line 15 of file MooseBaseErrorInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the object \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseErrorInterface::mooseError(), and MooseBaseErrorInterface::mooseWarning().
flagInvalidSolutionInternal()
void SolutionInvalidInterface::flagInvalidSolutionInternal (InvalidSolutionID _invalid_solution_id) const protected inherited
Set solution invalid mark for the given solution ID.
Definition at line 26 of file SolutionInvalidInterface.C.
{
  auto & solution_invalidity = _si_moose_object.getMooseApp().solutionInvalidity();
  if (_si_problem.immediatelyPrintInvalidSolution())
    solution_invalidity.printDebug(_invalid_solution_id);
  return solution_invalidity.flagInvalidSolutionInternal(_invalid_solution_id);
}
getADDefaultValue()
const ADVariableValue * ScalarCoupleable::getADDefaultValue (const std::string & var_name) const private inherited
Helper method to return (and insert if necessary) the AD default value for an uncoupled variable.
Parameters
var_name the name of the variable for which to retrieve a default value
Returns
ADVariableValue * a pointer to the associated ADVariableValue.
Definition at line 167 of file ScalarCoupleable.C.
{
  auto default_value_it = _dual_default_value.find(var_name);
  if (default_value_it == _dual_default_value.end())
  {
    auto value = std::make_unique<ADVariableValue>(_sc_fe_problem.getMaxScalarOrder(),
                                                   _sc_parameters.defaultCoupledValue(var_name));
    default_value_it = _dual_default_value.insert(std::make_pair(var_name, std::move(value))).first;
  }
  return default_value_it->second.get();
}
Referenced by ScalarCoupleable::adCoupledScalarValue().
getAllElemIDs()
std::set< dof_id_type > ElementIDInterface::getAllElemIDs (unsigned int elem_id_index) const inline inherited
Return all the unique element IDs for an element integer with its index on the entire domain.
Definition at line 120 of file ElementIDInterface.h.
  {
    return _id_mesh->getAllElemIDs(elem_id_index);
  }
getBlockCoordSystem()
Moose::CoordinateSystemType BlockRestrictable::getBlockCoordSystem () protected inherited
Check if the blocks this object operates on all have the same coordinate system, and if so return it.
Definition at line 311 of file BlockRestrictable.C.
{
  if (!_blk_mesh)
    mooseError("No mesh available in BlockRestrictable::checkCoordSystem()");
  if (!_blk_feproblem)
    mooseError("No problem available in BlockRestrictable::checkCoordSystem()");
  const auto & subdomains = blockRestricted() ? blockIDs() : meshBlockIDs();
  if (subdomains.empty())
    mooseError("No subdomains found in the problem.");
  // make sure all subdomains are using the same coordinate system
  auto coord_system = _blk_feproblem->getCoordSystem(*subdomains.begin());
  for (auto subdomain : subdomains)
    if (_blk_feproblem->getCoordSystem(subdomain) != coord_system)
      mooseError("This object requires all subdomains to have the same coordinate system.");
  return coord_system;
}
getCheckedPointerParam()
template<typename T > T MooseBaseParameterInterface::getCheckedPointerParam (const std::string & name, const std::string & error_string = "") const inherited
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
The template parameter must be a pointer or an error will be thrown.
Definition at line 264 of file MooseBaseParameterInterface.h.
{
  return parameters().getCheckedPointerParam<T>(name, error_string);
}
getCoupledMooseScalarVars()
const std::vector< MooseVariableScalar * > & ScalarCoupleable::getCoupledMooseScalarVars () inline inherited
Get the list of coupled scalar variables.
Returns
The list of coupled variables
Definition at line 45 of file ScalarCoupleable.h.
  {
    return _coupled_moose_scalar_vars;
  }
Referenced by AuxScalarKernel::AuxScalarKernel(), MortarScalarBase::computeJacobian(), and ScalarInitialCondition::ScalarInitialCondition().
getDataFileName()
std::string DataFileInterface< MooseObject >::getDataFileName (const std::string & param) const inherited
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
relative to the input file directory
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
relative to the input file directory
Definition at line 34 of file DataFileInterface.C.
{
  {
    const auto & absolute_path = _parent.template getParam<FileName>(param);
    if (MooseUtils::checkFileReadable(absolute_path, false, false, false))
    {
      _parent.paramInfo(param, "Data file '", absolute_path, "' found relative to the input file.");
      return absolute_path;
    }
  }
  const auto & relative_path = _parent.parameters().rawParamVal(param);
  return getDataFileNameByName(relative_path, &param);
}
getDataFileNameByName()
std::string DataFileInterface< MooseObject >::getDataFileNameByName (const std::string & name, const std::string * param = nullptr) const inherited
Returns the path of a data file for a given relative file path.
This can be used for hardcoded datafile names and will search the same locations as getDataFileName. The optional param pointer can be used to turn the mooseErrors this function emits into paramErrors
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
Definition at line 42 of file DataFileInterface.C.
{
  const auto share_dir = MooseUtils::pathjoin(Moose::getExecutablePath(), "..", "share");
  if (MooseUtils::pathIsDirectory(share_dir))
  {
    const auto dirs = MooseUtils::listDir(share_dir, false);
    for (const auto & data_dir : dirs)
    {
      const auto path = MooseUtils::pathjoin(data_dir, "data", relative_path);
      if (MooseUtils::checkFileReadable(path, false, false, false))
      {
        if (param)
          _parent.paramInfo(
              *param, "Data file '", path, "' found in an installed app distribution.");
        else
          mooseInfo("Data file '", path, "' found in an installed app distribution.");
        return path;
      }
    }
  }
  for (const auto & data_dir : Registry::getRegistry().getDataFilePaths())
  {
    const auto path = MooseUtils::pathjoin(data_dir, relative_path);
    if (MooseUtils::checkFileReadable(path, false, false, false))
    {
      if (param)
        _parent.paramInfo(*param, "Data file '", path, "' found in a source repository.");
      else
        mooseInfo("Data file '", path, "' found in a source repository.");
      return path;
    }
  }
  mooseException(param ? _parent.parameters().inputLocation(*param) : _parent.name(),
                 ": Unable to find data file '",
                 relative_path,
                 "' anywhere");
}
getDefaultPostprocessorValueByName()
PostprocessorValue PostprocessorInterface::getDefaultPostprocessorValueByName (const PostprocessorName & name) const private inherited
Returns
The default value stored in the PostprocessorName name.
Definition at line 96 of file PostprocessorInterface.C.
{
  mooseAssert(isDefaultPostprocessorValueByName(name), "Not a default value");
  Real real_value = -std::numeric_limits<Real>::max();
  std::istringstream ss(name);
  ss >> real_value;
  return real_value;
}
Referenced by PostprocessorInterface::getPostprocessorValueInternal().
getDefaultValue()
const VariableValue * ScalarCoupleable::getDefaultValue (const std::string & var_name) const private inherited
Helper method to return (and insert if necessary) the default value for an uncoupled variable.
Parameters
var_name the name of the variable for which to retrieve a default value
Returns
VariableValue * a pointer to the associated VarirableValue.
Definition at line 110 of file ScalarCoupleable.C.
{
  auto default_value_it = _default_value.find(var_name);
  if (default_value_it == _default_value.end())
  {
    auto value = std::make_unique<VariableValue>(_sc_fe_problem.getMaxScalarOrder(),
                                                 _sc_parameters.defaultCoupledValue(var_name));
    default_value_it = _default_value.insert(std::make_pair(var_name, std::move(value))).first;
  }
  return default_value_it->second.get();
}
Referenced by ScalarCoupleable::coupledMatrixTagScalarValue(), ScalarCoupleable::coupledScalarValue(), ScalarCoupleable::coupledScalarValueOld(), ScalarCoupleable::coupledScalarValueOlder(), and ScalarCoupleable::coupledVectorTagScalarValue().
getDistribution() [1/2]
const Distribution & DistributionInterface::getDistribution (const std::string & name) const inherited
Get a distribution with a given name.
Parameters
name The name of the parameter key of the distribution to retrieve
Returns
The distribution with name associated with the parameter 'name'
Definition at line 31 of file DistributionInterface.C.
{
  DistributionName dist_name = _dni_params.get<DistributionName>(name);
  return _dni_feproblem.getDistribution(dist_name);
}
Referenced by DistributionInterface::getDistribution(), and DistributionInterface::getDistributionByName().
getDistribution() [2/2]
template<typename T > const T & DistributionInterface::getDistribution (const std::string & name) const inherited
Definition at line 69 of file DistributionInterface.h.
{
  try
  {
    const T & dist = dynamic_cast<const T &>(getDistribution(name));
    return dist;
  }
  catch (std::bad_cast & exception)
  {
    DistributionName dist_name = _dni_params.get<DistributionName>(name);
    mooseError("The '",
               _dni_moose_object_ptr->name(),
               "' object failed to retrieve '",
               dist_name,
               "' distribution with the desired type.");
  }
}
getDistributionByName() [1/2]
const Distribution & DistributionInterface::getDistributionByName (const DistributionName & name) const inherited
Get a distribution with a given name.
Parameters
name The name of the distribution to retrieve
Returns
The distribution with name 'name'
Definition at line 38 of file DistributionInterface.C.
{
  return _dni_feproblem.getDistribution(name);
}
Referenced by RandomIC::RandomIC().
getDistributionByName() [2/2]
template<typename T > const T & DistributionInterface::getDistributionByName (const std::string & name) const inherited
Definition at line 89 of file DistributionInterface.h.
{
  try
  {
    const T & dist = dynamic_cast<const T &>(getDistribution(name));
    return dist;
  }
  catch (std::bad_cast & exception)
  {
    mooseError("The '",
               _dni_moose_object_ptr->name(),
               "' object failed to retrieve '",
               name,
               "' distribution with the desired type.");
  }
}
getElementID() [1/2]
dof_id_type ElementIDInterface::getElementID (const Elem * elem, unsigned int elem_id_index) const inline inherited
Get an element integer for an element.
Definition at line 138 of file ElementIDInterface.h.
  {
    if (elem_id_index == elem->n_extra_integers())
      return elem->subdomain_id();
    return elem->get_extra_integer(elem_id_index);
  }
getElementID() [2/2]
const dof_id_type & ElementIDInterface::getElementID (const std::string & id_parameter_name, unsigned int comp = 0) const virtual inherited
Gets an element integer with a parameter of the object derived from this interface.
Parameters
id_parameter_name Name of object parameter
comp Component number for vector of integer names
Returns
Integer for the current element
Reimplemented in Material.
Definition at line 72 of file ElementIDInterface.C.
{
  auto id = getElementIDIndex(id_parameter_name, comp);
  auto & _subproblem = *_obj_parameters.getCheckedPointerParam<SubProblem *>("_subproblem");
  auto tid = _obj_parameters.get<THREAD_ID>("_tid");
  auto & assembly = _subproblem.assembly(tid, 0);
  return assembly.extraElemID(id);
}
Referenced by Material::getElementID().
getElementIDByName()
const dof_id_type & ElementIDInterface::getElementIDByName (const std::string & id_name) const virtual inherited
Gets an element integer with the element integer name.
Parameters
id_name Name of element integer
Returns
Integer for the current element
Reimplemented in Material.
Definition at line 101 of file ElementIDInterface.C.
{
  auto id = getElementIDIndexByName(id_name);
  auto & _subproblem = *_obj_parameters.getCheckedPointerParam<SubProblem *>("_subproblem");
  auto tid = _obj_parameters.get<THREAD_ID>("_tid");
  auto & assembly = _subproblem.assembly(tid, 0);
  return assembly.extraElemID(id);
}
Referenced by Material::getElementIDByName().
getElementIDIndex()
unsigned int ElementIDInterface::getElementIDIndex (const std::string & id_parameter_name, unsigned int comp = 0) const virtual inherited
Gets index of an element integer with a parameter of the object derived from this interface.
Parameters
id_parameter_name Name of object parameter
comp Component number for vector of integer names
Returns
Index of the element integer
Definition at line 36 of file ElementIDInterface.C.
{
  auto & p = _obj_parameters.get<std::vector<ExtraElementIDName>>(id_parameter_name);
  if (comp >= p.size())
    mooseError(id_parameter_name, " does not have enough integer names");
  return getElementIDIndexByName(p[comp]);
}
Referenced by ElementIDInterface::getElementID(), and ElementIDInterface::getElementIDNeighbor().
getElementIDIndexByName()
unsigned int ElementIDInterface::getElementIDIndexByName (const std::string & id_name) const virtual inherited
Return the accessing integer for an extra element integer with its name.
Parameters
id_name Name of element integer
Returns
Index of the element integer
Definition at line 47 of file ElementIDInterface.C.
{
  if (!_id_mesh.get())
    mooseError("Mesh is not available for getting element integers");
  auto & mesh_base = _id_mesh->getMesh();
  if (id_name == "subdomain_id")
  {
    if (mesh_base.has_elem_integer(id_name))
      mooseError("MOOSE does not allow 'subdomain_id' element integer in a mesh. 'subdomain_id' is "
                 "reserved for element subdomain ID");
    return mesh_base.n_elem_integers();
  }
  if (!mesh_base.has_elem_integer(id_name))
    mooseError(
        "Mesh does not have an element integer names as ", id_name, " but required by ", _ei_name);
  auto id = mesh_base.get_elem_integer_index(id_name);
  return id;
}
Referenced by ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), ElementIDInterface::getElementIDByName(), ElementIDInterface::getElementIDIndex(), and ElementIDInterface::getElementIDNeighborByName().
getElementIDNeighbor()
const dof_id_type & ElementIDInterface::getElementIDNeighbor (const std::string & id_parameter_name, unsigned int comp = 0) const virtual inherited
Gets a neighbor element integer with a parameter of the object derived from this interface.
Parameters
id_parameter_name Name of object parameter
comp Component number for vector of integer names
Returns
Integer for the neighbor element
Reimplemented in Material.
Definition at line 86 of file ElementIDInterface.C.
{
  auto id = getElementIDIndex(id_parameter_name, comp);
  auto & _subproblem = *_obj_parameters.getCheckedPointerParam<SubProblem *>("_subproblem");
  auto tid = _obj_parameters.get<THREAD_ID>("_tid");
  auto & assembly = _subproblem.assembly(tid, 0);
  return assembly.extraElemIDNeighbor(id);
}
Referenced by Material::getElementID(), and Material::getElementIDNeighbor().
getElementIDNeighborByName()
const dof_id_type & ElementIDInterface::getElementIDNeighborByName (const std::string & id_name) const virtual inherited
Gets a neighbor element integer with the element integer name.
Parameters
id_name Name of element integer
Returns
Integer for the neighbor element
Reimplemented in Material.
Definition at line 115 of file ElementIDInterface.C.
{
  auto id = getElementIDIndexByName(id_name);
  auto & _subproblem = *_obj_parameters.getCheckedPointerParam<SubProblem *>("_subproblem");
  auto tid = _obj_parameters.get<THREAD_ID>("_tid");
  auto & assembly = _subproblem.assembly(tid, 0);
  return assembly.extraElemIDNeighbor(id);
}
Referenced by Material::getElementIDByName(), and Material::getElementIDNeighborByName().
getElemIDMapping()
std::unordered_map< dof_id_type, std::set< dof_id_type > > ElementIDInterface::getElemIDMapping (const std::string & id_name1, const std::string & id_name2) const inline inherited
Get the mapping from IDs of one extra element integer to another given the two integer names.
Definition at line 112 of file ElementIDInterface.h.
  {
    return _id_mesh->getElemIDMapping(id_name1, id_name2);
  }
getElemIDsOnBlocks()
std::set< dof_id_type > ElementIDInterface::getElemIDsOnBlocks (unsigned int elem_id_index, const std::set< SubdomainID > & blks) const inline inherited
Return all the unique element IDs for an extra element integer with its index on a set of subdomains.
Definition at line 129 of file ElementIDInterface.h.
  {
    return _id_mesh->getElemIDsOnBlocks(elem_id_index, blks);
  }
getExecuteOnEnum()
const ExecFlagEnum & SetupInterface::getExecuteOnEnum () const inherited
Return the execute on MultiMooseEnum for this object.
Definition at line 65 of file SetupInterface.C.
{
  return _execute_enum;
}
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), MultiAppTransfer::checkMultiAppExecuteOn(), IntegralPreservingFunctionIC::initialSetup(), MultiAppConservativeTransfer::initialSetup(), Terminator::initialSetup(), ElementReporter::shouldStore(), GeneralReporter::shouldStore(), and NodalReporter::shouldStore().
getFunction()
const Function & FunctionInterface::getFunction (const std::string & name) const inherited
Get a function with a given name.
Parameters
name The name of the parameter key of the function to retrieve
Returns
The function with name associated with the parameter 'name'
Definition at line 30 of file FunctionInterface.C.
{
  return _fni_feproblem.getFunction(_fni_params.get<FunctionName>(name), _fni_tid);
}
Referenced by FunctionDT::FunctionDT(), and Output::Output().
getFunctionByName()
const Function & FunctionInterface::getFunctionByName (const FunctionName & name) const inherited
Get a function with a given name.
Parameters
name The name of the function to retrieve
Returns
The function with name 'name'
Definition at line 36 of file FunctionInterface.C.
{
  return _fni_feproblem.getFunction(name, _fni_tid);
}
Referenced by ArrayBodyForce::ArrayBodyForce(), ArrayFunctionIC::ArrayFunctionIC(), CompositeFunction::CompositeFunction(), FunctionArrayAux::FunctionArrayAux(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionRankTwoTensorTempl< is_ad >::GenericFunctionRankTwoTensorTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), LinearCombinationFunction::LinearCombinationFunction(), and LineFunctionSampler::LineFunctionSampler().
getFunctor() [1/4]
template<typename T > const Moose::Functor< T > & FunctorInterface::getFunctor (const std::string & name) protected inherited
Retrieves a functor from the subproblem.
This method also leverages the ability to create default functors if the user passed an integer or real in the input file
Parameters
name The name of the functor to retrieve. This should match the functor parameter name, \emph not the actual name of the functor created in the input file
Returns
The functor
Definition at line 191 of file FunctorInterface.h.
{
  mooseAssert(_fi_subproblem, "This must be non-null");
  return getFunctor<T>(name, *_fi_subproblem, _fi_tid);
}
Referenced by MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl().
getFunctor() [2/4]
template<typename T > const Moose::Functor< T > & FunctorInterface::getFunctor (const std::string & name, SubProblem & subproblem) protected inherited
Retrieves a functor from the passed-in subproblem.
This method also leverages the ability to create default functors if the user passed an integer or real in the input file
Parameters
name The name of the functor to retrieve. This should match the functor parameter name, \emph not the actual name of the functor created in the input file
subproblem The subproblem to query for the functor
Returns
The functor
Definition at line 176 of file FunctorInterface.h.
{
  return getFunctor<T>(name, subproblem, _fi_tid);
}
getFunctor() [3/4]
template<typename T > const Moose::Functor< T > & FunctorInterface::getFunctor (const std::string & name, SubProblem & subproblem, THREAD_ID tid) protected inherited
Retrieves a functor from the passed-in subproblem.
This method also leverages the ability to create default functors if the user passed an integer or real in the input file
Parameters
name The name of the functor to retrieve. This should match the functor parameter name, \emph not the actual name of the functor created in the input file
subproblem The subproblem to query for the functor
tid The thread ID used to retrieve the functor from the subproblem
Returns
The functor
Definition at line 167 of file FunctorInterface.h.
{
  // Check if the supplied parameter is a valid input parameter key
  std::string functor_name = deduceFunctorName(name);
  return getFunctorByName<T>(functor_name, subproblem, tid);
}
getFunctor() [4/4]
template<typename T > const Moose::Functor< T > & FunctorInterface::getFunctor (const std::string & name, THREAD_ID tid) protected inherited
Retrieves a functor from the subproblem.
This method also leverages the ability to create default functors if the user passed an integer or real in the input file
Parameters
name The name of the functor to retrieve. This should match the functor parameter name, \emph not the actual name of the functor created in the input file
tid The thread ID used to retrieve the functor from this interface's subproblem
Returns
The functor
Definition at line 183 of file FunctorInterface.h.
{
  mooseAssert(_fi_subproblem, "This must be non-null");
  return getFunctor<T>(name, *_fi_subproblem, tid);
}
getFunctorByName()
template<typename T > const Moose::Functor< T > & FunctorInterface::getFunctorByName (const std::string & name, SubProblem & subproblem, THREAD_ID tid) private inherited
Retrieves a functor from the passed-in subproblem.
This method also leverages the ability to create default functors if the user passed an integer or real in the input file
Parameters
name The actual name of the functor to retrieve instead of the parameter name
subproblem The subproblem to query for the functor
tid The thread ID used to retrieve the functor from the subproblem
Returns
The functor
Definition at line 199 of file FunctorInterface.h.
{
  // Check if it's just a constant
  const auto * const default_functor = defaultFunctor<T>(name);
  if (default_functor)
    return *default_functor;
  return subproblem.getFunctor<T>(name, tid, _fi_name, isADObject());
}
getGenericZeroMaterialProperty() [1/2]
template<typename T , bool is_ad> const GenericMaterialProperty< T, is_ad > & MaterialBase::getGenericZeroMaterialProperty
Return a constant zero anonymous material property.
Definition at line 417 of file MaterialBase.h.
{
  // static zero property storage
  static GenericMaterialProperty<T, is_ad> zero(MaterialPropertyInterface::zero_property_id);
  // resize to accomodate maximum number of qpoints
  // (in multiapp scenarios getMaxQps can return different values in each app; we need the max)
  unsigned int nqp = _fe_problem.getMaxQps();
  if (nqp > zero.size())
    zero.resize(nqp);
  // set values for all qpoints to zero
  for (unsigned int qp = 0; qp < nqp; ++qp)
    MathUtils::mooseSetToZero(zero[qp]);
  return zero;
}
getGenericZeroMaterialProperty() [2/2]
template<typename T , bool is_ad> const GenericMaterialProperty< T, is_ad > & MaterialBase::getGenericZeroMaterialProperty (const std::string & name)
Return a material property that is initialized to zero by default and does not need to (but can) be declared by another material.
Definition at line 375 of file MaterialBase.h.
{
  // Check if the supplied parameter is a valid input parameter key
  std::string prop_name = name;
  if (_pars.have_parameter<MaterialPropertyName>(name))
    prop_name = _pars.get<MaterialPropertyName>(name);
  return getGenericZeroMaterialPropertyByName<T, is_ad>(prop_name);
}
getGenericZeroMaterialPropertyByName()
template<typename T , bool is_ad> const GenericMaterialProperty< T, is_ad > & MaterialBase::getGenericZeroMaterialPropertyByName (const std::string & prop_name)
Definition at line 387 of file MaterialBase.h.
{
  checkExecutionStage();
  auto & preload_with_zero = materialData().getProperty<T, is_ad>(prop_name, 0, *this);
  _requested_props.insert(prop_name);
  registerPropName(prop_name, true, 0);
  _fe_problem.markMatPropRequested(prop_name);
  // Register this material on these blocks and boundaries as a zero property with relaxed
  // consistency checking
  for (std::set<SubdomainID>::const_iterator it = blockIDs().begin(); it != blockIDs().end(); ++it)
    _fe_problem.storeSubdomainZeroMatProp(*it, prop_name);
  for (std::set<BoundaryID>::const_iterator it = boundaryIDs().begin(); it != boundaryIDs().end();
       ++it)
    _fe_problem.storeBoundaryZeroMatProp(*it, prop_name);
  // set values for all qpoints to zero
  // (in multiapp scenarios getMaxQps can return different values in each app; we need the max)
  unsigned int nqp = _fe_problem.getMaxQps();
  if (nqp > preload_with_zero.size())
    preload_with_zero.resize(nqp);
  for (unsigned int qp = 0; qp < nqp; ++qp)
    MathUtils::mooseSetToZero(preload_with_zero[qp]);
  return preload_with_zero;
}
getMasterSeed()
unsigned int RandomInterface::getMasterSeed () const inline inherited
Definition at line 66 of file RandomInterface.h.
{ return _master_seed; }
getMatPropDependencies()
virtual const std::set< unsigned int > & MaterialBase::getMatPropDependencies () const pure virtual
Retrieve the set of material properties that this object depends on.
Returns
The IDs corresponding to the material properties that MUST be reinited before evaluating this object
Implemented in InterfaceMaterial, and Material.
getMooseApp()
MooseApp & MooseBase::getMooseApp () const inline inherited
Get the MooseApp this class is associated with.
Definition at line 35 of file MooseBase.h.
{ return _app; }
Referenced by ReporterTransferInterface::checkHasReporterValue(), Coupleable::checkWritableVar(), MooseBaseParameterInterface::connectControllableParams(), Coupleable::Coupleable(), MortarData::createMortarInterface(), EigenProblem::doFreeNonlinearPowerIterations(), Terminator::execute(), FEProblemSolve::FEProblemSolve(), SolutionInvalidInterface::flagInvalidSolutionInternal(), MaterialPropertyInterface::MaterialPropertyInterface(), MooseVariableDataFV< OutputType >::MooseVariableDataFV(), ProgressOutput::output(), MooseBaseParameterInterface::paramError(), PetscOutputInterface::petscLinearOutput(), PetscOutputInterface::petscNonlinearOutput(), PetscOutputInterface::PetscOutputInterface(), PostprocessorInterface::postprocessorsAdded(), MultiApp::preTransfer(), Reporter::Reporter(), ReporterInterface::reportersAdded(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
getMooseVariableDependencies()
const std::set< MooseVariableFieldBase * > & MooseVariableDependencyInterface::getMooseVariableDependencies () const inline inherited
Retrieve the set of MooseVariableFieldBase that this object depends on.
Returns
The MooseVariableFieldBase that MUST be reinited before evaluating this object
Definition at line 35 of file MooseVariableDependencyInterface.h.
  {
    return _moose_variable_dependencies;
  }
Referenced by ComputeUserObjectsThread::subdomainChanged(), and MooseObjectWarehouseBase< T >::updateVariableDependencyHelper().
getNearestNodeLocator()
NearestNodeLocator & GeometricSearchInterface::getNearestNodeLocator (const BoundaryName & primary, const BoundaryName & secondary) inherited
Retrieve the PentrationLocator associated with the two sides.
Definition at line 53 of file GeometricSearchInterface.C.
{
  _requires_geometric_search = true;
  return _geometric_search_data.getNearestNodeLocator(primary, secondary);
}
getOutputs()
std::set< OutputName > MaterialBase::getOutputs ()
Get the list of output objects that this class is restricted.
Returns
A vector of OutputNames
Definition at line 179 of file MaterialBase.C.
{
  const std::vector<OutputName> & out = getParam<std::vector<OutputName>>("outputs");
  return std::set<OutputName>(out.begin(), out.end());
}
getParam() [1/2]
template<typename T > const T & MooseBaseParameterInterface::getParam (const std::string & name) const inherited
Retrieve a parameter for the object.
Parameters
name The name of the parameter
Returns
The value of the parameter
Definition at line 200 of file MooseBaseParameterInterface.h.
{
  return InputParameters::getParamHelper(name, _pars, static_cast<T *>(0));
}
Referenced by AddGeneralReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddPeriodicBCAction::act(), CreateDisplacedProblemAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), ConstraintWarehouse::addObject(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), ADNodalKernel::ADNodalKernel(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), PiecewiseTabularBase::buildFromJSON(), Console::Console(), FEProblemBase::createTagSolutions(), AccumulateReporter::declareLateValues(), DerivativeParsedMaterialTempl< is_ad >::DerivativeParsedMaterialTempl(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EigenKernel::EigenKernel(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), GenericConstantRankTwoTensorTempl< is_ad >::GenericConstantRankTwoTensorTempl(), MooseApp::getCheckpointDirectories(), ExecutorInterface::getExecutor(), AdvancedOutput::init(), IterationAdaptiveDT::init(), TimeSequenceStepper::init(), AttribThread::initFrom(), AttribSysNum::initFrom(), AttribResidualObject::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), Console::initialSetup(), IterationAdaptiveDT::limitDTToPostprocessorValue(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MortarConsumerInterface::MortarConsumerInterface(), NestedDivision::NestedDivision(), ConsoleUtils::outputExecutionInformation(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedMaterialTempl< is_ad >::ParsedMaterialTempl(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), ParsedODEKernel::ParsedODEKernel(), ParsedPostprocessor::ParsedPostprocessor(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), Moose::FV::setInterpolationMethod(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), TimePeriod::TimePeriod(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and VectorOfPostprocessors::VectorOfPostprocessors().
getParam() [2/2]
template<typename T1 , typename T2 > std::vector< std::pair< T1, T2 > > MooseBaseParameterInterface::getParam (const std::string & param1, const std::string & param2) const inherited
Retrieve two parameters and provide pair of parameters for the object.
Parameters
param1 The name of first parameter
param2 The name of second parameter
Returns
Vector of pairs of first and second parameters
Definition at line 257 of file MooseBaseParameterInterface.h.
{
  return _pars.get<T1, T2>(param1, param2);
}
getPenetrationLocator()
PenetrationLocator & GeometricSearchInterface::getPenetrationLocator (const BoundaryName & primary, const BoundaryName & secondary, Order order) inherited
Retrieve the PentrationLocator associated with the two sides.
Definition at line 35 of file GeometricSearchInterface.C.
{
  _requires_geometric_search = true;
  return _geometric_search_data.getPenetrationLocator(primary, secondary, order);
}
getPostprocessorName()
const PostprocessorName & PostprocessorInterface::getPostprocessorName (const std::string & param_name, const unsigned int index = 0) const inherited
Get the name of a postprocessor.
This can only be used if the postprocessor parameter does not have a default value set (see isDefaultPostprocessorValue()), in which case the "name" is actually the default value.
Parameters
param_name The name of the Postprocessor parameter
index The index of the Postprocessor
Returns
The name of the given Postprocessor
Definition at line 185 of file PostprocessorInterface.C.
{
  return getPostprocessorNameInternal(param_name, index, /* allow_default_value = */ false);
}
Referenced by EigenKernel::EigenKernel().
getPostprocessorNameInternal()
const PostprocessorName & PostprocessorInterface::getPostprocessorNameInternal (const std::string & param_name, const unsigned int index, const bool allow_default_value = true) const private inherited
Internal method for getting the PostprocessorName associated with a paremeter.
Needed in order to allow the return of a name that is a default value.
Definition at line 192 of file PostprocessorInterface.C.
{
  checkParam(param_name, index);
  const auto & name = _ppi_params.isType<PostprocessorName>(param_name)
                          ? _ppi_params.get<PostprocessorName>(param_name)
                          : _ppi_params.get<std::vector<PostprocessorName>>(param_name)[index];
  if (!allow_default_value && isDefaultPostprocessorValueByName(name))
  {
    std::stringstream oss;
    oss << "Cannot get the name associated with PostprocessorName parameter \"" << param_name
        << "\"";
    if (index)
      oss << " at index " << index;
    oss << ",\nbecause said parameter is a default Postprocessor value.";
    _ppi_moose_object.paramError(param_name, oss.str());
  }
  return name;
}
Referenced by PostprocessorInterface::getPostprocessorName(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), and PostprocessorInterface::isDefaultPostprocessorValue().
getPostprocessorValue()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValue (const std::string & param_name, const unsigned int index = 0) const inherited
doco-normal-methods-begin Retrieve the value of a Postprocessor or one of it's old or older values
Parameters
param_name The name of the Postprocessor parameter (see below)
index The index of the Postprocessor
Returns
A reference to the desired value
The name required by this method is the name that is hard-coded into your source code. For example, if you have a Kernel that requires a Postprocessor you may have an input file with "pp = my_pp", this function requires the "pp" name as input (see .../moose_test/functions/PostprocessorFunction.C)
see getPostprocessorValueByName getPostprocessorValueOldByName getPostprocessorValueOlderByName
Definition at line 36 of file PostprocessorInterface.C.
{
  return getPostprocessorValueInternal(param_name, index, /* t_index = */ 0);
}
Referenced by EigenKernel::EigenKernel(), FunctionValuePostprocessor::FunctionValuePostprocessor(), LinearCombinationPostprocessor::LinearCombinationPostprocessor(), ParsedPostprocessor::ParsedPostprocessor(), and PicardSolve::PicardSolve().
getPostprocessorValueByName()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueByName (const PostprocessorName & name) const virtual inherited
Retrieve the value of the Postprocessor.
Parameters
name Postprocessor name (see below)
Returns
A reference to the desired value
The name required by this method is the name defined in the input file. For example, if you have a Kernel that requires a Postprocessor you may have an input file with "pp = my_pp", this method requires the "my_pp" name as input (see .../moose_test/functions/PostprocessorFunction.C)
see getPostprocessorValue getPostprocessorValueOld getPostprocessorValueOlder
Definition at line 57 of file PostprocessorInterface.C.
{
  return getPostprocessorValueByNameInternal(name, /* t_index = */ 0);
}
Referenced by EigenKernel::EigenKernel(), PIDTransientControl::execute(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), ParsedODEKernel::ParsedODEKernel(), PicardSolve::savePostprocessorValues(), SecantSolve::savePostprocessorValues(), SteffensenSolve::savePostprocessorValues(), Terminator::Terminator(), PicardSolve::transformPostprocessors(), SecantSolve::transformPostprocessors(), SteffensenSolve::transformPostprocessors(), and VectorOfPostprocessors::VectorOfPostprocessors().
getPostprocessorValueByNameInternal()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueByNameInternal (const PostprocessorName & name, std::size_t t_index) const private inherited
Definition at line 246 of file PostprocessorInterface.C.
{
  mooseAssert(t_index < 3, "Invalid time index");
  mooseAssert(!isDefaultPostprocessorValueByName(name), "Should not be default");
  // If all pps have been added, we can check for existance
  if (postprocessorsAdded() && !hasPostprocessorByName(name))
    _ppi_moose_object.mooseError("A Postprocessor with the name \"", name, "\" was not found.");
  if (t_index == 0)
    addPostprocessorDependencyHelper(name);
  return _ppi_feproblem.getReporterData().getReporterValue<PostprocessorValue>(
      PostprocessorReporterName(name), _ppi_moose_object, REPORTER_MODE_ROOT, t_index);
}
Referenced by PostprocessorInterface::getPostprocessorValueByName(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::getPostprocessorValueOldByName(), and PostprocessorInterface::getPostprocessorValueOlderByName().
getPostprocessorValueInternal()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueInternal (const std::string & param_name, unsigned int index, std::size_t t_index) const private inherited
Internal methods for getting Postprocessor values.
Definition at line 218 of file PostprocessorInterface.C.
{
  const auto & name = getPostprocessorNameInternal(param_name, index);
  // If the Postprocessor is a default value (either set by addParam or set to a constant
  // value by the user in input/an action), we covert the name to a value, store said
  // value locally, and return it so that it fits in with the rest of the interface
  // (needing a reference to a value)
  if (isDefaultPostprocessorValueByName(name))
  {
    const auto value = getDefaultPostprocessorValueByName(name);
    const auto & value_ref =
        *_default_values.emplace(name, std::make_unique<PostprocessorValue>(value))
             .first->second; // first is inserted pair, second is value in pair
    mooseAssert(value == value_ref, "Inconsistent default value");
    return value_ref;
  }
  // If not a default and all pps have been added, we check check for existance
  else if (postprocessorsAdded() && !hasPostprocessorByName(name))
    _ppi_moose_object.paramError(
        param_name, "A Postprocessor with the name \"", name, "\" was not found.");
  return getPostprocessorValueByNameInternal(name, t_index);
}
Referenced by PostprocessorInterface::getPostprocessorValue(), PostprocessorInterface::getPostprocessorValueOld(), and PostprocessorInterface::getPostprocessorValueOlder().
getPostprocessorValueOld()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOld (const std::string & param_name, const unsigned int index = 0) const inherited
Definition at line 43 of file PostprocessorInterface.C.
{
  return getPostprocessorValueInternal(param_name, index, /* t_index = */ 1);
}
getPostprocessorValueOldByName()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOldByName (const PostprocessorName & name) const inherited
Definition at line 63 of file PostprocessorInterface.C.
{
  return getPostprocessorValueByNameInternal(name, /* t_index = */ 1);
}
Referenced by EigenKernel::EigenKernel().
getPostprocessorValueOlder()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOlder (const std::string & param_name, const unsigned int index = 0) const inherited
Definition at line 50 of file PostprocessorInterface.C.
{
  return getPostprocessorValueInternal(param_name, index, /* t_index = */ 2);
}
getPostprocessorValueOlderByName()
const PostprocessorValue & PostprocessorInterface::getPostprocessorValueOlderByName (const PostprocessorName & name) const inherited
Definition at line 69 of file PostprocessorInterface.C.
{
  return getPostprocessorValueByNameInternal(name, /* t_index = */ 2);
}
getQuadratureNearestNodeLocator()
NearestNodeLocator & GeometricSearchInterface::getQuadratureNearestNodeLocator (const BoundaryName & primary, const BoundaryName & secondary) inherited
Retrieve a Quadrature NearestNodeLocator associated with the two sides.
A "Quadrature" version means that it's going to find the nearest nodes to each quadrature point on this boundary
Definition at line 61 of file GeometricSearchInterface.C.
{
  _requires_geometric_search = true;
  return _geometric_search_data.getQuadratureNearestNodeLocator(primary, secondary);
}
getQuadraturePenetrationLocator()
PenetrationLocator & GeometricSearchInterface::getQuadraturePenetrationLocator (const BoundaryName & primary, const BoundaryName & secondary, Order order) inherited
Retrieve the Quadrature PentrationLocator associated with the two sides.
A "Quadrature" version means that it's going to find the penetration each quadrature point on this boundary
Definition at line 44 of file GeometricSearchInterface.C.
{
  _requires_geometric_search = true;
  return _geometric_search_data.getQuadraturePenetrationLocator(primary, secondary, order);
}
getRandomLong()
unsigned long RandomInterface::getRandomLong () const inherited
Returns the next random number (long) from the generator tied to this object (elem/node).
Definition at line 69 of file RandomInterface.C.
{
  mooseAssert(_generator, "Random Generator is NULL, did you call setRandomResetFrequency()?");
  dof_id_type id;
  if (_is_nodal)
    id = _curr_node->id();
  else
    id = _curr_element->id();
  return _generator->randl(id);
}
getRandomReal()
Real RandomInterface::getRandomReal () const inherited
Returns the next random number (Real) from the generator tied to this object (elem/node).
Definition at line 83 of file RandomInterface.C.
{
  mooseAssert(_generator, "Random Generator is NULL, did you call setRandomResetFrequency()?");
  dof_id_type id;
  if (_is_nodal)
    id = _curr_node->id();
  else
    id = _curr_element->id();
  return _generator->rand(id);
}
getRenamedParam()
template<typename T > const T & MooseBaseParameterInterface::getRenamedParam (const std::string & old_name, const std::string & new_name) const inherited
Retrieve a renamed parameter for the object.
This helper makes sure we check both names before erroring, and that only one parameter is passed to avoid silent errors
Parameters
old_name the old name for the parameter
new_name the new name for the parameter
Definition at line 207 of file MooseBaseParameterInterface.h.
{
  // this enables having a default on the new parameter but bypassing it with the old one
  // Most important: accept new parameter
  if (isParamSetByUser(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Second most: accept old parameter
  else if (isParamValid(old_name) && !isParamSetByUser(new_name))
    return InputParameters::getParamHelper(old_name, _pars, static_cast<T *>(0));
  // Third most: accept default for new parameter
  else if (isParamValid(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Refuse: no default, no value passed
  else if (!isParamValid(old_name) && !isParamValid(new_name))
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' is being retrieved without being set.\n"
               "Did you misspell it?");
  // Refuse: both old and new parameters set by user
  else
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' may not be provided alongside former parameter '" + old_name + "'");
}
getRequestedItems()
virtual const std::set< std::string > & MaterialBase::getRequestedItems () inline override virtual
Return a set of properties accessed with getMaterialProperty.
Returns
A reference to the set of properties with calls to getMaterialProperty
Implements DependencyResolverInterface.
Definition at line 180 of file MaterialBase.h.
{ return _requested_props; }
Referenced by Material::getMaterialByName().
getResetOnTime()
ExecFlagType RandomInterface::getResetOnTime () const inline inherited
Definition at line 68 of file RandomInterface.h.
{ return _reset_on; }
getRestartableData()
template<typename T , typename... Args> const T & Restartable::getRestartableData (const std::string & data_name) const protected inherited
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
Forwarded arguments are not allowed in this case because we assume that the object is restarted and we won't need different constructors to initialize it.
NOTE: This returns a const reference! Make sure you store it in a const reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
Definition at line 287 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, nullptr).get();
}
getScalarVar()
const MooseVariableScalar * ScalarCoupleable::getScalarVar (const std::string & var_name, unsigned int comp) const protected inherited
Extract pointer to a scalar coupled variable.
Parameters
var_name Name of parameter desired
comp Component number of multiple coupled variables
Returns
Pointer to the desired variable
Definition at line 311 of file ScalarCoupleable.C.
{
  const auto var_name = _sc_parameters.checkForRename(var_name_in);
  const auto it = _coupled_scalar_vars.find(var_name);
  if (it != _coupled_scalar_vars.end())
  {
    const auto & entry = it->second;
    if (comp < entry.size())
      return entry[comp];
    else
      mooseError(_sc_name, ": Trying to get a non-existent component of variable '", var_name, "'");
  }
  else
    mooseError(_sc_name, ": Trying to get a non-existent variable '", var_name, "'");
}
Referenced by ScalarCoupleable::adCoupledScalarValue(), ScalarCoupleable::coupledMatrixTagScalarValue(), ScalarCoupleable::coupledScalar(), ScalarCoupleable::coupledScalarDot(), ScalarCoupleable::coupledScalarDotDot(), ScalarCoupleable::coupledScalarDotDotDu(), ScalarCoupleable::coupledScalarDotDotOld(), ScalarCoupleable::coupledScalarDotDu(), ScalarCoupleable::coupledScalarDotOld(), ScalarCoupleable::coupledScalarOrder(), ScalarCoupleable::coupledScalarValue(), ScalarCoupleable::coupledScalarValueOld(), ScalarCoupleable::coupledScalarValueOlder(), ScalarCoupleable::coupledVectorTagScalarValue(), ParsedAuxScalar::ParsedAuxScalar(), ParsedODEKernel::ParsedODEKernel(), and ParsedScalarRateCoefficient::ParsedScalarRateCoefficient().
getScalarVariableCoupleableMatrixTags()
const std::set< TagID > & ScalarCoupleable::getScalarVariableCoupleableMatrixTags () const inline inherited
Definition at line 55 of file ScalarCoupleable.h.
  {
    return _sc_coupleable_matrix_tags;
  }
getScalarVariableCoupleableVectorTags()
const std::set< TagID > & ScalarCoupleable::getScalarVariableCoupleableVectorTags () const inline inherited
Definition at line 50 of file ScalarCoupleable.h.
  {
    return _sc_coupleable_vector_tags;
  }
getScatterVectorPostprocessorValue()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValue (const std::string & param_name, const std::string & vector_name) const inherited
Return the scatter value for the post processor.
This is only valid when you expec the vector to be of lenghth "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
param_name The name of the parameter holding the vpp name
vector_name The name of the vector
Returns
The reference to the current scatter value
Definition at line 106 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getScatterVectorPostprocessorValueByName(getVectorPostprocessorName(param_name),
                                                  vector_name);
}
getScatterVectorPostprocessorValueByName()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValueByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
Return the scatter value for the post processor.
This is only valid when you expec the vector to be of lenghth "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
name The name of the VectorPostprocessor
vector_name The name of the vector
Returns
The reference to the current scatter value
Definition at line 115 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorContextByNameHelper(name, vector_name).getScatterValue();
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValue().
getScatterVectorPostprocessorValueOld()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValueOld (const std::string & param_name, const std::string & vector_name) const inherited
Return the old scatter value for the post processor.
This is only valid when you expec the vector to be of lenghth "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
param_name The name of the parameter holding the vpp name
vector_name The name of the vector
Returns
The reference to the old scatter value
Definition at line 122 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getScatterVectorPostprocessorValueOldByName(getVectorPostprocessorName(param_name),
                                                     vector_name);
}
getScatterVectorPostprocessorValueOldByName()
const ScatterVectorPostprocessorValue & VectorPostprocessorInterface::getScatterVectorPostprocessorValueOldByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
Return the old scatter value for the post processor.
This is only valid when you expect the vector to be of length "num_procs" In that case - this will return a reference to a value that will be this processor's value from that vector
Parameters
name The name of the VectorPostprocessor
vector_name The name of the vector
Returns
The reference to the old scatter value
Definition at line 131 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorContextByNameHelper(name, vector_name).getScatterValueOld();
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValueOld().
getSeed()
unsigned int RandomInterface::getSeed (std::size_t id) inherited
Get the seed for the passed in elem/node id.
Parameters
id - dof object id
Returns
current seed for this id
Definition at line 61 of file RandomInterface.C.
{
  mooseAssert(_random_data, "RandomData object is NULL!");
  return _random_data->getSeed(id);
}
getSuppliedItems()
virtual const std::set< std::string > & MaterialBase::getSuppliedItems () inline override virtual
Return a set of properties accessed with declareProperty.
Returns
A reference to the set of properties with calls to declareProperty
Implements DependencyResolverInterface.
Definition at line 186 of file MaterialBase.h.
{ return _supplied_props; }
getSuppliedPropIDs()
const std::set< unsigned int > & MaterialBase::getSuppliedPropIDs () inline
Get the prop ids corresponding to declareProperty.
Returns
A reference to the set of properties with calls to declareProperty
Definition at line 192 of file MaterialBase.h.
{ return _supplied_prop_ids; }
getUserObject()
template<class T > const T & UserObjectInterface::getUserObject (const std::string & param_name, bool is_dependency = true) const inherited
Get an user object with a given parameter param_name.
Parameters
param_name The name of the parameter key of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with name associated with the parameter param_name
Definition at line 160 of file UserObjectInterface.h.
{
  return castUserObject<T>(getUserObjectBase(param_name, is_dependency), param_name);
}
getUserObjectBase()
const UserObject & UserObjectInterface::getUserObjectBase (const std::string & param_name, bool is_dependency = true) const inherited
Get an user object with a given parameter param_name.
Parameters
param_name The name of the parameter key of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with name associated with the parameter param_name
Definition at line 79 of file UserObjectInterface.C.
{
  const auto object_name = getUserObjectName(param_name);
  if (!hasUserObjectByName(object_name))
    _uoi_moose_object.paramError(
        param_name, "The requested UserObject with the name \"", object_name, "\" was not found.");
  return getUserObjectBaseByName(object_name, is_dependency);
}
Referenced by UserObjectInterface::getUserObject().
getUserObjectBaseByName()
const UserObject & UserObjectInterface::getUserObjectBaseByName (const UserObjectName & object_name, bool is_dependency = true) const inherited
Get an user object with the name object_name.
Parameters
object_name The name of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with the name object_name
Definition at line 91 of file UserObjectInterface.C.
{
  if (!hasUserObjectByName(object_name))
    _uoi_moose_object.mooseError(
        "The requested UserObject with the name \"", object_name, "\" was not found.");
  const auto & uo_base_tid0 = _uoi_feproblem.getUserObjectBase(object_name, /* tid = */ 0);
  if (is_dependency)
    addUserObjectDependencyHelper(uo_base_tid0);
  const THREAD_ID tid = uo_base_tid0.needThreadedCopy() ? _uoi_tid : 0;
  return _uoi_feproblem.getUserObjectBase(object_name, tid);
}
Referenced by UserObject::getDependObjects(), UserObjectInterface::getUserObjectBase(), and UserObjectInterface::getUserObjectByName().
getUserObjectByName()
template<class T > const T & UserObjectInterface::getUserObjectByName (const UserObjectName & object_name, bool is_dependency = true) const inherited
Get an user object with the name object_name.
Parameters
object_name The name of the user object to retrieve
is_dependency Whether the user object we are retrieving should be viewed as a dependency, e.g. whether the retrieved user object should be sorted and executed before this object (if we are a user object)
Returns
The user object with the name object_name
Definition at line 167 of file UserObjectInterface.h.
{
  return castUserObject<T>(getUserObjectBaseByName(object_name, is_dependency));
}
getUserObjectName()
UserObjectName UserObjectInterface::getUserObjectName (const std::string & param_name) const inherited
Returns
The name of the user object associated with the parameter param_name
Definition at line 34 of file UserObjectInterface.C.
{
  const auto & params = _uoi_moose_object.parameters();
  if (!params.isParamValid(param_name))
    _uoi_moose_object.mooseError("Failed to get a parameter with the name \"",
                                 param_name,
                                 "\" when getting a UserObjectName.",
                                 "\n\nKnown parameters:\n",
                                 _uoi_moose_object.parameters());
  // Other interfaces will use this interface (PostprocessorInterface, VectorPostprocessorInterface)
  // to grab UOs with a specialized name, so we need to check them all
  UserObjectName name;
  if (params.isType<UserObjectName>(param_name))
    name = params.get<UserObjectName>(param_name);
  else if (params.isType<PostprocessorName>(param_name))
    name = params.get<PostprocessorName>(param_name);
  else if (params.isType<VectorPostprocessorName>(param_name))
    name = params.get<VectorPostprocessorName>(param_name);
  else if (params.isType<std::string>(param_name))
    name = params.get<std::string>(param_name);
  else
    _uoi_moose_object.paramError(
        param_name,
        "Parameter of type \"",
        params.type(param_name),
        "\" is not an expected type for getting the name of a UserObject.");
  return name;
}
Referenced by UserObjectInterface::getUserObjectBase(), and UserObjectInterface::hasUserObject().
getVectorPostprocessorByNameHelper()
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorByNameHelper (const VectorPostprocessorName & name, const std::string & vector_name, bool broadcast, std::size_t t_index) const private inherited
Helper function for extracting VPP data from ReporterData object.
Definition at line 269 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessorByName(name, vector_name);
  addVectorPostprocessorDependencyHelper(name);
  const ReporterMode mode = broadcast ? REPORTER_MODE_REPLICATED : REPORTER_MODE_ROOT;
  return _vpi_feproblem.getReporterData().getReporterValue<VectorPostprocessorValue>(
      VectorPostprocessorReporterName(name, vector_name), _vpi_moose_object, mode, t_index);
}
Referenced by VectorPostprocessorInterface::getVectorPostprocessorValueByName(), and VectorPostprocessorInterface::getVectorPostprocessorValueOldByName().
getVectorPostprocessorContextByNameHelper()
const VectorPostprocessorContext< VectorPostprocessorValue > & VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper (const VectorPostprocessorName & name, const std::string & vector_name) const private inherited
Helper for getting the VPP context that handles scatter values.
Definition at line 284 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessorByName(name, vector_name);
  addVectorPostprocessorDependencyHelper(name);
  // The complete name of the store Reporter value
  const VectorPostprocessorReporterName r_name(name, vector_name);
  // Indicate the scatter value is desired, so the the VectorPostprocessorContext will do scatter
  _vpi_feproblem.getReporterData().getReporterValue<VectorPostprocessorValue>(
      r_name, _vpi_moose_object, REPORTER_MODE_VPP_SCATTER, 0);
  // Retrieve the VectorPostprocessorContext which contains the scattered value to be referenced
  const auto & context = _vpi_feproblem.getReporterData().getReporterContextBase(r_name);
  auto vpp_context_ptr =
      dynamic_cast<const VectorPostprocessorContext<VectorPostprocessorValue> *>(&context);
  mooseAssert(vpp_context_ptr, "Failed to get the VectorPostprocessorContext");
  return *vpp_context_ptr;
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValueByName(), and VectorPostprocessorInterface::getScatterVectorPostprocessorValueOldByName().
getVectorPostprocessorName()
const VectorPostprocessorName & VectorPostprocessorInterface::getVectorPostprocessorName (const std::string & param_name) const inherited
Get the name of a VectorPostprocessor associated with a parameter.
Parameters
param_name The name of the VectorPostprocessor parameter
Returns
The name of the given VectorPostprocessor
Definition at line 203 of file VectorPostprocessorInterface.C.
{
  const auto & params = _vpi_moose_object.parameters();
  if (!params.isParamValid(param_name))
    _vpi_moose_object.mooseError(
        "When getting a VectorPostprocessor, failed to get a parameter with the name \"",
        param_name,
        "\".",
        "\n\nKnown parameters:\n",
        _vpi_moose_object.parameters());
  if (!params.isType<VectorPostprocessorName>(param_name))
    _vpi_moose_object.mooseError(
        "Supplied parameter with name \"",
        param_name,
        "\" of type \"",
        params.type(param_name),
        "\" is not an expected type for getting a VectorPostprocessor.\n\n",
        "The allowed type is \"VectorPostprocessorName\".");
  return params.get<VectorPostprocessorName>(param_name);
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValue(), VectorPostprocessorInterface::getScatterVectorPostprocessorValueOld(), VectorPostprocessorInterface::getVectorPostprocessorValue(), VectorPostprocessorInterface::getVectorPostprocessorValueOld(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::isVectorPostprocessorDistributed(), and VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor().
getVectorPostprocessorValue() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValue (const std::string & param_name, const std::string & vector_name) const inherited
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the value of a VectorPostprocessor
Parameters
param_name The name of the VectorPostprocessor parameter (see below)
vector_name The name of the particular vector you want.
Returns
A reference to the desired value
The name required by this method is the name that is hard-coded into your source code. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this function requires the "pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValueOld getVectorPostprocessorValueByName getVectorPostprocessorValueOldByName
Definition at line 36 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueByName(getVectorPostprocessorName(param_name), vector_name);
}
getVectorPostprocessorValue() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValue (const std::string & param_name, const std::string & vector_name, bool needs_broadcast) const inherited
Retrieve the value of a VectorPostprocessor.
Parameters
param_name The name of the VectorPostprocessor parameter (see below)
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
A reference to the desired value
The name required by this method is the name that is hard-coded into your source code. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this function requires the "pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValueOld getVectorPostprocessorValueByName getVectorPostprocessorValueOldByName
Definition at line 66 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueByName(
      getVectorPostprocessorName(param_name), vector_name, needs_broadcast);
}
getVectorPostprocessorValueByName() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the value of the VectorPostprocessor
Parameters
name VectorPostprocessor name (see below)
vector_name The name of the particular vector you want.
Returns
A reference to the desired value
The name required by this method is the name defined in the input file. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this method requires the "my_pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValue getVectorPostprocessorValueOldByName getVectorPostprocessorValueByName
Definition at line 44 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(name, vector_name, _broadcast_by_default, 0);
}
Referenced by VectorPostprocessorInterface::getVectorPostprocessorValue().
getVectorPostprocessorValueByName() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueByName (const VectorPostprocessorName & name, const std::string & vector_name, bool needs_broadcast) const inherited
Retrieve the value of the VectorPostprocessor.
Parameters
name VectorPostprocessor name (see below)
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
A reference to the desired value
The name required by this method is the name defined in the input file. For example, if you have a Kernel that requires a VectorPostprocessor you may have an input file with "pp = my_pp", this method requires the "my_pp" name as input (see .../moose_test/functions/VectorPostprocessorFunction.C)
see getVectorPostprocessorValue getVectorPostprocessorValueOldByName getVectorPostprocessorValueByName
Definition at line 76 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(
      name, vector_name, needs_broadcast || _broadcast_by_default, 0);
}
getVectorPostprocessorValueOld() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOld (const std::string & param_name, const std::string & vector_name) const inherited
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the old value of a VectorPostprocessor
Parameters
param_name The name of the VectorPostprocessor parameter
vector_name The name of the particular vector you want.
Returns
The value of the VectorPostprocessor
see getVectorPostprocessorValue
Definition at line 51 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueOldByName(getVectorPostprocessorName(param_name), vector_name);
}
getVectorPostprocessorValueOld() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOld (const std::string & param_name, const std::string & vector_name, bool needs_broadcast) const inherited
Retrieve the old value of a VectorPostprocessor.
Parameters
param_name The name of the VectorPostprocessor parameter
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
The value of the VectorPostprocessor
see getVectorPostprocessorValue
Definition at line 86 of file VectorPostprocessorInterface.C.
{
  possiblyCheckHasVectorPostprocessor(param_name, vector_name);
  return getVectorPostprocessorValueOldByName(
      getVectorPostprocessorName(param_name), vector_name, needs_broadcast);
}
getVectorPostprocessorValueOldByName() [1/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOldByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
DEPRECATED: Use the new version where you need to specify whether or not the vector must be broadcast.
Retrieve the old value of a VectorPostprocessor
Parameters
name The name of the VectorPostprocessor
vector_name The name of the particular vector you want.
Returns
The value of the VectorPostprocessor
If within the validParams for the object the addVectorPostprocessorParam was called this method will retun a reference to the default value specified in the call to the addVectorPostprocessorParam function if the postVectorPostprocessor does not exist.
see getVectorPostprocessorValueByName
Definition at line 59 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(name, vector_name, _broadcast_by_default, 1);
}
Referenced by VectorPostprocessorInterface::getVectorPostprocessorValueOld().
getVectorPostprocessorValueOldByName() [2/2]
const VectorPostprocessorValue & VectorPostprocessorInterface::getVectorPostprocessorValueOldByName (const VectorPostprocessorName & name, const std::string & vector_name, bool needs_broadcast) const inherited
Retrieve the old value of a VectorPostprocessor.
Parameters
name The name of the VectorPostprocessor
vector_name The name of the particular vector you want.
need_broadcast Whether or not this object requires the vector to be replicated in parallel
Returns
The value of the VectorPostprocessor
If within the validParams for the object the addVectorPostprocessorParam was called this method will retun a reference to the default value specified in the call to the addVectorPostprocessorParam function if the postVectorPostprocessor does not exist.
see getVectorPostprocessorValueByName
Definition at line 96 of file VectorPostprocessorInterface.C.
{
  return getVectorPostprocessorByNameHelper(
      name, vector_name, needs_broadcast || _broadcast_by_default, 1);
}
getZeroMaterialProperty()
template<typename T , typename... Ts> const MaterialProperty< T > & MaterialBase::getZeroMaterialProperty (Ts... args) inline
for backwards compatibility
Definition at line 164 of file MaterialBase.h.
  {
    return getGenericZeroMaterialProperty<T, false>(args...);
  }
getZeroMaterialPropertyByName()
template<typename T , typename... Ts> const MaterialProperty< T > & MaterialBase::getZeroMaterialPropertyByName (Ts... args) inline
for backwards compatibility
Definition at line 171 of file MaterialBase.h.
  {
    return getGenericZeroMaterialPropertyByName<T, false>(args...);
  }
ghostable()
virtual bool MaterialBase::ghostable () const inline virtual
Whether this material supports ghosted computations.
This is important for finite volume calculations in which variables have defined values on ghost cells/elements and for which these ghost values may need to flow through material calculations to be eventually consumed by FV flux kernels or boundary conditions
Reimplemented in Material.
Definition at line 231 of file MaterialBase.h.
{ return false; }
hasBlockMaterialProperty()
template<typename T , bool is_ad> bool BlockRestrictable::hasBlockMaterialProperty (const std::string & prop_name) inherited
Check if a material property is valid for all blocks of this object.
This method returns true if the supplied property name has been declared in a Material object on the block ids for this object.
Template Parameters
T The type of material property
Parameters
prop_name the name of the property to query
Returns
true if the property exists for all block ids of the object, otherwise false
See also
Material::hasBlockMaterialProperty
Definition at line 264 of file BlockRestrictable.h.
{
  mooseAssert(_blk_material_data != NULL, "MaterialData pointer is not defined");
  return hasBlockMaterialPropertyHelper(prop_name) &&
         _blk_material_data->haveGenericProperty<T, is_ad>(prop_name);
}
hasBlockMaterialPropertyHelper()
bool BlockRestrictable::hasBlockMaterialPropertyHelper (const std::string & prop_name) protected virtual inherited
A helper method to allow the Material object to specialize the behavior of hasBlockMaterialProperty.
It also avoid circular #include problems.
See also
hasBlockMaterialProperty
Definition at line 275 of file BlockRestrictable.C.
{
  // Reference to MaterialWarehouse for testing and retrieving block ids
  const MaterialWarehouse & warehouse = _blk_feproblem->getMaterialWarehouse();
  // Complete set of ids that this object is active
  const std::set<SubdomainID> & ids = blockRestricted() ? blockIDs() : meshBlockIDs();
  // Loop over each id for this object
  for (const auto & id : ids)
  {
    // Storage of material properties that have been DECLARED on this id
    std::set<std::string> declared_props;
    // If block materials exist, populated the set of properties that were declared
    if (warehouse.hasActiveBlockObjects(id))
    {
      const std::vector<std::shared_ptr<MaterialBase>> & mats = warehouse.getActiveBlockObjects(id);
      for (const auto & mat : mats)
      {
        const std::set<std::string> & mat_props = mat->getSuppliedItems();
        declared_props.insert(mat_props.begin(), mat_props.end());
      }
    }
    // If the supplied property is not in the list of properties on the current id, return false
    if (declared_props.find(prop_name) == declared_props.end())
      return false;
  }
  // If you get here the supplied property is defined on all blocks
  return true;
}
Referenced by BlockRestrictable::hasBlockMaterialProperty().
hasBlocks() [1/5]
bool BlockRestrictable::hasBlocks (const std::set< SubdomainID > & ids) const inherited
Test if the supplied set of block ids are valid for this object.
Parameters
ids A std::set of SubdomainIDs to check
Returns
True if all of the given ids are found within the ids for this object
See also
isSubset
Definition at line 237 of file BlockRestrictable.C.
{
  if (_blk_ids.empty() || _blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return true;
  else
    return std::includes(_blk_ids.begin(), _blk_ids.end(), ids.begin(), ids.end());
}
hasBlocks() [2/5]
bool BlockRestrictable::hasBlocks (const std::vector< SubdomainID > & ids) const inherited
Test if the supplied vector block ids are valid for this object.
Parameters
ids A vector of SubdomainIDs ids to check
Returns
True if all of the given ids are found within the ids for this object
Definition at line 230 of file BlockRestrictable.C.
{
  std::set<SubdomainID> ids_set(ids.begin(), ids.end());
  return hasBlocks(ids_set);
}
hasBlocks() [3/5]
bool BlockRestrictable::hasBlocks (const std::vector< SubdomainName > & names) const inherited
Test if the supplied vector of block names are valid for this object.
Parameters
names A vector of SubdomainNames to check
Returns
True if the given ids are valid for this object
Definition at line 215 of file BlockRestrictable.C.
{
  return hasBlocks(_blk_mesh->getSubdomainIDs(names));
}
hasBlocks() [4/5]
bool BlockRestrictable::hasBlocks (const SubdomainName & name) const inherited
Test if the supplied block name is valid for this object.
Parameters
name A SubdomainName to check
Returns
True if the given id is valid for this object
Definition at line 205 of file BlockRestrictable.C.
{
  // Create a vector and utilize the getSubdomainIDs function, which
  // handles the ANY_BLOCK_ID (getSubdomainID does not)
  std::vector<SubdomainName> names(1);
  names[0] = name;
  return hasBlocks(_blk_mesh->getSubdomainIDs(names));
}
Referenced by DiracKernelBase::addPoint(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), DomainUserObject::checkVariable(), ComputeJacobianThread::compute(), DomainUserObject::DomainUserObject(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), ExtraIDIntegralVectorPostprocessor::execute(), MeshDivisionFunctorReductionVectorPostprocessor::execute(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), MooseVariableField< OutputType >::hasBlocks(), BlockRestrictable::hasBlocks(), FVFluxKernel::hasFaceSide(), and PointwiseRenormalizeVector::PointwiseRenormalizeVector().
hasBlocks() [5/5]
bool BlockRestrictable::hasBlocks (SubdomainID id) const inherited
Test if the supplied block ids are valid for this object.
Parameters
id A SubdomainID to check
Returns
True if the given id is valid for this object
Definition at line 221 of file BlockRestrictable.C.
{
  if (_blk_ids.empty() || _blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return true;
  else
    return _blk_ids.find(id) != _blk_ids.end();
}
hasBoundary() [1/5]
bool BoundaryRestrictable::hasBoundary (const BoundaryID & id) const inherited
Test if the supplied boundary ids are valid for this object.
Parameters
id A BoundaryID to check
Returns
True if the given id is valid for this object
Definition at line 224 of file BoundaryRestrictable.C.
{
  if (_bnd_ids.empty() || _bnd_ids.find(Moose::ANY_BOUNDARY_ID) != _bnd_ids.end())
    return true;
  else
    return _bnd_ids.find(id) != _bnd_ids.end();
}
hasBoundary() [2/5]
bool BoundaryRestrictable::hasBoundary (const BoundaryName & name) const inherited
Test if the supplied boundary name is valid for this object.
Parameters
name A BoundaryName to check
Returns
True if the given id is valid for this object
Definition at line 210 of file BoundaryRestrictable.C.
{
  // Create a vector and utilize the getBoundaryIDs function, which
  // handles the ANY_BOUNDARY_ID (getBoundaryID does not)
  return hasBoundary(_bnd_mesh->getBoundaryIDs({name}));
}
Referenced by BoundaryRestrictable::hasBoundary(), and BoundaryRestrictable::hasBoundaryMaterialPropertyHelper().
hasBoundary() [3/5]
bool BoundaryRestrictable::hasBoundary (const std::set< BoundaryID > & ids, TEST_TYPE type = ALL) const inherited
Test if the supplied set of boundary ids are valid for this object.
Parameters
ids A std::set of BoundaryIDs to check
type A flag for the type of matching to perform: ALL requires that all supplied ids must match those of the object; ANY requires that any one of the supplied ids must match those of the object
Returns
True if the all of the given ids are found within the ids for this object
See also
isSubset
Definition at line 240 of file BoundaryRestrictable.C.
{
  // An empty input is assumed to be ANY_BOUNDARY_ID
  if (ids.empty() || ids.find(Moose::ANY_BOUNDARY_ID) != ids.end())
    return true;
  // All supplied IDs must match those of the object
  else if (type == ALL)
  {
    if (_bnd_ids.find(Moose::ANY_BOUNDARY_ID) != _bnd_ids.end())
      return true;
    else
      return std::includes(_bnd_ids.begin(), _bnd_ids.end(), ids.begin(), ids.end());
  }
  // Any of the supplied IDs must match those of the object
  else
  {
    // Loop through the supplied ids
    for (const auto & id : ids)
    {
      // Test the current supplied id
      bool test = hasBoundary(id);
      // If the id exists in the stored ids, then return true, otherwise
      if (test)
        return true;
    }
    return false;
  }
}
hasBoundary() [4/5]
bool BoundaryRestrictable::hasBoundary (const std::vector< BoundaryID > & ids, TEST_TYPE type = ALL) const inherited
Test if the supplied vector boundary ids are valid for this object.
Parameters
ids A vector of BoundaryIDs ids to check
type A flag for the type of matching to perform: ALL requires that all supplied ids must match those of the object; ANY requires that any one of the supplied ids must match those of the object
Returns
True if the all of the given ids are found within the ids for this object
Definition at line 233 of file BoundaryRestrictable.C.
{
  std::set<BoundaryID> ids_set(ids.begin(), ids.end());
  return hasBoundary(ids_set, type);
}
hasBoundary() [5/5]
bool BoundaryRestrictable::hasBoundary (const std::vector< BoundaryName > & names) const inherited
Test if the supplied vector of boundary names are valid for this object.
Parameters
names A vector of BoundaryNames to check
Returns
True if the given ids are valid for this object
Definition at line 218 of file BoundaryRestrictable.C.
{
  return hasBoundary(_bnd_mesh->getBoundaryIDs(names));
}
hasBoundaryMaterialProperty()
template<typename T , bool is_ad> bool BoundaryRestrictable::hasBoundaryMaterialProperty (const std::string & prop_name) const inherited
Check if a material property is valid for all boundaries of this object.
This method returns true if the supplied property name has been declared in a Material object on the boundary ids for this object.
Template Parameters
T The type of material property
Parameters
prop_name the name of the property to query
Returns
true if the property exists for all boundary ids of the object, otherwise false
Definition at line 233 of file BoundaryRestrictable.h.
{
  // If you get here the supplied property is defined on all boundaries, but is still subject
  // existence in the MateialData class
  return hasBoundaryMaterialPropertyHelper(prop_name) &&
         _bnd_material_data.haveGenericProperty<T, is_ad>(prop_name);
}
hasBoundaryMaterialPropertyHelper()
bool BoundaryRestrictable::hasBoundaryMaterialPropertyHelper (const std::string & prop_name) const protected inherited
A helper method to avoid circular #include problems.
See also
hasBoundaryMaterialProperty
Definition at line 301 of file BoundaryRestrictable.C.
{
  // Reference to MaterialWarehouse for testing and retrieving boundary ids
  const MaterialWarehouse & warehouse = _bnd_feproblem->getMaterialWarehouse();
  // Complete set of BoundaryIDs that this object is defined
  const std::set<BoundaryID> & ids =
      hasBoundary(Moose::ANY_BOUNDARY_ID) ? meshBoundaryIDs() : boundaryIDs();
  // Loop over each BoundaryID for this object
  for (const auto & id : ids)
  {
    // Storage of material properties that have been DECLARED on this BoundaryID
    std::set<std::string> declared_props;
    // If boundary materials exist, populated the set of properties that were declared
    if (warehouse.hasActiveBoundaryObjects(id))
    {
      const std::vector<std::shared_ptr<MaterialBase>> & mats =
          warehouse.getActiveBoundaryObjects(id);
      for (const auto & mat : mats)
      {
        const std::set<std::string> & mat_props = mat->getSuppliedItems();
        declared_props.insert(mat_props.begin(), mat_props.end());
      }
    }
    // If the supplied property is not in the list of properties on the current id, return false
    if (declared_props.find(prop_name) == declared_props.end())
      return false;
  }
  // If you get here the supplied property is defined on all boundaries
  return true;
}
Referenced by BoundaryRestrictable::hasBoundaryMaterialProperty().
hasElementID()
bool ElementIDInterface::hasElementID (const std::string & id_name) const inline inherited
Whether mesh has an element integer with a given name.
Definition at line 82 of file ElementIDInterface.h.
{ return _id_mesh->hasElementID(id_name); }
hasFunction()
bool FunctionInterface::hasFunction (const std::string & param_name) const inherited
Determine if the function exists.
Parameters
param_name The name of the function parameter
index The index of the function
Returns
True if the function exists
Definition at line 42 of file FunctionInterface.C.
{
  return hasFunctionByName(_fni_params.get<FunctionName>(param_name));
}
hasFunctionByName()
bool FunctionInterface::hasFunctionByName (const FunctionName & name) const inherited
Determine if the function exists.
Parameters
name The name of the function
Returns
True if the function exists
Definition at line 48 of file FunctionInterface.C.
{
  return _fni_feproblem.hasFunction(name, _fni_tid);
}
Referenced by FunctionInterface::hasFunction().
hasPostprocessor()
bool PostprocessorInterface::hasPostprocessor (const std::string & param_name, const unsigned int index = 0) const inherited
Determine if the Postprocessor data exists.
Parameters
param_name The name of the Postprocessor parameter
index The index of the Postprocessor
Returns
True if the Postprocessor exists
See also
hasPostprocessorByName getPostprocessorValue
Definition at line 107 of file PostprocessorInterface.C.
{
  if (!postprocessorsAdded())
    _ppi_moose_object.mooseError(
        "Cannot call hasPostprocessor() until all Postprocessors have been constructed.");
  return hasPostprocessorByName(getPostprocessorNameInternal(param_name, index));
}
hasPostprocessorByName()
bool PostprocessorInterface::hasPostprocessorByName (const PostprocessorName & name) const inherited
Determine if the Postprocessor data exists.
Parameters
name The name of the Postprocessor
Returns
True if the Postprocessor exists
See also
hasPostprocessor getPostprocessorValueByName
Definition at line 118 of file PostprocessorInterface.C.
{
  if (!postprocessorsAdded())
    _ppi_moose_object.mooseError(
        "Cannot call hasPostprocessorByName() until all Postprocessors have been constructed.");
  return _ppi_feproblem.getReporterData().hasReporterValue<PostprocessorValue>(
      PostprocessorReporterName(name));
}
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), AdvancedOutput::initShowHideLists(), Exodus::outputReporters(), and TableOutput::outputReporters().
hasStatefulProperties()
bool MaterialBase::hasStatefulProperties () const inline
Returns
Whether this material has stateful properties
Definition at line 223 of file MaterialBase.h.
{ return _has_stateful_property; }
hasUserObject() [1/2]
bool UserObjectInterface::hasUserObject (const std::string & param_name) const inherited
Returns
Whether or not a UserObject exists with the name given by the parameter param_name.
Definition at line 67 of file UserObjectInterface.C.
{
  return hasUserObjectByName(getUserObjectName(param_name));
}
hasUserObject() [2/2]
template<class T > bool UserObjectInterface::hasUserObject (const std::string & param_name) const inherited
Definition at line 175 of file UserObjectInterface.h.
{
  return hasUserObjectByName<T>(getUserObjectName(param_name));
}
hasUserObjectByName() [1/2]
bool UserObjectInterface::hasUserObjectByName (const UserObjectName & object_name) const inherited
Definition at line 73 of file UserObjectInterface.C.
{
  return _uoi_feproblem.hasUserObject(object_name);
}
Referenced by UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::hasUserObject(), and UserObjectInterface::hasUserObjectByName().
hasUserObjectByName() [2/2]
template<class T > bool UserObjectInterface::hasUserObjectByName (const UserObjectName & object_name) const inherited
Definition at line 182 of file UserObjectInterface.h.
{
  if (!hasUserObjectByName(object_name))
    return false;
  return dynamic_cast<const T *>(&_uoi_feproblem.getUserObjectBase(object_name));
}
hasVectorPostprocessor() [1/2]
bool VectorPostprocessorInterface::hasVectorPostprocessor (const std::string & param_name) const inherited
Determine if the VectorPostprocessor exists by parameter.
Parameters
name The name of the VectorPostprocessor parameter
Returns
True if the VectorPostprocessor exists
Definition at line 168 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessor() until all "
                              "VectorPostprocessors have been constructed.");
  return hasVectorPostprocessorByName(getVectorPostprocessorName(param_name));
}
hasVectorPostprocessor() [2/2]
bool VectorPostprocessorInterface::hasVectorPostprocessor (const std::string & param_name, const std::string & vector_name) const inherited
Determine if the VectorPostprocessor data exists by parameter.
Parameters
param_name The name of the VectorPostprocessor parameter
vector_name The vector name within the VectorPostprocessor
Returns
True if the VectorPostprocessor data exists
See also
hasVectorPostprocessorByName getVectorPostprocessorValue
Definition at line 138 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessor() until all VectorPostprocessors "
                              "have been constructed.");
  return hasVectorPostprocessorByName(getVectorPostprocessorName(param_name), vector_name);
}
Referenced by VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor().
hasVectorPostprocessorByName() [1/2]
bool VectorPostprocessorInterface::hasVectorPostprocessorByName (const VectorPostprocessorName & name) const inherited
Determine if the VectorPostprocessor exists by name.
Parameters
name The name of the VectorPostprocessor
Returns
True if the VectorPostprocessor exists
Definition at line 178 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessorByName() until all "
                              "VectorPostprocessors have been constructed.");
  return _vpi_feproblem.hasUserObject(name) &&
         dynamic_cast<const VectorPostprocessor *>(&_vpi_feproblem.getUserObjectBase(name));
}
hasVectorPostprocessorByName() [2/2]
bool VectorPostprocessorInterface::hasVectorPostprocessorByName (const VectorPostprocessorName & name, const std::string & vector_name) const inherited
Determine if the VectorPostprocessor data exists by name.
Parameters
name The name of the VectorPostprocessor
vector_name The vector name within the VectorPostprocessor
Returns
True if the VectorPostprocessor data exists
See also
hasVectorPostprocessor getVectorPostprocessorValueByName
Definition at line 149 of file VectorPostprocessorInterface.C.
{
  if (!vectorPostprocessorsAdded())
    _vpi_feproblem.mooseError("Cannot call hasVectorPostprocessorByName() until all "
                              "VectorPostprocessors have been constructed.");
  const bool has_vpp = _vpi_feproblem.getReporterData().hasReporterValue<VectorPostprocessorValue>(
      VectorPostprocessorReporterName(name, vector_name));
  if (has_vpp)
    mooseAssert(_vpi_feproblem.hasUserObject(name) && dynamic_cast<const VectorPostprocessor *>(
                                                          &_vpi_feproblem.getUserObjectBase(name)),
                "Has reporter VectorPostprocessor Reporter value but not VectorPostprocessor UO");
  return has_vpp;
}
Referenced by VectorPostprocessorInterface::hasVectorPostprocessor(), AdvancedOutput::initShowHideLists(), CSV::output(), and VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName().
initializeBlockRestrictable()
void BlockRestrictable::initializeBlockRestrictable (const MooseObject * moose_object) protected inherited
An initialization routine needed for dual constructors.
Definition at line 74 of file BlockRestrictable.C.
{
  // If the mesh pointer is not defined, but FEProblemBase is, get it from there
  if (_blk_feproblem != NULL && _blk_mesh == NULL)
    _blk_mesh = &_blk_feproblem->mesh();
  // Check that the mesh pointer was defined, it is required for this class to operate
  if (_blk_mesh == NULL)
    mooseError("The input parameters must contain a pointer to FEProblem via '_fe_problem' or a "
               "pointer to the MooseMesh via '_mesh'");
  // Populate the MaterialData pointer
  if (_blk_feproblem != NULL)
    _blk_material_data = &_blk_feproblem->getMaterialData(Moose::BLOCK_MATERIAL_DATA, _blk_tid);
  // The 'block' input is defined
  if (moose_object->isParamValid("block"))
  {
    // Extract the blocks from the input
    _blocks = moose_object->getParam<std::vector<SubdomainName>>("block");
    // Store the IDs in a set, handling ANY_BLOCK_ID if supplied
    if (std::find(_blocks.begin(), _blocks.end(), "ANY_BLOCK_ID") != _blocks.end())
      _blk_ids.insert(Moose::ANY_BLOCK_ID);
    else
    {
      // Get the IDs from the supplied names
      _vec_ids = _blk_mesh->getSubdomainIDs(_blocks);
      _blk_ids.insert(_vec_ids.begin(), _vec_ids.end());
    }
  }
  // When 'blocks' is not set and there is a "variable", use the blocks from the variable
  else if (moose_object->isParamValid("variable"))
  {
    std::string variable_name = moose_object->parameters().getMooseType("variable");
    if (!variable_name.empty())
      _blk_ids = _blk_feproblem
                     ->getVariable(_blk_tid,
                                   variable_name,
                                   Moose::VarKindType::VAR_ANY,
                                   Moose::VarFieldType::VAR_FIELD_ANY)
                     .activeSubdomains();
  }
  // Produce error if the object is not allowed to be both block and boundary restricted
  if (!_blk_dual_restrictable && !_boundary_ids.empty() && !_boundary_ids.empty())
    if (!_boundary_ids.empty() && _boundary_ids.find(Moose::ANY_BOUNDARY_ID) == _boundary_ids.end())
      moose_object->paramError("block",
                               "Attempted to restrict the object '",
                               _blk_name,
                               "' to a block, but the object is already restricted by boundary");
  // If no blocks were defined above, specify that it is valid on all blocks
  if (_blk_ids.empty() && !moose_object->isParamValid("boundary"))
  {
    _blk_ids.insert(Moose::ANY_BLOCK_ID);
    _blocks = {"ANY_BLOCK_ID"};
  }
  // If this object is block restricted, check that defined blocks exist on the mesh
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) == _blk_ids.end())
  {
    const std::set<SubdomainID> & valid_ids = _blk_mesh->meshSubdomains();
    std::vector<SubdomainID> diff;
    std::set_difference(_blk_ids.begin(),
                        _blk_ids.end(),
                        valid_ids.begin(),
                        valid_ids.end(),
                        std::back_inserter(diff));
    if (!diff.empty())
    {
      std::ostringstream msg;
      auto sep = " ";
      msg << "the following blocks (ids) do not exist on the mesh:";
      for (const auto & id : diff)
      {
        if (_blk_name.size() > 0)
        {
          auto & name =
              _blocks.at(std::find(_vec_ids.begin(), _vec_ids.end(), id) - _vec_ids.begin());
          if (std::to_string(id) != name)
            msg << sep << name << " (" << id << ")";
          else
            msg << sep << id;
        }
        else
          msg << sep << id;
        sep = ", ";
      }
      moose_object->paramError("block", msg.str());
    }
  }
  // Get the mesh dimension for the blocks
  if (blockRestricted())
    _blk_dim = _blk_mesh->getBlocksMaxDimension(_blocks);
  else
    _blk_dim = _blk_mesh->dimension();
}
Referenced by BlockRestrictable::BlockRestrictable().
initializeBoundaryRestrictable()
void BoundaryRestrictable::initializeBoundaryRestrictable () private inherited
An initialization routine needed for dual constructors.
Definition at line 72 of file BoundaryRestrictable.C.
{
  // The name and id of the object
  const std::string & name = _moose_object.getParam<std::string>("_object_name");
  // If the mesh pointer is not defined, but FEProblemBase is, get it from there
  if (_bnd_feproblem != NULL && _bnd_mesh == NULL)
    _bnd_mesh = &_bnd_feproblem->mesh();
  // Check that the mesh pointer was defined, it is required for this class to operate
  if (_bnd_mesh == NULL)
    mooseError("The input parameters must contain a pointer to FEProblemBase via '_fe_problem' or "
               "a pointer to the MooseMesh via '_mesh'");
  // If the user supplies boundary IDs
  if (_moose_object.isParamValid("boundary"))
  {
    // Extract the blocks from the input
    _boundary_names = _moose_object.getParam<std::vector<BoundaryName>>("boundary");
    // Get the IDs from the supplied names
    _vec_ids = _bnd_mesh->getBoundaryIDs(_boundary_names, true);
    // Store the IDs, handling ANY_BOUNDARY_ID if supplied
    if (std::find(_boundary_names.begin(), _boundary_names.end(), "ANY_BOUNDARY_ID") !=
        _boundary_names.end())
      _bnd_ids.insert(Moose::ANY_BOUNDARY_ID);
    else
      _bnd_ids.insert(_vec_ids.begin(), _vec_ids.end());
  }
  // Produce error if the object is not allowed to be both block and boundary restricted
  if (!_bnd_dual_restrictable && !_bnd_ids.empty() && !_block_ids.empty())
    if (!_block_ids.empty() && _block_ids.find(Moose::ANY_BLOCK_ID) == _block_ids.end())
      _moose_object.paramError("boundary",
                               "Attempted to restrict the object '",
                               name,
                               "' to a boundary, but the object is already restricted by block(s)");
  // Store ANY_BOUNDARY_ID if empty
  if (_bnd_ids.empty())
  {
    _bnd_ids.insert(Moose::ANY_BOUNDARY_ID);
    _boundary_names = {"ANY_BOUNDARY_ID"};
  }
  // If this object is block restricted, check that defined blocks exist on the mesh
  if (_bnd_ids.find(Moose::ANY_BOUNDARY_ID) == _bnd_ids.end())
  {
    const std::set<BoundaryID> * valid_ids;
    const char * message_ptr = nullptr;
    if (_bnd_nodal)
    {
      valid_ids = &_bnd_mesh->meshNodesetIds();
      message_ptr = "node sets";
    }
    else
    {
      valid_ids = &_bnd_mesh->meshSidesetIds();
      message_ptr = "side sets";
    }
    std::vector<BoundaryID> diff;
    std::set_difference(_bnd_ids.begin(),
                        _bnd_ids.end(),
                        valid_ids->begin(),
                        valid_ids->end(),
                        std::back_inserter(diff));
    if (!diff.empty())
    {
      std::ostringstream msg;
      auto sep = " ";
      msg << "the following " << message_ptr << " (ids) do not exist on the mesh:";
      for (const auto & id : diff)
      {
        if (_boundary_names.size() > 0)
        {
          auto & name = _boundary_names.at(std::find(_vec_ids.begin(), _vec_ids.end(), id) -
                                           _vec_ids.begin());
          if (std::to_string(id) != name)
            msg << sep << name << " (" << id << ")";
          else
            msg << sep << id;
        }
        else
          msg << sep << id;
        sep = ", ";
      }
      if (!_bnd_nodal)
        // Diagnostic message
        msg << "\n\nMOOSE distinguishes between \"node sets\" and \"side sets\" depending on "
               "whether \nyou are using \"Nodal\" or \"Integrated\" BCs respectively. Node sets "
               "corresponding \nto your side sets are constructed for you by default.\n\n"
               "Try setting \"Mesh/construct_side_list_from_node_list=true\" if you see this "
               "error.\n"
               "Note: If you are running with adaptivity you should prefer using side sets.";
      _moose_object.paramError("boundary", msg.str());
    }
  }
}
Referenced by BoundaryRestrictable::BoundaryRestrictable().
initialSetup()
void SetupInterface::initialSetup () virtual inherited
Gets called at the beginning of the simulation before this object is asked to do its job.
Reimplemented in DerivativeSumMaterialTempl< is_ad >, AdvancedOutput, MultiAppFieldTransfer, Transfer, MortarNodalAuxKernelTempl< ComputeValueType >, ProjectedStatefulMaterialAuxTempl< T, is_ad >, SolutionAux, SolutionScalarAux, TimePeriod, Axisymmetric2D3DSolutionFunction, CoarsenedPiecewiseLinear, ImageFunction, MooseParsedFunction, MooseParsedGradFunction, MooseParsedVectorFunction, PiecewiseConstantFromCSV, PiecewiseLinear, PiecewiseLinearBase, PiecewiseTabularBase, SolutionFunction, LibtorchControlValuePostprocessor, LibtorchArtificialNeuralNetParameters, DerivativeFunctionMaterialBaseTempl< is_ad >, DerivativeFunctionMaterialBaseTempl< is_ad >, FullSolveMultiApp, MultiApp, TransientMultiApp, Console, CSV, Exodus, Nemesis, OversampleOutput, NodalVariableValue, SideIntegralMaterialPropertyTempl< is_ad >, MultiAppCloneReporterTransfer, MultiAppConservativeTransfer, MultiAppDofCopyTransfer, MultiAppGeneralFieldNearestLocationTransfer, MultiAppGeneralFieldTransfer, MultiAppProjectionTransfer, MultiAppReporterTransfer, MultiAppTransfer, MultiAppVariableValueSamplePostprocessorTransfer, MultiAppVariableValueSampleTransfer, ElementSubdomainModifier, GhostingUserObject, InterfaceQpUserObjectBase, NodalPatchRecoveryMaterialProperty, ProjectedStatefulMaterialNodalPatchRecoveryTempl< T, is_ad >, RadialAverage, SolutionUserObject, Terminator, MooseVariableBase, HistogramVectorPostprocessor, and DGFunctionTemperatureAdvection.
Definition at line 40 of file SetupInterface.C.
{
}
Referenced by LibtorchControlValuePostprocessor::initialSetup(), Console::initialSetup(), CSV::initialSetup(), and Positions::meshChanged().
initQpStatefulProperties()
void MaterialBase::initQpStatefulProperties () protected virtual
Initialize stateful properties at quadrature points.
Note when using this function you only need to address the "current" material properties not the old ones directly, i.e. if you have a property named "_diffusivity" and an older property named "_diffusivity_old". You only need to initialize diffusivity. MOOSE will use copy that initial value to the old and older values as necessary.
Reimplemented in ElectricField, ADSurfaceCharge, DerivativeParsedMaterialHelperTempl< is_ad >, GenericConstant2DArray, GenericConstantArray, GenericConstantMaterialTempl< is_ad >, GenericConstantRankTwoTensorTempl< is_ad >, GenericConstantVectorMaterialTempl< is_ad >, GenericFunctionMaterialTempl< is_ad >, GenericFunctionRankTwoTensorTempl< is_ad >, GenericFunctionVectorMaterialTempl< is_ad >, MaterialADConverterTempl< T >, MaterialFunctorConverterTempl< T >, and ParsedMaterialHelper< is_ad >.
Definition at line 133 of file MaterialBase.C.
{
  _overrides_init_stateful_props = false;
}
Referenced by initStatefulProperties().
initStatefulProperties()
void MaterialBase::initStatefulProperties (unsigned int n_points) virtual
Initialize stateful properties (if material has some)
Definition at line 114 of file MaterialBase.C.
{
  for (_qp = 0; _qp < n_points; ++_qp)
    initQpStatefulProperties();
  // checking for statefulness of properties via this loop is necessary
  // because owned props might have been promoted to stateful by calls to
  // getMaterialProperty[Old/Older] from other objects.  In these cases, this
  // object won't otherwise know that it owns stateful properties.
  for (auto & prop : _supplied_props)
    if (materialData().getMaterialPropertyStorage().isStatefulProp(prop) &&
        !_overrides_init_stateful_props)
      mooseWarning(std::string("Material \"") + name() +
                   "\" provides one or more stateful "
                   "properties but initQpStatefulProperties() "
                   "was not overridden in the derived class.");
}
isADObject()
virtual bool ADFunctorInterface::isADObject () const inline override private virtual inherited
Whether this interface is for an AD object.
Implements FunctorInterface.
Definition at line 27 of file ADFunctorInterface.h.
{ return true; }
isBlockSubset() [1/2]
bool BlockRestrictable::isBlockSubset (const std::set< SubdomainID > & ids) const inherited
Test if the class block ids are a subset of the supplied objects.
Parameters
ids A std::set of Subdomains to check
Returns
True if all of the block ids for this class are found within the given ids (opposite of hasBlocks)
See also
hasBlocks
Definition at line 246 of file BlockRestrictable.C.
{
  // An empty input is assumed to be ANY_BLOCK_ID
  if (ids.empty() || ids.find(Moose::ANY_BLOCK_ID) != ids.end())
    return true;
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return std::includes(ids.begin(),
                         ids.end(),
                         _blk_mesh->meshSubdomains().begin(),
                         _blk_mesh->meshSubdomains().end());
  else
    return std::includes(ids.begin(), ids.end(), _blk_ids.begin(), _blk_ids.end());
}
Referenced by BlockRestrictable::checkVariable(), BlockRestrictable::isBlockSubset(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), and ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux().
isBlockSubset() [2/2]
bool BlockRestrictable::isBlockSubset (const std::vector< SubdomainID > & ids) const inherited
Test if the class block ids are a subset of the supplied objects.
Parameters
ids A std::vector of Subdomains to check
Returns
True if all of the block ids for this class are found within the given ids (opposite of hasBlocks)
See also
hasBlocks
Definition at line 262 of file BlockRestrictable.C.
{
  std::set<SubdomainID> ids_set(ids.begin(), ids.end());
  return isBlockSubset(ids_set);
}
isBoundaryMaterial()
virtual bool MaterialBase::isBoundaryMaterial () const pure virtual
Returns true of the MaterialData type is not associated with volume data.
Implemented in InterfaceMaterial, and Material.
isBoundarySubset() [1/2]
bool BoundaryRestrictable::isBoundarySubset (const std::set< BoundaryID > & ids) const inherited
Test if the class boundary ids are a subset of the supplied objects.
Parameters
ids A std::set of boundaries to check
Returns
True if all of the boundary ids for this class are found within the given ids (opposite of hasBoundary)
See also
hasBoundary
Definition at line 272 of file BoundaryRestrictable.C.
{
  // An empty input is assumed to be ANY_BOUNDARY_ID
  if (ids.empty() || ids.find(Moose::ANY_BOUNDARY_ID) != ids.end())
    return true;
  if (_bnd_ids.find(Moose::ANY_BOUNDARY_ID) != _bnd_ids.end())
    return std::includes(ids.begin(),
                         ids.end(),
                         _bnd_mesh->meshBoundaryIds().begin(),
                         _bnd_mesh->meshBoundaryIds().end());
  else
    return std::includes(ids.begin(), ids.end(), _bnd_ids.begin(), _bnd_ids.end());
}
Referenced by BoundaryRestrictable::isBoundarySubset().
isBoundarySubset() [2/2]
bool BoundaryRestrictable::isBoundarySubset (const std::vector< BoundaryID > & ids) const inherited
Definition at line 288 of file BoundaryRestrictable.C.
{
  std::set<BoundaryID> ids_set(ids.begin(), ids.end());
  return isBoundarySubset(ids_set);
}
isCoupledScalar()
bool ScalarCoupleable::isCoupledScalar (const std::string & var_name, unsigned int i = 0) const protected inherited
Returns true if a variables has been coupled_as name.
Parameters
var_name The of the coupled variable
i By default 0, in general the index to test in a vector of MooseVariable pointers.
Definition at line 70 of file ScalarCoupleable.C.
{
  const auto var_name = _sc_parameters.checkForRename(var_name_in);
  auto it = _coupled_scalar_vars.find(var_name);
  if (it != _coupled_scalar_vars.end())
    return (i < it->second.size());
  else
  {
    // Make sure the user originally requested this value in the InputParameter syntax
    if (!_sc_parameters.hasCoupledValue(var_name))
      mooseError(_sc_name,
                 ": The coupled scalar variable \"",
                 var_name,
                 "\" was never added to this object's "
                 "InputParameters, please double-check "
                 "your spelling");
    return false;
  }
}
Referenced by ScalarCoupleable::adCoupledScalarValue(), Product1BodyScalar::computeQpJacobian(), Product2BodyScalar::computeQpJacobian(), Product3BodyScalar::computeQpJacobian(), EnergyTermScalar::computeQpOffDiagJacobian(), Reactant3BodyScalar::computeQpOffDiagJacobian(), EnergyTermScalar::computeQpResidual(), ScalarLinearInterpolation::computeValue(), ScalarSplineInterpolation::computeValue(), SuperelasticRateCoefficientScalar::computeValue(), ScalarCoupleable::coupledMatrixTagScalarValue(), ScalarCoupleable::coupledScalarOrder(), ScalarCoupleable::coupledScalarValue(), ScalarCoupleable::coupledScalarValueOld(), ScalarCoupleable::coupledScalarValueOlder(), and ScalarCoupleable::coupledVectorTagScalarValue().
isDefaultPostprocessorValue()
bool PostprocessorInterface::isDefaultPostprocessorValue (const std::string & param_name, const unsigned int index = 0) const inherited
Determine whether or not the Postprocessor is a default value.
A default value is when the value is either the value set by addParam, or is a user-set value in input instead of a name to a postprocessor.
Parameters
param_name The name of the Postprocessor parameter
index The index of the postprocessor
Returns
True if the Postprocessor is a default value, false if the Postprocessor is the name of a Postprocessor
Definition at line 75 of file PostprocessorInterface.C.
{
  return isDefaultPostprocessorValueByName(getPostprocessorNameInternal(param_name, index));
}
Referenced by EigenKernel::EigenKernel().
isDefaultPostprocessorValueByName()
bool PostprocessorInterface::isDefaultPostprocessorValueByName (const PostprocessorName & name) const private inherited
Returns
True if the PostprocessorName name repesents a default value: the name converts to a value (set by addParam or set via input), and a Postprocessor does not exist with the same name (we do allow Postprocessors with numbered names...)
Definition at line 82 of file PostprocessorInterface.C.
{
  // We do allow actual Postprocessor objects to have names that will succeed in being
  // represented as a double... so if the name does actually exist as a PP, it's not a default
  if (_ppi_feproblem.getReporterData().hasReporterValue<PostprocessorValue>(
          PostprocessorReporterName(name)))
    return false;
  std::istringstream ss(name);
  Real real_value = -std::numeric_limits<Real>::max();
  return (ss >> real_value && ss.eof());
}
Referenced by PostprocessorInterface::getDefaultPostprocessorValueByName(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), and PostprocessorInterface::isDefaultPostprocessorValue().
isFunctor() [1/2]
bool FunctorInterface::isFunctor (const std::string & name) const protected inherited
Checks the subproblem for the given functor.
This will not query default functors potentially stored in this object, e.g. this method will return false if the user passed an int or real to the functor param in the input file
Parameters
name The name of the functor to check. This should match the functor parameter name, \emph not the actual name of the functor created in the input file
Returns
Whether the subproblem has the specified functor
Definition at line 113 of file FunctorInterface.C.
{
  mooseAssert(_fi_subproblem, "This must be non-null");
  return isFunctor(name, *_fi_subproblem);
}
Referenced by FunctorInterface::isFunctor().
isFunctor() [2/2]
bool FunctorInterface::isFunctor (const std::string & name, const SubProblem & subproblem) const protected inherited
Checks the passed-in subproblem for the given functor.
This will not query default functors potentially stored in this object, e.g. this method will return false if the user passed an int or real to the functor param in the input file
Parameters
name The name of the functor to check. This should match the functor parameter name, \emph not the actual name of the functor created in the input file
subproblem The subproblem to query for the functor
Returns
Whether the subproblem has the specified functor
Definition at line 104 of file FunctorInterface.C.
{
  // Check if the supplied parameter is a valid input parameter key
  std::string functor_name = deduceFunctorName(name);
  return subproblem.hasFunctor(functor_name, _fi_tid);
}
isImplicit()
bool TransientInterface::isImplicit () inline inherited
Definition at line 38 of file TransientInterface.h.
{ return _is_implicit; }
Referenced by ComputeJacobianThread::compute().
isInterfaceMaterial()
virtual bool MaterialBase::isInterfaceMaterial () inline virtual
Reimplemented in InterfaceMaterial.
Definition at line 90 of file MaterialBase.h.
{ return false; };
isNodal()
bool RandomInterface::isNodal () const inline inherited
Definition at line 67 of file RandomInterface.h.
{ return _is_nodal; }
Referenced by ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementValueSampler::ElementValueSampler(), and NodalValueSampler::NodalValueSampler().
isParamSetByUser()
bool MooseBaseParameterInterface::isParamSetByUser (const std::string & nm) const inline inherited
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
Parameters
nm The name of the parameter to test
Definition at line 108 of file MooseBaseParameterInterface.h.
{ return _pars.isParamSetByUser(nm); }
Referenced by SetAdaptivityOptionsAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), LibtorchNeuralNetControl::conditionalParameterError(), MooseBaseParameterInterface::getRenamedParam(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), PiecewiseTabularBase::PiecewiseTabularBase(), MooseMesh::prepare(), and SolutionUserObject::readXda().
isParamValid()
bool MooseBaseParameterInterface::isParamValid (const std::string & name) const inline inherited
Test if the supplied parameter is valid.
Parameters
name The name of the parameter to test
Definition at line 102 of file MooseBaseParameterInterface.h.
{ return _pars.isParamValid(name); }
Referenced by AddDriftDiffusionAction::act(), AddSpecies::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CopyNodalVarsAction::act(), CreateDisplacedProblemAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), AddGeneralReactions::AddGeneralReactions(), AddZapdosReactions::AddZapdosReactions(), AdvectiveFluxAux::AdvectiveFluxAux(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), GeneratedMesh::buildMesh(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), ChemicalReactionsBase::ChemicalReactionsBase(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), CombinerGenerator::CombinerGenerator(), CSVReader::CSVReader(), ConstantReporter::declareConstantReporterValues(), DGKernelBase::DGKernelBase(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EEDFEnergyTownsendLog::EEDFEnergyTownsendLog(), Eigenvalue::Eigenvalue(), ElectronEnergyTermRate::ElectronEnergyTermRate(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), PIDTransientControl::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FileOutput::FileOutput(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FunctionDT::FunctionDT(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getRenamedParam(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), Terminator::handleMessage(), HeavySpeciesTempl< is_ad >::HeavySpeciesTempl(), HFEMDirichletBC::HFEMDirichletBC(), EigenExecutionerBase::init(), Eigenvalue::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), MooseParsedFunction::initialSetup(), MooseParsedGradFunction::initialSetup(), MooseParsedVectorFunction::initialSetup(), PiecewiseTabularBase::initialSetup(), SolutionFunction::initialSetup(), Console::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), IterationAdaptiveDT::IterationAdaptiveDT(), LeastSquaresFit::LeastSquaresFit(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MatCoupledForce::MatCoupledForce(), MooseMesh::MooseMesh(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarConsumerInterface::MortarConsumerInterface(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalExtremeValue::NodalExtremeValue(), EigenExecutionerBase::normalizeSolution(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PetscOutput::PetscOutput(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), PicardSolve::PicardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseTabularBase::PiecewiseTabularBase(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), MooseMesh::prepare(), MultiApp::readCommandLineArguments(), SolutionUserObject::readExodusII(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), MooseMesh::setCoordSystem(), FileOutput::setFileBase(), FileOutput::setFileBaseInternal(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SideDiffusiveFluxIntegralTempl< is_ad, T >::SideDiffusiveFluxIntegralTempl(), SideExtremeValue::SideExtremeValue(), SolutionUserObject::SolutionUserObject(), Terminator::Terminator(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), MultiAppDofCopyTransfer::transfer(), TransformGenerator::TransformGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
isVectorPostprocessorDistributed()
bool VectorPostprocessorInterface::isVectorPostprocessorDistributed (const std::string & param_name) const inherited
Return true if the VectorPostprocessor is marked with parallel_type as DISTRIBUTED.
Definition at line 190 of file VectorPostprocessorInterface.C.
{
  return isVectorPostprocessorDistributedByName(getVectorPostprocessorName(param_name));
}
isVectorPostprocessorDistributedByName()
bool VectorPostprocessorInterface::isVectorPostprocessorDistributedByName (const VectorPostprocessorName & name) const inherited
Definition at line 196 of file VectorPostprocessorInterface.C.
{
  return _vpi_feproblem.getVectorPostprocessorObjectByName(name).isDistributed();
}
Referenced by VectorPostprocessorInterface::isVectorPostprocessorDistributed().
jacobianSetup()
void SetupInterface::jacobianSetup () virtual inherited
Gets called just before the Jacobian is computed and before this object is asked to do its job.
Reimplemented in EqualValueEmbeddedConstraint, Function, ADKernelTempl< T >, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 50 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::jacobianSetup(), and ComputeFVFluxJacobianThread< RangeType >::setup().
makeElemArg()
Moose::ElemArg FunctorInterface::makeElemArg (const Elem * elem, bool correct_skewnewss = false) const protected inherited
Helper method to create an elemental argument for a functor that includes whether to perform skewness corrections.
Definition at line 120 of file FunctorInterface.C.
{
  return {elem, correct_skewness};
}
Referenced by FVCoupledForce::computeQpResidual(), FVFunctorTimeKernel::computeQpResidual(), FVBoundedValueConstraint::computeQpResidual(), FVIntegralValueConstraint::computeQpResidual(), FVPointValueConstraint::computeQpResidual(), FunctorAux::computeValue(), SecondTimeDerivativeAux::computeValue(), TimeDerivativeAux::computeValue(), and FunctorTimes::initialize().
materialData() [1/2]
virtual const MaterialData & MaterialBase::materialData () const protected pure virtual
Implemented in InterfaceMaterial, and Material.
Referenced by declareGenericPropertyByName(), getGenericZeroMaterialPropertyByName(), initStatefulProperties(), and registerPropName().
materialData() [2/2]
virtual MaterialData & MaterialBase::materialData () protected pure virtual
Implemented in InterfaceMaterial, and Material.
maxElementID()
dof_id_type ElementIDInterface::maxElementID (unsigned int elem_id_index) const inline inherited
Return the maximum element ID for an element integer with its index.
Definition at line 87 of file ElementIDInterface.h.
  {
    return _id_mesh->maxElementID(elem_id_index);
  }
meshBlockIDs()
const std::set< SubdomainID > & BlockRestrictable::meshBlockIDs () const inherited
Return all of the SubdomainIDs for the mesh.
Returns
A set of all subdomians for the entire mesh
Definition at line 269 of file BlockRestrictable.C.
{
  return _blk_mesh->meshSubdomains();
}
Referenced by BlockRestrictable::checkVariable(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), and SolutionIC::initialSetup().
meshBoundaryIDs()
const std::set< BoundaryID > & BoundaryRestrictable::meshBoundaryIDs () const inherited
Returns the set of all boundary ids for the entire mesh.
Returns
A const reference the the boundary ids for the entire mesh
Definition at line 295 of file BoundaryRestrictable.C.
{
  return _bnd_mesh->getBoundaryIDs();
}
Referenced by BoundaryRestrictable::hasBoundaryMaterialPropertyHelper().
meshChanged()
virtual void MeshChangedInterface::meshChanged () inline virtual inherited
Called on this object when the mesh changes.
Reimplemented in GeometryBase, EqualValueBoundaryConstraint, DiracKernelBase, FVPointValueConstraint, MeshDivision, Console, Exodus, Nemesis, OversampleOutput, Positions, ExplicitTimeIntegrator, MultiAppVariableValueSamplePostprocessorTransfer, GhostingUserObject, NearestNodeNumberUO, RadialAverage, MooseVariableDataFV< OutputType >, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 34 of file MeshChangedInterface.h.
{}
Referenced by MooseVariableFE< OutputType >::meshChanged(), and MooseVariableFV< OutputType >::meshChanged().
minElementID()
dof_id_type ElementIDInterface::minElementID (unsigned int elem_id_index) const inline inherited
Return the minimum element ID for an element integer with its index.
Definition at line 95 of file ElementIDInterface.h.
  {
    return _id_mesh->minElementID(elem_id_index);
  }
miProblem() [1/2]
virtual FEProblemBase & MaterialBase::miProblem () inline protected virtual
Definition at line 276 of file MaterialBase.h.
{ return _fe_problem; }
miProblem() [2/2]
virtual const FEProblemBase & MaterialBase::miProblem () const inline protected virtual
Definition at line 275 of file MaterialBase.h.
{ return _fe_problem; }
mooseDeprecated()
template<typename... Args> void MooseBaseErrorInterface::mooseDeprecated (Args &&... args) const inline inherited
Definition at line 78 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseDeprecatedStream(_console, false, true, std::forward<Args>(args)...);
  }
Referenced by FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::advanceMultiApps(), MultiApp::appProblem(), Executioner::augmentedPicardConvergenceCheck(), MooseMesh::buildSideList(), FEProblemBase::computeResidual(), AddVariableAction::determineType(), Eigenvalue::Eigenvalue(), MooseMesh::elem(), FunctionDT::FunctionDT(), RandomICBase::generateRandom(), MooseMesh::getBoundariesToElems(), Control::getExecuteOptions(), FEProblemBase::getNonlinearSystem(), FEProblemBase::getUserObjects(), FEProblemBase::hasPostprocessor(), MooseMesh::node(), FixedPointSolve::numPicardIts(), RelationshipManager::operator>=(), Executioner::picardSolve(), and MooseMesh::setBoundaryToNormalMap().
mooseError()
template<typename... Args> void MooseBaseErrorInterface::mooseError (Args &&... args) const inline inherited
Emits an error prefixed with object name and type.
Definition at line 38 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, errorPrefix("error"), std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
Referenced by HierarchicalGridPartitioner::_do_partition(), PetscExternalPartitioner::_do_partition(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AdaptivityAction::act(), AddFVICAction::act(), AddICAction::act(), AddMeshGeneratorAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVectorPostprocessorAction::act(), CheckFVBCAction::act(), CheckIntegrityAction::act(), CommonOutputAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DeprecatedBlockAction::act(), InitProblemAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetAdaptivityOptionsAction::act(), SetupMeshAction::act(), SetupMeshCompleteAction::act(), SetupPredictorAction::act(), SetupTimeStepperAction::act(), SplitMeshAction::act(), FEProblemBase::adaptMesh(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::addConstraint(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFVInitialCondition(), AddGeneralReactions::AddGeneralReactions(), FEProblemBase::addInitialCondition(), FEProblemBase::addLineSearch(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addOutput(), SubProblem::addPiecewiseByBlockLambdaFunctor(), DistributedRectilinearMeshGenerator::addPoint(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), FEProblemBase::addPostprocessor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseMesh::addQuadratureNode(), FEProblemBase::addReporter(), AddVariableAction::addVariable(), FEProblemBase::addVectorPostprocessor(), SubProblem::addVectorTag(), AddZapdosReactions::AddZapdosReactions(), ADEEDFRateConstantTownsend::ADEEDFRateConstantTownsend(), ADGasElectronMoments::ADGasElectronMoments(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), MooseVariableScalar::adUDot(), Output::advancedExecuteOn(), AdvectiveFluxAux::AdvectiveFluxAux(), ADZapdosEEDFRateConstant::ADZapdosEEDFRateConstant(), MooseVariableBase::allDofIndices(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayConstantIC::ArrayConstantIC(), ArrayFunctionIC::ArrayFunctionIC(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), Function::average(), Axisymmetric2D3DSolutionFunction::Axisymmetric2D3DSolutionFunction(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), BoltzmannSolverScalar::BoltzmannSolverScalar(), BoundingValueElementDamper::BoundingValueElementDamper(), BoundingValueNodalDamper::BoundingValueNodalDamper(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), MooseMesh::buildCoarseningMap(), MultiApp::buildComm(), DistributedRectilinearMeshGenerator::buildCube(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), PiecewiseTabularBase::buildFromXY(), MooseMesh::buildLowerDMesh(), GeneratedMesh::buildMesh(), MeshGeneratorMesh::buildMesh(), SpiralAnnularMesh::buildMesh(), TiledMesh::buildMesh(), ImageMesh::buildMesh3D(), ImageMeshGenerator::buildMesh3D(), MooseMesh::buildRefinementMap(), buildRequiredMaterials(), MooseMesh::buildSideList(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), UserObjectInterface::castUserObject(), EigenExecutionerBase::chebyshev(), SubProblem::checkBlockMatProps(), SubProblem::checkBoundaryMatProps(), MooseMesh::checkCoordinateSystems(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkDisplacementOrders(), FEProblemBase::checkDuplicatePostprocessorVariableNames(), MooseMesh::checkDuplicateSubdomainNames(), checkExecutionStage(), MeshGenerator::checkGetMesh(), ReporterTransferInterface::checkHasReporterValue(), FEProblemBase::checkICRestartError(), EigenExecutionerBase::checkIntegrity(), Eigenvalue::checkIntegrity(), Steady::checkIntegrity(), ExplicitTimeIntegrator::checkLinearConvergence(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), PostprocessorInterface::checkParam(), FEProblemBase::checkProblemIntegrity(), Sampler::checkReinitStatus(), checkStatefulSanity(), FEProblemBase::checkUserObjects(), MultiAppTransfer::checkVariable(), DomainUserObject::checkVariable(), ChemicalReactionsBase::ChemicalReactionsBase(), MooseMesh::clone(), LibmeshPartitioner::clone(), CombinerGenerator::CombinerGenerator(), ElementSubdomainModifier::complementMovingBoundaryID(), ElementSubdomainModifier::complementMovingBoundaryName(), MooseVariableFieldBase::componentName(), CompositeFunction::CompositeFunction(), NodalPatchRecovery::compute(), VariableCondensationPreconditioner::computeDInverseDiag(), CompositionDT::computeDT(), MooseVariableFieldBase::computeFaceValues(), TimeStepper::computeFailedDT(), IterationAdaptiveDT::computeFailedDT(), TimeSequenceStepperBase::computeFailedDT(), MooseMesh::computeFiniteVolumeCoords(), FVFluxKernel::computeJacobian(), ArrayKernel::computeJacobian(), ArrayKernel::computeOffDiagJacobian(), FVElementalKernel::computeOffDiagJacobian(), computeProperties(), ScalarKernel::computeQpJacobian(), ScalarKernel::computeQpResidual(), FVFluxKernel::computeResidual(), ArrayKernel::computeResidual(), FVFluxBC::computeResidual(), ResidualObject::computeResidualAndJacobian(), FVFluxKernel::computeResidualAndJacobian(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualL2Norm(), FEProblemBase::computeResidualTag(), FEProblemBase::computeResidualType(), TimeStepper::computeStep(), ActuallyExplicitEuler::computeTimeDerivatives(), AStableDirk4::computeTimeDerivatives(), BDF2::computeTimeDerivatives(), CrankNicolson::computeTimeDerivatives(), ExplicitEuler::computeTimeDerivatives(), ExplicitRK2::computeTimeDerivatives(), ExplicitTVDRK2::computeTimeDerivatives(), ImplicitEuler::computeTimeDerivatives(), ImplicitMidpoint::computeTimeDerivatives(), LStableDirk2::computeTimeDerivatives(), LStableDirk3::computeTimeDerivatives(), LStableDirk4::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), FEProblemBase::computeUserObjectsInternal(), BolsigValueScalar::computeValue(), PenetrationAux::computeValue(), BuildArrayVariableAux::computeValue(), TagVectorArrayVariableAux::computeValue(), ConcentricCircleMesh::ConcentricCircleMesh(), ConditionalEnableControl::ConditionalEnableControl(), TimeStepper::constrainStep(), LibtorchNeuralNetControl::controlNeuralNet(), AddVariableAction::createInitialConditionAction(), DataRead::DataRead(), ReporterTransferInterface::declareClone(), MeshGenerator::declareMeshProperty(), ReporterTransferInterface::declareVectorClone(), FunctorRelationshipManager::delete_remote_elements(), MooseMesh::deleteRemoteElements(), BicubicSplineFunction::derivative(), MooseMesh::detectPairedSidesets(), FEProblemBase::determineNonlinearSystem(), MeshDiagnosticsGenerator::diagnosticsLog(), DiffusionRateTemp::DiffusionRateTemp(), FunctorBinnedValuesDivision::divisionIndex(), FunctorRelationshipManager::dofmap_reinit(), FEProblemBase::duplicateVariableCheck(), EEDFRateConstant::EEDFRateConstant(), EEDFRateConstantTownsend::EEDFRateConstantTownsend(), Eigenvalue::Eigenvalue(), ElectricField::ElectricField(), ElectronMobility::ElectronMobility(), ElementIntegerAux::ElementIntegerAux(), ElementQualityAux::ElementQualityAux(), ElementUOAux::ElementUOAux(), DistributedRectilinearMeshGenerator::elemId(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), MooseMesh::errorIfDistributedMesh(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), BoltzmannSolverScalar::execute(), Eigenvalue::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), ElementQualityChecker::execute(), DiscreteElementUserObject::execute(), DomainUserObject::execute(), FEProblemBase::execute(), FEProblemBase::executeControls(), MultiAppVectorPostprocessorTransfer::executeFromMultiapp(), MultiAppVectorPostprocessorTransfer::executeToMultiapp(), ExplicitSSPRungeKutta::ExplicitSSPRungeKutta(), FileOutput::FileOutput(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), ElementQualityChecker::finalize(), VerifyElementUniqueID::finalize(), VerifyNodalUniqueID::finalize(), DiscreteElementUserObject::finalize(), Transfer::find_sys(), BreakMeshByBlockGeneratorBase::findFreeBoundaryId(), FunctionDT::FunctionDT(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), GapValueAux::GapValueAux(), Gas::Gas(), GasBase::GasBase(), GasElectronMoments::GasElectronMoments(), AllSideSetsByNormalsGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundingBoxNodeSetGenerator::generate(), BreakMeshByBlockGenerator::generate(), CombinerGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshCollectionGenerator::generate(), MeshDiagnosticsGenerator::generate(), MeshExtruderGenerator::generate(), MeshRepairGenerator::generate(), MoveNodeGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), SideSetsFromNormalsGenerator::generate(), SideSetsFromPointsGenerator::generate(), SmoothMeshGenerator::generate(), SpiralAnnularMeshGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), TiledMeshGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GeneratedMesh::GeneratedMesh(), GeneratedMeshGenerator::GeneratedMeshGenerator(), MeshGenerator::generateInternal(), CircularBoundaryCorrectionGenerator::generateRadialCorrectionFactor(), RandomICBase::generateRandom(), GenericConstantMaterialTempl< is_ad >::GenericConstantMaterialTempl(), GenericConstantVectorMaterialTempl< is_ad >::GenericConstantVectorMaterialTempl(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), DisplacedProblem::getActualFieldVariable(), FEProblemBase::getActualFieldVariable(), DisplacedProblem::getArrayVariable(), FEProblemBase::getArrayVariable(), MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::getBlockConnectedBlocks(), VariableOldValueBoundsAux::getBound(), MooseMesh::getBoundaryID(), MultiApp::getBoundingBox(), MooseMesh::getCoarseningMap(), MooseVariableBase::getContinuity(), Control::getControllableParameterByName(), MooseMesh::getCoordSystem(), PropertyReadFile::getData(), TransfiniteMeshGenerator::getDiscreteEdge(), FEProblemBase::getDistribution(), MooseVariableBase::getDofIndices(), VariableCondensationPreconditioner::getDofToCondense(), TransfiniteMeshGenerator::getEdge(), GhostingUserObject::getElementalValue(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), PropertyReadFile::getElementData(), MooseMesh::getElementIDIndex(), Material::getElementIDNeighbor(), Material::getElementIDNeighborByName(), MooseMesh::getElemIDMapping(), MooseMesh::getElemIDsOnBlocks(), MultiAppFieldTransfer::getEquationSystem(), MultiApp::getExecutioner(), MultiAppTransfer::getFromMultiApp(), MultiAppTransfer::getFromMultiAppInfo(), FEProblemBase::getFunction(), SubProblem::getFunctor(), MooseMesh::getGeneralAxisymmetricCoordAxis(), DistributedRectilinearMeshGenerator::getGhostNeighbors(), BatchMaterial< Tuple, Output, Input >::getIndex(), DistributedRectilinearMeshGenerator::getIndices(), SolutionUserObject::getLocalVarIndex(), Material::getMaterialByName(), FEProblemBase::getMaterialData(), SubProblem::getMatrixTagID(), AnnularMesh::getMaxInDimension(), GeneratedMesh::getMaxInDimension(), FEProblemBase::getMaxQps(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), AnnularMesh::getMinInDimension(), GeneratedMesh::getMinInDimension(), MultiAppTransfer::getMultiApp(), DistributedRectilinearMeshGenerator::getNeighbors(), MooseMesh::getNodeBlockIds(), PropertyReadFile::getNodeData(), MooseMesh::getNodeList(), FEProblemBase::getNonlinearSystem(), MooseMesh::getPairedBoundaryMapping(), ImageMesh::GetPixelInfo(), ImageMeshGenerator::GetPixelInfo(), PlaneIDMeshGenerator::getPlaneID(), FEProblemBase::getPositionsObject(), PostprocessorInterface::getPostprocessorValueByNameInternal(), MooseMesh::getRefinementMap(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), FEProblemBase::getSampler(), JSONFileReader::getScalar(), DisplacedProblem::getScalarVariable(), FEProblemBase::getScalarVariable(), DisplacedProblem::getStandardVariable(), FEProblemBase::getStandardVariable(), MooseMesh::getSubdomainBoundaryIds(), DisplacedProblem::getSystem(), FEProblemBase::getSystem(), FEProblemBase::getTimeFromStateArg(), Transient::getTimeIntegratorName(), MultiAppTransfer::getToMultiApp(), MultiAppTransfer::getToMultiAppInfo(), MooseMesh::getUniqueCoordSystem(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::getUserObjectName(), JSONFileReader::getVector(), VectorPostprocessorInterface::getVectorPostprocessorName(), SubProblem::getVectorTag(), SubProblem::getVectorTagID(), DisplacedProblem::getVectorVariable(), FEProblemBase::getVectorVariable(), GhostingAux::GhostingAux(), MultiApp::globalAppToLocal(), Function::gradient(), MooseParsedVectorFunction::gradient(), Terminator::handleMessage(), MooseVariableBase::hasDoFsOnNodes(), PostprocessorInterface::hasPostprocessor(), PostprocessorInterface::hasPostprocessorByName(), ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), AddVariableAction::init(), MooseMesh::init(), Sampler::init(), AddAuxVariableAction::init(), EigenExecutionerBase::init(), Eigenvalue::init(), Transient::init(), FEProblemBase::init(), CrankNicolson::init(), ExplicitTimeIntegrator::init(), CSVTimeSequenceStepper::init(), IterationAdaptiveDT::init(), MultiApp::init(), FEProblemBase::initialAdaptMesh(), BoltzmannSolverScalar::initialize(), PolynomialCoefficients::initialize(), CartesianGridDivision::initialize(), CylindricalGridDivision::initialize(), NestedDivision::initialize(), SphericalGridDivision::initialize(), SubProblem::initialSetup(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), Axisymmetric2D3DSolutionFunction::initialSetup(), MooseParsedFunction::initialSetup(), SolutionFunction::initialSetup(), SolutionIC::initialSetup(), FullSolveMultiApp::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), SolutionUserObject::initialSetup(), Function::integral(), InterpolatedCoefficientLinear::InterpolatedCoefficientLinear(), InterpolatedCoefficientSpline::InterpolatedCoefficientSpline(), EigenExecutionerBase::inversePowerIteration(), InversePowerMethod::InversePowerMethod(), Sampler::isAdaptiveSamplingCompleted(), MooseMesh::isBoundaryFullyExternalToSubdomains(), MooseVariableBase::isNodal(), IterationAdaptiveDT::IterationAdaptiveDT(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LineSearch::lineSearch(), ReporterPointMarker::markerSetup(), Material::Material(), MaterialOutputAction::materialOutputHelper(), MaterialRealTensorValueAux::MaterialRealTensorValueAux(), MaterialRealVectorValueAuxTempl< is_ad >::MaterialRealVectorValueAuxTempl(), Distribution::median(), FunctorRelationshipManager::mesh_reinit(), SubProblem::meshChanged(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshExtruderGenerator::MeshExtruderGenerator(), MeshRepairGenerator::MeshRepairGenerator(), SetupMeshAction::modifyParamsForUseSplit(), MeshMetaDataInterface::mooseErrorInternal(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MoveNodeGenerator::MoveNodeGenerator(), ElementSubdomainModifier::movingBoundaryID(), ElementSubdomainModifier::movingBoundaryName(), MultiApp::MultiApp(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NearestNodeDistanceAux::NearestNodeDistanceAux(), NearestNodeValueAux::NearestNodeValueAux(), FEProblemBase::needsPreviousNewtonIteration(), NewmarkBeta::NewmarkBeta(), NodalPatchRecoveryBase::nodalPatchRecovery(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), DistributedRectilinearMeshGenerator::nodeId(), DistributedRectilinearMeshGenerator::numNeighbors(), Output::onInterval(), FunctorRelationshipManager::operator()(), RelationshipManager::operator==(), MortarNodalGeometryOutput::output(), Output::Output(), DistributedRectilinearMeshGenerator::paritionSquarely(), PiecewiseBilinear::parse(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), ExplicitTimeIntegrator::performExplicitSolve(), PetscExternalPartitioner::PetscExternalPartitioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), Executioner::picardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseMulticonstant::PiecewiseMulticonstant(), PiecewiseTabularBase::PiecewiseTabularBase(), SolutionUserObject::pointValueGradientWrapper(), SolutionUserObject::pointValueWrapper(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName(), AStableDirk4::postResidual(), ExplicitRK2::postResidual(), ExplicitTVDRK2::postResidual(), ImplicitMidpoint::postResidual(), LStableDirk2::postResidual(), LStableDirk3::postResidual(), LStableDirk4::postResidual(), VariableCondensationPreconditioner::preallocateCondensedJacobian(), Predictor::Predictor(), Transient::preExecute(), MooseMesh::prepare(), MooseMesh::prepared(), FixedPointSolve::printFixedPointConvergenceReason(), RateCoefficientProvider::RateCoefficientProvider(), RateCoefficientProvider::reaction_coefficient(), RateCoefficientProvider::reaction_coefficient_derivative(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readExodusII(), SolutionUserObject::readXda(), FunctorRelationshipManager::redistribute(), Sampler::reinit(), RinglebMesh::RinglebMesh(), RinglebMeshGenerator::RinglebMeshGenerator(), PiecewiseMultiInterpolation::sample(), ScalarComponentIC::ScalarComponentIC(), ScalarLinearInterpolation::ScalarLinearInterpolation(), ScalarSplineInterpolation::ScalarSplineInterpolation(), DistributedRectilinearMeshGenerator::scaleNodalPositions(), BicubicSplineFunction::secondDerivative(), FunctorRelationshipManager::set_mesh(), MooseVariableBase::setActiveTags(), DistributedRectilinearMeshGenerator::setBoundaryNames(), MooseMesh::setCoordSystem(), FEProblemBase::setCoupling(), PiecewiseBase::setData(), FileOutput::setFileBaseInternal(), MooseMesh::setGeneralAxisymmetricCoordAxes(), FEProblemSolve::setInnerSolve(), MeshGenerator::setMeshProperty(), FEProblemBase::setNonlocalCouplingMatrix(), Sampler::setNumberOfCols(), Sampler::setNumberOfRandomSeeds(), Sampler::setNumberOfRows(), Split::setup(), TransientMultiApp::setupApp(), SetupMeshAction::setupMesh(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), TimePeriodBase::setupTimes(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SideSetsFromNormalsGenerator::SideSetsFromNormalsGenerator(), SideSetsFromPointsGenerator::SideSetsFromPointsGenerator(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), SolutionTimeAdaptiveDT::SolutionTimeAdaptiveDT(), SolutionUserObject::SolutionUserObject(), FullSolveMultiApp::solveStep(), UserObject::spatialPoints(), UserObject::spatialValue(), SpiralAnnularMesh::SpiralAnnularMesh(), SpiralAnnularMeshGenerator::SpiralAnnularMeshGenerator(), StitchedMesh::StitchedMesh(), subdomainSetup(), GeneralUserObject::subdomainSetup(), NodalUserObject::subdomainSetup(), Constraint::subdomainSetup(), SuperelasticReactionRate::SuperelasticReactionRate(), FEProblemBase::swapBackMaterialsNeighbor(), Terminator::Terminator(), GeneralUserObject::threadJoin(), ThreadedGeneralUserObject::threadJoin(), DiscreteElementUserObject::threadJoin(), TimePeriodBase::TimePeriodBase(), VectorPostprocessorVisualizationAux::timestepSetup(), FEProblemBase::trustUserCouplingMatrix(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), FEProblemBase::uDotDotOldRequested(), MooseVariableScalar::uDotOld(), FEProblemBase::uDotOldRequested(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), SolutionUserObject::updateExodusBracketingTimeIndices(), FEProblemBase::updateMaxQps(), BoundingBoxIC::value(), Function::value(), Axisymmetric2D3DSolutionFunction::value(), PiecewiseConstantFromCSV::value(), ValueProvider::ValueProvider(), ValueRangeMarker::ValueRangeMarker(), ValueThresholdMarker::ValueThresholdMarker(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), MultiAppTransfer::variableIntegrityCheck(), VariableTimeIntegrationAux::VariableTimeIntegrationAux(), AddVariableAction::variableType(), Function::vectorCurl(), SubProblem::vectorTagName(), SubProblem::vectorTagType(), Function::vectorValue(), MooseParsedFunction::vectorValue(), MooseParsedGradFunction::vectorValue(), SubProblem::verifyVectorTags(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
mooseErrorNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseErrorNonPrefixed (Args &&... args) const inline inherited
Emits an error without the prefixing included in mooseError().
Definition at line 50 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
mooseInfo()
template<typename... Args> void MooseBaseErrorInterface::mooseInfo (Args &&... args) const inline inherited
Definition at line 84 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseInfoStream(_console, std::forward<Args>(args)...);
  }
Referenced by AddZapdosReactions::act(), SetupRecoverFileBaseAction::act(), AStableDirk4::AStableDirk4(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), BoltzmannSolverScalar::execute(), ExplicitRK2::ExplicitRK2(), ExplicitTVDRK2::ExplicitTVDRK2(), MultiAppTransfer::getPointInTargetAppFrame(), ImplicitMidpoint::ImplicitMidpoint(), InversePowerMethod::InversePowerMethod(), LStableDirk2::LStableDirk2(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), NonlinearEigen::NonlinearEigen(), ProjectionAux::ProjectionAux(), FEProblemBase::setRestartFile(), and SymmetryTransformGenerator::SymmetryTransformGenerator().
mooseWarning()
template<typename... Args> void MooseBaseErrorInterface::mooseWarning (Args &&... args) const inline inherited
Emits a warning prefixed with object name and type.
Definition at line 62 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(
        _console, errorPrefix("warning"), std::forward<Args>(args)...);
  }
Referenced by AddFunctionAction::act(), AddKernelAction::act(), CommonOutputAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupMeshAction::act(), DumpObjectsProblem::addAuxVariable(), DiracKernelBase::addPoint(), BoundaryMarker::BoundaryMarker(), BoundsAuxBase::BoundsAuxBase(), DistributedRectilinearMeshGenerator::buildCube(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), CartesianMeshGenerator::CartesianMeshGenerator(), CheckOutputAction::checkConsoleOutput(), MultiAppTransfer::checkMultiAppExecuteOn(), GapValueAux::computeValue(), MeshDiagnosticsGenerator::diagnosticsLog(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), Postprocessor::evaluateDotWarning(), ElementQualityChecker::finalize(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FixedPointSolve::FixedPointSolve(), ElementSubdomainIDGenerator::generate(), ParsedGenerateSideset::generate(), MultiAppTransfer::getAppInfo(), FunctorBinnedValuesDivision::getBinIndex(), FEProblemBase::getMaterial(), Terminator::handleMessage(), initStatefulProperties(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::mesh(), NewmarkBeta::NewmarkBeta(), NodalPatchRecovery::NodalPatchRecovery(), Output::Output(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), Executioner::problem(), PropertyReadFile::readData(), TestSourceStepper::rejectStep(), resetQpProperties(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setCoordSystem(), FEProblemBase::sizeZeroes(), TransientMultiApp::solveStep(), TimeDerivativeAux::TimeDerivativeAux(), PiecewiseConstantFromCSV::value(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
mooseWarningNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseWarningNonPrefixed (Args &&... args) const inline inherited
Emits a warning without the prefixing included in mooseWarning().
Definition at line 72 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(_console, std::forward<Args>(args)...);
  }
name()
virtual const std::string & MooseBase::name () const inline virtual inherited
Get the name of the class.
Returns
The name of the class
Reimplemented in MooseVariableBase.
Definition at line 47 of file MooseBase.h.
{ return _name; }
Referenced by HierarchicalGridPartitioner::_do_partition(), AdaptivityAction::act(), AddElementalFieldAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVariableAction::act(), CopyNodalVarsAction::act(), DeprecatedBlockAction::act(), DisplayGhostingAction::act(), MaterialOutputAction::act(), AddDriftDiffusionAction::addADKernels(), FEProblemBase::addAnyRedistributers(), Executioner::addAttributeReporter(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFunctorMaterial(), FunctorMaterial::addFunctorProperty(), FunctorMaterial::addFunctorPropertyByBlocks(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), ADDGKernel::ADDGKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), SubProblem::addPiecewiseByBlockLambdaFunctor(), FEProblemBase::addPostprocessor(), UserObject::addPostprocessorDependencyHelper(), InitialConditionBase::addPostprocessorDependencyHelper(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), UserObject::addUserObjectDependencyHelper(), AuxKernelTempl< ComputeValueType >::addUserObjectDependencyHelper(), InitialConditionBase::addUserObjectDependencyHelper(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), UserObject::addVectorPostprocessorDependencyHelper(), FVFluxKernel::adjustRMGhostLayers(), ADSurfaceCharge::ADSurfaceCharge(), Output::advancedExecuteOn(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayDGKernel::ArrayDGKernel(), ArrayParsedAux::ArrayParsedAux(), AStableDirk4::AStableDirk4(), Function::average(), MultiApp::backup(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), PiecewiseTabularBase::buildFromFile(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkICRestartError(), Damper::checkMinDamping(), Coupleable::checkWritableVar(), CompositeFunction::CompositeFunction(), computeProperties(), FEProblemBase::computeUserObjectByName(), VectorPostprocessorVisualizationAux::computeValue(), MooseBaseParameterInterface::connectControllableParams(), BatchMaterial< Tuple, Output, Input >::construct(), MultiApp::createApp(), AddVariableAction::createInitialConditionAction(), MultiApp::createLocalApp(), MeshGeneratorSystem::createMeshGeneratorOrder(), declareADProperty(), MeshGenerator::declareMeshesForSubByName(), MeshGenerator::declareNullMeshName(), declareProperty(), DOFMapOutput::demangle(), DerivativeSumMaterialTempl< is_ad >::DerivativeSumMaterialTempl(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DomainUserObject::DomainUserObject(), DumpObjectsProblem::dumpObjectHelper(), EconomouDielectricBC::EconomouDielectricBC(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementValueSampler::ElementValueSampler(), MooseMesh::errorIfDistributedMesh(), MooseBaseErrorInterface::errorPrefix(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), PointValue::execute(), RestartableDataReporter::execute(), MultiAppNearestNodeTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), MultiApp::fillPositions(), PointSamplerBase::finalize(), FunctionDT::FunctionDT(), FVFunctionIC::functionName(), FunctionIC::functionName(), FunctorPositions::FunctorPositions(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), BoundaryDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), GeneratedMeshGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MeshGenerator::generateInternal(), InterfaceMaterial::getADMaterialProperty(), Material::getADMaterialProperty(), MultiAppTransfer::getAppInfo(), MultiApp::getBoundingBox(), Control::getControllableParameterByName(), Control::getControllableValue(), Control::getControllableValueByName(), UserObject::getDependObjects(), FEProblemBase::getDistribution(), DistributionInterface::getDistribution(), DistributionInterface::getDistributionByName(), AddZapdosReactions::getElectronImpactKernelName(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), MultiApp::getExecutioner(), FEProblemBase::getExecutor(), OutputWarehouse::getFileNumbers(), FEProblemBase::getFunction(), SubProblem::getFunctor(), AuxKernelTempl< ComputeValueType >::getGenericMaterialProperty(), NodalPatchRecovery::getGenericMaterialProperty(), InterfaceMaterial::getGenericMaterialProperty(), Material::getGenericMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialPropertyByName(), Material::getGenericOptionalMaterialProperty(), getGenericZeroMaterialProperty(), BatchMaterial< Tuple, Output, Input >::getIndex(), AddZapdosReactions::getKernelName(), SolutionUserObject::getLocalVarIndex(), Marker::getMarkerValue(), Material::getMaterial(), FEProblemBase::getMaterial(), Material::getMaterialByName(), AuxKernelTempl< ComputeValueType >::getMaterialProperty(), NodalPatchRecovery::getMaterialProperty(), InterfaceMaterial::getMaterialProperty(), Material::getMaterialProperty(), SubProblem::getMaterialPropertyBlockNames(), SubProblem::getMaterialPropertyBoundaryNames(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOld(), NodalPatchRecovery::getMaterialPropertyOld(), InterfaceMaterial::getMaterialPropertyOld(), Material::getMaterialPropertyOld(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOlder(), NodalPatchRecovery::getMaterialPropertyOlder(), InterfaceMaterial::getMaterialPropertyOlder(), Material::getMaterialPropertyOlder(), MeshGenerator::getMesh(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshesByName(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MultiAppTransfer::getMultiApp(), InterfaceMaterial::getNeighborADMaterialProperty(), InterfaceMaterial::getNeighborMaterialProperty(), InterfaceMaterial::getNeighborMaterialPropertyOld(), InterfaceMaterial::getNeighborMaterialPropertyOlder(), Material::getOptionalADMaterialProperty(), Material::getOptionalMaterialProperty(), Material::getOptionalMaterialPropertyOld(), Material::getOptionalMaterialPropertyOlder(), FEProblemBase::getPositionsObject(), FEProblemBase::getPostprocessorValueByName(), AddReactions::getReactionKernelName(), ReporterData::getReporterInfo(), FEProblemBase::getSampler(), Transient::getTimeStepperName(), ProjectedStatefulMaterialStorageAction::getTypeEnum(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), Terminator::handleMessage(), FEProblemBase::hasFunction(), SubProblem::hasFunctor(), SubProblem::hasFunctorWithType(), AdvancedOutput::hasOutputHelper(), FEProblemBase::hasPostprocessor(), FEProblemBase::hasPostprocessorValueByName(), FEProblemBase::hasUserObject(), AdvancedOutput::init(), FEProblemBase::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), AttribName::initFrom(), NestedDivision::initialize(), SolutionScalarAux::initialSetup(), NodalVariableValue::initialSetup(), MultiAppProjectionTransfer::initialSetup(), SolutionUserObject::initialSetup(), AdvancedOutput::initOutputList(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), initStatefulProperties(), Function::integral(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), MeshGenerator::isChildMeshGenerator(), MeshGenerator::isNullMeshName(), MeshGenerator::isParentMeshGenerator(), LinearCombinationFunction::LinearCombinationFunction(), FEProblemBase::logAdd(), LymberopoulosElectronBC::LymberopoulosElectronBC(), Marker::Marker(), Material::Material(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), Distribution::median(), MemoryUsageReporter::MemoryUsageReporter(), MeshGenerator::meshPropertyPrefix(), MooseVariableInterface< T >::MooseVariableInterface(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), NeumannCircuitVoltageMoles_KV::NeumannCircuitVoltageMoles_KV(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), NodalValueSampler::NodalValueSampler(), MooseBaseParameterInterface::objectErrorPrefix(), MeshGenerator::Comparator::operator()(), DOFMapOutput::output(), ProgressOutput::output(), Output::Output(), AdvancedOutput::outputElementalVariables(), ConsoleUtils::outputExecutionInformation(), AdvancedOutput::outputInput(), AdvancedOutput::outputNodalVariables(), AdvancedOutput::outputPostprocessors(), Exodus::outputPostprocessors(), Nemesis::outputPostprocessors(), TableOutput::outputReporter(), AdvancedOutput::outputReporters(), AdvancedOutput::outputScalarVariables(), AdvancedOutput::outputSystemInformation(), AdvancedOutput::outputVectorPostprocessors(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedODEKernel::ParsedODEKernel(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PointVariableSamplerBase::PointVariableSamplerBase(), MultiApp::readCommandLineArguments(), Receiver::Receiver(), Executor::Result::record(), FEProblemBase::registerRandomInterface(), GlobalParamsAction::remove(), resetQpProperties(), MultiApp::restore(), SakiyamaEnergySecondaryElectronBC::SakiyamaEnergySecondaryElectronBC(), SakiyamaSecondaryElectronBC::SakiyamaSecondaryElectronBC(), ScalarComponentIC::ScalarComponentIC(), SecondaryElectronBC::SecondaryElectronBC(), SecondaryElectronEnergyBC::SecondaryElectronEnergyBC(), MultiApp::setAppOutputFileBase(), MooseMesh::setBoundaryName(), Control::setControllableValue(), Control::setControllableValueByName(), GlobalParamsAction::setDoubleIndexParam(), OutputWarehouse::setFileNumbers(), GlobalParamsAction::setParam(), FEProblemBase::setPostprocessorValueByName(), GlobalParamsAction::setScalarParam(), MooseMesh::setSubdomainName(), GlobalParamsAction::setTripleIndexParam(), Split::setup(), TransientMultiApp::setupApp(), GlobalParamsAction::setVectorParam(), SideCurrent::SideCurrent(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SideValueSampler::SideValueSampler(), TransientMultiApp::solveStep(), UserObject::spatialValue(), StitchedMesh::StitchedMesh(), SubProblem::storeBoundaryDelayedCheckMatProp(), SubProblem::storeBoundaryMatPropName(), SubProblem::storeBoundaryZeroMatProp(), SubProblem::storeSubdomainDelayedCheckMatProp(), SubProblem::storeSubdomainMatPropName(), SubProblem::storeSubdomainZeroMatProp(), subdomainSetup(), TaggingInterface::TaggingInterface(), VectorPostprocessorVisualizationAux::timestepSetup(), MultiAppDofCopyTransfer::transfer(), TransientMultiApp::TransientMultiApp(), MooseBase::typeAndName(), MooseBaseParameterInterface::uniqueParameterName(), UserObject::UserObject(), UserObjectInterface::userObjectName(), MultiAppTransfer::variableIntegrityCheck(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), AdvancedOutput::wantOutput(), Coupleable::writableCoupledValue(), and Coupleable::writableVariable().
numBlocks()
unsigned int BlockRestrictable::numBlocks () const inherited
Return the number of blocks for this object.
Returns
The number of subdomains
Definition at line 199 of file BlockRestrictable.C.
{
  return (unsigned int)_blk_ids.size();
}
Referenced by ElementCentroidPositions::initialize().
numBoundaryIDs()
unsigned int BoundaryRestrictable::numBoundaryIDs () const inherited
Return the number of boundaries for this object.
Returns
The number of boundary ids
Definition at line 192 of file BoundaryRestrictable.C.
{
  return (unsigned int)_bnd_ids.size();
}
Referenced by SidesetInfoVectorPostprocessor::initialize().
objectErrorPrefix()
std::string MooseBaseParameterInterface::objectErrorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for an object.
Definition at line 58 of file MooseBaseParameterInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the class \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseParameterInterface::paramErrorMsg().
paramError()
template<typename... Args> void MooseBaseParameterInterface::paramError (const std::string & param, Args... args) const inherited
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseError - only printing a message using the given args.
Definition at line 233 of file MooseBaseParameterInterface.h.
{
  Moose::show_trace = false;
  std::string msg = paramErrorMsg(param, std::forward<Args>(args)...);
  callMooseErrorRaw(msg, &_moose_base->getMooseApp());
  Moose::show_trace = true;
}
Referenced by HierarchicalGridPartitioner::_do_partition(), SetupDebugAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), ADDGKernel::ADDGKernel(), ReporterPointSource::addPoints(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ADNodalKernel::ADNodalKernel(), ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), AdvectiveFluxAux::AdvectiveFluxAux(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), ArrayBodyForce::ArrayBodyForce(), ArrayDGKernel::ArrayDGKernel(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayDirichletBC::ArrayDirichletBC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), ArrayPenaltyDirichletBC::ArrayPenaltyDirichletBC(), ArrayVacuumBC::ArrayVacuumBC(), BlockDeletionGenerator::BlockDeletionGenerator(), BlockWeightedPartitioner::BlockWeightedPartitioner(), BoundsAuxBase::BoundsAuxBase(), BreakMeshByBlockGenerator::BreakMeshByBlockGenerator(), BuildArrayVariableAux::BuildArrayVariableAux(), PiecewiseTabularBase::buildFromFile(), CartesianGridDivision::CartesianGridDivision(), UserObjectInterface::castUserObject(), checkComponent(), MeshGenerator::checkGetMesh(), PostprocessorInterface::checkParam(), Coupleable::checkVar(), MultiAppTransfer::checkVariable(), CircularBoundaryCorrectionGenerator::CircularBoundaryCorrectionGenerator(), CircularBoundaryCorrectionGenerator::circularCenterCalculator(), MultiAppGeneralFieldTransfer::closestToPosition(), CombinerGenerator::CombinerGenerator(), CompositionDT::CompositionDT(), ConcentricCircleMeshGenerator::ConcentricCircleMeshGenerator(), LibtorchNeuralNetControl::conditionalParameterError(), ConstantVectorPostprocessor::ConstantVectorPostprocessor(), ContainsPointAux::ContainsPointAux(), CopyValueAux::CopyValueAux(), Coupleable::Coupleable(), CoupledForceTempl< is_ad >::CoupledForceTempl(), CoupledValueFunctionMaterialTempl< is_ad >::CoupledValueFunctionMaterialTempl(), MultiApp::createApp(), MeshGeneratorSystem::createMeshGenerator(), CylindricalGridDivision::CylindricalGridDivision(), ConstantReporter::declareConstantReporterValues(), AccumulateReporter::declareLateValues(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DGLowerDKernel::DGLowerDKernel(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementLengthAux::ElementLengthAux(), ElementLpNormAux::ElementLpNormAux(), ElementValueSampler::ElementValueSampler(), ReporterPointSource::errorCheck(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), ExtraElementIDAux::ExtraElementIDAux(), ExtraElementIntegerDivision::ExtraElementIntegerDivision(), FEProblemSolve::FEProblemSolve(), FillBetweenCurvesGenerator::FillBetweenCurvesGenerator(), FillBetweenSidesetsGenerator::FillBetweenSidesetsGenerator(), ReporterPointSource::fillPoint(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), InternalSideIndicator::finalize(), FixedPointSolve::FixedPointSolve(), ForcingFunctionAux::ForcingFunctionAux(), FunctionArrayAux::FunctionArrayAux(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorAux::FunctorAux(), FunctorBinnedValuesDivision::FunctorBinnedValuesDivision(), FunctorElementalGradientAuxTempl< is_ad >::FunctorElementalGradientAuxTempl(), FunctorPositions::FunctorPositions(), FunctorVectorElementalAuxTempl< is_ad >::FunctorVectorElementalAuxTempl(), FVFluxBC::FVFluxBC(), FVInterfaceKernel::FVInterfaceKernel(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), FVTwoVarContinuityConstraint::FVTwoVarContinuityConstraint(), AdvancedExtruderGenerator::generate(), BlockDeletionGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundaryDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), BreakMeshByBlockGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), CombinerGenerator::generate(), ExplodeMeshGenerator::generate(), ExtraNodesetGenerator::generate(), FillBetweenCurvesGenerator::generate(), FillBetweenSidesetsGenerator::generate(), GeneratedMeshGenerator::generate(), MeshCollectionGenerator::generate(), MeshExtruderGenerator::generate(), ParsedCurveGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), PropertyReadFile::getBlockData(), PropertyReadFile::getData(), Sampler::getGlobalSamples(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), Sampler::getLocalSamples(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), Sampler::getNextLocalRow(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectName(), HFEMDirichletBC::HFEMDirichletBC(), MultiApp::init(), BlockWeightedPartitioner::initialize(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), PiecewiseConstantFromCSV::initialSetup(), LibtorchControlValuePostprocessor::initialSetup(), ReferenceResidualProblem::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), HistogramVectorPostprocessor::initialSetup(), AddMetaDataGenerator::inputChecker(), IntegratedBC::IntegratedBC(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceValueUserObjectAux::InterfaceValueUserObjectAux(), InterpolatedStatefulMaterialTempl< T >::InterpolatedStatefulMaterialTempl(), InversePowerMethod::InversePowerMethod(), IterationAdaptiveDT::IterationAdaptiveDT(), MultiApp::keepSolutionDuringRestore(), Kernel::Kernel(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LinearCombinationFunction::LinearCombinationFunction(), LowerDIntegratedBC::LowerDIntegratedBC(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), MaterialADConverterTempl< T >::MaterialADConverterTempl(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), PatternedMeshGenerator::mergeSubdomainNameMaps(), MeshCollectionGenerator::MeshCollectionGenerator(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshDivisionAux::MeshDivisionAux(), MeshGenerator::MeshGenerator(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarNodalAuxKernelTempl< ComputeValueType >::MortarNodalAuxKernelTempl(), MultiApp::moveApp(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), NestedDivision::NestedDivision(), NodalBC::NodalBC(), NodalEqualValueConstraint::NodalEqualValueConstraint(), NodalKernel::NodalKernel(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), NodalValueSampler::NodalValueSampler(), Output::Output(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), PatchMeshGenerator::PatchMeshGenerator(), PatternedMeshGenerator::PatternedMeshGenerator(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), PeriodicSegmentalConstraint::PeriodicSegmentalConstraint(), PIDTransientControl::PIDTransientControl(), PlaneDeletionGenerator::PlaneDeletionGenerator(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), PolyLineMeshGenerator::PolyLineMeshGenerator(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), LibmeshPartitioner::prepareBlocksForSubdomainPartitioner(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), PropertyReadFile::PropertyReadFile(), RandomIC::RandomIC(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readXda(), ReferenceResidualProblem::ReferenceResidualProblem(), RefineBlockGenerator::RefineBlockGenerator(), RefineSidesetGenerator::RefineSidesetGenerator(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setPartitioner(), TimeSequenceStepperBase::setupSequence(), SingleRankPartitioner::SingleRankPartitioner(), SphericalGridDivision::SphericalGridDivision(), SymmetryTransformGenerator::SymmetryTransformGenerator(), Terminator::Terminator(), TimeDerivativeAux::TimeDerivativeAux(), Transfer::Transfer(), TransformGenerator::TransformGenerator(), TransientMultiApp::TransientMultiApp(), ParsedCurveGenerator::tSectionSpaceDefiner(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), UserObject::UserObject(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), VolumeAux::VolumeAux(), XYDelaunayGenerator::XYDelaunayGenerator(), and XYMeshLineCutter::XYMeshLineCutter().
paramErrorMsg()
template<typename... Args> std::string MooseBaseParameterInterface::paramErrorMsg (const std::string & param, Args... args) const inline private inherited
Definition at line 171 of file MooseBaseParameterInterface.h.
  {
    auto param_prefix = paramErrorPrefix(_pars, param);
    // With no input location information, append object info (name + type)
    const std::string object_prefix =
        _pars.inputLocation(param).empty() ? objectErrorPrefix("parameter error") : "";
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    // Wrap error message to a separate line from param_prefix if it is about to
    // blow past 100 chars.  But only wrap if the param_prefix is long enough (12
    // chars) for the wrap to buy us much extra length. We don't check object_prefix
    // here because it will go before the parameter error
    if ((param_prefix.size() > 12 && msg.size() + param_prefix.size() > 99) ||
        msg.find("\n") != std::string::npos)
    {
      if (param_prefix.size() > 0 && param_prefix[param_prefix.size() - 1] != ':')
        param_prefix += ":";
      return object_prefix + param_prefix + "\n    " + MooseUtils::replaceAll(msg, "\n", "\n    ");
    }
    return object_prefix + param_prefix + " " + msg;
  }
Referenced by MooseBaseParameterInterface::paramError(), MooseBaseParameterInterface::paramInfo(), and MooseBaseParameterInterface::paramWarning().
parameters()
const InputParameters & MooseBaseParameterInterface::parameters () const inline inherited
Get the parameters of the object.
Returns
The parameters of the object
Definition at line 53 of file MooseBaseParameterInterface.h.
{ return _pars; }
Referenced by SetupDebugAction::act(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), FEProblemBase::addPostprocessor(), FEProblemBase::addPredictor(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), AdvancedOutput::AdvancedOutput(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), Moose::assemble_matrix(), AuxScalarKernel::AuxScalarKernel(), BoundsAuxBase::BoundsAuxBase(), MooseMesh::buildTypedMesh(), UserObjectInterface::castUserObject(), PostprocessorInterface::checkParam(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), Moose::compute_bounds(), Moose::compute_jacobian(), Moose::compute_nearnullspace(), Moose::compute_nullspace(), Moose::compute_postcheck(), Moose::compute_transpose_nullspace(), LibtorchNeuralNetControl::conditionalParameterError(), Console::Console(), MultiApp::createApp(), Postprocessor::declareValue(), DumpObjectsProblem::deduceNecessaryParameters(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), DumpObjectsProblem::dumpObjectHelper(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElectronsFromIonization::ElectronsFromIonization(), Executor::Executor(), Exodus::Exodus(), FEProblem::FEProblem(), FEProblemBase::FEProblemBase(), FixedPointSolve::FixedPointSolve(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GapValueAux::GapValueAux(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), MooseBaseParameterInterface::getCheckedPointerParam(), ExecutorInterface::getExecutor(), Material::getMaterial(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), UserObjectInterface::getUserObjectName(), VectorPostprocessorInterface::getVectorPostprocessorName(), GhostingUserObject::GhostingUserObject(), HphiRadialInterface::HphiRadialInterface(), AttribSystem::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), FullSolveMultiApp::initialSetup(), FEProblemBase::initNullSpaceVectors(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), isValid(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseAppCoordTransform::MooseAppCoordTransform(), MooseVariableInterface< T >::MooseVariableInterface(), MultiApp::MultiApp(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodeFaceConstraint::NodeFaceConstraint(), PatchMeshGenerator::PatchMeshGenerator(), PenetrationAux::PenetrationAux(), PicardSolve::PicardSolve(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), ProjectedStatefulMaterialStorageAction::processProperty(), MultiAppProjectionTransfer::projectSolution(), PropertyReadFile::PropertyReadFile(), PseudoTimestep::PseudoTimestep(), RandomIC::RandomIC(), InputParameterWarehouse::removeInputParameters(), OutputWarehouse::resetFileBase(), MooseAppCoordTransform::setCoordinateSystem(), FEProblemBase::setInputParametersFEProblem(), FEProblem::setInputParametersFEProblem(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SteffensenSolve::SteffensenSolve(), DumpObjectsProblem::stringifyParameters(), TaggingInterface::TaggingInterface(), Transfer::Transfer(), Transient::Transient(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
paramInfo()
template<typename... Args> void MooseBaseParameterInterface::paramInfo (const std::string & param, Args... args) const inherited
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseInfo - only printing a message using the given args.
Definition at line 250 of file MooseBaseParameterInterface.h.
{
  mooseInfo(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by TransientMultiApp::TransientMultiApp().
paramWarning()
template<typename... Args> void MooseBaseParameterInterface::paramWarning (const std::string & param, Args... args) const inherited
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseWarning - only printing a message using the given args.
Definition at line 243 of file MooseBaseParameterInterface.h.
{
  mooseWarning(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by MultiAppNearestNodeTransfer::execute(), FEProblemSolve::FEProblemSolve(), PlaneIDMeshGenerator::generate(), UniqueExtraIDMeshGenerator::generate(), Terminator::initialSetup(), and MooseMesh::MooseMesh().
possiblyCheckHasVectorPostprocessor()
void VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor (const std::string & param_name, const std::string & vector_name) const private inherited
Helpers for "possibly" checking if a vpp exists.
This is only able to check for existance after all vpps have been added (after the task creating them has been called). If called before said task, this will do nothing, hence the "possibly". This allows us to have errors reported directly by the object requesting the vpp instead of through a system with less context.
Definition at line 228 of file VectorPostprocessorInterface.C.
{
  // Can't do checking if vpps have not been added
  if (!vectorPostprocessorsAdded())
    return;
  if (!hasVectorPostprocessor(param_name))
    _vpi_moose_object.paramError(param_name,
                                 "A VectorPostprocessor with the name \"",
                                 getVectorPostprocessorName(param_name),
                                 "\" was not found.");
  if (!hasVectorPostprocessor(param_name, vector_name))
    _vpi_moose_object.paramError(param_name,
                                 "The VectorPostprocessor \"",
                                 getVectorPostprocessorName(param_name),
                                 "\" does not have a vector named \"",
                                 vector_name,
                                 "\".");
}
Referenced by VectorPostprocessorInterface::getScatterVectorPostprocessorValue(), VectorPostprocessorInterface::getScatterVectorPostprocessorValueOld(), VectorPostprocessorInterface::getVectorPostprocessorValue(), and VectorPostprocessorInterface::getVectorPostprocessorValueOld().
possiblyCheckHasVectorPostprocessorByName()
void VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName (const VectorPostprocessorName & name, const std::string & vector_name) const private inherited
Definition at line 250 of file VectorPostprocessorInterface.C.
{
  // Can't do checking if vpps have not been added
  if (!vectorPostprocessorsAdded())
    return;
  if (!hasVectorPostprocessorByName(name))
    _vpi_moose_object.mooseError(
        "A VectorPostprocessor with the name \"", name, "\" was not found.");
  if (!hasVectorPostprocessorByName(name, vector_name))
    _vpi_moose_object.mooseError("The VectorPostprocessor \"",
                                 name,
                                 "\" does not have a vector named \"",
                                 vector_name,
                                 "\".");
}
Referenced by VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), and VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper().
postprocessorsAdded()
bool PostprocessorInterface::postprocessorsAdded () const private inherited
Returns
True if all pps have been added (the task associated with adding them is complete)
Definition at line 264 of file PostprocessorInterface.C.
{
  return _ppi_feproblem.getMooseApp().actionWarehouse().isTaskComplete("add_postprocessor");
}
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), and PostprocessorInterface::hasPostprocessorByName().
qRule()
virtual const QBase & MaterialBase::qRule () const protected pure virtual
Implemented in InterfaceMaterial, and Material.
Referenced by resetProperties().
registerInvalidSolutionInternal()
InvalidSolutionID SolutionInvalidInterface::registerInvalidSolutionInternal (const std::string & message) const protected inherited
Definition at line 35 of file SolutionInvalidInterface.C.
{
  return moose::internal::getSolutionInvalidityRegistry().registerInvalidity(
      _si_moose_object.type(), message);
}
registerPropName()
void MaterialBase::registerPropName (const std::string & prop_name, bool is_get, const unsigned int state) protected
Small helper function to call store{Subdomain,Boundary}MatPropName.
Definition at line 149 of file MaterialBase.C.
{
  if (!is_get)
  {
    const auto property_id = materialData().getPropertyId(prop_name);
    _supplied_props.insert(prop_name);
    _supplied_prop_ids.insert(property_id);
    // Store the minimum state declared
    auto find_min_state = _props_to_min_states.find(property_id);
    if (find_min_state == _props_to_min_states.end())
      _props_to_min_states.emplace(property_id, state);
    else
      find_min_state->second = std::min(find_min_state->second, state);
    // Store material properties for block ids
    for (const auto & block_id : blockIDs())
      _fe_problem.storeSubdomainMatPropName(block_id, prop_name);
    // Store material properties for the boundary ids
    for (const auto & boundary_id : boundaryIDs())
      _fe_problem.storeBoundaryMatPropName(boundary_id, prop_name);
  }
  if (state > 0)
    _has_stateful_property = true;
}
Referenced by declareGenericPropertyByName(), InterfaceMaterial::getGenericMaterialPropertyByName(), Material::getGenericMaterialPropertyByName(), InterfaceMaterial::getGenericNeighborMaterialPropertyByName(), and getGenericZeroMaterialPropertyByName().
registerRestartableDataOnApp()
RestartableDataValue & Restartable::registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const private inherited
Helper function for actually registering the restartable data.
Definition at line 51 of file Restartable.C.
{
  return _restartable_app.registerRestartableData(
      std::move(data), tid, _restartable_read_only, _metaname);
}
Referenced by Restartable::declareRestartableDataHelper().
registerRestartableNameWithFilterOnApp()
void Restartable::registerRestartableNameWithFilterOnApp (const std::string & name, Moose::RESTARTABLE_FILTER filter) private inherited
Helper function for actually registering the restartable data.
Definition at line 59 of file Restartable.C.
{
  _restartable_app.registerRestartableNameWithFilter(name, filter);
}
Referenced by Restartable::declareRecoverableData().
requiresGeometricSearch()
bool GeometricSearchInterface::requiresGeometricSearch () const inline inherited
Whether any of this interface's methods have been called, e.g.
whether the object that this interface is for requires geometric search data
Definition at line 65 of file GeometricSearchInterface.h.
{ return _requires_geometric_search; }
resetProperties()
void MaterialBase::resetProperties () virtual
Resets the properties at each quadrature point (see resetQpProperties), only called if 'compute = false'.
This method is called internally by MOOSE, you probably don't want to mess with this.
Definition at line 203 of file MaterialBase.C.
{
  for (_qp = 0; _qp < qRule().n_points(); ++_qp)
    resetQpProperties();
}
resetQpProperties()
void MaterialBase::resetQpProperties () protected virtual
Resets the properties prior to calculation of traditional materials (only if 'compute = false').
This method must be overridden in your class. This is called just prior to the re-calculation of traditional material properties to ensure that the properties are in a proper state for calculation.
Reimplemented in DerivativeParsedMaterialTempl< is_ad >.
Definition at line 210 of file MaterialBase.C.
{
  if (!_compute)
    mooseDoOnce(mooseWarning("You disabled the computation of this (",
                             name(),
                             ") material by MOOSE, but have not overridden the 'resetQpProperties' "
                             "method, this can lead to unintended values being set for material "
                             "property values."));
}
Referenced by resetProperties().
residualSetup()
void SetupInterface::residualSetup () virtual inherited
Gets called just before the residual is computed and before this object is asked to do its job.
Reimplemented in NodeFaceConstraint, Function, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 55 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::residualSetup(), ComputeFVFluxResidualThread< RangeType >::setup(), and ComputeFVFluxRJThread< RangeType >::setup().
restartableName()
std::string Restartable::restartableName (const std::string & data_name) const protected inherited
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
This should only be used in this interface and in testing.
Definition at line 66 of file Restartable.C.
{
  return _restartable_system_name + "/" + _restartable_name + "/" + data_name;
}
Referenced by Restartable::declareRecoverableData(), and Restartable::declareRestartableDataHelper().
restricted()
bool BoundaryRestrictable::restricted (const std::set< BoundaryID > & ids) static inherited
Helper for determining if the object is boundary restricted.
This is needed for the MaterialPropertyInterface.
Definition at line 204 of file BoundaryRestrictable.C.
{
  return ids.find(Moose::ANY_BOUNDARY_ID) == ids.end();
}
Referenced by BoundaryRestrictable::boundaryRestricted(), and moose::internal::boundaryRestricted().
setFaceInfo()
void MaterialBase::setFaceInfo (const FaceInfo & fi) inline
Definition at line 233 of file MaterialBase.h.
{ _face_info = &fi; }
setRandomDataPointer()
void RandomInterface::setRandomDataPointer (RandomData * random_data) inherited
Definition at line 54 of file RandomInterface.C.
{
  _random_data = random_data;
  _generator = &_random_data->getGenerator();
}
Referenced by FEProblemBase::registerRandomInterface().
setRandomResetFrequency()
void RandomInterface::setRandomResetFrequency (ExecFlagType exec_flag) inherited
This interface should be called from a derived class to enable random number generation in this object.
Definition at line 47 of file RandomInterface.C.
{
  _reset_on = exec_flag;
  _ri_problem.registerRandomInterface(*this, _ri_name);
}
sort()
template<typename T > void DependencyResolverInterface::sort (typename std::vector< T > & vector) static inherited
Given a vector, sort using the getRequested/SuppliedItems sets.
Definition at line 64 of file DependencyResolverInterface.h.
{
  sortDFS(vector);
}
Referenced by TheWarehouse::prepare().
sortDFS()
template<typename T > void DependencyResolverInterface::sortDFS (typename std::vector< T > & vector) static inherited
Given a vector, sort using the depth-first search.
Class that represents the dependency as a graph
Definition at line 71 of file DependencyResolverInterface.h.
{
  if (vector.size() <= 1)
    return;
  DependencyResolver<T> graph;
  // Map of suppliers: what is supplied -> by what object
  std::multimap<std::string, T> suppliers_map;
  for (auto & v : vector)
  {
    for (const auto & supplied_item : v->getSuppliedItems())
    {
      suppliers_map.emplace(supplied_item, v);
      graph.addNode(v);
    }
  }
  // build the dependency graph
  for (auto & v : vector)
  {
    for (const auto & requested_item : v->getRequestedItems())
    {
      const auto & [begin_it, end_it] = suppliers_map.equal_range(requested_item);
      if (begin_it == end_it)
        graph.addNode(v);
      else
        for (const auto & [supplier_name, supplier_object] : as_range(begin_it, end_it))
        {
          libmesh_ignore(supplier_name);
          if (supplier_object == v)
            // We allow an object to have a circular dependency within itself; e.g. we choose to
            // trust a developer knows what they are doing within a single object
            continue;
          graph.addEdge(supplier_object, v);
        }
    }
  }
  vector = graph.dfs();
}
Referenced by DependencyResolverInterface::sort().
subdomainSetup()
void MaterialBase::subdomainSetup () override virtual
Subdomain setup evaluating material properties when required.
Reimplemented from SetupInterface.
Reimplemented in Material.
Definition at line 186 of file MaterialBase.C.
{
  mooseError("MaterialBase::subdomainSetup in Material'", name(), "' needs to be implemented");
}
timestepSetup()
void SetupInterface::timestepSetup () virtual inherited
Gets called at the beginning of the timestep before this object is asked to do its job.
Reimplemented in VectorPostprocessorVisualizationAux, EqualValueEmbeddedConstraint, Function, Console, JSONOutput, Positions, MemoryUsage, NumNonlinearIterations, Times, SolutionUserObject, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, MooseVariableFV< T >, and VectorMemoryUsage.
Definition at line 45 of file SetupInterface.C.
{
}
Referenced by JSONOutput::timestepSetup(), and MooseVariableField< OutputType >::timestepSetup().
type()
const std::string & MooseBase::type () const inline inherited
Get the type of this class.
Returns
the name of the type of this class
Definition at line 41 of file MooseBase.h.
{ return _type; }
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), CreateProblemDefaultAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetupDebugAction::act(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::addDistribution(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addObject(), DistributedRectilinearMeshGenerator::addPoint(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), PhysicsBasedPreconditioner::addSystem(), FEProblemBase::addTimeIntegrator(), SubProblem::addVectorTag(), DisplacedProblem::addVectorTag(), FEProblemBase::advanceMultiApps(), FEProblemBase::backupMultiApps(), BoundaryPreservedMarker::BoundaryPreservedMarker(), DistributedRectilinearMeshGenerator::buildCube(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildPRefinementAndCoarseningMaps(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), FEProblemBase::computeAuxiliaryKernels(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpJacobian(), HFEMDirichletBC::computeLowerDQpJacobian(), ArrayHFEMDiffusion::computeLowerDQpJacobian(), HFEMDiffusion::computeLowerDQpJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), FEProblemBase::computeMultiAppsDT(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), DGCoupledAdvection::computeOffDiagJacobianHelper(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ScalarKernel::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueBoundaryConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), LinearNodalConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), DGConvection::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), InterfaceDiffusion::computeQpJacobian(), InterfaceReaction::computeQpJacobian(), DGCoupledAdvection::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), DGFunctionTemperatureAdvection::computeQpJacobian(), DGTemperatureAdvection::computeQpJacobian(), InterTemperatureAdvection::computeQpJacobian(), CoupledTiedValueConstraint::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), HFEMTestJump::computeQpOffDiagJacobian(), HFEMTrialJump::computeQpOffDiagJacobian(), DGCoupledAdvection::computeQpOffDiagJacobian(), ScalarKernel::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), EqualValueBoundaryConstraint::computeQpResidual(), EqualValueEmbeddedConstraint::computeQpResidual(), LinearNodalConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), DGConvection::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), DGEFieldAdvection::computeQpResidual(), HphiRadialInterface::computeQpResidual(), InterfaceAdvection::computeQpResidual(), InterfaceLogDiffusionElectrons::computeQpResidual(), PotentialSurfaceCharge::computeQpResidual(), ADDGAdvection::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), HFEMDiffusion::computeQpResidual(), HFEMTestJump::computeQpResidual(), HFEMTrialJump::computeQpResidual(), InterfaceDiffusion::computeQpResidual(), InterfaceReaction::computeQpResidual(), DGCoupledAdvection::computeQpResidual(), DGFunctionConvection::computeQpResidual(), DGFunctionTemperatureAdvection::computeQpResidual(), DGTemperatureAdvection::computeQpResidual(), InterTemperatureAdvection::computeQpResidual(), ArrayDGDiffusion::computeQpResidual(), ArrayHFEMDiffusion::computeQpResidual(), FEProblemBase::computeUserObjectByName(), FEProblemBase::computeUserObjects(), FEProblemBase::computeUserObjectsInternal(), BatchMaterial< Tuple, Output, Input >::construct(), DisplacedProblem::createQRules(), FEProblemBase::createQRules(), MeshGenerator::declareMeshProperty(), DumpObjectsProblem::deduceNecessaryParameters(), DumpObjectsProblem::dumpObjectHelper(), FEProblemBase::duplicateVariableCheck(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), MooseBaseErrorInterface::errorPrefix(), AB2PredictorCorrector::estimateTimeError(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finishMultiAppStep(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), ElementSubdomainIDGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), PatternedMeshGenerator::generate(), MeshGenerator::generateInternal(), MultiAppTransfer::getAppInfo(), TransfiniteMeshGenerator::getEdge(), ElementGenerator::getElemType(), FEProblemBase::getMaterial(), FEProblemBase::getMaterialData(), MaterialOutputAction::getParams(), ReporterData::getReporterInfo(), Transient::getTimeIntegratorName(), FEProblemBase::getTransfers(), SubProblem::getVectorTags(), DisplacedProblem::getVectorTags(), CommonOutputAction::hasConsole(), FEProblemBase::hasMultiApps(), AdvancedOutput::hasOutput(), FEProblemBase::incrementMultiAppTStep(), AdvancedOutput::initAvailableLists(), FunctorPositions::initialize(), FunctorTimes::initialize(), MultiAppConservativeTransfer::initialSetup(), ArrayDGDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), RelationshipManager::isType(), FEProblemBase::logAdd(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), SubProblem::numVectorTags(), DisplacedProblem::numVectorTags(), MooseBaseParameterInterface::objectErrorPrefix(), AdvancedOutput::output(), Console::output(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), ProjectedStatefulMaterialStorageAction::processProperty(), SolutionInvalidInterface::registerInvalidSolutionInternal(), FEProblemBase::restoreMultiApps(), MeshRepairGenerator::separateSubdomainsByElementType(), FEProblemBase::setCoupling(), MooseBase::typeAndName(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), DisplacedProblem::updateGeomSearch(), FEProblemBase::updateGeomSearch(), UserObjectInterface::userObjectType(), and AdvancedOutput::wantOutput().
typeAndName()
std::string MooseBase::typeAndName () const inline inherited
Get the class's combined type and name; useful in error handling.
Returns
The type and name of this class in the form '<type()> "<name()>"'.
Definition at line 53 of file MooseBase.h.
  {
    return type() + std::string(" \"") + name() + std::string("\"");
  }
Referenced by ReporterContext< T >::finalize(), and ReporterData::getReporterInfo().
uniqueName()
MooseObjectName MooseBaseParameterInterface::uniqueName () const inline inherited
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
Definition at line 58 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectName(_pars.get<std::string>("_unique_name"));
  }
Referenced by MooseBaseParameterInterface::connectControllableParams(), and Action::uniqueActionName().
uniqueParameterName()
MooseObjectParameterName MooseBaseParameterInterface::uniqueParameterName (const std::string & parameter_name) const inline inherited
The unique parameter name of a valid parameter of this object for accessing parameter controls.
Definition at line 43 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectParameterName(
        _pars.get<std::string>("_moose_base"), _moose_base->name(), parameter_name);
  }
userObjectName()
const std::string & UserObjectInterface::userObjectName (const UserObject & uo) const private inherited
Gets a UserObject's name; avoids including UserObject.h in the UserObjectInterface.
Definition at line 113 of file UserObjectInterface.C.
{
  return uo.name();
}
Referenced by UserObjectInterface::castUserObject().
userObjectType()
const std::string & UserObjectInterface::userObjectType (const UserObject & uo) const private inherited
Gets a UserObject's type; avoids including UserObject.h in the UserObjectInterface.
Definition at line 107 of file UserObjectInterface.C.
{
  return uo.type();
}
Referenced by UserObjectInterface::castUserObject().
validateExecutionerType()
void ScalarCoupleable::validateExecutionerType (const std::string & name, const std::string & fn_name) const private inherited
Checks to make sure that the current Executioner has set "_is_transient" when old/older values are coupled in.
Parameters
name the name of the variable
fn_name The name of the function that called this method - used in the error message
Definition at line 329 of file ScalarCoupleable.C.
{
  if (!_sc_fe_problem.isTransient())
    mooseError(_sc_name,
               ": Calling '",
               fn_name,
               "' on variable \"",
               name,
               "\" when using a \"Steady\" executioner is not allowed. This value is available "
               "only in transient simulations.");
}
Referenced by ScalarCoupleable::coupledScalarDot(), ScalarCoupleable::coupledScalarDotDot(), ScalarCoupleable::coupledScalarDotDotDu(), ScalarCoupleable::coupledScalarDotDotOld(), ScalarCoupleable::coupledScalarDotDu(), ScalarCoupleable::coupledScalarDotOld(), ScalarCoupleable::coupledScalarValueOld(), and ScalarCoupleable::coupledScalarValueOlder().
validParams()
InputParameters MaterialBase::validParams () static
Definition at line 21 of file MaterialBase.C.
{
  InputParameters params = MooseObject::validParams();
  params += BlockRestrictable::validParams();
  params += BoundaryRestrictable::validParams();
  params += TransientInterface::validParams();
  params += RandomInterface::validParams();
  params += ADFunctorInterface::validParams();
  params.addParam<bool>("use_displaced_mesh",
                        false,
                        "Whether or not this object should use the "
                        "displaced mesh for computation.  Note that "
                        "in the case this is true but no "
                        "displacements are provided in the Mesh block "
                        "the undisplaced mesh will still be used.");
  params.addParam<bool>("compute",
                        true,
                        "When false, MOOSE will not call compute methods on this material. "
                        "The user must call computeProperties() after retrieving the MaterialBase "
                        "via MaterialBasePropertyInterface::getMaterialBase(). "
                        "Non-computed MaterialBases are not sorted for dependencies.");
  params.addPrivateParam<bool>("_neighbor", false);
  params.addPrivateParam<bool>("_interface", false);
  // Outputs
  params += OutputInterface::validParams();
  params.set<std::vector<OutputName>>("outputs") = {"none"};
  params.addParam<std::vector<std::string>>(
      "output_properties",
      {},
      "List of material properties, from this material, to output (outputs "
      "must also be defined to an output type)");
  params.addParam<MaterialPropertyName>(
      "declare_suffix",
      "",
      "An optional suffix parameter that can be appended to any declared properties. The suffix "
      "will be prepended with a '_' character.");
  // Allow Material objects to be enabled/disabled by Control objects
  params.declareControllable("enable");
  params.addParamNamesToGroup("outputs output_properties", "Outputs");
  params.addParamNamesToGroup("use_displaced_mesh", "Advanced");
  params.registerBase("MaterialBase");
  return params;
}
Referenced by InterfaceMaterial::validParams(), and Material::validParams().
vectorPostprocessorsAdded()
bool VectorPostprocessorInterface::vectorPostprocessorsAdded () const private inherited
Returns
True if all vpps have been added (the task associated with adding them is complete)
Definition at line 306 of file VectorPostprocessorInterface.C.
{
  return _vpi_feproblem.getMooseApp().actionWarehouse().isTaskComplete("add_vector_postprocessor");
}
Referenced by VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), and VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName().
Member Data Documentation
_action_factory
ActionFactory& MooseBaseParameterInterface::_action_factory protected inherited
Builds Actions.
Definition at line 164 of file MooseBaseParameterInterface.h.
Referenced by CommonOutputAction::create(), AddVariableAction::createInitialConditionAction(), AddSpecies::createInitialConditions(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
_app
MooseApp& MooseBase::_app protected inherited
The MOOSE application this is associated with.
Definition at line 60 of file MooseBase.h.
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), MeshGenerator::addChildMeshGenerator(), FEProblemBase::addMaterialHelper(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addOutput(), MeshGenerator::addParentMeshGenerator(), FVFluxKernel::adjustRMGhostLayers(), FEProblemBase::allowOutput(), AStableDirk4::AStableDirk4(), FileMesh::buildMesh(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), MeshGenerator::checkGetMesh(), FEProblemBase::checkICRestartError(), FEProblemBase::checkNonlinearConvergence(), OversampleOutput::cloneMesh(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), Console::Console(), TimeStepper::constrainStep(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::createLocalApp(), FEProblemBase::customSetup(), MeshGenerator::declareMeshProperty(), MeshGenerator::declareNullMeshName(), MooseMesh::determineUseDistributedMesh(), DumpObjectsProblem::dumpObjectHelper(), DumpObjectsProblem::dumpVariableHelper(), EigenExecutionerBase::EigenExecutionerBase(), EigenKernel::EigenKernel(), PIDTransientControl::execute(), Eigenvalue::execute(), InversePowerMethod::execute(), NonlinearEigen::execute(), Steady::execute(), Transient::execute(), PseudoTimestep::execute(), IterationInfo::execute(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FileOutput::FileOutput(), ChangeOverFixedPointPostprocessor::finalize(), RadialAverage::finalize(), FixedPointSolve::FixedPointSolve(), FEProblemBase::forceOutput(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), SideSetsFromNormalsGenerator::generate(), MeshGenerator::generateInternal(), FEProblemBase::getExecutor(), MeshGenerator::getMeshByName(), NumFixedPointIterations::getValue(), NumRelationshipManagers::getValue(), GhostingUserObject::GhostingUserObject(), MooseMesh::init(), InversePowerMethod::init(), NonlinearEigen::init(), Transient::init(), FEProblemBase::init(), TimePeriod::initialSetup(), Console::initialSetup(), AdvancedOutput::initOutputList(), FEProblemBase::initPetscOutput(), EigenProblem::initPetscOutput(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MeshGenerator::MeshGenerator(), EigenExecutionerBase::normalizeSolution(), NumFailedTimeSteps::NumFailedTimeSteps(), AugmentSparsityOnInterface::operator()(), Checkpoint::output(), Exodus::output(), Nemesis::output(), PerfGraphOutput::output(), Tecplot::output(), MortarNodalGeometryOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Exodus::outputEmptyTimestep(), Console::outputInput(), Exodus::outputInput(), Exodus::outputNodalVariables(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), Console::outputSystemInformation(), JSONOutput::outputSystemInformation(), MultiApp::parentOutputPositionChanged(), PIDTransientControl::PIDTransientControl(), Transient::preExecute(), Eigenvalue::prepareSolverOptions(), FEProblemBase::projectSolution(), MultiApp::setAppOutputFileBase(), FileOutput::setFileBaseInternal(), MeshGenerator::setMeshProperty(), MeshGenerator::setMeshPropertyHelper(), FEProblemBase::setRestartFile(), TransientMultiApp::setupApp(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SolutionInvalidityReporter::SolutionInvalidityReporter(), FEProblemBase::solve(), EigenProblem::solve(), PetscOutput::solveSetup(), TransientMultiApp::solveStep(), FEProblemBase::subdomainSetup(), FEProblemBase::theWarehouse(), TimeExtremeValue::TimeExtremeValue(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), Transient::Transient(), FEProblemBase::updateMortarMesh(), Console::write(), and FEProblemBase::~FEProblemBase().
_assembly
Assembly& MaterialBase::_assembly protected
Definition at line 284 of file MaterialBase.h.
_blk_dim
unsigned int BlockRestrictable::_blk_dim private inherited
Largest mesh dimension of the elements in the blocks for this object.
Definition at line 259 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blocksMaxDimension(), and BlockRestrictable::initializeBlockRestrictable().
_blk_dual_restrictable
const bool BlockRestrictable::_blk_dual_restrictable private inherited
Flag for allowing dual restriction.
Definition at line 238 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_blk_feproblem
FEProblemBase* BlockRestrictable::_blk_feproblem private inherited
Pointer to FEProblemBase.
Definition at line 241 of file BlockRestrictable.h.
Referenced by BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), and BlockRestrictable::initializeBlockRestrictable().
_blk_ids
std::set<SubdomainID> BlockRestrictable::_blk_ids private inherited
Set of block ids supplied by the user via the input file (for error checking)
Definition at line 229 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blockIDs(), BlockRestrictable::blockRestricted(), BlockRestrictable::checkVariable(), BlockRestrictable::hasBlocks(), BlockRestrictable::initializeBlockRestrictable(), BlockRestrictable::isBlockSubset(), and BlockRestrictable::numBlocks().
_blk_material_data
const MaterialData* BlockRestrictable::_blk_material_data protected inherited
Pointer to the MaterialData class for this object.
Definition at line 207 of file BlockRestrictable.h.
Referenced by BlockRestrictable::hasBlockMaterialProperty(), and BlockRestrictable::initializeBlockRestrictable().
_blk_mesh
MooseMesh* BlockRestrictable::_blk_mesh private inherited
Pointer to Mesh.
Definition at line 244 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blockIDs(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlocks(), BlockRestrictable::initializeBlockRestrictable(), BlockRestrictable::isBlockSubset(), and BlockRestrictable::meshBlockIDs().
_blk_name
const std::string& BlockRestrictable::_blk_name private inherited
Name of the object.
Definition at line 256 of file BlockRestrictable.h.
Referenced by BlockRestrictable::checkVariable(), and BlockRestrictable::initializeBlockRestrictable().
_blk_tid
THREAD_ID BlockRestrictable::_blk_tid private inherited
Thread id for this object.
Definition at line 253 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_block_ids
const std::set<SubdomainID>& BoundaryRestrictable::_block_ids private inherited
Reference to the block_ids, defaults to an empty set if not provided.
Definition at line 204 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::initializeBoundaryRestrictable().
_blocks
std::vector<SubdomainName> BlockRestrictable::_blocks private inherited
Vector the block names supplied by the user via the input file.
Definition at line 235 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blocks(), and BlockRestrictable::initializeBlockRestrictable().
_bnd_dual_restrictable
const bool BoundaryRestrictable::_bnd_dual_restrictable private inherited
Flag for allowing dual restriction with BlockRestrictable.
Definition at line 198 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::initializeBoundaryRestrictable().
_bnd_feproblem
FEProblemBase* BoundaryRestrictable::_bnd_feproblem private inherited
Pointer to FEProblemBase.
Definition at line 183 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::hasBoundaryMaterialPropertyHelper(), and BoundaryRestrictable::initializeBoundaryRestrictable().
_bnd_ids
std::set<BoundaryID> BoundaryRestrictable::_bnd_ids private inherited
Set of the boundary ids.
Definition at line 189 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::boundaryIDs(), BoundaryRestrictable::boundaryRestricted(), BoundaryRestrictable::hasBoundary(), BoundaryRestrictable::initializeBoundaryRestrictable(), BoundaryRestrictable::isBoundarySubset(), and BoundaryRestrictable::numBoundaryIDs().
_bnd_material_data
const MaterialData& BoundaryRestrictable::_bnd_material_data private inherited
Pointer to MaterialData for boundary (.
See also
hasBoundaryMaterialProperty)
Definition at line 210 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::hasBoundaryMaterialProperty().
_bnd_mesh
MooseMesh* BoundaryRestrictable::_bnd_mesh private inherited
Point to mesh.
Definition at line 186 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::hasBoundary(), BoundaryRestrictable::initializeBoundaryRestrictable(), BoundaryRestrictable::isBoundarySubset(), and BoundaryRestrictable::meshBoundaryIDs().
_bnd_nodal
bool BoundaryRestrictable::_bnd_nodal private inherited
Whether or not this object is restricted to nodesets.
Definition at line 213 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::initializeBoundaryRestrictable().
_bnd_tid
THREAD_ID BoundaryRestrictable::_bnd_tid private inherited
Thread id for this object.
Definition at line 207 of file BoundaryRestrictable.h.
_boundary_ids
const std::set<BoundaryID>& BlockRestrictable::_boundary_ids private inherited
Reference to the boundary_ids, defaults to an empty set if not provided.
Definition at line 250 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_boundary_names
std::vector<BoundaryName> BoundaryRestrictable::_boundary_names private inherited
Vector the the boundary names.
Definition at line 195 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::boundaryNames(), and BoundaryRestrictable::initializeBoundaryRestrictable().
_broadcast_by_default
const bool VectorPostprocessorInterface::_broadcast_by_default private inherited
Whether or not to force broadcasting by default.
Definition at line 352 of file VectorPostprocessorInterface.h.
Referenced by VectorPostprocessorInterface::getVectorPostprocessorValueByName(), and VectorPostprocessorInterface::getVectorPostprocessorValueOldByName().
_compute
const bool MaterialBase::_compute protected
If False MOOSE does not compute this property.
Definition at line 313 of file MaterialBase.h.
Referenced by resetQpProperties().
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_coord
const MooseArray<Real>& MaterialBase::_coord protected
Definition at line 288 of file MaterialBase.h.
_coord_sys
const Moose::CoordinateSystemType& MaterialBase::_coord_sys protected
Coordinate system.
Definition at line 295 of file MaterialBase.h.
_coupled_moose_scalar_vars
std::vector<MooseVariableScalar *> ScalarCoupleable::_coupled_moose_scalar_vars private inherited
Vector of coupled variables.
Definition at line 286 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::getCoupledMooseScalarVars(), and ScalarCoupleable::ScalarCoupleable().
_coupled_scalar_vars
std::unordered_map<std::string, std::vector<MooseVariableScalar *> > ScalarCoupleable::_coupled_scalar_vars private inherited
Coupled vars whose values we provide.
Definition at line 277 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::coupledScalarComponents(), ScalarCoupleable::getScalarVar(), ScalarCoupleable::isCoupledScalar(), and ScalarCoupleable::ScalarCoupleable().
_curr_element
const Elem* const& RandomInterface::_curr_element private inherited
Definition at line 84 of file RandomInterface.h.
Referenced by RandomInterface::getRandomLong(), and RandomInterface::getRandomReal().
_curr_node
const Node* const& RandomInterface::_curr_node private inherited
Definition at line 83 of file RandomInterface.h.
Referenced by RandomInterface::getRandomLong(), and RandomInterface::getRandomReal().
_current_execute_flag
const ExecFlagType& SetupInterface::_current_execute_flag protected inherited
Reference to FEProblemBase.
Definition at line 78 of file SetupInterface.h.
Referenced by PseudoTimestep::execute().
_declare_suffix
const MaterialPropertyName MaterialBase::_declare_suffix private
Definition at line 342 of file MaterialBase.h.
Referenced by declareGenericPropertyByName().
_default_ad_real_functors
std::vector<std::unique_ptr<Moose::Functor<ADReal> > > FunctorInterface::_default_ad_real_functors private inherited
Storage vector for Moose::Functor<ADReal> default objects.
Definition at line 162 of file FunctorInterface.h.
_default_real_functors
std::vector<std::unique_ptr<Moose::Functor<Real> > > FunctorInterface::_default_real_functors private inherited
Storage vector for Moose::Functor<Real> default objects.
Definition at line 159 of file FunctorInterface.h.
Referenced by FunctorInterface::defaultFunctor().
_default_value
std::unordered_map<std::string, std::unique_ptr<VariableValue> > ScalarCoupleable::_default_value mutable private inherited
Will hold the default value for optional coupled scalar variables.
Definition at line 280 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::getDefaultValue().
_default_values
std::map<PostprocessorName, std::unique_ptr<PostprocessorValue> > PostprocessorInterface::_default_values mutable private inherited
Holds the default postprocessor values that are requested (key is PostprocessorName)
Definition at line 154 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::getPostprocessorValueInternal().
_displacements
std::vector<unsigned int> MaterialBase::_displacements protected
Definition at line 332 of file MaterialBase.h.
_dni_feproblem
FEProblemBase& DistributionInterface::_dni_feproblem private inherited
Reference to FEProblemBase instance.
Definition at line 61 of file DistributionInterface.h.
Referenced by DistributionInterface::getDistribution(), and DistributionInterface::getDistributionByName().
_dni_moose_object_ptr
const MooseObject* const DistributionInterface::_dni_moose_object_ptr private inherited
Pointer to the MooseObject.
Definition at line 64 of file DistributionInterface.h.
Referenced by DistributionInterface::getDistribution(), and DistributionInterface::getDistributionByName().
_dni_params
const InputParameters& DistributionInterface::_dni_params private inherited
Parameters of the object with this interface.
Definition at line 58 of file DistributionInterface.h.
Referenced by DistributionInterface::getDistribution().
_dof_indices
std::vector<libMesh::dof_id_type> MooseVariableDependencyInterface::_dof_indices private inherited
A container for holding dof indices in order to avoid constant memory reallocation.
Definition at line 86 of file MooseVariableDependencyInterface.h.
Referenced by MooseVariableDependencyInterface::checkVariables().
_dt
Real& TransientInterface::_dt protected inherited
Time step size.
Definition at line 67 of file TransientInterface.h.
Referenced by ADSurfaceCharge::computeQpProperties(), InterfaceQpValueUserObject::computeRealValue(), Sigma::computeValue(), ForcingFunctionAux::computeValue(), PIDTransientControl::execute(), TimeIntegratedPostprocessor::execute(), and VariableTimeIntegrationAux::getIntegralValue().
_dt_old
Real& TransientInterface::_dt_old protected inherited
Size of the old time step.
Definition at line 70 of file TransientInterface.h.
Referenced by VariableTimeIntegrationAux::getIntegralValue().
_dual_default_value
std::unordered_map<std::string, std::unique_ptr<ADVariableValue> > ScalarCoupleable::_dual_default_value mutable private inherited
Will hold the default AD value for optional coupled scalar variables.
Definition at line 283 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::getADDefaultValue().
_ei_name
const std::string& ElementIDInterface::_ei_name private inherited
Name of the object using this interface.
Definition at line 154 of file ElementIDInterface.h.
Referenced by ElementIDInterface::getElementIDIndexByName().
_empty_block_ids
const std::set<SubdomainID> BoundaryRestrictable::_empty_block_ids private inherited
An empty set for referencing when block_ids is not included.
Definition at line 201 of file BoundaryRestrictable.h.
_empty_boundary_ids
const std::set<BoundaryID> BlockRestrictable::_empty_boundary_ids private inherited
An empty set for referencing when boundary_ids is not included.
Definition at line 247 of file BlockRestrictable.h.
_empty_execute_enum
ExecFlagEnum SetupInterface::_empty_execute_enum private inherited
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
This is private because others should not be messing with it.
Definition at line 71 of file SetupInterface.h.
Referenced by SetupInterface::SetupInterface().
_enabled
const bool& MooseObject::_enabled protected inherited
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
Definition at line 58 of file MooseObject.h.
Referenced by MooseObject::enabled().
_execute_enum
const ExecFlagEnum& SetupInterface::_execute_enum protected inherited
Execute settings for this object.
Definition at line 75 of file SetupInterface.h.
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), SetupInterface::getExecuteOnEnum(), JSONOutput::outputReporters(), XMLOutput::outputVectorPostprocessors(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
_face_info
const FaceInfo* MaterialBase::_face_info = nullptr protected
Definition at line 339 of file MaterialBase.h.
Referenced by setFaceInfo().
_factory
Factory& MooseBaseParameterInterface::_factory protected inherited
The Factory associated with the MooseApp.
Definition at line 161 of file MooseBaseParameterInterface.h.
Referenced by AddGeneralReactions::act(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), ElementIDOutputAction::act(), AddSpecies::act(), AdaptivityAction::act(), AddControlAction::act(), AddNodalNormalsAction::act(), AddPeriodicBCAction::act(), AutoCheckpointAction::act(), ComposeTimeStepperAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DisplayGhostingAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), PartitionerAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SetupPreconditionerAction::act(), SetupPredictorAction::act(), SetupResidualDebugAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddGeneralReactions::addEEDFReactionKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddDriftDiffusionAction::addPosition(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), MooseBaseParameterInterface::connectControllableParams(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), MaterialOutputAction::getParams(), and ProjectedStatefulMaterialStorageAction::processProperty().
_fe_problem
FEProblemBase& MaterialBase::_fe_problem protected
Definition at line 282 of file MaterialBase.h.
Referenced by checkExecutionStage(), checkStatefulSanity(), getGenericZeroMaterialProperty(), getGenericZeroMaterialPropertyByName(), miProblem(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), registerPropName(), and Material::subdomainSetup().
_fi_name
const std::string FunctorInterface::_fi_name private inherited
The name of the object that this interface belongs to.
Definition at line 150 of file FunctorInterface.h.
Referenced by FunctorInterface::getFunctorByName().
_fi_params
const InputParameters& FunctorInterface::_fi_params private inherited
Parameters of the object with this interface.
Definition at line 147 of file FunctorInterface.h.
Referenced by FunctorInterface::deduceFunctorName().
_fi_subproblem
SubProblem* const FunctorInterface::_fi_subproblem private inherited
Pointer to subproblem if the subproblem pointer parameter was set.
Definition at line 153 of file FunctorInterface.h.
Referenced by FunctorInterface::getFunctor(), and FunctorInterface::isFunctor().
_fi_tid
const THREAD_ID FunctorInterface::_fi_tid private inherited
Current threaded it.
Definition at line 156 of file FunctorInterface.h.
Referenced by FunctorInterface::getFunctor(), and FunctorInterface::isFunctor().
_fni_feproblem
FEProblemBase& FunctionInterface::_fni_feproblem private inherited
Reference to FEProblemBase instance.
Definition at line 84 of file FunctionInterface.h.
Referenced by FunctionInterface::getFunction(), FunctionInterface::getFunctionByName(), and FunctionInterface::hasFunctionByName().
_fni_params
const InputParameters& FunctionInterface::_fni_params private inherited
Parameters of the object with this interface.
Definition at line 81 of file FunctionInterface.h.
Referenced by FunctionInterface::getFunction(), and FunctionInterface::hasFunction().
_fni_tid
const THREAD_ID FunctionInterface::_fni_tid private inherited
Thread ID.
Definition at line 87 of file FunctionInterface.h.
Referenced by FunctionInterface::getFunction(), FunctionInterface::getFunctionByName(), and FunctionInterface::hasFunctionByName().
_generator
MooseRandom* RandomInterface::_generator mutable private inherited
Definition at line 74 of file RandomInterface.h.
Referenced by RandomInterface::getRandomLong(), RandomInterface::getRandomReal(), and RandomInterface::setRandomDataPointer().
_geometric_search_data
GeometricSearchData& GeometricSearchInterface::_geometric_search_data protected inherited
Definition at line 68 of file GeometricSearchInterface.h.
Referenced by GeometricSearchInterface::getNearestNodeLocator(), GeometricSearchInterface::getPenetrationLocator(), GeometricSearchInterface::getQuadratureNearestNodeLocator(), and GeometricSearchInterface::getQuadraturePenetrationLocator().
_has_stateful_property
bool MaterialBase::_has_stateful_property protected
Definition at line 335 of file MaterialBase.h.
Referenced by hasStatefulProperties(), and registerPropName().
_id_mesh
std::shared_ptr<MooseMesh>& ElementIDInterface::_id_mesh private inherited
References to the mesh and displaced mesh (currently in the ActionWarehouse)
Definition at line 151 of file ElementIDInterface.h.
Referenced by ElementIDInterface::areElemIDsIdentical(), ElementIDInterface::getAllElemIDs(), ElementIDInterface::getElementIDIndexByName(), ElementIDInterface::getElemIDMapping(), ElementIDInterface::getElemIDsOnBlocks(), ElementIDInterface::hasElementID(), ElementIDInterface::maxElementID(), and ElementIDInterface::minElementID().
_is_implicit
bool TransientInterface::_is_implicit protected inherited
If the object is using implicit or explicit form.
This does NOT mean time scheme, but which values are going to be used in the object - either from current time or old time. Note that even explicit schemes have implicit form (it is the time derivative "kernel")
Definition at line 58 of file TransientInterface.h.
Referenced by EigenKernel::computeJacobian(), EigenKernel::computeOffDiagJacobian(), IntegratedBC::computeResidualAndJacobian(), NodalBC::computeResidualAndJacobian(), Kernel::computeResidualAndJacobian(), TransientInterface::determineState(), EigenKernel::EigenKernel(), EigenKernel::enabled(), and TransientInterface::isImplicit().
_is_nodal
bool RandomInterface::_is_nodal private inherited
Definition at line 80 of file RandomInterface.h.
Referenced by RandomInterface::getRandomLong(), RandomInterface::getRandomReal(), and RandomInterface::isNodal().
_is_transient
bool TransientInterface::_is_transient protected inherited
Definition at line 73 of file TransientInterface.h.
Referenced by InterfaceTimeKernel::InterfaceTimeKernel().
_master_seed
unsigned int RandomInterface::_master_seed private inherited
Definition at line 79 of file RandomInterface.h.
Referenced by RandomInterface::getMasterSeed().
_mci_feproblem
FEProblemBase& MeshChangedInterface::_mci_feproblem protected inherited
Reference to FEProblemBase instance.
Definition at line 38 of file MeshChangedInterface.h.
Referenced by MeshChangedInterface::MeshChangedInterface().
_mesh
MooseMesh& MaterialBase::_mesh protected
Definition at line 292 of file MaterialBase.h.
Referenced by FunctorMaterial::addFunctorPropertyByBlocks(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), and PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl().
_metaname
const RestartableDataMapName Restartable::_metaname private inherited
Restartable metadata name.
Definition at line 240 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_moose_base
const MooseBase* const MooseBaseParameterInterface::_moose_base private inherited
The MooseBase object that inherits this class.
Definition at line 168 of file MooseBaseParameterInterface.h.
Referenced by MooseBaseParameterInterface::connectControllableParams(), MooseBaseParameterInterface::objectErrorPrefix(), MooseBaseParameterInterface::paramError(), and MooseBaseParameterInterface::uniqueParameterName().
_moose_object
const MooseObject& BoundaryRestrictable::_moose_object private inherited
The moose object that this is an interface for.
Definition at line 216 of file BoundaryRestrictable.h.
Referenced by BoundaryRestrictable::initializeBoundaryRestrictable().
_moose_variable_dependencies
std::set<MooseVariableFieldBase *> MooseVariableDependencyInterface::_moose_variable_dependencies private inherited
Definition at line 83 of file MooseVariableDependencyInterface.h.
Referenced by MooseVariableDependencyInterface::addMooseVariableDependency(), MooseVariableDependencyInterface::checkAllVariables(), and MooseVariableDependencyInterface::getMooseVariableDependencies().
_name
const std::string& MooseBase::_name protected inherited
The name of this class, reference to value stored in InputParameters.
Definition at line 66 of file MooseBase.h.
Referenced by AddFieldSplitAction::act(), AddBCAction::act(), AddConstraintAction::act(), AddControlAction::act(), AddDamperAction::act(), AddDGKernelAction::act(), AddDiracKernelAction::act(), AddDistributionAction::act(), AddFunctionAction::act(), AddFunctorMaterialAction::act(), AddFVBCAction::act(), AddFVInitialConditionAction::act(), AddFVInterfaceKernelAction::act(), AddFVKernelAction::act(), AddIndicatorAction::act(), AddInitialConditionAction::act(), AddInterfaceKernelAction::act(), AddKernelAction::act(), AddMarkerAction::act(), AddMaterialAction::act(), AddMeshDivisionAction::act(), AddMeshGeneratorAction::act(), AddMultiAppAction::act(), AddNodalKernelAction::act(), AddOutputAction::act(), AddPeriodicBCAction::act(), AddPositionsAction::act(), AddPostprocessorAction::act(), AddReporterAction::act(), AddSamplerAction::act(), AddScalarKernelAction::act(), AddTimesAction::act(), AddTimeStepperAction::act(), AddTransferAction::act(), AddUserObjectAction::act(), AddVectorPostprocessorAction::act(), PartitionerAction::act(), ReadExecutorParamsAction::act(), SetupPreconditionerAction::act(), SetupTimeIntegratorAction::act(), AddDriftDiffusionAction::addADKernels(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromXY(), PiecewiseLinearBase::buildInterpolation(), CombinerGenerator::CombinerGenerator(), Executor::Executor(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), FunctionDT::FunctionDT(), FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), MooseBase::name(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), PiecewiseBase::setData(), and Split::setup().
_normals
const MooseArray<Point>& MaterialBase::_normals protected
normals at quadrature points (valid only in boundary materials)
Definition at line 290 of file MaterialBase.h.
Referenced by ADSurfaceCharge::computeQpProperties().
_obj_parameters
const InputParameters& ElementIDInterface::_obj_parameters private inherited
Reference to the object's input parameters.
Definition at line 148 of file ElementIDInterface.h.
Referenced by ElementIDInterface::getElementID(), ElementIDInterface::getElementIDByName(), ElementIDInterface::getElementIDIndex(), ElementIDInterface::getElementIDNeighbor(), and ElementIDInterface::getElementIDNeighborByName().
_oi_moose_app
MooseApp& OutputInterface::_oi_moose_app private inherited
Reference the the MooseApp; neede for access to the OutputWarehouse.
Definition at line 66 of file OutputInterface.h.
_oi_output_warehouse
OutputWarehouse& OutputInterface::_oi_output_warehouse private inherited
Reference to the OutputWarehouse for populating the Output object hide lists.
Definition at line 69 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList().
_oi_outputs
std::set<OutputName> OutputInterface::_oi_outputs private inherited
The set of Output object names listed in the 'outputs' parameter.
Definition at line 72 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList(), and OutputInterface::getOutputs().
_overrides_init_stateful_props
bool MaterialBase::_overrides_init_stateful_props = true protected
Definition at line 337 of file MaterialBase.h.
Referenced by initQpStatefulProperties(), and initStatefulProperties().
_parent
const MooseObject & DataFileInterface< MooseObject >::_parent private inherited
Definition at line 46 of file DataFileInterface.h.
_pars
const InputParameters& MooseBaseParameterInterface::_pars protected inherited
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Definition at line 158 of file MooseBaseParameterInterface.h.
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), AddPeriodicBCAction::act(), AddVariableAction::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), FunctorMaterial::addFunctorPropertyByBlocks(), FVFluxKernel::adjustRMGhostLayers(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), PiecewiseTabularBase::buildFromFile(), PNGOutput::calculateRescalingValues(), BlockWeightedPartitioner::clone(), GridPartitioner::clone(), HierarchicalGridPartitioner::clone(), PetscExternalPartitioner::clone(), RandomPartitioner::clone(), SingleRankPartitioner::clone(), MooseBaseParameterInterface::connectControllableParams(), Console::Console(), AddVariableAction::createInitialConditionAction(), declareADProperty(), declareProperty(), FEProblemSolve::FEProblemSolve(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), FileMeshGenerator::generate(), getGenericZeroMaterialProperty(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getParam(), MooseBaseParameterInterface::getRenamedParam(), AddVariableAction::init(), AdvancedOutput::initExecutionTypes(), Console::initialSetup(), MooseBaseParameterInterface::isParamSetByUser(), MooseBaseParameterInterface::isParamValid(), MultiApp::keepSolutionDuringRestore(), MooseBaseParameterInterface::paramErrorMsg(), GlobalParamsAction::parameters(), MooseBaseParameterInterface::parameters(), MooseMesh::prepare(), Eigenvalue::prepareSolverOptions(), MooseMesh::setCoordSystem(), MooseMesh::setPartitionerHelper(), SetupMeshAction::setupMesh(), Transient::setupTimeIntegrator(), MooseBaseParameterInterface::uniqueName(), and MooseBaseParameterInterface::uniqueParameterName().
_point_zero
const Point& ScalarCoupleable::_point_zero protected inherited
Zero point.
Definition at line 233 of file ScalarCoupleable.h.
Referenced by FunctionDT::computeDT(), FunctionScalarAux::computeValue(), and FunctionScalarIC::value().
_ppi_feproblem
const FEProblemBase& PostprocessorInterface::_ppi_feproblem private inherited
Reference the the FEProblemBase class.
Definition at line 151 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::hasPostprocessorByName(), PostprocessorInterface::isDefaultPostprocessorValueByName(), and PostprocessorInterface::postprocessorsAdded().
_ppi_moose_object
const MooseObject& PostprocessorInterface::_ppi_moose_object private inherited
The MooseObject that uses this interface.
Definition at line 145 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::checkParam(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueByNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), PostprocessorInterface::hasPostprocessor(), and PostprocessorInterface::hasPostprocessorByName().
_ppi_params
const InputParameters& PostprocessorInterface::_ppi_params private inherited
PostprocessorInterface Parameters.
Definition at line 148 of file PostprocessorInterface.h.
Referenced by PostprocessorInterface::checkParam(), PostprocessorInterface::coupledPostprocessors(), and PostprocessorInterface::getPostprocessorNameInternal().
_props_to_min_states
std::unordered_map<unsigned int, unsigned int> MaterialBase::_props_to_min_states protected
The minimum states requested (0 = current, 1 = old, 2 = older) This is sparse and is used to keep track of whether or not stateful properties are requested without state 0 being requested.
Definition at line 324 of file MaterialBase.h.
Referenced by checkStatefulSanity(), and registerPropName().
_qp
unsigned int MaterialBase::_qp protected
Definition at line 286 of file MaterialBase.h.
Referenced by InterfaceMaterial::computeProperties(), Material::computeProperties(), computePropertiesAtQp(), ADEEDFRateConstantTownsend::computeQpProperties(), ADZapdosEEDFRateConstant::computeQpProperties(), DiffusionRateTemp::computeQpProperties(), EEDFRateConstant::computeQpProperties(), EEDFRateConstantTownsend::computeQpProperties(), HeatCapacityRatio::computeQpProperties(), InterpolatedCoefficientLinear::computeQpProperties(), InterpolatedCoefficientSpline::computeQpProperties(), SpeciesSum::computeQpProperties(), SuperelasticReactionRate::computeQpProperties(), ZapdosEEDFRateConstant::computeQpProperties(), ElectricField::computeQpProperties(), ADGasElectronMoments::computeQpProperties(), ADSurfaceCharge::computeQpProperties(), Gas::computeQpProperties(), GasBase::computeQpProperties(), GasElectronMoments::computeQpProperties(), Water::computeQpProperties(), ADPiecewiseLinearInterpolationMaterial::computeQpProperties(), GenericConstant2DArray::computeQpProperties(), GenericConstantArray::computeQpProperties(), PiecewiseLinearInterpolationMaterial::computeQpProperties(), ElectricField::initQpStatefulProperties(), ADSurfaceCharge::initQpStatefulProperties(), initStatefulProperties(), CompileTimeDerivativesMaterial< N, is_ad, MaxD >::loopEvaluate(), resetProperties(), and Material::subdomainSetup().
_random_data
RandomData* RandomInterface::_random_data private inherited
Definition at line 73 of file RandomInterface.h.
Referenced by RandomInterface::getSeed(), and RandomInterface::setRandomDataPointer().
_real_zero
const Real& ScalarCoupleable::_real_zero protected inherited
Scalar zero.
Definition at line 227 of file ScalarCoupleable.h.
_requested_props
std::set<std::string> MaterialBase::_requested_props protected
Set of properties accessed via get method.
Definition at line 298 of file MaterialBase.h.
Referenced by InterfaceMaterial::getGenericMaterialPropertyByName(), Material::getGenericMaterialPropertyByName(), InterfaceMaterial::getGenericNeighborMaterialPropertyByName(), getGenericZeroMaterialPropertyByName(), Material::getMaterialByName(), and getRequestedItems().
_requires_geometric_search
bool GeometricSearchInterface::_requires_geometric_search protected inherited
Whether any of this interface's methods have been called, e.g.
whether the object that this interface is for requires geometric search data
Definition at line 72 of file GeometricSearchInterface.h.
Referenced by GeometricSearchInterface::getNearestNodeLocator(), GeometricSearchInterface::getPenetrationLocator(), GeometricSearchInterface::getQuadratureNearestNodeLocator(), GeometricSearchInterface::getQuadraturePenetrationLocator(), and GeometricSearchInterface::requiresGeometricSearch().
_reset_on
ExecFlagType RandomInterface::_reset_on private inherited
Definition at line 81 of file RandomInterface.h.
Referenced by RandomInterface::getResetOnTime(), and RandomInterface::setRandomResetFrequency().
_restartable_app
MooseApp& Restartable::_restartable_app protected inherited
Reference to the application.
Definition at line 227 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp(), and Restartable::registerRestartableNameWithFilterOnApp().
_restartable_name
std::string Restartable::_restartable_name private inherited
The name of the object.
Definition at line 243 of file Restartable.h.
Referenced by Restartable::declareRestartableDataWithObjectNameWithContext(), and Restartable::restartableName().
_restartable_read_only
const bool Restartable::_restartable_read_only protected inherited
Flag for toggling read only status (see ReporterData)
Definition at line 236 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_restartable_system_name
const std::string Restartable::_restartable_system_name protected inherited
The system name this object is in.
Definition at line 230 of file Restartable.h.
Referenced by Restartable::restartableName().
_restartable_tid
const THREAD_ID Restartable::_restartable_tid protected inherited
The thread ID for this object.
Definition at line 233 of file Restartable.h.
Referenced by Restartable::declareRestartableDataHelper().
_ri_name
const std::string RandomInterface::_ri_name private inherited
Definition at line 77 of file RandomInterface.h.
Referenced by RandomInterface::setRandomResetFrequency().
_ri_problem
FEProblemBase& RandomInterface::_ri_problem private inherited
Definition at line 76 of file RandomInterface.h.
Referenced by RandomInterface::setRandomResetFrequency().
_sc_coupleable_matrix_tags
std::set<TagID> ScalarCoupleable::_sc_coupleable_matrix_tags mutable private inherited
The scalar coupleable matrix tags.
Definition at line 294 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::coupledMatrixTagScalarValue(), and ScalarCoupleable::getScalarVariableCoupleableMatrixTags().
_sc_coupleable_vector_tags
std::set<TagID> ScalarCoupleable::_sc_coupleable_vector_tags mutable private inherited
The scalar coupleable vector tags.
Definition at line 292 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::coupledVectorTagScalarValue(), and ScalarCoupleable::getScalarVariableCoupleableVectorTags().
_sc_coupled_vars
std::unordered_map<std::string, std::vector<MooseVariableFieldBase *> > ScalarCoupleable::_sc_coupled_vars private inherited
Field variables coupled into this object (for error checking)
Definition at line 289 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::checkVar(), and ScalarCoupleable::ScalarCoupleable().
_sc_fe_problem
FEProblemBase& ScalarCoupleable::_sc_fe_problem protected inherited
Definition at line 221 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::coupledScalarOrder(), ScalarCoupleable::coupledVectorTagScalarValue(), ScalarCoupleable::getADDefaultValue(), ScalarCoupleable::getDefaultValue(), and ScalarCoupleable::validateExecutionerType().
_sc_is_implicit
const bool ScalarCoupleable::_sc_is_implicit private inherited
True if implicit value is required.
Definition at line 274 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::adCoupledScalarValue(), ScalarCoupleable::coupledScalarValue(), ScalarCoupleable::coupledScalarValueOld(), and ScalarCoupleable::coupledScalarValueOlder().
_sc_name
const std::string& ScalarCoupleable::_sc_name private inherited
The name of the object this interface is part of.
Definition at line 271 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::checkVar(), ScalarCoupleable::coupledScalarComponents(), ScalarCoupleable::coupledVectorTagScalarValue(), ScalarCoupleable::getScalarVar(), ScalarCoupleable::isCoupledScalar(), ScalarCoupleable::ScalarCoupleable(), and ScalarCoupleable::validateExecutionerType().
_sc_parameters
const InputParameters& ScalarCoupleable::_sc_parameters private inherited
Definition at line 268 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::checkVar(), ScalarCoupleable::coupledScalarComponents(), ScalarCoupleable::getADDefaultValue(), ScalarCoupleable::getDefaultValue(), ScalarCoupleable::getScalarVar(), ScalarCoupleable::isCoupledScalar(), and ScalarCoupleable::ScalarCoupleable().
_sc_tid
const THREAD_ID ScalarCoupleable::_sc_tid protected inherited
Thread ID of the thread using this object.
Definition at line 224 of file ScalarCoupleable.h.
Referenced by ScalarCoupleable::ScalarCoupleable().
_scalar_zero
const VariableValue& ScalarCoupleable::_scalar_zero protected inherited
Zero value of a scalar variable.
Definition at line 230 of file ScalarCoupleable.h.
_si_moose_object
MooseObject& SolutionInvalidInterface::_si_moose_object private inherited
The MooseObject that owns this interface.
Definition at line 43 of file SolutionInvalidInterface.h.
Referenced by SolutionInvalidInterface::flagInvalidSolutionInternal(), and SolutionInvalidInterface::registerInvalidSolutionInternal().
_si_problem
FEProblemBase& SolutionInvalidInterface::_si_problem private inherited
A reference to FEProblem base.
Definition at line 46 of file SolutionInvalidInterface.h.
Referenced by SolutionInvalidInterface::flagInvalidSolutionInternal().
_subproblem
SubProblem& MaterialBase::_subproblem protected
Definition at line 280 of file MaterialBase.h.
Referenced by FunctorMaterial::addFunctorPropertyByBlocks().
_supplied_prop_ids
std::set<unsigned int> MaterialBase::_supplied_prop_ids protected
The ids of the supplied properties, i.e.
the indices where they are stored in the _material_data->props(). Note: these ids ARE NOT IN THE SAME ORDER AS THE _supplied_props set, which is ordered alphabetically by name. The intention of this container is to allow rapid copying of MaterialProperty values in MaterialBase::computeProperties() without looking up the ids from the name strings each time.
Definition at line 310 of file MaterialBase.h.
Referenced by Material::computeProperties(), getSuppliedPropIDs(), registerPropName(), and Material::subdomainSetup().
_supplied_props
std::set<std::string> MaterialBase::_supplied_props protected
Set of properties declared.
Definition at line 301 of file MaterialBase.h.
Referenced by getSuppliedItems(), initStatefulProperties(), and registerPropName().
_t
Real& TransientInterface::_t protected inherited
Time.
Definition at line 61 of file TransientInterface.h.
Referenced by FVFunctionDirichletBC::boundaryValue(), AnalyticalDiffIndicator::computeQpIntegral(), AnalyticalIndicator::computeQpIntegral(), ElementH1SemiError::computeQpIntegral(), ElementL1Error::computeQpIntegral(), ElementL2Error::computeQpIntegral(), ElementVectorL2Error::computeQpIntegral(), ElementW1pError::computeQpIntegral(), FunctionElementIntegral::computeQpIntegral(), FunctionSideIntegral::computeQpIntegral(), FunctionElementIntegralUserObject::computeQpIntegral(), FunctionDiffusion::computeQpJacobian(), VectorFunctionReaction::computeQpJacobian(), VelocityFunctionOutflowBC::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), Gas::computeQpProperties(), GasBase::computeQpProperties(), GasElectronMoments::computeQpProperties(), FieldEmissionBC::computeQpResidual(), NeumannCircuitVoltageMoles_KV::computeQpResidual(), NeumannCircuitVoltageNew::computeQpResidual(), SchottkyEmissionBC::computeQpResidual(), TM0AntennaVertBC::computeQpResidual(), ADConservativeAdvectionBC::computeQpResidual(), ADFunctionNeumannBC::computeQpResidual(), ADFunctionPenaltyDirichletBC::computeQpResidual(), ADVectorFunctionNeumannBC::computeQpResidual(), ConvectiveFluxBC::computeQpResidual(), DGFunctionDiffusionDirichletBC::computeQpResidual(), FunctionGradientNeumannBC::computeQpResidual(), FunctionNeumannBC::computeQpResidual(), FunctionPenaltyDirichletBC::computeQpResidual(), SinDirichletBC::computeQpResidual(), SinNeumannBC::computeQpResidual(), VectorCurlPenaltyDirichletBC::computeQpResidual(), VectorDivPenaltyDirichletBC::computeQpResidual(), VectorFunctionDirichletBC::computeQpResidual(), VectorPenaltyDirichletBC::computeQpResidual(), FunctionDiracSource::computeQpResidual(), FVFunctionNeumannBC::computeQpResidual(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), FVBodyForce::computeQpResidual(), FunctionDiffusion::computeQpResidual(), VectorBodyForce::computeQpResidual(), VectorFunctionReaction::computeQpResidual(), UserForcingFunctionNodalKernel::computeQpResidual(), VelocityFunctionOutflowBC::computeQpResidual(), DGFunctionConvection::computeQpResidual(), ArrayBodyForce::computeQpResidual(), FunctionDirichletBC::computeQpValue(), DataRead::computeValue(), ScalarLinearInterpolation::computeValue(), ScalarSplineInterpolation::computeValue(), ArrayParsedAux::computeValue(), ElementH1ErrorFunctionAux::computeValue(), ElementL2ErrorFunctionAux::computeValue(), ForcingFunctionAux::computeValue(), FunctionArrayAux::computeValue(), FunctionAux::computeValue(), FunctionScalarAux::computeValue(), ParsedAux::computeValue(), ParsedVectorAux::computeValue(), SolutionAux::computeValue(), SolutionScalarAux::computeValue(), VectorFunctionAux::computeValue(), FunctionDerivativeAux::computeValue(), ConditionalFunctionEnableControl::conditionMet(), TimePeriod::conditionMet(), BoltzmannSolverScalar::execute(), BoolFunctionControl::execute(), PIDTransientControl::execute(), RealFunctionControl::execute(), NodalL2Error::execute(), TimeExtremeValue::execute(), IterationInfo::execute(), LeastSquaresFitHistory::execute(), LineFunctionSampler::execute(), UserForcingFunction::f(), ParsedPostprocessor::finalize(), FunctionValuePostprocessor::getValue(), ScalarL2Error::getValue(), BoltzmannSolverScalar::initialize(), ActivateElementsByPath::isElementActivated(), and SolutionUserObject::timestepSetup().
_t_step
int& TransientInterface::_t_step protected inherited
The number of the time step.
Definition at line 64 of file TransientInterface.h.
Referenced by PIDTransientControl::execute(), AccumulateReporter::execute(), IterationInfo::execute(), ChangeOverFixedPointPostprocessor::finalize(), and ChangeOverTimePostprocessor::finalize().
_ti_feproblem
FEProblemBase& TransientInterface::_ti_feproblem protected inherited
Definition at line 50 of file TransientInterface.h.
Referenced by Function::evaluate(), Function::evaluateDotHelper(), Function::evaluateGradientHelper(), Function::evaluateHelper(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), and SolutionFunction::SolutionFunction().
_ti_name
const std::string TransientInterface::_ti_name private inherited
Definition at line 76 of file TransientInterface.h.
_ti_params
const InputParameters& TransientInterface::_ti_params protected inherited
Definition at line 48 of file TransientInterface.h.
_tid
THREAD_ID MaterialBase::_tid protected
Definition at line 283 of file MaterialBase.h.
Referenced by FunctorMaterial::addFunctorPropertyByBlocks(), and FunctorSmootherTempl< T >::FunctorSmootherTempl().
_type
const std::string& MooseBase::_type protected inherited
The type of this class.
Definition at line 63 of file MooseBase.h.
Referenced by FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), FEProblemBase::init(), FEProblemBase::solverTypeString(), and MooseBase::type().
_uoi_feproblem
const FEProblemBase& UserObjectInterface::_uoi_feproblem private inherited
Reference to the FEProblemBase instance.
Definition at line 128 of file UserObjectInterface.h.
Referenced by UserObjectInterface::getUserObjectBaseByName(), and UserObjectInterface::hasUserObjectByName().
_uoi_moose_object
const MooseObject& UserObjectInterface::_uoi_moose_object private inherited
Moose object using the interface.
Definition at line 125 of file UserObjectInterface.h.
Referenced by UserObjectInterface::castUserObject(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), and UserObjectInterface::getUserObjectName().
_uoi_tid
const THREAD_ID UserObjectInterface::_uoi_tid private inherited
Thread ID.
Definition at line 131 of file UserObjectInterface.h.
Referenced by UserObjectInterface::getUserObjectBaseByName().
_vec_ids
std::vector<SubdomainID> BlockRestrictable::_vec_ids private inherited
Vector of block ids supplied by the user via the input file (for error reporting)
Definition at line 232 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_vpi_feproblem
const FEProblemBase& VectorPostprocessorInterface::_vpi_feproblem private inherited
Reference the FEProblemBase class.
Definition at line 358 of file VectorPostprocessorInterface.h.
Referenced by VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), VectorPostprocessorInterface::isVectorPostprocessorDistributedByName(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
_vpi_moose_object
const MooseObject& VectorPostprocessorInterface::_vpi_moose_object private inherited
The MooseObject that uses this interface.
Definition at line 355 of file VectorPostprocessorInterface.h.
Referenced by VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper(), VectorPostprocessorInterface::getVectorPostprocessorName(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), and VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName().
_vpi_tid
const THREAD_ID VectorPostprocessorInterface::_vpi_tid private inherited
Thread ID.
Definition at line 361 of file VectorPostprocessorInterface.h.
The documentation for this class was generated from the following files:
moose/framework/include/materials/MaterialBase.h
moose/framework/src/materials/MaterialBase.C