Zapdos: MultiAppGeneralFieldShapeEvaluationTransfer Class Reference
MultiAppGeneralFieldShapeEvaluationTransfer Class Reference
Evaluates origin shape functions to compute the target variables.
#include <MultiAppGeneralFieldShapeEvaluationTransfer.h>
Public Types
enum DIRECTION { TO_MULTIAPP , FROM_MULTIAPP , BETWEEN_MULTIAPP }
Public Member Functions
MultiAppGeneralFieldShapeEvaluationTransfer (const InputParameters &parameters)
virtual void initialSetup () override
Method called at the beginning of the simulation for checking integrity or doing one-time setup.
virtual void getAppInfo () override
This method will fill information into the convenience member variables (_to_problems, _from_meshes, etc.)
virtual void execute () override
Execute the transfer.
VariableName getFromVarName (unsigned int var_index)
Get the source variable name, with the suffix for array/vector variables.
VariableName getToVarName (unsigned int var_index)
Get the target variable name, with the suffix for array/vector variables.
virtual void postExecute ()
Add some extra work if necessary after execute().
void variableIntegrityCheck (const AuxVariableName &var_name) const
Utility to verify that the variable in the destination system exists.
const std::shared_ptr< MultiApp > getMultiApp () const
Use this getter to obtain the MultiApp for transfers with a single direction.
const std::shared_ptr< MultiApp > getFromMultiApp () const
Get the MultiApp to transfer data from.
const std::shared_ptr< MultiApp > getToMultiApp () const
Get the MultiApp to transfer data to.
std::string getFromName () const
Get the name of thing being transferred from.
std::string getToName () const
Get the name of thing being transferred to.
bool hasFromMultiApp () const
Whether the transfer owns a non-null from_multi_app.
bool hasToMultiApp () const
Whether the transfer owns a non-null to_multi_app.
const MultiMooseEnum & directions ()
The directions this Transfer should be executed on.
void setCurrentDirection (const int direction)
Set this Transfer to be executed in a given direction.
virtual bool enabled () const
Return the enabled status of the object.
MooseApp & getMooseApp () const
Get the MooseApp this class is associated with.
const std::string & type () const
Get the type of this class.
virtual const std::string & name () const
Get the name of the class.
std::string typeAndName () const
Get the class's combined type and name; useful in error handling.
MooseObjectParameterName uniqueParameterName (const std::string &parameter_name) const
The unique parameter name of a valid parameter of this object for accessing parameter controls.
const InputParameters & parameters () const
Get the parameters of the object.
MooseObjectName uniqueName () const
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
template<typename T >
const T & getParam (const std::string &name) const
Retrieve a parameter for the object.
template<typename T1 , typename T2 >
std::vector< std::pair< T1, T2 > > getParam (const std::string &param1, const std::string &param2) const
Retrieve two parameters and provide pair of parameters for the object.
template<typename T >
const T & getRenamedParam (const std::string &old_name, const std::string &new_name) const
Retrieve a renamed parameter for the object.
template<typename T >
T getCheckedPointerParam (const std::string &name, const std::string &error_string="") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
bool isParamValid (const std::string &name) const
Test if the supplied parameter is valid.
bool isParamSetByUser (const std::string &nm) const
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
template<typename... Args>
void paramError (const std::string &param, Args... args) const
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramWarning (const std::string &param, Args... args) const
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramInfo (const std::string &param, Args... args) const
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
std::string objectErrorPrefix (const std::string &error_type) const
A descriptive prefix for errors for an object.
void connectControllableParams (const std::string &parameter, const std::string &object_type, const std::string &object_name, const std::string &object_parameter) const
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
template<typename... Args>
void mooseError (Args &&... args) const
Emits an error prefixed with object name and type.
template<typename... Args>
void mooseErrorNonPrefixed (Args &&... args) const
Emits an error without the prefixing included in mooseError().
template<typename... Args>
void mooseWarning (Args &&... args) const
Emits a warning prefixed with object name and type.
template<typename... Args>
void mooseWarningNonPrefixed (Args &&... args) const
Emits a warning without the prefixing included in mooseWarning().
template<typename... Args>
void mooseDeprecated (Args &&... args) const
template<typename... Args>
void mooseInfo (Args &&... args) const
std::string errorPrefix (const std::string &error_type) const
A descriptive prefix for errors for this object:
std::string getDataFileName (const std::string &param) const
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
std::string getDataFileNameByName (const std::string &name, const std::string *param=nullptr) const
Returns the path of a data file for a given relative file path.
virtual void timestepSetup ()
Gets called at the beginning of the timestep before this object is asked to do its job.
virtual void jacobianSetup ()
Gets called just before the Jacobian is computed and before this object is asked to do its job.
virtual void residualSetup ()
Gets called just before the residual is computed and before this object is asked to do its job.
virtual void subdomainSetup ()
Gets called when the subdomain changes (i.e.
virtual void customSetup (const ExecFlagType &)
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
const ExecFlagEnum & getExecuteOnEnum () const
Return the execute on MultiMooseEnum for this object.
PerfGraph & perfGraph ()
Get the PerfGraph.
MooseEnum direction ()
MooseEnum currentDirection ()
Static Public Member Functions
static InputParameters validParams ()
static void addSkipCoordCollapsingParam (InputParameters &params)
Add the option to skip coordinate collapsing in coordinate transformation operations.
static System * find_sys (EquationSystems &es, const std::string &var_name)
Small helper function for finding the system containing the variable.
static std::string possibleDirections ()
Used to construct InputParameters.
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Static Public Attributes
static const Number OutOfMeshValue = -999999
Protected Types
enum MeshDivisionTransferUse { RESTRICTION , MATCH_DIVISION_INDEX , MATCH_SUBAPP_INDEX }
Matching enum for the mesh division behaviors.
Protected Member Functions
virtual void prepareEvaluationOfInterpValues (const unsigned int var_index) override
virtual void evaluateInterpValues (const std::vector< std::pair< Point, unsigned int > > &incoming_points, std::vector< std::pair< Real, Real > > &outgoing_vals) override
void extractLocalFromBoundingBoxes (std::vector< BoundingBox > &local_bboxes)
bool acceptPointInOriginMesh (unsigned int i_from, const std::vector< BoundingBox > &local_bboxes, const Point &pt, const unsigned int mesh_div, Real &distance) const
bool inMesh (const PointLocatorBase *const pl, const Point &pt) const
bool inBlocks (const std::set< SubdomainID > &blocks, const Elem *elem) const
virtual bool inBlocks (const std::set< SubdomainID > &blocks, const MooseMesh &mesh, const Elem *elem) const
bool inBlocks (const std::set< SubdomainID > &blocks, const MooseMesh &mesh, const Node *node) const
bool inBlocks (const std::set< SubdomainID > &blocks, const PointLocatorBase *const pl, const Point &pt) const
bool onBoundaries (const std::set< BoundaryID > &boundaries, const MooseMesh &mesh, const Node *node) const
bool onBoundaries (const std::set< BoundaryID > &boundaries, const MooseMesh &mesh, const Elem *elem) const
bool onBoundaries (const std::set< BoundaryID > &boundaries, const std::set< SubdomainID > &block_restriction, const MooseMesh &mesh, const PointLocatorBase *const pl, const Point &pt) const
bool acceptPointMeshDivision (const Point &pt, const unsigned int i_local, const unsigned int only_from_this_mesh_div) const
Whether a point lies inside the mesh division delineated by the MeshDivision object.
bool closestToPosition (unsigned int pos_index, const Point &pt) const
Whether a point is closest to a position at the index specified than any other position.
bool detectConflict (Real value_1, Real value_2, Real distance_1, Real distance_2) const
Detects whether two source values are valid and equidistant for a desired target location.
void registerConflict (unsigned int problem, dof_id_type dof_id, Point p, Real dist, bool local)
Register a potential value conflict, e.g.
virtual std::vector< VariableName > getFromVarNames () const override
Virtual function defining variables to be transferred.
virtual std::vector< AuxVariableName > getToVarNames () const override
Virtual function defining variables to transfer to.
bool performAdjustment (const PostprocessorValue &from, const PostprocessorValue &to) const
EquationSystems & getEquationSystem (FEProblemBase &problem, bool use_displaced) const
Returns the Problem's equation system, displaced or not Be careful! If you transfer TO a displaced system you will likely need a synchronization So most transfers reach the non-displaced system directly.
std::vector< unsigned int > getFromsPerProc ()
Return the number of "from" domains that each processor owns.
NumericVector< Real > & getTransferVector (unsigned int i_local, std::string var_name)
If we are transferring to a multiapp, return the appropriate solution vector.
unsigned int getGlobalSourceAppIndex (unsigned int i_from) const
Return the global app index from the local index in the "from-multiapp" transfer direction.
unsigned int getGlobalTargetAppIndex (unsigned int i_to) const
Return the global app index from the local index in the "to-multiapp" transfer direction.
unsigned int getLocalSourceAppIndex (unsigned int i_from) const
Return the local app index from the global index in the "from-multiapp" transfer direction We use the fact that global app indexes are consecutive on a given rank.
Point getPointInTargetAppFrame (const Point &p, unsigned int local_i_to, const std::string &phase) const
Get the target app point from a point in the reference frame.
void checkMultiAppExecuteOn ()
Helper method for checking the 'check_multiapp_execute_on' flag.
void checkVariable (const FEProblemBase &fe_problem, const VariableName &var_name, const std::string &param_name="") const
Helper for checking a problem for a variable.
void extendBoundingBoxes (const Real factor, std::vector< BoundingBox > &bboxes) const
Extends bounding boxes to avoid missing points.
template<typename T , typename... Args>
T & declareRestartableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
ManagedValue< T > declareManagedRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declares a piece of "managed" restartable data and initialize it.
template<typename T , typename... Args>
const T & getRestartableData (const std::string &data_name) const
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
template<typename T , typename... Args>
T & declareRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
T & declareRecoverableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "recoverable" and initialize it.
template<typename T , typename... Args>
T & declareRestartableDataWithObjectName (const std::string &data_name, const std::string &object_name, Args &&... args)
Declare a piece of data as "restartable".
template<typename T , typename... Args>
T & declareRestartableDataWithObjectNameWithContext (const std::string &data_name, const std::string &object_name, void *context, Args &&... args)
Declare a piece of data as "restartable".
std::string restartableName (const std::string &data_name) const
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level) const
Call to register a named section for timing.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level, const std::string &live_message, const bool print_dots=true) const
Call to register a named section for timing.
std::string timedSectionName (const std::string &section_name) const
std::vector< BoundingBox > getFromBoundingBoxes ()
Return the bounding boxes of all the "from" domains, including all the domains not local to this processor.
std::vector< BoundingBox > getFromBoundingBoxes (BoundaryID boundary_id)
Static Protected Member Functions
static void addBBoxFactorParam (InputParameters &params)
Add the bounding box factor parameter to the supplied input parameters.
static void transformBoundingBox (BoundingBox &box, const MultiAppCoordTransform &transform)
Transform a bounding box according to the transformations in the provided coordinate transformation object.
Protected Attributes
const std::vector< unsigned int > _from_var_components
Origin array/vector variable components.
const std::vector< unsigned int > _to_var_components
Target array/vector variable components.
const bool _use_bounding_boxes
Whether to use bounding boxes to determine the applications that may receive point requests then send value data, and at other various checks.
const bool _use_nearest_app
Whether to keep track of the distance from the requested point to the app position.
const Positions * _nearest_positions_obj
bool _source_app_must_contain_point
Whether the source app mesh must actually contain the points for them to be considered or whether the bounding box is enough.
std::set< SubdomainID > _from_blocks
Origin block(s) restriction.
std::set< SubdomainID > _to_blocks
Target block(s) restriction.
std::set< BoundaryID > _to_boundaries
Target boundary(ies) restriction.
std::set< BoundaryID > _from_boundaries
Origin boundary(ies) restriction.
std::vector< const MeshDivision * > _from_mesh_divisions
Division of the origin mesh.
std::vector< const MeshDivision * > _to_mesh_divisions
Division of the target mesh.
const MooseEnum & _from_mesh_division_behavior
How to use the origin mesh divisions to restrict the transfer.
const MooseEnum & _to_mesh_division_behavior
How to use the target mesh divisions to restrict the transfer.
const bool _elemental_boundary_restriction_on_sides
Whether elemental variable boundary restriction is considered by element side or element nodes.
std::vector< std::unique_ptr< PointLocatorBase > > _from_point_locators
Point locators, useful to examine point location with regards to domain restriction.
std::vector< unsigned int > _global_app_start_per_proc
First app each processor owns, indexed by processor If no app on the processor, will have a -1 for the app start instead.
bool _greedy_search
Whether or not a greedy strategy will be used If true, all the partitions will be checked for a given outgoing point.
const bool _search_value_conflicts
Whether to look for conflicts between origin points, multiple valid values for a target point.
const std::vector< VariableName > _from_var_names
Name of variables transferring from.
const std::vector< AuxVariableName > _to_var_names
Name of variables transferring to.
VariableName _from_var_name
This values are used if a derived class only supports one variable.
AuxVariableName _to_var_name
bool _preserve_transfer
If this transfer is going to conserve the physics.
std::vector< PostprocessorName > _from_postprocessors_to_be_preserved
Postprocessor evaluates an adjuster for the source physics.
std::vector< PostprocessorName > _to_postprocessors_to_be_preserved
Postprocessor evaluates an adjuster for the target physics.
std::shared_ptr< MultiApp > _multi_app
Deprecated class attribute for compatibility with the apps.
std::vector< FEProblemBase * > _to_problems
std::vector< FEProblemBase * > _from_problems
std::vector< EquationSystems * > _to_es
std::vector< EquationSystems * > _from_es
std::vector< MooseMesh * > _to_meshes
std::vector< MooseMesh * > _from_meshes
std::vector< Point > _to_positions
std::vector< Point > _from_positions
std::vector< std::unique_ptr< MultiAppCoordTransform > > _to_transforms
std::vector< std::unique_ptr< MultiAppCoordTransform > > _from_transforms
const bool _skip_coordinate_collapsing
Whether to skip coordinate collapsing (transformations of coordinates between applications using different frames of reference)
bool _displaced_source_mesh
True if displaced mesh is used for the source mesh, otherwise false.
bool _displaced_target_mesh
True if displaced mesh is used for the target mesh, otherwise false.
std::vector< unsigned int > _to_local2global_map
Given local app index, returns global app index.
std::vector< unsigned int > _from_local2global_map
Given local app index, returns global app index.
SubProblem & _subproblem
FEProblemBase & _fe_problem
SystemBase & _sys
THREAD_ID _tid
MultiMooseEnum _directions
The directions this Transfer is to be executed on.
const bool & _enabled
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
MooseApp & _app
The MOOSE application this is associated with.
const std::string & _type
The type of this class.
const std::string & _name
The name of this class, reference to value stored in InputParameters.
const InputParameters & _pars
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Factory & _factory
The Factory associated with the MooseApp.
ActionFactory & _action_factory
Builds Actions.
const ExecFlagEnum & _execute_enum
Execute settings for this object.
const ExecFlagType & _current_execute_flag
Reference to FEProblemBase.
MooseApp & _restartable_app
Reference to the application.
const std::string _restartable_system_name
The system name this object is in.
const THREAD_ID _restartable_tid
The thread ID for this object.
const bool _restartable_read_only
Flag for toggling read only status (see ReporterData)
MooseApp & _pg_moose_app
The MooseApp that owns the PerfGraph.
const std::string _prefix
A prefix to use for all sections.
MooseEnum _direction
MooseEnum _current_direction
Private Types
typedef std::unordered_map< processor_id_type, std::vector< std::pair< Point, unsigned int > > > ProcessorToPointVec
A map from pid to a set of points.
typedef std::unordered_map< processor_id_type, std::vector< PointInfo > > ProcessorToPointInfoVec
A map from pid to a set of point info.
typedef std::vector< std::unordered_map< dof_id_type, InterpInfo > > DofobjectToInterpValVec
A vector, indexed by to-problem id, of maps from dof object to interpolation values.
typedef PointIndexedMap InterpCache
A map from Point to interpolation values NOTE: this is not an asynchronous cache.
typedef std::vector< InterpCache > InterpCaches
A vector of such caches, indexed by to_problem.
Private Member Functions
bool usesMooseAppCoordTransform () const override
Whether this transfer handles non-translation-based transformations, e.g.
void buildMeshFunctions (const unsigned int var_index, std::vector< MeshFunction > &local_meshfuns)
void evaluateInterpValuesWithMeshFunctions (const std::vector< BoundingBox > &local_bboxes, std::vector< MeshFunction > &local_meshfuns, const std::vector< std::pair< Point, unsigned int > > &incoming_points, std::vector< std::pair< Real, Real > > &outgoing_vals)
void prepareToTransfer ()
Initialize supporting attributes like bounding boxes, processor app indexes etc.
void transferVariable (unsigned int i)
Performs the transfer for the variable of index i.
void extractOutgoingPoints (const unsigned int var_index, ProcessorToPointVec &outgoing_points)
void locatePointReceivers (const Point point, std::set< processor_id_type > &processors)
void cacheIncomingInterpVals (processor_id_type pid, const unsigned int var_index, std::vector< PointInfo > &pointInfoVec, const std::vector< std::pair< Point, unsigned int > > &point_requests, const std::vector< std::pair< Real, Real > > &incoming_vals, DofobjectToInterpValVec &dofobject_to_valsvec, InterpCaches &interp_caches, InterpCaches &distance_caches)
void examineReceivedValueConflicts (const unsigned int var_index, const DofobjectToInterpValVec &dofobject_to_valsvec, const InterpCaches &distance_caches)
Remove potential value conflicts that did not materialize because another source was closer Several equidistant valid values were received, but they were not closest.
void examineLocalValueConflicts (const unsigned int var_index, const DofobjectToInterpValVec &dofobject_to_valsvec, const InterpCaches &distance_caches)
Remove potential value conflicts that did not materialize because another source was closer Several equidistant valid values were found when computing values to send, but they were not closest, another value got selected.
void outputValueConflicts (const unsigned int var_index, const DofobjectToInterpValVec &dofobject_to_valsvec, const InterpCaches &distance_caches)
Report on conflicts between overlapping child apps, equidistant origin points etc.
void setSolutionVectorValues (const unsigned int var_index, const DofobjectToInterpValVec &dofobject_to_valsvec, const InterpCaches &interp_caches)
void cacheOutgoingPointInfo (const Point point, const dof_id_type dof_object_id, const unsigned int problem_id, ProcessorToPointVec &outgoing_points)
Real bboxMinDistance (const Point &p, const BoundingBox &bbox) const
Compute minimum distance.
Real bboxMaxDistance (const Point &p, const BoundingBox &bbox) const
Compute max distance.
Point getMaxToProblemsBBoxDimensions () const
Obtains the max dimensions to scale all points in the mesh.
std::vector< BoundingBox > getRestrictedFromBoundingBoxes () const
Get from bounding boxes for given domains and boundaries.
std::vector< unsigned int > getGlobalStartAppPerProc () const
Get global index for the first app each processes owns Requires a global communication, must be called on every domain simultaneously.
void adjustTransferredSolution (FEProblemBase *from_problem, PostprocessorName &from_postprocessor, FEProblemBase &to_problem, PostprocessorName &to_postprocessor)
void adjustTransferredSolutionNearestPoint (unsigned int i, FEProblemBase *from_problem, PostprocessorName &from_postprocessor, FEProblemBase &to_problem, PostprocessorName &to_postprocessor)
void getFromMultiAppInfo ()
void getToMultiAppInfo ()
template<typename... Args>
std::string paramErrorMsg (const std::string &param, Args... args) const
RestartableDataValue & registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const
Helper function for actually registering the restartable data.
void registerRestartableNameWithFilterOnApp (const std::string &name, Moose::RESTARTABLE_FILTER filter)
Helper function for actually registering the restartable data.
template<typename T , typename... Args>
RestartableData< T > & declareRestartableDataHelper (const std::string &data_name, void *context, Args &&... args) const
Helper function for declaring restartable data.
Private Attributes
std::vector< BoundingBox > _local_bboxes
std::vector< MeshFunction > _local_meshfuns
std::vector< MooseVariableFieldBase * > _to_variables
The target variables.
unsigned int _var_size
The number of variables to transfer.
bool _error_on_miss
Error out when some points can not be located.
const Real _default_extrapolation_value
Value to use when no received data is valid for a target location.
Real _bbox_factor
How much we should relax bounding boxes.
std::vector< Real > _fixed_bbox_size
Set the bounding box sizes manually.
std::vector< unsigned int > _froms_per_proc
Number of source/from applications per processor. This vector is indexed by processor id.
std::vector< BoundingBox > _from_bboxes
Bounding boxes for all source applications.
ProcessorToPointInfoVec _processor_to_pointInfoVec
A map from processor to pointInfo vector.
std::vector< std::tuple< unsigned int, dof_id_type, Point, Real > > _local_conflicts
Keeps track of all local equidistant points to requested points, creating an indetermination in which values should be sent for that request We keep the origin problem ID, the dof ID, the point, and the distance origin-target If using nearest-positions the origin problem ID is not set.
std::vector< std::tuple< unsigned int, dof_id_type, Point, Real > > _received_conflicts
Keeps track of all received conflicts.
bool _use_nearestpoint_pps
Whether to use a nearest point UserObject to obtain the conservation factor.
bool _allow_skipped_adjustment
Whether the adjustment may be skipped when the postprocessor values are 0 / of different signs.
std::shared_ptr< MultiApp > _from_multi_app
The MultiApps this Transfer is transferring data to or from.
std::shared_ptr< MultiApp > _to_multi_app
std::unique_ptr< MooseAppCoordTransform > _from_moose_app_transform
The moose coordinate transformation object describing rotations, scaling, and coordinate system of the from application.
std::unique_ptr< MooseAppCoordTransform > _to_moose_app_transform
The moose coordinate transformation object describing rotations, scaling, and coordinate system of the to application.
const MooseBase *const _moose_base
The MooseBase object that inherits this class.
const MooseObject & _parent
ExecFlagEnum _empty_execute_enum
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
const RestartableDataMapName _metaname
Restartable metadata name.
std::string _restartable_name
The name of the object.
Detailed Description
Evaluates origin shape functions to compute the target variables.
Definition at line 19 of file MultiAppGeneralFieldShapeEvaluationTransfer.h.
Member Typedef Documentation
DofobjectToInterpValVec
typedef std::vector<std::unordered_map<dof_id_type, InterpInfo> > MultiAppGeneralFieldTransfer::DofobjectToInterpValVec private inherited
A vector, indexed by to-problem id, of maps from dof object to interpolation values.
Definition at line 318 of file MultiAppGeneralFieldTransfer.h.
InterpCache
typedef PointIndexedMap MultiAppGeneralFieldTransfer::InterpCache private inherited
A map from Point to interpolation values NOTE: this is not an asynchronous cache.
It is built to completion during the transfer and used as a whole to reconstruct the target variable
Definition at line 323 of file MultiAppGeneralFieldTransfer.h.
InterpCaches
typedef std::vector<InterpCache> MultiAppGeneralFieldTransfer::InterpCaches private inherited
A vector of such caches, indexed by to_problem.
Definition at line 326 of file MultiAppGeneralFieldTransfer.h.
ProcessorToPointInfoVec
typedef std::unordered_map<processor_id_type, std::vector<PointInfo> > MultiAppGeneralFieldTransfer::ProcessorToPointInfoVec private inherited
A map from pid to a set of point info.
Definition at line 315 of file MultiAppGeneralFieldTransfer.h.
ProcessorToPointVec
typedef std::unordered_map<processor_id_type, std::vector<std::pair<Point, unsigned int> > > MultiAppGeneralFieldTransfer::ProcessorToPointVec private inherited
A map from pid to a set of points.
Definition at line 297 of file MultiAppGeneralFieldTransfer.h.
Member Enumeration Documentation
DIRECTION
enum Transfer::DIRECTION inherited
Enumerator
TO_MULTIAPP
FROM_MULTIAPP
BETWEEN_MULTIAPP
Definition at line 68 of file Transfer.h.
  {
    TO_MULTIAPP,
    FROM_MULTIAPP,
    BETWEEN_MULTIAPP
  };
MeshDivisionTransferUse
enum MultiAppGeneralFieldTransfer::MeshDivisionTransferUse protected inherited
Matching enum for the mesh division behaviors.
Enumerator
RESTRICTION
MATCH_DIVISION_INDEX
MATCH_SUBAPP_INDEX
Definition at line 242 of file MultiAppGeneralFieldTransfer.h.
  {
    RESTRICTION,
    MATCH_DIVISION_INDEX,
    MATCH_SUBAPP_INDEX
  };
Constructor & Destructor Documentation
MultiAppGeneralFieldShapeEvaluationTransfer()
MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer (const InputParameters & parameters)
Definition at line 42 of file MultiAppGeneralFieldShapeEvaluationTransfer.C.
  : MultiAppGeneralFieldTransfer(parameters)
{
  // Nearest point isn't well defined for sending app-based data from main app to a multiapp
  if (_nearest_positions_obj && isParamValid("to_multi_app") && !isParamValid("from_multi_app"))
    paramError("use_nearest_position",
               "Cannot use nearest-position algorithm when sending from the main application");
  // There's not much use for matching cell divisions when the locations have to match exactly
  // to get a valid source variable value anyway
  if (_from_mesh_division_behavior == MeshDivisionTransferUse::MATCH_DIVISION_INDEX ||
      _to_mesh_division_behavior == MeshDivisionTransferUse::MATCH_DIVISION_INDEX)
    paramError("from_mesh_division_usage",
               "Matching division index is disabled for shape evaluation transfers");
}
Member Function Documentation
acceptPointInOriginMesh()
bool MultiAppGeneralFieldTransfer::acceptPointInOriginMesh (unsigned int i_from, const std::vector< BoundingBox > & local_bboxes, const Point & pt, const unsigned int mesh_div, Real & distance) const protected inherited
Definition at line 1445 of file MultiAppGeneralFieldTransfer.C.
{
  if (_use_bounding_boxes && !local_bboxes[i_from].contains_point(pt))
    return false;
  else
  {
    auto * pl = _from_point_locators[i_from].get();
    const auto from_global_num = getGlobalSourceAppIndex(i_from);
    const auto transformed_pt = _from_transforms[from_global_num]->mapBack(pt);
    // Check point against source block restriction
    if (!_from_blocks.empty() && !inBlocks(_from_blocks, pl, transformed_pt))
      return false;
    // Check point against source boundary restriction. Block restriction will speed up the search
    if (!_from_boundaries.empty() &&
        !onBoundaries(_from_boundaries, _from_blocks, *_from_meshes[i_from], pl, transformed_pt))
      return false;
    // Check point against the source mesh division
    if ((!_from_mesh_divisions.empty() || !_to_mesh_divisions.empty()) &&
        !acceptPointMeshDivision(transformed_pt, i_from, only_from_mesh_div))
      return false;
    // Get nearest position (often a subapp position) for the target point
    // We want values from the child app that is closest to the same position as the target
    Point nearest_position_source;
    if (_nearest_positions_obj)
    {
      const bool initial = _fe_problem.getCurrentExecuteOnFlag() == EXEC_INITIAL;
      // The search for the nearest position is done in the reference frame
      const Point nearest_position = _nearest_positions_obj->getNearestPosition(pt, initial);
      nearest_position_source = _nearest_positions_obj->getNearestPosition(
          (*_from_transforms[from_global_num])(Point(0, 0, 0)), initial);
      if (!_skip_coordinate_collapsing &&
          _from_transforms[from_global_num]->hasNonTranslationTransformation())
        mooseError("Rotation and scaling currently unsupported with nearest positions transfer.");
      // Source (usually app position) is not closest to the same positions as the target, dont
      // send values
      if (nearest_position != nearest_position_source)
        return false;
      // Set the distance as the distance from the nearest position to the target point
      distance = (pt - nearest_position_source).norm();
    }
    // Check that the app actually contains the origin point
    // We dont need to check if we already found it in a block or a boundary
    if (_from_blocks.empty() && _from_boundaries.empty() && _source_app_must_contain_point &&
        !inMesh(pl, transformed_pt))
      return false;
  }
  return true;
}
Referenced by evaluateInterpValuesWithMeshFunctions(), and MultiAppGeneralFieldUserObjectTransfer::evaluateInterpValuesWithUserObjects().
acceptPointMeshDivision()
bool MultiAppGeneralFieldTransfer::acceptPointMeshDivision (const Point & pt, const unsigned int i_local, const unsigned int only_from_this_mesh_div) const protected inherited
Whether a point lies inside the mesh division delineated by the MeshDivision object.
Parameters
pt point to examine, in the local coordinates (source frame for from_direction=true)
i_local the index of the problem to consider, holding the mesh division to examine
only_from_this_mesh_div a mesh division index that must be matched when the to/from_mesh_division_behavior for the direction examined is MATCH_DIVISION/SUBAPP_INDEX It is ignored otherwise
Definition at line 1625 of file MultiAppGeneralFieldTransfer.C.
{
  // This routine can also be called to examine if the to_mesh_division index matches the current
  // source subapp index
  unsigned int source_mesh_div = MooseMeshDivision::INVALID_DIVISION_INDEX - 1;
  if (!_from_mesh_divisions.empty())
    source_mesh_div = _from_mesh_divisions[i_local]->divisionIndex(pt);
  // If the point is not indexed in the source division
  if (!_from_mesh_divisions.empty() && source_mesh_div == MooseMeshDivision::INVALID_DIVISION_INDEX)
    return false;
  // If the point is not the at the same index in the target and the origin meshes, reject
  else if ((_from_mesh_division_behavior == MeshDivisionTransferUse::MATCH_DIVISION_INDEX ||
            _to_mesh_division_behavior == MeshDivisionTransferUse::MATCH_DIVISION_INDEX) &&
           source_mesh_div != only_from_this_mesh_div)
    return false;
  // If the point is at a certain division index that is not the same as the index of the subapp
  // we wanted the information to be from for that point, reject
  else if (_from_mesh_division_behavior == MeshDivisionTransferUse::MATCH_SUBAPP_INDEX &&
           source_mesh_div != only_from_this_mesh_div)
    return false;
  else if (_to_mesh_division_behavior == MeshDivisionTransferUse::MATCH_SUBAPP_INDEX &&
           only_from_this_mesh_div != getGlobalSourceAppIndex(i_local))
    return false;
  else
    return true;
}
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh().
addBBoxFactorParam()
void MultiAppTransfer::addBBoxFactorParam (InputParameters & params) static protected inherited
Add the bounding box factor parameter to the supplied input parameters.
Definition at line 54 of file MultiAppTransfer.C.
{
  params.addRangeCheckedParam<Real>(
      "bbox_factor",
      1 + TOLERANCE,
      "bbox_factor>0",
      "Multiply bounding box width (in all directions) by the prescribed factor. Values less than "
      "1 will shrink the bounding box; values greater than 1 will enlarge the bounding box. It is "
      "generally not advised to ever shrink the bounding box. On the other hand it may be helpful "
      "to enlarge the bounding box. Larger bounding boxes will lead to more accurate determination "
      "of the closest node/element with the tradeoff of more communication.");
}
Referenced by MultiAppNearestNodeTransfer::validParams(), MultiAppProjectionTransfer::validParams(), and MultiAppShapeEvaluationTransfer::validParams().
addSkipCoordCollapsingParam()
void MultiAppTransfer::addSkipCoordCollapsingParam (InputParameters & params) static inherited
Add the option to skip coordinate collapsing in coordinate transformation operations.
Definition at line 68 of file MultiAppTransfer.C.
{
  params.addParam<bool>(
      "skip_coordinate_collapsing",
      true,
      "Whether to skip coordinate collapsing (translation and rotation are still performed, only "
      "XYZ, RZ etc collapsing is skipped) when performing mapping and inverse "
      "mapping coordinate transformation operations. This parameter should only "
      "be set by users who really know what they're doing.");
  params.addParamNamesToGroup("skip_coordinate_collapsing", "Advanced");
}
Referenced by MultiAppTransfer::validParams().
adjustTransferredSolution()
void MultiAppConservativeTransfer::adjustTransferredSolution (FEProblemBase * from_problem, PostprocessorName & from_postprocessor, FEProblemBase & to_problem, PostprocessorName & to_postprocessor) private inherited
Definition at line 398 of file MultiAppConservativeTransfer.C.
{
  PostprocessorValue from_adjuster = 0;
  if (from_problem)
    from_adjuster = from_problem->getPostprocessorValueByName(from_postprocessor);
  else
    from_adjuster = 0;
  /* Everyone on the parent side should know this value; use it to scale the solution */
  if (_current_direction == FROM_MULTIAPP)
  {
    /* In this case, only one subapp has value, and other subapps' must be zero.
     *  We should see the maximum value.
     */
    PostprocessorValue from_adjuster_tmp = from_adjuster;
    comm().max(from_adjuster);
    /* We may have a negative value, and let us try it again  */
    if (MooseUtils::absoluteFuzzyLessEqual(from_adjuster, 0.))
    {
      comm().min(from_adjuster_tmp);
      from_adjuster = from_adjuster_tmp;
    }
  }
  // Compute to-postprocessor to have the adjuster
  to_problem.computeUserObjectByName(EXEC_TRANSFER, Moose::POST_AUX, to_postprocessor);
  // Now we should have the right adjuster based on the transferred solution
  const auto to_adjuster = to_problem.getPostprocessorValueByName(to_postprocessor);
  // decide if the adjustment should be performed
  if (!performAdjustment(from_adjuster, to_adjuster))
    return;
  auto & to_var = to_problem.getVariable(
      0, _to_var_name, Moose::VarKindType::VAR_ANY, Moose::VarFieldType::VAR_FIELD_STANDARD);
  auto & to_sys = to_var.sys().system();
  auto var_num = to_sys.variable_number(_to_var_name);
  auto sys_num = to_sys.number();
  auto * pps =
      dynamic_cast<const BlockRestrictable *>(&(to_problem.getUserObjectBase(to_postprocessor)));
  auto & to_solution = to_var.sys().solution();
  auto & to_mesh = to_problem.mesh().getMesh();
  auto & moose_mesh = to_problem.mesh();
  bool is_nodal = to_sys.variable_type(var_num).family == LAGRANGE;
  if (is_nodal)
  {
    for (const auto & node : to_mesh.local_node_ptr_range())
    {
      // Skip this node if the variable has no dofs at it.
      if (node->n_dofs(sys_num, var_num) < 1)
        continue;
      bool scale_current_node = false;
      /* If we care about block IDs */
      if (pps)
      {
        auto & blockids = pps->blockIDs();
        auto & node_to_elem_map = moose_mesh.nodeToElemMap();
        auto neighbor_elements = node_to_elem_map.find(node->id());
        for (auto element : neighbor_elements->second)
        {
          auto & elem = to_mesh.elem_ref(element);
          if (blockids.find(elem.subdomain_id()) != blockids.end())
          {
            scale_current_node = true;
            break;
          }
        }
      }
      else
      {
        scale_current_node = true;
      }
      /* Need to scale this node */
      if (scale_current_node)
      {
        dof_id_type dof = node->dof_number(sys_num, var_num, 0);
        to_solution.set(dof, (from_adjuster / to_adjuster) * to_solution(dof));
      }
    }
  }
  else
  {
    for (auto & elem : as_range(to_mesh.local_elements_begin(), to_mesh.local_elements_end()))
    {
      // Skip this element if the variable has no dofs at it.
      if (elem->n_dofs(sys_num, var_num) < 1)
        continue;
      bool scale_current_element = false;
      if (pps)
      {
        auto & blockids = pps->blockIDs();
        if (blockids.find(elem->subdomain_id()) != blockids.end())
        {
          scale_current_element = true;
        }
      }
      else
      {
        scale_current_element = true;
      }
      if (scale_current_element)
      {
        unsigned int n_comp = elem->n_comp(sys_num, var_num);
        for (unsigned int offset = 0; offset < n_comp; offset++)
        {
          dof_id_type dof = elem->dof_number(sys_num, var_num, offset);
          to_solution.set(dof, (from_adjuster / to_adjuster) * to_solution(dof));
        }
      }
    }
  }
  to_solution.close();
  to_sys.update();
  // Compute again so that the post-processor has the value with the updated solution
  to_problem.computeUserObjectByName(EXEC_TRANSFER, Moose::POST_AUX, to_postprocessor);
}
Referenced by MultiAppConservativeTransfer::postExecute().
adjustTransferredSolutionNearestPoint()
void MultiAppConservativeTransfer::adjustTransferredSolutionNearestPoint (unsigned int i, FEProblemBase * from_problem, PostprocessorName & from_postprocessor, FEProblemBase & to_problem, PostprocessorName & to_postprocessor) private inherited
Definition at line 280 of file MultiAppConservativeTransfer.C.
{
  PostprocessorValue from_adjuster = 0;
  if (from_problem && _current_direction == FROM_MULTIAPP)
    from_adjuster = from_problem->getPostprocessorValueByName(from_postprocessor);
  else
    from_adjuster = 0;
  /* Everyone on the parent application side should know this value; use it to scale the solution */
  if (_current_direction == FROM_MULTIAPP)
  {
    /* In this case, only one subapp has value, and other subapps' must be zero.
     *  We should see the maximum value.
     */
    PostprocessorValue from_adjuster_tmp = from_adjuster;
    comm().max(from_adjuster);
    /* We may have a negative value */
    if (MooseUtils::absoluteFuzzyLessEqual(from_adjuster, 0.))
    {
      comm().min(from_adjuster_tmp);
      from_adjuster = from_adjuster_tmp;
    }
  }
  PostprocessorValue to_adjuster = 0;
  // Compute to-postprocessor to have the adjuster
  if (_current_direction == TO_MULTIAPP)
  {
    to_problem.computeUserObjectByName(EXEC_TRANSFER, Moose::POST_AUX, to_postprocessor);
    to_adjuster = to_problem.getPostprocessorValueByName(to_postprocessor);
  }
  auto & to_var = to_problem.getVariable(
      0, _to_var_name, Moose::VarKindType::VAR_ANY, Moose::VarFieldType::VAR_FIELD_STANDARD);
  auto & to_sys = to_var.sys().system();
  auto var_num = to_sys.variable_number(_to_var_name);
  auto sys_num = to_sys.number();
  auto & pps = static_cast<const NearestPointIntegralVariablePostprocessor &>(
      _current_direction == FROM_MULTIAPP ? (to_problem.getUserObjectBase(to_postprocessor))
                                          : (from_problem->getUserObjectBase(from_postprocessor)));
  auto & to_solution = to_var.sys().solution();
  auto & to_mesh = to_problem.mesh().getMesh();
  bool is_nodal = to_sys.variable_type(var_num).family == LAGRANGE;
  if (is_nodal)
  {
    for (const auto & node : to_mesh.local_node_ptr_range())
    {
      // Skip this node if the variable has no dofs at it.
      if (node->n_dofs(sys_num, var_num) < 1)
        continue;
      Real scale = 1;
      if (_current_direction == FROM_MULTIAPP)
      {
        auto ii = pps.nearestPointIndex(*node);
        if (ii != i || !performAdjustment(from_adjuster, pps.userObjectValue(i)))
          continue;
        scale = from_adjuster / pps.userObjectValue(i);
      }
      else
      {
        if (!performAdjustment(pps.userObjectValue(i), to_adjuster))
          continue;
        scale = pps.userObjectValue(i) / to_adjuster;
      }
      /* Need to scale this node */
      dof_id_type dof = node->dof_number(sys_num, var_num, 0);
      to_solution.set(dof, scale * to_solution(dof));
    }
  }
  else
  {
    for (auto & elem : as_range(to_mesh.local_elements_begin(), to_mesh.local_elements_end()))
    {
      // Skip this element if the variable has no dofs at it.
      if (elem->n_dofs(sys_num, var_num) < 1)
        continue;
      Real scale = 1;
      if (_current_direction == FROM_MULTIAPP)
      {
        unsigned int ii = pps.nearestPointIndex(elem->vertex_average());
        if (ii != i || !performAdjustment(from_adjuster, pps.userObjectValue(i)))
          continue;
        scale = from_adjuster / pps.userObjectValue(i);
      }
      else
      {
        if (!performAdjustment(pps.userObjectValue(i), to_adjuster))
          continue;
        scale = pps.userObjectValue(i) / to_adjuster;
      }
      dof_id_type dof = elem->dof_number(sys_num, var_num, 0);
      to_solution.set(dof, scale * to_solution(dof));
    }
  }
  to_solution.close();
  to_sys.update();
  // Compute the to-postprocessor again so that it has the right value with the updated solution
  if (_current_direction == TO_MULTIAPP)
    to_problem.computeUserObjectByName(EXEC_TRANSFER, Moose::POST_AUX, to_postprocessor);
}
Referenced by MultiAppConservativeTransfer::postExecute().
bboxMaxDistance()
Real MultiAppGeneralFieldTransfer::bboxMaxDistance (const Point & p, const BoundingBox & bbox) const private inherited
Compute max distance.
Parameters
p the point of interest
bbox the bounding box to find the maximum distance from
Definition at line 1666 of file MultiAppGeneralFieldTransfer.C.
{
  std::array<Point, 2> source_points = {{bbox.first, bbox.second}};
  std::array<Point, 8> all_points;
  for (unsigned int x = 0; x < 2; x++)
    for (unsigned int y = 0; y < 2; y++)
      for (unsigned int z = 0; z < 2; z++)
        all_points[x + 2 * y + 4 * z] =
            Point(source_points[x](0), source_points[y](1), source_points[z](2));
  Real max_distance = 0.;
  for (unsigned int i = 0; i < 8; i++)
  {
    Real distance = (p - all_points[i]).norm();
    if (distance > max_distance)
      max_distance = distance;
  }
  return max_distance;
}
Referenced by MultiAppGeneralFieldTransfer::locatePointReceivers().
bboxMinDistance()
Real MultiAppGeneralFieldTransfer::bboxMinDistance (const Point & p, const BoundingBox & bbox) const private inherited
Compute minimum distance.
Parameters
p the point of interest
bbox the bounding box to find the minimum distance from
Definition at line 1690 of file MultiAppGeneralFieldTransfer.C.
{
  std::array<Point, 2> source_points = {{bbox.first, bbox.second}};
  std::array<Point, 8> all_points;
  for (unsigned int x = 0; x < 2; x++)
    for (unsigned int y = 0; y < 2; y++)
      for (unsigned int z = 0; z < 2; z++)
        all_points[x + 2 * y + 4 * z] =
            Point(source_points[x](0), source_points[y](1), source_points[z](2));
  Real min_distance = std::numeric_limits<Real>::max();
  for (unsigned int i = 0; i < 8; i++)
  {
    Real distance = (p - all_points[i]).norm();
    if (distance < min_distance)
      min_distance = distance;
  }
  return min_distance;
}
Referenced by MultiAppGeneralFieldTransfer::locatePointReceivers().
buildMeshFunctions()
void MultiAppGeneralFieldShapeEvaluationTransfer::buildMeshFunctions (const unsigned int var_index, std::vector< MeshFunction > & local_meshfuns) private
Definition at line 72 of file MultiAppGeneralFieldShapeEvaluationTransfer.C.
{
  local_meshfuns.reserve(_from_problems.size());
  // Construct a local mesh function for each origin problem
  for (unsigned int i_from = 0; i_from < _from_problems.size(); ++i_from)
  {
    FEProblemBase & from_problem = *_from_problems[i_from];
    MooseVariableFieldBase & from_var =
        from_problem.getVariable(0,
                                 _from_var_names[var_index],
                                 Moose::VarKindType::VAR_ANY,
                                 Moose::VarFieldType::VAR_FIELD_ANY);
    System & from_sys = from_var.sys().system();
    unsigned int from_var_num = from_sys.variable_number(getFromVarName(var_index));
    local_meshfuns.emplace_back(getEquationSystem(from_problem, _displaced_source_mesh),
                                *from_sys.current_local_solution,
                                from_sys.get_dof_map(),
                                from_var_num);
    local_meshfuns.back().init();
    local_meshfuns.back().enable_out_of_mesh_mode(GeneralFieldTransfer::BetterOutOfMeshValue);
  }
}
Referenced by prepareEvaluationOfInterpValues().
cacheIncomingInterpVals()
void MultiAppGeneralFieldTransfer::cacheIncomingInterpVals (processor_id_type pid, const unsigned int var_index, std::vector< PointInfo > & pointInfoVec, const std::vector< std::pair< Point, unsigned int > > & point_requests, const std::vector< std::pair< Real, Real > > & incoming_vals, DofobjectToInterpValVec & dofobject_to_valsvec, InterpCaches & interp_caches, InterpCaches & distance_caches) private inherited
Definition at line 827 of file MultiAppGeneralFieldTransfer.C.
{
  mooseAssert(pointInfoVec.size() == incoming_vals.size(),
              "Number of dof objects does not equal to the number of incoming values");
  dof_id_type val_offset = 0;
  for (const auto & pointinfo : pointInfoVec)
  {
    // Retrieve target information from cached point infos
    const auto problem_id = pointinfo.problem_id;
    const auto dof_object_id = pointinfo.dof_object_id;
    auto & fe_type = _to_variables[var_index]->feType();
    bool is_nodal = _to_variables[var_index]->isNodal();
    // In the higher order elemental variable case, we receive point values, not nodal or
    // elemental. We use an InterpCache to store the values. The distance_cache is necessary to
    // choose between multiple origin problems sending values. This code could be unified with the
    // lower order order case by using the dofobject_to_valsvec
    if (fe_type.order > CONSTANT && !is_nodal)
    {
      // Cache solution on target mesh in its local frame of reference
      InterpCache & value_cache = interp_caches[problem_id];
      InterpCache & distance_cache = distance_caches[problem_id];
      Point p = _to_transforms[getGlobalTargetAppIndex(problem_id)]->mapBack(
          point_requests[val_offset].first);
      const Number val = incoming_vals[val_offset].first;
      // Initialize distance to be able to compare
      if (!distance_cache.hasKey(p))
        distance_cache[p] = std::numeric_limits<Real>::max();
      // We should only have one closest value for each variable at any given point.
      // While there are shared Qps, on vertices for higher order variables usually,
      // the generic projector only queries each point once
      if (_search_value_conflicts && !GeneralFieldTransfer::isBetterOutOfMeshValue(val) &&
          value_cache.hasKey(p) != 0 && !MooseUtils::absoluteFuzzyEqual(value_cache[p], val) &&
          MooseUtils::absoluteFuzzyEqual(distance_cache[p], incoming_vals[val_offset].second))
        registerConflict(problem_id, dof_object_id, p, incoming_vals[val_offset].second, false);
      if ((!GeneralFieldTransfer::isBetterOutOfMeshValue(val) || _use_nearest_app) &&
          MooseUtils::absoluteFuzzyGreaterThan(distance_cache[p], incoming_vals[val_offset].second))
      {
        // NOTE: We store the distance as well as the value. We really only need the
        // value to construct the variable, but the distance is used to make decisions in nearest
        // node schemes on which value to use
        value_cache[p] = val;
        distance_cache[p] = incoming_vals[val_offset].second;
      }
    }
    else
    {
      // Using the dof object pointer, so we can handle
      // both element and node using the same code
#ifndef NDEBUG
      auto var_num = _to_variables[var_index]->number();
      auto & to_sys = _to_variables[var_index]->sys();
      const MeshBase & to_mesh = _to_problems[problem_id]->mesh(_displaced_target_mesh).getMesh();
      const DofObject * dof_object_ptr = nullptr;
      const auto sys_num = to_sys.number();
      // It is a node
      if (is_nodal)
        dof_object_ptr = to_mesh.node_ptr(dof_object_id);
      // It is an element
      else
        dof_object_ptr = to_mesh.elem_ptr(dof_object_id);
      // We should only be supporting nodal and constant elemental
      // variables in this code path; if we see multiple DoFs on one
      // object we should have been using GenericProjector
      mooseAssert(dof_object_ptr->n_dofs(sys_num, var_num) == 1,
                  "Unexpectedly found " << dof_object_ptr->n_dofs(sys_num, var_num)
                                        << "dofs instead of 1");
#endif
      auto & dofobject_to_val = dofobject_to_valsvec[problem_id];
      // Check if we visited this dof object earlier
      auto values_ptr = dofobject_to_val.find(dof_object_id);
      // We did not visit this
      if (values_ptr == dofobject_to_val.end())
      {
        // Values for this dof object
        auto & val = dofobject_to_val[dof_object_id];
        // Interpolation value
        val.interp = incoming_vals[val_offset].first;
        // Where this value came from
        val.pid = pid;
        // Distance
        val.distance = incoming_vals[val_offset].second;
      }
      else
      {
        auto & val = values_ptr->second;
        // Look for value conflicts
        if (detectConflict(val.interp,
                           incoming_vals[val_offset].first,
                           val.distance,
                           incoming_vals[val_offset].second))
        {
          // Keep track of distance and value
          const Point p =
              getPointInTargetAppFrame(point_requests[val_offset].first,
                                       problem_id,
                                       "Registration of received equi-distant value conflict");
          registerConflict(problem_id, dof_object_id, p, incoming_vals[val_offset].second, false);
        }
        // We adopt values that are, in order of priority
        // - valid
        // - closest distance
        // - the smallest rank with the same distance
        if (!GeneralFieldTransfer::isBetterOutOfMeshValue(incoming_vals[val_offset].first) &&
            (MooseUtils::absoluteFuzzyGreaterThan(val.distance, incoming_vals[val_offset].second) ||
             ((val.pid > pid) &&
              MooseUtils::absoluteFuzzyEqual(val.distance, incoming_vals[val_offset].second))))
        {
          val.interp = incoming_vals[val_offset].first;
          val.pid = pid;
          val.distance = incoming_vals[val_offset].second;
        }
      }
    }
    // Move it to next position
    val_offset++;
  }
}
Referenced by MultiAppGeneralFieldTransfer::transferVariable().
cacheOutgoingPointInfo()
void MultiAppGeneralFieldTransfer::cacheOutgoingPointInfo (const Point point, const dof_id_type dof_object_id, const unsigned int problem_id, ProcessorToPointVec & outgoing_points) private inherited
Definition at line 628 of file MultiAppGeneralFieldTransfer.C.
{
  std::set<processor_id_type> processors;
  // Find which processors will receive point data so they can send back value data
  // The list can be larger than needed, depending on the heuristic / algorithm used to make
  // the call on whether a processor (and the apps it runs) should be involved
  processors.clear();
  locatePointReceivers(point, processors);
  // We need to send this location data to these processors so they can send back values
  for (const auto pid : processors)
  {
    // Select which from_mesh_division the source data must come from for this point
    unsigned int required_source_division = 0;
    if (_from_mesh_division_behavior == MeshDivisionTransferUse::MATCH_SUBAPP_INDEX)
      required_source_division = getGlobalTargetAppIndex(problem_id);
    else if (_from_mesh_division_behavior == MeshDivisionTransferUse::MATCH_DIVISION_INDEX ||
             _to_mesh_division_behavior == MeshDivisionTransferUse::MATCH_DIVISION_INDEX ||
             _to_mesh_division_behavior == MeshDivisionTransferUse::MATCH_SUBAPP_INDEX)
      required_source_division = _to_mesh_divisions[problem_id]->divisionIndex(
          _to_transforms[getGlobalTargetAppIndex(problem_id)]->mapBack(point));
    // Skip if we already know we don't want the point
    if (required_source_division == MooseMeshDivision::INVALID_DIVISION_INDEX)
      continue;
    // Store outgoing information for every source process
    outgoing_points[pid].push_back(std::pair<Point, unsigned int>(point, required_source_division));
    // Store point information locally for processing received data
    // We can use these information when insert values to solution vector
    PointInfo pointinfo;
    pointinfo.problem_id = problem_id;
    pointinfo.dof_object_id = dof_object_id;
    _processor_to_pointInfoVec[pid].push_back(pointinfo);
  }
}
Referenced by MultiAppGeneralFieldTransfer::extractOutgoingPoints().
checkMultiAppExecuteOn()
void MultiAppTransfer::checkMultiAppExecuteOn () protected inherited
Helper method for checking the 'check_multiapp_execute_on' flag.
This method was added to allow the check to be delayed by child classes, see StochasticToolsTransfer for an example.
Definition at line 164 of file MultiAppTransfer.C.
{
  if (_from_multi_app && !_to_multi_app)
    if (getExecuteOnEnum() != _from_multi_app->getExecuteOnEnum())
      mooseDoOnce(
          mooseWarning("MultiAppTransfer execute_on flags do not match associated from_multi_app "
                       "execute_on flags"));
  if (_to_multi_app && !_from_multi_app)
    if (getExecuteOnEnum() != _to_multi_app->getExecuteOnEnum())
      mooseDoOnce(
          mooseWarning("MultiAppTransfer execute_on flags do not match associated to_multi_app "
                       "execute_on flags"));
  // In the case of siblings transfer, the check will be looser
  if (_from_multi_app && _to_multi_app)
    if (getExecuteOnEnum() != _from_multi_app->getExecuteOnEnum() &&
        getExecuteOnEnum() != _to_multi_app->getExecuteOnEnum())
      mooseDoOnce(
          mooseWarning("MultiAppTransfer execute_on flags do not match associated to_multi_app "
                       "and from_multi_app execute_on flags"));
}
Referenced by MultiAppTransfer::MultiAppTransfer().
checkVariable()
void MultiAppTransfer::checkVariable (const FEProblemBase & fe_problem, const VariableName & var_name, const std::string & param_name = "") const protected inherited
Helper for checking a problem for a variable.
Parameters
fe_problem The problem that should contain the variable
var_name The name of the variable that should exist within the problem
param_name (optional) The input file parameter name for throwing paramError, if not provided a mooseError is thrown.
Definition at line 599 of file MultiAppTransfer.C.
{
  if (!fe_problem.hasVariable(var_name))
  {
    if (param_name.empty())
      mooseError("The variable '", var_name, "' does not exist.");
    else
      paramError(param_name, "The variable '", var_name, "' does not exist.");
  }
}
Referenced by MultiAppDofCopyTransfer::transfer().
closestToPosition()
bool MultiAppGeneralFieldTransfer::closestToPosition (unsigned int pos_index, const Point & pt) const protected inherited
Whether a point is closest to a position at the index specified than any other position.
Parameters
pos_index the index of the position to consider in the positions vector
pt the point
Returns
whether the point is closest to this position than any other in the positions vector
Definition at line 1655 of file MultiAppGeneralFieldTransfer.C.
{
  mooseAssert(_nearest_positions_obj, "Should not be here without a positions object");
  if (!_skip_coordinate_collapsing)
    paramError("skip_coordinate_collapsing", "Coordinate collapsing not implemented");
  bool initial = _fe_problem.getCurrentExecuteOnFlag() == EXEC_INITIAL;
  return _nearest_positions_obj->getPosition(pos_index, initial) ==
         _nearest_positions_obj->getNearestPosition(pt, initial);
}
Referenced by MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), and MultiAppGeneralFieldNearestLocationTransfer::checkRestrictionsForSource().
connectControllableParams()
void MooseBaseParameterInterface::connectControllableParams (const std::string & parameter, const std::string & object_type, const std::string & object_name, const std::string & object_parameter) const inherited
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
Parameters
parameter Name of the controllable parameter of this action
object_type Type of the object added by this action.
object_name Name of the object added by this action.
object_parameter Name of the parameter of the object.
Definition at line 34 of file MooseBaseParameterInterface.C.
{
  MooseObjectParameterName primary_name(uniqueName(), parameter);
  const auto base_type = _factory.getValidParams(object_type).get<std::string>("_moose_base");
  MooseObjectParameterName secondary_name(base_type, object_name, object_parameter);
  _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
      primary_name, secondary_name);
  const auto & tags = _pars.get<std::vector<std::string>>("control_tags");
  for (const auto & tag : tags)
  {
    if (!tag.empty())
    {
      MooseObjectParameterName tagged_name(tag, _moose_base->name(), parameter);
      _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
          tagged_name, secondary_name);
    }
  }
}
currentDirection()
MooseEnum Transfer::currentDirection () inline inherited
Definition at line 85 of file Transfer.h.
{ return _current_direction; }
customSetup()
virtual void SetupInterface::customSetup (const ExecFlagType &) inline virtual inherited
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
Reimplemented in Function.
Definition at line 61 of file SetupInterface.h.
{}
declareManagedRestartableDataWithContext()
template<typename T , typename... Args> Restartable::ManagedValue< T > Restartable::declareManagedRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declares a piece of "managed" restartable data and initialize it.
Here, "managed" restartable data means that the caller can destruct this data upon destruction of the return value of this method. Therefore, this ManagedValue<T> wrapper should survive after the final calls to dataStore() for it. That is... at the very end.
This is needed for objects whose destruction ordering is important, and enables natural c++ destruction in reverse construction order of the object that declares it.
See delcareRestartableData and declareRestartableDataWithContext for more information.
Definition at line 276 of file Restartable.h.
{
  auto & data_ptr =
      declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...);
  return Restartable::ManagedValue<T>(data_ptr);
}
declareRecoverableData()
template<typename T , typename... Args> T & Restartable::declareRecoverableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "recoverable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
Note - this data will NOT be restored on Restart!
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 351 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  registerRestartableNameWithFilterOnApp(full_name, Moose::RESTARTABLE_FILTER::RECOVERABLE);
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableData()
template<typename T , typename... Args> T & Restartable::declareRestartableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 269 of file Restartable.h.
{
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataHelper()
template<typename T , typename... Args> RestartableData< T > & Restartable::declareRestartableDataHelper (const std::string & data_name, void * context, Args &&... args) const private inherited
Helper function for declaring restartable data.
We use this function to reduce code duplication when returning const/nonconst references to the data.
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 303 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  // Here we will create the RestartableData even though we may not use this instance.
  // If it's already in use, the App will return a reference to the existing instance and we'll
  // return that one instead. We might refactor this to have the app create the RestartableData
  // at a later date.
  auto data_ptr =
      std::make_unique<RestartableData<T>>(full_name, context, std::forward<Args>(args)...);
  auto & restartable_data_ref = static_cast<RestartableData<T> &>(
      registerRestartableDataOnApp(std::move(data_ptr), _restartable_tid));
  return restartable_data_ref;
}
declareRestartableDataWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 294 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...).set();
}
declareRestartableDataWithObjectName()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectName (const std::string & data_name, const std::string & object_name, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
args Arguments to forward to the constructor of the data
Definition at line 323 of file Restartable.h.
{
  return declareRestartableDataWithObjectNameWithContext<T>(
      data_name, object_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataWithObjectNameWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectNameWithContext (const std::string & data_name, const std::string & object_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 333 of file Restartable.h.
{
  std::string old_name = _restartable_name;
  _restartable_name = object_name;
  T & value = declareRestartableDataWithContext<T>(data_name, context, std::forward<Args>(args)...);
  _restartable_name = old_name;
  return value;
}
detectConflict()
bool MultiAppGeneralFieldTransfer::detectConflict (Real value_1, Real value_2, Real distance_1, Real distance_2) const protected inherited
Detects whether two source values are valid and equidistant for a desired target location.
Parameters
value_1 value from the first value source / subapp
value_2 value from the second value source / subapp
distance_1 distance from the first source
distance_2 distance from the second source
Returns
true if the values are different and distances from the source points/apps are the same
Definition at line 1846 of file MultiAppGeneralFieldTransfer.C.
{
  // No conflict if we're not looking for them
  if (_search_value_conflicts)
    // Only consider conflicts if the values are valid and different
    if (current_value != GeneralFieldTransfer::BetterOutOfMeshValue &&
        new_value != GeneralFieldTransfer::BetterOutOfMeshValue &&
        !MooseUtils::absoluteFuzzyEqual(current_value, new_value))
      // Conflict only occurs if the origin points are equidistant
      if (MooseUtils::absoluteFuzzyEqual(current_distance, new_distance))
        return true;
  return false;
}
Referenced by MultiAppGeneralFieldTransfer::cacheIncomingInterpVals(), evaluateInterpValuesWithMeshFunctions(), and MultiAppGeneralFieldUserObjectTransfer::evaluateInterpValuesWithUserObjects().
direction()
MooseEnum Transfer::direction () inline inherited
The current direction that this Transfer is going in. direction() is to be deprecated for currentDirection()
Definition at line 84 of file Transfer.h.
{ return _direction; }
Referenced by Transfer::setCurrentDirection().
directions()
const MultiMooseEnum & Transfer::directions () inline inherited
The directions this Transfer should be executed on.
Definition at line 79 of file Transfer.h.
{ return _directions; }
enabled()
virtual bool MooseObject::enabled () const inline virtual inherited
Return the enabled status of the object.
Reimplemented in EigenKernel.
Definition at line 54 of file MooseObject.h.
{ return _enabled; }
Referenced by EigenKernel::enabled().
errorPrefix()
std::string MooseBaseErrorInterface::errorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for this object:
The following <error_type> occurred in the object "<name>", of type "<type>".
Definition at line 15 of file MooseBaseErrorInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the object \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseErrorInterface::mooseError(), and MooseBaseErrorInterface::mooseWarning().
evaluateInterpValues()
void MultiAppGeneralFieldShapeEvaluationTransfer::evaluateInterpValues (const std::vector< std::pair< Point, unsigned int > > & incoming_points, std::vector< std::pair< Real, Real > > & outgoing_vals) override protected virtual
Implements MultiAppGeneralFieldTransfer.
Definition at line 100 of file MultiAppGeneralFieldShapeEvaluationTransfer.C.
{
  evaluateInterpValuesWithMeshFunctions(
      _local_bboxes, _local_meshfuns, incoming_points, outgoing_vals);
}
evaluateInterpValuesWithMeshFunctions()
void MultiAppGeneralFieldShapeEvaluationTransfer::evaluateInterpValuesWithMeshFunctions (const std::vector< BoundingBox > & local_bboxes, std::vector< MeshFunction > & local_meshfuns, const std::vector< std::pair< Point, unsigned int > > & incoming_points, std::vector< std::pair< Real, Real > > & outgoing_vals) private
Definition at line 109 of file MultiAppGeneralFieldShapeEvaluationTransfer.C.
{
  dof_id_type i_pt = 0;
  for (auto & [pt, mesh_div] : incoming_points)
  {
    bool point_found = false;
    outgoing_vals[i_pt].second = GeneralFieldTransfer::BetterOutOfMeshValue;
    // Loop on all local origin problems until:
    // - we've found the point in an app and the value at that point is valid
    // - or if looking for conflicts between apps, we must check them all
    // - or if looking for the nearest app, we also check them all
    for (MooseIndex(_from_problems.size()) i_from = 0;
         i_from < _from_problems.size() &&
         (!point_found || _search_value_conflicts || _nearest_positions_obj);
         ++i_from)
    {
      // Check spatial restrictions
      Real distance = 0;
      if (!acceptPointInOriginMesh(i_from, local_bboxes, pt, mesh_div, distance))
        continue;
      else
      {
        // Use mesh function to compute interpolation values
        const auto from_global_num = getGlobalSourceAppIndex(i_from);
        const auto local_pt = _from_transforms[from_global_num]->mapBack(pt);
        auto val = (local_meshfuns[i_from])(local_pt);
        // Look for overlaps. The check is not active outside of overlap search because in that
        // case we accept the first value from the lowest ranked process
        // NOTE: There is no guarantee this will be the final value used among all problems
        //       but for shape evaluation we really do expect only one value to even be valid
        if (detectConflict(val, outgoing_vals[i_pt].first, distance, outgoing_vals[i_pt].second))
          registerConflict(i_from, 0, local_pt, distance, true);
        // No need to consider decision factors if value is invalid
        if (val == GeneralFieldTransfer::BetterOutOfMeshValue)
          continue;
        else
          point_found = true;
        // Assign value and the distance from the target point to the origin data
        // distance only matters if multiple applications are providing a valid value
        // which would mean they overlap in the reference space. The distance can help
        // lift the indetermination on which value to select
        if (distance < outgoing_vals[i_pt].second)
        {
          outgoing_vals[i_pt].first = val;
          outgoing_vals[i_pt].second = distance;
        }
      }
    }
    if (!point_found)
      outgoing_vals[i_pt] = {GeneralFieldTransfer::BetterOutOfMeshValue,
                             GeneralFieldTransfer::BetterOutOfMeshValue};
    // Move to next point
    i_pt++;
  }
}
Referenced by evaluateInterpValues().
examineLocalValueConflicts()
void MultiAppGeneralFieldTransfer::examineLocalValueConflicts (const unsigned int var_index, const DofobjectToInterpValVec & dofobject_to_valsvec, const InterpCaches & distance_caches) private inherited
Remove potential value conflicts that did not materialize because another source was closer Several equidistant valid values were found when computing values to send, but they were not closest, another value got selected.
Parameters
var_index the index of the variable of interest
dofobject_to_valsvec a data structure mapping dofobjects to received values and distances (used for nodal-value-dof-only variables and constant monomials)
distance_caches a cache holding the distances received (used for higher order elemental variables)
Definition at line 1031 of file MultiAppGeneralFieldTransfer.C.
{
  const auto var_name = getToVarName(var_index);
  // We must check a posteriori because we could have:
  // - two equidistant points with different values from two different problems
  // - two (or more) equidistant points with different values from the same problem
  // but a third point/value couple from another problem is actually closer, so there is no
  // conflict because only that last one matters. We check here whether the potential conflicts
  // actually were the nearest points. We use several global reductions. If there are not too many
  // potential conflicts (and there should not be in a well-posed problem) it should be manageably
  // expensive
  // Move relevant conflict info (location, distance) to a smaller data structure
  std::vector<std::tuple<Point, Real>> potential_conflicts;
  potential_conflicts.reserve(_local_conflicts.size());
  // Loop over potential conflicts to broadcast all the conflicts
  for (auto conflict_it = _local_conflicts.begin(); conflict_it != _local_conflicts.end();
       ++conflict_it)
  {
    // Extract info for the potential conflict
    const auto potential_conflict = *conflict_it;
    const unsigned int i_from = std::get<0>(potential_conflict);
    Point p = std::get<2>(potential_conflict);
    const Real distance = std::get<3>(potential_conflict);
    // If not using nearest-positions: potential conflict was saved in the source frame
    // If using nearest-positions: potential conflict was saved in the reference frame
    if (!_nearest_positions_obj)
    {
      const auto from_global_num = getGlobalSourceAppIndex(i_from);
      p = (*_from_transforms[from_global_num])(p);
    }
    // Send data in the global frame of reference
    potential_conflicts.push_back(std::make_tuple(p, distance));
  }
  _communicator.allgather(potential_conflicts, false);
  // conflicts could have been reported multiple times within a tolerance
  std::sort(potential_conflicts.begin(), potential_conflicts.end());
  potential_conflicts.erase(unique(potential_conflicts.begin(),
                                   potential_conflicts.end(),
                                   [](auto l, auto r)
{
                                     return std::get<0>(l).absolute_fuzzy_equals(std::get<0>(r)) &&
                                            std::abs(std::get<1>(l) - std::get<1>(r)) < TOLERANCE;
                                   }),
                            potential_conflicts.end());
  std::vector<std::tuple<Point, Real>> real_conflicts;
  real_conflicts.reserve(potential_conflicts.size());
  // For each potential conflict, we need to identify what problem asked for that value
  for (auto conflict_it = potential_conflicts.begin(); conflict_it != potential_conflicts.end();
       ++conflict_it)
  {
    // Extract info for the potential conflict
    auto potential_conflict = *conflict_it;
    const Point p = std::get<0>(potential_conflict);
    const Real distance = std::get<1>(potential_conflict);
    // Check all the problems to try to find this requested point in the data structures filled
    // with the received information
    bool target_found = false;
    bool conflict_real = false;
    for (const auto i_to : index_range(_to_problems))
    {
      // Extract variable info
      auto & es = getEquationSystem(*_to_problems[i_to], _displaced_target_mesh);
      System * to_sys = find_sys(es, var_name);
      auto var_num = to_sys->variable_number(var_name);
      auto & fe_type = to_sys->variable_type(var_num);
      bool is_nodal = _to_variables[var_index]->isNodal();
      // Move to the local frame of reference for the target problem
      Point local_p =
          getPointInTargetAppFrame(p, i_to, "Resolution of local value conflicts detected");
      // Higher order elemental
      if (fe_type.order > CONSTANT && !is_nodal)
      {
        // distance_caches finds use a binned floating point search
        auto cached_distance = distance_caches[i_to].find(local_p);
        if (cached_distance != distance_caches[i_to].end())
        {
          target_found = true;
          // Distance between source & target is still the distance we found in the sending
          // process when we detected a potential overlap while gathering values to send
          if (MooseUtils::absoluteFuzzyEqual(cached_distance->second, distance))
            conflict_real = true;
        }
      }
      // Nodal-value-dof-only and const monomial variable
      else
      {
        // Find the dof id for the variable to be set
        dof_id_type dof_object_id = std::numeric_limits<dof_id_type>::max();
        auto pl = _to_problems[i_to]->mesh().getPointLocator();
        pl->enable_out_of_mesh_mode();
        if (is_nodal)
        {
          auto node = pl->locate_node(local_p);
          if (node)
            // this is not the dof_id for the variable, but the dof_object_id
            dof_object_id = node->id();
        }
        else
        {
          auto elem = (*pl)(local_p);
          if (elem)
            dof_object_id = elem->id();
        }
        pl->disable_out_of_mesh_mode();
        // point isn't even in mesh
        if (dof_object_id == std::numeric_limits<dof_id_type>::max())
          continue;
        // this dof was not requested by this problem on this process
        if (dofobject_to_valsvec[i_to].find(dof_object_id) == dofobject_to_valsvec[i_to].end())
          continue;
        target_found = true;
        // Check the saved distance in the vector of saved results. If the same, then the local
        // conflict we detected with that distance is still an issue after receiving all values
        if (MooseUtils::absoluteFuzzyEqual(
                dofobject_to_valsvec[i_to].find(dof_object_id)->second.distance, distance))
          conflict_real = true;
      }
    }
    // Only keep the actual conflicts / overlaps
    if (target_found && conflict_real)
      real_conflicts.push_back(potential_conflict);
  }
  // Communicate real conflicts to all so they can be checked by every process
  _communicator.allgather(real_conflicts, false);
  // Delete potential conflicts that were resolved
  // Each local list of conflicts will now be updated. It's important to keep conflict lists local
  // so we can give more context like the sending processor id (the domain of which can be
  // inspected by the user)
  for (auto conflict_it = _local_conflicts.begin(); conflict_it != _local_conflicts.end();)
  {
    // Extract info for the potential conflict
    const auto potential_conflict = *conflict_it;
    const unsigned int i_from = std::get<0>(potential_conflict);
    Point p = std::get<2>(potential_conflict);
    const Real distance = std::get<3>(potential_conflict);
    if (!_nearest_positions_obj)
    {
      const auto from_global_num = getGlobalSourceAppIndex(i_from);
      p = (*_from_transforms[from_global_num])(p);
    }
    // If not in the vector of real conflicts, was not real so delete it
    if (std::find_if(real_conflicts.begin(),
                     real_conflicts.end(),
                     [p, distance](const auto & item)
                     {
                       return std::get<0>(item).absolute_fuzzy_equals(p) &&
                              std::abs(std::get<1>(item) - distance) < TOLERANCE;
                     }) == real_conflicts.end())
      _local_conflicts.erase(conflict_it);
    else
      ++conflict_it;
  }
}
Referenced by MultiAppGeneralFieldTransfer::outputValueConflicts().
examineReceivedValueConflicts()
void MultiAppGeneralFieldTransfer::examineReceivedValueConflicts (const unsigned int var_index, const DofobjectToInterpValVec & dofobject_to_valsvec, const InterpCaches & distance_caches) private inherited
Remove potential value conflicts that did not materialize because another source was closer Several equidistant valid values were received, but they were not closest.
Parameters
var_index the index of the variable of interest
dofobject_to_valsvec a data structure mapping dofobjects to received values and distances (used for nodal-value-dof-only variables and constant monomials)
distance_caches a cache holding the distances received (used for higher order elemental variables)
Definition at line 978 of file MultiAppGeneralFieldTransfer.C.
{
  const auto var_name = getToVarName(var_index);
  // We must check a posteriori because we could have two
  // equidistant points with different values from two different problems, but a third point from
  // another problem is actually closer, so there is no conflict because only that last one
  // matters We check here whether the potential conflicts actually were the nearest points Loop
  // over potential conflicts
  for (auto conflict_it = _received_conflicts.begin(); conflict_it != _received_conflicts.end();)
  {
    const auto potential_conflict = *conflict_it;
    bool overlap_found = false;
    // Extract info for the potential conflict
    const unsigned int problem_id = std::get<0>(potential_conflict);
    const dof_id_type dof_object_id = std::get<1>(potential_conflict);
    const Point p = std::get<2>(potential_conflict);
    const Real distance = std::get<3>(potential_conflict);
    // Extract target variable info
    auto & es = getEquationSystem(*_to_problems[problem_id], _displaced_target_mesh);
    System * to_sys = find_sys(es, var_name);
    auto var_num = to_sys->variable_number(var_name);
    auto & fe_type = to_sys->variable_type(var_num);
    bool is_nodal = _to_variables[var_index]->isNodal();
    // Higher order elemental
    if (fe_type.order > CONSTANT && !is_nodal)
    {
      auto cached_distance = distance_caches[problem_id].find(p);
      if (cached_distance == distance_caches[problem_id].end())
        mooseError("Conflict point was not found in the map of all origin-target distances");
      // Distance is still the distance when we detected a potential overlap
      if (MooseUtils::absoluteFuzzyEqual(cached_distance->second, distance))
        overlap_found = true;
    }
    // Nodal and const monomial variable
    else if (MooseUtils::absoluteFuzzyEqual(
                 dofobject_to_valsvec[problem_id].find(dof_object_id)->second.distance, distance))
      overlap_found = true;
    // Map will only keep the actual overlaps
    if (!overlap_found)
      _received_conflicts.erase(conflict_it);
    else
      ++conflict_it;
  }
}
Referenced by MultiAppGeneralFieldTransfer::outputValueConflicts().
execute()
void MultiAppGeneralFieldTransfer::execute () override virtual inherited
Execute the transfer.
Implements Transfer.
Definition at line 431 of file MultiAppGeneralFieldTransfer.C.
{
  getAppInfo();
  // Set up bounding boxes, etc
  prepareToTransfer();
  // loop over the vector of variables and make the transfer one by one
  for (const auto i : make_range(_var_size))
    transferVariable(i);
  postExecute();
}
extendBoundingBoxes()
void MultiAppTransfer::extendBoundingBoxes (const Real factor, std::vector< BoundingBox > & bboxes) const protected inherited
Extends bounding boxes to avoid missing points.
Definition at line 452 of file MultiAppTransfer.C.
{
  const auto extension_factor = factor - 1;
  // Extend (or contract if the extension factor is negative) bounding boxes along all the
  // directions by the same length. Greater than zero values of this member may be necessary because
  // the nearest bounding box does not necessarily give you the closest node/element. It will depend
  // on the partition and geometry. A node/element will more likely find its nearest source
  // element/node by extending bounding boxes. If each of the bounding boxes covers the entire
  // domain, a node/element will be able to find its nearest source element/node for sure, but at
  // the same time, more communication will be involved and can be expensive.
  for (auto & box : bboxes)
  {
    // libmesh set an invalid bounding box using this code
    // for (unsigned int i=0; i<LIBMESH_DIM; i++)
    // {
    //   this->first(i)  =  std::numeric_limits<Real>::max();
    //   this->second(i) = -std::numeric_limits<Real>::max();
    // }
    // If it is an invalid box, we should skip it
    if (box.first(0) == std::numeric_limits<Real>::max())
      continue;
    auto width = box.second - box.first;
    box.second += width * extension_factor;
    box.first -= width * extension_factor;
  }
}
Referenced by MultiAppTransfer::getFromBoundingBoxes(), and MultiAppGeneralFieldTransfer::prepareToTransfer().
extractLocalFromBoundingBoxes()
void MultiAppGeneralFieldTransfer::extractLocalFromBoundingBoxes (std::vector< BoundingBox > & local_bboxes) protected inherited
Definition at line 813 of file MultiAppGeneralFieldTransfer.C.
{
  local_bboxes.resize(_froms_per_proc[processor_id()]);
  // Find the index to the first of this processor's local bounding boxes.
  unsigned int local_start = 0;
  for (processor_id_type i_proc = 0; i_proc < n_processors() && i_proc != processor_id(); ++i_proc)
    local_start += _froms_per_proc[i_proc];
  // Extract the local bounding boxes.
  for (const auto i_from : make_range(_froms_per_proc[processor_id()]))
    local_bboxes[i_from] = _from_bboxes[local_start + i_from];
}
Referenced by prepareEvaluationOfInterpValues(), and MultiAppGeneralFieldUserObjectTransfer::prepareEvaluationOfInterpValues().
extractOutgoingPoints()
void MultiAppGeneralFieldTransfer::extractOutgoingPoints (const unsigned int var_index, ProcessorToPointVec & outgoing_points) private inherited
Definition at line 670 of file MultiAppGeneralFieldTransfer.C.
{
  // Get the variable name, with the accommodation for array/vector names
  const auto & var_name = getToVarName(var_index);
  // Clean up the map from processor to pointInfo vector
  // This map should be consistent with outgoing_points
  _processor_to_pointInfoVec.clear();
  // Loop over all problems
  for (const auto i_to : index_range(_to_problems))
  {
    const auto global_i_to = getGlobalTargetAppIndex(i_to);
    // libMesh EquationSystems
    auto & es = getEquationSystem(*_to_problems[i_to], _displaced_target_mesh);
    // libMesh system that has this variable
    System * to_sys = find_sys(es, var_name);
    auto sys_num = to_sys->number();
    auto var_num = _to_variables[var_index]->number();
    auto & fe_type = _to_variables[var_index]->feType();
    bool is_nodal = _to_variables[var_index]->isNodal();
    // Moose mesh
    const auto & to_moose_mesh = _to_problems[i_to]->mesh(_displaced_target_mesh);
    const auto & to_mesh = to_moose_mesh.getMesh();
    // We support more general variables via libMesh GenericProjector
    if (fe_type.order > CONSTANT && !is_nodal)
    {
      GeneralFieldTransfer::RecordRequests<Number> f;
      GeneralFieldTransfer::RecordRequests<Gradient> g;
      GeneralFieldTransfer::NullAction<Number> nullsetter;
      const std::vector<unsigned int> varvec(1, var_num);
      libMesh::GenericProjector<GeneralFieldTransfer::RecordRequests<Number>,
                                GeneralFieldTransfer::RecordRequests<Gradient>,
                                Number,
                                GeneralFieldTransfer::NullAction<Number>>
          request_gather(*to_sys, f, &g, nullsetter, varvec);
      // Defining only boundary values will not be enough to describe the variable, disallow it
      if (_to_boundaries.size() && (_to_variables[var_index]->getContinuity() == DISCONTINUOUS))
        mooseError("Higher order discontinuous elemental variables are not supported for "
                   "target-boundary "
                   "restricted transfers");
      // Not implemented as the target mesh division could similarly be cutting elements in an
      // arbitrary way with not enough requested points to describe the target variable
      if (!_to_mesh_divisions.empty() && !_to_mesh_divisions[i_to]->coversEntireMesh())
        mooseError("Higher order variable support not implemented for target mesh division "
                   "unless the mesh is fully covered / indexed in the mesh division. This must be "
                   "set programmatically in the MeshDivision object used.");
      // We dont look at boundary restriction, not supported for higher order target variables
      // Same for mesh divisions
      const auto & to_begin = _to_blocks.empty()
                                  ? to_mesh.active_local_elements_begin()
                                  : to_mesh.active_local_subdomain_set_elements_begin(_to_blocks);
      const auto & to_end = _to_blocks.empty()
                                ? to_mesh.active_local_elements_end()
                                : to_mesh.active_local_subdomain_set_elements_end(_to_blocks);
      ConstElemRange to_elem_range(to_begin, to_end);
      request_gather.project(to_elem_range);
      dof_id_type point_id = 0;
      for (const Point & p : f.points_requested())
        // using the point number as a "dof_object_id" will serve to identify the point if we ever
        // rework interp/distance_cache into the dof_id_to_value maps
        this->cacheOutgoingPointInfo(
            (*_to_transforms[global_i_to])(p), point_id++, i_to, outgoing_points);
      // This is going to require more complicated transfer work
      if (!g.points_requested().empty())
        mooseError("We don't currently support variables with gradient degrees of freedom");
    }
    else if (is_nodal)
    {
      for (const auto & node : to_mesh.local_node_ptr_range())
      {
        // Skip this node if the variable has no dofs at it.
        if (node->n_dofs(sys_num, var_num) < 1)
          continue;
        // Skip if it is a block restricted transfer and current node does not have
        // specified blocks
        if (!_to_blocks.empty() && !inBlocks(_to_blocks, to_moose_mesh, node))
          continue;
        if (!_to_boundaries.empty() && !onBoundaries(_to_boundaries, to_moose_mesh, node))
          continue;
        // Skip if the node does not meet the target mesh division behavior
        // We cannot know from which app the data will come from so we cannot know
        // the source mesh division index and the source app global index
        if (!_to_mesh_divisions.empty() && _to_mesh_divisions[i_to]->divisionIndex(*node) ==
                                               MooseMeshDivision::INVALID_DIVISION_INDEX)
          continue;
        // Cache point information
        // We will use this information later for setting values back to solution vectors
        cacheOutgoingPointInfo(
            (*_to_transforms[global_i_to])(*node), node->id(), i_to, outgoing_points);
      }
    }
    else // Elemental, constant monomial
    {
      for (const auto & elem :
           as_range(to_mesh.local_elements_begin(), to_mesh.local_elements_end()))
      {
        // Skip this element if the variable has no dofs at it.
        if (elem->n_dofs(sys_num, var_num) < 1)
          continue;
        // Skip if the element is not inside the block restriction
        if (!_to_blocks.empty() && !inBlocks(_to_blocks, elem))
          continue;
        // Skip if the element does not have a side on the boundary
        if (!_to_boundaries.empty() && !onBoundaries(_to_boundaries, to_moose_mesh, elem))
          continue;
        // Skip if the element is not indexed within the mesh division
        if (!_to_mesh_divisions.empty() && _to_mesh_divisions[i_to]->divisionIndex(*elem) ==
                                               MooseMeshDivision::INVALID_DIVISION_INDEX)
          continue;
        // Cache point information
        // We will use this information later for setting values back to solution vectors
        cacheOutgoingPointInfo((*_to_transforms[global_i_to])(elem->vertex_average()),
                               elem->id(),
                               i_to,
                               outgoing_points);
      } // for
    }   // else
  }     // for
}
Referenced by MultiAppGeneralFieldTransfer::transferVariable().
find_sys()
System * Transfer::find_sys (EquationSystems & es, const std::string & var_name) static inherited
Small helper function for finding the system containing the variable.
Note that this implies that variable names are unique across all systems!
Parameters
es The EquationSystems object to be searched.
var_name The name of the variable you are looking for.
Note that this implies that variable names are unique across all systems!
Definition at line 89 of file Transfer.C.
{
  // Find the system this variable is from
  for (unsigned int i = 0; i < es.n_systems(); i++)
    if (es.get_system(i).has_variable(var_name))
      return &es.get_system(i);
  ::mooseError("Unable to find variable " + var_name + " in any system.");
  // Unreachable
  return &es.get_system(0);
}
Referenced by MultiAppGeneralFieldTransfer::examineLocalValueConflicts(), MultiAppGeneralFieldTransfer::examineReceivedValueConflicts(), MultiAppNearestNodeTransfer::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), MultiAppGeneralFieldTransfer::setSolutionVectorValues(), and MultiAppShapeEvaluationTransfer::transferVariable().
getAppInfo()
void MultiAppGeneralFieldTransfer::getAppInfo () override virtual inherited
This method will fill information into the convenience member variables (_to_problems, _from_meshes, etc.)
Reimplemented from MultiAppTransfer.
Definition at line 415 of file MultiAppGeneralFieldTransfer.C.
{
  MultiAppFieldTransfer::getAppInfo();
  // Create the point locators to locate evaluation points in the origin mesh(es)
  _from_point_locators.resize(_from_problems.size());
  for (const auto i_from : index_range(_from_problems))
  {
    const auto & from_moose_mesh = _from_problems[i_from]->mesh(_displaced_source_mesh);
    _from_point_locators[i_from] =
        PointLocatorBase::build(TREE_LOCAL_ELEMENTS, from_moose_mesh.getMesh());
    _from_point_locators[i_from]->enable_out_of_mesh_mode();
  }
}
Referenced by MultiAppGeneralFieldTransfer::execute().
getCheckedPointerParam()
template<typename T > T MooseBaseParameterInterface::getCheckedPointerParam (const std::string & name, const std::string & error_string = "") const inherited
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
The template parameter must be a pointer or an error will be thrown.
Definition at line 264 of file MooseBaseParameterInterface.h.
{
  return parameters().getCheckedPointerParam<T>(name, error_string);
}
getDataFileName()
std::string DataFileInterface< MooseObject >::getDataFileName (const std::string & param) const inherited
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
relative to the input file directory
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
relative to the input file directory
Definition at line 34 of file DataFileInterface.C.
{
  {
    const auto & absolute_path = _parent.template getParam<FileName>(param);
    if (MooseUtils::checkFileReadable(absolute_path, false, false, false))
    {
      _parent.paramInfo(param, "Data file '", absolute_path, "' found relative to the input file.");
      return absolute_path;
    }
  }
  const auto & relative_path = _parent.parameters().rawParamVal(param);
  return getDataFileNameByName(relative_path, &param);
}
getDataFileNameByName()
std::string DataFileInterface< MooseObject >::getDataFileNameByName (const std::string & name, const std::string * param = nullptr) const inherited
Returns the path of a data file for a given relative file path.
This can be used for hardcoded datafile names and will search the same locations as getDataFileName. The optional param pointer can be used to turn the mooseErrors this function emits into paramErrors
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
Definition at line 42 of file DataFileInterface.C.
{
  const auto share_dir = MooseUtils::pathjoin(Moose::getExecutablePath(), "..", "share");
  if (MooseUtils::pathIsDirectory(share_dir))
  {
    const auto dirs = MooseUtils::listDir(share_dir, false);
    for (const auto & data_dir : dirs)
    {
      const auto path = MooseUtils::pathjoin(data_dir, "data", relative_path);
      if (MooseUtils::checkFileReadable(path, false, false, false))
      {
        if (param)
          _parent.paramInfo(
              *param, "Data file '", path, "' found in an installed app distribution.");
        else
          mooseInfo("Data file '", path, "' found in an installed app distribution.");
        return path;
      }
    }
  }
  for (const auto & data_dir : Registry::getRegistry().getDataFilePaths())
  {
    const auto path = MooseUtils::pathjoin(data_dir, relative_path);
    if (MooseUtils::checkFileReadable(path, false, false, false))
    {
      if (param)
        _parent.paramInfo(*param, "Data file '", path, "' found in a source repository.");
      else
        mooseInfo("Data file '", path, "' found in a source repository.");
      return path;
    }
  }
  mooseException(param ? _parent.parameters().inputLocation(*param) : _parent.name(),
                 ": Unable to find data file '",
                 relative_path,
                 "' anywhere");
}
getEquationSystem()
EquationSystems & MultiAppFieldTransfer::getEquationSystem (FEProblemBase & problem, bool use_displaced) const protected inherited
Returns the Problem's equation system, displaced or not Be careful! If you transfer TO a displaced system you will likely need a synchronization So most transfers reach the non-displaced system directly.
Definition at line 55 of file MultiAppFieldTransfer.C.
{
  if (use_displaced)
  {
    if (!problem.getDisplacedProblem())
      mooseError("No displaced problem to provide a displaced equation system");
    return problem.getDisplacedProblem()->es();
  }
  else
    return problem.es();
}
Referenced by buildMeshFunctions(), MultiAppGeneralFieldTransfer::examineLocalValueConflicts(), MultiAppGeneralFieldTransfer::examineReceivedValueConflicts(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), MultiAppGeneralFieldTransfer::setSolutionVectorValues(), and MultiAppShapeEvaluationTransfer::transferVariable().
getExecuteOnEnum()
const ExecFlagEnum & SetupInterface::getExecuteOnEnum () const inherited
Return the execute on MultiMooseEnum for this object.
Definition at line 65 of file SetupInterface.C.
{
  return _execute_enum;
}
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), MultiAppTransfer::checkMultiAppExecuteOn(), IntegralPreservingFunctionIC::initialSetup(), MultiAppConservativeTransfer::initialSetup(), Terminator::initialSetup(), ElementReporter::shouldStore(), GeneralReporter::shouldStore(), and NodalReporter::shouldStore().
getFromBoundingBoxes() [1/2]
std::vector< BoundingBox > MultiAppTransfer::getFromBoundingBoxes () protected inherited
Return the bounding boxes of all the "from" domains, including all the domains not local to this processor.
There is a boundary restricted version which will return a degenerate minimum boundary box (min, min, min, min, min, min) in the case where the source domain doesn't have any active nodes on the boundary. Note: bounding boxes are in the reference space when using coordinate transformations / positions Note: global bounding boxes are not indexed by app number. But rather outer indexing is by process, then the inner indexing is by local app number.
Definition at line 482 of file MultiAppTransfer.C.
{
  std::vector<std::pair<Point, Point>> bb_points(_from_meshes.size());
  for (unsigned int i = 0; i < _from_meshes.size(); i++)
  {
    // Get a bounding box around the mesh elements that are local to the current
    // processor.
    BoundingBox bbox = MeshTools::create_local_bounding_box(*_from_meshes[i]);
    // Translate the bounding box to the from domain's position. We may have rotations so we must
    // be careful in constructing the new min and max (first and second)
    const auto from_global_num = getGlobalSourceAppIndex(i);
    transformBoundingBox(bbox, *_from_transforms[from_global_num]);
    // Cast the bounding box into a pair of points (so it can be put through
    // MPI communication).
    bb_points[i] = static_cast<std::pair<Point, Point>>(bbox);
  }
  // Serialize the bounding box points.
  _communicator.allgather(bb_points);
  // Recast the points back into bounding boxes and return.
  std::vector<BoundingBox> bboxes(bb_points.size());
  for (unsigned int i = 0; i < bb_points.size(); i++)
    bboxes[i] = static_cast<BoundingBox>(bb_points[i]);
  // possibly extend bounding boxes
  extendBoundingBoxes(_bbox_factor, bboxes);
  return bboxes;
}
Referenced by MultiAppNearestNodeTransfer::execute(), MultiAppProjectionTransfer::execute(), and MultiAppShapeEvaluationTransfer::transferVariable().
getFromBoundingBoxes() [2/2]
std::vector< BoundingBox > MultiAppTransfer::getFromBoundingBoxes (BoundaryID boundary_id) protected inherited
Definition at line 516 of file MultiAppTransfer.C.
{
  std::vector<std::pair<Point, Point>> bb_points(_from_meshes.size());
  const Real min_r = std::numeric_limits<Real>::lowest();
  const Real max_r = std::numeric_limits<Real>::max();
  for (unsigned int i = 0; i < _from_meshes.size(); i++)
  {
    Point min(max_r, max_r, max_r);
    Point max(min_r, min_r, min_r);
    bool at_least_one = false;
    // TODO: Factor this into mesh_tools after adding new boundary bounding box routine.
    const ConstBndNodeRange & bnd_nodes = *_from_meshes[i]->getBoundaryNodeRange();
    for (const auto & bnode : bnd_nodes)
    {
      if (bnode->_bnd_id == boundary_id &&
          bnode->_node->processor_id() == _from_meshes[i]->processor_id())
      {
        at_least_one = true;
        const auto & node = *bnode->_node;
        for (const auto i : make_range(Moose::dim))
        {
          min(i) = std::min(min(i), node(i));
          max(i) = std::max(max(i), node(i));
        }
      }
    }
    BoundingBox bbox(min, max);
    if (!at_least_one)
      bbox.min() = max; // If we didn't hit any nodes, this will be _the_ minimum bbox
    else
    {
      // Translate the bounding box to the from domain's position. We may have rotations so we must
      // be careful in constructing the new min and max (first and second)
      const auto from_global_num = getGlobalSourceAppIndex(i);
      transformBoundingBox(bbox, *_from_transforms[from_global_num]);
    }
    // Cast the bounding box into a pair of points (so it can be put through
    // MPI communication).
    bb_points[i] = static_cast<std::pair<Point, Point>>(bbox);
  }
  // Serialize the bounding box points.
  _communicator.allgather(bb_points);
  // Recast the points back into bounding boxes and return.
  std::vector<BoundingBox> bboxes(bb_points.size());
  for (unsigned int i = 0; i < bb_points.size(); i++)
    bboxes[i] = static_cast<BoundingBox>(bb_points[i]);
  // possibly extend bounding boxes
  extendBoundingBoxes(_bbox_factor, bboxes);
  return bboxes;
}
getFromMultiApp()
const std::shared_ptr< MultiApp > MultiAppTransfer::getFromMultiApp () const inline inherited
Get the MultiApp to transfer data from.
Definition at line 63 of file MultiAppTransfer.h.
  {
    if (!_from_multi_app)
      mooseError(
          "A from_multiapp was requested but is unavailable. Check the from_multi_app parameter");
    else
      return _from_multi_app;
  }
Referenced by MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), MultiAppCopyTransfer::execute(), MultiAppGeometricInterpolationTransfer::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppCloneReporterTransfer::executeFromMultiapp(), MultiAppReporterTransfer::executeFromMultiapp(), MultiAppVectorPostprocessorTransfer::executeFromMultiapp(), MultiAppReporterTransfer::executeToMultiapp(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppConservativeTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppReporterTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppConservativeTransfer::postExecute(), and MultiAppVariableValueSamplePostprocessorTransfer::setupPostprocessorCommunication().
getFromMultiAppInfo()
void MultiAppTransfer::getFromMultiAppInfo () private inherited
Definition at line 437 of file MultiAppTransfer.C.
{
  if (!_from_multi_app)
    mooseError("There is no from_multiapp to get info from");
  fillInfo(*_from_multi_app, _from_local2global_map, _from_problems, _from_positions);
}
Referenced by MultiAppTransfer::getAppInfo().
getFromName()
std::string MultiAppTransfer::getFromName () const inline inherited
Get the name of thing being transferred from.
Returns
the name of the multiapp or "Parent"
Definition at line 86 of file MultiAppTransfer.h.
  {
    if (_from_multi_app)
      return _from_multi_app->name();
    else
      return "Parent";
  }
getFromsPerProc()
std::vector< unsigned int > MultiAppTransfer::getFromsPerProc () protected inherited
Return the number of "from" domains that each processor owns.
Note: same indexing as getFromBoundingBoxes
Definition at line 577 of file MultiAppTransfer.C.
{
  std::vector<unsigned int> froms_per_proc;
  if (_to_multi_app)
    froms_per_proc.resize(n_processors(), 1);
  if (_from_multi_app)
  {
    froms_per_proc.resize(n_processors());
    _communicator.allgather(_from_multi_app->numLocalApps(), froms_per_proc);
  }
  return froms_per_proc;
}
Referenced by MultiAppNearestNodeTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppGeneralFieldTransfer::prepareToTransfer(), and MultiAppShapeEvaluationTransfer::transferVariable().
getFromVarName()
VariableName MultiAppGeneralFieldTransfer::getFromVarName (unsigned int var_index) inherited
Get the source variable name, with the suffix for array/vector variables.
Definition at line 1808 of file MultiAppGeneralFieldTransfer.C.
{
  mooseAssert(var_index < _from_var_names.size(), "No source variable at this index");
  VariableName var_name = _from_var_names[var_index];
  if (_from_var_components.size())
    var_name += "_" + std::to_string(_from_var_components[var_index]);
  return var_name;
}
Referenced by MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), buildMeshFunctions(), and MultiAppGeneralFieldTransfer::outputValueConflicts().
getFromVarNames()
virtual std::vector< VariableName > MultiAppConservativeTransfer::getFromVarNames () const inline override protected virtual inherited
Virtual function defining variables to be transferred.
Implements MultiAppFieldTransfer.
Definition at line 34 of file MultiAppConservativeTransfer.h.
{ return _from_var_names; }
getGlobalSourceAppIndex()
unsigned int MultiAppTransfer::getGlobalSourceAppIndex (unsigned int i_from) const protected inherited
Return the global app index from the local index in the "from-multiapp" transfer direction.
Definition at line 634 of file MultiAppTransfer.C.
{
  mooseAssert(_current_direction == TO_MULTIAPP || i_from < _from_local2global_map.size(),
              "Out of bounds local from-app index");
  return _current_direction == TO_MULTIAPP ? 0 : _from_local2global_map[i_from];
}
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppGeneralFieldTransfer::acceptPointMeshDivision(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldNearestLocationTransfer::checkRestrictionsForSource(), MultiAppGeneralFieldNearestLocationTransfer::evaluateInterpValuesNearestNode(), evaluateInterpValuesWithMeshFunctions(), MultiAppGeneralFieldUserObjectTransfer::evaluateInterpValuesWithUserObjects(), MultiAppGeneralFieldTransfer::examineLocalValueConflicts(), MultiAppTransfer::getFromBoundingBoxes(), MultiAppGeneralFieldNearestLocationTransfer::getPointInLocalSourceFrame(), MultiAppGeneralFieldTransfer::getRestrictedFromBoundingBoxes(), and MultiAppGeneralFieldTransfer::initialSetup().
getGlobalStartAppPerProc()
std::vector< unsigned int > MultiAppGeneralFieldTransfer::getGlobalStartAppPerProc () const private inherited
Get global index for the first app each processes owns Requires a global communication, must be called on every domain simultaneously.
Definition at line 1798 of file MultiAppGeneralFieldTransfer.C.
{
  std::vector<unsigned int> global_app_start_per_proc(1, -1);
  if (_from_local2global_map.size())
    global_app_start_per_proc[0] = _from_local2global_map[0];
  _communicator.allgather(global_app_start_per_proc, true);
  return global_app_start_per_proc;
}
Referenced by MultiAppGeneralFieldTransfer::prepareToTransfer().
getGlobalTargetAppIndex()
unsigned int MultiAppTransfer::getGlobalTargetAppIndex (unsigned int i_to) const protected inherited
Return the global app index from the local index in the "to-multiapp" transfer direction.
Definition at line 642 of file MultiAppTransfer.C.
{
  mooseAssert(_current_direction == FROM_MULTIAPP || i_to < _to_local2global_map.size(),
              "Out of bounds local to-app index");
  return _current_direction == FROM_MULTIAPP ? 0 : _to_local2global_map[i_to];
}
Referenced by MultiAppGeneralFieldTransfer::cacheIncomingInterpVals(), MultiAppGeneralFieldTransfer::cacheOutgoingPointInfo(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), MultiAppTransfer::getPointInTargetAppFrame(), MultiAppGeneralFieldTransfer::locatePointReceivers(), and MultiAppGeneralFieldTransfer::setSolutionVectorValues().
getLocalSourceAppIndex()
unsigned int MultiAppTransfer::getLocalSourceAppIndex (unsigned int i_from) const protected inherited
Return the local app index from the global index in the "from-multiapp" transfer direction We use the fact that global app indexes are consecutive on a given rank.
Definition at line 650 of file MultiAppTransfer.C.
{
  return _current_direction == TO_MULTIAPP
             ? 0
             : _from_local2global_map[i_from] - _from_local2global_map[0];
}
getMaxToProblemsBBoxDimensions()
Point MultiAppGeneralFieldTransfer::getMaxToProblemsBBoxDimensions () const private inherited
Obtains the max dimensions to scale all points in the mesh.
Returns
the maximum dimension in each coordinate axis of all target problems
Definition at line 1828 of file MultiAppGeneralFieldTransfer.C.
{
  Point max_dimension = {std::numeric_limits<Real>::min(),
                         std::numeric_limits<Real>::min(),
                         std::numeric_limits<Real>::min()};
  for (const auto & to_mesh : _to_meshes)
  {
    const auto bbox = to_mesh->getInflatedProcessorBoundingBox();
    for (const auto dim : make_range(LIBMESH_DIM))
      max_dimension(dim) = std::max(
          max_dimension(dim), std::max(std::abs(bbox.first(dim)), std::abs(bbox.second(dim))));
  }
  return max_dimension;
}
Referenced by MultiAppGeneralFieldTransfer::transferVariable().
getMooseApp()
MooseApp & MooseBase::getMooseApp () const inline inherited
Get the MooseApp this class is associated with.
Definition at line 35 of file MooseBase.h.
{ return _app; }
Referenced by ReporterTransferInterface::checkHasReporterValue(), Coupleable::checkWritableVar(), MooseBaseParameterInterface::connectControllableParams(), Coupleable::Coupleable(), MortarData::createMortarInterface(), EigenProblem::doFreeNonlinearPowerIterations(), Terminator::execute(), FEProblemSolve::FEProblemSolve(), SolutionInvalidInterface::flagInvalidSolutionInternal(), MaterialPropertyInterface::MaterialPropertyInterface(), MooseVariableDataFV< OutputType >::MooseVariableDataFV(), ProgressOutput::output(), MooseBaseParameterInterface::paramError(), PetscOutputInterface::petscLinearOutput(), PetscOutputInterface::petscNonlinearOutput(), PetscOutputInterface::PetscOutputInterface(), PostprocessorInterface::postprocessorsAdded(), MultiApp::preTransfer(), Reporter::Reporter(), ReporterInterface::reportersAdded(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
getMultiApp()
const std::shared_ptr< MultiApp > MultiAppTransfer::getMultiApp () const inline inherited
Use this getter to obtain the MultiApp for transfers with a single direction.
Definition at line 48 of file MultiAppTransfer.h.
  {
    if (_from_multi_app && _to_multi_app && _from_multi_app != _to_multi_app)
      mooseError("Unclear which app you want to retrieve from Transfer ", name());
    else if (_from_multi_app)
      return _from_multi_app;
    else if (_to_multi_app)
      return _to_multi_app;
    else if (_multi_app)
      return _multi_app;
    else
      mooseError("Should not get here, there should be a multiapp");
  }
Referenced by MultiAppCloneReporterTransfer::initialSetup(), and MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer().
getParam() [1/2]
template<typename T > const T & MooseBaseParameterInterface::getParam (const std::string & name) const inherited
Retrieve a parameter for the object.
Parameters
name The name of the parameter
Returns
The value of the parameter
Definition at line 200 of file MooseBaseParameterInterface.h.
{
  return InputParameters::getParamHelper(name, _pars, static_cast<T *>(0));
}
Referenced by AddGeneralReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddPeriodicBCAction::act(), CreateDisplacedProblemAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), ConstraintWarehouse::addObject(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), ADNodalKernel::ADNodalKernel(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), PiecewiseTabularBase::buildFromJSON(), Console::Console(), FEProblemBase::createTagSolutions(), AccumulateReporter::declareLateValues(), DerivativeParsedMaterialTempl< is_ad >::DerivativeParsedMaterialTempl(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EigenKernel::EigenKernel(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), GenericConstantRankTwoTensorTempl< is_ad >::GenericConstantRankTwoTensorTempl(), MooseApp::getCheckpointDirectories(), ExecutorInterface::getExecutor(), AdvancedOutput::init(), IterationAdaptiveDT::init(), TimeSequenceStepper::init(), AttribThread::initFrom(), AttribSysNum::initFrom(), AttribResidualObject::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), Console::initialSetup(), IterationAdaptiveDT::limitDTToPostprocessorValue(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MortarConsumerInterface::MortarConsumerInterface(), NestedDivision::NestedDivision(), ConsoleUtils::outputExecutionInformation(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedMaterialTempl< is_ad >::ParsedMaterialTempl(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), ParsedODEKernel::ParsedODEKernel(), ParsedPostprocessor::ParsedPostprocessor(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), Moose::FV::setInterpolationMethod(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), TimePeriod::TimePeriod(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and VectorOfPostprocessors::VectorOfPostprocessors().
getParam() [2/2]
template<typename T1 , typename T2 > std::vector< std::pair< T1, T2 > > MooseBaseParameterInterface::getParam (const std::string & param1, const std::string & param2) const inherited
Retrieve two parameters and provide pair of parameters for the object.
Parameters
param1 The name of first parameter
param2 The name of second parameter
Returns
Vector of pairs of first and second parameters
Definition at line 257 of file MooseBaseParameterInterface.h.
{
  return _pars.get<T1, T2>(param1, param2);
}
getPointInTargetAppFrame()
Point MultiAppTransfer::getPointInTargetAppFrame (const Point & p, unsigned int local_i_to, const std::string & phase) const protected inherited
Get the target app point from a point in the reference frame.
Parameters
p the point in the reference frame
local_i_to the local target problem into
phase the phase of the transfer where this is being attempted in case we have to output an info message that the coordinate collapse is not being applied
Returns
the point in the target app frame
Definition at line 613 of file MultiAppTransfer.C.
{
  const auto & to_transform = _to_transforms[getGlobalTargetAppIndex(local_i_to)];
  if (to_transform->hasCoordinateSystemTypeChange())
  {
    if (!_skip_coordinate_collapsing)
      mooseInfo(phase + " cannot use the point in the target app frame due to the "
                        "non-uniqueness of the coordinate collapsing reverse mapping."
                        " Coordinate collapse is ignored for this operation");
    to_transform->skipCoordinateCollapsing(true);
    const auto target_point = to_transform->mapBack(p);
    to_transform->skipCoordinateCollapsing(false);
    return target_point;
  }
  else
    return to_transform->mapBack(p);
}
Referenced by MultiAppGeneralFieldTransfer::cacheIncomingInterpVals(), and MultiAppGeneralFieldTransfer::examineLocalValueConflicts().
getRenamedParam()
template<typename T > const T & MooseBaseParameterInterface::getRenamedParam (const std::string & old_name, const std::string & new_name) const inherited
Retrieve a renamed parameter for the object.
This helper makes sure we check both names before erroring, and that only one parameter is passed to avoid silent errors
Parameters
old_name the old name for the parameter
new_name the new name for the parameter
Definition at line 207 of file MooseBaseParameterInterface.h.
{
  // this enables having a default on the new parameter but bypassing it with the old one
  // Most important: accept new parameter
  if (isParamSetByUser(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Second most: accept old parameter
  else if (isParamValid(old_name) && !isParamSetByUser(new_name))
    return InputParameters::getParamHelper(old_name, _pars, static_cast<T *>(0));
  // Third most: accept default for new parameter
  else if (isParamValid(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Refuse: no default, no value passed
  else if (!isParamValid(old_name) && !isParamValid(new_name))
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' is being retrieved without being set.\n"
               "Did you misspell it?");
  // Refuse: both old and new parameters set by user
  else
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' may not be provided alongside former parameter '" + old_name + "'");
}
getRestartableData()
template<typename T , typename... Args> const T & Restartable::getRestartableData (const std::string & data_name) const protected inherited
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
Forwarded arguments are not allowed in this case because we assume that the object is restarted and we won't need different constructors to initialize it.
NOTE: This returns a const reference! Make sure you store it in a const reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
Definition at line 287 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, nullptr).get();
}
getRestrictedFromBoundingBoxes()
std::vector< BoundingBox > MultiAppGeneralFieldTransfer::getRestrictedFromBoundingBoxes () const private inherited
Get from bounding boxes for given domains and boundaries.
Definition at line 1714 of file MultiAppGeneralFieldTransfer.C.
{
  std::vector<std::pair<Point, Point>> bb_points(_from_meshes.size());
  const Real min_r = std::numeric_limits<Real>::lowest();
  const Real max_r = std::numeric_limits<Real>::max();
  for (const auto j : make_range(_from_meshes.size()))
  {
    Point min(max_r, max_r, max_r);
    Point max(min_r, min_r, min_r);
    bool at_least_one = false;
    const auto & from_mesh = _from_problems[j]->mesh(_displaced_source_mesh);
    for (const auto & elem : as_range(from_mesh.getMesh().local_elements_begin(),
                                      from_mesh.getMesh().local_elements_end()))
    {
      if (!_from_blocks.empty() && !inBlocks(_from_blocks, from_mesh, elem))
        continue;
      for (const auto & node : elem->node_ref_range())
      {
        if (!_from_boundaries.empty() && !onBoundaries(_from_boundaries, from_mesh, &node))
          continue;
        at_least_one = true;
        for (const auto i : make_range(LIBMESH_DIM))
        {
          min(i) = std::min(min(i), node(i));
          max(i) = std::max(max(i), node(i));
        }
      }
    }
    // For 2D RZ problems, we need to amend the bounding box to cover the whole XYZ projection
    // - The XYZ-Y axis is assumed aligned with the RZ-Z axis
    // - RZ systems also cover negative coordinates hence the use of the maximum R
    // NOTE: We will only support the case where there is only one coordinate system
    if ((from_mesh.getUniqueCoordSystem() == Moose::COORD_RZ) && (LIBMESH_DIM == 3))
    {
      min(0) = -max(0);
      min(2) = -max(0);
      max(2) = max(0);
    }
    BoundingBox bbox(min, max);
    if (!at_least_one)
      bbox.min() = max; // If we didn't hit any nodes, this will be _the_ minimum bbox
    else
    {
      // Translate the bounding box to the from domain's position. We may have rotations so we
      // must be careful in constructing the new min and max (first and second)
      const auto from_global_num = getGlobalSourceAppIndex(j);
      transformBoundingBox(bbox, *_from_transforms[from_global_num]);
    }
    // Cast the bounding box into a pair of points (so it can be put through
    // MPI communication).
    bb_points[j] = static_cast<std::pair<Point, Point>>(bbox);
  }
  // Serialize the bounding box points.
  _communicator.allgather(bb_points);
  // Recast the points back into bounding boxes and return.
  std::vector<BoundingBox> bboxes(bb_points.size());
  for (const auto i : make_range(bb_points.size()))
    bboxes[i] = static_cast<BoundingBox>(bb_points[i]);
  // TODO move up
  // Check for a user-set fixed bounding box size and modify the sizes as appropriate
  if (_fixed_bbox_size != std::vector<Real>(3, 0))
    for (const auto i : make_range(LIBMESH_DIM))
      if (!MooseUtils::absoluteFuzzyEqual(_fixed_bbox_size[i], 0))
        for (const auto j : make_range(bboxes.size()))
        {
          const auto current_width = (bboxes[j].second - bboxes[j].first)(i);
          bboxes[j].first(i) -= (_fixed_bbox_size[i] - current_width) / 2;
          bboxes[j].second(i) += (_fixed_bbox_size[i] - current_width) / 2;
        }
  return bboxes;
}
Referenced by MultiAppGeneralFieldTransfer::prepareToTransfer().
getToMultiApp()
const std::shared_ptr< MultiApp > MultiAppTransfer::getToMultiApp () const inline inherited
Get the MultiApp to transfer data to.
Definition at line 73 of file MultiAppTransfer.h.
  {
    if (!_to_multi_app)
      mooseError(
          "A to_multiapp was requested but is unavailable. Check the to_multi_app parameter");
    else
      return _to_multi_app;
  }
Referenced by MultiAppCopyTransfer::execute(), MultiAppGeometricInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), MultiAppReporterTransfer::executeFromMultiapp(), MultiAppReporterTransfer::executeToMultiapp(), MultiAppVectorPostprocessorTransfer::executeToMultiapp(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppConservativeTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppReporterTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), and MultiAppConservativeTransfer::postExecute().
getToMultiAppInfo()
void MultiAppTransfer::getToMultiAppInfo () private inherited
Definition at line 428 of file MultiAppTransfer.C.
{
  if (!_to_multi_app)
    mooseError("There is no to_multiapp to get info from");
  fillInfo(*_to_multi_app, _to_local2global_map, _to_problems, _to_positions);
}
Referenced by MultiAppTransfer::getAppInfo().
getToName()
std::string MultiAppTransfer::getToName () const inline inherited
Get the name of thing being transferred to.
Returns
the name of the multiapp or "Parent"
Definition at line 98 of file MultiAppTransfer.h.
  {
    if (_to_multi_app)
      return _to_multi_app->name();
    else
      return "Parent";
  }
getToVarName()
VariableName MultiAppGeneralFieldTransfer::getToVarName (unsigned int var_index) inherited
Get the target variable name, with the suffix for array/vector variables.
Definition at line 1818 of file MultiAppGeneralFieldTransfer.C.
{
  mooseAssert(var_index < _to_var_names.size(), "No target variable at this index");
  VariableName var_name = _to_var_names[var_index];
  if (_to_var_components.size())
    var_name += "_" + std::to_string(_to_var_components[var_index]);
  return var_name;
}
Referenced by MultiAppGeneralFieldTransfer::examineLocalValueConflicts(), MultiAppGeneralFieldTransfer::examineReceivedValueConflicts(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), MultiAppGeneralFieldTransfer::outputValueConflicts(), and MultiAppGeneralFieldTransfer::setSolutionVectorValues().
getToVarNames()
virtual std::vector< AuxVariableName > MultiAppConservativeTransfer::getToVarNames () const inline override protected virtual inherited
Virtual function defining variables to transfer to.
Implements MultiAppFieldTransfer.
Definition at line 35 of file MultiAppConservativeTransfer.h.
{ return _to_var_names; }
getTransferVector()
NumericVector< Real > & MultiAppTransfer::getTransferVector (unsigned int i_local, std::string var_name) protected inherited
If we are transferring to a multiapp, return the appropriate solution vector.
Definition at line 591 of file MultiAppTransfer.C.
{
  mooseAssert(_to_multi_app, "getTransferVector only works for transfers to multiapps");
  return _to_multi_app->appTransferVector(_to_local2global_map[i_local], var_name);
}
Referenced by MultiAppNearestNodeTransfer::execute(), and MultiAppShapeEvaluationTransfer::transferVariable().
hasFromMultiApp()
bool MultiAppTransfer::hasFromMultiApp () const inline inherited
Whether the transfer owns a non-null from_multi_app.
Definition at line 112 of file MultiAppTransfer.h.
{ return !(!_from_multi_app); }
Referenced by MultiAppGeometricInterpolationTransfer::execute(), MultiAppReporterTransfer::executeFromMultiapp(), MultiAppReporterTransfer::executeToMultiapp(), MultiAppConservativeTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), and MultiAppGeneralFieldTransfer::outputValueConflicts().
hasToMultiApp()
bool MultiAppTransfer::hasToMultiApp () const inline inherited
Whether the transfer owns a non-null to_multi_app.
Definition at line 115 of file MultiAppTransfer.h.
{ return !(!_to_multi_app); }
Referenced by MultiAppReporterTransfer::executeFromMultiapp(), MultiAppReporterTransfer::executeToMultiapp(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppGeneralFieldTransfer::outputValueConflicts(), and MultiAppGeneralFieldTransfer::setSolutionVectorValues().
inBlocks() [1/4]
bool MultiAppGeneralFieldTransfer::inBlocks (const std::set< SubdomainID > & blocks, const Elem * elem) const protected inherited
Definition at line 1516 of file MultiAppGeneralFieldTransfer.C.
{
  return blocks.find(elem->subdomain_id()) != blocks.end();
}
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), MultiAppGeneralFieldTransfer::getRestrictedFromBoundingBoxes(), and MultiAppGeneralFieldTransfer::inBlocks().
inBlocks() [2/4]
bool MultiAppGeneralFieldTransfer::inBlocks (const std::set< SubdomainID > & blocks, const MooseMesh & mesh, const Elem * elem) const protected virtual inherited
Reimplemented in MultiAppGeneralFieldNearestLocationTransfer, and MultiAppGeneralFieldNearestLocationTransfer.
Definition at line 1523 of file MultiAppGeneralFieldTransfer.C.
{
  return inBlocks(blocks, elem);
}
inBlocks() [3/4]
bool MultiAppGeneralFieldTransfer::inBlocks (const std::set< SubdomainID > & blocks, const MooseMesh & mesh, const Node * node) const protected inherited
Definition at line 1531 of file MultiAppGeneralFieldTransfer.C.
{
  const std::set<SubdomainID> & node_blocks = mesh.getNodeBlockIds(*node);
  std::set<SubdomainID> u;
  std::set_intersection(blocks.begin(),
                        blocks.end(),
                        node_blocks.begin(),
                        node_blocks.end(),
                        std::inserter(u, u.begin()));
  return !u.empty();
}
inBlocks() [4/4]
bool MultiAppGeneralFieldTransfer::inBlocks (const std::set< SubdomainID > & blocks, const PointLocatorBase *const pl, const Point & pt) const protected inherited
Definition at line 1546 of file MultiAppGeneralFieldTransfer.C.
{
  const Elem * elem = (*pl)(point, &blocks);
  return (elem != nullptr);
}
initialSetup()
void MultiAppGeneralFieldTransfer::initialSetup () override virtual inherited
Method called at the beginning of the simulation for checking integrity or doing one-time setup.
Reimplemented from MultiAppConservativeTransfer.
Reimplemented in MultiAppGeneralFieldNearestLocationTransfer.
Definition at line 220 of file MultiAppGeneralFieldTransfer.C.
{
  MultiAppConservativeTransfer::initialSetup();
  // Use IDs for block and boundary restriction
  // Loop over all source problems
  for (const auto i_from : index_range(_from_problems))
  {
    const auto & from_moose_mesh = _from_problems[i_from]->mesh(_displaced_source_mesh);
    if (isParamValid("from_blocks"))
    {
      auto & blocks = getParam<std::vector<SubdomainName>>("from_blocks");
      std::vector<SubdomainID> ids = from_moose_mesh.getSubdomainIDs(blocks);
      _from_blocks.insert(ids.begin(), ids.end());
      if (_from_blocks.size() != blocks.size())
        paramError("from_blocks", "Some blocks were not found in the mesh");
    }
    if (isParamValid("from_boundaries"))
    {
      auto & boundary_names = getParam<std::vector<BoundaryName>>("from_boundaries");
      std::vector<BoundaryID> boundary_ids = from_moose_mesh.getBoundaryIDs(boundary_names);
      _from_boundaries.insert(boundary_ids.begin(), boundary_ids.end());
      if (_from_boundaries.size() != boundary_names.size())
        paramError("from_boundaries", "Some boundaries were not found in the mesh");
    }
    if (isParamValid("from_mesh_division"))
    {
      const auto & mesh_div_name = getParam<MeshDivisionName>("from_mesh_division");
      _from_mesh_divisions.push_back(&_from_problems[i_from]->getMeshDivision(mesh_div_name));
      // Check that the behavior set makes sense
      if (_from_mesh_division_behavior == MeshDivisionTransferUse::RESTRICTION)
      {
        if (_from_mesh_divisions[i_from]->coversEntireMesh())
          mooseInfo("'from_mesh_division_usage' is set to use a spatial restriction but the "
                    "'from_mesh_division' for source app of global index " +
                    std::to_string(getGlobalSourceAppIndex(i_from)) +
                    " covers the entire mesh. Do not expect any restriction from a mesh "
                    "division that covers the entire mesh");
      }
      else if (_from_mesh_division_behavior == MeshDivisionTransferUse::MATCH_DIVISION_INDEX &&
               !isParamValid("to_mesh_division"))
        paramError("to_mesh_division_usage",
                   "Source mesh division cannot match target mesh division if no target mesh "
                   "division is specified");
      else if (_from_mesh_division_behavior == MeshDivisionTransferUse::MATCH_SUBAPP_INDEX)
      {
        if (!hasToMultiApp())
          paramError("from_mesh_division_usage",
                     "Cannot match source mesh division index to target subapp index if there is "
                     "only one target: the parent app (not a subapp)");
        else if (getToMultiApp()->numGlobalApps() !=
                 _from_mesh_divisions[i_from]->getNumDivisions())
          mooseWarning("Attempting to match target subapp index with the number of source mesh "
                       "divisions, which is " +
                       std::to_string(_from_mesh_divisions[i_from]->getNumDivisions()) +
                       " while there are " + std::to_string(getToMultiApp()->numGlobalApps()) +
                       " target subapps");
        if (_to_mesh_division_behavior == MeshDivisionTransferUse::MATCH_DIVISION_INDEX)
          // We do not support it because it would require sending the point + target app index +
          // target app division index, and we only send the Point + one number
          paramError("from_mesh_division_usage",
                     "We do not support using target subapp index for source division behavior and "
                     "matching the division index for the target mesh division behavior.");
      }
      else if (_from_mesh_division_behavior == "none")
        paramError("from_mesh_division_usage", "User must specify a 'from_mesh_division_usage'");
    }
    else if (_from_mesh_division_behavior != "none")
      paramError("from_mesh_division",
                 "'from_mesh_division' must be specified if the usage method is specified");
  }
  // Loop over all target problems
  for (const auto i_to : index_range(_to_problems))
  {
    const auto & to_moose_mesh = _to_problems[i_to]->mesh(_displaced_target_mesh);
    if (isParamValid("to_blocks"))
    {
      auto & blocks = getParam<std::vector<SubdomainName>>("to_blocks");
      std::vector<SubdomainID> ids = to_moose_mesh.getSubdomainIDs(blocks);
      _to_blocks.insert(ids.begin(), ids.end());
      if (_to_blocks.size() != blocks.size())
        paramError("to_blocks", "Some blocks were not found in the mesh");
    }
    if (isParamValid("to_boundaries"))
    {
      auto & boundary_names = getParam<std::vector<BoundaryName>>("to_boundaries");
      std::vector<BoundaryID> boundary_ids = to_moose_mesh.getBoundaryIDs(boundary_names);
      _to_boundaries.insert(boundary_ids.begin(), boundary_ids.end());
      if (_to_boundaries.size() != boundary_names.size())
        paramError("to_boundaries", "Some boundaries were not found in the mesh");
    }
    if (isParamValid("to_mesh_division"))
    {
      const auto & mesh_div_name = getParam<MeshDivisionName>("to_mesh_division");
      _to_mesh_divisions.push_back(&_to_problems[i_to]->getMeshDivision(mesh_div_name));
      // Check that the behavior set makes sense
      if (_to_mesh_division_behavior == MeshDivisionTransferUse::RESTRICTION)
      {
        if (_to_mesh_divisions[i_to]->coversEntireMesh())
          mooseInfo("'to_mesh_division_usage' is set to use a spatial restriction but the "
                    "'to_mesh_division' for target application of global index " +
                    std::to_string(getGlobalSourceAppIndex(i_to)) +
                    " covers the entire mesh. Do not expect any restriction from a mesh "
                    "division that covers the entire mesh");
      }
      else if (_to_mesh_division_behavior == MeshDivisionTransferUse::MATCH_DIVISION_INDEX)
      {
        if (!isParamValid("from_mesh_division"))
          paramError("to_mesh_division_usage",
                     "Target mesh division cannot match source mesh division if no source mesh "
                     "division is specified");
        else if ((*_from_mesh_divisions.begin())->getNumDivisions() !=
                 _to_mesh_divisions[i_to]->getNumDivisions())
          mooseWarning("Source and target mesh divisions do not have the same number of bins. If "
                       "this is what you expect, please reach out to a MOOSE or app developer to "
                       "ensure appropriate use");
      }
      else if (_to_mesh_division_behavior == MeshDivisionTransferUse::MATCH_SUBAPP_INDEX)
      {
        if (!hasFromMultiApp())
          paramError(
              "to_mesh_division_usage",
              "Cannot match target mesh division index to source subapp index if there is only one "
              "source: the parent app (not a subapp)");
        else if (getFromMultiApp()->numGlobalApps() != _to_mesh_divisions[i_to]->getNumDivisions())
          mooseWarning("Attempting to match source subapp index with the number of target mesh "
                       "divisions, which is " +
                       std::to_string(_to_mesh_divisions[i_to]->getNumDivisions()) +
                       " while there are " + std::to_string(getFromMultiApp()->numGlobalApps()) +
                       " source subapps");
        if (_from_mesh_division_behavior == MeshDivisionTransferUse::MATCH_DIVISION_INDEX)
          paramError(
              "from_mesh_division_usage",
              "We do not support using source subapp index for the target division behavior and "
              "matching the division index for the source mesh division behavior.");
      }
      else if (_to_mesh_division_behavior == "none")
        paramError("to_mesh_division_usage", "User must specify a 'to_mesh_division_usage'");
    }
    else if (_to_mesh_division_behavior != "none")
      paramError("to_mesh_division",
                 "'to_mesh_division' must be specified if usage method '" +
                     Moose::stringify(_to_mesh_division_behavior) + "' is specified");
  }
  // Check if components are set correctly if using an array variable
  for (const auto i_from : index_range(_from_problems))
  {
    for (const auto var_index : make_range(_from_var_names.size()))
    {
      MooseVariableFieldBase & from_var =
          _from_problems[i_from]->getVariable(0,
                                              _from_var_names[var_index],
                                              Moose::VarKindType::VAR_ANY,
                                              Moose::VarFieldType::VAR_FIELD_ANY);
      if (from_var.count() > 1 && _from_var_components.empty())
        paramError("source_variable_components", "Component must be passed for an array variable");
      if (_from_var_components.size() && from_var.count() < _from_var_components[var_index])
        paramError("source_variable_components",
                   "Component passed is larger than size of variable");
    }
  }
  for (const auto i_to : index_range(_to_problems))
  {
    for (const auto var_index : make_range(_to_var_names.size()))
    {
      MooseVariableFieldBase & to_var =
          _to_problems[i_to]->getVariable(0,
                                          _to_var_names[var_index],
                                          Moose::VarKindType::VAR_ANY,
                                          Moose::VarFieldType::VAR_FIELD_ANY);
      if (to_var.count() > 1 && _to_var_components.empty())
        paramError("target_variable_components", "Component must be passed for an array variable");
      if (_to_var_components.size() && to_var.count() < _to_var_components[var_index])
        paramError("target_variable_components",
                   "Component passed is larger than size of variable");
    }
  }
  // Cache some quantities to avoid having to get them on every transferred point
  if (_to_problems.size())
  {
    _to_variables.resize(_to_var_names.size());
    for (const auto i_var : index_range(_to_var_names))
      _to_variables[i_var] = &_to_problems[0]->getVariable(
          0, _to_var_names[i_var], Moose::VarKindType::VAR_ANY, Moose::VarFieldType::VAR_FIELD_ANY);
  }
}
Referenced by MultiAppGeneralFieldNearestLocationTransfer::initialSetup().
inMesh()
bool MultiAppGeneralFieldTransfer::inMesh (const PointLocatorBase *const pl, const Point & pt) const protected inherited
Definition at line 1507 of file MultiAppGeneralFieldTransfer.C.
{
  // Note: we do not take advantage of a potential block restriction of the mesh here. This is
  // because we can avoid this routine by calling inBlocks() instead
  const Elem * elem = (*pl)(point);
  return (elem != nullptr);
}
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), and MultiAppGeneralFieldNearestLocationTransfer::checkRestrictionsForSource().
isParamSetByUser()
bool MooseBaseParameterInterface::isParamSetByUser (const std::string & nm) const inline inherited
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
Parameters
nm The name of the parameter to test
Definition at line 108 of file MooseBaseParameterInterface.h.
{ return _pars.isParamSetByUser(nm); }
Referenced by SetAdaptivityOptionsAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), LibtorchNeuralNetControl::conditionalParameterError(), MooseBaseParameterInterface::getRenamedParam(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), PiecewiseTabularBase::PiecewiseTabularBase(), MooseMesh::prepare(), and SolutionUserObject::readXda().
isParamValid()
bool MooseBaseParameterInterface::isParamValid (const std::string & name) const inline inherited
Test if the supplied parameter is valid.
Parameters
name The name of the parameter to test
Definition at line 102 of file MooseBaseParameterInterface.h.
{ return _pars.isParamValid(name); }
Referenced by AddDriftDiffusionAction::act(), AddSpecies::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CopyNodalVarsAction::act(), CreateDisplacedProblemAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), AddGeneralReactions::AddGeneralReactions(), AddZapdosReactions::AddZapdosReactions(), AdvectiveFluxAux::AdvectiveFluxAux(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), GeneratedMesh::buildMesh(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), ChemicalReactionsBase::ChemicalReactionsBase(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), CombinerGenerator::CombinerGenerator(), CSVReader::CSVReader(), ConstantReporter::declareConstantReporterValues(), DGKernelBase::DGKernelBase(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EEDFEnergyTownsendLog::EEDFEnergyTownsendLog(), Eigenvalue::Eigenvalue(), ElectronEnergyTermRate::ElectronEnergyTermRate(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), PIDTransientControl::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FileOutput::FileOutput(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FunctionDT::FunctionDT(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getRenamedParam(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), Terminator::handleMessage(), HeavySpeciesTempl< is_ad >::HeavySpeciesTempl(), HFEMDirichletBC::HFEMDirichletBC(), EigenExecutionerBase::init(), Eigenvalue::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), MooseParsedFunction::initialSetup(), MooseParsedGradFunction::initialSetup(), MooseParsedVectorFunction::initialSetup(), PiecewiseTabularBase::initialSetup(), SolutionFunction::initialSetup(), Console::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), IterationAdaptiveDT::IterationAdaptiveDT(), LeastSquaresFit::LeastSquaresFit(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MatCoupledForce::MatCoupledForce(), MooseMesh::MooseMesh(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarConsumerInterface::MortarConsumerInterface(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalExtremeValue::NodalExtremeValue(), EigenExecutionerBase::normalizeSolution(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PetscOutput::PetscOutput(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), PicardSolve::PicardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseTabularBase::PiecewiseTabularBase(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), MooseMesh::prepare(), MultiApp::readCommandLineArguments(), SolutionUserObject::readExodusII(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), MooseMesh::setCoordSystem(), FileOutput::setFileBase(), FileOutput::setFileBaseInternal(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SideDiffusiveFluxIntegralTempl< is_ad, T >::SideDiffusiveFluxIntegralTempl(), SideExtremeValue::SideExtremeValue(), SolutionUserObject::SolutionUserObject(), Terminator::Terminator(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), MultiAppDofCopyTransfer::transfer(), TransformGenerator::TransformGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
jacobianSetup()
void SetupInterface::jacobianSetup () virtual inherited
Gets called just before the Jacobian is computed and before this object is asked to do its job.
Reimplemented in EqualValueEmbeddedConstraint, Function, ADKernelTempl< T >, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 50 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::jacobianSetup(), and ComputeFVFluxJacobianThread< RangeType >::setup().
locatePointReceivers()
void MultiAppGeneralFieldTransfer::locatePointReceivers (const Point point, std::set< processor_id_type > & processors) private inherited
Definition at line 536 of file MultiAppGeneralFieldTransfer.C.
{
  // Check which processors have apps that may include or be near this point
  // A point may be close enough to several problems, hosted on several processes
  bool found = false;
  // Additional process-restriction techniques we could use (TODOs):
  // - nearest_positions/_app could use its own heuristic
  // - from_mesh_divisions could be polled for which divisions they possess on each
  //   process, depending on the behavior chosen. This could limit potential senders.
  //   This should be done ahead of this function call, for all points at once
  // Select the method for determining the apps receiving points/sending values
  if (_use_bounding_boxes)
  {
    // We examine all bounding boxes and find the maximum distance within a bounding box
    // from the point. This creates a sphere around the point of interest. Any app with a bounding
    // box that intersects this sphere (with a bboxMinDistance < nearest_max_distance) will be
    // considered a potential source.
    // NOTE: This is a heuristic. We could try others
    // NOTE: from_bboxes are in the reference space, as is the point
    Real nearest_max_distance = std::numeric_limits<Real>::max();
    for (const auto & bbox : _from_bboxes)
    {
      Real distance = bboxMaxDistance(point, bbox);
      if (distance < nearest_max_distance)
        nearest_max_distance = distance;
    }
    unsigned int from0 = 0;
    for (processor_id_type i_proc = 0; i_proc < n_processors();
         from0 += _froms_per_proc[i_proc], ++i_proc)
      for (unsigned int i_from = from0; i_from < from0 + _froms_per_proc[i_proc]; ++i_from)
      {
        Real distance = bboxMinDistance(point, _from_bboxes[i_from]);
        // We will not break here because we want to send a point to all possible source domains
        if (_greedy_search || distance <= nearest_max_distance ||
            _from_bboxes[i_from].contains_point(point))
        {
          processors.insert(i_proc);
          found = true;
        }
      }
  }
  // Greedy search will contact every single processor. It's not scalable, but if there's valid data
  // on any subapp on any process, it will find it
  else if (_greedy_search)
  {
    found = true;
    for (const auto i_proc : make_range(n_processors()))
      processors.insert(i_proc);
  }
  // Since we indicated that we only wanted values from a subapp with the same global index as the
  // target mesh division, we might as well only communicate with the process that owns this app
  else if (!_to_mesh_divisions.empty() &&
           _to_mesh_division_behavior == MeshDivisionTransferUse::MATCH_SUBAPP_INDEX)
  {
    // The target point could have a different index in each target mesh division. So on paper, we
    // would need to check all of them.
    auto saved_target_div = MooseMeshDivision::INVALID_DIVISION_INDEX;
    for (const auto i_to : index_range(_to_meshes))
    {
      const auto target_div = _to_mesh_divisions[i_to]->divisionIndex(
          _to_transforms[getGlobalTargetAppIndex(i_to)]->mapBack(point));
      // If it's the same division index, do not redo the search
      if (target_div == saved_target_div)
        continue;
      else
        saved_target_div = target_div;
      // Look for the processors owning a source-app with an index equal to the target mesh division
      for (const auto i_proc : make_range(n_processors()))
        for (const auto i_from : make_range(_froms_per_proc[i_proc]))
          if (target_div == _global_app_start_per_proc[i_proc] + i_from)
          {
            processors.insert(i_proc);
            found = true;
          }
    }
  }
  else
    mooseError("No algorithm were selected to find which processes may send value data "
               "for a each target point. Please either specify using bounding boxes, "
               "greedy search, or to_mesh_division-based parameters");
  // Error out if we could not find this point when ask us to do so
  if (!found && _error_on_miss)
    mooseError("Cannot locate point ", point, " \n ", "mismatched meshes are used");
}
Referenced by MultiAppGeneralFieldTransfer::cacheOutgoingPointInfo().
mooseDeprecated()
template<typename... Args> void MooseBaseErrorInterface::mooseDeprecated (Args &&... args) const inline inherited
Definition at line 78 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseDeprecatedStream(_console, false, true, std::forward<Args>(args)...);
  }
Referenced by FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::advanceMultiApps(), MultiApp::appProblem(), Executioner::augmentedPicardConvergenceCheck(), MooseMesh::buildSideList(), FEProblemBase::computeResidual(), AddVariableAction::determineType(), Eigenvalue::Eigenvalue(), MooseMesh::elem(), FunctionDT::FunctionDT(), RandomICBase::generateRandom(), MooseMesh::getBoundariesToElems(), Control::getExecuteOptions(), FEProblemBase::getNonlinearSystem(), FEProblemBase::getUserObjects(), FEProblemBase::hasPostprocessor(), MooseMesh::node(), FixedPointSolve::numPicardIts(), RelationshipManager::operator>=(), Executioner::picardSolve(), and MooseMesh::setBoundaryToNormalMap().
mooseError()
template<typename... Args> void MooseBaseErrorInterface::mooseError (Args &&... args) const inline inherited
Emits an error prefixed with object name and type.
Definition at line 38 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, errorPrefix("error"), std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
Referenced by HierarchicalGridPartitioner::_do_partition(), PetscExternalPartitioner::_do_partition(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AdaptivityAction::act(), AddFVICAction::act(), AddICAction::act(), AddMeshGeneratorAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVectorPostprocessorAction::act(), CheckFVBCAction::act(), CheckIntegrityAction::act(), CommonOutputAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DeprecatedBlockAction::act(), InitProblemAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetAdaptivityOptionsAction::act(), SetupMeshAction::act(), SetupMeshCompleteAction::act(), SetupPredictorAction::act(), SetupTimeStepperAction::act(), SplitMeshAction::act(), FEProblemBase::adaptMesh(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::addConstraint(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFVInitialCondition(), AddGeneralReactions::AddGeneralReactions(), FEProblemBase::addInitialCondition(), FEProblemBase::addLineSearch(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addOutput(), SubProblem::addPiecewiseByBlockLambdaFunctor(), DistributedRectilinearMeshGenerator::addPoint(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), FEProblemBase::addPostprocessor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseMesh::addQuadratureNode(), FEProblemBase::addReporter(), AddVariableAction::addVariable(), FEProblemBase::addVectorPostprocessor(), SubProblem::addVectorTag(), AddZapdosReactions::AddZapdosReactions(), ADEEDFRateConstantTownsend::ADEEDFRateConstantTownsend(), ADGasElectronMoments::ADGasElectronMoments(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), MooseVariableScalar::adUDot(), Output::advancedExecuteOn(), AdvectiveFluxAux::AdvectiveFluxAux(), ADZapdosEEDFRateConstant::ADZapdosEEDFRateConstant(), MooseVariableBase::allDofIndices(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayConstantIC::ArrayConstantIC(), ArrayFunctionIC::ArrayFunctionIC(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), Function::average(), Axisymmetric2D3DSolutionFunction::Axisymmetric2D3DSolutionFunction(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), BoltzmannSolverScalar::BoltzmannSolverScalar(), BoundingValueElementDamper::BoundingValueElementDamper(), BoundingValueNodalDamper::BoundingValueNodalDamper(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), MooseMesh::buildCoarseningMap(), MultiApp::buildComm(), DistributedRectilinearMeshGenerator::buildCube(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), PiecewiseTabularBase::buildFromXY(), MooseMesh::buildLowerDMesh(), GeneratedMesh::buildMesh(), MeshGeneratorMesh::buildMesh(), SpiralAnnularMesh::buildMesh(), TiledMesh::buildMesh(), ImageMesh::buildMesh3D(), ImageMeshGenerator::buildMesh3D(), MooseMesh::buildRefinementMap(), MaterialBase::buildRequiredMaterials(), MooseMesh::buildSideList(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), UserObjectInterface::castUserObject(), EigenExecutionerBase::chebyshev(), SubProblem::checkBlockMatProps(), SubProblem::checkBoundaryMatProps(), MooseMesh::checkCoordinateSystems(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkDisplacementOrders(), FEProblemBase::checkDuplicatePostprocessorVariableNames(), MooseMesh::checkDuplicateSubdomainNames(), MaterialBase::checkExecutionStage(), MeshGenerator::checkGetMesh(), ReporterTransferInterface::checkHasReporterValue(), FEProblemBase::checkICRestartError(), EigenExecutionerBase::checkIntegrity(), Eigenvalue::checkIntegrity(), Steady::checkIntegrity(), ExplicitTimeIntegrator::checkLinearConvergence(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), PostprocessorInterface::checkParam(), FEProblemBase::checkProblemIntegrity(), Sampler::checkReinitStatus(), MaterialBase::checkStatefulSanity(), FEProblemBase::checkUserObjects(), MultiAppTransfer::checkVariable(), DomainUserObject::checkVariable(), ChemicalReactionsBase::ChemicalReactionsBase(), MooseMesh::clone(), LibmeshPartitioner::clone(), CombinerGenerator::CombinerGenerator(), ElementSubdomainModifier::complementMovingBoundaryID(), ElementSubdomainModifier::complementMovingBoundaryName(), MooseVariableFieldBase::componentName(), CompositeFunction::CompositeFunction(), NodalPatchRecovery::compute(), VariableCondensationPreconditioner::computeDInverseDiag(), CompositionDT::computeDT(), MooseVariableFieldBase::computeFaceValues(), TimeStepper::computeFailedDT(), IterationAdaptiveDT::computeFailedDT(), TimeSequenceStepperBase::computeFailedDT(), MooseMesh::computeFiniteVolumeCoords(), FVFluxKernel::computeJacobian(), ArrayKernel::computeJacobian(), ArrayKernel::computeOffDiagJacobian(), FVElementalKernel::computeOffDiagJacobian(), MaterialBase::computeProperties(), ScalarKernel::computeQpJacobian(), ScalarKernel::computeQpResidual(), FVFluxKernel::computeResidual(), ArrayKernel::computeResidual(), FVFluxBC::computeResidual(), ResidualObject::computeResidualAndJacobian(), FVFluxKernel::computeResidualAndJacobian(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualL2Norm(), FEProblemBase::computeResidualTag(), FEProblemBase::computeResidualType(), TimeStepper::computeStep(), ActuallyExplicitEuler::computeTimeDerivatives(), AStableDirk4::computeTimeDerivatives(), BDF2::computeTimeDerivatives(), CrankNicolson::computeTimeDerivatives(), ExplicitEuler::computeTimeDerivatives(), ExplicitRK2::computeTimeDerivatives(), ExplicitTVDRK2::computeTimeDerivatives(), ImplicitEuler::computeTimeDerivatives(), ImplicitMidpoint::computeTimeDerivatives(), LStableDirk2::computeTimeDerivatives(), LStableDirk3::computeTimeDerivatives(), LStableDirk4::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), FEProblemBase::computeUserObjectsInternal(), BolsigValueScalar::computeValue(), PenetrationAux::computeValue(), BuildArrayVariableAux::computeValue(), TagVectorArrayVariableAux::computeValue(), ConcentricCircleMesh::ConcentricCircleMesh(), ConditionalEnableControl::ConditionalEnableControl(), TimeStepper::constrainStep(), LibtorchNeuralNetControl::controlNeuralNet(), AddVariableAction::createInitialConditionAction(), DataRead::DataRead(), ReporterTransferInterface::declareClone(), MeshGenerator::declareMeshProperty(), ReporterTransferInterface::declareVectorClone(), FunctorRelationshipManager::delete_remote_elements(), MooseMesh::deleteRemoteElements(), BicubicSplineFunction::derivative(), MooseMesh::detectPairedSidesets(), FEProblemBase::determineNonlinearSystem(), MeshDiagnosticsGenerator::diagnosticsLog(), DiffusionRateTemp::DiffusionRateTemp(), FunctorBinnedValuesDivision::divisionIndex(), FunctorRelationshipManager::dofmap_reinit(), FEProblemBase::duplicateVariableCheck(), EEDFRateConstant::EEDFRateConstant(), EEDFRateConstantTownsend::EEDFRateConstantTownsend(), Eigenvalue::Eigenvalue(), ElectricField::ElectricField(), ElectronMobility::ElectronMobility(), ElementIntegerAux::ElementIntegerAux(), ElementQualityAux::ElementQualityAux(), ElementUOAux::ElementUOAux(), DistributedRectilinearMeshGenerator::elemId(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), MooseMesh::errorIfDistributedMesh(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), BoltzmannSolverScalar::execute(), Eigenvalue::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), ElementQualityChecker::execute(), DiscreteElementUserObject::execute(), DomainUserObject::execute(), FEProblemBase::execute(), FEProblemBase::executeControls(), MultiAppVectorPostprocessorTransfer::executeFromMultiapp(), MultiAppVectorPostprocessorTransfer::executeToMultiapp(), ExplicitSSPRungeKutta::ExplicitSSPRungeKutta(), FileOutput::FileOutput(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), ElementQualityChecker::finalize(), VerifyElementUniqueID::finalize(), VerifyNodalUniqueID::finalize(), DiscreteElementUserObject::finalize(), Transfer::find_sys(), BreakMeshByBlockGeneratorBase::findFreeBoundaryId(), FunctionDT::FunctionDT(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), GapValueAux::GapValueAux(), Gas::Gas(), GasBase::GasBase(), GasElectronMoments::GasElectronMoments(), AllSideSetsByNormalsGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundingBoxNodeSetGenerator::generate(), BreakMeshByBlockGenerator::generate(), CombinerGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshCollectionGenerator::generate(), MeshDiagnosticsGenerator::generate(), MeshExtruderGenerator::generate(), MeshRepairGenerator::generate(), MoveNodeGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), SideSetsFromNormalsGenerator::generate(), SideSetsFromPointsGenerator::generate(), SmoothMeshGenerator::generate(), SpiralAnnularMeshGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), TiledMeshGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GeneratedMesh::GeneratedMesh(), GeneratedMeshGenerator::GeneratedMeshGenerator(), MeshGenerator::generateInternal(), CircularBoundaryCorrectionGenerator::generateRadialCorrectionFactor(), RandomICBase::generateRandom(), GenericConstantMaterialTempl< is_ad >::GenericConstantMaterialTempl(), GenericConstantVectorMaterialTempl< is_ad >::GenericConstantVectorMaterialTempl(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), DisplacedProblem::getActualFieldVariable(), FEProblemBase::getActualFieldVariable(), DisplacedProblem::getArrayVariable(), FEProblemBase::getArrayVariable(), MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::getBlockConnectedBlocks(), VariableOldValueBoundsAux::getBound(), MooseMesh::getBoundaryID(), MultiApp::getBoundingBox(), MooseMesh::getCoarseningMap(), MooseVariableBase::getContinuity(), Control::getControllableParameterByName(), MooseMesh::getCoordSystem(), PropertyReadFile::getData(), TransfiniteMeshGenerator::getDiscreteEdge(), FEProblemBase::getDistribution(), MooseVariableBase::getDofIndices(), VariableCondensationPreconditioner::getDofToCondense(), TransfiniteMeshGenerator::getEdge(), GhostingUserObject::getElementalValue(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), PropertyReadFile::getElementData(), MooseMesh::getElementIDIndex(), Material::getElementIDNeighbor(), Material::getElementIDNeighborByName(), MooseMesh::getElemIDMapping(), MooseMesh::getElemIDsOnBlocks(), MultiAppFieldTransfer::getEquationSystem(), MultiApp::getExecutioner(), MultiAppTransfer::getFromMultiApp(), MultiAppTransfer::getFromMultiAppInfo(), FEProblemBase::getFunction(), SubProblem::getFunctor(), MooseMesh::getGeneralAxisymmetricCoordAxis(), DistributedRectilinearMeshGenerator::getGhostNeighbors(), BatchMaterial< Tuple, Output, Input >::getIndex(), DistributedRectilinearMeshGenerator::getIndices(), SolutionUserObject::getLocalVarIndex(), Material::getMaterialByName(), FEProblemBase::getMaterialData(), SubProblem::getMatrixTagID(), AnnularMesh::getMaxInDimension(), GeneratedMesh::getMaxInDimension(), FEProblemBase::getMaxQps(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), AnnularMesh::getMinInDimension(), GeneratedMesh::getMinInDimension(), MultiAppTransfer::getMultiApp(), DistributedRectilinearMeshGenerator::getNeighbors(), MooseMesh::getNodeBlockIds(), PropertyReadFile::getNodeData(), MooseMesh::getNodeList(), FEProblemBase::getNonlinearSystem(), MooseMesh::getPairedBoundaryMapping(), ImageMesh::GetPixelInfo(), ImageMeshGenerator::GetPixelInfo(), PlaneIDMeshGenerator::getPlaneID(), FEProblemBase::getPositionsObject(), PostprocessorInterface::getPostprocessorValueByNameInternal(), MooseMesh::getRefinementMap(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), FEProblemBase::getSampler(), JSONFileReader::getScalar(), DisplacedProblem::getScalarVariable(), FEProblemBase::getScalarVariable(), DisplacedProblem::getStandardVariable(), FEProblemBase::getStandardVariable(), MooseMesh::getSubdomainBoundaryIds(), DisplacedProblem::getSystem(), FEProblemBase::getSystem(), FEProblemBase::getTimeFromStateArg(), Transient::getTimeIntegratorName(), MultiAppTransfer::getToMultiApp(), MultiAppTransfer::getToMultiAppInfo(), MooseMesh::getUniqueCoordSystem(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::getUserObjectName(), JSONFileReader::getVector(), VectorPostprocessorInterface::getVectorPostprocessorName(), SubProblem::getVectorTag(), SubProblem::getVectorTagID(), DisplacedProblem::getVectorVariable(), FEProblemBase::getVectorVariable(), GhostingAux::GhostingAux(), MultiApp::globalAppToLocal(), Function::gradient(), MooseParsedVectorFunction::gradient(), Terminator::handleMessage(), MooseVariableBase::hasDoFsOnNodes(), PostprocessorInterface::hasPostprocessor(), PostprocessorInterface::hasPostprocessorByName(), ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), AddVariableAction::init(), MooseMesh::init(), Sampler::init(), AddAuxVariableAction::init(), EigenExecutionerBase::init(), Eigenvalue::init(), Transient::init(), FEProblemBase::init(), CrankNicolson::init(), ExplicitTimeIntegrator::init(), CSVTimeSequenceStepper::init(), IterationAdaptiveDT::init(), MultiApp::init(), FEProblemBase::initialAdaptMesh(), BoltzmannSolverScalar::initialize(), PolynomialCoefficients::initialize(), CartesianGridDivision::initialize(), CylindricalGridDivision::initialize(), NestedDivision::initialize(), SphericalGridDivision::initialize(), SubProblem::initialSetup(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), Axisymmetric2D3DSolutionFunction::initialSetup(), MooseParsedFunction::initialSetup(), SolutionFunction::initialSetup(), SolutionIC::initialSetup(), FullSolveMultiApp::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), SolutionUserObject::initialSetup(), Function::integral(), InterpolatedCoefficientLinear::InterpolatedCoefficientLinear(), InterpolatedCoefficientSpline::InterpolatedCoefficientSpline(), EigenExecutionerBase::inversePowerIteration(), InversePowerMethod::InversePowerMethod(), Sampler::isAdaptiveSamplingCompleted(), MooseMesh::isBoundaryFullyExternalToSubdomains(), MooseVariableBase::isNodal(), IterationAdaptiveDT::IterationAdaptiveDT(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LineSearch::lineSearch(), ReporterPointMarker::markerSetup(), Material::Material(), MaterialOutputAction::materialOutputHelper(), MaterialRealTensorValueAux::MaterialRealTensorValueAux(), MaterialRealVectorValueAuxTempl< is_ad >::MaterialRealVectorValueAuxTempl(), Distribution::median(), FunctorRelationshipManager::mesh_reinit(), SubProblem::meshChanged(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshExtruderGenerator::MeshExtruderGenerator(), MeshRepairGenerator::MeshRepairGenerator(), SetupMeshAction::modifyParamsForUseSplit(), MeshMetaDataInterface::mooseErrorInternal(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MoveNodeGenerator::MoveNodeGenerator(), ElementSubdomainModifier::movingBoundaryID(), ElementSubdomainModifier::movingBoundaryName(), MultiApp::MultiApp(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NearestNodeDistanceAux::NearestNodeDistanceAux(), NearestNodeValueAux::NearestNodeValueAux(), FEProblemBase::needsPreviousNewtonIteration(), NewmarkBeta::NewmarkBeta(), NodalPatchRecoveryBase::nodalPatchRecovery(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), DistributedRectilinearMeshGenerator::nodeId(), DistributedRectilinearMeshGenerator::numNeighbors(), Output::onInterval(), FunctorRelationshipManager::operator()(), RelationshipManager::operator==(), MortarNodalGeometryOutput::output(), Output::Output(), DistributedRectilinearMeshGenerator::paritionSquarely(), PiecewiseBilinear::parse(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), ExplicitTimeIntegrator::performExplicitSolve(), PetscExternalPartitioner::PetscExternalPartitioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), Executioner::picardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseMulticonstant::PiecewiseMulticonstant(), PiecewiseTabularBase::PiecewiseTabularBase(), SolutionUserObject::pointValueGradientWrapper(), SolutionUserObject::pointValueWrapper(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName(), AStableDirk4::postResidual(), ExplicitRK2::postResidual(), ExplicitTVDRK2::postResidual(), ImplicitMidpoint::postResidual(), LStableDirk2::postResidual(), LStableDirk3::postResidual(), LStableDirk4::postResidual(), VariableCondensationPreconditioner::preallocateCondensedJacobian(), Predictor::Predictor(), Transient::preExecute(), MooseMesh::prepare(), MooseMesh::prepared(), FixedPointSolve::printFixedPointConvergenceReason(), RateCoefficientProvider::RateCoefficientProvider(), RateCoefficientProvider::reaction_coefficient(), RateCoefficientProvider::reaction_coefficient_derivative(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readExodusII(), SolutionUserObject::readXda(), FunctorRelationshipManager::redistribute(), Sampler::reinit(), RinglebMesh::RinglebMesh(), RinglebMeshGenerator::RinglebMeshGenerator(), PiecewiseMultiInterpolation::sample(), ScalarComponentIC::ScalarComponentIC(), ScalarLinearInterpolation::ScalarLinearInterpolation(), ScalarSplineInterpolation::ScalarSplineInterpolation(), DistributedRectilinearMeshGenerator::scaleNodalPositions(), BicubicSplineFunction::secondDerivative(), FunctorRelationshipManager::set_mesh(), MooseVariableBase::setActiveTags(), DistributedRectilinearMeshGenerator::setBoundaryNames(), MooseMesh::setCoordSystem(), FEProblemBase::setCoupling(), PiecewiseBase::setData(), FileOutput::setFileBaseInternal(), MooseMesh::setGeneralAxisymmetricCoordAxes(), FEProblemSolve::setInnerSolve(), MeshGenerator::setMeshProperty(), FEProblemBase::setNonlocalCouplingMatrix(), Sampler::setNumberOfCols(), Sampler::setNumberOfRandomSeeds(), Sampler::setNumberOfRows(), Split::setup(), TransientMultiApp::setupApp(), SetupMeshAction::setupMesh(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), TimePeriodBase::setupTimes(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SideSetsFromNormalsGenerator::SideSetsFromNormalsGenerator(), SideSetsFromPointsGenerator::SideSetsFromPointsGenerator(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), SolutionTimeAdaptiveDT::SolutionTimeAdaptiveDT(), SolutionUserObject::SolutionUserObject(), FullSolveMultiApp::solveStep(), UserObject::spatialPoints(), UserObject::spatialValue(), SpiralAnnularMesh::SpiralAnnularMesh(), SpiralAnnularMeshGenerator::SpiralAnnularMeshGenerator(), StitchedMesh::StitchedMesh(), MaterialBase::subdomainSetup(), GeneralUserObject::subdomainSetup(), NodalUserObject::subdomainSetup(), Constraint::subdomainSetup(), SuperelasticReactionRate::SuperelasticReactionRate(), FEProblemBase::swapBackMaterialsNeighbor(), Terminator::Terminator(), GeneralUserObject::threadJoin(), ThreadedGeneralUserObject::threadJoin(), DiscreteElementUserObject::threadJoin(), TimePeriodBase::TimePeriodBase(), VectorPostprocessorVisualizationAux::timestepSetup(), FEProblemBase::trustUserCouplingMatrix(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), FEProblemBase::uDotDotOldRequested(), MooseVariableScalar::uDotOld(), FEProblemBase::uDotOldRequested(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), SolutionUserObject::updateExodusBracketingTimeIndices(), FEProblemBase::updateMaxQps(), BoundingBoxIC::value(), Function::value(), Axisymmetric2D3DSolutionFunction::value(), PiecewiseConstantFromCSV::value(), ValueProvider::ValueProvider(), ValueRangeMarker::ValueRangeMarker(), ValueThresholdMarker::ValueThresholdMarker(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), MultiAppTransfer::variableIntegrityCheck(), VariableTimeIntegrationAux::VariableTimeIntegrationAux(), AddVariableAction::variableType(), Function::vectorCurl(), SubProblem::vectorTagName(), SubProblem::vectorTagType(), Function::vectorValue(), MooseParsedFunction::vectorValue(), MooseParsedGradFunction::vectorValue(), SubProblem::verifyVectorTags(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
mooseErrorNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseErrorNonPrefixed (Args &&... args) const inline inherited
Emits an error without the prefixing included in mooseError().
Definition at line 50 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
mooseInfo()
template<typename... Args> void MooseBaseErrorInterface::mooseInfo (Args &&... args) const inline inherited
Definition at line 84 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseInfoStream(_console, std::forward<Args>(args)...);
  }
Referenced by AddZapdosReactions::act(), SetupRecoverFileBaseAction::act(), AStableDirk4::AStableDirk4(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), BoltzmannSolverScalar::execute(), ExplicitRK2::ExplicitRK2(), ExplicitTVDRK2::ExplicitTVDRK2(), MultiAppTransfer::getPointInTargetAppFrame(), ImplicitMidpoint::ImplicitMidpoint(), InversePowerMethod::InversePowerMethod(), LStableDirk2::LStableDirk2(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), NonlinearEigen::NonlinearEigen(), ProjectionAux::ProjectionAux(), FEProblemBase::setRestartFile(), and SymmetryTransformGenerator::SymmetryTransformGenerator().
mooseWarning()
template<typename... Args> void MooseBaseErrorInterface::mooseWarning (Args &&... args) const inline inherited
Emits a warning prefixed with object name and type.
Definition at line 62 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(
        _console, errorPrefix("warning"), std::forward<Args>(args)...);
  }
Referenced by AddFunctionAction::act(), AddKernelAction::act(), CommonOutputAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupMeshAction::act(), DumpObjectsProblem::addAuxVariable(), DiracKernelBase::addPoint(), BoundaryMarker::BoundaryMarker(), BoundsAuxBase::BoundsAuxBase(), DistributedRectilinearMeshGenerator::buildCube(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), CartesianMeshGenerator::CartesianMeshGenerator(), CheckOutputAction::checkConsoleOutput(), MultiAppTransfer::checkMultiAppExecuteOn(), GapValueAux::computeValue(), MeshDiagnosticsGenerator::diagnosticsLog(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), Postprocessor::evaluateDotWarning(), ElementQualityChecker::finalize(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FixedPointSolve::FixedPointSolve(), ElementSubdomainIDGenerator::generate(), ParsedGenerateSideset::generate(), MultiAppTransfer::getAppInfo(), FunctorBinnedValuesDivision::getBinIndex(), FEProblemBase::getMaterial(), Terminator::handleMessage(), MaterialBase::initStatefulProperties(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::mesh(), NewmarkBeta::NewmarkBeta(), NodalPatchRecovery::NodalPatchRecovery(), Output::Output(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), Executioner::problem(), PropertyReadFile::readData(), TestSourceStepper::rejectStep(), MaterialBase::resetQpProperties(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setCoordSystem(), FEProblemBase::sizeZeroes(), TransientMultiApp::solveStep(), TimeDerivativeAux::TimeDerivativeAux(), PiecewiseConstantFromCSV::value(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
mooseWarningNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseWarningNonPrefixed (Args &&... args) const inline inherited
Emits a warning without the prefixing included in mooseWarning().
Definition at line 72 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(_console, std::forward<Args>(args)...);
  }
name()
virtual const std::string & MooseBase::name () const inline virtual inherited
Get the name of the class.
Returns
The name of the class
Reimplemented in MooseVariableBase.
Definition at line 47 of file MooseBase.h.
{ return _name; }
Referenced by HierarchicalGridPartitioner::_do_partition(), AdaptivityAction::act(), AddElementalFieldAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVariableAction::act(), CopyNodalVarsAction::act(), DeprecatedBlockAction::act(), DisplayGhostingAction::act(), MaterialOutputAction::act(), AddDriftDiffusionAction::addADKernels(), FEProblemBase::addAnyRedistributers(), Executioner::addAttributeReporter(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFunctorMaterial(), FunctorMaterial::addFunctorProperty(), FunctorMaterial::addFunctorPropertyByBlocks(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), ADDGKernel::ADDGKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), SubProblem::addPiecewiseByBlockLambdaFunctor(), FEProblemBase::addPostprocessor(), UserObject::addPostprocessorDependencyHelper(), InitialConditionBase::addPostprocessorDependencyHelper(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), UserObject::addUserObjectDependencyHelper(), AuxKernelTempl< ComputeValueType >::addUserObjectDependencyHelper(), InitialConditionBase::addUserObjectDependencyHelper(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), UserObject::addVectorPostprocessorDependencyHelper(), FVFluxKernel::adjustRMGhostLayers(), ADSurfaceCharge::ADSurfaceCharge(), Output::advancedExecuteOn(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayDGKernel::ArrayDGKernel(), ArrayParsedAux::ArrayParsedAux(), AStableDirk4::AStableDirk4(), Function::average(), MultiApp::backup(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), PiecewiseTabularBase::buildFromFile(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkICRestartError(), Damper::checkMinDamping(), Coupleable::checkWritableVar(), CompositeFunction::CompositeFunction(), MaterialBase::computeProperties(), FEProblemBase::computeUserObjectByName(), VectorPostprocessorVisualizationAux::computeValue(), MooseBaseParameterInterface::connectControllableParams(), BatchMaterial< Tuple, Output, Input >::construct(), MultiApp::createApp(), AddVariableAction::createInitialConditionAction(), MultiApp::createLocalApp(), MeshGeneratorSystem::createMeshGeneratorOrder(), MaterialBase::declareADProperty(), MeshGenerator::declareMeshesForSubByName(), MeshGenerator::declareNullMeshName(), MaterialBase::declareProperty(), DOFMapOutput::demangle(), DerivativeSumMaterialTempl< is_ad >::DerivativeSumMaterialTempl(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DomainUserObject::DomainUserObject(), DumpObjectsProblem::dumpObjectHelper(), EconomouDielectricBC::EconomouDielectricBC(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementValueSampler::ElementValueSampler(), MooseMesh::errorIfDistributedMesh(), MooseBaseErrorInterface::errorPrefix(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), PointValue::execute(), RestartableDataReporter::execute(), MultiAppNearestNodeTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), MultiApp::fillPositions(), PointSamplerBase::finalize(), FunctionDT::FunctionDT(), FVFunctionIC::functionName(), FunctionIC::functionName(), FunctorPositions::FunctorPositions(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), BoundaryDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), GeneratedMeshGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MeshGenerator::generateInternal(), InterfaceMaterial::getADMaterialProperty(), Material::getADMaterialProperty(), MultiAppTransfer::getAppInfo(), MultiApp::getBoundingBox(), Control::getControllableParameterByName(), Control::getControllableValue(), Control::getControllableValueByName(), UserObject::getDependObjects(), FEProblemBase::getDistribution(), DistributionInterface::getDistribution(), DistributionInterface::getDistributionByName(), AddZapdosReactions::getElectronImpactKernelName(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), MultiApp::getExecutioner(), FEProblemBase::getExecutor(), OutputWarehouse::getFileNumbers(), FEProblemBase::getFunction(), SubProblem::getFunctor(), AuxKernelTempl< ComputeValueType >::getGenericMaterialProperty(), NodalPatchRecovery::getGenericMaterialProperty(), InterfaceMaterial::getGenericMaterialProperty(), Material::getGenericMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialPropertyByName(), Material::getGenericOptionalMaterialProperty(), MaterialBase::getGenericZeroMaterialProperty(), BatchMaterial< Tuple, Output, Input >::getIndex(), AddZapdosReactions::getKernelName(), SolutionUserObject::getLocalVarIndex(), Marker::getMarkerValue(), Material::getMaterial(), FEProblemBase::getMaterial(), Material::getMaterialByName(), AuxKernelTempl< ComputeValueType >::getMaterialProperty(), NodalPatchRecovery::getMaterialProperty(), InterfaceMaterial::getMaterialProperty(), Material::getMaterialProperty(), SubProblem::getMaterialPropertyBlockNames(), SubProblem::getMaterialPropertyBoundaryNames(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOld(), NodalPatchRecovery::getMaterialPropertyOld(), InterfaceMaterial::getMaterialPropertyOld(), Material::getMaterialPropertyOld(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOlder(), NodalPatchRecovery::getMaterialPropertyOlder(), InterfaceMaterial::getMaterialPropertyOlder(), Material::getMaterialPropertyOlder(), MeshGenerator::getMesh(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshesByName(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MultiAppTransfer::getMultiApp(), InterfaceMaterial::getNeighborADMaterialProperty(), InterfaceMaterial::getNeighborMaterialProperty(), InterfaceMaterial::getNeighborMaterialPropertyOld(), InterfaceMaterial::getNeighborMaterialPropertyOlder(), Material::getOptionalADMaterialProperty(), Material::getOptionalMaterialProperty(), Material::getOptionalMaterialPropertyOld(), Material::getOptionalMaterialPropertyOlder(), FEProblemBase::getPositionsObject(), FEProblemBase::getPostprocessorValueByName(), AddReactions::getReactionKernelName(), ReporterData::getReporterInfo(), FEProblemBase::getSampler(), Transient::getTimeStepperName(), ProjectedStatefulMaterialStorageAction::getTypeEnum(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), Terminator::handleMessage(), FEProblemBase::hasFunction(), SubProblem::hasFunctor(), SubProblem::hasFunctorWithType(), AdvancedOutput::hasOutputHelper(), FEProblemBase::hasPostprocessor(), FEProblemBase::hasPostprocessorValueByName(), FEProblemBase::hasUserObject(), AdvancedOutput::init(), FEProblemBase::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), AttribName::initFrom(), NestedDivision::initialize(), SolutionScalarAux::initialSetup(), NodalVariableValue::initialSetup(), MultiAppProjectionTransfer::initialSetup(), SolutionUserObject::initialSetup(), AdvancedOutput::initOutputList(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MaterialBase::initStatefulProperties(), Function::integral(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), MeshGenerator::isChildMeshGenerator(), MeshGenerator::isNullMeshName(), MeshGenerator::isParentMeshGenerator(), LinearCombinationFunction::LinearCombinationFunction(), FEProblemBase::logAdd(), LymberopoulosElectronBC::LymberopoulosElectronBC(), Marker::Marker(), Material::Material(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), Distribution::median(), MemoryUsageReporter::MemoryUsageReporter(), MeshGenerator::meshPropertyPrefix(), MooseVariableInterface< T >::MooseVariableInterface(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), NeumannCircuitVoltageMoles_KV::NeumannCircuitVoltageMoles_KV(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), NodalValueSampler::NodalValueSampler(), MooseBaseParameterInterface::objectErrorPrefix(), MeshGenerator::Comparator::operator()(), DOFMapOutput::output(), ProgressOutput::output(), Output::Output(), AdvancedOutput::outputElementalVariables(), ConsoleUtils::outputExecutionInformation(), AdvancedOutput::outputInput(), AdvancedOutput::outputNodalVariables(), AdvancedOutput::outputPostprocessors(), Exodus::outputPostprocessors(), Nemesis::outputPostprocessors(), TableOutput::outputReporter(), AdvancedOutput::outputReporters(), AdvancedOutput::outputScalarVariables(), AdvancedOutput::outputSystemInformation(), AdvancedOutput::outputVectorPostprocessors(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedODEKernel::ParsedODEKernel(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PointVariableSamplerBase::PointVariableSamplerBase(), MultiApp::readCommandLineArguments(), Receiver::Receiver(), Executor::Result::record(), FEProblemBase::registerRandomInterface(), GlobalParamsAction::remove(), MaterialBase::resetQpProperties(), MultiApp::restore(), SakiyamaEnergySecondaryElectronBC::SakiyamaEnergySecondaryElectronBC(), SakiyamaSecondaryElectronBC::SakiyamaSecondaryElectronBC(), ScalarComponentIC::ScalarComponentIC(), SecondaryElectronBC::SecondaryElectronBC(), SecondaryElectronEnergyBC::SecondaryElectronEnergyBC(), MultiApp::setAppOutputFileBase(), MooseMesh::setBoundaryName(), Control::setControllableValue(), Control::setControllableValueByName(), GlobalParamsAction::setDoubleIndexParam(), OutputWarehouse::setFileNumbers(), GlobalParamsAction::setParam(), FEProblemBase::setPostprocessorValueByName(), GlobalParamsAction::setScalarParam(), MooseMesh::setSubdomainName(), GlobalParamsAction::setTripleIndexParam(), Split::setup(), TransientMultiApp::setupApp(), GlobalParamsAction::setVectorParam(), SideCurrent::SideCurrent(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SideValueSampler::SideValueSampler(), TransientMultiApp::solveStep(), UserObject::spatialValue(), StitchedMesh::StitchedMesh(), SubProblem::storeBoundaryDelayedCheckMatProp(), SubProblem::storeBoundaryMatPropName(), SubProblem::storeBoundaryZeroMatProp(), SubProblem::storeSubdomainDelayedCheckMatProp(), SubProblem::storeSubdomainMatPropName(), SubProblem::storeSubdomainZeroMatProp(), MaterialBase::subdomainSetup(), TaggingInterface::TaggingInterface(), VectorPostprocessorVisualizationAux::timestepSetup(), MultiAppDofCopyTransfer::transfer(), TransientMultiApp::TransientMultiApp(), MooseBase::typeAndName(), MooseBaseParameterInterface::uniqueParameterName(), UserObject::UserObject(), UserObjectInterface::userObjectName(), MultiAppTransfer::variableIntegrityCheck(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), AdvancedOutput::wantOutput(), Coupleable::writableCoupledValue(), and Coupleable::writableVariable().
objectErrorPrefix()
std::string MooseBaseParameterInterface::objectErrorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for an object.
Definition at line 58 of file MooseBaseParameterInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the class \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseParameterInterface::paramErrorMsg().
onBoundaries() [1/3]
bool MultiAppGeneralFieldTransfer::onBoundaries (const std::set< BoundaryID > & boundaries, const MooseMesh & mesh, const Elem * elem) const protected inherited
Definition at line 1573 of file MultiAppGeneralFieldTransfer.C.
{
  // Get all boundaries each side of the element is part of
  const BoundaryInfo & bnd_info = mesh.getMesh().get_boundary_info();
  std::vector<BoundaryID> vec_to_fill;
  std::vector<BoundaryID> vec_to_fill_temp;
  if (_elemental_boundary_restriction_on_sides)
    for (const auto side : make_range(elem->n_sides()))
    {
      bnd_info.boundary_ids(elem, side, vec_to_fill_temp);
      vec_to_fill.insert(vec_to_fill.end(), vec_to_fill_temp.begin(), vec_to_fill_temp.end());
    }
  else
    for (const auto node_index : make_range(elem->n_nodes()))
    {
      bnd_info.boundary_ids(elem->node_ptr(node_index), vec_to_fill_temp);
      vec_to_fill.insert(vec_to_fill.end(), vec_to_fill_temp.begin(), vec_to_fill_temp.end());
    }
  std::set<BoundaryID> vec_to_fill_set(vec_to_fill.begin(), vec_to_fill.end());
  // Look for a match between the boundaries from the restriction and those near the element
  std::set<BoundaryID> u;
  std::set_intersection(boundaries.begin(),
                        boundaries.end(),
                        vec_to_fill_set.begin(),
                        vec_to_fill_set.end(),
                        std::inserter(u, u.begin()));
  return !u.empty();
}
onBoundaries() [2/3]
bool MultiAppGeneralFieldTransfer::onBoundaries (const std::set< BoundaryID > & boundaries, const MooseMesh & mesh, const Node * node) const protected inherited
Definition at line 1555 of file MultiAppGeneralFieldTransfer.C.
{
  const BoundaryInfo & bnd_info = mesh.getMesh().get_boundary_info();
  std::vector<BoundaryID> vec_to_fill;
  bnd_info.boundary_ids(node, vec_to_fill);
  std::set<BoundaryID> vec_to_fill_set(vec_to_fill.begin(), vec_to_fill.end());
  std::set<BoundaryID> u;
  std::set_intersection(boundaries.begin(),
                        boundaries.end(),
                        vec_to_fill_set.begin(),
                        vec_to_fill_set.end(),
                        std::inserter(u, u.begin()));
  return !u.empty();
}
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), MultiAppGeneralFieldTransfer::getRestrictedFromBoundingBoxes(), and MultiAppGeneralFieldTransfer::onBoundaries().
onBoundaries() [3/3]
bool MultiAppGeneralFieldTransfer::onBoundaries (const std::set< BoundaryID > & boundaries, const std::set< SubdomainID > & block_restriction, const MooseMesh & mesh, const PointLocatorBase *const pl, const Point & pt) const protected inherited
Definition at line 1606 of file MultiAppGeneralFieldTransfer.C.
{
  // Find the element containing the point and use the block restriction if known for speed
  const Elem * elem;
  if (block_restriction.empty())
    elem = (*pl)(point);
  else
    elem = (*pl)(point, &block_restriction);
  if (!elem)
    return false;
  return onBoundaries(boundaries, mesh, elem);
}
outputValueConflicts()
void MultiAppGeneralFieldTransfer::outputValueConflicts (const unsigned int var_index, const DofobjectToInterpValVec & dofobject_to_valsvec, const InterpCaches & distance_caches) private inherited
Report on conflicts between overlapping child apps, equidistant origin points etc.
Definition at line 1203 of file MultiAppGeneralFieldTransfer.C.
{
  // Remove potential conflicts that did not materialize, the value did not end up being used
  examineReceivedValueConflicts(var_index, dofobject_to_valsvec, distance_caches);
  examineLocalValueConflicts(var_index, dofobject_to_valsvec, distance_caches);
  // Output the conflicts from the selection of local values (evaluateInterpValues-type routines)
  // to send in response to value requests at target points
  const std::string rank_str = std::to_string(_communicator.rank());
  if (_local_conflicts.size())
  {
    std::string local_conflicts_string = "";
    std::string potential_reasons =
        "Are some points in target mesh equidistant from the sources "
        "(nodes/centroids/apps/positions, depending on transfer) in origin mesh(es)?\n";
    for (const auto & conflict : _local_conflicts)
    {
      const unsigned int problem_id = std::get<0>(conflict);
      Point p = std::get<2>(conflict);
      std::string origin_domain_message;
      if (hasFromMultiApp() && !_nearest_positions_obj)
      {
        // NOTES:
        // - The origin app for a conflict may not be unique.
        // - The conflicts vectors only store the conflictual points, not the original one
        //   The original value found with a given distance could be retrieved from the main
        //   caches
        const auto app_id = _from_local2global_map[problem_id];
        origin_domain_message = "In source child app " + std::to_string(app_id) + " mesh,";
      }
      // We can't locate the source app when considering nearest positions, so we saved the data
      // in the reference space. So we return the conflict location in the target app (parent or
      // sibling) instead
      else if (hasFromMultiApp() && _nearest_positions_obj)
      {
        if (_to_problems.size() == 1 || _skip_coordinate_collapsing)
        {
          p = (*_to_transforms[0])(p);
          origin_domain_message = "In target app mesh,";
        }
        else
          origin_domain_message = "In reference (post-coordinate collapse) mesh,";
      }
      else
        origin_domain_message = "In source parent app mesh,";
      if (hasFromMultiApp() && _from_problems.size() > 1)
        mooseDoOnce(potential_reasons += "Are multiple subapps overlapping?\n";);
      local_conflicts_string += origin_domain_message + " point: (" + std::to_string(p(0)) + ", " +
                                std::to_string(p(1)) + ", " + std::to_string(p(2)) +
                                "), equi-distance: " + std::to_string(std::get<3>(conflict)) + "\n";
    }
    // Explicitly name source to give more context
    std::string source_str = "unknown";
    if (_from_var_names.size())
      source_str = "variable '" + getFromVarName(var_index) + "'";
    else if (isParamValid("source_user_object"))
      source_str = "user object '" + getParam<UserObjectName>("source_user_object") + "'";
    mooseWarning("On rank " + rank_str +
                 ", multiple valid values from equidistant points were "
                 "found in the origin mesh for source " +
                 source_str + " for " + std::to_string(_local_conflicts.size()) +
                 " target points.\n" + potential_reasons + "Conflicts detected at :\n" +
                 local_conflicts_string);
  }
  // Output the conflicts discovered when receiving values from multiple origin problems
  if (_received_conflicts.size())
  {
    std::string received_conflict_string = "";
    std::string potential_reasons =
        "Are some points in target mesh equidistant from the sources "
        "(nodes/centroids/apps/positions, depending on transfer) in origin mesh(es)?\n";
    for (const auto & conflict : _received_conflicts)
    {
      // Extract info for the potential overlap
      const unsigned int problem_id = std::get<0>(conflict);
      const Point p = std::get<2>(conflict);
      std::string target_domain_message;
      if (hasToMultiApp())
      {
        const auto app_id = _to_local2global_map[problem_id];
        target_domain_message = "In target child app " + std::to_string(app_id) + " mesh,";
      }
      else
        target_domain_message = "In target parent app mesh,";
      if (hasToMultiApp() && _to_problems.size() > 1)
        mooseDoOnce(potential_reasons += "Are multiple subapps overlapping?\n";);
      received_conflict_string += target_domain_message + " point: (" + std::to_string(p(0)) +
                                  ", " + std::to_string(p(1)) + ", " + std::to_string(p(2)) +
                                  "), equi-distance: " + std::to_string(std::get<3>(conflict)) +
                                  "\n";
    }
    mooseWarning("On rank " + rank_str +
                 ", multiple valid values from equidistant points were "
                 "received for target variable '" +
                 getToVarName(var_index) + "' for " + std::to_string(_received_conflicts.size()) +
                 " target points.\n" + potential_reasons + "Conflicts detected at :\n" +
                 received_conflict_string);
  }
  if (_local_conflicts.empty() && _received_conflicts.empty())
  {
    if (isParamSetByUser("search_value_conflict"))
      mooseInfo("Automated diagnosis did not detect floating point indetermination in transfer");
    else if (_to_problems.size() > 10 || _from_problems.size() > 10)
      mooseInfo("Automated diagnosis did not detect any floating point indetermination in "
                "transfer. You may consider turning it off using `search_value_conflicts=false` "
                "to improve performance/scalability.");
  }
  // Reset the conflicts vectors, to be used for checking conflicts when transferring the next
  // variable
  _local_conflicts.clear();
  _received_conflicts.clear();
}
Referenced by MultiAppGeneralFieldTransfer::transferVariable().
paramError()
template<typename... Args> void MooseBaseParameterInterface::paramError (const std::string & param, Args... args) const inherited
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseError - only printing a message using the given args.
Definition at line 233 of file MooseBaseParameterInterface.h.
{
  Moose::show_trace = false;
  std::string msg = paramErrorMsg(param, std::forward<Args>(args)...);
  callMooseErrorRaw(msg, &_moose_base->getMooseApp());
  Moose::show_trace = true;
}
Referenced by HierarchicalGridPartitioner::_do_partition(), SetupDebugAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), ADDGKernel::ADDGKernel(), ReporterPointSource::addPoints(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ADNodalKernel::ADNodalKernel(), ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), AdvectiveFluxAux::AdvectiveFluxAux(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), ArrayBodyForce::ArrayBodyForce(), ArrayDGKernel::ArrayDGKernel(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayDirichletBC::ArrayDirichletBC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), ArrayPenaltyDirichletBC::ArrayPenaltyDirichletBC(), ArrayVacuumBC::ArrayVacuumBC(), BlockDeletionGenerator::BlockDeletionGenerator(), BlockWeightedPartitioner::BlockWeightedPartitioner(), BoundsAuxBase::BoundsAuxBase(), BreakMeshByBlockGenerator::BreakMeshByBlockGenerator(), BuildArrayVariableAux::BuildArrayVariableAux(), PiecewiseTabularBase::buildFromFile(), CartesianGridDivision::CartesianGridDivision(), UserObjectInterface::castUserObject(), checkComponent(), MeshGenerator::checkGetMesh(), PostprocessorInterface::checkParam(), Coupleable::checkVar(), MultiAppTransfer::checkVariable(), CircularBoundaryCorrectionGenerator::CircularBoundaryCorrectionGenerator(), CircularBoundaryCorrectionGenerator::circularCenterCalculator(), MultiAppGeneralFieldTransfer::closestToPosition(), CombinerGenerator::CombinerGenerator(), CompositionDT::CompositionDT(), ConcentricCircleMeshGenerator::ConcentricCircleMeshGenerator(), LibtorchNeuralNetControl::conditionalParameterError(), ConstantVectorPostprocessor::ConstantVectorPostprocessor(), ContainsPointAux::ContainsPointAux(), CopyValueAux::CopyValueAux(), Coupleable::Coupleable(), CoupledForceTempl< is_ad >::CoupledForceTempl(), CoupledValueFunctionMaterialTempl< is_ad >::CoupledValueFunctionMaterialTempl(), MultiApp::createApp(), MeshGeneratorSystem::createMeshGenerator(), CylindricalGridDivision::CylindricalGridDivision(), ConstantReporter::declareConstantReporterValues(), AccumulateReporter::declareLateValues(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DGLowerDKernel::DGLowerDKernel(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementLengthAux::ElementLengthAux(), ElementLpNormAux::ElementLpNormAux(), ElementValueSampler::ElementValueSampler(), ReporterPointSource::errorCheck(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), ExtraElementIDAux::ExtraElementIDAux(), ExtraElementIntegerDivision::ExtraElementIntegerDivision(), FEProblemSolve::FEProblemSolve(), FillBetweenCurvesGenerator::FillBetweenCurvesGenerator(), FillBetweenSidesetsGenerator::FillBetweenSidesetsGenerator(), ReporterPointSource::fillPoint(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), InternalSideIndicator::finalize(), FixedPointSolve::FixedPointSolve(), ForcingFunctionAux::ForcingFunctionAux(), FunctionArrayAux::FunctionArrayAux(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorAux::FunctorAux(), FunctorBinnedValuesDivision::FunctorBinnedValuesDivision(), FunctorElementalGradientAuxTempl< is_ad >::FunctorElementalGradientAuxTempl(), FunctorPositions::FunctorPositions(), FunctorVectorElementalAuxTempl< is_ad >::FunctorVectorElementalAuxTempl(), FVFluxBC::FVFluxBC(), FVInterfaceKernel::FVInterfaceKernel(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), FVTwoVarContinuityConstraint::FVTwoVarContinuityConstraint(), AdvancedExtruderGenerator::generate(), BlockDeletionGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundaryDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), BreakMeshByBlockGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), CombinerGenerator::generate(), ExplodeMeshGenerator::generate(), ExtraNodesetGenerator::generate(), FillBetweenCurvesGenerator::generate(), FillBetweenSidesetsGenerator::generate(), GeneratedMeshGenerator::generate(), MeshCollectionGenerator::generate(), MeshExtruderGenerator::generate(), ParsedCurveGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), PropertyReadFile::getBlockData(), PropertyReadFile::getData(), Sampler::getGlobalSamples(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), Sampler::getLocalSamples(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), Sampler::getNextLocalRow(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectName(), HFEMDirichletBC::HFEMDirichletBC(), MultiApp::init(), BlockWeightedPartitioner::initialize(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), PiecewiseConstantFromCSV::initialSetup(), LibtorchControlValuePostprocessor::initialSetup(), ReferenceResidualProblem::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), HistogramVectorPostprocessor::initialSetup(), AddMetaDataGenerator::inputChecker(), IntegratedBC::IntegratedBC(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceValueUserObjectAux::InterfaceValueUserObjectAux(), InterpolatedStatefulMaterialTempl< T >::InterpolatedStatefulMaterialTempl(), InversePowerMethod::InversePowerMethod(), IterationAdaptiveDT::IterationAdaptiveDT(), MultiApp::keepSolutionDuringRestore(), Kernel::Kernel(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LinearCombinationFunction::LinearCombinationFunction(), LowerDIntegratedBC::LowerDIntegratedBC(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), MaterialADConverterTempl< T >::MaterialADConverterTempl(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), PatternedMeshGenerator::mergeSubdomainNameMaps(), MeshCollectionGenerator::MeshCollectionGenerator(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshDivisionAux::MeshDivisionAux(), MeshGenerator::MeshGenerator(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarNodalAuxKernelTempl< ComputeValueType >::MortarNodalAuxKernelTempl(), MultiApp::moveApp(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), NestedDivision::NestedDivision(), NodalBC::NodalBC(), NodalEqualValueConstraint::NodalEqualValueConstraint(), NodalKernel::NodalKernel(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), NodalValueSampler::NodalValueSampler(), Output::Output(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), PatchMeshGenerator::PatchMeshGenerator(), PatternedMeshGenerator::PatternedMeshGenerator(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), PeriodicSegmentalConstraint::PeriodicSegmentalConstraint(), PIDTransientControl::PIDTransientControl(), PlaneDeletionGenerator::PlaneDeletionGenerator(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), PolyLineMeshGenerator::PolyLineMeshGenerator(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), LibmeshPartitioner::prepareBlocksForSubdomainPartitioner(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), PropertyReadFile::PropertyReadFile(), RandomIC::RandomIC(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readXda(), ReferenceResidualProblem::ReferenceResidualProblem(), RefineBlockGenerator::RefineBlockGenerator(), RefineSidesetGenerator::RefineSidesetGenerator(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setPartitioner(), TimeSequenceStepperBase::setupSequence(), SingleRankPartitioner::SingleRankPartitioner(), SphericalGridDivision::SphericalGridDivision(), SymmetryTransformGenerator::SymmetryTransformGenerator(), Terminator::Terminator(), TimeDerivativeAux::TimeDerivativeAux(), Transfer::Transfer(), TransformGenerator::TransformGenerator(), TransientMultiApp::TransientMultiApp(), ParsedCurveGenerator::tSectionSpaceDefiner(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), UserObject::UserObject(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), VolumeAux::VolumeAux(), XYDelaunayGenerator::XYDelaunayGenerator(), and XYMeshLineCutter::XYMeshLineCutter().
paramErrorMsg()
template<typename... Args> std::string MooseBaseParameterInterface::paramErrorMsg (const std::string & param, Args... args) const inline private inherited
Definition at line 171 of file MooseBaseParameterInterface.h.
  {
    auto param_prefix = paramErrorPrefix(_pars, param);
    // With no input location information, append object info (name + type)
    const std::string object_prefix =
        _pars.inputLocation(param).empty() ? objectErrorPrefix("parameter error") : "";
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    // Wrap error message to a separate line from param_prefix if it is about to
    // blow past 100 chars.  But only wrap if the param_prefix is long enough (12
    // chars) for the wrap to buy us much extra length. We don't check object_prefix
    // here because it will go before the parameter error
    if ((param_prefix.size() > 12 && msg.size() + param_prefix.size() > 99) ||
        msg.find("\n") != std::string::npos)
    {
      if (param_prefix.size() > 0 && param_prefix[param_prefix.size() - 1] != ':')
        param_prefix += ":";
      return object_prefix + param_prefix + "\n    " + MooseUtils::replaceAll(msg, "\n", "\n    ");
    }
    return object_prefix + param_prefix + " " + msg;
  }
Referenced by MooseBaseParameterInterface::paramError(), MooseBaseParameterInterface::paramInfo(), and MooseBaseParameterInterface::paramWarning().
parameters()
const InputParameters & MooseBaseParameterInterface::parameters () const inline inherited
Get the parameters of the object.
Returns
The parameters of the object
Definition at line 53 of file MooseBaseParameterInterface.h.
{ return _pars; }
Referenced by SetupDebugAction::act(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), FEProblemBase::addPostprocessor(), FEProblemBase::addPredictor(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), AdvancedOutput::AdvancedOutput(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), Moose::assemble_matrix(), AuxScalarKernel::AuxScalarKernel(), BoundsAuxBase::BoundsAuxBase(), MooseMesh::buildTypedMesh(), UserObjectInterface::castUserObject(), PostprocessorInterface::checkParam(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), Moose::compute_bounds(), Moose::compute_jacobian(), Moose::compute_nearnullspace(), Moose::compute_nullspace(), Moose::compute_postcheck(), Moose::compute_transpose_nullspace(), LibtorchNeuralNetControl::conditionalParameterError(), Console::Console(), MultiApp::createApp(), Postprocessor::declareValue(), DumpObjectsProblem::deduceNecessaryParameters(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), DumpObjectsProblem::dumpObjectHelper(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElectronsFromIonization::ElectronsFromIonization(), Executor::Executor(), Exodus::Exodus(), FEProblem::FEProblem(), FEProblemBase::FEProblemBase(), FixedPointSolve::FixedPointSolve(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GapValueAux::GapValueAux(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), MooseBaseParameterInterface::getCheckedPointerParam(), ExecutorInterface::getExecutor(), Material::getMaterial(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), UserObjectInterface::getUserObjectName(), VectorPostprocessorInterface::getVectorPostprocessorName(), GhostingUserObject::GhostingUserObject(), HphiRadialInterface::HphiRadialInterface(), AttribSystem::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), FullSolveMultiApp::initialSetup(), FEProblemBase::initNullSpaceVectors(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), isValid(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseAppCoordTransform::MooseAppCoordTransform(), MooseVariableInterface< T >::MooseVariableInterface(), MultiApp::MultiApp(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodeFaceConstraint::NodeFaceConstraint(), PatchMeshGenerator::PatchMeshGenerator(), PenetrationAux::PenetrationAux(), PicardSolve::PicardSolve(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), ProjectedStatefulMaterialStorageAction::processProperty(), MultiAppProjectionTransfer::projectSolution(), PropertyReadFile::PropertyReadFile(), PseudoTimestep::PseudoTimestep(), RandomIC::RandomIC(), InputParameterWarehouse::removeInputParameters(), OutputWarehouse::resetFileBase(), MooseAppCoordTransform::setCoordinateSystem(), FEProblemBase::setInputParametersFEProblem(), FEProblem::setInputParametersFEProblem(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SteffensenSolve::SteffensenSolve(), DumpObjectsProblem::stringifyParameters(), TaggingInterface::TaggingInterface(), Transfer::Transfer(), Transient::Transient(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
paramInfo()
template<typename... Args> void MooseBaseParameterInterface::paramInfo (const std::string & param, Args... args) const inherited
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseInfo - only printing a message using the given args.
Definition at line 250 of file MooseBaseParameterInterface.h.
{
  mooseInfo(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by TransientMultiApp::TransientMultiApp().
paramWarning()
template<typename... Args> void MooseBaseParameterInterface::paramWarning (const std::string & param, Args... args) const inherited
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseWarning - only printing a message using the given args.
Definition at line 243 of file MooseBaseParameterInterface.h.
{
  mooseWarning(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by MultiAppNearestNodeTransfer::execute(), FEProblemSolve::FEProblemSolve(), PlaneIDMeshGenerator::generate(), UniqueExtraIDMeshGenerator::generate(), Terminator::initialSetup(), and MooseMesh::MooseMesh().
perfGraph()
PerfGraph & PerfGraphInterface::perfGraph () inherited
Get the PerfGraph.
Definition at line 78 of file PerfGraphInterface.C.
{
  return _pg_moose_app.perfGraph();
}
Referenced by CommonOutputAction::act(), PerfGraphData::finalize(), and PerfGraphOutput::output().
performAdjustment()
bool MultiAppConservativeTransfer::performAdjustment (const PostprocessorValue & from, const PostprocessorValue & to) const protected inherited
Definition at line 526 of file MultiAppConservativeTransfer.C.
{
  if (from * to > 0)
    return true;
  else if (_allow_skipped_adjustment)
    return false;
  else
    mooseError("Adjustment postprocessors from: ",
               from,
               " to: ",
               to,
               " must both have the same sign and be different from 0");
}
Referenced by MultiAppConservativeTransfer::adjustTransferredSolution(), and MultiAppConservativeTransfer::adjustTransferredSolutionNearestPoint().
possibleDirections()
static std::string Transfer::possibleDirections () inline static inherited
Used to construct InputParameters.
Definition at line 76 of file Transfer.h.
{ return "to_multiapp from_multiapp between_multiapp"; }
Referenced by Transfer::validParams().
postExecute()
void MultiAppConservativeTransfer::postExecute () virtual inherited
Add some extra work if necessary after execute().
For example, adjust the solution to preserve some physics quality of interest.
Definition at line 215 of file MultiAppConservativeTransfer.C.
{
  if (_preserve_transfer)
  {
    TIME_SECTION("MultiAppConservativeTransfer::execute()",
                 5,
                 "Post transfer to preserve postprocessor values");
    if (_current_direction == TO_MULTIAPP)
    {
      FEProblemBase & from_problem = getToMultiApp()->problemBase();
      if (_use_nearestpoint_pps)
        from_problem.computeUserObjectByName(
            EXEC_TRANSFER, Moose::POST_AUX, _from_postprocessors_to_be_preserved[0]);
      for (unsigned int i = 0; i < getToMultiApp()->numGlobalApps(); i++)
        if (getToMultiApp()->hasLocalApp(i))
        {
          if (_use_nearestpoint_pps)
            adjustTransferredSolutionNearestPoint(i,
                                                  &from_problem,
                                                  _from_postprocessors_to_be_preserved[0],
                                                  getToMultiApp()->appProblemBase(i),
                                                  _to_postprocessors_to_be_preserved[0]);
          else
            adjustTransferredSolution(&from_problem,
                                      _from_postprocessors_to_be_preserved[i],
                                      getToMultiApp()->appProblemBase(i),
                                      _to_postprocessors_to_be_preserved[0]);
        }
    }
    else if (_current_direction == FROM_MULTIAPP)
    {
      FEProblemBase & to_problem = getFromMultiApp()->problemBase();
      if (_use_nearestpoint_pps)
        to_problem.computeUserObjectByName(
            EXEC_TRANSFER, Moose::POST_AUX, _to_postprocessors_to_be_preserved[0]);
      for (unsigned int i = 0; i < getFromMultiApp()->numGlobalApps(); i++)
      {
        if (_use_nearestpoint_pps)
          adjustTransferredSolutionNearestPoint(
              i,
              getFromMultiApp()->hasLocalApp(i) ? &getFromMultiApp()->appProblemBase(i) : nullptr,
              _from_postprocessors_to_be_preserved[0],
              to_problem,
              _to_postprocessors_to_be_preserved[0]);
        else
          adjustTransferredSolution(
              getFromMultiApp()->hasLocalApp(i) ? &getFromMultiApp()->appProblemBase(i) : nullptr,
              _from_postprocessors_to_be_preserved[0],
              to_problem,
              _to_postprocessors_to_be_preserved[i]);
      }
      // Compute the to-postprocessor again so that it has the right value with the updated solution
      if (_use_nearestpoint_pps)
        to_problem.computeUserObjectByName(
            EXEC_TRANSFER, Moose::POST_AUX, _to_postprocessors_to_be_preserved[0]);
    }
  }
}
Referenced by MultiAppGeneralFieldTransfer::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppShapeEvaluationTransfer::execute(), and MultiAppUserObjectTransfer::execute().
prepareEvaluationOfInterpValues()
void MultiAppGeneralFieldShapeEvaluationTransfer::prepareEvaluationOfInterpValues (const unsigned int var_index) override protected virtual
Implements MultiAppGeneralFieldTransfer.
Definition at line 60 of file MultiAppGeneralFieldShapeEvaluationTransfer.C.
{
  _local_bboxes.clear();
  if (_use_bounding_boxes)
    extractLocalFromBoundingBoxes(_local_bboxes);
  _local_meshfuns.clear();
  buildMeshFunctions(var_index, _local_meshfuns);
}
prepareToTransfer()
void MultiAppGeneralFieldTransfer::prepareToTransfer () private inherited
Initialize supporting attributes like bounding boxes, processor app indexes etc.
Definition at line 446 of file MultiAppGeneralFieldTransfer.C.
{
  // Get the bounding boxes for the "from" domains.
  // Clean up _from_bboxes from the previous transfer execution
  _from_bboxes.clear();
  // NOTE: This ignores the app's bounding box inflation and padding
  _from_bboxes = getRestrictedFromBoundingBoxes();
  // Expand bounding boxes. Some desired points might be excluded
  // without an expansion
  extendBoundingBoxes(_bbox_factor, _from_bboxes);
  // Figure out how many "from" domains each processor owns.
  _froms_per_proc.clear();
  _froms_per_proc = getFromsPerProc();
  // Get the index for the first source app every processor owns
  _global_app_start_per_proc = getGlobalStartAppPerProc();
}
Referenced by MultiAppGeneralFieldTransfer::execute().
registerConflict()
void MultiAppGeneralFieldTransfer::registerConflict (unsigned int problem, dof_id_type dof_id, Point p, Real dist, bool local) protected inherited
Register a potential value conflict, e.g.
two or more equidistant source points for a single target point, with different values possible
Parameters
problem problem ID for the point of interest. For local conflicts, use origin problem id, for received conflicts, use target id
dof_id id id of the DoF is transferring a DoF. If not, use -1
p point where the conflict happens
dist distance between the origin and the target
local if true, local conflict found when gathering data to send, if false, received value conflict found when receiving data from multiple source problems
Definition at line 967 of file MultiAppGeneralFieldTransfer.C.
{
  // NOTE We could be registering the same conflict several times, we could count them instead
  if (local)
    _local_conflicts.push_back(std::make_tuple(problem, dof_id, p, dist));
  else
    _received_conflicts.push_back(std::make_tuple(problem, dof_id, p, dist));
}
Referenced by MultiAppGeneralFieldTransfer::cacheIncomingInterpVals(), MultiAppGeneralFieldNearestLocationTransfer::evaluateInterpValuesNearestNode(), evaluateInterpValuesWithMeshFunctions(), and MultiAppGeneralFieldUserObjectTransfer::evaluateInterpValuesWithUserObjects().
registerRestartableDataOnApp()
RestartableDataValue & Restartable::registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const private inherited
Helper function for actually registering the restartable data.
Definition at line 51 of file Restartable.C.
{
  return _restartable_app.registerRestartableData(
      std::move(data), tid, _restartable_read_only, _metaname);
}
Referenced by Restartable::declareRestartableDataHelper().
registerRestartableNameWithFilterOnApp()
void Restartable::registerRestartableNameWithFilterOnApp (const std::string & name, Moose::RESTARTABLE_FILTER filter) private inherited
Helper function for actually registering the restartable data.
Definition at line 59 of file Restartable.C.
{
  _restartable_app.registerRestartableNameWithFilter(name, filter);
}
Referenced by Restartable::declareRecoverableData().
registerTimedSection() [1/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
Returns
The ID of the section - use when starting timing
Definition at line 53 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(timed_section_name, level);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
registerTimedSection() [2/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level, const std::string & live_message, const bool print_dots = true) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
live_message The message to be printed to the screen during execution
print_dots Whether or not progress dots should be printed for this section
Returns
The ID of the section - use when starting timing
Definition at line 64 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(
        timedSectionName(section_name), level, live_message, print_dots);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
residualSetup()
void SetupInterface::residualSetup () virtual inherited
Gets called just before the residual is computed and before this object is asked to do its job.
Reimplemented in NodeFaceConstraint, Function, Positions, Times, MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, MooseVariableFE< ComputeValueType >, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, and MooseVariableFV< T >.
Definition at line 55 of file SetupInterface.C.
{
}
Referenced by MooseVariableField< OutputType >::residualSetup(), ComputeFVFluxResidualThread< RangeType >::setup(), and ComputeFVFluxRJThread< RangeType >::setup().
restartableName()
std::string Restartable::restartableName (const std::string & data_name) const protected inherited
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
This should only be used in this interface and in testing.
Definition at line 66 of file Restartable.C.
{
  return _restartable_system_name + "/" + _restartable_name + "/" + data_name;
}
Referenced by Restartable::declareRecoverableData(), and Restartable::declareRestartableDataHelper().
setCurrentDirection()
void Transfer::setCurrentDirection (const int direction) inline inherited
Set this Transfer to be executed in a given direction.
Definition at line 89 of file Transfer.h.
  {
    _current_direction = direction;
    _direction = direction;
  }
Referenced by FEProblemBase::execMultiAppTransfers().
setSolutionVectorValues()
void MultiAppGeneralFieldTransfer::setSolutionVectorValues (const unsigned int var_index, const DofobjectToInterpValVec & dofobject_to_valsvec, const InterpCaches & interp_caches) private inherited
Definition at line 1329 of file MultiAppGeneralFieldTransfer.C.
{
  // Get the variable name, with the accommodation for array/vector names
  const auto & var_name = getToVarName(var_index);
  for (const auto problem_id : index_range(_to_problems))
  {
    auto & dofobject_to_val = dofobject_to_valsvec[problem_id];
    // libMesh EquationSystems
    // NOTE: we would expect to set variables from the displaced equation system here
    auto & es = getEquationSystem(*_to_problems[problem_id], false);
    // libMesh system
    System * to_sys = find_sys(es, var_name);
    // libMesh mesh
    const MeshBase & to_mesh = _to_problems[problem_id]->mesh(_displaced_target_mesh).getMesh();
    auto var_num = to_sys->variable_number(var_name);
    auto sys_num = to_sys->number();
    auto & fe_type = _to_variables[var_index]->feType();
    bool is_nodal = _to_variables[var_index]->isNodal();
    if (fe_type.order > CONSTANT && !is_nodal)
    {
      // We may need to use existing data values in places where the
      // from app domain doesn't overlap
      MeshFunction to_func(es, *to_sys->current_local_solution, to_sys->get_dof_map(), var_num);
      to_func.init();
      GeneralFieldTransfer::CachedData<Number> f(
          interp_caches[problem_id], to_func, _default_extrapolation_value);
      libMesh::VectorSetAction<Number> setter(*to_sys->solution);
      const std::vector<unsigned int> varvec(1, var_num);
      libMesh::GenericProjector<GeneralFieldTransfer::CachedData<Number>,
                                GeneralFieldTransfer::CachedData<Gradient>,
                                Number,
                                libMesh::VectorSetAction<Number>>
          set_solution(*to_sys, f, nullptr, setter, varvec);
      // We dont look at boundary restriction, not supported for higher order target variables
      const auto & to_begin = _to_blocks.empty()
                                  ? to_mesh.active_local_elements_begin()
                                  : to_mesh.active_local_subdomain_set_elements_begin(_to_blocks);
      const auto & to_end = _to_blocks.empty()
                                ? to_mesh.active_local_elements_end()
                                : to_mesh.active_local_subdomain_set_elements_end(_to_blocks);
      ConstElemRange active_local_elem_range(to_begin, to_end);
      set_solution.project(active_local_elem_range);
    }
    else
    {
      for (const auto & val_pair : dofobject_to_val)
      {
        const auto dof_object_id = val_pair.first;
        const DofObject * dof_object = nullptr;
        if (is_nodal)
          dof_object = to_mesh.node_ptr(dof_object_id);
        else
          dof_object = to_mesh.elem_ptr(dof_object_id);
        const auto dof = dof_object->dof_number(sys_num, var_num, 0);
        const auto val = val_pair.second.interp;
        // This will happen if meshes are mismatched
        if (_error_on_miss && GeneralFieldTransfer::isBetterOutOfMeshValue(val))
        {
          const auto target_location =
              hasToMultiApp()
                  ? " on target app " + std::to_string(getGlobalTargetAppIndex(problem_id))
                  : " on parent app ";
          if (is_nodal)
            mooseError("No source value could be found for node ",
                       dof_object_id,
                       target_location,
                       "could not be located. Node details:\n",
                       _to_meshes[problem_id]->nodePtr(dof_object_id)->get_info());
          else
            mooseError("No source value could be found for element ",
                       dof_object_id,
                       target_location,
                       "could not be located. Element details:\n",
                       _to_meshes[problem_id]->elemPtr(dof_object_id)->get_info());
        }
        // We should not put garbage into our solution vector
        // but it can be that we want to set it to a different value than what was already there
        // for example: the source app has been displaced and was sending an indicator of its
        // position
        if (GeneralFieldTransfer::isBetterOutOfMeshValue(val))
        {
          if (!GeneralFieldTransfer::isBetterOutOfMeshValue(_default_extrapolation_value))
            to_sys->solution->set(dof, _default_extrapolation_value);
          continue;
        }
        to_sys->solution->set(dof, val);
      }
    }
    to_sys->solution->close();
    // Sync local solutions
    to_sys->update();
  }
}
Referenced by MultiAppGeneralFieldTransfer::transferVariable().
subdomainSetup()
void SetupInterface::subdomainSetup () virtual inherited
Gets called when the subdomain changes (i.e.
in a Jacobian or residual loop) and before this object is asked to do its job
Reimplemented in Material, MaterialBase, GeneralUserObject, NodalUserObject, ThreadedGeneralUserObject, and Constraint.
Definition at line 60 of file SetupInterface.C.
{
}
timedSectionName()
std::string PerfGraphInterface::timedSectionName (const std::string & section_name) const protected inherited
Returns
The name of the timed section with the name section_name.
Optionally adds a prefix if one is defined.
Definition at line 47 of file PerfGraphInterface.C.
{
  return _prefix.empty() ? "" : (_prefix + "::") + section_name;
}
Referenced by PerfGraphInterface::registerTimedSection().
timestepSetup()
void SetupInterface::timestepSetup () virtual inherited
Gets called at the beginning of the timestep before this object is asked to do its job.
Reimplemented in VectorPostprocessorVisualizationAux, EqualValueEmbeddedConstraint, Function, Console, JSONOutput, Positions, MemoryUsage, NumNonlinearIterations, Times, SolutionUserObject, MooseVariableField< OutputType >, MooseVariableField< Real >, MooseVariableField< T >, MooseVariableField< RealVectorValue >, MooseVariableField< RealEigenVector >, MooseVariableField< ComputeValueType >, MooseVariableFV< OutputType >, MooseVariableFV< Real >, MooseVariableFV< RealVectorValue >, MooseVariableFV< RealEigenVector >, MooseVariableFV< ComputeValueType >, MooseVariableFV< T >, and VectorMemoryUsage.
Definition at line 45 of file SetupInterface.C.
{
}
Referenced by JSONOutput::timestepSetup(), and MooseVariableField< OutputType >::timestepSetup().
transferVariable()
void MultiAppGeneralFieldTransfer::transferVariable (unsigned int i) private inherited
Performs the transfer for the variable of index i.
Definition at line 468 of file MultiAppGeneralFieldTransfer.C.
{
  mooseAssert(i < _var_size, "The variable of index " << i << " does not exist");
  // Find outgoing target points
  // We need to know what points we need to send which processors
  // One processor will receive many points from many processors
  // One point may go to different processors
  ProcessorToPointVec outgoing_points;
  extractOutgoingPoints(i, outgoing_points);
  if (_from_var_names.size())
    prepareEvaluationOfInterpValues(i);
  else
    prepareEvaluationOfInterpValues(-1);
  // Fill values and app ids for incoming points
  // We are responsible to compute values for these incoming points
  auto gather_functor =
      [this](processor_id_type /*pid*/,
             const std::vector<std::pair<Point, unsigned int>> & incoming_locations,
             std::vector<std::pair<Real, Real>> & outgoing_vals)
  {
    outgoing_vals.resize(
        incoming_locations.size(),
        {GeneralFieldTransfer::BetterOutOfMeshValue, GeneralFieldTransfer::BetterOutOfMeshValue});
    // Evaluate interpolation values for these incoming points
    evaluateInterpValues(incoming_locations, outgoing_vals);
  };
  DofobjectToInterpValVec dofobject_to_valsvec(_to_problems.size());
  InterpCaches interp_caches(_to_problems.size(), getMaxToProblemsBBoxDimensions());
  InterpCaches distance_caches(_to_problems.size(), getMaxToProblemsBBoxDimensions());
  // Copy data out to incoming_vals_ids
  auto action_functor = [this, &i, &dofobject_to_valsvec, &interp_caches, &distance_caches](
                            processor_id_type pid,
                            const std::vector<std::pair<Point, unsigned int>> & my_outgoing_points,
                            const std::vector<std::pair<Real, Real>> & incoming_vals)
  {
    auto & pointInfoVec = _processor_to_pointInfoVec[pid];
    // Cache interpolation values for each dof object / points
    cacheIncomingInterpVals(pid,
                            i,
                            pointInfoVec,
                            my_outgoing_points,
                            incoming_vals,
                            dofobject_to_valsvec,
                            interp_caches,
                            distance_caches);
  };
  // We assume incoming_vals_ids is ordered in the same way as outgoing_points
  // Hopefully, pull_parallel_vector_data will not mess up this
  const std::pair<Real, Real> * ex = nullptr;
  libMesh::Parallel::pull_parallel_vector_data(
      comm(), outgoing_points, gather_functor, action_functor, ex);
  // Check for conflicts and overlaps from the maps that were built during the transfer
  if (_search_value_conflicts)
    outputValueConflicts(i, dofobject_to_valsvec, distance_caches);
  // Set cached values into solution vector
  setSolutionVectorValues(i, dofobject_to_valsvec, interp_caches);
}
Referenced by MultiAppGeneralFieldTransfer::execute().
transformBoundingBox()
void MultiAppTransfer::transformBoundingBox (BoundingBox & box, const MultiAppCoordTransform & transform) static protected inherited
Transform a bounding box according to the transformations in the provided coordinate transformation object.
Definition at line 446 of file MultiAppTransfer.C.
{
  MultiApp::transformBoundingBox(box, transform);
}
Referenced by MultiAppTransfer::getFromBoundingBoxes(), and MultiAppGeneralFieldTransfer::getRestrictedFromBoundingBoxes().
type()
const std::string & MooseBase::type () const inline inherited
Get the type of this class.
Returns
the name of the type of this class
Definition at line 41 of file MooseBase.h.
{ return _type; }
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), CreateProblemDefaultAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetupDebugAction::act(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::addDistribution(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addObject(), DistributedRectilinearMeshGenerator::addPoint(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), PhysicsBasedPreconditioner::addSystem(), FEProblemBase::addTimeIntegrator(), SubProblem::addVectorTag(), DisplacedProblem::addVectorTag(), FEProblemBase::advanceMultiApps(), FEProblemBase::backupMultiApps(), BoundaryPreservedMarker::BoundaryPreservedMarker(), DistributedRectilinearMeshGenerator::buildCube(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildPRefinementAndCoarseningMaps(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), FEProblemBase::computeAuxiliaryKernels(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpJacobian(), HFEMDirichletBC::computeLowerDQpJacobian(), ArrayHFEMDiffusion::computeLowerDQpJacobian(), HFEMDiffusion::computeLowerDQpJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), FEProblemBase::computeMultiAppsDT(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), DGCoupledAdvection::computeOffDiagJacobianHelper(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ScalarKernel::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueBoundaryConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), LinearNodalConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), DGConvection::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), InterfaceDiffusion::computeQpJacobian(), InterfaceReaction::computeQpJacobian(), DGCoupledAdvection::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), DGFunctionTemperatureAdvection::computeQpJacobian(), DGTemperatureAdvection::computeQpJacobian(), InterTemperatureAdvection::computeQpJacobian(), CoupledTiedValueConstraint::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), HFEMTestJump::computeQpOffDiagJacobian(), HFEMTrialJump::computeQpOffDiagJacobian(), DGCoupledAdvection::computeQpOffDiagJacobian(), ScalarKernel::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), EqualValueBoundaryConstraint::computeQpResidual(), EqualValueEmbeddedConstraint::computeQpResidual(), LinearNodalConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), DGConvection::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), DGEFieldAdvection::computeQpResidual(), HphiRadialInterface::computeQpResidual(), InterfaceAdvection::computeQpResidual(), InterfaceLogDiffusionElectrons::computeQpResidual(), PotentialSurfaceCharge::computeQpResidual(), ADDGAdvection::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), HFEMDiffusion::computeQpResidual(), HFEMTestJump::computeQpResidual(), HFEMTrialJump::computeQpResidual(), InterfaceDiffusion::computeQpResidual(), InterfaceReaction::computeQpResidual(), DGCoupledAdvection::computeQpResidual(), DGFunctionConvection::computeQpResidual(), DGFunctionTemperatureAdvection::computeQpResidual(), DGTemperatureAdvection::computeQpResidual(), InterTemperatureAdvection::computeQpResidual(), ArrayDGDiffusion::computeQpResidual(), ArrayHFEMDiffusion::computeQpResidual(), FEProblemBase::computeUserObjectByName(), FEProblemBase::computeUserObjects(), FEProblemBase::computeUserObjectsInternal(), BatchMaterial< Tuple, Output, Input >::construct(), DisplacedProblem::createQRules(), FEProblemBase::createQRules(), MeshGenerator::declareMeshProperty(), DumpObjectsProblem::deduceNecessaryParameters(), DumpObjectsProblem::dumpObjectHelper(), FEProblemBase::duplicateVariableCheck(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), MooseBaseErrorInterface::errorPrefix(), AB2PredictorCorrector::estimateTimeError(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finishMultiAppStep(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), ElementSubdomainIDGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), PatternedMeshGenerator::generate(), MeshGenerator::generateInternal(), MultiAppTransfer::getAppInfo(), TransfiniteMeshGenerator::getEdge(), ElementGenerator::getElemType(), FEProblemBase::getMaterial(), FEProblemBase::getMaterialData(), MaterialOutputAction::getParams(), ReporterData::getReporterInfo(), Transient::getTimeIntegratorName(), FEProblemBase::getTransfers(), SubProblem::getVectorTags(), DisplacedProblem::getVectorTags(), CommonOutputAction::hasConsole(), FEProblemBase::hasMultiApps(), AdvancedOutput::hasOutput(), FEProblemBase::incrementMultiAppTStep(), AdvancedOutput::initAvailableLists(), FunctorPositions::initialize(), FunctorTimes::initialize(), MultiAppConservativeTransfer::initialSetup(), ArrayDGDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), RelationshipManager::isType(), FEProblemBase::logAdd(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), SubProblem::numVectorTags(), DisplacedProblem::numVectorTags(), MooseBaseParameterInterface::objectErrorPrefix(), AdvancedOutput::output(), Console::output(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), ProjectedStatefulMaterialStorageAction::processProperty(), SolutionInvalidInterface::registerInvalidSolutionInternal(), FEProblemBase::restoreMultiApps(), MeshRepairGenerator::separateSubdomainsByElementType(), FEProblemBase::setCoupling(), MooseBase::typeAndName(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), DisplacedProblem::updateGeomSearch(), FEProblemBase::updateGeomSearch(), UserObjectInterface::userObjectType(), and AdvancedOutput::wantOutput().
typeAndName()
std::string MooseBase::typeAndName () const inline inherited
Get the class's combined type and name; useful in error handling.
Returns
The type and name of this class in the form '<type()> "<name()>"'.
Definition at line 53 of file MooseBase.h.
  {
    return type() + std::string(" \"") + name() + std::string("\"");
  }
Referenced by ReporterContext< T >::finalize(), and ReporterData::getReporterInfo().
uniqueName()
MooseObjectName MooseBaseParameterInterface::uniqueName () const inline inherited
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
Definition at line 58 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectName(_pars.get<std::string>("_unique_name"));
  }
Referenced by MooseBaseParameterInterface::connectControllableParams(), and Action::uniqueActionName().
uniqueParameterName()
MooseObjectParameterName MooseBaseParameterInterface::uniqueParameterName (const std::string & parameter_name) const inline inherited
The unique parameter name of a valid parameter of this object for accessing parameter controls.
Definition at line 43 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectParameterName(
        _pars.get<std::string>("_moose_base"), _moose_base->name(), parameter_name);
  }
usesMooseAppCoordTransform()
bool MultiAppGeneralFieldShapeEvaluationTransfer::usesMooseAppCoordTransform () const inline override private virtual
Whether this transfer handles non-translation-based transformations, e.g.
whether it uses the MooseAppCoordTransform object
Reimplemented from MultiAppTransfer.
Definition at line 34 of file MultiAppGeneralFieldShapeEvaluationTransfer.h.
{ return true; }
validParams()
InputParameters MultiAppGeneralFieldShapeEvaluationTransfer::validParams () static
Definition at line 26 of file MultiAppGeneralFieldShapeEvaluationTransfer.C.
{
  InputParameters params = MultiAppGeneralFieldTransfer::validParams();
  params.addClassDescription(
      "Transfers field data at the MultiApp position using the finite element shape "
      "functions from the origin application.");
  // Blanket ban on origin boundary restriction. Most shape functions have their support extend
  // outside the boundary. For a true face variable, this parameter would make sense again
  params.suppressParameter<std::vector<BoundaryName>>("from_boundaries");
  // Shape function evaluations return an invalid value outside an app's domain anyway
  params.suppressParameter<bool>("from_app_must_contain_point");
  return params;
}
variableIntegrityCheck()
void MultiAppTransfer::variableIntegrityCheck (const AuxVariableName & var_name) const inherited
Utility to verify that the variable in the destination system exists.
Definition at line 188 of file MultiAppTransfer.C.
{
  bool variable_found = false;
  bool has_an_app = false;
  // Check the from_multi_app for the variable
  if (_from_multi_app)
    for (unsigned int i = 0; i < _from_multi_app->numGlobalApps(); i++)
      if (_from_multi_app->hasLocalApp(i))
      {
        has_an_app = true;
        if (_from_multi_app->appProblemBase(i).hasVariable(var_name))
          variable_found = true;
      }
  // Check the to_multi_app for the variable
  if (_to_multi_app)
    for (unsigned int i = 0; i < _to_multi_app->numGlobalApps(); i++)
      if (_to_multi_app->hasLocalApp(i))
      {
        has_an_app = true;
        if (_to_multi_app->appProblemBase(i).hasVariable(var_name))
          variable_found = true;
      }
  if (!variable_found && has_an_app)
    mooseError("Cannot find variable ", var_name, " for ", name(), " Transfer");
}
Referenced by MultiAppFieldTransfer::initialSetup(), and MultiAppVariableValueSampleTransfer::initialSetup().
Member Data Documentation
_action_factory
ActionFactory& MooseBaseParameterInterface::_action_factory protected inherited
Builds Actions.
Definition at line 164 of file MooseBaseParameterInterface.h.
Referenced by CommonOutputAction::create(), AddVariableAction::createInitialConditionAction(), AddSpecies::createInitialConditions(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
_allow_skipped_adjustment
bool MultiAppConservativeTransfer::_allow_skipped_adjustment private inherited
Whether the adjustment may be skipped when the postprocessor values are 0 / of different signs.
Definition at line 70 of file MultiAppConservativeTransfer.h.
Referenced by MultiAppConservativeTransfer::performAdjustment().
_app
MooseApp& MooseBase::_app protected inherited
The MOOSE application this is associated with.
Definition at line 60 of file MooseBase.h.
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), MeshGenerator::addChildMeshGenerator(), FEProblemBase::addMaterialHelper(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addOutput(), MeshGenerator::addParentMeshGenerator(), FVFluxKernel::adjustRMGhostLayers(), FEProblemBase::allowOutput(), AStableDirk4::AStableDirk4(), FileMesh::buildMesh(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), MeshGenerator::checkGetMesh(), FEProblemBase::checkICRestartError(), FEProblemBase::checkNonlinearConvergence(), OversampleOutput::cloneMesh(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), Console::Console(), TimeStepper::constrainStep(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::createLocalApp(), FEProblemBase::customSetup(), MeshGenerator::declareMeshProperty(), MeshGenerator::declareNullMeshName(), MooseMesh::determineUseDistributedMesh(), DumpObjectsProblem::dumpObjectHelper(), DumpObjectsProblem::dumpVariableHelper(), EigenExecutionerBase::EigenExecutionerBase(), EigenKernel::EigenKernel(), PIDTransientControl::execute(), Eigenvalue::execute(), InversePowerMethod::execute(), NonlinearEigen::execute(), Steady::execute(), Transient::execute(), PseudoTimestep::execute(), IterationInfo::execute(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FileOutput::FileOutput(), ChangeOverFixedPointPostprocessor::finalize(), RadialAverage::finalize(), FixedPointSolve::FixedPointSolve(), FEProblemBase::forceOutput(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), SideSetsFromNormalsGenerator::generate(), MeshGenerator::generateInternal(), FEProblemBase::getExecutor(), MeshGenerator::getMeshByName(), NumFixedPointIterations::getValue(), NumRelationshipManagers::getValue(), GhostingUserObject::GhostingUserObject(), MooseMesh::init(), InversePowerMethod::init(), NonlinearEigen::init(), Transient::init(), FEProblemBase::init(), TimePeriod::initialSetup(), Console::initialSetup(), AdvancedOutput::initOutputList(), FEProblemBase::initPetscOutput(), EigenProblem::initPetscOutput(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MeshGenerator::MeshGenerator(), EigenExecutionerBase::normalizeSolution(), NumFailedTimeSteps::NumFailedTimeSteps(), AugmentSparsityOnInterface::operator()(), Checkpoint::output(), Exodus::output(), Nemesis::output(), PerfGraphOutput::output(), Tecplot::output(), MortarNodalGeometryOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Exodus::outputEmptyTimestep(), Console::outputInput(), Exodus::outputInput(), Exodus::outputNodalVariables(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), Console::outputSystemInformation(), JSONOutput::outputSystemInformation(), MultiApp::parentOutputPositionChanged(), PIDTransientControl::PIDTransientControl(), Transient::preExecute(), Eigenvalue::prepareSolverOptions(), FEProblemBase::projectSolution(), MultiApp::setAppOutputFileBase(), FileOutput::setFileBaseInternal(), MeshGenerator::setMeshProperty(), MeshGenerator::setMeshPropertyHelper(), FEProblemBase::setRestartFile(), TransientMultiApp::setupApp(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SolutionInvalidityReporter::SolutionInvalidityReporter(), FEProblemBase::solve(), EigenProblem::solve(), PetscOutput::solveSetup(), TransientMultiApp::solveStep(), FEProblemBase::subdomainSetup(), FEProblemBase::theWarehouse(), TimeExtremeValue::TimeExtremeValue(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), Transient::Transient(), FEProblemBase::updateMortarMesh(), Console::write(), and FEProblemBase::~FEProblemBase().
_bbox_factor
Real MultiAppGeneralFieldTransfer::_bbox_factor private inherited
How much we should relax bounding boxes.
Definition at line 338 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::prepareToTransfer().
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_current_direction
MooseEnum Transfer::_current_direction protected inherited
Definition at line 106 of file Transfer.h.
Referenced by MultiAppConservativeTransfer::adjustTransferredSolution(), MultiAppConservativeTransfer::adjustTransferredSolutionNearestPoint(), Transfer::currentDirection(), MultiAppCloneReporterTransfer::execute(), MultiAppCopyTransfer::execute(), MultiAppGeometricInterpolationTransfer::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppReporterTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), MultiAppVectorPostprocessorTransfer::execute(), MultiAppTransfer::getAppInfo(), MultiAppTransfer::getGlobalSourceAppIndex(), MultiAppTransfer::getGlobalTargetAppIndex(), MultiAppTransfer::getLocalSourceAppIndex(), MultiAppFieldTransfer::initialSetup(), MultiAppConservativeTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppConservativeTransfer::postExecute(), Transfer::setCurrentDirection(), Transfer::Transfer(), and MultiAppShapeEvaluationTransfer::transferVariable().
_current_execute_flag
const ExecFlagType& SetupInterface::_current_execute_flag protected inherited
Reference to FEProblemBase.
Definition at line 78 of file SetupInterface.h.
Referenced by PseudoTimestep::execute().
_default_extrapolation_value
const Real MultiAppGeneralFieldTransfer::_default_extrapolation_value private inherited
Value to use when no received data is valid for a target location.
Definition at line 335 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::setSolutionVectorValues().
_direction
MooseEnum Transfer::_direction protected inherited
The current direction that is being executed for this Transfer. _direction is to be deprecated for _current_direction
Definition at line 105 of file Transfer.h.
Referenced by Transfer::direction(), MultiAppTransfer::MultiAppTransfer(), Transfer::setCurrentDirection(), and Transfer::Transfer().
_directions
MultiMooseEnum Transfer::_directions protected inherited
The directions this Transfer is to be executed on.
Definition at line 110 of file Transfer.h.
Referenced by MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), Transfer::directions(), MultiAppReporterTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::setupPostprocessorCommunication(), and Transfer::Transfer().
_displaced_source_mesh
bool MultiAppTransfer::_displaced_source_mesh protected inherited
True if displaced mesh is used for the source mesh, otherwise false.
Definition at line 154 of file MultiAppTransfer.h.
Referenced by MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), buildMeshFunctions(), MultiAppUserObjectTransfer::execute(), MultiAppGeometricInterpolationTransfer::fillSourceInterpolationPoints(), MultiAppUserObjectTransfer::findSubAppToTransferFrom(), MultiAppTransfer::getAppInfo(), MultiAppGeneralFieldTransfer::getAppInfo(), MultiAppGeneralFieldTransfer::getRestrictedFromBoundingBoxes(), MultiAppGeneralFieldTransfer::initialSetup(), and MultiAppShapeEvaluationTransfer::transferVariable().
_displaced_target_mesh
bool MultiAppTransfer::_displaced_target_mesh protected inherited
True if displaced mesh is used for the target mesh, otherwise false.
Definition at line 156 of file MultiAppTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::cacheIncomingInterpVals(), MultiAppGeneralFieldTransfer::examineLocalValueConflicts(), MultiAppGeneralFieldTransfer::examineReceivedValueConflicts(), MultiAppUserObjectTransfer::execute(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), MultiAppTransfer::getAppInfo(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppGeometricInterpolationTransfer::interpolateTargetPoints(), and MultiAppGeneralFieldTransfer::setSolutionVectorValues().
_elemental_boundary_restriction_on_sides
const bool MultiAppGeneralFieldTransfer::_elemental_boundary_restriction_on_sides protected inherited
Whether elemental variable boundary restriction is considered by element side or element nodes.
Definition at line 250 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::onBoundaries().
_empty_execute_enum
ExecFlagEnum SetupInterface::_empty_execute_enum private inherited
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
This is private because others should not be messing with it.
Definition at line 71 of file SetupInterface.h.
Referenced by SetupInterface::SetupInterface().
_enabled
const bool& MooseObject::_enabled protected inherited
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
Definition at line 58 of file MooseObject.h.
Referenced by MooseObject::enabled().
_error_on_miss
bool MultiAppGeneralFieldTransfer::_error_on_miss private inherited
Error out when some points can not be located.
Definition at line 332 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::locatePointReceivers(), and MultiAppGeneralFieldTransfer::setSolutionVectorValues().
_execute_enum
const ExecFlagEnum& SetupInterface::_execute_enum protected inherited
Execute settings for this object.
Definition at line 75 of file SetupInterface.h.
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), SetupInterface::getExecuteOnEnum(), JSONOutput::outputReporters(), XMLOutput::outputVectorPostprocessors(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
_factory
Factory& MooseBaseParameterInterface::_factory protected inherited
The Factory associated with the MooseApp.
Definition at line 161 of file MooseBaseParameterInterface.h.
Referenced by AddGeneralReactions::act(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), ElementIDOutputAction::act(), AddSpecies::act(), AdaptivityAction::act(), AddControlAction::act(), AddNodalNormalsAction::act(), AddPeriodicBCAction::act(), AutoCheckpointAction::act(), ComposeTimeStepperAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DisplayGhostingAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), PartitionerAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SetupPreconditionerAction::act(), SetupPredictorAction::act(), SetupResidualDebugAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddGeneralReactions::addEEDFReactionKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddDriftDiffusionAction::addPosition(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), MooseBaseParameterInterface::connectControllableParams(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), MaterialOutputAction::getParams(), and ProjectedStatefulMaterialStorageAction::processProperty().
_fe_problem
FEProblemBase& Transfer::_fe_problem protected inherited
Definition at line 97 of file Transfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), MultiAppGeneralFieldTransfer::closestToPosition(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppGeneralFieldNearestLocationTransfer::getNumDivisions(), MultiAppGeneralFieldNearestLocationTransfer::getNumSources(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), and MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer().
_fixed_bbox_size
std::vector<Real> MultiAppGeneralFieldTransfer::_fixed_bbox_size private inherited
Set the bounding box sizes manually.
Definition at line 341 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::getRestrictedFromBoundingBoxes().
_from_bboxes
std::vector<BoundingBox> MultiAppGeneralFieldTransfer::_from_bboxes private inherited
Bounding boxes for all source applications.
The indexing of this vector is similar to 'processor_id * n_local_subapps + i_local_subapp', except the number of local subapps can be different on each processor. Use the _from_per_proc vector to find the start/end index for a given processor. See MultiAppGeneralFieldTransfer::locatePointReceivers() for an example
Definition at line 350 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::extractLocalFromBoundingBoxes(), MultiAppGeneralFieldTransfer::locatePointReceivers(), and MultiAppGeneralFieldTransfer::prepareToTransfer().
_from_blocks
std::set<SubdomainID> MultiAppGeneralFieldTransfer::_from_blocks protected inherited
Origin block(s) restriction.
Definition at line 218 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldTransfer::getRestrictedFromBoundingBoxes(), and MultiAppGeneralFieldTransfer::initialSetup().
_from_boundaries
std::set<BoundaryID> MultiAppGeneralFieldTransfer::_from_boundaries protected inherited
Origin boundary(ies) restriction.
Definition at line 227 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldTransfer::getRestrictedFromBoundingBoxes(), and MultiAppGeneralFieldTransfer::initialSetup().
_from_es
std::vector<EquationSystems *> MultiAppTransfer::_from_es protected inherited
Definition at line 141 of file MultiAppTransfer.h.
Referenced by MultiAppTransfer::getAppInfo().
_from_local2global_map
std::vector<unsigned int> MultiAppTransfer::_from_local2global_map protected inherited
Given local app index, returns global app index.
Definition at line 198 of file MultiAppTransfer.h.
Referenced by MultiAppNearestNodeTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppTransfer::getAppInfo(), MultiAppTransfer::getFromMultiAppInfo(), MultiAppTransfer::getGlobalSourceAppIndex(), MultiAppGeneralFieldTransfer::getGlobalStartAppPerProc(), MultiAppTransfer::getLocalSourceAppIndex(), MultiAppGeneralFieldTransfer::outputValueConflicts(), and MultiAppShapeEvaluationTransfer::transferVariable().
_from_mesh_division_behavior
const MooseEnum& MultiAppGeneralFieldTransfer::_from_mesh_division_behavior protected inherited
How to use the origin mesh divisions to restrict the transfer.
Definition at line 236 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointMeshDivision(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldTransfer::cacheOutgoingPointInfo(), MultiAppGeneralFieldNearestLocationTransfer::checkRestrictionsForSource(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), and MultiAppGeneralFieldShapeEvaluationTransfer().
_from_mesh_divisions
std::vector<const MeshDivision *> MultiAppGeneralFieldTransfer::_from_mesh_divisions protected inherited
Division of the origin mesh.
Definition at line 230 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppGeneralFieldTransfer::acceptPointMeshDivision(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldNearestLocationTransfer::checkRestrictionsForSource(), MultiAppGeneralFieldNearestLocationTransfer::getNumDivisions(), MultiAppGeneralFieldNearestLocationTransfer::getNumSources(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), and MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer().
_from_meshes
std::vector<MooseMesh *> MultiAppTransfer::_from_meshes protected inherited
Definition at line 143 of file MultiAppTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppNearestNodeTransfer::execute(), MultiAppTransfer::getAppInfo(), MultiAppTransfer::getFromBoundingBoxes(), MultiAppGeneralFieldNearestLocationTransfer::getNumAppsPerTree(), and MultiAppGeneralFieldTransfer::getRestrictedFromBoundingBoxes().
_from_moose_app_transform
std::unique_ptr<MooseAppCoordTransform> MultiAppTransfer::_from_moose_app_transform private inherited
The moose coordinate transformation object describing rotations, scaling, and coordinate system of the from application.
Definition at line 259 of file MultiAppTransfer.h.
Referenced by MultiAppTransfer::getAppInfo().
_from_multi_app
std::shared_ptr<MultiApp> MultiAppTransfer::_from_multi_app private inherited
The MultiApps this Transfer is transferring data to or from.
Definition at line 251 of file MultiAppTransfer.h.
Referenced by MultiAppTransfer::checkMultiAppExecuteOn(), MultiAppTransfer::getAppInfo(), MultiAppTransfer::getFromMultiApp(), MultiAppTransfer::getFromMultiAppInfo(), MultiAppTransfer::getFromName(), MultiAppTransfer::getFromsPerProc(), MultiAppTransfer::getMultiApp(), MultiAppTransfer::hasFromMultiApp(), MultiAppTransfer::initialSetup(), MultiAppTransfer::MultiAppTransfer(), and MultiAppTransfer::variableIntegrityCheck().
_from_point_locators
std::vector<std::unique_ptr<PointLocatorBase> > MultiAppGeneralFieldTransfer::_from_point_locators protected inherited
Point locators, useful to examine point location with regards to domain restriction.
Definition at line 253 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppGeneralFieldNearestLocationTransfer::checkRestrictionsForSource(), and MultiAppGeneralFieldTransfer::getAppInfo().
_from_positions
std::vector<Point> MultiAppTransfer::_from_positions protected inherited
Definition at line 145 of file MultiAppTransfer.h.
Referenced by MultiAppTransfer::getAppInfo(), MultiAppTransfer::getFromMultiAppInfo(), and MultiAppGeneralFieldNearestLocationTransfer::getPointInLocalSourceFrame().
_from_postprocessors_to_be_preserved
std::vector<PostprocessorName> MultiAppConservativeTransfer::_from_postprocessors_to_be_preserved protected inherited
Postprocessor evaluates an adjuster for the source physics.
Definition at line 51 of file MultiAppConservativeTransfer.h.
Referenced by MultiAppConservativeTransfer::initialSetup(), and MultiAppConservativeTransfer::postExecute().
_from_problems
std::vector<FEProblemBase *> MultiAppTransfer::_from_problems protected inherited
Definition at line 139 of file MultiAppTransfer.h.
Referenced by MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), buildMeshFunctions(), evaluateInterpValuesWithMeshFunctions(), MultiAppGeneralFieldUserObjectTransfer::evaluateInterpValuesWithUserObjects(), MultiAppNearestNodeTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppTransfer::getAppInfo(), MultiAppGeneralFieldTransfer::getAppInfo(), MultiAppTransfer::getFromMultiAppInfo(), MultiAppGeneralFieldNearestLocationTransfer::getNumSources(), MultiAppGeneralFieldTransfer::getRestrictedFromBoundingBoxes(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppGeneralFieldTransfer::outputValueConflicts(), and MultiAppShapeEvaluationTransfer::transferVariable().
_from_transforms
std::vector<std::unique_ptr<MultiAppCoordTransform> > MultiAppTransfer::_from_transforms protected inherited
Definition at line 147 of file MultiAppTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldNearestLocationTransfer::evaluateInterpValuesNearestNode(), evaluateInterpValuesWithMeshFunctions(), MultiAppGeneralFieldUserObjectTransfer::evaluateInterpValuesWithUserObjects(), MultiAppGeneralFieldTransfer::examineLocalValueConflicts(), MultiAppGeometricInterpolationTransfer::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppUserObjectTransfer::findSubAppToTransferFrom(), MultiAppTransfer::getAppInfo(), MultiAppTransfer::getFromBoundingBoxes(), MultiAppGeneralFieldNearestLocationTransfer::getPointInLocalSourceFrame(), MultiAppGeneralFieldTransfer::getRestrictedFromBoundingBoxes(), and MultiAppShapeEvaluationTransfer::transferVariable().
_from_var_components
const std::vector<unsigned int> MultiAppGeneralFieldTransfer::_from_var_components protected inherited
Origin array/vector variable components.
Definition at line 191 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::getFromVarName(), MultiAppGeneralFieldTransfer::initialSetup(), and MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer().
_from_var_name
VariableName MultiAppConservativeTransfer::_from_var_name protected inherited
This values are used if a derived class only supports one variable.
Definition at line 45 of file MultiAppConservativeTransfer.h.
Referenced by MultiAppGeometricInterpolationTransfer::execute(), MultiAppNearestNodeTransfer::execute(), and MultiAppProjectionTransfer::execute().
_from_var_names
const std::vector<VariableName> MultiAppConservativeTransfer::_from_var_names protected inherited
Name of variables transferring from.
Definition at line 40 of file MultiAppConservativeTransfer.h.
Referenced by MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), buildMeshFunctions(), MultiAppGeneralFieldTransfer::getFromVarName(), MultiAppConservativeTransfer::getFromVarNames(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppGeneralFieldTransfer::outputValueConflicts(), MultiAppGeneralFieldTransfer::transferVariable(), and MultiAppShapeEvaluationTransfer::transferVariable().
_froms_per_proc
std::vector<unsigned int> MultiAppGeneralFieldTransfer::_froms_per_proc private inherited
Number of source/from applications per processor. This vector is indexed by processor id.
Definition at line 344 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::extractLocalFromBoundingBoxes(), MultiAppGeneralFieldTransfer::locatePointReceivers(), and MultiAppGeneralFieldTransfer::prepareToTransfer().
_global_app_start_per_proc
std::vector<unsigned int> MultiAppGeneralFieldTransfer::_global_app_start_per_proc protected inherited
First app each processor owns, indexed by processor If no app on the processor, will have a -1 for the app start instead.
Definition at line 257 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::locatePointReceivers(), and MultiAppGeneralFieldTransfer::prepareToTransfer().
_greedy_search
bool MultiAppGeneralFieldTransfer::_greedy_search protected inherited
Whether or not a greedy strategy will be used If true, all the partitions will be checked for a given outgoing point.
Definition at line 262 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::locatePointReceivers().
_local_bboxes
std::vector<BoundingBox> MultiAppGeneralFieldShapeEvaluationTransfer::_local_bboxes private
Definition at line 58 of file MultiAppGeneralFieldShapeEvaluationTransfer.h.
Referenced by evaluateInterpValues(), and prepareEvaluationOfInterpValues().
_local_conflicts
std::vector<std::tuple<unsigned int, dof_id_type, Point, Real> > MultiAppGeneralFieldTransfer::_local_conflicts private inherited
Keeps track of all local equidistant points to requested points, creating an indetermination in which values should be sent for that request We keep the origin problem ID, the dof ID, the point, and the distance origin-target If using nearest-positions the origin problem ID is not set.
Definition at line 359 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::examineLocalValueConflicts(), MultiAppGeneralFieldTransfer::outputValueConflicts(), and MultiAppGeneralFieldTransfer::registerConflict().
_local_meshfuns
std::vector<MeshFunction> MultiAppGeneralFieldShapeEvaluationTransfer::_local_meshfuns private
Definition at line 62 of file MultiAppGeneralFieldShapeEvaluationTransfer.h.
Referenced by evaluateInterpValues(), and prepareEvaluationOfInterpValues().
_metaname
const RestartableDataMapName Restartable::_metaname private inherited
Restartable metadata name.
Definition at line 240 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_moose_base
const MooseBase* const MooseBaseParameterInterface::_moose_base private inherited
The MooseBase object that inherits this class.
Definition at line 168 of file MooseBaseParameterInterface.h.
Referenced by MooseBaseParameterInterface::connectControllableParams(), MooseBaseParameterInterface::objectErrorPrefix(), MooseBaseParameterInterface::paramError(), and MooseBaseParameterInterface::uniqueParameterName().
_multi_app
std::shared_ptr<MultiApp> MultiAppTransfer::_multi_app protected inherited
Deprecated class attribute for compatibility with the apps.
Definition at line 136 of file MultiAppTransfer.h.
Referenced by MultiAppUserObjectTransfer::execute(), MultiAppUserObjectTransfer::findSubAppToTransferFrom(), MultiAppTransfer::getMultiApp(), and MultiAppTransfer::MultiAppTransfer().
_name
const std::string& MooseBase::_name protected inherited
The name of this class, reference to value stored in InputParameters.
Definition at line 66 of file MooseBase.h.
Referenced by AddFieldSplitAction::act(), AddBCAction::act(), AddConstraintAction::act(), AddControlAction::act(), AddDamperAction::act(), AddDGKernelAction::act(), AddDiracKernelAction::act(), AddDistributionAction::act(), AddFunctionAction::act(), AddFunctorMaterialAction::act(), AddFVBCAction::act(), AddFVInitialConditionAction::act(), AddFVInterfaceKernelAction::act(), AddFVKernelAction::act(), AddIndicatorAction::act(), AddInitialConditionAction::act(), AddInterfaceKernelAction::act(), AddKernelAction::act(), AddMarkerAction::act(), AddMaterialAction::act(), AddMeshDivisionAction::act(), AddMeshGeneratorAction::act(), AddMultiAppAction::act(), AddNodalKernelAction::act(), AddOutputAction::act(), AddPeriodicBCAction::act(), AddPositionsAction::act(), AddPostprocessorAction::act(), AddReporterAction::act(), AddSamplerAction::act(), AddScalarKernelAction::act(), AddTimesAction::act(), AddTimeStepperAction::act(), AddTransferAction::act(), AddUserObjectAction::act(), AddVectorPostprocessorAction::act(), PartitionerAction::act(), ReadExecutorParamsAction::act(), SetupPreconditionerAction::act(), SetupTimeIntegratorAction::act(), AddDriftDiffusionAction::addADKernels(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromXY(), PiecewiseLinearBase::buildInterpolation(), CombinerGenerator::CombinerGenerator(), Executor::Executor(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), FunctionDT::FunctionDT(), FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), MooseBase::name(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), PiecewiseBase::setData(), and Split::setup().
_nearest_positions_obj
const Positions* MultiAppGeneralFieldTransfer::_nearest_positions_obj protected inherited
Definition at line 211 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldNearestLocationTransfer::checkRestrictionsForSource(), MultiAppGeneralFieldTransfer::closestToPosition(), MultiAppGeneralFieldNearestLocationTransfer::evaluateInterpValuesNearestNode(), evaluateInterpValuesWithMeshFunctions(), MultiAppGeneralFieldUserObjectTransfer::evaluateInterpValuesWithUserObjects(), MultiAppGeneralFieldTransfer::examineLocalValueConflicts(), MultiAppGeneralFieldNearestLocationTransfer::getNumDivisions(), MultiAppGeneralFieldNearestLocationTransfer::getNumSources(), MultiAppGeneralFieldNearestLocationTransfer::getPointInLocalSourceFrame(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), and MultiAppGeneralFieldTransfer::outputValueConflicts().
_parent
const MooseObject & DataFileInterface< MooseObject >::_parent private inherited
Definition at line 46 of file DataFileInterface.h.
_pars
const InputParameters& MooseBaseParameterInterface::_pars protected inherited
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Definition at line 158 of file MooseBaseParameterInterface.h.
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), AddPeriodicBCAction::act(), AddVariableAction::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), FunctorMaterial::addFunctorPropertyByBlocks(), FVFluxKernel::adjustRMGhostLayers(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), PiecewiseTabularBase::buildFromFile(), PNGOutput::calculateRescalingValues(), BlockWeightedPartitioner::clone(), GridPartitioner::clone(), HierarchicalGridPartitioner::clone(), PetscExternalPartitioner::clone(), RandomPartitioner::clone(), SingleRankPartitioner::clone(), MooseBaseParameterInterface::connectControllableParams(), Console::Console(), AddVariableAction::createInitialConditionAction(), MaterialBase::declareADProperty(), MaterialBase::declareProperty(), FEProblemSolve::FEProblemSolve(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), FileMeshGenerator::generate(), MaterialBase::getGenericZeroMaterialProperty(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getParam(), MooseBaseParameterInterface::getRenamedParam(), AddVariableAction::init(), AdvancedOutput::initExecutionTypes(), Console::initialSetup(), MooseBaseParameterInterface::isParamSetByUser(), MooseBaseParameterInterface::isParamValid(), MultiApp::keepSolutionDuringRestore(), MooseBaseParameterInterface::paramErrorMsg(), GlobalParamsAction::parameters(), MooseBaseParameterInterface::parameters(), MooseMesh::prepare(), Eigenvalue::prepareSolverOptions(), MooseMesh::setCoordSystem(), MooseMesh::setPartitionerHelper(), SetupMeshAction::setupMesh(), Transient::setupTimeIntegrator(), MooseBaseParameterInterface::uniqueName(), and MooseBaseParameterInterface::uniqueParameterName().
_pg_moose_app
MooseApp& PerfGraphInterface::_pg_moose_app protected inherited
The MooseApp that owns the PerfGraph.
Definition at line 124 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::perfGraph().
_prefix
const std::string PerfGraphInterface::_prefix protected inherited
A prefix to use for all sections.
Definition at line 127 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::timedSectionName().
_preserve_transfer
bool MultiAppConservativeTransfer::_preserve_transfer protected inherited
If this transfer is going to conserve the physics.
Definition at line 49 of file MultiAppConservativeTransfer.h.
Referenced by MultiAppConservativeTransfer::initialSetup(), and MultiAppConservativeTransfer::postExecute().
_processor_to_pointInfoVec
ProcessorToPointInfoVec MultiAppGeneralFieldTransfer::_processor_to_pointInfoVec private inherited
A map from processor to pointInfo vector.
Definition at line 353 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::cacheOutgoingPointInfo(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), and MultiAppGeneralFieldTransfer::transferVariable().
_received_conflicts
std::vector<std::tuple<unsigned int, dof_id_type, Point, Real> > MultiAppGeneralFieldTransfer::_received_conflicts private inherited
Keeps track of all received conflicts.
Multiple problems (different subapps for example) are sending values for a target point that do not match and are equally valid/distant We keep the target problem ID, the point/dof ID, the point, and the origin-target distance. The distance indicates whether a potential conflict ended up materializing
Definition at line 365 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::examineReceivedValueConflicts(), MultiAppGeneralFieldTransfer::outputValueConflicts(), and MultiAppGeneralFieldTransfer::registerConflict().
_restartable_app
MooseApp& Restartable::_restartable_app protected inherited
Reference to the application.
Definition at line 227 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp(), and Restartable::registerRestartableNameWithFilterOnApp().
_restartable_name
std::string Restartable::_restartable_name private inherited
The name of the object.
Definition at line 243 of file Restartable.h.
Referenced by Restartable::declareRestartableDataWithObjectNameWithContext(), and Restartable::restartableName().
_restartable_read_only
const bool Restartable::_restartable_read_only protected inherited
Flag for toggling read only status (see ReporterData)
Definition at line 236 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_restartable_system_name
const std::string Restartable::_restartable_system_name protected inherited
The system name this object is in.
Definition at line 230 of file Restartable.h.
Referenced by Restartable::restartableName().
_restartable_tid
const THREAD_ID Restartable::_restartable_tid protected inherited
The thread ID for this object.
Definition at line 233 of file Restartable.h.
Referenced by Restartable::declareRestartableDataHelper().
_search_value_conflicts
const bool MultiAppGeneralFieldTransfer::_search_value_conflicts protected inherited
Whether to look for conflicts between origin points, multiple valid values for a target point.
Definition at line 265 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::cacheIncomingInterpVals(), MultiAppGeneralFieldTransfer::detectConflict(), MultiAppGeneralFieldNearestLocationTransfer::evaluateInterpValuesNearestNode(), evaluateInterpValuesWithMeshFunctions(), MultiAppGeneralFieldUserObjectTransfer::evaluateInterpValuesWithUserObjects(), and MultiAppGeneralFieldTransfer::transferVariable().
_skip_coordinate_collapsing
const bool MultiAppTransfer::_skip_coordinate_collapsing protected inherited
Whether to skip coordinate collapsing (transformations of coordinates between applications using different frames of reference)
Definition at line 151 of file MultiAppTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppGeneralFieldTransfer::closestToPosition(), MultiAppGeneralFieldNearestLocationTransfer::evaluateInterpValuesNearestNode(), MultiAppTransfer::getAppInfo(), MultiAppGeneralFieldNearestLocationTransfer::getPointInLocalSourceFrame(), MultiAppTransfer::getPointInTargetAppFrame(), and MultiAppGeneralFieldTransfer::outputValueConflicts().
_source_app_must_contain_point
bool MultiAppGeneralFieldTransfer::_source_app_must_contain_point protected inherited
Whether the source app mesh must actually contain the points for them to be considered or whether the bounding box is enough.
If false, we can interpolate between apps
Definition at line 215 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppGeneralFieldNearestLocationTransfer::checkRestrictionsForSource(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), and MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer().
_subproblem
SubProblem& Transfer::_subproblem protected inherited
Definition at line 96 of file Transfer.h.
_sys
SystemBase& Transfer::_sys protected inherited
Definition at line 98 of file Transfer.h.
_tid
THREAD_ID Transfer::_tid protected inherited
Definition at line 100 of file Transfer.h.
Referenced by MultiAppPostprocessorToAuxScalarTransfer::execute(), and MultiAppScalarToAuxScalarTransfer::execute().
_to_blocks
std::set<SubdomainID> MultiAppGeneralFieldTransfer::_to_blocks protected inherited
Target block(s) restriction.
Definition at line 221 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::extractOutgoingPoints(), MultiAppGeneralFieldTransfer::initialSetup(), and MultiAppGeneralFieldTransfer::setSolutionVectorValues().
_to_boundaries
std::set<BoundaryID> MultiAppGeneralFieldTransfer::_to_boundaries protected inherited
Target boundary(ies) restriction.
Definition at line 224 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::extractOutgoingPoints(), and MultiAppGeneralFieldTransfer::initialSetup().
_to_es
std::vector<EquationSystems *> MultiAppTransfer::_to_es protected inherited
Definition at line 140 of file MultiAppTransfer.h.
Referenced by MultiAppNearestNodeTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppTransfer::getAppInfo(), and MultiAppShapeEvaluationTransfer::transferVariable().
_to_local2global_map
std::vector<unsigned int> MultiAppTransfer::_to_local2global_map protected inherited
Given local app index, returns global app index.
Definition at line 196 of file MultiAppTransfer.h.
Referenced by MultiAppNearestNodeTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppTransfer::getAppInfo(), MultiAppTransfer::getGlobalTargetAppIndex(), MultiAppTransfer::getToMultiAppInfo(), MultiAppTransfer::getTransferVector(), MultiAppGeneralFieldTransfer::outputValueConflicts(), and MultiAppShapeEvaluationTransfer::transferVariable().
_to_mesh_division_behavior
const MooseEnum& MultiAppGeneralFieldTransfer::_to_mesh_division_behavior protected inherited
How to use the target mesh divisions to restrict the transfer.
Definition at line 239 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointMeshDivision(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldTransfer::cacheOutgoingPointInfo(), MultiAppGeneralFieldNearestLocationTransfer::checkRestrictionsForSource(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppGeneralFieldTransfer::locatePointReceivers(), and MultiAppGeneralFieldShapeEvaluationTransfer().
_to_mesh_divisions
std::vector<const MeshDivision *> MultiAppGeneralFieldTransfer::_to_mesh_divisions protected inherited
Division of the target mesh.
Definition at line 233 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppGeneralFieldTransfer::cacheOutgoingPointInfo(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), MultiAppGeneralFieldTransfer::initialSetup(), and MultiAppGeneralFieldTransfer::locatePointReceivers().
_to_meshes
std::vector<MooseMesh *> MultiAppTransfer::_to_meshes protected inherited
Definition at line 142 of file MultiAppTransfer.h.
Referenced by MultiAppNearestNodeTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppTransfer::getAppInfo(), MultiAppGeneralFieldTransfer::getMaxToProblemsBBoxDimensions(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), MultiAppGeneralFieldTransfer::locatePointReceivers(), MultiAppGeneralFieldTransfer::setSolutionVectorValues(), and MultiAppShapeEvaluationTransfer::transferVariable().
_to_moose_app_transform
std::unique_ptr<MooseAppCoordTransform> MultiAppTransfer::_to_moose_app_transform private inherited
The moose coordinate transformation object describing rotations, scaling, and coordinate system of the to application.
Definition at line 263 of file MultiAppTransfer.h.
Referenced by MultiAppTransfer::getAppInfo().
_to_multi_app
std::shared_ptr<MultiApp> MultiAppTransfer::_to_multi_app private inherited
Definition at line 252 of file MultiAppTransfer.h.
Referenced by MultiAppTransfer::checkMultiAppExecuteOn(), MultiAppTransfer::getAppInfo(), MultiAppTransfer::getFromsPerProc(), MultiAppTransfer::getMultiApp(), MultiAppTransfer::getToMultiApp(), MultiAppTransfer::getToMultiAppInfo(), MultiAppTransfer::getToName(), MultiAppTransfer::getTransferVector(), MultiAppTransfer::hasToMultiApp(), MultiAppTransfer::initialSetup(), MultiAppTransfer::MultiAppTransfer(), and MultiAppTransfer::variableIntegrityCheck().
_to_positions
std::vector<Point> MultiAppTransfer::_to_positions protected inherited
Definition at line 144 of file MultiAppTransfer.h.
Referenced by MultiAppTransfer::getAppInfo(), and MultiAppTransfer::getToMultiAppInfo().
_to_postprocessors_to_be_preserved
std::vector<PostprocessorName> MultiAppConservativeTransfer::_to_postprocessors_to_be_preserved protected inherited
Postprocessor evaluates an adjuster for the target physics.
Definition at line 53 of file MultiAppConservativeTransfer.h.
Referenced by MultiAppConservativeTransfer::initialSetup(), and MultiAppConservativeTransfer::postExecute().
_to_problems
std::vector<FEProblemBase *> MultiAppTransfer::_to_problems protected inherited
Definition at line 138 of file MultiAppTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::cacheIncomingInterpVals(), MultiAppGeneralFieldTransfer::examineLocalValueConflicts(), MultiAppGeneralFieldTransfer::examineReceivedValueConflicts(), MultiAppNearestNodeTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), MultiAppTransfer::getAppInfo(), MultiAppTransfer::getToMultiAppInfo(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppProjectionTransfer::initialSetup(), MultiAppGeneralFieldTransfer::outputValueConflicts(), MultiAppProjectionTransfer::projectSolution(), MultiAppGeneralFieldTransfer::setSolutionVectorValues(), MultiAppGeneralFieldTransfer::transferVariable(), and MultiAppShapeEvaluationTransfer::transferVariable().
_to_transforms
std::vector<std::unique_ptr<MultiAppCoordTransform> > MultiAppTransfer::_to_transforms protected inherited
Definition at line 146 of file MultiAppTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::cacheIncomingInterpVals(), MultiAppGeneralFieldTransfer::cacheOutgoingPointInfo(), MultiAppGeometricInterpolationTransfer::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), MultiAppTransfer::getAppInfo(), MultiAppTransfer::getPointInTargetAppFrame(), MultiAppGeneralFieldTransfer::locatePointReceivers(), MultiAppGeneralFieldTransfer::outputValueConflicts(), and MultiAppShapeEvaluationTransfer::transferVariable().
_to_var_components
const std::vector<unsigned int> MultiAppGeneralFieldTransfer::_to_var_components protected inherited
Target array/vector variable components.
Definition at line 194 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::getToVarName(), MultiAppGeneralFieldTransfer::initialSetup(), and MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer().
_to_var_name
AuxVariableName MultiAppConservativeTransfer::_to_var_name protected inherited
Definition at line 46 of file MultiAppConservativeTransfer.h.
Referenced by MultiAppConservativeTransfer::adjustTransferredSolution(), MultiAppConservativeTransfer::adjustTransferredSolutionNearestPoint(), MultiAppGeometricInterpolationTransfer::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppProjectionTransfer::initialSetup(), MultiAppGeometricInterpolationTransfer::interpolateTargetPoints(), and MultiAppProjectionTransfer::projectSolution().
_to_var_names
const std::vector<AuxVariableName> MultiAppConservativeTransfer::_to_var_names protected inherited
Name of variables transferring to.
Definition at line 42 of file MultiAppConservativeTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::getToVarName(), MultiAppConservativeTransfer::getToVarNames(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), and MultiAppShapeEvaluationTransfer::transferVariable().
_to_variables
std::vector<MooseVariableFieldBase *> MultiAppGeneralFieldTransfer::_to_variables private inherited
The target variables.
Definition at line 293 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::cacheIncomingInterpVals(), MultiAppGeneralFieldTransfer::examineLocalValueConflicts(), MultiAppGeneralFieldTransfer::examineReceivedValueConflicts(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), MultiAppGeneralFieldTransfer::initialSetup(), and MultiAppGeneralFieldTransfer::setSolutionVectorValues().
_type
const std::string& MooseBase::_type protected inherited
The type of this class.
Definition at line 63 of file MooseBase.h.
Referenced by FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), FEProblemBase::init(), FEProblemBase::solverTypeString(), and MooseBase::type().
_use_bounding_boxes
const bool MultiAppGeneralFieldTransfer::_use_bounding_boxes protected inherited
Whether to use bounding boxes to determine the applications that may receive point requests then send value data, and at other various checks.
Definition at line 198 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), MultiAppGeneralFieldTransfer::locatePointReceivers(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), prepareEvaluationOfInterpValues(), and MultiAppGeneralFieldUserObjectTransfer::prepareEvaluationOfInterpValues().
_use_nearest_app
const bool MultiAppGeneralFieldTransfer::_use_nearest_app protected inherited
Whether to keep track of the distance from the requested point to the app position.
Definition at line 201 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::cacheIncomingInterpVals(), and MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer().
_use_nearestpoint_pps
bool MultiAppConservativeTransfer::_use_nearestpoint_pps private inherited
Whether to use a nearest point UserObject to obtain the conservation factor.
Definition at line 68 of file MultiAppConservativeTransfer.h.
Referenced by MultiAppConservativeTransfer::initialSetup(), and MultiAppConservativeTransfer::postExecute().
_var_size
unsigned int MultiAppGeneralFieldTransfer::_var_size private inherited
The number of variables to transfer.
Definition at line 329 of file MultiAppGeneralFieldTransfer.h.
Referenced by MultiAppGeneralFieldTransfer::execute(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), and MultiAppGeneralFieldTransfer::transferVariable().
OutOfMeshValue
const Number Transfer::OutOfMeshValue = -999999 static inherited
Definition at line 113 of file Transfer.h.
Referenced by MultiAppProjectionTransfer::execute(), and MultiAppShapeEvaluationTransfer::transferVariable().
The documentation for this class was generated from the following files:
moose/framework/include/transfers/MultiAppGeneralFieldShapeEvaluationTransfer.h
moose/framework/src/transfers/MultiAppGeneralFieldShapeEvaluationTransfer.C