Zapdos: SpiralAnnularMesh Class Reference
SpiralAnnularMesh Class Reference
Mesh generated from parameters.
#include <SpiralAnnularMesh.h>
Public Types
enum class ParallelType { DEFAULT , REPLICATED , DISTRIBUTED }
using PeriodicNodeInfo = std::pair< const Node *, BoundaryID >
Helper type for building periodic node maps.
Public Member Functions
SpiralAnnularMesh (const InputParameters &parameters)
SpiralAnnularMesh (const SpiralAnnularMesh &)=default
SpiralAnnularMesh & operator= (const SpiralAnnularMesh &other_mesh)=delete
virtual std::unique_ptr< MooseMesh > safeClone () const override
A safer version of the clone() method that hands back an allocated object wrapped in a smart pointer.
virtual void buildMesh () override
Must be overridden by child classes.
virtual MooseMesh & clone () const
Clone method.
void determineUseDistributedMesh ()
Determine whether to use a distributed mesh.
std::unique_ptr< MeshBase > buildMeshBaseObject (unsigned int dim=libMesh::invalid_uint)
Method to construct a libMesh::MeshBase object that is normally set and used by the MooseMesh object during the "init()" phase.
template<typename T >
std::unique_ptr< T > buildTypedMesh (unsigned int dim=libMesh::invalid_uint)
Shortcut method to construct a unique pointer to a libMesh mesh instance.
void setMeshBase (std::unique_ptr< MeshBase > mesh_base)
Method to set the mesh_base object.
virtual void init ()
Initialize the Mesh object.
virtual unsigned int dimension () const
Returns MeshBase::mesh_dimension(), (not MeshBase::spatial_dimension()!) of the underlying libMesh mesh object.
virtual unsigned int effectiveSpatialDimension () const
Returns the effective spatial dimension determined by the coordinates actually used by the mesh.
unsigned int getBlocksMaxDimension (const std::vector< SubdomainName > &blocks) const
Returns the maximum element dimension on the given blocks.
std::vector< BoundaryID > getBoundaryIDs (const Elem *const elem, const unsigned short int side) const
Returns a vector of boundary IDs for the requested element on the requested side.
const std::set< BoundaryID > & getBoundaryIDs () const
Returns a const reference to a set of all user-specified boundary IDs.
std::vector< BoundaryID > getBoundaryIDs (const std::vector< BoundaryName > &boundary_name, bool generate_unknown=false) const
Get the associated BoundaryID for the boundary names that are passed in.
const Elem * getLowerDElem (const Elem *, unsigned short int) const
Returns a const pointer to a lower dimensional element that corresponds to a side of a higher dimensional element.
unsigned int getHigherDSide (const Elem *elem) const
Returns the local side ID of the interior parent aligned with the lower dimensional element.
void buildNodeList ()
Calls BoundaryInfo::build_node_list()/build_side_list() and makes separate copies of Nodes/Elems in those lists.
void buildBndElemList ()
const std::map< dof_id_type, std::vector< dof_id_type > > & nodeToElemMap ()
If not already created, creates a map from every node to all elements to which they are connected.
const std::map< dof_id_type, std::vector< dof_id_type > > & nodeToActiveSemilocalElemMap ()
If not already created, creates a map from every node to all active semilocal elements to which they are connected.
virtual bnd_node_iterator bndNodesBegin ()
Return iterators to the beginning/end of the boundary nodes list.
virtual bnd_node_iterator bndNodesEnd ()
virtual bnd_elem_iterator bndElemsBegin ()
Return iterators to the beginning/end of the boundary elements list.
virtual bnd_elem_iterator bndElemsEnd ()
void buildNodeListFromSideList ()
Calls BoundaryInfo::build_node_list_from_side_list().
void buildSideList (std::vector< dof_id_type > &el, std::vector< unsigned short int > &sl, std::vector< boundary_id_type > &il)
Calls BoundaryInfo::build_side_list().
std::vector< std::tuple< dof_id_type, unsigned short int, boundary_id_type > > buildSideList ()
As above, but uses the non-deprecated std::tuple interface.
std::vector< std::tuple< dof_id_type, unsigned short int, boundary_id_type > > buildActiveSideList () const
Calls BoundaryInfo::build_active_side_list.
unsigned int sideWithBoundaryID (const Elem *const elem, const BoundaryID boundary_id) const
Calls BoundaryInfo::side_with_boundary_id().
MeshBase::node_iterator localNodesBegin ()
Calls local_nodes_begin/end() on the underlying libMesh mesh object.
MeshBase::const_node_iterator localNodesBegin () const
MeshBase::node_iterator localNodesEnd ()
MeshBase::const_node_iterator localNodesEnd () const
MeshBase::element_iterator activeLocalElementsBegin ()
Calls active_local_nodes_begin/end() on the underlying libMesh mesh object.
MeshBase::const_element_iterator activeLocalElementsBegin () const
const MeshBase::element_iterator activeLocalElementsEnd ()
const MeshBase::const_element_iterator activeLocalElementsEnd () const
virtual dof_id_type nNodes () const
Calls n_nodes/elem() on the underlying libMesh mesh object.
virtual dof_id_type nElem () const
virtual dof_id_type maxNodeId () const
Calls max_node/elem_id() on the underlying libMesh mesh object.
virtual dof_id_type maxElemId () const
virtual const Node & node (const dof_id_type i) const
Various accessors (pointers/references) for Node "i".
virtual Node & node (const dof_id_type i)
virtual const Node & nodeRef (const dof_id_type i) const
virtual Node & nodeRef (const dof_id_type i)
virtual const Node * nodePtr (const dof_id_type i) const
virtual Node * nodePtr (const dof_id_type i)
virtual const Node * queryNodePtr (const dof_id_type i) const
virtual Node * queryNodePtr (const dof_id_type i)
virtual Elem * elem (const dof_id_type i)
Various accessors (pointers/references) for Elem "i".
virtual const Elem * elem (const dof_id_type i) const
virtual Elem * elemPtr (const dof_id_type i)
virtual const Elem * elemPtr (const dof_id_type i) const
virtual Elem * queryElemPtr (const dof_id_type i)
virtual const Elem * queryElemPtr (const dof_id_type i) const
bool prepared () const
Setter/getter for whether the mesh is prepared.
virtual void prepared (bool state)
void needsPrepareForUse ()
If this method is called, we will call libMesh's prepare_for_use method when we call Moose's prepare method.
void meshChanged ()
Declares that the MooseMesh has changed, invalidates cached data and rebuilds caches.
virtual void onMeshChanged ()
Declares a callback function that is executed at the conclusion of meshChanged().
void cacheChangedLists ()
Cache information about what elements were refined and coarsened in the previous step.
ConstElemPointerRange * refinedElementRange () const
Return a range that is suitable for threaded execution over elements that were just refined.
ConstElemPointerRange * coarsenedElementRange () const
Return a range that is suitable for threaded execution over elements that were just coarsened.
const std::vector< const Elem * > & coarsenedElementChildren (const Elem *elem) const
Get the newly removed children element ids for an element that was just coarsened.
void updateActiveSemiLocalNodeRange (std::set< dof_id_type > &ghosted_elems)
Clears the "semi-local" node list and rebuilds it.
bool isSemiLocal (Node *const node) const
Returns true if the node is semi-local.
const std::unordered_map< boundary_id_type, std::unordered_set< dof_id_type > > & getBoundariesToElems () const
Returns a map of boundaries to ids of elements on the boundary.
const std::unordered_map< boundary_id_type, std::unordered_set< dof_id_type > > & getBoundariesToActiveSemiLocalElemIds () const
Returns a map of boundaries to ids of elements on the boundary.
std::unordered_set< dof_id_type > getBoundaryActiveSemiLocalElemIds (BoundaryID bid) const
Return all ids of elements which have a side which is part of a sideset.
std::unordered_set< dof_id_type > getBoundaryActiveNeighborElemIds (BoundaryID bid) const
Return all ids of neighbors of elements which have a side which is part of a sideset.
bool isBoundaryFullyExternalToSubdomains (BoundaryID bid, const std::set< SubdomainID > &blk_group) const
Returns whether a boundary (given by its id) is not crossing through a group of blocks, by which we mean that elements on both sides of the boundary are in those blocks.
const std::set< SubdomainID > & meshSubdomains () const
Returns a read-only reference to the set of subdomains currently present in the Mesh.
const std::set< BoundaryID > & meshBoundaryIds () const
Returns a read-only reference to the set of boundary IDs currently present in the Mesh.
const std::set< BoundaryID > & meshSidesetIds () const
Returns a read-only reference to the set of sidesets currently present in the Mesh.
const std::set< BoundaryID > & meshNodesetIds () const
Returns a read-only reference to the set of nodesets currently present in the Mesh.
void setBoundaryToNormalMap (std::unique_ptr< std::map< BoundaryID, RealVectorValue > > boundary_map)
Sets the mapping between BoundaryID and normal vector Is called by AddAllSideSetsByNormals.
void setBoundaryToNormalMap (std::map< BoundaryID, RealVectorValue > *boundary_map)
void setMeshBoundaryIDs (std::set< BoundaryID > boundary_IDs)
Sets the set of BoundaryIDs Is called by AddAllSideSetsByNormals.
const RealVectorValue & getNormalByBoundaryID (BoundaryID id) const
Returns the normal vector associated with a given BoundaryID.
bool prepare (const MeshBase *mesh_to_clone)
Calls prepare_for_use() if the underlying MeshBase object isn't prepared, then communicates various boundary information on parallel meshes.
void update ()
Calls buildNodeListFromSideList(), buildNodeList(), and buildBndElemList().
unsigned int uniformRefineLevel () const
Returns the level of uniform refinement requested (zero if AMR is disabled).
void setUniformRefineLevel (unsigned int, bool deletion=true)
Set uniform refinement level.
bool skipDeletionRepartitionAfterRefine () const
Return a flag indicating whether or not we should skip remote deletion and repartition after uniform refinements.
bool skipRefineWhenUseSplit () const
Whether or not skip uniform refinements when using a pre-split mesh.
void addGhostedBoundary (BoundaryID boundary_id)
This will add the boundary ids to be ghosted to this processor.
void setGhostedBoundaryInflation (const std::vector< Real > &inflation)
This sets the inflation amount for the bounding box for each partition for use in ghosting boundaries.
const std::set< unsigned int > & getGhostedBoundaries () const
Return a writable reference to the set of ghosted boundary IDs.
const std::vector< Real > & getGhostedBoundaryInflation () const
Return a writable reference to the _ghosted_boundaries_inflation vector.
void ghostGhostedBoundaries ()
Actually do the ghosting of boundaries that need to be ghosted to this processor.
void needGhostGhostedBoundaries (bool needghost)
Whether or not we want to ghost ghosted boundaries.
unsigned int getPatchSize () const
Getter for the patch_size parameter.
unsigned int getGhostingPatchSize () const
Getter for the ghosting_patch_size parameter.
unsigned int getMaxLeafSize () const
Getter for the maximum leaf size parameter.
void setPatchUpdateStrategy (Moose::PatchUpdateType patch_update_strategy)
Set the patch size update strategy.
const Moose::PatchUpdateType & getPatchUpdateStrategy () const
Get the current patch update strategy.
BoundingBox getInflatedProcessorBoundingBox (Real inflation_multiplier=0.01) const
Get a (slightly inflated) processor bounding box.
operator libMesh::MeshBase & ()
Implicit conversion operator from MooseMesh -> libMesh::MeshBase.
operator const libMesh::MeshBase & () const
MeshBase & getMesh ()
Accessor for the underlying libMesh Mesh object.
MeshBase & getMesh (const std::string &name)
const MeshBase & getMesh () const
const MeshBase & getMesh (const std::string &name) const
const MeshBase * getMeshPtr () const
void printInfo (std::ostream &os=libMesh::out, const unsigned int verbosity=0) const
Calls print_info() on the underlying Mesh.
const std::set< SubdomainID > & getNodeBlockIds (const Node &node) const
Return list of blocks to which the given node belongs.
const std::vector< dof_id_type > & getNodeList (boundary_id_type nodeset_id) const
Return a writable reference to a vector of node IDs that belong to nodeset_id.
const Node * addUniqueNode (const Point &p, Real tol=1e-6)
Add a new node to the mesh.
Node * addQuadratureNode (const Elem *elem, const unsigned short int side, const unsigned int qp, BoundaryID bid, const Point &point)
Adds a fictitious "QuadratureNode".
Node * getQuadratureNode (const Elem *elem, const unsigned short int side, const unsigned int qp)
Get a specified quadrature node.
void clearQuadratureNodes ()
Clear out any existing quadrature nodes.
BoundaryID getBoundaryID (const BoundaryName &boundary_name) const
Get the associated BoundaryID for the boundary name.
SubdomainID getSubdomainID (const SubdomainName &subdomain_name) const
Get the associated subdomain ID for the subdomain name.
std::vector< SubdomainID > getSubdomainIDs (const std::vector< SubdomainName > &subdomain_name) const
Get the associated subdomainIDs for the subdomain names that are passed in.
void setSubdomainName (SubdomainID subdomain_id, const SubdomainName &name)
This method sets the name for subdomain_id to name.
const std::string & getSubdomainName (SubdomainID subdomain_id) const
Return the name of a block given an id.
std::vector< SubdomainName > getSubdomainNames (const std::vector< SubdomainID > &subdomain_ids) const
Get the associated subdomainNames for the subdomain ids that are passed in.
void setBoundaryName (BoundaryID boundary_id, BoundaryName name)
This method sets the boundary name of the boundary based on the id parameter.
const std::string & getBoundaryName (BoundaryID boundary_id)
Return the name of the boundary given the id.
void buildPeriodicNodeMap (std::multimap< dof_id_type, dof_id_type > &periodic_node_map, unsigned int var_number, PeriodicBoundaries *pbs) const
This routine builds a multimap of boundary ids to matching boundary ids across all periodic boundaries in the system.
void buildPeriodicNodeSets (std::map< BoundaryID, std::set< dof_id_type > > &periodic_node_sets, unsigned int var_number, PeriodicBoundaries *pbs) const
This routine builds a datastructure of node ids organized by periodic boundary ids.
Real dimensionWidth (unsigned int component) const
Returns the width of the requested dimension.
bool detectOrthogonalDimRanges (Real tol=1e-6)
This routine determines whether the Mesh is a regular orthogonal mesh (i.e.
void addPeriodicVariable (unsigned int var_num, BoundaryID primary, BoundaryID secondary)
For "regular orthogonal" meshes, determine if variable var_num is periodic with respect to the primary and secondary BoundaryIDs, record this fact in the _periodic_dim data structure.
bool isTranslatedPeriodic (unsigned int nonlinear_var_num, unsigned int component) const
Returns whether this generated mesh is periodic in the given dimension for the given variable.
RealVectorValue minPeriodicVector (unsigned int nonlinear_var_num, Point p, Point q) const
This function returns the minimum vector between two points on the mesh taking into account periodicity for the given variable number.
Real minPeriodicDistance (unsigned int nonlinear_var_num, Point p, Point q) const
This function returns the distance between two points on the mesh taking into account periodicity for the given variable number.
const std::pair< BoundaryID, BoundaryID > * getPairedBoundaryMapping (unsigned int component)
This function attempts to return the paired boundary ids for the given component.
void buildRefinementAndCoarseningMaps (Assembly *assembly)
Create the refinement and coarsening maps necessary for projection of stateful material properties when using adaptivity.
const std::vector< std::vector< QpMap > > & getRefinementMap (const Elem &elem, int parent_side, int child, int child_side)
Get the refinement map for a given element type.
const std::vector< std::pair< unsigned int, QpMap > > & getCoarseningMap (const Elem &elem, int input_side)
Get the coarsening map for a given element type.
void changeBoundaryId (const boundary_id_type old_id, const boundary_id_type new_id, bool delete_prev)
Change all the boundary IDs for a given side from old_id to new_id.
const std::set< BoundaryID > & getSubdomainBoundaryIds (const SubdomainID subdomain_id) const
Get the list of boundary ids associated with the given subdomain id.
std::set< BoundaryID > getSubdomainInterfaceBoundaryIds (const SubdomainID subdomain_id) const
Get the list of boundaries that contact the given subdomain.
std::set< SubdomainID > getBoundaryConnectedBlocks (const BoundaryID bid) const
Get the list of subdomains associated with the given boundary.
std::set< SubdomainID > getBoundaryConnectedSecondaryBlocks (const BoundaryID bid) const
Get the list of subdomains associated with the given boundary of its secondary side.
std::set< SubdomainID > getInterfaceConnectedBlocks (const BoundaryID bid) const
Get the list of subdomains contacting the given boundary.
const std::set< SubdomainID > & getBlockConnectedBlocks (const SubdomainID subdomain_id) const
Get the list of subdomains neighboring a given subdomain.
bool isBoundaryNode (dof_id_type node_id) const
Returns true if the requested node is in the list of boundary nodes, false otherwise.
bool isBoundaryNode (dof_id_type node_id, BoundaryID bnd_id) const
Returns true if the requested node is in the list of boundary nodes for the specified boundary, false otherwise.
bool isBoundaryElem (dof_id_type elem_id) const
Returns true if the requested element is in the list of boundary elements, false otherwise.
bool isBoundaryElem (dof_id_type elem_id, BoundaryID bnd_id) const
Returns true if the requested element is in the list of boundary elements for the specified boundary, false otherwise.
void errorIfDistributedMesh (std::string name) const
Generate a unified error message if the underlying libMesh mesh is a DistributedMesh.
bool isDistributedMesh () const
Returns the final Mesh distribution type.
bool isParallelTypeForced () const
Tell the user if the distribution was overriden for any reason.
void setParallelType (ParallelType parallel_type)
Allow to change parallel type.
const MooseEnum & partitionerName () const
bool isPartitionerForced () const
Tell the user if the partitioner was overriden for any reason.
void allowRecovery (bool allow)
Set whether or not this mesh is allowed to read a recovery file.
void setCustomPartitioner (Partitioner *partitioner)
Setter for custom partitioner.
bool isRegularOrthogonal ()
Getter to query if the mesh was detected to be regular and orthogonal.
bool hasSecondOrderElements ()
check if the mesh has SECOND order elements
virtual std::unique_ptr< PointLocatorBase > getPointLocator () const
Proxy function to get a (sub)PointLocator from either the underlying libMesh mesh (default), or to allow derived meshes to return a custom point locator.
virtual std::string getFileName () const
Returns the name of the mesh file read to produce this mesh if any or an empty string otherwise.
void needsRemoteElemDeletion (bool need_delete)
Set whether we need to delete remote elements.
bool needsRemoteElemDeletion () const
Whether we need to delete remote elements.
void allowRemoteElementRemoval (bool allow_removal)
Set whether to allow remote element removal.
bool allowRemoteElementRemoval () const
Whether we are allow remote element removal.
void deleteRemoteElements ()
Delete remote elements.
bool hasMeshBase () const
Whether mesh base object was constructed or not.
bool hasElementID (const std::string &id_name) const
Whether mesh has an extra element integer with a given name.
unsigned int getElementIDIndex (const std::string &id_name) const
Return the accessing integer for an extra element integer with its name.
dof_id_type maxElementID (unsigned int elem_id_index) const
Return the maximum element ID for an extra element integer with its accessing index.
dof_id_type minElementID (unsigned int elem_id_index) const
Return the minimum element ID for an extra element integer with its accessing index.
bool areElemIDsIdentical (const std::string &id_name1, const std::string &id_name2) const
Whether or not two extra element integers are identical.
std::set< dof_id_type > getAllElemIDs (unsigned int elem_id_index) const
Return all the unique element IDs for an extra element integer with its index.
std::set< dof_id_type > getElemIDsOnBlocks (unsigned int elem_id_index, const std::set< SubdomainID > &blks) const
Return all the unique element IDs for an extra element integer with its index on a set of subdomains.
std::unordered_map< dof_id_type, std::set< dof_id_type > > getElemIDMapping (const std::string &from_id_name, const std::string &to_id_name) const
void cacheFaceInfoVariableOwnership () const
Cache if variables live on the elements connected by the FaceInfo objects.
void cacheFVElementalDoFs () const
Cache the DoF indices for FV variables on each element.
void computeFiniteVolumeCoords () const
Compute the face coordinate value for all FaceInfo and ElemInfo objects.
void isDisplaced (bool is_displaced)
Set whether this mesh is displaced.
bool isDisplaced () const
whether this mesh is displaced
const std::map< boundary_id_type, std::vector< dof_id_type > > & nodeSetNodes () const
Moose::CoordinateSystemType getCoordSystem (SubdomainID sid) const
Get the coordinate system type, e.g.
const std::map< SubdomainID, Moose::CoordinateSystemType > & getCoordSystem () const
Get the map from subdomain ID to coordinate system type, e.g.
Moose::CoordinateSystemType getUniqueCoordSystem () const
Get the coordinate system from the mesh, it must be the same in all subdomains otherwise this will error.
void setCoordSystem (const std::vector< SubdomainName > &blocks, const MultiMooseEnum &coord_sys)
Set the coordinate system for the provided blocks to coord_sys.
void setAxisymmetricCoordAxis (const MooseEnum &rz_coord_axis)
For axisymmetric simulations, set the symmetry coordinate axis.
void setGeneralAxisymmetricCoordAxes (const std::vector< SubdomainName > &blocks, const std::vector< std::pair< Point, RealVectorValue > > &axes)
Sets the general coordinate axes for axisymmetric blocks.
const std::pair< Point, RealVectorValue > & getGeneralAxisymmetricCoordAxis (SubdomainID subdomain_id) const
Gets the general axisymmetric coordinate axis for a block.
bool usingGeneralAxisymmetricCoordAxes () const
Returns true if general axisymmetric coordinate axes are being used.
unsigned int getAxisymmetricRadialCoord () const
Returns the desired radial direction for RZ coordinate transformation.
void checkCoordinateSystems ()
Performs a sanity check for every element in the mesh.
void setCoordData (const MooseMesh &other_mesh)
Set the coordinate system data to that of other_mesh.
void markFiniteVolumeInfoDirty ()
Mark the finite volume information as dirty.
bool isFiniteVolumeInfoDirty () const
MooseAppCoordTransform & coordTransform ()
const MooseUnits & lengthUnit () const
const std::unordered_map< std::pair< const Elem *, unsigned short int >, const Elem * > & getLowerDElemMap () const
This function attempts to return the map from a high-order element side to its corresponding lower-d element.
bool isSplit () const
void buildFiniteVolumeInfo () const
Builds the face and elem info vectors that store meta-data needed for looping over and doing calculations based on mesh faces and elements in a finite volume setting.
void setupFiniteVolumeMeshData () const
Sets up the additional data needed for finite volume computations.
void doingPRefinement (bool doing_p_refinement)
Indicate whether the kind of adaptivity we're doing is p-refinement.
bool doingPRefinement () const
Query whether we have p-refinement.
const std::vector< QpMap > & getPRefinementMap (const Elem &elem) const
Get the map describing for each volumetric quadrature point (qp) on the refined level which qp on the previous coarser level the fine qp is closest to.
const std::vector< QpMap > & getPRefinementSideMap (const Elem &elem) const
Get the map describing for each side quadrature point (qp) on the refined level which qp on the previous coarser level the fine qp is closest to.
const std::vector< QpMap > & getPCoarseningMap (const Elem &elem) const
Get the map describing for each volumetric quadrature point (qp) on the coarse level which qp on the previous finer level the coarse qp is closest to.
const std::vector< QpMap > & getPCoarseningSideMap (const Elem &elem) const
Get the map describing for each side quadrature point (qp) on the coarse level which qp on the previous finer level the coarse qp is closest to.
void buildPRefinementAndCoarseningMaps (Assembly *assembly)
virtual bool enabled () const
Return the enabled status of the object.
MooseApp & getMooseApp () const
Get the MooseApp this class is associated with.
const std::string & type () const
Get the type of this class.
virtual const std::string & name () const
Get the name of the class.
std::string typeAndName () const
Get the class's combined type and name; useful in error handling.
MooseObjectParameterName uniqueParameterName (const std::string &parameter_name) const
The unique parameter name of a valid parameter of this object for accessing parameter controls.
const InputParameters & parameters () const
Get the parameters of the object.
MooseObjectName uniqueName () const
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
template<typename T >
const T & getParam (const std::string &name) const
Retrieve a parameter for the object.
template<typename T1 , typename T2 >
std::vector< std::pair< T1, T2 > > getParam (const std::string &param1, const std::string &param2) const
Retrieve two parameters and provide pair of parameters for the object.
template<typename T >
const T & getRenamedParam (const std::string &old_name, const std::string &new_name) const
Retrieve a renamed parameter for the object.
template<typename T >
T getCheckedPointerParam (const std::string &name, const std::string &error_string="") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
bool isParamValid (const std::string &name) const
Test if the supplied parameter is valid.
bool isParamSetByUser (const std::string &nm) const
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
template<typename... Args>
void paramError (const std::string &param, Args... args) const
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramWarning (const std::string &param, Args... args) const
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramInfo (const std::string &param, Args... args) const
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
std::string objectErrorPrefix (const std::string &error_type) const
A descriptive prefix for errors for an object.
void connectControllableParams (const std::string &parameter, const std::string &object_type, const std::string &object_name, const std::string &object_parameter) const
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
template<typename... Args>
void mooseError (Args &&... args) const
Emits an error prefixed with object name and type.
template<typename... Args>
void mooseErrorNonPrefixed (Args &&... args) const
Emits an error without the prefixing included in mooseError().
template<typename... Args>
void mooseWarning (Args &&... args) const
Emits a warning prefixed with object name and type.
template<typename... Args>
void mooseWarningNonPrefixed (Args &&... args) const
Emits a warning without the prefixing included in mooseWarning().
template<typename... Args>
void mooseDeprecated (Args &&... args) const
template<typename... Args>
void mooseInfo (Args &&... args) const
std::string errorPrefix (const std::string &error_type) const
A descriptive prefix for errors for this object:
std::string getDataFileName (const std::string &param) const
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
std::string getDataFileNameByName (const std::string &name, const std::string *param=nullptr) const
Returns the path of a data file for a given relative file path.
PerfGraph & perfGraph ()
Get the PerfGraph.
ConstElemRange * getActiveLocalElementRange ()
Return pointers to range objects for various types of ranges (local nodes, boundary elems, etc.).
NodeRange * getActiveNodeRange ()
SemiLocalNodeRange * getActiveSemiLocalNodeRange () const
ConstNodeRange * getLocalNodeRange ()
StoredRange< MooseMesh::const_bnd_node_iterator, const BndNode * > * getBoundaryNodeRange ()
StoredRange< MooseMesh::const_bnd_elem_iterator, const BndElement * > * getBoundaryElementRange ()
virtual Real getMinInDimension (unsigned int component) const
Returns the min or max of the requested dimension respectively.
virtual Real getMaxInDimension (unsigned int component) const
bool isCustomPartitionerRequested () const
Setter and getter for _custom_partitioner_requested.
void setIsCustomPartitionerRequested (bool cpr)
unsigned int nFace () const
accessors for the FaceInfo objects
const std::vector< const FaceInfo * > & faceInfo () const
Accessor for local FaceInfo objects.
const FaceInfo * faceInfo (const Elem *elem, unsigned int side) const
Accessor for the local FaceInfo object on the side of one element. Returns null if ghosted.
face_info_iterator ownedFaceInfoBegin ()
Iterators to owned faceInfo objects.
face_info_iterator ownedFaceInfoEnd ()
elem_info_iterator ownedElemInfoBegin ()
Iterators to owned faceInfo objects.
elem_info_iterator ownedElemInfoEnd ()
const ElemInfo & elemInfo (const dof_id_type id) const
Accessor for the elemInfo object for a given element ID.
const std::vector< const ElemInfo * > & elemInfoVector () const
Accessor for the element info objects owned by this process.
const std::vector< FaceInfo > & allFaceInfo () const
Accessor for all FaceInfo objects.
Static Public Member Functions
static InputParameters validParams ()
static MooseEnum partitioning ()
returns MooseMesh partitioning options so other classes can use it
static void setSubdomainName (MeshBase &mesh, SubdomainID subdomain_id, const SubdomainName &name)
This method sets the name for subdomain_id on the provided mesh to name.
static void changeBoundaryId (MeshBase &mesh, const boundary_id_type old_id, const boundary_id_type new_id, bool delete_prev)
Change all the boundary IDs for a given side from old_id to new_id for the given mesh.
static void setPartitioner (MeshBase &mesh_base, MooseEnum &partitioner, bool use_distributed_mesh, const InputParameters &params, MooseObject &context_obj)
Method for setting the partitioner on the passed in mesh_base object.
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Types
enum { X = 0 , Y , Z }
Convenience enums.
enum { MIN = 0 , MAX }
typedef std::vector< BndNode * >::iterator bnd_node_iterator_imp
typedef std::vector< BndNode * >::const_iterator const_bnd_node_iterator_imp
typedef std::vector< BndElement * >::iterator bnd_elem_iterator_imp
typedef std::vector< BndElement * >::const_iterator const_bnd_elem_iterator_imp
Protected Member Functions
void cacheInfo ()
void freeBndNodes ()
void freeBndElems ()
void setPartitionerHelper (MeshBase *mesh=nullptr)
template<typename T , typename... Args>
T & declareRestartableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
ManagedValue< T > declareManagedRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declares a piece of "managed" restartable data and initialize it.
template<typename T , typename... Args>
const T & getRestartableData (const std::string &data_name) const
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
template<typename T , typename... Args>
T & declareRestartableDataWithContext (const std::string &data_name, void *context, Args &&... args)
Declare a piece of data as "restartable" and initialize it.
template<typename T , typename... Args>
T & declareRecoverableData (const std::string &data_name, Args &&... args)
Declare a piece of data as "recoverable" and initialize it.
template<typename T , typename... Args>
T & declareRestartableDataWithObjectName (const std::string &data_name, const std::string &object_name, Args &&... args)
Declare a piece of data as "restartable".
template<typename T , typename... Args>
T & declareRestartableDataWithObjectNameWithContext (const std::string &data_name, const std::string &object_name, void *context, Args &&... args)
Declare a piece of data as "restartable".
std::string restartableName (const std::string &data_name) const
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level) const
Call to register a named section for timing.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level, const std::string &live_message, const bool print_dots=true) const
Call to register a named section for timing.
std::string timedSectionName (const std::string &section_name) const
Protected Attributes
const Real _inner_radius
Radius of the inner circle.
const Real _outer_radius
Radius of the outer circle. Logically, it's bigger that inner_radius.
Real _radial_bias
Factor to increase initial_delta_r for each ring.
const unsigned int _nodes_per_ring
Number of nodes on each ring.
const bool _use_tri6
Generate mesh of TRI6 elements instead of TRI3 elements.
unsigned int _num_rings
Number of rings.You can't specify both the number of rings and the radial bias if you want to match a specified outer radius exactly... you have to leave one of those parameters free so that it can be determined.
const boundary_id_type _cylinder_bid
The boundary id to use for the cylinder.
const boundary_id_type _exterior_bid
const Real _initial_delta_r
std::vector< std::unique_ptr< GhostingFunctor > > _ghosting_functors
Deprecated (DO NOT USE)
std::vector< std::shared_ptr< RelationshipManager > > _relationship_managers
The list of active geometric relationship managers (bound to the underlying MeshBase object).
bool _built_from_other_mesh = false
Whether or not this mesh was built from another mesh.
ParallelType _parallel_type
Can be set to DISTRIBUTED, REPLICATED, or DEFAULT.
bool _use_distributed_mesh
False by default.
bool _distribution_overridden
bool _parallel_type_overridden
std::unique_ptr< libMesh::MeshBase > _mesh
Pointer to underlying libMesh mesh object.
MooseEnum _partitioner_name
The partitioner used on this mesh.
bool _partitioner_overridden
std::unique_ptr< Partitioner > _custom_partitioner
The custom partitioner.
bool _custom_partitioner_requested
unsigned int _uniform_refine_level
The level of uniform refinement requested (set to zero if AMR is disabled)
bool _skip_refine_when_use_split
Whether or not to skip uniform refinements when using a pre-split mesh.
bool _skip_deletion_repartition_after_refine
Whether or not skip remote deletion and repartition after uniform refinements.
bool _is_changed
true if mesh is changed (i.e. after adaptivity step)
bool _is_nemesis
True if a Nemesis Mesh was read in.
bool _moose_mesh_prepared = false
True if prepare has been called on the mesh.
std::unique_ptr< ConstElemPointerRange > _refined_elements
The elements that were just refined.
std::unique_ptr< ConstElemPointerRange > _coarsened_elements
The elements that were just coarsened.
std::map< const Elem *, std::vector< const Elem * > > _coarsened_element_children
Map of Parent elements to child elements for elements that were just coarsened.
std::set< Node * > _semilocal_node_list
Used for generating the semilocal node range.
std::unique_ptr< ConstElemRange > _active_local_elem_range
A range for use with threading.
std::unique_ptr< SemiLocalNodeRange > _active_semilocal_node_range
std::unique_ptr< NodeRange > _active_node_range
std::unique_ptr< ConstNodeRange > _local_node_range
std::unique_ptr< StoredRange< MooseMesh::const_bnd_node_iterator, const BndNode * > > _bnd_node_range
std::unique_ptr< StoredRange< MooseMesh::const_bnd_elem_iterator, const BndElement * > > _bnd_elem_range
std::map< dof_id_type, std::vector< dof_id_type > > _node_to_elem_map
A map of all of the current nodes to the elements that they are connected to.
bool _node_to_elem_map_built
std::map< dof_id_type, std::vector< dof_id_type > > _node_to_active_semilocal_elem_map
A map of all of the current nodes to the active elements that they are connected to.
bool _node_to_active_semilocal_elem_map_built
std::set< SubdomainID > _mesh_subdomains
A set of subdomain IDs currently present in the mesh.
std::unique_ptr< std::map< BoundaryID, RealVectorValue > > _boundary_to_normal_map
The boundary to normal map - valid only when AddAllSideSetsByNormals is active.
std::vector< BndNode * > _bnd_nodes
array of boundary nodes
std::map< boundary_id_type, std::set< dof_id_type > > _bnd_node_ids
Map of sets of node IDs in each boundary.
std::vector< BndElement * > _bnd_elems
array of boundary elems
std::unordered_map< boundary_id_type, std::unordered_set< dof_id_type > > _bnd_elem_ids
Map of set of elem IDs connected to each boundary.
std::map< dof_id_type, Node * > _quadrature_nodes
std::map< dof_id_type, std::map< unsigned int, std::map< dof_id_type, Node * > > > _elem_to_side_to_qp_to_quadrature_nodes
std::vector< BndNode > _extra_bnd_nodes
std::map< dof_id_type, std::set< SubdomainID > > _block_node_list
list of nodes that belongs to a specified block (domain)
std::map< boundary_id_type, std::vector< dof_id_type > > _node_set_nodes
list of nodes that belongs to a specified nodeset: indexing [nodeset_id] -> [array of node ids]
std::set< unsigned int > _ghosted_boundaries
std::vector< Real > _ghosted_boundaries_inflation
unsigned int _patch_size
The number of nodes to consider in the NearestNode neighborhood.
unsigned int _ghosting_patch_size
The number of nearest neighbors to consider for ghosting purposes when iteration patch update strategy is used.
unsigned int _max_leaf_size
Moose::PatchUpdateType _patch_update_strategy
The patch update strategy.
std::vector< Node * > _node_map
Vector of all the Nodes in the mesh for determining when to add a new point.
bool _regular_orthogonal_mesh
Boolean indicating whether this mesh was detected to be regular and orthogonal.
std::vector< std::vector< Real > > _bounds
The bounds in each dimension of the mesh for regular orthogonal meshes.
std::vector< std::pair< BoundaryID, BoundaryID > > _paired_boundary
A vector holding the paired boundaries for a regular orthogonal mesh.
const bool _is_split
Whether or not we are using a (pre-)split mesh (automatically DistributedMesh)
const bool & _enabled
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
MooseApp & _app
The MOOSE application this is associated with.
const std::string & _type
The type of this class.
const std::string & _name
The name of this class, reference to value stored in InputParameters.
const InputParameters & _pars
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Factory & _factory
The Factory associated with the MooseApp.
ActionFactory & _action_factory
Builds Actions.
MooseApp & _restartable_app
Reference to the application.
const std::string _restartable_system_name
The system name this object is in.
const THREAD_ID _restartable_tid
The thread ID for this object.
const bool _restartable_read_only
Flag for toggling read only status (see ReporterData)
MooseApp & _pg_moose_app
The MooseApp that owns the PerfGraph.
const std::string _prefix
A prefix to use for all sections.
std::set< BoundaryID > _mesh_boundary_ids
A set of boundary IDs currently present in the mesh.
std::set< BoundaryID > _mesh_sideset_ids
std::set< BoundaryID > _mesh_nodeset_ids
Private Member Functions
void detectPairedSidesets ()
This routine detects paired sidesets of a regular orthogonal mesh (.i.e.
void buildRefinementMap (const Elem &elem, QBase &qrule, QBase &qrule_face, int parent_side, int child, int child_side)
Build the refinement map for a given element type.
void buildCoarseningMap (const Elem &elem, QBase &qrule, QBase &qrule_face, int input_side)
Build the coarsening map for a given element type.
void mapPoints (const std::vector< Point > &from, const std::vector< Point > &to, std::vector< QpMap > &qp_map)
Find the closest points that map "from" to "to" and fill up "qp_map".
void findAdaptivityQpMaps (const Elem *template_elem, QBase &qrule, QBase &qrule_face, std::vector< std::vector< QpMap > > &refinement_map, std::vector< std::pair< unsigned int, QpMap > > &coarsen_map, int parent_side, int child, int child_side)
Given an elem type, get maps that tell us what qp's are closest to each other between a parent and it's children.
void buildHRefinementAndCoarseningMaps (Assembly *assembly)
const std::vector< QpMap > & getPRefinementMapHelper (const Elem &elem, const std::map< std::pair< ElemType, unsigned int >, std::vector< QpMap > > &) const
const std::vector< QpMap > & getPCoarseningMapHelper (const Elem &elem, const std::map< std::pair< ElemType, unsigned int >, std::vector< QpMap > > &) const
void updateCoordTransform ()
Update the coordinate transformation object based on our coordinate system data.
void checkDuplicateSubdomainNames ()
Loop through all subdomain IDs and check if there is name duplication used for the subdomains with same ID.
void buildElemIDInfo ()
Build extra data for faster access to the information of extra element integers.
void buildLowerDMesh ()
Build lower-d mesh for all sides.
template<typename... Args>
std::string paramErrorMsg (const std::string &param, Args... args) const
RestartableDataValue & registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const
Helper function for actually registering the restartable data.
void registerRestartableNameWithFilterOnApp (const std::string &name, Moose::RESTARTABLE_FILTER filter)
Helper function for actually registering the restartable data.
template<typename T , typename... Args>
RestartableData< T > & declareRestartableDataHelper (const std::string &data_name, void *context, Args &&... args) const
Helper function for declaring restartable data.
Private Attributes
std::unordered_map< dof_id_type, ElemInfo > _elem_to_elem_info
Map connecting elems with their corresponding ElemInfo, we use the element ID as the key.
std::vector< const ElemInfo * > _elem_info
Holds only those ElemInfo objects that have processor_id equal to this process's id, e.g.
std::vector< FaceInfo > _all_face_info
FaceInfo object storing information for face based loops.
std::vector< const FaceInfo * > _face_info
Holds only those FaceInfo objects that have processor_id equal to this process's id, e.g.
std::unordered_map< std::pair< const Elem *, unsigned int >, FaceInfo * > _elem_side_to_face_info
Map from elem-side pair to FaceInfo.
bool _finite_volume_info_dirty = true
bool _linear_finite_volume_dofs_cached = false
std::map< unsigned int, std::vector< bool > > _periodic_dim
A map of vectors indicating which dimensions are periodic in a regular orthogonal mesh for the specified variable numbers.
RealVectorValue _half_range
A convenience vector used to hold values in each dimension representing half of the range.
std::vector< Node * > _extreme_nodes
A vector containing the nodes at the corners of a regular orthogonal mesh.
std::map< std::pair< int, ElemType >, std::vector< std::vector< QpMap > > > _elem_type_to_refinement_map
Holds mappings for volume to volume and parent side to child side Map key:
std::map< std::pair< ElemType, unsigned int >, std::vector< QpMap > > _elem_type_to_p_refinement_map
std::map< std::pair< ElemType, unsigned int >, std::vector< QpMap > > _elem_type_to_p_refinement_side_map
std::map< ElemType, std::map< std::pair< int, int >, std::vector< std::vector< QpMap > > > > _elem_type_to_child_side_refinement_map
Holds mappings for "internal" child sides to parent volume. The second key is (child, child_side).
std::map< std::pair< int, ElemType >, std::vector< std::pair< unsigned int, QpMap > > > _elem_type_to_coarsening_map
Holds mappings for volume to volume and parent side to child side Map key:
std::map< std::pair< ElemType, unsigned int >, std::vector< QpMap > > _elem_type_to_p_coarsening_map
std::map< std::pair< ElemType, unsigned int >, std::vector< QpMap > > _elem_type_to_p_coarsening_side_map
std::unordered_map< SubdomainID, std::set< SubdomainID > > _sub_to_neighbor_subs
Holds a map from subomdain ids to the neighboring subdomain ids.
std::unordered_map< SubdomainID, std::set< BoundaryID > > _subdomain_boundary_ids
Holds a map from subomdain ids to the boundary ids that are attached to it.
std::unordered_map< SubdomainID, std::set< BoundaryID > > _neighbor_subdomain_boundary_ids
Holds a map from neighbor subomdain ids to the boundary ids that are attached to it.
std::unordered_map< std::pair< const Elem *, unsigned short int >, const Elem * > _higher_d_elem_side_to_lower_d_elem
Holds a map from a high-order element side to its corresponding lower-d element.
std::unordered_map< const Elem *, unsigned short int > _lower_d_elem_to_higher_d_elem_side
bool _allow_recovery
Whether or not this Mesh is allowed to read a recovery file.
bool _construct_node_list_from_side_list
Whether or not to allow generation of nodesets from sidesets.
bool _need_delete
Whether we need to delete remote elements after init'ing the EquationSystems.
bool _allow_remote_element_removal
Whether to allow removal of remote elements.
std::set< Elem * > _ghost_elems_from_ghost_boundaries
Set of elements ghosted by ghostGhostedBoundaries.
bool _need_ghost_ghosted_boundaries
A parallel mesh generator such as DistributedRectilinearMeshGenerator already make everything ready.
std::vector< std::unordered_map< SubdomainID, std::set< dof_id_type > > > _block_id_mapping
Unique element integer IDs for each subdomain and each extra element integers.
std::vector< dof_id_type > _max_ids
Maximum integer ID for each extra element integer.
std::vector< dof_id_type > _min_ids
Minimum integer ID for each extra element integer.
std::vector< std::vector< bool > > _id_identical_flag
Flags to indicate whether or not any two extra element integers are the same.
bool _is_displaced
Whether this mesh is displaced.
std::map< SubdomainID, Moose::CoordinateSystemType > _coord_sys
Type of coordinate system per subdomain.
unsigned int _rz_coord_axis
Storage for RZ axis selection.
std::unordered_map< SubdomainID, std::pair< Point, RealVectorValue > > _subdomain_id_to_rz_coord_axis
Map of subdomain ID to general axisymmetric axis.
std::unique_ptr< MooseAppCoordTransform > _coord_transform
A coordinate transformation object that describes how to transform this problem's coordinate system into the canonical/reference coordinate system.
bool _coord_system_set
Whether the coordinate system has been set.
std::vector< SubdomainName > _provided_coord_blocks
Set for holding user-provided coordinate system type block names.
bool _doing_p_refinement
Whether we have p-refinement (as opposed to h-refinement)
const MooseBase *const _moose_base
The MooseBase object that inherits this class.
const MooseObject & _parent
const RestartableDataMapName _metaname
Restartable metadata name.
std::string _restartable_name
The name of the object.
Detailed Description
Mesh generated from parameters.
Definition at line 17 of file SpiralAnnularMesh.h.
Member Typedef Documentation
bnd_elem_iterator_imp
typedef std::vector<BndElement*>::iterator MooseMesh::bnd_elem_iterator_imp protected inherited
Definition at line 1481 of file MooseMesh.h.
bnd_node_iterator_imp
typedef std::vector<BndNode*>::iterator MooseMesh::bnd_node_iterator_imp protected inherited
Definition at line 1474 of file MooseMesh.h.
const_bnd_elem_iterator_imp
typedef std::vector<BndElement*>::const_iterator MooseMesh::const_bnd_elem_iterator_imp protected inherited
Definition at line 1482 of file MooseMesh.h.
const_bnd_node_iterator_imp
typedef std::vector<BndNode*>::const_iterator MooseMesh::const_bnd_node_iterator_imp protected inherited
Definition at line 1475 of file MooseMesh.h.
PeriodicNodeInfo
using MooseMesh::PeriodicNodeInfo = std::pair<const Node *, BoundaryID> inherited
Helper type for building periodic node maps.
Definition at line 1049 of file MooseMesh.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected inherited
Convenience enums.
Enumerator
X
Y
Z
Definition at line 1385 of file MooseMesh.h.
  {
    X = 0,
    Y,
    Z
  };
anonymous enum
anonymous enum protected inherited
Enumerator
MIN
MAX
Definition at line 1391 of file MooseMesh.h.
  {
    MIN = 0,
    MAX
  };
ParallelType
enum class MooseMesh::ParallelType strong inherited
Enumerator
DEFAULT
REPLICATED
DISTRIBUTED
Definition at line 104 of file MooseMesh.h.
  {
    DEFAULT,
    REPLICATED,
    DISTRIBUTED
  };
Constructor & Destructor Documentation
SpiralAnnularMesh() [1/2]
SpiralAnnularMesh::SpiralAnnularMesh (const InputParameters & parameters)
Definition at line 48 of file SpiralAnnularMesh.C.
  : MooseMesh(parameters),
    _inner_radius(getParam<Real>("inner_radius")),
    _outer_radius(getParam<Real>("outer_radius")),
    _radial_bias(1.0),
    _nodes_per_ring(getParam<unsigned int>("nodes_per_ring")),
    _use_tri6(getParam<bool>("use_tri6")),
    _num_rings(getParam<unsigned int>("num_rings")),
    _cylinder_bid(getParam<boundary_id_type>("cylinder_bid")),
    _exterior_bid(getParam<boundary_id_type>("exterior_bid")),
    _initial_delta_r(2 * libMesh::pi * _inner_radius / _nodes_per_ring)
{
  // catch likely user errors
  if (_outer_radius <= _inner_radius)
    mooseError("SpiralAnnularMesh: outer_radius must be greater than inner_radius");
}
SpiralAnnularMesh() [2/2]
SpiralAnnularMesh::SpiralAnnularMesh (const SpiralAnnularMesh &) default
Member Function Documentation
activeLocalElementsBegin() [1/2]
MeshBase::element_iterator MooseMesh::activeLocalElementsBegin () inherited
Calls active_local_nodes_begin/end() on the underlying libMesh mesh object.
Definition at line 2791 of file MooseMesh.C.
{
  return getMesh().active_local_elements_begin();
}
Referenced by FEProblemBase::checkDisplacementOrders(), MooseMesh::hasSecondOrderElements(), and TopResidualDebugOutput::printTopResiduals().
activeLocalElementsBegin() [2/2]
MeshBase::const_element_iterator MooseMesh::activeLocalElementsBegin () const inherited
Definition at line 2803 of file MooseMesh.C.
{
  return getMesh().active_local_elements_begin();
}
activeLocalElementsEnd() [1/2]
const MeshBase::element_iterator MooseMesh::activeLocalElementsEnd () inherited
Definition at line 2797 of file MooseMesh.C.
{
  return getMesh().active_local_elements_end();
}
Referenced by FEProblemBase::checkDisplacementOrders(), MooseMesh::hasSecondOrderElements(), and TopResidualDebugOutput::printTopResiduals().
activeLocalElementsEnd() [2/2]
const MeshBase::const_element_iterator MooseMesh::activeLocalElementsEnd () const inherited
Definition at line 2809 of file MooseMesh.C.
{
  return getMesh().active_local_elements_end();
}
addGhostedBoundary()
void MooseMesh::addGhostedBoundary (BoundaryID boundary_id) inherited
This will add the boundary ids to be ghosted to this processor.
Definition at line 2969 of file MooseMesh.C.
{
  _ghosted_boundaries.insert(boundary_id);
}
Referenced by FEProblemBase::addGhostedBoundary(), and SetupMeshAction::setupMesh().
addPeriodicVariable()
void MooseMesh::addPeriodicVariable (unsigned int var_num, BoundaryID primary, BoundaryID secondary) inherited
For "regular orthogonal" meshes, determine if variable var_num is periodic with respect to the primary and secondary BoundaryIDs, record this fact in the _periodic_dim data structure.
Definition at line 1963 of file MooseMesh.C.
{
  if (!_regular_orthogonal_mesh)
    return;
  _periodic_dim[var_num].resize(dimension());
  _half_range = Point(dimensionWidth(0) / 2.0, dimensionWidth(1) / 2.0, dimensionWidth(2) / 2.0);
  for (unsigned int component = 0; component < dimension(); ++component)
  {
    const std::pair<BoundaryID, BoundaryID> * boundary_ids = getPairedBoundaryMapping(component);
    if (boundary_ids != nullptr &&
        ((boundary_ids->first == primary && boundary_ids->second == secondary) ||
         (boundary_ids->first == secondary && boundary_ids->second == primary)))
      _periodic_dim[var_num][component] = true;
  }
}
Referenced by AddPeriodicBCAction::setPeriodicVars().
addQuadratureNode()
Node * MooseMesh::addQuadratureNode (const Elem * elem, const unsigned short int side, const unsigned int qp, BoundaryID bid, const Point & point) inherited
Adds a fictitious "QuadratureNode".
This doesn't actually add it to the libMesh mesh... we just keep track of these here in MooseMesh.
QuadratureNodes are fictitious "Nodes" that are located at quadrature points. This is useful for using the geometric search system to do searches based on quadrature point locations....
Parameters
elem The element
side The side number on which we want to add a quadrature node
qp The number of the quadrature point
bid The boundary ID for the point to be added with
point The physical location of the point
Definition at line 1382 of file MooseMesh.C.
{
  Node * qnode;
  if (_elem_to_side_to_qp_to_quadrature_nodes[elem->id()][side].find(qp) ==
      _elem_to_side_to_qp_to_quadrature_nodes[elem->id()][side].end())
  {
    // Create a new node id starting from the max node id and counting down.  This will be the least
    // likely to collide with an existing node id.
    // Note that we are using numeric_limits<unsigned>::max even
    // though max_id is stored as a dof_id_type.  I tried this with
    // numeric_limits<dof_id_type>::max and it broke several tests in
    // MOOSE.  So, this is some kind of a magic number that we will
    // just continue to use...
    dof_id_type max_id = std::numeric_limits<unsigned int>::max() - 100;
    dof_id_type new_id = max_id - _quadrature_nodes.size();
    if (new_id <= getMesh().max_node_id())
      mooseError("Quadrature node id collides with existing node id!");
    qnode = new Node(point, new_id);
    // Keep track of this new node in two different ways for easy lookup
    _quadrature_nodes[new_id] = qnode;
    _elem_to_side_to_qp_to_quadrature_nodes[elem->id()][side][qp] = qnode;
    if (elem->active())
    {
      _node_to_elem_map[new_id].push_back(elem->id());
      _node_to_active_semilocal_elem_map[new_id].push_back(elem->id());
    }
  }
  else
    qnode = _elem_to_side_to_qp_to_quadrature_nodes[elem->id()][side][qp];
  BndNode * bnode = new BndNode(qnode, bid);
  _bnd_nodes.push_back(bnode);
  _bnd_node_ids[bid].insert(qnode->id());
  _extra_bnd_nodes.push_back(*bnode);
  // Do this so the range will be regenerated next time it is accessed
  _bnd_node_range.reset();
  return qnode;
}
Referenced by GeometricSearchData::generateQuadratureNodes().
addUniqueNode()
const Node * MooseMesh::addUniqueNode (const Point & p, Real tol = 1e-6) inherited
Add a new node to the mesh.
If there is already a node located at the point passed then the node will not be added. In either case a reference to the node at that location will be returned
Looping through the mesh nodes each time we add a point is very slow. To speed things up we keep a local data structure
Definition at line 1348 of file MooseMesh.C.
{
  if (getMesh().n_nodes() != _node_map.size())
  {
    _node_map.clear();
    _node_map.reserve(getMesh().n_nodes());
    for (const auto & node : getMesh().node_ptr_range())
      _node_map.push_back(node);
  }
  Node * node = nullptr;
  for (unsigned int i = 0; i < _node_map.size(); ++i)
  {
    if (p.relative_fuzzy_equals(*_node_map[i], tol))
    {
      node = _node_map[i];
      break;
    }
  }
  if (node == nullptr)
  {
    node = getMesh().add_node(new Node(p));
    _node_map.push_back(node);
  }
  mooseAssert(node != nullptr, "Node is NULL");
  return node;
}
allFaceInfo()
const std::vector< FaceInfo > & MooseMesh::allFaceInfo () const inline inherited
Accessor for all FaceInfo objects.
Definition at line 2078 of file MooseMesh.h.
{
  return _all_face_info;
}
allowRecovery()
void MooseMesh::allowRecovery (bool allow) inline inherited
Set whether or not this mesh is allowed to read a recovery file.
Definition at line 1006 of file MooseMesh.h.
{ _allow_recovery = allow; }
allowRemoteElementRemoval() [1/2]
bool MooseMesh::allowRemoteElementRemoval () const inline inherited
Whether we are allow remote element removal.
Definition at line 1069 of file MooseMesh.h.
{ return _allow_remote_element_removal; }
Referenced by MooseMesh::MooseMesh().
allowRemoteElementRemoval() [2/2]
void MooseMesh::allowRemoteElementRemoval (bool allow_removal) inherited
Set whether to allow remote element removal.
Definition at line 3645 of file MooseMesh.C.
{
  _allow_remote_element_removal = allow_remote_element_removal;
  if (_mesh)
    _mesh->allow_remote_element_removal(allow_remote_element_removal);
  if (!allow_remote_element_removal)
    // If we're not allowing remote element removal now, then we will need deletion later after
    // late geoemetric ghosting functors have been added (late geometric ghosting functor addition
    // happens when algebraic ghosting functors are added)
    _need_delete = true;
}
Referenced by MooseApp::attachRelationshipManagers().
areElemIDsIdentical()
bool MooseMesh::areElemIDsIdentical (const std::string & id_name1, const std::string & id_name2) const inline inherited
Whether or not two extra element integers are identical.
Definition at line 2064 of file MooseMesh.h.
{
  auto id1 = getElementIDIndex(id_name1);
  auto id2 = getElementIDIndex(id_name2);
  return _id_identical_flag[id1][id2];
}
bndElemsBegin()
MooseMesh::bnd_elem_iterator MooseMesh::bndElemsBegin () virtual inherited
Return iterators to the beginning/end of the boundary elements list.
Definition at line 1333 of file MooseMesh.C.
{
  Predicates::NotNull<bnd_elem_iterator_imp> p;
  return bnd_elem_iterator(_bnd_elems.begin(), _bnd_elems.end(), p);
}
Referenced by MooseMesh::getBoundaryElementRange(), and MeshInfo::possiblyAddSidesetInfo().
bndElemsEnd()
MooseMesh::bnd_elem_iterator MooseMesh::bndElemsEnd () virtual inherited
Definition at line 1341 of file MooseMesh.C.
{
  Predicates::NotNull<bnd_elem_iterator_imp> p;
  return bnd_elem_iterator(_bnd_elems.end(), _bnd_elems.end(), p);
}
Referenced by MooseMesh::getBoundaryElementRange(), and MeshInfo::possiblyAddSidesetInfo().
bndNodesBegin()
MooseMesh::bnd_node_iterator MooseMesh::bndNodesBegin () virtual inherited
Return iterators to the beginning/end of the boundary nodes list.
Definition at line 1317 of file MooseMesh.C.
{
  Predicates::NotNull<bnd_node_iterator_imp> p;
  return bnd_node_iterator(_bnd_nodes.begin(), _bnd_nodes.end(), p);
}
Referenced by MooseMesh::getBoundaryNodeRange().
bndNodesEnd()
MooseMesh::bnd_node_iterator MooseMesh::bndNodesEnd () virtual inherited
Definition at line 1325 of file MooseMesh.C.
{
  Predicates::NotNull<bnd_node_iterator_imp> p;
  return bnd_node_iterator(_bnd_nodes.end(), _bnd_nodes.end(), p);
}
Referenced by MooseMesh::getBoundaryNodeRange().
buildActiveSideList()
std::vector< std::tuple< dof_id_type, unsigned short int, boundary_id_type > > MooseMesh::buildActiveSideList () const inherited
Calls BoundaryInfo::build_active_side_list.
Returns
A container of active (element, side, id) tuples.
Definition at line 2755 of file MooseMesh.C.
{
  return getMesh().get_boundary_info().build_active_side_list();
}
Referenced by MooseMesh::buildFiniteVolumeInfo(), and PenetrationLocator::detectPenetration().
buildBndElemList()
void MooseMesh::buildBndElemList () inherited
Definition at line 952 of file MooseMesh.C.
{
  TIME_SECTION("buildBndElemList", 5, "Building Boundary Elements List");
  freeBndElems();
  auto bc_tuples = getMesh().get_boundary_info().build_active_side_list();
  int n = bc_tuples.size();
  _bnd_elems.clear();
  _bnd_elems.reserve(n);
  for (const auto & t : bc_tuples)
  {
    auto elem_id = std::get<0>(t);
    auto side_id = std::get<1>(t);
    auto bc_id = std::get<2>(t);
    _bnd_elems.push_back(new BndElement(getMesh().elem_ptr(elem_id), side_id, bc_id));
    _bnd_elem_ids[bc_id].insert(elem_id);
  }
}
Referenced by MooseMesh::update().
buildCoarseningMap()
void MooseMesh::buildCoarseningMap (const Elem & elem, QBase & qrule, QBase & qrule_face, int input_side) private inherited
Build the coarsening map for a given element type.
This will tell you what quadrature points to copy from and to for stateful material properties on newly created elements from Adaptivity.
Parameters
elem The element that represents the element type you need the coarsening map for.
qrule The quadrature rule in use.
qrule_face The current face quadrature rule
input_side The side to map
TODO: When running with parallel mesh + stateful adaptivty we will need to make sure that each processor has a complete map. This may require parallel communication. This is likely to happen when running on a mixed element mesh.
Definition at line 2288 of file MooseMesh.C.
{
  TIME_SECTION("buildCoarseningMap", 5, "Building Coarsening Map");
  std::pair<int, ElemType> the_pair(input_side, elem.type());
  if (_elem_type_to_coarsening_map.find(the_pair) != _elem_type_to_coarsening_map.end())
    mooseError("Already built a qp coarsening map!");
  std::vector<std::vector<QpMap>> refinement_map;
  std::vector<std::pair<unsigned int, QpMap>> & coarsen_map =
      _elem_type_to_coarsening_map[the_pair];
  // The -1 here is for a specific child.  We don't do that for coarsening maps
  // Also note that we're always mapping the same side to the same side (which is guaranteed by
  // libMesh).
  findAdaptivityQpMaps(
      &elem, qrule, qrule_face, refinement_map, coarsen_map, input_side, -1, input_side);
}
Referenced by MooseMesh::buildHRefinementAndCoarseningMaps().
buildElemIDInfo()
void MooseMesh::buildElemIDInfo () private inherited
Build extra data for faster access to the information of extra element integers.
Definition at line 856 of file MooseMesh.C.
{
  unsigned int n = getMesh().n_elem_integers() + 1;
  _block_id_mapping.clear();
  _max_ids.clear();
  _min_ids.clear();
  _id_identical_flag.clear();
  _block_id_mapping.resize(n);
  _max_ids.resize(n, std::numeric_limits<dof_id_type>::min());
  _min_ids.resize(n, std::numeric_limits<dof_id_type>::max());
  _id_identical_flag.resize(n, std::vector<bool>(n, true));
  for (const auto & elem : getMesh().active_local_element_ptr_range())
    for (unsigned int i = 0; i < n; ++i)
    {
      auto id = (i == n - 1 ? elem->subdomain_id() : elem->get_extra_integer(i));
      _block_id_mapping[i][elem->subdomain_id()].insert(id);
      if (id > _max_ids[i])
        _max_ids[i] = id;
      if (id < _min_ids[i])
        _min_ids[i] = id;
      for (unsigned int j = 0; j < n; ++j)
      {
        auto idj = (j == n - 1 ? elem->subdomain_id() : elem->get_extra_integer(j));
        if (i != j && _id_identical_flag[i][j] && id != idj)
          _id_identical_flag[i][j] = false;
      }
    }
  for (unsigned int i = 0; i < n; ++i)
  {
    for (auto & blk : meshSubdomains())
      comm().set_union(_block_id_mapping[i][blk]);
    comm().min(_id_identical_flag[i]);
  }
  comm().max(_max_ids);
  comm().min(_min_ids);
}
Referenced by MooseMesh::update().
buildFiniteVolumeInfo()
void MooseMesh::buildFiniteVolumeInfo () const inherited
Builds the face and elem info vectors that store meta-data needed for looping over and doing calculations based on mesh faces and elements in a finite volume setting.
This should only be called when finite volume variables are used in the problem or when the face and elem info objects are necessary for functor-based evaluations.
Definition at line 3476 of file MooseMesh.C.
{
  mooseAssert(!Threads::in_threads,
              "This routine has not been implemented for threads. Please query this routine before "
              "a threaded region or contact a MOOSE developer to discuss.");
  _finite_volume_info_dirty = false;
  using Keytype = std::pair<const Elem *, unsigned short int>;
  // create a map from elem/side --> boundary ids
  std::vector<std::tuple<dof_id_type, unsigned short int, boundary_id_type>> side_list =
      buildActiveSideList();
  std::map<Keytype, std::set<boundary_id_type>> side_map;
  for (auto & [elem_id, side, bc_id] : side_list)
  {
    const Elem * elem = _mesh->elem_ptr(elem_id);
    Keytype key(elem, side);
    auto & bc_set = side_map[key];
    bc_set.insert(bc_id);
  }
  _face_info.clear();
  _all_face_info.clear();
  _elem_side_to_face_info.clear();
  _elem_to_elem_info.clear();
  _elem_info.clear();
  // by performing the element ID comparison check in the below loop, we are ensuring that we never
  // double count face contributions. If a face lies along a process boundary, the only process that
  // will contribute to both sides of the face residuals/Jacobians will be the process that owns the
  // element with the lower ID.
  auto begin = getMesh().active_elements_begin();
  auto end = getMesh().active_elements_end();
  // We prepare a map connecting the Elem* and the corresponding ElemInfo
  // for the active elements.
  for (const Elem * elem : as_range(begin, end))
    _elem_to_elem_info.emplace(elem->id(), elem);
  _linear_finite_volume_dofs_cached = false;
  dof_id_type face_index = 0;
  for (const Elem * elem : as_range(begin, end))
  {
    for (unsigned int side = 0; side < elem->n_sides(); ++side)
    {
      // get the neighbor element
      const Elem * neighbor = elem->neighbor_ptr(side);
      // Check if the FaceInfo shall belong to the element. If yes,
      // create and initialize the FaceInfo. We need this to ensure that
      // we do not duplicate FaceInfo-s.
      if (Moose::FV::elemHasFaceInfo(*elem, neighbor))
      {
        mooseAssert(!neighbor || (neighbor->level() < elem->level() ? neighbor->active() : true),
                    "If the neighbor is coarser than the element, we expect that the neighbor must "
                    "be active.");
        // We construct the faceInfo using the elementinfo and side index
        _all_face_info.emplace_back(&_elem_to_elem_info[elem->id()], side, face_index++);
        auto & fi = _all_face_info.back();
        // get all the sidesets that this face is contained in and cache them
        // in the face info.
        std::set<boundary_id_type> & boundary_ids = fi.boundaryIDs();
        boundary_ids.clear();
        // We initialize the weights/other information in faceInfo. If the neighbor does not exist
        // or is remote (so when we are on some sort of mesh boundary), we initialize the ghost
        // cell and use it to compute the weights corresponding to the faceInfo.
        if (!neighbor || neighbor == remote_elem)
          fi.computeBoundaryCoefficients();
        else
          fi.computeInternalCoefficients(&_elem_to_elem_info[neighbor->id()]);
        auto lit = side_map.find(Keytype(&fi.elem(), fi.elemSideID()));
        if (lit != side_map.end())
          boundary_ids.insert(lit->second.begin(), lit->second.end());
        if (fi.neighborPtr())
        {
          auto rit = side_map.find(Keytype(fi.neighborPtr(), fi.neighborSideID()));
          if (rit != side_map.end())
            boundary_ids.insert(rit->second.begin(), rit->second.end());
        }
      }
    }
  }
  // Build the local face info and elem_side to face info maps. We need to do this after
  // _all_face_info is finished being constructed because emplace_back invalidates all iterators and
  // references if ever the new size exceeds capacity
  for (auto & fi : _all_face_info)
  {
    const Elem * const elem = &fi.elem();
    const auto side = fi.elemSideID();
#ifndef NDEBUG
    auto pair_it =
#endif
        _elem_side_to_face_info.emplace(std::make_pair(elem, side), &fi);
    mooseAssert(pair_it.second, "We should be adding unique FaceInfo objects.");
    // We will add the faces on processor boundaries to the list of face infos on each
    // associated processor.
    if (fi.elem().processor_id() == this->processor_id() ||
        (fi.neighborPtr() && (fi.neighborPtr()->processor_id() == this->processor_id())))
      _face_info.push_back(&fi);
  }
  for (auto & ei : _elem_to_elem_info)
    if (ei.second.elem()->processor_id() == this->processor_id())
      _elem_info.push_back(&ei.second);
}
Referenced by MooseMesh::setupFiniteVolumeMeshData().
buildHRefinementAndCoarseningMaps()
void MooseMesh::buildHRefinementAndCoarseningMaps (Assembly * assembly) private inherited
Definition at line 2044 of file MooseMesh.C.
{
  std::map<ElemType, Elem *> canonical_elems;
  // First, loop over all elements and find a canonical element for each type
  // Doing it this way guarantees that this is going to work in parallel
  for (const auto & elem : getMesh().element_ptr_range()) // TODO: Thread this
  {
    ElemType type = elem->type();
    if (canonical_elems.find(type) ==
        canonical_elems.end()) // If we haven't seen this type of elem before save it
      canonical_elems[type] = elem;
    else
    {
      Elem * stored = canonical_elems[type];
      if (elem->id() < stored->id()) // Arbitrarily keep the one with a lower id
        canonical_elems[type] = elem;
    }
  }
  // Now build the maps using these templates
  // Note: This MUST be done NOT threaded!
  for (const auto & can_it : canonical_elems)
  {
    Elem * elem = can_it.second;
    // Need to do this just once to get the right qrules put in place
    assembly->setCurrentSubdomainID(elem->subdomain_id());
    assembly->reinit(elem);
    assembly->reinit(elem, 0);
    auto && qrule = assembly->writeableQRule();
    auto && qrule_face = assembly->writeableQRuleFace();
    // Volume to volume projection for refinement
    buildRefinementMap(*elem, *qrule, *qrule_face, -1, -1, -1);
    // Volume to volume projection for coarsening
    buildCoarseningMap(*elem, *qrule, *qrule_face, -1);
    // Map the sides of children
    for (unsigned int side = 0; side < elem->n_sides(); side++)
    {
      // Side to side for sides that match parent's sides
      buildRefinementMap(*elem, *qrule, *qrule_face, side, -1, side);
      buildCoarseningMap(*elem, *qrule, *qrule_face, side);
    }
    // Child side to parent volume mapping for "internal" child sides
    for (unsigned int child = 0; child < elem->n_children(); ++child)
      for (unsigned int side = 0; side < elem->n_sides();
           ++side)                                // Assume children have the same number of sides!
        if (!elem->is_child_on_side(child, side)) // Otherwise we already computed that map
          buildRefinementMap(*elem, *qrule, *qrule_face, -1, child, side);
  }
}
Referenced by MooseMesh::buildRefinementAndCoarseningMaps().
buildLowerDMesh()
void MooseMesh::buildLowerDMesh () private inherited
Build lower-d mesh for all sides.
Definition at line 502 of file MooseMesh.C.
{
  auto & mesh = getMesh();
  if (!mesh.is_serial())
    mooseError(
        "Hybrid finite element method must use replicated mesh.\nCurrently lower-dimensional mesh "
        "does not support mesh re-partitioning and a debug assertion being hit related with "
        "neighbors of lower-dimensional element, with distributed mesh.");
  // Lower-D element build requires neighboring element information
  if (!mesh.is_prepared())
    mesh.find_neighbors();
  // maximum number of sides of all elements
  unsigned int max_n_sides = 0;
  // remove existing lower-d element first
  std::set<Elem *> deleteable_elems;
  for (auto & elem : mesh.element_ptr_range())
    if (elem->subdomain_id() == Moose::INTERNAL_SIDE_LOWERD_ID ||
        elem->subdomain_id() == Moose::BOUNDARY_SIDE_LOWERD_ID)
      deleteable_elems.insert(elem);
    else if (elem->n_sides() > max_n_sides)
      max_n_sides = elem->n_sides();
  for (auto & elem : deleteable_elems)
    mesh.delete_elem(elem);
  mesh.comm().max(max_n_sides);
  deleteable_elems.clear();
  dof_id_type max_elem_id = mesh.max_elem_id();
  unique_id_type max_unique_id = mesh.parallel_max_unique_id();
  std::vector<Elem *> side_elems;
  _higher_d_elem_side_to_lower_d_elem.clear();
  for (const auto & elem : mesh.active_element_ptr_range())
  {
    // skip existing lower-d elements
    if (elem->interior_parent())
      continue;
    for (const auto side : elem->side_index_range())
    {
      Elem * neig = elem->neighbor_ptr(side);
      bool build_side = false;
      if (!neig)
        build_side = true;
      else
      {
        mooseAssert(!neig->is_remote(), "We error if the mesh is not serial");
        if (!neig->active())
          build_side = true;
        else if (neig->level() == elem->level() && elem->id() < neig->id())
          build_side = true;
      }
      if (build_side)
      {
        std::unique_ptr<Elem> side_elem(elem->build_side_ptr(side, false));
        // The side will be added with the same processor id as the parent.
        side_elem->processor_id() = elem->processor_id();
        // Add subdomain ID
        if (neig)
          side_elem->subdomain_id() = Moose::INTERNAL_SIDE_LOWERD_ID;
        else
          side_elem->subdomain_id() = Moose::BOUNDARY_SIDE_LOWERD_ID;
        // set ids consistently across processors (these ids will be temporary)
        side_elem->set_id(max_elem_id + elem->id() * max_n_sides + side);
        side_elem->set_unique_id(max_unique_id + elem->id() * max_n_sides + side);
        // Also assign the side's interior parent, so it is always
        // easy to figure out the Elem we came from.
        // Note: the interior parent could be a ghost element.
        side_elem->set_interior_parent(elem);
        side_elems.push_back(side_elem.release());
        // add link between higher d element to lower d element
        auto pair = std::make_pair(elem, side);
        auto link = std::make_pair(pair, side_elems.back());
        auto ilink = std::make_pair(side_elems.back(), side);
        _lower_d_elem_to_higher_d_elem_side.insert(ilink);
        _higher_d_elem_side_to_lower_d_elem.insert(link);
      }
    }
  }
  // finally, add the lower-dimensional element to the mesh
  // Note: lower-d interior element will exist on a processor if its associated interior
  //       parent exists on a processor whether or not being a ghost. Lower-d elements will
  //       get its interior parent's processor id.
  for (auto & elem : side_elems)
    mesh.add_elem(elem);
  _mesh_subdomains.insert(Moose::INTERNAL_SIDE_LOWERD_ID);
  mesh.subdomain_name(Moose::INTERNAL_SIDE_LOWERD_ID) = "INTERNAL_SIDE_LOWERD_SUBDOMAIN";
  _mesh_subdomains.insert(Moose::BOUNDARY_SIDE_LOWERD_ID);
  mesh.subdomain_name(Moose::BOUNDARY_SIDE_LOWERD_ID) = "BOUNDARY_SIDE_LOWERD_SUBDOMAIN";
  // we do all the stuff in prepare_for_use such as renumber_nodes_and_elements(),
  // update_parallel_id_counts(), cache_elem_dims(), etc. except partitioning here.
  const bool skip_partitioning_old = mesh.skip_partitioning();
  mesh.skip_partitioning(true);
  mesh.prepare_for_use();
  mesh.skip_partitioning(skip_partitioning_old);
}
Referenced by MooseMesh::init().
buildMesh()
void SpiralAnnularMesh::buildMesh () override virtual
Must be overridden by child classes.
This is where the Mesh object is actually created and filled in.
Implements MooseMesh.
Definition at line 72 of file SpiralAnnularMesh.C.
{
  {
    // Compute the radial bias given:
    // .) the inner radius
    // .) the outer radius
    // .) the initial_delta_r
    // .) the desired number of intervals
    // Note: the exponent n used in the formula is one less than the
    // number of rings the user requests.
    Real alpha = 1.1;
    int n = _num_rings - 1;
    // lambda used to compute the residual and Jacobian for the Newton iterations.
    // We capture parameters which don't need to change from the current scope at
    // the time this lambda is declared. The values are not updated later, so we
    // can't use this for e.g. f, df, and alpha.
    auto newton = [this, n](Real & f, Real & df, const Real & alpha)
    {
      f = (1. - std::pow(alpha, n + 1)) / (1. - alpha) -
          (_outer_radius - _inner_radius) / _initial_delta_r;
      df = (-(n + 1) * (1 - alpha) * std::pow(alpha, n) + (1. - std::pow(alpha, n + 1))) /
           (1. - alpha) / (1. - alpha);
    };
    Real f, df;
    int num_iter = 1;
    newton(f, df, alpha);
    while (std::abs(f) > 1.e-9 && num_iter <= 25)
    {
      // Compute and apply update.
      Real dx = -f / df;
      alpha += dx;
      newton(f, df, alpha);
      num_iter++;
    }
    // In case the Newton iteration fails to converge.
    if (num_iter > 25)
      mooseError("Newton iteration failed to converge (more than 25 iterations).");
    // Set radial basis to the value of alpha that we computed with Newton.
    _radial_bias = alpha;
  }
  // The number of rings specified by the user does not include the ring at
  // the surface of the cylinder itself, so we increment it by one now.
  _num_rings += 1;
  // Mesh we are eventually going to create.
  MeshBase & mesh = getMesh();
  BoundaryInfo & boundary_info = mesh.get_boundary_info();
  // Data structure that holds pointers to the Nodes of each ring.
  std::vector<std::vector<Node *>> ring_nodes(_num_rings);
  // Initialize radius and delta_r variables.
  Real radius = _inner_radius;
  Real delta_r = _initial_delta_r;
  // Node id counter.
  unsigned int current_node_id = 0;
  for (std::size_t r = 0; r < _num_rings; ++r)
  {
    ring_nodes[r].resize(_nodes_per_ring);
    // Add nodes starting from either theta=0 or theta=pi/nodes_per_ring
    Real theta = r % 2 == 0 ? 0 : (libMesh::pi / _nodes_per_ring);
    for (std::size_t n = 0; n < _nodes_per_ring; ++n)
    {
      ring_nodes[r][n] = mesh.add_point(Point(radius * std::cos(theta), radius * std::sin(theta)),
                                        current_node_id++);
      // Update angle
      theta += 2 * libMesh::pi / _nodes_per_ring;
    }
    // Go to next ring
    radius += delta_r;
    delta_r *= _radial_bias;
  }
  // Add elements
  for (std::size_t r = 0; r < _num_rings - 1; ++r)
  {
    // even -> odd ring
    if (r % 2 == 0)
    {
      // Inner ring (n, n*, n+1)
      // Starred indices refer to nodes on the "outer" ring of this pair.
      for (std::size_t n = 0; n < _nodes_per_ring; ++n)
      {
        // Wrap around
        unsigned int np1 = (n == _nodes_per_ring - 1) ? 0 : n + 1;
        Elem * elem = mesh.add_elem(new Tri3);
        elem->set_node(0) = ring_nodes[r][n];
        elem->set_node(1) = ring_nodes[r + 1][n];
        elem->set_node(2) = ring_nodes[r][np1];
        // Add interior faces to 'cylinder' sideset if we are on ring 0.
        if (r == 0)
          boundary_info.add_side(elem->id(), /*side=*/2, _cylinder_bid);
      }
      // Outer ring (n*, n+1*, n+1)
      for (std::size_t n = 0; n < _nodes_per_ring; ++n)
      {
        // Wrap around
        unsigned int np1 = (n == _nodes_per_ring - 1) ? 0 : n + 1;
        Elem * elem = mesh.add_elem(new Tri3);
        elem->set_node(0) = ring_nodes[r + 1][n];
        elem->set_node(1) = ring_nodes[r + 1][np1];
        elem->set_node(2) = ring_nodes[r][np1];
        // Add exterior faces to 'exterior' sideset if we're on the last ring.
        // Note: this code appears in two places since we could end on either an even or odd ring.
        if (r == _num_rings - 2)
          boundary_info.add_side(elem->id(), /*side=*/0, _exterior_bid);
      }
    }
    else
    {
      // odd -> even ring
      // Inner ring (n, n+1*, n+1)
      for (std::size_t n = 0; n < _nodes_per_ring; ++n)
      {
        // Wrap around
        unsigned int np1 = (n == _nodes_per_ring - 1) ? 0 : n + 1;
        Elem * elem = mesh.add_elem(new Tri3);
        elem->set_node(0) = ring_nodes[r][n];
        elem->set_node(1) = ring_nodes[r + 1][np1];
        elem->set_node(2) = ring_nodes[r][np1];
      }
      // Outer ring (n*, n+1*, n)
      for (std::size_t n = 0; n < _nodes_per_ring; ++n)
      {
        // Wrap around
        unsigned int np1 = (n == _nodes_per_ring - 1) ? 0 : n + 1;
        Elem * elem = mesh.add_elem(new Tri3);
        elem->set_node(0) = ring_nodes[r + 1][n];
        elem->set_node(1) = ring_nodes[r + 1][np1];
        elem->set_node(2) = ring_nodes[r][n];
        // Add exterior faces to 'exterior' sideset if we're on the last ring.
        if (r == _num_rings - 2)
          boundary_info.add_side(elem->id(), /*side=*/0, _exterior_bid);
      }
    }
  }
  // Sanity check: make sure all elements have positive area. Note: we
  // can't use elem->volume() for this, as that always returns a
  // positive area regardless of the node ordering.
  // We compute (p1-p0) \cross (p2-p0) and check that the z-component is positive.
  for (const auto & elem : mesh.element_ptr_range())
  {
    Point cp = (elem->point(1) - elem->point(0)).cross(elem->point(2) - elem->point(0));
    if (cp(2) < 0.)
      mooseError("Invalid elem found with negative area");
  }
  // Create sideset names.
  boundary_info.sideset_name(_cylinder_bid) = "cylinder";
  boundary_info.sideset_name(_exterior_bid) = "exterior";
  // Find neighbors, etc.
  mesh.prepare_for_use();
  if (_use_tri6)
  {
    mesh.all_second_order(/*full_ordered=*/true);
    std::vector<unsigned int> nos;
    // Loop over the elements, moving mid-edge nodes onto the
    // nearest radius as applicable. For each element, exactly one
    // edge should lie on the same radius, so we move only that
    // mid-edge node.
    for (const auto & elem : mesh.element_ptr_range())
    {
      // Make sure we are dealing only with triangles
      libmesh_assert(elem->n_vertices() == 3);
      // Compute vertex radii
      Real radii[3] = {elem->point(0).norm(), elem->point(1).norm(), elem->point(2).norm()};
      // Compute absolute differences between radii so we can determine which two are on the same
      // circular arc.
      Real dr[3] = {std::abs(radii[0] - radii[1]),
                    std::abs(radii[1] - radii[2]),
                    std::abs(radii[2] - radii[0])};
      // Compute index of minimum dr.
      auto index = std::distance(std::begin(dr), std::min_element(std::begin(dr), std::end(dr)));
      // Make sure that the minimum found is also (almost) zero.
      if (dr[index] > TOLERANCE)
        mooseError("Error: element had no sides with nodes on same radius.");
      // Get list of all local node ids on this side. The first
      // two entries in nos correspond to the vertices, the last
      // entry corresponds to the mid-edge node.
      nos = elem->nodes_on_side(index);
      // Compute the angles associated with nodes nos[0] and nos[1].
      Real theta0 = std::atan2(elem->point(nos[0])(1), elem->point(nos[0])(0)),
           theta1 = std::atan2(elem->point(nos[1])(1), elem->point(nos[1])(0));
      // atan2 returns values in the range (-pi, pi).  If theta0
      // and theta1 have the same sign, we can simply average them
      // to get half of the acute angle between them. On the other
      // hand, if theta0 and theta1 are of opposite sign _and_ both
      // are larger than pi/2, we need to add 2*pi when averaging,
      // otherwise we will get half of the _obtuse_ angle between
      // them, and the point will flip to the other side of the
      // circle (see below).
      Real new_theta = 0.5 * (theta0 + theta1);
      // It should not be possible for both:
      // 1.) |theta0| > pi/2, and
      // 2.) |theta1| < pi/2
      // as this would not be a well-formed element.
      if ((theta0 * theta1 < 0) && (std::abs(theta0) > 0.5 * libMesh::pi) &&
          (std::abs(theta1) > 0.5 * libMesh::pi))
        new_theta = 0.5 * (theta0 + theta1 + 2 * libMesh::pi);
      // The new radius will be the radius of point nos[0] or nos[1] (they are the same!).
      Real new_r = elem->point(nos[0]).norm();
      // Finally, move the point to its new location.
      elem->point(nos[2]) = Point(new_r * std::cos(new_theta), new_r * std::sin(new_theta), 0.);
    }
  }
}
buildMeshBaseObject()
std::unique_ptr< MeshBase > MooseMesh::buildMeshBaseObject (unsigned int dim = libMesh::invalid_uint) inherited
Method to construct a libMesh::MeshBase object that is normally set and used by the MooseMesh object during the "init()" phase.
If the parameter dim is not provided, then its value will be taken from the input file mesh block.
Definition at line 2593 of file MooseMesh.C.
{
  if (dim == libMesh::invalid_uint)
    dim = getParam<MooseEnum>("dim");
  std::unique_ptr<MeshBase> mesh;
  if (_use_distributed_mesh)
    mesh = buildTypedMesh<DistributedMesh>(dim);
  else
    mesh = buildTypedMesh<ReplicatedMesh>(dim);
  return mesh;
}
Referenced by MooseMesh::init().
buildNodeList()
void MooseMesh::buildNodeList () inherited
Calls BoundaryInfo::build_node_list()/build_side_list() and makes separate copies of Nodes/Elems in those lists.
Allocates memory which is cleaned up in the freeBndNodes()/freeBndElems() functions.
Definition at line 822 of file MooseMesh.C.
{
  TIME_SECTION("buildNodeList", 5, "Building Node List");
  freeBndNodes();
  auto bc_tuples = getMesh().get_boundary_info().build_node_list();
  int n = bc_tuples.size();
  _bnd_nodes.clear();
  _bnd_nodes.reserve(n);
  for (const auto & t : bc_tuples)
  {
    auto node_id = std::get<0>(t);
    auto bc_id = std::get<1>(t);
    _bnd_nodes.push_back(new BndNode(getMesh().node_ptr(node_id), bc_id));
    _node_set_nodes[bc_id].push_back(node_id);
    _bnd_node_ids[bc_id].insert(node_id);
  }
  _bnd_nodes.reserve(_bnd_nodes.size() + _extra_bnd_nodes.size());
  for (unsigned int i = 0; i < _extra_bnd_nodes.size(); i++)
  {
    BndNode * bnode = new BndNode(_extra_bnd_nodes[i]._node, _extra_bnd_nodes[i]._bnd_id);
    _bnd_nodes.push_back(bnode);
    _bnd_node_ids[std::get<1>(bc_tuples[i])].insert(_extra_bnd_nodes[i]._node->id());
  }
  // This sort is here so that boundary conditions are always applied in the same order
  std::sort(_bnd_nodes.begin(), _bnd_nodes.end(), BndNodeCompare());
}
Referenced by MooseMesh::update().
buildNodeListFromSideList()
void MooseMesh::buildNodeListFromSideList () inherited
Calls BoundaryInfo::build_node_list_from_side_list().
Definition at line 2723 of file MooseMesh.C.
{
  if (_construct_node_list_from_side_list)
    getMesh().get_boundary_info().build_node_list_from_side_list();
}
Referenced by MooseMesh::prepare(), and MooseMesh::update().
buildPeriodicNodeMap()
void MooseMesh::buildPeriodicNodeMap (std::multimap< dof_id_type, dof_id_type > & periodic_node_map, unsigned int var_number, PeriodicBoundaries * pbs) const inherited
This routine builds a multimap of boundary ids to matching boundary ids across all periodic boundaries in the system.
Definition at line 1577 of file MooseMesh.C.
{
  TIME_SECTION("buildPeriodicNodeMap", 5);
  // clear existing map
  periodic_node_map.clear();
  // get periodic nodes
  std::vector<PeriodicNodeInfo> periodic_nodes;
  for (const auto & t : getMesh().get_boundary_info().build_node_list())
  {
    // unfortunately libMesh does not give us a pointer, so we have to look it up ourselves
    auto node = _mesh->node_ptr(std::get<0>(t));
    mooseAssert(node != nullptr,
                "libMesh::BoundaryInfo::build_node_list() returned an ID for a non-existing node");
    auto bc_id = std::get<1>(t);
    periodic_nodes.emplace_back(node, bc_id);
  }
  // sort by boundary id
  std::sort(periodic_nodes.begin(),
            periodic_nodes.end(),
            [](const PeriodicNodeInfo & a, const PeriodicNodeInfo & b) -> bool
            { return a.second > b.second; });
  // build kd-tree
  using KDTreeType = nanoflann::KDTreeSingleIndexAdaptor<
      nanoflann::L2_Simple_Adaptor<Real, PointListAdaptor<PeriodicNodeInfo>, Real, std::size_t>,
      PointListAdaptor<PeriodicNodeInfo>,
      LIBMESH_DIM,
      std::size_t>;
  const unsigned int max_leaf_size = 20; // slightly affects runtime
  auto point_list =
      PointListAdaptor<PeriodicNodeInfo>(periodic_nodes.begin(), periodic_nodes.end());
  auto kd_tree = std::make_unique<KDTreeType>(
      LIBMESH_DIM, point_list, nanoflann::KDTreeSingleIndexAdaptorParams(max_leaf_size));
  mooseAssert(kd_tree != nullptr, "KDTree was not properly initialized.");
  kd_tree->buildIndex();
  // data structures for kd-tree search
  nanoflann::SearchParameters search_params;
  std::vector<nanoflann::ResultItem<std::size_t, Real>> ret_matches;
  // iterate over periodic nodes (boundary ids are in contiguous blocks)
  PeriodicBoundaryBase * periodic = nullptr;
  BoundaryID current_bc_id = BoundaryInfo::invalid_id;
  for (auto & pair : periodic_nodes)
  {
    // entering a new block of boundary IDs
    if (pair.second != current_bc_id)
    {
      current_bc_id = pair.second;
      periodic = pbs->boundary(current_bc_id);
      if (periodic && !periodic->is_my_variable(var_number))
        periodic = nullptr;
    }
    // variable is not periodic at this node, skip
    if (!periodic)
      continue;
    // clear result buffer
    ret_matches.clear();
    // id of the current node
    const auto id = pair.first->id();
    // position where we expect a periodic partner for the current node and boundary
    Point search_point = periodic->get_corresponding_pos(*pair.first);
    // search at the expected point
    kd_tree->radiusSearch(&(search_point)(0), libMesh::TOLERANCE, ret_matches, search_params);
    for (auto & match_pair : ret_matches)
    {
      const auto & match = periodic_nodes[match_pair.first];
      // add matched node if the boundary id is the corresponding id in the periodic pair
      if (match.second == periodic->pairedboundary)
        periodic_node_map.emplace(id, match.first->id());
    }
  }
}
buildPeriodicNodeSets()
void MooseMesh::buildPeriodicNodeSets (std::map< BoundaryID, std::set< dof_id_type > > & periodic_node_sets, unsigned int var_number, PeriodicBoundaries * pbs) const inherited
This routine builds a datastructure of node ids organized by periodic boundary ids.
Definition at line 1662 of file MooseMesh.C.
{
  TIME_SECTION("buildPeriodicNodeSets", 5);
  periodic_node_sets.clear();
  // Loop over all the boundary nodes adding the periodic nodes to the appropriate set
  for (const auto & t : getMesh().get_boundary_info().build_node_list())
  {
    auto node_id = std::get<0>(t);
    auto bc_id = std::get<1>(t);
    // Is this current node on a known periodic boundary?
    if (periodic_node_sets.find(bc_id) != periodic_node_sets.end())
      periodic_node_sets[bc_id].insert(node_id);
    else // This still might be a periodic node but we just haven't seen this boundary_id yet
    {
      const PeriodicBoundaryBase * periodic = pbs->boundary(bc_id);
      if (periodic && periodic->is_my_variable(var_number))
        periodic_node_sets[bc_id].insert(node_id);
    }
  }
}
buildPRefinementAndCoarseningMaps()
void MooseMesh::buildPRefinementAndCoarseningMaps (Assembly * assembly) inherited
Definition at line 2101 of file MooseMesh.C.
{
  _elem_type_to_p_refinement_map.clear();
  _elem_type_to_p_refinement_side_map.clear();
  _elem_type_to_p_coarsening_map.clear();
  _elem_type_to_p_coarsening_side_map.clear();
  std::map<ElemType, std::pair<Elem *, unsigned int>> elems_and_max_p_level;
  for (const auto & elem : getMesh().active_element_ptr_range())
  {
    const auto type = elem->type();
    auto & [picked_elem, max_p_level] = elems_and_max_p_level[type];
    if (!picked_elem)
      picked_elem = elem;
    max_p_level = std::max(max_p_level, elem->p_level());
  }
  // The only requirement on the FEType is that it can be arbitrarily p-refined
  const FEType p_refinable_fe_type(CONSTANT, MONOMIAL);
  std::vector<Point> volume_ref_points_coarse, volume_ref_points_fine, face_ref_points_coarse,
      face_ref_points_fine;
  std::vector<unsigned int> p_levels;
  for (auto & [elem_type, elem_p_level_pair] : elems_and_max_p_level)
  {
    auto & [moose_elem, max_p_level] = elem_p_level_pair;
    const auto dim = moose_elem->dim();
    // Need to do this just once to get the right qrules put in place
    assembly->setCurrentSubdomainID(moose_elem->subdomain_id());
    assembly->reinit(moose_elem);
    assembly->reinit(moose_elem, 0);
    auto & qrule = assembly->writeableQRule();
    auto & qrule_face = assembly->writeableQRuleFace();
    libMesh::Parallel::Communicator self_comm{};
    ReplicatedMesh mesh(self_comm);
    mesh.set_mesh_dimension(dim);
    for (const auto & nd : moose_elem->node_ref_range())
      mesh.add_point(nd);
    Elem * const elem = mesh.add_elem(Elem::build(elem_type).release());
    for (const auto i : elem->node_index_range())
      elem->set_node(i) = mesh.node_ptr(i);
    std::unique_ptr<FEBase> fe(FEBase::build(dim, p_refinable_fe_type));
    std::unique_ptr<FEBase> fe_face(FEBase::build(dim, p_refinable_fe_type));
    fe_face->get_phi();
    const auto & face_phys_points = fe_face->get_xyz();
    fe->attach_quadrature_rule(qrule);
    fe_face->attach_quadrature_rule(qrule_face);
    fe->reinit(elem);
    volume_ref_points_coarse = qrule->get_points();
    fe_face->reinit(elem, (unsigned int)0);
    FEInterface::inverse_map(
        dim, p_refinable_fe_type, elem, face_phys_points, face_ref_points_coarse);
    p_levels.resize(max_p_level + 1);
    std::iota(p_levels.begin(), p_levels.end(), 0);
    MeshRefinement mesh_refinement(mesh);
    for (const auto p_level : p_levels)
    {
      mesh_refinement.uniformly_p_refine(1);
      fe->reinit(elem);
      volume_ref_points_fine = qrule->get_points();
      fe_face->reinit(elem, (unsigned int)0);
      FEInterface::inverse_map(
          dim, p_refinable_fe_type, elem, face_phys_points, face_ref_points_fine);
      const auto map_key = std::make_pair(elem_type, p_level);
      auto & volume_refine_map = _elem_type_to_p_refinement_map[map_key];
      auto & face_refine_map = _elem_type_to_p_refinement_side_map[map_key];
      auto & volume_coarsen_map = _elem_type_to_p_coarsening_map[map_key];
      auto & face_coarsen_map = _elem_type_to_p_coarsening_side_map[map_key];
      auto fill_maps = [this](const auto & coarse_ref_points,
                              const auto & fine_ref_points,
                              auto & coarsen_map,
                              auto & refine_map)
      {
        mapPoints(fine_ref_points, coarse_ref_points, refine_map);
        mapPoints(coarse_ref_points, fine_ref_points, coarsen_map);
      };
      fill_maps(
          volume_ref_points_coarse, volume_ref_points_fine, volume_coarsen_map, volume_refine_map);
      fill_maps(face_ref_points_coarse, face_ref_points_fine, face_coarsen_map, face_refine_map);
      // With this level's maps filled our fine points now become our coarse points
      volume_ref_points_fine.swap(volume_ref_points_coarse);
      face_ref_points_fine.swap(face_ref_points_coarse);
    }
  }
}
Referenced by MooseMesh::buildRefinementAndCoarseningMaps(), and FEProblemBase::meshChangedHelper().
buildRefinementAndCoarseningMaps()
void MooseMesh::buildRefinementAndCoarseningMaps (Assembly * assembly) inherited
Create the refinement and coarsening maps necessary for projection of stateful material properties when using adaptivity.
Parameters
assembly Pointer to the Assembly object for this Mesh.
Definition at line 2199 of file MooseMesh.C.
{
  TIME_SECTION("buildRefinementAndCoarseningMaps", 5, "Building Refinement And Coarsening Maps");
  if (doingPRefinement())
    buildPRefinementAndCoarseningMaps(assembly);
  else
    buildHRefinementAndCoarseningMaps(assembly);
}
Referenced by DumpObjectsProblem::addAuxVariable().
buildRefinementMap()
void MooseMesh::buildRefinementMap (const Elem & elem, QBase & qrule, QBase & qrule_face, int parent_side, int child, int child_side) private inherited
Build the refinement map for a given element type.
This will tell you what quadrature points to copy from and to for stateful material properties on newly created elements from Adaptivity.
Parameters
elem The element that represents the element type you need the refinement map for.
qrule The quadrature rule in use.
qrule_face The current face quadrature rule
parent_side The side of the parent to map (-1 if not mapping parent sides)
child The child number (-1 if not mapping child internal sides)
child_side The side number of the child (-1 if not mapping sides)
Definition at line 2209 of file MooseMesh.C.
{
  TIME_SECTION("buildRefinementMap", 5, "Building Refinement Map");
  if (child == -1) // Doing volume mapping or parent side mapping
  {
    mooseAssert(parent_side == child_side,
                "Parent side must match child_side if not passing a specific child!");
    std::pair<int, ElemType> the_pair(parent_side, elem.type());
    if (_elem_type_to_refinement_map.find(the_pair) != _elem_type_to_refinement_map.end())
      mooseError("Already built a qp refinement map!");
    std::vector<std::pair<unsigned int, QpMap>> coarsen_map;
    std::vector<std::vector<QpMap>> & refinement_map = _elem_type_to_refinement_map[the_pair];
    findAdaptivityQpMaps(
        &elem, qrule, qrule_face, refinement_map, coarsen_map, parent_side, child, child_side);
  }
  else // Need to map a child side to parent volume qps
  {
    std::pair<int, int> child_pair(child, child_side);
    if (_elem_type_to_child_side_refinement_map.find(elem.type()) !=
            _elem_type_to_child_side_refinement_map.end() &&
        _elem_type_to_child_side_refinement_map[elem.type()].find(child_pair) !=
            _elem_type_to_child_side_refinement_map[elem.type()].end())
      mooseError("Already built a qp refinement map!");
    std::vector<std::pair<unsigned int, QpMap>> coarsen_map;
    std::vector<std::vector<QpMap>> & refinement_map =
        _elem_type_to_child_side_refinement_map[elem.type()][child_pair];
    findAdaptivityQpMaps(
        &elem, qrule, qrule_face, refinement_map, coarsen_map, parent_side, child, child_side);
  }
}
Referenced by MooseMesh::buildHRefinementAndCoarseningMaps().
buildSideList() [1/2]
std::vector< std::tuple< dof_id_type, unsigned short int, boundary_id_type > > MooseMesh::buildSideList () inherited
As above, but uses the non-deprecated std::tuple interface.
Definition at line 2749 of file MooseMesh.C.
{
  return getMesh().get_boundary_info().build_side_list();
}
buildSideList() [2/2]
void MooseMesh::buildSideList (std::vector< dof_id_type > & el, std::vector< unsigned short int > & sl, std::vector< boundary_id_type > & il) inherited
Calls BoundaryInfo::build_side_list().
Fills in the three passed vectors with list logical (element, side, id) tuples. This function will eventually be deprecated in favor of the one below, which returns a single std::vector of (elem-id, side-id, bc-id) tuples instead.
Definition at line 2730 of file MooseMesh.C.
{
#ifdef LIBMESH_ENABLE_DEPRECATED
  mooseDeprecated("The version of MooseMesh::buildSideList() taking three arguments is "
                  "deprecated, call the version that returns a vector of tuples instead.");
  getMesh().get_boundary_info().build_side_list(el, sl, il);
#else
  libmesh_ignore(el);
  libmesh_ignore(sl);
  libmesh_ignore(il);
  mooseError("The version of MooseMesh::buildSideList() taking three "
             "arguments is not available in your version of libmesh, call the "
             "version that returns a vector of tuples instead.");
#endif
}
Referenced by InterfaceQpUserObjectBase::initialSetup().
buildTypedMesh()
template<typename T > std::unique_ptr< T > MooseMesh::buildTypedMesh (unsigned int dim = libMesh::invalid_uint) inherited
Shortcut method to construct a unique pointer to a libMesh mesh instance.
The created derived-from-MeshBase object will have its allow_remote_element_removal flag set to whatever our value is. We will also attach any geometric RelationshipManagers that have been requested by our simulation objects to the MeshBase object. If the parameter dim is not provided, then its value will be taken from the input file mesh block.
Definition at line 2001 of file MooseMesh.h.
{
  // If the requested mesh type to build doesn't match our current value for _use_distributed_mesh,
  // then we need to make sure to make our state consistent because other objects, like the periodic
  // boundary condition action, will be querying isDistributedMesh()
  if (_use_distributed_mesh != std::is_same<T, DistributedMesh>::value)
    setParallelType(MeshType<T>::value);
  if (dim == libMesh::invalid_uint)
    dim = getParam<MooseEnum>("dim");
  auto mesh = std::make_unique<T>(_communicator, dim);
  if (!getParam<bool>("allow_renumbering"))
    mesh->allow_renumbering(false);
  mesh->allow_remote_element_removal(_allow_remote_element_removal);
  _app.attachRelationshipManagers(*mesh, *this);
  if (_custom_partitioner_requested)
  {
    // Check of partitioner is supplied (not allowed if custom partitioner is used)
    if (!parameters().isParamSetByAddParam("partitioner"))
      mooseError("If partitioner block is provided, partitioner keyword cannot be used!");
    // Set custom partitioner
    if (!_custom_partitioner.get())
      mooseError("Custom partitioner requested but not set!");
    mesh->partitioner() = _custom_partitioner->clone();
  }
  else
    setPartitionerHelper(mesh.get());
  return mesh;
}
cacheChangedLists()
void MooseMesh::cacheChangedLists () inherited
Cache information about what elements were refined and coarsened in the previous step.
Definition at line 710 of file MooseMesh.C.
{
  TIME_SECTION("cacheChangedLists", 5, "Caching Changed Lists");
  ConstElemRange elem_range(getMesh().local_elements_begin(), getMesh().local_elements_end(), 1);
  CacheChangedListsThread cclt(*this);
  Threads::parallel_reduce(elem_range, cclt);
  _coarsened_element_children.clear();
  _refined_elements = std::make_unique<ConstElemPointerRange>(cclt._refined_elements.begin(),
                                                              cclt._refined_elements.end());
  _coarsened_elements = std::make_unique<ConstElemPointerRange>(cclt._coarsened_elements.begin(),
                                                                cclt._coarsened_elements.end());
  _coarsened_element_children = cclt._coarsened_element_children;
}
Referenced by FEProblemBase::meshChangedHelper().
cacheFaceInfoVariableOwnership()
void MooseMesh::cacheFaceInfoVariableOwnership () const inherited
Cache if variables live on the elements connected by the FaceInfo objects.
The following paragraph of code assigns the VarFaceNeighbors
The face is an internal face of this variable if it is defined on the elem and neighbor subdomains
The face is an invalid face of this variable if it is neither defined on the elem nor the neighbor subdomains
If not 1. or 2. then this is a boundary for this variable and the else clause applies
Definition at line 3671 of file MooseMesh.C.
{
  mooseAssert(
      !Threads::in_threads,
      "Performing writes to faceInfo variable association maps. This must be done unthreaded!");
  std::vector<const MooseVariableFieldBase *> moose_vars;
  for (const auto i : make_range(_app.feProblem().numNonlinearSystems()))
  {
    const auto & nl_variables = _app.feProblem().getNonlinearSystemBase(i).getVariables(0);
    for (const auto & var : nl_variables)
      if (var->fieldType() == 0)
        moose_vars.push_back(var);
  }
  const auto & aux_variables = _app.feProblem().getAuxiliarySystem().getVariables(0);
  for (const auto & var : aux_variables)
    if (var->fieldType() == 0)
      moose_vars.push_back(var);
  for (FaceInfo & face : _all_face_info)
  {
    const SubdomainID elem_subdomain_id = face.elemSubdomainID();
    const SubdomainID neighbor_subdomain_id = face.neighborSubdomainID();
    // loop through vars
    for (unsigned int j = 0; j < moose_vars.size(); ++j)
    {
      // get the variable, its name, and its domain of definition
      const MooseVariableFieldBase * const var = moose_vars[j];
      const std::pair<unsigned int, unsigned int> var_sys =
          std::make_pair(var->number(), var->sys().number());
      std::set<SubdomainID> var_subdomains = var->blockIDs();
      bool var_defined_elem = var_subdomains.find(elem_subdomain_id) != var_subdomains.end();
      bool var_defined_neighbor =
          var_subdomains.find(neighbor_subdomain_id) != var_subdomains.end();
      if (var_defined_elem && var_defined_neighbor)
        face.faceType(var_sys) = FaceInfo::VarFaceNeighbors::BOTH;
      else if (!var_defined_elem && !var_defined_neighbor)
        face.faceType(var_sys) = FaceInfo::VarFaceNeighbors::NEITHER;
      else
      {
        // this is a boundary face for this variable, set elem or neighbor
        if (var_defined_elem)
          face.faceType(var_sys) = FaceInfo::VarFaceNeighbors::ELEM;
        else if (var_defined_neighbor)
          face.faceType(var_sys) = FaceInfo::VarFaceNeighbors::NEIGHBOR;
        else
          mooseError("Should never get here");
      }
    }
  }
}
Referenced by MooseMesh::setupFiniteVolumeMeshData().
cacheFVElementalDoFs()
void MooseMesh::cacheFVElementalDoFs () const inherited
Cache the DoF indices for FV variables on each element.
These indices are used to speed up the setup loops of finite volume systems.
Definition at line 3737 of file MooseMesh.C.
{
  mooseAssert(!Threads::in_threads,
              "Performing writes to elemInfo dof indices. This must be done unthreaded!");
  const unsigned int num_eqs = _app.feProblem().es().n_systems();
  for (auto & elem_info_pair : _elem_to_elem_info)
  {
    ElemInfo & elem_info = elem_info_pair.second;
    auto & dof_vector = elem_info.dofIndices();
    dof_vector.clear();
    dof_vector.resize(num_eqs);
    for (const auto i : make_range(_app.feProblem().numNonlinearSystems()))
      if (_app.feProblem().getNonlinearSystemBase(i).nFVVariables())
      {
        auto & sys = _app.feProblem().getNonlinearSystemBase(i);
        dof_vector[sys.number()].resize(sys.nVariables(), libMesh::DofObject::invalid_id);
        const auto & variables = sys.getVariables(0);
        for (const auto & var : variables)
        {
          const auto & var_subdomains = var->blockIDs();
          // We will only cache for FV variables and if they live on the current subdomain
          if (var->isFV() && var_subdomains.find(elem_info.subdomain_id()) != var_subdomains.end())
          {
            std::vector<dof_id_type> indices;
            var->dofMap().dof_indices(elem_info.elem(), indices, var->number());
            mooseAssert(indices.size() == 1, "We expect to have only one dof per element!");
            dof_vector[sys.number()][var->number()] = indices[0];
          }
        }
      }
    if (_app.feProblem().getAuxiliarySystem().nFVVariables())
    {
      auto & sys = _app.feProblem().getAuxiliarySystem();
      dof_vector[sys.number()].resize(sys.nVariables(), libMesh::DofObject::invalid_id);
      const auto & aux_variables = sys.getVariables(0);
      for (const auto & var : aux_variables)
      {
        const auto & var_subdomains = var->blockIDs();
        // We will only cache for FV variables and if they live on the current subdomain
        if (var->isFV() && var_subdomains.find(elem_info.subdomain_id()) != var_subdomains.end())
        {
          std::vector<dof_id_type> indices;
          var->dofMap().dof_indices(elem_info.elem(), indices, var->number());
          mooseAssert(indices.size() == 1, "We expect to have only one dof per element!");
          dof_vector[sys.number()][var->number()] = indices[0];
        }
      }
    }
  }
}
Referenced by MooseMesh::setupFiniteVolumeMeshData().
cacheInfo()
void MooseMesh::cacheInfo () protected inherited
Definition at line 1204 of file MooseMesh.C.
{
  TIME_SECTION("cacheInfo", 3);
  _sub_to_neighbor_subs.clear();
  _subdomain_boundary_ids.clear();
  _neighbor_subdomain_boundary_ids.clear();
  _block_node_list.clear();
  _higher_d_elem_side_to_lower_d_elem.clear();
  // TODO: Thread this!
  for (const auto & elem : getMesh().element_ptr_range())
  {
    const Elem * ip_elem = elem->interior_parent();
    if (ip_elem)
    {
      unsigned int ip_side = ip_elem->which_side_am_i(elem);
      // For some grid sequencing tests: ip_side == libMesh::invalid_uint
      if (ip_side != libMesh::invalid_uint)
      {
        auto pair = std::make_pair(ip_elem, ip_side);
        _higher_d_elem_side_to_lower_d_elem.insert(
            std::pair<std::pair<const Elem *, unsigned short int>, const Elem *>(pair, elem));
      }
    }
    for (unsigned int nd = 0; nd < elem->n_nodes(); ++nd)
    {
      Node & node = *elem->node_ptr(nd);
      _block_node_list[node.id()].insert(elem->subdomain_id());
    }
  }
  for (const auto & elem : getMesh().active_local_element_ptr_range())
  {
    SubdomainID subdomain_id = elem->subdomain_id();
    for (unsigned int side = 0; side < elem->n_sides(); side++)
    {
      std::vector<BoundaryID> boundary_ids = getBoundaryIDs(elem, side);
      std::set<BoundaryID> & subdomain_set = _subdomain_boundary_ids[subdomain_id];
      subdomain_set.insert(boundary_ids.begin(), boundary_ids.end());
      Elem * neig = elem->neighbor_ptr(side);
      if (neig)
      {
        _neighbor_subdomain_boundary_ids[neig->subdomain_id()].insert(boundary_ids.begin(),
                                                                      boundary_ids.end());
        SubdomainID neighbor_subdomain_id = neig->subdomain_id();
        if (neighbor_subdomain_id != subdomain_id)
          _sub_to_neighbor_subs[subdomain_id].insert(neighbor_subdomain_id);
      }
    }
  }
  for (const auto & blk_id : _mesh_subdomains)
  {
    _communicator.set_union(_sub_to_neighbor_subs[blk_id]);
    _communicator.set_union(_subdomain_boundary_ids[blk_id]);
    _communicator.set_union(_neighbor_subdomain_boundary_ids[blk_id]);
  }
}
Referenced by MooseMesh::update().
changeBoundaryId() [1/2]
void MooseMesh::changeBoundaryId (const boundary_id_type old_id, const boundary_id_type new_id, bool delete_prev) inherited
Change all the boundary IDs for a given side from old_id to new_id.
If delete_prev is true, also actually remove the side with old_id from the BoundaryInfo object.
Definition at line 2499 of file MooseMesh.C.
{
  TIME_SECTION("changeBoundaryId", 6);
  changeBoundaryId(getMesh(), old_id, new_id, delete_prev);
}
Referenced by MooseMesh::changeBoundaryId().
changeBoundaryId() [2/2]
void MooseMesh::changeBoundaryId (MeshBase & mesh, const boundary_id_type old_id, const boundary_id_type new_id, bool delete_prev) static inherited
Change all the boundary IDs for a given side from old_id to new_id for the given mesh.
If delete_prev is true, also actually remove the side with old_id from the BoundaryInfo object.
Definition at line 2508 of file MooseMesh.C.
{
  // Get a reference to our BoundaryInfo object, we will use it several times below...
  BoundaryInfo & boundary_info = mesh.get_boundary_info();
  // Container to catch ids passed back from BoundaryInfo
  std::vector<boundary_id_type> old_ids;
  // Only level-0 elements store BCs.  Loop over them.
  for (auto & elem : as_range(mesh.level_elements_begin(0), mesh.level_elements_end(0)))
  {
    unsigned int n_sides = elem->n_sides();
    for (unsigned int s = 0; s != n_sides; ++s)
    {
      boundary_info.boundary_ids(elem, s, old_ids);
      if (std::find(old_ids.begin(), old_ids.end(), old_id) != old_ids.end())
      {
        std::vector<boundary_id_type> new_ids(old_ids);
        std::replace(new_ids.begin(), new_ids.end(), old_id, new_id);
        if (delete_prev)
        {
          boundary_info.remove_side(elem, s);
          boundary_info.add_side(elem, s, new_ids);
        }
        else
          boundary_info.add_side(elem, s, new_ids);
      }
    }
  }
  // Remove any remaining references to the old ID from the
  // BoundaryInfo object.  This prevents things like empty sidesets
  // from showing up when printing information, etc.
  if (delete_prev)
    boundary_info.remove_id(old_id);
}
checkCoordinateSystems()
void MooseMesh::checkCoordinateSystems () inherited
Performs a sanity check for every element in the mesh.
If an element dimension is 3 and the corresponding coordinate system is RZ, then this will error. If an element dimension is greater than 1 and the corresponding system is RPSHERICAL then this will error
Definition at line 4005 of file MooseMesh.C.
{
  for (const auto & elem : getMesh().element_ptr_range())
  {
    SubdomainID sid = elem->subdomain_id();
    if (_coord_sys[sid] == Moose::COORD_RZ && elem->dim() == 3)
      mooseError("An RZ coordinate system was requested for subdomain " + Moose::stringify(sid) +
                 " which contains 3D elements.");
    if (_coord_sys[sid] == Moose::COORD_RSPHERICAL && elem->dim() > 1)
      mooseError("An RSPHERICAL coordinate system was requested for subdomain " +
                 Moose::stringify(sid) + " which contains 2D or 3D elements.");
  }
}
Referenced by FEProblemBase::checkCoordinateSystems().
checkDuplicateSubdomainNames()
void MooseMesh::checkDuplicateSubdomainNames () private inherited
Loop through all subdomain IDs and check if there is name duplication used for the subdomains with same ID.
Throw out an error if any name duplication is found.
Definition at line 4035 of file MooseMesh.C.
{
  std::map<SubdomainName, SubdomainID> subdomain;
  for (const auto & sbd_id : _mesh_subdomains)
  {
    std::string sub_name = getSubdomainName(sbd_id);
    if (!sub_name.empty() && subdomain.count(sub_name) > 0)
      mooseError("The subdomain name ",
                 sub_name,
                 " is used for both subdomain with ID=",
                 subdomain[sub_name],
                 " and ID=",
                 sbd_id,
                 ", Please rename one of them!");
    else
      subdomain[sub_name] = sbd_id;
  }
}
Referenced by MooseMesh::prepare().
clearQuadratureNodes()
void MooseMesh::clearQuadratureNodes () inherited
Clear out any existing quadrature nodes.
Most likely called before re-adding them.
Definition at line 1452 of file MooseMesh.C.
{
  // Delete all the quadrature nodes
  for (auto & it : _quadrature_nodes)
    delete it.second;
  _quadrature_nodes.clear();
  _elem_to_side_to_qp_to_quadrature_nodes.clear();
  _extra_bnd_nodes.clear();
}
Referenced by DisplacedProblem::meshChanged(), GeometricSearchData::reinit(), and MooseMesh::~MooseMesh().
clone()
MooseMesh & MooseMesh::clone () const virtual inherited
Clone method.
Allocates memory you are responsible to clean up.
Definition at line 2559 of file MooseMesh.C.
{
  mooseError("MooseMesh::clone() is no longer supported, use MooseMesh::safeClone() instead.");
}
Referenced by TiledMesh::buildMesh().
coarsenedElementChildren()
const std::vector< const Elem * > & MooseMesh::coarsenedElementChildren (const Elem * elem) const inherited
Get the newly removed children element ids for an element that was just coarsened.
Parameters
elem Pointer to the parent element that was coarsened to.
Returns
The child element ids in Elem::child() order.
Definition at line 740 of file MooseMesh.C.
{
  auto elem_to_child_pair = _coarsened_element_children.find(elem);
  mooseAssert(elem_to_child_pair != _coarsened_element_children.end(), "Missing element in map");
  return elem_to_child_pair->second;
}
Referenced by FEProblemBase::meshChangedHelper(), ProjectMaterialProperties::onBoundary(), and ProjectMaterialProperties::onElement().
coarsenedElementRange()
ConstElemPointerRange * MooseMesh::coarsenedElementRange () const inherited
Return a range that is suitable for threaded execution over elements that were just coarsened.
Note that these are the Parent elements that are now set to be INACTIVE. Their children are the elements that were just removed. Use coarsenedElementChildren() to get the element IDs for the children that were just removed for a particular parent element.
Definition at line 734 of file MooseMesh.C.
{
  return _coarsened_elements.get();
}
Referenced by FEProblemBase::meshChangedHelper().
computeFiniteVolumeCoords()
void MooseMesh::computeFiniteVolumeCoords () const inherited
Compute the face coordinate value for all FaceInfo and ElemInfo objects.
'Coordinate' here means a coordinate value associated with the coordinate system. For Cartesian coordinate systems, 'coordinate' is simply '1'; in RZ, '2*pi*r', and in spherical, '4*pi*r^2'
Definition at line 3616 of file MooseMesh.C.
{
  if (_finite_volume_info_dirty)
    mooseError("Trying to compute face- and elem-info coords when the information is dirty");
  for (auto & fi : _all_face_info)
  {
    // get elem & neighbor elements, and set subdomain ids
    const SubdomainID elem_subdomain_id = fi.elemSubdomainID();
    const SubdomainID neighbor_subdomain_id = fi.neighborSubdomainID();
    coordTransformFactor(
        *this, elem_subdomain_id, fi.faceCentroid(), fi.faceCoord(), neighbor_subdomain_id);
  }
  for (auto & ei : _elem_to_elem_info)
    coordTransformFactor(
        *this, ei.second.subdomain_id(), ei.second.centroid(), ei.second.coordFactor());
}
Referenced by MooseMesh::setupFiniteVolumeMeshData().
connectControllableParams()
void MooseBaseParameterInterface::connectControllableParams (const std::string & parameter, const std::string & object_type, const std::string & object_name, const std::string & object_parameter) const inherited
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
Parameters
parameter Name of the controllable parameter of this action
object_type Type of the object added by this action.
object_name Name of the object added by this action.
object_parameter Name of the parameter of the object.
Definition at line 34 of file MooseBaseParameterInterface.C.
{
  MooseObjectParameterName primary_name(uniqueName(), parameter);
  const auto base_type = _factory.getValidParams(object_type).get<std::string>("_moose_base");
  MooseObjectParameterName secondary_name(base_type, object_name, object_parameter);
  _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
      primary_name, secondary_name);
  const auto & tags = _pars.get<std::vector<std::string>>("control_tags");
  for (const auto & tag : tags)
  {
    if (!tag.empty())
    {
      MooseObjectParameterName tagged_name(tag, _moose_base->name(), parameter);
      _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
          tagged_name, secondary_name);
    }
  }
}
coordTransform()
MooseAppCoordTransform & MooseMesh::coordTransform () inline inherited
Returns
the coordinate transformation object that describes how to transform this problem's coordinate system into the canonical/reference coordinate system
Definition at line 1800 of file MooseMesh.h.
{
  mooseAssert(_coord_transform, "The coordinate transformation object is null.");
  return *_coord_transform;
}
Referenced by FEProblemBase::coordTransform().
declareManagedRestartableDataWithContext()
template<typename T , typename... Args> Restartable::ManagedValue< T > Restartable::declareManagedRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declares a piece of "managed" restartable data and initialize it.
Here, "managed" restartable data means that the caller can destruct this data upon destruction of the return value of this method. Therefore, this ManagedValue<T> wrapper should survive after the final calls to dataStore() for it. That is... at the very end.
This is needed for objects whose destruction ordering is important, and enables natural c++ destruction in reverse construction order of the object that declares it.
See delcareRestartableData and declareRestartableDataWithContext for more information.
Definition at line 276 of file Restartable.h.
{
  auto & data_ptr =
      declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...);
  return Restartable::ManagedValue<T>(data_ptr);
}
declareRecoverableData()
template<typename T , typename... Args> T & Restartable::declareRecoverableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "recoverable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
Note - this data will NOT be restored on Restart!
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 351 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  registerRestartableNameWithFilterOnApp(full_name, Moose::RESTARTABLE_FILTER::RECOVERABLE);
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableData()
template<typename T , typename... Args> T & Restartable::declareRestartableData (const std::string & data_name, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
args Arguments to forward to the constructor of the data
Definition at line 269 of file Restartable.h.
{
  return declareRestartableDataWithContext<T>(data_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataHelper()
template<typename T , typename... Args> RestartableData< T > & Restartable::declareRestartableDataHelper (const std::string & data_name, void * context, Args &&... args) const private inherited
Helper function for declaring restartable data.
We use this function to reduce code duplication when returning const/nonconst references to the data.
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 303 of file Restartable.h.
{
  const auto full_name = restartableName(data_name);
  // Here we will create the RestartableData even though we may not use this instance.
  // If it's already in use, the App will return a reference to the existing instance and we'll
  // return that one instead. We might refactor this to have the app create the RestartableData
  // at a later date.
  auto data_ptr =
      std::make_unique<RestartableData<T>>(full_name, context, std::forward<Args>(args)...);
  auto & restartable_data_ref = static_cast<RestartableData<T> &>(
      registerRestartableDataOnApp(std::move(data_ptr), _restartable_tid));
  return restartable_data_ref;
}
declareRestartableDataWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithContext (const std::string & data_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable" and initialize it.
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 294 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, context, std::forward<Args>(args)...).set();
}
declareRestartableDataWithObjectName()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectName (const std::string & data_name, const std::string & object_name, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
args Arguments to forward to the constructor of the data
Definition at line 323 of file Restartable.h.
{
  return declareRestartableDataWithObjectNameWithContext<T>(
      data_name, object_name, nullptr, std::forward<Args>(args)...);
}
declareRestartableDataWithObjectNameWithContext()
template<typename T , typename... Args> T & Restartable::declareRestartableDataWithObjectNameWithContext (const std::string & data_name, const std::string & object_name, void * context, Args &&... args) protected inherited
Declare a piece of data as "restartable".
This means that in the event of a restart this piece of data will be restored back to its previous value.
NOTE: This returns a reference! Make sure you store it in a reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
object_name A supplied name for the object that is declaring this data.
context Context pointer that will be passed to the load and store functions
args Arguments to forward to the constructor of the data
Definition at line 333 of file Restartable.h.
{
  std::string old_name = _restartable_name;
  _restartable_name = object_name;
  T & value = declareRestartableDataWithContext<T>(data_name, context, std::forward<Args>(args)...);
  _restartable_name = old_name;
  return value;
}
deleteRemoteElements()
void MooseMesh::deleteRemoteElements () inherited
Delete remote elements.
Definition at line 3659 of file MooseMesh.C.
{
  _allow_remote_element_removal = true;
  if (!_mesh)
    mooseError("Cannot delete remote elements because we have not yet attached a MeshBase");
  _mesh->allow_remote_element_removal(true);
  _mesh->delete_remote_elements();
}
detectOrthogonalDimRanges()
bool MooseMesh::detectOrthogonalDimRanges (Real tol = 1e-6) inherited
This routine determines whether the Mesh is a regular orthogonal mesh (i.e.
square in 2D, cubic in 3D). If it is, then we can use a number of convenience functions when periodic boundary conditions are applied. This routine populates the _range vector which is necessary for these convenience functions.
Note: This routine can potentially identify meshes with concave faces that still "fit" in the convex hull of the corresponding regular orthogonal mesh. This case is highly unlikely in practice and if a user does this, well.... release the kicker!
Definition at line 1689 of file MooseMesh.C.
{
  TIME_SECTION("detectOrthogonalDimRanges", 5);
  if (_regular_orthogonal_mesh)
    return true;
  std::vector<Real> min(3, std::numeric_limits<Real>::max());
  std::vector<Real> max(3, std::numeric_limits<Real>::min());
  unsigned int dim = getMesh().mesh_dimension();
  // Find the bounding box of our mesh
  for (const auto & node : getMesh().node_ptr_range())
    // Check all coordinates, we don't know if this mesh might be lying in a higher dim even if the
    // mesh dimension is lower.
    for (const auto i : make_range(Moose::dim))
    {
      if ((*node)(i) < min[i])
        min[i] = (*node)(i);
      if ((*node)(i) > max[i])
        max[i] = (*node)(i);
    }
  this->comm().max(max);
  this->comm().min(min);
  _extreme_nodes.resize(8); // 2^LIBMESH_DIM
  // Now make sure that there are actual nodes at all of the extremes
  std::vector<bool> extreme_matches(8, false);
  std::vector<unsigned int> comp_map(3);
  for (const auto & node : getMesh().node_ptr_range())
  {
    // See if the current node is located at one of the extremes
    unsigned int coord_match = 0;
    for (const auto i : make_range(Moose::dim))
    {
      if (std::abs((*node)(i)-min[i]) < tol)
      {
        comp_map[i] = MIN;
        ++coord_match;
      }
      else if (std::abs((*node)(i)-max[i]) < tol)
      {
        comp_map[i] = MAX;
        ++coord_match;
      }
    }
    if (coord_match == LIBMESH_DIM) // Found a coordinate at one of the extremes
    {
      _extreme_nodes[comp_map[X] * 4 + comp_map[Y] * 2 + comp_map[Z]] = node;
      extreme_matches[comp_map[X] * 4 + comp_map[Y] * 2 + comp_map[Z]] = true;
    }
  }
  // See if we matched all of the extremes for the mesh dimension
  this->comm().max(extreme_matches);
  if (std::count(extreme_matches.begin(), extreme_matches.end(), true) == (1 << dim))
    _regular_orthogonal_mesh = true;
  // Set the bounds
  _bounds.resize(LIBMESH_DIM);
  for (const auto i : make_range(Moose::dim))
  {
    _bounds[i].resize(2);
    _bounds[i][MIN] = min[i];
    _bounds[i][MAX] = max[i];
  }
  return _regular_orthogonal_mesh;
}
Referenced by AddPeriodicBCAction::autoTranslationBoundaries(), and MooseMesh::prepare().
detectPairedSidesets()
void MooseMesh::detectPairedSidesets () private inherited
This routine detects paired sidesets of a regular orthogonal mesh (.i.e.
parallel sidesets "across" from one and other). The _paired_boundary datastructure is populated with this information.
Definition at line 1763 of file MooseMesh.C.
{
  TIME_SECTION("detectPairedSidesets", 5);
  // Loop over level-0 elements (since boundary condition information
  // is only directly stored for them) and find sidesets with normals
  // that point in the -x, +x, -y, +y, and -z, +z direction.  If there
  // is a unique sideset id for each direction, then the paired
  // sidesets consist of (-x,+x), (-y,+y), (-z,+z).  If there are
  // multiple sideset ids for a given direction, then we can't pick a
  // single pair for that direction.  In that case, we'll just return
  // as was done in the original algorithm.
  // Points used for direction comparison
  const Point minus_x(-1, 0, 0), plus_x(1, 0, 0), minus_y(0, -1, 0), plus_y(0, 1, 0),
      minus_z(0, 0, -1), plus_z(0, 0, 1);
  // we need to test all element dimensions from dim down to 1
  const unsigned int dim = getMesh().mesh_dimension();
  // boundary id sets for elements of different dimensions
  std::vector<std::set<BoundaryID>> minus_x_ids(dim), plus_x_ids(dim), minus_y_ids(dim),
      plus_y_ids(dim), minus_z_ids(dim), plus_z_ids(dim);
  std::vector<std::unique_ptr<FEBase>> fe_faces(dim);
  std::vector<std::unique_ptr<QGauss>> qfaces(dim);
  for (unsigned side_dim = 0; side_dim < dim; ++side_dim)
  {
    // Face is assumed to be flat, therefore normal is assumed to be
    // constant over the face, therefore only compute it at 1 qp.
    qfaces[side_dim] = std::unique_ptr<QGauss>(new QGauss(side_dim, CONSTANT));
    // A first-order Lagrange FE for the face.
    fe_faces[side_dim] = FEBase::build(side_dim + 1, FEType(FIRST, LAGRANGE));
    fe_faces[side_dim]->attach_quadrature_rule(qfaces[side_dim].get());
  }
  // We need this to get boundary ids for each boundary face we encounter.
  BoundaryInfo & boundary_info = getMesh().get_boundary_info();
  std::vector<boundary_id_type> face_ids;
  for (auto & elem : as_range(getMesh().level_elements_begin(0), getMesh().level_elements_end(0)))
  {
    // dimension of the current element and its normals
    unsigned int side_dim = elem->dim() - 1;
    const std::vector<Point> & normals = fe_faces[side_dim]->get_normals();
    // loop over element sides
    for (unsigned int s = 0; s < elem->n_sides(); s++)
    {
      // If side is on the boundary
      if (elem->neighbor_ptr(s) == nullptr)
      {
        std::unique_ptr<Elem> side = elem->build_side_ptr(s);
        fe_faces[side_dim]->reinit(elem, s);
        // Get the boundary ID(s) for this side.  If there is more
        // than 1 boundary id, then we already can't determine a
        // unique pairing of sides in this direction, but we'll just
        // keep going to keep the logic simple.
        boundary_info.boundary_ids(elem, s, face_ids);
        // x-direction faces
        if (normals[0].absolute_fuzzy_equals(minus_x))
          minus_x_ids[side_dim].insert(face_ids.begin(), face_ids.end());
        else if (normals[0].absolute_fuzzy_equals(plus_x))
          plus_x_ids[side_dim].insert(face_ids.begin(), face_ids.end());
        // y-direction faces
        else if (normals[0].absolute_fuzzy_equals(minus_y))
          minus_y_ids[side_dim].insert(face_ids.begin(), face_ids.end());
        else if (normals[0].absolute_fuzzy_equals(plus_y))
          plus_y_ids[side_dim].insert(face_ids.begin(), face_ids.end());
        // z-direction faces
        else if (normals[0].absolute_fuzzy_equals(minus_z))
          minus_z_ids[side_dim].insert(face_ids.begin(), face_ids.end());
        else if (normals[0].absolute_fuzzy_equals(plus_z))
          plus_z_ids[side_dim].insert(face_ids.begin(), face_ids.end());
      }
    }
  }
  // For a distributed mesh, boundaries may be distributed as well. We therefore collect information
  // from everyone. If the mesh is already serial, then there is no need to do an allgather. Note
  // that this is just going to gather information about what the periodic bc ids are. We are not
  // gathering any remote elements or anything like that. It's just that the GhostPointNeighbors
  // ghosting functor currently relies on the fact that every process agrees on whether we have
  // periodic boundaries; every process that thinks there are periodic boundaries will call
  // MeshBase::sub_point_locator which makes a parallel_object_only() assertion (right or wrong). So
  // we all need to go there (or not go there)
  if (_use_distributed_mesh && !_mesh->is_serial())
  {
    // Pack all data together so that we send them via one communication
    // pair: boundary side --> boundary ids.
    std::vector<std::pair<boundary_id_type, boundary_id_type>> vecdata;
    //  We check boundaries on all dimensions
    for (unsigned side_dim = 0; side_dim < dim; ++side_dim)
    {
      // "6" means: we have at most 6 boundaries. It is true for generated simple mesh
      // "detectPairedSidesets" is designed for only simple meshes
      for (auto bd = minus_x_ids[side_dim].begin(); bd != minus_x_ids[side_dim].end(); bd++)
        vecdata.emplace_back(side_dim * 6 + 0, *bd);
      for (auto bd = plus_x_ids[side_dim].begin(); bd != plus_x_ids[side_dim].end(); bd++)
        vecdata.emplace_back(side_dim * 6 + 1, *bd);
      for (auto bd = minus_y_ids[side_dim].begin(); bd != minus_y_ids[side_dim].end(); bd++)
        vecdata.emplace_back(side_dim * 6 + 2, *bd);
      for (auto bd = plus_y_ids[side_dim].begin(); bd != plus_y_ids[side_dim].end(); bd++)
        vecdata.emplace_back(side_dim * 6 + 3, *bd);
      for (auto bd = minus_z_ids[side_dim].begin(); bd != minus_z_ids[side_dim].end(); bd++)
        vecdata.emplace_back(side_dim * 6 + 4, *bd);
      for (auto bd = plus_z_ids[side_dim].begin(); bd != plus_z_ids[side_dim].end(); bd++)
        vecdata.emplace_back(side_dim * 6 + 5, *bd);
    }
    _communicator.allgather(vecdata, false);
    // Unpack data, and add them into minus/plus_x/y_ids
    for (auto pair = vecdata.begin(); pair != vecdata.end(); pair++)
    {
      // Convert data from the long vector, and add data to separated sets
      auto side_dim = pair->first / 6;
      auto side = pair->first % 6;
      switch (side)
      {
        case 0:
          minus_x_ids[side_dim].insert(pair->second);
          break;
        case 1:
          plus_x_ids[side_dim].insert(pair->second);
          break;
        case 2:
          minus_y_ids[side_dim].insert(pair->second);
          break;
        case 3:
          plus_y_ids[side_dim].insert(pair->second);
          break;
        case 4:
          minus_z_ids[side_dim].insert(pair->second);
          break;
        case 5:
          plus_z_ids[side_dim].insert(pair->second);
          break;
        default:
          mooseError("Unknown boundary side ", side);
      }
    }
  } // end if (_use_distributed_mesh && !_need_ghost_ghosted_boundaries)
  for (unsigned side_dim = 0; side_dim < dim; ++side_dim)
  {
    // If unique pairings were found, fill up the _paired_boundary data
    // structure with that information.
    if (minus_x_ids[side_dim].size() == 1 && plus_x_ids[side_dim].size() == 1)
      _paired_boundary.emplace_back(
          std::make_pair(*(minus_x_ids[side_dim].begin()), *(plus_x_ids[side_dim].begin())));
    if (minus_y_ids[side_dim].size() == 1 && plus_y_ids[side_dim].size() == 1)
      _paired_boundary.emplace_back(
          std::make_pair(*(minus_y_ids[side_dim].begin()), *(plus_y_ids[side_dim].begin())));
    if (minus_z_ids[side_dim].size() == 1 && plus_z_ids[side_dim].size() == 1)
      _paired_boundary.emplace_back(
          std::make_pair(*(minus_z_ids[side_dim].begin()), *(plus_z_ids[side_dim].begin())));
  }
}
Referenced by MooseMesh::getPairedBoundaryMapping().
determineUseDistributedMesh()
void MooseMesh::determineUseDistributedMesh () inherited
Determine whether to use a distributed mesh.
Should be called during construction
Definition at line 2565 of file MooseMesh.C.
{
  switch (_parallel_type)
  {
    case ParallelType::DEFAULT:
      // The user did not specify 'parallel_type = XYZ' in the input file,
      // so we allow the --distributed-mesh command line arg to possibly turn
      // on DistributedMesh.  If the command line arg is not present, we pick ReplicatedMesh.
      if (_app.getDistributedMeshOnCommandLine())
        _use_distributed_mesh = true;
      break;
    case ParallelType::REPLICATED:
      if (_app.getDistributedMeshOnCommandLine() || _is_nemesis || _is_split)
        _parallel_type_overridden = true;
      _use_distributed_mesh = false;
      break;
    case ParallelType::DISTRIBUTED:
      _use_distributed_mesh = true;
      break;
  }
  // If the user specifies 'nemesis = true' in the Mesh block, or they are using --use-split,
  // we must use DistributedMesh.
  if (_is_nemesis || _is_split)
    _use_distributed_mesh = true;
}
Referenced by MooseMesh::MooseMesh(), and MooseMesh::setParallelType().
dimension()
unsigned int MooseMesh::dimension () const virtual inherited
Returns MeshBase::mesh_dimension(), (not MeshBase::spatial_dimension()!) of the underlying libMesh mesh object.
Definition at line 2668 of file MooseMesh.C.
{
  return getMesh().mesh_dimension();
}
Referenced by MooseMesh::addPeriodicVariable(), AddPeriodicBCAction::autoTranslationBoundaries(), NodalPatchRecoveryBase::evaluateBasisFunctions(), FunctionPeriodicBoundary::FunctionPeriodicBoundary(), MooseMesh::getPairedBoundaryMapping(), Moose::FV::greenGaussGradient(), PointVariableSamplerBase::initialize(), BlockRestrictable::initializeBlockRestrictable(), PropertyReadFile::initVoronoiCenterPoints(), MooseMesh::isTranslatedPeriodic(), MooseMesh::minPeriodicVector(), MooseVariableData< OutputType >::MooseVariableData(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PenetrationLocator::PenetrationLocator(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), SidesetInfoVectorPostprocessor::SidesetInfoVectorPostprocessor(), and Moose::PetscSupport::storePetscOptions().
dimensionWidth()
Real MooseMesh::dimensionWidth (unsigned int component) const inherited
Returns the width of the requested dimension.
Definition at line 1939 of file MooseMesh.C.
{
  return getMaxInDimension(component) - getMinInDimension(component);
}
Referenced by MooseMesh::addPeriodicVariable(), AddPeriodicBCAction::autoTranslationBoundaries(), and MooseMesh::effectiveSpatialDimension().
doingPRefinement() [1/2]
bool MooseMesh::doingPRefinement () const inline inherited
Query whether we have p-refinement.
Definition at line 1327 of file MooseMesh.h.
{ return _doing_p_refinement; }
Referenced by MooseMesh::buildRefinementAndCoarseningMaps().
doingPRefinement() [2/2]
void MooseMesh::doingPRefinement (bool doing_p_refinement) inline inherited
Indicate whether the kind of adaptivity we're doing is p-refinement.
Definition at line 1322 of file MooseMesh.h.
{ _doing_p_refinement = doing_p_refinement; }
Referenced by SubProblem::doingPRefinement(), ProjectMaterialProperties::onBoundary(), CacheChangedListsThread::onElement(), and ProjectMaterialProperties::onElement().
effectiveSpatialDimension()
unsigned int MooseMesh::effectiveSpatialDimension () const virtual inherited
Returns the effective spatial dimension determined by the coordinates actually used by the mesh.
This means that a 1D mesh that has non-zero z or y coordinates is actually a 2D or 3D mesh, respectively. Likewise a 2D mesh that has non-zero z coordinates is actually 3D mesh.
Definition at line 2674 of file MooseMesh.C.
{
  const Real abs_zero = 1e-12;
  // See if the mesh is completely containd in the z and y planes to calculate effective spatial
  // dim
  for (unsigned int dim = LIBMESH_DIM; dim >= 1; --dim)
    if (dimensionWidth(dim - 1) >= abs_zero)
      return dim;
  // If we get here, we have a 1D mesh on the x-axis.
  return 1;
}
Referenced by Exodus::setOutputDimensionInExodusWriter().
elem() [1/2]
Elem * MooseMesh::elem (const dof_id_type i) virtual inherited
Various accessors (pointers/references) for Elem "i".
If the requested elem is a remote element on a distributed mesh, only the query accessors are valid to call, and they return NULL.
Definition at line 2839 of file MooseMesh.C.
{
  mooseDeprecated("MooseMesh::elem() is deprecated, please use MooseMesh::elemPtr() instead");
  return elemPtr(i);
}
Referenced by MooseMesh::addQuadratureNode(), MooseMesh::buildCoarseningMap(), MooseMesh::buildElemIDInfo(), MooseMesh::buildFiniteVolumeInfo(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildLowerDMesh(), AnnularMesh::buildMesh(), ConcentricCircleMesh::buildMesh(), RinglebMesh::buildMesh(), buildMesh(), MooseMesh::buildPRefinementAndCoarseningMaps(), MooseMesh::buildRefinementMap(), MooseMesh::cacheInfo(), MooseMesh::changeBoundaryId(), MooseMesh::checkCoordinateSystems(), MooseMesh::coarsenedElementChildren(), MooseMesh::detectPairedSidesets(), MooseMesh::faceInfo(), MooseMesh::findAdaptivityQpMaps(), MooseMesh::getBlocksMaxDimension(), MooseMesh::getBoundaryIDs(), MooseMesh::getCoarseningMap(), MooseMesh::getElemIDMapping(), MooseMesh::getHigherDSide(), MooseMesh::getLowerDElem(), MooseMesh::getPCoarseningMap(), MooseMesh::getPCoarseningMapHelper(), MooseMesh::getPCoarseningSideMap(), MooseMesh::getPRefinementMap(), MooseMesh::getPRefinementMapHelper(), MooseMesh::getPRefinementSideMap(), MooseMesh::getQuadratureNode(), MooseMesh::getRefinementMap(), MooseMesh::ghostGhostedBoundaries(), MooseMesh::nodeToActiveSemilocalElemMap(), MooseMesh::nodeToElemMap(), MooseMesh::prepare(), MooseMesh::sideWithBoundaryID(), and MooseMesh::updateActiveSemiLocalNodeRange().
elem() [2/2]
const Elem * MooseMesh::elem (const dof_id_type i) const virtual inherited
Definition at line 2846 of file MooseMesh.C.
{
  mooseDeprecated("MooseMesh::elem() is deprecated, please use MooseMesh::elemPtr() instead");
  return elemPtr(i);
}
elemInfo()
const ElemInfo & MooseMesh::elemInfo (const dof_id_type id) const inherited
Accessor for the elemInfo object for a given element ID.
Definition at line 3610 of file MooseMesh.C.
{
  return libmesh_map_find(_elem_to_elem_info, id);
}
elemInfoVector()
const std::vector< const ElemInfo * > & MooseMesh::elemInfoVector () const inline inherited
Accessor for the element info objects owned by this process.
Definition at line 1156 of file MooseMesh.h.
{ return _elem_info; }
elemPtr() [1/2]
Elem * MooseMesh::elemPtr (const dof_id_type i) virtual inherited
Definition at line 2853 of file MooseMesh.C.
{
  return getMesh().elem_ptr(i);
}
Referenced by FEProblemBase::addGhostedElem(), SystemBase::augmentSendList(), NodalPatchRecoveryAuxBase::blockRestrictElements(), NodalPatchRecovery::compute(), BoundaryMarker::computeElementMarker(), NodalPatchRecoveryAuxBase::computeValue(), ProjectionAux::computeValue(), dataLoad(), MooseMesh::elem(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), ActivateElementsUserObjectBase::execute(), ElementSubdomainModifier::execute(), NonlinearSystemBase::findImplicitGeometricCouplingEntries(), NearestNodeLocator::findNodes(), NodeElemConstraint::getConnectedDofIndices(), NodeFaceConstraint::getConnectedDofIndices(), FEProblemBase::getDiracElements(), PenetrationThread::getInfoForFacesWithCommonNodes(), ActivateElementsUserObjectBase::getNewlyActivatedElementRange(), ActivateElementsUserObjectBase::getNewlyActivatedNodeRange(), DiracKernelBase::hasPointsOnElem(), ActivateElementsUserObjectBase::isNewlyActivated(), Moose::Mortar::loopOverMortarSegments(), PenetrationThread::operator()(), SecondaryNeighborhoodThread::operator()(), FEProblemBase::prepare(), FEProblemBase::prepareFace(), FEProblemBase::reinitDirac(), FEProblemBase::reinitElem(), FEProblemBase::reinitElemFace(), FEProblemBase::reinitElemFaceRef(), FEProblemBase::reinitElemNeighborAndLowerD(), FEProblemBase::reinitLowerDElem(), FEProblemBase::reinitNeighbor(), FEProblemBase::reinitNeighborFaceRef(), ElementSubdomainModifier::setAncestorsSubdomainIDs(), EqualValueEmbeddedConstraint::shouldApply(), ActivateElementsUserObjectBase::updateBoundaryInfo(), and NearestNodeLocator::updatePatch().
elemPtr() [2/2]
const Elem * MooseMesh::elemPtr (const dof_id_type i) const virtual inherited
Definition at line 2859 of file MooseMesh.C.
{
  return getMesh().elem_ptr(i);
}
enabled()
virtual bool MooseObject::enabled () const inline virtual inherited
Return the enabled status of the object.
Reimplemented in EigenKernel.
Definition at line 54 of file MooseObject.h.
{ return _enabled; }
Referenced by EigenKernel::enabled().
errorIfDistributedMesh()
void MooseMesh::errorIfDistributedMesh (std::string name) const inherited
Generate a unified error message if the underlying libMesh mesh is a DistributedMesh.
Clients of MooseMesh can use this function to throw an error if they know they don't work with DistributedMesh.
See, for example, the NodalVariableValue class.
Definition at line 3358 of file MooseMesh.C.
{
  if (_use_distributed_mesh)
    mooseError("Cannot use ",
               name,
               " with DistributedMesh!\n",
               "Consider specifying parallel_type = 'replicated' in your input file\n",
               "to prevent it from being run with DistributedMesh.");
}
Referenced by BoundaryPreservedMarker::BoundaryPreservedMarker(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementsAlongLine::ElementsAlongLine(), ElementsAlongPlane::ElementsAlongPlane(), FunctorPositions::initialize(), FunctorTimes::initialize(), IntersectionPointsAlongLine::IntersectionPointsAlongLine(), LineMaterialSamplerBase< T >::LineMaterialSamplerBase(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), NodeElemConstraint::NodeElemConstraint(), NonlocalIntegratedBC::NonlocalIntegratedBC(), NonlocalKernel::NonlocalKernel(), PatternedMesh::PatternedMesh(), StitchedMesh::StitchedMesh(), and TiledMesh::TiledMesh().
errorPrefix()
std::string MooseBaseErrorInterface::errorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for this object:
The following <error_type> occurred in the object "<name>", of type "<type>".
Definition at line 15 of file MooseBaseErrorInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the object \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseErrorInterface::mooseError(), and MooseBaseErrorInterface::mooseWarning().
faceInfo() [1/2]
const std::vector< const FaceInfo * > & MooseMesh::faceInfo () const inline inherited
Accessor for local FaceInfo objects.
Definition at line 2072 of file MooseMesh.h.
{
  return _face_info;
}
Referenced by LayeredSideDiffusiveFluxAverage::computeQpIntegral(), SideIntegralVariableUserObject::computeQpIntegral(), InterfaceUserObject::execute(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), InternalSideUserObject::getFaceInfos(), SideUserObject::getFaceInfos(), and Moose::FV::loopOverElemFaceInfo().
faceInfo() [2/2]
const FaceInfo * MooseMesh::faceInfo (const Elem * elem, unsigned int side) const inherited
Accessor for the local FaceInfo object on the side of one element. Returns null if ghosted.
Definition at line 3594 of file MooseMesh.C.
{
  auto it = _elem_side_to_face_info.find(std::make_pair(elem, side));
  if (it == _elem_side_to_face_info.end())
    return nullptr;
  else
  {
    mooseAssert(it->second,
                "For some reason, the FaceInfo object is NULL! Try calling "
                "`buildFiniteVolumeInfo()` before using this accessor!");
    return it->second;
  }
}
findAdaptivityQpMaps()
void MooseMesh::findAdaptivityQpMaps (const Elem * template_elem, QBase & qrule, QBase & qrule_face, std::vector< std::vector< QpMap > > & refinement_map, std::vector< std::pair< unsigned int, QpMap > > & coarsen_map, int parent_side, int child, int child_side) private inherited
Given an elem type, get maps that tell us what qp's are closest to each other between a parent and it's children.
This is mainly used for mapping stateful material properties during adaptivity.
There are 3 cases here:
Volume to volume (parent_side = -1, child = -1, child_side = -1)
Parent side to child side (parent_side = 0+, child = -1, child_side = 0+)
Child side to parent volume (parent_side = -1, child = 0+, child_side = 0+)
Case 3 only happens under refinement (need to invent data at internal child sides).
Parameters
template_elem An element of the type that we need to find the maps for
qrule The quadrature rule that we need to find the maps for
qrule_face The face quadrature rule that we need to find the maps for
refinement_map The map to use when an element gets split
coarsen_map The map to use when an element is coarsened.
parent_side - the id of the parent's side
child - the id of the child element
child_side - The id of the child's side
Definition at line 2358 of file MooseMesh.C.
{
  TIME_SECTION("findAdaptivityQpMaps", 5);
  ReplicatedMesh mesh(_communicator);
  mesh.skip_partitioning(true);
  unsigned int dim = template_elem->dim();
  mesh.set_mesh_dimension(dim);
  for (unsigned int i = 0; i < template_elem->n_nodes(); ++i)
    mesh.add_point(template_elem->point(i));
  Elem * elem = mesh.add_elem(Elem::build(template_elem->type()).release());
  for (unsigned int i = 0; i < template_elem->n_nodes(); ++i)
    elem->set_node(i) = mesh.node_ptr(i);
  std::unique_ptr<FEBase> fe(FEBase::build(dim, FEType()));
  fe->get_phi();
  const std::vector<Point> & q_points_volume = fe->get_xyz();
  std::unique_ptr<FEBase> fe_face(FEBase::build(dim, FEType()));
  fe_face->get_phi();
  const std::vector<Point> & q_points_face = fe_face->get_xyz();
  fe->attach_quadrature_rule(&qrule);
  fe_face->attach_quadrature_rule(&qrule_face);
  // The current q_points (locations in *physical* space)
  const std::vector<Point> * q_points;
  if (parent_side != -1)
  {
    fe_face->reinit(elem, parent_side);
    q_points = &q_points_face;
  }
  else
  {
    fe->reinit(elem);
    q_points = &q_points_volume;
  }
  std::vector<Point> parent_ref_points;
  FEInterface::inverse_map(elem->dim(), FEType(), elem, *q_points, parent_ref_points);
  MeshRefinement mesh_refinement(mesh);
  mesh_refinement.uniformly_refine(1);
  // A map from the child element index to the locations of all the child's quadrature points in
  // *reference* space. Note that we use a map here instead of a vector because the caller can
  // pass an explicit child index. We are not guaranteed to have a sequence from [0, n_children)
  std::map<unsigned int, std::vector<Point>> child_to_ref_points;
  unsigned int n_children = elem->n_children();
  refinement_map.resize(n_children);
  std::vector<unsigned int> children;
  if (child != -1) // Passed in a child explicitly
    children.push_back(child);
  else
  {
    children.resize(n_children);
    for (unsigned int child = 0; child < n_children; ++child)
      children[child] = child;
  }
  for (unsigned int i = 0; i < children.size(); ++i)
  {
    unsigned int child = children[i];
    if ((parent_side != -1 && !elem->is_child_on_side(child, parent_side)))
      continue;
    const Elem * child_elem = elem->child_ptr(child);
    if (child_side != -1)
    {
      fe_face->reinit(child_elem, child_side);
      q_points = &q_points_face;
    }
    else
    {
      fe->reinit(child_elem);
      q_points = &q_points_volume;
    }
    std::vector<Point> child_ref_points;
    FEInterface::inverse_map(elem->dim(), FEType(), elem, *q_points, child_ref_points);
    child_to_ref_points[child] = child_ref_points;
    std::vector<QpMap> & qp_map = refinement_map[child];
    // Find the closest parent_qp to each child_qp
    mapPoints(child_ref_points, parent_ref_points, qp_map);
  }
  coarsen_map.resize(parent_ref_points.size());
  // For each parent qp find the closest child qp
  for (unsigned int child = 0; child < n_children; child++)
  {
    if (parent_side != -1 && !elem->is_child_on_side(child, child_side))
      continue;
    std::vector<Point> & child_ref_points = child_to_ref_points[child];
    std::vector<QpMap> qp_map;
    // Find all of the closest points from parent_qp to _THIS_ child's qp
    mapPoints(parent_ref_points, child_ref_points, qp_map);
    // Check those to see if they are closer than what we currently have for each point
    for (unsigned int parent_qp = 0; parent_qp < parent_ref_points.size(); ++parent_qp)
    {
      std::pair<unsigned int, QpMap> & child_and_map = coarsen_map[parent_qp];
      unsigned int & closest_child = child_and_map.first;
      QpMap & closest_map = child_and_map.second;
      QpMap & current_map = qp_map[parent_qp];
      if (current_map._distance < closest_map._distance)
      {
        closest_child = child;
        closest_map = current_map;
      }
    }
  }
}
Referenced by MooseMesh::buildCoarseningMap(), and MooseMesh::buildRefinementMap().
freeBndElems()
void MooseMesh::freeBndElems () protected inherited
Definition at line 348 of file MooseMesh.C.
{
  // free memory
  for (auto & belem : _bnd_elems)
    delete belem;
  for (auto & it : _bnd_elem_ids)
    it.second.clear();
  _bnd_elem_ids.clear();
}
Referenced by MooseMesh::buildBndElemList(), and MooseMesh::~MooseMesh().
freeBndNodes()
void MooseMesh::freeBndNodes () protected inherited
Definition at line 330 of file MooseMesh.C.
{
  // free memory
  for (auto & bnode : _bnd_nodes)
    delete bnode;
  for (auto & it : _node_set_nodes)
    it.second.clear();
  _node_set_nodes.clear();
  for (auto & it : _bnd_node_ids)
    it.second.clear();
  _bnd_node_ids.clear();
}
Referenced by MooseMesh::buildNodeList(), and MooseMesh::~MooseMesh().
getActiveLocalElementRange()
ConstElemRange * MooseMesh::getActiveLocalElementRange () inherited
Return pointers to range objects for various types of ranges (local nodes, boundary elems, etc.).
Definition at line 1035 of file MooseMesh.C.
{
  if (!_active_local_elem_range)
  {
    TIME_SECTION("getActiveLocalElementRange", 5);
    _active_local_elem_range = std::make_unique<ConstElemRange>(
        getMesh().active_local_elements_begin(), getMesh().active_local_elements_end(), GRAIN_SIZE);
  }
  return _active_local_elem_range.get();
}
Referenced by DumpObjectsProblem::addAuxVariable(), NonlinearSystemBase::computeDamping(), AuxiliarySystem::computeElementalVarsHelper(), FEProblemBase::computeIndicators(), NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), FEProblemBase::computeMarkers(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::computeResidualInternal(), FEProblemBase::computeUserObjectsInternal(), PointwiseRenormalizeVector::execute(), WorkBalance::execute(), LayeredBase::getBounds(), MooseMesh::meshChanged(), DOFMapOutput::output(), MeshInfo::possiblyAddSubdomainInfo(), FEProblemBase::projectSolution(), SystemBase::setVariableGlobalDoFs(), FixedPointSolve::solve(), TransientMultiApp::solveStep(), MooseMesh::updateActiveSemiLocalNodeRange(), Adaptivity::updateErrorVectors(), FEProblemBase::updateMaxQps(), and SystemBase::zeroVariables().
getActiveNodeRange()
NodeRange * MooseMesh::getActiveNodeRange () inherited
Definition at line 1049 of file MooseMesh.C.
{
  if (!_active_node_range)
  {
    TIME_SECTION("getActiveNodeRange", 5);
    _active_node_range = std::make_unique<NodeRange>(
        getMesh().active_nodes_begin(), getMesh().active_nodes_end(), GRAIN_SIZE);
  }
  return _active_node_range.get();
}
Referenced by VariableCondensationPreconditioner::getDofToCondense(), and MooseMesh::meshChanged().
getActiveSemiLocalNodeRange()
SemiLocalNodeRange * MooseMesh::getActiveSemiLocalNodeRange () const inherited
Definition at line 1063 of file MooseMesh.C.
{
  mooseAssert(_active_semilocal_node_range,
              "_active_semilocal_node_range has not been created yet!");
  return _active_semilocal_node_range.get();
}
getAllElemIDs()
std::set< dof_id_type > MooseMesh::getAllElemIDs (unsigned int elem_id_index) const inherited
Return all the unique element IDs for an extra element integer with its index.
Definition at line 926 of file MooseMesh.C.
{
  std::set<dof_id_type> unique_ids;
  for (auto & pair : _block_id_mapping[elem_id_index])
    for (auto & id : pair.second)
      unique_ids.insert(id);
  return unique_ids;
}
Referenced by MooseMesh::getElemIDMapping().
getAxisymmetricRadialCoord()
unsigned int MooseMesh::getAxisymmetricRadialCoord () const inherited
Returns the desired radial direction for RZ coordinate transformation.
Returns
The coordinate direction for the radial direction
Definition at line 3992 of file MooseMesh.C.
{
  if (usingGeneralAxisymmetricCoordAxes())
    mooseError("getAxisymmetricRadialCoord() should not be called if "
               "setGeneralAxisymmetricCoordAxes() has been called.");
  if (_rz_coord_axis == 0)
    return 1; // if the rotation axis is x (0), then the radial direction is y (1)
  else
    return 0; // otherwise the radial direction is assumed to be x, i.e., the rotation axis is y
}
Referenced by coordTransformFactor(), SubProblem::getAxisymmetricRadialCoord(), and Moose::FV::greenGaussGradient().
getBlockConnectedBlocks()
const std::set< SubdomainID > & MooseMesh::getBlockConnectedBlocks (const SubdomainID subdomain_id) const inherited
Get the list of subdomains neighboring a given subdomain.
Parameters
subdomain_id The boundary ID you want to get the subdomain IDs for.
Returns
All subdomain IDs neighboring a given subdomain
Definition at line 3295 of file MooseMesh.C.
{
  auto it = _sub_to_neighbor_subs.find(subdomain_id);
  if (it == _sub_to_neighbor_subs.end())
    mooseError("Unable to find subdomain ID: ", subdomain_id, '.');
  return it->second;
}
getBlocksMaxDimension()
unsigned int MooseMesh::getBlocksMaxDimension (const std::vector< SubdomainName > & blocks) const inherited
Returns the maximum element dimension on the given blocks.
Definition at line 2689 of file MooseMesh.C.
{
  const auto & mesh = getMesh();
  // Take a shortcut if possible
  if (const auto & elem_dims = mesh.elem_dimensions(); mesh.is_prepared() && elem_dims.size() == 1)
    return *elem_dims.begin();
  unsigned short dim = 0;
  const auto subdomain_ids = getSubdomainIDs(blocks);
  const std::set<SubdomainID> subdomain_ids_set(subdomain_ids.begin(), subdomain_ids.end());
  for (const auto & elem : mesh.active_subdomain_set_elements_ptr_range(subdomain_ids_set))
    dim = std::max(dim, elem->dim());
  // Get the maximumal globally
  _communicator.max(dim);
  return dim;
}
Referenced by BlockRestrictable::initializeBlockRestrictable().
getBoundariesToActiveSemiLocalElemIds()
const std::unordered_map< boundary_id_type, std::unordered_set< dof_id_type > > & MooseMesh::getBoundariesToActiveSemiLocalElemIds () const inherited
Returns a map of boundaries to ids of elements on the boundary.
Definition at line 1122 of file MooseMesh.C.
{
  return _bnd_elem_ids;
}
Referenced by MooseMesh::getBoundariesToElems().
getBoundariesToElems()
const std::unordered_map< boundary_id_type, std::unordered_set< dof_id_type > > & MooseMesh::getBoundariesToElems () const inherited
Returns a map of boundaries to ids of elements on the boundary.
Definition at line 1114 of file MooseMesh.C.
{
  mooseDeprecated("MooseMesh::getBoundariesToElems is deprecated, "
                  "use MooseMesh::getBoundariesToActiveSemiLocalElemIds");
  return getBoundariesToActiveSemiLocalElemIds();
}
getBoundaryActiveNeighborElemIds()
std::unordered_set< dof_id_type > MooseMesh::getBoundaryActiveNeighborElemIds (BoundaryID bid) const inherited
Return all ids of neighbors of elements which have a side which is part of a sideset.
Note that boundaries are sided, this is on the neighbor side. For the sideset side, use getBoundariesActiveLocalElemIds. Note that while the element is local and active, the neighbor is not guaranteed to be local, it could be ghosted. Note that if the neighbor is not ghosted, is a remote_elem, then it will not be included
Parameters
bid the id of the sideset of interest
Definition at line 1139 of file MooseMesh.C.
{
  // Vector of boundary elems is updated every mesh update
  std::unordered_set<dof_id_type> neighbor_elems;
  for (const auto & bnd_elem : _bnd_elems)
  {
    const auto & [elem_ptr, elem_side, elem_bid] = *bnd_elem;
    if (elem_bid == bid)
    {
      const auto * neighbor = elem_ptr->neighbor_ptr(elem_side);
      // Dont add fully remote elements, ghosted is fine
      if (neighbor && neighbor != libMesh::remote_elem)
      {
        // handle mesh refinement, only return active elements near the boundary
        if (neighbor->active())
          neighbor_elems.insert(neighbor->id());
        else
        {
          std::vector<const Elem *> family;
          neighbor->active_family_tree_by_neighbor(family, elem_ptr);
          for (const auto & child_neighbor : family)
            neighbor_elems.insert(child_neighbor->id());
        }
      }
    }
  }
  return neighbor_elems;
}
getBoundaryActiveSemiLocalElemIds()
std::unordered_set< dof_id_type > MooseMesh::getBoundaryActiveSemiLocalElemIds (BoundaryID bid) const inherited
Return all ids of elements which have a side which is part of a sideset.
Note that boundaries are sided.
Parameters
bid the id of the sideset of interest
Definition at line 1128 of file MooseMesh.C.
{
  // The boundary to element map is computed on every mesh update
  const auto it = _bnd_elem_ids.find(bid);
  if (it == _bnd_elem_ids.end())
    // Boundary is not local to this domain, return an empty set
    return std::unordered_set<dof_id_type>{};
  return it->second;
}
getBoundaryConnectedBlocks()
std::set< SubdomainID > MooseMesh::getBoundaryConnectedBlocks (const BoundaryID bid) const inherited
Get the list of subdomains associated with the given boundary.
Parameters
bid The boundary ID you want to get the subdomain IDs for.
Returns
All subdomain IDs associated with given boundary ID
Definition at line 3262 of file MooseMesh.C.
{
  std::set<SubdomainID> subdomain_ids;
  for (const auto & it : _subdomain_boundary_ids)
    if (it.second.find(bid) != it.second.end())
      subdomain_ids.insert(it.first);
  return subdomain_ids;
}
Referenced by DomainUserObject::DomainUserObject(), and MooseMesh::getInterfaceConnectedBlocks().
getBoundaryConnectedSecondaryBlocks()
std::set< SubdomainID > MooseMesh::getBoundaryConnectedSecondaryBlocks (const BoundaryID bid) const inherited
Get the list of subdomains associated with the given boundary of its secondary side.
Parameters
bid The boundary ID you want to get the subdomain IDs for.
Returns
All subdomain IDs associated with given boundary ID
Definition at line 3273 of file MooseMesh.C.
{
  std::set<SubdomainID> subdomain_ids;
  for (const auto & it : _neighbor_subdomain_boundary_ids)
    if (it.second.find(bid) != it.second.end())
      subdomain_ids.insert(it.first);
  return subdomain_ids;
}
Referenced by DomainUserObject::DomainUserObject().
getBoundaryElementRange()
ConstBndElemRange * MooseMesh::getBoundaryElementRange () inherited
Definition at line 1100 of file MooseMesh.C.
{
  if (!_bnd_elem_range)
  {
    TIME_SECTION("getBoundaryElementRange", 5);
    _bnd_elem_range =
        std::make_unique<ConstBndElemRange>(bndElemsBegin(), bndElemsEnd(), GRAIN_SIZE);
  }
  return _bnd_elem_range.get();
}
Referenced by DumpObjectsProblem::addAuxVariable(), AuxiliarySystem::computeElementalVarsHelper(), DMMooseGetEmbedding_Private(), GeometricSearchData::generateQuadratureNodes(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MooseMesh::meshChanged(), and GeometricSearchData::updateQuadratureNodes().
getBoundaryID()
BoundaryID MooseMesh::getBoundaryID (const BoundaryName & boundary_name) const inherited
Get the associated BoundaryID for the boundary name.
Returns
param boundary_name The name of the boundary.
the boundary id from the passed boundary name.
Definition at line 1464 of file MooseMesh.C.
{
  if (boundary_name == "ANY_BOUNDARY_ID")
    mooseError("Please use getBoundaryIDs() when passing \"ANY_BOUNDARY_ID\"");
  return MooseMeshUtils::getBoundaryID(boundary_name, getMesh());
}
Referenced by AddPeriodicBCAction::act(), ConstraintWarehouse::addObject(), PatternedMesh::buildMesh(), StitchedMesh::buildMesh(), TiledMesh::buildMesh(), DMSetUp_Moose_Pre(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), GeometricSearchData::getNearestNodeLocator(), GeometricSearchData::getPenetrationLocator(), GeometricSearchData::getQuadratureNearestNodeLocator(), GeometricSearchData::getQuadraturePenetrationLocator(), LinearNodalConstraint::LinearNodalConstraint(), LowerBoundNodalKernel::LowerBoundNodalKernel(), NodalScalarKernel::NodalScalarKernel(), AugmentSparsityOnInterface::operator()(), SetupMeshAction::setupMesh(), EqualValueBoundaryConstraint::updateConstrainedNodes(), and UpperBoundNodalKernel::UpperBoundNodalKernel().
getBoundaryIDs() [1/3]
const std::set< BoundaryID > & MooseMesh::getBoundaryIDs () const inherited
Returns a const reference to a set of all user-specified boundary IDs.
On a distributed mesh this will only include boundary IDs which exist on local or ghosted elements; a copy and a call to _communicator.set_union() will be necessary to get the global ID set.
Definition at line 2717 of file MooseMesh.C.
{
  return getMesh().get_boundary_info().get_boundary_ids();
}
Referenced by MooseMesh::cacheInfo().
getBoundaryIDs() [2/3]
std::vector< BoundaryID > MooseMesh::getBoundaryIDs (const Elem *const elem, const unsigned short int side) const inherited
Returns a vector of boundary IDs for the requested element on the requested side.
Definition at line 2709 of file MooseMesh.C.
{
  std::vector<BoundaryID> ids;
  getMesh().get_boundary_info().boundary_ids(elem, side, ids);
  return ids;
}
Referenced by NonlinearSystemBase::computeJacobianInternal(), DGKernelBase::DGKernelBase(), DGKernelBase::excludeBoundary(), MultiAppUserObjectTransfer::execute(), BoundaryRestrictable::hasBoundary(), BoundaryRestrictable::initializeBoundaryRestrictable(), BoundaryRestrictable::meshBoundaryIDs(), ElementSubdomainModifier::setComplementMovingBoundaryName(), ElementSubdomainModifier::setMovingBoundaryName(), and ActivateElementsUserObjectBase::setNewBoundayName().
getBoundaryIDs() [3/3]
std::vector< BoundaryID > MooseMesh::getBoundaryIDs (const std::vector< BoundaryName > & boundary_name, bool generate_unknown = false) const inherited
Get the associated BoundaryID for the boundary names that are passed in.
Returns
param boundary_name The names of the boundaries.
the boundary ids from the passed boundary names.
Definition at line 1495 of file MooseMesh.C.
{
  return MooseMeshUtils::getBoundaryIDs(
      getMesh(), boundary_name, generate_unknown, _mesh_boundary_ids);
}
getBoundaryName()
const std::string & MooseMesh::getBoundaryName (BoundaryID boundary_id) inherited
Return the name of the boundary given the id.
Definition at line 1556 of file MooseMesh.C.
{
  BoundaryInfo & boundary_info = getMesh().get_boundary_info();
  // We need to figure out if this boundary is a sideset or nodeset
  if (boundary_info.get_side_boundary_ids().count(boundary_id))
    return boundary_info.get_sideset_name(boundary_id);
  else
    return boundary_info.get_nodeset_name(boundary_id);
}
Referenced by DumpObjectsProblem::addAuxVariable(), BoundaryElemIntegrityCheckThread::operator()(), NonlinearThread::printBoundaryExecutionInformation(), and MaterialPropertyDebugOutput::printMaterialMap().
getBoundaryNodeRange()
ConstBndNodeRange * MooseMesh::getBoundaryNodeRange () inherited
Definition at line 1086 of file MooseMesh.C.
{
  if (!_bnd_node_range)
  {
    TIME_SECTION("getBoundaryNodeRange", 5);
    _bnd_node_range =
        std::make_unique<ConstBndNodeRange>(bndNodesBegin(), bndNodesEnd(), GRAIN_SIZE);
  }
  return _bnd_node_range.get();
}
Referenced by DumpObjectsProblem::addAuxVariable(), ElementSubdomainModifier::buildMovedBndNodesRange(), NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeMortarNodalVars(), NonlinearSystemBase::computeNodalBCs(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), AuxiliarySystem::computeNodalVarsHelper(), NonlinearSystemBase::computeResidualInternal(), DMMooseGetEmbedding_Private(), NearestNodeLocator::findNodes(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), ActivateElementsUserObjectBase::getNewlyActivatedBndNodeRange(), MooseMesh::meshChanged(), FEProblemBase::projectSolution(), NonlinearSystemBase::setInitialSolution(), and NearestNodeLocator::updatePatch().
getCheckedPointerParam()
template<typename T > T MooseBaseParameterInterface::getCheckedPointerParam (const std::string & name, const std::string & error_string = "") const inherited
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
The template parameter must be a pointer or an error will be thrown.
Definition at line 264 of file MooseBaseParameterInterface.h.
{
  return parameters().getCheckedPointerParam<T>(name, error_string);
}
getCoarseningMap()
const std::vector< std::pair< unsigned int, QpMap > > & MooseMesh::getCoarseningMap (const Elem & elem, int input_side) inherited
Get the coarsening map for a given element type.
This will tell you what quadrature points to copy from and to for stateful material properties on newly created elements from Adaptivity.
Parameters
elem The element that represents the element type you need the coarsening map for.
input_side The side to map
Definition at line 2316 of file MooseMesh.C.
{
  std::pair<int, ElemType> the_pair(input_side, elem.type());
  if (_elem_type_to_coarsening_map.find(the_pair) == _elem_type_to_coarsening_map.end())
    mooseError("Could not find a suitable qp refinement map!");
  return _elem_type_to_coarsening_map[the_pair];
}
Referenced by ProjectMaterialProperties::onBoundary(), and ProjectMaterialProperties::onElement().
getCoordSystem() [1/2]
const std::map< SubdomainID, Moose::CoordinateSystemType > & MooseMesh::getCoordSystem () const inherited
Get the map from subdomain ID to coordinate system type, e.g.
xyz, rz, or r-spherical
Definition at line 3905 of file MooseMesh.C.
{
  return _coord_sys;
}
Referenced by MooseMesh::setGeneralAxisymmetricCoordAxes().
getCoordSystem() [2/2]
Moose::CoordinateSystemType MooseMesh::getCoordSystem (SubdomainID sid) const inherited
Get the coordinate system type, e.g.
xyz, rz, or r-spherical, for the provided subdomain id sid
Definition at line 3873 of file MooseMesh.C.
{
  auto it = _coord_sys.find(sid);
  if (it != _coord_sys.end())
    return (*it).second;
  else
    mooseError("Requested subdomain ", sid, " does not exist.");
}
Referenced by coordTransformFactor(), SubProblem::getCoordSystem(), Moose::FV::greenGaussGradient(), and MooseAppCoordTransform::setCoordinateSystem().
getDataFileName()
std::string DataFileInterface< MooseObject >::getDataFileName (const std::string & param) const inherited
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
relative to the input file directory
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
relative to the input file directory
Definition at line 34 of file DataFileInterface.C.
{
  {
    const auto & absolute_path = _parent.template getParam<FileName>(param);
    if (MooseUtils::checkFileReadable(absolute_path, false, false, false))
    {
      _parent.paramInfo(param, "Data file '", absolute_path, "' found relative to the input file.");
      return absolute_path;
    }
  }
  const auto & relative_path = _parent.parameters().rawParamVal(param);
  return getDataFileNameByName(relative_path, &param);
}
getDataFileNameByName()
std::string DataFileInterface< MooseObject >::getDataFileNameByName (const std::string & name, const std::string * param = nullptr) const inherited
Returns the path of a data file for a given relative file path.
This can be used for hardcoded datafile names and will search the same locations as getDataFileName. The optional param pointer can be used to turn the mooseErrors this function emits into paramErrors
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
Definition at line 42 of file DataFileInterface.C.
{
  const auto share_dir = MooseUtils::pathjoin(Moose::getExecutablePath(), "..", "share");
  if (MooseUtils::pathIsDirectory(share_dir))
  {
    const auto dirs = MooseUtils::listDir(share_dir, false);
    for (const auto & data_dir : dirs)
    {
      const auto path = MooseUtils::pathjoin(data_dir, "data", relative_path);
      if (MooseUtils::checkFileReadable(path, false, false, false))
      {
        if (param)
          _parent.paramInfo(
              *param, "Data file '", path, "' found in an installed app distribution.");
        else
          mooseInfo("Data file '", path, "' found in an installed app distribution.");
        return path;
      }
    }
  }
  for (const auto & data_dir : Registry::getRegistry().getDataFilePaths())
  {
    const auto path = MooseUtils::pathjoin(data_dir, relative_path);
    if (MooseUtils::checkFileReadable(path, false, false, false))
    {
      if (param)
        _parent.paramInfo(*param, "Data file '", path, "' found in a source repository.");
      else
        mooseInfo("Data file '", path, "' found in a source repository.");
      return path;
    }
  }
  mooseException(param ? _parent.parameters().inputLocation(*param) : _parent.name(),
                 ": Unable to find data file '",
                 relative_path,
                 "' anywhere");
}
getElementIDIndex()
unsigned int MooseMesh::getElementIDIndex (const std::string & id_name) const inline inherited
Return the accessing integer for an extra element integer with its name.
Definition at line 2056 of file MooseMesh.h.
{
  if (!hasElementID(id_name))
    mooseError("Mesh does not have element ID for ", id_name);
  return getMesh().get_elem_integer_index(id_name);
}
Referenced by MooseMesh::areElemIDsIdentical().
getElemIDMapping()
std::unordered_map< dof_id_type, std::set< dof_id_type > > MooseMesh::getElemIDMapping (const std::string & from_id_name, const std::string & to_id_name) const inherited
Definition at line 897 of file MooseMesh.C.
{
  auto & mesh_base = getMesh();
  if (!mesh_base.has_elem_integer(from_id_name))
    mooseError("Mesh does not have the element integer name '", from_id_name, "'");
  if (!mesh_base.has_elem_integer(to_id_name))
    mooseError("Mesh does not have the element integer name '", to_id_name, "'");
  const auto id1 = mesh_base.get_elem_integer_index(from_id_name);
  const auto id2 = mesh_base.get_elem_integer_index(to_id_name);
  std::unordered_map<dof_id_type, std::set<dof_id_type>> id_map;
  for (const auto id : getAllElemIDs(id1))
    id_map[id] = std::set<dof_id_type>();
  for (const auto & elem : mesh_base.active_local_element_ptr_range())
    id_map[elem->get_extra_integer(id1)].insert(elem->get_extra_integer(id2));
  for (auto & [id, ids] : id_map)
  {
    libmesh_ignore(id); // avoid overzealous gcc 9.4 unused var warning
    comm().set_union(ids);
  }
  return id_map;
}
getElemIDsOnBlocks()
std::set< dof_id_type > MooseMesh::getElemIDsOnBlocks (unsigned int elem_id_index, const std::set< SubdomainID > & blks) const inherited
Return all the unique element IDs for an extra element integer with its index on a set of subdomains.
Definition at line 936 of file MooseMesh.C.
{
  std::set<dof_id_type> unique_ids;
  for (auto & blk : blks)
  {
    auto it = _block_id_mapping[elem_id_index].find(blk);
    if (it == _block_id_mapping[elem_id_index].end())
      mooseError("Block ", blk, " is not available on the mesh");
    for (auto & mid : it->second)
      unique_ids.insert(mid);
  }
  return unique_ids;
}
getFileName()
virtual std::string MooseMesh::getFileName () const inline virtual inherited
Returns the name of the mesh file read to produce this mesh if any or an empty string otherwise.
Reimplemented in FileMesh, and TiledMesh.
Definition at line 1046 of file MooseMesh.h.
{ return ""; }
getGeneralAxisymmetricCoordAxis()
const std::pair< Point, RealVectorValue > & MooseMesh::getGeneralAxisymmetricCoordAxis (SubdomainID subdomain_id) const inherited
Gets the general axisymmetric coordinate axis for a block.
Parameters
[in] subdomain_id Subdomain ID for which to get axisymmetric coordinate axis
Definition at line 3967 of file MooseMesh.C.
{
  auto it = _subdomain_id_to_rz_coord_axis.find(subdomain_id);
  if (it != _subdomain_id_to_rz_coord_axis.end())
    return (*it).second;
  else
    mooseError("Requested subdomain ", subdomain_id, " does not exist.");
}
Referenced by coordTransformFactor().
getGhostedBoundaries()
const std::set< unsigned int > & MooseMesh::getGhostedBoundaries () const inherited
Return a writable reference to the set of ghosted boundary IDs.
Definition at line 2981 of file MooseMesh.C.
{
  return _ghosted_boundaries;
}
getGhostedBoundaryInflation()
const std::vector< Real > & MooseMesh::getGhostedBoundaryInflation () const inherited
Return a writable reference to the _ghosted_boundaries_inflation vector.
Definition at line 2987 of file MooseMesh.C.
{
  return _ghosted_boundaries_inflation;
}
Referenced by NearestNodeLocator::findNodes(), and NearestNodeLocator::updatePatch().
getGhostingPatchSize()
unsigned int MooseMesh::getGhostingPatchSize () const inline inherited
Getter for the ghosting_patch_size parameter.
Definition at line 608 of file MooseMesh.h.
{ return _ghosting_patch_size; }
Referenced by NearestNodeLocator::findNodes(), and NearestNodeLocator::updatePatch().
getHigherDSide()
unsigned int MooseMesh::getHigherDSide (const Elem * elem) const inherited
Returns the local side ID of the interior parent aligned with the lower dimensional element.
Definition at line 1484 of file MooseMesh.C.
{
  auto it = _lower_d_elem_to_higher_d_elem_side.find(elem);
  if (it != _lower_d_elem_to_higher_d_elem_side.end())
    return it->second;
  else
    return libMesh::invalid_uint;
}
getInflatedProcessorBoundingBox()
BoundingBox MooseMesh::getInflatedProcessorBoundingBox (Real inflation_multiplier = 0.01) const inherited
Get a (slightly inflated) processor bounding box.
Parameters
inflation_multiplier This amount will be multiplied by the length of the diagonal of the bounding box to find the amount to inflate the bounding box by in all directions.
Definition at line 3159 of file MooseMesh.C.
{
  // Grab a bounding box to speed things up.  Note that
  // local_bounding_box is *not* equivalent to processor_bounding_box
  // with processor_id() except in serial.
  BoundingBox bbox = MeshTools::create_local_bounding_box(getMesh());
  // Inflate the bbox just a bit to deal with roundoff
  // Adding 1% of the diagonal size in each direction on each end
  Real inflation_amount = inflation_multiplier * (bbox.max() - bbox.min()).norm();
  Point inflation(inflation_amount, inflation_amount, inflation_amount);
  bbox.first -= inflation;  // min
  bbox.second += inflation; // max
  return bbox;
}
Referenced by PointVariableSamplerBase::execute(), PositionsFunctorValueSampler::execute(), CartesianGridDivision::initialize(), and RadialAverage::updateCommunicationLists().
getInterfaceConnectedBlocks()
std::set< SubdomainID > MooseMesh::getInterfaceConnectedBlocks (const BoundaryID bid) const inherited
Get the list of subdomains contacting the given boundary.
Parameters
bid The boundary ID you want to get the subdomain IDs for.
Returns
All subdomain IDs contacting given boundary ID
Definition at line 3284 of file MooseMesh.C.
{
  std::set<SubdomainID> subdomain_ids = getBoundaryConnectedBlocks(bid);
  for (const auto & it : _neighbor_subdomain_boundary_ids)
    if (it.second.find(bid) != it.second.end())
      subdomain_ids.insert(it.first);
  return subdomain_ids;
}
getLocalNodeRange()
ConstNodeRange * MooseMesh::getLocalNodeRange () inherited
Definition at line 1072 of file MooseMesh.C.
{
  if (!_local_node_range)
  {
    TIME_SECTION("getLocalNodeRange", 5);
    _local_node_range = std::make_unique<ConstNodeRange>(
        getMesh().local_nodes_begin(), getMesh().local_nodes_end(), GRAIN_SIZE);
  }
  return _local_node_range.get();
}
Referenced by DumpObjectsProblem::addAuxVariable(), NonlinearSystemBase::computeDamping(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeNodalVarsHelper(), NonlinearSystemBase::computeResidualInternal(), FEProblemBase::computeUserObjectsInternal(), WorkBalance::execute(), and MooseMesh::meshChanged().
getLowerDElem()
const Elem * MooseMesh::getLowerDElem (const Elem * elem, unsigned short int side) const inherited
Returns a const pointer to a lower dimensional element that corresponds to a side of a higher dimensional element.
This relationship is established through an internal_parent; if there is no lowerDElem, nullptr is returned.
Definition at line 1473 of file MooseMesh.C.
{
  auto it = _higher_d_elem_side_to_lower_d_elem.find(std::make_pair(elem, side));
  if (it != _higher_d_elem_side_to_lower_d_elem.end())
    return it->second;
  else
    return nullptr;
}
Referenced by GhostLowerDElems::operator()(), DisplacedProblem::reinitElemNeighborAndLowerD(), and FEProblemBase::reinitElemNeighborAndLowerD().
getLowerDElemMap()
const std::unordered_map< std::pair< const Elem *, unsigned short int >, const Elem * > & MooseMesh::getLowerDElemMap () const inline inherited
This function attempts to return the map from a high-order element side to its corresponding lower-d element.
Definition at line 2090 of file MooseMesh.h.
{
  return _higher_d_elem_side_to_lower_d_elem;
}
getMaxInDimension()
Real MooseMesh::getMaxInDimension (unsigned int component) const virtual inherited
Reimplemented in AnnularMesh, and GeneratedMesh.
Definition at line 1954 of file MooseMesh.C.
{
  mooseAssert(_mesh, "The MeshBase has not been constructed");
  mooseAssert(component < _bounds.size(), "Requested dimension out of bounds");
  return _bounds[component][MAX];
}
Referenced by MooseMesh::dimensionWidth(), AnnularMesh::getMaxInDimension(), GeneratedMesh::getMaxInDimension(), and PropertyReadFile::PropertyReadFile().
getMaxLeafSize()
unsigned int MooseMesh::getMaxLeafSize () const inline inherited
Getter for the maximum leaf size parameter.
Definition at line 613 of file MooseMesh.h.
{ return _max_leaf_size; }
Referenced by NearestNodeLocator::findNodes(), and NearestNodeLocator::updatePatch().
getMesh() [1/4]
MeshBase & MooseMesh::getMesh () inherited
Accessor for the underlying libMesh Mesh object.
Definition at line 3188 of file MooseMesh.C.
{
  mooseAssert(_mesh, "Mesh hasn't been created");
  return *_mesh;
}
Referenced by AddPeriodicBCAction::act(), MooseMesh::activeLocalElementsBegin(), MooseMesh::activeLocalElementsEnd(), Adaptivity::adaptMesh(), FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), MooseMesh::addQuadratureNode(), MooseMesh::addUniqueNode(), DumpObjectsProblem::addVariable(), MultiAppConservativeTransfer::adjustTransferredSolution(), MultiAppConservativeTransfer::adjustTransferredSolutionNearestPoint(), NonlinearSystemBase::assembleScalingVector(), Assembly::Assembly(), MooseApp::attachRelationshipManagers(), MooseMesh::buildActiveSideList(), MooseMesh::buildBndElemList(), MooseMesh::buildElemIDInfo(), MooseMesh::buildFiniteVolumeInfo(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildLowerDMesh(), AnnularMesh::buildMesh(), ConcentricCircleMesh::buildMesh(), FileMesh::buildMesh(), GeneratedMesh::buildMesh(), PatternedMesh::buildMesh(), RinglebMesh::buildMesh(), buildMesh(), StitchedMesh::buildMesh(), TiledMesh::buildMesh(), ImageMesh::buildMesh2D(), ImageMesh::buildMesh3D(), MooseMesh::buildNodeList(), MooseMesh::buildNodeListFromSideList(), MooseMesh::buildPeriodicNodeMap(), MooseMesh::buildPeriodicNodeSets(), MooseMesh::buildPRefinementAndCoarseningMaps(), MooseMesh::buildSideList(), MooseMesh::cacheChangedLists(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), MooseMesh::cacheInfo(), MooseMesh::changeBoundaryId(), MooseMesh::checkCoordinateSystems(), MultiAppGeometricInterpolationTransfer::computeTransformation(), NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), MortarData::createMortarInterface(), MooseMesh::detectOrthogonalDimRanges(), MooseMesh::detectPairedSidesets(), MooseMesh::dimension(), ExtraElementIntegerDivision::divisionIndex(), FunctorBinnedValuesDivision::divisionIndex(), SubdomainsDivision::divisionIndex(), DumpObjectsProblem::dumpVariableHelper(), ElementalVariableValue::ElementalVariableValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), MooseMesh::elemPtr(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), ElemSideNeighborLayersTester::execute(), NodalNormalsCorner::execute(), NodalNormalsPreprocessor::execute(), ExtraElementIntegerDivision::ExtraElementIntegerDivision(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), MultiAppGeometricInterpolationTransfer::fillSourceInterpolationPoints(), ActivateElementsUserObjectBase::finalize(), ElementSubdomainModifier::finalize(), MooseMesh::getActiveLocalElementRange(), MooseMesh::getActiveNodeRange(), MooseMesh::getBlocksMaxDimension(), MooseMesh::getBoundaryID(), MooseMesh::getBoundaryIDs(), MooseMesh::getBoundaryName(), MooseMesh::getElementIDIndex(), MooseMesh::getElemIDMapping(), MooseMesh::getInflatedProcessorBoundingBox(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MooseMesh::getLocalNodeRange(), SubProblem::getMaterialPropertyBlockNames(), SubProblem::getMaterialPropertyBoundaryNames(), MooseMesh::getNodeList(), FEProblemBase::getNonlinearEvaluableElementRange(), MooseMesh::getPointLocator(), MooseMesh::getSubdomainID(), MooseMesh::getSubdomainIDs(), MooseMesh::getSubdomainName(), MooseMesh::ghostGhostedBoundaries(), MooseMesh::hasElementID(), UpdateDisplacedMeshThread::init(), MooseMesh::init(), ExtraElementIntegerDivision::initialize(), ElementCentroidPositions::initialize(), ElementGroupCentroidPositions::initialize(), FunctorPositions::initialize(), FunctorTimes::initialize(), VerifyElementUniqueID::initialize(), VerifyNodalUniqueID::initialize(), Exodus::initialSetup(), NodalVariableValue::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), OversampleOutput::initOversample(), MultiAppGeometricInterpolationTransfer::interpolateTargetPoints(), LinearNodalConstraint::LinearNodalConstraint(), MooseMesh::localNodesBegin(), MooseMesh::localNodesEnd(), Moose::Mortar::loopOverMortarSegments(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseMesh::maxElemId(), MooseMesh::maxNodeId(), GeometryBase::meshChanged(), Nemesis::meshChanged(), GhostingUserObject::meshChanged(), RadialAverage::meshChanged(), MooseMesh::MooseMesh(), MooseMesh::nElem(), MooseMesh::nNodes(), NodalPatchRecovery::NodalPatchRecovery(), NodalVariableValue::NodalVariableValue(), MooseMesh::nodeToActiveSemilocalElemMap(), MooseMesh::nodeToElemMap(), MultiAppGeneralFieldTransfer::onBoundaries(), BoundaryNodeIntegrityCheckThread::onNode(), ComputeNodalUserObjectsThread::onNode(), MortarUserObjectThread::operator()(), ProxyRelationshipManager::operator()(), ComputeMortarFunctor::operator()(), XDA::output(), ConsoleUtils::outputMeshInformation(), MooseMesh::prepare(), EqualValueEmbeddedConstraint::prepareSecondaryToPrimaryMap(), BoundaryPreservedMarker::preserveBoundary(), MooseMesh::printInfo(), ActivateElementsUserObjectBase::push_boundary_node_info(), ActivateElementsUserObjectBase::push_boundary_side_info(), ElementSubdomainModifier::pushBoundaryNodeInfo(), ElementSubdomainModifier::pushBoundarySideInfo(), MooseMesh::queryElemPtr(), MooseMesh::queryNodePtr(), FileMesh::read(), PropertyReadFile::readData(), RedistributeProperties::redistribute(), SubProblem::restrictionBoundaryCheckName(), SubProblem::restrictionSubdomainCheckName(), MooseMesh::setBoundaryName(), ElementSubdomainModifier::setComplementMovingBoundaryName(), NonlinearSystemBase::setConstraintSecondaryValues(), XFEMInterface::setDisplacedMesh(), XFEMInterface::setMesh(), ElementSubdomainModifier::setMovingBoundaryName(), ActivateElementsUserObjectBase::setNewBoundayName(), Exodus::setOutputDimensionInExodusWriter(), MooseMesh::setPartitionerHelper(), MooseMesh::setSubdomainName(), ImageSampler::setupImageSampler(), SetupMeshAction::setupMesh(), MooseMesh::sideWithBoundaryID(), MultiAppGeometricInterpolationTransfer::subdomainIDsNode(), ElementSubdomainModifier::synchronizeBoundaryInfo(), MultiAppDofCopyTransfer::transfer(), DisplacedProblem::undisplaceMesh(), Adaptivity::uniformRefine(), MooseMesh::updateActiveSemiLocalNodeRange(), ActivateElementsUserObjectBase::updateBoundaryInfo(), ElementSubdomainModifier::updateComplementBoundaryInfo(), EqualValueBoundaryConstraint::updateConstrainedNodes(), Adaptivity::updateErrorVectors(), RandomData::updateGenerators(), DisplacedProblem::updateMesh(), ElementSubdomainModifier::updateMovingBoundaryInfo(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
getMesh() [2/4]
const MeshBase & MooseMesh::getMesh () const inherited
Definition at line 3195 of file MooseMesh.C.
{
  mooseAssert(_mesh, "Mesh hasn't been created");
  return *_mesh;
}
getMesh() [3/4]
MeshBase & MooseMesh::getMesh (const std::string & name) inherited
getMesh() [4/4]
const MeshBase & MooseMesh::getMesh (const std::string & name) const inherited
getMeshPtr()
const MeshBase * MooseMesh::getMeshPtr () const inherited
Definition at line 3182 of file MooseMesh.C.
{
  return _mesh.get();
}
Referenced by MooseApp::attachRelationshipManagers(), and AugmentSparsityOnInterface::operator()().
getMinInDimension()
Real MooseMesh::getMinInDimension (unsigned int component) const virtual inherited
Returns the min or max of the requested dimension respectively.
Reimplemented in AnnularMesh, and GeneratedMesh.
Definition at line 1945 of file MooseMesh.C.
{
  mooseAssert(_mesh, "The MeshBase has not been constructed");
  mooseAssert(component < _bounds.size(), "Requested dimension out of bounds");
  return _bounds[component][MIN];
}
Referenced by MooseMesh::dimensionWidth(), AnnularMesh::getMinInDimension(), GeneratedMesh::getMinInDimension(), and PropertyReadFile::PropertyReadFile().
getMooseApp()
MooseApp & MooseBase::getMooseApp () const inline inherited
Get the MooseApp this class is associated with.
Definition at line 35 of file MooseBase.h.
{ return _app; }
Referenced by ReporterTransferInterface::checkHasReporterValue(), Coupleable::checkWritableVar(), MooseBaseParameterInterface::connectControllableParams(), Coupleable::Coupleable(), MortarData::createMortarInterface(), EigenProblem::doFreeNonlinearPowerIterations(), Terminator::execute(), FEProblemSolve::FEProblemSolve(), SolutionInvalidInterface::flagInvalidSolutionInternal(), MaterialPropertyInterface::MaterialPropertyInterface(), MooseVariableDataFV< OutputType >::MooseVariableDataFV(), ProgressOutput::output(), MooseBaseParameterInterface::paramError(), PetscOutputInterface::petscLinearOutput(), PetscOutputInterface::petscNonlinearOutput(), PetscOutputInterface::PetscOutputInterface(), PostprocessorInterface::postprocessorsAdded(), MultiApp::preTransfer(), Reporter::Reporter(), ReporterInterface::reportersAdded(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
getNodeBlockIds()
const std::set< SubdomainID > & MooseMesh::getNodeBlockIds (const Node & node) const inherited
Return list of blocks to which the given node belongs.
Definition at line 1270 of file MooseMesh.C.
{
  std::map<dof_id_type, std::set<SubdomainID>>::const_iterator it =
      _block_node_list.find(node.id());
  if (it == _block_node_list.end())
    mooseError("Unable to find node: ", node.id(), " in any block list.");
  return it->second;
}
Referenced by MultiAppUserObjectTransfer::hasBlocks(), MultiAppGeneralFieldNearestLocationTransfer::inBlocks(), MultiAppGeneralFieldTransfer::inBlocks(), GeometryBase::meshChanged(), ComputeNodalKernelJacobiansThread::onNode(), ComputeNodalKernelsThread::onNode(), ComputeNodalUserObjectsThread::onNode(), ComputeInitialConditionThread::operator()(), and TopResidualDebugOutput::printTopResiduals().
getNodeList()
const std::vector< dof_id_type > & MooseMesh::getNodeList (boundary_id_type nodeset_id) const inherited
Return a writable reference to a vector of node IDs that belong to nodeset_id.
Definition at line 3210 of file MooseMesh.C.
{
  std::map<boundary_id_type, std::vector<dof_id_type>>::const_iterator it =
      _node_set_nodes.find(nodeset_id);
  if (it == _node_set_nodes.end())
  {
    // On a distributed mesh we might not know about a remote nodeset,
    // so we'll return an empty vector and hope the nodeset exists
    // elsewhere.
    if (!getMesh().is_serial())
    {
      static const std::vector<dof_id_type> empty_vec;
      return empty_vec;
    }
    // On a replicated mesh we should know about every nodeset and if
    // we're asked for one that doesn't exist then it must be a bug.
    else
    {
      mooseError("Unable to nodeset ID: ", nodeset_id, '.');
    }
  }
  return it->second;
}
Referenced by LinearNodalConstraint::LinearNodalConstraint(), GeometryBase::meshChanged(), NodalScalarKernel::NodalScalarKernel(), and EqualValueBoundaryConstraint::updateConstrainedNodes().
getNormalByBoundaryID()
const RealVectorValue & MooseMesh::getNormalByBoundaryID (BoundaryID id) const inherited
Returns the normal vector associated with a given BoundaryID.
It's only valid to call this when AddAllSideSetsByNormals is active.
Definition at line 2549 of file MooseMesh.C.
{
  mooseAssert(_boundary_to_normal_map.get() != nullptr, "Boundary To Normal Map not built!");
  // Note: Boundaries that are not in the map (existing boundaries) will default
  // construct a new RealVectorValue - (x,y,z)=(0, 0, 0)
  return (*_boundary_to_normal_map)[id];
}
getPairedBoundaryMapping()
const std::pair< BoundaryID, BoundaryID > * MooseMesh::getPairedBoundaryMapping (unsigned int component) inherited
This function attempts to return the paired boundary ids for the given component.
For example, in a generated 2D mesh, passing 0 for the "x" component will return (3, 1).
Parameters
component - An integer representing the desired component (dimension)
Returns
std::pair pointer - The matching boundary pairs for the passed component
Definition at line 2026 of file MooseMesh.C.
{
  if (!_regular_orthogonal_mesh)
    mooseError("Trying to retrieve automatic paired mapping for a mesh that is not regular and "
               "orthogonal");
  mooseAssert(component < dimension(), "Requested dimension out of bounds");
  if (_paired_boundary.empty())
    detectPairedSidesets();
  if (component < _paired_boundary.size())
    return &_paired_boundary[component];
  else
    return nullptr;
}
Referenced by MooseMesh::addPeriodicVariable(), and AddPeriodicBCAction::autoTranslationBoundaries().
getParam() [1/2]
template<typename T > const T & MooseBaseParameterInterface::getParam (const std::string & name) const inherited
Retrieve a parameter for the object.
Parameters
name The name of the parameter
Returns
The value of the parameter
Definition at line 200 of file MooseBaseParameterInterface.h.
{
  return InputParameters::getParamHelper(name, _pars, static_cast<T *>(0));
}
Referenced by AddGeneralReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddPeriodicBCAction::act(), CreateDisplacedProblemAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), ConstraintWarehouse::addObject(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), ADNodalKernel::ADNodalKernel(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), PiecewiseTabularBase::buildFromJSON(), Console::Console(), FEProblemBase::createTagSolutions(), AccumulateReporter::declareLateValues(), DerivativeParsedMaterialTempl< is_ad >::DerivativeParsedMaterialTempl(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EigenKernel::EigenKernel(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), GenericConstantRankTwoTensorTempl< is_ad >::GenericConstantRankTwoTensorTempl(), MooseApp::getCheckpointDirectories(), ExecutorInterface::getExecutor(), AdvancedOutput::init(), IterationAdaptiveDT::init(), TimeSequenceStepper::init(), AttribThread::initFrom(), AttribSysNum::initFrom(), AttribResidualObject::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), Console::initialSetup(), IterationAdaptiveDT::limitDTToPostprocessorValue(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MortarConsumerInterface::MortarConsumerInterface(), NestedDivision::NestedDivision(), ConsoleUtils::outputExecutionInformation(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedMaterialTempl< is_ad >::ParsedMaterialTempl(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), ParsedODEKernel::ParsedODEKernel(), ParsedPostprocessor::ParsedPostprocessor(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), Moose::FV::setInterpolationMethod(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), TimePeriod::TimePeriod(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and VectorOfPostprocessors::VectorOfPostprocessors().
getParam() [2/2]
template<typename T1 , typename T2 > std::vector< std::pair< T1, T2 > > MooseBaseParameterInterface::getParam (const std::string & param1, const std::string & param2) const inherited
Retrieve two parameters and provide pair of parameters for the object.
Parameters
param1 The name of first parameter
param2 The name of second parameter
Returns
Vector of pairs of first and second parameters
Definition at line 257 of file MooseBaseParameterInterface.h.
{
  return _pars.get<T1, T2>(param1, param2);
}
getPatchSize()
unsigned int MooseMesh::getPatchSize () const inherited
Getter for the patch_size parameter.
Definition at line 3141 of file MooseMesh.C.
{
  return _patch_size;
}
Referenced by NearestNodeLocator::findNodes(), and NearestNodeLocator::updatePatch().
getPatchUpdateStrategy()
const Moose::PatchUpdateType & MooseMesh::getPatchUpdateStrategy () const inherited
Get the current patch update strategy.
Definition at line 3153 of file MooseMesh.C.
{
  return _patch_update_strategy;
}
Referenced by FEProblemBase::possiblyRebuildGeomSearchPatches().
getPCoarseningMap()
const std::vector< QpMap > & MooseMesh::getPCoarseningMap (const Elem & elem) const inherited
Get the map describing for each volumetric quadrature point (qp) on the coarse level which qp on the previous finer level the coarse qp is closest to.
Definition at line 4090 of file MooseMesh.C.
{
  return getPCoarseningMapHelper(elem, _elem_type_to_p_coarsening_map);
}
Referenced by ProjectMaterialProperties::onElement().
getPCoarseningMapHelper()
const std::vector< QpMap > & MooseMesh::getPCoarseningMapHelper (const Elem & elem, const std::map< std::pair< ElemType, unsigned int >, std::vector< QpMap > > & map) const private inherited
Definition at line 4068 of file MooseMesh.C.
{
  mooseAssert(elem.active() && elem.p_refinement_flag() == Elem::JUST_COARSENED,
              "These are the conditions that should be met for requesting a coarsening map");
  return libmesh_map_find(map, std::make_pair(elem.type(), elem.p_level()));
}
Referenced by MooseMesh::getPCoarseningMap(), and MooseMesh::getPCoarseningSideMap().
getPCoarseningSideMap()
const std::vector< QpMap > & MooseMesh::getPCoarseningSideMap (const Elem & elem) const inherited
Get the map describing for each side quadrature point (qp) on the coarse level which qp on the previous finer level the coarse qp is closest to.
Definition at line 4096 of file MooseMesh.C.
{
  return getPCoarseningMapHelper(elem, _elem_type_to_p_coarsening_side_map);
}
Referenced by ProjectMaterialProperties::onBoundary().
getPointLocator()
std::unique_ptr< PointLocatorBase > MooseMesh::getPointLocator () const virtual inherited
Proxy function to get a (sub)PointLocator from either the underlying libMesh mesh (default), or to allow derived meshes to return a custom point locator.
Definition at line 3470 of file MooseMesh.C.
{
  return getMesh().sub_point_locator();
}
Referenced by PointValue::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), ElementsAlongLine::execute(), IntersectionPointsAlongLine::execute(), PointSamplerBase::initialize(), FindValueOnLine::initialize(), ReporterPointMarker::markerSetup(), and EqualValueEmbeddedConstraint::prepareSecondaryToPrimaryMap().
getPRefinementMap()
const std::vector< QpMap > & MooseMesh::getPRefinementMap (const Elem & elem) const inherited
Get the map describing for each volumetric quadrature point (qp) on the refined level which qp on the previous coarser level the fine qp is closest to.
Definition at line 4078 of file MooseMesh.C.
{
  return getPRefinementMapHelper(elem, _elem_type_to_p_refinement_map);
}
Referenced by ProjectMaterialProperties::onElement().
getPRefinementMapHelper()
const std::vector< QpMap > & MooseMesh::getPRefinementMapHelper (const Elem & elem, const std::map< std::pair< ElemType, unsigned int >, std::vector< QpMap > > & map) const private inherited
Definition at line 4055 of file MooseMesh.C.
{
  mooseAssert(elem.active() && elem.p_refinement_flag() == Elem::JUST_REFINED,
              "These are the conditions that should be met for requesting a refinement map");
  // We are actually seeking the map stored with the p_level - 1 key, e.g. the refinement map that
  // maps from the previous p_level to this element's p_level
  return libmesh_map_find(map,
                          std::make_pair(elem.type(), cast_int<unsigned int>(elem.p_level() - 1)));
}
Referenced by MooseMesh::getPRefinementMap(), and MooseMesh::getPRefinementSideMap().
getPRefinementSideMap()
const std::vector< QpMap > & MooseMesh::getPRefinementSideMap (const Elem & elem) const inherited
Get the map describing for each side quadrature point (qp) on the refined level which qp on the previous coarser level the fine qp is closest to.
Definition at line 4084 of file MooseMesh.C.
{
  return getPRefinementMapHelper(elem, _elem_type_to_p_refinement_side_map);
}
Referenced by ProjectMaterialProperties::onBoundary().
getQuadratureNode()
Node * MooseMesh::getQuadratureNode (const Elem * elem, const unsigned short int side, const unsigned int qp) inherited
Get a specified quadrature node.
Parameters
elem The element the quadrature point is on
side The side the quadrature point is on
qp The quadrature point number associated with the point
Definition at line 1434 of file MooseMesh.C.
{
  mooseAssert(_elem_to_side_to_qp_to_quadrature_nodes.find(elem->id()) !=
                  _elem_to_side_to_qp_to_quadrature_nodes.end(),
              "Elem has no quadrature nodes!");
  mooseAssert(_elem_to_side_to_qp_to_quadrature_nodes[elem->id()].find(side) !=
                  _elem_to_side_to_qp_to_quadrature_nodes[elem->id()].end(),
              "Side has no quadrature nodes!");
  mooseAssert(_elem_to_side_to_qp_to_quadrature_nodes[elem->id()][side].find(qp) !=
                  _elem_to_side_to_qp_to_quadrature_nodes[elem->id()][side].end(),
              "qp not found on side!");
  return _elem_to_side_to_qp_to_quadrature_nodes[elem->id()][side][qp];
}
Referenced by GapValueAux::computeValue(), NearestNodeDistanceAux::computeValue(), PenetrationAux::computeValue(), and GeometricSearchData::updateQuadratureNodes().
getRefinementMap()
const std::vector< std::vector< QpMap > > & MooseMesh::getRefinementMap (const Elem & elem, int parent_side, int child, int child_side) inherited
Get the refinement map for a given element type.
This will tell you what quadrature points to copy from and to for stateful material properties on newly created elements from Adaptivity.
Parameters
elem The element that represents the element type you need the refinement map for.
parent_side The side of the parent to map (-1 if not mapping parent sides)
child The child number (-1 if not mapping child internal sides)
child_side The side number of the child (-1 if not mapping sides)
TODO: When running with parallel mesh + stateful adaptivty we will need to make sure that each processor has a complete map. This may require parallel communication. This is likely to happen when running on a mixed element mesh.
Definition at line 2252 of file MooseMesh.C.
{
  if (child == -1) // Doing volume mapping or parent side mapping
  {
    mooseAssert(parent_side == child_side,
                "Parent side must match child_side if not passing a specific child!");
    std::pair<int, ElemType> the_pair(parent_side, elem.type());
    if (_elem_type_to_refinement_map.find(the_pair) == _elem_type_to_refinement_map.end())
      mooseError("Could not find a suitable qp refinement map!");
    return _elem_type_to_refinement_map[the_pair];
  }
  else // Need to map a child side to parent volume qps
  {
    std::pair<int, int> child_pair(child, child_side);
    if (_elem_type_to_child_side_refinement_map.find(elem.type()) ==
            _elem_type_to_child_side_refinement_map.end() ||
        _elem_type_to_child_side_refinement_map[elem.type()].find(child_pair) ==
            _elem_type_to_child_side_refinement_map[elem.type()].end())
      mooseError("Could not find a suitable qp refinement map!");
    return _elem_type_to_child_side_refinement_map[elem.type()][child_pair];
  }
}
Referenced by ProjectMaterialProperties::onBoundary(), ProjectMaterialProperties::onElement(), and ProjectMaterialProperties::onInternalSide().
getRenamedParam()
template<typename T > const T & MooseBaseParameterInterface::getRenamedParam (const std::string & old_name, const std::string & new_name) const inherited
Retrieve a renamed parameter for the object.
This helper makes sure we check both names before erroring, and that only one parameter is passed to avoid silent errors
Parameters
old_name the old name for the parameter
new_name the new name for the parameter
Definition at line 207 of file MooseBaseParameterInterface.h.
{
  // this enables having a default on the new parameter but bypassing it with the old one
  // Most important: accept new parameter
  if (isParamSetByUser(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Second most: accept old parameter
  else if (isParamValid(old_name) && !isParamSetByUser(new_name))
    return InputParameters::getParamHelper(old_name, _pars, static_cast<T *>(0));
  // Third most: accept default for new parameter
  else if (isParamValid(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Refuse: no default, no value passed
  else if (!isParamValid(old_name) && !isParamValid(new_name))
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' is being retrieved without being set.\n"
               "Did you misspell it?");
  // Refuse: both old and new parameters set by user
  else
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' may not be provided alongside former parameter '" + old_name + "'");
}
getRestartableData()
template<typename T , typename... Args> const T & Restartable::getRestartableData (const std::string & data_name) const protected inherited
Declare a piece of data as "restartable" and initialize it Similar to declareRestartableData but returns a const reference to the object.
Forwarded arguments are not allowed in this case because we assume that the object is restarted and we won't need different constructors to initialize it.
NOTE: This returns a const reference! Make sure you store it in a const reference!
Parameters
data_name The name of the data (usually just use the same name as the member variable)
Definition at line 287 of file Restartable.h.
{
  return declareRestartableDataHelper<T>(data_name, nullptr).get();
}
getSubdomainBoundaryIds()
const std::set< BoundaryID > & MooseMesh::getSubdomainBoundaryIds (const SubdomainID subdomain_id) const inherited
Get the list of boundary ids associated with the given subdomain id.
Parameters
subdomain_id The subdomain ID you want to get the boundary ids for.
Returns
All boundary IDs connected to elements in the give
Definition at line 3237 of file MooseMesh.C.
{
  std::unordered_map<SubdomainID, std::set<BoundaryID>>::const_iterator it =
      _subdomain_boundary_ids.find(subdomain_id);
  if (it == _subdomain_boundary_ids.end())
    mooseError("Unable to find subdomain ID: ", subdomain_id, '.');
  return it->second;
}
Referenced by MooseMesh::getSubdomainInterfaceBoundaryIds(), and FEProblemBase::prepareMaterials().
getSubdomainID()
SubdomainID MooseMesh::getSubdomainID (const SubdomainName & subdomain_name) const inherited
Get the associated subdomain ID for the subdomain name.
Parameters
subdomain_name The name of the subdomain
Returns
The subdomain id from the passed subdomain name.
Definition at line 1503 of file MooseMesh.C.
{
  return MooseMeshUtils::getSubdomainID(subdomain_name, getMesh());
}
Referenced by ConstraintWarehouse::addObject(), SystemBase::addVariable(), FVInterfaceKernel::FVInterfaceKernel(), SolutionIC::initialSetup(), AugmentSparsityOnInterface::operator()(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl(), MooseMesh::setCoordSystem(), and MooseMesh::setGeneralAxisymmetricCoordAxes().
getSubdomainIDs()
std::vector< SubdomainID > MooseMesh::getSubdomainIDs (const std::vector< SubdomainName > & subdomain_name) const inherited
Get the associated subdomainIDs for the subdomain names that are passed in.
Parameters
subdomain_name The names of the subdomains
Returns
The subdomain ids from the passed subdomain names.
Definition at line 1509 of file MooseMesh.C.
{
  return MooseMeshUtils::getSubdomainIDs(getMesh(), subdomain_name);
}
Referenced by MultiAppUserObjectTransfer::execute(), MooseMesh::getBlocksMaxDimension(), BlockRestrictable::hasBlocks(), SubdomainsDivision::initialize(), BlockRestrictable::initializeBlockRestrictable(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeometricInterpolationTransfer::interpolateTargetPoints(), and LayeredBase::LayeredBase().
getSubdomainInterfaceBoundaryIds()
std::set< BoundaryID > MooseMesh::getSubdomainInterfaceBoundaryIds (const SubdomainID subdomain_id) const inherited
Get the list of boundaries that contact the given subdomain.
Parameters
subdomain_id The subdomain ID you want to get the boundary ids for.
Returns
All boundary IDs connected to elements in the given subdomain
Definition at line 3249 of file MooseMesh.C.
{
  const auto & bnd_ids = getSubdomainBoundaryIds(subdomain_id);
  std::set<BoundaryID> boundary_ids(bnd_ids.begin(), bnd_ids.end());
  std::unordered_map<SubdomainID, std::set<BoundaryID>>::const_iterator it =
      _neighbor_subdomain_boundary_ids.find(subdomain_id);
  boundary_ids.insert(it->second.begin(), it->second.end());
  return boundary_ids;
}
getSubdomainName()
const std::string & MooseMesh::getSubdomainName (SubdomainID subdomain_id) const inherited
Return the name of a block given an id.
Definition at line 1527 of file MooseMesh.C.
{
  return getMesh().subdomain_name(subdomain_id);
}
Referenced by FEProblemBase::checkDependMaterialsHelper(), MooseMesh::checkDuplicateSubdomainNames(), DomainUserObject::checkVariable(), MooseMesh::getSubdomainNames(), NonlinearThread::printBlockExecutionInformation(), MaterialPropertyDebugOutput::printMaterialMap(), TopResidualDebugOutput::printTopResiduals(), and MooseMesh::setGeneralAxisymmetricCoordAxes().
getSubdomainNames()
std::vector< SubdomainName > MooseMesh::getSubdomainNames (const std::vector< SubdomainID > & subdomain_ids) const inherited
Get the associated subdomainNames for the subdomain ids that are passed in.
Parameters
subdomain_ids The ids of the subdomains
Returns
The subdomain names from the passed subdomain ids.
Definition at line 1533 of file MooseMesh.C.
{
  std::vector<SubdomainName> names(subdomain_ids.size());
  for (unsigned int i = 0; i < subdomain_ids.size(); i++)
    names[i] = getSubdomainName(subdomain_ids[i]);
  return names;
}
Referenced by NonlinearSystemBase::checkKernelCoverage(), and SolutionIC::initialSetup().
getUniqueCoordSystem()
Moose::CoordinateSystemType MooseMesh::getUniqueCoordSystem () const inherited
Get the coordinate system from the mesh, it must be the same in all subdomains otherwise this will error.
Definition at line 3883 of file MooseMesh.C.
{
  const auto unique_system = _coord_sys.find(*meshSubdomains().begin())->second;
  // Check that it is actually unique
  bool result = std::all_of(
      std::next(_coord_sys.begin()),
      _coord_sys.end(),
      [unique_system](
          typename std::unordered_map<SubdomainID, Moose::CoordinateSystemType>::const_reference
              item) { return (item.second == unique_system); });
  if (!result)
    mooseError("The unique coordinate system of the mesh was requested by the mesh contains "
               "multiple blocks with different coordinate systems");
  if (usingGeneralAxisymmetricCoordAxes())
    mooseError("General axisymmetric coordinate axes are being used, and it is currently "
               "conservatively assumed that in this case there is no unique coordinate system.");
  return unique_system;
}
ghostGhostedBoundaries()
void MooseMesh::ghostGhostedBoundaries () inherited
Actually do the ghosting of boundaries that need to be ghosted to this processor.
Definition at line 3054 of file MooseMesh.C.
{
  // No need to do this if using a serial mesh
  // We do not need to ghost boundary elements when _need_ghost_ghosted_boundaries
  // is not true. _need_ghost_ghosted_boundaries can be set by a mesh generator
  // where boundaries are already ghosted accordingly
  if (!_use_distributed_mesh || !_need_ghost_ghosted_boundaries)
    return;
  TIME_SECTION("GhostGhostedBoundaries", 3);
  parallel_object_only();
  DistributedMesh & mesh = dynamic_cast<DistributedMesh &>(getMesh());
  // We clear ghosted elements that were added by previous invocations of this
  // method but leave ghosted elements that were added by other code, e.g.
  // OversampleOutput, untouched
  mesh.clear_extra_ghost_elems(_ghost_elems_from_ghost_boundaries);
  _ghost_elems_from_ghost_boundaries.clear();
  std::set<const Elem *, CompareElemsByLevel> boundary_elems_to_ghost;
  std::set<Node *> connected_nodes_to_ghost;
  std::vector<const Elem *> family_tree;
  for (const auto & t : mesh.get_boundary_info().build_side_list())
  {
    auto elem_id = std::get<0>(t);
    auto bc_id = std::get<2>(t);
    if (_ghosted_boundaries.find(bc_id) != _ghosted_boundaries.end())
    {
      Elem * elem = mesh.elem_ptr(elem_id);
#ifdef LIBMESH_ENABLE_AMR
      elem->family_tree(family_tree);
      Elem * parent = elem->parent();
      while (parent)
      {
        family_tree.push_back(parent);
        parent = parent->parent();
      }
#else
      family_tree.clear();
      family_tree.push_back(elem);
#endif
      for (const auto & felem : family_tree)
      {
        boundary_elems_to_ghost.insert(felem);
        // The entries of connected_nodes_to_ghost need to be
        // non-constant, so that they will work in things like
        // UpdateDisplacedMeshThread. The container returned by
        // family_tree contains const Elems even when the Elem
        // it is called on is non-const, so once that interface
        // gets fixed we can remove this const_cast.
        for (unsigned int n = 0; n < felem->n_nodes(); ++n)
          connected_nodes_to_ghost.insert(const_cast<Node *>(felem->node_ptr(n)));
      }
    }
  }
  // We really do want to store this by value instead of by reference
  const auto prior_ghost_elems = mesh.extra_ghost_elems();
  mesh.comm().allgather_packed_range(&mesh,
                                     connected_nodes_to_ghost.begin(),
                                     connected_nodes_to_ghost.end(),
                                     extra_ghost_elem_inserter<Node>(mesh));
  mesh.comm().allgather_packed_range(&mesh,
                                     boundary_elems_to_ghost.begin(),
                                     boundary_elems_to_ghost.end(),
                                     extra_ghost_elem_inserter<Elem>(mesh));
  const auto & current_ghost_elems = mesh.extra_ghost_elems();
  std::set_difference(current_ghost_elems.begin(),
                      current_ghost_elems.end(),
                      prior_ghost_elems.begin(),
                      prior_ghost_elems.end(),
                      std::inserter(_ghost_elems_from_ghost_boundaries,
                                    _ghost_elems_from_ghost_boundaries.begin()));
}
Referenced by FEProblemBase::ghostGhostedBoundaries(), and SetupMeshAction::setupMesh().
hasElementID()
bool MooseMesh::hasElementID (const std::string & id_name) const inline inherited
Whether mesh has an extra element integer with a given name.
Definition at line 2050 of file MooseMesh.h.
{
  return getMesh().has_elem_integer(id_name);
}
Referenced by MooseMesh::getElementIDIndex().
hasMeshBase()
bool MooseMesh::hasMeshBase () const inline inherited
Whether mesh base object was constructed or not.
Definition at line 1079 of file MooseMesh.h.
{ return _mesh.get() != nullptr; }
Referenced by MeshGeneratorMesh::buildMesh().
hasSecondOrderElements()
bool MooseMesh::hasSecondOrderElements () inherited
check if the mesh has SECOND order elements
Definition at line 3448 of file MooseMesh.C.
{
  bool mesh_has_second_order_elements = false;
  for (auto it = activeLocalElementsBegin(), end = activeLocalElementsEnd(); it != end; ++it)
    if ((*it)->default_order() == SECOND)
    {
      mesh_has_second_order_elements = true;
      break;
    }
  // We checked our local elements, so take the max over all processors.
  comm().max(mesh_has_second_order_elements);
  return mesh_has_second_order_elements;
}
Referenced by Assembly::adCurvatures(), Assembly::Assembly(), Assembly::havePRefinement(), and MultiAppGeneralFieldNearestLocationTransfer::initialSetup().
init()
void MooseMesh::init () virtual inherited
Initialize the Mesh object.
Most of the time this will turn around and call build_mesh so the child class can build the Mesh object.
However, during Recovery this will read the CPA file...
If the mesh base hasn't been constructed by the time init is called, just do it here. This can happen if somebody builds a mesh outside of the normal Action system. Forcing developers to create, construct the MeshBase, and then init separately is a bit much for casual use but it gives us the ability to run MeshGenerators in-between.
Definition at line 2615 of file MooseMesh.C.
{
  if (!_mesh)
    _mesh = buildMeshBaseObject();
  if (_app.isSplitMesh() && _use_distributed_mesh)
    mooseError("You cannot use the mesh splitter capability with DistributedMesh!");
  TIME_SECTION("init", 2);
  if (_app.isRecovering() && _allow_recovery && _app.isUltimateMaster())
  {
    // Some partitioners are not idempotent.  Some recovery data
    // files require partitioning to match mesh partitioning.  This
    // means that, when recovering, we can't safely repartition.
    const bool skip_partitioning_later = getMesh().skip_partitioning();
    getMesh().skip_partitioning(true);
    const bool allow_renumbering_later = getMesh().allow_renumbering();
    getMesh().allow_renumbering(false);
    // For now, only read the recovery mesh on the Ultimate Master..
    // sub-apps need to just build their mesh like normal
    {
      TIME_SECTION("readRecoveredMesh", 2);
      getMesh().read(_app.getRestartRecoverFileBase() + MooseApp::checkpointSuffix());
    }
    getMesh().allow_renumbering(allow_renumbering_later);
    getMesh().skip_partitioning(skip_partitioning_later);
  }
  else // Normally just build the mesh
  {
    // Don't allow partitioning during building
    if (_app.isSplitMesh())
      getMesh().skip_partitioning(true);
    buildMesh();
    // Re-enable partitioning so the splitter can partition!
    if (_app.isSplitMesh())
      getMesh().skip_partitioning(false);
    if (getParam<bool>("build_all_side_lowerd_mesh"))
      buildLowerDMesh();
  }
}
isBoundaryElem() [1/2]
bool MooseMesh::isBoundaryElem (dof_id_type elem_id) const inherited
Returns true if the requested element is in the list of boundary elements, false otherwise.
Definition at line 3332 of file MooseMesh.C.
{
  bool found_elem = false;
  for (const auto & it : _bnd_elem_ids)
  {
    if (it.second.find(elem_id) != it.second.end())
    {
      found_elem = true;
      break;
    }
  }
  return found_elem;
}
Referenced by BoundaryMarker::computeElementMarker(), and MultiAppUserObjectTransfer::isBoundaryElem().
isBoundaryElem() [2/2]
bool MooseMesh::isBoundaryElem (dof_id_type elem_id, BoundaryID bnd_id) const inherited
Returns true if the requested element is in the list of boundary elements for the specified boundary, false otherwise.
Definition at line 3347 of file MooseMesh.C.
{
  bool found_elem = false;
  auto it = _bnd_elem_ids.find(bnd_id);
  if (it != _bnd_elem_ids.end())
    if (it->second.find(elem_id) != it->second.end())
      found_elem = true;
  return found_elem;
}
isBoundaryFullyExternalToSubdomains()
bool MooseMesh::isBoundaryFullyExternalToSubdomains (BoundaryID bid, const std::set< SubdomainID > & blk_group) const inherited
Returns whether a boundary (given by its id) is not crossing through a group of blocks, by which we mean that elements on both sides of the boundary are in those blocks.
Parameters
bid the id of the boundary of interest
blk_group the group of blocks potentially traversed
Returns
whether the boundary does not cross between the subdomains in the group
Definition at line 1170 of file MooseMesh.C.
{
  mooseAssert(_bnd_elem_range, "Boundary element range is not initialized");
  // Loop over all side elements of the mesh, select those on the boundary
  for (const auto & bnd_elem : *_bnd_elem_range)
  {
    const auto & [elem_ptr, elem_side, elem_bid] = *bnd_elem;
    if (elem_bid == bid)
    {
      // If an element is internal to the group of subdomain, check the neighbor
      if (blk_group.find(elem_ptr->subdomain_id()) != blk_group.end())
      {
        const auto * const neighbor = elem_ptr->neighbor_ptr(elem_side);
        // If we did not ghost the neighbor, we cannot decide
        if (neighbor == libMesh::remote_elem)
          mooseError("Insufficient level of geometrical ghosting to determine "
                     "if a boundary is internal to the mesh");
        // If the neighbor does not exist, then we are on the edge of the mesh
        if (!neighbor)
          continue;
        // If the neighbor is also in the group of subdomain,
        // then the boundary cuts the subdomains
        if (blk_group.find(neighbor->subdomain_id()) != blk_group.end())
          return false;
      }
    }
  }
  return true;
}
isBoundaryNode() [1/2]
bool MooseMesh::isBoundaryNode (dof_id_type node_id) const inherited
Returns true if the requested node is in the list of boundary nodes, false otherwise.
Definition at line 3306 of file MooseMesh.C.
{
  bool found_node = false;
  for (const auto & it : _bnd_node_ids)
  {
    if (it.second.find(node_id) != it.second.end())
    {
      found_node = true;
      break;
    }
  }
  return found_node;
}
Referenced by LowerBoundNodalKernel::computeQpJacobian(), UpperBoundNodalKernel::computeQpJacobian(), LowerBoundNodalKernel::computeQpOffDiagJacobian(), UpperBoundNodalKernel::computeQpOffDiagJacobian(), LowerBoundNodalKernel::computeQpResidual(), UpperBoundNodalKernel::computeQpResidual(), NodalNormalsPreprocessor::execute(), and MultiAppUserObjectTransfer::isBoundaryNode().
isBoundaryNode() [2/2]
bool MooseMesh::isBoundaryNode (dof_id_type node_id, BoundaryID bnd_id) const inherited
Returns true if the requested node is in the list of boundary nodes for the specified boundary, false otherwise.
Definition at line 3321 of file MooseMesh.C.
{
  bool found_node = false;
  std::map<boundary_id_type, std::set<dof_id_type>>::const_iterator it = _bnd_node_ids.find(bnd_id);
  if (it != _bnd_node_ids.end())
    if (it->second.find(node_id) != it->second.end())
      found_node = true;
  return found_node;
}
isCustomPartitionerRequested()
bool MooseMesh::isCustomPartitionerRequested () const inherited
Setter and getter for _custom_partitioner_requested.
Definition at line 3442 of file MooseMesh.C.
{
  return _custom_partitioner_requested;
}
isDisplaced() [1/2]
bool MooseMesh::isDisplaced () const inline inherited
whether this mesh is displaced
Definition at line 1188 of file MooseMesh.h.
{ return _is_displaced; }
isDisplaced() [2/2]
void MooseMesh::isDisplaced (bool is_displaced) inline inherited
Set whether this mesh is displaced.
Definition at line 1183 of file MooseMesh.h.
{ _is_displaced = is_displaced; }
isDistributedMesh()
bool MooseMesh::isDistributedMesh () const inline inherited
Returns the final Mesh distribution type.
Definition at line 981 of file MooseMesh.h.
{ return _use_distributed_mesh; }
Referenced by AddPeriodicBCAction::autoTranslationBoundaries(), BoundaryMarker::BoundaryMarker(), VerifyElementUniqueID::finalize(), VerifyNodalUniqueID::finalize(), ConsoleUtils::outputMeshInformation(), Checkpoint::updateCheckpointFiles(), and RandomData::updateGenerators().
isFiniteVolumeInfoDirty()
bool MooseMesh::isFiniteVolumeInfoDirty () const inline inherited
Returns
whether the finite volume information is dirty
Definition at line 1279 of file MooseMesh.h.
{ return _finite_volume_info_dirty; }
Referenced by FEProblemBase::meshChangedHelper().
isParallelTypeForced()
bool MooseMesh::isParallelTypeForced () const inline inherited
Tell the user if the distribution was overriden for any reason.
Definition at line 986 of file MooseMesh.h.
{ return _parallel_type_overridden; }
Referenced by ConsoleUtils::outputMeshInformation().
isParamSetByUser()
bool MooseBaseParameterInterface::isParamSetByUser (const std::string & nm) const inline inherited
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
Parameters
nm The name of the parameter to test
Definition at line 108 of file MooseBaseParameterInterface.h.
{ return _pars.isParamSetByUser(nm); }
Referenced by SetAdaptivityOptionsAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), LibtorchNeuralNetControl::conditionalParameterError(), MooseBaseParameterInterface::getRenamedParam(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), PiecewiseTabularBase::PiecewiseTabularBase(), MooseMesh::prepare(), and SolutionUserObject::readXda().
isParamValid()
bool MooseBaseParameterInterface::isParamValid (const std::string & name) const inline inherited
Test if the supplied parameter is valid.
Parameters
name The name of the parameter to test
Definition at line 102 of file MooseBaseParameterInterface.h.
{ return _pars.isParamValid(name); }
Referenced by AddDriftDiffusionAction::act(), AddSpecies::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CopyNodalVarsAction::act(), CreateDisplacedProblemAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), AddGeneralReactions::AddGeneralReactions(), AddZapdosReactions::AddZapdosReactions(), AdvectiveFluxAux::AdvectiveFluxAux(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), GeneratedMesh::buildMesh(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), ChemicalReactionsBase::ChemicalReactionsBase(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), CombinerGenerator::CombinerGenerator(), CSVReader::CSVReader(), ConstantReporter::declareConstantReporterValues(), DGKernelBase::DGKernelBase(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EEDFEnergyTownsendLog::EEDFEnergyTownsendLog(), Eigenvalue::Eigenvalue(), ElectronEnergyTermRate::ElectronEnergyTermRate(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), PIDTransientControl::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FileOutput::FileOutput(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FunctionDT::FunctionDT(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getRenamedParam(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), Terminator::handleMessage(), HeavySpeciesTempl< is_ad >::HeavySpeciesTempl(), HFEMDirichletBC::HFEMDirichletBC(), EigenExecutionerBase::init(), Eigenvalue::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), MooseParsedFunction::initialSetup(), MooseParsedGradFunction::initialSetup(), MooseParsedVectorFunction::initialSetup(), PiecewiseTabularBase::initialSetup(), SolutionFunction::initialSetup(), Console::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), IterationAdaptiveDT::IterationAdaptiveDT(), LeastSquaresFit::LeastSquaresFit(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MatCoupledForce::MatCoupledForce(), MooseMesh::MooseMesh(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarConsumerInterface::MortarConsumerInterface(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalExtremeValue::NodalExtremeValue(), EigenExecutionerBase::normalizeSolution(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PetscOutput::PetscOutput(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), PicardSolve::PicardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseTabularBase::PiecewiseTabularBase(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), MooseMesh::prepare(), MultiApp::readCommandLineArguments(), SolutionUserObject::readExodusII(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), MooseMesh::setCoordSystem(), FileOutput::setFileBase(), FileOutput::setFileBaseInternal(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SideDiffusiveFluxIntegralTempl< is_ad, T >::SideDiffusiveFluxIntegralTempl(), SideExtremeValue::SideExtremeValue(), SolutionUserObject::SolutionUserObject(), Terminator::Terminator(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), MultiAppDofCopyTransfer::transfer(), TransformGenerator::TransformGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
isPartitionerForced()
bool MooseMesh::isPartitionerForced () const inline inherited
Tell the user if the partitioner was overriden for any reason.
Definition at line 1001 of file MooseMesh.h.
{ return _partitioner_overridden; }
Referenced by ConsoleUtils::outputMeshInformation().
isRegularOrthogonal()
bool MooseMesh::isRegularOrthogonal () inline inherited
Getter to query if the mesh was detected to be regular and orthogonal.
Definition at line 1031 of file MooseMesh.h.
{ return _regular_orthogonal_mesh; }
isSemiLocal()
bool MooseMesh::isSemiLocal (Node *const node) const inherited
Returns true if the node is semi-local.
Parameters
node Node pointer
Returns
true is the node is semi-local, false otherwise
Definition at line 789 of file MooseMesh.C.
{
  return _semilocal_node_list.find(node) != _semilocal_node_list.end();
}
isSplit()
bool MooseMesh::isSplit () const inline inherited
Returns
Whether or not this mesh comes from a split mesh
Definition at line 1302 of file MooseMesh.h.
{ return _is_split; }
Referenced by ConsoleUtils::outputMeshInformation().
isTranslatedPeriodic()
bool MooseMesh::isTranslatedPeriodic (unsigned int nonlinear_var_num, unsigned int component) const inherited
Returns whether this generated mesh is periodic in the given dimension for the given variable.
Parameters
nonlinear_var_num - The nonlinear variable number
component - An integer representing the desired component (dimension)
Definition at line 1984 of file MooseMesh.C.
{
  mooseAssert(component < dimension(), "Requested dimension out of bounds");
  if (_periodic_dim.find(nonlinear_var_num) != _periodic_dim.end())
    return _periodic_dim.at(nonlinear_var_num)[component];
  else
    return false;
}
Referenced by MooseMesh::minPeriodicVector().
lengthUnit()
const MooseUnits & MooseMesh::lengthUnit () const inherited
Returns
the length unit of this mesh provided through the coordinate transformation object
Definition at line 4028 of file MooseMesh.C.
{
  mooseAssert(_coord_transform, "This must be non-null");
  return _coord_transform->lengthUnit();
}
localNodesBegin() [1/2]
MeshBase::node_iterator MooseMesh::localNodesBegin () inherited
Calls local_nodes_begin/end() on the underlying libMesh mesh object.
Definition at line 2767 of file MooseMesh.C.
{
  return getMesh().local_nodes_begin();
}
Referenced by MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), TopResidualDebugOutput::printTopResiduals(), and OversampleOutput::updateOversample().
localNodesBegin() [2/2]
MeshBase::const_node_iterator MooseMesh::localNodesBegin () const inherited
Definition at line 2779 of file MooseMesh.C.
{
  return getMesh().local_nodes_begin();
}
localNodesEnd() [1/2]
MeshBase::node_iterator MooseMesh::localNodesEnd () inherited
Definition at line 2773 of file MooseMesh.C.
{
  return getMesh().local_nodes_end();
}
Referenced by MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), TopResidualDebugOutput::printTopResiduals(), and OversampleOutput::updateOversample().
localNodesEnd() [2/2]
MeshBase::const_node_iterator MooseMesh::localNodesEnd () const inherited
Definition at line 2785 of file MooseMesh.C.
{
  return getMesh().local_nodes_end();
}
mapPoints()
void MooseMesh::mapPoints (const std::vector< Point > & from, const std::vector< Point > & to, std::vector< QpMap > & qp_map) private inherited
Find the closest points that map "from" to "to" and fill up "qp_map".
Essentially, for each point in "from" find the closest point in "to".
Parameters
from The reference positions in the parent of the the points we're mapping from
to The reference positions in the parent of the the points we're mapping to
qp_map This will be filled with QpMap objects holding the mappings.
Definition at line 2327 of file MooseMesh.C.
{
  unsigned int n_from = from.size();
  unsigned int n_to = to.size();
  qp_map.resize(n_from);
  for (unsigned int i = 0; i < n_from; ++i)
  {
    const Point & from_point = from[i];
    QpMap & current_map = qp_map[i];
    for (unsigned int j = 0; j < n_to; ++j)
    {
      const Point & to_point = to[j];
      Real distance = (from_point - to_point).norm();
      if (distance < current_map._distance)
      {
        current_map._distance = distance;
        current_map._from = i;
        current_map._to = j;
      }
    }
  }
}
Referenced by MooseMesh::buildPRefinementAndCoarseningMaps(), and MooseMesh::findAdaptivityQpMaps().
markFiniteVolumeInfoDirty()
void MooseMesh::markFiniteVolumeInfoDirty () inline inherited
Mark the finite volume information as dirty.
Definition at line 1274 of file MooseMesh.h.
{ _finite_volume_info_dirty = true; }
maxElementID()
dof_id_type MooseMesh::maxElementID (unsigned int elem_id_index) const inline inherited
Return the maximum element ID for an extra element integer with its accessing index.
Definition at line 1094 of file MooseMesh.h.
{ return _max_ids[elem_id_index]; }
maxElemId()
dof_id_type MooseMesh::maxElemId () const virtual inherited
Definition at line 2833 of file MooseMesh.C.
{
  return getMesh().max_elem_id();
}
Referenced by SolutionUserObject::pointValueGradientWrapper(), and SolutionUserObject::pointValueWrapper().
maxNodeId()
dof_id_type MooseMesh::maxNodeId () const virtual inherited
Calls max_node/elem_id() on the underlying libMesh mesh object.
This may be larger than n_nodes/elem() in cases where the id numbering is not contiguous.
Definition at line 2827 of file MooseMesh.C.
{
  return getMesh().max_node_id();
}
meshBoundaryIds()
const std::set< BoundaryID > & MooseMesh::meshBoundaryIds () const inherited
Returns a read-only reference to the set of boundary IDs currently present in the Mesh.
Definition at line 2917 of file MooseMesh.C.
{
  return _mesh_boundary_ids;
}
Referenced by BoundaryRestrictable::isBoundarySubset().
meshChanged()
void MooseMesh::meshChanged () inherited
Declares that the MooseMesh has changed, invalidates cached data and rebuilds caches.
Sets a flag so that clients of the MooseMesh also know when it has changed.
Definition at line 679 of file MooseMesh.C.
{
  TIME_SECTION("meshChanged", 3, "Updating Because Mesh Changed");
  update();
  // Delete all of the cached ranges
  _active_local_elem_range.reset();
  _active_node_range.reset();
  _active_semilocal_node_range.reset();
  _local_node_range.reset();
  _bnd_node_range.reset();
  _bnd_elem_range.reset();
  // Rebuild the ranges
  getActiveLocalElementRange();
  getActiveNodeRange();
  getLocalNodeRange();
  getBoundaryNodeRange();
  getBoundaryElementRange();
  // Call the callback function onMeshChanged
  onMeshChanged();
}
Referenced by DisplacedProblem::init(), FEProblemBase::init(), DisplacedProblem::meshChanged(), and FEProblemBase::meshChangedHelper().
meshNodesetIds()
const std::set< BoundaryID > & MooseMesh::meshNodesetIds () const inherited
Returns a read-only reference to the set of nodesets currently present in the Mesh.
Definition at line 2929 of file MooseMesh.C.
{
  return _mesh_nodeset_ids;
}
Referenced by GeometricSearchData::GeometricSearchData(), and BoundaryRestrictable::initializeBoundaryRestrictable().
meshSidesetIds()
const std::set< BoundaryID > & MooseMesh::meshSidesetIds () const inherited
Returns a read-only reference to the set of sidesets currently present in the Mesh.
Definition at line 2923 of file MooseMesh.C.
{
  return _mesh_sideset_ids;
}
Referenced by DGKernelBase::DGKernelBase(), and BoundaryRestrictable::initializeBoundaryRestrictable().
meshSubdomains()
const std::set< SubdomainID > & MooseMesh::meshSubdomains () const inherited
Returns a read-only reference to the set of subdomains currently present in the Mesh.
Definition at line 2911 of file MooseMesh.C.
{
  return _mesh_subdomains;
}
Referenced by FEProblemBase::adaptMesh(), BlockRestrictable::blockIDs(), MooseMesh::buildElemIDInfo(), FEProblemBase::checkProblemIntegrity(), FEProblemBase::checkUserObjects(), MultiAppGeometricInterpolationTransfer::computeTransformation(), NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), MultiApp::getBoundingBox(), MooseMesh::getUniqueCoordSystem(), FEProblemBase::initialAdaptMesh(), BlockAverageValue::initialize(), BlockRestrictable::initializeBlockRestrictable(), MultiAppDofCopyTransfer::initialSetup(), BlockRestrictable::isBlockSubset(), BlockRestrictable::meshBlockIDs(), MooseMesh::MooseMesh(), DOFMapOutput::output(), NonlinearSystemBase::setConstraintSecondaryValues(), MooseMesh::setCoordSystem(), and MooseMesh::setGeneralAxisymmetricCoordAxes().
minElementID()
dof_id_type MooseMesh::minElementID (unsigned int elem_id_index) const inline inherited
Return the minimum element ID for an extra element integer with its accessing index.
Definition at line 1099 of file MooseMesh.h.
{ return _min_ids[elem_id_index]; }
minPeriodicDistance()
Real MooseMesh::minPeriodicDistance (unsigned int nonlinear_var_num, Point p, Point q) const inherited
This function returns the distance between two points on the mesh taking into account periodicity for the given variable number.
Parameters
nonlinear_var_num - The nonlinear variable number
p,q - The points for which to compute a minimum distance
Returns
Real - The L2 distance between p and q
Definition at line 2020 of file MooseMesh.C.
{
  return minPeriodicVector(nonlinear_var_num, p, q).norm();
}
minPeriodicVector()
RealVectorValue MooseMesh::minPeriodicVector (unsigned int nonlinear_var_num, Point p, Point q) const inherited
This function returns the minimum vector between two points on the mesh taking into account periodicity for the given variable number.
Parameters
nonlinear_var_num - The nonlinear variable number
p,q - The points between which to compute a minimum vector
Returns
RealVectorValue - The vector pointing from p to q
Definition at line 1995 of file MooseMesh.C.
{
  for (unsigned int i = 0; i < dimension(); ++i)
  {
    // check to see if we're closer in real or periodic space in x, y, and z
    if (isTranslatedPeriodic(nonlinear_var_num, i))
    {
      // Need to test order before differencing
      if (p(i) > q(i))
      {
        if (p(i) - q(i) > _half_range(i))
          p(i) -= _half_range(i) * 2;
      }
      else
      {
        if (q(i) - p(i) > _half_range(i))
          p(i) += _half_range(i) * 2;
      }
    }
  }
  return q - p;
}
Referenced by MooseMesh::minPeriodicDistance().
mooseDeprecated()
template<typename... Args> void MooseBaseErrorInterface::mooseDeprecated (Args &&... args) const inline inherited
Definition at line 78 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseDeprecatedStream(_console, false, true, std::forward<Args>(args)...);
  }
Referenced by FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::advanceMultiApps(), MultiApp::appProblem(), Executioner::augmentedPicardConvergenceCheck(), MooseMesh::buildSideList(), FEProblemBase::computeResidual(), AddVariableAction::determineType(), Eigenvalue::Eigenvalue(), MooseMesh::elem(), FunctionDT::FunctionDT(), RandomICBase::generateRandom(), MooseMesh::getBoundariesToElems(), Control::getExecuteOptions(), FEProblemBase::getNonlinearSystem(), FEProblemBase::getUserObjects(), FEProblemBase::hasPostprocessor(), MooseMesh::node(), FixedPointSolve::numPicardIts(), RelationshipManager::operator>=(), Executioner::picardSolve(), and MooseMesh::setBoundaryToNormalMap().
mooseError()
template<typename... Args> void MooseBaseErrorInterface::mooseError (Args &&... args) const inline inherited
Emits an error prefixed with object name and type.
Definition at line 38 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, errorPrefix("error"), std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
Referenced by HierarchicalGridPartitioner::_do_partition(), PetscExternalPartitioner::_do_partition(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AdaptivityAction::act(), AddFVICAction::act(), AddICAction::act(), AddMeshGeneratorAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVectorPostprocessorAction::act(), CheckFVBCAction::act(), CheckIntegrityAction::act(), CommonOutputAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DeprecatedBlockAction::act(), InitProblemAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetAdaptivityOptionsAction::act(), SetupMeshAction::act(), SetupMeshCompleteAction::act(), SetupPredictorAction::act(), SetupTimeStepperAction::act(), SplitMeshAction::act(), FEProblemBase::adaptMesh(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::addConstraint(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFVInitialCondition(), AddGeneralReactions::AddGeneralReactions(), FEProblemBase::addInitialCondition(), FEProblemBase::addLineSearch(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addOutput(), SubProblem::addPiecewiseByBlockLambdaFunctor(), DistributedRectilinearMeshGenerator::addPoint(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), FEProblemBase::addPostprocessor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseMesh::addQuadratureNode(), FEProblemBase::addReporter(), AddVariableAction::addVariable(), FEProblemBase::addVectorPostprocessor(), SubProblem::addVectorTag(), AddZapdosReactions::AddZapdosReactions(), ADEEDFRateConstantTownsend::ADEEDFRateConstantTownsend(), ADGasElectronMoments::ADGasElectronMoments(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), MooseVariableScalar::adUDot(), Output::advancedExecuteOn(), AdvectiveFluxAux::AdvectiveFluxAux(), ADZapdosEEDFRateConstant::ADZapdosEEDFRateConstant(), MooseVariableBase::allDofIndices(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayConstantIC::ArrayConstantIC(), ArrayFunctionIC::ArrayFunctionIC(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), Function::average(), Axisymmetric2D3DSolutionFunction::Axisymmetric2D3DSolutionFunction(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), BoltzmannSolverScalar::BoltzmannSolverScalar(), BoundingValueElementDamper::BoundingValueElementDamper(), BoundingValueNodalDamper::BoundingValueNodalDamper(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), MooseMesh::buildCoarseningMap(), MultiApp::buildComm(), DistributedRectilinearMeshGenerator::buildCube(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), PiecewiseTabularBase::buildFromXY(), MooseMesh::buildLowerDMesh(), GeneratedMesh::buildMesh(), MeshGeneratorMesh::buildMesh(), buildMesh(), TiledMesh::buildMesh(), ImageMesh::buildMesh3D(), ImageMeshGenerator::buildMesh3D(), MooseMesh::buildRefinementMap(), MaterialBase::buildRequiredMaterials(), MooseMesh::buildSideList(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), UserObjectInterface::castUserObject(), EigenExecutionerBase::chebyshev(), SubProblem::checkBlockMatProps(), SubProblem::checkBoundaryMatProps(), MooseMesh::checkCoordinateSystems(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkDisplacementOrders(), FEProblemBase::checkDuplicatePostprocessorVariableNames(), MooseMesh::checkDuplicateSubdomainNames(), MaterialBase::checkExecutionStage(), MeshGenerator::checkGetMesh(), ReporterTransferInterface::checkHasReporterValue(), FEProblemBase::checkICRestartError(), EigenExecutionerBase::checkIntegrity(), Eigenvalue::checkIntegrity(), Steady::checkIntegrity(), ExplicitTimeIntegrator::checkLinearConvergence(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), PostprocessorInterface::checkParam(), FEProblemBase::checkProblemIntegrity(), Sampler::checkReinitStatus(), MaterialBase::checkStatefulSanity(), FEProblemBase::checkUserObjects(), MultiAppTransfer::checkVariable(), DomainUserObject::checkVariable(), ChemicalReactionsBase::ChemicalReactionsBase(), MooseMesh::clone(), LibmeshPartitioner::clone(), CombinerGenerator::CombinerGenerator(), ElementSubdomainModifier::complementMovingBoundaryID(), ElementSubdomainModifier::complementMovingBoundaryName(), MooseVariableFieldBase::componentName(), CompositeFunction::CompositeFunction(), NodalPatchRecovery::compute(), VariableCondensationPreconditioner::computeDInverseDiag(), CompositionDT::computeDT(), MooseVariableFieldBase::computeFaceValues(), TimeStepper::computeFailedDT(), IterationAdaptiveDT::computeFailedDT(), TimeSequenceStepperBase::computeFailedDT(), MooseMesh::computeFiniteVolumeCoords(), FVFluxKernel::computeJacobian(), ArrayKernel::computeJacobian(), ArrayKernel::computeOffDiagJacobian(), FVElementalKernel::computeOffDiagJacobian(), MaterialBase::computeProperties(), ScalarKernel::computeQpJacobian(), ScalarKernel::computeQpResidual(), FVFluxKernel::computeResidual(), ArrayKernel::computeResidual(), FVFluxBC::computeResidual(), ResidualObject::computeResidualAndJacobian(), FVFluxKernel::computeResidualAndJacobian(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualL2Norm(), FEProblemBase::computeResidualTag(), FEProblemBase::computeResidualType(), TimeStepper::computeStep(), ActuallyExplicitEuler::computeTimeDerivatives(), AStableDirk4::computeTimeDerivatives(), BDF2::computeTimeDerivatives(), CrankNicolson::computeTimeDerivatives(), ExplicitEuler::computeTimeDerivatives(), ExplicitRK2::computeTimeDerivatives(), ExplicitTVDRK2::computeTimeDerivatives(), ImplicitEuler::computeTimeDerivatives(), ImplicitMidpoint::computeTimeDerivatives(), LStableDirk2::computeTimeDerivatives(), LStableDirk3::computeTimeDerivatives(), LStableDirk4::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), FEProblemBase::computeUserObjectsInternal(), BolsigValueScalar::computeValue(), PenetrationAux::computeValue(), BuildArrayVariableAux::computeValue(), TagVectorArrayVariableAux::computeValue(), ConcentricCircleMesh::ConcentricCircleMesh(), ConditionalEnableControl::ConditionalEnableControl(), TimeStepper::constrainStep(), LibtorchNeuralNetControl::controlNeuralNet(), AddVariableAction::createInitialConditionAction(), DataRead::DataRead(), ReporterTransferInterface::declareClone(), MeshGenerator::declareMeshProperty(), ReporterTransferInterface::declareVectorClone(), FunctorRelationshipManager::delete_remote_elements(), MooseMesh::deleteRemoteElements(), BicubicSplineFunction::derivative(), MooseMesh::detectPairedSidesets(), FEProblemBase::determineNonlinearSystem(), MeshDiagnosticsGenerator::diagnosticsLog(), DiffusionRateTemp::DiffusionRateTemp(), FunctorBinnedValuesDivision::divisionIndex(), FunctorRelationshipManager::dofmap_reinit(), FEProblemBase::duplicateVariableCheck(), EEDFRateConstant::EEDFRateConstant(), EEDFRateConstantTownsend::EEDFRateConstantTownsend(), Eigenvalue::Eigenvalue(), ElectricField::ElectricField(), ElectronMobility::ElectronMobility(), ElementIntegerAux::ElementIntegerAux(), ElementQualityAux::ElementQualityAux(), ElementUOAux::ElementUOAux(), DistributedRectilinearMeshGenerator::elemId(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), MooseMesh::errorIfDistributedMesh(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), BoltzmannSolverScalar::execute(), Eigenvalue::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), ElementQualityChecker::execute(), DiscreteElementUserObject::execute(), DomainUserObject::execute(), FEProblemBase::execute(), FEProblemBase::executeControls(), MultiAppVectorPostprocessorTransfer::executeFromMultiapp(), MultiAppVectorPostprocessorTransfer::executeToMultiapp(), ExplicitSSPRungeKutta::ExplicitSSPRungeKutta(), FileOutput::FileOutput(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), ElementQualityChecker::finalize(), VerifyElementUniqueID::finalize(), VerifyNodalUniqueID::finalize(), DiscreteElementUserObject::finalize(), Transfer::find_sys(), BreakMeshByBlockGeneratorBase::findFreeBoundaryId(), FunctionDT::FunctionDT(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), GapValueAux::GapValueAux(), Gas::Gas(), GasBase::GasBase(), GasElectronMoments::GasElectronMoments(), AllSideSetsByNormalsGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundingBoxNodeSetGenerator::generate(), BreakMeshByBlockGenerator::generate(), CombinerGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshCollectionGenerator::generate(), MeshDiagnosticsGenerator::generate(), MeshExtruderGenerator::generate(), MeshRepairGenerator::generate(), MoveNodeGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), SideSetsFromNormalsGenerator::generate(), SideSetsFromPointsGenerator::generate(), SmoothMeshGenerator::generate(), SpiralAnnularMeshGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), TiledMeshGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GeneratedMesh::GeneratedMesh(), GeneratedMeshGenerator::GeneratedMeshGenerator(), MeshGenerator::generateInternal(), CircularBoundaryCorrectionGenerator::generateRadialCorrectionFactor(), RandomICBase::generateRandom(), GenericConstantMaterialTempl< is_ad >::GenericConstantMaterialTempl(), GenericConstantVectorMaterialTempl< is_ad >::GenericConstantVectorMaterialTempl(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), DisplacedProblem::getActualFieldVariable(), FEProblemBase::getActualFieldVariable(), DisplacedProblem::getArrayVariable(), FEProblemBase::getArrayVariable(), MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::getBlockConnectedBlocks(), VariableOldValueBoundsAux::getBound(), MooseMesh::getBoundaryID(), MultiApp::getBoundingBox(), MooseMesh::getCoarseningMap(), MooseVariableBase::getContinuity(), Control::getControllableParameterByName(), MooseMesh::getCoordSystem(), PropertyReadFile::getData(), TransfiniteMeshGenerator::getDiscreteEdge(), FEProblemBase::getDistribution(), MooseVariableBase::getDofIndices(), VariableCondensationPreconditioner::getDofToCondense(), TransfiniteMeshGenerator::getEdge(), GhostingUserObject::getElementalValue(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), PropertyReadFile::getElementData(), MooseMesh::getElementIDIndex(), Material::getElementIDNeighbor(), Material::getElementIDNeighborByName(), MooseMesh::getElemIDMapping(), MooseMesh::getElemIDsOnBlocks(), MultiAppFieldTransfer::getEquationSystem(), MultiApp::getExecutioner(), MultiAppTransfer::getFromMultiApp(), MultiAppTransfer::getFromMultiAppInfo(), FEProblemBase::getFunction(), SubProblem::getFunctor(), MooseMesh::getGeneralAxisymmetricCoordAxis(), DistributedRectilinearMeshGenerator::getGhostNeighbors(), BatchMaterial< Tuple, Output, Input >::getIndex(), DistributedRectilinearMeshGenerator::getIndices(), SolutionUserObject::getLocalVarIndex(), Material::getMaterialByName(), FEProblemBase::getMaterialData(), SubProblem::getMatrixTagID(), AnnularMesh::getMaxInDimension(), GeneratedMesh::getMaxInDimension(), FEProblemBase::getMaxQps(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), AnnularMesh::getMinInDimension(), GeneratedMesh::getMinInDimension(), MultiAppTransfer::getMultiApp(), DistributedRectilinearMeshGenerator::getNeighbors(), MooseMesh::getNodeBlockIds(), PropertyReadFile::getNodeData(), MooseMesh::getNodeList(), FEProblemBase::getNonlinearSystem(), MooseMesh::getPairedBoundaryMapping(), ImageMesh::GetPixelInfo(), ImageMeshGenerator::GetPixelInfo(), PlaneIDMeshGenerator::getPlaneID(), FEProblemBase::getPositionsObject(), PostprocessorInterface::getPostprocessorValueByNameInternal(), MooseMesh::getRefinementMap(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), FEProblemBase::getSampler(), JSONFileReader::getScalar(), DisplacedProblem::getScalarVariable(), FEProblemBase::getScalarVariable(), DisplacedProblem::getStandardVariable(), FEProblemBase::getStandardVariable(), MooseMesh::getSubdomainBoundaryIds(), DisplacedProblem::getSystem(), FEProblemBase::getSystem(), FEProblemBase::getTimeFromStateArg(), Transient::getTimeIntegratorName(), MultiAppTransfer::getToMultiApp(), MultiAppTransfer::getToMultiAppInfo(), MooseMesh::getUniqueCoordSystem(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::getUserObjectName(), JSONFileReader::getVector(), VectorPostprocessorInterface::getVectorPostprocessorName(), SubProblem::getVectorTag(), SubProblem::getVectorTagID(), DisplacedProblem::getVectorVariable(), FEProblemBase::getVectorVariable(), GhostingAux::GhostingAux(), MultiApp::globalAppToLocal(), Function::gradient(), MooseParsedVectorFunction::gradient(), Terminator::handleMessage(), MooseVariableBase::hasDoFsOnNodes(), PostprocessorInterface::hasPostprocessor(), PostprocessorInterface::hasPostprocessorByName(), ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), AddVariableAction::init(), MooseMesh::init(), Sampler::init(), AddAuxVariableAction::init(), EigenExecutionerBase::init(), Eigenvalue::init(), Transient::init(), FEProblemBase::init(), CrankNicolson::init(), ExplicitTimeIntegrator::init(), CSVTimeSequenceStepper::init(), IterationAdaptiveDT::init(), MultiApp::init(), FEProblemBase::initialAdaptMesh(), BoltzmannSolverScalar::initialize(), PolynomialCoefficients::initialize(), CartesianGridDivision::initialize(), CylindricalGridDivision::initialize(), NestedDivision::initialize(), SphericalGridDivision::initialize(), SubProblem::initialSetup(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), Axisymmetric2D3DSolutionFunction::initialSetup(), MooseParsedFunction::initialSetup(), SolutionFunction::initialSetup(), SolutionIC::initialSetup(), FullSolveMultiApp::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), SolutionUserObject::initialSetup(), Function::integral(), InterpolatedCoefficientLinear::InterpolatedCoefficientLinear(), InterpolatedCoefficientSpline::InterpolatedCoefficientSpline(), EigenExecutionerBase::inversePowerIteration(), InversePowerMethod::InversePowerMethod(), Sampler::isAdaptiveSamplingCompleted(), MooseMesh::isBoundaryFullyExternalToSubdomains(), MooseVariableBase::isNodal(), IterationAdaptiveDT::IterationAdaptiveDT(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LineSearch::lineSearch(), ReporterPointMarker::markerSetup(), Material::Material(), MaterialOutputAction::materialOutputHelper(), MaterialRealTensorValueAux::MaterialRealTensorValueAux(), MaterialRealVectorValueAuxTempl< is_ad >::MaterialRealVectorValueAuxTempl(), Distribution::median(), FunctorRelationshipManager::mesh_reinit(), SubProblem::meshChanged(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshExtruderGenerator::MeshExtruderGenerator(), MeshRepairGenerator::MeshRepairGenerator(), SetupMeshAction::modifyParamsForUseSplit(), MeshMetaDataInterface::mooseErrorInternal(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MoveNodeGenerator::MoveNodeGenerator(), ElementSubdomainModifier::movingBoundaryID(), ElementSubdomainModifier::movingBoundaryName(), MultiApp::MultiApp(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NearestNodeDistanceAux::NearestNodeDistanceAux(), NearestNodeValueAux::NearestNodeValueAux(), FEProblemBase::needsPreviousNewtonIteration(), NewmarkBeta::NewmarkBeta(), NodalPatchRecoveryBase::nodalPatchRecovery(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), DistributedRectilinearMeshGenerator::nodeId(), DistributedRectilinearMeshGenerator::numNeighbors(), Output::onInterval(), FunctorRelationshipManager::operator()(), RelationshipManager::operator==(), MortarNodalGeometryOutput::output(), Output::Output(), DistributedRectilinearMeshGenerator::paritionSquarely(), PiecewiseBilinear::parse(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), ExplicitTimeIntegrator::performExplicitSolve(), PetscExternalPartitioner::PetscExternalPartitioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), Executioner::picardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseMulticonstant::PiecewiseMulticonstant(), PiecewiseTabularBase::PiecewiseTabularBase(), SolutionUserObject::pointValueGradientWrapper(), SolutionUserObject::pointValueWrapper(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName(), AStableDirk4::postResidual(), ExplicitRK2::postResidual(), ExplicitTVDRK2::postResidual(), ImplicitMidpoint::postResidual(), LStableDirk2::postResidual(), LStableDirk3::postResidual(), LStableDirk4::postResidual(), VariableCondensationPreconditioner::preallocateCondensedJacobian(), Predictor::Predictor(), Transient::preExecute(), MooseMesh::prepare(), MooseMesh::prepared(), FixedPointSolve::printFixedPointConvergenceReason(), RateCoefficientProvider::RateCoefficientProvider(), RateCoefficientProvider::reaction_coefficient(), RateCoefficientProvider::reaction_coefficient_derivative(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readExodusII(), SolutionUserObject::readXda(), FunctorRelationshipManager::redistribute(), Sampler::reinit(), RinglebMesh::RinglebMesh(), RinglebMeshGenerator::RinglebMeshGenerator(), PiecewiseMultiInterpolation::sample(), ScalarComponentIC::ScalarComponentIC(), ScalarLinearInterpolation::ScalarLinearInterpolation(), ScalarSplineInterpolation::ScalarSplineInterpolation(), DistributedRectilinearMeshGenerator::scaleNodalPositions(), BicubicSplineFunction::secondDerivative(), FunctorRelationshipManager::set_mesh(), MooseVariableBase::setActiveTags(), DistributedRectilinearMeshGenerator::setBoundaryNames(), MooseMesh::setCoordSystem(), FEProblemBase::setCoupling(), PiecewiseBase::setData(), FileOutput::setFileBaseInternal(), MooseMesh::setGeneralAxisymmetricCoordAxes(), FEProblemSolve::setInnerSolve(), MeshGenerator::setMeshProperty(), FEProblemBase::setNonlocalCouplingMatrix(), Sampler::setNumberOfCols(), Sampler::setNumberOfRandomSeeds(), Sampler::setNumberOfRows(), Split::setup(), TransientMultiApp::setupApp(), SetupMeshAction::setupMesh(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), TimePeriodBase::setupTimes(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SideSetsFromNormalsGenerator::SideSetsFromNormalsGenerator(), SideSetsFromPointsGenerator::SideSetsFromPointsGenerator(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), SolutionTimeAdaptiveDT::SolutionTimeAdaptiveDT(), SolutionUserObject::SolutionUserObject(), FullSolveMultiApp::solveStep(), UserObject::spatialPoints(), UserObject::spatialValue(), SpiralAnnularMesh(), SpiralAnnularMeshGenerator::SpiralAnnularMeshGenerator(), StitchedMesh::StitchedMesh(), MaterialBase::subdomainSetup(), GeneralUserObject::subdomainSetup(), NodalUserObject::subdomainSetup(), Constraint::subdomainSetup(), SuperelasticReactionRate::SuperelasticReactionRate(), FEProblemBase::swapBackMaterialsNeighbor(), Terminator::Terminator(), GeneralUserObject::threadJoin(), ThreadedGeneralUserObject::threadJoin(), DiscreteElementUserObject::threadJoin(), TimePeriodBase::TimePeriodBase(), VectorPostprocessorVisualizationAux::timestepSetup(), FEProblemBase::trustUserCouplingMatrix(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), FEProblemBase::uDotDotOldRequested(), MooseVariableScalar::uDotOld(), FEProblemBase::uDotOldRequested(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), SolutionUserObject::updateExodusBracketingTimeIndices(), FEProblemBase::updateMaxQps(), BoundingBoxIC::value(), Function::value(), Axisymmetric2D3DSolutionFunction::value(), PiecewiseConstantFromCSV::value(), ValueProvider::ValueProvider(), ValueRangeMarker::ValueRangeMarker(), ValueThresholdMarker::ValueThresholdMarker(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), MultiAppTransfer::variableIntegrityCheck(), VariableTimeIntegrationAux::VariableTimeIntegrationAux(), AddVariableAction::variableType(), Function::vectorCurl(), SubProblem::vectorTagName(), SubProblem::vectorTagType(), Function::vectorValue(), MooseParsedFunction::vectorValue(), MooseParsedGradFunction::vectorValue(), SubProblem::verifyVectorTags(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
mooseErrorNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseErrorNonPrefixed (Args &&... args) const inline inherited
Emits an error without the prefixing included in mooseError().
Definition at line 50 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
mooseInfo()
template<typename... Args> void MooseBaseErrorInterface::mooseInfo (Args &&... args) const inline inherited
Definition at line 84 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseInfoStream(_console, std::forward<Args>(args)...);
  }
Referenced by AddZapdosReactions::act(), SetupRecoverFileBaseAction::act(), AStableDirk4::AStableDirk4(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), BoltzmannSolverScalar::execute(), ExplicitRK2::ExplicitRK2(), ExplicitTVDRK2::ExplicitTVDRK2(), MultiAppTransfer::getPointInTargetAppFrame(), ImplicitMidpoint::ImplicitMidpoint(), InversePowerMethod::InversePowerMethod(), LStableDirk2::LStableDirk2(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), NonlinearEigen::NonlinearEigen(), ProjectionAux::ProjectionAux(), FEProblemBase::setRestartFile(), and SymmetryTransformGenerator::SymmetryTransformGenerator().
mooseWarning()
template<typename... Args> void MooseBaseErrorInterface::mooseWarning (Args &&... args) const inline inherited
Emits a warning prefixed with object name and type.
Definition at line 62 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(
        _console, errorPrefix("warning"), std::forward<Args>(args)...);
  }
Referenced by AddFunctionAction::act(), AddKernelAction::act(), CommonOutputAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupMeshAction::act(), DumpObjectsProblem::addAuxVariable(), DiracKernelBase::addPoint(), BoundaryMarker::BoundaryMarker(), BoundsAuxBase::BoundsAuxBase(), DistributedRectilinearMeshGenerator::buildCube(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), CartesianMeshGenerator::CartesianMeshGenerator(), CheckOutputAction::checkConsoleOutput(), MultiAppTransfer::checkMultiAppExecuteOn(), GapValueAux::computeValue(), MeshDiagnosticsGenerator::diagnosticsLog(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), Postprocessor::evaluateDotWarning(), ElementQualityChecker::finalize(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FixedPointSolve::FixedPointSolve(), ElementSubdomainIDGenerator::generate(), ParsedGenerateSideset::generate(), MultiAppTransfer::getAppInfo(), FunctorBinnedValuesDivision::getBinIndex(), FEProblemBase::getMaterial(), Terminator::handleMessage(), MaterialBase::initStatefulProperties(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::mesh(), NewmarkBeta::NewmarkBeta(), NodalPatchRecovery::NodalPatchRecovery(), Output::Output(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), Executioner::problem(), PropertyReadFile::readData(), TestSourceStepper::rejectStep(), MaterialBase::resetQpProperties(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setCoordSystem(), FEProblemBase::sizeZeroes(), TransientMultiApp::solveStep(), TimeDerivativeAux::TimeDerivativeAux(), PiecewiseConstantFromCSV::value(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
mooseWarningNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseWarningNonPrefixed (Args &&... args) const inline inherited
Emits a warning without the prefixing included in mooseWarning().
Definition at line 72 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(_console, std::forward<Args>(args)...);
  }
name()
virtual const std::string & MooseBase::name () const inline virtual inherited
Get the name of the class.
Returns
The name of the class
Reimplemented in MooseVariableBase.
Definition at line 47 of file MooseBase.h.
{ return _name; }
Referenced by HierarchicalGridPartitioner::_do_partition(), AdaptivityAction::act(), AddElementalFieldAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVariableAction::act(), CopyNodalVarsAction::act(), DeprecatedBlockAction::act(), DisplayGhostingAction::act(), MaterialOutputAction::act(), AddDriftDiffusionAction::addADKernels(), FEProblemBase::addAnyRedistributers(), Executioner::addAttributeReporter(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFunctorMaterial(), FunctorMaterial::addFunctorProperty(), FunctorMaterial::addFunctorPropertyByBlocks(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), ADDGKernel::ADDGKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), SubProblem::addPiecewiseByBlockLambdaFunctor(), FEProblemBase::addPostprocessor(), UserObject::addPostprocessorDependencyHelper(), InitialConditionBase::addPostprocessorDependencyHelper(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), UserObject::addUserObjectDependencyHelper(), AuxKernelTempl< ComputeValueType >::addUserObjectDependencyHelper(), InitialConditionBase::addUserObjectDependencyHelper(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), UserObject::addVectorPostprocessorDependencyHelper(), FVFluxKernel::adjustRMGhostLayers(), ADSurfaceCharge::ADSurfaceCharge(), Output::advancedExecuteOn(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayDGKernel::ArrayDGKernel(), ArrayParsedAux::ArrayParsedAux(), AStableDirk4::AStableDirk4(), Function::average(), MultiApp::backup(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), PiecewiseTabularBase::buildFromFile(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkICRestartError(), Damper::checkMinDamping(), Coupleable::checkWritableVar(), CompositeFunction::CompositeFunction(), MaterialBase::computeProperties(), FEProblemBase::computeUserObjectByName(), VectorPostprocessorVisualizationAux::computeValue(), MooseBaseParameterInterface::connectControllableParams(), BatchMaterial< Tuple, Output, Input >::construct(), MultiApp::createApp(), AddVariableAction::createInitialConditionAction(), MultiApp::createLocalApp(), MeshGeneratorSystem::createMeshGeneratorOrder(), MaterialBase::declareADProperty(), MeshGenerator::declareMeshesForSubByName(), MeshGenerator::declareNullMeshName(), MaterialBase::declareProperty(), DOFMapOutput::demangle(), DerivativeSumMaterialTempl< is_ad >::DerivativeSumMaterialTempl(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DomainUserObject::DomainUserObject(), DumpObjectsProblem::dumpObjectHelper(), EconomouDielectricBC::EconomouDielectricBC(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementValueSampler::ElementValueSampler(), MooseMesh::errorIfDistributedMesh(), MooseBaseErrorInterface::errorPrefix(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), PointValue::execute(), RestartableDataReporter::execute(), MultiAppNearestNodeTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), MultiApp::fillPositions(), PointSamplerBase::finalize(), FunctionDT::FunctionDT(), FVFunctionIC::functionName(), FunctionIC::functionName(), FunctorPositions::FunctorPositions(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), BoundaryDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), GeneratedMeshGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MeshGenerator::generateInternal(), InterfaceMaterial::getADMaterialProperty(), Material::getADMaterialProperty(), MultiAppTransfer::getAppInfo(), MultiApp::getBoundingBox(), Control::getControllableParameterByName(), Control::getControllableValue(), Control::getControllableValueByName(), UserObject::getDependObjects(), FEProblemBase::getDistribution(), DistributionInterface::getDistribution(), DistributionInterface::getDistributionByName(), AddZapdosReactions::getElectronImpactKernelName(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), MultiApp::getExecutioner(), FEProblemBase::getExecutor(), OutputWarehouse::getFileNumbers(), FEProblemBase::getFunction(), SubProblem::getFunctor(), AuxKernelTempl< ComputeValueType >::getGenericMaterialProperty(), NodalPatchRecovery::getGenericMaterialProperty(), InterfaceMaterial::getGenericMaterialProperty(), Material::getGenericMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialProperty(), InterfaceMaterial::getGenericNeighborMaterialPropertyByName(), Material::getGenericOptionalMaterialProperty(), MaterialBase::getGenericZeroMaterialProperty(), BatchMaterial< Tuple, Output, Input >::getIndex(), AddZapdosReactions::getKernelName(), SolutionUserObject::getLocalVarIndex(), Marker::getMarkerValue(), Material::getMaterial(), FEProblemBase::getMaterial(), Material::getMaterialByName(), AuxKernelTempl< ComputeValueType >::getMaterialProperty(), NodalPatchRecovery::getMaterialProperty(), InterfaceMaterial::getMaterialProperty(), Material::getMaterialProperty(), SubProblem::getMaterialPropertyBlockNames(), SubProblem::getMaterialPropertyBoundaryNames(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOld(), NodalPatchRecovery::getMaterialPropertyOld(), InterfaceMaterial::getMaterialPropertyOld(), Material::getMaterialPropertyOld(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOlder(), NodalPatchRecovery::getMaterialPropertyOlder(), InterfaceMaterial::getMaterialPropertyOlder(), Material::getMaterialPropertyOlder(), MeshGenerator::getMesh(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshesByName(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MultiAppTransfer::getMultiApp(), InterfaceMaterial::getNeighborADMaterialProperty(), InterfaceMaterial::getNeighborMaterialProperty(), InterfaceMaterial::getNeighborMaterialPropertyOld(), InterfaceMaterial::getNeighborMaterialPropertyOlder(), Material::getOptionalADMaterialProperty(), Material::getOptionalMaterialProperty(), Material::getOptionalMaterialPropertyOld(), Material::getOptionalMaterialPropertyOlder(), FEProblemBase::getPositionsObject(), FEProblemBase::getPostprocessorValueByName(), AddReactions::getReactionKernelName(), ReporterData::getReporterInfo(), FEProblemBase::getSampler(), Transient::getTimeStepperName(), ProjectedStatefulMaterialStorageAction::getTypeEnum(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), Terminator::handleMessage(), FEProblemBase::hasFunction(), SubProblem::hasFunctor(), SubProblem::hasFunctorWithType(), AdvancedOutput::hasOutputHelper(), FEProblemBase::hasPostprocessor(), FEProblemBase::hasPostprocessorValueByName(), FEProblemBase::hasUserObject(), AdvancedOutput::init(), FEProblemBase::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), AttribName::initFrom(), NestedDivision::initialize(), SolutionScalarAux::initialSetup(), NodalVariableValue::initialSetup(), MultiAppProjectionTransfer::initialSetup(), SolutionUserObject::initialSetup(), AdvancedOutput::initOutputList(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MaterialBase::initStatefulProperties(), Function::integral(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), MeshGenerator::isChildMeshGenerator(), MeshGenerator::isNullMeshName(), MeshGenerator::isParentMeshGenerator(), LinearCombinationFunction::LinearCombinationFunction(), FEProblemBase::logAdd(), LymberopoulosElectronBC::LymberopoulosElectronBC(), Marker::Marker(), Material::Material(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), Distribution::median(), MemoryUsageReporter::MemoryUsageReporter(), MeshGenerator::meshPropertyPrefix(), MooseVariableInterface< T >::MooseVariableInterface(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), NeumannCircuitVoltageMoles_KV::NeumannCircuitVoltageMoles_KV(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), NodalValueSampler::NodalValueSampler(), MooseBaseParameterInterface::objectErrorPrefix(), MeshGenerator::Comparator::operator()(), DOFMapOutput::output(), ProgressOutput::output(), Output::Output(), AdvancedOutput::outputElementalVariables(), ConsoleUtils::outputExecutionInformation(), AdvancedOutput::outputInput(), AdvancedOutput::outputNodalVariables(), AdvancedOutput::outputPostprocessors(), Exodus::outputPostprocessors(), Nemesis::outputPostprocessors(), TableOutput::outputReporter(), AdvancedOutput::outputReporters(), AdvancedOutput::outputScalarVariables(), AdvancedOutput::outputSystemInformation(), AdvancedOutput::outputVectorPostprocessors(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedODEKernel::ParsedODEKernel(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PointVariableSamplerBase::PointVariableSamplerBase(), MultiApp::readCommandLineArguments(), Receiver::Receiver(), Executor::Result::record(), FEProblemBase::registerRandomInterface(), GlobalParamsAction::remove(), MaterialBase::resetQpProperties(), MultiApp::restore(), SakiyamaEnergySecondaryElectronBC::SakiyamaEnergySecondaryElectronBC(), SakiyamaSecondaryElectronBC::SakiyamaSecondaryElectronBC(), ScalarComponentIC::ScalarComponentIC(), SecondaryElectronBC::SecondaryElectronBC(), SecondaryElectronEnergyBC::SecondaryElectronEnergyBC(), MultiApp::setAppOutputFileBase(), MooseMesh::setBoundaryName(), Control::setControllableValue(), Control::setControllableValueByName(), GlobalParamsAction::setDoubleIndexParam(), OutputWarehouse::setFileNumbers(), GlobalParamsAction::setParam(), FEProblemBase::setPostprocessorValueByName(), GlobalParamsAction::setScalarParam(), MooseMesh::setSubdomainName(), GlobalParamsAction::setTripleIndexParam(), Split::setup(), TransientMultiApp::setupApp(), GlobalParamsAction::setVectorParam(), SideCurrent::SideCurrent(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SideValueSampler::SideValueSampler(), TransientMultiApp::solveStep(), UserObject::spatialValue(), StitchedMesh::StitchedMesh(), SubProblem::storeBoundaryDelayedCheckMatProp(), SubProblem::storeBoundaryMatPropName(), SubProblem::storeBoundaryZeroMatProp(), SubProblem::storeSubdomainDelayedCheckMatProp(), SubProblem::storeSubdomainMatPropName(), SubProblem::storeSubdomainZeroMatProp(), MaterialBase::subdomainSetup(), TaggingInterface::TaggingInterface(), VectorPostprocessorVisualizationAux::timestepSetup(), MultiAppDofCopyTransfer::transfer(), TransientMultiApp::TransientMultiApp(), MooseBase::typeAndName(), MooseBaseParameterInterface::uniqueParameterName(), UserObject::UserObject(), UserObjectInterface::userObjectName(), MultiAppTransfer::variableIntegrityCheck(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), AdvancedOutput::wantOutput(), Coupleable::writableCoupledValue(), and Coupleable::writableVariable().
needGhostGhostedBoundaries()
void MooseMesh::needGhostGhostedBoundaries (bool needghost) inline inherited
Whether or not we want to ghost ghosted boundaries.
Definition at line 598 of file MooseMesh.h.
{ _need_ghost_ghosted_boundaries = needghost; }
needsPrepareForUse()
void MooseMesh::needsPrepareForUse () inherited
If this method is called, we will call libMesh's prepare_for_use method when we call Moose's prepare method.
This should only be set when the mesh structure is changed by MeshGenerators (i.e. Element deletion).
Definition at line 2905 of file MooseMesh.C.
{
  prepared(false);
}
needsRemoteElemDeletion() [1/2]
bool MooseMesh::needsRemoteElemDeletion () const inline inherited
Whether we need to delete remote elements.
Definition at line 1059 of file MooseMesh.h.
{ return _need_delete; }
needsRemoteElemDeletion() [2/2]
void MooseMesh::needsRemoteElemDeletion (bool need_delete) inline inherited
Set whether we need to delete remote elements.
Definition at line 1054 of file MooseMesh.h.
{ _need_delete = need_delete; }
Referenced by Adaptivity::uniformRefine().
nElem()
dof_id_type MooseMesh::nElem () const virtual inherited
Definition at line 2821 of file MooseMesh.C.
{
  return getMesh().n_elem();
}
Referenced by PropertyReadFile::getElementData(), and PropertyReadFile::readData().
nFace()
unsigned int MooseMesh::nFace () const inline inherited
accessors for the FaceInfo objects
Definition at line 1122 of file MooseMesh.h.
{ return _face_info.size(); }
nNodes()
dof_id_type MooseMesh::nNodes () const virtual inherited
Calls n_nodes/elem() on the underlying libMesh mesh object.
Definition at line 2815 of file MooseMesh.C.
{
  return getMesh().n_nodes();
}
Referenced by PropertyReadFile::getNodeData(), and PropertyReadFile::readData().
node() [1/2]
Node & MooseMesh::node (const dof_id_type i) virtual inherited
Definition at line 624 of file MooseMesh.C.
{
  mooseDeprecated("MooseMesh::node() is deprecated, please use MooseMesh::nodeRef() instead");
  return nodeRef(i);
}
node() [2/2]
const Node & MooseMesh::node (const dof_id_type i) const virtual inherited
Various accessors (pointers/references) for Node "i".
If the requested node is a remote node on a distributed mesh, only the query accessors are valid to call, and they return NULL.
Definition at line 617 of file MooseMesh.C.
{
  mooseDeprecated("MooseMesh::node() is deprecated, please use MooseMesh::nodeRef() instead");
  return nodeRef(i);
}
Referenced by MooseMesh::addUniqueNode(), GeneratedMesh::buildMesh(), MooseMesh::buildPeriodicNodeMap(), MooseMesh::cacheInfo(), MooseMesh::detectOrthogonalDimRanges(), MooseMesh::getNodeBlockIds(), MooseMesh::isSemiLocal(), and MooseMesh::updateActiveSemiLocalNodeRange().
nodePtr() [1/2]
Node * MooseMesh::nodePtr (const dof_id_type i) virtual inherited
Definition at line 651 of file MooseMesh.C.
{
  return &nodeRef(i);
}
nodePtr() [2/2]
const Node * MooseMesh::nodePtr (const dof_id_type i) const virtual inherited
Definition at line 645 of file MooseMesh.C.
{
  return &nodeRef(i);
}
Referenced by dataLoad(), ActivateElementsUserObjectBase::updateBoundaryInfo(), and ElementSubdomainModifier::updateComplementBoundaryInfo().
nodeRef() [1/2]
Node & MooseMesh::nodeRef (const dof_id_type i) virtual inherited
Definition at line 639 of file MooseMesh.C.
{
  return const_cast<Node &>(const_cast<const MooseMesh *>(this)->nodeRef(i));
}
nodeRef() [2/2]
const Node & MooseMesh::nodeRef (const dof_id_type i) const virtual inherited
Definition at line 631 of file MooseMesh.C.
{
  const auto node_ptr = queryNodePtr(i);
  mooseAssert(node_ptr, "Missing node");
  return *node_ptr;
}
Referenced by NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), NearestNodeLocator::findNodes(), NonlinearSystemBase::getNodeDofs(), MooseMesh::node(), MooseMesh::nodePtr(), MooseMesh::nodeRef(), ResetDisplacedMeshThread::onNode(), UpdateDisplacedMeshThread::onNode(), NearestNodeThread::operator()(), PenetrationThread::operator()(), SecondaryNeighborhoodThread::operator()(), FEProblemBase::reinitNode(), FEProblemBase::reinitNodeFace(), NonlinearSystemBase::setConstraintSecondaryValues(), EqualValueBoundaryConstraint::updateConstrainedNodes(), and NearestNodeLocator::updatePatch().
nodeSetNodes()
const std::map< boundary_id_type, std::vector< dof_id_type > > & MooseMesh::nodeSetNodes () const inline inherited
Returns
A map from nodeset ids to the vector of node ids in the nodeset
Definition at line 2084 of file MooseMesh.h.
{
  return _node_set_nodes;
}
nodeToActiveSemilocalElemMap()
const std::map< dof_id_type, std::vector< dof_id_type > > & MooseMesh::nodeToActiveSemilocalElemMap () inherited
If not already created, creates a map from every node to all active semilocal elements to which they are connected.
Semilocal elements include local elements and elements that share at least one node with a local element.
Note
Extra ghosted elements are not included in this map!
Definition at line 1003 of file MooseMesh.C.
{
  if (!_node_to_active_semilocal_elem_map_built) // Guard the creation with a double checked lock
  {
    Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
    // This is allowing the timing to be run even with threads
    // This is safe because all threads will be waiting on this section when it runs
    // NOTE: Do not copy this construction to other places without thinking REALLY hard about it
    // The PerfGraph is NOT threadsafe and will cause all kinds of havok if care isn't taken
    auto in_threads = Threads::in_threads;
    Threads::in_threads = false;
    TIME_SECTION("nodeToActiveSemilocalElemMap", 5, "Building SemiLocalElemMap");
    Threads::in_threads = in_threads;
    if (!_node_to_active_semilocal_elem_map_built)
    {
      for (const auto & elem :
           as_range(getMesh().semilocal_elements_begin(), getMesh().semilocal_elements_end()))
        if (elem->active())
          for (unsigned int n = 0; n < elem->n_nodes(); n++)
            _node_to_active_semilocal_elem_map[elem->node_id(n)].push_back(elem->id());
      _node_to_active_semilocal_elem_map_built =
          true; // MUST be set at the end for double-checked locking to work!
    }
  }
  return _node_to_active_semilocal_elem_map;
}
Referenced by DumpObjectsProblem::addAuxVariable().
nodeToElemMap()
const std::map< dof_id_type, std::vector< dof_id_type > > & MooseMesh::nodeToElemMap () inherited
If not already created, creates a map from every node to all elements to which they are connected.
Definition at line 975 of file MooseMesh.C.
{
  if (!_node_to_elem_map_built) // Guard the creation with a double checked lock
  {
    Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
    if (!_node_to_elem_map_built)
    {
      // This is allowing the timing to be run even with threads
      // This is safe because all threads will be waiting on this section when it runs
      // NOTE: Do not copy this construction to other places without thinking REALLY hard about it
      // The PerfGraph is NOT threadsafe and will cause all kinds of havok if care isn't taken
      auto in_threads = Threads::in_threads;
      Threads::in_threads = false;
      TIME_SECTION("nodeToElemMap", 5, "Building Node To Elem Map");
      Threads::in_threads = in_threads;
      for (const auto & elem : getMesh().active_element_ptr_range())
        for (unsigned int n = 0; n < elem->n_nodes(); n++)
          _node_to_elem_map[elem->node_id(n)].push_back(elem->id());
      _node_to_elem_map_built = true; // MUST be set at the end for double-checked locking to work!
    }
  }
  return _node_to_elem_map;
}
Referenced by MultiAppConservativeTransfer::adjustTransferredSolution(), NodalPatchRecovery::compute(), NodalPatchRecoveryAuxBase::computeValue(), ProjectionAux::computeValue(), PenetrationLocator::detectPenetration(), DMMooseGetEmbedding_Private(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), NonlinearSystemBase::findImplicitGeometricCouplingEntries(), NearestNodeLocator::findNodes(), ActivateElementsUserObjectBase::isNewlyActivated(), LinearNodalConstraint::LinearNodalConstraint(), GhostHigherDLowerDPointNeighbors::operator()(), MultiAppGeometricInterpolationTransfer::subdomainIDsNode(), EqualValueBoundaryConstraint::updateConstrainedNodes(), RandomData::updateGenerators(), and NearestNodeLocator::updatePatch().
objectErrorPrefix()
std::string MooseBaseParameterInterface::objectErrorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for an object.
Definition at line 58 of file MooseBaseParameterInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the class \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseParameterInterface::paramErrorMsg().
onMeshChanged()
void MooseMesh::onMeshChanged () virtual inherited
Declares a callback function that is executed at the conclusion of meshChanged().
Ther user can implement actions required after changing the mesh here.
Definition at line 705 of file MooseMesh.C.
{
}
Referenced by MooseMesh::meshChanged().
operator const libMesh::MeshBase &()
MooseMesh::operator const libMesh::MeshBase & () const inherited
Definition at line 3179 of file MooseMesh.C.
{ return getMesh(); }
operator libMesh::MeshBase &()
MooseMesh::operator libMesh::MeshBase & () inherited
Implicit conversion operator from MooseMesh -> libMesh::MeshBase.
Definition at line 3177 of file MooseMesh.C.
{ return getMesh(); }
operator=()
SpiralAnnularMesh & SpiralAnnularMesh::operator= (const SpiralAnnularMesh & other_mesh) delete
ownedElemInfoBegin()
MooseMesh::elem_info_iterator MooseMesh::ownedElemInfoBegin () inherited
Iterators to owned faceInfo objects.
These faceInfo-s are required for the face loops and to filter out the faceInfo-s that are not owned by this processor in case we have a distributed mesh and we included FaceInfo objects that are on processor boundaries
Definition at line 1300 of file MooseMesh.C.
{
  return elem_info_iterator(_elem_info.begin(),
                            _elem_info.end(),
                            Predicates::NotNull<std::vector<const ElemInfo *>::iterator>());
}
Referenced by FEProblemBase::projectSolution().
ownedElemInfoEnd()
MooseMesh::elem_info_iterator MooseMesh::ownedElemInfoEnd () inherited
Definition at line 1308 of file MooseMesh.C.
{
  return elem_info_iterator(_elem_info.end(),
                            _elem_info.end(),
                            Predicates::NotNull<std::vector<const ElemInfo *>::iterator>());
}
Referenced by FEProblemBase::projectSolution().
ownedFaceInfoBegin()
MooseMesh::face_info_iterator MooseMesh::ownedFaceInfoBegin () inherited
Iterators to owned faceInfo objects.
These faceInfo-s are required for the face loops and to filter out the faceInfo-s that are not owned by this processor in case we have a distributed mesh and we included FaceInfo objects that are on processor boundaries
Definition at line 1282 of file MooseMesh.C.
{
  return face_info_iterator(
      _face_info.begin(),
      _face_info.end(),
      libMesh::Predicates::pid<std::vector<const FaceInfo *>::iterator>(this->processor_id()));
}
Referenced by NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualAndJacobianInternal(), and NonlinearSystemBase::computeResidualInternal().
ownedFaceInfoEnd()
MooseMesh::face_info_iterator MooseMesh::ownedFaceInfoEnd () inherited
Definition at line 1291 of file MooseMesh.C.
{
  return face_info_iterator(
      _face_info.end(),
      _face_info.end(),
      libMesh::Predicates::pid<std::vector<const FaceInfo *>::iterator>(this->processor_id()));
}
Referenced by NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualAndJacobianInternal(), and NonlinearSystemBase::computeResidualInternal().
paramError()
template<typename... Args> void MooseBaseParameterInterface::paramError (const std::string & param, Args... args) const inherited
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseError - only printing a message using the given args.
Definition at line 233 of file MooseBaseParameterInterface.h.
{
  Moose::show_trace = false;
  std::string msg = paramErrorMsg(param, std::forward<Args>(args)...);
  callMooseErrorRaw(msg, &_moose_base->getMooseApp());
  Moose::show_trace = true;
}
Referenced by HierarchicalGridPartitioner::_do_partition(), SetupDebugAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), ADDGKernel::ADDGKernel(), ReporterPointSource::addPoints(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ADNodalKernel::ADNodalKernel(), ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), AdvectiveFluxAux::AdvectiveFluxAux(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), ArrayBodyForce::ArrayBodyForce(), ArrayDGKernel::ArrayDGKernel(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayDirichletBC::ArrayDirichletBC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), ArrayPenaltyDirichletBC::ArrayPenaltyDirichletBC(), ArrayVacuumBC::ArrayVacuumBC(), BlockDeletionGenerator::BlockDeletionGenerator(), BlockWeightedPartitioner::BlockWeightedPartitioner(), BoundsAuxBase::BoundsAuxBase(), BreakMeshByBlockGenerator::BreakMeshByBlockGenerator(), BuildArrayVariableAux::BuildArrayVariableAux(), PiecewiseTabularBase::buildFromFile(), CartesianGridDivision::CartesianGridDivision(), UserObjectInterface::castUserObject(), checkComponent(), MeshGenerator::checkGetMesh(), PostprocessorInterface::checkParam(), Coupleable::checkVar(), MultiAppTransfer::checkVariable(), CircularBoundaryCorrectionGenerator::CircularBoundaryCorrectionGenerator(), CircularBoundaryCorrectionGenerator::circularCenterCalculator(), MultiAppGeneralFieldTransfer::closestToPosition(), CombinerGenerator::CombinerGenerator(), CompositionDT::CompositionDT(), ConcentricCircleMeshGenerator::ConcentricCircleMeshGenerator(), LibtorchNeuralNetControl::conditionalParameterError(), ConstantVectorPostprocessor::ConstantVectorPostprocessor(), ContainsPointAux::ContainsPointAux(), CopyValueAux::CopyValueAux(), Coupleable::Coupleable(), CoupledForceTempl< is_ad >::CoupledForceTempl(), CoupledValueFunctionMaterialTempl< is_ad >::CoupledValueFunctionMaterialTempl(), MultiApp::createApp(), MeshGeneratorSystem::createMeshGenerator(), CylindricalGridDivision::CylindricalGridDivision(), ConstantReporter::declareConstantReporterValues(), AccumulateReporter::declareLateValues(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DGLowerDKernel::DGLowerDKernel(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementLengthAux::ElementLengthAux(), ElementLpNormAux::ElementLpNormAux(), ElementValueSampler::ElementValueSampler(), ReporterPointSource::errorCheck(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), ExtraElementIDAux::ExtraElementIDAux(), ExtraElementIntegerDivision::ExtraElementIntegerDivision(), FEProblemSolve::FEProblemSolve(), FillBetweenCurvesGenerator::FillBetweenCurvesGenerator(), FillBetweenSidesetsGenerator::FillBetweenSidesetsGenerator(), ReporterPointSource::fillPoint(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), InternalSideIndicator::finalize(), FixedPointSolve::FixedPointSolve(), ForcingFunctionAux::ForcingFunctionAux(), FunctionArrayAux::FunctionArrayAux(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorAux::FunctorAux(), FunctorBinnedValuesDivision::FunctorBinnedValuesDivision(), FunctorElementalGradientAuxTempl< is_ad >::FunctorElementalGradientAuxTempl(), FunctorPositions::FunctorPositions(), FunctorVectorElementalAuxTempl< is_ad >::FunctorVectorElementalAuxTempl(), FVFluxBC::FVFluxBC(), FVInterfaceKernel::FVInterfaceKernel(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), FVTwoVarContinuityConstraint::FVTwoVarContinuityConstraint(), AdvancedExtruderGenerator::generate(), BlockDeletionGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundaryDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), BreakMeshByBlockGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), CombinerGenerator::generate(), ExplodeMeshGenerator::generate(), ExtraNodesetGenerator::generate(), FillBetweenCurvesGenerator::generate(), FillBetweenSidesetsGenerator::generate(), GeneratedMeshGenerator::generate(), MeshCollectionGenerator::generate(), MeshExtruderGenerator::generate(), ParsedCurveGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), PropertyReadFile::getBlockData(), PropertyReadFile::getData(), Sampler::getGlobalSamples(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), Sampler::getLocalSamples(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), Sampler::getNextLocalRow(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectName(), HFEMDirichletBC::HFEMDirichletBC(), MultiApp::init(), BlockWeightedPartitioner::initialize(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), PiecewiseConstantFromCSV::initialSetup(), LibtorchControlValuePostprocessor::initialSetup(), ReferenceResidualProblem::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), HistogramVectorPostprocessor::initialSetup(), AddMetaDataGenerator::inputChecker(), IntegratedBC::IntegratedBC(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceValueUserObjectAux::InterfaceValueUserObjectAux(), InterpolatedStatefulMaterialTempl< T >::InterpolatedStatefulMaterialTempl(), InversePowerMethod::InversePowerMethod(), IterationAdaptiveDT::IterationAdaptiveDT(), MultiApp::keepSolutionDuringRestore(), Kernel::Kernel(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LinearCombinationFunction::LinearCombinationFunction(), LowerDIntegratedBC::LowerDIntegratedBC(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), MaterialADConverterTempl< T >::MaterialADConverterTempl(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), PatternedMeshGenerator::mergeSubdomainNameMaps(), MeshCollectionGenerator::MeshCollectionGenerator(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshDivisionAux::MeshDivisionAux(), MeshGenerator::MeshGenerator(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarNodalAuxKernelTempl< ComputeValueType >::MortarNodalAuxKernelTempl(), MultiApp::moveApp(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), NestedDivision::NestedDivision(), NodalBC::NodalBC(), NodalEqualValueConstraint::NodalEqualValueConstraint(), NodalKernel::NodalKernel(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), NodalValueSampler::NodalValueSampler(), Output::Output(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), PatchMeshGenerator::PatchMeshGenerator(), PatternedMeshGenerator::PatternedMeshGenerator(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), PeriodicSegmentalConstraint::PeriodicSegmentalConstraint(), PIDTransientControl::PIDTransientControl(), PlaneDeletionGenerator::PlaneDeletionGenerator(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), PolyLineMeshGenerator::PolyLineMeshGenerator(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), LibmeshPartitioner::prepareBlocksForSubdomainPartitioner(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), PropertyReadFile::PropertyReadFile(), RandomIC::RandomIC(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readXda(), ReferenceResidualProblem::ReferenceResidualProblem(), RefineBlockGenerator::RefineBlockGenerator(), RefineSidesetGenerator::RefineSidesetGenerator(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setPartitioner(), TimeSequenceStepperBase::setupSequence(), SingleRankPartitioner::SingleRankPartitioner(), SphericalGridDivision::SphericalGridDivision(), SymmetryTransformGenerator::SymmetryTransformGenerator(), Terminator::Terminator(), TimeDerivativeAux::TimeDerivativeAux(), Transfer::Transfer(), TransformGenerator::TransformGenerator(), TransientMultiApp::TransientMultiApp(), ParsedCurveGenerator::tSectionSpaceDefiner(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), UserObject::UserObject(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), VolumeAux::VolumeAux(), XYDelaunayGenerator::XYDelaunayGenerator(), and XYMeshLineCutter::XYMeshLineCutter().
paramErrorMsg()
template<typename... Args> std::string MooseBaseParameterInterface::paramErrorMsg (const std::string & param, Args... args) const inline private inherited
Definition at line 171 of file MooseBaseParameterInterface.h.
  {
    auto param_prefix = paramErrorPrefix(_pars, param);
    // With no input location information, append object info (name + type)
    const std::string object_prefix =
        _pars.inputLocation(param).empty() ? objectErrorPrefix("parameter error") : "";
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    // Wrap error message to a separate line from param_prefix if it is about to
    // blow past 100 chars.  But only wrap if the param_prefix is long enough (12
    // chars) for the wrap to buy us much extra length. We don't check object_prefix
    // here because it will go before the parameter error
    if ((param_prefix.size() > 12 && msg.size() + param_prefix.size() > 99) ||
        msg.find("\n") != std::string::npos)
    {
      if (param_prefix.size() > 0 && param_prefix[param_prefix.size() - 1] != ':')
        param_prefix += ":";
      return object_prefix + param_prefix + "\n    " + MooseUtils::replaceAll(msg, "\n", "\n    ");
    }
    return object_prefix + param_prefix + " " + msg;
  }
Referenced by MooseBaseParameterInterface::paramError(), MooseBaseParameterInterface::paramInfo(), and MooseBaseParameterInterface::paramWarning().
parameters()
const InputParameters & MooseBaseParameterInterface::parameters () const inline inherited
Get the parameters of the object.
Returns
The parameters of the object
Definition at line 53 of file MooseBaseParameterInterface.h.
{ return _pars; }
Referenced by SetupDebugAction::act(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), FEProblemBase::addPostprocessor(), FEProblemBase::addPredictor(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), AdvancedOutput::AdvancedOutput(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), Moose::assemble_matrix(), AuxScalarKernel::AuxScalarKernel(), BoundsAuxBase::BoundsAuxBase(), MooseMesh::buildTypedMesh(), UserObjectInterface::castUserObject(), PostprocessorInterface::checkParam(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), Moose::compute_bounds(), Moose::compute_jacobian(), Moose::compute_nearnullspace(), Moose::compute_nullspace(), Moose::compute_postcheck(), Moose::compute_transpose_nullspace(), LibtorchNeuralNetControl::conditionalParameterError(), Console::Console(), MultiApp::createApp(), Postprocessor::declareValue(), DumpObjectsProblem::deduceNecessaryParameters(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), DumpObjectsProblem::dumpObjectHelper(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElectronsFromIonization::ElectronsFromIonization(), Executor::Executor(), Exodus::Exodus(), FEProblem::FEProblem(), FEProblemBase::FEProblemBase(), FixedPointSolve::FixedPointSolve(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GapValueAux::GapValueAux(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), MooseBaseParameterInterface::getCheckedPointerParam(), ExecutorInterface::getExecutor(), Material::getMaterial(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), UserObjectInterface::getUserObjectName(), VectorPostprocessorInterface::getVectorPostprocessorName(), GhostingUserObject::GhostingUserObject(), HphiRadialInterface::HphiRadialInterface(), AttribSystem::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), FullSolveMultiApp::initialSetup(), FEProblemBase::initNullSpaceVectors(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), isValid(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseAppCoordTransform::MooseAppCoordTransform(), MooseVariableInterface< T >::MooseVariableInterface(), MultiApp::MultiApp(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodeFaceConstraint::NodeFaceConstraint(), PatchMeshGenerator::PatchMeshGenerator(), PenetrationAux::PenetrationAux(), PicardSolve::PicardSolve(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), ProjectedStatefulMaterialStorageAction::processProperty(), MultiAppProjectionTransfer::projectSolution(), PropertyReadFile::PropertyReadFile(), PseudoTimestep::PseudoTimestep(), RandomIC::RandomIC(), InputParameterWarehouse::removeInputParameters(), OutputWarehouse::resetFileBase(), MooseAppCoordTransform::setCoordinateSystem(), FEProblemBase::setInputParametersFEProblem(), FEProblem::setInputParametersFEProblem(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SteffensenSolve::SteffensenSolve(), DumpObjectsProblem::stringifyParameters(), TaggingInterface::TaggingInterface(), Transfer::Transfer(), Transient::Transient(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
paramInfo()
template<typename... Args> void MooseBaseParameterInterface::paramInfo (const std::string & param, Args... args) const inherited
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseInfo - only printing a message using the given args.
Definition at line 250 of file MooseBaseParameterInterface.h.
{
  mooseInfo(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by TransientMultiApp::TransientMultiApp().
paramWarning()
template<typename... Args> void MooseBaseParameterInterface::paramWarning (const std::string & param, Args... args) const inherited
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseWarning - only printing a message using the given args.
Definition at line 243 of file MooseBaseParameterInterface.h.
{
  mooseWarning(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by MultiAppNearestNodeTransfer::execute(), FEProblemSolve::FEProblemSolve(), PlaneIDMeshGenerator::generate(), UniqueExtraIDMeshGenerator::generate(), Terminator::initialSetup(), and MooseMesh::MooseMesh().
partitionerName()
const MooseEnum & MooseMesh::partitionerName () const inline inherited
Definition at line 996 of file MooseMesh.h.
{ return _partitioner_name; }
Referenced by ConsoleUtils::outputMeshInformation().
partitioning()
MooseEnum MooseMesh::partitioning () static inherited
returns MooseMesh partitioning options so other classes can use it
Definition at line 3637 of file MooseMesh.C.
{
  MooseEnum partitioning("default=-3 metis=-2 parmetis=-1 linear=0 centroid hilbert_sfc morton_sfc",
                         "default");
  return partitioning;
}
Referenced by MooseMesh::partitioning(), and MooseMesh::validParams().
perfGraph()
PerfGraph & PerfGraphInterface::perfGraph () inherited
Get the PerfGraph.
Definition at line 78 of file PerfGraphInterface.C.
{
  return _pg_moose_app.perfGraph();
}
Referenced by CommonOutputAction::act(), PerfGraphData::finalize(), and PerfGraphOutput::output().
prepare()
bool MooseMesh::prepare (const MeshBase * mesh_to_clone) inherited
Calls prepare_for_use() if the underlying MeshBase object isn't prepared, then communicates various boundary information on parallel meshes.
Also calls update() internally. Instead of calling prepare_for_use on the currently held MeshBase object, a mesh_to_clone can be provided. If it is provided (e.g. this method is given a non-null argument), then _mesh will be assigned a clone of the mesh_to_clone. The provided mesh_to_clone must already be prepared
Parameters
mesh_to_clone If nonnull, we will clone this mesh instead of preparing our current one
Returns
Whether the libMesh mesh was prepared. This should really only be relevant in MOOSE framework contexts where we need to make a decision about what to do with the displaced mesh. If the reference mesh base object has prepare_for_use called (e.g. this method returns true when called for the reference mesh), then we must pass the reference mesh base object into this method when we call this for the displaced mesh. This is because the displaced mesh \emph must be an exact clone of the reference mesh. We have seen that prepare_for_use called on two previously identical meshes can result in two different meshes even with Metis partitioning
Definition at line 361 of file MooseMesh.C.
{
  TIME_SECTION("prepare", 2, "Preparing Mesh", true);
  bool called_prepare_for_use = false;
  mooseAssert(_mesh, "The MeshBase has not been constructed");
  if (!dynamic_cast<DistributedMesh *>(&getMesh()) || _is_nemesis)
    // For whatever reason we do not want to allow renumbering here nor ever in the future?
    getMesh().allow_renumbering(false);
  if (mesh_to_clone)
  {
    mooseAssert(mesh_to_clone->is_prepared(),
                "The mesh we wish to clone from must already be prepared");
    _mesh = mesh_to_clone->clone();
    _moose_mesh_prepared = false;
  }
  else if (!_mesh->is_prepared())
  {
    _mesh->prepare_for_use();
    _moose_mesh_prepared = false;
    called_prepare_for_use = true;
  }
  if (_moose_mesh_prepared)
    return called_prepare_for_use;
  // Collect (local) subdomain IDs
  _mesh_subdomains.clear();
  for (const auto & elem : getMesh().element_ptr_range())
    _mesh_subdomains.insert(elem->subdomain_id());
  // add explicitly requested subdomains
  if (isParamValid("add_subdomain_ids"))
  {
    const auto add_subdomain_id = getParam<std::vector<SubdomainID>>("add_subdomain_ids");
    _mesh_subdomains.insert(add_subdomain_id.begin(), add_subdomain_id.end());
  }
  // Make sure nodesets have been generated
  buildNodeListFromSideList();
  // Collect (local) boundary IDs
  const std::set<BoundaryID> & local_bids = getMesh().get_boundary_info().get_boundary_ids();
  _mesh_boundary_ids.insert(local_bids.begin(), local_bids.end());
  const std::set<BoundaryID> & local_node_bids =
      getMesh().get_boundary_info().get_node_boundary_ids();
  _mesh_nodeset_ids.insert(local_node_bids.begin(), local_node_bids.end());
  const std::set<BoundaryID> & local_side_bids =
      getMesh().get_boundary_info().get_side_boundary_ids();
  _mesh_sideset_ids.insert(local_side_bids.begin(), local_side_bids.end());
  // Communicate subdomain and boundary IDs if this is a parallel mesh
  if (!getMesh().is_serial())
  {
    _communicator.set_union(_mesh_subdomains);
    _communicator.set_union(_mesh_boundary_ids);
    _communicator.set_union(_mesh_nodeset_ids);
    _communicator.set_union(_mesh_sideset_ids);
  }
  if (!_built_from_other_mesh)
  {
    if (!_coord_system_set)
      setCoordSystem(_provided_coord_blocks, getParam<MultiMooseEnum>("coord_type"));
    else if (_pars.isParamSetByUser("coord_type"))
      mooseError(
          "Trying to set coordinate system type information based on the user input file, but "
          "the coordinate system type information has already been set programmatically! "
          "Either remove your coordinate system type information from the input file, or contact "
          "your application developer");
  }
  // Set general axisymmetric axes if provided
  if (isParamValid("rz_coord_blocks") && isParamValid("rz_coord_origins") &&
      isParamValid("rz_coord_directions"))
  {
    const auto rz_coord_blocks = getParam<std::vector<SubdomainName>>("rz_coord_blocks");
    const auto rz_coord_origins = getParam<std::vector<Point>>("rz_coord_origins");
    const auto rz_coord_directions = getParam<std::vector<RealVectorValue>>("rz_coord_directions");
    if (rz_coord_origins.size() == rz_coord_blocks.size() &&
        rz_coord_directions.size() == rz_coord_blocks.size())
    {
      std::vector<std::pair<Point, RealVectorValue>> rz_coord_axes;
      for (unsigned int i = 0; i < rz_coord_origins.size(); ++i)
        rz_coord_axes.push_back(std::make_pair(rz_coord_origins[i], rz_coord_directions[i]));
      setGeneralAxisymmetricCoordAxes(rz_coord_blocks, rz_coord_axes);
      if (isParamSetByUser("rz_coord_axis"))
        mooseError("The parameter 'rz_coord_axis' may not be provided if 'rz_coord_blocks', "
                   "'rz_coord_origins', and 'rz_coord_directions' are provided.");
    }
    else
      mooseError("The parameters 'rz_coord_blocks', 'rz_coord_origins', and "
                 "'rz_coord_directions' must all have the same size.");
  }
  else if (isParamValid("rz_coord_blocks") || isParamValid("rz_coord_origins") ||
           isParamValid("rz_coord_directions"))
    mooseError("If any of the parameters 'rz_coord_blocks', 'rz_coord_origins', and "
               "'rz_coord_directions' are provided, then all must be provided.");
  detectOrthogonalDimRanges();
  update();
  // Check if there is subdomain name duplication for the same subdomain ID
  checkDuplicateSubdomainNames();
  _moose_mesh_prepared = true;
  return called_prepare_for_use;
}
prepared() [1/2]
bool MooseMesh::prepared () const inherited
Setter/getter for whether the mesh is prepared.
Definition at line 2877 of file MooseMesh.C.
{
  return _mesh->is_prepared() && _moose_mesh_prepared;
}
Referenced by MooseMesh::needsPrepareForUse(), AnnularMesh::prepared(), and GeneratedMesh::prepared().
prepared() [2/2]
void MooseMesh::prepared (bool state) virtual inherited
If we are explicitly setting the mesh to not prepared, then we've likely modified the mesh and can no longer make assumptions about orthogonality. We really should recheck.
Reimplemented in AnnularMesh, and GeneratedMesh.
Definition at line 2883 of file MooseMesh.C.
{
  if (state)
    mooseError("We don't have any right to tell the libmesh mesh that it *is* prepared. Only a "
               "call to prepare_for_use should tell us that");
  // Some people may call this even before we have a MeshBase object. This isn't dangerous really
  // because when the MeshBase object is born, it knows it's in an unprepared state
  if (_mesh)
    _mesh->set_isnt_prepared();
  // If the libMesh mesh isn't preparead, then our MooseMesh wrapper is also no longer prepared
  _moose_mesh_prepared = false;
  _regular_orthogonal_mesh = false;
}
printInfo()
void MooseMesh::printInfo (std::ostream & os = libMesh::out, const unsigned int verbosity = 0) const inherited
Calls print_info() on the underlying Mesh.
Definition at line 3202 of file MooseMesh.C.
{
  os << '\n';
  getMesh().print_info(os, verbosity);
  os << std::flush;
}
Referenced by Adaptivity::adaptMesh().
queryElemPtr() [1/2]
Elem * MooseMesh::queryElemPtr (const dof_id_type i) virtual inherited
Definition at line 2865 of file MooseMesh.C.
{
  return getMesh().query_elem_ptr(i);
}
Referenced by PointSamplerBase::getLocalElemContainingPoint(), DisplacedProblem::reinitElemPhys(), FEProblemBase::reinitElemPhys(), DisplacedProblem::reinitNeighborPhys(), FEProblemBase::reinitNeighborPhys(), and EqualValueBoundaryConstraint::updateConstrainedNodes().
queryElemPtr() [2/2]
const Elem * MooseMesh::queryElemPtr (const dof_id_type i) const virtual inherited
Definition at line 2871 of file MooseMesh.C.
{
  return getMesh().query_elem_ptr(i);
}
queryNodePtr() [1/2]
Node * MooseMesh::queryNodePtr (const dof_id_type i) virtual inherited
Definition at line 673 of file MooseMesh.C.
{
  return const_cast<Node *>(const_cast<const MooseMesh *>(this)->queryNodePtr(i));
}
queryNodePtr() [2/2]
const Node * MooseMesh::queryNodePtr (const dof_id_type i) const virtual inherited
Definition at line 657 of file MooseMesh.C.
{
  if (i > getMesh().max_node_id())
  {
    auto it = _quadrature_nodes.find(i);
    if (it == _quadrature_nodes.end())
      return nullptr;
    auto & node_ptr = it->second;
    mooseAssert(node_ptr, "Uninitialized quadrature node");
    return node_ptr;
  }
  return getMesh().query_node_ptr(i);
}
Referenced by NonlinearSystemBase::findImplicitGeometricCouplingEntries(), MooseMesh::nodeRef(), MooseMesh::queryNodePtr(), and EqualValueBoundaryConstraint::updateConstrainedNodes().
refinedElementRange()
ConstElemPointerRange * MooseMesh::refinedElementRange () const inherited
Return a range that is suitable for threaded execution over elements that were just refined.
Returns
The Parent elements that are now set to be INACTIVE. Their children are the new elements.
Definition at line 728 of file MooseMesh.C.
{
  return _refined_elements.get();
}
Referenced by FEProblemBase::meshChangedHelper().
registerRestartableDataOnApp()
RestartableDataValue & Restartable::registerRestartableDataOnApp (std::unique_ptr< RestartableDataValue > data, THREAD_ID tid) const private inherited
Helper function for actually registering the restartable data.
Definition at line 51 of file Restartable.C.
{
  return _restartable_app.registerRestartableData(
      std::move(data), tid, _restartable_read_only, _metaname);
}
Referenced by Restartable::declareRestartableDataHelper().
registerRestartableNameWithFilterOnApp()
void Restartable::registerRestartableNameWithFilterOnApp (const std::string & name, Moose::RESTARTABLE_FILTER filter) private inherited
Helper function for actually registering the restartable data.
Definition at line 59 of file Restartable.C.
{
  _restartable_app.registerRestartableNameWithFilter(name, filter);
}
Referenced by Restartable::declareRecoverableData().
registerTimedSection() [1/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
Returns
The ID of the section - use when starting timing
Definition at line 53 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(timed_section_name, level);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
registerTimedSection() [2/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level, const std::string & live_message, const bool print_dots = true) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
live_message The message to be printed to the screen during execution
print_dots Whether or not progress dots should be printed for this section
Returns
The ID of the section - use when starting timing
Definition at line 64 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(
        timedSectionName(section_name), level, live_message, print_dots);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
restartableName()
std::string Restartable::restartableName (const std::string & data_name) const protected inherited
Gets the name of a piece of restartable data given a data name, adding the system name and object name prefix.
This should only be used in this interface and in testing.
Definition at line 66 of file Restartable.C.
{
  return _restartable_system_name + "/" + _restartable_name + "/" + data_name;
}
Referenced by Restartable::declareRecoverableData(), and Restartable::declareRestartableDataHelper().
safeClone()
std::unique_ptr< MooseMesh > SpiralAnnularMesh::safeClone () const override virtual
A safer version of the clone() method that hands back an allocated object wrapped in a smart pointer.
This makes it much less likely that the caller will leak the memory in question.
Implements MooseMesh.
Definition at line 66 of file SpiralAnnularMesh.C.
{
  return std::make_unique<SpiralAnnularMesh>(*this);
}
setAxisymmetricCoordAxis()
void MooseMesh::setAxisymmetricCoordAxis (const MooseEnum & rz_coord_axis) inherited
For axisymmetric simulations, set the symmetry coordinate axis.
For r in the x-direction, z in the y-direction the coordinate axis would be y
Definition at line 3911 of file MooseMesh.C.
{
  _rz_coord_axis = rz_coord_axis;
  updateCoordTransform();
}
Referenced by FEProblemBase::setAxisymmetricCoordAxis().
setBoundaryName()
void MooseMesh::setBoundaryName (BoundaryID boundary_id, BoundaryName name) inherited
This method sets the boundary name of the boundary based on the id parameter.
Definition at line 1544 of file MooseMesh.C.
{
  BoundaryInfo & boundary_info = getMesh().get_boundary_info();
  // We need to figure out if this boundary is a sideset or nodeset
  if (boundary_info.get_side_boundary_ids().count(boundary_id))
    boundary_info.sideset_name(boundary_id) = name;
  else
    boundary_info.nodeset_name(boundary_id) = name;
}
Referenced by ElementSubdomainModifier::setComplementMovingBoundaryName(), ElementSubdomainModifier::setMovingBoundaryName(), ActivateElementsUserObjectBase::setNewBoundayName(), and SetupMeshAction::setupMesh().
setBoundaryToNormalMap() [1/2]
void MooseMesh::setBoundaryToNormalMap (std::map< BoundaryID, RealVectorValue > * boundary_map) inherited
Definition at line 2948 of file MooseMesh.C.
{
  mooseDeprecated("setBoundaryToNormalMap(std::map<BoundaryID, RealVectorValue> * boundary_map) is "
                  "deprecated, use the unique_ptr version instead");
  _boundary_to_normal_map.reset(boundary_map);
}
setBoundaryToNormalMap() [2/2]
void MooseMesh::setBoundaryToNormalMap (std::unique_ptr< std::map< BoundaryID, RealVectorValue > > boundary_map) inherited
Sets the mapping between BoundaryID and normal vector Is called by AddAllSideSetsByNormals.
Definition at line 2941 of file MooseMesh.C.
{
  _boundary_to_normal_map = std::move(boundary_map);
}
setCoordData()
void MooseMesh::setCoordData (const MooseMesh & other_mesh) inherited
Set the coordinate system data to that of other_mesh.
Definition at line 4020 of file MooseMesh.C.
{
  _coord_sys = other_mesh._coord_sys;
  _rz_coord_axis = other_mesh._rz_coord_axis;
  _subdomain_id_to_rz_coord_axis = other_mesh._subdomain_id_to_rz_coord_axis;
}
Referenced by DisplacedProblem::DisplacedProblem().
setCoordSystem()
void MooseMesh::setCoordSystem (const std::vector< SubdomainName > & blocks, const MultiMooseEnum & coord_sys) inherited
Set the coordinate system for the provided blocks to coord_sys.
Definition at line 3805 of file MooseMesh.C.
{
  TIME_SECTION("setCoordSystem", 5, "Setting Coordinate System");
  if (!_provided_coord_blocks.empty() && (_provided_coord_blocks != blocks))
  {
    const std::string param_name = isParamValid("coord_block") ? "coord_block" : "block";
    mooseWarning("Supplied blocks in the 'setCoordSystem' method do not match the value of the "
                 "'Mesh/",
                 param_name,
                 "' parameter. Did you provide different parameter values for 'Mesh/",
                 param_name,
                 "' and 'Problem/block'?. We will honor the parameter value from 'Mesh/",
                 param_name,
                 "'");
    mooseAssert(_coord_system_set,
                "If we are arriving here due to a bad specification in the Problem block, then we "
                "should have already set our coordinate system subdomains from the Mesh block");
    return;
  }
  if (_pars.isParamSetByUser("coord_type") && getParam<MultiMooseEnum>("coord_type") != coord_sys)
    mooseError("Supplied coordinate systems in the 'setCoordSystem' method do not match the value "
               "of the 'Mesh/coord_type' parameter. Did you provide different parameter values for "
               "'coord_type' to 'Mesh' and 'Problem'?");
  auto subdomains = meshSubdomains();
  // It's possible that a user has called this API before the mesh is prepared and consequently we
  // don't yet have the subdomains in meshSubdomains()
  for (const auto & sub_name : blocks)
  {
    const auto sub_id = getSubdomainID(sub_name);
    subdomains.insert(sub_id);
  }
  if (coord_sys.size() <= 1)
  {
    // We will specify the same coordinate system for all blocks
    const auto coord_type = coord_sys.size() == 0
                                ? Moose::COORD_XYZ
                                : Moose::stringToEnum<Moose::CoordinateSystemType>(coord_sys[0]);
    for (const auto sid : subdomains)
      _coord_sys[sid] = coord_type;
  }
  else
  {
    if (blocks.size() != coord_sys.size())
      mooseError("Number of blocks and coordinate systems does not match.");
    for (const auto i : index_range(blocks))
    {
      SubdomainID sid = getSubdomainID(blocks[i]);
      Moose::CoordinateSystemType coord_type =
          Moose::stringToEnum<Moose::CoordinateSystemType>(coord_sys[i]);
      _coord_sys[sid] = coord_type;
    }
    for (const auto & sid : subdomains)
      if (_coord_sys.find(sid) == _coord_sys.end())
        mooseError("Subdomain '" + Moose::stringify(sid) +
                   "' does not have a coordinate system specified.");
  }
  _coord_system_set = true;
  updateCoordTransform();
}
Referenced by MooseMesh::prepare(), and FEProblemBase::setCoordSystem().
setCustomPartitioner()
void MooseMesh::setCustomPartitioner (Partitioner * partitioner) inherited
Setter for custom partitioner.
Definition at line 3436 of file MooseMesh.C.
{
  _custom_partitioner = partitioner->clone();
}
setGeneralAxisymmetricCoordAxes()
void MooseMesh::setGeneralAxisymmetricCoordAxes (const std::vector< SubdomainName > & blocks, const std::vector< std::pair< Point, RealVectorValue > > & axes) inherited
Sets the general coordinate axes for axisymmetric blocks.
This method must be used if any of the following are true:
There are multiple axisymmetric coordinate systems
Any axisymmetric coordinate system axis/direction is not the +X or +Y axis
Any axisymmetric coordinate system does not start at (0,0,0)
Parameters
[in] blocks Subdomain names
[in] axes Pair of values defining the axisymmetric coordinate axis for each subdomain. The first value is the point on the axis corresponding to the origin. The second value is the direction vector of the axis (normalization not necessary).
Definition at line 3919 of file MooseMesh.C.
{
  // Set the axes for the given blocks
  mooseAssert(blocks.size() == axes.size(), "Blocks and axes vectors must be the same length.");
  for (const auto i : index_range(blocks))
  {
    const auto subdomain_id = getSubdomainID(blocks[i]);
    const auto it = _coord_sys.find(subdomain_id);
    if (it == _coord_sys.end())
      mooseError("The block '",
                 blocks[i],
                 "' has not set a coordinate system. Make sure to call setCoordSystem() before "
                 "setGeneralAxisymmetricCoordAxes().");
    else
    {
      if (it->second == Moose::COORD_RZ)
      {
        const auto direction = axes[i].second;
        if (direction.is_zero())
          mooseError("Only nonzero vectors may be supplied for RZ directions.");
        _subdomain_id_to_rz_coord_axis[subdomain_id] =
            std::make_pair(axes[i].first, direction.unit());
      }
      else
        mooseError("The block '",
                   blocks[i],
                   "' was provided in setGeneralAxisymmetricCoordAxes(), but the coordinate system "
                   "for this block is not 'RZ'.");
    }
  }
  // Make sure there are no RZ blocks that still do not have axes
  const auto all_subdomain_ids = meshSubdomains();
  for (const auto subdomain_id : all_subdomain_ids)
    if (getCoordSystem(subdomain_id) == Moose::COORD_RZ &&
        !_subdomain_id_to_rz_coord_axis.count(subdomain_id))
      mooseError("The block '",
                 getSubdomainName(subdomain_id),
                 "' was specified to use the 'RZ' coordinate system but was not given in "
                 "setGeneralAxisymmetricCoordAxes().");
  updateCoordTransform();
}
Referenced by MooseMesh::prepare().
setGhostedBoundaryInflation()
void MooseMesh::setGhostedBoundaryInflation (const std::vector< Real > & inflation) inherited
This sets the inflation amount for the bounding box for each partition for use in ghosting boundaries.
Definition at line 2975 of file MooseMesh.C.
{
  _ghosted_boundaries_inflation = inflation;
}
Referenced by SetupMeshAction::setupMesh().
setIsCustomPartitionerRequested()
void MooseMesh::setIsCustomPartitionerRequested (bool cpr) inherited
Definition at line 3464 of file MooseMesh.C.
{
  _custom_partitioner_requested = cpr;
}
setMeshBase()
void MooseMesh::setMeshBase (std::unique_ptr< MeshBase > mesh_base) inherited
Method to set the mesh_base object.
If this method is NOT called prior to calling init(), a MeshBase object will be automatically constructed and set.
Definition at line 2608 of file MooseMesh.C.
{
  _mesh = std::move(mesh_base);
  _mesh->allow_remote_element_removal(_allow_remote_element_removal);
}
setMeshBoundaryIDs()
void MooseMesh::setMeshBoundaryIDs (std::set< BoundaryID > boundary_IDs) inherited
Sets the set of BoundaryIDs Is called by AddAllSideSetsByNormals.
Definition at line 2935 of file MooseMesh.C.
{
  _mesh_boundary_ids = boundary_IDs;
}
setParallelType()
void MooseMesh::setParallelType (ParallelType parallel_type) inline inherited
Allow to change parallel type.
Definition at line 2043 of file MooseMesh.h.
{
  _parallel_type = parallel_type;
  determineUseDistributedMesh();
}
Referenced by MooseMesh::buildTypedMesh().
setPartitioner()
void MooseMesh::setPartitioner (MeshBase & mesh_base, MooseEnum & partitioner, bool use_distributed_mesh, const InputParameters & params, MooseObject & context_obj) static inherited
Method for setting the partitioner on the passed in mesh_base object.
Definition at line 3381 of file MooseMesh.C.
{
  // Set the partitioner based on partitioner name
  switch (partitioner)
  {
    case -3: // default
      // We'll use the default partitioner, but notify the user of which one is being used...
      if (use_distributed_mesh)
        partitioner = "parmetis";
      else
        partitioner = "metis";
      break;
    // No need to explicitily create the metis or parmetis partitioners,
    // They are the default for serial and parallel mesh respectively
    case -2: // metis
    case -1: // parmetis
      break;
    case 0: // linear
      mesh_base.partitioner().reset(new LinearPartitioner);
      break;
    case 1: // centroid
    {
      if (!params.isParamValid("centroid_partitioner_direction"))
        context_obj.paramError(
            "centroid_partitioner_direction",
            "If using the centroid partitioner you _must_ specify centroid_partitioner_direction!");
      MooseEnum direction = params.get<MooseEnum>("centroid_partitioner_direction");
      if (direction == "x")
        mesh_base.partitioner().reset(new CentroidPartitioner(CentroidPartitioner::X));
      else if (direction == "y")
        mesh_base.partitioner().reset(new CentroidPartitioner(CentroidPartitioner::Y));
      else if (direction == "z")
        mesh_base.partitioner().reset(new CentroidPartitioner(CentroidPartitioner::Z));
      else if (direction == "radial")
        mesh_base.partitioner().reset(new CentroidPartitioner(CentroidPartitioner::RADIAL));
      break;
    }
    case 2: // hilbert_sfc
      mesh_base.partitioner().reset(new HilbertSFCPartitioner);
      break;
    case 3: // morton_sfc
      mesh_base.partitioner().reset(new MortonSFCPartitioner);
      break;
  }
}
Referenced by MooseMesh::setPartitionerHelper().
setPartitionerHelper()
void MooseMesh::setPartitionerHelper (MeshBase * mesh = nullptr) protected inherited
Definition at line 3369 of file MooseMesh.C.
{
  if (_use_distributed_mesh && (_partitioner_name != "default" && _partitioner_name != "parmetis"))
  {
    _partitioner_name = "parmetis";
    _partitioner_overridden = true;
  }
  setPartitioner(mesh ? *mesh : getMesh(), _partitioner_name, _use_distributed_mesh, _pars, *this);
}
Referenced by MooseMesh::buildTypedMesh().
setPatchUpdateStrategy()
void MooseMesh::setPatchUpdateStrategy (Moose::PatchUpdateType patch_update_strategy) inherited
Set the patch size update strategy.
Definition at line 3147 of file MooseMesh.C.
{
  _patch_update_strategy = patch_update_strategy;
}
setSubdomainName() [1/2]
void MooseMesh::setSubdomainName (MeshBase & mesh, SubdomainID subdomain_id, const SubdomainName & name) static inherited
This method sets the name for subdomain_id on the provided mesh to name.
Definition at line 1521 of file MooseMesh.C.
{
  mesh.subdomain_name(subdomain_id) = name;
}
setSubdomainName() [2/2]
void MooseMesh::setSubdomainName (SubdomainID subdomain_id, const SubdomainName & name) inherited
This method sets the name for subdomain_id to name.
Definition at line 1515 of file MooseMesh.C.
{
  getMesh().subdomain_name(subdomain_id) = name;
}
Referenced by MooseMesh::MooseMesh(), and SetupMeshAction::setupMesh().
setUniformRefineLevel()
void MooseMesh::setUniformRefineLevel (unsigned int level, bool deletion = true) inherited
Set uniform refinement level.
Definition at line 2962 of file MooseMesh.C.
{
  _uniform_refine_level = level;
  _skip_deletion_repartition_after_refine = deletion;
}
Referenced by SetupMeshAction::setupMesh().
setupFiniteVolumeMeshData()
void MooseMesh::setupFiniteVolumeMeshData () const inherited
Sets up the additional data needed for finite volume computations.
This involves building FaceInfo and ElemInfo objects, caching variable associations and elemental DoF indices for FV variables.
Definition at line 3796 of file MooseMesh.C.
{
  buildFiniteVolumeInfo();
  computeFiniteVolumeCoords();
  cacheFaceInfoVariableOwnership();
  cacheFVElementalDoFs();
}
Referenced by DisplacedProblem::init(), FEProblemBase::init(), FEProblemBase::meshChangedHelper(), and DisplacedProblem::updateMesh().
sideWithBoundaryID()
unsigned int MooseMesh::sideWithBoundaryID (const Elem *const elem, const BoundaryID boundary_id) const inherited
Calls BoundaryInfo::side_with_boundary_id().
Definition at line 2761 of file MooseMesh.C.
{
  return getMesh().get_boundary_info().side_with_boundary_id(elem, boundary_id);
}
skipDeletionRepartitionAfterRefine()
bool MooseMesh::skipDeletionRepartitionAfterRefine () const inline inherited
Return a flag indicating whether or not we should skip remote deletion and repartition after uniform refinements.
If the flag is true, uniform refinements will run more efficiently, but at the same time, there might be extra ghosting elements. The number of layers of additional ghosting elements depends on the number of uniform refinement levels. This flag should be used only when you have a "fine enough" coarse mesh and want to refine the mesh by a few levels. Otherwise, it might introduce an unbalanced workload and too large ghosting domain.
Definition at line 2037 of file MooseMesh.h.
{
  return _skip_deletion_repartition_after_refine;
}
Referenced by Adaptivity::uniformRefine().
skipRefineWhenUseSplit()
bool MooseMesh::skipRefineWhenUseSplit () const inline inherited
Whether or not skip uniform refinements when using a pre-split mesh.
Definition at line 567 of file MooseMesh.h.
{ return _skip_refine_when_use_split; }
timedSectionName()
std::string PerfGraphInterface::timedSectionName (const std::string & section_name) const protected inherited
Returns
The name of the timed section with the name section_name.
Optionally adds a prefix if one is defined.
Definition at line 47 of file PerfGraphInterface.C.
{
  return _prefix.empty() ? "" : (_prefix + "::") + section_name;
}
Referenced by PerfGraphInterface::registerTimedSection().
type()
const std::string & MooseBase::type () const inline inherited
Get the type of this class.
Returns
the name of the type of this class
Definition at line 41 of file MooseBase.h.
{ return _type; }
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), CreateProblemDefaultAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetupDebugAction::act(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::addDistribution(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addObject(), DistributedRectilinearMeshGenerator::addPoint(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), PhysicsBasedPreconditioner::addSystem(), FEProblemBase::addTimeIntegrator(), SubProblem::addVectorTag(), DisplacedProblem::addVectorTag(), FEProblemBase::advanceMultiApps(), FEProblemBase::backupMultiApps(), BoundaryPreservedMarker::BoundaryPreservedMarker(), DistributedRectilinearMeshGenerator::buildCube(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildPRefinementAndCoarseningMaps(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), FEProblemBase::computeAuxiliaryKernels(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpJacobian(), HFEMDirichletBC::computeLowerDQpJacobian(), ArrayHFEMDiffusion::computeLowerDQpJacobian(), HFEMDiffusion::computeLowerDQpJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), FEProblemBase::computeMultiAppsDT(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), DGCoupledAdvection::computeOffDiagJacobianHelper(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ScalarKernel::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueBoundaryConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), LinearNodalConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), DGConvection::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), InterfaceDiffusion::computeQpJacobian(), InterfaceReaction::computeQpJacobian(), DGCoupledAdvection::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), DGFunctionTemperatureAdvection::computeQpJacobian(), DGTemperatureAdvection::computeQpJacobian(), InterTemperatureAdvection::computeQpJacobian(), CoupledTiedValueConstraint::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), HFEMTestJump::computeQpOffDiagJacobian(), HFEMTrialJump::computeQpOffDiagJacobian(), DGCoupledAdvection::computeQpOffDiagJacobian(), ScalarKernel::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), EqualValueBoundaryConstraint::computeQpResidual(), EqualValueEmbeddedConstraint::computeQpResidual(), LinearNodalConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), DGConvection::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), DGEFieldAdvection::computeQpResidual(), HphiRadialInterface::computeQpResidual(), InterfaceAdvection::computeQpResidual(), InterfaceLogDiffusionElectrons::computeQpResidual(), PotentialSurfaceCharge::computeQpResidual(), ADDGAdvection::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), HFEMDiffusion::computeQpResidual(), HFEMTestJump::computeQpResidual(), HFEMTrialJump::computeQpResidual(), InterfaceDiffusion::computeQpResidual(), InterfaceReaction::computeQpResidual(), DGCoupledAdvection::computeQpResidual(), DGFunctionConvection::computeQpResidual(), DGFunctionTemperatureAdvection::computeQpResidual(), DGTemperatureAdvection::computeQpResidual(), InterTemperatureAdvection::computeQpResidual(), ArrayDGDiffusion::computeQpResidual(), ArrayHFEMDiffusion::computeQpResidual(), FEProblemBase::computeUserObjectByName(), FEProblemBase::computeUserObjects(), FEProblemBase::computeUserObjectsInternal(), BatchMaterial< Tuple, Output, Input >::construct(), DisplacedProblem::createQRules(), FEProblemBase::createQRules(), MeshGenerator::declareMeshProperty(), DumpObjectsProblem::deduceNecessaryParameters(), DumpObjectsProblem::dumpObjectHelper(), FEProblemBase::duplicateVariableCheck(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), MooseBaseErrorInterface::errorPrefix(), AB2PredictorCorrector::estimateTimeError(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finishMultiAppStep(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), ElementSubdomainIDGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), PatternedMeshGenerator::generate(), MeshGenerator::generateInternal(), MultiAppTransfer::getAppInfo(), TransfiniteMeshGenerator::getEdge(), ElementGenerator::getElemType(), FEProblemBase::getMaterial(), FEProblemBase::getMaterialData(), MaterialOutputAction::getParams(), ReporterData::getReporterInfo(), Transient::getTimeIntegratorName(), FEProblemBase::getTransfers(), SubProblem::getVectorTags(), DisplacedProblem::getVectorTags(), CommonOutputAction::hasConsole(), FEProblemBase::hasMultiApps(), AdvancedOutput::hasOutput(), FEProblemBase::incrementMultiAppTStep(), AdvancedOutput::initAvailableLists(), FunctorPositions::initialize(), FunctorTimes::initialize(), MultiAppConservativeTransfer::initialSetup(), ArrayDGDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), RelationshipManager::isType(), FEProblemBase::logAdd(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), SubProblem::numVectorTags(), DisplacedProblem::numVectorTags(), MooseBaseParameterInterface::objectErrorPrefix(), AdvancedOutput::output(), Console::output(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), ProjectedStatefulMaterialStorageAction::processProperty(), SolutionInvalidInterface::registerInvalidSolutionInternal(), FEProblemBase::restoreMultiApps(), MeshRepairGenerator::separateSubdomainsByElementType(), FEProblemBase::setCoupling(), MooseBase::typeAndName(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), DisplacedProblem::updateGeomSearch(), FEProblemBase::updateGeomSearch(), UserObjectInterface::userObjectType(), and AdvancedOutput::wantOutput().
typeAndName()
std::string MooseBase::typeAndName () const inline inherited
Get the class's combined type and name; useful in error handling.
Returns
The type and name of this class in the form '<type()> "<name()>"'.
Definition at line 53 of file MooseBase.h.
  {
    return type() + std::string(" \"") + name() + std::string("\"");
  }
Referenced by ReporterContext< T >::finalize(), and ReporterData::getReporterInfo().
uniformRefineLevel()
unsigned int MooseMesh::uniformRefineLevel () const inherited
Returns the level of uniform refinement requested (zero if AMR is disabled).
Definition at line 2956 of file MooseMesh.C.
{
  return _uniform_refine_level;
}
Referenced by DumpObjectsProblem::addAuxVariable(), Adaptivity::uniformRefine(), and Adaptivity::uniformRefineWithProjection().
uniqueName()
MooseObjectName MooseBaseParameterInterface::uniqueName () const inline inherited
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
Definition at line 58 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectName(_pars.get<std::string>("_unique_name"));
  }
Referenced by MooseBaseParameterInterface::connectControllableParams(), and Action::uniqueActionName().
uniqueParameterName()
MooseObjectParameterName MooseBaseParameterInterface::uniqueParameterName (const std::string & parameter_name) const inline inherited
The unique parameter name of a valid parameter of this object for accessing parameter controls.
Definition at line 43 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectParameterName(
        _pars.get<std::string>("_moose_base"), _moose_base->name(), parameter_name);
  }
update()
void MooseMesh::update () inherited
Calls buildNodeListFromSideList(), buildNodeList(), and buildBndElemList().
Definition at line 480 of file MooseMesh.C.
{
  TIME_SECTION("update", 3, "Updating Mesh", true);
  // Rebuild the boundary conditions
  buildNodeListFromSideList();
  // Update the node to elem map
  _node_to_elem_map.clear();
  _node_to_elem_map_built = false;
  _node_to_active_semilocal_elem_map.clear();
  _node_to_active_semilocal_elem_map_built = false;
  buildNodeList();
  buildBndElemList();
  cacheInfo();
  buildElemIDInfo();
  _finite_volume_info_dirty = true;
}
Referenced by MooseMesh::meshChanged(), MooseMesh::prepare(), ElementSubdomainModifier::synchronizeBoundaryInfo(), ActivateElementsUserObjectBase::updateBoundaryInfo(), and EqualValueBoundaryConstraint::updateConstrainedNodes().
updateActiveSemiLocalNodeRange()
void MooseMesh::updateActiveSemiLocalNodeRange (std::set< dof_id_type > & ghosted_elems) inherited
Clears the "semi-local" node list and rebuilds it.
Semi-local nodes consist of all nodes that belong to local and ghost elements.
Definition at line 748 of file MooseMesh.C.
{
  TIME_SECTION("updateActiveSemiLocalNodeRange", 5, "Updating ActiveSemiLocalNode Range");
  _semilocal_node_list.clear();
  // First add the nodes connected to local elems
  ConstElemRange * active_local_elems = getActiveLocalElementRange();
  for (const auto & elem : *active_local_elems)
  {
    for (unsigned int n = 0; n < elem->n_nodes(); ++n)
    {
      // Since elem is const here but we require a non-const Node * to
      // store in the _semilocal_node_list (otherwise things like
      // UpdateDisplacedMeshThread don't work), we are using a
      // const_cast. A more long-term fix would be to have
      // getActiveLocalElementRange return a non-const ElemRange.
      Node * node = const_cast<Node *>(elem->node_ptr(n));
      _semilocal_node_list.insert(node);
    }
  }
  // Now add the nodes connected to ghosted_elems
  for (const auto & ghost_elem_id : ghosted_elems)
  {
    Elem * elem = getMesh().elem_ptr(ghost_elem_id);
    for (unsigned int n = 0; n < elem->n_nodes(); n++)
    {
      Node * node = elem->node_ptr(n);
      _semilocal_node_list.insert(node);
    }
  }
  // Now create the actual range
  _active_semilocal_node_range = std::make_unique<SemiLocalNodeRange>(_semilocal_node_list.begin(),
                                                                      _semilocal_node_list.end());
}
Referenced by DumpObjectsProblem::addAuxVariable(), FEProblemBase::meshChangedHelper(), and FEProblemBase::possiblyRebuildGeomSearchPatches().
updateCoordTransform()
void MooseMesh::updateCoordTransform () private inherited
Update the coordinate transformation object based on our coordinate system data.
The coordinate transformation will be created if it hasn't been already
Definition at line 3983 of file MooseMesh.C.
{
  if (!_coord_transform)
    _coord_transform = std::make_unique<MooseAppCoordTransform>(*this);
  else
    _coord_transform->setCoordinateSystem(*this);
}
Referenced by MooseMesh::MooseMesh(), MooseMesh::setAxisymmetricCoordAxis(), MooseMesh::setCoordSystem(), and MooseMesh::setGeneralAxisymmetricCoordAxes().
usingGeneralAxisymmetricCoordAxes()
bool MooseMesh::usingGeneralAxisymmetricCoordAxes () const inherited
Returns true if general axisymmetric coordinate axes are being used.
Definition at line 3977 of file MooseMesh.C.
{
  return _subdomain_id_to_rz_coord_axis.size() > 0;
}
Referenced by coordTransformFactor(), MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::getUniqueCoordSystem(), and MooseAppCoordTransform::setCoordinateSystem().
validParams()
InputParameters SpiralAnnularMesh::validParams () static
Definition at line 18 of file SpiralAnnularMesh.C.
{
  InputParameters params = MooseMesh::validParams();
  params.addRequiredRangeCheckedParam<Real>(
      "inner_radius", "inner_radius>0.", "The size of the inner circle.");
  params.addRequiredRangeCheckedParam<Real>("outer_radius",
                                            "outer_radius>0.",
                                            "The size of the outer circle."
                                            " Logically, it has to be greater than inner_radius");
  params.addRequiredRangeCheckedParam<unsigned int>(
      "nodes_per_ring", "nodes_per_ring>5", "Number of nodes on each ring.");
  params.addParam<bool>(
      "use_tri6", false, "Generate mesh of TRI6 elements instead of TRI3 elements.");
  params.addRequiredRangeCheckedParam<unsigned int>(
      "num_rings", "num_rings>1", "The number of rings.");
  params.addParam<boundary_id_type>(
      "cylinder_bid", 1, "The boundary id to use for the cylinder (inner circle)");
  params.addParam<boundary_id_type>(
      "exterior_bid", 2, "The boundary id to use for the exterior (outer circle)");
  params.addParam<Real>("initial_delta_r",
                        "Width of the initial layer of elements around the cylinder."
                        "This number should be approximately"
                        " 2 * pi * inner_radius / nodes_per_ring to ensure that the"
                        " initial layer of elements is almost equilateral");
  params.addClassDescription("Creates an annual mesh based on TRI3 elements"
                             " (it can also be TRI6 elements) on several rings.");
  return params;
}
Member Data Documentation
_action_factory
ActionFactory& MooseBaseParameterInterface::_action_factory protected inherited
Builds Actions.
Definition at line 164 of file MooseBaseParameterInterface.h.
Referenced by CommonOutputAction::create(), AddVariableAction::createInitialConditionAction(), AddSpecies::createInitialConditions(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
_active_local_elem_range
std::unique_ptr<ConstElemRange> MooseMesh::_active_local_elem_range protected inherited
A range for use with threading.
We do this so that it doesn't have to get rebuilt all the time (which takes time).
Definition at line 1435 of file MooseMesh.h.
Referenced by MooseMesh::getActiveLocalElementRange(), and MooseMesh::meshChanged().
_active_node_range
std::unique_ptr<NodeRange> MooseMesh::_active_node_range protected inherited
Definition at line 1438 of file MooseMesh.h.
Referenced by MooseMesh::getActiveNodeRange(), and MooseMesh::meshChanged().
_active_semilocal_node_range
std::unique_ptr<SemiLocalNodeRange> MooseMesh::_active_semilocal_node_range protected inherited
Definition at line 1437 of file MooseMesh.h.
Referenced by MooseMesh::getActiveSemiLocalNodeRange(), MooseMesh::meshChanged(), and MooseMesh::updateActiveSemiLocalNodeRange().
_all_face_info
std::vector<FaceInfo> MooseMesh::_all_face_info mutable private inherited
FaceInfo object storing information for face based loops.
This container holds all the FaceInfo objects accessible from this process
Definition at line 1544 of file MooseMesh.h.
Referenced by MooseMesh::allFaceInfo(), MooseMesh::buildFiniteVolumeInfo(), MooseMesh::cacheFaceInfoVariableOwnership(), and MooseMesh::computeFiniteVolumeCoords().
_allow_recovery
bool MooseMesh::_allow_recovery private inherited
Whether or not this Mesh is allowed to read a recovery file.
Definition at line 1735 of file MooseMesh.h.
Referenced by MooseMesh::allowRecovery(), and MooseMesh::init().
_allow_remote_element_removal
bool MooseMesh::_allow_remote_element_removal private inherited
Whether to allow removal of remote elements.
Definition at line 1744 of file MooseMesh.h.
Referenced by MooseMesh::allowRemoteElementRemoval(), MooseMesh::buildTypedMesh(), MooseMesh::deleteRemoteElements(), and MooseMesh::setMeshBase().
_app
MooseApp& MooseBase::_app protected inherited
The MOOSE application this is associated with.
Definition at line 60 of file MooseBase.h.
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), MeshGenerator::addChildMeshGenerator(), FEProblemBase::addMaterialHelper(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addOutput(), MeshGenerator::addParentMeshGenerator(), FVFluxKernel::adjustRMGhostLayers(), FEProblemBase::allowOutput(), AStableDirk4::AStableDirk4(), FileMesh::buildMesh(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), MeshGenerator::checkGetMesh(), FEProblemBase::checkICRestartError(), FEProblemBase::checkNonlinearConvergence(), OversampleOutput::cloneMesh(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), Console::Console(), TimeStepper::constrainStep(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::createLocalApp(), FEProblemBase::customSetup(), MeshGenerator::declareMeshProperty(), MeshGenerator::declareNullMeshName(), MooseMesh::determineUseDistributedMesh(), DumpObjectsProblem::dumpObjectHelper(), DumpObjectsProblem::dumpVariableHelper(), EigenExecutionerBase::EigenExecutionerBase(), EigenKernel::EigenKernel(), PIDTransientControl::execute(), Eigenvalue::execute(), InversePowerMethod::execute(), NonlinearEigen::execute(), Steady::execute(), Transient::execute(), PseudoTimestep::execute(), IterationInfo::execute(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FileOutput::FileOutput(), ChangeOverFixedPointPostprocessor::finalize(), RadialAverage::finalize(), FixedPointSolve::FixedPointSolve(), FEProblemBase::forceOutput(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), SideSetsFromNormalsGenerator::generate(), MeshGenerator::generateInternal(), FEProblemBase::getExecutor(), MeshGenerator::getMeshByName(), NumFixedPointIterations::getValue(), NumRelationshipManagers::getValue(), GhostingUserObject::GhostingUserObject(), MooseMesh::init(), InversePowerMethod::init(), NonlinearEigen::init(), Transient::init(), FEProblemBase::init(), TimePeriod::initialSetup(), Console::initialSetup(), AdvancedOutput::initOutputList(), FEProblemBase::initPetscOutput(), EigenProblem::initPetscOutput(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MeshGenerator::MeshGenerator(), EigenExecutionerBase::normalizeSolution(), NumFailedTimeSteps::NumFailedTimeSteps(), AugmentSparsityOnInterface::operator()(), Checkpoint::output(), Exodus::output(), Nemesis::output(), PerfGraphOutput::output(), Tecplot::output(), MortarNodalGeometryOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Exodus::outputEmptyTimestep(), Console::outputInput(), Exodus::outputInput(), Exodus::outputNodalVariables(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), Console::outputSystemInformation(), JSONOutput::outputSystemInformation(), MultiApp::parentOutputPositionChanged(), PIDTransientControl::PIDTransientControl(), Transient::preExecute(), Eigenvalue::prepareSolverOptions(), FEProblemBase::projectSolution(), MultiApp::setAppOutputFileBase(), FileOutput::setFileBaseInternal(), MeshGenerator::setMeshProperty(), MeshGenerator::setMeshPropertyHelper(), FEProblemBase::setRestartFile(), TransientMultiApp::setupApp(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SolutionInvalidityReporter::SolutionInvalidityReporter(), FEProblemBase::solve(), EigenProblem::solve(), PetscOutput::solveSetup(), TransientMultiApp::solveStep(), FEProblemBase::subdomainSetup(), FEProblemBase::theWarehouse(), TimeExtremeValue::TimeExtremeValue(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), Transient::Transient(), FEProblemBase::updateMortarMesh(), Console::write(), and FEProblemBase::~FEProblemBase().
_block_id_mapping
std::vector<std::unordered_map<SubdomainID, std::set<dof_id_type> > > MooseMesh::_block_id_mapping private inherited
Unique element integer IDs for each subdomain and each extra element integers.
Definition at line 1756 of file MooseMesh.h.
Referenced by MooseMesh::buildElemIDInfo(), MooseMesh::getAllElemIDs(), and MooseMesh::getElemIDsOnBlocks().
_block_node_list
std::map<dof_id_type, std::set<SubdomainID> > MooseMesh::_block_node_list protected inherited
list of nodes that belongs to a specified block (domain)
Definition at line 1493 of file MooseMesh.h.
Referenced by MooseMesh::cacheInfo(), and MooseMesh::getNodeBlockIds().
_bnd_elem_ids
std::unordered_map<boundary_id_type, std::unordered_set<dof_id_type> > MooseMesh::_bnd_elem_ids protected inherited
Map of set of elem IDs connected to each boundary.
Definition at line 1485 of file MooseMesh.h.
Referenced by MooseMesh::buildBndElemList(), MooseMesh::freeBndElems(), MooseMesh::getBoundariesToActiveSemiLocalElemIds(), MooseMesh::getBoundaryActiveSemiLocalElemIds(), and MooseMesh::isBoundaryElem().
_bnd_elem_range
std::unique_ptr<StoredRange<MooseMesh::const_bnd_elem_iterator, const BndElement *> > MooseMesh::_bnd_elem_range protected inherited
Definition at line 1442 of file MooseMesh.h.
Referenced by MooseMesh::getBoundaryElementRange(), MooseMesh::isBoundaryFullyExternalToSubdomains(), and MooseMesh::meshChanged().
_bnd_elems
std::vector<BndElement *> MooseMesh::_bnd_elems protected inherited
array of boundary elems
Definition at line 1480 of file MooseMesh.h.
Referenced by MooseMesh::bndElemsBegin(), MooseMesh::bndElemsEnd(), MooseMesh::buildBndElemList(), MooseMesh::freeBndElems(), and MooseMesh::getBoundaryActiveNeighborElemIds().
_bnd_node_ids
std::map<boundary_id_type, std::set<dof_id_type> > MooseMesh::_bnd_node_ids protected inherited
Map of sets of node IDs in each boundary.
Definition at line 1477 of file MooseMesh.h.
Referenced by MooseMesh::addQuadratureNode(), MooseMesh::buildNodeList(), MooseMesh::freeBndNodes(), and MooseMesh::isBoundaryNode().
_bnd_node_range
std::unique_ptr<StoredRange<MooseMesh::const_bnd_node_iterator, const BndNode *> > MooseMesh::_bnd_node_range protected inherited
Definition at line 1440 of file MooseMesh.h.
Referenced by MooseMesh::addQuadratureNode(), MooseMesh::getBoundaryNodeRange(), and MooseMesh::meshChanged().
_bnd_nodes
std::vector<BndNode *> MooseMesh::_bnd_nodes protected inherited
array of boundary nodes
Definition at line 1473 of file MooseMesh.h.
Referenced by MooseMesh::addQuadratureNode(), MooseMesh::bndNodesBegin(), MooseMesh::bndNodesEnd(), MooseMesh::buildNodeList(), and MooseMesh::freeBndNodes().
_boundary_to_normal_map
std::unique_ptr<std::map<BoundaryID, RealVectorValue> > MooseMesh::_boundary_to_normal_map protected inherited
The boundary to normal map - valid only when AddAllSideSetsByNormals is active.
Definition at line 1470 of file MooseMesh.h.
Referenced by MooseMesh::getNormalByBoundaryID(), and MooseMesh::setBoundaryToNormalMap().
_bounds
std::vector<std::vector<Real> > MooseMesh::_bounds protected inherited
The bounds in each dimension of the mesh for regular orthogonal meshes.
Definition at line 1520 of file MooseMesh.h.
Referenced by MooseMesh::detectOrthogonalDimRanges(), MooseMesh::getMaxInDimension(), MooseMesh::getMinInDimension(), and MooseMesh::MooseMesh().
_built_from_other_mesh
bool MooseMesh::_built_from_other_mesh = false protected inherited
Whether or not this mesh was built from another mesh.
Definition at line 1360 of file MooseMesh.h.
Referenced by MooseMesh::prepare().
_coarsened_element_children
std::map<const Elem *, std::vector<const Elem *> > MooseMesh::_coarsened_element_children protected inherited
Map of Parent elements to child elements for elements that were just coarsened.
NOTE: the child element pointers ARE PROBABLY INVALID. Only use them for indexing!
Definition at line 1426 of file MooseMesh.h.
Referenced by MooseMesh::cacheChangedLists(), and MooseMesh::coarsenedElementChildren().
_coarsened_elements
std::unique_ptr<ConstElemPointerRange> MooseMesh::_coarsened_elements protected inherited
The elements that were just coarsened.
Definition at line 1419 of file MooseMesh.h.
Referenced by MooseMesh::cacheChangedLists(), and MooseMesh::coarsenedElementRange().
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_construct_node_list_from_side_list
bool MooseMesh::_construct_node_list_from_side_list private inherited
Whether or not to allow generation of nodesets from sidesets.
Definition at line 1738 of file MooseMesh.h.
Referenced by MooseMesh::buildNodeListFromSideList().
_coord_sys
std::map<SubdomainID, Moose::CoordinateSystemType> MooseMesh::_coord_sys private inherited
Type of coordinate system per subdomain.
Definition at line 1774 of file MooseMesh.h.
Referenced by MooseMesh::checkCoordinateSystems(), MooseMesh::getCoordSystem(), MooseMesh::getUniqueCoordSystem(), MooseMesh::setCoordData(), MooseMesh::setCoordSystem(), and MooseMesh::setGeneralAxisymmetricCoordAxes().
_coord_system_set
bool MooseMesh::_coord_system_set private inherited
Whether the coordinate system has been set.
Definition at line 1787 of file MooseMesh.h.
Referenced by MooseMesh::prepare(), and MooseMesh::setCoordSystem().
_coord_transform
std::unique_ptr<MooseAppCoordTransform> MooseMesh::_coord_transform private inherited
A coordinate transformation object that describes how to transform this problem's coordinate system into the canonical/reference coordinate system.
Definition at line 1784 of file MooseMesh.h.
Referenced by MooseMesh::coordTransform(), MooseMesh::lengthUnit(), and MooseMesh::updateCoordTransform().
_custom_partitioner
std::unique_ptr<Partitioner> MooseMesh::_custom_partitioner protected inherited
The custom partitioner.
Definition at line 1381 of file MooseMesh.h.
Referenced by MooseMesh::buildTypedMesh(), and MooseMesh::setCustomPartitioner().
_custom_partitioner_requested
bool MooseMesh::_custom_partitioner_requested protected inherited
Definition at line 1382 of file MooseMesh.h.
Referenced by MooseMesh::buildTypedMesh(), MooseMesh::isCustomPartitionerRequested(), and MooseMesh::setIsCustomPartitionerRequested().
_cylinder_bid
const boundary_id_type SpiralAnnularMesh::_cylinder_bid protected
The boundary id to use for the cylinder.
Definition at line 56 of file SpiralAnnularMesh.h.
Referenced by buildMesh().
_distribution_overridden
bool MooseMesh::_distribution_overridden protected inherited
Definition at line 1370 of file MooseMesh.h.
_doing_p_refinement
bool MooseMesh::_doing_p_refinement private inherited
Whether we have p-refinement (as opposed to h-refinement)
Definition at line 1793 of file MooseMesh.h.
Referenced by MooseMesh::doingPRefinement().
_elem_info
std::vector<const ElemInfo *> MooseMesh::_elem_info mutable private inherited
Holds only those ElemInfo objects that have processor_id equal to this process's id, e.g.
the local ElemInfo objects
Definition at line 1540 of file MooseMesh.h.
Referenced by MooseMesh::buildFiniteVolumeInfo(), MooseMesh::elemInfoVector(), MooseMesh::ownedElemInfoBegin(), and MooseMesh::ownedElemInfoEnd().
_elem_side_to_face_info
std::unordered_map<std::pair<const Elem *, unsigned int>, FaceInfo *> MooseMesh::_elem_side_to_face_info mutable private inherited
Map from elem-side pair to FaceInfo.
Definition at line 1552 of file MooseMesh.h.
Referenced by MooseMesh::buildFiniteVolumeInfo(), and MooseMesh::faceInfo().
_elem_to_elem_info
std::unordered_map<dof_id_type, ElemInfo> MooseMesh::_elem_to_elem_info mutable private inherited
Map connecting elems with their corresponding ElemInfo, we use the element ID as the key.
Definition at line 1536 of file MooseMesh.h.
Referenced by MooseMesh::buildFiniteVolumeInfo(), MooseMesh::cacheFVElementalDoFs(), MooseMesh::computeFiniteVolumeCoords(), and MooseMesh::elemInfo().
_elem_to_side_to_qp_to_quadrature_nodes
std::map<dof_id_type, std::map<unsigned int, std::map<dof_id_type, Node *> > > MooseMesh::_elem_to_side_to_qp_to_quadrature_nodes protected inherited
Definition at line 1489 of file MooseMesh.h.
Referenced by MooseMesh::addQuadratureNode(), MooseMesh::clearQuadratureNodes(), and MooseMesh::getQuadratureNode().
_elem_type_to_child_side_refinement_map
std::map<ElemType, std::map<std::pair<int, int>, std::vector<std::vector<QpMap> > > > MooseMesh::_elem_type_to_child_side_refinement_map private inherited
Holds mappings for "internal" child sides to parent volume. The second key is (child, child_side).
Definition at line 1697 of file MooseMesh.h.
Referenced by MooseMesh::buildRefinementMap(), and MooseMesh::getRefinementMap().
_elem_type_to_coarsening_map
std::map<std::pair<int, ElemType>, std::vector<std::pair<unsigned int, QpMap> > > MooseMesh::_elem_type_to_coarsening_map private inherited
Holds mappings for volume to volume and parent side to child side Map key:
first member corresponds to element side. It's -1 for volume quadrature points
second member correponds to the element type Map value:
Vector is sized based on the number of quadrature points in the parent (e.g. coarser) element.
For each parent quadrature point we store a pair
The first member of the pair identifies which child holds the closest refined-level quadrature point
The second member of the pair is the QpMap. The _from data member will correspond to the parent quadrature point index. The _to data member will correspond to which child element quadrature point is closest to the parent quadrature point. And _distance is the distance between the two
Definition at line 1714 of file MooseMesh.h.
Referenced by MooseMesh::buildCoarseningMap(), and MooseMesh::getCoarseningMap().
_elem_type_to_p_coarsening_map
std::map<std::pair<ElemType, unsigned int>, std::vector<QpMap> > MooseMesh::_elem_type_to_p_coarsening_map private inherited
Definition at line 1716 of file MooseMesh.h.
Referenced by MooseMesh::buildPRefinementAndCoarseningMaps(), and MooseMesh::getPCoarseningMap().
_elem_type_to_p_coarsening_side_map
std::map<std::pair<ElemType, unsigned int>, std::vector<QpMap> > MooseMesh::_elem_type_to_p_coarsening_side_map private inherited
Definition at line 1718 of file MooseMesh.h.
Referenced by MooseMesh::buildPRefinementAndCoarseningMaps(), and MooseMesh::getPCoarseningSideMap().
_elem_type_to_p_refinement_map
std::map<std::pair<ElemType, unsigned int>, std::vector<QpMap> > MooseMesh::_elem_type_to_p_refinement_map private inherited
Definition at line 1691 of file MooseMesh.h.
Referenced by MooseMesh::buildPRefinementAndCoarseningMaps(), and MooseMesh::getPRefinementMap().
_elem_type_to_p_refinement_side_map
std::map<std::pair<ElemType, unsigned int>, std::vector<QpMap> > MooseMesh::_elem_type_to_p_refinement_side_map private inherited
Definition at line 1693 of file MooseMesh.h.
Referenced by MooseMesh::buildPRefinementAndCoarseningMaps(), and MooseMesh::getPRefinementSideMap().
_elem_type_to_refinement_map
std::map<std::pair<int, ElemType>, std::vector<std::vector<QpMap> > > MooseMesh::_elem_type_to_refinement_map private inherited
Holds mappings for volume to volume and parent side to child side Map key:
first member corresponds to element side. It's -1 for volume quadrature points
second member correponds to the element type Map value:
Outermost index is the child element index
Once we have indexed by the child element index, we have a std::vector of QpMaps. This vector is sized by the number of reference points in the child element. Then for each reference point in the child element we have a QpMap whose _from index corresponds to the child element reference point, a _to index which corresponds to the reference point on the parent element that the child element reference point is closest to, and a _distance member which is the distance between the mapped child and parent reference quadrature points
Definition at line 1689 of file MooseMesh.h.
Referenced by MooseMesh::buildRefinementMap(), and MooseMesh::getRefinementMap().
_enabled
const bool& MooseObject::_enabled protected inherited
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
Definition at line 58 of file MooseObject.h.
Referenced by MooseObject::enabled().
_exterior_bid
const boundary_id_type SpiralAnnularMesh::_exterior_bid protected
Definition at line 56 of file SpiralAnnularMesh.h.
Referenced by buildMesh().
_extra_bnd_nodes
std::vector<BndNode> MooseMesh::_extra_bnd_nodes protected inherited
Definition at line 1490 of file MooseMesh.h.
Referenced by MooseMesh::addQuadratureNode(), MooseMesh::buildNodeList(), and MooseMesh::clearQuadratureNodes().
_extreme_nodes
std::vector<Node *> MooseMesh::_extreme_nodes private inherited
A vector containing the nodes at the corners of a regular orthogonal mesh.
Definition at line 1574 of file MooseMesh.h.
Referenced by MooseMesh::detectOrthogonalDimRanges().
_face_info
std::vector<const FaceInfo *> MooseMesh::_face_info mutable private inherited
Holds only those FaceInfo objects that have processor_id equal to this process's id, e.g.
the local FaceInfo objects
Definition at line 1548 of file MooseMesh.h.
Referenced by MooseMesh::buildFiniteVolumeInfo(), MooseMesh::faceInfo(), MooseMesh::nFace(), MooseMesh::ownedFaceInfoBegin(), and MooseMesh::ownedFaceInfoEnd().
_factory
Factory& MooseBaseParameterInterface::_factory protected inherited
The Factory associated with the MooseApp.
Definition at line 161 of file MooseBaseParameterInterface.h.
Referenced by AddGeneralReactions::act(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), ElementIDOutputAction::act(), AddSpecies::act(), AdaptivityAction::act(), AddControlAction::act(), AddNodalNormalsAction::act(), AddPeriodicBCAction::act(), AutoCheckpointAction::act(), ComposeTimeStepperAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DisplayGhostingAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), PartitionerAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SetupPreconditionerAction::act(), SetupPredictorAction::act(), SetupResidualDebugAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddGeneralReactions::addEEDFReactionKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddDriftDiffusionAction::addPosition(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), MooseBaseParameterInterface::connectControllableParams(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), MaterialOutputAction::getParams(), and ProjectedStatefulMaterialStorageAction::processProperty().
_finite_volume_info_dirty
bool MooseMesh::_finite_volume_info_dirty = true mutable private inherited
Definition at line 1555 of file MooseMesh.h.
Referenced by MooseMesh::buildFiniteVolumeInfo(), MooseMesh::computeFiniteVolumeCoords(), MooseMesh::isFiniteVolumeInfoDirty(), MooseMesh::markFiniteVolumeInfoDirty(), and MooseMesh::update().
_ghost_elems_from_ghost_boundaries
std::set<Elem *> MooseMesh::_ghost_elems_from_ghost_boundaries private inherited
Set of elements ghosted by ghostGhostedBoundaries.
Definition at line 1747 of file MooseMesh.h.
Referenced by MooseMesh::ghostGhostedBoundaries().
_ghosted_boundaries
std::set<unsigned int> MooseMesh::_ghosted_boundaries protected inherited
Definition at line 1498 of file MooseMesh.h.
Referenced by MooseMesh::addGhostedBoundary(), MooseMesh::getGhostedBoundaries(), and MooseMesh::ghostGhostedBoundaries().
_ghosted_boundaries_inflation
std::vector<Real> MooseMesh::_ghosted_boundaries_inflation protected inherited
Definition at line 1499 of file MooseMesh.h.
Referenced by MooseMesh::getGhostedBoundaryInflation(), and MooseMesh::setGhostedBoundaryInflation().
_ghosting_functors
std::vector<std::unique_ptr<GhostingFunctor> > MooseMesh::_ghosting_functors protected inherited
Deprecated (DO NOT USE)
Definition at line 1354 of file MooseMesh.h.
_ghosting_patch_size
unsigned int MooseMesh::_ghosting_patch_size protected inherited
The number of nearest neighbors to consider for ghosting purposes when iteration patch update strategy is used.
Definition at line 1505 of file MooseMesh.h.
Referenced by MooseMesh::getGhostingPatchSize().
_half_range
RealVectorValue MooseMesh::_half_range private inherited
A convenience vector used to hold values in each dimension representing half of the range.
Definition at line 1571 of file MooseMesh.h.
Referenced by MooseMesh::addPeriodicVariable(), and MooseMesh::minPeriodicVector().
_higher_d_elem_side_to_lower_d_elem
std::unordered_map<std::pair<const Elem *, unsigned short int>, const Elem *> MooseMesh::_higher_d_elem_side_to_lower_d_elem private inherited
Holds a map from a high-order element side to its corresponding lower-d element.
Definition at line 1731 of file MooseMesh.h.
Referenced by MooseMesh::buildLowerDMesh(), MooseMesh::cacheInfo(), MooseMesh::getLowerDElem(), and MooseMesh::getLowerDElemMap().
_id_identical_flag
std::vector<std::vector<bool> > MooseMesh::_id_identical_flag private inherited
Flags to indicate whether or not any two extra element integers are the same.
Definition at line 1762 of file MooseMesh.h.
Referenced by MooseMesh::areElemIDsIdentical(), and MooseMesh::buildElemIDInfo().
_initial_delta_r
const Real SpiralAnnularMesh::_initial_delta_r protected
Definition at line 62 of file SpiralAnnularMesh.h.
Referenced by buildMesh().
_inner_radius
const Real SpiralAnnularMesh::_inner_radius protected
Radius of the inner circle.
Definition at line 34 of file SpiralAnnularMesh.h.
Referenced by buildMesh(), and SpiralAnnularMesh().
_is_changed
bool MooseMesh::_is_changed protected inherited
true if mesh is changed (i.e. after adaptivity step)
Definition at line 1407 of file MooseMesh.h.
_is_displaced
bool MooseMesh::_is_displaced private inherited
Whether this mesh is displaced.
Definition at line 1765 of file MooseMesh.h.
Referenced by MooseMesh::isDisplaced().
_is_nemesis
bool MooseMesh::_is_nemesis protected inherited
True if a Nemesis Mesh was read in.
Definition at line 1410 of file MooseMesh.h.
Referenced by FileMesh::buildMesh(), MooseMesh::determineUseDistributedMesh(), MooseMesh::prepare(), and FileMesh::read().
_is_split
const bool MooseMesh::_is_split protected inherited
Whether or not we are using a (pre-)split mesh (automatically DistributedMesh)
Definition at line 1526 of file MooseMesh.h.
Referenced by MooseMesh::determineUseDistributedMesh(), and MooseMesh::isSplit().
_linear_finite_volume_dofs_cached
bool MooseMesh::_linear_finite_volume_dofs_cached = false mutable private inherited
Definition at line 1560 of file MooseMesh.h.
Referenced by MooseMesh::buildFiniteVolumeInfo().
_local_node_range
std::unique_ptr<ConstNodeRange> MooseMesh::_local_node_range protected inherited
Definition at line 1439 of file MooseMesh.h.
Referenced by MooseMesh::getLocalNodeRange(), and MooseMesh::meshChanged().
_lower_d_elem_to_higher_d_elem_side
std::unordered_map<const Elem *, unsigned short int> MooseMesh::_lower_d_elem_to_higher_d_elem_side private inherited
Definition at line 1732 of file MooseMesh.h.
Referenced by MooseMesh::buildLowerDMesh(), and MooseMesh::getHigherDSide().
_max_ids
std::vector<dof_id_type> MooseMesh::_max_ids private inherited
Maximum integer ID for each extra element integer.
Definition at line 1758 of file MooseMesh.h.
Referenced by MooseMesh::buildElemIDInfo(), and MooseMesh::maxElementID().
_max_leaf_size
unsigned int MooseMesh::_max_leaf_size protected inherited
Definition at line 1508 of file MooseMesh.h.
Referenced by MooseMesh::getMaxLeafSize().
_mesh
std::unique_ptr<libMesh::MeshBase> MooseMesh::_mesh protected inherited
Pointer to underlying libMesh mesh object.
Definition at line 1374 of file MooseMesh.h.
Referenced by MooseMesh::allowRemoteElementRemoval(), MooseMesh::buildFiniteVolumeInfo(), MooseMesh::buildPeriodicNodeMap(), MooseMesh::deleteRemoteElements(), MooseMesh::detectPairedSidesets(), MooseMesh::getMaxInDimension(), MooseMesh::getMesh(), MooseMesh::getMeshPtr(), MooseMesh::getMinInDimension(), MooseMesh::hasMeshBase(), MooseMesh::init(), MooseMesh::prepare(), MooseMesh::prepared(), and MooseMesh::setMeshBase().
_mesh_boundary_ids
std::set<BoundaryID> MooseMesh::_mesh_boundary_ids protected inherited
A set of boundary IDs currently present in the mesh.
In serial, this is equivalent to the values returned by _mesh.get_boundary_info().get_boundary_ids(). In parallel, it will contain off-processor boundary IDs as well.
Definition at line 1464 of file MooseMesh.h.
Referenced by MooseMesh::getBoundaryIDs(), MooseMesh::meshBoundaryIds(), MooseMesh::prepare(), and MooseMesh::setMeshBoundaryIDs().
_mesh_nodeset_ids
std::set<BoundaryID> MooseMesh::_mesh_nodeset_ids protected inherited
Definition at line 1466 of file MooseMesh.h.
Referenced by MooseMesh::meshNodesetIds(), and MooseMesh::prepare().
_mesh_sideset_ids
std::set<BoundaryID> MooseMesh::_mesh_sideset_ids protected inherited
Definition at line 1465 of file MooseMesh.h.
Referenced by MooseMesh::meshSidesetIds(), and MooseMesh::prepare().
_mesh_subdomains
std::set<SubdomainID> MooseMesh::_mesh_subdomains protected inherited
A set of subdomain IDs currently present in the mesh.
For parallel meshes, includes subdomains defined on other processors as well.
Definition at line 1456 of file MooseMesh.h.
Referenced by MooseMesh::buildLowerDMesh(), MooseMesh::cacheInfo(), MooseMesh::checkDuplicateSubdomainNames(), MooseMesh::meshSubdomains(), and MooseMesh::prepare().
_metaname
const RestartableDataMapName Restartable::_metaname private inherited
Restartable metadata name.
Definition at line 240 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_min_ids
std::vector<dof_id_type> MooseMesh::_min_ids private inherited
Minimum integer ID for each extra element integer.
Definition at line 1760 of file MooseMesh.h.
Referenced by MooseMesh::buildElemIDInfo(), and MooseMesh::minElementID().
_moose_base
const MooseBase* const MooseBaseParameterInterface::_moose_base private inherited
The MooseBase object that inherits this class.
Definition at line 168 of file MooseBaseParameterInterface.h.
Referenced by MooseBaseParameterInterface::connectControllableParams(), MooseBaseParameterInterface::objectErrorPrefix(), MooseBaseParameterInterface::paramError(), and MooseBaseParameterInterface::uniqueParameterName().
_moose_mesh_prepared
bool MooseMesh::_moose_mesh_prepared = false protected inherited
True if prepare has been called on the mesh.
Definition at line 1413 of file MooseMesh.h.
Referenced by MooseMesh::prepare(), and MooseMesh::prepared().
_name
const std::string& MooseBase::_name protected inherited
The name of this class, reference to value stored in InputParameters.
Definition at line 66 of file MooseBase.h.
Referenced by AddFieldSplitAction::act(), AddBCAction::act(), AddConstraintAction::act(), AddControlAction::act(), AddDamperAction::act(), AddDGKernelAction::act(), AddDiracKernelAction::act(), AddDistributionAction::act(), AddFunctionAction::act(), AddFunctorMaterialAction::act(), AddFVBCAction::act(), AddFVInitialConditionAction::act(), AddFVInterfaceKernelAction::act(), AddFVKernelAction::act(), AddIndicatorAction::act(), AddInitialConditionAction::act(), AddInterfaceKernelAction::act(), AddKernelAction::act(), AddMarkerAction::act(), AddMaterialAction::act(), AddMeshDivisionAction::act(), AddMeshGeneratorAction::act(), AddMultiAppAction::act(), AddNodalKernelAction::act(), AddOutputAction::act(), AddPeriodicBCAction::act(), AddPositionsAction::act(), AddPostprocessorAction::act(), AddReporterAction::act(), AddSamplerAction::act(), AddScalarKernelAction::act(), AddTimesAction::act(), AddTimeStepperAction::act(), AddTransferAction::act(), AddUserObjectAction::act(), AddVectorPostprocessorAction::act(), PartitionerAction::act(), ReadExecutorParamsAction::act(), SetupPreconditionerAction::act(), SetupTimeIntegratorAction::act(), AddDriftDiffusionAction::addADKernels(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromXY(), PiecewiseLinearBase::buildInterpolation(), CombinerGenerator::CombinerGenerator(), Executor::Executor(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), FunctionDT::FunctionDT(), FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), MooseBase::name(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), PiecewiseBase::setData(), and Split::setup().
_need_delete
bool MooseMesh::_need_delete private inherited
Whether we need to delete remote elements after init'ing the EquationSystems.
Definition at line 1741 of file MooseMesh.h.
Referenced by MooseMesh::allowRemoteElementRemoval(), and MooseMesh::needsRemoteElemDeletion().
_need_ghost_ghosted_boundaries
bool MooseMesh::_need_ghost_ghosted_boundaries private inherited
A parallel mesh generator such as DistributedRectilinearMeshGenerator already make everything ready.
We do not need to gather all boundaries to every single processor. In general, we should avoid using ghostGhostedBoundaries when posssible since it is not scalable
Definition at line 1753 of file MooseMesh.h.
Referenced by MooseMesh::ghostGhostedBoundaries(), and MooseMesh::needGhostGhostedBoundaries().
_neighbor_subdomain_boundary_ids
std::unordered_map<SubdomainID, std::set<BoundaryID> > MooseMesh::_neighbor_subdomain_boundary_ids private inherited
Holds a map from neighbor subomdain ids to the boundary ids that are attached to it.
Definition at line 1727 of file MooseMesh.h.
Referenced by MooseMesh::cacheInfo(), MooseMesh::getBoundaryConnectedSecondaryBlocks(), MooseMesh::getInterfaceConnectedBlocks(), and MooseMesh::getSubdomainInterfaceBoundaryIds().
_node_map
std::vector<Node *> MooseMesh::_node_map protected inherited
Vector of all the Nodes in the mesh for determining when to add a new point.
Definition at line 1514 of file MooseMesh.h.
Referenced by MooseMesh::addUniqueNode().
_node_set_nodes
std::map<boundary_id_type, std::vector<dof_id_type> > MooseMesh::_node_set_nodes protected inherited
list of nodes that belongs to a specified nodeset: indexing [nodeset_id] -> [array of node ids]
Definition at line 1496 of file MooseMesh.h.
Referenced by MooseMesh::buildNodeList(), MooseMesh::freeBndNodes(), MooseMesh::getNodeList(), and MooseMesh::nodeSetNodes().
_node_to_active_semilocal_elem_map
std::map<dof_id_type, std::vector<dof_id_type> > MooseMesh::_node_to_active_semilocal_elem_map protected inherited
A map of all of the current nodes to the active elements that they are connected to.
Definition at line 1449 of file MooseMesh.h.
Referenced by MooseMesh::addQuadratureNode(), MooseMesh::nodeToActiveSemilocalElemMap(), and MooseMesh::update().
_node_to_active_semilocal_elem_map_built
bool MooseMesh::_node_to_active_semilocal_elem_map_built protected inherited
Definition at line 1450 of file MooseMesh.h.
Referenced by MooseMesh::nodeToActiveSemilocalElemMap(), and MooseMesh::update().
_node_to_elem_map
std::map<dof_id_type, std::vector<dof_id_type> > MooseMesh::_node_to_elem_map protected inherited
A map of all of the current nodes to the elements that they are connected to.
Definition at line 1445 of file MooseMesh.h.
Referenced by MooseMesh::addQuadratureNode(), MooseMesh::nodeToElemMap(), and MooseMesh::update().
_node_to_elem_map_built
bool MooseMesh::_node_to_elem_map_built protected inherited
Definition at line 1446 of file MooseMesh.h.
Referenced by MooseMesh::nodeToElemMap(), and MooseMesh::update().
_nodes_per_ring
const unsigned int SpiralAnnularMesh::_nodes_per_ring protected
Number of nodes on each ring.
Definition at line 44 of file SpiralAnnularMesh.h.
Referenced by buildMesh().
_num_rings
unsigned int SpiralAnnularMesh::_num_rings protected
Number of rings.You can't specify both the number of rings and the radial bias if you want to match a specified outer radius exactly... you have to leave one of those parameters free so that it can be determined.
Definition at line 53 of file SpiralAnnularMesh.h.
Referenced by buildMesh().
_outer_radius
const Real SpiralAnnularMesh::_outer_radius protected
Radius of the outer circle. Logically, it's bigger that inner_radius.
Definition at line 37 of file SpiralAnnularMesh.h.
Referenced by buildMesh(), and SpiralAnnularMesh().
_paired_boundary
std::vector<std::pair<BoundaryID, BoundaryID> > MooseMesh::_paired_boundary protected inherited
A vector holding the paired boundaries for a regular orthogonal mesh.
Definition at line 1523 of file MooseMesh.h.
Referenced by MooseMesh::detectPairedSidesets(), and MooseMesh::getPairedBoundaryMapping().
_parallel_type
ParallelType MooseMesh::_parallel_type protected inherited
Can be set to DISTRIBUTED, REPLICATED, or DEFAULT.
Determines whether the underlying libMesh mesh is a ReplicatedMesh or DistributedMesh.
Definition at line 1364 of file MooseMesh.h.
Referenced by MooseMesh::determineUseDistributedMesh(), and MooseMesh::setParallelType().
_parallel_type_overridden
bool MooseMesh::_parallel_type_overridden protected inherited
Definition at line 1371 of file MooseMesh.h.
Referenced by MooseMesh::determineUseDistributedMesh(), and MooseMesh::isParallelTypeForced().
_parent
const MooseObject & DataFileInterface< MooseObject >::_parent private inherited
Definition at line 46 of file DataFileInterface.h.
_pars
const InputParameters& MooseBaseParameterInterface::_pars protected inherited
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Definition at line 158 of file MooseBaseParameterInterface.h.
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), AddPeriodicBCAction::act(), AddVariableAction::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), FunctorMaterial::addFunctorPropertyByBlocks(), FVFluxKernel::adjustRMGhostLayers(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), PiecewiseTabularBase::buildFromFile(), PNGOutput::calculateRescalingValues(), BlockWeightedPartitioner::clone(), GridPartitioner::clone(), HierarchicalGridPartitioner::clone(), PetscExternalPartitioner::clone(), RandomPartitioner::clone(), SingleRankPartitioner::clone(), MooseBaseParameterInterface::connectControllableParams(), Console::Console(), AddVariableAction::createInitialConditionAction(), MaterialBase::declareADProperty(), MaterialBase::declareProperty(), FEProblemSolve::FEProblemSolve(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), FileMeshGenerator::generate(), MaterialBase::getGenericZeroMaterialProperty(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getParam(), MooseBaseParameterInterface::getRenamedParam(), AddVariableAction::init(), AdvancedOutput::initExecutionTypes(), Console::initialSetup(), MooseBaseParameterInterface::isParamSetByUser(), MooseBaseParameterInterface::isParamValid(), MultiApp::keepSolutionDuringRestore(), MooseBaseParameterInterface::paramErrorMsg(), GlobalParamsAction::parameters(), MooseBaseParameterInterface::parameters(), MooseMesh::prepare(), Eigenvalue::prepareSolverOptions(), MooseMesh::setCoordSystem(), MooseMesh::setPartitionerHelper(), SetupMeshAction::setupMesh(), Transient::setupTimeIntegrator(), MooseBaseParameterInterface::uniqueName(), and MooseBaseParameterInterface::uniqueParameterName().
_partitioner_name
MooseEnum MooseMesh::_partitioner_name protected inherited
The partitioner used on this mesh.
Definition at line 1377 of file MooseMesh.h.
Referenced by MooseMesh::partitionerName(), and MooseMesh::setPartitionerHelper().
_partitioner_overridden
bool MooseMesh::_partitioner_overridden protected inherited
Definition at line 1378 of file MooseMesh.h.
Referenced by MooseMesh::isPartitionerForced(), and MooseMesh::setPartitionerHelper().
_patch_size
unsigned int MooseMesh::_patch_size protected inherited
The number of nodes to consider in the NearestNode neighborhood.
Definition at line 1502 of file MooseMesh.h.
Referenced by MooseMesh::getPatchSize().
_patch_update_strategy
Moose::PatchUpdateType MooseMesh::_patch_update_strategy protected inherited
The patch update strategy.
Definition at line 1511 of file MooseMesh.h.
Referenced by MooseMesh::getPatchUpdateStrategy(), MooseMesh::MooseMesh(), and MooseMesh::setPatchUpdateStrategy().
_periodic_dim
std::map<unsigned int, std::vector<bool> > MooseMesh::_periodic_dim private inherited
A map of vectors indicating which dimensions are periodic in a regular orthogonal mesh for the specified variable numbers.
This data structure is populated by addPeriodicVariable.
Definition at line 1566 of file MooseMesh.h.
Referenced by MooseMesh::addPeriodicVariable(), and MooseMesh::isTranslatedPeriodic().
_pg_moose_app
MooseApp& PerfGraphInterface::_pg_moose_app protected inherited
The MooseApp that owns the PerfGraph.
Definition at line 124 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::perfGraph().
_prefix
const std::string PerfGraphInterface::_prefix protected inherited
A prefix to use for all sections.
Definition at line 127 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::timedSectionName().
_provided_coord_blocks
std::vector<SubdomainName> MooseMesh::_provided_coord_blocks private inherited
Set for holding user-provided coordinate system type block names.
Definition at line 1790 of file MooseMesh.h.
Referenced by MooseMesh::MooseMesh(), MooseMesh::prepare(), and MooseMesh::setCoordSystem().
_quadrature_nodes
std::map<dof_id_type, Node *> MooseMesh::_quadrature_nodes protected inherited
Definition at line 1487 of file MooseMesh.h.
Referenced by MooseMesh::addQuadratureNode(), MooseMesh::clearQuadratureNodes(), and MooseMesh::queryNodePtr().
_radial_bias
Real SpiralAnnularMesh::_radial_bias protected
Factor to increase initial_delta_r for each ring.
For a uniform grid : radial_bias = 1.0
Definition at line 41 of file SpiralAnnularMesh.h.
Referenced by buildMesh().
_refined_elements
std::unique_ptr<ConstElemPointerRange> MooseMesh::_refined_elements protected inherited
The elements that were just refined.
Definition at line 1416 of file MooseMesh.h.
Referenced by MooseMesh::cacheChangedLists(), and MooseMesh::refinedElementRange().
_regular_orthogonal_mesh
bool MooseMesh::_regular_orthogonal_mesh protected inherited
Boolean indicating whether this mesh was detected to be regular and orthogonal.
Definition at line 1517 of file MooseMesh.h.
Referenced by MooseMesh::addPeriodicVariable(), MooseMesh::detectOrthogonalDimRanges(), GeneratedMesh::GeneratedMesh(), MooseMesh::getPairedBoundaryMapping(), MooseMesh::isRegularOrthogonal(), and MooseMesh::prepared().
_relationship_managers
std::vector<std::shared_ptr<RelationshipManager> > MooseMesh::_relationship_managers protected inherited
The list of active geometric relationship managers (bound to the underlying MeshBase object).
Definition at line 1357 of file MooseMesh.h.
_restartable_app
MooseApp& Restartable::_restartable_app protected inherited
Reference to the application.
Definition at line 227 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp(), and Restartable::registerRestartableNameWithFilterOnApp().
_restartable_name
std::string Restartable::_restartable_name private inherited
The name of the object.
Definition at line 243 of file Restartable.h.
Referenced by Restartable::declareRestartableDataWithObjectNameWithContext(), and Restartable::restartableName().
_restartable_read_only
const bool Restartable::_restartable_read_only protected inherited
Flag for toggling read only status (see ReporterData)
Definition at line 236 of file Restartable.h.
Referenced by Restartable::registerRestartableDataOnApp().
_restartable_system_name
const std::string Restartable::_restartable_system_name protected inherited
The system name this object is in.
Definition at line 230 of file Restartable.h.
Referenced by Restartable::restartableName().
_restartable_tid
const THREAD_ID Restartable::_restartable_tid protected inherited
The thread ID for this object.
Definition at line 233 of file Restartable.h.
Referenced by Restartable::declareRestartableDataHelper().
_rz_coord_axis
unsigned int MooseMesh::_rz_coord_axis private inherited
Storage for RZ axis selection.
Definition at line 1777 of file MooseMesh.h.
Referenced by MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::setAxisymmetricCoordAxis(), and MooseMesh::setCoordData().
_semilocal_node_list
std::set<Node *> MooseMesh::_semilocal_node_list protected inherited
Used for generating the semilocal node range.
Definition at line 1429 of file MooseMesh.h.
Referenced by MooseMesh::isSemiLocal(), and MooseMesh::updateActiveSemiLocalNodeRange().
_skip_deletion_repartition_after_refine
bool MooseMesh::_skip_deletion_repartition_after_refine protected inherited
Whether or not skip remote deletion and repartition after uniform refinements.
Definition at line 1404 of file MooseMesh.h.
Referenced by MooseMesh::setUniformRefineLevel(), and MooseMesh::skipDeletionRepartitionAfterRefine().
_skip_refine_when_use_split
bool MooseMesh::_skip_refine_when_use_split protected inherited
Whether or not to skip uniform refinements when using a pre-split mesh.
Definition at line 1401 of file MooseMesh.h.
Referenced by MooseMesh::skipRefineWhenUseSplit().
_sub_to_neighbor_subs
std::unordered_map<SubdomainID, std::set<SubdomainID> > MooseMesh::_sub_to_neighbor_subs private inherited
Holds a map from subomdain ids to the neighboring subdomain ids.
Definition at line 1721 of file MooseMesh.h.
Referenced by MooseMesh::cacheInfo(), and MooseMesh::getBlockConnectedBlocks().
_subdomain_boundary_ids
std::unordered_map<SubdomainID, std::set<BoundaryID> > MooseMesh::_subdomain_boundary_ids private inherited
Holds a map from subomdain ids to the boundary ids that are attached to it.
Definition at line 1724 of file MooseMesh.h.
Referenced by MooseMesh::cacheInfo(), MooseMesh::getBoundaryConnectedBlocks(), and MooseMesh::getSubdomainBoundaryIds().
_subdomain_id_to_rz_coord_axis
std::unordered_map<SubdomainID, std::pair<Point, RealVectorValue> > MooseMesh::_subdomain_id_to_rz_coord_axis private inherited
Map of subdomain ID to general axisymmetric axis.
Definition at line 1780 of file MooseMesh.h.
Referenced by MooseMesh::getGeneralAxisymmetricCoordAxis(), MooseMesh::setCoordData(), MooseMesh::setGeneralAxisymmetricCoordAxes(), and MooseMesh::usingGeneralAxisymmetricCoordAxes().
_type
const std::string& MooseBase::_type protected inherited
The type of this class.
Definition at line 63 of file MooseBase.h.
Referenced by FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), FEProblemBase::init(), FEProblemBase::solverTypeString(), and MooseBase::type().
_uniform_refine_level
unsigned int MooseMesh::_uniform_refine_level protected inherited
The level of uniform refinement requested (set to zero if AMR is disabled)
Definition at line 1398 of file MooseMesh.h.
Referenced by MooseMesh::setUniformRefineLevel(), and MooseMesh::uniformRefineLevel().
_use_distributed_mesh
bool MooseMesh::_use_distributed_mesh protected inherited
False by default.
Final value is determined by several factors including the 'distribution' setting in the input file, and whether or not the Mesh file is a Nemesis file.
Definition at line 1369 of file MooseMesh.h.
Referenced by MooseMesh::buildMeshBaseObject(), MooseMesh::buildTypedMesh(), MooseMesh::detectPairedSidesets(), MooseMesh::determineUseDistributedMesh(), MooseMesh::errorIfDistributedMesh(), MooseMesh::ghostGhostedBoundaries(), MooseMesh::init(), MooseMesh::isDistributedMesh(), and MooseMesh::setPartitionerHelper().
_use_tri6
const bool SpiralAnnularMesh::_use_tri6 protected
Generate mesh of TRI6 elements instead of TRI3 elements.
Definition at line 47 of file SpiralAnnularMesh.h.
Referenced by buildMesh().
The documentation for this class was generated from the following files:
moose/framework/include/mesh/SpiralAnnularMesh.h
moose/framework/src/mesh/SpiralAnnularMesh.C