Zapdos: FaceInfo Class Reference
FaceInfo Class Reference
This data structure is used to store geometric and variable related metadata about each cell face in the mesh.
#include <FaceInfo.h>
Public Types
enum class VarFaceNeighbors { BOTH , NEITHER , ELEM , NEIGHBOR }
This enum is used to indicate which side(s) of a face a particular variable is defined on.
Public Member Functions
FaceInfo (const ElemInfo *const elem_info, const unsigned int side, const dof_id_type id)
dof_id_type id () const
Return the ID of the face.
Real faceArea () const
Returns the face area of face id.
Real & faceCoord ()
Sets/gets the coordinate transformation factor (for e.g.
Real faceCoord () const
const Point & normal () const
Returns the unit normal vector for the face oriented outward from the face's elem element.
const Point & faceCentroid () const
Returns the coordinates of the face centroid.
Point skewnessCorrectionVector () const
Returns the skewness-correction vector (vector between the approximate and real face centroids).
const Point & elemCentroid () const
Returns the element centroids of the elements on the elem and neighbor sides of the face.
const Point & neighborCentroid () const
VarFaceNeighbors faceType (const std::pair< unsigned int, unsigned int > &var_sys) const
Returns which side(s) the given variable-system number pair is defined on for this face.
VarFaceNeighbors & faceType (const std::pair< unsigned int, unsigned int > &var_sys)
Mutably returns which side(s) the given variable-system number pair is defined on for this face.
const std::set< BoundaryID > & boundaryIDs () const
std::set< BoundaryID > & boundaryIDs ()
Returns the set of boundary ids for all boundaries that include this face.
Real elemVolume () const
Return the element volume.
Real neighborVolume () const
Return the neighbor volume.
Real gC () const
Return the geometric weighting factor.
const Point & dCN () const
Real dCNMag () const
const Point & eCN () const
processor_id_type processor_id () const
void computeInternalCoefficients (const ElemInfo *const neighbor_info)
Takes the ElemInfo of the neighbor cell and computes interpolation weights together with other quantities used to generate spatial operators.
void computeBoundaryCoefficients ()
Computes the interpolation weights and similar quantities with the assumption that the face is on a boundary.
const Elem & elem () const
const Elem * elemPtr () const
const Elem & neighbor () const
const Elem * neighborPtr () const
SubdomainID elemSubdomainID () const
SubdomainID neighborSubdomainID () const
unsigned int elemSideID () const
unsigned int neighborSideID () const
Private Attributes
const ElemInfo *const _elem_info
the elem and neighbor elems
const ElemInfo * _neighbor_info
const dof_id_type _id
Real _face_coord = 0
Point _normal
const processor_id_type _processor_id
const unsigned int _elem_side_id
the elem local side id
unsigned int _neighbor_side_id
Real _face_area
Point _face_centroid
Point _d_cn
the distance vector between neighbor and element centroids
Point _e_cn
Real _d_cn_mag
the distance norm between neighbor and element centroids
Real _gc
Geometric weighting factor for face value interpolation.
std::map< std::pair< unsigned int, unsigned int >, VarFaceNeighbors > _face_types_by_var
a map that provides the information about what face type this is for each variable.
std::set< BoundaryID > _boundary_ids
the set of boundary ids that this face is associated with
Detailed Description
This data structure is used to store geometric and variable related metadata about each cell face in the mesh.
This info is used by face loops (e.g. for finite volumes method numerical flux loop). These objects can be created and cached up front. Since it only stores information that changes when the mesh is modified it only needs an update whenever the mesh changes.
Definition at line 35 of file FaceInfo.h.
Member Enumeration Documentation
VarFaceNeighbors
enum class FaceInfo::VarFaceNeighbors strong
This enum is used to indicate which side(s) of a face a particular variable is defined on.
This is important for certain BC-related finite volume calculations. Because of the way side-sets and variable block-restriction work in MOOSE, there may be boundary conditions applied to internal faces on the mesh where a variable is only active on one or even zero sides of the face. For such faces, FV needs to know which sides (if any) to add BC residual contributions to.
Enumerator
BOTH
NEITHER
ELEM
NEIGHBOR
Definition at line 47 of file FaceInfo.h.
  {
    BOTH,
    NEITHER,
    ELEM,
    NEIGHBOR
  };
Constructor & Destructor Documentation
FaceInfo()
FaceInfo::FaceInfo (const ElemInfo *const elem_info, const unsigned int side, const dof_id_type id)
Definition at line 19 of file FaceInfo.C.
  : _elem_info(elem_info),
    _neighbor_info(nullptr),
    _id(id),
    _processor_id(_elem_info->elem()->processor_id()),
    _elem_side_id(side),
    _neighbor_side_id(libMesh::invalid_uint),
    _gc(0.5)
{
  // Compute face-related quantities
  unsigned int dim = _elem_info->elem()->dim();
  const std::unique_ptr<const Elem> face = _elem_info->elem()->build_side_ptr(_elem_side_id);
  std::unique_ptr<FEBase> fe(FEBase::build(dim, FEType(_elem_info->elem()->default_order())));
  QGauss qface(dim - 1, CONSTANT);
  fe->attach_quadrature_rule(&qface);
  const std::vector<Point> & normals = fe->get_normals();
  fe->reinit(_elem_info->elem(), _elem_side_id);
  mooseAssert(normals.size() == 1, "FaceInfo construction broken w.r.t. computing face normals");
  _normal = normals[0];
  _face_area = face->volume();
  _face_centroid = face->vertex_average();
}
Member Function Documentation
boundaryIDs() [1/2]
std::set< BoundaryID > & FaceInfo::boundaryIDs () inline
Returns the set of boundary ids for all boundaries that include this face.
Definition at line 119 of file FaceInfo.h.
{ return _boundary_ids; }
boundaryIDs() [2/2]
const std::set< BoundaryID > & FaceInfo::boundaryIDs () const inline
Definition at line 116 of file FaceInfo.h.
{ return _boundary_ids; }
Referenced by FVFluxKernel::avoidBoundary(), and FVFluxKernel::skipForBoundary().
computeBoundaryCoefficients()
void FaceInfo::computeBoundaryCoefficients ()
Computes the interpolation weights and similar quantities with the assumption that the face is on a boundary.
Definition at line 65 of file FaceInfo.C.
{
  mooseAssert(!_neighbor_info, "This functions shall only be called on a boundary!");
  // Setup quantities used for the approximation of the spatial derivatives
  _d_cn = _face_centroid - _elem_info->centroid();
  _d_cn_mag = _d_cn.norm();
  _e_cn = _d_cn / _d_cn_mag;
  // For interpolation coefficients
  _gc = 1.0;
}
computeInternalCoefficients()
void FaceInfo::computeInternalCoefficients (const ElemInfo *const neighbor_info)
Takes the ElemInfo of the neighbor cell and computes interpolation weights together with other quantities used to generate spatial operators.
Definition at line 44 of file FaceInfo.C.
{
  mooseAssert(neighbor_info,
              "We need a neighbor if we want to compute interpolation coefficients!");
  _neighbor_info = neighbor_info;
  _neighbor_side_id = _neighbor_info->elem()->which_neighbor_am_i(_elem_info->elem());
  // Setup quantities used for the approximation of the spatial derivatives
  _d_cn = _neighbor_info->centroid() - _elem_info->centroid();
  _d_cn_mag = _d_cn.norm();
  _e_cn = _d_cn / _d_cn_mag;
  Point r_intersection =
      _elem_info->centroid() +
      (((_face_centroid - _elem_info->centroid()) * _normal) / (_e_cn * _normal)) * _e_cn;
  // For interpolation coefficients
  _gc = (_neighbor_info->centroid() - r_intersection).norm() / _d_cn_mag;
}
dCN()
const Point & FaceInfo::dCN () const inline
Returns
the distance vector drawn from centroid C to N, or in terms of MOOSE implementation, the distance vector obtained from subtracting the element centroid from the neighbor centroid
Definition at line 134 of file FaceInfo.h.
{ return _d_cn; }
Referenced by Moose::FV::interpCoeffs().
dCNMag()
Real FaceInfo::dCNMag () const inline
Returns
the magnitude of the distance vector between centroids C and N, or in terms of MOOSE implementation, the magnitude of the distance vector between neighbor and element centroids
Definition at line 140 of file FaceInfo.h.
{ return _d_cn_mag; }
Referenced by MooseVariableFV< OutputType >::adGradSln(), and FVOrthogonalDiffusion::computeQpResidual().
eCN()
const Point & FaceInfo::eCN () const inline
Returns
the normalized (e.g. unit) distance vector drawn from centroid C to N, or in terms of MOOSE implementation, the normalized (e.g. unit) distance vector obtained from subtracting the element centroid from the neighbor centroid
Definition at line 147 of file FaceInfo.h.
{ return _e_cn; }
Referenced by MooseVariableFV< OutputType >::adGradSln().
elem()
const Elem & FaceInfo::elem () const inline
Returns the elem and neighbor elements adjacent to the face. If a face is on a mesh boundary, the neighborPtr will return nullptr - the elem will never be null.
Definition at line 80 of file FaceInfo.h.
{ return *(_elem_info->elem()); }
Referenced by MooseVariableFV< OutputType >::adGradSln(), FVDiffusionInterface::computeQpResidual(), Moose::FV::determineElemOneAndTwo(), FVFluxBC::elemArg(), Function::evaluate(), MooseVariableFE< OutputType >::faceEvaluate(), MooseVariableFV< Real >::getExtrapolatedBoundaryFaceValue(), Moose::FunctorBase< T >::hasFaceSide(), FVFluxKernel::hasFaceSide(), SideIntegralFunctorPostprocessorTempl< is_ad >::hasFaceSide(), PiecewiseByBlockLambdaFunctor< T >::isExtrapolatedBoundaryFace(), Moose::FunctorBase< T >::isInternalFace(), Moose::FV::loopOverElemFaceInfo(), Moose::FaceArg::makeElem(), FaceArgProducerInterface::makeFace(), Moose::FV::onBoundary(), Assembly::reinitFVFace(), and FVInterfaceKernel::setupData().
elemCentroid()
const Point & FaceInfo::elemCentroid () const inline
Returns the element centroids of the elements on the elem and neighbor sides of the face.
If no neighbor face is defined, a "ghost" neighbor centroid is calculated by reflecting/extrapolating from the elem centroid through the face centroid
i.e. the vector from the elem element centroid to the face centroid is doubled in length. The tip of this new vector is the neighbor centroid. This is important for FV dirichlet BCs.
Definition at line 92 of file FaceInfo.h.
{ return _elem_info->centroid(); }
Referenced by MooseVariableFV< OutputType >::adGradSln(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), and FVDiffusionInterface::computeQpResidual().
elemPtr()
const Elem * FaceInfo::elemPtr () const inline
Definition at line 81 of file FaceInfo.h.
{ return _elem_info->elem(); }
Referenced by FVFunctorDirichletBCTempl< is_ad >::boundaryValue(), Moose::FunctorBase< T >::checkFace(), SideAdvectiveFluxIntegralTempl< is_ad >::computeFaceInfoIntegral(), FVInterfaceKernel::elemArg(), FVFluxKernel::elemArg(), Function::evaluate(), MooseVariableFV< OutputType >::evaluate(), and MooseVariableFE< OutputType >::faceEvaluate().
elemSideID()
unsigned int FaceInfo::elemSideID () const inline
Returns the elem and neighbor centroids. If no neighbor element exists, then the maximum unsigned int is returned for the neighbor side ID.
Definition at line 106 of file FaceInfo.h.
{ return _elem_side_id; }
Referenced by MooseVariableFE< OutputType >::faceEvaluate(), and Assembly::reinitFVFace().
elemSubdomainID()
SubdomainID FaceInfo::elemSubdomainID () const inline
Returns the elem and neighbor subdomain IDs. If no neighbor element exists, then an invalid ID is returned for the neighbor subdomain ID.
Definition at line 99 of file FaceInfo.h.
{ return _elem_info->subdomain_id(); }
Referenced by Moose::FV::onBoundary().
elemVolume()
Real FaceInfo::elemVolume () const inline
Return the element volume.
Definition at line 122 of file FaceInfo.h.
{ return _elem_info->volume(); }
faceArea()
Real FaceInfo::faceArea () const inline
Returns the face area of face id.
Definition at line 59 of file FaceInfo.h.
{ return _face_area; }
Referenced by FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVScalarLagrangeMultiplierInterface::computeJacobian(), FVFluxBC::computeResidual(), FVInterfaceKernel::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), FVScalarLagrangeMultiplierInterface::computeResidual(), and Moose::FV::loopOverElemFaceInfo().
faceCentroid()
const Point & FaceInfo::faceCentroid () const inline
Returns the coordinates of the face centroid.
Definition at line 70 of file FaceInfo.h.
{ return _face_centroid; }
Referenced by MooseVariableFV< OutputType >::adGradSln(), FVFunctionDirichletBC::boundaryValue(), Moose::FunctorBase< T >::checkFace(), MooseMeshUtils::computeFaceInfoFaceCoord(), FVFunctionNeumannBC::computeQpResidual(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), FVFluxBC::computeResidual(), Moose::FaceArg::getPoint(), and Moose::FV::loopOverElemFaceInfo().
faceCoord() [1/2]
Real & FaceInfo::faceCoord () inline
Sets/gets the coordinate transformation factor (for e.g.
rz, spherical coords) to be used for integration over faces.
Definition at line 63 of file FaceInfo.h.
{ return _face_coord; }
Referenced by MooseMeshUtils::computeFaceInfoFaceCoord(), FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVScalarLagrangeMultiplierInterface::computeJacobian(), FVFluxBC::computeResidual(), FVInterfaceKernel::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), and FVScalarLagrangeMultiplierInterface::computeResidual().
faceCoord() [2/2]
Real FaceInfo::faceCoord () const inline
Definition at line 64 of file FaceInfo.h.
{ return _face_coord; }
faceType() [1/2]
FaceInfo::VarFaceNeighbors & FaceInfo::faceType (const std::pair< unsigned int, unsigned int > & var_sys) inline
Mutably returns which side(s) the given variable-system number pair is defined on for this face.
Definition at line 227 of file FaceInfo.h.
{
  return _face_types_by_var[var_sys];
}
faceType() [2/2]
FaceInfo::VarFaceNeighbors FaceInfo::faceType (const std::pair< unsigned int, unsigned int > & var_sys) const inline
Returns which side(s) the given variable-system number pair is defined on for this face.
Definition at line 214 of file FaceInfo.h.
{
  auto it = _face_types_by_var.find(var_sys);
  if (it == _face_types_by_var.end())
    mooseError("Variable number ",
               var_sys.first,
               " in system number ",
               var_sys.second,
               " not found in variable to VarFaceNeighbors map");
  return it->second;
}
Referenced by MooseVariableFV< OutputType >::computeFaceValues(), FVFluxBC::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), FVFluxBC::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), Moose::FV::determineElemOneAndTwo(), FVBoundaryCondition::hasFaceSide(), FVInterfaceKernel::setupData(), FVFluxBC::uOnGhost(), and FVFluxBC::uOnUSub().
gC()
Real FaceInfo::gC () const inline
Return the geometric weighting factor.
Definition at line 128 of file FaceInfo.h.
{ return _gc; }
Referenced by Moose::FV::interpCoeffs().
id()
dof_id_type FaceInfo::id () const inline
Return the ID of the face.
Definition at line 56 of file FaceInfo.h.
{ return _id; }
neighbor()
const Elem & FaceInfo::neighbor () const inline
Definition at line 205 of file FaceInfo.h.
{
  mooseAssert(_neighbor_info,
              "FaceInfo object 'const Elem & neighbor()' is called but neighbor element pointer "
              "is null. This occurs for faces at the domain boundary");
  return *(_neighbor_info->elem());
}
Referenced by Function::evaluate(), Moose::FunctorBase< T >::hasFaceSide(), FVFluxKernel::hasFaceSide(), PiecewiseByBlockLambdaFunctor< T >::isExtrapolatedBoundaryFace(), and Moose::FV::onBoundary().
neighborCentroid()
const Point & FaceInfo::neighborCentroid () const inline
Definition at line 233 of file FaceInfo.h.
{
  mooseAssert(_neighbor_info,
              "The neighbor is not defined on this faceInfo! A possible explanation is that the "
              "face is a (physical/processor) boundary face.");
  return _neighbor_info->centroid();
}
Referenced by MooseVariableFV< OutputType >::adGradSln(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), and FVDiffusionInterface::computeQpResidual().
neighborPtr()
const Elem * FaceInfo::neighborPtr () const inline
Definition at line 83 of file FaceInfo.h.
{ return _neighbor_info ? _neighbor_info->elem() : nullptr; }
Referenced by MooseVariableFV< OutputType >::adGradSln(), FVFunctorDirichletBCTempl< is_ad >::boundaryValue(), Moose::FunctorBase< T >::checkFace(), FVDiffusionInterface::computeQpResidual(), Moose::FV::determineElemOneAndTwo(), Function::evaluate(), MooseVariableFV< OutputType >::evaluate(), MooseVariableFE< OutputType >::faceEvaluate(), MooseVariableFV< Real >::getExtrapolatedBoundaryFaceValue(), Moose::FunctorBase< T >::hasFaceSide(), FVFluxKernel::hasFaceSide(), SideIntegralFunctorPostprocessorTempl< is_ad >::hasFaceSide(), PiecewiseByBlockLambdaFunctor< T >::isExtrapolatedBoundaryFace(), Moose::FunctorBase< T >::isInternalFace(), Moose::FV::loopOverElemFaceInfo(), FaceArgProducerInterface::makeFace(), Moose::FaceArg::makeNeighbor(), FVInterfaceKernel::neighborArg(), FVFluxBC::neighborArg(), FVFluxKernel::neighborArg(), Moose::FV::onBoundary(), Assembly::reinitFVFace(), and ComputeFVFluxThread< RangeType, AttributeTagType >::reinitVariables().
neighborSideID()
unsigned int FaceInfo::neighborSideID () const inline
Definition at line 107 of file FaceInfo.h.
{ return _neighbor_side_id; }
Referenced by MooseVariableFE< OutputType >::faceEvaluate(), and Assembly::reinitFVFace().
neighborSubdomainID()
SubdomainID FaceInfo::neighborSubdomainID () const inline
Definition at line 242 of file FaceInfo.h.
{
  return _neighbor_info ? _neighbor_info->subdomain_id() : Moose::INVALID_BLOCK_ID;
}
Referenced by Moose::FV::onBoundary().
neighborVolume()
Real FaceInfo::neighborVolume () const inline
Return the neighbor volume.
Definition at line 248 of file FaceInfo.h.
{
  mooseAssert(_neighbor_info,
              "The neighbor is not defined on this faceInfo! A possible explanation is that the "
              "face is a (physical/processor) boundary face.");
  return _neighbor_info->volume();
}
normal()
const Point & FaceInfo::normal () const inline
Returns the unit normal vector for the face oriented outward from the face's elem element.
Definition at line 67 of file FaceInfo.h.
{ return _normal; }
Referenced by SideAdvectiveFluxIntegralTempl< is_ad >::computeFaceInfoIntegral(), FVFluxBC::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVFluxBC::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), Function::evaluate(), Moose::FV::gradUDotNormal(), Moose::FV::interpCoeffs(), Moose::FV::interpolate(), Moose::FV::loopOverElemFaceInfo(), and FVInterfaceKernel::setupData().
processor_id()
processor_id_type FaceInfo::processor_id () const inline
Returns
the ID of the processor that owns this object
Definition at line 152 of file FaceInfo.h.
{ return _processor_id; }
skewnessCorrectionVector()
Point FaceInfo::skewnessCorrectionVector () const
Returns the skewness-correction vector (vector between the approximate and real face centroids).
Definition at line 79 of file FaceInfo.C.
{
  const Point r_intersection =
      _elem_info->centroid() +
      (((_face_centroid - _elem_info->centroid()) * _normal) / (_e_cn * _normal)) * _e_cn;
  return _face_centroid - r_intersection;
}
Referenced by Moose::FV::skewCorrectedLinearInterpolation().
Member Data Documentation
_boundary_ids
std::set<BoundaryID> FaceInfo::_boundary_ids private
the set of boundary ids that this face is associated with
Definition at line 201 of file FaceInfo.h.
Referenced by boundaryIDs().
_d_cn
Point FaceInfo::_d_cn private
the distance vector between neighbor and element centroids
Definition at line 186 of file FaceInfo.h.
Referenced by computeBoundaryCoefficients(), computeInternalCoefficients(), and dCN().
_d_cn_mag
Real FaceInfo::_d_cn_mag private
the distance norm between neighbor and element centroids
Definition at line 190 of file FaceInfo.h.
Referenced by computeBoundaryCoefficients(), computeInternalCoefficients(), and dCNMag().
_e_cn
Point FaceInfo::_e_cn private
Definition at line 187 of file FaceInfo.h.
Referenced by computeBoundaryCoefficients(), computeInternalCoefficients(), eCN(), and skewnessCorrectionVector().
_elem_info
const ElemInfo* const FaceInfo::_elem_info private
the elem and neighbor elems
Definition at line 168 of file FaceInfo.h.
Referenced by computeBoundaryCoefficients(), computeInternalCoefficients(), elem(), elemCentroid(), elemPtr(), elemSubdomainID(), elemVolume(), FaceInfo(), and skewnessCorrectionVector().
_elem_side_id
const unsigned int FaceInfo::_elem_side_id private
the elem local side id
Definition at line 179 of file FaceInfo.h.
Referenced by elemSideID(), and FaceInfo().
_face_area
Real FaceInfo::_face_area private
Definition at line 182 of file FaceInfo.h.
Referenced by faceArea(), and FaceInfo().
_face_centroid
Point FaceInfo::_face_centroid private
Definition at line 183 of file FaceInfo.h.
Referenced by computeBoundaryCoefficients(), computeInternalCoefficients(), faceCentroid(), FaceInfo(), and skewnessCorrectionVector().
_face_coord
Real FaceInfo::_face_coord = 0 private
Definition at line 173 of file FaceInfo.h.
Referenced by faceCoord().
_face_types_by_var
std::map<std::pair<unsigned int, unsigned int>, VarFaceNeighbors> FaceInfo::_face_types_by_var private
a map that provides the information about what face type this is for each variable.
The first member of the key is the variable number; the second member of the key is the number of the system that the variable lives in
Definition at line 198 of file FaceInfo.h.
Referenced by faceType().
_gc
Real FaceInfo::_gc private
Geometric weighting factor for face value interpolation.
Definition at line 193 of file FaceInfo.h.
Referenced by computeBoundaryCoefficients(), computeInternalCoefficients(), and gC().
_id
const dof_id_type FaceInfo::_id private
Definition at line 171 of file FaceInfo.h.
Referenced by id().
_neighbor_info
const ElemInfo* FaceInfo::_neighbor_info private
Definition at line 169 of file FaceInfo.h.
Referenced by computeBoundaryCoefficients(), computeInternalCoefficients(), neighbor(), neighborCentroid(), neighborPtr(), neighborSubdomainID(), and neighborVolume().
_neighbor_side_id
unsigned int FaceInfo::_neighbor_side_id private
Definition at line 180 of file FaceInfo.h.
Referenced by computeInternalCoefficients(), and neighborSideID().
_normal
Point FaceInfo::_normal private
Definition at line 174 of file FaceInfo.h.
Referenced by computeInternalCoefficients(), FaceInfo(), normal(), and skewnessCorrectionVector().
_processor_id
const processor_id_type FaceInfo::_processor_id private
Definition at line 176 of file FaceInfo.h.
Referenced by processor_id().
The documentation for this class was generated from the following files:
moose/framework/include/mesh/FaceInfo.h
moose/framework/src/mesh/FaceInfo.C