Zapdos: MooseVariableFV< OutputType > Class Template Reference
MooseVariableFV< OutputType > Class Template Reference
This class provides variable solution values for other classes/objects to bind to when looping over faces or elements.
#include <MooseVariableFV.h>
Public Types
using OutputGradient = typename MooseVariableField< OutputType >::OutputGradient
using OutputSecond = typename MooseVariableField< OutputType >::OutputSecond
using OutputDivergence = typename MooseVariableField< OutputType >::OutputDivergence
using FieldVariableValue = typename MooseVariableField< OutputType >::FieldVariableValue
using FieldVariableGradient = typename MooseVariableField< OutputType >::FieldVariableGradient
using FieldVariableSecond = typename MooseVariableField< OutputType >::FieldVariableSecond
using FieldVariableCurl = typename MooseVariableField< OutputType >::FieldVariableCurl
using FieldVariableDivergence = typename MooseVariableField< OutputType >::FieldVariableDivergence
using OutputShape = typename MooseVariableField< OutputType >::OutputShape
using OutputShapeGradient = typename MooseVariableField< OutputType >::OutputShapeGradient
using OutputShapeSecond = typename MooseVariableField< OutputType >::OutputShapeSecond
using OutputShapeDivergence = typename MooseVariableField< OutputType >::OutputShapeDivergence
using OutputData = typename MooseVariableField< OutputType >::OutputData
using DoFValue = typename MooseVariableField< OutputType >::DoFValue
using FieldVariablePhiValue = typename MooseVariableField< OutputType >::FieldVariablePhiValue
using FieldVariablePhiDivergence = typename MooseVariableField< OutputType >::FieldVariablePhiDivergence
using FieldVariablePhiGradient = typename MooseVariableField< OutputType >::FieldVariablePhiGradient
using FieldVariablePhiSecond = typename MooseVariableField< OutputType >::FieldVariablePhiSecond
using ElemQpArg = Moose::ElemQpArg
using ElemSideQpArg = Moose::ElemSideQpArg
using ElemArg = Moose::ElemArg
using FaceArg = Moose::FaceArg
using StateArg = Moose::StateArg
using NodeArg = Moose::NodeArg
using ElemPointArg = Moose::ElemPointArg
typedef MooseArray< std::vector< OutputShape > > FieldVariablePhiCurl
typedef MooseArray< std::vector< OutputShape > > FieldVariableTestValue
typedef MooseArray< std::vector< OutputShapeGradient > > FieldVariableTestGradient
typedef MooseArray< std::vector< OutputShapeSecond > > FieldVariableTestSecond
typedef MooseArray< std::vector< OutputShape > > FieldVariableTestCurl
typedef MooseArray< std::vector< OutputShapeDivergence > > FieldVariableTestDivergence
using FunctorType = FunctorBase< Moose::ADType< OutputType >::type >
using FunctorReturnType = Moose::ADType< OutputType >::type
using ValueType = Moose::ADType< OutputType >::type
using GradientType = typename MetaPhysicL::ReplaceAlgebraicType< Moose::ADType< OutputType >::type, typename TensorTools::IncrementRank< typename MetaPhysicL::ValueType< Moose::ADType< OutputType >::type >::type >::type >::type
This rigmarole makes it so that a user can create functors that return containers (std::vector, std::array).
using DotType = ValueType
Public Member Functions
MooseVariableFV (const InputParameters &parameters)
virtual bool isFV () const override
virtual void prepare () override final
Prepare the elemental degrees of freedom.
virtual void prepareNeighbor () override final
Prepare the neighbor element degrees of freedom.
virtual void prepareAux () override final
virtual void reinitNode () override final
virtual void reinitNodes (const std::vector< dof_id_type > &) override final
virtual void reinitNodesNeighbor (const std::vector< dof_id_type > &) override final
virtual void reinitAux () override final
virtual void reinitAuxNeighbor () override final
virtual void prepareLowerD () override final
Prepare a lower dimensional element's degrees of freedom.
virtual const dof_id_type & nodalDofIndex () const override final
virtual const dof_id_type & nodalDofIndexNeighbor () const override final
virtual std::size_t phiSize () const override final
Return phi size.
virtual std::size_t phiFaceSize () const override final
Return phiFace size.
virtual std::size_t phiNeighborSize () const override final
Return phiNeighbor size.
virtual std::size_t phiFaceNeighborSize () const override final
Return phiFaceNeighbor size.
virtual std::size_t phiLowerSize () const override final
Return the number of shape functions on the lower dimensional element for this variable.
virtual void computeElemValuesFace () override
Compute values at facial quadrature points.
virtual void computeNeighborValuesFace () override
Compute values at facial quadrature points for the neighbor.
virtual void computeNeighborValues () override
Compute values at quadrature points for the neighbor.
virtual void computeLowerDValues () override final
compute values at quadrature points on the lower dimensional element
virtual void computeNodalNeighborValues () override final
Compute nodal values of this variable in the neighbor.
virtual void computeNodalValues () override final
Compute nodal values of this variable.
virtual const std::vector< dof_id_type > & dofIndicesLower () const override final
Get dof indices for the current lower dimensional element (this is meaningful when performing mortar FEM)
unsigned int numberOfDofs () const override final
Get the number of local DoFs.
virtual unsigned int numberOfDofsNeighbor () override final
virtual bool isNodal () const override final
Is this variable nodal.
bool hasDoFsOnNodes () const override final
Does this variable have DoFs on nodes.
FEContinuity getContinuity () const override final
Return the continuity of this variable.
virtual bool isNodalDefined () const override final
Is this variable defined at nodes.
virtual void setNodalValue (const OutputType &value, unsigned int idx=0) override
virtual void setDofValue (const OutputData &value, unsigned int index) override
Degree of freedom value setters.
void clearDofIndices () override
Clear out the dof indices.
virtual void prepareIC () override
Prepare the initial condition.
Moose::VarFieldType fieldType () const override
Filed type of this variable.
bool isArray () const override
bool isVector () const override
virtual const Elem *const & currentElem () const override
Current element this variable is evaluated at.
virtual void getDofIndices (const Elem *elem, std::vector< dof_id_type > &dof_indices) const override
virtual const std::vector< dof_id_type > & dofIndices () const final
Get local DoF indices.
virtual const std::vector< dof_id_type > & dofIndicesNeighbor () const final
Get neighbor DOF indices for currently selected element.
Moose::FV::InterpMethod faceInterpolationMethod () const
void clearAllDofIndices () final
const DoFValue & nodalVectorTagValue (TagID) const override
const FieldVariableValue & vectorTagValue (TagID tag) const override
tag values getters
const DoFValue & vectorTagDofValue (TagID tag) const override
const FieldVariableValue & matrixTagValue (TagID tag)
const FieldVariableValue & vectorTagValueNeighbor (TagID tag)
const FieldVariableValue & matrixTagValueNeighbor (TagID tag)
const FieldVariableValue & uDot () const
const FieldVariableValue & sln () const override
const FieldVariableValue & slnOld () const override
const FieldVariableValue & slnOlder () const override
const FieldVariableGradient & gradSln () const override
element gradients
const FieldVariableGradient & gradSlnOld () const override
const FieldVariableValue & uDotNeighbor () const
const FieldVariableValue & slnNeighbor () const override
const FieldVariableValue & slnOldNeighbor () const override
const FieldVariableGradient & gradSlnNeighbor () const override
neighbor solution gradients
const FieldVariableGradient & gradSlnOldNeighbor () const override
const VariableValue & duDotDu () const
const VariableValue & duDotDotDu () const
const VariableValue & duDotDuNeighbor () const
const VariableValue & duDotDotDuNeighbor () const
const ADTemplateVariableValue< OutputType > & adSln () const override
AD.
const ADTemplateVariableGradient< OutputType > & adGradSln () const override
AD grad solution getter.
virtual const VectorValue< ADReal > & adGradSln (const Elem *const elem, const StateArg &state, const bool correct_skewness=false) const
Retrieve (or potentially compute) the gradient on the provided element.
virtual VectorValue< ADReal > adGradSln (const FaceInfo &fi, const StateArg &state, const bool correct_skewness=false) const
Retrieve (or potentially compute) a cross-diffusion-corrected gradient on the provided face.
virtual VectorValue< ADReal > uncorrectedAdGradSln (const FaceInfo &fi, const StateArg &state, const bool correct_skewness=false) const
Retrieve (or potentially compute) the uncorrected gradient on the provided face.
ADReal getBoundaryFaceValue (const FaceInfo &fi, const StateArg &state, bool correct_skewness=false) const
Retrieve the solution value at a boundary face.
const ADTemplateVariableSecond< OutputType > & adSecondSln () const override
AD second solution getter.
const ADTemplateVariableValue< OutputType > & adUDot () const override
AD time derivative getter.
const ADTemplateVariableValue< OutputType > & adUDotDot () const override
AD second time derivative getter.
const ADTemplateVariableGradient< OutputType > & adGradSlnDot () const override
AD grad of time derivative solution getter.
const ADTemplateVariableValue< OutputType > & adSlnNeighbor () const override
neighbor AD
const ADTemplateVariableGradient< OutputType > & adGradSlnNeighbor () const override
AD grad neighbor solution getter.
const ADTemplateVariableSecond< OutputType > & adSecondSlnNeighbor () const override
AD second neighbor solution getter.
const ADTemplateVariableValue< OutputType > & adUDotNeighbor () const override
AD neighbor time derivative getter.
const ADTemplateVariableValue< OutputType > & adUDotDotNeighbor () const override
AD neighbor second time derivative getter.
const ADTemplateVariableGradient< OutputType > & adGradSlnNeighborDot () const override
AD grad of time derivative neighbor solution getter.
virtual void computeElemValues () override
Initializes/computes variable values from the solution vectors for the current element being operated on in assembly.
virtual void computeFaceValues (const FaceInfo &fi) override
Initializes/computes variable values from the solution vectors for the face represented by fi.
void setDofValues (const DenseVector< OutputData > &values) override
Set local DOF values and evaluate the values on quadrature points.
OutputData getElementalValue (const Elem *elem, unsigned int idx=0) const
Get the current value of this variable on an element.
OutputData getElementalValueOld (const Elem *elem, unsigned int idx=0) const
Get the old value of this variable on an element.
OutputData getElementalValueOlder (const Elem *elem, unsigned int idx=0) const
Get the older value of this variable on an element.
virtual void insert (NumericVector< Number > &residual) override
virtual void add (NumericVector< Number > &residual) override
const DoFValue & dofValues () const override
dof values getters
const DoFValue & dofValuesOld () const override
const DoFValue & dofValuesOlder () const override
const DoFValue & dofValuesPreviousNL () const override
const DoFValue & dofValuesNeighbor () const override
const DoFValue & dofValuesOldNeighbor () const override
const DoFValue & dofValuesOlderNeighbor () const override
const DoFValue & dofValuesPreviousNLNeighbor () const override
const DoFValue & dofValuesDot () const override
const DoFValue & dofValuesDotNeighbor () const override
const DoFValue & dofValuesDotOld () const override
const DoFValue & dofValuesDotOldNeighbor () const override
const DoFValue & dofValuesDotDot () const override
const DoFValue & dofValuesDotDotNeighbor () const override
const DoFValue & dofValuesDotDotOld () const override
const DoFValue & dofValuesDotDotOldNeighbor () const override
const MooseArray< Number > & dofValuesDuDotDu () const override
const MooseArray< Number > & dofValuesDuDotDuNeighbor () const override
const MooseArray< Number > & dofValuesDuDotDotDu () const override
const MooseArray< Number > & dofValuesDuDotDotDuNeighbor () const override
const MooseArray< ADReal > & adDofValues () const override
Returns the AD dof values.
const MooseArray< ADReal > & adDofValuesNeighbor () const override
Returns the AD neighbor dof values.
OutputType getValue (const Elem *elem) const
Note: const monomial is always the case - higher order solns are reconstructed - so this is simpler func than FE equivalent.
OutputTools< OutputType >::OutputGradient getGradient (const Elem *elem) const
Compute the variable gradient value at a point on an element.
bool hasDirichletBC () const
Returns true if a Dirichlet BC exists on the current face.
std::pair< bool, const FVDirichletBCBase * > getDirichletBC (const FaceInfo &fi) const
std::pair< bool, std::vector< const FVFluxBC * > > getFluxBCs (const FaceInfo &fi) const
virtual void residualSetup () override
virtual void jacobianSetup () override
virtual void timestepSetup () override
virtual void meshChanged () override
Called on this object when the mesh changes.
ADReal getElemValue (const Elem *elem, const StateArg &state) const
Get the solution value for the provided element and seed the derivative for the corresponding dof index.
void setActiveTags (const std::set< TagID > &vtags) override
Set the active vector tags.
virtual void requireQpComputations () const
Request that quadrature point data be (pre)computed.
virtual bool isDirichletBoundaryFace (const FaceInfo &fi, const Elem *elem, const Moose::StateArg &state) const
Determine whether a specified face side is a Dirichlet boundary face.
const MooseArray< OutputType > & nodalValueArray () const override
Methods for retrieving values of variables at the nodes in a MooseArray for AuxKernelBase.
const MooseArray< OutputType > & nodalValueOldArray () const override
const MooseArray< OutputType > & nodalValueOlderArray () const override
bool computingSecond () const override final
Whether or not this variable is computing any second derivatives.
bool computingCurl () const override final
Whether or not this variable is computing any curl quantities.
bool computingDiv () const override final
Whether or not this variable is computing any divergence quantities.
bool usesSecondPhiNeighbor () const override final
Whether or not this variable is actually using the shape function second derivatives.
const FieldVariablePhiValue & phi () const override final
Return the variable's elemental shape functions.
const FieldVariablePhiGradient & gradPhi () const override final
Return the gradients of the variable's elemental shape functions.
const FieldVariablePhiSecond & secondPhi () const override final
Return the rank-2 tensor of second derivatives of the variable's elemental shape functions.
const FieldVariablePhiValue & curlPhi () const override final
Curl of the shape functions.
const FieldVariablePhiDivergence & divPhi () const override final
Divergence of the shape functions.
const FieldVariablePhiValue & phiFace () const override final
Return the variable's shape functions on an element face.
const FieldVariablePhiGradient & gradPhiFace () const override final
Return the gradients of the variable's shape functions on an element face.
const FieldVariablePhiSecond & secondPhiFace () const override final
Return the rank-2 tensor of second derivatives of the variable's shape functions on an element face.
const FieldVariablePhiValue & phiFaceNeighbor () const override final
Return the variable's shape functions on a neighboring element face.
const FieldVariablePhiGradient & gradPhiFaceNeighbor () const override final
Return the gradients of the variable's shape functions on a neighboring element face.
const FieldVariablePhiSecond & secondPhiFaceNeighbor () const override final
Return the rank-2 tensor of second derivatives of the variable's shape functions on a neighboring element face.
const FieldVariablePhiValue & phiNeighbor () const override final
Return the variable's shape functions on a neighboring element.
const FieldVariablePhiGradient & gradPhiNeighbor () const override final
Return the gradients of the variable's shape functions on a neighboring element.
const FieldVariablePhiSecond & secondPhiNeighbor () const override final
Return the rank-2 tensor of second derivatives of the variable's shape functions on a neighboring element.
virtual const FieldVariablePhiValue & phiLower () const override
Return the variable's shape functions on a lower-dimensional element.
unsigned int oldestSolutionStateRequested () const override final
The oldest solution state that is requested for this variable (0 = current, 1 = old, 2 = older, etc).
virtual ADReal getExtrapolatedBoundaryFaceValue (const FaceInfo &fi, bool two_term_expansion, bool correct_skewness, const Elem *elem_side_to_extrapolate_from, const StateArg &state) const
Retrieves an extrapolated boundary value for the provided face.
bool usesPhiNeighbor () const
Whether or not this variable is actually using the shape function value.
bool usesGradPhiNeighbor () const
Whether or not this variable is actually using the shape function gradient.
bool hasBlocks (const SubdomainName &name) const
Test if the supplied block name is valid for this object.
bool hasBlocks (const std::vector< SubdomainName > &names) const
Test if the supplied vector of block names are valid for this object.
bool hasBlocks (const std::vector< SubdomainID > &ids) const
Test if the supplied vector block ids are valid for this object.
bool hasBlocks (const std::set< SubdomainID > &ids) const
Test if the supplied set of block ids are valid for this object.
std::string componentName (const unsigned int comp) const
Get the variable name of a component in libMesh.
const std::set< SubdomainID > & activeSubdomains () const
The subdomains the variable is active on.
bool activeOnSubdomain (SubdomainID subdomain) const
Is the variable active on the subdomain?
bool activeOnSubdomains (const std::set< SubdomainID > &subdomains) const
Is the variable active on the subdomains?
unsigned int number () const
Get variable number coming from libMesh.
const FEType & feType () const
Get the type of finite element object.
SystemBase & sys ()
Get the system this variable is part of.
const SystemBase & sys () const
Get the system this variable is part of.
const std::string & name () const override
Get the variable name.
bool useDual () const
Get dual mortar option.
const std::vector< dof_id_type > & allDofIndices () const
Get all global dofindices for the variable.
unsigned int totalVarDofs ()
Moose::VarKindType kind () const
Kind of the variable (Nonlinear, Auxiliary, ...)
void scalingFactor (Real factor)
Set the scaling factor for this variable.
void scalingFactor (const std::vector< Real > &factor)
Real scalingFactor () const
Get the scaling factor for this variable.
const std::vector< Real > & arrayScalingFactor () const
Order order () const
Get the order of this variable Note: Order enum can be implicitly converted to unsigned int.
unsigned int count () const
Get the number of components Note: For standard and vector variables, the number is one.
const DofMap & dofMap () const
The DofMap associated with the system this variable is in.
std::vector< dof_id_type > componentDofIndices (const std::vector< dof_id_type > &dof_indices, unsigned int component) const
Obtain DoF indices of a component with the indices of the 0th component.
bool eigen () const
Whether or not this variable operates on an eigen kernel.
void eigen (bool eigen)
Mark this variable as an eigen var or non-eigen var.
void initialSetup () override
Gets called at the beginning of the simulation before this object is asked to do its job.
virtual bool enabled () const
Return the enabled status of the object.
MooseApp & getMooseApp () const
Get the MooseApp this class is associated with.
const std::string & type () const
Get the type of this class.
std::string typeAndName () const
Get the class's combined type and name; useful in error handling.
MooseObjectParameterName uniqueParameterName (const std::string &parameter_name) const
The unique parameter name of a valid parameter of this object for accessing parameter controls.
const InputParameters & parameters () const
Get the parameters of the object.
MooseObjectName uniqueName () const
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
template<typename T >
const T & getParam (const std::string &name) const
Retrieve a parameter for the object.
template<typename T1 , typename T2 >
std::vector< std::pair< T1, T2 > > getParam (const std::string &param1, const std::string &param2) const
Retrieve two parameters and provide pair of parameters for the object.
template<typename T >
const T & getRenamedParam (const std::string &old_name, const std::string &new_name) const
Retrieve a renamed parameter for the object.
template<typename T >
T getCheckedPointerParam (const std::string &name, const std::string &error_string="") const
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
bool isParamValid (const std::string &name) const
Test if the supplied parameter is valid.
bool isParamSetByUser (const std::string &nm) const
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
template<typename... Args>
void paramError (const std::string &param, Args... args) const
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramWarning (const std::string &param, Args... args) const
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
template<typename... Args>
void paramInfo (const std::string &param, Args... args) const
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
std::string objectErrorPrefix (const std::string &error_type) const
A descriptive prefix for errors for an object.
void connectControllableParams (const std::string &parameter, const std::string &object_type, const std::string &object_name, const std::string &object_parameter) const
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
template<typename... Args>
void mooseError (Args &&... args) const
Emits an error prefixed with object name and type.
template<typename... Args>
void mooseErrorNonPrefixed (Args &&... args) const
Emits an error without the prefixing included in mooseError().
template<typename... Args>
void mooseWarning (Args &&... args) const
Emits a warning prefixed with object name and type.
template<typename... Args>
void mooseWarningNonPrefixed (Args &&... args) const
Emits a warning without the prefixing included in mooseWarning().
template<typename... Args>
void mooseDeprecated (Args &&... args) const
template<typename... Args>
void mooseInfo (Args &&... args) const
std::string errorPrefix (const std::string &error_type) const
A descriptive prefix for errors for this object:
std::string getDataFileName (const std::string &param) const
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
std::string getDataFileNameByName (const std::string &name, const std::string *param=nullptr) const
Returns the path of a data file for a given relative file path.
const std::vector< SubdomainName > & blocks () const
Return the block names for this object.
unsigned int numBlocks () const
Return the number of blocks for this object.
virtual const std::set< SubdomainID > & blockIDs () const
Return the block subdomain ids for this object Note, if this is not block restricted, this function returns all mesh subdomain ids.
unsigned int blocksMaxDimension () const
Return the largest mesh dimension of the elements in the blocks for this object.
bool isBlockSubset (const std::set< SubdomainID > &ids) const
Test if the class block ids are a subset of the supplied objects.
bool isBlockSubset (const std::vector< SubdomainID > &ids) const
Test if the class block ids are a subset of the supplied objects.
template<typename T , bool is_ad = false>
bool hasBlockMaterialProperty (const std::string &prop_name)
Check if a material property is valid for all blocks of this object.
const std::set< SubdomainID > & meshBlockIDs () const
Return all of the SubdomainIDs for the mesh.
virtual bool blockRestricted () const
Returns true if this object has been restricted to a block.
virtual void checkVariable (const MooseVariableFieldBase &variable) const
Helper for checking that the ids for this object are in agreement with the variables on the supplied variable.
void buildOutputHideVariableList (std::set< std::string > variable_names)
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
const std::set< OutputName > & getOutputs ()
Get the list of output objects that this class is restricted.
virtual void subdomainSetup ()
Gets called when the subdomain changes (i.e.
virtual void customSetup (const ExecFlagType &)
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
virtual void customSetup (const ExecFlagType &exec_type) override
const ExecFlagEnum & getExecuteOnEnum () const
Return the execute on MultiMooseEnum for this object.
const MooseFunctorName & functorName () const
Return the functor name.
void setCacheClearanceSchedule (const std::set< ExecFlagType > &clearance_schedule)
Set how often to clear the functor evaluation cache.
bool isInternalFace (const FaceInfo &) const
Returns true if the face is an internal face.
virtual bool isConstant () const
Returns true if this functor is a constant.
virtual bool hasFaceSide (const FaceInfo &fi, const bool fi_elem_side) const override
Moose::FaceArg checkFace (const Moose::FaceArg &face) const
Examines the incoming face argument.
ValueType operator() (const ElemArg &elem, const StateArg &state) const
Same as their evaluate overloads with the same arguments but allows for caching implementation.
ValueType operator() (const FaceArg &face, const StateArg &state) const
ValueType operator() (const ElemQpArg &qp, const StateArg &state) const
ValueType operator() (const ElemSideQpArg &qp, const StateArg &state) const
ValueType operator() (const ElemPointArg &elem_point, const StateArg &state) const
ValueType operator() (const NodeArg &node, const StateArg &state) const
GradientType gradient (const ElemArg &elem, const StateArg &state) const
Same as their evaluateGradient overloads with the same arguments but allows for caching implementation.
GradientType gradient (const FaceArg &face, const StateArg &state) const
GradientType gradient (const ElemQpArg &qp, const StateArg &state) const
GradientType gradient (const ElemSideQpArg &qp, const StateArg &state) const
GradientType gradient (const ElemPointArg &elem_point, const StateArg &state) const
GradientType gradient (const NodeArg &node, const StateArg &state) const
DotType dot (const ElemArg &elem, const StateArg &state) const
Same as their evaluateDot overloads with the same arguments but allows for caching implementation.
DotType dot (const FaceArg &face, const StateArg &state) const
DotType dot (const ElemQpArg &qp, const StateArg &state) const
DotType dot (const ElemSideQpArg &qp, const StateArg &state) const
DotType dot (const ElemPointArg &elem_point, const StateArg &state) const
DotType dot (const NodeArg &node, const StateArg &state) const
GradientType gradDot (const ElemArg &elem, const StateArg &state) const
Same as their evaluateGradDot overloads with the same arguments but allows for caching implementation.
GradientType gradDot (const FaceArg &face, const StateArg &state) const
GradientType gradDot (const ElemQpArg &qp, const StateArg &state) const
GradientType gradDot (const ElemSideQpArg &qp, const StateArg &state) const
GradientType gradDot (const ElemPointArg &elem_point, const StateArg &state) const
GradientType gradDot (const NodeArg &node, const StateArg &state) const
Static Public Member Functions
static InputParameters validParams ()
Public Attributes
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Member Functions
virtual ADReal getDirichletBoundaryFaceValue (const FaceInfo &fi, const Elem *elem, const Moose::StateArg &state) const
Retrieves a Dirichlet boundary value for the provided face.
bool isExtrapolatedBoundaryFace (const FaceInfo &fi, const Elem *elem, const Moose::StateArg &state) const override
Returns whether this is an extrapolated boundary face.
void clearCaches ()
clear finite volume caches
bool doDerivatives () const
virtual bool hasBlockMaterialPropertyHelper (const std::string &prop_name)
A helper method to allow the Material object to specialize the behavior of hasBlockMaterialProperty.
void initializeBlockRestrictable (const MooseObject *moose_object)
An initialization routine needed for dual constructors.
Moose::CoordinateSystemType getBlockCoordSystem ()
Check if the blocks this object operates on all have the same coordinate system, and if so return it.
Functor evaluation routines
These methods are all for evaluating functors with different kinds of spatial arguments.
Each of these methods also takes a state argument. For a description of the state argument, please see the StateArg doxygen
virtual GradientType evaluateGradient (const ElemSideQpArg &, const StateArg &) const
virtual GradientType evaluateGradient (const ElemPointArg &, const StateArg &) const
Evaluate the functor gradient with a given element and point.
virtual GradientType evaluateGradient (const NodeArg &, const StateArg &) const
virtual DotType evaluateDot (const FaceArg &, const StateArg &) const
virtual DotType evaluateDot (const ElemQpArg &, const StateArg &) const
virtual DotType evaluateDot (const ElemSideQpArg &, const StateArg &) const
virtual DotType evaluateDot (const ElemPointArg &, const StateArg &) const
Evaluate the functor time derivative with a given element and point.
virtual DotType evaluateDot (const NodeArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemArg &, const StateArg &) const
Evaluate the functor gradient-dot with a given element.
virtual GradientType evaluateGradDot (const FaceArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemQpArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemSideQpArg &, const StateArg &) const
virtual GradientType evaluateGradDot (const ElemPointArg &, const StateArg &) const
Evaluate the functor gradient-dot with a given element and point.
virtual GradientType evaluateGradDot (const NodeArg &, const StateArg &) const
Protected Attributes
usingMooseVariableFieldMembers
std::unique_ptr< MooseVariableDataFV< OutputType > > _element_data
Holder for all the data associated with the "main" element.
std::unique_ptr< MooseVariableDataFV< OutputType > > _neighbor_data
Holder for all the data associated with the neighbor element.
std::unordered_map< const Elem *, VectorValue< ADReal > > _elem_to_grad
A cache for storing gradients on elements.
bool _two_term_boundary_expansion
Whether to use a two term expansion for computing boundary face values.
VectorValue< ADReal > _temp_cell_gradient
A member to hold the cell gradient when not caching, used to return a reference (due to expensive ADReal copy)
const bool _cache_cell_gradients
Whether to cache cell gradients.
Moose::FV::InterpMethod _face_interp_method
Decides if an average or skewed corrected average is used for the face interpolation.
SystemBase & _sys
System this variable is part of.
FEType _fe_type
The FEType associated with this variable.
unsigned int _var_num
variable number (from libMesh)
unsigned int _index
variable number within MOOSE
bool _is_eigen
Whether or not this variable operates on eigen kernels.
Moose::VarKindType _var_kind
Variable type (see MooseTypes.h)
SubProblem & _subproblem
Problem this variable is part of.
const Variable & _variable
libMesh variable object for this variable
Assembly & _assembly
Assembly data.
const DofMap & _dof_map
DOF map.
std::vector< dof_id_type > _dof_indices
DOF indices.
MooseMesh & _mesh
mesh the variable is active in
THREAD_ID _tid
Thread ID.
const unsigned int _count
Number of variables in the array.
std::vector< Real > _scaling_factor
scaling factor for this variable
std::string _var_name
Variable name.
bool _use_dual
If dual mortar approach is used.
const bool _is_array
Whether this is an array variable.
const bool & _enabled
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
MooseApp & _app
The MOOSE application this is associated with.
const std::string & _type
The type of this class.
const std::string & _name
The name of this class, reference to value stored in InputParameters.
const InputParameters & _pars
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Factory & _factory
The Factory associated with the MooseApp.
ActionFactory & _action_factory
Builds Actions.
const MaterialData * _blk_material_data
Pointer to the MaterialData class for this object.
const ExecFlagEnum & _execute_enum
Execute settings for this object.
const ExecFlagType & _current_execute_flag
Reference to FEProblemBase.
FEProblemBase & _mci_feproblem
Reference to FEProblemBase instance.
Private Member Functions
ValueType evaluate (const ElemArg &elem, const StateArg &) const override final
Evaluate the functor with a given element.
ValueType evaluate (const FaceArg &face, const StateArg &) const override final
ValueType evaluate (const NodeArg &node, const StateArg &) const override final
ValueType evaluate (const ElemPointArg &elem_point, const StateArg &state) const override final
Evaluate the functor with a given element and point.
ValueType evaluate (const ElemQpArg &elem_qp, const StateArg &state) const override final
ValueType evaluate (const ElemSideQpArg &elem_side_qp, const StateArg &state) const override final
GradientType evaluateGradient (const ElemQpArg &qp_arg, const StateArg &) const override final
GradientType evaluateGradient (const ElemArg &elem_arg, const StateArg &) const override final
Evaluate the functor gradient with a given element.
GradientType evaluateGradient (const FaceArg &face, const StateArg &) const override final
DotType evaluateDot (const ElemArg &elem, const StateArg &) const override final
Evaluate the functor time derivative with a given element.
void determineBoundaryToDirichletBCMap ()
Setup the boundary to Dirichlet BC map.
template<typename... Args>
std::string paramErrorMsg (const std::string &param, Args... args) const
void clearCacheData ()
clear cache data
ValueType queryQpCache (unsigned int qp, const QBase &qrule, std::vector< std::pair< bool, Moose::ADType< OutputType >::type > > &qp_cache_data, const SpaceArg &space, const StateArg &state) const
check a qp cache and if invalid then evaluate
ValueType queryFVArgCache (std::map< SpaceArg, ValueType > &cache_data, const SpaceArg &space) const
check a finite volume spatial argument cache and if invalid then evaluate
Private Attributes
bool _dirichlet_map_setup = false
Whether the boundary to Dirichlet cache map has been setup yet.
const NumericVector< Number > *const & _solution
The current (ghosted) solution.
const FieldVariablePhiValue & _phi
Shape functions.
const FieldVariablePhiGradient & _grad_phi
const FieldVariablePhiValue & _phi_face
const FieldVariablePhiGradient & _grad_phi_face
const FieldVariablePhiValue & _phi_face_neighbor
const FieldVariablePhiGradient & _grad_phi_face_neighbor
const FieldVariablePhiValue & _phi_neighbor
const FieldVariablePhiGradient & _grad_phi_neighbor
const Elem * _prev_elem
A member used to help determine when we can return cached data as opposed to computing new data.
std::unordered_map< BoundaryID, const FVDirichletBCBase * > _boundary_id_to_dirichlet_bc
Map from boundary ID to Dirichlet boundary conditions.
const MooseBase *const _moose_base
The MooseBase object that inherits this class.
const MooseObject & _parent
std::set< SubdomainID > _blk_ids
Set of block ids supplied by the user via the input file (for error checking)
std::vector< SubdomainID > _vec_ids
Vector of block ids supplied by the user via the input file (for error reporting)
std::vector< SubdomainName > _blocks
Vector the block names supplied by the user via the input file.
const bool _blk_dual_restrictable
Flag for allowing dual restriction.
FEProblemBase * _blk_feproblem
Pointer to FEProblemBase.
MooseMesh * _blk_mesh
Pointer to Mesh.
const std::set< BoundaryID > _empty_boundary_ids
An empty set for referencing when boundary_ids is not included.
const std::set< BoundaryID > & _boundary_ids
Reference to the boundary_ids, defaults to an empty set if not provided.
THREAD_ID _blk_tid
Thread id for this object.
const std::string & _blk_name
Name of the object.
unsigned int _blk_dim
Largest mesh dimension of the elements in the blocks for this object.
MooseApp & _oi_moose_app
Reference the the MooseApp; neede for access to the OutputWarehouse.
OutputWarehouse & _oi_output_warehouse
Reference to the OutputWarehouse for populating the Output object hide lists.
std::set< OutputName > _oi_outputs
The set of Output object names listed in the 'outputs' parameter.
ExecFlagEnum _empty_execute_enum
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
std::set< ExecFlagType > _clearance_schedule
How often to clear the material property cache.
dof_id_type _current_qp_map_key
Current key for qp map cache.
std::vector< std::pair< bool, ValueType > > * _current_qp_map_value
Current value for qp map cache.
std::unordered_map< dof_id_type, std::vector< std::pair< bool, ValueType > > > _qp_to_value
Cached element quadrature point functor property evaluations.
dof_id_type _current_side_qp_map_key
Current key for side-qp map cache.
std::vector< std::vector< std::pair< bool, ValueType > > > * _current_side_qp_map_value
Current value for side-qp map cache.
std::unordered_map< dof_id_type, std::vector< std::vector< std::pair< bool, ValueType > > > > _side_qp_to_value
Cached element quadrature point functor property evaluations.
std::map< ElemArg, ValueType > _elem_arg_to_value
Map from element arguments to their cached evaluations.
std::map< FaceArg, ValueType > _face_arg_to_value
Map from face arguments to their cached evaluations.
std::map< NodeArg, ValueType > _node_arg_to_value
Map from nodal arguments to their cached evaluations.
MooseFunctorName _functor_name
name of the functor
Friends
void Moose::initDofIndices (MooseVariableFV< OutputType > &, const Elem &)
const TimeIntegrator *const _time_integrator
the time integrator used for computing time derivatives
ADReal _ad_real_dummy = 0
A dummy ADReal variable.
bool hasBlocks (const SubdomainID id) const override
Returns whether the functor is defined on this block.
const NumericVector< Number > & getSolution (const Moose::StateArg &state) const
Get the solution corresponding to the provided state.
Detailed Description
template<typename OutputType>
class MooseVariableFV< OutputType >
This class provides variable solution values for other classes/objects to bind to when looping over faces or elements.
It provides both elem and neighbor values when accessed in flux/face object calculations. The templating is to enable support for both vector and scalar variables. Gradient reconstruction (when enabled) occurs transparently within this class and kernels coupling to these values will naturally "see" according to the selected reconstruction methods.
OutputType OutputShape OutputData
Real Real Real RealVectorValue RealVectorValue Real RealEigenVector Real RealEigenVector
Definition at line 52 of file MooseVariableFV.h.
Member Typedef Documentation
DoFValue
template<typename OutputType > using MooseVariableFV< OutputType >::DoFValue = typename MooseVariableField<OutputType>::DoFValue
Definition at line 71 of file MooseVariableFV.h.
DotType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::DotType = ValueType inherited
Definition at line 67 of file MooseFunctor.h.
ElemArg
template<typename OutputType > using MooseVariableFV< OutputType >::ElemArg = Moose::ElemArg
Definition at line 81 of file MooseVariableFV.h.
ElemPointArg
template<typename OutputType > using MooseVariableFV< OutputType >::ElemPointArg = Moose::ElemPointArg
Definition at line 85 of file MooseVariableFV.h.
ElemQpArg
template<typename OutputType > using MooseVariableFV< OutputType >::ElemQpArg = Moose::ElemQpArg
Definition at line 79 of file MooseVariableFV.h.
ElemSideQpArg
template<typename OutputType > using MooseVariableFV< OutputType >::ElemSideQpArg = Moose::ElemSideQpArg
Definition at line 80 of file MooseVariableFV.h.
FaceArg
template<typename OutputType > using MooseVariableFV< OutputType >::FaceArg = Moose::FaceArg
Definition at line 82 of file MooseVariableFV.h.
FieldVariableCurl
template<typename OutputType > using MooseVariableFV< OutputType >::FieldVariableCurl = typename MooseVariableField<OutputType>::FieldVariableCurl
Definition at line 62 of file MooseVariableFV.h.
FieldVariableDivergence
template<typename OutputType > using MooseVariableFV< OutputType >::FieldVariableDivergence = typename MooseVariableField<OutputType>::FieldVariableDivergence
Definition at line 63 of file MooseVariableFV.h.
FieldVariableGradient
template<typename OutputType > using MooseVariableFV< OutputType >::FieldVariableGradient = typename MooseVariableField<OutputType>::FieldVariableGradient
Definition at line 60 of file MooseVariableFV.h.
FieldVariablePhiCurl
template<typename OutputType > typedef MooseArray<std::vector<OutputShape> > MooseVariableField< OutputType >::FieldVariablePhiCurl inherited
Definition at line 69 of file MooseVariableField.h.
FieldVariablePhiDivergence
template<typename OutputType > using MooseVariableFV< OutputType >::FieldVariablePhiDivergence = typename MooseVariableField<OutputType>::FieldVariablePhiDivergence
Definition at line 74 of file MooseVariableFV.h.
FieldVariablePhiGradient
template<typename OutputType > using MooseVariableFV< OutputType >::FieldVariablePhiGradient = typename MooseVariableField<OutputType>::FieldVariablePhiGradient
Definition at line 76 of file MooseVariableFV.h.
FieldVariablePhiSecond
template<typename OutputType > using MooseVariableFV< OutputType >::FieldVariablePhiSecond = typename MooseVariableField<OutputType>::FieldVariablePhiSecond
Definition at line 78 of file MooseVariableFV.h.
FieldVariablePhiValue
template<typename OutputType > using MooseVariableFV< OutputType >::FieldVariablePhiValue = typename MooseVariableField<OutputType>::FieldVariablePhiValue
Definition at line 73 of file MooseVariableFV.h.
FieldVariableSecond
template<typename OutputType > using MooseVariableFV< OutputType >::FieldVariableSecond = typename MooseVariableField<OutputType>::FieldVariableSecond
Definition at line 61 of file MooseVariableFV.h.
FieldVariableTestCurl
template<typename OutputType > typedef MooseArray<std::vector<OutputShape> > MooseVariableField< OutputType >::FieldVariableTestCurl inherited
Definition at line 77 of file MooseVariableField.h.
FieldVariableTestDivergence
template<typename OutputType > typedef MooseArray<std::vector<OutputShapeDivergence> > MooseVariableField< OutputType >::FieldVariableTestDivergence inherited
Definition at line 78 of file MooseVariableField.h.
FieldVariableTestGradient
template<typename OutputType > typedef MooseArray<std::vector<OutputShapeGradient> > MooseVariableField< OutputType >::FieldVariableTestGradient inherited
Definition at line 75 of file MooseVariableField.h.
FieldVariableTestSecond
template<typename OutputType > typedef MooseArray<std::vector<OutputShapeSecond> > MooseVariableField< OutputType >::FieldVariableTestSecond inherited
Definition at line 76 of file MooseVariableField.h.
FieldVariableTestValue
template<typename OutputType > typedef MooseArray<std::vector<OutputShape> > MooseVariableField< OutputType >::FieldVariableTestValue inherited
Definition at line 74 of file MooseVariableField.h.
FieldVariableValue
template<typename OutputType > using MooseVariableFV< OutputType >::FieldVariableValue = typename MooseVariableField<OutputType>::FieldVariableValue
Definition at line 59 of file MooseVariableFV.h.
FunctorReturnType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::FunctorReturnType = Moose::ADType< OutputType >::type inherited
Definition at line 55 of file MooseFunctor.h.
FunctorType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::FunctorType = FunctorBase<Moose::ADType< OutputType >::type > inherited
Definition at line 54 of file MooseFunctor.h.
GradientType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::GradientType = typename MetaPhysicL::ReplaceAlgebraicType< Moose::ADType< OutputType >::type , typename TensorTools::IncrementRank<typename MetaPhysicL::ValueType<Moose::ADType< OutputType >::type >::type>::type>::type inherited
This rigmarole makes it so that a user can create functors that return containers (std::vector, std::array).
This logic will make it such that if a user requests a functor type T that is a container of algebraic types, for example Reals, then the GradientType will be a container of the gradients of those algebraic types, in this example VectorValue<Reals>. So if T is std::vector<Real>, then GradientType will be std::vector<VectorValue<Real>>. As another example: T = std::array<VectorValue<Real>, 1> -> GradientType = std::array<TensorValue<Real>, 1>
Definition at line 64 of file MooseFunctor.h.
NodeArg
template<typename OutputType > using MooseVariableFV< OutputType >::NodeArg = Moose::NodeArg
Definition at line 84 of file MooseVariableFV.h.
OutputData
template<typename OutputType > using MooseVariableFV< OutputType >::OutputData = typename MooseVariableField<OutputType>::OutputData
Definition at line 70 of file MooseVariableFV.h.
OutputDivergence
template<typename OutputType > using MooseVariableFV< OutputType >::OutputDivergence = typename MooseVariableField<OutputType>::OutputDivergence
Definition at line 57 of file MooseVariableFV.h.
OutputGradient
template<typename OutputType > using MooseVariableFV< OutputType >::OutputGradient = typename MooseVariableField<OutputType>::OutputGradient
Definition at line 55 of file MooseVariableFV.h.
OutputSecond
template<typename OutputType > using MooseVariableFV< OutputType >::OutputSecond = typename MooseVariableField<OutputType>::OutputSecond
Definition at line 56 of file MooseVariableFV.h.
OutputShape
template<typename OutputType > using MooseVariableFV< OutputType >::OutputShape = typename MooseVariableField<OutputType>::OutputShape
Definition at line 65 of file MooseVariableFV.h.
OutputShapeDivergence
template<typename OutputType > using MooseVariableFV< OutputType >::OutputShapeDivergence = typename MooseVariableField<OutputType>::OutputShapeDivergence
Definition at line 68 of file MooseVariableFV.h.
OutputShapeGradient
template<typename OutputType > using MooseVariableFV< OutputType >::OutputShapeGradient = typename MooseVariableField<OutputType>::OutputShapeGradient
Definition at line 66 of file MooseVariableFV.h.
OutputShapeSecond
template<typename OutputType > using MooseVariableFV< OutputType >::OutputShapeSecond = typename MooseVariableField<OutputType>::OutputShapeSecond
Definition at line 67 of file MooseVariableFV.h.
StateArg
template<typename OutputType > using MooseVariableFV< OutputType >::StateArg = Moose::StateArg
Definition at line 83 of file MooseVariableFV.h.
ValueType
using Moose::FunctorBase< Moose::ADType< OutputType >::type >::ValueType = Moose::ADType< OutputType >::type inherited
Definition at line 56 of file MooseFunctor.h.
Constructor & Destructor Documentation
MooseVariableFV()
template<typename OutputType > MooseVariableFV< OutputType >::MooseVariableFV (const InputParameters & parameters)
Definition at line 63 of file MooseVariableFV.C.
  : MooseVariableField<OutputType>(parameters),
    _solution(this->_sys.currentSolution()),
    _phi(this->_assembly.template fePhi<OutputShape>(FEType(CONSTANT, MONOMIAL))),
    _grad_phi(this->_assembly.template feGradPhi<OutputShape>(FEType(CONSTANT, MONOMIAL))),
    _phi_face(this->_assembly.template fePhiFace<OutputShape>(FEType(CONSTANT, MONOMIAL))),
    _grad_phi_face(this->_assembly.template feGradPhiFace<OutputShape>(FEType(CONSTANT, MONOMIAL))),
    _phi_face_neighbor(
        this->_assembly.template fePhiFaceNeighbor<OutputShape>(FEType(CONSTANT, MONOMIAL))),
    _grad_phi_face_neighbor(
        this->_assembly.template feGradPhiFaceNeighbor<OutputShape>(FEType(CONSTANT, MONOMIAL))),
    _phi_neighbor(this->_assembly.template fePhiNeighbor<OutputShape>(FEType(CONSTANT, MONOMIAL))),
    _grad_phi_neighbor(
        this->_assembly.template feGradPhiNeighbor<OutputShape>(FEType(CONSTANT, MONOMIAL))),
    _prev_elem(nullptr),
    _two_term_boundary_expansion(this->isParamValid("two_term_boundary_expansion")
                                     ? this->template getParam<bool>("two_term_boundary_expansion")
                                     : true),
    _cache_cell_gradients(this->isParamValid("cache_cell_gradients")
                              ? this->template getParam<bool>("cache_cell_gradients")
                              : true)
{
  _element_data = std::make_unique<MooseVariableDataFV<OutputType>>(
      *this, _sys, _tid, Moose::ElementType::Element, this->_assembly.elem());
  _neighbor_data = std::make_unique<MooseVariableDataFV<OutputType>>(
      *this, _sys, _tid, Moose::ElementType::Neighbor, this->_assembly.neighbor());
  if (this->isParamValid("face_interp_method"))
  {
    const auto & interp_method = this->template getParam<MooseEnum>("face_interp_method");
    if (interp_method == "average")
      _face_interp_method = Moose::FV::InterpMethod::Average;
    else if (interp_method == "skewness-corrected")
      _face_interp_method = Moose::FV::InterpMethod::SkewCorrectedAverage;
  }
  else
    _face_interp_method = Moose::FV::InterpMethod::Average;
}
Member Function Documentation
activeOnSubdomain()
bool MooseVariableFieldBase::activeOnSubdomain (SubdomainID subdomain) const inherited
Is the variable active on the subdomain?
Parameters
subdomain The subdomain id in question
Returns
true if active on subdomain, false otherwise
Definition at line 45 of file MooseVariableFieldBase.C.
{
  return this->_sys.system().variable(_var_num).active_on_subdomain(subdomain);
}
Referenced by ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), ComputeFullJacobianThread::computeOnInternalFace(), ComputeDiracThread::onElement(), and FlagElementsThread::onElement().
activeOnSubdomains()
bool MooseVariableFieldBase::activeOnSubdomains (const std::set< SubdomainID > & subdomains) const inherited
Is the variable active on the subdomains?
Parameters
subdomains The subdomain ids in question
Returns
true if active on all provided subdomains, false otherwise
Definition at line 51 of file MooseVariableFieldBase.C.
{
  const auto & active_subs = activeSubdomains();
  return std::includes(
      active_subs.begin(), active_subs.end(), subdomains.begin(), subdomains.end());
}
activeSubdomains()
const std::set< SubdomainID > & MooseVariableFieldBase::activeSubdomains () const inherited
The subdomains the variable is active on.
Definition at line 39 of file MooseVariableFieldBase.C.
{
  return this->_sys.system().variable(_var_num).active_subdomains();
}
Referenced by SetupResidualDebugAction::act(), MooseVariableFieldBase::activeOnSubdomains(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), BlockRestrictable::checkVariable(), DGLowerDKernel::DGLowerDKernel(), HFEMDirichletBC::HFEMDirichletBC(), and LowerDIntegratedBC::LowerDIntegratedBC().
add()
template<typename OutputType > void MooseVariableFV< OutputType >::add (NumericVector< Number > & residual) override virtual
Implements MooseVariableFieldBase.
Definition at line 153 of file MooseVariableFV.C.
{
  _element_data->add(residual);
}
adDofValues()
template<typename OutputType > const MooseArray< ADReal > & MooseVariableFV< OutputType >::adDofValues inline override virtual
Returns the AD dof values.
Implements MooseVariableField< OutputType >.
Definition at line 711 of file MooseVariableFV.h.
{
  return _element_data->adDofValues();
}
adDofValuesNeighbor()
template<typename OutputType > const MooseArray< ADReal > & MooseVariableFV< OutputType >::adDofValuesNeighbor inline override virtual
Returns the AD neighbor dof values.
Implements MooseVariableField< OutputType >.
Definition at line 718 of file MooseVariableFV.h.
{
  return _neighbor_data->adDofValues();
}
adGradSln() [1/3]
template<typename OutputType > const ADTemplateVariableGradient< OutputType > & MooseVariableFV< OutputType >::adGradSln () const inline override virtual
AD grad solution getter.
Implements MooseVariableField< OutputType >.
Definition at line 263 of file MooseVariableFV.h.
  {
    return _element_data->adGradSln();
  }
Referenced by LayeredSideDiffusiveFluxAverage::computeQpIntegral(), FVOneVarDiffusionInterface::computeQpResidual(), FVAnisotropicDiffusion::computeQpResidual(), MooseVariableFV< OutputType >::evaluateGradient(), and Moose::FV::gradUDotNormal().
adGradSln() [2/3]
template<typename OutputType > const VectorValue< ADReal > & MooseVariableFV< OutputType >::adGradSln (const Elem *const elem, const StateArg & state, const bool correct_skewness = false) const virtual
Retrieve (or potentially compute) the gradient on the provided element.
Overriders of this method cannot call getBoundaryFaceValue because that method itself may lead to a call to adGradSln(const Elem * const) resulting in infinite recursion
Parameters
elem The element for which to retrieve the gradient
state State argument which describes at what time / solution iteration state we want to evaluate the variable
correct_skewness Whether to perform skew corrections
Returns
The gradient at the element centroid
Definition at line 608 of file MooseVariableFV.C.
{
  // We ensure that no caching takes place when we compute skewness-corrected
  // quantities.
  if (_cache_cell_gradients && !correct_skewness && state.state == 0)
  {
    auto it = _elem_to_grad.find(elem);
    if (it != _elem_to_grad.end())
      return it->second;
  }
  auto grad = FV::greenGaussGradient(
      ElemArg({elem, correct_skewness}), state, *this, _two_term_boundary_expansion, this->_mesh);
  if (_cache_cell_gradients && !correct_skewness && state.state == 0)
  {
    auto pr = _elem_to_grad.emplace(elem, std::move(grad));
    mooseAssert(pr.second, "Insertion should have just happened.");
    return pr.first->second;
  }
  else
  {
    _temp_cell_gradient = std::move(grad);
    return _temp_cell_gradient;
  }
}
adGradSln() [3/3]
template<typename OutputType > VectorValue< ADReal > MooseVariableFV< OutputType >::adGradSln (const FaceInfo & fi, const StateArg & state, const bool correct_skewness = false) const virtual
Retrieve (or potentially compute) a cross-diffusion-corrected gradient on the provided face.
"Correcting" the face gradient involves weighting the gradient stencil more heavily on the solution values on the face-neighbor cells than a linear interpolation between cell center gradients does
Parameters
face The face for which to retrieve the gradient.
state State argument which describes at what time / solution iteration state we want to evaluate the variable
correct_skewness Whether to perform skew corrections
Definition at line 666 of file MooseVariableFV.C.
{
  const bool var_defined_on_elem = this->hasBlocks(fi.elem().subdomain_id());
  const Elem * const elem = &fi.elem();
  const Elem * const neighbor = fi.neighborPtr();
  const bool is_internal_face = this->isInternalFace(fi);
  const ADReal side_one_value = (!is_internal_face && !var_defined_on_elem)
                                    ? getBoundaryFaceValue(fi, state, correct_skewness)
                                    : getElemValue(elem, state);
  const ADReal side_two_value = (var_defined_on_elem && !is_internal_face)
                                    ? getBoundaryFaceValue(fi, state, correct_skewness)
                                    : getElemValue(neighbor, state);
  const auto delta =
      this->isInternalFace(fi)
          ? fi.dCNMag()
          : (fi.faceCentroid() - (var_defined_on_elem ? fi.elemCentroid() : fi.neighborCentroid()))
                .norm();
  // This is the component of the gradient which is parallel to the line connecting
  // the cell centers. Therefore, we can use our second order, central difference
  // scheme to approximate it.
  auto face_grad = ((side_two_value - side_one_value) / delta) * fi.eCN();
  // We only need non-orthogonal correctors in 2+ dimensions
  if (this->_mesh.dimension() > 1)
  {
    // We are using an orthogonal approach for the non-orthogonal correction, for more information
    // see Hrvoje Jasak's PhD Thesis (Imperial College, 1996)
    const auto & interpolated_gradient = uncorrectedAdGradSln(fi, state, correct_skewness);
    face_grad += interpolated_gradient - (interpolated_gradient * fi.eCN()) * fi.eCN();
  }
  return face_grad;
}
adGradSlnDot()
template<typename OutputType > const ADTemplateVariableGradient< OutputType > & MooseVariableFV< OutputType >::adGradSlnDot () const inline override virtual
AD grad of time derivative solution getter.
Implements MooseVariableField< OutputType >.
Definition at line 333 of file MooseVariableFV.h.
  {
    return _element_data->adGradSlnDot();
  }
adGradSlnNeighbor()
template<typename OutputType > const ADTemplateVariableGradient< OutputType > & MooseVariableFV< OutputType >::adGradSlnNeighbor () const inline override virtual
AD grad neighbor solution getter.
Implements MooseVariableField< OutputType >.
Definition at line 343 of file MooseVariableFV.h.
  {
    return _neighbor_data->adGradSln();
  }
adGradSlnNeighborDot()
template<typename OutputType > const ADTemplateVariableGradient< OutputType > & MooseVariableFV< OutputType >::adGradSlnNeighborDot () const inline override virtual
AD grad of time derivative neighbor solution getter.
Implements MooseVariableField< OutputType >.
Definition at line 359 of file MooseVariableFV.h.
  {
    return _neighbor_data->adGradSlnDot();
  }
adSecondSln()
template<typename OutputType > const ADTemplateVariableSecond< OutputType > & MooseVariableFV< OutputType >::adSecondSln () const inline override virtual
AD second solution getter.
Implements MooseVariableField< OutputType >.
Definition at line 321 of file MooseVariableFV.h.
  {
    return _element_data->adSecondSln();
  }
adSecondSlnNeighbor()
template<typename OutputType > const ADTemplateVariableSecond< OutputType > & MooseVariableFV< OutputType >::adSecondSlnNeighbor () const inline override virtual
AD second neighbor solution getter.
Implements MooseVariableField< OutputType >.
Definition at line 347 of file MooseVariableFV.h.
  {
    return _neighbor_data->adSecondSln();
  }
adSln()
template<typename OutputType > const ADTemplateVariableValue< OutputType > & MooseVariableFV< OutputType >::adSln () const inline override virtual
AD.
Implements MooseVariableField< OutputType >.
Definition at line 259 of file MooseVariableFV.h.
  {
    return _element_data->adSln();
  }
adSlnNeighbor()
template<typename OutputType > const ADTemplateVariableValue< OutputType > & MooseVariableFV< OutputType >::adSlnNeighbor () const inline override virtual
neighbor AD
Implements MooseVariableField< OutputType >.
Definition at line 339 of file MooseVariableFV.h.
  {
    return _neighbor_data->adSln();
  }
adUDot()
template<typename OutputType > const ADTemplateVariableValue< OutputType > & MooseVariableFV< OutputType >::adUDot () const inline override virtual
AD time derivative getter.
Implements MooseVariableField< OutputType >.
Definition at line 325 of file MooseVariableFV.h.
  {
    return _element_data->adUDot();
  }
adUDotDot()
template<typename OutputType > const ADTemplateVariableValue< OutputType > & MooseVariableFV< OutputType >::adUDotDot () const inline override virtual
AD second time derivative getter.
Implements MooseVariableField< OutputType >.
Definition at line 329 of file MooseVariableFV.h.
  {
    return _element_data->adUDotDot();
  }
adUDotDotNeighbor()
template<typename OutputType > const ADTemplateVariableValue< OutputType > & MooseVariableFV< OutputType >::adUDotDotNeighbor () const inline override virtual
AD neighbor second time derivative getter.
Implements MooseVariableField< OutputType >.
Definition at line 355 of file MooseVariableFV.h.
  {
    return _neighbor_data->adUDotDot();
  }
adUDotNeighbor()
template<typename OutputType > const ADTemplateVariableValue< OutputType > & MooseVariableFV< OutputType >::adUDotNeighbor () const inline override virtual
AD neighbor time derivative getter.
Implements MooseVariableField< OutputType >.
Definition at line 351 of file MooseVariableFV.h.
  {
    return _neighbor_data->adUDot();
  }
allDofIndices()
const std::vector< dof_id_type > & MooseVariableBase::allDofIndices () const inherited
Get all global dofindices for the variable.
Definition at line 137 of file MooseVariableBase.C.
{
  const auto it = _sys.subproblem()._var_dof_map.find(name());
  if (it != _sys.subproblem()._var_dof_map.end())
    return it->second;
  else
    mooseError("VariableAllDoFMap not prepared for ",
               name(),
               " . Check nonlocal coupling requirement for the variable.");
}
Referenced by FEProblemBase::addJacobianBlockTags(), NonlocalIntegratedBC::computeNonlocalJacobian(), NonlocalKernel::computeNonlocalJacobian(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), FEProblemBase::prepare(), Assembly::prepareNonlocal(), Assembly::prepareVariableNonlocal(), and MooseVariableBase::totalVarDofs().
arrayScalingFactor()
const std::vector< Real > & MooseVariableBase::arrayScalingFactor () const inline inherited
Definition at line 97 of file MooseVariableBase.h.
{ return _scaling_factor; }
Referenced by Assembly::addJacobianBlock(), Assembly::addJacobianBlockNonlocal(), Assembly::addJacobianNeighbor(), Assembly::cacheJacobianBlock(), and Assembly::cacheJacobianBlockNonzero().
blockIDs()
const std::set< SubdomainID > & BlockRestrictable::blockIDs () const virtual inherited
Return the block subdomain ids for this object Note, if this is not block restricted, this function returns all mesh subdomain ids.
Returns
a set of SubdomainIDs that are valid for this object
Definition at line 190 of file BlockRestrictable.C.
{
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return _blk_mesh->meshSubdomains();
  else
    return _blk_ids;
}
Referenced by FunctorMaterial::addFunctorProperty(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), NodalPatchRecoveryAuxBase::blockRestrictElements(), MooseMesh::cacheFaceInfoVariableOwnership(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), BlockRestrictable::getBlockCoordSystem(), MaterialBase::getGenericZeroMaterialPropertyByName(), BlockRestrictable::hasBlockMaterialPropertyHelper(), SubdomainsDivision::initialize(), ElementCentroidPositions::initialize(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), MaterialBase::registerPropName(), and FVPointValueConstraint::setMyElem().
blockRestricted()
bool BlockRestrictable::blockRestricted () const virtual inherited
Returns true if this object has been restricted to a block.
See also
MooseObject
Definition at line 178 of file BlockRestrictable.C.
{
  return _blk_ids.find(Moose::ANY_BLOCK_ID) == _blk_ids.end();
}
Referenced by NodalPatchRecoveryAuxBase::blockRestrictElements(), BlockRestrictable::checkVariable(), SubdomainsDivision::divisionIndex(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), SubdomainsDivision::initialize(), ElementCentroidPositions::initialize(), BlockRestrictable::initializeBlockRestrictable(), SolutionIC::initialSetup(), and FVPointValueConstraint::setMyElem().
blocks()
const std::vector< SubdomainName > & BlockRestrictable::blocks () const inherited
Return the block names for this object.
Note, if the 'blocks' input parameter was not utilized this will return an empty vector.
Returns
vector of SubdomainNames that are valid for this object
Definition at line 184 of file BlockRestrictable.C.
{
  return _blocks;
}
Referenced by MaterialOutputAction::getParams(), BlockAverageValue::initialize(), SubdomainsDivision::initialize(), and SolutionIC::initialSetup().
blocksMaxDimension()
unsigned int BlockRestrictable::blocksMaxDimension () const inherited
Return the largest mesh dimension of the elements in the blocks for this object.
Definition at line 360 of file BlockRestrictable.C.
{
  mooseAssert(_blk_dim != libMesh::invalid_uint, "Block restriction not initialized");
  return _blk_dim;
}
buildOutputHideVariableList()
void OutputInterface::buildOutputHideVariableList (std::set< std::string > variable_names) inherited
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
Parameters
variable_names A set of variables for which the 'outputs' parameter controls
By default this is called by the constructor and passes the block name as the list of variables. This needs to be called explicitly if the build_list flag is set to False in the constructor. The latter cases is needed by the Material object to work correctly with the automatic material output capability.
Definition at line 61 of file OutputInterface.C.
{
  // Set of available names
  const std::set<OutputName> & avail = _oi_output_warehouse.getOutputNames();
  // Check for 'none'; hide variables on all outputs
  if (_oi_outputs.find("none") != _oi_outputs.end())
    for (const auto & name : avail)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  // Check for empty and 'all' in 'outputs' parameter; do not perform any variable restrictions in
  // these cases
  else if (_oi_outputs.empty() || _oi_outputs.find("all") != _oi_outputs.end())
    return;
  // Limit the variable output to Output objects listed
  else
  {
    // Create a list of outputs where the variable should be hidden
    std::set<OutputName> hide;
    std::set_difference(avail.begin(),
                        avail.end(),
                        _oi_outputs.begin(),
                        _oi_outputs.end(),
                        std::inserter(hide, hide.begin()));
    // If 'outputs' is specified add the object name to the list of items to hide
    for (const auto & name : hide)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  }
}
Referenced by ReporterTransferInterface::hideVariableHelper(), and OutputInterface::OutputInterface().
checkFace()
FaceArg Moose::FunctorBase< Moose::ADType< OutputType >::type >::checkFace (const Moose::FaceArg & face) const inherited
Examines the incoming face argument.
If the face argument producer (residual object, postprocessor, etc.) did not indicate a sidedness to the face, e.g. if the face_side member of the FaceArg is nullptr, then we may "modify" the sidedness of the argument if we are only defined on one side of the face. If the face argument producer \emph has indicated a sidedness and we are not defined on that side, then we will error
Parameters
face The face argument created by the face argument producer, likely a residual object
Returns
A face with possibly changed sidedness depending on whether we aren't defined on both sides of the face
Definition at line 181 of file MooseFunctor.h.
{
  const Elem * const elem = face.face_side;
  const FaceInfo * const fi = face.fi;
  mooseAssert(fi, "face info should be non-null");
  auto ret_face = face;
  bool check_elem_def = false;
  bool check_neighbor_def = false;
  if (!elem)
  {
    if (!hasFaceSide(*fi, true))
    {
      ret_face.face_side = fi->neighborPtr();
      check_neighbor_def = true;
    }
    else if (!hasFaceSide(*fi, false))
    {
      ret_face.face_side = fi->elemPtr();
      check_elem_def = true;
    }
  }
  else if (elem == fi->elemPtr())
    check_elem_def = true;
  else
  {
    mooseAssert(elem == fi->neighborPtr(), "This has to match something");
    check_neighbor_def = true;
  }
  if (check_elem_def && !hasFaceSide(*fi, true))
  {
    std::string additional_message = "It is not defined on the neighbor side either.";
    if (hasFaceSide(*fi, false))
      additional_message = "It is however defined on the neighbor side.";
    additional_message += " Face centroid: " + Moose::stringify(fi->faceCentroid());
    mooseError(_functor_name,
               " is not defined on the element side of the face information, but a face argument "
               "producer "
               "(e.g. residual object, postprocessor, etc.) has requested evaluation there.\n",
               additional_message);
  }
  if (check_neighbor_def && !hasFaceSide(*fi, false))
  {
    std::string additional_message = "It is not defined on the element side either.";
    if (hasFaceSide(*fi, true))
      additional_message = "It is however defined on the element side.";
    additional_message += " Face centroid: " + Moose::stringify(fi->faceCentroid());
    mooseError(
        _functor_name,
        " is not defined on the neighbor side of the face information, but a face argument "
        "producer (e.g. residual object, postprocessor, etc.) has requested evaluation there.\n",
        additional_message);
  }
  return ret_face;
}
checkVariable()
void BlockRestrictable::checkVariable (const MooseVariableFieldBase & variable) const virtual inherited
Helper for checking that the ids for this object are in agreement with the variables on the supplied variable.
Parameters
variable The variable to check against.
Reimplemented in DomainUserObject.
Definition at line 333 of file BlockRestrictable.C.
{
  // a variable defined on all internal sides does not need this check because
  // it can be coupled with other variables in DG kernels
  if (variable.activeSubdomains().count(Moose::INTERNAL_SIDE_LOWERD_ID) > 0)
    return;
  if (!isBlockSubset(variable.activeSubdomains()))
  {
    std::string var_ids = Moose::stringify(variable.activeSubdomains(), ", ");
    std::string obj_ids = Moose::stringify(blockRestricted() ? _blk_ids : meshBlockIDs(), ", ");
    mooseError("The 'block' parameter of the object '",
               _blk_name,
               "' must be a subset of the 'block' parameter of the variable '",
               variable.name(),
               "':\n    Object '",
               _blk_name,
               "': ",
               obj_ids,
               "\n    Variable '",
               variable.name(),
               "': ",
               var_ids);
  }
}
Referenced by DomainUserObject::checkVariable().
clearAllDofIndices()
template<typename OutputType > void MooseVariableFV< OutputType >::clearAllDofIndices final virtual
Reimplemented from MooseVariableBase.
Definition at line 739 of file MooseVariableFV.C.
{
  _element_data->clearDofIndices();
  _neighbor_data->clearDofIndices();
}
clearCacheData()
void Moose::FunctorBase< Moose::ADType< OutputType >::type >::clearCacheData private inherited
clear cache data
Definition at line 391 of file MooseFunctor.h.
{
  for (auto & map_pr : _qp_to_value)
    for (auto & pr : map_pr.second)
      pr.first = false;
  for (auto & map_pr : _side_qp_to_value)
  {
    auto & side_vector = map_pr.second;
    for (auto & qp_vector : side_vector)
      for (auto & pr : qp_vector)
        pr.first = false;
  }
  _current_qp_map_key = DofObject::invalid_id;
  _current_qp_map_value = nullptr;
  _current_side_qp_map_key = DofObject::invalid_id;
  _current_side_qp_map_value = nullptr;
  _elem_arg_to_value.clear();
  _face_arg_to_value.clear();
  _node_arg_to_value.clear();
}
clearCaches()
template<typename OutputType > void MooseVariableFV< OutputType >::clearCaches protected
clear finite volume caches
Definition at line 722 of file MooseVariableFV.C.
{
  _elem_to_grad.clear();
}
clearDofIndices()
template<typename OutputType > void MooseVariableFV< OutputType >::clearDofIndices () override virtual
Clear out the dof indices.
We do this in case this variable is not going to be prepared at all...
Implements MooseVariableFieldBase.
Definition at line 118 of file MooseVariableFV.C.
{
  _element_data->clearDofIndices();
}
componentDofIndices()
std::vector< dof_id_type > MooseVariableBase::componentDofIndices (const std::vector< dof_id_type > & dof_indices, unsigned int component) const inherited
Obtain DoF indices of a component with the indices of the 0th component.
Definition at line 155 of file MooseVariableBase.C.
{
  std::vector<dof_id_type> new_dof_indices(dof_indices);
  if (component != 0)
  {
    if (isNodal())
      for (auto & id : new_dof_indices)
        id += component;
    else
    {
      unsigned int n = dof_indices.size();
      for (auto & id : new_dof_indices)
        id += component * n;
    }
  }
  return new_dof_indices;
}
Referenced by Assembly::addJacobianBlock(), Assembly::cacheJacobianBlock(), and Assembly::cacheJacobianBlockNonzero().
componentName()
std::string MooseVariableFieldBase::componentName (const unsigned int comp) const inherited
Get the variable name of a component in libMesh.
Definition at line 27 of file MooseVariableFieldBase.C.
{
  if (comp >= _count)
    mooseError("Component index must be less than the number of components of variable ",
               _var_name);
  if (isArray())
    return this->_subproblem.arrayVariableComponent(_var_name, comp);
  else
    return _var_name;
}
computeElemValues()
template<typename OutputType > void MooseVariableFV< OutputType >::computeElemValues override virtual
Initializes/computes variable values from the solution vectors for the current element being operated on in assembly.
This must be called every time the current element (as defined by the assembly data structure changes in order for objects that bind to sln, adSln, uDot, etc. to be updated/correct.
Implements MooseVariableFieldBase.
Definition at line 307 of file MooseVariableFV.C.
{
  _element_data->setGeometry(Moose::Volume);
  _element_data->computeValues();
}
computeElemValuesFace()
template<typename OutputType > void MooseVariableFV< OutputType >::computeElemValuesFace () override virtual
Compute values at facial quadrature points.
Implements MooseVariableFieldBase.
Definition at line 315 of file MooseVariableFV.C.
{
  _element_data->setGeometry(Moose::Face);
  _element_data->computeValues();
}
computeFaceValues()
template<typename OutputType > void MooseVariableFV< OutputType >::computeFaceValues (const FaceInfo & fi) override virtual
Initializes/computes variable values from the solution vectors for the face represented by fi.
This includes initializing data for elements on both sides of the face (elem and neighbor) and handles the case where there is no element on one side of the face gracefully - i.e. you call this uniformly for every face regardless of whether you are on a boundary or not - or whether the variable is only defined on one side of the face or not.
Reimplemented from MooseVariableFieldBase.
Definition at line 339 of file MooseVariableFV.C.
{
  _element_data->setGeometry(Moose::Face);
  _neighbor_data->setGeometry(Moose::Face);
  const auto facetype = fi.faceType(std::make_pair(this->number(), this->sys().number()));
  if (facetype == FaceInfo::VarFaceNeighbors::NEITHER)
    return;
  else if (facetype == FaceInfo::VarFaceNeighbors::BOTH)
  {
    _element_data->computeValuesFace(fi);
    _neighbor_data->computeValuesFace(fi);
  }
  else if (facetype == FaceInfo::VarFaceNeighbors::ELEM)
    _element_data->computeValuesFace(fi);
  else if (facetype == FaceInfo::VarFaceNeighbors::NEIGHBOR)
    _neighbor_data->computeValuesFace(fi);
  else
    mooseError("robert wrote broken MooseVariableFV code");
}
computeLowerDValues()
template<typename OutputType > virtual void MooseVariableFV< OutputType >::computeLowerDValues () inline final override virtual
compute values at quadrature points on the lower dimensional element
Implements MooseVariableFieldBase.
Definition at line 135 of file MooseVariableFV.h.
  {
    // mooseError("computeLowerDValues not supported by MooseVariableFVBase");
  }
computeNeighborValues()
template<typename OutputType > void MooseVariableFV< OutputType >::computeNeighborValues () override virtual
Compute values at quadrature points for the neighbor.
Implements MooseVariableFieldBase.
Definition at line 331 of file MooseVariableFV.C.
{
  _neighbor_data->setGeometry(Moose::Volume);
  _neighbor_data->computeValues();
}
computeNeighborValuesFace()
template<typename OutputType > void MooseVariableFV< OutputType >::computeNeighborValuesFace () override virtual
Compute values at facial quadrature points for the neighbor.
Implements MooseVariableFieldBase.
Definition at line 323 of file MooseVariableFV.C.
{
  _neighbor_data->setGeometry(Moose::Face);
  _neighbor_data->computeValues();
}
computeNodalNeighborValues()
template<typename OutputType > virtual void MooseVariableFV< OutputType >::computeNodalNeighborValues () inline final override virtual
Compute nodal values of this variable in the neighbor.
Implements MooseVariableFieldBase.
Definition at line 139 of file MooseVariableFV.h.
  {
    // mooseError("computeNodalNeighborValues not supported by MooseVariableFVBase");
  }
computeNodalValues()
template<typename OutputType > virtual void MooseVariableFV< OutputType >::computeNodalValues () inline final override virtual
Compute nodal values of this variable.
Implements MooseVariableFieldBase.
Definition at line 143 of file MooseVariableFV.h.
  {
    // mooseError("computeNodalValues not supported by MooseVariableFVBase");
  }
computingCurl()
template<typename OutputType > bool MooseVariableFV< OutputType >::computingCurl () const inline final override virtual
Whether or not this variable is computing any curl quantities.
Implements MooseVariableField< OutputType >.
Definition at line 569 of file MooseVariableFV.h.
{ return false; }
computingDiv()
template<typename OutputType > bool MooseVariableFV< OutputType >::computingDiv () const inline final override virtual
Whether or not this variable is computing any divergence quantities.
Implements MooseVariableField< OutputType >.
Definition at line 570 of file MooseVariableFV.h.
{ return false; }
computingSecond()
template<typename OutputType > bool MooseVariableFV< OutputType >::computingSecond () const inline final override virtual
Whether or not this variable is computing any second derivatives.
Implements MooseVariableField< OutputType >.
Definition at line 568 of file MooseVariableFV.h.
{ return false; }
connectControllableParams()
void MooseBaseParameterInterface::connectControllableParams (const std::string & parameter, const std::string & object_type, const std::string & object_name, const std::string & object_parameter) const inherited
Connect controllable parameter of this action with the controllable parameters of the objects added by this action.
Parameters
parameter Name of the controllable parameter of this action
object_type Type of the object added by this action.
object_name Name of the object added by this action.
object_parameter Name of the parameter of the object.
Definition at line 34 of file MooseBaseParameterInterface.C.
{
  MooseObjectParameterName primary_name(uniqueName(), parameter);
  const auto base_type = _factory.getValidParams(object_type).get<std::string>("_moose_base");
  MooseObjectParameterName secondary_name(base_type, object_name, object_parameter);
  _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
      primary_name, secondary_name);
  const auto & tags = _pars.get<std::vector<std::string>>("control_tags");
  for (const auto & tag : tags)
  {
    if (!tag.empty())
    {
      MooseObjectParameterName tagged_name(tag, _moose_base->name(), parameter);
      _moose_base->getMooseApp().getInputParameterWarehouse().addControllableParameterConnection(
          tagged_name, secondary_name);
    }
  }
}
count()
unsigned int MooseVariableBase::count () const inline inherited
Get the number of components Note: For standard and vector variables, the number is one.
Definition at line 109 of file MooseVariableBase.h.
{ return _count; }
Referenced by Assembly::addJacobianBlock(), EigenProblem::adjustEigenVector(), ArrayBodyForce::ArrayBodyForce(), ArrayConstantIC::ArrayConstantIC(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayFunctionIC::ArrayFunctionIC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), BuildArrayVariableAux::BuildArrayVariableAux(), Assembly::cacheJacobianBlock(), Assembly::cacheJacobianBlockNonzero(), TagAuxBase< T >::checkCoupledVariable(), BuildArrayVariableAux::compute(), ArrayNodalBC::computeJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), ArrayNodalBC::computeOffDiagJacobian(), ArrayIntegratedBC::computeQpJacobian(), ArrayNodalBC::computeQpJacobian(), ArrayKernel::computeQpJacobian(), EigenArrayDirichletBC::computeQpJacobian(), ArrayCoupledTimeDerivative::computeQpJacobian(), ArrayDiffusion::computeQpJacobian(), ArrayReaction::computeQpJacobian(), ArrayTimeDerivative::computeQpJacobian(), ArrayIntegratedBC::computeQpOffDiagJacobian(), ArrayKernel::computeQpOffDiagJacobian(), ArrayCoupledTimeDerivative::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), ArrayNodalBC::computeQpOffDiagJacobian(), EigenArrayDirichletBC::computeQpOffDiagJacobian(), Kernel::computeQpOffDiagJacobianArray(), ArrayIntegratedBC::computeQpOffDiagJacobianScalar(), ArrayKernel::computeQpOffDiagJacobianScalar(), ArrayCoupledTimeDerivative::computeQpResidual(), ArrayReaction::computeQpResidual(), ArrayTimeDerivative::computeQpResidual(), ArrayParsedAux::computeValue(), FunctionArrayAux::computeValue(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), FunctionArrayAux::FunctionArrayAux(), ArrayFunctionIC::gradient(), AdvancedOutput::initAvailableLists(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), ArrayDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), Assembly::prepareJacobianBlock(), Assembly::prepareLowerD(), Assembly::prepareNeighbor(), Assembly::prepareNonlocal(), Assembly::prepareVariable(), Assembly::prepareVariableNonlocal(), MultiAppDofCopyTransfer::transfer(), MultiAppDofCopyTransfer::transferDofObject(), and ArrayFunctionIC::value().
curlPhi()
template<typename OutputType > const FieldVariablePhiValue & MooseVariableFV< OutputType >::curlPhi () const inline final override virtual
Curl of the shape functions.
Implements MooseVariableField< OutputType >.
Definition at line 579 of file MooseVariableFV.h.
  {
    mooseError("We don't currently implement curl for FV");
  }
currentElem()
template<typename OutputType > virtual const Elem *const & MooseVariableFV< OutputType >::currentElem () const inline override virtual
Current element this variable is evaluated at.
Implements MooseVariableFieldBase.
Definition at line 176 of file MooseVariableFV.h.
{ return _element_data->currentElem(); }
customSetup() [1/2]
virtual void SetupInterface::customSetup (const ExecFlagType &) inline virtual inherited
Gets called in FEProblemBase::execute() for execute flags other than initial, timestep_begin, nonlinear, linear and subdomain.
Reimplemented in Function.
Definition at line 61 of file SetupInterface.h.
{}
customSetup() [2/2]
void Moose::FunctorBase< Moose::ADType< OutputType >::type >::customSetup (const ExecFlagType & exec_type) override virtual inherited
Implements Moose::FunctorAbstract.
Definition at line 134 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(exec_type))
    clearCacheData();
}
determineBoundaryToDirichletBCMap()
template<typename OutputType > void MooseVariableFV< OutputType >::determineBoundaryToDirichletBCMap private
Setup the boundary to Dirichlet BC map.
Definition at line 850 of file MooseVariableFV.C.
{
  _boundary_id_to_dirichlet_bc.clear();
  std::vector<FVDirichletBCBase *> bcs;
  // I believe because query() returns by value but condition returns by reference that binding to a
  // const lvalue reference results in the query() getting destructed and us holding onto a dangling
  // reference. I think that condition returned by value we would be able to bind to a const lvalue
  // reference here. But as it is we'll bind to a regular lvalue
  const auto base_query = this->_subproblem.getMooseApp()
                              .theWarehouse()
                              .query()
                              .template condition<AttribSystem>("FVDirichletBC")
                              .template condition<AttribThread>(_tid)
                              .template condition<AttribVar>(_var_num)
                              .template condition<AttribSysNum>(this->_sys.number());
  for (const auto bnd_id : this->_mesh.getBoundaryIDs())
  {
    auto base_query_copy = base_query;
    base_query_copy.template condition<AttribBoundaries>(std::set<BoundaryID>({bnd_id}))
        .queryInto(bcs);
    mooseAssert(bcs.size() <= 1, "cannot have multiple dirichlet BCs on the same boundary");
    if (!bcs.empty())
      _boundary_id_to_dirichlet_bc.emplace(bnd_id, bcs[0]);
  }
  _dirichlet_map_setup = true;
}
divPhi()
template<typename OutputType > const FieldVariablePhiDivergence & MooseVariableFV< OutputType >::divPhi () const inline final override virtual
Divergence of the shape functions.
Implements MooseVariableField< OutputType >.
Definition at line 583 of file MooseVariableFV.h.
  {
    mooseError("We don't currently implement divergence for FV");
  }
doDerivatives()
bool MooseVariableBase::doDerivatives () const protected inherited
Returns
whether we should insert derivatives
dofIndices()
template<typename OutputType > virtual const std::vector< dof_id_type > & MooseVariableFV< OutputType >::dofIndices () const inline final virtual
Get local DoF indices.
Reimplemented from MooseVariableBase.
Definition at line 184 of file MooseVariableFV.h.
  {
    return _element_data->dofIndices();
  }
Referenced by FVElementalKernel::computeJacobian(), FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVScalarLagrangeMultiplierInterface::computeJacobian(), FVScalarLagrangeMultiplierConstraint::computeOffDiagJacobian(), FVElementalKernel::computeResidualAndJacobian(), and FVScalarLagrangeMultiplierConstraint::computeResidualAndJacobian().
dofIndicesLower()
template<typename OutputType > const std::vector< dof_id_type > & MooseVariableFV< OutputType >::dofIndicesLower () const final override virtual
Get dof indices for the current lower dimensional element (this is meaningful when performing mortar FEM)
Returns
the lower dimensional element's dofs
Implements MooseVariableFieldBase.
Definition at line 795 of file MooseVariableFV.h.
{
  static const std::vector<dof_id_type> empty;
  return empty;
}
dofIndicesNeighbor()
template<typename OutputType > virtual const std::vector< dof_id_type > & MooseVariableFV< OutputType >::dofIndicesNeighbor () const inline final virtual
Get neighbor DOF indices for currently selected element.
Returns
the neighbor degree of freedom indices
Implements MooseVariableFieldBase.
Definition at line 188 of file MooseVariableFV.h.
  {
    return _neighbor_data->dofIndices();
  }
Referenced by FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), and FVScalarLagrangeMultiplierInterface::computeJacobian().
dofMap()
const DofMap & MooseVariableBase::dofMap () const inline inherited
The DofMap associated with the system this variable is in.
Definition at line 131 of file MooseVariableBase.h.
{ return _dof_map; }
Referenced by AuxScalarKernel::compute(), and ScalarVariable::execute().
dofValues()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValues () const override virtual
dof values getters
Implements MooseVariableField< OutputType >.
Definition at line 160 of file MooseVariableFV.C.
{
  return _element_data->dofValues();
}
dofValuesDot()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesDot override virtual
Implements MooseVariableField< OutputType >.
Definition at line 216 of file MooseVariableFV.C.
{
  return _element_data->dofValuesDot();
}
dofValuesDotDot()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesDotDot override virtual
Implements MooseVariableField< OutputType >.
Definition at line 223 of file MooseVariableFV.C.
{
  return _element_data->dofValuesDotDot();
}
dofValuesDotDotNeighbor()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesDotDotNeighbor override virtual
Implements MooseVariableField< OutputType >.
Definition at line 251 of file MooseVariableFV.C.
{
  return _neighbor_data->dofValuesDotDot();
}
dofValuesDotDotOld()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesDotDotOld override virtual
Implements MooseVariableField< OutputType >.
Definition at line 237 of file MooseVariableFV.C.
{
  return _element_data->dofValuesDotDotOld();
}
dofValuesDotDotOldNeighbor()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesDotDotOldNeighbor override virtual
Implements MooseVariableField< OutputType >.
Definition at line 265 of file MooseVariableFV.C.
{
  return _neighbor_data->dofValuesDotDotOld();
}
dofValuesDotNeighbor()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesDotNeighbor override virtual
Implements MooseVariableField< OutputType >.
Definition at line 244 of file MooseVariableFV.C.
{
  return _neighbor_data->dofValuesDot();
}
dofValuesDotOld()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesDotOld override virtual
Implements MooseVariableField< OutputType >.
Definition at line 230 of file MooseVariableFV.C.
{
  return _element_data->dofValuesDotOld();
}
dofValuesDotOldNeighbor()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesDotOldNeighbor override virtual
Implements MooseVariableField< OutputType >.
Definition at line 258 of file MooseVariableFV.C.
{
  return _neighbor_data->dofValuesDotOld();
}
dofValuesDuDotDotDu()
template<typename OutputType > const MooseArray< Number > & MooseVariableFV< OutputType >::dofValuesDuDotDotDu override virtual
Implements MooseVariableField< OutputType >.
Definition at line 279 of file MooseVariableFV.C.
{
  return _element_data->dofValuesDuDotDotDu();
}
dofValuesDuDotDotDuNeighbor()
template<typename OutputType > const MooseArray< Number > & MooseVariableFV< OutputType >::dofValuesDuDotDotDuNeighbor override virtual
Implements MooseVariableField< OutputType >.
Definition at line 293 of file MooseVariableFV.C.
{
  return _neighbor_data->dofValuesDuDotDotDu();
}
dofValuesDuDotDu()
template<typename OutputType > const MooseArray< Number > & MooseVariableFV< OutputType >::dofValuesDuDotDu override virtual
Implements MooseVariableField< OutputType >.
Definition at line 272 of file MooseVariableFV.C.
{
  return _element_data->dofValuesDuDotDu();
}
dofValuesDuDotDuNeighbor()
template<typename OutputType > const MooseArray< Number > & MooseVariableFV< OutputType >::dofValuesDuDotDuNeighbor override virtual
Implements MooseVariableField< OutputType >.
Definition at line 286 of file MooseVariableFV.C.
{
  return _neighbor_data->dofValuesDuDotDu();
}
dofValuesNeighbor()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesNeighbor override virtual
Implements MooseVariableField< OutputType >.
Definition at line 188 of file MooseVariableFV.C.
{
  return _neighbor_data->dofValues();
}
dofValuesOld()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesOld override virtual
Implements MooseVariableField< OutputType >.
Definition at line 167 of file MooseVariableFV.C.
{
  return _element_data->dofValuesOld();
}
dofValuesOlder()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesOlder override virtual
Implements MooseVariableField< OutputType >.
Definition at line 174 of file MooseVariableFV.C.
{
  return _element_data->dofValuesOlder();
}
dofValuesOlderNeighbor()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesOlderNeighbor override virtual
Implements MooseVariableField< OutputType >.
Definition at line 202 of file MooseVariableFV.C.
{
  return _neighbor_data->dofValuesOlder();
}
dofValuesOldNeighbor()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesOldNeighbor override virtual
Implements MooseVariableField< OutputType >.
Definition at line 195 of file MooseVariableFV.C.
{
  return _neighbor_data->dofValuesOld();
}
dofValuesPreviousNL()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesPreviousNL override virtual
Implements MooseVariableField< OutputType >.
Definition at line 181 of file MooseVariableFV.C.
{
  return _element_data->dofValuesPreviousNL();
}
dofValuesPreviousNLNeighbor()
template<typename OutputType > const MooseVariableFV< OutputType >::DoFValue & MooseVariableFV< OutputType >::dofValuesPreviousNLNeighbor override virtual
Implements MooseVariableField< OutputType >.
Definition at line 209 of file MooseVariableFV.C.
{
  return _neighbor_data->dofValuesPreviousNL();
}
dot() [1/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluateDot overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 110 of file MooseFunctor.h.
{
  return evaluateDot(elem, state);
}
dot() [2/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 114 of file MooseFunctor.h.
{
  return evaluateDot(elem_point, state);
}
dot() [3/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 112 of file MooseFunctor.h.
{
  return evaluateDot(elem_qp, state);
}
dot() [4/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 113 of file MooseFunctor.h.
{
  return evaluateDot(elem_side_qp, state);
}
dot() [5/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const FaceArg & face, const StateArg & state) const inherited
Definition at line 111 of file MooseFunctor.h.
{
  return evaluateDot(checkFace(face), state);
}
dot() [6/6]
FunctorBase< Moose::ADType< OutputType >::type >::DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::dot (const NodeArg & node, const StateArg & state) const inherited
Definition at line 115 of file MooseFunctor.h.
{
  return evaluateDot(node, state);
}
duDotDotDu()
template<typename OutputType > const VariableValue & MooseVariableFV< OutputType >::duDotDotDu () const inline
Definition at line 254 of file MooseVariableFV.h.
{ return _element_data->duDotDotDu(); }
duDotDotDuNeighbor()
template<typename OutputType > const VariableValue & MooseVariableFV< OutputType >::duDotDotDuNeighbor () const inline
Definition at line 256 of file MooseVariableFV.h.
{ return _neighbor_data->duDotDotDu(); }
duDotDu()
template<typename OutputType > const VariableValue & MooseVariableFV< OutputType >::duDotDu () const inline
Definition at line 253 of file MooseVariableFV.h.
{ return _element_data->duDotDu(); }
duDotDuNeighbor()
template<typename OutputType > const VariableValue & MooseVariableFV< OutputType >::duDotDuNeighbor () const inline
Definition at line 255 of file MooseVariableFV.h.
{ return _neighbor_data->duDotDu(); }
eigen() [1/2]
bool MooseVariableBase::eigen () const inline inherited
Whether or not this variable operates on an eigen kernel.
Definition at line 158 of file MooseVariableBase.h.
{ return _is_eigen; }
Referenced by EigenProblem::adjustEigenVector().
eigen() [2/2]
void MooseVariableBase::eigen (bool eigen) inline inherited
Mark this variable as an eigen var or non-eigen var.
Definition at line 163 of file MooseVariableBase.h.
{ _is_eigen = eigen; }
Referenced by MooseVariableBase::eigen().
enabled()
virtual bool MooseObject::enabled () const inline virtual inherited
Return the enabled status of the object.
Reimplemented in EigenKernel.
Definition at line 54 of file MooseObject.h.
{ return _enabled; }
Referenced by EigenKernel::enabled().
errorPrefix()
std::string MooseBaseErrorInterface::errorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for this object:
The following <error_type> occurred in the object "<name>", of type "<type>".
Definition at line 15 of file MooseBaseErrorInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the object \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseErrorInterface::mooseError(), and MooseBaseErrorInterface::mooseWarning().
evaluate() [1/6]
template<typename OutputType > MooseVariableFV< OutputType >::ValueType MooseVariableFV< OutputType >::evaluate (const ElemArg & elem, const StateArg & state) const final override private virtual
Evaluate the functor with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Implements Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 725 of file MooseVariableFV.h.
{
  return getElemValue(elem_arg.elem, state);
}
evaluate() [2/6]
template<typename OutputType > MooseVariableFV< OutputType >::ValueType MooseVariableFV< OutputType >::evaluate (const ElemPointArg & elem_point, const StateArg & state) const final override private virtual
Evaluate the functor with a given element and point.
Some example implementations of this method could perform a two-term Taylor expansion using cell-centered value and gradient
Implements Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 732 of file MooseVariableFV.h.
{
  return (*this)(elem_point.makeElem(), state) +
         (elem_point.point - elem_point.elem->vertex_average()) *
             this->gradient(elem_point.makeElem(), state);
}
evaluate() [3/6]
template<typename OutputType > MooseVariableFV< OutputType >::ValueType MooseVariableFV< OutputType >::evaluate (const ElemQpArg & qp, const StateArg & state) const final override private virtual
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor evaluated at the requested state and space
Implements Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 741 of file MooseVariableFV.h.
{
  return (*this)(ElemPointArg{elem_qp.elem,
                              elem_qp.point,
                              _face_interp_method == Moose::FV::InterpMethod::SkewCorrectedAverage},
                 state);
}
evaluate() [4/6]
template<typename OutputType > MooseVariableFV< OutputType >::ValueType MooseVariableFV< OutputType >::evaluate (const ElemSideQpArg & side_qp, const StateArg & state) const final override private virtual
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor evaluated at the requested state and space
Implements Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 751 of file MooseVariableFV.h.
{
  return (*this)(ElemPointArg{elem_side_qp.elem,
                              elem_side_qp.point,
                              _face_interp_method == Moose::FV::InterpMethod::SkewCorrectedAverage},
                 state);
}
evaluate() [5/6]
template<typename OutputType > MooseVariableFV< OutputType >::ValueType MooseVariableFV< OutputType >::evaluate (const FaceArg & face, const StateArg & state) const final override private virtual
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor evaluated at the requested state and space
Implements Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 747 of file MooseVariableFV.C.
{
  const FaceInfo * const fi = face.fi;
  mooseAssert(fi, "The face information must be non-null");
  if (isDirichletBoundaryFace(*fi, face.face_side, state))
  {
    mooseAssert(state.state == 0,
                "We have not yet added support for evaluating Dirichlet boundary conditions at "
                "states other than the current solution state (e.g. current time)");
    return getDirichletBoundaryFaceValue(*fi, face.face_side, state);
  }
  else if (isExtrapolatedBoundaryFace(*fi, face.face_side, state))
  {
    bool two_term_boundary_expansion = _two_term_boundary_expansion;
    if (face.limiter_type == Moose::FV::LimiterType::Upwind)
      if ((face.elem_is_upwind && face.face_side == fi->elemPtr()) ||
          (!face.elem_is_upwind && face.face_side == fi->neighborPtr()))
        two_term_boundary_expansion = false;
    return getExtrapolatedBoundaryFaceValue(
        *fi, two_term_boundary_expansion, face.correct_skewness, face.face_side, state);
  }
  else
  {
    mooseAssert(this->isInternalFace(*fi),
                "We must be either Dirichlet, extrapolated, or internal");
    return Moose::FV::interpolate(*this, face, state);
  }
}
evaluate() [6/6]
template<typename OutputType > MooseVariableFV< OutputType >::ValueType MooseVariableFV< OutputType >::evaluate (const NodeArg & node, const StateArg & state) const final override private virtual
Implements Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 778 of file MooseVariableFV.C.
{
  const auto & node_to_elem_map = this->_mesh.nodeToElemMap();
  const auto & elem_ids = libmesh_map_find(node_to_elem_map, node_arg.node->id());
  ValueType sum = 0;
  Real total_weight = 0;
  mooseAssert(elem_ids.size(), "There should always be at least one element connected to a node");
  for (const auto elem_id : elem_ids)
  {
    const Elem * const elem = this->_mesh.queryElemPtr(elem_id);
    mooseAssert(elem, "We should have this element available");
    if (!this->hasBlocks(elem->subdomain_id()))
      continue;
    const ElemPointArg elem_point{
        elem, *node_arg.node, _face_interp_method == Moose::FV::InterpMethod::SkewCorrectedAverage};
    const auto weight = 1 / (*node_arg.node - elem->vertex_average()).norm();
    sum += weight * (*this)(elem_point, state);
    total_weight += weight;
  }
  return sum / total_weight;
}
evaluateDot() [1/6]
template<typename OutputType > MooseVariableFV< OutputType >::DotType MooseVariableFV< OutputType >::evaluateDot (const ElemArg & , const StateArg &) const final override private virtual
Evaluate the functor time derivative with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 802 of file MooseVariableFV.C.
{
  mooseError("evaluateDot not implemented for this class of finite volume variables");
}
evaluateDot() [2/6]
virtual DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateDot (const ElemPointArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor time derivative with a given element and point.
Definition at line 322 of file MooseFunctor.h.
  {
    mooseError("Element-point time derivative not implemented for functor " + functorName());
  }
evaluateDot() [3/6]
virtual DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateDot (const ElemQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor time derivative evaluated at the requested state and space
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, and MooseVariableFE< ComputeValueType >.
Definition at line 302 of file MooseFunctor.h.
  {
    mooseError("Element quadrature point time derivative not implemented for functor " +
               functorName());
  }
evaluateDot() [4/6]
virtual DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateDot (const ElemSideQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor time derivative evaluated at the requested state and space
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, and MooseVariableFE< ComputeValueType >.
Definition at line 313 of file MooseFunctor.h.
  {
    mooseError("Element side quadrature point time derivative not implemented for functor " +
               functorName());
  }
evaluateDot() [5/6]
virtual DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateDot (const FaceArg & , const StateArg &) const inline protected virtual inherited
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor time derivative evaluated at the requested state and space
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, and MooseVariableFE< ComputeValueType >.
Definition at line 292 of file MooseFunctor.h.
  {
    mooseError("Face time derivative not implemented for functor " + functorName());
  }
evaluateDot() [6/6]
virtual DotType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateDot (const NodeArg & , const StateArg &) const inline protected virtual inherited
Definition at line 327 of file MooseFunctor.h.
  {
    mooseError("Time derivative at node not implemented for functor " + functorName());
  }
evaluateGradDot() [1/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const ElemArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor gradient-dot with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, and MooseVariableFE< ComputeValueType >.
Definition at line 336 of file MooseFunctor.h.
  {
    mooseError("Element gradient-dot not implemented for functor " + functorName());
  }
evaluateGradDot() [2/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const ElemPointArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor gradient-dot with a given element and point.
Definition at line 376 of file MooseFunctor.h.
  {
    mooseError("Element-point gradient-dot not implemented for functor " + functorName());
  }
evaluateGradDot() [3/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const ElemQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient-dot evaluated at the requested state and space
Definition at line 356 of file MooseFunctor.h.
  {
    mooseError("Element quadrature point gradient-dot not implemented for functor " +
               functorName());
  }
evaluateGradDot() [4/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const ElemSideQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient-dot evaluated at the requested state and space
Definition at line 367 of file MooseFunctor.h.
  {
    mooseError("Element side quadrature point gradient-dot not implemented for functor " +
               functorName());
  }
evaluateGradDot() [5/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const FaceArg & , const StateArg &) const inline protected virtual inherited
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor gradient-dot evaluated at the requested state and space
Definition at line 346 of file MooseFunctor.h.
  {
    mooseError("Face gradient-dot not implemented for functor " + functorName());
  }
evaluateGradDot() [6/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradDot (const NodeArg & , const StateArg &) const inline protected virtual inherited
Definition at line 381 of file MooseFunctor.h.
  {
    mooseError("Gradient-dot at node not implemented for functor " + functorName());
  }
evaluateGradient() [1/6]
template<typename OutputType > MooseVariableFV< OutputType >::GradientType MooseVariableFV< OutputType >::evaluateGradient (const ElemArg & , const StateArg &) const final override private virtual
Evaluate the functor gradient with a given element.
Some example implementations of this method could compute an element-average or evaluate at the element centroid
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 771 of file MooseVariableFV.h.
{
  return adGradSln(elem_arg.elem, state, elem_arg.correct_skewness);
}
evaluateGradient() [2/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradient (const ElemPointArg & , const StateArg &) const inline protected virtual inherited
Evaluate the functor gradient with a given element and point.
Definition at line 268 of file MooseFunctor.h.
  {
    mooseError("Element-point gradient not implemented for functor " + functorName());
  }
evaluateGradient() [3/6]
template<typename OutputType > MooseVariableFV< OutputType >::GradientType MooseVariableFV< OutputType >::evaluateGradient (const ElemQpArg & , const StateArg &) const final override private virtual
Parameters
qp See the ElemQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient evaluated at the requested state and space
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 762 of file MooseVariableFV.h.
{
  return adGradSln(
      qp_arg.elem, state, _face_interp_method == Moose::FV::InterpMethod::SkewCorrectedAverage);
}
evaluateGradient() [4/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradient (const ElemSideQpArg & , const StateArg &) const inline protected virtual inherited
Parameters
side_qp See the ElemSideQpArg doxygen
state See the StateArg doxygen
Returns
The functor gradient evaluated at the requested state and space
Reimplemented in MooseVariableFE< OutputType >, MooseVariableFE< Real >, MooseVariableFE< T >, MooseVariableFE< RealVectorValue >, MooseVariableFE< RealEigenVector >, and MooseVariableFE< ComputeValueType >.
Definition at line 259 of file MooseFunctor.h.
  {
    mooseError("Element side quadrature point gradient not implemented for functor " +
               functorName());
  }
evaluateGradient() [5/6]
template<typename OutputType > MooseVariableFV< OutputType >::GradientType MooseVariableFV< OutputType >::evaluateGradient (const FaceArg & , const StateArg &) const final override private virtual
Parameters
face See the FaceArg doxygen
state See the StateArg doxygen
Returns
The functor gradient evaluated at the requested state and space
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 779 of file MooseVariableFV.h.
{
  mooseAssert(face.fi, "We must have a non-null face information");
  return adGradSln(*face.fi, state, face.correct_skewness);
}
evaluateGradient() [6/6]
virtual GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::evaluateGradient (const NodeArg & , const StateArg &) const inline protected virtual inherited
Definition at line 273 of file MooseFunctor.h.
  {
    mooseError("Gradient at node not implemented for functor " + functorName());
  }
faceInterpolationMethod()
template<typename OutputType > Moose::FV::InterpMethod MooseVariableFV< OutputType >::faceInterpolationMethod () const inline
Definition at line 193 of file MooseVariableFV.h.
{ return _face_interp_method; }
Referenced by FVAnisotropicDiffusion::computeQpResidual(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), and FVFluxKernel::gradUDotNormal().
feType()
const FEType & MooseVariableBase::feType () const inline inherited
Get the type of finite element object.
Definition at line 54 of file MooseVariableBase.h.
{ return _fe_type; }
Referenced by SetupResidualDebugAction::act(), ADDGKernel::ADDGKernel(), Assembly::adGradPhi(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), BoundsAuxBase::BoundsAuxBase(), BuildArrayVariableAux::BuildArrayVariableAux(), TagAuxBase< T >::checkCoupledVariable(), GapValueAux::computeValue(), CopyValueAux::CopyValueAux(), DGKernel::DGKernel(), MultiAppNearestNodeTransfer::execute(), moose::internal::incompatVarMsg(), AdvancedOutput::initAvailableLists(), MultiAppProjectionTransfer::initialSetup(), AdvancedOutput::initShowHideLists(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), MeshDivisionAux::MeshDivisionAux(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodalBC::NodalBC(), NodalKernel::NodalKernel(), SolutionUserObject::pointValueWrapper(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), MultiAppDofCopyTransfer::transfer(), and VectorNodalBC::VectorNodalBC().
fieldType()
template<typename OutputType > Moose::VarFieldType MooseVariableFV< OutputType >::fieldType () const override virtual
Filed type of this variable.
Implements MooseVariableFieldBase.
Definition at line 104 of file MooseVariableFV.C.
{
  if (std::is_same<OutputType, Real>::value)
    return Moose::VarFieldType::VAR_FIELD_STANDARD;
  else if (std::is_same<OutputType, RealVectorValue>::value)
    return Moose::VarFieldType::VAR_FIELD_VECTOR;
  else if (std::is_same<OutputType, RealEigenVector>::value)
    return Moose::VarFieldType::VAR_FIELD_ARRAY;
  else
    mooseError("Unknown variable field type");
}
functorName()
const MooseFunctorName & Moose::FunctorBase< Moose::ADType< OutputType >::type >::functorName () const inline inherited
Return the functor name.
Definition at line 77 of file MooseFunctor.h.
{ return _functor_name; }
getBlockCoordSystem()
Moose::CoordinateSystemType BlockRestrictable::getBlockCoordSystem () protected inherited
Check if the blocks this object operates on all have the same coordinate system, and if so return it.
Definition at line 311 of file BlockRestrictable.C.
{
  if (!_blk_mesh)
    mooseError("No mesh available in BlockRestrictable::checkCoordSystem()");
  if (!_blk_feproblem)
    mooseError("No problem available in BlockRestrictable::checkCoordSystem()");
  const auto & subdomains = blockRestricted() ? blockIDs() : meshBlockIDs();
  if (subdomains.empty())
    mooseError("No subdomains found in the problem.");
  // make sure all subdomains are using the same coordinate system
  auto coord_system = _blk_feproblem->getCoordSystem(*subdomains.begin());
  for (auto subdomain : subdomains)
    if (_blk_feproblem->getCoordSystem(subdomain) != coord_system)
      mooseError("This object requires all subdomains to have the same coordinate system.");
  return coord_system;
}
getBoundaryFaceValue()
template<typename OutputType > ADReal MooseVariableFV< OutputType >::getBoundaryFaceValue (const FaceInfo & fi, const StateArg & state, bool correct_skewness = false) const
Retrieve the solution value at a boundary face.
If we're using a one term Taylor series expansion we'll simply return the ajacent element centroid value. If we're doing two terms, then we will compute the gradient if necessary to help us interpolate from the element centroid value to the face
Definition at line 590 of file MooseVariableFV.C.
{
  mooseAssert(!this->isInternalFace(fi),
              "A boundary face value has been requested on an internal face.");
  if (isDirichletBoundaryFace(fi, nullptr, state))
    return getDirichletBoundaryFaceValue(fi, nullptr, state);
  else if (isExtrapolatedBoundaryFace(fi, nullptr, state))
    return getExtrapolatedBoundaryFaceValue(
        fi, _two_term_boundary_expansion, correct_skewness, nullptr, state);
  mooseError("Unknown boundary face type!");
}
Referenced by InterfaceIntegralVariableValuePostprocessor::computeQpIntegral(), SideIntegralVariableUserObject::computeQpIntegral(), FVConstantScalarOutflowBC::computeQpResidual(), and FVTwoVarContinuityConstraint::computeQpResidual().
getCheckedPointerParam()
template<typename T > T MooseBaseParameterInterface::getCheckedPointerParam (const std::string & name, const std::string & error_string = "") const inherited
Verifies that the requested parameter exists and is not NULL and returns it to the caller.
The template parameter must be a pointer or an error will be thrown.
Definition at line 264 of file MooseBaseParameterInterface.h.
{
  return parameters().getCheckedPointerParam<T>(name, error_string);
}
getContinuity()
template<typename OutputType > FEContinuity MooseVariableFV< OutputType >::getContinuity () const inline final override virtual
Return the continuity of this variable.
Reimplemented from MooseVariableBase.
Definition at line 160 of file MooseVariableFV.h.
{ return _element_data->getContinuity(); };
getDataFileName()
std::string DataFileInterface< MooseObject >::getDataFileName (const std::string & param) const inherited
Returns the path of a data file for a given FileName type parameter, searching (in the following order)
relative to the input file directory
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
relative to the input file directory
Definition at line 34 of file DataFileInterface.C.
{
  {
    const auto & absolute_path = _parent.template getParam<FileName>(param);
    if (MooseUtils::checkFileReadable(absolute_path, false, false, false))
    {
      _parent.paramInfo(param, "Data file '", absolute_path, "' found relative to the input file.");
      return absolute_path;
    }
  }
  const auto & relative_path = _parent.parameters().rawParamVal(param);
  return getDataFileNameByName(relative_path, &param);
}
getDataFileNameByName()
std::string DataFileInterface< MooseObject >::getDataFileNameByName (const std::string & name, const std::string * param = nullptr) const inherited
Returns the path of a data file for a given relative file path.
This can be used for hardcoded datafile names and will search the same locations as getDataFileName. The optional param pointer can be used to turn the mooseErrors this function emits into paramErrors
relative to the running binary (assuming the application is installed)
relative to all registered data file directories
Definition at line 42 of file DataFileInterface.C.
{
  const auto share_dir = MooseUtils::pathjoin(Moose::getExecutablePath(), "..", "share");
  if (MooseUtils::pathIsDirectory(share_dir))
  {
    const auto dirs = MooseUtils::listDir(share_dir, false);
    for (const auto & data_dir : dirs)
    {
      const auto path = MooseUtils::pathjoin(data_dir, "data", relative_path);
      if (MooseUtils::checkFileReadable(path, false, false, false))
      {
        if (param)
          _parent.paramInfo(
              *param, "Data file '", path, "' found in an installed app distribution.");
        else
          mooseInfo("Data file '", path, "' found in an installed app distribution.");
        return path;
      }
    }
  }
  for (const auto & data_dir : Registry::getRegistry().getDataFilePaths())
  {
    const auto path = MooseUtils::pathjoin(data_dir, relative_path);
    if (MooseUtils::checkFileReadable(path, false, false, false))
    {
      if (param)
        _parent.paramInfo(*param, "Data file '", path, "' found in a source repository.");
      else
        mooseInfo("Data file '", path, "' found in a source repository.");
      return path;
    }
  }
  mooseException(param ? _parent.parameters().inputLocation(*param) : _parent.name(),
                 ": Unable to find data file '",
                 relative_path,
                 "' anywhere");
}
getDirichletBC()
template<typename OutputType > std::pair< bool, const FVDirichletBCBase * > MooseVariableFV< OutputType >::getDirichletBC (const FaceInfo & fi) const
Definition at line 414 of file MooseVariableFV.C.
{
  if (!_dirichlet_map_setup)
    const_cast<MooseVariableFV<OutputType> *>(this)->determineBoundaryToDirichletBCMap();
  for (const auto bnd_id : fi.boundaryIDs())
    if (auto it = _boundary_id_to_dirichlet_bc.find(bnd_id);
        it != _boundary_id_to_dirichlet_bc.end())
      return {true, it->second};
  return {false, nullptr};
}
Referenced by FVFluxKernel::skipForBoundary().
getDirichletBoundaryFaceValue()
template<typename OutputType > ADReal MooseVariableFV< OutputType >::getDirichletBoundaryFaceValue (const FaceInfo & fi, const Elem * elem, const Moose::StateArg & state) const protected virtual
Retrieves a Dirichlet boundary value for the provided face.
Callers of this method should be sure that isDirichletBoundaryFace returns true. In the base implementation we only inspect the face information object for the Dirichlet value. However, derived classes may allow discontinuities between + and - side face values, e.g. one side may have a Dirichlet condition and the other side may perform extrapolation to determine its value. This is the reason for the existence of the elem parameter, to indicate sidedness
Parameters
fi The face information object
elem An element that can be used to indicate sidedness of the face
state State argument which describes at what time / solution iteration state we want to evaluate the variable
Returns
The Dirichlet value on the boundary face associated with fi (and potentially elem)
Definition at line 505 of file MooseVariableFV.C.
{
  mooseAssert(isDirichletBoundaryFace(fi, elem, state),
              "This function should only be called on Dirichlet boundary faces.");
  mooseAssert(state.state == 0,
              "getDirichletBoundaryFaceValue currently only supports evaluating at the current "
              "time/iteration state");
  const auto & diri_pr = getDirichletBC(fi);
  mooseAssert(diri_pr.first,
              "This functor should only be called if we are on a Dirichlet boundary face.");
  const FVDirichletBCBase & bc = *diri_pr.second;
  return ADReal(bc.boundaryValue(fi));
}
getDofIndices()
template<typename OutputType > virtual void MooseVariableFV< OutputType >::getDofIndices (const Elem * elem, std::vector< dof_id_type > & dof_indices) const inline override virtual
Reimplemented from MooseVariableBase.
Definition at line 178 of file MooseVariableFV.h.
  {
    return _element_data->getDofIndices(elem, dof_indices);
  }
getElementalValue()
template<typename OutputType > MooseVariableFV< OutputType >::OutputData MooseVariableFV< OutputType >::getElementalValue (const Elem * elem, unsigned int idx = 0) const
Get the current value of this variable on an element.
Parameters
[in] elem Element at which to get value
[in] idx Local index of this variable's element DoFs
Returns
Variable value
Definition at line 125 of file MooseVariableFV.C.
{
  return _element_data->getElementalValue(elem, Moose::Current, idx);
}
getElementalValueOld()
template<typename OutputType > MooseVariableFV< OutputType >::OutputData MooseVariableFV< OutputType >::getElementalValueOld (const Elem * elem, unsigned int idx = 0) const
Get the old value of this variable on an element.
Parameters
[in] elem Element at which to get value
[in] idx Local index of this variable's element DoFs
Returns
Variable value
Definition at line 132 of file MooseVariableFV.C.
{
  return _element_data->getElementalValue(elem, Moose::Old, idx);
}
getElementalValueOlder()
template<typename OutputType > MooseVariableFV< OutputType >::OutputData MooseVariableFV< OutputType >::getElementalValueOlder (const Elem * elem, unsigned int idx = 0) const
Get the older value of this variable on an element.
Parameters
[in] elem Element at which to get value
[in] idx Local index of this variable's element DoFs
Returns
Variable value
Definition at line 139 of file MooseVariableFV.C.
{
  return _element_data->getElementalValue(elem, Moose::Older, idx);
}
getElemValue()
template<typename OutputType > ADReal MooseVariableFV< OutputType >::getElemValue (const Elem * elem, const StateArg & state) const
Get the solution value for the provided element and seed the derivative for the corresponding dof index.
Parameters
elem The element to retrieive the solution value for
state State argument which describes at what time / solution iteration state we want to evaluate the variable
Definition at line 453 of file MooseVariableFV.C.
{
  mooseAssert(elem,
              "The elem shall exist! This typically occurs when the "
              "user wants to evaluate non-existing elements (nullptr) at physical boundaries.");
  mooseAssert(
      this->hasBlocks(elem->subdomain_id()),
      "The variable should be defined on the element's subdomain! This typically occurs when the "
      "user wants to evaluate the elements right next to the boundary of two variables (block "
      "boundary). The subdomain which is queried: " +
          Moose::stringify(this->activeSubdomains()) + " the subdomain of the element " +
          std::to_string(elem->subdomain_id()));
  Moose::initDofIndices(const_cast<MooseVariableFV<OutputType> &>(*this), *elem);
  mooseAssert(
      this->_dof_indices.size() == 1,
      "There should only be one dof-index for a constant monomial variable on any given element");
  const dof_id_type index = this->_dof_indices[0];
  // It's not safe to use solutionState(0) because it returns the libMesh System solution member
  // which is wrong during things like finite difference Jacobian evaluation, e.g. when PETSc
  // perturbs the solution vector we feed these perturbations into the current_local_solution
  // while the libMesh solution is frozen in the non-perturbed state
  const auto & global_soln = (state.state == 0)
                                 ? *this->_sys.currentSolution()
                                 : this->_sys.solutionState(state.state, state.iteration_type);
  ADReal value = global_soln(index);
  if (ADReal::do_derivatives && state.state == 0 &&
      this->_sys.number() == this->_subproblem.currentNlSysNum())
    Moose::derivInsert(value.derivatives(), index, 1.);
  return value;
}
Referenced by FVDiffusionInterface::computeQpResidual(), and MooseVariableFV< OutputType >::evaluate().
getExecuteOnEnum()
const ExecFlagEnum & SetupInterface::getExecuteOnEnum () const inherited
Return the execute on MultiMooseEnum for this object.
Definition at line 65 of file SetupInterface.C.
{
  return _execute_enum;
}
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), MultiAppTransfer::checkMultiAppExecuteOn(), IntegralPreservingFunctionIC::initialSetup(), MultiAppConservativeTransfer::initialSetup(), Terminator::initialSetup(), ElementReporter::shouldStore(), GeneralReporter::shouldStore(), and NodalReporter::shouldStore().
getExtrapolatedBoundaryFaceValue()
template<typename OutputType > ADReal MooseVariableFV< OutputType >::getExtrapolatedBoundaryFaceValue (const FaceInfo & fi, bool two_term_expansion, bool correct_skewness, const Elem * elem_side_to_extrapolate_from, const StateArg & state) const virtual
Retrieves an extrapolated boundary value for the provided face.
Callers of this method should be sure that isExtrapolatedBoundaryFace returns true. In the base implementation we only inspect the face information object for the extrapolated value. However, derived classes may allow discontinuities between + and - side face values, e.g. one side may have a Dirichlet condition and the other side may perform extrapolation to determine its value. This is the reason for the existence of the elem parameter, to indicate sidedness
Parameters
fi The face information object
two_term_expansion Whether to use the cell gradient in addition to the cell center value to compute the extrapolated boundary face value. If this is false, then the cell center value will be used
correct_skewness Whether to perform skew corrections. This is relevant when performing two term expansions as the gradient evaluation may involve evaluating face values on internal skewed faces
elem_side_to_extrapolate_from An element that can be used to indicate sidedness of the face
state State argument which describes at what time / solution iteration state we want to evaluate the variable
Returns
The extrapolated value on the boundary face associated with fi (and potentially elem_side_to_extrapolate_from)
Definition at line 540 of file MooseVariableFV.C.
{
  mooseAssert(
      isExtrapolatedBoundaryFace(fi, elem_to_extrapolate_from, state) || !two_term_expansion,
      "We allow Dirichlet boundary conditions to call this method. However, the only way to "
      "ensure we don't have infinite recursion, with Green Gauss gradients calling back to the "
      "Dirichlet boundary condition calling back to this method, is to do a one term expansion");
  ADReal boundary_value;
  bool elem_to_extrapolate_from_is_fi_elem;
  std::tie(elem_to_extrapolate_from, elem_to_extrapolate_from_is_fi_elem) =
      [this, &fi, elem_to_extrapolate_from]() -> std::pair<const Elem *, bool>
  {
    if (elem_to_extrapolate_from)
      // Somebody already specified the element to extropolate from
      return {elem_to_extrapolate_from, elem_to_extrapolate_from == fi.elemPtr()};
    else
    {
      const auto [elem_guaranteed_to_have_dofs,
                  other_elem,
                  elem_guaranteed_to_have_dofs_is_fi_elem] =
          Moose::FV::determineElemOneAndTwo(fi, *this);
      // We only care about the element guaranteed to have degrees of freedom and current C++
      // doesn't allow us to not assign one of the returned items like python does
      libmesh_ignore(other_elem);
      // We will extrapolate from the element guaranteed to have degrees of freedom
      return {elem_guaranteed_to_have_dofs, elem_guaranteed_to_have_dofs_is_fi_elem};
    }
  }();
  if (two_term_expansion)
  {
    const Point vector_to_face = elem_to_extrapolate_from_is_fi_elem
                                     ? (fi.faceCentroid() - fi.elemCentroid())
                                     : (fi.faceCentroid() - fi.neighborCentroid());
    boundary_value = adGradSln(elem_to_extrapolate_from, state, correct_skewness) * vector_to_face +
                     getElemValue(elem_to_extrapolate_from, state);
  }
  else
    boundary_value = getElemValue(elem_to_extrapolate_from, state);
  return boundary_value;
}
getFluxBCs()
template<typename OutputType > std::pair< bool, std::vector< const FVFluxBC * > > MooseVariableFV< OutputType >::getFluxBCs (const FaceInfo & fi) const
Definition at line 429 of file MooseVariableFV.C.
{
  std::vector<const FVFluxBC *> bcs;
  this->_subproblem.getMooseApp()
      .theWarehouse()
      .query()
      .template condition<AttribSystem>("FVFluxBC")
      .template condition<AttribThread>(_tid)
      .template condition<AttribBoundaries>(fi.boundaryIDs())
      .template condition<AttribVar>(_var_num)
      .template condition<AttribSysNum>(this->_sys.number())
      .queryInto(bcs);
  bool has_flux_bc = bcs.size() > 0;
  if (has_flux_bc)
    return std::make_pair(true, bcs);
  else
    return std::make_pair(false, std::vector<const FVFluxBC *>());
}
Referenced by FVFluxKernel::skipForBoundary().
getGradient()
template<typename OutputType > OutputTools< OutputType >::OutputGradient MooseVariableFV< OutputType >::getGradient (const Elem * elem) const
Compute the variable gradient value at a point on an element.
Parameters
elem The element we are computing on
phi Evaluated shape functions at a point
Returns
The variable gradient value
Definition at line 372 of file MooseVariableFV.C.
{
  return {};
}
getMooseApp()
MooseApp & MooseBase::getMooseApp () const inline inherited
Get the MooseApp this class is associated with.
Definition at line 35 of file MooseBase.h.
{ return _app; }
Referenced by ReporterTransferInterface::checkHasReporterValue(), Coupleable::checkWritableVar(), MooseBaseParameterInterface::connectControllableParams(), Coupleable::Coupleable(), MortarData::createMortarInterface(), EigenProblem::doFreeNonlinearPowerIterations(), Terminator::execute(), FEProblemSolve::FEProblemSolve(), SolutionInvalidInterface::flagInvalidSolutionInternal(), MaterialPropertyInterface::MaterialPropertyInterface(), MooseVariableDataFV< OutputType >::MooseVariableDataFV(), ProgressOutput::output(), MooseBaseParameterInterface::paramError(), PetscOutputInterface::petscLinearOutput(), PetscOutputInterface::petscNonlinearOutput(), PetscOutputInterface::PetscOutputInterface(), PostprocessorInterface::postprocessorsAdded(), MultiApp::preTransfer(), Reporter::Reporter(), ReporterInterface::reportersAdded(), and VectorPostprocessorInterface::vectorPostprocessorsAdded().
getOutputs()
const std::set< OutputName > & OutputInterface::getOutputs () inherited
Get the list of output objects that this class is restricted.
Returns
A set of OutputNames
Definition at line 94 of file OutputInterface.C.
{
  return _oi_outputs;
}
getParam() [1/2]
template<typename T > const T & MooseBaseParameterInterface::getParam (const std::string & name) const inherited
Retrieve a parameter for the object.
Parameters
name The name of the parameter
Returns
The value of the parameter
Definition at line 200 of file MooseBaseParameterInterface.h.
{
  return InputParameters::getParamHelper(name, _pars, static_cast<T *>(0));
}
Referenced by AddGeneralReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddPeriodicBCAction::act(), CreateDisplacedProblemAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), ConstraintWarehouse::addObject(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), ADNodalKernel::ADNodalKernel(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), PiecewiseTabularBase::buildFromJSON(), Console::Console(), FEProblemBase::createTagSolutions(), AccumulateReporter::declareLateValues(), DerivativeParsedMaterialTempl< is_ad >::DerivativeParsedMaterialTempl(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EigenKernel::EigenKernel(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakMeshByBlockGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), GenericConstantRankTwoTensorTempl< is_ad >::GenericConstantRankTwoTensorTempl(), MooseApp::getCheckpointDirectories(), ExecutorInterface::getExecutor(), AdvancedOutput::init(), IterationAdaptiveDT::init(), TimeSequenceStepper::init(), AttribThread::initFrom(), AttribSysNum::initFrom(), AttribResidualObject::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), Console::initialSetup(), IterationAdaptiveDT::limitDTToPostprocessorValue(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MortarConsumerInterface::MortarConsumerInterface(), NestedDivision::NestedDivision(), ConsoleUtils::outputExecutionInformation(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedMaterialTempl< is_ad >::ParsedMaterialTempl(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), ParsedODEKernel::ParsedODEKernel(), ParsedPostprocessor::ParsedPostprocessor(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), PiecewiseConstantByBlockMaterialTempl< is_ad >::PiecewiseConstantByBlockMaterialTempl(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), Moose::FV::setInterpolationMethod(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), TimePeriod::TimePeriod(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and VectorOfPostprocessors::VectorOfPostprocessors().
getParam() [2/2]
template<typename T1 , typename T2 > std::vector< std::pair< T1, T2 > > MooseBaseParameterInterface::getParam (const std::string & param1, const std::string & param2) const inherited
Retrieve two parameters and provide pair of parameters for the object.
Parameters
param1 The name of first parameter
param2 The name of second parameter
Returns
Vector of pairs of first and second parameters
Definition at line 257 of file MooseBaseParameterInterface.h.
{
  return _pars.get<T1, T2>(param1, param2);
}
getRenamedParam()
template<typename T > const T & MooseBaseParameterInterface::getRenamedParam (const std::string & old_name, const std::string & new_name) const inherited
Retrieve a renamed parameter for the object.
This helper makes sure we check both names before erroring, and that only one parameter is passed to avoid silent errors
Parameters
old_name the old name for the parameter
new_name the new name for the parameter
Definition at line 207 of file MooseBaseParameterInterface.h.
{
  // this enables having a default on the new parameter but bypassing it with the old one
  // Most important: accept new parameter
  if (isParamSetByUser(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Second most: accept old parameter
  else if (isParamValid(old_name) && !isParamSetByUser(new_name))
    return InputParameters::getParamHelper(old_name, _pars, static_cast<T *>(0));
  // Third most: accept default for new parameter
  else if (isParamValid(new_name) && !isParamValid(old_name))
    return InputParameters::getParamHelper(new_name, _pars, static_cast<T *>(0));
  // Refuse: no default, no value passed
  else if (!isParamValid(old_name) && !isParamValid(new_name))
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' is being retrieved without being set.\n"
               "Did you misspell it?");
  // Refuse: both old and new parameters set by user
  else
    mooseError(_pars.blockFullpath() + ": parameter '" + new_name +
               "' may not be provided alongside former parameter '" + old_name + "'");
}
getSolution()
template<typename OutputType > const NumericVector< Number > & MooseVariableField< OutputType >::getSolution (const Moose::StateArg & state) const protected inherited
Get the solution corresponding to the provided state.
Definition at line 60 of file MooseVariableField.C.
{
  // It's not safe to use solutionState(0) because it returns the libMesh System solution member
  // which is wrong during things like finite difference Jacobian evaluation, e.g. when PETSc
  // perturbs the solution vector we feed these perturbations into the current_local_solution
  // while the libMesh solution is frozen in the non-perturbed state
  return (state.state == 0) ? *this->_sys.currentSolution()
                            : this->_sys.solutionState(state.state, state.iteration_type);
}
getValue()
template<typename OutputType > OutputType MooseVariableFV< OutputType >::getValue (const Elem * elem) const
Note: const monomial is always the case - higher order solns are reconstructed - so this is simpler func than FE equivalent.
Definition at line 362 of file MooseVariableFV.C.
{
  Moose::initDofIndices(const_cast<MooseVariableFV<OutputType> &>(*this), *elem);
  mooseAssert(this->_dof_indices.size() == 1, "Wrong size for dof indices");
  OutputType value = (*this->_sys.currentSolution())(this->_dof_indices[0]);
  return value;
}
gradDot() [1/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluateGradDot overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 123 of file MooseFunctor.h.
{
  return evaluateGradDot(elem, state);
}
gradDot() [2/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 127 of file MooseFunctor.h.
{
  return evaluateGradDot(elem_point, state);
}
gradDot() [3/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 125 of file MooseFunctor.h.
{
  return evaluateGradDot(elem_qp, state);
}
gradDot() [4/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 126 of file MooseFunctor.h.
{
  return evaluateGradDot(elem_side_qp, state);
}
gradDot() [5/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const FaceArg & face, const StateArg & state) const inherited
Definition at line 124 of file MooseFunctor.h.
{
  return evaluateGradDot(checkFace(face), state);
}
gradDot() [6/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradDot (const NodeArg & node, const StateArg & state) const inherited
Definition at line 128 of file MooseFunctor.h.
{
  return evaluateGradDot(node, state);
}
gradient() [1/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluateGradient overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 97 of file MooseFunctor.h.
{
  return evaluateGradient(elem, state);
}
gradient() [2/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 101 of file MooseFunctor.h.
{
  return evaluateGradient(elem_point, state);
}
gradient() [3/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 99 of file MooseFunctor.h.
{
  return evaluateGradient(elem_qp, state);
}
gradient() [4/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 100 of file MooseFunctor.h.
{
  return evaluateGradient(elem_side_qp, state);
}
gradient() [5/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const FaceArg & face, const StateArg & state) const inherited
Definition at line 98 of file MooseFunctor.h.
{
  return evaluateGradient(checkFace(face), state);
}
gradient() [6/6]
FunctorBase< Moose::ADType< OutputType >::type >::GradientType Moose::FunctorBase< Moose::ADType< OutputType >::type >::gradient (const NodeArg & node, const StateArg & state) const inherited
Definition at line 102 of file MooseFunctor.h.
{
  return evaluateGradient(node, state);
}
gradPhi()
template<typename OutputType > const FieldVariablePhiGradient & MooseVariableFV< OutputType >::gradPhi () const inline final override virtual
Return the gradients of the variable's elemental shape functions.
Implements MooseVariableField< OutputType >.
Definition at line 574 of file MooseVariableFV.h.
{ return _grad_phi; }
gradPhiFace()
template<typename OutputType > const FieldVariablePhiGradient & MooseVariableFV< OutputType >::gradPhiFace () const inline final override virtual
Return the gradients of the variable's shape functions on an element face.
Implements MooseVariableField< OutputType >.
Definition at line 589 of file MooseVariableFV.h.
{ return _grad_phi_face; }
gradPhiFaceNeighbor()
template<typename OutputType > const FieldVariablePhiGradient & MooseVariableFV< OutputType >::gradPhiFaceNeighbor () const inline final override virtual
Return the gradients of the variable's shape functions on a neighboring element face.
Implements MooseVariableField< OutputType >.
Definition at line 599 of file MooseVariableFV.h.
  {
    return _grad_phi_face_neighbor;
  }
gradPhiNeighbor()
template<typename OutputType > const FieldVariablePhiGradient & MooseVariableFV< OutputType >::gradPhiNeighbor () const inline final override virtual
Return the gradients of the variable's shape functions on a neighboring element.
Implements MooseVariableField< OutputType >.
Definition at line 609 of file MooseVariableFV.h.
  {
    return _grad_phi_neighbor;
  }
gradSln()
template<typename OutputType > const FieldVariableGradient & MooseVariableFV< OutputType >::gradSln () const inline override virtual
element gradients
Implements MooseVariableField< OutputType >.
Definition at line 227 of file MooseVariableFV.h.
  {
    return _element_data->gradSln(Moose::Current);
  }
gradSlnNeighbor()
template<typename OutputType > const FieldVariableGradient & MooseVariableFV< OutputType >::gradSlnNeighbor () const inline override virtual
neighbor solution gradients
Implements MooseVariableField< OutputType >.
Definition at line 244 of file MooseVariableFV.h.
  {
    return _neighbor_data->gradSln(Moose::Current);
  }
gradSlnOld()
template<typename OutputType > const FieldVariableGradient & MooseVariableFV< OutputType >::gradSlnOld () const inline override virtual
Implements MooseVariableField< OutputType >.
Definition at line 231 of file MooseVariableFV.h.
  {
    return _element_data->gradSln(Moose::Old);
  }
gradSlnOldNeighbor()
template<typename OutputType > const FieldVariableGradient & MooseVariableFV< OutputType >::gradSlnOldNeighbor () const inline override virtual
Implements MooseVariableField< OutputType >.
Definition at line 248 of file MooseVariableFV.h.
  {
    return _neighbor_data->gradSln(Moose::Old);
  }
hasBlockMaterialProperty()
template<typename T , bool is_ad> bool BlockRestrictable::hasBlockMaterialProperty (const std::string & prop_name) inherited
Check if a material property is valid for all blocks of this object.
This method returns true if the supplied property name has been declared in a Material object on the block ids for this object.
Template Parameters
T The type of material property
Parameters
prop_name the name of the property to query
Returns
true if the property exists for all block ids of the object, otherwise false
See also
Material::hasBlockMaterialProperty
Definition at line 264 of file BlockRestrictable.h.
{
  mooseAssert(_blk_material_data != NULL, "MaterialData pointer is not defined");
  return hasBlockMaterialPropertyHelper(prop_name) &&
         _blk_material_data->haveGenericProperty<T, is_ad>(prop_name);
}
hasBlockMaterialPropertyHelper()
bool BlockRestrictable::hasBlockMaterialPropertyHelper (const std::string & prop_name) protected virtual inherited
A helper method to allow the Material object to specialize the behavior of hasBlockMaterialProperty.
It also avoid circular #include problems.
See also
hasBlockMaterialProperty
Definition at line 275 of file BlockRestrictable.C.
{
  // Reference to MaterialWarehouse for testing and retrieving block ids
  const MaterialWarehouse & warehouse = _blk_feproblem->getMaterialWarehouse();
  // Complete set of ids that this object is active
  const std::set<SubdomainID> & ids = blockRestricted() ? blockIDs() : meshBlockIDs();
  // Loop over each id for this object
  for (const auto & id : ids)
  {
    // Storage of material properties that have been DECLARED on this id
    std::set<std::string> declared_props;
    // If block materials exist, populated the set of properties that were declared
    if (warehouse.hasActiveBlockObjects(id))
    {
      const std::vector<std::shared_ptr<MaterialBase>> & mats = warehouse.getActiveBlockObjects(id);
      for (const auto & mat : mats)
      {
        const std::set<std::string> & mat_props = mat->getSuppliedItems();
        declared_props.insert(mat_props.begin(), mat_props.end());
      }
    }
    // If the supplied property is not in the list of properties on the current id, return false
    if (declared_props.find(prop_name) == declared_props.end())
      return false;
  }
  // If you get here the supplied property is defined on all blocks
  return true;
}
Referenced by BlockRestrictable::hasBlockMaterialProperty().
hasBlocks() [1/5]
bool BlockRestrictable::hasBlocks (const std::set< SubdomainID > & ids) const inherited
Test if the supplied set of block ids are valid for this object.
Parameters
ids A std::set of SubdomainIDs to check
Returns
True if all of the given ids are found within the ids for this object
See also
isSubset
Definition at line 237 of file BlockRestrictable.C.
{
  if (_blk_ids.empty() || _blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return true;
  else
    return std::includes(_blk_ids.begin(), _blk_ids.end(), ids.begin(), ids.end());
}
hasBlocks() [2/5]
bool BlockRestrictable::hasBlocks (const std::vector< SubdomainID > & ids) const inherited
Test if the supplied vector block ids are valid for this object.
Parameters
ids A vector of SubdomainIDs ids to check
Returns
True if all of the given ids are found within the ids for this object
Definition at line 230 of file BlockRestrictable.C.
{
  std::set<SubdomainID> ids_set(ids.begin(), ids.end());
  return hasBlocks(ids_set);
}
hasBlocks() [3/5]
bool BlockRestrictable::hasBlocks (const std::vector< SubdomainName > & names) const inherited
Test if the supplied vector of block names are valid for this object.
Parameters
names A vector of SubdomainNames to check
Returns
True if the given ids are valid for this object
Definition at line 215 of file BlockRestrictable.C.
{
  return hasBlocks(_blk_mesh->getSubdomainIDs(names));
}
hasBlocks() [4/5]
template<typename OutputType > bool MooseVariableField< OutputType >::hasBlocks (const SubdomainID) const inline override virtual inherited
Returns whether the functor is defined on this block.
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 370 of file MooseVariableField.h.
{ return BlockRestrictable::hasBlocks(id); }
Referenced by Coupleable::checkWritableVar(), GradientJumpIndicator::computeQpIntegral(), ProjectionAux::computeValue(), Moose::FV::determineElemOneAndTwo(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), and FVInterfaceKernel::FVInterfaceKernel().
hasBlocks() [5/5]
bool BlockRestrictable::hasBlocks (const SubdomainName & name) const inherited
Test if the supplied block name is valid for this object.
Parameters
name A SubdomainName to check
Returns
True if the given id is valid for this object
Definition at line 205 of file BlockRestrictable.C.
{
  // Create a vector and utilize the getSubdomainIDs function, which
  // handles the ANY_BLOCK_ID (getSubdomainID does not)
  std::vector<SubdomainName> names(1);
  names[0] = name;
  return hasBlocks(_blk_mesh->getSubdomainIDs(names));
}
Referenced by DiracKernelBase::addPoint(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), DomainUserObject::checkVariable(), ComputeJacobianThread::compute(), DomainUserObject::DomainUserObject(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), ExtraIDIntegralVectorPostprocessor::execute(), MeshDivisionFunctorReductionVectorPostprocessor::execute(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), MooseVariableField< OutputType >::hasBlocks(), BlockRestrictable::hasBlocks(), FVFluxKernel::hasFaceSide(), and PointwiseRenormalizeVector::PointwiseRenormalizeVector().
hasDirichletBC()
template<typename OutputType > bool MooseVariableFV< OutputType >::hasDirichletBC () const inline
Returns true if a Dirichlet BC exists on the current face.
This only works if the variable has been initialized on a face with computeFaceValues. Its return value is nonsense if initialized on a single element via computeElemValues.
Definition at line 444 of file MooseVariableFV.h.
  {
    return _element_data->hasDirichletBC() || _neighbor_data->hasDirichletBC();
  }
hasDoFsOnNodes()
template<typename OutputType > bool MooseVariableFV< OutputType >::hasDoFsOnNodes () const inline final override virtual
Does this variable have DoFs on nodes.
Returns
true if it does, false if not.
Reimplemented from MooseVariableBase.
Definition at line 158 of file MooseVariableFV.h.
{ return false; }
hasFaceSide()
bool Moose::FunctorBase< Moose::ADType< OutputType >::type >::hasFaceSide (const FaceInfo & fi, const bool fi_elem_side) const override virtual inherited
Implements FaceArgInterface.
Definition at line 169 of file MooseFunctor.h.
{
  if (fi_elem_side)
    return hasBlocks(fi.elem().subdomain_id());
  else
    return fi.neighborPtr() && hasBlocks(fi.neighbor().subdomain_id());
}
initializeBlockRestrictable()
void BlockRestrictable::initializeBlockRestrictable (const MooseObject * moose_object) protected inherited
An initialization routine needed for dual constructors.
Definition at line 74 of file BlockRestrictable.C.
{
  // If the mesh pointer is not defined, but FEProblemBase is, get it from there
  if (_blk_feproblem != NULL && _blk_mesh == NULL)
    _blk_mesh = &_blk_feproblem->mesh();
  // Check that the mesh pointer was defined, it is required for this class to operate
  if (_blk_mesh == NULL)
    mooseError("The input parameters must contain a pointer to FEProblem via '_fe_problem' or a "
               "pointer to the MooseMesh via '_mesh'");
  // Populate the MaterialData pointer
  if (_blk_feproblem != NULL)
    _blk_material_data = &_blk_feproblem->getMaterialData(Moose::BLOCK_MATERIAL_DATA, _blk_tid);
  // The 'block' input is defined
  if (moose_object->isParamValid("block"))
  {
    // Extract the blocks from the input
    _blocks = moose_object->getParam<std::vector<SubdomainName>>("block");
    // Store the IDs in a set, handling ANY_BLOCK_ID if supplied
    if (std::find(_blocks.begin(), _blocks.end(), "ANY_BLOCK_ID") != _blocks.end())
      _blk_ids.insert(Moose::ANY_BLOCK_ID);
    else
    {
      // Get the IDs from the supplied names
      _vec_ids = _blk_mesh->getSubdomainIDs(_blocks);
      _blk_ids.insert(_vec_ids.begin(), _vec_ids.end());
    }
  }
  // When 'blocks' is not set and there is a "variable", use the blocks from the variable
  else if (moose_object->isParamValid("variable"))
  {
    std::string variable_name = moose_object->parameters().getMooseType("variable");
    if (!variable_name.empty())
      _blk_ids = _blk_feproblem
                     ->getVariable(_blk_tid,
                                   variable_name,
                                   Moose::VarKindType::VAR_ANY,
                                   Moose::VarFieldType::VAR_FIELD_ANY)
                     .activeSubdomains();
  }
  // Produce error if the object is not allowed to be both block and boundary restricted
  if (!_blk_dual_restrictable && !_boundary_ids.empty() && !_boundary_ids.empty())
    if (!_boundary_ids.empty() && _boundary_ids.find(Moose::ANY_BOUNDARY_ID) == _boundary_ids.end())
      moose_object->paramError("block",
                               "Attempted to restrict the object '",
                               _blk_name,
                               "' to a block, but the object is already restricted by boundary");
  // If no blocks were defined above, specify that it is valid on all blocks
  if (_blk_ids.empty() && !moose_object->isParamValid("boundary"))
  {
    _blk_ids.insert(Moose::ANY_BLOCK_ID);
    _blocks = {"ANY_BLOCK_ID"};
  }
  // If this object is block restricted, check that defined blocks exist on the mesh
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) == _blk_ids.end())
  {
    const std::set<SubdomainID> & valid_ids = _blk_mesh->meshSubdomains();
    std::vector<SubdomainID> diff;
    std::set_difference(_blk_ids.begin(),
                        _blk_ids.end(),
                        valid_ids.begin(),
                        valid_ids.end(),
                        std::back_inserter(diff));
    if (!diff.empty())
    {
      std::ostringstream msg;
      auto sep = " ";
      msg << "the following blocks (ids) do not exist on the mesh:";
      for (const auto & id : diff)
      {
        if (_blk_name.size() > 0)
        {
          auto & name =
              _blocks.at(std::find(_vec_ids.begin(), _vec_ids.end(), id) - _vec_ids.begin());
          if (std::to_string(id) != name)
            msg << sep << name << " (" << id << ")";
          else
            msg << sep << id;
        }
        else
          msg << sep << id;
        sep = ", ";
      }
      moose_object->paramError("block", msg.str());
    }
  }
  // Get the mesh dimension for the blocks
  if (blockRestricted())
    _blk_dim = _blk_mesh->getBlocksMaxDimension(_blocks);
  else
    _blk_dim = _blk_mesh->dimension();
}
Referenced by BlockRestrictable::BlockRestrictable().
initialSetup()
void MooseVariableBase::initialSetup () override virtual inherited
Gets called at the beginning of the simulation before this object is asked to do its job.
Reimplemented from SetupInterface.
Definition at line 187 of file MooseVariableBase.C.
{
  // Currently the scaling vector is only used through AD residual computing objects
  if (_subproblem.haveADObjects() &&
      (_subproblem.automaticScaling() || (std::find_if(_scaling_factor.begin(),
                                                       _scaling_factor.end(),
                                                       [](const Real element) {
                                                         return !MooseUtils::absoluteFuzzyEqual(
                                                             element, 1.);
                                                       }) != _scaling_factor.end())))
    _sys.addScalingVector();
}
insert()
template<typename OutputType > void MooseVariableFV< OutputType >::insert (NumericVector< Number > & residual) override virtual
Implements MooseVariableFieldBase.
Definition at line 146 of file MooseVariableFV.C.
{
  _element_data->insert(residual);
}
isArray()
template<typename OutputType > bool MooseVariableFV< OutputType >::isArray () const override virtual
Returns
true if this is an array variable, false otherwise.
Implements MooseVariableFieldBase.
Definition at line 400 of file MooseVariableFV.C.
{
  return std::is_same<OutputType, RealEigenVector>::value;
}
isBlockSubset() [1/2]
bool BlockRestrictable::isBlockSubset (const std::set< SubdomainID > & ids) const inherited
Test if the class block ids are a subset of the supplied objects.
Parameters
ids A std::set of Subdomains to check
Returns
True if all of the block ids for this class are found within the given ids (opposite of hasBlocks)
See also
hasBlocks
Definition at line 246 of file BlockRestrictable.C.
{
  // An empty input is assumed to be ANY_BLOCK_ID
  if (ids.empty() || ids.find(Moose::ANY_BLOCK_ID) != ids.end())
    return true;
  if (_blk_ids.find(Moose::ANY_BLOCK_ID) != _blk_ids.end())
    return std::includes(ids.begin(),
                         ids.end(),
                         _blk_mesh->meshSubdomains().begin(),
                         _blk_mesh->meshSubdomains().end());
  else
    return std::includes(ids.begin(), ids.end(), _blk_ids.begin(), _blk_ids.end());
}
Referenced by BlockRestrictable::checkVariable(), BlockRestrictable::isBlockSubset(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), and ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux().
isBlockSubset() [2/2]
bool BlockRestrictable::isBlockSubset (const std::vector< SubdomainID > & ids) const inherited
Test if the class block ids are a subset of the supplied objects.
Parameters
ids A std::vector of Subdomains to check
Returns
True if all of the block ids for this class are found within the given ids (opposite of hasBlocks)
See also
hasBlocks
Definition at line 262 of file BlockRestrictable.C.
{
  std::set<SubdomainID> ids_set(ids.begin(), ids.end());
  return isBlockSubset(ids_set);
}
isConstant()
virtual bool Moose::FunctorBase< Moose::ADType< OutputType >::type >::isConstant () const inline virtual inherited
Returns true if this functor is a constant.
Definition at line 167 of file MooseFunctor.h.
{ return false; }
isDirichletBoundaryFace()
template<typename OutputType > bool MooseVariableFV< OutputType >::isDirichletBoundaryFace (const FaceInfo & fi, const Elem * elem, const Moose::StateArg & state) const virtual
Determine whether a specified face side is a Dirichlet boundary face.
In the base implementation we only inspect the face information object for whether there are Dirichlet conditions. However, derived classes may allow discontinuities between + and - side face values, e.g. one side may have a Dirichlet condition and the other side may perform extrapolation to determine its value
Parameters
fi The face information object
elem An element that can be used to indicate sidedness of the face
state The state at which to determine whether the face is a Dirichlet face or not
Returns
Whether the potentially sided (as indicated by elem) fi is a Dirichlet boundary face for this variable
Definition at line 493 of file MooseVariableFV.C.
{
  const auto & pr = getDirichletBC(fi);
  // First member of this pair indicates whether we have a DirichletBC
  return pr.first;
}
isExtrapolatedBoundaryFace()
template<typename OutputType > bool MooseVariableFV< OutputType >::isExtrapolatedBoundaryFace (const FaceInfo & fi, const Elem * elem, const Moose::StateArg & state) const override protected virtual
Returns whether this is an extrapolated boundary face.
An extrapolated boundary face is boundary face for which is not a corresponding Dirichlet condition, e.g. we need to compute some approximation for the boundary face value using the adjacent cell centroid information. In the base implementation we only inspect the face information object for whether we should perform extrapolation. However, derived classes may allow discontinuities between + and - side face values, e.g. one side may have a Dirichlet condition and the other side may perform extrapolation to determine its value
Parameters
fi The face information object
elem An element that can be used to indicate sidedness of the face
state The state at which to determine whether the face is extrapolated or not
Returns
Whether the potentially sided (as indicated by elem) fi is an extrapolated boundary face for this variable
Reimplemented from Moose::FunctorBase< Moose::ADType< OutputType >::type >.
Definition at line 528 of file MooseVariableFV.C.
{
  if (isDirichletBoundaryFace(fi, elem, state))
    return false;
  else
    return !this->isInternalFace(fi);
}
isFV()
template<typename OutputType > virtual bool MooseVariableFV< OutputType >::isFV () const inline override virtual
Reimplemented from MooseVariableFieldBase.
Definition at line 94 of file MooseVariableFV.h.
{ return true; }
isInternalFace()
bool Moose::FunctorBase< Moose::ADType< OutputType >::type >::isInternalFace (const FaceInfo & fi) const inherited
Returns true if the face is an internal face.
Definition at line 162 of file MooseFunctor.h.
{
  if (!fi.neighborPtr())
    return false;
  return hasBlocks(fi.elem().subdomain_id()) && hasBlocks(fi.neighborPtr()->subdomain_id());
}
isNodal()
template<typename OutputType > virtual bool MooseVariableFV< OutputType >::isNodal () const inline final override virtual
Is this variable nodal.
Returns
true if it nodal, otherwise false
Reimplemented from MooseVariableBase.
Definition at line 156 of file MooseVariableFV.h.
{ return false; }
isNodalDefined()
template<typename OutputType > virtual bool MooseVariableFV< OutputType >::isNodalDefined () const inline final override virtual
Is this variable defined at nodes.
Returns
true if it the variable is defined at nodes, otherwise false
Implements MooseVariableFieldBase.
Definition at line 162 of file MooseVariableFV.h.
{ return false; }
isParamSetByUser()
bool MooseBaseParameterInterface::isParamSetByUser (const std::string & nm) const inline inherited
Test if the supplied parameter is set by a user, as opposed to not set or set to default.
Parameters
nm The name of the parameter to test
Definition at line 108 of file MooseBaseParameterInterface.h.
{ return _pars.isParamSetByUser(nm); }
Referenced by SetAdaptivityOptionsAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), LibtorchNeuralNetControl::conditionalParameterError(), MooseBaseParameterInterface::getRenamedParam(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), PiecewiseTabularBase::PiecewiseTabularBase(), MooseMesh::prepare(), and SolutionUserObject::readXda().
isParamValid()
bool MooseBaseParameterInterface::isParamValid (const std::string & name) const inline inherited
Test if the supplied parameter is valid.
Parameters
name The name of the parameter to test
Definition at line 102 of file MooseBaseParameterInterface.h.
{ return _pars.isParamValid(name); }
Referenced by AddDriftDiffusionAction::act(), AddSpecies::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CopyNodalVarsAction::act(), CreateDisplacedProblemAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), AddGeneralReactions::AddGeneralReactions(), AddZapdosReactions::AddZapdosReactions(), AdvectiveFluxAux::AdvectiveFluxAux(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), AddPeriodicBCAction::autoTranslationBoundaries(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), GeneratedMesh::buildMesh(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), ChemicalReactionsBase::ChemicalReactionsBase(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), CombinerGenerator::CombinerGenerator(), CSVReader::CSVReader(), ConstantReporter::declareConstantReporterValues(), DGKernelBase::DGKernelBase(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), EEDFEnergyTownsendLog::EEDFEnergyTownsendLog(), Eigenvalue::Eigenvalue(), ElectronEnergyTermRate::ElectronEnergyTermRate(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), PIDTransientControl::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), Exodus::Exodus(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FEProblemSolve::FEProblemSolve(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FileOutput::FileOutput(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FunctionDT::FunctionDT(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FVInterfaceKernel::FVInterfaceKernel(), BlockDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshExtruderGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getRenamedParam(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), Terminator::handleMessage(), HeavySpeciesTempl< is_ad >::HeavySpeciesTempl(), HFEMDirichletBC::HFEMDirichletBC(), EigenExecutionerBase::init(), Eigenvalue::init(), IterationAdaptiveDT::init(), AdvancedOutput::initExecutionTypes(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), MooseParsedFunction::initialSetup(), MooseParsedGradFunction::initialSetup(), MooseParsedVectorFunction::initialSetup(), PiecewiseTabularBase::initialSetup(), SolutionFunction::initialSetup(), Console::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSampleTransfer::initialSetup(), IterationAdaptiveDT::IterationAdaptiveDT(), LeastSquaresFit::LeastSquaresFit(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MatCoupledForce::MatCoupledForce(), MooseMesh::MooseMesh(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarConsumerInterface::MortarConsumerInterface(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalExtremeValue::NodalExtremeValue(), EigenExecutionerBase::normalizeSolution(), Output::Output(), MultiAppGeneralFieldTransfer::outputValueConflicts(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PetscOutput::PetscOutput(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), PicardSolve::PicardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseTabularBase::PiecewiseTabularBase(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), MooseMesh::prepare(), MultiApp::readCommandLineArguments(), SolutionUserObject::readExodusII(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), MooseMesh::setCoordSystem(), FileOutput::setFileBase(), FileOutput::setFileBaseInternal(), SetupMeshAction::setupMesh(), MooseApp::setupOptions(), SideDiffusiveFluxIntegralTempl< is_ad, T >::SideDiffusiveFluxIntegralTempl(), SideExtremeValue::SideExtremeValue(), SolutionUserObject::SolutionUserObject(), Terminator::Terminator(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), MultiAppDofCopyTransfer::transfer(), TransformGenerator::TransformGenerator(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
isVector()
template<typename OutputType > bool MooseVariableFV< OutputType >::isVector () const override virtual
Returns
true if this is a vector-valued element, false otherwise.
Implements MooseVariableFieldBase.
Definition at line 407 of file MooseVariableFV.C.
{
  return std::is_same<OutputType, RealVectorValue>::value;
}
jacobianSetup()
template<typename OutputType > void MooseVariableFV< OutputType >::jacobianSetup override virtual
Reimplemented from MooseVariableField< OutputType >.
Definition at line 715 of file MooseVariableFV.C.
{
  clearCaches();
}
kind()
Moose::VarKindType MooseVariableBase::kind () const inline inherited
Kind of the variable (Nonlinear, Auxiliary, ...)
Definition at line 85 of file MooseVariableBase.h.
{ return _var_kind; }
Referenced by ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), FVFluxBC::FVFluxBC(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), and PeriodicSegmentalConstraint::PeriodicSegmentalConstraint().
matrixTagValue()
template<typename OutputType > const FieldVariableValue & MooseVariableFV< OutputType >::matrixTagValue (TagID tag) inline
Definition at line 210 of file MooseVariableFV.h.
  {
    return _element_data->matrixTagValue(tag);
  }
matrixTagValueNeighbor()
template<typename OutputType > const FieldVariableValue & MooseVariableFV< OutputType >::matrixTagValueNeighbor (TagID tag) inline
Definition at line 218 of file MooseVariableFV.h.
  {
    return _neighbor_data->matrixTagValue(tag);
  }
meshBlockIDs()
const std::set< SubdomainID > & BlockRestrictable::meshBlockIDs () const inherited
Return all of the SubdomainIDs for the mesh.
Returns
A set of all subdomians for the entire mesh
Definition at line 269 of file BlockRestrictable.C.
{
  return _blk_mesh->meshSubdomains();
}
Referenced by BlockRestrictable::checkVariable(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), and SolutionIC::initialSetup().
meshChanged()
template<typename OutputType > void MooseVariableFV< OutputType >::meshChanged override virtual
Called on this object when the mesh changes.
Reimplemented from MeshChangedInterface.
Definition at line 803 of file MooseVariableFV.h.
{
  _prev_elem = nullptr;
  _dirichlet_map_setup = false;
  MooseVariableField<OutputType>::meshChanged();
}
mooseDeprecated()
template<typename... Args> void MooseBaseErrorInterface::mooseDeprecated (Args &&... args) const inline inherited
Definition at line 78 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseDeprecatedStream(_console, false, true, std::forward<Args>(args)...);
  }
Referenced by FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::advanceMultiApps(), MultiApp::appProblem(), Executioner::augmentedPicardConvergenceCheck(), MooseMesh::buildSideList(), FEProblemBase::computeResidual(), AddVariableAction::determineType(), Eigenvalue::Eigenvalue(), MooseMesh::elem(), FunctionDT::FunctionDT(), RandomICBase::generateRandom(), MooseMesh::getBoundariesToElems(), Control::getExecuteOptions(), FEProblemBase::getNonlinearSystem(), FEProblemBase::getUserObjects(), FEProblemBase::hasPostprocessor(), MooseMesh::node(), FixedPointSolve::numPicardIts(), RelationshipManager::operator>=(), Executioner::picardSolve(), and MooseMesh::setBoundaryToNormalMap().
mooseError()
template<typename... Args> void MooseBaseErrorInterface::mooseError (Args &&... args) const inline inherited
Emits an error prefixed with object name and type.
Definition at line 38 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, errorPrefix("error"), std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
Referenced by HierarchicalGridPartitioner::_do_partition(), PetscExternalPartitioner::_do_partition(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AdaptivityAction::act(), AddFVICAction::act(), AddICAction::act(), AddMeshGeneratorAction::act(), AddPeriodicBCAction::act(), AddTimeStepperAction::act(), AddVectorPostprocessorAction::act(), CheckFVBCAction::act(), CheckIntegrityAction::act(), CommonOutputAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DeprecatedBlockAction::act(), InitProblemAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetAdaptivityOptionsAction::act(), SetupMeshAction::act(), SetupMeshCompleteAction::act(), SetupPredictorAction::act(), SetupTimeStepperAction::act(), SplitMeshAction::act(), FEProblemBase::adaptMesh(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::addConstraint(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), SubProblem::addFunctor(), FEProblemBase::addFVInitialCondition(), AddGeneralReactions::AddGeneralReactions(), FEProblemBase::addInitialCondition(), FEProblemBase::addLineSearch(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addOutput(), SubProblem::addPiecewiseByBlockLambdaFunctor(), DistributedRectilinearMeshGenerator::addPoint(), DiracKernelBase::addPoint(), DiracKernelBase::addPointWithValidId(), FEProblemBase::addPostprocessor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseMesh::addQuadratureNode(), FEProblemBase::addReporter(), AddVariableAction::addVariable(), FEProblemBase::addVectorPostprocessor(), SubProblem::addVectorTag(), AddZapdosReactions::AddZapdosReactions(), ADEEDFRateConstantTownsend::ADEEDFRateConstantTownsend(), ADGasElectronMoments::ADGasElectronMoments(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), MooseVariableScalar::adUDot(), Output::advancedExecuteOn(), AdvectiveFluxAux::AdvectiveFluxAux(), ADZapdosEEDFRateConstant::ADZapdosEEDFRateConstant(), MooseVariableBase::allDofIndices(), MultiApp::appPostprocessorValue(), MultiApp::appProblem(), MultiApp::appProblemBase(), MultiApp::appUserObjectBase(), ArrayConstantIC::ArrayConstantIC(), ArrayFunctionIC::ArrayFunctionIC(), ArrayParsedAux::ArrayParsedAux(), AddPeriodicBCAction::autoTranslationBoundaries(), Function::average(), Axisymmetric2D3DSolutionFunction::Axisymmetric2D3DSolutionFunction(), BicubicSplineFunction::BicubicSplineFunction(), BlockDeletionGenerator::BlockDeletionGenerator(), BoltzmannSolverScalar::BoltzmannSolverScalar(), BoundingValueElementDamper::BoundingValueElementDamper(), BoundingValueNodalDamper::BoundingValueNodalDamper(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), MooseMesh::buildCoarseningMap(), MultiApp::buildComm(), DistributedRectilinearMeshGenerator::buildCube(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromJSON(), PiecewiseTabularBase::buildFromXY(), MooseMesh::buildLowerDMesh(), GeneratedMesh::buildMesh(), MeshGeneratorMesh::buildMesh(), SpiralAnnularMesh::buildMesh(), TiledMesh::buildMesh(), ImageMesh::buildMesh3D(), ImageMeshGenerator::buildMesh3D(), MooseMesh::buildRefinementMap(), MaterialBase::buildRequiredMaterials(), MooseMesh::buildSideList(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), CartesianGridDivision::CartesianGridDivision(), CartesianMeshGenerator::CartesianMeshGenerator(), UserObjectInterface::castUserObject(), EigenExecutionerBase::chebyshev(), SubProblem::checkBlockMatProps(), SubProblem::checkBoundaryMatProps(), MooseMesh::checkCoordinateSystems(), FEProblemBase::checkDependMaterialsHelper(), FEProblemBase::checkDisplacementOrders(), FEProblemBase::checkDuplicatePostprocessorVariableNames(), MooseMesh::checkDuplicateSubdomainNames(), MaterialBase::checkExecutionStage(), MeshGenerator::checkGetMesh(), ReporterTransferInterface::checkHasReporterValue(), FEProblemBase::checkICRestartError(), EigenExecutionerBase::checkIntegrity(), Eigenvalue::checkIntegrity(), Steady::checkIntegrity(), ExplicitTimeIntegrator::checkLinearConvergence(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), PostprocessorInterface::checkParam(), FEProblemBase::checkProblemIntegrity(), Sampler::checkReinitStatus(), MaterialBase::checkStatefulSanity(), FEProblemBase::checkUserObjects(), MultiAppTransfer::checkVariable(), DomainUserObject::checkVariable(), ChemicalReactionsBase::ChemicalReactionsBase(), MooseMesh::clone(), LibmeshPartitioner::clone(), CombinerGenerator::CombinerGenerator(), ElementSubdomainModifier::complementMovingBoundaryID(), ElementSubdomainModifier::complementMovingBoundaryName(), MooseVariableFieldBase::componentName(), CompositeFunction::CompositeFunction(), NodalPatchRecovery::compute(), VariableCondensationPreconditioner::computeDInverseDiag(), CompositionDT::computeDT(), MooseVariableFieldBase::computeFaceValues(), TimeStepper::computeFailedDT(), IterationAdaptiveDT::computeFailedDT(), TimeSequenceStepperBase::computeFailedDT(), MooseMesh::computeFiniteVolumeCoords(), FVFluxKernel::computeJacobian(), ArrayKernel::computeJacobian(), ArrayKernel::computeOffDiagJacobian(), FVElementalKernel::computeOffDiagJacobian(), MaterialBase::computeProperties(), ScalarKernel::computeQpJacobian(), ScalarKernel::computeQpResidual(), FVFluxKernel::computeResidual(), ArrayKernel::computeResidual(), FVFluxBC::computeResidual(), ResidualObject::computeResidualAndJacobian(), FVFluxKernel::computeResidualAndJacobian(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualL2Norm(), FEProblemBase::computeResidualTag(), FEProblemBase::computeResidualType(), TimeStepper::computeStep(), ActuallyExplicitEuler::computeTimeDerivatives(), AStableDirk4::computeTimeDerivatives(), BDF2::computeTimeDerivatives(), CrankNicolson::computeTimeDerivatives(), ExplicitEuler::computeTimeDerivatives(), ExplicitRK2::computeTimeDerivatives(), ExplicitTVDRK2::computeTimeDerivatives(), ImplicitEuler::computeTimeDerivatives(), ImplicitMidpoint::computeTimeDerivatives(), LStableDirk2::computeTimeDerivatives(), LStableDirk3::computeTimeDerivatives(), LStableDirk4::computeTimeDerivatives(), NewmarkBeta::computeTimeDerivatives(), FEProblemBase::computeUserObjectsInternal(), BolsigValueScalar::computeValue(), PenetrationAux::computeValue(), BuildArrayVariableAux::computeValue(), TagVectorArrayVariableAux::computeValue(), ConcentricCircleMesh::ConcentricCircleMesh(), ConditionalEnableControl::ConditionalEnableControl(), TimeStepper::constrainStep(), LibtorchNeuralNetControl::controlNeuralNet(), AddVariableAction::createInitialConditionAction(), DataRead::DataRead(), ReporterTransferInterface::declareClone(), MeshGenerator::declareMeshProperty(), ReporterTransferInterface::declareVectorClone(), FunctorRelationshipManager::delete_remote_elements(), MooseMesh::deleteRemoteElements(), BicubicSplineFunction::derivative(), MooseMesh::detectPairedSidesets(), FEProblemBase::determineNonlinearSystem(), MeshDiagnosticsGenerator::diagnosticsLog(), DiffusionRateTemp::DiffusionRateTemp(), FunctorBinnedValuesDivision::divisionIndex(), FunctorRelationshipManager::dofmap_reinit(), FEProblemBase::duplicateVariableCheck(), EEDFRateConstant::EEDFRateConstant(), EEDFRateConstantTownsend::EEDFRateConstantTownsend(), Eigenvalue::Eigenvalue(), ElectricField::ElectricField(), ElectronMobility::ElectronMobility(), ElementIntegerAux::ElementIntegerAux(), ElementQualityAux::ElementQualityAux(), ElementUOAux::ElementUOAux(), DistributedRectilinearMeshGenerator::elemId(), ProjectionAux::elemOnNodeVariableIsDefinedOn(), MooseMesh::errorIfDistributedMesh(), SolutionUserObject::evalMeshFunction(), SolutionUserObject::evalMeshFunctionGradient(), SolutionUserObject::evalMultiValuedMeshFunction(), SolutionUserObject::evalMultiValuedMeshFunctionGradient(), BoltzmannSolverScalar::execute(), Eigenvalue::execute(), MultiAppPostprocessorInterpolationTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppPostprocessorTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), ElementQualityChecker::execute(), DiscreteElementUserObject::execute(), DomainUserObject::execute(), FEProblemBase::execute(), FEProblemBase::executeControls(), MultiAppVectorPostprocessorTransfer::executeFromMultiapp(), MultiAppVectorPostprocessorTransfer::executeToMultiapp(), ExplicitSSPRungeKutta::ExplicitSSPRungeKutta(), FileOutput::FileOutput(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), ElementQualityChecker::finalize(), VerifyElementUniqueID::finalize(), VerifyNodalUniqueID::finalize(), DiscreteElementUserObject::finalize(), Transfer::find_sys(), BreakMeshByBlockGeneratorBase::findFreeBoundaryId(), FunctionDT::FunctionDT(), FunctionScalarAux::FunctionScalarAux(), FunctionScalarIC::FunctionScalarIC(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), GapValueAux::GapValueAux(), Gas::Gas(), GasBase::GasBase(), GasElectronMoments::GasElectronMoments(), AllSideSetsByNormalsGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundingBoxNodeSetGenerator::generate(), BreakMeshByBlockGenerator::generate(), CombinerGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), ElementSubdomainIDGenerator::generate(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), GeneratedMeshGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), MeshCollectionGenerator::generate(), MeshDiagnosticsGenerator::generate(), MeshExtruderGenerator::generate(), MeshRepairGenerator::generate(), MoveNodeGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), SideSetsFromNormalsGenerator::generate(), SideSetsFromPointsGenerator::generate(), SmoothMeshGenerator::generate(), SpiralAnnularMeshGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), TiledMeshGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GeneratedMesh::GeneratedMesh(), GeneratedMeshGenerator::GeneratedMeshGenerator(), MeshGenerator::generateInternal(), CircularBoundaryCorrectionGenerator::generateRadialCorrectionFactor(), RandomICBase::generateRandom(), GenericConstantMaterialTempl< is_ad >::GenericConstantMaterialTempl(), GenericConstantVectorMaterialTempl< is_ad >::GenericConstantVectorMaterialTempl(), GenericFunctionMaterialTempl< is_ad >::GenericFunctionMaterialTempl(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), DisplacedProblem::getActualFieldVariable(), FEProblemBase::getActualFieldVariable(), DisplacedProblem::getArrayVariable(), FEProblemBase::getArrayVariable(), MooseMesh::getAxisymmetricRadialCoord(), MooseMesh::getBlockConnectedBlocks(), VariableOldValueBoundsAux::getBound(), MooseMesh::getBoundaryID(), MultiApp::getBoundingBox(), MooseMesh::getCoarseningMap(), MooseVariableBase::getContinuity(), Control::getControllableParameterByName(), MooseMesh::getCoordSystem(), PropertyReadFile::getData(), TransfiniteMeshGenerator::getDiscreteEdge(), FEProblemBase::getDistribution(), MooseVariableBase::getDofIndices(), VariableCondensationPreconditioner::getDofToCondense(), TransfiniteMeshGenerator::getEdge(), GhostingUserObject::getElementalValue(), ElementUOProvider::getElementalValueLong(), ElementUOProvider::getElementalValueReal(), PropertyReadFile::getElementData(), MooseMesh::getElementIDIndex(), Material::getElementIDNeighbor(), Material::getElementIDNeighborByName(), MooseMesh::getElemIDMapping(), MooseMesh::getElemIDsOnBlocks(), MultiAppFieldTransfer::getEquationSystem(), MultiApp::getExecutioner(), MultiAppTransfer::getFromMultiApp(), MultiAppTransfer::getFromMultiAppInfo(), FEProblemBase::getFunction(), SubProblem::getFunctor(), MooseMesh::getGeneralAxisymmetricCoordAxis(), DistributedRectilinearMeshGenerator::getGhostNeighbors(), BatchMaterial< Tuple, Output, Input >::getIndex(), DistributedRectilinearMeshGenerator::getIndices(), SolutionUserObject::getLocalVarIndex(), Material::getMaterialByName(), FEProblemBase::getMaterialData(), SubProblem::getMatrixTagID(), AnnularMesh::getMaxInDimension(), GeneratedMesh::getMaxInDimension(), FEProblemBase::getMaxQps(), FEProblemBase::getMeshDivision(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), AnnularMesh::getMinInDimension(), GeneratedMesh::getMinInDimension(), MultiAppTransfer::getMultiApp(), DistributedRectilinearMeshGenerator::getNeighbors(), MooseMesh::getNodeBlockIds(), PropertyReadFile::getNodeData(), MooseMesh::getNodeList(), FEProblemBase::getNonlinearSystem(), MooseMesh::getPairedBoundaryMapping(), ImageMesh::GetPixelInfo(), ImageMeshGenerator::GetPixelInfo(), PlaneIDMeshGenerator::getPlaneID(), FEProblemBase::getPositionsObject(), PostprocessorInterface::getPostprocessorValueByNameInternal(), MooseMesh::getRefinementMap(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), FEProblemBase::getSampler(), JSONFileReader::getScalar(), DisplacedProblem::getScalarVariable(), FEProblemBase::getScalarVariable(), DisplacedProblem::getStandardVariable(), FEProblemBase::getStandardVariable(), MooseMesh::getSubdomainBoundaryIds(), DisplacedProblem::getSystem(), FEProblemBase::getSystem(), FEProblemBase::getTimeFromStateArg(), Transient::getTimeIntegratorName(), MultiAppTransfer::getToMultiApp(), MultiAppTransfer::getToMultiAppInfo(), MooseMesh::getUniqueCoordSystem(), FEProblemBase::getUserObject(), FEProblemBase::getUserObjectBase(), UserObjectInterface::getUserObjectBaseByName(), UserObjectInterface::getUserObjectName(), JSONFileReader::getVector(), VectorPostprocessorInterface::getVectorPostprocessorName(), SubProblem::getVectorTag(), SubProblem::getVectorTagID(), DisplacedProblem::getVectorVariable(), FEProblemBase::getVectorVariable(), GhostingAux::GhostingAux(), MultiApp::globalAppToLocal(), Function::gradient(), MooseParsedVectorFunction::gradient(), Terminator::handleMessage(), MooseVariableBase::hasDoFsOnNodes(), PostprocessorInterface::hasPostprocessor(), PostprocessorInterface::hasPostprocessorByName(), ReporterInterface::hasReporterValue(), ReporterInterface::hasReporterValueByName(), VectorPostprocessorInterface::hasVectorPostprocessor(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), AddVariableAction::init(), MooseMesh::init(), Sampler::init(), AddAuxVariableAction::init(), EigenExecutionerBase::init(), Eigenvalue::init(), Transient::init(), FEProblemBase::init(), CrankNicolson::init(), ExplicitTimeIntegrator::init(), CSVTimeSequenceStepper::init(), IterationAdaptiveDT::init(), MultiApp::init(), FEProblemBase::initialAdaptMesh(), BoltzmannSolverScalar::initialize(), PolynomialCoefficients::initialize(), CartesianGridDivision::initialize(), CylindricalGridDivision::initialize(), NestedDivision::initialize(), SphericalGridDivision::initialize(), SubProblem::initialSetup(), SolutionAux::initialSetup(), SolutionScalarAux::initialSetup(), Axisymmetric2D3DSolutionFunction::initialSetup(), MooseParsedFunction::initialSetup(), SolutionFunction::initialSetup(), SolutionIC::initialSetup(), FullSolveMultiApp::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), SolutionUserObject::initialSetup(), Function::integral(), InterpolatedCoefficientLinear::InterpolatedCoefficientLinear(), InterpolatedCoefficientSpline::InterpolatedCoefficientSpline(), EigenExecutionerBase::inversePowerIteration(), InversePowerMethod::InversePowerMethod(), Sampler::isAdaptiveSamplingCompleted(), MooseMesh::isBoundaryFullyExternalToSubdomains(), MooseVariableBase::isNodal(), IterationAdaptiveDT::IterationAdaptiveDT(), LibmeshPartitioner::LibmeshPartitioner(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LineSearch::lineSearch(), ReporterPointMarker::markerSetup(), Material::Material(), MaterialOutputAction::materialOutputHelper(), MaterialRealTensorValueAux::MaterialRealTensorValueAux(), MaterialRealVectorValueAuxTempl< is_ad >::MaterialRealVectorValueAuxTempl(), Distribution::median(), FunctorRelationshipManager::mesh_reinit(), SubProblem::meshChanged(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshExtruderGenerator::MeshExtruderGenerator(), MeshRepairGenerator::MeshRepairGenerator(), SetupMeshAction::modifyParamsForUseSplit(), MeshMetaDataInterface::mooseErrorInternal(), MooseMesh::MooseMesh(), MooseVariableBase::MooseVariableBase(), MoveNodeGenerator::MoveNodeGenerator(), ElementSubdomainModifier::movingBoundaryID(), ElementSubdomainModifier::movingBoundaryName(), MultiApp::MultiApp(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NearestNodeDistanceAux::NearestNodeDistanceAux(), NearestNodeValueAux::NearestNodeValueAux(), FEProblemBase::needsPreviousNewtonIteration(), NewmarkBeta::NewmarkBeta(), NodalPatchRecoveryBase::nodalPatchRecovery(), NodalPatchRecoveryAuxBase::NodalPatchRecoveryAuxBase(), DistributedRectilinearMeshGenerator::nodeId(), DistributedRectilinearMeshGenerator::numNeighbors(), Output::onInterval(), FunctorRelationshipManager::operator()(), RelationshipManager::operator==(), MortarNodalGeometryOutput::output(), Output::Output(), DistributedRectilinearMeshGenerator::paritionSquarely(), PiecewiseBilinear::parse(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ParsedSubdomainMeshGenerator::ParsedSubdomainMeshGenerator(), ExplicitTimeIntegrator::performExplicitSolve(), PetscExternalPartitioner::PetscExternalPartitioner(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), Executioner::picardSolve(), PIDTransientControl::PIDTransientControl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseMulticonstant::PiecewiseMulticonstant(), PiecewiseTabularBase::PiecewiseTabularBase(), SolutionUserObject::pointValueGradientWrapper(), SolutionUserObject::pointValueWrapper(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessorByName(), AStableDirk4::postResidual(), ExplicitRK2::postResidual(), ExplicitTVDRK2::postResidual(), ImplicitMidpoint::postResidual(), LStableDirk2::postResidual(), LStableDirk3::postResidual(), LStableDirk4::postResidual(), VariableCondensationPreconditioner::preallocateCondensedJacobian(), Predictor::Predictor(), Transient::preExecute(), MooseMesh::prepare(), MooseMesh::prepared(), FixedPointSolve::printFixedPointConvergenceReason(), RateCoefficientProvider::RateCoefficientProvider(), RateCoefficientProvider::reaction_coefficient(), RateCoefficientProvider::reaction_coefficient_derivative(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readExodusII(), SolutionUserObject::readXda(), FunctorRelationshipManager::redistribute(), Sampler::reinit(), RinglebMesh::RinglebMesh(), RinglebMeshGenerator::RinglebMeshGenerator(), PiecewiseMultiInterpolation::sample(), ScalarComponentIC::ScalarComponentIC(), ScalarLinearInterpolation::ScalarLinearInterpolation(), ScalarSplineInterpolation::ScalarSplineInterpolation(), DistributedRectilinearMeshGenerator::scaleNodalPositions(), BicubicSplineFunction::secondDerivative(), FunctorRelationshipManager::set_mesh(), MooseVariableBase::setActiveTags(), DistributedRectilinearMeshGenerator::setBoundaryNames(), MooseMesh::setCoordSystem(), FEProblemBase::setCoupling(), PiecewiseBase::setData(), FileOutput::setFileBaseInternal(), MooseMesh::setGeneralAxisymmetricCoordAxes(), FEProblemSolve::setInnerSolve(), MeshGenerator::setMeshProperty(), FEProblemBase::setNonlocalCouplingMatrix(), Sampler::setNumberOfCols(), Sampler::setNumberOfRandomSeeds(), Sampler::setNumberOfRows(), Split::setup(), TransientMultiApp::setupApp(), SetupMeshAction::setupMesh(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), TimePeriodBase::setupTimes(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SideSetsFromNormalsGenerator::SideSetsFromNormalsGenerator(), SideSetsFromPointsGenerator::SideSetsFromPointsGenerator(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), SolutionTimeAdaptiveDT::SolutionTimeAdaptiveDT(), SolutionUserObject::SolutionUserObject(), FullSolveMultiApp::solveStep(), UserObject::spatialPoints(), UserObject::spatialValue(), SpiralAnnularMesh::SpiralAnnularMesh(), SpiralAnnularMeshGenerator::SpiralAnnularMeshGenerator(), StitchedMesh::StitchedMesh(), MaterialBase::subdomainSetup(), GeneralUserObject::subdomainSetup(), NodalUserObject::subdomainSetup(), Constraint::subdomainSetup(), SuperelasticReactionRate::SuperelasticReactionRate(), FEProblemBase::swapBackMaterialsNeighbor(), Terminator::Terminator(), GeneralUserObject::threadJoin(), ThreadedGeneralUserObject::threadJoin(), DiscreteElementUserObject::threadJoin(), TimePeriodBase::TimePeriodBase(), VectorPostprocessorVisualizationAux::timestepSetup(), FEProblemBase::trustUserCouplingMatrix(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), FEProblemBase::uDotDotOldRequested(), MooseVariableScalar::uDotOld(), FEProblemBase::uDotOldRequested(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), SolutionUserObject::updateExodusBracketingTimeIndices(), FEProblemBase::updateMaxQps(), BoundingBoxIC::value(), Function::value(), Axisymmetric2D3DSolutionFunction::value(), PiecewiseConstantFromCSV::value(), ValueProvider::ValueProvider(), ValueRangeMarker::ValueRangeMarker(), ValueThresholdMarker::ValueThresholdMarker(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), MultiAppTransfer::variableIntegrityCheck(), VariableTimeIntegrationAux::VariableTimeIntegrationAux(), AddVariableAction::variableType(), Function::vectorCurl(), SubProblem::vectorTagName(), SubProblem::vectorTagType(), Function::vectorValue(), MooseParsedFunction::vectorValue(), MooseParsedGradFunction::vectorValue(), SubProblem::verifyVectorTags(), and ZapdosEEDFRateConstant::ZapdosEEDFRateConstant().
mooseErrorNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseErrorNonPrefixed (Args &&... args) const inline inherited
Emits an error without the prefixing included in mooseError().
Definition at line 50 of file MooseBaseErrorInterface.h.
  {
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    callMooseErrorRaw(msg, &_app);
  }
mooseInfo()
template<typename... Args> void MooseBaseErrorInterface::mooseInfo (Args &&... args) const inline inherited
Definition at line 84 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseInfoStream(_console, std::forward<Args>(args)...);
  }
Referenced by AddZapdosReactions::act(), SetupRecoverFileBaseAction::act(), AStableDirk4::AStableDirk4(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), BoltzmannSolverScalar::execute(), ExplicitRK2::ExplicitRK2(), ExplicitTVDRK2::ExplicitTVDRK2(), MultiAppTransfer::getPointInTargetAppFrame(), ImplicitMidpoint::ImplicitMidpoint(), InversePowerMethod::InversePowerMethod(), LStableDirk2::LStableDirk2(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), NonlinearEigen::NonlinearEigen(), ProjectionAux::ProjectionAux(), FEProblemBase::setRestartFile(), and SymmetryTransformGenerator::SymmetryTransformGenerator().
mooseWarning()
template<typename... Args> void MooseBaseErrorInterface::mooseWarning (Args &&... args) const inline inherited
Emits a warning prefixed with object name and type.
Definition at line 62 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(
        _console, errorPrefix("warning"), std::forward<Args>(args)...);
  }
Referenced by AddFunctionAction::act(), AddKernelAction::act(), CommonOutputAction::act(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupMeshAction::act(), DumpObjectsProblem::addAuxVariable(), DiracKernelBase::addPoint(), BoundaryMarker::BoundaryMarker(), BoundsAuxBase::BoundsAuxBase(), DistributedRectilinearMeshGenerator::buildCube(), MultiAppVariableValueSamplePostprocessorTransfer::cacheElemToPostprocessorData(), CartesianMeshGenerator::CartesianMeshGenerator(), CheckOutputAction::checkConsoleOutput(), MultiAppTransfer::checkMultiAppExecuteOn(), GapValueAux::computeValue(), MeshDiagnosticsGenerator::diagnosticsLog(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), Postprocessor::evaluateDotWarning(), ElementQualityChecker::finalize(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), FixedPointSolve::FixedPointSolve(), ElementSubdomainIDGenerator::generate(), ParsedGenerateSideset::generate(), MultiAppTransfer::getAppInfo(), FunctorBinnedValuesDivision::getBinIndex(), FEProblemBase::getMaterial(), Terminator::handleMessage(), MaterialBase::initStatefulProperties(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::mesh(), NewmarkBeta::NewmarkBeta(), NodalPatchRecovery::NodalPatchRecovery(), Output::Output(), PiecewiseConstantFromCSV::PiecewiseConstantFromCSV(), Executioner::problem(), PropertyReadFile::readData(), TestSourceStepper::rejectStep(), MaterialBase::resetQpProperties(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setCoordSystem(), FEProblemBase::sizeZeroes(), TransientMultiApp::solveStep(), TimeDerivativeAux::TimeDerivativeAux(), PiecewiseConstantFromCSV::value(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
mooseWarningNonPrefixed()
template<typename... Args> void MooseBaseErrorInterface::mooseWarningNonPrefixed (Args &&... args) const inline inherited
Emits a warning without the prefixing included in mooseWarning().
Definition at line 72 of file MooseBaseErrorInterface.h.
  {
    moose::internal::mooseWarningStream(_console, std::forward<Args>(args)...);
  }
name()
const std::string & MooseVariableBase::name () const inline override virtual inherited
Get the variable name.
Reimplemented from MooseBase.
Definition at line 69 of file MooseVariableBase.h.
{ return _var_name; }
Referenced by SetupResidualDebugAction::act(), InitialConditionWarehouse::addObject(), MooseVariableBase::allDofIndices(), ArrayParsedAux::ArrayParsedAux(), BlockRestrictable::checkVariable(), DomainUserObject::checkVariable(), Coupleable::checkWritableVar(), Coupleable::coupledName(), Moose::FV::determineElemOneAndTwo(), GreaterThanLessThanPostprocessor::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppGeometricInterpolationTransfer::fillSourceInterpolationPoints(), FunctionArrayAux::FunctionArrayAux(), FVInitialConditionTempl< T >::FVInitialConditionTempl(), GapValueAux::GapValueAux(), MultiAppGeometricInterpolationTransfer::interpolateTargetPoints(), DerivativeMaterialInterface< T >::isNotObjectVariable(), ParsedAux::ParsedAux(), ParsedAuxScalar::ParsedAuxScalar(), ParsedODEKernel::ParsedODEKernel(), ParsedScalarRateCoefficient::ParsedScalarRateCoefficient(), ConstraintWarehouse::subdomainsCovered(), MultiAppDofCopyTransfer::transfer(), MultiAppShapeEvaluationTransfer::transferVariable(), FVFluxBC::uOnGhost(), and FVFluxBC::uOnUSub().
nodalDofIndex()
template<typename OutputType > virtual const dof_id_type & MooseVariableFV< OutputType >::nodalDofIndex () const inline final override virtual
Implements MooseVariableFieldBase.
Definition at line 112 of file MooseVariableFV.h.
  {
    mooseError("nodalDofIndex not supported by MooseVariableFVBase");
  }
nodalDofIndexNeighbor()
template<typename OutputType > virtual const dof_id_type & MooseVariableFV< OutputType >::nodalDofIndexNeighbor () const inline final override virtual
Implements MooseVariableFieldBase.
Definition at line 116 of file MooseVariableFV.h.
  {
    mooseError("nodalDofIndexNeighbor not supported by MooseVariableFVBase");
  }
nodalValueArray()
template<typename OutputType > const MooseArray< OutputType > & MooseVariableFV< OutputType >::nodalValueArray () const inline override virtual
Methods for retrieving values of variables at the nodes in a MooseArray for AuxKernelBase.
Implements MooseVariableField< OutputType >.
Definition at line 555 of file MooseVariableFV.h.
  {
    mooseError("Finite volume variables do not have defined values at nodes.");
  }
nodalValueOldArray()
template<typename OutputType > const MooseArray< OutputType > & MooseVariableFV< OutputType >::nodalValueOldArray () const inline override virtual
Implements MooseVariableField< OutputType >.
Definition at line 559 of file MooseVariableFV.h.
  {
    mooseError("Finite volume variables do not have defined values at nodes.");
  }
nodalValueOlderArray()
template<typename OutputType > const MooseArray< OutputType > & MooseVariableFV< OutputType >::nodalValueOlderArray () const inline override virtual
Implements MooseVariableField< OutputType >.
Definition at line 563 of file MooseVariableFV.h.
  {
    mooseError("Finite volume variables do not have defined values at nodes.");
  }
nodalVectorTagValue()
template<typename OutputType > const DoFValue & MooseVariableFV< OutputType >::nodalVectorTagValue (TagID) const inline override virtual
Implements MooseVariableField< OutputType >.
Definition at line 197 of file MooseVariableFV.h.
  {
    mooseError("nodalVectorTagValue not implemented for finite volume variables.");
  }
number()
unsigned int MooseVariableBase::number () const inline inherited
Get variable number coming from libMesh.
Returns
the libmesh variable number
Definition at line 49 of file MooseVariableBase.h.
{ return _var_num; }
Referenced by AdaptivityAction::act(), Assembly::addJacobianBlock(), Assembly::addJacobianCoupledVarPair(), EigenProblem::adjustEigenVector(), MooseMesh::cacheFaceInfoVariableOwnership(), Assembly::cacheJacobianBlock(), Assembly::cacheJacobianBlockNonzero(), Assembly::cacheJacobianCoupledVarPair(), ComputeJacobianThread::compute(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayIntegratedBC::computeJacobian(), IntegratedBC::computeJacobian(), NonlocalIntegratedBC::computeJacobian(), VectorIntegratedBC::computeJacobian(), NodeElemConstraint::computeJacobian(), NodeFaceConstraint::computeJacobian(), ArrayKernel::computeJacobian(), EigenKernel::computeJacobian(), Kernel::computeJacobian(), KernelGrad::computeJacobian(), KernelValue::computeJacobian(), MassLumpedTimeDerivative::computeJacobian(), NonlocalKernel::computeJacobian(), ODEKernel::computeJacobian(), TimeDerivative::computeJacobian(), VectorKernel::computeJacobian(), VectorTimeDerivative::computeJacobian(), NodalEqualValueConstraint::computeJacobian(), ScalarKernel::computeJacobian(), FVFluxBC::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), MortarConstraint::computeJacobian(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDResidual(), DGLowerDKernel::computeLowerDResidual(), NonlocalIntegratedBC::computeNonlocalJacobian(), NonlocalKernel::computeNonlocalJacobian(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ArrayIntegratedBC::computeOffDiagJacobian(), IntegratedBC::computeOffDiagJacobian(), LowerDIntegratedBC::computeOffDiagJacobian(), NodalBC::computeOffDiagJacobian(), NonlocalIntegratedBC::computeOffDiagJacobian(), VectorIntegratedBC::computeOffDiagJacobian(), VectorNodalBC::computeOffDiagJacobian(), NodeElemConstraint::computeOffDiagJacobian(), NodeFaceConstraint::computeOffDiagJacobian(), DGLowerDKernel::computeOffDiagJacobian(), ADKernelScalarBase::computeOffDiagJacobian(), ArrayKernel::computeOffDiagJacobian(), EigenKernel::computeOffDiagJacobian(), Kernel::computeOffDiagJacobian(), KernelGrad::computeOffDiagJacobian(), KernelValue::computeOffDiagJacobian(), NonlocalKernel::computeOffDiagJacobian(), VectorKernel::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), ADDGKernel::computeOffDiagJacobian(), ADNodalKernel::computeOffDiagJacobian(), ArrayIntegratedBC::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), ArrayKernel::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), NodalScalarKernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), ComputeFullJacobianThread::computeOnInterface(), ComputeFullJacobianThread::computeOnInternalFace(), EEDFReactionLog::computeQpJacobian(), EEDFReactionTownsendLog::computeQpJacobian(), OldEqualValueConstraint::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), ArrayIntegratedBC::computeQpOffDiagJacobian(), ArrayKernel::computeQpOffDiagJacobian(), ArrayCoupledTimeDerivative::computeQpOffDiagJacobian(), ArrayDiffusion::computeQpOffDiagJacobian(), ArrayReaction::computeQpOffDiagJacobian(), ArrayTimeDerivative::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), ArrayNodalBC::computeQpOffDiagJacobian(), EEDFReactionTownsendLog::computeQpOffDiagJacobian(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), ArrayIntegratedBC::computeResidual(), ArrayLowerDIntegratedBC::computeResidual(), IntegratedBC::computeResidual(), LowerDIntegratedBC::computeResidual(), VectorIntegratedBC::computeResidual(), NodeElemConstraint::computeResidual(), NodeFaceConstraint::computeResidual(), FVElementalKernel::computeResidual(), ArrayKernel::computeResidual(), EigenKernel::computeResidual(), Kernel::computeResidual(), KernelGrad::computeResidual(), KernelValue::computeResidual(), ODEKernel::computeResidual(), ODETimeKernel::computeResidual(), TimeKernel::computeResidual(), VectorKernel::computeResidual(), VectorTimeKernel::computeResidual(), ADScalarKernel::computeResidual(), NodalEqualValueConstraint::computeResidual(), ScalarKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVFluxBC::computeResidual(), FVInterfaceKernel::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), FVScalarLagrangeMultiplierInterface::computeResidual(), ADMortarConstraint::computeResidual(), MortarConstraint::computeResidual(), IntegratedBC::computeResidualAndJacobian(), NodalBC::computeResidualAndJacobian(), Kernel::computeResidualAndJacobian(), MortarScalarBase::computeScalarOffDiagJacobian(), PenaltyPeriodicSegmentalConstraint::computeScalarQpOffDiagJacobian(), PeriodicSegmentalConstraint::computeScalarQpOffDiagJacobian(), DebugResidualAux::computeValue(), ProjectionAux::computeValue(), CoupledForceNodalKernel::CoupledForceNodalKernel(), CoupledForceTempl< is_ad >::CoupledForceTempl(), ScalarCoupleable::coupledScalar(), Moose::FV::determineElemOneAndTwo(), EconomouDielectricBC::EconomouDielectricBC(), VariableResidual::execute(), NodalNormalsCorner::execute(), NodalNormalsEvaluator::execute(), NodalNormalsPreprocessor::execute(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), ConservativeAdvection::fullUpwind(), BoundsAuxBase::getDoFIndex(), FVBoundaryCondition::hasFaceSide(), LazyCoupleable::init(), NodalNormalsPreprocessor::initialize(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), ArrayKernel::initQpOffDiagJacobian(), LowerBoundNodalKernel::LowerBoundNodalKernel(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), ComputeDiracThread::onElement(), ComputeNodalKernelBCJacobiansThread::onNode(), ComputeNodalKernelJacobiansThread::onNode(), Assembly::prepareBlock(), Assembly::prepareBlockNonlocal(), Assembly::prepareJacobianBlock(), Assembly::prepareLowerD(), Assembly::prepareNeighbor(), Assembly::prepareNonlocal(), Assembly::prepareVariable(), Assembly::prepareVariableNonlocal(), MultiAppProjectionTransfer::projectSolution(), EqualValueEmbeddedConstraint::reinitConstraint(), AddPeriodicBCAction::setPeriodicVars(), FVInterfaceKernel::setupData(), NonlinearSystemBase::setupScalingData(), MultiAppDofCopyTransfer::transferDofObject(), FVFluxBC::uOnGhost(), FVFluxBC::uOnUSub(), UpdateErrorVectorsThread::UpdateErrorVectorsThread(), UpperBoundNodalKernel::UpperBoundNodalKernel(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and MortarConstraintBase::zeroInactiveLMDofs().
numberOfDofs()
template<typename OutputType > unsigned int MooseVariableFV< OutputType >::numberOfDofs () const inline final override virtual
Get the number of local DoFs.
Reimplemented from MooseVariableBase.
Definition at line 149 of file MooseVariableFV.h.
{ return _element_data->numberOfDofs(); }
numberOfDofsNeighbor()
template<typename OutputType > virtual unsigned int MooseVariableFV< OutputType >::numberOfDofsNeighbor () inline final override virtual
Implements MooseVariableFieldBase.
Definition at line 151 of file MooseVariableFV.h.
  {
    mooseError("numberOfDofsNeighbor not supported by MooseVariableFVBase");
  }
numBlocks()
unsigned int BlockRestrictable::numBlocks () const inherited
Return the number of blocks for this object.
Returns
The number of subdomains
Definition at line 199 of file BlockRestrictable.C.
{
  return (unsigned int)_blk_ids.size();
}
Referenced by ElementCentroidPositions::initialize().
objectErrorPrefix()
std::string MooseBaseParameterInterface::objectErrorPrefix (const std::string & error_type) const inherited
A descriptive prefix for errors for an object.
Definition at line 58 of file MooseBaseParameterInterface.C.
{
  std::stringstream oss;
  oss << "The following " << error_type << " occurred in the class \"" << _moose_base->name()
      << "\", of type \"" << _moose_base->type() << "\".\n\n";
  return oss.str();
}
Referenced by MooseBaseParameterInterface::paramErrorMsg().
oldestSolutionStateRequested()
template<typename OutputType > unsigned int MooseVariableFV< OutputType >::oldestSolutionStateRequested () const final override virtual
The oldest solution state that is requested for this variable (0 = current, 1 = old, 2 = older, etc).
Implements MooseVariableFieldBase.
Definition at line 729 of file MooseVariableFV.C.
{
  unsigned int state = 0;
  state = std::max(state, _element_data->oldestSolutionStateRequested());
  state = std::max(state, _neighbor_data->oldestSolutionStateRequested());
  return state;
}
operator()() [1/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const ElemArg & elem, const StateArg & state) const inherited
Same as their evaluate overloads with the same arguments but allows for caching implementation.
These are the methods a user will call in their code
Definition at line 84 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(elem, state);
  mooseAssert(state.state == 0,
              "Cached evaluations are only currently supported for the current state.");
  return queryFVArgCache(_elem_arg_to_value, elem);
}
operator()() [2/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const ElemPointArg & elem_point, const StateArg & state) const inherited
Definition at line 88 of file MooseFunctor.h.
{
  return evaluate(elem_point, state);
}
operator()() [3/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const ElemQpArg & qp, const StateArg & state) const inherited
Definition at line 86 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(elem_qp, state);
  const auto elem_id = elem_qp.elem->id();
  if (elem_id != _current_qp_map_key)
  {
    _current_qp_map_key = elem_id;
    _current_qp_map_value = &_qp_to_value[elem_id];
  }
  auto & qp_data = *_current_qp_map_value;
  const auto qp = elem_qp.qp;
  const auto * const qrule = elem_qp.qrule;
  mooseAssert(qrule, "qrule must be non-null");
  return queryQpCache(qp, *qrule, qp_data, elem_qp, state);
}
operator()() [4/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const ElemSideQpArg & qp, const StateArg & state) const inherited
Definition at line 87 of file MooseFunctor.h.
{
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(elem_side_qp, state);
  const Elem * const elem = elem_side_qp.elem;
  mooseAssert(elem, "elem must be non-null");
  const auto elem_id = elem->id();
  if (elem_id != _current_side_qp_map_key)
  {
    _current_side_qp_map_key = elem_id;
    _current_side_qp_map_value = &_side_qp_to_value[elem_id];
  }
  auto & side_qp_data = *_current_side_qp_map_value;
  const auto side = elem_side_qp.side;
  const auto qp = elem_side_qp.qp;
  const auto * const qrule = elem_side_qp.qrule;
  mooseAssert(qrule, "qrule must be non-null");
  // Check and see whether we even have sized for this side
  if (side >= side_qp_data.size())
    side_qp_data.resize(elem->n_sides());
  // Ok we were sized enough for our side
  auto & qp_data = side_qp_data[side];
  return queryQpCache(qp, *qrule, qp_data, elem_side_qp, state);
}
operator()() [5/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const FaceArg & face, const StateArg & state) const inherited
Definition at line 85 of file MooseFunctor.h.
{
  const auto face = checkFace(face_in);
  if (_clearance_schedule.count(EXEC_ALWAYS))
    return evaluate(face, state);
  mooseAssert(state.state == 0,
              "Cached evaluations are only currently supported for the current state.");
  return queryFVArgCache(_face_arg_to_value, face);
}
operator()() [6/6]
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::operator() (const NodeArg & node, const StateArg & state) const inherited
Definition at line 89 of file MooseFunctor.h.
{
  return evaluate(node, state);
}
order()
Order MooseVariableBase::order () const inherited
Get the order of this variable Note: Order enum can be implicitly converted to unsigned int.
Definition at line 149 of file MooseVariableBase.C.
{
  return _fe_type.order;
}
Referenced by FEProblemBase::checkDisplacementOrders(), AuxScalarKernel::compute(), ScalarInitialCondition::compute(), ADScalarKernel::computeADJacobian(), ODEKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVScalarLagrangeMultiplierConstraint::computeOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), DGFunctionDiffusionDirichletBC::computeQpJacobian(), DGDiffusionPostprocessorDirichletBC::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), ArrayIntegratedBC::computeQpOffDiagJacobianScalar(), ArrayKernel::computeQpOffDiagJacobianScalar(), DGFunctionDiffusionDirichletBC::computeQpResidual(), DGDiffusionPostprocessorDirichletBC::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), ODEKernel::computeResidual(), ODETimeKernel::computeResidual(), ADScalarKernel::computeResidual(), ScalarKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), ProjectionAux::computeValue(), ScalarCoupleable::coupledScalarOrder(), MultiAppPostprocessorToAuxScalarTransfer::execute(), FunctionScalarAux::FunctionScalarAux(), GapValueAux::GapValueAux(), ArrayDGDiffusion::initQpResidual(), NodalPatchRecovery::NodalPatchRecovery(), FEProblemBase::projectInitialConditionOnCustomRange(), ProjectionAux::ProjectionAux(), FEProblemBase::projectSolution(), ScalarComponentIC::ScalarComponentIC(), and MooseVariableBase::validParams().
paramError()
template<typename... Args> void MooseBaseParameterInterface::paramError (const std::string & param, Args... args) const inherited
Emits an error prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseError - only printing a message using the given args.
Definition at line 233 of file MooseBaseParameterInterface.h.
{
  Moose::show_trace = false;
  std::string msg = paramErrorMsg(param, std::forward<Args>(args)...);
  callMooseErrorRaw(msg, &_moose_base->getMooseApp());
  Moose::show_trace = true;
}
Referenced by HierarchicalGridPartitioner::_do_partition(), SetupDebugAction::act(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), ADDGKernel::ADDGKernel(), ReporterPointSource::addPoints(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ADNodalKernel::ADNodalKernel(), ADPenaltyPeriodicSegmentalConstraint::ADPenaltyPeriodicSegmentalConstraint(), ADPeriodicSegmentalConstraint::ADPeriodicSegmentalConstraint(), AdvancedExtruderGenerator::AdvancedExtruderGenerator(), AdvectiveFluxAux::AdvectiveFluxAux(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), ArrayBodyForce::ArrayBodyForce(), ArrayDGKernel::ArrayDGKernel(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), ArrayDirichletBC::ArrayDirichletBC(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), ArrayParsedAux::ArrayParsedAux(), ArrayPenaltyDirichletBC::ArrayPenaltyDirichletBC(), ArrayVacuumBC::ArrayVacuumBC(), BlockDeletionGenerator::BlockDeletionGenerator(), BlockWeightedPartitioner::BlockWeightedPartitioner(), BoundsAuxBase::BoundsAuxBase(), BreakMeshByBlockGenerator::BreakMeshByBlockGenerator(), BuildArrayVariableAux::BuildArrayVariableAux(), PiecewiseTabularBase::buildFromFile(), CartesianGridDivision::CartesianGridDivision(), UserObjectInterface::castUserObject(), checkComponent(), MeshGenerator::checkGetMesh(), PostprocessorInterface::checkParam(), Coupleable::checkVar(), MultiAppTransfer::checkVariable(), CircularBoundaryCorrectionGenerator::CircularBoundaryCorrectionGenerator(), CircularBoundaryCorrectionGenerator::circularCenterCalculator(), MultiAppGeneralFieldTransfer::closestToPosition(), CombinerGenerator::CombinerGenerator(), CompositionDT::CompositionDT(), ConcentricCircleMeshGenerator::ConcentricCircleMeshGenerator(), LibtorchNeuralNetControl::conditionalParameterError(), ConstantVectorPostprocessor::ConstantVectorPostprocessor(), ContainsPointAux::ContainsPointAux(), CopyValueAux::CopyValueAux(), Coupleable::Coupleable(), CoupledForceTempl< is_ad >::CoupledForceTempl(), CoupledValueFunctionMaterialTempl< is_ad >::CoupledValueFunctionMaterialTempl(), MultiApp::createApp(), MeshGeneratorSystem::createMeshGenerator(), CylindricalGridDivision::CylindricalGridDivision(), ConstantReporter::declareConstantReporterValues(), AccumulateReporter::declareLateValues(), DGKernel::DGKernel(), DGKernelBase::DGKernelBase(), DGLowerDKernel::DGLowerDKernel(), DiffusionFluxAux::DiffusionFluxAux(), DomainUserObject::DomainUserObject(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElementExtremeFunctorValueTempl< is_ad >::ElementExtremeFunctorValueTempl(), ElementExtremeValue::ElementExtremeValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), ElementLengthAux::ElementLengthAux(), ElementLpNormAux::ElementLpNormAux(), ElementValueSampler::ElementValueSampler(), ReporterPointSource::errorCheck(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), ExtraElementIDAux::ExtraElementIDAux(), ExtraElementIntegerDivision::ExtraElementIntegerDivision(), FEProblemSolve::FEProblemSolve(), FillBetweenCurvesGenerator::FillBetweenCurvesGenerator(), FillBetweenSidesetsGenerator::FillBetweenSidesetsGenerator(), ReporterPointSource::fillPoint(), SpatialUserObjectVectorPostprocessor::fillPoints(), CombinerGenerator::fillPositions(), MultiApp::fillPositions(), InternalSideIndicator::finalize(), FixedPointSolve::FixedPointSolve(), ForcingFunctionAux::ForcingFunctionAux(), FunctionArrayAux::FunctionArrayAux(), FunctionValuePostprocessor::FunctionValuePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorAux::FunctorAux(), FunctorBinnedValuesDivision::FunctorBinnedValuesDivision(), FunctorElementalGradientAuxTempl< is_ad >::FunctorElementalGradientAuxTempl(), FunctorPositions::FunctorPositions(), FunctorVectorElementalAuxTempl< is_ad >::FunctorVectorElementalAuxTempl(), FVFluxBC::FVFluxBC(), FVInterfaceKernel::FVInterfaceKernel(), FVOneVarDiffusionInterface::FVOneVarDiffusionInterface(), FVTwoVarContinuityConstraint::FVTwoVarContinuityConstraint(), AdvancedExtruderGenerator::generate(), BlockDeletionGenerator::generate(), BlockToMeshConverterGenerator::generate(), BoundaryDeletionGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), BreakMeshByBlockGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), CombinerGenerator::generate(), ExplodeMeshGenerator::generate(), ExtraNodesetGenerator::generate(), FillBetweenCurvesGenerator::generate(), FillBetweenSidesetsGenerator::generate(), GeneratedMeshGenerator::generate(), MeshCollectionGenerator::generate(), MeshExtruderGenerator::generate(), ParsedCurveGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), PatternedMeshGenerator::generate(), PlaneIDMeshGenerator::generate(), RefineBlockGenerator::generate(), RefineSidesetGenerator::generate(), RenameBlockGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), StackGenerator::generate(), StitchedMeshGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), PropertyReadFile::getBlockData(), PropertyReadFile::getData(), Sampler::getGlobalSamples(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), Sampler::getLocalSamples(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), Sampler::getNextLocalRow(), PostprocessorInterface::getPostprocessorNameInternal(), PostprocessorInterface::getPostprocessorValueInternal(), MultiAppNearestNodeTransfer::getTargetLocalNodes(), UserObjectInterface::getUserObjectBase(), UserObjectInterface::getUserObjectName(), HFEMDirichletBC::HFEMDirichletBC(), MultiApp::init(), BlockWeightedPartitioner::initialize(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), PiecewiseConstantFromCSV::initialSetup(), LibtorchControlValuePostprocessor::initialSetup(), ReferenceResidualProblem::initialSetup(), MultiAppCloneReporterTransfer::initialSetup(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), MultiAppVariableValueSamplePostprocessorTransfer::initialSetup(), HistogramVectorPostprocessor::initialSetup(), AddMetaDataGenerator::inputChecker(), IntegratedBC::IntegratedBC(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceValueUserObjectAux::InterfaceValueUserObjectAux(), InterpolatedStatefulMaterialTempl< T >::InterpolatedStatefulMaterialTempl(), InversePowerMethod::InversePowerMethod(), IterationAdaptiveDT::IterationAdaptiveDT(), MultiApp::keepSolutionDuringRestore(), Kernel::Kernel(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), LinearCombinationFunction::LinearCombinationFunction(), LowerDIntegratedBC::LowerDIntegratedBC(), PNGOutput::makeMeshFunc(), MatCoupledForce::MatCoupledForce(), MaterialADConverterTempl< T >::MaterialADConverterTempl(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), PatternedMeshGenerator::mergeSubdomainNameMaps(), MeshCollectionGenerator::MeshCollectionGenerator(), MeshDiagnosticsGenerator::MeshDiagnosticsGenerator(), MeshDivisionAux::MeshDivisionAux(), MeshGenerator::MeshGenerator(), MoosePreconditioner::MoosePreconditioner(), MooseVariableBase::MooseVariableBase(), MortarConstraintBase::MortarConstraintBase(), MortarNodalAuxKernelTempl< ComputeValueType >::MortarNodalAuxKernelTempl(), MultiApp::moveApp(), MoveNodeGenerator::MoveNodeGenerator(), MultiApp::MultiApp(), MultiAppCloneReporterTransfer::MultiAppCloneReporterTransfer(), MultiAppGeneralFieldNearestLocationTransfer::MultiAppGeneralFieldNearestLocationTransfer(), MultiAppGeneralFieldShapeEvaluationTransfer::MultiAppGeneralFieldShapeEvaluationTransfer(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppGeometricInterpolationTransfer::MultiAppGeometricInterpolationTransfer(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppPostprocessorInterpolationTransfer::MultiAppPostprocessorInterpolationTransfer(), MultiAppPostprocessorToAuxScalarTransfer::MultiAppPostprocessorToAuxScalarTransfer(), MultiAppPostprocessorTransfer::MultiAppPostprocessorTransfer(), MultiAppProjectionTransfer::MultiAppProjectionTransfer(), MultiAppReporterTransfer::MultiAppReporterTransfer(), MultiAppScalarToAuxScalarTransfer::MultiAppScalarToAuxScalarTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), MultiAppVariableValueSampleTransfer::MultiAppVariableValueSampleTransfer(), MultiAppVectorPostprocessorTransfer::MultiAppVectorPostprocessorTransfer(), NestedDivision::NestedDivision(), NodalBC::NodalBC(), NodalEqualValueConstraint::NodalEqualValueConstraint(), NodalKernel::NodalKernel(), NodalPatchRecoveryAux::NodalPatchRecoveryAux(), NodalValueSampler::NodalValueSampler(), Output::Output(), ParsedCurveGenerator::ParsedCurveGenerator(), ParsedElementDeletionGenerator::ParsedElementDeletionGenerator(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), ParsedGenerateSideset::ParsedGenerateSideset(), ParsedNodeTransformGenerator::ParsedNodeTransformGenerator(), PatchMeshGenerator::PatchMeshGenerator(), PatternedMeshGenerator::PatternedMeshGenerator(), PenaltyPeriodicSegmentalConstraint::PenaltyPeriodicSegmentalConstraint(), PeriodicSegmentalConstraint::PeriodicSegmentalConstraint(), PIDTransientControl::PIDTransientControl(), PlaneDeletionGenerator::PlaneDeletionGenerator(), PlaneIDMeshGenerator::PlaneIDMeshGenerator(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), PolyLineMeshGenerator::PolyLineMeshGenerator(), ReporterInterface::possiblyCheckHasReporter(), VectorPostprocessorInterface::possiblyCheckHasVectorPostprocessor(), LibmeshPartitioner::prepareBlocksForSubdomainPartitioner(), ProjectedMaterialPropertyNodalPatchRecoveryAux::ProjectedMaterialPropertyNodalPatchRecoveryAux(), PropertyReadFile::PropertyReadFile(), RandomIC::RandomIC(), MultiApp::readCommandLineArguments(), PropertyReadFile::readData(), SolutionUserObject::readXda(), ReferenceResidualProblem::ReferenceResidualProblem(), RefineBlockGenerator::RefineBlockGenerator(), RefineSidesetGenerator::RefineSidesetGenerator(), RenameBlockGenerator::RenameBlockGenerator(), RenameBoundaryGenerator::RenameBoundaryGenerator(), ReporterPointSource::ReporterPointSource(), SecondTimeDerivativeAux::SecondTimeDerivativeAux(), MooseMesh::setPartitioner(), TimeSequenceStepperBase::setupSequence(), SingleRankPartitioner::SingleRankPartitioner(), SphericalGridDivision::SphericalGridDivision(), SymmetryTransformGenerator::SymmetryTransformGenerator(), Terminator::Terminator(), TimeDerivativeAux::TimeDerivativeAux(), Transfer::Transfer(), TransformGenerator::TransformGenerator(), TransientMultiApp::TransientMultiApp(), ParsedCurveGenerator::tSectionSpaceDefiner(), UniqueExtraIDMeshGenerator::UniqueExtraIDMeshGenerator(), UserObject::UserObject(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), VolumeAux::VolumeAux(), XYDelaunayGenerator::XYDelaunayGenerator(), and XYMeshLineCutter::XYMeshLineCutter().
paramErrorMsg()
template<typename... Args> std::string MooseBaseParameterInterface::paramErrorMsg (const std::string & param, Args... args) const inline private inherited
Definition at line 171 of file MooseBaseParameterInterface.h.
  {
    auto param_prefix = paramErrorPrefix(_pars, param);
    // With no input location information, append object info (name + type)
    const std::string object_prefix =
        _pars.inputLocation(param).empty() ? objectErrorPrefix("parameter error") : "";
    std::ostringstream oss;
    moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
    std::string msg = oss.str();
    // Wrap error message to a separate line from param_prefix if it is about to
    // blow past 100 chars.  But only wrap if the param_prefix is long enough (12
    // chars) for the wrap to buy us much extra length. We don't check object_prefix
    // here because it will go before the parameter error
    if ((param_prefix.size() > 12 && msg.size() + param_prefix.size() > 99) ||
        msg.find("\n") != std::string::npos)
    {
      if (param_prefix.size() > 0 && param_prefix[param_prefix.size() - 1] != ':')
        param_prefix += ":";
      return object_prefix + param_prefix + "\n    " + MooseUtils::replaceAll(msg, "\n", "\n    ");
    }
    return object_prefix + param_prefix + " " + msg;
  }
Referenced by MooseBaseParameterInterface::paramError(), MooseBaseParameterInterface::paramInfo(), and MooseBaseParameterInterface::paramWarning().
parameters()
const InputParameters & MooseBaseParameterInterface::parameters () const inline inherited
Get the parameters of the object.
Returns
The parameters of the object
Definition at line 53 of file MooseBaseParameterInterface.h.
{ return _pars; }
Referenced by SetupDebugAction::act(), FEProblemBase::addAuxKernel(), FEProblemBase::addAuxScalarKernel(), DisplacedProblem::addAuxVariable(), FEProblemBase::addBoundaryCondition(), FEProblemBase::addConstraint(), FEProblemBase::addDamper(), FEProblemBase::addDGKernel(), FEProblemBase::addDiracKernel(), FEProblemBase::addDistribution(), FEProblemBase::addFunction(), FEProblemBase::addFunctorMaterial(), FEProblemBase::addFVBC(), FEProblemBase::addFVInitialCondition(), FEProblemBase::addFVInterfaceKernel(), FEProblemBase::addFVKernel(), FEProblemBase::addIndicator(), FEProblemBase::addInitialCondition(), FEProblemBase::addInterfaceKernel(), FEProblemBase::addInterfaceMaterial(), FEProblemBase::addKernel(), FEProblem::addLineSearch(), FEProblemBase::addMarker(), FEProblemBase::addMaterial(), FEProblemBase::addMaterialHelper(), FEProblemBase::addMeshDivision(), FEProblemBase::addMultiApp(), FEProblemBase::addNodalKernel(), FEProblemBase::addObject(), FEProblemBase::addObjectParamsHelper(), FEProblemBase::addOutput(), FEProblemBase::addPostprocessor(), FEProblemBase::addPredictor(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), FEProblemBase::addScalarKernel(), FEProblemBase::addTimeIntegrator(), FEProblemBase::addTransfer(), FEProblemBase::addUserObject(), DisplacedProblem::addVariable(), FEProblemBase::addVectorPostprocessor(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), AdvancedOutput::AdvancedOutput(), AnnularMesh::AnnularMesh(), AnnularMeshGenerator::AnnularMeshGenerator(), Moose::assemble_matrix(), AuxScalarKernel::AuxScalarKernel(), BoundsAuxBase::BoundsAuxBase(), MooseMesh::buildTypedMesh(), UserObjectInterface::castUserObject(), PostprocessorInterface::checkParam(), LibmeshPartitioner::clone(), OversampleOutput::cloneMesh(), Moose::compute_bounds(), Moose::compute_jacobian(), Moose::compute_nearnullspace(), Moose::compute_nullspace(), Moose::compute_postcheck(), Moose::compute_transpose_nullspace(), LibtorchNeuralNetControl::conditionalParameterError(), Console::Console(), MultiApp::createApp(), Postprocessor::declareValue(), DumpObjectsProblem::deduceNecessaryParameters(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), DumpObjectsProblem::dumpObjectHelper(), EigenProblem::EigenProblem(), Eigenvalue::Eigenvalue(), ElectronsFromIonization::ElectronsFromIonization(), Executor::Executor(), Exodus::Exodus(), FEProblem::FEProblem(), FEProblemBase::FEProblemBase(), FixedPointSolve::FixedPointSolve(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GapValueAux::GapValueAux(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), MooseBaseParameterInterface::getCheckedPointerParam(), ExecutorInterface::getExecutor(), Material::getMaterial(), ReporterInterface::getReporterName(), Reporter::getReporterValueName(), UserObjectInterface::getUserObjectName(), VectorPostprocessorInterface::getVectorPostprocessorName(), GhostingUserObject::GhostingUserObject(), HphiRadialInterface::HphiRadialInterface(), AttribSystem::initFrom(), AttribDisplaced::initFrom(), BlockRestrictable::initializeBlockRestrictable(), FullSolveMultiApp::initialSetup(), FEProblemBase::initNullSpaceVectors(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), isValid(), IterationAdaptiveDT::IterationAdaptiveDT(), LibtorchNeuralNetControl::LibtorchNeuralNetControl(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseAppCoordTransform::MooseAppCoordTransform(), MooseVariableInterface< T >::MooseVariableInterface(), MultiApp::MultiApp(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), MultiAppGeneralFieldUserObjectTransfer::MultiAppGeneralFieldUserObjectTransfer(), MultiAppTransfer::MultiAppTransfer(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NodeFaceConstraint::NodeFaceConstraint(), PatchMeshGenerator::PatchMeshGenerator(), PenetrationAux::PenetrationAux(), PicardSolve::PicardSolve(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), ProjectedStatefulMaterialStorageAction::processProperty(), MultiAppProjectionTransfer::projectSolution(), PropertyReadFile::PropertyReadFile(), PseudoTimestep::PseudoTimestep(), RandomIC::RandomIC(), InputParameterWarehouse::removeInputParameters(), OutputWarehouse::resetFileBase(), MooseAppCoordTransform::setCoordinateSystem(), FEProblemBase::setInputParametersFEProblem(), FEProblem::setInputParametersFEProblem(), SideSetsFromBoundingBoxGenerator::SideSetsFromBoundingBoxGenerator(), SteffensenSolve::SteffensenSolve(), DumpObjectsProblem::stringifyParameters(), TaggingInterface::TaggingInterface(), Transfer::Transfer(), Transient::Transient(), VectorBodyForce::VectorBodyForce(), VectorFunctionDirichletBC::VectorFunctionDirichletBC(), VectorFunctionIC::VectorFunctionIC(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
paramInfo()
template<typename... Args> void MooseBaseParameterInterface::paramInfo (const std::string & param, Args... args) const inherited
Emits an informational message prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseInfo - only printing a message using the given args.
Definition at line 250 of file MooseBaseParameterInterface.h.
{
  mooseInfo(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by TransientMultiApp::TransientMultiApp().
paramWarning()
template<typename... Args> void MooseBaseParameterInterface::paramWarning (const std::string & param, Args... args) const inherited
Emits a warning prefixed with the file and line number of the given param (from the input file) along with the full parameter path+name followed by the given args as the message.
If this object's parameters were not created directly by the Parser, then this function falls back to the normal behavior of mooseWarning - only printing a message using the given args.
Definition at line 243 of file MooseBaseParameterInterface.h.
{
  mooseWarning(paramErrorMsg(param, std::forward<Args>(args)...));
}
Referenced by MultiAppNearestNodeTransfer::execute(), FEProblemSolve::FEProblemSolve(), PlaneIDMeshGenerator::generate(), UniqueExtraIDMeshGenerator::generate(), Terminator::initialSetup(), and MooseMesh::MooseMesh().
phi()
template<typename OutputType > const FieldVariablePhiValue & MooseVariableFV< OutputType >::phi () const inline final override virtual
Return the variable's elemental shape functions.
Implements MooseVariableField< OutputType >.
Definition at line 573 of file MooseVariableFV.h.
{ return _phi; }
phiFace()
template<typename OutputType > const FieldVariablePhiValue & MooseVariableFV< OutputType >::phiFace () const inline final override virtual
Return the variable's shape functions on an element face.
Implements MooseVariableField< OutputType >.
Definition at line 588 of file MooseVariableFV.h.
{ return _phi_face; }
phiFaceNeighbor()
template<typename OutputType > const FieldVariablePhiValue & MooseVariableFV< OutputType >::phiFaceNeighbor () const inline final override virtual
Return the variable's shape functions on a neighboring element face.
Implements MooseVariableField< OutputType >.
Definition at line 595 of file MooseVariableFV.h.
  {
    return _phi_face_neighbor;
  }
phiFaceNeighborSize()
template<typename OutputType > virtual std::size_t MooseVariableFV< OutputType >::phiFaceNeighborSize () const inline final override virtual
Return phiFaceNeighbor size.
Implements MooseVariableFieldBase.
Definition at line 123 of file MooseVariableFV.h.
  {
    return _phi_face_neighbor.size();
  }
phiFaceSize()
template<typename OutputType > virtual std::size_t MooseVariableFV< OutputType >::phiFaceSize () const inline final override virtual
Return phiFace size.
Implements MooseVariableFieldBase.
Definition at line 121 of file MooseVariableFV.h.
{ return _phi_face.size(); }
phiLower()
template<typename OutputType > const MooseVariableFV< OutputType >::FieldVariablePhiValue & MooseVariableFV< OutputType >::phiLower () const override virtual
Return the variable's shape functions on a lower-dimensional element.
Implements MooseVariableField< OutputType >.
Definition at line 820 of file MooseVariableFV.h.
{
  mooseError("Not defined for finite volume variables");
}
phiLowerSize()
template<typename OutputType > virtual std::size_t MooseVariableFV< OutputType >::phiLowerSize () const inline final override virtual
Return the number of shape functions on the lower dimensional element for this variable.
Implements MooseVariableFieldBase.
Definition at line 127 of file MooseVariableFV.h.
  {
    mooseError("phiLowerSize not supported by MooseVariableFVBase");
  }
phiNeighbor()
template<typename OutputType > const FieldVariablePhiValue & MooseVariableFV< OutputType >::phiNeighbor () const inline final override virtual
Return the variable's shape functions on a neighboring element.
Implements MooseVariableField< OutputType >.
Definition at line 608 of file MooseVariableFV.h.
{ return _phi_neighbor; }
phiNeighborSize()
template<typename OutputType > virtual std::size_t MooseVariableFV< OutputType >::phiNeighborSize () const inline final override virtual
Return phiNeighbor size.
Implements MooseVariableFieldBase.
Definition at line 122 of file MooseVariableFV.h.
{ return _phi_neighbor.size(); }
phiSize()
template<typename OutputType > virtual std::size_t MooseVariableFV< OutputType >::phiSize () const inline final override virtual
Return phi size.
Implements MooseVariableFieldBase.
Definition at line 120 of file MooseVariableFV.h.
{ return _phi.size(); }
prepare()
template<typename OutputType > virtual void MooseVariableFV< OutputType >::prepare () inline final override virtual
Prepare the elemental degrees of freedom.
Implements MooseVariableFieldBase.
Definition at line 102 of file MooseVariableFV.h.
{}
prepareAux()
template<typename OutputType > void MooseVariableFV< OutputType >::prepareAux final override virtual
Implements MooseVariableFieldBase.
Definition at line 842 of file MooseVariableFV.C.
{
  _element_data->prepareAux();
  _neighbor_data->prepareAux();
}
prepareIC()
template<typename OutputType > void MooseVariableFV< OutputType >::prepareIC () override virtual
Prepare the initial condition.
Implements MooseVariableFieldBase.
Definition at line 300 of file MooseVariableFV.C.
{
  _element_data->prepareIC();
}
prepareLowerD()
template<typename OutputType > virtual void MooseVariableFV< OutputType >::prepareLowerD () inline final override virtual
Prepare a lower dimensional element's degrees of freedom.
Implements MooseVariableFieldBase.
Definition at line 110 of file MooseVariableFV.h.
{}
prepareNeighbor()
template<typename OutputType > virtual void MooseVariableFV< OutputType >::prepareNeighbor () inline final override virtual
Prepare the neighbor element degrees of freedom.
Implements MooseVariableFieldBase.
Definition at line 103 of file MooseVariableFV.h.
{}
queryFVArgCache()
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::queryFVArgCache (std::map< SpaceArg, ValueType > & cache_data, const SpaceArg & space) const private inherited
check a finite volume spatial argument cache and if invalid then evaluate
Definition at line 407 of file MooseFunctor.h.
{
  // We don't want to evaluate if the key already exists, so instead we value initialize
  auto [it, inserted] = cache_data.try_emplace(space, ValueType());
  auto & value = it->second;
  if (inserted)
    // value not ready to go
    // this function is only called from functions that assert we are in the current time state
    value = evaluate(space, currentState());
  return value;
}
queryQpCache()
FunctorBase< Moose::ADType< OutputType >::type >::ValueType Moose::FunctorBase< Moose::ADType< OutputType >::type >::queryQpCache (unsigned int qp, const QBase & qrule, std::vector< std::pair< bool, Moose::ADType< OutputType >::type > > & qp_cache_data, const SpaceArg & space, const StateArg & state) const private inherited
check a qp cache and if invalid then evaluate
Definition at line 397 of file MooseFunctor.h.
{
  // Check and see whether we even have sized for this quadrature point. If we haven't then we
  // must evaluate
  if (qp >= qp_cache_data.size())
  {
    qp_cache_data.resize(qrule.n_points(), std::make_pair(false, ValueType()));
    auto & pr = qp_cache_data[qp];
    pr.second = evaluate(space, state);
    pr.first = true;
    return pr.second;
  }
  // We've already sized for this qp, so let's see whether we have a valid cache value
  auto & pr = qp_cache_data[qp];
  if (pr.first)
    return pr.second;
  // No valid cache value so evaluate
  pr.second = evaluate(space, state);
  pr.first = true;
  return pr.second;
}
reinitAux()
template<typename OutputType > virtual void MooseVariableFV< OutputType >::reinitAux () inline final override virtual
Implements MooseVariableFieldBase.
Definition at line 108 of file MooseVariableFV.h.
{}
reinitAuxNeighbor()
template<typename OutputType > virtual void MooseVariableFV< OutputType >::reinitAuxNeighbor () inline final override virtual
Implements MooseVariableFieldBase.
Definition at line 109 of file MooseVariableFV.h.
{}
reinitNode()
template<typename OutputType > virtual void MooseVariableFV< OutputType >::reinitNode () inline final override virtual
Implements MooseVariableFieldBase.
Definition at line 105 of file MooseVariableFV.h.
{}
reinitNodes()
template<typename OutputType > virtual void MooseVariableFV< OutputType >::reinitNodes (const std::vector< dof_id_type > &) inline final override virtual
Implements MooseVariableFieldBase.
Definition at line 106 of file MooseVariableFV.h.
{}
reinitNodesNeighbor()
template<typename OutputType > virtual void MooseVariableFV< OutputType >::reinitNodesNeighbor (const std::vector< dof_id_type > &) inline final override virtual
Implements MooseVariableFieldBase.
Definition at line 107 of file MooseVariableFV.h.
{}
requireQpComputations()
template<typename OutputType > virtual void MooseVariableFV< OutputType >::requireQpComputations () const inline virtual
Request that quadrature point data be (pre)computed.
Quadrature point data is (pre)computed by default for this base class but derived variable classes may choose not to unless this API is called
Definition at line 474 of file MooseVariableFV.h.
{}
Referenced by FVTimeKernel::FVTimeKernel().
residualSetup()
template<typename OutputType > void MooseVariableFV< OutputType >::residualSetup override virtual
Reimplemented from MooseVariableField< OutputType >.
Definition at line 708 of file MooseVariableFV.C.
{
  clearCaches();
}
scalingFactor() [1/3]
Real MooseVariableBase::scalingFactor () const inline inherited
Get the scaling factor for this variable.
Definition at line 96 of file MooseVariableBase.h.
{ return _scaling_factor[0]; }
Referenced by MooseVariableBase::MooseVariableBase().
scalingFactor() [2/3]
void MooseVariableBase::scalingFactor (const std::vector< Real > & factor) inherited
Definition at line 181 of file MooseVariableBase.C.
{
  _scaling_factor = factor;
}
scalingFactor() [3/3]
void MooseVariableBase::scalingFactor (Real factor) inherited
Set the scaling factor for this variable.
Definition at line 175 of file MooseVariableBase.C.
{
  _scaling_factor.assign(_count, factor);
}
Referenced by ADScalarKernel::computeADJacobian(), ADDGKernel::computeElemNeighJacobian(), ADMortarScalarBase::computeJacobian(), FVElementalKernel::computeJacobian(), ADKernelScalarBase::computeJacobian(), ADNodalKernel::computeJacobian(), NodalKernel::computeJacobian(), FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVScalarLagrangeMultiplierInterface::computeJacobian(), ADMortarConstraint::computeJacobian(), NodalConstraint::computeJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), FVScalarLagrangeMultiplierConstraint::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), ADMortarScalarBase::computeResidual(), MortarScalarBase::computeResidual(), ADKernelScalarBase::computeResidual(), ADNodalKernel::computeResidual(), NodalKernel::computeResidual(), TimeNodalKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), FVScalarLagrangeMultiplierInterface::computeResidual(), NodalConstraint::computeResidual(), FVElementalKernel::computeResidualAndJacobian(), ADKernelScalarBase::computeResidualAndJacobian(), FVScalarLagrangeMultiplierConstraint::computeResidualAndJacobian(), MortarScalarBase::computeScalarJacobian(), KernelScalarBase::computeScalarJacobian(), MortarScalarBase::computeScalarOffDiagJacobian(), KernelScalarBase::computeScalarOffDiagJacobian(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarResidual(), ScalarTagMatrixAux::computeValue(), ScalarTagVectorAux::computeValue(), TagMatrixAux::computeValue(), TagVectorAux::computeValue(), and ReferenceResidualProblem::initialSetup().
secondPhi()
template<typename OutputType > const FieldVariablePhiSecond & MooseVariableFV< OutputType >::secondPhi () const inline final override virtual
Return the rank-2 tensor of second derivatives of the variable's elemental shape functions.
Implements MooseVariableField< OutputType >.
Definition at line 575 of file MooseVariableFV.h.
  {
    mooseError("We don't currently implement second derivatives for FV");
  }
Referenced by MooseVariableInterface< T >::secondPhi().
secondPhiFace()
template<typename OutputType > const FieldVariablePhiSecond & MooseVariableFV< OutputType >::secondPhiFace () const inline final override virtual
Return the rank-2 tensor of second derivatives of the variable's shape functions on an element face.
Implements MooseVariableField< OutputType >.
Definition at line 590 of file MooseVariableFV.h.
  {
    mooseError("We don't currently implement second derivatives for FV");
  }
Referenced by MooseVariableInterface< T >::secondPhiFace().
secondPhiFaceNeighbor()
template<typename OutputType > const FieldVariablePhiSecond & MooseVariableFV< OutputType >::secondPhiFaceNeighbor () const inline final override virtual
Return the rank-2 tensor of second derivatives of the variable's shape functions on a neighboring element face.
Implements MooseVariableField< OutputType >.
Definition at line 603 of file MooseVariableFV.h.
  {
    mooseError("We don't currently implement second derivatives for FV");
  }
secondPhiNeighbor()
template<typename OutputType > const FieldVariablePhiSecond & MooseVariableFV< OutputType >::secondPhiNeighbor () const inline final override virtual
Return the rank-2 tensor of second derivatives of the variable's shape functions on a neighboring element.
Implements MooseVariableField< OutputType >.
Definition at line 613 of file MooseVariableFV.h.
  {
    mooseError("We don't currently implement second derivatives for FV");
  }
setActiveTags()
template<typename OutputType > void MooseVariableFV< OutputType >::setActiveTags (const std::set< TagID > & vtags) override virtual
Set the active vector tags.
Parameters
vtags Additional vector tags that this variable will need to query at dof indices for, in addition to our own required solution tags
Reimplemented from MooseVariableBase.
Definition at line 787 of file MooseVariableFV.h.
{
  _element_data->setActiveTags(vtags);
  _neighbor_data->setActiveTags(vtags);
}
setCacheClearanceSchedule()
void Moose::FunctorBase< Moose::ADType< OutputType >::type >::setCacheClearanceSchedule (const std::set< ExecFlagType > & clearance_schedule) inherited
Set how often to clear the functor evaluation cache.
Definition at line 139 of file MooseFunctor.h.
{
  _clearance_schedule = clearance_schedule;
}
setDofValue()
template<typename OutputType > void MooseVariableFV< OutputType >::setDofValue (const OutputData & value, unsigned int index) override virtual
Degree of freedom value setters.
Implements MooseVariableField< OutputType >.
Definition at line 386 of file MooseVariableFV.C.
{
  _element_data->setDofValue(value, index);
}
setDofValues()
template<typename OutputType > void MooseVariableFV< OutputType >::setDofValues (const DenseVector< OutputData > & values) override virtual
Set local DOF values and evaluate the values on quadrature points.
Implements MooseVariableField< OutputType >.
Definition at line 393 of file MooseVariableFV.C.
{
  _element_data->setDofValues(values);
}
setNodalValue()
template<typename OutputType > void MooseVariableFV< OutputType >::setNodalValue (const OutputType & value, unsigned int idx = 0) override virtual
Implements MooseVariableField< OutputType >.
Definition at line 379 of file MooseVariableFV.C.
{
  mooseError("FV variables do not support setNodalValue");
}
sln()
template<typename OutputType > const FieldVariableValue & MooseVariableFV< OutputType >::sln () const inline override virtual
Returns
the current elemental solution
Implements MooseVariableField< OutputType >.
Definition at line 224 of file MooseVariableFV.h.
{ return _element_data->sln(Moose::Current); }
slnNeighbor()
template<typename OutputType > const FieldVariableValue & MooseVariableFV< OutputType >::slnNeighbor () const inline override virtual
Returns
the current neighbor solution
Implements MooseVariableField< OutputType >.
Definition at line 236 of file MooseVariableFV.h.
  {
    return _neighbor_data->sln(Moose::Current);
  }
slnOld()
template<typename OutputType > const FieldVariableValue & MooseVariableFV< OutputType >::slnOld () const inline override virtual
Returns
the old elemental solution, e.g. that of the previous timestep
Implements MooseVariableField< OutputType >.
Definition at line 225 of file MooseVariableFV.h.
{ return _element_data->sln(Moose::Old); }
slnOlder()
template<typename OutputType > const FieldVariableValue & MooseVariableFV< OutputType >::slnOlder () const inline override virtual
Returns
the older elemental solution, e.g. that of two timesteps ago
Implements MooseVariableField< OutputType >.
Definition at line 226 of file MooseVariableFV.h.
{ return _element_data->sln(Moose::Older); }
slnOldNeighbor()
template<typename OutputType > const FieldVariableValue & MooseVariableFV< OutputType >::slnOldNeighbor () const inline override virtual
Returns
the old neighbor solution, e.g. that of the previous timestep
Implements MooseVariableField< OutputType >.
Definition at line 240 of file MooseVariableFV.h.
  {
    return _neighbor_data->sln(Moose::Old);
  }
subdomainSetup()
void SetupInterface::subdomainSetup () virtual inherited
Gets called when the subdomain changes (i.e.
in a Jacobian or residual loop) and before this object is asked to do its job
Reimplemented in Material, MaterialBase, GeneralUserObject, NodalUserObject, ThreadedGeneralUserObject, and Constraint.
Definition at line 60 of file SetupInterface.C.
{
}
sys() [1/2]
SystemBase & MooseVariableBase::sys () inline inherited
Get the system this variable is part of.
Definition at line 59 of file MooseVariableBase.h.
{ return _sys; }
Referenced by ADDGKernel::ADDGKernel(), FEProblemBase::addInitialCondition(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), MultiAppConservativeTransfer::adjustTransferredSolution(), MultiAppConservativeTransfer::adjustTransferredSolutionNearestPoint(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldShapeEvaluationTransfer::buildMeshFunctions(), MooseMesh::cacheFaceInfoVariableOwnership(), FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), FVFluxBC::computeResidual(), FVInterfaceKernel::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), Moose::FV::determineElemOneAndTwo(), DGKernel::DGKernel(), MultiAppGeometricInterpolationTransfer::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppProjectionTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppUserObjectTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), MultiAppVariableValueSampleTransfer::execute(), MultiAppGeometricInterpolationTransfer::fillSourceInterpolationPoints(), FVBoundaryCondition::hasFaceSide(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), MultiAppGeometricInterpolationTransfer::interpolateTargetPoints(), Kernel::Kernel(), NodalBC::NodalBC(), NodalKernel::NodalKernel(), Exodus::outputScalarVariables(), Nemesis::outputScalarVariables(), TableOutput::outputScalarVariables(), FEProblemBase::projectInitialConditionOnCustomRange(), FEProblemBase::projectSolution(), MultiAppProjectionTransfer::projectSolution(), MooseVariableScalar::reinit(), FVInterfaceKernel::setupData(), MultiAppDofCopyTransfer::transfer(), MultiAppDofCopyTransfer::transferDofObject(), MultiAppShapeEvaluationTransfer::transferVariable(), FVFluxBC::uOnGhost(), and FVFluxBC::uOnUSub().
sys() [2/2]
const SystemBase & MooseVariableBase::sys () const inline inherited
Get the system this variable is part of.
Definition at line 64 of file MooseVariableBase.h.
{ return _sys; }
timestepSetup()
template<typename OutputType > void MooseVariableFV< OutputType >::timestepSetup override virtual
Reimplemented from MooseVariableField< OutputType >.
Definition at line 812 of file MooseVariableFV.h.
{
  _dirichlet_map_setup = false;
  MooseVariableField<OutputType>::timestepSetup();
}
totalVarDofs()
unsigned int MooseVariableBase::totalVarDofs () inline inherited
Definition at line 80 of file MooseVariableBase.h.
{ return allDofIndices().size(); }
type()
const std::string & MooseBase::type () const inline inherited
Get the type of this class.
Returns
the name of the type of this class
Definition at line 41 of file MooseBase.h.
{ return _type; }
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), CreateProblemDefaultAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), SetupDebugAction::act(), FEProblemBase::addAuxArrayVariable(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), FEProblemBase::addDistribution(), DistributedRectilinearMeshGenerator::addElement(), FEProblemBase::addFunction(), FEProblemBase::addMeshDivision(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addObject(), DistributedRectilinearMeshGenerator::addPoint(), FEProblemBase::addPredictor(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), FEProblemBase::addReporter(), FEProblemBase::addSampler(), PhysicsBasedPreconditioner::addSystem(), FEProblemBase::addTimeIntegrator(), SubProblem::addVectorTag(), DisplacedProblem::addVectorTag(), FEProblemBase::advanceMultiApps(), FEProblemBase::backupMultiApps(), BoundaryPreservedMarker::BoundaryPreservedMarker(), DistributedRectilinearMeshGenerator::buildCube(), MooseMesh::buildHRefinementAndCoarseningMaps(), MooseMesh::buildPRefinementAndCoarseningMaps(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), FEProblemBase::computeAuxiliaryKernels(), ElemElemConstraint::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), DGKernel::computeElemNeighJacobian(), ADDGKernel::computeElemNeighJacobian(), ElemElemConstraint::computeElemNeighResidual(), ArrayDGKernel::computeElemNeighResidual(), DGKernel::computeElemNeighResidual(), ADDGKernel::computeElemNeighResidual(), ArrayDGLowerDKernel::computeLowerDJacobian(), DGLowerDKernel::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDJacobian(), LowerDIntegratedBC::computeLowerDJacobian(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpJacobian(), HFEMDirichletBC::computeLowerDQpJacobian(), ArrayHFEMDiffusion::computeLowerDQpJacobian(), HFEMDiffusion::computeLowerDQpJacobian(), ArrayLowerDIntegratedBC::computeLowerDQpOffDiagJacobian(), ArrayDGLowerDKernel::computeLowerDQpOffDiagJacobian(), ArrayHFEMDirichletBC::computeLowerDQpOffDiagJacobian(), HFEMDirichletBC::computeLowerDQpOffDiagJacobian(), FEProblemBase::computeMultiAppsDT(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), DGKernel::computeOffDiagElemNeighJacobian(), ADDGKernel::computeOffDiagElemNeighJacobian(), DGCoupledAdvection::computeOffDiagJacobianHelper(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), ScalarKernel::computeQpJacobian(), ArbitrarilyTiedValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueBoundaryConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), LinearNodalConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), DGConvection::computeQpJacobian(), ArrayDGDiffusion::computeQpJacobian(), DGDiffusion::computeQpJacobian(), InterfaceDiffusion::computeQpJacobian(), InterfaceReaction::computeQpJacobian(), DGCoupledAdvection::computeQpJacobian(), DGFunctionConvection::computeQpJacobian(), DGFunctionTemperatureAdvection::computeQpJacobian(), DGTemperatureAdvection::computeQpJacobian(), InterTemperatureAdvection::computeQpJacobian(), CoupledTiedValueConstraint::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), ArrayDGKernel::computeQpOffDiagJacobian(), HFEMTestJump::computeQpOffDiagJacobian(), HFEMTrialJump::computeQpOffDiagJacobian(), DGCoupledAdvection::computeQpOffDiagJacobian(), ScalarKernel::computeQpResidual(), ArbitrarilyTiedValueConstraint::computeQpResidual(), CoupledTiedValueConstraint::computeQpResidual(), EqualValueBoundaryConstraint::computeQpResidual(), EqualValueEmbeddedConstraint::computeQpResidual(), LinearNodalConstraint::computeQpResidual(), TiedValueConstraint::computeQpResidual(), DGConvection::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), DGEFieldAdvection::computeQpResidual(), HphiRadialInterface::computeQpResidual(), InterfaceAdvection::computeQpResidual(), InterfaceLogDiffusionElectrons::computeQpResidual(), PotentialSurfaceCharge::computeQpResidual(), ADDGAdvection::computeQpResidual(), ADDGDiffusion::computeQpResidual(), DGDiffusion::computeQpResidual(), HFEMDiffusion::computeQpResidual(), HFEMTestJump::computeQpResidual(), HFEMTrialJump::computeQpResidual(), InterfaceDiffusion::computeQpResidual(), InterfaceReaction::computeQpResidual(), DGCoupledAdvection::computeQpResidual(), DGFunctionConvection::computeQpResidual(), DGFunctionTemperatureAdvection::computeQpResidual(), DGTemperatureAdvection::computeQpResidual(), InterTemperatureAdvection::computeQpResidual(), ArrayDGDiffusion::computeQpResidual(), ArrayHFEMDiffusion::computeQpResidual(), FEProblemBase::computeUserObjectByName(), FEProblemBase::computeUserObjects(), FEProblemBase::computeUserObjectsInternal(), BatchMaterial< Tuple, Output, Input >::construct(), DisplacedProblem::createQRules(), FEProblemBase::createQRules(), MeshGenerator::declareMeshProperty(), DumpObjectsProblem::deduceNecessaryParameters(), DumpObjectsProblem::dumpObjectHelper(), FEProblemBase::duplicateVariableCheck(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), MooseBaseErrorInterface::errorPrefix(), AB2PredictorCorrector::estimateTimeError(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finishMultiAppStep(), FVScalarLagrangeMultiplierInterface::FVScalarLagrangeMultiplierInterface(), ElementSubdomainIDGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), PatternedMeshGenerator::generate(), MeshGenerator::generateInternal(), MultiAppTransfer::getAppInfo(), TransfiniteMeshGenerator::getEdge(), ElementGenerator::getElemType(), FEProblemBase::getMaterial(), FEProblemBase::getMaterialData(), MaterialOutputAction::getParams(), ReporterData::getReporterInfo(), Transient::getTimeIntegratorName(), FEProblemBase::getTransfers(), SubProblem::getVectorTags(), DisplacedProblem::getVectorTags(), CommonOutputAction::hasConsole(), FEProblemBase::hasMultiApps(), AdvancedOutput::hasOutput(), FEProblemBase::incrementMultiAppTStep(), AdvancedOutput::initAvailableLists(), FunctorPositions::initialize(), FunctorTimes::initialize(), MultiAppConservativeTransfer::initialSetup(), ArrayDGDiffusion::initQpResidual(), AdvancedOutput::initShowHideLists(), RelationshipManager::isType(), FEProblemBase::logAdd(), MaterialFunctorConverterTempl< T >::MaterialFunctorConverterTempl(), SubProblem::numVectorTags(), DisplacedProblem::numVectorTags(), MooseBaseParameterInterface::objectErrorPrefix(), AdvancedOutput::output(), Console::output(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), ProjectedStatefulMaterialStorageAction::processProperty(), SolutionInvalidInterface::registerInvalidSolutionInternal(), FEProblemBase::restoreMultiApps(), MeshRepairGenerator::separateSubdomainsByElementType(), FEProblemBase::setCoupling(), MooseBase::typeAndName(), AuxScalarKernel::uOld(), ScalarKernelBase::uOld(), DisplacedProblem::updateGeomSearch(), FEProblemBase::updateGeomSearch(), UserObjectInterface::userObjectType(), and AdvancedOutput::wantOutput().
typeAndName()
std::string MooseBase::typeAndName () const inline inherited
Get the class's combined type and name; useful in error handling.
Returns
The type and name of this class in the form '<type()> "<name()>"'.
Definition at line 53 of file MooseBase.h.
  {
    return type() + std::string(" \"") + name() + std::string("\"");
  }
Referenced by ReporterContext< T >::finalize(), and ReporterData::getReporterInfo().
uDot()
template<typename OutputType > const FieldVariableValue & MooseVariableFV< OutputType >::uDot () const inline
Definition at line 223 of file MooseVariableFV.h.
{ return _element_data->uDot(); }
uDotNeighbor()
template<typename OutputType > const FieldVariableValue & MooseVariableFV< OutputType >::uDotNeighbor () const inline
Definition at line 235 of file MooseVariableFV.h.
{ return _neighbor_data->uDot(); }
uncorrectedAdGradSln()
template<typename OutputType > VectorValue< ADReal > MooseVariableFV< OutputType >::uncorrectedAdGradSln (const FaceInfo & fi, const StateArg & state, const bool correct_skewness = false) const virtual
Retrieve (or potentially compute) the uncorrected gradient on the provided face.
This uncorrected gradient is a simple linear interpolation between cell gradients computed at the centers of the two neighboring cells. "Correcting" the face gradient involves weighting the gradient stencil more heavily on the solution values on the face-neighbor cells than the linear interpolation process does. This is commonly known as a cross-diffusion correction. Correction is done in adGradSln(const FaceInfo & fi)
Parameters
face The face for which to retrieve the gradient
state State argument which describes at what time / solution iteration state we want to evaluate the variable
correct_skewness Whether to perform skew corrections
Definition at line 640 of file MooseVariableFV.C.
{
  const bool var_defined_on_elem = this->hasBlocks(fi.elem().subdomain_id());
  const Elem * const elem_one = var_defined_on_elem ? &fi.elem() : fi.neighborPtr();
  const Elem * const elem_two = var_defined_on_elem ? fi.neighborPtr() : &fi.elem();
  const VectorValue<ADReal> elem_one_grad = adGradSln(elem_one, state, correct_skewness);
  // If we have a neighbor then we interpolate between the two to the face. If we do not, then we
  // apply a zero Hessian assumption and use the element centroid gradient as the uncorrected face
  // gradient
  if (elem_two && this->hasBlocks(elem_two->subdomain_id()))
  {
    const VectorValue<ADReal> & elem_two_grad = adGradSln(elem_two, state, correct_skewness);
    // Uncorrected gradient value
    return Moose::FV::linearInterpolation(elem_one_grad, elem_two_grad, fi, var_defined_on_elem);
  }
  else
    return elem_one_grad;
}
uniqueName()
MooseObjectName MooseBaseParameterInterface::uniqueName () const inline inherited
The unique name for accessing input parameters of this object in the InputParameterWarehouse.
Definition at line 58 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectName(_pars.get<std::string>("_unique_name"));
  }
Referenced by MooseBaseParameterInterface::connectControllableParams(), and Action::uniqueActionName().
uniqueParameterName()
MooseObjectParameterName MooseBaseParameterInterface::uniqueParameterName (const std::string & parameter_name) const inline inherited
The unique parameter name of a valid parameter of this object for accessing parameter controls.
Definition at line 43 of file MooseBaseParameterInterface.h.
  {
    return MooseObjectParameterName(
        _pars.get<std::string>("_moose_base"), _moose_base->name(), parameter_name);
  }
useDual()
bool MooseVariableBase::useDual () const inline inherited
Get dual mortar option.
Definition at line 74 of file MooseVariableBase.h.
{ return _use_dual; }
Referenced by MortarConstraintBase::MortarConstraintBase().
usesGradPhiNeighbor()
template<typename OutputType > bool MooseVariableField< OutputType >::usesGradPhiNeighbor () const inline inherited
Whether or not this variable is actually using the shape function gradient.
Currently hardcoded to true because we always compute the value.
Definition at line 319 of file MooseVariableField.h.
{ return true; }
Referenced by Assembly::copyNeighborShapes().
usesPhiNeighbor()
template<typename OutputType > bool MooseVariableField< OutputType >::usesPhiNeighbor () const inline inherited
Whether or not this variable is actually using the shape function value.
Currently hardcoded to true because we always compute the value.
Definition at line 312 of file MooseVariableField.h.
{ return true; }
Referenced by Assembly::copyNeighborShapes().
usesSecondPhiNeighbor()
template<typename OutputType > bool MooseVariableFV< OutputType >::usesSecondPhiNeighbor () const inline final override virtual
Whether or not this variable is actually using the shape function second derivatives.
Implements MooseVariableField< OutputType >.
Definition at line 571 of file MooseVariableFV.h.
{ return false; }
validParams()
template<typename OutputType > InputParameters MooseVariableFV< OutputType >::validParams static
Definition at line 34 of file MooseVariableFV.C.
{
  InputParameters params = MooseVariableField<OutputType>::validParams();
  params.set<bool>("fv") = true;
  params.set<MooseEnum>("family") = "MONOMIAL";
  params.set<MooseEnum>("order") = "CONSTANT";
  params.template addParam<bool>(
      "two_term_boundary_expansion",
      true,
      "Whether to use a two-term Taylor expansion to calculate boundary face values. "
      "If the two-term expansion is used, then the boundary face value depends on the "
      "adjoining cell center gradient, which itself depends on the boundary face value. "
      "Consequently an implicit solve is used to simultaneously solve for the adjoining cell "
      "center gradient and boundary face value(s).");
  MooseEnum face_interp_method("average skewness-corrected", "average");
  params.template addParam<MooseEnum>("face_interp_method",
                                      face_interp_method,
                                      "Switch that can select between face interpoaltion methods.");
  params.template addParam<bool>(
      "cache_cell_gradients", true, "Whether to cache cell gradients or re-compute them.");
  // Just evaluating finite volume variables at an arbitrary location in a cell requires a layer of
  // ghosting since we will use two term expansions
  params.addRelationshipManager("ElementSideNeighborLayers",
                                Moose::RelationshipManagerType::GEOMETRIC |
                                    Moose::RelationshipManagerType::ALGEBRAIC);
  return params;
}
vectorTagDofValue()
template<typename OutputType > const DoFValue & MooseVariableFV< OutputType >::vectorTagDofValue (TagID tag) const inline override virtual
Implements MooseVariableField< OutputType >.
Definition at line 206 of file MooseVariableFV.h.
  {
    return _element_data->vectorTagDofValue(tag);
  }
vectorTagValue()
template<typename OutputType > const FieldVariableValue & MooseVariableFV< OutputType >::vectorTagValue (TagID tag) const inline override virtual
tag values getters
Implements MooseVariableField< OutputType >.
Definition at line 202 of file MooseVariableFV.h.
  {
    return _element_data->vectorTagValue(tag);
  }
vectorTagValueNeighbor()
template<typename OutputType > const FieldVariableValue & MooseVariableFV< OutputType >::vectorTagValueNeighbor (TagID tag) inline
Definition at line 214 of file MooseVariableFV.h.
  {
    return _neighbor_data->vectorTagValue(tag);
  }
Friends And Related Function Documentation
Moose::initDofIndices
template<typename OutputType > void Moose::initDofIndices (MooseVariableFV< OutputType > & , const Elem &) friend
Member Data Documentation
_action_factory
ActionFactory& MooseBaseParameterInterface::_action_factory protected inherited
Builds Actions.
Definition at line 164 of file MooseBaseParameterInterface.h.
Referenced by CommonOutputAction::create(), AddVariableAction::createInitialConditionAction(), AddSpecies::createInitialConditions(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), CreateExecutionerAction::setupAutoPreconditioning(), and ReadExecutorParamsAction::setupAutoPreconditioning().
_ad_real_dummy
template<typename OutputType > ADReal MooseVariableField< OutputType >::_ad_real_dummy = 0 mutable protected inherited
A dummy ADReal variable.
Definition at line 382 of file MooseVariableField.h.
_app
MooseApp& MooseBase::_app protected inherited
The MOOSE application this is associated with.
Definition at line 60 of file MooseBase.h.
Referenced by AB2PredictorCorrector::AB2PredictorCorrector(), FEProblemBase::addAnyRedistributers(), DumpObjectsProblem::addAuxVariable(), MeshGenerator::addChildMeshGenerator(), FEProblemBase::addMaterialHelper(), MeshGenerator::addMeshSubgenerator(), FEProblemBase::addMultiApp(), FEProblemBase::addOutput(), MeshGenerator::addParentMeshGenerator(), FVFluxKernel::adjustRMGhostLayers(), FEProblemBase::allowOutput(), AStableDirk4::AStableDirk4(), FileMesh::buildMesh(), MooseMesh::buildTypedMesh(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), MeshGenerator::checkGetMesh(), FEProblemBase::checkICRestartError(), FEProblemBase::checkNonlinearConvergence(), OversampleOutput::cloneMesh(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), Console::Console(), TimeStepper::constrainStep(), MultiApp::createApp(), MultiApp::createApps(), MultiApp::createLocalApp(), FEProblemBase::customSetup(), MeshGenerator::declareMeshProperty(), MeshGenerator::declareNullMeshName(), MooseMesh::determineUseDistributedMesh(), DumpObjectsProblem::dumpObjectHelper(), DumpObjectsProblem::dumpVariableHelper(), EigenExecutionerBase::EigenExecutionerBase(), EigenKernel::EigenKernel(), PIDTransientControl::execute(), Eigenvalue::execute(), InversePowerMethod::execute(), NonlinearEigen::execute(), Steady::execute(), Transient::execute(), PseudoTimestep::execute(), IterationInfo::execute(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), FEProblemBase::FEProblemBase(), FileOutput::FileOutput(), ChangeOverFixedPointPostprocessor::finalize(), RadialAverage::finalize(), FixedPointSolve::FixedPointSolve(), FEProblemBase::forceOutput(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), ExtraNodesetGenerator::generate(), FileMeshGenerator::generate(), SideSetsFromNormalsGenerator::generate(), MeshGenerator::generateInternal(), FEProblemBase::getExecutor(), MeshGenerator::getMeshByName(), NumFixedPointIterations::getValue(), NumRelationshipManagers::getValue(), GhostingUserObject::GhostingUserObject(), MooseMesh::init(), InversePowerMethod::init(), NonlinearEigen::init(), Transient::init(), FEProblemBase::init(), TimePeriod::initialSetup(), Console::initialSetup(), AdvancedOutput::initOutputList(), FEProblemBase::initPetscOutput(), EigenProblem::initPetscOutput(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), MeshGenerator::MeshGenerator(), EigenExecutionerBase::normalizeSolution(), NumFailedTimeSteps::NumFailedTimeSteps(), AugmentSparsityOnInterface::operator()(), Checkpoint::output(), Exodus::output(), Nemesis::output(), PerfGraphOutput::output(), Tecplot::output(), MortarNodalGeometryOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Exodus::outputEmptyTimestep(), Console::outputInput(), Exodus::outputInput(), Exodus::outputNodalVariables(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), Console::outputSystemInformation(), JSONOutput::outputSystemInformation(), MultiApp::parentOutputPositionChanged(), PIDTransientControl::PIDTransientControl(), Transient::preExecute(), Eigenvalue::prepareSolverOptions(), FEProblemBase::projectSolution(), MultiApp::setAppOutputFileBase(), FileOutput::setFileBaseInternal(), MeshGenerator::setMeshProperty(), MeshGenerator::setMeshPropertyHelper(), FEProblemBase::setRestartFile(), TransientMultiApp::setupApp(), TimeSequenceStepperBase::setupSequence(), Transient::setupTimeIntegrator(), SideSetExtruderGenerator::SideSetExtruderGenerator(), SolutionInvalidityReporter::SolutionInvalidityReporter(), FEProblemBase::solve(), EigenProblem::solve(), PetscOutput::solveSetup(), TransientMultiApp::solveStep(), FEProblemBase::subdomainSetup(), FEProblemBase::theWarehouse(), TimeExtremeValue::TimeExtremeValue(), TimeIntervalTimes::TimeIntervalTimes(), TimePeriod::TimePeriod(), Transient::Transient(), FEProblemBase::updateMortarMesh(), Console::write(), and FEProblemBase::~FEProblemBase().
_assembly
Assembly& MooseVariableBase::_assembly protected inherited
Assembly data.
Definition at line 212 of file MooseVariableBase.h.
Referenced by MooseVariableFE< OutputType >::MooseVariableFE(), and MooseVariableFV< OutputType >::MooseVariableFV().
_blk_dim
unsigned int BlockRestrictable::_blk_dim private inherited
Largest mesh dimension of the elements in the blocks for this object.
Definition at line 259 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blocksMaxDimension(), and BlockRestrictable::initializeBlockRestrictable().
_blk_dual_restrictable
const bool BlockRestrictable::_blk_dual_restrictable private inherited
Flag for allowing dual restriction.
Definition at line 238 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_blk_feproblem
FEProblemBase* BlockRestrictable::_blk_feproblem private inherited
Pointer to FEProblemBase.
Definition at line 241 of file BlockRestrictable.h.
Referenced by BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlockMaterialPropertyHelper(), and BlockRestrictable::initializeBlockRestrictable().
_blk_ids
std::set<SubdomainID> BlockRestrictable::_blk_ids private inherited
Set of block ids supplied by the user via the input file (for error checking)
Definition at line 229 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blockIDs(), BlockRestrictable::blockRestricted(), BlockRestrictable::checkVariable(), BlockRestrictable::hasBlocks(), BlockRestrictable::initializeBlockRestrictable(), BlockRestrictable::isBlockSubset(), and BlockRestrictable::numBlocks().
_blk_material_data
const MaterialData* BlockRestrictable::_blk_material_data protected inherited
Pointer to the MaterialData class for this object.
Definition at line 207 of file BlockRestrictable.h.
Referenced by BlockRestrictable::hasBlockMaterialProperty(), and BlockRestrictable::initializeBlockRestrictable().
_blk_mesh
MooseMesh* BlockRestrictable::_blk_mesh private inherited
Pointer to Mesh.
Definition at line 244 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blockIDs(), BlockRestrictable::getBlockCoordSystem(), BlockRestrictable::hasBlocks(), BlockRestrictable::initializeBlockRestrictable(), BlockRestrictable::isBlockSubset(), and BlockRestrictable::meshBlockIDs().
_blk_name
const std::string& BlockRestrictable::_blk_name private inherited
Name of the object.
Definition at line 256 of file BlockRestrictable.h.
Referenced by BlockRestrictable::checkVariable(), and BlockRestrictable::initializeBlockRestrictable().
_blk_tid
THREAD_ID BlockRestrictable::_blk_tid private inherited
Thread id for this object.
Definition at line 253 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_blocks
std::vector<SubdomainName> BlockRestrictable::_blocks private inherited
Vector the block names supplied by the user via the input file.
Definition at line 235 of file BlockRestrictable.h.
Referenced by BlockRestrictable::blocks(), and BlockRestrictable::initializeBlockRestrictable().
_boundary_id_to_dirichlet_bc
template<typename OutputType > std::unordered_map<BoundaryID, const FVDirichletBCBase *> MooseVariableFV< OutputType >::_boundary_id_to_dirichlet_bc private
Map from boundary ID to Dirichlet boundary conditions.
Added to speed up Dirichlet BC lookups in getDirichletBC
Definition at line 685 of file MooseVariableFV.h.
_boundary_ids
const std::set<BoundaryID>& BlockRestrictable::_boundary_ids private inherited
Reference to the boundary_ids, defaults to an empty set if not provided.
Definition at line 250 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
_cache_cell_gradients
template<typename OutputType > const bool MooseVariableFV< OutputType >::_cache_cell_gradients protected
Whether to cache cell gradients.
Definition at line 699 of file MooseVariableFV.h.
_clearance_schedule
std::set<ExecFlagType> Moose::FunctorBase< Moose::ADType< OutputType >::type >::_clearance_schedule private inherited
How often to clear the material property cache.
Definition at line 411 of file MooseFunctor.h.
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_count
const unsigned int MooseVariableBase::_count protected inherited
Number of variables in the array.
Definition at line 227 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::componentName(), MooseVariableBase::count(), MooseVariableBase::MooseVariableBase(), and MooseVariableBase::scalingFactor().
_current_execute_flag
const ExecFlagType& SetupInterface::_current_execute_flag protected inherited
Reference to FEProblemBase.
Definition at line 78 of file SetupInterface.h.
Referenced by PseudoTimestep::execute().
_current_qp_map_key
dof_id_type Moose::FunctorBase< Moose::ADType< OutputType >::type >::_current_qp_map_key mutable private inherited
Current key for qp map cache.
Definition at line 417 of file MooseFunctor.h.
_current_qp_map_value
std::vector<std::pair<bool, ValueType> >* Moose::FunctorBase< Moose::ADType< OutputType >::type >::_current_qp_map_value mutable private inherited
Current value for qp map cache.
Definition at line 420 of file MooseFunctor.h.
_current_side_qp_map_key
dof_id_type Moose::FunctorBase< Moose::ADType< OutputType >::type >::_current_side_qp_map_key mutable private inherited
Current key for side-qp map cache.
Definition at line 433 of file MooseFunctor.h.
_current_side_qp_map_value
std::vector<std::vector<std::pair<bool, ValueType> > >* Moose::FunctorBase< Moose::ADType< OutputType >::type >::_current_side_qp_map_value mutable private inherited
Current value for side-qp map cache.
Definition at line 436 of file MooseFunctor.h.
_dirichlet_map_setup
template<typename OutputType > bool MooseVariableFV< OutputType >::_dirichlet_map_setup = false private
Whether the boundary to Dirichlet cache map has been setup yet.
Definition at line 552 of file MooseVariableFV.h.
Referenced by MooseVariableFV< OutputType >::meshChanged(), and MooseVariableFV< OutputType >::timestepSetup().
_dof_indices
std::vector<dof_id_type> MooseVariableBase::_dof_indices protected inherited
DOF indices.
Definition at line 218 of file MooseVariableBase.h.
Referenced by MooseVariableBase::clearAllDofIndices(), MooseVariableScalar::computeAD(), MooseVariableBase::dofIndices(), MooseVariableScalar::insert(), MooseVariableBase::numberOfDofs(), MooseVariableScalar::reinit(), MooseVariableScalar::setValue(), and MooseVariableScalar::setValues().
_dof_map
const DofMap& MooseVariableBase::_dof_map protected inherited
DOF map.
Definition at line 215 of file MooseVariableBase.h.
Referenced by MooseVariableBase::dofMap(), MooseVariableScalar::insert(), and MooseVariableScalar::reinit().
_elem_arg_to_value
std::map<ElemArg, ValueType> Moose::FunctorBase< Moose::ADType< OutputType >::type >::_elem_arg_to_value mutable private inherited
Map from element arguments to their cached evaluations.
Definition at line 449 of file MooseFunctor.h.
_elem_to_grad
template<typename OutputType > std::unordered_map<const Elem *, VectorValue<ADReal> > MooseVariableFV< OutputType >::_elem_to_grad mutable protected
A cache for storing gradients on elements.
Definition at line 689 of file MooseVariableFV.h.
_element_data
template<typename OutputType > std::unique_ptr<MooseVariableDataFV<OutputType> > MooseVariableFV< OutputType >::_element_data protected
Holder for all the data associated with the "main" element.
Definition at line 658 of file MooseVariableFV.h.
Referenced by MooseVariableFV< OutputType >::adDofValues(), MooseVariableFV< OutputType >::adGradSln(), MooseVariableFV< OutputType >::adGradSlnDot(), MooseVariableFV< OutputType >::adSecondSln(), MooseVariableFV< OutputType >::adSln(), MooseVariableFV< OutputType >::adUDot(), MooseVariableFV< OutputType >::adUDotDot(), MooseVariableFV< OutputType >::currentElem(), MooseVariableFV< OutputType >::dofIndices(), MooseVariableFV< OutputType >::duDotDotDu(), MooseVariableFV< OutputType >::duDotDu(), MooseVariableFV< OutputType >::getContinuity(), MooseVariableFV< OutputType >::getDofIndices(), MooseVariableFV< OutputType >::gradSln(), MooseVariableFV< OutputType >::gradSlnOld(), MooseVariableFV< OutputType >::hasDirichletBC(), MooseVariableFV< OutputType >::matrixTagValue(), MooseVariableFV< OutputType >::MooseVariableFV(), MooseVariableFV< OutputType >::numberOfDofs(), MooseVariableFV< OutputType >::setActiveTags(), MooseVariableFV< OutputType >::sln(), MooseVariableFV< OutputType >::slnOld(), MooseVariableFV< OutputType >::slnOlder(), MooseVariableFV< OutputType >::uDot(), MooseVariableFV< OutputType >::vectorTagDofValue(), and MooseVariableFV< OutputType >::vectorTagValue().
_empty_boundary_ids
const std::set<BoundaryID> BlockRestrictable::_empty_boundary_ids private inherited
An empty set for referencing when boundary_ids is not included.
Definition at line 247 of file BlockRestrictable.h.
_empty_execute_enum
ExecFlagEnum SetupInterface::_empty_execute_enum private inherited
Empty ExecFlagEnum for the case when the "execute_on" parameter is not included.
This is private because others should not be messing with it.
Definition at line 71 of file SetupInterface.h.
Referenced by SetupInterface::SetupInterface().
_enabled
const bool& MooseObject::_enabled protected inherited
Reference to the "enable" InputParameters, used by Controls for toggling on/off MooseObjects.
Definition at line 58 of file MooseObject.h.
Referenced by MooseObject::enabled().
_execute_enum
const ExecFlagEnum& SetupInterface::_execute_enum protected inherited
Execute settings for this object.
Definition at line 75 of file SetupInterface.h.
Referenced by ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), SetupInterface::getExecuteOnEnum(), JSONOutput::outputReporters(), XMLOutput::outputVectorPostprocessors(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseByBlockFunctorMaterialTempl< T >::PiecewiseByBlockFunctorMaterialTempl(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl().
_face_arg_to_value
std::map<FaceArg, ValueType> Moose::FunctorBase< Moose::ADType< OutputType >::type >::_face_arg_to_value mutable private inherited
Map from face arguments to their cached evaluations.
Definition at line 452 of file MooseFunctor.h.
_face_interp_method
template<typename OutputType > Moose::FV::InterpMethod MooseVariableFV< OutputType >::_face_interp_method protected
Decides if an average or skewed corrected average is used for the face interpolation.
Other options are not taken into account here, but at higher, kernel-based levels.
Definition at line 704 of file MooseVariableFV.h.
Referenced by MooseVariableFV< OutputType >::evaluate(), MooseVariableFV< OutputType >::evaluateGradient(), and MooseVariableFV< OutputType >::faceInterpolationMethod().
_factory
Factory& MooseBaseParameterInterface::_factory protected inherited
The Factory associated with the MooseApp.
Definition at line 161 of file MooseBaseParameterInterface.h.
Referenced by AddGeneralReactions::act(), AddReactions::act(), AddScalarReactions::act(), AddZapdosReactions::act(), ChemicalReactions::act(), AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), ElementIDOutputAction::act(), AddSpecies::act(), AdaptivityAction::act(), AddControlAction::act(), AddNodalNormalsAction::act(), AddPeriodicBCAction::act(), AutoCheckpointAction::act(), ComposeTimeStepperAction::act(), CreateDisplacedProblemAction::act(), CreateExecutionerAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), DisplayGhostingAction::act(), MaterialDerivativeTestAction::act(), MaterialOutputAction::act(), PartitionerAction::act(), SetAdaptivityOptionsAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), SetupPreconditionerAction::act(), SetupPredictorAction::act(), SetupResidualDebugAction::act(), SetupTimeStepperAction::act(), AddDriftDiffusionAction::addADKernels(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), AddPeriodicRelativeNodalDifference::addAverageNodalPP(), AddDriftDiffusionAction::addChargeSourceKernels(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddDriftDiffusionAction::addCurrent(), AddDriftDiffusionAction::addDensityLog(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddGeneralReactions::addEEDFReactionKernel(), AddDriftDiffusionAction::addEfield(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsIC(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddDriftDiffusionAction::addPosition(), CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseObjectAction::addRelationshipManagers(), AddPeriodicRelativeNodalDifference::addRelativePeriodicDiffPP(), AddZapdosReactions::addSuperelasticRateCoefficient(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), MooseBaseParameterInterface::connectControllableParams(), DynamicObjectRegistrationAction::DynamicObjectRegistrationAction(), MaterialOutputAction::getParams(), and ProjectedStatefulMaterialStorageAction::processProperty().
_fe_type
FEType MooseVariableBase::_fe_type protected inherited
The FEType associated with this variable.
Definition at line 191 of file MooseVariableBase.h.
Referenced by MooseVariableBase::feType(), MooseVariableBase::MooseVariableBase(), MooseVariableConstMonomial::MooseVariableConstMonomial(), and MooseVariableBase::order().
_functor_name
MooseFunctorName Moose::FunctorBase< Moose::ADType< OutputType >::type >::_functor_name private inherited
name of the functor
Definition at line 458 of file MooseFunctor.h.
_grad_phi
template<typename OutputType > const FieldVariablePhiGradient& MooseVariableFV< OutputType >::_grad_phi private
Definition at line 671 of file MooseVariableFV.h.
Referenced by MooseVariableFV< OutputType >::gradPhi().
_grad_phi_face
template<typename OutputType > const FieldVariablePhiGradient& MooseVariableFV< OutputType >::_grad_phi_face private
Definition at line 673 of file MooseVariableFV.h.
Referenced by MooseVariableFV< OutputType >::gradPhiFace().
_grad_phi_face_neighbor
template<typename OutputType > const FieldVariablePhiGradient& MooseVariableFV< OutputType >::_grad_phi_face_neighbor private
Definition at line 675 of file MooseVariableFV.h.
Referenced by MooseVariableFV< OutputType >::gradPhiFaceNeighbor().
_grad_phi_neighbor
template<typename OutputType > const FieldVariablePhiGradient& MooseVariableFV< OutputType >::_grad_phi_neighbor private
Definition at line 677 of file MooseVariableFV.h.
Referenced by MooseVariableFV< OutputType >::gradPhiNeighbor().
_index
unsigned int MooseVariableBase::_index protected inherited
variable number within MOOSE
Definition at line 197 of file MooseVariableBase.h.
_is_array
const bool MooseVariableBase::_is_array protected inherited
Whether this is an array variable.
Definition at line 239 of file MooseVariableBase.h.
Referenced by MooseVariableBase::isArray(), and MooseVariableBase::MooseVariableBase().
_is_eigen
bool MooseVariableBase::_is_eigen protected inherited
Whether or not this variable operates on eigen kernels.
Definition at line 200 of file MooseVariableBase.h.
Referenced by MooseVariableBase::eigen().
_mci_feproblem
FEProblemBase& MeshChangedInterface::_mci_feproblem protected inherited
Reference to FEProblemBase instance.
Definition at line 38 of file MeshChangedInterface.h.
Referenced by MeshChangedInterface::MeshChangedInterface().
_mesh
MooseMesh& MooseVariableBase::_mesh protected inherited
mesh the variable is active in
Definition at line 221 of file MooseVariableBase.h.
_moose_base
const MooseBase* const MooseBaseParameterInterface::_moose_base private inherited
The MooseBase object that inherits this class.
Definition at line 168 of file MooseBaseParameterInterface.h.
Referenced by MooseBaseParameterInterface::connectControllableParams(), MooseBaseParameterInterface::objectErrorPrefix(), MooseBaseParameterInterface::paramError(), and MooseBaseParameterInterface::uniqueParameterName().
_name
const std::string& MooseBase::_name protected inherited
The name of this class, reference to value stored in InputParameters.
Definition at line 66 of file MooseBase.h.
Referenced by AddFieldSplitAction::act(), AddBCAction::act(), AddConstraintAction::act(), AddControlAction::act(), AddDamperAction::act(), AddDGKernelAction::act(), AddDiracKernelAction::act(), AddDistributionAction::act(), AddFunctionAction::act(), AddFunctorMaterialAction::act(), AddFVBCAction::act(), AddFVInitialConditionAction::act(), AddFVInterfaceKernelAction::act(), AddFVKernelAction::act(), AddIndicatorAction::act(), AddInitialConditionAction::act(), AddInterfaceKernelAction::act(), AddKernelAction::act(), AddMarkerAction::act(), AddMaterialAction::act(), AddMeshDivisionAction::act(), AddMeshGeneratorAction::act(), AddMultiAppAction::act(), AddNodalKernelAction::act(), AddOutputAction::act(), AddPeriodicBCAction::act(), AddPositionsAction::act(), AddPostprocessorAction::act(), AddReporterAction::act(), AddSamplerAction::act(), AddScalarKernelAction::act(), AddTimesAction::act(), AddTimeStepperAction::act(), AddTransferAction::act(), AddUserObjectAction::act(), AddVectorPostprocessorAction::act(), PartitionerAction::act(), ReadExecutorParamsAction::act(), SetupPreconditionerAction::act(), SetupTimeIntegratorAction::act(), AddDriftDiffusionAction::addADKernels(), ADPiecewiseLinearInterpolationMaterial::ADPiecewiseLinearInterpolationMaterial(), PiecewiseTabularBase::buildFromFile(), PiecewiseTabularBase::buildFromXY(), PiecewiseLinearBase::buildInterpolation(), CombinerGenerator::CombinerGenerator(), Executor::Executor(), ExtraIDIntegralReporter::ExtraIDIntegralReporter(), MultiApp::fillPositions(), CentroidMultiApp::fillPositions(), QuadraturePointMultiApp::fillPositions(), FunctionDT::FunctionDT(), FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), MooseBase::name(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PiecewiseBilinear::PiecewiseBilinear(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), PiecewiseBase::setData(), and Split::setup().
_neighbor_data
template<typename OutputType > std::unique_ptr<MooseVariableDataFV<OutputType> > MooseVariableFV< OutputType >::_neighbor_data protected
Holder for all the data associated with the neighbor element.
Definition at line 661 of file MooseVariableFV.h.
Referenced by MooseVariableFV< OutputType >::adDofValuesNeighbor(), MooseVariableFV< OutputType >::adGradSlnNeighbor(), MooseVariableFV< OutputType >::adGradSlnNeighborDot(), MooseVariableFV< OutputType >::adSecondSlnNeighbor(), MooseVariableFV< OutputType >::adSlnNeighbor(), MooseVariableFV< OutputType >::adUDotDotNeighbor(), MooseVariableFV< OutputType >::adUDotNeighbor(), MooseVariableFV< OutputType >::dofIndicesNeighbor(), MooseVariableFV< OutputType >::duDotDotDuNeighbor(), MooseVariableFV< OutputType >::duDotDuNeighbor(), MooseVariableFV< OutputType >::gradSlnNeighbor(), MooseVariableFV< OutputType >::gradSlnOldNeighbor(), MooseVariableFV< OutputType >::hasDirichletBC(), MooseVariableFV< OutputType >::matrixTagValueNeighbor(), MooseVariableFV< OutputType >::MooseVariableFV(), MooseVariableFV< OutputType >::setActiveTags(), MooseVariableFV< OutputType >::slnNeighbor(), MooseVariableFV< OutputType >::slnOldNeighbor(), MooseVariableFV< OutputType >::uDotNeighbor(), and MooseVariableFV< OutputType >::vectorTagValueNeighbor().
_node_arg_to_value
std::map<NodeArg, ValueType> Moose::FunctorBase< Moose::ADType< OutputType >::type >::_node_arg_to_value mutable private inherited
Map from nodal arguments to their cached evaluations.
Definition at line 455 of file MooseFunctor.h.
_oi_moose_app
MooseApp& OutputInterface::_oi_moose_app private inherited
Reference the the MooseApp; neede for access to the OutputWarehouse.
Definition at line 66 of file OutputInterface.h.
_oi_output_warehouse
OutputWarehouse& OutputInterface::_oi_output_warehouse private inherited
Reference to the OutputWarehouse for populating the Output object hide lists.
Definition at line 69 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList().
_oi_outputs
std::set<OutputName> OutputInterface::_oi_outputs private inherited
The set of Output object names listed in the 'outputs' parameter.
Definition at line 72 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList(), and OutputInterface::getOutputs().
_parent
const MooseObject & DataFileInterface< MooseObject >::_parent private inherited
Definition at line 46 of file DataFileInterface.h.
_pars
const InputParameters& MooseBaseParameterInterface::_pars protected inherited
Parameters of this object, references the InputParameters stored in the InputParametersWarehouse.
Definition at line 158 of file MooseBaseParameterInterface.h.
Referenced by AddDriftDiffusionAction::act(), AddPeriodicRelativeNodalDifference::act(), AddSpecies::act(), AddAuxKernelAction::act(), AddFVICAction::act(), AddICAction::act(), AddPeriodicBCAction::act(), AddVariableAction::act(), CommonOutputAction::act(), ComposeTimeStepperAction::act(), CreateProblemAction::act(), CreateProblemDefaultAction::act(), SetupDebugAction::act(), SetupMeshAction::act(), FunctorMaterial::addFunctorPropertyByBlocks(), FVFluxKernel::adjustRMGhostLayers(), BreakMeshByBlockGeneratorBase::BreakMeshByBlockGeneratorBase(), PiecewiseTabularBase::buildFromFile(), PNGOutput::calculateRescalingValues(), BlockWeightedPartitioner::clone(), GridPartitioner::clone(), HierarchicalGridPartitioner::clone(), PetscExternalPartitioner::clone(), RandomPartitioner::clone(), SingleRankPartitioner::clone(), MooseBaseParameterInterface::connectControllableParams(), Console::Console(), AddVariableAction::createInitialConditionAction(), MaterialBase::declareADProperty(), MaterialBase::declareProperty(), FEProblemSolve::FEProblemSolve(), FVAdvection::FVAdvection(), FVAnisotropicDiffusion::FVAnisotropicDiffusion(), FVDiffusion::FVDiffusion(), FileMeshGenerator::generate(), MaterialBase::getGenericZeroMaterialProperty(), MeshGenerator::getMeshGeneratorNameFromParam(), MeshGenerator::getMeshGeneratorNamesFromParam(), MooseBaseParameterInterface::getParam(), MooseBaseParameterInterface::getRenamedParam(), AddVariableAction::init(), AdvancedOutput::initExecutionTypes(), Console::initialSetup(), MooseBaseParameterInterface::isParamSetByUser(), MooseBaseParameterInterface::isParamValid(), MultiApp::keepSolutionDuringRestore(), MooseBaseParameterInterface::paramErrorMsg(), GlobalParamsAction::parameters(), MooseBaseParameterInterface::parameters(), MooseMesh::prepare(), Eigenvalue::prepareSolverOptions(), MooseMesh::setCoordSystem(), MooseMesh::setPartitionerHelper(), SetupMeshAction::setupMesh(), Transient::setupTimeIntegrator(), MooseBaseParameterInterface::uniqueName(), and MooseBaseParameterInterface::uniqueParameterName().
_phi
template<typename OutputType > const FieldVariablePhiValue& MooseVariableFV< OutputType >::_phi private
Shape functions.
Definition at line 670 of file MooseVariableFV.h.
Referenced by MooseVariableFV< OutputType >::phi(), and MooseVariableFV< OutputType >::phiSize().
_phi_face
template<typename OutputType > const FieldVariablePhiValue& MooseVariableFV< OutputType >::_phi_face private
Definition at line 672 of file MooseVariableFV.h.
Referenced by MooseVariableFV< OutputType >::phiFace(), and MooseVariableFV< OutputType >::phiFaceSize().
_phi_face_neighbor
template<typename OutputType > const FieldVariablePhiValue& MooseVariableFV< OutputType >::_phi_face_neighbor private
Definition at line 674 of file MooseVariableFV.h.
Referenced by MooseVariableFV< OutputType >::phiFaceNeighbor(), and MooseVariableFV< OutputType >::phiFaceNeighborSize().
_phi_neighbor
template<typename OutputType > const FieldVariablePhiValue& MooseVariableFV< OutputType >::_phi_neighbor private
Definition at line 676 of file MooseVariableFV.h.
Referenced by MooseVariableFV< OutputType >::phiNeighbor(), and MooseVariableFV< OutputType >::phiNeighborSize().
_prev_elem
template<typename OutputType > const Elem* MooseVariableFV< OutputType >::_prev_elem mutable private
A member used to help determine when we can return cached data as opposed to computing new data.
Definition at line 681 of file MooseVariableFV.h.
Referenced by MooseVariableFV< OutputType >::meshChanged().
_qp_to_value
std::unordered_map<dof_id_type, std::vector<std::pair<bool, ValueType> > > Moose::FunctorBase< Moose::ADType< OutputType >::type >::_qp_to_value mutable private inherited
Cached element quadrature point functor property evaluations.
The map key is the element id. The map values should have size corresponding to the number of quadrature points on the element. The vector elements are pairs. The first member of the pair indicates whether a cached value has been computed. The second member of the pair is the (cached) value. If the boolean is false, then the value cannot be trusted
Definition at line 427 of file MooseFunctor.h.
_scaling_factor
std::vector<Real> MooseVariableBase::_scaling_factor protected inherited
scaling factor for this variable
Definition at line 230 of file MooseVariableBase.h.
Referenced by MooseVariableBase::arrayScalingFactor(), MooseVariableBase::initialSetup(), and MooseVariableBase::scalingFactor().
_side_qp_to_value
std::unordered_map<dof_id_type, std::vector<std::vector<std::pair<bool, ValueType> > > > Moose::FunctorBase< Moose::ADType< OutputType >::type >::_side_qp_to_value mutable private inherited
Cached element quadrature point functor property evaluations.
The map key is the element id. The map values are a multi-dimensional vector (or vector of vectors) with the first index corresponding to the side and the second index corresponding to the quadrature point index. The elements returned after double indexing are pairs. The first member of the pair indicates whether a cached value has been computed. The second member of the pair is the (cached) value. If the boolean is false, then the value cannot be trusted
Definition at line 446 of file MooseFunctor.h.
_solution
template<typename OutputType > const NumericVector<Number>* const& MooseVariableFV< OutputType >::_solution private
The current (ghosted) solution.
Note that this needs to be stored as a reference to a pointer because the solution might not exist at the time that this variable is constructed, so we cannot safely dereference at that time
Definition at line 667 of file MooseVariableFV.h.
_subproblem
SubProblem& MooseVariableBase::_subproblem protected inherited
Problem this variable is part of.
Definition at line 206 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::componentName(), MooseVariableScalar::computeAD(), and MooseVariableBase::initialSetup().
_sys
SystemBase& MooseVariableBase::_sys protected inherited
System this variable is part of.
Definition at line 188 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::activeOnSubdomain(), MooseVariableFieldBase::activeSubdomains(), MooseVariableScalar::adUDot(), MooseVariableBase::allDofIndices(), MooseVariableScalar::computeAD(), MooseVariableBase::initialSetup(), MooseVariableBase::MooseVariableBase(), MooseVariableFE< OutputType >::MooseVariableFE(), MooseVariableFV< OutputType >::MooseVariableFV(), MooseVariableScalar::MooseVariableScalar(), MooseVariableScalar::reinit(), MooseVariableBase::sys(), MooseVariableScalar::uDot(), MooseVariableScalar::uDotDot(), MooseVariableScalar::uDotDotOld(), and MooseVariableScalar::uDotOld().
_temp_cell_gradient
template<typename OutputType > VectorValue<ADReal> MooseVariableFV< OutputType >::_temp_cell_gradient mutable protected
A member to hold the cell gradient when not caching, used to return a reference (due to expensive ADReal copy)
Definition at line 696 of file MooseVariableFV.h.
_tid
THREAD_ID MooseVariableBase::_tid protected inherited
Thread ID.
Definition at line 224 of file MooseVariableBase.h.
Referenced by MooseVariableFE< OutputType >::MooseVariableFE(), MooseVariableFV< OutputType >::MooseVariableFV(), and MooseVariableScalar::reinit().
_time_integrator
template<typename OutputType > const TimeIntegrator* const MooseVariableField< OutputType >::_time_integrator protected inherited
the time integrator used for computing time derivatives
Definition at line 379 of file MooseVariableField.h.
_two_term_boundary_expansion
template<typename OutputType > bool MooseVariableFV< OutputType >::_two_term_boundary_expansion protected
Whether to use a two term expansion for computing boundary face values.
Definition at line 692 of file MooseVariableFV.h.
_type
const std::string& MooseBase::_type protected inherited
The type of this class.
Definition at line 63 of file MooseBase.h.
Referenced by FillBetweenCurvesGenerator::generate(), FillBetweenPointVectorsGenerator::generate(), FillBetweenSidesetsGenerator::generate(), FEProblemBase::init(), FEProblemBase::solverTypeString(), and MooseBase::type().
_use_dual
bool MooseVariableBase::_use_dual protected inherited
If dual mortar approach is used.
Definition at line 236 of file MooseVariableBase.h.
Referenced by MooseVariableBase::useDual().
_var_kind
Moose::VarKindType MooseVariableBase::_var_kind protected inherited
Variable type (see MooseTypes.h)
Definition at line 203 of file MooseVariableBase.h.
Referenced by MooseVariableBase::kind().
_var_name
std::string MooseVariableBase::_var_name protected inherited
Variable name.
Definition at line 233 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::componentName(), MooseVariableBase::MooseVariableBase(), and MooseVariableBase::name().
_var_num
unsigned int MooseVariableBase::_var_num protected inherited
variable number (from libMesh)
Definition at line 194 of file MooseVariableBase.h.
Referenced by MooseVariableFieldBase::activeOnSubdomain(), MooseVariableFieldBase::activeSubdomains(), MooseVariableBase::MooseVariableBase(), MooseVariableBase::number(), and MooseVariableScalar::reinit().
_variable
const Variable& MooseVariableBase::_variable protected inherited
libMesh variable object for this variable
Definition at line 209 of file MooseVariableBase.h.
_vec_ids
std::vector<SubdomainID> BlockRestrictable::_vec_ids private inherited
Vector of block ids supplied by the user via the input file (for error reporting)
Definition at line 232 of file BlockRestrictable.h.
Referenced by BlockRestrictable::initializeBlockRestrictable().
usingMooseVariableFieldMembers
template<typename OutputType > MooseVariableFV< OutputType >::usingMooseVariableFieldMembers protected
Definition at line 655 of file MooseVariableFV.h.
The documentation for this class was generated from the following files:
moose/framework/include/fviks/FVInterfaceKernel.h
moose/framework/include/variables/MooseVariableFV.h
moose/framework/src/variables/MooseVariableFV.C