Zapdos: InputStream Class Reference
InputStream Class Reference abstract
Helper class that hands out input streams to an underlying, managed stream of arbitrary type.
#include <InputStream.h>
Public Member Functions
virtual ~InputStream ()
virtual std::shared_ptr< std::istream > get () const =0
Gets an input stream to the underlying stream.
bool inUse () const
Whether or not anything is still using this stream.
virtual std::optional< std::filesystem::path > getFilename () const
Gets the underlying filename, if any.
Protected Member Functions
void addSharedStream (const std::weak_ptr< std::istream > stream) const
Internal method to be called by derived classes to add a shared stream to _shared_streams (so that it can be tracked).
Private Attributes
std::vector< std::weak_ptr< std::istream > > _shared_streams
The streams that have been handed out by get()
Detailed Description
Helper class that hands out input streams to an underlying, managed stream of arbitrary type.
Definition at line 22 of file InputStream.h.
Constructor & Destructor Documentation
~InputStream()
InputStream::~InputStream () virtual
Definition at line 14 of file InputStream.C.
{
  if (inUse())
    mooseError("Stream still in use");
}
Member Function Documentation
addSharedStream()
void InputStream::addSharedStream (const std::weak_ptr< std::istream > stream) const protected
Internal method to be called by derived classes to add a shared stream to _shared_streams (so that it can be tracked).
Should be called in the overridden get() by derived classes.
Definition at line 21 of file InputStream.C.
{
  mooseAssert(!stream.expired(), "Stream is expired");
  for (auto & entry : _shared_streams)
    if (entry.expired())
    {
      entry = stream;
      return;
    }
  _shared_streams.push_back(stream);
}
Referenced by FileInputStream::get(), and StringInputStream::get().
get()
virtual std::shared_ptr< std::istream > InputStream::get () const pure virtual
Gets an input stream to the underlying stream.
This is returned as a shared_ptr so that this class can tell whether or not another object is still using the stream.
Implemented in FileInputStream, and StringInputStream.
Referenced by RestartableDataReader::deserializeValue(), and RestartableDataReader::readHeader().
getFilename()
std::optional< std::filesystem::path > InputStream::getFilename () const virtual
Gets the underlying filename, if any.
Reimplemented in FileInputStream.
Definition at line 44 of file InputStream.C.
{
  return {};
}
Referenced by RestartableDataReader::deserializeValue(), and RestartableDataReader::readHeader().
inUse()
bool InputStream::inUse () const
Whether or not anything is still using this stream.
This is checked by seeing whether or not the use count of any of the streams handed out by get() is > 1 (with the only use count being the one stored in _shared_streams)
Definition at line 35 of file InputStream.C.
{
  for (auto & stream : _shared_streams)
    if (!stream.expired())
      return true;
  return false;
}
Referenced by StringInputStream::release(), and ~InputStream().
Member Data Documentation
_shared_streams
std::vector<std::weak_ptr<std::istream> > InputStream::_shared_streams mutable private
The streams that have been handed out by get()
Definition at line 60 of file InputStream.h.
Referenced by addSharedStream(), and inUse().
The documentation for this class was generated from the following files:
moose/framework/include/restart/InputStream.h
moose/framework/src/restart/InputStream.C