Zapdos: MeshGeneratorSystem Class Reference
MeshGeneratorSystem Class Reference
System that manages MeshGenerators.
#include <MeshGeneratorSystem.h>
Public Member Functions
MeshGeneratorSystem (MooseApp &app)
void executeMeshGenerators ()
Execute and clear the Mesh Generators data structure.
void addMeshGenerator (const std::string &type, const std::string &name, const InputParameters &params)
Add a mesh generator that will act on the meshes in the system.
const MeshGenerator & appendMeshGenerator (const std::string &type, const std::string &name, InputParameters params)
Append a mesh generator that will act on the current final mesh generator in the system.
std::unique_ptr< MeshBase > & getMeshGeneratorOutput (const MeshGeneratorName &name)
Get a reference to a pointer that will be the output of the MeshGenerator named name.
void createAddedMeshGenerators ()
Creates (constructs) all of the MeshGenerators that have been declared using addMeshGenerator().
std::vector< std::string > getMeshGeneratorNames () const
Get names of all mesh generators Note: This function should be called after all mesh generators are added with the 'add_mesh_generator' task.
std::unique_ptr< MeshBase > getSavedMesh (const std::string &name)
Get the saved mesh by name.
std::vector< std::string > getSavedMeshNames () const
Get all user-defined saved meshes except main and main_displaced.
bool hasMeshGenerator (const MeshGeneratorName &name) const
const MeshGenerator & getMeshGenerator (const std::string &name) const
bool hasMeshGeneratorParams (const MeshGeneratorName &name) const
Whether or not we know about the parameters for a MeshGenerator with the given name.
bool appendingMeshGenerators () const
Whether or not mesh generators are currently being appended (append_mesh_generator task)
bool hasBreakMeshByBlockGenerator () const
PerfGraph & perfGraph ()
Get the PerfGraph.
Static Public Member Functions
static std::string mainMeshGeneratorName ()
The name reserved for the "main" mesh generator which is the one used for the numerical solver downstream.
static InputParameters validParams ()
Protected Member Functions
PerfID registerTimedSection (const std::string &section_name, const unsigned int level) const
Call to register a named section for timing.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level, const std::string &live_message, const bool print_dots=true) const
Call to register a named section for timing.
std::string timedSectionName (const std::string &section_name) const
Protected Attributes
MooseApp & _pg_moose_app
The MooseApp that owns the PerfGraph.
const std::string _prefix
A prefix to use for all sections.
Private Member Functions
std::vector< std::pair< std::string, MeshGeneratorName > > getMeshGeneratorParamDependencies (const InputParameters &params, const bool allow_empty=false) const
Gets the MeshGeneratorNames that are referenced in an object's parameters.
void createMeshGeneratorOrder ()
Order all of the _mesh_generators into _ordered_mesh_generators for later execution in executeMeshGenerators.
std::shared_ptr< MeshGenerator > createMeshGenerator (const std::string &name)
Internal method for actually constructing a mesh generator after it has been declared externally in addMeshGenerator (in Actions).
MeshGenerator & getMeshGeneratorInternal (const std::string &name)
Get a MeshGenerator with the name name.
Private Attributes
MooseApp & _app
The MooseApp that owns this system.
std::unordered_map< std::string, std::pair< std::string, InputParameters > > _mesh_generator_params
The MeshGenerators declared using addMeshGenerator(), cleared after createMeshGenerators() Key is the name, pair contains the type and the params.
std::map< std::string, std::shared_ptr< MeshGenerator > > _mesh_generators
Owning storage for mesh generators, map of name -> MeshGenerator.
std::vector< std::vector< MeshGenerator * > > _ordered_mesh_generators
Holds the ordered mesh generators from createMeshGeneratorOrder() until they are executed in executeMeshGenerators()
std::map< std::string, std::list< std::unique_ptr< MeshBase > > > _mesh_generator_outputs
Holds the output for each mesh generator - including duplicates needed downstream.
std::string _final_generator_name
The final mesh generator name to use.
std::map< std::string, std::unique_ptr< MeshBase > > _save_in_meshes
Holds the map of save in mesh -> name.
bool _has_bmbb
Whether any of the mesh generators are a BreakMeshByBlockGenerator.
Detailed Description
System that manages MeshGenerators.
To be owned by the MooseApp.
Definition at line 27 of file MeshGeneratorSystem.h.
Constructor & Destructor Documentation
MeshGeneratorSystem()
MeshGeneratorSystem::MeshGeneratorSystem (MooseApp & app)
Definition at line 18 of file MeshGeneratorSystem.C.
  : PerfGraphInterface(app.perfGraph(), "MeshGeneratorSystem"),
    ParallelObject(app),
    _app(app),
    _has_bmbb(false)
{
}
Member Function Documentation
addMeshGenerator()
void MeshGeneratorSystem::addMeshGenerator (const std::string & type, const std::string & name, const InputParameters & params)
Add a mesh generator that will act on the meshes in the system.
Parameters
type The type of MeshGenerator
name The name of the MeshGenerator
params The params used to construct the MeshGenerator
Internally, this will store the parameters for future construction during the "add_mesh_generator" task. When called during the "create_mesh_generator" task (i.e., when creating mesh subgenerators), it will also construct the generator.
We don't construct them yet because we want to create them in order during createMeshGenerators() as much as possible so that we don't need lazy construction for things like mesh properties.
Definition at line 27 of file MeshGeneratorSystem.C.
{
  mooseAssert(!_mesh_generator_params.count(name), "Already exists");
  _mesh_generator_params.emplace(
      std::piecewise_construct, std::forward_as_tuple(name), std::forward_as_tuple(type, params));
  // This should be a sub mesh generator. We can assume this because if we're in the middle of
  // constructing mesh generators (not "adding" them, where we simply store their parameters)
  if (_app.constructingMeshGenerators())
    createMeshGenerator(name);
  if (type == "BreakMeshByBlockGenerator")
    _has_bmbb = true;
}
Referenced by MooseApp::addMeshGenerator().
appendingMeshGenerators()
bool MeshGeneratorSystem::appendingMeshGenerators () const
Whether or not mesh generators are currently being appended (append_mesh_generator task)
Definition at line 575 of file MeshGeneratorSystem.C.
{
  return _app.actionWarehouse().getCurrentTaskName() == "append_mesh_generator";
}
Referenced by appendMeshGenerator(), and MooseApp::constructingMeshGenerators().
appendMeshGenerator()
const MeshGenerator & MeshGeneratorSystem::appendMeshGenerator (const std::string & type, const std::string & name, InputParameters params)
Append a mesh generator that will act on the current final mesh generator in the system.
Parameters
type The type of MeshGenerator
name The name of the MeshGenerator
params The params used to construct the MeshGenerator
This MeshGenerator must have a parameter "input" of type MeshGeneratorName for this to work, as said parameter is set to the current final generator
Note: This function must be called during the append_mesh_generator task.
Definition at line 45 of file MeshGeneratorSystem.C.
{
  if (!appendingMeshGenerators())
    mooseError("Can only call appendMeshGenerator() during the append_mesh_generator task");
  // Make sure this mesh generator has one and _only_ one input, as "input"
  const auto param_name_mg_name_pairs = getMeshGeneratorParamDependencies(params, true);
  if (param_name_mg_name_pairs.size() != 1 || param_name_mg_name_pairs[0].first != "input")
    mooseError("While adding ",
               type,
               " '",
               name,
               "' via appendMeshGenerator():\nCan only append a mesh generator that takes a "
               "single input mesh generator via the parameter named 'input'");
  // If no final generator is set, we need to make sure that we have one; we will hit
  // this the first time we add an appended MeshGenerator and only need to do it once.
  // We'll then generate the final ordering within the execution phase. We'll also
  // clear the ordering because it could be invalid if we append any more generators,
  // and we'll be re-ordering within executeMeshgenerators() anyway (where we don't
  // keep track of any state for the sake of simpler logic)
  if (_final_generator_name.empty())
  {
    if (_mesh_generators.empty())
      mooseError("Cannot use appendMeshGenerator() because there is not a generator to append to!");
    createMeshGeneratorOrder();
    _ordered_mesh_generators.clear();
  }
  // Set the final generator as the input
  mooseAssert(hasMeshGenerator(_final_generator_name), "Missing final generator");
  params.set<MeshGeneratorName>("input") = _final_generator_name;
  // Keep track of the new final generator
  _final_generator_name = name;
  // Need to add this to the param map so that createMeshGenerator can use it
  mooseAssert(!_mesh_generator_params.count(name), "Already exists");
  _mesh_generator_params.emplace(
      std::piecewise_construct, std::forward_as_tuple(name), std::forward_as_tuple(type, params));
  return *createMeshGenerator(name);
}
Referenced by MooseApp::appendMeshGenerator().
createAddedMeshGenerators()
void MeshGeneratorSystem::createAddedMeshGenerators ()
Creates (constructs) all of the MeshGenerators that have been declared using addMeshGenerator().
This parses the input parameters of type <MeshGenerator> and std::vector<MeshGeneratorName> to build the execution tree for the generators, and constructs them in dependency order
Sub generators are also generated within this phase, although the dependency resolution described above is only for the dependencies that we can parse using InputParameters. However, we require that sub generators be constructed within their dependency order (except for the last one, which may be coupled to via the generator creating said sub generator).
Should only be called by the CreateAddedMeshGenerator action during the create_added_mesh_generators task.
Definition at line 123 of file MeshGeneratorSystem.C.
{
  mooseAssert(_app.actionWarehouse().getCurrentTaskName() == "create_added_mesh_generators",
              "Should not run now");
  // No generators were added via addMeshGenerator()
  if (_mesh_generator_params.empty())
    return;
  DependencyResolver<std::string> resolver;
  // Define the dependencies known so far
  for (const auto & [name, type_params_pair] : _mesh_generator_params)
  {
    resolver.addItem(name);
    for (const auto & param_dependency_pair :
         getMeshGeneratorParamDependencies(type_params_pair.second))
      resolver.addEdge(param_dependency_pair.second, name);
  }
  std::vector<std::vector<std::string>> ordered_generators;
  try
  {
    ordered_generators = resolver.getSortedValuesSets();
  }
  catch (CyclicDependencyException<std::string> & e)
  {
    mooseError("Cyclic dependencies detected in mesh generation: ",
               MooseUtils::join(e.getCyclicDependencies(), " <- "));
  }
  // Construct all of the mesh generators that we know exist
  for (const auto & generator_names : ordered_generators)
    for (const auto & generator_name : generator_names)
      if (_mesh_generator_params.count(generator_name))
        createMeshGenerator(generator_name);
  mooseAssert(_mesh_generator_params.empty(), "Should be empty");
  mooseAssert(_final_generator_name.empty(), "Should be unset at this point");
  // Set the final generator if we have one set by the user
  // and if so make sure it also exists
  const auto & moose_mesh = _app.actionWarehouse().getMesh();
  if (moose_mesh->parameters().have_parameter<std::string>("final_generator") &&
      moose_mesh->isParamValid("final_generator"))
  {
    mooseAssert(moose_mesh->type() == "MeshGeneratorMesh",
                "Assumption for mesh type is now invalid");
    _final_generator_name = moose_mesh->getParam<std::string>("final_generator");
    if (!hasMeshGenerator(_final_generator_name))
      moose_mesh->paramError("final_generator",
                             "The forced final MeshGenerator '",
                             _final_generator_name,
                             "' does not exist");
  }
}
Referenced by CreateAddedMeshGenerators::act().
createMeshGenerator()
std::shared_ptr< MeshGenerator > MeshGeneratorSystem::createMeshGenerator (const std::string & name) private
Internal method for actually constructing a mesh generator after it has been declared externally in addMeshGenerator (in Actions).
Definition at line 397 of file MeshGeneratorSystem.C.
{
  libmesh_parallel_only(comm());
  mooseAssert(_app.constructingMeshGenerators(), "Should not run now");
  const auto find_params = _mesh_generator_params.find(generator_name);
  mooseAssert(find_params != _mesh_generator_params.end(), "Not added");
  const auto & [type, params] = find_params->second;
  mooseAssert(comm().verify(type + generator_name), "Inconsistent construction order");
  std::shared_ptr<MeshGenerator> mg =
      _app.getFactory().create<MeshGenerator>(type, generator_name, params);
  if (mg->hasSaveMesh())
  {
    if (_save_in_meshes.count(mg->getSavedMeshName()))
      mg->paramError("save_with_name",
                     "The save with name '",
                     mg->getSavedMeshName(),
                     "' has already been used");
    _save_in_meshes.emplace(mg->getSavedMeshName(), nullptr);
  }
  // Setup the children and parents
  for (const auto & dependency : mg->getRequestedMeshGenerators())
  {
    // We _shouldn't_ hit this; now that we enforce construction ordering we do
    // all of this error checking at construction time because the info is available
    mooseAssert(hasMeshGenerator(dependency), "Missing dependency");
    auto & dependency_mg = getMeshGeneratorInternal(dependency);
    mg->addParentMeshGenerator(dependency_mg, MeshGenerator::AddParentChildKey());
    dependency_mg.addChildMeshGenerator(*mg, MeshGenerator::AddParentChildKey());
  }
  // Loop through all of the MeshGeneratorName and std::vector<MeshGeneratorName>
  // parameters (meshes that we should depend on), and make sure that either:
  // - We directly depend on them and requested a mesh from them
  // - We created a sub generator that depends on them and we declared it
  for (const auto & param_dependency_pair : getMeshGeneratorParamDependencies(mg->parameters()))
  {
    const auto & param_name = param_dependency_pair.first;
    const auto & dependency_name = param_dependency_pair.second;
    if (mg->isNullMeshName(dependency_name))
      continue;
    // True if this dependency was requested and is a parent
    if (mg->isParentMeshGenerator(dependency_name))
    {
      mooseAssert(mg->getRequestedMeshGenerators().count(dependency_name), "Wasn't requested");
      continue;
    }
    // Whether or not this is a dependency of at least one SubGenerator
    auto find_sub_dependency = std::find_if(mg->getSubMeshGenerators().begin(),
                                            mg->getSubMeshGenerators().end(),
                                            [&dependency_name](const auto & mg)
                                            { return mg->isParentMeshGenerator(dependency_name); });
    const auto is_sub_dependency = find_sub_dependency != mg->getSubMeshGenerators().end();
    // This should be used by a sub generator
    if (mg->getRequestedMeshGeneratorsForSub().count(dependency_name))
    {
      if (!is_sub_dependency)
        mg->mooseError("The sub generator dependency declared from MeshGenerator '",
                       dependency_name,
                       "' from the parameter '",
                       param_name,
                       "' was not used.\n\nDependencies that are declared by declareMeshForSub() "
                       "must be used as an input to a sub generator created by this object.");
    }
    // This was used by a sub generator but wasn't declared
    else if (is_sub_dependency)
      mg->mooseError(
          "The MeshGenerator '",
          dependency_name,
          "' was referenced in the parameter '",
          param_name,
          "' and used in the sub generator ",
          (*find_sub_dependency)->type(),
          " '",
          (*find_sub_dependency)->name(),
          "', but was not declared as a sub dependency.\n\nTo correct this, modify the code of ",
          mg->type(),
          " to include a call to declareMesh(es)ForSub(\"",
          param_name,
          "\") in the constructor.");
    // Isn't used at all
    else
      mg->mooseError(
          "You failed to request the generated mesh(es) for the parameter '",
          param_name,
          "'.\n\nIn specific, the mesh from MeshGenerator '",
          dependency_name,
          "' was not requested.\n\nTo correct this, you should remove the parameter if the "
          "mesh(es)\nare not needed, or request the mesh(es) with getMesh()/getMeshes().");
  }
  mooseAssert(!_mesh_generators.count(generator_name), "Already created");
  _mesh_generators.emplace(generator_name, mg);
  mooseAssert(!_mesh_generator_outputs.count(generator_name), "Already exists");
  _mesh_generator_outputs[generator_name];
  _mesh_generator_params.erase(find_params);
  return mg;
}
Referenced by addMeshGenerator(), appendMeshGenerator(), and createAddedMeshGenerators().
createMeshGeneratorOrder()
void MeshGeneratorSystem::createMeshGeneratorOrder () private
Order all of the _mesh_generators into _ordered_mesh_generators for later execution in executeMeshGenerators.
Definition at line 182 of file MeshGeneratorSystem.C.
{
  mooseAssert(_app.constructingMeshGenerators() ||
                  _app.actionWarehouse().getCurrentTaskName() == "execute_mesh_generators",
              "Incorrect call time");
  mooseAssert(_ordered_mesh_generators.empty(), "Already ordered");
  mooseAssert(_mesh_generators.size(), "No mesh generators to order");
  TIME_SECTION("createMeshGeneratorOrder", 1, "Ordering Mesh Generators");
  // We dare not sort these based on address!
  DependencyResolver<MeshGenerator *, MeshGenerator::Comparator> resolver;
  // The mesh generators that must be called
  // This is needed to mark the generators that could be cut due to a
  // final generator being set, but should still be called because they're
  // either being saved in memory or as output
  std::vector<std::string> required_generators;
  for (const auto & it : _mesh_generators)
    if (it.second->hasSaveMesh() || it.second->hasOutput())
      required_generators.push_back(it.second->name());
  // The mesh generator tree should have all the mesh generators that
  // The final generator depends on and all the mesh generators
  // with 'save in' flag. Here we loop over all the mesh generators
  // and conditionally add all of the dependencies into the resolver
  for (const auto & it : _mesh_generators)
  {
    MeshGenerator * mg = it.second.get();
    // The mesh generator has to meet one of the following conditions:
    // Final mesh generator is not set, so we build the whole tree
    if (_final_generator_name.empty() ||
        // This mesh generator is the final generator
        mg->name() == _final_generator_name ||
        // This needs to be saved or output
        mg->hasSaveMesh() || mg->hasOutput() ||
        // Final mesh generator set and is a child of this generator
        (_final_generator_name.size() && mg->isChildMeshGenerator(_final_generator_name, false)) ||
        // This is a dependency of a generator that needs to be saved or output
        std::find_if(required_generators.begin(),
                     required_generators.end(),
                     [&mg](const auto & name) { return mg->isChildMeshGenerator(name, false); }) !=
            required_generators.end())
    {
      resolver.addItem(mg);
      for (const auto & dep_mg : mg->getParentMeshGenerators())
        resolver.addEdge(&getMeshGeneratorInternal(dep_mg->name()), mg);
    }
  }
  // ...and sort them
  try
  {
    _ordered_mesh_generators = resolver.getSortedValuesSets();
  }
  // It is _quite_ hard to trigger this to test it. I've tried to no avail.
  // Now that we...
  // - check and sort up front
  // - know if dependencies exist at the time of requesting them
  // - require that sub generators depend only on other sub generators in an object's
  //   tree + input dependencies that we explicitly declare
  // I don't think it's possible. But we'll leave it here anyway and it
  // definitely will not be covered
  catch (CyclicDependencyException<MeshGenerator *, MeshGenerator::Comparator> & e)
  {
    const auto & cycle = e.getCyclicDependencies();
    std::vector<std::string> names(cycle.size());
    for (const auto i : index_range(cycle))
      names[i] = cycle[i]->name();
    mooseError("Cyclic dependencies detected in mesh generation: ",
               MooseUtils::join(names, " <- "));
  }
  mooseAssert(_ordered_mesh_generators.size(), "No mesh generators found");
  const auto & final_generators = _ordered_mesh_generators.back();
  // We haven't forced a final generator yet
  if (_final_generator_name.empty())
  {
    mooseAssert(final_generators.size(), "Empty vector");
    // See if we have multiple independent trees of generators
    const auto ancestor_list = resolver.getAncestors(final_generators.back());
    if (ancestor_list.size() != resolver.size() && _final_generator_name.empty())
    {
      // Need to remove duplicates and possibly perform a difference so we'll import our list
      // into a set for these operations.
      std::set<MeshGenerator *, MeshGenerator::Comparator> ancestors(ancestor_list.begin(),
                                                                     ancestor_list.end());
      // Get all of the items from the resolver so we can compare against the tree from the
      // final generator we just pulled.
      const auto & allValues = resolver.getSortedValues();
      decltype(ancestors) all(allValues.begin(), allValues.end());
      decltype(ancestors) ind_tree;
      std::set_difference(all.begin(),
                          all.end(),
                          ancestors.begin(),
                          ancestors.end(),
                          std::inserter(ind_tree, ind_tree.end()));
      std::ostringstream oss;
      oss << "Your MeshGenerator tree contains multiple possible generator outputs :\n\""
          << final_generators.back()->name()
          << " and one or more of the following from an independent set: \"";
      bool first = true;
      for (const auto & gen : ind_tree)
      {
        if (!first)
          oss << ", ";
        else
          first = false;
        oss << gen->name();
      }
      oss << "\"\n\nThis may be due to a missing dependency or may be intentional. Please either\n"
             "- check that all the mesh generators are connected as a tree and culminate in a "
             "single final mesh. Having one wrong 'input=mg' parameter is the most common error\n"
             "- add additional dependencies to remove the ambiguity if you are using a user-built "
             "MeshGenerator\n"
             "- if you intend to execute a subset of the defined generators (uncommon), select the"
             " final MeshGenerator in the [Mesh] block with the \"final_generator\" parameter.";
      mooseError(oss.str());
    }
    _final_generator_name = final_generators.back()->name();
  }
  else
    mooseAssert(hasMeshGenerator(_final_generator_name), "Missing the preset final generator");
}
Referenced by appendMeshGenerator(), and executeMeshGenerators().
executeMeshGenerators()
void MeshGeneratorSystem::executeMeshGenerators ()
Execute and clear the Mesh Generators data structure.
Definition at line 317 of file MeshGeneratorSystem.C.
{
  libmesh_parallel_only(comm());
  // we do not need to do this when there are no mesh generators
  if (_mesh_generators.empty())
    return;
  // Order the generators
  createMeshGeneratorOrder();
  std::map<std::string, std::unique_ptr<MeshBase> *> to_save_in_meshes;
  // Loop over the MeshGenerators and save all meshes marked to to_save_in_meshes
  for (const auto & generator_set : _ordered_mesh_generators)
    for (const auto & generator : generator_set)
      if (generator->hasSaveMesh())
      {
        if (_final_generator_name == generator->name())
          generator->paramError("save_with_name",
                                "Cannot use the save in capability with the final mesh generator");
        to_save_in_meshes.emplace(generator->getSavedMeshName(),
                                  &getMeshGeneratorOutput(generator->name()));
      }
  // Grab the outputs from the final generator so MeshGeneratorMesh can pick it up
  to_save_in_meshes.emplace(mainMeshGeneratorName(),
                            &getMeshGeneratorOutput(_final_generator_name));
  // Run the MeshGenerators in the proper order
  for (const auto & generator_set : _ordered_mesh_generators)
  {
    for (const auto & generator : generator_set)
    {
      const auto & name = generator->name();
      auto current_mesh = generator->generateInternal();
#ifdef DEBUG
      // Assert that the mesh is either marked as not prepared or if it is marked as prepared,
      // that it's *actually* prepared
      if (!_has_bmbb && !MeshTools::valid_is_prepared(*current_mesh))
        generator->mooseError("The generated mesh is marked as prepared but is not actually "
                              "prepared. Please edit the '",
                              generator->type(),
                              "' class to call 'set_isnt_prepared()'");
#endif
      // Now we need to possibly give this mesh to downstream generators
      auto & outputs = _mesh_generator_outputs[name];
      if (outputs.size())
      {
        auto & first_output = *outputs.begin();
        first_output = std::move(current_mesh);
        const auto & copy_from = *first_output;
        auto output_it = ++outputs.begin();
        // For all of the rest we need to make a copy
        for (; output_it != outputs.end(); ++output_it)
          (*output_it) = copy_from.clone();
      }
    }
  }
  // Grab all the valid save in meshes from the temporary map to_save_in_meshes
  // and store them in _save_in_meshes
  for (auto & [name, mesh_ptr] : to_save_in_meshes)
  {
    mooseAssert(mesh_ptr, "Invalid pointer");
    mooseAssert(*mesh_ptr, "Invalid pointer");
    if (name != mainMeshGeneratorName())
      mooseAssert(_save_in_meshes.count(name), "Mesh has not been requested for save");
    _save_in_meshes[name] = std::move(*mesh_ptr);
  }
}
Referenced by ExecuteMeshGenerators::act().
getMeshGenerator()
const MeshGenerator & MeshGeneratorSystem::getMeshGenerator (const std::string & name) const
Returns
The MeshGenerator with the name name.
Definition at line 531 of file MeshGeneratorSystem.C.
{
  const auto it = _mesh_generators.find(name);
  if (it == _mesh_generators.end())
    mooseError("Failed to find a MeshGenerator with the name '", name, "'");
  mooseAssert(it->second, "Invalid shared pointer");
  return *it->second;
}
Referenced by MooseApp::getMeshGenerator().
getMeshGeneratorInternal()
MeshGenerator & MeshGeneratorSystem::getMeshGeneratorInternal (const std::string & name) inline private
Get a MeshGenerator with the name name.
We add the "internal" here so that we allow objects that have non-const access to MooseApp to call getMeshGenerator without a const_cast. If the name was the same, you'd get an error about trying to access a private method.
Definition at line 185 of file MeshGeneratorSystem.h.
  {
    return const_cast<MeshGenerator &>(std::as_const(*this).getMeshGenerator(name));
  }
Referenced by createMeshGenerator(), and createMeshGeneratorOrder().
getMeshGeneratorNames()
std::vector< std::string > MeshGeneratorSystem::getMeshGeneratorNames () const
Get names of all mesh generators Note: This function should be called after all mesh generators are added with the 'add_mesh_generator' task.
The returned value will be undefined and depends on the ordering that mesh generators are added by MOOSE if the function is called during the 'add_mesh_generator' task.
Definition at line 541 of file MeshGeneratorSystem.C.
{
  std::vector<std::string> names;
  for (auto & pair : _mesh_generators)
    names.push_back(pair.first);
  return names;
}
Referenced by MooseApp::getMeshGeneratorNames().
getMeshGeneratorOutput()
std::unique_ptr< MeshBase > & MeshGeneratorSystem::getMeshGeneratorOutput (const MeshGeneratorName & name)
Get a reference to a pointer that will be the output of the MeshGenerator named name.
Definition at line 506 of file MeshGeneratorSystem.C.
{
  mooseAssert(_app.constructingMeshGenerators() ||
                  _app.actionWarehouse().getCurrentTaskName() == "execute_mesh_generators",
              "Incorrect call time");
  auto it = _mesh_generator_outputs.find(name);
  mooseAssert(it != _mesh_generator_outputs.end(), "Not initialized");
  it->second.push_back(nullptr);
  return it->second.back();
}
Referenced by executeMeshGenerators(), and MeshGenerator::getMeshByName().
getMeshGeneratorParamDependencies()
std::vector< std::pair< std::string, MeshGeneratorName > > MeshGeneratorSystem::getMeshGeneratorParamDependencies (const InputParameters & params, const bool allow_empty = false) const private
Gets the MeshGeneratorNames that are referenced in an object's parameters.
The result is returned as a pair of param name -> MeshGeneratorName in order to provide context.
The allow_empty param sets whether or not to report names that are empty.
Definition at line 93 of file MeshGeneratorSystem.C.
{
  std::vector<std::pair<std::string, MeshGeneratorName>> dependencies;
  auto add_dependency =
      [&dependencies, &allow_empty](const auto & param_name, const auto & dependency)
  {
    if (dependency.size() || allow_empty)
      dependencies.emplace_back(param_name, dependency);
  };
  for (const auto & [name, param] : params)
    if (const auto dependency =
            dynamic_cast<const Parameters::Parameter<MeshGeneratorName> *>(param.get()))
      add_dependency(name, dependency->get());
    else if (const auto dependencies =
                 dynamic_cast<const Parameters::Parameter<std::vector<MeshGeneratorName>> *>(
                     param.get()))
    {
      if (allow_empty && dependencies->get().empty())
        add_dependency(name, std::string());
      for (const auto & dependency : dependencies->get())
        add_dependency(name, dependency);
    }
  return dependencies;
}
Referenced by appendMeshGenerator(), createAddedMeshGenerators(), and createMeshGenerator().
getSavedMesh()
std::unique_ptr< MeshBase > MeshGeneratorSystem::getSavedMesh (const std::string & name)
Get the saved mesh by name.
Definition at line 559 of file MeshGeneratorSystem.C.
{
  auto find_mesh = _save_in_meshes.find(name);
  if (find_mesh == _save_in_meshes.end())
    mooseError("Failed to find a saved mesh with the name '", name, "'");
  auto & mesh_unique_ptr = find_mesh->second;
  if (!mesh_unique_ptr)
    mooseError("While getting the saved mesh generator '",
               name,
               "', said mesh has already been retreived");
  return std::move(mesh_unique_ptr);
}
Referenced by SetupMeshAction::act(), and MooseApp::getMeshGeneratorMesh().
getSavedMeshNames()
std::vector< std::string > MeshGeneratorSystem::getSavedMeshNames () const
Get all user-defined saved meshes except main and main_displaced.
Definition at line 550 of file MeshGeneratorSystem.C.
{
  std::vector<std::string> names;
  for (auto & pair : _save_in_meshes)
    names.push_back(pair.first);
  return names;
}
hasBreakMeshByBlockGenerator()
bool MeshGeneratorSystem::hasBreakMeshByBlockGenerator () const inline
Returns
Whether any of our mesh generators were of type BreakMeshByBlockGenerator
Definition at line 151 of file MeshGeneratorSystem.h.
{ return _has_bmbb; }
Referenced by ExtraNodesetGenerator::generate(), and SideSetsFromNormalsGenerator::generate().
hasMeshGenerator()
bool MeshGeneratorSystem::hasMeshGenerator (const MeshGeneratorName & name) const
Returns
Whether or not a mesh generator exists with the name name.
Definition at line 519 of file MeshGeneratorSystem.C.
{
  return _mesh_generators.count(name);
}
Referenced by appendMeshGenerator(), createAddedMeshGenerators(), createMeshGenerator(), createMeshGeneratorOrder(), and MooseApp::hasMeshGenerator().
hasMeshGeneratorParams()
bool MeshGeneratorSystem::hasMeshGeneratorParams (const MeshGeneratorName & name) const
Whether or not we know about the parameters for a MeshGenerator with the given name.
This is primarily for error checking. If MeshGenerator dependencies are screwed up, someone could be looking for a MeshGenerator that hasn't been constructed yet. With this, at least we can give the user some context that we know the generator exists, just that the dependencies are hosed.
Definition at line 525 of file MeshGeneratorSystem.C.
{
  return _mesh_generator_params.count(name);
}
mainMeshGeneratorName()
static std::string MeshGeneratorSystem::mainMeshGeneratorName () inline static
The name reserved for the "main" mesh generator which is the one used for the numerical solver downstream.
Definition at line 146 of file MeshGeneratorSystem.h.
{ return "main"; };
Referenced by executeMeshGenerators(), MooseApp::getMeshGeneratorMesh(), and MeshGenerator::MeshGenerator().
perfGraph()
PerfGraph & PerfGraphInterface::perfGraph () inherited
Get the PerfGraph.
Definition at line 78 of file PerfGraphInterface.C.
{
  return _pg_moose_app.perfGraph();
}
Referenced by CommonOutputAction::act(), PerfGraphData::finalize(), and PerfGraphOutput::output().
registerTimedSection() [1/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
Returns
The ID of the section - use when starting timing
Definition at line 53 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(timed_section_name, level);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
registerTimedSection() [2/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level, const std::string & live_message, const bool print_dots = true) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
live_message The message to be printed to the screen during execution
print_dots Whether or not progress dots should be printed for this section
Returns
The ID of the section - use when starting timing
Definition at line 64 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(
        timedSectionName(section_name), level, live_message, print_dots);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
timedSectionName()
std::string PerfGraphInterface::timedSectionName (const std::string & section_name) const protected inherited
Returns
The name of the timed section with the name section_name.
Optionally adds a prefix if one is defined.
Definition at line 47 of file PerfGraphInterface.C.
{
  return _prefix.empty() ? "" : (_prefix + "::") + section_name;
}
Referenced by PerfGraphInterface::registerTimedSection().
validParams()
InputParameters PerfGraphInterface::validParams () static inherited
Definition at line 16 of file PerfGraphInterface.C.
{
  InputParameters params = emptyInputParameters();
  return params;
}
Member Data Documentation
_app
MooseApp& MeshGeneratorSystem::_app private
The MooseApp that owns this system.
Definition at line 191 of file MeshGeneratorSystem.h.
Referenced by addMeshGenerator(), appendingMeshGenerators(), createAddedMeshGenerators(), createMeshGenerator(), createMeshGeneratorOrder(), and getMeshGeneratorOutput().
_final_generator_name
std::string MeshGeneratorSystem::_final_generator_name private
The final mesh generator name to use.
Definition at line 207 of file MeshGeneratorSystem.h.
Referenced by appendMeshGenerator(), createAddedMeshGenerators(), createMeshGeneratorOrder(), and executeMeshGenerators().
_has_bmbb
bool MeshGeneratorSystem::_has_bmbb private
Whether any of the mesh generators are a BreakMeshByBlockGenerator.
Definition at line 213 of file MeshGeneratorSystem.h.
Referenced by addMeshGenerator(), executeMeshGenerators(), and hasBreakMeshByBlockGenerator().
_mesh_generator_outputs
std::map<std::string, std::list<std::unique_ptr<MeshBase> > > MeshGeneratorSystem::_mesh_generator_outputs private
Holds the output for each mesh generator - including duplicates needed downstream.
Definition at line 204 of file MeshGeneratorSystem.h.
Referenced by createMeshGenerator(), executeMeshGenerators(), and getMeshGeneratorOutput().
_mesh_generator_params
std::unordered_map<std::string, std::pair<std::string, InputParameters> > MeshGeneratorSystem::_mesh_generator_params private
The MeshGenerators declared using addMeshGenerator(), cleared after createMeshGenerators() Key is the name, pair contains the type and the params.
Definition at line 195 of file MeshGeneratorSystem.h.
Referenced by addMeshGenerator(), appendMeshGenerator(), createAddedMeshGenerators(), createMeshGenerator(), and hasMeshGeneratorParams().
_mesh_generators
std::map<std::string, std::shared_ptr<MeshGenerator> > MeshGeneratorSystem::_mesh_generators private
Owning storage for mesh generators, map of name -> MeshGenerator.
Definition at line 198 of file MeshGeneratorSystem.h.
Referenced by appendMeshGenerator(), createMeshGenerator(), createMeshGeneratorOrder(), executeMeshGenerators(), getMeshGenerator(), getMeshGeneratorNames(), and hasMeshGenerator().
_ordered_mesh_generators
std::vector<std::vector<MeshGenerator *> > MeshGeneratorSystem::_ordered_mesh_generators private
Holds the ordered mesh generators from createMeshGeneratorOrder() until they are executed in executeMeshGenerators()
Definition at line 201 of file MeshGeneratorSystem.h.
Referenced by appendMeshGenerator(), createMeshGeneratorOrder(), and executeMeshGenerators().
_pg_moose_app
MooseApp& PerfGraphInterface::_pg_moose_app protected inherited
The MooseApp that owns the PerfGraph.
Definition at line 124 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::perfGraph().
_prefix
const std::string PerfGraphInterface::_prefix protected inherited
A prefix to use for all sections.
Definition at line 127 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::timedSectionName().
_save_in_meshes
std::map<std::string, std::unique_ptr<MeshBase> > MeshGeneratorSystem::_save_in_meshes private
Holds the map of save in mesh -> name.
Definition at line 210 of file MeshGeneratorSystem.h.
Referenced by createMeshGenerator(), executeMeshGenerators(), getSavedMesh(), and getSavedMeshNames().
The documentation for this class was generated from the following files:
moose/framework/include/base/MeshGeneratorSystem.h
moose/framework/src/base/MeshGeneratorSystem.C