Zapdos: ReporterData Class Reference
ReporterData Class Reference
This is a helper class for managing the storage of declared Reporter object values.
#include <ReporterData.h>
Classes
class WriteKey
Public Member Functions
ReporterData (MooseApp &moose_app)
template<typename T >
bool hasReporterValue (const ReporterName &reporter_name) const
Return True if a Reporter value with the given type and name have been created.
bool hasReporterValue (const ReporterName &reporter_name) const
Return True if a Reporter value with any type exists with the given name.
template<typename T >
bool hasReporterState (const ReporterName &reporter_name) const
bool hasReporterState (const ReporterName &reporter_name) const
std::set< ReporterName > getReporterNames () const
Return a list of all reporter names.
std::set< std::string > getPostprocessorNames () const
Return a list of all postprocessor names.
DenseVector< Real > getAllRealReporterValues () const
Get all real reporter values including postprocessor and vector postprocessor values into a dense vector.
std::vector< std::string > getAllRealReporterFullNames () const
Get full names of all real reporter values Note: For a postprocessor, the full name is the postprocessor name plus '/value'.
template<typename T >
const T & getReporterValue (const ReporterName &reporter_name, const MooseObject &consumer, const ReporterMode &mode, const std::size_t time_index=0) const
Method for returning read only references to Reporter values.
template<typename T >
const T & getReporterValue (const ReporterName &reporter_name, const std::size_t time_index=0) const
Method for returning a read-only reference to Reporter values that already exist.
template<typename T >
void setReporterValue (const ReporterName &reporter_name, const T &value, const std::size_t time_index=0)
Method for setting Reporter values that already exist.
template<typename T >
void needReporterTimeIndex (const ReporterName &reporter_name, const std::size_t time_index)
Method for setting that a specific time index is requested for a Reporter value.
const ReporterProducerEnum & getReporterMode (const ReporterName &reporter_name) const
Return the ReporterProducerEnum for an existing ReporterValue.
std::string getReporterInfo (const ReporterName &reporter_name) const
Gets information pertaining to the Reporter with name reporter_name.
std::string getReporterInfo () const
Gets information about all declared/requested Reporters.
template<typename T , typename S , typename... Args>
T & declareReporterValue (const ReporterName &reporter_name, const ReporterMode &mode, const MooseObject &producer, Args &&... args)
Method for returning a writable reference to the current Reporter value.
void finalize (const std::string &object_name)
Helper function for performing post calculation actions via the ReporterContext objects.
void copyValuesBack ()
At the end of a timestep this method is called to copy the values back in time in preparation for the next timestep.
void check () const
Perform integrity check for get/declare calls.
bool hasReporterWithMode (const std::string &obj_name, const ReporterMode &mode) const
Return true if the supplied mode exists in the produced Reporter values.
const ReporterContextBase & getReporterContextBase (const ReporterName &reporter_name) const
ReporterContextBase & getReporterContextBase (const ReporterName &reporter_name)
const ReporterStateBase & getReporterStateBase (const ReporterName &reporter_name) const
@Returns The ReporterStateBase associated with the Reporter with name reporter_name.
ReporterStateBase & getReporterStateBase (const ReporterName &reporter_name)
Static Public Member Functions
static std::string getReporterInfo (const ReporterStateBase &state, const ReporterContextBase *context)
Gets information pertaining to the Reporter with state state and possibly context context.
Private Member Functions
template<typename T >
ReporterState< T > & getReporterStateHelper (const ReporterName &reporter_name, bool declare, const MooseObject *moose_object=nullptr) const
Helper method for creating the necessary RestartableData for Reporter values.
RestartableDataValue & getRestartableDataHelper (std::unique_ptr< RestartableDataValue > data_ptr, bool declare) const
Helper for registering data with the MooseApp to avoid cyclic includes.
Private Attributes
MooseApp & _app
For accessing the restart/recover system, which is where Reporter values are stored.
std::map< ReporterName, ReporterStateBase * > _states
Map from ReporterName -> Reporter state.
std::map< ReporterName, std::unique_ptr< ReporterContextBase > > _context_ptrs
The ReporterContext objects are created when a value is declared.
Detailed Description
This is a helper class for managing the storage of declared Reporter object values.
This design of the system is a generalization of the VectorPostprocessor system that the Reporter objects replaced.
Foremost, this object doesn't store the data. It simply acts as helper for using the restart system of the MooseApp. This object automatically handles the old, older, ... data. All declarations create std::pair<T, std::vector<T>> restartable data on the MooseApp, where the first value is the current value and the data in the vector are the older data.
The ReporterState object is a RestartableData object that serves as a helper for managing the time history. A "context" object also exists that uses the ReporterState for performing special operations. Refer to ReporterState.h/C for more information.
It is important to note that the Reporter values are not threaded. However, the Reporter objects are UserObject based, so the calculation of the values can be threaded.
This object also relies on ReporterName objects, which are simply a combination of the Reporter object name and the data name. If you recall the VectorPostprocessor system on which this is based required an object name and a vector name. The ReporterName class simply provides a convenient way to provide that information in a single object. Special Parser syntax was also defined so that application developers do not have to have input parameters for both the object and data names (see Parser.C/h).
Definition at line 48 of file ReporterData.h.
Constructor & Destructor Documentation
ReporterData()
ReporterData::ReporterData (MooseApp & moose_app)
Definition at line 13 of file ReporterData.C.
: _app(moose_app) {}
Member Function Documentation
check()
void ReporterData::check () const
Perform integrity check for get/declare calls.
Definition at line 137 of file ReporterData.C.
{
  std::string missing;
  for (const auto & name_state_pair : _states)
    if (!hasReporterValue(name_state_pair.first))
      missing += getReporterInfo(name_state_pair.first) + "\n";
  if (missing.size())
    mooseError("The following Reporter(s) were not declared:\n\n", missing);
}
Referenced by DumpObjectsProblem::addAuxVariable().
copyValuesBack()
void ReporterData::copyValuesBack ()
At the end of a timestep this method is called to copy the values back in time in preparation for the next timestep.
See FEProblemBase::advanceState
Definition at line 16 of file ReporterData.C.
{
  for (const auto & name_context_pair : _context_ptrs)
    name_context_pair.second->copyValuesBack();
}
Referenced by FEProblemBase::advanceState().
declareReporterValue()
template<typename T , typename S , typename... Args> T & ReporterData::declareReporterValue (const ReporterName & reporter_name, const ReporterMode & mode, const MooseObject & producer, Args &&... args)
Method for returning a writable reference to the current Reporter value.
This method is used by the Reporter class to produce values.
Template Parameters
T The Reporter value C++ type.
S (optional) The ReporterContext for performing specialized actions after the values have been computed. For example, ReporterBroadcastContext automatically broadcasts the computed value. See ReporterState.C/h for more information.
Parameters
reporter_name The name of the reporter value, which includes the object name and the data name.
mode The mode that the produced value will be computed by the Reporter object
producer The MooseObject that produces this value
args (optional) Any number of optional arguments passed into the Context type given by the S template parameter. If S = ReporterContext then the first argument can be used as the default value (see ReporterContext.h).
The ReporterContext objects allow for custom handling of data (e.g., broadcasting the value). The get/declare methods can be called in any order thus an the underlying RestartableData object is often created by the get method before it is declared. Therefore the custom functionality cannot be handled by specializing the RestartableData/ReporterState object directly because the state is often created prior to the declaration that dictates how the produced value shall be computed. Thus, the reason for the separate ReporterContext objects.
Definition at line 391 of file ReporterData.h.
{
  // Get/create the ReporterState
  auto & state = getReporterStateHelper<T>(reporter_name, /* declare = */ true, &producer);
  // They key in _states (ReporterName) is not unique by special type. This is done on purpose
  // because we want to store reporter names a single name regardless of special type.
  // Because of this, we have the case where someone could request a reporter value
  // that is later declared as a pp or a vpp value. In this case, when it is first
  // requested, the _state entry will have a key and name with a special type of ANY.
  // When it's declared here (later), we will still find the correct entry because
  // we don't check the special type in the key/name. But... we want the actual
  // key and name to represent a pp or a vpp. Therefore, we'll set it properly,
  // remove the entry in the map (which has the ANY key), and re-add it so that it
  // has the pp/vpp key. This allows us to identify Reporters that really represent
  // pps/vpps in output and in error reporting.
  if (reporter_name.isPostprocessor() && !state.getReporterName().isPostprocessor())
  {
    state.setIsPostprocessor();
    _states.erase(reporter_name);
    _states.emplace(reporter_name, &state);
  }
  else if (reporter_name.isVectorPostprocessor() &&
           !state.getReporterName().isVectorPostprocessor())
  {
    state.setIsVectorPostprocessor();
    _states.erase(reporter_name);
    _states.emplace(reporter_name, &state);
  }
  mooseAssert(!_context_ptrs.count(reporter_name), "Context already exists");
  // Create the ReporterContext
  auto context_ptr = std::make_unique<S>(_app, producer, state, args...);
  context_ptr->init(mode); // initialize the mode, see ContextReporter
  _context_ptrs.emplace(reporter_name, std::move(context_ptr));
  return state.value();
}
Referenced by ReporterTransferInterface::declareClone(), ReporterGeneralContext< T >::declareClone(), VectorPostprocessor::declareVector(), ReporterTransferInterface::declareVectorClone(), and ReporterGeneralContext< T >::declareVectorClone().
finalize()
void ReporterData::finalize (const std::string & object_name)
Helper function for performing post calculation actions via the ReporterContext objects.
If you recall, the original VectorPostprocessor system included the ability to perform some scatter and broadcast actions via the special call on the storage helper object. This is a replacement for that method that leverages the ReporterContext objects to perform value specific actions, including some automatic operations depending how the data is produced and consumed.
See FEProblemBase::joinAndFinalize
Definition at line 23 of file ReporterData.C.
{
  for (auto & name_context_pair : _context_ptrs)
    if (name_context_pair.first.getObjectName() == object_name)
      name_context_pair.second->finalize();
}
Referenced by FEProblemBase::joinAndFinalize().
getAllRealReporterFullNames()
std::vector< std::string > ReporterData::getAllRealReporterFullNames () const
Get full names of all real reporter values Note: For a postprocessor, the full name is the postprocessor name plus '/value'.
For a vector postprocessor, the full name is the vector postprocessor name plus the vector name followed by '/#' where '#' is the index of the vector.
Definition at line 81 of file ReporterData.C.
{
  std::vector<std::string> output;
  for (const auto & name_context_pair : _context_ptrs)
  {
    const ReporterName & rname = name_context_pair.first;
    if (hasReporterValue<Real>(rname))
      output.push_back(rname.getCombinedName());
    if (hasReporterValue<std::vector<Real>>(rname))
    {
      auto pname = rname.getCombinedName();
      const auto & vec = getReporterValue<std::vector<Real>>(pname);
      for (unsigned int i = 0; i < vec.size(); ++i)
        output.push_back(pname + "/" + std::to_string(i));
    }
  }
  return output;
}
Referenced by FEProblemBase::execute().
getAllRealReporterValues()
DenseVector< Real > ReporterData::getAllRealReporterValues () const
Get all real reporter values including postprocessor and vector postprocessor values into a dense vector.
Definition at line 56 of file ReporterData.C.
{
  DenseVector<Real> all_values;
  std::vector<Real> & output = all_values.get_values();
  for (const auto & name_context_pair : _context_ptrs)
  {
    const ReporterName & rname = name_context_pair.first;
    if (hasReporterValue<Real>(rname))
      output.push_back(getReporterValue<Real>(rname.getCombinedName()));
    if (hasReporterValue<std::vector<Real>>(rname))
    {
      const auto & vec = getReporterValue<std::vector<Real>>(rname.getCombinedName());
      for (const auto & v : vec)
        output.push_back(v);
    }
  }
  return all_values;
}
Referenced by FEProblemBase::execute().
getPostprocessorNames()
std::set< std::string > ReporterData::getPostprocessorNames () const
Return a list of all postprocessor names.
Definition at line 46 of file ReporterData.C.
{
  std::set<std::string> output;
  for (const auto & name_context_pair : _context_ptrs)
    if (name_context_pair.first.isPostprocessor())
      output.insert(name_context_pair.first.getObjectName());
  return output;
}
Referenced by FEProblemBase::checkDuplicatePostprocessorVariableNames().
getReporterContextBase() [1/2]
ReporterContextBase & ReporterData::getReporterContextBase (const ReporterName & reporter_name)
Definition at line 113 of file ReporterData.C.
{
  if (!hasReporterValue(reporter_name))
    mooseError("Unable to locate Reporter context with name: ", reporter_name);
  return *_context_ptrs.at(reporter_name);
}
getReporterContextBase() [2/2]
const ReporterContextBase & ReporterData::getReporterContextBase (const ReporterName & reporter_name) const
Returns
The ReporterContextBase associated with the Reporter with name reporter_name.
Definition at line 105 of file ReporterData.C.
{
  if (!hasReporterValue(reporter_name))
    mooseError("Unable to locate Reporter context with name: ", reporter_name);
  return *_context_ptrs.at(reporter_name);
}
Referenced by ReporterTransferInterface::declareClone(), AccumulateReporter::declareLateValues(), ReporterTransferInterface::declareVectorClone(), getReporterInfo(), getReporterMode(), VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper(), hasReporterValue(), JSONOutput::outputReporters(), ReporterTransferInterface::resizeReporter(), ReporterTransferInterface::transferReporter(), and ReporterTransferInterface::transferToVectorReporter().
getReporterInfo() [1/3]
std::string ReporterData::getReporterInfo () const
Gets information about all declared/requested Reporters.
Definition at line 222 of file ReporterData.C.
{
  std::string out = _states.empty() ? "No reporters were requested or declared." : "";
  for (const auto & name : getReporterNames())
    out += getReporterInfo(name) + "\n";
  return out;
}
Referenced by check(), getReporterInfo(), getReporterStateHelper(), and ReporterContextBase::requiresConsumerModes().
getReporterInfo() [2/3]
std::string ReporterData::getReporterInfo (const ReporterName & reporter_name) const
Gets information pertaining to the Reporter with name reporter_name.
Definition at line 214 of file ReporterData.C.
{
  return getReporterInfo(getReporterStateBase(reporter_name),
                         hasReporterValue(reporter_name) ? &getReporterContextBase(reporter_name)
                                                         : nullptr);
}
getReporterInfo() [3/3]
std::string ReporterData::getReporterInfo (const ReporterStateBase & state, const ReporterContextBase * context) static
Gets information pertaining to the Reporter with state state and possibly context context.
Definition at line 178 of file ReporterData.C.
{
  std::stringstream oss;
  const auto & name = state.getReporterName();
  if (name.isPostprocessor())
    oss << "Postprocessor \"" << name.getObjectName() << "\":\n";
  else
  {
    oss << name.specialTypeToName() << " \"" << name.getCombinedName() << "\":\n  Type:\n    "
        << state.valueType() << "\n";
  }
  oss << "  Producer:\n    ";
  if (context)
  {
    oss << context->getProducer().type() << " \"" << context->getProducer().name() << "\"";
    oss << "\n  Context type:\n    " << context->contextType();
  }
  else
    oss << "None";
  oss << "\n  Consumer(s):\n";
  if (state.getConsumers().empty())
    oss << "    None\n";
  else
    for (const auto & mode_object_pair : state.getConsumers())
    {
      const ReporterMode mode = mode_object_pair.first;
      const MooseObject * object = mode_object_pair.second;
      oss << "    " << object->typeAndName() << " (mode: " << mode << ")\n";
    }
  return oss.str();
}
Referenced by ReporterDebugOutput::output().
getReporterMode()
const ReporterProducerEnum & ReporterData::getReporterMode (const ReporterName & reporter_name) const
Return the ReporterProducerEnum for an existing ReporterValue.
Parameters
reporter_name The name of the reporter value, which includes the object name and the data name.
Definition at line 166 of file ReporterData.C.
{
  return getReporterContextBase(reporter_name).getProducerModeEnum();
}
Referenced by AccumulateReporter::declareAccumulateHelper().
getReporterNames()
std::set< ReporterName > ReporterData::getReporterNames () const
Return a list of all reporter names.
Definition at line 37 of file ReporterData.C.
{
  std::set<ReporterName> output;
  for (const auto & name_context_pair : _context_ptrs)
    output.insert(name_context_pair.second->name());
  return output;
}
Referenced by getReporterInfo(), AdvancedOutput::initAvailableLists(), TableOutput::outputVectorPostprocessors(), and XMLOutput::outputVectorPostprocessors().
getReporterStateBase() [1/2]
ReporterStateBase & ReporterData::getReporterStateBase (const ReporterName & reporter_name)
Definition at line 129 of file ReporterData.C.
{
  if (!hasReporterState(reporter_name))
    mooseError("Unable to locate Reporter state with name: ", reporter_name);
  return *_states.at(reporter_name);
}
getReporterStateBase() [2/2]
const ReporterStateBase & ReporterData::getReporterStateBase (const ReporterName & reporter_name) const
@Returns The ReporterStateBase associated with the Reporter with name reporter_name.
Definition at line 121 of file ReporterData.C.
{
  if (!hasReporterState(reporter_name))
    mooseError("Unable to locate Reporter state with name: ", reporter_name);
  return *_states.at(reporter_name);
}
Referenced by ReporterTransferInterface::addReporterTransferMode(), getReporterInfo(), and hasReporterState().
getReporterStateHelper()
template<typename T > ReporterState< T > & ReporterData::getReporterStateHelper (const ReporterName & reporter_name, bool declare, const MooseObject * moose_object = nullptr) const private
Helper method for creating the necessary RestartableData for Reporter values.
Template Parameters
T The desired C++ type for the Reporter value
Parameters
reporter_name Object/data name for the Reporter value
declare Flag indicating if the ReporterValue is being declared or read. This flag is passed to the existing MooseApp restart/recover system that errors if a value is declared multiple times.
moose_object The object requesting/declaring the state, used in error handling.
Definition at line 321 of file ReporterData.h.
{
  if (hasReporterState(reporter_name))
  {
    const auto error_helper =
        [this, &reporter_name, &moose_object, &declare](const std::string & suffix)
    {
      std::stringstream oss;
      oss << "While " << (declare ? "declaring" : "requesting") << " a "
          << reporter_name.specialTypeToName() << " value with the name \""
          << reporter_name.getValueName() << "\"";
      if (!reporter_name.isPostprocessor() && !reporter_name.isVectorPostprocessor())
        oss << " and type \"" << MooseUtils::prettyCppType<T>() << "\"";
      oss << ",\na Reporter with the same name " << suffix << ".\n\n";
      oss << getReporterInfo(reporter_name);
      if (moose_object)
        moose_object->mooseError(oss.str());
      else
        mooseError(oss.str());
    };
    if (declare && hasReporterValue(reporter_name))
      error_helper("has already been declared");
    if (!hasReporterState<T>(reporter_name))
    {
      std::stringstream oss;
      oss << "has been " << (declare || !hasReporterValue(reporter_name) ? "requested" : "declared")
          << " with a different type";
      error_helper(oss.str());
    }
  }
  // Reporter states are stored as restartable data. The act of registering restartable data
  // may be done multiple times with the same name, which will happen when more than one
  // get value is done, or a get value and a declare is done. With this, we create a new
  // state every time, but said created state may not be the actual state if this state
  // is already registered as restartable data. Therefore, we create a state, and then
  // cast the restartable data received back to a state (which may be different than
  // the one we created, but that's okay)
  auto state_unique_ptr = std::make_unique<ReporterState<T>>(reporter_name);
  auto & restartable_value = getRestartableDataHelper(std::move(state_unique_ptr), declare);
  auto * state = dynamic_cast<ReporterState<T> *>(&restartable_value);
  mooseAssert(state, "Cast failed. The check above must be broken!");
  // See declareReporterValue for a comment on what happens if a state for the same
  // name is requested but with different special types. TLDR: ReporterNames with
  // different special types are not unique so they'll be the same entry
  _states.emplace(reporter_name, state);
  return *state;
}
getReporterValue() [1/2]
template<typename T > const T & ReporterData::getReporterValue (const ReporterName & reporter_name, const MooseObject & consumer, const ReporterMode & mode, const std::size_t time_index = 0) const
Method for returning read only references to Reporter values.
Template Parameters
T The Reporter value C++ type.
Parameters
reporter_name The name of the reporter value, which includes the object name and the data name.
consumer The MooseObject consuming the Reporter value (for error reporting)
mode The mode that the value will be consumed by the by the ReporterInterface object
time_index (optional) When not provided or zero is provided the current value is returned. If an index greater than zero is provided then the corresponding old data is returned (1 = old, 2 = older, etc.).
Definition at line 379 of file ReporterData.h.
{
  auto & state = getReporterStateHelper<T>(reporter_name, /* declare = */ false, &consumer);
  state.addConsumer(mode, consumer);
  return state.value(time_index);
}
Referenced by FEProblemBase::getPostprocessorValueByName(), PostprocessorInterface::getPostprocessorValueByNameInternal(), ReporterInterface::getReporterValueByName(), VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), VectorPostprocessorInterface::getVectorPostprocessorContextByNameHelper(), FEProblemBase::getVectorPostprocessorValueByName(), TableOutput::outputReporter(), Exodus::outputReporters(), TableOutput::outputVectorPostprocessors(), XMLOutput::outputVectorPostprocessors(), and ReporterContext< T >::transferToVector().
getReporterValue() [2/2]
template<typename T > const T & ReporterData::getReporterValue (const ReporterName & reporter_name, const std::size_t time_index = 0) const
Method for returning a read-only reference to Reporter values that already exist.
Template Parameters
T The Reporter value C++ type.
Parameters
reporter_name The name of the reporter value, which includes the object name and the data name.
time_index (optional) When not provided or zero is provided the current value is returned. If an index greater than zero is provided then the corresponding old data is returned (1 = old, 2 = older, etc.).
Definition at line 454 of file ReporterData.h.
{
  if (!hasReporterValue<T>(reporter_name))
    mooseError("Reporter name \"",
               reporter_name,
               "\" with type \"",
               MooseUtils::prettyCppType<T>(),
               "\" is not declared.");
  // Force the const version of value, which does not allow for increasing time index
  return static_cast<const ReporterState<T> &>(
             getReporterStateHelper<T>(reporter_name, /* declare = */ false))
      .value(time_index);
}
getRestartableDataHelper()
RestartableDataValue & ReporterData::getRestartableDataHelper (std::unique_ptr< RestartableDataValue > data_ptr, bool declare) const private
Helper for registering data with the MooseApp to avoid cyclic includes.
Definition at line 149 of file ReporterData.C.
{
  return _app.registerRestartableData(std::move(data_ptr), 0, !declare);
}
Referenced by getReporterStateHelper().
hasReporterState() [1/2]
template<typename T > bool ReporterData::hasReporterState (const ReporterName & reporter_name) const
Returns
True if a ReporterState is defined for the Reporter with name reporter_name and the given type.
Definition at line 445 of file ReporterData.h.
{
  if (!hasReporterState(reporter_name))
    return false;
  return dynamic_cast<const ReporterState<T> *>(&getReporterStateBase(reporter_name));
}
Referenced by getReporterStateBase(), getReporterStateHelper(), and hasReporterState().
hasReporterState() [2/2]
bool ReporterData::hasReporterState (const ReporterName & reporter_name) const
Returns
True if a ReporterState is defined for the Reporter with name reporter_name.
Definition at line 172 of file ReporterData.C.
{
  return _states.count(reporter_name);
}
hasReporterValue() [1/2]
template<typename T > bool ReporterData::hasReporterValue (const ReporterName & reporter_name) const
Return True if a Reporter value with the given type and name have been created.
Definition at line 436 of file ReporterData.h.
{
  if (!hasReporterValue(reporter_name))
    return false;
  return dynamic_cast<const ReporterContext<T> *>(&getReporterContextBase(reporter_name));
}
Referenced by check(), ReporterTransferInterface::checkHasReporterValue(), AccumulateReporter::declareAccumulateHelper(), AccumulateReporter::declareLateValues(), getAllRealReporterFullNames(), getAllRealReporterValues(), getReporterContextBase(), getReporterInfo(), getReporterStateHelper(), PostprocessorInterface::hasPostprocessorByName(), FEProblemBase::hasPostprocessorValueByName(), hasReporterValue(), ReporterInterface::hasReporterValueByName(), VectorPostprocessorInterface::hasVectorPostprocessorByName(), MooseParsedFunctionWrapper::initialize(), PostprocessorInterface::isDefaultPostprocessorValueByName(), TableOutput::outputReporter(), Exodus::outputReporters(), TableOutput::outputVectorPostprocessors(), and XMLOutput::outputVectorPostprocessors().
hasReporterValue() [2/2]
bool ReporterData::hasReporterValue (const ReporterName & reporter_name) const
Return True if a Reporter value with any type exists with the given name.
Definition at line 31 of file ReporterData.C.
{
  return _context_ptrs.count(reporter_name);
}
hasReporterWithMode()
bool ReporterData::hasReporterWithMode (const std::string & obj_name, const ReporterMode & mode) const
Return true if the supplied mode exists in the produced Reporter values.
See also
CSV.C/h
Definition at line 156 of file ReporterData.C.
{
  for (const auto & name_context_pair : _context_ptrs)
    if (name_context_pair.first.getObjectName() == obj_name &&
        name_context_pair.second->getProducerModeEnum() == mode)
      return true;
  return false;
}
Referenced by CSV::output().
needReporterTimeIndex()
template<typename T > void ReporterData::needReporterTimeIndex (const ReporterName & reporter_name, const std::size_t time_index)
Method for setting that a specific time index is requested for a Reporter value.
Template Parameters
T The Reporter value C++ type.
Parameters
reporter_name The name of the reporter value, which includes the object name and the data name.
time_index The time index that is needed
Definition at line 483 of file ReporterData.h.
{
  getReporterValue<T>(reporter_name, 0); // for error checking that it is declared
  getReporterStateHelper<T>(reporter_name, /* declare = */ false).value(time_index);
}
Referenced by Receiver::Receiver().
setReporterValue()
template<typename T > void ReporterData::setReporterValue (const ReporterName & reporter_name, const T & value, const std::size_t time_index = 0)
Method for setting Reporter values that already exist.
Template Parameters
T The Reporter value C++ type.
Parameters
reporter_name The name of the reporter value, which includes the object name and the data name.
value The value to which the Reporter will be changed to.
time_index (optional) When not provided or zero is provided the current value is returned. If an index greater than zero is provided then the corresponding old data is returned (1 = old, 2 = older, etc.). WARNING! This method is designed for setting values outside of the traditional interfaces such as is necessary for Transfers. This is an advanced capability that should be used with caution.
See also
FEProblemBase::setPostprocessorValueByName
Definition at line 472 of file ReporterData.h.
{
  // https://stackoverflow.com/questions/123758/how-do-i-remove-code-duplication-between-similar-const-and-non-const-member-func
  const auto & me = *this;
  const_cast<T &>(me.getReporterValue<T>(reporter_name, time_index)) = value;
}
Referenced by FEProblemBase::setPostprocessorValueByName(), FEProblemBase::setVectorPostprocessorValueByName(), and ReporterContext< T >::transfer().
Member Data Documentation
_app
MooseApp& ReporterData::_app private
For accessing the restart/recover system, which is where Reporter values are stored.
Definition at line 284 of file ReporterData.h.
Referenced by declareReporterValue(), and getRestartableDataHelper().
_context_ptrs
std::map<ReporterName, std::unique_ptr<ReporterContextBase> > ReporterData::_context_ptrs private
The ReporterContext objects are created when a value is declared.
The context objects include a reference to the associated ReporterState values. This container stores the context object for each Reporter value.
Definition at line 316 of file ReporterData.h.
Referenced by copyValuesBack(), declareReporterValue(), finalize(), getAllRealReporterFullNames(), getAllRealReporterValues(), getPostprocessorNames(), getReporterContextBase(), getReporterNames(), hasReporterValue(), and hasReporterWithMode().
_states
std::map<ReporterName, ReporterStateBase *> ReporterData::_states mutable private
Map from ReporterName -> Reporter state.
We need to keep track of all of the states that are created so that we can check them after Reporter declaration to make sure all states have a producer (are delcared). We cannot check _context_ptrs, because a context is only defined for Reporters that have been declared. This is mutable so that it can be inserted into when requesting Reporter values.
Definition at line 311 of file ReporterData.h.
Referenced by check(), declareReporterValue(), getReporterInfo(), getReporterStateBase(), getReporterStateHelper(), and hasReporterState().
The documentation for this class was generated from the following files:
moose/framework/include/reporters/ReporterData.h
moose/framework/src/reporters/ReporterData.C