Zapdos: ElementPairLocator Class Reference
ElementPairLocator Class Reference
This is the ElementPairLocator class.
#include <ElementPairLocator.h>
Public Types
typedef std::list< std::pair< const Elem *, const Elem * > > ElementPairList
Public Member Functions
ElementPairLocator (unsigned int interface_id)
virtual ~ElementPairLocator ()
virtual void reinit ()
virtual void update ()
const ElementPairList & getElemPairs () const
const ElementPairInfo & getElemPairInfo (std::pair< const Elem *, const Elem * > elem_pair) const
Protected Attributes
const ElementPairList * _elem_pairs
std::map< std::pair< const Elem *, const Elem * >, ElementPairInfo > _element_pair_info
unsigned int _interface_id
Detailed Description
This is the ElementPairLocator class.
This is a base class that finds the element pairs for ElementElementConstraint
Definition at line 34 of file ElementPairLocator.h.
Member Typedef Documentation
ElementPairList
typedef std::list<std::pair<const Elem *, const Elem *> > ElementPairLocator::ElementPairList
Definition at line 44 of file ElementPairLocator.h.
Constructor & Destructor Documentation
ElementPairLocator()
ElementPairLocator::ElementPairLocator (unsigned int interface_id) inline
Definition at line 37 of file ElementPairLocator.h.
                                                : _elem_pairs(NULL)
  {
    _interface_id = interface_id;
  }
~ElementPairLocator()
virtual ElementPairLocator::~ElementPairLocator () inline virtual
Definition at line 42 of file ElementPairLocator.h.
{}
Member Function Documentation
getElemPairInfo()
const ElementPairInfo & ElementPairLocator::getElemPairInfo (std::pair< const Elem *, const Elem * > elem_pair) const inline
Definition at line 58 of file ElementPairLocator.h.
  {
    std::map<std::pair<const Elem *, const Elem *>, ElementPairInfo>::const_iterator it =
        _element_pair_info.find(elem_pair);
    if (it == _element_pair_info.end())
      mooseError("Could not find ElemenPairInfo for specified element pair");
    return it->second;
  }
Referenced by NonlinearSystemBase::constraintJacobians(), and NonlinearSystemBase::constraintResiduals().
getElemPairs()
const ElementPairList & ElementPairLocator::getElemPairs () const inline
Definition at line 50 of file ElementPairLocator.h.
  {
    if (_elem_pairs == NULL)
      mooseError("_elem_pairs has not yet been initialized and it needs to be initialized by a "
                 "derived class");
    return *_elem_pairs;
  }
Referenced by NonlinearSystemBase::constraintJacobians(), and NonlinearSystemBase::constraintResiduals().
reinit()
virtual void ElementPairLocator::reinit () inline virtual
Definition at line 46 of file ElementPairLocator.h.
{};
Referenced by GeometricSearchData::reinit(), and GeometricSearchData::update().
update()
virtual void ElementPairLocator::update () inline virtual
Definition at line 48 of file ElementPairLocator.h.
{};
Referenced by GeometricSearchData::update().
Member Data Documentation
_elem_pairs
const ElementPairList* ElementPairLocator::_elem_pairs protected
Definition at line 68 of file ElementPairLocator.h.
Referenced by getElemPairs().
_element_pair_info
std::map<std::pair<const Elem *, const Elem *>, ElementPairInfo> ElementPairLocator::_element_pair_info protected
Definition at line 69 of file ElementPairLocator.h.
Referenced by getElemPairInfo().
_interface_id
unsigned int ElementPairLocator::_interface_id protected
Definition at line 70 of file ElementPairLocator.h.
Referenced by ElementPairLocator().
The documentation for this class was generated from the following file:
moose/framework/include/geomsearch/ElementPairLocator.h