Zapdos: MooseObjectWarehouseBase< T > Class Template Reference
MooseObjectWarehouseBase< T > Class Template Reference
A base storage container for MooseObjects.
#include <MooseObjectWarehouseBase.h>
Public Member Functions
MooseObjectWarehouseBase (bool threaded=true)
Constructor.
virtual ~MooseObjectWarehouseBase ()
Destructor.
virtual void addObject (std::shared_ptr< T > object, THREAD_ID tid=0, bool recurse=true)
Adds an object to the storage structure.
unsigned int size (THREAD_ID tid=0) const
Return how many kernels we store in the current warehouse.
std::set< SubdomainID > getActiveBlocks (THREAD_ID tid=0) const
Return a set of active SubdomainsIDs.
virtual void updateActive (THREAD_ID tid=0)
Updates the active objects storage.
void sort (THREAD_ID tid=0)
Sort the objects using the DependencyResolver.
void subdomainsCovered (std::set< SubdomainID > &subdomains_covered, std::set< std::string > &unique_variables, THREAD_ID tid=0) const
Populates a set of covered subdomains and the associated variable names.
THREAD_ID numThreads () const
Return the number of threads.
std::string activeObjectsToFormattedString (THREAD_ID tid=0, const std::string &prefix="[DBG]") const
Output the active content of the warehouse to a string, meant to be output to the console.
const std::vector< std::shared_ptr< T > > & getObjects (THREAD_ID tid=0) const
Retrieve complete vector to the all/block/boundary restricted objects for a given thread.
const std::map< SubdomainID, std::vector< std::shared_ptr< T > > > & getBlockObjects (THREAD_ID tid=0) const
const std::vector< std::shared_ptr< T > > & getBlockObjects (SubdomainID id, THREAD_ID tid=0) const
const std::map< BoundaryID, std::vector< std::shared_ptr< T > > > & getBoundaryObjects (THREAD_ID tid=0) const
const std::vector< std::shared_ptr< T > > & getBoundaryObjects (BoundaryID id, THREAD_ID tid=0) const
const std::vector< std::shared_ptr< T > > & getActiveObjects (THREAD_ID tid=0) const
Retrieve complete vector to the active all/block/boundary restricted objects for a given thread.
const std::map< SubdomainID, std::vector< std::shared_ptr< T > > > & getActiveBlockObjects (THREAD_ID tid=0) const
const std::vector< std::shared_ptr< T > > & getActiveBlockObjects (SubdomainID id, THREAD_ID tid=0) const
const std::map< BoundaryID, std::vector< std::shared_ptr< T > > > & getActiveBoundaryObjects (THREAD_ID tid=0) const
const std::vector< std::shared_ptr< T > > & getActiveBoundaryObjects (BoundaryID id, THREAD_ID tid=0) const
bool hasObjects (THREAD_ID tid=0) const
Convenience functions for determining if objects exist.
bool hasActiveObjects (THREAD_ID tid=0) const
bool hasActiveBlockObjects (THREAD_ID tid=0) const
bool hasActiveBlockObjects (SubdomainID id, THREAD_ID tid=0) const
bool hasActiveBoundaryObjects (THREAD_ID tid=0) const
bool hasActiveBoundaryObjects (BoundaryID id, THREAD_ID tid=0) const
bool hasBoundaryObjects (BoundaryID id, THREAD_ID tid=0) const
bool hasActiveObject (const std::string &name, THREAD_ID tid=0) const
Convenience functions for checking/getting specific objects.
std::shared_ptr< T > getObject (const std::string &name, THREAD_ID tid=0) const
std::shared_ptr< T > getActiveObject (const std::string &name, THREAD_ID tid=0) const
void updateVariableDependency (std::set< MooseVariableFieldBase * > &needed_moose_vars, THREAD_ID tid=0) const
Update variable dependency vector.
void updateBlockVariableDependency (SubdomainID id, std::set< MooseVariableFieldBase * > &needed_moose_vars, THREAD_ID tid=0) const
void updateBoundaryVariableDependency (std::set< MooseVariableFieldBase * > &needed_moose_vars, THREAD_ID tid=0) const
void updateBoundaryVariableDependency (BoundaryID id, std::set< MooseVariableFieldBase * > &needed_moose_vars, THREAD_ID tid=0) const
void updateBlockFEVariableCoupledVectorTagDependency (SubdomainID id, std::set< TagID > &needed_fe_var_vector_tags, THREAD_ID tid=0) const
Update FE variable coupleable vector tag vector.
void updateBoundaryFEVariableCoupledVectorTagDependency (BoundaryID id, std::set< TagID > &needed_fe_var_vector_tags, THREAD_ID tid=0) const
void updateMatPropDependency (std::set< unsigned int > &needed_mat_props, THREAD_ID tid=0) const
Update material property dependency vector.
void updateBlockMatPropDependency (SubdomainID id, std::set< unsigned int > &needed_mat_props, THREAD_ID tid=0) const
void updateBoundaryMatPropDependency (std::set< unsigned int > &needed_mat_props, THREAD_ID tid=0) const
void updateBoundaryMatPropDependency (BoundaryID id, std::set< unsigned int > &needed_mat_props, THREAD_ID tid=0) const
Protected Member Functions
void checkThreadID (THREAD_ID tid) const
Calls assert on thread id.
Static Protected Member Functions
static void updateActiveHelper (std::vector< std::shared_ptr< T > > &active, const std::vector< std::shared_ptr< T > > &all)
Helper method for updating active vectors.
static void sortHelper (std::vector< std::shared_ptr< T > > &objects)
Helper method for sorting vectors of objects.
static void updateVariableDependencyHelper (std::set< MooseVariableFieldBase * > &needed_moose_vars, const std::vector< std::shared_ptr< T > > &objects)
Helper method for updating variable dependency vector.
static void updateFEVariableCoupledVectorTagDependencyHelper (std::set< TagID > &needed_fe_var_vector_tags, const std::vector< std::shared_ptr< T > > &objects)
Helper method for updating FE variable coupleable vector tag vector.
static void updateMatPropDependencyHelper (std::set< unsigned int > &needed_mat_props, const std::vector< std::shared_ptr< T > > &objects)
Helper method for updating material property dependency vector.
Protected Attributes
const THREAD_ID _num_threads
Convenience member storing the number of threads used for storage (1 or libMesh::n_threads)
std::vector< std::vector< std::shared_ptr< T > > > _all_objects
Storage container for the ALL pointers (THREAD_ID on outer vector)
std::vector< std::vector< std::shared_ptr< T > > > _active_objects
All active objects (THREAD_ID on outer vector)
std::vector< std::map< SubdomainID, std::vector< std::shared_ptr< T > > > > _all_block_objects
std::vector< std::map< SubdomainID, std::vector< std::shared_ptr< T > > > > _active_block_objects
Active block restricted objects (THREAD_ID on outer vector)
std::vector< std::map< BoundaryID, std::vector< std::shared_ptr< T > > > > _all_boundary_objects
std::vector< std::map< BoundaryID, std::vector< std::shared_ptr< T > > > > _active_boundary_objects
Active boundary restricted objects (THREAD_ID on outer vector)
Friends
class MaterialWarehouse
Detailed Description
template<typename T>
class MooseObjectWarehouseBase< T >
A base storage container for MooseObjects.
Definition at line 29 of file MooseObjectWarehouseBase.h.
Constructor & Destructor Documentation
MooseObjectWarehouseBase()
template<typename T > MooseObjectWarehouseBase< T >::MooseObjectWarehouseBase (bool threaded = true)
Constructor.
Parameters
threaded When true (default) threaded storage is enabled.
Definition at line 247 of file MooseObjectWarehouseBase.h.
  : _num_threads(threaded ? libMesh::n_threads() : 1),
    _all_objects(_num_threads),
    _active_objects(_num_threads),
    _all_block_objects(_num_threads),
    _active_block_objects(_num_threads),
    _all_boundary_objects(_num_threads),
    _active_boundary_objects(_num_threads)
{
}
~MooseObjectWarehouseBase()
template<typename T > MooseObjectWarehouseBase< T >::~MooseObjectWarehouseBase virtual
Destructor.
Definition at line 259 of file MooseObjectWarehouseBase.h.
{
}
Member Function Documentation
activeObjectsToFormattedString()
template<typename T > std::string MooseObjectWarehouseBase< T >::activeObjectsToFormattedString (THREAD_ID tid = 0, const std::string & prefix = "[DBG]") const
Output the active content of the warehouse to a string, meant to be output to the console.
Parameters
tid the thread id
prefix a string to prepend to the string
Definition at line 756 of file MooseObjectWarehouseBase.h.
{
  std::vector<std::string> output;
  for (const auto & object : _active_objects[tid])
    output.push_back(object->name());
  return ConsoleUtils::formatString(MooseUtils::join(output, " "), prefix);
}
Referenced by NonlinearThread::printBlockExecutionInformation(), NonlinearThread::printBoundaryExecutionInformation(), ComputeNodalKernelBCJacobiansThread::printGeneralExecutionInformation(), ComputeNodalKernelBcsThread::printGeneralExecutionInformation(), ComputeNodalKernelJacobiansThread::printGeneralExecutionInformation(), and ComputeNodalKernelsThread::printGeneralExecutionInformation().
addObject()
template<typename T > void MooseObjectWarehouseBase< T >::addObject (std::shared_ptr< T > object, THREAD_ID tid = 0, bool recurse = true) virtual
Adds an object to the storage structure.
Parameters
tid The thread ID (default is 0)
recurse Whether or not to build recusive warehouses (typically for Kernels)
Reimplemented in MooseObjectWarehouse< ADDirichletBCBase >, ExecuteMooseObjectWarehouse< AuxKernelTempl >, MooseObjectWarehouse< AuxKernelTempl >, ExecuteMooseObjectWarehouse< AuxKernelTempl< Real > >, MooseObjectWarehouse< AuxKernelTempl< Real > >, ExecuteMooseObjectWarehouse< AuxKernelTempl< RealVectorValue > >, MooseObjectWarehouse< AuxKernelTempl< RealVectorValue > >, MooseObjectWarehouse< AuxKernelType >, ExecuteMooseObjectWarehouse< AuxScalarKernel >, MooseObjectWarehouse< AuxScalarKernel >, MooseObjectWarehouse< Constraint >, ExecuteMooseObjectWarehouse< Control >, MooseObjectWarehouse< Control >, MooseObjectWarehouse< DGKernelBase >, MooseObjectWarehouse< DiracKernelBase >, MooseObjectWarehouse< DirichletBCBase >, MooseObjectWarehouse< ElementDamper >, MooseObjectWarehouse< Function >, MooseObjectWarehouse< GeneralDamper >, MooseObjectWarehouse< Indicator >, MooseObjectWarehouse< IntegratedBCBase >, MooseObjectWarehouse< InterfaceKernelBase >, MooseObjectWarehouse< InternalSideIndicator >, MooseObjectWarehouse< KernelBase >, MooseObjectWarehouse< Marker >, MooseObjectWarehouse< MaterialBase >, MooseObjectWarehouse< MeshDivision >, ExecuteMooseObjectWarehouse< MultiApp >, MooseObjectWarehouse< MultiApp >, MooseObjectWarehouse< NodalBCBase >, MooseObjectWarehouse< NodalConstraint >, MooseObjectWarehouse< NodalDamper >, MooseObjectWarehouse< NodalKernelBase >, MooseObjectWarehouse< ScalarKernelBase >, ExecuteMooseObjectWarehouse< T >, MooseObjectWarehouse< T >, ExecuteMooseObjectWarehouse< Transfer >, MooseObjectWarehouse< Transfer >, ExecuteMooseObjectWarehouse< TransientMultiApp >, MooseObjectWarehouse< TransientMultiApp >, ExecuteMooseObjectWarehouse< UserObject >, and MooseObjectWarehouse< UserObject >.
Definition at line 273 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  // Stores object in list of all objects
  _all_objects[tid].push_back(object);
  // If enabled, store object in a list of all active
  bool enabled = object->enabled();
  if (enabled)
    _active_objects[tid].push_back(object);
  // Perform casts to the Block/BoundaryRestrictable
  std::shared_ptr<BoundaryRestrictable> bnd =
      std::dynamic_pointer_cast<BoundaryRestrictable>(object);
  std::shared_ptr<BlockRestrictable> blk = std::dynamic_pointer_cast<BlockRestrictable>(object);
  // Boundary Restricted
  if (bnd && bnd->boundaryRestricted())
  {
    const std::set<BoundaryID> & ids = bnd->boundaryIDs();
    for (std::set<BoundaryID>::const_iterator it = ids.begin(); it != ids.end(); ++it)
    {
      _all_boundary_objects[tid][*it].push_back(object);
      if (enabled)
        _active_boundary_objects[tid][*it].push_back(object);
    }
  }
  // Block Restricted
  else if (blk)
  {
    const std::set<SubdomainID> & ids =
        blk->blockRestricted() ? blk->blockIDs() : blk->meshBlockIDs();
    for (std::set<SubdomainID>::const_iterator it = ids.begin(); it != ids.end(); ++it)
    {
      _all_block_objects[tid][*it].push_back(object);
      if (enabled)
        _active_block_objects[tid][*it].push_back(object);
    }
    // Check variables
    std::shared_ptr<Coupleable> c_ptr = std::dynamic_pointer_cast<Coupleable>(object);
    if (c_ptr)
      for (MooseVariableFieldBase * var : c_ptr->getCoupledMooseVars())
        blk->checkVariable(*var);
    const InputParameters & parameters = object->parameters();
    SubProblem & problem = *parameters.get<SubProblem *>("_subproblem");
    THREAD_ID tid = parameters.get<THREAD_ID>("_tid");
    if (parameters.isParamValid("variable"))
    {
      // Try the scalar version first
      std::string variable_name = parameters.getMooseType("variable");
      if (variable_name == "")
        // When using vector variables, we are only going to use the first one in the list at the
        // interface level...
        variable_name = parameters.getVecMooseType("variable")[0];
      blk->checkVariable(problem.getVariable(
          tid, variable_name, Moose::VarKindType::VAR_ANY, Moose::VarFieldType::VAR_FIELD_ANY));
    }
  }
}
Referenced by FEProblemBase::addInitialCondition(), FVInitialConditionWarehouse::addObject(), InitialConditionWarehouse::addObject(), MooseObjectWarehouse< T >::addObject(), and NonlinearSystemBase::addSplit().
checkThreadID()
template<typename T > void MooseObjectWarehouseBase< T >::checkThreadID (THREAD_ID tid) const inline protected
Calls assert on thread id.
Definition at line 787 of file MooseObjectWarehouseBase.h.
{
  mooseAssert(tid < _num_threads,
              "Attempting to access a thread id ("
                  << tid << ") greater than the number allowed by the storage item ("
                  << _num_threads << ")");
}
Referenced by MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getActiveBlockObjects(), MooseObjectWarehouseBase< T >::getActiveBlocks(), MooseObjectWarehouseBase< T >::getActiveBoundaryObjects(), MooseObjectWarehouseBase< T >::getActiveObject(), MooseObjectWarehouseBase< T >::getActiveObjects(), MooseObjectWarehouseBase< T >::getBlockObjects(), MooseObjectWarehouseBase< T >::getBoundaryObjects(), MooseObjectWarehouseBase< T >::getObject(), MooseObjectWarehouseBase< T >::getObjects(), MooseObjectWarehouseBase< T >::hasActiveBlockObjects(), MooseObjectWarehouseBase< T >::hasActiveBoundaryObjects(), MooseObjectWarehouseBase< T >::hasActiveObject(), MooseObjectWarehouseBase< T >::hasActiveObjects(), MooseObjectWarehouseBase< T >::hasBoundaryObjects(), MooseObjectWarehouseBase< T >::hasObjects(), ConstraintWarehouse::residualEnd(), MooseObjectWarehouseBase< T >::size(), MaterialWarehouse::sort(), MooseObjectWarehouseBase< T >::sort(), and MooseObjectWarehouseBase< T >::updateActive().
getActiveBlockObjects() [1/2]
template<typename T > const std::vector< std::shared_ptr< T > > & MooseObjectWarehouseBase< T >::getActiveBlockObjects (SubdomainID id, THREAD_ID tid = 0) const
Definition at line 434 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  const auto iter = _active_block_objects[tid].find(id);
  mooseAssert(iter != _active_block_objects[tid].end(),
              "Unable to located active block objects for the given id: " << id << ".");
  return iter->second;
}
getActiveBlockObjects() [2/2]
template<typename T > const std::map< SubdomainID, std::vector< std::shared_ptr< T > > > & MooseObjectWarehouseBase< T >::getActiveBlockObjects (THREAD_ID tid = 0) const inline
Definition at line 426 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _active_block_objects[tid];
}
Referenced by MaterialPropertyInterface::buildRequiredMaterials(), FEProblemBase::checkProblemIntegrity(), NonlinearThread::computeOnElement(), NonlinearThread::computeOnInternalFace(), ComputeFullJacobianThread::computeOnInternalFace(), FEProblemBase::getFVMatsAndDependencies(), BlockRestrictable::hasBlockMaterialPropertyHelper(), ComputeIndicatorThread::onElement(), ComputeMarkerThread::onElement(), ComputeMaterialsObjectThread::onElement(), ComputeIndicatorThread::onInternalSide(), ComputeNodalKernelJacobiansThread::onNode(), ComputeNodalKernelsThread::onNode(), ComputeInitialConditionThread::operator()(), ComputeFVInitialConditionThread::operator()(), ComputeDiracThread::printBlockExecutionInformation(), ComputeIndicatorThread::printBlockExecutionInformation(), ComputeMarkerThread::printBlockExecutionInformation(), FEProblemBase::reinitMaterials(), Moose::Mortar::setupMortarMaterials(), MooseObjectWarehouseBase< T >::updateBlockFEVariableCoupledVectorTagDependency(), MooseObjectWarehouseBase< T >::updateBlockMatPropDependency(), and MooseObjectWarehouseBase< T >::updateBlockVariableDependency().
getActiveBlocks()
template<typename T > std::set< SubdomainID > MooseObjectWarehouseBase< T >::getActiveBlocks (THREAD_ID tid = 0) const
Return a set of active SubdomainsIDs.
Definition at line 534 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  std::set<SubdomainID> ids;
  for (const auto & object_pair : _active_block_objects[tid])
    ids.insert(object_pair.first);
  return ids;
}
Referenced by FEProblemBase::checkProblemIntegrity().
getActiveBoundaryObjects() [1/2]
template<typename T > const std::vector< std::shared_ptr< T > > & MooseObjectWarehouseBase< T >::getActiveBoundaryObjects (BoundaryID id, THREAD_ID tid = 0) const
Definition at line 415 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  const auto iter = _active_boundary_objects[tid].find(id);
  mooseAssert(iter != _active_boundary_objects[tid].end(),
              "Unable to located active boundary objects for the given id: " << id << ".");
  return iter->second;
}
getActiveBoundaryObjects() [2/2]
template<typename T > const std::map< BoundaryID, std::vector< std::shared_ptr< T > > > & MooseObjectWarehouseBase< T >::getActiveBoundaryObjects (THREAD_ID tid = 0) const inline
Definition at line 407 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _active_boundary_objects[tid];
}
Referenced by NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeMortarNodalVars(), NonlinearSystemBase::computeNodalBCs(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), NonlinearThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnBoundary(), NonlinearThread::computeOnInterface(), ComputeFullJacobianThread::computeOnInterface(), BoundaryRestrictable::hasBoundaryMaterialPropertyHelper(), ComputeMaterialsObjectThread::onBoundary(), ComputeMaterialsObjectThread::onInterface(), ComputeBoundaryInitialConditionThread::onNode(), ComputeNodalKernelBCJacobiansThread::onNode(), ComputeNodalKernelBcsThread::onNode(), FEProblemBase::reinitMaterialsBoundary(), FEProblemBase::reinitMaterialsInterface(), NonlinearSystemBase::setInitialSolution(), MooseObjectWarehouseBase< T >::updateBoundaryFEVariableCoupledVectorTagDependency(), MooseObjectWarehouseBase< T >::updateBoundaryMatPropDependency(), and MooseObjectWarehouseBase< T >::updateBoundaryVariableDependency().
getActiveObject()
template<typename T > std::shared_ptr< T > MooseObjectWarehouseBase< T >::getActiveObject (const std::string & name, THREAD_ID tid = 0) const
Definition at line 523 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  for (const auto & object : _active_objects[tid])
    if (object->name() == name)
      return object;
  mooseError("Unable to locate active object: ", name, ".");
}
Referenced by DerivativeParsedMaterialHelperTempl< is_ad >::assembleDerivatives(), FEProblemBase::getFunction(), FEProblemBase::getMaterial(), FEProblemBase::getMeshDivision(), NonlinearSystemBase::getSplit(), LibtorchControlValuePostprocessor::initialSetup(), and LibtorchArtificialNeuralNetParameters::initialSetup().
getActiveObjects()
template<typename T > const std::vector< std::shared_ptr< T > > & MooseObjectWarehouseBase< T >::getActiveObjects (THREAD_ID tid = 0) const inline
Retrieve complete vector to the active all/block/boundary restricted objects for a given thread.
Parameters
tid The thread id to retrieve objects from
Definition at line 399 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _active_objects[tid];
}
Referenced by DumpObjectsProblem::addAuxVariable(), FEProblemBase::backupMultiApps(), NonlinearEigenSystem::checkIntegrity(), FEProblemBase::checkProblemIntegrity(), NonlinearSystemBase::computeDamping(), NonlinearSystemBase::computeDiracContributions(), FEProblemBase::computeIndicators(), FEProblemBase::computeMarkers(), FEProblemBase::computeMultiAppsDT(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeScalarKernelsJacobians(), AuxiliarySystem::computeScalarVars(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), FEProblemBase::execTransfers(), FEProblemBase::finalizeMultiApps(), FEProblemBase::finishMultiAppStep(), ConstraintWarehouse::getActiveNodalConstraints(), FEProblemBase::getTransfers(), FEProblemBase::incrementMultiAppTStep(), ComputeDiracThread::onElement(), ComputeElemDampingThread::onElement(), ComputeNodalDampingThread::onNode(), FEProblemBase::postExecute(), FEProblemBase::projectInitialConditionOnCustomRange(), FEProblemBase::projectSolution(), FEProblemBase::restoreMultiApps(), and AuxiliarySystem::setScalarVariableCoupleableTags().
getBlockObjects() [1/2]
template<typename T > const std::vector< std::shared_ptr< T > > & MooseObjectWarehouseBase< T >::getBlockObjects (SubdomainID id, THREAD_ID tid = 0) const
Definition at line 388 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  const auto iter = _all_block_objects[tid].find(id);
  mooseAssert(iter != _all_block_objects[tid].end(),
              "Unable to located active block objects for the given id: " << id << ".");
  return iter->second;
}
getBlockObjects() [2/2]
template<typename T > const std::map< SubdomainID, std::vector< std::shared_ptr< T > > > & MooseObjectWarehouseBase< T >::getBlockObjects (THREAD_ID tid = 0) const inline
Definition at line 380 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _all_block_objects[tid];
}
Referenced by MaterialPropertyDebugOutput::printMaterialMap().
getBoundaryObjects() [1/2]
template<typename T > const std::vector< std::shared_ptr< T > > & MooseObjectWarehouseBase< T >::getBoundaryObjects (BoundaryID id, THREAD_ID tid = 0) const
Definition at line 369 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  const auto iter = _all_boundary_objects[tid].find(id);
  mooseAssert(iter != _all_boundary_objects[tid].end(),
              "Unable to located active boundary objects for the given id: " << id << ".");
  return iter->second;
}
getBoundaryObjects() [2/2]
template<typename T > const std::map< BoundaryID, std::vector< std::shared_ptr< T > > > & MooseObjectWarehouseBase< T >::getBoundaryObjects (THREAD_ID tid = 0) const inline
Definition at line 353 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _all_boundary_objects[tid];
}
Referenced by ComputeFullJacobianThread::computeOnBoundary(), and MaterialPropertyDebugOutput::printMaterialMap().
getObject()
template<typename T > std::shared_ptr< T > MooseObjectWarehouseBase< T >::getObject (const std::string & name, THREAD_ID tid = 0) const
Definition at line 512 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  for (const auto & object : _all_objects[tid])
    if (object->name() == name)
      return object;
  mooseError("Unable to locate object: ", name, ".");
}
Referenced by FEProblemBase::getMultiApp().
getObjects()
template<typename T > const std::vector< std::shared_ptr< T > > & MooseObjectWarehouseBase< T >::getObjects (THREAD_ID tid = 0) const inline
Retrieve complete vector to the all/block/boundary restricted objects for a given thread.
Parameters
tid The thread id to retrieve objects from
Definition at line 345 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _all_objects[tid];
}
Referenced by FEProblemBase::checkNonlocalCoupling(), MooseApp::errorCheck(), MooseObjectTagWarehouse< T >::getMatrixTagObjectWarehouse(), MooseObjectTagWarehouse< T >::getMatrixTagsObjectWarehouse(), MooseObjectTagWarehouse< T >::getVectorTagObjectWarehouse(), MooseObjectTagWarehouse< T >::getVectorTagsObjectWarehouse(), and FEProblemBase::setNonlocalCouplingMatrix().
hasActiveBlockObjects() [1/2]
template<typename T > bool MooseObjectWarehouseBase< T >::hasActiveBlockObjects (SubdomainID id, THREAD_ID tid = 0) const
Definition at line 472 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  const auto iter = _active_block_objects[tid].find(id);
  return iter != _active_block_objects[tid].end();
}
hasActiveBlockObjects() [2/2]
template<typename T > bool MooseObjectWarehouseBase< T >::hasActiveBlockObjects (THREAD_ID tid = 0) const
Definition at line 461 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  bool has_active_block_objects = false;
  for (const auto & object_pair : _active_block_objects[tid])
    has_active_block_objects |= !(object_pair.second.empty());
  return has_active_block_objects;
}
Referenced by AuxiliarySystem::computeElementalVarsHelper(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeMortarNodalVars(), AuxiliarySystem::computeNodalVarsHelper(), NonlinearThread::computeOnElement(), ComputeFullJacobianThread::computeOnInternalFace(), NonlinearSystemBase::computeResidualInternal(), BlockRestrictable::hasBlockMaterialPropertyHelper(), ComputeIndicatorThread::onElement(), ComputeMarkerThread::onElement(), ComputeMaterialsObjectThread::onElement(), ProjectMaterialProperties::onElement(), ComputeIndicatorThread::onInternalSide(), NonlinearThread::onInternalSide(), ComputeNodalKernelJacobiansThread::onNode(), ComputeNodalKernelsThread::onNode(), ComputeInitialConditionThread::operator()(), ComputeFVInitialConditionThread::operator()(), ComputeJacobianBlocksThread::postInternalSide(), FEProblemBase::prepareMaterials(), ComputeDiracThread::printBlockExecutionInformation(), ComputeIndicatorThread::printBlockExecutionInformation(), ComputeMarkerThread::printBlockExecutionInformation(), NonlinearThread::printBlockExecutionInformation(), FEProblemBase::reinitMaterials(), MooseObjectWarehouseBase< T >::updateBlockFEVariableCoupledVectorTagDependency(), MooseObjectWarehouseBase< T >::updateBlockMatPropDependency(), and MooseObjectWarehouseBase< T >::updateBlockVariableDependency().
hasActiveBoundaryObjects() [1/2]
template<typename T > bool MooseObjectWarehouseBase< T >::hasActiveBoundaryObjects (BoundaryID id, THREAD_ID tid = 0) const
Definition at line 492 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  const auto iter = _active_boundary_objects[tid].find(id);
  return iter != _active_boundary_objects[tid].end();
}
hasActiveBoundaryObjects() [2/2]
template<typename T > bool MooseObjectWarehouseBase< T >::hasActiveBoundaryObjects (THREAD_ID tid = 0) const
Definition at line 481 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  bool has_active_boundary_objects = false;
  for (const auto & object_pair : _active_boundary_objects[tid])
    has_active_boundary_objects |= !(object_pair.second.empty());
  return has_active_boundary_objects;
}
Referenced by AuxiliarySystem::computeElementalVarsHelper(), NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeMortarNodalVars(), NonlinearSystemBase::computeNodalBCs(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), AuxiliarySystem::computeNodalVarsHelper(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnInterface(), NonlinearSystemBase::computeResidualInternal(), BoundaryRestrictable::hasBoundaryMaterialPropertyHelper(), NonlinearSystemBase::needBoundaryMaterialOnSide(), FEProblemBase::needInterfaceMaterialOnSide(), NonlinearSystemBase::needInterfaceMaterialOnSide(), ComputeMaterialsObjectThread::onBoundary(), NonlinearThread::onBoundary(), ComputeMaterialsObjectThread::onInterface(), NonlinearThread::onInterface(), ComputeBoundaryInitialConditionThread::onNode(), ComputeNodalKernelBCJacobiansThread::onNode(), ComputeNodalKernelBcsThread::onNode(), NonlinearThread::printBoundaryExecutionInformation(), ComputeNodalKernelBCJacobiansThread::printGeneralExecutionInformation(), FEProblemBase::reinitMaterialsBoundary(), FEProblemBase::reinitMaterialsInterface(), NonlinearSystemBase::setInitialSolution(), MooseObjectWarehouseBase< T >::updateBoundaryFEVariableCoupledVectorTagDependency(), MooseObjectWarehouseBase< T >::updateBoundaryMatPropDependency(), and MooseObjectWarehouseBase< T >::updateBoundaryVariableDependency().
hasActiveObject()
template<typename T > bool MooseObjectWarehouseBase< T >::hasActiveObject (const std::string & name, THREAD_ID tid = 0) const
Convenience functions for checking/getting specific objects.
Definition at line 501 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  for (const auto & object : _active_objects[tid])
    if (object->name() == name)
      return true;
  return false;
}
Referenced by FEProblemBase::hasFunction(), and FEProblemBase::hasMultiApp().
hasActiveObjects()
template<typename T > bool MooseObjectWarehouseBase< T >::hasActiveObjects (THREAD_ID tid = 0) const
Definition at line 453 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return !_active_objects[tid].empty();
}
Referenced by DumpObjectsProblem::addAuxVariable(), NonlinearEigenSystem::checkIntegrity(), NonlinearSystemBase::checkKernelCoverage(), NonlinearSystemBase::computeDamping(), NonlinearSystemBase::computeDiracContributions(), FEProblemBase::computeIndicators(), NonlinearSystemBase::computeJacobianInternal(), FEProblemBase::computeMarkers(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeScalarKernelsJacobians(), AuxiliarySystem::computeScalarVars(), NonlinearSystemBase::containsTimeKernel(), FEProblemBase::execMultiAppTransfers(), ConstraintWarehouse::hasActiveNodalConstraints(), FEProblemBase::hasMultiApps(), ComputeNodalKernelBcsThread::printGeneralExecutionInformation(), ComputeNodalKernelJacobiansThread::printGeneralExecutionInformation(), ComputeNodalKernelsThread::printGeneralExecutionInformation(), FEProblemBase::projectInitialConditionOnCustomRange(), FEProblemBase::projectSolution(), MooseObjectWarehouseBase< T >::updateMatPropDependency(), and MooseObjectWarehouseBase< T >::updateVariableDependency().
hasBoundaryObjects()
template<typename T > bool MooseObjectWarehouseBase< T >::hasBoundaryObjects (BoundaryID id, THREAD_ID tid = 0) const
Definition at line 361 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _all_boundary_objects[tid].find(id) != _all_boundary_objects[tid].end();
}
hasObjects()
template<typename T > bool MooseObjectWarehouseBase< T >::hasObjects (THREAD_ID tid = 0) const
Convenience functions for determining if objects exist.
Definition at line 445 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return !_all_objects[tid].empty();
}
Referenced by DumpObjectsProblem::addAuxVariable().
numThreads()
template<typename T > THREAD_ID MooseObjectWarehouseBase< T >::numThreads () const inline
Return the number of threads.
Definition at line 176 of file MooseObjectWarehouseBase.h.
{ return _num_threads; }
size()
template<typename T > unsigned int MooseObjectWarehouseBase< T >::size (THREAD_ID tid = 0) const
Return how many kernels we store in the current warehouse.
Definition at line 265 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  return _all_objects[tid].size();
}
Referenced by NonlinearThread::printBlockExecutionInformation().
sort()
template<typename T > void MooseObjectWarehouseBase< T >::sort (THREAD_ID tid = 0)
Sort the objects using the DependencyResolver.
Definition at line 574 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  for (auto & object_pair : _all_block_objects[tid])
    sortHelper(object_pair.second);
  for (auto & object_pair : _all_boundary_objects[tid])
    sortHelper(object_pair.second);
  sortHelper(_all_objects[tid]);
  // The active lists now must be update to reflect the order changes
  updateActive(tid);
}
Referenced by DumpObjectsProblem::addAuxVariable(), ScalarInitialConditionWarehouse::initialSetup(), FVInitialConditionWarehouse::initialSetup(), and InitialConditionWarehouse::initialSetup().
sortHelper()
template<typename T > void MooseObjectWarehouseBase< T >::sortHelper (std::vector< std::shared_ptr< T > > & objects) static protected
Helper method for sorting vectors of objects.
Definition at line 767 of file MooseObjectWarehouseBase.h.
{
  // Do nothing if the vector is empty
  if (objects.empty())
    return;
  try
  {
    // Sort based on dependencies
    DependencyResolverInterface::sort<std::shared_ptr<T>>(objects);
  }
  catch (CyclicDependencyException<std::shared_ptr<T>> & e)
  {
    DependencyResolverInterface::cyclicDependencyError<std::shared_ptr<T>>(
        e, "Cyclic dependency detected in object ordering");
  }
}
Referenced by MaterialWarehouse::sort(), and MooseObjectWarehouseBase< T >::sort().
subdomainsCovered()
template<typename T > void MooseObjectWarehouseBase< T >::subdomainsCovered (std::set< SubdomainID > & subdomains_covered, std::set< std::string > & unique_variables, THREAD_ID tid = 0) const
Populates a set of covered subdomains and the associated variable names.
Definition at line 743 of file MooseObjectWarehouseBase.h.
{
  for (const auto & object : _active_objects[tid])
    unique_variables.insert(object->variable().name());
  for (const auto & object_pair : _active_block_objects[tid])
    subdomains_covered.insert(object_pair.first);
}
Referenced by NonlinearSystemBase::checkKernelCoverage().
updateActive()
template<typename T > void MooseObjectWarehouseBase< T >::updateActive (THREAD_ID tid = 0) virtual
Updates the active objects storage.
Reimplemented in MaterialWarehouse, ConstraintWarehouse, ExecuteMooseObjectWarehouse< T >, ExecuteMooseObjectWarehouse< AuxScalarKernel >, ExecuteMooseObjectWarehouse< AuxKernelTempl< Real > >, ExecuteMooseObjectWarehouse< AuxKernelTempl< RealVectorValue > >, ExecuteMooseObjectWarehouse< AuxKernelTempl >, ExecuteMooseObjectWarehouse< UserObject >, ExecuteMooseObjectWarehouse< MultiApp >, ExecuteMooseObjectWarehouse< TransientMultiApp >, ExecuteMooseObjectWarehouse< Transfer >, ExecuteMooseObjectWarehouse< Control >, MooseObjectTagWarehouse< T >, MooseObjectTagWarehouse< DiracKernelBase >, MooseObjectTagWarehouse< NodalKernelBase >, MooseObjectTagWarehouse< KernelBase >, MooseObjectTagWarehouse< ScalarKernelBase >, MooseObjectTagWarehouse< DGKernelBase >, MooseObjectTagWarehouse< InterfaceKernelBase >, MooseObjectTagWarehouse< IntegratedBCBase >, MooseObjectTagWarehouse< NodalBCBase >, MooseObjectWarehouse< T >, MooseObjectWarehouse< Constraint >, MooseObjectWarehouse< MaterialBase >, MooseObjectWarehouse< AuxScalarKernel >, MooseObjectWarehouse< AuxKernelTempl< Real > >, MooseObjectWarehouse< AuxKernelTempl< RealVectorValue > >, MooseObjectWarehouse< AuxKernelTempl >, MooseObjectWarehouse< DiracKernelBase >, MooseObjectWarehouse< AuxKernelType >, MooseObjectWarehouse< ElementDamper >, MooseObjectWarehouse< Indicator >, MooseObjectWarehouse< InternalSideIndicator >, MooseObjectWarehouse< Marker >, MooseObjectWarehouse< NodalDamper >, MooseObjectWarehouse< NodalKernelBase >, MooseObjectWarehouse< NodalConstraint >, MooseObjectWarehouse< MeshDivision >, MooseObjectWarehouse< Function >, MooseObjectWarehouse< KernelBase >, MooseObjectWarehouse< IntegratedBCBase >, MooseObjectWarehouse< UserObject >, MooseObjectWarehouse< MultiApp >, MooseObjectWarehouse< TransientMultiApp >, MooseObjectWarehouse< Transfer >, MooseObjectWarehouse< Control >, MooseObjectWarehouse< ScalarKernelBase >, MooseObjectWarehouse< DGKernelBase >, MooseObjectWarehouse< InterfaceKernelBase >, MooseObjectWarehouse< NodalBCBase >, MooseObjectWarehouse< DirichletBCBase >, MooseObjectWarehouse< ADDirichletBCBase >, and MooseObjectWarehouse< GeneralDamper >.
Definition at line 545 of file MooseObjectWarehouseBase.h.
{
  checkThreadID(tid);
  updateActiveHelper(_active_objects[tid], _all_objects[tid]);
  for (const auto & object_pair : _all_block_objects[tid])
    updateActiveHelper(_active_block_objects[tid][object_pair.first], object_pair.second);
  for (const auto & object_pair : _all_boundary_objects[tid])
    updateActiveHelper(_active_boundary_objects[tid][object_pair.first], object_pair.second);
}
Referenced by MooseObjectWarehouse< T >::updateActive().
updateActiveHelper()
template<typename T > void MooseObjectWarehouseBase< T >::updateActiveHelper (std::vector< std::shared_ptr< T > > & active, const std::vector< std::shared_ptr< T > > & all) static protected
Helper method for updating active vectors.
Definition at line 560 of file MooseObjectWarehouseBase.h.
{
  // Clear the active list
  active.clear();
  std::copy_if(all.begin(),
               all.end(),
               std::back_inserter(active),
               [](const std::shared_ptr<T> & object) { return object->enabled(); });
}
Referenced by MooseObjectWarehouseBase< T >::updateActive().
updateBlockFEVariableCoupledVectorTagDependency()
template<typename T > void MooseObjectWarehouseBase< T >::updateBlockFEVariableCoupledVectorTagDependency (SubdomainID id, std::set< TagID > & needed_fe_var_vector_tags, THREAD_ID tid = 0) const
Update FE variable coupleable vector tag vector.
Definition at line 653 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBlockObjects(id, tid))
    updateFEVariableCoupledVectorTagDependencyHelper(needed_fe_var_vector_tags,
                                                     getActiveBlockObjects(id, tid));
}
Referenced by ComputeNodalKernelsThread::onNode(), ComputeIndicatorThread::subdomainChanged(), ComputeMaterialsObjectThread::subdomainChanged(), and ComputeUserObjectsThread::subdomainChanged().
updateBlockMatPropDependency()
template<typename T > void MooseObjectWarehouseBase< T >::updateBlockMatPropDependency (SubdomainID id, std::set< unsigned int > & needed_mat_props, THREAD_ID tid = 0) const
Definition at line 698 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBlockObjects(id, tid))
    updateMatPropDependencyHelper(needed_mat_props, getActiveBlockObjects(id, tid));
}
Referenced by FEProblemBase::prepareMaterials().
updateBlockVariableDependency()
template<typename T > void MooseObjectWarehouseBase< T >::updateBlockVariableDependency (SubdomainID id, std::set< MooseVariableFieldBase * > & needed_moose_vars, THREAD_ID tid = 0) const
Definition at line 601 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBlockObjects(id, tid))
    updateVariableDependencyHelper(needed_moose_vars, getActiveBlockObjects(id, tid));
}
updateBoundaryFEVariableCoupledVectorTagDependency()
template<typename T > void MooseObjectWarehouseBase< T >::updateBoundaryFEVariableCoupledVectorTagDependency (BoundaryID id, std::set< TagID > & needed_fe_var_vector_tags, THREAD_ID tid = 0) const
Definition at line 663 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBoundaryObjects(id, tid))
    updateFEVariableCoupledVectorTagDependencyHelper(needed_fe_var_vector_tags,
                                                     getActiveBoundaryObjects(id, tid));
}
Referenced by ComputeNodalKernelBcsThread::onNode().
updateBoundaryMatPropDependency() [1/2]
template<typename T > void MooseObjectWarehouseBase< T >::updateBoundaryMatPropDependency (BoundaryID id, std::set< unsigned int > & needed_mat_props, THREAD_ID tid = 0) const
Definition at line 718 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBoundaryObjects(id, tid))
    updateMatPropDependencyHelper(needed_mat_props, getActiveBoundaryObjects(id, tid));
}
updateBoundaryMatPropDependency() [2/2]
template<typename T > void MooseObjectWarehouseBase< T >::updateBoundaryMatPropDependency (std::set< unsigned int > & needed_mat_props, THREAD_ID tid = 0) const
Definition at line 708 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBoundaryObjects(tid))
    for (auto & active_bnd_object : _active_boundary_objects[tid])
      updateMatPropDependencyHelper(needed_mat_props, active_bnd_object.second);
}
Referenced by FEProblemBase::prepareMaterials().
updateBoundaryVariableDependency() [1/2]
template<typename T > void MooseObjectWarehouseBase< T >::updateBoundaryVariableDependency (BoundaryID id, std::set< MooseVariableFieldBase * > & needed_moose_vars, THREAD_ID tid = 0) const
Definition at line 625 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBoundaryObjects(id, tid))
    updateVariableDependencyHelper(needed_moose_vars, getActiveBoundaryObjects(id, tid));
}
updateBoundaryVariableDependency() [2/2]
template<typename T > void MooseObjectWarehouseBase< T >::updateBoundaryVariableDependency (std::set< MooseVariableFieldBase * > & needed_moose_vars, THREAD_ID tid = 0) const
Definition at line 612 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveBoundaryObjects(tid))
  {
    typename std::map<BoundaryID, std::vector<std::shared_ptr<T>>>::const_iterator it;
    for (const auto & object_pair : _active_boundary_objects[tid])
      updateVariableDependencyHelper(needed_moose_vars, object_pair.second);
  }
}
Referenced by FEProblemBase::prepareMaterials().
updateFEVariableCoupledVectorTagDependencyHelper()
template<typename T > void MooseObjectWarehouseBase< T >::updateFEVariableCoupledVectorTagDependencyHelper (std::set< TagID > & needed_fe_var_vector_tags, const std::vector< std::shared_ptr< T > > & objects) static protected
Helper method for updating FE variable coupleable vector tag vector.
Definition at line 673 of file MooseObjectWarehouseBase.h.
{
  for (const auto & object : objects)
  {
    auto c = dynamic_cast<const Coupleable *>(object.get());
    if (c)
    {
      const auto & tag_deps = c->getFEVariableCoupleableVectorTags();
      needed_fe_var_vector_tags.insert(tag_deps.begin(), tag_deps.end());
    }
  }
}
Referenced by MooseObjectWarehouseBase< T >::updateBlockFEVariableCoupledVectorTagDependency(), and MooseObjectWarehouseBase< T >::updateBoundaryFEVariableCoupledVectorTagDependency().
updateMatPropDependency()
template<typename T > void MooseObjectWarehouseBase< T >::updateMatPropDependency (std::set< unsigned int > & needed_mat_props, THREAD_ID tid = 0) const
Update material property dependency vector.
Definition at line 689 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveObjects(tid))
    updateMatPropDependencyHelper(needed_mat_props, _all_objects[tid]);
}
Referenced by ComputeDiracThread::subdomainChanged(), and ComputeIndicatorThread::subdomainChanged().
updateMatPropDependencyHelper()
template<typename T > void MooseObjectWarehouseBase< T >::updateMatPropDependencyHelper (std::set< unsigned int > & needed_mat_props, const std::vector< std::shared_ptr< T > > & objects) static protected
Helper method for updating material property dependency vector.
Definition at line 727 of file MooseObjectWarehouseBase.h.
{
  for (auto & object : objects)
  {
    auto c = dynamic_cast<const MaterialPropertyInterface *>(object.get());
    if (c)
    {
      auto & mp_deps = c->getMatPropDependencies();
      needed_mat_props.insert(mp_deps.begin(), mp_deps.end());
    }
  }
}
Referenced by MooseObjectWarehouseBase< T >::updateBlockMatPropDependency(), MooseObjectWarehouseBase< T >::updateBoundaryMatPropDependency(), and MooseObjectWarehouseBase< T >::updateMatPropDependency().
updateVariableDependency()
template<typename T > void MooseObjectWarehouseBase< T >::updateVariableDependency (std::set< MooseVariableFieldBase * > & needed_moose_vars, THREAD_ID tid = 0) const
Update variable dependency vector.
Definition at line 592 of file MooseObjectWarehouseBase.h.
{
  if (hasActiveObjects(tid))
    updateVariableDependencyHelper(needed_moose_vars, _all_objects[tid]);
}
Referenced by FEProblemBase::prepareMaterials(), ComputeDiracThread::subdomainChanged(), ComputeIndicatorThread::subdomainChanged(), ComputeMarkerThread::subdomainChanged(), and ComputeMaterialsObjectThread::subdomainChanged().
updateVariableDependencyHelper()
template<typename T > void MooseObjectWarehouseBase< T >::updateVariableDependencyHelper (std::set< MooseVariableFieldBase * > & needed_moose_vars, const std::vector< std::shared_ptr< T > > & objects) static protected
Helper method for updating variable dependency vector.
Definition at line 636 of file MooseObjectWarehouseBase.h.
{
  for (const auto & object : objects)
  {
    auto c = dynamic_cast<const MooseVariableDependencyInterface *>(object.get());
    if (c)
    {
      const auto & mv_deps = c->getMooseVariableDependencies();
      needed_moose_vars.insert(mv_deps.begin(), mv_deps.end());
    }
  }
}
Referenced by MooseObjectWarehouseBase< T >::updateBlockVariableDependency(), MooseObjectWarehouseBase< T >::updateBoundaryVariableDependency(), and MooseObjectWarehouseBase< T >::updateVariableDependency().
Friends And Related Function Documentation
MaterialWarehouse
template<typename T > friend class MaterialWarehouse friend
Definition at line 243 of file MooseObjectWarehouseBase.h.
Member Data Documentation
_active_block_objects
template<typename T > std::vector<std::map<SubdomainID, std::vector<std::shared_ptr<T> > > > MooseObjectWarehouseBase< T >::_active_block_objects protected
Active block restricted objects (THREAD_ID on outer vector)
Definition at line 200 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getActiveBlockObjects(), MooseObjectWarehouseBase< T >::getActiveBlocks(), MooseObjectWarehouseBase< T >::hasActiveBlockObjects(), MooseObjectWarehouseBase< T >::subdomainsCovered(), and MooseObjectWarehouseBase< T >::updateActive().
_active_boundary_objects
template<typename T > std::vector<std::map<BoundaryID, std::vector<std::shared_ptr<T> > > > MooseObjectWarehouseBase< T >::_active_boundary_objects protected
Active boundary restricted objects (THREAD_ID on outer vector)
Definition at line 206 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getActiveBoundaryObjects(), MooseObjectWarehouseBase< T >::hasActiveBoundaryObjects(), MooseObjectWarehouseBase< T >::updateActive(), MooseObjectWarehouseBase< T >::updateBoundaryMatPropDependency(), and MooseObjectWarehouseBase< T >::updateBoundaryVariableDependency().
_active_objects
template<typename T > std::vector<std::vector<std::shared_ptr<T> > > MooseObjectWarehouseBase< T >::_active_objects protected
All active objects (THREAD_ID on outer vector)
Definition at line 194 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::activeObjectsToFormattedString(), MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getActiveObject(), MooseObjectWarehouseBase< T >::getActiveObjects(), MooseObjectWarehouseBase< T >::hasActiveObject(), MooseObjectWarehouseBase< T >::hasActiveObjects(), ConstraintWarehouse::residualEnd(), MooseObjectWarehouseBase< T >::subdomainsCovered(), and MooseObjectWarehouseBase< T >::updateActive().
_all_block_objects
template<typename T > std::vector<std::map<SubdomainID, std::vector<std::shared_ptr<T> > > > MooseObjectWarehouseBase< T >::_all_block_objects protected
Definition at line 197 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getBlockObjects(), MaterialWarehouse::sort(), MooseObjectWarehouseBase< T >::sort(), and MooseObjectWarehouseBase< T >::updateActive().
_all_boundary_objects
template<typename T > std::vector<std::map<BoundaryID, std::vector<std::shared_ptr<T> > > > MooseObjectWarehouseBase< T >::_all_boundary_objects protected
Definition at line 203 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getBoundaryObjects(), MooseObjectWarehouseBase< T >::hasBoundaryObjects(), MaterialWarehouse::sort(), MooseObjectWarehouseBase< T >::sort(), and MooseObjectWarehouseBase< T >::updateActive().
_all_objects
template<typename T > std::vector<std::vector<std::shared_ptr<T> > > MooseObjectWarehouseBase< T >::_all_objects protected
Storage container for the ALL pointers (THREAD_ID on outer vector)
Definition at line 191 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::addObject(), MooseObjectWarehouseBase< T >::getObject(), MooseObjectWarehouseBase< T >::getObjects(), MooseObjectWarehouseBase< T >::hasObjects(), MooseObjectWarehouseBase< T >::size(), MooseObjectWarehouseBase< T >::sort(), MooseObjectWarehouseBase< T >::updateActive(), MooseObjectWarehouseBase< T >::updateMatPropDependency(), and MooseObjectWarehouseBase< T >::updateVariableDependency().
_num_threads
template<typename T > const THREAD_ID MooseObjectWarehouseBase< T >::_num_threads protected
Convenience member storing the number of threads used for storage (1 or libMesh::n_threads)
Definition at line 188 of file MooseObjectWarehouseBase.h.
Referenced by MooseObjectWarehouseBase< T >::checkThreadID(), and MooseObjectWarehouseBase< T >::numThreads().
The documentation for this class was generated from the following file:
moose/framework/include/warehouses/MooseObjectWarehouseBase.h