Zapdos: MooseException Class Reference
MooseException Class Reference
Provides a way for users to bail out of the current solve.
#include <MooseException.h>
Public Member Functions
MooseException (std::string message)
MooseException (const MooseException &)=default
Set an explicit default constructor to avoid the variadic template constructor below catch the copy construction case.
template<typename... Args>
MooseException (Args &&... args)
~MooseException () throw ()
For some reason, on GCC 4.6.3, I get 'error: looser throw specifier' when deriving from std::exception unless I declare that the destructor won't throw by adding the throw() specification.
virtual const char * what () const throw ()
Get out the error message.
Protected Attributes
std::string _message
Detailed Description
Provides a way for users to bail out of the current solve.
Definition at line 20 of file MooseException.h.
Constructor & Destructor Documentation
MooseException() [1/3]
MooseException::MooseException (std::string message) inline
Parameters
message The message to display
Definition at line 26 of file MooseException.h.
: _message(message) {}
MooseException() [2/3]
MooseException::MooseException (const MooseException &) default
Set an explicit default constructor to avoid the variadic template constructor below catch the copy construction case.
MooseException() [3/3]
template<typename... Args> MooseException::MooseException (Args &&... args) inline explicit
Parameters
args List of arguments that gets stringified and concatenated to form the message to display
Definition at line 39 of file MooseException.h.
  {
    std::ostringstream ss;
    streamArguments(ss, args...);
    _message = ss.str();
  }
~MooseException()
MooseException::~MooseException () throw () inline
For some reason, on GCC 4.6.3, I get 'error: looser throw specifier' when deriving from std::exception unless I declare that the destructor won't throw by adding the throw() specification.
Clang doesn't seem to care about this line of code.
Definition at line 53 of file MooseException.h.
{}
Member Function Documentation
what()
virtual const char * MooseException::what () const throw () inline virtual
Get out the error message.
Satisfies the interface of std::exception
Definition at line 60 of file MooseException.h.
{ return _message.c_str(); }
Referenced by ComputeThreadedGeneralUserObjectsThread::caughtMooseException(), ThreadedFaceLoop< RangeType >::caughtMooseException(), ThreadedNodeLoop< RangeType, IteratorType >::caughtMooseException(), ThreadedElementLoop< RangeType >::caughtMooseException(), NonlinearSystemBase::computeDamping(), AuxiliarySystem::computeElementalVarsHelper(), AuxiliarySystem::computeMortarNodalVars(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), FillBetweenCurvesGenerator::generate(), FillBetweenSidesetsGenerator::generate(), XYMeshLineCutter::generate(), FillBetweenPointVectorsTools::isBoundaryOpenSingleSegment(), FillBetweenPointVectorsTools::isCurveOpenSingleSegment(), ThreadedFaceLoop< RangeType >::operator()(), and DisplacedProblem::updateMesh().
Member Data Documentation
_message
std::string MooseException::_message protected
Definition at line 63 of file MooseException.h.
Referenced by MooseException(), and what().
The documentation for this class was generated from the following file:
moose/framework/include/base/MooseException.h