Zapdos: ConsoleStream Class Reference
ConsoleStream Class Reference
A helper class for re-directing output streams to Console output objects form MooseObjects.
#include <ConsoleStream.h>
Public Member Functions
ConsoleStream (OutputWarehouse &output_warehouse)
Constructor.
template<typename StreamType >
const ConsoleStream & operator<< (const StreamType &s) const
The output stream operator.
const ConsoleStream & operator<< (const StandardEndLine &manip) const
This overload is here to handle the the std::endl manipulator.
void unsetf (std::ios_base::fmtflags mask) const
Unset format flags.
std::streampos tellp () const
std::streamsize precision () const
Return the current precision.
std::streamsize precision (std::streamsize new_precision) const
Set the precision and return the old precision.
std::ios_base::fmtflags flags () const
Return the current flags.
std::ios_base::fmtflags flags (std::ios_base::fmtflags new_flags) const
Set the flags and return the old flags.
unsigned long long int numPrinted () const
The number of times something has been printed.
Private Attributes
OutputWarehouse & _output_warehouse
Reference to the OutputWarhouse that contains the Console output objects.
std::shared_ptr< std::ostringstream > _oss
The stream for buffering the message This stupidly has to be a shared pointer because of something in AutomaticMortarGeneration that requires this to be trivially copyable.
Detailed Description
A helper class for re-directing output streams to Console output objects form MooseObjects.
Definition at line 30 of file ConsoleStream.h.
Constructor & Destructor Documentation
ConsoleStream()
ConsoleStream::ConsoleStream (OutputWarehouse & output_warehouse)
Constructor.
Parameters
output_warehouse A reference to the OutputWarehouse containing the Console outputs
ConsoleStreamInterface contains an instance of this object, which allows message streams to be transferred to Console output objects. This class simply provides an operator<< method that passes the stream to the Console objects.
Definition at line 17 of file ConsoleStream.C.
  : _output_warehouse(output_warehouse), _oss(std::make_shared<std::ostringstream>())
{
}
Member Function Documentation
flags() [1/2]
std::ios_base::fmtflags ConsoleStream::flags () const
Return the current flags.
Definition at line 58 of file ConsoleStream.C.
{
  return _oss->flags();
}
Referenced by SystemBase::applyScalingFactors().
flags() [2/2]
std::ios_base::fmtflags ConsoleStream::flags (std::ios_base::fmtflags new_flags) const
Set the flags and return the old flags.
Definition at line 64 of file ConsoleStream.C.
{
  return _oss->flags(new_flags);
}
numPrinted()
unsigned long long int ConsoleStream::numPrinted () const
The number of times something has been printed.
Definition at line 70 of file ConsoleStream.C.
{
  return _output_warehouse.numPrinted();
}
Referenced by PerfGraph::addToExecutionList(), PerfGraphLivePrint::printLiveMessage(), PerfGraphLivePrint::printStats(), and PerfGraphLivePrint::start().
operator<<() [1/2]
const ConsoleStream & ConsoleStream::operator<< (const StandardEndLine & manip) const
This overload is here to handle the the std::endl manipulator.
Definition at line 24 of file ConsoleStream.C.
{
  const std::lock_guard<std::mutex> lock(manip_mutex);
  if (manip == (std::basic_ostream<char> & (*)(std::basic_ostream<char> &)) & std::endl)
    (*_oss) << '\n';
  else
    (*_oss) << manip;
  _output_warehouse.mooseConsole(*_oss);
  return *this;
}
operator<<() [2/2]
template<typename StreamType > const ConsoleStream & ConsoleStream::operator<< (const StreamType & s) const
The output stream operator.
Parameters
s The data to be output to the Console objects
This allows any object to uses _console to write to the Console: _console << "The combination to the air lock is " << 12345 << std::endl;
Definition at line 104 of file ConsoleStream.h.
{
  std::lock_guard<std::mutex> lock(_stream_mutex);
  (*_oss) << s;
  return *this;
}
precision() [1/2]
std::streamsize ConsoleStream::precision () const
Return the current precision.
Definition at line 46 of file ConsoleStream.C.
{
  return _oss->precision();
}
Referenced by SystemBase::applyScalingFactors().
precision() [2/2]
std::streamsize ConsoleStream::precision (std::streamsize new_precision) const
Set the precision and return the old precision.
Definition at line 52 of file ConsoleStream.C.
{
  return _oss->precision(new_precision);
}
tellp()
std::streampos ConsoleStream::tellp () const inline
Definition at line 63 of file ConsoleStream.h.
{ return _oss->tellp(); }
unsetf()
void ConsoleStream::unsetf (std::ios_base::fmtflags mask) const
Unset format flags.
Definition at line 40 of file ConsoleStream.C.
{
  _oss->unsetf(mask);
}
Referenced by SystemBase::applyScalingFactors().
Member Data Documentation
_oss
std::shared_ptr<std::ostringstream> ConsoleStream::_oss mutable private
The stream for buffering the message This stupidly has to be a shared pointer because of something in AutomaticMortarGeneration that requires this to be trivially copyable.
Definition at line 98 of file ConsoleStream.h.
Referenced by flags(), operator<<(), precision(), tellp(), and unsetf().
_output_warehouse
OutputWarehouse& ConsoleStream::_output_warehouse private
Reference to the OutputWarhouse that contains the Console output objects.
Definition at line 92 of file ConsoleStream.h.
Referenced by numPrinted(), and operator<<().
The documentation for this class was generated from the following files:
moose/framework/include/outputs/ConsoleStream.h
moose/framework/src/outputs/ConsoleStream.C