Zapdos: NonlinearEigenSystem Class Reference
NonlinearEigenSystem Class Reference
Nonlinear eigenvalue system to be solved.
#include <NonlinearEigenSystem.h>
Public Member Functions
NonlinearEigenSystem (EigenProblem &problem, const std::string &name)
virtual void solve () override
Solve the system (using libMesh magic)
virtual void stopSolve () override
Quit the current solve as soon as possible.
virtual unsigned int getCurrentNonlinearIterationNumber () override
Returns the current nonlinear iteration number.
virtual void setupFiniteDifferencedPreconditioner () override
virtual bool converged () override
Returns the convergence state.
virtual NumericVector< Number > & RHS () override
NumericVector< Number > & residualVectorAX ()
NumericVector< Number > & residualVectorBX ()
void attachSLEPcCallbacks ()
unsigned int getNumConvergedEigenvalues () const
Get the number of converged eigenvalues.
virtual NonlinearSolver< Number > * nonlinearSolver () override
virtual SNES getSNES () override
Retrieve snes from slepc eigen solver.
virtual EPS getEPS ()
Retrieve EPS (SLEPc eigen solver)
EigenSystem & sys ()
void checkIntegrity ()
For eigenvalue problems (including standard and generalized), inhomogeneous (Dirichlet or Neumann) boundary conditions are not allowed.
std::pair< Real, Real > getConvergedEigenvalue (dof_id_type n) const
Return the Nth converged eigenvalue.
std::pair< Real, Real > getConvergedEigenpair (dof_id_type n) const
Return the Nth converged eigenvalue and copies the respective eigen vector to the solution vector.
const std::vector< std::pair< Real, Real > > & getAllConvergedEigenvalues () const
Get the number of converged eigenvalues.
TagID eigenVectorTag () const
Vector tag ID of right hand side.
TagID nonEigenVectorTag () const
Vector tag ID of left hand side.
TagID eigenMatrixTag () const
Matrix tag ID of right hand side.
TagID nonEigenMatrixTag () const
Matrix tag ID of left hand side.
std::set< TagID > defaultVectorTags () const override
Get the default vector tags associated with this system.
std::set< TagID > defaultMatrixTags () const override
Get the default matrix tags associted with this system.
void precondMatrixIncludesEigenKernels (bool precond_matrix_includes_eigen)
If the preconditioning matrix includes eigen kernels.
bool precondMatrixIncludesEigenKernels () const
TagID precondMatrixTag () const
virtual void attachPreconditioner (Preconditioner< Number > *preconditioner) override
Attach a customized preconditioner that requires physics knowledge.
Preconditioner< Number > * preconditioner () const
virtual void turnOffJacobian () override
Turn off the Jacobian (must be called before equation system initialization)
void residualAndJacobianTogether () override
Call this method if you want the residual and Jacobian to be computed simultaneously.
NonlinearEigenSystem (EigenProblem &problem, const std::string &name)
bool converged ()
Returns the convergence state.
void checkIntegrity ()
virtual void init () override
Initialize the system.
bool computedScalingJacobian () const
virtual void restoreSolutions () override
Restore current solutions (call after your solve failed)
virtual bool computingInitialResidual ()
Returns true if this system is currently computing the initial residual for a solve.
virtual void initialSetup () override
Setup Functions.
virtual void timestepSetup () override
virtual void customSetup (const ExecFlagType &exec_type) override
virtual void residualSetup () override
virtual void jacobianSetup () override
void setupFieldDecomposition ()
bool haveFiniteDifferencedPreconditioner () const
bool haveFieldSplitPreconditioner () const
void addTimeIntegrator (const std::string &type, const std::string &name, InputParameters &parameters) override
Add a time integrator.
virtual void addTimeIntegrator (const std::string &, const std::string &, InputParameters &)
virtual void addTimeIntegrator (std::shared_ptr< TimeIntegrator >)
void addDotVectors ()
Add u_dot, u_dotdot, u_dot_old and u_dotdot_old vectors if requested by the time integrator.
virtual void addKernel (const std::string &kernel_name, const std::string &name, InputParameters &parameters)
Adds a kernel.
virtual void addNodalKernel (const std::string &kernel_name, const std::string &name, InputParameters &parameters)
Adds a NodalKernel.
void addScalarKernel (const std::string &kernel_name, const std::string &name, InputParameters &parameters)
Adds a scalar kernel.
void addBoundaryCondition (const std::string &bc_name, const std::string &name, InputParameters &parameters)
Adds a boundary condition.
void addConstraint (const std::string &c_name, const std::string &name, InputParameters &parameters)
Adds a Constraint.
void addDiracKernel (const std::string &kernel_name, const std::string &name, InputParameters &parameters)
Adds a Dirac kernel.
void addDGKernel (std::string dg_kernel_name, const std::string &name, InputParameters &parameters)
Adds a DG kernel.
void addInterfaceKernel (std::string interface_kernel_name, const std::string &name, InputParameters &parameters)
Adds an interface kernel.
void addDamper (const std::string &damper_name, const std::string &name, InputParameters &parameters)
Adds a damper.
void addSplit (const std::string &split_name, const std::string &name, InputParameters &parameters)
Adds a split.
std::shared_ptr< Split > getSplit (const std::string &name)
Retrieves a split by name.
void zeroVectorForResidual (const std::string &vector_name)
void setInitialSolution ()
void setConstraintSecondaryValues (NumericVector< Number > &solution, bool displaced)
Sets the value of constrained variables in the solution vector.
void constraintResiduals (NumericVector< Number > &residual, bool displaced)
Add residual contributions from Constraints.
void computeResidualTag (NumericVector< Number > &residual, TagID tag_id)
Computes residual for a given tag.
void computeResidualTags (const std::set< TagID > &tags)
Form multiple tag-associated residual vectors for all the given tags.
void computeResidualAndJacobianTags (const std::set< TagID > &vector_tags, const std::set< TagID > &matrix_tags)
Form possibly multiple tag-associated vectors and matrices.
void computeResidualAndJacobianInternal (const std::set< TagID > &vector_tags, const std::set< TagID > &matrix_tags)
Compute residual and Jacobian from contributions not related to constraints, such as nodal boundary conditions.
void computeResidual (NumericVector< Number > &residual, TagID tag_id)
Form a residual vector for a given tag.
void addImplicitGeometricCouplingEntries (GeometricSearchData &geom_search_data)
Adds entries to the Jacobian in the correct positions for couplings coming from dofs being coupled that are related geometrically (i.e.
void constraintJacobians (bool displaced)
Add jacobian contributions from Constraints.
void computeJacobianTags (const std::set< TagID > &tags)
Computes multiple (tag associated) Jacobian matricese.
void computeScaling ()
Method used to obtain scaling factors for variables.
void computeJacobian (SparseMatrix< Number > &jacobian, const std::set< TagID > &tags)
Associate jacobian to systemMatrixTag, and then form a matrix for all the tags.
void computeJacobian (SparseMatrix< Number > &jacobian)
Take all tags in the system, and form a matrix for all tags in the system.
void computeJacobianBlocks (std::vector< JacobianBlock * > &blocks)
Computes several Jacobian blocks simultaneously, summing their contributions into smaller preconditioning matrices.
void computeJacobianBlocks (std::vector< JacobianBlock * > &blocks, const std::set< TagID > &tags)
Real computeDamping (const NumericVector< Number > &solution, const NumericVector< Number > &update)
Compute damping.
void computeTimeDerivatives (bool jacobian_calculation=false)
Computes the time derivative vector.
void onTimestepBegin ()
Called at the beginning of the time step.
virtual void subdomainSetup (SubdomainID subdomain, THREAD_ID tid)
Called from assembling when we hit a new subdomain.
virtual void subdomainSetup ()
virtual void setSolution (const NumericVector< Number > &soln)
void updateActive (THREAD_ID tid)
Update active objects of Warehouses owned by NonlinearSystemBase.
virtual void setSolutionUDot (const NumericVector< Number > &udot)
Set transient term used by residual and Jacobian evaluation.
virtual void setSolutionUDotDot (const NumericVector< Number > &udotdot)
Set transient term used by residual and Jacobian evaluation.
NumericVector< Number > * solutionUDot () override
const NumericVector< Number > * solutionUDot () const override
NumericVector< Number > * solutionUDotDot () override
const NumericVector< Number > * solutionUDotDot () const override
NumericVector< Number > * solutionUDotOld () override
const NumericVector< Number > * solutionUDotOld () const override
NumericVector< Number > * solutionUDotDotOld () override
const NumericVector< Number > * solutionUDotDotOld () const override
NumericVector< Number > & getResidualTimeVector ()
Return a numeric vector that is associated with the time tag.
NumericVector< Number > & getResidualNonTimeVector ()
Return a numeric vector that is associated with the nontime tag.
NumericVector< Number > & residualVector (TagID tag)
Return a residual vector that is associated with the residual tag.
const NumericVector< Number > *const & currentSolution () const override
The solution vector that is currently being operated on.
virtual void serializeSolution ()
virtual NumericVector< Number > & serializedSolution () override
Returns a reference to a serialized version of the solution vector for this subproblem.
virtual NumericVector< Number > & residualCopy () override
virtual NumericVector< Number > & residualGhosted () override
virtual void augmentSparsity (SparsityPattern::Graph &sparsity, std::vector< dof_id_type > &n_nz, std::vector< dof_id_type > &n_oz) override
Will modify the sparsity pattern to add logical geometric connections.
void setPreconditioner (std::shared_ptr< MoosePreconditioner > pc)
Sets a preconditioner.
MoosePreconditioner const * getPreconditioner () const
void useFiniteDifferencedPreconditioner (bool use=true)
If called with true this system will use a finite differenced form of the Jacobian as the preconditioner.
void setDecomposition (const std::vector< std::string > &decomposition)
If called with a single string, it is used as the name of a the top-level decomposition split.
void useFieldSplitPreconditioner (bool use=true)
If called with true this system will use a field split preconditioner matrix.
void addImplicitGeometricCouplingEntriesToJacobian (bool add=true)
If called with true this will add entries into the jacobian to link together degrees of freedom that are found to be related through the geometric search system.
void assembleConstraintsSeparately (bool separately=true)
Indicates whether to assemble residual and Jacobian after each constraint application.
void setupDampers ()
Setup damping stuff (called before we actually start)
void reinitIncrementAtQpsForDampers (THREAD_ID tid, const std::set< MooseVariable * > &damped_vars)
Compute the incremental change in variables at QPs for dampers.
void reinitIncrementAtNodeForDampers (THREAD_ID tid, const std::set< MooseVariable * > &damped_vars)
Compute the incremental change in variables at nodes for dampers.
unsigned int nNonlinearIterations () const
Return the number of non-linear iterations.
unsigned int nLinearIterations () const
Return the number of linear iterations.
unsigned int nResidualEvaluations () const
Return the total number of residual evaluations done so far in this calculation.
Real finalNonlinearResidual () const
Return the final nonlinear residual.
Real nonlinearNorm () const
Return the last nonlinear norm.
void printAllVariableNorms (bool state)
Force the printing of all variable norms after each solve.
void debuggingResiduals (bool state)
void setPredictor (std::shared_ptr< Predictor > predictor)
Predictor * getPredictor ()
void setPCSide (MooseEnum pcs)
Moose::PCSideType getPCSide ()
void setMooseKSPNormType (MooseEnum kspnorm)
Moose::MooseKSPNormType getMooseKSPNormType ()
bool needBoundaryMaterialOnSide (BoundaryID bnd_id, THREAD_ID tid) const
Indicated whether this system needs material properties on boundaries.
bool needInterfaceMaterialOnSide (BoundaryID bnd_id, THREAD_ID tid) const
Indicated whether this system needs material properties on interfaces.
bool needSubdomainMaterialOnSide (SubdomainID subdomain_id, THREAD_ID tid) const
Indicates whether this system needs material properties on internal sides.
bool doingDG () const
Getter for _doing_dg.
MooseObjectTagWarehouse< KernelBase > & getKernelWarehouse ()
Access functions to Warehouses from outside NonlinearSystemBase.
MooseObjectTagWarehouse< DGKernelBase > & getDGKernelWarehouse ()
MooseObjectTagWarehouse< InterfaceKernelBase > & getInterfaceKernelWarehouse ()
MooseObjectTagWarehouse< DiracKernelBase > & getDiracKernelWarehouse ()
MooseObjectTagWarehouse< IntegratedBCBase > & getIntegratedBCWarehouse ()
const MooseObjectTagWarehouse< IntegratedBCBase > & getIntegratedBCWarehouse () const
Return the IntegratedBCBase warehouse.
const MooseObjectWarehouse< ElementDamper > & getElementDamperWarehouse () const
const MooseObjectWarehouse< NodalDamper > & getNodalDamperWarehouse () const
const ConstraintWarehouse & getConstraintWarehouse () const
const MooseObjectTagWarehouse< NodalBCBase > & getNodalBCWarehouse () const
Return the NodalBCBase warehouse.
bool hasSaveIn () const
Weather or not the nonlinear system has save-ins.
bool hasDiagSaveIn () const
Weather or not the nonlinear system has diagonal Jacobian save-ins.
virtual System & system () override
Get the reference to the libMesh system.
virtual const System & system () const override
virtual void setSolutionUDotOld (const NumericVector< Number > &u_dot_old)
virtual void setSolutionUDotDotOld (const NumericVector< Number > &u_dotdot_old)
virtual void setPreviousNewtonSolution (const NumericVector< Number > &soln)
TagID timeVectorTag () const override
Ideally, we should not need this API.
TagID nonTimeVectorTag () const override
TagID residualVectorTag () const override
TagID systemMatrixTag () const override
Return the Matrix Tag ID for System.
bool computeScalingOnce () const
void computeScalingOnce (bool compute_scaling_once)
void autoScalingParam (Real resid_vs_jac_scaling_param)
Sets the param that indicates the weighting of the residual vs the Jacobian in determining variable scaling parameters.
void scalingGroupVariables (const std::vector< std::vector< std::string > > &scaling_group_variables)
void ignoreVariablesForAutoscaling (const std::vector< std::string > &ignore_variables_for_autoscaling)
bool offDiagonalsInAutoScaling () const
void offDiagonalsInAutoScaling (bool off_diagonals_in_auto_scaling)
unsigned int number () const
Gets the number of this system.
virtual MooseMesh & mesh ()
virtual const MooseMesh & mesh () const
virtual SubProblem & subproblem ()
virtual const SubProblem & subproblem () const
void applyScalingFactors (const std::vector< Real > &inverse_scaling_factors)
Applies scaling factors to the system's variables.
bool computingScalingJacobian () const
Whether we are computing an initial Jacobian for automatic variable scaling.
bool automaticScaling () const
Getter for whether we are performing automatic scaling.
void automaticScaling (bool automatic_scaling)
Setter for whether we are performing automatic scaling.
void setVerboseFlag (const bool &verbose)
Sets the verbose flag.
virtual DofMap & dofMap ()
Gets writeable reference to the dof map.
virtual const DofMap & dofMap () const
Gets const reference to the dof map.
virtual void initializeObjects ()
Called only once, just before the solve begins so objects can do some precalculations.
virtual void update (bool update_libmesh_system=true)
Update the system (doing libMesh magic)
virtual void copyOldSolutions ()
Shifts the solutions backwards in time.
NumericVector< Number > & solution ()
const NumericVector< Number > & solution () const
NumericVector< Number > & solutionOld ()
const NumericVector< Number > & solutionOld () const
NumericVector< Number > & solutionOlder ()
const NumericVector< Number > & solutionOlder () const
virtual const NumericVector< Number > * solutionPreviousNewton () const
virtual NumericVector< Number > * solutionPreviousNewton ()
virtual void initSolutionState ()
Initializes the solution state.
virtual NumericVector< Number > & solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time)
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
virtual const NumericVector< Number > & solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time) const
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
virtual void needSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time)
Registers that the solution state state is needed.
virtual bool hasSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type=Moose::SolutionIterationType::Time) const
Whether or not the system has the solution state (0 = current, 1 = old, 2 = older, etc).
virtual Number & duDotDu ()
virtual const Number & duDotDu () const
virtual Number & duDotDotDu ()
virtual const Number & duDotDotDu () const
virtual void saveOldSolutions ()
Save the old and older solutions.
virtual void restoreOldSolutions ()
Restore the old and older solutions when the saved solutions present.
bool hasVector (const std::string &tag_name) const
Check if the named vector exists in the system.
virtual bool hasVector (TagID tag_id) const
Check if the tagged vector exists in the system.
virtual void associateVectorToTag (NumericVector< Number > &vec, TagID tag)
Associate a vector for a given tag.
virtual void disassociateVectorFromTag (NumericVector< Number > &vec, TagID tag)
Disassociate a given vector from a given tag.
virtual void disassociateVectorFromTag (TagID tag)
Disassociate any vector that is associated with a given tag.
virtual void disassociateDefaultVectorTags ()
Disassociate the vectors associated with the default vector tags of this system.
virtual bool hasMatrix (TagID tag) const
Check if the tagged matrix exists in the system.
virtual SparseMatrix< Number > & getMatrix (TagID tag)
Get a raw SparseMatrix.
virtual const SparseMatrix< Number > & getMatrix (TagID tag) const
Get a raw SparseMatrix.
virtual void activeAllMatrixTags ()
Make all exsiting matrices ative.
virtual void activeMatrixTag (TagID tag)
Active a matrix for tag.
virtual bool matrixTagActive (TagID tag) const
If or not a matrix tag is active.
virtual void deactiveMatrixTag (TagID tag)
deactive a matrix for tag
virtual void deactiveAllMatrixTags ()
Make matrices inactive.
void closeTaggedMatrices (const std::set< TagID > &tags)
Close all matrices associated the tags.
void flushTaggedMatrices (const std::set< TagID > &tags)
flushes all matrices associated to tags.
virtual void associateMatrixToTag (SparseMatrix< Number > &matrix, TagID tag)
Associate a matrix to a tag.
virtual void disassociateMatrixFromTag (SparseMatrix< Number > &matrix, TagID tag)
Disassociate a matrix from a tag.
virtual void disassociateMatrixFromTag (TagID tag)
Disassociate any matrix that is associated with a given tag.
virtual void disassociateDefaultMatrixTags ()
Disassociate the matrices associated with the default matrix tags of this system.
virtual void augmentSendList (std::vector< dof_id_type > &send_list)
Will modify the send_list to add all of the extra ghosted dofs for this system.
virtual void addVariable (const std::string &var_type, const std::string &var_name, InputParameters &parameters)
Canonical method for adding a variable.
virtual bool isArrayVariable (const std::string &var_name) const
If a variable is an array variable.
virtual bool isScalarVariable (unsigned int var_name) const
MooseVariableFieldBase & getVariable (THREAD_ID tid, const std::string &var_name) const
Gets a reference to a variable of with specified name.
MooseVariableFieldBase & getVariable (THREAD_ID tid, unsigned int var_number) const
Gets a reference to a variable with specified number.
template<typename T >
MooseVariableFE< T > & getFieldVariable (THREAD_ID tid, const std::string &var_name)
Gets a reference to a variable of with specified name.
template<typename T >
MooseVariableFE< T > & getFieldVariable (THREAD_ID tid, unsigned int var_number)
Gets a reference to a variable with specified number.
template<typename T >
MooseVariableField< T > & getActualFieldVariable (THREAD_ID tid, const std::string &var_name)
Returns a field variable pointer - this includes finite volume variables.
template<typename T >
MooseVariableField< T > & getActualFieldVariable (THREAD_ID tid, unsigned int var_number)
Returns a field variable pointer - this includes finite volume variables.
template<typename T >
MooseVariableFV< T > & getFVVariable (THREAD_ID tid, const std::string &var_name)
Return a finite volume variable.
virtual MooseVariableScalar & getScalarVariable (THREAD_ID tid, const std::string &var_name) const
Gets a reference to a scalar variable with specified number.
virtual MooseVariableScalar & getScalarVariable (THREAD_ID tid, unsigned int var_number) const
Gets a reference to a variable with specified number.
virtual const std::set< SubdomainID > * getVariableBlocks (unsigned int var_number)
Get the block where a variable of this system is defined.
virtual unsigned int nVariables () const
Get the number of variables in this system.
unsigned int nFieldVariables () const
Get the number of field variables in this system.
unsigned int nFVVariables () const
Get the number of finite volume variables in this system.
std::size_t getMaxVarNDofsPerElem () const
Gets the maximum number of dofs used by any one variable on any one element.
std::size_t getMaxVarNDofsPerNode () const
Gets the maximum number of dofs used by any one variable on any one node.
void assignMaxVarNDofsPerElem (std::size_t max_dofs)
assign the maximum element dofs
void assignMaxVarNDofsPerNode (std::size_t max_dofs)
assign the maximum node dofs
virtual void addVariableToZeroOnResidual (std::string var_name)
Adds this variable to the list of variables to be zeroed during each residual evaluation.
virtual void addVariableToZeroOnJacobian (std::string var_name)
Adds this variable to the list of variables to be zeroed during each Jacobian evaluation.
virtual void zeroVariables (std::vector< std::string > &vars_to_be_zeroed)
Zero out the solution for the list of variables passed in.
virtual void zeroVariablesForResidual ()
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on residual evaluation by a call to addVariableToZeroOnResidual()
virtual void zeroVariablesForJacobian ()
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on Jacobian evaluation by a call to addVariableToZeroOnResidual()
virtual Order getMinQuadratureOrder ()
Get minimal quadrature order needed for integrating variables in this system.
virtual void prepare (THREAD_ID tid)
Prepare the system for use.
virtual void prepareFace (THREAD_ID tid, bool resize_data)
Prepare the system for use on sides.
virtual void prepareNeighbor (THREAD_ID tid)
Prepare the system for use.
virtual void prepareLowerD (THREAD_ID tid)
Prepare the system for use for lower dimensional elements.
virtual void reinitElem (const Elem *elem, THREAD_ID tid)
Reinit an element assembly info.
virtual void reinitElemFace (const Elem *elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid)
Reinit assembly info for a side of an element.
virtual void reinitNeighborFace (const Elem *elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid)
Compute the values of the variables at all the current points.
virtual void reinitNeighbor (const Elem *elem, THREAD_ID tid)
Compute the values of the variables at all the current points.
virtual void reinitLowerD (THREAD_ID tid)
Compute the values of the variables on the lower dimensional element.
virtual void reinitNode (const Node *node, THREAD_ID tid)
Reinit nodal assembly info.
virtual void reinitNodeFace (const Node *node, BoundaryID bnd_id, THREAD_ID tid)
Reinit nodal assembly info on a face.
virtual void reinitNodes (const std::vector< dof_id_type > &nodes, THREAD_ID tid)
Reinit variables at a set of nodes.
virtual void reinitNodesNeighbor (const std::vector< dof_id_type > &nodes, THREAD_ID tid)
Reinit variables at a set of neighbor nodes.
virtual void reinitScalars (THREAD_ID tid, bool reinit_for_derivative_reordering=false)
Reinit scalar varaibles.
virtual void addVariableToCopy (const std::string &dest_name, const std::string &source_name, const std::string &timestep)
Add info about variable that will be copied.
const std::vector< MooseVariableFieldBase * > & getVariables (THREAD_ID tid)
const std::vector< MooseVariableScalar * > & getScalarVariables (THREAD_ID tid)
const std::set< SubdomainID > & getSubdomainsForVar (unsigned int var_number) const
const std::set< SubdomainID > & getSubdomainsForVar (const std::string &var_name) const
Get the block where a variable of this system is defined.
void removeVector (const std::string &name)
Remove a vector from the system with the given name.
void removeVector (TagID tag_id)
Remove a solution length vector from the system with the specified TagID.
NumericVector< Number > & addVector (const std::string &vector_name, const bool project, const ParallelType type)
Adds a solution length vector to the system.
NumericVector< Number > & addVector (TagID tag, const bool project, const ParallelType type)
Adds a solution length vector to the system with the specified TagID.
void closeTaggedVector (const TagID tag)
Close vector with the given tag.
void closeTaggedVectors (const std::set< TagID > &tags)
Close all vectors for given tags.
void zeroTaggedVector (const TagID tag)
Zero vector with the given tag.
void zeroTaggedVectors (const std::set< TagID > &tags)
Zero all vectors for given tags.
void setVariableGlobalDoFs (const std::string &var_name)
set all the global dof indices for a variable
const std::vector< dof_id_type > & getVariableGlobalDoFs ()
Get the global dof indices of a variable, this needs to be called after the indices have been set by setVariableGlobalDoFs
SparseMatrix< Number > & addMatrix (TagID tag)
Adds a matrix with a given tag.
void removeMatrix (TagID tag)
Removes a matrix with a given tag.
virtual const std::string & name () const
const std::vector< VariableName > & getVariableNames () const
void getStandardFieldVariableNames (std::vector< VariableName > &std_field_variables) const
unsigned int getMaxVariableNumber () const
Returns the maximum number of all variables on the system.
virtual void computeVariables (const NumericVector< Number > &)
void copyVars (ExodusII_IO &io)
virtual void copySolutionsBackwards ()
Copy current solution into old and older.
TimeIntegrator * getTimeIntegrator ()
const TimeIntegrator * getTimeIntegrator () const
std::shared_ptr< TimeIntegrator > getSharedTimeIntegrator ()
bool hasVarCopy () const
Whether or not there are variables to be restarted from an Exodus mesh file.
void addScalingVector ()
Add the scaling factor vector to the system.
bool solutionStatesInitialized () const
Whether or not the solution states have been initialized via initSolutionState()
void clearAllDofIndices ()
Clear all dof indices from moose variables.
void setActiveVariableCoupleableVectorTags (const std::set< TagID > &vtags, THREAD_ID tid)
Set the active vector tags for the variables.
void setActiveScalarVariableCoupleableVectorTags (const std::set< TagID > &vtags, THREAD_ID tid)
Set the active vector tags for the scalar variables.
Moose::VarKindType varKind () const
PerfGraph & perfGraph ()
Get the PerfGraph.
void checkKernelCoverage (const std::set< SubdomainID > &mesh_subdomains) const
bool containsTimeKernel ()
virtual NumericVector< Number > & getVector (const std::string &name)
Get a raw NumericVector by name.
virtual const NumericVector< Number > & getVector (const std::string &name) const
virtual NumericVector< Number > & getVector (TagID tag)
Get a raw NumericVector by tag.
virtual const NumericVector< Number > & getVector (TagID tag) const
virtual bool hasVariable (const std::string &var_name) const
Query a system for a variable.
virtual bool hasScalarVariable (const std::string &var_name) const
Static Public Member Functions
static InputParameters validParams ()
Public Attributes
unsigned int _num_residual_evaluations
FEProblemBase & _fe_problem
System & _sys
Real _last_nl_rnorm
Real _initial_residual_before_preset_bcs
Real _initial_residual_after_preset_bcs
std::vector< unsigned int > _current_l_its
unsigned int _current_nl_its
bool _compute_initial_residual_before_preset_bcs
const ConsoleStream _console
An instance of helper class to write streams to the Console objects.
Protected Member Functions
virtual void postAddResidualObject (ResidualObject &object) override
Called after any ResidualObject-derived objects are added to the system.
void computeScalingJacobian () override
Compute a "Jacobian" for automatic scaling purposes.
void computeScalingResidual () override
Compute a "residual" for automatic scaling purposes.
void computeResidualInternal (const std::set< TagID > &tags)
Compute the residual for a given tag.
void computeNodalBCs (NumericVector< Number > &residual)
Enforces nodal boundary conditions.
void computeNodalBCs (NumericVector< Number > &residual, const std::set< TagID > &tags)
Form a residual for BCs that at least has one of the given tags.
void computeNodalBCs (const std::set< TagID > &tags)
Form multiple tag-associated residual vectors for the given tags.
void computeNodalBCsResidualAndJacobian ()
compute the residual and Jacobian for nodal boundary conditions
void computeJacobianInternal (const std::set< TagID > &tags)
Form multiple matrices for all the tags.
void computeDiracContributions (const std::set< TagID > &tags, bool is_jacobian)
void computeScalarKernelsJacobians (const std::set< TagID > &tags)
void enforceNodalConstraintsResidual (NumericVector< Number > &residual)
Enforce nodal constraints.
void enforceNodalConstraintsJacobian ()
void mortarConstraints (Moose::ComputeType compute_type, const std::set< TagID > &vector_tags, const std::set< TagID > &matrix_tags)
Do mortar constraint residual/jacobian computations.
void assembleScalingVector ()
Assemble the numeric vector of scaling factors such that it can be used during assembly of the system matrix.
NumericVector< Number > & solutionInternal () const override
Internal getter for solution owned by libMesh.
void getNodeDofs (dof_id_type node_id, std::vector< dof_id_type > &dofs)
PerfID registerTimedSection (const std::string &section_name, const unsigned int level) const
Call to register a named section for timing.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level, const std::string &live_message, const bool print_dots=true) const
Call to register a named section for timing.
std::string timedSectionName (const std::string &section_name) const
Protected Attributes
EigenSystem & _eigen_sys
EigenProblem & _eigen_problem
std::unique_ptr< SlepcEigenSolverConfiguration > _solver_configuration
std::vector< std::pair< Real, Real > > _eigen_values
unsigned int _n_eigen_pairs_required
NumericVector< Number > & _work_rhs_vector_AX
NumericVector< Number > & _work_rhs_vector_BX
TagID _Ax_tag
TagID _Bx_tag
TagID _A_tag
TagID _B_tag
TagID _precond_tag
bool _precond_matrix_includes_eigen
Preconditioner< Number > * _preconditioner
const NumericVector< Number > * _current_solution
solution vector from nonlinear solver
NumericVector< Number > * _residual_ghosted
ghosted form of the residual
std::unique_ptr< NumericVector< Number > > _serialized_solution
Serialized version of the solution vector, or nullptr if a serialized solution is not needed.
std::unique_ptr< NumericVector< Number > > _residual_copy
Copy of the residual vector, or nullptr if a copy is not needed.
NumericVector< Number > * _u_dot
solution vector for u^dot
NumericVector< Number > * _u_dotdot
solution vector for u^dotdot
NumericVector< Number > * _u_dot_old
old solution vector for u^dot
NumericVector< Number > * _u_dotdot_old
old solution vector for u^dotdot
Number _du_dot_du
\({du^dot}\over{du} \)
Number _du_dotdot_du
\({du^dotdot}\over{du} \)
TagID _Re_time_tag
Tag for time contribution residual.
std::set< TagID > _nl_vector_tags
Vector tags to temporarily store all tags associated with the current system.
std::set< TagID > _nl_matrix_tags
Matrix tags to temporarily store all tags associated with the current system.
NumericVector< Number > * _Re_time
residual vector for time contributions
TagID _Re_non_time_tag
Tag for non-time contribution residual.
NumericVector< Number > * _Re_non_time
residual vector for non-time contributions
TagID _Re_tag
Used for the residual vector from PETSc.
TagID _Ke_non_time_tag
Tag for non-time contribution Jacobian.
TagID _Ke_system_tag
Tag for system contribution Jacobian.
MooseObjectTagWarehouse< DiracKernelBase > _dirac_kernels
Dirac Kernel storage for each thread.
MooseObjectWarehouse< ElementDamper > _element_dampers
Element Dampers for each thread.
MooseObjectWarehouse< NodalDamper > _nodal_dampers
Nodal Dampers for each thread.
MooseObjectWarehouse< GeneralDamper > _general_dampers
General Dampers.
MooseObjectTagWarehouse< NodalKernelBase > _nodal_kernels
NodalKernels for each thread.
MooseObjectWarehouseBase< Split > _splits
Decomposition splits.
ConstraintWarehouse _constraints
Constraints storage object.
NumericVector< Number > * _increment_vec
increment vector
Moose::PCSideType _pc_side
Preconditioning side.
Moose::MooseKSPNormType _ksp_norm
KSP norm type.
bool _use_finite_differenced_preconditioner
Whether or not to use a finite differenced preconditioner.
MatFDColoring _fdcoloring
bool _have_decomposition
Whether or not the system can be decomposed into splits.
std::string _decomposition_split
Name of the top-level split of the decomposition.
bool _use_field_split_preconditioner
Whether or not to use a FieldSplitPreconditioner matrix based on the decomposition.
bool _add_implicit_geometric_coupling_entries_to_jacobian
Whether or not to add implicit geometric couplings to the Jacobian for FDP.
bool _assemble_constraints_separately
Whether or not to assemble the residual and Jacobian after the application of each constraint.
bool _need_residual_ghosted
Whether or not a ghosted copy of the residual needs to be made.
bool _debugging_residuals
true if debugging residuals
bool _doing_dg
true if DG is active (optimization reasons)
std::vector< std::string > _vecs_to_zero_for_residual
vectors that will be zeroed before a residual computation
unsigned int _n_iters
unsigned int _n_linear_iters
unsigned int _n_residual_evaluations
Total number of residual evaluations that have been performed.
Real _final_residual
std::shared_ptr< Predictor > _predictor
If predictor is active, this is non-NULL.
bool _computing_initial_residual
bool _print_all_var_norms
bool _has_save_in
If there is any Kernel or IntegratedBC having save_in.
bool _has_diag_save_in
If there is any Kernel or IntegratedBC having diag_save_in.
bool _has_nodalbc_save_in
If there is a nodal BC having save_in.
bool _has_nodalbc_diag_save_in
If there is a nodal BC having diag_save_in.
bool _computed_scaling
Flag used to indicate whether we have already computed the scaling Jacobian.
bool _compute_scaling_once
Whether the scaling factors should only be computed once at the beginning of the simulation through an extra Jacobian evaluation.
Real _resid_vs_jac_scaling_param
The param that indicates the weighting of the residual vs the Jacobian in determining variable scaling parameters.
std::vector< std::vector< std::string > > _scaling_group_variables
A container of variable groupings that can be used in scaling calculations.
std::vector< bool > _variable_autoscaled
Container to hold flag if variable is to participate in autoscaling.
std::vector< std::string > _ignore_variables_for_autoscaling
A container for variables that do not partipate in autoscaling.
bool _off_diagonals_in_auto_scaling
Whether to include off diagonals when determining automatic scaling factors.
std::unique_ptr< DiagonalMatrix< Number > > _scaling_matrix
A diagonal matrix used for computing scaling.
SubProblem & _subproblem
MooseApp & _app
Factory & _factory
MooseMesh & _mesh
std::string _name
The name of this system.
std::vector< VariableWarehouse > _vars
Variable warehouses (one for each thread)
std::map< unsigned int, std::set< SubdomainID > > _var_map
Map of variables (variable id -> array of subdomains where it lives)
unsigned int _max_var_number
Maximum variable number.
std::vector< std::string > _vars_to_be_zeroed_on_residual
std::vector< std::string > _vars_to_be_zeroed_on_jacobian
std::vector< NumericVector< Number > * > _tagged_vectors
Tagged vectors (pointer)
std::vector< SparseMatrix< Number > * > _tagged_matrices
Tagged matrices (pointer)
std::vector< bool > _matrix_tag_active_flags
Active flags for tagged matrices.
NumericVector< Real > * _saved_old
NumericVector< Real > * _saved_older
NumericVector< Real > * _saved_dot_old
NumericVector< Real > * _saved_dotdot_old
Moose::VarKindType _var_kind
default kind of variables in this system
std::vector< VarCopyInfo > _var_to_copy
size_t _max_var_n_dofs_per_elem
Maximum number of dofs for any one variable on any one element.
size_t _max_var_n_dofs_per_node
Maximum number of dofs for any one variable on any one node.
std::shared_ptr< TimeIntegrator > _time_integrator
Time integrator.
std::vector< std::vector< MooseVariableFieldBase * > > _numbered_vars
Map variable number to its pointer.
bool _automatic_scaling
Whether to automatically scale the variables.
bool _verbose
True if printing out additional information.
bool _solution_states_initialized
Whether or not the solution states have been initialized.
std::vector< dof_id_type > _var_all_dof_indices
Container for the dof indices of a given variable.
MooseApp & _pg_moose_app
The MooseApp that owns the PerfGraph.
const std::string _prefix
A prefix to use for all sections.
MooseObjectTagWarehouse< KernelBase > _kernels
MooseObjectTagWarehouse< ScalarKernelBase > _scalar_kernels
MooseObjectTagWarehouse< DGKernelBase > _dg_kernels
MooseObjectTagWarehouse< InterfaceKernelBase > _interface_kernels
MooseObjectTagWarehouse< IntegratedBCBase > _integrated_bcs
MooseObjectTagWarehouse< NodalBCBase > _nodal_bcs
MooseObjectWarehouse< DirichletBCBase > _preset_nodal_bcs
MooseObjectWarehouse< ADDirichletBCBase > _ad_preset_nodal_bcs
Private Member Functions
void findImplicitGeometricCouplingEntries (GeometricSearchData &geom_search_data, std::unordered_map< dof_id_type, std::vector< dof_id_type > > &graph)
Finds the implicit sparsity graph between geometrically related dofs.
void setupScalingData ()
Setup group scaling containers.
TagName oldSolutionStateVectorName (const unsigned int, Moose::SolutionIterationType iteration_type) const
Gets the vector name used for an old (not current) solution state.
Private Attributes
std::unordered_map< std::pair< BoundaryID, BoundaryID >, ComputeMortarFunctor > _undisplaced_mortar_functors
Functors for computing undisplaced mortar constraints.
std::unordered_map< std::pair< BoundaryID, BoundaryID >, ComputeMortarFunctor > _displaced_mortar_functors
Functors for computing displaced mortar constraints.
std::vector< NumericVector< Number > * > _solution_state
The current states of the solution (0 = current, 1 = old, etc)
bool _auto_scaling_initd
Whether we've initialized the automatic scaling data structures.
std::unordered_map< unsigned int, unsigned int > _var_to_group_var
A map from variable index to group variable index and it's associated (inverse) scaling factor.
std::size_t _num_scaling_groups
The number of scaling groups.
std::array< std::vector< NumericVector< Number > * >, 2 > _solution_states
The solution states (0 = current, 1 = old, 2 = older, etc)
std::vector< NumericVector< Number > * > _saved_solution_states
The saved solution states (0 = current, 1 = old, 2 = older, etc)
Detailed Description
Nonlinear eigenvalue system to be solved.
Definition at line 29 of file NonlinearEigenSystem.h.
Constructor & Destructor Documentation
NonlinearEigenSystem() [1/2]
NonlinearEigenSystem::NonlinearEigenSystem (EigenProblem & problem, const std::string & name)
Definition at line 101 of file NonlinearEigenSystem.C.
  : NonlinearSystemBase(eigen_problem, eigen_problem.es().add_system<EigenSystem>(name), name),
    _eigen_sys(eigen_problem.es().get_system<EigenSystem>(name)),
    _eigen_problem(eigen_problem),
    _solver_configuration(nullptr),
    _n_eigen_pairs_required(eigen_problem.getNEigenPairsRequired()),
    _work_rhs_vector_AX(addVector("work_rhs_vector_Ax", false, PARALLEL)),
    _work_rhs_vector_BX(addVector("work_rhs_vector_Bx", false, PARALLEL)),
    _precond_matrix_includes_eigen(false),
    _preconditioner(nullptr)
{
  sys().attach_assemble_function(Moose::assemble_matrix);
  SlepcEigenSolver<Number> * solver =
      cast_ptr<SlepcEigenSolver<Number> *>(_eigen_sys.eigen_solver.get());
  if (!solver)
    mooseError("A slepc eigen solver is required");
  // setup of our class @SlepcSolverConfiguration
  _solver_configuration = std::make_unique<SlepcEigenSolverConfiguration>(eigen_problem, *solver);
  solver->set_solver_configuration(*_solver_configuration);
  _Ax_tag = eigen_problem.addVectorTag("Ax_tag");
  _Bx_tag = eigen_problem.addVectorTag("Eigen");
  _A_tag = eigen_problem.addMatrixTag("A_tag");
  _B_tag = eigen_problem.addMatrixTag("Eigen");
  // By default, _precond_tag and _A_tag will share the same
  // objects. If we want to include eigen contributions to
  // the preconditioning matrix, and then _precond_tag will
  // point to part of "B" objects
  _precond_tag = eigen_problem.addMatrixTag("Eigen_precond");
}
NonlinearEigenSystem() [2/2]
NonlinearEigenSystem::NonlinearEigenSystem (EigenProblem & problem, const std::string & name)
Member Function Documentation
activeAllMatrixTags()
void SystemBase::activeAllMatrixTags () virtual inherited
Make all exsiting matrices ative.
Definition at line 1103 of file SystemBase.C.
{
  auto num_matrix_tags = _subproblem.numMatrixTags();
  _matrix_tag_active_flags.resize(num_matrix_tags);
  for (decltype(num_matrix_tags) tag = 0; tag < num_matrix_tags; tag++)
    if (hasMatrix(tag))
      _matrix_tag_active_flags[tag] = true;
    else
      _matrix_tag_active_flags[tag] = false;
}
Referenced by NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualAndJacobianInternal(), and NonlinearSystemBase::computeResidualTags().
activeMatrixTag()
void SystemBase::activeMatrixTag (TagID tag) virtual inherited
Active a matrix for tag.
Definition at line 1068 of file SystemBase.C.
{
  mooseAssert(_subproblem.matrixTagExists(tag),
              "Cannot active Matrix with matrix_tag : " << tag << "that does not exist");
  if (_matrix_tag_active_flags.size() < tag + 1)
    _matrix_tag_active_flags.resize(tag + 1);
  _matrix_tag_active_flags[tag] = true;
}
addBoundaryCondition()
void NonlinearSystemBase::addBoundaryCondition (const std::string & bc_name, const std::string & name, InputParameters & parameters) inherited
Adds a boundary condition.
Parameters
bc_name The type of the boundary condition
name The name of the boundary condition
parameters Boundary condition parameters
Definition at line 528 of file NonlinearSystemBase.C.
{
  // ThreadID
  THREAD_ID tid = 0;
  // Create the object
  std::shared_ptr<BoundaryCondition> bc =
      _factory.create<BoundaryCondition>(bc_name, name, parameters, tid);
  postAddResidualObject(*bc);
  // Active BoundaryIDs for the object
  const std::set<BoundaryID> & boundary_ids = bc->boundaryIDs();
  auto bc_var = dynamic_cast<const MooseVariableFieldBase *>(&bc->variable());
  _vars[tid].addBoundaryVar(boundary_ids, bc_var);
  // Cast to the various types of BCs
  std::shared_ptr<NodalBCBase> nbc = std::dynamic_pointer_cast<NodalBCBase>(bc);
  std::shared_ptr<IntegratedBCBase> ibc = std::dynamic_pointer_cast<IntegratedBCBase>(bc);
  // NodalBCBase
  if (nbc)
  {
    if (nbc->checkNodalVar() && !nbc->variable().isNodal())
      mooseError("Trying to use nodal boundary condition '",
                 nbc->name(),
                 "' on a non-nodal variable '",
                 nbc->variable().name(),
                 "'.");
    _nodal_bcs.addObject(nbc);
    _vars[tid].addBoundaryVars(boundary_ids, nbc->getCoupledVars());
    if (parameters.get<std::vector<AuxVariableName>>("save_in").size() > 0)
      _has_nodalbc_save_in = true;
    if (parameters.get<std::vector<AuxVariableName>>("diag_save_in").size() > 0)
      _has_nodalbc_diag_save_in = true;
    // DirichletBCs that are preset
    std::shared_ptr<DirichletBCBase> dbc = std::dynamic_pointer_cast<DirichletBCBase>(bc);
    if (dbc && dbc->preset())
      _preset_nodal_bcs.addObject(dbc);
    std::shared_ptr<ADDirichletBCBase> addbc = std::dynamic_pointer_cast<ADDirichletBCBase>(bc);
    if (addbc && addbc->preset())
      _ad_preset_nodal_bcs.addObject(addbc);
  }
  // IntegratedBCBase
  else if (ibc)
  {
    _integrated_bcs.addObject(ibc, tid);
    _vars[tid].addBoundaryVars(boundary_ids, ibc->getCoupledVars());
    if (parameters.get<std::vector<AuxVariableName>>("save_in").size() > 0)
      _has_save_in = true;
    if (parameters.get<std::vector<AuxVariableName>>("diag_save_in").size() > 0)
      _has_diag_save_in = true;
    for (tid = 1; tid < libMesh::n_threads(); tid++)
    {
      // Create the object
      bc = _factory.create<BoundaryCondition>(bc_name, name, parameters, tid);
      // Give users opportunity to set some parameters
      postAddResidualObject(*bc);
      // Active BoundaryIDs for the object
      const std::set<BoundaryID> & boundary_ids = bc->boundaryIDs();
      _vars[tid].addBoundaryVar(boundary_ids, bc_var);
      ibc = std::static_pointer_cast<IntegratedBCBase>(bc);
      _integrated_bcs.addObject(ibc, tid);
      _vars[tid].addBoundaryVars(boundary_ids, ibc->getCoupledVars());
    }
  }
  else
    mooseError("Unknown BoundaryCondition type for object named ", bc->name());
}
addConstraint()
void NonlinearSystemBase::addConstraint (const std::string & c_name, const std::string & name, InputParameters & parameters) inherited
Adds a Constraint.
Parameters
c_name The type of the constraint
name The name of the constraint
parameters Constraint parameters
Definition at line 612 of file NonlinearSystemBase.C.
{
  std::shared_ptr<Constraint> constraint = _factory.create<Constraint>(c_name, name, parameters);
  _constraints.addObject(constraint);
  postAddResidualObject(*constraint);
  if (constraint && constraint->addCouplingEntriesToJacobian())
    addImplicitGeometricCouplingEntriesToJacobian(true);
}
addDamper()
void NonlinearSystemBase::addDamper (const std::string & damper_name, const std::string & name, InputParameters & parameters) inherited
Adds a damper.
Parameters
damper_name The type of the damper
name The name of the damper
parameters Damper parameters
Definition at line 679 of file NonlinearSystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); ++tid)
  {
    std::shared_ptr<Damper> damper = _factory.create<Damper>(damper_name, name, parameters, tid);
    // Attempt to cast to the damper types
    std::shared_ptr<ElementDamper> ed = std::dynamic_pointer_cast<ElementDamper>(damper);
    std::shared_ptr<NodalDamper> nd = std::dynamic_pointer_cast<NodalDamper>(damper);
    std::shared_ptr<GeneralDamper> gd = std::dynamic_pointer_cast<GeneralDamper>(damper);
    if (gd)
    {
      _general_dampers.addObject(gd);
      break; // not threaded
    }
    else if (ed)
      _element_dampers.addObject(ed, tid);
    else if (nd)
      _nodal_dampers.addObject(nd, tid);
    else
      mooseError("Invalid damper type");
  }
}
addDGKernel()
void NonlinearSystemBase::addDGKernel (std::string dg_kernel_name, const std::string & name, InputParameters & parameters) inherited
Adds a DG kernel.
Parameters
dg_kernel_name The type of the DG kernel
name The name of the DG kernel
parameters DG kernel parameters
Definition at line 639 of file NonlinearSystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); ++tid)
  {
    auto dg_kernel = _factory.create<DGKernelBase>(dg_kernel_name, name, parameters, tid);
    _dg_kernels.addObject(dg_kernel, tid);
    postAddResidualObject(*dg_kernel);
  }
  _doing_dg = true;
  if (parameters.get<std::vector<AuxVariableName>>("save_in").size() > 0)
    _has_save_in = true;
  if (parameters.get<std::vector<AuxVariableName>>("diag_save_in").size() > 0)
    _has_diag_save_in = true;
}
addDiracKernel()
void NonlinearSystemBase::addDiracKernel (const std::string & kernel_name, const std::string & name, InputParameters & parameters) inherited
Adds a Dirac kernel.
Parameters
kernel_name The type of the dirac kernel
name The name of the Dirac kernel
parameters Dirac kernel parameters
Definition at line 625 of file NonlinearSystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    std::shared_ptr<DiracKernelBase> kernel =
        _factory.create<DiracKernelBase>(kernel_name, name, parameters, tid);
    postAddResidualObject(*kernel);
    _dirac_kernels.addObject(kernel, tid);
  }
}
addDotVectors()
void NonlinearSystemBase::addDotVectors () inherited
Add u_dot, u_dotdot, u_dot_old and u_dotdot_old vectors if requested by the time integrator.
Definition at line 202 of file NonlinearSystemBase.C.
{
  if (_fe_problem.uDotRequested())
    _u_dot = &addVector("u_dot", true, GHOSTED);
  if (_fe_problem.uDotOldRequested())
    _u_dot_old = &addVector("u_dot_old", true, GHOSTED);
  if (_fe_problem.uDotDotRequested())
    _u_dotdot = &addVector("u_dotdot", true, GHOSTED);
  if (_fe_problem.uDotDotOldRequested())
    _u_dotdot_old = &addVector("u_dotdot_old", true, GHOSTED);
}
addImplicitGeometricCouplingEntries()
void NonlinearSystemBase::addImplicitGeometricCouplingEntries (GeometricSearchData & geom_search_data) inherited
Adds entries to the Jacobian in the correct positions for couplings coming from dofs being coupled that are related geometrically (i.e.
near each other across a gap).
Definition at line 2079 of file NonlinearSystemBase.C.
{
  if (!hasMatrix(systemMatrixTag()))
    mooseError("Need a system matrix ");
  // At this point, have no idea how to make
  // this work with tag system
  auto & jacobian = getMatrix(systemMatrixTag());
  std::unordered_map<dof_id_type, std::vector<dof_id_type>> graph;
  findImplicitGeometricCouplingEntries(geom_search_data, graph);
  for (const auto & it : graph)
  {
    dof_id_type dof = it.first;
    const auto & row = it.second;
    for (const auto & coupled_dof : row)
      jacobian.add(dof, coupled_dof, 0);
  }
}
Referenced by NonlinearSystemBase::computeJacobianInternal().
addImplicitGeometricCouplingEntriesToJacobian()
void NonlinearSystemBase::addImplicitGeometricCouplingEntriesToJacobian (bool add = true) inline inherited
If called with true this will add entries into the jacobian to link together degrees of freedom that are found to be related through the geometric search system.
These entries are really only used by the Finite Difference Preconditioner and the constraint system right now.
Definition at line 462 of file NonlinearSystemBase.h.
  {
    _add_implicit_geometric_coupling_entries_to_jacobian = add;
  }
Referenced by NonlinearSystemBase::addConstraint(), and FiniteDifferencePreconditioner::FiniteDifferencePreconditioner().
addInterfaceKernel()
void NonlinearSystemBase::addInterfaceKernel (std::string interface_kernel_name, const std::string & name, InputParameters & parameters) inherited
Adds an interface kernel.
Parameters
interface_kernel_name The type of the interface kernel
name The name of the interface kernel
parameters interface kernel parameters
Definition at line 659 of file NonlinearSystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); ++tid)
  {
    std::shared_ptr<InterfaceKernelBase> interface_kernel =
        _factory.create<InterfaceKernelBase>(interface_kernel_name, name, parameters, tid);
    postAddResidualObject(*interface_kernel);
    const std::set<BoundaryID> & boundary_ids = interface_kernel->boundaryIDs();
    auto ik_var = dynamic_cast<const MooseVariableFieldBase *>(&interface_kernel->variable());
    _vars[tid].addBoundaryVar(boundary_ids, ik_var);
    _interface_kernels.addObject(interface_kernel, tid);
    _vars[tid].addBoundaryVars(boundary_ids, interface_kernel->getCoupledVars());
  }
}
addKernel()
void NonlinearSystemBase::addKernel (const std::string & kernel_name, const std::string & name, InputParameters & parameters) virtual inherited
Adds a kernel.
Parameters
kernel_name The type of the kernel
name The name of the kernel
parameters Kernel parameters
Reimplemented in MooseEigenSystem.
Definition at line 477 of file NonlinearSystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    // Create the kernel object via the factory and add to warehouse
    std::shared_ptr<KernelBase> kernel =
        _factory.create<KernelBase>(kernel_name, name, parameters, tid);
    _kernels.addObject(kernel, tid);
    postAddResidualObject(*kernel);
  }
  if (parameters.get<std::vector<AuxVariableName>>("save_in").size() > 0)
    _has_save_in = true;
  if (parameters.get<std::vector<AuxVariableName>>("diag_save_in").size() > 0)
    _has_diag_save_in = true;
}
addMatrix()
SparseMatrix< Number > & SystemBase::addMatrix (TagID tag) inherited
Adds a matrix with a given tag.
Parameters
tag_name The name of the tag
Definition at line 559 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag))
    mooseError("Cannot add tagged matrix with TagID ",
               tag,
               " in system '",
               name(),
               "' because the tag does not exist in the problem");
  if (hasMatrix(tag))
    return getMatrix(tag);
  const auto matrix_name = _subproblem.matrixTagName(tag);
  SparseMatrix<Number> & mat = system().add_matrix(matrix_name);
  associateMatrixToTag(mat, tag);
  return mat;
}
addNodalKernel()
void NonlinearSystemBase::addNodalKernel (const std::string & kernel_name, const std::string & name, InputParameters & parameters) virtual inherited
Adds a NodalKernel.
Parameters
kernel_name The type of the nodal kernel
name The name of the kernel
parameters Kernel parameters
Definition at line 497 of file NonlinearSystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    // Create the kernel object via the factory and add to the warehouse
    std::shared_ptr<NodalKernelBase> kernel =
        _factory.create<NodalKernelBase>(kernel_name, name, parameters, tid);
    _nodal_kernels.addObject(kernel, tid);
    postAddResidualObject(*kernel);
  }
  if (parameters.get<std::vector<AuxVariableName>>("save_in").size() > 0)
    _has_save_in = true;
  if (parameters.get<std::vector<AuxVariableName>>("diag_save_in").size() > 0)
    _has_diag_save_in = true;
}
addScalarKernel()
void NonlinearSystemBase::addScalarKernel (const std::string & kernel_name, const std::string & name, InputParameters & parameters) inherited
Adds a scalar kernel.
Parameters
kernel_name The type of the kernel
name The name of the kernel
parameters Kernel parameters
Definition at line 517 of file NonlinearSystemBase.C.
{
  std::shared_ptr<ScalarKernelBase> kernel =
      _factory.create<ScalarKernelBase>(kernel_name, name, parameters);
  postAddResidualObject(*kernel);
  _scalar_kernels.addObject(kernel);
}
addScalingVector()
void SystemBase::addScalingVector () inherited
Add the scaling factor vector to the system.
Definition at line 1464 of file SystemBase.C.
{
  addVector("scaling_factors", /*project=*/false, libMesh::ParallelType::GHOSTED);
  _subproblem.hasScalingVector();
}
Referenced by MooseVariableBase::initialSetup().
addSplit()
void NonlinearSystemBase::addSplit (const std::string & split_name, const std::string & name, InputParameters & parameters) inherited
Adds a split.
Parameters
split_name The type of the split
name The name of the split
parameters Split parameters
Definition at line 707 of file NonlinearSystemBase.C.
{
  std::shared_ptr<Split> split = _factory.create<Split>(split_name, name, parameters);
  _splits.addObject(split);
}
addTimeIntegrator() [1/3]
virtual void SystemBase::addTimeIntegrator (const std::string & , const std::string & , InputParameters &) inline virtual inherited
Reimplemented from SystemBase.
Definition at line 861 of file SystemBase.h.
  {
  }
addTimeIntegrator() [2/3]
void NonlinearSystemBase::addTimeIntegrator (const std::string & type, const std::string & name, InputParameters & parameters) override virtual inherited
Add a time integrator.
Parameters
type Type of the integrator
name The name of the integrator
parameters Integrator params
Reimplemented from SystemBase.
Definition at line 466 of file NonlinearSystemBase.C.
{
  parameters.set<SystemBase *>("_sys") = this;
  std::shared_ptr<TimeIntegrator> ti = _factory.create<TimeIntegrator>(type, name, parameters);
  _time_integrator = ti;
}
addTimeIntegrator() [3/3]
virtual void SystemBase::addTimeIntegrator (std::shared_ptr< TimeIntegrator >) inline virtual inherited
Reimplemented from SystemBase.
Definition at line 867 of file SystemBase.h.
{}
addVariable()
void SystemBase::addVariable (const std::string & var_type, const std::string & var_name, InputParameters & parameters) virtual inherited
Canonical method for adding a variable.
Parameters
var_type the type of the variable, e.g. MooseVariableScalar
var_name the variable name, e.g. 'u'
params the InputParameters from which to construct the variable
Reimplemented in AuxiliarySystem.
Definition at line 708 of file SystemBase.C.
{
  _numbered_vars.resize(libMesh::n_threads());
  auto components = parameters.get<unsigned int>("components");
  // Convert the std::vector parameter provided by the user into a std::set for use by libMesh's
  // System::add_variable method
  std::set<SubdomainID> blocks;
  const auto & block_param = parameters.get<std::vector<SubdomainName>>("block");
  for (const auto & subdomain_name : block_param)
  {
    SubdomainID blk_id = _mesh.getSubdomainID(subdomain_name);
    blocks.insert(blk_id);
  }
  auto fe_type = FEType(Utility::string_to_enum<Order>(parameters.get<MooseEnum>("order")),
                        Utility::string_to_enum<FEFamily>(parameters.get<MooseEnum>("family")));
  unsigned int var_num;
  if (var_type == "ArrayMooseVariable")
  {
    if (fe_type.family == NEDELEC_ONE || fe_type.family == LAGRANGE_VEC ||
        fe_type.family == MONOMIAL_VEC || fe_type.family == RAVIART_THOMAS)
      mooseError("Vector family type cannot be used in an array variable");
    // Build up the variable names
    std::vector<std::string> var_names;
    for (unsigned int i = 0; i < components; i++)
      var_names.push_back(SubProblem::arrayVariableComponent(name, i));
    // The number returned by libMesh is the _last_ variable number... we want to hold onto the
    // _first_
    var_num = system().add_variables(var_names, fe_type, &blocks) - (components - 1);
    // Set as array variable
    if (parameters.isParamSetByUser("array") && !parameters.get<bool>("array"))
      mooseError("Variable '",
                 name,
                 "' is an array variable ('components' > 1) but 'array' is set to false.");
    parameters.set<bool>("array") = true;
  }
  else
    var_num = system().add_variable(name, fe_type, &blocks);
  parameters.set<unsigned int>("_var_num") = var_num;
  parameters.set<SystemBase *>("_system_base") = this;
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    parameters.set<THREAD_ID>("tid") = tid;
    std::shared_ptr<MooseVariableBase> var =
        _factory.create<MooseVariableBase>(var_type, name, parameters, tid);
    _vars[tid].add(name, var);
    if (auto fe_var = dynamic_cast<MooseVariableFieldBase *>(var.get()))
    {
      auto required_size = var_num + components;
      if (required_size > _numbered_vars[tid].size())
        _numbered_vars[tid].resize(required_size);
      for (MooseIndex(components) component = 0; component < components; ++component)
        _numbered_vars[tid][var_num + component] = fe_var;
      if (auto * const functor = dynamic_cast<Moose::FunctorBase<ADReal> *>(fe_var))
        _subproblem.addFunctor(name, *functor, tid);
      else if (auto * const functor = dynamic_cast<Moose::FunctorBase<ADRealVectorValue> *>(fe_var))
        _subproblem.addFunctor(name, *functor, tid);
      else if (auto * const functor = dynamic_cast<Moose::FunctorBase<RealEigenVector> *>(fe_var))
        _subproblem.addFunctor(name, *functor, tid);
      else
        mooseError("This should be a functor");
    }
    if (var->blockRestricted())
      for (const SubdomainID & id : var->blockIDs())
        for (MooseIndex(components) component = 0; component < components; ++component)
          _var_map[var_num + component].insert(id);
    else
      for (MooseIndex(components) component = 0; component < components; ++component)
        _var_map[var_num + component] = std::set<SubdomainID>();
  }
  // getMaxVariableNumber is an API method used in Rattlesnake
  if (var_num > _max_var_number)
    _max_var_number = var_num;
}
Referenced by AuxiliarySystem::addVariable().
addVariableToCopy()
void SystemBase::addVariableToCopy (const std::string & dest_name, const std::string & source_name, const std::string & timestep) virtual inherited
Add info about variable that will be copied.
Parameters
dest_name Name of the nodal variable being used for copying into (name is from the exodusII file)
source_name Name of the nodal variable being used for copying from (name is from the exodusII file)
timestep Timestep in the file being used
Definition at line 1143 of file SystemBase.C.
{
  _var_to_copy.push_back(VarCopyInfo(dest_name, source_name, timestep));
}
Referenced by CopyNodalVarsAction::act().
addVariableToZeroOnJacobian()
void SystemBase::addVariableToZeroOnJacobian (std::string var_name) virtual inherited
Adds this variable to the list of variables to be zeroed during each Jacobian evaluation.
Parameters
var_name The name of the variable to be zeroed.
Reimplemented in DisplacedSystem.
Definition at line 169 of file SystemBase.C.
{
  _vars_to_be_zeroed_on_jacobian.push_back(var_name);
}
Referenced by ADDGKernel::ADDGKernel(), DisplacedSystem::addVariableToZeroOnJacobian(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), DGKernel::DGKernel(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), NodalBC::NodalBC(), and NodalKernel::NodalKernel().
addVariableToZeroOnResidual()
void SystemBase::addVariableToZeroOnResidual (std::string var_name) virtual inherited
Adds this variable to the list of variables to be zeroed during each residual evaluation.
Parameters
var_name The name of the variable to be zeroed.
Reimplemented in DisplacedSystem.
Definition at line 163 of file SystemBase.C.
{
  _vars_to_be_zeroed_on_residual.push_back(var_name);
}
Referenced by ADDGKernel::ADDGKernel(), DisplacedSystem::addVariableToZeroOnResidual(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), DGKernel::DGKernel(), IntegratedBC::IntegratedBC(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), NodalBC::NodalBC(), and NodalKernel::NodalKernel().
addVector() [1/2]
NumericVector< Number > & SystemBase::addVector (const std::string & vector_name, const bool project, const ParallelType type) inherited
Adds a solution length vector to the system.
Parameters
vector_name The name of the vector.
project Whether or not to project this vector when doing mesh refinement. If the vector is just going to be recomputed then there is no need to project it.
type What type of parallel vector. This is usually either PARALLEL or GHOSTED. GHOSTED is needed if you are going to be accessing off-processor entries. The ghosting pattern is the same as the solution vector.
Definition at line 597 of file SystemBase.C.
{
  if (hasVector(vector_name))
    return getVector(vector_name);
  NumericVector<Number> & vec = system().add_vector(vector_name, project, type);
  return vec;
}
Referenced by AuxiliarySystem::addDotVectors(), NonlinearSystemBase::addDotVectors(), SystemBase::addScalingVector(), PicardSolve::allocateStorage(), SecantSolve::allocateStorage(), SteffensenSolve::allocateStorage(), AStableDirk4::AStableDirk4(), ExplicitTimeIntegrator::ExplicitTimeIntegrator(), NonlinearSystemBase::getResidualNonTimeVector(), NonlinearSystemBase::getResidualTimeVector(), CentralDifference::initialSetup(), LStableDirk3::LStableDirk3(), LStableDirk4::LStableDirk4(), SystemBase::needSolutionState(), NonlinearSystemBase::residualGhosted(), and SystemBase::saveOldSolutions().
addVector() [2/2]
NumericVector< Number > & SystemBase::addVector (TagID tag, const bool project, const ParallelType type) inherited
Adds a solution length vector to the system with the specified TagID.
Parameters
tag_name The name of the tag
project Whether or not to project this vector when doing mesh refinement. If the vector is just going to be recomputed then there is no need to project it.
type What type of parallel vector. This is usually either PARALLEL or GHOSTED. GHOSTED is needed if you are going to be accessing off-processor entries. The ghosting pattern is the same as the solution vector.
Definition at line 607 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot add tagged vector with TagID ",
               tag,
               " in system '",
               name(),
               "' because the tag does not exist in the problem");
  if (hasVector(tag))
  {
    auto & vec = getVector(tag);
    if (type != ParallelType::AUTOMATIC && vec.type() != type)
      mooseError("Cannot add tagged vector '",
                 _subproblem.vectorTagName(tag),
                 "', in system '",
                 name(),
                 "' because a vector with the same name was found with a different parallel type");
    return vec;
  }
  const auto vector_name = _subproblem.vectorTagName(tag);
  NumericVector<Number> & vec = system().add_vector(vector_name, project, type);
  associateVectorToTag(vec, tag);
  return vec;
}
applyScalingFactors()
void SystemBase::applyScalingFactors (const std::vector< Real > & inverse_scaling_factors) inherited
Applies scaling factors to the system's variables.
Parameters
inverse_scaling_factors A vector containing the inverse of each variable's scaling factor, e.g. 1 / scaling_factor
Definition at line 1424 of file SystemBase.C.
{
  for (MooseIndex(_vars) thread = 0; thread < _vars.size(); ++thread)
  {
    auto & field_variables = _vars[thread].fieldVariables();
    for (MooseIndex(field_variables) i = 0; i < field_variables.size(); ++i)
      field_variables[i]->scalingFactor(1. / inverse_scaling_factors[i] *
                                        field_variables[i]->scalingFactor());
    auto offset = field_variables.size();
    auto & scalar_variables = _vars[thread].scalars();
    for (MooseIndex(scalar_variables) i = 0; i < scalar_variables.size(); ++i)
      scalar_variables[i]->scalingFactor(1. / inverse_scaling_factors[offset + i] *
                                         scalar_variables[i]->scalingFactor());
    if (thread == 0 && _verbose)
    {
      _console << "Automatic scaling factors:\n";
      auto original_flags = _console.flags();
      auto original_precision = _console.precision();
      _console.unsetf(std::ios_base::floatfield);
      _console.precision(6);
      for (const auto & field_variable : field_variables)
        _console << "  " << field_variable->name() << ": " << field_variable->scalingFactor()
                 << "\n";
      for (const auto & scalar_variable : scalar_variables)
        _console << "  " << scalar_variable->name() << ": " << scalar_variable->scalingFactor()
                 << "\n";
      _console << "\n" << std::endl;
      // restore state
      _console.flags(original_flags);
      _console.precision(original_precision);
    }
  }
}
Referenced by NonlinearSystemBase::computeScaling().
assembleConstraintsSeparately()
void NonlinearSystemBase::assembleConstraintsSeparately (bool separately = true) inline inherited
Indicates whether to assemble residual and Jacobian after each constraint application.
When true, enables "transitive" constraint application: subsequent constraints can use prior constraints' results.
Definition at line 472 of file NonlinearSystemBase.h.
  {
    _assemble_constraints_separately = separately;
  }
assembleScalingVector()
void NonlinearSystemBase::assembleScalingVector () protected inherited
Assemble the numeric vector of scaling factors such that it can be used during assembly of the system matrix.
Definition at line 3873 of file NonlinearSystemBase.C.
{
  if (!hasVector("scaling_factors"))
    // No variables have indicated they need scaling
    return;
  auto & scaling_vector = getVector("scaling_factors");
  const auto & lm_mesh = _mesh.getMesh();
  const auto & dof_map = dofMap();
  const auto & field_variables = _vars[0].fieldVariables();
  const auto & scalar_variables = _vars[0].scalars();
  std::vector<dof_id_type> dof_indices;
  for (const Elem * const elem :
       as_range(lm_mesh.active_local_elements_begin(), lm_mesh.active_local_elements_end()))
    for (const auto * const field_var : field_variables)
    {
      mooseAssert(field_var->count() == 1,
                  "Contact Alex Lindsay and tell him to make this work for array variables.");
      dof_map.dof_indices(elem, dof_indices, field_var->number());
      for (const auto dof : dof_indices)
        scaling_vector.set(dof, field_var->scalingFactor());
    }
  for (const auto * const scalar_var : scalar_variables)
  {
    mooseAssert(scalar_var->count() == 1,
                "Contact Alex Lindsay and tell him to make this work for array variables.");
    dof_map.SCALAR_dof_indices(dof_indices, scalar_var->number());
    for (const auto dof : dof_indices)
      scaling_vector.set(dof, scalar_var->scalingFactor());
  }
  // Parallel assemble
  scaling_vector.close();
  if (auto * displaced_problem = _fe_problem.getDisplacedProblem().get())
    // copy into the corresponding displaced system vector because they should be the exact same
    displaced_problem->systemBaseNonlinear(number()).getVector("scaling_factors") = scaling_vector;
}
Referenced by NonlinearSystemBase::computeScaling(), solve(), and NonlinearSystem::solve().
assignMaxVarNDofsPerElem()
void SystemBase::assignMaxVarNDofsPerElem (std::size_t max_dofs) inline inherited
assign the maximum element dofs
Definition at line 575 of file SystemBase.h.
{ _max_var_n_dofs_per_elem = max_dofs; }
assignMaxVarNDofsPerNode()
void SystemBase::assignMaxVarNDofsPerNode (std::size_t max_dofs) inline inherited
assign the maximum node dofs
Definition at line 580 of file SystemBase.h.
{ _max_var_n_dofs_per_node = max_dofs; }
associateMatrixToTag()
void SystemBase::associateMatrixToTag (SparseMatrix< Number > & matrix, TagID tag) virtual inherited
Associate a matrix to a tag.
Reimplemented in DisplacedSystem.
Definition at line 1025 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag))
    mooseError("Cannot associate matrix to tag ", tag, " because that tag does not exist");
  if (_tagged_matrices.size() < tag + 1)
    _tagged_matrices.resize(tag + 1);
  _tagged_matrices[tag] = &matrix;
}
Referenced by SystemBase::addMatrix(), DisplacedSystem::associateMatrixToTag(), NonlinearSystemBase::computeJacobian(), FEProblemBase::computeJacobianInternal(), FEProblemBase::computeJacobianTag(), and FEProblemBase::computeResidualAndJacobian().
associateVectorToTag()
void SystemBase::associateVectorToTag (NumericVector< Number > & vec, TagID tag) virtual inherited
Associate a vector for a given tag.
Reimplemented in DisplacedSystem.
Definition at line 930 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot associate vector to tag ", tag, " because that tag does not exist");
  if (_tagged_vectors.size() < tag + 1)
    _tagged_vectors.resize(tag + 1);
  _tagged_vectors[tag] = &vec;
}
Referenced by SystemBase::addVector(), DisplacedSystem::associateVectorToTag(), NonlinearSystemBase::computeNodalBCs(), FEProblemBase::computeResidual(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualTag(), NonlinearSystemBase::computeResidualTag(), FEProblemBase::computeResidualType(), and NonlinearSystemBase::setSolution().
attachPreconditioner()
void NonlinearEigenSystem::attachPreconditioner (Preconditioner< Number > * preconditioner) override virtual
Attach a customized preconditioner that requires physics knowledge.
Generic preconditioners should be implemented in PETSc, instead.
Implements NonlinearSystemBase.
Definition at line 451 of file NonlinearEigenSystem.C.
{
  _preconditioner = preconditioner;
  // If we have a customized preconditioner,
  // We need to let PETSc know that
  if (_preconditioner)
  {
    Moose::SlepcSupport::registerPCToPETSc();
    // Mark this, and then we can setup correct petsc options
    _eigen_problem.solverParams()._customized_pc_for_eigen = true;
    _eigen_problem.solverParams()._type = Moose::ST_JFNK;
  }
}
attachSLEPcCallbacks()
void NonlinearEigenSystem::attachSLEPcCallbacks ()
Definition at line 254 of file NonlinearEigenSystem.C.
{
  // Tell libmesh not close matrices before solve
  _eigen_sys.get_eigen_solver().set_close_matrix_before_solve(false);
  // Matrix A
  if (_eigen_sys.has_matrix_A())
  {
    Mat mat = static_cast<PetscMatrix<Number> &>(_eigen_sys.get_matrix_A()).mat();
    Moose::SlepcSupport::attachCallbacksToMat(_eigen_problem, mat, false);
  }
  // Matrix B
  if (_eigen_sys.has_matrix_B())
  {
    Mat mat = static_cast<PetscMatrix<Number> &>(_eigen_sys.get_matrix_B()).mat();
    Moose::SlepcSupport::attachCallbacksToMat(_eigen_problem, mat, true);
  }
  // Shell matrix A
  if (_eigen_sys.has_shell_matrix_A())
  {
    Mat mat = static_cast<PetscShellMatrix<Number> &>(_eigen_sys.get_shell_matrix_A()).mat();
    // Attach callbacks for nonlinear eigenvalue solver
    Moose::SlepcSupport::attachCallbacksToMat(_eigen_problem, mat, false);
    // Set MatMult operations for shell
    Moose::SlepcSupport::setOperationsForShellMat(_eigen_problem, mat, false);
  }
  // Shell matrix B
  if (_eigen_sys.has_shell_matrix_B())
  {
    Mat mat = static_cast<PetscShellMatrix<Number> &>(_eigen_sys.get_shell_matrix_B()).mat();
    Moose::SlepcSupport::attachCallbacksToMat(_eigen_problem, mat, true);
    // Set MatMult operations for shell
    Moose::SlepcSupport::setOperationsForShellMat(_eigen_problem, mat, true);
  }
  // Preconditioning matrix
  if (_eigen_sys.has_precond_matrix())
  {
    Mat mat = static_cast<PetscMatrix<Number> &>(_eigen_sys.get_precond_matrix()).mat();
    Moose::SlepcSupport::attachCallbacksToMat(_eigen_problem, mat, true);
  }
  // Shell preconditioning matrix
  if (_eigen_sys.has_shell_precond_matrix())
  {
    Mat mat = static_cast<PetscShellMatrix<Number> &>(_eigen_sys.get_shell_precond_matrix()).mat();
    Moose::SlepcSupport::attachCallbacksToMat(_eigen_problem, mat, true);
  }
}
augmentSendList()
void SystemBase::augmentSendList (std::vector< dof_id_type > & send_list) virtual inherited
Will modify the send_list to add all of the extra ghosted dofs for this system.
Reimplemented in DisplacedSystem.
Definition at line 441 of file SystemBase.C.
{
  std::set<dof_id_type> & ghosted_elems = _subproblem.ghostedElems();
  DofMap & dof_map = dofMap();
  std::vector<dof_id_type> dof_indices;
  System & sys = system();
  unsigned int sys_num = sys.number();
  unsigned int n_vars = sys.n_vars();
  for (const auto & elem_id : ghosted_elems)
  {
    Elem * elem = _mesh.elemPtr(elem_id);
    if (elem->active())
    {
      dof_map.dof_indices(elem, dof_indices);
      // Only need to ghost it if it's actually not on this processor
      for (const auto & dof : dof_indices)
        if (dof < dof_map.first_dof() || dof >= dof_map.end_dof())
          send_list.push_back(dof);
      // Now add the DoFs from all of the nodes.  This is necessary because of block
      // restricted variables.  A variable might not live _on_ this element but it
      // might live on nodes connected to this element.
      for (unsigned int n = 0; n < elem->n_nodes(); n++)
      {
        Node * node = elem->node_ptr(n);
        // Have to get each variable's dofs
        for (unsigned int v = 0; v < n_vars; v++)
        {
          const Variable & var = sys.variable(v);
          unsigned int var_num = var.number();
          unsigned int n_comp = var.n_components();
          // See if this variable has any dofs at this node
          if (node->n_dofs(sys_num, var_num) > 0)
          {
            // Loop over components of the variable
            for (unsigned int c = 0; c < n_comp; c++)
              send_list.push_back(node->dof_number(sys_num, var_num, c));
          }
        }
      }
    }
  }
}
Referenced by DisplacedSystem::augmentSendList(), and extraSendList().
augmentSparsity()
void NonlinearSystemBase::augmentSparsity (SparsityPattern::Graph & sparsity, std::vector< dof_id_type > & n_nz, std::vector< dof_id_type > & n_oz) override virtual inherited
Will modify the sparsity pattern to add logical geometric connections.
Implements SystemBase.
Definition at line 3248 of file NonlinearSystemBase.C.
{
  if (_add_implicit_geometric_coupling_entries_to_jacobian)
  {
    _fe_problem.updateGeomSearch();
    std::unordered_map<dof_id_type, std::vector<dof_id_type>> graph;
    findImplicitGeometricCouplingEntries(_fe_problem.geomSearchData(), graph);
    if (_fe_problem.getDisplacedProblem())
      findImplicitGeometricCouplingEntries(_fe_problem.getDisplacedProblem()->geomSearchData(),
                                           graph);
    const dof_id_type first_dof_on_proc = dofMap().first_dof(processor_id());
    const dof_id_type end_dof_on_proc = dofMap().end_dof(processor_id());
    // The total number of dofs on and off processor
    const dof_id_type n_dofs_on_proc = dofMap().n_local_dofs();
    const dof_id_type n_dofs_not_on_proc = dofMap().n_dofs() - dofMap().n_local_dofs();
    for (const auto & git : graph)
    {
      dof_id_type dof = git.first;
      dof_id_type local_dof = dof - first_dof_on_proc;
      if (dof < first_dof_on_proc || dof >= end_dof_on_proc)
        continue;
      const auto & row = git.second;
      SparsityPattern::Row & sparsity_row = sparsity[local_dof];
      unsigned int original_row_length = sparsity_row.size();
      sparsity_row.insert(sparsity_row.end(), row.begin(), row.end());
      SparsityPattern::sort_row(
          sparsity_row.begin(), sparsity_row.begin() + original_row_length, sparsity_row.end());
      // Fix up nonzero arrays
      for (const auto & coupled_dof : row)
      {
        if (coupled_dof < first_dof_on_proc || coupled_dof >= end_dof_on_proc)
        {
          if (n_oz[local_dof] < n_dofs_not_on_proc)
            n_oz[local_dof]++;
        }
        else
        {
          if (n_nz[local_dof] < n_dofs_on_proc)
            n_nz[local_dof]++;
        }
      }
    }
  }
}
automaticScaling() [1/2]
bool SystemBase::automaticScaling () const inline inherited
Getter for whether we are performing automatic scaling.
Returns
whether we are performing automatic scaling
Definition at line 117 of file SystemBase.h.
{ return _automatic_scaling; }
Referenced by SubProblem::automaticScaling().
automaticScaling() [2/2]
void SystemBase::automaticScaling (bool automatic_scaling) inline inherited
Setter for whether we are performing automatic scaling.
Parameters
automatic_scaling A boolean representing whether we are performing automatic scaling
Definition at line 123 of file SystemBase.h.
{ _automatic_scaling = automatic_scaling; }
autoScalingParam()
void NonlinearSystemBase::autoScalingParam (Real resid_vs_jac_scaling_param) inline inherited
Sets the param that indicates the weighting of the residual vs the Jacobian in determining variable scaling parameters.
A value of 1 indicates pure residual-based scaling. A value of 0 indicates pure Jacobian-based scaling
Definition at line 655 of file NonlinearSystemBase.h.
  {
    _resid_vs_jac_scaling_param = resid_vs_jac_scaling_param;
  }
Referenced by FEProblemSolve::FEProblemSolve().
checkIntegrity() [1/2]
void NonlinearEigenSystem::checkIntegrity ()
For eigenvalue problems (including standard and generalized), inhomogeneous (Dirichlet or Neumann) boundary conditions are not allowed.
Definition at line 393 of file NonlinearEigenSystem.C.
{
  if (_nodal_bcs.hasActiveObjects())
  {
    const auto & nodal_bcs = _nodal_bcs.getActiveObjects();
    for (const auto & nodal_bc : nodal_bcs)
    {
      // If this is a dirichlet boundary condition
      auto nbc = std::dynamic_pointer_cast<DirichletBC>(nodal_bc);
      // If this is a eigen Dirichlet boundary condition
      auto eigen_nbc = std::dynamic_pointer_cast<EigenDirichletBC>(nodal_bc);
      // ArrayDirichletBC
      auto anbc = std::dynamic_pointer_cast<ArrayDirichletBC>(nodal_bc);
      // EigenArrayDirichletBC
      auto aeigen_nbc = std::dynamic_pointer_cast<EigenArrayDirichletBC>(nodal_bc);
      // If it is a Dirichlet boundary condition, then value has to be zero
      if (nbc && nbc->variable().eigen() && nbc->getParam<Real>("value"))
        mooseError(
            "Can't set an inhomogeneous Dirichlet boundary condition for eigenvalue problems.");
      // If it is an array Dirichlet boundary condition, all values should be zero
      else if (anbc)
      {
        auto & values = anbc->getParam<RealEigenVector>("values");
        for (MooseIndex(values) i = 0; i < values.size(); i++)
        {
          if (values(i))
            mooseError("Can't set an inhomogeneous array Dirichlet boundary condition for "
                       "eigenvalue problems.");
        }
      }
      else if (!nbc && !eigen_nbc && !anbc && !aeigen_nbc)
        mooseError(
            "Invalid NodalBC for eigenvalue problems, please use homogeneous (array) Dirichlet.");
    }
  }
}
checkIntegrity() [2/2]
void NonlinearEigenSystem::checkIntegrity () inline
Definition at line 207 of file NonlinearEigenSystem.h.
{}
checkKernelCoverage()
void NonlinearSystemBase::checkKernelCoverage (const std::set< SubdomainID > & mesh_subdomains) const inherited
System Integrity Checks
Definition at line 3409 of file NonlinearSystemBase.C.
{
  // Obtain all blocks and variables covered by all kernels
  std::set<SubdomainID> input_subdomains;
  std::set<std::string> kernel_variables;
  bool global_kernels_exist = false;
  global_kernels_exist |= _scalar_kernels.hasActiveObjects();
  global_kernels_exist |= _nodal_kernels.hasActiveObjects();
  _kernels.subdomainsCovered(input_subdomains, kernel_variables);
  _dg_kernels.subdomainsCovered(input_subdomains, kernel_variables);
  _nodal_kernels.subdomainsCovered(input_subdomains, kernel_variables);
  _scalar_kernels.subdomainsCovered(input_subdomains, kernel_variables);
  _constraints.subdomainsCovered(input_subdomains, kernel_variables);
  if (_fe_problem.haveFV())
  {
    std::vector<FVElementalKernel *> fv_elemental_kernels;
    _fe_problem.theWarehouse()
        .query()
        .template condition<AttribSystem>("FVElementalKernel")
        .queryInto(fv_elemental_kernels);
    for (auto fv_kernel : fv_elemental_kernels)
    {
      if (fv_kernel->blockRestricted())
        for (auto block_id : fv_kernel->blockIDs())
          input_subdomains.insert(block_id);
      else
        global_kernels_exist = true;
      kernel_variables.insert(fv_kernel->variable().name());
      // Check for lagrange multiplier
      if (dynamic_cast<FVScalarLagrangeMultiplierConstraint *>(fv_kernel))
        kernel_variables.insert(dynamic_cast<FVScalarLagrangeMultiplierConstraint *>(fv_kernel)
                                    ->lambdaVariable()
                                    .name());
    }
    std::vector<FVFluxKernel *> fv_flux_kernels;
    _fe_problem.theWarehouse()
        .query()
        .template condition<AttribSystem>("FVFluxKernel")
        .queryInto(fv_flux_kernels);
    for (auto fv_kernel : fv_flux_kernels)
    {
      if (fv_kernel->blockRestricted())
        for (auto block_id : fv_kernel->blockIDs())
          input_subdomains.insert(block_id);
      else
        global_kernels_exist = true;
      kernel_variables.insert(fv_kernel->variable().name());
    }
    std::vector<FVInterfaceKernel *> fv_interface_kernels;
    _fe_problem.theWarehouse()
        .query()
        .template condition<AttribSystem>("FVInterfaceKernel")
        .queryInto(fv_interface_kernels);
    for (auto fvik : fv_interface_kernels)
      if (auto scalar_fvik = dynamic_cast<FVScalarLagrangeMultiplierInterface *>(fvik))
        kernel_variables.insert(scalar_fvik->lambdaVariable().name());
    std::vector<FVFluxBC *> fv_flux_bcs;
    _fe_problem.theWarehouse()
        .query()
        .template condition<AttribSystem>("FVFluxBC")
        .queryInto(fv_flux_bcs);
    for (auto fvbc : fv_flux_bcs)
      if (auto scalar_fvbc = dynamic_cast<FVBoundaryScalarLagrangeMultiplierConstraint *>(fvbc))
        kernel_variables.insert(scalar_fvbc->lambdaVariable().name());
  }
  // Check kernel coverage of subdomains (blocks) in your mesh
  if (!global_kernels_exist)
  {
    std::set<SubdomainID> difference;
    std::set_difference(mesh_subdomains.begin(),
                        mesh_subdomains.end(),
                        input_subdomains.begin(),
                        input_subdomains.end(),
                        std::inserter(difference, difference.end()));
    // there supposed to be no kernels on this lower-dimensional subdomain
    difference.erase(Moose::INTERNAL_SIDE_LOWERD_ID);
    difference.erase(Moose::BOUNDARY_SIDE_LOWERD_ID);
    if (!difference.empty())
    {
      std::vector<SubdomainID> difference_vec =
          std::vector<SubdomainID>(difference.begin(), difference.end());
      std::vector<SubdomainName> difference_names = _mesh.getSubdomainNames(difference_vec);
      std::stringstream missing_block_names;
      std::copy(difference_names.begin(),
                difference_names.end(),
                std::ostream_iterator<std::string>(missing_block_names, " "));
      std::stringstream missing_block_ids;
      std::copy(difference.begin(),
                difference.end(),
                std::ostream_iterator<unsigned int>(missing_block_ids, " "));
      mooseError("Each subdomain must contain at least one Kernel.\nThe following block(s) lack an "
                 "active kernel: " +
                     missing_block_names.str(),
                 " (ids: ",
                 missing_block_ids.str(),
                 ")");
    }
  }
  // Check kernel use of variables
  std::set<VariableName> variables(getVariableNames().begin(), getVariableNames().end());
  std::set<VariableName> difference;
  std::set_difference(variables.begin(),
                      variables.end(),
                      kernel_variables.begin(),
                      kernel_variables.end(),
                      std::inserter(difference, difference.end()));
  // skip checks for varaibles defined on lower-dimensional subdomain
  std::set<VariableName> vars(difference);
  for (auto & var_name : vars)
  {
    auto blks = getSubdomainsForVar(var_name);
    if (blks.count(Moose::INTERNAL_SIDE_LOWERD_ID) || blks.count(Moose::BOUNDARY_SIDE_LOWERD_ID))
      difference.erase(var_name);
  }
  if (!difference.empty())
  {
    std::stringstream missing_kernel_vars;
    std::copy(difference.begin(),
              difference.end(),
              std::ostream_iterator<std::string>(missing_kernel_vars, " "));
    mooseError("Each variable must be referenced by at least one active Kernel.\nThe following "
               "variable(s) lack an active kernel: " +
               missing_kernel_vars.str());
  }
}
clearAllDofIndices()
void SystemBase::clearAllDofIndices () inherited
Clear all dof indices from moose variables.
Definition at line 1519 of file SystemBase.C.
{
  for (auto & var_warehouse : _vars)
    var_warehouse.clearAllDofIndices();
}
Referenced by SubProblem::clearAllDofIndices().
closeTaggedMatrices()
void SystemBase::closeTaggedMatrices (const std::set< TagID > & tags) inherited
Close all matrices associated the tags.
Definition at line 1009 of file SystemBase.C.
{
  for (auto tag : tags)
    if (hasMatrix(tag))
      getMatrix(tag).close();
}
Referenced by NonlinearSystemBase::computeJacobianInternal(), and NonlinearSystemBase::computeResidualAndJacobianTags().
closeTaggedVector()
void SystemBase::closeTaggedVector (const TagID tag) inherited
Close vector with the given tag.
Definition at line 638 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot close vector with TagID ",
               tag,
               " in system '",
               name(),
               "' because that tag does not exist in the problem");
  else if (!hasVector(tag))
    mooseError("Cannot close vector tag with name '",
               _subproblem.vectorTagName(tag),
               "' in system '",
               name(),
               "' because there is no vector associated with that tag");
  getVector(tag).close();
}
Referenced by SystemBase::closeTaggedVectors().
closeTaggedVectors()
void SystemBase::closeTaggedVectors (const std::set< TagID > & tags) inherited
Close all vectors for given tags.
Definition at line 657 of file SystemBase.C.
{
  for (const auto tag : tags)
    closeTaggedVector(tag);
}
Referenced by NonlinearSystemBase::computeResidualAndJacobianTags(), and NonlinearSystemBase::computeResidualTags().
computeDamping()
Real NonlinearSystemBase::computeDamping (const NumericVector< Number > & solution, const NumericVector< Number > & update) inherited
Compute damping.
Parameters
solution The trail solution vector
update The incremental update to the solution vector
Returns
returns The damping factor
Definition at line 3096 of file NonlinearSystemBase.C.
{
  // Default to no damping
  Real damping = 1.0;
  bool has_active_dampers = false;
  try
  {
    if (_element_dampers.hasActiveObjects())
    {
      PARALLEL_TRY
      {
        TIME_SECTION("computeDampers", 3, "Computing Dampers");
        has_active_dampers = true;
        *_increment_vec = update;
        ComputeElemDampingThread cid(_fe_problem, *this);
        Threads::parallel_reduce(*_mesh.getActiveLocalElementRange(), cid);
        damping = std::min(cid.damping(), damping);
      }
      PARALLEL_CATCH;
    }
    if (_nodal_dampers.hasActiveObjects())
    {
      PARALLEL_TRY
      {
        TIME_SECTION("computeDamping::element", 3, "Computing Element Damping");
        has_active_dampers = true;
        *_increment_vec = update;
        ComputeNodalDampingThread cndt(_fe_problem, *this);
        Threads::parallel_reduce(*_mesh.getLocalNodeRange(), cndt);
        damping = std::min(cndt.damping(), damping);
      }
      PARALLEL_CATCH;
    }
    if (_general_dampers.hasActiveObjects())
    {
      PARALLEL_TRY
      {
        TIME_SECTION("computeDamping::general", 3, "Computing General Damping");
        has_active_dampers = true;
        const auto & gdampers = _general_dampers.getActiveObjects();
        for (const auto & damper : gdampers)
        {
          Real gd_damping = damper->computeDamping(solution, update);
          try
          {
            damper->checkMinDamping(gd_damping);
          }
          catch (MooseException & e)
          {
            _fe_problem.setException(e.what());
          }
          damping = std::min(gd_damping, damping);
        }
      }
      PARALLEL_CATCH;
    }
  }
  catch (MooseException & e)
  {
    // The buck stops here, we have already handled the exception by
    // calling stopSolve(), it is now up to PETSc to return a
    // "diverged" reason during the next solve.
  }
  _communicator.min(damping);
  if (has_active_dampers && damping < 1.0)
    _console << " Damping factor: " << damping << std::endl;
  return damping;
}
Referenced by FEProblemBase::computeDamping().
computeDiracContributions()
void NonlinearSystemBase::computeDiracContributions (const std::set< TagID > & tags, bool is_jacobian) protected inherited
Definition at line 3175 of file NonlinearSystemBase.C.
{
  _fe_problem.clearDiracInfo();
  std::set<const Elem *> dirac_elements;
  if (_dirac_kernels.hasActiveObjects())
  {
    TIME_SECTION("computeDirac", 3, "Computing DiracKernels");
    // TODO: Need a threading fix... but it's complicated!
    for (THREAD_ID tid = 0; tid < libMesh::n_threads(); ++tid)
    {
      const auto & dkernels = _dirac_kernels.getActiveObjects(tid);
      for (const auto & dkernel : dkernels)
      {
        dkernel->clearPoints();
        dkernel->addPoints();
      }
    }
    ComputeDiracThread cd(_fe_problem, tags, is_jacobian);
    _fe_problem.getDiracElements(dirac_elements);
    DistElemRange range(dirac_elements.begin(), dirac_elements.end(), 1);
    // TODO: Make Dirac work thread!
    // Threads::parallel_reduce(range, cd);
    cd(range);
  }
}
Referenced by NonlinearSystemBase::computeJacobianInternal(), and NonlinearSystemBase::computeResidualInternal().
computedScalingJacobian()
bool NonlinearSystemBase::computedScalingJacobian () const inline inherited
Definition at line 72 of file NonlinearSystemBase.h.
{ return _computed_scaling; }
computeJacobian() [1/2]
void NonlinearSystemBase::computeJacobian (SparseMatrix< Number > & jacobian) inherited
Take all tags in the system, and form a matrix for all tags in the system.
Definition at line 2933 of file NonlinearSystemBase.C.
{
  _nl_matrix_tags.clear();
  auto & tags = _fe_problem.getMatrixTags();
  for (auto & tag : tags)
    _nl_matrix_tags.insert(tag.second);
  computeJacobian(jacobian, _nl_matrix_tags);
}
computeJacobian() [2/2]
void NonlinearSystemBase::computeJacobian (SparseMatrix< Number > & jacobian, const std::set< TagID > & tags) inherited
Associate jacobian to systemMatrixTag, and then form a matrix for all the tags.
Definition at line 2946 of file NonlinearSystemBase.C.
{
  associateMatrixToTag(jacobian, systemMatrixTag());
  computeJacobianTags(tags);
  disassociateMatrixFromTag(jacobian, systemMatrixTag());
}
Referenced by NonlinearSystemBase::computeJacobian().
computeJacobianBlocks() [1/2]
void NonlinearSystemBase::computeJacobianBlocks (std::vector< JacobianBlock * > & blocks) inherited
Computes several Jacobian blocks simultaneously, summing their contributions into smaller preconditioning matrices.
Used by Physics-based preconditioning
Parameters
blocks The blocks to fill in (JacobianBlock is defined in ComputeJacobianBlocksThread)
Definition at line 2975 of file NonlinearSystemBase.C.
{
  _nl_matrix_tags.clear();
  auto & tags = _fe_problem.getMatrixTags();
  for (auto & tag : tags)
    _nl_matrix_tags.insert(tag.second);
  computeJacobianBlocks(blocks, _nl_matrix_tags);
}
Referenced by NonlinearSystemBase::computeJacobianBlocks(), FEProblemBase::computeJacobianBlocks(), and EigenProblem::computeJacobianBlocks().
computeJacobianBlocks() [2/2]
void NonlinearSystemBase::computeJacobianBlocks (std::vector< JacobianBlock * > & blocks, const std::set< TagID > & tags) inherited
Definition at line 2987 of file NonlinearSystemBase.C.
{
  TIME_SECTION("computeJacobianBlocks", 3);
  FloatingPointExceptionGuard fpe_guard(_app);
  for (unsigned int i = 0; i < blocks.size(); i++)
  {
    SparseMatrix<Number> & jacobian = blocks[i]->_jacobian;
    MatSetOption(static_cast<PetscMatrix<Number> &>(jacobian).mat(),
                 MAT_KEEP_NONZERO_PATTERN, // This is changed in 3.1
                 PETSC_TRUE);
    if (!_fe_problem.errorOnJacobianNonzeroReallocation())
      MatSetOption(static_cast<PetscMatrix<Number> &>(jacobian).mat(),
                   MAT_NEW_NONZERO_ALLOCATION_ERR,
                   PETSC_TRUE);
    jacobian.zero();
  }
  for (unsigned int tid = 0; tid < libMesh::n_threads(); tid++)
    _fe_problem.reinitScalars(tid);
  PARALLEL_TRY
  {
    ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();
    ComputeJacobianBlocksThread cjb(_fe_problem, blocks, tags);
    Threads::parallel_reduce(elem_range, cjb);
  }
  PARALLEL_CATCH;
  for (unsigned int i = 0; i < blocks.size(); i++)
    blocks[i]->_jacobian.close();
  for (unsigned int i = 0; i < blocks.size(); i++)
  {
    libMesh::System & precond_system = blocks[i]->_precond_system;
    SparseMatrix<Number> & jacobian = blocks[i]->_jacobian;
    unsigned int ivar = blocks[i]->_ivar;
    unsigned int jvar = blocks[i]->_jvar;
    // Dirichlet BCs
    std::vector<numeric_index_type> zero_rows;
    PARALLEL_TRY
    {
      ConstBndNodeRange & bnd_nodes = *_mesh.getBoundaryNodeRange();
      for (const auto & bnode : bnd_nodes)
      {
        BoundaryID boundary_id = bnode->_bnd_id;
        Node * node = bnode->_node;
        if (_nodal_bcs.hasActiveBoundaryObjects(boundary_id))
        {
          const auto & bcs = _nodal_bcs.getActiveBoundaryObjects(boundary_id);
          if (node->processor_id() == processor_id())
          {
            _fe_problem.reinitNodeFace(node, boundary_id, 0);
            for (const auto & bc : bcs)
              if (bc->variable().number() == ivar && bc->shouldApply())
              {
                // The first zero is for the variable number... there is only one variable in
                // each mini-system The second zero only works with Lagrange elements!
                zero_rows.push_back(node->dof_number(precond_system.number(), 0, 0));
              }
          }
        }
      }
    }
    PARALLEL_CATCH;
    jacobian.close();
    // This zeroes the rows corresponding to Dirichlet BCs and puts a 1.0 on the diagonal
    if (ivar == jvar)
      jacobian.zero_rows(zero_rows, 1.0);
    else
      jacobian.zero_rows(zero_rows, 0.0);
    jacobian.close();
  }
}
computeJacobianInternal()
void NonlinearSystemBase::computeJacobianInternal (const std::set< TagID > & tags) protected inherited
Form multiple matrices for all the tags.
Users should not call this func directly.
Definition at line 2597 of file NonlinearSystemBase.C.
{
  TIME_SECTION("computeJacobianInternal", 3);
  _fe_problem.setCurrentNonlinearSystem(number());
  // Make matrix ready to use
  activeAllMatrixTags();
  for (auto tag : tags)
  {
    if (!hasMatrix(tag))
      continue;
    auto & jacobian = getMatrix(tag);
    // Necessary for speed
    if (auto petsc_matrix = dynamic_cast<PetscMatrix<Number> *>(&jacobian))
    {
      MatSetOption(petsc_matrix->mat(),
                   MAT_KEEP_NONZERO_PATTERN, // This is changed in 3.1
                   PETSC_TRUE);
      if (!_fe_problem.errorOnJacobianNonzeroReallocation())
        MatSetOption(petsc_matrix->mat(), MAT_NEW_NONZERO_ALLOCATION_ERR, PETSC_FALSE);
    }
  }
  jacobianSetup();
  // Jacobian contributions from UOs - for now this is used for ray tracing
  // and ray kernels that contribute to the Jacobian (think line sources)
  std::vector<UserObject *> uos;
  _fe_problem.theWarehouse()
      .query()
      .condition<AttribSystem>("UserObject")
      .condition<AttribExecOns>(EXEC_PRE_KERNELS)
      .queryInto(uos);
  for (auto & uo : uos)
    uo->jacobianSetup();
  for (auto & uo : uos)
  {
    uo->initialize();
    uo->execute();
    uo->finalize();
  }
  // reinit scalar variables
  for (unsigned int tid = 0; tid < libMesh::n_threads(); tid++)
    _fe_problem.reinitScalars(tid);
  PARALLEL_TRY
  {
    // We would like to compute ScalarKernels, block NodalKernels, FVFluxKernels, and mortar objects
    // up front because we want these included whether we are computing an ordinary Jacobian or a
    // Jacobian for determining variable scaling factors
    computeScalarKernelsJacobians(tags);
    // Block restricted Nodal Kernels
    if (_nodal_kernels.hasActiveBlockObjects())
    {
      ComputeNodalKernelJacobiansThread cnkjt(_fe_problem, *this, _nodal_kernels, tags);
      ConstNodeRange & range = *_mesh.getLocalNodeRange();
      Threads::parallel_reduce(range, cnkjt);
      unsigned int n_threads = libMesh::n_threads();
      for (unsigned int i = 0; i < n_threads;
           i++) // Add any cached jacobians that might be hanging around
        _fe_problem.assembly(i, number()).addCachedJacobian(Assembly::GlobalDataKey{});
    }
    using FVRange = StoredRange<MooseMesh::const_face_info_iterator, const FaceInfo *>;
    if (_fe_problem.haveFV())
    {
      // the same loop works for both residual and jacobians because it keys
      // off of FEProblem's _currently_computing_jacobian parameter
      ComputeFVFluxJacobianThread<FVRange> fvj(
          _fe_problem, this->number(), tags, /*on_displaced=*/false);
      FVRange faces(_fe_problem.mesh().ownedFaceInfoBegin(), _fe_problem.mesh().ownedFaceInfoEnd());
      Threads::parallel_reduce(faces, fvj);
    }
    if (auto displaced_problem = _fe_problem.getDisplacedProblem();
        displaced_problem && displaced_problem->haveFV())
    {
      ComputeFVFluxJacobianThread<FVRange> fvr(
          _fe_problem, this->number(), tags, /*on_displaced=*/true);
      FVRange faces(displaced_problem->mesh().ownedFaceInfoBegin(),
                    displaced_problem->mesh().ownedFaceInfoEnd());
      Threads::parallel_reduce(faces, fvr);
    }
    mortarConstraints(Moose::ComputeType::Jacobian, {}, tags);
    // Get our element range for looping over
    ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();
    if (_fe_problem.computingScalingJacobian())
    {
      // Only compute Jacobians corresponding to the diagonals of volumetric compute objects
      // because this typically gives us a good representation of the physics. NodalBCs and
      // Constraints can introduce dramatically different scales (often order unity).
      // IntegratedBCs and/or InterfaceKernels may use penalty factors. DGKernels may be ok, but
      // they are almost always used in conjunction with Kernels
      ComputeJacobianForScalingThread cj(_fe_problem, tags);
      Threads::parallel_reduce(elem_range, cj);
      unsigned int n_threads = libMesh::n_threads();
      for (unsigned int i = 0; i < n_threads;
           i++) // Add any Jacobian contributions still hanging around
        _fe_problem.addCachedJacobian(i);
      closeTaggedMatrices(tags);
      return;
    }
    switch (_fe_problem.coupling())
    {
      case Moose::COUPLING_DIAG:
      {
        ComputeJacobianThread cj(_fe_problem, tags);
        Threads::parallel_reduce(elem_range, cj);
        unsigned int n_threads = libMesh::n_threads();
        for (unsigned int i = 0; i < n_threads;
             i++) // Add any Jacobian contributions still hanging around
          _fe_problem.addCachedJacobian(i);
        // Boundary restricted Nodal Kernels
        if (_nodal_kernels.hasActiveBoundaryObjects())
        {
          ComputeNodalKernelBCJacobiansThread cnkjt(_fe_problem, *this, _nodal_kernels, tags);
          ConstBndNodeRange & bnd_range = *_mesh.getBoundaryNodeRange();
          Threads::parallel_reduce(bnd_range, cnkjt);
          unsigned int n_threads = libMesh::n_threads();
          for (unsigned int i = 0; i < n_threads;
               i++) // Add any cached jacobians that might be hanging around
            _fe_problem.assembly(i, number()).addCachedJacobian(Assembly::GlobalDataKey{});
        }
      }
      break;
      default:
      case Moose::COUPLING_CUSTOM:
      {
        ComputeFullJacobianThread cj(_fe_problem, tags);
        Threads::parallel_reduce(elem_range, cj);
        unsigned int n_threads = libMesh::n_threads();
        for (unsigned int i = 0; i < n_threads; i++)
          _fe_problem.addCachedJacobian(i);
        // Boundary restricted Nodal Kernels
        if (_nodal_kernels.hasActiveBoundaryObjects())
        {
          ComputeNodalKernelBCJacobiansThread cnkjt(_fe_problem, *this, _nodal_kernels, tags);
          ConstBndNodeRange & bnd_range = *_mesh.getBoundaryNodeRange();
          Threads::parallel_reduce(bnd_range, cnkjt);
          unsigned int n_threads = libMesh::n_threads();
          for (unsigned int i = 0; i < n_threads;
               i++) // Add any cached jacobians that might be hanging around
            _fe_problem.assembly(i, number()).addCachedJacobian(Assembly::GlobalDataKey{});
        }
      }
      break;
    }
    computeDiracContributions(tags, true);
    static bool first = true;
    // This adds zeroes into geometric coupling entries to ensure they stay in the matrix
    if (first && (_add_implicit_geometric_coupling_entries_to_jacobian))
    {
      first = false;
      addImplicitGeometricCouplingEntries(_fe_problem.geomSearchData());
      if (_fe_problem.getDisplacedProblem())
        addImplicitGeometricCouplingEntries(_fe_problem.getDisplacedProblem()->geomSearchData());
    }
  }
  PARALLEL_CATCH;
  // Have no idea how to have constraints work
  // with the tag system
  PARALLEL_TRY
  {
    // Add in Jacobian contributions from other Constraints
    if (_fe_problem._has_constraints)
    {
      // Some constraints need values from the Jacobian
      closeTaggedMatrices(tags);
      // Nodal Constraints
      enforceNodalConstraintsJacobian();
      // Undisplaced Constraints
      constraintJacobians(false);
      // Displaced Constraints
      if (_fe_problem.getDisplacedProblem())
        constraintJacobians(true);
    }
  }
  PARALLEL_CATCH;
  // We need to close the save_in variables on the aux system before NodalBCBases clear the dofs
  // on boundary nodes
  if (_has_diag_save_in)
    _fe_problem.getAuxiliarySystem().solution().close();
  PARALLEL_TRY
  {
    MooseObjectWarehouse<NodalBCBase> * nbc_warehouse;
    // Select nodal kernels
    if (tags.size() == _fe_problem.numMatrixTags() || !tags.size())
      nbc_warehouse = &_nodal_bcs;
    else if (tags.size() == 1)
      nbc_warehouse = &(_nodal_bcs.getMatrixTagObjectWarehouse(*(tags.begin()), 0));
    else
      nbc_warehouse = &(_nodal_bcs.getMatrixTagsObjectWarehouse(tags, 0));
    if (nbc_warehouse->hasActiveObjects())
    {
      // We may be switching from add to set. Moreover, we rely on a call to MatZeroRows to enforce
      // the nodal boundary condition constraints which requires that the matrix be truly assembled
      // as opposed to just flushed. Consequently we can't do the following despite any desire to
      // keep our initial sparsity pattern honored (see https://gitlab.com/petsc/petsc/-/issues/852)
      //
      // flushTaggedMatrices(tags);
      closeTaggedMatrices(tags);
      // Cache the information about which BCs are coupled to which
      // variables, so we don't have to figure it out for each node.
      std::map<std::string, std::set<unsigned int>> bc_involved_vars;
      const std::set<BoundaryID> & all_boundary_ids = _mesh.getBoundaryIDs();
      for (const auto & bid : all_boundary_ids)
      {
        // Get reference to all the NodalBCs for this ID.  This is only
        // safe if there are NodalBCBases there to be gotten...
        if (nbc_warehouse->hasActiveBoundaryObjects(bid))
        {
          const auto & bcs = nbc_warehouse->getActiveBoundaryObjects(bid);
          for (const auto & bc : bcs)
          {
            const std::vector<MooseVariableFEBase *> & coupled_moose_vars =
                bc->getCoupledMooseVars();
            // Create the set of "involved" MOOSE nonlinear vars, which includes all coupled vars
            // and the BC's own variable
            std::set<unsigned int> & var_set = bc_involved_vars[bc->name()];
            for (const auto & coupled_var : coupled_moose_vars)
              if (coupled_var->kind() == Moose::VAR_NONLINEAR)
                var_set.insert(coupled_var->number());
            var_set.insert(bc->variable().number());
          }
        }
      }
      // reinit scalar variables again. This reinit does not re-fill any of the scalar variable
      // solution arrays because that was done above. It only will reorder the derivative
      // information for AD calculations to be suitable for NodalBC calculations
      for (unsigned int tid = 0; tid < libMesh::n_threads(); tid++)
        _fe_problem.reinitScalars(tid, true);
      // Get variable coupling list.  We do all the NodalBCBase stuff on
      // thread 0...  The couplingEntries() data structure determines
      // which variables are "coupled" as far as the preconditioner is
      // concerned, not what variables a boundary condition specifically
      // depends on.
      auto & coupling_entries = _fe_problem.couplingEntries(/*_tid=*/0, this->number());
      // Compute Jacobians for NodalBCBases
      ConstBndNodeRange & bnd_nodes = *_mesh.getBoundaryNodeRange();
      for (const auto & bnode : bnd_nodes)
      {
        BoundaryID boundary_id = bnode->_bnd_id;
        Node * node = bnode->_node;
        if (nbc_warehouse->hasActiveBoundaryObjects(boundary_id) &&
            node->processor_id() == processor_id())
        {
          _fe_problem.reinitNodeFace(node, boundary_id, 0);
          const auto & bcs = nbc_warehouse->getActiveBoundaryObjects(boundary_id);
          for (const auto & bc : bcs)
          {
            // Get the set of involved MOOSE vars for this BC
            std::set<unsigned int> & var_set = bc_involved_vars[bc->name()];
            // Loop over all the variables whose Jacobian blocks are
            // actually being computed, call computeOffDiagJacobian()
            // for each one which is actually coupled (otherwise the
            // value is zero.)
            for (const auto & it : coupling_entries)
            {
              unsigned int ivar = it.first->number(), jvar = it.second->number();
              // We are only going to call computeOffDiagJacobian() if:
              // 1.) the BC's variable is ivar
              // 2.) jvar is "involved" with the BC (including jvar==ivar), and
              // 3.) the BC should apply.
              if ((bc->variable().number() == ivar) && var_set.count(jvar) && bc->shouldApply())
                bc->computeOffDiagJacobian(jvar);
            }
            const auto & coupled_scalar_vars = bc->getCoupledMooseScalarVars();
            for (const auto & jvariable : coupled_scalar_vars)
              if (hasScalarVariable(jvariable->name()))
                bc->computeOffDiagJacobianScalar(jvariable->number());
          }
        }
      } // end loop over boundary nodes
      // Set the cached NodalBCBase values in the Jacobian matrix
      _fe_problem.assembly(0, number()).setCachedJacobian(Assembly::GlobalDataKey{});
    }
  }
  PARALLEL_CATCH;
  closeTaggedMatrices(tags);
  // We need to close the save_in variables on the aux system before NodalBCBases clear the dofs
  // on boundary nodes
  if (_has_nodalbc_diag_save_in)
    _fe_problem.getAuxiliarySystem().solution().close();
  if (hasDiagSaveIn())
    _fe_problem.getAuxiliarySystem().update();
  // Accumulate the occurrence of solution invalid warnings for the current iteration cumulative
  // counters
  _app.solutionInvalidity().solutionInvalidAccumulation();
}
Referenced by NonlinearSystemBase::computeJacobianTags().
computeJacobianTags()
void NonlinearSystemBase::computeJacobianTags (const std::set< TagID > & tags) inherited
Computes multiple (tag associated) Jacobian matricese.
Definition at line 2956 of file NonlinearSystemBase.C.
{
  TIME_SECTION("computeJacobianTags", 5);
  FloatingPointExceptionGuard fpe_guard(_app);
  try
  {
    computeJacobianInternal(tags);
  }
  catch (MooseException & e)
  {
    // The buck stops here, we have already handled the exception by
    // calling stopSolve(), it is now up to PETSc to return a
    // "diverged" reason during the next solve.
  }
}
Referenced by NonlinearSystemBase::computeJacobian(), and FEProblemBase::computeJacobianTags().
computeNodalBCs() [1/3]
void NonlinearSystemBase::computeNodalBCs (const std::set< TagID > & tags) protected inherited
Form multiple tag-associated residual vectors for the given tags.
Definition at line 1867 of file NonlinearSystemBase.C.
{
  // We need to close the diag_save_in variables on the aux system before NodalBCBases clear the
  // dofs on boundary nodes
  if (_has_save_in)
    _fe_problem.getAuxiliarySystem().solution().close();
  PARALLEL_TRY
  {
    ConstBndNodeRange & bnd_nodes = *_mesh.getBoundaryNodeRange();
    if (!bnd_nodes.empty())
    {
      TIME_SECTION("NodalBCs", 3 /*, "Computing NodalBCs"*/);
      MooseObjectWarehouse<NodalBCBase> * nbc_warehouse;
      // Select nodal kernels
      if (tags.size() == _fe_problem.numVectorTags(Moose::VECTOR_TAG_RESIDUAL) || !tags.size())
        nbc_warehouse = &_nodal_bcs;
      else if (tags.size() == 1)
        nbc_warehouse = &(_nodal_bcs.getVectorTagObjectWarehouse(*(tags.begin()), 0));
      else
        nbc_warehouse = &(_nodal_bcs.getVectorTagsObjectWarehouse(tags, 0));
      for (const auto & bnode : bnd_nodes)
      {
        BoundaryID boundary_id = bnode->_bnd_id;
        Node * node = bnode->_node;
        if (node->processor_id() == processor_id())
        {
          // reinit variables in nodes
          _fe_problem.reinitNodeFace(node, boundary_id, 0);
          if (nbc_warehouse->hasActiveBoundaryObjects(boundary_id))
          {
            const auto & bcs = nbc_warehouse->getActiveBoundaryObjects(boundary_id);
            for (const auto & nbc : bcs)
              if (nbc->shouldApply())
                nbc->computeResidual();
          }
        }
      }
    }
  }
  PARALLEL_CATCH;
  if (_Re_time)
    _Re_time->close();
  _Re_non_time->close();
}
computeNodalBCs() [2/3]
void NonlinearSystemBase::computeNodalBCs (NumericVector< Number > & residual) protected inherited
Enforces nodal boundary conditions.
The boundary condition will be implemented in the residual using all the tags in the system.
Definition at line 1843 of file NonlinearSystemBase.C.
{
  _nl_vector_tags.clear();
  const auto & residual_vector_tags = _fe_problem.getVectorTags(Moose::VECTOR_TAG_RESIDUAL);
  for (const auto & residual_vector_tag : residual_vector_tags)
    _nl_vector_tags.insert(residual_vector_tag._id);
  associateVectorToTag(residual, residualVectorTag());
  computeNodalBCs(residual, _nl_vector_tags);
  disassociateVectorFromTag(residual, residualVectorTag());
}
Referenced by NonlinearSystemBase::computeNodalBCs(), and NonlinearSystemBase::computeResidualTags().
computeNodalBCs() [3/3]
void NonlinearSystemBase::computeNodalBCs (NumericVector< Number > & residual, const std::set< TagID > & tags) protected inherited
Form a residual for BCs that at least has one of the given tags.
Definition at line 1857 of file NonlinearSystemBase.C.
{
  associateVectorToTag(residual, residualVectorTag());
  computeNodalBCs(tags);
  disassociateVectorFromTag(residual, residualVectorTag());
}
computeNodalBCsResidualAndJacobian()
void NonlinearSystemBase::computeNodalBCsResidualAndJacobian () protected inherited
compute the residual and Jacobian for nodal boundary conditions
Definition at line 1920 of file NonlinearSystemBase.C.
{
  PARALLEL_TRY
  {
    ConstBndNodeRange & bnd_nodes = *_mesh.getBoundaryNodeRange();
    if (!bnd_nodes.empty())
    {
      TIME_SECTION("NodalBCs", 3 /*, "Computing NodalBCs"*/);
      for (const auto & bnode : bnd_nodes)
      {
        BoundaryID boundary_id = bnode->_bnd_id;
        Node * node = bnode->_node;
        if (node->processor_id() == processor_id())
        {
          // reinit variables in nodes
          _fe_problem.reinitNodeFace(node, boundary_id, 0);
          if (_nodal_bcs.hasActiveBoundaryObjects(boundary_id))
          {
            const auto & bcs = _nodal_bcs.getActiveBoundaryObjects(boundary_id);
            for (const auto & nbc : bcs)
              if (nbc->shouldApply())
                nbc->computeResidualAndJacobian();
          }
        }
      }
    }
  }
  PARALLEL_CATCH;
  // Set the cached NodalBCBase values in the Jacobian matrix
  _fe_problem.assembly(0, number()).setCachedJacobian(Assembly::GlobalDataKey{});
}
Referenced by NonlinearSystemBase::computeResidualAndJacobianTags().
computeResidual()
void NonlinearSystemBase::computeResidual (NumericVector< Number > & residual, TagID tag_id) inherited
Form a residual vector for a given tag.
Definition at line 746 of file NonlinearSystemBase.C.
{
  mooseDeprecated(" Please use computeResidualTag");
  computeResidualTag(residual, tag_id);
}
computeResidualAndJacobianInternal()
void NonlinearSystemBase::computeResidualAndJacobianInternal (const std::set< TagID > & vector_tags, const std::set< TagID > & matrix_tags) inherited
Compute residual and Jacobian from contributions not related to constraints, such as nodal boundary conditions.
Definition at line 1753 of file NonlinearSystemBase.C.
{
  TIME_SECTION("computeResidualAndJacobianInternal", 3);
  // Make matrix ready to use
  activeAllMatrixTags();
  for (auto tag : matrix_tags)
  {
    if (!hasMatrix(tag))
      continue;
    auto & jacobian = getMatrix(tag);
    // Necessary for speed
    if (auto petsc_matrix = dynamic_cast<PetscMatrix<Number> *>(&jacobian))
    {
      MatSetOption(petsc_matrix->mat(),
                   MAT_KEEP_NONZERO_PATTERN, // This is changed in 3.1
                   PETSC_TRUE);
      if (!_fe_problem.errorOnJacobianNonzeroReallocation())
        MatSetOption(petsc_matrix->mat(), MAT_NEW_NONZERO_ALLOCATION_ERR, PETSC_FALSE);
    }
  }
  residualSetup();
  // Residual contributions from UOs - for now this is used for ray tracing
  // and ray kernels that contribute to the residual (think line sources)
  std::vector<UserObject *> uos;
  _fe_problem.theWarehouse()
      .query()
      .condition<AttribSystem>("UserObject")
      .condition<AttribExecOns>(EXEC_PRE_KERNELS)
      .queryInto(uos);
  for (auto & uo : uos)
    uo->residualSetup();
  for (auto & uo : uos)
  {
    uo->initialize();
    uo->execute();
    uo->finalize();
  }
  // reinit scalar variables
  for (unsigned int tid = 0; tid < libMesh::n_threads(); tid++)
    _fe_problem.reinitScalars(tid);
  // residual contributions from the domain
  PARALLEL_TRY
  {
    TIME_SECTION("Kernels", 3 /*, "Computing Kernels"*/);
    ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();
    ComputeResidualAndJacobianThread crj(_fe_problem, vector_tags, matrix_tags);
    Threads::parallel_reduce(elem_range, crj);
    using FVRange = StoredRange<MooseMesh::const_face_info_iterator, const FaceInfo *>;
    if (_fe_problem.haveFV())
    {
      ComputeFVFluxRJThread<FVRange> fvrj(
          _fe_problem, this->number(), vector_tags, matrix_tags, /*on_displaced=*/false);
      FVRange faces(_fe_problem.mesh().ownedFaceInfoBegin(), _fe_problem.mesh().ownedFaceInfoEnd());
      Threads::parallel_reduce(faces, fvrj);
    }
    if (auto displaced_problem = _fe_problem.getDisplacedProblem();
        displaced_problem && displaced_problem->haveFV())
    {
      ComputeFVFluxRJThread<FVRange> fvr(
          _fe_problem, this->number(), vector_tags, matrix_tags, /*on_displaced=*/true);
      FVRange faces(displaced_problem->mesh().ownedFaceInfoBegin(),
                    displaced_problem->mesh().ownedFaceInfoEnd());
      Threads::parallel_reduce(faces, fvr);
    }
    mortarConstraints(Moose::ComputeType::ResidualAndJacobian, vector_tags, matrix_tags);
    unsigned int n_threads = libMesh::n_threads();
    for (unsigned int i = 0; i < n_threads;
         i++) // Add any cached residuals that might be hanging around
    {
      _fe_problem.addCachedResidual(i);
      _fe_problem.addCachedJacobian(i);
    }
  }
  PARALLEL_CATCH;
}
Referenced by NonlinearSystemBase::computeResidualAndJacobianTags().
computeResidualAndJacobianTags()
void NonlinearSystemBase::computeResidualAndJacobianTags (const std::set< TagID > & vector_tags, const std::set< TagID > & matrix_tags) inherited
Form possibly multiple tag-associated vectors and matrices.
Definition at line 831 of file NonlinearSystemBase.C.
{
  const bool required_residual =
      vector_tags.find(residualVectorTag()) == vector_tags.end() ? false : true;
  try
  {
    zeroTaggedVectors(vector_tags);
    computeResidualAndJacobianInternal(vector_tags, matrix_tags);
    closeTaggedVectors(vector_tags);
    closeTaggedMatrices(matrix_tags);
    if (required_residual)
    {
      auto & residual = getVector(residualVectorTag());
      if (_time_integrator)
        _time_integrator->postResidual(residual);
      else
        residual += *_Re_non_time;
      residual.close();
    }
    computeNodalBCsResidualAndJacobian();
    closeTaggedVectors(vector_tags);
    closeTaggedMatrices(matrix_tags);
  }
  catch (MooseException & e)
  {
    // The buck stops here, we have already handled the exception by
    // calling stopSolve(), it is now up to PETSc to return a
    // "diverged" reason during the next solve.
  }
}
Referenced by FEProblemBase::computeResidualAndJacobian().
computeResidualInternal()
void NonlinearSystemBase::computeResidualInternal (const std::set< TagID > & tags) protected inherited
Compute the residual for a given tag.
Parameters
tags The tags of kernels for which the residual is to be computed.
Definition at line 1534 of file NonlinearSystemBase.C.
{
  parallel_object_only();
  TIME_SECTION("computeResidualInternal", 3);
  residualSetup();
  const auto vector_tag_data = _fe_problem.getVectorTags(tags);
  // Residual contributions from UOs - for now this is used for ray tracing
  // and ray kernels that contribute to the residual (think line sources)
  std::vector<UserObject *> uos;
  _fe_problem.theWarehouse()
      .query()
      .condition<AttribSystem>("UserObject")
      .condition<AttribExecOns>(EXEC_PRE_KERNELS)
      .queryInto(uos);
  for (auto & uo : uos)
    uo->residualSetup();
  for (auto & uo : uos)
  {
    uo->initialize();
    uo->execute();
    uo->finalize();
  }
  // reinit scalar variables
  for (unsigned int tid = 0; tid < libMesh::n_threads(); tid++)
    _fe_problem.reinitScalars(tid);
  // residual contributions from the domain
  PARALLEL_TRY
  {
    TIME_SECTION("Kernels", 3 /*, "Computing Kernels"*/);
    ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();
    ComputeResidualThread cr(_fe_problem, tags);
    Threads::parallel_reduce(elem_range, cr);
    // We pass face information directly to FV residual objects for their evaluation. Consequently
    // we must make sure to do separate threaded loops for 1) undisplaced face information objects
    // and undisplaced residual objects and 2) displaced face information objects and displaced
    // residual objects
    using FVRange = StoredRange<MooseMesh::const_face_info_iterator, const FaceInfo *>;
    if (_fe_problem.haveFV())
    {
      ComputeFVFluxResidualThread<FVRange> fvr(
          _fe_problem, this->number(), tags, /*on_displaced=*/false);
      FVRange faces(_fe_problem.mesh().ownedFaceInfoBegin(), _fe_problem.mesh().ownedFaceInfoEnd());
      Threads::parallel_reduce(faces, fvr);
    }
    if (auto displaced_problem = _fe_problem.getDisplacedProblem();
        displaced_problem && displaced_problem->haveFV())
    {
      ComputeFVFluxResidualThread<FVRange> fvr(
          _fe_problem, this->number(), tags, /*on_displaced=*/true);
      FVRange faces(displaced_problem->mesh().ownedFaceInfoBegin(),
                    displaced_problem->mesh().ownedFaceInfoEnd());
      Threads::parallel_reduce(faces, fvr);
    }
    unsigned int n_threads = libMesh::n_threads();
    for (unsigned int i = 0; i < n_threads;
         i++) // Add any cached residuals that might be hanging around
      _fe_problem.addCachedResidual(i);
  }
  PARALLEL_CATCH;
  // residual contributions from the scalar kernels
  PARALLEL_TRY
  {
    // do scalar kernels (not sure how to thread this)
    if (_scalar_kernels.hasActiveObjects())
    {
      TIME_SECTION("ScalarKernels", 3 /*, "Computing ScalarKernels"*/);
      MooseObjectWarehouse<ScalarKernelBase> * scalar_kernel_warehouse;
      // This code should be refactored once we can do tags for scalar
      // kernels
      // Should redo this based on Warehouse
      if (!tags.size() || tags.size() == _fe_problem.numVectorTags(Moose::VECTOR_TAG_RESIDUAL))
        scalar_kernel_warehouse = &_scalar_kernels;
      else if (tags.size() == 1)
        scalar_kernel_warehouse =
            &(_scalar_kernels.getVectorTagObjectWarehouse(*(tags.begin()), 0));
      else
        // scalar_kernels is not threading
        scalar_kernel_warehouse = &(_scalar_kernels.getVectorTagsObjectWarehouse(tags, 0));
      bool have_scalar_contributions = false;
      const auto & scalars = scalar_kernel_warehouse->getActiveObjects();
      for (const auto & scalar_kernel : scalars)
      {
        scalar_kernel->reinit();
        const std::vector<dof_id_type> & dof_indices = scalar_kernel->variable().dofIndices();
        const DofMap & dof_map = scalar_kernel->variable().dofMap();
        const dof_id_type first_dof = dof_map.first_dof();
        const dof_id_type end_dof = dof_map.end_dof();
        for (dof_id_type dof : dof_indices)
        {
          if (dof >= first_dof && dof < end_dof)
          {
            scalar_kernel->computeResidual();
            have_scalar_contributions = true;
            break;
          }
        }
      }
      if (have_scalar_contributions)
        _fe_problem.addResidualScalar();
    }
  }
  PARALLEL_CATCH;
  // residual contributions from Block NodalKernels
  PARALLEL_TRY
  {
    if (_nodal_kernels.hasActiveBlockObjects())
    {
      TIME_SECTION("NodalKernels", 3 /*, "Computing NodalKernels"*/);
      ComputeNodalKernelsThread cnk(_fe_problem, _nodal_kernels, tags);
      ConstNodeRange & range = *_mesh.getLocalNodeRange();
      if (range.begin() != range.end())
      {
        _fe_problem.reinitNode(*range.begin(), 0);
        Threads::parallel_reduce(range, cnk);
        unsigned int n_threads = libMesh::n_threads();
        for (unsigned int i = 0; i < n_threads;
             i++) // Add any cached residuals that might be hanging around
          _fe_problem.addCachedResidual(i);
      }
    }
  }
  PARALLEL_CATCH;
  if (_fe_problem.computingScalingResidual())
    // We computed the volumetric objects. We can return now before we get into
    // any strongly enforced constraint conditions or penalty-type objects
    // (DGKernels, IntegratedBCs, InterfaceKernels, Constraints)
    return;
  // residual contributions from boundary NodalKernels
  PARALLEL_TRY
  {
    if (_nodal_kernels.hasActiveBoundaryObjects())
    {
      TIME_SECTION("NodalKernelBCs", 3 /*, "Computing NodalKernelBCs"*/);
      ComputeNodalKernelBcsThread cnk(_fe_problem, _nodal_kernels, tags);
      ConstBndNodeRange & bnd_node_range = *_mesh.getBoundaryNodeRange();
      Threads::parallel_reduce(bnd_node_range, cnk);
      unsigned int n_threads = libMesh::n_threads();
      for (unsigned int i = 0; i < n_threads;
           i++) // Add any cached residuals that might be hanging around
        _fe_problem.addCachedResidual(i);
    }
  }
  PARALLEL_CATCH;
  mortarConstraints(Moose::ComputeType::Residual, tags, {});
  if (_residual_copy.get())
  {
    _Re_non_time->close();
    _Re_non_time->localize(*_residual_copy);
  }
  if (_need_residual_ghosted)
  {
    _Re_non_time->close();
    *_residual_ghosted = *_Re_non_time;
    _residual_ghosted->close();
  }
  PARALLEL_TRY { computeDiracContributions(tags, false); }
  PARALLEL_CATCH;
  if (_fe_problem._has_constraints)
  {
    PARALLEL_TRY { enforceNodalConstraintsResidual(*_Re_non_time); }
    PARALLEL_CATCH;
    _Re_non_time->close();
  }
  // Add in Residual contributions from other Constraints
  if (_fe_problem._has_constraints)
  {
    PARALLEL_TRY
    {
      // Undisplaced Constraints
      constraintResiduals(*_Re_non_time, false);
      // Displaced Constraints
      if (_fe_problem.getDisplacedProblem())
        constraintResiduals(*_Re_non_time, true);
      if (_fe_problem.computingNonlinearResid())
        _constraints.residualEnd();
    }
    PARALLEL_CATCH;
    _Re_non_time->close();
  }
  // Accumulate the occurrence of solution invalid warnings for the current iteration cumulative
  // counters
  _app.solutionInvalidity().solutionInvalidAccumulation();
}
Referenced by NonlinearSystemBase::computeResidualTags().
computeResidualTag()
void NonlinearSystemBase::computeResidualTag (NumericVector< Number > & residual, TagID tag_id) inherited
Computes residual for a given tag.
Parameters
residual Residual is formed in here
the tag of kernels for which the residual is to be computed.
Definition at line 732 of file NonlinearSystemBase.C.
{
  _nl_vector_tags.clear();
  _nl_vector_tags.insert(tag_id);
  _nl_vector_tags.insert(residualVectorTag());
  associateVectorToTag(residual, residualVectorTag());
  computeResidualTags(_nl_vector_tags);
  disassociateVectorFromTag(residual, residualVectorTag());
}
Referenced by NonlinearSystemBase::computeResidual(), and CrankNicolson::init().
computeResidualTags()
void NonlinearSystemBase::computeResidualTags (const std::set< TagID > & tags) inherited
Form multiple tag-associated residual vectors for all the given tags.
Definition at line 754 of file NonlinearSystemBase.C.
{
  parallel_object_only();
  TIME_SECTION("nl::computeResidualTags", 5);
  _fe_problem.setCurrentNonlinearSystem(number());
  _fe_problem.setCurrentlyComputingResidual(true);
  bool required_residual = tags.find(residualVectorTag()) == tags.end() ? false : true;
  _n_residual_evaluations++;
  // not suppose to do anythin on matrix
  deactiveAllMatrixTags();
  FloatingPointExceptionGuard fpe_guard(_app);
  for (const auto & numeric_vec : _vecs_to_zero_for_residual)
    if (hasVector(numeric_vec))
    {
      NumericVector<Number> & vec = getVector(numeric_vec);
      vec.close();
      vec.zero();
    }
  try
  {
    zeroTaggedVectors(tags);
    computeResidualInternal(tags);
    closeTaggedVectors(tags);
    if (required_residual)
    {
      auto & residual = getVector(residualVectorTag());
      if (_time_integrator)
        _time_integrator->postResidual(residual);
      else
        residual += *_Re_non_time;
      residual.close();
    }
    if (_fe_problem.computingScalingResidual())
      // We don't want to do nodal bcs or anything else
      return;
    computeNodalBCs(tags);
    closeTaggedVectors(tags);
    // If we are debugging residuals we need one more assignment to have the ghosted copy up to
    // date
    if (_need_residual_ghosted && _debugging_residuals && required_residual)
    {
      auto & residual = getVector(residualVectorTag());
      *_residual_ghosted = residual;
      _residual_ghosted->close();
    }
    // Need to close and update the aux system in case residuals were saved to it.
    if (_has_nodalbc_save_in)
      _fe_problem.getAuxiliarySystem().solution().close();
    if (hasSaveIn())
      _fe_problem.getAuxiliarySystem().update();
  }
  catch (MooseException & e)
  {
    // The buck stops here, we have already handled the exception by
    // calling stopSolve(), it is now up to PETSc to return a
    // "diverged" reason during the next solve.
  }
  // not supposed to do anything on matrix
  activeAllMatrixTags();
  _fe_problem.setCurrentlyComputingResidual(false);
}
Referenced by NonlinearSystemBase::computeResidualTag(), and FEProblemBase::computeResidualTags().
computeScalarKernelsJacobians()
void NonlinearSystemBase::computeScalarKernelsJacobians (const std::set< TagID > & tags) protected inherited
Definition at line 2523 of file NonlinearSystemBase.C.
{
  MooseObjectWarehouse<ScalarKernelBase> * scalar_kernel_warehouse;
  if (!tags.size() || tags.size() == _fe_problem.numMatrixTags())
    scalar_kernel_warehouse = &_scalar_kernels;
  else if (tags.size() == 1)
    scalar_kernel_warehouse = &(_scalar_kernels.getMatrixTagObjectWarehouse(*(tags.begin()), 0));
  else
    scalar_kernel_warehouse = &(_scalar_kernels.getMatrixTagsObjectWarehouse(tags, 0));
  // Compute the diagonal block for scalar variables
  if (scalar_kernel_warehouse->hasActiveObjects())
  {
    const auto & scalars = scalar_kernel_warehouse->getActiveObjects();
    _fe_problem.reinitScalars(/*tid=*/0);
    _fe_problem.reinitOffDiagScalars(/*_tid*/ 0);
    bool have_scalar_contributions = false;
    for (const auto & kernel : scalars)
    {
      kernel->reinit();
      const std::vector<dof_id_type> & dof_indices = kernel->variable().dofIndices();
      const DofMap & dof_map = kernel->variable().dofMap();
      const dof_id_type first_dof = dof_map.first_dof();
      const dof_id_type end_dof = dof_map.end_dof();
      for (dof_id_type dof : dof_indices)
      {
        if (dof >= first_dof && dof < end_dof)
        {
          kernel->computeJacobian();
          _fe_problem.addJacobianOffDiagScalar(kernel->variable().number());
          have_scalar_contributions = true;
          break;
        }
      }
    }
    if (have_scalar_contributions)
      _fe_problem.addJacobianScalar();
  }
}
Referenced by NonlinearSystemBase::computeJacobianInternal().
computeScaling()
void NonlinearSystemBase::computeScaling () inherited
Method used to obtain scaling factors for variables.
Definition at line 3720 of file NonlinearSystemBase.C.
{
  _console << "\nPerforming automatic scaling calculation\n" << std::endl;
  TIME_SECTION("computeScaling", 3, "Computing Automatic Scaling");
  // It's funny but we need to assemble our vector of scaling factors here otherwise we will be
  // applying scaling factors of 0 during Assembly of our scaling Jacobian
  assembleScalingVector();
  // container for repeated access of element global dof indices
  std::vector<dof_id_type> dof_indices;
  if (!_auto_scaling_initd)
    setupScalingData();
  std::vector<Real> inverse_scaling_factors(_num_scaling_groups, 0);
  std::vector<Real> resid_inverse_scaling_factors(_num_scaling_groups, 0);
  std::vector<Real> jac_inverse_scaling_factors(_num_scaling_groups, 0);
  auto & dof_map = dofMap();
  // what types of scaling do we want?
  bool jac_scaling = _resid_vs_jac_scaling_param < 1. - TOLERANCE;
  bool resid_scaling = _resid_vs_jac_scaling_param > TOLERANCE;
  const NumericVector<Number> & scaling_residual = RHS();
  if (jac_scaling)
  {
    // if (!_auto_scaling_initd)
    // We need to reinit this when the number of dofs changes
    // but there is no good way to track that
    // In theory, it is the job of libmesh system to track this,
    // but this special matrix is not owned by libMesh system
    // Let us reinit eveytime since it is not expensive
    {
      auto init_vector = NumericVector<Number>::build(this->comm());
      init_vector->init(system().n_dofs(), system().n_local_dofs(), /*fast=*/false, PARALLEL);
      _scaling_matrix->clear();
      _scaling_matrix->init(*init_vector);
    }
    _fe_problem.computingScalingJacobian(true);
    // Dispatch to derived classes to ensure that we use the correct matrix tag
    computeScalingJacobian();
    _fe_problem.computingScalingJacobian(false);
  }
  if (resid_scaling)
  {
    _fe_problem.computingScalingResidual(true);
    _fe_problem.computingNonlinearResid(true);
    // Dispatch to derived classes to ensure that we use the correct vector tag
    computeScalingResidual();
    _fe_problem.computingNonlinearResid(false);
    _fe_problem.computingScalingResidual(false);
  }
  auto examine_dof_indices = [this,
                              jac_scaling,
                              resid_scaling,
                              &dof_map,
                              &jac_inverse_scaling_factors,
                              &resid_inverse_scaling_factors,
                              &scaling_residual](const auto & dof_indices, const auto var_number)
  {
    for (auto dof_index : dof_indices)
      if (dof_map.local_index(dof_index))
      {
        if (jac_scaling)
        {
          // For now we will use the diagonal for determining scaling
          auto mat_value = (*_scaling_matrix)(dof_index, dof_index);
          auto & factor = jac_inverse_scaling_factors[_var_to_group_var[var_number]];
          factor = std::max(factor, std::abs(mat_value));
        }
        if (resid_scaling)
        {
          auto vec_value = scaling_residual(dof_index);
          auto & factor = resid_inverse_scaling_factors[_var_to_group_var[var_number]];
          factor = std::max(factor, std::abs(vec_value));
        }
      }
  };
  // Compute our scaling factors for the spatial field variables
  for (const auto & elem : *mesh().getActiveLocalElementRange())
    for (const auto i : make_range(system().n_vars()))
      if (_variable_autoscaled[i] && system().variable_type(i).family != SCALAR)
      {
        dof_map.dof_indices(elem, dof_indices, i);
        examine_dof_indices(dof_indices, i);
      }
  for (const auto i : make_range(system().n_vars()))
    if (_variable_autoscaled[i] && system().variable_type(i).family == SCALAR)
    {
      dof_map.SCALAR_dof_indices(dof_indices, i);
      examine_dof_indices(dof_indices, i);
    }
  if (resid_scaling)
    _communicator.max(resid_inverse_scaling_factors);
  if (jac_scaling)
    _communicator.max(jac_inverse_scaling_factors);
  if (jac_scaling && resid_scaling)
    for (MooseIndex(inverse_scaling_factors) i = 0; i < inverse_scaling_factors.size(); ++i)
    {
      // Be careful not to take log(0)
      if (!resid_inverse_scaling_factors[i])
      {
        if (!jac_inverse_scaling_factors[i])
          inverse_scaling_factors[i] = 1;
        else
          inverse_scaling_factors[i] = jac_inverse_scaling_factors[i];
      }
      else if (!jac_inverse_scaling_factors[i])
        // We know the resid is not zero
        inverse_scaling_factors[i] = resid_inverse_scaling_factors[i];
      else
        inverse_scaling_factors[i] =
            std::exp(_resid_vs_jac_scaling_param * std::log(resid_inverse_scaling_factors[i]) +
                     (1 - _resid_vs_jac_scaling_param) * std::log(jac_inverse_scaling_factors[i]));
    }
  else if (jac_scaling)
    inverse_scaling_factors = jac_inverse_scaling_factors;
  else if (resid_scaling)
    inverse_scaling_factors = resid_inverse_scaling_factors;
  else
    mooseError("We shouldn't be calling this routine if we're not performing any scaling");
  // We have to make sure that our scaling values are not zero
  for (auto & scaling_factor : inverse_scaling_factors)
    if (scaling_factor == 0)
      scaling_factor = 1;
  // Now flatten the group scaling factors to the individual variable scaling factors
  std::vector<Real> flattened_inverse_scaling_factors(system().n_vars());
  for (const auto i : index_range(flattened_inverse_scaling_factors))
    flattened_inverse_scaling_factors[i] = inverse_scaling_factors[_var_to_group_var[i]];
  // Now set the scaling factors for the variables
  applyScalingFactors(flattened_inverse_scaling_factors);
  if (auto displaced_problem = _fe_problem.getDisplacedProblem().get())
    displaced_problem->systemBaseNonlinear(number()).applyScalingFactors(
        flattened_inverse_scaling_factors);
  _auto_scaling_initd = true;
}
Referenced by solve(), and NonlinearSystem::solve().
computeScalingJacobian()
void NonlinearEigenSystem::computeScalingJacobian () override protected virtual
Compute a "Jacobian" for automatic scaling purposes.
Implements NonlinearSystemBase.
Definition at line 482 of file NonlinearEigenSystem.C.
{
  _eigen_problem.computeJacobianTag(*_current_solution, *_scaling_matrix, precondMatrixTag());
}
computeScalingOnce() [1/2]
bool NonlinearSystemBase::computeScalingOnce () const inline inherited
Definition at line 644 of file NonlinearSystemBase.h.
{ return _compute_scaling_once; }
Referenced by FEProblemSolve::FEProblemSolve().
computeScalingOnce() [2/2]
void NonlinearSystemBase::computeScalingOnce (bool compute_scaling_once) inline inherited
Definition at line 645 of file NonlinearSystemBase.h.
  {
    _compute_scaling_once = compute_scaling_once;
  }
computeScalingResidual()
void NonlinearEigenSystem::computeScalingResidual () override protected virtual
Compute a "residual" for automatic scaling purposes.
Implements NonlinearSystemBase.
Definition at line 488 of file NonlinearEigenSystem.C.
{
  _eigen_problem.computeResidualTag(*_current_solution, RHS(), nonEigenVectorTag());
}
computeTimeDerivatives()
void NonlinearSystemBase::computeTimeDerivatives (bool jacobian_calculation = false) inherited
Computes the time derivative vector.
Definition at line 1011 of file NonlinearSystemBase.C.
{
  // If we're doing any Jacobian calculation other than the initial Jacobian calculation for
  // automatic variable scaling, then we can just return because the residual function evaluation
  // has already done this work for us
  if (jacobian_calculation && !_fe_problem.computingScalingJacobian())
    return;
  if (_time_integrator)
  {
    _time_integrator->preStep();
    _time_integrator->computeTimeDerivatives();
  }
}
Referenced by FEProblemBase::computeJacobianTags(), and ExplicitSSPRungeKutta::solveStage().
computeVariables()
virtual void SystemBase::computeVariables (const NumericVector< Number > &) inline virtual inherited
Definition at line 852 of file SystemBase.h.
{}
computingInitialResidual()
virtual bool NonlinearSystemBase::computingInitialResidual () inline virtual inherited
Returns true if this system is currently computing the initial residual for a solve.
Returns
Whether or not we are currently computing the initial residual.
Definition at line 97 of file NonlinearSystemBase.h.
{ return _computing_initial_residual; }
computingScalingJacobian()
bool SystemBase::computingScalingJacobian () const inherited
Whether we are computing an initial Jacobian for automatic variable scaling.
Definition at line 1471 of file SystemBase.C.
{
  return _subproblem.computingScalingJacobian();
}
Referenced by Assembly::addJacobianBlock(), Assembly::addJacobianBlockNonlocal(), Assembly::addJacobianNeighbor(), Assembly::cacheJacobianBlock(), EigenKernel::computeJacobian(), Kernel::computeJacobian(), VectorKernel::computeJacobian(), and FEProblemBase::computeJacobianTags().
constraintJacobians()
void NonlinearSystemBase::constraintJacobians (bool displaced) inherited
Add jacobian contributions from Constraints.
Parameters
jacobian reference to the Jacobian matrix
displaced Controls whether to do the displaced Constraints or non-displaced
Definition at line 2103 of file NonlinearSystemBase.C.
{
  if (!hasMatrix(systemMatrixTag()))
    mooseError("A system matrix is required");
  auto & jacobian = getMatrix(systemMatrixTag());
  if (!_fe_problem.errorOnJacobianNonzeroReallocation())
    MatSetOption(static_cast<PetscMatrix<Number> &>(jacobian).mat(),
                 MAT_NEW_NONZERO_ALLOCATION_ERR,
                 PETSC_FALSE);
  if (_fe_problem.ignoreZerosInJacobian())
    MatSetOption(
        static_cast<PetscMatrix<Number> &>(jacobian).mat(), MAT_IGNORE_ZERO_ENTRIES, PETSC_TRUE);
  std::vector<numeric_index_type> zero_rows;
  if (displaced)
    mooseAssert(_fe_problem.getDisplacedProblem(),
                "If we're calling this method with displaced = true, then we better well have a "
                "displaced problem");
  auto & subproblem = displaced ? static_cast<SubProblem &>(*_fe_problem.getDisplacedProblem())
                                : static_cast<SubProblem &>(_fe_problem);
  const auto & penetration_locators = subproblem.geomSearchData()._penetration_locators;
  bool constraints_applied;
  if (!_assemble_constraints_separately)
    constraints_applied = false;
  for (const auto & it : penetration_locators)
  {
    if (_assemble_constraints_separately)
    {
      // Reset the constraint_applied flag before each new constraint, as they need to be
      // assembled separately
      constraints_applied = false;
    }
    PenetrationLocator & pen_loc = *(it.second);
    std::vector<dof_id_type> & secondary_nodes = pen_loc._nearest_node._secondary_nodes;
    BoundaryID secondary_boundary = pen_loc._secondary_boundary;
    BoundaryID primary_boundary = pen_loc._primary_boundary;
    zero_rows.clear();
    if (_constraints.hasActiveNodeFaceConstraints(secondary_boundary, displaced))
    {
      const auto & constraints =
          _constraints.getActiveNodeFaceConstraints(secondary_boundary, displaced);
      for (const auto & secondary_node_num : secondary_nodes)
      {
        Node & secondary_node = _mesh.nodeRef(secondary_node_num);
        if (secondary_node.processor_id() == processor_id())
        {
          if (pen_loc._penetration_info[secondary_node_num])
          {
            PenetrationInfo & info = *pen_loc._penetration_info[secondary_node_num];
            const Elem * primary_elem = info._elem;
            unsigned int primary_side = info._side_num;
            // reinit variables at the node
            _fe_problem.reinitNodeFace(&secondary_node, secondary_boundary, 0);
            _fe_problem.prepareAssembly(0);
            _fe_problem.reinitOffDiagScalars(0);
            std::vector<Point> points;
            points.push_back(info._closest_point);
            // reinit variables on the primary element's face at the contact point
            _fe_problem.setNeighborSubdomainID(primary_elem, 0);
            subproblem.reinitNeighborPhys(primary_elem, primary_side, points, 0);
            for (const auto & nfc : constraints)
            {
              // Return if this constraint does not correspond to the primary-secondary pair
              // prepared by the outer loops.
              // This continue statement is required when, e.g. one secondary surface constrains
              // more than one primary surface.
              if (nfc->secondaryBoundary() != secondary_boundary ||
                  nfc->primaryBoundary() != primary_boundary)
                continue;
              nfc->_jacobian = &jacobian;
              if (nfc->shouldApply())
              {
                constraints_applied = true;
                nfc->prepareShapes(nfc->variable().number());
                nfc->prepareNeighborShapes(nfc->variable().number());
                nfc->computeJacobian();
                if (nfc->overwriteSecondaryJacobian())
                {
                  // Add this variable's dof's row to be zeroed
                  zero_rows.push_back(nfc->variable().nodalDofIndex());
                }
                std::vector<dof_id_type> secondary_dofs(1, nfc->variable().nodalDofIndex());
                // Assume that if the user is overwriting the secondary Jacobian, then they are
                // supplying Jacobians that do not correspond to their other physics
                // (e.g. Kernels), hence we should not apply a scalingFactor that is normally
                // based on the order of their other physics (e.g. Kernels)
                Real scaling_factor =
                    nfc->overwriteSecondaryJacobian() ? 1. : nfc->variable().scalingFactor();
                // Cache the jacobian block for the secondary side
                nfc->addJacobian(_fe_problem.assembly(0, number()),
                                 nfc->_Kee,
                                 secondary_dofs,
                                 nfc->_connected_dof_indices,
                                 scaling_factor);
                // Cache Ken, Kne, Knn
                if (nfc->addCouplingEntriesToJacobian())
                {
                  // Make sure we use a proper scaling factor (e.g. don't use an interior scaling
                  // factor when we're overwriting secondary stuff)
                  nfc->addJacobian(_fe_problem.assembly(0, number()),
                                   nfc->_Ken,
                                   secondary_dofs,
                                   nfc->primaryVariable().dofIndicesNeighbor(),
                                   scaling_factor);
                  // Use _connected_dof_indices to get all the correct columns
                  nfc->addJacobian(_fe_problem.assembly(0, number()),
                                   nfc->_Kne,
                                   nfc->primaryVariable().dofIndicesNeighbor(),
                                   nfc->_connected_dof_indices,
                                   nfc->variable().scalingFactor());
                  // We've handled Ken and Kne, finally handle Knn
                  _fe_problem.cacheJacobianNeighbor(0);
                }
                // Do the off-diagonals next
                const std::vector<MooseVariableFEBase *> coupled_vars = nfc->getCoupledMooseVars();
                for (const auto & jvar : coupled_vars)
                {
                  // Only compute jacobians for nonlinear variables
                  if (jvar->kind() != Moose::VAR_NONLINEAR)
                    continue;
                  // Only compute Jacobian entries if this coupling is being used by the
                  // preconditioner
                  if (nfc->variable().number() == jvar->number() ||
                      !_fe_problem.areCoupled(
                          nfc->variable().number(), jvar->number(), this->number()))
                    continue;
                  // Need to zero out the matrices first
                  _fe_problem.prepareAssembly(0);
                  nfc->prepareShapes(nfc->variable().number());
                  nfc->prepareNeighborShapes(jvar->number());
                  nfc->computeOffDiagJacobian(jvar->number());
                  // Cache the jacobian block for the secondary side
                  nfc->addJacobian(_fe_problem.assembly(0, number()),
                                   nfc->_Kee,
                                   secondary_dofs,
                                   nfc->_connected_dof_indices,
                                   scaling_factor);
                  // Cache Ken, Kne, Knn
                  if (nfc->addCouplingEntriesToJacobian())
                  {
                    // Make sure we use a proper scaling factor (e.g. don't use an interior scaling
                    // factor when we're overwriting secondary stuff)
                    nfc->addJacobian(_fe_problem.assembly(0, number()),
                                     nfc->_Ken,
                                     secondary_dofs,
                                     jvar->dofIndicesNeighbor(),
                                     scaling_factor);
                    // Use _connected_dof_indices to get all the correct columns
                    nfc->addJacobian(_fe_problem.assembly(0, number()),
                                     nfc->_Kne,
                                     nfc->variable().dofIndicesNeighbor(),
                                     nfc->_connected_dof_indices,
                                     nfc->variable().scalingFactor());
                    // We've handled Ken and Kne, finally handle Knn
                    _fe_problem.cacheJacobianNeighbor(0);
                  }
                }
              }
            }
          }
        }
      }
    }
    if (_assemble_constraints_separately)
    {
      // See if constraints were applied anywhere
      _communicator.max(constraints_applied);
      if (constraints_applied)
      {
        MatSetOption(static_cast<PetscMatrix<Number> &>(jacobian).mat(),
                     MAT_KEEP_NONZERO_PATTERN, // This is changed in 3.1
                     PETSC_TRUE);
        jacobian.close();
        jacobian.zero_rows(zero_rows, 0.0);
        jacobian.close();
        _fe_problem.addCachedJacobian(0);
        jacobian.close();
      }
    }
  }
  if (!_assemble_constraints_separately)
  {
    // See if constraints were applied anywhere
    _communicator.max(constraints_applied);
    if (constraints_applied)
    {
      MatSetOption(static_cast<PetscMatrix<Number> &>(jacobian).mat(),
                   MAT_KEEP_NONZERO_PATTERN, // This is changed in 3.1
                   PETSC_TRUE);
      jacobian.close();
      jacobian.zero_rows(zero_rows, 0.0);
      jacobian.close();
      _fe_problem.addCachedJacobian(0);
      jacobian.close();
    }
  }
  THREAD_ID tid = 0;
  // go over element-element constraint interface
  const auto & element_pair_locators = subproblem.geomSearchData()._element_pair_locators;
  for (const auto & it : element_pair_locators)
  {
    ElementPairLocator & elem_pair_loc = *(it.second);
    if (_constraints.hasActiveElemElemConstraints(it.first, displaced))
    {
      // ElemElemConstraint objects
      const auto & _element_constraints =
          _constraints.getActiveElemElemConstraints(it.first, displaced);
      // go over pair elements
      const std::list<std::pair<const Elem *, const Elem *>> & elem_pairs =
          elem_pair_loc.getElemPairs();
      for (const auto & pr : elem_pairs)
      {
        const Elem * elem1 = pr.first;
        const Elem * elem2 = pr.second;
        if (elem1->processor_id() != processor_id())
          continue;
        const ElementPairInfo & info = elem_pair_loc.getElemPairInfo(pr);
        // for each element process constraints on the
        for (const auto & ec : _element_constraints)
        {
          _fe_problem.setCurrentSubdomainID(elem1, tid);
          subproblem.reinitElemPhys(elem1, info._elem1_constraint_q_point, tid);
          _fe_problem.setNeighborSubdomainID(elem2, tid);
          subproblem.reinitNeighborPhys(elem2, info._elem2_constraint_q_point, tid);
          ec->prepareShapes(ec->variable().number());
          ec->prepareNeighborShapes(ec->variable().number());
          ec->reinit(info);
          ec->computeJacobian();
          _fe_problem.cacheJacobian(tid);
          _fe_problem.cacheJacobianNeighbor(tid);
        }
        _fe_problem.addCachedJacobian(tid);
      }
    }
  }
  // go over NodeELemConstraints
  std::set<dof_id_type> unique_secondary_node_ids;
  constraints_applied = false;
  for (const auto & secondary_id : _mesh.meshSubdomains())
  {
    for (const auto & primary_id : _mesh.meshSubdomains())
    {
      if (_constraints.hasActiveNodeElemConstraints(secondary_id, primary_id, displaced))
      {
        const auto & constraints =
            _constraints.getActiveNodeElemConstraints(secondary_id, primary_id, displaced);
        // get unique set of ids of all nodes on current block
        unique_secondary_node_ids.clear();
        const MeshBase & meshhelper = _mesh.getMesh();
        for (const auto & elem : as_range(meshhelper.active_subdomain_elements_begin(secondary_id),
                                          meshhelper.active_subdomain_elements_end(secondary_id)))
        {
          for (auto & n : elem->node_ref_range())
            unique_secondary_node_ids.insert(n.id());
        }
        for (auto secondary_node_id : unique_secondary_node_ids)
        {
          const Node & secondary_node = _mesh.nodeRef(secondary_node_id);
          // check if secondary node is on current processor
          if (secondary_node.processor_id() == processor_id())
          {
            // This reinits the variables that exist on the secondary node
            _fe_problem.reinitNodeFace(&secondary_node, secondary_id, 0);
            // This will set aside residual and jacobian space for the variables that have dofs
            // on the secondary node
            _fe_problem.prepareAssembly(0);
            _fe_problem.reinitOffDiagScalars(0);
            for (const auto & nec : constraints)
            {
              if (nec->shouldApply())
              {
                constraints_applied = true;
                nec->_jacobian = &jacobian;
                nec->prepareShapes(nec->variable().number());
                nec->prepareNeighborShapes(nec->variable().number());
                nec->computeJacobian();
                if (nec->overwriteSecondaryJacobian())
                {
                  // Add this variable's dof's row to be zeroed
                  zero_rows.push_back(nec->variable().nodalDofIndex());
                }
                std::vector<dof_id_type> secondary_dofs(1, nec->variable().nodalDofIndex());
                // Cache the jacobian block for the secondary side
                nec->addJacobian(_fe_problem.assembly(0, number()),
                                 nec->_Kee,
                                 secondary_dofs,
                                 nec->_connected_dof_indices,
                                 nec->variable().scalingFactor());
                // Cache the jacobian block for the primary side
                nec->addJacobian(_fe_problem.assembly(0, number()),
                                 nec->_Kne,
                                 nec->primaryVariable().dofIndicesNeighbor(),
                                 nec->_connected_dof_indices,
                                 nec->variable().scalingFactor());
                _fe_problem.cacheJacobian(0);
                _fe_problem.cacheJacobianNeighbor(0);
                // Do the off-diagonals next
                const std::vector<MooseVariableFEBase *> coupled_vars = nec->getCoupledMooseVars();
                for (const auto & jvar : coupled_vars)
                {
                  // Only compute jacobians for nonlinear variables
                  if (jvar->kind() != Moose::VAR_NONLINEAR)
                    continue;
                  // Only compute Jacobian entries if this coupling is being used by the
                  // preconditioner
                  if (nec->variable().number() == jvar->number() ||
                      !_fe_problem.areCoupled(
                          nec->variable().number(), jvar->number(), this->number()))
                    continue;
                  // Need to zero out the matrices first
                  _fe_problem.prepareAssembly(0);
                  nec->prepareShapes(nec->variable().number());
                  nec->prepareNeighborShapes(jvar->number());
                  nec->computeOffDiagJacobian(jvar->number());
                  // Cache the jacobian block for the secondary side
                  nec->addJacobian(_fe_problem.assembly(0, number()),
                                   nec->_Kee,
                                   secondary_dofs,
                                   nec->_connected_dof_indices,
                                   nec->variable().scalingFactor());
                  // Cache the jacobian block for the primary side
                  nec->addJacobian(_fe_problem.assembly(0, number()),
                                   nec->_Kne,
                                   nec->variable().dofIndicesNeighbor(),
                                   nec->_connected_dof_indices,
                                   nec->variable().scalingFactor());
                  _fe_problem.cacheJacobian(0);
                  _fe_problem.cacheJacobianNeighbor(0);
                }
              }
            }
          }
        }
      }
    }
  }
  // See if constraints were applied anywhere
  _communicator.max(constraints_applied);
  if (constraints_applied)
  {
    MatSetOption(static_cast<PetscMatrix<Number> &>(jacobian).mat(),
                 MAT_KEEP_NONZERO_PATTERN, // This is changed in 3.1
                 PETSC_TRUE);
    jacobian.close();
    jacobian.zero_rows(zero_rows, 0.0);
    jacobian.close();
    _fe_problem.addCachedJacobian(0);
    jacobian.close();
  }
}
Referenced by NonlinearSystemBase::computeJacobianInternal().
constraintResiduals()
void NonlinearSystemBase::constraintResiduals (NumericVector< Number > & residual, bool displaced) inherited
Add residual contributions from Constraints.
Parameters
residual - reference to the residual vector where constraint contributions will be computed
displaced Controls whether to do the displaced Constraints or non-displaced
Definition at line 1217 of file NonlinearSystemBase.C.
{
  // Make sure the residual is in a good state
  residual.close();
  if (displaced)
    mooseAssert(_fe_problem.getDisplacedProblem(),
                "If we're calling this method with displaced = true, then we better well have a "
                "displaced problem");
  auto & subproblem = displaced ? static_cast<SubProblem &>(*_fe_problem.getDisplacedProblem())
                                : static_cast<SubProblem &>(_fe_problem);
  const auto & penetration_locators = subproblem.geomSearchData()._penetration_locators;
  bool constraints_applied;
  bool residual_has_inserted_values = false;
  if (!_assemble_constraints_separately)
    constraints_applied = false;
  for (const auto & it : penetration_locators)
  {
    if (_assemble_constraints_separately)
    {
      // Reset the constraint_applied flag before each new constraint, as they need to be
      // assembled separately
      constraints_applied = false;
    }
    PenetrationLocator & pen_loc = *(it.second);
    std::vector<dof_id_type> & secondary_nodes = pen_loc._nearest_node._secondary_nodes;
    BoundaryID secondary_boundary = pen_loc._secondary_boundary;
    BoundaryID primary_boundary = pen_loc._primary_boundary;
    if (_constraints.hasActiveNodeFaceConstraints(secondary_boundary, displaced))
    {
      const auto & constraints =
          _constraints.getActiveNodeFaceConstraints(secondary_boundary, displaced);
      for (unsigned int i = 0; i < secondary_nodes.size(); i++)
      {
        dof_id_type secondary_node_num = secondary_nodes[i];
        Node & secondary_node = _mesh.nodeRef(secondary_node_num);
        if (secondary_node.processor_id() == processor_id())
        {
          if (pen_loc._penetration_info[secondary_node_num])
          {
            PenetrationInfo & info = *pen_loc._penetration_info[secondary_node_num];
            const Elem * primary_elem = info._elem;
            unsigned int primary_side = info._side_num;
            // *These next steps MUST be done in this order!*
            // This reinits the variables that exist on the secondary node
            _fe_problem.reinitNodeFace(&secondary_node, secondary_boundary, 0);
            // This will set aside residual and jacobian space for the variables that have dofs on
            // the secondary node
            _fe_problem.prepareAssembly(0);
            std::vector<Point> points;
            points.push_back(info._closest_point);
            // reinit variables on the primary element's face at the contact point
            _fe_problem.setNeighborSubdomainID(primary_elem, 0);
            subproblem.reinitNeighborPhys(primary_elem, primary_side, points, 0);
            for (const auto & nfc : constraints)
            {
              // Return if this constraint does not correspond to the primary-secondary pair
              // prepared by the outer loops.
              // This continue statement is required when, e.g. one secondary surface constrains
              // more than one primary surface.
              if (nfc->secondaryBoundary() != secondary_boundary ||
                  nfc->primaryBoundary() != primary_boundary)
                continue;
              if (nfc->shouldApply())
              {
                constraints_applied = true;
                nfc->computeResidual();
                if (nfc->overwriteSecondaryResidual())
                {
                  // The below will actually overwrite the residual for every single dof that
                  // lives on the node. We definitely don't want to do that!
                  // _fe_problem.setResidual(residual, 0);
                  const auto & secondary_var = nfc->variable();
                  const auto & secondary_dofs = secondary_var.dofIndices();
                  mooseAssert(secondary_dofs.size() == secondary_var.count(),
                              "We are on a node so there should only be one dof per variable (for "
                              "an ArrayVariable we should have a number of dofs equal to the "
                              "number of components");
                  // Assume that if the user is overwriting the secondary residual, then they are
                  // supplying residuals that do not correspond to their other physics
                  // (e.g. Kernels), hence we should not apply a scalingFactor that is normally
                  // based on the order of their other physics (e.g. Kernels)
                  std::vector<Number> values = {nfc->secondaryResidual()};
                  residual.insert(values, secondary_dofs);
                  residual_has_inserted_values = true;
                }
                else
                  _fe_problem.cacheResidual(0);
                _fe_problem.cacheResidualNeighbor(0);
              }
            }
          }
        }
      }
    }
    if (_assemble_constraints_separately)
    {
      // Make sure that secondary contribution to primary are assembled, and ghosts have been
      // exchanged, as current primaries might become secondaries on next iteration and will need to
      // contribute their former secondaries' contributions to the future primaries. See if
      // constraints were applied anywhere
      _communicator.max(constraints_applied);
      if (constraints_applied)
      {
        // If any of the above constraints inserted values in the residual, it needs to be
        // assembled before adding the cached residuals below.
        _communicator.max(residual_has_inserted_values);
        if (residual_has_inserted_values)
        {
          residual.close();
          residual_has_inserted_values = false;
        }
        _fe_problem.addCachedResidualDirectly(residual, 0);
        residual.close();
        if (_need_residual_ghosted)
          *_residual_ghosted = residual;
      }
    }
  }
  if (!_assemble_constraints_separately)
  {
    _communicator.max(constraints_applied);
    if (constraints_applied)
    {
      // If any of the above constraints inserted values in the residual, it needs to be assembled
      // before adding the cached residuals below.
      _communicator.max(residual_has_inserted_values);
      if (residual_has_inserted_values)
        residual.close();
      _fe_problem.addCachedResidualDirectly(residual, 0);
      residual.close();
      if (_need_residual_ghosted)
        *_residual_ghosted = residual;
    }
  }
  // go over element-element constraint interface
  THREAD_ID tid = 0;
  const auto & element_pair_locators = subproblem.geomSearchData()._element_pair_locators;
  for (const auto & it : element_pair_locators)
  {
    ElementPairLocator & elem_pair_loc = *(it.second);
    if (_constraints.hasActiveElemElemConstraints(it.first, displaced))
    {
      // ElemElemConstraint objects
      const auto & _element_constraints =
          _constraints.getActiveElemElemConstraints(it.first, displaced);
      // go over pair elements
      const std::list<std::pair<const Elem *, const Elem *>> & elem_pairs =
          elem_pair_loc.getElemPairs();
      for (const auto & pr : elem_pairs)
      {
        const Elem * elem1 = pr.first;
        const Elem * elem2 = pr.second;
        if (elem1->processor_id() != processor_id())
          continue;
        const ElementPairInfo & info = elem_pair_loc.getElemPairInfo(pr);
        // for each element process constraints on the
        for (const auto & ec : _element_constraints)
        {
          _fe_problem.setCurrentSubdomainID(elem1, tid);
          subproblem.reinitElemPhys(elem1, info._elem1_constraint_q_point, tid);
          _fe_problem.setNeighborSubdomainID(elem2, tid);
          subproblem.reinitNeighborPhys(elem2, info._elem2_constraint_q_point, tid);
          ec->prepareShapes(ec->variable().number());
          ec->prepareNeighborShapes(ec->variable().number());
          ec->reinit(info);
          ec->computeResidual();
          _fe_problem.cacheResidual(tid);
          _fe_problem.cacheResidualNeighbor(tid);
        }
        _fe_problem.addCachedResidual(tid);
      }
    }
  }
  // go over NodeELemConstraints
  std::set<dof_id_type> unique_secondary_node_ids;
  constraints_applied = false;
  residual_has_inserted_values = false;
  for (const auto & secondary_id : _mesh.meshSubdomains())
  {
    for (const auto & primary_id : _mesh.meshSubdomains())
    {
      if (_constraints.hasActiveNodeElemConstraints(secondary_id, primary_id, displaced))
      {
        const auto & constraints =
            _constraints.getActiveNodeElemConstraints(secondary_id, primary_id, displaced);
        // get unique set of ids of all nodes on current block
        unique_secondary_node_ids.clear();
        const MeshBase & meshhelper = _mesh.getMesh();
        for (const auto & elem : as_range(meshhelper.active_subdomain_elements_begin(secondary_id),
                                          meshhelper.active_subdomain_elements_end(secondary_id)))
        {
          for (auto & n : elem->node_ref_range())
            unique_secondary_node_ids.insert(n.id());
        }
        for (auto secondary_node_id : unique_secondary_node_ids)
        {
          Node & secondary_node = _mesh.nodeRef(secondary_node_id);
          // check if secondary node is on current processor
          if (secondary_node.processor_id() == processor_id())
          {
            // This reinits the variables that exist on the secondary node
            _fe_problem.reinitNodeFace(&secondary_node, secondary_id, 0);
            // This will set aside residual and jacobian space for the variables that have dofs
            // on the secondary node
            _fe_problem.prepareAssembly(0);
            for (const auto & nec : constraints)
            {
              if (nec->shouldApply())
              {
                constraints_applied = true;
                nec->computeResidual();
                if (nec->overwriteSecondaryResidual())
                {
                  _fe_problem.setResidual(residual, 0);
                  residual_has_inserted_values = true;
                }
                else
                  _fe_problem.cacheResidual(0);
                _fe_problem.cacheResidualNeighbor(0);
              }
            }
            _fe_problem.addCachedResidual(0);
          }
        }
      }
    }
  }
  _communicator.max(constraints_applied);
  if (constraints_applied)
  {
    // If any of the above constraints inserted values in the residual, it needs to be assembled
    // before adding the cached residuals below.
    _communicator.max(residual_has_inserted_values);
    if (residual_has_inserted_values)
      residual.close();
    _fe_problem.addCachedResidualDirectly(residual, 0);
    residual.close();
    if (_need_residual_ghosted)
      *_residual_ghosted = residual;
  }
  // We may have additional tagged vectors that also need to be accumulated
  _fe_problem.addCachedResidual(0);
}
Referenced by NonlinearSystemBase::computeResidualInternal().
containsTimeKernel()
bool NonlinearSystemBase::containsTimeKernel () inherited
Definition at line 3555 of file NonlinearSystemBase.C.
{
  auto & time_kernels = _kernels.getVectorTagObjectWarehouse(timeVectorTag(), 0);
  return time_kernels.hasActiveObjects();
}
Referenced by EigenExecutionerBase::checkIntegrity(), Eigenvalue::checkIntegrity(), and Steady::checkIntegrity().
converged() [1/2]
bool NonlinearEigenSystem::converged () inline virtual
Returns the convergence state.
Returns
true if converged, otherwise false
Implements NonlinearSystemBase.
Definition at line 205 of file NonlinearEigenSystem.h.
{ return false; }
converged() [2/2]
bool NonlinearEigenSystem::converged () override virtual
Returns the convergence state.
Returns
true if converged, otherwise false
Implements NonlinearSystemBase.
Definition at line 328 of file NonlinearEigenSystem.C.
{
  return _eigen_sys.get_n_converged();
}
copyOldSolutions()
void SystemBase::copyOldSolutions () virtual inherited
Shifts the solutions backwards in time.
Definition at line 1254 of file SystemBase.C.
{
  const auto states =
      _solution_states[static_cast<unsigned short>(Moose::SolutionIterationType::Time)].size();
  if (states > 1)
    for (unsigned int i = states - 1; i > 0; --i)
      solutionState(i) = solutionState(i - 1);
  if (solutionUDotOld())
    *solutionUDotOld() = *solutionUDot();
  if (solutionUDotDotOld())
    *solutionUDotDotOld() = *solutionUDotDot();
  if (solutionPreviousNewton())
    *solutionPreviousNewton() = *currentSolution();
}
Referenced by EigenExecutionerBase::inversePowerIteration().
copySolutionsBackwards()
void SystemBase::copySolutionsBackwards () virtual inherited
Copy current solution into old and older.
Definition at line 1227 of file SystemBase.C.
{
  system().update();
  // Copying the solutions backward so the current solution will become the old, and the old will
  // become older. The same applies to the nonlinear iterates.
  for (const auto iteration_index : index_range(_solution_states))
  {
    const auto states = _solution_states[iteration_index].size();
    if (states > 1)
      for (unsigned int i = states - 1; i > 0; --i)
        solutionState(i, Moose::SolutionIterationType(iteration_index)) =
            solutionState(i - 1, Moose::SolutionIterationType(iteration_index));
  }
  if (solutionUDotOld())
    *solutionUDotOld() = *solutionUDot();
  if (solutionUDotDotOld())
    *solutionUDotDotOld() = *solutionUDotDot();
  if (solutionPreviousNewton())
    *solutionPreviousNewton() = *currentSolution();
}
copyVars()
void SystemBase::copyVars (ExodusII_IO & io) inherited
Definition at line 1151 of file SystemBase.C.
{
  int n_steps = io.get_num_time_steps();
  bool did_copy = false;
  for (const auto & vci : _var_to_copy)
  {
    int timestep = -1;
    if (vci._timestep == "LATEST")
      // Use the last time step in the file from which to retrieve the solution
      timestep = n_steps;
    else
    {
      timestep = MooseUtils::convert<int>(vci._timestep);
      if (timestep > n_steps)
        mooseError("Invalid value passed as \"initial_from_file_timestep\". Expected \"LATEST\" or "
                   "a valid integer between 1 and ",
                   n_steps,
                   " inclusive, received ",
                   vci._timestep);
    }
    did_copy = true;
    if (hasVariable(vci._dest_name))
    {
      const auto & var = getVariable(0, vci._dest_name);
      if (var.isArray())
      {
        const auto & array_var = getFieldVariable<RealEigenVector>(0, vci._dest_name);
        for (MooseIndex(var.count()) i = 0; i < var.count(); ++i)
        {
          const auto exodus_var = _subproblem.arrayVariableComponent(vci._source_name, i);
          const auto system_var = array_var.componentName(i);
          if (var.isNodal())
            io.copy_nodal_solution(system(), exodus_var, system_var, timestep);
          else
            io.copy_elemental_solution(system(), exodus_var, system_var, timestep);
        }
      }
      else
      {
        if (var.isNodal())
          io.copy_nodal_solution(system(), vci._dest_name, vci._source_name, timestep);
        else
          io.copy_elemental_solution(system(), vci._dest_name, vci._source_name, timestep);
      }
    }
    else if (hasScalarVariable(vci._dest_name))
      io.copy_scalar_solution(system(), {vci._dest_name}, {vci._source_name}, timestep);
    else
      mooseError("Unrecognized variable ", vci._dest_name, " in variables to copy.");
  }
  if (did_copy)
    solution().close();
}
currentSolution()
const NumericVector< Number > *const & NonlinearSystemBase::currentSolution () const inline override virtual inherited
The solution vector that is currently being operated on.
This is typically a ghosted vector that comes in from the Nonlinear solver.
Implements SystemBase.
Definition at line 409 of file NonlinearSystemBase.h.
  {
    return _current_solution;
  }
Referenced by FEProblemBase::computeDamping(), Transient::relativeSolutionDifferenceNorm(), and AB2PredictorCorrector::step().
customSetup()
void NonlinearSystemBase::customSetup (const ExecFlagType & exec_type) override virtual inherited
Reimplemented from SystemBase.
Definition at line 386 of file NonlinearSystemBase.C.
{
  SystemBase::customSetup(exec_type);
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    _kernels.customSetup(exec_type, tid);
    _nodal_kernels.customSetup(exec_type, tid);
    _dirac_kernels.customSetup(exec_type, tid);
    if (_doing_dg)
      _dg_kernels.customSetup(exec_type, tid);
    _interface_kernels.customSetup(exec_type, tid);
    _element_dampers.customSetup(exec_type, tid);
    _nodal_dampers.customSetup(exec_type, tid);
    _integrated_bcs.customSetup(exec_type, tid);
    if (_fe_problem.haveFV())
    {
      std::vector<FVFluxBC *> bcs;
      _fe_problem.theWarehouse()
          .query()
          .template condition<AttribSystem>("FVFluxBC")
          .template condition<AttribThread>(tid)
          .queryInto(bcs);
      std::vector<FVInterfaceKernel *> iks;
      _fe_problem.theWarehouse()
          .query()
          .template condition<AttribSystem>("FVInterfaceKernel")
          .template condition<AttribThread>(tid)
          .queryInto(iks);
      std::vector<FVFluxKernel *> kernels;
      _fe_problem.theWarehouse()
          .query()
          .template condition<AttribSystem>("FVFluxKernel")
          .template condition<AttribThread>(tid)
          .queryInto(kernels);
      for (auto * bc : bcs)
        bc->customSetup(exec_type);
      for (auto * ik : iks)
        ik->customSetup(exec_type);
      for (auto * kernel : kernels)
        kernel->customSetup(exec_type);
    }
  }
  _scalar_kernels.customSetup(exec_type);
  _constraints.customSetup(exec_type);
  _general_dampers.customSetup(exec_type);
  _nodal_bcs.customSetup(exec_type);
}
deactiveAllMatrixTags()
void SystemBase::deactiveAllMatrixTags () virtual inherited
Make matrices inactive.
Definition at line 1092 of file SystemBase.C.
{
  auto num_matrix_tags = _subproblem.numMatrixTags();
  _matrix_tag_active_flags.resize(num_matrix_tags);
  for (decltype(num_matrix_tags) tag = 0; tag < num_matrix_tags; tag++)
    _matrix_tag_active_flags[tag] = false;
}
Referenced by NonlinearSystemBase::computeResidualTags(), and NonlinearSystemBase::setInitialSolution().
deactiveMatrixTag()
void SystemBase::deactiveMatrixTag (TagID tag) virtual inherited
deactive a matrix for tag
Definition at line 1080 of file SystemBase.C.
{
  mooseAssert(_subproblem.matrixTagExists(tag),
              "Cannot deactivate Matrix with matrix_tag : " << tag << "that does not exist");
  if (_matrix_tag_active_flags.size() < tag + 1)
    _matrix_tag_active_flags.resize(tag + 1);
  _matrix_tag_active_flags[tag] = false;
}
debuggingResiduals()
void NonlinearSystemBase::debuggingResiduals (bool state) inline inherited
Definition at line 540 of file NonlinearSystemBase.h.
{ _debugging_residuals = state; }
defaultMatrixTags()
std::set< TagID > NonlinearEigenSystem::defaultMatrixTags () const override virtual
Get the default matrix tags associted with this system.
Reimplemented from SystemBase.
Definition at line 503 of file NonlinearEigenSystem.C.
{
  auto tags = NonlinearSystemBase::defaultMatrixTags();
  tags.insert(eigenMatrixTag());
  tags.insert(nonEigenMatrixTag());
  return tags;
}
defaultVectorTags()
std::set< TagID > NonlinearEigenSystem::defaultVectorTags () const override virtual
Get the default vector tags associated with this system.
Reimplemented from SystemBase.
Definition at line 494 of file NonlinearEigenSystem.C.
{
  auto tags = NonlinearSystemBase::defaultVectorTags();
  tags.insert(eigenVectorTag());
  tags.insert(nonEigenVectorTag());
  return tags;
}
disassociateDefaultMatrixTags()
void SystemBase::disassociateDefaultMatrixTags () virtual inherited
Disassociate the matrices associated with the default matrix tags of this system.
Reimplemented in DisplacedSystem.
Definition at line 1059 of file SystemBase.C.
{
  const auto tags = defaultMatrixTags();
  for (const auto tag : tags)
    if (_subproblem.matrixTagExists(tag))
      disassociateMatrixFromTag(tag);
}
Referenced by DisplacedSystem::disassociateDefaultMatrixTags().
disassociateDefaultVectorTags()
void SystemBase::disassociateDefaultVectorTags () virtual inherited
Disassociate the vectors associated with the default vector tags of this system.
Reimplemented in DisplacedSystem.
Definition at line 964 of file SystemBase.C.
{
  const auto tags = defaultVectorTags();
  for (const auto tag : tags)
    if (_subproblem.vectorTagExists(tag))
      disassociateVectorFromTag(tag);
}
Referenced by DisplacedSystem::disassociateDefaultVectorTags().
disassociateMatrixFromTag() [1/2]
void SystemBase::disassociateMatrixFromTag (SparseMatrix< Number > & matrix, TagID tag) virtual inherited
Disassociate a matrix from a tag.
Reimplemented in DisplacedSystem.
Definition at line 1037 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag))
    mooseError("Cannot disassociate matrix from tag ", tag, " because that tag does not exist");
  if (hasMatrix(tag) && &getMatrix(tag) != &matrix)
    mooseError("You can not disassociate a matrix from a tag which it was not associated to");
  disassociateMatrixFromTag(tag);
}
Referenced by NonlinearSystemBase::computeJacobian(), FEProblemBase::computeJacobianInternal(), FEProblemBase::computeJacobianTag(), FEProblemBase::computeResidualAndJacobian(), SystemBase::disassociateDefaultMatrixTags(), SystemBase::disassociateMatrixFromTag(), and DisplacedSystem::disassociateMatrixFromTag().
disassociateMatrixFromTag() [2/2]
void SystemBase::disassociateMatrixFromTag (TagID tag) virtual inherited
Disassociate any matrix that is associated with a given tag.
Reimplemented in DisplacedSystem.
Definition at line 1048 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag))
    mooseError("Cannot disassociate matrix from tag ", tag, " because that tag does not exist");
  if (_tagged_matrices.size() < tag + 1)
    _tagged_matrices.resize(tag + 1);
  _tagged_matrices[tag] = nullptr;
}
disassociateVectorFromTag() [1/2]
void SystemBase::disassociateVectorFromTag (NumericVector< Number > & vec, TagID tag) virtual inherited
Disassociate a given vector from a given tag.
Reimplemented in DisplacedSystem.
Definition at line 942 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot disassociate vector from tag ", tag, " because that tag does not exist");
  if (hasVector(tag) && &getVector(tag) != &vec)
    mooseError("You can not disassociate a vector from a tag which it was not associated to");
  disassociateVectorFromTag(tag);
}
Referenced by NonlinearSystemBase::computeNodalBCs(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualTag(), NonlinearSystemBase::computeResidualTag(), FEProblemBase::computeResidualType(), SystemBase::disassociateDefaultVectorTags(), SystemBase::disassociateVectorFromTag(), DisplacedSystem::disassociateVectorFromTag(), and CentralDifference::initialSetup().
disassociateVectorFromTag() [2/2]
void SystemBase::disassociateVectorFromTag (TagID tag) virtual inherited
Disassociate any vector that is associated with a given tag.
Reimplemented in DisplacedSystem.
Definition at line 953 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot disassociate vector from tag ", tag, " because that tag does not exist");
  if (_tagged_vectors.size() < tag + 1)
    _tagged_vectors.resize(tag + 1);
  _tagged_vectors[tag] = nullptr;
}
dofMap() [1/2]
DofMap & SystemBase::dofMap () virtual inherited
Gets writeable reference to the dof map.
Definition at line 1131 of file SystemBase.C.
{
  return system().get_dof_map();
}
Referenced by NonlinearSystemBase::assembleScalingVector(), MooseApp::attachRelationshipManagers(), SystemBase::augmentSendList(), NonlinearSystemBase::augmentSparsity(), NonlinearSystemBase::computeScaling(), NonlinearSystemBase::findImplicitGeometricCouplingEntries(), Adaptivity::init(), ActivateElementsUserObjectBase::initSolutions(), PNGOutput::makeMeshFunc(), GhostingUserObject::meshChanged(), Exodus::outputScalarVariables(), Nemesis::outputScalarVariables(), TableOutput::outputScalarVariables(), and ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes().
dofMap() [2/2]
const DofMap & SystemBase::dofMap () const virtual inherited
Gets const reference to the dof map.
Definition at line 1137 of file SystemBase.C.
{
  return system().get_dof_map();
}
doingDG()
bool NonlinearSystemBase::doingDG () const inherited
Getter for _doing_dg.
Definition at line 3614 of file NonlinearSystemBase.C.
{
  return _doing_dg;
}
duDotDotDu() [1/2]
virtual Number & SystemBase::duDotDotDu () inline virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 223 of file SystemBase.h.
{ return _du_dotdot_du; }
Referenced by DisplacedSystem::duDotDotDu(), and MooseVariableScalar::reinit().
duDotDotDu() [2/2]
virtual const Number & SystemBase::duDotDotDu () const inline virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 225 of file SystemBase.h.
{ return _du_dotdot_du; }
duDotDu() [1/2]
virtual Number & SystemBase::duDotDu () inline virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 222 of file SystemBase.h.
{ return _du_dot_du; }
Referenced by DisplacedSystem::duDotDu(), and MooseVariableScalar::reinit().
duDotDu() [2/2]
virtual const Number & SystemBase::duDotDu () const inline virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 224 of file SystemBase.h.
{ return _du_dot_du; }
eigenMatrixTag()
TagID NonlinearEigenSystem::eigenMatrixTag () const inline
Matrix tag ID of right hand side.
Definition at line 141 of file NonlinearEigenSystem.h.
{ return _B_tag; }
Referenced by defaultMatrixTags(), Moose::SlepcSupport::mooseEPSFormMatrices(), and Moose::SlepcSupport::mooseSlepcEigenFormJacobianB().
eigenVectorTag()
TagID NonlinearEigenSystem::eigenVectorTag () const inline
Vector tag ID of right hand side.
Definition at line 131 of file NonlinearEigenSystem.h.
{ return _Bx_tag; }
Referenced by defaultVectorTags(), Moose::SlepcSupport::mooseMatMult_Eigen(), Moose::SlepcSupport::mooseSlepcEigenFormFunctionAB(), and Moose::SlepcSupport::mooseSlepcEigenFormFunctionB().
enforceNodalConstraintsJacobian()
void NonlinearSystemBase::enforceNodalConstraintsJacobian () protected inherited
Definition at line 1052 of file NonlinearSystemBase.C.
{
  if (!hasMatrix(systemMatrixTag()))
    mooseError(" A system matrix is required");
  auto & jacobian = getMatrix(systemMatrixTag());
  THREAD_ID tid = 0; // constraints are going to be done single-threaded
  if (_constraints.hasActiveNodalConstraints())
  {
    const auto & ncs = _constraints.getActiveNodalConstraints();
    for (const auto & nc : ncs)
    {
      std::vector<dof_id_type> & secondary_node_ids = nc->getSecondaryNodeId();
      std::vector<dof_id_type> & primary_node_ids = nc->getPrimaryNodeId();
      if ((secondary_node_ids.size() > 0) && (primary_node_ids.size() > 0))
      {
        _fe_problem.reinitNodes(primary_node_ids, tid);
        _fe_problem.reinitNodesNeighbor(secondary_node_ids, tid);
        nc->computeJacobian(jacobian);
      }
    }
    _fe_problem.addCachedJacobian(tid);
    jacobian.close();
  }
}
Referenced by NonlinearSystemBase::computeJacobianInternal().
enforceNodalConstraintsResidual()
void NonlinearSystemBase::enforceNodalConstraintsResidual (NumericVector< Number > & residual) protected inherited
Enforce nodal constraints.
Definition at line 1027 of file NonlinearSystemBase.C.
{
  THREAD_ID tid = 0; // constraints are going to be done single-threaded
  residual.close();
  if (_constraints.hasActiveNodalConstraints())
  {
    const auto & ncs = _constraints.getActiveNodalConstraints();
    for (const auto & nc : ncs)
    {
      std::vector<dof_id_type> & secondary_node_ids = nc->getSecondaryNodeId();
      std::vector<dof_id_type> & primary_node_ids = nc->getPrimaryNodeId();
      if ((secondary_node_ids.size() > 0) && (primary_node_ids.size() > 0))
      {
        _fe_problem.reinitNodes(primary_node_ids, tid);
        _fe_problem.reinitNodesNeighbor(secondary_node_ids, tid);
        nc->computeResidual(residual);
      }
    }
    _fe_problem.addCachedResidualDirectly(residual, tid);
    residual.close();
  }
}
Referenced by NonlinearSystemBase::computeResidualInternal().
finalNonlinearResidual()
Real NonlinearSystemBase::finalNonlinearResidual () const inline inherited
Return the final nonlinear residual.
Definition at line 526 of file NonlinearSystemBase.h.
{ return _final_residual; }
findImplicitGeometricCouplingEntries()
void NonlinearSystemBase::findImplicitGeometricCouplingEntries (GeometricSearchData & geom_search_data, std::unordered_map< dof_id_type, std::vector< dof_id_type > > & graph) private inherited
Finds the implicit sparsity graph between geometrically related dofs.
Definition at line 1970 of file NonlinearSystemBase.C.
{
  const auto & node_to_elem_map = _mesh.nodeToElemMap();
  const auto & nearest_node_locators = geom_search_data._nearest_node_locators;
  for (const auto & it : nearest_node_locators)
  {
    std::vector<dof_id_type> & secondary_nodes = it.second->_secondary_nodes;
    for (const auto & secondary_node : secondary_nodes)
    {
      std::set<dof_id_type> unique_secondary_indices;
      std::set<dof_id_type> unique_primary_indices;
      auto node_to_elem_pair = node_to_elem_map.find(secondary_node);
      if (node_to_elem_pair != node_to_elem_map.end())
      {
        const std::vector<dof_id_type> & elems = node_to_elem_pair->second;
        // Get the dof indices from each elem connected to the node
        for (const auto & cur_elem : elems)
        {
          std::vector<dof_id_type> dof_indices;
          dofMap().dof_indices(_mesh.elemPtr(cur_elem), dof_indices);
          for (const auto & dof : dof_indices)
            unique_secondary_indices.insert(dof);
        }
      }
      std::vector<dof_id_type> primary_nodes = it.second->_neighbor_nodes[secondary_node];
      for (const auto & primary_node : primary_nodes)
      {
        auto primary_node_to_elem_pair = node_to_elem_map.find(primary_node);
        mooseAssert(primary_node_to_elem_pair != node_to_elem_map.end(),
                    "Missing entry in node to elem map");
        const std::vector<dof_id_type> & primary_node_elems = primary_node_to_elem_pair->second;
        // Get the dof indices from each elem connected to the node
        for (const auto & cur_elem : primary_node_elems)
        {
          std::vector<dof_id_type> dof_indices;
          dofMap().dof_indices(_mesh.elemPtr(cur_elem), dof_indices);
          for (const auto & dof : dof_indices)
            unique_primary_indices.insert(dof);
        }
      }
      for (const auto & secondary_id : unique_secondary_indices)
        for (const auto & primary_id : unique_primary_indices)
        {
          graph[secondary_id].push_back(primary_id);
          graph[primary_id].push_back(secondary_id);
        }
    }
  }
  // handle node-to-node constraints
  const auto & ncs = _constraints.getActiveNodalConstraints();
  for (const auto & nc : ncs)
  {
    std::vector<dof_id_type> primary_dofs;
    std::vector<dof_id_type> & primary_node_ids = nc->getPrimaryNodeId();
    for (const auto & node_id : primary_node_ids)
    {
      Node * node = _mesh.queryNodePtr(node_id);
      if (node && node->processor_id() == this->processor_id())
      {
        getNodeDofs(node_id, primary_dofs);
      }
    }
    _communicator.allgather(primary_dofs);
    std::vector<dof_id_type> secondary_dofs;
    std::vector<dof_id_type> & secondary_node_ids = nc->getSecondaryNodeId();
    for (const auto & node_id : secondary_node_ids)
    {
      Node * node = _mesh.queryNodePtr(node_id);
      if (node && node->processor_id() == this->processor_id())
      {
        getNodeDofs(node_id, secondary_dofs);
      }
    }
    _communicator.allgather(secondary_dofs);
    for (const auto & primary_id : primary_dofs)
      for (const auto & secondary_id : secondary_dofs)
      {
        graph[primary_id].push_back(secondary_id);
        graph[secondary_id].push_back(primary_id);
      }
  }
  // Make every entry sorted and unique
  for (auto & it : graph)
  {
    std::vector<dof_id_type> & row = it.second;
    std::sort(row.begin(), row.end());
    std::vector<dof_id_type>::iterator uit = std::unique(row.begin(), row.end());
    row.resize(uit - row.begin());
  }
}
Referenced by NonlinearSystemBase::addImplicitGeometricCouplingEntries(), and NonlinearSystemBase::augmentSparsity().
flushTaggedMatrices()
void SystemBase::flushTaggedMatrices (const std::set< TagID > & tags) inherited
flushes all matrices associated to tags.
Flush assembles the matrix but doesn't shrink memory allocation
Definition at line 1017 of file SystemBase.C.
{
  for (auto tag : tags)
    if (hasMatrix(tag))
      getMatrix(tag).flush();
}
getActualFieldVariable() [1/2]
template<typename T > template MooseVariableField< RealEigenVector > & SystemBase::getActualFieldVariable< RealEigenVector > (THREAD_ID tid, const std::string & var_name) inherited
Returns a field variable pointer - this includes finite volume variables.
Definition at line 107 of file SystemBase.C.
{
  return *_vars[tid].getActualFieldVariable<T>(var_name);
}
Referenced by BoundsAuxBase::BoundsAuxBase(), Assembly::copyFaceShapes(), Assembly::copyNeighborShapes(), and Assembly::copyShapes().
getActualFieldVariable() [2/2]
template<typename T > template MooseVariableField< RealEigenVector > & SystemBase::getActualFieldVariable< RealEigenVector > (THREAD_ID tid, unsigned int var_number) inherited
Returns a field variable pointer - this includes finite volume variables.
Definition at line 128 of file SystemBase.C.
{
  return *_vars[tid].getActualFieldVariable<T>(var_number);
}
getAllConvergedEigenvalues()
const std::vector< std::pair< Real, Real > > & NonlinearEigenSystem::getAllConvergedEigenvalues () const inline
Get the number of converged eigenvalues.
Returns
all converged eigenvalues as complex numbers
Definition at line 123 of file NonlinearEigenSystem.h.
  {
    return _eigen_values;
  }
Referenced by Eigenvalues::execute().
getConstraintWarehouse()
const ConstraintWarehouse & NonlinearSystemBase::getConstraintWarehouse () const inline inherited
Definition at line 598 of file NonlinearSystemBase.h.
{ return _constraints; }
getConvergedEigenpair()
std::pair< Real, Real > NonlinearEigenSystem::getConvergedEigenpair (dof_id_type n) const
Return the Nth converged eigenvalue and copies the respective eigen vector to the solution vector.
Returns
The Nth converged eigenvalue as a complex number, i.e. the first and the second number is the real and the imaginary part of the eigenvalue, respectively.
Definition at line 440 of file NonlinearEigenSystem.C.
{
  unsigned int n_converged_eigenvalues = getNumConvergedEigenvalues();
  if (n >= n_converged_eigenvalues)
    mooseError(n, " not in [0, ", n_converged_eigenvalues, ")");
  return _eigen_sys.get_eigenpair(n);
}
Referenced by solve().
getConvergedEigenvalue()
std::pair< Real, Real > NonlinearEigenSystem::getConvergedEigenvalue (dof_id_type n) const
Return the Nth converged eigenvalue.
Returns
The Nth converged eigenvalue as a complex number, i.e. the first and the second number is the real and the imaginary part of the eigenvalue, respectively.
Definition at line 431 of file NonlinearEigenSystem.C.
{
  unsigned int n_converged_eigenvalues = getNumConvergedEigenvalues();
  if (n >= n_converged_eigenvalues)
    mooseError(n, " not in [0, ", n_converged_eigenvalues, ")");
  return _eigen_sys.get_eigenvalue(n);
}
Referenced by solve().
getCurrentNonlinearIterationNumber()
unsigned int NonlinearEigenSystem::getCurrentNonlinearIterationNumber () override virtual
Returns the current nonlinear iteration number.
In libmesh, this is updated during the nonlinear solve, so it should be up-to-date.
Implements NonlinearSystemBase.
Definition at line 334 of file NonlinearEigenSystem.C.
{
  mooseError("did not implement yet \n");
  return 0;
}
getDGKernelWarehouse()
MooseObjectTagWarehouse< DGKernelBase > & NonlinearSystemBase::getDGKernelWarehouse () inline inherited
Definition at line 583 of file NonlinearSystemBase.h.
{ return _dg_kernels; }
getDiracKernelWarehouse()
MooseObjectTagWarehouse< DiracKernelBase > & NonlinearSystemBase::getDiracKernelWarehouse () inline inherited
Definition at line 588 of file NonlinearSystemBase.h.
{ return _dirac_kernels; }
getElementDamperWarehouse()
const MooseObjectWarehouse< ElementDamper > & NonlinearSystemBase::getElementDamperWarehouse () const inline inherited
Definition at line 590 of file NonlinearSystemBase.h.
  {
    return _element_dampers;
  }
Referenced by ComputeElemDampingThread::onElement(), and ComputeElemDampingThread::printGeneralExecutionInformation().
getEPS()
EPS NonlinearEigenSystem::getEPS () virtual
Retrieve EPS (SLEPc eigen solver)
Definition at line 381 of file NonlinearEigenSystem.C.
{
  SlepcEigenSolver<Number> * solver =
      cast_ptr<SlepcEigenSolver<Number> *>(&(*_eigen_sys.eigen_solver));
  if (!solver)
    mooseError("Unable to retrieve eigen solver");
  return solver->eps();
}
Referenced by getSNES(), Moose::SlepcSupport::mooseSlepcEigenFormFunctionA(), Moose::SlepcSupport::mooseSlepcEigenFormFunctionAB(), Moose::SlepcSupport::mooseSlepcEigenFormFunctionB(), and Moose::SlepcSupport::mooseSlepcEigenFormJacobianA().
getFieldVariable() [1/2]
template<typename T > template MooseVariableFE< RealEigenVector > & SystemBase::getFieldVariable< RealEigenVector > (THREAD_ID tid, const std::string & var_name) inherited
Gets a reference to a variable of with specified name.
This excludes and cannot return finite volume variables.
Parameters
tid Thread id
var_name variable name
Returns
reference the variable (class)
Definition at line 100 of file SystemBase.C.
{
  return *_vars[tid].getFieldVariable<T>(var_name);
}
Referenced by Marker::getMarkerValue().
getFieldVariable() [2/2]
template<typename T > template MooseVariableFE< RealEigenVector > & SystemBase::getFieldVariable< RealEigenVector > (THREAD_ID tid, unsigned int var_number) inherited
Gets a reference to a variable with specified number.
This excludes and cannot return finite volume variables.
Parameters
tid Thread id
var_number libMesh variable number
Returns
reference the variable (class)
Definition at line 121 of file SystemBase.C.
{
  return *_vars[tid].getFieldVariable<T>(var_number);
}
getFVVariable()
template<typename T > template MooseVariableFV< Real > & SystemBase::getFVVariable< Real > (THREAD_ID tid, const std::string & var_name) inherited
Return a finite volume variable.
Definition at line 114 of file SystemBase.C.
{
  return *_vars[tid].getFVVariable<T>(var_name);
}
getIntegratedBCWarehouse() [1/2]
MooseObjectTagWarehouse< IntegratedBCBase > & NonlinearSystemBase::getIntegratedBCWarehouse () inline inherited
Definition at line 589 of file NonlinearSystemBase.h.
{ return _integrated_bcs; }
Referenced by BoundaryElemIntegrityCheckThread::operator()().
getIntegratedBCWarehouse() [2/2]
const MooseObjectTagWarehouse< IntegratedBCBase > & NonlinearSystemBase::getIntegratedBCWarehouse () const inline inherited
Return the IntegratedBCBase warehouse.
Definition at line 608 of file NonlinearSystemBase.h.
  {
    return _integrated_bcs;
  }
getInterfaceKernelWarehouse()
MooseObjectTagWarehouse< InterfaceKernelBase > & NonlinearSystemBase::getInterfaceKernelWarehouse () inline inherited
Definition at line 584 of file NonlinearSystemBase.h.
  {
    return _interface_kernels;
  }
getKernelWarehouse()
MooseObjectTagWarehouse< KernelBase > & NonlinearSystemBase::getKernelWarehouse () inline inherited
Access functions to Warehouses from outside NonlinearSystemBase.
Definition at line 582 of file NonlinearSystemBase.h.
{ return _kernels; }
Referenced by DOFMapOutput::output().
getMatrix() [1/2]
SparseMatrix< Number > & SystemBase::getMatrix (TagID tag) virtual inherited
Get a raw SparseMatrix.
Reimplemented in DisplacedSystem.
Definition at line 973 of file SystemBase.C.
{
  if (!hasMatrix(tag))
  {
    if (!_subproblem.matrixTagExists(tag))
      mooseError("Cannot retreive matrix with tag ", tag, " because that tag does not exist");
    else
      mooseError("Cannot retreive matrix with tag ",
                 tag,
                 " in system '",
                 name(),
                 "'\nbecause a matrix has not been associated with that tag.");
  }
  return *_tagged_matrices[tag];
}
Referenced by Assembly::addCachedJacobian(), NonlinearSystemBase::addImplicitGeometricCouplingEntries(), Assembly::addJacobianCoupledVarPair(), Assembly::addJacobianLowerD(), Assembly::addJacobianNeighbor(), Assembly::addJacobianNeighborLowerD(), Assembly::addJacobianNonlocal(), SystemBase::addMatrix(), SystemBase::closeTaggedMatrices(), NonlinearSystemBase::computeJacobianInternal(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::constraintJacobians(), SystemBase::disassociateMatrixFromTag(), NonlinearSystemBase::enforceNodalConstraintsJacobian(), SystemBase::flushTaggedMatrices(), DisplacedSystem::getMatrix(), MooseVariableScalar::reinit(), Assembly::setCachedJacobian(), and Assembly::zeroCachedJacobian().
getMatrix() [2/2]
const SparseMatrix< Number > & SystemBase::getMatrix (TagID tag) const virtual inherited
Get a raw SparseMatrix.
Reimplemented in DisplacedSystem.
Definition at line 991 of file SystemBase.C.
{
  if (!hasMatrix(tag))
  {
    if (!_subproblem.matrixTagExists(tag))
      mooseError("Cannot retreive matrix with tag ", tag, " because that tag does not exist");
    else
      mooseError("Cannot retreive matrix with tag ",
                 tag,
                 " in system '",
                 name(),
                 "'\nbecause a matrix has not been associated with that tag.");
  }
  return *_tagged_matrices[tag];
}
getMaxVariableNumber()
unsigned int SystemBase::getMaxVariableNumber () const inline inherited
Returns the maximum number of all variables on the system.
Definition at line 850 of file SystemBase.h.
{ return _max_var_number; }
getMaxVarNDofsPerElem()
std::size_t SystemBase::getMaxVarNDofsPerElem () const inline inherited
Gets the maximum number of dofs used by any one variable on any one element.
Returns
The max
Definition at line 563 of file SystemBase.h.
{ return _max_var_n_dofs_per_elem; }
Referenced by Moose::globalDofIndexToDerivative().
getMaxVarNDofsPerNode()
std::size_t SystemBase::getMaxVarNDofsPerNode () const inline inherited
Gets the maximum number of dofs used by any one variable on any one node.
Returns
The max
Definition at line 570 of file SystemBase.h.
{ return _max_var_n_dofs_per_node; }
getMinQuadratureOrder()
Order SystemBase::getMinQuadratureOrder () virtual inherited
Get minimal quadrature order needed for integrating variables in this system.
Returns
The minimal order of quadrature
Reimplemented in AuxiliarySystem.
Definition at line 230 of file SystemBase.C.
{
  Order order = CONSTANT;
  const std::vector<MooseVariableFieldBase *> & vars = _vars[0].fieldVariables();
  for (const auto & var : vars)
  {
    FEType fe_type = var->feType();
    if (fe_type.default_quadrature_order() > order)
      order = fe_type.default_quadrature_order();
  }
  return order;
}
getMooseKSPNormType()
Moose::MooseKSPNormType NonlinearSystemBase::getMooseKSPNormType () inline inherited
Definition at line 553 of file NonlinearSystemBase.h.
{ return _ksp_norm; }
Referenced by Moose::PetscSupport::petscSetDefaultKSPNormType().
getNodalBCWarehouse()
const MooseObjectTagWarehouse< NodalBCBase > & NonlinearSystemBase::getNodalBCWarehouse () const inline inherited
Return the NodalBCBase warehouse.
Definition at line 603 of file NonlinearSystemBase.h.
{ return _nodal_bcs; }
getNodalDamperWarehouse()
const MooseObjectWarehouse< NodalDamper > & NonlinearSystemBase::getNodalDamperWarehouse () const inline inherited
Definition at line 594 of file NonlinearSystemBase.h.
  {
    return _nodal_dampers;
  }
Referenced by ComputeNodalDampingThread::onNode(), and ComputeNodalDampingThread::printGeneralExecutionInformation().
getNodeDofs()
void NonlinearSystemBase::getNodeDofs (dof_id_type node_id, std::vector< dof_id_type > & dofs) protected inherited
Definition at line 1957 of file NonlinearSystemBase.C.
{
  const Node & node = _mesh.nodeRef(node_id);
  unsigned int s = number();
  if (node.has_dofs(s))
  {
    for (unsigned int v = 0; v < nVariables(); v++)
      for (unsigned int c = 0; c < node.n_comp(s, v); c++)
        dofs.push_back(node.dof_number(s, v, c));
  }
}
Referenced by NonlinearSystemBase::findImplicitGeometricCouplingEntries().
getNumConvergedEigenvalues()
unsigned int NonlinearEigenSystem::getNumConvergedEigenvalues () const inline
Get the number of converged eigenvalues.
Returns
The number of converged eigenvalues
Definition at line 75 of file NonlinearEigenSystem.h.
{ return _eigen_sys.get_n_converged(); };
Referenced by getConvergedEigenpair(), getConvergedEigenvalue(), and solve().
getPCSide()
Moose::PCSideType NonlinearSystemBase::getPCSide () inline inherited
Definition at line 549 of file NonlinearSystemBase.h.
{ return _pc_side; }
Referenced by Moose::PetscSupport::petscSetDefaultPCSide().
getPreconditioner()
MoosePreconditioner const * NonlinearSystemBase::getPreconditioner () const inherited
Definition at line 3381 of file NonlinearSystemBase.C.
{
  return _preconditioner.get();
}
Referenced by ConsoleUtils::outputExecutionInformation().
getPredictor()
Predictor * NonlinearSystemBase::getPredictor () inline inherited
Definition at line 545 of file NonlinearSystemBase.h.
{ return _predictor.get(); }
Referenced by AB2PredictorCorrector::estimateTimeError().
getResidualNonTimeVector()
NumericVector< Number > & NonlinearSystemBase::getResidualNonTimeVector () inherited
Return a numeric vector that is associated with the nontime tag.
Definition at line 971 of file NonlinearSystemBase.C.
{
  if (!_Re_non_time)
  {
    _Re_non_time_tag = _fe_problem.addVectorTag("NONTIME");
    // Most applications don't need the expense of ghosting
    ParallelType ptype = _need_residual_ghosted ? GHOSTED : PARALLEL;
    _Re_non_time = &addVector(_Re_non_time_tag, false, ptype);
  }
  else if (_need_residual_ghosted && _Re_non_time->type() == PARALLEL)
  {
    const auto vector_name = _subproblem.vectorTagName(_Re_non_time_tag);
    // If an application changes its mind, the libMesh API lets us
    // change the vector.
    _Re_non_time = &system().add_vector(vector_name, false, GHOSTED);
  }
  return *_Re_non_time;
}
Referenced by PseudoTimestep::currentResidualNorm(), NonlinearSystemBase::NonlinearSystemBase(), and NonlinearSystemBase::residualVector().
getResidualTimeVector()
NumericVector< Number > & NonlinearSystemBase::getResidualTimeVector () inherited
Return a numeric vector that is associated with the time tag.
Definition at line 948 of file NonlinearSystemBase.C.
{
  if (!_Re_time)
  {
    _Re_time_tag = _fe_problem.addVectorTag("TIME");
    // Most applications don't need the expense of ghosting
    ParallelType ptype = _need_residual_ghosted ? GHOSTED : PARALLEL;
    _Re_time = &addVector(_Re_time_tag, false, ptype);
  }
  else if (_need_residual_ghosted && _Re_time->type() == PARALLEL)
  {
    const auto vector_name = _subproblem.vectorTagName(_Re_time_tag);
    // If an application changes its mind, the libMesh API lets us
    // change the vector.
    _Re_time = &system().add_vector(vector_name, false, GHOSTED);
  }
  return *_Re_time;
}
Referenced by NonlinearSystemBase::residualVector().
getScalarVariable() [1/2]
MooseVariableScalar & SystemBase::getScalarVariable (THREAD_ID tid, const std::string & var_name) const virtual inherited
Gets a reference to a scalar variable with specified number.
Parameters
tid Thread id
var_name A string which is the name of the variable to get.
Returns
reference the variable (class)
Definition at line 134 of file SystemBase.C.
{
  MooseVariableScalar * var = dynamic_cast<MooseVariableScalar *>(_vars[tid].getVariable(var_name));
  if (!var)
    mooseError("Scalar variable '" + var_name + "' does not exist in this system");
  return *var;
}
Referenced by Assembly::addJacobianOffDiagScalar(), MortarScalarBase::computeOffDiagJacobianScalar(), ArrayIntegratedBC::computeOffDiagJacobianScalar(), IntegratedBC::computeOffDiagJacobianScalar(), VectorIntegratedBC::computeOffDiagJacobianScalar(), ArrayKernel::computeOffDiagJacobianScalar(), Kernel::computeOffDiagJacobianScalar(), ODEKernel::computeOffDiagJacobianScalar(), ScalarLagrangeMultiplier::computeOffDiagJacobianScalar(), VectorKernel::computeOffDiagJacobianScalar(), KernelScalarBase::computeOffDiagJacobianScalarLocal(), MortarScalarBase::computeScalarOffDiagJacobianScalar(), KernelScalarBase::computeScalarOffDiagJacobianScalar(), DMMooseSetVariables(), Assembly::init(), ReferenceResidualProblem::initialSetup(), and NonlinearSystemBase::setupScalingData().
getScalarVariable() [2/2]
MooseVariableScalar & SystemBase::getScalarVariable (THREAD_ID tid, unsigned int var_number) const virtual inherited
Gets a reference to a variable with specified number.
Parameters
tid Thread id
var_number libMesh variable number
Returns
reference the variable (class)
Definition at line 143 of file SystemBase.C.
{
  MooseVariableScalar * var =
      dynamic_cast<MooseVariableScalar *>(_vars[tid].getVariable(var_number));
  if (!var)
    mooseError("variable #" + Moose::stringify(var_number) + " does not exist in this system");
  return *var;
}
getScalarVariables()
const std::vector< MooseVariableScalar * > & SystemBase::getScalarVariables (THREAD_ID tid) inline inherited
Definition at line 737 of file SystemBase.h.
  {
    return _vars[tid].scalars();
  }
Referenced by Assembly::addResidualScalar(), ODEKernel::computeJacobian(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), AuxiliarySystem::computeScalarVars(), Assembly::init(), SystemBase::initSolutionState(), NonlinearThread::onElement(), Assembly::prepareOffDiagScalar(), and Assembly::prepareScalar().
getSharedTimeIntegrator()
std::shared_ptr< TimeIntegrator > SystemBase::getSharedTimeIntegrator () inline inherited
Definition at line 872 of file SystemBase.h.
{ return _time_integrator; }
Referenced by DisplacedProblem::DisplacedProblem().
getSNES()
SNES NonlinearEigenSystem::getSNES () override virtual
Retrieve snes from slepc eigen solver.
It is valid for only nonlinear eigen solver. You should see a big error if you do this for linear solver.
Implements NonlinearSystemBase.
Definition at line 366 of file NonlinearEigenSystem.C.
{
  EPS eps = getEPS();
  if (_eigen_problem.isNonlinearEigenvalueSolver())
  {
    SNES snes = nullptr;
    Moose::SlepcSupport::mooseSlepcEPSGetSNES(eps, &snes);
    return snes;
  }
  else
    mooseError("There is no SNES in linear eigen solver");
}
Referenced by Moose::SlepcSupport::mooseEPSFormMatrices(), and Moose::SlepcSupport::mooseSlepcEigenFormFunctionMFFD().
getSplit()
std::shared_ptr< Split > NonlinearSystemBase::getSplit (const std::string & name) inherited
Retrieves a split by name.
Parameters
name The name of the split
Definition at line 716 of file NonlinearSystemBase.C.
{
  return _splits.getActiveObject(name);
}
Referenced by Split::setup(), and NonlinearSystemBase::setupFieldDecomposition().
getStandardFieldVariableNames()
void SystemBase::getStandardFieldVariableNames (std::vector< VariableName > & std_field_variables) const inherited
getSubdomainsForVar() [1/2]
const std::set< SubdomainID > & SystemBase::getSubdomainsForVar (const std::string & var_name) const inline inherited
Get the block where a variable of this system is defined.
Parameters
var_name The name of the variable
Returns
the set of subdomain ids where the variable is active (defined)
Definition at line 753 of file SystemBase.h.
  {
    return getSubdomainsForVar(getVariable(0, var_name).number());
  }
getSubdomainsForVar() [2/2]
const std::set< SubdomainID > & SystemBase::getSubdomainsForVar (unsigned int var_number) const inline inherited
Definition at line 742 of file SystemBase.h.
  {
    return _var_map.at(var_number);
  }
Referenced by NonlinearSystemBase::checkKernelCoverage(), and SystemBase::getSubdomainsForVar().
getTimeIntegrator() [1/2]
TimeIntegrator * SystemBase::getTimeIntegrator () inline inherited
Definition at line 869 of file SystemBase.h.
{ return _time_integrator.get(); }
Referenced by Transient::endStep(), AB2PredictorCorrector::estimateTimeError(), Transient::getTimeIntegratorName(), MooseVariableData< OutputType >::MooseVariableData(), and Transient::preExecute().
getTimeIntegrator() [2/2]
const TimeIntegrator * SystemBase::getTimeIntegrator () const inline inherited
Definition at line 870 of file SystemBase.h.
{ return _time_integrator.get(); }
getVariable() [1/2]
MooseVariableFieldBase & SystemBase::getVariable (THREAD_ID tid, const std::string & var_name) const inherited
Gets a reference to a variable of with specified name.
Parameters
tid Thread id
var_name variable name
Returns
reference the variable (class)
Definition at line 79 of file SystemBase.C.
{
  MooseVariableFieldBase * var =
      dynamic_cast<MooseVariableFieldBase *>(_vars[tid].getVariable(var_name));
  if (!var)
    mooseError("Variable '", var_name, "' does not exist in this system");
  return *var;
}
Referenced by AdaptivityAction::act(), Assembly::addJacobianBlock(), Assembly::addJacobianBlockNonlocal(), FEProblemBase::addJacobianBlockTags(), Assembly::addJacobianNeighbor(), NonlocalIntegratedBC::computeNonlocalOffDiagJacobian(), NonlocalKernel::computeNonlocalOffDiagJacobian(), Assembly::copyFaceShapes(), Assembly::copyNeighborShapes(), Assembly::copyShapes(), SystemBase::copyVars(), DMMooseSetVariables(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), NodeElemConstraint::getConnectedDofIndices(), NodeFaceConstraint::getConnectedDofIndices(), SystemBase::getSubdomainsForVar(), ResidualObject::getVariable(), Assembly::init(), NodalNormalsPreprocessor::initialize(), ReferenceResidualProblem::initialSetup(), Assembly::initNonlocalCoupling(), PNGOutput::makeMeshFunc(), FEProblemBase::prepare(), Assembly::prepareBlock(), Assembly::prepareBlockNonlocal(), AddPeriodicBCAction::setPeriodicVars(), NonlinearSystemBase::setupScalingData(), UpdateErrorVectorsThread::UpdateErrorVectorsThread(), and VariableCondensationPreconditioner::VariableCondensationPreconditioner().
getVariable() [2/2]
MooseVariableFieldBase & SystemBase::getVariable (THREAD_ID tid, unsigned int var_number) const inherited
Gets a reference to a variable with specified number.
Parameters
tid Thread id
var_number libMesh variable number
Returns
reference the variable (class)
Definition at line 89 of file SystemBase.C.
{
  if (var_number < _numbered_vars[tid].size())
    if (_numbered_vars[tid][var_number])
      return *_numbered_vars[tid][var_number];
  mooseError("Variable #", Moose::stringify(var_number), " does not exist in this system");
}
getVariableBlocks()
const std::set< SubdomainID > * SystemBase::getVariableBlocks (unsigned int var_number) virtual inherited
Get the block where a variable of this system is defined.
Parameters
var_number The number of the variable
Returns
the set of subdomain ids where the variable is active (defined)
Definition at line 153 of file SystemBase.C.
{
  mooseAssert(_var_map.find(var_number) != _var_map.end(), "Variable does not exist.");
  if (_var_map[var_number].empty())
    return nullptr;
  else
    return &_var_map[var_number];
}
Referenced by PhysicsBasedPreconditioner::addSystem().
getVariableGlobalDoFs()
const std::vector< dof_id_type > & SystemBase::getVariableGlobalDoFs () inline inherited
Get the global dof indices of a variable, this needs to be called after the indices have been set by setVariableGlobalDoFs
Definition at line 825 of file SystemBase.h.
{ return _var_all_dof_indices; }
getVariableNames()
const std::vector< VariableName > & SystemBase::getVariableNames () const inline inherited
Definition at line 843 of file SystemBase.h.
{ return _vars[0].names(); }
Referenced by MooseEigenSystem::buildSystemDoFIndices(), NonlinearSystemBase::checkKernelCoverage(), SystemBase::hasVariable(), SystemBase::isArrayVariable(), AddPeriodicBCAction::setPeriodicVars(), and SingleMatrixPreconditioner::SingleMatrixPreconditioner().
getVariables()
const std::vector< MooseVariableFieldBase * > & SystemBase::getVariables (THREAD_ID tid) inline inherited
Definition at line 732 of file SystemBase.h.
  {
    return _vars[tid].fieldVariables();
  }
Referenced by Assembly::addJacobianOffDiagScalar(), Assembly::addResidual(), Assembly::addResidualLower(), Assembly::addResidualNeighbor(), MooseMesh::cacheFaceInfoVariableOwnership(), MooseMesh::cacheFVElementalDoFs(), Assembly::cacheResidual(), Assembly::cacheResidualLower(), Assembly::cacheResidualNeighbor(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), Assembly::init(), Assembly::initNonlocalCoupling(), SystemBase::initSolutionState(), Assembly::prepareLowerD(), Assembly::prepareNeighbor(), Assembly::prepareOffDiagScalar(), Assembly::prepareResidual(), Assembly::setResidual(), and Assembly::setResidualNeighbor().
getVector() [1/4]
NumericVector< Number > & SystemBase::getVector (const std::string & name) virtual inherited
Get a raw NumericVector by name.
Get a raw NumericVector with the given name.
Reimplemented in DisplacedSystem.
Definition at line 882 of file SystemBase.C.
{
  return system().get_vector(name);
}
Referenced by Assembly::addCachedResiduals(), Assembly::addResidual(), Assembly::addResidualLower(), Assembly::addResidualNeighbor(), Assembly::addResidualScalar(), SystemBase::addVector(), NonlinearSystemBase::assembleScalingVector(), SystemBase::closeTaggedVector(), FEProblemBase::computeBounds(), FEProblemBase::computeNearNullSpace(), FEProblemBase::computeNullSpace(), NonlinearSystemBase::computeResidualAndJacobianTags(), NonlinearSystemBase::computeResidualTags(), CentralDifference::computeTimeDerivatives(), FEProblemBase::computeTransposeNullSpace(), SystemBase::disassociateVectorFromTag(), DisplacedSystem::getVector(), Assembly::hasScalingVector(), SystemBase::needSolutionState(), ReferenceResidualProblem::ReferenceResidualProblem(), MooseVariableScalar::reinit(), PicardSolve::saveVariableValues(), SecantSolve::saveVariableValues(), SteffensenSolve::saveVariableValues(), NonlinearSystemBase::setPreviousNewtonSolution(), TaggingInterface::setResidual(), SystemBase::solutionPreviousNewton(), SystemBase::solutionState(), MultiAppDofCopyTransfer::transfer(), PicardSolve::transformVariables(), SecantSolve::transformVariables(), SteffensenSolve::transformVariables(), and SystemBase::zeroTaggedVector().
getVector() [2/4]
const NumericVector< Number > & SystemBase::getVector (const std::string & name) const virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 888 of file SystemBase.C.
{
  return system().get_vector(name);
}
getVector() [3/4]
NumericVector< Number > & SystemBase::getVector (TagID tag) virtual inherited
Get a raw NumericVector by tag.
Reimplemented in DisplacedSystem.
Definition at line 894 of file SystemBase.C.
{
  if (!hasVector(tag))
  {
    if (!_subproblem.vectorTagExists(tag))
      mooseError("Cannot retreive vector with tag ", tag, " because that tag does not exist");
    else
      mooseError("Cannot retreive vector with tag ",
                 tag,
                 " in system '",
                 name(),
                 "'\nbecause a vector has not been associated with that tag.");
  }
  return *_tagged_vectors[tag];
}
getVector() [4/4]
const NumericVector< Number > & SystemBase::getVector (TagID tag) const virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 912 of file SystemBase.C.
{
  if (!hasVector(tag))
  {
    if (!_subproblem.vectorTagExists(tag))
      mooseError("Cannot retreive vector with tag ", tag, " because that tag does not exist");
    else
      mooseError("Cannot retreive vector with tag ",
                 tag,
                 " in system '",
                 name(),
                 "'\nbecause a vector has not been associated with that tag.");
  }
  return *_tagged_vectors[tag];
}
hasDiagSaveIn()
bool NonlinearSystemBase::hasDiagSaveIn () const inline inherited
Weather or not the nonlinear system has diagonal Jacobian save-ins.
Definition at line 623 of file NonlinearSystemBase.h.
{ return _has_diag_save_in || _has_nodalbc_diag_save_in; }
Referenced by NonlinearSystemBase::computeJacobianInternal().
hasMatrix()
virtual bool SystemBase::hasMatrix (TagID tag) const inline virtual inherited
Check if the tagged matrix exists in the system.
Reimplemented in DisplacedSystem.
Definition at line 328 of file SystemBase.h.
  {
    return tag < _tagged_matrices.size() && _tagged_matrices[tag];
  }
Referenced by SystemBase::activeAllMatrixTags(), Assembly::addCachedJacobian(), NonlinearSystemBase::addImplicitGeometricCouplingEntries(), Assembly::addJacobianCoupledVarPair(), Assembly::addJacobianLowerD(), Assembly::addJacobianNeighbor(), Assembly::addJacobianNeighborLowerD(), Assembly::addJacobianNonlocal(), SystemBase::addMatrix(), Assembly::cacheJacobian(), Assembly::cacheJacobianBlock(), Assembly::cacheJacobianBlockNonzero(), Assembly::cacheJacobianCoupledVarPair(), Assembly::cacheJacobianMortar(), Assembly::cacheJacobianNeighbor(), Assembly::cacheJacobianNonlocal(), SystemBase::closeTaggedMatrices(), NonlinearSystemBase::computeJacobianInternal(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::constraintJacobians(), SystemBase::disassociateMatrixFromTag(), NonlinearSystemBase::enforceNodalConstraintsJacobian(), SystemBase::flushTaggedMatrices(), SystemBase::getMatrix(), DisplacedSystem::hasMatrix(), MooseVariableScalar::reinit(), SystemBase::removeMatrix(), Assembly::setCachedJacobian(), and Assembly::zeroCachedJacobian().
hasSaveIn()
bool NonlinearSystemBase::hasSaveIn () const inline inherited
Weather or not the nonlinear system has save-ins.
Definition at line 618 of file NonlinearSystemBase.h.
{ return _has_save_in || _has_nodalbc_save_in; }
Referenced by NonlinearSystemBase::computeResidualTags().
hasScalarVariable()
bool SystemBase::hasScalarVariable (const std::string & var_name) const virtual inherited
Definition at line 825 of file SystemBase.C.
{
  if (system().has_variable(var_name))
    return system().variable_type(var_name).family == SCALAR;
  else
    return false;
}
Referenced by MortarScalarBase::computeJacobian(), NonlinearSystemBase::computeJacobianInternal(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), SystemBase::copyVars(), postAddResidualObject(), AddPeriodicBCAction::setPeriodicVars(), and NonlinearSystemBase::setupScalingData().
hasSolutionState()
bool SystemBase::hasSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) const inline virtual inherited
Whether or not the system has the solution state (0 = current, 1 = old, 2 = older, etc).
Reimplemented in DisplacedSystem.
Definition at line 1004 of file SystemBase.h.
{
  return _solution_states[static_cast<unsigned short>(iteration_type)].size() > state;
}
Referenced by PointwiseRenormalizeVector::execute(), PointwiseRenormalizeVector::finalize(), DisplacedSystem::hasSolutionState(), SystemBase::needSolutionState(), SystemBase::restoreSolutions(), ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes(), and SystemBase::solutionState().
hasVarCopy()
bool SystemBase::hasVarCopy () const inline inherited
Whether or not there are variables to be restarted from an Exodus mesh file.
Definition at line 875 of file SystemBase.h.
{ return _var_to_copy.size() > 0; }
hasVariable()
bool SystemBase::hasVariable (const std::string & var_name) const virtual inherited
Query a system for a variable.
Parameters
var_name name of the variable
Returns
true if the variable exists
Definition at line 800 of file SystemBase.C.
{
  auto & names = getVariableNames();
  if (system().has_variable(var_name))
    return system().variable_type(var_name).family != SCALAR;
  if (std::find(names.begin(), names.end(), var_name) != names.end())
    // array variable
    return true;
  else
    return false;
}
Referenced by ADDGKernel::ADDGKernel(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayKernel::ArrayKernel(), SystemBase::copyVars(), DGKernel::DGKernel(), DMMooseSetVariables(), FEProblemBase::duplicateVariableCheck(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), Kernel::Kernel(), PNGOutput::makeMeshFunc(), MultiAppVariableValueSamplePostprocessorTransfer::MultiAppVariableValueSamplePostprocessorTransfer(), NonlinearSystemBase::setupScalingData(), and Coupleable::writableCoupledValue().
hasVector() [1/2]
bool SystemBase::hasVector (const std::string & tag_name) const inherited
Check if the named vector exists in the system.
Definition at line 873 of file SystemBase.C.
{
  return system().have_vector(name);
}
Referenced by FEProblemBase::addCachedResidualDirectly(), Assembly::addCachedResiduals(), Assembly::addResidual(), Assembly::addResidualLower(), Assembly::addResidualNeighbor(), Assembly::addResidualScalar(), SystemBase::addVector(), NonlinearSystemBase::assembleScalingVector(), Assembly::cacheResidual(), Assembly::cacheResidualLower(), Assembly::cacheResidualNeighbor(), SystemBase::closeTaggedVector(), FEProblemBase::computeBounds(), NonlinearSystemBase::computeResidualTags(), CentralDifference::computeTimeDerivatives(), SystemBase::disassociateVectorFromTag(), SystemBase::getVector(), DisplacedSystem::hasVector(), MooseVariableScalar::reinit(), SystemBase::removeVector(), SubProblem::selectVectorTagsFromSystem(), NonlinearSystemBase::setPreviousNewtonSolution(), TaggingInterface::setResidual(), SystemBase::solutionPreviousNewton(), and SystemBase::zeroTaggedVector().
hasVector() [2/2]
virtual bool SystemBase::hasVector (TagID tag_id) const inline virtual inherited
Check if the tagged vector exists in the system.
Reimplemented in DisplacedSystem.
Definition at line 249 of file SystemBase.h.
  {
    return tag_id < _tagged_vectors.size() && _tagged_vectors[tag_id];
  }
haveFieldSplitPreconditioner()
bool NonlinearSystemBase::haveFieldSplitPreconditioner () const inline inherited
Definition at line 113 of file NonlinearSystemBase.h.
{ return _use_field_split_preconditioner; }
Referenced by FEProblemBase::solve().
haveFiniteDifferencedPreconditioner()
bool NonlinearSystemBase::haveFiniteDifferencedPreconditioner () const inline inherited
Definition at line 109 of file NonlinearSystemBase.h.
  {
    return _use_finite_differenced_preconditioner;
  }
ignoreVariablesForAutoscaling()
void NonlinearSystemBase::ignoreVariablesForAutoscaling (const std::vector< std::string > & ignore_variables_for_autoscaling) inline inherited
Definition at line 666 of file NonlinearSystemBase.h.
  {
    _ignore_variables_for_autoscaling = ignore_variables_for_autoscaling;
  }
Referenced by FEProblemSolve::FEProblemSolve().
init()
void NonlinearSystemBase::init () override virtual inherited
Initialize the system.
Reimplemented from SystemBase.
Reimplemented in NonlinearSystem.
Definition at line 185 of file NonlinearSystemBase.C.
{
  SystemBase::init();
  if (_fe_problem.hasDampers())
    setupDampers();
  _current_solution = _sys.current_local_solution.get();
  if (_serialized_solution.get())
    _serialized_solution->init(_sys.n_dofs(), false, SERIAL);
  if (_residual_copy.get())
    _residual_copy->init(_sys.n_dofs(), false, SERIAL);
}
Referenced by NonlinearSystem::init().
initializeObjects()
virtual void SystemBase::initializeObjects () inline virtual inherited
Called only once, just before the solve begins so objects can do some precalculations.
Definition at line 155 of file SystemBase.h.
{};
initialSetup()
void NonlinearSystemBase::initialSetup () override virtual inherited
Setup Functions.
Reimplemented from SystemBase.
Definition at line 231 of file NonlinearSystemBase.C.
{
  TIME_SECTION("nlInitialSetup", 2, "Setting Up Nonlinear System");
  SystemBase::initialSetup();
  {
    TIME_SECTION("kernelsInitialSetup", 2, "Setting Up Kernels/BCs/Constraints");
    for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    {
      _kernels.initialSetup(tid);
      _nodal_kernels.initialSetup(tid);
      _dirac_kernels.initialSetup(tid);
      if (_doing_dg)
        _dg_kernels.initialSetup(tid);
      _interface_kernels.initialSetup(tid);
      _element_dampers.initialSetup(tid);
      _nodal_dampers.initialSetup(tid);
      _integrated_bcs.initialSetup(tid);
      if (_fe_problem.haveFV())
      {
        std::vector<FVElementalKernel *> fv_elemental_kernels;
        _fe_problem.theWarehouse()
            .query()
            .template condition<AttribSystem>("FVElementalKernel")
            .template condition<AttribThread>(tid)
            .queryInto(fv_elemental_kernels);
        for (auto * fv_kernel : fv_elemental_kernels)
          fv_kernel->initialSetup();
        std::vector<FVFluxKernel *> fv_flux_kernels;
        _fe_problem.theWarehouse()
            .query()
            .template condition<AttribSystem>("FVFluxKernel")
            .template condition<AttribThread>(tid)
            .queryInto(fv_flux_kernels);
        for (auto * fv_kernel : fv_flux_kernels)
          fv_kernel->initialSetup();
      }
    }
    _scalar_kernels.initialSetup();
    _constraints.initialSetup();
    _general_dampers.initialSetup();
    _nodal_bcs.initialSetup();
  }
  {
    TIME_SECTION("mortarSetup", 2, "Initializing Mortar Interfaces");
    auto create_mortar_functors = [this](const bool displaced)
    {
      // go over mortar interfaces and construct functors
      const auto & mortar_interfaces = _fe_problem.getMortarInterfaces(displaced);
      for (const auto & mortar_interface : mortar_interfaces)
      {
        const auto primary_secondary_boundary_pair = mortar_interface.first;
        if (!_constraints.hasActiveMortarConstraints(primary_secondary_boundary_pair, displaced))
          continue;
        const auto & mortar_generation_object = mortar_interface.second;
        auto & mortar_constraints =
            _constraints.getActiveMortarConstraints(primary_secondary_boundary_pair, displaced);
        auto & subproblem = displaced
                                ? static_cast<SubProblem &>(*_fe_problem.getDisplacedProblem())
                                : static_cast<SubProblem &>(_fe_problem);
        auto & mortar_functors =
            displaced ? _displaced_mortar_functors : _undisplaced_mortar_functors;
        mortar_functors.emplace(primary_secondary_boundary_pair,
                                ComputeMortarFunctor(mortar_constraints,
                                                     mortar_generation_object,
                                                     subproblem,
                                                     _fe_problem,
                                                     displaced,
                                                     subproblem.assembly(0, number())));
      }
    };
    create_mortar_functors(false);
    create_mortar_functors(true);
  }
  if (_automatic_scaling)
  {
    if (_off_diagonals_in_auto_scaling)
      _scaling_matrix = std::make_unique<OffDiagonalScalingMatrix<Number>>(_communicator);
    else
      _scaling_matrix = std::make_unique<DiagonalMatrix<Number>>(_communicator);
  }
}
initSolutionState()
void SystemBase::initSolutionState () virtual inherited
Initializes the solution state.
Reimplemented in DisplacedSystem.
Definition at line 1321 of file SystemBase.C.
{
  // Default is the current solution
  unsigned int state = 0;
  // Add additional states as required by the variable states requested
  for (const auto & var : getVariables(/* tid = */ 0))
    state = std::max(state, var->oldestSolutionStateRequested());
  for (const auto & var : getScalarVariables(/* tid = */ 0))
    state = std::max(state, var->oldestSolutionStateRequested());
  needSolutionState(state, Moose::SolutionIterationType::Time);
  _solution_states_initialized = true;
}
Referenced by DisplacedSystem::initSolutionState().
isArrayVariable()
bool SystemBase::isArrayVariable (const std::string & var_name) const virtual inherited
If a variable is an array variable.
Definition at line 813 of file SystemBase.C.
{
  auto & names = getVariableNames();
  if (!system().has_variable(var_name) &&
      std::find(names.begin(), names.end(), var_name) != names.end())
    // array variable
    return true;
  else
    return false;
}
isScalarVariable()
bool SystemBase::isScalarVariable (unsigned int var_name) const virtual inherited
Definition at line 834 of file SystemBase.C.
{
  return (system().variable(var_num).type().family == SCALAR);
}
Referenced by Assembly::init(), ReferenceResidualProblem::initialSetup(), and Assembly::initNonlocalCoupling().
jacobianSetup()
void NonlinearSystemBase::jacobianSetup () override virtual inherited
Reimplemented from SystemBase.
Definition at line 2569 of file NonlinearSystemBase.C.
{
  SystemBase::jacobianSetup();
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    _kernels.jacobianSetup(tid);
    _nodal_kernels.jacobianSetup(tid);
    _dirac_kernels.jacobianSetup(tid);
    if (_doing_dg)
      _dg_kernels.jacobianSetup(tid);
    _interface_kernels.jacobianSetup(tid);
    _element_dampers.jacobianSetup(tid);
    _nodal_dampers.jacobianSetup(tid);
    _integrated_bcs.jacobianSetup(tid);
  }
  _scalar_kernels.jacobianSetup();
  _constraints.jacobianSetup();
  _general_dampers.jacobianSetup();
  _nodal_bcs.jacobianSetup();
  // Avoid recursion
  if (this == &_fe_problem.currentNonlinearSystem())
    _fe_problem.jacobianSetup();
  _app.solutionInvalidity().resetSolutionInvalidCurrentIteration();
}
Referenced by NonlinearSystemBase::computeJacobianInternal().
matrixTagActive()
bool SystemBase::matrixTagActive (TagID tag) const virtual inherited
If or not a matrix tag is active.
Definition at line 1117 of file SystemBase.C.
{
  mooseAssert(_subproblem.matrixTagExists(tag), "Matrix tag " << tag << " does not exist");
  return tag < _matrix_tag_active_flags.size() && _matrix_tag_active_flags[tag];
}
mesh() [1/2]
virtual MooseMesh & SystemBase::mesh () inline virtual inherited
Definition at line 96 of file SystemBase.h.
{ return _mesh; }
Referenced by CreateDisplacedProblemAction::addProxyRelationshipManagers(), NonlinearSystemBase::computeScaling(), DMMooseGetEmbedding_Private(), DMSetUp_Moose_Pre(), SolutionIC::initialSetup(), MooseVariableData< OutputType >::MooseVariableData(), ComputeNodalKernelJacobiansThread::onNode(), ComputeNodalKernelsThread::onNode(), and ComputeNodalUserObjectsThread::onNode().
mesh() [2/2]
virtual const MooseMesh & SystemBase::mesh () const inline virtual inherited
Definition at line 97 of file SystemBase.h.
{ return _mesh; }
mortarConstraints()
void NonlinearSystemBase::mortarConstraints (Moose::ComputeType compute_type, const std::set< TagID > & vector_tags, const std::set< TagID > & matrix_tags) protected inherited
Do mortar constraint residual/jacobian computations.
Definition at line 3627 of file NonlinearSystemBase.C.
{
  parallel_object_only();
  try
  {
    for (auto & map_pr : _undisplaced_mortar_functors)
      map_pr.second(compute_type, vector_tags, matrix_tags);
    for (auto & map_pr : _displaced_mortar_functors)
      map_pr.second(compute_type, vector_tags, matrix_tags);
  }
  catch (MetaPhysicL::LogicError &)
  {
    mooseError(
        "We caught a MetaPhysicL error in NonlinearSystemBase::mortarConstraints. This is very "
        "likely due to AD not having a sufficiently large derivative container size. Please run "
        "MOOSE configure with the '--with-derivative-size=<n>' option");
  }
}
Referenced by NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualAndJacobianInternal(), and NonlinearSystemBase::computeResidualInternal().
name()
const std::string & SystemBase::name () const virtual inherited
Definition at line 1297 of file SystemBase.C.
{
  return system().name();
}
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addConstraint(), NonlinearSystemBase::addDamper(), NonlinearSystemBase::addDGKernel(), NonlinearSystemBase::addDiracKernel(), NonlinearSystemBase::addInterfaceKernel(), AuxiliarySystem::addKernel(), MooseEigenSystem::addKernel(), NonlinearSystemBase::addKernel(), SystemBase::addMatrix(), NonlinearSystemBase::addNodalKernel(), AuxiliarySystem::addScalarKernel(), NonlinearSystemBase::addScalarKernel(), NonlinearSystemBase::addSplit(), AuxiliarySystem::addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), AuxiliarySystem::addVariable(), SystemBase::addVariable(), SystemBase::addVector(), NonlinearSystemBase::checkKernelCoverage(), SystemBase::closeTaggedVector(), DisplacedProblem::DisplacedProblem(), SystemBase::getMatrix(), NonlinearSystemBase::getSplit(), SystemBase::getVector(), DisplacedSystem::getVector(), SystemBase::hasVector(), postAddResidualObject(), SystemBase::removeMatrix(), SystemBase::removeVector(), NonlinearSystemBase::setupScalingData(), SystemBase::solutionState(), and SystemBase::zeroTaggedVector().
needBoundaryMaterialOnSide()
bool NonlinearSystemBase::needBoundaryMaterialOnSide (BoundaryID bnd_id, THREAD_ID tid) const inherited
Indicated whether this system needs material properties on boundaries.
Returns
Boolean if IntegratedBCs are active
Definition at line 3595 of file NonlinearSystemBase.C.
{
  return _integrated_bcs.hasActiveBoundaryObjects(bnd_id, tid);
}
needInterfaceMaterialOnSide()
bool NonlinearSystemBase::needInterfaceMaterialOnSide (BoundaryID bnd_id, THREAD_ID tid) const inherited
Indicated whether this system needs material properties on interfaces.
Returns
Boolean if IntegratedBCs are active
Definition at line 3601 of file NonlinearSystemBase.C.
{
  return _interface_kernels.hasActiveBoundaryObjects(bnd_id, tid);
}
needSolutionState()
void SystemBase::needSolutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) virtual inherited
Registers that the solution state state is needed.
Reimplemented in DisplacedSystem.
Definition at line 1393 of file SystemBase.C.
{
  libmesh_parallel_only(this->comm());
  if (hasSolutionState(state, iteration_type))
    return;
  auto & solution_states = _solution_states[static_cast<unsigned short>(iteration_type)];
  solution_states.resize(state + 1);
  // The 0-th (current) solution state is owned by libMesh
  if (!solution_states[0])
    solution_states[0] = &solutionInternal();
  else
    mooseAssert(solution_states[0] == &solutionInternal(), "Inconsistent current solution");
  // We will manually add all states past current
  for (unsigned int i = 1; i <= state; ++i)
    if (!solution_states[i])
    {
      auto tag = _subproblem.addVectorTag(oldSolutionStateVectorName(i, iteration_type),
                                          Moose::VECTOR_TAG_SOLUTION);
      solution_states[i] = &addVector(tag, true, GHOSTED);
    }
    else
      mooseAssert(solution_states[i] == &getVector(oldSolutionStateVectorName(i, iteration_type)),
                  "Inconsistent solution state");
}
Referenced by EigenExecutionerBase::EigenExecutionerBase(), SystemBase::initSolutionState(), DisplacedSystem::needSolutionState(), and SystemBase::solutionState().
needSubdomainMaterialOnSide()
bool NonlinearSystemBase::needSubdomainMaterialOnSide (SubdomainID subdomain_id, THREAD_ID tid) const inherited
Indicates whether this system needs material properties on internal sides.
Returns
Boolean if DGKernels are active
Definition at line 3607 of file NonlinearSystemBase.C.
{
  return _doing_dg;
}
nFieldVariables()
unsigned int SystemBase::nFieldVariables () const inherited
Get the number of field variables in this system.
Returns
the number of field variables
Definition at line 849 of file SystemBase.C.
{
  unsigned int n = 0;
  for (auto & var : _vars[0].fieldVariables())
    n += var->count();
  return n;
}
Referenced by SystemBase::nVariables().
nFVVariables()
unsigned int SystemBase::nFVVariables () const inherited
Get the number of finite volume variables in this system.
Returns
the number of finite volume variables
Definition at line 859 of file SystemBase.C.
{
  unsigned int n = 0;
  for (auto & var : _vars[0].fieldVariables())
    if (var->isFV())
      n += var->count();
  return n;
}
Referenced by MooseMesh::cacheFVElementalDoFs().
nLinearIterations()
unsigned int NonlinearSystemBase::nLinearIterations () const inline inherited
Return the number of linear iterations.
Definition at line 516 of file NonlinearSystemBase.h.
{ return _n_linear_iters; }
Referenced by IterationAdaptiveDT::acceptStep().
nNonlinearIterations()
unsigned int NonlinearSystemBase::nNonlinearIterations () const inline inherited
Return the number of non-linear iterations.
Definition at line 511 of file NonlinearSystemBase.h.
{ return _n_iters; }
Referenced by IterationAdaptiveDT::acceptStep().
nonEigenMatrixTag()
TagID NonlinearEigenSystem::nonEigenMatrixTag () const inline
Matrix tag ID of left hand side.
Definition at line 146 of file NonlinearEigenSystem.h.
{ return _A_tag; }
Referenced by defaultMatrixTags(), Moose::SlepcSupport::mooseEPSFormMatrices(), and Moose::SlepcSupport::mooseSlepcEigenFormJacobianA().
nonEigenVectorTag()
TagID NonlinearEigenSystem::nonEigenVectorTag () const inline
Vector tag ID of left hand side.
Definition at line 136 of file NonlinearEigenSystem.h.
{ return _Ax_tag; }
Referenced by computeScalingResidual(), defaultVectorTags(), Moose::SlepcSupport::mooseMatMult_NonEigen(), Moose::SlepcSupport::mooseSlepcEigenFormFunctionA(), and Moose::SlepcSupport::mooseSlepcEigenFormFunctionAB().
nonlinearNorm()
Real NonlinearSystemBase::nonlinearNorm () const inline inherited
Return the last nonlinear norm.
Returns
A Real containing the last computed residual norm
Definition at line 532 of file NonlinearSystemBase.h.
{ return _last_nl_rnorm; }
Referenced by Console::writeVariableNorms().
nonlinearSolver()
NonlinearSolver< Number > * NonlinearEigenSystem::nonlinearSolver () override virtual
Implements NonlinearSystemBase.
Definition at line 359 of file NonlinearEigenSystem.C.
{
  mooseError("did not implement yet \n");
  return NULL;
}
nonTimeVectorTag()
TagID NonlinearSystemBase::nonTimeVectorTag () const inline override virtual inherited
Reimplemented from SystemBase.
Definition at line 635 of file NonlinearSystemBase.h.
{ return _Re_non_time_tag; }
Referenced by FEProblemBase::addCachedResidualDirectly(), and CrankNicolson::init().
nResidualEvaluations()
unsigned int NonlinearSystemBase::nResidualEvaluations () const inline inherited
Return the total number of residual evaluations done so far in this calculation.
Definition at line 521 of file NonlinearSystemBase.h.
{ return _n_residual_evaluations; }
Referenced by NumResidualEvaluations::getValue().
number()
unsigned int SystemBase::number () const inherited
Gets the number of this system.
Returns
The number of this system
Definition at line 1125 of file SystemBase.C.
{
  return system().number();
}
Referenced by FEProblemBase::addCachedResidualDirectly(), FEProblemBase::addJacobian(), FEProblemBase::addJacobianBlockTags(), FEProblemBase::addJacobianLowerD(), FEProblemBase::addJacobianNeighbor(), FEProblemBase::addJacobianNeighborLowerD(), FEProblemBase::addJacobianOffDiagScalar(), FEProblemBase::addJacobianScalar(), FEProblemBase::addResidual(), FEProblemBase::addResidualLower(), FEProblemBase::addResidualNeighbor(), FEProblemBase::addResidualScalar(), ADKernelTempl< T >::ADKernelTempl(), ArrayKernel::ArrayKernel(), NonlinearSystemBase::assembleScalingVector(), MooseMesh::cacheFaceInfoVariableOwnership(), ComputeResidualAndJacobianThread::compute(), MooseVariableScalar::computeAD(), FEProblemBase::computeBounds(), Assembly::computeFaceMap(), ArrayNodalBC::computeJacobian(), NodalBC::computeJacobian(), VectorNodalBC::computeJacobian(), FVFluxBC::computeJacobian(), FVInterfaceKernel::computeJacobian(), FVFluxKernel::computeJacobian(), FVBoundaryScalarLagrangeMultiplierConstraint::computeJacobian(), FEProblemBase::computeJacobianBlock(), NonlinearSystemBase::computeJacobianInternal(), FEProblemBase::computeNearNullSpace(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), FEProblemBase::computeNullSpace(), ArrayNodalBC::computeOffDiagJacobian(), NodalBC::computeOffDiagJacobian(), VectorNodalBC::computeOffDiagJacobian(), NodalKernel::computeOffDiagJacobian(), ComputeFullJacobianThread::computeOnBoundary(), ComputeFullJacobianThread::computeOnElement(), ComputeFullJacobianThread::computeOnInterface(), ComputeFullJacobianThread::computeOnInternalFace(), FEProblemBase::computePostCheck(), EqualValueEmbeddedConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), FVOrthogonalBoundaryDiffusion::computeQpResidual(), FVFluxBC::computeResidual(), FVInterfaceKernel::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), IntegratedBC::computeResidualAndJacobian(), NodalBC::computeResidualAndJacobian(), Kernel::computeResidualAndJacobian(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Assembly::computeSinglePointMapAD(), FEProblemBase::computeTransposeNullSpace(), DebugResidualAux::computeValue(), NearestNodeValueAux::computeValue(), NonlinearSystemBase::constraintJacobians(), Coupleable::coupled(), FEProblemBase::currentNlSysNum(), PseudoTimestep::currentResidualNorm(), Moose::FV::determineElemOneAndTwo(), ComputeResidualAndJacobianThread::determineObjectWarehouses(), ComputeResidualThread::determineObjectWarehouses(), Moose::doDerivatives(), GreaterThanLessThanPostprocessor::execute(), VariableResidual::execute(), NodalNormalsCorner::execute(), NodalNormalsEvaluator::execute(), NodalNormalsPreprocessor::execute(), NumNonlinearIterations::finalize(), ElementSubdomainModifier::finalize(), BoundsAuxBase::getDoFIndex(), NonlinearSystemBase::getNodeDofs(), SystemBase::getSubdomainsForVar(), NumLinearIterations::getValue(), NumResidualEvaluations::getValue(), Residual::getValue(), Moose::globalDofIndexToDerivative(), FVBoundaryCondition::hasFaceSide(), NonlinearSystemBase::initialSetup(), ActivateElementsUserObjectBase::initSolutions(), EigenExecutionerBase::inversePowerIteration(), Kernel::Kernel(), EigenExecutionerBase::nonlinearSolve(), ComputeDiracThread::onElement(), ComputeNodalKernelBCJacobiansThread::onNode(), ComputeNodalKernelJacobiansThread::onNode(), PointwiseRenormalizeVector::PointwiseRenormalizeVector(), FEProblemBase::prepare(), FEProblemBase::prepareAssembly(), SystemBase::prepareFace(), FEProblemBase::prepareFaceShapes(), FEProblemBase::prepareNeighborShapes(), FEProblemBase::prepareShapes(), EqualValueEmbeddedConstraint::reinitConstraint(), FEProblemBase::reinitDirac(), FEProblemBase::reinitNeighborPhys(), FEProblemBase::reinitOffDiagScalars(), FEProblemBase::setResidual(), FEProblemBase::setResidualNeighbor(), PhysicsBasedPreconditioner::setup(), FVInterfaceKernel::setupData(), FEProblemSolve::solve(), ActuallyExplicitEuler::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), ExplicitSSPRungeKutta::solveStage(), UserObject::systemNumber(), MultiAppDofCopyTransfer::transferDofObject(), FVFluxBC::uOnGhost(), FVFluxBC::uOnUSub(), and MortarConstraintBase::zeroInactiveLMDofs().
nVariables()
unsigned int SystemBase::nVariables () const virtual inherited
Get the number of variables in this system.
Returns
the number of variables
Definition at line 840 of file SystemBase.C.
{
  unsigned int n = nFieldVariables();
  n += _vars[0].scalars().size();
  return n;
}
Referenced by AdaptivityAction::act(), FieldSplitPreconditioner::FieldSplitPreconditioner(), FiniteDifferencePreconditioner::FiniteDifferencePreconditioner(), NonlinearSystemBase::getNodeDofs(), Assembly::init(), MaxVarNDofsPerElem::onElement(), MaxVarNDofsPerNode::onNode(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), and SingleMatrixPreconditioner::SingleMatrixPreconditioner().
offDiagonalsInAutoScaling() [1/2]
bool NonlinearSystemBase::offDiagonalsInAutoScaling () const inline inherited
Definition at line 671 of file NonlinearSystemBase.h.
{ return _off_diagonals_in_auto_scaling; }
Referenced by ComputeJacobianForScalingThread::computeOnElement(), and FEProblemSolve::FEProblemSolve().
offDiagonalsInAutoScaling() [2/2]
void NonlinearSystemBase::offDiagonalsInAutoScaling (bool off_diagonals_in_auto_scaling) inline inherited
Definition at line 672 of file NonlinearSystemBase.h.
  {
    _off_diagonals_in_auto_scaling = off_diagonals_in_auto_scaling;
  }
oldSolutionStateVectorName()
TagName SystemBase::oldSolutionStateVectorName (const unsigned int state, Moose::SolutionIterationType iteration_type) const private inherited
Gets the vector name used for an old (not current) solution state.
Definition at line 1338 of file SystemBase.C.
{
  mooseAssert(state != 0, "Not an old state");
  if (iteration_type == Moose::SolutionIterationType::Time)
  {
    if (state == 1)
      return Moose::OLD_SOLUTION_TAG;
    else if (state == 2)
      return Moose::OLDER_SOLUTION_TAG;
  }
  else if (iteration_type == Moose::SolutionIterationType::Nonlinear && state == 1)
    return Moose::PREVIOUS_NL_SOLUTION_TAG;
  return "solution_state_" + std::to_string(state) + "_" + Moose::stringify(iteration_type);
}
Referenced by SystemBase::needSolutionState(), and SystemBase::solutionState().
onTimestepBegin()
void NonlinearSystemBase::onTimestepBegin () inherited
Called at the beginning of the time step.
Definition at line 867 of file NonlinearSystemBase.C.
{
  if (_time_integrator)
    _time_integrator->preSolve();
  if (_predictor.get())
    _predictor->timestepSetup();
}
perfGraph()
PerfGraph & PerfGraphInterface::perfGraph () inherited
Get the PerfGraph.
Definition at line 78 of file PerfGraphInterface.C.
{
  return _pg_moose_app.perfGraph();
}
Referenced by CommonOutputAction::act(), PerfGraphData::finalize(), and PerfGraphOutput::output().
postAddResidualObject()
void NonlinearEigenSystem::postAddResidualObject (ResidualObject &) override protected virtual
Called after any ResidualObject-derived objects are added to the system.
Reimplemented from NonlinearSystemBase.
Definition at line 141 of file NonlinearEigenSystem.C.
{
  // If it is an eigen dirichlet boundary condition, we should skip it because their
  // contributions should be zero. If we do not skip it, preconditioning matrix will
  // be singular because boundary elements are zero.
  if (_precond_matrix_includes_eigen && !dynamic_cast<EigenDirichletBC *>(&object) &&
      !dynamic_cast<EigenArrayDirichletBC *>(&object))
    object.useMatrixTag(_precond_tag, {});
  auto & vtags = object.getVectorTags({});
  auto & mtags = object.getMatrixTags({});
  // If it is an eigen kernel, mark its variable as eigen
  if (vtags.find(_Bx_tag) != vtags.end() || mtags.find(_B_tag) != mtags.end())
  {
    // Note: the object may be on the displaced system
    auto sys = object.parameters().get<SystemBase *>("_sys");
    auto vname = object.variable().name();
    if (hasScalarVariable(vname))
      sys->getScalarVariable(0, vname).eigen(true);
    else
      sys->getVariable(0, vname).eigen(true);
  }
  // If this is not an eigen kernel
  // If there is no vector eigen tag and no matrix eigen tag,
  // then we consider this as noneigen kernel
  if (vtags.find(_Bx_tag) == vtags.end() && mtags.find(_B_tag) == mtags.end())
  {
    // Noneigen Vector tag
    object.useVectorTag(_Ax_tag, {});
    // Noneigen Matrix tag
    object.useMatrixTag(_A_tag, {});
    // Noneigen Kernels
    object.useMatrixTag(_precond_tag, {});
  }
  else
  {
    // Associate the eigen matrix tag and the vector tag
    // if this is a eigen kernel
    object.useMatrixTag(_B_tag, {});
    object.useVectorTag(_Bx_tag, {});
  }
}
preconditioner()
Preconditioner< Number > * NonlinearEigenSystem::preconditioner () const inline
Definition at line 165 of file NonlinearEigenSystem.h.
{ return _preconditioner; }
Referenced by attachPreconditioner(), Moose::SlepcSupport::PCApply_MoosePC(), and Moose::SlepcSupport::PCSetUp_MoosePC().
precondMatrixIncludesEigenKernels() [1/2]
bool NonlinearEigenSystem::precondMatrixIncludesEigenKernels () const inline
Definition at line 159 of file NonlinearEigenSystem.h.
{ return _precond_matrix_includes_eigen; }
precondMatrixIncludesEigenKernels() [2/2]
void NonlinearEigenSystem::precondMatrixIncludesEigenKernels (bool precond_matrix_includes_eigen) inline
If the preconditioning matrix includes eigen kernels.
Definition at line 154 of file NonlinearEigenSystem.h.
  {
    _precond_matrix_includes_eigen = precond_matrix_includes_eigen;
  }
Referenced by Eigenvalue::Eigenvalue().
precondMatrixTag()
TagID NonlinearEigenSystem::precondMatrixTag () const inline
Definition at line 161 of file NonlinearEigenSystem.h.
{ return _precond_tag; }
Referenced by computeScalingJacobian(), and Moose::SlepcSupport::mooseSlepcEigenFormJacobianA().
prepare()
void SystemBase::prepare (THREAD_ID tid) virtual inherited
Prepare the system for use.
Parameters
tid ID of the thread
Definition at line 245 of file SystemBase.C.
{
  if (_subproblem.hasActiveElementalMooseVariables(tid))
  {
    const std::set<MooseVariableFieldBase *> & active_elemental_moose_variables =
        _subproblem.getActiveElementalMooseVariables(tid);
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
      var->clearDofIndices();
    for (const auto & var : active_elemental_moose_variables)
      if (&(var->sys()) == this)
        var->prepare();
  }
  else
  {
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
      var->prepare();
  }
}
Referenced by SubProblem::reinitElemFaceRef().
prepareFace()
void SystemBase::prepareFace (THREAD_ID tid, bool resize_data) virtual inherited
Prepare the system for use on sides.
This will try to reuse the preparation done on the element.
Parameters
tid ID of the thread
resize_data Pass True if this system needs to resize residual and jacobian datastructures based on preparing this face
Definition at line 268 of file SystemBase.C.
{
  // We only need to do something if the element prepare was restricted
  if (_subproblem.hasActiveElementalMooseVariables(tid))
  {
    const std::set<MooseVariableFieldBase *> & active_elemental_moose_variables =
        _subproblem.getActiveElementalMooseVariables(tid);
    std::vector<MooseVariableFieldBase *> newly_prepared_vars;
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
    {
      mooseAssert(&var->sys() == this,
                  "I will cry if we store variables in our warehouse that don't belong to us");
      // If it wasn't in the active list, we need to prepare it. This has the potential to duplicate
      // prepare if we have these conditions:
      //
      // 1. We have a displaced problem
      // 2. We are using AD
      // 3. We are not using global AD indexing
      //
      // But I think I would rather risk duplicate prepare than introduce an additional member set
      // variable for tracking prepared variables. Set insertion is slow and some simulations have a
      // ton of variables
      if (!active_elemental_moose_variables.count(var))
      {
        var->prepare();
        newly_prepared_vars.push_back(var);
      }
    }
    // Make sure to resize the residual and jacobian datastructures for all the new variables
    if (resize_data)
      for (const auto var_ptr : newly_prepared_vars)
      {
        _subproblem.assembly(tid, number()).prepareVariable(var_ptr);
        if (_subproblem.checkNonlocalCouplingRequirement())
          _subproblem.assembly(tid, number()).prepareVariableNonlocal(var_ptr);
      }
  }
}
prepareLowerD()
void SystemBase::prepareLowerD (THREAD_ID tid) virtual inherited
Prepare the system for use for lower dimensional elements.
Parameters
tid ID of the thread
Definition at line 321 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->prepareLowerD();
}
prepareNeighbor()
void SystemBase::prepareNeighbor (THREAD_ID tid) virtual inherited
Prepare the system for use.
Parameters
tid ID of the thread
Definition at line 313 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->prepareNeighbor();
}
Referenced by SubProblem::reinitNeighborFaceRef().
printAllVariableNorms()
void NonlinearSystemBase::printAllVariableNorms (bool state) inline inherited
Force the printing of all variable norms after each solve.
Definition at line 538 of file NonlinearSystemBase.h.
{ _print_all_var_norms = state; }
registerTimedSection() [1/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
Returns
The ID of the section - use when starting timing
Definition at line 53 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(timed_section_name, level);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
registerTimedSection() [2/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level, const std::string & live_message, const bool print_dots = true) const protected inherited
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
live_message The message to be printed to the screen during execution
print_dots Whether or not progress dots should be printed for this section
Returns
The ID of the section - use when starting timing
Definition at line 64 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(
        timedSectionName(section_name), level, live_message, print_dots);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
reinitElem()
void SystemBase::reinitElem (const Elem * elem, THREAD_ID tid) virtual inherited
Reinit an element assembly info.
Parameters
elem Which element we are reinitializing for
tid ID of the thread
Reimplemented in AuxiliarySystem.
Definition at line 329 of file SystemBase.C.
{
  if (_subproblem.hasActiveElementalMooseVariables(tid))
  {
    const std::set<MooseVariableFieldBase *> & active_elemental_moose_variables =
        _subproblem.getActiveElementalMooseVariables(tid);
    for (const auto & var : active_elemental_moose_variables)
      if (&(var->sys()) == this)
        var->computeElemValues();
  }
  else
  {
    const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
    for (const auto & var : vars)
      var->computeElemValues();
  }
}
reinitElemFace()
void SystemBase::reinitElemFace (const Elem * elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid) virtual inherited
Reinit assembly info for a side of an element.
Parameters
elem The element
side Side of of the element
bnd_id Boundary id on that side
tid Thread ID
Reimplemented in AuxiliarySystem.
Definition at line 349 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeElemValuesFace();
}
Referenced by SubProblem::reinitElemFaceRef().
reinitIncrementAtNodeForDampers()
void NonlinearSystemBase::reinitIncrementAtNodeForDampers (THREAD_ID tid, const std::set< MooseVariable * > & damped_vars) inherited
Compute the incremental change in variables at nodes for dampers.
Called before we use damping
Parameters
tid Thread ID
damped_vars Set of variables for which increment is to be computed
Definition at line 3401 of file NonlinearSystemBase.C.
{
  for (const auto & var : damped_vars)
    var->computeIncrementAtNode(*_increment_vec);
}
Referenced by ComputeNodalDampingThread::onNode().
reinitIncrementAtQpsForDampers()
void NonlinearSystemBase::reinitIncrementAtQpsForDampers (THREAD_ID tid, const std::set< MooseVariable * > & damped_vars) inherited
Compute the incremental change in variables at QPs for dampers.
Called before we use damping
Parameters
tid Thread ID
damped_vars Set of variables for which increment is to be computed
Definition at line 3393 of file NonlinearSystemBase.C.
{
  for (const auto & var : damped_vars)
    var->computeIncrementAtQps(*_increment_vec);
}
Referenced by ComputeElemDampingThread::onElement().
reinitLowerD()
void SystemBase::reinitLowerD (THREAD_ID tid) virtual inherited
Compute the values of the variables on the lower dimensional element.
Definition at line 379 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeLowerDValues();
}
reinitNeighbor()
void SystemBase::reinitNeighbor (const Elem * elem, THREAD_ID tid) virtual inherited
Compute the values of the variables at all the current points.
Definition at line 371 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeNeighborValues();
}
reinitNeighborFace()
void SystemBase::reinitNeighborFace (const Elem * elem, unsigned int side, BoundaryID bnd_id, THREAD_ID tid) virtual inherited
Compute the values of the variables at all the current points.
Definition at line 360 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
    var->computeNeighborValuesFace();
}
Referenced by SubProblem::reinitNeighborFaceRef().
reinitNode()
void SystemBase::reinitNode (const Node * node, THREAD_ID tid) virtual inherited
Reinit nodal assembly info.
Parameters
node Node to reinit for
tid Thread ID
Definition at line 387 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNode();
    if (var->isNodalDefined())
      var->computeNodalValues();
  }
}
reinitNodeFace()
void SystemBase::reinitNodeFace (const Node * node, BoundaryID bnd_id, THREAD_ID tid) virtual inherited
Reinit nodal assembly info on a face.
Parameters
node Node to reinit
bnd_id Boundary ID
tid Thread ID
Definition at line 399 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNode();
    if (var->isNodalDefined())
      var->computeNodalValues();
  }
}
reinitNodes()
void SystemBase::reinitNodes (const std::vector< dof_id_type > & nodes, THREAD_ID tid) virtual inherited
Reinit variables at a set of nodes.
Parameters
nodes List of node ids to reinit
tid Thread ID
Definition at line 411 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNodes(nodes);
    var->computeNodalValues();
  }
}
reinitNodesNeighbor()
void SystemBase::reinitNodesNeighbor (const std::vector< dof_id_type > & nodes, THREAD_ID tid) virtual inherited
Reinit variables at a set of neighbor nodes.
Parameters
nodes List of node ids to reinit
tid Thread ID
Definition at line 422 of file SystemBase.C.
{
  const std::vector<MooseVariableFieldBase *> & vars = _vars[tid].fieldVariables();
  for (const auto & var : vars)
  {
    var->reinitNodesNeighbor(nodes);
    var->computeNodalNeighborValues();
  }
}
reinitScalars()
void SystemBase::reinitScalars (THREAD_ID tid, bool reinit_for_derivative_reordering = false) virtual inherited
Reinit scalar varaibles.
Parameters
tid Thread ID
reinit_for_derivative_reordering A flag indicating whether we are reinitializing for the purpose of re-ordering derivative information for ADNodalBCs
Definition at line 433 of file SystemBase.C.
{
  const std::vector<MooseVariableScalar *> & vars = _vars[tid].scalars();
  for (const auto & var : vars)
    var->reinit(reinit_for_derivative_reordering);
}
removeMatrix()
void SystemBase::removeMatrix (TagID tag) inherited
Removes a matrix with a given tag.
Parameters
tag_name The name of the tag
Definition at line 579 of file SystemBase.C.
{
  if (!_subproblem.matrixTagExists(tag_id))
    mooseError("Cannot remove the matrix with TagID ",
               tag_id,
               "\nin system '",
               name(),
               "', because that tag does not exist in the problem");
  if (hasMatrix(tag_id))
  {
    const auto matrix_name = _subproblem.matrixTagName(tag_id);
    system().remove_matrix(matrix_name);
    _tagged_matrices[tag_id] = nullptr;
  }
}
removeVector() [1/2]
void SystemBase::removeVector (const std::string & name) inherited
Remove a vector from the system with the given name.
Definition at line 1291 of file SystemBase.C.
{
  system().remove_vector(name);
}
Referenced by SystemBase::restoreOldSolutions().
removeVector() [2/2]
void SystemBase::removeVector (TagID tag_id) inherited
Remove a solution length vector from the system with the specified TagID.
Parameters
tag_id Tag ID
Definition at line 690 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag_id))
    mooseError("Cannot remove the vector with TagID ",
               tag_id,
               "\nin system '",
               name(),
               "', because that tag does not exist in the problem");
  if (hasVector(tag_id))
  {
    auto vector_name = _subproblem.vectorTagName(tag_id);
    system().remove_vector(vector_name);
    _tagged_vectors[tag_id] = nullptr;
  }
}
residualAndJacobianTogether()
void NonlinearEigenSystem::residualAndJacobianTogether () override virtual
Call this method if you want the residual and Jacobian to be computed simultaneously.
Implements NonlinearSystemBase.
Definition at line 473 of file NonlinearEigenSystem.C.
{
  mooseError(
      "NonlinearEigenSystem::residualAndJacobianTogether is not implemented. It might even be "
      "nonsensical. If it is sensical and you want this capability, please contact a MOOSE "
      "developer.");
}
residualCopy()
NumericVector< Number > & NonlinearSystemBase::residualCopy () override virtual inherited
Reimplemented from SystemBase.
Definition at line 3209 of file NonlinearSystemBase.C.
{
  if (!_residual_copy.get())
    _residual_copy = NumericVector<Number>::build(_communicator);
  return *_residual_copy;
}
residualGhosted()
NumericVector< Number > & NonlinearSystemBase::residualGhosted () override virtual inherited
Reimplemented from SystemBase.
Definition at line 3218 of file NonlinearSystemBase.C.
{
  _need_residual_ghosted = true;
  if (!_residual_ghosted)
  {
    // The first time we realize we need a ghosted residual vector,
    // we add it.
    _residual_ghosted = &addVector("residual_ghosted", false, GHOSTED);
    // If we've already realized we need time and/or non-time
    // residual vectors, but we haven't yet realized they need to be
    // ghosted, fix that now.
    //
    // If an application changes its mind, the libMesh API lets us
    // change the vector.
    if (_Re_time)
    {
      const auto vector_name = _subproblem.vectorTagName(_Re_time_tag);
      _Re_time = &system().add_vector(vector_name, false, GHOSTED);
    }
    if (_Re_non_time)
    {
      const auto vector_name = _subproblem.vectorTagName(_Re_non_time_tag);
      _Re_non_time = &system().add_vector(vector_name, false, GHOSTED);
    }
  }
  return *_residual_ghosted;
}
residualSetup()
void NonlinearSystemBase::residualSetup () override virtual inherited
Reimplemented from SystemBase.
Definition at line 1504 of file NonlinearSystemBase.C.
{
  TIME_SECTION("residualSetup", 3);
  SystemBase::residualSetup();
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    _kernels.residualSetup(tid);
    _nodal_kernels.residualSetup(tid);
    _dirac_kernels.residualSetup(tid);
    if (_doing_dg)
      _dg_kernels.residualSetup(tid);
    _interface_kernels.residualSetup(tid);
    _element_dampers.residualSetup(tid);
    _nodal_dampers.residualSetup(tid);
    _integrated_bcs.residualSetup(tid);
  }
  _scalar_kernels.residualSetup();
  _constraints.residualSetup();
  _general_dampers.residualSetup();
  _nodal_bcs.residualSetup();
  // Avoid recursion
  if (this == &_fe_problem.currentNonlinearSystem())
    _fe_problem.residualSetup();
  _app.solutionInvalidity().resetSolutionInvalidCurrentIteration();
}
Referenced by NonlinearSystemBase::computeResidualAndJacobianInternal(), and NonlinearSystemBase::computeResidualInternal().
residualVector()
NumericVector< Number > & NonlinearSystemBase::residualVector (TagID tag) inherited
Return a residual vector that is associated with the residual tag.
Definition at line 994 of file NonlinearSystemBase.C.
{
  mooseDeprecated("Please use getVector()");
  switch (tag)
  {
    case 0:
      return getResidualNonTimeVector();
    case 1:
      return getResidualTimeVector();
    default:
      mooseError("The required residual vector is not available");
  }
}
residualVectorAX()
NumericVector< Number > & NonlinearEigenSystem::residualVectorAX ()
Definition at line 347 of file NonlinearEigenSystem.C.
{
  return _work_rhs_vector_AX;
}
residualVectorBX()
NumericVector< Number > & NonlinearEigenSystem::residualVectorBX ()
Definition at line 353 of file NonlinearEigenSystem.C.
{
  return _work_rhs_vector_BX;
}
residualVectorTag()
TagID NonlinearSystemBase::residualVectorTag () const inline override virtual inherited
Reimplemented from SystemBase.
Definition at line 636 of file NonlinearSystemBase.h.
{ return _Re_tag; }
Referenced by NonlinearSystemBase::computeNodalBCs(), FEProblemBase::computeResidual(), FEProblemBase::computeResidualAndJacobian(), NonlinearSystemBase::computeResidualAndJacobianTags(), FEProblemBase::computeResidualInternal(), NonlinearSystemBase::computeResidualTag(), NonlinearSystemBase::computeResidualTags(), FEProblemBase::computeResidualType(), and FEProblemBase::setResidualNeighbor().
restoreOldSolutions()
void SystemBase::restoreOldSolutions () virtual inherited
Restore the old and older solutions when the saved solutions present.
Definition at line 531 of file SystemBase.C.
{
  const auto states =
      _solution_states[static_cast<unsigned short>(Moose::SolutionIterationType::Time)].size();
  if (states > 1)
    for (unsigned int i = 1; i <= states - 1; ++i)
      if (_saved_solution_states[i])
      {
        solutionState(i) = *(_saved_solution_states[i]);
        removeVector("save_solution_state_" + std::to_string(i));
        _saved_solution_states[i] = nullptr;
      }
  if (_saved_dot_old && solutionUDotOld())
  {
    *solutionUDotOld() = *_saved_dot_old;
    removeVector("save_solution_dot_old");
    _saved_dot_old = nullptr;
  }
  if (_saved_dotdot_old && solutionUDotDotOld())
  {
    *solutionUDotDotOld() = *_saved_dotdot_old;
    removeVector("save_solution_dotdot_old");
    _saved_dotdot_old = nullptr;
  }
}
restoreSolutions()
void NonlinearSystemBase::restoreSolutions () override virtual inherited
Restore current solutions (call after your solve failed)
Reimplemented from SystemBase.
Definition at line 222 of file NonlinearSystemBase.C.
{
  // call parent
  SystemBase::restoreSolutions();
  // and update _current_solution
  _current_solution = _sys.current_local_solution.get();
}
RHS()
NumericVector< Number > & NonlinearEigenSystem::RHS () override virtual
Implements NonlinearSystemBase.
Definition at line 341 of file NonlinearEigenSystem.C.
{
  return _work_rhs_vector_BX;
}
Referenced by computeScalingResidual().
saveOldSolutions()
void SystemBase::saveOldSolutions () virtual inherited
Save the old and older solutions.
Definition at line 499 of file SystemBase.C.
{
  const auto states =
      _solution_states[static_cast<unsigned short>(Moose::SolutionIterationType::Time)].size();
  if (states > 1)
  {
    _saved_solution_states.resize(states);
    for (unsigned int i = 1; i <= states - 1; ++i)
      if (!_saved_solution_states[i])
        _saved_solution_states[i] =
            &addVector("save_solution_state_" + std::to_string(i), false, PARALLEL);
    for (unsigned int i = 1; i <= states - 1; ++i)
      *(_saved_solution_states[i]) = solutionState(i);
  }
  if (!_saved_dot_old && solutionUDotOld())
    _saved_dot_old = &addVector("save_solution_dot_old", false, PARALLEL);
  if (!_saved_dotdot_old && solutionUDotDotOld())
    _saved_dotdot_old = &addVector("save_solution_dotdot_old", false, PARALLEL);
  if (solutionUDotOld())
    *_saved_dot_old = *solutionUDotOld();
  if (solutionUDotDotOld())
    *_saved_dotdot_old = *solutionUDotDotOld();
}
scalingGroupVariables()
void NonlinearSystemBase::scalingGroupVariables (const std::vector< std::vector< std::string > > & scaling_group_variables) inline inherited
Definition at line 660 of file NonlinearSystemBase.h.
  {
    _scaling_group_variables = scaling_group_variables;
  }
Referenced by FEProblemSolve::FEProblemSolve().
serializedSolution()
NumericVector< Number > & NonlinearSystemBase::serializedSolution () override virtual inherited
Returns a reference to a serialized version of the solution vector for this subproblem.
Implements SystemBase.
Definition at line 3360 of file NonlinearSystemBase.C.
{
  if (!_serialized_solution.get())
  {
    _serialized_solution = NumericVector<Number>::build(_communicator);
    _serialized_solution->init(_sys.n_dofs(), false, SERIAL);
  }
  return *_serialized_solution;
}
Referenced by PNGOutput::calculateRescalingValues(), and PNGOutput::makeMeshFunc().
serializeSolution()
void NonlinearSystemBase::serializeSolution () virtual inherited
Definition at line 3309 of file NonlinearSystemBase.C.
{
  if (_serialized_solution.get())
  {
    if (!_serialized_solution->initialized() || _serialized_solution->size() != _sys.n_dofs())
    {
      _serialized_solution->clear();
      _serialized_solution->init(_sys.n_dofs(), false, SERIAL);
    }
    _current_solution->localize(*_serialized_solution);
  }
}
Referenced by NonlinearSystemBase::setSolution().
setActiveScalarVariableCoupleableVectorTags()
void SystemBase::setActiveScalarVariableCoupleableVectorTags (const std::set< TagID > & vtags, THREAD_ID tid) inherited
Set the active vector tags for the scalar variables.
Definition at line 1532 of file SystemBase.C.
{
  _vars[tid].setActiveScalarVariableCoupleableVectorTags(vtags);
}
Referenced by SubProblem::setActiveScalarVariableCoupleableVectorTags().
setActiveVariableCoupleableVectorTags()
void SystemBase::setActiveVariableCoupleableVectorTags (const std::set< TagID > & vtags, THREAD_ID tid) inherited
Set the active vector tags for the variables.
Definition at line 1526 of file SystemBase.C.
{
  _vars[tid].setActiveVariableCoupleableVectorTags(vtags);
}
Referenced by SubProblem::setActiveFEVariableCoupleableVectorTags().
setConstraintSecondaryValues()
void NonlinearSystemBase::setConstraintSecondaryValues (NumericVector< Number > & solution, bool displaced) inherited
Sets the value of constrained variables in the solution vector.
Definition at line 1081 of file NonlinearSystemBase.C.
{
  if (displaced)
    mooseAssert(_fe_problem.getDisplacedProblem(),
                "If we're calling this method with displaced = true, then we better well have a "
                "displaced problem");
  auto & subproblem = displaced ? static_cast<SubProblem &>(*_fe_problem.getDisplacedProblem())
                                : static_cast<SubProblem &>(_fe_problem);
  const auto & penetration_locators = subproblem.geomSearchData()._penetration_locators;
  bool constraints_applied = false;
  for (const auto & it : penetration_locators)
  {
    PenetrationLocator & pen_loc = *(it.second);
    std::vector<dof_id_type> & secondary_nodes = pen_loc._nearest_node._secondary_nodes;
    BoundaryID secondary_boundary = pen_loc._secondary_boundary;
    BoundaryID primary_boundary = pen_loc._primary_boundary;
    if (_constraints.hasActiveNodeFaceConstraints(secondary_boundary, displaced))
    {
      const auto & constraints =
          _constraints.getActiveNodeFaceConstraints(secondary_boundary, displaced);
      for (unsigned int i = 0; i < secondary_nodes.size(); i++)
      {
        dof_id_type secondary_node_num = secondary_nodes[i];
        Node & secondary_node = _mesh.nodeRef(secondary_node_num);
        if (secondary_node.processor_id() == processor_id())
        {
          if (pen_loc._penetration_info[secondary_node_num])
          {
            PenetrationInfo & info = *pen_loc._penetration_info[secondary_node_num];
            const Elem * primary_elem = info._elem;
            unsigned int primary_side = info._side_num;
            // reinit variables at the node
            _fe_problem.reinitNodeFace(&secondary_node, secondary_boundary, 0);
            _fe_problem.prepareAssembly(0);
            std::vector<Point> points;
            points.push_back(info._closest_point);
            // reinit variables on the primary element's face at the contact point
            _fe_problem.setNeighborSubdomainID(primary_elem, 0);
            subproblem.reinitNeighborPhys(primary_elem, primary_side, points, 0);
            for (const auto & nfc : constraints)
            {
              // Return if this constraint does not correspond to the primary-secondary pair
              // prepared by the outer loops.
              // This continue statement is required when, e.g. one secondary surface constrains
              // more than one primary surface.
              if (nfc->secondaryBoundary() != secondary_boundary ||
                  nfc->primaryBoundary() != primary_boundary)
                continue;
              if (nfc->shouldApply())
              {
                constraints_applied = true;
                nfc->computeSecondaryValue(solution);
              }
            }
          }
        }
      }
    }
  }
  // go over NodeELemConstraints
  std::set<dof_id_type> unique_secondary_node_ids;
  for (const auto & secondary_id : _mesh.meshSubdomains())
  {
    for (const auto & primary_id : _mesh.meshSubdomains())
    {
      if (_constraints.hasActiveNodeElemConstraints(secondary_id, primary_id, displaced))
      {
        const auto & constraints =
            _constraints.getActiveNodeElemConstraints(secondary_id, primary_id, displaced);
        // get unique set of ids of all nodes on current block
        unique_secondary_node_ids.clear();
        const MeshBase & meshhelper = _mesh.getMesh();
        for (const auto & elem : as_range(meshhelper.active_subdomain_elements_begin(secondary_id),
                                          meshhelper.active_subdomain_elements_end(secondary_id)))
        {
          for (auto & n : elem->node_ref_range())
            unique_secondary_node_ids.insert(n.id());
        }
        for (auto secondary_node_id : unique_secondary_node_ids)
        {
          Node & secondary_node = _mesh.nodeRef(secondary_node_id);
          // check if secondary node is on current processor
          if (secondary_node.processor_id() == processor_id())
          {
            // This reinits the variables that exist on the secondary node
            _fe_problem.reinitNodeFace(&secondary_node, secondary_id, 0);
            // This will set aside residual and jacobian space for the variables that have dofs
            // on the secondary node
            _fe_problem.prepareAssembly(0);
            for (const auto & nec : constraints)
            {
              if (nec->shouldApply())
              {
                constraints_applied = true;
                nec->computeSecondaryValue(solution);
              }
            }
          }
        }
      }
    }
  }
  // See if constraints were applied anywhere
  _communicator.max(constraints_applied);
  if (constraints_applied)
  {
    solution.close();
    update();
  }
}
Referenced by NonlinearSystemBase::setInitialSolution().
setDecomposition()
void NonlinearSystemBase::setDecomposition (const std::vector< std::string > & decomposition) inherited
If called with a single string, it is used as the name of a the top-level decomposition split.
If the array is empty, no decomposition is used. In all other cases an error occurs.
Although a single top-level split is allowed in Problem, treat it as a list of splits for conformity with the Split input syntax.
Definition at line 440 of file NonlinearSystemBase.C.
{
  if (splits.size() && splits.size() != 1)
    mooseError("Only a single top-level split is allowed in a Problem's decomposition.");
  if (splits.size())
  {
    _decomposition_split = splits[0];
    _have_decomposition = true;
  }
  else
    _have_decomposition = false;
}
Referenced by FEProblemSolve::FEProblemSolve(), and FieldSplitPreconditioner::FieldSplitPreconditioner().
setInitialSolution()
void NonlinearSystemBase::setInitialSolution () inherited
Definition at line 876 of file NonlinearSystemBase.C.
{
  deactiveAllMatrixTags();
  NumericVector<Number> & initial_solution(solution());
  if (_predictor.get() && _predictor->shouldApply())
  {
    TIME_SECTION("applyPredictor", 2, "Applying Predictor");
    _predictor->apply(initial_solution);
    _fe_problem.predictorCleanup(initial_solution);
  }
  // do nodal BC
  {
    TIME_SECTION("initialBCs", 2, "Applying BCs To Initial Condition");
    ConstBndNodeRange & bnd_nodes = *_mesh.getBoundaryNodeRange();
    for (const auto & bnode : bnd_nodes)
    {
      BoundaryID boundary_id = bnode->_bnd_id;
      Node * node = bnode->_node;
      if (node->processor_id() == processor_id())
      {
        // reinit variables in nodes
        _fe_problem.reinitNodeFace(node, boundary_id, 0);
        if (_preset_nodal_bcs.hasActiveBoundaryObjects(boundary_id))
        {
          const auto & preset_bcs = _preset_nodal_bcs.getActiveBoundaryObjects(boundary_id);
          for (const auto & preset_bc : preset_bcs)
            preset_bc->computeValue(initial_solution);
        }
        if (_ad_preset_nodal_bcs.hasActiveBoundaryObjects(boundary_id))
        {
          const auto & preset_bcs_res = _ad_preset_nodal_bcs.getActiveBoundaryObjects(boundary_id);
          for (const auto & preset_bc : preset_bcs_res)
            preset_bc->computeValue(initial_solution);
        }
      }
    }
  }
  _sys.solution->close();
  update();
  // Set constraint secondary values
  setConstraintSecondaryValues(initial_solution, false);
  if (_fe_problem.getDisplacedProblem())
    setConstraintSecondaryValues(initial_solution, true);
}
Referenced by solve(), and NonlinearSystem::solve().
setMooseKSPNormType()
void NonlinearSystemBase::setMooseKSPNormType (MooseEnum kspnorm) inherited
Definition at line 3578 of file NonlinearSystemBase.C.
{
  if (kspnorm == "none")
    _ksp_norm = Moose::KSPN_NONE;
  else if (kspnorm == "preconditioned")
    _ksp_norm = Moose::KSPN_PRECONDITIONED;
  else if (kspnorm == "unpreconditioned")
    _ksp_norm = Moose::KSPN_UNPRECONDITIONED;
  else if (kspnorm == "natural")
    _ksp_norm = Moose::KSPN_NATURAL;
  else if (kspnorm == "default")
    _ksp_norm = Moose::KSPN_DEFAULT;
  else
    mooseError("Unknown ksp norm type specified.");
}
Referenced by MoosePreconditioner::MoosePreconditioner().
setPCSide()
void NonlinearSystemBase::setPCSide (MooseEnum pcs) inherited
Definition at line 3563 of file NonlinearSystemBase.C.
{
  if (pcs == "left")
    _pc_side = Moose::PCS_LEFT;
  else if (pcs == "right")
    _pc_side = Moose::PCS_RIGHT;
  else if (pcs == "symmetric")
    _pc_side = Moose::PCS_SYMMETRIC;
  else if (pcs == "default")
    _pc_side = Moose::PCS_DEFAULT;
  else
    mooseError("Unknown PC side specified.");
}
Referenced by MoosePreconditioner::MoosePreconditioner().
setPreconditioner()
void NonlinearSystemBase::setPreconditioner (std::shared_ptr< MoosePreconditioner > pc) inherited
Sets a preconditioner.
Parameters
pc The preconditioner to be set
Definition at line 3372 of file NonlinearSystemBase.C.
{
  if (_preconditioner.get() != nullptr)
    mooseError("More than one active Preconditioner detected");
  _preconditioner = pc;
}
Referenced by SetupPreconditionerAction::act().
setPredictor()
void NonlinearSystemBase::setPredictor (std::shared_ptr< Predictor > predictor) inherited
Definition at line 931 of file NonlinearSystemBase.C.
{
  _predictor = predictor;
}
Referenced by SetupPredictorAction::act().
setPreviousNewtonSolution()
void NonlinearSystemBase::setPreviousNewtonSolution (const NumericVector< Number > & soln) virtual inherited
Definition at line 3620 of file NonlinearSystemBase.C.
{
  if (hasVector(Moose::PREVIOUS_NL_SOLUTION_TAG))
    getVector(Moose::PREVIOUS_NL_SOLUTION_TAG) = soln;
}
Referenced by FEProblemBase::computePostCheck().
setSolution()
void NonlinearSystemBase::setSolution (const NumericVector< Number > & soln) virtual inherited
Definition at line 3324 of file NonlinearSystemBase.C.
{
  _current_solution = &soln;
  auto tag = _subproblem.getVectorTagID(Moose::SOLUTION_TAG);
  associateVectorToTag(const_cast<NumericVector<Number> &>(soln), tag);
  if (_serialized_solution.get())
    serializeSolution();
}
Referenced by FEProblemBase::computeDamping(), FEProblemBase::computeJacobianInternal(), FEProblemBase::computeJacobianTag(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualInternal(), FEProblemBase::computeResidualTag(), FEProblemBase::computeResidualType(), ActuallyExplicitEuler::solve(), and ExplicitSSPRungeKutta::solveStage().
setSolutionUDot()
void NonlinearSystemBase::setSolutionUDot (const NumericVector< Number > & udot) virtual inherited
Set transient term used by residual and Jacobian evaluation.
Parameters
udot transient term
Note
If the calling sequence for residual evaluation was changed, this could become an explicit argument.
Definition at line 3336 of file NonlinearSystemBase.C.
{
  *_u_dot = u_dot;
}
setSolutionUDotDot()
void NonlinearSystemBase::setSolutionUDotDot (const NumericVector< Number > & udotdot) virtual inherited
Set transient term used by residual and Jacobian evaluation.
Parameters
udotdot transient term
Note
If the calling sequence for residual evaluation was changed, this could become an explicit argument.
Definition at line 3342 of file NonlinearSystemBase.C.
{
  *_u_dotdot = u_dotdot;
}
setSolutionUDotDotOld()
void NonlinearSystemBase::setSolutionUDotDotOld (const NumericVector< Number > & u_dotdot_old) virtual inherited
Definition at line 3354 of file NonlinearSystemBase.C.
{
  *_u_dotdot_old = u_dotdot_old;
}
setSolutionUDotOld()
void NonlinearSystemBase::setSolutionUDotOld (const NumericVector< Number > & u_dot_old) virtual inherited
Definition at line 3348 of file NonlinearSystemBase.C.
{
  *_u_dot_old = u_dot_old;
}
setupDampers()
void NonlinearSystemBase::setupDampers () inherited
Setup damping stuff (called before we actually start)
Definition at line 3387 of file NonlinearSystemBase.C.
{
  _increment_vec = &_sys.add_vector("u_increment", true, GHOSTED);
}
Referenced by NonlinearSystemBase::init().
setupFieldDecomposition()
void NonlinearSystemBase::setupFieldDecomposition () inherited
Definition at line 456 of file NonlinearSystemBase.C.
{
  if (!_have_decomposition)
    return;
  std::shared_ptr<Split> top_split = getSplit(_decomposition_split);
  top_split->setup(*this);
}
Referenced by FieldSplitPreconditioner::FieldSplitPreconditioner().
setupFiniteDifferencedPreconditioner()
void NonlinearEigenSystem::setupFiniteDifferencedPreconditioner () override virtual
Implements NonlinearSystemBase.
Definition at line 322 of file NonlinearEigenSystem.C.
{
  mooseError("did not implement yet \n");
}
setupScalingData()
void NonlinearSystemBase::setupScalingData () private inherited
Setup group scaling containers.
Definition at line 3651 of file NonlinearSystemBase.C.
{
  if (_auto_scaling_initd)
    return;
  // Want the libMesh count of variables, not MOOSE, e.g. I don't care about array variable counts
  const auto n_vars = system().n_vars();
  if (_scaling_group_variables.empty())
  {
    _var_to_group_var.reserve(n_vars);
    _num_scaling_groups = n_vars;
    for (const auto var_number : make_range(n_vars))
      _var_to_group_var.emplace(var_number, var_number);
  }
  else
  {
    std::set<unsigned int> var_numbers, var_numbers_covered, var_numbers_not_covered;
    for (const auto var_number : make_range(n_vars))
      var_numbers.insert(var_number);
    _num_scaling_groups = _scaling_group_variables.size();
    for (const auto group_index : index_range(_scaling_group_variables))
      for (const auto & var_name : _scaling_group_variables[group_index])
      {
        if (!hasVariable(var_name) && !hasScalarVariable(var_name))
          mooseError("'",
                     var_name,
                     "', provided to the 'scaling_group_variables' parameter, does not exist in "
                     "the nonlinear system.");
        const MooseVariableBase & var =
            hasVariable(var_name)
                ? static_cast<MooseVariableBase &>(getVariable(0, var_name))
                : static_cast<MooseVariableBase &>(getScalarVariable(0, var_name));
        auto map_pair = _var_to_group_var.emplace(var.number(), group_index);
        if (!map_pair.second)
          mooseError("Variable ", var_name, " is contained in multiple scaling grouplings");
        var_numbers_covered.insert(var.number());
      }
    std::set_difference(var_numbers.begin(),
                        var_numbers.end(),
                        var_numbers_covered.begin(),
                        var_numbers_covered.end(),
                        std::inserter(var_numbers_not_covered, var_numbers_not_covered.begin()));
    _num_scaling_groups = _scaling_group_variables.size() + var_numbers_not_covered.size();
    auto index = static_cast<unsigned int>(_scaling_group_variables.size());
    for (auto var_number : var_numbers_not_covered)
      _var_to_group_var.emplace(var_number, index++);
  }
  _variable_autoscaled.resize(n_vars, true);
  const auto & number_to_var_map = _vars[0].numberToVariableMap();
  if (_ignore_variables_for_autoscaling.size())
    for (const auto i : index_range(_variable_autoscaled))
      if (std::find(_ignore_variables_for_autoscaling.begin(),
                    _ignore_variables_for_autoscaling.end(),
                    libmesh_map_find(number_to_var_map, i)->name()) !=
          _ignore_variables_for_autoscaling.end())
        _variable_autoscaled[i] = false;
}
Referenced by NonlinearSystemBase::computeScaling().
setVariableGlobalDoFs()
void SystemBase::setVariableGlobalDoFs (const std::string & var_name) inherited
set all the global dof indices for a variable
Parameters
var_name The name of the variable
Definition at line 175 of file SystemBase.C.
{
  AllLocalDofIndicesThread aldit(_subproblem, {var_name});
  ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();
  Threads::parallel_reduce(elem_range, aldit);
  // Gather the dof indices across procs to get all the dof indices for var_name
  aldit.dofIndicesSetUnion();
  const auto & all_dof_indices = aldit.getDofIndices();
  _var_all_dof_indices.assign(all_dof_indices.begin(), all_dof_indices.end());
}
setVerboseFlag()
void SystemBase::setVerboseFlag (const bool & verbose) inline inherited
Sets the verbose flag.
Parameters
[in] verbose Verbose flag
Definition at line 129 of file SystemBase.h.
{ _verbose = verbose; }
Referenced by Executioner::Executioner().
solution() [1/2]
NumericVector< Number > & SystemBase::solution () inline inherited
Definition at line 176 of file SystemBase.h.
{ return solutionState(0); }
Referenced by Adaptivity::adaptMesh(), TransientMultiApp::appTransferVector(), MooseEigenSystem::combineSystemSolution(), NonlinearSystemBase::computeDamping(), AuxiliarySystem::computeElementalVarsHelper(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeMortarNodalVars(), NonlinearSystemBase::computeNodalBCs(), AuxiliarySystem::computeNodalVarsHelper(), NonlinearSystemBase::computeResidualTags(), AuxiliarySystem::computeScalarVars(), SystemBase::copyVars(), GreaterThanLessThanPostprocessor::execute(), MultiAppPostprocessorToAuxScalarTransfer::execute(), MultiAppScalarToAuxScalarTransfer::execute(), MultiAppVariableValueSamplePostprocessorTransfer::execute(), NodalNormalsCorner::execute(), NodalNormalsEvaluator::execute(), NodalNormalsPreprocessor::execute(), NodalNormalsCorner::finalize(), NodalNormalsEvaluator::finalize(), NodalNormalsPreprocessor::finalize(), NodalNormalsCorner::initialize(), NodalNormalsEvaluator::initialize(), NodalNormalsPreprocessor::initialize(), MooseEigenSystem::initSystemSolution(), ComputeIndicatorThread::onElement(), ComputeMarkerThread::onElement(), ComputeUserObjectsThread::onElement(), ComputeNodalUserObjectsThread::onNode(), FEProblemBase::projectInitialConditionOnCustomRange(), FEProblemBase::projectSolution(), Transient::relativeSolutionDifferenceNorm(), SystemBase::restoreSolutions(), PicardSolve::saveVariableValues(), SecantSolve::saveVariableValues(), SteffensenSolve::saveVariableValues(), MooseEigenSystem::scaleSystemSolution(), AuxiliarySystem::serializeSolution(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::setInitialSolution(), DisplacedSystem::solutionInternal(), solve(), MultiAppDofCopyTransfer::transfer(), PicardSolve::transformVariables(), SecantSolve::transformVariables(), SteffensenSolve::transformVariables(), and SystemBase::zeroVariables().
solution() [2/2]
const NumericVector< Number > & SystemBase::solution () const inline inherited
Definition at line 179 of file SystemBase.h.
{ return solutionState(0); }
solutionInternal()
NumericVector< Number > & NonlinearSystemBase::solutionInternal () const inline override protected virtual inherited
Internal getter for solution owned by libMesh.
Implements SystemBase.
Definition at line 759 of file NonlinearSystemBase.h.
{ return *_sys.solution; }
solutionOld() [1/2]
NumericVector< Number > & SystemBase::solutionOld () inline inherited
Definition at line 177 of file SystemBase.h.
{ return solutionState(1); }
Referenced by MooseEigenSystem::combineSystemSolution(), CentralDifference::computeTimeDerivatives(), ActivateElementsUserObjectBase::initSolutions(), MooseEigenSystem::initSystemSolutionOld(), MooseVariableScalar::reinit(), Transient::relativeSolutionDifferenceNorm(), SystemBase::restoreSolutions(), ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes(), ActuallyExplicitEuler::solve(), and AdamsPredictor::timestepSetup().
solutionOld() [2/2]
const NumericVector< Number > & SystemBase::solutionOld () const inline inherited
Definition at line 180 of file SystemBase.h.
{ return solutionState(1); }
solutionOlder() [1/2]
NumericVector< Number > & SystemBase::solutionOlder () inline inherited
Definition at line 178 of file SystemBase.h.
{ return solutionState(2); }
Referenced by MooseEigenSystem::combineSystemSolution(), CentralDifference::computeTimeDerivatives(), ActivateElementsUserObjectBase::initSolutions(), MooseVariableScalar::reinit(), and ElementSubdomainModifier::setOldAndOlderSolutionsForMovedNodes().
solutionOlder() [2/2]
const NumericVector< Number > & SystemBase::solutionOlder () const inline inherited
Definition at line 181 of file SystemBase.h.
{ return solutionState(2); }
solutionPreviousNewton() [1/2]
NumericVector< Number > * SystemBase::solutionPreviousNewton () virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 1303 of file SystemBase.C.
{
  if (hasVector(Moose::PREVIOUS_NL_SOLUTION_TAG))
    return &getVector(Moose::PREVIOUS_NL_SOLUTION_TAG);
  else
    return nullptr;
}
solutionPreviousNewton() [2/2]
const NumericVector< Number > * SystemBase::solutionPreviousNewton () const virtual inherited
Reimplemented in DisplacedSystem.
Definition at line 1312 of file SystemBase.C.
{
  if (hasVector(Moose::PREVIOUS_NL_SOLUTION_TAG))
    return &getVector(Moose::PREVIOUS_NL_SOLUTION_TAG);
  else
    return nullptr;
}
Referenced by SystemBase::copyOldSolutions(), SystemBase::copySolutionsBackwards(), and SystemBase::restoreSolutions().
solutionState() [1/2]
NumericVector< Number > & SystemBase::solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) virtual inherited
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
If the state does not exist, it will be initialized in addition to any newer states before it that have not been initialized.
Reimplemented in DisplacedSystem.
Definition at line 1384 of file SystemBase.C.
{
  if (!hasSolutionState(state, iteration_type))
    needSolutionState(state, iteration_type);
  return *_solution_states[static_cast<unsigned short>(iteration_type)][state];
}
Referenced by SystemBase::copyOldSolutions(), SystemBase::copySolutionsBackwards(), PointwiseRenormalizeVector::execute(), PointwiseRenormalizeVector::finalize(), SystemBase::restoreOldSolutions(), SystemBase::saveOldSolutions(), SystemBase::solution(), SystemBase::solutionOld(), SystemBase::solutionOlder(), and DisplacedSystem::solutionState().
solutionState() [2/2]
const NumericVector< Number > & SystemBase::solutionState (const unsigned int state, Moose::SolutionIterationType iteration_type = Moose::SolutionIterationType::Time) const virtual inherited
Get a state of the solution (0 = current, 1 = old, 2 = older, etc).
Reimplemented in DisplacedSystem.
Definition at line 1357 of file SystemBase.C.
{
  if (!hasSolutionState(state, iteration_type))
    mooseError("For iteration type '",
               Moose::stringify(iteration_type),
               "': solution state ",
               state,
               " was requested in ",
               name(),
               " but only up to state ",
               _solution_states[static_cast<unsigned short>(iteration_type)].size() - 1,
               " is available.");
  const auto & solution_states = _solution_states[static_cast<unsigned short>(iteration_type)];
  if (state == 0)
    mooseAssert(solution_states[0] == &solutionInternal(), "Inconsistent current solution");
  else
    mooseAssert(solution_states[state] ==
                    &getVector(oldSolutionStateVectorName(state, iteration_type)),
                "Inconsistent solution state");
  return *solution_states[state];
}
solutionStatesInitialized()
bool SystemBase::solutionStatesInitialized () const inline inherited
Whether or not the solution states have been initialized via initSolutionState()
After the solution states have been initialized, additional solution states cannot be added.
Definition at line 888 of file SystemBase.h.
{ return _solution_states_initialized; }
Referenced by AuxScalarKernel::uOld(), and ScalarKernelBase::uOld().
solutionUDot() [1/2]
const NumericVector< Number > * NonlinearSystemBase::solutionUDot () const inline override virtual inherited
Implements SystemBase.
Definition at line 389 of file NonlinearSystemBase.h.
{ return _u_dot; }
solutionUDot() [2/2]
NumericVector< Number > * NonlinearSystemBase::solutionUDot () inline override virtual inherited
Implements SystemBase.
Definition at line 385 of file NonlinearSystemBase.h.
{ return _u_dot; }
Referenced by CentralDifference::initialSetup().
solutionUDotDot() [1/2]
const NumericVector< Number > * NonlinearSystemBase::solutionUDotDot () const inline override virtual inherited
Implements SystemBase.
Definition at line 390 of file NonlinearSystemBase.h.
{ return _u_dotdot; }
solutionUDotDot() [2/2]
NumericVector< Number > * NonlinearSystemBase::solutionUDotDot () inline override virtual inherited
Implements SystemBase.
Definition at line 386 of file NonlinearSystemBase.h.
{ return _u_dotdot; }
Referenced by CentralDifference::initialSetup().
solutionUDotDotOld() [1/2]
const NumericVector< Number > * NonlinearSystemBase::solutionUDotDotOld () const inline override virtual inherited
Implements SystemBase.
Definition at line 392 of file NonlinearSystemBase.h.
{ return _u_dotdot_old; }
solutionUDotDotOld() [2/2]
NumericVector< Number > * NonlinearSystemBase::solutionUDotDotOld () inline override virtual inherited
Implements SystemBase.
Definition at line 388 of file NonlinearSystemBase.h.
{ return _u_dotdot_old; }
solutionUDotOld() [1/2]
const NumericVector< Number > * NonlinearSystemBase::solutionUDotOld () const inline override virtual inherited
Implements SystemBase.
Definition at line 391 of file NonlinearSystemBase.h.
{ return _u_dot_old; }
solutionUDotOld() [2/2]
NumericVector< Number > * NonlinearSystemBase::solutionUDotOld () inline override virtual inherited
Implements SystemBase.
Definition at line 387 of file NonlinearSystemBase.h.
{ return _u_dot_old; }
solve()
void NonlinearEigenSystem::solve () override virtual
Solve the system (using libMesh magic)
Implements NonlinearSystemBase.
Definition at line 186 of file NonlinearEigenSystem.C.
{
  // Clear the iteration counters
  _current_l_its.clear();
  _current_nl_its = 0;
  // Initialize the solution vector using a predictor and known values from nodal bcs
  setInitialSolution();
  // Now that the initial solution has ben set, potentially perform a residual/Jacobian evaluation
  // to determine variable scaling factors
  if (_automatic_scaling)
  {
    if (_compute_scaling_once)
    {
      if (!_computed_scaling)
      {
        computeScaling();
        _computed_scaling = true;
      }
    }
    else
      computeScaling();
  }
  // We do not know a priori what variable a global degree of freedom corresponds to, so we need a
  // map from global dof to scaling factor. We just use a ghosted NumericVector for that mapping
  assembleScalingVector();
// In DEBUG mode, Libmesh will check the residual automatically. This may cause
// an error because B does not need to assembly by default.
// When PETSc is older than 3.13, we always need to do an extra assembly,
// so we do not do "close" here
#if DEBUG && !PETSC_RELEASE_LESS_THAN(3, 13, 0)
  if (sys().has_matrix_B())
    sys().get_matrix_B().close();
#endif
  // We apply initial guess for only nonlinear solver
  if (_eigen_problem.isNonlinearEigenvalueSolver())
    _eigen_sys.set_initial_space(solution());
  // Solve the transient problem if we have a time integrator; the
  // steady problem if not.
  if (_time_integrator)
  {
    _time_integrator->solve();
    _time_integrator->postSolve();
  }
  else
    system().solve();
  // store eigenvalues
  unsigned int n_converged_eigenvalues = getNumConvergedEigenvalues();
  _n_eigen_pairs_required = _eigen_problem.getNEigenPairsRequired();
  if (_n_eigen_pairs_required < n_converged_eigenvalues)
    n_converged_eigenvalues = _n_eigen_pairs_required;
  _eigen_values.resize(n_converged_eigenvalues);
  for (unsigned int n = 0; n < n_converged_eigenvalues; n++)
    _eigen_values[n] = getConvergedEigenvalue(n);
  // Update the solution vector to the active eigenvector
  if (n_converged_eigenvalues)
    getConvergedEigenpair(_eigen_problem.activeEigenvalueIndex());
}
stopSolve()
void NonlinearEigenSystem::stopSolve () override virtual
Quit the current solve as soon as possible.
Implements NonlinearSystemBase.
Definition at line 316 of file NonlinearEigenSystem.C.
{
  mooseError("did not implement yet \n");
}
subdomainSetup() [1/2]
void SystemBase::subdomainSetup () virtual inherited
Reimplemented from SystemBase.
Definition at line 894 of file SystemBase.C.
{
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _vars[tid].subdomainSetup();
}
subdomainSetup() [2/2]
void NonlinearSystemBase::subdomainSetup (SubdomainID subdomain, THREAD_ID tid) virtual inherited
Called from assembling when we hit a new subdomain.
Parameters
subdomain ID of the new subdomain
tid Thread ID
Definition at line 937 of file NonlinearSystemBase.C.
{
  SystemBase::subdomainSetup();
  _kernels.subdomainSetup(subdomain, tid);
  _nodal_kernels.subdomainSetup(subdomain, tid);
  _element_dampers.subdomainSetup(subdomain, tid);
  _nodal_dampers.subdomainSetup(subdomain, tid);
}
subproblem() [1/2]
virtual SubProblem & SystemBase::subproblem () inline virtual inherited
Definition at line 98 of file SystemBase.h.
{ return _subproblem; }
Referenced by CreateDisplacedProblemAction::addProxyRelationshipManagers(), MooseVariableBase::allDofIndices(), NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), Moose::globalDofIndexToDerivative(), NonlinearSystemBase::initialSetup(), MooseVariableScalar::MooseVariableScalar(), MooseVariableScalar::reinit(), and NonlinearSystemBase::setConstraintSecondaryValues().
subproblem() [2/2]
virtual const SubProblem & SystemBase::subproblem () const inline virtual inherited
Definition at line 99 of file SystemBase.h.
{ return _subproblem; }
sys()
EigenSystem & NonlinearEigenSystem::sys () inline
Definition at line 90 of file NonlinearEigenSystem.h.
{ return _eigen_sys; }
Referenced by NonlinearEigenSystem(), postAddResidualObject(), and solve().
system() [1/2]
virtual const System & NonlinearSystemBase::system () const inline override virtual inherited
Implements SystemBase.
Definition at line 626 of file NonlinearSystemBase.h.
{ return _sys; }
system() [2/2]
virtual System & NonlinearSystemBase::system () inline override virtual inherited
Get the reference to the libMesh system.
Implements SystemBase.
Definition at line 625 of file NonlinearSystemBase.h.
{ return _sys; }
Referenced by Adaptivity::adaptMesh(), PhysicsBasedPreconditioner::addSystem(), PhysicsBasedPreconditioner::apply(), NonlinearSystemBase::computeScaling(), PseudoTimestep::currentResidualNorm(), DMCreateGlobalVector_Moose(), DMCreateMatrix_Moose(), DMMooseFunction(), DMMooseGetEmbedding_Private(), DMMooseGetMeshBlocks_Private(), DMMooseJacobian(), DMSetFromOptions_Moose(), DMSetUp_Moose_Pre(), VariableResidual::execute(), NonlinearSystemBase::getResidualNonTimeVector(), NonlinearSystemBase::getResidualTimeVector(), ReferenceResidualProblem::initialSetup(), ActivateElementsUserObjectBase::initSolutions(), Moose::SlepcSupport::mooseMatMult(), Moose::SlepcSupport::moosePetscSNESFormFunction(), Moose::SlepcSupport::moosePetscSNESFormMatricesTags(), Moose::SlepcSupport::moosePetscSNESFormMatrixTag(), Moose::SlepcSupport::mooseSlepcEigenFormFunctionAB(), ConsoleUtils::outputNonlinearSystemInformation(), PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(), NonlinearSystemBase::residualGhosted(), PhysicsBasedPreconditioner::setup(), NonlinearSystemBase::setupScalingData(), SingleMatrixPreconditioner::SingleMatrixPreconditioner(), TimeIntegrator::solve(), solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), Moose::PetscSupport::storePetscOptions(), NonlinearSystemBase::turnOffJacobian(), ReferenceResidualProblem::updateReferenceResidual(), VariableCondensationPreconditioner::VariableCondensationPreconditioner(), and Console::writeVariableNorms().
systemMatrixTag()
TagID NonlinearSystemBase::systemMatrixTag () const inline override virtual inherited
Return the Matrix Tag ID for System.
Reimplemented from SystemBase.
Definition at line 637 of file NonlinearSystemBase.h.
{ return _Ke_system_tag; }
Referenced by NonlinearSystemBase::addImplicitGeometricCouplingEntries(), NonlinearSystemBase::computeJacobian(), FEProblemBase::computeJacobianInternal(), FEProblemBase::computeResidualAndJacobian(), NonlinearSystemBase::constraintJacobians(), and NonlinearSystemBase::enforceNodalConstraintsJacobian().
timedSectionName()
std::string PerfGraphInterface::timedSectionName (const std::string & section_name) const protected inherited
Returns
The name of the timed section with the name section_name.
Optionally adds a prefix if one is defined.
Definition at line 47 of file PerfGraphInterface.C.
{
  return _prefix.empty() ? "" : (_prefix + "::") + section_name;
}
Referenced by PerfGraphInterface::registerTimedSection().
timestepSetup()
void NonlinearSystemBase::timestepSetup () override virtual inherited
Reimplemented from SystemBase.
Definition at line 332 of file NonlinearSystemBase.C.
{
  SystemBase::timestepSetup();
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    _kernels.timestepSetup(tid);
    _nodal_kernels.timestepSetup(tid);
    _dirac_kernels.timestepSetup(tid);
    if (_doing_dg)
      _dg_kernels.timestepSetup(tid);
    _interface_kernels.timestepSetup(tid);
    _element_dampers.timestepSetup(tid);
    _nodal_dampers.timestepSetup(tid);
    _integrated_bcs.timestepSetup(tid);
    if (_fe_problem.haveFV())
    {
      std::vector<FVFluxBC *> bcs;
      _fe_problem.theWarehouse()
          .query()
          .template condition<AttribSystem>("FVFluxBC")
          .template condition<AttribThread>(tid)
          .queryInto(bcs);
      std::vector<FVInterfaceKernel *> iks;
      _fe_problem.theWarehouse()
          .query()
          .template condition<AttribSystem>("FVInterfaceKernel")
          .template condition<AttribThread>(tid)
          .queryInto(iks);
      std::vector<FVFluxKernel *> kernels;
      _fe_problem.theWarehouse()
          .query()
          .template condition<AttribSystem>("FVFluxKernel")
          .template condition<AttribThread>(tid)
          .queryInto(kernels);
      for (auto * bc : bcs)
        bc->timestepSetup();
      for (auto * ik : iks)
        ik->timestepSetup();
      for (auto * kernel : kernels)
        kernel->timestepSetup();
    }
  }
  _scalar_kernels.timestepSetup();
  _constraints.timestepSetup();
  _general_dampers.timestepSetup();
  _nodal_bcs.timestepSetup();
}
timeVectorTag()
TagID NonlinearSystemBase::timeVectorTag () const inline override virtual inherited
Ideally, we should not need this API.
There exists a really bad API "addCachedResidualDirectly " in FEProblem and DisplacedProblem This API should go away once addCachedResidualDirectly is removed in the future Return Tag ID for Time
Reimplemented from SystemBase.
Definition at line 634 of file NonlinearSystemBase.h.
{ return _Re_time_tag; }
Referenced by FEProblemBase::addCachedResidualDirectly(), and NonlinearSystemBase::containsTimeKernel().
turnOffJacobian()
void NonlinearEigenSystem::turnOffJacobian () override virtual
Turn off the Jacobian (must be called before equation system initialization)
Reimplemented from NonlinearSystemBase.
Definition at line 467 of file NonlinearEigenSystem.C.
{
  // Let us do nothing at the current moment
}
update()
void SystemBase::update (bool update_libmesh_system = true) virtual inherited
Update the system (doing libMesh magic)
Definition at line 1211 of file SystemBase.C.
{
  if (update_libmesh_system)
    system().update();
}
Referenced by Adaptivity::adaptMesh(), MooseEigenSystem::combineSystemSolution(), NonlinearSystemBase::computeDamping(), NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualTags(), EigenProblem::doFreeNonlinearPowerIterations(), PointwiseRenormalizeVector::finalize(), MooseEigenSystem::initSystemSolution(), MooseEigenSystem::initSystemSolutionOld(), MooseEigenSystem::scaleSystemSolution(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::setInitialSolution(), FEProblemBase::solve(), EigenProblem::solve(), DisplacedProblem::syncSolutions(), MultiAppDofCopyTransfer::transfer(), PicardSolve::transformVariables(), SecantSolve::transformVariables(), and SteffensenSolve::transformVariables().
updateActive()
void NonlinearSystemBase::updateActive (THREAD_ID tid) inherited
Update active objects of Warehouses owned by NonlinearSystemBase.
Definition at line 3074 of file NonlinearSystemBase.C.
{
  _element_dampers.updateActive(tid);
  _nodal_dampers.updateActive(tid);
  _integrated_bcs.updateActive(tid);
  _dg_kernels.updateActive(tid);
  _interface_kernels.updateActive(tid);
  _dirac_kernels.updateActive(tid);
  _kernels.updateActive(tid);
  _nodal_kernels.updateActive(tid);
  if (tid == 0)
  {
    _general_dampers.updateActive();
    _nodal_bcs.updateActive();
    _preset_nodal_bcs.updateActive();
    _ad_preset_nodal_bcs.updateActive();
    _constraints.updateActive();
    _scalar_kernels.updateActive();
  }
}
useFieldSplitPreconditioner()
void NonlinearSystemBase::useFieldSplitPreconditioner (bool use = true) inline inherited
If called with true this system will use a field split preconditioner matrix.
Definition at line 452 of file NonlinearSystemBase.h.
{ _use_field_split_preconditioner = use; }
Referenced by FieldSplitPreconditioner::FieldSplitPreconditioner().
useFiniteDifferencedPreconditioner()
void NonlinearSystemBase::useFiniteDifferencedPreconditioner (bool use = true) inline inherited
If called with true this system will use a finite differenced form of the Jacobian as the preconditioner.
Definition at line 437 of file NonlinearSystemBase.h.
  {
    _use_finite_differenced_preconditioner = use;
  }
Referenced by FiniteDifferencePreconditioner::FiniteDifferencePreconditioner().
validParams()
InputParameters PerfGraphInterface::validParams () static inherited
Definition at line 16 of file PerfGraphInterface.C.
{
  InputParameters params = emptyInputParameters();
  return params;
}
varKind()
Moose::VarKindType SystemBase::varKind () const inline inherited
Returns
the type of variables this system holds, e.g. nonlinear or auxiliary
Definition at line 916 of file SystemBase.h.
{ return _var_kind; }
Referenced by Coupleable::coupled(), and UserObject::UserObject().
zeroTaggedVector()
void SystemBase::zeroTaggedVector (const TagID tag) inherited
Zero vector with the given tag.
Definition at line 664 of file SystemBase.C.
{
  if (!_subproblem.vectorTagExists(tag))
    mooseError("Cannot zero vector with TagID ",
               tag,
               " in system '",
               name(),
               "' because that tag does not exist in the problem");
  else if (!hasVector(tag))
    mooseError("Cannot zero vector tag with name '",
               _subproblem.vectorTagName(tag),
               "' in system '",
               name(),
               "' because there is no vector associated with that tag");
  getVector(tag).zero();
}
Referenced by SystemBase::zeroTaggedVectors().
zeroTaggedVectors()
void SystemBase::zeroTaggedVectors (const std::set< TagID > & tags) inherited
Zero all vectors for given tags.
Definition at line 683 of file SystemBase.C.
{
  for (const auto tag : tags)
    zeroTaggedVector(tag);
}
Referenced by NonlinearSystemBase::computeResidualAndJacobianTags(), and NonlinearSystemBase::computeResidualTags().
zeroVariables()
void SystemBase::zeroVariables (std::vector< std::string > & vars_to_be_zeroed) virtual inherited
Zero out the solution for the list of variables passed in.
@ param vars_to_be_zeroed The variable names in this vector will have their solutions set to zero after this call
Reimplemented in DisplacedSystem.
Definition at line 189 of file SystemBase.C.
{
  if (vars_to_be_zeroed.size() > 0)
  {
    NumericVector<Number> & solution = this->solution();
    auto problem = dynamic_cast<FEProblemBase *>(&_subproblem);
    if (!problem)
      mooseError("System needs to be registered in FEProblemBase for using zeroVariables.");
    AllLocalDofIndicesThread aldit(*problem, vars_to_be_zeroed, true);
    ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();
    Threads::parallel_reduce(elem_range, aldit);
    const auto & dof_indices_to_zero = aldit.getDofIndices();
    solution.close();
    for (const auto & dof : dof_indices_to_zero)
      solution.set(dof, 0);
    solution.close();
    // Call update to update the current_local_solution for this system
    system().update();
  }
}
Referenced by DisplacedSystem::zeroVariables(), SystemBase::zeroVariablesForJacobian(), and SystemBase::zeroVariablesForResidual().
zeroVariablesForJacobian()
void SystemBase::zeroVariablesForJacobian () virtual inherited
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on Jacobian evaluation by a call to addVariableToZeroOnResidual()
Definition at line 224 of file SystemBase.C.
{
  zeroVariables(_vars_to_be_zeroed_on_jacobian);
}
zeroVariablesForResidual()
void SystemBase::zeroVariablesForResidual () virtual inherited
Zero out the solution for the variables that were registered as needing to have their solutions zeroed on out on residual evaluation by a call to addVariableToZeroOnResidual()
Definition at line 218 of file SystemBase.C.
{
  zeroVariables(_vars_to_be_zeroed_on_residual);
}
zeroVectorForResidual()
void NonlinearSystemBase::zeroVectorForResidual (const std::string & vector_name) inherited
Definition at line 722 of file NonlinearSystemBase.C.
{
  for (unsigned int i = 0; i < _vecs_to_zero_for_residual.size(); ++i)
    if (vector_name == _vecs_to_zero_for_residual[i])
      return;
  _vecs_to_zero_for_residual.push_back(vector_name);
}
Member Data Documentation
_A_tag
TagID NonlinearEigenSystem::_A_tag protected
Definition at line 186 of file NonlinearEigenSystem.h.
Referenced by nonEigenMatrixTag(), NonlinearEigenSystem(), and postAddResidualObject().
_ad_preset_nodal_bcs
MooseObjectWarehouse<ADDirichletBCBase> NonlinearSystemBase::_ad_preset_nodal_bcs protected inherited
Definition at line 828 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::setInitialSolution(), and NonlinearSystemBase::updateActive().
_add_implicit_geometric_coupling_entries_to_jacobian
bool NonlinearSystemBase::_add_implicit_geometric_coupling_entries_to_jacobian protected inherited
Whether or not to add implicit geometric couplings to the Jacobian for FDP.
Definition at line 874 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addImplicitGeometricCouplingEntriesToJacobian(), NonlinearSystemBase::augmentSparsity(), and NonlinearSystemBase::computeJacobianInternal().
_app
MooseApp& SystemBase::_app protected inherited
Definition at line 926 of file SystemBase.h.
Referenced by NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeJacobianTags(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), and NonlinearSystem::solve().
_assemble_constraints_separately
bool NonlinearSystemBase::_assemble_constraints_separately protected inherited
Whether or not to assemble the residual and Jacobian after the application of each constraint.
Definition at line 877 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::assembleConstraintsSeparately(), NonlinearSystemBase::constraintJacobians(), and NonlinearSystemBase::constraintResiduals().
_auto_scaling_initd
bool NonlinearSystemBase::_auto_scaling_initd private inherited
Whether we've initialized the automatic scaling data structures.
Definition at line 974 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeScaling(), and NonlinearSystemBase::setupScalingData().
_automatic_scaling
bool SystemBase::_automatic_scaling protected inherited
Whether to automatically scale the variables.
Definition at line 979 of file SystemBase.h.
Referenced by SystemBase::automaticScaling(), NonlinearSystem::init(), NonlinearSystemBase::initialSetup(), solve(), and NonlinearSystem::solve().
_Ax_tag
TagID NonlinearEigenSystem::_Ax_tag protected
Definition at line 184 of file NonlinearEigenSystem.h.
Referenced by nonEigenVectorTag(), NonlinearEigenSystem(), and postAddResidualObject().
_B_tag
TagID NonlinearEigenSystem::_B_tag protected
Definition at line 187 of file NonlinearEigenSystem.h.
Referenced by eigenMatrixTag(), NonlinearEigenSystem(), and postAddResidualObject().
_Bx_tag
TagID NonlinearEigenSystem::_Bx_tag protected
Definition at line 185 of file NonlinearEigenSystem.h.
Referenced by eigenVectorTag(), NonlinearEigenSystem(), and postAddResidualObject().
_compute_initial_residual_before_preset_bcs
bool NonlinearSystemBase::_compute_initial_residual_before_preset_bcs inherited
Definition at line 685 of file NonlinearSystemBase.h.
Referenced by FEProblemBase::checkNonlinearConvergence(), FEProblemSolve::FEProblemSolve(), and NonlinearSystem::solve().
_compute_scaling_once
bool NonlinearSystemBase::_compute_scaling_once protected inherited
Whether the scaling factors should only be computed once at the beginning of the simulation through an extra Jacobian evaluation.
If this is set to false, then the scaling factors will be computed during an extra Jacobian evaluation at the beginning of every time step.
Definition at line 925 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeScalingOnce(), solve(), and NonlinearSystem::solve().
_computed_scaling
bool NonlinearSystemBase::_computed_scaling protected inherited
Flag used to indicate whether we have already computed the scaling Jacobian.
Definition at line 920 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computedScalingJacobian(), solve(), and NonlinearSystem::solve().
_computing_initial_residual
bool NonlinearSystemBase::_computing_initial_residual protected inherited
Definition at line 901 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computingInitialResidual(), and NonlinearSystem::solve().
_console
const ConsoleStream ConsoleStreamInterface::_console inherited
An instance of helper class to write streams to the Console objects.
Definition at line 31 of file ConsoleStreamInterface.h.
Referenced by IterationAdaptiveDT::acceptStep(), MaterialOutputAction::act(), MeshOnlyAction::act(), SetupDebugAction::act(), FEProblemBase::adaptMesh(), Adaptivity::adaptMesh(), PerfGraph::addToExecutionList(), SimplePredictor::apply(), SystemBase::applyScalingFactors(), MultiApp::backup(), FEProblemBase::backupMultiApps(), CoarsenedPiecewiseLinear::buildCoarsenedGrid(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), MeshDiagnosticsGenerator::checkElementVolumes(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), FEProblemBase::checkProblemIntegrity(), ReferenceResidualProblem::checkRelativeConvergence(), MeshDiagnosticsGenerator::checkSidesetsOrientation(), IterationAdaptiveDT::computeAdaptiveDT(), Transient::computeConstrainedDT(), FixedPointSolve::computeCustomConvergencePostprocessor(), NonlinearSystemBase::computeDamping(), IterationAdaptiveDT::computeDT(), IterationAdaptiveDT::computeFailedDT(), IterationAdaptiveDT::computeInitialDT(), IterationAdaptiveDT::computeInterpolationDT(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), NonlinearSystemBase::computeScaling(), Problem::console(), TimeStepper::constrainStep(), IterationAdaptiveDT::constrainStep(), MultiApp::createApp(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), Eigenvalue::execute(), Steady::execute(), MessageFromInput::execute(), ActionWarehouse::executeActionsWithAction(), ActionWarehouse::executeAllActions(), ElementQualityChecker::finalize(), FEProblemBase::finishMultiAppStep(), MeshRepairGenerator::fixOverlappingNodes(), MeshGenerator::generateInternal(), VariableCondensationPreconditioner::getDofToCondense(), InversePowerMethod::init(), NonlinearEigen::init(), FEProblemBase::initialAdaptMesh(), EigenExecutionerBase::inversePowerIteration(), FEProblemBase::joinAndFinalize(), Transient::keepGoing(), IterationAdaptiveDT::limitDTByFunction(), IterationAdaptiveDT::limitDTToPostprocessorValue(), FEProblemBase::logAdd(), EigenExecutionerBase::makeBXConsistent(), Console::meshChanged(), MooseBaseErrorInterface::mooseDeprecated(), MooseBaseErrorInterface::mooseInfo(), MooseBaseErrorInterface::mooseWarning(), MooseBaseErrorInterface::mooseWarningNonPrefixed(), ReferenceResidualProblem::nonlinearConvergenceSetup(), Console::output(), DOFMapOutput::output(), MaterialPropertyDebugOutput::output(), PerfGraphOutput::output(), ReporterDebugOutput::output(), VariableResidualNormsDebugOutput::output(), ControlOutput::outputActiveObjects(), ControlOutput::outputChangedControls(), ControlOutput::outputControls(), Console::outputInput(), Console::outputPostprocessors(), PseudoTimestep::outputPseudoTimestep(), Console::outputReporters(), Console::outputScalarVariables(), Console::outputSystemInformation(), FEProblemBase::possiblyRebuildGeomSearchPatches(), EigenExecutionerBase::postExecute(), AB2PredictorCorrector::postSolve(), ActionWarehouse::printActionDependencySets(), SolutionInvalidity::printDebug(), EigenExecutionerBase::printEigenvalue(), PicardSolve::printFixedPointConvergenceHistory(), SecantSolve::printFixedPointConvergenceHistory(), SteffensenSolve::printFixedPointConvergenceHistory(), FixedPointSolve::printFixedPointConvergenceReason(), PerfGraphLivePrint::printLiveMessage(), MaterialPropertyDebugOutput::printMaterialMap(), PerfGraphLivePrint::printStats(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), AutomaticMortarGeneration::projectSecondaryNodesSinglePair(), SolutionTimeAdaptiveDT::rejectStep(), MultiApp::restore(), FEProblemBase::restoreMultiApps(), SimplePredictor::shouldApply(), Checkpoint::shouldOutput(), SubProblem::showFunctorRequestors(), SubProblem::showFunctors(), FullSolveMultiApp::showStatusMessage(), FEProblemSolve::solve(), FixedPointSolve::solve(), NonlinearSystem::solve(), AStableDirk4::solve(), ExplicitRK2::solve(), ExplicitTVDRK2::solve(), ImplicitMidpoint::solve(), LStableDirk2::solve(), LStableDirk3::solve(), LStableDirk4::solve(), EigenProblem::solve(), FixedPointSolve::solveStep(), TransientMultiApp::solveStep(), PerfGraphLivePrint::start(), AB2PredictorCorrector::step(), NonlinearEigen::takeStep(), Transient::takeStep(), Console::writeTimestepInformation(), Console::writeVariableNorms(), and FEProblemBase::~FEProblemBase().
_constraints
ConstraintWarehouse NonlinearSystemBase::_constraints protected inherited
Constraints storage object.
Definition at line 850 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addConstraint(), NonlinearSystemBase::checkKernelCoverage(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), NonlinearSystemBase::customSetup(), NonlinearSystemBase::enforceNodalConstraintsJacobian(), NonlinearSystemBase::enforceNodalConstraintsResidual(), NonlinearSystemBase::findImplicitGeometricCouplingEntries(), NonlinearSystemBase::getConstraintWarehouse(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::timestepSetup(), and NonlinearSystemBase::updateActive().
_current_l_its
std::vector<unsigned int> NonlinearSystemBase::_current_l_its inherited
Definition at line 683 of file NonlinearSystemBase.h.
Referenced by SolutionHistory::output(), solve(), and NonlinearSystem::solve().
_current_nl_its
unsigned int NonlinearSystemBase::_current_nl_its inherited
Definition at line 684 of file NonlinearSystemBase.h.
Referenced by FEProblemBase::checkNonlinearConvergence(), SolutionHistory::output(), solve(), and NonlinearSystem::solve().
_current_solution
const NumericVector<Number>* NonlinearSystemBase::_current_solution protected inherited
solution vector from nonlinear solver
Definition at line 762 of file NonlinearSystemBase.h.
Referenced by computeScalingJacobian(), NonlinearSystem::computeScalingJacobian(), computeScalingResidual(), NonlinearSystem::computeScalingResidual(), NonlinearSystemBase::currentSolution(), NonlinearSystemBase::init(), NonlinearSystemBase::restoreSolutions(), NonlinearSystemBase::serializeSolution(), NonlinearSystemBase::setSolution(), and NonlinearSystem::solve().
_debugging_residuals
bool NonlinearSystemBase::_debugging_residuals protected inherited
true if debugging residuals
Definition at line 882 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeResidualTags(), and NonlinearSystemBase::debuggingResiduals().
_decomposition_split
std::string NonlinearSystemBase::_decomposition_split protected inherited
Name of the top-level split of the decomposition.
Definition at line 869 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::setDecomposition(), and NonlinearSystemBase::setupFieldDecomposition().
_dg_kernels
MooseObjectTagWarehouse<DGKernelBase> NonlinearSystemBase::_dg_kernels protected inherited
Definition at line 818 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addDGKernel(), NonlinearSystemBase::checkKernelCoverage(), NonlinearSystemBase::customSetup(), NonlinearSystemBase::getDGKernelWarehouse(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), NonlinearSystemBase::timestepSetup(), and NonlinearSystemBase::updateActive().
_dirac_kernels
MooseObjectTagWarehouse<DiracKernelBase> NonlinearSystemBase::_dirac_kernels protected inherited
Dirac Kernel storage for each thread.
Definition at line 832 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addDiracKernel(), NonlinearSystemBase::computeDiracContributions(), NonlinearSystemBase::customSetup(), NonlinearSystemBase::getDiracKernelWarehouse(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), NonlinearSystemBase::timestepSetup(), and NonlinearSystemBase::updateActive().
_displaced_mortar_functors
std::unordered_map<std::pair<BoundaryID, BoundaryID>, ComputeMortarFunctor> NonlinearSystemBase::_displaced_mortar_functors private inherited
Functors for computing displaced mortar constraints.
Definition at line 968 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::initialSetup(), and NonlinearSystemBase::mortarConstraints().
_doing_dg
bool NonlinearSystemBase::_doing_dg protected inherited
true if DG is active (optimization reasons)
Definition at line 885 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addDGKernel(), NonlinearSystemBase::customSetup(), NonlinearSystemBase::doingDG(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::needSubdomainMaterialOnSide(), NonlinearSystemBase::residualSetup(), and NonlinearSystemBase::timestepSetup().
_du_dot_du
Number NonlinearSystemBase::_du_dot_du protected inherited
\({du^dot}\over{du} \)
Definition at line 784 of file NonlinearSystemBase.h.
_du_dotdot_du
Number NonlinearSystemBase::_du_dotdot_du protected inherited
\({du^dotdot}\over{du} \)
Definition at line 786 of file NonlinearSystemBase.h.
_eigen_problem
EigenProblem& NonlinearEigenSystem::_eigen_problem protected
Definition at line 178 of file NonlinearEigenSystem.h.
Referenced by attachPreconditioner(), attachSLEPcCallbacks(), computeScalingJacobian(), computeScalingResidual(), getSNES(), and solve().
_eigen_sys
EigenSystem& NonlinearEigenSystem::_eigen_sys protected
Definition at line 177 of file NonlinearEigenSystem.h.
Referenced by attachSLEPcCallbacks(), converged(), getConvergedEigenpair(), getConvergedEigenvalue(), getEPS(), getNumConvergedEigenvalues(), NonlinearEigenSystem(), solve(), and sys().
_eigen_values
std::vector<std::pair<Real, Real> > NonlinearEigenSystem::_eigen_values protected
Definition at line 180 of file NonlinearEigenSystem.h.
Referenced by getAllConvergedEigenvalues(), and solve().
_element_dampers
MooseObjectWarehouse<ElementDamper> NonlinearSystemBase::_element_dampers protected inherited
Element Dampers for each thread.
Definition at line 835 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addDamper(), NonlinearSystemBase::computeDamping(), NonlinearSystemBase::customSetup(), NonlinearSystemBase::getElementDamperWarehouse(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), NonlinearSystemBase::subdomainSetup(), NonlinearSystemBase::timestepSetup(), and NonlinearSystemBase::updateActive().
_factory
Factory& SystemBase::_factory protected inherited
Definition at line 927 of file SystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addConstraint(), NonlinearSystemBase::addDamper(), NonlinearSystemBase::addDGKernel(), NonlinearSystemBase::addDiracKernel(), NonlinearSystemBase::addInterfaceKernel(), AuxiliarySystem::addKernel(), MooseEigenSystem::addKernel(), NonlinearSystemBase::addKernel(), NonlinearSystemBase::addNodalKernel(), AuxiliarySystem::addScalarKernel(), NonlinearSystemBase::addScalarKernel(), NonlinearSystemBase::addSplit(), AuxiliarySystem::addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), and SystemBase::addVariable().
_fdcoloring
MatFDColoring NonlinearSystemBase::_fdcoloring protected inherited
Definition at line 864 of file NonlinearSystemBase.h.
Referenced by NonlinearSystem::setupColoringFiniteDifferencedPreconditioner(), and NonlinearSystem::solve().
_fe_problem
FEProblemBase& NonlinearSystemBase::_fe_problem inherited
Definition at line 677 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addDotVectors(), NonlinearSystemBase::assembleScalingVector(), NonlinearSystemBase::augmentSparsity(), NonlinearSystemBase::checkKernelCoverage(), NonlinearSystemBase::computeDamping(), NonlinearSystemBase::computeDiracContributions(), NonlinearSystemBase::computeJacobian(), NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeNodalBCs(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::computeScalarKernelsJacobians(), NonlinearSystemBase::computeScaling(), NonlinearSystem::computeScalingJacobian(), NonlinearSystem::computeScalingResidual(), NonlinearSystemBase::computeTimeDerivatives(), NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), NonlinearSystem::converged(), NonlinearSystemBase::customSetup(), DMMooseGetEmbedding_Private(), DMSetFromOptions_Moose(), DMSetUp_Moose_Pre(), MooseEigenSystem::eigenKernelOnCurrent(), MooseEigenSystem::eigenKernelOnOld(), NonlinearSystemBase::enforceNodalConstraintsJacobian(), NonlinearSystemBase::enforceNodalConstraintsResidual(), NonlinearSystemBase::getResidualNonTimeVector(), NonlinearSystemBase::getResidualTimeVector(), NonlinearSystemBase::init(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::NonlinearSystemBase(), NonlinearSystem::residualAndJacobianTogether(), NonlinearSystemBase::residualSetup(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::setInitialSolution(), NonlinearSystem::solve(), and NonlinearSystemBase::timestepSetup().
_final_residual
Real NonlinearSystemBase::_final_residual protected inherited
Definition at line 896 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::finalNonlinearResidual(), and NonlinearSystem::solve().
_general_dampers
MooseObjectWarehouse<GeneralDamper> NonlinearSystemBase::_general_dampers protected inherited
General Dampers.
Definition at line 841 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addDamper(), NonlinearSystemBase::computeDamping(), NonlinearSystemBase::customSetup(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), NonlinearSystemBase::timestepSetup(), and NonlinearSystemBase::updateActive().
_has_diag_save_in
bool NonlinearSystemBase::_has_diag_save_in protected inherited
If there is any Kernel or IntegratedBC having diag_save_in.
Definition at line 909 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addDGKernel(), MooseEigenSystem::addKernel(), NonlinearSystemBase::addKernel(), NonlinearSystemBase::addNodalKernel(), NonlinearSystemBase::computeJacobianInternal(), and NonlinearSystemBase::hasDiagSaveIn().
_has_nodalbc_diag_save_in
bool NonlinearSystemBase::_has_nodalbc_diag_save_in protected inherited
If there is a nodal BC having diag_save_in.
Definition at line 915 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::computeJacobianInternal(), and NonlinearSystemBase::hasDiagSaveIn().
_has_nodalbc_save_in
bool NonlinearSystemBase::_has_nodalbc_save_in protected inherited
If there is a nodal BC having save_in.
Definition at line 912 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::computeResidualTags(), and NonlinearSystemBase::hasSaveIn().
_has_save_in
bool NonlinearSystemBase::_has_save_in protected inherited
If there is any Kernel or IntegratedBC having save_in.
Definition at line 906 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addDGKernel(), MooseEigenSystem::addKernel(), NonlinearSystemBase::addKernel(), NonlinearSystemBase::addNodalKernel(), NonlinearSystemBase::computeNodalBCs(), and NonlinearSystemBase::hasSaveIn().
_have_decomposition
bool NonlinearSystemBase::_have_decomposition protected inherited
Whether or not the system can be decomposed into splits.
Definition at line 867 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::setDecomposition(), and NonlinearSystemBase::setupFieldDecomposition().
_ignore_variables_for_autoscaling
std::vector<std::string> NonlinearSystemBase::_ignore_variables_for_autoscaling protected inherited
A container for variables that do not partipate in autoscaling.
Definition at line 941 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::ignoreVariablesForAutoscaling(), and NonlinearSystemBase::setupScalingData().
_increment_vec
NumericVector<Number>* NonlinearSystemBase::_increment_vec protected inherited
increment vector
Definition at line 853 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeDamping(), NonlinearSystemBase::reinitIncrementAtNodeForDampers(), NonlinearSystemBase::reinitIncrementAtQpsForDampers(), and NonlinearSystemBase::setupDampers().
_initial_residual_after_preset_bcs
Real NonlinearSystemBase::_initial_residual_after_preset_bcs inherited
Definition at line 682 of file NonlinearSystemBase.h.
Referenced by FEProblemBase::checkNonlinearConvergence(), and Residual::getValue().
_initial_residual_before_preset_bcs
Real NonlinearSystemBase::_initial_residual_before_preset_bcs inherited
Definition at line 681 of file NonlinearSystemBase.h.
Referenced by Residual::getValue(), EigenExecutionerBase::inversePowerIteration(), Moose::PetscSupport::petscNonlinearConverged(), and NonlinearSystem::solve().
_integrated_bcs
MooseObjectTagWarehouse<IntegratedBCBase> NonlinearSystemBase::_integrated_bcs protected inherited
BoundaryCondition Warhouses
Definition at line 825 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::customSetup(), NonlinearSystemBase::getIntegratedBCWarehouse(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::needBoundaryMaterialOnSide(), NonlinearSystemBase::residualSetup(), NonlinearSystemBase::timestepSetup(), and NonlinearSystemBase::updateActive().
_interface_kernels
MooseObjectTagWarehouse<InterfaceKernelBase> NonlinearSystemBase::_interface_kernels protected inherited
Definition at line 819 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addInterfaceKernel(), NonlinearSystemBase::customSetup(), NonlinearSystemBase::getInterfaceKernelWarehouse(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::needInterfaceMaterialOnSide(), NonlinearSystemBase::residualSetup(), NonlinearSystemBase::timestepSetup(), and NonlinearSystemBase::updateActive().
_Ke_non_time_tag
TagID NonlinearSystemBase::_Ke_non_time_tag protected inherited
Tag for non-time contribution Jacobian.
Definition at line 809 of file NonlinearSystemBase.h.
_Ke_system_tag
TagID NonlinearSystemBase::_Ke_system_tag protected inherited
Tag for system contribution Jacobian.
Definition at line 812 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::NonlinearSystemBase(), and NonlinearSystemBase::systemMatrixTag().
_kernels
MooseObjectTagWarehouse<KernelBase> NonlinearSystemBase::_kernels protected inherited
Kernel Storage
Definition at line 816 of file NonlinearSystemBase.h.
Referenced by MooseEigenSystem::addKernel(), NonlinearSystemBase::addKernel(), NonlinearSystemBase::checkKernelCoverage(), NonlinearSystemBase::containsTimeKernel(), NonlinearSystemBase::customSetup(), NonlinearSystemBase::getKernelWarehouse(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), NonlinearSystemBase::subdomainSetup(), NonlinearSystemBase::timestepSetup(), and NonlinearSystemBase::updateActive().
_ksp_norm
Moose::MooseKSPNormType NonlinearSystemBase::_ksp_norm protected inherited
KSP norm type.
Definition at line 859 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::getMooseKSPNormType(), and NonlinearSystemBase::setMooseKSPNormType().
_last_nl_rnorm
Real NonlinearSystemBase::_last_nl_rnorm inherited
Definition at line 680 of file NonlinearSystemBase.h.
Referenced by FEProblemBase::checkNonlinearConvergence(), and NonlinearSystemBase::nonlinearNorm().
_matrix_tag_active_flags
std::vector<bool> SystemBase::_matrix_tag_active_flags protected inherited
Active flags for tagged matrices.
Definition at line 951 of file SystemBase.h.
Referenced by SystemBase::activeAllMatrixTags(), SystemBase::activeMatrixTag(), SystemBase::deactiveAllMatrixTags(), SystemBase::deactiveMatrixTag(), and SystemBase::matrixTagActive().
_max_var_n_dofs_per_elem
size_t SystemBase::_max_var_n_dofs_per_elem protected inherited
Maximum number of dofs for any one variable on any one element.
Definition at line 967 of file SystemBase.h.
Referenced by SystemBase::assignMaxVarNDofsPerElem(), and SystemBase::getMaxVarNDofsPerElem().
_max_var_n_dofs_per_node
size_t SystemBase::_max_var_n_dofs_per_node protected inherited
Maximum number of dofs for any one variable on any one node.
Definition at line 970 of file SystemBase.h.
Referenced by SystemBase::assignMaxVarNDofsPerNode(), and SystemBase::getMaxVarNDofsPerNode().
_max_var_number
unsigned int SystemBase::_max_var_number protected inherited
Maximum variable number.
Definition at line 938 of file SystemBase.h.
Referenced by SystemBase::addVariable(), and SystemBase::getMaxVariableNumber().
_mesh
MooseMesh& SystemBase::_mesh protected inherited
Definition at line 929 of file SystemBase.h.
Referenced by SystemBase::addVariable(), NonlinearSystemBase::assembleScalingVector(), SystemBase::augmentSendList(), NonlinearSystemBase::checkKernelCoverage(), NonlinearSystemBase::computeDamping(), AuxiliarySystem::computeElementalVarsHelper(), NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), AuxiliarySystem::computeMortarNodalVars(), NonlinearSystemBase::computeNodalBCs(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), AuxiliarySystem::computeNodalVarsHelper(), NonlinearSystemBase::computeResidualAndJacobianInternal(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::constraintJacobians(), NonlinearSystemBase::constraintResiduals(), NonlinearSystemBase::findImplicitGeometricCouplingEntries(), NonlinearSystemBase::getNodeDofs(), SystemBase::mesh(), NonlinearSystemBase::setConstraintSecondaryValues(), NonlinearSystemBase::setInitialSolution(), SystemBase::setVariableGlobalDoFs(), and SystemBase::zeroVariables().
_n_eigen_pairs_required
unsigned int NonlinearEigenSystem::_n_eigen_pairs_required protected
Definition at line 181 of file NonlinearEigenSystem.h.
Referenced by solve().
_n_iters
unsigned int NonlinearSystemBase::_n_iters protected inherited
Definition at line 890 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::nNonlinearIterations(), and NonlinearSystem::solve().
_n_linear_iters
unsigned int NonlinearSystemBase::_n_linear_iters protected inherited
Definition at line 891 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::nLinearIterations(), and NonlinearSystem::solve().
_n_residual_evaluations
unsigned int NonlinearSystemBase::_n_residual_evaluations protected inherited
Total number of residual evaluations that have been performed.
Definition at line 894 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeResidualTags(), and NonlinearSystemBase::nResidualEvaluations().
_name
std::string SystemBase::_name protected inherited
The name of this system.
Definition at line 931 of file SystemBase.h.
_need_residual_ghosted
bool NonlinearSystemBase::_need_residual_ghosted protected inherited
Whether or not a ghosted copy of the residual needs to be made.
Definition at line 880 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::constraintResiduals(), NonlinearSystemBase::getResidualNonTimeVector(), NonlinearSystemBase::getResidualTimeVector(), and NonlinearSystemBase::residualGhosted().
_nl_matrix_tags
std::set<TagID> NonlinearSystemBase::_nl_matrix_tags protected inherited
Matrix tags to temporarily store all tags associated with the current system.
Definition at line 795 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeJacobian(), and NonlinearSystemBase::computeJacobianBlocks().
_nl_vector_tags
std::set<TagID> NonlinearSystemBase::_nl_vector_tags protected inherited
Vector tags to temporarily store all tags associated with the current system.
Definition at line 792 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeNodalBCs(), and NonlinearSystemBase::computeResidualTag().
_nodal_bcs
MooseObjectTagWarehouse<NodalBCBase> NonlinearSystemBase::_nodal_bcs protected inherited
Definition at line 826 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), checkIntegrity(), NonlinearSystemBase::computeJacobianBlocks(), NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeNodalBCs(), NonlinearSystemBase::computeNodalBCsResidualAndJacobian(), NonlinearSystemBase::customSetup(), NonlinearSystemBase::getNodalBCWarehouse(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), NonlinearSystemBase::timestepSetup(), and NonlinearSystemBase::updateActive().
_nodal_dampers
MooseObjectWarehouse<NodalDamper> NonlinearSystemBase::_nodal_dampers protected inherited
Nodal Dampers for each thread.
Definition at line 838 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addDamper(), NonlinearSystemBase::computeDamping(), NonlinearSystemBase::customSetup(), NonlinearSystemBase::getNodalDamperWarehouse(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), NonlinearSystemBase::subdomainSetup(), NonlinearSystemBase::timestepSetup(), and NonlinearSystemBase::updateActive().
_nodal_kernels
MooseObjectTagWarehouse<NodalKernelBase> NonlinearSystemBase::_nodal_kernels protected inherited
NodalKernels for each thread.
Definition at line 844 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addNodalKernel(), NonlinearSystemBase::checkKernelCoverage(), NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::customSetup(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), NonlinearSystemBase::subdomainSetup(), NonlinearSystemBase::timestepSetup(), and NonlinearSystemBase::updateActive().
_num_residual_evaluations
unsigned int NonlinearSystemBase::_num_residual_evaluations inherited
Definition at line 542 of file NonlinearSystemBase.h.
_num_scaling_groups
std::size_t NonlinearSystemBase::_num_scaling_groups private inherited
The number of scaling groups.
Definition at line 980 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeScaling(), and NonlinearSystemBase::setupScalingData().
_numbered_vars
std::vector<std::vector<MooseVariableFieldBase *> > SystemBase::_numbered_vars protected inherited
Map variable number to its pointer.
Definition at line 976 of file SystemBase.h.
Referenced by SystemBase::addVariable(), and SystemBase::getVariable().
_off_diagonals_in_auto_scaling
bool NonlinearSystemBase::_off_diagonals_in_auto_scaling protected inherited
Whether to include off diagonals when determining automatic scaling factors.
Definition at line 944 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::initialSetup(), and NonlinearSystemBase::offDiagonalsInAutoScaling().
_pc_side
Moose::PCSideType NonlinearSystemBase::_pc_side protected inherited
Preconditioning side.
Definition at line 857 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::getPCSide(), and NonlinearSystemBase::setPCSide().
_pg_moose_app
MooseApp& PerfGraphInterface::_pg_moose_app protected inherited
The MooseApp that owns the PerfGraph.
Definition at line 124 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::perfGraph().
_precond_matrix_includes_eigen
bool NonlinearEigenSystem::_precond_matrix_includes_eigen protected
Definition at line 189 of file NonlinearEigenSystem.h.
Referenced by postAddResidualObject(), and precondMatrixIncludesEigenKernels().
_precond_tag
TagID NonlinearEigenSystem::_precond_tag protected
Definition at line 188 of file NonlinearEigenSystem.h.
Referenced by NonlinearEigenSystem(), postAddResidualObject(), and precondMatrixTag().
_preconditioner
Preconditioner<Number>* NonlinearEigenSystem::_preconditioner protected
Definition at line 191 of file NonlinearEigenSystem.h.
Referenced by attachPreconditioner(), and preconditioner().
_predictor
std::shared_ptr<Predictor> NonlinearSystemBase::_predictor protected inherited
If predictor is active, this is non-NULL.
Definition at line 899 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::getPredictor(), NonlinearSystemBase::onTimestepBegin(), NonlinearSystemBase::setInitialSolution(), and NonlinearSystemBase::setPredictor().
_prefix
const std::string PerfGraphInterface::_prefix protected inherited
A prefix to use for all sections.
Definition at line 127 of file PerfGraphInterface.h.
Referenced by PerfGraphInterface::timedSectionName().
_preset_nodal_bcs
MooseObjectWarehouse<DirichletBCBase> NonlinearSystemBase::_preset_nodal_bcs protected inherited
Definition at line 827 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::setInitialSolution(), and NonlinearSystemBase::updateActive().
_print_all_var_norms
bool NonlinearSystemBase::_print_all_var_norms protected inherited
Definition at line 903 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::printAllVariableNorms().
_Re_non_time
NumericVector<Number>* NonlinearSystemBase::_Re_non_time protected inherited
residual vector for non-time contributions
Definition at line 803 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeNodalBCs(), NonlinearSystemBase::computeResidualAndJacobianTags(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::getResidualNonTimeVector(), NonlinearSystemBase::residualGhosted(), and NonlinearSystem::stopSolve().
_Re_non_time_tag
TagID NonlinearSystemBase::_Re_non_time_tag protected inherited
Tag for non-time contribution residual.
Definition at line 801 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::getResidualNonTimeVector(), NonlinearSystemBase::nonTimeVectorTag(), and NonlinearSystemBase::residualGhosted().
_Re_tag
TagID NonlinearSystemBase::_Re_tag protected inherited
Used for the residual vector from PETSc.
Definition at line 806 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::NonlinearSystemBase(), and NonlinearSystemBase::residualVectorTag().
_Re_time
NumericVector<Number>* NonlinearSystemBase::_Re_time protected inherited
residual vector for time contributions
Definition at line 798 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeNodalBCs(), NonlinearSystemBase::getResidualTimeVector(), NonlinearSystemBase::residualGhosted(), and NonlinearSystem::stopSolve().
_Re_time_tag
TagID NonlinearSystemBase::_Re_time_tag protected inherited
Tag for time contribution residual.
Definition at line 789 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::getResidualTimeVector(), NonlinearSystemBase::residualGhosted(), and NonlinearSystemBase::timeVectorTag().
_resid_vs_jac_scaling_param
Real NonlinearSystemBase::_resid_vs_jac_scaling_param protected inherited
The param that indicates the weighting of the residual vs the Jacobian in determining variable scaling parameters.
A value of 1 indicates pure residual-based scaling. A value of 0 indicates pure Jacobian-based scaling
Definition at line 930 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::autoScalingParam(), NonlinearSystemBase::computeScaling(), and NonlinearSystem::init().
_residual_copy
std::unique_ptr<NumericVector<Number> > NonlinearSystemBase::_residual_copy protected inherited
Copy of the residual vector, or nullptr if a copy is not needed.
Definition at line 771 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::init(), and NonlinearSystemBase::residualCopy().
_residual_ghosted
NumericVector<Number>* NonlinearSystemBase::_residual_ghosted protected inherited
ghosted form of the residual
Definition at line 764 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::constraintResiduals(), and NonlinearSystemBase::residualGhosted().
_saved_dot_old
NumericVector<Real>* SystemBase::_saved_dot_old protected inherited
Definition at line 958 of file SystemBase.h.
Referenced by SystemBase::restoreOldSolutions(), and SystemBase::saveOldSolutions().
_saved_dotdot_old
NumericVector<Real>* SystemBase::_saved_dotdot_old protected inherited
Definition at line 959 of file SystemBase.h.
Referenced by SystemBase::restoreOldSolutions(), and SystemBase::saveOldSolutions().
_saved_old
NumericVector<Real>* SystemBase::_saved_old protected inherited
Definition at line 954 of file SystemBase.h.
_saved_older
NumericVector<Real>* SystemBase::_saved_older protected inherited
Definition at line 955 of file SystemBase.h.
_saved_solution_states
std::vector<NumericVector<Number> *> SystemBase::_saved_solution_states private inherited
The saved solution states (0 = current, 1 = old, 2 = older, etc)
Definition at line 1000 of file SystemBase.h.
Referenced by SystemBase::restoreOldSolutions(), and SystemBase::saveOldSolutions().
_scalar_kernels
MooseObjectTagWarehouse<ScalarKernelBase> NonlinearSystemBase::_scalar_kernels protected inherited
Definition at line 817 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addScalarKernel(), NonlinearSystemBase::checkKernelCoverage(), NonlinearSystemBase::computeResidualInternal(), NonlinearSystemBase::computeScalarKernelsJacobians(), NonlinearSystemBase::customSetup(), NonlinearSystemBase::initialSetup(), NonlinearSystemBase::jacobianSetup(), NonlinearSystemBase::residualSetup(), NonlinearSystemBase::timestepSetup(), and NonlinearSystemBase::updateActive().
_scaling_group_variables
std::vector<std::vector<std::string> > NonlinearSystemBase::_scaling_group_variables protected inherited
A container of variable groupings that can be used in scaling calculations.
This can be useful for simulations in which vector-like variables are split into invidual scalar-field components like for solid/fluid mechanics
Definition at line 935 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::scalingGroupVariables(), and NonlinearSystemBase::setupScalingData().
_scaling_matrix
std::unique_ptr<DiagonalMatrix<Number> > NonlinearSystemBase::_scaling_matrix protected inherited
A diagonal matrix used for computing scaling.
Definition at line 947 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeScaling(), computeScalingJacobian(), NonlinearSystem::computeScalingJacobian(), and NonlinearSystemBase::initialSetup().
_serialized_solution
std::unique_ptr<NumericVector<Number> > NonlinearSystemBase::_serialized_solution protected inherited
Serialized version of the solution vector, or nullptr if a serialized solution is not needed.
Definition at line 768 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::init(), NonlinearSystemBase::serializedSolution(), NonlinearSystemBase::serializeSolution(), and NonlinearSystemBase::setSolution().
_solution_state
std::vector<NumericVector<Number> *> NonlinearSystemBase::_solution_state private inherited
The current states of the solution (0 = current, 1 = old, etc)
Definition at line 971 of file NonlinearSystemBase.h.
_solution_states
std::array<std::vector<NumericVector<Number> *>, 2> SystemBase::_solution_states private inherited
The solution states (0 = current, 1 = old, 2 = older, etc)
Definition at line 998 of file SystemBase.h.
Referenced by SystemBase::copyOldSolutions(), SystemBase::copySolutionsBackwards(), SystemBase::hasSolutionState(), SystemBase::needSolutionState(), SystemBase::restoreOldSolutions(), SystemBase::saveOldSolutions(), and SystemBase::solutionState().
_solution_states_initialized
bool SystemBase::_solution_states_initialized protected inherited
Whether or not the solution states have been initialized.
Definition at line 985 of file SystemBase.h.
Referenced by SystemBase::initSolutionState(), and SystemBase::solutionStatesInitialized().
_solver_configuration
std::unique_ptr<SlepcEigenSolverConfiguration> NonlinearEigenSystem::_solver_configuration protected
Definition at line 179 of file NonlinearEigenSystem.h.
Referenced by NonlinearEigenSystem().
_splits
MooseObjectWarehouseBase<Split> NonlinearSystemBase::_splits protected inherited
Decomposition splits.
Definition at line 847 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addSplit(), and NonlinearSystemBase::getSplit().
_subproblem
SubProblem& SystemBase::_subproblem protected inherited
Definition at line 924 of file SystemBase.h.
Referenced by SystemBase::activeAllMatrixTags(), SystemBase::activeMatrixTag(), SystemBase::addMatrix(), SystemBase::addScalingVector(), SystemBase::addVariable(), SystemBase::addVector(), SystemBase::associateMatrixToTag(), SystemBase::associateVectorToTag(), SystemBase::augmentSendList(), SystemBase::closeTaggedVector(), SystemBase::computingScalingJacobian(), SystemBase::copyVars(), SystemBase::deactiveAllMatrixTags(), SystemBase::deactiveMatrixTag(), SystemBase::disassociateDefaultMatrixTags(), SystemBase::disassociateDefaultVectorTags(), SystemBase::disassociateMatrixFromTag(), SystemBase::disassociateVectorFromTag(), SystemBase::getMatrix(), NonlinearSystemBase::getResidualNonTimeVector(), NonlinearSystemBase::getResidualTimeVector(), SystemBase::getVector(), SystemBase::matrixTagActive(), SystemBase::needSolutionState(), SystemBase::prepare(), SystemBase::prepareFace(), SystemBase::reinitElem(), SystemBase::removeMatrix(), SystemBase::removeVector(), NonlinearSystemBase::residualGhosted(), NonlinearSystemBase::setSolution(), SystemBase::setVariableGlobalDoFs(), SystemBase::subproblem(), SystemBase::zeroTaggedVector(), and SystemBase::zeroVariables().
_sys
System& NonlinearSystemBase::_sys inherited
Definition at line 678 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::init(), NonlinearSystemBase::NonlinearSystemBase(), NonlinearSystemBase::restoreSolutions(), NonlinearSystemBase::serializedSolution(), NonlinearSystemBase::serializeSolution(), NonlinearSystemBase::setInitialSolution(), NonlinearSystemBase::setupDampers(), NonlinearSystemBase::solutionInternal(), and NonlinearSystemBase::system().
_tagged_matrices
std::vector<SparseMatrix<Number> *> SystemBase::_tagged_matrices protected inherited
Tagged matrices (pointer)
Definition at line 949 of file SystemBase.h.
Referenced by SystemBase::associateMatrixToTag(), SystemBase::disassociateMatrixFromTag(), SystemBase::getMatrix(), SystemBase::hasMatrix(), and SystemBase::removeMatrix().
_tagged_vectors
std::vector<NumericVector<Number> *> SystemBase::_tagged_vectors protected inherited
Tagged vectors (pointer)
Definition at line 947 of file SystemBase.h.
Referenced by SystemBase::associateVectorToTag(), SystemBase::disassociateVectorFromTag(), SystemBase::getVector(), SystemBase::hasVector(), and SystemBase::removeVector().
_time_integrator
std::shared_ptr<TimeIntegrator> SystemBase::_time_integrator protected inherited
Time integrator.
Definition at line 973 of file SystemBase.h.
Referenced by AuxiliarySystem::addTimeIntegrator(), NonlinearSystemBase::addTimeIntegrator(), DisplacedSystem::addTimeIntegrator(), AuxiliarySystem::compute(), NonlinearSystemBase::computeResidualAndJacobianTags(), NonlinearSystemBase::computeResidualTags(), NonlinearSystemBase::computeTimeDerivatives(), SystemBase::getSharedTimeIntegrator(), SystemBase::getTimeIntegrator(), NonlinearSystemBase::onTimestepBegin(), solve(), and NonlinearSystem::solve().
_u_dot
NumericVector<Number>* NonlinearSystemBase::_u_dot protected inherited
solution vector for u^dot
Definition at line 774 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addDotVectors(), NonlinearSystemBase::setSolutionUDot(), and NonlinearSystemBase::solutionUDot().
_u_dot_old
NumericVector<Number>* NonlinearSystemBase::_u_dot_old protected inherited
old solution vector for u^dot
Definition at line 779 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addDotVectors(), NonlinearSystemBase::setSolutionUDotOld(), and NonlinearSystemBase::solutionUDotOld().
_u_dotdot
NumericVector<Number>* NonlinearSystemBase::_u_dotdot protected inherited
solution vector for u^dotdot
Definition at line 776 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addDotVectors(), NonlinearSystemBase::setSolutionUDotDot(), and NonlinearSystemBase::solutionUDotDot().
_u_dotdot_old
NumericVector<Number>* NonlinearSystemBase::_u_dotdot_old protected inherited
old solution vector for u^dotdot
Definition at line 781 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::addDotVectors(), NonlinearSystemBase::setSolutionUDotDotOld(), and NonlinearSystemBase::solutionUDotDotOld().
_undisplaced_mortar_functors
std::unordered_map<std::pair<BoundaryID, BoundaryID>, ComputeMortarFunctor> NonlinearSystemBase::_undisplaced_mortar_functors private inherited
Functors for computing undisplaced mortar constraints.
Definition at line 964 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::initialSetup(), and NonlinearSystemBase::mortarConstraints().
_use_field_split_preconditioner
bool NonlinearSystemBase::_use_field_split_preconditioner protected inherited
Whether or not to use a FieldSplitPreconditioner matrix based on the decomposition.
Definition at line 871 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::haveFieldSplitPreconditioner(), and NonlinearSystemBase::useFieldSplitPreconditioner().
_use_finite_differenced_preconditioner
bool NonlinearSystemBase::_use_finite_differenced_preconditioner protected inherited
Whether or not to use a finite differenced preconditioner.
Definition at line 862 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::haveFiniteDifferencedPreconditioner(), NonlinearSystem::solve(), and NonlinearSystemBase::useFiniteDifferencedPreconditioner().
_var_all_dof_indices
std::vector<dof_id_type> SystemBase::_var_all_dof_indices protected inherited
Container for the dof indices of a given variable.
Definition at line 988 of file SystemBase.h.
Referenced by SystemBase::getVariableGlobalDoFs(), and SystemBase::setVariableGlobalDoFs().
_var_kind
Moose::VarKindType SystemBase::_var_kind protected inherited
default kind of variables in this system
Definition at line 962 of file SystemBase.h.
Referenced by SystemBase::varKind().
_var_map
std::map<unsigned int, std::set<SubdomainID> > SystemBase::_var_map protected inherited
Map of variables (variable id -> array of subdomains where it lives)
Definition at line 936 of file SystemBase.h.
Referenced by SystemBase::addVariable(), SystemBase::getSubdomainsForVar(), and SystemBase::getVariableBlocks().
_var_to_copy
std::vector<VarCopyInfo> SystemBase::_var_to_copy protected inherited
Definition at line 964 of file SystemBase.h.
Referenced by SystemBase::addVariableToCopy(), SystemBase::copyVars(), and SystemBase::hasVarCopy().
_var_to_group_var
std::unordered_map<unsigned int, unsigned int> NonlinearSystemBase::_var_to_group_var private inherited
A map from variable index to group variable index and it's associated (inverse) scaling factor.
Definition at line 977 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeScaling(), and NonlinearSystemBase::setupScalingData().
_variable_autoscaled
std::vector<bool> NonlinearSystemBase::_variable_autoscaled protected inherited
Container to hold flag if variable is to participate in autoscaling.
Definition at line 938 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeScaling(), and NonlinearSystemBase::setupScalingData().
_vars
std::vector<VariableWarehouse> SystemBase::_vars protected inherited
Variable warehouses (one for each thread)
Definition at line 934 of file SystemBase.h.
Referenced by NonlinearSystemBase::addBoundaryCondition(), NonlinearSystemBase::addInterfaceKernel(), AuxiliarySystem::addVariable(), SystemBase::addVariable(), SystemBase::applyScalingFactors(), NonlinearSystemBase::assembleScalingVector(), SystemBase::clearAllDofIndices(), AuxiliarySystem::compute(), SystemBase::customSetup(), SystemBase::getActualFieldVariable(), SystemBase::getFieldVariable(), SystemBase::getFVVariable(), SystemBase::getMinQuadratureOrder(), AuxiliarySystem::getMinQuadratureOrder(), SystemBase::getScalarVariable(), SystemBase::getScalarVariables(), SystemBase::getVariable(), SystemBase::getVariableNames(), SystemBase::getVariables(), SystemBase::initialSetup(), SystemBase::jacobianSetup(), SystemBase::nFieldVariables(), SystemBase::nFVVariables(), SystemBase::nVariables(), SystemBase::prepare(), SystemBase::prepareFace(), SystemBase::prepareLowerD(), SystemBase::prepareNeighbor(), SystemBase::reinitElem(), SystemBase::reinitElemFace(), SystemBase::reinitLowerD(), SystemBase::reinitNeighbor(), SystemBase::reinitNeighborFace(), SystemBase::reinitNode(), SystemBase::reinitNodeFace(), SystemBase::reinitNodes(), SystemBase::reinitNodesNeighbor(), SystemBase::reinitScalars(), SystemBase::residualSetup(), SystemBase::setActiveScalarVariableCoupleableVectorTags(), SystemBase::setActiveVariableCoupleableVectorTags(), NonlinearSystemBase::setupScalingData(), SystemBase::subdomainSetup(), and SystemBase::timestepSetup().
_vars_to_be_zeroed_on_jacobian
std::vector<std::string> SystemBase::_vars_to_be_zeroed_on_jacobian protected inherited
Definition at line 941 of file SystemBase.h.
Referenced by SystemBase::addVariableToZeroOnJacobian(), and SystemBase::zeroVariablesForJacobian().
_vars_to_be_zeroed_on_residual
std::vector<std::string> SystemBase::_vars_to_be_zeroed_on_residual protected inherited
Definition at line 940 of file SystemBase.h.
Referenced by SystemBase::addVariableToZeroOnResidual(), and SystemBase::zeroVariablesForResidual().
_vecs_to_zero_for_residual
std::vector<std::string> NonlinearSystemBase::_vecs_to_zero_for_residual protected inherited
vectors that will be zeroed before a residual computation
Definition at line 888 of file NonlinearSystemBase.h.
Referenced by NonlinearSystemBase::computeResidualTags(), and NonlinearSystemBase::zeroVectorForResidual().
_verbose
bool SystemBase::_verbose protected inherited
True if printing out additional information.
Definition at line 982 of file SystemBase.h.
Referenced by SystemBase::applyScalingFactors(), and SystemBase::setVerboseFlag().
_work_rhs_vector_AX
NumericVector<Number>& NonlinearEigenSystem::_work_rhs_vector_AX protected
Definition at line 182 of file NonlinearEigenSystem.h.
Referenced by residualVectorAX().
_work_rhs_vector_BX
NumericVector<Number>& NonlinearEigenSystem::_work_rhs_vector_BX protected
Definition at line 183 of file NonlinearEigenSystem.h.
Referenced by residualVectorBX(), and RHS().
The documentation for this class was generated from the following files:
moose/framework/include/systems/NonlinearEigenSystem.h
moose/framework/src/systems/NonlinearEigenSystem.C