Zapdos: ReporterTransferInterface Class Reference
ReporterTransferInterface Class Reference
#include <ReporterTransferInterface.h>
Public Member Functions
ReporterTransferInterface (const Transfer *transfer)
Static Public Member Functions
static InputParameters validParams ()
Protected Member Functions
void addReporterTransferMode (const ReporterName &name, const ReporterMode &mode, FEProblemBase &problem)
void transferReporter (const ReporterName &from_reporter, const ReporterName &to_reporter, const FEProblemBase &from_problem, FEProblemBase &to_problem, unsigned int time_index=0)
void transferToVectorReporter (const ReporterName &from_reporter, const ReporterName &to_reporter, const FEProblemBase &from_problem, FEProblemBase &to_problem, dof_id_type index, unsigned int time_index=0)
void declareClone (const ReporterName &from_reporter, const ReporterName &to_reporter, const FEProblemBase &from_problem, FEProblemBase &to_problem, const ReporterMode &mode)
void declareClone (const ReporterName &rname, FEProblemBase &problem, const std::string &type, const ReporterMode &mode)
void declareVectorClone (const ReporterName &from_reporter, const ReporterName &to_reporter, const FEProblemBase &from_problem, FEProblemBase &to_problem, const ReporterMode &mode)
void declareVectorClone (const ReporterName &rname, FEProblemBase &problem, const std::string &type, const ReporterMode &mode)
void resizeReporter (const ReporterName &name, FEProblemBase &problem, dof_id_type n)
std::vector< ReporterName > getReporterNamesHelper (std::string prefix, const std::string &obj_name, const std::vector< ReporterName > &rep_names)
void checkHasReporterValue (const ReporterName &reporter, const FEProblemBase &problem) const
Checks if the problem problem has a Reporter value with the name reporter.
Static Protected Member Functions
static MultiMooseEnum standardTransferTypes ()
Private Member Functions
void hideVariableHelper (const ReporterName &reporter, FEProblemBase &problem)
Helper for hiding the variables in the problem problem if the Reporter with name reporter is associated with a Reporter object (not a PP or VPP)
Private Attributes
const Transfer & _rti_transfer
The Transfer that this interface is associated with.
Detailed Description
Definition at line 27 of file ReporterTransferInterface.h.
Constructor & Destructor Documentation
ReporterTransferInterface()
ReporterTransferInterface::ReporterTransferInterface (const Transfer * transfer)
Definition at line 23 of file ReporterTransferInterface.C.
  : _rti_transfer(*transfer)
{
}
Member Function Documentation
addReporterTransferMode()
void ReporterTransferInterface::addReporterTransferMode (const ReporterName & name, const ReporterMode & mode, FEProblemBase & problem) protected
Definition at line 29 of file ReporterTransferInterface.C.
{
  checkHasReporterValue(name, problem);
  problem.getReporterData(ReporterData::WriteKey())
      .getReporterStateBase(name)
      .addConsumer(mode, _rti_transfer);
}
Referenced by MultiAppCloneReporterTransfer::initialSetup(), and MultiAppReporterTransfer::initialSetup().
checkHasReporterValue()
void ReporterTransferInterface::checkHasReporterValue (const ReporterName & reporter, const FEProblemBase & problem) const protected
Checks if the problem problem has a Reporter value with the name reporter.
Definition at line 189 of file ReporterTransferInterface.C.
{
  if (!problem.getReporterData().hasReporterValue(reporter))
    _rti_transfer.mooseError("Reporter with the name \"",
                             reporter,
                             "\" within app \"",
                             problem.getMooseApp().name(),
                             "\" was not found.");
}
Referenced by addReporterTransferMode(), declareClone(), declareVectorClone(), resizeReporter(), transferReporter(), and transferToVectorReporter().
declareClone() [1/2]
void ReporterTransferInterface::declareClone (const ReporterName & from_reporter, const ReporterName & to_reporter, const FEProblemBase & from_problem, FEProblemBase & to_problem, const ReporterMode & mode) protected
Definition at line 83 of file ReporterTransferInterface.C.
{
  checkHasReporterValue(from_reporter, from_problem);
  from_problem.getReporterData()
      .getReporterContextBase(from_reporter)
      .declareClone(
          to_problem.getReporterData(ReporterData::WriteKey()), to_reporter, mode, _rti_transfer);
  // Hide variables (if requested in parameters) if name is associated with a reporter object
  hideVariableHelper(to_reporter, to_problem);
}
Referenced by MultiAppCloneReporterTransfer::initialSetup().
declareClone() [2/2]
void ReporterTransferInterface::declareClone (const ReporterName & rname, FEProblemBase & problem, const std::string & type, const ReporterMode & mode) protected
Definition at line 100 of file ReporterTransferInterface.C.
{
  ReporterData & rdata = problem.getReporterData(ReporterData::WriteKey());
  if (type == "bool")
    rdata.declareReporterValue<bool, ReporterGeneralContext<bool>>(rname, mode, _rti_transfer);
  else if (type == "integer")
    rdata.declareReporterValue<int, ReporterGeneralContext<int>>(rname, mode, _rti_transfer);
  else if (type == "real")
    rdata.declareReporterValue<Real, ReporterGeneralContext<Real>>(rname, mode, _rti_transfer);
  else if (type == "string")
    rdata.declareReporterValue<std::string, ReporterGeneralContext<std::string>>(
        rname, mode, _rti_transfer);
  else
    _rti_transfer.mooseError("Unknown reporter type, ", type, ".");
  // Hide variables (if requested in parameters) if name is associated with a reporter object
  hideVariableHelper(rname, problem);
}
declareVectorClone() [1/2]
void ReporterTransferInterface::declareVectorClone (const ReporterName & from_reporter, const ReporterName & to_reporter, const FEProblemBase & from_problem, FEProblemBase & to_problem, const ReporterMode & mode) protected
Definition at line 123 of file ReporterTransferInterface.C.
{
  checkHasReporterValue(from_reporter, from_problem);
  from_problem.getReporterData()
      .getReporterContextBase(from_reporter)
      .declareVectorClone(
          to_problem.getReporterData(ReporterData::WriteKey()), to_reporter, mode, _rti_transfer);
  // Hide variables (if requested in parameters) if name is associated with a reporter object
  hideVariableHelper(to_reporter, to_problem);
}
Referenced by MultiAppCloneReporterTransfer::initialSetup().
declareVectorClone() [2/2]
void ReporterTransferInterface::declareVectorClone (const ReporterName & rname, FEProblemBase & problem, const std::string & type, const ReporterMode & mode) protected
Definition at line 140 of file ReporterTransferInterface.C.
{
  ReporterData & rdata = problem.getReporterData(ReporterData::WriteKey());
  if (type == "bool")
    rdata.declareReporterValue<std::vector<bool>, ReporterVectorContext<bool>>(
        rname, mode, _rti_transfer);
  else if (type == "integer")
    rdata.declareReporterValue<std::vector<int>, ReporterVectorContext<int>>(
        rname, mode, _rti_transfer);
  else if (type == "real")
    rdata.declareReporterValue<std::vector<Real>, ReporterVectorContext<Real>>(
        rname, mode, _rti_transfer);
  else if (type == "string")
    rdata.declareReporterValue<std::vector<std::string>, ReporterVectorContext<std::string>>(
        rname, mode, _rti_transfer);
  else
    _rti_transfer.mooseError("Unknown reporter type, ", type, ".");
  // Hide variables (if requested in parameters) if name is associated with a reporter object
  hideVariableHelper(rname, problem);
}
getReporterNamesHelper()
std::vector< ReporterName > ReporterTransferInterface::getReporterNamesHelper (std::string prefix, const std::string & obj_name, const std::vector< ReporterName > & rep_names) protected
Definition at line 175 of file ReporterTransferInterface.C.
{
  if (!prefix.empty())
    prefix += ":";
  std::vector<ReporterName> rnames;
  rnames.reserve(rep_names.size());
  for (const auto & rn : rep_names)
    rnames.emplace_back(obj_name, prefix + rn.getObjectName() + ":" + rn.getValueName());
  return rnames;
}
hideVariableHelper()
void ReporterTransferInterface::hideVariableHelper (const ReporterName & reporter, FEProblemBase & problem) private
Helper for hiding the variables in the problem problem if the Reporter with name reporter is associated with a Reporter object (not a PP or VPP)
Definition at line 70 of file ReporterTransferInterface.C.
{
  if (problem.hasUserObject(reporter.getObjectName()))
  {
    Reporter * rep =
        dynamic_cast<Reporter *>(&problem.getUserObject<UserObject>(reporter.getObjectName()));
    if (rep)
      rep->buildOutputHideVariableList({reporter.getCombinedName()});
  }
}
Referenced by declareClone(), and declareVectorClone().
resizeReporter()
void ReporterTransferInterface::resizeReporter (const ReporterName & name, FEProblemBase & problem, dof_id_type n) protected
Definition at line 166 of file ReporterTransferInterface.C.
{
  checkHasReporterValue(name, problem);
  problem.getReporterData(ReporterData::WriteKey()).getReporterContextBase(name).resize(n);
}
Referenced by MultiAppCloneReporterTransfer::initialSetup().
standardTransferTypes()
static MultiMooseEnum ReporterTransferInterface::standardTransferTypes () inline static protected
Definition at line 34 of file ReporterTransferInterface.h.
  {
    return MultiMooseEnum("bool=0 integer=1 real=2 string=3");
  }
Referenced by MultiAppCloneReporterTransfer::validParams().
transferReporter()
void ReporterTransferInterface::transferReporter (const ReporterName & from_reporter, const ReporterName & to_reporter, const FEProblemBase & from_problem, FEProblemBase & to_problem, unsigned int time_index = 0) protected
Definition at line 40 of file ReporterTransferInterface.C.
{
  checkHasReporterValue(from_reporter, from_problem);
  checkHasReporterValue(to_reporter, to_problem);
  from_problem.getReporterData()
      .getReporterContextBase(from_reporter)
      .transfer(to_problem.getReporterData(ReporterData::WriteKey()), to_reporter, time_index);
}
Referenced by MultiAppCloneReporterTransfer::executeFromMultiapp(), MultiAppReporterTransfer::executeFromMultiapp(), and MultiAppReporterTransfer::executeToMultiapp().
transferToVectorReporter()
void ReporterTransferInterface::transferToVectorReporter (const ReporterName & from_reporter, const ReporterName & to_reporter, const FEProblemBase & from_problem, FEProblemBase & to_problem, dof_id_type index, unsigned int time_index = 0) protected
Definition at line 54 of file ReporterTransferInterface.C.
{
  checkHasReporterValue(from_reporter, from_problem);
  checkHasReporterValue(to_reporter, to_problem);
  from_problem.getReporterData()
      .getReporterContextBase(from_reporter)
      .transferToVector(
          to_problem.getReporterData(ReporterData::WriteKey()), to_reporter, index, time_index);
}
Referenced by MultiAppCloneReporterTransfer::executeFromMultiapp().
validParams()
InputParameters ReporterTransferInterface::validParams () static
Definition at line 17 of file ReporterTransferInterface.C.
{
  InputParameters params = emptyInputParameters();
  return params;
}
Referenced by MultiAppCloneReporterTransfer::validParams(), and MultiAppReporterTransfer::validParams().
Member Data Documentation
_rti_transfer
const Transfer& ReporterTransferInterface::_rti_transfer private
The Transfer that this interface is associated with.
Definition at line 182 of file ReporterTransferInterface.h.
Referenced by addReporterTransferMode(), checkHasReporterValue(), declareClone(), and declareVectorClone().
The documentation for this class was generated from the following files:
moose/framework/include/transfers/ReporterTransferInterface.h
moose/framework/src/transfers/ReporterTransferInterface.C