Zapdos: VectorPostprocessor Class Reference
VectorPostprocessor Class Reference
Base class for Postprocessors that produce a vector of values.
#include <VectorPostprocessor.h>
Public Member Functions
VectorPostprocessor (const MooseObject *moose_object)
virtual ~VectorPostprocessor ()=default
std::string PPName () const
Returns the name of the VectorPostprocessor.
bool containsCompleteHistory () const
Return whether or not this VectorPostprocessor contains complete history.
bool isDistributed () const
Return true if the VPP is operating in distributed mode.
const std::set< std::string > & getVectorNames () const
Return the names of the vectors associated with this object.
void buildOutputHideVariableList (std::set< std::string > variable_names)
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
const std::set< OutputName > & getOutputs ()
Get the list of output objects that this class is restricted.
Static Public Member Functions
static InputParameters validParams ()
Protected Member Functions
VectorPostprocessorValue & declareVector (const std::string &vector_name)
Register a new vector to fill up.
Protected Attributes
const std::string _vpp_name
The name of the VectorPostprocessor.
FEProblemBase & _vpp_fe_problem
The FEProblemBase.
const MooseEnum & _parallel_type
DISTRIBUTED or REPLICATED.
Private Attributes
const MooseObject & _vpp_moose_object
const THREAD_ID _vpp_tid
const bool _contains_complete_history
const bool _is_distributed
const bool _is_broadcast
std::map< std::string, VectorPostprocessorValue > _thread_local_vectors
std::set< std::string > _vector_names
MooseApp & _oi_moose_app
Reference the the MooseApp; neede for access to the OutputWarehouse.
OutputWarehouse & _oi_output_warehouse
Reference to the OutputWarehouse for populating the Output object hide lists.
std::set< OutputName > _oi_outputs
The set of Output object names listed in the 'outputs' parameter.
Friends
class SamplerBase
Detailed Description
Base class for Postprocessors that produce a vector of values.
Definition at line 33 of file VectorPostprocessor.h.
Constructor & Destructor Documentation
VectorPostprocessor()
VectorPostprocessor::VectorPostprocessor (const MooseObject * moose_object)
Definition at line 51 of file VectorPostprocessor.C.
  : OutputInterface(moose_object->parameters()),
    _vpp_name(MooseUtils::shortName(moose_object->parameters().get<std::string>("_object_name"))),
    _vpp_fe_problem(
        *moose_object->parameters().getCheckedPointerParam<FEProblemBase *>("_fe_problem_base")),
    _parallel_type(moose_object->parameters().get<MooseEnum>("parallel_type")),
    _vpp_moose_object(*moose_object),
    _vpp_tid(moose_object->parameters().isParamValid("_tid")
                 ? moose_object->parameters().get<THREAD_ID>("_tid")
                 : 0),
    _contains_complete_history(moose_object->parameters().get<bool>("contains_complete_history")),
    _is_distributed(_parallel_type == "DISTRIBUTED"),
    _is_broadcast(_is_distributed || !moose_object->parameters().get<bool>("_auto_broadcast"))
{
}
~VectorPostprocessor()
virtual VectorPostprocessor::~VectorPostprocessor () virtual default
Member Function Documentation
buildOutputHideVariableList()
void OutputInterface::buildOutputHideVariableList (std::set< std::string > variable_names) inherited
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
Parameters
variable_names A set of variables for which the 'outputs' parameter controls
By default this is called by the constructor and passes the block name as the list of variables. This needs to be called explicitly if the build_list flag is set to False in the constructor. The latter cases is needed by the Material object to work correctly with the automatic material output capability.
Definition at line 61 of file OutputInterface.C.
{
  // Set of available names
  const std::set<OutputName> & avail = _oi_output_warehouse.getOutputNames();
  // Check for 'none'; hide variables on all outputs
  if (_oi_outputs.find("none") != _oi_outputs.end())
    for (const auto & name : avail)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  // Check for empty and 'all' in 'outputs' parameter; do not perform any variable restrictions in
  // these cases
  else if (_oi_outputs.empty() || _oi_outputs.find("all") != _oi_outputs.end())
    return;
  // Limit the variable output to Output objects listed
  else
  {
    // Create a list of outputs where the variable should be hidden
    std::set<OutputName> hide;
    std::set_difference(avail.begin(),
                        avail.end(),
                        _oi_outputs.begin(),
                        _oi_outputs.end(),
                        std::inserter(hide, hide.begin()));
    // If 'outputs' is specified add the object name to the list of items to hide
    for (const auto & name : hide)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  }
}
Referenced by ReporterTransferInterface::hideVariableHelper(), and OutputInterface::OutputInterface().
containsCompleteHistory()
bool VectorPostprocessor::containsCompleteHistory () const inline
Return whether or not this VectorPostprocessor contains complete history.
Definition at line 50 of file VectorPostprocessor.h.
{ return _contains_complete_history; }
Referenced by SamplerBase::initialize(), MaterialVectorPostprocessor::initialize(), and CSV::output().
declareVector()
VectorPostprocessorValue & VectorPostprocessor::declareVector (const std::string & vector_name) protected
Register a new vector to fill up.
Definition at line 68 of file VectorPostprocessor.C.
{
  _vector_names.insert(vector_name);
  if (_vpp_tid)
    return _thread_local_vectors.emplace(vector_name, VectorPostprocessorValue()).first->second;
  // _is_broadcast = true (_auto_broadcast = false) then data is produced in a replicated manner
  ReporterMode mode = REPORTER_MODE_ROOT;
  if (_is_broadcast)
    mode = REPORTER_MODE_REPLICATED;
  if (_is_distributed)
    mode = REPORTER_MODE_DISTRIBUTED;
  return _vpp_fe_problem.getReporterData(ReporterData::WriteKey())
      .declareReporterValue<VectorPostprocessorValue,
                            VectorPostprocessorContext<VectorPostprocessorValue>>(
          VectorPostprocessorReporterName(_vpp_name, vector_name), mode, _vpp_moose_object);
}
Referenced by ConstantVectorPostprocessor::ConstantVectorPostprocessor(), CSVReader::CSVReader(), ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), HistogramVectorPostprocessor::initialSetup(), LeastSquaresFit::LeastSquaresFit(), LeastSquaresFitHistory::LeastSquaresFitHistory(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MeshDivisionFunctorReductionVectorPostprocessor::MeshDivisionFunctorReductionVectorPostprocessor(), SamplerBase::setupVariables(), SidesetInfoVectorPostprocessor::SidesetInfoVectorPostprocessor(), SpatialAverageBase::SpatialAverageBase(), and WorkBalance::WorkBalance().
getOutputs()
const std::set< OutputName > & OutputInterface::getOutputs () inherited
Get the list of output objects that this class is restricted.
Returns
A set of OutputNames
Definition at line 94 of file OutputInterface.C.
{
  return _oi_outputs;
}
getVectorNames()
const std::set< std::string > & VectorPostprocessor::getVectorNames () const
Return the names of the vectors associated with this object.
Definition at line 89 of file VectorPostprocessor.C.
{
  return _vector_names;
}
Referenced by HistogramVectorPostprocessor::execute(), and HistogramVectorPostprocessor::initialSetup().
isDistributed()
bool VectorPostprocessor::isDistributed () const inline
Return true if the VPP is operating in distributed mode.
Definition at line 55 of file VectorPostprocessor.h.
{ return _is_distributed; }
Referenced by VectorPostprocessorInterface::isVectorPostprocessorDistributedByName(), and XMLOutput::outputVectorPostprocessors().
PPName()
std::string VectorPostprocessor::PPName () const inline
Returns the name of the VectorPostprocessor.
Definition at line 45 of file VectorPostprocessor.h.
{ return _vpp_name; }
validParams()
InputParameters VectorPostprocessor::validParams () static
Definition at line 18 of file VectorPostprocessor.C.
{
  InputParameters params = UserObject::validParams();
  params += OutputInterface::validParams();
  params.addParam<bool>("contains_complete_history",
                        false,
                        "Set this flag to indicate that the values in all vectors declared by this "
                        "VPP represent a time history (e.g. with each invocation, new values are "
                        "added and old values are never removed). This changes the output so that "
                        "only a single file is output and updated with each invocation");
  // VPPs can set this to true if their resulting vectors are naturally replicated in parallel
  // setting this to false will keep MOOSE from unnecessarily broadcasting those vectors
  params.addPrivateParam<bool>("_auto_broadcast", true);
  // VPPs can operate in "distributed" mode, which disables the automatic broadcasting
  // and results in an individual file per processor if CSV output is enabled
  MooseEnum parallel_type("DISTRIBUTED REPLICATED", "REPLICATED");
  params.addParam<MooseEnum>(
      "parallel_type",
      parallel_type,
      "Set how the data is represented within the VectorPostprocessor (VPP); 'distributed' "
      "indicates that data within the VPP is distributed and no auto communication is performed, "
      "this setting will result in parallel output within the CSV output; 'replicated' indicates "
      "that the data within the VPP is correct on processor 0, the data will automatically be "
      "broadcast to all processors unless the '_auto_broadcast' param is set to false within the "
      "validParams function.");
  params.addParamNamesToGroup("outputs", "Advanced");
  params.registerBase("VectorPostprocessor");
  return params;
}
Referenced by ElementVectorPostprocessor::validParams(), GeneralVectorPostprocessor::validParams(), InterfaceVectorPostprocessor::validParams(), InternalSideVectorPostprocessor::validParams(), NodalVectorPostprocessor::validParams(), and SideVectorPostprocessor::validParams().
Friends And Related Function Documentation
SamplerBase
friend class SamplerBase friend
Definition at line 77 of file VectorPostprocessor.h.
Member Data Documentation
_contains_complete_history
const bool VectorPostprocessor::_contains_complete_history private
Definition at line 84 of file VectorPostprocessor.h.
Referenced by containsCompleteHistory().
_is_broadcast
const bool VectorPostprocessor::_is_broadcast private
Definition at line 88 of file VectorPostprocessor.h.
Referenced by declareVector().
_is_distributed
const bool VectorPostprocessor::_is_distributed private
Definition at line 86 of file VectorPostprocessor.h.
Referenced by declareVector(), and isDistributed().
_oi_moose_app
MooseApp& OutputInterface::_oi_moose_app private inherited
Reference the the MooseApp; neede for access to the OutputWarehouse.
Definition at line 66 of file OutputInterface.h.
_oi_output_warehouse
OutputWarehouse& OutputInterface::_oi_output_warehouse private inherited
Reference to the OutputWarehouse for populating the Output object hide lists.
Definition at line 69 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList().
_oi_outputs
std::set<OutputName> OutputInterface::_oi_outputs private inherited
The set of Output object names listed in the 'outputs' parameter.
Definition at line 72 of file OutputInterface.h.
Referenced by OutputInterface::buildOutputHideVariableList(), and OutputInterface::getOutputs().
_parallel_type
const MooseEnum& VectorPostprocessor::_parallel_type protected
DISTRIBUTED or REPLICATED.
Definition at line 75 of file VectorPostprocessor.h.
_thread_local_vectors
std::map<std::string, VectorPostprocessorValue> VectorPostprocessor::_thread_local_vectors private
Definition at line 90 of file VectorPostprocessor.h.
Referenced by declareVector().
_vector_names
std::set<std::string> VectorPostprocessor::_vector_names private
Definition at line 92 of file VectorPostprocessor.h.
Referenced by declareVector(), and getVectorNames().
_vpp_fe_problem
FEProblemBase& VectorPostprocessor::_vpp_fe_problem protected
The FEProblemBase.
Definition at line 72 of file VectorPostprocessor.h.
Referenced by declareVector().
_vpp_moose_object
const MooseObject& VectorPostprocessor::_vpp_moose_object private
Definition at line 80 of file VectorPostprocessor.h.
Referenced by declareVector().
_vpp_name
const std::string VectorPostprocessor::_vpp_name protected
The name of the VectorPostprocessor.
Definition at line 69 of file VectorPostprocessor.h.
Referenced by declareVector(), and PPName().
_vpp_tid
const THREAD_ID VectorPostprocessor::_vpp_tid private
Definition at line 82 of file VectorPostprocessor.h.
Referenced by declareVector().
The documentation for this class was generated from the following files:
moose/framework/include/vectorpostprocessors/VectorPostprocessor.h
moose/framework/src/vectorpostprocessors/VectorPostprocessor.C