Zapdos: PerfGraphInterface Class Reference
PerfGraphInterface Class Reference
Interface for objects interacting with the PerfGraph.
#include <PerfGraphInterface.h>
Public Member Functions
PerfGraphInterface (const MooseObject *moose_object)
For objects that are MooseObjects with a default prefix of type()
PerfGraphInterface (const MooseObject *moose_object, const std::string prefix)
For objects that are MooseObjects.
PerfGraphInterface (PerfGraph &perf_graph, const std::string prefix="")
For objects that aren't MooseObjects.
PerfGraphInterface (MooseApp &moose_app, const std::string prefix="")
For objects that construct the PerfGraphInterface before the PerfGraph is initialized (see MooseApp and OutputWarehouse)
virtual ~PerfGraphInterface ()=default
PerfGraph & perfGraph ()
Get the PerfGraph.
Static Public Member Functions
static InputParameters validParams ()
Protected Member Functions
PerfID registerTimedSection (const std::string &section_name, const unsigned int level) const
Call to register a named section for timing.
PerfID registerTimedSection (const std::string &section_name, const unsigned int level, const std::string &live_message, const bool print_dots=true) const
Call to register a named section for timing.
std::string timedSectionName (const std::string &section_name) const
Protected Attributes
MooseApp & _pg_moose_app
The MooseApp that owns the PerfGraph.
const std::string _prefix
A prefix to use for all sections.
Detailed Description
Interface for objects interacting with the PerfGraph.
Enables getting PerfGraph information and registering PerfGraph timed sections.
Definition at line 59 of file PerfGraphInterface.h.
Constructor & Destructor Documentation
PerfGraphInterface() [1/4]
PerfGraphInterface::PerfGraphInterface (const MooseObject * moose_object)
For objects that are MooseObjects with a default prefix of type()
Definition at line 22 of file PerfGraphInterface.C.
  : _pg_moose_app(*moose_object->parameters().getCheckedPointerParam<MooseApp *>(
        "_moose_app", "PerfGraphInterface is unable to retrieve the MooseApp pointer!")),
    _prefix(moose_object->type())
{
}
PerfGraphInterface() [2/4]
PerfGraphInterface::PerfGraphInterface (const MooseObject * moose_object, const std::string prefix)
For objects that are MooseObjects.
Definition at line 29 of file PerfGraphInterface.C.
  : _pg_moose_app(*moose_object->parameters().getCheckedPointerParam<MooseApp *>(
        "_moose_app", "PerfGraphInterface is unable to retrieve the MooseApp pointer!")),
    _prefix(prefix)
{
}
PerfGraphInterface() [3/4]
PerfGraphInterface::PerfGraphInterface (PerfGraph & perf_graph, const std::string prefix = "")
For objects that aren't MooseObjects.
Definition at line 41 of file PerfGraphInterface.C.
  : _pg_moose_app(perf_graph.mooseApp()), _prefix(prefix)
{
}
PerfGraphInterface() [4/4]
PerfGraphInterface::PerfGraphInterface (MooseApp & moose_app, const std::string prefix = "")
For objects that construct the PerfGraphInterface before the PerfGraph is initialized (see MooseApp and OutputWarehouse)
Definition at line 36 of file PerfGraphInterface.C.
  : _pg_moose_app(moose_app), _prefix(prefix)
{
}
~PerfGraphInterface()
virtual PerfGraphInterface::~PerfGraphInterface () virtual default
Member Function Documentation
perfGraph()
PerfGraph & PerfGraphInterface::perfGraph ()
Get the PerfGraph.
Definition at line 78 of file PerfGraphInterface.C.
{
  return _pg_moose_app.perfGraph();
}
Referenced by CommonOutputAction::act(), PerfGraphData::finalize(), and PerfGraphOutput::output().
registerTimedSection() [1/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level) const protected
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
Returns
The ID of the section - use when starting timing
Definition at line 53 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(timed_section_name, level);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
registerTimedSection() [2/2]
PerfID PerfGraphInterface::registerTimedSection (const std::string & section_name, const unsigned int level, const std::string & live_message, const bool print_dots = true) const protected
Call to register a named section for timing.
Parameters
section_name The name of the code section to be timed
level The importance of the timer - lower is more important (0 will always come out)
live_message The message to be printed to the screen during execution
print_dots Whether or not progress dots should be printed for this section
Returns
The ID of the section - use when starting timing
Definition at line 64 of file PerfGraphInterface.C.
{
  const auto timed_section_name = timedSectionName(section_name);
  if (!moose::internal::getPerfGraphRegistry().sectionExists(timed_section_name))
    return moose::internal::getPerfGraphRegistry().registerSection(
        timedSectionName(section_name), level, live_message, print_dots);
  else
    return moose::internal::getPerfGraphRegistry().sectionID(timed_section_name);
}
timedSectionName()
std::string PerfGraphInterface::timedSectionName (const std::string & section_name) const protected
Returns
The name of the timed section with the name section_name.
Optionally adds a prefix if one is defined.
Definition at line 47 of file PerfGraphInterface.C.
{
  return _prefix.empty() ? "" : (_prefix + "::") + section_name;
}
Referenced by registerTimedSection().
validParams()
InputParameters PerfGraphInterface::validParams () static
Definition at line 16 of file PerfGraphInterface.C.
{
  InputParameters params = emptyInputParameters();
  return params;
}
Member Data Documentation
_pg_moose_app
MooseApp& PerfGraphInterface::_pg_moose_app protected
The MooseApp that owns the PerfGraph.
Definition at line 124 of file PerfGraphInterface.h.
Referenced by perfGraph().
_prefix
const std::string PerfGraphInterface::_prefix protected
A prefix to use for all sections.
Definition at line 127 of file PerfGraphInterface.h.
Referenced by timedSectionName().
The documentation for this class was generated from the following files:
moose/framework/include/interfaces/PerfGraphInterface.h
moose/framework/src/interfaces/PerfGraphInterface.C