Zapdos: PerfNode Class Reference
PerfNode Class Reference
A node in the PerfGraph.
#include <PerfNode.h>
Public Member Functions
PerfNode (const PerfID id)
Create a PerfNode with the given ID.
PerfID id () const
Get the ID of this Node.
void setStartTimeAndMemory (const std::chrono::time_point< std::chrono::steady_clock > time, const long int memory)
Set the current start time.
const std::chrono::time_point< std::chrono::steady_clock > & startTime () const
Get the currnet start time Only makes sense if this node is running.
const long unsigned int & startMemory () const
Get the current start memory Only makes sense if this node is running.
void addTimeAndMemory (const std::chrono::time_point< std::chrono::steady_clock > time, const long int memory)
Add some time into this Node by taking the difference with the time passed in.
void incrementNumCalls ()
Increments the number of calls.
void addTimeAndMemory (const std::chrono::steady_clock::duration time)
Add some time into this Node.
PerfNode * getChild (const PerfID id)
Get a child node with the unique id given.
const std::map< PerfID, std::unique_ptr< PerfNode > > & children () const
Get the children.
std::chrono::steady_clock::duration selfTime () const
Get the time this node took.
Real selfTimeSec () const
Get the time this node took in seconds.
Real selfTimeAvg () const
The average time this node took in seconds.
std::chrono::steady_clock::duration totalTime () const
The time this Node plus all of it's children took.
Real totalTimeSec () const
The time this Node plus all of its children took in seconds.
Real totalTimeAvg () const
The average time this Node plus all of its children took in seconds.
std::chrono::steady_clock::duration childrenTime () const
Get the time this nodes children took.
Real childrenTimeSec () const
The time this node's children took in seconds.
unsigned long int numCalls () const
Get the number of times this node was called.
long int selfMemory () const
Get the amount of memory added by this node.
long int childrenMemory () const
Get the amount of memory added by this node.
long int totalMemory () const
Get the amount of memory added by this node.
Private Attributes
const PerfID _id
The unique ID for the section this Node corresponds to.
std::chrono::time_point< std::chrono::steady_clock > _start_time
The current start_time for this node (if it's on the stack)
std::chrono::steady_clock::duration _total_time
The total elapsed time for this node.
long unsigned int _start_memory
The starting memory for this node.
long unsigned int _num_calls
Number of times this node has been called.
long unsigned int _total_memory
The total memory added while this node is active.
std::map< PerfID, std::unique_ptr< PerfNode > > _children
Timers that are directly underneath this node.
Friends
void dataStore (std::ostream &, const std::unique_ptr< PerfNode > &, void *)
void dataLoad (std::istream &, const std::unique_ptr< PerfNode > &, void *)
Detailed Description
A node in the PerfGraph.
Stores the timing for a particular section of code.
The design here is that _children are automatically added and kept track of within the Node - and only raw pointers are handed back out.
Definition at line 24 of file PerfNode.h.
Constructor & Destructor Documentation
PerfNode()
PerfNode::PerfNode (const PerfID id) inline
Create a PerfNode with the given ID.
Definition at line 30 of file PerfNode.h.
: _id(id), _total_time(0), _num_calls(0), _total_memory(0) {}
Member Function Documentation
addTimeAndMemory() [1/2]
void PerfNode::addTimeAndMemory (const std::chrono::steady_clock::duration time) inline
Add some time into this Node.
Definition at line 80 of file PerfNode.h.
{ _total_time += time; }
addTimeAndMemory() [2/2]
void PerfNode::addTimeAndMemory (const std::chrono::time_point< std::chrono::steady_clock > time, const long int memory) inline
Add some time into this Node by taking the difference with the time passed in.
Definition at line 65 of file PerfNode.h.
  {
    _total_time += time - _start_time;
    _total_memory += memory - _start_memory;
  }
children()
const std::map< PerfID, std::unique_ptr< PerfNode > > & PerfNode::children () const inline
Get the children.
Definition at line 106 of file PerfNode.h.
{ return _children; }
Referenced by PerfGraph::recursivelyUpdate(), to_json(), and PerfGraph::treeRecurseInternal().
childrenMemory()
long int PerfNode::childrenMemory () const
Get the amount of memory added by this node.
Definition at line 47 of file PerfNode.C.
{
  long int children_memory = 0;
  for (auto & child_it : _children)
    children_memory += child_it.second->totalMemory();
  return children_memory;
}
Referenced by PerfGraph::recursivelyUpdate(), and selfMemory().
childrenTime()
std::chrono::steady_clock::duration PerfNode::childrenTime () const
Get the time this nodes children took.
Definition at line 30 of file PerfNode.C.
{
  std::chrono::steady_clock::duration children_time(0);
  for (auto & child_it : _children)
    children_time += child_it.second->totalTime();
  return children_time;
}
Referenced by childrenTimeSec(), and selfTime().
childrenTimeSec()
Real PerfNode::childrenTimeSec () const inline
The time this node's children took in seconds.
Definition at line 141 of file PerfNode.h.
{ return std::chrono::duration<Real>(childrenTime()).count(); }
Referenced by PerfGraph::recursivelyUpdate().
getChild()
PerfNode * PerfNode::getChild (const PerfID id) inline
Get a child node with the unique id given.
Note: this will automatically create the Node internally if it needs to.
Implemented in header to allow for more optimization
Parameters
id The unique ID of the child node
Returns
The pointer to the child node
Definition at line 92 of file PerfNode.h.
  {
    // RHS insertion on purpose
    auto & child_node = _children[id];
    if (!child_node)
      child_node = std::make_unique<PerfNode>(id);
    return child_node.get();
  }
id()
PerfID PerfNode::id () const inline
Get the ID of this Node.
Definition at line 35 of file PerfNode.h.
{ return _id; }
Referenced by getChild(), PerfGraph::recursivelyUpdate(), to_json(), and PerfGraph::treeRecurseInternal().
incrementNumCalls()
void PerfNode::incrementNumCalls () inline
Increments the number of calls.
Definition at line 75 of file PerfNode.h.
{ _num_calls++; }
Referenced by PerfGraph::push().
numCalls()
unsigned long int PerfNode::numCalls () const inline
Get the number of times this node was called.
Definition at line 146 of file PerfNode.h.
{ return _num_calls; }
Referenced by PerfGraph::recursivelyUpdate(), selfTimeAvg(), to_json(), totalTimeAvg(), and PerfGraph::treeTable().
selfMemory()
long int PerfNode::selfMemory () const
Get the amount of memory added by this node.
Definition at line 41 of file PerfNode.C.
{
  return _total_memory - childrenMemory();
}
Referenced by PerfGraph::recursivelyUpdate(), to_json(), and PerfGraph::treeTable().
selfTime()
std::chrono::steady_clock::duration PerfNode::selfTime () const
Get the time this node took.
Definition at line 16 of file PerfNode.C.
{
  return _total_time - childrenTime();
}
Referenced by selfTimeSec().
selfTimeAvg()
Real PerfNode::selfTimeAvg () const inline
The average time this node took in seconds.
Definition at line 119 of file PerfNode.h.
{ return selfTimeSec() / static_cast<Real>(numCalls()); }
Referenced by PerfGraph::treeTable().
selfTimeSec()
Real PerfNode::selfTimeSec () const inline
Get the time this node took in seconds.
Definition at line 115 of file PerfNode.h.
{ return std::chrono::duration<Real>(selfTime()).count(); }
Referenced by PerfGraph::recursivelyUpdate(), selfTimeAvg(), to_json(), and PerfGraph::treeTable().
setStartTimeAndMemory()
void PerfNode::setStartTimeAndMemory (const std::chrono::time_point< std::chrono::steady_clock > time, const long int memory) inline
Set the current start time.
Definition at line 40 of file PerfNode.h.
  {
    _start_time = time;
    _start_memory = memory;
  }
Referenced by PerfGraph::push().
startMemory()
const long unsigned int & PerfNode::startMemory () const inline
Get the current start memory Only makes sense if this node is running.
Definition at line 60 of file PerfNode.h.
{ return _start_memory; }
startTime()
const std::chrono::time_point< std::chrono::steady_clock > & PerfNode::startTime () const inline
Get the currnet start time Only makes sense if this node is running.
Definition at line 51 of file PerfNode.h.
  {
    return _start_time;
  }
totalMemory()
long int PerfNode::totalMemory () const inline
Get the amount of memory added by this node.
Definition at line 161 of file PerfNode.h.
{ return _total_memory; }
Referenced by PerfGraph::recursivelyUpdate(), and PerfGraph::treeTable().
totalTime()
std::chrono::steady_clock::duration PerfNode::totalTime () const
The time this Node plus all of it's children took.
Definition at line 22 of file PerfNode.C.
{
  // Note that all of the children's time is already
  // accounted for in the total time
  return _total_time;
}
Referenced by totalTimeSec(), and PerfGraph::treeRecurseInternal().
totalTimeAvg()
Real PerfNode::totalTimeAvg () const inline
The average time this Node plus all of its children took in seconds.
Definition at line 132 of file PerfNode.h.
{ return totalTimeSec() / static_cast<Real>(numCalls()); }
Referenced by PerfGraph::treeTable().
totalTimeSec()
Real PerfNode::totalTimeSec () const inline
The time this Node plus all of its children took in seconds.
Definition at line 128 of file PerfNode.h.
{ return std::chrono::duration<Real>(totalTime()).count(); }
Referenced by PerfGraph::recursivelyUpdate(), totalTimeAvg(), and PerfGraph::treeTable().
Friends And Related Function Documentation
dataLoad
void dataLoad (std::istream & , const std::unique_ptr< PerfNode > & , void *) friend
Definition at line 79 of file PerfNode.C.
{
  std::string name;
  // When we recursively add children, we grab the name before recursing into
  // dataLoad(), so only load the name if we're on the root
  if (node.get() == &static_cast<PerfGraph *>(perf_graph)->rootNode())
    dataLoad(stream, name, nullptr);
  std::chrono::steady_clock::duration total_time;
  dataLoad(stream, total_time, nullptr);
  node->_total_time += total_time;
  long unsigned int num_calls;
  dataLoad(stream, num_calls, nullptr);
  node->_num_calls += num_calls;
  long unsigned int total_memory;
  dataLoad(stream, total_memory, nullptr);
  node->_total_memory += total_memory;
  // Recursively add the children
  // If a matching child exists with the same name, the time/calls/memory will be appended
  // to said node. If a node does not exist with the same name, it will be created
  std::size_t num_children;
  dataLoad(stream, num_children, nullptr);
  std::size_t i = 0;
  while (i++ < num_children)
  {
    dataLoad(stream, name, nullptr);
    const auto id = moose::internal::getPerfGraphRegistry().sectionID(name);
    node->getChild(id); // creates the child if it does not exist
    const auto & child = node->_children[id];
    dataLoad(stream, child, perf_graph);
  }
}
dataStore
void dataStore (std::ostream & , const std::unique_ptr< PerfNode > & , void *) friend
Definition at line 58 of file PerfNode.C.
{
  // We store the name instead of the ID because the ID could change in recover
  std::string name = moose::internal::getPerfGraphRegistry().sectionInfo(node->id())._name;
  dataStore(stream, name, nullptr);
  dataStore(stream, node->_total_time, nullptr);
  dataStore(stream, node->_num_calls, nullptr);
  dataStore(stream, node->_total_memory, nullptr);
  // Recursively add all of the children
  std::size_t num_children = node->children().size();
  dataStore(stream, num_children, nullptr);
  for (auto & id_child_pair : node->_children)
  {
    const auto & child = id_child_pair.second;
    dataStore(stream, child, nullptr);
  }
}
Member Data Documentation
_children
std::map<PerfID, std::unique_ptr<PerfNode> > PerfNode::_children private
Timers that are directly underneath this node.
Definition at line 183 of file PerfNode.h.
Referenced by children(), childrenMemory(), childrenTime(), and getChild().
_id
const PerfID PerfNode::_id private
The unique ID for the section this Node corresponds to.
Definition at line 165 of file PerfNode.h.
Referenced by id().
_num_calls
long unsigned int PerfNode::_num_calls private
Number of times this node has been called.
Definition at line 177 of file PerfNode.h.
Referenced by incrementNumCalls(), and numCalls().
_start_memory
long unsigned int PerfNode::_start_memory private
The starting memory for this node.
Definition at line 174 of file PerfNode.h.
Referenced by addTimeAndMemory(), setStartTimeAndMemory(), and startMemory().
_start_time
std::chrono::time_point<std::chrono::steady_clock> PerfNode::_start_time private
The current start_time for this node (if it's on the stack)
Definition at line 168 of file PerfNode.h.
Referenced by addTimeAndMemory(), setStartTimeAndMemory(), and startTime().
_total_memory
long unsigned int PerfNode::_total_memory private
The total memory added while this node is active.
Definition at line 180 of file PerfNode.h.
Referenced by addTimeAndMemory(), selfMemory(), and totalMemory().
_total_time
std::chrono::steady_clock::duration PerfNode::_total_time private
The total elapsed time for this node.
Definition at line 171 of file PerfNode.h.
Referenced by addTimeAndMemory(), selfTime(), and totalTime().
The documentation for this class was generated from the following files:
moose/framework/include/utils/PerfNode.h
moose/framework/src/utils/PerfNode.C