Zapdos: BicubicSplineInterpolation Class Reference
BicubicSplineInterpolation Class Reference
This class interpolates tabulated functions with a bi-cubic spline.
#include <BicubicSplineInterpolation.h>
Public Member Functions
BicubicSplineInterpolation ()
BicubicSplineInterpolation (const std::vector< Real > &x1, const std::vector< Real > &x2, const std::vector< std::vector< Real > > &y, const std::vector< Real > &yx11=std::vector< Real >(), const std::vector< Real > &yx1n=std::vector< Real >(), const std::vector< Real > &yx21=std::vector< Real >(), const std::vector< Real > &yx2n=std::vector< Real >())
In the future, may add interface that allows necessary vector of boundary conditions to be supplied for each edge of grid; however, for now we just use natural splines at the grid boundaries.
virtual ~BicubicSplineInterpolation ()=default
void setData (const std::vector< Real > &x1, const std::vector< Real > &x2, const std::vector< std::vector< Real > > &y, const std::vector< Real > &yx11=std::vector< Real >(), const std::vector< Real > &yx1n=std::vector< Real >(), const std::vector< Real > &yx21=std::vector< Real >(), const std::vector< Real > &yx2n=std::vector< Real >())
Set the x1, x2 and y values, and first derivatives at the edges.
void errorCheck ()
Sanity checks on input data.
Real sample (Real x1, Real x2, Real yx11=_deriv_bound, Real yx1n=_deriv_bound)
Samples value at point (x1, x2)
void sampleValueAndDerivatives (Real x1, Real x2, Real &y, Real &dy1, Real &dy2, Real yx11=_deriv_bound, Real yx1n=_deriv_bound, Real yx21=_deriv_bound, Real yx2n=_deriv_bound)
Samples value and first derivatives at point (x1, x2) Use this function for speed when computing both value and derivatives, as it minimizes the amount of spline evaluation.
Real sampleDerivative (Real x1, Real x2, unsigned int deriv_var, Real yp1=_deriv_bound, Real ypn=_deriv_bound)
Samples first derivative at point (x1, x2)
Real sample2ndDerivative (Real x1, Real x2, unsigned int deriv_var, Real yp1=_deriv_bound, Real ypn=_deriv_bound)
Samples second derivative at point (x1, x2)
Real sample (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, Real x_int) const
ADReal sample (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, const ADReal &x_int) const
Real sampleDerivative (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, Real x_int) const
Real sample2ndDerivative (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, Real x_int) const
Protected Member Functions
void constructRowSplineSecondDerivativeTable ()
Precompute tables of row (column) spline second derivatives and store them to reduce computational demands.
void constructColumnSplineSecondDerivativeTable ()
void solve ()
Calculates the tables of second derivatives.
void constructRowSpline (Real x1, std::vector< Real > &spline_eval, std::vector< Real > &spline_second_derivs, Real yx11=_deriv_bound, Real yx1n=_deriv_bound)
Helper functions to evaluate column splines and construct row spline for the given point.
void constructColumnSpline (Real x2, std::vector< Real > &spline_eval, std::vector< Real > &spline_second_derivs, Real yx21=_deriv_bound, Real yx2n=_deriv_bound)
Helper functions to evaluate row splines and construct column spline for the given point.
template<typename T >
T sample (const std::vector< Real > &x, const std::vector< Real > &y, const std::vector< Real > &y2, const T &x_int, unsigned int klo, unsigned int khi) const
Sample value at point x_int given the indices of the vector of dependent values that bound the point.
void spline (const std::vector< Real > &x, const std::vector< Real > &y, std::vector< Real > &y2, Real yp1=_deriv_bound, Real ypn=_deriv_bound)
This function calculates the second derivatives based on supplied x and y-vectors.
void findInterval (const std::vector< Real > &x, Real x_int, unsigned int &klo, unsigned int &khi) const
template<typename T >
void computeCoeffs (const std::vector< Real > &x, unsigned int klo, unsigned int khi, const T &x_int, Real &h, T &a, T &b) const
Protected Attributes
std::vector< Real > _x1
Independent values in the x1 direction.
std::vector< Real > _x2
Independent values in the x2 direction.
std::vector< std::vector< Real > > _y
The dependent values at (x1, x2) points.
std::vector< std::vector< Real > > _y_trans
Transpose of _y.
std::vector< Real > _yx11
Boundary conditions.
std::vector< Real > _yx1n
std::vector< Real > _yx21
std::vector< Real > _yx2n
std::vector< std::vector< Real > > _y2_rows
Second derivatives.
std::vector< std::vector< Real > > _y2_columns
std::vector< Real > _row_spline_second_derivs
Vectors used during sampling.
std::vector< Real > _row_spline_eval
std::vector< Real > _column_spline_second_derivs
std::vector< Real > _column_spline_eval
Static Protected Attributes
static int _file_number = 0
File number for data dump.
static const Real _deriv_bound = std::numeric_limits<Real>::max()
Detailed Description
This class interpolates tabulated functions with a bi-cubic spline.
Adopted from Numerical Recipes in C (section 3.6). Consistent with the terminology in Numerical Recipes, moving over a column spline means moving over the x1 coord Likewise, moving over a row spline means moving over the x2 coord
Definition at line 22 of file BicubicSplineInterpolation.h.
Constructor & Destructor Documentation
BicubicSplineInterpolation() [1/2]
BicubicSplineInterpolation::BicubicSplineInterpolation ()
Definition at line 15 of file BicubicSplineInterpolation.C.
{}
BicubicSplineInterpolation() [2/2]
BicubicSplineInterpolation::BicubicSplineInterpolation (const std::vector< Real > & x1, const std::vector< Real > & x2, const std::vector< std::vector< Real > > & y, const std::vector< Real > & yx11 = std::vector<Real>(), const std::vector< Real > & yx1n = std::vector<Real>(), const std::vector< Real > & yx21 = std::vector<Real>(), const std::vector< Real > & yx2n = std::vector<Real>())
In the future, may add interface that allows necessary vector of boundary conditions to be supplied for each edge of grid; however, for now we just use natural splines at the grid boundaries.
Definition at line 17 of file BicubicSplineInterpolation.C.
  : SplineInterpolationBase(),
    _x1(x1),
    _x2(x2),
    _y(y),
    _yx11(yx11),
    _yx1n(yx1n),
    _yx21(yx21),
    _yx2n(yx2n)
{
  auto n = _x2.size();
  _row_spline_second_derivs.resize(n);
  _column_spline_eval.resize(n);
  auto m = _x1.size();
  _column_spline_second_derivs.resize(m);
  _row_spline_eval.resize(m);
  errorCheck();
  solve();
}
~BicubicSplineInterpolation()
virtual BicubicSplineInterpolation::~BicubicSplineInterpolation () virtual default
Member Function Documentation
computeCoeffs()
template<typename T > void SplineInterpolationBase::computeCoeffs (const std::vector< Real > & x, unsigned int klo, unsigned int khi, const T & x_int, Real & h, T & a, T & b) const protected inherited
Definition at line 85 of file SplineInterpolationBase.C.
{
  h = x[khi] - x[klo];
  if (h == 0)
    mooseError("The values of x must be distinct");
  a = (x[khi] - x_int) / h;
  b = (x_int - x[klo]) / h;
}
Referenced by SplineInterpolationBase::sample(), SplineInterpolationBase::sample2ndDerivative(), and SplineInterpolationBase::sampleDerivative().
constructColumnSpline()
void BicubicSplineInterpolation::constructColumnSpline (Real x2, std::vector< Real > & spline_eval, std::vector< Real > & spline_second_derivs, Real yx21 = _deriv_bound, Real yx2n = _deriv_bound) protected
Helper functions to evaluate row splines and construct column spline for the given point.
Definition at line 278 of file BicubicSplineInterpolation.C.
{
  auto m = _x1.size();
  // Find the indices that bound the point x2
  unsigned int klo, khi;
  findInterval(_x2, x2, klo, khi);
  // Evaluate m row-splines to get y-values for column spline construction using
  // the indices above to avoid computing them for each j
  for (decltype(m) j = 0; j < m; ++j)
    _row_spline_eval[j] = SplineInterpolationBase::sample(_x2, _y[j], _y2_rows[j], x2, klo, khi);
  // Construct single column spline; get back the second derivatives wrt x1 coord
  // on the x1 grid points
  spline(_x1, row_spline_eval, column_spline_second_derivs, yx21, yx2n);
}
Referenced by sample(), sample2ndDerivative(), sampleDerivative(), and sampleValueAndDerivatives().
constructColumnSplineSecondDerivativeTable()
void BicubicSplineInterpolation::constructColumnSplineSecondDerivativeTable () protected
Definition at line 127 of file BicubicSplineInterpolation.C.
{
  auto m = _x1.size();
  auto n = _x2.size();
  _y2_columns.resize(n);
  _y_trans.resize(n);
  for (decltype(n) j = 0; j < n; ++j)
    _y_trans[j].resize(m);
  // transpose the _y values so the columns can be easily iterated over
  for (decltype(n) i = 0; i < _y.size(); ++i)
    for (decltype(n) j = 0; j < _y[0].size(); ++j)
      _y_trans[j][i] = _y[i][j];
  if (_yx11.empty())
    for (decltype(n) j = 0; j < n; ++j)
      spline(_x1, _y_trans[j], _y2_columns[j]);
  else
    for (decltype(n) j = 0; j < n; ++j)
      spline(_x1, _y_trans[j], _y2_columns[j], _yx11[j], _yx1n[j]);
}
Referenced by solve().
constructRowSpline()
void BicubicSplineInterpolation::constructRowSpline (Real x1, std::vector< Real > & spline_eval, std::vector< Real > & spline_second_derivs, Real yx11 = _deriv_bound, Real yx1n = _deriv_bound) protected
Helper functions to evaluate column splines and construct row spline for the given point.
Definition at line 254 of file BicubicSplineInterpolation.C.
{
  auto n = _x2.size();
  // Find the indices that bound the point x1
  unsigned int klo, khi;
  findInterval(_x1, x1, klo, khi);
  // Evaluate n column-splines to get y-values for row spline construction using
  // the indices above to avoid computing them for each j
  for (decltype(n) j = 0; j < n; ++j)
    _column_spline_eval[j] =
        SplineInterpolationBase::sample(_x1, _y_trans[j], _y2_columns[j], x1, klo, khi);
  // Construct single row spline; get back the second derivatives wrt x2 coord
  // on the x2 grid points
  spline(_x2, column_spline_eval, row_spline_second_derivs, yx11, yx1n);
}
Referenced by sample2ndDerivative(), sampleDerivative(), and sampleValueAndDerivatives().
constructRowSplineSecondDerivativeTable()
void BicubicSplineInterpolation::constructRowSplineSecondDerivativeTable () protected
Precompute tables of row (column) spline second derivatives and store them to reduce computational demands.
Definition at line 112 of file BicubicSplineInterpolation.C.
{
  auto m = _x1.size();
  _y2_rows.resize(m);
  if (_yx21.empty())
    for (decltype(m) j = 0; j < m; ++j)
      spline(_x2, _y[j], _y2_rows[j]);
  else
    for (decltype(m) j = 0; j < m; ++j)
      spline(_x2, _y[j], _y2_rows[j], _yx21[j], _yx2n[j]);
}
Referenced by solve().
errorCheck()
void BicubicSplineInterpolation::errorCheck ()
Sanity checks on input data.
Definition at line 75 of file BicubicSplineInterpolation.C.
{
  auto m = _x1.size(), n = _x2.size();
  if (_y.size() != m)
    mooseError("y row dimension does not match the size of x1.");
  else
    for (decltype(m) i = 0; i < _y.size(); ++i)
      if (_y[i].size() != n)
        mooseError("y column dimension does not match the size of x2.");
  if (_yx11.empty())
    _yx11.resize(n, _deriv_bound);
  else if (_yx11.size() != n)
    mooseError("The length of the vectors holding the first derivatives of y with respect to x1 "
               "must match the length of x2.");
  if (_yx1n.empty())
    _yx1n.resize(n, _deriv_bound);
  else if (_yx1n.size() != n)
    mooseError("The length of the vectors holding the first derivatives of y with respect to x1 "
               "must match the length of x2.");
  if (_yx21.empty())
    _yx21.resize(m, _deriv_bound);
  else if (_yx21.size() != m)
    mooseError("The length of the vectors holding the first derivatives of y with respect to x2 "
               "must match the length of x1.");
  if (_yx2n.empty())
    _yx2n.resize(m, _deriv_bound);
  else if (_yx2n.size() != m)
    mooseError("The length of the vectors holding the first derivatives of y with respect to x2 "
               "must match the length of x1.");
}
Referenced by BicubicSplineInterpolation(), and setData().
findInterval()
void SplineInterpolationBase::findInterval (const std::vector< Real > & x, Real x_int, unsigned int & klo, unsigned int & khi) const protected inherited
Definition at line 65 of file SplineInterpolationBase.C.
{
  klo = 0;
  mooseAssert(x.size() >= 2, "You must have at least two knots to create a spline.");
  khi = x.size() - 1;
  while (khi - klo > 1)
  {
    unsigned int k = (khi + klo) >> 1;
    if (x[k] > x_int)
      khi = k;
    else
      klo = k;
  }
}
Referenced by constructColumnSpline(), constructRowSpline(), SplineInterpolationBase::sample(), SplineInterpolationBase::sample2ndDerivative(), and SplineInterpolationBase::sampleDerivative().
sample() [1/4]
ADReal SplineInterpolationBase::sample (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, const ADReal & x_int) const inherited
Definition at line 113 of file SplineInterpolationBase.C.
{
  unsigned int klo, khi;
  findInterval(x, MetaPhysicL::raw_value(x_int), klo, khi);
  return sample(x, y, y2, x_int, klo, khi);
}
sample() [2/4]
template<typename T > T SplineInterpolationBase::sample (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, const T & x_int, unsigned int klo, unsigned int khi) const protected inherited
Sample value at point x_int given the indices of the vector of dependent values that bound the point.
This method is useful in bicubic spline interpolation, where several spline evaluations are needed to sample from a 2D point.
Definition at line 157 of file SplineInterpolationBase.C.
{
  Real h;
  T a, b;
  computeCoeffs(x, klo, khi, x_int, h, a, b);
  return a * y[klo] + b * y[khi] +
         ((a * a * a - a) * y2[klo] + (b * b * b - b) * y2[khi]) * (h * h) / 6.0;
}
sample() [3/4]
Real SplineInterpolationBase::sample (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, Real x_int) const inherited
Definition at line 101 of file SplineInterpolationBase.C.
{
  unsigned int klo, khi;
  findInterval(x, x_int, klo, khi);
  return sample(x, y, y2, x_int, klo, khi);
}
Referenced by constructColumnSpline(), constructRowSpline(), SplineInterpolationBase::sample(), SplineInterpolation::sample(), sample(), and sampleValueAndDerivatives().
sample() [4/4]
Real BicubicSplineInterpolation::sample (Real x1, Real x2, Real yx11 = _deriv_bound, Real yx1n = _deriv_bound)
Samples value at point (x1, x2)
Definition at line 159 of file BicubicSplineInterpolation.C.
{
  constructColumnSpline(x2, _row_spline_eval, _column_spline_second_derivs, yx11, yx1n);
  // Evaluate newly constructed column spline
  return SplineInterpolationBase::sample(_x1, _row_spline_eval, _column_spline_second_derivs, x1);
}
Referenced by BicubicSplineFunction::value().
sample2ndDerivative() [1/2]
Real SplineInterpolationBase::sample2ndDerivative (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, Real x_int) const inherited
Definition at line 141 of file SplineInterpolationBase.C.
{
  unsigned int klo, khi;
  findInterval(x, x_int, klo, khi);
  Real h, a, b;
  computeCoeffs(x, klo, khi, x_int, h, a, b);
  return a * y2[klo] + b * y2[khi];
}
Referenced by SplineInterpolation::sample2ndDerivative(), and sample2ndDerivative().
sample2ndDerivative() [2/2]
Real BicubicSplineInterpolation::sample2ndDerivative (Real x1, Real x2, unsigned int deriv_var, Real yp1 = _deriv_bound, Real ypn = _deriv_bound)
Samples second derivative at point (x1, x2)
Definition at line 202 of file BicubicSplineInterpolation.C.
{
  // Take second derivative along x1 axis
  if (deriv_var == 1)
  {
    constructColumnSpline(x2, _row_spline_eval, _column_spline_second_derivs, yp1, ypn);
    // Evaluate second derivative wrt x1 of newly constructed column spline
    return SplineInterpolationBase::sample2ndDerivative(
        _x1, _row_spline_eval, _column_spline_second_derivs, x1);
  }
  // Take second derivative along x2 axis
  else if (deriv_var == 2)
  {
    constructRowSpline(x1, _column_spline_eval, _row_spline_second_derivs, yp1, ypn);
    // Evaluate second derivative wrt x2 of newly constructed row spline
    return SplineInterpolationBase::sample2ndDerivative(
        _x2, _column_spline_eval, _row_spline_second_derivs, x2);
  }
  else
    mooseError("deriv_var must be either 1 or 2 in BicubicSplineInterpolation");
}
Referenced by BicubicSplineFunction::secondDerivative().
sampleDerivative() [1/2]
Real SplineInterpolationBase::sampleDerivative (const std::vector< Real > & x, const std::vector< Real > & y, const std::vector< Real > & y2, Real x_int) const inherited
Definition at line 125 of file SplineInterpolationBase.C.
{
  unsigned int klo, khi;
  findInterval(x, x_int, klo, khi);
  Real h, a, b;
  computeCoeffs(x, klo, khi, x_int, h, a, b);
  return (y[khi] - y[klo]) / h -
         (((3.0 * a * a - 1.0) * y2[klo] + (3.0 * b * b - 1.0) * -y2[khi]) * h / 6.0);
}
Referenced by SplineInterpolation::sampleDerivative(), sampleDerivative(), and sampleValueAndDerivatives().
sampleDerivative() [2/2]
Real BicubicSplineInterpolation::sampleDerivative (Real x1, Real x2, unsigned int deriv_var, Real yp1 = _deriv_bound, Real ypn = _deriv_bound)
Samples first derivative at point (x1, x2)
Definition at line 171 of file BicubicSplineInterpolation.C.
{
  // Take derivative along x1 axis
  if (deriv_var == 1)
  {
    constructColumnSpline(x2, _row_spline_eval, _column_spline_second_derivs, yp1, ypn);
    // Evaluate derivative wrt x1 of newly constructed column spline
    return SplineInterpolationBase::sampleDerivative(
        _x1, _row_spline_eval, _column_spline_second_derivs, x1);
  }
  // Take derivative along x2 axis
  else if (deriv_var == 2)
  {
    constructRowSpline(x1, _column_spline_eval, _row_spline_second_derivs, yp1, ypn);
    // Evaluate derivative wrt x2 of newly constructed row spline
    return SplineInterpolationBase::sampleDerivative(
        _x2, _column_spline_eval, _row_spline_second_derivs, x2);
  }
  else
    mooseError("deriv_var must be either 1 or 2 in BicubicSplineInterpolation");
}
Referenced by BicubicSplineFunction::derivative().
sampleValueAndDerivatives()
void BicubicSplineInterpolation::sampleValueAndDerivatives (Real x1, Real x2, Real & y, Real & dy1, Real & dy2, Real yx11 = _deriv_bound, Real yx1n = _deriv_bound, Real yx21 = _deriv_bound, Real yx2n = _deriv_bound)
Samples value and first derivatives at point (x1, x2) Use this function for speed when computing both value and derivatives, as it minimizes the amount of spline evaluation.
Definition at line 233 of file BicubicSplineInterpolation.C.
{
  constructColumnSpline(x2, _row_spline_eval, _column_spline_second_derivs, yx11, yx1n);
  y = SplineInterpolationBase::sample(_x1, _row_spline_eval, _column_spline_second_derivs, x1);
  dy1 = SplineInterpolationBase::sampleDerivative(
      _x1, _row_spline_eval, _column_spline_second_derivs, x1);
  constructRowSpline(x1, _column_spline_eval, _row_spline_second_derivs, yx21, yx2n);
  dy2 = SplineInterpolationBase::sampleDerivative(
      _x2, _column_spline_eval, _row_spline_second_derivs, x2);
}
setData()
void BicubicSplineInterpolation::setData (const std::vector< Real > & x1, const std::vector< Real > & x2, const std::vector< std::vector< Real > > & y, const std::vector< Real > & yx11 = std::vector<Real>(), const std::vector< Real > & yx1n = std::vector<Real>(), const std::vector< Real > & yx21 = std::vector<Real>(), const std::vector< Real > & yx2n = std::vector<Real>())
Set the x1, x2 and y values, and first derivatives at the edges.
Definition at line 46 of file BicubicSplineInterpolation.C.
{
  _x1 = x1;
  _x2 = x2;
  _y = y;
  _yx11 = yx11;
  _yx1n = yx1n;
  _yx21 = yx21;
  _yx2n = yx2n;
  auto n = _x2.size();
  _row_spline_second_derivs.resize(n);
  _column_spline_eval.resize(n);
  auto m = _x1.size();
  _column_spline_second_derivs.resize(m);
  _row_spline_eval.resize(m);
  errorCheck();
  solve();
}
Referenced by BicubicSplineFunction::BicubicSplineFunction().
solve()
void BicubicSplineInterpolation::solve () protected
Calculates the tables of second derivatives.
Definition at line 152 of file BicubicSplineInterpolation.C.
{
  constructRowSplineSecondDerivativeTable();
  constructColumnSplineSecondDerivativeTable();
}
Referenced by BicubicSplineInterpolation(), and setData().
spline()
void SplineInterpolationBase::spline (const std::vector< Real > & x, const std::vector< Real > & y, std::vector< Real > & y2, Real yp1 = _deriv_bound, Real ypn = _deriv_bound) protected inherited
This function calculates the second derivatives based on supplied x and y-vectors.
Definition at line 19 of file SplineInterpolationBase.C.
{
  auto n = x.size();
  if (n < 2)
    mooseError("You must have at least two knots to create a spline.");
  std::vector<Real> u(n, 0.);
  y2.assign(n, 0.);
  if (yp1 >= 1e30)
    y2[0] = u[0] = 0.;
  else
  {
    y2[0] = -0.5;
    u[0] = (3.0 / (x[1] - x[0])) * ((y[1] - y[0]) / (x[1] - x[0]) - yp1);
  }
  // decomposition of tri-diagonal algorithm (y2 and u are used for temporary storage)
  for (decltype(n) i = 1; i < n - 1; i++)
  {
    Real sig = (x[i] - x[i - 1]) / (x[i + 1] - x[i - 1]);
    Real p = sig * y2[i - 1] + 2.0;
    y2[i] = (sig - 1.0) / p;
    u[i] = (y[i + 1] - y[i]) / (x[i + 1] - x[i]) - (y[i] - y[i - 1]) / (x[i] - x[i - 1]);
    u[i] = (6.0 * u[i] / (x[i + 1] - x[i - 1]) - sig * u[i - 1]) / p;
  }
  Real qn, un;
  if (ypn >= 1e30)
    qn = un = 0.;
  else
  {
    qn = 0.5;
    un = (3.0 / (x[n - 1] - x[n - 2])) * (ypn - (y[n - 1] - y[n - 2]) / (x[n - 1] - x[n - 2]));
  }
  y2[n - 1] = (un - qn * u[n - 2]) / (qn * y2[n - 2] + 1.);
  // back substitution
  for (auto k = n - 1; k >= 1; k--)
    y2[k - 1] = y2[k - 1] * y2[k] + u[k - 1];
}
Referenced by constructColumnSpline(), constructColumnSplineSecondDerivativeTable(), constructRowSpline(), constructRowSplineSecondDerivativeTable(), and SplineInterpolation::solve().
Member Data Documentation
_column_spline_eval
std::vector<Real> BicubicSplineInterpolation::_column_spline_eval protected
Definition at line 118 of file BicubicSplineInterpolation.h.
Referenced by BicubicSplineInterpolation(), constructRowSpline(), sample2ndDerivative(), sampleDerivative(), sampleValueAndDerivatives(), and setData().
_column_spline_second_derivs
std::vector<Real> BicubicSplineInterpolation::_column_spline_second_derivs protected
Definition at line 117 of file BicubicSplineInterpolation.h.
Referenced by BicubicSplineInterpolation(), sample(), sample2ndDerivative(), sampleDerivative(), sampleValueAndDerivatives(), and setData().
_deriv_bound
const Real SplineInterpolationBase::_deriv_bound = std::numeric_limits<Real>::max() static protected inherited
Definition at line 79 of file SplineInterpolationBase.h.
Referenced by errorCheck().
_file_number
int BicubicSplineInterpolation::_file_number = 0 static protected
File number for data dump.
Definition at line 153 of file BicubicSplineInterpolation.h.
_row_spline_eval
std::vector<Real> BicubicSplineInterpolation::_row_spline_eval protected
Definition at line 116 of file BicubicSplineInterpolation.h.
Referenced by BicubicSplineInterpolation(), constructColumnSpline(), sample(), sample2ndDerivative(), sampleDerivative(), sampleValueAndDerivatives(), and setData().
_row_spline_second_derivs
std::vector<Real> BicubicSplineInterpolation::_row_spline_second_derivs protected
Vectors used during sampling.
Definition at line 115 of file BicubicSplineInterpolation.h.
Referenced by BicubicSplineInterpolation(), sample2ndDerivative(), sampleDerivative(), sampleValueAndDerivatives(), and setData().
_x1
std::vector<Real> BicubicSplineInterpolation::_x1 protected
Independent values in the x1 direction.
Definition at line 91 of file BicubicSplineInterpolation.h.
Referenced by BicubicSplineInterpolation(), constructColumnSpline(), constructColumnSplineSecondDerivativeTable(), constructRowSpline(), constructRowSplineSecondDerivativeTable(), errorCheck(), sample(), sample2ndDerivative(), sampleDerivative(), sampleValueAndDerivatives(), and setData().
_x2
std::vector<Real> BicubicSplineInterpolation::_x2 protected
Independent values in the x2 direction.
Definition at line 93 of file BicubicSplineInterpolation.h.
Referenced by BicubicSplineInterpolation(), constructColumnSpline(), constructColumnSplineSecondDerivativeTable(), constructRowSpline(), constructRowSplineSecondDerivativeTable(), errorCheck(), sample2ndDerivative(), sampleDerivative(), sampleValueAndDerivatives(), and setData().
_y
std::vector<std::vector<Real> > BicubicSplineInterpolation::_y protected
The dependent values at (x1, x2) points.
Definition at line 95 of file BicubicSplineInterpolation.h.
Referenced by constructColumnSpline(), constructColumnSplineSecondDerivativeTable(), constructRowSplineSecondDerivativeTable(), errorCheck(), and setData().
_y2_columns
std::vector<std::vector<Real> > BicubicSplineInterpolation::_y2_columns protected
Definition at line 112 of file BicubicSplineInterpolation.h.
Referenced by constructColumnSplineSecondDerivativeTable(), and constructRowSpline().
_y2_rows
std::vector<std::vector<Real> > BicubicSplineInterpolation::_y2_rows protected
Second derivatives.
Definition at line 111 of file BicubicSplineInterpolation.h.
Referenced by constructColumnSpline(), and constructRowSplineSecondDerivativeTable().
_y_trans
std::vector<std::vector<Real> > BicubicSplineInterpolation::_y_trans protected
Transpose of _y.
Definition at line 97 of file BicubicSplineInterpolation.h.
Referenced by constructColumnSplineSecondDerivativeTable(), and constructRowSpline().
_yx11
std::vector<Real> BicubicSplineInterpolation::_yx11 protected
Boundary conditions.
The first index indicates the coordinate the derivative is with respect to. The second index indicates the grid index, e.g. 1 is the lower bound, and n is the upper bound
Definition at line 105 of file BicubicSplineInterpolation.h.
Referenced by constructColumnSplineSecondDerivativeTable(), errorCheck(), and setData().
_yx1n
std::vector<Real> BicubicSplineInterpolation::_yx1n protected
Definition at line 106 of file BicubicSplineInterpolation.h.
Referenced by constructColumnSplineSecondDerivativeTable(), errorCheck(), and setData().
_yx21
std::vector<Real> BicubicSplineInterpolation::_yx21 protected
Definition at line 107 of file BicubicSplineInterpolation.h.
Referenced by constructRowSplineSecondDerivativeTable(), errorCheck(), and setData().
_yx2n
std::vector<Real> BicubicSplineInterpolation::_yx2n protected
Definition at line 108 of file BicubicSplineInterpolation.h.
Referenced by constructRowSplineSecondDerivativeTable(), errorCheck(), and setData().
The documentation for this class was generated from the following files:
moose/framework/include/utils/BicubicSplineInterpolation.h
moose/framework/src/utils/BicubicSplineInterpolation.C