Zapdos: DistributionInterface Class Reference
DistributionInterface Class Reference
Interface for objects that need to use distributions.
#include <DistributionInterface.h>
Public Member Functions
DistributionInterface (const MooseObject *moose_object)
const Distribution & getDistribution (const std::string &name) const
Get a distribution with a given name.
template<typename T >
const T & getDistribution (const std::string &name) const
const Distribution & getDistributionByName (const DistributionName &name) const
Get a distribution with a given name.
template<typename T >
const T & getDistributionByName (const std::string &name) const
Static Public Member Functions
static InputParameters validParams ()
Private Attributes
const InputParameters & _dni_params
Parameters of the object with this interface.
FEProblemBase & _dni_feproblem
Reference to FEProblemBase instance.
const MooseObject *const _dni_moose_object_ptr
Pointer to the MooseObject.
Detailed Description
Interface for objects that need to use distributions.
Inherit from this class at a very low level to make the getDistribution method available.
Definition at line 25 of file DistributionInterface.h.
Constructor & Destructor Documentation
DistributionInterface()
DistributionInterface::DistributionInterface (const MooseObject * moose_object)
Definition at line 23 of file DistributionInterface.C.
  : _dni_params(moose_object->parameters()),
    _dni_feproblem(*_dni_params.getCheckedPointerParam<FEProblemBase *>("_fe_problem_base")),
    _dni_moose_object_ptr(moose_object)
{
}
Member Function Documentation
getDistribution() [1/2]
const Distribution & DistributionInterface::getDistribution (const std::string & name) const
Get a distribution with a given name.
Parameters
name The name of the parameter key of the distribution to retrieve
Returns
The distribution with name associated with the parameter 'name'
Definition at line 31 of file DistributionInterface.C.
{
  DistributionName dist_name = _dni_params.get<DistributionName>(name);
  return _dni_feproblem.getDistribution(dist_name);
}
Referenced by getDistribution(), and getDistributionByName().
getDistribution() [2/2]
template<typename T > const T & DistributionInterface::getDistribution (const std::string & name) const
Definition at line 69 of file DistributionInterface.h.
{
  try
  {
    const T & dist = dynamic_cast<const T &>(getDistribution(name));
    return dist;
  }
  catch (std::bad_cast & exception)
  {
    DistributionName dist_name = _dni_params.get<DistributionName>(name);
    mooseError("The '",
               _dni_moose_object_ptr->name(),
               "' object failed to retrieve '",
               dist_name,
               "' distribution with the desired type.");
  }
}
getDistributionByName() [1/2]
const Distribution & DistributionInterface::getDistributionByName (const DistributionName & name) const
Get a distribution with a given name.
Parameters
name The name of the distribution to retrieve
Returns
The distribution with name 'name'
Definition at line 38 of file DistributionInterface.C.
{
  return _dni_feproblem.getDistribution(name);
}
Referenced by RandomIC::RandomIC().
getDistributionByName() [2/2]
template<typename T > const T & DistributionInterface::getDistributionByName (const std::string & name) const
Definition at line 89 of file DistributionInterface.h.
{
  try
  {
    const T & dist = dynamic_cast<const T &>(getDistribution(name));
    return dist;
  }
  catch (std::bad_cast & exception)
  {
    mooseError("The '",
               _dni_moose_object_ptr->name(),
               "' object failed to retrieve '",
               name,
               "' distribution with the desired type.");
  }
}
validParams()
InputParameters DistributionInterface::validParams () static
Definition at line 17 of file DistributionInterface.C.
{
  InputParameters params = emptyInputParameters();
  return params;
}
Referenced by FVInterfaceKernel::validParams(), RandomIC::validParams(), and Sampler::validParams().
Member Data Documentation
_dni_feproblem
FEProblemBase& DistributionInterface::_dni_feproblem private
Reference to FEProblemBase instance.
Definition at line 61 of file DistributionInterface.h.
Referenced by getDistribution(), and getDistributionByName().
_dni_moose_object_ptr
const MooseObject* const DistributionInterface::_dni_moose_object_ptr private
Pointer to the MooseObject.
Definition at line 64 of file DistributionInterface.h.
Referenced by getDistribution(), and getDistributionByName().
_dni_params
const InputParameters& DistributionInterface::_dni_params private
Parameters of the object with this interface.
Definition at line 58 of file DistributionInterface.h.
Referenced by getDistribution().
The documentation for this class was generated from the following files:
moose/framework/include/distributions/DistributionInterface.h
moose/framework/src/distributions/DistributionInterface.C