Zapdos: SamplerBase Class Reference
SamplerBase Class Reference
Base class for VectorPostprocessors that need to do "sampling" of values in the domain.
#include <SamplerBase.h>
Public Member Functions
SamplerBase (const InputParameters &parameters, VectorPostprocessor *vpp, const libMesh::Parallel::Communicator &comm)
virtual ~SamplerBase ()=default
Static Public Member Functions
static InputParameters validParams ()
Protected Member Functions
void setupVariables (const std::vector< std::string > &variable_names)
You MUST call this in the constructor of the child class and pass down the name of the variables.
virtual void addSample (const Point &p, const Real &id, const std::vector< Real > &values)
Call this with the value of every variable at each point you want to sample at.
virtual void initialize ()
Initialize the datastructures.
virtual void finalize ()
Finalize the values.
virtual void threadJoin (const SamplerBase &y)
Join the values.
Protected Attributes
const InputParameters & _sampler_params
The child params.
VectorPostprocessor * _vpp
The child VectorPostprocessor.
const libMesh::Parallel::Communicator & _comm
The communicator of the child.
std::vector< std::string > _variable_names
The variable names.
const unsigned int _sort_by
What to sort by.
VectorPostprocessorValue & _x
x coordinate of the points
VectorPostprocessorValue & _y
y coordinate of the points
VectorPostprocessorValue & _z
x coordinate of the points
VectorPostprocessorValue & _id
The node ID of each point.
std::vector< VectorPostprocessorValue * > _values
Detailed Description
Base class for VectorPostprocessors that need to do "sampling" of values in the domain.
Definition at line 36 of file SamplerBase.h.
Constructor & Destructor Documentation
SamplerBase()
SamplerBase::SamplerBase (const InputParameters & parameters, VectorPostprocessor * vpp, const libMesh::Parallel::Communicator & comm)
Parameters
parameters The parameters for the object
vpp A pointer to the child object
comm The communicator of the child
Definition at line 36 of file SamplerBase.C.
  : _sampler_params(parameters),
    _vpp(vpp),
    _comm(comm),
    _sort_by(parameters.get<MooseEnum>("sort_by")),
    _x(vpp->declareVector("x")),
    _y(vpp->declareVector("y")),
    _z(vpp->declareVector("z")),
    _id(vpp->declareVector("id"))
{
}
~SamplerBase()
virtual SamplerBase::~SamplerBase () virtual default
Member Function Documentation
addSample()
void SamplerBase::addSample (const Point & p, const Real & id, const std::vector< Real > & values) protected virtual
Call this with the value of every variable at each point you want to sample at.
Parameters
p The point where you took the sample
id This can either be an actual ID or a distance or anything else you want
values The value of each variable
Definition at line 61 of file SamplerBase.C.
{
  _x.push_back(p(0));
  _y.push_back(p(1));
  _z.push_back(p(2));
  _id.push_back(id);
  mooseAssert(values.size() == _variable_names.size(), "Mismatch of variable names to vector size");
  for (MooseIndex(values) i = 0; i < values.size(); ++i)
    _values[i]->emplace_back(values[i]);
}
Referenced by ElementValueSampler::execute(), LineFunctionSampler::execute(), NodalValueSampler::execute(), SideValueSampler::execute(), and PointSamplerBase::finalize().
finalize()
void SamplerBase::finalize () protected virtual
Finalize the values.
YOU MUST CALL THIS DURING finalize() in the child class!
We have several vectors that all need to be processed in the same way. Rather than enumerate them all, let's just create a vector of pointers and work on them that way.
We now have one sorted vector. The remaining vectors need to be sorted according to that vector. We'll need a temporary vector to hold values as we map them according to the sorted indices. After that, we'll swap the vector contents with the sorted vector to get the values back into the original vector.
Reimplemented in PointSamplerBase, ElementValueSampler, LineFunctionSampler, LineMaterialSamplerBase< T >, LineMaterialSamplerBase< Real >, NodalValueSampler, and SideValueSampler.
Definition at line 91 of file SamplerBase.C.
{
  constexpr auto NUM_ID_VECTORS = 4;
  std::vector<VectorPostprocessorValue *> vec_ptrs;
  vec_ptrs.reserve(_values.size() + NUM_ID_VECTORS);
  // Initialize the pointer vector with the position and ID vectors
  vec_ptrs = {{&_x, &_y, &_z, &_id}};
  // Now extend the vector by all the remaining values vector before processing
  vec_ptrs.insert(vec_ptrs.end(), _values.begin(), _values.end());
  // Gather up each of the partial vectors
  for (auto vec_ptr : vec_ptrs)
    _comm.allgather(*vec_ptr, /* identical buffer lengths = */ false);
  // Now create an index vector by using an indirect sort
  std::vector<std::size_t> sorted_indices;
  Moose::indirectSort(vec_ptrs[_sort_by]->begin(), vec_ptrs[_sort_by]->end(), sorted_indices);
  // This vector is used as temp storage to sort each of the remaining vectors according to the
  // first
  auto vector_length = sorted_indices.size();
  VectorPostprocessorValue tmp_vector(vector_length);
#ifndef NDEBUG
  for (const auto vec_ptr : vec_ptrs)
    if (vec_ptr->size() != vector_length)
      mooseError("Vector length mismatch");
#endif
  // Sort each of the vectors using the same sorted indices
  for (auto & vec_ptr : vec_ptrs)
  {
    for (MooseIndex(sorted_indices) j = 0; j < sorted_indices.size(); ++j)
      tmp_vector[j] = (*vec_ptr)[sorted_indices[j]];
    // Swap vector storage with sorted vector
    vec_ptr->swap(tmp_vector);
  }
}
Referenced by PointSamplerBase::finalize(), ElementValueSampler::finalize(), LineFunctionSampler::finalize(), LineMaterialSamplerBase< T >::finalize(), NodalValueSampler::finalize(), and SideValueSampler::finalize().
initialize()
void SamplerBase::initialize () protected virtual
Initialize the datastructures.
YOU MUST CALL THIS DURING initialize() in the child class!
Reimplemented in PointSamplerBase, PointVariableSamplerBase, ElementValueSampler, LineFunctionSampler, LineMaterialSamplerBase< T >, LineMaterialSamplerBase< Real >, NodalValueSampler, PointValueSampler, PositionsFunctorValueSampler, and SideValueSampler.
Definition at line 75 of file SamplerBase.C.
{
  // Don't reset the vectors if we want to retain history
  if (_vpp->containsCompleteHistory() && _comm.rank() == 0)
    return;
  _x.clear();
  _y.clear();
  _z.clear();
  _id.clear();
  std::for_each(
      _values.begin(), _values.end(), [](VectorPostprocessorValue * vec) { vec->clear(); });
}
Referenced by PointSamplerBase::initialize(), PointVariableSamplerBase::initialize(), ElementValueSampler::initialize(), LineFunctionSampler::initialize(), LineMaterialSamplerBase< T >::initialize(), NodalValueSampler::initialize(), and SideValueSampler::initialize().
setupVariables()
void SamplerBase::setupVariables (const std::vector< std::string > & variable_names) protected
You MUST call this in the constructor of the child class and pass down the name of the variables.
Parameters
variable_names The names of the variables. Note: The order of the variables sets the order of the values for addSample()
Definition at line 51 of file SamplerBase.C.
{
  _variable_names = variable_names;
  _values.reserve(variable_names.size());
  for (const auto & variable_name : variable_names)
    _values.push_back(&_vpp->declareVector(variable_name));
}
Referenced by ElementValueSampler::ElementValueSampler(), LineFunctionSampler::LineFunctionSampler(), LineMaterialSamplerBase< T >::LineMaterialSamplerBase(), NodalValueSampler::NodalValueSampler(), PointVariableSamplerBase::PointVariableSamplerBase(), PositionsFunctorValueSampler::PositionsFunctorValueSampler(), and SideValueSampler::SideValueSampler().
threadJoin()
void SamplerBase::threadJoin (const SamplerBase & y) protected virtual
Join the values.
YOU MUST CALL THIS DURING threadJoin() in the child class!
Parameters
y You must cast the UserObject to your child class type first then you can pass it in here.
Reimplemented in ElementValueSampler, NodalValueSampler, and SideValueSampler.
Definition at line 145 of file SamplerBase.C.
{
  _x.insert(_x.end(), y._x.begin(), y._x.end());
  _y.insert(_y.end(), y._y.begin(), y._y.end());
  _z.insert(_z.end(), y._z.begin(), y._z.end());
  _id.insert(_id.end(), y._id.begin(), y._id.end());
  for (MooseIndex(_variable_names) i = 0; i < _variable_names.size(); i++)
    _values[i]->insert(_values[i]->end(), y._values[i]->begin(), y._values[i]->end());
}
Referenced by ElementValueSampler::threadJoin(), NodalValueSampler::threadJoin(), and SideValueSampler::threadJoin().
validParams()
InputParameters SamplerBase::validParams () static
Definition at line 22 of file SamplerBase.C.
{
  InputParameters params = emptyInputParameters();
  MooseEnum sort_options("x y z id");
  params.addRequiredParam<MooseEnum>("sort_by", sort_options, "What to sort the samples by");
  // The value from this VPP is naturally already on every processor
  // TODO: Make this not the case!  See #11415
  params.set<bool>("_auto_broadcast") = false;
  return params;
}
Referenced by ElementValueSampler::validParams(), LineFunctionSampler::validParams(), LineMaterialSamplerBase< T >::validParams(), NodalValueSampler::validParams(), PointSamplerBase::validParams(), PointVariableSamplerBase::validParams(), and SideValueSampler::validParams().
Member Data Documentation
_comm
const libMesh::Parallel::Communicator& SamplerBase::_comm protected
The communicator of the child.
Definition at line 100 of file SamplerBase.h.
Referenced by PointSamplerBase::finalize(), finalize(), and initialize().
_id
VectorPostprocessorValue& SamplerBase::_id protected
The node ID of each point.
Definition at line 116 of file SamplerBase.h.
Referenced by addSample(), finalize(), LineValueSampler::getValue(), initialize(), and threadJoin().
_sampler_params
const InputParameters& SamplerBase::_sampler_params protected
The child params.
Definition at line 94 of file SamplerBase.h.
_sort_by
const unsigned int SamplerBase::_sort_by protected
What to sort by.
Definition at line 106 of file SamplerBase.h.
Referenced by finalize(), and LineValueSampler::getValue().
_values
std::vector<VectorPostprocessorValue *> SamplerBase::_values protected
Definition at line 118 of file SamplerBase.h.
Referenced by addSample(), finalize(), LineValueSampler::getValue(), initialize(), setupVariables(), and threadJoin().
_variable_names
std::vector<std::string> SamplerBase::_variable_names protected
The variable names.
Definition at line 103 of file SamplerBase.h.
Referenced by addSample(), setupVariables(), and threadJoin().
_vpp
VectorPostprocessor* SamplerBase::_vpp protected
The child VectorPostprocessor.
Definition at line 97 of file SamplerBase.h.
Referenced by initialize(), and setupVariables().
_x
VectorPostprocessorValue& SamplerBase::_x protected
x coordinate of the points
Definition at line 109 of file SamplerBase.h.
Referenced by addSample(), finalize(), initialize(), and threadJoin().
_y
VectorPostprocessorValue& SamplerBase::_y protected
y coordinate of the points
Definition at line 111 of file SamplerBase.h.
Referenced by addSample(), finalize(), initialize(), and threadJoin().
_z
VectorPostprocessorValue& SamplerBase::_z protected
x coordinate of the points
Definition at line 113 of file SamplerBase.h.
Referenced by addSample(), finalize(), initialize(), and threadJoin().
The documentation for this class was generated from the following files:
moose/framework/include/vectorpostprocessors/SamplerBase.h
moose/framework/src/vectorpostprocessors/SamplerBase.C