Zapdos: OutputInterface Class Reference
OutputInterface Class Reference
A class to provide an common interface to objects requiring "outputs" option.
#include <OutputInterface.h>
Public Member Functions
OutputInterface (const InputParameters &parameters, bool build_list=true)
Handles 'outputs' parameter for objects that desire control of variable outputs.
void buildOutputHideVariableList (std::set< std::string > variable_names)
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
const std::set< OutputName > & getOutputs ()
Get the list of output objects that this class is restricted.
Static Public Member Functions
static InputParameters validParams ()
Private Attributes
MooseApp & _oi_moose_app
Reference the the MooseApp; neede for access to the OutputWarehouse.
OutputWarehouse & _oi_output_warehouse
Reference to the OutputWarehouse for populating the Output object hide lists.
std::set< OutputName > _oi_outputs
The set of Output object names listed in the 'outputs' parameter.
Detailed Description
A class to provide an common interface to objects requiring "outputs" option.
The 'outputs' option, when set restricts the output of the variable(s) associated with this object to only occur on output objects listed.
Definition at line 33 of file OutputInterface.h.
Constructor & Destructor Documentation
OutputInterface()
OutputInterface::OutputInterface (const InputParameters & parameters, bool build_list = true)
Handles 'outputs' parameter for objects that desire control of variable outputs.
Parameters
parameters The parameters object holding data for the class to use.
build_list If false the buildOutputHideVariableList must be called explicitly, this behavior is required for automatic output of material properties
Definition at line 35 of file OutputInterface.C.
  : _oi_moose_app(*parameters.getCheckedPointerParam<MooseApp *>("_moose_app")),
    _oi_output_warehouse(_oi_moose_app.getOutputWarehouse()),
    _oi_outputs(parameters.get<std::vector<OutputName>>("outputs").begin(),
                parameters.get<std::vector<OutputName>>("outputs").end())
{
  // By default it is assumed that the variable name associated with 'outputs' is the name
  // of the block, this is the case for Markers, Indicators, VectorPostprocessors, and
  // Postprocessors.
  // However, for Materials this is not the case, so the call to buildOutputHideVariableList must be
  // disabled, the build_list allows for this behavior. The hide lists are handled by
  // MaterialOutputAction in this case.
  //
  // Variables/AuxVariables also call the buildOutputHideVariableList method later, because when
  // their actions are called the Output objects do not exist. This case is handled by the
  // CheckOutputAction::checkVariableOutput.
  if (build_list)
  {
    std::set<std::string> names_set;
    names_set.insert(parameters.get<std::string>("_object_name"));
    buildOutputHideVariableList(names_set);
  }
}
Member Function Documentation
buildOutputHideVariableList()
void OutputInterface::buildOutputHideVariableList (std::set< std::string > variable_names)
Builds hide lists for output objects NOT listed in the 'outputs' parameter.
Parameters
variable_names A set of variables for which the 'outputs' parameter controls
By default this is called by the constructor and passes the block name as the list of variables. This needs to be called explicitly if the build_list flag is set to False in the constructor. The latter cases is needed by the Material object to work correctly with the automatic material output capability.
Definition at line 61 of file OutputInterface.C.
{
  // Set of available names
  const std::set<OutputName> & avail = _oi_output_warehouse.getOutputNames();
  // Check for 'none'; hide variables on all outputs
  if (_oi_outputs.find("none") != _oi_outputs.end())
    for (const auto & name : avail)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  // Check for empty and 'all' in 'outputs' parameter; do not perform any variable restrictions in
  // these cases
  else if (_oi_outputs.empty() || _oi_outputs.find("all") != _oi_outputs.end())
    return;
  // Limit the variable output to Output objects listed
  else
  {
    // Create a list of outputs where the variable should be hidden
    std::set<OutputName> hide;
    std::set_difference(avail.begin(),
                        avail.end(),
                        _oi_outputs.begin(),
                        _oi_outputs.end(),
                        std::inserter(hide, hide.begin()));
    // If 'outputs' is specified add the object name to the list of items to hide
    for (const auto & name : hide)
      _oi_output_warehouse.addInterfaceHideVariables(name, variable_names);
  }
}
Referenced by ReporterTransferInterface::hideVariableHelper(), and OutputInterface().
getOutputs()
const std::set< OutputName > & OutputInterface::getOutputs ()
Get the list of output objects that this class is restricted.
Returns
A set of OutputNames
Definition at line 94 of file OutputInterface.C.
{
  return _oi_outputs;
}
validParams()
InputParameters OutputInterface::validParams () static
Definition at line 18 of file OutputInterface.C.
{
  InputParameters params = emptyInputParameters();
  params.addClassDescription("Interface to handle the restriction of outputs from objects");
  params.addParam<std::vector<OutputName>>("outputs",
                                           "Vector of output names where you would like "
                                           "to restrict the output of variables(s) "
                                           "associated with this object");
  params.addParamNamesToGroup("outputs", "Advanced");
  std::set<std::string> reserved = {"all", "none"};
  params.setReservedValues("outputs", reserved);
  return params;
}
Referenced by Indicator::validParams(), Marker::validParams(), MaterialBase::validParams(), Postprocessor::validParams(), Reporter::validParams(), MooseVariableBase::validParams(), and VectorPostprocessor::validParams().
Member Data Documentation
_oi_moose_app
MooseApp& OutputInterface::_oi_moose_app private
Reference the the MooseApp; neede for access to the OutputWarehouse.
Definition at line 66 of file OutputInterface.h.
_oi_output_warehouse
OutputWarehouse& OutputInterface::_oi_output_warehouse private
Reference to the OutputWarehouse for populating the Output object hide lists.
Definition at line 69 of file OutputInterface.h.
Referenced by buildOutputHideVariableList().
_oi_outputs
std::set<OutputName> OutputInterface::_oi_outputs private
The set of Output object names listed in the 'outputs' parameter.
Definition at line 72 of file OutputInterface.h.
Referenced by buildOutputHideVariableList(), and getOutputs().
The documentation for this class was generated from the following files:
moose/framework/include/interfaces/OutputInterface.h
moose/framework/src/interfaces/OutputInterface.C