Zapdos: AttribPostAux Class Reference
AttribPostAux Class Reference abstract
TODO: delete this later - it is a temporary hack for dealing with inter-system dependencies.
#include <Attributes.h>
Public Types
typedef int Key
Public Member Functions
void setFrom (Key k)
AttribPostAux (TheWarehouse &w)
AttribPostAux (TheWarehouse &w, Key val)
AttribPostAux (TheWarehouse &w, const std::set< Key > &vals)
virtual void initFrom (const MooseObject *obj) override
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
virtual bool isMatch (const Attribute &other) const override
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
virtual bool isEqual (const Attribute &other) const override
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
hashfunc (_vals)
clonefunc (AttribPostAux)
bool operator== (const Attribute &other) const
bool operator!= (const Attribute &other) const
unsigned int id () const
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
virtual std::size_t hash () const =0
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
virtual std::unique_ptr< Attribute > clone () const =0
clone creates and returns and identical (deep) copy of this attribute - i.e.
Private Attributes
std::set< Key > _vals
int _id = -1
Detailed Description
TODO: delete this later - it is a temporary hack for dealing with inter-system dependencies.
this attribute was added to ensure that UOs are uniquely assigned a single group to prevent multiple executions when it is queried in FEProblemBase::computeUserObjectsInternal() for a given exec flag time.
Definition at line 344 of file Attributes.h.
Member Typedef Documentation
Key
typedef int AttribPostAux::Key
Definition at line 347 of file Attributes.h.
Constructor & Destructor Documentation
AttribPostAux() [1/3]
AttribPostAux::AttribPostAux (TheWarehouse & w) inline
Definition at line 354 of file Attributes.h.
: Attribute(w, "post_aux") {}
AttribPostAux() [2/3]
AttribPostAux::AttribPostAux (TheWarehouse & w, Key val) inline
Definition at line 355 of file Attributes.h.
: Attribute(w, "post_aux") { _vals.insert(val); }
AttribPostAux() [3/3]
AttribPostAux::AttribPostAux (TheWarehouse & w, const std::set< Key > & vals) inline
Definition at line 356 of file Attributes.h.
    : Attribute(w, "post_aux"), _vals(vals)
  {
  }
Member Function Documentation
clone()
virtual std::unique_ptr< Attribute > Attribute::clone () const pure virtual inherited
clone creates and returns and identical (deep) copy of this attribute - i.e.
the result of clone should return true if passed into isMatch.
Referenced by FEProblemBase::computeUserObjectsInternal(), and TheWarehouse::update().
clonefunc()
AttribPostAux::clonefunc (AttribPostAux)
hash()
virtual std::size_t Attribute::hash () const pure virtual inherited
This function must return a deterministic value that is uniquely determined by the data the attribute holds (i.e.
is initialized with). Ideally, the data should be uniformly and randomly distributed across the domain of size_t values - e.g. 1 and 2 should hash to completely unrelated values. Use of std::hash for POD is encouraged. A convenience hash_combine function is also provided to combine the results an existing hash with one or more other values.
Referenced by std::hash< Attribute >::operator()().
hashfunc()
AttribPostAux::hashfunc (_vals)
id()
unsigned int Attribute::id () const inline inherited
returns the unique attribute ID associated with all attributes that have the same (mose derived) class as this object.
This ID is determined at construction time this
Definition at line 66 of file TheWarehouse.h.
{ return _id; }
Referenced by std::hash< Attribute >::operator()().
initFrom()
void AttribPostAux::initFrom (const MooseObject * obj) override virtual
initFrom reads and stores the desired meta-data from obj for later matching comparisons.
Implements Attribute.
Definition at line 392 of file Attributes.C.
{
}
isEqual()
bool AttribPostAux::isEqual (const Attribute & other) const override virtual
isEqual returns true if the meta-data stored in this attribute is identical to that stored in other.
isEqual does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 385 of file Attributes.C.
{
  const auto a = dynamic_cast<const AttribPostAux *>(&other);
  return a && a->_vals == _vals;
}
isMatch()
bool AttribPostAux::isMatch (const Attribute & other) const override virtual
isMatch returns true if the meta-data stored in this attribute is equivalent to that stored in other.
This is is for query matching - not exact equivalence. isMatch does not need to check/compare the values from the instances' id() functions.
Implements Attribute.
Definition at line 369 of file Attributes.C.
{
  const auto a = dynamic_cast<const AttribPostAux *>(&other);
  bool is_match = false;
  if (a && !_vals.empty() && !a->_vals.empty())
  {
    is_match = std::includes(_vals.begin(), _vals.end(), a->_vals.begin(), a->_vals.end()) ||
               std::includes(a->_vals.begin(), a->_vals.end(), _vals.begin(), _vals.end());
  }
  return is_match;
}
operator!=()
bool Attribute::operator!= (const Attribute & other) const inline inherited
Definition at line 61 of file TheWarehouse.h.
{ return !(*this == other); }
operator==()
bool Attribute::operator== (const Attribute & other) const inline inherited
Definition at line 57 of file TheWarehouse.h.
  {
    return _id == other._id && isEqual(other);
  }
setFrom()
void AttribPostAux::setFrom (Key k) inline
Definition at line 348 of file Attributes.h.
  {
    _vals.clear();
    _vals.insert(k);
  }
Member Data Documentation
_id
int Attribute::_id = -1 private inherited
Definition at line 91 of file TheWarehouse.h.
Referenced by Attribute::id(), and Attribute::operator==().
_vals
std::set<Key> AttribPostAux::_vals private
Definition at line 367 of file Attributes.h.
Referenced by AttribPostAux(), isEqual(), isMatch(), and setFrom().
The documentation for this class was generated from the following files:
moose/framework/include/base/Attributes.h
moose/framework/src/base/Attributes.C