Zapdos: moose/framework/src/interfaces/Coupleable.C File Reference
Coupleable.C File Reference
Functions
void checkComponent (const MooseObject *obj, unsigned int comp, unsigned int bound, const std::string &var_name)
const ADVectorVariableSecond & adCoupledVectorSecond (const std::string &, unsigned int)
Function Documentation
adCoupledVectorSecond()
const ADVectorVariableSecond & adCoupledVectorSecond (const std::string & , unsigned int)
Definition at line 2116 of file Coupleable.C.
{
  mooseError("Automatic differentiation using second derivatives of vector variables is not "
             "implemented.");
}
checkComponent()
void checkComponent (const MooseObject * obj, unsigned int comp, unsigned int bound, const std::string & var_name)
Definition at line 172 of file Coupleable.C.
{
  if (bound > 0 && comp >= bound)
    obj->paramError(
        var_name, "component ", comp, " is out of range for this variable (max ", bound - 1, ")");
}
Referenced by Coupleable::checkVar(), Coupleable::coupled(), and Coupleable::getDefaultValue().