Zapdos: moose/framework/include/restart/DataIO.h File Reference
DataIO.h File Reference
Classes
class libMesh::Parallel::Packing< std::basic_string< T > >
Namespaces
namespace libMesh
The following methods are specializations for using the libMesh::Parallel::packed_range_* routines for std::strings.
namespace libMesh::Parallel
Functions
template<typename P >
void storeHelper (std::ostream &stream, P &data, void *context)
Scalar helper routine.
template<typename P >
void storeHelper (std::ostream &stream, std::vector< P > &data, void *context)
Vector helper routine.
template<typename P >
void storeHelper (std::ostream &stream, std::shared_ptr< P > &data, void *context)
Shared pointer helper routine.
template<typename P >
void storeHelper (std::ostream &stream, std::unique_ptr< P > &data, void *context)
Unique pointer helper routine.
template<typename P >
void storeHelper (std::ostream &stream, std::set< P > &data, void *context)
Set helper routine.
template<typename P , typename Q >
void storeHelper (std::ostream &stream, std::map< P, Q > &data, void *context)
Map helper routine.
template<typename P , typename Q >
void storeHelper (std::ostream &stream, std::unordered_map< P, Q > &data, void *context)
Unordered_map helper routine.
template<typename P , typename Q >
void storeHelper (std::ostream &stream, HashMap< P, Q > &data, void *context)
HashMap helper routine.
template<typename P >
void loadHelper (std::istream &stream, P &data, void *context)
Scalar helper routine.
template<typename P >
void loadHelper (std::istream &stream, std::vector< P > &data, void *context)
Vector helper routine.
template<typename P >
void loadHelper (std::istream &stream, std::shared_ptr< P > &data, void *context)
Shared Pointer helper routine.
template<typename P >
void loadHelper (std::istream &stream, std::unique_ptr< P > &data, void *context)
Unique Pointer helper routine.
template<typename P >
void loadHelper (std::istream &stream, std::set< P > &data, void *context)
Set helper routine.
template<typename P , typename Q >
void loadHelper (std::istream &stream, std::map< P, Q > &data, void *context)
Map helper routine.
template<typename P , typename Q >
void loadHelper (std::istream &stream, std::unordered_map< P, Q > &data, void *context)
Unordered_map helper routine.
template<typename P , typename Q >
void loadHelper (std::istream &stream, HashMap< P, Q > &data, void *context)
Hashmap helper routine.
template<typename T >
void dataStore (std::ostream &stream, T &v, void *)
template<typename T >
void dataStore (std::ostream &, T *&, void *)
void dataStore (std::ostream &stream, Point &p, void *context)
template<typename T , typename U >
void dataStore (std::ostream &stream, std::pair< T, U > &p, void *context)
template<typename T >
void dataStore (std::ostream &stream, std::vector< T > &v, void *context)
template<typename T >
void dataStore (std::ostream &stream, std::shared_ptr< T > &v, void *context)
template<typename T >
void dataStore (std::ostream &stream, std::unique_ptr< T > &v, void *context)
template<typename T >
void dataStore (std::ostream &stream, std::set< T > &s, void *context)
template<typename T >
void dataStore (std::ostream &stream, std::list< T > &l, void *context)
template<typename T >
void dataStore (std::ostream &stream, std::deque< T > &l, void *context)
template<typename T , typename U >
void dataStore (std::ostream &stream, std::map< T, U > &m, void *context)
template<typename T , typename U >
void dataStore (std::ostream &stream, std::unordered_map< T, U > &m, void *context)
template<typename T , typename U >
void dataStore (std::ostream &stream, HashMap< T, U > &m, void *context)
template<>
void dataStore (std::ostream &stream, Real &v, void *context)
template<>
void dataStore (std::ostream &stream, std::string &v, void *context)
template<>
void dataStore (std::ostream &stream, VariableName &v, void *context)
template<>
void dataStore (std::ostream &stream, bool &v, void *context)
template<>
void dataStore (std::ostream &stream, std::vector< bool > &v, void *context)
template<>
void dataStore (std::ostream &stream, const Elem *&e, void *context)
template<>
void dataStore (std::ostream &stream, const Node *&n, void *context)
template<>
void dataStore (std::ostream &stream, Elem *&e, void *context)
template<>
void dataStore (std::ostream &stream, Node *&n, void *context)
template<>
void dataStore (std::ostream &stream, std::stringstream &s, void *context)
template<>
void dataStore (std::ostream &stream, DualReal &dn, void *context)
template<>
void dataStore (std::ostream &stream, RealEigenVector &v, void *context)
template<>
void dataStore (std::ostream &stream, RealEigenMatrix &v, void *context)
template<>
void dataStore (std::ostream &stream, libMesh::Parameters &p, void *context)
template<std::size_t N>
void dataStore (std::ostream &stream, std::array< DualReal, N > &dn, void *context)
template<std::size_t N>
void dataStore (std::ostream &stream, DualReal(&dn)[N], void *context)
template<typename T >
void dataStore (std::ostream &stream, NumericVector< T > &v, void *context)
template<>
void dataStore (std::ostream &stream, Vec &v, void *context)
template<typename T >
void dataStore (std::ostream &stream, DenseVector< T > &v, void *context)
template<typename T >
void dataStore (std::ostream &stream, TensorValue< T > &v, void *context)
template<typename T >
void dataStore (std::ostream &stream, DenseMatrix< T > &v, void *context)
template<typename T >
void dataStore (std::ostream &stream, VectorValue< T > &v, void *context)
template<typename T >
void dataStore (std::ostream &stream, RankTwoTensorTempl< T > &rtt, void *context)
template<typename T >
void dataStore (std::ostream &stream, RankThreeTensorTempl< T > &rtt, void *context)
template<typename T >
void dataStore (std::ostream &stream, RankFourTensorTempl< T > &rft, void *context)
template<typename T >
void dataStore (std::ostream &stream, SymmetricRankTwoTensorTempl< T > &srtt, void *context)
template<typename T >
void dataStore (std::ostream &stream, SymmetricRankFourTensorTempl< T > &srft, void *context)
template<typename T >
void dataStore (std::ostream &stream, ColumnMajorMatrixTempl< T > &cmm, void *context)
template<typename T >
void dataLoad (std::istream &stream, T &v, void *)
template<typename T >
void dataLoad (std::istream &, T *&, void *)
template<typename T , typename U >
void dataLoad (std::istream &stream, std::pair< T, U > &p, void *context)
template<typename T >
void dataLoad (std::istream &stream, std::vector< T > &v, void *context)
template<typename T >
void dataLoad (std::istream &stream, std::shared_ptr< T > &v, void *context)
template<typename T >
void dataLoad (std::istream &stream, std::unique_ptr< T > &v, void *context)
template<typename T >
void dataLoad (std::istream &stream, std::set< T > &s, void *context)
template<typename T >
void dataLoad (std::istream &stream, std::list< T > &l, void *context)
template<typename T >
void dataLoad (std::istream &stream, std::deque< T > &l, void *context)
template<typename T , typename U >
void dataLoad (std::istream &stream, std::map< T, U > &m, void *context)
template<typename T , typename U >
void dataLoad (std::istream &stream, std::unordered_map< T, U > &m, void *context)
template<typename T , typename U >
void dataLoad (std::istream &stream, HashMap< T, U > &m, void *context)
template<>
void dataLoad (std::istream &stream, Real &v, void *)
template<>
void dataLoad (std::istream &stream, std::string &v, void *)
template<>
void dataLoad (std::istream &stream, VariableName &v, void *)
template<>
void dataLoad (std::istream &stream, bool &v, void *)
template<>
void dataLoad (std::istream &stream, std::vector< bool > &v, void *)
template<>
void dataLoad (std::istream &stream, const Elem *&e, void *context)
template<>
void dataLoad (std::istream &stream, const Node *&e, void *context)
template<>
void dataLoad (std::istream &stream, Elem *&e, void *context)
template<>
void dataLoad (std::istream &stream, Node *&e, void *context)
template<>
void dataLoad (std::istream &stream, std::stringstream &s, void *context)
template<>
void dataLoad (std::istream &stream, DualReal &dn, void *context)
template<>
void dataLoad (std::istream &stream, RealEigenVector &v, void *context)
template<>
void dataLoad (std::istream &stream, RealEigenMatrix &v, void *context)
template<>
void dataLoad (std::istream &stream, libMesh::Parameters &p, void *context)
template<std::size_t N>
void dataLoad (std::istream &stream, std::array< DualReal, N > &dn, void *context)
template<std::size_t N>
void dataLoad (std::istream &stream, DualReal(&dn)[N], void *context)
template<typename T >
void dataLoad (std::istream &stream, NumericVector< T > &v, void *context)
template<>
void dataLoad (std::istream &stream, Vec &v, void *context)
template<typename T >
void dataLoad (std::istream &stream, DenseVector< T > &v, void *context)
template<typename T >
void dataLoad (std::istream &stream, TensorValue< T > &v, void *context)
template<typename T >
void dataLoad (std::istream &stream, DenseMatrix< T > &v, void *context)
template<typename T >
void dataLoad (std::istream &stream, VectorValue< T > &v, void *context)
template<typename T >
void dataLoad (std::istream &stream, RankTwoTensorTempl< T > &rtt, void *context)
template<typename T >
void dataLoad (std::istream &stream, RankThreeTensorTempl< T > &rtt, void *context)
template<typename T >
void dataLoad (std::istream &stream, RankFourTensorTempl< T > &rft, void *context)
template<typename T >
void dataLoad (std::istream &stream, SymmetricRankTwoTensorTempl< T > &rtt, void *context)
template<typename T >
void dataLoad (std::istream &stream, SymmetricRankFourTensorTempl< T > &rft, void *context)
template<typename T >
void dataLoad (std::istream &stream, ColumnMajorMatrixTempl< T > &cmm, void *context)
void dataLoad (std::istream &stream, Point &p, void *context)
template<typename T >
void dataStoreSkippable (std::ostream &stream, T &v, void *context)
Stores the data v in a "skippable" sense.
template<typename T >
void dataLoadSkippable (std::istream &stream, T &v, void *context)
Loads a piece of "skippable" data.
void dataLoadSkip (std::istream &stream)
Skips a piece of "skippable" data.
Function Documentation
dataLoad() [1/41]
template<typename T > void dataLoad (std::istream & , T *& , void *)
Definition at line 482 of file DataIO.h.
{
  mooseError("Attempting to load a raw pointer type: \"",
             demangle(typeid(T).name()),
             " *\" as restartable data!\nWrite a custom dataLoad() template specialization!\n\n");
}
dataLoad() [2/41]
template<> void dataLoad (std::istream & stream, bool & v, void *)
Definition at line 348 of file DataIO.C.
{
  stream.read((char *)&v, sizeof(v));
}
dataLoad() [3/41]
template<typename T > void dataLoad (std::istream & stream, ColumnMajorMatrixTempl< T > & cmm, void * context)
Definition at line 761 of file DataIO.h.
{
  dataLoad(stream, cmm._values, context);
}
dataLoad() [4/41]
template<> void dataLoad (std::istream & stream, const Elem *& e, void * context)
Definition at line 384 of file DataIO.C.
{
  if (!context)
    mooseError("Can only load Elem objects using a MooseMesh context!");
  MooseMesh * mesh = static_cast<MooseMesh *>(context);
  // TODO: Write out the unique ID of this element
  dof_id_type id = libMesh::DofObject::invalid_id;
  loadHelper(stream, id, context);
  if (id != libMesh::DofObject::invalid_id)
    e = mesh->elemPtr(id);
  else
    e = NULL;
}
dataLoad() [5/41]
template<> void dataLoad (std::istream & stream, const Node *& e, void * context)
Definition at line 404 of file DataIO.C.
{
  if (!context)
    mooseError("Can only load Node objects using a MooseMesh context!");
  MooseMesh * mesh = static_cast<MooseMesh *>(context);
  // TODO: Write out the unique ID of this nodeent
  dof_id_type id = libMesh::DofObject::invalid_id;
  loadHelper(stream, id, context);
  if (id != libMesh::DofObject::invalid_id)
    n = mesh->nodePtr(id);
  else
    n = NULL;
}
dataLoad() [6/41]
template<typename T > void dataLoad (std::istream & stream, DenseMatrix< T > & v, void * context)
Definition at line 530 of file DataIO.C.
{
  unsigned int m = 0, n = 0;
  stream.read((char *)&m, sizeof(m));
  stream.read((char *)&n, sizeof(n));
  v.resize(m, n);
  for (unsigned int i = 0; i < m; i++)
    for (unsigned int j = 0; j < n; j++)
    {
      T r = 0;
      dataLoad(stream, r, context);
      v(i, j) = r;
    }
}
dataLoad() [7/41]
template<typename T > void dataLoad (std::istream & stream, DenseVector< T > & v, void * context)
Definition at line 702 of file DataIO.h.
{
  unsigned int n = 0;
  dataLoad(stream, n, nullptr);
  v.resize(n);
  for (unsigned int i = 0; i < n; i++)
  {
    T r = 0;
    dataLoad(stream, r, context);
    v(i) = r;
  }
}
dataLoad() [8/41]
template<> void dataLoad (std::istream & stream, DualReal & dn, void * context)
Definition at line 363 of file DataIO.C.
{
  dataLoad(stream, dn.value(), context);
  if (DualReal::do_derivatives)
  {
    auto & derivatives = dn.derivatives();
    std::size_t size = 0;
    stream.read((char *)&size, sizeof(size));
    derivatives.resize(size);
    for (MooseIndex(derivatives) i = 0; i < derivatives.size(); ++i)
    {
      dataLoad(stream, derivatives.raw_index(i), context);
      dataLoad(stream, derivatives.raw_at(i), context);
    }
  }
}
dataLoad() [9/41]
template<std::size_t N> void dataLoad (std::istream & stream, DualReal(&) dn[N], void * context) inline
Definition at line 677 of file DataIO.h.
{
  for (std::size_t i = 0; i < N; ++i)
    dataLoad(stream, dn[i], context);
}
dataLoad() [10/41]
template<> void dataLoad (std::istream & stream, Elem *& e, void * context)
Definition at line 424 of file DataIO.C.
{
  if (!context)
    mooseError("Can only load Elem objects using a MooseMesh context!");
  MooseMesh * mesh = static_cast<MooseMesh *>(context);
  // TODO: Write out the unique ID of this element
  dof_id_type id = libMesh::DofObject::invalid_id;
  loadHelper(stream, id, context);
  if (id != libMesh::DofObject::invalid_id)
    e = mesh->elemPtr(id);
  else
    e = NULL;
}
dataLoad() [11/41]
template<typename T , typename U > void dataLoad (std::istream & stream, HashMap< T, U > & m, void * context) inline
Definition at line 619 of file DataIO.h.
{
  // First read the size of the map
  unsigned int size = 0;
  dataLoad(stream, size, nullptr);
  for (unsigned int i = 0; i < size; i++)
  {
    T key;
    loadHelper(stream, key, context);
    U & value = m[key];
    loadHelper(stream, value, context);
  }
}
dataLoad() [12/41]
template<> void dataLoad (std::istream & stream, libMesh::Parameters & p, void * context)
Definition at line 578 of file DataIO.C.
{
  p.clear();
  // First read the size of the map
  unsigned int size = 0;
  stream.read((char *)&size, sizeof(size));
  for (unsigned int i = 0; i < size; i++)
  {
    std::string key, type;
    loadHelper(stream, key, context);
    loadHelper(stream, type, context);
#define loadscalar(ptype)                                                                          \
  else if (type == demangle(typeid(ptype).name())) do                                              \
  {                                                                                                \
    ptype & value = p.set<ptype>(key);                                                             \
    loadHelper(stream, value, context);                                                            \
  }                                                                                                \
  while (0)
    if (false)
      ;
    loadscalar(Real);
    loadscalar(short);
    loadscalar(int);
    loadscalar(long);
    loadscalar(unsigned short);
    loadscalar(unsigned int);
    loadscalar(unsigned long);
#undef loadscalar
  }
}
dataLoad() [13/41]
template<> void dataLoad (std::istream & stream, Node *& e, void * context)
Definition at line 444 of file DataIO.C.
{
  if (!context)
    mooseError("Can only load Node objects using a MooseMesh context!");
  MooseMesh * mesh = static_cast<MooseMesh *>(context);
  // TODO: Write out the unique ID of this nodeent
  dof_id_type id = libMesh::DofObject::invalid_id;
  loadHelper(stream, id, context);
  if (id != libMesh::DofObject::invalid_id)
    n = mesh->nodePtr(id);
  else
    n = NULL;
}
dataLoad() [14/41]
template<typename T > void dataLoad (std::istream & stream, NumericVector< T > & v, void * context)
Definition at line 685 of file DataIO.h.
{
  numeric_index_type size = v.local_size();
  for (numeric_index_type i = v.first_local_index(); i < v.first_local_index() + size; i++)
  {
    T r = 0;
    dataLoad(stream, r, context);
    v.set(i, r);
  }
  v.close();
}
dataLoad() [15/41]
void dataLoad (std::istream & stream, Point & p, void * context)
Definition at line 566 of file DataIO.C.
{
  for (const auto i : make_range(Moose::dim))
  {
    Real r = 0;
    dataLoad(stream, r, context);
    p(i) = r;
  }
}
dataLoad() [16/41]
template<typename T > void dataLoad (std::istream & stream, RankFourTensorTempl< T > & rft, void * context)
Definition at line 740 of file DataIO.h.
{
  dataLoad(stream, rft._vals, context);
}
dataLoad() [17/41]
template<typename T > void dataLoad (std::istream & stream, RankThreeTensorTempl< T > & rtt, void * context)
Definition at line 733 of file DataIO.h.
{
  dataLoad(stream, rtt._vals, context);
}
dataLoad() [18/41]
template<typename T > void dataLoad (std::istream & stream, RankTwoTensorTempl< T > & rtt, void * context)
Definition at line 726 of file DataIO.h.
{
  dataLoad(stream, rtt._coords, context);
}
dataLoad() [19/41]
template<> void dataLoad (std::istream & stream, Real & v, void *)
Definition at line 318 of file DataIO.C.
{
  stream.read((char *)&v, sizeof(v));
}
Referenced by dataLoad().
dataLoad() [20/41]
template<> void dataLoad (std::istream & stream, RealEigenMatrix & v, void * context)
Definition at line 494 of file DataIO.C.
{
  unsigned int m = 0;
  stream.read((char *)&m, sizeof(m));
  unsigned int n = 0;
  stream.read((char *)&n, sizeof(n));
  v.resize(m, n);
  for (unsigned int i = 0; i < m; i++)
    for (unsigned int j = 0; j < n; j++)
    {
      Real r = 0;
      dataLoad(stream, r, context);
      v(i, j) = r;
    }
}
dataLoad() [21/41]
template<> void dataLoad (std::istream & stream, RealEigenVector & v, void * context)
Definition at line 479 of file DataIO.C.
{
  unsigned int n = 0;
  stream.read((char *)&n, sizeof(n));
  v.resize(n);
  for (unsigned int i = 0; i < n; i++)
  {
    Real r = 0;
    dataLoad(stream, r, context);
    v(i) = r;
  }
}
dataLoad() [22/41]
template<std::size_t N> void dataLoad (std::istream & stream, std::array< DualReal, N > & dn, void * context) inline
Definition at line 669 of file DataIO.h.
{
  for (std::size_t i = 0; i < N; ++i)
    dataLoad(stream, dn[i], context);
}
dataLoad() [23/41]
template<typename T > void dataLoad (std::istream & stream, std::deque< T > & l, void * context) inline
Definition at line 563 of file DataIO.h.
{
  // First read the size of the container
  unsigned int size = 0;
  dataLoad(stream, size, nullptr);
  for (unsigned int i = 0; i < size; i++)
  {
    T data;
    loadHelper(stream, data, context);
    l.push_back(std::move(data));
  }
}
dataLoad() [24/41]
template<typename T > void dataLoad (std::istream & stream, std::list< T > & l, void * context) inline
Definition at line 547 of file DataIO.h.
{
  // First read the size of the set
  unsigned int size = 0;
  dataLoad(stream, size, nullptr);
  for (unsigned int i = 0; i < size; i++)
  {
    T data;
    loadHelper(stream, data, context);
    l.push_back(std::move(data));
  }
}
dataLoad() [25/41]
template<typename T , typename U > void dataLoad (std::istream & stream, std::map< T, U > & m, void * context) inline
Definition at line 579 of file DataIO.h.
{
  m.clear();
  // First read the size of the map
  unsigned int size = 0;
  dataLoad(stream, size, nullptr);
  for (unsigned int i = 0; i < size; i++)
  {
    T key;
    loadHelper(stream, key, context);
    U & value = m[key];
    loadHelper(stream, value, context);
  }
}
dataLoad() [26/41]
template<typename T , typename U > void dataLoad (std::istream & stream, std::pair< T, U > & p, void * context) inline
Definition at line 491 of file DataIO.h.
{
  loadHelper(stream, p.first, context);
  loadHelper(stream, p.second, context);
}
dataLoad() [27/41]
template<typename T > void dataLoad (std::istream & stream, std::set< T > & s, void * context) inline
Definition at line 531 of file DataIO.h.
{
  // First read the size of the set
  unsigned int size = 0;
  dataLoad(stream, size, nullptr);
  for (unsigned int i = 0; i < size; i++)
  {
    T data;
    loadHelper(stream, data, context);
    s.insert(std::move(data));
  }
}
dataLoad() [28/41]
template<typename T > void dataLoad (std::istream & stream, std::shared_ptr< T > & v, void * context) inline
Definition at line 513 of file DataIO.h.
{
  T * tmp = v.get();
  loadHelper(stream, tmp, context);
}
dataLoad() [29/41]
template<> void dataLoad (std::istream & stream, std::string & v, void *)
Definition at line 325 of file DataIO.C.
{
  // Read the size of the string
  unsigned int size = 0;
  stream.read((char *)&size, sizeof(size));
  // Resize the string data
  v.resize(size);
  // Read the string
  stream.read(&v[0], sizeof(char) * size);
}
dataLoad() [30/41]
template<> void dataLoad (std::istream & stream, std::stringstream & s, void * context)
Definition at line 464 of file DataIO.C.
{
  size_t s_size = 0;
  stream.read((char *)&s_size, sizeof(s_size));
  std::unique_ptr<char[]> s_s = std::make_unique<char[]>(s_size);
  stream.read(s_s.get(), s_size);
  // Clear the stringstream before loading new data into it.
  s.str(std::string());
  s.write(s_s.get(), s_size);
}
dataLoad() [31/41]
template<typename T > void dataLoad (std::istream & stream, std::unique_ptr< T > & v, void * context) inline
Definition at line 522 of file DataIO.h.
{
  T * tmp = v.get();
  loadHelper(stream, tmp, context);
}
dataLoad() [32/41]
template<typename T , typename U > void dataLoad (std::istream & stream, std::unordered_map< T, U > & m, void * context) inline
Definition at line 599 of file DataIO.h.
{
  m.clear();
  // First read the size of the map
  unsigned int size = 0;
  dataLoad(stream, size, nullptr);
  for (unsigned int i = 0; i < size; i++)
  {
    T key;
    loadHelper(stream, key, context);
    U & value = m[key];
    loadHelper(stream, value, context);
  }
}
dataLoad() [33/41]
template<> void dataLoad (std::istream & stream, std::vector< bool > & v, void * context)
Definition at line 355 of file DataIO.C.
{
  for (bool b : v)
    dataLoad(stream, b, context);
}
dataLoad() [34/41]
template<typename T > void dataLoad (std::istream & stream, std::vector< T > & v, void * context) inline
Definition at line 499 of file DataIO.h.
{
  // First read the size of the vector
  unsigned int size = 0;
  dataLoad(stream, size, nullptr);
  v.resize(size);
  for (unsigned int i = 0; i < size; i++)
    loadHelper(stream, v[i], context);
}
dataLoad() [35/41]
template<typename T > void dataLoad (std::istream & stream, SymmetricRankFourTensorTempl< T > & rft, void * context)
Definition at line 754 of file DataIO.h.
{
  dataLoad(stream, rft._vals, context);
}
dataLoad() [36/41]
template<typename T > void dataLoad (std::istream & stream, SymmetricRankTwoTensorTempl< T > & rtt, void * context)
Definition at line 747 of file DataIO.h.
{
  dataLoad(stream, rtt._vals, context);
}
dataLoad() [37/41]
template<typename T > void dataLoad (std::istream & stream, T & v, void *) inline
Definition at line 474 of file DataIO.h.
{
  stream.read((char *)&v, sizeof(v));
  mooseAssert(!stream.bad(), "Failed to load");
}
Referenced by dataLoad(), dataLoadSkip(), dataLoadSkippable(), and loadHelper().
dataLoad() [38/41]
template<typename T > void dataLoad (std::istream & stream, TensorValue< T > & v, void * context)
Definition at line 512 of file DataIO.C.
{
  // Obviously if someone loads data with different LIBMESH_DIM than was used for saving them, it
  // won't work.
  for (const auto i : make_range(Moose::dim))
    for (const auto j : make_range(Moose::dim))
    {
      T r = 0;
      dataLoad(stream, r, context);
      v(i, j) = r;
    }
}
dataLoad() [39/41]
template<> void dataLoad (std::istream & stream, VariableName & v, void * context)
Definition at line 340 of file DataIO.C.
{
  auto & name = static_cast<std::string &>(v);
  dataLoad(stream, name, context);
}
dataLoad() [40/41]
template<> void dataLoad (std::istream & stream, Vec & v, void * context)
Definition at line 616 of file DataIO.C.
{
  PetscInt local_size;
  VecGetLocalSize(v, &local_size);
  PetscScalar * array;
  VecGetArray(v, &array);
  for (PetscInt i = 0; i < local_size; i++)
    dataLoad(stream, array[i], context);
  VecRestoreArray(v, &array);
}
dataLoad() [41/41]
template<typename T > void dataLoad (std::istream & stream, VectorValue< T > & v, void * context)
Definition at line 550 of file DataIO.C.
{
  // Obviously if someone loads data with different LIBMESH_DIM than was used for saving them, it
  // won't work.
  for (const auto i : make_range(Moose::dim))
  {
    T r = 0;
    dataLoad(stream, r, context);
    v(i) = r;
  }
}
dataLoadSkip()
void dataLoadSkip (std::istream & stream) inline
Skips a piece of "skippable" data.
See dataStoreSkippable.
Definition at line 1017 of file DataIO.h.
{
  std::size_t data_stream_size;
  dataLoad(stream, data_stream_size, nullptr);
  stream.seekg(data_stream_size, std::ios::cur);
}
dataLoadSkippable()
template<typename T > void dataLoadSkippable (std::istream & stream, T & v, void * context) inline
Loads a piece of "skippable" data.
See dataStoreSkippable.
Definition at line 1005 of file DataIO.h.
{
  std::size_t data_stream_size;
  dataLoad(stream, data_stream_size, nullptr);
  std::stringstream data_stream;
  dataLoad(stream, data_stream, nullptr);
  dataLoad(data_stream, v, context);
}
dataStore() [1/41]
template<typename T > void dataStore (std::ostream & , T *& , void *) inline
Definition at line 176 of file DataIO.h.
{
  mooseError("Attempting to store a raw pointer type: \"",
             demangle(typeid(T).name()),
             " *\" as restartable data!\nWrite a custom dataStore() template specialization!\n\n");
}
dataStore() [2/41]
template<> void dataStore (std::ostream & stream, bool & v, void * context)
Definition at line 53 of file DataIO.C.
{
  stream.write((char *)&v, sizeof(v));
}
dataStore() [3/41]
template<typename T > void dataStore (std::ostream & stream, ColumnMajorMatrixTempl< T > & cmm, void * context)
Definition at line 465 of file DataIO.h.
{
  dataStore(stream, cmm._values, context);
}
dataStore() [4/41]
template<> void dataStore (std::ostream & stream, const Elem *& e, void * context)
Definition at line 108 of file DataIO.C.
{
  // TODO: Write out the unique ID of this elem
  dof_id_type id = libMesh::DofObject::invalid_id;
  if (e)
  {
    id = e->id();
    if (id == libMesh::DofObject::invalid_id)
      mooseError("Can't output Elems with invalid ids!");
  }
  storeHelper(stream, id, context);
}
dataStore() [5/41]
template<> void dataStore (std::ostream & stream, const Node *& n, void * context)
Definition at line 125 of file DataIO.C.
{
  // TODO: Write out the unique ID of this node
  dof_id_type id = libMesh::DofObject::invalid_id;
  if (n)
  {
    id = n->id();
    if (id == libMesh::DofObject::invalid_id)
      mooseError("Can't output Nodes with invalid ids!");
  }
  storeHelper(stream, id, context);
}
dataStore() [6/41]
template<typename T > void dataStore (std::ostream & stream, DenseMatrix< T > & v, void * context)
Definition at line 232 of file DataIO.C.
{
  unsigned int m = v.m();
  unsigned int n = v.n();
  stream.write((char *)&m, sizeof(m));
  stream.write((char *)&n, sizeof(n));
  for (unsigned int i = 0; i < m; i++)
    for (unsigned int j = 0; j < n; j++)
    {
      T r = v(i, j);
      dataStore(stream, r, context);
    }
}
dataStore() [7/41]
template<typename T > void dataStore (std::ostream & stream, DenseVector< T > & v, void * context)
Definition at line 408 of file DataIO.h.
{
  unsigned int m = v.size();
  dataStore(stream, m, nullptr);
  for (unsigned int i = 0; i < v.size(); i++)
  {
    T r = v(i);
    dataStore(stream, r, context);
  }
}
dataStore() [8/41]
template<> void dataStore (std::ostream & stream, DualReal & dn, void * context)
Definition at line 89 of file DataIO.C.
{
  dataStore(stream, dn.value(), context);
  if (DualReal::do_derivatives)
  {
    auto & derivatives = dn.derivatives();
    std::size_t size = derivatives.size();
    dataStore(stream, size, context);
    for (MooseIndex(size) i = 0; i < size; ++i)
    {
      dataStore(stream, derivatives.raw_index(i), context);
      dataStore(stream, derivatives.raw_at(i), context);
    }
  }
}
dataStore() [9/41]
template<std::size_t N> void dataStore (std::ostream & stream, DualReal(&) dn[N], void * context) inline
Definition at line 382 of file DataIO.h.
{
  for (std::size_t i = 0; i < N; ++i)
    dataStore(stream, dn[i], context);
}
dataStore() [10/41]
template<> void dataStore (std::ostream & stream, Elem *& e, void * context)
Definition at line 142 of file DataIO.C.
{
  // TODO: Write out the unique ID of this elem
  dof_id_type id = libMesh::DofObject::invalid_id;
  if (e)
  {
    id = e->id();
    if (id == libMesh::DofObject::invalid_id)
      mooseError("Can't output Elems with invalid ids!");
  }
  storeHelper(stream, id, context);
}
dataStore() [11/41]
template<typename T , typename U > void dataStore (std::ostream & stream, HashMap< T, U > & m, void * context) inline
Definition at line 321 of file DataIO.h.
{
  // First store the size of the map
  unsigned int size = m.size();
  dataStore(stream, size, nullptr);
  typename HashMap<T, U>::iterator it = m.begin();
  typename HashMap<T, U>::iterator end = m.end();
  for (; it != end; ++it)
  {
    T & key = const_cast<T &>(it->first);
    storeHelper(stream, key, context);
    storeHelper(stream, it->second, context);
  }
}
dataStore() [12/41]
template<> void dataStore (std::ostream & stream, libMesh::Parameters & p, void * context)
Definition at line 277 of file DataIO.C.
{
  // First store the size of the map
  unsigned int size = p.n_parameters();
  stream.write((char *)&size, sizeof(size));
  auto it = p.begin();
  auto end = p.end();
  for (; it != end; ++it)
  {
    auto & key = const_cast<std::string &>(it->first);
    auto type = it->second->type();
    storeHelper(stream, key, context);
    storeHelper(stream, type, context);
#define storescalar(ptype)                                                                         \
  else if (it->second->type() == demangle(typeid(ptype).name())) storeHelper(                      \
      stream,                                                                                      \
      (dynamic_cast<libMesh::Parameters::Parameter<ptype> *>(MooseUtils::get(it->second)))->get(), \
      context)
    if (false)
      ;
    storescalar(Real);
    storescalar(short);
    storescalar(int);
    storescalar(long);
    storescalar(unsigned short);
    storescalar(unsigned int);
    storescalar(unsigned long);
#undef storescalar
  }
}
dataStore() [13/41]
template<> void dataStore (std::ostream & stream, Node *& n, void * context)
Definition at line 159 of file DataIO.C.
{
  // TODO: Write out the unique ID of this node
  dof_id_type id = libMesh::DofObject::invalid_id;
  if (n)
  {
    id = n->id();
    if (id == libMesh::DofObject::invalid_id)
      mooseError("Can't output Nodes with invalid ids!");
  }
  storeHelper(stream, id, context);
}
dataStore() [14/41]
template<typename T > void dataStore (std::ostream & stream, NumericVector< T > & v, void * context)
Definition at line 390 of file DataIO.h.
{
  v.close();
  numeric_index_type size = v.local_size();
  for (numeric_index_type i = v.first_local_index(); i < v.first_local_index() + size; i++)
  {
    T r = v(i);
    dataStore(stream, r, context);
  }
}
dataStore() [15/41]
void dataStore (std::ostream & stream, Point & p, void * context)
Definition at line 266 of file DataIO.C.
{
  for (const auto i : make_range(Moose::dim))
  {
    Real r = p(i);
    dataStore(stream, r, context);
  }
}
dataStore() [16/41]
template<typename T > void dataStore (std::ostream & stream, RankFourTensorTempl< T > & rft, void * context)
Definition at line 444 of file DataIO.h.
{
  dataStore(stream, rft._vals, context);
}
dataStore() [17/41]
template<typename T > void dataStore (std::ostream & stream, RankThreeTensorTempl< T > & rtt, void * context)
Definition at line 437 of file DataIO.h.
{
  dataStore(stream, rtt._vals, context);
}
dataStore() [18/41]
template<typename T > void dataStore (std::ostream & stream, RankTwoTensorTempl< T > & rtt, void * context)
Definition at line 430 of file DataIO.h.
{
  dataStore(stream, rtt._coords, context);
}
dataStore() [19/41]
template<> void dataStore (std::ostream & stream, Real & v, void * context)
Definition at line 26 of file DataIO.C.
{
  stream.write((char *)&v, sizeof(v));
}
Referenced by dataStore().
dataStore() [20/41]
template<> void dataStore (std::ostream & stream, RealEigenMatrix & v, void * context)
Definition at line 201 of file DataIO.C.
{
  unsigned int m = v.rows();
  stream.write((char *)&m, sizeof(m));
  unsigned int n = v.cols();
  stream.write((char *)&n, sizeof(n));
  for (unsigned int i = 0; i < m; i++)
    for (unsigned int j = 0; j < n; j++)
    {
      Real r = v(i, j);
      dataStore(stream, r, context);
    }
}
dataStore() [21/41]
template<> void dataStore (std::ostream & stream, RealEigenVector & v, void * context)
Definition at line 188 of file DataIO.C.
{
  unsigned int m = v.size();
  stream.write((char *)&m, sizeof(m));
  for (unsigned int i = 0; i < v.size(); i++)
  {
    Real r = v(i);
    dataStore(stream, r, context);
  }
}
dataStore() [22/41]
template<std::size_t N> void dataStore (std::ostream & stream, std::array< DualReal, N > & dn, void * context) inline
Definition at line 374 of file DataIO.h.
{
  for (std::size_t i = 0; i < N; ++i)
    dataStore(stream, dn[i], context);
}
dataStore() [23/41]
template<typename T > void dataStore (std::ostream & stream, std::deque< T > & l, void * context) inline
Definition at line 261 of file DataIO.h.
{
  // First store the size of the container
  unsigned int size = l.size();
  dataStore(stream, size, nullptr);
  typename std::deque<T>::iterator it = l.begin();
  typename std::deque<T>::iterator end = l.end();
  for (; it != end; ++it)
  {
    T & x = const_cast<T &>(*it);
    storeHelper(stream, x, context);
  }
}
dataStore() [24/41]
template<typename T > void dataStore (std::ostream & stream, std::list< T > & l, void * context) inline
Definition at line 243 of file DataIO.h.
{
  // First store the size of the set
  unsigned int size = l.size();
  dataStore(stream, size, nullptr);
  typename std::list<T>::iterator it = l.begin();
  typename std::list<T>::iterator end = l.end();
  for (; it != end; ++it)
  {
    T & x = const_cast<T &>(*it);
    storeHelper(stream, x, context);
  }
}
dataStore() [25/41]
template<typename T , typename U > void dataStore (std::ostream & stream, std::map< T, U > & m, void * context) inline
Definition at line 279 of file DataIO.h.
{
  // First store the size of the map
  unsigned int size = m.size();
  dataStore(stream, size, nullptr);
  typename std::map<T, U>::iterator it = m.begin();
  typename std::map<T, U>::iterator end = m.end();
  for (; it != end; ++it)
  {
    T & key = const_cast<T &>(it->first);
    storeHelper(stream, key, context);
    storeHelper(stream, it->second, context);
  }
}
dataStore() [26/41]
template<typename T , typename U > void dataStore (std::ostream & stream, std::pair< T, U > & p, void * context) inline
Definition at line 187 of file DataIO.h.
{
  storeHelper(stream, p.first, context);
  storeHelper(stream, p.second, context);
}
dataStore() [27/41]
template<typename T > void dataStore (std::ostream & stream, std::set< T > & s, void * context) inline
Definition at line 225 of file DataIO.h.
{
  // First store the size of the set
  unsigned int size = s.size();
  dataStore(stream, size, nullptr);
  typename std::set<T>::iterator it = s.begin();
  typename std::set<T>::iterator end = s.end();
  for (; it != end; ++it)
  {
    T & x = const_cast<T &>(*it);
    storeHelper(stream, x, context);
  }
}
dataStore() [28/41]
template<typename T > void dataStore (std::ostream & stream, std::shared_ptr< T > & v, void * context) inline
Definition at line 207 of file DataIO.h.
{
  T * tmp = v.get();
  storeHelper(stream, tmp, context);
}
dataStore() [29/41]
template<> void dataStore (std::ostream & stream, std::string & v, void * context)
Definition at line 33 of file DataIO.C.
{
  // Write the size of the string
  unsigned int size = v.size();
  stream.write((char *)&size, sizeof(size));
  // Write the string (Do not store the null byte)
  stream.write(v.c_str(), sizeof(char) * size);
}
dataStore() [30/41]
template<> void dataStore (std::ostream & stream, std::stringstream & s, void * context)
Definition at line 176 of file DataIO.C.
{
  const std::string & s_str = s.str();
  size_t s_size = s_str.size();
  stream.write((char *)&s_size, sizeof(s_size));
  stream.write(s_str.c_str(), sizeof(char) * (s_str.size()));
}
dataStore() [31/41]
template<typename T > void dataStore (std::ostream & stream, std::unique_ptr< T > & v, void * context) inline
Definition at line 216 of file DataIO.h.
{
  T * tmp = v.get();
  storeHelper(stream, tmp, context);
}
dataStore() [32/41]
template<typename T , typename U > void dataStore (std::ostream & stream, std::unordered_map< T, U > & m, void * context) inline
Definition at line 300 of file DataIO.h.
{
  // First store the size of the map
  unsigned int size = m.size();
  dataStore(stream, size, nullptr);
  typename std::unordered_map<T, U>::iterator it = m.begin();
  typename std::unordered_map<T, U>::iterator end = m.end();
  for (; it != end; ++it)
  {
    T & key = const_cast<T &>(it->first);
    storeHelper(stream, key, context);
    storeHelper(stream, it->second, context);
  }
}
dataStore() [33/41]
template<> void dataStore (std::ostream & stream, std::vector< bool > & v, void * context)
Definition at line 60 of file DataIO.C.
{
  for (bool b : v)
    dataStore(stream, b, context);
}
dataStore() [34/41]
template<typename T > void dataStore (std::ostream & stream, std::vector< T > & v, void * context) inline
Definition at line 195 of file DataIO.h.
{
  // First store the size of the vector
  unsigned int size = v.size();
  dataStore(stream, size, nullptr);
  for (unsigned int i = 0; i < size; i++)
    storeHelper(stream, v[i], context);
}
dataStore() [35/41]
template<typename T > void dataStore (std::ostream & stream, SymmetricRankFourTensorTempl< T > & srft, void * context)
Definition at line 458 of file DataIO.h.
{
  dataStore(stream, srft._vals, context);
}
dataStore() [36/41]
template<typename T > void dataStore (std::ostream & stream, SymmetricRankTwoTensorTempl< T > & srtt, void * context)
Definition at line 451 of file DataIO.h.
{
  dataStore(stream, srtt._vals, context);
}
dataStore() [37/41]
template<typename T > void dataStore (std::ostream & stream, T & v, void *) inline
Definition at line 157 of file DataIO.h.
{
#ifdef LIBMESH_HAVE_CXX11_TYPE_TRAITS
  static_assert(std::is_polymorphic<T>::value == false,
                "Cannot serialize a class that has virtual "
                "members!\nWrite a custom dataStore() "
                "template specialization!\n\n");
  static_assert(std::is_trivially_copyable<T>::value,
                "Cannot serialize a class that is not trivially copyable!\nWrite a custom "
                "dataStore() template specialization!\n\n");
#endif
  // Moose::out<<"Generic dataStore"<<std::endl;
  stream.write((char *)&v, sizeof(v));
  mooseAssert(!stream.bad(), "Failed to store");
}
Referenced by dataStore(), dataStoreSkippable(), and storeHelper().
dataStore() [38/41]
template<typename T > void dataStore (std::ostream & stream, TensorValue< T > & v, void * context)
Definition at line 217 of file DataIO.C.
{
  for (const auto i : make_range(Moose::dim))
    for (const auto j : make_range(Moose::dim))
    {
      T r = v(i, j);
      dataStore(stream, r, context);
    }
}
dataStore() [39/41]
template<> void dataStore (std::ostream & stream, VariableName & v, void * context)
Definition at line 45 of file DataIO.C.
{
  auto & name = static_cast<std::string &>(v);
  dataStore(stream, name, context);
}
dataStore() [40/41]
template<> void dataStore (std::ostream & stream, Vec & v, void * context)
Definition at line 630 of file DataIO.C.
{
  PetscInt local_size;
  VecGetLocalSize(v, &local_size);
  PetscScalar * array;
  VecGetArray(v, &array);
  for (PetscInt i = 0; i < local_size; i++)
    dataStore(stream, array[i], context);
  VecRestoreArray(v, &array);
}
dataStore() [41/41]
template<typename T > void dataStore (std::ostream & stream, VectorValue< T > & v, void * context)
Definition at line 251 of file DataIO.C.
{
  // Obviously if someone loads data with different LIBMESH_DIM than was used for saving them, it
  // won't work.
  for (const auto i : make_range(Moose::dim))
  {
    T r = v(i);
    dataStore(stream, r, context);
  }
}
dataStoreSkippable()
template<typename T > void dataStoreSkippable (std::ostream & stream, T & v, void * context) inline
Stores the data v in a "skippable" sense.
That is, when it is loaded, its data can be skipped through.
The resulting data must be loaded with dataLoadSkippable or dataLoadSkip.
Definition at line 989 of file DataIO.h.
{
  std::stringstream data_stream;
  dataStore(data_stream, v, context);
  // We have an extra std::size_t value because the store of
  // std::stringstream also stores the size
  std::size_t data_stream_size =
      static_cast<std::size_t>(data_stream.tellp()) + sizeof(std::size_t);
  dataStore(stream, data_stream_size, nullptr);
  dataStore(stream, data_stream, nullptr);
}
loadHelper() [1/8]
template<typename P , typename Q > void loadHelper (std::istream & stream, HashMap< P, Q > & data, void * context) inline
Hashmap helper routine.
Definition at line 889 of file DataIO.h.
{
  dataLoad(stream, data, context);
}
loadHelper() [2/8]
template<typename P > void loadHelper (std::istream & stream, P & data, void * context) inline
Scalar helper routine.
Definition at line 833 of file DataIO.h.
{
  dataLoad(stream, data, context);
}
Referenced by dataLoad(), MaterialPropertyBase< T, is_ad >::load(), RestartableData< T >::loadInternal(), and ReporterState< T >::loadInternal().
loadHelper() [3/8]
template<typename P , typename Q > void loadHelper (std::istream & stream, std::map< P, Q > & data, void * context) inline
Map helper routine.
Definition at line 873 of file DataIO.h.
{
  dataLoad(stream, data, context);
}
loadHelper() [4/8]
template<typename P > void loadHelper (std::istream & stream, std::set< P > & data, void * context) inline
Set helper routine.
Definition at line 865 of file DataIO.h.
{
  dataLoad(stream, data, context);
}
loadHelper() [5/8]
template<typename P > void loadHelper (std::istream & stream, std::shared_ptr< P > & data, void * context) inline
Shared Pointer helper routine.
Definition at line 849 of file DataIO.h.
{
  dataLoad(stream, data, context);
}
loadHelper() [6/8]
template<typename P > void loadHelper (std::istream & stream, std::unique_ptr< P > & data, void * context) inline
Unique Pointer helper routine.
Definition at line 857 of file DataIO.h.
{
  dataLoad(stream, data, context);
}
loadHelper() [7/8]
template<typename P , typename Q > void loadHelper (std::istream & stream, std::unordered_map< P, Q > & data, void * context) inline
Unordered_map helper routine.
Definition at line 881 of file DataIO.h.
{
  dataLoad(stream, data, context);
}
loadHelper() [8/8]
template<typename P > void loadHelper (std::istream & stream, std::vector< P > & data, void * context) inline
Vector helper routine.
Definition at line 841 of file DataIO.h.
{
  dataLoad(stream, data, context);
}
storeHelper() [1/8]
template<typename P , typename Q > void storeHelper (std::ostream & stream, HashMap< P, Q > & data, void * context) inline
HashMap helper routine.
Definition at line 825 of file DataIO.h.
{
  dataStore(stream, data, context);
}
storeHelper() [2/8]
template<typename P > void storeHelper (std::ostream & stream, P & data, void * context) inline
Scalar helper routine.
Definition at line 769 of file DataIO.h.
{
  dataStore(stream, data, context);
}
Referenced by dataStore(), MaterialPropertyBase< T, is_ad >::store(), RestartableData< T >::storeInternal(), and ReporterState< T >::storeInternal().
storeHelper() [3/8]
template<typename P , typename Q > void storeHelper (std::ostream & stream, std::map< P, Q > & data, void * context) inline
Map helper routine.
Definition at line 809 of file DataIO.h.
{
  dataStore(stream, data, context);
}
storeHelper() [4/8]
template<typename P > void storeHelper (std::ostream & stream, std::set< P > & data, void * context) inline
Set helper routine.
Definition at line 801 of file DataIO.h.
{
  dataStore(stream, data, context);
}
storeHelper() [5/8]
template<typename P > void storeHelper (std::ostream & stream, std::shared_ptr< P > & data, void * context) inline
Shared pointer helper routine.
Definition at line 785 of file DataIO.h.
{
  dataStore(stream, data, context);
}
storeHelper() [6/8]
template<typename P > void storeHelper (std::ostream & stream, std::unique_ptr< P > & data, void * context) inline
Unique pointer helper routine.
Definition at line 793 of file DataIO.h.
{
  dataStore(stream, data, context);
}
storeHelper() [7/8]
template<typename P , typename Q > void storeHelper (std::ostream & stream, std::unordered_map< P, Q > & data, void * context) inline
Unordered_map helper routine.
Definition at line 817 of file DataIO.h.
{
  dataStore(stream, data, context);
}
storeHelper() [8/8]
template<typename P > void storeHelper (std::ostream & stream, std::vector< P > & data, void * context) inline
Vector helper routine.
Definition at line 777 of file DataIO.h.
{
  dataStore(stream, data, context);
}