Zapdos: moose/framework/src/utils/FormattedTable.C File Reference
FormattedTable.C File Reference
Namespaces
namespace gnuplot
Functions
template<>
void dataStore (std::ostream &stream, FormattedTable &table, void *context)
template<>
void dataLoad (std::istream &stream, FormattedTable &table, void *context)
template<>
void dataStore (std::ostream &stream, std::shared_ptr< TableValueBase > &value_base, void *context)
template<>
void dataLoad (std::istream &stream, std::shared_ptr< TableValueBase > &value_base, void *context)
std::ostream & operator<< (std::ostream &os, const TableValueBase &value)
Variables
const unsigned short DEFAULT_CSV_PRECISION = 14
const std::string DEFAULT_CSV_DELIMITER = ","
const std::string gnuplot::before_terminal = "set terminal "
const std::string gnuplot::before_ext = "\nset output 'all"
const std::string gnuplot::after_ext
Function Documentation
dataLoad() [1/2]
template<> void dataLoad (std::istream & stream, FormattedTable & table, void * context)
Definition at line 39 of file FormattedTable.C.
{
  loadHelper(stream, table._data, context);
  loadHelper(stream, table._align_widths, context);
  loadHelper(stream, table._column_names, context);
  loadHelper(stream, table._output_row_index, context);
  loadHelper(stream, table._headers_output, context);
}
Referenced by dataLoad(), and TableValue< T >::load().
dataLoad() [2/2]
template<> void dataLoad (std::istream & stream, std::shared_ptr< TableValueBase > & value_base, void * context)
Definition at line 57 of file FormattedTable.C.
{
  std::string type;
  dataLoad(stream, type, context);
  if (type == typeid(bool).name())
    TableValue<bool>::load(stream, value_base, context);
  else if (type == typeid(unsigned short int).name())
    TableValue<unsigned short int>::load(stream, value_base, context);
  else if (type == typeid(unsigned int).name())
    TableValue<unsigned int>::load(stream, value_base, context);
  else if (type == typeid(unsigned long int).name())
    TableValue<unsigned long int>::load(stream, value_base, context);
  else if (type == typeid(unsigned long long int).name())
    TableValue<unsigned long long int>::load(stream, value_base, context);
  else if (type == typeid(short int).name())
    TableValue<short int>::load(stream, value_base, context);
  else if (type == typeid(int).name())
    TableValue<int>::load(stream, value_base, context);
  else if (type == typeid(long int).name())
    TableValue<long int>::load(stream, value_base, context);
  else if (type == typeid(long long int).name())
    TableValue<long long int>::load(stream, value_base, context);
  else if (type == typeid(float).name())
    TableValue<float>::load(stream, value_base, context);
  else if (type == typeid(double).name())
    TableValue<double>::load(stream, value_base, context);
  else if (type == typeid(long double).name())
    TableValue<long double>::load(stream, value_base, context);
  else if (type == typeid(char).name())
    TableValue<char>::load(stream, value_base, context);
  else if (type == typeid(char *).name())
    TableValue<char *>::load(stream, value_base, context);
  else if (type == typeid(std::string).name())
    TableValue<std::string>::load(stream, value_base, context);
  else
    mooseError("Unsupported table value type ", demangle(type.c_str()));
}
dataStore() [1/2]
template<> void dataStore (std::ostream & stream, FormattedTable & table, void * context)
Definition at line 27 of file FormattedTable.C.
{
  table.fillEmptyValues();
  storeHelper(stream, table._data, context);
  storeHelper(stream, table._align_widths, context);
  storeHelper(stream, table._column_names, context);
  storeHelper(stream, table._output_row_index, context);
  storeHelper(stream, table._headers_output, context);
}
Referenced by TableValue< T >::store().
dataStore() [2/2]
template<> void dataStore (std::ostream & stream, std::shared_ptr< TableValueBase > & value_base, void * context)
Definition at line 50 of file FormattedTable.C.
{
  value_base->store(stream, context);
}
operator<<()
std::ostream & operator<< (std::ostream & os, const TableValueBase & value)
Definition at line 596 of file FormattedTable.C.
{
  value.print(os);
  return os;
}
Variable Documentation
DEFAULT_CSV_DELIMITER
const std::string DEFAULT_CSV_DELIMITER = ","
Definition at line 23 of file FormattedTable.C.
DEFAULT_CSV_PRECISION
const unsigned short DEFAULT_CSV_PRECISION = 14
Definition at line 22 of file FormattedTable.C.