Zapdos: moose/framework/include/utils/FormattedTable.h File Reference
FormattedTable.h File Reference
Classes
class TableValueBase
class TableValue< T >
class FormattedTable
This class is used for building, formatting, and outputting tables of numbers.
Namespaces
namespace libMesh
The following methods are specializations for using the libMesh::Parallel::packed_range_* routines for std::strings.
Functions
template<>
void dataStore (std::ostream &stream, FormattedTable &table, void *context)
template<>
void dataLoad (std::istream &stream, FormattedTable &v, void *context)
template<>
void dataStore (std::ostream &stream, TableValueBase *&value, void *context)
template<>
void dataLoad (std::istream &stream, TableValueBase *&value, void *context)
std::ostream & operator<< (std::ostream &os, const TableValueBase &value)
template<>
void dataStore (std::ostream &stream, FormattedTable &table, void *context)
template<>
void dataLoad (std::istream &stream, FormattedTable &v, void *context)
template<>
void dataStore (std::ostream &stream, TableValueBase *&value, void *context)
template<>
void dataLoad (std::istream &stream, TableValueBase *&value, void *context)
Function Documentation
dataLoad() [1/4]
template<> void dataLoad (std::istream & stream, FormattedTable & v, void * context)
Definition at line 322 of file FormattedTable.C.
{
  loadHelper(stream, table._data, context);
  loadHelper(stream, table._align_widths, context);
  loadHelper(stream, table._column_names, context);
  loadHelper(stream, table._output_row_index, context);
  loadHelper(stream, table._headers_output, context);
}
Referenced by TableValue< T >::load().
dataLoad() [2/4]
template<> void dataLoad (std::istream & stream, FormattedTable & v, void * context)
Definition at line 322 of file FormattedTable.C.
{
  loadHelper(stream, table._data, context);
  loadHelper(stream, table._align_widths, context);
  loadHelper(stream, table._column_names, context);
  loadHelper(stream, table._output_row_index, context);
  loadHelper(stream, table._headers_output, context);
}
Referenced by dataLoad().
dataLoad() [3/4]
template<> void dataLoad (std::istream & stream, TableValueBase *& value, void * context)
dataLoad() [4/4]
template<> void dataLoad (std::istream & stream, TableValueBase *& value, void * context)
dataStore() [1/4]
template<> void dataStore (std::ostream & stream, FormattedTable & table, void * context)
Definition at line 320 of file FormattedTable.C.
{
  table.fillEmptyValues();
  storeHelper(stream, table._data, context);
  storeHelper(stream, table._align_widths, context);
  storeHelper(stream, table._column_names, context);
  storeHelper(stream, table._output_row_index, context);
  storeHelper(stream, table._headers_output, context);
}
Referenced by TableValue< T >::store().
dataStore() [2/4]
template<> void dataStore (std::ostream & stream, FormattedTable & table, void * context)
Definition at line 320 of file FormattedTable.C.
{
  table.fillEmptyValues();
  storeHelper(stream, table._data, context);
  storeHelper(stream, table._align_widths, context);
  storeHelper(stream, table._column_names, context);
  storeHelper(stream, table._output_row_index, context);
  storeHelper(stream, table._headers_output, context);
}
dataStore() [3/4]
template<> void dataStore (std::ostream & stream, TableValueBase *& value, void * context)
dataStore() [4/4]
template<> void dataStore (std::ostream & stream, TableValueBase *& value, void * context)
operator<<()
std::ostream & operator<< (std::ostream & os, const TableValueBase & value)
Definition at line 596 of file FormattedTable.C.
{
  value.print(os);
  return os;
}