Zapdos: moose/framework/include/utils/InputParameters.h File Reference
InputParameters.h File Reference
Classes
class FunctionParserBase< T >
class InputParameters
The main MOOSE class responsible for handling user-defined parameters in almost every MOOSE system.
struct InputParameters::Metadata
Functions
template<>
void InputParameters::addRequiredParam< std::vector< MooseEnum > > (const std::string &name, const std::vector< MooseEnum > &moose_enums, const std::string &doc_string)
template<>
void InputParameters::addParam< std::vector< MooseEnum > > (const std::string &, const std::string &)
template<>
void InputParameters::addDeprecatedParam< std::vector< MooseEnum > > (const std::string &name, const std::string &doc_string, const std::string &deprecation_message)
InputParameters emptyInputParameters ()
Variables
class FunctionParserBase Action
Function Documentation
emptyInputParameters()
InputParameters emptyInputParameters ()
Definition at line 1163 of file InputParameters.C.
{
  InputParameters params;
  return params;
}
Referenced by ConstantReporter::addReporterTypeParams(), Moose::FV::advectedInterpolationParameter(), OversampleOutput::cloneMesh(), CompositionDT::compositionDTParams(), AppFactory::createAppShared(), dummyParams(), AdvancedOutput::enableOutputTypes(), MooseServer::gatherDocumentCompletionItems(), MooseServer::gatherDocumentDefinitionLocations(), Moose::PetscSupport::getPetscValidParams(), Moose::SlepcSupport::getSlepcEigenProblemValidParams(), NearestPointBase< UserObjectType, BaseType >::NearestPointBase(), MooseApp::validParams(), MooseObject::validParams(), DistributionInterface::validParams(), FEProblemSolve::validParams(), FixedPointSolve::validParams(), ExecutorInterface::validParams(), FunctionInterface::validParams(), MooseParsedFunctionBase::validParams(), GeometricSearchInterface::validParams(), BlockRestrictable::validParams(), BoundaryRestrictable::validParams(), BoundaryRestrictableRequired::validParams(), ElementIDInterface::validParams(), FunctorInterface::validParams(), MeshChangedInterface::validParams(), MortarConsumerInterface::validParams(), OrientedBoxInterface::validParams(), OutputInterface::validParams(), PerfGraphInterface::validParams(), PostprocessorInterface::validParams(), RandomInterface::validParams(), SetupInterface::validParams(), TaggingInterface::validParams(), TransientInterface::validParams(), MaterialPropertyInterface::validParams(), ParsedMaterialBase::validParams(), Parser::validParams(), Reporter::validParams(), ReporterInterface::validParams(), SamplerInterface::validParams(), ReporterTransferInterface::validParams(), LayeredBase::validParams(), ShapeUserObject< T >::validParams(), UserObjectInterface::validParams(), FileRangeBuilder::validParams(), ImageSampler::validParams(), MeshBaseImageSampler::validParams(), MooseAppCoordTransform::validParams(), NestedSolveTempl< is_ad >::validParams(), NeighborCoupleableMooseVariableDependencyIntermediateInterface::validParams(), SamplerBase::validParams(), and VectorPostprocessorInterface::validParams().
InputParameters::addDeprecatedParam< std::vector< MooseEnum > >()
template<> void InputParameters::addDeprecatedParam< std::vector< MooseEnum > > (const std::string & name, const std::string & doc_string, const std::string & deprecation_message)
Definition at line 1089 of file InputParameters.C.
{
  mooseError("You must supply a vector of MooseEnum object(s) and the deprecation string when "
             "using addDeprecatedParam, even if the parameter is not required!");
}
InputParameters::addParam< std::vector< MooseEnum > >()
template<> void InputParameters::addParam< std::vector< MooseEnum > > (const std::string & , const std::string &)
Definition at line 1044 of file InputParameters.C.
{
  mooseError("You must supply a vector of MooseEnum object(s) when using addParam, even if the "
             "parameter is not required!");
}
InputParameters::addRequiredParam< std::vector< MooseEnum > >()
template<> void InputParameters::addRequiredParam< std::vector< MooseEnum > > (const std::string & name, const std::vector< MooseEnum > & moose_enums, const std::string & doc_string)
Definition at line 1012 of file InputParameters.C.
{
  InputParameters::set<std::vector<MooseEnum>>(name) =
      moose_enums; // valid parameter is set by set_attributes
  auto & metadata = _params[name];
  metadata._required = true;
  metadata._doc_string = doc_string;
}
Variable Documentation
Action
class FunctionParserBase Action