Zapdos: moose/framework/src/utils/LineSegment.C File Reference
LineSegment.C File Reference
Functions
void dataStore (std::ostream &stream, LineSegment &l, void *context)
void dataLoad (std::istream &stream, LineSegment &l, void *context)
void to_json (nlohmann::json &json, const LineSegment &l)
Function Documentation
dataLoad()
void dataLoad (std::istream & stream, LineSegment & l, void * context)
Definition at line 243 of file LineSegment.C.
{
  Point p0;
  dataLoad(stream, p0, context);
  Point p1;
  dataLoad(stream, p1, context);
  l.set(p0, p1);
}
Referenced by dataLoad().
dataStore()
void dataStore (std::ostream & stream, LineSegment & l, void * context)
Definition at line 236 of file LineSegment.C.
{
  dataStore(stream, l.start(), context);
  dataStore(stream, l.end(), context);
}
Referenced by dataStore().
to_json()
void to_json (nlohmann::json & json, const LineSegment & l)
Definition at line 253 of file LineSegment.C.
{
  to_json(json["start"], l.start());
  to_json(json["end"], l.end());
}
Referenced by to_json().