Zapdos: moose/framework/include/base/MooseError.h File Reference
MooseError.h File Reference
Namespaces
namespace MetaPhysicL
We need to instantiate the following CompareTypes to tell the compiler that ADReal is a subtype of ChainedADReal.
namespace moose
namespace moose::internal
Functions
template<size_t n, typename... T>
void print_tuple (std::ostream &os, const std::tuple< T... > &tup)
template<typename... T>
std::ostream & operator<< (std::ostream &os, const std::tuple< T... > &tup)
template<typename... Args>
void mooseError (Args &&... args)
Emit an error message with the given stringified, concatenated args and terminate the application.
std::string moose::internal::incompatVarMsg (MooseVariableFieldBase &var1, MooseVariableFieldBase &var2)
Builds and returns a string of the form:
std::string moose::internal::mooseMsgFmt (const std::string &msg, const std::string &title, const std::string &color)
Format a message for output with a title.
std::string moose::internal::mooseMsgFmt (const std::string &msg, const std::string &color)
Format a message for output without a title.
void moose::internal::mooseErrorRaw (std::string msg, const std::string prefix)
void moose::translateMetaPhysicLError (const MetaPhysicL::LogicError &)
emit a relatively clear error message when we catch a MetaPhysicL logic error
template<typename... Args>
void mooseWarning (Args &&... args)
Emit a warning message with the given stringified, concatenated args.
template<typename... Args>
void mooseUnused (Args &&... args)
Warning message used to notify the users of unused parts of their input files Really used internally by the parser and shouldn't really be called elsewhere.
template<typename... Args>
void mooseDeprecated (Args &&... args)
Emit a deprecated code/feature message with the given stringified, concatenated args.
template<typename... Args>
void mooseDeprecationExpired (Args &&... args)
Emit a deprecated code/feature message with the given stringified, concatenated args.
template<typename... Args>
void mooseInfo (Args &&... args)
Emit an informational message with the given stringified, concatenated args.
template<typename... Args>
void mooseInfoRepeated (Args &&... args)
Emit an informational message with the given stringified, concatenated args.
void moose::internal::mooseStreamAll (std::ostringstream &ss)
All of the following are not meant to be called directly - they are called by the normal macros (mooseError(), etc.) down below.
template<typename T , typename... Args>
void moose::internal::mooseStreamAll (std::ostringstream &ss, T &&val, Args &&... args)
template<typename S , typename... Args>
void moose::internal::mooseWarningStream (S &oss, Args &&... args)
template<typename S , typename... Args>
void moose::internal::mooseUnusedStream (S &oss, Args &&... args)
template<typename S , typename... Args>
void moose::internal::mooseInfoStreamRepeated (S &oss, Args &&... args)
template<typename S , typename... Args>
void moose::internal::mooseInfoStream (S &oss, Args &&... args)
template<typename S , typename... Args>
void moose::internal::mooseDeprecatedStream (S &oss, const bool expired, const bool print_title, Args &&... args)
Variables
Threads::spin_mutex moose::internal::moose_stream_lock
Function Documentation
mooseDeprecated()
template<typename... Args> void mooseDeprecated (Args &&... args)
Emit a deprecated code/feature message with the given stringified, concatenated args.
Definition at line 313 of file MooseError.h.
{
  moose::internal::mooseDeprecatedStream(Moose::out, false, true, std::forward<Args>(args)...);
}
Referenced by InputParameters::addDeprecatedCoupledVar(), Coupleable::adZeroGradient(), Coupleable::adZeroSecond(), Coupleable::adZeroValue(), ChangeOverTimestepPostprocessor::ChangeOverTimestepPostprocessor(), NonlinearSystemBase::computeResidual(), Factory::create(), MooseUtils::DelimitedFileReader::DelimitedFileReader(), Factory::deprecatedMessage(), MooseVariableFE< OutputType >::dofValue(), EigenProblem::EigenProblem(), UserForcingFunction::f(), FaceFaceConstraint::FaceFaceConstraint(), MooseUtils::DelimitedFileReader::getColumnData(), MooseUtils::DelimitedFileReader::getColumnNames(), Coupleable::getFEVar(), MooseApp::getRecoverFileBase(), Registry::getRegisteredName(), MooseApp::hasRecoverFileBase(), Syntax::isActionRequired(), MatDiffusionBase< T >::MatDiffusionBase(), MooseApp::MooseApp(), MultiAppNearestNodeTransfer::MultiAppNearestNodeTransfer(), MultiAppShapeEvaluationTransfer::MultiAppShapeEvaluationTransfer(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), NodalScalarKernel::NodalScalarKernel(), MooseEnum::operator!=(), MooseEnum::operator==(), InputParameters::paramSetByUser(), PercentChangePostprocessor::PercentChangePostprocessor(), ActionWarehouse::problem(), DerivativeMaterialPropertyNameInterface::propertyName(), DerivativeMaterialPropertyNameInterface::propertyNameFirst(), DerivativeMaterialPropertyNameInterface::propertyNameSecond(), DerivativeMaterialPropertyNameInterface::propertyNameThird(), RankTwoTensorTempl< T >::RankTwoTensorTempl(), ReferenceResidualProblem::ReferenceResidualProblem(), Moose::registerActions(), Moose::registerObjects(), NonlinearSystemBase::residualVector(), MooseUtils::DelimitedFileReader::setHeaderFlag(), Exodus::setOutputDimension(), MooseApp::setupOptions(), PointReduction::sqr(), TimedPrint::TimedPrint(), UserForcingFunction::UserForcingFunction(), Parser::walkRaw(), and Coupleable::writableCoupledValue().
mooseDeprecationExpired()
template<typename... Args> void mooseDeprecationExpired (Args &&... args)
Emit a deprecated code/feature message with the given stringified, concatenated args.
Definition at line 321 of file MooseError.h.
{
  moose::internal::mooseDeprecatedStream(Moose::out, true, true, std::forward<Args>(args)...);
}
Referenced by Factory::deprecatedMessage().
mooseError()
template<typename... Args> void mooseError (Args &&... args)
Emit an error message with the given stringified, concatenated args and terminate the application.
Inside static functions, you will need to explicitly scope your mooseError call - i.e. do "::mooseError(arg1, ...);".
Definition at line 284 of file MooseError.h.
{
  std::ostringstream oss;
  moose::internal::mooseStreamAll(oss, std::forward<Args>(args)...);
  moose::internal::mooseErrorRaw(oss.str());
}
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), ADConservativeAdvectionBC::ADConservativeAdvectionBC(), Coupleable::adCoupledDofValues(), Coupleable::adCoupledDot(), Coupleable::adCoupledDotDot(), Coupleable::adCoupledGradient(), Coupleable::adCoupledGradientDot(), Coupleable::adCoupledLowerValue(), NeighborCoupleable::adCoupledNeighborGradient(), NeighborCoupleable::adCoupledNeighborValue(), NeighborCoupleable::adCoupledNeighborValueDot(), Coupleable::adCoupledNodalValue(), ScalarCoupleable::adCoupledScalarValue(), Coupleable::adCoupledSecond(), Coupleable::adCoupledValue(), Coupleable::adCoupledVectorDot(), Coupleable::adCoupledVectorGradient(), NeighborCoupleable::adCoupledVectorNeighborValue(), adCoupledVectorSecond(), Coupleable::adCoupledVectorValue(), VariableWarehouse::add(), ActionWarehouse::addActionBlock(), NonlinearSystemBase::addBoundaryCondition(), InputParameterWarehouse::addControllableParameterAlias(), InputParameterWarehouse::addControllableParameterConnection(), NonlinearSystemBase::addDamper(), FormattedTable::addData(), Syntax::addDependency(), InputParameters::addDeprecatedParam(), MooseEnumBase::addDocumentation(), MooseEnumBase::addEnumerationItem(), MooseEnumBase::addEnumerationName(), MooseApp::addExecutor(), ADDGKernel::ADDGKernel(), NonlinearSystemBase::addImplicitGeometricCouplingEntries(), InputParameterWarehouse::addInputParameters(), AuxiliarySystem::addKernel(), Moose::LibtorchArtificialNeuralNet::addLayer(), FEProblem::addLineSearch(), SystemBase::addMatrix(), ConstraintWarehouse::addObject(), FVInitialConditionWarehouse::addObject(), InitialConditionWarehouse::addObject(), ExecuteMooseObjectWarehouse< T >::addObject(), OutputWarehouse::addOutputFilename(), InputParameters::addParam(), InputParameters::addParamNamesToGroup(), InputParameters::addPrivateParam(), MaterialPropertyStorage::addProperty(), InputParameters::addRequiredParam(), SystemBase::addVariable(), SystemBase::addVector(), MooseVariableData< OutputType >::adGradPhi(), MooseVariableData< OutputType >::adGradPhiFace(), MooseVariableDataFV< OutputType >::adGradSlnDot(), ADInterfaceKernelTempl< T >::ADInterfaceKernelTempl(), ADMaterialProperty< T >::ADMaterialProperty(), Moose::adOffset(), AllLocalDofIndicesThread::AllLocalDofIndicesThread(), ExecFlagEnum::appendCurrent(), MeshGeneratorSystem::appendMeshGenerator(), Syntax::appendTaskName(), MooseApp::appNameToLibName(), ArrayDGKernel::ArrayDGKernel(), ArrayDiffusion::ArrayDiffusion(), ArrayReaction::ArrayReaction(), ArrayTimeDerivative::ArrayTimeDerivative(), MooseEnum::assign(), MultiMooseEnum::assign(), SystemBase::associateMatrixToTag(), SystemBase::associateVectorToTag(), InputParameters::at(), MooseApp::attachRelationshipManagers(), TheWarehouse::attribID(), BlockAverageValue::averageValue(), boundaryIntegrityCheckError(), MooseMeshXYCuttingUtils::boundaryTriElemImprover(), ReporterContext< T >::broadcast(), RegistryEntry< T >::build(), Moose::FV::Limiter< T >::build(), RegistryEntry< T >::buildAction(), PiecewiseLinearBase::buildInterpolation(), AutomaticMortarGeneration::buildMortarSegmentMesh(), AutomaticMortarGeneration::buildMortarSegmentMesh3d(), AutomaticMortarGeneration::buildNodeToElemMaps(), ParsedFunctorMaterialTempl< is_ad >::buildParsedFunction(), ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), MooseObjectName::check(), ReporterData::check(), MooseObjectParameterName::check(), MaterialPropertyInterface::checkBlockAndBoundaryCompatibility(), InputParameters::checkConsistentType(), ControllableParameter::checkExecuteOnType(), MaterialPropertyInterface::checkExecutionStage(), Moose::FunctorBase< T >::checkFace(), MooseUtils::checkFileReadable(), MooseUtils::checkFileWriteable(), Coupleable::checkFuncType(), NonlinearEigenSystem::checkIntegrity(), NonlinearSystemBase::checkKernelCoverage(), MooseApp::checkMetaDataIntegrity(), OutputWarehouse::checkOutputs(), InputParameters::checkParamName(), InputParameters::checkParams(), ColumnMajorMatrixTempl< T >::checkShapeEquality(), ColumnMajorMatrixTempl< T >::checkSquareness(), ActionWarehouse::checkUnsatisfiedActions(), ScalarCoupleable::checkVar(), Coupleable::checkVar(), BlockRestrictable::checkVariable(), Coupleable::checkWritableVar(), MathUtils::circumcenter2D(), MathUtils::circumcenter3D(), MooseUtils::clearSymlink(), FunctionPeriodicBoundary::clone(), SystemBase::closeTaggedVector(), ComparisonPostprocessor::comparisonIsTrue(), PenetrationThread::competeInteractions(), CompositeTensorBase< T, U >::CompositeTensorBase(), ElementH1ErrorFunctionAux::compute(), ComputeJacobianThread::compute(), MooseVariableData< OutputType >::computeAD(), SplineInterpolationBase::computeCoeffs(), ADInterfaceKernelTempl< T >::computeElemNeighJacobian(), InterfaceKernelTempl< T >::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighJacobian(), ArrayDGKernel::computeElemNeighResidual(), InternalSideIntegralPostprocessor::computeFaceInfoIntegral(), SideIntegralPostprocessor::computeFaceInfoIntegral(), Assembly::computeFaceMap(), MooseVariableFV< OutputType >::computeFaceValues(), HistogramVectorPostprocessor::computeHistogram(), AutomaticMortarGeneration::computeInactiveLMNodes(), AutomaticMortarGeneration::computeIncorrectEdgeDroppingInactiveLMNodes(), MooseVariableData< OutputType >::computeIncrementAtNode(), ADIntegratedBCTempl< T >::computeJacobian(), ArrayIntegratedBC::computeJacobian(), ADKernelTempl< T >::computeJacobian(), NodalConstraint::computeJacobian(), Moose::LibtorchArtificialNeuralNetTrainer< SamplerType >::computeLocalBatchSize(), ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(), LowerDIntegratedBC::computeLowerDOffDiagJacobian(), EigenProblem::computeMatricesTags(), ArrayDGKernel::computeOffDiagElemNeighJacobian(), ArrayIntegratedBC::computeOffDiagJacobian(), MortarScalarBase::computeOffDiagJacobianScalar(), ArrayDGLowerDKernel::computeOffDiagLowerDJacobian(), DGLowerDKernel::computeOffDiagLowerDJacobian(), SideAdvectiveFluxIntegralTempl< is_ad >::computeQpIntegral(), NodalEqualValueConstraint::computeQpJacobian(), CoupledTiedValueConstraint::computeQpJacobian(), EqualValueBoundaryConstraint::computeQpJacobian(), EqualValueEmbeddedConstraint::computeQpJacobian(), LinearNodalConstraint::computeQpJacobian(), TiedValueConstraint::computeQpJacobian(), PenaltyEqualValueConstraintTempl< is_ad >::computeQpJacobian(), CoupledTiedValueConstraint::computeQpOffDiagJacobian(), EqualValueEmbeddedConstraint::computeQpOffDiagJacobian(), KernelValue::computeQpResidual(), NodalEqualValueConstraint::computeQpResidual(), ADKernelGradTempl< T >::computeQpResidual(), ADKernelStabilizedTempl< T >::computeQpResidual(), ADKernelValueTempl< T >::computeQpResidual(), InterfaceQpValueUserObject::computeRealValue(), InterfaceQpMaterialPropertyBaseUserObject< T >::computeRealValue(), ArrayIntegratedBC::computeResidual(), NodalConstraint::computeResidual(), KernelScalarBase::computeScalarOffDiagJacobian(), ADMortarScalarBase::computeScalarQpResidual(), MortarScalarBase::computeScalarQpResidual(), ADKernelScalarBase::computeScalarQpResidual(), KernelScalarBase::computeScalarQpResidual(), NonlinearSystemBase::computeScaling(), CentralDifference::computeTimeDerivatives(), MultiAppGeometricInterpolationTransfer::computeTransformation(), ControllableItem::connect(), NonlinearSystemBase::constraintJacobians(), MooseUtils::convert(), MooseUnits::convert(), MemoryUtils::convertBytes(), MooseUtils::convertLatestCheckpoint(), MooseUtils::convertStringToInt(), MooseMeshUtils::coordTransformFactor(), Assembly::copyFaceShapes(), MooseApp::copyInputs(), Assembly::copyNeighborShapes(), Assembly::copyShapes(), SystemBase::copyVars(), LazyCoupleable::coupled(), NeighborCoupleable::coupledArrayNeighborGradient(), NeighborCoupleable::coupledArrayNeighborGradientOld(), NeighborCoupleable::coupledArrayNeighborGradientOlder(), AuxKernelTempl< ComputeValueType >::coupledDotDu(), CoupledForceNodalKernel::CoupledForceNodalKernel(), Coupleable::coupledMatrixTagValue(), Coupleable::coupledMatrixTagValues(), Coupleable::coupledName(), NeighborCoupleable::coupledNeighborDofValues(), NeighborCoupleable::coupledNeighborDofValuesOld(), NeighborCoupleable::coupledNeighborDofValuesOlder(), NeighborCoupleable::coupledNeighborGradient(), NeighborCoupleable::coupledNeighborGradientOld(), NeighborCoupleable::coupledNeighborGradientOlder(), NeighborCoupleable::coupledNeighborSecond(), NeighborCoupleable::coupledNeighborValueOlder(), Coupleable::coupledNodalDot(), Coupleable::coupledNodalValue(), Coupleable::coupledNodalValueOld(), Coupleable::coupledNodalValueOlder(), ScalarCoupleable::coupledScalarComponents(), ScalarCoupleable::coupledScalarValueOlder(), Coupleable::coupledValueLower(), NeighborCoupleable::coupledVectorNeighborGradient(), NeighborCoupleable::coupledVectorNeighborGradientOld(), NeighborCoupleable::coupledVectorNeighborGradientOlder(), Coupleable::coupledVectorTagArrayGradient(), Coupleable::coupledVectorTagArrayGradients(), Coupleable::coupledVectorTagArrayValues(), Coupleable::coupledVectorTagDofValues(), Coupleable::coupledVectorTagGradient(), Coupleable::coupledVectorTagGradients(), ScalarCoupleable::coupledVectorTagScalarValue(), Coupleable::coupledVectorTagValues(), ActionFactory::create(), Factory::create(), MeshGeneratorSystem::createAddedMeshGenerators(), AppFactory::createdAppCount(), MooseApp::createExecutors(), MeshGeneratorSystem::createMeshGeneratorOrder(), MortarData::createMortarInterface(), MooseApp::createRMFromTemplateAndInit(), AppFactory::createShared(), MooseUtils::createSymlink(), MooseVariableFV< OutputType >::curlPhi(), MooseVariableData< OutputType >::curlSln(), MooseVariableDataFV< OutputType >::curlSln(), DependencyResolverInterface::cyclicDependencyError(), CyclicDependencyException< T, Compare >::CyclicDependencyException(), RankTwoTensorTempl< T >::d2sin3Lode(), RestartableDataMap::data(), SidesetInfoVectorPostprocessor::dataHelper(), dataLoad(), dataStore(), ReporterVectorContext< T >::declareClone(), InputParameters::declareControllable(), ReporterVectorContext< T >::declareVectorClone(), FunctorInterface::deduceFunctorName(), InputParameters::defaultCoupledValue(), Syntax::deleteTaskDependencies(), MooseEnumBase::deprecate(), Syntax::deprecatedActionSyntaxMessage(), DerivativeSumMaterialTempl< is_ad >::DerivativeSumMaterialTempl(), Moose::derivInsert(), RestartableDataReader::deserializeValue(), ComputeResidualAndJacobianThread::determineObjectWarehouses(), DGKernel::DGKernel(), SystemBase::disassociateMatrixFromTag(), SystemBase::disassociateVectorFromTag(), MooseVariableFV< OutputType >::divPhi(), MooseVariableData< OutputType >::divSln(), DMCreateFieldDecomposition_Moose(), DMMooseFunction(), DMMooseGetEmbedding_Private(), DMMooseJacobian(), DMSetUp_Moose_Pre(), EigenProblem::doFreeNonlinearPowerIterations(), MooseVariableData< OutputType >::dofValuesDot(), MooseVariableDataFV< OutputType >::dofValuesDot(), MooseVariableData< OutputType >::dofValuesDotDot(), MooseVariableDataFV< OutputType >::dofValuesDotDot(), MooseVariableData< OutputType >::dofValuesDotDotOld(), MooseVariableDataFV< OutputType >::dofValuesDotDotOld(), MooseVariableData< OutputType >::dofValuesDotOld(), MooseVariableDataFV< OutputType >::dofValuesDotOld(), MooseVariableInterface< Real >::dotDu(), MooseVariableInterface< Real >::dotOld(), DriftDiffusion::DriftDiffusion(), DriftDiffusionDoNothingBC::DriftDiffusionDoNothingBC(), RankTwoTensorTempl< T >::dsin3Lode(), SymmetricRankTwoTensorTempl< T >::dsin3Lode(), MooseApp::dynamicAllRegistration(), MooseApp::dynamicAppRegistration(), EconomouDielectricBC::EconomouDielectricBC(), EEDFEnergyTownsendLog::EEDFEnergyTownsendLog(), ColumnMajorMatrixTempl< T >::eigen(), ColumnMajorMatrixTempl< T >::eigenNonsym(), EigenProblem::EigenProblem(), Eigenvalues::Eigenvalues(), ElectronEnergyTermRate::ElectronEnergyTermRate(), ElectronsFromIonization::ElectronsFromIonization(), ElementalVariableValue::ElementalVariableValue(), ElementGroupCentroidPositions::ElementGroupCentroidPositions(), NonlinearSystemBase::enforceNodalConstraintsJacobian(), BicubicInterpolation::errorCheck(), BicubicSplineInterpolation::errorCheck(), FileRangeBuilder::errorCheck(), SplineInterpolation::errorCheck(), Parser::errorCheck(), ADFParser::Eval(), GeneralFieldTransfer::RecordRequests< Output >::eval_mixed_derivatives(), GeneralFieldTransfer::CachedData< Output >::eval_mixed_derivatives(), GeneralFieldTransfer::RecordRequests< Output >::eval_old_dofs(), GeneralFieldTransfer::CachedData< Output >::eval_old_dofs(), Moose::NullFunctor< T >::evaluate(), MooseVariableFE< OutputType >::evaluate(), evaluate(), Moose::FunctorBase< T >::evaluateDot(), MooseVariableFV< OutputType >::evaluateDot(), GriddedData::evaluateFcn(), Moose::FunctorBase< T >::evaluateGradDot(), Moose::FunctorBase< T >::evaluateGradient(), MultiAppGeneralFieldTransfer::examineReceivedValueConflicts(), FindValueOnLine::execute(), GreaterThanLessThanPostprocessor::execute(), PointValue::execute(), TimeExtremeValue::execute(), VectorPostprocessorComparison::execute(), RestartableDataReporter::execute(), MultiAppCopyTransfer::execute(), MultiAppGeometricInterpolationTransfer::execute(), MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), InterfaceQpUserObjectBase::execute(), LeastSquaresFit::execute(), LeastSquaresFitHistory::execute(), NodalValueSampler::execute(), PositionsFunctorValueSampler::execute(), ChannelGradient::execute(), MooseApp::executeExecutioner(), Exodus::Exodus(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), Parser::extractParams(), MooseVariableFE< OutputType >::faceEvaluate(), FaceInfo::faceType(), FactorizedRankTwoTensorTempl< T >::FactorizedRankTwoTensorTempl(), Moose::fe_lagrange_1D_shape(), Moose::fe_lagrange_1D_shape_deriv(), Moose::fe_lagrange_2D_shape(), Moose::fe_lagrange_2D_shape_deriv(), MooseVariableData< OutputType >::fetchADDoFValues(), MooseVariableFV< OutputType >::fieldType(), FileRangeBuilder::FileRangeBuilder(), ColumnMajorMatrixTempl< T >::fill(), RankFourTensorTempl< T >::fillAntisymmetricFromInputVector(), RankFourTensorTempl< T >::fillAntisymmetricIsotropicFromInputVector(), FillBetweenPointVectorsTools::fillBetweenPointVectorsGenerator(), RankFourTensorTempl< T >::fillFromInputVector(), SymmetricRankFourTensorTempl< T >::fillFromInputVector(), RankTwoTensorTempl< T >::fillFromInputVector(), SymmetricRankTwoTensorTempl< T >::fillFromInputVector(), RankThreeTensorTempl< T >::fillFromInputVector(), RankTwoTensorTempl< T >::fillFromScalarVariable(), SymmetricRankTwoTensorTempl< T >::fillFromScalarVariable(), RankFourTensorTempl< T >::fillGeneralFromInputVector(), RankThreeTensorTempl< T >::fillGeneralFromInputVector(), RankFourTensorTempl< T >::fillGeneralIsotropicFromInputVector(), RankFourTensorTempl< T >::fillGeneralOrthotropicFromInputVector(), SymmetricRankFourTensorTempl< T >::fillGeneralOrthotropicFromInputVector(), NearestPointBase< UserObjectType, BaseType >::fillPoints(), RankFourTensorTempl< T >::fillPrincipalFromInputVector(), SymmetricRankFourTensorTempl< T >::fillPrincipalFromInputVector(), MultiAppGeometricInterpolationTransfer::fillSourceInterpolationPoints(), RankFourTensorTempl< T >::fillSymmetricIsotropicEandNuFromInputVector(), SymmetricRankFourTensorTempl< T >::fillSymmetricIsotropicEandNuFromInputVector(), PointSamplerBase::finalize(), SamplerBase::finalize(), PeriodicComparisonCounter::finalize(), MemoryUsage::finalize(), ReporterContext< T >::finalize(), NearestPointAverage::finalize(), NearestPointIntegralVariablePostprocessor::finalize(), VectorPostprocessorContext< T >::finalize(), MooseApp::finalizeRestore(), NearestNodeLocator::findNodes(), DiracKernelInfo::findPoint(), MultiIndex< T >::flatIndex(), FormattedTable::FormattedTable(), ParsedMaterialHelper< is_ad >::functionParse(), FunctionPeriodicBoundary::FunctionPeriodicBoundary(), FunctionParserUtils< is_ad >::functionsOptimize(), FunctorSmootherTempl< T >::FunctorSmootherTempl(), FVMatAdvection::FVMatAdvection(), WorkBalance::gather(), LeastSquaresFitBase::generate(), GenericFunctorGradientMaterialTempl< is_ad >::GenericFunctorGradientMaterialTempl(), GenericFunctorMaterialTempl< is_ad >::GenericFunctorMaterialTempl(), GenericVectorFunctorMaterialTempl< is_ad >::GenericVectorFunctorMaterialTempl(), RankTwoTensorTempl< typename T::value_type >::genRandomTensor(), GeometricSearchData::GeometricSearchData(), FileInputStream::get(), ControllableItem::get(), InputParameters::get(), FunctionPeriodicBoundary::get_corresponding_pos(), ActionWarehouse::getAction(), ActionWarehouse::getActionByTask(), MooseObjectWarehouseBase< T >::getActiveObject(), BlockRestrictable::getBlockCoordSystem(), MaterialPropertyInterface::getBlockMaterialProperty(), MooseVariableFV< OutputType >::getBoundaryFaceValue(), MooseMeshUtils::getBoundaryIDs(), InputParameters::getCheckedPointerParam(), NonlinearEigenSystem::getConvergedEigenpair(), NonlinearEigenSystem::getConvergedEigenvalue(), NonlinearEigenSystem::getCurrentNonlinearIterationNumber(), MooseUtils::DelimitedFileReader::getData(), MooseUtils::DelimitedFileReader::getDataAsPoints(), Coupleable::getDefaultValue(), InputParameters::getDescription(), DistributionInterface::getDistribution(), DistributionInterface::getDistributionByName(), MooseVariableData< OutputType >::getElementalValue(), MooseVariableDataFV< OutputType >::getElementalValue(), ElementIDInterface::getElementIDIndex(), ElementIDInterface::getElementIDIndexByName(), ElementPairLocator::getElemPairInfo(), ElementPairLocator::getElemPairs(), NonlinearEigenSystem::getEPS(), Moose::getExec(), MooseApp::getExecutor(), VariableWarehouse::getFVVariable(), AuxKernelTempl< ComputeValueType >::getGenericMaterialProperty(), MaterialPropertyInterface::getGenericMaterialProperty(), RestartableDataReader::getHeader(), MortarData::getHigherDimSubdomainIDs(), MaterialPropertyRegistry::getID(), PenetrationThread::getInfoForFacesWithCommonNodes(), InputParameterWarehouse::getInputParameters(), FormattedTable::getLastData(), MooseUtils::getLatestCheckpointFilePrefix(), LayeredBase::getLayerValue(), AuxKernelTempl< ComputeValueType >::getMaterialProperty(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOld(), AuxKernelTempl< ComputeValueType >::getMaterialPropertyOlder(), SystemBase::getMatrix(), MeshGeneratorSystem::getMeshGenerator(), MortarData::getMortarInterface(), MortarSegmentHelper::getMortarSegments(), MaterialPropertyRegistry::getName(), Times::getNextTime(), MooseVariableData< OutputType >::getNodalValue(), EigenProblem::getNonlinearEigenSystem(), MooseObjectWarehouseBase< T >::getObject(), OutputWarehouse::getOutput(), InputParameters::getParamHelper(), Moose::PetscSupport::getPetscKSPNormType(), Moose::PetscSupport::getPetscPCSide(), Positions::getPosition(), Positions::getPositions(), Positions::getPositionsVector2D(), Positions::getPositionsVector3D(), Positions::getPositionsVector4D(), Times::getPreviousTime(), InterfaceQpUserObjectBase::getQpValue(), InterfaceValueTools::getQuantity(), MaterialStdVectorAuxTempl< is_ad >::getRealValue(), MooseApp::getRenamedParam(), MooseBaseParameterInterface::getRenamedParam(), ReporterData::getReporterContextBase(), ReporterData::getReporterStateBase(), ReporterData::getReporterStateHelper(), ReporterData::getReporterValue(), MooseApp::getRestartableDataMap(), MooseApp::getRestartableDataMapName(), MooseApp::getRestartableMetaData(), MooseApp::getRMClone(), RankTwoTensorTempl< T >::getRUDecompositionRotation(), SamplerInterface::getSamplerByName(), MeshGeneratorSystem::getSavedMesh(), ScalarCoupleable::getScalarVar(), SystemBase::getScalarVariable(), InterfaceQpUserObjectBase::getSideAverageValue(), PenetrationThread::getSideCornerNodes(), PenetrationThread::getSmoothingEdgeNodesAndWeights(), PenetrationThread::getSmoothingFacesAndWeights(), NonlinearEigenSystem::getSNES(), NonlinearSystem::getSNES(), Syntax::getSortedTask(), MooseMeshUtils::getSubdomainID(), InputParameters::getSyntax(), Times::getTimeAtIndex(), Times::getTimes(), ActionFactory::getValidParams(), AppFactory::getValidParams(), NumRelationshipManagers::getValue(), Residual::getValue(), SideAverageValue::getValue(), VectorPostprocessorComponent::getValue(), LineValueSampler::getValue(), FindValueOnLine::getValueAtPoint(), Coupleable::getVarHelper(), SystemBase::getVariable(), SystemBase::getVector(), Coupleable::getVectorVar(), Moose::globalDofIndexToDerivative(), MooseVariableInterface< T >::gradient(), MooseVariableInterface< T >::gradientOld(), MooseVariableInterface< T >::gradientOlder(), MooseVariableData< OutputType >::gradSlnDot(), MooseVariableDataFV< OutputType >::gradSlnDot(), MooseVariableData< OutputType >::gradSlnDotDot(), MooseVariableDataFV< OutputType >::gradSlnDotDot(), Moose::FV::greenGaussGradient(), Moose::FunctorBase< T >::hasBlocks(), InputParameters::hasDefault(), HeatCapacityRatio::HeatCapacityRatio(), Parser::hitCLIFilter(), MooseUtils::hostname(), HphiRadialInterface::HphiRadialInterface(), GeneralRegistry< Key, Item, KeyHash >::id(), FunctionPeriodicBoundary::init(), LazyCoupleable::init(), CommandLine::initForMultiApp(), MooseParsedFunctionWrapper::initialize(), ElementGroupCentroidPositions::initialize(), FunctorPositions::initialize(), ReporterPositions::initialize(), FunctorTimes::initialize(), ReporterTimes::initialize(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), CoarsenedPiecewiseLinear::initialSetup(), PiecewiseLinear::initialSetup(), PiecewiseLinearBase::initialSetup(), IntegralPreservingFunctionIC::initialSetup(), CSV::initialSetup(), Exodus::initialSetup(), NodalVariableValue::initialSetup(), ReferenceResidualProblem::initialSetup(), MultiAppConservativeTransfer::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), AdvancedOutput::initOutputList(), AdvancedOutput::initShowHideLists(), Parser::initSyntaxFormatter(), InputParameters::addDeprecatedParam< std::vector< MooseEnum > >(), InputParameters::addParam< std::vector< MooseEnum > >(), MooseUtils::StaticallyAllocatedSet< T, N >::insert(), MooseUtils::installedInputsDir(), LayeredBase::integralValue(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::InterfaceDiffusiveFluxIntegralTempl(), InterfaceIntegralVariableValuePostprocessor::InterfaceIntegralVariableValuePostprocessor(), InterfaceKernelTempl< T >::InterfaceKernelTempl(), InterfaceLogDiffusionElectrons::InterfaceLogDiffusionElectrons(), InterfaceTimeKernel::InterfaceTimeKernel(), Moose::FV::interpCoeffs(), Moose::FV::interpolate(), MultiAppGeometricInterpolationTransfer::interpolateTargetPoints(), ColumnMajorMatrixTempl< T >::inverse(), RankFourTensorTempl< T >::invSymm(), RestartableDataReader::isAvailable(), Coupleable::isCoupled(), ScalarCoupleable::isCoupledScalar(), Moose::FunctorBase< T >::isExtrapolatedBoundaryFace(), ActionWarehouse::isTaskComplete(), InputParameters::isType(), MortarSegmentInfo::isValid(), GeneralRegistry< Key, Item, KeyHash >::itemNonLocking(), ADFParser::JITCompile(), JouleHeating::JouleHeating(), LayeredBase::LayeredBase(), LayeredSideIntegralBase< UserObjectType >::LayeredSideIntegralBase(), LeastSquaresFit::LeastSquaresFit(), MooseApp::libNameToAppName(), Moose::LibtorchArtificialNeuralNet::LibtorchArtificialNeuralNet(), Moose::FV::limiterType(), LinearCombinationPostprocessor::LinearCombinationPostprocessor(), LinearNodalConstraint::LinearNodalConstraint(), LineMaterialSamplerBase< T >::LineMaterialSamplerBase(), MooseMeshXYCuttingUtils::lineRemoverCutElemTri(), MooseMeshXYCuttingUtils::lineRemoverMoveNode(), LineValueSampler::LineValueSampler(), RestartableEquationSystems::load(), MooseApp::loadLibraryAndDependencies(), Moose::LibtorchTorchScriptNeuralNet::loadNeuralNetwork(), MultiAppGeneralFieldTransfer::locatePointReceivers(), LockFile::LockFile(), LowerBoundNodalKernel::LowerBoundNodalKernel(), MooseUtils::makedirs(), FaceArgProducerInterface::makeFace(), FormattedTable::makeGnuplot(), InputParameters::makeParamNotRequired(), InputParameters::makeParamRequired(), PNGOutput::makePNG(), MultiAppCoordTransform::mapBack(), MaterialProperty< T >::MaterialProperty(), MaterialPropertyBase< T, is_ad >::MaterialPropertyBase(), MaterialStdVectorRealGradientAux::MaterialStdVectorRealGradientAux(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MooseVariableDataBase< OutputType >::matrixTagValue(), MeshBaseImageSampler::MeshBaseImageSampler(), MeshMetaDataInterface::meshPropertyPrefix(), MooseApp::MooseApp(), MooseAppCoordTransform::MooseAppCoordTransform(), moose::internal::mooseDeprecatedStream(), MooseEnumBase::MooseEnumBase(), MeshMetaDataInterface::mooseErrorInternal(), Moose::SlepcSupport::mooseMatMult_Eigen(), Moose::SlepcSupport::mooseMatMult_NonEigen(), MooseParsedFunctionBase::MooseParsedFunctionBase(), MathUtils::mooseSetToZero(), Moose::SlepcSupport::mooseSlepcEPSGetSNES(), MooseVariableInterface< T >::mooseVariable(), MooseVariableConstMonomial::MooseVariableConstMonomial(), MooseVariableInterface< T >::mooseVariableField(), moose::internal::mooseWarningStream(), NonlinearSystemBase::mortarConstraints(), MultiAppUserObjectTransfer::MultiAppUserObjectTransfer(), MultiIndex< T >::MultiIndex(), NeighborMooseVariableInterface< T >::neighborGradient(), NeighborMooseVariableInterface< T >::neighborGradientOld(), KDTree::neighborSearch(), NeighborMooseVariableInterface< T >::neighborSecond(), NeighborMooseVariableInterface< Real >::neighborSecond(), NeighborMooseVariableInterface< T >::neighborSecondOld(), NeighborMooseVariableInterface< T >::neighborSecondOlder(), NeighborMooseVariableInterface< T >::neighborSecondPhi(), NeighborMooseVariableInterface< Real >::neighborSecondPhi(), NeighborMooseVariableInterface< T >::neighborSecondTest(), NeighborMooseVariableInterface< T >::neighborValueOld(), NeumannCircuitVoltageNew::NeumannCircuitVoltageNew(), NodalConstraint::NodalConstraint(), MooseVariableFV< OutputType >::nodalDofIndex(), MooseVariableFV< OutputType >::nodalDofIndexNeighbor(), MooseVariableDataBase< OutputType >::nodalMatrixTagValue(), ProjectedStatefulMaterialNodalPatchRecoveryTempl< T, is_ad >::nodalPatchRecovery(), NodalScalarKernel::NodalScalarKernel(), MooseVariableDataBase< OutputType >::nodalValue(), MooseVariableFV< OutputType >::nodalValueArray(), MooseVariableDataBase< OutputType >::nodalValueArray(), MooseVariableData< OutputType >::nodalValueDot(), MooseVariableData< OutputType >::nodalValueDotDot(), MooseVariableData< OutputType >::nodalValueDotDotOld(), MooseVariableData< OutputType >::nodalValueDotOld(), MooseVariableFV< OutputType >::nodalValueOldArray(), MooseVariableFV< OutputType >::nodalValueOlderArray(), NodalVariableValue::NodalVariableValue(), MooseVariableDataBase< OutputType >::nodalVectorTagValue(), MooseVariableFV< OutputType >::nodalVectorTagValue(), NonlinearEigenSystem::NonlinearEigenSystem(), NonlinearEigenSystem::nonlinearSolver(), SystemBase::nonTimeVectorTag(), InputParameters::numberDefaultCoupledValues(), MooseVariableFV< OutputType >::numberOfDofsNeighbor(), NumDOFs::NumDOFs(), NumFailedTimeSteps::NumFailedTimeSteps(), NumNonlinearIterations::NumNonlinearIterations(), NumVars::NumVars(), Registry::objData(), Moose::FV::onBoundary(), FlagElementsThread::onElement(), ProjectMaterialProperties::onInternalSide(), FormattedTable::open(), MooseUnits::operator Real(), NearestNodeThread::operator()(), PenetrationThread::operator()(), ColumnMajorMatrixTempl< T >::operator()(), ColumnMajorMatrixTempl< T >::operator*(), ColumnMajorMatrixTempl< T >::operator+=(), ADMaterialProperty< T >::operator=(), ColumnMajorMatrixTempl< T >::operator=(), InputParameters::operator=(), MaterialProperty< T >::operator=(), MaterialPropertyBase< T, is_ad >::operator=(), OutputMapWrapper< T >::operator[](), ExecuteMooseObjectWarehouse< T >::operator[](), OrientedBoxInterface::OrientedBoxInterface(), Exodus::output(), SolutionHistory::output(), XDA::output(), AdvancedOutput::outputElementalVariables(), AdvancedOutput::outputInput(), AdvancedOutput::outputNodalVariables(), AdvancedOutput::outputPostprocessors(), AdvancedOutput::outputReporters(), AdvancedOutput::outputScalarVariables(), Exodus::outputSetup(), AdvancedOutput::outputSystemInformation(), AdvancedOutput::outputVectorPostprocessors(), Console::outputVectorPostprocessors(), MooseUnits::parse(), Parser::parse(), GriddedData::parse(), FunctionMaterialPropertyDescriptor< is_ad >::parseDependentSymbols(), FunctionMaterialPropertyDescriptor< is_ad >::parseDerivative(), ParsedODEKernel::ParsedODEKernel(), ParsedPostprocessor::ParsedPostprocessor(), ParsedScalarReaction::ParsedScalarReaction(), MooseUnits::parseError(), Factory::parseTime(), Moose::SlepcSupport::PCApply_MoosePC(), Moose::SlepcSupport::PCSetUp_MoosePC(), PenaltyCircuitPotential::PenaltyCircuitPotential(), PenetrationLocator::PenetrationLocator(), MultiAppConservativeTransfer::performAdjustment(), MooseVariableFV< OutputType >::phiLower(), MooseVariableFV< OutputType >::phiLowerSize(), PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(), MathUtils::plainLog(), MathUtils::poly1Log(), MathUtils::poly2Log(), MathUtils::poly3Log(), MathUtils::poly4Log(), PolynomialFit::PolynomialFit(), CommandLine::populateInputParams(), RankTwoTensorTempl< T >::positiveProjectionEigenDecomposition(), SymmetricRankTwoTensorTempl< T >::positiveProjectionEigenDecomposition(), EigenProblem::postScaleEigenVector(), MortarNodalAuxKernelTempl< ComputeValueType >::precalculateValue(), ADKernelValueTempl< T >::precomputeQpJacobian(), MaterialPropertyValueTempl< is_ad >::precomputeQpJacobian(), MooseUtils::DelimitedFileReader::preprocessLine(), MooseUtils::DelimitedFileReader::processLine(), Moose::PetscSupport::processPetscFlags(), Moose::Mortar::projectQPoints3d(), PseudoTimestep::PseudoTimestep(), PerfGraph::push(), rankConfig(), RankFourTensorTempl< T >::RankFourTensorTempl(), RankMap::ranks(), RankThreeTensorTempl< T >::RankThreeTensorTempl(), RankTwoTensorTempl< T >::RankTwoTensorTempl(), MooseUtils::DelimitedFileReader::readColumnData(), RestartableDataReader::readHeader(), MooseUtils::realpath(), DerivativeParsedMaterialHelperTempl< is_ad >::recurseDerivative(), MooseApp::recursivelyCreateExecutors(), ReferenceResidualProblem::ReferenceResidualProblem(), Factory::reg(), MooseApp::registerRestartableData(), MooseApp::registerRestartableNameWithFilter(), moose::internal::PerfGraphRegistry::registerSection(), Syntax::registerTaskName(), EqualValueEmbeddedConstraint::reinitConstraint(), RelativeSolutionDifferenceNorm::RelativeSolutionDifferenceNorm(), StringInputStream::release(), ExecFlagEnum::removeAvailableFlags(), MooseUtils::removedirs(), SystemBase::removeMatrix(), MooseApp::removeRelationshipManager(), SystemBase::removeVector(), InputParameters::renameCoupledVarInternal(), InputParameters::renameParamInternal(), ReporterName::ReporterName(), Factory::reportUnregisteredError(), Coupleable::requestStates(), RestartableDataReader::requireRestoring(), ReporterContextBase::requiresConsumerModes(), NonlinearEigenSystem::residualAndJacobianTogether(), NonlinearSystem::residualAndJacobianTogether(), SystemBase::residualCopy(), SystemBase::residualGhosted(), NonlinearSystemBase::residualVector(), SystemBase::residualVectorTag(), MultiIndex< T >::resize(), ReporterGeneralContext< T >::resize(), MooseVariableDataBase< OutputType >::resizeVectorTagData(), OptionalMaterialPropertyProxy< M, T, is_ad >::resolve(), RestartableDataReader::restore(), RestartableEquationSystems::restore(), MooseApp::restore(), RestartableDataReader::restoreData(), SystemBase::restoreSolutions(), Moose::restrictPointToFace(), PenetrationThread::restrictPointToFace(), PenetrationThread::restrictPointToSpecifiedEdgeOfFace(), SymmetricRankTwoTensorTempl< T >::row(), MooseApp::run(), MooseApp::runInputs(), LinearInterpolation::sample(), BicubicInterpolation::sample2ndDerivative(), BicubicSplineInterpolation::sample2ndDerivative(), BidimensionalInterpolation::sample2ndDerivative(), BidimensionalInterpolation::sampleDerivative(), BicubicInterpolation::sampleDerivative(), BicubicSplineInterpolation::sampleDerivative(), BilinearInterpolation::sampleDerivativeInternal(), BidimensionalInterpolation::sampleValueAndDerivatives(), ScalarCoupleable::ScalarCoupleable(), MortarScalarBase::scalarVariable(), CommandLine::search(), MooseVariableInterface< T >::second(), MooseVariableInterface< T >::secondOld(), MooseVariableInterface< T >::secondOlder(), MooseVariableInterface< Real >::secondOlder(), MooseVariableInterface< T >::secondPhi(), MooseVariableFV< OutputType >::secondPhi(), MooseVariableInterface< T >::secondPhiFace(), MooseVariableFV< OutputType >::secondPhiFace(), MooseVariableFV< OutputType >::secondPhiFaceNeighbor(), MooseVariableFV< OutputType >::secondPhiNeighbor(), MooseVariableData< OutputType >::secondSln(), MooseVariableDataFV< OutputType >::secondSln(), MooseVariableInterface< T >::secondTest(), MooseVariableInterface< Real >::secondTest(), MooseVariableInterface< Real >::secondTestFace(), MooseVariableInterface< T >::secondTestFace(), PerfGraph::sectionData(), Moose::FV::selectInterpolationMethod(), ControllableItem::set(), Adaptivity::setAdaptivityOn(), MooseAppCoordTransform::setCoordinateSystem(), NonlinearSystemBase::setDecomposition(), InputParameters::setDeprecatedVarDocString(), MultiAppCoordTransform::setDestinationCoordTransform(), InputParameters::setDocString(), Moose::SlepcSupport::setEigenProblemOptions(), Moose::SlepcSupport::setEigenProblemSolverParams(), Moose::SlepcSupport::setEigenSolverOptions(), Adaptivity::setErrorEstimator(), ActionWarehouse::setFinalTask(), PiecewiseByBlockLambdaFunctor< T >::setFunctor(), MooseEnumItem::setID(), NonlinearSystemBase::setMooseKSPNormType(), Assembly::setMortarQRule(), FVPointValueConstraint::setMyElem(), Moose::SlepcSupport::setNewtonPetscOptions(), MooseVariableFV< OutputType >::setNodalValue(), Moose::SlepcSupport::setNonlinearPowerOptions(), PenetrationLocator::setNormalSmoothingMethod(), Exodus::setOutputDimensionInExodusWriter(), Adaptivity::setParam(), NonlinearSystemBase::setPCSide(), NonlinearSystemBase::setPreconditioner(), MooseAppCoordTransform::setRotation(), Moose::PetscSupport::setSinglePetscOption(), MultiAppGeneralFieldTransfer::setSolutionVectorValues(), NonlinearSystem::setupColoringFiniteDifferencedPreconditioner(), MooseAppCoordTransform::setUpDirection(), NonlinearEigenSystem::setupFiniteDifferencedPreconditioner(), NonlinearSystem::setupFiniteDifferencedPreconditioner(), MeshBaseImageSampler::setupImageSampler(), ImageSampler::setupImageSampler(), MooseApp::setupOptions(), NonlinearSystemBase::setupScalingData(), Moose::SlepcSupport::setWhichEigenPairsOptions(), InputParameters::shouldIgnore(), SideAdvectiveFluxIntegralTempl< is_ad >::SideAdvectiveFluxIntegralTempl(), SideDiffusiveFluxIntegralTempl< is_ad, T >::SideDiffusiveFluxIntegralTempl(), RankTwoTensorTempl< T >::sin3Lode(), SymmetricRankTwoTensorTempl< T >::sin3Lode(), MultiIndex< T >::slice(), SystemBase::solutionState(), SpatialAverageBase::SpatialAverageBase(), MeshDivisionFunctorReductionVectorPostprocessor::spatialValue(), NearestPointAverage::spatialValue(), NearestPointIntegralVariablePostprocessor::spatialValue(), SplineInterpolationBase::spline(), MooseUtils::splitFileName(), GriddedData::splitToRealVec(), MooseVariableDataBase< OutputType >::stateToTagHelper(), NonlinearEigenSystem::stopSolve(), RestartableDataValue::store(), Moose::PetscSupport::storePetscOptions(), Moose::PetscSupport::stringify(), Moose::stringify(), Moose::stringToEnum< CoordinateSystemType >(), Moose::stringToEnum< EigenProblemType >(), Moose::stringToEnum< EigenSolveType >(), Moose::stringToEnum< LineSearchType >(), Moose::stringToEnum< MffdType >(), Moose::stringToEnum< RelationshipManagerType >(), Moose::stringToEnum< SolveType >(), Moose::stringToEnum< TimeIntegratorType >(), Moose::stringToEnum< WhichEigenPairs >(), PiecewiseByBlockLambdaFunctor< T >::subdomainErrorMessage(), MultiAppGeometricInterpolationTransfer::subdomainIDsNode(), InputParameters::suppressParameter(), RankFourTensorTempl< T >::surfaceFillFromInputVector(), RankTwoTensorTempl< T >::syev(), SymmetricRankTwoTensorTempl< T >::syev(), RankTwoTensorTempl< T >::symmetricEigenvaluesEigenvectors(), SymmetricRankTwoTensorTempl< T >::symmetricEigenvaluesEigenvectors(), SymmetricRankFourTensorTempl< T >::SymmetricRankFourTensorTempl(), SymmetricRankTwoTensorTempl< T >::SymmetricRankTwoTensorTempl(), Console::systemInfoFlags(), SystemBase::systemMatrixTag(), TableValue< T >::TableValue(), TaggingInterface::TaggingInterface(), LibtorchUtils::tensorToVector(), TimeExtremeValue::TimeExtremeValue(), TimeIntervalTimes::TimeIntervalTimes(), SystemBase::timeVectorTag(), Moose::LibtorchArtificialNeuralNetTrainer< SamplerType >::train(), MultiAppDofCopyTransfer::transfer(), InputParameters::transferParam(), ReporterContext< T >::transferToVector(), MultiAppShapeEvaluationTransfer::transferVariable(), MooseAppCoordTransform::transformMesh(), moose::translateMetaPhysicLError(), MortarSegmentHelper::triangulatePoly(), TrilinearInterpolation::TrilinearInterpolation(), InputParameters::type(), MooseVariableData< OutputType >::uDot(), MooseVariableDataFV< OutputType >::uDot(), MooseVariableData< OutputType >::uDotDot(), MooseVariableDataFV< OutputType >::uDotDot(), MooseVariableData< OutputType >::uDotDotOld(), MooseVariableDataFV< OutputType >::uDotDotOld(), MooseVariableData< OutputType >::uDotOld(), MooseVariableDataFV< OutputType >::uDotOld(), Positions::unrollMultiDPositions(), AuxKernelTempl< ComputeValueType >::uOld(), AuxKernelTempl< Real >::uOlder(), AuxKernelTempl< ComputeValueType >::uOlder(), MortarData::update(), Checkpoint::updateCheckpointFiles(), EqualValueBoundaryConstraint::updateConstrainedNodes(), NearestNodeLocator::updatePatch(), UpperBoundNodalKernel::UpperBoundNodalKernel(), TaggingInterface::useMatrixTag(), NearestPointAverage::userObjectValue(), NearestPointIntegralVariablePostprocessor::userObjectValue(), TaggingInterface::useVectorTag(), Coupleable::validateExecutionerType(), ScalarCoupleable::validateExecutionerType(), FunctionMaterialPropertyDescriptor< is_ad >::value(), IntegralPreservingFunctionIC::value(), ReporterState< T >::value(), MooseVariableInterface< Real >::valueOlder(), VariableValueVolumeHistogram::VariableValueVolumeHistogram(), InputParameters::varName(), VectorMagnitudeFunctorMaterialTempl< is_ad >::VectorMagnitudeFunctorMaterialTempl(), VectorNodalBC::VectorNodalBC(), MooseVariableDataBase< OutputType >::vectorTagDofValue(), Coupleable::vectorTagDofValueHelper(), MooseVariableDataBase< OutputType >::vectorTagGradient(), MooseVariableDataBase< OutputType >::vectorTagValue(), Coupleable::vectorTagValueHelper(), MooseParsedFunctionBase::verifyFunction(), VTKOutput::VTKOutput(), ImageSampler::vtkThreshold(), MeshBaseImageSampler::vtkThreshold(), Coupleable::writableCoupledValue(), Coupleable::writableVariable(), RestartableDataWriter::write(), MooseApp::writeRestartableMetaData(), Console::writeStreamToFile(), DOFMapOutput::writeStreamToFile(), SystemBase::zeroTaggedVector(), SystemBase::zeroVariables(), InputStream::~InputStream(), and ThreadedFaceLoop< RangeType >::~ThreadedFaceLoop().
mooseInfo()
template<typename... Args> void mooseInfo (Args &&... args)
Emit an informational message with the given stringified, concatenated args.
Definition at line 329 of file MooseError.h.
{
  moose::internal::mooseInfoStream(Moose::out, std::forward<Args>(args)...);
}
Referenced by MultiAppGeneralFieldNearestLocationTransfer::evaluateInterpValuesNearestNode(), DataFileInterface< Action >::getDataFileNameByName(), MultiAppGeneralFieldTransfer::initialSetup(), PNGOutput::makeMeshFunc(), MultiAppGeneralFieldTransfer::outputValueConflicts(), MooseBaseParameterInterface::paramInfo(), Parser::parse(), DerivativeParsedMaterialHelperTempl< is_ad >::recurseDerivative(), and ReferenceResidualProblem::ReferenceResidualProblem().
mooseInfoRepeated()
template<typename... Args> void mooseInfoRepeated (Args &&... args)
Emit an informational message with the given stringified, concatenated args.
Definition at line 337 of file MooseError.h.
{
  moose::internal::mooseInfoStreamRepeated(Moose::out, std::forward<Args>(args)...);
}
Referenced by MeshDiagnosticsGenerator::diagnosticsLog(), UnitsConversionEvaler::eval(), and Terminator::handleMessage().
mooseUnused()
template<typename... Args> void mooseUnused (Args &&... args)
Warning message used to notify the users of unused parts of their input files Really used internally by the parser and shouldn't really be called elsewhere.
Definition at line 305 of file MooseError.h.
{
  moose::internal::mooseUnusedStream(Moose::out, std::forward<Args>(args)...);
}
Referenced by Parser::errorCheck().
mooseWarning()
template<typename... Args> void mooseWarning (Args &&... args)
Emit a warning message with the given stringified, concatenated args.
Inside static functions, you will need to explicitly scope your mooseWarning call - i.e. do "::mooseWarning(arg1, ...);".
Definition at line 296 of file MooseError.h.
{
  moose::internal::mooseWarningStream(Moose::out, std::forward<Args>(args)...);
}
Referenced by AutomaticMortarGeneration::buildMortarSegmentMesh(), AutomaticMortarGeneration::buildMortarSegmentMesh3d(), MooseEnumBase::checkDeprecated(), ComputeFVFluxThread< RangeType, AttributeTagType >::checkPropDeps(), OversampleOutput::cloneMesh(), NonlinearSystem::converged(), PenetrationLocator::detectPenetration(), MeshDivisionFunctorReductionVectorPostprocessor::execute(), FileRangeBuilder::FileRangeBuilder(), ControllableParameter::get(), MooseMeshUtils::getBoundaryIDs(), Coupleable::getDefaultVectorValue(), PointSamplerBase::getLocalElemContainingPoint(), MemoryUtils::getMemoryStats(), Positions::getNearestPositionIndex(), LineValueSampler::getValue(), Moose::FV::harmonicInterpolation(), ElementGroupCentroidPositions::initialize(), ReferenceResidualProblem::initialSetup(), MultiAppGeneralFieldNearestLocationTransfer::initialSetup(), MultiAppGeneralFieldTransfer::initialSetup(), AdvancedOutput::initPostprocessorOrVectorPostprocessorLists(), LayeredBase::LayeredBase(), LeastSquaresFit::LeastSquaresFit(), MooseApp::loadLibraryAndDependencies(), LockFile::LockFile(), MaterialVectorPostprocessor::MaterialVectorPostprocessor(), MemoryUsageReporter::MemoryUsageReporter(), MultiAppGeneralFieldTransfer::MultiAppGeneralFieldTransfer(), NonlocalIntegratedBC::NonlocalIntegratedBC(), NonlocalKernel::NonlocalKernel(), MultiAppGeneralFieldTransfer::outputValueConflicts(), MooseBaseParameterInterface::paramWarning(), Moose::PetscSupport::processPetscFlags(), MooseMeshXYCuttingUtils::quadToTriOnLine(), MooseMeshXYCuttingUtils::quasiTriElementsFixer(), MooseUtils::serialBegin(), MooseUtils::serialEnd(), Moose::SlepcSupport::setEigenProblemSolverParams(), MooseApp::setupOptions(), ShapeUserObject< T >::ShapeUserObject(), NonlinearSystem::solve(), Tecplot::Tecplot(), InputParameters::transferParam(), Checkpoint::updateCheckpointFiles(), DerivativeMaterialInterface< T >::validateCoupling(), DerivativeMaterialInterface< T >::validateDerivativeMaterialPropertyBase(), and LockFile::~LockFile().
operator<<()
template<typename... T> std::ostream & operator<< (std::ostream & os, const std::tuple< T... > & tup)
Definition at line 43 of file MooseError.h.
{
  os << "[";
  print_tuple<0>(os, tup);
  return os << "]";
}
print_tuple()
template<size_t n, typename... T> void print_tuple (std::ostream & os, const std::tuple< T... > & tup)
Definition at line 32 of file MooseError.h.
{
  if constexpr (n < sizeof...(T))
  {
    if (n != 0)
      os << ", ";
    os << std::get<n>(tup);
    print_tuple<n + 1>(os, tup);
  }
}