Zapdos: moose/framework/include/functions/MooseParsedFunctionWrapper.h File Reference
MooseParsedFunctionWrapper.h File Reference
Classes
class MooseParsedFunctionWrapper
A wrapper class for creating and evaluating parsed functions via the libMesh::ParsedFunction interface for fparser.
Functions
template<typename T >
T evaluate (Real, const Point &)
The general evaluation method is not defined.
Function Documentation
evaluate()
template<typename T > T evaluate (Real , const Point &)
The general evaluation method is not defined.
Definition at line 144 of file MooseParsedFunctionWrapper.h.
{
  mooseError("The evaluate method is not defined for this type.");
}
Referenced by DerivativeParsedMaterialHelperTempl< is_ad >::computeQpProperties(), ParsedMaterialHelper< is_ad >::computeQpProperties(), Moose::FunctorBase< T >::operator()(), Moose::FunctorBase< T >::queryFVArgCache(), and Moose::FunctorBase< T >::queryQpCache().