Zapdos: moose/framework/include/base/MooseBaseErrorInterface.h File Reference
MooseBaseErrorInterface.h File Reference
Classes
class MooseBaseErrorInterface
Interface that provides APIs to output errors/warnings/info messages.
Functions
void callMooseErrorRaw (std::string &msg, MooseApp *app)
Function Documentation
callMooseErrorRaw()
void callMooseErrorRaw (std::string & msg, MooseApp * app)
Definition at line 24 of file MooseBaseErrorInterface.C.
{
  app->getOutputWarehouse().mooseConsole();
  std::string prefix;
  if (!app->isUltimateMaster())
    prefix = app->name();
  moose::internal::mooseErrorRaw(msg, prefix);
}
Referenced by MooseBaseErrorInterface::mooseError(), MooseBaseErrorInterface::mooseErrorNonPrefixed(), and MooseBaseParameterInterface::paramError().