Zapdos: moose/framework/src/base/Moose.C File Reference
Moose.C File Reference
Namespaces
namespace Moose
MOOSE now contains C++17 code, so give a reasonable error message stating what the user can do to address this in their environment if C++17 compatibility isn't found.
Functions
void Moose::associateSyntaxInner (Syntax &syntax, ActionFactory &action_factory)
void Moose::registerAll (Factory &f, ActionFactory &af, Syntax &s)
Register objects that are in MOOSE.
void Moose::registerObjects (Factory &factory)
void Moose::registerObjects (Factory &factory, const std::set< std::string > &obj_labels)
void Moose::addActionTypes (Syntax &syntax)
void Moose::registerActions (Syntax &syntax, ActionFactory &action_factory)
Multiple Action class can be associated with a single input file section, in which case all associated Actions will be created and "acted" on when the associated input file section is seen.
void Moose::registerActions (Syntax &syntax, ActionFactory &action_factory, const std::set< std::string > &obj_labels)
void Moose::associateSyntax (Syntax &syntax, ActionFactory &action_factory)
void Moose::setSolverDefaults (FEProblemBase &problem)
MPI_Comm Moose::swapLibMeshComm (MPI_Comm new_comm)
Swap the libMesh MPI communicator out for ours.
bool Moose::colorConsole ()
Returns whether Console coloring is turned on (default: true).
bool Moose::setColorConsole (bool use_color, bool force=false)
Turns color escape sequences on/off for info written to stdout.
Variables
const ExecFlagType EXEC_NONE = registerDefaultExecFlag("NONE")
const ExecFlagType EXEC_INITIAL = registerDefaultExecFlag("INITIAL")
const ExecFlagType EXEC_LINEAR = registerDefaultExecFlag("LINEAR")
const ExecFlagType EXEC_NONLINEAR = registerDefaultExecFlag("NONLINEAR")
const ExecFlagType EXEC_TIMESTEP_END = registerDefaultExecFlag("TIMESTEP_END")
const ExecFlagType EXEC_TIMESTEP_BEGIN = registerDefaultExecFlag("TIMESTEP_BEGIN")
const ExecFlagType EXEC_MULTIAPP_FIXED_POINT_END
const ExecFlagType EXEC_MULTIAPP_FIXED_POINT_BEGIN
const ExecFlagType EXEC_FINAL = registerDefaultExecFlag("FINAL")
const ExecFlagType EXEC_FORCED = registerExecFlag("FORCED")
const ExecFlagType EXEC_FAILED = registerExecFlag("FAILED")
const ExecFlagType EXEC_CUSTOM = registerDefaultExecFlag("CUSTOM")
const ExecFlagType EXEC_SUBDOMAIN = registerExecFlag("SUBDOMAIN")
const ExecFlagType EXEC_ALWAYS = registerExecFlag("ALWAYS")
const ExecFlagType EXEC_PRE_DISPLACE = registerExecFlag("PRE_DISPLACE")
const ExecFlagType EXEC_SAME_AS_MULTIAPP = registerExecFlag("SAME_AS_MULTIAPP")
const ExecFlagType EXEC_PRE_MULTIAPP_SETUP = registerExecFlag("PRE_MULTIAPP_SETUP")
const ExecFlagType EXEC_TRANSFER = registerExecFlag("TRANSFER")
const ExecFlagType EXEC_PRE_KERNELS = registerExecFlag("PRE_KERNELS")
static bool Moose::_color_console = isatty(fileno(stdout))
bool Moose::_warnings_are_errors = false
Variable to toggle any warning into an error (includes deprecated code warnings)
bool Moose::_deprecated_is_error = false
Variable to toggle only deprecated warnings as errors.
bool Moose::_throw_on_error = false
Variable to turn on exceptions during mooseError(), should only be used within MOOSE unit tests or when about to perform threaded operations because exception throwing in threaded regions is safe while aborting is inherently not when singletons are involved (e.g.
bool Moose::_throw_on_warning = false
Variable to turn on exceptions during mooseWarning(), should only be used in MOOSE unit tests.
int Moose::interrupt_signal_number = 0
Used by the signal handler to determine if we should write a checkpoint file out at any point during operation.
bool Moose::show_trace = true
Set to true (the default) to print the stack trace with error and warning messages - false to omit it.
bool Moose::show_multiple = false
Set to false (the default) to display an error message only once for each error call code location (as opposed to every time the code is executed).
Variable Documentation
EXEC_ALWAYS
const ExecFlagType EXEC_ALWAYS = registerExecFlag("ALWAYS")
Definition at line 42 of file Moose.C.
Referenced by Moose::ADWrapperFunctor< T >::ADWrapperFunctor(), Moose::FunctorBase< T >::FunctorBase(), Moose::FunctorBase< T >::operator()(), Moose::RawValueFunctor< T >::RawValueFunctor(), FEProblemBase::shouldPrintExecution(), SetupDebugAction::validParams(), FunctorMaterial::validParams(), GenericFunctorGradientMaterialTempl< is_ad >::validParams(), GenericFunctorMaterialTempl< is_ad >::validParams(), GenericVectorFunctorMaterialTempl< is_ad >::validParams(), and VectorMagnitudeFunctorMaterialTempl< is_ad >::validParams().
EXEC_CUSTOM
const ExecFlagType EXEC_CUSTOM = registerDefaultExecFlag("CUSTOM")
Definition at line 40 of file Moose.C.
Referenced by EigenExecutionerBase::postExecute(), and DiscreteElementUserObject::validParams().
EXEC_FAILED
const ExecFlagType EXEC_FAILED = registerExecFlag("FAILED")
Definition at line 39 of file Moose.C.
Referenced by AdvancedOutput::addValidParams(), Output::getDefaultExecFlagEnum(), FixedPointSolve::solveStep(), SetupDebugAction::validParams(), and Console::validParams().
EXEC_FINAL
const ExecFlagType EXEC_FINAL = registerDefaultExecFlag("FINAL")
Definition at line 37 of file Moose.C.
Referenced by Eigenvalue::execute(), Steady::execute(), Transient::execute(), MultiApp::finalize(), Terminator::initialSetup(), Console::output(), CSV::output(), Output::outputStep(), OversampleOutput::outputStep(), EigenExecutionerBase::postExecute(), Checkpoint::shouldOutput(), PerfGraphOutput::validParams(), and AdvancedOutput::wantOutput().
EXEC_FORCED
const ExecFlagType EXEC_FORCED = registerExecFlag("FORCED")
Definition at line 38 of file Moose.C.
Referenced by Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), OutputWarehouse::outputStep(), Output::shouldOutput(), TransientMultiApp::solveStep(), and AdvancedOutput::wantOutput().
EXEC_INITIAL
const ExecFlagType EXEC_INITIAL = registerDefaultExecFlag("INITIAL")
Definition at line 28 of file Moose.C.
Referenced by MultiAppGeneralFieldTransfer::acceptPointInOriginMesh(), ElementIDOutputAction::act(), AddNodalNormalsAction::act(), DumpObjectsProblem::addAuxVariable(), FEProblemBase::addOutput(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), ChangeOverFixedPointPostprocessor::ChangeOverFixedPointPostprocessor(), ChangeOverTimePostprocessor::ChangeOverTimePostprocessor(), MultiAppGeneralFieldTransfer::closestToPosition(), NearestPositionsDivision::divisionIndex(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), Eigenvalue::execute(), Steady::execute(), PseudoTimestep::execute(), PositionsFunctorValueSampler::execute(), FEProblemBase::execute(), EigenProblem::execute(), Control::getExecuteOptions(), Material::getMaterialByName(), MultiAppGeneralFieldNearestLocationTransfer::getNumDivisions(), MultiAppGeneralFieldNearestLocationTransfer::getNumSources(), MaterialOutputAction::getParams(), NumPositions::getValue(), groupUserObjects(), EigenExecutionerBase::init(), InversePowerMethod::init(), NonlinearEigen::init(), PositionsFunctorValueSampler::initialize(), IntegralPreservingFunctionIC::initialSetup(), RandomICBase::initialSetup(), Console::initialSetup(), EigenExecutionerBase::normalizeSolution(), FEProblemBase::objectSetupHelper(), Console::output(), ControlOutput::output(), OutputOnWarehouse::OutputOnWarehouse(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), Transient::preExecute(), ProjectedStatefulMaterialStorageAction::processProperty(), RandomICBase::RandomICBase(), MultiApp::restore(), ExecuteMooseObjectWarehouse< T >::setup(), RandomData::updateSeeds(), CommonOutputAction::validParams(), GhostingAux::validParams(), Control::validParams(), Console::validParams(), ControlOutput::validParams(), DOFMapOutput::validParams(), Exodus::validParams(), JSONOutput::validParams(), MaterialPropertyDebugOutput::validParams(), Output::validParams(), ReporterDebugOutput::validParams(), MultiAppPositions::validParams(), PseudoTimestep::validParams(), AccumulateReporter::validParams(), ElementQualityChecker::validParams(), GhostingUserObject::validParams(), InterfaceQpUserObjectBase::validParams(), JSONFileReader::validParams(), and MessageFromInput::validParams().
EXEC_LINEAR
const ExecFlagType EXEC_LINEAR = registerDefaultExecFlag("LINEAR")
Definition at line 29 of file Moose.C.
Referenced by SetupResidualDebugAction::act(), EigenExecutionerBase::chebyshev(), FEProblemBase::computeBounds(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), FEProblemBase::computeUserObjectsInternal(), Terminator::execute(), FEProblemBase::execute(), CSV::getVectorPostprocessorFileName(), EigenExecutionerBase::init(), Eigenvalue::init(), EigenExecutionerBase::inversePowerIteration(), EigenExecutionerBase::makeBXConsistent(), FEProblemBase::objectSetupHelper(), Console::output(), JSONOutput::outputReporters(), XMLOutput::outputVectorPostprocessors(), PetscOutputInterface::petscLinearOutput(), EigenExecutionerBase::postExecute(), EigenProblem::postScaleEigenVector(), Moose::FunctorBase< T >::residualSetup(), ExecuteMooseObjectWarehouse< T >::residualSetup(), AuxiliarySystem::setPreviousNewtonSolution(), ExecuteMooseObjectWarehouse< T >::setup(), EigenProblem::solve(), AuxKernelTempl< ComputeValueType >::validParams(), SetupInterface::validParams(), Console::validParams(), TopResidualDebugOutput::validParams(), and FunctorPositions::validParams().
EXEC_MULTIAPP_FIXED_POINT_BEGIN
const ExecFlagType EXEC_MULTIAPP_FIXED_POINT_BEGIN
Initial value:
=
    registerDefaultExecFlag("MULTIAPP_FIXED_POINT_BEGIN")
Definition at line 35 of file Moose.C.
Referenced by Transient::computeConstrainedDT(), Transient::execute(), Transient::incrementStepOrReject(), FixedPointSolve::solve(), and FixedPointSolve::solveStep().
EXEC_MULTIAPP_FIXED_POINT_END
const ExecFlagType EXEC_MULTIAPP_FIXED_POINT_END
Initial value:
=
    registerDefaultExecFlag("MULTIAPP_FIXED_POINT_END")
Definition at line 33 of file Moose.C.
Referenced by Transient::computeConstrainedDT(), Transient::execute(), Transient::incrementStepOrReject(), and FixedPointSolve::solve().
EXEC_NONE
const ExecFlagType EXEC_NONE = registerDefaultExecFlag("NONE")
Definition at line 27 of file Moose.C.
Referenced by DumpObjectsProblem::addAuxVariable(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), FEProblemBase::execute(), CSV::initialSetup(), Output::outputStep(), Checkpoint::outputStep(), OversampleOutput::outputStep(), FEProblemBase::outputStep(), Executor::validParams(), Positions::validParams(), and CSVReader::validParams().
EXEC_NONLINEAR
const ExecFlagType EXEC_NONLINEAR = registerDefaultExecFlag("NONLINEAR")
Definition at line 30 of file Moose.C.
Referenced by FEProblemBase::computeJacobianBlocks(), EigenProblem::computeJacobianBlocks(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeUserObjectsInternal(), Terminator::execute(), FEProblemBase::execute(), CSV::getVectorPostprocessorFileName(), Moose::FunctorBase< T >::jacobianSetup(), ExecuteMooseObjectWarehouse< T >::jacobianSetup(), FEProblemBase::objectSetupHelper(), Console::output(), JSONOutput::outputReporters(), XMLOutput::outputVectorPostprocessors(), PetscOutputInterface::petscNonlinearOutput(), ExecuteMooseObjectWarehouse< T >::setup(), Console::validParams(), TopResidualDebugOutput::validParams(), and VariableResidualNormsDebugOutput::validParams().
EXEC_PRE_DISPLACE
const ExecFlagType EXEC_PRE_DISPLACE = registerExecFlag("PRE_DISPLACE")
Definition at line 43 of file Moose.C.
Referenced by FEProblemBase::computeJacobianBlocks(), EigenProblem::computeJacobianBlocks(), FEProblemBase::computeJacobianTags(), FEProblemBase::computeResidualAndJacobian(), FEProblemBase::computeResidualTags(), and AuxKernelTempl< ComputeValueType >::validParams().
EXEC_PRE_KERNELS
const ExecFlagType EXEC_PRE_KERNELS = registerExecFlag("PRE_KERNELS")
Definition at line 47 of file Moose.C.
Referenced by NonlinearSystemBase::computeJacobianInternal(), NonlinearSystemBase::computeResidualAndJacobianInternal(), and NonlinearSystemBase::computeResidualInternal().
EXEC_PRE_MULTIAPP_SETUP
const ExecFlagType EXEC_PRE_MULTIAPP_SETUP = registerExecFlag("PRE_MULTIAPP_SETUP")
Definition at line 45 of file Moose.C.
Referenced by Eigenvalue::init(), Steady::init(), Transient::init(), Control::validParams(), MultiApp::validParams(), and Sampler::validParams().
EXEC_SAME_AS_MULTIAPP
const ExecFlagType EXEC_SAME_AS_MULTIAPP = registerExecFlag("SAME_AS_MULTIAPP")
Definition at line 44 of file Moose.C.
Referenced by FEProblemBase::addTransfer(), and MultiAppTransfer::validParams().
EXEC_SUBDOMAIN
const ExecFlagType EXEC_SUBDOMAIN = registerExecFlag("SUBDOMAIN")
Definition at line 41 of file Moose.C.
Referenced by FEProblemBase::execute(), FEProblemBase::objectSetupHelper(), and ExecuteMooseObjectWarehouse< T >::setup().
EXEC_TIMESTEP_BEGIN
const ExecFlagType EXEC_TIMESTEP_BEGIN = registerDefaultExecFlag("TIMESTEP_BEGIN")
Definition at line 32 of file Moose.C.
Referenced by AddNodalNormalsAction::act(), AddPeriodicRelativeNodalDifference::addNormalizationKernels(), AddPeriodicRelativeNodalDifference::addPerviousSolutionsKernels(), AddPeriodicControllers::AddTimePeriod(), AddPeriodicRelativeNodalDifference::AddTimePeriod(), Transient::computeConstrainedDT(), Transient::execute(), FEProblemBase::execute(), TransientMultiApp::finishStep(), Transient::incrementStepOrReject(), FEProblemBase::objectSetupHelper(), ExecuteMooseObjectWarehouse< T >::setup(), FixedPointSolve::solve(), FixedPointSolve::solveStep(), NonlinearEigen::takeStep(), Moose::FunctorBase< T >::timestepSetup(), ElementUOAux::validParams(), MultiApp::validParams(), Console::validParams(), ControlOutput::validParams(), FunctorPositions::validParams(), FunctorTimes::validParams(), SimulationTimes::validParams(), Transfer::validParams(), ElemSideNeighborLayersTester::validParams(), and RadialAverage::validParams().
EXEC_TIMESTEP_END
const ExecFlagType EXEC_TIMESTEP_END = registerDefaultExecFlag("TIMESTEP_END")
Definition at line 31 of file Moose.C.
Referenced by SetupResidualDebugAction::act(), Transient::computeConstrainedDT(), Transient::endStep(), Eigenvalue::execute(), Steady::execute(), Transient::execute(), PseudoTimestep::execute(), TransientMultiApp::finishStep(), Control::getExecuteOptions(), MaterialOutputAction::getParams(), Transient::incrementStepOrReject(), NonlinearEigen::init(), Console::output(), ProgressOutput::output(), EigenExecutionerBase::postExecute(), ProjectedStatefulMaterialStorageAction::processProperty(), FixedPointSolve::solve(), FixedPointSolve::solveStep(), TagAuxBase< T >::TagAuxBase(), InversePowerMethod::takeStep(), NonlinearEigen::takeStep(), CommonOutputAction::validParams(), AuxKernelTempl< ComputeValueType >::validParams(), GhostingAux::validParams(), TagAuxBase< T >::validParams(), Control::validParams(), Console::validParams(), Output::validParams(), ProgressOutput::validParams(), TopResidualDebugOutput::validParams(), PseudoTimestep::validParams(), AccumulateReporter::validParams(), InterfaceQpUserObjectBase::validParams(), and UserObject::validParams().
EXEC_TRANSFER
const ExecFlagType EXEC_TRANSFER = registerExecFlag("TRANSFER")
Definition at line 46 of file Moose.C.
Referenced by MultiAppConservativeTransfer::adjustTransferredSolution(), MultiAppConservativeTransfer::adjustTransferredSolutionNearestPoint(), MultiAppConservativeTransfer::initialSetup(), MultiAppConservativeTransfer::postExecute(), SetupDebugAction::validParams(), and Postprocessor::validParams().