Zapdos: moose::internal Namespace Reference
moose::internal Namespace Reference
Classes
class ExecFlagRegistry
Registry for statically defining execute flags with consistent numbering.
class PerfGraphRegistry
The place where all timed sections will be stored.
class PerfGraphSectionInfo
Used to hold metadata about the registered sections Note: this is a class instead of a struct because structs are not able to be created in place using emplace_back in C++11.
struct SoltionInvalidityNameHash
Helper class that hash the name associated with an invalid solution.
class SolutionInvalidityInfo
Helper class that stores the info associated with an invalid solution.
class SolutionInvalidityName
Helper class that stores the name associated with an invalid solution.
class SolutionInvalidityRegistry
The place where all sections with solution invalid warnings will be stored.
Functions
std::string incompatVarMsg (MooseVariableFieldBase &var1, MooseVariableFieldBase &var2)
Builds and returns a string of the form:
std::string mooseMsgFmt (const std::string &msg, const std::string &title, const std::string &color)
Format a message for output with a title.
std::string mooseMsgFmt (const std::string &msg, const std::string &color)
Format a message for output without a title.
void mooseErrorRaw (std::string msg, const std::string prefix)
bool boundaryRestricted (const std::set< BoundaryID > &boundary_ids)
SolutionInvalidityRegistry & getSolutionInvalidityRegistry ()
Get the global SolutionInvalidityRegistry singleton.
std::ostream & operator<< (std::ostream &os, const SolutionInvalidityName &name)
PerfGraphRegistry & getPerfGraphRegistry ()
Get the global PerfGraphRegistry singleton.
template<typename T1 , typename T2 >
void rawValueEqualityHelper (T1 &out, const T2 &in)
template<typename T1 , typename T2 >
void rawValueEqualityHelper (std::vector< T1 > &out, const std::vector< T2 > &in)
template<typename T1 , typename T2 , std::size_t N>
void rawValueEqualityHelper (std::array< T1, N > &out, const std::array< T2, N > &in)
void mooseStreamAll (std::ostringstream &ss)
All of the following are not meant to be called directly - they are called by the normal macros (mooseError(), etc.) down below.
template<typename T , typename... Args>
void mooseStreamAll (std::ostringstream &ss, T &&val, Args &&... args)
template<typename S , typename... Args>
void mooseWarningStream (S &oss, Args &&... args)
template<typename S , typename... Args>
void mooseUnusedStream (S &oss, Args &&... args)
template<typename S , typename... Args>
void mooseInfoStreamRepeated (S &oss, Args &&... args)
template<typename S , typename... Args>
void mooseInfoStream (S &oss, Args &&... args)
template<typename S , typename... Args>
void mooseDeprecatedStream (S &oss, const bool expired, const bool print_title, Args &&... args)
Variables
Threads::spin_mutex moose_stream_lock
Function Documentation
boundaryRestricted()
bool moose::internal::boundaryRestricted (const std::set< BoundaryID > & boundary_ids)
Definition at line 42 of file MaterialPropertyInterface.C.
{
  return !boundary_ids.empty() && BoundaryRestrictable::restricted(boundary_ids);
}
Referenced by MaterialPropertyInterface::getMaterialDataType().
getPerfGraphRegistry()
PerfGraphRegistry & moose::internal::getPerfGraphRegistry ()
Get the global PerfGraphRegistry singleton.
So it can be constructed.
Definition at line 20 of file PerfGraphRegistry.C.
{
  // In C++11 this is even thread safe! (Lookup "Static Initializers")
  static PerfGraphRegistry perf_graph_registry_singleton;
  return perf_graph_registry_singleton;
}
Referenced by PerfGraphInterface::registerTimedSection(), and to_json().
getSolutionInvalidityRegistry()
SolutionInvalidityRegistry & moose::internal::getSolutionInvalidityRegistry ()
Get the global SolutionInvalidityRegistry singleton.
So it can be constructed.
Definition at line 18 of file SolutionInvalidityRegistry.C.
{
  // In C++11 this is even thread safe! (Lookup "Static Initializers")
  static SolutionInvalidityRegistry solution_invalid_registry_singleton;
  return solution_invalid_registry_singleton;
}
Referenced by SolutionInvalidInterface::registerInvalidSolutionInternal(), SolutionInvalidity::sync(), and to_json().
incompatVarMsg()
std::string moose::internal::incompatVarMsg (MooseVariableFieldBase & var1, MooseVariableFieldBase & var2)
Builds and returns a string of the form:
[var1-elemtype],ORDER[var1-order] != [var2-elemtype],ORDER[var2-order]
This is a convenience function to be used when error messages (especially with paramError) need to report that variable types are incompatible (e.g. with residual save-in).
Definition at line 23 of file MooseError.C.
{
  std::stringstream ss;
  ss << libMesh::Utility::enum_to_string<FEFamily>(var1.feType().family) << ",ORDER"
     << var1.feType().order
     << " != " << libMesh::Utility::enum_to_string<FEFamily>(var2.feType().family) << ",ORDER"
     << var2.feType().order;
  return ss.str();
}
Referenced by ADDGKernel::ADDGKernel(), ADIntegratedBCTempl< T >::ADIntegratedBCTempl(), ADKernelTempl< T >::ADKernelTempl(), ArrayDGKernel::ArrayDGKernel(), ArrayIntegratedBC::ArrayIntegratedBC(), ArrayKernel::ArrayKernel(), DGKernel::DGKernel(), IntegratedBC::IntegratedBC(), Kernel::Kernel(), NodalBC::NodalBC(), NodalKernel::NodalKernel(), and MultiAppDofCopyTransfer::transfer().
mooseDeprecatedStream()
template<typename S , typename... Args> void moose::internal::mooseDeprecatedStream (S & oss, const bool expired, const bool print_title, Args &&... args)
Definition at line 236 of file MooseError.h.
{
  if (Moose::_deprecated_is_error)
    mooseError("\n\nDeprecated code:\n", std::forward<Args>(args)...);
  std::ostringstream ss;
  mooseStreamAll(ss, args...);
  const auto color = expired ? COLOR_RED : COLOR_YELLOW;
  std::string msg =
      print_title
          ? mooseMsgFmt(
                ss.str(),
                "*** Warning, This code is deprecated and will be removed in future versions:",
                color)
          : mooseMsgFmt(ss.str(), color);
  oss << msg;
  ss.str("");
  if (Moose::show_trace)
  {
    if (libMesh::global_n_processors() == 1)
      print_trace(ss);
    else
      libMesh::write_traceout();
    {
      Threads::spin_mutex::scoped_lock lock(moose_stream_lock);
      oss << ss.str() << std::endl;
    };
  };
}
Referenced by InputParameters::attemptPrintDeprecated(), mooseDeprecated(), MooseBaseErrorInterface::mooseDeprecated(), and mooseDeprecationExpired().
mooseErrorRaw()
void moose::internal::mooseErrorRaw (std::string msg, const std::string prefix)
Definition at line 50 of file MooseError.C.
{
  if (Moose::_throw_on_error)
    throw std::runtime_error(msg);
  msg = mooseMsgFmt(msg, "*** ERROR ***", COLOR_RED);
  std::ostringstream oss;
  oss << msg << "\n";
  // this independent flush of the partial error message (i.e. without the
  // trace) is here because trace retrieval can be slow in some
  // circumstances, and we want to get the error message out ASAP.
  msg = oss.str();
  if (!prefix.empty())
    MooseUtils::indentMessage(prefix, msg);
  {
    Threads::spin_mutex::scoped_lock lock(moose_stream_lock);
    Moose::err << msg << std::flush;
  }
  oss.str("");
  if (Moose::show_trace && libMesh::global_n_processors() == 1)
    print_trace(oss);
  msg = oss.str();
  if (!prefix.empty())
    MooseUtils::indentMessage(prefix, msg);
  {
    Threads::spin_mutex::scoped_lock lock(moose_stream_lock);
    Moose::err << msg << std::flush;
    if (libMesh::global_n_processors() > 1)
      libMesh::write_traceout();
  }
  MOOSE_ABORT;
}
Referenced by callMooseErrorRaw(), and mooseError().
mooseInfoStream()
template<typename S , typename... Args> void moose::internal::mooseInfoStream (S & oss, Args &&... args)
Definition at line 229 of file MooseError.h.
{
  mooseDoOnce(mooseInfoStreamRepeated(oss, args...););
}
Referenced by mooseInfo(), and MooseBaseErrorInterface::mooseInfo().
mooseInfoStreamRepeated()
template<typename S , typename... Args> void moose::internal::mooseInfoStreamRepeated (S & oss, Args &&... args)
Definition at line 216 of file MooseError.h.
{
  std::ostringstream ss;
  mooseStreamAll(ss, args...);
  std::string msg = mooseMsgFmt(ss.str(), "*** Info ***", COLOR_CYAN);
  {
    Threads::spin_mutex::scoped_lock lock(moose_stream_lock);
    oss << msg << std::flush;
  }
}
Referenced by mooseInfoRepeated(), and mooseInfoStream().
mooseMsgFmt() [1/2]
std::string moose::internal::mooseMsgFmt (const std::string & msg, const std::string & color)
Format a message for output without a title.
Parameters
msg The message to print
color The color to print the message in
Returns
The formatted message
Definition at line 42 of file MooseError.C.
{
  std::ostringstream oss;
  oss << "\n" << color << "\n" << msg << COLOR_DEFAULT << "\n";
  return oss.str();
}
mooseMsgFmt() [2/2]
std::string moose::internal::mooseMsgFmt (const std::string & msg, const std::string & title, const std::string & color)
Format a message for output with a title.
Parameters
msg The message to print
title The title that will go on a line before the message
color The color to print the message in
Returns
The formatted message
Definition at line 34 of file MooseError.C.
{
  std::ostringstream oss;
  oss << "\n" << color << "\n" << title << "\n" << msg << COLOR_DEFAULT << "\n";
  return oss.str();
}
Referenced by mooseDeprecatedStream(), mooseErrorRaw(), mooseInfoStreamRepeated(), mooseUnusedStream(), and mooseWarningStream().
mooseStreamAll() [1/2]
void moose::internal::mooseStreamAll (std::ostringstream &)
All of the following are not meant to be called directly - they are called by the normal macros (mooseError(), etc.) down below.
Definition at line 91 of file MooseError.C.
{
}
Referenced by mooseDeprecatedStream(), mooseError(), MooseBaseErrorInterface::mooseError(), MooseBaseErrorInterface::mooseErrorNonPrefixed(), mooseInfoStreamRepeated(), mooseStreamAll(), mooseUnusedStream(), mooseWarningStream(), and MooseBaseParameterInterface::paramErrorMsg().
mooseStreamAll() [2/2]
template<typename T , typename... Args> void moose::internal::mooseStreamAll (std::ostringstream & ss, T && val, Args &&... args)
Definition at line 173 of file MooseError.h.
{
  ss << val;
  mooseStreamAll(ss, std::forward<Args>(args)...);
}
mooseUnusedStream()
template<typename S , typename... Args> void moose::internal::mooseUnusedStream (S & oss, Args &&... args)
Definition at line 200 of file MooseError.h.
{
  std::ostringstream ss;
  mooseStreamAll(ss, args...);
  std::string msg = mooseMsgFmt(ss.str(), "*** Warning ***", COLOR_YELLOW);
  if (Moose::_throw_on_warning)
    throw std::runtime_error(msg);
  {
    Threads::spin_mutex::scoped_lock lock(moose_stream_lock);
    oss << msg << std::flush;
  }
}
Referenced by mooseUnused().
mooseWarningStream()
template<typename S , typename... Args> void moose::internal::mooseWarningStream (S & oss, Args &&... args)
Definition at line 181 of file MooseError.h.
{
  if (Moose::_warnings_are_errors)
    mooseError(std::forward<Args>(args)...);
  std::ostringstream ss;
  mooseStreamAll(ss, args...);
  std::string msg = mooseMsgFmt(ss.str(), "*** Warning ***", COLOR_YELLOW);
  if (Moose::_throw_on_warning)
    throw std::runtime_error(msg);
  {
    Threads::spin_mutex::scoped_lock lock(moose_stream_lock);
    oss << msg << std::flush;
  }
}
Referenced by mooseWarning(), MooseBaseErrorInterface::mooseWarning(), and MooseBaseErrorInterface::mooseWarningNonPrefixed().
operator<<()
std::ostream & moose::internal::operator<< (std::ostream & os, const SolutionInvalidityName & name)
Definition at line 42 of file SolutionInvalidityRegistry.C.
{
  os << name.object_type << ": " << name.message;
  return os;
}
rawValueEqualityHelper() [1/3]
template<typename T1 , typename T2 , std::size_t N> void moose::internal::rawValueEqualityHelper (std::array< T1, N > & out, const std::array< T2, N > & in)
Definition at line 233 of file MaterialProperty.h.
{
  for (MooseIndex(in) i = 0; i < in.size(); ++i)
    rawValueEqualityHelper(out[i], in[i]);
}
rawValueEqualityHelper() [2/3]
template<typename T1 , typename T2 > void moose::internal::rawValueEqualityHelper (std::vector< T1 > & out, const std::vector< T2 > & in)
Definition at line 224 of file MaterialProperty.h.
{
  out.resize(in.size());
  for (MooseIndex(in) i = 0; i < in.size(); ++i)
    rawValueEqualityHelper(out[i], in[i]);
}
rawValueEqualityHelper() [3/3]
template<typename T1 , typename T2 > void moose::internal::rawValueEqualityHelper (T1 & out, const T2 & in)
Definition at line 217 of file MaterialProperty.h.
{
  out = MetaPhysicL::raw_value(in);
}
Referenced by MaterialPropertyBase< T, is_ad >::qpCopy(), rawValueEqualityHelper(), and MaterialPropertyBase< T, is_ad >::swap().
Variable Documentation
moose_stream_lock
Threads::spin_mutex moose::internal::moose_stream_lock inline
Definition at line 134 of file MooseError.h.
Referenced by mooseDeprecatedStream(), mooseErrorRaw(), mooseInfoStreamRepeated(), mooseUnusedStream(), and mooseWarningStream().