Zapdos: Moose::FV Namespace Reference
Moose::FV Namespace Reference
Classes
class CentralDifferenceLimiter
Implements a limiter which reproduces a central-differencing scheme, defined by $\beta(r_f) = 1$.
class Limiter
Base class for defining slope limiters for finite volume or potentially reconstructed Discontinuous-Galerkin applications.
struct LimiterValueType
struct LimiterValueType< ADReal >
struct LimiterValueType< Real >
struct LimiterValueType< T, typename std::enable_if< HasMemberType_value_type< T >::value >::type >
class MinModLimiter
Implements the Min-Mod limiter, defined by $\beta(r_f) = \text{max}(0, \text{min}(1, r_f))$.
class QUICKLimiter
Implements a limiter which reproduces the QUICK scheme, defined by $\beta(r_f) = \frac{3+r_f}{4}$.
class SOULimiter
Implements a limiter which reproduces the second-order-upwind scheme, defined by $\beta(r_f) = r_f$.
class UpwindLimiter
Implements a limiter which reproduces the upwind scheme, defined by $\beta(r_f) = 0$.
class VanLeerLimiter
Implements the Van Leer limiter, defined by $\beta(r_f) = \frac{r_f + \text{abs}(r_f)}{1 + \text{abs}(r_f)}$.
Enumerations
enum class LimiterType : int {
VanLeer = 0 , Upwind , CentralDifference , MinMod ,
SOU , QUICK
}
enum class InterpMethod {
Average , HarmonicAverage , SkewCorrectedAverage , Upwind ,
RhieChow , VanLeer , MinMod , SOU ,
QUICK
}
This codifies a set of available ways to interpolate with elem+neighbor solution information to calculate values (e.g.
Functions
LimiterType limiterType (InterpMethod interp_method)
Return the limiter type associated with the supplied interpolation method.
bool elemHasFaceInfo (const Elem &elem, const Elem *const neighbor)
This function infers based on elements if the faceinfo between them belongs to the element or not.
template<typename OutputType >
std::tuple< const Elem *, const Elem *, bool > determineElemOneAndTwo (const FaceInfo &fi, const MooseVariableFV< OutputType > &var)
This utility determines element one and element two given a FaceInfo fi and variable var.
template std::tuple< const Elem *, const Elem *, bool > determineElemOneAndTwo (const FaceInfo &fi, const MooseVariableFV< Real > &var)
ADReal gradUDotNormal (const FaceInfo &face_info, const MooseVariableFV< Real > &fv_var, const Moose::StateArg &time, bool correct_skewness=false)
Calculates and returns "grad_u dot normal" on the face to be used for diffusive terms.
bool onBoundary (const std::set< SubdomainID > &subs, const FaceInfo &fi)
Determine whether the passed-in face is on the boundary of an object that lives on the provided subdomains.
MooseEnum interpolationMethods ()
Returns an enum with all the currently supported interpolation methods and the current default for FV: first-order upwind.
InputParameters advectedInterpolationParameter ()
InterpMethod selectInterpolationMethod (const std::string &interp_method)
bool setInterpolationMethod (const MooseObject &obj, Moose::FV::InterpMethod &interp_method, const std::string &param_name)
Sets one interpolation method.
template<typename ActionFunctor >
void loopOverElemFaceInfo (const Elem &elem, const MooseMesh &mesh, ActionFunctor &act, const Moose::CoordinateSystemType coord_type, const unsigned int rz_radial_coord=libMesh::invalid_uint)
template<typename T , typename Enable = typename std::enable_if<ScalarTraits<T>::value>::type>
VectorValue< T > greenGaussGradient (const ElemArg &elem_arg, const StateArg &state_arg, const FunctorBase< T > &functor, const bool two_term_boundary_expansion, const MooseMesh &mesh)
Compute a cell gradient using the method of Green-Gauss.
template<typename T , typename Enable = typename std::enable_if<ScalarTraits<T>::value>::type>
VectorValue< T > greenGaussGradient (const FaceArg &face_arg, const StateArg &state_arg, const FunctorBase< T > &functor, const bool two_term_boundary_expansion, const MooseMesh &mesh)
Compute a face gradient from Green-Gauss cell gradients, with orthogonality correction On the boundaries, the boundary element value is used.
template<typename T >
TensorValue< T > greenGaussGradient (const ElemArg &elem_arg, const StateArg &state_arg, const Moose::FunctorBase< VectorValue< T > > &functor, const bool two_term_boundary_expansion, const MooseMesh &mesh)
template<typename T >
TensorValue< T > greenGaussGradient (const FaceArg &face_arg, const StateArg &state_arg, const Moose::FunctorBase< VectorValue< T > > &functor, const bool two_term_boundary_expansion, const MooseMesh &mesh)
template<typename T >
Moose::FunctorBase< std::vector< T > >::GradientType greenGaussGradient (const ElemArg &elem_arg, const StateArg &state_arg, const Moose::FunctorBase< std::vector< T > > &functor, const bool two_term_boundary_expansion, const MooseMesh &mesh)
template<typename T >
Moose::FunctorBase< std::vector< T > >::GradientType greenGaussGradient (const FaceArg &face_arg, const StateArg &state_arg, const Moose::FunctorBase< std::vector< T > > &functor, const bool two_term_boundary_expansion, const MooseMesh &mesh)
template<typename T , std::size_t N>
Moose::FunctorBase< std::array< T, N > >::GradientType greenGaussGradient (const ElemArg &elem_arg, const StateArg &state_arg, const Moose::FunctorBase< std::array< T, N > > &functor, const bool two_term_boundary_expansion, const MooseMesh &mesh)
template<typename T , std::size_t N>
Moose::FunctorBase< std::array< T, N > >::GradientType greenGaussGradient (const FaceArg &face_arg, const StateArg &state_arg, const Moose::FunctorBase< std::array< T, N > > &functor, const bool two_term_boundary_expansion, const MooseMesh &mesh)
template<typename Vector = RealVectorValue>
std::pair< Real, Real > interpCoeffs (const InterpMethod m, const FaceInfo &fi, const bool one_is_elem, const Vector advector=Vector())
Produce the interpolation coefficients in the equation:
template<typename T , typename T2 >
libMesh::CompareTypes< T, T2 >::supertype linearInterpolation (const T &value1, const T2 &value2, const FaceInfo &fi, const bool one_is_elem, const InterpMethod interp_method=InterpMethod::Average)
A simple linear interpolation of values between cell centers to a cell face.
template<typename T1 , typename T2 >
libMesh::CompareTypes< T1, T2 >::supertype harmonicInterpolation (const T1 &value1, const T2 &value2, const FaceInfo &fi, const bool one_is_elem)
Computes the harmonic mean (1/(gc/value1+(1-gc)/value2)) of Reals, RealVectorValues and RealTensorValues while accounting for the possibility that one or both of them are AD.
template<typename T , typename T2 , typename T3 >
libMesh::CompareTypes< T, T2 >::supertype skewCorrectedLinearInterpolation (const T &value1, const T2 &value2, const T3 &face_gradient, const FaceInfo &fi, const bool one_is_elem)
Linear interpolation with skewness correction using the face gradient.
template<typename T , typename T2 , typename T3 >
void interpolate (InterpMethod m, T &result, const T2 &value1, const T3 &value2, const FaceInfo &fi, const bool one_is_elem)
Provides interpolation of face values for non-advection-specific purposes (although it can/will still be used by advective kernels sometimes).
template<typename T >
T linearInterpolation (const FunctorBase< T > &functor, const FaceArg &face, const StateArg &time)
perform a possibly skew-corrected linear interpolation by evaluating the supplied functor with the provided functor face argument
template<typename T1 , typename T2 , typename T3 , template< typename > class Vector1, template< typename > class Vector2>
void interpolate (InterpMethod m, Vector1< T1 > &result, const T2 &fi_elem_advected, const T2 &fi_neighbor_advected, const Vector2< T3 > &fi_elem_advector, const Vector2< T3 > &fi_neighbor_advector, const FaceInfo &fi)
Computes the product of the advected and the advector based on the given interpolation method.
template<typename T , typename T2 , typename T3 , typename Vector >
void interpolate (InterpMethod m, T &result, const T2 &value1, const T3 &value2, const Vector &advector, const FaceInfo &fi, const bool one_is_elem)
Provides interpolation of face values for advective flux kernels.
template<typename Scalar , typename Vector >
Scalar rF (const Scalar &phiC, const Scalar &phiD, const Vector &gradC, const RealVectorValue &dCD)
From Moukalled 12.30.
template<typename T >
std::pair< T, T > interpCoeffs (const Limiter< T > &limiter, const T &phi_upwind, const T &phi_downwind, const VectorValue< T > *const grad_phi_upwind, const FaceInfo &fi, const bool fi_elem_is_upwind)
Produce the interpolation coefficients in the equation:
template<typename Scalar , typename Vector , typename Enable = typename std::enable_if<ScalarTraits<Scalar>::value>::type>
Scalar interpolate (const Limiter< Scalar > &limiter, const Scalar &phi_upwind, const Scalar &phi_downwind, const Vector *const grad_phi_upwind, const FaceInfo &fi, const bool fi_elem_is_upwind)
Interpolates with a limiter.
template<typename Limiter , typename T , typename Tensor >
VectorValue< T > interpolate (const Limiter &limiter, const TypeVector< T > &phi_upwind, const TypeVector< T > &phi_downwind, const Tensor *const grad_phi_upwind, const FaceInfo &fi, const bool fi_elem_is_upwind)
Vector overload.
template<typename T , typename Enable = typename std::enable_if<ScalarTraits<T>::value>::type>
std::pair< std::pair< T, T >, std::pair< T, T > > interpCoeffsAndAdvected (const FunctorBase< T > &functor, const FaceArg &face, const StateArg &time)
Interpolates with a limiter and a face argument.
template<typename T , typename Enable = typename std::enable_if<ScalarTraits<T>::value>::type>
T interpolate (const FunctorBase< T > &functor, const FaceArg &face, const StateArg &time)
template<typename T >
VectorValue< T > interpolate (const FunctorBase< VectorValue< T > > &functor, const FaceArg &face, const StateArg &time)
template<typename T >
T containerInterpolate (const FunctorBase< T > &functor, const FaceArg &face, const StateArg &time)
template<typename T >
std::vector< T > interpolate (const FunctorBase< std::vector< T > > &functor, const FaceArg &face, const StateArg &time)
template<typename T , std::size_t N>
std::array< T, N > interpolate (const FunctorBase< std::array< T, N > > &functor, const FaceArg &face, const StateArg &time)
template<typename SubdomainRestrictable >
bool onBoundary (const SubdomainRestrictable &obj, const FaceInfo &fi)
Return whether the supplied face is on a boundary of the object's execution.
Variables
const MooseEnum moose_limiter_type
Enumeration Type Documentation
InterpMethod
enum class Moose::FV::InterpMethod strong
This codifies a set of available ways to interpolate with elem+neighbor solution information to calculate values (e.g.
solution, material properties, etc.) at the face (centroid). These methods are used in the class's interpolate functions. Some interpolation methods are only meant to be used with advective terms (e.g. upwind), others are more generically applicable.
Enumerator
Average
gc*elem+(1-gc)*neighbor
HarmonicAverage
1/(gc/elem+(1-gc)/neighbor)
SkewCorrectedAverage
(gc*elem+(1-gc)*neighbor)+gradient*(rf-rf')
Upwind
weighted
RhieChow
VanLeer
MinMod
SOU
QUICK
Definition at line 35 of file MathFVUtils.h.
{
  Average,
  HarmonicAverage,
  SkewCorrectedAverage,
  Upwind,
  // Rhie-Chow
  RhieChow,
  VanLeer,
  MinMod,
  SOU,
  QUICK
};
LimiterType
enum class Moose::FV::LimiterType : int strong
Enumerator
VanLeer
Upwind
CentralDifference
MinMod
SOU
QUICK
Definition at line 25 of file Limiter.h.
{
  VanLeer = 0,
  Upwind,
  CentralDifference,
  MinMod,
  SOU,
  QUICK
};
Function Documentation
advectedInterpolationParameter()
InputParameters Moose::FV::advectedInterpolationParameter ()
Returns
An input parameters object that contains the advected_interp_method parameter, e.g. the interpolation method to use for an advected quantity
Definition at line 67 of file MathFVUtils.C.
{
  auto params = emptyInputParameters();
  params.addParam<MooseEnum>(
      "advected_interp_method",
      interpolationMethods(),
      "The interpolation to use for the advected quantity. Options are "
      "'upwind', 'average', 'sou' (for second-order upwind), 'min_mod', 'vanLeer', 'quick', and "
      "'skewness-corrected' with the default being 'upwind'.");
  return params;
}
Referenced by FVAdvection::validParams().
containerInterpolate()
template<typename T > T Moose::FV::containerInterpolate (const FunctorBase< T > & functor, const FaceArg & face, const StateArg & time)
Definition at line 633 of file MathFVUtils.h.
{
  typedef typename FunctorBase<T>::GradientType ContainerGradientType;
  typedef typename ContainerGradientType::value_type GradientType;
  const GradientType * const example_gradient = nullptr;
  mooseAssert(face.fi, "this must be non-null");
  const auto limiter = Limiter<typename T::value_type>::build(face.limiter_type);
  const auto upwind_arg = face.elem_is_upwind ? face.makeElem() : face.makeNeighbor();
  const auto downwind_arg = face.elem_is_upwind ? face.makeNeighbor() : face.makeElem();
  const auto phi_upwind = functor(upwind_arg, time);
  const auto phi_downwind = functor(downwind_arg, time);
  // initialize in order to get proper size
  T ret = phi_upwind;
  typename T::value_type coeff_upwind, coeff_downwind;
  if (face.limiter_type == LimiterType::Upwind ||
      face.limiter_type == LimiterType::CentralDifference)
  {
    for (const auto i : index_range(ret))
    {
      const auto &component_upwind = phi_upwind[i], component_downwind = phi_downwind[i];
      std::tie(coeff_upwind, coeff_downwind) = interpCoeffs(*limiter,
                                                            component_upwind,
                                                            component_downwind,
                                                            example_gradient,
                                                            *face.fi,
                                                            face.elem_is_upwind);
      ret[i] = coeff_upwind * component_upwind + coeff_downwind * component_downwind;
    }
  }
  else
  {
    const auto grad_phi_upwind = functor.gradient(upwind_arg, time);
    for (const auto i : index_range(ret))
    {
      const auto &component_upwind = phi_upwind[i], component_downwind = phi_downwind[i];
      const auto & grad = grad_phi_upwind[i];
      std::tie(coeff_upwind, coeff_downwind) = interpCoeffs(
          *limiter, component_upwind, component_downwind, &grad, *face.fi, face.elem_is_upwind);
      ret[i] = coeff_upwind * component_upwind + coeff_downwind * component_downwind;
    }
  }
  return ret;
}
Referenced by interpolate().
determineElemOneAndTwo() [1/2]
template<typename OutputType > std::tuple< const Elem *, const Elem *, bool > Moose::FV::determineElemOneAndTwo (const FaceInfo & fi, const MooseVariableFV< OutputType > & var)
This utility determines element one and element two given a FaceInfo fi and variable var.
You may ask what in the world "element one" and "element two" means, and that would be a very good question. What it means is: a variable will always have degrees of freedom on element one. A variable may or may not have degrees of freedom on element two. So we are introducing a second terminology here. FaceInfo geometric objects have element-neighbor pairs. These element-neighbor pairs are purely geometric and have no relation to the algebraic system of variables. The elem1-elem2 notation introduced here is based on dof/algebraic information and may very well be different from variable to variable, e.g. elem1 may correspond to the FaceInfo elem for one variable (and correspondingly elem2 will be the FaceInfo neighbor), but elem1 may correspond to the FaceInfo neighbor for another variable (and correspondingly for that variable elem2 will be the FaceInfo elem).
Returns
A tuple, where the first item is elem1, the second item is elem2, and the third item is a boolean indicating whether elem1 corresponds to the FaceInfo elem
Definition at line 38 of file FVUtils.C.
{
  auto ft = fi.faceType(std::make_pair(var.number(), var.sys().number()));
  mooseAssert(ft == FaceInfo::VarFaceNeighbors::BOTH
                  ? var.hasBlocks(fi.elem().subdomain_id()) && fi.neighborPtr() &&
                        var.hasBlocks(fi.neighborPtr()->subdomain_id())
                  : true,
              "Finite volume variable " << var.name()
                                        << " does not exist on both sides of the face despite "
                                           "what the FaceInfo is telling us.");
  mooseAssert(ft == FaceInfo::VarFaceNeighbors::ELEM
                  ? var.hasBlocks(fi.elem().subdomain_id()) &&
                        (!fi.neighborPtr() || !var.hasBlocks(fi.neighborPtr()->subdomain_id()))
                  : true,
              "Finite volume variable " << var.name()
                                        << " does not exist on or only on the elem side of the "
                                           "face despite what the FaceInfo is telling us.");
  mooseAssert(ft == FaceInfo::VarFaceNeighbors::NEIGHBOR
                  ? fi.neighborPtr() && var.hasBlocks(fi.neighborPtr()->subdomain_id()) &&
                        !var.hasBlocks(fi.elem().subdomain_id())
                  : true,
              "Finite volume variable " << var.name()
                                        << " does not exist on or only on the neighbor side of the "
                                           "face despite what the FaceInfo is telling us.");
  const bool one_is_elem =
      ft == FaceInfo::VarFaceNeighbors::BOTH || ft == FaceInfo::VarFaceNeighbors::ELEM;
  const Elem * const elem_one = one_is_elem ? &fi.elem() : fi.neighborPtr();
  mooseAssert(elem_one, "This elem should be non-null!");
  const Elem * const elem_two = one_is_elem ? fi.neighborPtr() : &fi.elem();
  return std::make_tuple(elem_one, elem_two, one_is_elem);
}
determineElemOneAndTwo() [2/2]
template std::tuple< const Elem *, const Elem *, bool > Moose::FV::determineElemOneAndTwo (const FaceInfo & fi, const MooseVariableFV< Real > & var)
elemHasFaceInfo()
bool Moose::FV::elemHasFaceInfo (const Elem & elem, const Elem *const neighbor)
This function infers based on elements if the faceinfo between them belongs to the element or not.
Parameters
elem Reference to an element
neighbor Pointer to the neighbor of the element
Returns
If the element (first argument) is the owner of the faceinfo between the two elements
Definition at line 20 of file FVUtils.C.
{
  // The face info belongs to elem:
  //  * at all mesh boundaries (i.e. where there is no neighbor)
  //  * if the element faces a neighbor which is on a lower refinement level
  //  * if the element is active and it has a lower ID than its neighbor
  if (!neighbor)
    return true;
  else if (elem.level() != neighbor->level())
    return neighbor->level() < elem.level();
  else if (!neighbor->active())
    return false;
  else
    return elem.id() < neighbor->id();
}
Referenced by MooseMesh::buildFiniteVolumeInfo(), and loopOverElemFaceInfo().
gradUDotNormal()
ADReal Moose::FV::gradUDotNormal (const FaceInfo & face_info, const MooseVariableFV< Real > & fv_var, const Moose::StateArg & time, bool correct_skewness = false)
Calculates and returns "grad_u dot normal" on the face to be used for diffusive terms.
If using any cross-diffusion corrections, etc. all those calculations should be handled appropriately by this function.
Definition at line 18 of file MathFVUtils.C.
{
  return fv_var.adGradSln(face_info, time, correct_skewness) * face_info.normal();
}
Referenced by FVFluxKernel::gradUDotNormal().
greenGaussGradient() [1/8]
template<typename T , typename Enable = typename std::enable_if<ScalarTraits<T>::value>::type> VectorValue< T > Moose::FV::greenGaussGradient (const ElemArg & elem_arg, const StateArg & state_arg, const FunctorBase< T > & functor, const bool two_term_boundary_expansion, const MooseMesh & mesh)
Compute a cell gradient using the method of Green-Gauss.
Parameters
elem_arg An element argument specifying the current element and whether to perform skew corrections
state_arg A state argument that indicates what temporal / solution iteration data to use when evaluating the provided functor
functor The functor that will provide information such as cell and face value evaluations necessary to construct the cell gradient
two_term_boundary_expansion Whether to perform a two-term expansion to compute extrapolated boundary face values. If this is true, then an implicit system has to be solved. If false, then the cell center value will be used as the extrapolated boundary face value
mesh The mesh on which we are computing the gradient
Returns
The computed cell gradient
Definition at line 40 of file GreenGaussGradient.h.
{
  mooseAssert(elem_arg.elem, "This should be non-null");
  const auto coord_type = mesh.getCoordSystem(elem_arg.elem->subdomain_id());
  const auto rz_radial_coord = mesh.getAxisymmetricRadialCoord();
  T elem_value = functor(elem_arg, state_arg);
  // We'll count the extrapolated boundaries
  unsigned int num_ebfs = 0;
  try
  {
    VectorValue<T> grad;
    bool volume_set = false;
    Real volume = 0;
    // If we are performing a two term Taylor expansion for extrapolated boundary faces (faces on
    // boundaries that do not have associated Dirichlet conditions), then the element gradient
    // depends on the boundary face value and the boundary face value depends on the element
    // gradient, so we have a system of equations to solve. Here is the system:
    //
    // \nabla \phi_C - \frac{1}{V} \sum_{ebf} \phi_{ebf} \vec{S_f} =
    //   \frac{1}{V} \sum_{of} \phi_{of} \vec{S_f}                       eqn. 1
    //
    // \phi_{ebf} - \vec{d_{Cf}} \cdot \nabla \phi_C = \phi_C            eqn. 2
    //
    // where $C$ refers to the cell centroid, $ebf$ refers to an extrapolated boundary face, $of$
    // refers to "other faces", e.g. non-ebf faces, and $f$ is a general face. $d_{Cf}$ is the
    // vector drawn from the element centroid to the face centroid, and $\vec{S_f}$ is the surface
    // vector, e.g. the face area times the outward facing normal
    // ebf eqns: element gradient coefficients, e.g. eqn. 2, LHS term 2 coefficient
    std::vector<VectorValue<Real>> ebf_grad_coeffs;
    // ebf eqns: rhs b values. These will actually correspond to the elem_value so we can use a
    // pointer and avoid copying. This is the RHS of eqn. 2
    std::vector<const T *> ebf_b;
    // elem grad eqns: ebf coefficients, e.g. eqn. 1, LHS term 2 coefficients
    std::vector<VectorValue<Real>> grad_ebf_coeffs;
    // elem grad eqns: rhs b value, e.g. eqn. 1 RHS
    VectorValue<T> grad_b = 0;
    auto action_functor = [&volume_set,
                           &volume,
                           &elem_value,
                           &elem_arg,
                           &num_ebfs,
                           &ebf_grad_coeffs,
                           &ebf_b,
                           &grad_ebf_coeffs,
                           &grad_b,
                           &state_arg,
                           &functor,
                           two_term_boundary_expansion,
                           coord_type,
                           rz_radial_coord](const Elem & libmesh_dbg_var(functor_elem),
                                            const Elem *,
                                            const FaceInfo * const fi,
                                            const Point & surface_vector,
                                            Real coord,
                                            const bool elem_has_info)
    {
      mooseAssert(fi, "We need a FaceInfo for this action_functor");
      mooseAssert(elem_arg.elem == &functor_elem,
                  "Just a sanity check that the element being passed in is the one we passed out.");
      if (functor.isExtrapolatedBoundaryFace(*fi, elem_arg.elem, state_arg))
      {
        if (two_term_boundary_expansion)
        {
          num_ebfs += 1;
          // eqn. 2
          ebf_grad_coeffs.push_back(-1. * (elem_has_info
                                               ? (fi->faceCentroid() - fi->elemCentroid())
                                               : (fi->faceCentroid() - fi->neighborCentroid())));
          ebf_b.push_back(&elem_value);
          // eqn. 1
          grad_ebf_coeffs.push_back(-surface_vector);
        }
        else
          // We are doing a one-term expansion for the extrapolated boundary faces, in which case we
          // have no eqn. 2 and we have no second term in the LHS of eqn. 1. Instead we apply the
          // element centroid value as the face value (one-term expansion) in the RHS of eqn. 1
          grad_b += surface_vector * elem_value;
      }
      else
        grad_b += surface_vector * functor(Moose::FaceArg{fi,
                                                          Moose::FV::LimiterType::CentralDifference,
                                                          true,
                                                          elem_arg.correct_skewness,
                                                          elem_arg.elem},
                                           state_arg);
      if (!volume_set)
      {
        // We use the FaceInfo volumes because those values have been pre-computed and cached.
        // An explicit call to elem->volume() here would incur unnecessary expense
        if (elem_has_info)
        {
          MooseMeshUtils::coordTransformFactor(
              fi->elemCentroid(), coord, coord_type, rz_radial_coord);
          volume = fi->elemVolume() * coord;
        }
        else
        {
          MooseMeshUtils::coordTransformFactor(
              fi->neighborCentroid(), coord, coord_type, rz_radial_coord);
          volume = fi->neighborVolume() * coord;
        }
        volume_set = true;
      }
    };
    Moose::FV::loopOverElemFaceInfo(
        *elem_arg.elem, mesh, action_functor, coord_type, rz_radial_coord);
    mooseAssert(volume_set && volume > 0, "We should have set the volume");
    grad_b /= volume;
    if (coord_type == Moose::CoordinateSystemType::COORD_RZ)
    {
      mooseAssert(rz_radial_coord != libMesh::invalid_uint, "rz_radial_coord must be set");
      grad_b(rz_radial_coord) -= elem_value / elem_arg.elem->vertex_average()(rz_radial_coord);
    }
    mooseAssert(
        coord_type != Moose::CoordinateSystemType::COORD_RSPHERICAL,
        "We have not yet implemented the correct translation from gradient to divergence for "
        "spherical coordinates yet.");
    // test for simple case
    if (num_ebfs == 0)
      grad = grad_b;
    else
    {
      // We have to solve a system
      const unsigned int sys_dim = Moose::dim + num_ebfs;
      DenseVector<T> x(sys_dim), b(sys_dim);
      DenseMatrix<T> A(sys_dim, sys_dim);
      // Let's make i refer to Moose::dim indices, and j refer to num_ebfs indices
      // eqn. 1
      for (const auto i : make_range(Moose::dim))
      {
        // LHS term 1 coeffs
        A(i, i) = 1;
        // LHS term 2 coeffs
        for (const auto j : make_range(num_ebfs))
          A(i, Moose::dim + j) = grad_ebf_coeffs[j](i) / volume;
        // RHS
        b(i) = grad_b(i);
      }
      // eqn. 2
      for (const auto j : make_range(num_ebfs))
      {
        // LHS term 1 coeffs
        A(Moose::dim + j, Moose::dim + j) = 1;
        // LHS term 2 coeffs
        for (const auto i : make_range(unsigned(Moose::dim)))
          A(Moose::dim + j, i) = ebf_grad_coeffs[j](i);
        // RHS
        b(Moose::dim + j) = *ebf_b[j];
      }
      A.lu_solve(b, x);
      // libMesh is generous about what it considers nonsingular. Let's check a little more strictly
      if (MooseUtils::absoluteFuzzyEqual(MetaPhysicL::raw_value(A(sys_dim - 1, sys_dim - 1)), 0))
        throw libMesh::LogicError("Matrix A is singular!");
      for (const auto i : make_range(Moose::dim))
        grad(i) = x(i);
    }
    return grad;
  }
  catch (libMesh::LogicError & e)
  {
    // Retry without two-term
    if (!two_term_boundary_expansion)
      mooseError(
          "I believe we should only get singular systems when two-term boundary expansion is "
          "being used. The error thrown during the computation of the gradient: ",
          e.what());
    const auto grad = greenGaussGradient(elem_arg, state_arg, functor, false, mesh);
    return grad;
  }
}
Referenced by PiecewiseByBlockLambdaFunctor< T >::evaluateGradient(), and greenGaussGradient().
greenGaussGradient() [2/8]
template<typename T , std::size_t N> Moose::FunctorBase< std::array< T, N > >::GradientType Moose::FV::greenGaussGradient (const ElemArg & elem_arg, const StateArg & state_arg, const Moose::FunctorBase< std::array< T, N > > & functor, const bool two_term_boundary_expansion, const MooseMesh & mesh)
Definition at line 410 of file GreenGaussGradient.h.
{
  typedef typename Moose::FunctorBase<std::array<T, N>>::GradientType GradientType;
  GradientType ret;
  for (const auto i : make_range(N))
  {
    // Note that this can be very inefficient. Within the scalar greenGaussGradient routine we're
    // going to do value type evaluations of the array functor from scalar_functor and we will be
    // discarding all the value type evaluations other than the one corresponding to i
    ArrayComponentFunctor<T, FunctorBase<std::array<T, N>>> scalar_functor(functor, i);
    ret[i] =
        greenGaussGradient(elem_arg, state_arg, scalar_functor, two_term_boundary_expansion, mesh);
  }
  return ret;
}
greenGaussGradient() [3/8]
template<typename T > Moose::FunctorBase< std::vector< T > >::GradientType Moose::FV::greenGaussGradient (const ElemArg & elem_arg, const StateArg & state_arg, const Moose::FunctorBase< std::vector< T > > & functor, const bool two_term_boundary_expansion, const MooseMesh & mesh)
Definition at line 360 of file GreenGaussGradient.h.
{
  // Determine the size of the container
  const auto vals = functor(elem_arg, state_arg);
  typedef typename Moose::FunctorBase<std::vector<T>>::GradientType GradientType;
  GradientType ret(vals.size());
  for (const auto i : index_range(ret))
  {
    // Note that this can be very inefficient. Within the scalar greenGaussGradient routine we're
    // going to do value type evaluations of the array functor from scalar_functor and we will be
    // discarding all the value type evaluations other than the one corresponding to i
    ArrayComponentFunctor<T, FunctorBase<std::vector<T>>> scalar_functor(functor, i);
    ret[i] =
        greenGaussGradient(elem_arg, state_arg, scalar_functor, two_term_boundary_expansion, mesh);
  }
  return ret;
}
greenGaussGradient() [4/8]
template<typename T > TensorValue< T > Moose::FV::greenGaussGradient (const ElemArg & elem_arg, const StateArg & state_arg, const Moose::FunctorBase< VectorValue< T > > & functor, const bool two_term_boundary_expansion, const MooseMesh & mesh)
Definition at line 318 of file GreenGaussGradient.h.
{
  TensorValue<T> ret;
  for (const auto i : make_range(Moose::dim))
  {
    VectorComponentFunctor<T> scalar_functor(functor, i);
    const auto row_gradient =
        greenGaussGradient(elem_arg, state_arg, scalar_functor, two_term_boundary_expansion, mesh);
    for (const auto j : make_range(unsigned(Moose::dim)))
      ret(i, j) = row_gradient(j);
  }
  return ret;
}
greenGaussGradient() [5/8]
template<typename T , typename Enable = typename std::enable_if<ScalarTraits<T>::value>::type> VectorValue< T > Moose::FV::greenGaussGradient (const FaceArg & face_arg, const StateArg & state_arg, const FunctorBase< T > & functor, const bool two_term_boundary_expansion, const MooseMesh & mesh)
Compute a face gradient from Green-Gauss cell gradients, with orthogonality correction On the boundaries, the boundary element value is used.
Parameters
face_arg A face argument specifying the current faceand whether to perform skew corrections
state_arg A state argument that indicates what temporal / solution iteration data to use when evaluating the provided functor
functor The functor that will provide information such as cell and face value evaluations necessary to construct the cell gradient
two_term_boundary_expansion Whether to perform a two-term expansion to compute extrapolated boundary face values. If this is true, then an implicit system has to be solved. If false, then the cell center value will be used as the extrapolated boundary face value
mesh The mesh on which we are computing the gradient
Returns
The computed cell gradient
Definition at line 260 of file GreenGaussGradient.h.
{
  mooseAssert(face_arg.fi, "We should have a face info to compute a face gradient");
  const auto & fi = *(face_arg.fi);
  const auto & elem_arg = face_arg.makeElem();
  const auto & neighbor_arg = face_arg.makeNeighbor();
  const bool defined_on_elem = functor.hasBlocks(fi.elemSubdomainID());
  const bool defined_on_neighbor = fi.neighborPtr() && functor.hasBlocks(fi.neighborSubdomainID());
  if (defined_on_elem && defined_on_neighbor)
  {
    const auto & value_elem = functor(elem_arg, state_arg);
    const auto & value_neighbor = functor(neighbor_arg, state_arg);
    // This is the component of the gradient which is parallel to the line connecting
    // the cell centers. Therefore, we can use our second order, central difference
    // scheme to approximate it.
    VectorValue<T> face_gradient = (value_neighbor - value_elem) / fi.dCNMag() * fi.eCN();
    // We only need nonorthogonal correctors in 2+ dimensions
    if (mesh.dimension() > 1)
    {
      // We are using an orthogonal approach for the non-orthogonal correction, for more information
      // see Hrvoje Jasak's PhD Thesis (Imperial College, 1996)
      VectorValue<T> interpolated_gradient;
      // Compute the gradients in the two cells on both sides of the face
      const auto & grad_elem =
          greenGaussGradient(elem_arg, state_arg, functor, two_term_boundary_expansion, mesh);
      const auto & grad_neighbor =
          greenGaussGradient(neighbor_arg, state_arg, functor, two_term_boundary_expansion, mesh);
      Moose::FV::interpolate(Moose::FV::InterpMethod::Average,
                             interpolated_gradient,
                             grad_elem,
                             grad_neighbor,
                             fi,
                             true);
      face_gradient += interpolated_gradient - (interpolated_gradient * fi.eCN()) * fi.eCN();
    }
    return face_gradient;
  }
  else if (defined_on_elem)
    return functor.gradient(elem_arg, state_arg);
  else if (defined_on_neighbor)
    return functor.gradient(neighbor_arg, state_arg);
  else
    mooseError("The functor must be defined on one of the sides");
}
greenGaussGradient() [6/8]
template<typename T , std::size_t N> Moose::FunctorBase< std::array< T, N > >::GradientType Moose::FV::greenGaussGradient (const FaceArg & face_arg, const StateArg & state_arg, const Moose::FunctorBase< std::array< T, N > > & functor, const bool two_term_boundary_expansion, const MooseMesh & mesh)
Definition at line 433 of file GreenGaussGradient.h.
{
  typedef typename Moose::FunctorBase<std::array<T, N>>::GradientType GradientType;
  GradientType ret;
  for (const auto i : make_range(N))
  {
    // Note that this can be very inefficient. Within the scalar greenGaussGradient routine we're
    // going to do value type evaluations of the array functor from scalar_functor and we will be
    // discarding all the value type evaluations other than the one corresponding to i
    ArrayComponentFunctor<T, FunctorBase<std::array<T, N>>> scalar_functor(functor, i);
    ret[i] =
        greenGaussGradient(face_arg, state_arg, scalar_functor, two_term_boundary_expansion, mesh);
  }
  return ret;
}
greenGaussGradient() [7/8]
template<typename T > Moose::FunctorBase< std::vector< T > >::GradientType Moose::FV::greenGaussGradient (const FaceArg & face_arg, const StateArg & state_arg, const Moose::FunctorBase< std::vector< T > > & functor, const bool two_term_boundary_expansion, const MooseMesh & mesh)
Definition at line 385 of file GreenGaussGradient.h.
{
  // Determine the size of the container
  const auto vals = functor(face_arg, state_arg);
  typedef typename Moose::FunctorBase<std::vector<T>>::GradientType GradientType;
  GradientType ret(vals.size());
  for (const auto i : index_range(ret))
  {
    // Note that this can be very inefficient. Within the scalar greenGaussGradient routine we're
    // going to do value type evaluations of the array functor from scalar_functor and we will be
    // discarding all the value type evaluations other than the one corresponding to i
    ArrayComponentFunctor<T, FunctorBase<std::vector<T>>> scalar_functor(functor, i);
    ret[i] =
        greenGaussGradient(face_arg, state_arg, scalar_functor, two_term_boundary_expansion, mesh);
  }
  return ret;
}
greenGaussGradient() [8/8]
template<typename T > TensorValue< T > Moose::FV::greenGaussGradient (const FaceArg & face_arg, const StateArg & state_arg, const Moose::FunctorBase< VectorValue< T > > & functor, const bool two_term_boundary_expansion, const MooseMesh & mesh)
Definition at line 339 of file GreenGaussGradient.h.
{
  TensorValue<T> ret;
  for (const auto i : make_range(unsigned(Moose::dim)))
  {
    VectorComponentFunctor<T> scalar_functor(functor, i);
    const auto row_gradient =
        greenGaussGradient(face_arg, state_arg, scalar_functor, two_term_boundary_expansion, mesh);
    for (const auto j : make_range(unsigned(Moose::dim)))
      ret(i, j) = row_gradient(j);
  }
  return ret;
}
harmonicInterpolation()
template<typename T1 , typename T2 > libMesh::CompareTypes< T1, T2 >::supertype Moose::FV::harmonicInterpolation (const T1 & value1, const T2 & value2, const FaceInfo & fi, const bool one_is_elem)
Computes the harmonic mean (1/(gc/value1+(1-gc)/value2)) of Reals, RealVectorValues and RealTensorValues while accounting for the possibility that one or both of them are AD.
For tensors, we use a component-wise mean instead of the matrix-inverse based option.
Parameters
value1 Reference to value1 in the (1/(gc/value1+(1-gc)/value2)) expression
value2 Reference to value2 in the (1/(gc/value1+(1-gc)/value2)) expression
fi Reference to the FaceInfo of the face on which the interpolation is requested
one_is_elem Boolean indicating if the interpolation weight on FaceInfo belongs to the element corresponding to value1
Returns
The interpolated value
Definition at line 167 of file MathFVUtils.h.
{
  // We check if the base values of the given template types match, if not we throw a compile-time
  // error
  static_assert(std::is_same<typename MetaPhysicL::RawType<T1>::value_type,
                             typename MetaPhysicL::RawType<T2>::value_type>::value,
                "The input values for harmonic interpolation need to have the same raw-value!");
  // Fetch the interpolation coefficients, we use the exact same coefficients as for a simple
  // weighted average
  const auto coeffs = interpCoeffs(InterpMethod::Average, fi, one_is_elem);
  // We check if the types are fit to compute the harmonic mean of. This is done compile-time
  // using constexpr. We start with Real/ADReal which is straightforward if the input values are
  // positive.
  if constexpr (libMesh::TensorTools::TensorTraits<T1>::rank == 0)
  {
    // The harmonic mean of mixed positive and negative numbers (and 0 as well) is not well-defined
    // so we assert that the input values shall be positive.
#ifndef NDEBUG
    if (value1 * value2 <= 0)
      mooseWarning("Input values (" + Moose::stringify(MetaPhysicL::raw_value(value1)) + " & " +
                   Moose::stringify(MetaPhysicL::raw_value(value2)) +
                   ") must be of the same sign for harmonic interpolation");
#endif
    return 1.0 / (coeffs.first / value1 + coeffs.second / value2);
  }
  // For vectors (ADRealVectorValue, VectorValue), we take the component-wise harmonic mean
  else if constexpr (libMesh::TensorTools::TensorTraits<T1>::rank == 1)
  {
    typename libMesh::CompareTypes<T1, T2>::supertype result;
    for (const auto i : make_range(Moose::dim))
    {
#ifndef NDEBUG
      if (value1(i) * value2(i) <= 0)
        mooseWarning("Component " + std::to_string(i) + " of input values (" +
                     Moose::stringify(MetaPhysicL::raw_value(value1(i))) + " & " +
                     Moose::stringify(MetaPhysicL::raw_value(value2(i))) +
                     ") must be of the same sign for harmonic interpolation");
#endif
      result(i) = 1.0 / (coeffs.first / value1(i) + coeffs.second / value2(i));
    }
    return result;
  }
  // For tensors (ADRealTensorValue, TensorValue), similarly to the vectors,
  // we take the component-wise harmonic mean instead of the matrix-inverse approach
  else if constexpr (libMesh::TensorTools::TensorTraits<T1>::rank == 2)
  {
    typename libMesh::CompareTypes<T1, T2>::supertype result;
    for (const auto i : make_range(Moose::dim))
      for (const auto j : make_range(Moose::dim))
      {
#ifndef NDEBUG
        if (value1(i, j) * value2(i, j) <= 0)
          mooseWarning("Component (" + std::to_string(i) + "," + std::to_string(j) +
                       ") of input values (" +
                       Moose::stringify(MetaPhysicL::raw_value(value1(i, j))) + " & " +
                       Moose::stringify(MetaPhysicL::raw_value(value2(i, j))) +
                       ") must be of the same sign for harmonic interpolation");
#endif
        result(i, j) = 1.0 / (coeffs.first / value1(i, j) + coeffs.second / value2(i, j));
      }
    return result;
  }
  // We ran out of options, harmonic mean is not supported for other types at the moment
  else
    // This line is supposed to throw an error when the user tries to compile this function with
    // types that are not supported. This is the reason we needed the always_false function. Hope as
    // C++ gets nicer, we can do this in a nicer way.
    static_assert(Moose::always_false<T1>,
                  "Harmonic interpolation is not implemented for the used type!");
}
Referenced by interpolate().
interpCoeffs() [1/2]
template<typename Vector = RealVectorValue> std::pair< Real, Real > Moose::FV::interpCoeffs (const InterpMethod m, const FaceInfo & fi, const bool one_is_elem, const Vector advector = Vector())
Produce the interpolation coefficients in the equation:
\phi_f = c_1 * \phi_{F1} + c_2 * \phi_{F2}
A couple of examples: if we are doing an average interpolation with an orthogonal regular grid, then the pair will be (0.5, 0.5). If we are doing an upwind interpolation with the velocity facing outward from the F1 element, then the pair will be (1.0, 0.0).
Parameters
m The interpolation method
fi The face information
one_is_elem Whether fi.elem() == F1
advector The advecting velocity. Not relevant for an Average interpolation
Returns
a pair where the first Real is c_1 and the second Real is c_2
Definition at line 104 of file MathFVUtils.h.
{
  switch (m)
  {
    case InterpMethod::Average:
    case InterpMethod::SkewCorrectedAverage:
    {
      if (one_is_elem)
        return std::make_pair(fi.gC(), 1. - fi.gC());
      else
        return std::make_pair(1. - fi.gC(), fi.gC());
    }
    case InterpMethod::Upwind:
    {
      if ((advector * fi.normal() > 0) == one_is_elem)
        return std::make_pair(1., 0.);
      else
        return std::make_pair(0., 1.);
    }
    default:
      mooseError("Unrecognized interpolation method");
  }
}
Referenced by containerInterpolate(), harmonicInterpolation(), interpCoeffsAndAdvected(), interpolate(), linearInterpolation(), and skewCorrectedLinearInterpolation().
interpCoeffs() [2/2]
template<typename T > std::pair< T, T > Moose::FV::interpCoeffs (const Limiter< T > & limiter, const T & phi_upwind, const T & phi_downwind, const VectorValue< T > *const grad_phi_upwind, const FaceInfo & fi, const bool fi_elem_is_upwind)
Produce the interpolation coefficients in the equation:
\phi_f = c_upwind * \phi_{upwind} + c_downwind * \phi_{downwind}
A couple of examples: if we are doing an average interpolation with an orthogonal regular grid, then the pair will be (0.5, 0.5). If we are doing an upwind interpolation then the pair will be (1.0, 0.0).
Returns
a pair where the first Real is c_upwind and the second Real is c_downwind
Definition at line 456 of file MathFVUtils.h.
{
  // Using beta, w_f, g nomenclature from Greenshields
  const auto beta = limiter(
      phi_upwind, phi_downwind, grad_phi_upwind, fi_elem_is_upwind ? fi.dCN() : Point(-fi.dCN()));
  const auto w_f = fi_elem_is_upwind ? fi.gC() : (1. - fi.gC());
  const auto g = beta * (1. - w_f);
  return std::make_pair(1. - g, g);
}
interpCoeffsAndAdvected()
template<typename T , typename Enable = typename std::enable_if<ScalarTraits<T>::value>::type> std::pair< std::pair< T, T >, std::pair< T, T > > Moose::FV::interpCoeffsAndAdvected (const FunctorBase< T > & functor, const FaceArg & face, const StateArg & time)
Interpolates with a limiter and a face argument.
Returns
a pair of pairs. The first pair corresponds to the interpolation coefficients with the first corresponding to the face information element and the second corresponding to the face information neighbor. This pair should sum to unity. The second pair corresponds to the face information functor element value and neighbor
Definition at line 534 of file MathFVUtils.h.
{
  typedef typename FunctorBase<T>::GradientType GradientType;
  static const GradientType zero(0);
  mooseAssert(face.fi, "this must be non-null");
  const auto limiter = Limiter<typename LimiterValueType<T>::value_type>::build(face.limiter_type);
  const auto upwind_arg = face.elem_is_upwind ? face.makeElem() : face.makeNeighbor();
  const auto downwind_arg = face.elem_is_upwind ? face.makeNeighbor() : face.makeElem();
  auto phi_upwind = functor(upwind_arg, time);
  auto phi_downwind = functor(downwind_arg, time);
  std::pair<T, T> interp_coeffs;
  if (face.limiter_type == LimiterType::Upwind ||
      face.limiter_type == LimiterType::CentralDifference)
    interp_coeffs =
        interpCoeffs(*limiter, phi_upwind, phi_downwind, &zero, *face.fi, face.elem_is_upwind);
  else
  {
    const auto grad_phi_upwind = functor.gradient(upwind_arg, time);
    interp_coeffs = interpCoeffs(
        *limiter, phi_upwind, phi_downwind, &grad_phi_upwind, *face.fi, face.elem_is_upwind);
  }
  if (face.elem_is_upwind)
    return std::make_pair(std::move(interp_coeffs),
                          std::make_pair(std::move(phi_upwind), std::move(phi_downwind)));
  else
    return std::make_pair(
        std::make_pair(std::move(interp_coeffs.second), std::move(interp_coeffs.first)),
        std::make_pair(std::move(phi_downwind), std::move(phi_upwind)));
}
Referenced by interpolate().
interpolate() [1/9]
template<typename T , std::size_t N> std::array< T, N > Moose::FV::interpolate (const FunctorBase< std::array< T, N > > & functor, const FaceArg & face, const StateArg & time)
Definition at line 693 of file MathFVUtils.h.
{
  return containerInterpolate(functor, face, time);
}
interpolate() [2/9]
template<typename T > std::vector< T > Moose::FV::interpolate (const FunctorBase< std::vector< T > > & functor, const FaceArg & face, const StateArg & time)
Definition at line 684 of file MathFVUtils.h.
{
  return containerInterpolate(functor, face, time);
}
interpolate() [3/9]
template<typename T , typename Enable = typename std::enable_if<ScalarTraits<T>::value>::type> T Moose::FV::interpolate (const FunctorBase< T > & functor, const FaceArg & face, const StateArg & time)
Definition at line 570 of file MathFVUtils.h.
{
  // Special handling for central differencing as it is the only interpolation method which
  // currently supports skew correction
  if (face.limiter_type == LimiterType::CentralDifference)
    return linearInterpolation(functor, face, time);
  const auto [interp_coeffs, advected] = interpCoeffsAndAdvected(functor, face, time);
  return interp_coeffs.first * advected.first + interp_coeffs.second * advected.second;
}
interpolate() [4/9]
template<typename T > VectorValue< T > Moose::FV::interpolate (const FunctorBase< VectorValue< T > > & functor, const FaceArg & face, const StateArg & time)
Definition at line 583 of file MathFVUtils.h.
{
  static const VectorValue<T> grad_zero(0);
  mooseAssert(face.fi, "this must be non-null");
  const auto limiter = Limiter<typename LimiterValueType<T>::value_type>::build(face.limiter_type);
  const auto upwind_arg = face.elem_is_upwind ? face.makeElem() : face.makeNeighbor();
  const auto downwind_arg = face.elem_is_upwind ? face.makeNeighbor() : face.makeElem();
  auto phi_upwind = functor(upwind_arg, time);
  auto phi_downwind = functor(downwind_arg, time);
  VectorValue<T> ret;
  T coeff_upwind, coeff_downwind;
  if (face.limiter_type == LimiterType::Upwind ||
      face.limiter_type == LimiterType::CentralDifference)
  {
    for (unsigned int i = 0; i < LIBMESH_DIM; ++i)
    {
      const auto &component_upwind = phi_upwind(i), component_downwind = phi_downwind(i);
      std::tie(coeff_upwind, coeff_downwind) = interpCoeffs(*limiter,
                                                            component_upwind,
                                                            component_downwind,
                                                            &grad_zero,
                                                            *face.fi,
                                                            face.elem_is_upwind);
      ret(i) = coeff_upwind * component_upwind + coeff_downwind * component_downwind;
    }
  }
  else
  {
    const auto grad_phi_upwind = functor.gradient(upwind_arg, time);
    for (unsigned int i = 0; i < LIBMESH_DIM; ++i)
    {
      const auto &component_upwind = phi_upwind(i), component_downwind = phi_downwind(i);
      const VectorValue<T> grad = grad_phi_upwind.row(i);
      std::tie(coeff_upwind, coeff_downwind) = interpCoeffs(
          *limiter, component_upwind, component_downwind, &grad, *face.fi, face.elem_is_upwind);
      ret(i) = coeff_upwind * component_upwind + coeff_downwind * component_downwind;
    }
  }
  return ret;
}
interpolate() [5/9]
template<typename Limiter , typename T , typename Tensor > VectorValue< T > Moose::FV::interpolate (const Limiter & limiter, const TypeVector< T > & phi_upwind, const TypeVector< T > & phi_downwind, const Tensor *const grad_phi_upwind, const FaceInfo & fi, const bool fi_elem_is_upwind)
Vector overload.
Definition at line 497 of file MathFVUtils.h.
{
  mooseAssert(limiter.constant() || grad_phi_upwind,
              "Non-null gradient only supported for constant limiters.");
  const VectorValue<T> * const gradient_example = nullptr;
  VectorValue<T> ret;
  for (const auto i : make_range(unsigned(LIBMESH_DIM)))
  {
    if (grad_phi_upwind)
    {
      const VectorValue<T> gradient = grad_phi_upwind->row(i);
      ret(i) =
          interpolate(limiter, phi_upwind(i), phi_downwind(i), &gradient, fi, fi_elem_is_upwind);
    }
    else
      ret(i) = interpolate(
          limiter, phi_upwind(i), phi_downwind(i), gradient_example, fi, fi_elem_is_upwind);
  }
  return ret;
}
interpolate() [6/9]
template<typename Scalar , typename Vector , typename Enable = typename std::enable_if<ScalarTraits<Scalar>::value>::type> Scalar Moose::FV::interpolate (const Limiter< Scalar > & limiter, const Scalar & phi_upwind, const Scalar & phi_downwind, const Vector *const grad_phi_upwind, const FaceInfo & fi, const bool fi_elem_is_upwind)
Interpolates with a limiter.
Definition at line 481 of file MathFVUtils.h.
{
  auto pr = interpCoeffs(limiter, phi_upwind, phi_downwind, grad_phi_upwind, fi, fi_elem_is_upwind);
  return pr.first * phi_upwind + pr.second * phi_downwind;
}
interpolate() [7/9]
template<typename T , typename T2 , typename T3 > void Moose::FV::interpolate (InterpMethod m, T & result, const T2 & value1, const T3 & value2, const FaceInfo & fi, const bool one_is_elem)
Provides interpolation of face values for non-advection-specific purposes (although it can/will still be used by advective kernels sometimes).
The interpolated value is stored in result. This should be called when a face value needs to be computed from two neighboring cells/elements. value1 and value2 represent the cell property/values from which to compute the face value. The one_is_elem parameter indicates whether value1 corresponds to the FaceInfo elem value; else it corresponds to the FaceInfo neighbor value
Definition at line 272 of file MathFVUtils.h.
{
  switch (m)
  {
    case InterpMethod::Average:
    case InterpMethod::SkewCorrectedAverage:
      result = linearInterpolation(value1, value2, fi, one_is_elem);
      break;
    case InterpMethod::HarmonicAverage:
      result = harmonicInterpolation(value1, value2, fi, one_is_elem);
      break;
    default:
      mooseError("unsupported interpolation method for interpolate() function");
  }
}
Referenced by FVOrthogonalDiffusion::computeQpResidual(), MooseVariableFV< OutputType >::evaluate(), greenGaussGradient(), and interpolate().
interpolate() [8/9]
template<typename T , typename T2 , typename T3 , typename Vector > void Moose::FV::interpolate (InterpMethod m, T & result, const T2 & value1, const T3 & value2, const Vector & advector, const FaceInfo & fi, const bool one_is_elem)
Provides interpolation of face values for advective flux kernels.
This should be called by advective kernels when a face value is needed from two neighboring cells/elements. The interpolated value is stored in result. value1 and value2 represent the two neighboring advected cell property/values. advector represents the vector quantity at the face that is doing the advecting (e.g. the flow velocity at the face); this value often will have been computed using a call to the non-advective interpolate function. The one_is_elem parameter indicates whether value1 corresponds to the FaceInfo elem value; else it corresponds to the FaceInfo neighbor value
Definition at line 386 of file MathFVUtils.h.
{
  const auto coeffs = interpCoeffs(m, fi, one_is_elem, advector);
  result = coeffs.first * value1 + coeffs.second * value2;
}
interpolate() [9/9]
template<typename T1 , typename T2 , typename T3 , template< typename > class Vector1, template< typename > class Vector2> void Moose::FV::interpolate (InterpMethod m, Vector1< T1 > & result, const T2 & fi_elem_advected, const T2 & fi_neighbor_advected, const Vector2< T3 > & fi_elem_advector, const Vector2< T3 > & fi_neighbor_advector, const FaceInfo & fi)
Computes the product of the advected and the advector based on the given interpolation method.
Definition at line 339 of file MathFVUtils.h.
{
  switch (m)
  {
    case InterpMethod::Average:
      result = linearInterpolation(fi_elem_advected * fi_elem_advector,
                                   fi_neighbor_advected * fi_neighbor_advector,
                                   fi,
                                   true);
      break;
    case InterpMethod::Upwind:
    {
      const auto face_advector = linearInterpolation(MetaPhysicL::raw_value(fi_elem_advector),
                                                     MetaPhysicL::raw_value(fi_neighbor_advector),
                                                     fi,
                                                     true);
      Real elem_coeff, neighbor_coeff;
      if (face_advector * fi.normal() > 0)
        elem_coeff = 1, neighbor_coeff = 0;
      else
        elem_coeff = 0, neighbor_coeff = 1;
      result = elem_coeff * fi_elem_advected * fi_elem_advector +
               neighbor_coeff * fi_neighbor_advected * fi_neighbor_advector;
      break;
    }
    default:
      mooseError("unsupported interpolation method for FVFaceInterface::interpolate");
  }
}
interpolationMethods()
MooseEnum Moose::FV::interpolationMethods ()
Returns an enum with all the currently supported interpolation methods and the current default for FV: first-order upwind.
Returns
MooseEnum with all the face interpolation methods supported
Definition at line 61 of file MathFVUtils.C.
{
  return MooseEnum("average upwind sou min_mod vanLeer quick skewness-corrected", "upwind");
}
Referenced by advectedInterpolationParameter().
limiterType()
LimiterType Moose::FV::limiterType (const InterpMethod interp_method)
Return the limiter type associated with the supplied interpolation method.
Definition at line 59 of file Limiter.C.
{
  switch (interp_method)
  {
    case InterpMethod::Average:
    case InterpMethod::SkewCorrectedAverage:
      return LimiterType::CentralDifference;
    case InterpMethod::Upwind:
      return LimiterType::Upwind;
    case InterpMethod::VanLeer:
      return LimiterType::VanLeer;
    case InterpMethod::MinMod:
      return LimiterType::MinMod;
    case InterpMethod::SOU:
      return LimiterType::SOU;
    case InterpMethod::QUICK:
      return LimiterType::QUICK;
    default:
      mooseError("Unrecognized interpolation method type.");
  }
}
Referenced by FVAdvection::computeQpResidual(), and FVDivergence::computeQpResidual().
linearInterpolation() [1/2]
template<typename T > T Moose::FV::linearInterpolation (const FunctorBase< T > & functor, const FaceArg & face, const StateArg & time)
perform a possibly skew-corrected linear interpolation by evaluating the supplied functor with the provided functor face argument
Definition at line 299 of file MathFVUtils.h.
{
  mooseAssert(face.limiter_type == LimiterType::CentralDifference,
              "this interpolation method is meant for linear interpolations");
  mooseAssert(face.fi,
              "We must have a non-null face_info in order to prepare our ElemFromFace tuples");
  const auto elem_arg = face.makeElem();
  const auto neighbor_arg = face.makeNeighbor();
  if (face.correct_skewness)
  {
    // This condition ensures that the recursive algorithm (face_center->
    // face_gradient -> cell_gradient -> face_center -> ...) terminates after
    // one loop. It is hardcoded to one loop at this point since it yields
    // 2nd order accuracy on skewed meshes with the minimum additional effort.
    FaceArg new_face(face);
    new_face.correct_skewness = false;
    const auto surface_gradient = functor.gradient(new_face, time);
    return skewCorrectedLinearInterpolation(
        functor(elem_arg, time), functor(neighbor_arg, time), surface_gradient, *face.fi, true);
  }
  else
    return linearInterpolation(
        functor(elem_arg, time), functor(neighbor_arg, time), *face.fi, true);
}
linearInterpolation() [2/2]
template<typename T , typename T2 > libMesh::CompareTypes< T, T2 >::supertype Moose::FV::linearInterpolation (const T & value1, const T2 & value2, const FaceInfo & fi, const bool one_is_elem, const InterpMethod interp_method = InterpMethod::Average)
A simple linear interpolation of values between cell centers to a cell face.
The one_is_elem parameter indicates whether value1 corresponds to the FaceInfo elem value; else it corresponds to the FaceInfo neighbor value
Definition at line 140 of file MathFVUtils.h.
{
  mooseAssert(interp_method == InterpMethod::Average ||
                  interp_method == InterpMethod::SkewCorrectedAverage,
              "The selected interpolation function only works with average or skewness-corrected "
              "average options!");
  const auto coeffs = interpCoeffs(interp_method, fi, one_is_elem);
  return coeffs.first * value1 + coeffs.second * value2;
}
Referenced by MooseVariableFV< Real >::clearCaches(), interpolate(), and linearInterpolation().
loopOverElemFaceInfo()
template<typename ActionFunctor > void Moose::FV::loopOverElemFaceInfo (const Elem & elem, const MooseMesh & mesh, ActionFunctor & act, const Moose::CoordinateSystemType coord_type, const unsigned int rz_radial_coord = libMesh::invalid_uint)
Definition at line 39 of file FVUtils.h.
{
  mooseAssert(elem.active(), "We should never call this method with an inactive element");
  for (const auto side : elem.side_index_range())
  {
    const Elem * const candidate_neighbor = elem.neighbor_ptr(side);
    bool elem_has_info = elemHasFaceInfo(elem, candidate_neighbor);
    std::set<const Elem *> neighbors;
    const bool inactive_neighbor_detected =
        candidate_neighbor ? !candidate_neighbor->active() : false;
    // See MooseMesh::buildFaceInfo for corresponding checks/additions of FaceInfo
    if (inactive_neighbor_detected)
    {
      // We must be next to an element that has been refined
      mooseAssert(candidate_neighbor->has_children(), "We should have children");
      const auto candidate_neighbor_side = candidate_neighbor->which_neighbor_am_i(&elem);
      for (const auto child_num : make_range(candidate_neighbor->n_children()))
        if (candidate_neighbor->is_child_on_side(child_num, candidate_neighbor_side))
        {
          const Elem * const child = candidate_neighbor->child_ptr(child_num);
          mooseAssert(child->level() - elem.level() == 1, "The math doesn't work out here.");
          mooseAssert(child->has_neighbor(&elem), "Elem should be a neighbor of this child.");
          mooseAssert(child->active(),
                      "We shouldn't have greater than a face mismatch level of one");
          neighbors.insert(child);
        }
    }
    else
      neighbors.insert(candidate_neighbor);
    for (const Elem * const neighbor : neighbors)
    {
      const FaceInfo * const fi =
          elem_has_info ? mesh.faceInfo(&elem, side)
                        : mesh.faceInfo(neighbor, neighbor->which_neighbor_am_i(&elem));
      mooseAssert(fi, "We should have found a FaceInfo");
      mooseAssert(elem_has_info ? &elem == &fi->elem() : &elem == fi->neighborPtr(),
                  "Doesn't seem like we understand how this FaceInfo thing is working");
      if (neighbor)
      {
        mooseAssert(neighbor != libMesh::remote_elem,
                    "Remote element detected. This indicates that you have insufficient geometric "
                    "ghosting. Please contact your application developers.");
        mooseAssert(elem_has_info ? neighbor == fi->neighborPtr() : neighbor == &fi->elem(),
                    "Doesn't seem like we understand how this FaceInfo thing is working");
      }
      const Point elem_normal = elem_has_info ? fi->normal() : Point(-fi->normal());
      Real coord;
      MooseMeshUtils::coordTransformFactor(fi->faceCentroid(), coord, coord_type, rz_radial_coord);
      const Point surface_vector = elem_normal * fi->faceArea() * coord;
      act(elem, neighbor, fi, surface_vector, coord, elem_has_info);
    }
  }
}
Referenced by greenGaussGradient().
onBoundary() [1/2]
bool Moose::FV::onBoundary (const std::set< SubdomainID > & subs, const FaceInfo & fi)
Determine whether the passed-in face is on the boundary of an object that lives on the provided subdomains.
Note that if the subdomain set is empty we consider that to mean that the object has no block restriction and lives on the entire mesh
Definition at line 28 of file MathFVUtils.C.
{
  if (!fi.neighborPtr())
    // We're on the exterior boundary
    return true;
  if (subs.empty())
    // The face is internal and our functor lives on all subdomains
    return false;
  const auto sub_count =
      subs.count(fi.elem().subdomain_id()) + subs.count(fi.neighbor().subdomain_id());
  switch (sub_count)
  {
    case 0:
      mooseError("We should not be calling isExtrapolatedBoundaryFace on a functor that doesn't "
                 "live on either of the face information's neighboring elements");
    case 1:
      // We only live on one of the subs
      return true;
    case 2:
      // We live on both of the subs
      return false;
    default:
      mooseError("There should be no other sub_count options");
  }
}
Referenced by FVFluxKernel::onBoundary().
onBoundary() [2/2]
template<typename SubdomainRestrictable > bool Moose::FV::onBoundary (const SubdomainRestrictable & obj, const FaceInfo & fi)
Return whether the supplied face is on a boundary of the object's execution.
Definition at line 705 of file MathFVUtils.h.
{
  const bool internal = fi.neighborPtr() && obj.hasBlocks(fi.elemSubdomainID()) &&
                        obj.hasBlocks(fi.neighborSubdomainID());
  return !internal;
}
rF()
template<typename Scalar , typename Vector > Scalar Moose::FV::rF (const Scalar & phiC, const Scalar & phiD, const Vector & gradC, const RealVectorValue & dCD)
From Moukalled 12.30.
r_f = (phiC - phiU) / (phiD - phiC)
However, this formula is only clear on grids where upwind locations can be readily determined, which is not the case for unstructured meshes. So we leverage a virtual upwind location and Moukalled 12.65
phiD - phiU = 2 * grad(phi)_C * dCD -> phiU = phiD - 2 * grad(phi)_C * dCD
Combining the two equations and performing some algebraic manipulation yields this equation for r_f:
r_f = 2 * grad(phi)_C * dCD / (phiD - phiC) - 1
This equation is clearly asymmetric considering the face between C and D because of the subscript on grad(phi). Hence this method can be thought of as constructing an r associated with the C side of the face
Definition at line 429 of file MathFVUtils.h.
{
  static const auto zero_vec = RealVectorValue(0);
  if ((phiD - phiC) == 0)
    // Handle zero denominator case. Note that MathUtils::sign returns 1 for sign(0) so we can omit
    // that operation here (e.g. sign(phiD - phiC) = sign(0) = 1). The second term preserves the
    // same sparsity pattern as the else branch; we want to add this so that we don't risk PETSc
    // shrinking the matrix now and then potentially reallocating nonzeros later (which is very
    // slow)
    return 1e6 * MathUtils::sign(gradC * dCD) + zero_vec * gradC;
  return 2. * gradC * dCD / (phiD - phiC) - 1.;
}
Referenced by Moose::FV::MinModLimiter< T >::limit(), Moose::FV::QUICKLimiter< T >::limit(), Moose::FV::SOULimiter< T >::limit(), and Moose::FV::VanLeerLimiter< T >::limit().
selectInterpolationMethod()
InterpMethod Moose::FV::selectInterpolationMethod (const std::string & interp_method)
Definition at line 80 of file MathFVUtils.C.
{
  if (interp_method == "average")
    return InterpMethod::Average;
  else if (interp_method == "harmonic")
    return InterpMethod::HarmonicAverage;
  else if (interp_method == "skewness-corrected")
    return InterpMethod::SkewCorrectedAverage;
  else if (interp_method == "upwind")
    return InterpMethod::Upwind;
  else if (interp_method == "rc")
    return InterpMethod::RhieChow;
  else if (interp_method == "vanLeer")
    return InterpMethod::VanLeer;
  else if (interp_method == "min_mod")
    return InterpMethod::MinMod;
  else if (interp_method == "sou")
    return InterpMethod::SOU;
  else if (interp_method == "quick")
    return InterpMethod::QUICK;
  else
    mooseError("Interpolation method ",
               interp_method,
               " is not currently an option in Moose::FV::selectInterpolationMethod");
}
Referenced by setInterpolationMethod().
setInterpolationMethod()
bool Moose::FV::setInterpolationMethod (const MooseObject & obj, Moose::FV::InterpMethod & interp_method, const std::string & param_name)
Sets one interpolation method.
Parameters
obj The MooseObject with input parameters to query
interp_method The interpolation method we will set
param_name The name of the parameter setting this interpolation method
Returns
Whether the interpolation method has indicated that we will need more than the default level of ghosting
Definition at line 107 of file MathFVUtils.C.
{
  bool need_more_ghosting = false;
  const auto & interp_method_in = obj.getParam<MooseEnum>(param_name);
  interp_method = selectInterpolationMethod(interp_method_in);
  if (interp_method == InterpMethod::SOU || interp_method == InterpMethod::MinMod ||
      interp_method == InterpMethod::VanLeer || interp_method == InterpMethod::QUICK)
    need_more_ghosting = true;
  return need_more_ghosting;
}
Referenced by FVAdvection::FVAdvection().
skewCorrectedLinearInterpolation()
template<typename T , typename T2 , typename T3 > libMesh::CompareTypes< T, T2 >::supertype Moose::FV::skewCorrectedLinearInterpolation (const T & value1, const T2 & value2, const T3 & face_gradient, const FaceInfo & fi, const bool one_is_elem)
Linear interpolation with skewness correction using the face gradient.
See more info in Moukalled Chapter 9. The correction involves a first order Taylor expansion around the intersection of the cell face and the line connecting the two cell centers.
Definition at line 251 of file MathFVUtils.h.
{
  const auto coeffs = interpCoeffs(InterpMethod::SkewCorrectedAverage, fi, one_is_elem);
  auto value = (coeffs.first * value1 + coeffs.second * value2) +
               face_gradient * fi.skewnessCorrectionVector();
  return value;
}
Referenced by linearInterpolation().
Variable Documentation
moose_limiter_type
const MooseEnum Moose::FV::moose_limiter_type extern