Zapdos: MooseMeshDivision Namespace Reference
MooseMeshDivision Namespace Reference
Variables
unsigned int INVALID_DIVISION_INDEX = std::numeric_limits<unsigned int>::max()
Invalid subdomain id to return when outside the mesh division.
Variable Documentation
INVALID_DIVISION_INDEX
unsigned int MooseMeshDivision::INVALID_DIVISION_INDEX = std::numeric_limits<unsigned int>::max() inline
Invalid subdomain id to return when outside the mesh division.
Definition at line 28 of file MeshDivision.h.
Referenced by MultiAppGeneralFieldTransfer::acceptPointMeshDivision(), MultiAppGeneralFieldNearestLocationTransfer::buildKDTrees(), MultiAppGeneralFieldTransfer::cacheOutgoingPointInfo(), MultiAppGeneralFieldNearestLocationTransfer::checkRestrictionsForSource(), MeshDivisionAux::computeValue(), SubdomainsDivision::divisionIndex(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), MeshDivisionFunctorReductionVectorPostprocessor::execute(), MultiAppGeneralFieldTransfer::extractOutgoingPoints(), FunctorBinnedValuesDivision::getBinIndex(), MultiAppGeneralFieldTransfer::locatePointReceivers(), and MeshDivisionFunctorReductionVectorPostprocessor::spatialValue().