Zapdos: std Namespace Reference
std Namespace Reference
Classes
struct hash< Attribute >
This template specialization allows Attributes to be used as unordered map key.
struct hash< ReporterName >
struct hash< std::pair< S, T > >
struct hash< std::vector< std::unique_ptr< Attribute > > >
This template specialization allows vector<Attribute> to be used as unordered map key.
Functions
MooseUnits pow (const MooseUnits &u, int e)
Function Documentation
pow()
MooseUnits std::pow (const MooseUnits & u, int e)
Definition at line 531 of file Units.C.
{
  MooseUnits r = u;
  r._factor = std::pow(u._factor, e);
  r._shift = 0.0;
  for (auto & b : r._base)
    b.second *= e;
  return r;
}
Referenced by RinglebMesh::arhopj(), RinglebMeshGenerator::arhopj(), AnnularMesh::buildMesh(), GeneratedMesh::buildMesh(), SpiralAnnularMesh::buildMesh(), ChemicalReactionsBase::ChemicalReactionsBase(), ElementH1ErrorFunctionAux::compute(), ElementLpNormAux::compute(), AB2PredictorCorrector::computeDT(), ElementW1pError::computeQpIntegral(), Product1BodyScalar::computeQpJacobian(), Product2BodyScalar::computeQpJacobian(), Product3BodyScalar::computeQpJacobian(), Reactant3BodyScalar::computeQpJacobian(), EnergyTermScalar::computeQpOffDiagJacobian(), Product1BodyScalar::computeQpOffDiagJacobian(), Product2BodyScalar::computeQpOffDiagJacobian(), Product3BodyScalar::computeQpOffDiagJacobian(), DiffusionRateTemp::computeQpProperties(), HeatCapacityRatio::computeQpProperties(), SuperelasticReactionRate::computeQpProperties(), Gas::computeQpProperties(), GasBase::computeQpProperties(), GasElectronMoments::computeQpProperties(), CircuitDirichletPotential::computeQpResidual(), FieldEmissionBC::computeQpResidual(), SchottkyEmissionBC::computeQpResidual(), ShootMethodLog::computeQpResidual(), TM0Cylindrical::computeQpResidual(), DGCoeffDiffusion::computeQpResidual(), SuperelasticRateCoefficientScalar::computeValue(), ElementH1ErrorFunctionAux::computeValue(), PseudoTimestep::currentResidualNorm(), RankTwoTensorTempl< T >::d2sin3Lode(), RankTwoTensorTempl< T >::dsin3Lode(), SymmetricRankTwoTensorTempl< T >::dsin3Lode(), FieldEmissionBC::FieldEmissionBC(), FillBetweenPointVectorsTools::fillBetweenPointVectorsGenerator(), PlasmaFrequencyInverse::finalize(), AdvancedExtruderGenerator::generate(), AnnularMeshGenerator::generate(), DistributedRectilinearMeshGenerator::generate(), SpiralAnnularMeshGenerator::generate(), TransfiniteMeshGenerator::getPointsDistribution(), ElementW1pError::getValue(), PercentChangePostprocessor::getValue(), MonotoneCubicInterpolation::initialize_derivs(), MonotoneCubicInterpolation::modify_derivs(), CompileTimeDerivatives::CTPow< L, R >::operator()(), DistributedRectilinearMeshGenerator::paritionSquarely(), MooseUnits::parse(), pow(), RankTwoTensorTempl< T >::sin3Lode(), SymmetricRankTwoTensorTempl< T >::sin3Lode(), MonotoneCubicInterpolation::solve(), MathUtils::taylorLog(), PseudoTimestep::timestepRDM(), and PseudoTimestep::timestepSER().