Zapdos: MooseMeshUtils Namespace Reference
MooseMeshUtils Namespace Reference
Functions
void changeBoundaryId (MeshBase &mesh, const boundary_id_type old_id, const boundary_id_type new_id, bool delete_prev)
std::vector< boundary_id_type > getBoundaryIDs (const MeshBase &mesh, const std::vector< BoundaryName > &boundary_name, bool generate_unknown)
std::vector< boundary_id_type > getBoundaryIDs (const MeshBase &mesh, const std::vector< BoundaryName > &boundary_name, bool generate_unknown, const std::set< BoundaryID > &mesh_boundary_ids)
std::set< BoundaryID > getBoundaryIDSet (const MeshBase &mesh, const std::vector< BoundaryName > &boundary_name, bool generate_unknown)
std::vector< subdomain_id_type > getSubdomainIDs (const MeshBase &mesh, const std::vector< SubdomainName > &subdomain_name)
BoundaryID getBoundaryID (const BoundaryName &boundary_name, const MeshBase &mesh)
Gets the boundary ID associated with the given BoundaryName.
SubdomainID getSubdomainID (const SubdomainName &subdomain_name, const MeshBase &mesh)
Gets the subdomain ID associated with the given SubdomainName.
void changeSubdomainId (MeshBase &mesh, const subdomain_id_type old_id, const subdomain_id_type new_id)
Changes the old subdomain ID to a new ID in the mesh.
Point meshCentroidCalculator (const MeshBase &mesh)
Calculates the centroid of a MeshBase.
std::unordered_map< dof_id_type, dof_id_type > getExtraIDUniqueCombinationMap (const MeshBase &mesh, const std::set< SubdomainID > &block_ids, std::vector< ExtraElementIDName > extra_ids)
Crate a new set of element-wise IDs by finding unique combinations of existing extra ID values.
bool isCoPlanar (const std::vector< Point > vec_pts, const Point plane_nvec, const Point fixed_pt)
Decides whether all the Points of a vector of Points are in a plane that is defined by a normal vector and an inplane Point.
bool isCoPlanar (const std::vector< Point > vec_pts, const Point plane_nvec)
Decides whether all the Points of a vector of Points are in a plane with a given normal vector.
bool isCoPlanar (const std::vector< Point > vec_pts)
Decides whether all the Points of a vector of Points are coplanar.
SubdomainID getNextFreeSubdomainID (MeshBase &input_mesh)
Checks input mesh and returns max(block ID) + 1, which represents a block ID that is not currently in use in the mesh.
BoundaryID getNextFreeBoundaryID (MeshBase &input_mesh)
Checks input mesh and returns the largest boundary ID in the mesh plus one, which is a boundary ID in the mesh that is not currently in use.
bool hasSubdomainID (MeshBase &input_mesh, const SubdomainID &id)
Whether a particular subdomain ID exists in the mesh.
bool hasSubdomainName (MeshBase &input_mesh, const SubdomainName &name)
Whether a particular subdomain name exists in the mesh.
bool hasBoundaryID (MeshBase &input_mesh, const BoundaryID &id)
Whether a particular boundary ID exists in the mesh.
bool hasBoundaryName (MeshBase &input_mesh, const BoundaryName &name)
Whether a particular boundary name exists in the mesh.
void makeOrderedNodeList (std::vector< std::pair< dof_id_type, dof_id_type > > &node_assm, std::vector< dof_id_type > &elem_id_list, std::vector< dof_id_type > &ordered_node_list, std::vector< dof_id_type > &ordered_elem_id_list)
Convert a list of sides in the form of a vector of pairs of node ids into a list of ordered nodes based on connectivity.
void changeBoundaryId (MeshBase &mesh, const libMesh::boundary_id_type old_id, const libMesh::boundary_id_type new_id, bool delete_prev)
Changes the old boundary ID to a new ID in the mesh.
std::vector< BoundaryID > getBoundaryIDs (const libMesh::MeshBase &mesh, const std::vector< BoundaryName > &boundary_name, bool generate_unknown, const std::set< BoundaryID > &mesh_boundary_ids)
Gets the boundary IDs with their names.
std::vector< BoundaryID > getBoundaryIDs (const libMesh::MeshBase &mesh, const std::vector< BoundaryName > &boundary_name, bool generate_unknown)
Gets the boundary IDs with their names.
std::set< BoundaryID > getBoundaryIDSet (const libMesh::MeshBase &mesh, const std::vector< BoundaryName > &boundary_name, bool generate_unknown)
Gets the boundary IDs into a set with their names.
std::vector< subdomain_id_type > getSubdomainIDs (const libMesh::MeshBase &mesh, const std::vector< SubdomainName > &subdomain_name)
Get the associated subdomainIDs for the subdomain names that are passed in.
template<typename P , typename C >
void coordTransformFactor (const P &point, C &factor, const Moose::CoordinateSystemType coord_type, const unsigned int rz_radial_coord=libMesh::invalid_uint)
compute a coordinate transformation factor
template<typename P , typename C >
C computeDistanceToAxis (const P &point, const Point &origin, const RealVectorValue &direction)
Computes the distance to a general axis.
template<typename P , typename C >
void coordTransformFactorRZGeneral (const P &point, const std::pair< Point, RealVectorValue > &axis, C &factor)
Computes a coordinate transformation factor for a general axisymmetric axis.
void computeFaceInfoFaceCoord (FaceInfo &fi, const Moose::CoordinateSystemType coord_type, const unsigned int rz_radial_coord=libMesh::invalid_uint)
Function Documentation
changeBoundaryId() [1/2]
void MooseMeshUtils::changeBoundaryId (MeshBase & mesh, const boundary_id_type old_id, const boundary_id_type new_id, bool delete_prev)
Definition at line 26 of file MooseMeshUtils.C.
{
  // Get a reference to our BoundaryInfo object, we will use it several times below...
  BoundaryInfo & boundary_info = mesh.get_boundary_info();
  // Container to catch ids passed back from BoundaryInfo
  std::vector<boundary_id_type> old_ids;
  // Only level-0 elements store BCs.  Loop over them.
  for (auto & elem : as_range(mesh.level_elements_begin(0), mesh.level_elements_end(0)))
  {
    unsigned int n_sides = elem->n_sides();
    for (unsigned int s = 0; s != n_sides; ++s)
    {
      boundary_info.boundary_ids(elem, s, old_ids);
      if (std::find(old_ids.begin(), old_ids.end(), old_id) != old_ids.end())
      {
        std::vector<boundary_id_type> new_ids(old_ids);
        std::replace(new_ids.begin(), new_ids.end(), old_id, new_id);
        if (delete_prev)
        {
          boundary_info.remove_side(elem, s);
          boundary_info.add_side(elem, s, new_ids);
        }
        else
          boundary_info.add_side(elem, s, new_ids);
      }
    }
  }
  // Remove any remaining references to the old ID from the
  // BoundaryInfo object.  This prevents things like empty sidesets
  // from showing up when printing information, etc.
  if (delete_prev)
    boundary_info.remove_id(old_id);
  // global information may now be out of sync
  mesh.set_isnt_prepared();
}
Referenced by MeshExtruderGenerator::changeID(), and FillBetweenSidesetsGenerator::generate().
changeBoundaryId() [2/2]
void MooseMeshUtils::changeBoundaryId (MeshBase & mesh, const libMesh::boundary_id_type old_id, const libMesh::boundary_id_type new_id, bool delete_prev)
Changes the old boundary ID to a new ID in the mesh.
Parameters
mesh the mesh
old_id the old boundary id
new_id the new boundary id
delete_prev whether to delete the previous boundary id from the mesh
changeSubdomainId()
void MooseMeshUtils::changeSubdomainId (MeshBase & mesh, const subdomain_id_type old_id, const subdomain_id_type new_id)
Changes the old subdomain ID to a new ID in the mesh.
Parameters
mesh the mesh
old_id the old subdomain id
new_id the new subdomain id
Definition at line 219 of file MooseMeshUtils.C.
{
  for (const auto & elem : mesh.element_ptr_range())
    if (elem->subdomain_id() == old_id)
      elem->subdomain_id() = new_id;
  // global cached information may now be out of sync
  mesh.set_isnt_prepared();
}
computeDistanceToAxis()
template<typename P , typename C > C MooseMeshUtils::computeDistanceToAxis (const P & point, const Point & origin, const RealVectorValue & direction)
Computes the distance to a general axis.
Parameters
[in] point Point for which to compute distance from axis
[in] origin Axis starting point
[in] direction Axis direction
Definition at line 164 of file MooseMeshUtils.h.
{
  return (point - origin).cross(direction).norm();
}
computeFaceInfoFaceCoord()
void MooseMeshUtils::computeFaceInfoFaceCoord (FaceInfo & fi, const Moose::CoordinateSystemType coord_type, const unsigned int rz_radial_coord = libMesh::invalid_uint) inline
Definition at line 187 of file MooseMeshUtils.h.
{
  coordTransformFactor(fi.faceCentroid(), fi.faceCoord(), coord_type, rz_radial_coord);
}
coordTransformFactor()
template<typename P , typename C > void MooseMeshUtils::coordTransformFactor (const P & point, C & factor, const Moose::CoordinateSystemType coord_type, const unsigned int rz_radial_coord = libMesh::invalid_uint)
compute a coordinate transformation factor
Parameters
point The libMesh Point in space where we are evaluating the factor
factor The output of this function. Would be 1 for cartesian coordinate systems, 2*pi*r for cylindrical coordinate systems, and 4*pi*r^2 for spherical coordinate systems
coord_type The coordinate system type, e.g. cartesian (COORD_XYZ), cylindrical (COORD_RZ), or spherical (COORD_RSPHERICAL)
rz_radial_coord The index at which to index point for the radial coordinate when in a cylindrical coordinate system
Definition at line 130 of file MooseMeshUtils.h.
{
  switch (coord_type)
  {
    case Moose::COORD_XYZ:
      factor = 1.0;
      break;
    case Moose::COORD_RZ:
    {
      mooseAssert(rz_radial_coord != libMesh::invalid_uint,
                  "Must pass in a valid rz radial coordinate");
      factor = 2 * M_PI * point(rz_radial_coord);
      break;
    }
    case Moose::COORD_RSPHERICAL:
      factor = 4 * M_PI * point(0) * point(0);
      break;
    default:
      mooseError("Unknown coordinate system");
  }
}
Referenced by computeFaceInfoFaceCoord(), coordTransformFactor(), Moose::FV::greenGaussGradient(), and Moose::FV::loopOverElemFaceInfo().
coordTransformFactorRZGeneral()
template<typename P , typename C > void MooseMeshUtils::coordTransformFactorRZGeneral (const P & point, const std::pair< Point, RealVectorValue > & axis, C & factor)
Computes a coordinate transformation factor for a general axisymmetric axis.
Parameters
[in] point The libMesh Point in space where we are evaluating the factor
[in] axis The pair of values defining the general axisymmetric axis. Respectively, the values are the axis starting point and direction.
[out] factor The coordinate transformation factor
Definition at line 179 of file MooseMeshUtils.h.
{
  factor = 2 * M_PI * computeDistanceToAxis<P, C>(point, axis.first, axis.second);
}
Referenced by coordTransformFactor().
getBoundaryID()
BoundaryID MooseMeshUtils::getBoundaryID (const BoundaryName & boundary_name, const MeshBase & mesh)
Gets the boundary ID associated with the given BoundaryName.
This is needed because the BoundaryName can be either an ID or a name. If it is a name, the mesh is queried for the ID associated with said name.
Definition at line 180 of file MooseMeshUtils.C.
{
  BoundaryID id = Moose::INVALID_BOUNDARY_ID;
  if (boundary_name.empty())
    return id;
  if (!MooseUtils::isDigits(boundary_name))
    id = mesh.get_boundary_info().get_id_by_name(boundary_name);
  else
  {
    std::istringstream ss(boundary_name);
    ss >> id;
  }
  return id;
}
Referenced by BoundaryDeletionGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MooseMesh::getBoundaryID(), and hasBoundaryName().
getBoundaryIDs() [1/4]
std::vector< BoundaryID > MooseMeshUtils::getBoundaryIDs (const libMesh::MeshBase & mesh, const std::vector< BoundaryName > & boundary_name, bool generate_unknown)
Gets the boundary IDs with their names.
The ordering of the returned boundary ID vector matches the vector of the boundary names in boundary_name. When a boundary name is not available in the mesh, if generate_unknown is true a non-existant boundary ID will be returned, otherwise a BoundaryInfo::invalid_id will be returned.
getBoundaryIDs() [2/4]
std::vector< BoundaryID > MooseMeshUtils::getBoundaryIDs (const libMesh::MeshBase & mesh, const std::vector< BoundaryName > & boundary_name, bool generate_unknown, const std::set< BoundaryID > & mesh_boundary_ids)
Gets the boundary IDs with their names.
The ordering of the returned boundary ID vector matches the vector of the boundary names in boundary_name. When a boundary name is not available in the mesh, if generate_unknown is true a non-existant boundary ID will be returned, otherwise a BoundaryInfo::invalid_id will be returned.
getBoundaryIDs() [3/4]
std::vector< boundary_id_type > MooseMeshUtils::getBoundaryIDs (const MeshBase & mesh, const std::vector< BoundaryName > & boundary_name, bool generate_unknown)
Definition at line 70 of file MooseMeshUtils.C.
{
  return getBoundaryIDs(
      mesh, boundary_name, generate_unknown, mesh.get_boundary_info().get_boundary_ids());
}
Referenced by BoundaryPreservedMarker::BoundaryPreservedMarker(), MeshExtruderGenerator::changeID(), BoundingBoxNodeSetGenerator::generate(), BreakBoundaryOnSubdomainGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), ElementDeletionGeneratorBase::generate(), ExtraNodesetGenerator::generate(), FillBetweenSidesetsGenerator::generate(), LowerDBlockFromSidesetGenerator::generate(), ParsedGenerateSideset::generate(), PatternedMeshGenerator::generate(), PolyLineMeshGenerator::generate(), RefineSidesetGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), SideSetsFromNormalsGenerator::generate(), SideSetsFromPointsGenerator::generate(), StackGenerator::generate(), XYDelaunayGenerator::generate(), getBoundaryIDs(), MooseMesh::getBoundaryIDs(), and getBoundaryIDSet().
getBoundaryIDs() [4/4]
std::vector< boundary_id_type > MooseMeshUtils::getBoundaryIDs (const MeshBase & mesh, const std::vector< BoundaryName > & boundary_name, bool generate_unknown, const std::set< BoundaryID > & mesh_boundary_ids)
If the conversion from a name to a number fails, that means that this must be a named boundary. We will look in the complete map for this sideset and create a new name/ID pair if requested.
Definition at line 79 of file MooseMeshUtils.C.
{
  const BoundaryInfo & boundary_info = mesh.get_boundary_info();
  const std::map<BoundaryID, std::string> & sideset_map = boundary_info.get_sideset_name_map();
  const std::map<BoundaryID, std::string> & nodeset_map = boundary_info.get_nodeset_name_map();
  BoundaryID max_boundary_local_id = 0;
  /* It is required to generate a new ID for a given name. It is used often in mesh modifiers such
   * as SideSetsBetweenSubdomains. Then we need to check the current boundary ids since they are
   * changing during "mesh modify()", and figure out the right max boundary ID. Most of mesh
   * modifiers are running in serial, and we won't involve a global communication.
   */
  if (generate_unknown)
  {
    const auto & bids = mesh.is_prepared() ? mesh.get_boundary_info().get_global_boundary_ids()
                                           : mesh.get_boundary_info().get_boundary_ids();
    max_boundary_local_id = bids.empty() ? 0 : *(bids.rbegin());
    /* We should not hit this often */
    if (!mesh.is_prepared() && !mesh.is_serial())
      mesh.comm().max(max_boundary_local_id);
  }
  BoundaryID max_boundary_id = mesh_boundary_ids.empty() ? 0 : *(mesh_boundary_ids.rbegin());
  max_boundary_id =
      max_boundary_id > max_boundary_local_id ? max_boundary_id : max_boundary_local_id;
  std::vector<BoundaryID> ids(boundary_name.size());
  for (unsigned int i = 0; i < boundary_name.size(); i++)
  {
    if (boundary_name[i] == "ANY_BOUNDARY_ID")
    {
      ids.assign(mesh_boundary_ids.begin(), mesh_boundary_ids.end());
      if (i)
        mooseWarning("You passed \"ANY_BOUNDARY_ID\" in addition to other boundary_names.  This "
                     "may be a logic error.");
      break;
    }
    if (boundary_name[i].empty() && !generate_unknown)
      mooseError("Incoming boundary name is empty and we are not generating unknown boundary IDs. "
                 "This is invalid.");
    BoundaryID id;
    if (boundary_name[i].empty() || !MooseUtils::isDigits(boundary_name[i]))
    {
      if (generate_unknown &&
          !MooseUtils::doesMapContainValue(sideset_map, std::string(boundary_name[i])) &&
          !MooseUtils::doesMapContainValue(nodeset_map, std::string(boundary_name[i])))
        id = ++max_boundary_id;
      else
        id = boundary_info.get_id_by_name(boundary_name[i]);
    }
    else
    {
      std::istringstream ss(boundary_name[i]);
      ss >> id;
      if (ss.fail())
        mooseError("Failed to convert integer ",
                   boundary_name[i],
                   " to a boundary id.  Got ",
                   id,
                   " instead.  Is the integer too large for boundary_id_type?");
    }
    ids[i] = id;
  }
  return ids;
}
getBoundaryIDSet() [1/2]
std::set< BoundaryID > MooseMeshUtils::getBoundaryIDSet (const libMesh::MeshBase & mesh, const std::vector< BoundaryName > & boundary_name, bool generate_unknown)
Gets the boundary IDs into a set with their names.
Because libMesh allows the same boundary to have multiple different boundary names, the size of the returned boundary ID set may be smaller than the size of the bounndary name vector. When a boundary name is not available in the mesh, if generate_unknown is true a non-existant boundary ID will be returned, otherwise a BoundaryInfo::invalid_id will be returned.
getBoundaryIDSet() [2/2]
std::set< BoundaryID > MooseMeshUtils::getBoundaryIDSet (const MeshBase & mesh, const std::vector< BoundaryName > & boundary_name, bool generate_unknown)
Definition at line 160 of file MooseMeshUtils.C.
{
  auto boundaries = getBoundaryIDs(mesh, boundary_name, generate_unknown);
  return std::set<BoundaryID>(boundaries.begin(), boundaries.end());
}
Referenced by DomainUserObject::DomainUserObject().
getExtraIDUniqueCombinationMap()
std::unordered_map< dof_id_type, dof_id_type > MooseMeshUtils::getExtraIDUniqueCombinationMap (const MeshBase & mesh, const std::set< SubdomainID > & block_ids, std::vector< ExtraElementIDName > extra_ids)
Crate a new set of element-wise IDs by finding unique combinations of existing extra ID values.
This function finds the unique combinations by recursively calling itself for extra ID inputs. In the recursive calling, the new unique combitnations is determined by combining the extra ID value of current level and the unique combination determined in the previous level in recursion. In the lowest level of recursion, the base combination is set by the unqiue ID values of the corresponding extra ID.
Parameters
mesh input mesh
block_ids block ids
extra_ids extra ids
Returns
map of element id to new extra id
Definition at line 248 of file MooseMeshUtils.C.
{
  // check block restriction
  const bool block_restricted = !block_ids.empty();
  // get element id name of interest in recursive parsing algorithm
  ExtraElementIDName id_name = extra_ids.back();
  extra_ids.pop_back();
  const auto id_index = mesh.get_elem_integer_index(id_name);
  // create base parsed id set
  if (extra_ids.empty())
  {
    // get set of extra id values;
    std::vector<dof_id_type> ids;
    {
      std::set<dof_id_type> ids_set;
      for (const auto & elem : mesh.active_element_ptr_range())
      {
        if (block_restricted && block_ids.find(elem->subdomain_id()) == block_ids.end())
          continue;
        const auto id = elem->get_extra_integer(id_index);
        ids_set.insert(id);
      }
      mesh.comm().set_union(ids_set);
      ids.assign(ids_set.begin(), ids_set.end());
    }
    // determine new extra id values;
    std::unordered_map<dof_id_type, dof_id_type> parsed_ids;
    for (auto & elem : mesh.active_element_ptr_range())
    {
      if (block_restricted && block_ids.find(elem->subdomain_id()) == block_ids.end())
        continue;
      parsed_ids[elem->id()] = std::distance(
          ids.begin(), std::lower_bound(ids.begin(), ids.end(), elem->get_extra_integer(id_index)));
    }
    return parsed_ids;
  }
  // if extra_ids is not empty, recursively call getExtraIDUniqueCombinationMap
  const auto base_parsed_ids =
      MooseMeshUtils::getExtraIDUniqueCombinationMap(mesh, block_ids, extra_ids);
  // parsing extra ids based on ref_parsed_ids
  std::vector<std::pair<dof_id_type, dof_id_type>> unique_ids;
  {
    std::set<std::pair<dof_id_type, dof_id_type>> unique_ids_set;
    for (const auto & elem : mesh.active_element_ptr_range())
    {
      if (block_restricted && block_ids.find(elem->subdomain_id()) == block_ids.end())
        continue;
      const dof_id_type id1 = libmesh_map_find(base_parsed_ids, elem->id());
      const dof_id_type id2 = elem->get_extra_integer(id_index);
      const std::pair<dof_id_type, dof_id_type> ids = std::make_pair(id1, id2);
      unique_ids_set.insert(ids);
    }
    mesh.comm().set_union(unique_ids_set);
    unique_ids.assign(unique_ids_set.begin(), unique_ids_set.end());
  }
  std::unordered_map<dof_id_type, dof_id_type> parsed_ids;
  for (const auto & elem : mesh.active_element_ptr_range())
  {
    if (block_restricted && block_ids.find(elem->subdomain_id()) == block_ids.end())
      continue;
    const dof_id_type id1 = libmesh_map_find(base_parsed_ids, elem->id());
    const dof_id_type id2 = elem->get_extra_integer(id_index);
    const dof_id_type new_id = std::distance(
        unique_ids.begin(),
        std::lower_bound(unique_ids.begin(), unique_ids.end(), std::make_pair(id1, id2)));
    parsed_ids[elem->id()] = new_id;
  }
  return parsed_ids;
}
Referenced by ExtraIDIntegralVectorPostprocessor::ExtraIDIntegralVectorPostprocessor(), UniqueExtraIDMeshGenerator::generate(), and getExtraIDUniqueCombinationMap().
getNextFreeBoundaryID()
BoundaryID MooseMeshUtils::getNextFreeBoundaryID (MeshBase & input_mesh)
Checks input mesh and returns the largest boundary ID in the mesh plus one, which is a boundary ID in the mesh that is not currently in use.
Parameters
input mesh over which to compute the next free boundary ID
Definition at line 389 of file MooseMeshUtils.C.
{
  auto boundary_ids = input_mesh.get_boundary_info().get_boundary_ids();
  if (boundary_ids.empty())
    return 0;
  return (*boundary_ids.rbegin() + 1);
}
Referenced by SideSetsFromBoundingBoxGenerator::generate(), and XYMeshLineCutter::generate().
getNextFreeSubdomainID()
SubdomainID MooseMeshUtils::getNextFreeSubdomainID (MeshBase & input_mesh)
Checks input mesh and returns max(block ID) + 1, which represents a block ID that is not currently in use in the mesh.
Parameters
input mesh over which to compute the next free block id
Definition at line 369 of file MooseMeshUtils.C.
{
  // Call this to get most up to date block id information
  input_mesh.cache_elem_data();
  std::set<SubdomainID> preexisting_subdomain_ids;
  input_mesh.subdomain_ids(preexisting_subdomain_ids);
  if (preexisting_subdomain_ids.empty())
    return 0;
  else
  {
    const auto highest_subdomain_id =
        *std::max_element(preexisting_subdomain_ids.begin(), preexisting_subdomain_ids.end());
    mooseAssert(highest_subdomain_id < std::numeric_limits<SubdomainID>::max(),
                "A SubdomainID with max possible value was found");
    return highest_subdomain_id + 1;
  }
}
Referenced by LowerDBlockFromSidesetGenerator::generate(), XYDelaunayGenerator::generate(), and MeshRepairGenerator::separateSubdomainsByElementType().
getSubdomainID()
SubdomainID MooseMeshUtils::getSubdomainID (const SubdomainName & subdomain_name, const MeshBase & mesh)
Gets the subdomain ID associated with the given SubdomainName.
This is needed because the SubdomainName can be either an ID or a name. If it is a name, the mesh is queried for the ID associated with said name.
Definition at line 198 of file MooseMeshUtils.C.
{
  if (subdomain_name == "ANY_BLOCK_ID")
    mooseError("getSubdomainID() does not work with \"ANY_BLOCK_ID\"");
  SubdomainID id = Moose::INVALID_BLOCK_ID;
  if (subdomain_name.empty())
    return id;
  if (!MooseUtils::isDigits(subdomain_name))
    id = mesh.get_id_by_name(subdomain_name);
  else
  {
    std::istringstream ss(subdomain_name);
    ss >> id;
  }
  return id;
}
Referenced by RenameBlockGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), XYDelaunayGenerator::generate(), MooseMesh::getSubdomainID(), getSubdomainIDs(), hasSubdomainName(), MooseMeshXYCuttingUtils::quadToTriOnLine(), and MooseMeshXYCuttingUtils::quasiTriElementsFixer().
getSubdomainIDs() [1/2]
std::vector< subdomain_id_type > MooseMeshUtils::getSubdomainIDs (const libMesh::MeshBase & mesh, const std::vector< SubdomainName > & subdomain_name)
Get the associated subdomainIDs for the subdomain names that are passed in.
Parameters
mesh The mesh
subdomain_name The names of the subdomains
Returns
The subdomain ids from the passed subdomain names.
getSubdomainIDs() [2/2]
std::vector< subdomain_id_type > MooseMeshUtils::getSubdomainIDs (const MeshBase & mesh, const std::vector< SubdomainName > & subdomain_name)
Definition at line 169 of file MooseMeshUtils.C.
{
  std::vector<SubdomainID> ids(subdomain_name.size());
  for (unsigned int i = 0; i < subdomain_name.size(); i++)
    ids[i] = MooseMeshUtils::getSubdomainID(subdomain_name[i], mesh);
  return ids;
}
Referenced by BlockDeletionGenerator::generate(), BlockToMeshConverterGenerator::generate(), BreakMeshByBlockGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), RefineBlockGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), XYDelaunayGenerator::generate(), MooseMesh::getSubdomainIDs(), BlockWeightedPartitioner::initialize(), and LibmeshPartitioner::prepareBlocksForSubdomainPartitioner().
hasBoundaryID()
bool MooseMeshUtils::hasBoundaryID (MeshBase & input_mesh, const BoundaryID & id)
Whether a particular boundary ID exists in the mesh.
Parameters
input mesh over which to determine boundary IDs
boundary ID
Definition at line 419 of file MooseMeshUtils.C.
{
  const BoundaryInfo & boundary_info = input_mesh.get_boundary_info();
  std::set<boundary_id_type> boundary_ids = boundary_info.get_boundary_ids();
  // On a distributed mesh we may have boundary IDs that only exist on
  // other processors
  if (!input_mesh.is_replicated())
    input_mesh.comm().set_union(boundary_ids);
  return boundary_ids.count(id) && (id != Moose::INVALID_BOUNDARY_ID);
}
Referenced by MooseMeshXYCuttingUtils::boundaryTriElemImprover(), and hasBoundaryName().
hasBoundaryName()
bool MooseMeshUtils::hasBoundaryName (MeshBase & input_mesh, const BoundaryName & name)
Whether a particular boundary name exists in the mesh.
Parameters
input mesh over which to determine boundary names
boundary name
Definition at line 433 of file MooseMeshUtils.C.
{
  const auto id = getBoundaryID(name, input_mesh);
  return hasBoundaryID(input_mesh, id);
}
Referenced by MultiAppNearestNodeTransfer::execute(), MultiAppUserObjectTransfer::execute(), BreakBoundaryOnSubdomainGenerator::generate(), CircularBoundaryCorrectionGenerator::generate(), MultiAppNearestNodeTransfer::getLocalEntitiesAndComponents(), and MultiAppNearestNodeTransfer::getTargetLocalNodes().
hasSubdomainID()
bool MooseMeshUtils::hasSubdomainID (MeshBase & input_mesh, const SubdomainID & id)
Whether a particular subdomain ID exists in the mesh.
Parameters
input mesh over which to determine subdomain IDs
subdomain ID
Definition at line 398 of file MooseMeshUtils.C.
{
  std::set<SubdomainID> mesh_blocks;
  input_mesh.subdomain_ids(mesh_blocks);
  // On a distributed mesh we may have sideset IDs that only exist on
  // other processors
  if (!input_mesh.is_replicated())
    input_mesh.comm().set_union(mesh_blocks);
  return mesh_blocks.count(id) && (id != Moose::INVALID_BLOCK_ID);
}
Referenced by BlockDeletionGenerator::generate(), ExplodeMeshGenerator::generate(), MeshExtruderGenerator::generate(), RefineBlockGenerator::generate(), and hasSubdomainName().
hasSubdomainName()
bool MooseMeshUtils::hasSubdomainName (MeshBase & input_mesh, const SubdomainName & name)
Whether a particular subdomain name exists in the mesh.
Parameters
input mesh over which to determine subdomain names
subdomain name
Definition at line 412 of file MooseMeshUtils.C.
{
  const auto id = getSubdomainID(name, input_mesh);
  return hasSubdomainID(input_mesh, id);
}
Referenced by MultiAppUserObjectTransfer::execute(), BreakMeshByBlockGenerator::generate(), ParsedGenerateSideset::generate(), ParsedSubdomainMeshGenerator::generate(), SideSetsAroundSubdomainGenerator::generate(), SideSetsBetweenSubdomainsGenerator::generate(), SubdomainBoundingBoxGenerator::generate(), and MultiAppDofCopyTransfer::initialSetup().
isCoPlanar() [1/3]
bool MooseMeshUtils::isCoPlanar (const std::vector< Point > vec_pts)
Decides whether all the Points of a vector of Points are coplanar.
Parameters
vec_pts vector of points to be examined
Returns
whether all the Points are in a same plane
Definition at line 342 of file MooseMeshUtils.C.
{
  // Assuming that overlapped Points are allowed, the Points that are overlapped with vec_pts[0] are
  // removed before further calculation.
  std::vector<Point> vec_pts_nonzero{vec_pts[0]};
  for (unsigned int i = 1; i < vec_pts.size(); i++)
    if (!MooseUtils::absoluteFuzzyEqual((vec_pts[i] - vec_pts[0]).norm(), 0.0))
      vec_pts_nonzero.push_back(vec_pts[i]);
  // 3 or fewer points are always coplanar
  if (vec_pts_nonzero.size() <= 3)
    return true;
  else
  {
    for (unsigned int i = 1; i < vec_pts_nonzero.size() - 1; i++)
    {
      const Point tmp_pt = (vec_pts_nonzero[i] - vec_pts_nonzero[0])
                               .cross(vec_pts_nonzero[i + 1] - vec_pts_nonzero[0]);
      // if the three points are not collinear, use cross product as the normal vector of the plane
      if (!MooseUtils::absoluteFuzzyEqual(tmp_pt.norm(), 0.0))
        return isCoPlanar(vec_pts_nonzero, tmp_pt.unit());
    }
  }
  // If all the points are collinear, they are also coplanar
  return true;
}
isCoPlanar() [2/3]
bool MooseMeshUtils::isCoPlanar (const std::vector< Point > vec_pts, const Point plane_nvec)
Decides whether all the Points of a vector of Points are in a plane with a given normal vector.
Parameters
vec_pts vector of points to be examined
plane_nvec normal vector of the plane
Returns
whether all the Points are in the same plane with the given normal vector
Definition at line 336 of file MooseMeshUtils.C.
{
  return isCoPlanar(vec_pts, plane_nvec, vec_pts.front());
}
isCoPlanar() [3/3]
bool MooseMeshUtils::isCoPlanar (const std::vector< Point > vec_pts, const Point plane_nvec, const Point fixed_pt)
Decides whether all the Points of a vector of Points are in a plane that is defined by a normal vector and an inplane Point.
Parameters
vec_pts vector of points to be examined
plane_nvec normal vector of the plane
fixed_pt a Point in the plane
Returns
whether all the Points are in the given plane
Definition at line 327 of file MooseMeshUtils.C.
{
  for (const auto & pt : vec_pts)
    if (!MooseUtils::absoluteFuzzyEqual((pt - fixed_pt) * plane_nvec, 0.0))
      return false;
  return true;
}
Referenced by Positions::arePositionsCoplanar(), FillBetweenPointVectorsTools::fillBetweenPointVectorsGenerator(), and isCoPlanar().
makeOrderedNodeList()
void MooseMeshUtils::makeOrderedNodeList (std::vector< std::pair< dof_id_type, dof_id_type > > & node_assm, std::vector< dof_id_type > & elem_id_list, std::vector< dof_id_type > & ordered_node_list, std::vector< dof_id_type > & ordered_elem_id_list)
Convert a list of sides in the form of a vector of pairs of node ids into a list of ordered nodes based on connectivity.
Parameters
node_assm vector of pairs of node ids that represent the sides
elem_id_list vector of element ids that represent the elements that contain the sides
ordered_node_list vector of node ids that represent the ordered nodes
ordered_elem_id_list vector of element corresponding to the ordered nodes
Definition at line 440 of file MooseMeshUtils.C.
{
  // a flag to indicate if the ordered_node_list has been reversed
  bool isFlipped = false;
  // Start from the first element, try to find a chain of nodes
  mooseAssert(node_assm.size(), "Node list must not be empty");
  ordered_node_list.push_back(node_assm.front().first);
  ordered_node_list.push_back(node_assm.front().second);
  ordered_elem_id_list.push_back(elem_id_list.front());
  // Remove the element that has just been added to ordered_node_list
  node_assm.erase(node_assm.begin());
  elem_id_list.erase(elem_id_list.begin());
  const unsigned int node_assm_size_0 = node_assm.size();
  for (unsigned int i = 0; i < node_assm_size_0; i++)
  {
    // Find nodes to expand the chain
    dof_id_type end_node_id = ordered_node_list.back();
    auto isMatch1 = [end_node_id](std::pair<dof_id_type, dof_id_type> old_id_pair)
    { return old_id_pair.first == end_node_id; };
    auto isMatch2 = [end_node_id](std::pair<dof_id_type, dof_id_type> old_id_pair)
    { return old_id_pair.second == end_node_id; };
    auto result = std::find_if(node_assm.begin(), node_assm.end(), isMatch1);
    bool match_first;
    if (result == node_assm.end())
    {
      match_first = false;
      result = std::find_if(node_assm.begin(), node_assm.end(), isMatch2);
    }
    else
    {
      match_first = true;
    }
    // If found, add the node to boundary_ordered_node_list
    if (result != node_assm.end())
    {
      ordered_node_list.push_back(match_first ? (*result).second : (*result).first);
      node_assm.erase(result);
      const auto elem_index = std::distance(node_assm.begin(), result);
      ordered_elem_id_list.push_back(elem_id_list[elem_index]);
      elem_id_list.erase(elem_id_list.begin() + elem_index);
    }
    // If there are still elements in node_assm and result ==
    // node_assm.end(), this means the curve is not a loop, the
    // ordered_node_list is flipped and try the other direction that has not
    // been examined yet.
    else
    {
      if (isFlipped)
        // Flipped twice; this means the node list has at least two segments.
        throw MooseException("The node list provided has more than one segments.");
      // mark the first flip event.
      isFlipped = true;
      std::reverse(ordered_node_list.begin(), ordered_node_list.end());
      std::reverse(ordered_elem_id_list.begin(), ordered_elem_id_list.end());
      // As this iteration is wasted, set the iterator backward
      i--;
    }
  }
}
Referenced by MooseMeshXYCuttingUtils::boundaryTriElemImprover(), and FillBetweenPointVectorsTools::isClosedLoop().
meshCentroidCalculator()
Point MooseMeshUtils::meshCentroidCalculator (const MeshBase & mesh)
Calculates the centroid of a MeshBase.
Parameters
mesh input mesh whose centroid needs to be calculated
Returns
a Point data containing the mesh centroid
Definition at line 230 of file MooseMeshUtils.C.
{
  Point centroid_pt = Point(0.0, 0.0, 0.0);
  Real vol_tmp = 0.0;
  for (const auto & elem :
       as_range(mesh.active_local_elements_begin(), mesh.active_local_elements_end()))
  {
    Real elem_vol = elem->volume();
    centroid_pt += (elem->true_centroid()) * elem_vol;
    vol_tmp += elem_vol;
  }
  mesh.comm().sum(centroid_pt);
  mesh.comm().sum(vol_tmp);
  centroid_pt /= vol_tmp;
  return centroid_pt;
}
Referenced by FillBetweenSidesetsGenerator::generate(), and MultiAppPositions::initialize().