Zapdos: CompileTimeDerivativesMaterialInternal::details Namespace Reference
CompileTimeDerivativesMaterialInternal::details Namespace Reference
Functions
template<std::size_t first, std::size_t second, std::size_t... tail>
constexpr bool is_sorted ()
Check if the given index sequence is sorted ()internal function)
template<std::size_t N>
constexpr std::size_t factorial ()
Compile time evaluation of the factorial of N.
template<std::size_t N, std::size_t M>
constexpr std::size_t num_derivatives ()
Number of distinct order N derivatives of a function with M variables.
template<std::size_t... first, std::size_t... second>
constexpr auto merge (std::index_sequence< first... >, std::index_sequence< second... >)
Merge two index sequences into one.
template<std::size_t Nmax, std::size_t first, std::size_t... tail>
constexpr auto increment (std::index_sequence< first, tail... >)
Increment the first number in an index sequence, but roll over into the next number if it reaches Nmax.
template<std::size_t M, std::size_t... N>
constexpr std::size_t total_derivatives (std::index_sequence< N... >)
Compute the total number of distinct derivatives for all orders N.
template<std::size_t... Ns>
constexpr auto zeroes (std::index_sequence< Ns... >)
Take an index sequence and return an index sequence of the same length with all entries replaced by zeroes.
Function Documentation
factorial()
template<std::size_t N> constexpr std::size_t CompileTimeDerivativesMaterialInternal::details::factorial () constexpr
Compile time evaluation of the factorial of N.
Definition at line 42 of file CompileTimeDerivativesMaterialInternal.h.
{
  if constexpr (N == 0)
    return 1;
  else if constexpr (N == 1)
    return 1;
  else
    return N * factorial<N - 1>();
}
Referenced by factorial(), and num_derivatives().
increment()
template<std::size_t Nmax, std::size_t first, std::size_t... tail> constexpr auto CompileTimeDerivativesMaterialInternal::details::increment (std::index_sequence< first, tail... >) constexpr
Increment the first number in an index sequence, but roll over into the next number if it reaches Nmax.
This basically increments a base-Nmax number with its digits in reverse!
Definition at line 78 of file CompileTimeDerivativesMaterialInternal.h.
{
  if constexpr (first + 1 == Nmax)
  {
    if constexpr (sizeof...(tail) == 0)
      return std::index_sequence<>{};
    else
      return merge(std::index_sequence<0>{}, increment<Nmax>(std::index_sequence<tail...>{}));
  }
  else
    return std::index_sequence<first + 1, tail...>{};
}
is_sorted()
template<std::size_t first, std::size_t second, std::size_t... tail> constexpr bool CompileTimeDerivativesMaterialInternal::details::is_sorted () constexpr
Check if the given index sequence is sorted ()internal function)
Definition at line 24 of file CompileTimeDerivativesMaterialInternal.h.
{
  if constexpr (first <= second)
  {
    if constexpr (sizeof...(tail) == 0)
      return true;
    else
      return is_sorted<second, tail...>();
  }
  else
    return false;
}
Referenced by is_sorted(), and CompileTimeDerivativesMaterialInternal::is_sorted().
merge()
template<std::size_t... first, std::size_t... second> constexpr auto CompileTimeDerivativesMaterialInternal::details::merge (std::index_sequence< first... > , std::index_sequence< second... >) constexpr
Merge two index sequences into one.
Definition at line 67 of file CompileTimeDerivativesMaterialInternal.h.
{
  return std::index_sequence<first..., second...>{};
}
Referenced by increment().
num_derivatives()
template<std::size_t N, std::size_t M> constexpr std::size_t CompileTimeDerivativesMaterialInternal::details::num_derivatives () constexpr
Number of distinct order N derivatives of a function with M variables.
Definition at line 57 of file CompileTimeDerivativesMaterialInternal.h.
{
  return factorial<N + M - 1>() / (factorial<N>() * factorial<M - 1>());
}
total_derivatives()
template<std::size_t M, std::size_t... N> constexpr std::size_t CompileTimeDerivativesMaterialInternal::details::total_derivatives (std::index_sequence< N... >) constexpr
Compute the total number of distinct derivatives for all orders N.
Definition at line 96 of file CompileTimeDerivativesMaterialInternal.h.
{
  return (num_derivatives<N, M>() + ...);
}
zeroes()
template<std::size_t... Ns> constexpr auto CompileTimeDerivativesMaterialInternal::details::zeroes (std::index_sequence< Ns... >) constexpr
Take an index sequence and return an index sequence of the same length with all entries replaced by zeroes.
Definition at line 107 of file CompileTimeDerivativesMaterialInternal.h.
{
  return std::index_sequence<(void(Ns), 0)...>{};
}
Referenced by CompileTimeDerivativesMaterialInternal::zeroes().