Zapdos: MetaPhysicL Namespace Reference
MetaPhysicL Namespace Reference
We need to instantiate the following CompareTypes to tell the compiler that ADReal is a subtype of ChainedADReal.
Classes
class DualNumber
class NumberArray
struct NWrapper
struct RawType< ColumnMajorMatrixTempl< T > >
struct RawType< Eigen::Matrix< T, M, N, O, M2, N2 > >
struct RawType< RankFourTensorTempl< T > >
struct RawType< RankThreeTensorTempl< T > >
struct RawType< RankTwoTensorTempl< T > >
struct RawType< SymmetricRankFourTensorTempl< T > >
struct RawType< SymmetricRankTwoTensorTempl< T > >
struct ReplaceAlgebraicType< libMesh::RealEigenVector, U >
class SemiDynamicSparseNumberArray
Functions
template<typename T >
auto raw_value (const Eigen::Map< T > &in)
CompareTypes_super (ADReal, ChainedADReal, ChainedADReal)
Detailed Description
We need to instantiate the following CompareTypes to tell the compiler that ADReal is a subtype of ChainedADReal.
Otherwise specialization of operators on DualNumber<T, D> and DualNumber<T2, D2> is ambiguous.
Function Documentation
CompareTypes_super()
MetaPhysicL::CompareTypes_super (ADReal , ChainedADReal , ChainedADReal)
raw_value()
template<typename T > auto MetaPhysicL::raw_value (const Eigen::Map< T > & in)
Definition at line 73 of file ADReal.h.
{
  return raw_value(in.eval());
}
Referenced by MooseUtils::absoluteFuzzyEqual(), MooseUtils::absoluteFuzzyGreaterEqual(), MooseUtils::absoluteFuzzyGreaterThan(), MooseUtils::absoluteFuzzyLessEqual(), MooseUtils::absoluteFuzzyLessThan(), TaggingInterface::addResiduals(), TaggingInterface::addResidualsWithoutConstraints(), Assembly::cacheResiduals(), Assembly::cacheResidualsWithoutConstraints(), Eigen::internal::cast< ADReal, double >(), Eigen::internal::cast< ADReal, int >(), Eigen::internal::cast< ADReal, long >(), Eigen::internal::cast< ADReal, long double >(), InternalSideIntegralVariablePostprocessor::computeFaceInfoIntegral(), SideDiffusiveFluxIntegralTempl< is_ad, T >::computeFaceInfoIntegral(), SideIntegralVariablePostprocessor::computeFaceInfoIntegral(), SideIntegralFunctorPostprocessorTempl< is_ad >::computeLocalContribution(), GradientJumpIndicator::computeQpIntegral(), ElementIntegralFunctorPostprocessorTempl< is_ad >::computeQpIntegral(), ElementIntegralMaterialPropertyTempl< is_ad >::computeQpIntegral(), ElementL2FunctorErrorTempl< is_ad >::computeQpIntegral(), InterfaceDiffusiveFluxIntegralTempl< is_ad >::computeQpIntegral(), InterfaceIntegralVariableValuePostprocessor::computeQpIntegral(), SideAdvectiveFluxIntegralTempl< is_ad >::computeQpIntegral(), SideDiffusiveFluxIntegralTempl< is_ad, T >::computeQpIntegral(), SideIntegralMaterialPropertyTempl< is_ad >::computeQpIntegral(), LayeredSideDiffusiveFluxAverage::computeQpIntegral(), SideIntegralVariableUserObject::computeQpIntegral(), ADSurfaceCharge::computeQpProperties(), MaterialADConverterTempl< T >::computeQpProperties(), MaterialFunctorConverterTempl< T >::computeQpProperties(), FVMatAdvection::computeQpResidual(), ElementExtremeMaterialPropertyTempl< is_ad >::computeQpValue(), FVElementalKernel::computeResidual(), ADNodalKernel::computeResidual(), FVScalarLagrangeMultiplierConstraint::computeResidual(), FVFluxBC::computeResidual(), FVInterfaceKernel::computeResidual(), FVFluxKernel::computeResidual(), FVBoundaryScalarLagrangeMultiplierConstraint::computeResidual(), FVScalarLagrangeMultiplierInterface::computeResidual(), AdvectiveFluxAux::computeValue(), DiffusionFluxAux::computeValue(), DivergenceAuxTempl< is_ad >::computeValue(), FunctorElementalGradientAuxTempl< is_ad >::computeValue(), FunctorVectorElementalAuxTempl< is_ad >::computeValue(), ProjectedStatefulMaterialAuxTempl< T, is_ad >::computeValue(), ADDirichletBCBaseTempl< T >::computeValue(), Moose::RawValueFunctor< T >::evaluate(), Moose::RawValueFunctor< T >::evaluateDot(), Moose::RawValueFunctor< T >::evaluateGradDot(), Moose::RawValueFunctor< T >::evaluateGradient(), ProjectedStatefulMaterialNodalPatchRecoveryTempl< T, is_ad >::execute(), FunctorADConverterTempl< T >::FunctorADConverterTempl(), ElementExtremeFunctorValueTempl< is_ad >::getProxyValuePair(), MaterialRankTwoTensorAuxTempl< is_ad >::getRealValue(), MaterialRateRealAuxTempl< is_ad >::getRealValue(), MaterialRealAuxTempl< is_ad >::getRealValue(), MaterialRealVectorValueAuxTempl< is_ad >::getRealValue(), MaterialStdVectorAuxTempl< is_ad >::getRealValue(), VectorMaterialRealVectorValueAuxTempl< is_ad >::getRealValue(), Moose::FV::greenGaussGradient(), Moose::FV::harmonicInterpolation(), Moose::FV::interpolate(), RankTwoTensorTempl< T >::isSymmetric(), MooseUtils::isZero(), NestedSolveTempl< is_ad >::normSquare(), RankFourTensorTempl< T >::printReal(), SymmetricRankFourTensorTempl< T >::printReal(), SymmetricRankTwoTensorTempl< T >::printReal(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), Moose::Mortar::projectQPoints3d(), raw_value(), moose::internal::rawValueEqualityHelper(), MooseUtils::relativeFuzzyEqual(), MooseUtils::relativeFuzzyGreaterEqual(), MooseUtils::relativeFuzzyGreaterThan(), MooseUtils::relativeFuzzyLessEqual(), MooseUtils::relativeFuzzyLessThan(), Eigen::internal::cast_impl< ADReal, int >::run(), SplineInterpolationBase::sample(), BilinearInterpolation::sampleDerivativeInternal(), PiecewiseMultilinear::sampleInternal(), BilinearInterpolation::sampleInternal(), Function::value(), PiecewiseConstant::value(), PiecewiseMulticonstant::value(), MetaPhysicL::RawType< ColumnMajorMatrixTempl< T > >::value(), MetaPhysicL::RawType< Eigen::Matrix< T, M, N, O, M2, N2 > >::value(), MetaPhysicL::RawType< RankFourTensorTempl< T > >::value(), MetaPhysicL::RawType< RankThreeTensorTempl< T > >::value(), MetaPhysicL::RawType< RankTwoTensorTempl< T > >::value(), MetaPhysicL::RawType< SymmetricRankFourTensorTempl< T > >::value(), MetaPhysicL::RawType< SymmetricRankTwoTensorTempl< T > >::value(), and PiecewiseLinearFromVectorPostprocessor::valueInternal().