Zapdos: InterfaceValueTools Namespace Reference
InterfaceValueTools Namespace Reference
Functions
MooseEnum InterfaceAverageOptions ()
Real getQuantity (const MooseEnum interface_value_type, const Real value_primary, const Real value_secondary)
Function Documentation
getQuantity()
Real InterfaceValueTools::getQuantity (const MooseEnum interface_value_type, const Real value_primary, const Real value_secondary)
Definition at line 28 of file InterfaceValueTools.C.
{
  Real result = 0.;
  switch (interface_value_type)
  {
    case 0: /*average*/
      result = (value_primary + value_secondary) * 0.5;
      break;
    case 1: /*jump_primary_minus_secondary*/
      result = (value_primary - value_secondary);
      break;
    case 2: /*jump_secondary_minus_primary*/
      result = (value_secondary - value_primary);
      break;
    case 3: /*jump_abs*/
      result = std::abs(value_secondary - value_primary);
      break;
    case 4: /*primary*/
      result = value_primary;
      break;
    case 5: /*secondary*/
      result = value_secondary;
      break;
    default:
      mooseError("InterfaceIntegralMaterialPropertyPostprocessor: the supplied integral "
                 "type is not in the list. Available options are: ",
                 InterfaceAverageOptions().getRawNames());
  }
  return result;
}
Referenced by InterfaceValueUserObject::computeInterfaceValueType(), and InterfaceIntegralVariableValuePostprocessor::computeQpIntegral().
InterfaceAverageOptions()
MooseEnum InterfaceValueTools::InterfaceAverageOptions ()
Definition at line 20 of file InterfaceValueTools.C.
{
  return MooseEnum("average jump_primary_minus_secondary jump_secondary_minus_primary "
                   "jump_abs primary secondary",
                   "average");
}
Referenced by getQuantity(), InterfaceIntegralVariableValuePostprocessor::validParams(), and InterfaceValueUserObject::validParams().