Zapdos: Moose Namespace Reference
Moose Namespace Reference
MOOSE now contains C++17 code, so give a reasonable error message stating what the user can do to address this in their environment if C++17 compatibility isn't found.
Namespaces
namespace FV
namespace Mortar
namespace PetscSupport
namespace SlepcSupport
Classes
struct _enumerate_iterator
struct _enumerate_range
struct _enumerate_struct
struct ADType
struct ADType< ADRankFourTensor >
struct ADType< ADRankThreeTensor >
struct ADType< ADRankTwoTensor >
struct ADType< ADReal >
struct ADType< ADSymmetricRankFourTensor >
struct ADType< ADSymmetricRankTwoTensor >
struct ADType< ADVariableGradient >
struct ADType< ADVariableSecond >
struct ADType< ADVariableValue >
struct ADType< ChainedADReal >
struct ADType< ChainedReal >
struct ADType< RankFourTensor >
struct ADType< RankThreeTensor >
struct ADType< RankTwoTensor >
struct ADType< Real >
struct ADType< RealEigenVector >
struct ADType< SymmetricRankFourTensor >
struct ADType< SymmetricRankTwoTensor >
struct ADType< VariableGradient >
struct ADType< VariableSecond >
struct ADType< VariableValue >
struct ADType< W< ADReal > >
struct ADType< W< Real > >
class ADWrapperFunctor
Wraps non-AD functors such that they can be used in objects that have requested the functor as AD.
class ArrayComponentFunctor
This is essentially a forwarding functor that forwards the spatial and temporal evaluation arguments to the parent array functor and then returns the result indexed at a given component.
class ConstantFunctor
Class template for creating constant functors.
struct DOFType
struct DOFType< RealVectorValue >
struct ElemArg
A structure that is used to evaluate Moose functors logically at an element/cell center.
struct ElemPointArg
A structure that is used to evaluate Moose functors at an arbitrary physical point contained within an element.
struct ElemQpArg
Argument for requesting functor evaluation at a quadrature point location in an element.
struct ElemSideQpArg
Argument for requesting functor evaluation at quadrature point locations on an element side.
struct FaceArg
A structure defining a "face" evaluation calling argument for Moose functors.
class FunctorAbstract
Abstract base class that can be used to hold collections of functors.
class FunctorBase
Base class template for functor objects.
class FunctorEnvelope
This is a wrapper that forwards calls to the implementation, which can be switched out at any time without disturbing references to FunctorBase.
class FunctorEnvelopeBase
A non-templated base class for functors that allow an owner object to hold different class template instantiations of Functor in a single container.
struct indirect_comparator
class LibtorchArtificialNeuralNet
class LibtorchArtificialNeuralNetTrainer
Templated class which is responsible for training LibtorchArtificialNeuralNets.
class LibtorchDataset
This class is a wrapper around a libtorch dataset which can be used by the data loaders in the neural net training process.
class LibtorchNeuralNetBase
This base class is meant to gather the functions and members common in every neural network based on Libtorch.
class LibtorchTorchScriptNeuralNet
struct LibtorchTrainingOptions
A struct containing necessary information for training neural networks.
struct NodeArg
class NullFunctor
A functor that serves as a placeholder during the simulation setup phase if a functor consumer requests a functor that has not yet been constructed.
class PassKey
class RawValueFunctor
class ScopedCommSwapper
struct SerialAccess
Serial access requires object data to be stored contiguously.
class SerialAccessRange
struct SerialAccessValueTypeHelper
Value type helper (necessary for any type that does not have a value_type member or where value_type doesn't have a suitable meaning (ADReal)).
struct SerialAccessValueTypeHelper< ADReal >
struct SerialAccessValueTypeHelper< Real >
struct ShapeType
struct ShapeType< Eigen::Matrix< Real, Eigen::Dynamic, 1 > >
struct StateArg
State argument for evaluating functors.
struct TypeList
Helper structure to hold a list of types.
class VectorComponentFunctor
This is essentially a forwarding functor that forwards the spatial and temporal evaluation arguments to the parent vector functor and then returns the result indexed at a given component.
class VectorCompositeFunctor
A functor that returns a vector composed of its component functor evaluations.
Typedefs
template<typename T >
using Functor = FunctorEnvelope< T >
template<typename T , bool is_ad>
using GenericType = typename std::conditional< is_ad, typename ADType< T >::type, T >::type
typedef std::function< void(const InputParameters &, InputParameters &)> RelationshipManagerInputParameterCallback
The type for the callback to set RelationshipManager parameters.
Enumerations
enum SolutionState : int { Current = 0 , Old = 1 , Older = 2 , PreviousNL = -1 }
enum class SolutionIterationType : unsigned short { Time = 0 , Nonlinear }
enum GeometryType { Volume , Face }
enum MaterialDataType {
BLOCK_MATERIAL_DATA , BOUNDARY_MATERIAL_DATA , FACE_MATERIAL_DATA , NEIGHBOR_MATERIAL_DATA ,
INTERFACE_MATERIAL_DATA
}
MaterialData types.
enum AuxGroup { PRE_IC = 0 , PRE_AUX = 1 , POST_AUX = 2 , ALL = 3 }
Flag for AuxKernel related execution type.
enum VarKindType { VAR_NONLINEAR , VAR_AUXILIARY , VAR_ANY }
Framework-wide stuff.
enum VarFieldType {
VAR_FIELD_STANDARD , VAR_FIELD_SCALAR , VAR_FIELD_VECTOR , VAR_FIELD_ARRAY ,
VAR_FIELD_ANY
}
enum CouplingType { COUPLING_DIAG , COUPLING_FULL , COUPLING_CUSTOM }
enum ConstraintSideType { SIDE_PRIMARY , SIDE_SECONDARY }
enum DGResidualType { Element , Neighbor }
enum DGJacobianType { ElementElement , ElementNeighbor , NeighborElement , NeighborNeighbor }
enum ConstraintType { Secondary = Element , Primary = Neighbor }
enum class ElementType : unsigned int { Element = DGResidualType::Element , Neighbor = DGResidualType::Neighbor , Lower = DGResidualType::Neighbor + 1 }
enum class MortarType : unsigned int { Secondary = static_cast<unsigned int>(Moose::ElementType::Element) , Primary = static_cast<unsigned int>(Moose::ElementType::Neighbor) , Lower = static_cast<unsigned int>(Moose::ElementType::Lower) }
enum class ComputeType { Residual , Jacobian , ResidualAndJacobian }
The type of nonlinear computation being performed.
enum class RESTARTABLE_FILTER : unsigned char { RECOVERABLE }
The filter type applied to a particular piece of "restartable" data.
enum ConstraintJacobianType {
SecondarySecondary = ElementElement , SecondaryPrimary = ElementNeighbor , PrimarySecondary = NeighborElement , PrimaryPrimary = NeighborNeighbor ,
LowerLower , LowerSecondary , LowerPrimary , SecondaryLower ,
PrimaryLower
}
enum CoordinateSystemType : int { COORD_XYZ = 0 , COORD_RZ , COORD_RSPHERICAL }
enum PCSideType { PCS_LEFT , PCS_RIGHT , PCS_SYMMETRIC , PCS_DEFAULT }
Preconditioning side.
enum MooseKSPNormType {
KSPN_NONE , KSPN_PRECONDITIONED , KSPN_UNPRECONDITIONED , KSPN_NATURAL ,
KSPN_DEFAULT
}
Norm type for converge test.
enum SolveType {
ST_PJFNK , ST_JFNK , ST_NEWTON , ST_FD ,
ST_LINEAR
}
Type of the solve.
enum EigenSolveType {
EST_POWER , EST_ARNOLDI , EST_KRYLOVSCHUR , EST_JACOBI_DAVIDSON ,
EST_NONLINEAR_POWER , EST_NEWTON , EST_PJFNK , EST_PJFNKMO ,
EST_JFNK
}
Type of the eigen solve.
enum EigenProblemType {
EPT_HERMITIAN , EPT_NON_HERMITIAN , EPT_GEN_HERMITIAN , EPT_GEN_INDEFINITE ,
EPT_GEN_NON_HERMITIAN , EPT_POS_GEN_NON_HERMITIAN , EPT_SLEPC_DEFAULT
}
Type of the eigen problem.
enum WhichEigenPairs {
WEP_LARGEST_MAGNITUDE , WEP_SMALLEST_MAGNITUDE , WEP_LARGEST_REAL , WEP_SMALLEST_REAL ,
WEP_LARGEST_IMAGINARY , WEP_SMALLEST_IMAGINARY , WEP_TARGET_MAGNITUDE , WEP_TARGET_REAL ,
WEP_TARGET_IMAGINARY , WEP_ALL_EIGENVALUES , WEP_SLEPC_DEFAULT
}
Which eigen pairs.
enum TimeIntegratorType {
TI_IMPLICIT_EULER , TI_EXPLICIT_EULER , TI_CRANK_NICOLSON , TI_BDF2 ,
TI_EXPLICIT_MIDPOINT , TI_LSTABLE_DIRK2 , TI_EXPLICIT_TVD_RK_2 , TI_NEWMARK_BETA
}
Time integrators.
enum ConstraintFormulationType { Penalty , Kinematic }
Type of constraint formulation.
enum LineSearchType {
LS_INVALID , LS_DEFAULT , LS_NONE , LS_BASIC ,
LS_SHELL , LS_CONTACT , LS_PROJECT , LS_L2 ,
LS_BT , LS_CP
}
Type of the line search.
enum MffdType { MFFD_INVALID , MFFD_WP , MFFD_DS }
Type of the matrix-free finite-differencing parameter.
enum PatchUpdateType { Never , Always , Auto , Iteration }
Type of patch update strategy for modeling node-face constraints or contact.
enum class RelationshipManagerType : unsigned char { DEFAULT = 0 , GEOMETRIC = 1 << 0 , ALGEBRAIC = 1 << 1 , COUPLING = 1 << 2 }
Main types of Relationship Managers.
enum RMSystemType { NONLINEAR , AUXILIARY , NONE }
enum VectorTagType { VECTOR_TAG_RESIDUAL = 0 , VECTOR_TAG_SOLUTION = 1 , VECTOR_TAG_ANY = 2 }
Functions
InputParameters commonAdaptivityParams ()
void associateSyntaxInner (Syntax &syntax, ActionFactory &action_factory)
void registerAll (Factory &f, ActionFactory &af, Syntax &s)
Register objects that are in MOOSE.
void registerObjects (Factory &factory)
void registerObjects (Factory &factory, const std::set< std::string > &obj_labels)
void addActionTypes (Syntax &syntax)
void registerActions (Syntax &syntax, ActionFactory &action_factory)
Multiple Action class can be associated with a single input file section, in which case all associated Actions will be created and "acted" on when the associated input file section is seen.
void registerActions (Syntax &syntax, ActionFactory &action_factory, const std::set< std::string > &obj_labels)
void associateSyntax (Syntax &syntax, ActionFactory &action_factory)
void setSolverDefaults (FEProblemBase &problem)
MPI_Comm swapLibMeshComm (MPI_Comm new_comm)
Swap the libMesh MPI communicator out for ours.
bool colorConsole ()
Returns whether Console coloring is turned on (default: true).
bool setColorConsole (bool use_color, bool force=false)
Turns color escape sequences on/off for info written to stdout.
void findContactPoint (PenetrationInfo &p_info, FEBase *fe_elem, FEBase *fe_side, FEType &fe_side_type, const Point &secondary_point, bool start_with_centroid, const Real tangential_tolerance, bool &contact_point_on_side)
Finds the closest point (called the contact point) on the primary_elem on side "side" to the secondary_point.
void restrictPointToFace (Point &p, const Elem *side, std::vector< const Node * > &off_edge_nodes)
void to_json (nlohmann::json &json, const Moose::LibtorchArtificialNeuralNet *const &network)
void assemble_matrix (EquationSystems &es, const std::string &system_name)
void compute_jacobian (const NumericVector< Number > &soln, SparseMatrix< Number > &jacobian, NonlinearImplicitSystem &sys)
void compute_bounds (NumericVector< Number > &lower, NumericVector< Number > &upper, NonlinearImplicitSystem &sys)
void compute_nullspace (std::vector< NumericVector< Number > * > &sp, NonlinearImplicitSystem &sys)
void compute_transpose_nullspace (std::vector< NumericVector< Number > * > &sp, NonlinearImplicitSystem &sys)
void compute_nearnullspace (std::vector< NumericVector< Number > * > &sp, NonlinearImplicitSystem &sys)
void compute_postcheck (const NumericVector< Number > &old_soln, NumericVector< Number > &search_direction, NumericVector< Number > &new_soln, bool &changed_search_direction, bool &changed_new_soln, NonlinearImplicitSystem &sys)
std::unordered_map< dof_id_type, Real > globalDofIndexToDerivative (const ADReal &ad_real, const SystemBase &sys, ElementType elem_type=ElementType::Element, THREAD_ID tid=0)
Generate a map from global dof index to derivative value.
bool doDerivatives (const SubProblem &subproblem, const SystemBase &sys)
void initCoordinateSystemType ()
void initSolveType ()
void initEigenSolveType ()
void initEigenProlemType ()
void initWhichEigenPairs ()
void initLineSearchType ()
void initTimeIntegratorsType ()
void initMffdType ()
void initRMType ()
template<>
QuadratureType stringToEnum< QuadratureType > (const std::string &s)
template<>
Order stringToEnum< Order > (const std::string &s)
template<>
CoordinateSystemType stringToEnum< CoordinateSystemType > (const std::string &s)
template<>
SolveType stringToEnum< SolveType > (const std::string &s)
template<>
EigenSolveType stringToEnum< EigenSolveType > (const std::string &s)
template<>
EigenProblemType stringToEnum< EigenProblemType > (const std::string &s)
template<>
WhichEigenPairs stringToEnum< WhichEigenPairs > (const std::string &s)
template<>
LineSearchType stringToEnum< LineSearchType > (const std::string &s)
template<>
TimeIntegratorType stringToEnum< TimeIntegratorType > (const std::string &s)
template<>
MffdType stringToEnum< MffdType > (const std::string &s)
template<>
RelationshipManagerType stringToEnum< RelationshipManagerType > (const std::string &s)
std::string stringify (const RelationshipManagerType &t)
std::string stringify (libMesh::FEFamily f)
std::string stringify (const SolveType &t)
Convert solve type into human readable string.
std::string stringify (const EigenSolveType &t)
Convert eigen solve type into human readable string.
std::string stringify (const VarFieldType &t)
Convert variable field type into human readable string.
std::string stringify (SolutionIterationType t)
Convert SolutionIterationType into string.
std::string stringify (ElementType t)
Convert ElementType into string.
std::string stringify (libMesh::ElemType t)
Convert the libmesh ElemType into string.
std::string stringify (const std::string &s)
Add no-op stringify if the argument already is a string (must use overloading)
std::string stringifyExact (Real)
Stringify Reals with enough precision to guarantee lossless Real -> string -> Real roundtrips.
Point toPoint (const std::vector< Real > &pos)
void findElementsIntersectedByPlane (const Plane &plane, const MeshBase &mesh, std::vector< const Elem * > &intersected_elems)
void elementsIntersectedByPlane (const Point &p0, const Point &normal, const MeshBase &mesh, std::vector< const Elem * > &intersected_elems)
Find all of the elements intersected by a plane.
void elementsIntersectedByPlane (const Point &p0, const Point &p1, const Point &p2, const MeshBase &mesh, std::vector< const Elem * > &intersected_elems)
Find all of the elements intersected by a plane.
std::string getExec ()
std::string getExecutablePath ()
This function returns the PATH of the running executable.
std::string getExecutableName ()
This function returns the name of the running executable.
int sideIntersectedByLine (const Elem *elem, std::vector< int > &not_side, const LineSegment &line_segment, Point &intersection_point)
Figure out which (if any) side of an Elem is intersected by a line.
int sideNeighborIsOn (const Elem *elem, const Elem *neighbor)
Returns the side number for elem that neighbor is on.
void recursivelyFindElementsIntersectedByLine (const LineSegment &line_segment, const Elem *current_elem, int incoming_side, const Point &incoming_point, std::vector< Elem * > &intersected_elems, std::vector< LineSegment > &segments)
Recursively find all elements intersected by a line segment.
void elementsIntersectedByLine (const Point &p0, const Point &p1, const MeshBase &mesh, const PointLocatorBase &point_locator, std::vector< Elem * > &intersected_elems, std::vector< LineSegment > &segments)
Find all of the elements intersected by a line.
StateArg currentState ()
StateArg oldState ()
StateArg previousNonlinearState ()
void initial_condition (EquationSystems &es, const std::string &system_name)
bool globalADIndexing ()
Whether we are using global AD indexing.
std::size_t adOffset (unsigned int var_num, std::size_t max_dofs_per_elem, ElementType element_type=ElementType::Element, unsigned int num_vars_in_system=0)
Helper function for computing automatic differentiation offset.
std::size_t adOffset (unsigned int var_num, std::size_t max_dofs_per_elem, DGJacobianType dg_jacobian_type, unsigned int num_vars_in_system=0)
template<typename T >
auto globalDofIndexToDerivative (const T &ad_real_container, const SystemBase &sys, ElementType elem_type=ElementType::Element, THREAD_ID tid=0) -> std::vector< std::unordered_map< dof_id_type, typename std::enable_if< std::is_same< ADReal, typename T::value_type >::value, Real >::type > >
Generate a map from global dof index to derivative value for a (probably quadrature-point-based) container like a material property or a variable value.
template<typename T >
T stringToEnum (const std::string &s)
template<>
QuadratureType stringToEnum< QuadratureType > (const std::string &s)
template<>
Order stringToEnum< Order > (const std::string &s)
template<>
CoordinateSystemType stringToEnum< CoordinateSystemType > (const std::string &s)
template<>
SolveType stringToEnum< SolveType > (const std::string &s)
template<>
LineSearchType stringToEnum< LineSearchType > (const std::string &s)
template<>
TimeIntegratorType stringToEnum< TimeIntegratorType > (const std::string &s)
template<>
RelationshipManagerType stringToEnum< RelationshipManagerType > (const std::string &s)
template<typename T >
std::vector< T > vectorStringsToEnum (const MultiMooseEnum &v)
template<typename T >
std::string stringify (const T &t)
conversion to string
std::string stringify (bool v)
std::string stringify (int v)
std::string stringify (long v)
std::string stringify (long long v)
std::string stringify (unsigned int v)
std::string stringify (unsigned long v)
std::string stringify (unsigned long long v)
std::string stringify (FEFamily f)
Convert FEType from libMesh into string.
template<typename T , typename U >
std::string stringify (const std::pair< T, U > &p, const std::string &delim=":")
Add pair stringify to support maps.
template<template< typename... > class T, typename... U>
std::string stringify (const T< U... > &c, const std::string &delim=", ", const std::string &elem_encl="", bool enclose_list_in_curly_braces=false)
Convert a container to a string with elements separated by delimiter of user's choice.
template<class Iterator >
_enumerate_range< Iterator > enumerate (Iterator first, Iterator last, typename std::iterator_traits< Iterator >::difference_type initial)
Enumerate function for iterating over a range and obtaining both a reference to the underlying type and an index simultaneously.
template<class Container >
_enumerate_range< typename Container::iterator > enumerate (Container &content)
template<class Container >
_enumerate_range< typename Container::const_iterator > enumerate (const Container &content)
template<class RandomAccessIterator >
void initialize_indirect_sort (RandomAccessIterator beg, RandomAccessIterator end, std::vector< size_t > &b)
template<class RandomAccessIterator >
void indirectSort (RandomAccessIterator beg, RandomAccessIterator end, std::vector< size_t > &b)
template<class RandomAccessIterator , class UserComparisonFunctor >
void indirectSort (RandomAccessIterator beg, RandomAccessIterator end, std::vector< size_t > &b, UserComparisonFunctor user_comp)
template<typename T >
void applyIndices (T &container, const std::vector< size_t > &indices)
Uses indices created by the indirectSort function to sort the given container (which must support random access, resizing, and std::swap.
void hash_combine (std::size_t &)
Used for hash function specialization for Attribute objects.
template<typename T , typename... Rest>
void hash_combine (std::size_t &seed, const T &v, Rest &&... rest)
Used to combine an existing hash value with the hash of one or more other values (v and rest).
template<typename T , typename... Rest>
void hash_combine (std::size_t &seed, const std::vector< T > &v, Rest &&... rest)
Used for hash function specialization for Attribute objects.
template<typename T , typename... Rest>
void hash_combine (std::size_t &seed, const std::set< T > &v, Rest &&... rest)
Used for hash function specialization for Attribute objects.
template<typename T >
T fe_lagrange_1D_shape (const Order order, const unsigned int i, const T &xi)
template<typename T >
T fe_lagrange_1D_shape_deriv (const Order order, const unsigned int i, const T &xi)
template<typename T , template< typename > class VectorType>
T fe_lagrange_2D_shape (const ElemType type, const Order order, const unsigned int i, const VectorType< T > &p)
template<typename T , template< typename > class VectorType>
T fe_lagrange_2D_shape_deriv (const ElemType type, const Order order, const unsigned int i, const unsigned int j, const VectorType< T > &p)
std::string stringify (const Moose::TimeIntegratorType &t)
template<std::size_t N>
void derivInsert (NumberArray< N, Real > &derivs, dof_id_type index, Real value)
SERIAL_ACCESS_SCALAR (Real)
SERIAL_ACCESS_SCALAR (ADReal)
SERIAL_ACCESS_CONST_SIZE (VectorValue, &obj(0u), Moose::dim)
SERIAL_ACCESS_CONST_SIZE (RankTwoTensorTempl, &obj(0u, 0u), RankTwoTensorTempl< T >::N2)
SERIAL_ACCESS_CONST_SIZE (RankFourTensorTempl, &obj(0u, 0u, 0u, 0u), RankFourTensorTempl< T >::N4)
SERIAL_ACCESS_DYNAMIC_SIZE (DenseVector, &obj(0u), obj.size())
template<typename T >
SerialAccessRange< T > serialAccess (T &obj)
template<template< typename, int > class L, int I, typename T , typename... Ts, typename... As>
void typeLoopInternal (TypeList< T, Ts... >, As... args)
Type loop.
template<template< typename, int > class L, typename... Ts, typename... As>
void typeLoop (TypeList< Ts... >, As... args)
Type loop.
template<std::size_t N>
void derivInsert (SemiDynamicSparseNumberArray< Real, libMesh::dof_id_type, NWrapper< N > > &derivs, libMesh::dof_id_type index, Real value)
template<typename T >
void initDofIndices (T &data, const Elem &elem)
Variables
static bool _color_console = isatty(fileno(stdout))
bool _warnings_are_errors = false
Variable to toggle any warning into an error (includes deprecated code warnings)
bool _deprecated_is_error = false
Variable to toggle only deprecated warnings as errors.
bool _throw_on_error = false
Variable to turn on exceptions during mooseError(), should only be used within MOOSE unit tests or when about to perform threaded operations because exception throwing in threaded regions is safe while aborting is inherently not when singletons are involved (e.g.
bool _throw_on_warning = false
Variable to turn on exceptions during mooseWarning(), should only be used in MOOSE unit tests.
int interrupt_signal_number = 0
Used by the signal handler to determine if we should write a checkpoint file out at any point during operation.
bool show_trace = true
Set to true (the default) to print the stack trace with error and warning messages - false to omit it.
bool show_multiple = false
Set to false (the default) to display an error message only once for each error call code location (as opposed to every time the code is executed).
std::map< std::string, CoordinateSystemType > coordinate_system_type_to_enum
std::map< std::string, SolveType > solve_type_to_enum
std::map< std::string, EigenSolveType > eigen_solve_type_to_enum
std::map< std::string, EigenProblemType > eigen_problem_type_to_enum
std::map< std::string, WhichEigenPairs > which_eigen_pairs_to_enum
std::map< std::string, LineSearchType > line_search_type_to_enum
std::map< std::string, TimeIntegratorType > time_integrator_to_enum
std::map< std::string, MffdType > mffd_type_to_enum
std::map< std::string, RelationshipManagerType > rm_type_to_enum
const processor_id_type INVALID_PROCESSOR_ID = libMesh::DofObject::invalid_processor_id
const SubdomainID ANY_BLOCK_ID = libMesh::Elem::invalid_subdomain_id - 1
const SubdomainID INTERNAL_SIDE_LOWERD_ID = libMesh::Elem::invalid_subdomain_id - 2
const SubdomainID BOUNDARY_SIDE_LOWERD_ID = libMesh::Elem::invalid_subdomain_id - 3
const SubdomainID INVALID_BLOCK_ID = libMesh::Elem::invalid_subdomain_id
const BoundaryID ANY_BOUNDARY_ID = static_cast<BoundaryID>(-1)
const BoundaryID INVALID_BOUNDARY_ID = libMesh::BoundaryInfo::invalid_id
const TagID INVALID_TAG_ID = static_cast<TagID>(-1)
const TagTypeID INVALID_TAG_TYPE_ID = static_cast<TagTypeID>(-1)
const TagName SOLUTION_TAG = "SOLUTION"
const TagName OLD_SOLUTION_TAG = "SOLUTION_STATE_1"
const TagName OLDER_SOLUTION_TAG = "SOLUTION_STATE_2"
const TagName PREVIOUS_NL_SOLUTION_TAG = "U_PREVIOUS_NL_NEWTON"
static constexpr std::size_t dim = LIBMESH_DIM
This is the dimension of all vector and tensor datastructures used in MOOSE.
PerfLog perf_log
Perflog to be used by applications.
bool _trap_fpe
Variable indicating whether we will enable FPE trapping for this run.
ExecFlagEnum execute_flags
Storage for the registered execute flags.
constexpr std::size_t constMaxQpsPerElem = 216
This is used for places where we initialize some qp-sized data structures that would end up being sized too small after the quadrature order gets bumped (dynamically in-sim).
template<class T >
constexpr std::false_type always_false {}
This is a helper variable template for cases when we want to use a default compile-time error with constexpr-based if conditions.
const std::set< SubdomainID > EMPTY_BLOCK_IDS = {}
const std::set< BoundaryID > EMPTY_BOUNDARY_IDS = {}
Detailed Description
MOOSE now contains C++17 code, so give a reasonable error message stating what the user can do to address this in their environment if C++17 compatibility isn't found.
Typedef Documentation
Functor
template<typename T > using Moose::Functor = typedef FunctorEnvelope<T>
Definition at line 33 of file MooseFunctorForward.h.
GenericType
template<typename T , bool is_ad> using Moose::GenericType = typedef typename std::conditional<is_ad, typename ADType<T>::type, T>::type
Definition at line 555 of file MooseTypes.h.
RelationshipManagerInputParameterCallback
typedef std::function<void(const InputParameters &, InputParameters &)> Moose::RelationshipManagerInputParameterCallback
The type for the callback to set RelationshipManager parameters.
Definition at line 900 of file MooseTypes.h.
Enumeration Type Documentation
AuxGroup
enum Moose::AuxGroup
Flag for AuxKernel related execution type.
Enumerator
PRE_IC
PRE_AUX
POST_AUX
ALL
Definition at line 614 of file MooseTypes.h.
{
  PRE_IC = 0,
  PRE_AUX = 1,
  POST_AUX = 2,
  ALL = 3
};
ComputeType
enum class Moose::ComputeType strong
The type of nonlinear computation being performed.
Enumerator
Residual
Jacobian
ResidualAndJacobian
Definition at line 691 of file MooseTypes.h.
{
  Residual,
  Jacobian,
  ResidualAndJacobian
};
ConstraintFormulationType
enum Moose::ConstraintFormulationType
Type of constraint formulation.
Enumerator
Penalty
Kinematic
Definition at line 828 of file MooseTypes.h.
{
  Penalty,
  Kinematic
};
ConstraintJacobianType
enum Moose::ConstraintJacobianType
Enumerator
SecondarySecondary
SecondaryPrimary
PrimarySecondary
PrimaryPrimary
LowerLower
LowerSecondary
LowerPrimary
SecondaryLower
PrimaryLower
Definition at line 707 of file MooseTypes.h.
{
  SecondarySecondary = ElementElement,
  SecondaryPrimary = ElementNeighbor,
  PrimarySecondary = NeighborElement,
  PrimaryPrimary = NeighborNeighbor,
  LowerLower,
  LowerSecondary,
  LowerPrimary,
  SecondaryLower,
  PrimaryLower
};
ConstraintSideType
enum Moose::ConstraintSideType
Enumerator
SIDE_PRIMARY
SIDE_SECONDARY
Definition at line 648 of file MooseTypes.h.
{
  SIDE_PRIMARY,
  SIDE_SECONDARY
};
ConstraintType
enum Moose::ConstraintType
Enumerator
Secondary
Primary
Definition at line 668 of file MooseTypes.h.
{
  Secondary = Element,
  Primary = Neighbor
};
CoordinateSystemType
enum Moose::CoordinateSystemType : int
Enumerator
COORD_XYZ
COORD_RZ
COORD_RSPHERICAL
Definition at line 720 of file MooseTypes.h.
{
  COORD_XYZ = 0,
  COORD_RZ,
  COORD_RSPHERICAL
};
CouplingType
enum Moose::CouplingType
Enumerator
COUPLING_DIAG
COUPLING_FULL
COUPLING_CUSTOM
Definition at line 641 of file MooseTypes.h.
{
  COUPLING_DIAG,
  COUPLING_FULL,
  COUPLING_CUSTOM
};
DGJacobianType
enum Moose::DGJacobianType
Enumerator
ElementElement
ElementNeighbor
NeighborElement
NeighborNeighbor
Definition at line 660 of file MooseTypes.h.
{
  ElementElement,
  ElementNeighbor,
  NeighborElement,
  NeighborNeighbor
};
DGResidualType
enum Moose::DGResidualType
Enumerator
Element
Neighbor
Definition at line 654 of file MooseTypes.h.
{
  Element,
  Neighbor
};
EigenProblemType
enum Moose::EigenProblemType
Type of the eigen problem.
Enumerator
EPT_HERMITIAN
Hermitian.
EPT_NON_HERMITIAN
Non-Hermitian.
EPT_GEN_HERMITIAN
Generalized Hermitian.
EPT_GEN_INDEFINITE
Generalized Hermitian indefinite.
EPT_GEN_NON_HERMITIAN
Generalized Non-Hermitian.
EPT_POS_GEN_NON_HERMITIAN
Generalized Non-Hermitian with positive (semi-)definite B.
EPT_SLEPC_DEFAULT
use whatever SLPEC has by default
Definition at line 781 of file MooseTypes.h.
{
  EPT_HERMITIAN,
  EPT_NON_HERMITIAN,
  EPT_GEN_HERMITIAN,
  EPT_GEN_INDEFINITE,
  EPT_GEN_NON_HERMITIAN,
  EPT_POS_GEN_NON_HERMITIAN,
  EPT_SLEPC_DEFAULT
};
EigenSolveType
enum Moose::EigenSolveType
Type of the eigen solve.
Enumerator
EST_POWER
Power / Inverse / RQI.
EST_ARNOLDI
Arnoldi.
EST_KRYLOVSCHUR
Krylov-Schur.
EST_JACOBI_DAVIDSON
Jacobi-Davidson.
EST_NONLINEAR_POWER
Nonlinear inverse power.
EST_NEWTON
Newton-based eigensolver with an assembled Jacobian matrix (fully coupled by default)
EST_PJFNK
Preconditioned Jacobian-free Newton Krylov.
EST_PJFNKMO
The same as PJFNK except that matrix-vector multiplication is employed to replace residual evaluation in linear solver.
EST_JFNK
Jacobian-free Newton Krylov.
Definition at line 765 of file MooseTypes.h.
{
  EST_POWER,
  EST_ARNOLDI,
  EST_KRYLOVSCHUR,
  EST_JACOBI_DAVIDSON,
  EST_NONLINEAR_POWER,
  EST_NEWTON,
  EST_PJFNK,
  EST_PJFNKMO,
  EST_JFNK
};
ElementType
enum class Moose::ElementType : unsigned int strong
Enumerator
Element
Neighbor
Lower
Definition at line 674 of file MooseTypes.h.
{
  Element = DGResidualType::Element,
  Neighbor = DGResidualType::Neighbor,
  Lower = DGResidualType::Neighbor + 1
};
GeometryType
enum Moose::GeometryType
Enumerator
Volume
Face
Definition at line 236 of file MooseTypes.h.
{
  Volume,
  Face
};
LineSearchType
enum Moose::LineSearchType
Type of the line search.
Enumerator
LS_INVALID
means not set
LS_DEFAULT
LS_NONE
LS_BASIC
LS_SHELL
LS_CONTACT
LS_PROJECT
LS_L2
LS_BT
LS_CP
Definition at line 836 of file MooseTypes.h.
{
  LS_INVALID,
  LS_DEFAULT,
  LS_NONE,
  LS_BASIC,
  LS_SHELL,
  LS_CONTACT,
  LS_PROJECT,
  LS_L2,
  LS_BT,
  LS_CP
};
MaterialDataType
enum Moose::MaterialDataType
MaterialData types.
See also
FEProblemBase, MaterialPropertyInterface
Enumerator
BLOCK_MATERIAL_DATA
BOUNDARY_MATERIAL_DATA
FACE_MATERIAL_DATA
NEIGHBOR_MATERIAL_DATA
INTERFACE_MATERIAL_DATA
Definition at line 602 of file MooseTypes.h.
{
  BLOCK_MATERIAL_DATA,
  BOUNDARY_MATERIAL_DATA,
  FACE_MATERIAL_DATA,
  NEIGHBOR_MATERIAL_DATA,
  INTERFACE_MATERIAL_DATA
};
MffdType
enum Moose::MffdType
Type of the matrix-free finite-differencing parameter.
Enumerator
MFFD_INVALID
means not set
MFFD_WP
MFFD_DS
Definition at line 853 of file MooseTypes.h.
{
  MFFD_INVALID,
  MFFD_WP,
  MFFD_DS
};
MooseKSPNormType
enum Moose::MooseKSPNormType
Norm type for converge test.
Enumerator
KSPN_NONE
KSPN_PRECONDITIONED
KSPN_UNPRECONDITIONED
KSPN_NATURAL
KSPN_DEFAULT
Use whatever we have in PETSc.
Definition at line 741 of file MooseTypes.h.
{
  KSPN_NONE,
  KSPN_PRECONDITIONED,
  KSPN_UNPRECONDITIONED,
  KSPN_NATURAL,
  KSPN_DEFAULT
};
MortarType
enum class Moose::MortarType : unsigned int strong
Enumerator
Secondary
Primary
Lower
Definition at line 681 of file MooseTypes.h.
{
  Secondary = static_cast<unsigned int>(Moose::ElementType::Element),
  Primary = static_cast<unsigned int>(Moose::ElementType::Neighbor),
  Lower = static_cast<unsigned int>(Moose::ElementType::Lower)
};
PatchUpdateType
enum Moose::PatchUpdateType
Type of patch update strategy for modeling node-face constraints or contact.
Enumerator
Never
Always
Auto
Iteration
Definition at line 863 of file MooseTypes.h.
{
  Never,
  Always,
  Auto,
  Iteration
};
PCSideType
enum Moose::PCSideType
Preconditioning side.
Enumerator
PCS_LEFT
PCS_RIGHT
PCS_SYMMETRIC
PCS_DEFAULT
Use whatever we have in PETSc.
Definition at line 730 of file MooseTypes.h.
{
  PCS_LEFT,
  PCS_RIGHT,
  PCS_SYMMETRIC,
  PCS_DEFAULT
};
RelationshipManagerType
enum class Moose::RelationshipManagerType : unsigned char strong
Main types of Relationship Managers.
Enumerator
DEFAULT
GEOMETRIC
ALGEBRAIC
COUPLING
Definition at line 874 of file MooseTypes.h.
{
  DEFAULT = 0,
  GEOMETRIC = 1 << 0,
  ALGEBRAIC = 1 << 1,
  COUPLING = 1 << 2
};
RESTARTABLE_FILTER
enum class Moose::RESTARTABLE_FILTER : unsigned char strong
The filter type applied to a particular piece of "restartable" data.
These filters will be applied during deserialization to include or exclude data as appropriate.
Enumerator
RECOVERABLE
Definition at line 702 of file MooseTypes.h.
{
  RECOVERABLE
};
RMSystemType
enum Moose::RMSystemType
Enumerator
NONLINEAR
AUXILIARY
NONE
Definition at line 882 of file MooseTypes.h.
{
  NONLINEAR,
  AUXILIARY,
  NONE
};
SolutionIterationType
enum class Moose::SolutionIterationType : unsigned short strong
Enumerator
Time
Nonlinear
Definition at line 229 of file MooseTypes.h.
{
  Time = 0,
  Nonlinear
};
SolutionState
enum Moose::SolutionState : int
Enumerator
Current
Old
Older
PreviousNL
Definition at line 221 of file MooseTypes.h.
{
  Current = 0,
  Old = 1,
  Older = 2,
  PreviousNL = -1
};
SolveType
enum Moose::SolveType
Type of the solve.
Enumerator
ST_PJFNK
Preconditioned Jacobian-Free Newton Krylov.
ST_JFNK
Jacobian-Free Newton Krylov.
ST_NEWTON
Full Newton Solve.
ST_FD
Use finite differences to compute Jacobian.
ST_LINEAR
Solving a linear problem.
Definition at line 753 of file MooseTypes.h.
{
  ST_PJFNK,
  ST_JFNK,
  ST_NEWTON,
  ST_FD,
  ST_LINEAR
};
TimeIntegratorType
enum Moose::TimeIntegratorType
Time integrators.
Enumerator
TI_IMPLICIT_EULER
TI_EXPLICIT_EULER
TI_CRANK_NICOLSON
TI_BDF2
TI_EXPLICIT_MIDPOINT
TI_LSTABLE_DIRK2
TI_EXPLICIT_TVD_RK_2
TI_NEWMARK_BETA
Definition at line 813 of file MooseTypes.h.
{
  TI_IMPLICIT_EULER,
  TI_EXPLICIT_EULER,
  TI_CRANK_NICOLSON,
  TI_BDF2,
  TI_EXPLICIT_MIDPOINT,
  TI_LSTABLE_DIRK2,
  TI_EXPLICIT_TVD_RK_2,
  TI_NEWMARK_BETA
};
VarFieldType
enum Moose::VarFieldType
Enumerator
VAR_FIELD_STANDARD
VAR_FIELD_SCALAR
VAR_FIELD_VECTOR
VAR_FIELD_ARRAY
VAR_FIELD_ANY
Definition at line 632 of file MooseTypes.h.
{
  VAR_FIELD_STANDARD,
  VAR_FIELD_SCALAR,
  VAR_FIELD_VECTOR,
  VAR_FIELD_ARRAY,
  VAR_FIELD_ANY
};
VarKindType
enum Moose::VarKindType
Framework-wide stuff.
Enumerator
VAR_NONLINEAR
VAR_AUXILIARY
VAR_ANY
Definition at line 625 of file MooseTypes.h.
{
  VAR_NONLINEAR,
  VAR_AUXILIARY,
  VAR_ANY
};
VectorTagType
enum Moose::VectorTagType
Enumerator
VECTOR_TAG_RESIDUAL
VECTOR_TAG_SOLUTION
VECTOR_TAG_ANY
Definition at line 889 of file MooseTypes.h.
{
  VECTOR_TAG_RESIDUAL = 0,
  VECTOR_TAG_SOLUTION = 1,
  VECTOR_TAG_ANY = 2
};
WhichEigenPairs
enum Moose::WhichEigenPairs
Which eigen pairs.
Enumerator
WEP_LARGEST_MAGNITUDE
largest magnitude
WEP_SMALLEST_MAGNITUDE
smallest magnitude
WEP_LARGEST_REAL
largest real
WEP_SMALLEST_REAL
smallest real
WEP_LARGEST_IMAGINARY
largest imaginary
WEP_SMALLEST_IMAGINARY
smallest imaginary
WEP_TARGET_MAGNITUDE
target magnitude
WEP_TARGET_REAL
target real
WEP_TARGET_IMAGINARY
target imaginary
WEP_ALL_EIGENVALUES
all eigenvalues
WEP_SLEPC_DEFAULT
use whatever we have in SLEPC
Definition at line 795 of file MooseTypes.h.
{
  WEP_LARGEST_MAGNITUDE,
  WEP_SMALLEST_MAGNITUDE,
  WEP_LARGEST_REAL,
  WEP_SMALLEST_REAL,
  WEP_LARGEST_IMAGINARY,
  WEP_SMALLEST_IMAGINARY,
  WEP_TARGET_MAGNITUDE,
  WEP_TARGET_REAL,
  WEP_TARGET_IMAGINARY,
  WEP_ALL_EIGENVALUES,
  WEP_SLEPC_DEFAULT
};
Function Documentation
addActionTypes()
void Moose::addActionTypes (Syntax & syntax)
The (optional) last param here indicates whether the task should trigger an Action auto-build. If a task is marked as "true". Then MOOSE will attempt to build the associated Action if one is not supplied by some other means (usually through the input file or custom Action). Only Actions that do not have required parameters and have defaults for all optional parameters can be built automatically (See ActionWarehouse.C).
Note: Many of the actions in the "Minimal Problem" section are marked as false. However, we can generally force creation of these "Action"s as needed by registering them to syntax that we expect to see even if those "Action"s don't normally pick up parameters from the input file.
Additional Actions
The following is the default set of action dependencies for a basic MOOSE problem. The formatting of this string is important. Each line represents a set of dependencies that depend on the previous line. Items on the same line have equal weight and can be executed in any order.
Additional dependencies can be inserted later inside of user applications with calls to ActionWarehouse::addDependency("task", "pre_req")
Definition at line 77 of file Moose.C.
{
  // clang-format off
  /**************************/
  /**** Register Actions ****/
  /**************************/
  registerMooseObjectTask("create_problem",               Problem,                false);
  registerMooseObjectTask("setup_executioner",            Executioner,            false);
  registerMooseObjectTask("read_executor",                Executor,               false);
  registerTask("add_executor", true);
  // This task does not construct an object, but it needs all of the parameters that
  // would normally be used to construct an object.
  registerMooseObjectTask("determine_system_type",        Executioner,            true);
  registerMooseObjectTask("setup_mesh",                   MooseMesh,              false);
  registerMooseObjectTask("set_mesh_base",                MooseMesh,              false);
  registerMooseObjectTask("init_mesh",                    MooseMesh,              false);
  registerMooseObjectTask("add_mesh_generator",           MeshGenerator,          false);
  registerTask("create_added_mesh_generators", true);
  registerMooseObjectTask("append_mesh_generator",        MeshGenerator,          false);
  registerMooseObjectTask("add_kernel",                   Kernel,                 false);
  appendMooseObjectTask  ("add_kernel",                   EigenKernel);
  appendMooseObjectTask  ("add_kernel",                   VectorKernel);
  appendMooseObjectTask  ("add_kernel",                   ArrayKernel);
  registerMooseObjectTask("add_variable",                 MooseVariableBase,      false);
  registerMooseObjectTask("add_aux_variable",             MooseVariableBase,      false);
  registerMooseObjectTask("add_elemental_field_variable", MooseVariableBase,      false);
  registerMooseObjectTask("add_nodal_kernel",             NodalKernel,            false);
  registerMooseObjectTask("add_functor_material",         MaterialBase,           false);
  registerMooseObjectTask("add_material",                 MaterialBase,           false);
  registerMooseObjectTask("add_bc",                       BoundaryCondition,      false);
  registerMooseObjectTask("add_function",                 Function,               false);
  registerMooseObjectTask("add_distribution",             Distribution,           false);
  registerMooseObjectTask("add_sampler",                  Sampler,                false);
  registerMooseObjectTask("add_aux_kernel",               AuxKernel,              false);
  appendMooseObjectTask  ("add_aux_kernel",               VectorAuxKernel);
  appendMooseObjectTask  ("add_aux_kernel",               ArrayAuxKernel);
  registerMooseObjectTask("add_scalar_kernel",            ScalarKernel,           false);
  registerMooseObjectTask("add_aux_scalar_kernel",        AuxScalarKernel,        false);
  registerMooseObjectTask("add_dirac_kernel",             DiracKernel,            false);
  appendMooseObjectTask  ("add_dirac_kernel",             VectorDiracKernel);
  registerMooseObjectTask("add_dg_kernel",                DGKernel,               false);
  registerMooseObjectTask("add_fv_kernel",                FVKernel,               false);
  registerMooseObjectTask("add_fv_bc",                    FVBoundaryCondition,    false);
  registerMooseObjectTask("add_fv_ik",                    FVInterfaceKernel,      false);
  registerMooseObjectTask("add_interface_kernel",         InterfaceKernel,        false);
  appendMooseObjectTask  ("add_interface_kernel",         VectorInterfaceKernel);
  registerMooseObjectTask("add_constraint",               Constraint,             false);
  registerMooseObjectTask("add_ic",                       InitialCondition,       false);
  appendMooseObjectTask  ("add_ic",                       ScalarInitialCondition);
  registerMooseObjectTask("add_fv_ic",                    FVInitialCondition,     false);
  registerMooseObjectTask("add_damper",                   Damper,                 false);
  registerMooseObjectTask("setup_predictor",              Predictor,              false);
  registerMooseObjectTask("add_time_steppers",            TimeStepper,            false);
  registerMooseObjectTask("add_time_stepper",             TimeStepper,            false);
  registerTask           ("compose_time_stepper",                                 true);
  registerMooseObjectTask("setup_time_integrator",        TimeIntegrator,         false);
  registerMooseObjectTask("add_preconditioning",          MoosePreconditioner,    false);
  registerMooseObjectTask("add_field_split",              Split,                  false);
  registerMooseObjectTask("add_mesh_division",            MeshDivision,           false);
  registerMooseObjectTask("add_user_object",              UserObject,             false);
  appendMooseObjectTask  ("add_user_object",              Postprocessor);
  registerMooseObjectTask("add_postprocessor",            Postprocessor,          false);
  registerMooseObjectTask("add_vector_postprocessor",     VectorPostprocessor,    false);
  registerMooseObjectTask("add_reporter",                 Reporter,               false);
  registerMooseObjectTask("add_positions",                Positions,              false);
  registerMooseObjectTask("add_times",                    Times,                  false);
  registerMooseObjectTask("add_indicator",                Indicator,              false);
  registerMooseObjectTask("add_marker",                   Marker,                 false);
  registerMooseObjectTask("add_multi_app",                MultiApp,               false);
  registerMooseObjectTask("add_transfer",                 Transfer,               false);
  registerMooseObjectTask("add_output",                   Output,                 false);
  registerMooseObjectTask("add_control",                  Control,                false);
  registerMooseObjectTask("add_partitioner",              MoosePartitioner,       false);
  // clang-format on
  registerTask("dynamic_object_registration", false);
  registerTask("common_output", true);
  registerTask("setup_recover_file_base", true);
  registerTask("recover_meta_data", true);
  registerTask("add_bounds_vectors", false);
  registerTask("add_periodic_bc", false);
  registerTask("add_aux_variable", false);
  registerTask("add_external_aux_variables", true);
  registerTask("add_variable", false);
  registerTask("add_mortar_variable", false);
  registerTask("execute_mesh_generators", true);
  registerTask("uniform_refine_mesh", false);
  registerTask("prepare_mesh", false);
  registerTask("delete_remote_elements_after_late_geometric_ghosting", false);
  registerTask("setup_mesh_complete", true); // calls prepare
  registerTask("post_mesh_prepared", false);
  registerTask("add_geometric_rm", false);
  registerTask("attach_geometric_rm", true);
  registerTask("attach_geometric_rm_final", true);
  registerTask("init_displaced_problem", false);
  registerTask("add_algebraic_rm", false);
  registerTask("attach_algebraic_rm", true);
  registerTask("add_coupling_rm", false);
  registerTask("attach_coupling_rm", true);
  registerTask("init_problem", true);
  registerTask("check_copy_nodal_vars", true);
  registerTask("copy_nodal_vars", true);
  registerTask("copy_nodal_aux_vars", true);
  registerTask("setup_postprocessor_data", false);
  registerTask("setup_time_steppers", true);
  registerTask("setup_dampers", true);
  registerTask("check_integrity", true);
  registerTask("resolve_optional_materials", true);
  registerTask("check_integrity_early", true);
  registerTask("setup_quadrature", true);
  registerTask("no_action", false); // Used for Empty Action placeholders
  registerTask("set_global_params", false);
  registerTask("setup_adaptivity", false);
  registerTask("meta_action", false);
  registerTask("setup_residual_debug", false);
  registerTask("setup_oversampling", false);
  registerTask("deprecated_block", false);
  registerTask("set_adaptivity_options", false);
  registerTask("add_mortar_interface", false);
  registerTask("coupling_functor_check", true);
  registerTask("add_master_action_material", false);
  registerTask("setup_projected_properties", false);
  // Dummy Actions (useful for sync points in the dependencies)
  registerTask("setup_function_complete", false);
  registerTask("setup_variable_complete", false);
  registerTask("setup_executioner_complete", false);
  registerTask("ready_to_init", true);
  // Output related actions
  registerTask("add_output_aux_variables", true);
  registerTask("check_output", true);
  registerTask("declare_late_reporters", true);
  registerTask("create_problem_default", true);
  registerTask("create_problem_custom", false);
  registerTask("create_problem_complete", false);
  // Action for setting up the signal-based checkpoint
  registerTask("auto_checkpoint_action", true);
  /**************************/
  /****** Dependencies ******/
  /**************************/
  // clang-format off
  syntax.addDependencySets("(meta_action)"
                           "(dynamic_object_registration)"
                           "(common_output)"
                           "(set_global_params)"
                           "(setup_recover_file_base)"
                           "(check_copy_nodal_vars)"
                           "(setup_mesh)"
                           "(add_geometric_rm)"
                           "(add_partitioner)"
                           "(add_mesh_generator)"
                           "(create_added_mesh_generators)"
                           "(append_mesh_generator)"
                           "(execute_mesh_generators)"
                           "(recover_meta_data)"
                           "(set_mesh_base)"
                           "(attach_geometric_rm)"
                           "(init_mesh)"
                           "(prepare_mesh)"
                           "(add_mortar_interface)"
                           "(uniform_refine_mesh)"
                           "(setup_mesh_complete)"
                           "(post_mesh_prepared)"
                           "(determine_system_type)"
                           "(create_problem)"
                           "(create_problem_custom)"
                           "(create_problem_default)"
                           "(create_problem_complete)"
                           "(setup_postprocessor_data)"
                           "(setup_time_integrator)"
                           "(setup_executioner)"
                           "(setup_executioner_complete)"
                           "(read_executor)"
                           "(add_executor)"
                           "(check_integrity_early)"
                           "(setup_predictor)"
                           "(init_displaced_problem)"
                           "(add_aux_variable, add_variable, add_elemental_field_variable,"
                           " add_external_aux_variables)"
                           "(add_mortar_variable)"
                           "(setup_variable_complete)"
                           "(setup_quadrature)"
                           "(add_function)"
                           "(add_periodic_bc)"
                           "(add_user_object)"
                           "(add_distribution)"
                           "(add_sampler)"
                           "(setup_function_complete)"
                           "(setup_adaptivity)"
                           "(set_adaptivity_options)"
                           "(add_ic, add_fv_ic)"
                           "(add_constraint, add_field_split)"
                           "(add_preconditioning)"
                           "(add_times)"
                           "(add_time_stepper, add_time_steppers)"
                           "(compose_time_stepper)"
                           "(setup_time_steppers)"
                           "(ready_to_init)"
                           "(setup_dampers)"
                           "(setup_residual_debug)"
                           "(add_bounds_vectors)"
                           "(add_positions)"
                           "(add_mesh_division)"  // NearestPositionsDivision uses a Positions
                           "(add_multi_app)"
                           "(add_transfer)"
                           "(copy_nodal_vars, copy_nodal_aux_vars)"
                           "(add_material)"
                           "(add_master_action_material)"
                           "(add_functor_material)"
                           "(setup_projected_properties)"
                           "(add_output_aux_variables)"
                           "(add_output)"
                           "(auto_checkpoint_action)"
                           "(add_postprocessor)"
                           "(add_vector_postprocessor)" // MaterialVectorPostprocessor requires this
                                                        // to be after material objects are created.
                           "(add_reporter)"
                           "(declare_late_reporters)"
                           "(add_aux_kernel, add_bc, add_damper, add_dirac_kernel, add_kernel,"
                           " add_nodal_kernel, add_dg_kernel, add_fv_kernel, add_fv_bc, add_fv_ik,"
                           " add_interface_kernel, add_scalar_kernel, add_aux_scalar_kernel,"
                           " add_indicator, add_marker)"
                           "(resolve_optional_materials)"
                           "(add_algebraic_rm)"
                           "(add_coupling_rm)"
                           "(attach_geometric_rm_final)"
                           "(attach_algebraic_rm)"
                           "(attach_coupling_rm)"
                           "(coupling_functor_check)"
                           "(delete_remote_elements_after_late_geometric_ghosting)"
                           "(init_problem)"
                           "(add_control)"
                           "(check_output)"
                           "(check_integrity)");
  // clang-format on
}
Referenced by associateSyntaxInner().
adOffset() [1/2]
std::size_t Moose::adOffset (unsigned int var_num, std::size_t max_dofs_per_elem, DGJacobianType dg_jacobian_type, unsigned int num_vars_in_system = 0) inline
Definition at line 109 of file ADUtils.h.
{
  if (dg_jacobian_type == DGJacobianType::ElementElement ||
      dg_jacobian_type == DGJacobianType::NeighborElement)
    return adOffset(var_num, max_dofs_per_elem, ElementType::Element);
  else
    return adOffset(var_num, max_dofs_per_elem, ElementType::Neighbor, num_vars_in_system);
}
adOffset() [2/2]
std::size_t Moose::adOffset (unsigned int var_num, std::size_t max_dofs_per_elem, ElementType element_type = ElementType::Element, unsigned int num_vars_in_system = 0) inline
Helper function for computing automatic differentiation offset.
Let's explain how our derivative index numbering scheme works:
Let's just think about continuous finite elements for a second. We use a variable major numbering scheme, such that each variables indices are in a contiguous block. Let's imagine we have two variables, u and v, and we're on a QUAD4. The AD indices will be ordered like this:
u0, u1, u2, u3, v0, v1, v2, v3
max_dofs_per_elem should be for a QUAD4: 4. For a QUAD9, 9. HEX27, 27. Etc. For CFEM the offset will be simply be the max_dofs_per_elem number times the var_num. So for u on a QUAD4: 4 * 0 = 0. For v: 4 * 1. So u indices start at index 0, v indices start at index 4.
With DFEM or interface kernels it's a little more complicated. We essentially already have an indices block that is num_vars_in_system * max_dofs_per_elem long, so in our two var, QUAD4 example: 4 * 2 = 8. So what we do is that if we are on a neighbor element, we do an additional offset by num_vars_in_system * max_dofs_per_elem. So now our derivative indices are ordered like this:
u0, u1, u2, u3, v0, v1, v2, v3, u0_neighbor, u1_neighbor, u2_neighbor, u3_neighbor, v0_neighbor, v1_neighbor, v2_neighbor, v3_neighbor
Finally if a lower-dimensional element is involved, then we another offset of num_vars_in_system * max_dofs_per_elem:
u0, u1, u2, u3, v0, v1, v2, v3, u0_neighbor, u1_neighbor, u2_neighbor, u3_neighbor, v0_neighbor, v1_neighbor, v2_neighbor, v3_neighbor, u0_lower, u1_lower, u2_lower, u3_lower, v0_lower, v1_lower, v2_lower, v3_lower
Note that a lower dimensional block will have less indices than a higher dimensional one, but we do not optimize for that consideration at this time
Parameters
var_num The variable number we are calculating the offset for
max_dofs_per_elem The maximum number of degrees of freedom for any one variable on an element
element_type The "type" of element that we are on. Current options are ElementType::Element, ElementType::Neighbor, and ElementType::Lower
num_vars_in_system The number of vars in the system. This is used in offset calculation unless element_type is ElementType::Element
Returns
The automatic differentiation indexing offset
Definition at line 79 of file ADUtils.h.
{
  // If our element type is anything other than ElementType::Element, then the user must
  // supply num_vars_in_system in order to calculate the offset
  mooseAssert(element_type == ElementType::Element || num_vars_in_system,
              "If our element type is anything other than ElementType::Element, then you "
              "must supply num_vars_in_system in order to calculate the offset");
  switch (element_type)
  {
    case ElementType::Element:
      return var_num * max_dofs_per_elem;
    case ElementType::Neighbor:
      return num_vars_in_system * max_dofs_per_elem + var_num * max_dofs_per_elem;
    case ElementType::Lower:
      return 2 * num_vars_in_system * max_dofs_per_elem + var_num * max_dofs_per_elem;
    default:
      mooseError(
          "Unsupported element type ",
          static_cast<typename std::underlying_type<decltype(element_type)>::type>(element_type));
  }
}
Referenced by adOffset(), and globalDofIndexToDerivative().
applyIndices()
template<typename T > void Moose::applyIndices (T & container, const std::vector< size_t > & indices)
Uses indices created by the indirectSort function to sort the given container (which must support random access, resizing, and std::swap.
Definition at line 108 of file IndirectSort.h.
{
  T tmp;
  tmp.resize(container.size());
  for (size_t i = 0; i < indices.size(); i++)
    tmp[i] = container[indices[i]];
  std::swap(tmp, container);
}
assemble_matrix()
void Moose::assemble_matrix (EquationSystems & es, const std::string & system_name)
Definition at line 40 of file NonlinearEigenSystem.C.
{
  EigenProblem * p = es.parameters.get<EigenProblem *>("_eigen_problem");
  EigenSystem & eigen_system = es.get_system<EigenSystem>(system_name);
  NonlinearEigenSystem & eigen_nl = p->getNonlinearEigenSystem(/*nl_sys_num=*/0);
  // If this is a nonlinear eigenvalue problem,
  // we do not need to assemble anything
  if (p->isNonlinearEigenvalueSolver())
  {
    // If you want an efficient eigensolver,
    // please use PETSc 3.13 or newer.
    // We need to do an unnecessary assembly,
    // if you use PETSc that is older than 3.13.
#if PETSC_RELEASE_LESS_THAN(3, 13, 0)
    if (eigen_system.has_matrix_B())
      p->computeJacobianTag(*eigen_system.current_local_solution,
                            eigen_system.get_matrix_B(),
                            eigen_nl.eigenMatrixTag());
#endif
    return;
  }
#if !PETSC_RELEASE_LESS_THAN(3, 13, 0)
  // If we use shell matrices and do not use a shell preconditioning matrix,
  // we only need to form a preconditioning matrix
  if (eigen_system.use_shell_matrices() && !eigen_system.use_shell_precond_matrix())
  {
    p->computeJacobianTag(*eigen_system.current_local_solution,
                          eigen_system.get_precond_matrix(),
                          eigen_nl.precondMatrixTag());
    return;
  }
#endif
  // If it is a linear generalized eigenvalue problem,
  // we assemble A and B together
  if (eigen_system.generalized())
  {
    p->computeJacobianAB(*eigen_system.current_local_solution,
                         eigen_system.get_matrix_A(),
                         eigen_system.get_matrix_B(),
                         eigen_nl.nonEigenMatrixTag(),
                         eigen_nl.eigenMatrixTag());
#if LIBMESH_HAVE_SLEPC
    if (p->negativeSignEigenKernel())
      MatScale(static_cast<PetscMatrix<Number> &>(eigen_system.get_matrix_B()).mat(), -1.0);
#endif
    return;
  }
  // If it is a linear eigenvalue problem, we assemble matrix A
  {
    p->computeJacobianTag(*eigen_system.current_local_solution,
                          eigen_system.get_matrix_A(),
                          eigen_nl.nonEigenMatrixTag());
    return;
  }
}
Referenced by NonlinearEigenSystem::NonlinearEigenSystem().
associateSyntax()
void Moose::associateSyntax (Syntax & syntax, ActionFactory & action_factory)
Definition at line 588 of file Moose.C.
{
  associateSyntaxInner(syntax, action_factory);
  registerActions(syntax, action_factory);
}
associateSyntaxInner()
void Moose::associateSyntaxInner (Syntax & syntax, ActionFactory & action_factory)
Note: the optional third parameter is used to differentiate which task is satisfied based on the syntax encountered for classes which are registered to satisfy more than one task
Variable/AuxVariable Actions
Note: the optional third parameter is used to differentiate which task is satisfied based on the syntax encountered for classes which are registered to satisfy more than one task
Variable/AuxVariable Actions
Definition at line 413 of file Moose.C.
{
  registerSyntaxTask("CopyNodalVarsAction", "Variables/*", "check_copy_nodal_vars");
  registerSyntaxTask("CopyNodalVarsAction", "Variables/*", "copy_nodal_vars");
  registerSyntaxTask("CopyNodalVarsAction", "AuxVariables/*", "check_copy_nodal_vars");
  registerSyntaxTask("CopyNodalVarsAction", "AuxVariables/*", "copy_nodal_aux_vars");
  registerSyntaxTask("AddKernelAction", "Kernels/*", "add_kernel");
  registerSyntaxTask("AddNodalKernelAction", "NodalKernels/*", "add_nodal_kernel");
  registerSyntaxTask("AddKernelAction", "AuxKernels/*", "add_aux_kernel");
  registerSyntaxTask("AddKernelAction", "Bounds/*", "add_aux_kernel");
  registerSyntax("AddAuxKernelAction", "AuxVariables/*/AuxKernel");
  registerSyntaxTask("AddScalarKernelAction", "ScalarKernels/*", "add_scalar_kernel");
  registerSyntaxTask("AddScalarKernelAction", "AuxScalarKernels/*", "add_aux_scalar_kernel");
  registerSyntaxTask("AddBCAction", "BCs/*", "add_bc");
  registerSyntax("CreateProblemAction", "Problem");
  registerSyntax("DynamicObjectRegistrationAction", "Problem");
  registerSyntax("SetupMeshAction", "Mesh");
  registerSyntax("SetupMeshCompleteAction", "Mesh");
  registerSyntax("CreateDisplacedProblemAction", "Mesh");
  registerSyntax("DisplayGhostingAction", "Mesh");
  registerSyntax("AddMeshGeneratorAction", "Mesh/*");
  registerSyntax("ElementIDOutputAction", "Mesh");
  syntax.registerSyntaxType("Mesh/*", "MeshGeneratorName");
  registerSyntax("AddFunctionAction", "Functions/*");
  syntax.registerSyntaxType("Functions/*", "FunctionName");
  registerSyntax("AddMeshDivisionAction", "MeshDivisions/*");
  syntax.registerSyntaxType("MeshDivisions/*", "MeshDivisionName");
  registerSyntax("GlobalParamsAction", "GlobalParams");
  registerSyntax("AddDistributionAction", "Distributions/*");
  syntax.registerSyntaxType("Distributions/*", "DistributionName");
  registerSyntax("AddSamplerAction", "Samplers/*");
  syntax.registerSyntaxType("Samplers/*", "SamplerName");
  registerSyntax("SetupDebugAction", "Debug");
  registerSyntax("SetupResidualDebugAction", "Debug");
  registerSyntax("AddVariableAction", "Variables/*");
  syntax.registerSyntaxType("Variables/*", "VariableName");
  syntax.registerSyntaxType("Variables/*", "NonlinearVariableName");
  registerSyntax("AddICAction", "Variables/*/InitialCondition");
  registerSyntax("AddFVICAction", "Variables/*/FVInitialCondition");
  registerSyntax("AddAuxVariableAction", "AuxVariables/*");
  syntax.registerSyntaxType("AuxVariables/*", "VariableName");
  syntax.registerSyntaxType("AuxVariables/*", "AuxVariableName");
  registerSyntax("AddICAction", "AuxVariables/*/InitialCondition");
  registerSyntax("AddFVICAction", "AuxVariables/*/FVInitialCondition");
  registerSyntaxTask("EmptyAction", "BCs/Periodic", "no_action"); // placeholder
  registerSyntax("AddPeriodicBCAction", "BCs/Periodic/*");
  registerSyntaxTask("AddInitialConditionAction", "ICs/*", "add_ic");
  registerSyntaxTask("AddFVInitialConditionAction", "FVICs/*", "add_fv_ic");
  registerSyntax("AddMaterialAction", "Materials/*");
  syntax.registerSyntaxType("Materials/*", "MaterialName");
  registerSyntax("AddFunctorMaterialAction", "FunctorMaterials/*");
  syntax.registerSyntaxType("FunctorMaterials/*", "MaterialName");
  registerSyntax("AddPostprocessorAction", "Postprocessors/*");
  syntax.registerSyntaxType("Postprocessors/*", "PostprocessorName");
  syntax.registerSyntaxType("Postprocessors/*", "UserObjectName");
  registerSyntax("AddVectorPostprocessorAction", "VectorPostprocessors/*");
  syntax.registerSyntaxType("VectorPostprocessors/*", "VectorPostprocessorName");
  registerSyntax("AddReporterAction", "Reporters/*");
  syntax.registerSyntaxType("Reporters/*", "ReporterName");
  registerSyntax("AddPositionsAction", "Positions/*");
  syntax.registerSyntaxType("Positions/*", "PositionsName");
  registerSyntax("AddTimesAction", "Times/*");
  syntax.registerSyntaxType("Times/*", "TimesName");
  registerSyntax("AddDamperAction", "Dampers/*");
  registerSyntax("AddOutputAction", "Outputs/*");
  registerSyntax("CommonOutputAction", "Outputs");
  syntax.registerSyntaxType("Outputs/*", "OutputName");
  // Note: Preconditioner Actions will be built by this setup action
  registerSyntax("SetupPreconditionerAction", "Preconditioning/*");
  registerSyntax("AddFieldSplitAction", "Preconditioning/*/*");
  registerSyntax("CreateExecutionerAction", "Executioner");
  registerSyntax("ReadExecutorParamsAction", "Executors/*");
  registerSyntaxTask("AddTimeStepperAction", "Executioner/TimeSteppers/*", "add_time_steppers");
  registerSyntaxTask("AddTimeStepperAction", "Executioner/TimeStepper", "add_time_stepper");
  registerSyntaxTask(
      "ComposeTimeStepperAction", "Executioner/TimeSteppers", "compose_time_stepper");
  registerSyntax("SetupTimeIntegratorAction", "Executioner/TimeIntegrator");
  syntax.registerSyntaxType("Executors/*", "ExecutorName");
  registerSyntax("SetupQuadratureAction", "Executioner/Quadrature");
  registerSyntax("SetupPredictorAction", "Executioner/Predictor");
#ifdef LIBMESH_ENABLE_AMR
  registerSyntax("AdaptivityAction", "Executioner/Adaptivity");
#endif
  registerSyntax("PartitionerAction", "Mesh/Partitioner");
  registerSyntax("AddDiracKernelAction", "DiracKernels/*");
  registerSyntax("AddDGKernelAction", "DGKernels/*");
  registerSyntax("AddFVKernelAction", "FVKernels/*");
  registerSyntax("AddFVBCAction", "FVBCs/*");
  registerSyntax("AddFVInterfaceKernelAction", "FVInterfaceKernels/*");
  registerSyntax("CheckFVBCAction", "FVBCs");
  registerSyntax("AddInterfaceKernelAction", "InterfaceKernels/*");
  registerSyntax("AddConstraintAction", "Constraints/*");
  registerSyntax("AddUserObjectAction", "UserObjects/*");
  syntax.registerSyntaxType("UserObjects/*", "UserObjectName");
  registerSyntax("AddControlAction", "Controls/*");
  registerSyntax("AddBoundsVectorsAction", "Bounds");
  registerSyntax("AddNodalNormalsAction", "NodalNormals");
  // Indicator
  registerSyntax("AddElementalFieldAction", "Adaptivity/Indicators/*");
  registerSyntax("AddIndicatorAction", "Adaptivity/Indicators/*");
  syntax.registerSyntaxType("Adaptivity/Indicators/*", "IndicatorName");
  // Marker
  registerSyntax("AddElementalFieldAction", "Adaptivity/Markers/*");
  registerSyntax("AddMarkerAction", "Adaptivity/Markers/*");
  syntax.registerSyntaxType("Adaptivity/Markers/*", "MarkerName");
  // New Adaptivity System
  registerSyntax("SetAdaptivityOptionsAction", "Adaptivity");
  // Deprecated Block
  registerSyntax("DeprecatedBlockAction", "DeprecatedBlock");
  // Multi Apps
  registerSyntax("AddMultiAppAction", "MultiApps/*");
  syntax.registerSyntaxType("MultiApps/*", "MultiAppName");
  // Transfers
  registerSyntax("AddTransferAction", "Transfers/*");
  // Material derivative test
  registerSyntaxTask("EmptyAction", "Debug/MaterialDerivativeTest", "no_action"); // placeholder
  registerSyntax("MaterialDerivativeTestAction", "Debug/MaterialDerivativeTest/*");
  registerSyntax("ProjectedStatefulMaterialStorageAction", "ProjectedStatefulMaterialStorage/*");
  addActionTypes(syntax);
}
Referenced by associateSyntax(), and registerAll().
colorConsole()
bool Moose::colorConsole ()
Returns whether Console coloring is turned on (default: true).
Definition at line 612 of file Moose.C.
{
  return _color_console;
}
commonAdaptivityParams()
InputParameters Moose::commonAdaptivityParams ()
Definition at line 24 of file SetAdaptivityOptionsAction.C.
{
  InputParameters params = Action::validParams();
  params.addParam<unsigned int>(
      "steps", 0, "The number of adaptive steps to use when doing a Steady simulation.");
  params.addRangeCheckedParam<unsigned int>(
      "interval", 1, "interval>0", "The number of time steps betweeen each adaptivity phase");
  params.addParam<unsigned int>(
      "max_h_level",
      0,
      "Maximum number of times a single element can be refined. If 0 then infinite.");
  params.addParam<Real>("start_time",
                        -std::numeric_limits<Real>::max(),
                        "The time that adaptivity will be active after.");
  params.addParam<Real>("stop_time",
                        std::numeric_limits<Real>::max(),
                        "The time after which adaptivity will no longer be active.");
  params.addParam<unsigned int>(
      "cycles_per_step",
      1,
      "The number of adaptive steps to use when on each timestep during a Transient simulation.");
  params.addParam<bool>(
      "recompute_markers_during_cycles", false, "Recompute markers during adaptivity cycles");
  params.addParam<bool>("switch_h_to_p_refinement", false, "True to perform p-refinement");
  const auto families_enum = AddVariableAction::getNonlinearVariableFamilies();
  MultiMooseEnum disable_p_refinement_for_families(families_enum.getRawNames());
  params.addParam<MultiMooseEnum>("disable_p_refinement_for_families",
                                  disable_p_refinement_for_families,
                                  "What families we should disable p-refinement for.");
  return params;
}
Referenced by AdaptivityAction::validParams(), and SetAdaptivityOptionsAction::validParams().
compute_bounds()
void Moose::compute_bounds (NumericVector< Number > & lower, NumericVector< Number > & upper, NonlinearImplicitSystem & sys)
Definition at line 43 of file NonlinearSystem.C.
{
  FEProblemBase * p =
      sys.get_equation_systems().parameters.get<FEProblemBase *>("_fe_problem_base");
  p->computeBounds(sys, lower, upper);
}
Referenced by NonlinearSystem::NonlinearSystem().
compute_jacobian()
void Moose::compute_jacobian (const NumericVector< Number > & soln, SparseMatrix< Number > & jacobian, NonlinearImplicitSystem & sys)
Definition at line 33 of file NonlinearSystem.C.
{
  FEProblemBase * p =
      sys.get_equation_systems().parameters.get<FEProblemBase *>("_fe_problem_base");
  p->computeJacobianSys(sys, soln, jacobian);
}
Referenced by NonlinearSystem::NonlinearSystem(), and NonlinearSystem::setupColoringFiniteDifferencedPreconditioner().
compute_nearnullspace()
void Moose::compute_nearnullspace (std::vector< NumericVector< Number > * > & sp, NonlinearImplicitSystem & sys)
Definition at line 70 of file NonlinearSystem.C.
{
  FEProblemBase * p =
      sys.get_equation_systems().parameters.get<FEProblemBase *>("_fe_problem_base");
  p->computeNearNullSpace(sys, sp);
}
Referenced by NonlinearSystem::NonlinearSystem().
compute_nullspace()
void Moose::compute_nullspace (std::vector< NumericVector< Number > * > & sp, NonlinearImplicitSystem & sys)
Definition at line 53 of file NonlinearSystem.C.
{
  FEProblemBase * p =
      sys.get_equation_systems().parameters.get<FEProblemBase *>("_fe_problem_base");
  p->computeNullSpace(sys, sp);
}
Referenced by NonlinearSystem::NonlinearSystem().
compute_postcheck()
void Moose::compute_postcheck (const NumericVector< Number > & old_soln, NumericVector< Number > & search_direction, NumericVector< Number > & new_soln, bool & changed_search_direction, bool & changed_new_soln, NonlinearImplicitSystem & sys)
Definition at line 78 of file NonlinearSystem.C.
{
  FEProblemBase * p =
      sys.get_equation_systems().parameters.get<FEProblemBase *>("_fe_problem_base");
  p->computePostCheck(
      sys, old_soln, search_direction, new_soln, changed_search_direction, changed_new_soln);
}
Referenced by NonlinearSystem::solve().
compute_transpose_nullspace()
void Moose::compute_transpose_nullspace (std::vector< NumericVector< Number > * > & sp, NonlinearImplicitSystem & sys)
Definition at line 61 of file NonlinearSystem.C.
{
  FEProblemBase * p =
      sys.get_equation_systems().parameters.get<FEProblemBase *>("_fe_problem_base");
  p->computeTransposeNullSpace(sys, sp);
}
Referenced by NonlinearSystem::NonlinearSystem().
currentState()
StateArg Moose::currentState () inline
Definition at line 244 of file MooseFunctorArguments.h.
{
  return {};
}
Referenced by MooseVariableDataFV< OutputType >::computeAD(), GradientJumpIndicator::computeQpIntegral(), MaterialFunctorConverterTempl< T >::computeQpProperties(), FunctorNeumannBC::computeQpResidual(), FunctorDirichletBC::computeQpValue(), TransientInterface::determineState(), and Moose::FunctorBase< T >::queryFVArgCache().
derivInsert() [1/2]
template<std::size_t N> void Moose::derivInsert (NumberArray< N, Real > & derivs, dof_id_type index, Real value) inline
Definition at line 20 of file NumberArrayOps.h.
{
  mooseAssert(index < MOOSE_AD_MAX_DOFS_PER_ELEM,
              "The requested derivative index "
                  << index << " is not less than " << MOOSE_AD_MAX_DOFS_PER_ELEM
                  << ". You can run `configure --with-derivative-size=<n>` to request a larger "
                     "derivative container.");
  derivs[index] = value;
}
Referenced by MooseVariableScalar::computeAD(), MooseVariableData< OutputType >::computeAD(), MooseVariableDataFV< OutputType >::computeAD(), Assembly::computeFaceMap(), ADPenaltyPeriodicSegmentalConstraint::computeQpResidual(), ADPeriodicSegmentalConstraint::computeQpResidual(), ADPenaltyPeriodicSegmentalConstraint::computeScalarQpResidual(), Assembly::computeSinglePointMapAD(), MooseVariableFE< OutputType >::computeSolution(), MooseVariableFE< OutputType >::evaluate(), MooseVariableData< OutputType >::fetchADDoFValues(), and MooseVariableDataFV< OutputType >::fetchADDoFValues().
derivInsert() [2/2]
template<std::size_t N> void Moose::derivInsert (SemiDynamicSparseNumberArray< Real, libMesh::dof_id_type, NWrapper< N > > & derivs, libMesh::dof_id_type index, Real value) inline
Definition at line 20 of file SparseOps.h.
{
#ifndef NDEBUG
  try
  {
    derivs.insert(index) = value;
  }
  catch (MetaPhysicL::LogicError &)
  {
    mooseError("The last insertion into the sparse derivative storage container exceeded the "
               "underlying array size. Consider running `configure --with-derivative-size=<n>` to "
               "obtain a larger underlying container");
  }
#else
  derivs.insert(index) = value;
#endif
}
doDerivatives()
bool Moose::doDerivatives (const SubProblem & subproblem, const SystemBase & sys)
Returns
whether we should be doing derivatives
Definition at line 79 of file ADUtils.C.
{
  return ADReal::do_derivatives && sys.number() == subproblem.currentNlSysNum();
}
Referenced by MooseVariableData< OutputType >::computeAD(), MooseVariableFE< OutputType >::computeSolution(), and MooseVariableFE< OutputType >::evaluate().
elementsIntersectedByLine()
void Moose::elementsIntersectedByLine (const Point & p0, const Point & p1, const MeshBase & mesh, const PointLocatorBase & point_locator, std::vector< Elem * > & intersected_elems, std::vector< LineSegment > & segments)
Find all of the elements intersected by a line.
The line is given as the beginning and ending points
Parameters
p0 The beginning of the line
p1 The end of the line
intersected_elems The elements intersected by the line. Will be empty if there are no intersections.
segments The line segments across each element
Definition at line 192 of file RayTracing.C.
{
  // Make sure our list is clear
  intersected_elems.clear();
  // Find the starting element
  const Elem * first_elem = point_locator(p0);
  // Quick return if can't even locate the first element.
  if (!first_elem)
    return;
  intersected_elems.push_back(const_cast<Elem *>(first_elem));
  // Make a LineSegment object out of our two points for ease:
  LineSegment line_segment = LineSegment(p0, p1);
  // Find 'em!
  recursivelyFindElementsIntersectedByLine(
      line_segment, first_elem, -1, p0, intersected_elems, segments);
}
Referenced by ElementsAlongLine::execute(), IntersectionPointsAlongLine::execute(), and LineMaterialSamplerBase< T >::execute().
elementsIntersectedByPlane() [1/2]
void Moose::elementsIntersectedByPlane (const Point & p0, const Point & normal, const MeshBase & mesh, std::vector< const Elem * > & intersected_elems)
Find all of the elements intersected by a plane.
The plane is given as a point and a normal vector.
Parameters
p0 Point in plane.
normal Normal vector to plane.
intersected_elems The elements intersected by the plane. Will be empty if there are no intersections.
Definition at line 53 of file ElementsIntersectedByPlane.C.
{
  // Make sure our list is clear
  intersected_elems.clear();
  // Create plane from point and normal:
  Plane plane(p0, normal);
  // Find 'em!
  findElementsIntersectedByPlane(plane, mesh, intersected_elems);
}
Referenced by ElementsAlongPlane::execute().
elementsIntersectedByPlane() [2/2]
void Moose::elementsIntersectedByPlane (const Point & p0, const Point & p1, const Point & p2, const MeshBase & mesh, std::vector< const Elem * > & intersected_elems)
Find all of the elements intersected by a plane.
The plane is given as three points in the plane.
Parameters
p0 Point in plane.
p1 Point in plane.
p2 Point in plane.
intersected_elems The elements intersected by the plane. Will be empty if there are no intersections.
Definition at line 69 of file ElementsIntersectedByPlane.C.
{
  // Make sure our list is clear
  intersected_elems.clear();
  // Create plane from three points:
  Plane plane(p0, p1, p2);
  // Find 'em!
  findElementsIntersectedByPlane(plane, mesh, intersected_elems);
}
enumerate() [1/3]
template<class Container > _enumerate_range< typename Container::const_iterator > Moose::enumerate (const Container & content)
Definition at line 68 of file Enumerate.h.
{
  return _enumerate_range<typename Container::const_iterator>(
      std::begin(content), std::end(content), 0);
}
enumerate() [2/3]
template<class Container > _enumerate_range< typename Container::iterator > Moose::enumerate (Container & content)
Definition at line 61 of file Enumerate.h.
{
  return _enumerate_range<typename Container::iterator>(std::begin(content), std::end(content), 0);
}
enumerate() [3/3]
template<class Iterator > _enumerate_range< Iterator > Moose::enumerate (Iterator first, Iterator last, typename std::iterator_traits< Iterator >::difference_type initial)
Enumerate function for iterating over a range and obtaining both a reference to the underlying type and an index simultaneously.
This method is forward-compatible with the C++17 structured bindings capability.
C++11 compatible usage:
for (auto it : Moose::enumerate(values)) _console << it.index() << ": " << it.value() << '
';
// Here the third argument is the starting index value for (auto it : Moose::enumerate(values.begin(), values.end(), 0)) _console << it.index() << ": " << it.value() << '
';
C++17 usage (DO NOT USE IN MOOSE):
for (auto [index, value] : Moose::enumerate(values)) _console << index << ": " << value << '
';
// Here the third argument is the starting index value for (auto [index, value] : Moose::enumerate(values.begin(), values.end(), 0)) _console << index << ": " << value << '
';
Definition at line 52 of file Enumerate.h.
{
  return _enumerate_range<Iterator>(first, last, initial);
}
Referenced by JvarMapInterfaceBase< T >::JvarMapInterfaceBase(), NearestPointAverage::nearestPointIndex(), NearestPointIntegralVariablePostprocessor::nearestPointIndex(), and NearestPointBase< UserObjectType, BaseType >::nearestUserObject().
fe_lagrange_1D_shape()
template<typename T > T Moose::fe_lagrange_1D_shape (const Order order, const unsigned int i, const T & xi)
Definition at line 22 of file MooseLagrangeHelpers.h.
{
  switch (order)
  {
      // Lagrange linears
    case FIRST:
    {
      libmesh_assert_less(i, 2);
      switch (i)
      {
        case 0:
          return .5 * (1. - xi);
        case 1:
          return .5 * (1. + xi);
        default:
          mooseError("Invalid shape function index i = ", i);
      }
    }
      // Lagrange quadratics
    case SECOND:
    {
      libmesh_assert_less(i, 3);
      switch (i)
      {
        case 0:
          return .5 * xi * (xi - 1.);
        case 1:
          return .5 * xi * (xi + 1);
        case 2:
          return (1. - xi * xi);
        default:
          mooseError("Invalid shape function index i = ", i);
      }
    }
      // Lagrange cubics
    case THIRD:
    {
      libmesh_assert_less(i, 4);
      switch (i)
      {
        case 0:
          return 9. / 16. * (1. / 9. - xi * xi) * (xi - 1.);
        case 1:
          return -9. / 16. * (1. / 9. - xi * xi) * (xi + 1.);
        case 2:
          return 27. / 16. * (1. - xi * xi) * (1. / 3. - xi);
        case 3:
          return 27. / 16. * (1. - xi * xi) * (1. / 3. + xi);
        default:
          mooseError("Invalid shape function index i = ", i);
      }
    }
    default:
      mooseError("Unsupported order");
  }
}
Referenced by AutomaticMortarGeneration::buildMortarSegmentMesh(), fe_lagrange_2D_shape(), fe_lagrange_2D_shape_deriv(), AutomaticMortarGeneration::getNormals(), AutomaticMortarGeneration::projectPrimaryNodesSinglePair(), and AutomaticMortarGeneration::projectSecondaryNodesSinglePair().
fe_lagrange_1D_shape_deriv()
template<typename T > T Moose::fe_lagrange_1D_shape_deriv (const Order order, const unsigned int i, const T & xi)
Definition at line 96 of file MooseLagrangeHelpers.h.
{
  switch (order)
  {
      // Lagrange linear shape function derivatives
    case FIRST:
    {
      libmesh_assert_less(i, 2);
      switch (i)
      {
        case 0:
          return -.5;
        case 1:
          return .5;
        default:
          mooseError("Invalid shape function index i = ", i);
      }
    }
      // Lagrange quadratic shape function derivatives
    case SECOND:
    {
      libmesh_assert_less(i, 3);
      switch (i)
      {
        case 0:
          return xi - .5;
        case 1:
          return xi + .5;
        case 2:
          return -2. * xi;
        default:
          mooseError("Invalid shape function index i = ", i);
      }
    }
      // Lagrange cubic shape function derivatives
    case THIRD:
    {
      libmesh_assert_less(i, 4);
      switch (i)
      {
        case 0:
          return -9. / 16. * (3. * xi * xi - 2. * xi - 1. / 9.);
        case 1:
          return -9. / 16. * (-3. * xi * xi - 2. * xi + 1. / 9.);
        case 2:
          return 27. / 16. * (3. * xi * xi - 2. / 3. * xi - 1.);
        case 3:
          return 27. / 16. * (-3. * xi * xi - 2. / 3. * xi + 1.);
        default:
          mooseError("Invalid shape function index i = ", i);
      }
    }
    default:
      mooseError("Unsupported order");
  }
}
Referenced by fe_lagrange_2D_shape_deriv().
fe_lagrange_2D_shape()
template<typename T , template< typename > class VectorType> T Moose::fe_lagrange_2D_shape (const ElemType type, const Order order, const unsigned int i, const VectorType< T > & p)
Definition at line 171 of file MooseLagrangeHelpers.h.
{
  switch (order)
  {
      // linear Lagrange shape functions
    case FIRST:
    {
      switch (type)
      {
        case QUAD4:
        case QUADSHELL4:
        case QUAD8:
        case QUADSHELL8:
        case QUAD9:
        {
          // Compute quad shape functions as a tensor-product
          const T xi = p(0);
          const T eta = p(1);
          libmesh_assert_less(i, 4);
          //                                0  1  2  3
          static const unsigned int i0[] = {0, 1, 1, 0};
          static const unsigned int i1[] = {0, 0, 1, 1};
          return (fe_lagrange_1D_shape(FIRST, i0[i], xi) * fe_lagrange_1D_shape(FIRST, i1[i], eta));
        }
        case TRI3:
        case TRISHELL3:
        case TRI6:
        case TRI7:
        {
          const T zeta1 = p(0);
          const T zeta2 = p(1);
          const T zeta0 = 1. - zeta1 - zeta2;
          libmesh_assert_less(i, 3);
          switch (i)
          {
            case 0:
              return zeta0;
            case 1:
              return zeta1;
            case 2:
              return zeta2;
            default:
              mooseError("Invalid shape function index i = ", i);
          }
        }
        default:
          mooseError("Unsupported element type:", type);
      }
    }
      // quadratic Lagrange shape functions
    case SECOND:
    {
      switch (type)
      {
        case QUAD8:
        {
          // Compute quad shape functions as a tensor-product
          const T xi = p(0);
          const T eta = p(1);
          libmesh_assert_less(i, 8);
          switch (i)
          {
            case 0:
              return .25 * (1. - xi) * (1. - eta) * (-1. - xi - eta);
            case 1:
              return .25 * (1. + xi) * (1. - eta) * (-1. + xi - eta);
            case 2:
              return .25 * (1. + xi) * (eta + 1.) * (-1. + xi + eta);
            case 3:
              return .25 * (1. - xi) * (eta + 1.) * (-1. - xi + eta);
            case 4:
              return .5 * (1. - xi * xi) * (1. - eta);
            case 5:
              return .5 * (1. + xi) * (1. - eta * eta);
            case 6:
              return .5 * (1. - xi * xi) * (1. + eta);
            case 7:
              return .5 * (1. - xi) * (1. - eta * eta);
            default:
              mooseError("Invalid shape function index i = ", i);
          }
        }
        case QUAD9:
        {
          // Compute quad shape functions as a tensor-product
          const T xi = p(0);
          const T eta = p(1);
          libmesh_assert_less(i, 9);
          //                                0  1  2  3  4  5  6  7  8
          static const unsigned int i0[] = {0, 1, 1, 0, 2, 1, 2, 0, 2};
          static const unsigned int i1[] = {0, 0, 1, 1, 0, 2, 1, 2, 2};
          return (fe_lagrange_1D_shape(SECOND, i0[i], xi) *
                  fe_lagrange_1D_shape(SECOND, i1[i], eta));
        }
        case TRI6:
        case TRI7:
        {
          const T zeta1 = p(0);
          const T zeta2 = p(1);
          const T zeta0 = 1. - zeta1 - zeta2;
          libmesh_assert_less(i, 6);
          switch (i)
          {
            case 0:
              return 2. * zeta0 * (zeta0 - 0.5);
            case 1:
              return 2. * zeta1 * (zeta1 - 0.5);
            case 2:
              return 2. * zeta2 * (zeta2 - 0.5);
            case 3:
              return 4. * zeta0 * zeta1;
            case 4:
              return 4. * zeta1 * zeta2;
            case 5:
              return 4. * zeta2 * zeta0;
            default:
              mooseError("Invalid shape function index i = ", i);
          }
        }
        default:
          mooseError("Unsupported 2D element type");
      }
    }
      // "cubic" (one cubic bubble) Lagrange shape functions
    case THIRD:
    {
      switch (type)
      {
        case TRI7:
        {
          const T zeta1 = p(0);
          const T zeta2 = p(1);
          const T zeta0 = 1. - zeta1 - zeta2;
          const T bubble_27th = zeta0 * zeta1 * zeta2;
          libmesh_assert_less(i, 7);
          switch (i)
          {
            case 0:
              return 2. * zeta0 * (zeta0 - 0.5) + 3. * bubble_27th;
            case 1:
              return 2. * zeta1 * (zeta1 - 0.5) + 3. * bubble_27th;
            case 2:
              return 2. * zeta2 * (zeta2 - 0.5) + 3. * bubble_27th;
            case 3:
              return 4. * zeta0 * zeta1 - 12. * bubble_27th;
            case 4:
              return 4. * zeta1 * zeta2 - 12. * bubble_27th;
            case 5:
              return 4. * zeta2 * zeta0 - 12. * bubble_27th;
            case 6:
              return 27. * bubble_27th;
            default:
              mooseError("Invalid shape function index i = ", i);
          }
        }
        default:
          mooseError("Unsupported 2D element type");
      }
    }
      // unsupported order
    default:
      mooseError("Unsupported order");
  }
}
Referenced by AutomaticMortarGeneration::getNormals(), and Moose::Mortar::projectQPoints3d().
fe_lagrange_2D_shape_deriv()
template<typename T , template< typename > class VectorType> T Moose::fe_lagrange_2D_shape_deriv (const ElemType type, const Order order, const unsigned int i, const unsigned int j, const VectorType< T > & p)
Definition at line 378 of file MooseLagrangeHelpers.h.
{
  libmesh_assert_less(j, 2);
  switch (order)
  {
      // linear Lagrange shape functions
    case FIRST:
    {
      switch (type)
      {
        case QUAD4:
        case QUADSHELL4:
        case QUAD8:
        case QUADSHELL8:
        case QUAD9:
        {
          // Compute quad shape functions as a tensor-product
          const T xi = p(0);
          const T eta = p(1);
          libmesh_assert_less(i, 4);
          //                                0  1  2  3
          static const unsigned int i0[] = {0, 1, 1, 0};
          static const unsigned int i1[] = {0, 0, 1, 1};
          switch (j)
          {
              // d()/dxi
            case 0:
              return (fe_lagrange_1D_shape_deriv(FIRST, i0[i], xi) *
                      fe_lagrange_1D_shape(FIRST, i1[i], eta));
              // d()/deta
            case 1:
              return (fe_lagrange_1D_shape(FIRST, i0[i], xi) *
                      fe_lagrange_1D_shape_deriv(FIRST, i1[i], eta));
            default:
              mooseError("Invalid derivative index j = ", j);
          }
        }
        case TRI3:
        case TRISHELL3:
        case TRI6:
        case TRI7:
        {
          libmesh_assert_less(i, 3);
          const T dzeta0dxi = -1.;
          const T dzeta1dxi = 1.;
          const T dzeta2dxi = 0.;
          const T dzeta0deta = -1.;
          const T dzeta1deta = 0.;
          const T dzeta2deta = 1.;
          switch (j)
          {
              // d()/dxi
            case 0:
            {
              switch (i)
              {
                case 0:
                  return dzeta0dxi;
                case 1:
                  return dzeta1dxi;
                case 2:
                  return dzeta2dxi;
                default:
                  mooseError("Invalid shape function index i = ", i);
              }
            }
              // d()/deta
            case 1:
            {
              switch (i)
              {
                case 0:
                  return dzeta0deta;
                case 1:
                  return dzeta1deta;
                case 2:
                  return dzeta2deta;
                default:
                  mooseError("Invalid shape function index i = ", i);
              }
            }
            default:
              mooseError("Invalid derivative index j = ", j);
          }
        }
        default:
          mooseError("Unsupported 2D element type");
      }
    }
      // quadratic Lagrange shape functions
    case SECOND:
    {
      switch (type)
      {
        case QUAD8:
        case QUADSHELL8:
        {
          const T xi = p(0);
          const T eta = p(1);
          libmesh_assert_less(i, 8);
          switch (j)
          {
              // d/dxi
            case 0:
              switch (i)
              {
                case 0:
                  return .25 * (1. - eta) * ((1. - xi) * (-1.) + (-1.) * (-1. - xi - eta));
                case 1:
                  return .25 * (1. - eta) * ((1. + xi) * (1.) + (1.) * (-1. + xi - eta));
                case 2:
                  return .25 * (1. + eta) * ((1. + xi) * (1.) + (1.) * (-1. + xi + eta));
                case 3:
                  return .25 * (1. + eta) * ((1. - xi) * (-1.) + (-1.) * (-1. - xi + eta));
                case 4:
                  return .5 * (-2. * xi) * (1. - eta);
                case 5:
                  return .5 * (1.) * (1. - eta * eta);
                case 6:
                  return .5 * (-2. * xi) * (1. + eta);
                case 7:
                  return .5 * (-1.) * (1. - eta * eta);
                default:
                  mooseError("Invalid shape function index i = ", i);
              }
              // d/deta
            case 1:
              switch (i)
              {
                case 0:
                  return .25 * (1. - xi) * ((1. - eta) * (-1.) + (-1.) * (-1. - xi - eta));
                case 1:
                  return .25 * (1. + xi) * ((1. - eta) * (-1.) + (-1.) * (-1. + xi - eta));
                case 2:
                  return .25 * (1. + xi) * ((1. + eta) * (1.) + (1.) * (-1. + xi + eta));
                case 3:
                  return .25 * (1. - xi) * ((1. + eta) * (1.) + (1.) * (-1. - xi + eta));
                case 4:
                  return .5 * (1. - xi * xi) * (-1.);
                case 5:
                  return .5 * (1. + xi) * (-2. * eta);
                case 6:
                  return .5 * (1. - xi * xi) * (1.);
                case 7:
                  return .5 * (1. - xi) * (-2. * eta);
                default:
                  mooseError("Invalid shape function index i = ", i);
              }
            default:
              mooseError("ERROR: Invalid derivative index j = ", j);
          }
        }
        case QUAD9:
        {
          // Compute quad shape functions as a tensor-product
          const T xi = p(0);
          const T eta = p(1);
          libmesh_assert_less(i, 9);
          //                                0  1  2  3  4  5  6  7  8
          static const unsigned int i0[] = {0, 1, 1, 0, 2, 1, 2, 0, 2};
          static const unsigned int i1[] = {0, 0, 1, 1, 0, 2, 1, 2, 2};
          switch (j)
          {
              // d()/dxi
            case 0:
              return (fe_lagrange_1D_shape_deriv(SECOND, i0[i], xi) *
                      fe_lagrange_1D_shape(SECOND, i1[i], eta));
              // d()/deta
            case 1:
              return (fe_lagrange_1D_shape(SECOND, i0[i], xi) *
                      fe_lagrange_1D_shape_deriv(SECOND, i1[i], eta));
            default:
              mooseError("Invalid derivative index j = ", j);
          }
        }
        case TRI6:
        case TRI7:
        {
          libmesh_assert_less(i, 6);
          const T zeta1 = p(0);
          const T zeta2 = p(1);
          const T zeta0 = 1. - zeta1 - zeta2;
          const T dzeta0dxi = -1.;
          const T dzeta1dxi = 1.;
          const T dzeta2dxi = 0.;
          const T dzeta0deta = -1.;
          const T dzeta1deta = 0.;
          const T dzeta2deta = 1.;
          switch (j)
          {
            case 0:
            {
              switch (i)
              {
                case 0:
                  return (4. * zeta0 - 1.) * dzeta0dxi;
                case 1:
                  return (4. * zeta1 - 1.) * dzeta1dxi;
                case 2:
                  return (4. * zeta2 - 1.) * dzeta2dxi;
                case 3:
                  return 4. * zeta1 * dzeta0dxi + 4. * zeta0 * dzeta1dxi;
                case 4:
                  return 4. * zeta2 * dzeta1dxi + 4. * zeta1 * dzeta2dxi;
                case 5:
                  return 4. * zeta2 * dzeta0dxi + 4 * zeta0 * dzeta2dxi;
                default:
                  mooseError("Invalid shape function index i = ", i);
              }
            }
            case 1:
            {
              switch (i)
              {
                case 0:
                  return (4. * zeta0 - 1.) * dzeta0deta;
                case 1:
                  return (4. * zeta1 - 1.) * dzeta1deta;
                case 2:
                  return (4. * zeta2 - 1.) * dzeta2deta;
                case 3:
                  return 4. * zeta1 * dzeta0deta + 4. * zeta0 * dzeta1deta;
                case 4:
                  return 4. * zeta2 * dzeta1deta + 4. * zeta1 * dzeta2deta;
                case 5:
                  return 4. * zeta2 * dzeta0deta + 4 * zeta0 * dzeta2deta;
                default:
                  mooseError("Invalid shape function index i = ", i);
              }
            }
            default:
              mooseError("ERROR: Invalid derivative index j = ", j);
          }
        }
        default:
          mooseError("ERROR: Unsupported 2D element type");
      }
    }
      // "cubic" (one cubic bubble) Lagrange shape functions
    case THIRD:
    {
      switch (type)
      {
        case TRI7:
        {
          libmesh_assert_less(i, 7);
          const T zeta1 = p(0);
          const T zeta2 = p(1);
          const T zeta0 = 1. - zeta1 - zeta2;
          const T dzeta0dxi = -1.;
          const T dzeta1dxi = 1.;
          const T dzeta2dxi = 0.;
          const T dbubbledxi = zeta2 * (1. - 2. * zeta1 - zeta2);
          const T dzeta0deta = -1.;
          const T dzeta1deta = 0.;
          const T dzeta2deta = 1.;
          const T dbubbledeta = zeta1 * (1. - zeta1 - 2. * zeta2);
          switch (j)
          {
            case 0:
            {
              switch (i)
              {
                case 0:
                  return (4. * zeta0 - 1.) * dzeta0dxi + 3. * dbubbledxi;
                case 1:
                  return (4. * zeta1 - 1.) * dzeta1dxi + 3. * dbubbledxi;
                case 2:
                  return (4. * zeta2 - 1.) * dzeta2dxi + 3. * dbubbledxi;
                case 3:
                  return 4. * zeta1 * dzeta0dxi + 4. * zeta0 * dzeta1dxi - 12. * dbubbledxi;
                case 4:
                  return 4. * zeta2 * dzeta1dxi + 4. * zeta1 * dzeta2dxi - 12. * dbubbledxi;
                case 5:
                  return 4. * zeta2 * dzeta0dxi + 4 * zeta0 * dzeta2dxi - 12. * dbubbledxi;
                case 6:
                  return 27. * dbubbledxi;
                default:
                  mooseError("Invalid shape function index i = ", i);
              }
            }
            case 1:
            {
              switch (i)
              {
                case 0:
                  return (4. * zeta0 - 1.) * dzeta0deta + 3. * dbubbledeta;
                case 1:
                  return (4. * zeta1 - 1.) * dzeta1deta + 3. * dbubbledeta;
                case 2:
                  return (4. * zeta2 - 1.) * dzeta2deta + 3. * dbubbledeta;
                case 3:
                  return 4. * zeta1 * dzeta0deta + 4. * zeta0 * dzeta1deta - 12. * dbubbledeta;
                case 4:
                  return 4. * zeta2 * dzeta1deta + 4. * zeta1 * dzeta2deta - 12. * dbubbledeta;
                case 5:
                  return 4. * zeta2 * dzeta0deta + 4 * zeta0 * dzeta2deta - 12. * dbubbledeta;
                case 6:
                  return 27. * dbubbledeta;
                default:
                  mooseError("Invalid shape function index i = ", i);
              }
            }
            default:
              mooseError("ERROR: Invalid derivative index j = ", j);
          }
        }
        default:
          mooseError("ERROR: Unsupported 2D element type");
      }
    }
      // unsupported order
    default:
      mooseError("Unsupported order");
  }
}
findContactPoint()
void Moose::findContactPoint (PenetrationInfo & p_info, FEBase * fe_elem, FEBase * fe_side, FEType & fe_side_type, const Point & secondary_point, bool start_with_centroid, const Real tangential_tolerance, bool & contact_point_on_side)
Finds the closest point (called the contact point) on the primary_elem on side "side" to the secondary_point.
Parameters
p_info The penetration info object, contains primary_elem, side, various other information
fe_elem FE object for the element
fe_side FE object for the side
fe_side_type The type of fe_side, needed for inverse_map routines
start_with_centroid if true, start inverse mapping procedure from element centroid
tangential_tolerance 'tangential' tolerance for determining whether a contact point on a side
secondary_point The physical space coordinates of the secondary node
contact_point_on_side whether or not the contact_point actually lies on that side of the element.
Definition at line 45 of file FindContactPoint.C.
{
  const Elem * primary_elem = p_info._elem;
  unsigned int dim = primary_elem->dim();
  const Elem * side = p_info._side;
  const std::vector<Point> & phys_point = fe_side->get_xyz();
  const std::vector<RealGradient> & dxyz_dxi = fe_side->get_dxyzdxi();
  const std::vector<RealGradient> & d2xyz_dxi2 = fe_side->get_d2xyzdxi2();
  const std::vector<RealGradient> & d2xyz_dxieta = fe_side->get_d2xyzdxideta();
  const std::vector<RealGradient> & dxyz_deta = fe_side->get_dxyzdeta();
  const std::vector<RealGradient> & d2xyz_deta2 = fe_side->get_d2xyzdeta2();
  const std::vector<RealGradient> & d2xyz_detaxi = fe_side->get_d2xyzdxideta();
  if (dim == 1)
  {
    const Node * nearest_node = side->node_ptr(0);
    p_info._closest_point = *nearest_node;
    p_info._closest_point_ref =
        primary_elem->master_point(primary_elem->get_node_index(nearest_node));
    std::vector<Point> elem_points = {p_info._closest_point_ref};
    const std::vector<RealGradient> & elem_dxyz_dxi = fe_elem->get_dxyzdxi();
    fe_elem->reinit(primary_elem, &elem_points);
    p_info._normal = elem_dxyz_dxi[0];
    if (nearest_node->id() == primary_elem->node_id(0))
      p_info._normal *= -1.0;
    p_info._normal /= p_info._normal.norm();
    Point from_secondary_to_closest = p_info._closest_point - secondary_point;
    p_info._distance = from_secondary_to_closest * p_info._normal;
    Point tangential = from_secondary_to_closest - p_info._distance * p_info._normal;
    p_info._tangential_distance = tangential.norm();
    p_info._dxyzdxi = dxyz_dxi;
    p_info._dxyzdeta = dxyz_deta;
    p_info._d2xyzdxideta = d2xyz_dxieta;
    p_info._side_phi = fe_side->get_phi();
    p_info._side_grad_phi = fe_side->get_dphi();
    contact_point_on_side = true;
    return;
  }
  Point ref_point;
  if (start_with_centroid)
    ref_point = FEInterface::inverse_map(
        dim - 1, fe_side_type, side, side->vertex_average(), TOLERANCE, false);
  else
    ref_point = p_info._closest_point_ref;
  std::vector<Point> points = {ref_point};
  fe_side->reinit(side, &points);
  RealGradient d = secondary_point - phys_point[0];
  Real update_size = std::numeric_limits<Real>::max();
  // Least squares
  for (unsigned int it = 0; it < 3 && update_size > TOLERANCE * 1e3; ++it)
  {
    DenseMatrix<Real> jac(dim - 1, dim - 1);
    jac(0, 0) = -(dxyz_dxi[0] * dxyz_dxi[0]);
    if (dim - 1 == 2)
    {
      jac(1, 0) = -(dxyz_dxi[0] * dxyz_deta[0]);
      jac(0, 1) = -(dxyz_deta[0] * dxyz_dxi[0]);
      jac(1, 1) = -(dxyz_deta[0] * dxyz_deta[0]);
    }
    DenseVector<Real> rhs(dim - 1);
    rhs(0) = dxyz_dxi[0] * d;
    if (dim - 1 == 2)
      rhs(1) = dxyz_deta[0] * d;
    DenseVector<Real> update(dim - 1);
    jac.lu_solve(rhs, update);
    ref_point(0) -= update(0);
    if (dim - 1 == 2)
      ref_point(1) -= update(1);
    points[0] = ref_point;
    fe_side->reinit(side, &points);
    d = secondary_point - phys_point[0];
    update_size = update.l2_norm();
  }
  update_size = std::numeric_limits<Real>::max();
  unsigned nit = 0;
  // Newton Loop
  for (; nit < 12 && update_size > TOLERANCE * TOLERANCE; nit++)
  {
    d = secondary_point - phys_point[0];
    DenseMatrix<Real> jac(dim - 1, dim - 1);
    jac(0, 0) = (d2xyz_dxi2[0] * d) - (dxyz_dxi[0] * dxyz_dxi[0]);
    if (dim - 1 == 2)
    {
      jac(1, 0) = (d2xyz_dxieta[0] * d) - (dxyz_dxi[0] * dxyz_deta[0]);
      jac(0, 1) = (d2xyz_detaxi[0] * d) - (dxyz_deta[0] * dxyz_dxi[0]);
      jac(1, 1) = (d2xyz_deta2[0] * d) - (dxyz_deta[0] * dxyz_deta[0]);
    }
    DenseVector<Real> rhs(dim - 1);
    rhs(0) = -dxyz_dxi[0] * d;
    if (dim - 1 == 2)
      rhs(1) = -dxyz_deta[0] * d;
    DenseVector<Real> update(dim - 1);
    jac.lu_solve(rhs, update);
    ref_point(0) += update(0);
    if (dim - 1 == 2)
      ref_point(1) += update(1);
    points[0] = ref_point;
    fe_side->reinit(side, &points);
    d = secondary_point - phys_point[0];
    update_size = update.l2_norm();
  }
  /*
    if (nit == 12 && update_size > TOLERANCE*TOLERANCE)
      Moose::err<<"Warning!  Newton solve for contact point failed to converge!"<<std::endl;
  */
  p_info._closest_point_ref = ref_point;
  p_info._closest_point = phys_point[0];
  p_info._distance = d.norm();
  if (dim - 1 == 2)
  {
    p_info._normal = dxyz_dxi[0].cross(dxyz_deta[0]);
    p_info._normal /= p_info._normal.norm();
  }
  else
  {
    const Node * const * elem_nodes = primary_elem->get_nodes();
    const Point in_plane_vector1 = *elem_nodes[1] - *elem_nodes[0];
    const Point in_plane_vector2 = *elem_nodes[2] - *elem_nodes[0];
    Point out_of_plane_normal = in_plane_vector1.cross(in_plane_vector2);
    out_of_plane_normal /= out_of_plane_normal.norm();
    p_info._normal = dxyz_dxi[0].cross(out_of_plane_normal);
    if (std::fabs(p_info._normal.norm()) > 1e-15)
      p_info._normal /= p_info._normal.norm();
  }
  // If the point has not penetrated the face, make the distance negative
  const Real dot(d * p_info._normal);
  if (dot > 0.0)
    p_info._distance = -p_info._distance;
  contact_point_on_side = FEInterface::on_reference_element(ref_point, side->type());
  p_info._tangential_distance = 0.0;
  if (!contact_point_on_side)
  {
    p_info._closest_point_on_face_ref = ref_point;
    restrictPointToFace(p_info._closest_point_on_face_ref, side, p_info._off_edge_nodes);
    points[0] = p_info._closest_point_on_face_ref;
    fe_side->reinit(side, &points);
    Point closest_point_on_face(phys_point[0]);
    RealGradient off_face = closest_point_on_face - p_info._closest_point;
    Real tangential_distance = off_face.norm();
    p_info._tangential_distance = tangential_distance;
    if (tangential_distance <= tangential_tolerance)
    {
      contact_point_on_side = true;
    }
  }
  const std::vector<std::vector<Real>> & phi = fe_side->get_phi();
  const std::vector<std::vector<RealGradient>> & grad_phi = fe_side->get_dphi();
  points[0] = p_info._closest_point_ref;
  fe_side->reinit(side, &points);
  p_info._side_phi = phi;
  p_info._side_grad_phi = grad_phi;
  p_info._dxyzdxi = dxyz_dxi;
  p_info._dxyzdeta = dxyz_deta;
  p_info._d2xyzdxideta = d2xyz_dxieta;
}
Referenced by PenetrationThread::createInfoForElem(), and PenetrationThread::operator()().
findElementsIntersectedByPlane()
void Moose::findElementsIntersectedByPlane (const Plane & plane, const MeshBase & mesh, std::vector< const Elem * > & intersected_elems)
Definition at line 24 of file ElementsIntersectedByPlane.C.
{
  // Loop over all elements to find elements intersected by the plane
  for (const auto & elem : mesh.element_ptr_range())
  {
    bool intersected = false;
    // Check whether the first node of this element is below or above the plane
    const Node & node0 = elem->node_ref(0);
    bool node0_above_plane = plane.above_surface(node0);
    // Loop over the rest of the nodes and check if any node is on the other side of the plane
    for (unsigned int i = 1; i < elem->n_nodes(); ++i)
    {
      const Node & node = elem->node_ref(i);
      bool node_above_plane = plane.above_surface(node);
      if (node0_above_plane != node_above_plane)
        intersected = true;
    }
    if (intersected)
      intersected_elems.push_back(elem);
  }
}
Referenced by elementsIntersectedByPlane().
getExec()
std::string Moose::getExec ()
Definition at line 24 of file ExecutablePath.C.
{
  std::string exec_path;
  char path[1024];
#if defined(__APPLE__)
  uint32_t size = sizeof(path);
  if (_NSGetExecutablePath(path, &size) == 0)
    exec_path = path;
  else
    mooseError("Unable to retrieve executable path");
#elif defined(__WIN32__)
  return "./";
#else // Linux with Proc
  std::ostringstream oss;
  oss << "/proc/" << getpid() << "/exe";
  int ch = readlink(oss.str().c_str(), path, 1024);
  if (ch != -1)
  {
    path[ch] = 0;
    exec_path = path;
  }
#endif
  return exec_path;
}
Referenced by getExecutableName(), and getExecutablePath().
getExecutableName()
std::string Moose::getExecutableName ()
This function returns the name of the running executable.
There is not a portable way to do this function implements this function for Mac OS X and Linux boxes containing a normal /proc tree
Definition at line 60 of file ExecutablePath.C.
{
  auto name = getExec();
  // strip off the path to get the name
  std::string::size_type start = name.find_last_of("/");
  if (start == std::string::npos)
    start = 0;
  return name.substr(start, std::string::npos);
}
Referenced by MooseApp::appBinaryName(), MooseApp::copyInputs(), and MooseApp::runInputs().
getExecutablePath()
std::string Moose::getExecutablePath ()
This function returns the PATH of the running executable.
There is not a portable way to do this function implements this function for Mac OS X and Linux boxes containing a normal /proc tree
Definition at line 51 of file ExecutablePath.C.
{
  auto exec_path = getExec();
  // strip off the exeuctable to get the PATH
  std::string::size_type t = exec_path.find_last_of("/");
  return exec_path.substr(0, t) + "/";
}
Referenced by MooseUtils::docsDir(), DataFileInterface< Action >::getDataFileNameByName(), SystemInfo::getExecutable(), MooseUtils::installedInputsDir(), ADFParser::JITCompile(), and MooseUtils::runTestsExecutable().
globalADIndexing()
bool Moose::globalADIndexing () inline
Whether we are using global AD indexing.
Definition at line 29 of file ADUtils.h.
{
  return true;
}
Referenced by FEProblemBase::init().
globalDofIndexToDerivative() [1/2]
std::unordered_map< dof_id_type, Real > Moose::globalDofIndexToDerivative (const ADReal & ad_real, const SystemBase & sys, const ElementType elem_type, const THREAD_ID tid)
Generate a map from global dof index to derivative value.
Definition at line 23 of file ADUtils.C.
{
  mooseAssert(dynamic_cast<const NonlinearSystemBase *>(&sys),
              "This must be a nonlinear system base object");
  const Assembly & assembly = sys.subproblem().assembly(tid, sys.number());
  const Elem * elem;
  switch (elem_type)
  {
    case ElementType::Element:
      elem = assembly.elem();
      break;
    case ElementType::Neighbor:
      elem = assembly.neighbor();
      break;
    case ElementType::Lower:
      elem = assembly.lowerDElem();
      break;
    default:
      mooseError("Unrecognized element type");
  }
  std::unordered_map<dof_id_type, Real> ret_val;
  const System & libmesh_sys = sys.system();
  const DofMap & dof_map = libmesh_sys.get_dof_map();
  const unsigned int num_vars = libmesh_sys.n_vars();
  const auto max_dofs_per_elem = sys.getMaxVarNDofsPerElem();
  for (unsigned int var_num = 0; var_num < num_vars; ++var_num)
  {
    std::vector<dof_id_type> global_indices;
    // Get the global indices corresponding to var_num that exist on elem
    dof_map.dof_indices(elem, global_indices, var_num);
    // determine the AD offset for the current var
    const auto ad_offset = adOffset(var_num, max_dofs_per_elem, elem_type, num_vars);
    // Map from global index to derivative
    for (MooseIndex(global_indices) local_index = 0; local_index < global_indices.size();
         ++local_index)
      ret_val[global_indices[local_index]] = ad_real.derivatives()[ad_offset + local_index];
  }
  return ret_val;
}
Referenced by globalDofIndexToDerivative().
globalDofIndexToDerivative() [2/2]
template<typename T > auto Moose::globalDofIndexToDerivative (const T & ad_real_container, const SystemBase & sys, ElementType elem_type = ElementType::Element, THREAD_ID tid = 0) -> std::vector<std::unordered_map< dof_id_type, typename std::enable_if<std::is_same<ADReal, typename T::value_type>::value, Real>::type>>
Generate a map from global dof index to derivative value for a (probably quadrature-point-based) container like a material property or a variable value.
Definition at line 136 of file ADUtils.h.
{
  std::vector<std::unordered_map<dof_id_type, Real>> ret_val(ad_real_container.size());
  for (MooseIndex(ad_real_container) i = 0; i < ad_real_container.size(); ++i)
    ret_val[i] = globalDofIndexToDerivative(ad_real_container[i], sys, elem_type, tid);
  return ret_val;
}
hash_combine() [1/4]
void Moose::hash_combine (std::size_t &) inline
Used for hash function specialization for Attribute objects.
Definition at line 22 of file MooseHashing.h.
{
}
Referenced by hash_combine(), std::hash< Attribute >::operator()(), PointIndexedMap::hash_point::operator()(), moose::internal::SoltionInvalidityNameHash::operator()(), std::hash< std::pair< S, T > >::operator()(), and std::hash< std::vector< std::unique_ptr< Attribute > > >::operator()().
hash_combine() [2/4]
template<typename T , typename... Rest> void Moose::hash_combine (std::size_t & seed, const std::set< T > & v, Rest &&... rest) inline
Used for hash function specialization for Attribute objects.
Definition at line 50 of file MooseHashing.h.
{
  for (auto & val : v)
    hash_combine(seed, val);
  hash_combine(seed, std::forward<Rest>(rest)...);
}
hash_combine() [3/4]
template<typename T , typename... Rest> void Moose::hash_combine (std::size_t & seed, const std::vector< T > & v, Rest &&... rest) inline
Used for hash function specialization for Attribute objects.
Definition at line 40 of file MooseHashing.h.
{
  for (auto & val : v)
    hash_combine(seed, val);
  hash_combine(seed, std::forward<Rest>(rest)...);
}
hash_combine() [4/4]
template<typename T , typename... Rest> void Moose::hash_combine (std::size_t & seed, const T & v, Rest &&... rest) inline
Used to combine an existing hash value with the hash of one or more other values (v and rest).
For example "auto h = std::hash("hello"); hash_combine(h, my_int_val, my_float_val, etc.);"
Definition at line 30 of file MooseHashing.h.
{
  std::hash<T> hasher;
  seed ^= hasher(v) + 0x9e3779b9 + (seed << 6) + (seed >> 2);
  hash_combine(seed, std::forward<Rest>(rest)...);
}
indirectSort() [1/2]
template<class RandomAccessIterator > void Moose::indirectSort (RandomAccessIterator beg, RandomAccessIterator end, std::vector< size_t > & b)
Definition at line 68 of file IndirectSort.h.
{
  // Space in b
  initialize_indirect_sort(beg, end, b);
  // Typedef for less typing.  Note: use of std::iterator_traits means this should work with
  // naked pointers too...
  typedef std::less<typename std::iterator_traits<RandomAccessIterator>::value_type>
      LessThanComparator;
  // Construct comparator object
  indirect_comparator<RandomAccessIterator, LessThanComparator> ic(beg, LessThanComparator());
  // Sort the indices, based on the data
  std::sort(b.begin(), b.end(), ic);
}
Referenced by SamplerBase::finalize().
indirectSort() [2/2]
template<class RandomAccessIterator , class UserComparisonFunctor > void Moose::indirectSort (RandomAccessIterator beg, RandomAccessIterator end, std::vector< size_t > & b, UserComparisonFunctor user_comp)
Definition at line 89 of file IndirectSort.h.
{
  // Space in b
  initialize_indirect_sort(beg, end, b);
  // Construct comparator object
  indirect_comparator<RandomAccessIterator, UserComparisonFunctor> ic(beg, user_comp);
  // Sort the indices, based on the data
  std::sort(b.begin(), b.end(), ic);
}
initCoordinateSystemType()
void Moose::initCoordinateSystemType ()
Definition at line 35 of file Conversion.C.
{
  if (coordinate_system_type_to_enum.empty())
  {
    coordinate_system_type_to_enum["XYZ"] = COORD_XYZ;
    coordinate_system_type_to_enum["RZ"] = COORD_RZ;
    coordinate_system_type_to_enum["RSPHERICAL"] = COORD_RSPHERICAL;
  }
}
Referenced by stringToEnum< CoordinateSystemType >().
initDofIndices()
template<typename T > void Moose::initDofIndices (T & data, const Elem & elem)
Definition at line 48 of file MooseVariableDataFV.h.
{
  if (data._prev_elem != &elem)
  {
    data._dof_map.dof_indices(&elem, data._dof_indices, data._var_num);
    data._prev_elem = &elem;
  }
}
Referenced by MooseVariableFV< OutputType >::getValue(), and MooseVariableDataFV< OutputType >::initDofIndices().
initEigenProlemType()
void Moose::initEigenProlemType ()
Definition at line 76 of file Conversion.C.
{
  if (eigen_problem_type_to_enum.empty())
  {
    eigen_problem_type_to_enum["HERMITIAN"] = EPT_HERMITIAN;
    eigen_problem_type_to_enum["NON_HERMITIAN"] = EPT_NON_HERMITIAN;
    eigen_problem_type_to_enum["GEN_HERMITIAN"] = EPT_GEN_HERMITIAN;
    eigen_problem_type_to_enum["GEN_NON_HERMITIAN"] = EPT_GEN_NON_HERMITIAN;
    eigen_problem_type_to_enum["GEN_INDEFINITE"] = EPT_GEN_INDEFINITE;
    eigen_problem_type_to_enum["POS_GEN_NON_HERMITIAN"] = EPT_POS_GEN_NON_HERMITIAN;
    eigen_problem_type_to_enum["SLEPC_DEFAULT"] = EPT_SLEPC_DEFAULT;
  }
}
Referenced by stringToEnum< EigenProblemType >().
initEigenSolveType()
void Moose::initEigenSolveType ()
Definition at line 59 of file Conversion.C.
{
  if (eigen_solve_type_to_enum.empty())
  {
    eigen_solve_type_to_enum["POWER"] = EST_POWER;
    eigen_solve_type_to_enum["ARNOLDI"] = EST_ARNOLDI;
    eigen_solve_type_to_enum["KRYLOVSCHUR"] = EST_KRYLOVSCHUR;
    eigen_solve_type_to_enum["JACOBI_DAVIDSON"] = EST_JACOBI_DAVIDSON;
    eigen_solve_type_to_enum["NONLINEAR_POWER"] = EST_NONLINEAR_POWER;
    eigen_solve_type_to_enum["NEWTON"] = EST_NEWTON;
    eigen_solve_type_to_enum["PJFNK"] = EST_PJFNK;
    eigen_solve_type_to_enum["PJFNKMO"] = EST_PJFNKMO;
    eigen_solve_type_to_enum["JFNK"] = EST_JFNK;
  }
}
Referenced by stringToEnum< EigenSolveType >().
initial_condition()
void Moose::initial_condition (EquationSystems & es, const std::string & system_name)
initialize_indirect_sort()
template<class RandomAccessIterator > void Moose::initialize_indirect_sort (RandomAccessIterator beg, RandomAccessIterator end, std::vector< size_t > & b)
Definition at line 52 of file IndirectSort.h.
{
  // enough storage for all the indices
  b.resize(std::distance(beg, end));
  // iota
  for (size_t i = 0; i < b.size(); ++i)
    b[i] = i;
}
Referenced by indirectSort().
initLineSearchType()
void Moose::initLineSearchType ()
Definition at line 110 of file Conversion.C.
{
  if (line_search_type_to_enum.empty())
  {
    line_search_type_to_enum["DEFAULT"] = LS_DEFAULT;
    line_search_type_to_enum["NONE"] = LS_NONE;
    line_search_type_to_enum["BASIC"] = LS_BASIC;
    line_search_type_to_enum["SHELL"] = LS_SHELL;
    line_search_type_to_enum["L2"] = LS_L2;
    line_search_type_to_enum["BT"] = LS_BT;
    line_search_type_to_enum["CP"] = LS_CP;
    line_search_type_to_enum["CONTACT"] = LS_CONTACT;
    line_search_type_to_enum["PROJECT"] = LS_PROJECT;
  }
}
Referenced by stringToEnum< LineSearchType >().
initMffdType()
void Moose::initMffdType ()
Definition at line 143 of file Conversion.C.
{
  if (mffd_type_to_enum.empty())
  {
    mffd_type_to_enum["DS"] = MFFD_DS;
    mffd_type_to_enum["WP"] = MFFD_WP;
  }
}
Referenced by stringToEnum< MffdType >().
initRMType()
void Moose::initRMType ()
Definition at line 153 of file Conversion.C.
{
  if (rm_type_to_enum.empty())
  {
    rm_type_to_enum["DEFAULT"] = RelationshipManagerType::DEFAULT;
    rm_type_to_enum["GEOMETRIC"] = RelationshipManagerType::GEOMETRIC;
    rm_type_to_enum["ALGEBRAIC"] = RelationshipManagerType::ALGEBRAIC;
    rm_type_to_enum["COUPLING"] = RelationshipManagerType::COUPLING;
  }
}
Referenced by stringToEnum< RelationshipManagerType >().
initSolveType()
void Moose::initSolveType ()
Definition at line 46 of file Conversion.C.
{
  if (solve_type_to_enum.empty())
  {
    solve_type_to_enum["PJFNK"] = ST_PJFNK;
    solve_type_to_enum["JFNK"] = ST_JFNK;
    solve_type_to_enum["NEWTON"] = ST_NEWTON;
    solve_type_to_enum["FD"] = ST_FD;
    solve_type_to_enum["LINEAR"] = ST_LINEAR;
  }
}
Referenced by stringToEnum< SolveType >().
initTimeIntegratorsType()
void Moose::initTimeIntegratorsType ()
Definition at line 128 of file Conversion.C.
{
  if (time_integrator_to_enum.empty())
  {
    time_integrator_to_enum["IMPLICIT_EULER"] = TI_IMPLICIT_EULER;
    time_integrator_to_enum["EXPLICIT_EULER"] = TI_EXPLICIT_EULER;
    time_integrator_to_enum["CRANK_NICOLSON"] = TI_CRANK_NICOLSON;
    time_integrator_to_enum["BDF2"] = TI_BDF2;
    time_integrator_to_enum["EXPLICIT_MIDPOINT"] = TI_EXPLICIT_MIDPOINT;
    time_integrator_to_enum["LSTABLE_DIRK2"] = TI_LSTABLE_DIRK2;
    time_integrator_to_enum["EXPLICIT_TVDRK2"] = TI_EXPLICIT_TVD_RK_2;
  }
}
Referenced by stringToEnum< TimeIntegratorType >().
initWhichEigenPairs()
void Moose::initWhichEigenPairs ()
Definition at line 91 of file Conversion.C.
{
  if (which_eigen_pairs_to_enum.empty())
  {
    which_eigen_pairs_to_enum["LARGEST_MAGNITUDE"] = WEP_LARGEST_MAGNITUDE;
    which_eigen_pairs_to_enum["SMALLEST_MAGNITUDE"] = WEP_SMALLEST_MAGNITUDE;
    which_eigen_pairs_to_enum["LARGEST_REAL"] = WEP_LARGEST_REAL;
    which_eigen_pairs_to_enum["SMALLEST_REAL"] = WEP_SMALLEST_REAL;
    which_eigen_pairs_to_enum["LARGEST_IMAGINARY"] = WEP_LARGEST_IMAGINARY;
    which_eigen_pairs_to_enum["SMALLEST_IMAGINARY"] = WEP_SMALLEST_IMAGINARY;
    which_eigen_pairs_to_enum["TARGET_MAGNITUDE"] = WEP_TARGET_MAGNITUDE;
    which_eigen_pairs_to_enum["TARGET_REAL"] = WEP_TARGET_REAL;
    which_eigen_pairs_to_enum["TARGET_IMAGINARY"] = WEP_TARGET_IMAGINARY;
    which_eigen_pairs_to_enum["ALL_EIGENVALUES"] = WEP_ALL_EIGENVALUES;
    which_eigen_pairs_to_enum["SLEPC_DEFAULT"] = WEP_SLEPC_DEFAULT;
  }
}
Referenced by stringToEnum< WhichEigenPairs >().
oldState()
StateArg Moose::oldState () inline
Definition at line 250 of file MooseFunctorArguments.h.
{
  return {(unsigned int)1};
}
Referenced by TransientInterface::determineState().
previousNonlinearState()
StateArg Moose::previousNonlinearState () inline
Definition at line 256 of file MooseFunctorArguments.h.
{
  return {(unsigned int)1, SolutionIterationType::Nonlinear};
}
recursivelyFindElementsIntersectedByLine()
void Moose::recursivelyFindElementsIntersectedByLine (const LineSegment & line_segment, const Elem * current_elem, int incoming_side, const Point & incoming_point, std::vector< Elem * > & intersected_elems, std::vector< LineSegment > & segments)
Recursively find all elements intersected by a line segment.
Works by moving from one element to the next through the side of the current element. This means that (other than for the first element) there is always an incoming_side that is the reason we ended up in this element in the first place. Search all the other sides to see if there is a next element...
Parameters
line_segment the LineSegment to intersect
current_elem The current element that needs to be searched
incoming_side The side of the current element that was intersected by the LineSegment that brought us here
intersected_elems The output
segments Line segments for the path across each element
Definition at line 144 of file RayTracing.C.
{
  Point intersection_point;
  std::vector<int> not_side(1, incoming_side);
  // Find the side of this element that the LineSegment intersects... while ignoring the incoming
  // side (we don't want to move backward!)
  int intersected_side =
      sideIntersectedByLine(current_elem, not_side, line_segment, intersection_point);
  if (intersected_side != -1) // -1 means that we didn't find any side
  {
    // Get the neighbor on that side
    const Elem * neighbor = current_elem->neighbor_ptr(intersected_side);
    if (neighbor)
    {
      // Add it to the list
      intersected_elems.push_back(const_cast<Elem *>(neighbor));
      // Add the line segment across the element to the segments list
      segments.push_back(LineSegment(incoming_point, intersection_point));
      // Note: This is finding the side the current_elem is on for the neighbor.  That's the
      // "incoming_side" for the neighbor
      int incoming_side = sideNeighborIsOn(neighbor, current_elem);
      // Recurse
      recursivelyFindElementsIntersectedByLine(
          line_segment, neighbor, incoming_side, intersection_point, intersected_elems, segments);
    }
    else // Add the final segment
      segments.push_back(LineSegment(incoming_point, line_segment.end()));
  }
  else // Add the final segment
    segments.push_back(LineSegment(incoming_point, line_segment.end()));
  // Finished... return out!
  return;
}
Referenced by elementsIntersectedByLine(), and recursivelyFindElementsIntersectedByLine().
registerActions() [1/2]
void Moose::registerActions (Syntax & syntax, ActionFactory & action_factory)
Multiple Action class can be associated with a single input file section, in which case all associated Actions will be created and "acted" on when the associated input file section is seen.
Example: "setup_mesh" <--------—> SetupMeshAction <------— \ [Mesh] / "setup_mesh_complete" <—> SetupMeshCompleteAction <-
Action classes can also be registered to act on more than one input file section for a different task if similar logic can work in multiple cases
Example: "add_variable" <--— -> [Variables/ *] \ / CopyNodalVarsAction / \ "add_aux_variable" <- -> [AuxVariables/ *]
Note: Placeholder "no_action" actions must be put in places where it is possible to match an object with a star or a more specific parent later on. (i.e. where one needs to negate the '*' matching prematurely).
Definition at line 395 of file Moose.C.
{
  mooseDeprecated("use registerAll instead of registerActions");
  registerActions(syntax, action_factory, {"MooseApp"});
}
Referenced by associateSyntax(), registerActions(), and registerAll().
registerActions() [2/2]
void Moose::registerActions (Syntax & syntax, ActionFactory & action_factory, const std::set< std::string > & obj_labels)
Definition at line 402 of file Moose.C.
{
  Registry::registerActionsTo(action_factory, obj_labels);
  // TODO: Why is this here?
  registerTask("finish_input_file_output", false);
}
registerAll()
void Moose::registerAll (Factory & f, ActionFactory & af, Syntax & s)
Register objects that are in MOOSE.
Definition at line 55 of file Moose.C.
{
  registerObjects(f, {"MooseApp"});
  associateSyntaxInner(s, af);
  registerActions(s, af, {"MooseApp"});
  registerDataFilePath();
}
Referenced by MooseApp::MooseApp().
registerObjects() [1/2]
void Moose::registerObjects (Factory & factory)
Definition at line 64 of file Moose.C.
{
  mooseDeprecated("use registerAll instead of registerObjects");
  registerObjects(factory, {"MooseApp"});
}
Referenced by registerAll(), and registerObjects().
registerObjects() [2/2]
void Moose::registerObjects (Factory & factory, const std::set< std::string > & obj_labels)
Definition at line 71 of file Moose.C.
{
  Registry::registerObjectsTo(factory, obj_labels);
}
restrictPointToFace()
void Moose::restrictPointToFace (Point & p, const Elem * side, std::vector< const Node * > & off_edge_nodes)
Definition at line 264 of file FindContactPoint.C.
{
  const ElemType t(side->type());
  off_edge_nodes.clear();
  Real & xi = p(0);
  Real & eta = p(1);
  switch (t)
  {
    case EDGE2:
    case EDGE3:
    case EDGE4:
    {
      // The reference 1D element is [-1,1].
      if (xi < -1.0)
      {
        xi = -1.0;
        off_edge_nodes.push_back(side->node_ptr(0));
      }
      else if (xi > 1.0)
      {
        xi = 1.0;
        off_edge_nodes.push_back(side->node_ptr(1));
      }
      break;
    }
    case TRI3:
    case TRI6:
    case TRI7:
    {
      // The reference triangle is isosceles
      // and is bound by xi=0, eta=0, and xi+eta=1.
      if (xi <= 0.0 && eta <= 0.0)
      {
        xi = 0.0;
        eta = 0.0;
        off_edge_nodes.push_back(side->node_ptr(0));
      }
      else if (xi > 0.0 && xi < 1.0 && eta < 0.0)
      {
        eta = 0.0;
        off_edge_nodes.push_back(side->node_ptr(0));
        off_edge_nodes.push_back(side->node_ptr(1));
      }
      else if (eta > 0.0 && eta < 1.0 && xi < 0.0)
      {
        xi = 0.0;
        off_edge_nodes.push_back(side->node_ptr(2));
        off_edge_nodes.push_back(side->node_ptr(0));
      }
      else if (xi >= 1.0 && (eta - xi) <= -1.0)
      {
        xi = 1.0;
        eta = 0.0;
        off_edge_nodes.push_back(side->node_ptr(1));
      }
      else if (eta >= 1.0 && (eta - xi) >= 1.0)
      {
        xi = 0.0;
        eta = 1.0;
        off_edge_nodes.push_back(side->node_ptr(2));
      }
      else if ((xi + eta) > 1.0)
      {
        Real delta = (xi + eta - 1.0) / 2.0;
        xi -= delta;
        eta -= delta;
        off_edge_nodes.push_back(side->node_ptr(1));
        off_edge_nodes.push_back(side->node_ptr(2));
      }
      break;
    }
    case QUAD4:
    case QUAD8:
    case QUAD9:
    {
      // The reference quadrilateral element is [-1,1]^2.
      if (xi < -1.0)
      {
        xi = -1.0;
        if (eta < -1.0)
        {
          eta = -1.0;
          off_edge_nodes.push_back(side->node_ptr(0));
        }
        else if (eta > 1.0)
        {
          eta = 1.0;
          off_edge_nodes.push_back(side->node_ptr(3));
        }
        else
        {
          off_edge_nodes.push_back(side->node_ptr(3));
          off_edge_nodes.push_back(side->node_ptr(0));
        }
      }
      else if (xi > 1.0)
      {
        xi = 1.0;
        if (eta < -1.0)
        {
          eta = -1.0;
          off_edge_nodes.push_back(side->node_ptr(1));
        }
        else if (eta > 1.0)
        {
          eta = 1.0;
          off_edge_nodes.push_back(side->node_ptr(2));
        }
        else
        {
          off_edge_nodes.push_back(side->node_ptr(1));
          off_edge_nodes.push_back(side->node_ptr(2));
        }
      }
      else
      {
        if (eta < -1.0)
        {
          eta = -1.0;
          off_edge_nodes.push_back(side->node_ptr(0));
          off_edge_nodes.push_back(side->node_ptr(1));
        }
        else if (eta > 1.0)
        {
          eta = 1.0;
          off_edge_nodes.push_back(side->node_ptr(2));
          off_edge_nodes.push_back(side->node_ptr(3));
        }
      }
      break;
    }
    default:
    {
      mooseError("Unsupported face type: ", t);
      break;
    }
  }
}
Referenced by findContactPoint().
SERIAL_ACCESS_CONST_SIZE() [1/3]
Moose::SERIAL_ACCESS_CONST_SIZE (RankFourTensorTempl , & obj0u, 0u, 0u, 0u, RankFourTensorTempl< T >::N4)
SERIAL_ACCESS_CONST_SIZE() [2/3]
Moose::SERIAL_ACCESS_CONST_SIZE (RankTwoTensorTempl , & obj0u, 0u, RankTwoTensorTempl< T >::N2)
SERIAL_ACCESS_CONST_SIZE() [3/3]
Moose::SERIAL_ACCESS_CONST_SIZE (VectorValue , & obj0u, Moose::dim)
SERIAL_ACCESS_DYNAMIC_SIZE()
Moose::SERIAL_ACCESS_DYNAMIC_SIZE (DenseVector , & obj0u, obj. size())
SERIAL_ACCESS_SCALAR() [1/2]
Moose::SERIAL_ACCESS_SCALAR (ADReal)
SERIAL_ACCESS_SCALAR() [2/2]
Moose::SERIAL_ACCESS_SCALAR (Real)
serialAccess()
template<typename T > SerialAccessRange< T > Moose::serialAccess (T & obj)
Definition at line 151 of file SerialAccess.h.
{
  return SerialAccessRange<T>(obj);
}
Referenced by InterpolatedStatefulMaterialTempl< T >::computeQpProperties(), ProjectedStatefulMaterialAuxTempl< T, is_ad >::computeValue(), and ProjectedStatefulMaterialNodalPatchRecoveryTempl< T, is_ad >::execute().
setColorConsole()
bool Moose::setColorConsole (bool use_color, bool force = false)
Turns color escape sequences on/off for info written to stdout.
Returns the the set value which may be different than use_color.
Definition at line 618 of file Moose.C.
{
  _color_console = (isatty(fileno(stdout)) || force) && use_color;
  return _color_console;
}
Referenced by CommonOutputAction::act(), and MooseApp::setupOptions().
setSolverDefaults()
void Moose::setSolverDefaults (FEProblemBase & problem)
Definition at line 595 of file Moose.C.
{
  // May be a touch expensive to create a new DM every time, but probably safer to do it this way
  Moose::PetscSupport::petscSetDefaults(problem);
}
Referenced by FEProblemBase::solve().
sideIntersectedByLine()
int Moose::sideIntersectedByLine (const Elem * elem, std::vector< int > & not_side, const LineSegment & line_segment, Point & intersection_point)
Figure out which (if any) side of an Elem is intersected by a line.
Parameters
elem The elem to search
not_side Sides to not search (Use -1 if you want to search all sides)
intersection_point If an intersection is found this will be filled with the x,y,z position of that intersection
Returns
The side that is intersected by the line. Will return -1 if it doesn't intersect any side
Definition at line 34 of file RayTracing.C.
{
  unsigned int n_sides = elem->n_sides();
  // Whether or not they intersect
  bool intersect = false;
  unsigned int dim = elem->dim();
  for (unsigned int i = 0; i < n_sides; i++)
  {
    // Don't search the "not_side"
    // Note: A linear search is fine here because this vector is going to be < n_sides
    if (std::find(not_side.begin(), not_side.end(), static_cast<int>(i)) != not_side.end())
      continue;
    // Get a simplified side element
    std::unique_ptr<const Elem> side_elem = elem->side_ptr(i);
    if (dim == 3)
    {
      // Make a plane out of the first three nodes on the side
      Plane plane(side_elem->point(0), side_elem->point(1), side_elem->point(2));
      // See if they intersect
      intersect = line_segment.intersect(plane, intersection_point);
    }
    else if (dim == 2)
    {
      // Make a Line Segment out of the first two nodes on the side
      LineSegment side_segment(side_elem->point(0), side_elem->point(1));
      // See if they intersect
      intersect = line_segment.intersect(side_segment, intersection_point);
    }
    else // 1D
    {
      // See if the line segment contains the point
      intersect = line_segment.contains_point(side_elem->point(0));
      // If it does then save off that one point as the intersection point
      if (intersect)
        intersection_point = side_elem->point(0);
    }
    if (intersect)
    {
      if (side_elem->contains_point(intersection_point))
      {
        const Elem * neighbor = elem->neighbor_ptr(i);
        // If this side is on a boundary, let's do another search and see if we can find a better
        // candidate
        if (!neighbor)
        {
          not_side.push_back(i); // Make sure we don't find this side again
          int better_side = sideIntersectedByLine(elem, not_side, line_segment, intersection_point);
          if (better_side != -1)
            return better_side;
        }
        return i;
      }
    }
  }
  // Didn't find one
  return -1;
}
Referenced by recursivelyFindElementsIntersectedByLine(), and sideIntersectedByLine().
sideNeighborIsOn()
int Moose::sideNeighborIsOn (const Elem * elem, const Elem * neighbor)
Returns the side number for elem that neighbor is on.
Returns -1 if the neighbor can't be found to be a neighbor
Definition at line 115 of file RayTracing.C.
{
  unsigned int n_sides = elem->n_sides();
  for (unsigned int i = 0; i < n_sides; i++)
  {
    if (elem->neighbor_ptr(i) == neighbor)
      return i;
  }
  return -1;
}
Referenced by recursivelyFindElementsIntersectedByLine().
stringify() [1/21]
std::string Moose::stringify (bool v) inline
Definition at line 71 of file Conversion.h.
{
  return v ? "true" : "false";
}
stringify() [2/21]
std::string Moose::stringify (const EigenSolveType & t)
Convert eigen solve type into human readable string.
Definition at line 376 of file Conversion.C.
{
  switch (t)
  {
    case EST_POWER:
      return "Power";
    case EST_ARNOLDI:
      return "ARNOLDI";
    case EST_KRYLOVSCHUR:
      return "KRYLOVSCHUR";
    case EST_JACOBI_DAVIDSON:
      return "Jacobi Davidson";
    case EST_NONLINEAR_POWER:
      return "Nonlinear Power";
    case EST_PJFNKMO:
      return "PJFNK with Matrix Only";
    case EST_NEWTON:
      return "Newton";
    case EST_JFNK:
      return "JFNK";
    case EST_PJFNK:
      return "Preconditioned JFNK";
  }
  return "";
}
stringify() [3/21]
std::string Moose::stringify (const Moose::TimeIntegratorType & t)
stringify() [4/21]
std::string Moose::stringify (const RelationshipManagerType & t)
Definition at line 324 of file Conversion.C.
{
  // Cannot make a switch statement because the boolean logic doesn't work well with the class type
  // enumeration and because Cody says so.
  if (t == RelationshipManagerType::DEFAULT)
    return "DEFAULT";
  if (t == RelationshipManagerType::GEOMETRIC)
    return "GEOMETRIC";
  if (t == RelationshipManagerType::ALGEBRAIC)
    return "ALGEBRAIC";
  if (t == (RelationshipManagerType::GEOMETRIC | RelationshipManagerType::ALGEBRAIC))
    return "GEOMETRIC and ALGEBRAIC";
  if (t == (RelationshipManagerType::ALGEBRAIC | RelationshipManagerType::COUPLING))
    return "ALGEBRAIC and COUPLING";
  if (t == (RelationshipManagerType::GEOMETRIC | RelationshipManagerType::ALGEBRAIC |
            RelationshipManagerType::COUPLING))
    return "GEOMETRIC and ALGEBRAIC and COUPLING";
  if (t == RelationshipManagerType::COUPLING)
    return "COUPLING";
  mooseError("Unknown RelationshipManagerType");
}
Referenced by AddDriftDiffusionAction::act(), MaterialDerivativeTestAction::act(), SetupResidualDebugAction::act(), FEProblemBase::addAuxArrayVariable(), AddReactions::addAuxRate(), AddZapdosReactions::addAuxRate(), FEProblemBase::addAuxScalarVariable(), FEProblemBase::addAuxVariable(), AddReactions::addConstantCoefficient(), AddZapdosReactions::addConstantKernel(), AddZapdosReactions::addConstantRateCoefficient(), AddReactions::addConstantReaction(), AddZapdosReactions::addEEDFCoefficient(), AddZapdosReactions::addEEDFEnergy(), AddZapdosReactions::addEEDFKernel(), AddReactions::addFunctionCoefficient(), AddZapdosReactions::addFunctionKernel(), AddZapdosReactions::addFunctionRateCoefficient(), AddReactions::addFunctionReaction(), DiracKernelBase::addPoint(), MooseObjectAction::addRelationshipManagers(), AddScalarReactions::AddScalarReactions(), AddZapdosReactions::addSuperelasticRateCoefficient(), MooseVariableData< OutputType >::adGradPhi(), MooseVariableData< OutputType >::adGradPhiFace(), MooseEnum::assign(), ParsedFunctorMaterialTempl< is_ad >::buildParsedFunction(), MooseMesh::checkCoordinateSystems(), MeshDiagnosticsGenerator::checkElementOverlap(), MeshDiagnosticsGenerator::checkElementTypes(), Moose::FunctorBase< T >::checkFace(), MeshDiagnosticsGenerator::checkLocalJacobians(), MeshDiagnosticsGenerator::checkNonConformalMesh(), MeshDiagnosticsGenerator::checkNonConformalMeshFromAdaptivity(), MeshDiagnosticsGenerator::checkNonPlanarSides(), BlockRestrictable::checkVariable(), ChemicalReactionsBase::ChemicalReactionsBase(), CircularBoundaryCorrectionGenerator::circularCenterCalculator(), Moose::SlepcSupport::clearFreeNonlinearPowerIterations(), FEProblemBase::computeUserObjectsInternal(), CopyValueAux::CopyValueAux(), DGKernelBase::DGKernelBase(), CartesianGridDivision::divisionIndex(), CylindricalGridDivision::divisionIndex(), SphericalGridDivision::divisionIndex(), MonotoneCubicInterpolation::errorCheck(), UnitsConversionEvaler::eval(), FEProblemBase::execMultiApps(), FEProblemBase::execMultiAppTransfers(), MeshDivisionFunctorReductionVectorPostprocessor::execute(), DOFMapOutput::filename(), ElementQualityChecker::finalize(), ParsedMaterialHelper< is_ad >::functionParse(), ExtraNodesetGenerator::generate(), ActionWarehouse::getAction(), FunctorBinnedValuesDivision::getBinIndex(), ComputeFVFluxThread< RangeType, AttributeTagType >::getBlockNames(), ExecFlagEnum::getDocString(), SolutionUserObject::getLocalVarIndex(), Positions::getNearestPositionIndex(), MooseEnumBase::getRawNames(), MooseApp::getRelationshipManagerInfo(), SystemBase::getScalarVariable(), ProjectedStatefulMaterialStorageAction::getTypeEnum(), SystemBase::getVariable(), Moose::FV::harmonicInterpolation(), MultiAppGeneralFieldTransfer::initialSetup(), MatrixTools::inverse(), MooseVariableFV< Real >::jacobianSetup(), LeastSquaresFitHistory::LeastSquaresFitHistory(), MultiApp::localApp(), MeshDivisionAux::MeshDivisionAux(), SystemBase::oldSolutionStateVectorName(), Parser::parse(), PatternedMeshGenerator::PatternedMeshGenerator(), CompileTimeDerivatives::CTValue< tag, T >::print(), CompileTimeDerivatives::CTArrayRef< tag, T, I >::print(), CompileTimeDerivatives::CTIPow< B, E >::print(), libMesh::print_helper(), CompileTimeDerivatives::printTag(), TopResidualDebugOutput::printTopResiduals(), ProjectedStatefulMaterialStorageAction::processProperty(), DerivativeParsedMaterialHelperTempl< is_ad >::recurseMatProps(), MeshRepairGenerator::separateSubdomainsByElementType(), MooseMesh::setCoordSystem(), Moose::SlepcSupport::setFreeNonlinearPowerIterations(), Moose::SlepcSupport::setNewtonPetscOptions(), Moose::SlepcSupport::setSlepcEigenSolverTolerances(), Split::setup(), SystemBase::solutionState(), FEProblemBase::solverTypeString(), EigenProblem::solverTypeString(), stringify(), and FEProblemSolve::validParams().
stringify() [5/21]
std::string Moose::stringify (const SolveType & t)
Convert solve type into human readable string.
Definition at line 357 of file Conversion.C.
{
  switch (t)
  {
    case ST_NEWTON:
      return "NEWTON";
    case ST_JFNK:
      return "JFNK";
    case ST_PJFNK:
      return "Preconditioned JFNK";
    case ST_FD:
      return "FD";
    case ST_LINEAR:
      return "Linear";
  }
  return "";
}
stringify() [6/21]
template<typename T , typename U > std::string Moose::stringify (const std::pair< T, U > & p, const std::string & delim = ":")
Add pair stringify to support maps.
Definition at line 135 of file Conversion.h.
                                                              :")
{
  return stringify(p.first) + delim + stringify(p.second);
}
stringify() [7/21]
std::string Moose::stringify (const std::string & s)
Add no-op stringify if the argument already is a string (must use overloading)
Definition at line 458 of file Conversion.C.
{
  return s;
}
stringify() [8/21]
template<typename T > std::string Moose::stringify (const T & t)
conversion to string
Definition at line 62 of file Conversion.h.
{
  std::ostringstream os;
  os << t;
  return os.str();
}
stringify() [9/21]
template<template< typename... > class T, typename... U> std::string Moose::stringify (const T< U... > & c, const std::string & delim = ", ", const std::string & elem_encl = "", bool enclose_list_in_curly_braces = false)
Convert a container to a string with elements separated by delimiter of user's choice.
Optionally, the container elements can be enclosed by curly braces and can enclose elements in quotations (or other characters) to make the separation of elements more clear.
Parameters
[in] c Container to stringify
[in] delim String to print between elements
[in] elem_encl String to use at the beginning and end of each element, typically quotation marks
[in] enclose_list_in_curly_braces Enclose the list string in curly braces?
Definition at line 155 of file Conversion.h.
{
  std::string str;
  if (enclose_list_in_curly_braces)
    str += "{";
  const auto begin = c.begin();
  const auto end = c.end();
  for (auto i = begin; i != end; ++i)
    str += (i != begin ? delim : "") + elem_encl + stringify(*i) + elem_encl;
  if (enclose_list_in_curly_braces)
    str += "}";
  return str;
}
stringify() [10/21]
std::string Moose::stringify (const VarFieldType & t)
Convert variable field type into human readable string.
Definition at line 403 of file Conversion.C.
{
  switch (t)
  {
    case VAR_FIELD_STANDARD:
      return "STANDARD";
    case VAR_FIELD_VECTOR:
      return "VECTOR";
    case VAR_FIELD_ARRAY:
      return "ARRAY";
    case VAR_FIELD_SCALAR:
      return "SCALAR";
    case VAR_FIELD_ANY:
      return "ANY";
  }
  return "";
}
stringify() [11/21]
std::string Moose::stringify (ElementType t)
Convert ElementType into string.
Definition at line 436 of file Conversion.C.
{
  switch (t)
  {
    case ElementType::Element:
      return "ELEMENT";
    case ElementType::Neighbor:
      return "NEIGHBOR";
    case ElementType::Lower:
      return "LOWER";
    default:
      mooseError("unrecognized type");
  }
}
stringify() [12/21]
std::string Moose::stringify (FEFamily f)
Convert FEType from libMesh into string.
stringify() [13/21]
std::string Moose::stringify (int v) inline
Definition at line 78 of file Conversion.h.
{
  return std::to_string(v);
}
stringify() [14/21]
std::string Moose::stringify (libMesh::ElemType t)
Convert the libmesh ElemType into string.
Definition at line 452 of file Conversion.C.
{
  return libMesh::Utility::enum_to_string(t);
}
stringify() [15/21]
std::string Moose::stringify (libMesh::FEFamily f)
Definition at line 348 of file Conversion.C.
{
  return libMesh::Utility::enum_to_string(f);
}
stringify() [16/21]
std::string Moose::stringify (long long v) inline
Definition at line 88 of file Conversion.h.
{
  return std::to_string(v);
}
stringify() [17/21]
std::string Moose::stringify (long v) inline
Definition at line 83 of file Conversion.h.
{
  return std::to_string(v);
}
stringify() [18/21]
std::string Moose::stringify (SolutionIterationType t)
Convert SolutionIterationType into string.
Definition at line 422 of file Conversion.C.
{
  switch (t)
  {
    case SolutionIterationType::Time:
      return "time";
    case SolutionIterationType::Nonlinear:
      return "nonlinear";
    default:
      mooseError("Unhandled SolutionIterationType");
  }
}
stringify() [19/21]
std::string Moose::stringify (unsigned int v) inline
Definition at line 93 of file Conversion.h.
{
  return std::to_string(v);
}
stringify() [20/21]
std::string Moose::stringify (unsigned long long v) inline
Definition at line 103 of file Conversion.h.
{
  return std::to_string(v);
}
stringify() [21/21]
std::string Moose::stringify (unsigned long v) inline
Definition at line 98 of file Conversion.h.
{
  return std::to_string(v);
}
stringifyExact()
std::string Moose::stringifyExact (Real t)
Stringify Reals with enough precision to guarantee lossless Real -> string -> Real roundtrips.
Definition at line 464 of file Conversion.C.
{
  // this or std::numeric_limits<T>::max_digits10
  const unsigned int max_digits10 =
      std::floor(std::numeric_limits<Real>::digits * std::log10(2) + 2);
  std::ostringstream os;
  os << std::setprecision(max_digits10) << t;
  return os.str();
}
stringToEnum()
template<typename T > T Moose::stringToEnum (const std::string & s)
stringToEnum< CoordinateSystemType >() [1/2]
template<> CoordinateSystemType Moose::stringToEnum< CoordinateSystemType > (const std::string & s)
Definition at line 185 of file Conversion.C.
{
  initCoordinateSystemType();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!coordinate_system_type_to_enum.count(upper))
    mooseError("Unknown coordinate system type: ", upper);
  return coordinate_system_type_to_enum[upper];
}
stringToEnum< CoordinateSystemType >() [2/2]
template<> CoordinateSystemType Moose::stringToEnum< CoordinateSystemType > (const std::string & s)
Definition at line 185 of file Conversion.C.
{
  initCoordinateSystemType();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!coordinate_system_type_to_enum.count(upper))
    mooseError("Unknown coordinate system type: ", upper);
  return coordinate_system_type_to_enum[upper];
}
stringToEnum< EigenProblemType >()
template<> EigenProblemType Moose::stringToEnum< EigenProblemType > (const std::string & s)
Definition at line 230 of file Conversion.C.
{
  initEigenProlemType();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!eigen_problem_type_to_enum.count(upper))
    mooseError("Unknown eigen problem type: ", upper);
  return eigen_problem_type_to_enum[upper];
}
stringToEnum< EigenSolveType >()
template<> EigenSolveType Moose::stringToEnum< EigenSolveType > (const std::string & s)
Definition at line 215 of file Conversion.C.
{
  initEigenSolveType();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!eigen_solve_type_to_enum.count(upper))
    mooseError("Unknown eigen solve type: ", upper);
  return eigen_solve_type_to_enum[upper];
}
stringToEnum< LineSearchType >() [1/2]
template<> LineSearchType Moose::stringToEnum< LineSearchType > (const std::string & s)
Definition at line 260 of file Conversion.C.
{
  initLineSearchType();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!line_search_type_to_enum.count(upper))
    mooseError("Unknown line search type: ", upper);
  return line_search_type_to_enum[upper];
}
stringToEnum< LineSearchType >() [2/2]
template<> LineSearchType Moose::stringToEnum< LineSearchType > (const std::string & s)
Definition at line 260 of file Conversion.C.
{
  initLineSearchType();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!line_search_type_to_enum.count(upper))
    mooseError("Unknown line search type: ", upper);
  return line_search_type_to_enum[upper];
}
stringToEnum< MffdType >()
template<> MffdType Moose::stringToEnum< MffdType > (const std::string & s)
Definition at line 290 of file Conversion.C.
{
  initMffdType();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!mffd_type_to_enum.count(upper))
    mooseError("Unknown mffd type: ", upper);
  return mffd_type_to_enum[upper];
}
stringToEnum< Order >() [1/2]
template<> Order Moose::stringToEnum< Order > (const std::string & s)
Definition at line 172 of file Conversion.C.
{
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (upper.compare("AUTO") == 0)
    return INVALID_ORDER;
  else
    return Utility::string_to_enum<Order>(upper);
}
Referenced by SetupQuadratureAction::act().
stringToEnum< Order >() [2/2]
template<> Order Moose::stringToEnum< Order > (const std::string & s)
Definition at line 172 of file Conversion.C.
{
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (upper.compare("AUTO") == 0)
    return INVALID_ORDER;
  else
    return Utility::string_to_enum<Order>(upper);
}
Referenced by SetupQuadratureAction::act().
stringToEnum< QuadratureType >() [1/2]
template<> QuadratureType Moose::stringToEnum< QuadratureType > (const std::string & s)
Definition at line 165 of file Conversion.C.
{
  return Utility::string_to_enum<QuadratureType>("Q" + s);
}
stringToEnum< QuadratureType >() [2/2]
template<> QuadratureType Moose::stringToEnum< QuadratureType > (const std::string & s)
Definition at line 165 of file Conversion.C.
{
  return Utility::string_to_enum<QuadratureType>("Q" + s);
}
stringToEnum< RelationshipManagerType >() [1/2]
template<> RelationshipManagerType Moose::stringToEnum< RelationshipManagerType > (const std::string & s)
Definition at line 305 of file Conversion.C.
{
  initRMType();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!rm_type_to_enum.count(upper))
    mooseError("Unknown RelationshipManager type: ", upper);
  return rm_type_to_enum[upper];
}
stringToEnum< RelationshipManagerType >() [2/2]
template<> RelationshipManagerType Moose::stringToEnum< RelationshipManagerType > (const std::string & s)
Definition at line 305 of file Conversion.C.
{
  initRMType();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!rm_type_to_enum.count(upper))
    mooseError("Unknown RelationshipManager type: ", upper);
  return rm_type_to_enum[upper];
}
stringToEnum< SolveType >() [1/2]
template<> SolveType Moose::stringToEnum< SolveType > (const std::string & s)
Definition at line 200 of file Conversion.C.
{
  initSolveType();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!solve_type_to_enum.count(upper))
    mooseError("Unknown solve type: ", upper);
  return solve_type_to_enum[upper];
}
stringToEnum< SolveType >() [2/2]
template<> SolveType Moose::stringToEnum< SolveType > (const std::string & s)
Definition at line 200 of file Conversion.C.
{
  initSolveType();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!solve_type_to_enum.count(upper))
    mooseError("Unknown solve type: ", upper);
  return solve_type_to_enum[upper];
}
stringToEnum< TimeIntegratorType >() [1/2]
template<> TimeIntegratorType Moose::stringToEnum< TimeIntegratorType > (const std::string & s)
Definition at line 275 of file Conversion.C.
{
  initTimeIntegratorsType();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!time_integrator_to_enum.count(upper))
    mooseError("Unknown time integrator: ", upper);
  return time_integrator_to_enum[upper];
}
stringToEnum< TimeIntegratorType >() [2/2]
template<> TimeIntegratorType Moose::stringToEnum< TimeIntegratorType > (const std::string & s)
Definition at line 275 of file Conversion.C.
{
  initTimeIntegratorsType();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!time_integrator_to_enum.count(upper))
    mooseError("Unknown time integrator: ", upper);
  return time_integrator_to_enum[upper];
}
stringToEnum< WhichEigenPairs >()
template<> WhichEigenPairs Moose::stringToEnum< WhichEigenPairs > (const std::string & s)
Definition at line 245 of file Conversion.C.
{
  initWhichEigenPairs();
  std::string upper(s);
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (!which_eigen_pairs_to_enum.count(upper))
    mooseError("Unknown type of WhichEigenPairs: ", upper);
  return which_eigen_pairs_to_enum[upper];
}
swapLibMeshComm()
MPI_Comm Moose::swapLibMeshComm (MPI_Comm new_comm)
Swap the libMesh MPI communicator out for ours.
Note that you should usually use the Moose::ScopedCommSwapper class instead of calling this function.
Definition at line 602 of file Moose.C.
{
  MPI_Comm old_comm = PETSC_COMM_WORLD;
  PETSC_COMM_WORLD = new_comm;
  return old_comm;
}
Referenced by Moose::ScopedCommSwapper::forceSwap(), and Moose::ScopedCommSwapper::~ScopedCommSwapper().
to_json()
void Moose::to_json (nlohmann::json & json, const Moose::LibtorchArtificialNeuralNet *const & network)
Definition at line 140 of file LibtorchArtificialNeuralNet.C.
{
  if (network)
    network->store(json);
}
toPoint()
Point Moose::toPoint (const std::vector< Real > & pos)
Definition at line 476 of file Conversion.C.
{
  mooseAssert(pos.size() == LIBMESH_DIM, "Wrong array size while converting into a point");
  return Point(pos[0], pos[1], pos[2]);
}
typeLoop()
template<template< typename, int > class L, typename... Ts, typename... As> void Moose::typeLoop (TypeList< Ts... > , As... args)
Type loop.
Definition at line 178 of file SerialAccess.h.
{
  typeLoopInternal<L, 0>(TypeList<Ts...>{}, args...);
}
typeLoopInternal()
template<template< typename, int > class L, int I, typename T , typename... Ts, typename... As> void Moose::typeLoopInternal (TypeList< T, Ts... > , As... args)
Type loop.
Definition at line 168 of file SerialAccess.h.
{
  L<T, I>::apply(args...);
  if constexpr (sizeof...(Ts) > 0)
    typeLoopInternal<L, I + 1>(TypeList<Ts...>{}, args...);
}
vectorStringsToEnum()
template<typename T > std::vector< T > Moose::vectorStringsToEnum (const MultiMooseEnum & v)
Variable Documentation
_color_console
bool Moose::_color_console = isatty(fileno(stdout)) static
Definition at line 609 of file Moose.C.
Referenced by colorConsole(), and setColorConsole().
_deprecated_is_error
bool Moose::_deprecated_is_error = false
Variable to toggle only deprecated warnings as errors.
Definition at line 625 of file Moose.C.
Referenced by moose::internal::mooseDeprecatedStream(), and MooseApp::setupOptions().
_throw_on_error
bool Moose::_throw_on_error = false
Variable to turn on exceptions during mooseError(), should only be used within MOOSE unit tests or when about to perform threaded operations because exception throwing in threaded regions is safe while aborting is inherently not when singletons are involved (e.g.
what thread is responsible for destruction, or what do you do about mutexes?)
Definition at line 626 of file Moose.C.
Referenced by moose::internal::mooseErrorRaw(), MooseServer::parseDocumentForDiagnostics(), ThreadedFaceLoop< RangeType >::ThreadedFaceLoop(), and ThreadedFaceLoop< RangeType >::~ThreadedFaceLoop().
_throw_on_warning
bool Moose::_throw_on_warning = false
Variable to turn on exceptions during mooseWarning(), should only be used in MOOSE unit tests.
Definition at line 627 of file Moose.C.
Referenced by moose::internal::mooseUnusedStream(), and moose::internal::mooseWarningStream().
_trap_fpe
bool Moose::_trap_fpe extern
Variable indicating whether we will enable FPE trapping for this run.
_warnings_are_errors
bool Moose::_warnings_are_errors = false
Variable to toggle any warning into an error (includes deprecated code warnings)
Definition at line 624 of file Moose.C.
Referenced by moose::internal::mooseWarningStream(), and MooseApp::setupOptions().
always_false
template<class T > constexpr std::false_type Moose::always_false {} constexpr
This is a helper variable template for cases when we want to use a default compile-time error with constexpr-based if conditions.
The templating delays the triggering of the static assertion until the template is instantiated.
Definition at line 503 of file MooseTypes.h.
ANY_BLOCK_ID
const SubdomainID Moose::ANY_BLOCK_ID = libMesh::Elem::invalid_subdomain_id - 1
Definition at line 19 of file MooseTypes.C.
Referenced by SetupQuadratureAction::act(), FVInitialConditionWarehouse::addObject(), InitialConditionWarehouse::addObject(), BlockRestrictable::blockIDs(), BlockRestrictable::blockRestricted(), Assembly::bumpAllQRuleOrder(), Assembly::bumpVolumeQRuleOrder(), BlockRestrictable::hasBlocks(), AttribSubdomains::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), BlockRestrictable::isBlockSubset(), AttribSubdomains::isMatch(), and Assembly::qrules().
ANY_BOUNDARY_ID
const BoundaryID Moose::ANY_BOUNDARY_ID = static_cast<BoundaryID>(-1)
Definition at line 23 of file MooseTypes.C.
Referenced by SubProblem::checkBoundaryMatProps(), SubProblem::getMaterialPropertyBoundaryNames(), BoundaryRestrictable::hasBoundary(), hasBoundary(), BoundaryRestrictable::hasBoundaryMaterialPropertyHelper(), AttribBoundaries::initFrom(), BlockRestrictable::initializeBlockRestrictable(), BoundaryRestrictable::initializeBoundaryRestrictable(), BoundaryRestrictable::isBoundarySubset(), AttribBoundaries::isMatch(), ComputeUserObjectsThread::printBlockExecutionInformation(), and BoundaryRestrictable::restricted().
BOUNDARY_SIDE_LOWERD_ID
const SubdomainID Moose::BOUNDARY_SIDE_LOWERD_ID = libMesh::Elem::invalid_subdomain_id - 3
Definition at line 21 of file MooseTypes.C.
Referenced by SetupMeshCompleteAction::act(), FEProblemBase::adaptMesh(), ArrayHFEMDirichletBC::ArrayHFEMDirichletBC(), ArrayLowerDIntegratedBC::ArrayLowerDIntegratedBC(), MooseMesh::buildLowerDMesh(), NonlinearSystemBase::checkKernelCoverage(), HFEMDirichletBC::HFEMDirichletBC(), FEProblemBase::initialAdaptMesh(), LowerDIntegratedBC::LowerDIntegratedBC(), and ThreadedElementLoopBase< RangeType >::operator()().
constMaxQpsPerElem
constexpr std::size_t Moose::constMaxQpsPerElem = 216 constexpr
This is used for places where we initialize some qp-sized data structures that would end up being sized too small after the quadrature order gets bumped (dynamically in-sim).
So for these cases, we just use this constant to size those data structures overly large to accomodate rather than come up with some overkill complex mechanism for dynamically resizing them. Eventually, we may need or implement that more sophisticated mechanism and will no longer need this.
Definition at line 218 of file MooseTypes.h.
Referenced by MaterialPropertyInterface::defaultGenericMaterialProperty(), and FEProblemBase::updateMaxQps().
coordinate_system_type_to_enum
std::map<std::string, CoordinateSystemType> Moose::coordinate_system_type_to_enum
Definition at line 24 of file Conversion.C.
Referenced by initCoordinateSystemType(), and stringToEnum< CoordinateSystemType >().
dim
constexpr std::size_t Moose::dim = LIBMESH_DIM static constexpr
This is the dimension of all vector and tensor datastructures used in MOOSE.
We enforce LIBMESH_DIM == 3 through a static assertion above. Note that lower dimensional simulations embedded in 3D space can always be requested at runtime.
Definition at line 147 of file Moose.h.
Referenced by ParsedFunctorMaterialTempl< is_ad >::buildParsedFunction(), ColumnMajorMatrixTempl< T >::ColumnMajorMatrixTempl(), ColumnMajorMatrixTempl< Real >::ColumnMajorMatrixTempl(), GenericFunctionVectorMaterialTempl< is_ad >::computeQpFunctions(), ElementW1pError::computeQpIntegral(), GenericConstantVectorMaterialTempl< is_ad >::computeQpProperties(), FVAnisotropicDiffusion::computeQpResidual(), ArrayParsedAux::computeValue(), ElementH1ErrorFunctionAux::computeValue(), ParsedVectorAux::computeValue(), MooseVariableData< OutputType >::computeValues(), dataLoad(), dataStore(), MooseMesh::detectOrthogonalDimRanges(), SideDiffusiveFluxIntegralTempl< is_ad, T >::diffusivityGradientProduct(), InitialConditionTempl< T >::dotHelper(), IntersectionPointsAlongLine::execute(), ColumnMajorMatrixTempl< T >::fill(), findContactPoint(), GenericFunctionVectorMaterialTempl< is_ad >::GenericFunctionVectorMaterialTempl(), Coupleable::getDefaultVectorValue(), MultiAppTransfer::getFromBoundingBoxes(), ArrayFunctionIC::gradient(), Moose::FV::greenGaussGradient(), Moose::FV::harmonicInterpolation(), MooseAppCoordTransform::hasScalingOrRotationTransformation(), PropertyReadFile::initVoronoiCenterPoints(), MultiAppCoordTransform::isIdentity(), MooseUtils::isZero(), PointListAdaptor< PointObject >::kdtree_distance(), PointListAdaptor< PointObject >::kdtree_get_pt(), ResetDisplacedMeshThread::onNode(), SecondaryNeighborhoodThread::operator()(), ColumnMajorMatrixTempl< T >::operator*(), ColumnMajorMatrixTempl< T >::operator+=(), ColumnMajorMatrixTempl< T >::operator=(), ParsedFunctorMaterialTempl< is_ad >::ParsedFunctorMaterialTempl(), PropertyReadFile::PropertyReadFile(), MooseUtils::relativeFuzzyEqual(), sideIntersectedByLine(), MultiApp::transformBoundingBox(), and BoundingBoxIC::value().
eigen_problem_type_to_enum
std::map<std::string, EigenProblemType> Moose::eigen_problem_type_to_enum
Definition at line 27 of file Conversion.C.
Referenced by initEigenProlemType(), and stringToEnum< EigenProblemType >().
eigen_solve_type_to_enum
std::map<std::string, EigenSolveType> Moose::eigen_solve_type_to_enum
Definition at line 26 of file Conversion.C.
Referenced by initEigenSolveType(), and stringToEnum< EigenSolveType >().
EMPTY_BLOCK_IDS
const std::set<SubdomainID> Moose::EMPTY_BLOCK_IDS = {}
Definition at line 594 of file MooseTypes.h.
EMPTY_BOUNDARY_IDS
const std::set<BoundaryID> Moose::EMPTY_BOUNDARY_IDS = {}
Definition at line 595 of file MooseTypes.h.
execute_flags
ExecFlagEnum Moose::execute_flags extern
Storage for the registered execute flags.
This is needed for the ExecuteMooseObjectWarehouse to create the necessary storage containers on a per flag basis. This isn't something that should be used by application developers.
INTERNAL_SIDE_LOWERD_ID
const SubdomainID Moose::INTERNAL_SIDE_LOWERD_ID = libMesh::Elem::invalid_subdomain_id - 2
Definition at line 20 of file MooseTypes.C.
Referenced by SetupMeshCompleteAction::act(), FEProblemBase::adaptMesh(), ArrayDGLowerDKernel::ArrayDGLowerDKernel(), MooseMesh::buildLowerDMesh(), NonlinearSystemBase::checkKernelCoverage(), BlockRestrictable::checkVariable(), ComputeFullJacobianThread::computeOnInternalFace(), DGLowerDKernel::DGLowerDKernel(), FEProblemBase::initialAdaptMesh(), ThreadedElementLoopBase< RangeType >::operator()(), DisplacedProblem::reinitElemNeighborAndLowerD(), and FEProblemBase::reinitElemNeighborAndLowerD().
interrupt_signal_number
int Moose::interrupt_signal_number = 0
Used by the signal handler to determine if we should write a checkpoint file out at any point during operation.
Definition at line 628 of file Moose.C.
Referenced by Checkpoint::shouldOutput(), and SigHandler().
INVALID_BLOCK_ID
const SubdomainID Moose::INVALID_BLOCK_ID = libMesh::Elem::invalid_subdomain_id
Definition at line 22 of file MooseTypes.C.
Referenced by FunctorDirichletBC::computeQpValue(), MultiAppGeometricInterpolationTransfer::computeTransformation(), FunctorAux::computeValue(), SubdomainsDivision::divisionIndex(), MultiAppGeometricInterpolationTransfer::fillSourceInterpolationPoints(), BlockToMeshConverterGenerator::generate(), RenameBlockGenerator::generate(), XYDelaunayGenerator::generate(), XYMeshLineCutter::generate(), MooseMeshUtils::getSubdomainID(), MooseMeshUtils::hasSubdomainID(), MultiAppDofCopyTransfer::initialSetup(), MultiAppGeometricInterpolationTransfer::interpolateTargetPoints(), AttribSubdomains::isMatch(), FaceInfo::neighborSubdomainID(), ComputeJacobianForScalingThread::operator()(), AugmentSparsityOnInterface::operator()(), ThreadedFaceLoop< RangeType >::operator()(), ThreadedElementLoopBase< RangeType >::operator()(), ComputeFVFluxThread< RangeType, AttributeTagType >::printBlockExecutionInformation(), ComputeFVFluxThread< RangeType, AttributeTagType >::printBoundaryExecutionInformation(), MooseMeshXYCuttingUtils::quadToTriOnLine(), and MooseMeshXYCuttingUtils::quasiTriElementsFixer().
INVALID_BOUNDARY_ID
const BoundaryID Moose::INVALID_BOUNDARY_ID = libMesh::BoundaryInfo::invalid_id
Definition at line 24 of file MooseTypes.C.
Referenced by BreakMeshByBlockGenerator::addInterfaceBoundary(), MultiAppNearestNodeTransfer::execute(), BreakMeshByBlockGenerator::generate(), ExplodeMeshGenerator::generate(), PatternedMeshGenerator::generate(), RefineSidesetGenerator::generate(), RenameBoundaryGenerator::generate(), SideSetsFromBoundingBoxGenerator::generate(), MooseMeshUtils::getBoundaryID(), MooseMeshUtils::hasBoundaryID(), AugmentSparsityOnInterface::operator()(), and XYMeshLineCutter::XYMeshLineCutter().
INVALID_PROCESSOR_ID
const processor_id_type Moose::INVALID_PROCESSOR_ID = libMesh::DofObject::invalid_processor_id
Definition at line 18 of file MooseTypes.C.
INVALID_TAG_ID
const TagID Moose::INVALID_TAG_ID = static_cast<TagID>(-1)
Definition at line 25 of file MooseTypes.C.
Referenced by MooseVariableDataBase< OutputType >::assignNodalValue().
INVALID_TAG_TYPE_ID
const TagTypeID Moose::INVALID_TAG_TYPE_ID = static_cast<TagTypeID>(-1)
Definition at line 26 of file MooseTypes.C.
line_search_type_to_enum
std::map<std::string, LineSearchType> Moose::line_search_type_to_enum
Definition at line 29 of file Conversion.C.
Referenced by initLineSearchType(), and stringToEnum< LineSearchType >().
mffd_type_to_enum
std::map<std::string, MffdType> Moose::mffd_type_to_enum
Definition at line 31 of file Conversion.C.
Referenced by initMffdType(), and stringToEnum< MffdType >().
OLD_SOLUTION_TAG
const TagName Moose::OLD_SOLUTION_TAG = "SOLUTION_STATE_1"
Definition at line 28 of file MooseTypes.C.
Referenced by SystemBase::oldSolutionStateVectorName(), Coupleable::requestStates(), and MooseVariableDataBase< OutputType >::stateToTagHelper().
OLDER_SOLUTION_TAG
const TagName Moose::OLDER_SOLUTION_TAG = "SOLUTION_STATE_2"
Definition at line 29 of file MooseTypes.C.
Referenced by SystemBase::oldSolutionStateVectorName(), Coupleable::requestStates(), and MooseVariableDataBase< OutputType >::stateToTagHelper().
perf_log
PerfLog Moose::perf_log extern
Perflog to be used by applications.
If the application prints this in the end they will get performance info.
Referenced by CheckOutputAction::checkPerfLogOutput(), Console::output(), MooseServer::parseDocumentForDiagnostics(), MooseApp::setupOptions(), and Console::~Console().
PREVIOUS_NL_SOLUTION_TAG
const TagName Moose::PREVIOUS_NL_SOLUTION_TAG = "U_PREVIOUS_NL_NEWTON"
Definition at line 30 of file MooseTypes.C.
Referenced by FEProblemBase::computePostCheck(), FEProblemBase::needsPreviousNewtonIteration(), SystemBase::oldSolutionStateVectorName(), NonlinearSystemBase::setPreviousNewtonSolution(), SystemBase::solutionPreviousNewton(), and MooseVariableDataBase< OutputType >::stateToTagHelper().
rm_type_to_enum
std::map<std::string, RelationshipManagerType> Moose::rm_type_to_enum
Definition at line 32 of file Conversion.C.
Referenced by initRMType(), and stringToEnum< RelationshipManagerType >().
show_multiple
bool Moose::show_multiple = false
Set to false (the default) to display an error message only once for each error call code location (as opposed to every time the code is executed).
Definition at line 630 of file Moose.C.
show_trace
bool Moose::show_trace = true
Set to true (the default) to print the stack trace with error and warning messages - false to omit it.
Definition at line 629 of file Moose.C.
Referenced by InputParameters::attemptPrintDeprecated(), Factory::deprecatedMessage(), moose::internal::mooseDeprecatedStream(), moose::internal::mooseErrorRaw(), and MooseBaseParameterInterface::paramError().
SOLUTION_TAG
const TagName Moose::SOLUTION_TAG = "SOLUTION"
Definition at line 27 of file MooseTypes.C.
Referenced by FEProblemBase::createTagSolutions(), MooseVariableDataBase< OutputType >::MooseVariableDataBase(), NonlinearSystemBase::setSolution(), and MooseVariableDataBase< OutputType >::stateToTagHelper().
solve_type_to_enum
std::map<std::string, SolveType> Moose::solve_type_to_enum
Definition at line 25 of file Conversion.C.
Referenced by initSolveType(), and stringToEnum< SolveType >().
time_integrator_to_enum
std::map<std::string, TimeIntegratorType> Moose::time_integrator_to_enum
Definition at line 30 of file Conversion.C.
Referenced by initTimeIntegratorsType(), and stringToEnum< TimeIntegratorType >().
which_eigen_pairs_to_enum
std::map<std::string, WhichEigenPairs> Moose::which_eigen_pairs_to_enum
Definition at line 28 of file Conversion.C.
Referenced by initWhichEigenPairs(), and stringToEnum< WhichEigenPairs >().