Zapdos: moose/framework/src/parser/Parser.C File Reference
Parser.C File Reference
Classes
class DupParamWalker
class CompileParamWalker
class OverrideParamWalker
class UnusedWalker
class BadActiveWalker
Functions
bool isSectionActive (std::string path, hit::Node *root)
std::vector< std::string > findSimilar (std::string param, std::vector< std::string > options)
template<>
void Parser::setScalarParameter< ReporterName, std::string > (const std::string &full_name, const std::string &short_name, InputParameters::Parameter< ReporterName > *param, bool in_global, GlobalParamsAction *global_block)
template<>
void Parser::setVectorParameter< ReporterName, std::string > (const std::string &full_name, const std::string &short_name, InputParameters::Parameter< std::vector< ReporterName > > *param, bool in_global, GlobalParamsAction *global_block)
template<>
void Parser::setVectorParameter< CLIArgString, std::string > (const std::string &full_name, const std::string &short_name, InputParameters::Parameter< std::vector< CLIArgString > > *param, bool in_global, GlobalParamsAction *global_block)
template<typename T >
bool toBool (const std::string &, T &)
template<>
bool toBool< bool > (const std::string &s, bool &val)
template<>
void Parser::setScalarParameter< ReporterName, std::string > (const std::string &full_name, const std::string &, InputParameters::Parameter< ReporterName > *param, bool, GlobalParamsAction *)
template<>
void Parser::setVectorParameter< ReporterName, std::string > (const std::string &full_name, const std::string &, InputParameters::Parameter< std::vector< ReporterName > > *param, bool, GlobalParamsAction *)
template<>
void Parser::setVectorParameter< CLIArgString, std::string > (const std::string &full_name, const std::string &, InputParameters::Parameter< std::vector< CLIArgString > > *param, bool, GlobalParamsAction *)
Function Documentation
findSimilar()
std::vector< std::string > findSimilar (std::string param, std::vector< std::string > options)
Definition at line 314 of file Parser.C.
{
  std::vector<std::string> candidates;
  if (options.size() == 0)
    return candidates;
  int mindist = MooseUtils::levenshteinDist(options[0], param);
  for (auto & opt : options)
  {
    int dist = MooseUtils::levenshteinDist(opt, param);
    // magic number heuristics to get similarity distance cutoff
    int dist_cutoff = 1 + param.size() / 5;
    if (dist > dist_cutoff || dist > mindist)
      continue;
    if (dist < mindist)
    {
      mindist = dist;
      candidates.clear();
    }
    candidates.push_back(opt);
  }
  return candidates;
}
Referenced by UnusedWalker::walk().
isSectionActive()
bool isSectionActive (std::string path, hit::Node * root)
Definition at line 210 of file Parser.C.
{
  hit::Node * n = root->find(path);
  while (n)
  {
    hit::Node * section = n->parent();
    if (section)
    {
      auto actives = section->find("active");
      auto inactives = section->find("inactive");
      // only check current level, not nested ones
      if (actives && actives->type() == hit::NodeType::Field && actives->parent() == section)
      {
        auto vars = section->param<std::vector<std::string>>("active");
        bool have_var = false;
        for (auto & var : vars)
          if (n->path() == hit::pathNorm(var))
            have_var = true;
        if (!have_var)
          return false;
      }
      // only check current level, not nested ones
      if (inactives && inactives->type() == hit::NodeType::Field && inactives->parent() == section)
      {
        auto vars = section->param<std::vector<std::string>>("inactive");
        for (auto & var : vars)
          if (n->path() == hit::pathNorm(var))
            return false;
      }
    }
    n = section;
  }
  return true;
}
Referenced by UnusedWalker::walk(), and Parser::walkRaw().
Parser::setScalarParameter< ReporterName, std::string >() [1/2]
template<> void Parser::setScalarParameter< ReporterName, std::string > (const std::string & full_name, const std::string & short_name, InputParameters::Parameter< ReporterName > * param, bool in_global, GlobalParamsAction * global_block)
Definition at line 2469 of file Parser.C.
{
  std::vector<std::string> names = MooseUtils::rsplit(_root->param<std::string>(full_name), "/", 2);
  if (names.size() != 2)
    _errmsg += hit::errormsg(_root->find(full_name),
                             "The supplied name ReporterName '",
                             full_name,
                             "' must contain the '/' delimiter.");
  else
    param->set() = ReporterName(names[0], names[1]);
}
Parser::setScalarParameter< ReporterName, std::string >() [2/2]
template<> void Parser::setScalarParameter< ReporterName, std::string > (const std::string & full_name, const std::string & short_name, InputParameters::Parameter< ReporterName > * param, bool in_global, GlobalParamsAction * global_block)
Definition at line 2469 of file Parser.C.
{
  std::vector<std::string> names = MooseUtils::rsplit(_root->param<std::string>(full_name), "/", 2);
  if (names.size() != 2)
    _errmsg += hit::errormsg(_root->find(full_name),
                             "The supplied name ReporterName '",
                             full_name,
                             "' must contain the '/' delimiter.");
  else
    param->set() = ReporterName(names[0], names[1]);
}
Parser::setVectorParameter< CLIArgString, std::string >() [1/2]
template<> void Parser::setVectorParameter< CLIArgString, std::string > (const std::string & full_name, const std::string & short_name, InputParameters::Parameter< std::vector< CLIArgString > > * param, bool in_global, GlobalParamsAction * global_block)
Definition at line 2657 of file Parser.C.
{
  // Parsed as a vector of string, the vectors parameters are being cut
  auto rnames = _root->param<std::vector<std::string>>(full_name);
  param->set().resize(rnames.size()); // slightly oversized if vectors have been split
  // Skip empty parameter
  if (rnames.empty())
    return;
  // Re-assemble vector parameters
  unsigned int i_param = 0;
  bool vector_param_detected = false;
  for (unsigned int i = 0; i < rnames.size(); ++i)
  {
    // Look for a quote, both types
    std::vector<std::string> double_split =
        MooseUtils::rsplit(rnames[i], "\"", std::numeric_limits<std::size_t>::max());
    std::vector<std::string> single_split =
        MooseUtils::rsplit(rnames[i], "\'", std::numeric_limits<std::size_t>::max());
    if (double_split.size() + single_split.size() >= 3)
      // Either entering or exiting a vector parameter (>3 is entering another vector)
      // Even and >2 number of quotes means both finished and started another vector parameter
      if ((double_split.size() + single_split.size()) % 2 == 1)
        vector_param_detected = !vector_param_detected;
    // We're building a vector parameters, just append the text, rebuild the spaces
    if (vector_param_detected)
      param->set()[i_param] += rnames[i] + ' ';
    else
    {
      param->set()[i_param] += rnames[i];
      i_param++;
    }
  }
  // Use actual size after re-forming vector parameters
  param->set().resize(i_param);
}
Parser::setVectorParameter< CLIArgString, std::string >() [2/2]
template<> void Parser::setVectorParameter< CLIArgString, std::string > (const std::string & full_name, const std::string & short_name, InputParameters::Parameter< std::vector< CLIArgString > > * param, bool in_global, GlobalParamsAction * global_block)
Definition at line 2657 of file Parser.C.
{
  // Parsed as a vector of string, the vectors parameters are being cut
  auto rnames = _root->param<std::vector<std::string>>(full_name);
  param->set().resize(rnames.size()); // slightly oversized if vectors have been split
  // Skip empty parameter
  if (rnames.empty())
    return;
  // Re-assemble vector parameters
  unsigned int i_param = 0;
  bool vector_param_detected = false;
  for (unsigned int i = 0; i < rnames.size(); ++i)
  {
    // Look for a quote, both types
    std::vector<std::string> double_split =
        MooseUtils::rsplit(rnames[i], "\"", std::numeric_limits<std::size_t>::max());
    std::vector<std::string> single_split =
        MooseUtils::rsplit(rnames[i], "\'", std::numeric_limits<std::size_t>::max());
    if (double_split.size() + single_split.size() >= 3)
      // Either entering or exiting a vector parameter (>3 is entering another vector)
      // Even and >2 number of quotes means both finished and started another vector parameter
      if ((double_split.size() + single_split.size()) % 2 == 1)
        vector_param_detected = !vector_param_detected;
    // We're building a vector parameters, just append the text, rebuild the spaces
    if (vector_param_detected)
      param->set()[i_param] += rnames[i] + ' ';
    else
    {
      param->set()[i_param] += rnames[i];
      i_param++;
    }
  }
  // Use actual size after re-forming vector parameters
  param->set().resize(i_param);
}
Parser::setVectorParameter< ReporterName, std::string >() [1/2]
template<> void Parser::setVectorParameter< ReporterName, std::string > (const std::string & full_name, const std::string & short_name, InputParameters::Parameter< std::vector< ReporterName > > * param, bool in_global, GlobalParamsAction * global_block)
Definition at line 2632 of file Parser.C.
{
  auto rnames = _root->param<std::vector<std::string>>(full_name);
  param->set().resize(rnames.size());
  for (unsigned int i = 0; i < rnames.size(); ++i)
  {
    std::vector<std::string> names = MooseUtils::rsplit(rnames[i], "/", 2);
    if (names.size() != 2)
      _errmsg += hit::errormsg(_root->find(full_name),
                               "The supplied name ReporterName '",
                               rnames[i],
                               "' must contain the '/' delimiter.");
    else
      param->set()[i] = ReporterName(names[0], names[1]);
  }
}
Parser::setVectorParameter< ReporterName, std::string >() [2/2]
template<> void Parser::setVectorParameter< ReporterName, std::string > (const std::string & full_name, const std::string & short_name, InputParameters::Parameter< std::vector< ReporterName > > * param, bool in_global, GlobalParamsAction * global_block)
Definition at line 2632 of file Parser.C.
{
  auto rnames = _root->param<std::vector<std::string>>(full_name);
  param->set().resize(rnames.size());
  for (unsigned int i = 0; i < rnames.size(); ++i)
  {
    std::vector<std::string> names = MooseUtils::rsplit(rnames[i], "/", 2);
    if (names.size() != 2)
      _errmsg += hit::errormsg(_root->find(full_name),
                               "The supplied name ReporterName '",
                               rnames[i],
                               "' must contain the '/' delimiter.");
    else
      param->set()[i] = ReporterName(names[0], names[1]);
  }
}
toBool()
template<typename T > bool toBool (const std::string & , T &)
Definition at line 1668 of file Parser.C.
{
  return false;
}
Referenced by Parser::setScalarParameter().
toBool< bool >()
template<> bool toBool< bool > (const std::string & s, bool & val)
Definition at line 1674 of file Parser.C.
{
  return hit::toBool(s, &val);
}