Zapdos: moose/framework/include/geomsearch/PenetrationInfo.h File Reference
PenetrationInfo.h File Reference
Classes
class PenetrationInfo
Data structure used to hold penetration information.
Namespaces
namespace libMesh
The following methods are specializations for using the libMesh::Parallel::packed_range_* routines for std::strings.
Functions
template<>
void dataStore (std::ostream &stream, PenetrationInfo *&pinfo, void *context)
template<>
void dataLoad (std::istream &stream, PenetrationInfo *&pinfo, void *context)
Function Documentation
dataLoad()
template<> void dataLoad (std::istream & stream, PenetrationInfo *& pinfo, void * context)
Definition at line 208 of file PenetrationInfo.C.
{
  if (!context)
    mooseError("Can only load PenetrationInfo objects using a MooseMesh context!");
  // First, see if this is supposed to be NULL
  unsigned int i = 0;
  loadHelper(stream, i, context);
  if (i)
  {
    pinfo = new PenetrationInfo();
    loadHelper(stream, pinfo->_elem, context);
    loadHelper(stream, pinfo->_side_num, context);
    // Rebuild the side element.
    pinfo->_side = pinfo->_elem->build_side_ptr(pinfo->_side_num, false).release();
    loadHelper(stream, pinfo->_normal, context);
    loadHelper(stream, pinfo->_distance, context);
    loadHelper(stream, pinfo->_tangential_distance, context);
    loadHelper(stream, pinfo->_closest_point, context);
    loadHelper(stream, pinfo->_closest_point_ref, context);
    loadHelper(stream, pinfo->_closest_point_on_face_ref, context);
    loadHelper(stream, pinfo->_off_edge_nodes, context);
    loadHelper(stream, pinfo->_side_phi, context);
    loadHelper(stream, pinfo->_side_grad_phi, context);
    loadHelper(stream, pinfo->_dxyzdxi, context);
    loadHelper(stream, pinfo->_dxyzdeta, context);
    loadHelper(stream, pinfo->_d2xyzdxideta, context);
    loadHelper(stream, pinfo->_starting_elem, context);
    loadHelper(stream, pinfo->_starting_side_num, context);
    loadHelper(stream, pinfo->_starting_closest_point_ref, context);
    loadHelper(stream, pinfo->_incremental_slip, context);
    loadHelper(stream, pinfo->_accumulated_slip, context);
    loadHelper(stream, pinfo->_frictional_energy, context);
    loadHelper(stream, pinfo->_contact_force, context);
    loadHelper(stream, pinfo->_lagrange_multiplier, context);
    loadHelper(stream, pinfo->_lagrange_multiplier_slip, context);
    loadHelper(stream, pinfo->_mech_status, context);
    loadHelper(stream, pinfo->_mech_status_old, context);
    // Don't need frictional_energy_old, accumulated_slip_old, contact_force_old, or
    // locked_this_step
    // because they are always set by the constraints at the beginning of a new time step.
  }
  else
    pinfo = NULL;
}
Referenced by dataLoad< Moose::LibtorchArtificialNeuralNet >(), ReporterState< T >::loadInternal(), RestartableDataReader::readHeader(), and RedistributeProperties::redistribute().
dataStore()
template<> void dataStore (std::ostream & stream, PenetrationInfo *& pinfo, void * context)
Definition at line 156 of file PenetrationInfo.C.
{
  if (!context)
    mooseError("Can only store PenetrationInfo objects using a MooseMesh context!");
  if (pinfo)
  {
    // Store 1 so that we know that this pinfo really exists!
    unsigned int i = 1;
    storeHelper(stream, i, context);
    storeHelper(stream, pinfo->_elem, context);
    // Not storing the side element as we will need to recreate it on load
    storeHelper(stream, pinfo->_side_num, context);
    storeHelper(stream, pinfo->_normal, context);
    storeHelper(stream, pinfo->_distance, context);
    storeHelper(stream, pinfo->_tangential_distance, context);
    storeHelper(stream, pinfo->_closest_point, context);
    storeHelper(stream, pinfo->_closest_point_ref, context);
    storeHelper(stream, pinfo->_closest_point_on_face_ref, context);
    storeHelper(stream, pinfo->_off_edge_nodes, context);
    storeHelper(stream, pinfo->_side_phi, context);
    storeHelper(stream, pinfo->_side_grad_phi, context);
    storeHelper(stream, pinfo->_dxyzdxi, context);
    storeHelper(stream, pinfo->_dxyzdeta, context);
    storeHelper(stream, pinfo->_d2xyzdxideta, context);
    storeHelper(stream, pinfo->_starting_elem, context);
    storeHelper(stream, pinfo->_starting_side_num, context);
    storeHelper(stream, pinfo->_starting_closest_point_ref, context);
    storeHelper(stream, pinfo->_incremental_slip, context);
    storeHelper(stream, pinfo->_accumulated_slip, context);
    storeHelper(stream, pinfo->_frictional_energy, context);
    storeHelper(stream, pinfo->_contact_force, context);
    storeHelper(stream, pinfo->_lagrange_multiplier, context);
    storeHelper(stream, pinfo->_lagrange_multiplier_slip, context);
    storeHelper(stream, pinfo->_mech_status, context);
    storeHelper(stream, pinfo->_mech_status_old, context);
    // Don't need frictional_energy_old, accumulated_slip_old, contact_force_old, or
    // locked_this_step
    // because they are always set by the constraints at the beginning of a new time step.
  }
  else
  {
    // Store 0 so that we know that this pinfo is NULL
    unsigned int i = 0;
    storeHelper(stream, i, context);
  }
}
Referenced by dataStore< Moose::LibtorchArtificialNeuralNet >(), RedistributeProperties::redistribute(), ReporterState< T >::storeInternal(), and RestartableDataWriter::write().