Zapdos: moose/framework/include/utils/PetscDMMoose.h File Reference
PetscDMMoose.h File Reference
Functions
PetscErrorCode DMMooseRegisterAll ()
PetscErrorCode DMCreateMoose (MPI_Comm, NonlinearSystemBase &, DM *)
PetscErrorCode DMMooseReset (DM)
PetscErrorCode DMMooseSetNonlinearSystem (DM, NonlinearSystemBase &)
PetscErrorCode DMMooseGetNonlinearSystem (DM, NonlinearSystemBase *&)
PetscErrorCode DMMooseGetBlocks (DM, std::vector< std::string > &)
PetscErrorCode DMMooseGetVariables (DM, std::vector< std::string > &)
PetscErrorCode DMMooseGetSides (DM, std::set< std::string > &)
PetscErrorCode DMMooseGetUnSides (DM, std::set< std::string > &)
PetscErrorCode DMMooseGetContacts (DM, std::vector< std::pair< std::string, std::string > > &, std::vector< bool > &)
PetscErrorCode DMMooseGetUnContacts (DM, std::vector< std::pair< std::string, std::string > > &, std::vector< bool > &)
PetscErrorCode DMMooseSetBlocks (DM, const std::vector< std::string > &)
PetscErrorCode DMMooseSetVariables (DM, const std::vector< std::string > &)
PetscErrorCode DMMooseSetSides (DM, const std::set< std::string > &)
PetscErrorCode DMMooseSetUnSides (DM, const std::set< std::string > &)
PetscErrorCode DMMooseSetContacts (DM, const std::vector< std::pair< std::string, std::string > > &, const std::vector< bool > &)
PetscErrorCode DMMooseSetUnContacts (DM, const std::vector< std::pair< std::string, std::string > > &, const std::vector< bool > &)
PetscErrorCode DMMooseSetSplitNames (DM, const std::vector< std::string > &)
PetscErrorCode DMMooseGetSplitNames (DM, const std::vector< std::string > &)
PetscErrorCode DMMooseSetSplitVars (DM, const std::string &, const std::set< std::string > &)
PetscErrorCode DMMooseGetSplitVars (DM, const std::string &, std::set< std::string > &)
PetscErrorCode DMMooseSetSplitBlocks (DM, const std::string &, const std::set< std::string > &)
PetscErrorCode DMMooseGetSplitBlocks (DM, const std::string &, std::set< std::string > &)
PetscErrorCode DMMooseSetSplitSides (DM, const std::string &, const std::set< std::string > &)
PetscErrorCode DMMooseGetSplitSides (DM, const std::string &, std::set< std::string > &)
PetscErrorCode SNESUpdateDMMoose (SNES snes, PetscInt iteration)
Function Documentation
DMCreateMoose()
PetscErrorCode DMCreateMoose (MPI_Comm comm, NonlinearSystemBase & nl, DM * dm)
Definition at line 2335 of file PetscDMMoose.C.
{
  PetscErrorCode ierr;
  PetscFunctionBegin;
  ierr = DMCreate(comm, dm);
  CHKERRQ(ierr);
  ierr = DMSetType(*dm, DMMOOSE);
  CHKERRQ(ierr);
  ierr = DMMooseSetNonlinearSystem(*dm, nl);
  CHKERRQ(ierr);
  PetscFunctionReturn(0);
}
Referenced by DMCreateFieldDecomposition_Moose(), and Moose::PetscSupport::petscSetupDM().
DMMooseGetBlocks()
PetscErrorCode DMMooseGetBlocks (DM dm, std::vector< std::string > & block_names)
Definition at line 189 of file PetscDMMoose.C.
{
  PetscErrorCode ierr;
  PetscBool ismoose;
  PetscFunctionBegin;
  PetscValidHeaderSpecific(dm, DM_CLASSID, 1);
  ierr = PetscObjectTypeCompare((PetscObject)dm, DMMOOSE, &ismoose);
  CHKERRQ(ierr);
  if (!ismoose)
    LIBMESH_SETERRQ2(((PetscObject)dm)->comm,
                     PETSC_ERR_ARG_WRONG,
                     "Got DM oftype %s, not of type %s",
                     ((PetscObject)dm)->type_name,
                     DMMOOSE);
  DM_Moose * dmm = (DM_Moose *)dm->data;
  for (const auto & it : *(dmm->_block_ids))
    block_names.push_back(it.first);
  PetscFunctionReturn(0);
}
DMMooseGetContacts()
PetscErrorCode DMMooseGetContacts (DM , std::vector< std::pair< std::string, std::string > > & , std::vector< bool > &)
DMMooseGetNonlinearSystem()
PetscErrorCode DMMooseGetNonlinearSystem (DM dm, NonlinearSystemBase *& nl)
Definition at line 471 of file PetscDMMoose.C.
{
  PetscErrorCode ierr;
  PetscBool ismoose;
  PetscFunctionBegin;
  PetscValidHeaderSpecific(dm, DM_CLASSID, 1);
  ierr = PetscObjectTypeCompare((PetscObject)dm, DMMOOSE, &ismoose);
  CHKERRQ(ierr);
  if (!ismoose)
    LIBMESH_SETERRQ2(((PetscObject)dm)->comm,
                     PETSC_ERR_ARG_WRONG,
                     "Got DM oftype %s, not of type %s",
                     ((PetscObject)dm)->type_name,
                     DMMOOSE);
  DM_Moose * dmm = (DM_Moose *)(dm->data);
  nl = dmm->_nl;
  PetscFunctionReturn(0);
}
Referenced by DMMooseFunction(), DMMooseJacobian(), and DMVariableBounds_Moose().
DMMooseGetSides()
PetscErrorCode DMMooseGetSides (DM , std::set< std::string > &)
DMMooseGetSplitBlocks()
PetscErrorCode DMMooseGetSplitBlocks (DM , const std::string & , std::set< std::string > &)
DMMooseGetSplitNames()
PetscErrorCode DMMooseGetSplitNames (DM , const std::vector< std::string > &)
DMMooseGetSplitSides()
PetscErrorCode DMMooseGetSplitSides (DM , const std::string & , std::set< std::string > &)
DMMooseGetSplitVars()
PetscErrorCode DMMooseGetSplitVars (DM , const std::string & , std::set< std::string > &)
DMMooseGetUnContacts()
PetscErrorCode DMMooseGetUnContacts (DM , std::vector< std::pair< std::string, std::string > > & , std::vector< bool > &)
DMMooseGetUnSides()
PetscErrorCode DMMooseGetUnSides (DM , std::set< std::string > &)
DMMooseGetVariables()
PetscErrorCode DMMooseGetVariables (DM dm, std::vector< std::string > & var_names)
Definition at line 213 of file PetscDMMoose.C.
{
  PetscErrorCode ierr;
  PetscBool ismoose;
  PetscFunctionBegin;
  PetscValidHeaderSpecific(dm, DM_CLASSID, 1);
  ierr = PetscObjectTypeCompare((PetscObject)dm, DMMOOSE, &ismoose);
  CHKERRQ(ierr);
  if (!ismoose)
    LIBMESH_SETERRQ2(((PetscObject)dm)->comm,
                     PETSC_ERR_ARG_WRONG,
                     "Got DM oftype %s, not of type %s",
                     ((PetscObject)dm)->type_name,
                     DMMOOSE);
  DM_Moose * dmm = (DM_Moose *)(dm->data);
  for (const auto & it : *(dmm->_var_ids))
    var_names.push_back(it.first);
  PetscFunctionReturn(0);
}
DMMooseRegisterAll()
PetscErrorCode DMMooseRegisterAll ()
Definition at line 2469 of file PetscDMMoose.C.
{
  static PetscBool DMMooseRegisterAllCalled = PETSC_FALSE;
  PetscErrorCode ierr;
  PetscFunctionBegin;
  if (!DMMooseRegisterAllCalled)
  {
    ierr = DMRegister(DMMOOSE, DMCreate_Moose);
    CHKERRQ(ierr);
    DMMooseRegisterAllCalled = PETSC_TRUE;
  }
  PetscFunctionReturn(0);
}
Referenced by Moose::PetscSupport::petscSetupDM().
DMMooseReset()
PetscErrorCode DMMooseReset (DM dm)
Definition at line 1809 of file PetscDMMoose.C.
{
  PetscErrorCode ierr;
  DM_Moose * dmm = (DM_Moose *)(dm->data);
  PetscBool ismoose;
  PetscFunctionBegin;
  ierr = PetscObjectTypeCompare((PetscObject)dm, DMMOOSE, &ismoose);
  CHKERRQ(ierr);
  if (!ismoose)
    PetscFunctionReturn(0);
  if (!dmm->_nl)
    SETERRQ(PETSC_COMM_WORLD, PETSC_ERR_ARG_WRONGSTATE, "No Moose system set for DM_Moose");
  ierr = ISDestroy(&dmm->_embedding);
  CHKERRQ(ierr);
  for (auto & it : *(dmm->_splits))
  {
    DM_Moose::SplitInfo & split = it.second;
    ierr = ISDestroy(&split._rembedding);
    CHKERRQ(ierr);
    if (split._dm)
    {
      ierr = DMMooseReset(split._dm);
      CHKERRQ(ierr);
    }
  }
  dm->setupcalled = PETSC_FALSE;
  PetscFunctionReturn(0);
}
Referenced by DMMooseReset(), and SNESUpdateDMMoose().
DMMooseSetBlocks()
PetscErrorCode DMMooseSetBlocks (DM , const std::vector< std::string > &)
DMMooseSetContacts()
PetscErrorCode DMMooseSetContacts (DM , const std::vector< std::pair< std::string, std::string > > & , const std::vector< bool > &)
DMMooseSetNonlinearSystem()
PetscErrorCode DMMooseSetNonlinearSystem (DM dm, NonlinearSystemBase & nl)
Definition at line 237 of file PetscDMMoose.C.
{
  PetscErrorCode ierr;
  PetscBool ismoose;
  PetscFunctionBegin;
  PetscValidHeaderSpecific(dm, DM_CLASSID, 1);
  ierr = PetscObjectTypeCompare((PetscObject)dm, DMMOOSE, &ismoose);
  CHKERRQ(ierr);
  if (!ismoose)
    LIBMESH_SETERRQ2(((PetscObject)dm)->comm,
                     PETSC_ERR_ARG_WRONG,
                     "Got DM oftype %s, not of type %s",
                     ((PetscObject)dm)->type_name,
                     DMMOOSE);
  if (dm->setupcalled)
    SETERRQ(((PetscObject)dm)->comm,
            PETSC_ERR_ARG_WRONGSTATE,
            "Cannot reset the NonlinearSystem after DM has been set up.");
  DM_Moose * dmm = (DM_Moose *)(dm->data);
  dmm->_nl = &nl;
  PetscFunctionReturn(0);
}
Referenced by DMCreateMoose().
DMMooseSetSides()
PetscErrorCode DMMooseSetSides (DM dm, const std::set< std::string > & sides)
Definition at line 332 of file PetscDMMoose.C.
{
  PetscErrorCode ierr;
  DM_Moose * dmm = (DM_Moose *)dm->data;
  PetscBool ismoose;
  PetscFunctionBegin;
  PetscValidHeaderSpecific(dm, DM_CLASSID, 1);
  ierr = PetscObjectTypeCompare((PetscObject)dm, DMMOOSE, &ismoose);
  CHKERRQ(ierr);
  if (!ismoose)
    LIBMESH_SETERRQ2(PETSC_COMM_SELF,
                     PETSC_ERR_ARG_WRONG,
                     "Got DM oftype %s, not of type %s",
                     ((PetscObject)dm)->type_name,
                     DMMOOSE);
  if (dm->setupcalled)
    SETERRQ(PETSC_COMM_SELF, PETSC_ERR_ARG_WRONGSTATE, "Not for an already setup DM");
  if (dmm->_sides)
    delete dmm->_sides;
  dmm->_sides = new std::set<std::string>(sides);
  PetscFunctionReturn(0);
}
Referenced by DMSetFromOptions_Moose().
DMMooseSetSplitBlocks()
PetscErrorCode DMMooseSetSplitBlocks (DM , const std::string & , const std::set< std::string > &)
DMMooseSetSplitNames()
PetscErrorCode DMMooseSetSplitNames (DM dm, const std::vector< std::string > & split_names)
Definition at line 494 of file PetscDMMoose.C.
{
  PetscErrorCode ierr;
  PetscBool ismoose;
  PetscFunctionBegin;
  PetscValidHeaderSpecific(dm, DM_CLASSID, 1);
  ierr = PetscObjectTypeCompare((PetscObject)dm, DMMOOSE, &ismoose);
  CHKERRQ(ierr);
  if (!ismoose)
    LIBMESH_SETERRQ2(((PetscObject)dm)->comm,
                     PETSC_ERR_ARG_WRONG,
                     "Got DM oftype %s, not of type %s",
                     ((PetscObject)dm)->type_name,
                     DMMOOSE);
  DM_Moose * dmm = (DM_Moose *)(dm->data);
  if (dmm->_splits)
  {
    for (auto & it : *(dmm->_splits))
    {
      ierr = DMDestroy(&(it.second._dm));
      CHKERRQ(ierr);
      ierr = ISDestroy(&(it.second._rembedding));
      CHKERRQ(ierr);
    }
    delete dmm->_splits;
    dmm->_splits = LIBMESH_PETSC_NULLPTR;
  }
  if (dmm->_splitlocs)
  {
    delete dmm->_splitlocs;
    dmm->_splitlocs = LIBMESH_PETSC_NULLPTR;
  }
  dmm->_splits = new std::map<std::string, DM_Moose::SplitInfo>();
  dmm->_splitlocs = new std::multimap<std::string, unsigned int>();
  for (unsigned int i = 0; i < split_names.size(); ++i)
  {
    DM_Moose::SplitInfo info;
    info._dm = LIBMESH_PETSC_NULLPTR;
    info._rembedding = LIBMESH_PETSC_NULLPTR;
    std::string name = split_names[i];
    (*dmm->_splits)[name] = info;
    dmm->_splitlocs->insert(std::make_pair(name, i));
  }
  PetscFunctionReturn(0);
}
Referenced by DMSetFromOptions_Moose().
DMMooseSetSplitSides()
PetscErrorCode DMMooseSetSplitSides (DM , const std::string & , const std::set< std::string > &)
DMMooseSetSplitVars()
PetscErrorCode DMMooseSetSplitVars (DM , const std::string & , const std::set< std::string > &)
DMMooseSetUnContacts()
PetscErrorCode DMMooseSetUnContacts (DM , const std::vector< std::pair< std::string, std::string > > & , const std::vector< bool > &)
DMMooseSetUnSides()
PetscErrorCode DMMooseSetUnSides (DM dm, const std::set< std::string > & unsides)
Definition at line 359 of file PetscDMMoose.C.
{
  PetscErrorCode ierr;
  DM_Moose * dmm = (DM_Moose *)dm->data;
  PetscBool ismoose;
  PetscFunctionBegin;
  PetscValidHeaderSpecific(dm, DM_CLASSID, 1);
  ierr = PetscObjectTypeCompare((PetscObject)dm, DMMOOSE, &ismoose);
  CHKERRQ(ierr);
  if (!ismoose)
    LIBMESH_SETERRQ2(PETSC_COMM_SELF,
                     PETSC_ERR_ARG_WRONG,
                     "Got DM oftype %s, not of type %s",
                     ((PetscObject)dm)->type_name,
                     DMMOOSE);
  if (dm->setupcalled)
    SETERRQ(PETSC_COMM_SELF, PETSC_ERR_ARG_WRONGSTATE, "Not for an already setup DM");
  if (dmm->_sides)
    delete dmm->_sides;
  dmm->_unsides = new std::set<std::string>(unsides);
  PetscFunctionReturn(0);
}
Referenced by DMSetFromOptions_Moose().
DMMooseSetVariables()
PetscErrorCode DMMooseSetVariables (DM , const std::vector< std::string > &)
SNESUpdateDMMoose()
PetscErrorCode SNESUpdateDMMoose (SNES snes, PetscInt iteration)
Definition at line 2415 of file PetscDMMoose.C.
{
  /* This is called any time the structure of the problem changes in a way that affects the Jacobian
     sparsity pattern.
     For example, this may happen when NodeFaceConstraints change Jacobian's sparsity pattern based
     on newly-detected Penetration.
     In that case certain preconditioners (e.g., PCASM) will not work, unless we tell them that the
     sparsity pattern has changed.
     For now we are rebuilding the whole KSP, when necessary.
  */
  PetscErrorCode ierr;
  DM dm;
  KSP ksp;
  const char * prefix;
  MPI_Comm comm;
  PC pc;
  PetscFunctionBegin;
  if (iteration)
  {
    /* TODO: limit this only to situations when displaced (un)contact splits are present, as is
     * DisplacedProblem(). */
    ierr = SNESGetDM(snes, &dm);
    CHKERRQ(ierr);
    ierr = DMMooseReset(dm);
    CHKERRQ(ierr);
    ierr = DMSetUp(dm);
    CHKERRQ(ierr);
    ierr = SNESGetKSP(snes, &ksp);
    CHKERRQ(ierr);
    /* Should we rebuild the whole KSP? */
    ierr = PetscObjectGetOptionsPrefix((PetscObject)ksp, &prefix);
    CHKERRQ(ierr);
    ierr = PetscObjectGetComm((PetscObject)ksp, &comm);
    CHKERRQ(ierr);
    ierr = PCCreate(comm, &pc);
    CHKERRQ(ierr);
    ierr = PCSetDM(pc, dm);
    CHKERRQ(ierr);
    ierr = PCSetOptionsPrefix(pc, prefix);
    CHKERRQ(ierr);
    ierr = PCSetFromOptions(pc);
    CHKERRQ(ierr);
    ierr = KSPSetPC(ksp, pc);
    CHKERRQ(ierr);
    ierr = PCDestroy(&pc);
    CHKERRQ(ierr);
  }
  PetscFunctionReturn(0);
}