Zapdos: moose/framework/src/reporters/ReporterMode.C File Reference
ReporterMode.C File Reference
Variables
const ReporterMode REPORTER_MODE_UNSET ("UNSET")
const ReporterMode REPORTER_MODE_ROOT ("ROOT")
const ReporterMode REPORTER_MODE_REPLICATED ("REPLICATED")
const ReporterMode REPORTER_MODE_DISTRIBUTED ("DISTRIBUTED")
Variable Documentation
REPORTER_MODE_DISTRIBUTED
const ReporterMode REPORTER_MODE_DISTRIBUTED("DISTRIBUTED") ("DISTRIBUTED")
Referenced by AccumulateReporter::declareAccumulateHelper(), VectorPostprocessor::declareVector(), ReporterContext< T >::finalize(), ReporterPositions::initialize(), ReporterTimes::initialize(), MultiAppCloneReporterTransfer::initialSetup(), CSV::output(), ReporterContext< T >::ReporterContext(), and ReporterGatherContext< T >::ReporterGatherContext().
REPORTER_MODE_REPLICATED
const ReporterMode REPORTER_MODE_REPLICATED("REPLICATED") ("REPLICATED")
Referenced by AccumulateReporter::declareAccumulateHelper(), IterationInfo::declareHelper(), VectorPostprocessor::declareVector(), ReporterContext< T >::finalize(), ReporterBroadcastContext< T >::finalize(), ReporterScatterContext< T >::finalize(), VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), MultiAppReporterTransfer::initialSetup(), and ReporterContext< T >::ReporterContext().
REPORTER_MODE_ROOT
const ReporterMode REPORTER_MODE_ROOT("ROOT") ("ROOT")
Referenced by AccumulateReporter::declareAccumulateHelper(), VectorPostprocessor::declareVector(), ReporterContext< T >::finalize(), ReporterGatherContext< T >::finalize(), PostprocessorInterface::getPostprocessorValueByNameInternal(), VectorPostprocessorInterface::getVectorPostprocessorByNameHelper(), MultiAppCloneReporterTransfer::initialSetup(), JSONOutput::outputReporters(), ReporterBroadcastContext< T >::ReporterBroadcastContext(), ReporterContext< T >::ReporterContext(), ReporterScatterContext< T >::ReporterScatterContext(), and SolutionInvalidityReporter::SolutionInvalidityReporter().
REPORTER_MODE_UNSET
const ReporterMode REPORTER_MODE_UNSET("UNSET") ("UNSET")
Referenced by AccumulateReporter::declareAccumulateHelper(), Postprocessor::declareValue(), Reporter::declareValue(), Reporter::declareValueByName(), ReporterBroadcastContext< T >::finalize(), ReporterScatterContext< T >::finalize(), ReporterGatherContext< T >::finalize(), ReporterInterface::getReporterValue(), ReporterInterface::getReporterValueByName(), and ReporterContextBase::init().