Zapdos: moose/framework/src/restart/RestartableEquationSystems.C File Reference
RestartableEquationSystems.C File Reference
Functions
void dataStore (std::ostream &stream, RestartableEquationSystems &res, void *)
void dataLoad (std::istream &stream, RestartableEquationSystems &res, void *)
void dataStore (std::ostream &stream, RestartableEquationSystems::EquationSystemsHeader &header, void *)
void dataLoad (std::istream &stream, RestartableEquationSystems::EquationSystemsHeader &header, void *)
void dataStore (std::ostream &stream, RestartableEquationSystems::SystemHeader &header, void *)
void dataLoad (std::istream &stream, RestartableEquationSystems::SystemHeader &header, void *)
void dataStore (std::ostream &stream, RestartableEquationSystems::VariableHeader &header, void *)
void dataLoad (std::istream &stream, RestartableEquationSystems::VariableHeader &header, void *)
void dataStore (std::ostream &stream, RestartableEquationSystems::VectorHeader &header, void *)
void dataLoad (std::istream &stream, RestartableEquationSystems::VectorHeader &header, void *)
Function Documentation
dataLoad() [1/5]
void dataLoad (std::istream & stream, RestartableEquationSystems & res, void *)
Definition at line 384 of file RestartableEquationSystems.C.
{
  res.load(stream);
}
Referenced by dataLoad(), RestartableEquationSystems::load(), and RestartableEquationSystems::restore().
dataLoad() [2/5]
void dataLoad (std::istream & stream, RestartableEquationSystems::EquationSystemsHeader & header, void *)
Definition at line 397 of file RestartableEquationSystems.C.
{
  dataLoad(stream, header.systems, nullptr);
  dataLoad(stream, header.data_size, nullptr);
}
dataLoad() [3/5]
void dataLoad (std::istream & stream, RestartableEquationSystems::SystemHeader & header, void *)
Definition at line 413 of file RestartableEquationSystems.C.
{
  dataLoad(stream, header.name, nullptr);
  dataLoad(stream, header.type, nullptr);
  dataLoad(stream, header.variables, nullptr);
  dataLoad(stream, header.vectors, nullptr);
}
dataLoad() [4/5]
void dataLoad (std::istream & stream, RestartableEquationSystems::VariableHeader & header, void *)
Definition at line 428 of file RestartableEquationSystems.C.
{
  dataLoad(stream, header.name, nullptr);
  dataLoad(stream, header.type, nullptr);
}
dataLoad() [5/5]
void dataLoad (std::istream & stream, RestartableEquationSystems::VectorHeader & header, void *)
Definition at line 443 of file RestartableEquationSystems.C.
{
  dataLoad(stream, header.name, nullptr);
  dataLoad(stream, header.projections, nullptr);
  dataLoad(stream, header.type, nullptr);
  dataLoad(stream, header.variable_offset, nullptr);
}
dataStore() [1/5]
void dataStore (std::ostream & stream, RestartableEquationSystems & res, void *)
Definition at line 378 of file RestartableEquationSystems.C.
{
  res.store(stream);
}
Referenced by dataStore(), and RestartableEquationSystems::store().
dataStore() [2/5]
void dataStore (std::ostream & stream, RestartableEquationSystems::EquationSystemsHeader & header, void *)
Definition at line 390 of file RestartableEquationSystems.C.
{
  dataStore(stream, header.systems, nullptr);
  dataStore(stream, header.data_size, nullptr);
}
dataStore() [3/5]
void dataStore (std::ostream & stream, RestartableEquationSystems::SystemHeader & header, void *)
Definition at line 404 of file RestartableEquationSystems.C.
{
  dataStore(stream, header.name, nullptr);
  dataStore(stream, header.type, nullptr);
  dataStore(stream, header.variables, nullptr);
  dataStore(stream, header.vectors, nullptr);
}
dataStore() [4/5]
void dataStore (std::ostream & stream, RestartableEquationSystems::VariableHeader & header, void *)
Definition at line 422 of file RestartableEquationSystems.C.
{
  dataStore(stream, header.name, nullptr);
  dataStore(stream, header.type, nullptr);
}
dataStore() [5/5]
void dataStore (std::ostream & stream, RestartableEquationSystems::VectorHeader & header, void *)
Definition at line 435 of file RestartableEquationSystems.C.
{
  dataStore(stream, header.name, nullptr);
  dataStore(stream, header.projections, nullptr);
  dataStore(stream, header.type, nullptr);
  dataStore(stream, header.variable_offset, nullptr);
}