Zapdos: PointIndexedMap Struct Reference
PointIndexedMap Struct Reference
An unordered map indexed by Point, eg 3 floating point numbers Because floating point rounding errors can affect the hashing, eg the binning of values, we may need to look near a Point/key for where the initial value was stored.
#include <PointIndexedMap.h>
Classes
struct hash_point
Public Member Functions
PointIndexedMap (const Point &mesh_max_coords)
Point getRoundedPoint (const Point &p) const
Normalize, expand then round a point to create local bins.
Number & operator[] (Point p)
unsigned int hasKey (Point p)
std::unordered_map< Point, Number, hash_point >::const_iterator find (const Point &pt) const
bool attempt_find (const Point &p, Real dx, Real dy, Real dz, std::unordered_map< Point, Number, hash_point >::const_iterator &out) const
std::unordered_map< Point, Number, hash_point >::const_iterator end () const
Public Attributes
std::unordered_map< Point, Number, hash_point > base_map
The container indexed by points.
Point normalization
Normalization factors used to scale points before insertions/comparisons.
Detailed Description
An unordered map indexed by Point, eg 3 floating point numbers Because floating point rounding errors can affect the hashing, eg the binning of values, we may need to look near a Point/key for where the initial value was stored.
Definition at line 19 of file PointIndexedMap.h.
Constructor & Destructor Documentation
PointIndexedMap()
PointIndexedMap::PointIndexedMap (const Point & mesh_max_coords) inline
Definition at line 21 of file PointIndexedMap.h.
  {
    for (auto i : make_range(LIBMESH_DIM))
      normalization(i) =
          MooseUtils::absoluteFuzzyEqual(mesh_max_coords(i), 0) ? 1 : mesh_max_coords(i);
  }
Member Function Documentation
attempt_find()
bool PointIndexedMap::attempt_find (const Point & p, Real dx, Real dy, Real dz, std::unordered_map< Point, Number, hash_point >::const_iterator & out) const inline
Definition at line 117 of file PointIndexedMap.h.
  {
    // Some epsilon to move the point by.
    // There is no multiplicative epsilon that will reliably change the last decimal
    const auto eps = 1e-13;
    const auto shifted_rp = getRoundedPoint(p + Point(dx * eps * normalization(0),
                                                      dy * eps * normalization(1),
                                                      dz * eps * normalization(2)));
    out = base_map.find(shifted_rp);
    if (out != base_map.end())
      return true;
    return false;
  }
Referenced by find().
end()
std::unordered_map< Point, Number, hash_point >::const_iterator PointIndexedMap::end () const inline
Definition at line 135 of file PointIndexedMap.h.
  {
    return base_map.end();
  }
Referenced by GeneralFieldTransfer::CachedData< Output >::eval_at_node(), GeneralFieldTransfer::CachedData< Output >::eval_at_point(), hasKey(), and operator[]().
find()
std::unordered_map< Point, Number, hash_point >::const_iterator PointIndexedMap::find (const Point & pt) const inline
Definition at line 89 of file PointIndexedMap.h.
  {
    const auto rp = getRoundedPoint(pt);
    auto it = base_map.find(rp);
    if (it != base_map.end())
      return it;
    else
    {
      // Search the point with coordinates rounded down to origin
      auto rounded = base_map.find(rp);
      if (rounded != base_map.end())
        return rounded;
      // To store the output of tentative searches
      std::unordered_map<Point, Number, hash_point>::const_iterator out;
      // Search in all directions around
      for (int i : make_range(2))
        for (int j : make_range(2))
          for (int k : make_range(2))
            if (attempt_find(pt, 2 * i - 1, 2 * j - 1, 2 * k - 1, out))
              return out;
      return base_map.end();
    }
  }
Referenced by GeneralFieldTransfer::CachedData< Output >::eval_at_node(), GeneralFieldTransfer::CachedData< Output >::eval_at_point(), hasKey(), and operator[]().
getRoundedPoint()
Point PointIndexedMap::getRoundedPoint (const Point & p) const inline
Normalize, expand then round a point to create local bins.
normalize the point by dividing by the meshes max (non-zero) absolute coordinates
multiply the result by 1e12 and round, which keeps a fixed number of digits
Definition at line 33 of file PointIndexedMap.h.
  {
    // We cant support coordinates too far from the normalization point
    mooseAssert(p(0) / normalization(0) < 1 && p(1) / normalization(1) < 1 &&
                    p(2) / normalization(2) < 1,
                "Point coordinates for indexing must be normalized below 1. "
                "Point: "
                    << p << " normalization: " << normalization);
    std::vector<Real> rounded_p{round(p(0) / normalization(0) * pow(10, 12)),
                                round(p(1) / normalization(1) * pow(10, 12)),
                                round(p(2) / normalization(2) * pow(10, 12))};
    return Point(rounded_p[0], rounded_p[1], rounded_p[2]);
  }
Referenced by attempt_find(), find(), and operator[]().
hasKey()
unsigned int PointIndexedMap::hasKey (Point p) inline
Definition at line 80 of file PointIndexedMap.h.
  {
    auto it = find(p);
    if (it != end())
      return true;
    else
      return false;
  }
Referenced by MultiAppGeneralFieldTransfer::cacheIncomingInterpVals().
operator[]()
Number & PointIndexedMap::operator[] (Point p) inline
Definition at line 68 of file PointIndexedMap.h.
  {
    auto it = find(p);
    if (it != end())
      return const_cast<Number &>(it->second);
    else
    {
      const auto rp = getRoundedPoint(p);
      return base_map[rp];
    }
  }
Member Data Documentation
base_map
std::unordered_map<Point, Number, hash_point> PointIndexedMap::base_map
The container indexed by points.
Definition at line 63 of file PointIndexedMap.h.
Referenced by attempt_find(), end(), find(), and operator[]().
normalization
Point PointIndexedMap::normalization
Normalization factors used to scale points before insertions/comparisons.
Definition at line 66 of file PointIndexedMap.h.
Referenced by attempt_find(), getRoundedPoint(), and PointIndexedMap().
The documentation for this struct was generated from the following file:
moose/framework/include/utils/PointIndexedMap.h